### ISSUE TITLE
incorrect type for TaskDefinition.frequency?

### ISSUE THREAD

**Issue by zhammer** [backstage/backstage#10008]
https://github.com/backstage/backstage/blob/1d3bbbc5a1b337cdcd7da4d58ed470a4d60fef43/packages/backend-tasks/src/tasks/types.ts#L77-L80

hi! the docs for `TaskDefinition.frequency` say "If no value is given for this field then the task will only be invoked once (on any worker) and then unscheduled automatically." the type on this field is a non-nullable `Duration`. the same goes for `TaskDefinition.timeout`.

`TaskDefinition.initialDelay`, on the other hand, is an optional field.

should `TaskDefinition.frequenzy` and `TaskDefinition.timeout` be updated to nullable fields?

**Comment by zhammer** [comment]
actually when i left this field empty i got the following error:
`[1] Backend failed to start up, TypeError: Cannot read property 'toISO' of null`

**Comment by freben** [comment]
Ah, no that's a remnant, single-run isn't supported so it's the description that's wrong. Maybe contribute a fix? 🙌

**Comment by zhammer** [comment]
@freben sure thing :) 

why was this removed as a feature btw? just want to ask before i set our ldap processor to a frequency of 100 years to fake a single-run

**Comment by freben** [comment]
It was never built - the initial PR that added the package first attempted to support single runs which explains the comment, but we cut that out before merge to simplify due to no immediate need for the feature. Just forgot to update the comment then

**Comment by zhammer** [comment]
Ah got it
