### ISSUE TITLE
Unable to Create Backstage App

### ISSUE THREAD

**Issue by adamo57** [backstage/backstage#10021]
## Expected Behavior

When I run `npx @backstage/create-app` I expect an app to be generated for me.

## Actual Behavior

```shell
> npx @backstage/create-app
npx: installed 70 in 5.153s
Unexpected token ...
```

## Steps to Reproduce

1. Run `npx @backstage/create-app`

## Context

I am trying to set up the backstage app for the first time on this machine.

## Your Environment

`Linux  5.13.19-2-MANJARO #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64 GNU/Linux`

- Browser Information: 

N/A

- Output of `yarn backstage-cli info`: 

N/A

**Comment by dipakparmar** [comment]
@adamo57 could you please provide more info about your environment so someone can help assist. 

Your node.js version, npm version. Any special setup you might have

Also, you can try running the command in an isolated environment like a docker container to see if that also gives an error. 

I have tested on my end with npm `6.14.15` and node `v14.18.2` it works fine.

**Comment by adamo57** [comment]
@dipakparmar Thank you for responding. I can totally give the docker container a shot. Thats a great idea.

```shell
➜  ~ npm -v
5.0.0
➜  ~ node -v
v8.0.0
```

**Comment by adamo57** [comment]
@dipakparmar Please disregard. This was an issue with my node version being incorrect.
