### ISSUE TITLE
Not able to use hooks (useApi) inside customTechRadar component which results in inability to externalise the backend url and 3rd party credentials

### ISSUE THREAD

**Issue by ankitapandey1106** [backstage/backstage#10054]
I have created a customeTechRadar which extends TechRadarApi, calls stash to fetch the data to be fed in the tech radar response.
I had to use proxy to call the stash url but now to externalise the backend url and stash creds, I am trying to use useApi to read configs from app-config.yaml but it gives me error for incorrect use of hook, which makes sense as I am using it inside a class rather than functional component. I tried creating separate functional component and use it within but no luck. is there a way that this can be achieved ? or it's a feature we can't use. 
It will be helpful if I can get some references to this.
Thank you!

**Comment by freben** [comment]
When you create an API override, you have the ability to declare what dependencies (to other APIs) that you need. Then you just pass those into your class. See this file for a ton of examples: https://github.com/backstage/backstage/blob/1bd8972efa165d0aa72bb5d94bc74c22258d708e/packages/app-defaults/src/defaults/apis.ts#L152

**Comment by ankitapandey1106** [comment]
> When you create an API override, you have the ability to declare what dependencies (to other APIs) that you need. Then you just pass those into your class. See this file for a ton of examples:
> 
> https://github.com/backstage/backstage/blob/1bd8972efa165d0aa72bb5d94bc74c22258d708e/packages/app-defaults/src/defaults/apis.ts#L152

Thanks a lot! this works
