### ISSUE TITLE
async load() Function of customTechRadarApi not called on selection

### ISSUE THREAD

**Issue by ankitapandey1106** [backstage/backstage#10087]
I have extended TechRadar plugin to create a customTechRadarApi which supports multiple tech radars depending on a drop down that I have provided on UI, so depending on user selection from the drop down, that id is passed rom RadraPage to RadarComponent to the load method of customTechRadarApi  corresponding tech radar is loaded on runtime by fetching the data from respective API.

The issue I am facing here is, when user selects a different option from the drop down on the UI, the id gets passed from the RadarPage to RadarComponent but the load method is not invoked again.
Do we need to do anything additional to make a call to load method again or it's not allowed?
Any reference to this will be helpful.

Pasting some images for ref below -
![image](https://user-images.githubusercontent.com/32476575/157432305-7a055475-6174-4ead-930d-db6dba6ef225.png)

On page reload -
![image](https://user-images.githubusercontent.com/32476575/157432837-648dc294-2a2b-49da-b0bc-b2a444eca79d.png)

On changing the selection inside the drop down -
![image](https://user-images.githubusercontent.com/32476575/157432934-179e953c-0f01-4de4-9484-358463806715.png)

Here there is no call to load method

**Comment by ankitapandey1106** [comment]
This was resolved by passing in the load function call trigger

**Comment by aaronrumao** [comment]
Hi @ankitapandey1106 
We are trying to implement similar thing, Do you have any example on how we can achieve multiple tech-radars?
