### ISSUE TITLE
AwsS3UrlReader does not allow dots (.) in the bucket name

### ISSUE THREAD

**Issue by bryce-od** [backstage/backstage#10127]
## Actual Behavior

`AwsS3UrlReader` should be able to parse an s3 bucket with `.` as part of the bucket name, for example:
`https://my.bucket.name.s3.ap-southeast-2.amazonaws.com/pathname`

as per aws bucket naming rules:
> Bucket names can consist only of lowercase letters, numbers, dots (.), and hyphens (-).
https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html

## What is happening?
It throws the Error `"invalid AWS S3 URL, cannot parse region from host in ${url}"`

the lines of code
```
    let { host, pathname } = new URL(url);
    ....
    [bucket] = host.split(".");
    
    const match = host.match(/^s3\.([a-z\d-]+)\.amazonaws\.com$/);
    if (!match) {
      throw new Error(
        `invalid AWS S3 URL, cannot parse region from host in ${url}`,
      );
    }
``` 

## Steps to Reproduce

`await reader.readTree("https://my.bucket.name.s3.ap-southeast-2.amazonaws.com/pathname");`

throws
```
error Could not retrieve file tree from S3; caused by Error: invalid AWS S3 URL, cannot parse region from host in https://my.bucket.name.s3.ap-southeast-2.amazonaws.com/pathname type=plugin name=Error cause=Error: invalid AWS S3 URL, cannot parse region from host in https://my.bucket.name.s3.ap-southeast-2.amazonaws.com/pathname stack=Error: Could not retrieve file tree from S3; caused by Error: invalid AWS S3 URL, cannot parse region from host in https://my.bucket.name.s3.ap-southeast-2.amazonaws.com/pathname
```

## Context

I believe the issue was introduced when the `AwsS3UrlReader` was refactored in this commit:
https://github.com/backstage/backstage/commit/bc78cc3dca4f8662bc122e8dd4d4875d43bc7269

![Screen Shot 2022-03-11 at 5 21 33 pm](https://user-images.githubusercontent.com/85923137/157813701-0ec7063e-06b8-47af-ae99-e93b025223cf.png)

There is a workaround if you enable `s3ForcePathStyle` and the URL becomes:
`https://s3.ap-southeast-2.amazonaws.com/my.bucket.name/pathname`

```
  awsS3:
    - host: ap-southeast-2.amazonaws.com
      s3ForcePathStyle: true
```

**Comment by freben** [comment]
Oh, that's silly. Thanks for the nicely detailed report. Are you up for trying to submit a fix? 🙌

**Comment by freben** [comment]
I made a fix instead ^

**Comment by bryce-od** [comment]
Thanks @freben!
