### ISSUE TITLE
Persist starred entities in database

### ISSUE THREAD

**Issue by shailahir** [backstage/backstage#10121]
Currently starred entities are getting stored in local storage of the browser. So if a user star an entity in one browser and opens the backstage in another browser, the starred entities does not show. It is in that browser only.

## Feature Suggestion

If we can store the starred entities in the database. So that the starred entities would be available all the time regardless of the browser.

## Possible Implementation
Maybe create a backstage backend plugin or improve existing service to store the information about starred entities in the database.

## Context
![Screenshot 2022-03-11 092425](https://user-images.githubusercontent.com/31934874/157799072-cf65ada7-ece5-46a3-bb97-38688cd32f8b.png)

**Comment by shailahir** [comment]
@freben

**Comment by dschwank** [comment]
Sorry for the late feedback - yeah, we sync all starred entities to our DB as well.
If there is interest in the community, we could check if we can make it generic and contribute it to the community.

**Comment by shailahir** [comment]
We would be very grateful if you can contribute it.

**Comment by shailendra-ahir-cbre** [comment]
While implementing, will it have its own database (plugin_bookmarks) or we can use any other existing database.

**Comment by freben** [comment]
Their DIY approach probably involves supplying a custom implementation of the `starredEntitiesApiRef` that handles storage in some way that made sense to them specifically.

If we want to make a persisted storage for this as part of the open source offering, we probably would want to make a general user-settings-backend plugin or something like that, which has its own database, and which different plugins can leverage to store per-user data. It's a bit of a larger undertaking.

Another approach would be to make starred entities as a one-off unique feature inside the catalog itself, adding new endpoints to its REST API to toggle starred etc on a per-entity basis. Still, also a bit of work.

**Comment by Rugvip** [comment]
Noting that since the `starredEntitiesApiRef` was added we have now updated the `StorageApi` to make it possible to implement the async update that was previously a bit tricky to do. That is, if we add a `StorageApi` implementation with remote storage, we'd cover this use-case too.

**Comment by dschwank** [comment]
Yeah, it's exactly what @Rugvip & @freben mentioned. We added a new backend API and wrote a custom `BackendStarredEntitiesApi` which we use as `starredEntitiesApiRef`.

@shailahir & @shailendra-ahir-cbre - will push the topic in the next days, thus we hopefully contribute it in the near future.

**Comment by dschwank** [comment]
@shailahir & @shailendra-ahir-cbre thanks for the patience.

Short update - we just moved it to the upper part of our backlog. Can't promise a precise date, but chances are high that there is a contribution in the next 2 weeks from @backstage/sda-se-reviewers 🤞

**Comment by shailendra-ahir-cbre** [comment]
Is it available in stable release ?

**Comment by dschwank** [comment]
> but chances are high that there is a contribution in the next 2 weeks

The chances were high, but not high enough - like always in software dev there were other topics rushing in. So as you already noticed, it didn't work out.
But good news, we started this week with the transformation. In case there are no interruptions, the PR should be opened within the next week.

Thanks for waiting @shailendra-ahir-cbre . Have a nice weekend 👋

**Comment by dschwank** [comment]
Thanks for being so patient @shailendra-ahir-cbre

We finally had the time and opened the PR to persist the starred entities. Please have a look and feel free to give feedback!
https://github.com/backstage/backstage/pull/13327

**Comment by shailendra-ahir-cbre** [comment]
Thanks a lot @dschwank

**Comment by dschwank** [comment]
@freben as https://github.com/backstage/backstage/pull/13570 is merged, we could close this one - right?

**Comment by Rugvip** [comment]
Yep, thank you! 👍
