### ISSUE TITLE
[kubernetes-backend-plugin] per-user authentication for AWS auth provider when using federated identities

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#10142]
## Feature Suggestion

The current `aws` auth provider for the kubernetes-backend plugin allows Backstage to surface k8s objects from clusters using [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator), which is neat! However, it does so by using a static/fixed IAM role/account to authenticate every call to k8s. Effectively the same role will be used to fetch data from k8s, regardless of the user accessing the kubernetes plugin!

The `google` auth provider, on the other hand, has the kubernetes and kubernetes-backend plugins collaborating so that the user is prompted to log in to Google on demand, and with the resulting access token Backstage authenticates as _that particular user_ when making calls to k8s. In contrast, the `aws` provider almost seems like a [confused deputy](https://en.wikipedia.org/wiki/Confused_deputy_problem)! Wouldn't it be cool if Backstage could have the same fine-grained respect for access control when accessing aws-iam-authenticated clusters as it does when accessing, say, GKE clusters?

### Problem - AWS identities are not always federated

GKE clusters uniformly use OIDC authentication, and you can request a special scope from accounts.google.com just for accessing them. AWS APIs, on the other hand, authenticate with the AWS-specific 'security credential' (access key ID/secret access key/security token) mechanism, and IAM identities are not necessarily neatly federated with OIDC -- for example, access to your AWS account could always be brokered by a username/password. There's no secure way for Backstage to act on behalf of such users.

However, in the case when your AWS account uses [web identity federation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_oidc.html), I _think_ it should always be possible to retrieve a user's identity via the [GetCallerIdentity action](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html) - which is [already being done](https://github.com/backstage/backstage/blob/97e98ac7e4a8f83fb63cb7876c9119d1228465b4/plugins/kubernetes-backend/src/kubernetes-auth-translator/AwsIamKubernetesAuthTranslator.ts#L100) by Backstage.

### Values-file structure

What I can imagine is an app-config a bit like

```yaml
auth:
  providers:
    aws-oidc:
      # ... same config options as the generic oidc provider ...
kubernetes:
  clusterLocatorMethods:
  - type: config
    clusters:
      - name: <cluster name>
        url: <apiserver URL>
        authProvider: aws-oidc
```

alternatively -- rather than introducing a provider type for the auth plugins -- the `clusters` entry could be smart enough to allow any of the existing OIDC-compatible providers (like `auth0`, `gitlab`, `google`, etc) to be specified.

### User Experience

When you open the kubernetes tab for a service, you get the login popup; you click the log in button for this as-yet-undefined auth provider, finish up the OAuth2 authorization flow.

The problem is that at this point, all you have is an OIDC ID token, and you need a bit more data to effectively make a GetCallerIdentity request with creds specific to the federated user to whom the token belongs.

### specify role ARN in app-config and use [`sts:AssumeRoleWithWebIdentity`](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html)

The only potentially-awkward part here is that folks deploying Backstage would need to configure an IAM role out-of-band -- but they were probably doing this already anyway 😁 

The cluster config could have an `assumeRole` field whose value is the ARN for a role that is capable of calling GetCallerIdentity. If I'm not mistaken, this config parameter [already exists](https://github.com/backstage/backstage/blob/97e98ac7e4a8f83fb63cb7876c9119d1228465b4/plugins/kubernetes-backend/src/types/types.ts#L145), but isn't documented. Then instead of calling `assumeRole` with raw security creds like [this](https://github.com/backstage/backstage/blob/97e98ac7e4a8f83fb63cb7876c9119d1228465b4/plugins/kubernetes-backend/src/kubernetes-auth-translator/AwsIamKubernetesAuthTranslator.ts#L73), the kubernetes-backend could call `assumeRoleWithWebIdentity` with the OIDC ID token passed from the frontend following the authorization flow.

## Context

I didn't realize this section was down here and kinda threaded the context throughout the sections above; if it's better to keep the above sections more focused and tactical and leave the "narrative" part down here, I can revise!

**Comment by benjdlambert** [comment]
@mclarke47 for visibility.

**Comment by mclarke47** [comment]
Was this completed?

**Comment by ccodreanu** [comment]
I think this one and https://github.com/backstage/backstage/issues/10035 are related
