### ISSUE TITLE
(Feat): Support adding labels to Github PRs in publish:github:pull-request action

### ISSUE THREAD

**Issue by peimanja** [backstage/backstage#10152]
## Feature Suggestion

I would like to be able to add labels to pull requests created by `publish:github:pull-request` action. 

## Possible Implementation

- Allow passing option array of `labels` as inputs in `publish:github:pull-request` action. I had a quick look and looks like we are using `octokit-plugin-create-pull-request` package which might makes things ugly a little (not sure what was the motivation of using that instead of `octokit` library
- Create a new action called something like `github:label-pull-request` in https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/github which simply takes a PR url and adds labels using `octokit` library

## Context

We often trigger some automations with PR labels (like auto-merge) and this feature would allow us to keep the same workflow without changing our current process

**Comment by benjdlambert** [comment]
Thinking that the first option is probably the best short term, is this something you want to contribute @peimanja? 🙏 

The reason from what I recall that `octokit-plugin-create-pull-request` plugin is used, is that it's actually pretty hard to build all the things that's required to raise a pull request against a repo using the plain `octokit` library. So it actually does quite a bit of heavy lifting a provides a nice API. At it's core though it's still just octokit, so you should be able to use that library still to add labels to the resulting PR pretty easily FWIW.
