### ISSUE TITLE
HttpError: Not Found when scaffolding with GitHub team that doesn't exist

### ISSUE THREAD

**Issue by timja** [backstage/backstage#10160]
1. Scaffold repo with GitHub provider
2. Inside of template have a parameter for a GitHub team to assign access to
3. Provide a GitHub team that doesn't exist

The repository gets created but publish fails
```
2022-03-11T20:40:21.973Z HttpError: Not Found
at /app/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:86:21
```

_Originally posted by @peimanja in https://github.com/backstage/backstage/issues/8263#issuecomment-1065532112_

**Comment by timja** [comment]
A UI component that lists and validates teams would be best.

Apart from that yes could do some validation on the server side and do better logging.

**Comment by peimanja** [comment]
Thanks @timja. I agree, worst thing is creating an empty repository with no access and it increase support requests to internal team who owns the Github.

Best option would be to have a GithubTeamPicker UI field that validates or auto-complete github team fields.

**Comment by timja** [comment]
go away

**Comment by benjdlambert** [comment]
Does someone want to pick this up and have a go at implementing something :pray:

**Comment by ltdonner** [comment]
Unfortunately I don't have time to help with this but I would love to see it un-stale.

**Comment by timja** [comment]
go away
