### ISSUE TITLE
Include major/breaking plugin changes in upgrade-helper/create-app changelog

### ISSUE THREAD

**Issue by aarontsharp** [backstage/backstage#10210]
## Feature Suggestion
The upgrade-helper and create-app changelog (listed [here](https://github.com/backstage/backstage/blob/master/packages/create-app/CHANGELOG.md)) should include changelogs for default Backstage plugins, or at least major/breaking changes to those plugins.

## Possible Implementation
I would suggest including plugin changelogs in the create-app changelog/upgrade-helper, possibly by providing an option to select which plugins are used to keep the scope relevant. At a minimum, major plugin changes (especially those plugins included by default in `create-app`) should be more discoverable. I realize there are already changelogs for plugins, but surfacing this information in the changelog for the `create-app` plugin seems helpful for understanding which changes might affect a given user.

## Context
After using the backstage-cli to bump versions and following the upgrade-helper's suggestions to migrate to 0.70.0, I found my backend failed to start up as `GithubDiscoveryProcessor` (which I required in my config) was no longer a registered provider. This provider was removed by default as a breaking change introduced in 0.24.0 of the catalog-backend plugin [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/CHANGELOG.md#0240), which was automatically bumped when I ran `backstage-cli versions:bump`. This change was not mentioned in the create-app changelogs or the upgrade-helper, and I only discovered it after searching Backstage's Github repository.

I would like to keep Backstage up to date and appreciate the existing tools and information to assist in this process. However, I think the changelogs should be more comprehensive, and at a minimum include all breaking changes for commonly used Backstage plugins.

**Comment by awanlin** [comment]
We've been using the release view in GitHub as our starting place when a new release is published, this includes ALL of the changes. Maybe that would help for you? https://github.com/backstage/backstage/releases

Looking at the release 0.71.0 seems to have the item you noted (@backstage/plugin-catalog-backend@0.24.0) as well as all the changes for that release: https://github.com/backstage/backstage/releases/tag/v0.71.0

**Comment by aarontsharp** [comment]
This is very helpful thanks. It may be worth including these more comprehensive changelogs in the documentation for upgrading Backstage [here](https://backstage.io/docs/getting-started/keeping-backstage-updated#updating-backstage-versions-with-backstage-cli)

Since IMO, this line:
>We recommend peeking at this changelog for any applicable updates when upgrading packages.

implies that the changelog for the `create-app` would surface all of these breaking changes, where in my situation it did not.
