### ISSUE TITLE
Responsive Catalog Graph card

### ISSUE THREAD

**Issue by Xantier** [backstage/backstage#10224]
## Enhancement Suggestion

Currently catalog graph card has a `height` prop that can be passed into it, which defines the height of the card itself. This becomes a bit problematic for cases where one component within the catalog has a graphs of 2 nodes and another one has tens of hundreds of nodes. Choosing the correct values for these is not trivial. 

Ideally the card should have responsive height that matches the underlying d3 graph displayed within it. 

## Possible Implementation
* CSS Magic?
* Would we need to calculate the amount of nodes, the length of their texts displayed in the graph and then calculate how much space they would take to be able to estimate the correct height?

**Comment by freben** [comment]
Hm. And as you add different rendering modes, layout directions etc, it just gets harder and harder.

Is there some argument to be made for putting control in the hands of the user? Making a best effort initial guess and then letting the user resize the area or press a fullscreen button or similar?

**Comment by Xantier** [comment]
Yeah, tricky bit of magic will be needed regardless if this is approached. It could make sense to have more capabilities in the form of zooming/fullscreenifying the thing, kinda like those exist on the catalog graph page. I think that would go a long way already. 

Having a fully responsive card size might cause messups on the rest of the layout as well possibly...
