### ISSUE TITLE
TechDocs nested lists rendering indent problem

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#10232]
I have documentation files that are formatted via prettier. Prettier config extends the one from Spotify and it sets the `tabWidth` to 2, which is the default value and the one being used by the Spotify config.

However, after publishing, nested lists are not rendered properly. I realize that in the background we have mkdocs to manage this, and by default, if I"m not mistaken, in order for the nested list to work, we need indentation set to 4.

Correct me if I'm wrong, but this is where your plugin `techdocs-core` comes into place and solves this problem.

In my sample docker container that I created to test mkdocs with this plugin I'm able to solve the issue. In other words, with the plugin included the mkdocs site show lists correctly, without the plugin it does not.

But after publishing with `techdocs-cli` to my s3 bucket within our backstage instance the nested lists are not rendered correctly (not rendered as nested).

## Expected Behavior

The list should look like this:

- My Item
- My Item2
  - My SubItem
  - My SubItem 2
- My Item 3

## Actual Behavior

The list actually looks like this:

- My Item
- My Item2
- My SubItem
- My SubItem 2
- My Item 3

It seems that the `techdocs-core` is being ignored or something.

## Steps to Reproduce

- Create some docs
- Include prettier
- Extend spotify prettier config
- Set `tabWidth` to 2 (which is the default by the way and also set in the Spotify config)

## Context

Prettier config:

```
module.exports = {
  ...require('@spotify/prettier-config'),
  ...{
    singleQuote: true,
    trailingComma: 'es5',
    arrowParens: 'always',
    bracketSpacing: true,
    endOfLine: 'auto',
    printWidth: 80,
    tabWidth: 2,
    jsxSingleQuote: true,
  },
};
```

## Your Environment

- Browser Information: Google Chrome 99.0.4844.51

- Output of `yarn backstage-cli info`: 

```text
OS:   Windows_NT 10.0.19044 - win32/x64
node: v14.17.5
yarn: 1.22.11
cli:  0.13.1 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.6
  @backstage/backend-common                                0.10.6      
  @backstage/backend-tasks                                 0.1.5       
  @backstage/catalog-client                                0.5.5, 0.6.0
  @backstage/catalog-model                                 0.9.10      
  @backstage/cli-common                                    0.1.6       
  @backstage/cli                                           0.13.1      
  @backstage/config-loader                                 0.9.3       
  @backstage/config                                        0.1.13      
  @backstage/core-app-api                                  0.5.2       
  @backstage/core-components                               0.8.7, 0.8.8
  @backstage/core-plugin-api                               0.5.0, 0.6.0
  @backstage/dev-utils                                     0.2.20      
  @backstage/errors                                        0.2.0
  @backstage/integration-react                             0.1.21, 0.1.20
  @backstage/integration                                   0.7.2
  @backstage/plugin-api-docs                               0.7.1
  @backstage/plugin-app-backend                            0.3.23
  @backstage/plugin-auth-backend                           0.9.0
  @backstage/plugin-catalog-backend                        0.21.2
  @backstage/plugin-catalog-common                         0.1.2
  @backstage/plugin-catalog-graph                          0.2.9
  @backstage/plugin-catalog-import                         0.8.0
  @backstage/plugin-catalog-react                          0.6.14, 0.6.13
  @backstage/plugin-catalog                                0.7.11
  @backstage/plugin-github-actions                         0.4.34
  @backstage/plugin-org                                    0.4.1
  @backstage/plugin-permission-common                      0.4.0
  @backstage/plugin-permission-node                        0.4.2
  @backstage/plugin-permission-react                       0.3.0
  @backstage/plugin-proxy-backend                          0.2.17
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.10
  @backstage/plugin-scaffolder-backend                     0.15.23
  @backstage/plugin-scaffolder-common                      0.1.3
  @backstage/plugin-scaffolder                             0.11.18
  @backstage/plugin-search-backend-node                    0.4.5
  @backstage/plugin-search-backend                         0.4.1
  @backstage/plugin-search                                 0.6.1
  @backstage/plugin-tech-radar                             0.5.4
  @backstage/plugin-techdocs-backend                       0.13.2
  @backstage/plugin-techdocs                               0.13.2
  @backstage/plugin-user-settings                          0.3.18
  @backstage/plugin-xcmetrics                              0.2.17
  @backstage/search-common                                 0.2.2
  @backstage/techdocs-common                               0.11.6
  @backstage/test-utils                                    0.2.4
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1
```

**Comment by andrewthauer** [comment]
I believe this issue is fixed by [mdx_truly_sane_lists](https://github.com/backstage/mkdocs-techdocs-core/blob/main/src/core.py#L108). This a quirk in how `python-markdown` implements the markdown spec which isn't 100% compatible with commonmark of github flavoured markdown.

**Comment by ProticM** [comment]
@andrewthauer This is the part of my techdocs config:

```yaml
techdocs:
  builder: 'external'
  generator:
    runIn: 'docker'
    dockerImage: 'spotify/techdocs'
    pullImage: true
```

The publisher is configured to `aws3`. In my GitHub action I install the latest `techocs-cli` package. Here is part of the pipeline:

```yaml
- name: Install techdocs-cli
  run: npm install -g @techdocs/cli

- name: Install mkdocs and mkdocs Plugins
  run: python -m pip install mkdocs-techdocs-core==0.*

- name: Generate Docs Site
  run: techdocs-cli generate --no-docker --verbose

- name: Publish Docs Site
  run: techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
```

Basically, my GitHub action looks like an example on the Backstage documentation page, minus platinum action.

**Comment by andrewthauer** [comment]
@ProticM - Oh, I see you are not using docker and just installing the dependencies directly. Hard to say, but some additional things you could check / update are:

- `mkdocs-techdocs-core` is now at `1.0.1` so try bumping to that exact version
- Verify the mkdocs.yaml has `mkdocs-techdocs-core` registered correctly
- Explicitly add the `mdx_truly_sane_lists` to the mkdocs.yaml file

**Comment by yohannes** [comment]
Hi @andrewthauer,

On your remark above as followed:

> - Explicitly add the `mdx_truly_sane_lists` to the mkdocs.yaml file

Can you kindly help to clarify/elabroate What is the full syntax to add/declare it in the yml file?

**Comment by andrewthauer** [comment]
@yohannes 

[mdx_truly_sane_lists](https://github.com/radude/mdx_truly_sane_lists) is already included and configured by default in [mkdocs-techdocs-core] as seen here https://github.com/backstage/mkdocs-techdocs-core/blob/main/src/core.py#L128. So if you are using the latest https://github.com/backstage/techdocs-container then is should be working out of the box.

If you are building a custom `techdocs-container` image, then my recommendation is to add `mkdocs-techdocs-core` as a dependency and then include it in the `mkdocs.yaml` like so https://github.com/backstage/techdocs-container/blob/main/mock-docs/mkdocs.yml#L10. Or if you can't for some reason use `mkdocs-techdocs-core`, then it would look like:

```yaml
# mkdocs.yml

...

plugins:
  # this needs to be pip installed and available to the executing python library running mkdocs
  - mdx_truly_sane_lists
```

Hopefully that helps.

**Comment by yohannes** [comment]
Thanks @andrewthauer for those pointers.
