### ISSUE TITLE
[TechDocs] Create a "click-to-zoom" Addon

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#10270]
## What / Why

Sometimes, images referenced in documentation are too small to read within the chrome of a TechDocs site.  It would be great if clicking on an image would enlarge the image, perhaps in a modal-like experience.

## Scope / UAT Target
- [ ] As a TechDocs user, I should be able to view an enlarged version of an image when I click on it.
- [ ] As a Backstage Integrator, I should be able to install a TechDocs Addon that enables the above functionality

### Original report

The images references in techdocs rendering don't zoom like the the text content.
Is this the intended behaviour?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
May be we should consider the option where in, when user clicks on any image on the docs page, it should appear like a huge pop up and allow users' to zoom???

**Comment by iamEAP** [comment]
> _The images references in techdocs rendering don't zoom like the the text content._
Hey @shanthisagar-dhanya-kumar-db could you provide repro steps for this?  I'm having trouble picturing this.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Simple example, how do you zoom the images here https://demo.backstage.io/docs/default/component/backstage/overview/what-is-backstage/

**Comment by garyniemen** [comment]
The way I see it is like this.
1) The Zoom function is just for text - and I think that's right.
2) It is always possible to use browser functionality to increase the size of everything - and that's quite useful.
3) Clicking on an image causes it to pop out and expand. This is what is potentially missing and could be good and useful.
Thoughts?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Do we have any updates on this?
I believe the images should be made clickable by default and open in a different window?

**Comment by garyniemen** [comment]
@shanthisagar-dhanya-kumar-db Feel free to have a go (use case 3 above) and submit a PR.

**Comment by iamEAP** [comment]
If you (or anyone else) is considering a contribution in this regard: I will also just chime in and say that this is a _perfect_ use case for the recently released [TechDocs Addon Framework](https://backstage.io/docs/features/techdocs/addons#addons-in-the-content-location)

**Comment by benjdlambert** [comment]
@iamEAP can we close this now? Is the PR mentioned done?

**Comment by iamEAP** [comment]
Still a good idea, and as-yet unimplemented.  I've updated the title and description to make this a little easier for someone to come in and contribute it!
