### ISSUE TITLE
[Plugin] Kubecost

### ISSUE THREAD

**Issue by ananthulasrikar** [backstage/backstage#10289]
## Summary

Kubecost has lot of cost analysis across namespaces, labels etc. It would be great if kubecost cost plugin is developed its easy to install independent of the cloud platforms

## Project website (if applicable)

https://www.kubecost.com/
https://github.com/kubecost/cost-model - Open Source

**Comment by regicsolutions** [comment]
Looks like there is already a plugin out there for kubecost: 

https://github.com/BESTSELLER/backstage-plugin-kubecost

**Comment by danielpsf** [comment]
It seems [BESTSELLER/backstage-plugin-kubecost](https://github.com/BESTSELLER/backstage-plugin-kubecost) is archived. 🤔 

I wonder if it isn't worth forking it and putting it at https://github.com/backstage/backstage... 🧐

**Comment by jhaals** [comment]
We'd prefer if it would be forked by an organisation or individual that would be willing to update and develop the plugin. It can then be added by the plugin marketplace by placing a file in this directory https://github.com/backstage/backstage/tree/master/microsite/data/plugins

**Comment by sylus** [comment]
Just mentioning here in case the kubecost folks themselves had any opinions on this.

@AjayTripathy

I'd be happy to help in supporting it as well, as this integration will be important for my team :)

**Comment by AjayTripathy** [comment]
Thanks so much for tagging me into this @sylus . We're fully supportive of community plugins! If you all want to take the fork  you can reach out for help with our normal support channels (support@) and/or tag us into GH issues. If the kubecost org in github needs to take the fork that's an option as well, just would want to run it by our eng team.

**Comment by ananthulasrikar** [comment]
@AjayTripathy We would love to have it, its pretty important for us. Please let me know if I have to do anything from our side.

**Comment by ehrnst** [comment]
is this the new effort for adding kubecost/opencost? https://github.com/backstage/backstage/issues/14411

**Comment by Rugvip** [comment]
Yep I think it's best to focus efforts around #14411, let's continue the discussion there.

Let me know if it still makes sense to consider a Kubecost specific plugin in addition to an Opencost one, in which case I can reopen this

**Comment by phac008** [comment]
I read through [#14411](https://github.com/backstage/backstage/issues/14411), but maybe we should open this one again:

We create a specific Kubecost frontend application with use of Kubecost API.
https://www.npmjs.com/package/@suxess-it/backstage-plugin-kubecost

Please give it a try - we are very open for suggestions
