### ISSUE TITLE
[cli] [create-plugin] support backstage.role

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#10283]
## Feature Suggestion

Currently, `backstage-cli create-plugin` creates a frontend plugin by default
or a backend plugin if `--backend` was added to the command.

Since backstage.role was introduced, it would be great to support plugins for all roles.

## Context

Create common-library plugins.

**Comment by Rugvip** [comment]
Note that `create-plugin` is being replaced by just `create`, but the request still stands :grin:

Common library plugins happens to be supported though: `yarn backstage-cli create --select plugin-common`

**Comment by pjungermann** [comment]
Thanks @Rugvip . Somehow was not aware of create vs create-plugin. Just overlooked it. Is there any gap still then or should this issue be closed?

**Comment by freben** [comment]
Sound like we can close it! `create` is where the efforts will be spent going forward, and the set of templates will probably grow.
