### ISSUE TITLE
@codemirror/basic-setup conflict when upgrading from 0.71.1 to 1.0.0

### ISSUE THREAD

**Issue by testn** [backstage/backstage#10295]
## Expected Behavior
Upgrading 0.71.1 -> 1.0.0 should be smooth and error free

## Actual Behavior
```
Compiled with problems:X

WARNING in ../../node_modules/@uiw/react-codemirror/esm/index.js 8:0-40

The requested module '@codemirror/basic-setup' contains conflicting star exports for the name 'EditorView' with the previous requested module '@codemirror/view'
```

## Steps to Reproduce

Upgrade from 0.71.1 to 1.0.0 using 

`yarn backstage-cli versions:bump`

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```
backstage-cli info
OS:   Darwin 21.0.1 - darwin/arm64
node: v16.14.0
yarn: 1.22.17
cli:  0.16.0 (installed)

Dependencies:
  @backstage/app-defaults                       1.0.0
  @backstage/backend-common                     0.13.1
  @backstage/backend-tasks                      0.2.1
  @backstage/catalog-client                     1.0.0
  @backstage/catalog-model                      1.0.0
  @backstage/cli-common                         0.1.8
  @backstage/cli                                0.16.0
  @backstage/config-loader                      1.0.0
  @backstage/config                             1.0.0
  @backstage/core-app-api                       1.0.0
  @backstage/core-components                    0.9.2
  @backstage/core-plugin-api                    1.0.0
  @backstage/errors                             1.0.0
  @backstage/integration-react                  1.0.0
  @backstage/integration                        1.0.0
  @backstage/plugin-api-docs                    0.8.3
  @backstage/plugin-app-backend                 0.3.30
  @backstage/plugin-auth-backend                0.12.2
  @backstage/plugin-auth-node                   0.1.6
  @backstage/plugin-catalog-backend-module-ldap 0.4.1
  @backstage/plugin-catalog-backend             1.0.0
  @backstage/plugin-catalog-common              1.0.0
  @backstage/plugin-catalog-graph               0.2.15
  @backstage/plugin-catalog-import              0.8.6
  @backstage/plugin-catalog-react               1.0.0
  @backstage/plugin-catalog                     1.0.0
  @backstage/plugin-github-actions              0.5.3
  @backstage/plugin-org                         0.5.3
  @backstage/plugin-permission-common           0.5.3
  @backstage/plugin-permission-node             0.5.5
  @backstage/plugin-permission-react            0.3.4
  @backstage/plugin-proxy-backend               0.2.24
  @backstage/plugin-scaffolder-backend          1.0.0
  @backstage/plugin-scaffolder-common           1.0.0
  @backstage/plugin-scaffolder                  1.0.0
  @backstage/plugin-search-backend-node         0.5.2
  @backstage/plugin-search-backend              0.4.8
  @backstage/plugin-search-common               0.3.2
  @backstage/plugin-search                      0.7.4
  @backstage/plugin-tech-radar                  0.5.10
  @backstage/plugin-techdocs-backend            1.0.0
  @backstage/plugin-techdocs-node               1.0.0
  @backstage/plugin-techdocs                    1.0.0
  @backstage/plugin-user-settings               0.4.2
  @backstage/release-manifests                  0.0.2
  @backstage/search-common                      0.3.2
  @backstage/test-utils                         1.0.0
  @backstage/theme                              0.2.15
  @backstage/types                              1.0.0
  @backstage/version-bridge                     1.0.0
✨  Done in 1.47s.

```

**Comment by testn** [comment]
@freben it looks like there is something weird with registry.npmjs.org where the latest version is a bit off in some cache for @backstage/plugin-techdocs. Is it possible for you to re-publish?

```
yarn info @backstage/plugin-techdocs@1.0
yarn info v1.22.17
{
  maintainers: [
    {
      name: 'alund',
      email: 'alund@spotify.com'
    },
    {
      name: 'patriko',
      email: 'patriko@spotify.com'
    },
    {
      name: 'freben',
      email: 'freben@spotify.com'
    },
    {
      name: 'marcuseide',
      email: 'eide@spotify.com'
    }
  ],
  keywords: [
    'backstage',
    'techdocs'
  ],
  'dist-tags': {
    next: '0.15.1-next.0',
    nightly: '0.0.0-nightly-20220317022557',
    latest: '0.15.1'
  },
```

**Comment by Rugvip** [comment]
The `@codemirror` conflict is because of duplicate versions of those packages being incompatible. The duplication shows up in the first place because it was added as a dependency of the scaffolder plugin in the most recent release. Tbh there's not a lot we can do from our side except try to downgrade our dependencies to fit some of the existing usage.

To solve the problem you need to deduplicate the `@codemirror/*` installations. If you have `yarn-deduplicate` installed you can do it like this (thanks @kuangp):

```sh
yarn-deduplicate --scopes @codemirror
```

Or you can manually edit `yarn.lock` and remove all `@codemirror` entries.

Once you've done that you need to run `yarn install` again, and at that point the issue should be gone.

**Comment by Rugvip** [comment]
Regarding [`@backstage/plugin-techdocs`](https://www.npmjs.com/package/@backstage/plugin-techdocs), that looks alright on NPM. Perhaps it's an intentional delay of package versions on your end?

**Comment by Crevil** [comment]
Thanks @Rugvip . Just removing the locked version fixed it here 🙏

**Comment by testn** [comment]
re: @backstage/plugin-techdocs, It looks good now.
re: plugin, I just removed all codemirror and it works now.

**Comment by testn** [comment]
BTW, some of the upgrades did change all the dependency, should I update that manually?>

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/445123/158962812-e1befe6a-a62f-4701-a26a-4eafc06f053a.png">

**Comment by Rugvip** [comment]
@testn Nope any version bumps of `@backstage` packages you don't need to do manually, as they're handled by `yarn backstage-cli versions:bump`

**Comment by testn** [comment]
I did that already but it did not have the exact same version as when I did npx @backstage/create-app

**Comment by testn** [comment]
Oops sorry @Rugvip  .... I pasted in the wrong screenshots. It should be 

Frontend
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/445123/158964138-107b66af-85eb-4c0b-8f80-0771e2afb410.png">

Backend

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/445123/158964289-0a841129-0cd7-4074-bae5-af699d215d80.png">

**Comment by Rugvip** [comment]
Ah `versions:bump` skips bumping in `package.json` if its not necessary, and instead just modifies `yarn.lock`. So it wouldn't for example write a patch bump to `package.json` as that's already within range. That's just to reduce noise and merge conflicts a bit.

**Comment by testn** [comment]
Ah thanks. That kinda explains it... It was a bit confusing indeed. I noticed that `yarn.lock` is not exactly the same so I thought it was caused by `package.json`
