### ISSUE TITLE
cli: versions:check command should flag unsatisfied peerDependencies on @backstage packages

### ISSUE THREAD

**Issue by mtlewis** [backstage/backstage#10304]
## Feature Suggestion

For Backstage-related packages outside the `@backstage` scope, it's sometimes useful to create peerDependencies on `@backstage` packages. In particular, this is helpful when a package is intended to _augment_ a plugin by providing things like [Entity Providers](https://backstage.io/docs/reference/plugin-catalog-backend.entityprovider), [Search Engines](https://backstage.io/docs/reference/plugin-search-common.searchengine), or [Permission Policies](https://backstage.io/docs/reference/plugin-permission-node.permissionpolicy). 

In cases like this, a standard dependency doesn't help us. If the version installed by an integrator didn't satisfy the specified version range, then the package would be installed a second time inside the package, but the integration between the packages might still not work. A peerDependency is a more accurate representation of this relationship, but unsatisfied peerDependencies are treated as warnings rather than errors by both npm and yarn, and it's common for there to be many unsatisfied peerDependencies in large projects, so any signal you get from the warnings is noisy.

To address this, we should consider adding functionality to the `versions:check` command in the backstage-cli which validates peer dependencies on `@backstage` packages, and returns an error if any are unsatisfied, directing the user to upgrade the appropriate packages before upgrading Backstage itself.

## Possible Implementation

When `backstage-cli versions:check` is run:
- For each dependency* in each package in the workspace:
  - Load the package.json for the dependency
  - Check that all peerDependencies for packages in the `@backstage` scope are satisfied
  - Log any unsatisfied `@backstage` peerDependencies to the console, and prompt the user to upgrade those packages before upgrade Backstage.
  - Exit non-zero if any unsatisifed peerDependencies were found.

## Context

When building Backstage packages outside the monorepo, we want to ensure that users are prompted earlier than runtime when breaking changes in new versions of Backstage mean that they need to upgrade other packages, too.

**Comment by freben** [comment]
Makes sense! Added a help wanted label on it.
