### ISSUE TITLE
[versions:bump] patch level diff with upgrade helper

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#10302]
## Expected Behavior

When using `backstage-cli versions:bump` 
and then checking all changes at https://backstage.github.io/upgrade-helper/
all dependency versions used are the same.

## Actual Behavior

When using `backstage-cli versions:bump` 
and then checking all changes at https://backstage.github.io/upgrade-helper/
so far I always had differences for some dependencies, usually at patch level.

## Steps to Reproduce

1. Project on 0.71.1
2. Run `backstage-cli versions:bump`

**Comment by Rugvip** [comment]
The `backstage-cli versions:bump` command avoids modifying `package.json` if it doesn't need to. Idea is to avoid noise and merge conflicts. It would be pretty simple to change it to always bump `package.json` entries too, but not sure that's the correct fix.

A feature we have in mind for the upgrade helper is to filter out all of the dependency changes that would anyway be handled by `versions:bump`, which I think would also solve this right?

**Comment by pjungermann** [comment]
@Rugvip This sounds like a great idea, too, and would reduce the manual comparison effort.

My point was rather that after the versions:bump command was executed, some dependencies were changed, but at upgrade helper it was a different version.

E.g.
`"@backstage/core-components": "^0.9.1"` vs `"@backstage/core-components": "^0.9.2"`

At that point, I had to manually modify these at the package.json files in order to be in sync with what upgrade helper was showing. Of course, there could always be the question whether this is necessary or not.

**Comment by Rugvip** [comment]
@pjungermann It's not necessary from a technical point of view anyway, you should already have had `0.9.2` or above installed.

**Comment by pjungermann** [comment]
What do you mean with

> you should already have had 0.9.2 or above installed.

Because of  `^0.9.2`?

**Comment by pjungermann** [comment]
Another example from the last release

`"@testing-library/react": "^10.4.1"` vs `"@testing-library/react": "^12.1.3"`

**Comment by Rugvip** [comment]
Yep, because of the `^` range. When `versions:bump` sees a dependency bump that is within the declared dependency range it only modifies `yarn.lock` and leaves the `package.json` intact. You should see `@backstage/core-components` going from `0.9.1` to `0.9.2` in yarn lock during the bump.

The `@testing-library/react` example is why it would be really valuable to hide the dependency bumps of `@backstage` packages in the upgrade helper. Since `@testing-library/react` is not part of the Backstage ecosystem it does not get bumped automatically, so this is one that you need to do manually.

**Comment by pjungermann** [comment]
I just tried it again
```
"app@link:packages/app":
  version "0.0.0"
  dependencies:
    "@backstage/app-defaults" "^1.0.0"
    "@backstage/catalog-model" "^1.0.0"
    "@backstage/cli" "^0.16.0"
    "@backstage/core-app-api" "^1.0.0"
    "@backstage/core-components" "^0.9.1"
    [...]

"@backstage/core-components@^0.9.1", "@backstage/core-components@^0.9.2":
  version "0.9.2"
  [...]
```
I guess this is what you meant, right?
