### ISSUE TITLE
Missing documentation for generic auth providers

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#10303]
## Expected Behavior

The [auth docs section](https://backstage.io/docs/auth/) should contain documentation for how to set up the OAuth2 and OIDC providers.

## Actual Behavior

The documentation does not exist

## Context

The generic providers are different from the other ones in that they don't have a dedicated `ApiRef` in the frontend, and you likely want to set them up with a custom provider ID too. How to set up the frontend refs is already documented at https://backstage.io/docs/api/deprecations#generic-auth-api-refs, but it would be best to get that out into its own section.

Most likely we want to introduce a section that fully describes how a custom auth provider is installed with its own ID, frontend representation, entry on the settings page, entries in config, as well as installation in the backend. I believe all of these are documented in various places, except for the backend installation pattern, which would look something like this:

```ts
  return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      ...defaultAuthProviderFactories,
      myprovider: createOidcProvider({ // <- This is the important bit
        signIn: {
          resolver: ..., // <- along with a custom resolver if needed for sign-in
        },
      }),
    },
  });
```

With that section in place we can reference it from both the OAuth2 and OIDC doc pages, and otherwise keep those pretty lightweight, mostly giving an overview of the backend config options.

**Comment by sergeyshevch** [comment]
I can attach my use case to it. We are using dexidp for SSO in our org. For the clients, it's just a generic oidc provider. So in many cases, we can just use integration for okta or something similar. But here okta integrations are not working for us and setting up a generic oidc provider is quite hard. It will be nice to have this documented

**Comment by pavshu** [comment]
I've been attempting to grok OIDC setup for a bit now to make it work with Keycloak but to no avail. 
Unfortunately, [PR#12136](https://github.com/backstage/backstage/pull/12136) didn't make it in and there's been [a deprecation of some APIs that are auth-related](https://backstage.io/docs/api/deprecations#generic-auth-api-refs).

**Comment by sergeyshevch** [comment]
@pavshu I have a similar setup with the dex. If you want I can share some of it with you. You can contact with me by email

**Comment by pavshu** [comment]
Thank you for the offer @sergeyshevch :bow:! I got it working yesterday by following [the advice from Discord user `semogr`](https://discord.com/channels/687207715902193673/1005141701750435971/1006180553554415707).
I love the Backstage community! :heart_eyes:
