### ISSUE TITLE
[RFC] Can we access current user information in our backend plugins?

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#10314]
**Status:** Open for comments

## Need

I'm looking for a way to get the user profile info or other parts that are provided via IdentityAPI on the frontend. I could not find anything similar in the sourcecode and thus I'm asking here if there is a built-in way to get the user information in backend plugins?

For example, we have a number of backend plugins, and in one of them, we need to get the email of the currently logged-in user. Is this supported or do I need to dig in and provide a solution for this?

**Comment by freben** [comment]
Hi!

The frontend typically passes the user's Backstage token (from the identityApi) in the form of Authorization Bearer token headers in backend requests. If your frontend uses fetch from the fetchApi this happens automatically. However, that token does not contain any profile data or similar; you'll have to take the `sub` (which is a full entity ref string) out of it, and fetch more user details based on that. For example, if your org has reliable ingested org data in the catalog, you can look up the corresponding User entity.

**Comment by ikuegelgen** [comment]
Hi @freben, thanks for your answer. Another question from our side is: We use SSO providers to login. Is there a way to get the users email adress as claim to the Authorization Bearer token?

**Comment by ProticM** [comment]
Hi @freben.

In addition, we have valuable data for our users kind in the database. The issue is that a logged-in user can be someone that is not ingested as a User kind in our catalog. This is something we have currently, maybe it will change.

We use Okta provider, therefore our entity name is actually an email of the user, correct me if I'm wrong? And full entity ref is something like `{kind}:{namespace}/{entity-name}` so, in the token we should have `user:default/john@doe.com`?

Also, we are talking about the same token provided by the context in our custom scaffolder actions?

**Comment by freben** [comment]
@ikuegelgen Sure! Since you are yourselves responsible for [issuing the token](https://backstage.io/docs/auth/identity-resolver), you can add custom claims to the Backstage token at will.

**Comment by freben** [comment]
@ProticM You are free to design the entity names and catalog structure in any way you see fit. It's both a freedom and a source of potential confusion :) I think you should start with the question, how would you WANT things to be structured and work?

Your ingestion of entities into the catalog can be done in any of a multitude of ways, there's no fixed naming pattern or structure.

Your [sign-in resolver](https://backstage.io/docs/auth/identity-resolver) can also choose to do anything it wants. It could extract any part of the incoming identity data (from Okta) and fetch auxiliary data in any way that fits your needs.

You COULD take the first part of the email and use that as your naming pattern, if that makes sense to you. You could also put an annotation on your ingested User entities that you use as the "lookup key" instead of going by name, like [this example resolver](https://github.com/backstage/backstage/blob/9c01fe543da2a9a0a0ee676a57dc6b521def2f69/plugins/auth-backend/src/providers/google/provider.ts#L186) does.

The key is, you want to align what the catalog ingestion does, and what the sign-in resolver does, so that the issued token contains values that line up with actual entities. But they are two separate systems, and are set up and configured separately and freely.

**Comment by ProticM** [comment]
Hi @freben

> You are free to design the entity names and catalog structure in any way you see fit. It's both a freedom and a source of potential confusion :)

Yes, this part is clear :)

> You COULD take the first part of the email and use that as your naming pattern, if that makes sense to you.

This is exactly how we have it, with a slight problem that I now see that we can solve with the custom sign-in resolver which is something we did not reach in our implementation yet.

Basically, we use Okta provider to sign in our users and we take the first part of it as an entity name for our user. We do not have an annotation, but we do have a custom object with several additional values that are then used in our instance to build some custom UI. These values did not fit as a `label` or `annotation`.

To provide some context, the issue that we have is the vast amount of users belonging to different internal entities. A user with the same name and the first part of the Okta email can exist in multiple entities. In other words, we can have something like user.one@test.com and user.one@othertest.com thus we needed to resolve this by creating a namespace based on our legal entity because the user is unique per one.

Also, in situations when we acquire another external entity we might introduce more users with the same name. This cannot be avoided unless after acquiring it every single email is changed, which is something that is not feasible.

On the other hand, the signed-in user always has a default namespace set, which is something we need to align with the users in the catalog because we do not have users in the default namespace due to uniqueness problems. A custom implementation of the sign-in resolvers is something I see as a solution.

Do you have any remarks about this? And also, can a sign-in resolver be async? I predict that some external API is going to be called to fetch the information required.

**Comment by freben** [comment]
Ah I see. Let me throw one more suggestion into the mix:

What if your entities' `metadata.name` was instead the full email, and leave them all in the `default` namespace?

Namespaces are fine as such, but having to split apart the email and reconstructing it in an entity ref "shape" just to appease Backstage - and then asking users to type out their ownership info etc in a foreign way when emails are perfectly legible and understandable to them as humans ... Maybe it'd be better to just retain the original emails? Would that be a useful option you think?

The default rules for `metadata.name` don't permit `@` signs, but I feel that this use case is so sensible and the need will be so common, that maybe we should be even relaxing the default. Anyway, it's very easy to customize. In your catalog builder in `packages/backend/src/plugins/catalog.ts`, you can do

```ts
import { makeValidator } from '@backstage/catalog-model';
// ...
  builder.setFieldFormatValidators(
    makeValidator({
      isValidEntityName: value => {
        return (
          typeof value === 'string' &&
          value.length >= 1 &&
          value.length <= 63 &&
          /^[\w@+._-]+$/i.test(value)
        );
      },
    }),
  );
```

Or something like that. Maybe I missed some characters that are valid in emails in there, but it's a start.

**Comment by freben** [comment]
Also, yes - the resolver is async.

**Comment by ProticM** [comment]
Thanks @freben 

Yes, this is something we discussed before, whether we should leave them in the default namespace and use the full email as the name. And, it is still a valid thing for us that we might end up doing.

The reason why we did not do it, is because we set the namespace for every backstage entity...component, group, resource...etc...The number one reason for it is the uniqueness, and another important reason is that we have an idea of a possible multitenancy approach.

Something like AWS regions...the user logs in and after selecting a namespace somewhere in the header UI for example, the app will filter the entire UI (where possible) and possibly functionalities based on it. The idea behind this is to show the relevant information to the logged-in user if so desired. For example, if I belong to our internal entity 1 I could have difficulties finding the data that is relevant only to me and my entity in the vast amount of data presented in the backstage instance.

But, this is a milestone that is still far in the future...and also, to achieve it, the backstage user entity is not 100% required to be in a separate namespace...we can still have the above mentioned filter without it.

A question about the field validator. Does it know which field to validate? Where we can specify that this validator should validate `metadata.name`?

**Comment by freben** [comment]
> A question about the field validator. Does it know which field to validate? Where we can specify that this validator should validate `metadata.name`?

It's in the structure - `isValidEntityName` checks that particular field, and there are other siblings to that one in the parameter to `makeValidator` that check other aspects of an entity's shape.

> The reason why we did not do it, is because we set the namespace for every backstage entity...component, group, resource...etc...The number one reason for it is the uniqueness, and another important reason is that we have an idea of a possible multitenancy approach.

Sure, but your namespace structure CAN be different for different kinds if you want. Since the full email is already a perfect uniqueness constraint in and of itself, I thought it might be helpful to keep that one flat.

**Comment by ProticM** [comment]
Thanks @freben Yes, it is helpful for sure. If nothing else, a good confirmation that this is a valid thing to be considered as a metadata name for the users.

Especially the field validator. I was not aware of that possibility.

**Comment by freben** [comment]
No. That particular feature is the overall sanity check - org-wide rules for "lowest common denominator" type things. Also, the intent of the metadata block is that it should be the same for all kinds, in theory at least. That being said, you COULD easily make a processor that runs in the post step, just adding some additional check to the name and throwing an exception if it's not fulfilling some additional requirement.

**Comment by ProticM** [comment]
Ok, thanks for the information. Yes, the idea behind the metadata is clear. We have the metadata name check within our custom processor that ingest the users data and does exactly that, it throws an error if the extracted name does not meet the requirements.

But IMHO some particular things might be more useful if they are different per kind, but depending on the common metadata.

For example, all the columns in the catalog table are the same for every kind. We cannot have different catalog table columns per kind unless we replace the entire catalog table and include this functionality, even though the only thing that differs would be the columns.

**Comment by ProticM** [comment]
Hi @freben A quick question about customizing the claims. Let's take an email as an example.

I see that we are limited to setting `sub` and `ent` claims only. Now, I still feel that the `sub` should have the user entity ref as a value, but the `ent` field seems as not suitable for storing an email. Do you think the same?

Another idea is to place the email as a `sub` and then the stringified user entity ref would go to the `ent` list. The thing I do not like with this approach is that if we add more refs in the `ent` list then when parsing the token somewhere in the app it might be cumbersome to find the current user entity ref (to fetch more data for the current user for example), and introduce parsing mechanisms to extract it.

Any remarks on this question?
