### ISSUE TITLE
[CLI] List Depreciated Code

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#10319]
## Feature Suggestion

It would be really helpful if there was a way to list depreciated code. This would help keep ahead up upcoming changes

## Possible Implementation

We've added this by using [eslint-plugin-deprecation](https://github.com/gund/eslint-plugin-deprecation). Setting this up was pretty easy, just needed to to the following:

1. Add `eslint-plugin-deprecation` to the root `package.json`
2. In your root `.eslintrc.js` file under the `rules` section add `'deprecation/deprecation': 'warn', // or "error" to have stricter rule`
3. Next in the same file but at the root you'll need to add this:

```js
parserOptions: {
    project: ['./tsconfig.json'], // Specify it only for TypeScript files
    tsconfigRootDir: __dirname,
  },
```

Now when you run `yarn lint` you can see depreciated code.

**Note:** there are a few downside to this:

- We have a small repo, when I tried this on the Backstage repo with `yarn lint:all` it took a good 10-15 minutes to run
- There is a lot of noise in the output that we were not sure how to properly handle, it all looked like this:
```text
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: plugins\scaffolder-backend\config.d.ts.
The file must be included in at least one of the projects provided
```

## Context

Being able to see what code we are using that has been depreciated will save us time when the depreciated code has been removed. In the vast majority of cases the depreciated code has a replacement well in advance meaning users can move to that easily without much pain and confusion.

**Comment by awanlin** [comment]
@Rugvip you seem to be the one who does a lot of the cli work. Was hoping to get your thoughts on this?

**Comment by Rugvip** [comment]
Got this one listed, should happen any day now 😁

**Comment by awanlin** [comment]
> Got this one listed, should happen any day now 😁

Yeah? Awesome! Great minds think alike! 😆
