### ISSUE TITLE
Issues with updating entity relationships since upgrade to knex 1.0.2 / backstage@v0.70.0

### ISSUE THREAD

**Issue by saan800** [backstage/backstage#10348]
Ever since the upgrade to knex 1.0.2, we have seen some inconsistencies with catalog data being kept up to date when the source data files are changed.

We use `@vscode/sqlite3` for local dev, and `postgres` for deployed environments. 
We are seeing the issues with both types of DB. I've even deleted the DBs (both types) and restarted everything from scratch.
I've also tested out locally with `better-sqlite3` and it has issues too.

## Expected Behavior

* When a user entities' `memberOf` groups are changed, the Group's `relations.hasMember` should reflect the changes in the DB (ie remove user from old groups and add to new groups)
* When a user entity is deleted, the Group's `relations.hasMember` should reflect the changes in the DB
* When a component's `owner` group changes, the Group's `relations.component` should reflect the changes in the DB (ie remove component from old group and add to new group)
* When a component entity is deleted, the Group's `relations.component` should reflect the changes in the DB

NOTE:
* entity deletions are done in our custom `S3Processor` via this command `this.catalogClient.removeEntityByUid(entityUid, { token: process.env.BACKEND_SECRET })`

## Actual Behavior

To confirm the issue is consistent, I've followed the following steps on both sqlite and postgres DB types and on a couple of different environments, and get the same results:
* ✅  initial load of data from entity source files into DB is accurate
* ✅  add a new user that's not in a group (user data is loaded into the DB successfully)
* ✅  add a new user that is a `memberOf` group(s) (user data is loaded and successfully added to the group's relations)
* ✅  update an existing user's metadata annotations
* 🟥  move a user's `memberOf` from one group to another (the user is added to the new group, but they're also still listed under the relations of the old group)
* 🟥  move a component's `owner` from one group to another (the component is added to the new group, but it's also still listed under the relations of the old group)
* ✅  delete a user entity that's not a member of a group (successfully deletes the user entity from the DB)
* 🟥  delete a user entity that's a member of a group (successfully deletes the user entity from the DB, but it's still listed under the `relations` of the group)
* 🟥  delete a component entity that's owned by a group (successfully deletes the component entity from the DB, but it's still listed under the `relations` of the group)

## Steps to Reproduce

As above for your favourite entity source data and Processor type

We tried the above steps with our own in house `S3Processor` and with copying the files locally and using the standard [FileReaderProcessor](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/modules/core/FileReaderProcessor.ts)

## Context

We noticed that several of our source data changes were not being accurately reflected in backstage after we upgraded to `knex: v1.0.2`

It looks like the old "group" relations are not kept in sync when the user `memberOf` & component `owner` fields are updated or the entity is deleted.

## Your Environment

Local dev: we use currently `"@vscode/sqlite3": "^5.0.7"`, though I've done a quick test with `better-sqlite3` and it still has issues with data updates

Deployed environments (qa/production/etc): we use `"pg": "^8.5.1",`

**Comment by Rugvip** [comment]
Thank you for reporting! Just to check, are you confident that this was not an issue before knex `v1.0.2`?

**Comment by saan800** [comment]
We haven't seen any evidence of it being an issue before the upgrade to knex 1.0.2 (as part of migration to backstage [release 0.70.0](https://github.com/backstage/backstage/releases/tag/v0.70.0) ). 
Its likely that someone within the company would have made a change in the source data and let us know if it wasn't propagated to backstage, but I can't say with 100% certainty that it wasn't an issue previous to upgrade.

**Comment by saan800** [comment]
Conversation on whats seen in the DB: https://discord.com/channels/687207715902193673/956616026831863889

**Comment by saan800** [comment]
Data example:
* User entity changing from `Group1` to `Group2`
* User has `spec.memberOf` relationship to groups in source data
* `Group1` and `Group2` do not have `spec.members`  populated in source data, and relies on backstage catalog processing to generate the required relationships in the DB

Latest theory from conversation:  https://discord.com/channels/687207715902193673/956616026831863889

* The stitching process runs on [this line](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/processing/DefaultCatalogProcessingEngine.ts#L184)
* However that process runs after the [User entity has already been processed](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/processing/DefaultCatalogProcessingEngine.ts#L83) and the new relationships set (ie now a member of `Group2`, not `Group1`)
* `Group1` and `Group2` source data has not changed, so would not enter the `DefaultCatalogProcessingEngine.processTask` 
* This would mean that:
  * the stitching process to update a User's related entities currently only has access to the new relationship to `Group2`
  * the old `User`->`Group1` relationship would not be discovered, so `Group1` is not updated

**Comment by freben** [comment]
probably related problem: https://discord.com/channels/687207715902193673/923144214580191282/958144637028167730

**Comment by freben** [comment]
Alright, devising a fix that hopefully addresses this https://github.com/backstage/backstage/pull/10544
