### ISSUE TITLE
External route 'catalogIndex' of the 'org' plugin must be bound to a target route.

### ISSUE THREAD

**Issue by joel-vasiliev** [backstage/backstage#10346]
## Actual Behavior

after update coreComponent and corePluginAPI I'm facing this issue:
"External route 'catalogIndex' of the 'org' plugin must be bound to a target route."
Backstage loads but the screen loads without content (blank screen)

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by jhaals** [comment]
I believe this was mentioned in the changelog for the org plugin https://github.com/backstage/backstage/blob/master/plugins/org/CHANGELOG.md#minor-changes-1 . It's recommended to look for the `BREAKING` keyword in the changelog for those packages that are indicated to have breaking when running versions:bump or by comparing changes with the upgrade helper https://backstage.github.io/upgrade-helper/
