### ISSUE TITLE
Make webpack app-serve wait for backend startup before serving frontend

### ISSUE THREAD

**Issue by freben** [backstage/backstage#10349]
As reported in #10323, in some cases the frontend builds and starts too fast, before the relevant backend is ready for requests.

In this particular case it was the catalog page, and the catalog backend. We should one way or the other support this case - perhaps the frontend could perform retries, perhaps there could be some more explicit readiness endpoint that's polled by the app-backend before it lets through the first requests, or something else.

**Comment by shailahir** [comment]
Will it be applicable for separate deployment use case ?
https://backstage.io/docs/deployment/docker#separate-frontend
