### ISSUE TITLE
[Scaffolder] Templating fails because placeholder $text is not yet available

### ISSUE THREAD

**Issue by caromeva** [backstage/backstage#10351]
## Expected Behavior

Load the component and load the Swagger API in the corresponding tab.

## Actual Behavior

I am trying to make a component of type Component and one of type API. I have created the catalog-info.yaml file with variables whose values ​​are loaded from the template.yaml. I have an error when doing the registration step of the catalog-info.yaml. The error says the following:

Error: {"error":{"name":"Error","message":"InputError: Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location https://backstage-demo- springbootrest-app-cromero.ecomm-stg.company.com/ws/api/v1/v2/api-docs,
Error: Unable to read https://backstage-demo-springbootrest-app-cromero.ecomm-stg.company.com/ws/api/v1/v2/api-docs,
FetchError: request to https://backstage-demo-springbootrest-app-cromero.ecomm-stg.company.com/ws/api/v1/v2/api-docs failed

This is because from the API component I am calling a URL that is a Json Swagger using the $text $text placeholder: https://${{values.repoApplicationName}}.ecomm-stg.company.com/ws/api/ v1/v2/api-docs . The variable ${{values.repoApplicationName}} is replaced from the values ​​sent by the template.yaml

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

My localhost using Laptop MacBook M1

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by jhaals** [comment]
The problem is that it location registration does a dryRun before adding the actual location, there's a slight chicken and egg problem for this specific case. It probably make sense to add a `force` option to the [registration action](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/catalog/register.ts) which just registers and ignores the dryRun failure. Would you be interested looking at this @caromeva?

**Comment by pedroparraortega** [comment]
I'm facing the same situation trying to add an existing component pointing to the definition.
```
Placeholder $text could not read location https://my-service.com/swagger-docs, NotAllowedError: Reading from 'https://my-service.com/swagger-docs' is not allowed","level":"error","service":"backstage"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":500}}
```

**Comment by benjdlambert** [comment]
So there could be two things going on here, either the URL is not available when doing the `dryRun` or you'll need to allow the URL using the `backend.reading.allow` config option in `app-config.yaml`.

@pedroparraortega I think for your case, you might have to add the host to the allow list to be able to register existing things.

**Comment by pedroparraortega** [comment]
> So there could be two things going on here, either the URL is not available when doing the `dryRun` or you'll need to allow the URL using the `backend.reading.allow` config option in `app-config.yaml`.
> 
> @pedroparraortega I think for your case, you might have to add the host to the allow list to be able to register existing things.

```
  reading:
    allow:
      - host: '*.mycompany.com'
```

my config looks like this. I did a dump of this part of the config and got
```
[1] [
[1]   ConfigReader {
[1]     data: { host: 'catalogue.mycompany.com' },
[1]     context: 'app-config.yaml',
[1]     fallback: undefined,
[1]     prefix: 'backend.reading.allow[0]',
[1]     notifiedFilteredKeys: Set(0) {},
[1]     filteredKeys: undefined
[1]   }
[1] ]
```

if I query the URL i get the json with the api definition. So not sure what i'm missing here but not working.

I'm just testing from my local, so backstage should be able to read that url too.

**Comment by lalit774** [comment]
I am also getting the same issue. I am unable to access any third party URL for swagger file.

Folder Structure:
backstage/
    my-app
    api/petstore-json-url-api.yaml

App  config:
backend:
  reading:
    allow:
      - host: 'petstore.swagger.io'
        paths: ['/v2/']

  locations:
    # Backstage example components
    - type: file
      target: ../../../apis/petstore-json-url-api.yaml  


Swagger API file(petstore-json-url-api.yaml):
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-josn-URL
  description: The petstore API
  tags:
    - test
    - abc
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition: 
    $text: https://petstore.swagger.io/v2/swagger.json

**Comment by Rugvip** [comment]
Renamed this issue to keep it focused on the original problem, which is that the scaffolder registration dry-run fails because the content is not yet available. Let's keep the discussion here focused around that, with a good suggestion for a way forward in https://github.com/backstage/backstage/issues/10351#issuecomment-1078788492.

For other issues, see the suggestions in https://github.com/backstage/backstage/issues/10351#issuecomment-1087443774, and open separate issues if you're still running into trouble.

**Comment by riginoommen** [comment]
How to talk to an api endpoint for docs having the auth?

**Comment by TheDukeDK** [comment]
Can this be re-opened? I mean we have a use case of creating a new templated repo, getting it built and deployed with default swagger documentation. If the swagger documentation MUST be available before it is actually built to run the scaffolder then it completely defeats the purpose of scaffolding a new repo...

1. Fetch, template, with swagger endpoint as we know what it will be when deployed.
2. Publish the repo 
3. Trigger a build
4. Deploy new component 
5. Swagger endpoint is available.

This flow, of course, fails in the very beginning, if step five is a requirement for step 1. Is the some other way to template the api endpoint?

**Comment by TheDukeDK** [comment]
I went ahead and created new bug. #20831
