### ISSUE TITLE
Techdocs CLI `serve` results in a 404 error

### ISSUE THREAD

**Issue by Niksko** [backstage/backstage#10362]
## Expected Behavior

Running `npx @techdocs/cli serve` displays the techdocs

## Actual Behavior

Running `npx @techdocs/cli serve` displays a 404 page

## Steps to Reproduce

1. Set up a local mkdocs repo
2. `npx @techdocs/cli serve`
3. The 404 will appear in the opened browser window

## Context

This seems to be a regression in `1.0.0`. `npx @techdocs/cli@1.0.0 serve` displays the buggy behaviour. `npx @techdocs/cli@0.8.17 serve` works as expected.
The logs for the docker container that is spawned contain a 404 error, snippet below:

```
INFO     -  Documentation built in 1.95 seconds
INFO     -  [05:30:43] Serving on http://0.0.0.0:8000/
WARNING  -  [05:30:47] "GET /techdocs/index.html HTTP/1.1" code 404
```

**Comment by Niksko** [comment]
Hey @realandersn, thanks for looking at this.

Steps to reproduce:

```bash
mkdir techdocs-cli-404-reproduction
cd techdocs-cli-404-reproduction
cat > mkdocs.yaml <<EOF
site_name: test-site
nav:
  - Home: index.md
plugins:
  - techdocs-core
EOF
mkdir docs
echo "# Home" > docs/index.md
npx @techdocs/cli@1.0.0 serve
```

Expected: The created page is displayed

Actual: The 404 'mic drop' page is displayed

Running `npx @techdocs/cli@0.8.17 serve` works as expected.

**Comment by qjcg** [comment]
I'm getting the same 404 behavior `techdocs-cli serve` v1.0.0.

However, all is working fine when I run `techdocs-cli serve:mkdocs`.

**Comment by iamEAP** [comment]
Hmm...  I too am unable to reproduce, even with the detailed/scripted steps from Nik (thanks, BTW!).

What's more odd is that other than a few dependency bumps, `v0.8.17` and `v1.0.0` of the CLI are [basically identical](https://github.com/backstage/backstage/blob/master/packages/techdocs-cli/CHANGELOG.md#100)

Wondering if there are any other clues to why it might be working for Anders and I but not y'all.  Are y'all on windows?  What version of docker are you running?

**Comment by heyLu** [comment]
I am getting this on Linux with Docker 20.10.14.  A colleague is also encountering the same issue on macOS (not sure which versions).  I tested this with @Niksko's comment above and am also getting `ERROR 404: Error: Page not found`.

One odd thing I have is that the error message talks about `techdocs.builder` not being set to `local`, maybe that could be the cause?  Here's the full error message + a screenshot:

```
ERROR 404: Error: Page not found

Note that techdocs.builder is not set to 'local' in your config, which means this Backstage app will not generate docs if they are not found. Make sure the project's docs are generated and published by some external process (e.g. CI/CD pipeline). Or change techdocs.builder to 'local' to generate docs from this Backstage instance.
Looks like someone dropped the mic!
[Go back](http://localhost:3000/docs/default/component/local/)... or please [contact support](https://github.com/backstage/backstage/issues) if you think this is a bug.
```

![2022-04-22T17:19:21,056200386+02:00](https://user-images.githubusercontent.com/527119/164744340-d2fe6601-21dc-41ff-9ae7-3eab333df0d9.png)

And finally, my system details if relevant:

```
$ uname -a
Linux metaphya 5.17.2-arch3-1 #1 SMP PREEMPT Sun, 10 Apr 2022 11:18:32 +0000 x86_64 GNU/Linux

$ docker version
Client:
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.18
 Git commit:        a224086349
 Built:             Thu Mar 24 08:56:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18
  Git commit:       87a90dc786
  Built:            Thu Mar 24 08:56:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.2
  GitCommit:        de8046a5501db9e0e478e1c10cbcfb21af4c6b2d.m
 runc:
  Version:          1.1.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Niksko** [comment]
> Wondering if there are any other clues to why it might be working for Anders and I but not y'all. Are y'all on windows? What version of docker are you running?

Nope, running on Mac. We're able to reproduce across a few devs at my org.

```
$ uname -a
Darwin L4653 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin

$ docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.0 (74594)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Niksko** [comment]
I've submitted a fix above. I'm really puzzled as to why this isn't reproducible for people, the fix is fairly straightforward.

For those who can't reproduce: when you load the http://localhost:3000/docs/default/component/local/ after running `serve`, what URL does your browser request when it requests the techdocs index.html?

For me:

* Version 1.0.0: The browser requests http://localhost:3000/api/techdocs/index.html which returns a 404
* Version 0.8.17: The browser requests http://localhost:3000/api/index.html which returns a 200

The bug is that when the embedded-app is resolving the base url for the techdocs API, it used to read the value from config, and it was hardcoded to `http://localhost:3000/api`. The change I reference in the PR removes this, and so the base url for the techdocs API now resolves to `http://localhost:3000/api/techdocs`, as it should for a real Backstage installation.

The techdocs-cli when running with the embedded-app (i.e. `@techdocs/cli serve`) proxies requests to `http://localhost:3000/api` to the mkdocs container. When it does the proxying, it strips the `api` portion of the path, but it wasn't stripping the `techdocs` portion of the path that was added above.

**Comment by zhammer** [comment]
+1 on fixing this (haven't gotten to try @Niksko's fix but hope it works).

folks at my org have found techdocs-cli _super_ unstable. pretty much every update brings some issue that breaks local workflows. would love to see more focus on stability in future techdocs cli releases. (don't mean to be nagging. i realize it's a hard thing to get right and that i'm not proposing any solutions :) )

**Comment by ericis** [comment]
I have closed #11177 in favor of this issue. I will also re-test using the notes outlined in #11466.

**Comment by ericis** [comment]
Yes, I've replicated the behavior that @Niksko outlines and has provided a fix for. Waiting for his PR #11051 to be finalized and released in the "nightly" build in order to retest the fix.

**Comment by ericis** [comment]
@zhammer agreed. We're developing our own tooling to further abstract the TechDocs details away from developers, especially for documentation-only repositories by using containerized tooling with commands that "just work" out-of-the-box across hosting platforms. As a result, we are "pinning" tooling versions to known, working versions, but bugs like this even make that difficult. I just ran into a new issue that is likely a bug, where I can't upgrade MkDocs Material, because of something in the TechDocs MkDocs plug-in 🤷🏼‍♂️

**Comment by Niksko** [comment]
Hey folks, this was resolved by #11467. I can confirm that it's fixed on master. Happy to close this.

**Comment by ericis** [comment]
Thanks @Niksko . I've confirmed this is working with the nightly build in this repo:
https://github.com/ericis/test-techdocs-cli-serve

Both commands now work properly:

- `techdocs-cli serve`
- `techdocs-cli serve -v --no-docker`

**Comment by ericis** [comment]
@Niksko I found a fun related bug that produces a 404 when MkDocs "site_url" is configured outlined in #11557. I'm not certain that your code may have caused this regression, since you used a RegEx for pattern matching, but possibly.

**Comment by mikepea** [comment]
FWIW, I saw this same 404 error. Adding a link from our custom-named homepage to  `docs/index.md` fixed it for me.
