### ISSUE TITLE
Title & Description aren't passed to custom field extensions

### ISSUE THREAD

**Issue by brunomiranda-hotmart** [backstage/backstage#10395]
## Expected Behavior

Pass title & description to custom field extensions so that they can be rendered.

## Actual Behavior

Title & description aren't passed to custom field extension.

## Steps to Reproduce

1. Create a field extension.
```js
export function MyCustomExtension({
  rawErrors,
  required,
  formData,
  title,
  description,
}: FieldProps<string>) {
...

<FormControl
  margin="normal"
  required={required}
  error={rawErrors?.length > 0 && !formData}
>
  <InputLabel htmlFor="my-input">Title: { title }</InputLabel>
  <FormHelperText id="my-helper-text">Description: { description }</FormHelperText>
</FormControl>
```
2. Add field extension to template.
```yaml
field:
  title: My title
  description: My description
  type: string
  ui:field: MyCustomExtension
```

And that's what it looks like:
<img width="151" alt="image" src="https://user-images.githubusercontent.com/84582602/159696483-bda5a6b0-25d4-4fd6-ad44-839813003602.png">

### How has this issue affected you? What are you trying to accomplish?

I'm trying to create a custom field extensions to reuse a list of elements that can be at multiple fields.

**Comment by benjdlambert** [comment]
Could you try destructuring `title` and `description` from the `schema` instead.

```tsx
export function MyCustomExtension({
  rawErrors,
  required,
  formData,
  schema: { title, description },
}
```

Does it get applied there/

**Comment by brunomiranda-hotmart** [comment]
Thanks @benjdlambert , it does get applied there.
