### ISSUE TITLE
[RFC] Entity Links Type

### ISSUE THREAD

**Issue by jrusso1020** [backstage/backstage#10404]
**Status:** Open for comments
This is based off of a short [discussion on discord](https://discord.com/channels/687207715902193673/956205139545456690)

There were a previous RFC related to this https://github.com/backstage/backstage/issues/3787

## Need
There are many different types of links and sometimes you want to validate the existence of a specific type, this is related to software insights/scorecards specifically. For example you want to ensure a software component has a logs link, or a runbook link, or observability dashboard link. You can somewhat get around the issue by using the `title` and enforcing a naming convention for it, however this doesn't solve the issue for multiple occurrences of a specific type of link. For example there may be multiple observability dashboards or runbooks and you want to validate they have at least 2+. If you would like to quickly check if they have a specific type of link it is not straightforward at the moment, and a workaround is to use annotations for specific links that are required but this only allows a single entry instead of multiple.

## Proposal
The proposal is to add an optional `type?: string` to the `EntityLink` [link] (https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/entity/Entity.ts#L198) type that will allow you to specify different types of links. The type would not be a hardcoded set of types but a string that can be used as needed. We can default the type if we like but it should not be a requirement to add link types

This topic was brought up in the original RFC as a `rel` or `type` field but the value and use-cases were not apparent at the time. This proposal hopes to outline a use case that makes this more accepted.

## Alternatives
Do nothing, adopters may have to extend the model privately which could move them away from the open source version of entities and cause issues for them.

## Risks
Fairly low risk because the field is optional and would not be a breaking change

**Comment by marcus-crane** [comment]
Neat! This came up in a discussion I had with a coworker earlier

**Comment by jrusso1020** [comment]
> Thanks for writing this up! I, for one, would be in favor of this :)
> 
> While we're here, open questions for all:
> 
> * What should the field be named? `type`, `rel`, something else?
> * Should there be a set of well known types that you could adhere to of you wanted? Or is this just an unnecessary complication?

Thanks for the feedback/questions!

1. I think `type` is more appropriate because in general the intent is to categorize links into well known types. I'm honestly not sure what `rel` is off the bat myself, so I would need someone to explain it to me and I'm sure others might as welll

2. I think we could potentially create a short list of example types like `runbook`, `documentation`, `logs`, `dashboard` etc but I don't think this field should be an enum type with a set number of types. I think it should be freeform text that can be easily extended. Although I guess you could add a custom validator via a catalog processor or something to ensure the type field is only expected values. I don't see the need currently though

**Comment by andrewthauer** [comment]
First off, I'm I believe this would be useful. However, based on the proposal I'm not sure how this new field would be used from a code perspective within Backstage. One of the concerns from the original RFC was around when to use a link versus an annotation (or something else). The consensus seemed to be that that links should be purely for display purposes and avoid being used by any conditional app/plugin logic. I think it would be good to at the very least have some guidelines defined and a plan on what use cases would be acceptable in core and/or other plugins that may consume & use links.

**Comment by jrusso1020** [comment]
> First off, I believe this would be useful. However, based on the proposal I'm not sure how this new field would be used from a code perspective within Backstage. One of the concerns from the original RFC was around when to use a link versus an annotation (or something else). The consensus seemed to be that that links should be purely for display purposes and avoid being used by any conditional app/plugin logic. I think it would be good to at the very least to have some guidelines defined and a plan on what use cases would be acceptable in core and/or other plugins that may consume & use links.

Agree with this, we have been using annotations ourselves for important links based on this guidance. But the annotation approach causes issues when you want multiple values for a single annotation (list). Links with types seem better suited to allow you to have multiple let's say observability dashboards attached to an entity, documents, runbooks etc

**Comment by jrusso1020** [comment]
pinging to keep this alive since it's been a couple of weeks of inactivity, if there's no objections I can open up a PR for further discussion/debate!

**Comment by Rugvip** [comment]
Any thoughts on how this might impact `EntityLinksCard` and whether you already have some plans or have switched it out for something custom already?

Overall we're happy to proceed with this though, ofc a bit carefully. Current thinking is that we go forward with what you suggest, `type?: string`. We'd also have no "well known" types or anything like that either, it's left as a field completely open to customization.

**Comment by jrusso1020** [comment]
> Any thoughts on how this might impact `EntityLinksCard` and whether you already have some plans or have switched it out for something custom already?

@Rugvip 
We haven't switched it out for anything custom already, but there are a few things that come to mind that we could do with the `EntityLinksCard` once we have this field. None of which are necessities 

1) we could default icons to certain ones when not specified already
2) we could do something similar to what the scaffolder template page does where we filter and group links together based on their type. An extension/alternative of this would be allowing devs to pass in a list of filters themselves to the links card to group by certain link types or multiple types
3) it unlikes additional components that developers could easily build to show just specific types, or open sourcing these new components for what may become well known types

**Comment by jrusso1020** [comment]
Took me a while to get to this but just opened up a small PR with the change https://github.com/backstage/backstage/pull/12035
