### ISSUE TITLE
Catalog Table not Filtering Items by Metadata Title

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#10418]
## Expected Behavior

The catalog table should filter properly when the entity metadata title is present in the entity.

When we have the metadata title set in our component, the catalog table shows this value in the name column instead of the actual metadata name. This is OK, but in such a case, the filtering needs to act accordingly and filter the name column by metadata title instead of metadata name

## Actual Behavior

The catalog table does not filter the table when the value of the title is entered in the filter box. It still filters by name, even though in the name column we see the title.

Basically, the catalog table is showing a title, but filtering is done by the entity name.

For example, we have an entity with the name `data-central-dwh` and the title is set to `Data Central DWH`. In such a case, the filtering by `data central` does not work, but filtering by `data-central` does work

## Steps to Reproduce

- Create a couple of entities
- Set the title in metadata title property for them
- The name column in the catalog table shows the title, which is OK
- Try to filter the catalog table by that title

## Context

We want to show a nice user friendly values for our entities in the name column, instead of the name slug which is not that user friendly. This can be done by specifying a title for the entity, but filtering should acknowledge this new value and filter the table by it, instead of just using the entity name while doing so.

## Your Environment

- Browser Information: Google Chrome Version 99.0.4844.82

- Output of `yarn backstage-cli info`:

```text
OS:   Windows_NT 10.0.19044 - win32/x64
node: v16.14.2
yarn: 1.22.11
cli:  0.15.3 (installed)

Dependencies:
  @backstage/app-defaults                         0.2.1
  @backstage/backend-common                       0.13.0
  @backstage/backend-tasks                        0.2.0 
  @backstage/catalog-client                       0.9.0 
  @backstage/catalog-model                        0.13.0
  @backstage/cli-common                           0.1.8 
  @backstage/cli                                  0.15.3
  @backstage/config-loader                        0.9.7 
  @backstage/config                               0.1.15
  @backstage/core-app-api                         0.6.0 
  @backstage/core-components                      0.9.1 
  @backstage/core-plugin-api                      0.8.0 
  @backstage/dev-utils                            0.2.25
  @backstage/errors                               0.2.2
  @backstage/integration-react                    0.1.25
  @backstage/integration                          0.8.0
  @backstage/plugin-api-docs                      0.8.2
  @backstage/plugin-app-backend                   0.3.29
  @backstage/plugin-auth-backend                  0.12.1
  @backstage/plugin-auth-node                     0.1.5
  @backstage/plugin-catalog-backend-module-aws    0.1.2
  @backstage/plugin-catalog-backend-module-github 0.1.0
  @backstage/plugin-catalog-backend               0.24.0
  @backstage/plugin-catalog-common                0.2.2
  @backstage/plugin-catalog-graph                 0.2.14
  @backstage/plugin-catalog-import                0.8.5
  @backstage/plugin-catalog-react                 0.9.0
  @backstage/plugin-catalog                       0.10.0
  @backstage/plugin-github-actions                0.5.2
  @backstage/plugin-org                           0.5.2
  @backstage/plugin-permission-common             0.5.2
  @backstage/plugin-permission-node               0.5.4
  @backstage/plugin-permission-react              0.3.3
  @backstage/plugin-proxy-backend                 0.2.23
  @backstage/plugin-scaffolder-backend            0.18.0
  @backstage/plugin-scaffolder-common             0.3.0
  @backstage/plugin-scaffolder                    0.15.0
  @backstage/plugin-search-backend-node           0.5.1
  @backstage/plugin-search-backend                0.4.7
  @backstage/plugin-search-common                 0.3.1
  @backstage/plugin-search                        0.7.3
  @backstage/plugin-tech-radar                    0.5.9
  @backstage/plugin-techdocs-backend              0.14.2
  @backstage/plugin-techdocs-node                 0.11.12
  @backstage/plugin-techdocs                      0.15.1
  @backstage/plugin-user-settings                 0.4.1
  @backstage/plugin-xcmetrics                     0.2.22
  @backstage/release-manifests                    0.0.2
  @backstage/search-common                        0.3.1
  @backstage/test-utils                           0.3.0
  @backstage/theme                                0.2.15
  @backstage/types                                0.1.3
  @backstage/version-bridge                       0.1.2
```

**Comment by ProticM** [comment]
Hi @kuangp Thanks for the workaround, but this means that you redefined all other columns as well? If I'm not mistaken, in order to add a new column we need to change the list of columns like explained [here](https://github.com/backstage/backstage/issues/7004#issuecomment-908691197) for example?

There is no merging with something like default columns.

**Comment by freben** [comment]
@ProticM You have e.g. `CatalogTable.columns.createNameColumn()`. The [default columns](https://github.com/backstage/backstage/blob/2c77266deb25c08fc0c174967f3c3223d92eb474/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L67) of the `CatalogTable` are indeed not exported but that wouldn't necessarily be super helpful either ... you often want to rearrange or insert a column etc, and the simplest, most powerful customization option then is, just replace the set entirely but with helpful oneliner builders for the various parts.

**Comment by ProticM** [comment]
@freben Thanks for your answer.

Yes, I've been adding custom columns in the past, and I know that the only thing that is exported is the methods to create the default columns, and thus I was asking the previous question to see if something has changed.

Ok, I will go with this approach and close this ticket once verified.

**Comment by ProticM** [comment]
The issue is verified, closing it
