### ISSUE TITLE
`@backstage/plugin-scaffolder` needs more tests and restructuring

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#10430]
It's becoming increasingly difficult to add features and have confidence in the existing (or lack thereof) of unit tests for the frontend plugin. Some work has already started on building a `NextScaffolderRouter` which points to a different entrypoint which should be covered by unit tests.

This ticket is here to track ongoing work, as well as small features / bugs that could also be fixed part of the `boy scout rule` and being in that area already.

### Ongoing work
- [x] #10061 
- [x] `TemplateList`
- [ ] `TemplateWizardPage`
- [ ] `TaskPage`
- [ ] `AvailableActions`
- [ ] `TemplatePreview`
 

### Additional work

- [ ] #7868
- [ ] #8420
- [ ] #7577

**Comment by taras** [comment]
Additional item https://github.com/backstage/backstage/pull/16365

**Comment by Pike** [comment]
I've filed #16454 and #16456

**Comment by ScottGuymer** [comment]
I found another issue with vNext (I think)

https://github.com/backstage/backstage/issues/18739

**Comment by benjdlambert** [comment]
Gonna close this issue as scaffolder/next has definitely been shipped :tada:
