### ISSUE TITLE
Customize the Entity context menu in Catalog

### ISSUE THREAD

**Issue by SuganJoe** [backstage/backstage#10434]
In the Expedia group, we don't use the "unregister entity" or other menu options as we have a different way of deleting entities in our setup. So, for some organizations which don't use the unregister or inspect entity, it must be removable and all other menu items must be customizable for example e.g. badges in the menu item.
<img width="270" alt="Screen Shot 2022-03-24 at 6 44 47 PM" src="https://user-images.githubusercontent.com/25852441/160038344-609e32d2-b933-4c11-896b-ee8e3eab0049.png">

## Feature Suggestion

To help with the above use case, it's better to not hardcode the menu items like [here](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityContextMenu/EntityContextMenu.tsx#L127-L149) and give the users option to customize the items in the menu by passing custom values from the entity page, the same way as the extra menu items  options [here](https://github.com/backstage/backstage/blob/master/packages/app/src/components/catalog/EntityPage.tsx#L159)

## Possible Implementation

Add "unregister entity", "inspect entity" via "UNSTABLE_extraContextMenuItems" similar to badges from the [entity page](https://github.com/backstage/backstage/blob/master/packages/app/src/components/catalog/EntityPage.tsx#L159) instead of hardcoding it [here](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityContextMenu/EntityContextMenu.tsx#L127-L149)

Do similar checks [here](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityContextMenu/EntityContextMenu.tsx#L101)  to disable the "Unregister entity" button in the entity page itself, so that users have control over the menu item.

## Context

To make the entity context menu customizable.

I would like to work on this if you all think this approach works.

**Comment by guillermomanzo** [comment]
@benjdlambert @emmaindal any thoughts on this issue? :)

**Comment by emmaindal** [comment]
Thanks for opening this issue @SuganJoe I think the capability to compose the context menu makes totally sense to me. I see the `UNSTABLE_extraContextMenuItems` is prefixed with `UNSTABLE` so not sure if the plan is to deprecate that. In general for how to compose it, I'll leave it up to @backstage/maintainers, as I can imagine there is some patterns (you mentioned one of them) that one can follow for the catalog.

**Comment by jhaals** [comment]
Hi! There's is an option for disabling the unregister button :)
See https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityLayout/EntityLayout.tsx#L146 which can be passed into as props to `EntityLayout`.

**Comment by benjdlambert** [comment]
Wondering if we can make https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityLayout/EntityLayout.tsx#L147 `boolean | VisibleType ` and then deprecate the `boolean` in favour of `type VisibleType = 'visible' | 'hidden' | 'disabled'` instead? The name of that is probably not great, so feel free to pick something better :)

**Comment by SuganJoe** [comment]
@benjdlambert tried locally and this works perfectly for all scenarios.

Do you mean to initially keep  [disableUnregister](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityLayout/EntityLayout.tsx#L147)  as `boolean | VisibleType` both and at a later time, deprecate the boolean and just use `VisibleType`. Is it because the adapters of the code need a change if we directly switch from boolean to VisibleType?

**Comment by benjdlambert** [comment]
We should support both and do the checking inside the component to see if it's a boolean then use the existing behaviour, but if it's of a string type then check what the string is set to and do the new behaviour. Maybe you could also `console.warn` if boolean is provided with a deprecation messaetg.

**Comment by pallavipervaje** [comment]
> Hi! There's an option for disabling the unregister button :) See https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityLayout/EntityLayout.tsx#L146 which can be passed into as props to `EntityLayout`.

I would like to disable "Unregister entity" option. @benjdlambert Can you please provide an example to achieve this? I am not sure how to pass the properties. (new to Backstage IO and React)
