### ISSUE TITLE
Configurable catalog page size

### ISSUE THREAD

**Issue by lvenugopal** [backstage/backstage#10453]
Hello Team, 
We would like to request a new feature which can customize catalog page size to higher number (currently its 20 rows). 

## Feature Suggestion
Custom or the ability to set the number of default rows for the catalog table

## Possible Implementation
Custom parameter which can set the rows to the given value, else take the default one (currently 20 rows)

**Comment by jhaals** [comment]
Hi @lvenugopal, this sounds like a good idea. Would you be willing to help out and send a PR for this?

**Comment by shailahir** [comment]
I am working on it. will raise a PR in few hours possibly.

**Comment by shailahir** [comment]
Raised a PR #10516 , Please review
