### ISSUE TITLE
[DOC] Use the --cwd yarn arguments

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#10459]
## Feature Suggestion

In most documentations, to install backstage plugins, we found the following lines : 

```bash
cd packages/backend ## or packages/app
yarn add my-plugin
```

When installing multiple plugins, it could be confusing to go to a subdirectory --> install plugin --> switch directory --> install another plugin, etc. So I think that one-line commands could be way more pactical for users like :

```bash
yarn --cwd packages/backend add my-plugin ## or --cwd packages/app
```

## Context

I've already find myself in a situation where I wanted to install a backend plugin, install it then I wanted to install a frontend plugin and my command didn't work just because I didn't change my directory. 
With the `--cwd` argument, the user shouldn't have to change directory manually, the `yarn` would do all the work 🎉

**Comment by jhaals** [comment]
Hi @LvffY ! Yes we discussed this yesterday and we're all for using `--cwd` instead of having to paste an additional command to change the working directory. Are you interested in sending some PRs to make life easier for users?

**Comment by LvffY** [comment]
Hi @jhaals 

I could give it a try :)

**Comment by LvffY** [comment]
@jhaals Made a first draft of the PR, don't hesitate to review it :)

I just found the pattern in the **docs** repository (and I found it logic) so don't search for too long, but may be I miss something.
