### ISSUE TITLE
Add tokenmanager to tech-insights-backend plugin

### ISSUE THREAD

**Issue by lqlamTMA** [backstage/backstage#10463]
Currently, I have added tech-insights plugin to my source. When tech-insights backend call API of catalog-client to get entities, it will check the policy of permission, if we haven't tokenmanager to tech-insights-backend plugin. For my thinking, tech-insights-backend call to get entities from catalog-backend plugin, the two plugins are in the same backend, they shouldn't check the policy of permission. How do think about this case?

**Comment by jhaals** [comment]
Hi, there's still a network call involved and we don't have a clear way of telling whenever you run a split deployment or not.
The tech-insights-backend should obtain a token from the `tokenManager` and forward it when communicating with the catalog. Are you interested in addressing this?

**Comment by jhaals** [comment]
Also a notice to @Xantier as you worked a lot on this plugin :)
