### ISSUE TITLE
Documentation does not load

### ISSUE THREAD

**Issue by bigmirc** [backstage/backstage#10475]
## Expected Behavior

Dev portal documentation should load

## Actual Behavior

documentation page gets this error
Building a newer version of this documentation failed. Error: "Failed to generate docs from /var/folders/kk/g0ppfjfj52v62np_l0qc2flr0000gp/T/backstage-uJh8Mh into /private/var/folders/kk/g0ppfjfj52v62np_l0qc2flr0000gp/T/techdocs-tmp-CRObNC with error This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with: connect ENOENT /var/run/docker.sock"

## Steps to Reproduce

1. go to the dev portal documentation

## Your Environment

- Browser Information: Google Chrome

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.4.0 - darwin/x64
node: v16.13.1
yarn: 1.22.17
cli:  0.7.16 (installed)

Dependencies:
  @backstage/backend-common                                0.9.6
  @backstage/catalog-client                                0.5.0
  @backstage/catalog-model                                 0.9.4
  @backstage/cli-common                                    0.1.4
  @backstage/cli                                           0.7.16
  @backstage/config-loader                                 0.6.10
  @backstage/config                                        0.1.10
  @backstage/core-app-api                                  0.1.17
  @backstage/core-components                               0.6.1, 0.7.0
  @backstage/core-plugin-api                               0.1.10
  @backstage/errors                                        0.1.2
  @backstage/integration-react                             0.1.12
  @backstage/integration                                   0.6.8
  @backstage/plugin-api-docs                               0.6.12
  @backstage/plugin-app-backend                            0.3.16
  @backstage/plugin-auth-backend                           0.4.4
  @backstage/plugin-catalog-backend                        0.16.0, 0.17.0
  @backstage/plugin-catalog-import                         0.7.2
  @backstage/plugin-catalog-react                          0.5.2, 0.6.0
  @backstage/plugin-catalog                                0.7.1
  @backstage/plugin-github-actions                         0.4.22
  @backstage/plugin-org                                    0.3.27
  @backstage/plugin-proxy-backend                          0.2.13
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.2
  @backstage/plugin-scaffolder-backend                     0.15.9
  @backstage/plugin-scaffolder-common                      0.1.0
  @backstage/plugin-scaffolder                             0.11.8
  @backstage/plugin-search-backend-node                    0.4.2
  @backstage/plugin-search-backend                         0.2.6
  @backstage/plugin-search                                 0.4.15
  @backstage/plugin-tech-radar                             0.4.11
  @backstage/plugin-techdocs-backend                       0.10.4
  @backstage/plugin-techdocs                               0.12.2
  @backstage/plugin-user-settings                          0.3.9
  @backstage/search-common                                 0.2.0
  @backstage/techdocs-common                               0.10.3
  @backstage/test-utils-core                               0.1.3
  @backstage/test-utils                                    0.1.19
  @backstage/theme                                         0.2.11
  @backstage/version-bridge                                0.1.0

```

**Comment by ottosichert** [comment]
Hey @bigmirc! Can you verify you have Docker installed and running? One option would be to run `docker ps` in your terminal and ensure it is not showing an error.

> This operation requires Docker. Docker does not appear to be available

**Comment by bigmirc** [comment]
Hello,
This issue is also present in production.
    On Tuesday, March 29, 2022, 09:58:02 AM GMT+3, Otto Sichert ***@***.***> wrote:  
 
 


Hey @bigmirc! Can you verify you have Docker installed and running? One option would be to run docker ps in your terminal and ensure it is not showing an error.


This operation requires Docker. Docker does not appear to be available

**Comment by ottosichert** [comment]
Docker also needs to be installed and running in production. What is the output of following commands?

```
$ docker ps
$ echo $?
```

**Comment by bigmirc** [comment]
Hello,
Seems like no container is up, but I have Docker installed.
Thanks, Alex

    On Tuesday, March 29, 2022, 11:06:34 AM GMT+3, Otto Sichert ***@***.***> wrote:  
 
 


Docker also needs to be installed and running in production. What is the output of following commands?
$ docker ps
$ echo $?

**Comment by bigmirc** [comment]
it's returning 0.

**Comment by ottosichert** [comment]
How does your setup look like to build, distribute and run containers? As you mentioned, no containers are running hence why the documentation does not load.

On this page we outline the building part for Docker containers: https://backstage.io/docs/deployment/docker

The setup usually is very different for each adopter of Backstage, so it's hard to give you a definite answer that applies to your setup. Just that you'd need to ensure the containers are up

**Comment by garyniemen** [comment]
@bigmirc are you unstuck now?

**Comment by bigmirc** [comment]
yeeep, thanks a lot
    On Tuesday, April 26, 2022, 03:37:03 PM GMT+3, Gary Niemen ***@***.***> wrote:  
 
 


@bigmirc are you unstuck now?

**Comment by garyniemen** [comment]
Closing then.

**Comment by githoober** [comment]
I have precisely the same issue.  I run backstage in Kubernetes with two pods - backstage (both FE and BE) and Postgres.  I also am getting the following error: 

> Building a newer version of this documentation failed. Error: "Failed to generate docs from /tmp/backstage-zO2TIA into /tmp/techdocs-tmp-JjUuox; caused by Error: This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with; caused by Error: connect ENOENT /var/run/docker.sock"

Does it mean I need to run Docker inside of a Kubernetes pod?

**Comment by kgogolek** [comment]
@githoober I had the same issue but [this document](https://backstage.io/docs/features/techdocs/getting-started#disabling-docker-in-docker-situation-optional) was helpful:

I had to 

```
apt install python3-pip 
pip3 install mkdocs-techdocs-core
```

and change my config to:

```
    techdocs:
        builder: 'local' # Alternatives - 'external'
        generator:
            runIn: 'local' # Alternatives - 'local'
        publisher:
            type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
```

And it works like a dream now
