### ISSUE TITLE
Techdocs local build when used with techdocs backend sync api, gives Out Of Memory

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#10477]
We use techdocs backend plugin's sync api to generate the docs for us locally.
techdocs.builder and techdocs.runIn is set to "local"
We have 16 GB openshift pod where the app is deployed.
Let's saw when we call the techdocs backend sync api for multiple docs generation one after the other, then the pod gives Out Of Memory. Do we need to do any memory setting specifically for this?

**Comment by garyniemen** [comment]
Has anybody come across this? Any answers for @shanthisagar-dhanya-kumar-db

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Sorry, I have to say it was our openshift pod config which was causing the issue. We were using 1.6 GB and when I changed to around 10 GB, it started working as expected. I will close this ticket now.
