### ISSUE TITLE
Use --no-install-recommends in backend Dockerfile

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#10487]
## Expected Behavior

Do not install `apt-get` recommends packages during docker builds. 

## Actual Behavior

All suggested packages are installed during builds.

## Steps to Reproduce

In the docker file produced by default, just add the `--no-install-recommends` argument to `apt-get` command : 

```dockerfile
# This dockerfile builds an image for the backend package.
# It should be executed with the root of the repo as docker context.
#
# Before building this image, be sure to have run the following commands in the repo root:
#
# yarn install
# yarn tsc
# yarn build
#
# Once the commands have been run, you can build the image using `yarn build-image`

FROM node:16-bullseye-slim

WORKDIR /app

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

# install sqlite3 dependencies
RUN apt-get update && \
    ## This line has changed
    apt-get install -y --no-install-recommends libsqlite3-dev python3 cmake g++ && \
    rm -rf /var/lib/apt/lists/* && \
    yarn config set python /usr/bin/python3

RUN yarn install --frozen-lockfile --production --network-timeout 300000 && rm -rf "$(yarn cache dir)"

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY packages/backend/dist/bundle.tar.gz app-config.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```

## Context

As a docker best practice, it is always recommended to have the lighter images. For this, we already can add the `--no-install-recommends` to the docker builds. 

It accelerates the builds from ~5sec (negligeable) but lightens the image from ~20Mo. 

It doesn't mean that users can't remove this option, but enable it by default seems to be a bad idea as it violates docker best practices.

**Comment by benjdlambert** [comment]
@LvffY if you remove the entire `apt-get` line does the container still build successfully for you?

**Comment by LvffY** [comment]
@benjdlambert As is, it doesn't. 

Because the line `yarn config set python /usr/bin/python3` expects to python to be installed and it is not present in the root image `node:16-bullseye-slim`

**Comment by benjdlambert** [comment]
Do we need the other dependencies in there? Is it enough just to install python would be my next question :)
