### ISSUE TITLE
[Documentation] Instructions on how to write templates could be more expansive

### ISSUE THREAD

**Issue by proffalken** [backstage/backstage#10498]
## Expected Behavior

I wanted to write a simple template that took an input from some drop-down lists and text fields in the first step, and then automatically constructed a repoURL based on the values given.

## Actual Behavior

The documents show how to create a repo by filling in the repoURL component, but apart from `allowedHosts` there is very little on how to customise the repoURL component, and even less on how to construct the repoName from variables that have been entered already. 

I struggled to find the templating engine that is used and how much of the syntax is available (turns out it's [Nunjucks](https://mozilla.github.io/nunjucks/), but that's only mentioned briefly on the page about [migrating to v1beta3 templates](https://backstage.io/docs/features/software-templates/migrating-from-v1beta2-to-v1beta3), not the main templating page), and I also can't find guidance on which variables are available "out of the box" or how to access them.  

For example, is there a `${{ system.<variable_name> }}` pattern for extracting values from the Backstage `app-config.yaml` file?

## Steps to Reproduce

Based on the YAML at https://github.com/proffalken/backstage-terraform-module/blob/main/template.yaml, I'd hope to automatically construct a repoURL that matches the [Terraform Module Repo Requirements](https://www.terraform.io/registry/modules/publish#requirements) through chaining variable values, but I can't see how I set the `repoName` string.

![tf1](https://user-images.githubusercontent.com/262545/160548541-3248b7f1-869a-430c-976f-270aa9f80816.png)
![tf2](https://user-images.githubusercontent.com/262545/160548553-f9a0dbce-6714-4e24-8f9e-4d28b75266b9.png)

## Context

See above, I'm trying to create a software template that can create git repos which adhere to the [Terraform Module Repo Guidelines](https://www.terraform.io/registry/modules/publish#requirements)

## Your Environment

- Browser Information: Version 1.36.122 Chromium: 99.0.4844.88 (Official Build) (64-bit)](https://brave.com/latest/)

- Output of `yarn backstage-cli info`: 

```text
root@dd5ba4f32963:/app/packages/backend# yarn backstage-cli info
yarn run v1.22.18
$ /app/node_modules/.bin/backstage-cli info
OS:   Linux 5.13.0-30-lowlatency - linux/x64
node: v16.14.2
yarn: 1.22.18
cli:  0.16.0 (installed)

Dependencies:
  @backstage/backend-common                       0.13.1
  @backstage/backend-tasks                        0.2.1
  @backstage/catalog-client                       1.0.0
  @backstage/catalog-model                        1.0.0
  @backstage/cli-common                           0.1.8
  @backstage/cli                                  0.16.0
  @backstage/config-loader                        1.0.0
  @backstage/config                               1.0.0
  @backstage/errors                               1.0.0
  @backstage/integration                          1.0.0
  @backstage/plugin-app-backend                   0.3.30
  @backstage/plugin-auth-backend                  0.12.3
  @backstage/plugin-auth-node                     0.1.6
  @backstage/plugin-catalog-backend-module-github 0.1.1
  @backstage/plugin-catalog-backend               1.0.0
  @backstage/plugin-catalog-common                1.0.0
  @backstage/plugin-permission-common             0.5.3
  @backstage/plugin-permission-node               0.5.5
  @backstage/plugin-proxy-backend                 0.2.24
  @backstage/plugin-scaffolder-backend            1.0.0
  @backstage/plugin-scaffolder-common             1.0.0
  @backstage/plugin-search-backend-node           0.5.2
  @backstage/plugin-search-backend                0.4.8
  @backstage/plugin-search-common                 0.3.2
  @backstage/plugin-techdocs-backend              1.0.0
  @backstage/plugin-techdocs-node                 1.0.0
  @backstage/release-manifests                    0.0.2
  @backstage/search-common                        0.3.2
  @backstage/types                                1.0.0
Done in 0.36s.
```

**Comment by proffalken** [comment]
I should probably say at this point that I'm more than happy to help with writing the documentation once I know where to start!

**Comment by benjdlambert** [comment]
@proffalken please feel free to go ahead and use this ticket to make some improvement to the docs which you think would help out other users. We can sometimes get a little foggy and what should be important to new users being in and around the project from the beginning! :pray: Thanks!

**Comment by proffalken** [comment]
@benjdlambert - more than happy to do that, although the main thing I'm struggling with right now is working out how to actually do stuff!

I'm already on the slack and discord, is there anywhere else I should be looking to get help on how to do stuff so I can turn it into documentation?

**Comment by benjdlambert** [comment]
Ah ok, sorry, I misunderstood that there was more questions in the original issue.

So as far as customising the RepoPicker, you can't currently provide any additional validation to the RepoUrlPicker to ensure that it starts with `terraform-` or whatever.

I'd recommend building your own RepoPicker, that's maybe two inputs, which would be `Owner` and `RepositoryName` and then you can create your own field extension to do the validation there that's just specifically built for `terraform` modules.

Does this make sense?

**Comment by proffalken** [comment]
Yup, definitely, thanks.

This was just one example of where the docs could be improved, so I'll take a look at the other challenges I've faced and see if I can add more content there as well.

**Comment by benjdlambert** [comment]
Ok perfect! :)

**Comment by proffalken** [comment]
Still trying to find the time for this...

**Comment by proffalken** [comment]
Still an issue, needs to be expanded, finding time to do it is the biggest problem! :dagger:

**Comment by ldevore-indigoag** [comment]
I am running into the same thing. It would be great to have a way to import an extension into another custom extension where we could then add this extra validation, rather than having to add code from said extension that we would like to use.
