### ISSUE TITLE
Integrating Gogs self-hosted repository, is it possible?

### ISSUE THREAD

**Issue by ohmychill** [backstage/backstage#10491]
**Status:** Open for comments

## Need
Is it possible to integrate Gogs self-hosted repository on  Backstage just like Github or Bitbucket?
From the looks of it, only the mainstream tools have the documentations available on how to integrate it, no other documentations for other repository tools like Gogs.

## Proposal
I want to inquire from the community if there are other users here who have successfully integrated other non-mainstream tools like Gogs Repository. And if it's possible to suggest a new plugin for this tool (Gogs Repository)

**Comment by jhaals** [comment]
Hi @ohmychill

There is currently no support for Gogs in Backstage but it's fully possible(and welcome) to contribute an integration for it 😁
