### ISSUE TITLE
react and react-dom mismatch after upgrading to v1.0.0 (React 17)

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#10511]
https://github.com/backstage/backstage/pull/9037
https://github.com/backstage/backstage/issues/6910

We have upgraded our code base to v1.0.0 and following is the react version under packages/app/package.json
"react": "^17.0.2",
"react-dom": "^17.0.2",

We have extended some of the backstages' plugin such as api-docs/ catalog / tech-radar to give custom features for our project and following is what we have in the package.json there
"peerDependencies": {
    "@types/react": "^16.13.1 || ^17.0.0",
    "react": "^16.13.1 || ^17.0.0",
    "react-dom": "^16.13.1 || ^17.0.0"
  },
All our other internal plugins in the project have the same react and react-dom versions as above

Our root package.json has the following
"resolutions": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },

Now we are seeing below error 
ERROR 501: Lazy loaded chunk failed to load, try to reload the page: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

**Comment by Rugvip** [comment]
What does `yarn why react` and `yarn why react-dom` say? They should both just list a single version. It's possible to get a duplicate install with those version ranges since `^17.0.0` isn't exactly the same as `^17.0.2`, and ofc v16 satisfies the full range as well. Double check the `react` and `react-dom` entries in `yarn.lock`, most likely you should actually just be able to just remove them from `yarn.lock` and run `yarn install` to solve the issue.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
yarn why react
[4/4] Calculating file sizes...
=> Found "react@17.0.2"

yarn why react-dom
[4/4] Calculating file sizes...
=> Found "react-dom@17.0.2"

There appears to be only one version of both react and react-dom.

Clearing the yarn.lock did yarn install

Using the below versions everywhere in the project
"@types/react": "^17.0.2"
"react": "^17.0.2",
"react-dom": "^17.0.2",

Contents of yarn.lock
react@^17.0.2:
  version "17.0.2"

react-dom@^17.0.2:
  version "17.0.2"

Still the same issue.

**Comment by Rugvip** [comment]
Hmm, looks alright. You could double-check `@hot-loader/react` too, that there's only one of each of the specific 16 and 17 installed via ©backstage/cli.

I think it's time to move on to investigating point 2, is it possible that you have an invalid hook call somewhere? what does the stack trace look like?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
"@hot-loader/react-dom-v16@npm:@hot-loader/react-dom@^16.0.2":
  version "16.14.0"

"@hot-loader/react-dom-v17@npm:@hot-loader/react-dom@^17.0.2":
  version "17.0.2"

The internal plugin, where we see that error hasn't changed anything. All we are doing at the moment is to upgrade to v1.0.0.
And surprisingly, there is not console stack trace !!!

**Comment by shanthisagar-dhanya-kumar-db** [comment]
And now when I perform the following.

// Add this in node_modules/react-dom/index.js
window.React1 = require('react');

// Add this in your component file
require('react-dom');
window.React2 = require('react');
console.log(window.React1 === window.React2);

it prints false

**Comment by shanthisagar-dhanya-kumar-db** [comment]
and also we get the following warning while performing yarn install

warning "workspace-aggregator-2de7c4d2-d288-4b92-8bae-15d51521a951 > app > @backstage/cli > @hot-loader/react-dom-v16@16.14.0" has incorrect peer dependency "react@^16.14.0".
warning "workspace-aggregator-2de7c4d2-d288-4b92-8bae-15d51521a951 > @backstage-extended/plugin-catalog > react-helmet > react-side-effect@2.1.0" has incorrect peer dependency "react@^16.3.0".
warning "workspace-aggregator-2de7c4d2-d288-4b92-8bae-15d51521a951 > app > @backstage/core-components > @material-table/core > react-beautiful-dnd@13.0.0" has incorrect peer dependency "react@^16.8.5".
warning "workspace-aggregator-2de7c4d2-d288-4b92-8bae-15d51521a951 > app > @backstage/core-components > @material-table/core > react-beautiful-dnd@13.0.0" has incorrect peer dependency "react-dom@^16.8.5".
warning "workspace-aggregator-2de7c4d2-d288-4b92-8bae-15d51521a951 > app > @backstage/core-components > @material-table/core > react-beautiful-dnd > use-memo-one@1.1.1" has incorrect peer dependency "react@^16.8.0".

**Comment by mertcb** [comment]
We have the same issue, everything is same with @shanthisagar-dhanya-kumar-db and also we have the error at Catalog, TechDocs and Scaffolder pages

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Finally, it appears that we had the scenario 2 which is hooks inside the function which we detected and finally resolved it.
@Rugvip : Thanks for helping to understand the other views.
