### ISSUE TITLE
[Techdocs] Couldn't load the document because css 404 (Not Found)

### ISSUE THREAD

**Issue by lqlamTMA** [backstage/backstage#10529]
After I bumped up version of backstage to 1.0.0 . My backstage couldn't load document for using Techdocs plugin and I had got error 404 NOT Found css file as picture below:
![image](https://user-images.githubusercontent.com/29789620/160852111-5a721c0c-5c9d-4b22-a533-02cf6b2c52dd.png)

 After that I had investigated plugin-techdocs-backend code lines and seen that new version of plugin-techdocs-backend have added the code lines check permission if it is enabled.

![image](https://user-images.githubusercontent.com/29789620/160851851-d1c41166-10c1-4206-899c-8e51a7c4b864.png)

## Expected Behavior
I hope we could load css without authorization check because the css file is public

**Comment by shanthisagar-dhanya-kumar-db** [comment]
You will need to enable permissions in app config and also set the auth secret. Also check whether you have set correct CSP


permission:
  enabled: true
backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See backend-to-backend-auth.md in the docs for information on the format
  auth:
    keys:
     - secret: ${BACKSTAGE_BACKEND_AUTH_SECRET}
  baseUrl: ${BACKSTAGE_BACKEND_BASE_URL}
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
    img-src:
      # "'self'" and 'data' are from the backstage default but must be set since img-src is overriden
      - "'self'"
      - 'data:'
      - 'https://backstage.io'
      - '${BACKSTAGE_BACKEND_BASE_URL}'

**Comment by lqlamTMA** [comment]
> - 'https://backstage.io'

As you known, the css path is usually public so that you can see in techdocs page. It have a link tag to get the css script as picture below. 
![image](https://user-images.githubusercontent.com/29789620/161209263-77b99752-8e6a-4fa3-bf69-1485544243ae.png)

But techdocs-backend plugin have added authorization as mentioned in document 
![image](https://user-images.githubusercontent.com/29789620/161209814-fe00f1f0-437c-41de-b8f4-777b7c10006c.png)


How can we add authorization to header in http request GET for css tag in html above?

**Comment by lqlamTMA** [comment]
Hi @freben ,

Do you have any idea about this case?

Thanks,
Lam Ly

**Comment by iamEAP** [comment]
Hey there!  In order to use TechDocs successfully with the permissions framework, you will need to include some extra code in your backend that sets the auth token on a cookie.  I believe the folks working on the permissions framework will have better documentation for this in place soon!  But for now, you can reference these docs to help you out: https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md

**Comment by jvyang** [comment]
Hi @iamEAP, is the said documentation already in place?

**Comment by iamEAP** [comment]
As far as I can see, this is documented most directly here (https://backstage.io/docs/permissions/getting-started#optionally-add-cookie-based-authentication), which provides some better context.

You'll see it still links out to the tutorial I linked to above though.

**Comment by manuelscurti** [comment]
Hi! same issue here, could not find a way to authorize static assets requests made by the browser when opening techdocs.
I already set up cookie-based authentication.

tagging some band members for visibility: @freben @vinzscam @jhaals

**Comment by billabongrob** [comment]
Has anyone found a workaround in the latest versions? I'm using the permissions framework at the moment as well.

**Comment by chipnesh** [comment]
[This](https://github.com/backstage/backstage/issues/21824) might help you

**Comment by jubafourali** [comment]
I also face the same problem with assets
