### ISSUE TITLE
create-app: remove sqlite/postgres decision

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#10534]
## Feature Suggestion

I'm suggesting that we remove the SQLite vs PostgreSQL decision that the user has to make as part of `npx @backstage/create-app`. In most setups, you will want to use both, SQLite for local development, and PostgreSQL for production. There are exceptions to this, but I'm thinking this is by far the most common use-case.

## Possible Implementation

The configuration for PostgreSQL could be part of the `app-config.production.yaml`, while we leave `app-config.yaml` with SQLite for development. Both configurations can be annotated with some further instructions.

I'm interested to hear if there are any thoughts on this from everyone. If it's something we think we should go forward with, we'd also be happy if someone else want to pick this up.

Curious what @backstage/techdocs-core thinks as well. Given that there's [feature detection](https://github.com/backstage/backstage/blob/64e7349e9bb44e981f4e53a409134e4980ac589d/packages/create-app/templates/default-app/packages/backend/src/plugins/search.ts.hbs#L25-L27) right now I'm thinking that we could make it the default? Don't know exactly how well the different implementations behave though, maybe it makes sense to just leave `Lunr` as the only default and direct the user to the other options instead?

## Context

`create-app` asks the user to select what DB they want [here](https://github.com/backstage/backstage/blob/64e7349e9bb44e981f4e53a409134e4980ac589d/packages/create-app/src/createApp.ts#L53-L58). That input is then used in the template [in](https://github.com/backstage/backstage/blob/64e7349e9bb44e981f4e53a409134e4980ac589d/packages/create-app/templates/default-app/app-config.yaml.hbs#L26-L46) [a](https://github.com/backstage/backstage/blob/64e7349e9bb44e981f4e53a409134e4980ac589d/packages/create-app/templates/default-app/packages/backend/package.json.hbs#L33-L35) [couple](https://github.com/backstage/backstage/blob/64e7349e9bb44e981f4e53a409134e4980ac589d/packages/create-app/templates/default-app/packages/backend/package.json.hbs#L43-L48) [of](https://github.com/backstage/backstage/blob/64e7349e9bb44e981f4e53a409134e4980ac589d/packages/create-app/templates/default-app/packages/backend/src/plugins/search.ts.hbs#L7-L9) [places](https://github.com/backstage/backstage/blob/64e7349e9bb44e981f4e53a409134e4980ac589d/packages/create-app/templates/default-app/packages/backend/src/plugins/search.ts.hbs#L19-L28)

**Comment by shanthisagar-dhanya-kumar-db** [comment]
If the plan is to use sqlite and not better-sqlite , we are up for this. better-sqlite has a ton of dependencies which our org doesn't support by default as part of the base OS image.

**Comment by Rugvip** [comment]
Bit of a separate discussion which exact implementation of SQLite we'd use to be honest. It's currently `better-sqlite3` by default, with the other option being `@vscode/sqlite3`. We switched over to `better-sqlite3` because of the lack of prebuilt binaries for `@vscode/sqlite3`, which in turn adds additional install dependencies.

**Comment by lalit774** [comment]
We should make a documentation for community. so they understand, why we use SQLite for local development, and PostgreSQL for production.

**Comment by iamEAP** [comment]
> _Given that there's feature detection right now I'm thinking that we could make it the default? Don't know exactly how well the different implementations behave though, maybe it makes sense to just leave Lunr as the only default and direct the user to the other options instead?_

Lunr as default has proven problematic for adopters, I think. It's not quite fully featured enough, so the default behavior seems "broken" by most standards (specifically with respect to how filters behave).

The local=lunr / production = PG (or Elastic) paradigm is less good for search, compared to other uses of PG too, given how differently they (can) behave. It might be okay when devs are working on anything in backstage _but_ search, but working on search related tasks with that split would be frustrating/impossible.

I also think we don't want to necessarily _default_ to PG. It _can_ act as a search engine, and it's pretty good at it, but I would imagine adopters would find a much healthier ecosystem around Elastic (in terms of help/support/articles/etc online) for how to tune search, compared with PG. The niche it's intended to fill in the backstage ecosystem is "get search without having to make your deployment environment that much more complex," not necessarily to be the end-all-be-all search engine.

...All of this is to say: probably default to Lunr? And then we need to have better documentation and perhaps even logging to nudge people toward more "production-ready" engines, depending on their needs.

**Comment by jhaals** [comment]
This issue will be fixed by #10948
