### ISSUE TITLE
Azure DevOps Plugin: Unable to import builds

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#10545]
## Expected Behavior

I want to have the summary of my builds in backstage.

## Actual Behavior

Unable to my builds reports : 

![image](https://user-images.githubusercontent.com/37327656/161012799-2970bef0-4028-44ec-8c7c-90f24acfdfce.png)

## Steps to Reproduce

1. Follow steps on the [plugin page](https://github.com/backstage/backstage/tree/master/plugins/azure-devops)

```ts
const cicdContent = (
  // ... Other Cases
    <EntitySwitch.Case if={isAzurePipelinesAvailable}>
      <EntityAzurePipelinesContent defaultLimit={25} />
    </EntitySwitch.Case>
  </EntitySwitch>
);
```

3. Configure a component with azure devops annotations

```yaml
  annotations:
    dev.azure.com/project-repo: MY_PROJECT/backstage
    dev.azure.com/build-definition: backstage
```
4. Got the CI/CD error page where nothing can be found.

## Context

I'm using Azure devops for my builds and I want to see a summary of my builds per projects. I already see the PullRequests page, so I think my Azure DevOps integration is set up correctly. *But AFAIK, this page use the <b>project-repo</b> annotation*

## Your Environment

```text
yarn run v1.22.18
OS:   Linux 5.10.16.3-microsoft-standard-WSL2 - linux/x64
node: v16.14.2
yarn: 1.22.18
cli:  0.16.1-next.0 (installed)

Dependencies:
  @backstage/app-defaults                               1.0.1-next.0
  @backstage/backend-common                             0.13.1, 0.13.2-next.0
  @backstage/backend-tasks                              0.2.2-next.0
  @backstage/catalog-client                             1.0.0, 1.0.1-next.0
  @backstage/catalog-model                              1.0.0, 1.0.1-next.0
  @backstage/cli-common                                 0.1.8
  @backstage/cli                                        0.16.1-next.0
  @backstage/config-loader                              1.0.0, 1.0.1-next.0
  @backstage/config                                     1.0.0
  @backstage/core-app-api                               1.0.1-next.0
  @backstage/core-components                            0.9.2, 0.9.3-next.0
  @backstage/core-plugin-api                            1.0.0
  @backstage/errors                                     1.0.0
  @backstage/integration-react                          1.0.1-next.0
  @backstage/integration                                1.0.0, 1.0.1-next.0
  @backstage/plugin-api-docs                            0.8.4-next.0
  @backstage/plugin-app-backend                         0.3.31-next.0
  @backstage/plugin-auth-backend                        0.12.3
  @backstage/plugin-auth-node                           0.1.6, 0.2.0-next.0
  @backstage/plugin-azure-devops-backend                0.3.10-next.0
  @backstage/plugin-azure-devops-common                 0.2.2
  @backstage/plugin-azure-devops                        0.1.20-next.0
  @backstage/plugin-catalog-backend-module-azure        0.1.2-next.0
  @backstage/plugin-catalog-backend-module-gitlab       0.1.1
  @backstage/plugin-catalog-backend-module-msgraph      0.3.1-next.0
  @backstage/plugin-catalog-backend                     1.0.0, 1.0.1-next.0
  @backstage/plugin-catalog-common                      1.0.0, 1.0.1-next.0
  @backstage/plugin-catalog-graph                       0.2.16-next.0
  @backstage/plugin-catalog-import                      0.8.7-next.0
  @backstage/plugin-catalog-react                       1.0.0, 1.0.1-next.0
  @backstage/plugin-catalog                             1.0.1-next.0
  @backstage/plugin-github-actions                      0.5.4-next.0
  @backstage/plugin-org                                 0.5.4-next.0
  @backstage/plugin-permission-common                   0.5.3
  @backstage/plugin-permission-node                     0.5.5, 0.5.6-next.0
  @backstage/plugin-permission-react                    0.3.4
  @backstage/plugin-proxy-backend                       0.2.25-next.0
  @backstage/plugin-scaffolder-backend                  1.0.1-next.0
  @backstage/plugin-scaffolder-common                   1.0.0, 1.0.1-next.0
  @backstage/plugin-scaffolder                          1.0.1-next.0
  @backstage/plugin-search-backend-module-pg            0.3.2-next.0
  @backstage/plugin-search-backend-node                 0.5.3-next.0
  @backstage/plugin-search-backend                      0.5.0-next.0
  @backstage/plugin-search-common                       0.3.2, 0.3.3-next.0
  @backstage/plugin-search                              0.7.5-next.0
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.14
  @backstage/plugin-tech-insights-backend               0.2.10
  @backstage/plugin-tech-insights-common                0.2.4
  @backstage/plugin-tech-insights-node                  0.2.8
  @backstage/plugin-tech-insights                       0.1.13
  @backstage/plugin-tech-radar                          0.5.11-next.0
  @backstage/plugin-techdocs-backend                    1.0.1-next.0
  @backstage/plugin-techdocs-node                       1.0.1-next.0
  @backstage/plugin-techdocs                            1.0.1-next.0
  @backstage/plugin-user-settings                       0.4.3-next.0
  @backstage/release-manifests                          0.0.2
  @backstage/search-common                              0.3.2, 0.3.3-next.0
  @backstage/test-utils                                 1.0.1-next.0
  @backstage/theme                                      0.2.15
  @backstage/types                                      1.0.0
  @backstage/version-bridge                             1.0.0
```

**Comment by benjdlambert** [comment]
@awanlin do you have any steps to troubleshoot and debug this?

**Comment by awanlin** [comment]
@LvffY looks like we have two things going on here:

1. Your annotations are not correct. This should help you out:

   - If you want to use the `dev.azure.com/project-repo` annotation to view builds for a specific Repo it requires two parts the Project name and the Repo name as per the [plugin README](https://github.com/backstage/backstage/tree/master/plugins/azure-devops#entity-annotation), like this: `dev.azure.com/project-repo: <project-name>/<repo-name>`. You only have one part which is why it's not working. If you are suing this annotation then you don't need the `dev.azure.com/build-definition`, it works with a single annotation.
   - If you want to view builds for a specific build definition then your `dev.azure.com/build-definition` annotation looks correct to me if `backstage` is a build definition name. You also need the `dev.azure.com/project` annotation to provide the project name like this `dev.azure.com/project: <project-name>` as per the [plugin README](https://github.com/backstage/backstage/tree/master/plugins/azure-devops#azure-pipelines-only)

3. I don't think the Pull Request page is working if these are your annotations, my gut tells me it's empty and not showing any data. I think there is a bug here and it should show the same missing annotation view. Could you post a picture of what you are seeing, please?

Finally I just want to clarify this statement: "I want to see a summary of my builds per projects". The Azure DevOps plugin does not support viewing all the builds for a project only by Repo or Build Definition, this has not been a use case that we had considered.

**Comment by LvffY** [comment]
@awanlin Thanks for the answer.

I'll double check the README to be sure everything was clear to me.

On my side, the *project-repo* annotations was correct I just removed too much things before posting my issue, I edited my post.

Now I'm seeing my PR/Builds on the overview page but not in my CI/CD page. Thanks :)

For your last question : to be honest, I didn't think about that either, I just miswrite what I thought (the englist is not my mother tongue). But, when I read your idea, I thought that could be a good idea.

I think this could lead to some global dashboards to be able to have such kind of grouped data.

**Comment by LvffY** [comment]
@awanlin After reading again the README, it's clear, just me that misread it.

**Comment by awanlin** [comment]
@LvffY awesome! No worries about anything your wrote, if something is not clear to me I just tend to ask, never hurts :)

If everything is working can we close this issue? If you would like the "project view" then I would log a feature request issue for that
