### ISSUE TITLE
Improve microsite menu experience on mobile

### ISSUE THREAD

**Issue by suuus** [backstage/backstage#10557]
The microsite currently has an (ever growing) menu. When visiting this website on a mobile browser, the menu takes up a lot of space. Also it overlaps text on the page you visit.
![image](https://user-images.githubusercontent.com/40822355/161127394-ef108e05-3b2a-4895-a911-764f11531341.png)

## Feature Suggestion

If a visitor opens the website on a mobile browser, the menu should not take up a lot of space and not overlap any text of the page itself.

## Possible Implementation

A possible solution would be switching the menu to a hamburger menu for mobile browsers and smaller screens.

**Comment by benjdlambert** [comment]
Wondering if our plan to bump to docusaurus 2 is going to help with this, or at least change the work that's required. Maybe it makes sense to wait for those changes first, but still open to someone writing some quick CSS changes if it's not that much work.

**Comment by mateusmarquezini** [comment]
Hey! I was giving a look around the opened issues here and I'd like to add some info about this enhancement request, a couple of months ago we were discussing improving the microsite menu on mobile, however, this would be possible only on docusaurus v2, which is still in beta. Then yes @benjdlambert, bumping to v2 would be possible by using a [navbar](https://docusaurus.io/docs/api/themes/configuration#navbar) property under the `themeConfig` prop. For those who want to give a look at how it works in action on [Codesandbox](https://codesandbox.io/s/github/facebook/docusaurus/tree/main/examples/classic?file=/docusaurus.config.js).

**Comment by liverday** [comment]
#11780
