### ISSUE TITLE
Catalog-graph plugin: Be able to customize nodes of the graph

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#10569]
## Feature Suggestion

To increase readability on catalog graphs, I'd like to be able to customize the color of the node of my graph, for example depending on their types (e.g team, component, service, resource, etc.) and after that, may be remove labels on the nodes and add the legend of my colors.

I didn't see anything about that in the page [Customize the look-and-feel of your app](https://backstage.io/docs/getting-started/app-custom-theme). 

## Context

With my team, we could have very large graphs. From now, this is actually pretty hard to see the difference between a node that is a **Team**, or a **Component** or a **Resource** for example. *I mean, we could read the labels, but on very large graphs it's not that easy*

**Comment by shailahir** [comment]
I had a similar requirement to this for EntityRelationsGraph.

Pushed two props renderNode and renderLabel in EntityRelationsGraph. Please see this file if it can be helpful to solve your use case.

https://github.com/backstage/backstage/commits/121211bb81c5b1b49419a868a2ec1af01a6d2c61/plugins/catalog-graph/src/components/EntityRelationsGraph/EntityRelationsGraph.tsx

https://github.com/backstage/backstage/blob/master/plugins/catalog-graph/src/components/EntityRelationsGraph/EntityRelationsGraph.tsx

Related issue #8850

**Comment by LvffY** [comment]
@shailahir Thanks, I think this could solve my problem.

Do you have any example of usage for this two attributes ? 

If it works, it only lacks of documentation on this IMHO.

**Comment by shailahir** [comment]
I have full example but cannot show it as is because of the org policies.

**Comment by shvmbisht** [comment]
@shailahir please provide some sample examples or documentation for this amazing contribution

**Comment by LvffY** [comment]
@shvmbisht Did not try it for now. Will try to test what @shailahir pointed and get back with some documentation on this point if we succeed.

**Comment by LvffY** [comment]
@shailahir TBH, I understand that your functions may solve my problem but I don't really get where to write and put such a function. 

A sample example (or at least a written explanation) could be really useful here.

**Comment by shailahir** [comment]
@LvffY Sure. Let me put together an example. I will share in a few hours after closing my day at work.

**Comment by LvffY** [comment]
@shailahir Did you have time to look at some example ?

**Comment by shvmbisht** [comment]
@shailahir no pressure but any news on those examples?

**Comment by shailahir** [comment]
Hi @shvmbisht @LvffY , Sorry for delay

I have created one example, please have a look

https://gist.github.com/shailahir/f6b0cb591e29a66001bf830329470849

**Comment by shvmbisht** [comment]
@shailahir @LvffY checkout this https://github.com/backstage/backstage/pull/12034

**Comment by LvffY** [comment]
@Neemys we need to try the solutions provided here

**Comment by Ijaz1-Mohammed** [comment]
Can we increase the height of overall canvas of the graph. I meant in a full page?
