### ISSUE TITLE
Sidebar highlight + new back button

### ISSUE THREAD

**Issue by kkat018** [backstage/backstage#10579]
## Feature Suggestion
If we navigate to an entity in backstage, you can notice that the sidebar catalog button is not highlighted implying that we are in the catalog page. 
<img width="439" alt="Screenshot 2022-04-01 at 17 19 25" src="https://user-images.githubusercontent.com/55915733/161303791-72ea7886-f4fa-4632-8a39-a7292cec002d.png">

Another feature that could be added is a back button on each entity page to easily navigate back to the respective catalog menu:

<img width="936" alt="Screenshot 2022-04-01 at 17 20 42" src="https://user-images.githubusercontent.com/55915733/161303941-dbe9d678-00ef-4989-9b94-c39ee4be6585.png">

## Possible Implementation
This would involve making small changes to the sidebar that has already been well implemented and a small button would be added next to the entity name in the top bar. 

## Context
I would like to work on this if this sounds like a good feature/improvement.

**Comment by awanlin** [comment]
Hi @kkat018, the back button sounds like a great idea!!! 

I'm not sure I understand the first item, though. When I go to an entity I do see the sidebar highlighted. For example from the demo site: https://demo.backstage.io/catalog/default/component/playback-order

![image](https://user-images.githubusercontent.com/67169551/161326284-dc108b0d-8c94-4be1-97d1-efbedea3aa87.png)

Are you saying that little bit of color on the side of the Home is not easy to see? That seems fair to say

That highlight is driven by this: https://github.com/backstage/backstage/blob/268f7faeeaecb8a211265af67494a06ca2160779/packages/theme/src/themes.ts#L76

**Comment by kkat018** [comment]
Thanks for your feedback @awanlin :) 
As you can see in the above screenshot, the sidebar in Expedia Backstage comes from OSS. I have verified all plugins and they are up to date. But the highlight seems to be missing/incorrect when navigating to an entity. 
Although, the screenshot you have shared is also highlighting home option whereas if we are navigating through the API menu, and are viewing an entity, shouldn't the 'API' option be highlighted instead oh 'Home'?

**Comment by awanlin** [comment]
@kkat018 I guess I'm wondering if your custom theme might be missing the `indicator` value: https://github.com/backstage/backstage/blob/268f7faeeaecb8a211265af67494a06ca2160779/packages/theme/src/themes.ts#L76

You are correct, when you are on an API in the catalog it will highlight the Home option and not the API option in the sidebar, that feels like a bug. I'm not sure what the correct fix would be. Technically APIs are just another Kind so having the Home highlights does make some sense but I can also see the other side too

**Comment by benjdlambert** [comment]
Looks like #10605 could be somewhat related here too. @katz95 also maybe something you might be interested in :)

**Comment by kkat018** [comment]
@awanlin The custom theme does use that indicator. 
I looked around and it looks like the links might be the reason. Everything with `/catalog` results in the Home item being highlighted. 

If the back button sounds promising, can I be assigned the task of adding that? :)

**Comment by freben** [comment]
I think we're holding off a bit on design input on that one.

**Comment by katz95** [comment]
Great suggestions! There should be an indicator on the menu item where the user started (before clicking a link into the next page). So if a user started in the API page and clicked on an API, there should be an indicator next to API in the menu. Currently, it moves back to 'Home' in the demo, which is a bit jarring. I like your proposal @kkat018.

Regarding the 'back' button, I wonder if the solutions proposed in #10605 might suffice for now. Do you all see any cases where the breadcrumbs might not suffice?

**Comment by shailahir** [comment]
We also faced similar issue. we wanted to have a correct breadcrumbs. team solved it using multiple fixed routes in the App.tsx file

/api/:namespace/:kind/:name
/catalog/:namespace/:kind/:name
/custom/:namespace/:kind/:name

Then updated the links to use this pattern
