### ISSUE TITLE
Add some equivalent feature at API to library component

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#10571]
## Feature Suggestion

We'd like to see more objects like [APIs](https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api), because it doesn't fit to every engineering teams.

Some examples I have thought of : 
- **CLI**s for libraries that provides CLI
- **Tool**s as a generic way to define anything you want
- (May be) **Package**s for just some kind of JavaDoc

I'm probably missing many examples, but I think this is a good start :)

## Context

I'm working in a team of data engineers. This is not a world where we have APIs (I mean, not in the « Web way »). Our « microservices » are just some kind of micro libraries. 

Backstage seems to us like a great way to modelize our architecture and dependencies, but I think we need more tools to generalize the needs of all developers.

**Comment by freben** [comment]
Hi! The "core" model is unlikely to grow appreciably in the near term, but it's [easy to extend](https://backstage.io/docs/features/software-catalog/extending-the-model) for your own needs!

On your specific examples:

- I'd say a cli could be kind `Component`, type `cli`
- I'd say generic tools depend on what they are, some might be `Component` + `website` for example; not sure they'd warrant being a special kind
- Packages - probably not, I'd say; that sounds like a poor fit for the catalog

Clarification on the last point: you'd more likely have a `Component` of type `library` for example, and then sure, you could use a processor to put the latest javadoc in its description, taken from your artifact store, if you like. And then likewise, you would have frontend plugins that let users list the available versions in your artifact store for that library.
