### ISSUE TITLE
Add the backstage.io/source-location annotation automatically

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#10582]
## Feature Suggestion

I'd like the Azure DevOps integrations to automatically add the `backstage.io/source-location`  to be available for others plugins.

## Context

I just setup the [TODO Plugin](https://github.com/backstage/backstage/tree/master/plugins/todo). Because the todo plugin waits for the  `backstage.io/source-location` to searches TODOs, I was forced to manually add the `backstage.io/source-location` to `backstage.io/source-location: url:https://dev.azure.com/myOrg/myProject/_git/myRepo`. 

Because this is exactly the link behind the "view source code" of my component, I think this annotation could be added automatically during the discovery of the project.

Of course, this should be optionnal i.e if one URL is already set on the component, the manually added value should be kept.

An optionnal feature could be to log a warning message if the manually set option equals the automatically set. *This last one is up to you IMHO*

My purpose is to use on Azure DevOps but I will also have the same requirements on Gitlab instance, so may be this could be added for all integrations ?

**Comment by freben** [comment]
Hm i think the idea is that that annotation is only used if the source location is NOT the same as the location of the entity yaml itself.

https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageiomanaged-by-location

So code should probably be ready to use either of those annotations, with the source-location taking precedence.

There's a helper function in the catalog model for this purpose.

https://github.com/BalaNarvar/BackStage1/blob/9b3b2e6594c111a5bf6d90183714dfd64625547f/packages/catalog-model/src/location/helpers.ts#L94

**Comment by LvffY** [comment]
@freben I'm not sure I understand your point.

To be explicit : In my case, if I remove the explicit annotation, the plugin didn't find the source code.

Based on that and your answer, do you mean that the fix should be done on the todo plugin itself ?

**Comment by freben** [comment]
Correct, it sounded to me like the plugin should be using that function if it doesn't already. And the benefit with that annotation is that ALL entities already have it, no matter what.

**Comment by LvffY** [comment]
@freben Not an expert, but it seems that the plugin does not use this helper method.

I found a custom method [getEntitySourceUrl in the TodoReaderService](https://github.com/backstage/backstage/blob/master/plugins/todo-backend/src/service/TodoReaderService.ts#L129) that exactly search for the **ANNOTATION_SOURCE_LOCATION** variable.

I think that replacing [the call for this function](https://github.com/backstage/backstage/blob/master/plugins/todo-backend/src/service/TodoReaderService.ts#L78) could solve the problem.

**Comment by freben** [comment]
Hm but unfortunately it does seem to try both annotations, doesn't it. So I'm not sure that it'll be functionally different to use the other function, but surely it's a nice removal of duplication in the code.

That does make me surprised though - why doesn't the old code work? Hmm

**Comment by LvffY** [comment]
@freben Yes this seems odd to me also that I didn't work (but I'm not a web app developer, so I may miss something ...)

To avoid merging something not necessary, is there anything I can do to test it on my own backstage instance first ?
