### ISSUE TITLE
Breadcrumbs in Entity Catalog page

### ISSUE THREAD

**Issue by mufaddal7** [backstage/backstage#10605]
Breadcrumbs is a very user-friendly way to navigate. Adding Breadcrumbs to Entity Page can be a good UI/UX addition to backstage.

## Feature Suggestion

- Add Breadcrumbs to [Entity Page](https://demo.backstage.io/catalog/default/component/searcher)
- All Entities aren't mapped to a system/domain, write conditions accordingly. 
- Display breadcrumbs only when applicable

## Breadcrumb Example

- Group > User 
- System > Domain > Component 

## Possible Implementation

On the top of the page or maybe inside the page header we can incorporate breadcrumbs. 

![Screenshot 2022-04-04 at 1 04 53 PM](https://user-images.githubusercontent.com/42934221/161495930-30f83505-6581-4432-babf-4c3a464733b1.png)

We received this feature request from a user, the purpose of making this change is to enhance navigation capability.

**Comment by benjdlambert** [comment]
I think that we probably want to have breadcrumbs everywhere, and maybe it would be good if they were context aware to know that you're on an entity page and want to navigate through the catalog model not just the navigation in the app. Gonna loop in @katz95 here for some input! 👍

**Comment by katz95** [comment]
This is a great suggestion, @mufaddal7 , and I like that you situated them underneath the Header! Thank you!

**Comment by mufaddal7** [comment]
@katz95 Let me know how we can proceed, maybe we can decide on the UI and then develop the component. Up to you.

**Comment by freben** [comment]
Can always discuss details in a PR as well. Sometimes you need to get your hands dirty before getting a feeling for where things fit best :)

I wonder how this will work for people who do NOT use the full domain / system / component pattern, or perhaps invent their own kinds entirely.

**Comment by mufaddal7** [comment]
Please Reopen, am working on this

**Comment by freben** [comment]
@mufaddal7 I hadn't seen that comment before - is this still the case?

**Comment by yashoswalyo** [comment]
Hey @freben I have been working on this issue, this is how I have implemented the Breadcrumbs.
On Entity page based on current relations, the header will show breadcrumbs in place of subtitle. 

https://github.com/user-attachments/assets/24ea0081-477a-4997-aac0-4f806e0ab312

>I wonder how this will work for people who do NOT use the full domain / system / component pattern, or perhaps invent their own kinds entirely.

for them, We can have a prop  which will be an array of relations, which will also be the priority of relation in which breadcrumbs will be formed.

**Comment by yashoswalyo** [comment]
@jhaals ^^
