### ISSUE TITLE
Entity registration not working when providing GitHub repo Url to the catalog import wizard

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#10603]
## Expected Behavior

The catalog plugin should find all `catalog-info.yaml` files within the GitHub repository and register them properly.

## Actual Behavior

The catalog plugin fails to find `catalog-info.yaml` files and throws the following error:

`Couldn't search repository for metadata file., received http response status code 422: Validation Failed: {"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}`

We are using GitHub app integration and the proper permissions are in place (except for the `Administration: Read & write` because we do not allow repo creation at the moment)

In the past, the issue was occurring sporadically, but now it happens every time.

I can add here that providing a direct URL to the existing `catalog-info.yaml` within the repo file works without issues, also GitHub discovery works without issues. The focus here is on the repo URL wizard approach in which case the catalog plugin should scan the repo and auto-register all `catalog-info.yaml` files.

Another useful thing that we discovered is that if the GitHub user executing this flow from our backstage instance (manually registering the files via GitHub repository URL) is added as a contributor to the target repo, the error is gone. But, this is simply not a scalable solution.

## Steps to Reproduce

- Open backstage instance
- Got to `catalog-import` page
- Provide a repository URL in the input field
- Click on `Analyze`

## Context

We have a lot of repositories scattered across a couple of GitHub organizations, containing multiple `catalog-info.yaml` files. A portion of them needs to be registered via the catalog import page and we want to minimize the manual registration effort as much as possible

## Your Environment

- Browser Information: Google Chrome 99.0.4844.84 

- Output of `yarn backstage-cli info`: 

```text
OS:   Windows_NT 10.0.19044 - win32/x64
node: v16.14.2
yarn: 1.22.11
cli:  0.16.0 (installed)

Dependencies:
  @backstage/app-defaults                         1.0.0
  @backstage/backend-common                       0.13.1
  @backstage/backend-tasks                        0.2.1
  @backstage/catalog-client                       1.0.0
  @backstage/catalog-model                        1.0.0
  @backstage/cli-common                           0.1.8
  @backstage/cli                                  0.16.0
  @backstage/config-loader                        1.0.0
  @backstage/config                               1.0.0
  @backstage/core-app-api                         1.0.0
  @backstage/core-components                      0.9.2
  @backstage/core-plugin-api                      1.0.0
  @backstage/dev-utils                            1.0.0
  @backstage/errors                               1.0.0
  @backstage/integration-react                    1.0.0
  @backstage/integration                          1.0.0
  @backstage/plugin-api-docs                      0.8.3
  @backstage/plugin-app-backend                   0.3.30
  @backstage/plugin-auth-backend                  0.12.3
  @backstage/plugin-auth-node                     0.1.6
  @backstage/plugin-catalog-backend-module-aws    0.1.3
  @backstage/plugin-catalog-backend-module-github 0.1.1
  @backstage/plugin-catalog-backend               1.0.0
  @backstage/plugin-catalog-common                1.0.0
  @backstage/plugin-catalog-graph                 0.2.15
  @backstage/plugin-catalog-import                0.8.6
  @backstage/plugin-catalog-react                 1.0.0
  @backstage/plugin-catalog                       1.0.0
  @backstage/plugin-github-actions                0.5.3
  @backstage/plugin-org                           0.5.3
  @backstage/plugin-permission-common             0.5.3
  @backstage/plugin-permission-node               0.5.5
  @backstage/plugin-permission-react              0.3.4
  @backstage/plugin-proxy-backend                 0.2.24
  @backstage/plugin-scaffolder-backend            1.0.0
  @backstage/plugin-scaffolder-common             1.0.0
  @backstage/plugin-scaffolder                    1.0.0
  @backstage/plugin-search-backend-node           0.5.2
  @backstage/plugin-search-backend                0.4.8
  @backstage/plugin-search-common                 0.3.2
  @backstage/plugin-search                        0.7.4
  @backstage/plugin-tech-radar                    0.5.10
  @backstage/plugin-techdocs-backend              1.0.0
  @backstage/plugin-techdocs-node                 1.0.0
  @backstage/plugin-techdocs                      1.0.0
  @backstage/plugin-user-settings                 0.4.2
  @backstage/plugin-xcmetrics                     0.2.23
  @backstage/release-manifests                    0.0.2
  @backstage/search-common                        0.3.2
  @backstage/test-utils                           1.0.0
  @backstage/theme                                0.2.15
  @backstage/types                                1.0.0
  @backstage/version-bridge                       1.0.0
```

**Comment by benjdlambert** [comment]
Hmm this is pretty interesting. Did this have anything to do with version bumps or anything? Do you have an existing PAT registered as well as a Github App? And the App is installed into the organisation etc that you expect to be indexing?

Sorry for the basic questions, but not sure what this could be without some more information 👍

**Comment by ProticM** [comment]
Hi @benjdlambert 

No worries 👍 

I would say it is not related to the version bump because it was happening sporadically before as reported. But on the other hand, it might be related to version bump because now it is happening every time.

We do not have PAT registered as an integration. For GitHub, the only auth integration we have is the GitHub application. And yes, the app is installed where required. For example, on the same orgs other manual registrations (like pointing to the file directly) are working fine. Also, the GitHub app is able to auto-discover the orgs (I assume because the targets for auto-discovery are also direct files specified via glob).

**Comment by ProticM** [comment]
Hi @benjdlambert Did you manage to get some time to try to reproduce this?

**Comment by ProticM** [comment]
Thanks @benjdlambert for looking into this.

It is possible for me to check it out, but I cannot promise the time when it will be prioritized. I have quite an amount of work internally.

Could you pin point the import plugin code block where this is happening? Is it somewhere along these [lines](https://github.com/backstage/backstage/blob/a807a2099585f0122e5459c7aa01a8be12a54c96/plugins/catalog-import/src/api/CatalogImportClient.ts#L218)?

**Comment by Xantier** [comment]
This is a feature that was noticed missing by one of our clients as well. We can grab this item and put it into our pipeline to start working on it if @ProticM is ok with that?

**Comment by ProticM** [comment]
@Xantier Sure, I have no problem with that 👍

**Comment by Xantier** [comment]
@benjdlambert, Unfortunately we haven't gotten to this item on our backlog yet.

**Comment by benjdlambert** [comment]
Assigned!
