### ISSUE TITLE
allow msgraph catalog plugin to work with extensions

### ISSUE THREAD

**Issue by pedroparraortega** [backstage/backstage#10606]
Microsoft Graph allow you to expand objects with extensions system.
https://docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0
https://docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0

Which are GA for users and groups.

## Feature Suggestion
Allow the processors to work with schemaExtensions so the information is fetched while reading.

## Possible Implementation
- Add optional configuration to the plugin to configure extra fields you want to fetch
- IF defined, configure the client to fetch this extra fields.
-
## Context
We are using msgraph plugin to populate our catalogue for users/groups and we are using schemaExtensions to add extra information to the groups. Information that we would like to add as annotations on the entities for future use cases.

**Comment by freben** [comment]
Is this something that you might be interested in contributing?

**Comment by pedroparraortega** [comment]
> Is this something that you might be interested in contributing?

sure, i will try to to create a PR for this.
