### ISSUE TITLE
[Plugin] Cloud Build

### ISSUE THREAD

**Issue by ljupchokotev** [backstage/backstage#1063]
## Summary

A plugin for integration with [Google Cloud Build](https://cloud.google.com/cloud-build)

Features that I could think of:
* Choose which GCP project to show
* Show logs for a specific build
* Show details for a specific build, like substitutions, options, env vars, duration, etc.

## Project website (if applicable)

https://cloud.google.com/cloud-build

## Context
Similar to the CircleCI plugin, a CI view for organizations using Cloud Build.

**Comment by stefanalund** [comment]
@ljupchokotev thanks for submitting a ticket! Are you planning on working on this yourself or do you want me to add a [help wanted] label?

**Comment by ljupchokotev** [comment]
Hi @stefanalund, you can add the [help wanted] label, I can't work on this right now.

**Comment by adamdmharvey** [comment]
Thinking this one was completed and included into the Plugin Marketplace with https://github.com/backstage/backstage/pull/2515 ?

![image](https://user-images.githubusercontent.com/33203301/105800753-77bad280-5f65-11eb-992c-d783a3073640.png)

Suggest this could be closed?
