### ISSUE TITLE
Feedback Icon/component in the Header

### ISSUE THREAD

**Issue by kkat018** [backstage/backstage#10642]
Developers at EG are looking to add a feedback component in the Header on most pages on Backstage.

## Feature Suggestion
As this icon would be placed in the Header, we would like to suggest changes in the component to have an end icon as part of the Header. 
<img width="1463" alt="Screenshot 2022-04-04 at 17 16 46" src="https://user-images.githubusercontent.com/55915733/161733247-52c61f26-c3a5-4b4c-9563-8875e35c6104.png">

## Possible Implementation

Option 1: (simple, short and customisable )
To make it customisable, a [prop](https://github.com/backstage/backstage/blob/6880fbfb328228e55cd376fd200f91560f8ff3ec/packages/core-components/src/layout/Header/Header.tsx#L107) could be added with no specified icon. Depending on the need, any icon could be added by the developer. This would mean that any icon can be added to every page that uses header, it would only require passing the specific params.

Option 2: (dedicated for feedback)
We could have just one component dedicated for feedback. This could be set to visible as and when needed. This option would be feasible where every page uses a separate header which could possibly be coded in 3-4 different repos. So instead of having a custom icon, the Feedback param could be enabled with one line of code.

## Context
Feedback is a good way to understand customer satisfaction. 
To make the process easier, it would be great if we could have the dedicated item in the header for feedback. This would reduce developer's hassle of going in and changing each page of each type (techdocs, entities, etc). 

I would like to add this to Backstage if it sounds like a good feature!

**Comment by freben** [comment]
Hi!

Initial reaction is - we don't have a super solid story for the composability of pages yet. It's currently a bit heavyweight and iffy to get stuff into the headers, in a general and nice way.

Would it make sense to consider using one of the feedback libraries / designs where there's a _floating_ feedback button instead, that's overlaying other things so that you don't have to place it specifically in the header in terms of the JSX structure? I think that would be a big simplification too.

**Comment by kkat018** [comment]
Hi @freben ! Thanks for your feedback.
We do have this option in consideration as a floating button. Maybe this could be added?

<img width="1456" alt="Design 2" src="https://user-images.githubusercontent.com/55915733/162710580-e646baf9-225c-49e5-97ac-d81d03ca0e03.png">

**Comment by freben** [comment]
At that point you wouldn't have to make any core additions at all, right? As in, you wouldn't have to make a pull request to the main repo here to make it work.

Having a nice functional feedback button as a common core-component for others to use could still be a nice addition!
