### ISSUE TITLE
Sonarqube fails with SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by mishrasmarajit** [backstage/backstage#10660]
## Expected Behavior

SonarQube plugin does not fetch data from sonar server and fails with SELF_SIGNED_CERT_IN_CHAIN

## Actual Behavior

The backstage app sits behind a proxy for me. When the sonarqube plugin tries to access the Sonarqube link it always fails with the below message
[1] 2022-03-31T15:12:14.714Z proxy error [HPM] Error occurred while proxying request [SELF_SIGNED_CERT_IN_CHAIN] (https://nodejs.org/api/errors.html#errors_common_system_errors) type=plugin

I tried setting the NODE_TLS_REJECT_UNAUTHORIZED=0 I have also set the 'strict-ssl': false in the yarn config.

Please let me know how I can resolve it here.

## Steps to Reproduce

N/A

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

yarn run v1.22.1
$ /home/backstage/main/test/sophos-backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.13.0-37-generic - linux/x64
node: v16.14.2
yarn: 1.22.1
cli:  0.16.1-next.0 (local)

Dependencies:
  @backstage/catalog-client       1.0.0
  @backstage/catalog-model        1.0.0
  @backstage/core-components      0.9.2
  @backstage/integration-react    1.0.0
  @backstage/integration          1.0.0
  @backstage/plugin-catalog-react 1.0.0
  @backstage/plugin-sonarqube     0.3.3
Done in 1.38s.

**Comment by freben** [comment]
Hi! I think this is the same thing as this one: https://github.com/backstage/backstage/discussions/6377

I'll close as a duplicate for now, but let us know whether this worked out for you or not.

**Comment by Renz2018** [comment]
@freben hi, I encountered the same problem, but the [discussions/6377](https://github.com/backstage/backstage/discussions/6377) connection is no longer accessible. Can you give me a solution?
