### ISSUE TITLE
Custom page for "entity not found"

### ISSUE THREAD

**Issue by shmaram** [backstage/backstage#10661]
## Feature Suggestion

Currently, when entering a page where the entity is not found there is a page provided by backstage (see image).
I would like to have the ability to create my own page for this scenario.

![image](https://user-images.githubusercontent.com/12017112/161914932-ed9f63af-1e32-4067-975a-8f5a644abb2f.png)

**Comment by freben** [comment]
No, it's fixed right now. The code is [here](https://github.com/backstage/backstage/blob/5ac9a0c2d4670f97b65207414443978f8d2cba19/plugins/catalog/src/components/EntityLayout/EntityLayout.tsx#L267) within the entity layout. Is there something in particular that you would like to change within it?

**Comment by shmaram** [comment]
The best solution would be to allow creating a custom page, we specifically will need to add instructions to our users on how to register their service (entity) to the catalog.

**Comment by freben** [comment]
HI! Yeah this might be reasonable to add as a feature. Sounds like we should add a component as an optional prop on [the props](https://github.com/backstage/backstage/blob/f7154d786b217567920711e8eb444350f6f6375c/plugins/catalog/src/components/EntityLayout/EntityLayout.tsx#L151) of [EntityLayout](https://github.com/backstage/backstage/blob/f7154d786b217567920711e8eb444350f6f6375c/plugins/catalog/src/components/EntityLayout/EntityLayout.tsx#L174).

How to best do this? We don't have a solid common pattern for how to do component-replacement props, but taking some inspiration from MUI we could add a prop like this:
 
```ts
NotFoundComponent?: React.ElementType;
```

or possibly

```ts
components?:  {
  NotFoundComponent?: React.ElementType;
};
```

The former is probably OK.

Is this something you'd like to contribute?

**Comment by shmaram** [comment]
Sure, I think that could be nice, can you point me to some docs on how to do that?

**Comment by freben** [comment]
Hm not exactly docs as such - the links in the previous comment show where and how to make the change, and besides that it's regular react programming.

**Comment by shmaram** [comment]
I meant docs on how to contribute to backstage , code structure , how to submit MR , etc...

**Comment by freben** [comment]
Oh - see the CONTRIBUTING.md in the root of the repo. But it's not very formal; make the changes, make sure to DCO sign your commits, submit a pull request here in github

**Comment by shmaram** [comment]
Hi 
I made the change but I'm unable to push my new branch, I get 403, is there any access I need to request?

**Comment by jhaals** [comment]
You need to first fork the repository and then create a PR towards our repository

**Comment by shmaram** [comment]
@jhaals Thanks!
PR submitted (https://github.com/backstage/backstage/pull/11047)

Can you tell me how is the process now?

**Comment by jhaals** [comment]
Thanks for the contribution! PR has been merged 🎉 . Closing this issue since the feature will be in the next release.
