### ISSUE TITLE
Techdocs : Different plugin support

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#10670]
Do we have plans to support the following mkdocs plugins for techdocs

  - schema_reader
  - pdf-export
  - monorepo
  - mdpo:
      languages:
        - en     # first language is the original
        - de
  - section-index
  - git-revision-date
  - git-authors
  - macros
  - mkdocstrings
  - charts
  - print-site

**Comment by garyniemen** [comment]
Thanks for your question @shanthisagar-dhanya-kumar-db - we will discuss and get back to you.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
We have managed to extend the capability of the mkdocs-techdocs-core and add some of those plugins internally.
So, closing it based on this

**Comment by wufei523** [comment]
I think this issue should be reopened. print-site plugin is still not supported
