### ISSUE TITLE
plugin-search and plugin-home depend on plugin-search

### ISSUE THREAD

**Issue by jhaals** [backstage/backstage#10672]
Just noticed that both `@backstage/plugin-techdocs` and `@backstage/plugin-home` directly depend on `@backstage/plugin-search` which causes the `versions:bump` command to complain in certain situation as it's not intended to directly depend on other plugin packages. Would it be possible to migrate over to a search-common package or similar instead?

**Comment by emmaindal** [comment]
Thanks for opening the issue @jhaals, we plan to move the reusable components that currently lives in @backstage/plugin-search (which the techdocs + home plugin uses) to something like a *-react package. Will that solve it do you think?

**Comment by emmaindal** [comment]
Assigning this to myself to start look into during my Goalie week starting on Monday!

**Comment by awanlin** [comment]
Hi @emmaindal, just wanted to mention that this is currently blocking us from upgrading from 1.1.0-next.1 to 1.1.0-next.2 

The Discord thread for this is here if you want the background: https://discord.com/channels/687207715902193673/961249157790728262

I'll tag you in there as well

**Comment by emmaindal** [comment]
Thanks @awanlin I'm starting to look into this now!
