### ISSUE TITLE
Add Template kind by default in the allow list of locations in a newly created Backstage's app config

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#10691]
## Feature Suggestion

Add Template kind by default in the allow list of locations in a newly created Backstage's app config

## Possible Implementation

Add `Template` in the list https://github.com/backstage/backstage/blob/c596db3757059ae729bdd5ad188954d009413392/packages/create-app/templates/default-app/app-config.yaml.hbs#L88

## Context

This is just one of those "good first experience" for newcomers to Backstage. I added a template to the list and realized the global allow list did not have Template. This could have saved me a few minutes of looking into logs. :)

**Comment by freben** [comment]
We decided against that explicitly (at the time) - templates are a thing that an org probably wants to manage and curate very explicitly, and that you may not want random users registering a large number of, cluttering the scaffolder page. It feels like registering templates by url, rather than config, may be best to leave blocked?

**Comment by OrkoHunter** [comment]
Yeah, that totally makes sense from a "security" point of view. There is definitely a tradeoff here. :)

My gut feeling here says we should optimize for easier onboarding with least number of surprises and blockers. There is not a huge risk even if this is done. We can ofcourse leave a comment in app-config.yaml saying `Template` should not be globally allowed as random users can clutter the scaffolder page or something like that (Same for users and groups).

**Comment by freben** [comment]
We talked about this this morning. I think we should discourage a location based approach to adding templates, in the first place. We do have a location example in config where the additional kind is allowlisted, and we should have docs highlighting that workflow too (maybe there's something we could do better there).

If an org wants to allow random people to add templates using locations at all, I think that should be a conscious decision. And it should probably then be coupled with docs that explain how to slap some permissions system sugar on top of that so you don't willy nilly blanket-enable it for the entire org.

Hence... sorry but still voting to not perform this change.

**Comment by OrkoHunter** [comment]
> I think we should discourage a location based approach to adding templates

Aha, I wasn't mindful about this. It's all good then!
