### ISSUE TITLE
Address bar location still shows authenticated route after user signs out

### ISSUE THREAD

**Issue by mhaley37** [backstage/backstage#10723]
## Expected Behavior
As a user, when I sign out of a backstage created app, I expect to be brought back to the Sign in page and have the address bar of the browser reflect this.

## Actual Behavior
While I am brought back to the Sign in page, the address bar of the browser does not reflect this.  It still shows the location of `/settings` which was the last route I visited prior to signing out:

<img width="1366" alt="Screen Shot 2022-04-07 at 5 13 19 PM" src="https://user-images.githubusercontent.com/2686352/162451339-9fbcebd1-1744-425d-8569-1da507388226.png">

## Steps to Reproduce

1. Scaffold an app via `npx @backstage/create-app`.  Setup at least two authentication providers, following the [steps here](https://backstage.io/docs/auth/), ( guest can be one).
2. Sign into the app -- using `Guest` is fine
3. Go to settings ( note that the address bar of browser shows `/settings` route correctly), choose kebab menu -> Sign out. 
4. User is brought back to sign in page

## Context
Users find it confusing that the address bar shows a location that doesn't reflect where they actually are.  

In our implementation, we have a custom signin page component we created that uses the `<Sidebar />` component.  This component relies on the address bar location to determine which `<SidebarItem />` item is _Active_ which then controls which item is highlighted (and adds a proper `aria-current` attribute). 

## Your Environment

This was reproduced on a freshly scaffold backstage app using: npx @backstage/create-app ( backstage version 1.0.0). I have verified this is still reproducible after updating to 1.1.0-next.2.

    Browser Information:

    Google Chrome 100.0.4896.60
    Mozilla Firefox 98.0.2

    Output of yarn backstage-cli info:

yarn run v1.22.17
$ /Users/michaelhaley/projects/temp/temp-backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 21.4.0 - darwin/x64
node: v16.14.0
yarn: 1.22.17
cli:  0.17.0-next.2 (installed)

Dependencies:
  @backstage/app-defaults               1.0.1-next.1
  @backstage/backend-common             0.13.2-next.1
  @backstage/backend-tasks              0.3.0-next.2
  @backstage/catalog-client             1.0.0, 1.0.1-next.0
  @backstage/catalog-model              1.0.0, 1.0.1-next.1
  @backstage/cli-common                 0.1.8
  @backstage/cli                        0.17.0-next.2
  @backstage/config-loader              1.0.1-next.0
  @backstage/config                     1.0.0
  @backstage/core-app-api               1.0.1-next.0
  @backstage/core-components            0.9.2, 0.9.3-next.1
  @backstage/core-plugin-api            1.0.0
  @backstage/errors                     1.0.0
  @backstage/integration-react          1.0.0, 1.0.1-next.1
  @backstage/integration                1.0.0, 1.1.0-next.1
  @backstage/plugin-api-docs            0.8.4-next.2
  @backstage/plugin-app-backend         0.3.31-next.0
  @backstage/plugin-auth-backend        0.13.0-next.1
  @backstage/plugin-auth-node           0.2.0-next.0
  @backstage/plugin-catalog-backend     1.1.0-next.2
  @backstage/plugin-catalog-common      1.0.0, 1.0.1-next.1
  @backstage/plugin-catalog-graph       0.2.16-next.2
  @backstage/plugin-catalog-import      0.8.7-next.1
  @backstage/plugin-catalog-react       1.0.0, 1.0.1-next.2
  @backstage/plugin-catalog             1.1.0-next.2
  @backstage/plugin-github-actions      0.5.4-next.1
  @backstage/plugin-org                 0.5.4-next.2
  @backstage/plugin-permission-common   0.5.3, 0.6.0-next.0
  @backstage/plugin-permission-node     0.6.0-next.1
  @backstage/plugin-permission-react    0.3.4, 0.4.0-next.0
  @backstage/plugin-proxy-backend       0.2.25-next.0
  @backstage/plugin-scaffolder-backend  1.1.0-next.2
  @backstage/plugin-scaffolder-common   1.0.0, 1.0.1-next.0
  @backstage/plugin-scaffolder          1.0.1
  @backstage/plugin-search-backend-node 0.5.3-next.0
  @backstage/plugin-search-backend      0.5.0-next.1
  @backstage/plugin-search-common       0.3.2, 0.3.3-next.1
  @backstage/plugin-search              0.7.4, 0.7.5-next.0
  @backstage/plugin-tech-radar          0.5.11-next.1
  @backstage/plugin-techdocs-backend    1.0.1-next.1
  @backstage/plugin-techdocs-node       1.0.1-next.1
  @backstage/plugin-techdocs            1.0.1
  @backstage/plugin-user-settings       0.4.3-next.0
  @backstage/release-manifests          0.0.2
  @backstage/search-common              0.3.2, 0.3.3-next.1
  @backstage/test-utils                 1.0.1-next.1
  @backstage/theme                      0.2.15
  @backstage/types                      1.0.0
  @backstage/version-bridge             1.0.0

**Comment by freben** [comment]
Agreed, logout behaviour could be made better. Is this something that you might be interested in contributing a fix for?

**Comment by mhaley37** [comment]
Sure @freben I would take a look to see if this could be improved a bit.
