### ISSUE TITLE
Enable Https on localhost 

### ISSUE THREAD

**Issue by shailahir** [backstage/backstage#10753]
I am trying to use an azure devops application with backstage but it requries a callbck URL with https enabled.

## Feature Suggestion
Is it a good idea to enable https on localhost for local development. so that we can test out integrations with the external services demanding for https on our local machine itself.

## Context
![image](https://user-images.githubusercontent.com/31934874/162713688-ef263c63-6343-4401-a0e2-bb26831633ff.png)

**Comment by freben** [comment]
Yeah you can do that - either by modifying your backend directly, or by adding a TLS terminating proxy in front of your local dev server.

Testing out https things locally is always a bit awkward :)

**Comment by shailahir** [comment]
Thanks let me try.
