### ISSUE TITLE
Provide "YellowStar" as a reusable component. 

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#10784]
## 🗒 General

I noticed `YellowStar` is a component that is created many times across the code base and thought that it makes sense to either export it from `catalog-react` alternative keep the color in the theme? I see the change of the color is changed in multiple places already and it would be nice to keep it consistent. 

https://github.com/backstage/backstage/blob/b6af1b73fcd5774d5f4b29860c3844b214018df6/plugins/catalog-react/src/components/FavoriteEntity/FavoriteEntity.tsx#L29-L33

https://github.com/backstage/backstage/blob/8f16051d466e21d6d33f2b5b47f32fb8ec911dad/plugins/techdocs/src/home/components/Tables/actions.tsx#L24-L28

https://github.com/backstage/backstage/blob/e1460a97c64a7ed7283f8363e82fca9eb6e0f44b/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L56-L60

## 💻 Usage

In any situations where I would like to use a star icon, just visually or with functionality (Button).

**Comment by Rugvip** [comment]
Linking #https://github.com/backstage/backstage/issues/9948 here. We duplicated this ahead of catalog 1.0 since we didn't really like the existing API. As far as I can tell the most popular way forward right now is the `FavoriteEntity.Icon` option

**Comment by djamaile** [comment]
@Rugvip  @emmaindal  should I close my MR to prevent further duplication? Not sure how to proceed there.

**Comment by Rugvip** [comment]
@djamaile we're happy to move forward with adding `FavoriteEntity.Icon` if that's something you'd like to implement! Otherwise I think it's best that we merge your PR tbh

**Comment by djamaile** [comment]
@Rugvip feel free to merge for now, currently on vacation. Will be back in the week of 2nd of May, will put this issue on my list 👍

**Comment by djamaile** [comment]
Still wanting to do `FavoriteEntity.Icon` or is system icons the way forward? @Rugvip
