### ISSUE TITLE
[TechDocs] clicking on an anchor of TechDocs page result in full page reload

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#10803]
## Expected Behavior

Scroll to the section and not do a full page reload (not needed as the page is not changing)

## Actual Behavior

Clicking on an anchor result in a full page reload

## Steps to Reproduce

1. Go to https://demo.backstage.io/docs/default/component/backstage/getting-started
2. Click on for example "Create your Backstage App" in the table of contents.
3. See the full page reload.

## Your Environment

Demo site https://demo.backstage.io/docs/default/component/backstage/getting-started

**Comment by iamEAP** [comment]
For what it's worth: I'm no longer able to reproduce this on the latest master branch (the demo site may be a couple of versions behind, at this point)

**Comment by emmaindal** [comment]
@garyniemen @iamEAP I can't seem to reproduce on latest master now either. This was reported internally which could have been the case that were a version behind or so. But I can't reproduce there now either, so I think we can close this issue and re-open if needed!
