### ISSUE TITLE
Allow publish azure action to use AD access token also

### ISSUE THREAD

**Issue by shailahir** [backstage/backstage#10809]
Hi, 

I am trying to create a software template that publishes to the azure repo. And I have an authorized access token each time when I submit the template for backend processing. I am setting the token in the template secret. But this access token is giving error that TF400813: The user '' is not authorized to access this resource. 

When I checked the publish azure action is working with personal access tokens. Can we make it accept an access token as well ?

https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/azure.ts

**Comment by Rugvip** [comment]
Probably, what's the different between an access token and a personal access token? 😅 

Also want to check whether there's actually something wrong with the token. You say the error is `The user '' is not authorized to access this resource.`, are you sure the issue isn't that the token doesn't grant access to create repos in azure?

**Comment by shailahir** [comment]
Sorry I mean bearer token :)

**Comment by shailahir** [comment]
Related https://github.com/backstage/backstage/issues/10865
