### ISSUE TITLE
Token is not removed from cookie after logout

### ISSUE THREAD

**Issue by Vegim** [backstage/backstage#10807]
## Expected Behavior
The token cookie should be deleted after the user logs out. 

## Actual Behavior

The cookie token still resides on the browser which is making possible to make API requests towards protected endpoints. 

## Steps to Reproduce

1. Logout from backstage
2. Inspect the cookies with developer tools

## Your Environment

- Browser Information: 
Google Chrome

**Comment by Rugvip** [comment]
What auth provider and what cookie would that be? Providers should be removing the cookie over [here](https://github.com/backstage/backstage/blob/c88845531361f9b75cd81a48d6d656e26e3fb381/plugins/auth-backend/src/lib/oauth/OAuthAdapter.ts#L203)

**Comment by Vegim** [comment]
I'm using the oauth2 authentication provider. Yeah I saw that part of the code that you send me but only the refresh token is being deleted and that way the user is able to do API calls backstage for about an hour after the access token expires

> What auth provider and what cookie would that be? Providers should be removing the cookie over [here](https://github.com/backstage/backstage/blob/c88845531361f9b75cd81a48d6d656e26e3fb381/plugins/auth-backend/src/lib/oauth/OAuthAdapter.ts#L203)

**Comment by Rugvip** [comment]
The access token is not stored in a cookie and is thrown away on logout. I will say that invalidation is something we should be adding to the passport integration in the auth backend, but that's not there yet.

What access token are you talking about in this case? Have you set up any custom access control of the Backstage APIs? The backstage APIs aren't protected by default. Might be that this is something you need to add to your own setup
