### ISSUE TITLE
Information Disclosure in error messages

### ISSUE THREAD

**Issue by drenusha79** [backstage/backstage#10806]
We are using Backstage and we need to avoid Information Disclosure in error messages

For example there are verbose error messages which contain SQL statements which triggered the error, also from some other error messages can be verified which files exist on the application server and which do not!

We want to have generic error pages or messages when getting errors.

**Comment by Rugvip** [comment]
Where are you seeing SQL errors being forwarded to the frontend? Would like to fix those 😁 

Apart from that the best way forward here is for you to register a custom error handling middleware. The backend service builder has a `setErrorHandler` which you can use to that end.
