### ISSUE TITLE
Possibility to display API definition in the API tab of service entity

### ISSUE THREAD

**Issue by iammnils** [backstage/backstage#10810]
## Feature Suggestion

Providing a possibility to display the API definition directly through the table of provided / consumed APIs within the API tab of the service entity.

## Possible Implementation

We have provided a quick demo video below on how it could be implemented.
Please feel free to provide us with any feedback!
(Implementation inspired by the awesome entity inspector).

https://user-images.githubusercontent.com/69042156/163194341-fefca670-6d5e-4701-a135-f3aa0393b7af.mov

## Context

It is a common use case in order to understand or use a service, to have a closer look at the API definition related to the service.

However to see the API definition provided or consumed by this service, the user has to navigate to the respective API entity subsequently its definition, which can make it a little laborious work with it.

The idea of this issue is to improve this by providing a possibility to display the API definition directly through the table of provided / consumed APIs within the API tab of the service.

**Comment by Rugvip** [comment]
Nice, love it! 🎉 :grin:

Is this something you'd like to contribute?

**Comment by iammnils** [comment]
Glad you like it! We are happy to work on the implementation! 🥳

**Comment by bendu89** [comment]
Yes, we will make sure that its ends up in one of the upcoming sprints :-)

**Comment by marcus-crane** [comment]
Ah, this seems really nice (go away stalebot 😛)
