### ISSUE TITLE
[Catalog] Error: Malformed envelope, /relations/0 should have required property 'target'

### ISSUE THREAD

**Issue by lqlamTMA** [backstage/backstage#10822]
When add a entity which have kind is group. In the entity, I had added relations with Entity  ormat as below:
![image](https://user-images.githubusercontent.com/29789620/163309927-f0671597-df95-4280-83bd-039546d5884e.png)

And then use applyMutation function to add the entities
![image](https://user-images.githubusercontent.com/29789620/163310258-6d865da3-3483-430f-a47e-f9365eaf562d.png)

Finally, I had got error as below.
`[{"name":"InputError","message":"Policy check failed; caused by Error: Malformed envelope, /relations/0 should have required property 'target'","cause":{"name":"Error","message":"Malformed envelope, /relations/0 should have required property 'target'","stack":"Error: Malformed envelope, /relations/0 should have required property 'target'\n    at SchemaValidEntityPolicy.enforce (D:\\Project TMA\\HumanaWin10\\backstg-pg\\node_modules\\@backstage\\catalog-model\\dist\\index.cjs.js:830:11)\n    at AllEntityPolicies.enforce (D:\\Project TMA\\HumanaWin10\\backstg-pg\\node_modules\\@backstage\\catalog-model\\dist\\index.cjs.js:911:35)\n    at DefaultCatalogProcessingOrchestrator.runPolicyStep (D:\\Project TMA\\HumanaWin10\\backstg-pg\\node_modules\\@backstage\\plugin-catalog-backend\\dist\\index.cjs.js:2284:56)\n    at DefaultCatalogProcessingOrchestrator.processSingleEntity (D:\\Project TMA\\HumanaWin10\\backstg-pg\\node_modules\\@backstage\\plugin-catalog-backend\\dist\\index.cjs.js:2242:27)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async processTask (D:\\Project TMA\\HumanaWin10\\backstg-pg\\node_modules\\@backstage\\plugin-catalog-backend\\dist\\index.cjs.js:1630:26)"}}]`

Error message: "Malformed envelope, /relations/0 should have required property 'target'". As you known, relations array just have atributes 'type' and 'targetRef' as picture below:
![image](https://user-images.githubusercontent.com/29789620/163310625-9064291b-6770-4f02-88ba-f67dc9550225.png)

**Comment by freben** [comment]
Essentially relations are always machine generated by processors (it's one of the things that a processor can emit). You can't provide them directly in the input entity; even if the validation would have passed, your input would promptly be overwritten by the stitcher process. I agree the error is confusing though!

**Comment by Rugvip** [comment]
I believe we want to tweak the validation here so that it forbids any form of `relations` in the input.
