### ISSUE TITLE
Backstage upgrade from v0.4.19 to v1.0

### ISSUE THREAD

**Issue by ankitnmalhotra** [backstage/backstage#10854]
We are upgrading current instance of Backstage i.e. v0.4.19 to v1.0. We merged the code and executed build pipeline which failed with the following exception

execution failed at Yarn install step.

**Resolving packages...
error Couldn't find any versions for "@microsoft/api-extractor-model" that matches "workspace:*"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find any versions for "@rushstack/node-core-library" that matches "workspace:*"****

Need experts help in resolving the issue so that we can get to the latest version of backstage and its features.

Expectation was that after merge the build will work and no exception specifically one with YARN INSTALL was not expected

## Steps to Reproduce

1. git commit -m "merge v1.0 code into current"
Must set username and email address using git config
2. git push --set-upstream origin dev-v1.0
**At this point the code is pushed up and CI build called “pipeline” should be running in GitHub
3. Pipeline build failed: 

## Context

Upgrade to v1.0 is impacted and its timelines.
Critical for the developer platform support and new features.

## Your Environment

Google Chrome.
Github Dev Branch is created for Merge
```

**Comment by Rugvip** [comment]
Hmm, those `workspace:` entries are very unexpected afaik. Was it perhaps just something like a bad publish that's been fixed now, or are you still experiencing the issue? Do you have any references to `@microsoft/api-extractor-model` in your project?

**Comment by ankitnmalhotra** [comment]
> Hmm, those `workspace:` entries are very unexpected afaik. Was it perhaps just something like a bad publish that's been fixed now, or are you still experiencing the issue? Do you have any references to `@microsoft/api-extractor-model` in your project?

Thanks for your reply!

Do you have any suggestion on the upgrade path? We are doing any upgrade from 0.4.19 to 1.0 using version bump. Is it supported for such difference? Quick help is appriciated.

**Comment by Rugvip** [comment]
By `0.4.19`, do you mean the create-app version or the release version from more than a year ago? If it's the latter it might actually be quickest to create a new app and copy things over, because there's been a big number of changes since then

**Comment by ankitnmalhotra** [comment]
Yes we noticed a difference of 25K commits between version 0.4.19 and 1.0. However, we are primarily looking into app an backend functionality only. 

Should we proceed or do you suggest to do intermediate update and then final update to v1.0

**Comment by jhaals** [comment]
That's very far back unfortunately. The best way forward is probably to create a new app and forklift whatever configuration or custom settings that you might have.

**Comment by ankitnmalhotra** [comment]
Thanks @jhaals (Johan Haals) and @Rugvip (Patrick).

Have you done such upgrades in past? We wanted to make sure that out path for upgrade is correct and we don't run into issue for face limitation (on additional features) by choosing incorrect path. 

If you can share your experience on such upgrades?

**Comment by benjdlambert** [comment]
@ankitnmalhotra I think that creating a new app and moving stuff across is possibly the best option here. Because we've been moving very quickly over the last year a lot of things have changed, and if the instance hasn't been updated it's probably going to be much more effort to convert it across rather than starting again and copying things across or re-implementing again. I'm not aware of anyone who's done such a big version upgrade.

**Comment by jcarres-mdsol** [comment]
@ankitnmalhotra  I've been keeping backstage up to date in our installation and definitely 0.4 to 1.0 is crazy amount of changes. The advise to create a clean app and removing/configuring as you had your current app is best approach
