### ISSUE TITLE
Getting scope errors while publishing to azure

### ISSUE THREAD

**Issue by shailahir** [backstage/backstage#10865]
## Expected Behavior
When using software templates with option to publish to azure repos with host "dev.azure.com". It should allow to publish to azure repo.

## Actual Behavior

But instead I am getting following errors. Authentication failed , application 'app name' asked for scope vso.build does not exist on the resource 'resource id'

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by shailahir** [comment]
![image](https://user-images.githubusercontent.com/31934874/163776353-76b5ecbf-5e01-4793-adfd-938abd12467f.png)

**Comment by shailahir** [comment]
Related to https://github.com/backstage/backstage/issues/7684 But for microsoft auth provider.

**Comment by jksalazar** [comment]
Podrías compartir la solución?

**Comment by elplaza** [comment]
I have the @shailahir error with:
- backstage 1.11.1
- auth providers microsoft configured as described in [docs](https://backstage.io/docs/auth/microsoft/provider#configuration)
- repourlpicker configured as described in [docs](https://backstage.io/docs/features/software-templates/writing-templates/#using-the-users-oauth-token) using azure

@shailahir how did you fix it?

**Comment by shailahir** [comment]
> I have the @shailahir error with:
> - backstage 1.11.1
> - auth providers microsoft configured as described in [docs](https://backstage.io/docs/auth/microsoft/provider#configuration)
> - repourlpicker configured as described in [docs](https://backstage.io/docs/features/software-templates/writing-templates/#using-the-users-oauth-token) using azure
> 
> @shailahir how did you fix it?

I created a new api ref using miscosoft auth and provided correct scope in it. Registered it in api.ts file then we can use it to get the token by calling it's methods in the component

**Comment by elplaza** [comment]
Thanks a lot @shailahir for the answer!
I haven't a so deep Backstage knowledge so I didn't understand what exactly do you mean for "calling it's methods in the component" and how I can create a new api ref, please can you describe the solution in more detail?
Thanks in advance

p.s. Couldn't this solution be a pull request?

**Comment by shailahir** [comment]
@elplaza  sorry for cryptic language, let me come up with some github gist. May take some time but will share.

**Comment by Phiph** [comment]
Hey @shailahir  I'm hitting this issue at the moment, any movement on your GIST, or guidelines on how you solved this problem :) Cheers!
