### ISSUE TITLE
[Catalog] Importing conflicting entities should result in an error

### ISSUE THREAD

**Issue by NishkarshRaj** [backstage/backstage#10862]
## Expected Behavior

Our teams register catalogs in Backstage via tagged sources for version controlling the documentation.

A catalog was initially registered from a certain tag (say v1.0.0). This version offers certain code and its associated TechDocs.

A new version from another is now registered (without unregistering the previous version).

Ideally, Backstage should show warning/errors during the Analysis phase of the Catalog Import process if both catalogs are using the same `[namespace]/[name]`.

We should then un-register the previous catalog and register via a new source (would be great if a method for making this switch more efficient and automatic exists/can be developed).

## Actual Behavior

The catalog from the newly tagged location passes the analysis phase and we can Import it to see its the new location is registered. But in reality, the catalog showcases information about the previously registered tag and we can view this in `Inspect Element` as well.

## Steps to Reproduce

1. Tag your Catalog Repository and register it within Backstage from the tagged location.

`https://gitlab.com/[namespace]/[name]/-/blob/1.0.0/catalog-info.yaml` 

<img width="576" alt="Screenshot 2022-04-16 at 8 42 20 PM" src="https://user-images.githubusercontent.com/35298207/163680636-6554e065-0cc0-4623-bea8-66a25beb7b18.png">

2. Make relevant changes to the repository (TechDocs, other catalog metadata, etc. but keeping the `metadata.name` intact) and tag the repository again.

`https://gitlab.com/[namespace]/[name]/-/blob/1.1.0/catalog-info.yaml` 

<img width="574" alt="Screenshot 2022-04-16 at 8 43 21 PM" src="https://user-images.githubusercontent.com/35298207/163680623-39779d67-0eea-4f23-9e19-d662c4effe0a.png">

3. Register the catalog Backstage from the newly tagged location.

4. Backstage showcases information of the previously tagged catalog instead of the latest and doesn't even give warning/errors while registering an already existing catalog from a new source.

<img width="1307" alt="Screenshot 2022-04-16 at 8 44 16 PM" src="https://user-images.githubusercontent.com/35298207/163680611-3972a03a-75ce-4d0a-8d78-8643cca6677e.png">

## Context

The issue affects us given the catalog management becomes tedious and we can have a false sense of documentation and code being showcased in Backstage is the latest. For example, v1.0.0 docs are shown because we thought the v1.0.1 catalog is successfully registered.

## Your Environment

- Browser Information: Google Chrome 97.0.4692.99

- Backstage v1.0.3

**Comment by NishkarshRaj** [comment]
@Rugvip thanks for the follow-up 👍 

> managing documentation versions through registering entities on different tags 

Okay, I believe the first line of the issue I raised seems a little ambiguous 😛 
Some of our portal's adopters tend to register their repositories (kind: Component) via tagged source rather than branched source and they share that the latest documentation for the services/applications (tech docs) is up to date to a certain tag.

This is the exact issue I want to solve by raising the issue given the new tag (or branches) is believed to be registered but in reality Backstage still showcases the previously registered metadata and docs around the repository.

**Comment by marcus-crane** [comment]
This is an issue I've run into recently where we currently have a bunch of entities centralised in a single repo but we fake the location through the use of the `source-location` annotation.

The idea is that as we verify who owns what (these things are not always clear!), we migrate those catalog entries to their true home in the repo but Backstage gets a bit confused if you don't unregister things in the right order and claims that an item is already registered when it isn't (or it'll claim to be registered but the entity is not visible)

**Comment by NishkarshRaj** [comment]
Not stale

**Comment by NishkarshRaj** [comment]
@Rugvip

**Comment by Rugvip** [comment]
I think the way forward here is to add a check at [this](https://github.com/backstage/backstage/blob/5b830da1b13a6318626763f7632096d37d08da16/plugins/catalog-backend/src/service/DefaultLocationService.ts#L130) point to see if any of the resulting entities already exists in the catalog. We'd probably want to check whether they existing in conflicting or non-conflicting ways too, i.e. whether the conflicting entity refs have the same or different location keys. @backstage/catalog-core, is this something you want to have a look at? I'm sure contributions are welcome too though :grin:

**Comment by sblausten** [comment]
@NishkarshRaj would this help your use case? https://github.com/backstage/backstage/pull/16660

**Comment by benjdlambert** [comment]
I'm wondering if we can close this now as https://github.com/backstage/backstage/pull/16977 was merged @sblausten?
