### ISSUE TITLE
"Your Backstage instance is too old" nudges in logs

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#10890]
## Feature Suggestion

Backstage maintainers should actively keep their core packages up-to-date. If upgrades are left ignored for months, the updates can be really painful with all the changelogs in several packages.

## Possible Implementation

Whenever Backstage frontend or backend starts, the system should check the backstage version (perhaps from the `backstage.json` file, if it exists) with the latest release on GitHub or NPM and print the information in logs.

**Comment by razumovich** [comment]
I see that there's some logging about outdated packages implemented for frontend (startFrontend.ts). I think there should be similar implementation for backend.
