### ISSUE TITLE
Update Identity resolver docs

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#10903]
## Expected Behavior

https://backstage.io/docs/auth/identity-resolver describes the currently expected way of how set up signIn resolvers
considering the latest changes from release 1.1.0 https://github.com/backstage/backstage/blob/master/docs/releases/v1.1.0-changelog.md#backstageplugin-auth-backend0130

## Actual Behavior

https://backstage.io/docs/auth/identity-resolver still uses deprecated fields and functions.

**Comment by Rugvip** [comment]
Very much on our radar but didn't have time to finish this for the release today 😅

**Comment by pjungermann** [comment]
Great! Thought about making a PR, too, but probably too late for me today so I just opened this issue. And you can explain it better anyways I think 😁
