### ISSUE TITLE
scaffolder-plugin - publish:gitlab: project id output

### ISSUE THREAD

**Issue by zhammer** [backstage/backstage#10907]
https://github.com/backstage/backstage/blob/8cc75993a627299ebfcf782c3cc2b5bee9d82008/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/gitlab.ts#L159-L163

any objections to returning the id for the gitlab project we created as an output for `publish:gitlab`? we are trying out software templates and would like to be able to use the id of the created gitlab project in steps that follow `publish:gitlab`.

happy to put up an MR!

**Comment by zhammer** [comment]
changes would be:
- make sure `client.Projects.create` can return the project id
- `const { http_url_to_repo, id } = await ...`
- update outputs on the `publish:gitlab` json schema (not breaking)
- set the output in the action handler

**Comment by jhaals** [comment]
Sounds like a good idea, feel free to send a PR/MR 😄 👍

**Comment by benjdlambert** [comment]
Looks like we have the `projectId` already in the action. We just need to add the output to the `jsonschema` at the top of the action and then use https://github.com/backstage/backstage/blob/27d130b232623d5577bed13b4d2e06872592f84e/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/gitlab.ts#L168 to call `ctx.output` :pray:

**Comment by Parsifal-M** [comment]
Hey, could I pick this up?

Seems like a good one to get my hands dirty.

Thanks!

**Comment by benjdlambert** [comment]
Sure! Go ahead @Parsifal-M! :pray:

**Comment by Parsifal-M** [comment]
Apologies, bit new to front-end.

Does the `jsonschema` start here? https://github.com/backstage/backstage/blob/8cc75993a627299ebfcf782c3cc2b5bee9d82008/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/gitlab.ts#L50 

So we'd add basically projectId/repoId somewhere there? as an `output` and not an `input`?

Thanks!

**Comment by benjdlambert** [comment]
Indeed, you would want to add it to here: https://github.com/backstage/backstage/blob/8cc75993a627299ebfcf782c3cc2b5bee9d82008/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/gitlab.ts#L97-L109

**Comment by Parsifal-M** [comment]
Hey I have made the PR above is this more or less what is expected? Can you confirm if I need to make a `changeset` for this? I read the docs but was not 100% sure if its needed, please let me know and I can do one.

Thanks!

**Comment by freben** [comment]
Closing as fixed.
