### ISSUE TITLE
Backstage cli - proxy not respected

### ISSUE THREAD

**Issue by dweber019** [backstage/backstage#10955]
## Expected Behavior
Proxy should be respected or configurable for the Backstage cli.

## Actual Behavior
Proxy related error. e.g.
```
FetchError: request to https://versions.backstage.io/v1/tags/main/manifest.json failed, reason: connect ETIMEDOUT 185.199.108.153:443
```

## Steps to Reproduce
Execute `yarn backstage-cli versions:bump` behind a proxy.

## Context
Maybe this article could be a starting point https://github.com/backstage/backstage/blob/2cfd5fe4444f9e4efaf68bc375be775ed583a939/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md

The issue was introduced with the package https://github.com/backstage/backstage/tree/master/packages/release-manifests, specifically with the usage of cross-fetch (node-fetch) in https://github.com/backstage/backstage/blob/master/packages/release-manifests/src/manifest.ts#L48.

## Your Environment
Node 16

**Comment by dweber019** [comment]
I would be happy to provide a PR.
My suggestion is to use `global-agent` from https://github.com/backstage/backstage/blob/2cfd5fe4444f9e4efaf68bc375be775ed583a939/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md in https://github.com/backstage/backstage/blob/master/packages/release-manifests/src/manifest.ts#L17.

**Comment by Rugvip** [comment]
Hmm, bit tricky tbh, since the `release-manifests` package is intended to be supported both in browsers and in node. Do suggest something in a PR if you have a solution to that though! 👍

**Comment by dweber019** [comment]
Do you have a use case where release-manifests is used in a browser? URL, action in Backstage...

**Comment by dweber019** [comment]
As far as I could see `release-manifests` is only used in `@backstage/cli`.
