### ISSUE TITLE
Scaffolder : Skipping the steps based on input parameter value

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#10961]
Let's say we have the scaffolder template file with the spec section as follows

spec:
  owner: backstage@list.db.com
  type: service
  parameters:
    - title: Kind
      required:
        - kind
      properties:
        kind:
          title: Kind
          type: string
          description: API / Component
          enum: ["API", "Component"]
    - title: ComponentType
      required:
        - componenttype
      properties:
        componenttype:
          title: Type
          type: string
          description: Website / Library / Service / Resource
          enum: ["website", "library", "service", "resource"]
- title: APIType
      required:
        - apitype
      properties:
        apitype:
          title: Type
          type: string
          description: OpenAPI / AsyncAPI
          enum: ["openapi", "asyncapi"]

Now there are three title elements
Kind
ComponentType
APIType

And lets say when the user selects the "API" kind then the ComponentType shouldn't be asked
And lets say when the user selects the  "Component" kind then the APIType shouldn't be asked

Is there any way we can control the steps here based on the input type of the previous steps?
Any pointers would be helpful.

**Comment by jhaals** [comment]
Hi!
Backstage uses [jsonschema-form](https://react-jsonschema-form.readthedocs.io/en/latest/) as the underlying library to render the forms, the difference is that we use yaml instead of json in our template.  This sound like something that might be possible with `OneOf`. I suggest you try it out in their playground at https://rjsf-team.github.io/react-jsonschema-form/

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Thanks for the suggestion. I was able to use the OneOf and was able to solve it.
