### ISSUE TITLE
[TechDocs] clicking on an item in the table of contents results in not scrolling to the respective anchor

### ISSUE THREAD

**Issue by iammnils** [backstage/backstage#11003]
## Expected Behavior

When clicking on `Prerequisites` item in the table of contents, the page should scroll to the respective anchor

## Actual Behavior

When clicking on `Prerequisites` item in the table of contents, the page is not scrolling to the respective anchor

## Steps to Reproduce

1. Go to https://demo.backstage.io/docs/default/component/backstage/getting-started/running-backstage-locally/
2. Click on for example `Prerequisites` in the table of contents.
3. See how the page is not scrolling to the correct anchor `Prerequisites`

## Your Environment

Demo site https://demo.backstage.io/docs/default/component/backstage/getting-started/running-backstage-locally/

**Comment by garyniemen** [comment]
This works as expected on our internal instance. Any thoughts @ottosichert ?

**Comment by Irma12** [comment]
Noticed same behaviour when navigating to 

https://demo.backstage.io/docs/default/component/backstage/features/software-catalog/#manually-register-components.

Trying to navigate to any item under (https://demo.backstage.io/docs/default/component/backstage/features/software-catalog/#adding-components-to-the-catalog) will lead to the bottom of the page.

**Comment by ottosichert** [comment]
Hey @iammnils, thanks for reporting!

I can not reproduce the issue, neither on our internal Backstage instance nor on the demo site linked above.

Which OS, browser and OS are you using? Do you possibly have any extensions that interfere with scrolling behaviour (such as smooth scrolling, or restoring page state)?

**Comment by iammnils** [comment]
Hey @ottosichert!

Thanks for having a closer look.

I am using MacOS Big Sur `v.11.4` and Brave `v.1.38.109` without any additional extensions that could have an impact on with the scrolling behaviour.

Below, you can find a video of the bug in action. 

https://user-images.githubusercontent.com/69042156/166422129-c6249367-2553-472f-881e-e4afc08a03c1.mov

**Comment by garyniemen** [comment]
@Irma12 @iammnils We can reproduce and will get back with an update

**Comment by iammnils** [comment]
Thanks a lot @garyniemen!

**Comment by emmaindal** [comment]
Hello @iammnils I can't reproduce this issue on the latest versions of techdocs

```
"@backstage/plugin-techdocs": "^1.2.1-next.1",
"@backstage/plugin-techdocs-react": "^1.0.2-next.0",
```
    
can I ask you to upgrade your versions and see if the issue still appears? If so please re-open the issue!

**Comment by lceconi** [comment]
@emmaindal @garyniemen Can we reopen this issue? I'm still experience the same behaviour @iammnils described.

**Comment by lceconi** [comment]
More details:
- I was able to reproduce the behaviour in Chrome v105.0.5195.125; MacOS v12.6
- The `scrollIntoView` is working correctly in Firefox
- There's a [lot of bug reports](https://bugs.chromium.org/p/chromium/issues/list?q=scrollintoview&can=2) about the use of `scrollIntoView` in Chromium browsers

**Comment by sqsp-rwatkins** [comment]
@emmaindal Can we get this reopened?
@garyniemen Any progress on the update?

We are seeing this on our local instance. I can also see the behaviour in the catalog docs, for example: https://demo.backstage.io/catalog/default/component/backstage/docs/conf
It doesn't happen on the other docs page at https://demo.backstage.io/docs/default/component/backstage/conf

I have reproduced it on Chrome, Brave and Safari. It works fine on Firefox
