### ISSUE TITLE
[TechDocs] svg failed loading throws error

### ISSUE THREAD

**Issue by kim5566** [backstage/backstage#11015]
## Expected Behavior

Render svg correctly with:

```
![test](../img/test.svg)
```

and test.svg starts with

```
<?xml version="1.0" encoding="UTF-8"?>
```

## Actual Behavior

```
Error: ../img/test.svg
```

## Steps to Reproduce

1. Have a markdown file with line `![test](../img/test.svg)`
2. Use Techdocs external publisher (in my case, it's GCS)
3. View documentation with above svg image

## Context

It works locally but failed rendering on live site

I've tried to log error in https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/transformers/addBaseUrl.ts#L66-L75:
```diff
          if (isSvgNeedingInlining(attributeName, elemAttribute, apiOrigin)) {
            try {
              const svg = await fetch(newValue, { credentials: 'include' });
              const svgContent = await svg.text();
              elem.setAttribute(
                attributeName,
                                `data:image/svg+xml;base64,${btoa(svgContent)}`,

                // `data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(svgContent)))}`,
              );
            } catch (e) {
+            console.log(e)
               elem.setAttribute('alt', `Error: ${elemAttribute}`);
            }
```

It said
```
DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```

## Suggested Solution

change the line `data:image/svg+xml;base64,${btoa(svgContent)}` to

`btoa(unescape(svgContent(xml)))`

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by tjrobinson** [comment]
For the record, I tried this in a recent version of Backstage and the SVG rendered fine.
