### ISSUE TITLE
Scaffolder : Passing login identity information from frontend to backend

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#11048]
It appears that we cannot pass the loggedin user identity information from scaffolder frontend to scaffolder backend plugins?
Or am I missing something here, tried various different options with vain.
Any pointers would be helpful

**Comment by benjdlambert** [comment]
Duplicate of #5441

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Thanks I will follow this up in another thread.
