### ISSUE TITLE
Documentation for adding icons to a backstage app

### ISSUE THREAD

**Issue by zhammer** [backstage/backstage#11044]
## Feature Suggestion

I'd like some documentation on adding icons to a Backstage app! Happy to help with this :).

The current [links documentation](https://backstage.io/docs/features/software-catalog/descriptor-format#links-optional) reads:

> NOTE: The icon field value is meant to be a semantic key that will map to a specific icon that may be provided by an icon library (e.g. material-ui icons). These keys should be a sequence of [a-z0-9A-Z], possibly separated by one of [-_.]. Backstage may support some basic icons out of the box, but the Backstage integrator will ultimately be left to provide the appropriate icon component mappings. A generic fallback icon would be provided if a mapping cannot be resolved.

As far as I can tell, however, how to set this up is not documented:

<img width="605" alt="screenshot of a search for icon on backstage.io with no relevant results" src="https://user-images.githubusercontent.com/6956487/164759703-0b1c0062-3488-4064-95c8-7644727bb7e8.png">

This has been asked several times in the Backstage discord. (examples: [1](https://discord.com/channels/687207715902193673/923144214580191282/948521337788461076), [2](https://discord.com/channels/687207715902193673/923144214580191282/928038661604405248))

## Possible Implementation

- Add documentation somewhere about the `icons` field in `createApp`
- Link to that documentation from the `links` note (or just place those docs inline)
- *bonus 1* provide some docs on creating custom icons! rather than just mapping in material-ui
- *bonus 2* provide an example or helper function to ingest all material ui icons into the icon mapping. currently i can't figure out a better way to do it than manually mapping in every material-ui icon (as in, importing every single icon and then adding it to the object with a key being its name - maybe in lower, camel, or snake case.) given this library is included by default in a backstage app i think it makes sense to allow for easy inclusion of all of its icons

## Context

One thing to note here is that in the [example entity](https://backstage.io/docs/features/software-catalog/descriptor-format#overall-shape-of-an-entity) there is a link with the icon `dashboard`. Given "Backstage may support some basic icons out of the box, but the Backstage integrator..." it's easy to assume that `dashboard` is a "basic icon out of the box", even though it's not included and falls back to the fallback icon.

**Comment by jhaals** [comment]
Thanks for bringing this up Zach and you're correct that this is not documented 😓 
There's definitely rooms for a docs section on system icons and contributions in that area would be highly appreciated! 

@timbonicus also created a recent PR example styling the demo app. We probably should do something similar for our the demo site in terms of icons but I think a docs section would go a long way.

**Comment by awanlin** [comment]
@zhammer with #12969 and #12973 merged in do you think that's enough to close this issue?

**Comment by zhammer** [comment]
yep i think so!
