### ISSUE TITLE
[TechDocs] Support all mkdocs CLI options in techdocs-cli

### ISSUE THREAD

**Issue by Niksko** [backstage/backstage#11055]
## Feature Suggestion

`mkdocs` supports a number of additional command line options, only some of which are supported by the techdocs-cli.
Instead of adding these one-by-one to the techdocs-cli, @iamEAP [suggested](https://github.com/backstage/backstage/pull/11052#pullrequestreview-951234069) that we just support all mkdocs CLI options in the techdocs-cli.

## Possible Implementation

Commander (the library used in the techdocs-cli to parse CLI options) [already supports](https://github.com/tj/commander.js/issues/1568) the common `--` syntax, to indicate the end of arguments that should be processed and the start or arguments that should be passed-through in some manner. This is enabled by default, it should just be a matter of passing these through to the underlying code as required.

## Context

Specifically, as per #10604, I'd like to be able to use the `--strict` flag of `mkdocs build`

**Comment by garyniemen** [comment]
Any concerns with this @iamEAP (I am guessing not) before I put the help wanted label on this.

**Comment by iamEAP** [comment]
Yeah, all good @garyniemen!  I think Nik was going to take a first stab at implementing this though, so maybe hold off on the label for now.

**Comment by andrewthauer** [comment]
I would still like to see this happen. We have currently a wrapper CLI around techdocs-cli that does some additional features that are not supported now. Supporting add `mkdocs` flags would be a step towards us being able to deprecate our custom CLI. I might take a stab at this at some point, but not sure when I'll be able to get to it.
