### ISSUE TITLE
[RFC] Add sample catalog entities and template to create-app template

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#11062]
**Status:** Open for comments

Bit of a lightweight RFC to see what everyone think of this change. Especially looking for feedback from people that recently created new Backstage apps, and whether this approach might've helped the path towards getting started with and understanding the software catalog.

## Need

When creating a new app using `npx @backstage/create-app` you are greeted with a couple of example entities to make sure there's a bit of content in the catalog. That example data is useful, but it doesn't really help much if you want to play around with catalog definitions yourself. For that the current template doesn't help you much, and you're left having to dig through the documentation even for trying out very simple tweaks.

## Proposal

Add a few very simple entity definitions to something like an `examples/` directory in templated apps. These can be quite heavily annotated with explanations for what role the various fields have, some commented out ones, and so on. We'd likely also include a software template in the examples, so that one can play around with a custom template as well.

## Alternatives

Keep things as they are right now.

Or we try to change the flow in some other way, for example through documentation.

## Risks

By placing the example entity definitions within the generated app we may create some confusion about the ways of working with entity definitions. Having them directly in the internal Backstage projects is not recommended, especially not when bringing them in using `file` locations, which we'd want to do. I see this as the biggest risk and downside of making this change, and would have to be clearly highlighted likely in more than one place.

**Comment by afscrome** [comment]
We used this local file approach very successfully in our initial prototyping of backstage - being able to experiment with models before without having to push anything remote made it very easy to get started.

The main gotcha we faced is we expected local file changes to be reflected in backstage instantly, but they didn't.  Initially we were restarting the backstage app every time to get changes to show up (which significantly slowed down development).  Eventually we discovered the "refresh entity" button which helped a lot, but wasn't immediately obvious.  It would be awesome if when using local files, if backstage could monitor the file system and automatically refresh entities when the filesystem is updated.

**Comment by afscrome** [comment]
Another consideration is whether the backstage upgrade helper should have knowledge o these "example" files and exclude them from it's diff.  If these are added in v.next , they'll produce a lot of noise for people when they try to upgrade from 1.1 -> v.next.

**Comment by freben** [comment]
Closed by #11068
