### ISSUE TITLE
Linking TechDocs images not working as expected

### ISSUE THREAD

**Issue by Xantier** [backstage/backstage#11060]
## Expected Behavior
It should be possible to have the possibility to link to an image within tech docs. 

There is a need, especially for technical documentation, to zoom into a diagram with a lot of boxes and lines. The easiest way to achieve this on MD sites is to link to the image itself which opens it up on a new tab and browser native functionality can be used. Using a link like `[![](assets/my_image.jpg)](assets/my_image.jpg)` should work and link to the image itself.

## Actual Behavior
The application tries to link to the image but because Docs and their assets are piped through the backend, displaying individual images is not possible.

## Steps to Reproduce
Use construct of tech docs img linking as stated above.

## Possible implementation
Add a new preRender function into Backstage plugins/techdocs/src/reader/components/Reader.tsx file, around the line ~240.
    This prerender function decorates images within the rendered page to be clickable as described as standard markdown functionality
        [ ![](image.jpg) ](backendurl/api/static/namespace/component/component-name/image.jpg)

## Your Environment
Standard browser.
S3 hosted tech docs.

**Comment by garyniemen** [comment]
Any concerns about this @ottosichert or @emmaindal before I put the good first issue label on it.

**Comment by ottosichert** [comment]
`[![](assets/my_image.jpg)](assets/my_image.jpg)` is valid Markdown and should be rendered correctly, so yes indeed thanks for reporting this issue!
