### ISSUE TITLE
[Kafka Plugin] - Provide ability to see messages for selected topic

### ISSUE THREAD

**Issue by mspedalettiHM** [backstage/backstage#11077]
## Feature Suggestion

It would be beneficial if users could select/click from the topic list that plugin already has and actually go into the specific topic to see the messages.
 
![Screen Shot 2022-04-25 at 14 29 53](https://user-images.githubusercontent.com/72824304/165142400-de763f02-e478-42a3-800a-d1792977db45.png)

## Context

 Easier kafka debugging. Probably Kafka-console-consumer could be introduced in the plugin?

**Comment by benjdlambert** [comment]
Thanks, sounds pretty interesting! Is this something you want to contribute? :pray:

**Comment by dweber019** [comment]
Nice idea. Just as an input, we have a permissions in place. Everyone is allowed to see which topics exist and what's the lag of a consumer group but not everyone is allowed to read the messages.

**Comment by dweber019** [comment]
@mspedalettiHM, @benjdlambert  created a PR for the dashboard urls, see https://github.com/backstage/backstage/pull/11644
