### ISSUE TITLE
Implement a "Component" virtual TechDocs Addon Location

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#11109]
## Feature Suggestion

A common pattern for [TechDocs Addons](https://backstage.io/docs/features/techdocs/addons) within Spotify is to allow documentation authors to place static content conforming to a specific format in markdown files, instances of which are then queried for and replaced in the TechDocs frontend with dynamic content at render-time.

To illustrate, imagine an "Embed TechDocs" Addon that allowed one to embed a page or section from one TechDocs site within another.

A TechDocs author could include something like the following in the markdown documenting a component in order to dynamically load and render generally applicable content hosted on a specific page (`/architecture`) under a specific section (`#diagram`) of a completely different entity's documentation (`default:system/foobar`):

```md
## Foo Architecture

This `foo` component is one piece of the `foobar` system, as illustrated here:

<TechDocsAddon entityRef="default/system/foobar" path="architecture#diagram">EmbedTechDocs</TechDocsAddon>

The specific details of `foo` are... (etc.)
```

This is _possible_ to implement now using a `Content`-location Addon and the `useShadowRootElements()` hook from `@backstage/plugin-techdocs-react`...  But given that it's a common pattern, it's worth simplifying the implementation.

## Possible Implementation

- Consider creating a `Component` virtual location in `@backstage/plugin-techdocs-react`.  Addons with this location could behave like a hybrid of a physical location Addon and a virtual location Addon.  Physical because the component would be expected to return a real element to be rendered, but virtual because 
- Consider using the proposed markdown/tag above as a basis for querying DOM elements.  Using a single `<TechDocsAddon>` tag would allow us to easily allow-list the tag in the TechDocs Reader's sanitization codepath.  Attributes on the tag could be passed transparently as props to the underlying component.  The inner text of the `<TechDocsAddon>` tag could correspond to the `name` of the Addon, and in case of failure, the default behavior / fallback is to just render the name of the Addon as text.

## Context

This is a follow-up to #9636

**Comment by riginoommen** [comment]
This issue should not be closed automatically. because we are looking on this 

https://backstage.io/docs/features/techdocs/addons#locations

**Comment by zhammer** [comment]
I was able to get this working using a Content addon and React's [createPortal]()

```tsx
import React from 'react';
import { useShadowRootElements } from '@backstage/plugin-techdocs-react';
import { createPortal } from 'react-dom';

const MyAddonComponent = () => {
  return (
    <p>This is my added component!</p>
  )
}

// Checks for any divs in the markdown with the attribute
// <div data-techdocs-addon="MyAddonComponent"></div>
// and adds our React component as a child.
export const Addon = () => {
  const divs = useShadowRootElements<HTMLDivElement>(['div']);

  return (
    <>
      {divs
        .filter(div => div.dataset.techdocsAddon === "MyAddonComponent")
        .map(div => (
          createPortal(<MyAddonComponent />, div)
        ))}
    </>
  )
}
```
