### ISSUE TITLE
GitHub login not working, no auth provider registered

### ISSUE THREAD

**Issue by ankitnmalhotra** [backstage/backstage#11119]
We have 2 auth provider configured Guest and Github.

We are getting the below exception with Github auth provider

{"error":{"name":"NotFoundError","message":"Auth provider registered for 'github' is misconfigured. This could mean the configs under auth.providers.github are missing or the environment variables used are not defined. Check the auth backend plugin logs when the backend starts to see more details.","stack":"NotFoundError: Auth provider registered for 'github' is misconfigured. This could mean the configs under auth.providers.github are missing or the environment variables used are not defined. Check the auth backend plugin logs when the backend starts to see more details.\n    at 

Github should open the redirect url for authentication

Updated App-config.yaml file

Section Integration and Auth as below

auth:
  providers:
    github:
      development:
        clientId:
          $env: AUTH_GITHUB_CLIENT_ID
        clientSecret:
          $env: AUTH_GITHUB_CLIENT_SECRET
      production:
        clientId:
          $env: AUTH_GITHUB_CLIENT_ID
        clientSecret:
          $env: AUTH_GITHUB_CLIENT_SECRET

integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-credentials.yaml

1. Start backstage
2. Got to login screen, click on Github auth 
3. Exception screen pop up pointing to localhost:7000/api/auth/github URL

## Context
We are not able to standup and import custom templates to our environment.

Note the same exception is observed during importing templates.

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by ankitnmalhotra** [comment]
C:\Users\amalhotra048\backstage>yarn backstage-cli info
yarn run v1.22.1
$ C:\Users\amalhotra048\backstage\node_modules\.bin\backstage-cli info
OS:   Windows_NT 10.0.19042 - win32/x64
node: v16.14.2
yarn: 1.22.1
cli:  0.17.1-next.0 (local)

Dependencies:
  @backstage/integration-react     1.0.1
  @backstage/integration           1.1.0
  @backstage/plugin-catalog-react  1.0.1
  @backstage/plugin-home           0.4.20
  @backstage/plugin-stack-overflow 0.1.0
Done in 4.75s.

**Comment by benjdlambert** [comment]
Think this is because now the user is not in the Catalog? Maybe these docs can help you get setup with the users from github into the catalog https://backstage.io/docs/integrations/github/org.

**Comment by ankitnmalhotra** [comment]
I have the following setup done . Still getting the same User not found exception. 

Not sure what is incorrect here. 

Members your inputs are appreciated.

Now I am also observing the following 
2022-05-02T16:35:31.669Z catalog warn **No processor was able to handle reading of github-org:https://github.com/backstage-anks** type=plugin entity=location:default/generated-<key>

Task completed as per documentation:


Create an Org "Backstage-anks" and a GitHub App inside "Backstage-ankit-app". It currently have one owner and 1 member.

I added following setting in app-config.yml file

organization:
  name: Backstage-anks

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

catalog:
  processors:
    githubOrg:
      providers:
        - target: https://github.com

  locations:
    - type: github-org
      target: https://github.com/backstage-anks
      rules:
        - allow: [User, Group]
auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

**Comment by benjdlambert** [comment]
What does your `packages/backend/src/plugins/catalog.ts` look like? And have you followed this guide for setting up Github Org data? https://backstage.io/docs/integrations/github/org#docsNav

**Comment by HieuMinh67** [comment]
I'm facing the issue, have you found the way to fix it? Please help me

**Comment by benjdlambert** [comment]
@HieuMinh67 can you provide more details, and maybe look through the conversation above to see if there's anything else that can help you in here first? What's the error message you're seeing?

**Comment by HieuMinh67** [comment]
> @HieuMinh67 can you provide more details, and maybe look through the conversation above to see if there's anything else that can help you in here first? What's the error message you're seeing?

<img width="1275" alt="Screen Shot 2022-07-11 at 15 09 21" src="https://user-images.githubusercontent.com/43398131/178220003-d07fd9e6-9fed-492e-b31e-3591b5f2f006.png">

This is the message I got and below is my app info

Dependencies:
  @backstage/app-defaults                          1.0.4-next.2
  @backstage/backend-common                        0.14.0, 0.14.1-next.2
  @backstage/backend-tasks                         0.3.2, 0.3.3-next.2
  @backstage/catalog-client                        1.0.3, 1.0.4-next.1
  @backstage/catalog-model                         1.0.3, 1.1.0-next.2
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.0-next.2
  @backstage/config-loader                         1.1.2, 1.1.3-next.0
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.4-next.0
  @backstage/core-components                       0.10.0-next.2
  @backstage/core-plugin-api                       1.0.3
  @backstage/errors                                1.0.0, 1.1.0-next.0
  @backstage/integration-react                     1.1.2-next.2
  @backstage/integration                           1.2.1, 1.2.2-next.2
  @backstage/plugin-api-docs                       0.8.7-next.2
  @backstage/plugin-app-backend                    0.3.34-next.2
  @backstage/plugin-auth-backend                   0.15.0-next.2
  @backstage/plugin-auth-node                      0.2.2, 0.2.3-next.1
  @backstage/plugin-catalog-backend-module-github  0.1.4
  @backstage/plugin-catalog-backend                1.2.0, 1.2.1-next.2
  @backstage/plugin-catalog-common                 1.0.3, 1.0.4-next.0
  @backstage/plugin-catalog-graph                  0.2.19-next.2
  @backstage/plugin-catalog-import                 0.8.10-next.2
  @backstage/plugin-catalog-react                  1.1.2-next.2
  @backstage/plugin-catalog                        1.4.0-next.2
  @backstage/plugin-github-actions                 0.5.7-next.2
  @backstage/plugin-org                            0.5.7-next.2
  @backstage/plugin-permission-common              0.6.2, 0.6.3-next.0
  @backstage/plugin-permission-node                0.6.2, 0.6.3-next.1
  @backstage/plugin-permission-react               0.4.3-next.0
  @backstage/plugin-proxy-backend                  0.2.28-next.0
  @backstage/plugin-scaffolder-backend             1.4.0-next.2
  @backstage/plugin-scaffolder-common              1.1.1, 1.1.2-next.0
  @backstage/plugin-scaffolder                     1.4.0-next.2
  @backstage/plugin-search-backend-module-pg       0.3.5-next.2
  @backstage/plugin-search-backend-node            0.6.3-next.1
  @backstage/plugin-search-backend                 0.5.4-next.1
  @backstage/plugin-search-common                  0.3.5, 0.3.6-next.0
  @backstage/plugin-search-react                   0.2.2-next.2
  @backstage/plugin-search                         0.9.1-next.2
  @backstage/plugin-tech-radar                     0.5.14-next.2
  @backstage/plugin-techdocs-backend               1.2.0-next.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.2-next.2
  @backstage/plugin-techdocs-node                  1.2.0-next.2
  @backstage/plugin-techdocs-react                 1.0.2-next.1
  @backstage/plugin-techdocs                       1.2.1-next.2
  @backstage/plugin-user-settings                  0.4.6-next.2
  @backstage/release-manifests                     0.0.4
  @backstage/test-utils                            1.1.2-next.1
  @backstage/theme                                 0.2.16-next.1
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

**Comment by benjdlambert** [comment]
Can you take a look at the previous comment from @Rugvip and answer this?

>Do you have AUTH_GITHUB_CLIENT_ID and AUTH_GITHUB_CLIENT_SECRET set in your local environment? Another option is to use your local app-config.local.yaml and put the plaintext configuration there directly?

**Comment by HieuMinh67** [comment]
> Can you take a look at the previous comment from @Rugvip and answer this?
> 
> > Do you have AUTH_GITHUB_CLIENT_ID and AUTH_GITHUB_CLIENT_SECRET set in your local environment? Another option is to use your local app-config.local.yaml and put the plaintext configuration there directly?

![Screen Shot 2022-07-11 at 15 59 56](https://user-images.githubusercontent.com/43398131/178228224-7cbb0c67-a2aa-4322-a96e-83f4470c3ef4.png)

Yes, I did put the plaintext configuration directly in app-config.yaml

**Comment by HieuMinh67** [comment]
> Ok and is the above file `app-config.yaml`?
> 
> And also what does your `packages/backend/src/plugins/auth.ts` look like?

Yes, above file `app-config.yaml` and I didn't change `packages/backend/src/plugins/auth.ts`

**Comment by fr0stf0x** [comment]
ref https://github.com/backstage/backstage/issues/11119#issuecomment-1180155022

You can provide a auth provider like this

```typescript
return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      github: providers.github.create({
        signIn: {
          resolver(info, ctx) {
            const { profile } = info;
            const { displayName } = profile;
            const userRef = `user:default/${displayName}`; // Must be a full entity reference

            return ctx.issueToken({
              claims: {
                sub: userRef, // The user's own identity
                ent: [userRef], // A list of identities that the user claims ownership through
              },
            });
          }
        },
      }),
    }
  });
```

**Comment by benjdlambert** [comment]
Going to close this then as fixed, please comment to re-open if something changes! :pray:

**Comment by asarenkansah** [comment]
@HieuMinh67 can you give a more detailed explanation of what worked for you? What does it mean that you "insert auth inside backend: in app-config.yaml"

**Comment by HieuMinh67** [comment]
> @HieuMinh67 can you give a more detailed explanation of what worked for you? What does it mean that you "insert auth inside backend: in app-config.yaml"

<img width="755" alt="Screen Shot 2022-08-17 at 19 39 19" src="https://user-images.githubusercontent.com/43398131/185130298-cccab18f-c41a-407b-9ddf-23960a9c7143.png">

Because there are 2 auth so I make a mistake

**Comment by KaranS-hexaware** [comment]
I have followed this discussion and tried everything... but still getting this error
`
{"error":{"name":"NotFoundError","message":"No auth provider registered for 'github'","stack":"NotFoundError: No auth provider registered for 'github'\n    at /workspace/backstagePOC/backstage-tutorial/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:3541:15\n    at handleReturn (/workspace/backstagePOC/backstage-tutorial/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /workspace/backstagePOC/backstage-tutorial/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at Layer.handle [as handle_request] (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:328:13)\n    at /workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:346:12)\n    at next (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:280:10)\n    at jsonParser (/workspace/backstagePOC/backstage-tutorial/node_modules/body-parser/lib/types/json.js:110:7)\n    at handleReturn (/workspace/backstagePOC/backstage-tutorial/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at jsonParser (/workspace/backstagePOC/backstage-tutorial/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at Layer.handle [as handle_request] (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:328:13)\n    at /workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:346:12)\n    at next (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:280:10)"},"request":{"method":"GET","url":"/api/auth/github/start?scope=read%3Auser%20repo&origin=https%3A%2F%2F3000-rapidxdevel-backstagepo-qgnhs2lefe6.ws-us93.gitpod.io&env=development"},"response":{"statusCode":404}}
`
Any solution?

**Comment by SarveshMishra** [comment]
@KaranS-hexaware you can just put `auth` and all values above backend in app-config

**Comment by SagnikGhosh-INT020** [comment]
> I have followed this discussion and tried everything... but still getting this error `{"error":{"name":"NotFoundError","message":"No auth provider registered for 'github'","stack":"NotFoundError: No auth provider registered for 'github'\n at /workspace/backstagePOC/backstage-tutorial/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:3541:15\n at handleReturn (/workspace/backstagePOC/backstage-tutorial/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n at /workspace/backstagePOC/backstage-tutorial/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n at Layer.handle [as handle_request] (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/layer.js:95:5)\n at trim_prefix (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:328:13)\n at /workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:286:9\n at Function.process_params (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:346:12)\n at next (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:280:10)\n at jsonParser (/workspace/backstagePOC/backstage-tutorial/node_modules/body-parser/lib/types/json.js:110:7)\n at handleReturn (/workspace/backstagePOC/backstage-tutorial/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n at jsonParser (/workspace/backstagePOC/backstage-tutorial/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n at Layer.handle [as handle_request] (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/layer.js:95:5)\n at trim_prefix (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:328:13)\n at /workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:286:9\n at Function.process_params (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:346:12)\n at next (/workspace/backstagePOC/backstage-tutorial/node_modules/express/lib/router/index.js:280:10)"},"request":{"method":"GET","url":"/api/auth/github/start?scope=read%3Auser%20repo&origin=https%3A%2F%2F3000-rapidxdevel-backstagepo-qgnhs2lefe6.ws-us93.gitpod.io&env=development"},"response":{"statusCode":404}}` Any solution?

Any updates? I am facing the same issue, tried everything listed here.

**Comment by Kartik494** [comment]
> > @HieuMinh67 can you give a more detailed explanation of what worked for you? What does it mean that you "insert auth inside backend: in app-config.yaml"
> 
> <img alt="Screen Shot 2022-08-17 at 19 39 19" width="755" src="https://user-images.githubusercontent.com/43398131/185130298-cccab18f-c41a-407b-9ddf-23960a9c7143.png">
> 
> Because there are 2 auth so I make a mistake

Hi @henrypham67  could you help me out , i followed this and addressed the changes but while sign-in i still got error as 
`Origin 'http://localhost:7007' is not allowed`

**Comment by FsRiachos** [comment]
Hi there, same issue here
`{"error":{"name":"NotFoundError","message":"Unknown auth provider 'github'","stack":"NotFoundError: Unknown auth provider 'github'\n    at <anonymous> (/home/fsriachos/backstage/node_modules/@backstage/plugin-auth-backend/src/service/router.ts:161:11)\n    at handleReturn (/home/fsriachos/backstage/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /home/fsriachos/backstage/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at Layer.handle [as handle_request] (/home/fsriachos/backstage/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:328:13)\n    at /home/fsriachos/backstage/node_modules/express/lib/router/index.js:286:9\n    at param (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:365:14)\n    at param (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:376:14)\n    at Function.process_params (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:421:3)\n    at next (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:280:10)\n    at /home/fsriachos/backstage/node_modules/express/lib/router/index.js:646:15\n    at next (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:265:14)\n    at Function.handle (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:175:3)\n    at router (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:47:12)\n    at handleReturn (/home/fsriachos/backstage/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at router (/home/fsriachos/backstage/node_modules/express-promise-router/lib/express-promise-router.js:64:7)"},"request":{"method":"GET","url":"/api/auth/github/start?scope=read%3Auser&origin=http%3A%2F%2Flocalhost%3A3000&flow=popup&env=development"},"response":{"statusCode":404}}`

![image](https://github.com/backstage/backstage/assets/48324462/c837e6d5-290c-460f-b177-8b6908f39f7f)

Any suggestions?

Thank you

**Comment by seslly** [comment]
> Hi there, same issue here `{"error":{"name":"NotFoundError","message":"Unknown auth provider 'github'","stack":"NotFoundError: Unknown auth provider 'github'\n at <anonymous> (/home/fsriachos/backstage/node_modules/@backstage/plugin-auth-backend/src/service/router.ts:161:11)\n at handleReturn (/home/fsriachos/backstage/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n at /home/fsriachos/backstage/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n at Layer.handle [as handle_request] (/home/fsriachos/backstage/node_modules/express/lib/router/layer.js:95:5)\n at trim_prefix (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:328:13)\n at /home/fsriachos/backstage/node_modules/express/lib/router/index.js:286:9\n at param (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:365:14)\n at param (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:376:14)\n at Function.process_params (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:421:3)\n at next (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:280:10)\n at /home/fsriachos/backstage/node_modules/express/lib/router/index.js:646:15\n at next (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:265:14)\n at Function.handle (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:175:3)\n at router (/home/fsriachos/backstage/node_modules/express/lib/router/index.js:47:12)\n at handleReturn (/home/fsriachos/backstage/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n at router (/home/fsriachos/backstage/node_modules/express-promise-router/lib/express-promise-router.js:64:7)"},"request":{"method":"GET","url":"/api/auth/github/start?scope=read%3Auser&origin=http%3A%2F%2Flocalhost%3A3000&flow=popup&env=development"},"response":{"statusCode":404}}`
> 
> ![image](https://private-user-images.githubusercontent.com/48324462/319811564-c837e6d5-290c-460f-b177-8b6908f39f7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTEzNDMsIm5iZiI6MTcxMzQxMTA0MywicGF0aCI6Ii80ODMyNDQ2Mi8zMTk4MTE1NjQtYzgzN2U2ZDUtMjkwYy00NjBmLWIxNzctOGI2OTA4ZjM5ZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAzMzA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYmU3YjYxODg0YjYyZGYwNmZmODJmOGFhMTNlMzdmZjQ0MDExMTU0ZTkxNTBlZWM3NDg1NTNkZTMyYzFmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gq9jfoPiU9kYq7dR86OnhbTQBGSi28_2jJ_cDJqt5gU)
> 
> Any suggestions?
> 
> Thank you

for anyone else having this error when setting up google oauth this is how I resolved it

`yarn add @backstage/plugin-auth-backend-module-google-provider` in ./packages/backend
and add the following to the backend/src/index.ts
```
backend.add(import('@backstage/plugin-auth-backend-module-google-provider'));
```

More information here:
https://backstage.io/docs/auth/identity-resolver#building-custom-resolvers

**Comment by hungryengineer** [comment]
I am also facing the same issue related to popup for SSO using Github not working

**Comment by stolliemods** [comment]
I followed the link from @seslly and added: -

`backend.add(import('@backstage/plugin-auth-backend-module-github-provider'));` to the backend/src/index.ts file.

Its now working. The guide seems to expect that value to already be there, however, its not in the index.ts file in the boilerplate deployment I used from the Getting Started guide.

**Comment by rowan04** [comment]
I had the "GitHub provider is not configured to support sign-in" issue. I ended up in a different issue thread, and adding the code stated in this answer fixed my issue: https://github.com/backstage/backstage/issues/23748#issuecomment-2089061001
