### ISSUE TITLE
backstage/plugins/gocd/ plugin with multiple gocd instance

### ISSUE THREAD

**Issue by VKZycus** [backstage/backstage#11142]
https://github.com/backstage/backstage/tree/master/plugins/gocd

Currently gocd plugly of backstage we can connect to only one instance :

proxy:
  '/gocd':
    target: '<go cd server host>/go/api'
    allowedMethods: ['GET']
    allowedHeaders: ['Authorization']
    headers:
      Authorization: Basic ${GOCD_AUTH_CREDENTIALS}

We need multiple instance of gocd in backstage like 

*proxy:
  '/gocd':
    target: '<go cd **server1** host>/go/api'
    allowedMethods: ['GET']
    allowedHeaders: ['Authorization']
    headers:
      Authorization: Basic ${GOCD_AUTH_CREDENTIALS}**
  '/gocd':
    target: '<go cd **server2** host>/go/api'
    allowedMethods: ['GET']
    allowedHeaders: ['Authorization']
    headers:
      Authorization: Basic ${GOCD_AUTH_CREDENTIALS}**
*'/gocd':
    target: '<go cd **server3** host>/go/api'
    allowedMethods: ['GET']
    allowedHeaders: ['Authorization']
    headers:
      Authorization: Basic ${GOCD_AUTH_CREDENTIALS}**

**Comment by benjdlambert** [comment]
When supporting multiple instances we would like to move this logic to a backend plugin. If you take a look at how the `jenkins` plugin works with `annotations` on the `entity` and then using the backend plugin will call out to the right `gocd` instance instead. We should basically copy the implementation from then `jenkins` plugin to `gocd` also.
