### ISSUE TITLE
backstage/plugins/gocd/ creating custom view for gocd pipelines

### ISSUE THREAD

**Issue by VKZycus** [backstage/backstage#11143]
By using below plugin

https://github.com/backstage/backstage/tree/master/plugins/gocd

We are able to get default view

<img width="960" alt="gocd-plugin-screenshot" src="https://user-images.githubusercontent.com/104554101/165705426-6a9349fb-c812-4362-b699-d36f0d7e0dc0.png">

can we get a custom view of pipeline using react.

**Comment by benjdlambert** [comment]
Is this something you want to contribute? :pray:
