### ISSUE TITLE
Integration failing between backstage and auth0

### ISSUE THREAD

**Issue by shahidv3** [backstage/backstage#11147]
## Expected Behavior

Integration should work between auth0 and backstage

## Actual Behavior
When tried to login via auth0 - it shows this message "auth0 - Origin "https://<teleport.url>" not allowed"

## Steps to Reproduce

Auth0 side steps
1. Log in to the Auth0 dashboard
2. Navigate to Applications
3. Create an Application
4. Name: Backstage (or your custom app name)
5. Application type: Single Page Web Application
6. Click on the Settings tab
7. Add under Application URIs > Allowed Callback URLs: http://xxxx/api/auth/auth0/handler/frame
8. Click Save Changes

Backstage side steps

followed steps as mentioned here
https://backstage.io/docs/auth/auth0/provider

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by benjdlambert** [comment]
Is `app.baseUrl` set the the address that you see in the address bar when browsing backstage? And that `baseUrl` is what is in the Allowed Callback URLs?

**Comment by freben** [comment]
I think I'm still a bit unclear on what the use case looks like. Why would the app base url be different from the other base urls? Is the browser for sure not on the teleport url?

Are you doing "local" development remotely here? Or is this a production setting? I'm confused.

The origin given in your auth provider's settings must match your browser location.

Side note: remember that these URLs should take care to have correct ports (if not 80 or 443) specified as well.

**Comment by shahidv3** [comment]
hi @freben @benjdlambert

this is how the high level block diagram of backstage ,teleport and auth0 looks like

1. User log on to teleport url
2. Launches backstage application
3. Backstage application launched successfully
4. SSO using auth0 (followed steps as mentioned here https://backstage.io/docs/auth/auth0/provider)
5. When tried to login via auth0 - it shows this message "auth0 - Origin "https"//xxxx" not allowed"

<img width="692" alt="image" src="https://user-images.githubusercontent.com/10008362/167284866-642dcf32-d333-44ca-a5d1-b5b6cbd5ba12.png">

**Comment by shahidv3** [comment]
> I think I'm still a bit unclear on what the use case looks like. Why would the app base url be different from the other base urls? Is the browser for sure not on the teleport url?

> [MS] please refer the above diagram. the use case is the backstage portal will be accessed via teleport url. And we are trying for SSO integration between auth0 and backstage portal.

> Are you doing "local" development remotely here? Or is this a production setting? I'm confused.

> [MS] _prod setting_

> The origin given in your auth provider's settings must match your browser location.

>  [MS] yes its matching with the teleport url

> Side note: remember that these URLs should take care to have correct ports (if not 80 or 443) specified as well.
> [MS] this is taken care

**Comment by Rugvip** [comment]
Have you tried setting `app.baseUrl` to `https://<teleport.url>`?
