### ISSUE TITLE
Tech Radar plugin should include the description

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#11169]
## Feature Suggestion

The Tech Radar plugin should include the description found at the bottom of [the Zalando version](https://opensource.zalando.com/tech-radar/).

This helps people understand how to use the Tech Radar.

The Backstage plugin version only has the radar itself.

**Comment by dweber019** [comment]
I thought exactly the same, when I implemented this at my company.
Additionally I think `use` should be renamed to `adopt`, according to the Zalando link.

I have created https://github.com/backstage/backstage/pull/11183.
Let's discuss how it should look like there 😉

**Comment by freben** [comment]
Closing since the PR was merged!
