### ISSUE TITLE
EntityHasComponentsCard should be able to show aggregated components

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#11187]
## Feature Suggestion

On the EntityPage of a Domain, I would like to use the `EntityHasComponentsCard` (or some other similar card) to list the Components which are part of the Systems in this Domain.

![Screenshot 2022-04-30 at 21 31 23](https://user-images.githubusercontent.com/562403/166121779-06ada615-23bf-48cd-862f-96ca606f54c5.png)

## Possible Implementation

Perhaps the `EntityHasComponentsCard` could take the `relationsType="aggregated"` prop like the EntityOwnershipCard does?

## Context

When learning about a new Domain, it's nice to be able to browse through the Components easily so you can understand what they do, and thus learn more about what is in the scope of this Domain.

It is possible to click through the Systems individually, but that may take some time.

**Comment by benjdlambert** [comment]
Think we probably want to mock this up a little bit with some examples. Does it make sense to group them in the table by System?
