### ISSUE TITLE
Search for Google Docs

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#11188]
## Feature Suggestion

Similar to the [Confluence search capability](https://github.com/backstage/backstage/pull/9742), there should be an ability to search Google Docs in Backstage.

## Possible Implementation

There appears to be a search API: https://developers.google.com/drive/api/guides/search-files

## Context

Migrating legacy technical documentation to Backstage can take some time when the migration involves many components and teams. While the migration is ongoing, it becomes difficult to know if the docs you're looking for are in TechDocs, Google Docs, Confluence etc.

It is useful to be able to go directly to Backstage and to search across all these platforms.

**Comment by garyniemen** [comment]
@dtuite Any current thoughts on this?

**Comment by dtuite** [comment]
@garyniemen nothing more than I described in the issue. I'm happy to try and answer specific questions if you have them?

**Comment by emmaindal** [comment]
Great suggestion @dtuite I think we could definitely have that as an optional collator to use for adopters. 

Were you thinking of indexing all documents on a drive or restrict it to documents containing specific title patterns or similar? From my own perspective I would love to index any technical documentation that could have ended up in google drive for some reason but not necessarily everything.

**Comment by dtuite** [comment]
@emmaindal What's the thinking behind indexing the documents in backstage vs. using the search API provided by Google directly?

My thinking is that it's likely that Google's search tuning is likely better than the PG or ElasticSearch search capabilities that the average Backstage installation would have.

**Comment by emmaindal** [comment]
@dtuite oh I just assumed that was what you meant as you pointed to the confluence collator as one example. I think from my perspective one benefit of indexing the documents to backstage search is that all documents will be scored with the same relevance model and you will not end up with competing relevance models. Another benefit is for "All" search that you don't need to add any additional implementation for a separate search query and aggregate the results returned from the search backend vs google api. 

If one don't care about including these results in "All" search and want to use Google Search API directly, you could do this already today. By implementing your own [`SearchApi`](https://github.com/backstage/backstage/blob/master/plugins/search/src/apis.ts#L24) and just add a check for when the `query.types` includes `google-docs` or something, and then make the request to google instead.

**Comment by caioq** [comment]
@dtuite Hello everyone, I'm working on an internal solution that can be used in this issue. If no one is working on this, can you assign me this issue, please?
My solution is to create a Collator integrated with Google Drive API and Google Docs API where it is possible to input a customized query if the developer wishes to limit the search to a specific directory or files.
