### ISSUE TITLE
Unregistered entities are not removed from "Your Starred Entities" Home card

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#11185]
## Expected Behavior

Unregistered entities should be removed from the list on the "Your Starred Entities" card.

## Actual Behavior

It stays in the list.

In my localStorage, I can see the following:

```
/starredEntities/entityRefs
["component:default/sample-service-1","component:default/concierge-1"]
```

concierge-1 is the component which was unregistered.

## Steps to Reproduce

1. Star a component in the catalog.
2. View the Home plugin Starred Entities card. It should show the component.
3. Unregister the starred component from the catalog.
4. View the Home plugin Starred Entities card. It will still show the component.
5. Click the component. You will see an error saying "Backstage was unable to load the entity."

https://www.loom.com/share/68090d5e80f04bf180c7877721773bc5

## Context

Users are confused and think Backstage is broken because they see an error when they click the component. in the list of starred entities.

## Your Environment

This is running on Roadie. I'm assuming this is a Backstage bug rather than a Roadie bug because I can't imagine we interfered with the way this card works. Please let me know if there's any chance this is a false assumption.

**Comment by benjdlambert** [comment]
Yeah, this is kind of tricky to do, as it's not just when you unregister something. It could be when someone else un-registers that component, or things get deleted. I wonder if it makes sense to add some revalidation logic here to validate that they exist. We also want to use the `displayName` of the entity too, so I wonder if makes sense to wrap that logic up in there when we grab the `displayName`?

**Comment by kuangp** [comment]
@benjdlambert I put up a PR that implements the logic you mentioned
