### ISSUE TITLE
Alternative text not provided for profile picture

### ISSUE THREAD

**Issue by claudiahub** [backstage/backstage#11196]
## Expected Behavior

Screen readers have enough information to provide context on profile image.

## Actual Behavior

1. Navigate to `Settings` in side nav, navigate to main section of the page.
2. Press F12 to open developer tool.
3. Verify in the HTML whether `alt` attribute is given to profile pic or not.

## Context

Alternative text is not provided for profile picture, thus not allowing screen readers users to provide context.

A11y Conformance Level: A

WCAG Success Criteria: 1.1.1

## Environment

Browser Information: 
Google Chrome v100.0.4896.127
Firefox 99.0.1
Safari 15.4

**Comment by benjdlambert** [comment]
Closing as #11202 fixed this
