### ISSUE TITLE
The "url:" prefix in "edit-url" is included in the catalog's "Edit Metadata" link and breaks the link

### ISSUE THREAD

**Issue by ericis** [backstage/backstage#11252]
## Expected Behavior

"Edit Metadata" strips the "url:" prefix from the configuration value.

## Actual Behavior

"Edit Metadata" includes the "url:" prefix from the configuration value and doesn't work.

## Steps to Reproduce

1. Register a "Component" with a "backstage.io/edit-url" that contains the "url:" prefix in the value before the actual URL
2. View the component in the catalog and click "Edit Metadata" button
3. Notice that the "url:" prefix was output in the link

### With the "url:" prefix

**Link in configuration with "url:" prefix**

![image](https://user-images.githubusercontent.com/974919/166464232-512501b4-d919-4367-b57d-29a400918f06.png)

**"Edit Metadata" button**

![image](https://user-images.githubusercontent.com/974919/166464294-0f44e527-250b-4cc1-9c74-2adddb283811.png)

**Link incorrectly includes "url:" prefix**

![image](https://user-images.githubusercontent.com/974919/166464340-be23242c-5d80-4978-9221-e29962848727.png)

### Without the "url:" prefix

The documentation seems to suggest not to use the "url:" prefix:
https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageioview-url-backstageioedit-url

However, when the prefix is not included, the "Inspect entity" links are then disabled, whereas the "url:" prefixed links work properly.

**"Inspect Entity"**

![image](https://user-images.githubusercontent.com/974919/166466029-cb57c5b9-3079-48f0-9851-29fa18bf9de5.png)

**"Inspect Entity" links work properly with the "url:" prefix**

![image](https://user-images.githubusercontent.com/974919/166466328-a4f772fd-558d-41f2-bd91-b51a7a97a107.png)

**Comment by freben** [comment]
These shouldn't have a `url:` prefix, that's just not the format it expects at all. Not sure that we should add code here and there that compensates for what's ultimately a wrongly entered value 🤔 Did you encounter this in the main repo or was it in some custom entities/code?

**Comment by Rugvip** [comment]
`url:` prefix should indeed not be there. The confusion seems to be caused by particular logic for rendering links in the entity inspector, so fixing that over here: #11490.

**Comment by ericis** [comment]
Great discussion @freben and @Rugvip . I know I've seen the `url:` prefix for other configurations like `backstage.io/source-location`. Is there an opportunity to clarify that perhaps the `url:` prefix should not be required for any configuration entries, since the project could rely on the scheme (e.g. http, https, git, etc.)?
