### ISSUE TITLE
[RFC] Kubernetes backend API update

### ISSUE THREAD

**Issue by mclarke47** [backstage/backstage#11309]
**Status:** Open for comments

## Need

There are currently 2 endpoints in the Kubernetes backend plugin

[**GET `/clusters` endpoint**][clusters]

This endpoint returns the configured Kubernetes clusters and the authorization necessary to access this cluster on subsequent calls.

[**POST `/services/:serviceId` endpoint**][service]

This endpoint takes user authorization details and an Entity and returns the matching Kubernetes resources determined by the [supported labels][labels]

Initially, only these endpoints were required, and the plugin only supported Kubernetes objects and not CRDs. However, due to the prevalence of CRD based technology: [Argo][argo], [Crossplane][crossplane] etc... it is becoming necessary to: 

1. Group Kubernetes objects together into canned queries that return only specific CRDs
2. Allow the UI to fetch only specified Resources that it is rendering, i.e. rendering a Crossplane resource without fetching all the Kubernetes objects

The old services endpoint (a misnomer) is not flexible enough to support these use cases.

## Proposal

[**POST `/services/:serviceId` endpoint**][service] will be removed and new endpoints with more flexible functionality will be added.

[**GET `/clusters` endpoint**][clusters] will remain unchanged.

New endpoint: **POST `/entity/get-workload-resources` endpoint**

```json
{
    "auth": {...},
    "entity": {...}
}
```

This endpoint will function like the existing [**POST `/services/:serviceId` endpoint**][service] endpoint. Serving objects relating to the [Kubernetes workload][canned] resources, which can be extended through configuration to include other resources including CRDs.

New endpoint: **POST `/entity/custom-resources` endpoint**

```json
{
    "auth": {...},
    "customResources": [
        {
            "group": "",
            "apiVersion": "v1",
            "plural": "pods"
        }
    ],
    "entity": {...}
}
```

This endpoint will fetch all objects defined in the `customResources` field related to the supplied entity.

While it isn't ideal that the UI needs to know the `group` and `apiVersion` this solution allows for the development of Kubernetes based UI plugins without needing to edit the kubernetes-backend-plugin or its config. 

## Alternatives

I tried extending the [**POST `/services/:serviceId` endpoint**][service] locally to incorporate the changes above, however the implementation was unweildly and I think adding a new endpoint it a preferrable solution.

## Risks

The main risk is polluting the UI plugins as they need to know the `group` / `apiVersion` / `plural`s to call services. This can make migration tricky when moving `apiVersion`. One solution could be to allow `apiVersion` wildcards which the backend would respect, the UI would then need to check `apiVersion` before rendering.

[clusters]: https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesBuilder.ts#L242
[service]: https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesBuilder.ts#L226
[labels]:https://backstage.io/docs/features/kubernetes/configuration#surfacing-your-kubernetes-components-as-part-of-an-entity
[argo]: https://argoproj.github.io/
[crossplane]: https://crossplane.io/
[canned]: https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesFanOutHandler.ts#L45

**Comment by mclarke47** [comment]
Still not 100% sure on the paths for the new endpoints, alternatives welcome!

**Comment by Rugvip** [comment]
Throwing in an option that we've tried out a little bit with some success, which is to have a general resource list endpoint that accepts an `entity` parameter. This leaves the implementation open for listing things by other dimensions than a single entity. You can limit the scope of the initial implementation by making the `entity` parameter required. You can find an implementation of that pattern over here: https://github.com/backstage/backstage/blob/c2a8f014935cdc0fe55c135191e3a2125f4004cf/plugins/todo-backend/src/service/router.ts#L51-L62

And continued here: https://github.com/backstage/backstage/blob/c10b8b8f9e7e3df0fd30f1cf24f97f020551da3d/plugins/todo-backend/src/service/TodoReaderService.ts#L62-L81

If you go that route the endpoints might be something like `/workload-resources` and `/custom-resources` instead. Or perhaps `/resources/workloads`, `/resources/custom`.

**Comment by magnusp** [comment]
I would welcome the possibility to limit the amount of request hitting the kubernetes apiserver(s). We have a setup with 3 datacenters serving multiple clusters over rancher. So a query for an entity would hit 3*clusters per DC while the entity could possibly only match 1 DC in 1 cluster. In some cases we do have matching entities in 3x3 clusters (development, acceptance and production) but are only interested in matching for production. Adding to this we have different requirements depending what context the user is in. Looking at a single service we want the complete view of an entity (deployment, pods, events, etc) and in contrast looking at the list of services for a team we are only interested in the deployments on the production cluster, extracting a specific label.

**Comment by mclarke47** [comment]
Hey @magnusp this is the intended use case for the [serviceLocatorMethod](https://backstage.io/docs/features/kubernetes/configuration#servicelocatormethod), it is used to filter the Kubernetes clusters so that only the clusters where a service is located gets called, however there are currently no implementations. I was thinking of adding a basic implementation that would scan the clusters on startup and create an in-memory index but haven't gotten around to it.

**Comment by goenning** [comment]
Should we also have an option to get k8s resources for multiple entities?

What I've seen on backstage so far is that most plugins API support a single-component in the request, which makes sense as they are often used on the EntityPage.

But when you own dozens of components, it's very time consuming having to open each component page to see k8s resources status.

We'd like to build a single page where teams can see an aggregate (not too detailed) of all services they own in context of k8s.

Could we extend that API to support multiple entities? Or would it be better to call that API N times? Maybe the former would be more efficient?
