### ISSUE TITLE
Update microsite search backend documentation regarding scheduler

### ISSUE THREAD

**Issue by ottosichert** [backstage/backstage#11301]
In https://github.com/backstage/backstage/pull/9770 we replaced `defaultRefreshIntervalSeconds` in favour of using a `TaskRunner`. The documentation on the microsite however is missing the updated change.

The content from the changeset could be used:

https://github.com/backstage/backstage/pull/9770/files#diff-7dfa4a1df97d6d9ea81ed8dd3007306abf954e9b68c2d9fea127e7b3e1e32d64R14-R47

```tsx
import { Duration } from 'luxon';

const schedule = env.scheduler.createScheduledTaskRunner({
  frequency: Duration.fromObject({ seconds: 600 }),
  timeout: Duration.fromObject({ seconds: 900 }),
  initialDelay: Duration.fromObject({ seconds: 3 }),
});

indexBuilder.addCollator({
  schedule,
  factory: DefaultCatalogCollatorFactory.fromConfig(env.config, {
    discovery: env.discovery,
    tokenManager: env.tokenManager,
  }),
});

// plus any other collators

indexBuilder.addCollator({
  schedule,
  factory: DefaultTechDocsCollatorFactory.fromConfig(env.config, {
    discovery: env.discovery,
    tokenManager: env.tokenManager,
  }),
});

const { scheduler } = await indexBuilder.build();
scheduler.start();
```

Reference:
https://github.com/backstage/backstage/blob/9348b8401a55847e07c75419d447ed6244603ea6/docs/features/search/how-to-guides.md?plain=1#L63-L81

**Comment by emmaindal** [comment]
closed by https://github.com/backstage/backstage/pull/11305
