### ISSUE TITLE
Azure auth provider doesn't work with latest version

### ISSUE THREAD

**Issue by nadworny** [backstage/backstage#11368]
## Expected Behavior

I'm able to sign in using the Azure provider.

## Actual Behavior

I'm getting the following error: `The Microsoft Active Directory provider is not configured to support sign-in`

![image](https://user-images.githubusercontent.com/1425919/167157112-c85e1a6e-e487-45f4-b399-b943f7e9e4f2.png)

## Steps to Reproduce

1. `npm i @backstage/create-app@0.4.26`
2. `npx backstage-create-app`
3. Replace generated App.tsx with the following https://gist.github.com/nadworny/cbe79d3a5a1e645efbd38c051edea621

## Context

These are the lines that I changed/added in the App.tsx:
```typescript
import { AlertDisplay, OAuthRequestDialog, SignInProviderConfig, SignInPage } from '@backstage/core-components';
import { microsoftAuthApiRef } from '@backstage/core-plugin-api';

const microsoftAuthProvider: SignInProviderConfig = {
  id: 'azure-auth-provider',
  title: 'Microsoft Active Directory',
  message: 'Sign in to Backstage Application using your Active Directory account.',
  apiRef: microsoftAuthApiRef,
};

const app = createApp({
  apis,
  components: {
    SignInPage: props => (
      <SignInPage
        {...props}
        auto
        provider={microsoftAuthProvider}
      />
    ),
  },
...
```

The exact same changes worked with the `@backstage/create-app@0.3.45`. 

Also, the documentation doesn't seem to be up to date as there is a dead link under https://backstage.io/docs/auth/microsoft/provider. The `Adding the provider to the sign-in page` at the very end doesn't exist:
```
Adding the provider to the Backstage frontend
To add the provider to the frontend, add the microsoftAuthApiRef reference and SignInPage component as shown in [Adding the provider to the sign-in page](https://backstage.io/docs/auth/#adding-the-provider-to-the-sign-in-page).
```

## Your Environment

- Browser Information: Edge Version 101.0.1210.32 (Official build) (arm64)

- Output of `yarn backstage-cli info`: 

```text
yarn run v1.22.17
OS:   Darwin 21.4.0 - darwin/x64
node: v14.18.3
yarn: 1.22.17
cli:  0.17.0 (installed)

Dependencies:
  @backstage/app-defaults                    1.0.1
  @backstage/backend-common                  0.13.2
  @backstage/backend-tasks                   0.3.0
  @backstage/catalog-client                  1.0.1
  @backstage/catalog-model                   1.0.1
  @backstage/cli-common                      0.1.8
  @backstage/cli                             0.17.0
  @backstage/config-loader                   1.1.0
  @backstage/config                          1.0.0
  @backstage/core-app-api                    1.0.1
  @backstage/core-components                 0.9.3
  @backstage/core-plugin-api                 1.0.1
  @backstage/errors                          1.0.0
  @backstage/integration-react               1.0.1
  @backstage/integration                     1.1.0
  @backstage/plugin-api-docs                 0.8.4
  @backstage/plugin-app-backend              0.3.31
  @backstage/plugin-auth-backend             0.13.0
  @backstage/plugin-auth-node                0.2.0
  @backstage/plugin-catalog-backend          1.1.1
  @backstage/plugin-catalog-common           1.0.1
  @backstage/plugin-catalog-graph            0.2.16
  @backstage/plugin-catalog-import           0.8.7
  @backstage/plugin-catalog-react            1.0.1
  @backstage/plugin-catalog                  1.1.0
  @backstage/plugin-github-actions           0.5.4
  @backstage/plugin-org                      0.5.4
  @backstage/plugin-permission-common        0.6.0
  @backstage/plugin-permission-node          0.6.0
  @backstage/plugin-permission-react         0.4.0
  @backstage/plugin-proxy-backend            0.2.25
  @backstage/plugin-scaffolder-backend       1.1.0
  @backstage/plugin-scaffolder-common        1.0.1
  @backstage/plugin-scaffolder               1.1.0
  @backstage/plugin-search-backend-module-pg 0.3.2
  @backstage/plugin-search-backend-node      0.6.0
  @backstage/plugin-search-backend           0.5.1
  @backstage/plugin-search-common            0.3.3
  @backstage/plugin-search-react             0.1.0
  @backstage/plugin-search                   0.8.0
  @backstage/plugin-tech-radar               0.5.11
  @backstage/plugin-techdocs-backend         1.1.0
  @backstage/plugin-techdocs-node            1.1.0
  @backstage/plugin-techdocs-react           0.1.0
  @backstage/plugin-techdocs                 1.1.0
  @backstage/plugin-user-settings            0.4.3
  @backstage/release-manifests               0.0.2
  @backstage/search-common                   0.3.3
  @backstage/test-utils                      1.0.1
  @backstage/theme                           0.2.15
  @backstage/types                           1.0.0
  @backstage/version-bridge                  1.0.1

```

**Comment by freben** [comment]
Hi,

See this article, https://backstage.io/docs/auth/identity-resolver

and this changelog entry https://github.com/backstage/backstage/blob/master/plugins/auth-backend/CHANGELOG.md#0130

**Comment by nadworny** [comment]
hi @freben
thanks... so if I get it right, I'll need to add an azure provider to the backend as well?

**Comment by nadworny** [comment]
I managed to get it running by adding the resolver to the `auth.ts` according to the documentation.

One thing that's really annoying, but maybe I set it up wrongly, is that once you enable the auth provider in `app-config.yaml` and setup your local environment, the authentication pop-up window calls the backend on port `80`, instead of the configured `7007` port. This makes local testing almost impossible. I managed to work around it by first starting UI on port 7007, invoking the UI in the browser which shows the login screen, then starting backend also on 7007 and clicking on the `Sing in` button. This is not perfect because after a successful authentication, everything breaks as the UI is not working anymore due to port conflict.

**Comment by nadworny** [comment]
Callback URL in Azure is defined with 7007 port so it must be something else 😕

**Comment by Rugvip** [comment]
The popup is opened towards the host that `backend.baseUrl` is configured to in the frontend, at least with the default app APIs. Could you double check that it's set correctly?

**Comment by nadworny** [comment]
Not sure what it was but now it's working ;) thanks!

What shall we do regarding this one:
`Also, the documentation doesn't seem to be up to date as there is a dead link under https://backstage.io/docs/auth/microsoft/provider. The Adding the provider to the sign-in page at the very end doesn't exist.`

**Comment by sxs737** [comment]
@nadworny Can you please share changes you made in backend auth.ts . I made changes as described in changelog entry above and it still does not work

**Comment by carlosdiazs** [comment]
Hello @nadworny,

Please could you share your azure ad resolver? Thank you

**Comment by nadworny** [comment]
@carlosdiazs you mean changes that I made in UI or backend?

**Comment by carlosdiazs** [comment]
Great!
Thank you for share with us, it works for me.
One question, where did you find support (documentation, forums...) to know how to setup the auth.js for Microsoft Azure AD? I didn't find any support searching in backstage site or outside backstage.

Regards

**Comment by nadworny** [comment]
thanks @awanlin , I'm aware of it. We have postponed azure ad sync for a later date.

**Comment by mustafazeya** [comment]
@nadworny @awanlin So if we are not using Azure discovery along with using Azure auth provider, users will not be able to login to Backstage using Azure AD credential?

**Comment by mustafazeya** [comment]
> @mustafazeya not exactly, the great thing about Backstage is it's pretty interchangeable, in our case we use YAML files for our users and Azure AD for Auth. So as long as there is a YAMl file for the user that logs in we can use `ctx.signInWithCatalogUser`. For those without they get an error about the user not existing, that may not be the exact wording though.
> 
> Does that help?

@awanlin Thanks but does that mean we will have to create a catalog file for each user who is supposed to authenticate using Azure AD? How does the mapping happen between catalog user and Azure AD(probably using email?).

**Comment by Rugvip** [comment]
@mustafazeya populating the catalog with users if the recommended approach, but you can also check out https://backstage.io/docs/auth/identity-resolver#sign-in-without-users-in-the-catalog. That example lets you create a user identity without interacting with the catalog.

**Comment by TeamDman** [comment]
Here's the docs page for auto ingesting Azure users

https://backstage.io/docs/integrations/azure/org

**Comment by anishaanil1** [comment]
@nadworny @sxs737 , Is this still working on the latest version of backstage. 
I'm seeing a deviation in the documentation and getting errors after the routing is returned from the Azure System

**Comment by awanlin** [comment]
Hi @anishaanil1, yes this is still working, can you log an issue with the problem you are having and all the related details please?
