### ISSUE TITLE
Code coverage file view does not show code

### ISSUE THREAD

**Issue by jeremyguarini** [backstage/backstage#11369]
When viewing files in the code coverage view, the file contents should be displayed along with line numbers and highlighting. Currently just a blank page with highlighted row numbers is displayed. No code is rendered. Now if I refresh the page and try to view the file contents, everything works as expected.

## Expected Behavior

When viewing a file in code coverage I expect to see the lines of code with the coverage highlights

## Actual Behavior

Blank page with line numbers is displayed

## Steps to Reproduce

generate code coverage report
upload report to backstage 
navigate to the component that has the coverage report
select a file in the file explorer
pop-up shows page with only line numbers

## Context

Unable to view the code

Nothing in jsconsole or backend logs

## Your Environment

OSX 12.3.1

able to reproduce in chrome Version 101.0.4951.41 (Official Build) (x86_64) and in safari Version 15.4 (17613.1.17.1.13)

- Output of `yarn backstage-cli info`: 

```text
$ yarn backstage-cli info
yarn run v1.22.1
$ /Users/jguarini/code/backstage_github_clone/node_modules/.bin/backstage-cli info
OS:   Darwin 21.4.0 - darwin/x64
node: v16.13.0
yarn: 1.22.1
cli:  0.17.1-next.0 (local)

Dependencies:
  @backstage/catalog-client           0.7.2
  @backstage/catalog-model            0.10.1, 0.11.0
  @backstage/cli                      0.15.3, 0.17.0
  @backstage/config-loader            0.9.7, 1.1.0
  @backstage/config                   0.1.15
  @backstage/core-components          0.8.10
  @backstage/core-plugin-api          0.6.1, 0.7.0
  @backstage/dev-utils                1.0.1
  @backstage/errors                   0.2.2
  @backstage/integration-react        1.0.1
  @backstage/integration              0.7.5, 1.1.0
  @backstage/plugin-catalog-react     0.6.15, 1.0.1
  @backstage/plugin-permission-common 0.5.3
  @backstage/plugin-permission-react  0.3.4
  @backstage/test-utils               1.0.1
  @backstage/types                    0.1.3
  @backstage/version-bridge           0.1.2
✨  Done in 1.92s.
```

![image](https://user-images.githubusercontent.com/23618053/167170363-e08b73f8-c9e6-4195-b0a7-9a8988690dd5.png)

**Comment by freben** [comment]
Thanks for your report. I don't use this plugin myself and don't have test data readily available - hopefully the plugin owners/contributors could pitch in. @alde any ideas?

**Comment by freben** [comment]
And of course - if you can get even more insights by inspecting the page and checking the HTML/react contents etc, it would of course help

**Comment by jeremyguarini** [comment]
yeh the page contents is empty on that initial load

<img width="1617" alt="Screen Shot 2022-05-19 at 5 28 12 PM" src="https://user-images.githubusercontent.com/23618053/169425217-0a469b9c-1596-43ba-8498-20ae136f5dfb.png">

Looking at the network request
.../api/code-coverage/file-content?entity=component%3Adefault%2Fbackstage&path=plugins/permission-common/src/PermissionClient.ts

the response payload does in fact have the file contents. So there's a disconnect somewhere between the response and the render.


I also see some deprecation notices in the js console, though I'm not sure they are related.

```
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
core.js:1490 Deprecated as of 10.7.0. Please use highlight(code, options) instead.
```
