### ISSUE TITLE
Gerrit integration: Implement scaffolder publish action

### ISSUE THREAD

**Issue by anicke** [backstage/backstage#11379]
## Feature Suggestion

A missing piece of the Gerrit Integration is support for publishing to new Gerrit projects with the "Scaffolder". This is issue is created to track our contribution of this feature.

## Possible Implementation

* A new RepoUrlPicker for Gerrit will be added.
* A new action in "scaffolder-backend" that will create and push to a new Gerrit project ("gerrit-publish").

**Comment by freben** [comment]
Sounds good!

**Comment by anicke** [comment]
Yes, you can assign me.
