### ISSUE TITLE
Supporting permissions integration in scaffolder templates

### ISSUE THREAD

**Issue by morganmspencer** [backstage/backstage#11403]
## Feature Suggestion

When developing templates with the permissions integration enabled it would be great to allow parts of the template form to show/hide based upon the user's permissions. This would be nice to have on both the individual field and section level.

## Possible Implementation

Could be implemented similarly to how the feature flags were in [this issue](https://github.com/backstage/backstage/issues/8870) / [this PR](https://github.com/backstage/backstage/pull/9665).

## Context

Implementing this feature would allow granular control over who can utilize certain form fields and sections. For example, maybe you have specific fields that you only want admin users to fill out and you do not want a base user to see these.

**Comment by ltdonner** [comment]
(Though I think it would be cool to have the option for either template level or actions)

**Comment by morganmspencer** [comment]
Yes I was going to say both would be great as well

**Comment by Joonpark13** [comment]
I think this is absolutely worth pursuing and is likely worth a PRFC in the near future. One thing we need to be mindful of is how this would interact with location permissions, which are conceptually related (if someone has write access to some catalog component through a scaffolder template, but doesn't have location write access, does that even make sense?). [Currently location permissions live separately](https://github.com/backstage/backstage/blob/6a1a644405d40b51a1a4c72aa8ae4515b578147d/plugins/catalog-common/src/permissions.ts#L94-L131), and that implementation will likely need a second look.

**Comment by benjdlambert** [comment]
Probably going to solve #12617 for a lot of use cases around the backstage product.

**Comment by padupe** [comment]
I believe this implementation is still valid. Because it would allow us to grant access to the templates to specific people, preventing (in the worst case scenario) all users from "randomly creating projects".

**Comment by Rugvip** [comment]
Fixed by #15798 🎉
