### ISSUE TITLE
[Tech Insights] Cron upgrade breaks backend-tasks: Error: Failed to persist task, TypeError: (intermediate value).sendAt(...).add is not a function

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#11401]
## Expected Behavior

Tasks should be scheduled as configured

## Actual Behavior

We are seeing the following error from Tech Insights when it starts up: "Error: Failed to persist task, TypeError: (intermediate value).sendAt(...).add is not a function". 

## Temporary Workaround

After some investigation we were able to determine the issue was due to Cron changing from `moment-timezone` to `luxon` in a patch version by mistake - https://github.com/kelektiv/node-cron/issues/611. Do not use version `1.8.3` of Cron!

A work around to this is to set your `resolutions` in your root `package.json` like this:

```json
"resolutions": {
    "cron": "1.8.2"
  },
```

## Steps to Reproduce

1. Create a Backstage instance: `npx @backstage/create-app`
2. Configure Tech Insights as per its documentation
3. Make sure the backend `techInsights.ts` file matches this: https://github.com/backstage/backstage/tree/master/plugins/tech-insights-backend#backend-example
4. Navigate to `\packages\backend`
5. Run `yarn start`

Notice that you will see the following warning in the logs: "Failed to schedule fact retriever entityOwnershipFactRetriever, Error: Failed to persist task, TypeError: (intermediate value).sendAt(...).add is not a function"

## Context

This has prevented the Tech Insights fact retrievers from running which has blocked some development internally using this plugin. With the workaround we are unblocked but this will be an issue for others and when we upgrade to version `2.0.0` of Cron which includes this change to using `luxon`. From a quick look only the `backend-tasks` uses Cron but we are not sure where it is all being used the way Tech Insights is.

## Your Environment

We've been able to determine that this issue is specifically found in version `1.8.3` and `2.0.0` of Cron

**Comment by Xantier** [comment]
I believe this is likely the time to modify that cron scheduler of tech-insights to use the now released task scheduler package. The initial built-in cron functionality is standalone for tech insights and really just supports a single instance deployments natively. With those mods, we should be able to get rid of that cron dependency in favour of the tasks module

**Comment by Rugvip** [comment]
Thank you for reporting! I believe this is now fixed, as `1.8.3` seems to have been removed from NPM. Gonna close, but chime in if that doesn't make sense 😁

**Comment by awanlin** [comment]
@Rugvip Cron `2.0.0` also has this issue 😞  but I think @Xantier's plan makes the most sense to me

**Comment by Rugvip** [comment]
But we're not in `2.0.0` right? :p

**Comment by freben** [comment]
And besides, the central task scheduler had the same issue (uses the same cron library). So we'll have to take appropriate action whenever we bump to 2.0 there too.

**Comment by awanlin** [comment]
Yes, you are both right, I think I was more saying we'll need to keep this in mind whenever we go to 2.0, this is totally fine to stay closed 👍

**Comment by pjungermann** [comment]
@Rugvip seems like 1.8.3 was marked as "deprecated" but not removed. I was just running into the same issue.

**Comment by Rugvip** [comment]
Yep, can confirm that I got 1.8.3 installed in a new app. That's some less than desirable behavior ._.

**Comment by Xantier** [comment]
> And besides, the central task scheduler had the same issue (uses the same cron library). So we'll have to take appropriate action whenever we bump to 2.0 there too.

Just revisiting the tech-insights loop after a long while and noticed that the work to migrate that specific cron job has already been contributed and tech-insights is using the central task mgmt. That doesn't help in this specific case apart from the fact that modifications need to be made in a single place only now.

**Comment by Rugvip** [comment]
Properly fixed in #11462
