### ISSUE TITLE
[Search] Make entity annotations searchable by default

### ISSUE THREAD

**Issue by jcarres-mdsol** [backstage/backstage#11407]
Currently  `DefaultCatalogCollator` does not include the information of the annotations or tags or other useful data in the document created for search
https://github.com/backstage/backstage/blob/c46a99b0457ece1b3b4342d3cd9e50b25e3b6083/plugins/catalog-backend/src/search/DefaultCatalogCollator.ts#L123-L137

Wouldn't it be useful to include that information in searches also?

**Comment by garyniemen** [comment]
@emmaindal any thoughts?

**Comment by jcarres-mdsol** [comment]
I wanted to answer quickly what services were or not using travisCI and as we have that annotation, I instinctively searched for "travis-ci" as that's the annotation there and got nothing and thought was a waste having that information there to not unlock it.

In general I think people will want to answer all kind of weird questions. I have not experimented with the graphql plugins but I guess if not in search then the idea is that these kind of questions should be answered via queries to graphql?

Also, for your consideration, does is make sense to make the fields that search will consider configurable? Who knows what people put in `metadata` which maybe they want to later search for.

**Comment by jwnmulder** [comment]
That would be useful for us as well. Would love to be able to search within a selection of label values

**Comment by JordiPolo** [comment]
We have set of properties within metadata, I notice the value in one of those outdated in one service and wanted to know if any other services had that outdated value. So again, having that in search would have been very convenient.

**Comment by garyniemen** [comment]
Re-opening for now.

**Comment by iamEAP** [comment]
Hey everyone following along on this issue!  I'm consolidating this feature idea (as well as others) into a single issue.

I encourage you to continue the discussion (and perhaps, implementation? 😉) here: https://github.com/backstage/backstage/issues/14961
