### ISSUE TITLE
Helm: Missing default value for postgresql.service.port

### ISSUE THREAD

**Issue by alexweide** [backstage/backstage#11414]
I am trying to deploy the Helm Chart with the default configuration exactly like described in https://backstage.io/docs/deployment/helm. But it fails, because Helm is unable to template the [`postgres-test.yaml`](https://github.com/backstage/backstage/blob/master/contrib/chart/backstage/templates/tests/test-postgresql.yaml), because `postgresql.service.port` is not set.

## Expected Behavior

I expect the Helm chart to be deployable like described in the docs.

If I add the following lines to our `values.yaml` the deployment works like expected:
```
postgresql:
  service:
    port: 5432
```

## Actual Behavior

Helm is unable to template the postgres-test.yaml, because `postgresql.service.port` is not set.

## Steps to Reproduce

Deploy the Helm Chart like described here: https://backstage.io/docs/deployment/helm

## Your Environment

- Browser Information: -

- Output of `yarn backstage-cli info`: -

**Comment by Rugvip** [comment]
Seems sensible, is it something you would like to contribute?

**Comment by alexweide** [comment]
Hello @Rugvip ,

suddenly the issue was gone. I am closing the issue.

**Comment by cmoulliard** [comment]
Issue is not fixed at all

```
git clone https://github.com/backstage/backstage.git
cd contrib/chart/backstage
helm dependency update

cat <<EOF > cfg.yml
appConfig:
  app:
    baseUrl: https://backstage.192.168.1.90.nip.io
    title: Backstage
  backend:
    baseUrl: https://backstage.192.168.1.90.nip.io
    cors:
      origin: https://backstage.192.168.1.90.nip.io
  lighthouse:
    baseUrl: https://backstage.192.168.1.90.nip.io/lighthouse-api
  techdocs:
    storageUrl: https://backstage.192.168.1.90.nip.io/api/techdocs/static/docs
    requestUrl: https://backstage.192.168.1.90.nip.io/api/techdocs
EOF

helm install -f cfg.yml backstage .
Error: INSTALLATION FAILED: template: backstage/templates/tests/test-postgresql.yaml:17:27: executing "backstage/templates/tests/test-postgresql.yaml" at <.Values.postgresql.service.port>: nil pointer evaluating interface {}.port
```

**Comment by JaapHaitsma** [comment]
I run into the same issue as @alexweide adding the following to `values.yaml` indeed fixes the issue
```
postgresql:
  service:
    port: 5432
```

**Comment by TaboolaGruber** [comment]
Issue still exists and should be reopened, adding the lines @JaapHaitsma notes solve the issue

**Comment by Rugvip** [comment]
Sorry, will close this again as the helm chart documentation has been removed and we do not plan support the particular chart in contrib going forward. There's a newer chart at https://github.com/vinzscam/backstage-chart/ which I recommend that you use instead.
