### ISSUE TITLE
Groups hierarchy arrows go behind other boxes

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#11428]
First off, I totally understand if someone wants to change this from being a bug to an enhancement.

## Expected Behavior

Arrows should attach to the right side of their parent boxes.

## Actual Behavior

Arrows go behind boxes to the top and bottom of their parent boxes.

## Steps to Reproduce

Here's a screenshot...

At a glance, it looks like "Platform" is pointing at the bottom "roadie-backstage..." box in the list.

![Screenshot 2022-05-10 at 17 17 19](https://user-images.githubusercontent.com/562403/167675820-413f80f6-0204-43c8-970f-4bba51114320.png)

It doesn't actually look too bad in this screenshot, but I've seen instances where the arrows are going behind 6+ boxes as they travel up to the correct parent box, which makes the diagram difficult to follow. Unfortunately I can't screenshot these layouts as they contain customer data.

There is some demo data here which might be useful when reproducing this issue: https://github.com/RoadieHQ/demo-data/blob/main/examples/roadie.yaml

## Context

Small snags like this make Backstage more difficult to use easily and quickly.

## Your Environment

Google Chrome 101.0.4951.54 (Official Build) (arm64)
Mac

**Comment by Rugvip** [comment]
Yep let's fix this 👍 

Wondering if this is a problem with the underlying component or specific to the groups one, but will leave that for exploration :grin:

I'll also just highlight that this could have a couple of different solutions, for example modified arrow routing, target layout, or rendering.

Is this something you want to work on or should we open it up for contributions?

**Comment by dtuite** [comment]
> Is this something you want to work on or should we open it up for contributions?

Let's open it up to other contributors.

**Comment by andrmaz** [comment]
@dtuite Could I work on this ? I would love to start contributing

**Comment by dtuite** [comment]
Of course @andrmaz. All yours!

**Comment by andrmaz** [comment]
Thanks @dtuite! Any suggestions where I should start ?

**Comment by andrmaz** [comment]
@Rugvip I’m intrigued to know if I can consider changing the curve factory and consequentially remove the arrow marker as a possible practical solution, even though the design would be noticeably different.

![backstage_curve-step-before](https://user-images.githubusercontent.com/60042277/179397770-0d57109c-667d-489e-8625-c771fc8ae322.png)

**Comment by andrmaz** [comment]
@dtuite @Rugvip What's your thoughts on my last comment ? I would love to hear from you.

**Comment by dtuite** [comment]
@andrmaz personally I think that looks better. It looks a bit more like a system diagram to me now. Relationships are clearer.

**Comment by andrmaz** [comment]
@dtuite Thanks for your quick reply! I've just opened a pull request https://github.com/backstage/backstage/pull/13673

**Comment by awanlin** [comment]
@andrmaz any chance you can post an example from the Explore plugin's Group tab, please? Also, it's a little hard to read the test in the lower left where the `domain:playback` is. Would it be possible for this to use a prop to enable this change?

**Comment by dtuite** [comment]
I'm going to close this as fixed by https://github.com/backstage/backstage/pull/13673
