### ISSUE TITLE
Allow tableOptions to be passed to RelatedEntitiesCard based components

### ISSUE THREAD

**Issue by mhaley37** [backstage/backstage#11427]
The entity view page can be made up of different cards, many of which are based on `RelatedEntitiesCard`:
* `HasSubcomponentsCard`
* `HasSystemsCard`
* `DependsOnResources`
*  etc.

It would allow greater customization of the entity page if these individual tables could be augmented, using `material-table` [options](https://material-table.com/#/docs/all-props).  However, even though these are all composed from `material-table` there is no interface for passing options down to it 

## Feature Suggestion

If `RelatedEntitiesCard` could include a new property, `tableOptions` using the `material-table` [options](https://material-table.com/#/docs/all-props), each table could be more fine in `EntityPage.tsx` to build a more unique 

## Possible Implementation

`tableOptions` are already a prop in other components such as `CatalogIndexPage.tsx`, so I see implementing this similar to that:

```
export function DefaultCatalogPage(props: DefaultCatalogPageProps) {
  const {
    columns,
    actions,
    initiallySelectedFilter = 'owned',
    initialKind = 'component',
    tableOptions = {},
```

```
<CatalogTable
  columns={columns}
  actions={actions}
  tableOptions={tableOptions}
/>
```              
 The difference is, the cards we are trying to target -- those composed from `RelatedEntitiesCard` are several levels above the underlying `material-table`.  So `tableOptions` will have to be passed as a prop through all these levels inculding`EntityTable`.

## Context
This was discovered while we were running `a11y` tests on the entity page.  The scan flagged the `HasSubcomponents` table as having a [nested interactive](https://dequeuniversity.com/rules/axe/4.4/nested-interactive?application=axeAPI).  The culprit was that the table has draggable components.  

We ran into this on the Catalog Page and were able to disable draggable columns because `CatalogIndexPage` allows for these `options` to be passed as a property.  However, `HasSubComponents` does not.  

Beyond solving this issue, it would provider greater customization.

**Comment by Rugvip** [comment]
Yep I think that should be alright, doesn't seem to be too controversial to add it to `EntityTable` as well. Perhaps the issue you highlight is something we should fix as well though? referring to the draggable components

Is this something you want to work on or should we open it up for contributions?

**Comment by mhaley37** [comment]
Sure, I can take this one.  I don't think the `a11y` violation can be addressed directly in backstage, likely needs to be changed in `@material-table/core`.  I will look in further to confirm that.
