### ISSUE TITLE
Deploying with NX

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#11430]
Nx builds a project graph by analyzing your workspace, which it then uses to only rebuild what is necessary and to never run the same computation twice. Nx also helps establish structured code sharing and ownership management to keep the workspace maintainable.

Similar to the [Docker](https://backstage.io/docs/deployment/docker), [Kubernetes](https://backstage.io/docs/deployment/k8s) etc, there should be an ability to deploying with Nx.

## Possible Implementation

https://github.com/nrwl/nx

## Context

It is useful to be able to deploy with NX.

**Comment by Rugvip** [comment]
Could you provide a bit more infromation about what this would mean in practice? As in what is it that you want to incrementally build, when, and how do other tasks like running tests work?

Our development model is to work straight with source code without intermediate builds, so for local developmemt there is no need to build individual packages at all.

**Comment by zoidbergwill** [comment]
With large backstage repos, the build is quite slow, and speeding it up might be as simple as the following

> To make Lerna faster, all you need to do is to
> - install the `nx` package
> - set the `useNx` property to true in `lerna.json`.

Based on [Lerna 5.1 — New website, new guides, new Lerna example repo, distributed caching support and speed!](https://blog.nrwl.io/lerna-5-1-new-website-new-guides-new-lerna-example-repo-distributed-caching-support-and-speed-64d66410bec7)

I'll try on our own internal repo to see if it helps.
