### ISSUE TITLE
[RFC] Enhancing experience for Multi-Catalog Import capability with the `kind: Location` Entities

### ISSUE THREAD

**Issue by NishkarshRaj** [backstage/backstage#11445]
**Status:** Open for comments

## Need

Our Engineers in different teams/channels define a single source of truth - a `kind: Location` file and reference every other catalog via this file. Thus, they have to register only a single catalog manually via UI or with the API.

The existing import process seems to have a few issues that need to be overcome for a smooth onboarding and good customer experience.

### Case 1: Referencing an already imported catalog

The already existing catalog is re-imported and has multiple references. If one of the references is deleted, the catalog will be unregistered.

It might be a scenario that the alternate locations file might get it back on the next poll, but we should still not allow for a gap of lost data. Should we?

![rfc1](https://user-images.githubusercontent.com/35298207/167783025-b38c05f3-3adb-40a2-9e8c-fe1e6f1c55d1.png)

![rfc2](https://user-images.githubusercontent.com/35298207/167783056-825a53c2-b27d-44d8-a01e-7c6f84960400.png)

### Case 2: Incorrect descriptor definition in one or more files

![rfc3](https://user-images.githubusercontent.com/35298207/167783083-a26632f0-777a-4ed5-84bc-efac946b9684.png)

If any of the referenced descriptors have an error, it is shown on the screen.

One huge flaw is that the filename is not shown for the incorrectly defined descriptor. This will make it a cumbersome process to find and fix the file - especially when the number of references is large.

Another issue in this approach is that it only catches incorrect definition in a single file and exit the analysis/dry run. Keeping the tradeoff between experience and performance in mind, I think the analysis phase should find errors in each file (if exists) and showcase a cumulated error message after the analysis.

If not, it will be a bad experience to fix errors in a single file, analyze again - find another issue - fix again - rinse & repeat.

### Broken URL or File path References in the Catalog Import file

![](img/glob-3.png)

If any broken reference is present within the locations file, the error is thrown properly with the file name causing the exit of the analysis phase.

![rfc4](https://user-images.githubusercontent.com/35298207/167789013-e9d5171e-c7f8-4963-a7a8-9d93dc56a969.png)

While this is the correct and expected user journey, the same problem as highlighted in case 2 is still relevant - shows the first issue and exit analysis rather than showcasing all issues at once.

## Proposal

Enhance the Analyze Step (Dry Run API `/api/catalog/locations?dryRun=true`) for `kind: Location` entity:

In the Analyze step:

1. Check for correctness of all references - URL and file paths - if broken references - capture them.
2. Check the semantics and syntax of all correct references. - if errors/incorrect definition - capture them.
3. After the Analysis step, generate comprehensive data:

- List of correctly referenced catalogs with correct syntax
- List of incorrectly referenced catalogs
- List of correctly referenced catalogs with incorrect definitions with proper error handling messages.
- To rectify Case 1 highlighted above, create a check for an already existing catalog with this `namespace/name` and state it exists and cannot be re-imported or like a single catalog import - give the option to refresh?

## Risks

The following risks come to the mind:

- As the number of references to other catalogs grows in size - more resources will be required per API invocation and thus might cause performance issues.

**Comment by Rugvip** [comment]
Thank you for highlighting this, makes sense to fix!

Specifically regarding the first case, what version of the catalog packages are you on? I know we did somewhat recently change the frontend code so that it relies on the catalog's own ability to delete unreferenced entities rather than eagerly deleting things. It could be that this is actually already fixed.

Regarding the second case, is this something you want to work on? I'd be interested in a more concrete implementation proposal for the dry-run changes. Could be in draft PR form for example too to keep it a bit lightweight
