### ISSUE TITLE
[GitHub Actions Plugin] Support mono repos with multiple components with distinct workflows

### ISSUE THREAD

**Issue by iain-b** [backstage/backstage#11465]
We've had users come to us asking for better support for monorepos where different components have their own workflows. As is (AFAICS) the plugin fetchs all workflow runs for the repo. 

## Feature Suggestion

Support specifying which workflows relate to a given component.

## Possible Implementation

Could use [listWorkflowRuns](https://octokit.github.io/rest.js/v18#actions-list-workflow-runs) with a workflow ID to list only runs for a given workflow. Downside is this would lead to multiple calls if several workflows are required. Alternatively, we could filter after the fact. This requires the user to know the numeric ID (where the API accepts filename also but perhaps we can do this translation at the cost of a request).

Perhaps this would require a new annotation (e.g. `github.com/workflow-ids: 'one.yaml,two.yaml'`)? This would need to be a list to be useful but that could be difficult to manage (especially as file path is the easiest way to specify workflow ID). Alternatively, these could be passed as props (like branch for example).

## Context

I can work on this if there's an acceptable way to implement this.

I came across this look for an existing issue but I believe it's different. 
[[GitHub Actions Plugin]](https://github.com/backstage/backstage/issues/4689)

**Comment by Rugvip** [comment]
Sounds like a good area for improvement, and I think we could go either in a more generic direction with a solution that might apply to all CI/CD plugins, or something that only works for GitHub actions, or a bit of both.

One thing to consider here could be to use the workflow files to derive the information, basically by matching the path patterns against the source locations of the entities. May be best to add a backend plugin if we want to do that though.

Tbh I somewhat feel that a refactor of the API might make sense here as well. Right now the React code is unpacking the information in the entity and passing it to the API, which makes it impossible to inject different behavior at that point. If the API was closer to `listWorkflowRuns({entity})` then we'd be able to provide a lot more flexibility in how the mapping to workflow runs is handled

**Comment by iain-b** [comment]
Hi! 

Sorry about the delay replying here I went on PTO for a couple of weeks shortly after creating this.

Using the workflow files does seem like it'd be robust though you'd really wish that data was available through the API (though it doesn't look like it is).

> I think we could go either in a more generic direction with a solution that might apply to all CI/CD plugins, or something that only works for GitHub actions, or a bit of both.

I'm curious about this are we talking about simply a common approach or a shared interface for the API that CI plugins could implement? Or do I misunderstand?

**Comment by Rugvip** [comment]
@iain-b Yep could be a common approach across CI plugins. That's ofc very tricky though which is why it could make sense to at least start with something GH specific

**Comment by MnLujan** [comment]
Hi guys @iain-b @Rugvip! I'm interested in this. I have a `monorepo` with multiple components inside, and it would be very useful to be able to filter the specific workflow of the component. Is this currently possible?
