### ISSUE TITLE
Software Templates: Rollback previous steps in case of an error

### ISSUE THREAD

**Issue by omerfarukdogan** [backstage/backstage#11460]
Steps should have a way to rollback their changes if a subsequent step fails during the task.

## Feature Suggestion

Currently, steps are not informed about errors in subsequent steps. Therefore, there is no way to rollback the changes applied in a step if it is completed successfully but a subsequent step fails.

## Possible Implementation

Introduce a new field (such as `errorHandler`) in `TemplateAction`. If a step fails, `errorHandler` functions of previous actions are called by the scaffolder in reverse order.

## Context

We have a template which has multiple steps. Each step creates entities in external systems. When a step fails, these systems become inconsistent. We need a way to inform the completed steps that the task is failed so they can rollback their changes.

**Comment by benjdlambert** [comment]
Hmm not sure that we're looking to introduce this sort of complexity as yet to the scaffolder. What are the things that you are seeing that is failing? Are they meant to fail? Could you not retry them in the action rather than breaking the flow of the scaffolder and exiting when maybe retrying the thing in the action if it might fail could work around this?

**Comment by omerfarukdogan** [comment]
Hello @benjdlambert,

In our case, we have to notify an external system whenever a repository is created. The external system could be unavailable, or have an error which requires manual intervention. Retrying until it is successful may not be a good idea in such situations.

Is Software Templates planned to be limited to repository creation only? Because there could be more steps which are required for a new application to be available, such as provisioning a VM, creating a namespace on Kubernetes, or creating a database.

**Comment by jhaals** [comment]
I agree with Ben that rollbacks introduce a fair bit of complexity and that it require careful consideration before implementation, probably something that require an RFC with more details on how such a system could work.

Software templates can definitely be used to create other things then just repositories as you and others already do.
There's definitely pitfalls with rollbacks which can lead to some big security issues if the scaffolder rollback mean deletion of the resource, some form of takeover. Poorly written rollback logic could lead to deletion of already existing resources prior to scaffolding.
