### ISSUE TITLE
[TechDocs] How to use typedoc instead of markdown

### ISSUE THREAD

**Issue by Anonyfox** [backstage/backstage#11471]
## Feature Suggestion

For library-type components, I'd like to use the generated output from [TypeDoc](https://typedoc.org/) in the `/docs` tab and automatically index the contents in backstage search. Currently, the techdocs-cli seems to expect a strict structure before uploading (I am using Github Actions to generate the docs and have an AWS S3 bucket as destination)

## Context

While extracting shared functionality into reusable libraries, the discoverability of what functionalities exist and in which library they're implemented tends to suffer over time. In the specific case of typescript, the typedocs contain highly valuable detailed informations, even including [mermaid charts](https://www.npmjs.com/package/typedoc-plugin-mermaid).

Moving this very implementation-specific information over to markdown files in the `/docs` folder introduces the risk that these files get forgotten when changing the code, also it introduces hopping between files (code + docs) that is unneccessary AND requires writing information manually that typedoc already infers (like, which functions exist and their signatures).

**Comment by Anonyfox** [comment]
For anyone reading this: I got something working with outputting markdown from typedoc and using this as-is, like: 

```
typedoc --hideGenerator --includeVersion --excludeExternals --excludePrivate --plugin typedoc-plugin-markdown --out docs src
```

this works roughly out of the box, but the folder/file-hierarchy is autogenerated, so it seems that I can't produce a nice navigation sidebar with deep links (like, to every `class` that is exported).

**Comment by garyniemen** [comment]
@Anonyfox thanks for sharing how you got this working.

**Comment by emmaindal** [comment]
Hello @Anonyfox thanks for opening this issue. Can I just ask some clarifying questions about the request:

1. Would you like to see support for [TypeDoc](https://typedoc.org/) when using techdocs-cli? 
or
2. Do you want us to document the transformation of typedoc to markdown? 

Thanks!

**Comment by lpcruz** [comment]
+1 On this issue! Would be really slick to have native support for typedoc.

**Comment by anilazaidi** [comment]
Ditto to what @lpcruz said!!

**Comment by JBusch** [comment]
Woulb be nice to just have Markdown support for docs.
