### ISSUE TITLE
Importing component discovered via gh-discovery results in new location with type url created.

### ISSUE THREAD

**Issue by Irma12** [backstage/backstage#11501]
When github-discovery is enabled, registering an entity (which is already discovered) results in proper import after analyze is complete and register location of type url regardless of the fact entity is already discovered during discovery process.

## Expected Behavior

User should be notified component already exists.

## Actual Behavior

Component is imported with location type `url` regardless of the fact same component was discovered and imported via github discovery

## Steps to Reproduce

1. Enable github-discovery
2. Manually import/register component (which already is discovered via github-discovery) using` /catalog-import `

**Comment by Rugvip** [comment]
Hmm, makes sense to do something about this, but not entirely certain what. Do you think it would make sense to highlight that the entity already exists in the catalog and prompt the user whether they want to continue with the registration? I could see a way to implement that being to include the catalog presence in the dry-run result for each entity.

**Comment by Irma12** [comment]
I think it would be quite helpful tbh. Am I right in assuming we would also want to stop it being registered as 'url' location type ( through checkGitHubForExistingCatalogInfo)?

**Comment by jhaals** [comment]
Stop registering the location as url is perhaps not something we should enforce.  There's situations where you start out with discovery enabled but want to transition over to manually registered entities for better control so just denying is probably not a good experience for everyone. I like the idea of promoting the user for a manual registration based on the dry-run result.
