### ISSUE TITLE
code completion for scaffolder templates in ide

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#11507]
## Feature Suggestion
I believe I could be more productive about creating or updating backstage templates if there was an ide plugin that allowed code completion.

## Possible Implementation

I have not explored how this could be done, I am assuming most devs are using webstorm or visual studio, however if would be nice if this could be done in a more generic way to apply to any ide.

## Context
If I can get code completion for templates I can easily put together scaffolder templates more quickly, than referring to docs and copy and pasting.

**Comment by benjdlambert** [comment]
Duplicate of #12250

**Comment by benjdlambert** [comment]
Closing this for now as I think that it's captured in the other ticket.
