### ISSUE TITLE
Extensible IdentityClient

### ISSUE THREAD

**Issue by SpyQuel** [backstage/backstage#11503]
Could it be possible to extend the default IdentityClient?
In our use case, I would like to use the TokenIssuer to sign a JWT token containing other claims other than the ones required by Backstage, and I would like to specify also different signing algorithms.
I did it with version 0.5 but with version 1.1.0 I cannot anymore since IdentityClient is a class with a private constructor and there is no interface that I could implement.

## Feature Suggestion

The IdentityClient could extend an interface that I could implement with a custom one (same thing we are doing for the TokenIssuer).
Another solution could be to take some of the configurations from outside (e.g. the signing algorithm).

## Possible Implementation

Maybe also a more structured "extension plan" of the tokens management could be a good idea, the suggestions above are just to enable customizations.

## Context

Since we liked a lot the way Backstage was creating JWT tokens, we wanted to use them to send these tokens also to third-party systems by just adding other custom claims.
This is a very powerful feature if TokenIssuer and IdentityClient are extensible, but it seems that instead of making them more extensible the direction is to close them more (no interface, no public constructor, etc).
Maybe I am missing some other cleaner way to customize this behavior?

**Comment by Rugvip** [comment]
Yep this is something that we want to do but haven't focused our efforts on yet. Would you like to make a concrete implementation proposal to drive this forward?

**Comment by manuelscurti** [comment]
Hi! :) I would like to help making a concrete implementation. But before that, was there any reason to remove the IdentityApi interface that I'm missing?

**Comment by Rugvip** [comment]
@manuelscurti The `IdentityApi` is [alive an well](https://github.com/backstage/backstage/blob/013e54d0cbb1e31cdee91ae57439a381b1938a06/packages/core-plugin-api/src/apis/definitions/IdentityApi.ts#L24), for example with this implementation over [here](https://github.com/backstage/backstage/blob/013e54d0cbb1e31cdee91ae57439a381b1938a06/packages/core-components/src/layout/SignInPage/UserIdentity.ts#L41)
