### ISSUE TITLE
Now showing the Owned entities in catalog

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#11518]
## Expected Behavior
Given the user successfully sign-in and
When the same user is a member of a group, which owns some of the entities in the catalog
Then the owned entities should not be zero and shows the entities owned by the user.

## Actual Behavior
Showing the zero owned entities

## Steps to Reproduce

1. User exists the in the catalog with the `metadata.name` matching the local-part of the email, say `john.doe`
2. User belongs to the group, say `heroes`
3. There are entities with `heroes` as owner in the catalog
4. When `john.doe` logins in using one of the built-in providers (microsoft in our case), the user has ZERO owned entities.

## Context

With the changes in the `plugin-auth-backend:v0.13.0` the resolver needs to be configured in the `backend/src/plugins/auth.ts`.
We have configured the microsoft resolver as below.

```
      microsoft: providers.microsoft.create({
        signIn: {
          resolver:
            providers.microsoft.resolvers.emailLocalPartMatchingUserEntityName(),
        },
      }),
```

Looking at the code the built-in `commonByEmailLocalPartResolver` in [resolvers](https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/providers/resolvers.ts)

It does not include `ownedentitiesRef` as mentioned in the documentaiton [here](https://backstage.io/docs/auth/identity-resolver#custom-ownership-resolution)

**Shouldn't the `getDefaultOwnershipRefs` call be included in the built-in resolvers ?**

**Comment by pavanjn** [comment]
I'm facing the issue of a empty owned entities for a resolver as a "Sign-In without Users in the Catalog" (https://backstage.io/docs/auth/identity-resolver#sign-in-without-users-in-the-catalog)

**Comment by jhaals** [comment]
Would you be able to provide an entity that should be visible and also the resolver for us to try to reproduce this issue?

**Comment by pavanjn** [comment]
@jhaals I see an issue been created for this - https://github.com/backstage/backstage/issues/12107.

The issue is with oidc provider when used with the resolver from here - https://backstage.io/docs/auth/identity-resolver#sign-in-without-users-in-the-catalog.

**Comment by awanlin** [comment]
@pavanjn I posted a solution for this in #12107 : https://github.com/backstage/backstage/issues/12107#issuecomment-1158845189

The issue isn't with the OIDC provider but that the return needs to use `ctx.signInWithCatalogUser` and you need to have Users for Backstage to map with.

**Comment by awanlin** [comment]
@pavanjn, sorry, just saw your edit. To handle both cases you'll need to implement some custom logic, the elements you need to do that are all available to you. Let me see if I can find more details

**Comment by pavanjn** [comment]
@awanlin  Sorry for the multiple edits, i would try and update here.

**Comment by awanlin** [comment]
@pavanjn, no worries. So what you need to do to make this work is something like this:

Use `ctx.findCatalogUser` to find the user, if they exists then return `ctx.signInWithCatalogUser` else return `ctx.issueToken`.

That should get you what you'd like to see happen
