### ISSUE TITLE
[RFC] A "headless" Backstage

### ISSUE THREAD

**Issue by solimant** [backstage/backstage#11516]
**Status:** Open for comments

## Need
At Adobe, we use [React Spectrum](https://react-spectrum.adobe.com/react-spectrum/index.html) for our UI/UX, which is a React implementation of [Spectrum](https://spectrum.adobe.com/), Adobe's design system. We would like to take on Backstage for what it has to offer as an extensible and open platform for developer portals. However, one of the most significant roadblocks is the fact that Backstage UI is Material UI, and that would prevent us from offering a consistent user experience that complies with Adobe's design system.

Are there any plans for a "headless" Backstage? Would this idea be even entertained or open for discussion?

## Proposal

Decouple the Backstage UI from its core functionality, and offer a way for Backstage adopters to bring their own UI, which could perhaps be something similar to Gatsby's [component shadowing](https://www.gatsbyjs.com/docs/theme-api/#shadowing). Material UI can and should still be the default UI component library that's offered by Backstage OOTB for backward support for existing Backstage adopters.

## Alternatives
Without resorting to forking the Backstage repository and performing a surgical operation to replace all Material UI components with React Spectrum ones, I do not think there are other alternatives. Even deep stying and theming, if at all possible, will not offer Spectrum's accessibility guidelines, which comes with React Spectrum's implementation.

## Risks
- Bumpy backward compatibility for existing adopters, but will really depend on approach

**Comment by Rugvip** [comment]
This is actually more or less already the case in the sense that `@backstage/core-app-api` and `@backstage/core-plugin-api` are completely decoupled from MUI. It's not until you start relying on packages like `@backstage/app-defaults`, `@backstage/theme`, and `@backstage/core-components` that you bring in the MUI dependency. That ofc leaves a lot to be implemented yourself, and you're not going to be able to rely on most of the open source plugins, but you will sill get many of the other benefits that Backstage brings.

When it comes to being able to drill down and replace views and components both within plugins and app-wide, that's a bit of a longer journey and it's unlikely that it's something that will ever the available across the entire plugin ecosystem. A massive hurdle here ends up being API stability, with a lot of friction being added to developing plugins. I could see a future where some of the core plugins like the catalog and scaffolder are flexible enough to support this though.
