### ISSUE TITLE
Missing Index - Improve Error Handling In Search

### ISSUE THREAD

**Issue by danielsamet** [backstage/backstage#11511]
## Expected Behavior

I would like to suggest that when searching inside of an index that does not exist, it should error out with an HTTP 400 response. (I can confirm that this occurs within ElasticSearch, I do not know about other search engines).

## Actual Behavior

Currently, searching inside of an index that does not exist returns a 500 error.

## Steps to Reproduce

Build a search request to look inside of an index that does not currently exist. (You should be able to include a `type` to your `SearchQuery` with the name of the index you are trying to query from).

## Context

I am working on a new indexer related to some internal tooling. I am trying to cover the scenario that the indexer fails and no index has the correct alias associated with it. I would like Backstage to gracefully fail if/when this occurs (as opposed to displaying a 500 error, indicating that it's an unknown error).

## Your Environment

Not really environment specific. Kind of related to all environments.

- Browser Information: Google Chrome 100.

- Output of `yarn backstage-cli info`:

Many of our dependencies are outdated (we are slowly updating them). However, I can confirm that the code this relates to remains unchanged and this request is still relevant.

```text
OS:   Darwin 21.4.0 - darwin/x64
node: v14.18.1
yarn: 1.22.17
cli:  0.10.0 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.2
  @backstage/backend-common                                0.9.13, 0.10.3, 0.10.7, 0.8.10
  @backstage/catalog-client                                0.5.2, 0.6.0, 0.3.19, 0.5.4
  @backstage/catalog-model                                 0.9.7, 0.9.10, 0.9.9
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.10.0
  @backstage/config-loader                                 0.6.10, 0.8.1, 0.9.2, 0.9.3
  @backstage/config                                        0.1.11, 0.1.5, 0.1.12, 0.1.13
  @backstage/core-app-api                                  0.1.24, 0.2.0
  @backstage/core-components                               0.7.6, 0.8.0
  @backstage/core-plugin-api                               0.2.2, 0.3.0
  @backstage/errors                                        0.1.1, 0.1.5, 0.2.0
  @backstage/integration                                   0.6.10, 0.7.2, 0.5.9, 0.7.1
  @backstage/plugin-auth-backend                           0.4.10, 0.6.2
  @backstage/plugin-auth-node                              0.1.0
  @backstage/plugin-catalog-backend                        0.19.0, 0.20.0, 0.21.3
  @backstage/plugin-catalog-common                         0.1.0, 0.1.2
  @backstage/plugin-permission-common                      0.3.1, 0.4.0
  @backstage/plugin-permission-node                        0.3.0, 0.4.3
  @backstage/plugin-proxy-backend                          0.2.14
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.11, 0.1.8
  @backstage/plugin-scaffolder-backend                     0.15.24, 0.15.20
  @backstage/plugin-scaffolder-common                      0.1.2, 0.1.3
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.2.7, 0.2.8
  @backstage/plugin-techdocs-backend                       0.8.7
  @backstage/search-common                                 0.2.1, 0.2.2
  @backstage/techdocs-common                               0.6.8
  @backstage/test-utils                                    0.1.24
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1
```

## Additional Information

I have tracked down the issue and can see that it is related to the code in the search-backend plugin. In particular, it's in the [router](https://github.com/backstage/backstage/blob/cd6854046ebac7e31dfb68d39d306a309445d416/plugins/search-backend/src/service/router.ts#L96-L104). My suggestion is that instead of catching and immediately throwing the error here, it should instead log the issue and return an HTTP 400 error.

I am curious what your thoughts are? I am open to any other solution too obviously. Or perhaps do you disagree with the idea of handling the error differently? Please let me know what you think.

**Comment by emmaindal** [comment]
Hello @danielsamet I'm picking up this issue. Just to clarify one thing

> My suggestion is that instead of catching and immediately throwing the error here, it should instead log the issue and return an HTTP 400 error.

As a user, do you still expect to see an error message in the UI when there was an unsuccessful search across a missing index?

**Comment by emmaindal** [comment]
@danielsamet I've opened a draft PR for this. Please have a look and see if that meets your expectations!
