### ISSUE TITLE
Task Manager Failing and Not Restarting

### ISSUE THREAD

**Issue by blakeromano** [backstage/backstage#11526]
## Expected Behavior

When a task fails allow it to fail once and then retry on future times it is supposed to run

## Actual Behavior

Task failed and then stops running the task until the server was terminated and restarted

## Context

We have a task that runs every 10 minutes that will call an endpoint grab a list of entities and process them. This failed and then stopped running the task. Potentially making it an option to stop if failed or to retry on future attempts if failing would be a nice addition. (Potentially adding some method of throwing alerts if it fails may be nice for monitoring).

```
Task worker failed unexpectedly, Error: select "settings_json" as "settingsJson", CASE

WHEN next_run_start_at <= CURRENT_TIMESTAMP AND current_run_ticket IS NULL THEN TRUE
ELSE FALSE

END as "ready" from "backstage_backend_tasks__tasks" where "id" = $1 - Connection terminated unexpectedly [36mtype[39m=taskManager
```

## Your Environment

We run on one kubernetes pod backed by a serverless AWS RDS Postgres cluster.

**Comment by freben** [comment]
Hm that's not intended for sure. Maybe some part of the code isn't handling that database error gracefully, breaking the refresh loop instead of just trying again later. If so, needs a fix!

**Comment by blakeromano** [comment]
I would believe that is the case. I haven't dug into the backstage code to see how to allow it to fail gracefully and then just continue the task on the cycle as needed but I feel like that would be something that should definitely be worked on (I think even if it was opt out that would be better so you aren't calling a task that is consistently failing)
