### ISSUE TITLE
[TechDocs] Unable to embed videos that are located in the repository

### ISSUE THREAD

**Issue by omerfarukdogan** [backstage/backstage#11537]
## Expected Behavior

When I add a video to a document repository and add an iframe pointing to that video in the documentation, I expect the iframe to be rendered with the video I provided.

## Actual Behavior

The iframe element is not present in the documentation.

## Steps to Reproduce

1. Add a video into the document repository
2. Add an iframe into the documentation pointing to that video:
    `<iframe src="./sample-video.mp4"></iframe>`
3. Regenerate the documentation

## Context

I am trying to add a video, which is not uploaded to any external source, into a documentation. Currently, the sanitizer can't determine if the host of the source is in the `allowedIframeHosts` list, because when it [tries to parse](https://github.com/backstage/backstage/blob/aa8f764a3e9bfdcb9034e23094d913e3a678f06a/plugins/techdocs/src/reader/transformers/sanitizeDOM.ts#L46) the host of the src using `new URL(src)`, an Error is thrown. I believe relative links should be detected and allowed (preferably without any additional configuration).

**Comment by omerfarukdogan** [comment]
The issue is still relevant.

**Comment by marct83** [comment]
Is there a workaround for this?

**Comment by omerfarukdogan** [comment]
@marct83 Not that I know of. I have reopened this as a feature request #14722.

**Comment by andrewthauer** [comment]
Not sure if this helps, but did you see #7393?
