### ISSUE TITLE
Stackoverflow plugin encoding the API key

### ISSUE THREAD

**Issue by mmulligan03** [backstage/backstage#11531]
## Expected Behavior

To configure the API key for a private instance of Stackoverflow requires an API passed in the request parameters. It should be passed to StackOverflow unencoded.  

## Actual Behavior

The implementation of `qs.stringify` have encoding set to true by default. Which changes special characters present in the API. 

## Steps to Reproduce

1. Configure the StackOverflowQuestionsCollatorFactory
```
indexBuilder.addCollator({
    schedule,
    factory: StackOverflowQuestionsCollatorFactory.fromConfig(env.config, {
      logger: env.logger,
      requestParams: {
        key: env.config.getOptionalString('stackoverflow.apiKey')||"",
      },
    }),
  });
```

2. `stackoverflow.apiKey` is something like `Ab3dF*Q((` which  gets encoded as `Ab3dF%2AQ%28%28`

## Context

Just trying to connect to a private StackOverflow instance with an API key.
`qs.stringify` has the option to disable encoding. It can either be set to false or add a param to set it to false. 

https://github.com/backstage/backstage/blob/master/plugins/stack-overflow-backend/src/search/StackOverflowQuestionsCollatorFactory.ts#L96

```
const params = qs.stringify(this.requestParams, {
      arrayFormat: 'comma',
      addQueryPrefix: true,
      encode: false
    });
```
or
```
const params = qs.stringify(this.requestParams, {
      arrayFormat: 'comma',
      addQueryPrefix: true,
      encode: this.encodeParams || true
    });
```

**Comment by jhaals** [comment]
@emmaindal could you perhaps take a look at this? 🙏

**Comment by emmaindal** [comment]
@mmulligan03 Thanks for opening this issue, I've one question - do you know if its possible to set encoding to false to a specific param? so that we can continue to encode other things than the key. Otherwise I'm thinking it might make sense to just add the key param with its value of `env.config.getOptionalString('stackoverflow.apiKey')` directly to the request url if defined?

**Comment by mmulligan03** [comment]
From my understanding it's an all or nothing change to disable/enable encoding. Passing in the API key separately sounds better than the ability to disable the encoding.

**Comment by emmaindal** [comment]
> Passing in the API key separately sounds better than the ability to disable the encoding.

So then I would say this is the way to go. 

I'll add a help-wanted label on this issue and feel free to pick it up if you want @mmulligan03, otherwise I'll see if I find time next week to fix it.

**Comment by mmulligan03** [comment]
https://github.com/backstage/backstage/pull/11619

**Comment by mmulligan03** [comment]
I have the changes to address the concerns done, but I am away for 2 weeks and didn't bring my personal laptop... I'll get them in once I get back.
