### ISSUE TITLE
[Catalog]: Bring back batchAddOrUpdate functionality 

### ISSUE THREAD

**Issue by victormorfin97** [backstage/backstage#11547]
## Feature Suggestion

I want to know the feasibility to bring back the batchAddOrUpdate functionality that was already on entityCatalog but it got deprecated.
## Context

Currently at Expedia we have some edge cases where we need to update the entity right away instead of waiting to the next ingestion, we used to cover this functionality with the batchAddOrUpdate function, but a few time ago this method got deprecated and we are not longer able to use it and for a work around we are interacting directly with DB to make the updates, but we think it would be a better approach if we can reimplement something like batchAddOrUpdate functionality to the entitiesCatalog instead of working directly with DB.

**Comment by jhaals** [comment]
Hi Victor.

It really sounds like Entity Providers would be the logical replacement for that functionality used in the old catalog. They support adding and removing entities at your own interval. Is that something you've looked at? There's some information available in our docs [here](https://backstage.io/docs/features/software-catalog/external-integrations#custom-entity-providers)
