### ISSUE TITLE
Techdocs: Docs are not loading when saving a jar file inside the azure repository

### ISSUE THREAD

**Issue by CitsGit** [backstage/backstage#11563]
## Expected Behavior

Techdocs should work properly with respect to the md files in docs folder and mkdocs.yml file. Techdocs do not depend on file contents in another folders.

## Actual Behavior

![image](https://user-images.githubusercontent.com/98138120/168960743-e0010a02-98ab-446a-9f31-070b9934f2e3.png)

## Steps to Reproduce

Azure repo contents

- catalog-info.yaml
- docs folder that contain index.md file
- mkdocs.yml
- another folder that contain a jar file in it 

Expectation: The docs should load properly in backstage

When i delete the jar and reload backstage the doc will display properly

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by cinlysobin** [comment]
@garyniemen , Seems to be the same issue. But still, the fix for it is not done. Right

**Comment by ottosichert** [comment]
The related issue has been fixed now with https://github.com/backstage/backstage/pull/12090!

@CitsGit could you verify it also fixes this issue with JAR files?

**Comment by cinlysobin** [comment]
@ottosichert ,
Still i am getting the same issue.
Any change I have to do to get the corrected version?

**Comment by benjdlambert** [comment]
@cinlysobin what version of backstage are you using?

**Comment by cinlysobin** [comment]
"version": "1.3.0"

**Comment by benjdlambert** [comment]
So you probably want to run `yarn backstage-cli versions:bump` to grab the latest release, version `1.5.0` which is where this fixed was released in.

**Comment by cinlysobin** [comment]
Working fine with the latest release.
Thanks for the support

**Comment by freben** [comment]
Alright! Closing as fixed, please reopen if some issue persists.
