### ISSUE TITLE
[TechDocs AddOns] Different behaviour when view doc from doc page and from doc tab in component page

### ISSUE THREAD

**Issue by kim5566** [backstage/backstage#11569]
## Expected Behavior

If i have enabled TechDoc addons, expect same behaviour when viewing doc from doc page and from doc tab in catalog page

## Actual Behavior

1. view doc from doc page
<img width="212" alt="Screen Shot 2022-05-18 at 4 59 54 pm" src="https://user-images.githubusercontent.com/28945404/168977675-f87d4b6f-b47d-4445-ab73-953eed619a6d.png">
show up techdoc addons
<img width="220" alt="Screen Shot 2022-05-18 at 4 59 34 pm" src="https://user-images.githubusercontent.com/28945404/168977196-0491e173-80de-42d4-8d50-5d3f0c96275a.png">

2. view doc from component page
<img width="851" alt="Screen Shot 2022-05-18 at 5 01 09 pm 1" src="https://user-images.githubusercontent.com/28945404/168977569-a6829270-a33f-4502-87ec-b6b99522ee49.png">
adds-on not enabled
<img width="304" alt="Screen Shot 2022-05-18 at 5 01 42 pm" src="https://user-images.githubusercontent.com/28945404/168977574-6f380256-1a38-41a7-a15e-f1dc53da7e04.png">

This is not just for ReportIssue AddOns, if we added custom addons(which rendering Markdown file during runtime), users would get two different doc views with same component.

Would this be expected?

Would love to get an understanding on logic under the hood between these two.

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by camilaibs** [comment]
Hi @kim5566, thanks for reporting.
It seems to have been fixed here, could you check?
https://github.com/backstage/backstage/pull/11609

**Comment by kim5566** [comment]
Hey @camilaibs ! looks fixed to me! thanks! 

is there any dependency in `"@backstage/plugin-techdocs": "^1.1.2-next.0",`? 

could i only upgrade this package? as I still want to go for main release version 😀

**Comment by camilaibs** [comment]
@kim5566 here you can see the updated dependencies 🙂 :
https://github.com/backstage/backstage/blob/master/plugins/techdocs/CHANGELOG.md#112-next0

And thanks again for being active in the community 🎉
