### ISSUE TITLE
Tech Radar - Timeline - In Use?

### ISSUE THREAD

**Issue by no1melman** [backstage/backstage#11577]
We've been setting the timeline property - but it doesn't look like it has any effect - do we have to do the filtering ourselves to show the latest position? Doesn't seem to be worked out based on the `date` property of a timeline entry

https://github.com/backstage/backstage/blob/b73cfc4d4fadfd537ebb0c16ed274fa5a07ae3d1/plugins/tech-radar/src/api.ts#L114

==== Update ====

I've found that it isn't:

https://github.com/backstage/backstage/blob/b73cfc4d4fadfd537ebb0c16ed274fa5a07ae3d1/plugins/tech-radar/src/components/RadarComponent.tsx#L56

One would have thought it would have ordered based on date....

**Comment by no1melman** [comment]
Probably just needs

```javascript
// order by date in the timeline entry to make sure the latest is first
const sortByDate = (a: RadarEntrySnapshot, b: RadarEntrySnapshot) =>  b.date.getTime() - a.date.getTime();

const entries : RadarEntry [] = combinedEntries.map(value => {
  const newEntry : RadarEntry = {
    ...value,
    timeline: value.timeline.sort(sortByDate)
  }
  return newEntry
})
```

happy to create a PR if we want this?

**Comment by no1melman** [comment]
So here

https://github.com/backstage/backstage/blob/b73cfc4d4fadfd537ebb0c16ed274fa5a07ae3d1/plugins/tech-radar/src/components/RadarComponent.tsx#L102-L126

I'm guessing we could do:

```
  const sortByDate = (a: RadarEntrySnapshot, b: RadarEntrySnapshot) =>  b.date.getTime() - a.date.getTime();
  const sortTimeLine : RadarEntrySnapshot[] = (timeline: RadarEntrySnapshot[]) => timeline.sort(sortByDate)
  const mapToEntries = (
    loaderResponse: TechRadarLoaderResponse,
  ): Array<Entry> => {
    return loaderResponse.entries
      .filter(matchFilter(props.searchText))
      .map(entry => {
        const sortedTimeLine = sortTimeLine(entry.timeline)
        return ({
        id: entry.key,
        quadrant: loaderResponse.quadrants.find(q => q.id === entry.quadrant)!,
        title: entry.title,
        ring: loaderResponse.rings.find(
          r => r.id === sortedTimeLine [0].ringId,
        )!,
        timeline: sortedTimeLine.map(e => {
          return {
            date: e.date,
            ring: loaderResponse.rings.find(a => a.id === e.ringId)!,
            description: e.description,
            moved: e.moved,
          };
        }),
        moved: sortedTimeLine[0].moved,
        description: entry.description || sortedTimeLine[0].description,
        url: entry.url,
      })});
  };
```

**Comment by jhaals** [comment]
I believe this was introduced by @o-farooq in https://github.com/backstage/backstage/pull/3191, I hope that he can help out and clarify this as I'm not that familiar with this feature 🙏
