### ISSUE TITLE
[Kubernetes Plugin] Show more details on Requests/Limits

### ISSUE THREAD

**Issue by goenning** [backstage/backstage#11588]
## Feature Suggestion

We're using the kubernetes plugin and everyone is loving it in general, but the details around CPU/Memory usage is a bit confusing.

It currently show this:

![image](https://user-images.githubusercontent.com/94755/169075566-2f7e70a5-a69c-4a94-9cc6-b49f4f9cfe67.png)

And the common question is: ok, 53% of what? To see the Requests/Limit, we have to go into the YAML and search through a often gigantic file.

## Possible Implementation

I'm thinking we could be a bit more explicit and show the actual requests/limit values, like this: 

![image](https://user-images.githubusercontent.com/94755/169075942-43da3bb6-5589-4be8-a397-79d481ad14ed.png)

## Context

I'm happy to PR this in, just want to get some feedback before I spend some time on it.

**Comment by jhaals** [comment]
Sounds like a good idea!
FYI @mclarke47

**Comment by mclarke47** [comment]
I think this is done?
