### ISSUE TITLE
Header Hierarchy Jump on Catalog Import Page

### ISSUE THREAD

**Issue by Matth-Ng** [backstage/backstage#11620]
## Expected Behavior
The header tags should go in order of H1 to H6. In the catalog-import page, the infocard title should be encapsulated in an `<h3>`, and the text headers under it should use `<h4>`

## Actual Behavior
The infocard text uses `h6` and breaks header hierarchy. 

## Steps to Reproduce

go to the 

1. In a vanilla Backstage instance, go to the /catalog-import page
2. You can inspect the "Link to an existing entity file" text or the "Link to a repository" text and you will see that they are `<h6>`

<img width="761" alt="import component old" src="https://user-images.githubusercontent.com/51958813/169398097-c1aa6897-14ad-4ab8-8702-70e955569628.png">

## Context

This is an accessibility issue where headers should go in incremental order.

**Comment by Matth-Ng** [comment]
Created a PR to fix the header hierarchy while keeping the same existing style https://github.com/backstage/backstage/pull/11622

**Comment by benjdlambert** [comment]
Closing as merged
