### ISSUE TITLE
[GitHubOrgEntityProvider] - Make it configurable to only import groups or users. 

### ISSUE THREAD

**Issue by anicke** [backstage/backstage#11632]
This is related to #11406. We have a similar use case.

## Feature Suggestion

We have a different "user provider" and have no use for the github users but we do need the github groups in backstage.

## Possible Implementation

Add two boolean arguments to the provider.

```typescript
export interface GitHubOrgEntityProviderOptions {
  emitGroups?: boolean; // defaults to true
  emitUsers?: boolean;  // defaults to true
}
```
Only emit the entities of the wanted kind.

```typescript
    assignGroupsToUsers(users, groupMemberUsers);
    buildOrgHierarchy(groups);

    const { markCommitComplete } = markReadComplete({ users, groups });

    const entitiesToEmit = [...emitUsers ? users : [], ...emitGroups ? groups : [] ]

    await this.connection.applyMutation({
      type: 'full',
      entities: entitiesToEmit.map(entity => ({
        locationKey: `github-org-provider:${this.options.id}`,
        entity: withLocations(
          `https://${this.options.gitHubConfig.host}`,
          org,
          entity,
        ),
      })),
    });

    markCommitComplete();
```
I can prepare a PR is this is the way forward.

**Comment by Rugvip** [comment]
Sure! Seems like a sensible configuration, please do prep a PR! 👍 

I'm curious how you want to end up linking together the groups and users, will the GitHub teams actually end up referencing users as members? That raises a separate question, which is whether we child/member relations should be optional as well. That is, if you only emit groups, should those groups still include membership information?

**Comment by anicke** [comment]
So... We have done some experiments with this.

Our goal is to have the GitHub group members reference the "external samlIdentity" id (azure) instead of the GitHub id. What works for us is to fetch the mapping between GitHub id -> azure id from githubs graphql api. Use the query in the GitHubOrgEntityProvider to get group memberships per GitHub id. Then using a simple catalog processor we can add all GitHub related data for an azure user entity (like GitHub login id and the GitHub group memberships). The only changes needed to the GitHubOrgEntityProvider is to stop emitting the users and adding a namespace to the groups.
