### ISSUE TITLE
Jenkins job.get: not found type=errorHandler

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#11639]
Jenkins Plugin is no longer working, this did work in past releases but now the plugin is unable to identify the job

Error:
```
type=incomingRequest 
2022-05-21T01:43:00.229Z backstage error jenkins: job.get: FOLDER/MY-ORG-FOLDER/repo not found type=errorHandler notFound=true stack=Error: jenkins: job.get: FOLDER/MY-ORG-FOLDER/repo not found
```

annotations:
    jenkins.io/job-full-name: FOLDER/MY-ORG-FOLDER/repo 

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by Rugvip** [comment]
What version did you upgrade from? Not seeing any immediately suspicious changes in the most recent release.

Any other clues as to what might cause the lookup to fail?

**Comment by regicsolutions** [comment]
Issue was the user I was using didn't have the correct access.
