### ISSUE TITLE
Backstage Upgrade Helper should provide a Git patch 

### ISSUE THREAD

**Issue by sonytricoire** [backstage/backstage#11642]
## Feature Suggestion

Backstage Upgrade Helper could provide a **git patch** file for a one step migration using [git apply](https://git-scm.com/docs/git-apply)

**Comment by Rugvip** [comment]
Yep makes sense to have that easily available! I think with this in place it would be even better if we could avoid having the `@backstage/*` dependency bumps be part of the diff too.

Is this something you would like to contribute?

**Comment by VladMasarik** [comment]
@sonytricoire @Rugvip What do you think of the above linked PR? It is not covering the "second requirement" from Rugvip yet though, and I still have to add docs to the backstage. I will do it once we merge in the previous PR.

**Comment by sonytricoire** [comment]
> Yep makes sense to have that easily available! I think with this in place it would be even better if we could avoid having the `@backstage/*` dependency bumps be part of the diff too.
> 
> Is this something you would like to contribute?

Hi !
Sorry but I won't have time to contribute myself.
Hopefully @VladMasarik can 👍 

@VladMasarik your proposal seems ok to me (from a user perspective, I did not check technically), but I would add a short comment to explain "how to apply".

**Comment by Rugvip** [comment]
@VladMasarik yep I think that should solve it, thank you! 👍 

The second requirement seems decoupled enough and can be treated as a completely separate improvement

**Comment by benjdlambert** [comment]
@VladMasarik I think that @vinzscam got back to you in the other ticket and is awaiting your reply :pray:

**Comment by vinzscam** [comment]
Closed by https://github.com/backstage/upgrade-helper/pull/8
