### ISSUE TITLE
Warnings in api-report.md files

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#11653]
## Expected Behavior

no warning in all api-report.md files

## Actual Behavior

**ae-forgotten-export**
./plugins/github-deployments/api-report.md:3
./plugins/home/api-report.md:3
./plugins/user-settings/api-report.md:6
./plugins/config-schema/api-report.md:1
./plugins/splunk-on-call/api-report.md:10
./plugins/pagerduty/api-report.md:8
./plugins/circleci/api-report.md:1
./plugins/catalog/api-report.md:4
./plugins/kafka-backend/api-report.md:1
./plugins/rollbar/api-report.md:4
./plugins/git-release-manager/api-report.md:14
./plugins/gcalendar/api-report.md:1
./plugins/auth-backend/api-report.md:6
./plugins/explore/api-report.md:1
./plugins/search/api-report.md:2
./plugins/ilert/api-report.md:11
./plugins/search-backend-module-elasticsearch/api-report.md:8
./plugins/kafka/api-report.md:1
./plugins/catalog-import/api-report.md:3
./plugins/lighthouse/api-report.md:2
./plugins/search-backend-module-pg/api-report.md:1
./plugins/jenkins/api-report.md:3
./plugins/kubernetes/api-report.md:15
./plugins/cost-insights/api-report.md:3
./plugins/sentry/api-report.md:1
./plugins/api-docs/api-report.md:6
./plugins/proxy-backend/api-report.md:1
./plugins/github-actions/api-report.md:2
./packages/core-components/api-report.md:43

**ae-missing-release-tag**
./plugins/github-deployments/api-report.md:11
./plugins/home/api-report.md:4
./plugins/jenkins-backend/api-report.md:7
./plugins/gcp-projects/api-report.md:9
./plugins/cicd-statistics/api-report.md:22
./plugins/user-settings/api-report.md:16
./plugins/badges-backend/api-report.md:14
./plugins/code-climate/api-report.md:8
./plugins/azure-devops-backend/api-report.md:3
./plugins/config-schema/api-report.md:4
./plugins/splunk-on-call/api-report.md:7
./plugins/fossa/api-report.md:4
./plugins/firehydrant/api-report.md:2
./plugins/explore-react/api-report.md:3
./plugins/code-coverage/api-report.md:4
./plugins/azure-devops-common/api-report.md:21
./plugins/rollbar-backend/api-report.md:4
./plugins/pagerduty/api-report.md:8
./plugins/apache-airflow/api-report.md:2
./plugins/circleci/api-report.md:9
./plugins/code-coverage-backend/api-report.md:4
./plugins/app-backend/api-report.md:2
./plugins/kafka-backend/api-report.md:1
./plugins/allure/api-report.md:4
./plugins/cloudbuild/api-report.md:28
./plugins/rollbar/api-report.md:9
./plugins/azure-devops/api-report.md:20
./plugins/git-release-manager/api-report.md:65
./plugins/gcalendar/api-report.md:9
./plugins/auth-backend/api-report.md:27
./plugins/explore/api-report.md:9
./plugins/graphql-backend/api-report.md:2
./plugins/search/api-report.md:21
./plugins/ilert/api-report.md:14
./plugins/search-backend-module-elasticsearch/api-report.md:3
./plugins/kafka/api-report.md:5
./plugins/catalog-import/api-report.md:1
./plugins/kubernetes-backend/api-report.md:22
./plugins/shortcuts/api-report.md:6
./plugins/tech-radar/api-report.md:15
./plugins/catalog-graphql/api-report.md:2
./plugins/lighthouse/api-report.md:23
./plugins/newrelic/api-report.md:2
./plugins/search-backend-module-pg/api-report.md:8
./plugins/search-backend/api-report.md:2
./plugins/bazaar/api-report.md:4
./plugins/jenkins/api-report.md:11
./plugins/newrelic-dashboard/api-report.md:4
./plugins/kubernetes/api-report.md:39
./plugins/sonarqube/api-report.md:4
./plugins/cost-insights/api-report.md:77
./plugins/sentry/api-report.md:10
./plugins/api-docs/api-report.md:26
./plugins/gitops-profiles/api-report.md:19
./plugins/proxy-backend/api-report.md:1
./plugins/bazaar-backend/api-report.md:2
./plugins/badges/api-report.md:2
./plugins/bitrise/api-report.md:3
./plugins/kubernetes-common/api-report.md:22
./plugins/xcmetrics/api-report.md:2
./plugins/github-actions/api-report.md:18
./packages/core-components/api-report.md:97

**ae-unresolved-link**
./plugins/search-backend-module-elasticsearch/api-report.md:1
./packages/core-components/api-report.md:9

**Total:      982**

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by pjungermann** [comment]
@Rugvip maybe the list should be inverted to an "allow warnings list" instead :) So new packages will not start with them.

**Comment by benjdlambert** [comment]
@pjungermann your wish came true.
https://github.com/backstage/backstage/blob/master/scripts/api-extractor.ts#L200

**Comment by pjungermann** [comment]
Perfect! That will make it easier to reduce the list step by step. I couldn't get back to help on this one yet, but I didn't forget about it :)
