### ISSUE TITLE
[TechDocs] ERR_SSL_PROTOCOL_ERROR when viewing from Component Docs Tab

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#11650]
## Expected Behavior

TechDocs should display

## Actual Behavior

When trying to view TechDocs from the Components Docs tab we get a Error 404: TypeError and looking at the console we see there is an ERR_SSL_PROTOCOL_ERROR error:

![image](https://user-images.githubusercontent.com/67169551/169877583-cd0ab69e-9527-408d-b7a7-e7df5a8767d2.png)

If I change the URL to use HTTP it works. Not sure why this is, if this is something with my setup or a bug but submitting to be safe

## Steps to Reproduce

1. Ran npx @backstage/create-app to create a instances of Backstage, my version in the backstage.json is 1.2.0
2. Added the following to the app-config.yaml in the catalog.location section (this is a good example as it has a mkdoc.yml in place):
```yaml
- type: url
      target: https://github.com/backstage/backstage/blob/master/catalog-info.yaml 
```

3. Also in the app-config.yaml I changed the techdocs section to look like this:
```yaml
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
```
3. Now in the packages/backend there is a package.json open that and move the "better-sqlite3": "^7.5.0" from the devDependencies section to the dependencies section. This is to handle an error when I was started up the container the first time.
4. Then I added a Dockerfile to the root and used this, pretty much the same as from the multi-stage docker docks on backstage.io:
```
# Stage 1 - Create yarn install skeleton layer
FROM node:16-bullseye-slim AS packages

WORKDIR /app
COPY package.json yarn.lock ./

COPY packages packages

# Comment this out if you don't have any internal plugins
COPY plugins plugins

RUN find packages \! -name "package.json" -mindepth 2 -maxdepth 2 -exec rm -rf {} \+

# Stage 2 - Install dependencies and build packages
FROM node:16-bullseye-slim AS build

WORKDIR /app
COPY --from=packages /app .

# install sqlite3 dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential && \
    yarn config set python /usr/bin/python3

RUN yarn install --frozen-lockfile --network-timeout 600000 && rm -rf "$(yarn cache dir)"

COPY . .

RUN yarn tsc
RUN yarn --cwd packages/backend build

# Stage 3 - Build the actual backend image and install production dependencies
FROM node:16-bullseye-slim

WORKDIR /app

# install sqlite3 and TechDocs dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential python3-pip && \
    pip3 install mkdocs-techdocs-core==1.0.1 && \
    rm -rf /var/lib/apt/lists/* && \
    yarn config set python /usr/bin/python3

# Copy the install dependencies from the build stage and context
COPY --from=build /app/yarn.lock /app/package.json /app/packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn install --frozen-lockfile --production --network-timeout 600000 && rm -rf "$(yarn cache dir)"

# Copy the built packages from the build stage
COPY --from=build /app/packages/backend/dist/bundle.tar.gz .
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

# Copy any other files that we need at runtime
COPY app-config.yaml ./

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```
5. Then make sure your .dockerignore looks like this:
```text
.git
*.local.yaml
node_modules
packages/*/dist
packages/*/node_modules
plugins/*/dist
plugins/*/node_modules
```
6. From the root of your project run this to build the docker container: `docker image build -t backstage .`
7. Now run the container: `docker run -it -p 7007:7007 backstage`
8. In a browser open: http://localhost:7007/
9. Navigate to: http://localhost:7007/catalog/default/component/backstage/docs

Notice after a bit you get a Error 404: Type Error and then in the browser console you see an ERR_SSL_PROTOCOL_ERROR error

## Context

It makes it seem like TechDocs isn't working and can leads to a lot of troubleshooting. This does work when you look at it from the Docs sidebar option, so not in the Component which make is more odd 

## Your Environment

Google Chrome Version 101.0.4951.64 (Official Build) (arm64)

```text
OS:   Darwin 21.5.0 - darwin/x64
node: v14.18.1
yarn: 1.22.18
cli:  0.17.1 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.2
  @backstage/backend-common                        0.13.5
  @backstage/backend-tasks                         0.3.1
  @backstage/catalog-client                        1.0.2
  @backstage/catalog-model                         1.0.2
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.17.1
  @backstage/config-loader                         1.1.1
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.2
  @backstage/core-components                       0.9.4
  @backstage/core-plugin-api                       1.0.2
  @backstage/errors                                1.0.0
  @backstage/integration-react                     1.1.0
  @backstage/integration                           1.2.0
  @backstage/plugin-api-docs                       0.8.5
  @backstage/plugin-app-backend                    0.3.32
  @backstage/plugin-auth-backend                   0.14.0
  @backstage/plugin-auth-node                      0.2.1
  @backstage/plugin-catalog-backend                1.1.2
  @backstage/plugin-catalog-common                 1.0.2
  @backstage/plugin-catalog-graph                  0.2.17
  @backstage/plugin-catalog-import                 0.8.8
  @backstage/plugin-catalog-react                  1.1.0
  @backstage/plugin-catalog                        1.2.0
  @backstage/plugin-github-actions                 0.5.5
  @backstage/plugin-org                            0.5.5
  @backstage/plugin-permission-common              0.6.1
  @backstage/plugin-permission-node                0.6.1
  @backstage/plugin-permission-react               0.4.1
  @backstage/plugin-proxy-backend                  0.2.26
  @backstage/plugin-scaffolder-backend             1.2.0
  @backstage/plugin-scaffolder-common              1.1.0
  @backstage/plugin-scaffolder                     1.2.0
  @backstage/plugin-search-backend-module-pg       0.3.3
  @backstage/plugin-search-backend-node            0.6.1
  @backstage/plugin-search-backend                 0.5.2
  @backstage/plugin-search-common                  0.3.4
  @backstage/plugin-search-react                   0.2.0
  @backstage/plugin-search                         0.8.1
  @backstage/plugin-tech-radar                     0.5.12
  @backstage/plugin-techdocs-backend               1.1.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.0
  @backstage/plugin-techdocs-node                  1.1.1
  @backstage/plugin-techdocs-react                 1.0.0
  @backstage/plugin-techdocs                       1.1.1
  @backstage/plugin-user-settings                  0.4.4
  @backstage/release-manifests                     0.0.3
  @backstage/search-common                         0.3.4
  @backstage/test-utils                            1.1.0
  @backstage/theme                                 0.2.15
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
✨  Done in 3.01s.
```

**Comment by Zoney** [comment]
Get the same. Suspect the `**//index.html` (double slash) is a hint, as without one of the slashes I suspect it would work ?

**Comment by awanlin** [comment]
Sadly removing the double slash did nothing, the URL still would not load. BUT changing the HTTPS to HTTP did resolve the issue which lines up with the fact that the error was ERR_SSL_PROTOCOL_ERROR which indicates a SSL error.

**Comment by emmaindal** [comment]
Hi @awanlin thanks for opening this issue and providing so much details in the steps to reproduce. I tried to reproduce and this seems to be a Chrome only issue. I gave it a try in Firefox without seeing the error, then switched over to Chrome and can reproduce the error. I'll do some more investigation!

**Comment by emmaindal** [comment]
I've now at least been able to identify the difference in the two request urls (and the reason to why this error just show up in one of the two experiences): 

request url navigating to `/docs/default/component/backstage`
Request URL: http://localhost:7007/api/techdocs/static/docs/default/component/backstage/index.html
navigating to `/catalog/default/component/backstage/docs`
Request URL: https://localhost:7007/api/techdocs/static/docs/default/component/backstage/index.html

So in one ssl enabled (which results in this error) and one not. 

I've also been trying to run it with the exact step you provided but without the docker file you provided, and that does not give me the error. So it feels to me like it something in the docker file that causes this problem.

**Comment by ArtemChekunov** [comment]
Hi @emmaindal 

try to modify `app-config.yaml`
```
backend:
 csp:
   upgrade-insecure-requests: false
```

**Comment by starkmatt** [comment]
> Hi @emmaindal
> 
> try to modify `app-config.yaml`
> 
> ```
> backend:
>  csp:
>    upgrade-insecure-requests: false
> ```

Thanks heaps !
This had did the trick for me within my Docker container
