### ISSUE TITLE
Custom columns by entity type in catalog table

### ISSUE THREAD

**Issue by Crevil** [backstage/backstage#11663]
## Feature Suggestion

Currently the `CatalogTable` component renders custom columns based on the entity type if no custom columns are injected in the `columns` property. It would be great to somehow be able to do the same entity type casing for custom columns.
As the API specifices `columns?: TableColumn<CatalogTableRow>[]` there is no way to make this dynamic based on the entity filter.

https://github.com/backstage/backstage/blob/c1511c99a532aeb003a97510a5638bd939ee65ca/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L52

## Possible Implementation

Maybe I'm just missing some kind of extensability handle to actually do this otherwise the it isn't possible. 🙈 

A possible implementation is to extend the `columns` type to accept a callback that can react on the entity type filter much like the internal implementation does. But I don't know what the API should look like.

https://github.com/backstage/backstage/blob/c1511c99a532aeb003a97510a5638bd939ee65ca/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L69-L97

## Context

We have custom columns configured and are extending the table for `Components` to include its `Domain`. The column doesn't make sense when browsing domains in them self.

The internal implemntation of custom columns was introduced in #10462 based on #10452.

**Comment by benjdlambert** [comment]
Basically following these docs but render your own wrapped `CatalogTable` instead?

**Comment by Crevil** [comment]
This actually works all right. Thanks 👍 

I am facing a limitation that I believe is solveable. The [Create Component](https://github.com/backstage/backstage/blob/31499b9c2963ef2090c771b370b6f84e37e7c101/plugins/catalog/src/components/CatalogPage/DefaultCatalogPage.tsx#L75-L78) button uses the [`createComponentRouteRef`](https://github.com/backstage/backstage/blob/31499b9c2963ef2090c771b370b6f84e37e7c101/plugins/catalog/src/routes.ts#L22) but it is not exported from the module and can because of this not be referenced in my "opt out" version.

As it is an external route ref I can just use what ever I have already registered in my `App.tsx` but it seems "wrong" to not use the external reference when it is available. Any thoughts on this?

For others this is my `CustomCatalogTable` component that sets the columns based on the kind filter.

```tsx
function CustomCatalogTable(props: Omit<CatalogTableProps, 'columns'>) {
  const { filters } = useEntityList();

  let columns: Array<TableColumn<CatalogTableRow>>;
  switch (filters.kind?.value) {
    case 'domain':
      columns = [CatalogTable.columns.createNameColumn()];
      break;
    case 'group':
      columns = [
        CatalogTable.columns.createNameColumn(),
        createMetadataDescriptionColumn(),
      ];
      break;

    default:
      columns = [
        CatalogTable.columns.createNameColumn(),
        createMetadataDescriptionColumn(),
        createDomainColumn(),
        CatalogTable.columns.createOwnerColumn(),
      ];
      break;
  }

  return <CatalogTable {...props} columns={columns} />;
}
```

**Comment by Crevil** [comment]
I just realized I can access the routes through the plugin it self by paying a bit attention to the customization guide.

```
  const createComponentLink = useRouteRef(
    catalogPlugin.externalRoutes.createComponent,
  );
```

So the routing stuff works like a charm.

This is awesome. Thanks for pointing me in the right direction @benjdlambert . 🎉

**Comment by alexef** [comment]
Landed here in 2023. Thank you for documenting your custom catalog table, will use it in our use case. This should be part of the customization guide.
