### ISSUE TITLE
Getting started docs 'Setting up authentication' section incomplete

### ISSUE THREAD

**Issue by shippo-lueders** [backstage/backstage#11672]
## Expected Behavior

Backstage should start up after completing the [Setting up authentication](https://backstage.io/docs/getting-started/configuration#setting-up-authentication) and [Setting up a GitHub Integration](https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration) sections of the getting started page.

## Actual Behavior

The login modal displays an error "The GitHub provider is not configured to support sign-in"

## Steps to Reproduce

Follow the directions on this page - https://backstage.io/docs/getting-started/configuration

## Context

After googling for the error, I found this [Issue](https://github.com/backstage/backstage/issues/10983) which led me to the [Identity Resolver](https://backstage.io/docs/auth/identity-resolver) page which referenced `packages/backend/src/plugins/auth.ts` - and after looking at the source, I ended up uncommenting the following code
```js
        signIn: {
          resolver: providers.github.resolvers.usernameMatchingUserEntityName(),
        },
```

This got me past the previous error but led to a 'user not found error'.  This, along with some log statements led to the conclusion that backstage was expecting a user in it's system that matched the username of my GitHub account, so I added the following to `examples/org.yaml` which `app-config.yaml` automatically imports.
```yaml
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: <github username>
spec:
  profile:
    displayName: ...
    email: ...
  memberOf: [guests]
```

After these updates, I was able to successfully log in.  I'm new to Backstage so I'm not sure whether these steps are appropriate or whether there's a better solution, but these steps worked for me so I figured I'd post this for anyone else having the same problem.

**Comment by benjdlambert** [comment]
So I added some documentation here #11711 to point to the relevant documentation. There's some more changes coming soon too, #11715.

**Comment by benjdlambert** [comment]
Closing this as I believe that the PR's for updating the documentation has been merged!
