### ISSUE TITLE
[Sentry] Allow to overwrite organization for components

### ISSUE THREAD

**Issue by antoniomuso** [backstage/backstage#11688]
The Sentry plugin allows passing only an organization inside the backstage configuration file. But this is not too good if I want to use backstage for different Sentry organizations.

## Feature Suggestion

I suggest adding the possibility to overwrite the organization in a component using a new annotation:
```yaml
sentry.io/organization: anotherOrg
```

WDYT?

**Comment by benjdlambert** [comment]
Probably make sense, how will this work with authentication. Do all organizations live under one account, or do we also need a `sentry-backend` plugin that can manage difference auth configs?

**Comment by antoniomuso** [comment]
I think it is better to use the first approach because you can filter the organizations you want to use through the account.

**Comment by jhaals** [comment]
To clarify @benjdlambert's question;
Can you access the all the organisations with the same API key or do you need a separate key for each organisation?

In case it's the same key for all orgs then doing it like this probably make sense. If we need a separate api key for each org then it's probably best too look into creating a sentry backend.

**Comment by antoniomuso** [comment]
I can access all the organizations with the same API key, so we don't need a sentry backend.
