### ISSUE TITLE
Individual URLs for custom tabs in Documentation landing page

### ISSUE THREAD

**Issue by adrianke77** [backstage/backstage#11684]
## Feature Suggestion

Currently Documentation landing page does not have URL routing to individual custom tabs, unlike the tabs in Explore or other main pages. Would be good to allow the custom config for the landing page also cause this to be set up.

## Context

This is useful for bookmarking or passing links to individual tabs around.

**Comment by benjdlambert** [comment]
Is this techdocs or backstage.io/docs? Not sure I understand this ticket?

**Comment by garyniemen** [comment]
@adrianke77 Can you include a screenshot so we can more fully understand what you mean with this enhancement.

**Comment by adrianke77** [comment]
Currently, if `base-url/docs` redirects to the Documentation page, selecting individual tabs does not add additional pathing to the URL. This makes it not possible for individual tabs to be bookmarked etc

![image](https://user-images.githubusercontent.com/14866712/173024526-183022a3-e420-4c9b-ac89-ddeec58fe53b.png)

For the Explore page, `base-url/explore` redirects to the page, but there is also a path suffix unique to the current tab, here being '/tools':
![image](https://user-images.githubusercontent.com/14866712/173025180-700fc587-22ba-47e1-8274-5cd0e356d374.png)

So the feature request is to have a similar indication in the URL of what tab the user is on for the Documentation page. This could be a suffix specified for each tab in the custom config for the Documentation landing page.

**Comment by garyniemen** [comment]
Aha I see. It looks to me like those tabs on the Docs page are specific to your Backstage instance. We don't have them internally and they are not on our demo installation. Not to say that it's not a good idea though of course - the tabs and the URL suffix. Feel free to have a go to implement this yourself.

**Comment by adrianke77** [comment]
Yes the tabs are custom to our Backstage instance. It was set up using the custom documentation page tab capability now available in Backstage. 
The intent was to highlight that the way of setting up easily setting up custom tabs at the moment doesn't also map URLs to them and it would be nice if it did.
