### ISSUE TITLE
Backstage Proxy Standalone server is returning 

### ISSUE THREAD

**Issue by nitinPaypay** [backstage/backstage#11738]
I need to make an external API call from my Plugin so i have setup proxy for that and running this backstage proxy as standalone server. Now while running my plugin the standalone proxy is returning 404.

## Expected Behavior

Backstage standalone proxy server should return the external api call.

## Actual Behavior

Getting 404 from backstage proxy standalone server. 
Backstage proxy server log - 
2022-05-31T04:24:21.994Z backstage info ::1 - - [31/May/2022:04:24:21 +0000] "POST /api/proxy/newrelic/graphql/ HTTP/1.1" 404 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36" type=incomingRequest

## Steps to Reproduce

1. Creating new plugin by following this document - https://backstage.io/docs/plugins/create-a-plugin
2. Have setup the proxy by following this document - https://backstage.io/docs/plugins/call-existing-api
3. Running the backstage proxy backend as standalone server on : localhost:7007

## Context

I am working on creating new plugin and calling NewRelic graphql APIs. Now i am using backstage proxy for the NewRelic graphql api call.

Proxy configuration in app-config.yaml 
----------------------------------------
proxy:
  '/newrelic/graphql':
    target: https://api.newrelic.com/graphql
    headers:
      Api-Key: *********************

Plugin code to call this API
----------------------------------------
    const apiUrl = `${await this.discoveryApi.getBaseUrl(
      'proxy',
    )}/newrelic/graphql/`;

    const myHeaders = new Headers();
    myHeaders.append('Content-Type', 'application/json');

    const requestOptions: RequestInit = {
      method: 'POST',
      headers: myHeaders,
      body: requestBody,
    };
    const response = await this.fetchApi.fetch(apiUrl, requestOptions);

**Comment by anicke** [comment]
Have you tried removing the trailing slash in your "apiUrl"?

**Comment by KeesCBakker** [comment]
@nitinPaypay did you get it to work?

**Comment by pablosettecase** [comment]
I have the same issue. I have my own plugin, and when trying to use the proxy I get **net::ERR_ABORTED 404 (Not Found)**.

My config in both app-config.yaml and app-config.local.yaml is:
```
proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  jira: https://myjiraurl.org/jira/rest/api/2/issue
```

The Backstage logs on startup show what I expect:
```
[1] 2023-05-23T02:13:42.686Z proxy info [HPM] Proxy created: jira  -> https://myjiraurl.org/jira/rest/api/2/issue type=plugin
[1] 2023-05-23T02:13:42.687Z proxy info [HPM] Proxy rewrite rule created: "^/api/proxy/jira/?" ~> "/" type=plugin
```

Part of my plugin code for the proxied API request:
```
import { useApi, configApiRef } from '@backstage/core-plugin-api';

const config = useApi(configApiRef);
...
const backendUrl = config.getString('backend.baseUrl');
const url = `${backendUrl}/api/proxy/jira`;
const params = {
    headers: {
        "Content-Type": "application/json",
        "Authorization": "Bearer Token mysecrettoken",
    },
    body: JSON.stringify(data),
    method: "POST"
}
fetch(url, params)
.then(resp => {
    return resp;
});
```

In the browser I get the error Not Found:
```
POST http://localhost:7007/api/proxy/jira net::ERR_ABORTED 404 (Not Found)
```

**Comment by pablosettecase** [comment]
An update: GET requests go through but POST requests do not. I get 403 Forbidden error. This is my configuration for the proxy:

```
proxy:
  '/jira': 
    target: https://myjiraurl.org/jira/rest/api/2/issue
    headers:
      Authorization: ${AUTH_HEADER}
      Content-Type: application/json
    allowedHeaders: ['Authorization', 'Content-Type']
    allowedMethods: ['GET', 'POST']
```

and in my plugin I have:

```
const url = `${backendUrl}/api/proxy/jira`;
const data = {
    fields: {
        project:
        {
            key: "PROJKEY"
        },
        summary: "New Project Request",
        description: "something",
        "duedat": "2023-06-01",
        "assigne": { name:"me" },
        "reporte": { name:"me" },
        issuetype: {
            name: "Task"
        }
    }
}

const params = {
     headers: {
         "Authorization": "Bearer supersecrettoken",
         "Content-Type": "application/json"
     },
    body: JSON.stringify(data),
    method: "POST"
}

fetch(url, params)
.then((resp) => {
    if (resp.ok) {
        return resp.json();
    }
    console.log(resp);
    return false;
})
```

I can't get the POST request to go through. Any ideas for how I can debug this?
