### ISSUE TITLE
Entities REST API ignores 2nd and subsequent query parameters

### ISSUE THREAD

**Issue by paristote** [backstage/backstage#11770]
## Expected Behavior

All query parameters of the entities endpoint should be used when processing requests.
For example, a request like `GET /entities?filter=kind=user&fields=metadata.name` should process both `filter` and `fields` parameters.

## Actual Behavior

Only the first query parameter is used.
For example, 
* `GET /entities?filter=kind=user&fields=metadata.name` and
* `GET /entities?fields=metadata.name&filter=kind=user`

should be exactly the same, but they are not. 

## Steps to Reproduce

1. Fetch the response for `curl https://demo.backstage.io/api/catalog/entities?filter=kind=user&fields=metadata.name`
2. Fetch the response for `curl https://demo.backstage.io/api/catalog/entities?fields=metadata.name&filter=kind=user`
3. Compare the responses -> they are different

The 1st response contains all the 16 users (correct) but all their fields (incorrect), i.e. the parameter `fields=metadata.name` is ignored.
The 2nd response contains 66 items (incorrect, more than the 16 users) but each item only has the `metadata.name` property (correct), i.e. the parameter `filter=kind=user` is ignored.

The issue also affects requests with more than one `filter` parameter, e.g. when fetching all components with different tags
1. Fetch the response for `curl https://demo.backstage.io/api/catalog/entities?filter=metadata.tags.java&filter=metadata.tags.go`
2. Compare the response to the list of components on https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all

The components with tag `go` are missing from the response.

## Your Environment

- User agent: curl 7.79.1 (x86_64-apple-darwin21.0)
- Backstage version in our environment: 0.69.1

**Comment by freben** [comment]
I'm not at the computer to check, but I suspect that this may be your shell that's confusing you. The ampersand character probably has to be escaped, or the entire url quoted. Try

`curl 'https://demo.backstage.io/api/catalog/entities?filter=kind=user&fields=metadata.name'`

(note the quotes, you can also try double quotes instead of single)

**Comment by paristote** [comment]
Hi @freben , you're right it was the `&` character, it works well with the URL between quotes.
