### ISSUE TITLE
scaffolder: create component SignedInUserEmail

### ISSUE THREAD

**Issue by gabriel-dantas98** [backstage/backstage#11851]
Create a new component to have access to the user's email

## Feature Suggestion

One of the things I needed to develop the templates was to have information on who is running the template.
In my scenario, the idea is to be able to pass this email as a description of the Pull Request.

The idea is to make the field read-only.

## Possible Implementation

```typescript
import React, { useEffect } from 'react';
import { TextField } from '@material-ui/core';
import { FieldExtensionComponentProps } from '@backstage/plugin-scaffolder';
import { useUserProfile } from '@backstage/plugin-user-settings';

/**
 * SignedInUserEmail Picker
 */
export const SignedInUserEmailExtension = (props: FieldExtensionComponentProps<string>) => {
  const {
    required,
    schema: { title = 'User', description },
    rawErrors,
    formData,
    onChange,
    uiSchema: { 'ui:autofocus': autoFocus },
    idSchema,
  } = props;

  const { loading, profile } = useUserProfile();

  useEffect(() => {
    if (!loading) {
      onChange(profile.email);
    }
  }, [onChange, loading]);

  return (
    <TextField
      id={idSchema?.$id}
      label={title}
      required={required}
      value={profile.email ?? ''}
      margin="normal"
      helperText={description}
      error={rawErrors?.length > 0 && !formData}
      inputProps={{ autoFocus, readOnly: true }}
    />
  );
};
```

**Comment by freben** [comment]
Am I understanding it correctly that you technically don't need this value in the frontend as such, but rather want it available in the template itself? In later versions of the scaffolder, this is actually already available as e.g. `${{ user.entity.spec.profile.email }}` automatically. Does that achieve what you wanted to do?
