### ISSUE TITLE
Improve Local Template Development Experience

### ISSUE THREAD

**Issue by andresmonc** [backstage/backstage#11853]
## Feature Suggestion
Improve Local Template Development Experience

Currently developing on a template is cumbersome for our team. It requires us to do the following
- create a repository from the template wizard
- develop our changes on the new dummy repository
- manually move our changes to the template repo in a templatized format
- delete dummy repository 

I believe there's a few ways this problem could be handled but my suggestion is create a script for developing locally to interpolate nunjucks and then another to revert back to a nunjucks format
 

## Possible Implementation
One idea I had was to create a script for local development

npm run interpolate:
     - parse files line by line using nunjucks renderString. relying on a custom nunjucks config file provided by the user
     - store the templatized value (ex: ${{value.name}}) in a map along with the values that replaced it (ex: 'unique-string-1234')
     - store the above map on disk (ex: .backstagedev)
     - ready for development
npm run templatize:
     - load the .backstage file from disk
     - use the map above and do string replaces on file contents so unique-string-1234 -> ${{value.name}}
     - ready to push

I created a script similar to this for my team but instead relied on git commits. My script parses everything using nunjucks and then uses a git revert to undo the parsing and if there are conflicts this is handled via the stand git merge conflict resolution. This is not an optimal solution and I feel that this is something that backstage should work to solve in order to improve the overall experience.

**Comment by farhan-triplelift** [comment]
This has been a huge issue for our company as well. Our main paint point is there is no ability un-nunjuctify the templated code for code we've been developing on. Back porting the changes has been such a pain.

**Comment by Rugvip** [comment]
#11173 was released in the most recent `next` release, give it a spin! 😁

**Comment by andresmonc** [comment]
@Rugvip Hello Patrick! Not sure if i fully understand how the dry rub feature works. Would I be able to run the template locally with interplayed values?

**Comment by Rugvip** [comment]
@andresmonc how so, it's exactly what it does? You load in a local template into the editor, make changes, execute it, and view the results.

**Comment by andresmonc** [comment]
@Rugvip  What we're talking about is the ability to compile and run the code in your template. 
We are using template syntax in our Java template and so we can't compile our Java project for local development on the template.

**Comment by Rugvip** [comment]
@andresmonc ah alright, do you think an option to either download or save the dry-run result to a different folder would do it?

**Comment by Rugvip** [comment]
Dunno about re-upload, seems a bit tricker for a lot of reasons. Download should be pretty straight forward I think. All the data is there already, so just need to package it up with something like https://gildas-lormeau.github.io/zip.js/ in the frontend.

**Comment by erikahansen** [comment]
I'm not sure if it is possible but I was hoping we'd see something like this without having to run backstage. It's only inputs to a template, right?
