### ISSUE TITLE
Lerna Support has moved to Nrwl

### ISSUE THREAD

**Issue by mstelz** [backstage/backstage#11876]
## Feature Suggestion

[Lerna maintenance may be in question](https://github.com/lerna/lerna/issues/2703). As a result, we may want to switch to an alternative solution (such as [Nx](https://nx.dev/migration/adding-to-monorepo)). 

## Possible Implementation

Swap over to NX or another alternative

## Context

Move to a more frequently maintained toolchain to prevent technical debt

**Comment by Rugvip** [comment]
Thank you for the suggestion! Closing this as a duplicate of #11570
