### ISSUE TITLE
Software template frontend URL is not namespaced

### ISSUE THREAD

**Issue by DavidZemon** [backstage/backstage#11875]
## Expected Behavior

Software templates should include the namespace in the browser URL. For instance, a template with namespace `default` and name `my-template` with hostname `myco.com` should be found at `https://myco.com/create/templates/default/my-template`

## Actual Behavior

The example above is hosted at `https://myco.com/create/templates/my-template`.

## Steps to Reproduce

Add a software template to an instance of Backstage and navigate to it. Note that the browser URL does not include the template's namespace.

## Your Environment

- Output of `yarn backstage-cli info`: 

We've watched the 1.2.1 and 1.2.2 releases closely, looking for if this namespace issue was resolved and have not seen anything related which is why we have not yet applied those patches.

```text
OS:   Darwin 21.5.0 - darwin/x64
node: v14.19.0
yarn: 3.2.1
cli:  0.17.2-next.0 (installed)

Dependencies:
  @backstage/app-defaults                            1.0.2
  @backstage/backend-common                          0.13.5
  @backstage/backend-tasks                           0.3.1
  @backstage/catalog-client                          1.0.2
  @backstage/catalog-model                           1.0.2
  @backstage/cli-common                              0.1.9
  @backstage/cli                                     0.17.2-next.0
  @backstage/config-loader                           1.1.1
  @backstage/config                                  1.0.1
  @backstage/core-app-api                            1.0.2
  @backstage/core-components                         0.9.4
  @backstage/core-plugin-api                         1.0.2
  @backstage/dev-utils                               1.0.2
  @backstage/errors                                  1.0.0
  @backstage/integration-react                       1.1.0
  @backstage/integration                             1.2.0
  @backstage/plugin-api-docs                         0.8.5
  @backstage/plugin-app-backend                      0.3.32
  @backstage/plugin-auth-backend                     0.14.0
  @backstage/plugin-auth-node                        0.2.1
  @backstage/plugin-catalog-backend-module-bitbucket 0.1.3
  @backstage/plugin-catalog-backend                  1.1.2
  @backstage/plugin-catalog-common                   1.0.2
  @backstage/plugin-catalog-graph                    0.2.17
  @backstage/plugin-catalog-import                   0.8.8
  @backstage/plugin-catalog-react                    1.1.0
  @backstage/plugin-catalog                          1.2.0
  @backstage/plugin-github-actions                   0.5.5
  @backstage/plugin-home                             0.4.21
  @backstage/plugin-jenkins-backend                  0.1.22
  @backstage/plugin-jenkins-common                   0.1.4
  @backstage/plugin-jenkins                          0.7.4
  @backstage/plugin-org                              0.5.5
  @backstage/plugin-permission-common                0.6.1
  @backstage/plugin-permission-node                  0.6.1
  @backstage/plugin-permission-react                 0.4.1
  @backstage/plugin-proxy-backend                    0.2.26
  @backstage/plugin-scaffolder-backend               1.2.0
  @backstage/plugin-scaffolder-common                1.1.0
  @backstage/plugin-scaffolder                       1.2.0
  @backstage/plugin-search-backend-module-pg         0.3.3
  @backstage/plugin-search-backend-node              0.6.1
  @backstage/plugin-search-backend                   0.5.2
  @backstage/plugin-search-common                    0.3.4
  @backstage/plugin-search-react                     0.2.0
  @backstage/plugin-search                           0.8.1
  @backstage/plugin-stack-overflow                   0.1.1
  @backstage/plugin-tech-radar                       0.5.12
  @backstage/plugin-techdocs-backend                 1.1.1
  @backstage/plugin-techdocs-module-addons-contrib   1.0.0
  @backstage/plugin-techdocs-node                    1.1.1
  @backstage/plugin-techdocs-react                   1.0.0
  @backstage/plugin-techdocs                         1.1.1
  @backstage/plugin-user-settings                    0.4.4
  @backstage/release-manifests                       0.0.3
  @backstage/search-common                           0.3.4
  @backstage/test-utils                              1.1.0
  @backstage/theme                                   0.2.15
  @backstage/types                                   1.0.0
  @backstage/version-bridge                          1.0.1

```

**Comment by benjdlambert** [comment]
Hey :wave: You've got good eyes! We noticed this, and it's been fixed in the `next` routes https://github.com/backstage/backstage/pull/10575 part of the rewrite #10430 :) So it's coming, just not sure on any timelines as of yet.

**Comment by DavidZemon** [comment]
Any chance of getting a fix or workaround backported? I see that ticket was opened back on April 1, so I'm figuring this won't get released any time soon, but this has been a bug for even longer. I first reported this in Discord on March 4 but apparently dropped the ball and never created the ticket for it as @freben suggested I do.

**Comment by DavidZemon** [comment]
Yes, precisely. Right now, our template starter (we have a template for creating templates) that has this in it:

```yaml
metadata:
  # FIXME: This should be uncommented as soon as the EDP team reaches out to inform Template maintainers that
  #          namespaces are fully supported in entities of kind "Template"
#  namespace: ${{ values.train }}
  name: ${{ values.repoUrl.repo | lower }}
  title: ${{ values.title }}
  description: ${{ values.description }}
```

It's pretty painful... and the longer it goes on, the more painful it's going to be to reach out to all the disparate teams that have created their own templates and get them to uncomment that line.

**Comment by benjdlambert** [comment]
Yep I appreciate that, just actually looking through that PR, I actually don't think that there's anything that's blocking us doing that routing change right now, maybe we just need to be a little careful about routing and not breaking peoples bookmarks? So maybe changing the route to what the new one is in the `/next` PR, and then if that param is not provided then it 302's to auto fill in to `default` as the namespace?

Is this something you want to have a stab at implementing @DavidZemon? Otherwise I can see if I can get it in before the release on tuesday.

**Comment by DavidZemon** [comment]
I won't have a chance to tackle this before Monday's release, so if you could get it done by then, I'll owe you a beer for sure!

**Comment by benjdlambert** [comment]
Challenge accepted. 👍
