### ISSUE TITLE
Search feature is not working as expected after upgrade from v1.1.1 to v1.2.2

### ISSUE THREAD

**Issue by SerenaIce** [backstage/backstage#11889]
Issue:

After backstage upgrade from v1.1.1 to v1.2.2, the search feature is not stable, sometimes it works, but most time it doesn't.
And sometimes the query returns data back, sometimes the same query returns nothing without error, but sometimes the same got 502 errors.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/43363062/172508165-5603496f-e53e-4299-beab-02db5bf3be5f.png">

<img width="827" alt="image" src="https://user-images.githubusercontent.com/43363062/172509074-e2d8dd05-dba2-48df-85ba-ba141f924b6f.png">

It's weird. What's changed between v1.1.1 and v 1.2.2? 

Environment:

MacOS
Not browser related

**Comment by garyniemen** [comment]
@SerenaIce Did this get resolved?

**Comment by emmaindal** [comment]
I'll close this issue, please re-open if the issue still occurs @SerenaIce
