### ISSUE TITLE
GitHub Pull Request board hardcodes assumption on entity shape

### ISSUE THREAD

**Issue by julioz** [backstage/backstage#11888]
## Expected Behavior

Setting up the GitHub Pull Request Board plugin renders the pull requests for all components under a team's ownership.

## Actual Behavior

In our setup, the catalog groups are populated from the github-org provider, and we do see owned Components, but the board showed up with no data in the entity page. Our component `type` values are specific to our organization (e.g we don't call backend services `service` but further classify like `gateway`, `foundation-service`, etc).

<img width="805" alt="ghprb" src="https://user-images.githubusercontent.com/1541701/172326592-231146c9-4c96-4bff-a22e-52cc9c00f77e.png">

## Context

I drilled down in the source code, and found this line (https://github.com/backstage/backstage/blob/b5e056f3124a2c0fd23fc94a5d42f1d54d158c0a/plugins/github-pull-requests-board/src/hooks/useUserRepositories.tsx#L30), that queries the catalog for Components whose type == service (this is not the taxonomy we use at my org) so the dataset is returned empty.

**Comment by freben** [comment]
Hi! Sounds like an enhancement request on that plugin to make it more flexible. Pinging @gregorytalita who made the plugin. Is this something you might be interested in working on?

**Comment by leon-vg** [comment]
I suggest an addition - add the option to set your own filter. 

I'm thinking of repositories that contain many entities owned by different teams in one big yaml file. In the current setup of this plugin I think all the teams mentioned in this yaml would see Pull Requests for such a repository, right?

Two approaches - either add the option to add some filter object to the React component(s) or exposing an api that can be overridden, as is implemented in various other plugins. Or both...
