### ISSUE TITLE
Enhanced Collapsible Table Design

### ISSUE THREAD

**Issue by Expalex** [backstage/backstage#11880]
## 🗒 General

Expedia Group would like to propose an [Enhanced Collapsible Table](https://www.figma.com/proto/qhmbRRXcLXB4QP494nq8LI/New-Table?page-id=0%3A1&node-id=0%3A1&viewport=361%2C298%2C0.27&scaling=scale-down&starting-point-node-id=2%3A2432&show-proto-sidebar=1) (Figma) design .

## 💻 Usage
This new version will replace https://mui.com/material-ui/react-table/#collapsible-table. 
This version will be be easier to view, save space, scalable, and more consistent with the rest of Backstage design.

**Comment by freben** [comment]
Alright, this is a useful feature. But I'm not sure what you mean by "replace" - will we try to leverage existing functionality as much as possible, e.g. making these extra row contents more of an optional extension to the current model?

**Comment by Expalex** [comment]
@freben
https://mui.com/material-ui/react-table/#collapsible-table is what our team contributed last year. Since this is an improved version the old one can be replaced with the new. But if you choose to keep the old that’s fine too. Either way our dev team will start working on this and share with you. :)

**Comment by shailendra-ahir-cbre** [comment]
Hi guys, I have a question.
Does backstage use, [material-table](https://www.npmjs.com/package/material-table) or mui react-table (https://mui.com/material-ui/react-table).

**Comment by Expalex** [comment]
@freben would have best answers.

**Comment by Rugvip** [comment]
@shailendra-ahir-cbre we use https://www.npmjs.com/package/material-table, but that in turn uses https://mui.com/material-ui/react-table afaik.

I'm wondering what the addition that you're proposing would look like? From what I gathered so far it sound like something to contribute to MUI rather than Backstage?
