### ISSUE TITLE
Inconsistent Sidebar State whilst pinning and Unpinning

### ISSUE THREAD

**Issue by NishkarshRaj** [backstage/backstage#11885]
## Expected Behavior

The sidebar and the Main View are responsive to the **pin** and **unpin** functionality present on the Settings page.

This works perfectly in the Vanilla Backstage we have spun on our workstation.

https://user-images.githubusercontent.com/35298207/172301032-2586f0cc-5d90-4ef3-8aea-69cab5cedf86.mov

## Actual Behavior

After the upgrade to `v1.1.1` - we have faced the following bug.

I don't think this bug originates from Core Backstage and it's definitely something on our end but would like to understand if anyone has faced this issue and also how can we resolve this.

If we start from the pinned sidebar:

![pinned-sidebar](https://user-images.githubusercontent.com/35298207/172301640-e7cc57cd-6ef0-4e61-ae79-d7b7a74168e1.png)

And unpin from Sidebar, we get this inconsistent state:

![unpin-bug](https://user-images.githubusercontent.com/35298207/172301685-3056b4c4-ab87-417d-babe-cc8c8f832d06.png)

Once we hit refresh, the issue is resolved.

![unpin-refresh](https://user-images.githubusercontent.com/35298207/172301696-f4781e5d-d2c6-415c-a378-02d614acd228.png)

The same thing happens when we pin the sidebar.

![pin-bug](https://user-images.githubusercontent.com/35298207/172301723-dd11a93d-5db7-443c-a245-c8231e28a85a.png)

## Steps to Reproduce

Pin/Unpin the Sidebar from the Settings Page.

## Context

Poor user experience if we promote the changes - or delayed releases if wait till a fix is found.

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

Customized Backstage synced to `v1.2.0` upstream release.

**Comment by freben** [comment]
Oh I think was an actual bug, that was [addressed recently](https://github.com/backstage/backstage/pull/11629). What you might try, short of upgrading to `-next` versions, is to make sure that you don't have any duplicates of `@backstage/core-components` in your `yarn.lock` file. This can take a little bit of sleuthing to get right, let me know how it goes.

**Comment by NishkarshRaj** [comment]
@freben 👋 

I will play around with the pre-release and test this. Thanks 👍

**Comment by NishkarshRaj** [comment]
I deleted my `yarn.lock` and did a clean installation of the dependencies and the issue is fixed. 😄 

Thanks @freben ❤️
