### ISSUE TITLE
Gitlab Webhook Action Support?

### ISSUE THREAD

**Issue by ChrisJBurns** [backstage/backstage#11884]
Would there be a possibility of adding Webhook support for the Gitlab Actions? Similar to how we do it in the GitHub Actions code: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/githubWebhook.ts

**Comment by freben** [comment]
That would probably make sense! We don't have it on our own roadmap right now, but we'd definitely appreciate a contribution to that end.

**Comment by ChrisJBurns** [comment]
Not a JS guru but I can give it a shot.
