### ISSUE TITLE
Error: Could not Fetch catalog entities

### ISSUE THREAD

**Issue by siddharth159** [backstage/backstage#11987]
Hi,

I have setup Backstage on Amazon EC2 instance  Linux/UNIX , Ubuntu 20.04, t2 large.

start with yarn dev command (ss below) seems every catalog is loaded but still in component item it is showing error:

![image](https://user-images.githubusercontent.com/27622350/173278937-186c1994-480a-4fe6-b825-81b67505f71c.png)

![image](https://user-images.githubusercontent.com/27622350/173279028-929b4076-498c-43b7-8a6a-fd571daaf1ff.png)

Please help.

**Comment by siddharth159** [comment]
Can someone please help me on this.

**Comment by siddharth159** [comment]
No @Rugvip this is not an issue because if my run "yarn dev" via root access so everything fine (logs attached below)
![image](https://user-images.githubusercontent.com/27622350/173736333-fa352099-11da-42c4-a6a9-9551ce18c352.png)
![image](https://user-images.githubusercontent.com/27622350/173736368-4b2dd469-4128-4bac-9a90-08e3aebff7cc.png)
but still issue is persist in backstage portal and when I try to inspect it getting error connection timeout and I see "Private IP" of my machine .

![image](https://user-images.githubusercontent.com/27622350/173736544-62851382-0570-4744-b0fd-b77cb8ab0c35.png)

**Comment by siddharth159** [comment]
@Rugvip could you please check on this.

**Comment by jhaals** [comment]
Looks like your backend is listening on port 172(logged as `Listening on :172`) which explains why the frontend are not able to reach it on port 7007. Make sure your backend port is configured to 7007 in app-config.yaml

**Comment by siddharth159** [comment]
@jhaals sorry but I didn't get your point below is my app.config.yaml file and i have referred localhost with my "PRIVATE IP" in hosts file.

![image](https://user-images.githubusercontent.com/27622350/174250389-59a95ea6-27e3-4f9a-8ac2-c7ea2c1aeacd.png)

**Comment by jhaals** [comment]
The indentation of your configuration file is incorrect and `listen` should not be given a hostname. listen and port are at the same level in your config file.

Here's an example of a correctly formatted config file

```yaml
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
```

**Comment by siddharth159** [comment]
Hi @jhaals could you let me know about my configuration I'm trying to setup my BackStage on EC2 instance so instead of localhost I'm using my "Private IP" of EC2 machine and accessing the portal from External IP with port 3000 and for backend port I'm using 7007 but still facing issues to fetch catlog entites

**Comment by benjdlambert** [comment]
The `backend.baseUrl` and `app.baseUrl` should be URL's that you use to access the backstage application and what is in the address bar from your browser. So if you expect to be browsing backstage at `http://49.32.29.39` or whatever, then it would be that in the `baseUrl` part, and the `listen` should be `0.0.0.0` or something to listen on all addresses rather than just `localhost`

**Comment by nileshgadgi** [comment]
I am stuck in this issue. Please help if somebody have idea about it.

```
app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: Clouddrove

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    client: pg
    connection:
      host: localhost
      port: 5432
      user: postgres
      password: postgres
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration
      token: ${GITHUB_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}

proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  # endpoints:
  #   '/test':
  #     target: 'https://example.com'
  #     changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers: {}

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example template
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

    ## Uncomment these lines to add more example data
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    ## Uncomment these lines to add an example org
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
    #   rules:
    #     - allow: [User, Group]
```

I am using this configuration for my backstage setup. having this error while accessing it on browser.


![image](https://github.com/backstage/backstage/assets/115100281/4f342a9c-eadd-41ee-8556-c911ca8ec1a7)

**Comment by benjdlambert** [comment]
@nileshgadgi this error message is a symptom that your backend cannot start. If you are using `yarn dev` locally and get this error message please check the logs in the terminal to find the error why it cannot start.

**Comment by MrMarga** [comment]
@siddharth159  @nileshgadgi  .... 
Bro I am getting the same issue while installing on aws ec2 . Did you find the solution .? please let me know at "margaghale31@gmail.com"
