### ISSUE TITLE
backend: add signal handlers for controlled shutdown and to fix shutdown in Docker

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#12017]
## Feature Suggestion

Add a signal handled that handles shutdown of the Backend. Both for the purposes of a controlled shutdown, but also to make the backend exit properly when running in docker.

## Possible Implementation

This may be something that makes sense to make part of #11611 rather than to be implemented immediately, as we currently don't have any API surface in the backend where this fits very well. The primary candidate is of course `createServiceBuilder` but we may want to register the handlers earlier than that.

## Context

#11954

**Comment by jhaals** [comment]
> Is there any workaround for this at the moment? Inability to shutdown cleanly is creating lots of orphaned processes when trying to run in docker locally

Hi! Could you provide some additional context to how this manifests itself for you currently. How are you stopping the service and what processes do you see?

**Comment by bforbis** [comment]
A quick workaround solution is to use the `--init` option for docker which wraps the process in a baked in signal handler in the docker engine.

**Docker Run**
`docker run --init`

**Docker Compose**
```yaml
version: '3'
services:
  backstage:
    build: .
    init: true
```

**Comment by jhaals** [comment]
There is some progress on this in the new backend system that we're currently developing. It has a built-in [LifecycleService](https://github.com/backstage/backstage/blob/master/packages/backend-plugin-api/src/services/definitions/LifecycleService.ts) where a plugin can register a shutdown hook that is executed when the backend receives a stop signal. The final piece there is to add a process.exit() once the hooks are executed.

**Comment by Rugvip** [comment]
This is implemented in the new backend system
