### ISSUE TITLE
Add CA option to CertificateReferenceOptions in HttpsSettings

### ISSUE THREAD

**Issue by Kuan-Ying** [backstage/backstage#12029]
Backstage currently allows https configuration when starting the node server in app-config.yaml as below:
```yaml
backend:
  https:
    certificate:
      cert:
        ...
      key:
        ...
```
but there is no option to provide additional CA. The only work around is to add `NODE_EXTRA_CA_CERTS` when start the node server, which works but developers will need to set up it in a different place.

## Feature Suggestion

Add a config ca in `backend.https.certificate` options:
```yaml
backend:
  https:
    certificate:
      cert:
        ...
      key:
        ...
      ca:
        ...
```

## Possible Implementation

Backstage uses node.js's `https.createServer` method to start a server, and the supported `options` parameters are described in https://nodejs.org/api/tls.html#tlscreateserveroptions-secureconnectionlistener.

Would be nice that Backstage support all of them, or at least support important ones (like CA).

It required changes in
(1) [Pass entire https.settings object to `createHttpsServer`](https://github.com/backstage/backstage/blob/master/packages/backend-common/src/service/lib/hostFactory.ts#L72):
Instead of always only extracting `cert` and `cert`, pass the entire `httpsSettings` to `https.createServer`.

(2) [Update `CertificateReferenceOptions` type in the config types](https://github.com/backstage/backstage/blob/master/packages/backend-common/src/service/lib/config.ts#L30)
I feel we can make the type `CertificateReferenceOptions` becomes:
```ts
export type CertificateReferenceOptions = {
  key: string;
  cert: string;
  ca: string;
} & Record<string, any>;
```
or just make it an object and point the developers to this doc https://nodejs.org/api/tls.html#tlscreateserveroptions-secureconnectionlistener for the possible options.

## Context

In our company, intermediate CAs are installed to remote hosts and developers desktops / laptops. In order to connect to our internal services, we always need to provide intermediate CA when making network requests.

`NODE_EXTRA_CA_CERTS` is convenient but it would be nice to keep all https settings in a centralized place

**Comment by Rugvip** [comment]
Yep, makes sense! 👍 

Is it something you'd like to contribute?

**Comment by Kuan-Ying** [comment]
Sure. I'm happy to help contribute to this. Will work on this when I get time :)

**Comment by loubevi** [comment]
Would love to see this feature as well.  Any possibility of reopening?
