### ISSUE TITLE
Update publish:gitlab:merge-request action to allow commit updates and deletes

### ISSUE THREAD

**Issue by ljiljanaholden** [backstage/backstage#12026]
At the moment, publish:gitlab:merge-request Scaffolder action provides the ability to create merge requests that add new files to a Git repository. We have a scenario where we would like to be able to do both updates and deletes of the existing files.  

## Feature Suggestion

Provide an additional input parameter for the publish:gitlab:merge-request that defaults to 'create' but could also be 'update' or 'delete'. This parameter would be passed to the creation of Git commits in the action's handler. Currently, hardcoded value is 'create'

## Possible Implementation

I am happy to create a PR if you agree that this would be useful.

**Comment by ljiljanaholden** [comment]
OK, great - I'll create a PR soon

**Comment by satrox28** [comment]
Great, we were looking for it.

**Comment by taro-cmd** [comment]
we are interested in this update

**Comment by benjdlambert** [comment]
I think that this has been done and shipped. Closing. Feel free to re-open or comment if there's something missing!
