### ISSUE TITLE
Ability to swap docker with podman

### ISSUE THREAD

**Issue by ericis** [backstage/backstage#12028]
## Feature Suggestion

Support [`podman`](https://podman.io/) as an alternative to `docker` and perhaps the default tool.

Docker Desktop requires paid licensing in large organizations while Podman is a free and still open-source alternative for companies that is almost entirely compatible with the `docker` and `docker-compose` CLI commands. Podman has [recently released official support for macOS and Windows](https://podman.io/releases/2022/05/09/podman-release-v4.1.0.html) in addition to its long-time support for Linux; making `podman` a very viable, cross-platform alternative for companies.

## Possible Implementation

Introduce a new "tool" configuration for selecting Podman or Docker and then refactor the CLI to support the configured tool. For container-based vs. native-based tooling, code that currently offers a `useDocker` option (e.g. [`techdocs-cli serve`](https://github.com/backstage/backstage/blob/c2f9527fe2f2d737ee3e32b4d68d3df7a299c317/packages/techdocs-cli/src/commands/serve/serve.ts#L96)) could be refactored to `useContainer` and then internally use the configured tool.

## Context

Context provided in "Feature Suggestion".

**Comment by Rugvip** [comment]
We currently have the [`ContainerRunner`](https://github.com/backstage/backstage/blob/6d8bf5b9cf494815c0916e18daa226fb8186ba5f/packages/backend-common/src/util/ContainerRunner.ts#L40-L45) interface that we use for executing containers. The [`DockerContainerRunner`](https://github.com/backstage/backstage/blob/6d8bf5b9cf494815c0916e18daa226fb8186ba5f/packages/backend-common/src/util/DockerContainerRunner.ts#L32) is the only concrete implementation of that right now. Does it seem generic enough that we could implement a `PodmanContainerRunner`, and is that something you'd like to contribute?

**Comment by ericis** [comment]
@Rugvip It seems there are at least a couple of different implementations of `docker` then in the code base.

I believe I could make the change to the TechDocs CLI easily enough, but I am guessing that testing the `DockerContainerRunner` requires a much deeper and more thorough understanding of how Backstage is using the Docker API. Would it be appropriate to submit a PR that refactors the CLI separately from the work for `DockerContainerRunner`, since reviews and testing could take much longer?

1. The [`DockerContainerRunner`](https://github.com/backstage/backstage/blob/6d8bf5b9cf494815c0916e18daa226fb8186ba5f/packages/backend-common/src/util/DockerContainerRunner.ts#L32) you shared

    Because this code uses the Docker API and not docker commands, it may be possible to simply start `podman` to host a compatible API, since Podman has [supported a compatible Docker API for at least a couple of years](https://podman.io/blogs/2020/07/01/rest-versioning.html)

2. The hard-coded commands in the TechDocs CLI for the MkDocs server

    https://github.com/backstage/backstage/blob/c9a782d60922ab637d6969b4d8ad43f47bebb737/packages/techdocs-cli/src/lib/mkdocsServer.ts#L29-L58

    Because this code uses `docker` commands, it may be possible to `alias docker='podman'` to route these commands through `podman`, since `podman` is almost entirely compatible with `docker`.

Although there are possibly workarounds for ensuring Backstage can work with `podman`, it would be good to codify the option with explicit, first-class support.
