### ISSUE TITLE
Dependency tree graphs of entities relationship (packages/tools/plugins/...)

### ISSUE THREAD

**Issue by hpbonfim** [backstage/backstage#1204]
I've been working with a lot of tools with amount of dependencies and it's really sucks read all that list when we forget something..

## Feature Suggestion

My suggestion is to do a small graph showing us all entities relationship with a simple fast first look

## Possible Implementation

[Simple relationship image](https://ticpe.files.wordpress.com/2014/12/sistemas-nacionais.jpg)

## Context

An Entity-Relationship Diagram (ERD) is a visual presentation of entities and relationships. That type of diagrams is often used in the semi-structured or unstructured data in databases and information systems. At first glance ERD is similar to a flowchart

**Comment by Rugvip** [comment]
Adding some tooling for inline plantuml in docs as a part of #1217

**Comment by stefanalund** [comment]
@hpbonfim is this something you would be open to helping out with?

**Comment by adamdmharvey** [comment]
Realize this has overlap with my issue here, we were thinking the same thing:
https://github.com/backstage/backstage/issues/4394

Already have some traction on that other issue with a draft PR, at least as it relates to entity relationships within systems - even if it doesn't diagram every entity. That might get to the root ask here, at least to allow for further experimentation/enhancement.

I might suggest given that progress, this older issue could be closed - thoughts?

**Comment by benjdlambert** [comment]
ping @hpbonfim
