### ISSUE TITLE
Align msgraph entity provider config with these of other entity providers

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#12065]
## Feature Suggestion

Use the same configuration scheme as for other entity providers using `catalog.providers.{providerName}[.{providerId}]` as prefix (see e.g. AwsS3EntityProvider, BitbucketCloudEntityProvider, GerritEntityProvider, etc.).

Currently, it uses `catalog.processors.microsoftGraphOrg.providers` as prefix.

**Comment by jhaals** [comment]
Sounds good! Could you help out? 🙏 
We should make sure that it's backwards compatible :)

**Comment by pjungermann** [comment]
@jhaals Yes, this was my plan. I just thought I shared issues instead of post-it at my screen. Also, in case someone else wants to pick it up earlier.
