### ISSUE TITLE
github:publish allows enabling "Require signed commits"

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#12092]
So far as I can see, there is no option to require signed commits do this using the github:publish scaffolder task.

## Feature Suggestion

When configuring a github repo you have the ability to "require signed commits" for pull requests. 

## Possible Implementation

Not sure how it would be implemented.

## Context
Some companies require commits to be signed for verification purposes, by adding the option to the scaffolder task it can be enabled without a manual step.

**Comment by benjdlambert** [comment]
Sorry this one slipped through the net, feeling that we can just add an option to the `publish:github` action to require signed commits like everything else is right now. Would be good to take a look at this long list of options later to work out if we can  break them up into sections, but that's for later.
