### ISSUE TITLE
Permission: All the catalogs owned by the group in which the user is a member should be visible

### ISSUE THREAD

**Issue by cinlysobin** [backstage/backstage#12105]
## Expected Behavior

All the catalogs owned by the group in which the user is a member should be visible

## Actual Behavior

While login I am able to see only the catalog owned by the specific user. not the catalogs owned by the group in which he is a member of.

## Steps to Reproduce

used the following code n permissions.ts

```
if (isPermission(request.permission, catalogEntityReadPermission)) { 
  return createCatalogConditionalDecision(
    request.permission,
    catalogConditions.isEntityOwner(
      user?.identity.ownershipEntityRefs ?? [],
    ),
  );
}
```

## Context
I am trying to implement a rule in my organization where only the member of that team will be able to view their teams catalogs.

"All the catalogs owned by the group in which the user is a member should be visible"

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by Rugvip** [comment]
In release 1.3 we now display the identity information of the user on the settings page, does that look as expected, i.e. is the group information there?

Looks like this:

![image](https://user-images.githubusercontent.com/4984472/174266937-00e3fbd6-fb76-46d0-b33d-98139b131a93.png)

**Comment by CitsGit** [comment]
The package versions that are updated to make permissions working.
@backstage/plugin-permission-common": "^0.6.2
@backstage/plugin-permission-node": "^0.6.2
@backstage/plugin-permission-backend": "^0.5.7

**Comment by CitsGit** [comment]
Hi @Rugvip ,
I tired by upgrading backstage to 1.3
but now instead of username it is showing as guest
![image](https://user-images.githubusercontent.com/98138120/174581532-64ddcf16-2fc5-4b55-8162-46371e3d0775.png)

**Comment by CitsGit** [comment]
Hi @Rugvip,
I have upgraded backstage to 1.3.
Still have the same issue
![image](https://user-images.githubusercontent.com/98138120/174589255-66b021a9-0c7f-45c0-a24c-2d410f16eda2.png)

**Comment by Rugvip** [comment]
@CitsGit Looks like your sign-in resolver doesn't end up assigning groups ownership, could be either the resolver or catalog information that needs a tweak. See https://backstage.io/docs/auth/identity-resolver#backstage-user-identity for a much more in-depth explanation

**Comment by CitsGit** [comment]
@Rugvip ,
It got resolved by using the following code.
https://raw.githubusercontent.com/backstage/upgrade-helper-diff/release/0.4.28-next.0/packages/backend/src/plugins/auth.ts
Thanks a lot for the support and for pinpointing the location where I have to troubleshoot...
