### ISSUE TITLE
Error when running on minikube

### ISSUE THREAD

**Issue by mikeestrada** [backstage/backstage#12101]
## Expected Behavior

- Should be able to run backstage on minikube following [the guide](https://backstage.io/docs/deployment/k8s).

## Actual Behavior

When applying the final manifest for backstage - the image: backstage:1.0.0 returns a ErrImagePull.

I tried other images such as spotify/backstage-cookiecutter:latest but that yielded a whole 'nother slew of errors which I have wrestled with quite a bit. Any guidance would be amazing! Thanks

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by ipedrazas** [comment]
The guide says: 

> To create the Backstage deployment, first create a [Docker image](https://backstage.io/docs/deployment/docker).

The instructions to create that docker image are a bit below in that guide:

```
$ eval $(minikube docker-env)
$ yarn build-image --tag backstage:1.0.0
```
You don't need to push the image to a registry because you're doing the docker build inside of minikube 🙌
