### ISSUE TITLE
Users and groups from MSgraph org discovery not visible in backstage catalog

### ISSUE THREAD

**Issue by mustafazeya** [backstage/backstage#12135]
## Expected Behavior

Users and Groups should be visible in the backstage catalog
![image](https://user-images.githubusercontent.com/31076711/174573130-98fac607-f5b6-4f41-bdec-c4ce3767e0cf.png)

Following the [link](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/README.md), we should be able to use either `entity provider or a processor` to ingest the organization data.

## Actual Behavior

Getting error when using only entity provider to import org data from Azure

`Backend failed to start up, Error: Your config contains a "catalog.locations" entry of type microsoft-graph-org, but does not have the corresponding catalog processor MicrosoftGraphOrgReaderProcessor installed. This processor used to be built into the catalog itself, but is now moved to an external module that has to be installed manually. Please follow the installation instructions at https://backstage.io/docs/integrations/azure/org if you are using this ability, or remove the location from your app config if you do not. You can also silence this check entirely by setting the environment variable BACKSTAGE_CATALOG_SKIP_MISSING_PROCESSORS_CHECK to 'true'.`

## Steps to Reproduce

Follow the [link](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/README.md) and use `entity provider` for ingesting data

## Context
Content of `app-config.production.yaml` 

```yaml
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  processors:
    microsoftGraphOrg:
      providers:
        - target: https://graph.microsoft.com/v1.0
          authority: https://login.microsoftonline.com
          tenantId: ${AUTH_MICROSOFT_TENANT_ID}
          clientId: ${AUTH_MICROSOFT_CLIENT_ID}
          clientSecret: ${AUTH_MICROSOFT_CLIENT_SECRET}
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: github-org
      target: https://github.com/<orgname>
      rules:
        - allow: [User, Group]
    - type: microsoft-graph-org
      target: https://graph.microsoft.com/v1.0
      rules:
        - allow: [Group, User]
    - type: github-discovery
      target: https://github.com/<orgname>

```

Content of `catalog.ts`

```ts
import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';
import {
    GithubDiscoveryProcessor,
    GithubOrgReaderProcessor,
  } from '@backstage/plugin-catalog-backend-module-github';
import {
    ScmIntegrations,
    DefaultGithubCredentialsProvider
  } from '@backstage/integration';
  import { Duration } from 'luxon';
  import { MicrosoftGraphOrgEntityProvider } from '@backstage/plugin-catalog-backend-module-msgraph';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  const integrations = ScmIntegrations.fromConfig(env.config);
  const githubCredentialsProvider =
    DefaultGithubCredentialsProvider.fromIntegrations(integrations);
   // The target parameter below needs to match one of the providers' target
  // value specified in your app-config (see above).
  builder.addEntityProvider(
    MicrosoftGraphOrgEntityProvider.fromConfig(env.config, {
      id: 'production',
      target: 'https://graph.microsoft.com/v1.0',
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: Duration.fromObject({ minutes: 5 }),
        timeout: Duration.fromObject({ minutes: 3 }),
      }),
    }),
  );
  builder.addProcessor(
    GithubDiscoveryProcessor.fromConfig(env.config, {
      logger: env.logger,
      githubCredentialsProvider,
    }),
    GithubOrgReaderProcessor.fromConfig(env.config, {
      logger: env.logger,
      githubCredentialsProvider,
    }),
  );
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}

```
## Your Environment

- Browser Information: `MS Edge Version 102.0.1245.44`

- Output of `yarn backstage-cli info`: 

```text
yarn run v1.22.18
$ /mnt/c/Users/aim729/SAS/CDX/Github/Flysas-tech/cdx-backstage-infra/backstage-app/node_modules/.bin/backstage-cli info
OS:   Linux 4.4.0-19041-Microsoft - linux/x64
node: v16.13.0
yarn: 1.22.18
cli:  0.17.1 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.2
  @backstage/backend-common                        0.13.5, 0.14.0
  @backstage/backend-tasks                         0.3.1, 0.3.2
  @backstage/catalog-client                        1.0.2, 1.0.3
  @backstage/catalog-model                         1.0.2, 1.0.3
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.17.1
  @backstage/config-loader                         1.1.1, 1.1.2
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.2
  @backstage/core-components                       0.9.4
  @backstage/core-plugin-api                       1.0.2
  @backstage/errors                                1.0.0
  @backstage/integration-react                     1.1.0
  @backstage/integration                           1.2.0, 1.2.1
  @backstage/plugin-api-docs                       0.8.5
  @backstage/plugin-app-backend                    0.3.32
  @backstage/plugin-auth-backend                   0.14.0
  @backstage/plugin-auth-node                      0.2.1, 0.2.2
  @backstage/plugin-catalog-backend-module-github  0.1.3
  @backstage/plugin-catalog-backend-module-msgraph 0.3.3
  @backstage/plugin-catalog-backend                1.1.2, 1.2.0
  @backstage/plugin-catalog-common                 1.0.2, 1.0.3
  @backstage/plugin-catalog-graph                  0.2.17
  @backstage/plugin-catalog-import                 0.8.8
  @backstage/plugin-catalog-react                  1.1.0
  @backstage/plugin-catalog                        1.2.0
  @backstage/plugin-github-actions                 0.5.5
  @backstage/plugin-org                            0.5.5
  @backstage/plugin-permission-common              0.6.1, 0.6.2
  @backstage/plugin-permission-node                0.6.1, 0.6.2
  @backstage/plugin-permission-react               0.4.1
  @backstage/plugin-proxy-backend                  0.2.26
  @backstage/plugin-scaffolder-backend             1.2.0
  @backstage/plugin-scaffolder-common              1.1.0, 1.1.1
  @backstage/plugin-scaffolder                     1.2.0
  @backstage/plugin-search-backend-node            0.6.1
  @backstage/plugin-search-backend                 0.5.2
  @backstage/plugin-search-common                  0.3.4, 0.3.5
  @backstage/plugin-search-react                   0.2.0
  @backstage/plugin-search                         0.8.1
  @backstage/plugin-tech-radar                     0.5.12
  @backstage/plugin-techdocs-backend               1.1.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.0
  @backstage/plugin-techdocs-node                  1.1.1
  @backstage/plugin-techdocs-react                 1.0.0
  @backstage/plugin-techdocs                       1.1.1
  @backstage/plugin-user-settings                  0.4.4
  @backstage/release-manifests                     0.0.3
  @backstage/search-common                         0.3.4
  @backstage/test-utils                            1.1.0
  @backstage/theme                                 0.2.15
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

```

**Comment by jhaals** [comment]
Hi! It does indeed look like the processor is not installed. 
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/README.md#using-the-processor

```
// packages/backend/src/plugins/catalog.ts
builder.addProcessor(
  MicrosoftGraphOrgReaderProcessor.fromConfig(env.config, {
    logger: env.logger,
  }),
);
```

**Comment by mustafazeya** [comment]
> Hi! It does indeed look like the processor is not installed. https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/README.md#using-the-processor
> 
> ```
> // packages/backend/src/plugins/catalog.ts
> builder.addProcessor(
>   MicrosoftGraphOrgReaderProcessor.fromConfig(env.config, {
>     logger: env.logger,
>   }),
> );
> ```

@jhaals Do I need to add `processor `even if I am using `Entity Provider`? The documentation says we need to use one of them. Am I missing something here?

**Comment by jhaals** [comment]
I would think that the entity provider would be enough here. I'm guessing that there are already entities in the catalog database table created by the processor. Do you experience the same log lines if you start up with a clean database?

**Comment by pjungermann** [comment]
@mustafazeya I would suggest to keep the provider instead of adding the processor and remove the static location instead
```
    - type: microsoft-graph-org
      target: https://graph.microsoft.com/v1.0
      rules:
        - allow: [Group, User]
```
This will resolve the error message above, too.

Providers have full ownership of created entities and clean up automatically.
https://backstage.io/docs/features/software-catalog/life-of-an-entity

**Comment by pjungermann** [comment]
btw: you can use the transformers as hooks to get more insights on what data you got back from AzureAD / the MS Graph API. Might help with debugging your issue

**Comment by pjungermann** [comment]
>  In logs I see this output very frequently after the processor starts ingesting data.
[2m2022-06-21T10:29:45.979Z[22m [34mcatalog[39m [33mwarn[39m Unable to load photo for 4a65d53f-cf43-48c3-95cc-d87d08e259df [36mtype[39m=plugin

This is just a warning happening within `readMicrosoftGraphUsers` and not failing the ingestion.

The `defaultUserTransformer` treats the photo as optional, too. `spec.profile.picture` will not be set for these.

At least for those logs with `Unable to load photo for` (or `Unable to load userphoto for` which should not appear based on the config you have shared).

**Comment by pjungermann** [comment]
Users returned are required to have the properties `id`, `displayName`, and `mail`. Otherwise, they will be skipped and no User entity will be ingested. (see `defaultUserTransformer`)

**Comment by mustafazeya** [comment]
Thanks @pjungermann . It works now !!
Just one question, these catalog users from MS graph disappear every now and then and sometimes when I click on some user it gives `entities not found` error . It would be really nice if you may suggest some way to stabilize the content(users) of the catalog

**Comment by benjdlambert** [comment]
@mustafazeya they should be stable, are you using Postgres or SQLite?

**Comment by mustafazeya** [comment]
> @mustafazeya they should be stable, are you using Postgres or SQLite?

We haven't still moved to postgres but have plans to migrate DB to Postgres. Could that be an issue?? Our organization AD has around 20K users and 1K Groups.

**Comment by benjdlambert** [comment]
Do you run multiple replicas of backstage? could be that one of them is not populated because of rate limits or whatever and then the loadbalancer will round robin to the bad one? Using a persistent store like postgres should hopefully remedy some of these concerns or issues if it's what you're seeing.

**Comment by mustafazeya** [comment]
> Do you run multiple replicas of backstage? could be that one of them is not populated because of rate limits or whatever and then the loadbalancer will round robin to the bad one? Using a persistent store like postgres should hopefully remedy some of these concerns or issues if it's what you're seeing.

The key was to use postgres DB. After using a dedicated Postgresql, everything works fine.

**Comment by rscunha** [comment]
Hello guys,

I have a curious situation here, perhaps one of you can help me to understand this better.
After configuring the MicrosoftGraphOrg provider correctly: 
<img width="484" alt="image" src="https://github.com/backstage/backstage/assets/2797794/9f2565a7-dce0-4a4e-b555-34365e551c72">

<img width="536" alt="image" src="https://github.com/backstage/backstage/assets/2797794/7d3f4f1f-dfc9-4493-aec1-b23f45a94d82">


I still cannot view the task running in the Backstage logs, the only one I have seen is this one:

<img width="1609" alt="image" src="https://github.com/backstage/backstage/assets/2797794/ef880259-151b-4e9d-9d75-04a5a9e0028b">

and looking for this behavior in docs I figured out this:

<img width="835" alt="image" src="https://github.com/backstage/backstage/assets/2797794/d8abcbfb-7a18-4351-8b45-65325fb401dc">

For me, checking out my config it is impossible to see something wrong.

After a few days of learning about the source code, I figured out the backstage_plugin_catalog db and the table backstage_backend_tasks__tasks, and I realized that when I add or update the MicrosoftGraphOrg provider the column  next_run_start_at is not updated, and in this column, the registered value is something like few days from today... and because this the query won't find it. (I don't know why this value was registered wrong, but it was, indeed)

<img width="1207" alt="image" src="https://github.com/backstage/backstage/assets/2797794/c6a2eebf-820d-48e4-a533-fd811ac8d577">
 
The funny thing here is that the value for AzureDevOpsEntityProvider is always updated, even if the query fired by Knox uses only the setting_json, as a parameter, in case of conflict, as you may view below:

<img width="545" alt="image" src="https://github.com/backstage/backstage/assets/2797794/792354d4-879b-4c55-8320-508d457905b0">

After this journey, I would like to know if any of you have also gone through this situation.

For me, the only solution for a while is to force an update in this table.

What do you think?

Regards,
