### ISSUE TITLE
[RFC][catalog-backend] Refresh entities based on some pre stored key.

### ISSUE THREAD

**Issue by kissmikijr** [backstage/backstage#12155]
**Status:** Open for comments

## Need

Need a way to be able to trigger refreshes on individual entities. This need came up during a potential implementation of github webhook support. The github webhook API provides the file pathes in the push payload. 
So to be able to trigger a refresh for an entity that got provided by a catalog-info file we need to store some data to trigger the refresh.

## Proposal

Introduce a way to be able to store values and associate these values to entities then be able to trigger a refresh with these keys on all of the entities that a given key belongs to.

Create a new table called `refresh_keys`. with the following schema.
| refresh_keys| |
|--------|-------|
| id   | text |
| entity_ref   | text |
|key | text  |

Extend the `CatalogProcessorResult` with a new type:

```ts
/** @public */
export type CatalogProcessorRefreshKeysResult = {
  type: 'refresh';
  entityRef: String;
  key: String;
};

```
This gives the ability to emit `CatalogProcessorRefreshKeysResult` type from the processors, and the result should be stored in the `refresh_keys` table.

In the `DefaultCatalogProcessingEngine` we can store this new data that gets emitted from the processor chain.

The DefaultProcessingDatabase will need to be updated with two new methods to be able to store the data to its own table and one to get back the entityRef based on the key it gets as an argument.
```ts
setRefreshKeys(key: string, entityRef: string):  Promise<void> {
  // insert into the refresh_keys table
}

refreshByRefreshKey(key: string):  Promise<void> {
  // fetch from the refresh_keys table by key and trigger a database.refresh with the returned entityRefs.
}
```

For the refreshes there will be needed a new method on the `DefaultRefreshService` that can trigger refreshes based on the provided keys.

Update the existing processors to store the filepath/whole URL of the file that will create them.
- UrlReaderProcessor
- FileReaderProcessor
- PlaceholderProcessor

Update the PlaceholderProcessor to store the placeholder values to be able to trigger refreshes when the placeholder value changes.
```ts
emit(processingResult.refresh(
  entity: parseResult.entity,
  key: item.url
));
```

## Alternatives
An option would be to trigger refreshes based on the managed-by-location annotation instead of storing some key values to trigger these. However this wouldn't solve the PlaceholderProcessor issues to be able to trigger refreshes when a placeholder value changes.

## Risks

The processing loop would do an upsert for all of the keys that are returned during the processing. The `refresh_keys` table would be called at least 1 time for every entity when it processes.

In cases when a key gets tied to a lot of entities (for example when there is a root catalog-info.yaml file which contains a LOT of entities inside it) on refreshes triggered by this key could put a lot of stuff into the front of the processing queue.

### Appendix
Here is a PRFC for this https://github.com/backstage/backstage/pull/12156

**Comment by kissmikijr** [comment]
> I'm assuming entities can be associated with multiple "refresh keys" (or at least it looks like this implementation inherently supports it). For example, do we envision a scenario where entity FOO can be refreshed via a GitHub webhook via a repo URL key OR some other event that's associated with a key attached by another processor?

Exactly this! One usecase will be API entities. The UrlReader/FileReaderProcerros will add the file name to the "refresh keys" and the PlaceHolderProcessor will add the value of the placeholder in the definition:
// github.com/org/repo/api.yaml
```yaml
...
spec:
  definition:
    $text: https://github.com/my-repo/openapi.json
```
In this case the refresh keys array would contain two entries: 
```ts
const refreshKeys = [
  {entity: Entity, key: 'https://github.com/my-repo/openapi.json'}, 
  {entity: Entity, key: 'https://github.com/org/repo/blob/main/api.yaml' }
]
```
This would make it possible to be able to trigger a refresh on this API entity when the 'https://github.com/my-repo/openapi.json' file is changed! Which is pretty cool! :D 

> Should we also support a deleteRefreshKeys(entityRef: string, key?: string) // delete all or specific key for a entityRef so things can be cleaned up on entity deletion/unregistration? and also potentially a delete & add workflow to modify existing keys?

Nice thanks, you are correct, I totally forgot about the deletion cases! I'll update it.

**Comment by pjungermann** [comment]
I think API entities / placeholders can be tricky. E.g., the referenced OAS file doesn't need to be within the or any repository. You can also reference a file hosted somewhere else which is accessible to Backstage.
But sure, if any reference ends up as a "refresh key" and these systems allow to react on changes, too.. If not, it will stay stale until something else triggers the refresh.

**Comment by kissmikijr** [comment]
Yes, I agree. With the webhooks probably you'll have some kind of mechanism to trigger a regular refresh on your entities in a set intervals to make sure everything is synced and you didn't miss any events, this should make sure your API definition will be synced. Otherwise you should manually refresh.
