### ISSUE TITLE
Allow SOAP APIs to be viewed in the backstage

### ISSUE THREAD

**Issue by VladMasarik** [backstage/backstage#12175]
## Feature Suggestion
Allow SOAP WSDL files to be read, parsed and displayed in backstage the same way other API definitions are.

## Possible Implementation
I have been told that there should be some SOAP parser / reader library that processes the WSDL file, and then we can just display the data by passing it into the correct backstage places. I have no idea how true this is yet, as I have to do the research, but this would be the naive implementation.

## Context
Do you have any plans to support WSDL files in the future? If not, is this something you would welcome, and if there is no dedicated person to creating this, I would be able to implement it.

I saw a few discussions on discord where people wanted to used the WSDL files, but the offered solution from my understanding was just to read the WSDL file, and show it in the backstage as a text file, but I think showing it as a backstage API would be better.

I have been told that our company, and assuming loads of other companies have still rather old APIs that use SOAP. If backstage is supposed to catalog APIs, then supporting WSDL files, which already contain some useful data, should be easier than rewriting the APIs into a supported format.

What are your thoughts?

**Comment by freben** [comment]
> Do you have any plans to support WSDL files in the future? If not, is this something you would welcome, and if there is no dedicated person to creating this, I would be able to implement it.

We'd be very happy for a contribution towards this!

> I saw a few discussions on discord where people wanted to used the WSDL files, but the offered solution from my understanding was just to read the WSDL file, and show it in the backstage as a text file, but I think showing it as a backstage API would be better.

Without seeing the actual discussion, it sounds to me like this refers to using the API kind as you say, but adding no special treatment code in the frontend for it, which will result in it being shown using the fallback display: plain text. So today, out of the box, you should be able to make `kind: API` entities, maybe with `spec.type: wsdl` or so, and they will appear in the Backstage catalog just fine and its contract will be displayed verbatim without any frills.

> I have been told that our company, and assuming loads of other companies have still rather old APIs that use SOAP. If backstage is supposed to catalog APIs, then supporting WSDL files, which already contain some useful data, should be easier than rewriting the APIs into a supported format.

Sure! Let me offer some brief guidance.

- The [`api-docs` plugin](https://github.com/backstage/backstage/tree/master/plugins/api-docs) is the one that holds all of the logic and components for how stuff is displayed for API entities in the catalog.
- It relies on [a utility api](https://github.com/backstage/backstage/blob/0b66483ca070d9baaf00ad01e9b89435f04c562b/plugins/api-docs/src/config.ts#L21), whose reference `apiDocsConfigRef` is exported by that package. It has a default implementation which you [can see here](https://github.com/backstage/backstage/blob/0b66483ca070d9baaf00ad01e9b89435f04c562b/plugins/api-docs/src/plugin.ts#L34).
- Without modifying the core Backstage, you yourself can offer up a custom implementation of that API, returning not just [the default widgets](https://github.com/backstage/backstage/blob/0b66483ca070d9baaf00ad01e9b89435f04c562b/plugins/api-docs/src/components/ApiDefinitionCard/ApiDefinitionWidget.tsx#L29) but also additional ones.

But ultimately, once you have something functioning, we'd love to have that default set of widgets amended with your nice representational component!

**Comment by VladMasarik** [comment]
@freben Thank you a lot for the initial guide! I started working on the implementation. The initial idea was to reuse some kind of a SOAP / WSDL viewer library to create JS/Typescript components, but so far I have not found any relevant project. Therefore, my current steps would be to parse the XML myself, and build the components as well. Do you know by any chance of a better solution that I am missing?

So far the most relevant things I found was this https://github.com/tomi-vanek/wsdl-viewer , but I am not sure how to implement the XSLT language into TS. Most of the libraries are using WSDL files to build clients, but I am not sure if this can be used in our case, although I did manage to find this project https://github.com/TimLuq/wsdl-to-ts . The rest of the libraries are mostly in PHP so I am not sure that is possible either.

**Comment by freben** [comment]
Sorry I don't know of any helpers offhand! A quick googling supports your thesis. Maybe we'll be writing our own React based renderer then. Maybe you can copy some of the basic structure out of the rendered output of the Tomi Vanek solution to get bootstrapped, and put some styling on it.

**Comment by dweber019** [comment]
@VladMasarik we have the same challenge. Currently we use the Kind: API to show the WSDL definition but in plain text only and use a link to the legacy documentation, which in a CMS and hand written 😉 

I'm working on a solution as well but have the same trouble. The prove of concept I'm doing now is to convert the WSDL into a OpenApi spec and display it with the Swagger UI but not there jet.

**Comment by AlfadilTabar** [comment]
hi @dweber019 great to hear that you are working on this feature, can you share the updates on it if you have time.

**Comment by dweber019** [comment]
Tested several approaches but most of them I have canceled, because of they had licenceing issues or lack of maintenance support, like using https://www.npmjs.com/package/apiconnect-wsdl or a library based on it. An other approach was to convert a WSDL to any other format like postman and then convert to OpenAPI, this worked but a lot of important features, like the doc tag were missing.

I now started an other try with https://github.com/tomi-vanek/wsdl-viewer

**Comment by dweber019** [comment]
Created a plugin for viewing WSDL web services based on tomi-vanek at https://github.com/dweber019/backstage-plugin-api-docs-module-ws

Feedback and PR's welcome. It's not perfect yet 😉

**Comment by efenner-cambia** [comment]
@dweber019 I get a 404 at that link. Is the repo private?
