### ISSUE TITLE
Cannot use with node 18

### ISSUE THREAD

**Issue by fabiancook** [backstage/backstage#12216]
## Expected Behavior

Running `npx @backstage/create-app` with `node --version` of 18 or above 

## Actual Behavior

```bash
 Building the app:
  executing     yarn install ◠ error root@1.0.0: The engine "node" is incompatible with this module. Expected version "14 || 16". Got "18.3.0"
error Found incompatible module.
```

## Steps to Reproduce

1. [Install node current, 18.4.0](https://nodejs.org/en/)
2. Run `npx @backstage/create-app` 

## Your Environment

```bash
$ node --version
18.3.0
```

## Relevant 

I see the engine was last modified as per https://github.com/backstage/backstage/pull/6889, version 12 was in maintenance, 14 was LTS, and 16 was soon to be LTS (was August then, and LTS in October)

https://nodejs.org/en/about/releases/

As of today, version 14 is in maintenance, node 16 is current LTS, and node 18 will be LTS in October 

This might be more of a feature request than a bug, but, users will need to download current LTS to use, which will be no longer a presented option come October

**Comment by jhaals** [comment]
Hi! You're right that it's not supported, yet! :) We plan to switch over to node 18 in a month or two.
Some clarification have just been added in https://github.com/backstage/backstage/pull/12217
We have node 18 on our radar so I'm going to close this issue for now. Feel free to reopen if anything is unclear!
