### ISSUE TITLE
Backstage installation on mac cpu-features node-gyp

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#12221]
Try to install backstage on Mac with npx @backstage/create-app.

Bug:

Error: Could not execute command yarn install

It seems that something went wrong when creating the app 🤔

🔥 Failed to create app!

![image](https://user-images.githubusercontent.com/225961/175045282-1368fdf7-6248-40dd-92eb-15a223592639.png)
![image](https://user-images.githubusercontent.com/225961/175045374-e3f936e0-7fc2-493a-8fbf-20582691296d.png)
![image](https://user-images.githubusercontent.com/225961/175045430-db9d911e-36dd-4e68-82f3-70e2f909baff.png)

## Expected Behavior

Create backstage Application successfully

## Actual Behavior

Error: Could not execute command yarn install

## Steps to Reproduce

In terminal
npx @backstage/create-app

## Your Environment

Node Version: v16.13.0
Yarn Version: 1.22.17
NPM Version: 8.1.4
OS: MacBook Pro (13-inch, M1, 2020)

**Comment by jhaals** [comment]
Hi, sorry to hear that you experiencing problems, I was not able to reproduce this locally.
Which version do you get by running ` npx @backstage/create-app --version`? 
Looks like it fails building the sqlite dependency, is `python` in your patch is you run `which python`?

**Comment by lalit774** [comment]
lalitkumar@Lalits-MacBook-Pro code % npx @backstage/create-app --version
1.3.0
lalitkumar@Lalits-MacBook-Pro code % which python
python: aliased to python3
lalitkumar@Lalits-MacBook-Pro code % which python3
/opt/homebrew/bin/python3
lalitkumar@Lalits-MacBook-Pro code % python3 --version
Python 3.9.8
lalitkumar@Lalits-MacBook-Pro code %

**Comment by Rugvip** [comment]
See #12056 for the fix that will be part of the next release, but you can apply that manually already. Or you could `npx @backstage/create-app@0.4.29-next.0`
