### ISSUE TITLE
Unable to use custom "authentication server" with Okta authentication

### ISSUE THREAD

**Issue by DavidZemon** [backstage/backstage#12248]
## Expected Behavior

I should be able define a custom authentication server via a property such as `auth.providers.okta.<ENV>.authServer` property in `app-config.yaml`. This authentication server should then be used when communicating with Okta.

## Actual Behavior

There is no way to provide a custom auth server.

## Steps to Reproduce

1. Create an application in Okta that uses a non-default authentication server
2. Add a custom scope to the auth server, such as `employee_number`, which will set a property `employeeNumber` on the token returned from Okta to Backstage
3. Note that the new property is not included in the token that backstage receives.

## Context

We have to jump through some absurd hoops to get the employee number for the currently logged in user which will fall apart when we switch from BitBucket to GitHub. Our OAuth solution should be able to provide custom scopes, but the auth server is not handled correctly and we therefore cannot communicate correctly with Okta. Interestingly, we can still log in and get basic profile info, but can not get scopes.

## Your Environment

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.5.0 - darwin/x64
node: v14.19.3
yarn: 1.22.19
cli:  0.17.2 (installed)

Dependencies:
  @backstage/app-defaults                            1.0.3
  @backstage/backend-common                          0.14.0
  @backstage/backend-tasks                           0.3.2
  @backstage/catalog-client                          1.0.3
  @backstage/catalog-model                           1.0.3
  @backstage/cli-common                              0.1.9
  @backstage/cli                                     0.17.2
  @backstage/config-loader                           1.1.2
  @backstage/config                                  1.0.1
  @backstage/core-app-api                            1.0.3
  @backstage/core-components                         0.9.5
  @backstage/core-plugin-api                         1.0.3
  @backstage/dev-utils                               1.0.3
  @backstage/errors                                  1.0.0
  @backstage/integration-react                       1.1.1
  @backstage/integration                             1.2.1
  @backstage/plugin-api-docs                         0.8.6
  @backstage/plugin-app-backend                      0.3.33
  @backstage/plugin-auth-backend                     0.14.1
  @backstage/plugin-auth-node                        0.2.2
  @backstage/plugin-bitbucket-cloud-common           0.1.0
  @backstage/plugin-catalog-backend-module-bitbucket 0.2.0
  @backstage/plugin-catalog-backend                  1.2.0
  @backstage/plugin-catalog-common                   1.0.3
  @backstage/plugin-catalog-graph                    0.2.18
  @backstage/plugin-catalog-import                   0.8.9
  @backstage/plugin-catalog-react                    1.1.1
  @backstage/plugin-catalog                          1.3.0
  @backstage/plugin-github-actions                   0.5.6
  @backstage/plugin-home                             0.4.22
  @backstage/plugin-jenkins-backend                  0.1.23
  @backstage/plugin-jenkins-common                   0.1.5
  @backstage/plugin-jenkins                          0.7.5
  @backstage/plugin-org                              0.5.6
  @backstage/plugin-permission-common                0.6.2
  @backstage/plugin-permission-node                  0.6.2
  @backstage/plugin-permission-react                 0.4.2
  @backstage/plugin-proxy-backend                    0.2.27
  @backstage/plugin-scaffolder-backend               1.3.0
  @backstage/plugin-scaffolder-common                1.1.1
  @backstage/plugin-scaffolder                       1.3.0
  @backstage/plugin-search-backend-module-pg         0.3.4
  @backstage/plugin-search-backend-node              0.6.2
  @backstage/plugin-search-backend                   0.5.3
  @backstage/plugin-search-common                    0.3.5
  @backstage/plugin-search-react                     0.2.1
  @backstage/plugin-search                           0.9.0
  @backstage/plugin-stack-overflow                   0.1.2
  @backstage/plugin-tech-radar                       0.5.13
  @backstage/plugin-techdocs-backend                 1.1.2
  @backstage/plugin-techdocs-module-addons-contrib   1.0.1
  @backstage/plugin-techdocs-node                    1.1.2
  @backstage/plugin-techdocs-react                   1.0.1
  @backstage/plugin-techdocs                         1.2.0
  @backstage/plugin-user-settings                    0.4.5
  @backstage/release-manifests                       0.0.4
  @backstage/test-utils                              1.1.1
  @backstage/theme                                   0.2.15
  @backstage/types                                   1.0.0
  @backstage/version-bridge                          1.0.1
```

## Proposed fix

This seems to come down to two separate problems, the primary one with Okta strategy from passport-okta-oauth and one with Backstage. The main issue is that the strategy does not recognize custom auth server IDs as an option:

```js
option.authorizationURL = option.audience + "/oauth2/v1/authorize";
option.tokenURL = option.audience + "/oauth2/v1/token";
option.userInfoUrl = option.audience + "/oauth2/v1/userinfo";
```

This directly conflicts with the Okta documentation:

> **2. Okta as the identity platform for your app or API**
> This is for use cases where Okta is the authorization server for your resource server (for example, you want Okta to act as the user store for your application, but Okta is invisible to your users). This kind of authorization server we call a "Custom Authorization Server", and your base URL looks like this:
>
> `https://${yourOktaDomain}/oauth2/${authorizationServerId}`
>
> The full URL to the /authorize endpoint looks like this:
>
> `https://${yourOktaDomain}/oauth2/${authorizationServerId}/v1/authorize`

The second problem, of course, is the fact that Backstage doesn't give us any way to provide a custom auth server via `app-config.yaml`.
While debugging this issue, I originally thought `idp` was the name for this parameter and, in that train of thought, I figured out that IDP is also not passed from Backstage to passport. We don't need IDP, but passport _does_ properly support that parameter so it would probably make sense to add that as part of this ticket.

So what to do about this bug in passport-okta-oauth, which hasn't been touched in six years? There are a lot of forks, some of them actually have changes applied to them, but none contain a fix for the auth server. So the question in my head is: should Spotify create a fork and own the fix, should I (using my personal github account) create the fork, or should we pick one of the existing forks (none of which have any significant changes, but a few have more than none) and hope that they respond in a timely fashion? Given that this fork is going to be a direct dependency of Backstage, it probably would make sense for Spotify to own that fork and copy any relevant enhancements/fixes from other forks. Perhaps with the weight of a large company like Spotify behind it, passport might update their website to reference your fork instead of that outdated one instead.

**Comment by DavidZemon** [comment]
Btw, I changed my local copy of `oauth2.js` in `node_modules/` to contain these three lines as part of testing. I don't have passport-okta-oauth cloned locally, so can't provide a patch file for it in the same way I did for backstage

```js
option.authorizationURL = option.audience + `/oauth2/${option.idp}/v1/authorize`;
option.tokenURL = option.audience + `/oauth2/${option.idp}/v1/token`;
option.userInfoUrl = option.audience + `/oauth2/${option.idp}/v1/userinfo`;
```

**Comment by freben** [comment]
Sorry for a possibly unrelated and silly question - was `userInfoUrl` an unintentional typo only in the examples above? It should be `userInfoURL` I think.

**Comment by DavidZemon** [comment]
> Sorry for a possibly unrelated and silly question - was `userInfoUrl` an unintentional typo only in the examples above? It should be `userInfoURL` I think.

Oddly enough, no, not a typo: https://github.com/fischerdan/passport-okta-oauth/blob/master/lib/passport-okta-oauth/oauth2.js#L14
