### ISSUE TITLE
Preparing backstage for production deployment

### ISSUE THREAD

**Issue by cpgonz2** [backstage/backstage#12242]
Hi, I am not really an expert on deploying apps into an ecs fargate and all the stuff but I managed to get the backstage standalone app running and exposed into an ALB. To get this I needed to configure the baseurl of the app-config.production.yaml as my url domain defined by route53.

The main question is how to configure properly the backstage app in a "production" way so plugins can live in backend (for example auth providers)... and expose the service through the alb.

Thanks!

**Comment by awanlin** [comment]
@cpgonz2 we have a similar setup only we don't use Route53 as the domain we wanted to use lives somewhere else. To get us going we used Roadie's guide here: https://roadie.io/blog/backstage-fargate-up-and-running/

For our deployments to Dev, Stage, and Production our `app.baseUrl` and our `backend.baseUrl` are both `https://backstage.exmample.com`. This all goes through a Terraformed ABL in AWS. We use a single container as we haven't needed anything more complex yet. We use Azure AD auth and several other backend plugins like this without any issues.

I hope this is what you are looking for?

**Comment by cpgonz2** [comment]
Okey! Nice thank you so much.

@awanlin Just another question related to the auth backend plugins, the handler for example for github when login in must be in the backstage/plugins/auth-backend as the backstage github project, right? Because as I could see on the backstage webpage there is a TO-DO on that section [https://backstage.io/docs/auth/auth-backend](url), and there isn't much documentation about this step on Google.

Thanks again!

**Comment by awanlin** [comment]
Hi @cpgonz2, all your auth setup would go into `/packages/backend/src/plugins/auth.ts`. If you read through the documentation from here it will explain how to get that setup: https://backstage.io/docs/auth/

@benjdlambert, sorry to tag you directly but I'm just wondering what the intention of this page is/was? Maybe it's not needed? https://github.com/backstage/backstage/issues/url

**Comment by awanlin** [comment]
Ugh, sorry, I meant this one: https://backstage.io/docs/auth/auth-backend. Trying to do too many things at once!

**Comment by benjdlambert** [comment]
Hmm yep, to be honest I'm not really sure what we would put in that doc section apart from installation notes or something to setup a backstage instace that doesn't already have that plugin installed? @rugvip thoughts?
