### ISSUE TITLE
Catalog REST API for fetching multiple entities with one request

### ISSUE THREAD

**Issue by taras** [backstage/backstage#12254]
## Context

When using Catalog REST Api with the a Dataloader, we need to be able to make a single request for all of the entities that need to be fetched. 

## Feature Suggestion

Currently, we have to make a separate calls using `getEntityByRef` which requires a lot of calls to the catalog. Ideally, we'd be able to make a single request with a list of refs to retrieve all of the entities in one shot.

## Possible Implementation

We could add `refs?: string[]` parameter to `CatalogEntitiesRequest` which would allow us to use `fields` to control what fields are returned - pagination probably wouldn't make sense here. Alternatively, we could create `getEntitiesByRef` which would only take list of refs.

**Comment by freben** [comment]
There's effectively an OR between entries in the filter array. So while a bit awkward, you can filter by `[{ kind:... }, { kind:... }]` and split the result array after.

If we put the ref in the search table, which might be a good idea anyway, we could also do `[{ _ref: [a, b, c] }]`.

A custom endpoint for refs would probably be a bit faster and more convenient.

**Comment by vinzscam** [comment]
you can do this in one shot using `getEntities` and filtering by name:

```javascript
function fetchByRefs(refs: string[]) {
    const { items } = await catalogApi.getEntities({
        filter: {
            'metadata.name': refs.map(r => parseEntityRef(r).name),
        },
    });
    return items.filter(i => refs.includes(stringifyEntityRef(i)));
}
```

**Comment by taras** [comment]
@vinzscam that will load all of the records into memory which is undesirable.

**Comment by vinzscam** [comment]
> @vinzscam that will load all of the records into memory which is undesirable.

then wait for #12246

**Comment by taras** [comment]
Yeah, I don't really need what #12246 brings. It'd be much simpler to do what @freben suggested, just have an endpoint that takes a list of refs and returns those entities.

**Comment by vinzscam** [comment]
> Yeah, I don't really need what #12246 brings. It'd be much simpler to do what @freben suggested, just have an endpoint that takes a list of refs and returns those entities.

This looks like you already have a 48 pcs screwdriver set but you want to buy an extra specific screwdriver because you don’t need the other 47 pieces. 😅
I don’t think adding more endpoints with overlapping features between them is a smart move, since this would mean more code and more work for the core maintainers.
A smarter approach would be to add a new method for fetching entities by refs to the CatalogClient, reusing one of the endpoints.
Your specific case it’s a perfect suit for the new `/entities` endpoint, since you can get the feature for free (especially if you add the refs to the search table) at no extra cost (since the performance cost for the other features will be teared down by filtering the elements by refs).

**Comment by taras** [comment]
Using entities endpoint for this use case is undesirable for several reasons,

1. dataloader requires passing many refs. The number of refs many exceed URL length limit, for this reason it's preferable to pass the list of refs via body rather than URL. Since `entities` endpoint is a GET request which doesn't allow using body for params.
2. all of the filtering/sorting functionality is not only unnecessary, but also opposite of what dataloader needs. The entities returned by the response must match the order of refs in the request with error/null in place of unresolved entities
3. it will be easier to write and maintain a performant endpoint for this purpose without confusing it with unrelated functionality

To use your metaphor, using entities endpoint here would be to use use screws because you have 48 bit screwdriver set instead of a nail.

**Comment by vinzscam** [comment]
Yeah I can agree with the first point,  but if we have the string url problem in the new hypothetical endpoint, it means we should revisit this solution also for the other endpoints, since there the problem is going to be bigger (I don’t know if anyone found similar issues).

Point 2: you don’t have to deal with any filter if you don’t need it. The order of the response can be handled in CatalogClient.

Point 3: it is going to be more work to maintain, since you have an extra endpoint.
The performance of a brand new endpoint compared to the new `/entities` endpoint in your use case is going to be the same.

**Comment by taras** [comment]
> if we have the query string url length problem in the new hypothetical endpoint, it means we should revisit this solution also for the other endpoints

The existing endpoints might not suffer from url length limitation problem. It could but it hasn't been reported yet. It might never happen. For the data loader use case, this problem can be expected because resolving relationships can produce many references. For example, if you have a system with many components and you want to fetch all of the relationships, you will have many refs to retrieve.

> Point 3: it is going to be more work to maintain, since you have an extra endpoint.

Everything has a cost, but maintaining one endpoint that satisfies specific use case in addition to other unrelate use cases introduces unnecessary cognitive overhead. 

> The performance of a brand new endpoint compared to the new /entities endpoint in your use case is going to be the same.

I'm not sure if this is the case. `/entities` endpoint performs a matching query, where for this batch endpoint we can just do a bunch of selects in one query. We would need to verify this assertion, but we'd first have to implement both to compare.

BTW, this is a very specific use case to enable more performant fetching in a [GraphQL plugin that we're developing](https://github.com/thefrontside/backstage/pull/9). We're already using entities endpoint, but we just want to make it faster and simpler.

**Comment by freben** [comment]
> @vinzscam that will load all of the records into memory which is undesirable.

Not really, his example was basically like mine but only used `name` instead of specifying the entire kind+namespace+name triplet so it only needed to post-filter out the (probably minuscule number of) spurious extra potential matches. You could make the matcher exact upfront by doing 

```ts
function fetchByRefs(refs: string[]) {
  const filter = refs.map(refString => {
    const { kind, namespace, name } = parseEntityRef(refString);
    return {
      kind: kind,
      'metadata.namespace': namespace,
      'metadata.name': name,
    };
  };
  const response = await catalogApi.getEntities({ filter });
  return response.items;
}
```

**Comment by taras** [comment]
@freben @vinzscam I was reading that code example on my phone. I misread it. I thought it was querying all of the records and then filtering them in memory. I've give that a try to see if it'll work with the dataloader.

**Comment by Blackbaud-LeoWanderer** [comment]
hi @taras, out of curiosity, is the plugin you're developing planned to be merged to this repo as a contribution or will it be an external plugin? if it will be a contribution to this repo, is there a channel/thread/discussion to talk and contribute to it? and do you have a tentative date for getting it merged? 

I looked at the code and run some experiments with some graphql queries, and your implementation suits many of my requirements. There's a few things I considered adding like being able to query custom properties from the spec and custom relationships with a name parameter, and the ability to extend the schema / add more modules. Are you planning any of those too? Can I offer any help?

**Comment by taras** [comment]
@freben @vinzscam, @cowboyd reminded me that we did try using `catalogApi.getEntities` for DataLoader. It was slower than making an HTTP request for each entity using `getEntityByName`. This is the reason why we didn't end up using it. It was almost a year ago so I forgot.

@Blackbaud-LeoWanderer your timing is impeccable. We finally released the GraphQL Plugin for Backstage earlier this week. The source code is open source in [`thefrontside/backstage`](https://github.com/thefrontside/backstage/tree/main/plugins/graphql) monorepo. We publish from there because we have integration testing. I'm working on documentation right now. You can [track the docs that I'm working on](https://github.com/thefrontside/backstage/issues/66).

* query custom properties from the spec and custom relationships with a name parameter - our graphql plugin supports this. You don't even need to write JavaScript to do it. You can see an example of how we do [it in the schema](https://github.com/thefrontside/backstage/blob/main/plugins/graphql/src/app/modules/catalog/catalog.graphql#L92).
* ability to extend the schema / add more modules - our plugin uses graphql-modules so this functionality will be available out of the box.

> Can I offer any help?

We'd love help. There is lots of schema that can be exposed on case by case basis. We also have a few features that we need to implement. You can see the issues with [`graphql-plugin` label](https://github.com/thefrontside/backstage/issues?q=is%3Aissue+is%3Aopen+label%3Agraphql-plugin). 

> is there a channel/thread/discussion to talk and contribute to it?

In discord, there is a GraphQL channel and we can continue the conversation there. 

---

For those interested in batch loader, we just created a [PR with initial version](https://github.com/thefrontside/backstage/pull/70). It only supports Postgres at the moment. Additional backends can be added if desired.

**Comment by freben** [comment]
I bet there's a breaking point where the batch fetch is faster than individual items. It'll surely depend on the available concurrency etc too

**Comment by taras** [comment]
👋 I mentioned during today's Catalog Sig meeting, we created a Batch Loader plugin for Backstage. It doesn't currently have a REST API, it talks directly to the catalog. It only tested on Postgres https://github.com/thefrontside/backstage/tree/main/plugins/batch-loader. In our performance tests, we found that fetching 1000 nodes with GraphQL went from 4200ms to 160ms.

**Comment by freben** [comment]
@taras Oh you really shouldn't have the `entity_to_ref` there. You should start from `processing_state` which does have the ref already, and join that with `final_entities`.

**Comment by taras** [comment]
@freben when you say `start from processing_state`, are do you mean `refresh_state`? We'll try this approach and report back.

**Comment by freben** [comment]
Yeah sorry - wrong table name!

**Comment by wKich** [comment]
@freben It works, thank you

**Comment by taras** [comment]
It takes about 190ms to fetch 1000 nodes instead of 160ms but 20% difference is a good compromise for the simplicity it provides.

**Comment by freben** [comment]
This was addressed in https://github.com/backstage/backstage/pull/14354
