### ISSUE TITLE
Be able to manage multiple versions of the same techdocs

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#12259]
## Feature Suggestion

We'd like to add to the **techdocs** feature the possibility to manage multiple versions of the documentation. This would allow companies to deal with mutliple versions of their components without worrying about « loosing » the documentation of the version they use.

## Possible Implementation

I think there is (at least) two features to think of : 
- On the documentation holder (Azure Blob storage, Amazon S3, etc.), the directory `<storageUrl>/<entity kind>/<entity namespace>/<entity name>` contains the latest documentation. This is mostly for backward compatibility. 
- Add a  (optionnal ?) tag to define the version pattern that the project use (of course, this would be a regex). Based on this tag, every directories directly under `<storageUrl>/<entity kind>/<entity namespace>/<entity name>` and that follow the pattern contain the documentation for the the version specified. For examples : 
  - If the tag for the version pattern is `\d+.\d+.\d+` then : 
    - `<storageUrl>/<entity kind>/<entity namespace>/<entity name>/1.0.0` contains the techdocs for version **1.0.0** and should be rendered by the plugin
    - `<storageUrl>/<entity kind>/<entity namespace>/<entity name>/2.3.4` contains the techdocs for version **2.3.4** and should be rendered by the plugin
    - `<storageUrl>/<entity kind>/<entity namespace>/<entity name>/1.0.0.0` **may** contain the techdocs for version **1.0.0.0** but should be ignored by the plugin
  - If the tag for the version pattern is `\d+.\d+.\d+.\d+` then : 
    - `<storageUrl>/<entity kind>/<entity namespace>/<entity name>/1.0.0` **may** contain the techdocs for version **1.0.0** but should be ignored by the plugin
    - `<storageUrl>/<entity kind>/<entity namespace>/<entity name>/2.3.4` **may** contain the techdocs for version **2.3.4** but should be ignored by the plugin
    - `<storageUrl>/<entity kind>/<entity namespace>/<entity name>/1.0.0.0` contains the techdocs for version **1.0.0.0** and should be rendered by the plugin

## Context

Companies have many live version for each components. These components may be used by several people. These people want to be able to look at the doc of the specific version of the component they use in backstage.

**Comment by garyniemen** [comment]
@iamEAP @freben Can you comment on this one - it has wider Backstage implications right?

**Comment by iamEAP** [comment]
Hey @LvffY,

Are you looking for something more deeply integrated with your VCS provider (e.g. one version corresponds with one branch)?  I'm wondering if there's anything in particular you find limiting about how this can be achieved today using just navigation/hierarchy, e.g.

```yaml
# mkdocs.yml

nav:
  - v1:
    - Page: v1/page.md
  - v2:
    - Page: v2/page.md
```

**Comment by awanlin** [comment]
If we did go the VCS route `mike` could be an option to look into: https://github.com/jimporter/mike. It works with MkDocs and your git repo to publish versioned documentation. Feel like there would a lot of heavy lifting to integrate though

**Comment by LvffY** [comment]
@iamEAP @awanlin TBH, I didn't think about some kind of VCS integration but it would be great.

What I thought about is to only use the filesystem where the techdocs are stored (e.g. an Azure Blob storage) and look at the directory tree.

**Comment by iamEAP** [comment]
@LvffY Ah, cool.  So in that case, I'd recommend doing something like the above example `mkdocs.yml`.  Or, if your versioned code is stored in VCS like a monorepo, e.g.

```
$ tree .

├── docs
│   ├── authentication.md
│   └── index.md
├── mkdocs.yml
├── v1
│   ├── docs
│   │   ├── changelog.md
│   │   └── reference.md
│   └── mkdocs.yml
└── v2
    ├── docs
    │   ├── changelog.md
    │   ├── migrating.md
    │   └── reference.md
    └── mkdocs.yml

5 directories, 10 files
```

...Then you could consider using the [mkdocs-monorepo](https://github.com/backstage/mkdocs-monorepo-plugin#usage) plugin to stitch it all together into one TechDocs site.

**Comment by LvffY** [comment]
I won't have time to look into this, but if you think this could fit my needs, I think you can close the case :)

Thanks for your answers :)

**Comment by iamEAP** [comment]
Don't think we're _quite_ ready to close this yet, as I think it's worth discussing a bit more (this came up in discord today, for instance).

Also, linking to https://github.com/backstage/backstage/issues/11027, which is similar-ish.

**Comment by manuelstein** [comment]
I've also put this on my roadmap and was also eyeing `mike` (@awanlin). I was thinking a custom TechDocsReaderPageContent could do the job and offer a dropdown version selector similar to how mike renders multiple versions.

Some of our projects may be using sphinx, too, so our target would be to decouple the multi-version solution from rendering (as in the [recommended deployment setup](https://backstage.io/docs/features/techdocs/architecture#recommended-deployment)).

I'd prefer not using MkDocs to manage multiple versions as this is a feature we'd require across solutions. Rendered docs could come from different branches, yes, or they could be tags on a release branch, or, in case of `mike`, the rendered sites live in one separate branch of the same repo. So, I'd like to pursue offer something similar to the subfolder proposal.

@LvffY, interesting idea with the regex. Why would TechDocs need to understand the version string? In case of sorting them, couldn't it just use a magic sort function that detects semantic version strings? Or, do you also want to use it to filter the displayed versions?

**Comment by zinizhu** [comment]
any update on managing multiple versioning docs?

What we want is something like [Terraform's documentation pages](https://registry.terraform.io/providers/hashicorp/google/4.53.0/docs). Users can select the doc for a specific version in a drop down. As @LvffY said, the docs folder becomes harder to manage as the number of versions increases. Ideally the doc is always built from the latest repo but tagged with a specific version, then pushed to a cloud storage as an immutable  artifact.

**Comment by hwinkel** [comment]
This is in completed state but we can't find how this is working now. It's really important imho that the docs can follow a version of the given software

**Comment by fotisolgr** [comment]
Any updates on this guys? I totally agree that this feature whould be essential for many products that have multiple versions of the product in different customers.

**Comment by x3ro** [comment]
We're currently taking a stab at implementing this, and were wondering if our approach is something that could potentially make its way into Backstage, in its current or a modified form. I'm going to describe our approach here, and would be interested in feedback both from the Backstage maintainers, but also from other people who are interested in this functionality.

From a high-level perspective, here's what we did:

* We introduced a new metadata annotation, which looks like this:

```yaml
metadata:
  [...]
  annotations:
    [...]
    pg.com/techdocs-versions: |
      latest: url:https://github.com/x3ro/mkdocs-test/tree/main
      v1.0: url:https://github.com/x3ro/mkdocs-test/tree/v1.0
      v2.0: url:https://github.com/x3ro/mkdocs-test/tree/v2.0
```

* We added our own implementations of the TechDocs `Preparer`, which fetches the `latest` version first, and then fetches all other versions as subdirectories of the `latest` version. In addition, we write a JSON file that contains information on all generated versions, their location and their etags.
    * Since we can't just use the `latest` etag for checking whether documentation needs to be regenerated, we combine the etags of all versions into a new etag. If this combined etag is unchanged, we know we don't need to regenerate.
* We added our own implementation of the TechDocs `Generator`, which is mostly the same as the normal `Generator`, except that it runs once for every version, again placing versions in sub-directories underneath the `latest` version.
* We implemented a version selector, which just renders the data from the metadata annotation and redirects to the correct sub-directory on selection.

Generating the versions as sub-directories has the advantage that the publisher does not need to be modified at all, since it just uploads everything underneath the `latest` version, as if it was part of that documentation. 

## Limitations

* If a directory with the same name as a version exists within the `latest` documentation, this approach does not work
* Currently no search integration
* The approach is dictated somewhat by the structure of the TechDocs plugin. We wanted to avoid having to fork the `techdocs-backend` plugin, and as a result had to work around not being able to modify `DocsBuilder`.
* Probably more that I can't think of right now 😅

**Comment by wunderdogneo** [comment]
@iamEAP can this issue be reopened?

**Comment by iamEAP** [comment]
Sure.  Just FYI, I'm less involved in the day-to-day maintenance of TechDocs related things these days, but I'll tag in @agentbellnorm & co in my steed.

**Comment by manuelstein** [comment]
@x3ro, are you developing this publicly on GH? If yes, could you share a branch location?

**Comment by x3ro** [comment]
Hey @manuelstein. I'm afraid the development is not open source, and I'm also no longer on the relevant project. I'll ping someone who's still working on that Backstage instance, and maybe they can chime in here. But I'm not sure how much time they have to spare, so I wouldn't necessarily get my hopes up 😅

**Comment by chlab** [comment]
Have there been any more efforts in this direction? It would be really great to have a versioned documentation of certain components (such as frameworks) the way @zinizhu described it.

**Comment by sureshkmit** [comment]
This would be nice indeed!
