### ISSUE TITLE
Replace deprecated react-hot-reloader in favour of react-refresh

### ISSUE THREAD

**Issue by taras** [backstage/backstage#12253]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/74687/175526223-d413dce3-a747-4286-97d1-7cb9fa0979e6.png">

`react-hot-reloader` is being replaced with `react-refresh` @gaearon explains why in https://github.com/facebook/react/issues/16604#issuecomment-528663101

## Feature Suggestion

Replace `react-hot-reloader` with `react-refresh`.

## Possible Implementation

* Webpack Plugin - [react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin/)
* We might need #10394 because [sucrase doesn't support it yet](https://github.com/alangpierce/sucrase/issues/590). 

## Context

Just trying to find all of the little things that keep up from having the best development environment.

**Comment by taras** [comment]
It looks like this was actually done in https://github.com/backstage/backstage/pull/10394

**Comment by benjdlambert** [comment]
Yep, it's dependant on the `sucrase` stuff, because we don't use `babel` at all, and I think that the `react-refresh` plugin needs it without using other transforms in the transpilers.

**Comment by benjdlambert** [comment]
Closing as completed with #10394
