### ISSUE TITLE
Upgrade to React 18

### ISSUE THREAD

**Issue by taras** [backstage/backstage#12252]
There are a few places in code where React 17 is explicitly required, like this. 

```ts
  if (reactDomVersion.startsWith('16.')) {
      resolveAliases['react-dom'] = '@hot-loader/react-dom-v16';
    } else {
      resolveAliases['react-dom'] = '@hot-loader/react-dom-v17';
    }
```

## Feature Suggestion

Be able to upgrade to React 18.

## Possible Implementation

TBD, but we could start by capturing what is breaking in React 18. 

## Context

I don't actually have a reason to do this other than "being up-to-date for being up-to-date sake", but I couldn't find an issue that explains the current situation. I found a [PR that says there are breaking changes in React 18](https://github.com/backstage/backstage/pull/10711) but it doesn't reference what they are. Also #10711 and #11461 which close PRs that attempt to upgrade dependencies.

**Comment by taras** [comment]
It looks like some of the blockers might have been removed in https://github.com/backstage/backstage/pull/10394

**Comment by benjdlambert** [comment]
Yep, most of this hopefully will go away with the sucrase stuff :pray:

**Comment by tonedef** [comment]
Thanks Taras! Actually interested in this. We have some internal tools that leverage React 18 that we need to integrate with Backstage.

**Comment by benjdlambert** [comment]
The `hot` loader dependency has been removed. Probably some other bits still need to be done in order to get this to work fully. Mainly any breaking changes with the API, and adding React 18 to the `peerDependencies` for all packages. There could be other things too.

**Comment by webark** [comment]
seems like there are a couple of places where this is getting impacted.. :(

https://github.com/backstage/backstage/issues/10701

namely (at least the ones I have come across"

```
 <TechDocsAddons>
 <ScaffolderFieldExtensions>
 <AppProvider>
 <AppRouter>
 ```

**Comment by webark** [comment]
also https://github.com/backstage/backstage/blob/9896e7c2e26b0fcb102d8cd6a79939f493dd4bf5/packages/test-utils/src/testUtils/testingLibrary.ts#L43 is using `ReactDOM.render` rather than `createRoot`

**Comment by Rugvip** [comment]
No specific plans for what release we might target for this so far.

Happy for any contributions that help chip away at this though! Be it type fixes, updates to use `createRoot` behind some kind of version check, or just digging into more requirements.

**Comment by webark** [comment]
https://github.com/backstage/backstage/blob/c90963a617945f4f51c8a681bdb019edaca3c32b/plugins/techdocs/src/reader/transformers/addGitFeedbackLink.ts#L78

https://github.com/backstage/backstage/blob/c90963a617945f4f51c8a681bdb019edaca3c32b/plugins/techdocs/src/reader/transformers/addSidebarToggle.ts#L36

Two other locations that need to be updated to the new renderer https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

**Comment by webark** [comment]
for what it's worth.. I forced react 18 for the past 2 months without issue.

**Comment by RobotSail** [comment]
Looking at this issue, would we want to force upgrade all dependencies to React 18, or should we continue the same model of checking for versions and allowing the use of 16, 17, and 18?

**Comment by freben** [comment]
We intend to generally support two versions at a time, so most likely we'd switch our peer dep on react to `^17 || ^18` across the board at that time.

**Comment by RobotSail** [comment]
@freben How would recommend that I tackle this issue? I understand that generally small commits are the best approach, but the pre-commit hooks prevent me from committing changes if there's an error somewhere in the dependency tree, requiring me to make updates to many packages at once.

**Comment by webark** [comment]
Would we want to upgrade, see what breaks, make those changes in individual/grouped PRs, then after all those are merged, can do a single PR that **_just_** bumps the react dependency. Right?

**Comment by RobotSail** [comment]
It looks like one of the big blockers preventing the React 18 upgrade is Material UI, which needs its own preparation process to be upgraded to v5. I will create an issue and PR for this.

**Comment by RobotSail** [comment]
@awanlin Yeah I've been reading the PRs for it, I see that @Rugvip has a PR for #15484 which hasn't been merged yet, and there was also #16882 which hasn't been merged yet either. I'd like to contribute my help to this process in anyway possible.

**Comment by awanlin** [comment]
@RobotSail, yeah, that's what I thought. I just know a lot of people want to see that upgrade done and there has been a lot of work done so far but clearly more to do.

You've been doing great work and as a member of the Community I appreciate it! 🚀

**Comment by freben** [comment]
Yeah I'm not sure that MUI4 has any significant problem on React 18 right? We've had reports of people running successfully on 18 already.

**Comment by awanlin** [comment]
Hi @RobotSail @Rugvip, what's the timeline for seeing support for React 18 merged in? I see that #17414 is currently a Draft and there is also #17672 that is open. Once those both get merged in is that all that is left? Are either of these blocked by anything we can help with?

We really want to be able to use some of our internal packages but they are all on React 18 and rolling them back would be a lot of work for us when this seems very close.

**Comment by awanlin** [comment]
Hi @webark, just curious but when you forced the React 18 upgrade did you do anything more than adding the resolutions?

**Comment by RobotSail** [comment]
Hi @awanlin, sorry for the delay in the React 18 upgrade. We had to pivot from something internally so it was blocked a bit on my end. The React 18 upgrade is now my top priority. I'm still not 100% sure on what else is needed, but the current way forward is going to be to open the React version window from `^16 || ^17` to be `^16 || ^17 || ^18` and then deprecate `^16`. 

#17672 should be okay to merge and will provide a way forward to upgrading to 18.
As far as timelines go, I'm not entirely sure when it will be done, but we can say it should be done by June 9th.

**Comment by awanlin** [comment]
Awesome thanks @RobotSail, also no worries, things come up for sure!
