### ISSUE TITLE
[RFC] Provide a Custom Resource Definition API 

### ISSUE THREAD

**Issue by Mercanuis** [backstage/backstage#12250]
**Status:** Open for comments

## Need

There doesn't appear to be, for a documentation tool, any documentation that pertains to the API that is being used by Backstage for its CRD(s). This would be helpful for helping to new users for adopting as several IDEs are able to read CRD definitions and use them to validate YAML files

I was unable to find anything pertaining to the definition of the CRD, on both the Backstage site nor the GitHub. It would be helpful to add this section

**Comment by benjdlambert** [comment]
Need some more information here, not sure I understand the request here? Do you mean CRD's for the `k8s-plugin` or something else?

**Comment by Mercanuis** [comment]
To try and help clarify , what I'm referring to is per an example YAML for an API  Component Definition
```yam
apiVersion: backstage.io/v1alpha1 # <---- IDE doesn't know what this is, cannot find a YAML definition to pull or reach from
kind: API
metadata:
  name: my-service
  namespace: my-namespace
  description: A Service API definition
  tags:
    - developer
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector : 'app=myapp'
spec:
  type: openapi
  owner: group:mygroup
  system: id
  lifecycle: experimental
  definition:
    $text: ./api/myapi.yml
```

**Comment by pjungermann** [comment]
at e.g. IntelliJ IDEA it works as it supports schemas and DTOs. E.g., you can use https://json.schemastore.org/catalog-info.json Schema Store is supported out of the box. The IDE attempts to do an automatic detection, but you may need to add your own mapping (e.g., to use https://json.schemastore.org/catalog-info.json for all catalog-info.yaml files).

**Comment by pjungermann** [comment]
@benjdlambert 
https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json#L572
seems like you can use the file hosted at another repo, too. E.g., backstage/backstage could make sense.

Currently, the schema file is hosted at their repo
https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/catalog-info.json

**Comment by benjdlambert** [comment]
Nice @pjungermann, think we should do that. Have the definitions alongside the code in the repo, and then we can manage them from there pretty easily and update the `schemastore` references to point at our repo instead.

**Comment by stephanschielke** [comment]
> at e.g. IntelliJ IDEA it works as it supports schemas and DTOs. E.g., you can use https://json.schemastore.org/catalog-info.json Schema Store is supported out of the box. The IDE attempts to do an automatic detection, but you may need to add your own mapping (e.g., to use https://json.schemastore.org/catalog-info.json for all catalog-info.yaml files).

I can confirm this is working with JetBrains Webstorm and DTDs configured as well.
I'm using the `schemastore` `catalog-info.json`:

![Selection_2741](https://user-images.githubusercontent.com/401815/180786501-becc9322-ff9e-4d0d-b346-4ca16f553881.png)
![Selection_2740](https://user-images.githubusercontent.com/401815/180786508-9bc4a8e3-436e-44a7-a764-e4604488f050.png)

**Comment by Mercanuis** [comment]
Thanks to everyone for the help in finding a workaround or a potential solution here

**Comment by Mercanuis** [comment]
Thanks for everyone for potential workarounds. I tried to use @stephanschielke 's suggestion but trying to use a JSON schema didn't seem to resolve the issue of Jetbrains not understanding the Backstage Resource (Component, API, etc)

**Comment by thake** [comment]
@Mercanuis, I had the same problem. I added the json schema mapping and still had error markers on my catalog-info.yaml. In my case, they were caused by the installed kubernetes plugin. It interpreted the catalog-info.yaml as a CDR and tried to validate it. This caused the inspection errors. Try to disable the kubernetes inspections for catalog-info.yaml files. This helped in my case.

**Comment by Mercanuis** [comment]
I think this issue is not as potent as I thought. I found out recently you can tell IntelliJ that Backstage resources are not K8s resources by just taggin the file `# nonk8s` at the top

**Comment by danieljamesscott** [comment]
Has anyone been able to add the schema to IntelliJ? I have added https://json.schemastore.org/catalog-info.json, but IntelliJ throws up an error

    Error processing definition entity: unrecognised reference format: https://json.schemastore.org/catalog-info.json#/definitions/common/definitions/status

It's as if the parser is unable to process the nested `$ref`?
