### ISSUE TITLE
Catalog table filter ignores title field

### ISSUE THREAD

**Issue by dweber019** [backstage/backstage#12263]
## Expected Behavior
If the title and the name of an entity is different (e.g. name=`abc` and title=`bubu`), the title is displayed in the table as name.
I can filter the table (the filter to the right of the table title) with `bu` or `bubu` and the entity named `abc` is showing up.

## Actual Behavior
If I search for `bu` oder even `bubu` the entity named `abc` is not showing as result.

## Steps to Reproduce
See above.

## Your Environment
Backstage version 1.2.2

**Comment by dweber019** [comment]
I think this code is responsible for showing the title as name if existing but doesn't consider the filter functionality.
https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/columns.tsx#L36-L39

**Comment by dweber019** [comment]
Nice thanks.
I would suggest this solution has to be moved into Backstage. Filtering by title should be possible out-of-box. The current behavior is really bad from a user experience standpoint and should be fixt, right?

**Comment by freben** [comment]
It would probably be a good thing to add to the default catalog table, sure! Would you like to contribute that?
