### ISSUE TITLE
Permission: Admin users should have access to all catalogs to view and to unregister

### ISSUE THREAD

**Issue by cinlysobin** [backstage/backstage#12278]
## Expected Behavior

The users added in the admin group should be able to view all the catalogs in backstage

## Actual Behavior

Users in the admin group don't own any catalog hence wont be able to do any task if I add the catalog permission

## Steps to Reproduce

I have an organization, say A.

There is a child group named the admin group. 

All other groups are children in this admin group.

I have added a user to the admin group. The intention is that all catalogs owned by the children should be accessible to users in the admin group.

![image](https://user-images.githubusercontent.com/47130315/176121005-59238bad-0110-4303-99d7-8bf5086c4e6b.png)

## Context

My goal is to apply catalog permission to groups. I am able to give catalog permission by using following code snippet

    if (isPermission(request.permission, catalogEntityDeletePermission)) { 
      return createCatalogConditionalDecision(
        request.permission,
        catalogConditions.isEntityOwner(
          user?.identity.ownershipEntityRefs ?? [],
        ),
      );
    }
    if (isPermission(request.permission, catalogEntityReadPermission)) { 
      return createCatalogConditionalDecision(
        request.permission,
        catalogConditions.isEntityOwner(
          user?.identity.ownershipEntityRefs ?? [],
        ),
      );
    }

But I require a set of admin users who can able to access all catalogs. unregister it regardless of ownership issue.
Is there any other option to achieve the same? Please guide me on this.

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by FilipSwiatczak** [comment]
hey @cinlysobin we have a very small and permanent group of admins so we do the following in the permission.ts:
```
const isAdmin = (user: BackstageIdentityResponse | undefined) =>
  ['admin_user_entity_name1', 'name2'].some(admin =>
    user?.identity.userEntityRef.includes(admin),
  );
class CustomPolicy implements PermissionPolicy {
  async handle(
    request: PolicyQuery,
    _user?: BackstageIdentityResponse,
  ): Promise<PolicyDecision> {
    // exempting admins from permission checks
    if (isAdmin(_user)) {
      return { result: AuthorizeResult.ALLOW };
    }
.... (rest of the permissions)
```
it's potato code and a placeholder but works for the time being!

**Comment by cinlysobin** [comment]
Thanks a lot @FilipSwiatczak . That worked..
