### ISSUE TITLE
Issue rendering techdocs inside backstage

### ISSUE THREAD

**Issue by Vegim** [backstage/backstage#12279]
## Expected Behavior

Show the techdocs rendering properly

## Actual Behavior

404 page is showing when going to some random techdocs page. After refreshing it multiple times the page comes up.
This is not happing when running in localhost the page comes up after a loading page is shown. But running it inside a docker container shows 404 page not found first and after multiple page refreshes it shows the actual page. Inside my dockerfile I'm installing mkdocs like this 

```
RUN apt-get update && \
    apt-get install -y cookiecutter \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && yes | pip3 install --no-cache-dir \
    mkdocs-techdocs-core==1.0.2 
```
## Steps to Reproduce

In the docker image running backstage instance if you go to see some documentation when the pod first started running you would see the page 404 not found 

I'm getting this error message from the endpoint https://base-url/api/techdocs/metadata/techdocs/default/component/component-name is 
```
Unable to read techdocs_metadata.json

```

**Comment by Vegim** [comment]
This issue is decreasing user experience a lot because you need to do multiple refreshes to render the technical documentation. The full json error then we are getting from that endpoint that I mentioned inside backstage techdocs backend is shown below:
```
{
    "error": {
        "name": "NotFoundError",
        "message": "Unable to get metadata for 'component:default/test-cortex-07'; caused by Error: Unable to read techdocs_metadata.json at /app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/test-cortex-07/techdocs_metadata.json. Error: Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/test-cortex-07/techdocs_metadata.json'; caused by Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/test-cortex-07/techdocs_metadata.json'",
        "cause": {
            "name": "Error",
            "cause": {
                "errno": -2,
                "code": "ENOENT",
                "syscall": "open",
                "path": "/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/test-cortex-07/techdocs_metadata.json",
                "name": "Error",
                "message": "ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/test-cortex-07/techdocs_metadata.json'",
                "stack": "Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/test-cortex-07/techdocs_metadata.json'"
            },
            "message": "Unable to read techdocs_metadata.json at /app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/test-cortex-07/techdocs_metadata.json. Error: Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/test-cortex-07/techdocs_metadata.json'; caused by Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/test-cortex-07/techdocs_metadata.json'",
            "stack": "Error: Unable to read techdocs_metadata.json at /app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/test-cortex-07/techdocs_metadata.json. Error: Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/test-cortex-07/techdocs_metadata.json'; caused by Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/test-cortex-07/techdocs_metadata.json'\n    at LocalPublish.fetchTechDocsMetadata (/app/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:1387:13)\n    at async /app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:478:32"
        }
    },
    "request": {
        "method": "GET",
        "url": "/api/techdocs/metadata/techdocs/default/component/test-cortex-07"
    },
    "response": {
        "statusCode": 404
    }
}
```

**Comment by garyniemen** [comment]
@iamEAP Do you have time to look at this?

**Comment by iamEAP** [comment]
@Vegim can you share the `techdocs` configuration you have in `app-config.yaml` (as well as any differences you might have in, say, `app-config.local.yaml`)?

**Comment by Vegim** [comment]
This is the configuration that I have in app-config.yaml. I have no other configuration defined inside app-config.local.yaml
techdocs:
  builder: 'local'
  publisher:
    type: 'local'
  generator:
    runIn: local

**Comment by Vegim** [comment]
Is there any possible solution for this issue? This issue still stands even with the new backstage version 1.3.0.

**Comment by iamEAP** [comment]
> _...happening only inside an openshift okd cluster. I couldn't reproduce this issue locally._

Oh, this is an interesting detail, @Vegim.  Do you have multiple instances of the TechDocs and/or Backstage backend running in the cluster?  e.g. across pods or something?  If so, the `local` publisher could behave in undefined and unpredictable ways.  

On a cold restart (no generated files stored), the first request (which checks if the docs exist) might be routed to `pod-a`, where it sees no files, and begins the generation process, eventually build and storing the docs on disk.  A second request (that also checks if the docs exist) might _also_ hit `pod-a`, and get the thumbs up ("yes, these docs exist"), thus allowing another request for the HTML itself to start...  But this third request could be routed to `pod-b`, which does not have any such file yet, leading to a 404 experience.  ...As more people attempt to load the site, it becomes more likely that each pod will have generated and stored documentation.

To avoid this, you'll want to use a publisher other than `local`...  Something that writes files to a persistent storage location (e.g. AWS S3, GCS, etc).

**Comment by garyniemen** [comment]
@Vegim Can this issue be closed?

**Comment by Vegim** [comment]
@garyniemen Yeah sure you can close it. The soultion for this issue was mentioned by @iamEAP

**Comment by riju1710** [comment]
I experience the same problem in openshift where i am running with 1 pod , in local and using docker-compose and run with below configuration works fine but in opeshift its gettting the error - {"level":"info","message":"Unable to get metadata for 'component:default/api-guidelines' with error Error: Unable to read techdocs_metadata.json at /opt/app-root/src/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/api-guidelines/techdocs_metadata.json. Error: Error: ENOENT: no such file or directory, open '/opt/app-root/src/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/api-guidelines/techdocs_metadata.json'; caused by Error: ENOENT: no such file or directory,

techdocs:
  builder: 'local'
  publisher:
    type: 'local'
  generator:
    runIn: local

**Comment by riju1710** [comment]
any solutions

**Comment by bbgobie** [comment]
I experience the same issue in AKS with Nginx.
I'm unable to duplicate on my local k8s via K8s service with 5 replicas of my pod.
In my local I do get the metadata.json error but the end user does not get the 404 page

**Comment by ddeath** [comment]
Hi, if you have 1 pod, then manual workaround is to hit this endpoint:
`curl 'http://localhost:7007/api/techdocs/sync/default/component/template-service'`

where the path is basically same as as the one in error. Once you hit that endpoint then it should start working again.
