### ISSUE TITLE
[Scaffolder] Have a way to display the rendered file contents on the task result page

### ISSUE THREAD

**Issue by namco1992** [backstage/backstage#12304]
## Feature Suggestion

Have a way to display the rendered file contents on the task result page.

## Possible Implementation
We brainstormed a few approaches, and then got inspired by the dry-run feature https://github.com/backstage/backstage/pull/11173.

It could be implemented in two parts:
1. Have a preview action for software template authors to add it in their template. This action will just extract the file contents and put it to the `output` as this is the only way to send the results back to frontend.
2. A frontend component to display the result if there is any. It could be a collapsable tab like the dry-run results in template editor.

We've implemented this internally and it looks like this (thanks to the foundation work done in https://github.com/backstage/backstage/pull/11173 😄):

<img width="932" alt="image" src="https://user-images.githubusercontent.com/9165473/176358738-1ef3fa5c-9915-4e4b-b1c3-466fb2ee4a5d.png">

We would like to help to implement this if it's something that the community sees useful.

## Context

We have a large amount of repos that we would like to onboard to Backstage, and a canonical way to generate the `catalog-info.yaml` would be a great help in this early adoption stage. In the meantime, there are some historical reasons that we can't simply create a PR to a repo. Therefore, we would like to using the software template to generate the `catalog-info.yaml`, and show it as a task result on the frontend, so the users can copy the content and put it wherever they see fit.

However, there is currently no way to actually display the rendered file contents on the frontend, you can only have a PR or a brand new repo created, and direct the user to the according page.

A preview function can help if:
1. You want people to try out the software template without actually creating a PR/repo (feels like a dry-run, but serves different purposes, we still want the user to run our prepared templates)
2. You just want to preview what's in there before actually committing it

**Comment by namco1992** [comment]
@freben Thanks for the insights! Initially, we just wanted to see the rendered files on the page, and I didn't think that far regarding the "stop and approve to continue" part, IMO it seems to be a larger scope that might be in a separate issue/needs an RFC.

I think what we proposed here is more about providing an out-of-box "Inspecting work dir contents" solution. It's true that you can come up with whatever action you see fit as you suggested, but they all come with third-party dependencies. e.g. for uploading it, you might need some object storage like S3, and a corresponding integration with it.

IMO, it would be helpful if the Backstage itself can provide an easy way to preview the results. Currently what we did is just having an action, say "debug:preview", to extract the content to `output`:
```typescript
      const results = directoryContents.map(file => ({
        path: file.path,
        base64Content: file.content.toString('base64'),
      }));

      ctx.output('directoryContents', results);
```
And then you can add this action to your template, and expose the output:
```yaml
  steps:
	...
    - id: preview
      name: Preview
      action: debug:preview
  output:
    directoryContents: ${{ steps.preview.output.directoryContents }}
```
By doing this, the `directoryContents` will be streamed back to frontend, and can be used to display the contents (after some modification of the task page):
![image](https://user-images.githubusercontent.com/9165473/177275315-d8e95fda-e902-4317-97ec-547ca5c54a19.png)

This is a quick solution without tampering too much with the current workflow, however, it might be an issue if you have a large number of files/large file size, since all the outputs are stored in the database.

**Comment by benjdlambert** [comment]
So, just want to make sure that I understand the use case correctly.

1. You can't easily raise PR's to existing components
2. You want to make a script to kick off a scaffolder job for each repository that you will give the team the link to the job run so that they can see the output of the catalog-info.yaml
3. They can then raise the PR themselves with the contents of the `catalog-info.yaml` that they see in the output?

Is that correct?

**Comment by namco1992** [comment]
Hi @benjdlambert 👋 ,
1. Correct, and we actually can't do that even if we want to since we use Bitbucket and there is no Bitbucket PR publish action 😢 
2. Haven't reached the script level yet, but yes I think we can achieve that since the tasks (and the output) are persisted
3. Correct.

**Comment by namco1992** [comment]
Hi @benjdlambert, yes I do agree that it might be quite a specific use case, but I still decided to try my luck and shared my thoughts here to see if there are others who face the same issue 😳.

Currently we've built this "preview" feature by forking and modifying the scaffolder plugin, but we actually prefer not to do this as it might be hard for us to maintain it and keep up with the upstream releases. We will start building the Bitbucket PR action and hopefully can contribute it back to upstream.

Btw, the dry-run has two options, "Load template directory" loads a local dir, and you can edit and execute it. "Edit template form" allows you to pick a template from the catalog, but you can't execute it. So what we need is the mix if them, pick a template from catalog and execute it. Is there any particular reason that the dry-run prevents you from running a template from catalog?

**Comment by benjdlambert** [comment]
> Is there any particular reason that the dry-run prevents you from running a template from catalog?

Hmm not really I suppose, it's just only used for testing. And I'm also unsure how you would indicate how it's a dry run of a template compared to a normal run.

Thinking that we can keep this ticket open to see if there's any interest, but I'd recommend building your own solution for this to be honest, rather than adding this to the scaffolder right now.

**Comment by jpeach** [comment]
@benjdlambert A second use case for this - use the scaffolder UI to generate a Jira "create issue" link. The scaffolder is an easy way to generate a UI that lets you capture title, description, component and a few other fields. But there's no obvious system to send the resulting Jira link to, people would copy it from some results page UI and paste it where they need it.

**Comment by benjdlambert** [comment]
Hmm you could also use the `output` part to provide link to the created JIRA ticket though as part of that run, it's just a little confusing that the results page is still there. We're working on reimplementing some of this view also, so maybe it might make sense after the redesign.
