### ISSUE TITLE
TechDocs: Throwing error with base image as node:16-bullseye-slim

### ISSUE THREAD

**Issue by cinlysobin** [backstage/backstage#12308]
## Expected Behavior

TechDoc should load correctly when building with base image as "node:16-bullseye-slim" in docker file
## Actual Behavior

The error message is throwing as someone has dropped the MIC
## Steps to Reproduce

build the docker image with base image as node:16-bullseye-slim
Deploy and verify the techdocs.

Error message is throwing as someone have dropped the MIC
## Context

But with node:14-buster-slim Techdocs is working fine. But the same image is showing some vulnerabilities in Quay Scan.

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by garyniemen** [comment]
@iamEAP do you have time to look at this one?

**Comment by iamEAP** [comment]
Hey @cinlysobin, we might need a little more detail to get to the bottom of what's going on.  Could you share the rest of your `Dockerfile`?

**Comment by cinlysobin** [comment]
@iamEAP ,
Please find the Docker file

```
FROM node:14-buster-slim
WORKDIR /app

COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn install --frozen-lockfile --production --network-timeout 300000 && rm -rf "$(yarn cache dir)"

COPY packages/backend/dist/bundle.tar.gz app-config*.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

#RUN apt-get update && apt-get install -y python3 python3-pip
#RUN pip3 install mkdocs-techdocs-core==1.1.2

RUN chgrp -R 0 ./ && \
    chmod -R g=u ./

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```

**Comment by manuelstein** [comment]
If the Backstage container should build the docs, then you need to uncomment the lines that would install Python:
```
#RUN apt-get update && apt-get install -y python3 python3-pip
#RUN pip3 install mkdocs-techdocs-core==1.1.2
```
And, AFAICT, it could be that some nodejs package can not use python correctly, because its scripts resolve the binary from the npm config. With the installation, you'd have the binary `python3` in your path, but not as `python`. It requires `RUN yarn config set python /usr/bin/python3` for the package to know that it should use `python3`.

I'm also missing build-essentials to be installed. Maybe check your yarn install output, does it show any build errors installing the npm packages?
Pls cmp. https://github.com/backstage/backstage/blob/master/packages/backend/Dockerfile

**Comment by cinlysobin** [comment]
Hi @manuelstein ,
Please find the updated Docker file. Still i am facing the issue

FROM node:16-bullseye-slim

# Install sqlite3 dependencies. You can skip this if you don't use sqlite3 in the image,
# in which case you should also move better-sqlite3 to "devDependencies" in package.json.
RUN apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential && \
    rm -rf /var/lib/apt/lists/* && \
    yarn config set python /usr/bin/python3

# From here on we use the least-privileged `node` user to run the backend.
#USER node
WORKDIR /app

# This switches many Node.js dependencies to production mode.
ENV NODE_ENV production

# Copy over Yarn 3 configuration, release, and plugins
COPY .yarn ./.yarn
COPY .yarnrc.yml ./

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
#COPY --chown=node:node yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./

COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn plugin import workspace-tools

# Note that this install is not immutable, which is one of the reasons we don't recommend Yarn 3 yet
RUN yarn workspaces focus --all --production && rm -rf "$(yarn cache clean)"

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY packages/backend/dist/bundle.tar.gz app-config*.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

RUN chgrp -R 0 ./ && \
    chmod -R g=u ./
    
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install mkdocs-techdocs-core==1.1.2

CMD ["node", "packages/backend", "--config", "app-config.yaml"]

**Comment by cinlysobin** [comment]
I can see following error in inspect page
![image](https://user-images.githubusercontent.com/47130315/190133445-79f98cc1-1bb3-4e4b-aff3-d79fe93175e5.png)

UI View
![image](https://user-images.githubusercontent.com/47130315/190134033-802af42c-dd87-4c72-8a47-5307ca557161.png)




![image](https://user-images.githubusercontent.com/47130315/190134193-9b6f765d-95f7-4ffe-8ccc-83011a4559eb.png)

**Comment by manuelstein** [comment]
Thx for the follow-up, @cinlysobin. I had experienced the mike drop error myself when switching to node:16, but this seems to be a different error. Your last screenshot shows the documentation has been successfully generated.
@iamEAP I don't know enough about what happens after the techdocs generation to help on this one.

What's weird to me is the second resource load error where it tries to fetch the entity (`/api/catalog/entities/by-name/group/default/...:1`) and fails with 404 Not Found. It looks like the entity can't be retrieved by name. Does the entity name end on `:1`?
