### ISSUE TITLE
Software Template: 'Publish' action do not create new repo in the any user input location in Github

### ISSUE THREAD

**Issue by kumarnil** [backstage/backstage#12319]
Current behavior : Publish action in the s/w template always create new repo in the owner root location.

Expect behavior: Using publish action, can we create new Github repo in any user input Github location.

**Comment by benjdlambert** [comment]
If you enter an organisation in the owner field it should create it in the organisation you provide.

**Comment by Rugvip** [comment]
asd

**Comment by Rugvip** [comment]
asd

**Comment by kumarnil** [comment]
The above suggest work for me. Please close this issue.

**Comment by benjdlambert** [comment]
Thanks! Glad it worked out!
