### ISSUE TITLE
 gihub discovery

### ISSUE THREAD

**Issue by sangeethdba** [backstage/backstage#12335]
## Expected Behavior

should be able to use gihub discovery

## Actual Behavior

after adding  the packages and trying to start he app ,we are getting module not found
[1] /opt/isv/backstage/store-systems/packages/backend/dist/main.js:356
[1] /******/ 			throw e;
[1]          			^
[1]
[1] Error: Cannot find module '@backstage/plugin-catalog-backend-module-github'
[1]     at webpackMissingModule (webpack-internal:///./src/plugins/catalog.ts:9:50)
[1]     at eval (webpack-internal:///./src/plugins/catalog.ts:9:172)
[1]     at Module../src/plugins/catalog.ts (/opt/isv/backstage/store-systems/packages/backend/dist/main.js:52:1)
[1]     at __webpack_require__ (/opt/isv/backstage/store-systems/packages/backend/dist/main.js:353:33)
[1]     at fn (/opt/isv/backstage/store-systems/packages/backend/dist/main.js:513:21)
[1]     at eval (webpack-internal:///./src/index.ts:16:74)
[1]     at Module../src/index.ts (/opt/isv/backstage/store-systems/packages/backend/dist/main.js:19:1)
[1]     at __webpack_require__ (/opt/isv/backstage/store-systems/packages/backend/dist/main.js:353:33)
[1]     at /opt/isv/backstage/store-systems/packages/backend/dist/main.js:1332:37
[1]     at Object.<anonymous> (/opt/isv/backstage/store-systems/packages/backend/dist/main.js:1334:12)
[1]     at Module._compile (node:internal/modules/cjs/loader:1105:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
[1]     at Module.load (node:internal/modules/cjs/loader:981:32)
[1]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[1]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
[1]     at node:internal/main/run_main_module:17:47 {
[1]   code: 'MODULE_NOT_FOUND'
[1] }
## Steps to Reproduce

OS:   Linux 5.4.0-117-generic - linux/x64
node: v16.15.1
yarn: 1.22.19
cli:  0.17.2 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.3
  @backstage/backend-common                        0.14.0
  @backstage/backend-tasks                         0.3.2
  @backstage/catalog-client                        1.0.3
  @backstage/catalog-model                         1.0.3
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.17.2
  @backstage/config-loader                         1.1.2
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.3
  @backstage/core-components                       0.9.5
  @backstage/core-plugin-api                       1.0.3
  @backstage/errors                                1.0.0
  @backstage/integration-react                     1.1.1
  @backstage/integration                           1.2.1
  @backstage/plugin-api-docs                       0.8.6
  @backstage/plugin-app-backend                    0.3.33
  @backstage/plugin-auth-backend                   0.14.1
  @backstage/plugin-auth-node                      0.2.2
  @backstage/plugin-catalog-backend-module-github  0.1.4
  @backstage/plugin-catalog-backend                1.2.0
  @backstage/plugin-catalog-common                 1.0.3
  @backstage/plugin-catalog-graph                  0.2.18
  @backstage/plugin-catalog-import                 0.8.9
  @backstage/plugin-catalog-react                  1.1.1
  @backstage/plugin-catalog                        1.3.0
  @backstage/plugin-github-actions                 0.5.6
  @backstage/plugin-org                            0.5.6
  @backstage/plugin-permission-common              0.6.2
  @backstage/plugin-permission-node                0.6.2
  @backstage/plugin-permission-react               0.4.2
  @backstage/plugin-proxy-backend                  0.2.27
  @backstage/plugin-scaffolder-backend             1.3.0
  @backstage/plugin-scaffolder-common              1.1.1
  @backstage/plugin-scaffolder                     1.3.0
  @backstage/plugin-search-backend-module-pg       0.3.4
  @backstage/plugin-search-backend-node            0.6.2
  @backstage/plugin-search-backend                 0.5.3
  @backstage/plugin-search-common                  0.3.5
  @backstage/plugin-search-react                   0.2.1
  @backstage/plugin-search                         0.9.0
  @backstage/plugin-tech-radar                     0.5.13
  @backstage/plugin-techdocs-backend               1.1.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.1
  @backstage/plugin-techdocs-node                  1.1.2
  @backstage/plugin-techdocs-react                 1.0.1
  @backstage/plugin-techdocs                       1.2.0
  @backstage/plugin-user-settings                  0.4.5
  @backstage/release-manifests                     0.0.4
  @backstage/test-utils                            1.1.1
  @backstage/theme                                 0.2.15
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 0.67s.

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by freben** [comment]
Did you add `@backstage/plugin-catalog-backend-module-github` to your backend package.json, and ran `yarn install`?

**Comment by sangeethdba** [comment]
i did these steps.

# From your Backstage root directory
yarn add --cwd packages/backend @backstage/integration
yarn add --cwd packages/backend @backstage/plugin-catalog-backend-module-github
And then add the processors to your catalog builder:

// In packages/backend/src/plugins/catalog.ts
+import {
+  GithubDiscoveryProcessor,
+  GithubOrgReaderProcessor,
+} from '@backstage/plugin-catalog-backend-module-github';
+import {
+  ScmIntegrations,
+  DefaultGithubCredentialsProvider
+} from '@backstage/integration';

 export default async function createPlugin(
   env: PluginEnvironment,
 ): Promise<Router> {
   const builder = await CatalogBuilder.create(env);
+  const integrations = ScmIntegrations.fromConfig(env.config);
+  const githubCredentialsProvider =
+    DefaultGithubCredentialsProvider.fromIntegrations(integrations);
+  builder.addProcessor(
+    GithubDiscoveryProcessor.fromConfig(env.config, {
+      logger: env.logger,
+      githubCredentialsProvider,
+    }),
+    GithubOrgReaderProcessor.fromConfig(env.config, {
+      logger: env.logger,
+      githubCredentialsProvider,
+    }),
+  );

as per the document https://github.com/backstage/backstage/blob/1cb9cec16b2dfaa119b4caebd6517474c610319e/docs/integrations/github/discovery.md
and ran yarn dev

**Comment by freben** [comment]
What does the dependencies section look like in your `packages/backend/package.json`?

Are you running "yarn dev" in the package root or somewhere else?

**Comment by freben** [comment]
Are you no longer seeing the problem that this issue originally reported? Feel free to close the issue if so, and if needed ask for assistance on discord or in an issue for any followup things that appear
