### ISSUE TITLE
createAuthProviderIntegration is not publicly exported

### ISSUE THREAD

**Issue by simonecorsi** [backstage/backstage#12346]
## Expected Behavior

Hey 👋 

I was following the docs to integrate a back-to-back non-oauth auth provider and stumbled upon [this line](https://backstage.io/docs/auth/add-auth-provider#integration-wrapper) saying I should use `createAuthProviderIntegration` to connect my custom provider to the backend, but it seems that it is not exported in [auth-backend/src/providers/index.ts](https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/providers/index.ts)

I've opened an [PR for this](https://github.com/backstage/backstage/pull/12347) if you want to take a look

## Context

If external developers want to write their own custom Auth Provider they cannot use that function right now

**Comment by benjdlambert** [comment]
Closing as merged! Thanks!
