### ISSUE TITLE
Serving static files from suburl not working using app_baseUrl as environment variable

### ISSUE THREAD

**Issue by Hanyman8** [backstage/backstage#12387]
Hello, we are having an issue with serving static files from suburl using environment variables

We need to have served static files from https://OUR-DOMAIN/our-catalog/static/ because on https://OUR-DOMAIN/ there is other microservice with documentation.

I tested using hardcoded values to app-config.yaml and it works explained here https://github.com/backstage/backstage/issues/7285 
```
backend:
  baseUrl: https://OUR-DOMAIN/our-catalog/
```
and 
```
app:
  baseUrl: https://OUR-DOMAIN/our-catalog/
```

and it works hardcoded into app-config.yaml,

but it is NOT working, when I have set these two values as environment variables
```
APP_CONFIG_backend_baseUrl: https://OUR-DOMAIN/our-catalog/
APP_CONFIG_app_baseUrl: https://OUR-DOMAIN/our-catalog/
```

## Expected Behavior

The web should serve static files from suburl using environment variables

## Actual Behavior

Empty webpage, and the (web) console says: GET https://OUR-DOMAIN/static/module-lodash.43570314.js net::ERR_ABORTED 404 and other similar errors

## Steps to Reproduce

One application with its static files on https://DOMAIN/static/
Backstage instace running on https://DOMAIN/suburl/

## Context
It is running in GCP cluster next to our documentation service
Backstage and other docs app are in docker files

## Your Environment
GCP Kubernetes cluster

Google Chrome

- Output of `yarn backstage-cli info`: 
OS:   Linux 5.14.18-100.fc33.x86_64 - linux/x64
node: v16.14.0
yarn: 1.22.17
cli:  0.17.1 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.2
  @backstage/backend-common                        0.13.5
  @backstage/backend-tasks                         0.3.1
  @backstage/catalog-client                        1.0.2
  @backstage/catalog-model                         1.0.2
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.17.1
  @backstage/config-loader                         1.1.1
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.2
  @backstage/core-components                       0.9.4
  @backstage/core-plugin-api                       1.0.2
  @backstage/errors                                1.0.0
  @backstage/integration-react                     1.1.0
  @backstage/integration                           1.2.0
  @backstage/plugin-api-docs                       0.8.5
  @backstage/plugin-app-backend                    0.3.32
  @backstage/plugin-auth-backend                   0.14.0
  @backstage/plugin-auth-node                      0.2.1
  @backstage/plugin-catalog-backend                1.1.2
  @backstage/plugin-catalog-common                 1.0.2
  @backstage/plugin-catalog-graph                  0.2.17
  @backstage/plugin-catalog-import                 0.8.8
  @backstage/plugin-catalog-react                  1.1.0
  @backstage/plugin-catalog                        1.2.0
  @backstage/plugin-github-actions                 0.5.5
  @backstage/plugin-org                            0.5.5
  @backstage/plugin-permission-common              0.6.1
  @backstage/plugin-permission-node                0.6.1
  @backstage/plugin-permission-react               0.4.1
  @backstage/plugin-proxy-backend                  0.2.26
  @backstage/plugin-scaffolder-backend             1.2.0
  @backstage/plugin-scaffolder-common              1.1.0
  @backstage/plugin-scaffolder                     1.2.0
  @backstage/plugin-search-backend-module-pg       0.3.3
  @backstage/plugin-search-backend-node            0.6.1
  @backstage/plugin-search-backend                 0.5.2
  @backstage/plugin-search-common                  0.3.4
  @backstage/plugin-search-react                   0.2.0
  @backstage/plugin-search                         0.8.1
  @backstage/plugin-tech-radar                     0.5.12
  @backstage/plugin-techdocs-backend               1.1.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.0
  @backstage/plugin-techdocs-node                  1.1.1
  @backstage/plugin-techdocs-react                 1.0.0
  @backstage/plugin-techdocs                       1.1.1
  @backstage/plugin-user-settings                  0.4.4
  @backstage/release-manifests                     0.0.3
  @backstage/search-common                         0.3.4
  @backstage/test-utils                            1.1.0
  @backstage/theme                                 0.2.15
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

Thanks for any help

**Comment by Hanyman8** [comment]
It also works, when I have both set up 
Hardcoded in `app-config.yaml` and environment variables

**Comment by freben** [comment]
One "quirk" of the config system is that all config has to be present at build time as well because parts of it gets baked into the frontend build artifact. What has happened here, I think, is that the frontend was built without the config flags so that field was left empty.
