### ISSUE TITLE
[github-actions plugin] Filter should search across all pages

### ISSUE THREAD

**Issue by martina-if** [backstage/backstage#12391]
## Expected Behavior

When using the Github Actions plugin and wanting to use the `filter` search bar I would expect it to filter across all the pages of the list and not just the page that's selected.

## Actual Behavior

![Screenshot 2022-07-01 at 15 32 31](https://user-images.githubusercontent.com/736631/176904747-31077cd5-0af7-4e74-8aec-4a7a63f974d7.png)

In the example above, filtering for the word `add` found an entry but I had to go to the next page to find it (see at the bottom of the table it says `6-8 of 8`) - the first page was just empty but I could press the ">" button.

## Steps to Reproduce

1. Make sure the Github actions plugin is installed and the github configuration is set up
2. Register this component [https://github.com/RoadieHQ/sample-combined-monorepo/blob/main/catalog-info.yaml]()
3. Go to the github actions plugin and type "add" in the filter input

## Context

There are other components in backstage that follow the expected behaviour I explained above: filter should filter across all pages and the paging should then apply to the filtered data instead. Such components include the main catalog table or the github pull requests plugin table.

## Your Environment

```text
 "@backstage/plugin-github-actions": "^0.5.0",
```

**Comment by martina-if** [comment]
I would rather not disable this filter because we have heard form our users that this feature is very important when dealing with monorepos. And for this reason as well, the behaviour of the catalog table is better in my opinion. Not sure if we will get time to contribute this but if so, do you agree that this would be a good change?

**Comment by Rugvip** [comment]
Yep I think it makes sense to implement this by supplying filters to the GitHub API, which ofc means that we're limited by whatever filtering the GitHub API supports. It should be possible to hook up the data loading of the table so that it uses a callback that receives the filters, see for example [TodoList](https://github.com/backstage/backstage/blob/b80210274a0de24aba819edf807821fe6598ee8d/plugins/todo/src/components/TodoList/TodoList.tsx#L92-L120)

**Comment by garyniemen** [comment]
@martina-if What do you think about this issue now?

**Comment by emmaindal** [comment]
This issue seems to be unrelated to the search plugin and can be solved instead by changing the usage of the GitHub API, so I'll remove that label and keep the issue opened.
