### ISSUE TITLE
external TechDocs - owner in the TechDocs path

### ISSUE THREAD

**Issue by SainDave** [backstage/backstage#12411]
Currently if the TechDocs are stored externally then the path to the TechDocs takes the form:
```
default/Component/<entityName>
```
If you have multiple GitHub owners publishing to the same instance of Backstage then get clashes and prevents migration from one owner to another.

## Feature Suggestion
Include the owner in the TechDocs path:
```
default/Component/<owner>/<entityName>
```

## Possible Implementation
For example TechDocs in repository https://github.com/SainDave/my-awsome-app would be stored in:
```
default/Component/SainDave/my-awsome-app
```

## Context
This is to support multiple owners using the same instance of Backstage.

**Comment by soapraj** [comment]
Hi! @SainDave 

The triplet  default/Component/<entityName> is :namespace/:kind/:entityName maybe each owner could use a different namespace?
