### ISSUE TITLE
Github Auth Popup not closing after User cancels at the Oauth screen in it

### ISSUE THREAD

**Issue by shailendra-ahir-cbre** [backstage/backstage#12439]
## Expected Behavior
Enabled Login with github. If the user logs rejects the auth request, The popup should also closed.

## Actual Behavior
When the user "cancel" the oauth request the popup redirects to the /api/auth/github with errors description in URL and does not close itself.

![image](https://user-images.githubusercontent.com/91642195/177325931-0c992942-0c43-428d-b320-874b2623afaa.png)

![image](https://user-images.githubusercontent.com/91642195/177326707-4302e3ea-da6b-45e2-be4b-796ff097a16b.png)

![image](https://user-images.githubusercontent.com/91642195/177327177-55bcfdc3-fb8a-4048-b18b-727c2a096703.png)

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by Rugvip** [comment]
Does login work? It looks like your redirect URL is incorrect as it's taking the user back to the frontend rather than the backend auth endpoint. The path should be something like `/api/auth/github/handler/frame`
