### ISSUE TITLE
Techdocs, bitbucket reader doesn't update the last version in case of a different branch of default one

### ISSUE THREAD

**Issue by carlitose** [backstage/backstage#12449]
## Expected Behavior

You have your techdocs posted on bitbucket and you would show a version of a particular branch, in case of new commits you would like to see the new update on techdocs.

## Actual Behavior

After the first build of techdocs, you don't see any update

## Steps to Reproduce

1. Have a repository of techdocs in bitbucket
2. Create a new branch from the default
3. Added the new  URL of the new branch on the catalog `${bitbucketUrl}/${project}/${repo}/tree/${branch}`
4. Build the new version of techdocs
5. Make an update and push the new commit
6. Will not see any change

## Context

The problem is on 
[BitbucketUrlReader](https://github.com/backstage/backstage/blob/02e35fe7688c47e49b785ad4ce643c1bf0ae86bc/packages/backend-common/src/reading/BitbucketUrlReader.ts#L223)
```
 const commitsApiUrl = isHosted
      ? `${this.integration.config.apiBaseUrl}/repositories/${project}/${repoName}/commits/${branch}`
      : `${this.integration.config.apiBaseUrl}/projects/${project}/repos/${repoName}/commits`;
```
The case `isHosted` is false,  it uses this [endpoint](https://docs.atlassian.com/bitbucket-server/rest/7.9.0/bitbucket-rest.html#idp222)

But it explains:

_Retrieve a page of commits from a given starting commit or "between" two commits. **If no explicit commit is specified, the tip of the repository's default branch is assumed.** commits may be identified by branch or tag name or by ID. A path may be supplied to restrict the returned commits to only those which affect that path._

this means that in every case it provides only the list of default branch commits, so we don't have the list of the branch commits

**Comment by carlitose** [comment]
The problem exists also on`BitbucketSeverReader.getLastCommitShortHash` https://github.com/backstage/backstage/blob/master/packages/backend-common/src/reading/BitbucketServerUrlReader.ts#L192

**Comment by garyniemen** [comment]
Does the merged PR close this issue?
