### ISSUE TITLE
Add default scaffolding metrics

### ISSUE THREAD

**Issue by spencerrichardhenry** [backstage/backstage#12453]
(This issue is really a subset of what https://github.com/backstage/backstage/issues/8398 tackles. Let me know if this issue should be closed in favor of that one.)

We want to add (prometheus) metrics around scaffolding. How many projects have been scaffolded, who is using the scaffolder, time to scaffold a project, etc. Instead of forking each action and adding custom metrics, we thought to go ahead and contribute them to the Backstage repo. However, a discussion needs to take place around which metrics should be implemented (as well as any implementation details, how to handle metrics in a framework-agnostic manner, etc). I intend for this issue to give us the clarity into those subjects we need and then be closed by a PR we contribute.

## Possible Implementation

In the scaffolding actions, see if a prom register exists, and if it does, add the default scaffolding metrics to it.

## Context

Relevant discord thread: https://discord.com/channels/687207715902193673/923143744176418836/991731005486534676

**Comment by awanlin** [comment]
Just wanted to mention that there was talk of using OpenTelemetry when the catalog metrics were added: https://github.com/backstage/backstage/pull/6848#issuecomment-900234530. I'm wondering if that worth taking another look at, it's been nearly a year

More details on OpenTelemetry here: https://github.com/open-telemetry/opentelemetry-js

**Comment by cvperinchery** [comment]
Some other metrics that would be nice are:
- individual action invocations
- individual action latency
- latency for custom field extension

**Comment by cctechwiz** [comment]
Similar to what was mentioned above I'd like to see:

- the user (and what group they belong to) that triggered the scaffolding job
- the specific template/version that was used
- the duration of the scaffolding run (ideally of each action so we can track improvements over time if there are big actions)
- the success / error rates (of the whole pipeline and each action so we can zero in on problem actions)

**Comment by simonstamm** [comment]
We're also interested in those metrics mentioned above, especially:

* usage of each template (success and error count)
* duration of the scaffolder

**Comment by spencerrichardhenry** [comment]
PR: https://github.com/backstage/backstage/pull/13683

**Comment by Pike** [comment]
I think this landed with #13815

**Comment by freben** [comment]
Closing as implemented!
