### ISSUE TITLE
static catalog locations don't support gitlab unscoped route targets

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#12456]
## Expected Behavior

If I add a static catalog location to my app-config targeting an [unscoped route](https://docs.gitlab.com/ee/development/routing.html#project-routes) (i.e. a route without the `/-/` separator after the project name) to a file on a GitLab server, Backstage should parse the route and figure out how to access that file via the GItLab API using the token configured in the `integrations` section of my app-config.

## Actual Behavior

The referenced entity does not appear in the catalog, and the Backstage server logs lines like this:

```text
catalog warn YAML error at url:http://GITLAB-HOST/GROUP/PROJECT/blob/master/catalog-info.yaml, YAMLSyntaxError: All collection items must start at the same column
```

## Steps to Reproduce

1. Configure your gitlab integration with a token and add a static location to your app-config which targets an unscoped URL, like
    ```yaml
    integrations:
      gitlab:
        - host: GITLAB-HOST
          token: GITLAB-TOKEN
          apiBaseUrl: http://GITLAB-HOST/api/v4
    catalog:
      locations:
        - type: url
          target: http://GITLAB-HOST/GROUP/PROJECT/blob/master/catalog-info.yaml
    ```
2. open the catalog in your browser
3. view the server logs

## Context

I've got a pretty good picture of what's going on here.
1. When the GitLabUrlReader wants to read a location, first it [gets a fetch URL for the target](https://github.com/backstage/backstage/blob/74f72e5341a962743059b25a1bbaed8bfc0d5d24/packages/backend-common/src/reading/GitlabUrlReader.ts#L75)
2. When that target is an unscoped URL, we hit the default branch of [this conditional](https://github.com/backstage/backstage/blob/74f72e5341a962743059b25a1bbaed8bfc0d5d24/packages/integration/src/gitlab/core.ts#L42-L49) -- spoiler alert: @Rugvip's concern that this "might require some more work" turns out to be true 😬 
3. The [buildRawUrl function](https://github.com/backstage/backstage/blob/74f72e5341a962743059b25a1bbaed8bfc0d5d24/packages/integration/src/gitlab/core.ts#L69-L72) converts the unscoped URL to a raw URL.
4. When a request is made to that raw URL, [a `PRIVATE-TOKEN` header is provided](https://github.com/backstage/backstage/blob/74f72e5341a962743059b25a1bbaed8bfc0d5d24/packages/backend-common/src/reading/GitlabUrlReader.ts#L81) -- unfortunately, those raw URLs are intended to be accessed by a browser and they don't support token-based auth!
5. The GitLab server thinks it's receiving a browser request with no session info, so it responds with a redirect to the signin page.
6. Backstage tries to parse this 3xx response body as YAML, and it's not valid! Hence the error in the logs.

GitLab has been in the [process](https://docs.gitlab.com/ee/development/routing.html#migrating-unscoped-routes) of moving away from/deprecating these old-style unscoped routes for some time (ever since the introduction of subgroups), but it still maintains backwards compatibility with the old routing style. Backstage should probably continue to respect these old routes, at least as long as GitLab does.

Anyway, the correct change is probably to modify `getGitLabFileFetchUrl` so that, when presented with an unscoped URL, it converts it to a proper token-authenticating endpoint in the same way as the scoped case.

## Your Environment

- Browser Information:  Firefox 102.0

- Output of `yarn backstage-cli info`: 

I know these are a little out of date, but I'm confident the problem is still around!

```text
OS:   Darwin 21.5.0 - darwin/x64
node: v14.19.1
yarn: 1.22.10
cli:  0.8.1 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.9
  @backstage/backend-common                                0.13.2, 0.9.8, 0.9.14, 0.9.6, 0.9.9
  @backstage/catalog-client                                0.5.0, 0.5.5, 0.5.3, 0.7.2
  @backstage/catalog-model                                 0.9.6, 0.10.1, 0.11.0, 0.9.10, 0.9.8, 1.0.0
  @backstage/cli-common                                    0.1.5, 0.1.8
  @backstage/cli                                           0.7.16, 0.8.1
  @backstage/config-loader                                 0.6.10, 0.7.1, 0.7.2, 0.8.1, 1.1.0
  @backstage/config                                        0.1.11, 0.1.15, 1.0.0
  @backstage/core-app-api                                  0.1.19, 0.1.20, 0.2.1, 0.5.4
  @backstage/core-components                               0.6.1, 0.7.2, 0.7.3, 0.8.10, 0.8.2
  @backstage/core-plugin-api                               0.4.0, 0.1.12, 0.1.13, 0.3.1, 0.6.1, 0.7.0, 1.0.1
  @backstage/dev-utils                                     0.2.12
  @backstage/errors                                        0.1.4, 0.1.5, 0.2.2, 1.0.0
  @backstage/integration-react                             0.1.13
  @backstage/integration                                   0.6.10, 0.6.9, 0.7.0, 0.7.5, 1.1.0
  @backstage/plugin-api-docs                               0.6.12
  @backstage/plugin-app-backend                            0.3.18
  @backstage/plugin-auth-backend                           0.4.9
  @backstage/plugin-catalog-backend                        0.17.0, 0.18.0
  @backstage/plugin-catalog-import                         0.7.3
  @backstage/plugin-catalog-react                          0.6.9, 0.6.2, 0.6.15
  @backstage/plugin-catalog                                0.7.2
  @backstage/plugin-github-actions                         0.4.22
  @backstage/plugin-kubernetes-backend                     0.3.18, 0.4.13
  @backstage/plugin-kubernetes-common                      0.2.0, 0.1.5, 0.2.8
  @backstage/plugin-kubernetes                             0.5.2
  @backstage/plugin-org                                    0.3.27
  @backstage/plugin-permission-common                      0.5.1, 0.5.3
  @backstage/plugin-permission-react                       0.3.2, 0.3.4
  @backstage/plugin-proxy-backend                          0.2.13
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.4
  @backstage/plugin-scaffolder-backend                     0.15.14
  @backstage/plugin-scaffolder-common                      0.1.1
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.2.6
  @backstage/plugin-search                                 0.4.16
  @backstage/plugin-tech-radar                             0.4.11
  @backstage/plugin-techdocs-backend                       0.10.7
  @backstage/plugin-techdocs                               0.12.4
  @backstage/plugin-user-settings                          0.3.9
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.10.5
  @backstage/test-utils                                    0.1.20, 0.1.24
  @backstage/theme                                         0.2.12, 0.2.13, 0.2.14, 0.2.15
  @backstage/types                                         0.1.1, 0.1.3, 1.0.0
  @backstage/version-bridge                                0.1.0, 0.1.1, 0.1.2, 1.0.1
```

**Comment by Rugvip** [comment]
Applying the suggested fix to `getGitLabFileFetchUrl` sounds sensible! 👍 Is it something you'd like to contribute?
