### ISSUE TITLE
techdocs doesn't refresh the content for mkdocs-multirepo-plugin

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#12487]
We use https://github.com/jdoiro3/mkdocs-multirepo-plugin 

Our main repo contains root mkdocs.yaml
site_name: 'main'
site_description: 'main'
plugins:
  - techdocs-core
  - multirepo
nav:
  - Foundational-ADR: '!import $repo_1_url'
  - Service-ADR: '!import $repo_2_url'

$repo_1 contains mkdocs.yml and index.md and few .md files under docs
$repo_1 contains mkdocs.yml and index.md and few .md files under docs

Any changes we make to the root mkdocs.yaml or any .md files, gets reflected in backstage. Basically, somehow it finds the difference between the changes and retriggers the sync api and refreshes

Any changes we make to the $repo_1 OR $repo_2 mkdocs.yaml or any .md files, doesn't get reflected in backstage. Basically, somehow it is unable to find the difference between the changes so the content gets unrefreshed.

What is the trigger point for techdocs refresh?

**Comment by garyniemen** [comment]
This is not supported by default so I changed from bug to enhancement. Perhaps you can go to Discord docs like code channel to see if you can get any answers to your questions.

**Comment by dfl-aeb** [comment]
hey @shanthisagar-dhanya-kumar-db did you find a way to fix this?
I was thinking about force rebuilding the docs via the [sync api](https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/service/router.ts#L211) but unfortunately it's not possible atm.
