### ISSUE TITLE
Possibly require valid owner when using OwnerPicker

### ISSUE THREAD

**Issue by kjuulh** [backstage/backstage#12503]
When using owner picker it is not required that the selected value is a valid Owner. This is kind of unintuitive and requires extra handling on the backend to not receive invalid values.

## Feature Suggestion

As such we would like to have the same experience as using EntityPicker using `allowArbitraryValues: false`. This requires the user to select one of the options and not just anything arbitrary.

## Possible Implementation

```typescript 
// https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/OwnerPicker/OwnerPicker.tsx

export interface OwnerPickerUiOptions {
  allowedKinds?: string[];
  allowArbitraryValues?: boolean;
}
```

This should be sufficient to allow passing the value to EntityPicker which in turn already has a default of `true`

I would be happy to contribute the feature if wanted =D

## Context

Always having a valid owner after the create <something> template when for example trying to create a git repository we always have a valid team to create the repository under.

**Comment by benjdlambert** [comment]
Hey :wave: think this makes sense! Would you like to contribute this? I can assign you to the ticket if you want? :pray:

**Comment by kjuulh** [comment]
Sure that would be great. I'd be happy to

**Comment by benjdlambert** [comment]
Done! It's all yours 👏

**Comment by kjuulh** [comment]
As the PR has been merged, this enchancement should now be fixed.

**Comment by mustafazeya** [comment]
@kjuulh @benjdlambert How can we include this in our existing templates? what should be the version of the scaffolder-backend plugin for using this feature?
