### ISSUE TITLE
wrapInTestApp unmounts children on rerendering

### ISSUE THREAD

**Issue by vinzscam** [backstage/backstage#12524]
`wrapInTestApp` works great when testing components using testing library.
However, when testing a rerender of a component, it causes all the subcomponents to be recreated from scratch, losing any state.

## Expected Behavior

It shouldn't unmount and mount any child component.

## Steps to Reproduce

```javascript

 it('should correctly display the number of clicks', () => {
    function MyComponent() {
      const [state, setState] = useState(0);

      return (
        <>
          <span>number of clicks: {state}</span>
          <button onClick={() => setState(state + 1)}>increase counter</button>
        </>
      );
    }

    const { queryByText, getByText, rerender } = render(
      wrapInTestApp(<MyComponent />),
    );

    const button = getByText('increase counter');

    fireEvent.click(button);
    fireEvent.click(button);
    expect(queryByText('number of clicks: 2')).toBeInTheDocument();

    rerender(wrapInTestApp(<MyComponent />));
    fireEvent.click(button);
    expect(queryByText('number of clicks: 3')).toBeInTheDocument(); // here it fails, number of clicks: 0
});

```

## Context

This issue is producing false results and side effects inside some of my components, when testing how the components react in case of rerender.

Perhaps transforming the `wrapInTestApp` function into a react component could help in solving the issue.

**Comment by Rugvip** [comment]
Use `renderInTestApp(<MyComponent />)` + `rerender(<MyComponent />)` instead! `wrapInTestApp` creates a new app along with components every time, so it'd be tricky to keep those component references stable across calls.
