### ISSUE TITLE
[TechDocs] Editable content within the Backstage UI

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#12543]
## Feature Suggestion

What if it were possible to edit the contents of a TechDocs page right from the TechDocs UI in Backstage?

## Possible Implementation

- Community member @krivoruchkoN began implementing this as an Addon using `react-md-editor`: https://gist.github.com/krivoruchkoN/9de26d7971d4724ebd9d38824b315228.  Perhaps this could be taken across the finish line and generalized?

## Context

TechDocs has a few foundational advantages in place to help ensure documentation is high quality, up-to-date, and relevant: 

- The _docs like code_ philosophy of keeping documentation close to the source code it documents helps encourage updates as changes are made.
- View/edit links are integrated into the experience at the top of every page, making quick edits that much quicker
- The `<ReportIssue />` Addon simplifies the process of providing detailed feedback

...But even still, documentation can become stale and low quality over time.  Perhaps lowering the barrier to making changes _even further_ would help keep documentation quality, relevancy, and trust high.

**Comment by regicsolutions** [comment]
@iamEAP @Rugvip given this is closed was wondering if anything is planned for editing entity metadata within the UI.

Our use-case is similar and we were hoping to provide owners of entities the ability to propose or update entity metadata within the UI which would result in triggering and auto-merging a pull request.

**Comment by iamEAP** [comment]
I'm actually going to re-open this, as I think there's still quite a lot of interest in this area.

@regicsolutions: that sounds like a fantastic idea--something I bet the Catalog SIG would be interested in reviewing.  I'd recommend creating a separate issue to concentrate discussion and make sure it bubbles up to the SIG.

**Comment by georgeyord** [comment]
This is an important feature that would certainly make our life easier. Is there any intention on working on this?

**Comment by mitech11** [comment]
Any update here? I am stuck before we adopt this for our org as there are quite a few white papers that are written by researchers and analysts that have to stay close to my project technical documentation

**Comment by tradcliffe-expediagroup** [comment]
Hi, this is something my company is interested in working on in Q2, earlier if we have the bandwidth.

**Comment by G-man83** [comment]
Our company also need this feature 🙂

**Comment by chaulaode1257** [comment]
we also need this

**Comment by MarkPorohnja** [comment]
we need this feature as well

**Comment by daniddelrio** [comment]
This feature would be nice for us as well

**Comment by iamEAP** [comment]
Going to reopen this issue, as there appears to still be quite a bit of interest.

(I do not personally have availability to work or advise on this, however).

**Comment by camilaibs** [comment]
Perhaps adding suggestions for what the editing process would look like, defining requirements like who would be allowed to edit, whether changes should be reviewed by document owners, how you would view the user interface could help the community understand more concretely what we would like to implement.
Another question that came to mind is if it should be a core addon and kept in the main monorepo or if this issue could be moved to the community repo.

**Comment by tk-subgenius** [comment]
Hi, I like the idea @Rugvip  has to basically do it the same way as the browser-based template editor.  For me, the most important thing is to see the markdown rendered the 'backstage' way. 

I was editing a lot of markdown in VS Code using their markdown preview feature, but then when rendered in backstage some things were broken (lists, character escaping). I guess the markdown 'standard' isn't so rigid, resulting in differences between implementations.  So it would be great to get some realtime markdown preview directly from backstage.

**Comment by samrocketman** [comment]
I developed a local editor (integrated documentation environment).

* I use [techdocs-preview.sh][1] to launch it.
* It's [a WYSIWYG][2] intended to be run from local computer to quickly modify docs as code.

I developed it because there's not a good mkdocs parser for the features backstage supports.  So I made it.

[1]: https://github.com/samrocketman/home/blob/main/bin/techdocs-preview.sh
[2]: https://github.com/samrocketman/mkdocs-live-wysiwyg-plugin

**Comment by samrocketman** [comment]
I have grown the project into a functional extension for VSCode and derivatives of VSCode.

It has automated content refactoring when moving around documentation.  Specifically developed for TechDocs but can be used for any material themed docs as well.

The script has moved as well.

The project is now hosted at https://github.com/samrocketman/mkdocs-live-wysiwyg-plugin

**Comment by Estehsan** [comment]
👋 I built a plugin that implements this feature!

@estehsaan/backstage-plugin-techdocs-editor provides an in-app WYSIWYG Markdown editor for TechDocs pages that lets users edit and submit PRs without leaving Backstage.

Features:

"Edit this page" button via TechDocsEditPageAddon 
Full WYSIWYG editor (Toast UI) with file tree sidebar
Submits edits as pull/merge requests via GitHub or GitLab
Permissions-gated via @backstage/plugin-permission-common
Also available as an NFS extension page and entity content tab
Repo: https://github.com/Estehsan/backstage-techdoc-editor

Happy to answer questions or take feedback!
