### ISSUE TITLE
catalog-backend: querying facets is slow when there are lots of entites

### ISSUE THREAD

**Issue by zhyu** [backstage/backstage#12559]
## Expected Behavior

Querying facets should be optimized. 

## Actual Behavior

It takes around 1 second for our Backstage instance to query facets.
<img width="2106" alt="image" src="https://user-images.githubusercontent.com/1728523/178178063-5b52f300-bd51-44ea-8da4-66a2dacfc5cc.png">

## Steps to Reproduce

1. Prepare lots of entities (we have more than 30K)
2. Open the catalog page
3. Wait the tags filter to be rendered

## Context

We have more than 30K entities, however, most of them have no tags. I found it's pretty to slow to load the tags filter.
I checked the [source code](https://github.com/backstage/backstage/blob/426781af5ffa4bd6d90ade3374e64a7c330e1dc9/plugins/catalog-backend/src/service/DefaultEntitiesCatalog.ts#L329-L336), and found in this case, it seems all entities would be fetched in order to get their tags.
I wonder whether there is a way to optimize the query, instead of fetching all entities and then filter.

## Your Environment

- Browser Information:  Microsoft Edge
Version 103.0.1264.44 (Official build) (x86_64)

- Output of `yarn backstage-cli info`: 

```text
yarn run v1.22.19
$ /home/zhyu/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.4.0-1080-aws - linux/x64
node: v14.19.0
yarn: 1.22.19
cli:  0.17.2 (installed)

Dependencies:
  @backstage/app-defaults               1.0.3
  @backstage/backend-common             0.14.0
  @backstage/backend-tasks              0.3.2
  @backstage/catalog-client             1.0.3
  @backstage/catalog-model              1.0.3
  @backstage/cli-common                 0.1.9
  @backstage/cli                        0.17.2
  @backstage/config-loader              1.1.2
  @backstage/config                     1.0.1
  @backstage/core-app-api               1.0.3
  @backstage/core-components            0.9.5
  @backstage/core-plugin-api            1.0.3
  @backstage/dev-utils                  1.0.3
  @backstage/errors                     1.0.0
  @backstage/integration-react          1.1.1
  @backstage/integration                1.2.1
  @backstage/plugin-api-docs            0.8.6
  @backstage/plugin-app-backend         0.3.33
  @backstage/plugin-auth-backend        0.14.1
  @backstage/plugin-auth-node           0.2.2
  @backstage/plugin-catalog-backend     1.2.0
  @backstage/plugin-catalog-common      1.0.3
  @backstage/plugin-catalog-graph       0.2.18
  @backstage/plugin-catalog-import      0.8.9
  @backstage/plugin-catalog-react       1.1.1
  @backstage/plugin-catalog             1.3.0
  @backstage/plugin-circleci            0.3.6
  @backstage/plugin-github-actions      0.5.6
  @backstage/plugin-kubernetes-backend  0.6.0
  @backstage/plugin-kubernetes-common   0.3.0
  @backstage/plugin-kubernetes          0.6.6
  @backstage/plugin-org                 0.5.6
  @backstage/plugin-permission-backend  0.5.8
  @backstage/plugin-permission-common   0.6.2
  @backstage/plugin-permission-node     0.6.2
  @backstage/plugin-permission-react    0.4.2
  @backstage/plugin-proxy-backend       0.2.27
  @backstage/plugin-scaffolder-backend  1.3.0
  @backstage/plugin-scaffolder-common   1.1.1
  @backstage/plugin-scaffolder          1.3.0
  @backstage/plugin-search-backend-node 0.6.2
  @backstage/plugin-search-backend      0.5.3
  @backstage/plugin-search-common       0.3.5
  @backstage/plugin-search-react        0.2.1
  @backstage/plugin-search              0.9.0
  @backstage/plugin-techdocs-backend    1.1.2
  @backstage/plugin-techdocs-node       1.1.2
  @backstage/plugin-techdocs-react      1.0.1
  @backstage/plugin-techdocs            1.2.0
  @backstage/plugin-user-settings       0.4.5
  @backstage/release-manifests          0.0.4
  @backstage/test-utils                 1.1.1
  @backstage/theme                      0.2.15
  @backstage/types                      1.0.0
  @backstage/version-bridge             1.0.1
Done in 0.57s.

```

**Comment by freben** [comment]
Yeah - for context, we did use the catalog's entity search table initially for this purpose (it sure looks like a perfect, low hanging fruit for it), however that one has an intentionally force-lowercased value column so we wouldn't be able to get back correctly cased data. Hence the (known to be very wasteful) current first implementation.

Maybe it could be possible to amend the search table with a raw non-lowercased version of the value along with the one we already have. That would need a little bit of thought to get right - for example, what do we do when there are multiple variants of casing, eg in a string list such as `metadata.tags`? Do we keep just the most commonly occurring one or keep them all? Not a big problem, just mentioning it in passing.

Could also stop lowercasing the current column and instead ensure the use of a case insensitive index - but maybe that's a bit riskier to ensure that it works correctly across several db engines etc.

**Comment by awanlin** [comment]
Hi @nina-nee, would be super helpful to have details about your Backstage version and experience as well as Catalog size and any performance metrics you can share. This issue is pretty old so the information here isn't very helpful. I'd also look at enabling the Pagination feature documented here: https://backstage.io/docs/features/software-catalog/catalog-customization

**Comment by freben** [comment]
@nina-nee feel free to make a new issue with all of the relevant details (backstage versions, size of catalog, type of face that is being slow etc) and let's see if there's something to be found.
