### ISSUE TITLE
Show namespace in Kubernetes Error Reporting table

### ISSUE THREAD

**Issue by noisyscanner** [backstage/backstage#12565]
## Feature Suggestion
The error reporting table is very useful, but it could do with an extra column for the namespace, as we have the same pods/services/deployments replicated in several namespaces.
![image](https://user-images.githubusercontent.com/627654/178260479-a5318c70-ca1c-45d4-b4fb-6ce6b72d7e64.png)

## Possible Implementation
- Add another column to the table. Bonus points if clicking on it can scroll down the page and auto-expand the relevant namespace under the cluster accordion
- ...?

## Context
When the same resource exists in multiple namespaces, it can be difficult to work out easily where the errors are coming from.

I'm happy to have a bash at this if the team agrees with the simple implementation described above.

**Comment by benjdlambert** [comment]
@mclarke47 does this sound like something of value? :pray:

**Comment by benjdlambert** [comment]
Contribution are welcome, do you want to contribute this @noisyscanner? :pray:

**Comment by noisyscanner** [comment]
Ello, been away for a few weeks but happy to have a bash at this when I get a chance. Hopefully some time this week

**Comment by benjdlambert** [comment]
No worries :pray: I'll assign you to the ticket!
