### ISSUE TITLE
Not able to publish from a self-hosted Gitlab

### ISSUE THREAD

**Issue by HorcruxAshu** [backstage/backstage#12567]
**Status:** Open for comments

## Need

Not able to publish a repo in the self-hosted Gitlab on Backstage.io's Node.js template.
Getting 400 (Bad request error);

**Comment by benjdlambert** [comment]
Hey, going to close this issue and can you fill out this issue template instead? https://github.com/backstage/backstage/issues/new?assignees=&labels=bug&template=bug_template.md

**Comment by daydy16** [comment]
Hey @HorcruxAshu,
we're experiencing the same issues.
Have a look at this issue and this PR here: 
https://github.com/backstage/backstage/issues/8358 
https://github.com/backstage/backstage/pull/12403
