### ISSUE TITLE
Add button to clear all currently set filters

### ISSUE THREAD

**Issue by martinohmann** [backstage/backstage#12587]
## Feature Suggestion

It would be nice to have a button which clears all currently set filters.

## Possible Implementation

Clicking the button should clear the filters back to the defaults for the given view. For example, if filters are cleared on the catalog index, it should display `all` components or only the `owned` ones, depending on the configured `initialFilter`.

The implementation should be generic so that it is usable across all pages that provide filters (e.g. catalog, docs, api-docs, etc.).

## Context

I sometimes find myself manually resetting multiple filters and have the feeling that doing so via a single click is more ergonomic.

**Comment by benjdlambert** [comment]
Makes sense, do you have any ideas on what it should look like? Maybe a draft PR would be great? :pray:

**Comment by martinohmann** [comment]
@benjdlambert I'm not that familiar with React to quickly assemble a draft PR. This would take me a bit. But I did a small mockup to show how this could look like by messing around with the browser console 😉.

I also think the wording should be `Reset filters` instead of `Clear filters`, since the behaviour would be to reset them to the `initialFilters` instead of clearing them entirely.

![Screenshot 2022-07-14 at 16 40 27](https://user-images.githubusercontent.com/1335045/179009334-1c255097-acc9-43ad-8c63-db69ddfade4d.png)

**Comment by snehaljos** [comment]
hi @benjdlambert can I give it a try?

**Comment by benjdlambert** [comment]
Yep go ahead @snehaljos! Assigned!
