### ISSUE TITLE
Bump to Recharts V2

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#12609]
Renovate tried to bump Recharts from v1 to v2 but it looks like there's some breaking changes in the library that need fixing up in #12476

Let's bump to the latest library and fix up some of the Typescript errors that have started occurring part of the breaking changes.

It looks like there's absolutely 0 documentation on migration, https://github.com/recharts/recharts/issues/2333 so could be a little bit of trial and error, or maybe if someone has experience with doing this already and would like to help us out! :pray:

**Comment by benjdlambert** [comment]
Yeah they are I believe, any package that has a hard dependency of `recharts` will need updating at the same time to work with the new API that they've released without much instruction on how to upgrade 🤷

**Comment by asheerrizvi** [comment]
Alright, I guess I can give this a go over the weekend and see how it goes. Can you assign this to me? 🤞

**Comment by benjdlambert** [comment]
Of course! 👍

**Comment by benjdlambert** [comment]
Thanks! 👍

**Comment by asheerrizvi** [comment]
@benjdlambert wasn't able to work on this the previous weekend. Will try to take this up this time around.

**Comment by benjdlambert** [comment]
@asheerrizvi no worries - It's all good! 👊

**Comment by asheerrizvi** [comment]
@benjdlambert this one's a bit frustrating with the lack of any guide whatsoever lol. So I have got the project running on my local. Have upgraded recharts. For the typescript fixes I wanted to manually check if the graphs are working fine or not. Is there a way to do this on the UI for the plugins which need these upgrades?

**Comment by benjdlambert** [comment]
Hmm, some of them might have storybook stories, and as a workaround if there isn't any you could always just create a sample story for it and mock out the data that gets passed to the component?

**Comment by asheerrizvi** [comment]
Alright, thanks. Will try that.

**Comment by asheerrizvi** [comment]
@benjdlambert I am not able to find the time to work on this. I am un assigning myself from this, maybe someone else will be able to take this up. :|

**Comment by leonardomaier** [comment]
@benjdlambert just started working on this, could you please assign me?

**Comment by freben** [comment]
Assigned.

**Comment by leonardomaier** [comment]
@freben @benjdlambert done in https://github.com/backstage/backstage/pull/13517
