### ISSUE TITLE
não consigo registrar um componente 

### ISSUE THREAD

**Issue by Rafa3001** [backstage/backstage#12613]
ERRO 501 : Falha no carregamento do bloco carregado com preguiça, tente recarregar a página: Não é possível encontrar o módulo '@codemirror/autocomplete'

Parece que alguém deixou cair o microfone!
[Volte](http://localhost:3000/create) ... ou entre em [contato com o suporte](https://github.com/backstage/backstage/issues) [, Abre em uma nova janela](https://github.com/backstage/backstage/issues)se você acha que isso é um bug.

**Comment by oliveirafilipe** [comment]
Oi @Rafa3001, tudo certo? 

Acho que por estar em pt-br o título e descrição da Issue, talvez a comunidade não tenha tanta facilidade para te ajudar.

Tenho pouco conhecimento da ferramenta ainda mas me chamou atenção o título e descrição e pt-br então parei para ver e conseguiria ajudar em algo.

Tem mais informações sobre tua instalação? Por exemplo, estás rodando em Windows ou Linux (qual distro)? Estavas seguindo algum tutorial quando se deparou com o erro?
