### ISSUE TITLE
Extend ensureExists to database configuration when pluginDivisionMode=schema

### ISSUE THREAD

**Issue by andrewduckett** [backstage/backstage#12626]
## Feature Suggestion

I would like to disable (or skip) the process that ensures a plugin schema already exists using database configuration options.

## Possible Implementation

This option already exists when ensuring a database exists here: https://github.com/backstage/backstage/blob/b1e2d92a9a28d3e568178da34675729a3596b101/packages/backend-common/src/database/DatabaseManager.ts#L312

Could extend this `ensureExists` option to the block that checks if a schema exists (when `pluginDivisionMode==schema`), see: https://github.com/backstage/backstage/blob/b1e2d92a9a28d3e568178da34675729a3596b101/packages/backend-common/src/database/DatabaseManager.ts#L323

Or create a new configuration option, like `ensureSchemaExists` that is only used when `pluginDivisionMode==schema`. 

## Context

I'm in a situation where I cannot modify/escalate permissions to enable auto-creation of databases or schemas in PostgreSQL.  

I can however provision an instance with multiple schemas (but not databases) via IAC.  Since I can provision schemas in a single database before the application starts, and I know both the database and schema(s) will exist, disabling "create schema if does not exist" would be extremely helpful.

**Comment by benjdlambert** [comment]
Do you want to contribute this? We're thinking that the first option sounds the best, would be a shame to add a configuration option for this. :pray:

**Comment by andrewduckett** [comment]
Sure thing, give me a bit to test that it all works e2e for me and I'll report back with a quick PR
