### ISSUE TITLE
[RFC] Add horizontal scalability support with leader election

### ISSUE THREAD

**Issue by Crevil** [backstage/backstage#12634]
**Status:** Open for comments

## Need

As backstage instances becomes more critical to organizations the need for horizontally scaling it becomes more important.
As backstage in it self is not a high load application this is not for handling request load but instead recilience to infrastructure disturbance, eg. node crashes, pod rescheduling etc.

If we can scale out the backstage instances to at least 2 instances we can get high availability of the deployment reducing incidents and support tasks related to operational imperfections.

Currently we cannot scale out backstage instances as all instances will run catalog syncronization jobs which leads to significant load on external systems like GitHub when scraping large organizations. This in turn eats up all API points and in the end renders backstage unable to fetch data.

## Proposal

Add leader election capabilities to the backend allowing individual instances to know whether they are in charge of background tasks like catalog syncing.

The idea is that when the backend starts it will try to acquire a lease. If obtained the specific instance is responsible for running background tasks like catalog syncing and all other instances will do nothing.

A couple of variations exists on this implementation. Both are using the concept of leader election which can be implemented with [PostgreSQL Advisory Locks](https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS). Some information can be found in this [Using Postgresql Advisory Locks for Leader Election](https://jeremydmiller.com/2020/05/05/using-postgresql-advisory-locks-for-leader-election/) blog post.

### 1 Active/passive

Only let one instance do all work, including serving traffic. This means that we should configure a readiness probe endpoint accordingly to eg. let Kubernetes only route traffic to active instances. This can be seen as an active/passive setup. If the active instance drops out, the passive one will be able to acquire the lease and become active.

### 2. Active/active

This variant will only perform leader election for background tasks, but all instances will serve HTTP traffic. This avoids "readyness probe" complexity as all instances are available for serving traffic. The leader election will only affect asyncrounous jobs, like catalog syncing and thus limits the implementation.

## Alternatives

Reduce the sync interval of the catalog reducing usage on 3rd party APIs.
This doesn't really solve the root problem but might be a viable solution that requires no changes to backstage now.

The instances will still do a lot of work, now redundantly leading to excessive resource usage compared to usage.

## Risks

It requires plugin authors that uses async jobs to respect the leader election concept.

Anything parts of backstage that currently relies on "only one instance" will also be impacted. This usually comes out as in-memory caching or job handling. I'm unsure if we have anything like that in backstage though.

**Comment by Rugvip** [comment]
This is totally already a thing? 😁 Both the catalog processing loop and entity providers will collaborate and distribute works across all instances that share the same database.

Specifically for leader election, if you want to run your own jobs, look at https://github.com/backstage/backstage/tree/master/packages/backend-tasks and the scheduling that it provides.

**Comment by Crevil** [comment]
Well well well. How about that! 🎉🎉

I was not able to find any documentation in this regard so I figured it wasn't implemented.

This is awesome news. I guess we should document this in the deployment docs somewhere that multiple replicas work ?

**Comment by Rugvip** [comment]
@Crevil yep, #12656 :grin:

**Comment by Crevil** [comment]
You'r a machine 🙌 Thank you 🎉

**Comment by angeliski** [comment]
Hey @Rugvip Is there some pattern to use the same approach for plugins?
For example, the [tech-insights-backend](https://github.com/backstage/backstage/tree/master/plugins/tech-insights-backend#running-fact-retrievers-in-a-multi-instance-installation) need a env to limit how is running the checks. I believe the plugin should be update to match multiple instances too, so, how we can do that?
