### ISSUE TITLE
Why does my demo have one template?

### ISSUE THREAD

**Issue by yanyuxuanz** [backstage/backstage#12648]

**Comment by yanyuxuanz** [comment]
There is only one nodejs template  on my demo program,and how should I add or get others template?

**Comment by benjdlambert** [comment]
There's only one template shipped with the demo data. There are some other example templates in this repository here: https://github.com/backstage/software-templates

**Comment by benjdlambert** [comment]
You can also read through this documentation on how to add additional templates to the catalog: https://backstage.io/docs/features/software-templates/adding-templates

Closing this as this is expected behaviour.
