### ISSUE TITLE
allow swagger ui plugin configuration on the api entity page

### ISSUE THREAD

**Issue by lnavarette** [backstage/backstage#12676]
## Feature Suggestion

Allow [swagger UI configuration](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/) to include plugins. 

## Possible Implementation

A hook seems like the smallest footprint way of achieving this. From a user perspective, I would just wrap my entity definition card in a provider, defining swagger UI configuration. Specifically, I'm looking for plugins, but we'd likely want to build the hook generically enough so that other config options could be added if needed by other users. 

## Context

We use swagger UI plugins to hide options endpoints from the swagger UI (our API gateway requires them to be there, but we don't actually want to see them in the swagger UI) and show code samples (API providers embed code samples in the swagger, they're rendered on the page).

**Comment by lnavarette** [comment]
@benjdlambert sure. Does the implementation I described make sense to you?

**Comment by benjdlambert** [comment]
Yeah, I mean there is also the option to pass the options in as a prop to the widget itself right? Maybe that's simpler? Depends what you feel is best. Happy for you to open a draft PR and we can talk more over the code?
