### ISSUE TITLE
[ API docs plugin] The plugin is unable to resolve the $ref field when the models(schemas) are defined in a separate file.

### ISSUE THREAD

**Issue by parnita-saha** [backstage/backstage#12687]
## Expected Behavior

The plugin should be able to resolve the schemas defined in a separate yaml file (e.g: models.yml) using the $ref field.

## Actual Behavior

The plugin fails with error "Resolver error at paths". (PFA)

## Steps to Reproduce

1. Create two swagger files in your project one containing path details and another containing model(schemas) details.
```yml
openapi: 3.0.0
info:
  title: Vehicle Search
  description: |
    The Vehicle search API
  version: 1.0.0-Draft
tags:
  - name: Vehicle Search
    description: APIs to query vehicle properties and vehicle model.
servers:
  - url: test@example.com
paths:
  /vehicles/brands:
    get:
      summary: Lists all available brands
      operationId: vehicleBrands
      responses:
        '200':
          description: Returns the list of brands
          content:
            application/json:
              schema:
                $ref: 'models.yml#/components/schemas/DataOptionList'
              example:
                values: [
                {
                  "value": "BMW",
                  "label": "BMW"
                }
                ]
        '400':
          $ref: 'models.yml#/components/responses/ClientError'
        '500':
          $ref: 'models.yml#/components/responses/ServerError'
      tags:
        - Vehicle Search

```
```yml
components:
  schemas:
    DataOptionList:
      type: object
      properties:
        values:
          type: array
          items:
            $ref: '#/components/schemas/VehicleData'
    VehicleData:
      type: object
      required:
        - label
        - value
      properties:
        label:
          type: string
          example: label
        value:
          type: string
          example: value
        additionalText:
          type: string

    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 100
          maximum: 599
          example: 503
        title:
          type: string
          description: A short, summary of the problem type. Written in english and readable for engineers.
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out

  responses:
    ClientError:
      description: Client side error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: 400
            title: "Bad request"
            detail: "Validation failed"
    ServerError:
      description: Server side error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: 500
            title: "Internal Server Error"
            detail: "Failed to map model"

```
3. Register the API in backstage using "Register existing API" feature of backstage.
4. Click on the "Definition" tab and click on any of the API spec. It shows the "Resolve error". 

## Context
In our projects schemas are always defined in model.yml, we are unable to use the the API-docs plugin to onboard our APIs in backstage.
![API_doc_Error](https://user-images.githubusercontent.com/48051452/179447662-9f071cb6-1977-48b9-8729-d6fc0baee1d0.PNG)

**Comment by kissmikijr** [comment]
Is this issue present when you have the OpenApiRefProcessor configured?

https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-openapi

**Comment by parnita-saha** [comment]
Hi @kissmikijr Thank you for the suggestion. Unfortunately, the issue still exist after configuring the  " OpenApiRefProcessor".

![ApiProcessor](https://user-images.githubusercontent.com/48051452/179919292-bb77c2d1-0dcc-4da1-ba7b-8b6d2753338c.PNG)
![packageJson](https://user-images.githubusercontent.com/48051452/179919314-7dde2004-2e78-4015-a2b7-ec203b2fa595.PNG)
"

**Comment by drankou** [comment]
Having the same issue here
`Could not resolve reference: Tried to resolve a relative URL, without having a basePath.`

**Comment by kissmikijr** [comment]
Ah, bummer, I didn't try out the new processor, but I will soonish and I can try to dig into it what's going on!

**Comment by mfrinnstrom** [comment]
I have always referenced using relative paths like in the example below so maybe adding a `./` before `models.yml` might work. This might not be a viable option for everybody though. I'm on vacation right now but I will see if I can get your example working.

```yaml
$ref: "../../schemas/Pets.yaml"
```
I have a full example here: https://github.com/mfrinnstrom/backstage-openapi-ref-example
Behind the scenes it is using the following library to do the bundling: https://www.npmjs.com/package/@apidevtools/swagger-parser

**Comment by mfrinnstrom** [comment]
@parnita-saha I took some time to look into this. It seems this error shows up when the referenced file can't be found. This leaves the reference in place and then the UI will fail to load that referenced file. I'm thinking you have verified the filename so a more likely scenario would be that the `catalog-info.yaml` and `openapi.yaml` files are not in the same folder.

I have added another example to my repo for this case: https://github.com/mfrinnstrom/backstage-openapi-ref-example/tree/main/basepath
I have always had both files in the same folder so I haven't tested this scenario. I tried to add a fix but that is not so easy it seems. 

I'm using `ScmIntegration.resolveUrl` to get the URL based on the relative path, `models.yaml` in this case. The only base URL to do this from in the processor is the `catalog-info.yaml` URL as far as I can tell. This means that all file references will be relative to the `catalog-info.yaml` file and not the `openapi.yaml` file unfortunately.
In my example the result from `resolveUrl` for `models.yaml` will be `https://github.com/mfrinnstrom/backstage-openapi-ref-example/tree/main/basepath/models.yaml` which doesn't exist.

The `$text` reference in `catalog-info.yaml` has already been resolved to the actual OpenAPI spec content so I can't do anything with that either. So if this is your case as well that is all the info I can give you right now unfortunately, put `catalog-info.yaml` and `openapi.yaml` in the same folder and it should work.

Maybe @freben or @Rugvip have some suggestions for how to get the relative path to the `openapi.yaml` file and I can add support for that to the processor.

**Comment by mfrinnstrom** [comment]
I opened https://github.com/backstage/backstage/pull/12814 that adds support for defining a base path from which all `$ref` instances will be resolved. This allows you to have the specification in a separate folder from the `catalog-info.yaml` file. My [example](https://github.com/mfrinnstrom/backstage-openapi-ref-example/tree/main/basepath) has been updated and works with this PR.

**Comment by parnita-saha** [comment]
Hi @mfrinnstrom Thanks a lot for all the details and information. It is really helpful. I tried your suggestions and few more scenarios with the API folder structure that we use in our organization.
I renamed the `models.yaml` and` openapi.yaml` to `models-ps.yaml.yaml` and `openapi-ps.yaml`  as most of our yaml files are named in this format. Unfortunately, I got the same error stating "**Resolver error at paths./vehicles/brands.get.responses.200.content.application/json.schema.$ref**".
Currently the API ref only worked when I removed "-ps" part from the name and moved all the yaml files catalog-info.yaml,  openapi.yaml, models.yml in under same directory. 
I am still trying to check few other structures that are failing in our project. I will keep you posted if we find more scenarios to reproduce the same issue.

**Comment by mfrinnstrom** [comment]
@parnita-saha thanks for the added information. Have you tried it with the PR code?

Adding `-ps` should be possible I believe. I'm mostly stitching together code from Backstage itself and the [@apidevtools/swagger-parser](https://www.npmjs.com/package/@apidevtools/swagger-parser) library to make this work.

I will try and add that as a case as well and see what happens.

**Comment by parnita-saha** [comment]
@mfrinnstrom I have not got a chance to check the code yet. I will take a look ASAP.

**Comment by mfrinnstrom** [comment]
@parnita-saha A new `$openapi` resolver was added in the [last release](https://github.com/backstage/backstage/blob/master/docs/releases/v1.5.0-changelog.md#backstageplugin-catalog-backend-module-openapi011). Maybe you can have a look at that and see if that solves your issues. It should support the use-case where the `catalog-info.yaml` and `openapi.yaml` files aren't in the same folder.

**Comment by parnita-saha** [comment]
@mfrinnstrom Apologies for the delayed response. I have upgraded our backstage to the latest release with your changes of $openapi . It has solved the reported issues 🥇 
1.  catalog-info.yaml and openapi.yaml files aren't in the same folder.
2. Having file names with "-xx.yaml".

Thanks a lot for helping with the issue.
