### ISSUE TITLE
Add support for disabling app-config validation at build time

### ISSUE THREAD

**Issue by SoccerBoyMalloy** [backstage/backstage#12701]
We're deploying Backstage to several k8s environments and we're using kustomize to define per-environment entrypoints that each include their own `app-config.<environment>.yaml` config files. In an effort to reduce duplicate configuration, we're consolidating all common configuration into `app-config.yaml` - this common config includes references to environment variables. Now when we `yarn build`, it validates `app-config.yaml` and throws an error if any of the environment variables are missing (which they often are at build time). This means we have to move any common configuration that relies on environment variables back into the environment-specific configs so that `app-config.yaml` has no environment variables, and then only specify `app-config.yaml` at build time.

This poses a few questions:
1. Is this build time validation necessary?
2. We currently don't specify our `app-config.<environment>.yaml` configs during build time and things seem to work - that means much of our config already isn't being validated at build time. _Should_ we be specifying them at build time?

## Feature Suggestion

Add some kind of `--disable-validation` flag at build time.

## Context

* The [build docs](https://backstage.io/docs/local-dev/cli-commands#repo-build) don't indicate this is possible.
* We might be able to handle this by [defining a custom schema](https://backstage.io/docs/conf/defining), but that feels like the wrong approach.

**Comment by benjdlambert** [comment]
Until we have some way of loading the config from the backend for the frontend, then this needs to be built into the bundle so it needs to be at build time. Think we need to revisit how we're going to do that rather than adding this option. Will come back with an update on a possible way forward! :pray:
