### ISSUE TITLE
Entity reference must not be empty

### ISSUE THREAD

**Issue by pieterv-icloud-com** [backstage/backstage#12750]
## Expected Behavior

I should be able to run a template

## Actual Behavior

Create process fails with:

```Backend request failed, 500 Internal Server Error {"error":{"name":"Error","message":"Entity reference must not be empty","level":"error","service":"backstage"},"request":{"method":"POST","url":"/api/scaffolder/v2/tasks"},"response":{"statusCode":500}} (1 older message)```

## Steps to Reproduce

1. Create...
2. Choose any Template
3. Fill in Form and click on Create

## Context

Using Developer Tools I can see the following request:

```{"templateRef":"template:default/docs-template","values":{"register":true,"name":"test1","title":"test1","ownerTeam":"oneiress/account-servicing"},"secrets":{}}```

Response is a 500:

```{"error":{"name":"Error","message":"Entity reference must not be empty","level":"error","service":"backstage"},"request":{"method":"POST","url":"/api/scaffolder/v2/tasks"},"response":{"statusCode":500}}```

Executing the same command with curl:

```curl -X POST http://localhost:8080/api/scaffolder/v2/tasks -H 'Content-Type: application/json' -d '{"templateRef":"template:default/docs-template","values":{"register":true,"name":"test1","title":"test1","ownerTeam":"oneiress/acurity-admin"},"secrets":{}}'``

results in a 200.

Stack trace in the log:

```error Entity reference must not be empty type=errorHandler stack=Error: Entity reference must not be empty
    at Object.parseEntityRef (/usr/src/app/node_modules/@backstage/catalog-model/dist/index.cjs.js:81:11)
    at /usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:3939:52
    at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at /usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7
    at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at /usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
    at jsonParser (/usr/src/app/node_modules/body-parser/lib/types/json.js:119:7)
    at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)```

## Your Environment

This started happening when upgrading from 1.2.1 to 1.3.0, currently testing on 1.4.0

- Browser Information: Chrome/103.0.0.0 Safari/537.36

- Output of `yarn backstage-cli info`: <!--- Paste into the code block below  -->

```
OS:   Linux 5.10.104-linuxkit - linux/arm64
node: v14.18.3
yarn: 1.22.19
cli:  0.18.0 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.4
  @backstage/backend-common                        0.14.1
  @backstage/backend-plugin-api                    0.1.0
  @backstage/backend-tasks                         0.3.3
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.0
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.4
  @backstage/core-components                       0.10.0
  @backstage/core-plugin-api                       1.0.4
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.2
  @backstage/integration                           1.2.2
  @backstage/plugin-api-docs                       0.8.7
  @backstage/plugin-app-backend                    0.3.34
  @backstage/plugin-auth-backend                   0.15.0
  @backstage/plugin-auth-node                      0.2.3
  @backstage/plugin-badges-backend                 0.1.28
  @backstage/plugin-badges                         0.2.31
  @backstage/plugin-catalog-backend-module-github  0.1.5
  @backstage/plugin-catalog-backend                1.3.0
  @backstage/plugin-catalog-common                 1.0.4
  @backstage/plugin-catalog-graph                  0.2.19
  @backstage/plugin-catalog-import                 0.8.10
  @backstage/plugin-catalog-node                   1.0.0
  @backstage/plugin-catalog-react                  1.1.2
  @backstage/plugin-catalog                        1.4.0
  @backstage/plugin-circleci                       0.3.7
  @backstage/plugin-cloudbuild                     0.3.7
  @backstage/plugin-cost-insights-common           0.1.0
  @backstage/plugin-cost-insights                  0.11.29
  @backstage/plugin-explore-react                  0.0.19
  @backstage/plugin-explore                        0.3.38
  @backstage/plugin-gcp-projects                   0.3.26
  @backstage/plugin-github-actions                 0.5.7
  @backstage/plugin-gitops-profiles                0.3.25
  @backstage/plugin-graphiql                       0.2.39
  @backstage/plugin-home                           0.4.23
  @backstage/plugin-jenkins-common                 0.1.6
  @backstage/plugin-jenkins                        0.7.6
  @backstage/plugin-kafka-backend                  0.2.27
  @backstage/plugin-kafka                          0.3.7
  @backstage/plugin-kubernetes-backend             0.7.0
  @backstage/plugin-kubernetes-common              0.4.0
  @backstage/plugin-kubernetes                     0.7.0
  @backstage/plugin-lighthouse                     0.3.7
  @backstage/plugin-newrelic                       0.3.25
  @backstage/plugin-org                            0.5.7
  @backstage/plugin-pagerduty                      0.5.0
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.3
  @backstage/plugin-permission-react               0.4.3
  @backstage/plugin-proxy-backend                  0.2.28
  @backstage/plugin-rollbar                        0.4.7
  @backstage/plugin-scaffolder-backend             1.4.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.4.0
  @backstage/plugin-search-backend-module-pg       0.3.5
  @backstage/plugin-search-backend-node            1.0.0
  @backstage/plugin-search-backend                 1.0.0
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.0
  @backstage/plugin-search                         1.0.0
  @backstage/plugin-sentry                         0.4.0
  @backstage/plugin-shortcuts                      0.2.8
  @backstage/plugin-sonarqube                      0.3.7
  @backstage/plugin-stack-overflow                 0.1.3
  @backstage/plugin-tech-radar                     0.5.14
  @backstage/plugin-techdocs-backend               1.2.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.2
  @backstage/plugin-techdocs-node                  1.2.0
  @backstage/plugin-techdocs-react                 1.0.2
  @backstage/plugin-techdocs                       1.3.0
  @backstage/plugin-todo-backend                   0.1.31
  @backstage/plugin-todo                           0.2.9
  @backstage/plugin-user-settings                  0.4.6
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 2.88s.
```

**Comment by benjdlambert** [comment]
Believe that this is a duplicate of https://github.com/backstage/backstage/issues/11666

**Comment by pieterv-icloud-com** [comment]
Thx for sending the issue.

**Comment by pieterv-icloud-com** [comment]
Deployed to AWS and not having the issue anymore.
