### ISSUE TITLE
Large Text not properly getting aligned in Tools Section in Home Page Plugin

### ISSUE THREAD

**Issue by vijayakumarbathini** [backstage/backstage#12751]
## Expected Behavior

If tool name length is big, text should be wrapped instead of using the same line. So spacing between tools looks good.

## Actual Behavior

The size of the tool is matching the name of the tool and loosing uniqueness in the section

## Steps to Reproduce

Add tool with name > 30 chars, so it can show the mismatched CSS

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```
<img width="946" alt="image" src="https://user-images.githubusercontent.com/7524183/179922618-2a62b8db-983a-4902-b427-6c36c7f67f27.png">

**Comment by theparthshukla** [comment]
Happy to take this up :)

**Comment by benjdlambert** [comment]
Go ahead @theparthshukla! Assigned to you!

**Comment by theparthshukla** [comment]
The issue can now be closed!

**Comment by benjdlambert** [comment]
Thanks again!
