### ISSUE TITLE
[RFC] Persistent Session Store

### ISSUE THREAD

**Issue by cloudy-dayzz** [backstage/backstage#12757]
**Status:** Open for comments
The intention behind this RFC is to attempt to solve issues when running backstage within kubernetes when authentication is provided by an OIDC provider or similar.

## Need
I am proposing this change as when pods are scaled above 1 inside of kubernetes, then a user would need to re-login to each pod as it has a session store stored in memory. 
This also stops the ability to upgrade the application without effecting consumers, as any restarts of pods would lead to users having to re-login.

## Proposal
The proposal is to move the session storage outside of the application itself, and allow for it to back off to a service like memcache, similar to how is reccomended here https://backstage.io/docs/overview/architecture-overview#cache. 
There are similar RFC's at https://github.com/backstage/backstage/issues/11160 // https://github.com/backstage/backstage/issues/8462. 

Te move to a server-side session storage rather than in-memory is commented as a TODO here: https://github.com/backstage/backstage/blob/a85d9fe831603bb82fcb6807236d8e9dd398d18e/plugins/auth-backend/src/service/router.ts#L70 

Another idea is allowing the pods to share a state using something like a pre-shared key between them.

## Alternatives
I have had success with enabling sticky sessions on the load balancer, however this does not get around the problem of pods being restarted for updates and users having to re-login.

I would also be interested to see what other people running this deployment inside of kubernetes do to get around this problem too.

**Comment by dublx** [comment]
+1

**Comment by NishkarshRaj** [comment]
Linking another open discussion by @cloudy-dayzz here:

https://github.com/backstage/backstage/discussions/12564

@freben @Rugvip @benjdlambert - Would love to hear your thoughts around HA and Scaling Backstage in a microservice architecture.

**Comment by Blackbaud-LeoWanderer** [comment]
I'm also having this same issue and I wonder if we can add a `sessionStore` field to the `RouterOptions` [here](https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/service/router.ts#L43) and use it [where the session is configured](https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/service/router.ts#L90). Doing so we can let people use any of the [compatible stores](https://expressjs.com/en/resources/middleware/session.html#compatible-session-stores). Would this be a reasonable approach?

**Comment by Rugvip** [comment]
@Blackbaud-LeoWanderer it could be a way forward. We also need to consider how it impacts the rest of the auth backend an how providers are supposed to interact with the session store.

I linked this from #15999 to highlight it a bit more

**Comment by headphonejames** [comment]
Is the [session](https://github.com/backstage/backstage/blob/0182d61b9802ac314bf67fab4896a151f88c4385/plugins/auth-backend/src/service/router.ts#L90) in auth-backend being used for anything currently? (beyond [being necessary for auth0](https://github.com/backstage/backstage/blob/0182d61b9802ac314bf67fab4896a151f88c4385/plugins/auth-backend/src/providers/auth0/provider.ts#L73)) Not seeing where data being put in the session, but I could be missing something. Thanks.

**Comment by freben** [comment]
Closed by #17569
