### ISSUE TITLE
[RFC] Better way of showing errors when using Scaffolder  (exception handling) 

### ISSUE THREAD

**Issue by mufaddal7** [backstage/backstage#12760]
**Status:** Open for comments

## Need

When the scaffolder is running a happy scenario everything works fine, but whenever the scaffolder is failing it throws general errors and logs, which is very confusing for end users. 

We need a clear display of errors when the scaffolder is performing the stack of actions. We can show it in a similar way to how it's shown in other backstage components. Eg Picture: 

![image](https://user-images.githubusercontent.com/42934221/180049145-16aac225-d73b-4665-a7c0-204a886d3aeb.png)

## Proposal

While scaffolding an error can come from multiple places, such as - 
- Custom actions
- Built-in actions
- Connectivity issues
- Authorization issues 
et Cetra. 
 
We can capture these errors in the `ActionContext` object and throw a user-friendly error, in a pop-up or an alert.

We can create a new property of type function inside `ActionContext` named `throwError` or `showAlert` or anything that the community suggests. So in every action, we fire the function whenever there is something going wrong  ``ctx.showAlert("GitHub - failed to find the repository")``

This can be achieved for all cases where we are getting an error returned from the API, even if we are not getting a definite error, we can still highlight to the user what part failed. 

I believe the logs are good, but showing errors neatly is a better way to keep users engaged. My solution is quite raw right now , but I hope i was able to convey the idea. 

**An example of how errors are shown currently** 

![image](https://user-images.githubusercontent.com/42934221/179927648-eb82af10-8a59-4c76-a3d2-c5db17747ef3.png)

**How it can be made more UX Friendly** 

![image](https://user-images.githubusercontent.com/42934221/179930625-db6f84b8-ef27-48e5-bc4a-bfb09c89cd6a.png)

**Comment by NishkarshRaj** [comment]
This is awesome and will add lots of value 💯

**Comment by mufaddal7** [comment]
@benjdlambert @Rugvip Please take a look

**Comment by benjdlambert** [comment]
@mufaddal7 @NishkarshRaj I wonder if this has crossover with #5848? Do either of you want to try and raise a PR moving us in a better direction? Otherwise I can maybe look at it part of #10430 big meta issue>?

**Comment by NishkarshRaj** [comment]
@benjdlambert yes we are interested in contributing this 💯

**Comment by mufaddal7** [comment]
Fixed #13522
