### ISSUE TITLE
Catalog 'Policy check failed' repeats without end

### ISSUE THREAD

**Issue by tonyhsuclrous** [backstage/backstage#12806]
## Expected Behavior

My App should not keep sending warning logs about Policy check failed on entities which do not exist anymore.
```
2022-07-23T02:33:48.665Z catalog warn Policy check failed; caused by Error: "metadata.namespace" is not valid; expected a string that is sequences of [a-z0-9] separated by [-], at most 63 characters in total but found "sdp.today". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md type=plugin entity=component:sdp.today/ingress
2022-07-23T02:33:55.666Z catalog warn Policy check failed; caused by Error: "metadata.namespace" is not valid; expected a string that is sequences of [a-z0-9] separated by [-], at most 63 characters in total but found "sdp.today". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md type=plugin entity=component:sdp.today/portal
2022-07-23T02:34:18.690Z catalog warn Policy check failed; caused by Error: "metadata.namespace" is not valid; expected a string that is sequences of [a-z0-9] separated by [-], at most 63 characters in total but found "sdp.today". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md type=plugin entity=resource:sdp.today/gke
2022-07-23T02:34:29.706Z catalog warn Policy check failed; caused by Error: "metadata.namespace" is not valid; expected a string that is sequences of [a-z0-9] separated by [-], at most 63 characters in total but found "sdp.today". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md type=plugin entity=resource:sdp.today/db
2022-07-23T02:34:30.583Z catalog warn Policy check failed; caused by Error: "metadata.namespace" is not valid; expected a string that is sequences of [a-z0-9] separated by [-], at most 63 characters in total but found "sdp.today". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md type=plugin entity=system:sdp.today/sdp
```

## Actual Behavior

My App keeps sending warning logs without end.

## Steps to Reproduce

1. Set the namespace of an entity with bad format.
2. Delete the location entity of the entity in step 1.
3. Warning logs on Policy check failed never ends.

## Context

Want to see a better surfacing and observability around processing loop errors as stated in the [Errors section](https://backstage.io/docs/features/software-catalog/life-of-an-entity#errors) of `The Life of an Entity`.

## Your Environment

- Browser Information: 
Google Chrome 103.0.5060.114
- Output of `yarn backstage-cli info`: 

```text
yarn run v1.22.19
$ /Users/tepisu/tmp/portal/node_modules/.bin/backstage-cli info
OS:   Darwin 21.5.0 - darwin/arm64
node: v16.15.1
yarn: 1.22.19
cli:  0.18.0 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.4
  @backstage/backend-common                        0.14.1
  @backstage/backend-plugin-api                    0.1.0
  @backstage/backend-tasks                         0.3.3
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.0
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.4
  @backstage/core-components                       0.10.0
  @backstage/core-plugin-api                       1.0.4
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.2
  @backstage/integration                           1.2.2
  @backstage/plugin-api-docs                       0.8.7
  @backstage/plugin-app-backend                    0.3.34
  @backstage/plugin-auth-backend                   0.15.0
  @backstage/plugin-auth-node                      0.2.3
  @backstage/plugin-catalog-backend-module-gitlab  0.1.5
  @backstage/plugin-catalog-backend                1.3.0
  @backstage/plugin-catalog-common                 1.0.4
  @backstage/plugin-catalog-graph                  0.2.19
  @backstage/plugin-catalog-import                 0.8.10
  @backstage/plugin-catalog-node                   1.0.0
  @backstage/plugin-catalog-react                  1.1.2
  @backstage/plugin-catalog                        1.4.0
  @backstage/plugin-github-actions                 0.5.7
  @backstage/plugin-kubernetes-backend             0.7.0
  @backstage/plugin-kubernetes-common              0.4.0
  @backstage/plugin-kubernetes                     0.7.0
  @backstage/plugin-org                            0.5.7
  @backstage/plugin-permission-backend             0.5.9
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.3
  @backstage/plugin-permission-react               0.4.3
  @backstage/plugin-proxy-backend                  0.2.28
  @backstage/plugin-scaffolder-backend             1.4.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.4.0
  @backstage/plugin-search-backend-module-pg       0.3.5
  @backstage/plugin-search-backend-node            1.0.0
  @backstage/plugin-search-backend                 1.0.0
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.0
  @backstage/plugin-search                         1.0.0
  @backstage/plugin-tech-radar                     0.5.14
  @backstage/plugin-techdocs-backend               1.2.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.2
  @backstage/plugin-techdocs-node                  1.2.0
  @backstage/plugin-techdocs-react                 1.0.2
  @backstage/plugin-techdocs                       1.3.0
  @backstage/plugin-user-settings                  0.4.6
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
✨  Done in 1.03s.
```

**Comment by benjdlambert** [comment]
Can you still see the entity the catalog?

**Comment by tonyhsuclrous** [comment]
No, the entity is under another namespace.

I will delete deleting the entity and observe the outcome.

**Comment by tonyhsuclrous** [comment]
Deleting the entity does not stop error logs show up every 2 minutes.

At the end of the log message we have `entity=component:sdp.today/ingress`, this entity should not exist at all.

**Comment by benjdlambert** [comment]
You'll most likely ned to delete the Location that it's emitting this entity. How did you add the location to Backstage in the first place? Did you add it under `Import`? or do you have `github-discovery` or something setup?

**Comment by tonyhsuclrous** [comment]
Yes, I have also remove the Location which spawn the entity.

I use the `Register an existing component` to add the location.

**Comment by benjdlambert** [comment]
Hmm, if you've removed the location entity from backstage using the UI then it should not longer be processed. Is it possible that this is another entity?

**Comment by tonyhsuclrous** [comment]
I have an alpha env which has the same issue.

I can remove everything and observe the outcome.

I need to make a plan. Will be back.

**Comment by tonyhsuclrous** [comment]
I have deleted all entities and checked `/api/catalog/entities`.
```
[]
```

The error logs keep showing up every 2 minutes.
```
2022-07-25T23:13:55.418Z catalog warn Policy check failed; caused by Error: "metadata.namespace" is not valid; expected a string that is sequences of [a-z0-9] separated by [-], at most 63 characters in total but found "sdp.today". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md type=plugin entity=component:sdp.today/portal
2022-07-25T23:16:04.468Z catalog warn Policy check failed; caused by Error: "metadata.namespace" is not valid; expected a string that is sequences of [a-z0-9] separated by [-], at most 63 characters in total but found "sdp.today". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md type=plugin entity=component:sdp.today/portal
```
Restart the server and the error logs still show up.

Something probably stuck in the pg database.

Is there a way to remove these errors from the database by hand?

**Comment by benjdlambert** [comment]
You can probably clean out the `refresh_state` table. I think that should drop any processing. As always, would recommend doing a backup though just in case, but if it's a test instance then go ahead.

**Comment by tonyhsuclrous** [comment]
After performing below commands on database `backstage_plugin_catalog`, the repeating error logs disappear.
```
select entity_ref from refresh_state where errors!='[]';

delete from refresh_state where errors!='[]';
```

Thank you for your help.

Closing this issue due to edge case.

**Comment by benjdlambert** [comment]
Perfect - glad this worked out for you, gonna tag in @freben in here anyways, as this could be a sign of something else not working as expected.

**Comment by marcus-crane** [comment]
@benjdlambert @freben Heya, I'll reply here for context rather than a full thread. One thing I've wrangled with using Backstage over the last 6 months is that the `refresh_state` table can often cause things to get "stuck".

One example is that we had some entities being read from an S3 bucket. Let's say I have an entity that was reading correctly at some point but then an issue was introduced so it's visible but there's also an entry in `refresh_state` awaiting a fix.

Now let's say I want to move an entity definition from that S3 bucket to a repo using the Github discovery provider.

I unregister the existing entity and then I go to import a catalog definition from Github and it says it's fine but when I try to import, I see the "This item is already registered, would you like to refresh" button.

"Ah, I forgot to remove the location" so I do that and still "This item is registered". As I found out recently, it's because a `refresh_state` entry is still held despite the source location being removed.

I believe over time, these seem to be cleaned up if the location is removed (or thereabouts since my fix is "I dunno, it magically fixes itself after a few hours/days") but removing the `refresh_state` entry appears to fully clean the slate, allowing the newly relocated entry to be importable.

Anyway, I dunno if there should be something like instantly deleting a location will clear out any relevant `refresh_state` entries but I figure it's something useful to add here as context since I only just got around to poke around the Backstage internals just recently 🙂

**Comment by gavinclarkeuk** [comment]
We've been hitting this issue as well. I'm not convinced it is an edge case so think we should consider reopening. It seems this will happen if a bad catalog manifest is checked in, then repaired. We're seeing examples where a component name has spaces in, then gets fixed. For these entities the location typically wouldn't get removed, so I don't think the issue will naturally resolve itself.

**Comment by gavinclarkeuk** [comment]
Having just investigated the `refresh_state` table it looks like this also impacts locations that have been deleted. Seems to me that when the refresh_state table is processed there should be a simple check to see if the `entity_ref` actually still exists in the catalog. If it doesn't then perhaps the `refresh_state` entry could just be deleted?

**Comment by nikolaik** [comment]
> Having just investigated the `refresh_state` table it looks like this also impacts locations that have been deleted. Seems to me that when the refresh_state table is processed there should be a simple check to see if the `entity_ref` actually still exists in the catalog. If it doesn't then perhaps the `refresh_state` entry could just be deleted?

Hit by exactly the same scenario that you are describing @gavinclarkeuk and the proposed solution seems reasonable. Should I open a separate issue requesting such a change?

**Comment by jrtaylorJH** [comment]
This should absolutely be reopened as a really common scenario.
