### ISSUE TITLE
Documentation for genPageTheme needs update for props argument

### ISSUE THREAD

**Issue by Pike** [backstage/backstage#12815]
## Expected Behavior

The docs in https://backstage.io/docs/getting-started/app-custom-theme#example-of-a-custom-theme should use an object argument

## Actual Behavior

The docs use two options for colors and shape.

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Context

I think this goes back to https://github.com/backstage/backstage/pull/10145, CC @awanlin 

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by awanlin** [comment]
@Pike, good catch, totally missed this with the other changes I made. Would you like to submit a PR to correct this? If not I can.

**Comment by benjdlambert** [comment]
I think I just merged #12863 which should fix this I believe?

**Comment by Pike** [comment]
Yes, thanks.
