### ISSUE TITLE
Slowness Using Entity Catalog with Large Number of Entities

### ISSUE THREAD

**Issue by iriswang233** [backstage/backstage#12829]
## Expected Behavior

Good user experience when using entity catalog with large number of entities, including

1.  fast response for catalog APIs
	- /catalog/entity-facets
        -  avoid fetching entire final_entities table
        -  avoid triggering requests after page resize
	-  /catalog/entities
        -  optimise db query
        -  improve search indexing
2.  same guide about how to configure entity catalog plugin particularly for large number of entities

## Actual Behavior

When user exploring entity catalog plugin, the following 2 APIs are frequently used with different parameters. In our case, some requests are quite slow.

1.  /catalog/entity-facets
- /catalog/entity-facets?facet=metadata.tags and /catalog/entity-facets?facet=kind

These 2 APIs are triggered every time loading entity catalog page. They are scanning entire final entity table and filter data in code. There is a similar feedback here [https://github.com/backstage/backstage/issues/12559](https://github.com/backstage/backstage/issues/12559). When explaining relate DB query, it took 300ms to complete.

        EXPLAIN (ANALYZE) select "final_entities".* from "final_entities" where "final_entities"."final_entity" is not null order by "entity_id" asc;
                                                                        QUERY PLAN                                                            

        ---------------------------------------------------------------------------------------------------------------------------------------------
        
         Gather Merge  (cost=25557.93..30024.71 rows=38284 width=1327) (actual time=167.122..323.097 rows=45964 loops=1)
        
           Workers Planned: 2
        
           Workers Launched: 2
        
           ->  Sort  (cost=24557.91..24605.76 rows=19142 width=1327) (actual time=156.960..202.071 rows=15321 loops=3)
        
                 Sort Key: entity_id
        
                 Sort Method: external merge  Disk: 17296kB
        
                 Worker 0:  Sort Method: external merge  Disk: 30280kB
        
                 Worker 1:  Sort Method: external merge  Disk: 12712kB
        
                 ->  Parallel Seq Scan on final_entities  (cost=0.00..12136.48 rows=19142 width=1327) (actual time=0.012..37.013 rows=15321 loops=3)
        
                       Filter: (final_entity IS NOT NULL)
        
                       Rows Removed by Filter: 317
        
         Planning Time: 0.065 ms
        
         Execution Time: 333.242 ms
        
        (13 rows)

- /catalog/entity-facets?filter=kind=component&facet=spec.type and /catalog/entity-facets?filter=kind=component&facet=metadata.tags

These 2 APIs are triggered every time loading and **resizing** entity catalog page. When explaining relate DB query, it took 60ms to complete. There was a comment about "The catalog APIs themselves will largely be kept focused at more manual browsing and filtering" and "We will be bringing in Elasticsearch to support search, but it will be done in a separate search system not directly tied to the catalog." here [https://github.com/backstage/backstage/issues/4961#issuecomment-802353692](https://github.com/backstage/backstage/issues/4961#issuecomment-802353692). Is there any update on this? Although catalog APIs is for browsing and filtering but its implementation is highly related to search. I am wondering is it possible to leverage other search approach to provide better search performance in catalog APIs?

     EXPLAIN (ANALYZE) select "final_entities".* from "final_entities" where ((((("entity_id" in (select "entity_id" from "search" where "key" = 'kind' and ("value" = 'component'))))))) and "final_entities"."final_entity" is not null order by "entity_id" asc;
                                                                               QUERY PLAN                                                            

        ---------------------------------------------------------------------------------------------------------------------------------------------------------------
        
         Sort  (cost=13261.02..13261.15 rows=49 width=1327) (actual time=59.862..60.985 rows=2862 loops=1)
        
           Sort Key: final_entities.entity_id
        
           Sort Method: external merge  Disk: 4048kB
        
           ->  Nested Loop  (cost=12841.92..13259.65 rows=49 width=1327) (actual time=25.270..46.127 rows=2862 loops=1)
        
                 ->  HashAggregate  (cost=12841.51..12842.01 rows=50 width=37) (actual time=25.241..25.968 rows=2862 loops=1)
        
                       Group Key: search.entity_id
        
                       ->  Bitmap Heap Scan on search  (cost=12642.66..12841.38 rows=50 width=37) (actual time=13.789..24.185 rows=2862 loops=1)
        
                             Recheck Cond: (((value)::text = 'component'::text) AND ((key)::text = 'kind'::text))
        
                             Heap Blocks: exact=2580
        
                             ->  BitmapAnd  (cost=12642.66..12642.66 rows=50 width=0) (actual time=13.356..13.358 rows=0 loops=1)
        
                                   ->  Bitmap Index Scan on search_value_idx  (cost=0.00..1013.09 rows=3271 width=0) (actual  time=0.869..0.869 rows=3264 loops=1)
        
                                         Index Cond: ((value)::text = 'component'::text)
        
                                   ->  Bitmap Index Scan on search_key_idx  (cost=0.00..11629.30 rows=41699 width=0) (actual  time=12.184..12.184 rows=46522 loops=1)
        
                                         Index Cond: ((key)::text = 'kind'::text)
        
                 ->  Index Scan using final_entities_entity_id_idx on final_entities  (cost=0.41..8.35 rows=1 width=1327) (actual  time=0.007..0.007 rows=1 loops=2862)
        
                       Index Cond: (entity_id = search.entity_id)
        
                       Filter: (final_entity IS NOT NULL)
        
         Planning Time: 0.660 ms
        
         Execution Time: 62.221 ms
        
        (19 rows)

        
2.  /catalog/entities
- /catalog/entities?filter=kind=component,spec.type=service

This API is triggered every time loading entity catalog page with 'service' type selected. When explaining relate DB query, it took 400ms to complete. Is it necessary to query both kind=component and spec.type=service condition? Seems the result for query both conditions and query spec.type=service alone is same. Or would there be other way to optimise it?
            
            EXPLAIN (ANALYZE) select "final_entities".* from "final_entities" where ((((("entity_id" in (select "entity_id" from "search" where "key" = 'kind' and ("value" = 'component')))) and (("entity_id" in (select "entity_id" from "search" where "key" = 'spec.type' and ("value" = 'service'))))))) and "final_entities"."final_entity" is not null order by "entity_id" asc;
                                                                                        QUERY PLAN                                                                             
            --------------------------------------------------------------------------------------------------------------------------------------------------------------------
            
             Sort  (cost=1466.86..1466.86 rows=1 width=1327) (actual time=411.529..411.594 rows=884 loops=1)
            
               Sort Key: final_entities.entity_id
            
               Sort Method: quicksort  Memory: 1691kB
            
               ->  Nested Loop Semi Join  (cost=1454.79..1466.85 rows=1 width=1327) (actual time=2.382..409.275 rows=884 loops=1)
            
                     Join Filter: (final_entities.entity_id = search.entity_id)
            
                     ->  Nested Loop  (cost=334.53..342.56 rows=1 width=1364) (actual time=1.735..11.049 rows=884 loops=1)
            
                           ->  HashAggregate  (cost=334.12..334.13 rows=1 width=37) (actual time=1.716..2.311 rows=884 loops=1)
            
                                 Group Key: search_1.entity_id
            
                                 ->  Index Scan using search_value_idx on search search_1  (cost=0.56..334.11 rows=1 width=37) (actual time=0.032..1.470 rows=884 loops=1)
            
                                       Index Cond: ((value)::text = 'service'::text)
            
                                       Filter: ((key)::text = 'spec.type'::text)
            
                                       Rows Removed by Filter: 41
            
                           ->  Index Scan using final_entities_entity_id_idx on final_entities  (cost=0.41..8.43 rows=1 width=1327) (actual time=0.009..0.009 rows=1 loops=884)
            
                                 Index Cond: (entity_id = search_1.entity_id)
            
                                 Filter: (final_entity IS NOT NULL)
            
                     ->  Bitmap Heap Scan on search  (cost=1120.26..1124.28 rows=1 width=37) (actual time=0.447..0.447 rows=1 loops=884)
            
                           Recheck Cond: ((entity_id = search_1.entity_id) AND ((value)::text = 'component'::text))
            
                           Filter: ((key)::text = 'kind'::text)
            
                           Heap Blocks: exact=884
            
                           ->  BitmapAnd  (cost=1120.26..1120.26 rows=1 width=0) (actual time=0.444..0.444 rows=0 loops=884)
            
                                 ->  Bitmap Index Scan on search_entity_id_idx  (cost=0.00..106.91 rows=314 width=0) (actual time=0.027..0.027 rows=51 loops=884)
            
                                       Index Cond: (entity_id = search_1.entity_id)
            
                                 ->  Bitmap Index Scan on search_value_idx  (cost=0.00..1013.09 rows=3271 width=0) (actual time=0.415..0.415 rows=3268 loops=884)
            
                                       Index Cond: ((value)::text = 'component'::text)
            
             Planning Time: 0.473 ms
            
             Execution Time: 411.671 ms
            
            (26 rows)
            
- /catalog/entities?filter=kind=api,metadata.namespace=default,metadata.name=value1,metadata.name=value2  

This API is triggered every time click API tab from service page. When explaining relate DB query, it took 80ms to complete. Every filter will add 1 query to search table in the entire query string. Is it possible to optimise it in db queries or search indexing to support some common combination like kind_api_namespace_default_metadata_name? Or would there be other way to optimise it?
            
            EXPLAIN (ANALYZE) select "final_entities".* from "final_entities" where ((((("entity_id" in (select "entity_id" from "search" where "key" = 'kind' and ("value" = 'api')))) and (("entity_id" in (select "entity_id" from "search" where "key" = 'metadata.namespace' and ("value" = 'default')))) and (("entity_id" in (select "entity_id" from "search" where "key" = 'metadata.name' and ("value" in ('value1', 'value2')))))))) and "final_entities"."final_entity" is not null order by "entity_id" asc;
                                                                                          QUERY PLAN                                                                                 
            ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
            
             Sort  (cost=1817.80..1817.81 rows=1 width=1327) (actual time=88.564..88.567 rows=2 loops=1)
            
               Sort Key: final_entities.entity_id
            
               Sort Method: quicksort  Memory: 25kB
            
               ->  Nested Loop Semi Join  (cost=576.15..1817.79 rows=1 width=1327) (actual time=21.122..88.557 rows=2 loops=1)
            
                     ->  Nested Loop Semi Join  (cost=441.44..1679.06 rows=1 width=1401) (actual time=5.753..53.074 rows=1354 loops=1)
            
                           Join Filter: (final_entities.entity_id = search_1.entity_id)
            
                           ->  Nested Loop  (cost=334.53..342.56 rows=1 width=1364) (actual time=5.722..17.449 rows=1354 loops=1)
            
                                 ->  HashAggregate  (cost=334.12..334.13 rows=1 width=37) (actual time=5.700..6.143 rows=1354 loops=1)
            
                                       Group Key: search.entity_id
            
                                       ->  Index Scan using search_value_idx on search  (cost=0.56..334.11 rows=1 width=37) (actual time=0.030..5.260 rows=1354 loops=1)
            
                                             Index Cond: ((value)::text = 'api'::text)
            
                                             Filter: ((key)::text = 'kind'::text)
            
                                 ->  Index Scan using final_entities_entity_id_idx on final_entities  (cost=0.41..8.43 rows=1 width=1327) (actual time=0.008..0.008 rows=1 loops=1354)
            
                                       Index Cond: (entity_id = search.entity_id)
            
                                       Filter: (final_entity IS NOT NULL)
            
                           ->  Bitmap Heap Scan on search search_1  (cost=106.91..1336.49 rows=1 width=37) (actual time=0.025..0.025 rows=1 loops=1354)
            
                                 Recheck Cond: (entity_id = search.entity_id)
            
                                 Filter: (((key)::text = 'metadata.namespace'::text) AND ((value)::text = 'default'::text))
            
                                 Rows Removed by Filter: 12
            
                                 Heap Blocks: exact=2064
            
                                 ->  Bitmap Index Scan on search_entity_id_idx  (cost=0.00..106.91 rows=314 width=0) (actual time=0.015..0.015 rows=16 loops=1354)
            
                                       Index Cond: (entity_id = search.entity_id)
            
                     ->  Bitmap Heap Scan on search search_2  (cost=134.71..138.73 rows=1 width=37) (actual time=0.025..0.025 rows=0 loops=1354)
            
                           Recheck Cond: (((value)::text = ANY ('{value1,value2}'::text[])) AND (entity_id = final_entities.entity_id))
            
                           Filter: ((key)::text = 'metadata.name'::text)
            
                           Heap Blocks: exact=2
            
                           ->  BitmapAnd  (cost=134.71..134.71 rows=1 width=0) (actual time=0.023..0.023 rows=0 loops=1354)
            
                                 ->  Bitmap Index Scan on search_value_idx  (cost=0.00..50.28 rows=157 width=0) (actual time=0.014..0.014 rows=4 loops=1354)
            
                                       Index Cond: ((value)::text = ANY ('{value1,value2}'::text[]))
            
                                 ->  Bitmap Index Scan on search_entity_id_idx  (cost=0.00..84.18 rows=314 width=0) (actual time=0.008..0.008 rows=16 loops=1354)
            
                                       Index Cond: (entity_id = final_entities.entity_id)
            
             Planning Time: 0.770 ms
            
             Execution Time: 88.634 ms
            
            (33 rows)
            

## Steps to Reproduce

1.  Have 40k entities in db
2.  Inspect Network in the page and observe requests triggered
3.  Navigate to entity catalog page
4.  Change page size
5.  Select "service" type
6.  Click 1 service
7.  Navigate API tab
8.  Click 1 API
9.  Click the owner in API page
10.  Click the engineer lead in owner page
11.  Explain mentioned db queries in db to check execution time

## Context

My team is a big fan of entity catalog. As more and more entities onboarded, we are happy that the number reaches 40k and will continue increasing. Meanwhile, our user experiences slowness using the entity catalog plugin. After seeing several similar issues post in github and backstage are gaining more and more popularity, I am wondering is there a guide or any advice about using entity catalog with large number of entities or a plan to optimise the performance for entity catalog plugin.

## Your Environment

-   DB Information:

postgres:12.8

-   Browser Information:
    

Google Chrome

Version 103.0.5060.134 (Official Build) (x86_64)

-   Output of `yarn backstage-cli info`:
    

yarn backstage-cli info  
yarn run v1.22.18  
$ /Users/yuqi.wang/Documents/repo/helix/node_modules/.bin/backstage-cli info  
OS: Darwin 21.6.0 - darwin/x64  
node: v16.14.2  
yarn: 1.22.18  
cli: 0.17.1 (installed)

Dependencies:  
@backstage/app-defaults 1.0.3  
@backstage/backend-common 0.14.0  
@backstage/backend-tasks 0.3.2  
@backstage/catalog-client 1.0.3  
@backstage/catalog-model 1.0.3  
@backstage/cli-common 0.1.9  
@backstage/cli 0.17.2  
@backstage/config-loader 1.1.2  
@backstage/config 1.0.1  
@backstage/core-app-api 1.0.3  
@backstage/core-components 0.9.5  
@backstage/core-plugin-api 1.0.3  
@backstage/errors 1.0.0  
@backstage/integration-react 1.1.1  
@backstage/integration 1.2.1  
@backstage/plugin-analytics-module-ga 0.1.17  
@backstage/plugin-api-docs 0.8.6  
@backstage/plugin-app-backend 0.3.33  
@backstage/plugin-auth-backend 0.14.1  
@backstage/plugin-auth-node 0.2.2  
@backstage/plugin-catalog-backend-module-gitlab 0.1.4  
@backstage/plugin-catalog-backend-module-ldap 0.5.0  
@backstage/plugin-catalog-backend 1.2.0  
@backstage/plugin-catalog-common 1.0.3  
@backstage/plugin-catalog-graph 0.2.18  
@backstage/plugin-catalog-import 0.8.9  
@backstage/plugin-catalog-react 1.1.1  
@backstage/plugin-catalog 1.3.0  
@backstage/plugin-explore-react 0.0.18  
@backstage/plugin-explore 0.3.37  
@backstage/plugin-home 0.4.22  
@backstage/plugin-kubernetes-backend 0.6.0  
@backstage/plugin-kubernetes-common 0.3.0  
@backstage/plugin-kubernetes 0.6.6  
@backstage/plugin-org 0.5.6  
@backstage/plugin-pagerduty 0.4.0  
@backstage/plugin-permission-common 0.6.2  
@backstage/plugin-permission-node 0.6.2  
@backstage/plugin-permission-react 0.4.2  
@backstage/plugin-proxy-backend 0.2.27  
@backstage/plugin-scaffolder-backend 1.3.0  
@backstage/plugin-scaffolder-common 1.1.1  
@backstage/plugin-scaffolder 1.3.0  
@backstage/plugin-search-backend-module-pg 0.3.4  
@backstage/plugin-search-backend-node 0.6.2  
@backstage/plugin-search-backend 0.5.3  
@backstage/plugin-search-common 0.3.5  
@backstage/plugin-search-react 0.2.1  
@backstage/plugin-search 0.9.0  
@backstage/plugin-shortcuts 0.2.7  
@backstage/plugin-stack-overflow 0.1.2  
@backstage/plugin-tech-radar 0.5.13  
@backstage/plugin-techdocs-backend 1.1.2  
@backstage/plugin-techdocs-module-addons-contrib 1.0.1  
@backstage/plugin-techdocs-node 1.1.2  
@backstage/plugin-techdocs-react 1.0.1  
@backstage/plugin-techdocs 1.2.0  
@backstage/plugin-user-settings 0.4.5  
@backstage/release-manifests 0.0.4  
@backstage/test-utils 1.1.1  
@backstage/theme 0.2.15  
@backstage/types 1.0.0  
@backstage/version-bridge 1.0.1  
✨ Done in 0.68s.

**Comment by benjdlambert** [comment]
Hey :wave:

First off, thanks so much for digging into this and providing some useful numbers. This is going to be great for reference.

Secondly, we're on it. We know it's pretty slow right now, and not only the queries server side, it's also the frontend experience.

We're working on #12246 which is part of a larger piece of work to make the frontend behave better with many items in the catalog and overall improve the experience.

I'd like to keep this ticket open, and then we discuss after we've made some of the planned changes and see what we can do more in this area. Does that sound OK? :pray:

**Comment by iriswang233** [comment]
Hi,
Thanks for your reply! It's great to know that the pagination will come out soon. It will definitely help improve the performance of browsing with pagination. We will assess the performance about browsing, searching and filtering again with this change once it releases.

And how about the /catalog/entity-facets API, it's used to show available filters. Is there a plan to get rid of fetching all entities? It will affect the user experience about filtering entities as the entities increasing.

**Comment by benjdlambert** [comment]
Maybe @vinzscam can elaborate a little more, I know we spoke about the facets API, but not sure what the plan was for it for the new entities API and pagination.

**Comment by vinzscam** [comment]
Hi! Thanks for this @iriswang233!
Yes, some filters uses the facets endpoint for fetching data. The plan is to revisit the facets endpoint as well in the future, but I can ensure it isn't the main issue at this point.
Maybe I could share my WIP branch. The work you've done is fantastic and it would be interesting to reassess the performance of the new catalog implementation with your catalog.

**Comment by iriswang233** [comment]
Hi @vinzscam,

Yes. It would be good to revisit the facets endpoint. For us, it takes long time and sometimes fails to load the Type filter, but user can refresh the page to get it show. 
<img width="554" alt="Screenshot 2022-08-02 at 1 59 11 PM" src="https://user-images.githubusercontent.com/49713904/182302713-13cfeddf-a3cb-4387-a881-52484e94d1a1.png">
<img width="279" alt="Screenshot 2022-08-02 at 2 00 35 PM" src="https://user-images.githubusercontent.com/49713904/182302798-a7b99600-a890-4646-9276-c8ccdcba7308.png">

**Comment by iriswang233** [comment]
Hi team, is there any update about facets endpoints. It now sometimes takes more than 10s and fails with statement timeout.  So user can't select the components dropdown
<img width="384" alt="image (44)" src="https://user-images.githubusercontent.com/49713904/203252251-67d5163c-34ae-4f96-8ce8-b481c85bb155.png">

Maybe it's possible to have some cache to return cached result if current request failed. At least the function is still ok with outdated data.

**Comment by jhaals** [comment]
Hi! This is in progress here #14230

**Comment by riginoommen** [comment]
Request to reopen this issue

**Comment by ypetrych** [comment]
Hi, we have 4k entities in our Backstage. The number will grow and we already face the issues with slow performance trying to filter it (e.g. choosing some owner). Do you have any plans to optimise it for such cases? Thank you
