### ISSUE TITLE
Icons for entry types in search

### ISSUE THREAD

**Issue by viraptor** [backstage/backstage#12876]
## Feature Suggestion

Currently the quick search provides all search results in the same way. A document heading, a component, a system, etc. will all appear the same way (with possible extra text for documentation)

It would be great if I could tell at a glance what entry is what type.

This is mainly for the initial/quick search, however the full view uses pill buttons with very contrasting colours to annotate the "Kind". Maybe an icon + more discrete text there could make it a bit easier to skim?

## Possible Implementation

I'm thinking of including an icon before the entry, matching the icons in the dependency graph, so components, systems, etc. get a familiar look.

I'm not saying that AWS icons are particularly easy to recognise :) , but here's an example of their search:

<img width="904" alt="Screen Shot 2022-07-28 at 10 09 21 pm" src="https://user-images.githubusercontent.com/188063/181501440-5961937b-23ea-471e-8fcd-9d6c849df5ba.png">

Here's github's context search:

<img width="394" alt="Screen Shot 2022-07-28 at 10 12 39 pm" src="https://user-images.githubusercontent.com/188063/181502053-52a7dc11-b4e1-4bf6-95ac-2233bb177b15.png">

## Context

With lots of entries it's hard to tell what each of them corresponds to.

**Comment by garyniemen** [comment]
@viraptor did the above help you solve your problem?

**Comment by emmaindal** [comment]
I'll close this issue, feel free to open it again @viraptor if you don't think the suggestion above can help you solve the problem.
