### ISSUE TITLE
Support custom configuration for Webpack

### ISSUE THREAD

**Issue by SathishKumar140** [backstage/backstage#12893]
## Possible Implementation
Provide an option or refer a file in the root level of the project to read Webpack configuration and override existing configuration which default comes from backstage. 

## Context
Currently, backstage create a Webpack configuration to build the app. If there is a use case or library in which use the extension **.json** and it failed with a compile error. If provided with override the configuration specific to their needs will be helpful.

**Comment by benjdlambert** [comment]
Hey, this issue might be worth a read with some more context as to why we're probably not likely to do this: https://github.com/backstage/backstage/issues/7102

**Comment by SathishKumar140** [comment]
@benjdlambert I have gone through it but if there is an internal library/package that we are trying to use in my custom plugin and it compiles as part of the backstage app and it throws an error how to solve this case?

As I mentioned above **.json** file should be resolved as an extension and the backstage Webpack config should accept it. Is there any solution available to it?

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/4860919/182057297-95aa3077-501e-4d2c-8b68-1b92c8a4b738.png">

**Comment by benjdlambert** [comment]
It looks like the path for the import is wrong is all. I'm guessing the prefix doesn't work. Or maybe you have to include the `.json` extension but not sure. How is the import included?

**Comment by SathishKumar140** [comment]
@benjdlambert 
Path is correct and it's part of the package the import is used. We installed a similar package is installed in another project in our organization working without any issue. 
If we use the same package on backstage dependency not working and build failed with errors. I think the reason for not working is an extensions is not accepting from the Webpack file resolve **.json**, if we have a configuration for Webpack to override/add options as flexible will help here.

**Comment by benjdlambert** [comment]
Does it work if in your other package you don't rely on it resolving to `.json` automatically, and actually change the import to `loading.json` instead?

**Comment by benjdlambert** [comment]
I'm just trying to understand if it is as simple as adding the `resolveExtensions` or not. The node resolution should automatically work this stuff out as `.json` is a valid extension. Maybe come up with a PR and adding the extension and try it out to see if it works, and if it does raise a PR? :pray:

**Comment by Rugvip** [comment]
Ended up with #13022, since we're not aligned with the default webpack config atm

**Comment by Rugvip** [comment]
Closing as #13022 is merged

**Comment by SathishKumar140** [comment]
Thanks @Rugvip it will work
