### ISSUE TITLE
No Errors in logs when PAT expires using AzureDevOpsEntityProvider

### ISSUE THREAD

**Issue by blueboxes** [backstage/backstage#12899]
## Expected Behavior

When it cannot get data from Azure DevOps I would expect errors in logs. This happens with the AzureDevOpsDiscoveryProcessor.

## Actual Behavior

It silently fails and the catalog is not updated. Even setting the logging level to debug shows no errors.

## Steps to Reproduce

1. Use an expired PAT or one that doe snot have the correct access to read.   
1. Run Backstage  
1. Look at logs  

## Context

One day all the content disappeared from backstage (we are using in-memory DB, yet to move the real db) due to an issue with the token.

**Comment by blueboxes** [comment]
@goenning you may have an idea on this

**Comment by goenning** [comment]
I'm not sure tbh, but if there's an exception happening inside the call to Search API, I'd expect the outer functions to catch that and log It so at least it doesn't go completely silent.
