### ISSUE TITLE
[Scaffolder] Ability to modify the layout of the step form

### ISSUE THREAD

**Issue by taras** [backstage/backstage#12909]
## Context

One of our clients would like to be able to modify the layout of the form in a step. They would like to be able to show fields in two columns instead of one column. This can be accomplished by modifying props passed to the Grid component in [ObjectFieldTemplate](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/ObjectFieldTemplate/ObjectFieldTemplate.tsx#L31). RJSF provides an API for [changing the ObjectTemplate via uiSchema](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-templates/#objectfieldtemplate). Unfortunately, this API is not available in the scaffolder because there is no way to pass a component to [`transformSchemaToProps`](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/MultistepJsonForm/schema.ts#L109).  

## Feature Suggestion

Provide some mechanism to control the layout that's used by a step. 

## Possible Implementation

There are a few different ways that could be accomplished.

1. Provide several predefined layouts that can be configured for a specific step. For example,

```diff
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide some simple information
+     layout: 2-column
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
```

2. Allow defining custom templates

Alternatively, we could expose a new API for defining new templates. Similar to field extensions but for Object & Array templates. (I'm not sure if array templates are currently being used)

**Comment by benjdlambert** [comment]
Hmm I wonder if we can do something like `CustomFieldExtensions` and have this a component that you can provide?

`ui:layout` or something, and having `CustomLayoutRenderers` or something. Naming is TBD. haha

**Comment by taras** [comment]
A combination of these things, if you're open to a PR, I can get one of our devs to create it.

**Comment by benjdlambert** [comment]
Yeah draft up a PR, and let's continue the discussion there!

**Comment by taras** [comment]
@benjdlambert, @dagda1 submitted a PR with our first pass at this functionality. Please, let us know what we missed. Once the implementation is mergable, we'll update the docs to explain the new API.

**Comment by benjdlambert** [comment]
Thanks again @dagda1!
