### ISSUE TITLE
[Scarffolder] Creation from template breaks after updating from 1.1.1 to 1.2.0 (cloud hosted)

### ISSUE THREAD

**Issue by RemiVR** [backstage/backstage#12939]
## Expected Behavior

The template steps should be executed.

## Actual Behavior

After updating to version 1.2.0 from 1.1.1, when all the input fields have been filled in the template and click to create a new service from a template returns the following error: 
`Backend request failed, 500 Internal Server Error {"error":{"name":"Error","message":"Entity reference \"7508ac48-5c49-4137-85db-3174ff249f6a\" had missing or empty kind (e.g. did not start with \"component:\" or similar)","level":"error","service":"backstage"},"request":{"method":"POST","url":"/api/scaffolder/v2/tasks"},"response":{"statusCode":500}}`

After looking into it more, I found that backstage returns this error.

![template-error](https://user-images.githubusercontent.com/10207054/182160016-10cd6f97-0203-462d-ba06-8a0e7187a099.png)

Locally it's working fine, only the production build is throwing an error.

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

Dependencies:
  @backstage/app-defaults                          1.0.4
  @backstage/backend-common                        0.13.5
  @backstage/backend-plugin-api                    0.1.0
  @backstage/backend-tasks                         0.3.3
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.17.2
  @backstage/config-loader                         1.1.3
  @backstage/config                                0.1.15, 1.0.1
  @backstage/core-api                              0.2.23
  @backstage/core-app-api                          1.0.4
  @backstage/core-components                       0.10.0, 0.9.5
  @backstage/core-plugin-api                       0.1.13, 1.0.4
  @backstage/core                                  0.7.14
  @backstage/dev-utils                             1.0.4
  @backstage/errors                                1.1.0, 0.1.5
  @backstage/integration-react                     1.1.2
  @backstage/integration                           1.2.2
  @backstage/plugin-analytics-module-ga            0.1.18
  @backstage/plugin-api-docs                       0.8.7
  @backstage/plugin-app-backend                    0.3.34
  @backstage/plugin-auth-backend                   0.14.1
  @backstage/plugin-auth-node                      0.2.3
  @backstage/plugin-catalog-backend-module-github  0.1.5
  @backstage/plugin-catalog-backend                1.3.0
  @backstage/plugin-catalog-common                 1.0.4
  @backstage/plugin-catalog-graph                  0.2.19
  @backstage/plugin-catalog-import                 0.8.10
  @backstage/plugin-catalog-node                   1.0.0
  @backstage/plugin-catalog-react                  1.1.2
  @backstage/plugin-catalog                        1.4.0
  @backstage/plugin-circleci                       0.3.7
  @backstage/plugin-github-actions                 0.5.7
  @backstage/plugin-home                           0.4.23
  @backstage/plugin-kubernetes-backend             0.7.0
  @backstage/plugin-kubernetes-common              0.4.0
  @backstage/plugin-kubernetes                     0.7.0
  @backstage/plugin-org                            0.5.7
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.3
  @backstage/plugin-permission-react               0.4.3
  @backstage/plugin-proxy-backend                  0.2.28
  @backstage/plugin-scaffolder-backend             1.4.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.4.0
  @backstage/plugin-search-backend-module-pg       0.3.5
  @backstage/plugin-search-backend-node            0.6.2, 1.0.0
  @backstage/plugin-search-backend                 0.5.3
  @backstage/plugin-search-common                  0.3.5, 1.0.0
  @backstage/plugin-search-react                   0.2.1, 1.0.0
  @backstage/plugin-search                         0.8.1
  @backstage/plugin-sonarqube                      0.3.7
  @backstage/plugin-stack-overflow                 0.1.3
  @backstage/plugin-tech-radar                     0.5.14
  @backstage/plugin-techdocs-backend               1.2.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.2
  @backstage/plugin-techdocs-node                  1.2.0
  @backstage/plugin-techdocs-react                 1.0.2
  @backstage/plugin-techdocs                       1.3.0
  @backstage/plugin-user-settings                  0.4.6
  @backstage/release-manifests                     0.0.4
  @backstage/test-utils                            1.1.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 0.1.3, 1.0.0
  @backstage/version-bridge                        0.1.2, 1.0.1

```text

```

**Comment by benjdlambert** [comment]
Hey :wave: This could be down to the fact that the token that is in the `Authorization` header is not a valid Backstage Token. Granted if this happens, it shouldn't throw unless permissions are restricted to users but I believe this is what is happening.

**Comment by RemiVR** [comment]
This is a duplicate of #11666.
