### ISSUE TITLE
Not able to fetch Shell script file containing ${#} | Reads as end of comment expected got end of file.

### ISSUE THREAD

**Issue by HorcruxAshu** [backstage/backstage#12972]
## Expected Behavior

My contents directory contains a shell script file that has a line to calculate the length of the array as ${#Array[@]}.
My template directory tries to fetch it. It should be able to able to fetch this.
## Actual Behavior
When it tries to fetch the content directory. It throws an error while trying to fetch the Shell Script from the content directory says, "Expected end of comment, got end of file"

## Steps to Reproduce
1. Include a shell script file in the content directory that is calculating an array length using ${#Array[@]}
2. Try to fetch this content directory in the template.yaml
3. Run yarn dev and create component and then create repository. It throws error in fetch-base.
. 

## Your Environment

- Browser Information: Chrome Browser

```text

```

**Comment by Rugvip** [comment]
Are you using the most recent version of the scaffolder and templating action? The templating syntax uses `${{ ... }}` now to avoid this somewhat common collision.

It should also be possible to escape the substitution, use `fetch:plain` to avoid templating altogether, or use the `copyWithoutTemplating` option to avoid templating certain files.
