### ISSUE TITLE
[RFC] Re-Scaffolding (providing a way to consume the latest template upgrades in easy manner)

### ISSUE THREAD

**Issue by Abhay-soni-developer** [backstage/backstage#12985]
**Status:** Open for comments

We want the consumer to be able to consume the new updated template version which he used to scaffold the current repo.

## Need

currently, once the user creates a repo using any template and later down the line if the particular template is updated. he is not able to consume this template automatically and he has to do manual changes to sync with the latest updates template. so to solve this we want to give him the functionality to consume the latest template with a lot less hassle.

## Proposal

![suggested template update flowchart](https://user-images.githubusercontent.com/23618736/183059060-29401791-70c9-484b-94ce-147e9cf5a438.png)

## Explanation

1) User clicks over create button over any template.
2) The user enters the repo name, then the system verifies if a repo with the same name already exists or not in the targeted account.
3) If the step number 2 replies with repo do not exist. then we will simply create a new repo with the current template same as we do currently.
4) If step number 2 yields that a repo with the same name already exists, then we fetch the old form data that was used the built the repo.
5) Users can now change and fill new data fields if any required.
6) user clicks over the create_pull_request button and a pull request would be generated in the targeted repo with the new template.

## Alternatives

Open to a better alternative solution for the current pointed issue.

**Comment by Abhay-soni-developer** [comment]
@NishkarshRaj  @Ahampa07

**Comment by NishkarshRaj** [comment]
@benjdlambert @freben @Rugvip - it is a custom action we are creating for our team. 

We are happy to contribute this after hearing your thoughts to make it abstract and valuable for everyone 💯

**Comment by benjdlambert** [comment]
Hey :wave: So this request has popped up a few times in some other places, and I think right now we're thinking that this is possibly not something that is a responsibility of the scaffolder. Internally at Spotify, we treat these things differently, as you maybe don't want to upgrade the entire base template up at the same time as that's pretty risky depending on what has changed, you might want to raise a PR to bump things a little more granularly, like let's say a dependency in a `package.json` or something, and you might want to roll that out for all your components. It's not to say that this might not be powered by the scaffolder backend however. 

How it works internally is that we can run codemods against a large amount of repositories, and then raise PR's back to the original repository with the small changes in there for review and merge. The idea here is that they don't have to be based off any initial template either, it's a little unforuntate to require that all the things that get the upgrades were based off a particular template too. I want to be able to bump `log4j` everywhere, not just things that were created with the Java template for instance.

We might get to a point where we can open source our stuff, but realistically that's a long way off. But the concept is pretty simple, take a repository, run a codemod or upgrade thing, and raise a PR back to the repo.

Just a little bit of brain dump here to be honest, see what your thoughts are.
