### ISSUE TITLE
Backstage - check sub-folders

### ISSUE THREAD

**Issue by JosefBocan** [backstage/backstage#12996]
## Feature Suggestion
I didnt find a solution if we are storing more catalog-info.yml files in one repo and we want to have them all scaned by backstage. 

Is there a way or not I found a topic there that it should work on github but we have a gitlab. Can you help me or implement it :* 
https://roadie.io/changelog/non-standard-metadata-support/

Please help me with that :) 

## Context
the reason is monorepos because I would like to catalog infos to be created automaticaly and I didnt find the way how to do it in a good git flow or via anything else. I will be glad if you will be able to help me with that. :peace_symbol:  thx

**Comment by anicke** [comment]
Check out https://roadie.io/blog/backstage-monorepo-guide/

**Comment by JosefBocan** [comment]
You best thats the manual what I was looking for. Its a pitty that you dont have it in docu. May I create the contribution commit to add it to your manual? If I will be able to do it :D
