### ISSUE TITLE
Scaffolding EntityPicker with default namespace in values

### ISSUE THREAD

**Issue by tunkl** [backstage/backstage#12990]
## Feature Suggestion

We would like to have option which would modify behaviour of EntityPicker which would not skip default namespace, and wrote it into result every time. 

## Possible Implementation

I am proposing two changes how to achieve this:
1) Modify plugins/catalog-react/src/components/EntityRefLink/humanize.ts to accept optional parameter which would disable skip of default namespace.

2) Modify scaffolding EntityPicker to pass new optional parameter which would disable skip of default namespace here: https://github.com/backstage/backstage/blob/60ac7f3ad7832c6a5b417c4cea6e4a778ca4d081/plugins/scaffolder/src/components/fields/EntityPicker/EntityPicker.tsx#L70

## Context

We are using namespaces for all of our Entities, this forces us to define default namespace in every reference to Entity. 

We are also using scaffolding to make it easy for our developers to onboard into backstage, so we have prepared templates for different Entities. Users are walking through scaffolding process and selecting values for their Entity. For some fields we are using EntityPicker which loads entities from backstage and conveniently displays them to the user.

Our problem is, that for Users or Groups which are created in default namespace, they are provided by EntityPicker without default namespace, which in the end does not work, because the new yaml is created under namespace.

**Comment by benjdlambert** [comment]
Think this can be close as completed in the previous issues. Please let us know if we've missed something! :pray:
