### ISSUE TITLE
Auth plugin backend - skip migrations on Database Provider

### ISSUE THREAD

**Issue by darthaud** [backstage/backstage#12999]
## Expected Behavior

Allow skip migrations when Auth plugin provider is Database

using DatabaseOptions to skip migrations

`const databaseManager = DatabaseManager.fromConfig(config, { migrations: { skip: true } });`

The expected is the AuthPlugin with the Database provider doesn't run the migrations.

## Actual Behavior

The Auth plugin doesn't look to the skip migrations option and always runs the migration.

## Steps to Reproduce

On a fresh install

1. Set authentication provider to be database or leave without auth provider (database is the default provider)
2. Configure Database Manager to skip migrations
3. Run the application
4. Look at the logs and see the auth migrations running.

## Context

I can't use the standard migrations procedure. I must use a company-specific method to run the migrations.

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.15.0
yarn: 1.22.19
cli:  0.17.2 (installed)

Dependencies:
  @backstage/backend-common                  0.14.0
  @backstage/backend-tasks                   0.3.2
  @backstage/catalog-client                  1.0.3
  @backstage/catalog-model                   1.0.3
  @backstage/cli-common                      0.1.9
  @backstage/cli                             0.17.2
  @backstage/config-loader                   1.1.2
  @backstage/config                          1.0.1
  @backstage/errors                          1.0.0
  @backstage/integration                     1.2.1
  @backstage/plugin-app-backend              0.3.33
  @backstage/plugin-auth-backend             0.14.1
  @backstage/plugin-auth-node                0.2.2
  @backstage/plugin-catalog-backend          1.2.0
  @backstage/plugin-catalog-common           1.0.3
  @backstage/plugin-permission-common        0.6.2
  @backstage/plugin-permission-node          0.6.2
  @backstage/plugin-proxy-backend            0.2.27
  @backstage/plugin-scaffolder-backend       1.3.1
  @backstage/plugin-scaffolder-common        1.1.1
  @backstage/plugin-search-backend-module-pg 0.3.4
  @backstage/plugin-search-backend-node      0.6.2
  @backstage/plugin-search-backend           0.5.3
  @backstage/plugin-search-common            0.3.5
  @backstage/plugin-techdocs-backend         1.1.2
  @backstage/plugin-techdocs-node            1.1.2
  @backstage/release-manifests               0.0.4
  @backstage/types                           1.0.0
```

**Comment by darthaud** [comment]
I am trying to push a branch with a fix suggestion, but I am receiving a 403 error. Could you help me with this, please?

**Comment by awanlin** [comment]
@darthaud just checking but are you doing this from a fork? If not that could be why you are having issues.

**Comment by awanlin** [comment]
Yes, it's not super clear but the first line under the "Cloning the Repository" heading mentions it: https://backstage.io/docs/getting-started/contributors

**Comment by darthaud** [comment]
When I read it, I didn't understand that it was required.

**Comment by awanlin** [comment]
That's fair, I'd also read through this as well if you haven't yet

**Comment by awanlin** [comment]
https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md
