### ISSUE TITLE
Gitlab Scaffolder Meaningful Error Description

### ISSUE THREAD

**Issue by mohammadsrahman** [backstage/backstage#13002]
## Feature Suggestion

When using the publish:gitlab scaffolder and the owner (Namespace in gitlab) does not exist then we receive a

```
HTTPError: Response code 404 (Not Found)
```

@gitbeaker/node [Documentation](https://github.com/jdalrymple/gitbeaker#debugging) suggests using e.description

## Possible Implementation

``` 
      let { id: targetNamespace } = (await client.Namespaces.show(owner).catch(
          (reason) => {
            ctx.logger.error( `${owner} ${reason.description}`);
      })) as {
        id: number;
      };
```

## Context

Better Error Description from the gitlab API as this is already provided in the module. It just needs to be taken advantage of.

**Comment by Rugvip** [comment]
Yep! Would be good if we could clarify that error, is it something you'd like to contribute?

**Comment by mohammadsrahman** [comment]
> Yep! Would be good if we could clarify that error, is it something you'd like to contribute?

I could have a go if you want, but I'm not a javascript developer by trade.

**Comment by Parsifal-M** [comment]
Was this closed because it's stale? Why was it closed? Something I might look into as its currently biting me in the rear 😄
