### ISSUE TITLE
Backstage Link not routing properly

### ISSUE THREAD

**Issue by ivangonzalezacuna** [backstage/backstage#13007]
## Expected Behavior

Using the internal `Link` from the core-components package links to another location within backstage using an object for the `to` prop. Defining the `pathname` and `search` should redirect you to another part of the backstage instance.

## Actual Behavior

Since the `core-components` update to the version 0.10.0, this seems to be broken and not work anymore. Instead of redirecting to another place within Backstage, it adds an `[object Object]` at the end of the current string.

## Steps to Reproduce

In our internal backstage instance we have a page where we can see all the releases we have made within the company, listing the service name and the version name among other things. Inside the component view we have another custom card which shows the current deployed version, and a link to the the releases page with a search parameter, so that this release is highlighted among the others.

So our backstage Link would look more or less like this:

```typescript
        <BackstageLink
          to={{
            pathname: `/releases/day/${moment(date).format('YYYY-MM-DD')}`,
            search: link_id ? `release_id=${link_id}` : '',
          }}
        >
          {...}
        </BackstageLink>
```

Using a development environment, this should link from something like `http://localhost:3000/catalog/default/component/backstage` to `http://localhost:3000/releases/day/2022-08-08?release_id=...`. Instead, it links to `http://localhost:3000/catalog/default/component/backstage/[object%20Object]`.

If I just create the URL on my own (something like `/releases/day/2022-08-08?release_id=1234`) and insert it as a string, then the link will work again. This is our current solution, as a workaround, but I guess this is something that broke in the last version of this package. Or maybe I just misunderstood the idea behind it.

## Your Environment

- Browser Information: Firefox 103.0 (64-bit)

- Output of `yarn backstage-cli info`: 

```text
yarn run v1.22.19
$ /home/ivgo/backstage/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.16.2-051602-generic - linux/x64
node: v16.16.0
yarn: 1.22.19
cli:  0.18.0 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.4
  @backstage/backend-common                        0.14.1
  @backstage/backend-plugin-api                    0.1.0
  @backstage/backend-tasks                         0.3.3
  @backstage/backend-test-utils                    0.1.26
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.0
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.4
  @backstage/core-components                       0.10.0, 0.9.5
  @backstage/core-plugin-api                       1.0.4
  @backstage/dev-utils                             1.0.4
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.2
  @backstage/integration                           1.2.2
  @backstage/plugin-api-docs                       0.8.7
  @backstage/plugin-app-backend                    0.3.34
  @backstage/plugin-auth-backend                   0.15.0
  @backstage/plugin-auth-node                      0.2.3
  @backstage/plugin-catalog-backend-module-gitlab  0.1.5
  @backstage/plugin-catalog-backend-module-ldap    0.5.1
  @backstage/plugin-catalog-backend                1.3.0
  @backstage/plugin-catalog-common                 1.0.4
  @backstage/plugin-catalog-graph                  0.2.19
  @backstage/plugin-catalog-import                 0.8.10
  @backstage/plugin-catalog-node                   1.0.0
  @backstage/plugin-catalog-react                  1.1.2
  @backstage/plugin-catalog                        1.4.0
  @backstage/plugin-github-actions                 0.5.7
  @backstage/plugin-home                           0.4.23
  @backstage/plugin-kubernetes-backend             0.7.0
  @backstage/plugin-kubernetes-common              0.4.0
  @backstage/plugin-kubernetes                     0.7.0
  @backstage/plugin-org                            0.5.7
  @backstage/plugin-permission-backend             0.5.9
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.3
  @backstage/plugin-permission-react               0.4.3
  @backstage/plugin-proxy-backend                  0.2.28
  @backstage/plugin-scaffolder-backend             1.4.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.4.0
  @backstage/plugin-search-backend-node            1.0.0
  @backstage/plugin-search-backend                 1.0.0
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.0
  @backstage/plugin-search                         1.0.0
  @backstage/plugin-stack-overflow                 0.1.3
  @backstage/plugin-techdocs-backend               1.2.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.2
  @backstage/plugin-techdocs-node                  1.2.0
  @backstage/plugin-techdocs-react                 1.0.2
  @backstage/plugin-techdocs                       1.3.0
  @backstage/plugin-todo-backend                   0.1.31
  @backstage/plugin-todo                           0.2.9
  @backstage/plugin-user-settings                  0.4.6
  @backstage/plugin-vault-backend                  0.2.0
  @backstage/plugin-vault                          0.1.1
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 0.61s.
```

**Comment by freben** [comment]
Hi! I'll be honest and admit that I personally had no idea that an object was even a valid value for `to`... so we never designed for that to work. You have to form a single string instead. I see that the basis for those props' type is `MaterialLinkProps & RouterLinkProps`, and that's WAY too liberal since the two of them aren't at feature parity. It should have always been a string-only prop. We'd love a contribution to make that type more strict.

**Comment by ivangonzalezacuna** [comment]
Hm, good to know. We were using it in the previous releases without issues, until we upgraded to 1.4.0. Now all the cases have been migrated to normal strings, as you recommended, and those weird issues with the url are gone.

But yes, it would be nice to restrict the `to` prop for the core-components, so other people don't suffer the same issues.

By the way, I noticed it's not only happening to `Link`, but also to `Button`, which uses the same `to` prop. So, at least, both internal elements would need to be modified

**Comment by freben** [comment]
Yeah, good point! There may be more places indeed.

**Comment by freben** [comment]
Alright, I made a pull request (linked above), let's see what the reviewers think about it.

**Comment by ivangonzalezacuna** [comment]
Cool, thanks!. I have also found the way to force the type to be string. But you were faster :)

Let's see what other people think about it.
