### ISSUE TITLE
[microsite] Plugin Marketplace - New Plugin Sign

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#13015]
## Feature Suggestion

It would be pretty cool if we had a little tag/sign on plugins that are new making it easier to spot them

## Possible Implementation

This could be as simple as adding a tag/sign to the plugin card is they are less that `n` days old. The age could just be pulled from when the YAML was added to the `microsite` 

## Context

This would just give some extra love to newer plugins; when people check the market place this might catch their eye

**Comment by suuus** [comment]
This is about the Microsite Plugin marketplace, live view: https://backstage.io/plugins 
![Screenshot 2022-09-27 at 13 30 13](https://user-images.githubusercontent.com/40822355/192514065-6324475b-9e83-48bb-9e8c-97a7f2da5554.png)

**Comment by Znarvl** [comment]
Hi! I'm new to this project and would like to work on this issue. Is it still open?

**Comment by Znarvl** [comment]
Great, thanks!

**Comment by marcofaggian** [comment]
Hi @Znarvl @awanlin, I'm willing to help!
@Znarvl are you still on it?

**Comment by Znarvl** [comment]
@marcofaggian Yeah I'm working on it, hopefully I'll fix a pull request in the beginning of next week

**Comment by marcofaggian** [comment]
Hi, I was curious about how to get the date data and figured out:
- yaml file stats are all related to `git clone` moment
- date can be found using git history: `git log -1 --format="%ai" --reverse buildkite.yaml | cat -`

But this means that git must be a dependency at build time, is this a good-enough solution?

**Comment by marcofaggian** [comment]
Could not resist to the css challenge:
![Schermata 2022-10-07 alle 16 55 50](https://user-images.githubusercontent.com/19221001/194584931-fa0d191e-25ca-47bd-bb0e-8086798d13da.png)
What do you think about it?

**Comment by marcofaggian** [comment]
@Znarvl do you wish to provide your code as solution? Happy to go that way!

If not, I can open a PR and let @awanlin try out the solution, if it fits timings and usability (the git lookup is pretty impactful).

**Comment by Znarvl** [comment]
I kinda got stuck and got unmotivated when a solution got proposed, so go ahead and create a PR!

**Comment by marcofaggian** [comment]
Sorry to hear that @Znarvl !

I've actually another idea for this page: It would be great to convert it to something like [Slack's app public directory](https://slack.com/apps) with missing features like:
1. Search
2. Category navigation
3. Single plugin, dedicated onboarding page

A solution could be a Next.js ISR dedicated website, incrementally regenerated on `plugins/<plugin>.yaml` append.

But I would open an issue about it, if you deem it's a good idea.

**Comment by awanlin** [comment]
@marcofaggian I appreciate the ideas, it's for sure eventually what I'd love to see and I actually have an issue for adding a Category Filter here: https://github.com/backstage/backstage/issues/13014.

I think it's important to note that more than this page lives here, all the documentation for Backstage, as well as autogenerated code docs, and other material are in this site so moving to a different tech stack seems like a big jump. There is an open issue to upgrade to Docusaurus 2.0 which would give us more options (MDX and React support among them) while keeping everything we currently have still working: https://github.com/backstage/backstage/issues/12019

**Comment by marcofaggian** [comment]
The website shows all plugins as new, my suspect is the build system pulling just the head, not the complete history, rending this method of calculating "file addition date" useless.

I'll dig into it.

**Comment by cas--** [comment]
@marcofaggian The new plugin ribbon looks good but for the live site it's functionally broken as it shows all plugins as new. This is likely due to build process using a shallow git clone depth e.g. `git clone --depth 1` so the author dates for the all files in git will be the date of the last commit. 

I doubt the team want to slow the build process by modifying the clone depth. Instead perhaps add a new key with the date (e.g. `addedDate: '1970-01-01'`) to the metadata?

I have a patch to fix it

**Comment by marcofaggian** [comment]
> @marcofaggian The new plugin ribbon looks good but for the live site it's functionally broken as it shows all plugins as new. This is likely due to build process using a shallow git clone depth e.g. `git clone --depth 1` so the author dates for the all files in git will be the date of the last commit. 
> 
> I doubt the team want to slow the build process by modifying the clone depth. Instead perhaps add a new key with the date (e.g. `addedDate: '1970-01-01'`) to the metadata?
> 
> I have a patch to fix it
> 

Yes that solution would be the alternative. A PR would be appreciated!
