### ISSUE TITLE
Test Custom JSON form Components for Scaffolder Wizard

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#1302]
## Feature Suggestion
- We want to be able to test to see if the open standard of `json-forms` is sufficient for using in the wizard when creating components https://jsonforms.io/.
- Internally, we have many different types of custom elements in the form, mainly the `repo-selection` drop down.
- Would be good if we could try to replicate one of the harder custom elements and components that we have internally, and try to make sure that all of this would work with the new open standard.

## Possible Implementation
- Create a React JSON Form using mui that can use the users authentication to list repositories that we have access to
- Maybe we can build upon this branch: https://github.com/spotify/backstage/tree/blam/json-forms
- This branch already implements `react-json-form` in `mui` but does not try to render any custom components

**Comment by benjdlambert** [comment]
Think that we've pretty much proved that this is possible, but would be good to implement this repo dropdown pretty soon as it will improve the experience in the scaffolder rather than having freetext.

**Comment by benjdlambert** [comment]
Looking at the documentation,  I think we need to add another property to the `spec` of `TemplateEntityV1Alpha` which is the `uiSchema` which can set the widget that is rendered to our custom component:
https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/#custom-field-components

**Comment by ayshiff** [comment]
Can I work on it @benjdlambert ?
I'll build upon your branch 👍

**Comment by stefanalund** [comment]
@ayshiff Ben is out on some vacation, but sure! I'm assigning you. Thanks 🙏

**Comment by ayshiff** [comment]
@stefanalund Could I have more information regarding this issue knowing that it is more than 2 months old.
Is the scope of the issue always the same?
If it's easier to chat, could we make a point together on the Discord to discuss this ticket?
