### ISSUE TITLE
DaemonSet as part of Kubernetes core resources

### ISSUE THREAD

**Issue by Smorenoz** [backstage/backstage#13051]
## Feature Suggestion

Going through the `KubernetesFanOutHandler` service, I noticed that the `DEFAULT_OBJECTS` array is missing an entry for `daemonsets` which makes not possible for the actual fetching of these resources. 

## Context

I am currently working on trying to display helpful information about `DaemonSets` existing on a cluster.

**Comment by jhaals** [comment]
I believe you fixed this with #13053 closing this issue, please reopen if needed.
