### ISSUE TITLE
Generated backend HTTPS certificate age check should check expiration

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#13074]
## Feature Suggestion

The following logic is currently used to check the whether we need to generate a new HTTPS certificate for development: https://github.com/backstage/backstage/blob/5330e3758888b46da7833cdd2ae8efd39797044e/packages/backend-common/src/service/lib/hostFactory.ts#L100-L101

It would be preferable to check the actual certificate expiration instead, since the file could be recreated with an outdated certificate.

## Possible Implementation

We already use `node-forge` to generate certificates, so we could use it to parse the existing one as well. See for example [this SO answer](https://stackoverflow.com/questions/58724396/parse-x509-certificate-string-in-node#answer-58724754)

**Comment by benjdlambert** [comment]
Assigned @gibsonliketheguitar 🎸 !

**Comment by Znarvl** [comment]
Hello, is this issue still worked on or could I take it? I'm new to backstage and would like to contribute :)

**Comment by gibsonliketheguitar** [comment]
> Hello, is this issue still worked on or could I take it? I'm new to backstage and would like to contribute :)

Hey @Znarvl you can take over!. I've been busy with other stuff. 

Where I got stuck on.
I tried tracing to where the certificate is created and tried the local dev route. But in order to test and confirm that node-froge is working, I think you need to deploy it to docker. I haven't gotten around setting up docker and stuff

Good luck!

**Comment by Znarvl** [comment]
Alright, thanks!

**Comment by jgrumboe** [comment]
I've worked on this. Hopefully the implementation is fine.
