### ISSUE TITLE
[Backend System] Overview

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#13081]
[RFC](https://github.com/backstage/backstage/issues/11611), [Milestone](https://github.com/backstage/backstage/milestone/36)

The following is a list of issue task collections that are in scope for the initial Backend System release. All of the below issues will evolve over time as more requirements are discovered.

- #13082 - the Core API surface
- #13083 - building out service (API) definitions and implementations.
- #13084 - migrating existing plugins to be part of the new Backend System.

**Comment by camilaibs** [comment]
Closing in favor of https://github.com/backstage/backstage/issues/24493
