### ISSUE TITLE
Analytics events not getting generated when using oauth

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#13134]
Below is some of our configuration.

packages/app/src/api.ts
```
import {
  ScmIntegrationsApi,
  scmIntegrationsApiRef,
  ScmAuth,
} from '@backstage/integration-react';
import { 
  AnyApiFactory, 
  configApiRef, 
  createApiFactory, 
  oauthRequestApiRef, 
  discoveryApiRef, 
  ApiRef, 
  OAuthApi, 
  OpenIdConnectApi, 
  ProfileInfoApi, 
  BackstageIdentityApi, 
  SessionApi,
  createApiRef,
  analyticsApiRef,
  identityApiRef } from '@backstage/core-plugin-api';
import { OAuth2} from '@backstage/core-app-api';
import { DBLogoBlueMedium } from './logos/DBLogo';
import { DBAnalytics } from '@internal/plugin-analytics-module-db';

export const oauthAuthApiRef: ApiRef<
  OAuthApi &
    OpenIdConnectApi &
    ProfileInfoApi &
    BackstageIdentityApi &
    SessionApi 
> = createApiRef({
  id: 'internal.auth.acme',
});

export const apis: AnyApiFactory[] = [
  createApiFactory({
    api: scmIntegrationsApiRef,
    deps: { configApi: configApiRef },
    factory: ({ configApi }) => ScmIntegrationsApi.fromConfig(configApi),
  }),

  createApiFactory({
    api: analyticsApiRef,
    deps: { configApi: configApiRef, identityApi: identityApiRef },
    factory: ({ configApi, identityApi }) =>
      DBAnalytics.fromConfig(configApi, identityApi),
  }),

  ScmAuth.createDefaultApiFactory(),

  createApiFactory({
    api: oauthAuthApiRef,
    deps: {
      discoveryApi: discoveryApiRef,
      oauthRequestApi: oauthRequestApiRef,
      configApi: configApiRef,
    },
    factory: ({ discoveryApi, oauthRequestApi, configApi }) =>
      OAuth2.create({
        discoveryApi,
        provider: {
          id: 'oauth2',
          title: 'Oauth',
          icon: Icon,
        },
        oauthRequestApi,
        environment: configApi.getOptionalString('auth.environment'),
      }),
  }),
];
```
[Note :  DBAnaltytics is our custom analytics module responsible to capture the events and store it in our database for the time being ]

Our App.tsx has the below content for signin page
```
components: {
    SignInPage: props => {
      const discoveryApi = useApi(discoveryApiRef);
      return (
        <SignInPage
          {...props}
          providers={isGuestUserAvailable() ? ['guest', ...providers] : [...providers]}
          title={isGuestUserAvailable() ? "Select a sign-in method" : ""}
          align="center"
          onSignInSuccess={async (identityApi: IdentityApi) => {
            setTokenCookie(
              await discoveryApi.getBaseUrl('cookie'),
              identityApi,
            );

            props.onSignInSuccess(identityApi);
          }}
        />
      );
    },
  }
```
So we use guest as well as providers, which in this case we just oauth provider configured in the identityProviders.ts as below
```
export const providers = [
  {
    id: 'eidp-auth-provider',
    title: 'Oauth',
    message: 'Oauth',
    apiRef: oauthAuthApiRef,
  }
];
```
Now if we sign in as guest and click on the catalog or any plugin where the analtyics is hooked in, we get the analytics generated as below.
![image](https://user-images.githubusercontent.com/86959288/184511954-8321d443-c555-40e8-8da2-26d518f4e1d3.png)

But if I have logged in as oauth user, then the analytics events are not getting generated.

![image](https://user-images.githubusercontent.com/86959288/184511994-b3142090-7426-4353-8ea3-be96d9119266.png)

**Comment by jhaals** [comment]
@iamEAP do you have any pointers to give for this issue?

**Comment by iamEAP** [comment]
Hey, @shanthisagar-dhanya-kumar-db.

Unfortunately, this kind of issue can be hard to debug, but I think you're right to be honing in on the `identityApi` part of it.

First things to check:

- Is `props.onSignInSuccess()` being called with the identityApi in both cases?  I ask because any call to `identityApi. getBackstageIdentity()` in your custom analytics API implementation will hang indefinitely until a concrete implementation has actually been registered via that `onSignInSuccess` handler.
- Is the call to `identityApi.getBackstageIdentity()` in your custom analytics API implementation resolving a value or is it rejecting / throwing?  The Analytics API is set up to catch and swallow all errors so as not to impact the functionality of Backstage, so you may need to comb through places in your custom code that might be throwing errors and try and isolate the problem there.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
I think I found the root cause on analytics event capture.

Basically what we are doing is
For analytics events to be captured and sent to backend to persist, we are checking whether both the username and user email are present as part of the identity object.
For Guest login, it is by default set to "Guest" and "guest@example.com"
For EiDP login, what we capture and store in the identity object is just email address. [ We could possibly store additional claims, but the expected types of passport js library vs Eidp doesn't match, so we only capture email, else a huge customisation is required for authentication plugin. ]
And hence it is failing.
If we just check the existence of the email id as part of login identity object while capturing and persisting events data, it would fix this.

But, thanks for the pointers which really helped in troubleshooting the issue.
