### ISSUE TITLE
Add HTTP2 Server Support

### ISSUE THREAD

**Issue by danangarbansa** [backstage/backstage#13142]
## Feature Suggestion

To add option in the `app.config.yaml` config to enable HTTP2 server, something like

```bash
backend:
	enableHTTP2: true
```

This config should enable the HTTP2 server in the backstage backend.

## Possible Implementation

Seems like this is achievable by modifying the [hostFactory.ts](https://github.com/backstage/backstage/blob/8a534e0db9938350c8d55bccbb62dd10dff2eab9/packages/backend-common/src/service/lib/hostFactory.ts#L37)

```javascript
import * as http from 'http'
import * as http2 from 'http2'

export function createHttpServer(
  app: express.Express,
  logger?: Logger,
): http.Server {
  logger?.info('Initializing http server');

  // Just a mock implementation, somehow get this flag from the config
  if (shouldUseHttp2) {
	  return http2.createServer({ allowHTTP1: true }, app);
	}

  return http.createServer(app);
}
```

## Context

For more context, we have a use case to support gRPC call from backstage FE to a remote server. However, we want to proxy this request through backstage’s BE via the proxy plugin. This becomes a problem because gRPC relies on HTTP2 and the backstage BE server does not support that. 

Another problem that comes with this is that the library that is used by the proxy plugin   has an issue with HTTP2 support as well (see https://github.com/http-party/node-http-proxy/issues/1237), but this seems like a separate issue that should be handled separately.

**Comment by jhaals** [comment]
Hi @danangarbansa,

I think it make sense to update this to only `http2.createServer({ allowHTTP1: true }, app);` as it would be compatible with both to my understanding. What do you think?

**Comment by danangarbansa** [comment]
@jhaals yeah good point, I'll submit a PR for that

**Comment by danangarbansa** [comment]
@jhaals seems like the `allowHTTP1` option is only available in the `createSecureServer` method and looks like this won't be implemented soon. Reference: https://github.com/nodejs/node/issues/26795. 

Based on this, looks like enable it by option would be the best for the non-https server.

What do you think?

**Comment by jhaals** [comment]
Yeah I realise that H2 is only available with TLS so I think it make sense to run `http2.createServer({ allowHTTP1: true }, app);` when certificates are provided.

**Comment by danangarbansa** [comment]
After further investigation, this appears to be a larger issue than I initially thought.

Express does not support http2 at the moment. It won't work with the native node `http2` module.

As a workaround, we can use [spdy](https://www.npmjs.com/package/spdy) instead of the native `http2`. It works with express. However, there are reports that `spdy` won't work with node version >15, so this is definitely not a very good solution.

The `http2` support in express will be added in v5, which is currently in alpha version.

I think the best course of action is to wait for express v5 stable version to be released and update backstage's server implementation using the native `http2` module.

**Comment by freben** [comment]
Alright. Shall we close this one for now then? Do you have an option of terminating http2 in a fronting proxy?

**Comment by danangarbansa** [comment]
> Shall we close this one for now then?
Yeah I think we can close this one for now.

> Do you have an option of terminating http2 in a fronting proxy?
Our use case is to forward http2 connection to the upstream gRPC server using the backend proxy.

We are thinking of using [envoy's grpc bridge](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_http1_bridge_filter) in front of the gRPC upstream server, so we can keep the HTTP1.1 connection to the backstage.

Also, to answer your question we do have http2 connection from the client, but it is terminated in the Cloudflare since we are using Cloudflare Access to protect our backstage server.
