### ISSUE TITLE
[create-app] The template installs config for `lint-staged` although the package is not installed

### ISSUE THREAD

**Issue by planeiii-te** [backstage/backstage#13152]
Currently the config for `lint-staged` is installed even though the package itself is not a part of the project. I believe `husky` and `lint-staged` should be added to the `create-app`. Alternatively the unreferenced config can be removed.

## Expected Behavior

One of two things should happen. Either the related tools (`husky` and `lint-staged`) should be installed or the irrelevant config should be removed.

## Actual Behavior

The config for `lint-staged` is present although the `lint-stage` package (nor `husky`) are present.

## Steps to Reproduce

1. `cd $(mktemp -d /tmp/meh.XXXXXX)`
2. `npx @backstage/create-app --skip-install`
3. `grep -R lint-staged` 

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by benjdlambert** [comment]
I think `npx @backstage/create-app --skip-install` is going to not install any of the `npm` packages which is where those packages come from. If you're wanting to commit without installing you can do `git commit --no-verify` to workaround this issue.

**Comment by planeiii-te** [comment]
Running with `--skip-install` will not fix the problem. The problem is that the config for them exists, but the packages to use the config do not. Here's a [code search](https://cs.github.com/backstage/backstage?q=path%3Apackages%2Fcreate-app%2Ftemplates%2Fdefault-app+lint-staged) of this repo that shows that the only instance of `lint-staged` appears in the `create-app` template and it's in the `package.json.hbs`:

https://github.com/backstage/backstage/blob/bf340bcb4a06a374eb87c1868b736a251eed2e8c/packages/create-app/templates/default-app/package.json.hbs#L46-L54

There are no packages present to make use of this config. If this was setup correctly, there would be other instances of `lint-staged` present. It's like `husky` would be present as well.

**Comment by benjdlambert** [comment]
Ah - ok, now I understand. Maybe we should just add this dependency to the `package.json.hbs` then? Must have been something that was missed when creating those templates.

**Comment by jhaals** [comment]
@planeiii-te would you be willing to fix this in the template? 🙏
