### ISSUE TITLE
Apache Airflow Plugin does not send Auth Cookies to Proxy

### ISSUE THREAD

**Issue by zgriesinger** [backstage/backstage#13179]
## Expected Behavior

When using the airflow plugin with 
https://github.com/backstage/backstage/tree/master/plugins/apache-airflow
_and_ configuring the proxy plugin like this
```typescript
  apiRouter.use('/proxy', authMiddleware, await proxy(proxyEnv));
```
I expect to require Backstage Auth to view airflow resources.

## Actual Behavior

All calls return Unauthed. (or if you remove the auth middleware on the proxy registration it works)

## Steps to Reproduce

1. Configure proxy as outlined above
2. Follow steps in Airflow Plugin readme to install
3. View unauthorized errors on `localhost:3000/apache-airflow`
4. Remove `authMiddleware` view successes.

## Context

We like to try to require auth middlewares on all of our proxies in order to prevent privilege escalation - so we cannot use this plugin until it can pass through the authMiddleware. 

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.4.0 - darwin/arm64
node: v16.14.2
yarn: 1.22.19
cli:  0.18.0 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.4
  @backstage/backend-common                        0.14.1
  @backstage/backend-plugin-api                    0.1.0
  @backstage/backend-tasks                         0.3.3
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.0
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.4
  @backstage/core-components                       0.10.0, 0.10.1-next.1
  @backstage/core-plugin-api                       1.0.4, 1.0.5-next.0
  @backstage/dev-utils                             1.0.4
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.2
  @backstage/integration                           1.2.2, 1.3.0-next.1
  @backstage/plugin-apache-airflow                 0.2.0
  @backstage/plugin-api-docs                       0.8.7
  @backstage/plugin-app-backend                    0.3.34
  @backstage/plugin-auth-backend                   0.15.0
  @backstage/plugin-auth-node                      0.2.3
  @backstage/plugin-azure-devops-backend           0.3.13
  @backstage/plugin-azure-devops-common            0.2.4
  @backstage/plugin-azure-devops                   0.1.23
  @backstage/plugin-catalog-backend-module-github  0.1.5
  @backstage/plugin-catalog-backend                1.3.0
  @backstage/plugin-catalog-common                 1.0.4, 1.0.5-next.0
  @backstage/plugin-catalog-graph                  0.2.19
  @backstage/plugin-catalog-import                 0.8.10
  @backstage/plugin-catalog-node                   1.0.0
  @backstage/plugin-catalog-react                  1.1.2, 1.1.3-next.1
  @backstage/plugin-catalog                        1.4.0
  @backstage/plugin-github-actions                 0.5.7
  @backstage/plugin-graphiql                       0.2.39
  @backstage/plugin-home                           0.4.23
  @backstage/plugin-kafka-backend                  0.2.27
  @backstage/plugin-kafka                          0.3.7
  @backstage/plugin-kubernetes-backend             0.7.0
  @backstage/plugin-kubernetes-common              0.4.0
  @backstage/plugin-kubernetes                     0.7.1-next.1
  @backstage/plugin-lighthouse                     0.3.7
  @backstage/plugin-org                            0.5.7
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.3
  @backstage/plugin-permission-react               0.4.3, 0.4.4-next.0
  @backstage/plugin-proxy-backend                  0.2.28
  @backstage/plugin-scaffolder-backend             1.4.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.4.0
  @backstage/plugin-search-backend-node            1.0.0
  @backstage/plugin-search-backend                 1.0.0
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.0
  @backstage/plugin-search                         1.0.0
  @backstage/plugin-shortcuts                      0.2.8
  @backstage/plugin-stack-overflow                 0.1.3
  @backstage/plugin-tech-radar                     0.5.14
  @backstage/plugin-techdocs-backend               1.2.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.2
  @backstage/plugin-techdocs-node                  1.2.0
  @backstage/plugin-techdocs-react                 1.0.2
  @backstage/plugin-techdocs                       1.3.0
  @backstage/plugin-todo-backend                   0.1.31
  @backstage/plugin-todo                           0.2.9
  @backstage/plugin-user-settings                  0.4.6
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
```

**Comment by benjdlambert** [comment]
`authMiddleware` is probably overriding the `Authorization` header in the request to upstream. In the meantime I'd suggest that you copy the `authMiddleware` function, and do some selective stuff based on if the `request.url` has the `airflow` path and not do anything special there.

**Comment by sole0bserver** [comment]
@benjdlambert I actually observe similar behaviour while proxying requests from Scaffolder to BitBucket with "Authenticate API requests" enabled. Unauthorized 401, as basically it's the same header I'm trying to send, but with BitBucket access token. I appreciate the workaround you have provided, do you think it's applicable to my issue as well?

**Comment by benjdlambert** [comment]
When do you see this 401 with the scaffolder? The scaffolder shouldn't use the `proxy` endpoint, it should just call out to the provider directly with the token that you've configured in your `integrations` config. @pjungermann + others have done some great work recently with bitbucket, so maybe update to the latest versions and give it a go?

**Comment by sole0bserver** [comment]
Thing is, I use http:request action to create branch/PR in BitBucket (as bitbucketCloud:publish is only suitable for new repos it seems, in contrast to vast GitHub support). Docs for http:request action recommend to send requests through proxy...

**Comment by benjdlambert** [comment]
In that case I would suggest that it is something like that if you're going through the proxy, It's possible that the request is invalid with the users auth token or it's doing something. I wonder if it would make sense to contribute an action that can use the built in `integrations` to get auth from both the `integrations` config and be overriden by a provided token like the github ones  that can raise pull-requests rather than using the proxy and the `http:backstage:request` action?

**Comment by sole0bserver** [comment]
It would look nicer with custom action for BitBucket indeed, I'm just lacking time/dev experience to code it (more devops/systems background). 
I understood the issue as following:
- using http:backstage:request and access token (which is surely valid) I'm trying to send request via /proxy to BitBucket API;
- Access token for BitBucket is apparently in 'Authorization' header;
- As soon as the request hits authMiddleware header is read, and is this is token for BitBucket (and it is not valid inside Backstage) scaffolder receives 401 from authMiddleware;

So if I wrap access token for BitBucket differently (need to research), leaving Authorization header for internal auth means, it will supposedly work.

**Comment by benjdlambert** [comment]
Yeah or you will need to do the same as mentioned before to create your own proxy middleware that ignores validating the token on `/bitbucket` or `/airflow` or whatever

**Comment by sole0bserver** [comment]
Thanks a lot @benjdlambert! This was a fruitful conversation for me :)

**Comment by pjungermann** [comment]
seems like the discussion went a bit out of the original scope.

Re Bitbucket Cloud and `bitbucketCloud:publish`:
It is true that this action only supports new repositories at the moment.
I will need something for adding branches and PRs later for us, too.

For GitHub, there is a separate action for PRs. Something like this will be needed for Bitbucket Cloud as well.

This would render the while httpRequest + proxy solution unnecessary.

Maybe you are up for contributing this action.

**Comment by pjungermann** [comment]
`bitbucketCloud:publish` could be modified to support existing repositories and only fail if the specified branch already exists.

**Comment by sole0bserver** [comment]
@pjungermann Having this specific action would be the best, I can't unfortunately contribute to it directly (lack of Dev experience with this stack).
