### ISSUE TITLE
.dockerignore src exclusion breaks multi-stage builds

### ISSUE THREAD

**Issue by kunickiaj** [backstage/backstage#13180]
## Expected Behavior
Docker multi stage build from docs completes successfully.

## Actual Behavior
Fails with the following error:

```
 > [build 8/8] RUN yarn --cwd packages/backend build:
#17 0.280 yarn run v1.22.19
#17 0.316 $ backstage-cli package build
#17 1.780
#17 1.780 Error: Error: Could not resolve entry module (src/index.ts).
```

## Steps to Reproduce

1. Use the Dockerfile at https://backstage.io/docs/deployment/docker#multi-stage-build
2. `docker build -t backstage .`

## Context

I noticed that the issue was introduced by the following commit https://github.com/backstage/backstage/commit/7cda923c16c492605b8fe02cf9bab5e39bf58d9a

Specifically https://github.com/backstage/backstage/blob/7cda923c16c492605b8fe02cf9bab5e39bf58d9a/.dockerignore#L6

Removing the `.dockerignore` line excluding `packages/*/src` resolves the issue as this prevents the code from being available in the build stage.

## Your Environment

macOS 12.5, M1X (arm64), Docker for Mac

**Comment by benjdlambert** [comment]
In the docs that you linked there's a change that you have to make to the `.dockerignore` for `multi-stage` builds.

Something like:
```
node_modules
packages/*/dist
packages/*/node_modules
plugins/*/dist
plugins/*/node_modules
```

In the docker ignore should work.

**Comment by ananthulasrikar** [comment]
@kunickiaj I am having same issue :(

**Comment by Rugvip** [comment]
Will close this as it's an intended manual change that needs to be made and it is highlighted in docs. We can't support both docker build strategies either in an optimal way, and we strongly encourage use of the default host build setup.
