### ISSUE TITLE
Catalog entity filter returning 0 results for k8s plugin catalog cluster locator

### ISSUE THREAD

**Issue by asaf-erlich** [backstage/backstage#13191]
I'm trying to use the new EKS Cluster Processor and Kubernetes Catalog Collector created in the PR https://github.com/backstage/backstage/pull/11789 . I was able to get the cluster processor to ingest clusters into the catalog, but the cluster locator fails to find any of the clusters.

I'm stuck trying to debug why the catalog/entity?filter query is not returning values for one of the specific keys. The query `http://localhost:7007/api/catalog/entities/?filter=metadata.annotations.kubernetes.io%2Fapi-server,metadata.annotations.kubernetes.io%2Fauth-provider` returns 36 entities all of which have a `metadata.annotations.kubernetes.io/api-server-certificate-authority` but if I try to search with that key `http://localhost:7007/api/catalog/entities/?filter=metadata.annotations.kubernetes.io%2Fapi-server-certificate-authority` I get 0 results. The kubernetes cluster locator method catalog searches the catalog for the above 3 keys. Any suggestions would be appreciated.

Backstage version: `1.4.0`
@backstage/plugin-kubernetes-backend version: `0.7.0`
@backstage/plugin-kubernetes version: `0.7.0`
@backstage/plugin-catalog-backend-module-aws version: `0.1.7`

Discord links related to the above issue:
- https://discord.com/channels/687207715902193673/1009152120697663549/1009152120697663549
- https://discord.com/channels/687207715902193673/761562031521792020/1009149782314459176
- https://discord.com/channels/687207715902193673/1009148768240803860

On one of the above messages it was pointed out that if the values are very large the database engine won't index it, and the `metadata.annotations.kubernetes.io/api-server-certificate-authority` is a fairly large encoded string of 1,424 characters: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/stitching/buildEntitySearch.ts#L37 . This would line up with the above info but I don't know enough how to debug the catalog database to confirm that.

Thank you,
-Asaf

## Expected Behavior

Querying the catalog with the key values used by the k8s plugin should return results, namely full query it uses is `GET /api/catalog/entities?filter=kind=Resource,spec.type=kubernetes-cluster,metadata.annotations.kubernetes.io%2Fapi-server,metadata.annotations.kubernetes.io%2Fapi-server-certificate-authority,metadata.annotations.kubernetes.io%2Fauth-provider`. These are the keys one sees in the filter in the file https://github.com/backstage/backstage/blob/b6c8637fdcfcd84d8d17fbbbef816e698b4fff8b/plugins/kubernetes-backend/src/cluster-locator/CatalogClusterLocator.ts#L41-L47

## Actual Behavior
No clusters are returned by the query. This could be because there is a bug somewhere in one of the components involved or some detail I'm missing in configuration. The above PR is the only example of info about the new EKS Cluster Processor and Kubernetes Catalog Collector. There is no official documentation I could find so I did my best to debug and get it working, but it could be that I'm missing something. 

## Steps to Reproduce

1. Ensure you're on backstage version `1.4.0` or later.
2. `yarn workspace backend add @backstage/plugin-catalog-backend-module-aws`
3. Configure the collector correctly and ensure you have exported the correct env variables / other way to configure your aws credentials into backstage's running process:
    ```
    # Inside app-config.yaml
    catalog:
    processingIntervalSeconds: ${CATALOG_PROCESSING_INTERVAL_SECONDS}
    rules:
      - allow: [Component, System, API, Resource, Location]
    locations:
      - type: aws-eks
        target: <account-id>/<region>
    ```
    ```
    # Inside packages/backend/src/plugins/catalog.ts
     new AwsEKSClusterProcessor({
      credentialsFactory: () => new AWS.CredentialProviderChain().resolvePromise(),
    }),
    ```
4. Ensure the processor is ingesting kubernetes data. I ended up overwriting the package locally and adding log lines to do this but in the end you need to ensure entities similar to below are appearing in the catalog :
    ```
    {
        "apiVersion": "backstage.io/v1alpha1",
        "kind": "Resource",
        "metadata": {
            "annotations": {
                "amazonaws.com/account-id": "<account-id>",
                "amazonaws.com/arn": "<arn>",
                "kubernetes.io/api-server": "https://<url>.<region>.eks.amazonaws.com",
                "kubernetes.io/api-server-certificate-authority": "<very long 1400+ character string>",
                "kubernetes.io/auth-provider": "aws"
                },
            "name": "<name>",
            "namespace": "<namespace>"
            },
        "spec": {
            "type": "kubernetes-cluster",
            "owner": "unknown"
        }
    }
    ```
5. `yarn add --cwd packages/app @backstage/plugin-kubernetes`
6. `yarn add --cwd packages/backend @backstage/plugin-kubernetes-backend`
7.  Follow the steps to configure kubernetes https://backstage.io/docs/features/kubernetes/configuration but use catalog `clusterLocatorMethods`:
    ```
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'catalog'
    ```
8. Confirm querying catalog returns results for the query `http://localhost:7007/api/catalog/entities/?filter=metadata.annotations.kubernetes.io%2Fapi-server,metadata.annotations.kubernetes.io%2Fauth-provider` but fails i to return any values if specifying the certificate provider key like in `http://localhost:7007/api/catalog/entities/?filter=metadata.annotations.kubernetes.io%2Fapi-server-certificate-authority`

## Context
I'm trying to use the new EKS Cluster Processor and Kubernetes Catalog Collector created in the PR https://github.com/backstage/backstage/pull/11789 . I was able to get the cluster processor to ingest clusters into the catalog, but the cluster locator fails to find any of the clusters.

Log lines outputted from the k8s plugin when trying to lookup a service I expect to find the cluster for:
```
[1] 2022-08-16T20:05:37.798Z backstage info ::ffff:127.0.0.1 - - [16/Aug/2022:20:05:37 +0000] "GET /api/catalog/entities?filter=kind=Resource,spec.type=kubernetes-cluster,metadata.annotations.kubernetes.io%2Fapi-server,metadata.annotations.kubernetes.io%2Fapi-server-certificate-authority,metadata.annotations.kubernetes.io%2Fauth-provider HTTP/1.1" 200 2 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2022-08-16T20:05:37.798Z kubernetes info entity.metadata.name=backstage clusterDetails=[] type=plugin
```

## Your Environment

Backstage version: `1.4.0`
@backstage/plugin-kubernetes-backend version: `0.7.0`
@backstage/plugin-kubernetes version: `0.7.0`
@backstage/plugin-catalog-backend-module-aws version: `0.1.7`

- Browser Information: Google Chrome Version `104.0.5112.79 (Official Build) (arm64)`

- Output of `yarn backstage-cli info`: 

```text
yarn backstage-cli info
yarn run v1.22.17
$ /Users/asaferlich/dev/src/github.com/segmentio/backstage-segment/node_modules/.bin/backstage-cli info
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.14.2
yarn: 1.22.17
cli:  0.18.0 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.4
  @backstage/backend-common                        0.14.1, 0.15.0-next.2
  @backstage/backend-plugin-api                    0.1.0, 0.1.1-next.0
  @backstage/backend-tasks                         0.3.3, 0.3.4-next.0
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.0, 0.18.1-next.1
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.4
  @backstage/core-components                       0.10.0, 0.9.5
  @backstage/core-plugin-api                       1.0.4
  @backstage/dev-utils                             1.0.4
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.2
  @backstage/integration                           1.2.2, 1.3.0-next.1
  @backstage/plugin-analytics-module-ga            0.1.18
  @backstage/plugin-api-docs                       0.8.7
  @backstage/plugin-app-backend                    0.3.34
  @backstage/plugin-auth-backend                   0.15.0
  @backstage/plugin-auth-node                      0.2.3, 0.2.4-next.0
  @backstage/plugin-catalog-backend-module-github  0.1.5
  @backstage/plugin-catalog-backend                1.3.0, 1.3.1-next.2
  @backstage/plugin-catalog-common                 1.0.4, 1.0.5-next.0
  @backstage/plugin-catalog-graph                  0.2.19
  @backstage/plugin-catalog-node                   1.0.0, 1.0.1-next.0
  @backstage/plugin-catalog-react                  1.1.2
  @backstage/plugin-catalog                        1.4.0
  @backstage/plugin-github-actions                 0.5.7
  @backstage/plugin-github-pull-requests-board     0.1.1
  @backstage/plugin-home                           0.4.23
  @backstage/plugin-kubernetes-backend             0.7.0
  @backstage/plugin-kubernetes-common              0.4.0
  @backstage/plugin-kubernetes                     0.7.0
  @backstage/plugin-org                            0.5.7
  @backstage/plugin-pagerduty                      0.5.0
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.3, 0.6.4-next.0
  @backstage/plugin-permission-react               0.4.3
  @backstage/plugin-proxy-backend                  0.2.28
  @backstage/plugin-scaffolder-backend             1.4.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.4.0
  @backstage/plugin-search-backend-module-pg       0.3.5
  @backstage/plugin-search-backend-node            1.0.0
  @backstage/plugin-search-backend                 1.0.0
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.0
  @backstage/plugin-search                         1.0.0
  @backstage/plugin-shortcuts                      0.2.8
  @backstage/plugin-stack-overflow                 0.1.3
  @backstage/plugin-techdocs-backend               1.2.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.2
  @backstage/plugin-techdocs-node                  1.2.0
  @backstage/plugin-techdocs-react                 1.0.2
  @backstage/plugin-techdocs                       1.3.0
  @backstage/plugin-user-settings                  0.4.6
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
✨  Done in 0.94s.
```

**Comment by asaf-erlich** [comment]
cc original author of the PR @backjo in case you have any insight or suggestions for how to fix this

**Comment by freben** [comment]
Just noted that your example had an extra slash in it, `?filter/=`. Was that a typo?

Adding here that after discussions on discord, it is theorized that this could be due to the annotation value being too large. Whenever the key or the value is longer than 200 characters, it's not put in the search table at all since database engines do not like to index massive columns.

If this proves to be the culprit, maybe we could adjust the way that the search index is built. If the value is too long but the key still within limits, then maybe we could still store that key/value pair but with either a pruned value, or a placeholder value of some sort.

**Comment by asaf-erlich** [comment]
I suspect that is a typo or copy paste error. I will edit and remove them.

**Comment by asaf-erlich** [comment]
Done.

**Comment by asaf-erlich** [comment]
>If this proves to be the culprit, maybe we could adjust the way that the search index is built. If the value is too long but the key still within limits, then maybe we could still store that key/value pair but with either a pruned value, or a placeholder value of some sort.

That is one option since the query is just checking for the key existing. Alternatively the query could simply avoid searching with that key. There are other values that are aws cluster specific, namely all the ones below:
```
        "annotations": {
            "amazonaws.com/account-id": "<account-id>",
            "amazonaws.com/arn": "<arn>",
            "kubernetes.io/api-server": "https://<url>.<region>.eks.amazonaws.com",
            "kubernetes.io/api-server-certificate-authority": "<very long 1400+ character string>",
            "kubernetes.io/auth-provider": "aws"
            },
```

The query specifically asks for the last 3 and it might be smart to do that because it needs those values returned, but maybe the query could ask for the key existing for the others in the plugin and then error later when reading the values the value is missing.

**Comment by freben** [comment]
Alright, added an update that does index these large-value keys as well, but with a null for the value.

https://github.com/backstage/backstage/pull/13350

**Comment by asaf-erlich** [comment]
Thank you! 🙏
