### ISSUE TITLE
Bazaar plugin: The member link should target the backstage user catalog entity

### ISSUE THREAD

**Issue by anicke** [backstage/backstage#13190]
## Expected Behavior

The backstage user entity ref should be stored for each member and the member link should open the backstage user entity catalog page (i.e. "/catalog/default/user/username").

## Actual Behavior

The member database contains only the "display" name of an user and the member link goes to "https://github.com/${entity.displayName}"

## Steps to Reproduce

* Go to a Bazaar project that you are not a member of.
* Join the project by clicking the "Join project".
* The url in the "Latest members" points to Github.

## Implementation

* Add a new field to the members table that contains the user entity ref.
* Store the user entity ref when adding a new user.
* Update the url of the member list to link to the catalog page of the user.

I plan to work on this issue.

**Comment by benjdlambert** [comment]
@lykkeaxlin thoughts on this?

**Comment by lykkeaxlin** [comment]
A very welcomed improvement! :)

**Comment by pjungermann** [comment]
@anicke seems like your PR resolved this issue and it can be closed, right?

**Comment by anicke** [comment]
@pjungermann It was automatically close due to inactivity. I will soon open that PR again.
