### ISSUE TITLE
backstage configure with helios pipeline

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#13196]
## Feature Suggestion
We want to integrate backstage with helios pipeline. I have tried from past 2 weeks. I did not get, how it should work. There are 2 major configuration file.
helios-config.yml
     build_commands: 
        - npm install --global yarn
        - yarn config list --verbose
        - yarn install
        - yarn tsc
        - yarn build
DockerFile
just standard docker file

I am not sure, If i am missing something. Please  help me on this.

## Possible Implementation
Not Sure

## Context
Adding backstage to helios Pipeline

**Comment by benjdlambert** [comment]
What's the problem that you're seeing here? And what helios are you referring to? Need a little bit more information to help here :pray:
