### ISSUE TITLE
Dismiss Notifications After Optional Timeout Period

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#13205]
## Feature Suggestion

It would be nice if the notifications supported the ability to provide an optional timeout so they would close on their own.

![image](https://user-images.githubusercontent.com/67169551/185227907-59ee2b3e-c458-44b0-9688-37fb9b0fb11f.png)

## Possible Implementation

I'm open to suggestions but one thought was to have an optional `timeout` on the `AlertMessage` and then that could be used to close the alerts after the amount of time has passed on the provided `timeout`. The closing part might be handled in the `AlertDisplay` here: https://github.com/backstage/backstage/blob/d026d2e94ca32b46d9e4c05d6db2e5c4165da4c7/packages/core-components/src/components/AlertDisplay/AlertDisplay.tsx#L44

## Context

We are using the `alertApi` for notifications when Users or Groups are updated in our internal Org management plugin. Currently if you have to edit a few users and/or groups you end up with a stack of alerts you need to click through and close.

**Comment by awanlin** [comment]
I'd very much like to work on this but need some pointers as the best way to move forward and also if this is something that would be wanted

**Comment by benjdlambert** [comment]
Seems like a good idea, maybe implementing something in the component that render's the alert api to call the callback after a period? The `AlertDisplay` needs some love, it was a quick component to get running with 👍

**Comment by freben** [comment]
Another suggestion: should the alert message instead have a flag `transient: true` or similar, and then it's up to the alert display layer to have a configurable time for how long transient things hang around?

I think each plugin (that generates alerts) shouldn't necessarily have fine grained control about exact timings. The timeout could even conceivably be a per-user setting in the future.

**Comment by awanlin** [comment]
Alright, made some good progress on this today:


https://user-images.githubusercontent.com/67169551/188199502-07191ca2-7541-4051-b930-b097699110b6.mov

**Comment by shailendra-ahir-cbre** [comment]
We want this feature :)

**Comment by shailendra-ahir-cbre** [comment]
Congratulations and many thanks to @awanlin
