### ISSUE TITLE
[scaffolder] Hide steps based on a response of an API requests

### ISSUE THREAD

**Issue by taras** [backstage/backstage#13202]
## Context

One of our clients has templates with custom fields that show field options based on an API request. In some cases, it would be preferable to remove steps based on a response from an API request. I couldn't find a way to do with the scaffolder.

If we find a possible implementation that would be accepted, we'll be happy to submit a PR.

## Feature Suggestion

Provide some API that would allow to invoke an asyncronous operation that may modify the steps that are used to render the Stepper component. 

## Possible Implementation

It's unclear what would make a good API in this case considering templates my require different async operations.

**Comment by benjdlambert** [comment]
Hmm not sure about the best way to implement something like this to be honest. You could have a `customFieldExtension` which renders the `JSONSchema` returned, but it's a little tricky as I think that you might lose some of the type safety without defining it in the parameters.

Another though I have had though, is that an action could require more input from the user. So the action could have something like:

```ts
const { versionNumber } = ctx.waitForInput({
 type: 'object',
  properties: {
    versionNumber: {
      type: 'number',
    }
 }
});
```

And this would pause the job until the user visits the task screen again and types in the number and submits the form.

This would be pretty good for adding things like gates to be able to complete certain tasks, and blocking jobs. 

But realistically it's a little tricky to implement right now given that tasks are picked up and held onto and will block the worker. Maybe one for the future, and you could implement this like that.
