### ISSUE TITLE
[scaffolder] Include entity metadata in `ctx.templateInfo`

### ISSUE THREAD

**Issue by taras** [backstage/backstage#13223]
## Context

We have a client who has many templates that use template's tags in the scaffolding process. They are currently using `catalogClient.getEntityByName(ctx.templateInfo.entityRef)` to retrieve the template's metadata. This has the potential of introducing race conditions and it requires catalog client to be passed into steps as discussed in https://discord.com/channels/687207715902193673/1009510870168117338

## Feature Suggestion

Include entity metadata in `templateInfo` on entity prop.

## Possible Implementation

Metadata is retrieved to create the steps. We can attached that metadata to ctx.

**Comment by taras** [comment]
Frontside will work on implementing this feature.

**Comment by benjdlambert** [comment]
Maybe we just provide the metadata from the `template` instead of the entire entity like the `spec` stuff. We don't want to encourage the parsing of the spec from this field if possible. What are your thoughts @taras?

**Comment by taras** [comment]
@benjdlambert that makes sense.

**Comment by taras** [comment]
@dagda1 is going to work on it this week.
