### ISSUE TITLE
.vale.ini points to wrong StylesPath location

### ISSUE THREAD

**Issue by mrjerzy** [backstage/backstage#13224]
## Expected Behavior

Running `vale .` in the Backstage root directory executes vale checks

## Actual Behavior

Running `vale .` reports back that the defined stylepath cannot be found
```bash
> vale .             

E201 Invalid value [/Users/wzhjeki/code/backstage/.vale.ini:1:14]:

   1* StylesPath = .github/styles
   2  
   3  [*.md]

The path '/Users/wzhjeki/code/backstage/.github/styles' does not exist.
```

## Steps to Reproduce

Run `vale .` in the root directory

## Fix 

Point the StylesPath parameter in `.vale.ini` to `.github/vale`

```ini
StylesPath = .github/vale

[*.md]
BasedOnStyles = Vale
```

## Your Environment

- git repository with commit `d851b95dab19dcb7d6a5054c059057ffbb1b594c`
- vale version 2.20.0

**Comment by Rugvip** [comment]
Thank you for reporting! I believe the root `.vale.ini` might actually be unused, but would need to verify that. Doc checks are executed with `yarn lint:docs` rather than vale directly.
