### ISSUE TITLE
Add custom sort functionality to Table's TableFilter

### ISSUE THREAD

**Issue by david-christ** [backstage/backstage#13236]
Currently, the content of a `TableFilter` is sorted alphabetically. It might be valuable to allow programmers to pass in a custom sort function.

## Feature Suggestion

Extend the `TableFilter` interface with a new optional parameter that takes a custom sort function.

```typescript
type TableFilter = {
    column: string;
    type: 'select' | 'multiple-select';
    sort?: (rowA, rowB) => -1 | 0 | 1; // <- new parameter
};
```

## Possible Implementation

JavaScript's `sort()` function allows for custom sort functions to be passed in. So it might be possible to just internally forward the function provided by the new parameter.

## Context

If we e.g. want to filter a table containing details of different users by username, we might want to sort the TableFilter to show names of recently active users at the top.

If the sort function receives the whole row (instead of just the content of the sort field alone), it would also be possible to sort by a variety of criteria without referencing the source data in the outside component.

**Comment by benjdlambert** [comment]
Is this for just the `Catalog` page or is this for all instances of `Table`? We're looking at server side sorting for the Catalog at the minute, so if it's for that it might be worth waiting for this stuff to settle first. #12246. 

Noticed the other issue too #13235 are these meant to be used hand-in-hand?

**Comment by david-christ** [comment]
Hi @benjdlambert , our use-case is for the plain `Table`. E.g.:

```typescript
const filters: TableFilter[] = [
  {
    column: 'My Field',
    type: 'select',
  },
];

// ...

<Table
  // ...
  filters={filters}
/>
```

Regarding the other ticket, we are indeed intending to use both features in the same component for a particular use-case, but could also use them independently in other use-cases. For the table state use-case, we just like to add e.g. shortcut buttons above the table, like you could imagine a "Show my PRs" button on a GitHub PR list. Using again GitHub as an example, if you select reviewers for a PR on GitHub, you notice the list is not sorted alphabetically, but rather by best match, so we might want to sort a filter column e.g. by user is in the same team, user touched the same file you changed in this PR, ...

**Comment by benjdlambert** [comment]
Hmm OK, do you want to whip up a PR and we can discuss more in there? :pray:

**Comment by benjdlambert** [comment]
I know we already have some filtering in the `CatalogTable` that is done client side, maybe some inspiration for you if you were to take a look there too and how all that fits together.

**Comment by david-christ** [comment]
Hey @benjdlambert ,

Thanks for letting us know that a PR for this would be welcome. Always good to ensure that upfront ;-)
We have put this on our team's board and will implement it when the time comes.

Best wishes
David
