### ISSUE TITLE
Card Re-design for Template Marketplace

### ISSUE THREAD

**Issue by NishkarshRaj** [backstage/backstage#13243]
The existing card design for the Template Marketplace/ Scaffodler Page/Create Page is text-rich and not intuitive.

<img width="455" alt="Screenshot 2022-08-19 at 2 37 46 PM" src="https://user-images.githubusercontent.com/35298207/185585869-06b3bf85-33f2-4484-a471-899f8e3d69bc.png">

## Feature Suggestions

It would be great if we enhance the Card design with the following improvements:

- [ ] Add images to the card by referencing path or absolute URL - must have a decent fallback/default image
- [ ] Ability to showcase user-docs for the Template which we can already associate with a catalog of `kind: Template`

Although I am no designer - have a few ideas:

<img width="834" alt="Screenshot 2022-08-19 at 2 43 42 PM" src="https://user-images.githubusercontent.com/35298207/185586666-d10975fe-eabf-4b51-8a9a-7908f7cce0e8.png">

## Context

Visuals are always good for better understanding and quick lookups.

[Backstage Plugin](https://backstage.io/plugins) page is a prime example of this:

<img width="1434" alt="Screenshot 2022-08-19 at 2 45 45 PM" src="https://user-images.githubusercontent.com/35298207/185587052-8632255c-52d7-484a-863e-f57dff7fc66f.png">

And docs are necessary for improving self-service so that users can consume the templates without any support needed.

cc/ @katz95

**Comment by benjdlambert** [comment]
Hey :wave: Thanks for this, Kat is unfortunately no longer working on Backstage, but we're in the process of spinning up a team to deal with some of this ux and design work. In the meantime I think we can use our best judgement and discuss more in the PR's. It might be worth bringing to your attention that I did some redesigning of the template cards in the `/create/next` version of the scaffolder, so they look a little different. Could be worth bringing some of these concepts to 
those new cards too.

![Screenshot 2022-08-22 at 10 52 14](https://user-images.githubusercontent.com/3645856/185880872-b545e0c9-2224-4681-bb99-c9cad5173a33.png)

**Comment by NishkarshRaj** [comment]
Incredible, I've seen a few PRs by you around Scaffolder next but although we're on the latest Backstage version I see a white page on `create/next` - can you please link docs/link to PR I can use to play around.

Cheers,

**Comment by benjdlambert** [comment]
Yeah you'll need to include the new route in your app manually for now, although I'm probably going to change that when it's actually fully working so that you can enable it using a feature flag. It's still all under heavy development, But the form part, and review step is done, just got to do the ongoing tasks part for now, and then some other bits to tidy up.

If you check out the `packages/app/src/App.tsx` and check out the `create/next` part you should be able to see it in the main repo.

**Comment by NishkarshRaj** [comment]
@benjdlambert: another thought on this - alongside adding images and linking TechDocs.

Would it also make sense to hide the tags from the front?

<img width="421" alt="Screenshot 2022-08-31 at 11 01 34 AM" src="https://user-images.githubusercontent.com/35298207/187599663-cc95a61f-c7f9-4334-800c-f4b7cdd5fc8f.png">

We can still use tags for filtering and searching but not showcase them on the card - it will look much cleaner and more concise.
