### ISSUE TITLE
Scaffolder Search incorrectly outputs Templates with no tags for all search

### ISSUE THREAD

**Issue by NishkarshRaj** [backstage/backstage#13328]
## Expected Behavior

Scaffolder search results in list of templates matching the keyword(s) passed in the search.

## Actual Behavior

The search works as expected except in the cases when one or more onboarded template has no tags (`metadata.tag` in `kind: Template` descriptor) associated with it.

When this is the case:

- If you search for a keyword which related to no templates - all templates without any tags are shown in result
- If you search for a keyword which results in existing template - the no tagged templates still pollute the search.

## Steps to Reproduce

This happens on the latest Vanilla Backstage v1.5.0 but we've been facing the issue for quite some time now.

In the attached screenshot we've onboarded two Backstage Templates created by the maintainers:

1. https://github.com/backstage/software-templates/blob/main/scaffolder-templates/create-react-app/template.yaml (With tags)
2. https://github.com/backstage/software-templates/blob/main/scaffolder-templates/gitlab-merge-request/template.yaml (No Tags)

<img width="1440" alt="Screenshot 2022-08-24 at 5 43 27 PM" src="https://user-images.githubusercontent.com/35298207/186416320-72cb68ad-d3cc-4a65-ae9f-52efe8e74508.png">

### Case 1: Search for a keyword not associated with any template

<img width="1440" alt="Screenshot 2022-08-24 at 5 43 34 PM" src="https://user-images.githubusercontent.com/35298207/186416343-3bc4b5c2-79d5-4ce3-9534-07f95f3c18be.png">

### Case 2: Search for a keyword associated with existing template

<img width="1440" alt="Screenshot 2022-08-24 at 5 44 41 PM" src="https://user-images.githubusercontent.com/35298207/186416351-d9834a7c-0a94-4eb3-8fee-b802f1ed187f.png">

## Context

Backstage Scaffolder Search is always polluted by templates with no tags. Although tagging is a good practice we cannot enforce the adopters to tag all templates.

## Your Environment

- MacBook M1 2021
- Google Chrome 
- Node 14.17.3

**Comment by freben** [comment]
Ah! That was a small silly logic error in the free text matcher. Thanks for reporting. Made a PR to address it. https://github.com/backstage/backstage/pull/13349
