### ISSUE TITLE
GitHub topic filter for GitHub Entity Provider

### ISSUE THREAD

**Issue by timja** [backstage/backstage#13329]
## Feature Suggestion

The GitHub entity provider currently only supports repository regex for filtering repositories.
https://backstage.io/docs/integrations/github/discovery

It would be good if we could filter that by a GitHub topic as well.

regexes are not flexible enough.

We have a GitHub org with about 2000 repositories but only 300-400 of them are likely going to be in backstage.

Clicking through the catalog you constantly see rate limit errors currently:
![image](https://user-images.githubusercontent.com/21194782/186433003-170c4aaf-7a63-42ce-bf65-4e50eed8bef9.png)

**Comment by freben** [comment]
Could this be done in the form of just another parameter to the entity provider? Sounds like a sensible possible contribution 🙌

**Comment by timja** [comment]
yes there's a filters block which current optionally takes either a `repository` or a `branch` it could also take a `topic` or `topics` filter

**Comment by timja** [comment]
FYI @brentg-telus

**Comment by marcus-crane** [comment]
Ah yeah, this is something I've been after as well. I thought a topic called `backstage-excluded` might take sense?

**Comment by timja** [comment]
For inclusion you can use the search API to find all repositories matching the topic rather than listing all.

It may also be possible for exclusion but I'm not sure.

**Comment by marcus-crane** [comment]
It doesn't appear possible to exclude topics, only explicitly include them which works but seems like a bit of a step backwards as far as developers who might expect they just need a merge in a catalog file and nothing else

**Comment by marcus-crane** [comment]
That said, I assume the actual paging of the repositories is only a small portion of the rate limit being eaten since it's iterating 100 at a time so 2000 repos is only say 20 calls with the bulk being the actual fetching of the catalog files themselves, one by one.

In that case, it should be doable to just include the topics and then filter out anything matching an exclusion topic so that only those items remaining post-filter are queried?

**Comment by timja** [comment]
> which works but seems like a bit of a step backwards as far as developers who might expect they just need a merge in a catalog file and nothing else

easy enough to bulk-add topics and add them to new repositories though.

if the rate limit could be handled in another way then that would be better too

**Comment by marcus-crane** [comment]
> easy enough to bulk-add topics and add them to new repositories though.

Ah yeah, it's not "hard" by any means, I guess it just changes the existing mental model from "Backstage will automatically discover your stuff, just add a catalog file" to "just add a catalog file and a repo topic"

It's also "easy" (as in not technically difficult) to backfill but I can imagine that a bunch of new repos will get created that don't have the tag and then that translates into internal requests of "Why isn't Backstage finding my stuff" every time someone creates a new project/product etc whereas the inversion (explicitly ignoring repos) is less common?

I think both cases are perfectly valid depending on how your org operates though!

It seems like an extra search based provider might be a benefit here where users can determine any number of things that aren't expressible through the current provider such as "Filter by this topic" or "Filter by the absence of this topic"

![CleanShot 2022-08-27 at 14 06 11](https://user-images.githubusercontent.com/14816406/187010160-171bef89-b471-47c7-a912-478c40978c9f.png)

![CleanShot 2022-08-27 at 14 06 22](https://user-images.githubusercontent.com/14816406/187010162-9fa95fa3-c17b-4e41-a2c8-f3d2810fe5f5.png)

The only thing I'd note is that search with Github can be a bit hit or miss. For repo filtering, it seems fine although out of the box, it appears to return less repositories than what is surfaced by the existing pagination based provider:

![CleanShot 2022-08-27 at 14 02 39](https://user-images.githubusercontent.com/14816406/187010188-db5bcb87-6d30-43ea-9c18-7e540879b5ca.png)

I'm still looking into why that is exactly

**Comment by freben** [comment]
Closing as implemented by #13387
