### ISSUE TITLE
Allow for externally defined links in the AboutCard

### ISSUE THREAD

**Issue by david-christ** [backstage/backstage#13320]
The `CardHeader` of the `AboutCard` currently can only display links to GitHub and TechDocs. It would be great if we could provide additional links to show.

## Feature Suggestion

Currently, the API for the `AboutCard` only takes `variant` as a parameter: `<EntityAboutCard variant="gridItem" />`

Internally though, the `CardHeader` can take a variable amount of links already, see here, where a previously generated array of links is passed in:

https://github.com/backstage/backstage/blob/0e9785b260a82c1e4c2530b02d3ab00a186eee72/plugins/catalog/src/components/AboutCard/AboutCard.tsx#L172

It would be great if the `AboutCard`'s API could expose an interface for developers to provide more links.

## Possible Implementation

In it's most naive implementation, the developer could pass the same `IconLinkVerticalProps` that are used internally. If they want catalogue data to be displayed though, they would also need to access the entity.

```typescript
import PhoneIcon from '@material-ui/icons/Phone';

const entity = useEnity();
const myEntity = getMyEntity(entity);

const myEntityLinkProps: IconLinkVerticalProps = {
  label: 'On-call Roster',
  disabled: !myEntity,
  icon: <PhoneIcon />,
  href: myEntity.href,
};

// ...
    <EntityAboutCard additionalLinks={[myEntityLinkProps, otherEntityLinkProps, ...]} variant="gridItem" />
// ...
```

Alternatively, an abstraction over the catalogue could be used. The `disabled` property can be set internally on basis of the `hrefQuery` returning a valid entry. Given that the content of a metadata annotation can be more than just URLs, the user would also need to provide a formatter function.

```typescript
// AboutCard.tsx
export interface AdditionalLinkProps {
  label: string;
  icon: ReactNode;
  toHref: (annotation: string) => string;
}

export interface AboutCardAltProps {
  variant?: InfoCardVariants;
  suppressScm?: boolean;
  suppressTechdoc?: boolean;
  additionalLinks?: Record<string, AdditionalLinkProps>;
}

// Page.tsx
const additionalLinks = {
  'oncall.com/team-name': {
    label: 'View On-call',
    icon: <BuildIcon />,
    toHref: (slug: teamName) => `https://oncall.com/${teamName}/current-alerts`,
  },
  // ... more links
};
// ...
    <EntityAboutCard suppressTechdoc additionalLinks={additionalLinks} variant="gridItem" />
// ...
```

Lastly, the user could also provide a function to operate on the entity directly. This would allow more flexibility an possibly to re-arrange the links even before or in-between the SCM/Techdoc links.

```typescript
// AboutCard.tsx
export interface AboutCardAltProps {
  variant?: InfoCardVariants;
  additionalLinks?: (entity, viewInSource, viewInTechDocs) => IconLinkVerticalProps[];
}

// Page.tsx
const createAdditionalLinks = (entity: Entity, scmLink: IconLinkVerticalProps, techdocLink: IconLinkVerticalProps) => {
  const result: IconLinkVerticalProps[] = [];

  result.push(scmLink);
  // This example omits pushing techdocLink, because we don't want to show it.

  const annotations = entity.metadata.annotations;
  if (!annotations) return result;

  const teamName = annotations['oncall.com/team-name'];
  if (teamName) {
    const oncallLink = {
      label: 'View On-call',
      icon: <BuildIcon />,
      href: `https://oncall.com/${teamName}/current-alerts`
    };
    result.push(oncallLink);
  }

  // ... Add more links

  return result;
}

// ...
    <EntityAboutCard additionalLinks={createAdditionalLinks} variant="gridItem" />
// ...
```

## Context

We have a variety of external services we want to link. Our on-call, documentation (that are not in TechDocs), CI/CD, dashboards, and more. The `annotations` object is designed to hold references to those external systems. Whilst per the documentation those are rather intended for usage in plug-ins, it would be great to be able to link those on the entity's page directly. We could add our separate `LinksCard` to the entity's page, but it would look much cleaner if those links were sitting with the links that are already present for SCM and TechDocs in the About card.

---

**Edit:** Added more alternatives and added options to suppress SCM or Techdoc links as per the first comment response.

**Comment by tylerd-canva** [comment]
Not sure if this is worth being a separate feature request, but it would be nice to be able to disable the TechDocs link in the AboutCard if TechDocs isn't "setup" yet or docs don't exist for a given component. It's the only link to TechDocs that can't be removed without a patch file.

**Comment by freben** [comment]
Yeah the about card is a bit of a sore spot currently. I think the mindset for that component might be that it's a useful example and fairly useful in a lot of circumstances, but that we haven't had the time to give it a lot of care so we expect that many orgs will replace it with their own, better looking / behaving components. It's not particularly large or complex. So you may want to consider replacing it as one possible way forward, until we get the time to think it through some more.

Some components have been broken down into composite parts so that you'd e.g. do

```tsx
<AboutCard>
  <AboutCard.Header>
    <AboutCard.HeaderLink title={} ... />
    ...
  </AboutCard.Header>
  
</AboutCard>
```

...and stuff like that. And that's expressive and all, but gets to be a pretty large amount of noise for relatively small utility, compared to just building your own.

We also just recently started establishing a pattern for customization of plugins, and that might be something that this turns out to use in the future. We'll see.

**Comment by david-christ** [comment]
I see. In that case, we'll build our own with then. Thanks for your response.
