### ISSUE TITLE
[Github Pull Requests Board] Board fails to load when PR Author has been deleted

### ISSUE THREAD

**Issue by alecjacobs5401** [backstage/backstage#13336]
## Expected Behavior

When the user of an open Pull Request is deleted and replaced by https://github.com/ghost, the Pull Request Board should properly show that the user no longer exists for that Pull Request and continue to display all open/active Pull Requests for the owning group entity.

## Actual Behavior
The Pull Request board completely fails to load with a `TypeError` since the `author` value for the given Pull Request is `null`
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/12898497/186504822-e87ea2e8-b8f7-42a3-99da-4f3a78944152.png">

## Steps to Reproduce

1. Integrate a Backstage instance with the [github-pull-requests-board plugin](https://github.com/backstage/backstage/tree/master/plugins/github-pull-requests-board)
2. Register a `Group` entity
3. Register a Component Entity with a proper [`github.com/project-slug` annotation](https://backstage.io/docs/features/software-catalog/well-known-annotations#githubcomproject-slug)
4. Create a new github user that has access to the GitHub repo referenced in `github.com/project-slug`
5. Open up a Pull request in that repo
6. Navigate to the `Pull Requests` tab/page for the group entity and verify that the Pull Request Board successfully shows the newly opened PR
7. Delete the GitHub user that created the PR
8. Navigate back to the `Pull Requests` tab/page for the group entity and notice the error

## Context

This was a new issue when a user in the organization I belong to was deleted and replaced by https://github.com/ghost.

I was able to find the impacting PRs and closed them. Once they were closed, the Pull Request board loaded as normal.

It looks like the impacting lines are due to the expectation that the [author for a PullRequest](https://github.com/backstage/backstage/blob/ace32e1a646e6a29b81eb2c8749b85dee3690896/plugins/github-pull-requests-board/src/components/PullRequestCard/PullRequestCard.tsx#L30) is always present. Calling just [`author.login`](https://github.com/backstage/backstage/blob/ace32e1a646e6a29b81eb2c8749b85dee3690896/plugins/github-pull-requests-board/src/components/PullRequestCard/PullRequestCard.tsx#L44) here is raising the error.

Not sure if the intended solution is to just handle `author` being optional in the `PullRequestCard` or to enforce an `Author` type is always present when the `PullRequestCard` is being rendered

## Your Environment

- Browser Information: Google Chrome Version 104.0.5112.101 (only version tested)

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.6.0 - darwin/x64
node: v16.14.0
yarn: 1.22.17
cli:  0.18.0 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.4
  @backstage/backend-common                        0.14.1, 0.15.0
  @backstage/backend-plugin-api                    0.1.0
  @backstage/backend-tasks                         0.3.3
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.0
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.4
  @backstage/core-components                       0.10.0, 0.11.0, 0.9.5
  @backstage/core-plugin-api                       1.0.4, 1.0.5
  @backstage/dev-utils                             1.0.4
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.2
  @backstage/integration                           1.2.2, 1.3.0
  @backstage/plugin-analytics-module-ga            0.1.18
  @backstage/plugin-api-docs                       0.8.7
  @backstage/plugin-app-backend                    0.3.34
  @backstage/plugin-auth-backend                   0.15.0
  @backstage/plugin-auth-node                      0.2.3, 0.2.4
  @backstage/plugin-catalog-backend-module-github  0.1.5
  @backstage/plugin-catalog-backend                1.3.0
  @backstage/plugin-catalog-common                 1.0.4, 1.0.5
  @backstage/plugin-catalog-graph                  0.2.19
  @backstage/plugin-catalog-node                   1.0.0
  @backstage/plugin-catalog-react                  1.1.2, 1.1.3
  @backstage/plugin-catalog                        1.4.0
  @backstage/plugin-github-actions                 0.5.7
  @backstage/plugin-github-pull-requests-board     0.1.1
  @backstage/plugin-home                           0.4.23
  @backstage/plugin-kubernetes-backend             0.7.1
  @backstage/plugin-kubernetes-common              0.4.1
  @backstage/plugin-kubernetes                     0.7.1
  @backstage/plugin-org                            0.5.7
  @backstage/plugin-pagerduty                      0.5.0
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.3
  @backstage/plugin-permission-react               0.4.3, 0.4.4
  @backstage/plugin-proxy-backend                  0.2.28
  @backstage/plugin-scaffolder-backend             1.4.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.4.0
  @backstage/plugin-search-backend-module-pg       0.3.5
  @backstage/plugin-search-backend-node            1.0.0
  @backstage/plugin-search-backend                 1.0.0
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.0
  @backstage/plugin-search                         1.0.0
  @backstage/plugin-shortcuts                      0.2.8
  @backstage/plugin-stack-overflow                 0.1.3
  @backstage/plugin-techdocs-backend               1.2.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.2
  @backstage/plugin-techdocs-node                  1.2.0
  @backstage/plugin-techdocs-react                 1.0.2
  @backstage/plugin-techdocs                       1.3.0
  @backstage/plugin-user-settings                  0.4.6
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
```

**Comment by freben** [comment]
@gregorytalita is this something you might be able to look at? Or @alecjacobs5401 maybe you'd be able to issue a pull request to address that particular part of the code since you may have a way of easily reproducing?

**Comment by afscrome** [comment]
Was this fixed by #12803

**Comment by alecjacobs5401** [comment]
Ah, thanks for pointing that out @afscrome!

Do you know what version of the plugin that is using? We recently just did an upgrade to Backstage v1.5.0 _immediately after_ I opened this Issue and as part of that looks like we bumped to 
```
 @backstage/plugin-github-pull-requests-board     0.1.2
```
which looks to be the latest release, but I am still able to reproduce on this version of the plugin. Do you know if the fix will be in the next release?

**Comment by alecjacobs5401** [comment]
Ah, I just did another look at the PR you linked @afscrome and it looks like its a different error with the same root cause, so that might not have been the total fix.

@freben I can try to put together something, but might not be able to get to it until next week. I'll coordinate with my teammates

**Comment by freben** [comment]
The linked PR is definitely already released.

**Comment by alecjacobs5401** [comment]
Bumping this to keep it alive
