### ISSUE TITLE
Simplify the steps needed to install plugins

### ISSUE THREAD

**Issue by iocanel** [backstage/backstage#13356]
Currently, installing plugins is procedure that is performed manually by editing the actual source files.
The process can be quite error prone and can lead to hard to reproduce issues.

## Feature Suggestion
It would be great if there was a tool that could handle those code changes automatically.

## Possible Implementation
Given, that most changes are things like:
- add an import to file X
- add a function to file Z
- add a blob of code inside method Y 

it should be relatively easy to create a [Tree Sitter](https://github.com/tree-sitter/tree-sitter) based utility that could perform those modification to the source file. 

Each plugin could provide some metadata about the nature of the code changes that the tool could use to automate the process.

## Context
I want to be able to install plugins without having to edit source files by hand and have a more `off the self experince`.

**Comment by cmoulliard** [comment]
> a [Tree Sitter](https://github.com/tree-sitter/tree-sitter) based utility

How such an utility could be used ? Do we have to install another tool on the machine of the developer ? @iocanel

**Comment by iocanel** [comment]
> > a [Tree Sitter](https://github.com/tree-sitter/tree-sitter) based utility
> 
> How such an utility could be used ? Do we have to install another tool on the machine of the developer ? @iocanel

Not necesserialy. This tool could be part of `backstage-cli`. Or it could be a totally independant tool.

**Comment by manuelscurti** [comment]
I think there is an on-going RFC for this #11611

**Comment by cmoulliard** [comment]
> I think there is an on-going RFC for this #11611

No as the RFC which has ben implemented refers to what to do at the backend but not at all how we can help a user/developer when they would like to integrate a plugin part of the frontend UI 

Example about some of the changes needed to add by example the new CCF frontend plugin
- Import the plugin: https://github.com/ch007m/my-backstage/blob/main/packages/app/src/App.tsx#L37
- Extend the route: https://github.com/ch007m/my-backstage/blob/main/packages/app/src/App.tsx#L97-L98
