### ISSUE TITLE
The description column in tables should more eagerly expand when there is space for it

### ISSUE THREAD

**Issue by jcarres-mdsol** [backstage/backstage#13358]
## Expected Behavior

Description text spans to take the extra space

## Actual Behavior

Description is eagerly trying to not take the space

## Steps to Reproduce

Have long descriptions in entities, the problem is more obvious when there are less columns

## Context

I would like to see more of the description in the tables, even when removing multiple columns so description has plenty of space it is hardly using it

<img width="1383" alt="Screen Shot 2022-08-25 at 10 00 59 AM" src="https://user-images.githubusercontent.com/1803073/186726500-eec8b4b1-a816-4321-9e38-b828fb8fe0a9.png">

In this example, there are only 3 columns, the second is getting way too much space, which should be taken by description column instead, in addition, description has ton of space in its own column but decides to do ellipses instead.

## environment

backstage 1.5

```

**Comment by awanlin** [comment]
You should be able to adjust that. This is a rough example I spotted on Discord: https://discord.com/channels/687207715902193673/962123996017606707/963736688394395720

```tsx
<Route
      path="/catalog"
      element={
        <CatalogIndexPage
          columns={[
            CatalogTable.columns.createNameColumn(),
            {
              title: 'Test',
              width: '10%',
              field: 'resolved.name',
              highlight: true,
              render: ({ entity }) => entity.metadata?.name,
            },
          ]}
        />
      }
    />
```

**Comment by jcarres-mdsol** [comment]
Tried it, strange enough as soon as I add any kind of `width` even if it is 50% or 300% it will render it as a very small column
```
               columns={[
                  CatalogTable.columns.createNameColumn(),
                  CatalogTable.columns.createOwnerColumn(),
                  CatalogTable.columns.createSystemColumn(),
                  {
                    title: 'Description',
                    width: '80%',
                    field: 'resolved.description',
                    highlight: false,

                    render: ({ entity }) => entity.metadata?.description,
                  }
      ]}
  ```

Result

<img width="887" alt="Screen Shot 2022-08-26 at 4 27 42 PM" src="https://user-images.githubusercontent.com/1803073/187002581-97d70346-1a0a-496d-ba85-8138161836cb.png">

**Comment by jcarres-mdsol** [comment]
Ok, somehow the two last columns of the table will ignore the width setting and be always as small as they can get, moving columns around will always make the two on the right as small as possible.
The other columns will share equally the space unless overriding the width to share less. They can never take more than a share of the space left
