### ISSUE TITLE
Support ae-dir LDAP Vendor

### ISSUE THREAD

**Issue by timbuchwaldt** [backstage/backstage#13401]
Our LDAP vendor (https://ae-dir.com/) returns the DN property under the `dn` attribute, unlike the default 'entryDN'. The UUID is in `entryUUID`  though.

## Feature Suggestion

It would be great if either dn/uuid settings were overridable by the user or the ae-dir LDAP implementation could be added. One way to find out if ae-dir is used is querying the root-DSE and checking if it contains the `aeRoot`  property

**Comment by freben** [comment]
Cool - yeah, we'd love to get even better support for more vendors.

[This is where](https://github.com/backstage/backstage/blob/c657dbeaa73ccf037a5182cdcb6392e546d07687/plugins/catalog-backend-module-ldap/src/ldap/client.ts#L219) the client tries to deduce what the vendor is, and [this is where](https://github.com/backstage/backstage/blob/c657dbeaa73ccf037a5182cdcb6392e546d07687/plugins/catalog-backend-module-ldap/src/ldap/vendors.ts#L24) you find the current vendor definitions.

We could in theory make it possible to set the vendor explicitly on the provider/processor constructor, but so far we have leaned against autodetection.

Would you like to try to contribute this vendor support in an autodetecting way for starters?
