### ISSUE TITLE
Bitbucket Server Entity Provider - projectKey is case sensitive 

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#13403]
## Expected Behavior

The `projectKey` filter should be case insensitive or it should be documented that case matters

## Actual Behavior

After setting up the Bitbucket Server Entity Provider as per the docs nothing was getting picked up. After some investigation we determined that we needed to use the proper case for the `projectKey`.

## Possible Solution(s)

We could simply add some documentation about this to this page: https://backstage.io/docs/integrations/bitbucket/discovery

Or we update the `test` of the `projectKey` to be case insensitive:

https://github.com/backstage/backstage/blob/c91723ffd60a77cf6e4987613caa565cd49f24d2/plugins/catalog-backend-module-bitbucket-server/src/providers/BitbucketServerEntityProvider.ts#L168

## Steps to Reproduce

1. Follow the steps to setup the Bitbucket Server Entity Provider: https://backstage.io/docs/integrations/bitbucket/discovery
2. Setup the provider configuration using a `projectKey` that has various casing
3. Run `yarn dev`

**Notice:** Nothing is getting picked up but the Bitbucket Server Entity Provider

## Context

While trying to setup the Bitbucket Server Entity Provider we noticed that nothing was getting found which was very confusing. After working thorough the code we found that because all our Projects in Bitbucket are upper case the `projectKey` also needs to be upper case. Once we fixed that everything worked but it wasn't clear that it was case sensitive

## Your Environment

This is pretty specific to the Bitbucket Server Entity Provider and if you use the `projectKey` filter and no other environment specific items.

**Comment by awanlin** [comment]
@pjungermann could this also be an issue with the Cloud implementation? Do you have any thoughts on this?

**Comment by Rugvip** [comment]
Is the project key concept on the Bitbucket side case-insensitive? In that case I feel it would be safe to make it case insensitive on our side too. Otherwise, documentation update? 🤷

**Comment by pjungermann** [comment]
@awanlin I'm not aware that Bitbucket Cloud is case-insensitive. I only know uppercase keys. And I provided filters as such, too.

As the filter is a RegExp, you could make the RegExp case-insensitive, too, btw.
