### ISSUE TITLE
Do not block template creation, when a task is still being executed (blocking parallel execution)

### ISSUE THREAD

**Issue by ViniciusSouza** [backstage/backstage#13419]
Today, when a template with a long running action is being executed it blocks new templates creation.

![image](https://user-images.githubusercontent.com/1587176/187318292-b496dd78-08ef-40ab-8962-29d428d773b6.png)

![image](https://user-images.githubusercontent.com/1587176/187318307-79aa62cd-49de-4e51-886b-9922f56d9d99.png)

We have developed an integration with Argo Workflow and some workflows take some time to complete, in order to be able to use the output of the workflow on the next step. We have a wait-workflow execution action, that keeps querying the Ago Status API, when the workflow completed (success or not) we continue the steps.

As you can see at the picture above, we are not able to execute others template until the process finishes.

## Feature Suggestion

Using [worker threads](https://nodejs.org/api/worker_threads.html) to create to execute the action steps.

## Possible Implementation

[Scaffolder tasks](https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/src/scaffolder/tasks), more specifically the `TaskWorker.ts` can create a new thread to avoid a long running task to block others tasks.

## Context

I put together [this repository](https://github.com/ViniciusSouza/mgoc/tree/visouza/long-running-action) to help illustrate the issue.

**Comment by benjdlambert** [comment]
Yep, looks like we could probably increase the amount by default to 3 or so. We've also discussed being able to schedule these tasks on with Kubernetes Jobs, but nothing has been planned yet. This could give us a little more freedom to maybe remove some of these `TaskWorker` limits, and just have the scheduler push jobs to K8s or some other scheduling interface. But nothing solid yet. @ViniciusSouza, do you want to contribute upping the default limit, but in the meantime you can set `taskWorkers: 3` as an option to the `createRouter` function in the `packags/backend/src/plugins/scaffolder.ts` to work around this issue.
