### ISSUE TITLE
Supress pre-release changes from backstage upgrade helper when not relevant

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#13446]
## Feature Suggestion

When comparing non pre-release versions in the backstage upgrade helper, it shows the change logs for intermediate pre-release versions.  In the following example, the change log for `1.5.0` includes all the changes for `1.5.0-next.*`, so it should be sufficient to only show the 1.5.0 and 1.5.1 change logs.

## Possible Implementation

![image](https://user-images.githubusercontent.com/289860/187650050-53398ac2-82e6-4fd2-b672-d209858b694e.png)

Things get a bit more complicated if one (or both) sides is a pre-release version.  You could be clever and exclude the pre-release versions for any (e.g. if comparing 1.4.0-next.2 to 1.6.0.next-1 you could keep the pre-release changes logs for `1.4.0-next.3` and `1.6.0.next-0` but supress `1.5.-.next-*`, but that may be more trouble than it's worth.  The big benefit will come from optimising hte case where neither side of the comparison is a pre release.

**Comment by Rugvip** [comment]
Oh yes totally, is this something you'd like to contribute? Opening this up for contributions either way though, over in the https://github.com/backstage/upgrade-helper repo

**Comment by sohamchari** [comment]
Hi, I would like to contribute to this issue.

**Comment by jhaals** [comment]
Fantastic, I'll assign you to it!

**Comment by prikshit-1103** [comment]
Hi, I would like to contribute to this issue.

**Comment by prikshit-1103** [comment]
@jhaals I have discussed with @sohamchari  regarding it and he has also agreed to let me work on this issue ,
so could u please assign this to me ?

**Comment by VladMasarik** [comment]
@sohamchari @prikshit-1103 Feel free to continue your work, but I would like to note that there is an already existing PR https://github.com/backstage/upgrade-helper/pull/9

**Comment by vinzscam** [comment]
Closing this issue, since prereleases aren't published anymore https://github.com/backstage/backstage/pull/13967
