### ISSUE TITLE
Add link to "Keeping Backstage Updated" to Upgrade Helper 

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#13447]
## Feature Suggestion
It would be helpful if the backstage upgrade helper had a link back to https://backstage.io/docs/getting-started/keeping-backstage-updated

I'd be happy to have a go at adding this myself, but couldn't find the source for the upgrade helper.

**Comment by awanlin** [comment]
@afscrome great idea! I think this is what you are looking for: https://github.com/backstage/upgrade-helper

**Comment by awanlin** [comment]
Still a good idea 👍
