### ISSUE TITLE
Entity Relations Schema/Typescript issue

### ISSUE THREAD

**Issue by theute** [backstage/backstage#13456]
Same issue as: https://github.com/backstage/backstage/issues/11565
There was a fix: https://github.com/backstage/backstage/pull/11568

But it never made it to a release of @backstage/catalog-model and the problem still exists.

Thanks !

**Comment by theute** [comment]
Well I guess it duplicates https://github.com/backstage/backstage/issues/11753 sorry for the noise

**Comment by theute** [comment]
Reopening as I thinks it's still an issue since using "spec: dependsOn" doesn't allow for custom relationships.

**Comment by Rugvip** [comment]
@theute could you elaborate a bit on what the exact issue is?

**Comment by Rugvip** [comment]
To be clear as well, emitting entities with the `relations` field set from a processor is not possible, you'll need to emit the relations themselves separately.

**Comment by theute** [comment]
I thought the issue was clear in https://github.com/backstage/backstage/issues/11565 :)

And I was also trying to emit entities with the "relations" field like the original author:
`apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: xxx
  description: ''
  annotations:
    github.com/project-slug: https://github.com/xx/xx
spec:
  lifecycle: production
  owner: xxx
  type: service
relations:
  - type: ownedBy
    targetRef: group:xx`
    
   You are saying that this is not permitted, I will try with relations separately.
   
   Now I'm wondering about that fix https://github.com/backstage/backstage/pull/11568 it's not released but it's merged.

**Comment by Rugvip** [comment]
#11568 is released, but that is the schema for the format of output entities, the ones that you read from the catalog. The schema for what you're allowed to have as input into the catalog is a bit different, and it's unfortunately not something we have a schema for atm. In particular you're not allowed to have any `relations` at the top level, those must all be expressed or discovered in other ways.

**Comment by theute** [comment]
Ok, thanks !
