### ISSUE TITLE
Add well-known annotation for a issue tracker link to display on entity AboutCard

### ISSUE THREAD

**Issue by jpeach** [backstage/backstage#13472]
## Feature Suggestion

There's a high probability that organizations have issue trackers that are tracking issues for components. Today, you can add a generic link metadata to an entity and link to the component issues from the EntityLinksCard, but it would be nice to highlight this on the same level as the source and documentation (IMHO the issues are closely related at the same level).

## Possible Implementation

- Define a well-known annotation for an issues link, perhaps `backstage.io/view-issues-url`
- Update the AboutCard component to add the issues link to card header icon row, next to the source and docs links.

## Context

This would be a simple way to provide a clean method of navigation from the catalog to the appropriate issue tracker. It's easy to implement, easy for entity providers to support and will work with many (all?) different issue trackers. The same mechanism could reasonably work for teams as well as components by linking to an issue dashboard rather than a specific issue query.

**Comment by freben** [comment]
Could there be a use case for `metadata.links` in here, instead of annotations? https://backstage.io/docs/features/software-catalog/descriptor-format#links-optional

**Comment by jpeach** [comment]
Yeh that's what we are doing right now. I would like to get the additional UI on the about card header though. After all, the same argument about the links card could be used with tech docs and source links :)

**Comment by Rugvip** [comment]
We're thinking this is a bit too specific to add as a general feature for all about cards tbh. For now we'd recommend that you copy and create your own `AboutCard`. We very much want to find ways to make it more customizable and extensible though, but our focus is in other areas right now.

**Comment by jpeach** [comment]
> bit too specific to add as a general feature for all about cards 

The way I was thinking about this is that it is no more specific than the source location. If some entity has a source location, then it's highly likely that it also has an issue tracker location.

**Comment by Rugvip** [comment]
@jpeach I'd say it's quite common to not use the SCM issue trackers, but some external tool instead. I'm thinking that this is something we could add if we make the about card more flexible and customizable, but until then I recommend that you use a custom one.

**Comment by jpeach** [comment]
Closing this out, since we don't have consensus.
