### ISSUE TITLE
OKTA Integration failure

### ISSUE THREAD

**Issue by kumar385** [backstage/backstage#13491]
Hi,
I am trying to integrate OKTA - backstage i was getting error **"The Backstage Login provider is not configured to support sign-in"**.
This was not error before were getting before i update the packages by running **_yarn backstage-cli versions:check --fix_**

Okta received the request the authentication is success.
![image](https://user-images.githubusercontent.com/3529693/187974671-39fdec73-2514-4983-b27b-fd95839146f3.png)

app-config.yml

```
auth:
  environment: development
  providers:
    okta:
      development:
        clientId: xxx <<redacted for ticket>>
        clientSecret: xxx
        audience: xxx

```

App.tsx

```
import { oktaAuthApiRef } from '@backstage/core-plugin-api';
import { SignInPage } from '@backstage/core-components';

const app = createApp({
  apis,
    components: {
        SignInPage: props => (
          <SignInPage
            {...props}
            auto
            provider={{
              id: 'okta-auth-provider',
              title: 'Backstage Login',
              message: 'Sign in using okta',
              apiRef: oktaAuthApiRef,
            }}
          />
        ),
      },

```

--
PS C:\Projects\cna-backstage> yarn backstage-cli info
yarn run v1.22.19
$ C:\Projects\cna-backstage\node_modules\.bin\backstage-cli info
OS:   Windows_NT 10.0.19042 - win32/x64
node: v14.17.0
yarn: 1.22.19
cli:  0.18.1 (installed)
backstage:  1.5.0

Dependencies:
  @backstage/app-defaults                          1.0.5
  @backstage/backend-common                        0.15.0
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.5
  @backstage/core-components                       0.11.0
  @backstage/core-plugin-api                       1.0.5
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.3
  @backstage/integration                           1.3.0
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-app-backend                    0.3.35
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.4
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.5
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-import                 0.8.11
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.1.3
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-github-actions                 0.5.8
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.4
  @backstage/plugin-permission-react               0.4.4
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-module-pg       0.3.6
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-tech-radar                     0.5.15
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 16.44s.

**Comment by Rugvip** [comment]
It is now a requirement to explicitly configure providers for sign-in, see https://backstage.io/docs/auth/identity-resolver for more details

**Comment by Rugvip** [comment]
Will close this, let us know if we missed anything!

**Comment by madianas21** [comment]
Hi! Is it possible to provide a working example for Okta?
