### ISSUE TITLE
[RFC] Rate Limiting || Backstage <<>> Providers

### ISSUE THREAD

**Issue by NishkarshRaj** [backstage/backstage#13531]
**Status:** Open for comments

## Need

Backstage is built in an abstract manner that allows us to integrate with different providers like GitHub, GitLab, etc. that act as the source of truth for catalog descriptors. 

The different providers have different API requests quota which we might exceed as our adoption of the Portal grows with time.

Thus, we get erratic behavior due to `429: Too many requests` which includes:

- Errors are thrown on UI 

- Unable to register new catalogs

- Unable to use Scaffolder (fails Fetch template step)

- Unable to poll updates from the source of the catalog

## Alternatives

The workarounds I got are mentioned below - although we use GitLab, I think the alternatives are general enough to follow and extend.

The [GitLab Rate limits](https://docs.gitlab.com/ee/user/gitlab_com/#gitlabcom-specific-rate-limits) allow us 2000 requests per minute. We use a GitLab Service account for setting up the integration.

#### 1. Changing the polling time for catalog 

We can update the processing interval in the `packages/backend/src/plugins/catalog.ts` by following this [document](https://backstage.io/docs/reference/plugin-catalog-backend.catalogbuilder.setprocessingintervalseconds)

The challenge to this approach is that the polling time is being shared between different environments (if we host Backstage in Dev, Stage, Production, etc. with the same code base) - had this been **configuration driven** rather than **programmatic** - we could switch between the polling times of the environments. 

This is needed to prioritize the Production environment performance.

#### 2. Poll Users and Members Catalogs

There can be 1000s of users and 100s of teams which we can write descriptors for.

For the time being, we have restricted registering `kind: User` and `kind: Group` from Backstage UI and whitelisted the locations file for the central repository via static configuration.

#### 3. GitLab Discovery

[GitLab Discovery Processor](https://backstage.io/docs/integrations/gitlab/discovery) crawls the whitelisted groups and subgroups to find the Backstage catalog descriptors recurringly - and can be set to `*` for lookups in all branches - this can lead to an extreme number of wasted API calls.

- Enabled check for skipping locations file for repositories without the catalog descriptor. 

#### 4. Orphaned Catalogs

Orphaned Catalogs in all environments have 2 broken references - one of the catalog (`kind: *`) and one of their source location `kind: Location`.

These locations are polled with no reason or value and must be cleaned up.

Here is an [existing script](https://github.com/backstage/backstage/tree/master/contrib/scripts/orphan-clean-up) that we customized for a CI job.

## Proposal

I am not quite sure, looking for comments on what should be the best approach but these things come into mind:

- Use of WebHooks

- This seems like a general issue that most scaling organizations using Backstage should be facing / will face - I didn't find many documents or issues that could highlight the problem - would like to know how other adopters are managing this concern

The only issues related I found were:  #3734 #10866

**Comment by marcus-crane** [comment]
Heya, there is a pinned RFC about webhook handling that you can read more about here: https://github.com/backstage/backstage/issues/11082

**Comment by NishkarshRaj** [comment]
Thanks, will take a look into that but it seems mostly for GitHub.

**Comment by pjungermann** [comment]
PR #13931 might be of interest for you @NishkarshRaj 

Feedback welcome

**Comment by NishkarshRaj** [comment]
> PR #13931 might be of interest for you @NishkarshRaj
> 
> Feedback welcome

Awesome stuff! Looking forward to using your great work 💯

**Comment by shailendra-ahir-cbre** [comment]
Put your catalog-info files in a storage service. (which will not have a smaller request quota). Use webhooks to listen for interesting events (like creation/update/delete) from the source and update the files in the storage service.

**Comment by kmatyukhin** [comment]
Hello! I have just implemented a repeatable `UrlReader` for our internal Backstage installation using the [p-retry](https://www.npmjs.com/package/p-retry) package. In case of a 429 error, it retries the request with an exponential back-off. If you think this is a reasonable solution, I can port it to the all default readers in the main repository.

**Comment by drodil** [comment]
This same rate limiting happens also with the Bitbucket server and cloud instances. I hope there's some generic way to improve this in all of the providers like what @kmatyukhin mentioned above. I think porting that would make a lot of sense!

**Comment by freben** [comment]
Without having seen that retry mechanism, I'm only cautiously optimistic toward it in all honesty. I absolutely don't mean to be negative or put down the fine work you've done, so please take this message with a hopeful but cautious positivity in mind.

What I mean is - properly dealing with rate limiting is _really hard_, especially when you have a distributed system like the catalog accessing a shared resource. First, the truly safe way of dealing with it is to have a shared locking mechanism that harnesses the _global_ rate of requests across all systems, that all reading is using as a gatekeeper.

Secondly, bear in mind: the processing engine is a singular, throughput-optimized worker pool on which _all work_ happens, not just the small part that happens to hit rate limits. Adding blocking retries at a low level inside the URL reading, has the effect (seen from the outside) of reads taking a potentially abnormally long time to complete. This also means that the tasks issuing those reads take a potentially abnormally long time to complete, choking/starving the entire work queue just spinning and doing no effective work while waiting for the rate limit to stop blocking.

Then there's always the risk that not-perfectly-tuned retries actually exacerbate the rate limit problem.

So in the context of the processing queue, I think what we'd have to do is to abort instantly in the face of a rate limit response, and _putback the task_ in the queue with a dynamic time window that corresponds to the ideal time to try again, and _also_ ensuring that other tasks that happen to get started in the meantime don't even try to make a request but instead yield and also putback somehow.

I feel that there's a risk that the proposed solution might work for (1) a small number of retries, (2) within a very narrow time window, and (3) only when very close to the limit. In a system that's way over limit, effectively needing to back off by a factor of more than a handful of percent globally, would quickly get overburdened and stop working. Imagine the extreme case of having a billion entities, all refreshing once per second _each_ when there's no rate limit, and then you introduce a global rate limit of one request per second. Just to illustrate.

**Comment by kmatyukhin** [comment]
I absolutely agree with all that thoughts. I can expose all the handles that [retry](https://github.com/tim-kos/node-retry#retryoperationoptions) package has in the app-config, so everyone will be able to tune retry strategy according to their own situation. Does it make sense? In our case, we only have about 3000 entities in the catalog, but we encountered very strong Bitbucket Server limits. As a result, Backstage worked very unstable and sometimes crashed after scaffolder tasks failed because it was unable to retrieve template pieces. After adding retry logic, everything started working pretty well. I understand that it's a very particular case but I think it could help to many adopters.

**Comment by drodil** [comment]
@kmatyukhin exactly the issue we are facing with bitbucket server. We even thought of doing some extra functionality to just fetch all catalog infos and provide them to backstage from s3 bucket or something like that.

Could you do small PR to show your retry logic to the BB server provider? Maybe seeing it in place would make it more easier to discuss and if it looks good, it could be extended to other providers?

**Comment by ahhhndre** [comment]
Could the event framework also be a solution? Would mean updating the Bitbucket Server provider to add support. https://github.com/backstage/backstage/issues/10866#issuecomment-1327924876

I’ll admit, setting up web hooks on Bitbucket Sever isn’t easy if you have many repos, there’s no way to do it at the project level at least for the version we are on.

We are also seeing these error but they are much more random and spaced out. We are moving to GitHub so haven’t really done much to resolve them though

**Comment by kmatyukhin** [comment]
@drodil The trick is in the wrapping fetch call inside of UrlReader with pRetry. Something like that:
```javascript
    try {
      response = await pRetry(
        async () => {
          const response = await fetch(bitbucketUrl.toString(), {
            headers: {
              ...requestOptions.headers,
              ...(etag && { 'If-None-Match': etag }),
            },
            // TODO(freben): The signal cast is there because pre-3.x versions of
            // node-fetch have a very slightly deviating AbortSignal type signature.
            // There difference does not affect us in practice however. The cast can be
            // removed after we support ESM for CLI dependencies and migrate to
            // version 3 of node-fetch.
            // https://github.com/backstage/backstage/issues/8242
            ...(signal && { signal: signal as any }),
          });
          if (response.status === 429) {
            throw new Error(response.statusText);
          }
          return response;
        }, {
          forever: true,
        }
      );
    } catch (e) {
      throw new Error(`Unable to read ${url}, ${e}`);
    }
```
@ahhhndre We encounter the 429 error most frequently in the entities processing loop rather than in the Bitbucket provider.

**Comment by drodil** [comment]
@kmatyukhin nice. Will try that out tomorrow how it works for our case with hundreds of repos. 

@ahhhndre don't think the event system will help here as the problem really becomes only with lot of projects and repos. And as you said, setting up the webhook is a lot of work (unless it can be automated somehow). 

Apparently the bitbucket cloud provider uses the search api to find the catalog files. It seems this is not available on the server side which could help this issue at least a bit.

**Comment by kmatyukhin** [comment]
I know, it's just an example :) and anyway it is going to repeat only in case of _429: Too many requests_ result. And also, as I said before, in the real solution all the retry options will be exposed in app-config and by default `retries` will be zero to make it compatible with the current behavior.

**Comment by Rugvip** [comment]
I think the cleanest solution to hitting rate limits might be to dynamically slow down the processing interval so that rate limits are no longer hit, and of course clearly surface the current interval through metrics. With processors doing their own retry loops we'll end up in a situation where the processing loop is more or less permanently stuck with a filled queue, which impacts UX when users are trying to queue refreshes for individual entities.

**Comment by kmatyukhin** [comment]
Ok, @Rugvip . I got your point. I stop my attempts to add retry into UrlReader in the mainline.

**Comment by kmatyukhin** [comment]
Hi, @Rugvip! Can we reopen this RFC? The 429 error is really annoying us and we are getting more and more complains from our users. Using pRetry wrapper around fetch works pretty well and we use it extensively in our internal Bitbucket plugins but unfortunately there are many other places in Backstage core packages like `integration` or `scaffolder` that we are not able to patch in our local instance. So I would like to provide my fix for community review and deciding.

**Comment by drodil** [comment]
Would it help to also provide incremental catalog providers for services with rate limiting?

**Comment by Rugvip** [comment]
Yep I think it makes sense to move over a lot of the provider implementations to use incremental ingestion!

**Comment by kmatyukhin** [comment]
Hi, @Rugvip! Will you please review #18096. It implements my idea about repeating Bitbucket Server API calls in case of 429 error.

**Comment by sharadpattanshetti** [comment]
We had the same issue with our backstage instance integrated with Gitlab. We increased setprocessinginterval which has reduced the 429 errors. However, this is common to all the processors but we wanted to configure the different schedule for some of the processors. Like we have a processor which loads the organizational employee data and it needs to be triggered only once a day, so is it possible to do that? 
FYI - We are on backstage v1.13

**Comment by wjdavis5** [comment]
Just found this as I was researching implemented a Distributed locking mechanism into EntityProvider. As we scale horizontally we dont want N instances of provider hitting the various remote apis. Having a distributed scheduler would be nice too.
