### ISSUE TITLE
Dockerfile uses yarn config set python which is no longer support in Yarn 3

### ISSUE THREAD

**Issue by marcus-crane** [backstage/backstage#13564]
I'm going to circumvent the actual template this time since it's more just something that probably needs a tidy up but hasn't caused me an actual issue (yet?)

Within various Dockerfile, `yarn config set python` is used. As far as I understand, this is to ensure [node-gyp uses the proper Python executable](https://www.npmjs.com/package/node-gyp#user-content-configuring-python-dependency) to avoid issues such as https://github.com/backstage/backstage/issues/11583

As far as I can tell, it's technically still valid as the container will be using the stock `Yarn 1` shipped with the Node container and only bumped to Yarn 3 further in the execution flow when the `.yarn` files are copied in.

Yarn 3 itself doesn't appear to let you set arbitrary values anymore, only a handful of preset ones so `yarn config set python` isn't a valid command and presumably it being set earlier doesn't actually have any effect.

I only noticed this because I was manually upgrading Backstage and added `COPY .yarn` to the top of my file instead of at the bottom which caused my CI to fail.

In the meantime, it appears that you can set a `PYTHON` environment variable so it's probably just as straightforward as swapping `yarn config set python /usr/bin/python3` to `ENV PYTHON /usr/bin/python3` within the app template and current Dockerfiles.

Happy to open a PR for this later on.

**Comment by jhaals** [comment]
Hi Marcus!
Let's make sure we mention this in the [migration guide](https://github.com/backstage/backstage/blob/master/docs/tutorials/yarn-migration.md) first and then update this in the create-app template once we have officially made the switch!
Feel free to create PRs 🙏

**Comment by benjdlambert** [comment]
Closing as this looks to be fixed now! Thanks! :pray:

**Comment by marcus-crane** [comment]
Ah, did we want to update the template as well? I'm on holiday at the moment so I haven't opened anything yet but I can keep a note of it and open a PR when the project is formally switched over 🙂

As far as the "issue", yep it is closed
