### ISSUE TITLE
Templates' START OVER button retains some unfortunate state

### ISSUE THREAD

**Issue by ericbottard** [backstage/backstage#13594]
## Expected Behavior
Once a template has rendered and I click on START OVER, I expect to re-start from a coherent state. 

## Actual Behavior
I understand keeping the values that were just used is a _feature_, not a _bug_ and was done on purpose.
Yet, this has unfortunate consequences when _e.g._ using json-schema `dependencies`:

If for example, parameter `something` depends on `myBoolean` being set and I first run a template with `myBoolean=true` and `something=some value`, then START OVER and uncheck `myBoolean`, the visual representation for `something` correctly goes away (thanks to react-json-schema magic). HOWEVER, the previous value of `something=some value` has been retained and will be passed to actions, which can cause some nasty side effects.

**Comment by benjdlambert** [comment]
Hmm yes, so I actually think that we might have a fix for this, but it's dependent on a few things. #13428 and #13017. Basically what we want to do is enable the omission of extra data in the form state that doesn't meet the requirements for the jsonschema and then it should clean up the extra data that's in there from before.
