### ISSUE TITLE
[Search] Be less restrictive with unknown keys on query endpoint

### ISSUE THREAD

**Issue by pedronastasi** [backstage/backstage#13597]
## Feature Suggestion

Enable additional/custom params to Search query at GET - /query by implementing a minor change on:

[/plugins/search-backend/src/service/router.ts#L75-L82)](https://github.com/backstage/backstage/blob/master/plugins/search-backend/src/service/router.ts#L75-L82)

## Possible Implementation

It could work by adding an additional property at requestSchema  so that people can pass any custom/additional params to the search query object, such as.:

```
 const requestSchema = z.object({
    term: z.string().default(''),
    filters: jsonObjectSchema.optional(),
    types: z
      .array(z.string().refine(type => Object.keys(types).includes(type)))
      .optional(),
    pageCursor: z.string().optional(),
    customQueryParams: z.array(z.record(z.string(), z.any())).optional()
  });
```
 on [/plugins/search-backend/src/service/router.ts#L75-L82)](https://github.com/backstage/backstage/blob/master/plugins/search-backend/src/service/router.ts#L75-L82)

and on 
[/plugins/search-common/src/types.ts](https://github.com/backstage/backstage/blob/6232b480cbb7768681dd3e6b53726ae3f3681436/plugins/search-common/src/types.ts#L24-L29)

We could define the interface as 

```
interface SearchQuery {
    term: string;
    filters?: JsonObject;
    types?: string[];
    pageCursor?: string;
    customQueryParams?: Record<string, any>[]
}
```

## Context

At Expedia Group, we recently upgraded our Backstage instance to a more recent version, in which the added requestSchema validator is causing some conflicts in our implementation. In our particular case, we make use of ElasticSearch aggregations feature to return some stadistics of the query results, apart from few other queries. Moreover, as many people implement elasticSearch as their preferred searchEngine, by adding an extra param on the ResquestSchema  as a `customQueryParams:Record<string, any>[]`, for example,  will allow everyone to add extra custom queries that were previously  sent through it and had  not gone through any schema validation in previous versions. Nowadays, with the current one, if we implement it with any other necessary param  , it automatically deletes it due to  the `requestSchema `.

**Comment by iamEAP** [comment]
Hey @pedronastasi! Thanks for starting discussion on this.

Definitely understand the desire to have a bit of an escape hatch to be able to work around limitations of the interface, but I think we'd prefer to expand the interface to cover your use-case. Aggregations are definitely on our mind as something we want to support!

**Comment by pedronastasi** [comment]
Ok. Great! So it'd be something like this:
```
interface SearchQuery {
    term: string;
    filters?: JsonObject;
    types?: string[];
    pageCursor?: string;
    aggregations?: string[];
}

```


```
const requestSchema = z.object({
    term: z.string().default(''),
    filters: jsonObjectSchema.optional(),
    types: z
      .array(z.string().refine(type => Object.keys(types).includes(type)))
      .optional(),
    pageCursor: z.string().optional(),
    aggregations: z.array(z.string()).optional()
  });
```

Can I be assigned to this?

**Comment by camilaibs** [comment]
Hi @pedronastasi , I believe this issue is related to yours: https://github.com/backstage/backstage/issues/8468

We have seen the growing necessity to have an extensible search query and context and would love to hear your ideas here, feel free to assing to yourself, your contribution is more than welcome! One more thing, @iamEAP is in a different timezone than mine this week so he might answer you a little later, let's wait for his consideration before diving into coding 🙂

**Comment by pedronastasi** [comment]
Oh, yeah, they're related.I hope read from @iamEAP  soon.

**Comment by pedronastasi** [comment]
Ok. To keep it simple, we can work on `aggregations`  only; however, we're really interested in that "superset as we need different parameters I mentioned and it's continuously expanding as we improve our search plugin. So, we have no option but to pass it through the generic JSON object for filters .

What we currently do is to pass aggregation in the following way as query  params:

```
aggs: [
        'docType',
        'capability',
      ]
```

and we finally get a response 
<img width="480" alt="image-2022-08-10-15-33-38-503" src="https://user-images.githubusercontent.com/73761278/191087037-25a0ae11-195b-45b3-9673-92bd02b74512.png">

**Comment by pedronastasi** [comment]
We, then,  show them in the modal search
![image](https://user-images.githubusercontent.com/73761278/191299820-eccd8213-9819-4a4b-96ea-1d66f9e9bfdc.png)

**Comment by iamEAP** [comment]
Hey again @pedronastasi!  Thanks for illustrating in more depth.  Wwhat a great user experience!

This conversation happened to align with an architecture ritual we have internally, and we were able to discuss this in a little more depth.  The main takeaway from the conversation is that: while we would like to support aggregations (and many other things) in the search query and result interfaces, we don't feel we (as maintainers) have capacity to help shape / drive that conversation just now.  ...We also don't feel like it's fair to push the process of developing and proposing a solution onto members of the community either.  ...We have a sense that making this generic across search engines will be challenging, and a variety of alternatives have pros and cons that need to be weighed.

...With that in mind: our primary concern right now is to unblock y'all!

So (and, sorry for the whiplash), we think the best approach for now would be to make that zod check less restrictive.  For context: that schema check was put in place at the same time as permission support was added to search, and as far as I know, it's there primarily as a guard against unauthorized access to various document types.

I can't think of any harm in allowing unknown keys to pass through (other than the risk that, anyone passing such keys would be going outside the bounds of the defined interface and that any custom functionality built on those keys would not be guaranteed to continue working in the future, e.g. if we added and started using such a key on the interface).  (\cc @mtlewis, keep me honest, here).

Would you be willing to take a crack at updating that schema validation to allow unknown keys to pass through, @pedronastasi?

**Comment by pedronastasi** [comment]
Yes. I would like to be assigned to work on it

**Comment by pedronastasi** [comment]
.passthrough
By default Zod object schemas strip out unrecognized keys during parsing.

```
const person = z.object({
  name: z.string(),
});

person.parse({
  name: "bob dylan",
  extraKey: 61,
});
// => { name: "bob dylan" }
// extraKey has been stripped
```

Instead, if you want to pass through unknown keys, use .passthrough() .
```

person.passthrough().parse({
  name: "bob dylan",
  extraKey: 61,
});
// => { name: "bob dylan", extraKey: 61 }
```

**Comment by pedronastasi** [comment]
Great!. Should I apply what i sent you up here?

**Comment by iamEAP** [comment]
That sounds reasonable to me! A test for the change would also be great. ...And a descriptive changeset as well.

(You can take a look at other recently merged PRs to get a sense of what that looks like.)

**Comment by pedronastasi** [comment]
Sent a PR. https://github.com/backstage/backstage/pull/13795

**Comment by garyniemen** [comment]
Perhaps for you to review @iamEAP as you have been following closely.

**Comment by iamEAP** [comment]
Ah, yeah!  We're all good here, I think, as this PR was merged in about a week ago: https://github.com/backstage/backstage/pull/13890

Should be available to try out as of `@backstage/plugin-search-backend` version `1.1.0-next.1` or higher.
