### ISSUE TITLE
New Collapsible Table Design

### ISSUE THREAD

**Issue by Expalex** [backstage/backstage#13598]
## 🗒 General

Expedia Group would like to propose an enhanced collapsible table design.
This is to be an enhanced version to the existing https://mui.com/material-ui/react-table/#collapsible-table.
This improved version would be be easier to view, save space, scalable, and more consistent with the rest of Backstage design. 
A large portion the layout for this new one is different from what's existing. Thus, I recommend we replace the existing one with this, or have two versions for people pick from:  the current and this new one.

## 💻 Usage
<img width="998" alt="New_Collapsible_Table" src="https://user-images.githubusercontent.com/80132060/189252139-8d18bb9a-d943-4afb-accf-f3fdbd84da5e.png">

## 📐 Specs
[**ENHANCED COLLAPSIBLE TABLE**](https://www.figma.com/proto/0Xd7SAi2rIDmahyGZtzydT/Enhanced-Table?page-id=401%3A1080&node-id=401%3A1630&viewport=36%2C301%2C0.24&scaling=scale-down&starting-point-node-id=401%3A1630&hide-ui=1) (Figma interactive) design. 
There are two collapsible rows:  1) main  single row  2) multiple rows that wrap under "Details" column. Try clicking both.

**Comment by Expalex** [comment]
This conversation continues where https://github.com/backstage/backstage/issues/11880 left off. Communication somehow got dropped.
@freben  Would you clarify what you mean by "optional extension"?

**Comment by Expalex** [comment]
This conversation continues where https://github.com/backstage/backstage/issues/11880 left off. Communication somehow got dropped.

**Comment by Expalex** [comment]
Multiple rows that wrap (i.e. Details column) can be set to cap at one row, two rows, three rows or more before overflow “…” appears, in which instance user can click to expand and view all rows. This conversation continues where https://github.com/backstage/backstage/issues/11880 left off. Communication somehow got dropped.

**Comment by webark** [comment]
How does the striped table work with the subcontent? I know the current material table collapsible breaks the stripes cause it adds a row.

**Comment by Expalex** [comment]
[**Enhanced Collapsible Table Stripe**](https://www.figma.com/proto/0Xd7SAi2rIDmahyGZtzydT/Enhanced-Table?page-id=416%3A1550&node-id=416%3A1760&viewport=229%2C381%2C0.31&scaling=scale-down&starting-point-node-id=416%3A1760) (Figma) shows how rows with stripes would behave.

**Comment by Sonofigma** [comment]
Yeah, @Expalex have a point with making the tables collapsible and this would help users to determine what exact table and details they would love to get uncovered by toggling the chevron icons. I can design such tables on Figma, I am proficient with it.

**Comment by Expalex** [comment]
[**Enhanced Collapsible Table Stripe**](https://drive.google.com/file/d/1amwL-zot1RXR2Qe87g4fHBbxEKGQsOSG/view?usp=sharing)  (Video)  shows its behavior. @freben Do you have any questions?

**Comment by Rugvip** [comment]
Thank you for the suggestion @Expalex! It seems solid, but I'm no UX expert 😅

I do wonder if you have a sense of where this modification would be made? Would it be additions to the table from `core-components`, or more of a documented pattern for collapsible rows? Or is it even the case that this would fit best as a contribution towards https://material-table.com directly?

**Comment by Expalex** [comment]
@Rugvip It is to be a CORE contribution and part of Storybook. I am a UX designer. Now that you, a Spotify's engineer seem positive about this, I'll ask our engineer to talk to you more on what you've mentioned.

**Comment by Expalex** [comment]
Here is an example of how the table can be used to display data aggregation and details. <img width="1203" alt="Collapsible_Table_Aggregation_example" src="https://user-images.githubusercontent.com/80132060/193863562-43564137-4aae-4675-acd2-b9e3d865679f.png">

**Comment by Expalex** [comment]
Here is an example of how the table can be used to display data aggregation and details.

<img width="1697" alt="Collapsible_Table_Aggregation_example" src="https://user-images.githubusercontent.com/80132060/193868957-bb34e956-eeb0-4ac4-9d1d-f86a5eeab788.png">

**Comment by nwpappas** [comment]
> This improved version would be be easier to view, save space, scalable, and more consistent with the rest of Backstage design.

Could you go into more detail around how this is "easier to view, save space, scalable, and more consistent"?

It's unclear from the description and images what updates provide to MUI's collapsible table capabilities. Are you proposing net new capabilities or a data wrapper that simply makes pushing data in easier, and a default design application for that data using the existing the structure?

> ... or have two versions for people pick from: the current and this new one.

Having two of anything should be approached with caution. Keeping an experience consistent across multiple 3rd party plugins is challenging enough. If two options exist for (in this case) a table, it should be very clear when it is most appropriate to use one versus the other.
