### ISSUE TITLE
Backstage techdocs not loading on first attempt

### ISSUE THREAD

**Issue by johnan1** [backstage/backstage#13615]
## Expected Behavior

When visiting techdocs tab in Backstage, the docs should start loading based on the mkdocs definition in each of the respective repos.

## Actual Behavior

The first attempt to load the docs displays the usual error message below.
![image](https://user-images.githubusercontent.com/93215800/189381200-3490d63b-05ca-4dc3-a28c-ef44e50c73da.png)

## Steps to Reproduce

Our techdocs are defined slightly different because we need to source the files from the root directory of the repository. Our mkdocs.yml file is defined like this. We use the same-dir plugin so it can read the files directly from the root of the repo.

![image](https://user-images.githubusercontent.com/93215800/189386381-cd7bb438-0256-4f3a-9c41-3736bb50047e.png)

```
site_name: api-orchestration-docs
nav:
- Home: README.md
- User Guide: USERGUIDE.md
- Developer Guide: DEVGUIDE.md
plugins:
- techdocs-core
- same-dir
docs_dir: .

```
When we visit an service's techdoc tab, the first attempt will show this error in the logs

`[2m2022-09-09T15:14:49.974Z[22m [34mtechdocs[39m [32minfo[39m Unable to get metadata for 'component:default/api-orchestration' with error Error: Unable to read techdocs_metadata.json at /app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/api-orchestration/techdocs_metadata.json. Error: Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/api-orchestration/techdocs_metadata.json'; caused by Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/api-orchestration/techdocs_metadata.json' [36mtype[39m=plugin | [2m2022-09-09T15:14:49.974Z[22m [34mtechdocs[39m [32minfo[39m Unable to get metadata for 'component:default/api-orchestration' with error Error: Unable to read techdocs_metadata.json at /app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/api-orchestration/techdocs_metadata.json. Error: Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/api-orchestration/techdocs_metadata.json'; caused by Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/api-orchestration/techdocs_metadata.json' [36mtype[39m=plugin`

`"GET /api/techdocs/metadata/techdocs/default/component/api-orchestration HTTP/1.1" 404 2682 "-"`

Sometimes the techdocs page takes awhile to load but eventually a refresh will finally load the docs. **I only need to ever refresh the techdocs once. Even a rebuild/redeployment of the application will allow the techdocs to work after the first refresh.** It seems like Backstage doesn't know where to find these files at first because I'm using same-dir plugin?

## Your Environment

OS:   Windows_NT 10.0.19044 - win32/x64
node: v16.16.0
yarn: 1.22.19
cli:  0.18.1-next.1 (installed)
backstage:  1.5.0-next.1

Dependencies:
  @backstage/app-defaults                            1.0.5-next.1
  @backstage/backend-common                          0.15.0-next.2
  @backstage/backend-plugin-api                      0.1.1-next.0
  @backstage/backend-tasks                           0.3.4-next.0
  @backstage/catalog-client                          1.0.4
  @backstage/catalog-model                           1.1.0
  @backstage/cli-common                              0.1.9
  @backstage/cli                                     0.18.1-next.1
  @backstage/config-loader                           1.1.3
  @backstage/config                                  1.0.1
  @backstage/core-app-api                            1.0.5-next.0
  @backstage/core-components                         0.10.0, 0.10.1-next.1, 0.11.0-next.2
  @backstage/core-plugin-api                         1.0.4, 1.0.5-next.0
  @backstage/errors                                  1.1.0
  @backstage/integration-react                       1.1.3-next.1
  @backstage/integration                             1.2.2, 1.3.0-next.1
  @backstage/plugin-api-docs                         0.8.8-next.2
  @backstage/plugin-app-backend                      0.3.35-next.0
  @backstage/plugin-auth-backend                     0.15.1-next.1
  @backstage/plugin-auth-node                        0.2.4-next.0
  @backstage/plugin-bitbucket-cloud-common           0.1.2-next.0
  @backstage/plugin-catalog-backend-module-bitbucket 0.2.2-next.0
  @backstage/plugin-catalog-backend-module-ldap      0.5.2-next.0
  @backstage/plugin-catalog-backend                  1.3.1-next.2
  @backstage/plugin-catalog-common                   1.0.4, 1.0.5-next.0
  @backstage/plugin-catalog-graph                    0.2.20-next.1
  @backstage/plugin-catalog-import                   0.8.11-next.1
  @backstage/plugin-catalog-node                     1.0.1-next.0
  @backstage/plugin-catalog-react                    1.1.2, 1.1.3-next.2
  @backstage/plugin-catalog                          1.5.0-next.2
  @backstage/plugin-github-actions                   0.5.8-next.1
  @backstage/plugin-jenkins-common                   0.1.7-next.0
  @backstage/plugin-jenkins                          0.7.7-next.2
  @backstage/plugin-org                              0.5.8-next.1
  @backstage/plugin-permission-common                0.6.3
  @backstage/plugin-permission-node                  0.6.4-next.0
  @backstage/plugin-permission-react                 0.4.3, 0.4.4-next.0
  @backstage/plugin-proxy-backend                    0.2.29-next.0
  @backstage/plugin-scaffolder-backend               1.5.0-next.2
  @backstage/plugin-scaffolder-common                1.1.2
  @backstage/plugin-scaffolder                       1.5.0-next.2
  @backstage/plugin-search-backend-module-pg         0.3.6-next.0
  @backstage/plugin-search-backend-node              1.0.1-next.0
  @backstage/plugin-search-backend                   1.0.1-next.0
  @backstage/plugin-search-common                    1.0.0
  @backstage/plugin-search-react                     1.0.1-next.1
  @backstage/plugin-search                           1.0.1-next.1
  @backstage/plugin-sonarqube                        0.3.7
  @backstage/plugin-tech-radar                       0.5.15-next.1
  @backstage/plugin-techdocs-backend                 1.2.1-next.1
  @backstage/plugin-techdocs-module-addons-contrib   1.0.3-next.2
  @backstage/plugin-techdocs-node                    1.3.0-next.1
  @backstage/plugin-techdocs-react                   1.0.3-next.2
  @backstage/plugin-techdocs                         1.3.1-next.2
  @backstage/plugin-user-settings                    0.4.7-next.1
  @backstage/release-manifests                       0.0.5
  @backstage/test-utils                              1.1.3-next.0
  @backstage/theme                                   0.2.16
  @backstage/types                                   1.0.0
  @backstage/version-bridge                          1.0.1

**Comment by philipsabri** [comment]
Did you figure it out? We are having the same problem.

**Comment by bbgobie** [comment]
Same issue but in a regular techdocs layout

**Comment by dakshinau** [comment]
Im also facing the same issue

**Comment by dakshinau** [comment]
So apparently any mkdocs plugin that we use to generate docs  (which is not included in mkdocs-techdocs-core by default) needs to be installed manually.
in my case i added it to the Dockerfile `packages/backend/Dockerfile`

```
RUN pip3 install mkdocs-techdocs-core==1.1.7
RUN pip3 install mkdocs-same-dir
```

**Comment by G-man83** [comment]
> So apparently any mkdocs plugin that we use to generate docs (which is not included in mkdocs-techdocs-core by default) needs to be installed manually. in my case i added it to the Dockerfile `packages/backend/Dockerfile`
> 
> ```
> RUN pip3 install mkdocs-techdocs-core==1.1.7
> RUN pip3 install mkdocs-same-dir
> ```

@dakshinau where did you get the info for this?
