### ISSUE TITLE
Documentation on how to Use Feature Flags in Plugins

### ISSUE THREAD

**Issue by blueboxes** [backstage/backstage#13611]
## Feature Suggestion

There is no Documentation on how to Use Feature Flags in Plugins
 
## Context

After developing a plugin it was highlighted that there we no docs on feature flags and info online is out of date.

**Comment by blueboxes** [comment]
I have a document which I will create a PR for and attach.

**Comment by awanlin** [comment]
@blueboxes I think this can be closed now 😉
