### ISSUE TITLE
Enable APM trace with dd-trace which is not working in Backstage

### ISSUE THREAD

**Issue by SerenaIce** [backstage/backstage#13610]
Import the dd-trace, and invoke the trace.init() function to initialize with the required envs.
The APM metrics should showing up in datadog.

But actually it's not. I checked the envs and datadog-agent's status which should be fine. 
Except the metrics did not show up,  what is also weird that no logs showing up though I customer the logger and set debug: true when init().

So for now there's no signs for diagnose.
By the way the dogstatsd sending metrics successfully which proves that the agent host connection should be OK.

Environment:

Deploy app in AWS -> ecs -> cluster -> ec2 , the agent task and the application task are in the same instance.
Backstage: 1.5.0
dd-trace: 3.2.0
opentracing: 0.14.7

**Comment by andrewthauer** [comment]
We have this working, but haven't upgraded to to `dd-trace` -> `v3.2.0`. Will try next week. Was this working with `v2.*`?

**Comment by SerenaIce** [comment]
@andrewthauer , how did you integrate it? Could you please show the sample code? 

I just call the tracer.init() in packages/backend/indext.ts with the required envs. And I also set DD_TRACE_DEBUG: true and DD_TRACE_STARTUP_LOGS: true, still no logs show up.

**Comment by marcus-crane** [comment]
Hey @SerenaIce, here's how I've set up basic Datadog tracing in our Backstage instance. I haven't gotten around to customising it or adding extra spans though which you might want to do.

This is using `"dd-trace": "2.4.2"` which is a bit old nowadays but I might try upgrading it tomorrow.

```ts
// package/backend/src/tracer.ts
import tracer from 'dd-trace';

tracer.init({
    service: "backstage.api",
    env: "production",
    hostname: "<snip>", // You likely don't need this
    sampleRate: 1,
    plugins: false, // There are a lot of plugins so we manually set them up
});
tracer.use('pg', { enabled: true, service: "backstage.db" })
tracer.use('express', { enabled: true, middleware: false, service: "backstage.api", blocklist: ['/healthcheck'] })
export default tracer;
```

```ts
// package/backend/src/index.ts
import './tracer' // The tracer should always be imported first!
```

The main thing here is just that the tracer is imported before everything else at the top of `backend/src/index.ts`. You might choose to inline it if you prefer instead of having it in a separate file.

I guess I'll note that the above is using Datadog all the way through rather than opentracing but I don't imagine it would affect very much

**Comment by SerenaIce** [comment]
@marcus-crane , thanks and I will have a try. BTW, did you try to get the logs in your app service when enable the DD_TRACE_DEBUG: true? Which drove me crazy is that I couldn't see any logs which is hard for me to diagnose the issues.

**Comment by andrewthauer** [comment]
We are pretty much doing the same as @marcus-crane. More specifically:

```ts
const datadogConfig = {
  service: env.DATADOG_APM_DEFAULT_SERVICE ?? env.APP_NAME ?? 'backstage',
  hostname: env.DATADOG_APM_HOST,
  port: Number(env.DATADOG_APM_PORT),
  tags: { env: env.APP_ENV },
  logInjection: true,
};

const enabled = Boolean(env.DATADOG_APM_ENABLED) ?? false;
if (enabled) {
  tracer.init(datadogConfig);
}
```

NOTE: The above code is called more or less at the very beginning of the `plugins/backend/src/index.ts`'s `main` function. Hope this helps.

**Comment by SerenaIce** [comment]
We finally find the root cause about this issue. It is because we had wrong value format in our GLOBAL_AGENT_NO_PROXY setting. The format like 'x.x.x.x/xx' should not be correct for the ip segment. It should be like 'x.x.x.*'.  

So this is not a bug of backstage, I will close this one.
