### ISSUE TITLE
Optimize entity-facets endpoint

### ISSUE THREAD

**Issue by airavichandra** [backstage/backstage#13655]
The `/catalog/entity-facets` endpoint for querying facets takes a long time to load. Looking at the [implementation](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/DefaultEntitiesCatalog.ts#L329), it currently fetches all the entities from the final_entities table and then filters the entities it needs. This drastically slows down the response time. 

## Possible Implementation

As discussed with @freben and @vinzscam, we should be using the search table instead, which already has all the necessary fields and data. And do the filtering at the database level, instead of fetching everything at once. However, checking the [source code](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/stitching/buildEntitySearch.ts#L139), the search table only has lowercased entity values in its column, making it case insensitive and not being able to get the correctly cased data. There are a couple of options to overcome this:

1. Option 1 - Additional column in the search table to hold the original (case sensitive) value

Adding additional column will double the table size. We must take this into consideration and test how the performance has changed.

3. Option 2 - Avoid lowercasing entirely and change the index type to have a case insensitive collation.

We will need to investigate if sqlite supports case insensitive index. This method could also be risky, since we need to ensure that this works across several db engines.

P.S : Happy to work on this issue. It would be great if you could assign this to me.
cc: @guillermomanzo @rodmachen

**Comment by rodmachen** [comment]
I believe @airavichandra is still working on this issue.

**Comment by Rugvip** [comment]
Closing since #14230 is now merged!
