### ISSUE TITLE
Scaffolder: Dynamic Task Workers

### ISSUE THREAD

**Issue by OscarDHdz** [backstage/backstage#13650]
## Feature Suggestion

Hi there, having in mind: https://github.com/backstage/backstage/issues/3746 (being able to create Scaffolder TaskWorkers anywhere),
We are looking for a way to Dynamically instantiate  scaffolder `TaskWorkers` when needed instead of having a fixed amount set [here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/service/router.ts#L158). 

## Context

We were able to achieve that by creating our own `TaskBroker` implementation that had extra control over the `TaskWorkers`, and now we are looking to contribute back with that.

> **Note:** In case you are wondering, yes, we've been in scenarios in which we ran out of `TaskWorkers` because they are either stuck or just busy running long tasks.

### **Option 1 - Generic - StorageTaskBroker Hooks**
As a generic approach, not tied to a "dynamic workers" feature. We could setup some `hooks/prop` in the `StorageTaskBroker` Particularly:

* `onDispatch` Hook - To know when new task is about to be executed
*  `freeWorkers` flag to know if there are free workers or not

Here's a vague implementation:

```javascript
// TaskBroker instantiation
taskBroker = new StorageTaskBroker(databaseTaskStore, logger, {
    onDispatch: async (freeWorkers: boolean) => {
      if (!freeWorkers) {
        console.log(`Creating new worker!!`);
        const worker = await TaskWorker.create({...});
        worker.start();
      }
    }
  });

//TaskBroker freeWorkers flag - true
private async waitForDispatch() {
  this.freeWorkers = true; 
  ...
}

//TaskBroker freeWorkers flag - false
private signalDispatch() {
  this.freeWorkers = false;
  ...
}
```
Of course, that would need some improvements to properly pass and setup `hooks` in the right way and place (i.e. passing params to `createRouter`) 

### **Option 2 - Specific - Dynamic Workers Feature**

On the other side, we could contribute with a specific implementation to  dynamically create TaskWorkers. This option relies on:

* Replacing the `taskWorkers` fixed amount [here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/service/router.ts#L158), with a Prop like `taskWorkersMax` to set how many dynamic workers you would allow Backstage to instantiate. 

This option would require the following implementations:

* Listening to Free workers inside `StorageTaskWorker` (Similar to option 1)
* Setting who would be the `TaskWorkers` manager, responsible to turn on/off the workers (Probably `StorageTaskWorker`)
* A way to dynamically turn on `TaskWorkers` (Like passing a factory ) 
* A way to turn off TaskWorkers when no needed  (Probably in a `schedule`) 

Option 2 is what we've been running by providing our own `taskBroker` to the `createRouter` method. 
We made the `broker` our `TaskWorker` manager, being able to create new workers by passing a  factory in a form like `taskBroker.setWorkerFacory(igniteNewWorker)`

**Comment by freben** [comment]
I believe this is fixed by #13817
