### ISSUE TITLE
Default values in owner ,RepoUrlPicker like workspace ,project and repository

### ISSUE THREAD

**Issue by VKZycus** [backstage/backstage#13665]
Below is my template.yaml file where I am using Repourlpicker

 owner:
          title: Owner
          type: string
          description: Owner of the project
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - bitbucket.org

I need to make default value to my workspace ,project and repository so that it doesnt need to be filled again and again in backstage.

Can someone help me in giving default value to workspace ,project and repository.

**Comment by Manish3323** [comment]
+1 to @benjdlambert we are also doing this in one of our template

**Comment by luk-rs** [comment]
I'm also facing issues like this, additionally i'm wondering if you cant already display a combobox with the current available options for organizations and owners.

**Comment by benjdlambert** [comment]
You can provide `allowedOwners` or `allowedOrganizations` in `ui:options` too. There's some documentation here: https://backstage.io/docs/features/software-templates/writing-templates#the-repository-picker

**Comment by Rugvip** [comment]
Sounds like this is all covered already 👍

**Comment by luk-rs** [comment]
> You can provide `allowedOwners` or `allowedOrganizations` in `ui:options` too. There's some documentation here: https://backstage.io/docs/features/software-templates/writing-templates#the-repository-picker

Even though the documentation states that we can set the allowed Organizations/Owners for that functionality I'm seeing a slightly different behavior.  First, the allowedOrganizations doesn't seem to work, even though I have it set up when rendering in backstage it always renders a text box without any predefined option, and secondly, the allowedOwners field seems to work even though it blocks the first owner as the only possible option. Let me know if you need any further information on my configuration to understand what's going on.

**Comment by benjdlambert** [comment]
@luk-rs :wave:

> First, the allowedOrganizations doesn't seem to work, even though I have it set up when rendering in backstage it always renders a text box without any predefined option

`allowedOrganizations` are only available on Azure, and was only added recently, so make sure that both of these are satisfied.

> allowedOwners field seems to work even though it blocks the first owner as the only possible option

Are you providing more than one and it's still disabled and not allowing you to choose another one from the list that you've provided? Can you provide an simple reproduction template example?

**Comment by benjdlambert** [comment]
Yeah, this is something we've spoken about and want to do. I started some work on this already, basically having an `integrations-backend` that would optionally take a `userToken` from the client and would be able to list teams and groups you had write access to for each provider. Should probably create a ticket for this to be honest as I don't think it's ticket yet, but it's on my radar! :pray:

**Comment by artemptushkin** [comment]
@Rugvip 👋  I think this should be reopened as there is no way right now to pass a default workspace

For example, I have

https://gitlab.com/iptiq where `iptiq` is the default workspace, how can I setup this up now with the RepoUrlPicker? I have to input this always manual like the prefix of the `owner` which is not convenient

**Comment by benjdlambert** [comment]
@artemptushkin have you tried following the above comment? https://github.com/backstage/backstage/issues/13665#issuecomment-1250807363

**Comment by artemptushkin** [comment]
@benjdlambert I tried in default:

* gitlab.com/my-space
* gitlab.com?workspace=my-space
* gitlab.com?project=my-space

neither works, it adds this things to the URL on the UI but it doesn't use - I get 404 later

**Comment by jrtaylorJH** [comment]
Adding support for this
