### ISSUE TITLE
[RFC] extend the AdrPlugin to support gitlab too.

### ISSUE THREAD

**Issue by Abhay-soni-developer** [backstage/backstage#13675]
**Status:** Open for comments

## Need

The ADR plugin as of right now does not support any other service other than GitHub.
this RFC target is to extend this plugin feature to also support GitLab.

## Proposal

the plugin is using a custom hook name useOctokitRequest to get the repo content and file content from GitHub.
by using the Octokit library which only supports GitHub.

this hook takes the URL and returns the list of contents in the repo or file according to the URL.

according to my current plan. 

 * create useAdrFilesList(url) -> [filepaths...] 
 * create useAdrFileContent(filename) —> string (raw utf-8)
 * remove useOctokitRequest hook

these two hooks internally have to decide whether the request currently made is for Gitlab or GitHub.
> the good thing is, this solution is expandable for other services also such as bitbucket etc.

right now my strategy is to trim the hostname from the URL and decide whether the current request is for GitLab or GitHub

* useAdrFileList will be used in EntityAdrContent, where we will replace it with useOctokitRequest to get the ADR files list.
* useAdrFileContent will be used in AdrReader, where we will replace it with useOctokitRequest to the content inside the file in UTF-8 format.

> this solution will add the Gitlab support to the plugin-adr immediately, and create a smooth path for future extensions.

**Comment by Abhay-soni-developer** [comment]
happy to pickup / contribute.

**Comment by kuangp** [comment]
Another possible implementation is to build out the backend service to make use of the built in `UrlReaders` and have the frontend proxy all requests through the backend instead (similar to what the TODO plugin does). The search collator is already using `UrlReaders` so indexing ADRs already support all integrations and inspiration can be taken from there. This will also allow the plugin to be completely SCM agnostic and not just limited to Github/GitLab

**Comment by pjungermann** [comment]
I would be interested in support for Bitbucket Cloud.

I wonder a bit how to make these kind of things (support for all SCM providers) easier. 🤔

**Comment by awanlin** [comment]
👍 to the idea of using the `UrlReaders` for this so that way it works with Azure DevOps Repos and Bitbucket Server which is what we are using

**Comment by NishkarshRaj** [comment]
Can someone please re-open this

**Comment by NishkarshRaj** [comment]
@freben @benjdlambert

**Comment by LZING** [comment]
It is recommended to open this issue. Please do not bind with github. Like techdocs, it can support multiple warehouses. After all, it is impossible to only support github in enterprise development, most of them use gitlab

**Comment by awanlin** [comment]
Support for using `UrlReaders` in the ADR plugin was merged in on January 4, 2023 in this PR: https://github.com/backstage/backstage/pull/15348 and officially release with version `1.10.0` of Backstage

`UrlReaders` (https://backstage.io/docs/plugins/url-reader/) support pretty much all of the current integrations: https://backstage.io/docs/integrations/
