### ISSUE TITLE
jenkins warn PermissionAuthorizer is deprecated. Please use an instance of PermissionEvaluator instead of PermissionAuthorizer in PluginEnvironment#permissions

### ISSUE THREAD

**Issue by timja** [backstage/backstage#13701]
## Expected Behavior

No deprecation warning on startup

## Actual Behavior

A deprecation warning on startup

## Steps to Reproduce

1. Include the Jenkins backend plugin in an app using the recommended installation from https://github.com/backstage/backstage/blob/master/plugins/jenkins-backend/README.md

## Context

The documented code to include the plugin doesn't pass through the permissions system at all

createRouter, expects a permissions option:
https://github.com/backstage/backstage/blob/535ca54f0e7ccc39eedefe084b94cb8aa42f7df9/plugins/jenkins-backend/src/service/router.ts#L39-L54

but it's not passed in the recommended installation snippet:
https://github.com/backstage/backstage/blob/master/plugins/jenkins-backend/README.md

I would be happy enough to fix this if someone could point me in the direction, this specifically said no docs added:
https://github.com/backstage/backstage/pull/9840#issuecomment-1075917384

and it's just a bit unclear to me on what the developer is supposed to do.

## Your Environment

master branch of this repo [535ca54f0e7ccc39eedefe084b94cb8aa42f7df9](https://github.com/backstage/backstage/commit/535ca54f0e7ccc39eedefe084b94cb8aa42f7df9)

**Comment by benjdlambert** [comment]
I think that in the `README.md`, you probably want to add an example of passing through a `PermissionsEvaluator`, comes from the environment by default.

Something like:

```ts
createRouter({
  ...
  permissions: env.permissions
})
```

Should work I think?
