### ISSUE TITLE
Integration tests for jenkins-backend plugin

### ISSUE THREAD

**Issue by timja** [backstage/backstage#13707]
It would be good to have integration tests for the jenkins-backend plugin

https://github.com/backstage/backstage/pull/13388 completely broke it but it wasn't picked up by tests

_Originally posted by @benjdlambert in https://github.com/backstage/backstage/issues/13692#issuecomment-1249593608_

**Comment by benjdlambert** [comment]
This doesn't need to to be anything fancy too, just maybe Jest and mocking less so we catch the issue.

**Comment by casje896** [comment]
Hi! I'm new to this project and would like to try and contribute to this issue if that is okay?

**Comment by Rugvip** [comment]
@casje896 sure, thank you! 👍 Any kind of new tests for the Jenkins plugin would help

**Comment by casje896** [comment]
Hi! I have run into some problems with testing the jenkins API with less or without mocks. I'm focused on testing the buildProject and getBuild functions in jenkinsApi.ts. However, I’m unsure on how Backstage is practically using the jenkinsApi in the first place? Is there somewhere in Backstage where the api is used (so that I have something that I can base my test upon)?

**Comment by casje896** [comment]
Hi again, sorry for the long absence. 
I have tried for a while to get testing to work with msw but without much success. My problem is that the client is not receiving the project and I am unsure that it is even calling a url that the server is able to mock, the following is my code (currently located in jenkinsApi.test.js): 

```
import { rest } from 'msw';
import { setupServer } from 'msw/node';

...

describe('JenkinsApi with less mock', () => {
    
    const project: JenkinsProject = {
      actions: [],
      displayName: 'Example Build',
      fullDisplayName: 'Example jobName » Example Build',
      fullName: 'example-jobName/exampleBuild',
      inQueue: false,
      lastBuild: {
        actions: [],
        timestamp: 1,
        building: false,
        duration: 10,
        result: 'success',
        displayName: '#7',
        fullDisplayName: 'Example jobName » Example Build #7',
        url: 'https://jenkins.example.com/job/example-jobName/job/exampleBuild',
        number: 7,
      },
    };
    
    const api_noMock = new JenkinsApiImpl(fakePermissionApi); 
    const server = setupServer();
    setupRequestMockHandlers(server);
    const baseUrl = 'https://jenkins.example.com';
    
    const setupHandlers = () => {
      
      server.use(
        rest.get(`https://jenkins.example.com/job/example-jobName/`, (_, res, ctx) => { // this URL is wrong
          return res(ctx.json({ result: [project] })); 
        }),
      );
      
    };
    
    it('getProjects unfiltired', async () => {
      
      setupHandlers();

      const result = await api_noMock.getProjects(jenkinsInfo);

      expect(result).toHaveLength(1);
      expect(result[0]).toEqual({
        actions: [],
        displayName: 'Example Build',
        fullDisplayName: 'Example jobName » Example Build',
        fullName: 'example-jobName/exampleBuild',
        inQueue: false,
        lastBuild: {
          actions: [],
          timestamp: 1,
          building: false,
          duration: 10,
          result: 'success',
          displayName: '#7',
          fullDisplayName: 'Example jobName » Example Build #7',
          url: 'https://jenkins.example.com/job/example-jobName/job/exampleBuild',
          number: 7,
          status: 'success',
          source: {},
        },
        status: 'success',
      });
    });
    
  });
```

**Comment by freben** [comment]
The URL does indeed have to be exactly right, for it to match. So yeah you'll have to look through the client code to see what things it's calling and what those URL patterns are, and match them perfectly. Maybe you can insert some console.log statements in the client itself right before it calls `fetch`, to see what the URLs are that it's calling?
