### ISSUE TITLE
Property 'entityRef' is missing in type 'SearchDocument' but required in type 'AdrDocument' 

### ISSUE THREAD

**Issue by erdebee** [backstage/backstage#13723]
## Expected Behavior

AdrSearchResultListItem should render with a SearchDocument as input for the "result" property in SearchPage.tsx.

## Actual Behavior

AdrSearchResultItem expects AdrDocument. AdrDocument is expecting a non-existing property entityRef in type SearchDocument, as provided by the search rendering in SearchPage.tsx

## Steps to Reproduce

When using the provided example from the README.md of the ADR Plugin, in SearchPage.tsx, the compiler complains.

`Property 'entityRef' is missing in type 'SearchDocument' but required in type 'AdrDocument'`

For the below snippet: 

```
{results.map(({ type, document, highlight, rank }) => {
                    switch (type) {
                      case 'adr':
                        return (
                          <AdrSearchResultListItem
                            key={document.location}
                            result={document}
                            highlight={highlight}
                            rank={rank}
                          />
                        );
```

## Context

Adding the AdrSearchResultListItem in Search results, by using the code examples.

**Comment by kuangp** [comment]
A workaround/solution for this is to cast the document to `AdrDocument`: 
```diff
+import { AdrDocument } from '@backstage/plugin-adr-common';
...

{results.map(({ type, document, highlight, rank }) => {
                    switch (type) {
                      case 'adr':
                        return (
                          <AdrSearchResultListItem
                            key={document.location}
-                           result={document}
+                           result={document as AdrDocument}
                            highlight={highlight}
                            rank={rank}
                          />
                        );
```

I also took a peak at how the other result list items components are typed and it seems they are currently marked as `any`: https://github.com/backstage/backstage/blob/8b8ccbe3eed6cd93e61d7220ac7e809c9d8a6c21/plugins/stack-overflow/src/search/StackOverflowSearchResultListItem/StackOverflowSearchResultListItem.tsx#L29-L32

which is probably why this hasn't come up before which seems incorrect from a type def perspective so maybe the correct behavior should be that result list items should type the result param correctly and the search page should be type casting appropriately ? @emmaindal  thoughts?

**Comment by garyniemen** [comment]
@emmaindal Any thoughts on this?

**Comment by camilaibs** [comment]
Could you confirm that your concrete results are `AdrDocument`, which contains `entityRef` @erdebee ? I would love to hear your ideas about it as we plan to discuss it internally. Are there any suggestions for a generic results type that does not rely on casting?
