### ISSUE TITLE
[Scaffolder] Client API for triggering scaffolder workflow from an entity page

### ISSUE THREAD

**Issue by taras** [backstage/backstage#13735]
## Context

One of our clients has many scaffolder templates. They use templates as a starting point for activities on their platform. The list of templates is getting very long, and they would like to make the triggering scaffolder more contextual. In other words, they would like to prompt a user to start a scaffolder workflow without having to go to the Scaffolder create screen. We can imagine many different screens where they could trigger a scaffolder workflow, but the most common starting point would be a Catalog Entity Page.

## Feature Suggestion

Provide a Scaffolder Client API that makes it easy to create a link that initiates a Scaffolder workflow. The API should make it easy to specify some or all of the information necessary to trigger the workflow. If partial form data is provided, it should prompt the user to fill in the missing information.

## Possible Implementation

One way could be to create a route or update the existing route to accept information passed via parameters. Scaffolder Client API should allow generating a link that the route can parse to populate the form.

**Comment by Rugvip** [comment]
Do you think that exporting the existing `selectedTemplateRouteRef` through the scaffolder plugin might be enough for this? I'd say we need to look over the parameter names if we do that, thinking that `/templates/:namespace/:name` might be the way to go instead

**Comment by taras** [comment]
It might be, but we need to be able to pass additional data to pre-populate the form. 

With `useNativate`, we can pass a state object, but ideally that state would be stored in the URL so we can create those links without JavaScript. 

How about a `state` or `formData` query parameter that's base64 encoded JSON?

**Comment by benjdlambert** [comment]
`?formData=` and then some encoded json blob will work

**Comment by taras** [comment]
It sounds like have a plan,

1. Export `selectedTemplateRouteRef` from [here](https://github.com/backstage/backstage/blob/2a7a21e9c5a7947bdbf34f5f56410d01750c83f6/plugins/scaffolder/src/routes.ts#L44) 
2. Allow `selectedTemplateRouteRef` ref to accept a parameters that will be encoded json blob in `?=formData=` query parameter
3. Modify SelectedTemplate to load state similar to [how Template page does it](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/TemplatePage/TemplatePage.tsx#L77-L86)

One thing remaining, I don't see a way to pass an object for it to be encoded as a JSON blob. It could be done manually, but it seem like extra hoops for the consumer of the ref. Thoughts?

**Comment by benjdlambert** [comment]
I don't think it's going to be possible to encode it into the `routeRef` to be honest, at least it's not at the minute. Use navigate with the query string might be the cleanest to be honest. Or of course you could wrap this up in a hook or something to abstract away the `useRouteRef` and have the query string be encoded in the the return of it? Up to you whichever you think is best.

**Comment by taras** [comment]
For now, we can just show an example of how to serialize formData parameter. Should I create another feature request to expand the Ref API to accept a constructor function that can be used to serialize the URL?
