### ISSUE TITLE
Support the caFile file in the Kubernetes plugin configuration

### ISSUE THREAD

**Issue by jpeach** [backstage/backstage#13768]
## Feature Suggestion

As noted in https://github.com/backstage/backstage/pull/12911, the Kubernetes cluster `caData` field needs to be base64 encoded.

However, it looks like the Kubernetes client also supports a `caFile` field that reads the raw value from a file. This would work really well when Backstage is getting CA certificated from Kubernetes secrets volumes.

## Possible Implementation

I image that everywhere the plugin passes `caData` down to the Kubernetes client, it also needs to pass `caFile`.

## Context

Deploy Backstage in a Kubernetes cluster. The Kubernetes plugin is configured to scan multiple clusters. The CA certificates for each cluster are available as secrets in the deployment namespace.

**Comment by jpeach** [comment]
ref https://github.com/backstage/backstage/issues/13762

**Comment by freben** [comment]
ping @mclarke47 here
