### ISSUE TITLE
`BitbucketRepoPicker` issue with custom hostname. `allowedOwners` field does not render a list when is provided

### ISSUE THREAD

**Issue by vitokodev** [backstage/backstage#13789]
This line is a headache for me since we have Bitbucket Server on premise (custom hostname)...
Can we just have a `host.indexOf('bitbucket') >= 0` or similar?

_Originally posted by @vitokodev in https://github.com/backstage/backstage/pull/12640#discussion_r976628237_

**Comment by vitokodev** [comment]
Understood. I will try to workaround this specific use case.
Thanks @pjungermann .

**Comment by freben** [comment]
Closing as working as intended.
