### ISSUE TITLE
Typescript is super slow

### ISSUE THREAD

**Issue by shmidt-i** [backstage/backstage#1378]
After recent changes in build processes/also maybe due to new libs and type definitions being pulled in, typescript performance during development became really bad, it takes like 5-10 seconds for typescript to catch on changes.

This needs more investigation ;)

**Comment by Rugvip** [comment]
How are you measuring? `yarn tsc` is still ~20s for clean and ~6s for incremental, which is fine. Changes in VSCode are also within a few seconds. Do you have a long running VSCode typescript server that might still have old setups loaded by any chance?

**Comment by shmidt-i** [comment]
Yes, I mean the VSCode changes being understood by typescript in ridiculous amount of time. It's definitely not only me, we had it several times during mob sessions, but recently I started to feel it even when I'm doing solo dev.

**Comment by shmidt-i** [comment]
>Do you have a long running VSCode typescript server that might still have old setups loaded by any chance? 

Maybe, was thinking on digging more into the problem and created this ticket just to not forget ;)

**Comment by gabemeola** [comment]
May be related, but Typescript v4 may improve editing experience: https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#partial-editing-mode

**Comment by Rugvip** [comment]
Closing this as not actionable. Let's reopen if there's something more specific to look into
