### ISSUE TITLE
Authenticate API Request using a provider (Github)

### ISSUE THREAD

**Issue by a-gos** [backstage/backstage#13807]
## Expected Behavior

Authenticate Backstage front & API request using the Github Provider. 

I followed the [Authenticate API request](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md) and used the Github Provider with _usernameMatchingUserEntityName_ . The backstage should be able to authenticate with github and work.

## Actual Behavior

WIthout the API authenticated it was working well but we are exposing the backstage (for demo purposes) to the public so we wanted to make the api request safe. After adding the authentication to api request the log in is not longer working.

I fall in the same error as: https://github.com/backstage/backstage/issues/12673

Where we can not authenticate the user because the API is expecting to be authenticated before authentication. In that issue he proposes a bypass where the request to the api needed for authentication are exposed (in my case it would be all entities by name). This does not seem like a good solution, since you are a exposing to the public a big part of the API and may have a lot of security problems. Is there any way to control this in a more secure way?

## Steps to Reproduce

1. Add authentication with github provider
2. Add authentication to api requests
3. Try to log in

## Context

Unable to keep using Backstage with authentication without having the api exposed to the public.

## Your Environment

- Browser Information: Google Chrome 99.0.4844.51 (64 bits)

- Output of `yarn backstage-cli info`: 

```
OS:   Linux 5.15.0-48-generic - linux/x64
node: v16.14.2
yarn: 1.22.18
cli:  0.18.0 (installed)

Dependencies:
  @backstage/app-defaults               1.0.4
  @backstage/backend-common             0.14.1
  @backstage/backend-plugin-api         0.1.0
  @backstage/backend-tasks              0.3.3
  @backstage/catalog-client             1.0.4
  @backstage/catalog-model              1.1.0
  @backstage/cli-common                 0.1.9
  @backstage/cli                        0.18.0
  @backstage/config-loader              1.1.3
  @backstage/config                     1.0.1
  @backstage/core-app-api               1.0.4
  @backstage/core-components            0.10.0
  @backstage/core-plugin-api            1.0.4
  @backstage/dev-utils                  1.0.4
  @backstage/errors                     1.1.0
  @backstage/integration-react          1.1.2
  @backstage/integration                1.2.2
  @backstage/plugin-api-docs            0.8.7
  @backstage/plugin-app-backend         0.3.34
  @backstage/plugin-auth-backend        0.15.0
  @backstage/plugin-auth-node           0.2.3
  @backstage/plugin-catalog-backend     1.3.0
  @backstage/plugin-catalog-common      1.0.4
  @backstage/plugin-catalog-graph       0.2.19
  @backstage/plugin-catalog-import      0.8.10
  @backstage/plugin-catalog-node        1.0.0
  @backstage/plugin-catalog-react       1.1.2
  @backstage/plugin-catalog             1.4.0
  @backstage/plugin-github-actions      0.5.7
  @backstage/plugin-org                 0.5.7
  @backstage/plugin-permission-common   0.6.3
  @backstage/plugin-permission-node     0.6.3
  @backstage/plugin-permission-react    0.4.3
  @backstage/plugin-proxy-backend       0.2.28
  @backstage/plugin-scaffolder-backend  1.4.0
  @backstage/plugin-scaffolder-common   1.1.2
  @backstage/plugin-scaffolder          1.4.0
  @backstage/plugin-search-backend-node 1.0.0
  @backstage/plugin-search-backend      1.0.0
  @backstage/plugin-search-common       1.0.0
  @backstage/plugin-search-react        1.0.0
  @backstage/plugin-search              1.0.0
  @backstage/plugin-tech-radar          0.5.14
  @backstage/plugin-techdocs-backend    1.2.0
  @backstage/plugin-techdocs-node       1.2.0
  @backstage/plugin-techdocs-react      1.0.2
  @backstage/plugin-techdocs            1.3.0
  @backstage/plugin-user-settings       0.4.6
  @backstage/release-manifests          0.0.5
  @backstage/test-utils                 1.1.2
  @backstage/theme                      0.2.16
  @backstage/types                      1.0.0
  @backstage/version-bridge             1.0.1
Done in 0.49s.

```

**Comment by jhaals** [comment]
Hi @a-gos!
Sorry for the delayed reply. Backstage currently does not support or recommend any form of direct access by external users. Backstage in its current form meant to be deployed behind VPN or an SSO proxy. This might of course change in the future but at the moment that's the case. We have tried to capture this in our threat model at https://backstage.io/docs/overview/threat-model#trust-model
