### ISSUE TITLE
Tech Radar: Quadrant list of technologies scroll position resets on mouse move

### ISSUE THREAD

**Issue by adamkadzban** [backstage/backstage#13831]
## Expected Behavior

When there are enough technologies in a quadrant to introduce a scroll bar, you should be able to hover over entries "below the fold" (that you have to scroll down to see) and not have the scroll position reset.

## Actual Behavior

Any mouse movements that cause the entry in the radar itself to change focus resets the quadrant scroll position

## Steps to Reproduce

Example video: https://imgur.com/a/WoLlJKT

1. Create a Tech Radar
2. Add enough entries to a quadrant to introduce a scroll bar
3. Scroll down in the quadrant and move your mouse a little in any direction

## Context

This makes using the Tech Radar with many entries very difficult. The list of technologies is essentially unusable.

## Your Environment

N/A I'm using a hosted instance from Roadie

- Browser Information: Google Chrome Version 105.0.5195.102

- Output of yarn backstage-cli info: N/A I'm using a hosted instance from Roadie

**Comment by freben** [comment]
Alright, without digging too much into it, it sort of looks like it's due to the entire thing being redrawn when the active entry changes. Would you be willing to dig into the code and try to devise a fix? 🙏

**Comment by malin-mallan** [comment]
Hi, my name is Malin and I am new to the open source community but I have worked with React and TypeScript before. I would like to contribute to Backstage. 

I have manage to reproduce the bug and have start digging in to the code. Could i try to solve this bug?

**Comment by adamkadzban** [comment]
I'm afraid my front end development skills are quite lacking, so if @malin-mallan wants to take a stab at it then I am fully supportive!

**Comment by malin-mallan** [comment]
I have try to find where the bug happen but I got a bit stuck... I have two questions I need help with. 
1.    I have trouble with understanding the lifecycle of the project. When is components rerendered?
2.    I have been looking for the problem in plugins/tech-radar/src/components/. Do you think I look at the right place or could the problem be somewhere else?

**Comment by marcofaggian** [comment]
Hi, I've worked on this (first contribution! 🎉).
I had to rework the Radar component and it's utils to an "immutable" data management (to avoid side effects). Plus had to refactor RadarLegend in its single components.

Published PR: #14038
