### ISSUE TITLE
useCustomResources infinitely runs

### ISSUE THREAD

**Issue by mclarke47** [backstage/backstage#13832]
[useCustomResources](https://github.com/backstage/backstage/blob/master/plugins/kubernetes/src/hooks/useCustomResources.ts)

![Screen Shot 2022-09-23 at 12 48 43 PM](https://user-images.githubusercontent.com/6514980/192012053-9b7ff3af-5176-4881-926a-7fb0fecde93c.png)

**Comment by freben** [comment]
Oddly, I don't see that hook being called anywhere in the current code base 🤔 I must be missing something ...

![Screenshot 2022-09-23 at 19 01 56](https://user-images.githubusercontent.com/3097461/192013883-a83d0575-c9b0-41f5-90c9-dd529370cbcd.png)

**Comment by freben** [comment]
But if it indeed is that one anyway, a hunch based on just its shape: I'd guess the customResourceMatchers array comes in as a fresh new array every single time, leading the useCallback being triggered over and over etc

**Comment by freben** [comment]
Oh it probably is [useKubernetesObjects](https://github.com/backstage/backstage/blob/c02fda193d4d582ff955e007e1eebb3afe3d1206/plugins/kubernetes/src/hooks/useKubernetesObjects.ts#L33) instead then? But that one doesn't seem to have any risky inputs 🤔 Maybe the entire component that uses the hook is mounted and unmounted repeatedly instead then, for some other reason?

**Comment by mclarke47** [comment]
I was using the `useCustomResources` hook externally and noticed it did this when I used it in the open source repo too, I'm gonna write a test to replicate then fix it so it doesn't regress.
