### ISSUE TITLE
Allow BaseUrl to be Relative

### ISSUE THREAD

**Issue by sennyeya** [backstage/backstage#13872]
## Feature Suggestion

Let users define baseUrl for both frontend and backend as a relative URL at webpack compile time.

## Possible Implementation

Pass in document.location.origin as a secondary argument to https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/apis/implementations/DiscoveryApi/UrlPatternDiscovery.ts#L41 which will allow for relative resolution.

## Context

I want to use an ejected front end with a backend running on the same domain separated by routing rules in CloudFront, ie mydomain.com/api/* routes to the backend and anything else routes to the front end for client side routing. I would like to build the webpack bundle once in my pipeline and have it work for any stages that I have set up, DEV, TEST, PROD, etc. Currently, I would need to build the bundle for each stage with different environment variables. This shouldn't be an issue for the backend as I can provide the current stage url at run time.
This feature would allow me to build the front end and backend once and host it across multiple environments.

Currently, attempting to set the baseurl to the empty string causes `TypeError: Invalid type in config for key 'app.baseUrl' in 'app-config.yaml', got empty-string, wanted string`. Setting it to '/' causes the URL constructor to throw.

**Comment by ara6893** [comment]
Current approach is to use 
```
backend:
    baseUrl: '.'
```
and then `new URL(config.getString('backend.baseUrl'), document.location.origin)` which should resolve to the right url for API discovery. 

It looks like the app.baseUrl is working as expected.

**Comment by sennyeya** [comment]
@Rugvip Can we close this and https://github.com/backstage/backstage/issues/14365, now that https://github.com/backstage/backstage/pull/13927 (and its fix) has been merged in?

**Comment by Rugvip** [comment]
@sennyeya yep, thank you! 👍 

So closing this through #13927, the app will now automatically rewrite both app and backend base URLs to fit the current origin
