### ISSUE TITLE
MaxListenersExceededWarning present in the logs

### ISSUE THREAD

**Issue by zhivko-georgiev** [backstage/backstage#13882]
## Expected Behavior

No warnings of type MaxListenersExceededWarning present in the Backstage's logs.

## Actual Behavior

We have noticed that while browsing in the docs section of the Backstage's catalog, there are occurrences of the following warning message `(node:12) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit`

## Steps to Reproduce

1. Open backstage
2. Go to /docs section
3. Open randomly some of the docs back and forth so requests towards GET /api/techdocs/sync are fired 

## Context

Here is the techdocs config we are using right now:
```
techdocs:
  builder: 'local'
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName:
          $env: TECHDOCS_S3_BUCKET_NAME
  generator:
    runIn: local
```

We encountered recently killed container due to Out of memory and that happened some 30 mins after the occurrence of this warning in the logs. We can't be 100% that it's the exact cause of it but could be related somehow and it's worth investigating. 

Had a chat in Discord with @freben about it and he suspects that this is the possible [culprit](https://github.com/backstage/backstage/blob/master/plugins/techdocs-node/src/stages/publish/awsS3.ts#L51). Here is the [thread](https://discord.com/channels/687207715902193673/1023939513107611679) in Discord.

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```
Dependencies:
  @backstage/app-defaults                          1.0.6
  @backstage/backend-common                        0.15.1
  @backstage/backend-plugin-api                    0.1.2
  @backstage/backend-tasks                         0.3.5
  @backstage/catalog-client                        1.1.0
  @backstage/catalog-model                         1.1.1
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.19.0
  @backstage/config-loader                         1.1.4
  @backstage/config                                1.0.2
  @backstage/core-app-api                          1.1.0
  @backstage/core-components                       0.11.1
  @backstage/core-plugin-api                       1.0.6
  @backstage/dev-utils                             1.0.6
  @backstage/errors                                1.1.1
  @backstage/integration-react                     1.1.4
  @backstage/integration                           1.3.1
  @backstage/plugin-api-docs                       0.8.9
  @backstage/plugin-app-backend                    0.3.36
  @backstage/plugin-auth-backend                   0.16.0
  @backstage/plugin-auth-node                      0.2.5
  @backstage/plugin-catalog-backend-module-msgraph 0.4.2
  @backstage/plugin-catalog-backend                1.4.0
  @backstage/plugin-catalog-common                 1.0.6
  @backstage/plugin-catalog-graph                  0.2.21
  @backstage/plugin-catalog-import                 0.8.12
  @backstage/plugin-catalog-node                   1.1.0
  @backstage/plugin-catalog-react                  1.1.4
  @backstage/plugin-catalog                        1.5.1
  @backstage/plugin-git-release-manager            0.3.22
  @backstage/plugin-github-actions                 0.5.9
  @backstage/plugin-org                            0.5.9
  @backstage/plugin-permission-backend             0.5.11
  @backstage/plugin-permission-common              0.6.4
  @backstage/plugin-permission-node                0.6.5
  @backstage/plugin-permission-react               0.4.5
  @backstage/plugin-proxy-backend                  0.2.30
  @backstage/plugin-scaffolder-backend             1.6.0
  @backstage/plugin-scaffolder-common              1.2.0
  @backstage/plugin-scaffolder                     1.6.0
  @backstage/plugin-search-backend-node            1.0.2
  @backstage/plugin-search-backend                 1.0.2
  @backstage/plugin-search-common                  1.0.1
  @backstage/plugin-search-react                   1.1.0
  @backstage/plugin-search                         1.0.2
  @backstage/plugin-tech-radar                     0.5.16
  @backstage/plugin-techdocs-backend               1.3.0
  @backstage/plugin-techdocs-node                  1.4.0
  @backstage/plugin-techdocs-react                 1.0.4
  @backstage/plugin-techdocs                       1.3.2
  @backstage/plugin-user-settings                  0.4.8
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.0
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
```

**Comment by Nitinvonage** [comment]
we are also facing the same warning in our backstage 1.5.0 version. Let me share the details what we customised in our code after which we are reciving this warning.
1. we wrote our custom CatalogCollator, there instead of reading the the entities from [catalogClient](https://github.com/backstage/backstage/blob/3b65fc11e4a2af8b2faded872628ed158151ac5e/plugins/catalog-backend/src/search/DefaultCatalogCollatorFactory.ts#L110) we are directly making a db query to fetch entities.

**Comment by Nitinvonage** [comment]
I Checked the nightly build(0.0.0-nightly-20221011025843), its still giving me the below warning
`(node:25725) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 abort listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit`

Also i wanted to know is this a good practice to run Catalog & Techdocs collator with different scheduled task runner like

```
const schedule = env.scheduler.createScheduledTaskRunner({
    frequency: { minutes: 2 },
    timeout: { minutes: 3 },
    initialDelay: { seconds: 3 }, 
    });

  const scheduleTechdocs = env.scheduler.createScheduledTaskRunner({
    frequency: { minutes: 3 },
    timeout: { minutes: 4 },
      initialDelay: { seconds: 6 },
  });
```

**Comment by freben** [comment]
I believe running them separately should be just fine, yeah.

**Comment by Nitinvonage** [comment]
still getting similar issue, any clue where should i look more into

**Comment by freben** [comment]
Does the error go away if you go the recommended path and instead fetch the entities using a CatalogClient?

**Comment by Nitinvonage** [comment]
No, It still persist... What i also observed is after changing the default parallelism limit size, reducing to 5 or less also delays the error to come.
`DefaultTechDocsCollatorFactory.ts`
`this.parallelismLimit = options.parallelismLimit ?? 4;` 

any view point on this?

**Comment by rprakashg-redhat** [comment]
I'm also seeing this in the logs 
```
 k logs developer-hub-75cb79ff98-ppjr2 -n tools
Defaulted container "backstage-backend" out of: backstage-backend, install-dynamic-plugins (init)
Loaded config from app-config.yaml, app-config.example.yaml, app-config.example.production.yaml, app-config.dynamic-plugins.yaml, developer-hub-appconfig.yaml, app-config-from-configmap.yaml, env
(node:1) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```
