### ISSUE TITLE
Enable the ability to download static files from mkdocs templates

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#13940]
## Feature Suggestion

Enable the ability to download static files from mkdocs templates

## Possible Implementation

I have not looked into how it might be implemented.

## Context

If you add a link to a static json file like the following, I would expect that backstage would render the file somehow within backstage or allow the file to be downloaded:

```
[json](./test.json)
```

Instead it is showing a 404 error page.

**Comment by soapraj** [comment]
Hi! @punkle - I haven't tested this right now but I believe there is support for downloads of files within the /docs folder if you add a `download` attribute to the link tag like below

```[json](./test.json){: download }```

Can you try this and let us know if that works?

**Comment by jenden** [comment]
Using @soapraj's suggestion with the download link worked for me in Backstage with two minor issues: first, in backstage documentation the name of the file is set to "download" and second, I found some markdown parsers don't understand the tag and so the annotation shows up in the body of the file. Perhaps they are both solvable but I found it easier to add the html link directly with the download attribute as it solved both problems for me.

```
<a href="test.json" download>json</a>
```

**Comment by punkle** [comment]
I will give that a try thank you

**Comment by jenden** [comment]
@punkle could you help do a quick sanity check. I thought it was working but I really just ended up downloading files with the correct name that were empty. Could you confirm whether your test downloads had content?

**Comment by punkle** [comment]
Yes. The download had content.

**Comment by jenden** [comment]
I had to manipulate the link or the file download was empty because the link included the page name.


`href=assets/myfile.json` gave me a link with the page name that downloaded nothing. `href=../assets/myfile.json` worked.

**Comment by KatharinaSick** [comment]
Hi,

are there any updates on this? We are still facing the same issue and using HTML links (`<a href="...">...</a>`) is not very intuitive for everybody writing documentation.
