### ISSUE TITLE
Techdoc failing after backstage upgrade to  "version": "1.7.0-next.0"

### ISSUE THREAD

**Issue by kumarnil** [backstage/backstage#13962]
## Expected Behavior

Techdoc is not loading after backstage upgrade to v1.7.9-next.0

## Actual Behavior

Techdoc should load all the docs

## Steps to Reproduce

Click on the any techdoc file and it throws error.

## Context

Error details:-
 error Failed to build the docs page: request to https://gitlab.XXX-dns.com/api/v4/projects/YYYY%2F APP_ZZZ failed, reason: unable to verify the first certificate request to https://gitlab.XXX-dns.com/api/v4/projects/YYYY%2F APP_ZZZ failed, reason: unable to verify the first certificate type=system errno=UNABLE_TO_VERIFY_LEAF_SIGNATURE code=UNABLE_TO_VERIFY_LEAF_SIGNATURE stack=FetchError: request to https://gitlab.XXX-dns.com/api/v4/projects/YYYY%2FAPP_ZZZ failed, reason: unable to verify the first certificate
--
Sun, Oct 2 2022 10:27:21 am | at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1491:11)
Sun, Oct 2 2022 10:27:21 am | at ClientRequest.emit (node:events:513:28)
Sun, Oct 2 2022 10:27:21 am | at ClientRequest.emit (node:domain:489:12)
Sun, Oct 2 2022 10:27:21 am | at TLSSocket.socketErrorListener (node:_http_client:481:9)
Sun, Oct 2 2022 10:27:21 am | at TLSSocket.emit (node:events:513:28)
Sun, Oct 2 2022 10:27:21 am | at TLSSocket.emit (node:domain:489:12)
Sun, Oct 2 2022 10:27:21 am | at emitErrorNT (node:internal/streams/destroy:157:8)
Sun, Oct 2 2022 10:27:21 am | at emitErrorCloseNT (node:internal/streams/destroy:122:3)
Sun, Oct 2 2022 10:27:21 am | at processTicksAndRejections (node:internal/process/task_queues:83:21)

## Your Environment

development

- Chrome browser

- Output of `yarn backstage-cli info`: 
yarn run v1.22.19
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.14.0
yarn: 1.22.19
cli:  0.20.0-next.0 (installed)
backstage:  1.7.0-next.0

Dependencies:
  @backstage/app-defaults                          1.0.6, 1.0.7-next.0
  @backstage/backend-common                        0.15.2-next.0
  @backstage/backend-plugin-api                    0.1.3-next.0
  @backstage/backend-tasks                         0.3.6-next.0
  @backstage/catalog-client                        1.1.0, 1.1.1-next.0
  @backstage/catalog-model                         1.1.1, 1.1.2-next.0
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0-next.0
  @backstage/config-loader                         1.1.5-next.0
  @backstage/config                                1.0.2, 1.0.3-next.0
  @backstage/core-app-api                          1.1.0, 1.1.1-next.0
  @backstage/core-components                       0.11.1, 0.11.2-next.0, 0.9.5
  @backstage/core-plugin-api                       1.0.6, 1.0.7-next.0
  @backstage/dev-utils                             1.0.6
  @backstage/errors                                1.1.1, 1.1.2-next.0
  @backstage/integration-react                     1.1.4, 1.1.5-next.0
  @backstage/integration                           1.3.1, 1.3.2-next.0
  @backstage/plugin-api-docs                       0.8.10-next.0
  @backstage/plugin-app-backend                    0.3.37-next.0
  @backstage/plugin-auth-backend                   0.17.0-next.0
  @backstage/plugin-auth-node                      0.2.6-next.0
  @backstage/plugin-catalog-backend                1.4.1-next.0
  @backstage/plugin-catalog-common                 1.0.6, 1.0.7-next.0
  @backstage/plugin-catalog-graph                  0.2.22-next.0
  @backstage/plugin-catalog-import                 0.8.13-next.0
  @backstage/plugin-catalog-node                   1.1.1-next.0
  @backstage/plugin-catalog-react                  1.1.4, 1.1.5-next.0
  @backstage/plugin-catalog                        1.5.2-next.0
  @backstage/plugin-github-actions                 0.5.10-next.0
  @backstage/plugin-org                            0.5.10-next.0
  @backstage/plugin-permission-common              0.6.4, 0.6.5-next.0
  @backstage/plugin-permission-node                0.6.6-next.0
  @backstage/plugin-permission-react               0.4.5, 0.4.6-next.0
  @backstage/plugin-proxy-backend                  0.2.31-next.0
  @backstage/plugin-scaffolder-backend             1.7.0-next.0
  @backstage/plugin-scaffolder-common              1.2.1-next.0
  @backstage/plugin-scaffolder                     1.7.0-next.0
  @backstage/plugin-search-backend-module-pg       0.4.1-next.0
  @backstage/plugin-search-backend-node            1.0.3-next.0
  @backstage/plugin-search-backend                 1.0.3-next.0
  @backstage/plugin-search-common                  1.0.1, 1.0.2-next.0
  @backstage/plugin-search-react                   1.1.1-next.0
  @backstage/plugin-search                         1.0.3-next.0
  @backstage/plugin-tech-radar                     0.5.17-next.0
  @backstage/plugin-techdocs-backend               1.3.1-next.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5-next.0
  @backstage/plugin-techdocs-node                  1.4.1-next.0
  @backstage/plugin-techdocs-react                 1.0.5-next.0
  @backstage/plugin-techdocs                       1.3.3-next.0
  @backstage/plugin-user-settings                  0.5.0-next.0
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.0, 1.2.1-next.0
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

**Comment by Rugvip** [comment]
Looks like you might have some certificate issues in the communication with your internal gitlab instance. I'd make sure those are ironed out first before we dig into any potential changes to techdocs. Unless you believe that the certificate checks are failing because of a change in TechDocs, that could be checked by reverting back to the previous version.
