### ISSUE TITLE
Adjust the colour scheme of the CTA buttons under Actions Items

### ISSUE THREAD

**Issue by Sonofigma** [backstage/backstage#13964]
I will be proposing an adjustment to the CTA buttons under the "Actions Items" on the Cost Insight Page. 

Colors read meanings to users even before reading the text on it, and calls incorporate emotions when viewed by users. The CTA button under the "Actions Items" on the Cost Insight Page would convey an irresistible message to the users if they followed the Colour conventions for CTA's like Accept (Green Color), Snooze (mild color) & Dismiss (Red Color). With such color conventions applied to those CTA's, users would get a clearer message of what these CTA's can be used for.

<img width="948" alt="Screenshot 2022-10-02 at 17 42 06" src="https://user-images.githubusercontent.com/97257870/193467147-3b733e4d-e974-4ac4-9f89-b9fd9f2373ff.png">

**Comment by Sonofigma** [comment]
> I will be proposing an adjustment to the CTA buttons under the "Actions Items" on the Cost Insight Page.
> 
> Colors read meanings to users even before reading the text on it, and calls incorporate emotions when viewed by users. The CTA button under the "Actions Items" on the Cost Insight Page would convey an irresistible message to the users if they followed the Colour conventions for CTA's like Accept (Green Color), Snooze (mild color) & Dismiss (Red Color). With such color conventions applied to those CTA's, users would get a clearer message of what these CTA's can be used for.
> 
> <img alt="Screenshot 2022-10-02 at 17 42 06" width="948" src="https://user-images.githubusercontent.com/97257870/193467147-3b733e4d-e974-4ac4-9f89-b9fd9f2373ff.png">

To provide a clear solution,  I came up with a design that illustrates and explains the adjustments proposed. Here is the Figma link and I will be open to help any developer who would love to work on it.
**https://www.figma.com/file/SCcphLIRPFBlvkpZOIT71l/Hactoberfest?node-id=0%3A1**

**Comment by Rugvip** [comment]
To be honest I don't think we want to mess too much with the styling that MUI provides at this level. By relying on the standards the MUI set we make it much easier to customize the look and feel. If we start overriding styling in individual components then it's going to be a lot trickier to theme them.

That said there could be a better combination of MUI properties for these buttons?

**Comment by Sonofigma** [comment]
Oh, I think that makes sense. 
Yes, there could be, just a little refactoring would be required. 
Did I get you correctly @Rugvip

**Comment by freben** [comment]
@Sonofigma  Just wanted to loop back here and say that yes it sounds like you got it right! I understand that you wanted to leave this open for people to pitch in with development help, so I added the "help wanted" label.
