### ISSUE TITLE
Creating Permissions Using the Tutorial Fails on /api/catalog/entities endpoint

### ISSUE THREAD

**Issue by sennyeya** [backstage/backstage#13979]
## Expected Behavior

Using the tutorial for setting up permissions (https://backstage.io/docs/permissions/custom-rules), specifically the lines
```
toQuery: (systemRef: string) => ({
    key: 'relations.partOf',
    value: systemRef,
  }),
```
should filter the results returned by /api/catalog/entities correctly, ie those with the correct system reference.

## Actual Behavior

Nothing is filtered.

## Location
Filter can have both `.value` and `.values` parameters but 
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/DefaultEntitiesCatalog.ts#L100 does not support the `.value` parameter.

## Steps to Reproduce

1. Create a new permission that matches the tutorial
```
export const isInSystemRule = createCatalogPermissionRule({
  name: 'IS_IN_SYSTEM',
  description: 'Checks if an entity is part of the system provided',
  resourceType: 'catalog-entity',
  apply: (resource: Entity, systemRef: string) => {
    if (!resource.relations) {
      return false;
    }

    return resource.relations
      .filter(relation => relation.type === 'partOf')
      .some(relation => relation.targetRef === systemRef);
  },
  toQuery: (systemRef: string) => ({
    key: 'relations.partOf',
    value: systemRef,
  }),
});

const isInSystem = createConditionFactory(isInSystemRule);
```
2. Load the home page.

## Context

Trying to filter the set of entities shown to users on the home page.

## Your Environment

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.5.0 - darwin/arm64
node: v16.17.0
yarn: 3.2.3
cli:  0.18.1 (installed)
backstage:  1.5.0

Dependencies:
  @backstage/app-defaults                          1.0.5
  @backstage/backend-common                        0.15.0, 0.15.1
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.10, 0.1.9
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.3, 1.1.4
  @backstage/config                                1.0.1, 1.0.2
  @backstage/core-app-api                          1.0.5
  @backstage/core-components                       0.11.0
  @backstage/core-plugin-api                       1.0.5
  @backstage/errors                                1.1.0, 1.1.1
  @backstage/integration-react                     1.1.3
  @backstage/integration                           1.3.0, 1.3.1
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-app-backend                    0.3.35
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.4, 0.2.5
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.5, 1.0.6
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-import                 0.8.11
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.1.3
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-github-actions                 0.5.8
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-permission-backend             0.5.11
  @backstage/plugin-permission-common              0.6.3, 0.6.4
  @backstage/plugin-permission-node                0.6.4, 0.6.5
  @backstage/plugin-permission-react               0.4.4
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.1
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-module-pg       0.3.6
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.0.0, 1.0.1
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-tech-radar                     0.5.15
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

```

**Comment by mtlewis** [comment]
Hi @sennyeya! Sorry for the slow reply here. It looks like you've uncovered a problem with the tutorial, which incorrectly includes a `value` property on the response from `toQuery`. In fact, the filter returned here is the same one used in the rest of the catalog, and as such only supports `key` and `values`. I'll open a PR shortly to update the docs!

**Comment by sennyeya** [comment]
Would it also make sense to update the type? Having the `value` parameter supported by Intellisense makes creating ad-hoc policies confusing to start off with.

**Comment by mtlewis** [comment]
Docs PR: https://github.com/backstage/backstage/pull/14063

**Comment by sennyeya** [comment]
It looks like the type definition for `EntitiesSearchFilter` is 
```
export type EntitiesSearchFilter = {
  key: string;
  values?: string[];
};
```
but
```
toQuery(kinds: string[]) {
      return {
        key: 'kind',
        value: kinds.map(kind => kind.toLocaleLowerCase('en-US')),
      };
},
```
has no Intellisense complaint. I can see that we would want this to be extensible, but if we're only currently allowing `key` and `values` as the only valid properties, not sure why the typing isn't catching this?

This (I think) means that 
```
/**
   * Translate this rule to criteria suitable for use in querying a backing data store. The criteria
   * can be used for loading a collection of resources efficiently with conditional criteria already
   * applied.
   */
toQuery(...params: TParams): PermissionCriteria<TQuery>;
```
is matching something weird, since the type isn't coming through as just the TQuery. The typing for the `PermissionRule` that I'm using is `EntitiesSearchFilter`, 
```
export const isEntityKind = createCatalogPermissionRule({
    name: 'IS_ENTITY_KIND',
    description: 'Allow entities with the specified kind',
    resourceType: 'catalog-entity',
    apply(resource: Entity, kinds: string[]) {
      const resourceKind = resource.kind.toLocaleLowerCase('en-US');
      return kinds.some(kind => kind.toLocaleLowerCase('en-US') === resourceKind);
    },
    toQuery(kinds: string[]) {
      return {
        key: 'kind',
        test: kinds.map(kind => kind.toLocaleLowerCase('en-US')),
      };
    },
  });
  
```

**Comment by mtlewis** [comment]
I think it's more fundamental than that. Typescript allows extra properties in some situations, and one of those situations is in the return values of function parameters. See [this minimal playground example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nA8gIwFYQMbCgXigbygDMEAuKAZ2ACcBLAOwHMoBfAbgFgAobjOeqlAA2cRvDi4oACkYRgAYX7AI9YOSkBKXAD5YCFOixacu-NyhQ+AuEIgA6EYxlzFqlcE12ScDZy4tubkdxKU0daUJzYjIoAHIACQghESgAdzhqIQATAEJYgBooKIB6YqgAOQkAFQBlKAhqagzCiAA3FShgAAs4AFdGLpKygANkAENqYahaCih6OGwwCew4Ik6uiCH6gA9ILAgsqGo5Xup6TvB7KPHqcljxgC9Yov8NXyA):

```typescript
type FooObject = { foo: string };

const logFoo = (getContent: () => FooObject) => {
  console.log(getContent().foo);
}

logFoo(() => ({ 
  foo: 'Hello world!', 
  // No TS error, even though
  // `bar` is not part of the
  // expected return type.
  bar: 'baz' 
}));
```

**Comment by sennyeya** [comment]
You learn something everyday, very interesting behavior. Thanks for sharing!

Is there a case where `values` being undefined is a useful filter? It looks like the catalog query specifically filters that case out.

**Comment by mtlewis** [comment]
Hmm - where are you seeing that? Here's one place where entities are filtered using `EntitiesSearchFilter`s, and in this case, the key filter is always added, along with a value filter if values are present.

I believe one example use case for key-only filters is filtering for entities that have a specific [annotation](https://backstage.io/docs/features/software-catalog/well-known-annotations).

**Comment by sennyeya** [comment]
Ahh, that makes sense. I misread the query that you referenced, I thought https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/DefaultEntitiesCatalog.ts#L100 was the only where clause.
Feel free to close this when the PR goes through.
