### ISSUE TITLE
Module not found plugin error 

### ISSUE THREAD

**Issue by 13archit** [backstage/backstage#13982]
## Expected Behavior
Plugin Must Worked 

## Actual Behavior
Module Not found error for github action plugin 
Module not found: Can't resolve '@backstage/plugin-github-actions' in 'packages/app/src/components/catalog'
src/components/catalog/EntityPage.tsx

## Context

 Backstage App not starting and giving module not found error

## Your Environment

- Browser Information: 
 Google Chrome
- Output of `yarn backstage-cli info`: 
yarn run v1.22.19
$ /home/archit/try/node_modules/.bin/backstage-cli info
OS:   Linux 5.15.0-48-generic - linux/x64
node: v16.17.1
yarn: 1.22.19
cli:  0.19.0 (installed)
backstage:  1.6.0

Dependencies:
  @backstage/app-defaults                          1.0.6
  @backstage/backend-common                        0.15.1
  @backstage/backend-plugin-api                    0.1.2
  @backstage/backend-tasks                         0.3.5
  @backstage/catalog-client                        1.1.0
  @backstage/catalog-model                         1.1.1
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.19.0
  @backstage/config-loader                         1.1.4
  @backstage/config                                1.0.2
  @backstage/core-app-api                          1.1.0
  @backstage/core-components                       0.11.1
  @backstage/core-plugin-api                       1.0.6
  @backstage/errors                                1.1.1
  @backstage/integration-react                     1.1.4
  @backstage/integration                           1.3.1
  @backstage/plugin-api-docs                       0.8.9
  @backstage/plugin-app-backend                    0.3.36
  @backstage/plugin-auth-backend                   0.16.0
  @backstage/plugin-auth-node                      0.2.5
  @backstage/plugin-catalog-backend-module-github  0.1.7
  @backstage/plugin-catalog-backend                1.4.0
  @backstage/plugin-catalog-common                 1.0.6
  @backstage/plugin-catalog-graph                  0.2.21
  @backstage/plugin-catalog-import                 0.8.12
  @backstage/plugin-catalog-node                   1.1.0
  @backstage/plugin-catalog-react                  1.1.4
  @backstage/plugin-catalog                        1.5.1
  @backstage/plugin-github-actions                 0.5.9
  @backstage/plugin-kubernetes-backend             0.7.2
  @backstage/plugin-kubernetes-common              0.4.2
  @backstage/plugin-kubernetes                     0.7.2
  @backstage/plugin-org                            0.5.9
  @backstage/plugin-permission-common              0.6.4
  @backstage/plugin-permission-node                0.6.5
  @backstage/plugin-permission-react               0.4.5
  @backstage/plugin-proxy-backend                  0.2.30
  @backstage/plugin-scaffolder-backend             1.6.0
  @backstage/plugin-scaffolder-common              1.2.0
  @backstage/plugin-scaffolder                     1.6.0
  @backstage/plugin-search-backend-module-pg       0.4.0
  @backstage/plugin-search-backend-node            1.0.2
  @backstage/plugin-search-backend                 1.0.2
  @backstage/plugin-search-common                  1.0.1
  @backstage/plugin-search-react                   1.1.0
  @backstage/plugin-search                         1.0.2
  @backstage/plugin-tech-radar                     0.5.16
  @backstage/plugin-techdocs-backend               1.3.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.4
  @backstage/plugin-techdocs-node                  1.4.0
  @backstage/plugin-techdocs-react                 1.0.4
  @backstage/plugin-techdocs                       1.3.2
  @backstage/plugin-user-settings                  0.4.8
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.0
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

```text

```

**Comment by jhaals** [comment]
Hi, sorry to hear that you're having problems. 
Does `yarn install` run successfully? Is this for a newly created app?
It would be great if you could provide some steps to reproduce this problem.

**Comment by 13archit** [comment]
Yes, I ran yarn add command mentioned in readme file of plugin and it ran correctly , but there were some warnings about react .
"@backstage/plugin-github-actions > @backstage/core-plugin-api@1.0.6" has unmet peer dependency "react@^16.13.1 || ^17.0.0".
@backstage/plugin-github-actions > @backstage/core-plugin-api@1.0.6" has unmet peer dependency "react-router-dom@6.0.0-beta.0 || ^6.3.0"


Yes is for newly created app. I previously ran k8s plugin and it was working fine.

**Comment by soaand01** [comment]
Any update with this one? @13archit

**Comment by torsami77** [comment]
https://backstage.io/docs/local-dev/cli-build-system#subpath-exports

https://stackoverflow.com/questions/72785721/how-to-solve-error-package-subpath-while-using-jasmine-ts
