### ISSUE TITLE
Software Template not loading in UI (issue on parameter-schema) ResponseError: Request failed with 403 NotAllowedError

### ISSUE THREAD

**Issue by kumarnil** [backstage/backstage#13999]
## Expected Behavior

After I click on the "CHOOSE" button of a software template, it should fetch the template parameter schema and render the result in the UI view.

## Actual Behavior

https://development_domain/create?filters%5Bkind%5D=template&filters%5Buser%5D=all can see all templates.
After click on the "CHOOSE" button of any of the templates, it shows "Failed to load template, ResponseError: Request failed with 403 NotAllowedError".

## Steps to Reproduce

1. Upgraded backstage v 1.4 to Step 1.7 and stop working.

## Context

Not able to load any template in the UI

## Your Environment

- Browser Information: Google Chrome

- Output of `yarn backstage-cli info`: 
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.14.0
yarn: 1.22.19
cli:  0.20.0-next.0 (installed)
backstage:  1.7.0-next.0

Dependencies:
  @backstage/app-defaults                          1.0.6, 1.0.7-next.0
  @backstage/backend-common                        0.15.2-next.0
  @backstage/backend-plugin-api                    0.1.3-next.0
  @backstage/backend-tasks                         0.3.6-next.0
  @backstage/catalog-client                        1.1.0, 1.1.1-next.0
  @backstage/catalog-model                         1.1.1, 1.1.2-next.0
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0-next.0
  @backstage/config-loader                         1.1.5-next.0
  @backstage/config                                1.0.2, 1.0.3-next.0
  @backstage/core-app-api                          1.1.0, 1.1.1-next.0
  @backstage/core-components                       0.11.1, 0.11.2-next.0, 0.9.5
  @backstage/core-plugin-api                       1.0.6, 1.0.7-next.0
  @backstage/dev-utils                             1.0.6
  @backstage/errors                                1.1.1, 1.1.2-next.0
  @backstage/integration-react                     1.1.4, 1.1.5-next.0
  @backstage/integration                           1.3.1, 1.3.2-next.0
  @backstage/plugin-api-docs                       0.8.10-next.0
  @backstage/plugin-app-backend                    0.3.37-next.0
  @backstage/plugin-auth-backend                   0.17.0-next.0
  @backstage/plugin-auth-node                      0.2.6-next.0
  @backstage/plugin-catalog-backend                1.4.1-next.0
  @backstage/plugin-catalog-common                 1.0.6, 1.0.7-next.0
  @backstage/plugin-catalog-graph                  0.2.22-next.0
  @backstage/plugin-catalog-import                 0.8.13-next.0
  @backstage/plugin-catalog-node                   1.1.1-next.0
  @backstage/plugin-catalog-react                  1.1.4, 1.1.5-next.0
  @backstage/plugin-catalog                        1.5.2-next.0
  @backstage/plugin-github-actions                 0.5.10-next.0
  @backstage/plugin-org                            0.5.10-next.0
  @backstage/plugin-permission-common              0.6.4, 0.6.5-next.0
  @backstage/plugin-permission-node                0.6.6-next.0
  @backstage/plugin-permission-react               0.4.5, 0.4.6-next.0
  @backstage/plugin-proxy-backend                  0.2.31-next.0
  @backstage/plugin-scaffolder-backend             1.7.0-next.0
  @backstage/plugin-scaffolder-common              1.2.1-next.0
  @backstage/plugin-scaffolder                     1.7.0-next.0
  @backstage/plugin-search-backend-module-pg       0.4.1-next.0
  @backstage/plugin-search-backend-node            1.0.3-next.0
  @backstage/plugin-search-backend                 1.0.3-next.0
  @backstage/plugin-search-common                  1.0.1, 1.0.2-next.0
  @backstage/plugin-search-react                   1.1.1-next.0
  @backstage/plugin-search                         1.0.3-next.0
  @backstage/plugin-tech-radar                     0.5.17-next.0
  @backstage/plugin-techdocs-backend               1.3.1-next.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5-next.0
  @backstage/plugin-techdocs-node                  1.4.1-next.0
  @backstage/plugin-techdocs-react                 1.0.5-next.0
  @backstage/plugin-techdocs                       1.3.3-next.0
  @backstage/plugin-user-settings                  0.5.0-next.0
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.0, 1.2.1-next.0
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

**Comment by jhaals** [comment]
Hi! Sorry to hear that you're having problems.
It sounds like some of the arguments for permissions or token manager is not passed properly to the backend plugin. I would really double check that the wiring, perhaps comparing it to a new app or using the [example app](https://github.com/backstage/backstage/blob/master/packages/backend/src/index.ts#L65-L102) to see that all of the required services are created.

**Comment by kumarnil** [comment]
Here is **packages/backend/src/index.ts** file which looks good to me.

import Router from 'express-promise-router';
import {
  createServiceBuilder,
  loadBackendConfig,
  getRootLogger,
  useHotMemoize,
  notFoundHandler,
  CacheManager,
  DatabaseManager,
  SingleHostDiscovery,
  UrlReaders,
  ServerTokenManager,
} from '@backstage/backend-common';
import { TaskScheduler } from '@backstage/backend-tasks';
import { Config } from '@backstage/config';
import app from './plugins/app';
import auth from './plugins/auth';
import catalog from './plugins/catalog';
import scaffolder from './plugins/scaffolder';
import proxy from './plugins/proxy';
import techdocs from './plugins/techdocs';
import search from './plugins/search';
import apibackend from './plugins/api-backend';
import { PluginEnvironment } from './types';
import { ServerPermissionClient } from '@backstage/plugin-permission-node';
import { DefaultIdentityClient } from '@backstage/plugin-auth-node';

function makeCreateEnv(config: Config) {
  const root = getRootLogger();
  const reader = UrlReaders.default({ logger: root, config });
  const discovery = SingleHostDiscovery.fromConfig(config);
  const tokenManager = ServerTokenManager.fromConfig(config, { logger: root });
  const permissions = ServerPermissionClient.fromConfig(config, {
    discovery,
    tokenManager,
  });

  const cacheManager = CacheManager.fromConfig(config);
  const databaseManager = DatabaseManager.fromConfig(config, { logger: root });
  const taskScheduler = TaskScheduler.fromConfig(config);
  const identity = DefaultIdentityClient.create({
    discovery,
  });

  root.info(`Created UrlReader ${reader}`);

  return (plugin: string): PluginEnvironment => {
    const logger = root.child({ type: 'plugin', plugin });
    const database = databaseManager.forPlugin(plugin);
    const cache = cacheManager.forPlugin(plugin);
    const scheduler = taskScheduler.forPlugin(plugin);
    return {
      logger,
      database,
      cache,
      config,
      reader,
      discovery,
      tokenManager,
      scheduler,
      permissions,
      identity,
    };
  };
}

async function main() {
  const config = await loadBackendConfig({
    argv: process.argv,
    logger: getRootLogger(),
  });
  const createEnv = makeCreateEnv(config);

  const catalogEnv = useHotMemoize(module, () => createEnv('catalog'));
  const scaffolderEnv = useHotMemoize(module, () => createEnv('scaffolder'));
  const authEnv = useHotMemoize(module, () => createEnv('auth'));
  const proxyEnv = useHotMemoize(module, () => createEnv('proxy'));
  const techdocsEnv = useHotMemoize(module, () => createEnv('techdocs'));
  const searchEnv = useHotMemoize(module, () => createEnv('search'));
  const appEnv = useHotMemoize(module, () => createEnv('app'));
  const apiEnv = useHotMemoize(module, () => createEnv('apibackend'));
  

  const apiRouter = Router();
  apiRouter.use('/catalog', await catalog(catalogEnv));
  apiRouter.use('/scaffolder', await scaffolder(scaffolderEnv, config));
  apiRouter.use('/auth', await auth(authEnv));
  apiRouter.use('/techdocs', await techdocs(techdocsEnv));
  apiRouter.use('/proxy', await proxy(proxyEnv));
  apiRouter.use('/search', await search(searchEnv));
  apiRouter.use('/api', await apibackend(apiEnv));

  // Add backends ABOVE this line; this 404 handler is the catch-all fallback
  apiRouter.use(notFoundHandler());

  const service = createServiceBuilder(module)
    .loadConfig(config)
    .addRouter('/api', apiRouter)
    .addRouter('', await app(appEnv));

  await service.start().catch(err => {
    console.log(err);
    process.exit(1);
  });
}

module.hot?.accept();
main().catch(error => {
  console.error('Backend failed to start up', error);
  process.exit(1);
});

**Comment by kumarnil** [comment]
Could you pls suggest any solutions to fix this issue?

**Comment by benjdlambert** [comment]
Hey :wave: is it only this page that fails? do you get 403 errors around the project on other pages? Do you have permissions turned on? Or do you maybe have the `auth-middleware` enabled somewhere? Sorry for the dump of messages, just trying to cover a few bases.

**Comment by kumarnil** [comment]
All pages are loading correctly except template. None of the template is loading.

We do have auth setting to open this app. However rest other permissions are default settings of backstage.

**Comment by kumarnil** [comment]
Looks like 'jose.jwtVerify' method of @backstage - 'plugin-auth-node'  failing and throwing exception.

 const decoded = await jose.jwtVerify(token, this.keyStore, {
      algorithms: this.algorithms,
      audience: "backstage",
      issuer: this.issuer
    });

**Comment by sqsp-rwatkins** [comment]
We have encountered this issue also after upgrading to v1.6.0 and adding `plugin-auth-node`.
One of our team members noticed that the server is looking for the cookie `_oauth2_proxy` but the cookies available are `_oauth2_proxy_0` and `_oauth2_proxy_1` because we are using split cookies.
We removed `plugin-auth-node` for now to get around the issue.

**Comment by kumarnil** [comment]
Yes, I removed "plugin-auth-node" form the code and it fixed the issue. I believe this fix will be available in next backstage upgrade.

**Comment by regicsolutions** [comment]
@kumarnil @sqsp-rwatkins wondering if you found a fix for this aside from removing the plugin-with-node package?
