### ISSUE TITLE
[cli] Make it easier to deduplicate dependencies with yarn resolutions

### ISSUE THREAD

**Issue by taras** [backstage/backstage#13994]
I'm creating this feature request for others to learn how to do this and in case someone wants to implement this improvement.

## Context

The Backstage project releases new releases every few months. Between those releases are pre-releases with `next` tag. Sometimes consumers of the Backstage project want to use the pre-releases to experiment with the new changes or get the newly merged code sooner. Unfortunately, this process of getting a pre-release is complicated and error-prone. 

For example, if I want to upgrade to `@backstage/plugin-catalog-backend@1.4.1-next.0`, I'll get the following output with `yarn backstage-cli versions:check`

```
The following packages must be deduplicated by updating dependencies in package.json

  @backstage/plugin-catalog-backend @ ^1.4.0 should be changed to ^1.4.1-next.0

The following packages can be deduplicated by updating dependencies in package.json

  @backstage/backend-common @ ^0.15.0-next.1 should be changed to ^0.15.2-next.0
  @backstage/backend-common @ ^0.15.1 should be changed to ^0.15.2-next.0
  @backstage/backend-plugin-api @ ^0.1.2 should be changed to ^0.1.3-next.0
  @backstage/backend-tasks @ ^0.3.2 should be changed to ^0.3.6-next.0
  @backstage/backend-tasks @ ^0.3.5 should be changed to ^0.3.6-next.0
  @backstage/catalog-client @ ^1.0.3 should be changed to ^1.1.1-next.0
  @backstage/catalog-client @ ^1.0.4 should be changed to ^1.1.1-next.0
  @backstage/catalog-client @ ^1.1.0 should be changed to ^1.1.1-next.0
  @backstage/catalog-model @ ^1.0.3 should be changed to ^1.1.2-next.0
  @backstage/catalog-model @ ^1.1.0 should be changed to ^1.1.2-next.0
  @backstage/catalog-model @ ^1.1.1 should be changed to ^1.1.2-next.0
  @backstage/config-loader @ ^1.1.2 should be changed to ^1.1.5-next.0
  @backstage/config-loader @ ^1.1.4 should be changed to ^1.1.5-next.0
  @backstage/config @ ^1.0.1 should be changed to ^1.0.3-next.0
  @backstage/config @ ^1.0.2 should be changed to ^1.0.3-next.0
  @backstage/errors @ 1.1.1 should be changed to ^1.1.2-next.0
  @backstage/errors @ ^1.0.0 should be changed to ^1.1.2-next.0
  @backstage/errors @ ^1.1.0 should be changed to ^1.1.2-next.0
  @backstage/errors @ ^1.1.1 should be changed to ^1.1.2-next.0
  @backstage/integration @ ^1.2.1 should be changed to ^1.3.2-next.0
  @backstage/integration @ ^1.3.1 should be changed to ^1.3.2-next.0
  @backstage/plugin-auth-node @ ^0.2.5 should be changed to ^0.2.6-next.0
  @backstage/plugin-catalog-common @ ^1.0.3 should be changed to ^1.0.7-next.0
  @backstage/plugin-catalog-common @ ^1.0.6 should be changed to ^1.0.7-next.0
  @backstage/plugin-catalog-node @ ^1.1.0 should be changed to ^1.1.1-next.0
  @backstage/plugin-permission-common @ ^0.6.2 should be changed to ^0.6.5-next.0
  @backstage/plugin-permission-common @ ^0.6.4 should be changed to ^0.6.5-next.0
  @backstage/plugin-permission-node @ ^0.6.2 should be changed to ^0.6.6-next.0
  @backstage/plugin-permission-node @ ^0.6.5 should be changed to ^0.6.6-next.0
  @backstage/plugin-scaffolder-common @ ^1.1.1 should be changed to ^1.2.1-next.0
  @backstage/plugin-scaffolder-common @ ^1.2.0 should be changed to ^1.2.1-next.0
  @backstage/plugin-search-common @ ^1.0.1 should be changed to ^1.0.2-next.0
```

I upgraded to a new package, which installed new dependencies with `next.0` tag. To prevent unexpected problems, I have to force each dependency to use the same version [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/).

Here is the process for deduping each dependency.

1. Take the first package in the list and run `yarn why @backstage/backend-common`
2. See which package is using the wrong version. In this case, it's all of the package in the workspace.
3. Add `"@backstage/backend-common": "0.15.2-next.0"` to resolutions in package.json
4. Repeat for the next package on the list

## Feature Suggestion

It would be very nice if this could be done when running `yarn backstage-cli versions:bump --release next --pattern=@backstage/backend-common`, maybe behind `--resolutions` flag.

## Possible Implementation

I'm not sure if there is a better way to do this, but we could use the list of generated packages, iterate through each package and add it to the resolutions.

**Comment by jhaals** [comment]
Hi Taras, these warnings in the cli should probably be removed entirely, we have removed a fair bit of these false warnings previously and this should likely be removed as well.
Having transient dependencies on older versions of the packages mentioned above is not be a problem. However adding resolutions that lock them to a specific version could definitely introduce bugs and problems as behaviours inside the package you add resolutions for might have change. We should probably reword this into a bug report and make sure the CLI is updated to not introduce confusion about this.

**Comment by taras** [comment]
@jhaals I'm not sure they're entirely just warnings. 

For example, I just ran  `yarn backstage-cli versions:bump --release next --pattern=@backstage/core-app-api` on http://github.com/thefrontside/backstage and I get this. 

`yarn backstage-cli versions:check`

<img width="752" alt="image" src="https://user-images.githubusercontent.com/74687/194324685-3314ad93-4607-45e6-ba16-455ae9c6d96a.png">

`yarn why @backstage/core-app-api`

<img width="756" alt="image" src="https://user-images.githubusercontent.com/74687/194324961-9ce35312-55e9-4c91-baed-f00adce61428.png">

`"_project_#app#@backstage#app-defaults#@backstage#core-app-api"` can't be updated by changing package.json because it's transient dependency. 

I could fix that with resolutions but I don't know another way.

**Comment by jhaals** [comment]
Very specific bumps like this is not really why we have the pattern, it's more for bumping a specific namespace or plugins. For this example with just bumping @backstage/core-app-api you must bump the app defaults package as well as it depends on it.

**Comment by taras** [comment]
@jhaals thank you for discussing this issue with me. My goal was to surface this scenario in case others might find themselves in a similar situation. We've done that now, so we can close this issue :)

**Comment by taras** [comment]
@jhaals I forgot that you suggested we rephrase this feature request as a bug to remove the extra warnings. Do you still want me to do that?

**Comment by riginoommen** [comment]
How did this fixed
