### ISSUE TITLE
[K8s plugin] Improve the Kubernetes plugin documentation

### ISSUE THREAD

**Issue by namco1992** [backstage/backstage#14014]
The current [Kubernetes plugin documentation](https://backstage.io/docs/features/kubernetes/overview) has some info missing:

1. Didn't mention `objectTypes` config which controls the default resource types to fetch, it only exists in source code and changelog which is not easy to find.
2. [The RBAC](https://backstage.io/docs/features/kubernetes/configuration#role-based-access-control) should be updated to reflect the requirement for metrics. Since the `skipMetricsLookup` is false by default, then access to the `pods.metrics.k8s.io` resource is required, but it's not mentioned anywhere in the doc. Besides, the error message is not particularly helpful, it could lead to some confusion (the PR https://github.com/backstage/backstage/pull/13966 tries to address this issue).
3. The documentation is a bit hard to read in general. e.g. It's hard to notice that `catalog`, `localKubectlProxy` and `config` are on the same level, and below are the subfields of `config`.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/9165473/194251653-1ac350d4-7c41-4620-a04f-88e1c34c1e3e.png">

I would love to open a PR to fix 1 and 2, but I'm not sure what could be done for the general readability of the documentation. I suppose some restructuring is needed but I don't want to jump the gun, therefore I opened this issue for discussion.

**Comment by freben** [comment]
@namco1992 I see this never got an answer - you have some good suggestions in here, are you able to contribute some of them to the repo? 🙏

**Comment by namco1992** [comment]
Hi @freben sorry I almost forgot the issue 😂 I will open a PR to fix points 1 and 2 as mentioned above, and leave 3 for future improvements. WDYT?
