### ISSUE TITLE
Validate that a location exists before emitting a location during GitHub Discovery

### ISSUE THREAD

**Issue by Niksko** [backstage/backstage#14013]
## Feature Suggestion

Ensure that when configuring a GitHub org for entity discovery using the GitHub provider, the only locations that are emitted are ones where there actually exists a matching file.

At the moment, entities are emitted for every matching repository, regardless of whether the file they reference exists or not.

## Possible Implementation

Use an instance of `UrlReader` in the `GitHubEntityProvider` to confirm that the location actually exists before emitting a location for it. I'm not 100% sure of how the plumbing works, but it seems like it should be possible to store the results of these requests in the cache, so that when the `UrlReaderProcessor` looks up these URLs, it can make use of the cached results, leading to no net increase in requests to GitHub.

Alternatively, it may be possible to adjust the existing GraphQL query to include information about whether the repositories have a matching file directly. It's certainly possible for a static file name, but it's much more complex if the `catalogPath` field includes a wildcard.

If people think this is a good idea, I'm more than happy to contribute this feature.

## Context

At the moment, using GitHub Discovery at any sort of large organisation is largely broken, unless the entire organisation has created the required `catalog-info.yaml` file (or equivalent). This is because the GitHub discovery provider (and other providers) do not check that a file exists in a repository before emitting a location. The naive configuration of the provider (and in fact, the one suggested in the docs) is:

```
catalog:
  providers:
    github:
      providerId:
        organization: 'backstage'
        catalogPath: '/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '.*'
```

The result of this is that a location is created for every single non-archived repository in the organisation, regardless of whether these repositories contain a `catalog-info.yaml` file. The outcome is that for large organisations, your API rate limit will be rapidly exhausted because of the constant barrage of 404s from these locations being endlessly refreshed.

I think people's intuition is that the discovery provider will only discover locations that actually exist. I think this intuition should match the implementation.

**Comment by jhaals** [comment]
Hi @Niksko!

Thanks for sharing this in an issue! This is very similar to the problems defined in #13959 and I'm not sure if we should move this discussion over there or keep it here.

In any case I think we should investigate the possibility of doing some additional "processing" to EntityProviders, as they are essentially controlled by the integrator it allows us to potentially do a bit more work prior to adding the Location into the catalog.

To combat this problem I wonder if we could leverage the GitHub search to only add locations that match the file pattern. 
This is an example query: https://github.com/search?q=user%3Abackstage+path%3A%2F+filename%3Acatalog-info.yaml&type=code

`user:backstage path:/ filename:catalog-info.yaml`

I tried it out on the backstage org and it seems like we potentially could add Locations based on the search result.

**Comment by Niksko** [comment]
@jhaals I agree it solves the same issue, but the approach is quite different. Happy to merge this discussion into that one, but I explicitly created this separate issue because the desire in #13959 seemed to be to holistically address the issue of 'rogue' locations which could end up in the catalog for a number of reasons. This issue is more about avoiding them getting into the catalog in the first place.

As far as GitHub search, that's a good idea. I'll have a play around and see if I can put up a PR.

**Comment by andrewthauer** [comment]
@Niksko - Have a look at my suggestion in issue #13959. I believe this will accomplish your goal without using the search API.

https://github.com/backstage/backstage/issues/13959#issuecomment-1272414423

**Comment by Niksko** [comment]
> @Niksko - Have a look at my suggestion in issue #13959. I believe this will accomplish your goal without using the search API.
> 
> https://github.com/backstage/backstage/issues/13959#issuecomment-1272414423

This is a great suggestion and does avoid the search API, but what do we do about users who want the wildcard feature that is currently available in the configuration of this provider?

Perhaps I'll just put up a PR with this simple solution to get us part of the way there, and then think further about how to use search. One suggestion I've found to get around the API limitations is that you use date ranges in your search to partition the search space. That said, I'm sure there is some esoteric GitHub org out there that breaks this, but it's a start.

**Comment by jrtaylorJH** [comment]
This really needs a better explanation in the docs.
