### ISSUE TITLE
Kubernetes plugin system & team overview

### ISSUE THREAD

**Issue by jvilimek** [backstage/backstage#14020]
Kubernetes plugin is great for having an overview about a single service. But if a team has multiple services grouped under one system or namespace and wants to see if everything is OK? Lot's of clicking. Let's support also "system" and "team" cards.

## Feature Suggestion

Now the Kubernetes card is "out of the box" supported only for service. At least in the example app, thanks to the following annotation: `'backstage.io/kubernetes-label-selector': 'app=xxx-service-name'`

![image](https://user-images.githubusercontent.com/16001792/194322228-c587c9a1-e447-44ab-936d-9db79335a77b.png)

Typically the service is part of a bigger system, like on the next screenshot, when we have at least 2 backend services under the backstage system. It would be great to see the overview for the kubernetes like suggested on the picture
![image](https://user-images.githubusercontent.com/16001792/194323113-f75ce9b2-107b-4b88-8833-16387e3be35f.png)

Or for a team to see status for all services they own like this:

![image](https://user-images.githubusercontent.com/16001792/194323979-a09e6623-e979-4e33-8c15-514591e6b9a1.png)

## Possible Implementation

There is one quite straightforward. We can use annotations and existing labels we have in our AKS + add support for the [system,group] entities in [EntityPage.tsx](https://github.com/backstage/backstage/blob/master/packages/app/src/components/catalog/EntityPage.tsx).

For **system** we have implemented label `backstage.io/system` so the annotation for the kubernetes cluster would be `'backstage.io/kubernetes-label-selector': "'backstage.io/system'=xxx-system-name"`.

For **group** we have implemented label `email` so the annotation for the kubernetes cluster would be `'backstage.io/kubernetes-label-selector': "email=xxx-email-of-group_at_oriflame.com`.

The above annotations we can add to entities manually or add a processor, that would create them for us automatically.

Another possibility is to "teach" kubernetes plugin to aggregate all services under a system/group and then query the AKS with `label-selector-for-service01 OR label-selector-for-service02 OR ...` 

## Context

A team has usually more then one service to take care of. Having to click through all of them in the backstage is not very comfortable.

**Comment by jhaals** [comment]
@backstage/warpspeed

**Comment by freben** [comment]
This could be one way. Another one is to double down on the Home experience, such that a card could list either all things related to you _and any of the teams you are in_ (as per your Backstage token / identity), or just the ones that have interesting anomalies in them.

I mention this because it's a bit inconvenient to locate your own user's page or your own teams' pages, by name so to speak. Those experiences would rather be looking centered around looking at the k8s statuses of others, not yourself.

**Comment by jvilimek** [comment]
Thanks for the comment/suggestion. The situation in our company is that one team might own multiple systems and each system might have multiple services. For example "camunda" system has "engine", "sink", "source" and "backoffice" services.
Maybe having an overview of all services "I or my teams" owns like you have described, but with the possibility to eventually drill down based on a team, system and even a service would do it?
