### ISSUE TITLE
Yarn build uses local config instead of production

### ISSUE THREAD

**Issue by kamil-wojcik** [backstage/backstage#14023]
## Expected Behavior

When building application production config  app-config.production.yaml should be used.

## Actual Behavior

Instead of app-config.production.yaml, app-config.local.yaml is used.

## Steps to Reproduce

1. setup backstage project
2. run `yarn build`
3. when build is run its reporting that 
```
yarn build
yarn run v1.22.19
$ backstage-cli repo build --all
Building packages
Building apps
Loaded config from app-config.yaml, app-config.local.yaml
```
## Context

This affects my because my prod config has customize base path for application.
I found that href to static resources were using root path (based on local config) rather than app.baseUrl from production config.  Because of that I was getting 502 as static resource hrefs were pointing to wrong basepath.

I didn't found any other command to build app for prod.

as quick fix I change package.json with following 

```
-    "build": "backstage-cli package build",
+    "build": "backstage-cli package build --config app-config.yaml --config app-config.production.yaml",
```
 

## Your Environment

- Browser Information: 
Not related. Problem with build

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.6.0 - darwin/x64
node: v14.20.0
yarn: 1.22.19
cli:  0.19.0 (installed)
backstage:  1.6.0

Dependencies:
  @backstage/app-defaults                          1.0.6
  @backstage/backend-common                        0.15.1
  @backstage/backend-plugin-api                    0.1.2
  @backstage/backend-tasks                         0.3.5
  @backstage/catalog-client                        1.1.0
  @backstage/catalog-model                         1.1.1
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.19.0
  @backstage/config-loader                         1.1.4
  @backstage/config                                1.0.2
  @backstage/core-app-api                          1.1.0
  @backstage/core-components                       0.11.1, 0.9.5
  @backstage/core-plugin-api                       1.0.6
  @backstage/errors                                1.1.1
  @backstage/integration-react                     1.1.4
  @backstage/integration                           1.3.1
  @backstage/plugin-api-docs                       0.8.9
  @backstage/plugin-app-backend                    0.3.36
  @backstage/plugin-auth-backend                   0.16.0
  @backstage/plugin-auth-node                      0.2.5
  @backstage/plugin-catalog-backend-module-github  0.1.7
  @backstage/plugin-catalog-backend                1.4.0
  @backstage/plugin-catalog-common                 1.0.6
  @backstage/plugin-catalog-graph                  0.2.21
  @backstage/plugin-catalog-import                 0.8.12
  @backstage/plugin-catalog-node                   1.1.0
  @backstage/plugin-catalog-react                  1.1.4
  @backstage/plugin-catalog                        1.5.1
  @backstage/plugin-github-actions                 0.5.9
  @backstage/plugin-home                           0.4.25
  @backstage/plugin-org                            0.5.9
  @backstage/plugin-permission-common              0.6.4
  @backstage/plugin-permission-node                0.6.5
  @backstage/plugin-permission-react               0.4.5
  @backstage/plugin-proxy-backend                  0.2.30
  @backstage/plugin-scaffolder-backend             1.6.0
  @backstage/plugin-scaffolder-common              1.2.0
  @backstage/plugin-scaffolder                     1.6.0
  @backstage/plugin-search-backend-module-pg       0.4.0
  @backstage/plugin-search-backend-node            1.0.2
  @backstage/plugin-search-backend                 1.0.2
  @backstage/plugin-search-common                  1.0.1
  @backstage/plugin-search-react                   1.1.0
  @backstage/plugin-search                         1.0.2
  @backstage/plugin-sonarqube-backend              0.1.1
  @backstage/plugin-sonarqube                      0.4.1
  @backstage/plugin-stack-overflow                 0.1.5
  @backstage/plugin-tech-radar                     0.5.16
  @backstage/plugin-techdocs-backend               1.3.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.4
  @backstage/plugin-techdocs-node                  1.4.0
  @backstage/plugin-techdocs-react                 1.0.4
  @backstage/plugin-techdocs                       1.3.2
  @backstage/plugin-user-settings                  0.4.8
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.0
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
```

**Comment by sennyeya** [comment]
This is expected behavior for the base `yarn build` which by default is meant for local development. 

See https://backstage.io/docs/conf/#supplying-configuration.

**Comment by kamil-wojcik** [comment]
However docs about docker and building docker image do not mention anything about that its only for local. This not very useful. Usually docker is used to build image locally or in CI server and run it somewhere else.

See [https://backstage.io/docs/deployment/docker](https://backstage.io/docs/deployment/docker  )

Ideally docker image should be env agnostic and config should be mounted as volume. That way it will follow 12 factor app 
[https://12factor.net/](https://12factor.net/)

**Comment by sennyeya** [comment]
The docker configuration supplied there works for the out of the box Backstage experience, it's expected that your Git instance will not include `app-config.local.yaml` per https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/.gitignore.hbs. Then `yarn build` in your CI server will only be operating on `app-config.yaml`. 

There is currently no easy way to have a completely environment agnostic server as the front end has to be generated at build time and packaged into the Docker container. I opened https://github.com/backstage/backstage/pull/13927 to allow for relative urls at build time, which should solve some of the issue.

**Comment by jhaals** [comment]
Indeed this is perhaps not perfect when you have a local config.
We should add a `--config` option to `backstage-cli repo build`. Anyone interested in fixing this? 🙏

**Comment by sennyeya** [comment]
Happy to take a stab at it, but I believe I had a discussion with @Rugvip in https://github.com/backstage/backstage/pull/13896 about frontend only configs (which if I'm understanding correctly is what this is). I think this would be solved by https://github.com/backstage/backstage/pull/13927 which could be passed in at build time.

**Comment by mist3r3** [comment]
I actually have the same issue, I was going a bit crazy actually about that until I found that the build doesn't take the config you specify (and you can't add a --config option). So for us using docker (which is for us the production), it means I HAVE to use the app-config.yaml as the production one.

I think it would be useful to be able to create the docker image with different configs.
This is just my opinion :D 

Thanks

**Comment by Rugvip** [comment]
See #14329 for `--config` for repo build. We're on it :grin:

**Comment by Rugvip** [comment]
This is the updates solution for this: #14627. The `yarn build` command was incorrectly pointing to `backstage-cli repo build --all`, which didn't really make sense. It's now removed in favor of a `build:backend` command that should be used instead.

If you're building the frontend separately, you can add something like this to your own project:

```json
"build:frontend": "yarn workspace app build",
"build:frontend:prod": "yarn workspace app build --config ../../app-config.yaml --config ../../app-config.production.yaml",
```

**Comment by joelleibow** [comment]
@Rugvip Thank you so much for the guidance w/ regard to building the frontend separately.

In the setup you [described here](https://github.com/backstage/backstage/issues/14023#issuecomment-1315202777), how would you recommend handling the backend build given that it automatically builds the frontend w/out forwarding any `--config` arguments that may be provided? Using `--skip-build-dependencies` doesn't work in the scenario where internal plugins also need built.

**Comment by alikhil** [comment]
It should be really well documented. I have waste my day trying to figure out what was the problem
