### ISSUE TITLE
Add/improve labels in banner when viewing an entity from Docs

### ISSUE THREAD

**Issue by anilazaidi** [backstage/backstage#14026]
When viewing an entity from the **Docs** link, the banner may confuse users for the following reasons:

* The "Component" label is misleading; a `kind: Resource` entity can also have documentation
* The `<>` icon may not be intuitive to non-technical users 

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/52043997/194387050-0489d608-d0e1-4061-8093-6c4d8d46000c.png">

## Feature Suggestion

* Update the "Component" label to "Entity"
* Add `source` label below the `<>` icon

## Context

As a new Backstage user, I was confused by the some of the labels when viewing an entity from the **Docs** link

**Comment by OrkoHunter** [comment]
@anilazaidi Great observations! Both of the suggestions definitely make sense 💯

**Comment by utkarsh867** [comment]
These seem to be quick fixes that I can work on :)

**Comment by anilazaidi** [comment]
Thank you so much!!

**Comment by awanlin** [comment]
Hi @anilazaidi and @utkarsh867, for this item: "The "Component" label is misleading; a `kind: Resource` entity can also have documentation" should the solution not be to use the Kind name? So in the example should it not say Resource for a Resource or API for an API? I don't think "Entity" is generally used in the UI

**Comment by anilazaidi** [comment]
Hi @awanlin , to be honest, and this is just a personal opinion, I wish the UI used the term "entity" rather than "component". Mainly b/c this is the term used in Backstage docs and it eliminates the confusion with `kind: Component`...

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/52043997/195107582-fd3c8659-541a-45dc-9b00-df8ff0b159e4.png">

But it sounds like you're saying that the "Component" label is actually resolved per the `kind` of the entity? Is this true?

**Comment by awanlin** [comment]
Hi @anilazaidi, that's fair and I agree with your original comment that having this say "Component" when you are looking at a "Resource" would be confusing, sorry if that wasn't clear. I see Entity as being a generic term for all Kinds, but if we have the information to provide the proper detail then we should. This also gets us a bit of consistency with the Catalog views where it does that already.

**Comment by anilazaidi** [comment]
> but if we have the information to provide the proper detail then we should.

Makes sense!

**Comment by anilazaidi** [comment]
Thanks so much @Rugvip!!
