### ISSUE TITLE
Table Search does not work correctly (Sometimes) when we have grouped rows in the table

### ISSUE THREAD

**Issue by shailendra-ahir-cbre** [backstage/backstage#14037]
## Expected Behavior
We have a table in our page where we have grouped the rows in a parent child relation by using the parentChildData prop to the table. When we are searching an entity on the table, filtering is not happening and the same results are shown which were there without search term. (Search is a No op)

It is working fine for non grouped single entity per row tables.

## Actual Behavior

It should be able to search the records in the table, when we have grouped the rows in a parent child manner.

![image](https://user-images.githubusercontent.com/91642195/194540380-d4b49c8a-55e8-4404-9634-bd7c1da16dd7.png)

## Steps to Reproduce

1. import backstage table component and groups the rows in a parent child relationship using parentChildData prop.
2. Try to search an asset from the search
3. It will not search the assets if the parent child data is faulty (more than one parent - it can happen when backstage is still processing the entity and not refreshed in UI yet)

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by shailendra-ahir-cbre** [comment]
It could be related to the data also. If an entity has two parents (out of sync entities between backstage re-processing) this issue can occur.

**Comment by Govardhandamam** [comment]
@shailendra-ahir-cbre can you let me know on which page is this issue?
