### ISSUE TITLE
[FileReaderProcessor, GithubDiscoveryProcessor] Detected conflicting entityRef after renaming the entity definition file

### ISSUE THREAD

**Issue by mwz** [backstage/backstage#14042]
Hello,

I'm using the file reader processor as a source for my catalog location when running Backstage locally. It's set up with a wildcard target, so .e.g I have a single folder with multiple files, let's call it `catalog` and the target is configured as `catalog/*.yaml`. I've noticed that changing a name of any of the entity definition files causes the catalog processor to throw the following warning:

> Detected conflicting entityRef system:default/x already referenced by file:old-file.yaml and now also file:new-file.yaml type=plugin

In fact, this also happens when moving existing entities between files, e.g. when ownership of those entities changes. 

This issue prevents those affected entities to be reprocessed and their old versions remain in the catalog indefinitely until deleted manually.

I use github-discovery in production instead, but also with a centralised catalog location using a wildcard on a single folder, so I'm suspecting the same issue might also exist there, but I'll test that separately and confirm.
edit: I can confirm this issue also happens for the GithubDiscoveryProcessor.

This looks quite similar to #11483, except that it's related to the file reader location source.

## Expected Behavior

I'd expect Backstage to detect when the existing entities have changed a location and process them successfully if there are no duplicates, i.e. if they don't exist in more than one location.

## Actual Behavior

Backstage throws a warning (Detected conflicting entityRef) which prevents those affected entities to be processed automatically.
The only way to resolve this is to manually delete the existing entity and Backstage will process the new entity, however this is impractical to do for a non-small collection of entities.

## Steps to Reproduce

1. Define a file location for the catalog in `app-config.local.yaml`, e.g.:
   ```yaml
   catalog:
     locations:
       - type: file
         target: ../../catalog/*.yaml
   ```

2. Create a simple entity definition file (e.g. `test.yaml`) in the `catalog/` directory located at the root of the project, e.g.:
	```yaml
	apiVersion: backstage.io/v1alpha1
	kind: Group
	metadata:
	  name: test-group
	  description: Test group
	spec:
	  type: organisation
	  profile:
	    displayName: Test Group
	  children: []
	---
	apiVersion: backstage.io/v1alpha1
	kind: System
	metadata:
	  name: test-system
	  description: Test System
	spec:
	  owner: test-group
	```
3. Run Backstage and let it process those entities.
4. Stop Backstage and rename the file, e.g. `test2.yaml`.
5. Re-run Backstage and see the conflicting entityRef warnings in the terminal, e.g.:
   > Detected conflicting entityRef system:default/test-system already referenced by file:/project-path/catalog/test.yaml and now also file:/project-path/catalog/test2.yaml type=plugin

## Your Environment

Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.16.0
yarn: 1.22.19
cli:  0.18.1 (installed)
backstage:  1.5.0

Dependencies:
  @backstage/app-defaults                          1.0.5
  @backstage/backend-common                        0.15.0
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         0.7.10, 1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.3
  @backstage/config                                0.1.15, 1.0.1
  @backstage/core-app-api                          1.0.5
  @backstage/core-components                       0.11.0, 0.9.5
  @backstage/core-plugin-api                       1.0.5
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.3
  @backstage/integration                           1.3.0
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-app-backend                    0.3.35
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.4
  @backstage/plugin-catalog-backend-module-github  0.1.6
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.5
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-import                 0.8.11
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.1.3
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-circleci                       0.3.8
  @backstage/plugin-explore-react                  0.0.20
  @backstage/plugin-explore                        0.3.39
  @backstage/plugin-github-actions                 0.5.8
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.4
  @backstage/plugin-permission-react               0.4.4
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-tech-radar                     0.5.15
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 0.1.3, 1.0.0
  @backstage/version-bridge                        1.0.1
✨  Done in 0.80s.
```

**Comment by freben** [comment]
In the mean time, there are some scripts floating around for auto-deleting orphaned entities, contributed by the community, for example this one https://github.com/backstage/backstage/blob/089fffc3e1d94e75bf95bb180cc49f3ce16d8c85/contrib/scripts/orphan-clean-up

**Comment by rasovskym** [comment]
Is it also the intention thaht it detects even if the locations are the same and the strings differ only in URL encoding? For example:

Detected conflicting entityRef **location:default/main-index** already referenced by url:
https://dev.azure.com/organization/Project/_git/repo?path=%2Fbackstage.yaml
and now also url:
https://dev.azure.com/organization/Project/_git/repo?path=/backstage.yaml

Can you handle this at the *Processor component level, or do I still need to delete such entities using the script above? Often this is an index and affects hundreds of entities.

**Comment by Rugvip** [comment]
Yes, we've discussed having some form of canonicalization of location URLs, but right now it's up to the providers to make sure they only use a single form of the URL. Of course this might be quite tricky when dealing with the location store, and it could be worth introducing some URL translation there
