### ISSUE TITLE
As a Backstage user, there's no visual difference between `experimental` and `production` entities

### ISSUE THREAD

**Issue by anilazaidi** [backstage/backstage#14062]
Currently, `experimental` and `production` entities have the same banner styles; the only difference between the two is under "Lifecycle" which a user can easily miss:

_experimental entity_

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/52043997/194886896-221b8cde-f182-4bf4-ae8f-142d7e1b2056.png">

_production entity_
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/52043997/194886998-9c483a51-c6fb-4b67-bfa5-83953d057dc4.png">

## Feature Suggestion

Differentiate styles for `experimental` vs. `production` entities. Possible suggestions:

* Different banner colour for experimental entites?
* Use different coloured tags for Lifecycle?

## Context

I was working with an engineer to improve their information in Backstage and they were surprised how there's no visual difference between experimental and production entities.

**Comment by andrewthauer** [comment]
It makes sense to me to have a more obvious visual pattern for indicating the `lifecycle`. However, one thing I'll point out is that `lifecycle` can be any value and an organization can make up their own list. So `experimental` is only a suggestion. However, it's likely this is commonly used by most organizations I would guess. So, it might be that the theme would need to accommodate this.

**Comment by jkjetty** [comment]
I’m interested in exploring some options here if no one else is working on it.

**Comment by jhaals** [comment]
Please do! I'll assign you @jkjetty

**Comment by jkjetty** [comment]
Thanks! Didn't make a ton of progress yet, but I'm liking highlighting the label for any non-prod entity like this so far. Thoughts?

<img width="266" alt="Screenshot 2022-12-19 at 3 42 33 PM" src="https://user-images.githubusercontent.com/11138157/208549145-ace5e2b0-ade5-4056-a925-d08519e0db98.png">

**Comment by anilazaidi** [comment]
> Thanks! Didn't make a ton of progress yet, but I'm liking highlighting the label for any non-prod entity like this so far. Thoughts?

Love this @jkjetty!! I think any difference between `experimental` and `production` is better than nothing. Or perhaps making the highlight for `production` entities only? Kinda like how required fields are usually in bold or with an asterisk (*).

**Comment by freben** [comment]
I'd suggest a small icon to the left/right of the word instead of a border. Perhaps even leveraging the builtin `<StatusOK />` and `<StatusWarning />` or similar for it? Or leaving it unmodified for the production lifecycle.
