### ISSUE TITLE
Table is formatted incorrectly in core-components reference documentation

### ISSUE THREAD

**Issue by mheidal-dataminr** [backstage/backstage#14071]
In the reference documentation for the core components, [accessible here](https://backstage.io/docs/reference/core-components), the table formatting breaks down after the code section.

## Expected Behavior

Page should render a table.

## Actual Behavior

Page renders a single paragraph with pipe characters separating what are meant to be table rows and columns.

## Steps to Reproduce

View webpage at https://backstage.io/docs/reference/core-components .

## Your Environment

- Browser Information: Google Chrome 105

**Comment by jhaals** [comment]
Good find! We should fix that, are you interested in taking a look? 🙏

**Comment by Vikki123** [comment]
@jhaals Could you please assign this to me ?

**Comment by auchynnikau** [comment]
leave a comments
leave a comments
leave a comments

**Comment by auchynnikau** [comment]
Hi guys! Just published PR #14148 with fix for this issue. @jhaals please, take a look.

**Comment by auchynnikau** [comment]
@jhaals fix was merged, so we can close this issue

**Comment by freben** [comment]
Thanks! <3
