### ISSUE TITLE
passport-saml <= 3.2.1 has signature bypass vulnerability

### ISSUE THREAD

**Issue by srd90** [backstage/backstage#14112]
See 
1. https://github.com/node-saml/passport-saml/security/advisories/GHSA-m974-647v-whv7
2. https://github.com/node-saml/passport-saml/releases/tag/v3.2.2

Workaround (according to security advisory): Disable SAML authentication.

`backstage`'s current `passport-saml` version:
https://github.com/backstage/backstage/blob/2bb7fa54d76b1190274e9430cb49279af469b79f/plugins/auth-backend/package.json#L73

**Comment by OrkoHunter** [comment]
I'm surprised there is no automatic Snyk-vulnerability issue for this, since we have a [workflow](https://github.com/backstage/backstage/blob/master/.github/workflows/sync_snyk-github-issues.yml) for it. I noticed there aren't new Snyk issues since [August](https://github.com/backstage/backstage/issues?q=is%3Aissue+label%3Asnyk-vulnerability+is%3Aclosed). cc @HHogg

**Comment by OrkoHunter** [comment]
I believe this will be fixed by a version bump of passport-saml to 3.2.2 right?

**Comment by erikxiv** [comment]
Sidenote: The following workaround can be used on local installations
```package.json
  "resolutions": {
    "passport-saml": "^3.2.2",
  }
```

**Comment by erikxiv** [comment]
> I believe this will be fixed by a version bump of passport-saml to 3.2.2 right?

Yes.

**Comment by OrkoHunter** [comment]
Looks like this was fixed by https://github.com/backstage/backstage/pull/14104. 🤖

**Comment by graynk** [comment]
Hey @OrkoHunter, sorry to bump an old thread, but it seems like `passport-saml` was deprecated in favor of `@node-saml/passport-saml`: https://www.npmjs.com/package/passport-saml

It also uses an old version of `@xmldom/xmldom`, which has a vulneravility, not sure `plugin-auth-backend` is affected by it or not: https://github.com/advisories/GHSA-crh6-fp67-6883
