### ISSUE TITLE
build:api-docs crashes because LANG is not en_US

### ISSUE THREAD

**Issue by marcofaggian** [backstage/backstage#14127]
## Expected Behavior

When launching `yarn build:api-docs` it should run `scripts/api-extractor.ts` succesfully till the end.

## Actual Behavior

When launching `yarn build:api-docs`[ it checks if the prompt was "options:"](https://github.com/backstage/backstage/blob/master/scripts/api-extractor.ts#L1091), but the underlying `commander.js` generates automatically an help prompt that's localized to `LANG` definition. In my case (`it_IT.UTF-8`), I got "Opzioni:", that's italian for options.

## Steps to Reproduce

1. `LANG=it_IT yarn build:api-docs`

**Comment by OrkoHunter** [comment]
Closed by https://github.com/backstage/backstage/pull/14128
