### ISSUE TITLE
Backstage not able to load on ios 16 chrome version 106.0.5249.92

### ISSUE THREAD

**Issue by HChenCBRE** [backstage/backstage#14124]
## Expected Behavior

Backstage load on chrome and firefox

## Actual Behavior

Backstage not able to load on ios version of chrome.(not sure if this is an existing issue for all iphone and ipad users)

## Your Environment
ios version: 16
chrome version: 106.0.5249.92

**Comment by OrkoHunter** [comment]
@HChenCBRE Hey! could you also share a screenshot? I am exactly sure what you mean by "unable to load". Could it be a rendering issue, could it be a network issue - there's so many things that can go wrong right. 😅
