### ISSUE TITLE
[MissingAnnotationEmptyState] Specify multiple annotation lines

### ISSUE THREAD

**Issue by aarlaud** [backstage/backstage#14136]
## Feature Suggestion

MissingAnnotationEmptyState should be explicitly specifying the missing annotation(s).
In some cases however, it can be more than one annotation required.
Supporting multiple lines would be nice.

## Possible Implementation

[MissingAnnotationEmptyState](https://github.com/backstage/backstage/blob/a8562101fafc5384b82da0b0c79cd6791138ebec/packages/core-components/src/components/EmptyState/MissingAnnotationEmptyState.tsx#L56) could take props containing an annotation or an array of annotations to return more than [one CodeSnippet](https://github.com/backstage/backstage/blob/a8562101fafc5384b82da0b0c79cd6791138ebec/packages/core-components/src/components/EmptyState/MissingAnnotationEmptyState.tsx#L80) lines.

## Context

Attempting to provide clear instructions for plugin users to configure the right annotations.
Reference [issue](https://github.com/snyk-tech-services/backstage-plugin-snyk/issues/63)

**Comment by freben** [comment]
The ask as such makes sense. If you'd like to contribute that (maybe adding one more prop called `annotations` or so, where only one of that or `annotation` needs to be specified), go ahead.

As a side note, I'm honestly not a great fan of these large empty states. They are just too visually cluttered and should probably be condensed down into a single line of plain text and a link to more info instead. But that is a separate topic and can be addressed elsewhere.

**Comment by JSPRH** [comment]
@aarlaud Could you please have a look at #14326 and check if this fulfills your suggestions?
