### ISSUE TITLE
[techdoc-cli] Serve command not working as expected, getting JS error (Not implementation available ...)

### ISSUE THREAD

**Issue by yj-ang** [backstage/backstage#14134]
## Expected Behavior

`techdocs-cli serve` command should work as expected which serving the markdown file preview in browser.

## Actual Behavior

<img width="1639" alt="Screenshot 2022-10-14 at 6 35 27 PM" src="https://user-images.githubusercontent.com/22940472/195827867-9f9ae3fc-a2ae-4499-8bcd-fa3175ed2b8a.png">

## Steps to Reproduce

1. Install CLI tool `npm install -g @techdocs/cli`
2. Navigate to target page
3. Run `techdocs-cli serve` in any directory that have `mkdocs.yml` file. (I also tried `techdocs-cli serve --docker-image spotify/techdocs:latest` and `techdocs-cli serve --no-docker`, no luck for me.)

## Context

Not sure what extra context I could provide.

## Your Environment

- Browser Information: Chromium Engine Version 106.0.5249.103

- Output of `techdocs-cli -V`:1.2.1

**Comment by freben** [comment]
@backstage/techdocs-core I labeled this one to you.

**Comment by soapraj** [comment]
Hi! @yj-ang there is no dependency on the search API when you run the techdocs-cli serve command so not sure why the error about missing impl for search is shown.

Can you try running on v1.2.2 with npx @techdocs/cli@1.2.2 serve ?

**Comment by agentbellnorm** [comment]
@yj-ang @soapraj, We're working on a fix for this, see https://github.com/backstage/backstage/pull/14323, 

In the meantime, you should be able to work around this by downgrading to `@techdocs/cli@1.2.0`

**Comment by ottosichert** [comment]
The fix is merged now and will be available in next week's release! Closing this for now, please re-open if you still encounter any issues when using the latest version.

**Comment by yj-ang** [comment]
Noted. Looking forward to next release. Thank you! @agentbellnorm @soapraj @ottosichert
