### ISSUE TITLE
Use an `.nvmrc` file to make it simpler to use a specific NPM version

### ISSUE THREAD

**Issue by ShayNehmad-RecoLabs** [backstage/backstage#14151]
## Feature Suggestion

Adding an `.nvmrc` file would make it easy to use a correct version, that's what I did in my fork.

## Possible Implementation

I'm just going to add the file in a PR in a second :) 

## Context

[See relevant StackOverflow issue](https://stackoverflow.com/a/57839539/4119906).

**Comment by awanlin** [comment]
@ShayNehmad-RecoLabs I'm wondering if maybe this should just be something that gets added to the documentation? So it would be showing people how to add and `.nvmrc` to their own Backstage instance.

By forcing it to a specific version like this is goes against the Node.js Release guidance documented here: https://backstage.io/docs/overview/versioning-policy#nodejs-releases

What do you think?

**Comment by Rugvip** [comment]
Yep I'm thinking the same thing. We already have engine requirements to make sure a compatible version is used, but I feel that using a specific node version is upp to each project.
