### ISSUE TITLE
Implement "Branch protection rules" support for "publish:github" action

### ISSUE THREAD

**Issue by tb137** [backstage/backstage#14171]
## Feature Suggestion
Implement "Branch protection rules" support for "publish:github" action. Right now, it's missing, although it has some features already implemented. Theoretically it should be a quick change.

## Possible Implementation
New type should be created:
```
export type BypassPullRequestAllowances = {
  users: string[];
  teams: string[];
  apps: string[];
};
```
And added almost identical implementation as it was done with introduction to "require_code_owner_reviews" feature. 

"require_code_owner_reviews" object has to be extended with by introducing "bypassPullRequestAllowances". Please check the link bellow:
https://github.com/backstage/backstage/blob/56ea7edf63c8cbb53b4a45a0e4fa7c6f3765a4f8/plugins/scaffolder-backend/src/scaffolder/actions/builtin/helpers.ts#L226

## Context
By enabling BypassPullRequestAllowances feature I would like to be able to add users, teams or GitHub apps into the section "Bypass Pull Request Allowances" for default secured branched.

"Bypass Pull Request Allowances" - feature can be found in each repo by going to:
Settings -> Branches -> "Branch protection rules" (rule must exist) -> "Edit" -> "Require a pull request before merging" -> "Allow specified actors to bypass required pull requests"

I have a rough implementation done already and it works. However, I used a bit of hacky way to implement it as it's a build in Action...

**Comment by Rugvip** [comment]
Sound sensible! Contributions adding more options to the built-in publish actions are always welcome! 👍

**Comment by kurtaking** [comment]
@Rugvip, should this be closed? I see https://github.com/backstage/backstage/pull/14320 has been merged.

**Comment by freben** [comment]
Indeed!
