### ISSUE TITLE
Omit managedFields from Kubernetes resource YAML

### ISSUE THREAD

**Issue by jpeach** [backstage/backstage#14177]
## Feature Suggestion

The Kubernetes plugin lets you see the YAML for Kubernetes resources. It would be great if the extremely verbose `managedFields` field was omitted from the YAML.

https://github.com/kubernetes/kubernetes/issues/90066

## Possible Implementation

Delete the `managedFields` key before rendereing YAML

## Context

Inspect the YAML representation of a Kubernetes resource.

**Comment by freben** [comment]
Or at least collapsing them perhaps in the interface so that they don't take up as much space by default. This is for the frontend right?

**Comment by jpeach** [comment]
IMHO, best to just omit them altogether.
