### ISSUE TITLE
Ability to pass `FetchApi` to `createRouter` in auth-backend plugin

### ISSUE THREAD

**Issue by kvmw** [backstage/backstage#14186]
## Feature Suggestion
I need to replace the default `FetchApi` with a custom one for `CatalogApi` ( `CatalogClient` ). I've done this in all places needed, except one in auth-backend. 

`createRouter` in auth-backend plugin instantiates a ` CatalogClient` which is used in `CatalogAuthResolverContext` to fetch the User Entity if exist.  this function (`createRouter`) should provide a mean to supply the custom `FetchApi` to `CatalogClient`.

## Possible Implementation
Add an optional `FetchApi` to `RouterOptions` and use this value  during `CatalogClient` instantiation:
```ts
export interface RouterOptions {
  // ...
  discovery: PluginEndpointDiscovery;
  fetch?: FetchApi;  // ADD THIS
  // ...
}

export async function createRouter(options: RouterOptions,): Promise<express.Router> {
    //...
    const catalogApi = new CatalogClient({ discoveryApi: options.discovery, fetchApi: options.fetch });  // USE HERE
    //...
}
```

## Context
Sometimes a custom `FetchApi` is needed to provide some header values or deal with certain responses from server.  Backstage  enables [customisation of this Api and others](https://backstage.io/docs/api/utility-apis) but the need to be injected in all places that are needed. `createRouter` in auth-backend does not let this api to be injected.

**Comment by Rugvip** [comment]
Yep there's np adding a customization point like this, although perhaps we should make it the entire `CatalogApi` rather than the `FetchApi`. This is all going to be a lot neater once we're over to using #11611 too.

Can I ask why you need this though? If you've set it some form of requirement to have particular headers when making requests towards the catalog that's likely going to be an issue in many other plugins too.

**Comment by kvmw** [comment]
@Rugvip I need the CatalogApi to skip TLS verification for a specific endpoint.  I am able to inject my custom `FetchApi` everywhere else in the app which CatalogApi is used except in the above function (createRouter). 
As you probably know after authentication, CatalogApi is used to query `User` entity.  This call (query User Entity) is the only one that is failing because the above issue. 

In general injecting dependencies is better than instantiating them internally.

**Comment by freben** [comment]
Yeah there's no fetch API wrapper in the backend at all. `fetchApiRef` is exclusively a frontend thing. But I agree that it sounds like it's the entire CatalogClient that should be replaced instead, right? Maybe with a shim that only replaces a single method and passes through the other ones to a delegate (the original client).

**Comment by kvmw** [comment]
@freben  yeah, agree. I initially thought about the least changes to support above requirement without breaking the current users code. but introducing a new method which accepts a CatalogApi and delegating the old method to the new one would be another option to avoid breaking clients code.
