### ISSUE TITLE
npx @backstage/create-app causes error: "Could not execute command git config user.name"

### ISSUE THREAD

**Issue by aSemy** [backstage/backstage#14221]
## Expected Behavior

The 'Getting Started' guide works https://backstage.io/docs/getting-started/

## Actual Behavior

The 'Getting Started' guide does not work https://backstage.io/docs/getting-started/

## Steps to Reproduce

1. I create a new directory
2. I run `npx @backstage/create-app`
3. I enter a name for the app
4. I get an error `Error: Failed to read git config, Error: Could not execute command git config user.name`

   ```none
   npx @backstage/create-app
   Need to install the following packages:
     @backstage/create-app@0.4.32
   Ok to proceed? (y) y
   ? Enter a name for the app [required] my-backstage
   
   Creating the app...
   
   Error: Failed to read git config, Error: Could not execute command git config user.name
   
   It seems that something went wrong when creating the app 🤔
   
   🔥  Failed to create app!
   ```

I then tried to initialise a git repo myself with `git init`, but this did not have any effect.

When I run `git config --list`, I can see `user.name`

## Context

It looks like the same happens in the GitHub Action https://github.com/backstage/backstage/actions/runs/3273459460/jobs/5385687308#step:9:19

This might be related to #13585?

## Your Environment

- Browser Information: n/a

- Output of `yarn backstage-cli info`:
    
    ```text
    yarn run v1.22.19
    error Couldn't find a package.json file in ".../backstage"
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    ```

**Comment by dollopofsunshine** [comment]
You can re install backstage-cli again using yarn and get past this error for yarn backstage-cli info. But no luck with the actual error

**Comment by awanlin** [comment]
@aSemy and @dollopofsunshine, I'm just curious what do you get when you run `git config user.name`?

**Comment by aSemy** [comment]
There's no output.

I have git installed, but I don't have a global config set for name or email. I set this per-project using [`includeIf`](https://git-scm.com/docs/git-config#_includes) or manually.

**Comment by awanlin** [comment]
@aSemy, thanks and totally fair how you have this setup. There should be some sort of check on this to handle cases like this here: https://github.com/backstage/backstage/blob/c2ee8f8cfcbdb0e3a5f4d56d3bdc01cbebf79760/packages/create-app/src/lib/tasks.ts#L270

Can you you try setting those values to see if it will get past this error and create the app?

**Comment by aSemy** [comment]
If I run `git init` then `git config user.name` returns my name, but I still get the same error

```shell
➜  ~ cd projects/backstage 
➜  backstage git init .
Initialized empty Git repository in /Users/adam/projects/backstage/.git/
➜  backstage git:(main) git config user.name           
Adam
➜  backstage git:(main) npx @backstage/create-app
? Enter a name for the app [required] test

Creating the app...

Error: Failed to read git config, Error: Could not execute command git config user.name

It seems that something went wrong when creating the app 🤔

🔥  Failed to create app!

➜  backstage git:(main) 

```

**Comment by aSemy** [comment]
It looks like the Backstage CLI creates a temporary directory - so I'm not sure how to work around this.

https://github.com/backstage/backstage/blob/c2ee8f8cfcbdb0e3a5f4d56d3bdc01cbebf79760/packages/create-app/src/lib/tasks.ts#L254

I actually don't feel comfortable that `create-app` is automatically fetching my personal details and initialising a git repo. That's not my normal experience with these sorts of tools. I'd prefer it if `create-app` prompted "enter your name/email, or leave blank to automatically fetch these"

**Comment by awanlin** [comment]
@aSemy ok, thanks. And it's totally fair to feel that way about your personal data. The intention was to help simplify things but it looks like for a number of people that's not the case

Worth mentioning that I did a quick `npx @backstage/create-app` run and it works fine for me though I do have both my name and email in my git config

**Comment by awanlin** [comment]
@aSemy yeah I think the fix would be to make them optional and fall back to some default value

@leonardomaier @Rugvip could you maybe help us out with this one?

**Comment by aSemy** [comment]
Yeah no problem, I see the purpose of it, it would be nicer if Backstage was easier to set up because at the moment it's very confusing. Personally I'd prefer it if Backstage had a proper Docker image (Docker Hub is flooded with undocumented, 3rd party images) and official docker-compose.yml. I've tried following the instructions for the Dockerfile but I get lots of issues. I'm just mentioning this here because I appreciate the effort in making Backstage easier!

> Worth mentioning that I did a quick npx @backstage/create-app run and it works fine for me though I do have both my name and email in my git config

If you're looking for a way to reproduce this, then you can see this in GitHub Actions:

https://github.com/backstage/backstage/actions/runs/3273459460/jobs/5385687308#step:9:19

Aside from the privacy aspect, any CLI tool should work without requiring interactive input (this helps with testing, or for headless installs). If `create-app` requires any input, it should be possible to set this using flags or a config file. A friendly interactive terminal is a nice extra.

**Comment by Rugvip** [comment]
@awanlin yep gonna dig into this a bit.

On the personal data aspect I wanna clarify that we're of course not doing anything with that information, it's simply a check to see if we will be able to initialize a git repo, since those values need to be set in configuration for that to be possible. I'll look at refactoring the code to make it a bit more clear that that is the case. Now that check has of course also failed in this case, because the entire point of that check was that it should not be required, which it now has ended up being.

**Comment by awanlin** [comment]
Thanks @Rugvip, seems like a number of people have run into this so will be nice to have it fixed

**Comment by Rugvip** [comment]
PR up over at #14278

**Comment by dollopofsunshine** [comment]
has this issue been fixed? I'm still facing the git config.name error.

**Comment by martinezhermes** [comment]
This hasn't been fixed yet.

**Comment by awanlin** [comment]
@dollopofsunshine @martinezhermes can you try using this specific version: `npx @backstage/create-app@0.4.33-next.0`, this has the changes from #14278 that should fix the git error

**Comment by martinezhermes** [comment]
it is fixed in the specified version npx @backstage/create-app@0.4.33-next.0

**Comment by wmunyan** [comment]
I came across this as I was having the same issue.  I tried running `npx @backstage/create-app@0.4.33-next.0`.

I received the following output (after some progress):
```
 Installing dependencies:
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
  executing     yarn install ✖

Error: Could not execute command yarn install
```

**Comment by dollopofsunshine** [comment]
I updated the version in package.json to use 0.4.33-next.0 and I'm able to create the app. Thanks guys.
