### ISSUE TITLE
gitlab auth provider errors

### ISSUE THREAD

**Issue by matiri132** [backstage/backstage#14234]
## Expected Behavior

Allow to use gitlab as an Auth provider

## Actual Behavior

When i got redirected to the gitlab signin page i get the following response:
`{"error":{"name":"NotFoundError","message":"No configuration available for the 'development' environment of this provider."},"request":{"method":"GET","url":"/api/auth/gitlab/start?scope=read_user&origin=https%3A%2F%2Fbackstage.mgt.moni.com.ar&env=development"},"response":{"statusCode":404}}`

If i change my configuration in app-config.yaml to:

```
auth:
  environment: developmento
    providers:
      gitlab:
        development:
          clientId: ${AUTH_GITLAB_CLIENT_ID}
          clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
          audience: https://${GITLAB_BASE_URL}`
```
The error changes to:
XHRGEThttps://backstage.mgt.moni.com.ar/api/auth/gitlab/refresh?optional&env=development
[HTTP/1.1 401 Unauthorized 173ms]

1
`{"error":{"name":"AuthenticationError","message":"Refresh failed; caused by InputError: Missing session cookie","cause":{"name":"InputError","message":"Missing session cookie","stack":"InputError: Missing session cookie\n    at OAuthAdapter.refresh (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:421:15)\n    at OAuthEnvironmentHandler.refresh (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:199:58)\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/app/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)"}},"request":{"method":"GET","url":"/api/auth/gitlab/refresh?optional&env=development"},"response":{"statusCode":401}}`

## Steps to Reproduce

1. Login from backstage sign-in page -> Response 404 on pop up
2. curl https://${BACKSTAGE_URL}/api/auth/gitlab -> Response 404

## Context

1. This is my _auth.ts_ file:
```
`import {
  createRouter,
  providers,
} from '@backstage/plugin-auth-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      gitlab: providers.gitlab.create({
        signIn: {
          async resolver({ result: { fullProfile } }, ctx) {
            return ctx.signInWithCatalogUser({
              entityRef: {
                name: fullProfile.id,
              },
            });
          },
        },
      }),
    },
  });
}
```
3. In my _app-config.yaml_ :
```
auth:
  environment: production
    providers:
      gitlab:
        production:
          clientId: ${AUTH_GITLAB_CLIENT_ID}
          clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
          audience: https://${GITLAB_BASE_URL}`
```
4. App.tsx :
```
const app = createApp({
  apis,
  components: {
     SignInPage: props => (
       <SignInPage
         {...props}
         auto
         provider={{
           id: 'gitlab',
           title: 'Moni Backstage Login',
           message: 'Sign in using GitLab',
           apiRef: gitlabAuthApiRef,
         }}
       />
     ),
  },  `
```
## Your Environment

We are deploying Backstage with a custom Docker image inside a k8s cluster and accessing it from an ingress, i had no problems with any other plugin or integration.

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```
OS:   Linux 5.15.74-3-MANJARO - linux/x64
node: v14.20.0
yarn: 1.22.19
cli:  0.18.1 (installed)
backstage:  1.5.0

Dependencies:
  @backstage/app-defaults                          1.0.5
  @backstage/backend-common                        0.15.0
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.0.4, 1.1.0
  @backstage/catalog-model                         1.1.0, 1.1.1
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1, 1.0.2
  @backstage/core-app-api                          1.0.5
  @backstage/core-components                       0.11.0, 0.11.1, 0.9.5
  @backstage/core-plugin-api                       1.0.6, 1.0.5
  @backstage/errors                                1.1.0, 1.1.1
  @backstage/integration-react                     1.1.3
  @backstage/integration                           1.3.0, 1.3.1
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-app-backend                    0.3.35
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.4
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.5, 1.0.6
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-import                 0.8.11
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.1.4, 1.1.3
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-github-actions                 0.5.8
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-permission-common              0.6.3, 0.6.4
  @backstage/plugin-permission-node                0.6.4
  @backstage/plugin-permission-react               0.4.4, 0.4.5
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-module-pg       0.3.6
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.0.0, 1.0.1
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-tech-radar                     0.5.15
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 0.77s.

```

**Comment by Rugvip** [comment]
Not seeing any obvious issue here. Is anything logged when you start up the backend that might shed some light? For example, I see this if I start the backend in dev mode without a full config:

```log
auth warn Skipping auth0 auth provider, Missing required config value at 'auth.providers.auth0.development.clientId'
```

Do you have `AUTH_GITLAB_CLIENT_ID` etc. set in the environment?

**Comment by matiri132** [comment]
I can pass away the error the error associated to "environment: production" updating the app-config.yaml , but i cant figure out why i need to use development for environment, where can i change this value?.

But actually my core problem is related to the 401 response in the gitlab auth provider.

**Comment by lalit774** [comment]
I also passed away the error in github associated to environment: production updating in ap-config.yaml as well as update in callback URL: api/auth/github/handler/frame?env=prod

**Comment by matiri132** [comment]
The callback URL from Gitlab App?

**Comment by lalit774** [comment]
No, it is from github. But i got the same error in github integration

**Comment by matiri132** [comment]
Yes i got it. 
I'll close this issue and open a new one with the new error i got.
