### ISSUE TITLE
Failed to create app! - Could not execute command git config user.name

### ISSUE THREAD

**Issue by dollopofsunshine** [backstage/backstage#14248]
## Expected Behavior
Backstage app should get created in local. The issue is observed only from previous day. 

## Actual Behavior

Errors out with npx @backstage/create-app with the below error.

 ~ % npx @backstage/create-app     
? Enter a name for the app [required] test

Creating the app...

Error: Failed to read git config, Error: Could not execute command git config user.name

It seems that something went wrong when creating the app 🤔

🔥  Failed to create app!

## Context

Unable to create local backstage app - Errors our with the above error 

## Your Environment

- Output of `yarn backstage-cli info`: 
~ % yarn backstage-cli info       
yarn run v1.22.19
warning package.json: No license field
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.17.0
yarn: 1.22.19
cli:  0.20.0 (installed)
backstage:  N/A

Dependencies:
  @backstage/catalog-client           1.1.1
  @backstage/catalog-model            1.1.2
  @backstage/cli-common               0.1.10
  @backstage/cli                      0.20.0
  @backstage/config-loader            1.1.5
  @backstage/config                   1.0.3
  @backstage/core-components          0.11.2
  @backstage/core-plugin-api          1.0.7
  @backstage/create-app               0.4.32
  @backstage/errors                   1.1.2
  @backstage/integration-react        1.1.5
  @backstage/integration              1.3.2
  @backstage/plugin-catalog-common    1.0.7
  @backstage/plugin-catalog-react     1.2.0
  @backstage/plugin-permission-common 0.7.0
  @backstage/plugin-permission-react  0.4.6
  @backstage/plugin-search-common     1.1.0
  @backstage/plugin-search-react      1.2.0
  @backstage/plugin-tech-radar        0.5.17
  @backstage/plugin-techdocs-react    1.0.5
  @backstage/plugin-techdocs          1.3.3
  @backstage/release-manifests        0.0.6
  @backstage/theme                    0.2.16
  @backstage/types                    1.0.0
  @backstage/version-bridge           1.0.1
✨  Done in 1.58s.

**Comment by ubreckner** [comment]
Can confirm, this is happening for me as well.

**Comment by freben** [comment]
Closing as duplicate, see discussion in #14221
