### ISSUE TITLE
[RFC] EventStream logs of a custom action

### ISSUE THREAD

**Issue by gocapa** [backstage/backstage#14251]
**Status:** Open for comments

## Need

I would need some more information on creating a custom action, I have seen the docs but still cannot understand properly how to implement it in my Backstage instance. The stream logs that this custom action generates how to pass it into the frontend. I gues that the scaffolder backend plugin does it all through the context but I still don't know how to do it.

Lets say that this custom action does a lot of things out of the backstage backend, image it sends API requests to some API REST. How to get the callback and prompt the logs into the frontend, specifically in the EventStream section of the Task when creating a component.

If anyone can clarify a bit how this all works, I would appreciate! 👍 

Thanks! :)

**Comment by freben** [comment]
The actions have access to a logger through the context. See the [section on writing actions](https://backstage.io/docs/features/software-templates/writing-custom-actions) in the docs. Those are the logs that get streamed to the frontend when you watch a scaffolding task run.
