### ISSUE TITLE
Upgrade Backstage Issue Templates to use Github Issue Forms

### ISSUE THREAD

**Issue by Rutam21** [backstage/backstage#14264]
## Introduction

GitHub has already rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This allows to create interactive issue templates and validate them.

Backstage currently uses the older [issue template format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). The task is to create GitHub issue forms for this repository. The issue form needs to be designed to accommodate all the fields in the current issue template.

## Tasks Summary

 - Prepare bug report issue form in .github/ISSUE_TEMPLATE/bug.yaml
 - Prepare feature request issue form in .github/ISSUE_TEMPLATE/feature.yaml
 - Prepare plugin suggestion issue form in .github/ISSUE_TEMPLATE/plugin.yaml
 - Prepare RFC issue form in .github/ISSUE_TEMPLATE/rfc.yaml
 - Prepare UX Component issue form in .github/ISSUE_TEMPLATE/ux_component.yaml
 - Push changes to the fork and test issue forms
 - Submit pull request

## Anything Else

Please assign this issue to me. I will be more than happy to submit a PR for this. Thanks.

**Comment by Rutam21** [comment]
@jhaals Please assign this to me. Thanks.

**Comment by Rugvip** [comment]
Nice! Thank you! 😁 👍
