### ISSUE TITLE
[Plugin][Vault] Be able to have multiple vault instances setup.

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#14266]
## Feature Suggestion

My team is using vault and we'd like to use the [vault plugin](https://github.com/backstage/backstage/tree/master/plugins/vault) and I think it would be great to have a way to have multiple vault instances setup.

## Possible Implementation

I'm not a great web developer, but I think that this use case is very similar to https://github.com/backstage/backstage/issues/10674

## Context

In our company, there multiple teams (obviously). But these multiple teams can have multiple setup : 
- They could have different vault instances
- They could have one vault instances but with different users between teams.

Because of that, I think it's needed to have a way to configure multiple vault instances in backstage.

**Comment by freben** [comment]
This one surprised me a bit. I'm not a vault user myself, but i was under the impression that there's typically one installation and then you fence off different parts of it with ACLs?

**Comment by iiro** [comment]
I guess this depends on organisation... A bit irrelevant but maybe also related to this: different namespaces. You bump into this the moment you use Vault Enterprise / the managed Vault from Hashicorp (HCP Vault).

**Comment by LvffY** [comment]
> This one surprised me a bit. I'm not a vault user myself, but i was under the impression that there's typically one installation and then you fence off different parts of it with ACLs?

@freben I agreed with @iiro it mostly depends on organizations.

In my case, even if we manage policies inside each vaults, we don't want (or can't) have a single vault server (for network or customers policies reasons for example).

Indeed, the "multiple namespaces" use case could be taken into account also.

From my point of vue, this would lead to the same technical answer (but I may be wrong here)

**Comment by djetelina** [comment]
> This one surprised me a bit. I'm not a vault user myself, but i was under the impression that there's typically one installation and then you fence off different parts of it with ACLs?

Our setup - multiple installations per environment, each environment using its own installation. Then each team owning multiple secret engines (only one KV though).
