### ISSUE TITLE
Allow to hide default tabs in UserSettingsPage

### ISSUE THREAD

**Issue by graynk** [backstage/backstage#14274]
## Feature Suggestion
Currently, `UserSettingsPage` allows to add custom user tabs, but does not allow for removing the default ones. 

## Possible Implementation
Someone suggested in Discord that it could be done in the same way as Explore plugin does it.
I assume this means using the construct `useOutlet() || <DefaultSettingsPage />` to allow for easy replacements.

## Context
We would like to see just the General tab and remove Auth Providers and Feature Flags.

**Comment by awanlin** [comment]
Thanks @graynk that was me on Discord. This is what I was meaning: https://github.com/backstage/backstage/blob/4442bf8aaab4d3d68fc32bfc5f9b2aaf34ee94db/plugins/explore/src/components/ExploreLayout/ExploreLayout.tsx#L51

**Comment by freben** [comment]
Sounds sensible. Is this something you would like to contribute? 🙏

**Comment by graynk** [comment]
Sure, no problem, I'll take a stab at it this week
