### ISSUE TITLE
CatalogBuilder addLocationAnalyzers & setLocationAnalyzer API confusing + breaking change

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#14273]
## Expected Behavior

The API surface for the `CatalogBuilder` shouldn't have a confusing API in regards to `LocationAnalyzer` related interfaces 

## Actual Behavior

Recently as part of #13800 the `catalog-import` analyze process was pushed back into the backend. On a whole this makes sense. However, it has also introduced a confusing API surface and behaviour change. There was an existing `CatalogBuilder.setLocationAnalyzer` method which allowed you to change the default `LocationAnalyzer` (defaults to `RepoLocationAnalyzer`). Now there is a `addLocationAnalyzers`. Without looking at the code this is very confusing as to which is used for what.

Under the covers though they are entirely different and the default `RepoLocationAnalyzer` wraps the new `ScmLocationAnalyzer` (which also is not inherited from the original `LocationAnalyzer`). Instead the implementation of. So, if you had previously implemented a custom `LocationAnalzyer` it won't work as expected unless you also change that custom `LocationAnalyzer` to also wrap the `ScmLocationAnalyzers` and mimic the behaviour of the default `RepoLocationAnalyzer`.

I'm all for these improvements, but the current current API is just really confusing and misleading between the `ScmLocationAnalyzer`, `LocationAnalyzer` interfaces and their relationship + the 2 similar but different `CatalogBuilder` methods.

## Possible Solutions

I haven't fully thought through a suggested solution, but here are some options:

- More clearly distinguish the difference between `LocationAnalyzer` and `ScmLocationAnalyzer`, by renaming one or the other concepts.
- Maybe combine both concepts into a single concept and API surface
- Decouple the relationship of the 2 concepts so one doesn't rely on the other.

**Comment by andrewthauer** [comment]
Here's my workaround, but which wasn't so bad, but I can't use the new `addLocationAnalyzers` method + I needed to pass the analyzers into into my `CustomRepoLocationAnalyzer` and use part of the default `RepoLocationAnalyzer` code. It works, just a bit confusing and seems a bit ackward.

```
builder.setLocationAnalyzer(
  CustomRepoLocationAnalyzer.fromConfig(config, {
    logger: env.logger,
    analyzers: [
      new GithubLocationAnalyzer({
        discovery: env.discovery,
        config: env.config,
      }),
    ],
  }),
);
```

**Comment by freben** [comment]
Agreed, this can be confusing. It's a bit similar to `setFieldFormatValidators` which actually drives the constructor arguments to `FieldFormatEntityPolicy` internally, which doesn't even come into play at all if you replace the original policies... So you might sometimes be surprised that the thing you added doesn't even have any effect.

Essentially it's a convenience, to be able to configure, so to speak, a given aspect of a feature in isolation, instead of being asked to replace the entire implementation of it. But the pattern has drawbacks. Now this is in a 1.x package, and got out in a mainline release too.

Technically, we could deprecate `addLocationAnalyzers` again, but it's a bit of an ask, right after telling people that they have to add usage of it to their backends.

Might it be sensible to wait for the backend system, when this will be more moved out into a module of its own and be done differently anyway?

**Comment by andrewthauer** [comment]
Sure that works. I have a workaround now + it's documented. I just wanted to flag this for others and maybe have a discussion on improving it in the future.

**Comment by andrewthauer** [comment]
Thinking on this a bit more. What we have here is essentially a composite pattern. However, in this case `ScmLocationAnalyzer` doesn't actually inherit the interface of `LocationAnalyzer`. As you can see my solution is doing exactly that. So in reality we probably don't need 2 catalog builder methods, but a way to create a composite or at least make it more clear in the API surface.

**Comment by freben** [comment]
Not even quite that, right - Or, I mean, you actually do it in a composite way. But another adopter might not be interested in consuming the added individual analyzers at all; they may do things entirely differently. So tweaking it to become composite (e.g. in the backend system work) might not be worth it either

**Comment by andrewthauer** [comment]
Yes, that's true. It's not exactly a composite, but does use composition accomplish the same thing I guess. The `setLocationAnalyzer` could with the default `RepoLocationAnalyzer` (like my workaround) and make `addLocationAnalyzers` unnecessary. Although, it might be a little more verbose in the case you don't customize the `RepoLocationAnalyzer`.

**Comment by freben** [comment]
We could update `setLocationAnalyzer` to accept EITHER an analyzer, or a function that takes an scm analyzer array and returns the final analyzer :) That would be backwards compatible. But the naming confusion remains.

**Comment by andrewthauer** [comment]
Very true. So, it sounds like the interfaces should be named more distinctly, then used in single `CatalogBuilder.setLocationAnalyzer` as suggested. I just can't come up with a great name at the moment, but if we have one we could deprecate the old method. But again, no rush from me to do this. The only thing I worry about is when code changes in the default `RepoLocationAnalyzer`, we may need to incorporate those for it to continue to function properly.
