### ISSUE TITLE
Template should work

### ISSUE THREAD

**Issue by kumarnil** [backstage/backstage#14282]
## Expected Behavior

1. Template create action should be working
2. Able to import any yaml file

## Actual Behavior

Create action fails with:

Backend request failed, 500 {"error":{"name":"Error","message":"Entity reference must not be empty","level":"error","service":"backstage"},"request":{"method":"POST","url":"/api/scaffolder/v2/tasks"},"response":{"statusCode":500}}

## Steps to Reproduce

1. Create...
3. Choose any Template
4. Fill in Form and click on Create

## Context
Using Developer Tools I can see the following details:
Request details:
{
	"templateRef": "template:default/create-spring-boot-template",
	"values": {
		"build_tool": "Maven",
		"java_version": "1.8",
		"application_name": "jjgjhgjhg",
		"application_description": "gjhgjh",
		"java_package_name": "gjhgjhg",
		"repoUrl": "BBBBBBBB",
		"git_project_name": "jgj"
	},
	"secrets": {
		"USER_OAUTH_TOKEN": "AAAAAAAAAAAAA"
	}
}

Response error:
{"error":{"name":"Error","message":"Entity reference must not be empty","level":"error","service":"backstage"},"request":{"method":"POST","url":"/api/scaffolder/v2/tasks"},"response":{"statusCode":500}}

## Your Environment

- Browser Information:  Google Chrome

- Output of `yarn backstage-cli info`: 
S:   Darwin 21.6.0 - darwin/arm64
node: v16.14.0
yarn: 1.22.19
cli:  0.20.0 (installed)
backstage:  1.7.0-next.0

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-common                        0.15.2
  @backstage/backend-plugin-api                    0.1.3
  @backstage/backend-tasks                         0.3.6
  @backstage/catalog-client                        1.1.1
  @backstage/catalog-model                         1.1.2
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0
  @backstage/config-loader                         1.1.5
  @backstage/config                                1.0.3
  @backstage/core-app-api                          1.1.1
  @backstage/core-components                       0.11.2, 0.9.5
  @backstage/core-plugin-api                       1.0.7
  @backstage/dev-utils                             1.0.7
  @backstage/errors                                1.1.2
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.3.2
  @backstage/plugin-api-docs                       0.8.10
  @backstage/plugin-app-backend                    0.3.37
  @backstage/plugin-auth-backend                   0.17.0
  @backstage/plugin-auth-node                      0.2.6
  @backstage/plugin-catalog-backend                1.5.0
  @backstage/plugin-catalog-common                 1.0.7
  @backstage/plugin-catalog-graph                  0.2.22
  @backstage/plugin-catalog-import                 0.8.13-next.1
  @backstage/plugin-catalog-node                   1.2.0
  @backstage/plugin-catalog-react                  1.2.0
  @backstage/plugin-catalog                        1.6.0
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-org                            0.5.10
  @backstage/plugin-permission-common              0.6.5-next.1, 0.7.0
  @backstage/plugin-permission-node                0.6.6-next.1, 0.7.0
  @backstage/plugin-permission-react               0.4.6
  @backstage/plugin-proxy-backend                  0.2.31
  @backstage/plugin-scaffolder-backend             1.7.0
  @backstage/plugin-scaffolder-common              1.2.1
  @backstage/plugin-scaffolder                     1.7.0
  @backstage/plugin-search-backend-module-pg       0.4.1
  @backstage/plugin-search-backend-node            1.0.3
  @backstage/plugin-search-backend                 1.1.0
  @backstage/plugin-search-common                  1.1.0
  @backstage/plugin-search-react                   1.2.0
  @backstage/plugin-search                         1.0.3
  @backstage/plugin-tech-radar                     0.5.17
  @backstage/plugin-techdocs-backend               1.4.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5
  @backstage/plugin-techdocs-node                  1.4.1
  @backstage/plugin-techdocs-react                 1.0.5
  @backstage/plugin-techdocs                       1.3.3
  @backstage/plugin-user-settings                  0.5.0
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

**Comment by freben** [comment]
Hi!

How are you signing in to Backstage? Could it be that you are running as guest?

Would you mind trying to upgrade to the latest version of Backstage to check if the problems persist?

**Comment by kumarnil** [comment]
Sign in to backstage using backstage using custom oauth-proxy provider. No, app is not set to use for guest user at this point of time.
yes I upgraded to latest version yesterday, but the issue did not fixed.

The following two functionality not working:
1) Can not import any *.yaml file into backstage
2) None of the template is working

Note:- When I run this app as Guest user the above functionality working fine.

**Comment by kumarnil** [comment]
**Here is the error log:**
[jwt_session.go:51] Error retrieving session from token in Authorization header: [unable to verify bearer token, oidc: id token issued by a different provider, expected "https://AAAAAAAA.com" got "https://BBBBBB.com/api/auth"]

**Comment by jhaals** [comment]
Hi, sorry to hear that you're having problems.
From reading the first error message is almost sounds like the token is missing information. Could you share how signin resolver is configured as that might have clues. It might also help to inspect issued token by decoding it in the browser, see https://backstage.io/docs/auth/troubleshooting#inspecting-the-contents-of-a-backstage-token for information on how to do that.

**Comment by kumarnil** [comment]
signIn: {
          resolver: async (signInInfo: any, ctx) => {
            const { roles: role, name: id } = signInInfo.result.fullProfile;
            const sub = `user:${id}`;
            return ctx.issueToken({
              claims: { sub, ent: [`${role}`] },
            });
          },
        },

**Comment by freben** [comment]
sub and ent must always contain full entity ref stringsbon standard form, with kind, namespace, and name. I recommend using stringifyEntityRef to form them. And double check that you don't get null/undefined in any of those variables.

**Comment by kumarnil** [comment]
**I did the below update in the code, but issue did not fixed.**

import {
  DEFAULT_NAMESPACE,
  stringifyEntityRef,
} from '@backstage/catalog-model';

 resolver: async (signInInfo: any, ctx) => {
            const { name: id } = signInInfo.result.fullProfile;
            if (!id) {
              throw new Error(`Login user profile does not contain a username`);
            }
            const userEntityRef = stringifyEntityRef({
              kind: 'User',
              name: id,
              namespace: DEFAULT_NAMESPACE,
            });

            return ctx.issueToken({
              claims: {
                sub: userEntityRef,
                ent: [userEntityRef],
              },
            });
          }

**Comment by kumarnil** [comment]
This issue is open for while, I will appreciate if you could assist me to fix this issue?

**Comment by Rugvip** [comment]
@kumarnil What is the issue that you are currently facing? What are you seeing in the logs and what does the relevant parts of your setup look like?

The error message you posted [here](https://github.com/backstage/backstage/issues/14282#issuecomment-1288967394) is a strange one, it doesn't look like it's coming from Backstage.

**Comment by kumarnil** [comment]
Here is the error pops up on ui screen:
Backend request failed, 500 {"error":{"name":"Error","message":"Entity reference must not be empty","level":"error","service":"backstage"},"request":{"method":"POST","url":"/api/scaffolder/v2/tasks"},"response":{"statusCode":500}}

![image](https://user-images.githubusercontent.com/108412139/199780107-bcdcd668-359d-4cf0-8400-e4bb2a943f57.png)


Developer tool:--
![image](https://user-images.githubusercontent.com/108412139/199780707-94012454-fe13-4e40-b8a9-10ca04c8271e.png)

**Comment by kumarnil** [comment]
@Rugvip  please ignore the error message https://github.com/backstage/backstage/issues/14282#issuecomment-1288967394. And look to the above error which is still there.

**Comment by Rugvip** [comment]
@kumarnil I'm not able to reproduce this in a newly created app, I'm able to fill in the form and click create without issue. Could you provide some steps for how to reproduce?

**Comment by kumarnil** [comment]
@Rugvip  I guess it is very similar to https://github.com/backstage/backstage/issues/11666.

**Comment by Rugvip** [comment]
@kumarnil ah alright, does the workaround there work for you for now? It's on the roadmap to have a better solution in place

**Comment by kumarnil** [comment]
I added the following code but did not fixed for me.

**packages/backend/src/index.ts**

apiRouter.use(
    '/scaffolder',
    await scaffolder(scaffolderEnv, config),
    (req, _res, next) => {
      delete req.headers.authorization;
      next();
    },
  );

**Comment by Rugvip** [comment]
@kumarnil you need to flip that around so that `await scaffolder(scaffolderEnv, config)` is the last argument

**Comment by kumarnil** [comment]
@Rugvip **There is no luck.** Issue did not fixed.

apiRouter.use(
      '/scaffolder',
      (req, _res, next) => {
        delete req.headers.authorization;
        next();
      },
      await scaffolder(scaffolderEnv, config)      
    );

**Comment by Rugvip** [comment]
@kumarnil alright, please provide some steps for how to reproduce the issue and we can have a look

**Comment by kumarnil** [comment]
@Rugvip If you follow the same steps mention on issue https://github.com/backstage/backstage/issues/11666
I guess you can recreate it. However I tried above temp solution but did not work for me.

**Comment by kumarnil** [comment]
I will appreciate for any suggestion or idea to fix this issue.

**Comment by minkimcello** [comment]
@kumarnil To clarify, the scaffolder doesn't output the error in local development, right? You only get the 500 error in the live deployed instance?

It's hard to diagnose the problem without seeing all the details but if the workaround in #11666 didn't work and all the Backstage dependencies are up to date, this might be a cluster config problem and not a Backstage bug.

**Comment by kumarnil** [comment]
This issue fixed after updating deployment files. Deployment files blocking header token.
