### ISSUE TITLE
backstage-cli: `repo build` command should accept `--config`

### ISSUE THREAD

**Issue by mtlewis** [backstage/backstage#14329]
## Feature Suggestion

When running `backstage-cli repo build`, it should be possible to supply repeated `--config` arguments in order to specify the configuration that should be used.

## Possible Implementation

If I'm reading [this](https://github.com/backstage/backstage/blob/master/packages/cli/src/commands/repo/build.ts#L29) right, we already try to read the options off the top-level command when running each individual build, so it might be as simple as adding `--config` as a supported option to `repo build`.

## Context

When running `package build` directly it's possible to pass `--config`, but when building an entire backstage monorepo, it doesn't seem to be possible to pass `--config` in `repo build` and have the option propagate down.

**Comment by mtlewis** [comment]
Presuming I'm not missing some way of doing this that already exists I'm happy to work on it myself, so feel free to assign it to me!

**Comment by mist3r3** [comment]
Hi I'm encountering the same issue actually, I want to use a different file than app-config.yaml (app-config.production.yaml). And when creating my docker traced it back to 'backstage-cli package build' that didn't take the config from 'yarn tsc --config app-config.production.yaml'

What's the alternative?

**Comment by jhaals** [comment]
@mtlewis this would be great! Mike are you happy with someone from the community to take this on if you're busy at the moment?

**Comment by Rugvip** [comment]
Actual solution for this is described here: https://github.com/backstage/backstage/issues/14023#issuecomment-1315202777
