### ISSUE TITLE
Make backend-common provide middleware for verifying Backstage ID Tokens

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#1435]
## Feature Suggestion

Export a BackstageIdentity middleware from `backend-common` that allows verification of Backstage ID Tokens passed from the frontend or other services.

## Possible Implementation

We need to grab the public keys published by `/auth/.well-known/jwks.json` and use those for verification. Hopefully we can rely on existing packages for the entire flow, or we can implement the key fetching and caching ourselves and use `jose` for the key verification.

**Comment by Rugvip** [comment]
This is somewhat dependant on https://github.com/spotify/backstage/issues/1847, as we'll need to be calling out to the auth backend to verify tokens.

**Comment by GoWind** [comment]
@Rugvip  : I would like to take a shot at being able to provide a solution for this , if possible. Can you assign this to me ?

**Comment by lowjoel** [comment]
@GoWind have you managed to make any headway with this? We're running into this and wondering if we should be building something or waiting for your implementation.

**Comment by GoWind** [comment]
@lowjoel  , Yes I am working on this at the moment as I couldn't find time before.
I am targeting a PR end of this week.

**Comment by punkle** [comment]
Hi @GoWind, I have been looking at how access_tokens, already authenticated (by an API gateway) and sent to backstage can be used to allow backstage to retrieve the identity of the logged in user.

I would be interested in chatting about what you are working on and / or seeing how I can help at all.

**Comment by janwillies** [comment]
That's a usecase we are very interested in as well.

**Comment by dhenneke** [comment]
@punkle @janwillies We are in a similar position, since we use an oauth2-proxy and wanted to reuse the identity of the outer login in Backstage. This doesn't align 100% with this issue, but I think it might be interesting to share. But I must admit that this is only integrated into the frontend so there is currently no real backend-session (though I'm not sure that actually exists yet). I wanted to integrate it more into to the backend but got a bit lost in the authentication and session code so we chose the easy-path for now 😄.

Here's out approach:

```
<User> ---> <OAuth 2 Proxy> -------> <Backstage Backend>
    (session)         (id_token in header)
```

We added a new backend-route `/api/user` that checks if there is a token in the header, extracts the user ID, calls our identity backend with a service account to receive the user details, constructs a backstage identity (read: `SignInResult`), and returns it as JSON.

Then we use a custom signin page (configurable in `createApp(...)`) that calls the endpoint and populates the identity in the frontend:
```tsx

export const AutomaticSignInPage = ({
  onResult,
  fallback: FallbackComponent,
}: AutomaticSignInPageProps) => {
  // we call /api/user here:
  const { loading, error, signInResult } = useUserInfo();

  useEffect(() => {
    if (!loading && !error) {
      // finish the login with the identity we just received
      onResult({
        ...signInResult!,
        // it's hard to transmit a function call as json ;)
        getIdToken: async () => (signInResult as any).jwt,
      });
    }
  }, [onResult, loading, error, signInResult]);

  if (error && FallbackComponent) {
    // we show the original sign-in page in case something goes wrong.
    return <FallbackComponent />;
  }

  // a plain waiting page
  return <Page themeId="home" />;
};
```

Et voilà, the frontend knows who you are.

**Comment by GoWind** [comment]
@punkle  : I think your query is perhaps unrelated to this issue, but during the OAuth2 login process, If you are using a standardized `auth` provider such as Okta or google , you will receive an ID token that will contain the information of the user. 

Right now, backstage populates the session with only the `id` of the user in the`id` token. 
I am not sure of the frontend, but IIRC, there seems to be an `identityAPI` that you can use to fetch this `id` token and or the identity information.

**Comment by punkle** [comment]
@GoWind @dhenneke thanks for the help. I believe @dhenneke your solution is going to work for our solution. We have implemented something similar. 🙇

**Comment by erikxiv** [comment]
👋 I am taking a stab at protecting the api backend with backstage id tokens - for selfish reasons but hopefully contributable. It works, but I am not so sure about a good way to get all plugin clients, both core and community, to supply the id token on all backend requests. Do you have any thoughts around this? I currently need to fork all plugins and manually add an authorization header - not a long term solution. Maybe add something to the DiscoveryApi?

My implementation:
* All clients (e.g. [CatalogClient](https://github.com/backstage/backstage/blob/master/packages/catalog-client/src/CatalogClient.ts#L85)) consume the IdentityApi to get the idToken and pass it along to backend request via the authorization header
* A middleware in the backend is added to all api routes (except auth)
* Middleware validates the idToken against public keys in the backend

**Comment by GoWind** [comment]
@erikxiv  : Sounds great ! We would love to have authentication headers sent via the core plugins as well, as currently that is a insecurity that we have been meaning to plug for a long time.

One further suggestion. Rather than assuming an `idToken` , can you make the solution somehow configurable ( such as providing a method that can take A token and not just the `idToken` ? ) . The limitation being, we still rely on access Tokens within our systems at Zalando and have to generate a "fake" idToken to work with backstage. We have no realistic path to upgrade to id Tokens atleast for the next year or so. 

I suspect that other organizations might have the same problem as well and some way to customize this behaviour would be very useful.

**Comment by freben** [comment]
This could warrant its own apiRef, like a `backendAuthorizationApiRef` or similar, whose default implementation indeed makes use of the identity API but can be replaced with anything.

Completely off the top of my head, maybe it could have something like

```ts
decorate(options?: FetchOptions): Promise<FetchOptions>
```

@Rugvip ping

**Comment by Rugvip** [comment]
> This could warrant its own apiRef, like a `backendAuthorizationApiRef` or similar, whose default implementation indeed makes use of the identity API but can be replaced with anything.
> 
> Completely off the top of my head, maybe it could have something like
> 
> ```ts
> authorizationHeader(): Promise<string | undefined>
> ```
> 
> with utility methods that aid with forming a basic auth header, a token auth header, etc.
> 
> @Rugvip ping
> 
> (i originally thought the api should be a general RequestInfo/RequestInit decorator but since that one-or-two-arg interface is a bit harder to work with, I though maybe restricting it explicitly to the auth header could make sense)

This is what the `getIdToken()` of the `IdentityApi` is already intended for, there's really no other use-case for that token atm.

> One further suggestion. Rather than assuming an `idToken` , can you make the solution somehow configurable ( such as providing a method that can take A token and not just the `idToken` ? ) . The limitation being, we still rely on access Tokens within our systems at Zalando and have to generate a "fake" idToken to work with backstage. We have no realistic path to upgrade to id Tokens atleast for the next year or so.

> I suspect that other organizations might have the same problem as well and some way to customize this behaviour would be very useful.

I think it should be enough if we tweak the `IdentityApi` contract to not expect the token to specifically be an OpenID Connect ID Token, or even a JWT at all. With that you can simply use your own token in the sign in result. If you end up needing a mix of tokens or want to migrate in the future, you can start registering custom factories for e.g. the catalog API, that overrides the `IdentityApi` to use a different token provider.

**Comment by freben** [comment]
Nice, that does simplify things a lot.

> This is what the `getIdToken()` of the `IdentityApi` is already intended for, there's really no other use-case for that token atm.

In the future as well? Not intending for this one to expose the actual ID token as presented by an underlying iodc endpoint (where applicable), as opposed to the Backstage issued one?

**Comment by Rugvip** [comment]
> > This is what the `getIdToken()` of the `IdentityApi` is already intended for, there's really no other use-case for that token atm.
> 
> In the future as well? Not intending for this one to expose the actual ID token as presented by an underlying iodc endpoint (where applicable), as opposed to the Backstage issued one?

It'd be up to the integrator to make sure that whatever token is provided in the frontend is also understood in the backend. By default we'd use the `auth-backend` issues Backstage Identity ID Token + accompanying middleware, but I think we should allow those to be switched out if needed, such as for @GoWind's case. Some orgs might also prefer using access tokens and/or tokens that they have issued themselves and have tighter control of.

**Comment by erikxiv** [comment]
I ran into an additional complexity, realizing that the catalog api is consumed from the backend as well. As far as I interpret the design, you want apis to be consistent client/server, negating the option to pass along the request context (containg the idtoken to forward) as well as allowing flexible deployment options for plugins, negating the option to bypass the router that now demands authorization. My best idea atm with minimum refactoring would be to use another auth mechanism such as basic authenticaton for server-to-server. Another idea would be to make all backend api calls go through an api, thus allowing different implementations client/backend with some request parameter allowing to identify the user. Thoughts?

**Comment by GoWind** [comment]
I am looking at the crumb trail of how to customize the behaviour. It looks like there is a custom SignInProvider with a 

https://github.com/backstage/backstage/blob/ad364bdf575a891ee43a0b49ff8cc1046f0f0bee/packages/core/src/layout/SignInPage/customProvider.tsx#L63

that implements the [Identity](https://github.com/backstage/backstage/blob/ad364bdf575a891ee43a0b49ff8cc1046f0f0bee/packages/core-api/src/app/types.ts)
API

I am not sure how customizable the customProvider is, but I assume if you can add an ability to customize how `getIdToken` functions, perhaps custom implementations can return values that are not `idTokens` on the frontend.  The reason for this suggestion is that I presume some plugins (core and non-core) already make use of  `getIdToken` for sending authentication information and it might be harder to retrofit a newer method in the `Identity ` API onto the plugin.

Plugins can also explicitly call a `getAuthenticationToken` method on the Identity API (which can be an optional  method added to the API as well).

**Comment by Rugvip** [comment]
> I ran into an additional complexity, realizing that the catalog api is consumed from the backend as well. As far as I interpret the design, you want apis to be consistent client/server, negating the option to pass along the request context (containg the idtoken to forward) as well as allowing flexible deployment options for plugins, negating the option to bypass the router that now demands authorization. My best idea atm with minimum refactoring would be to use another auth mechanism such as basic authenticaton for server-to-server. Another idea would be to make all backend api calls go through an api, thus allowing different implementations client/backend with some request parameter allowing to identify the user. Thoughts?

Initial thought would be to separate the backend and frontend clients in a way that allows the backend one to forward auth tokens, and the frontend one to provide them automatically. We'd adapt the existing client to accept a token, and that would be the backend one, and the frontend one would then be a wrapper around that which makes the token optional by using a token provider instead. Thoughts @backstage/maintainers ?

**Comment by Rugvip** [comment]
> I am not sure how customizable the customProvider is, but I assume if you can add an ability to customize how `getIdToken` functions, perhaps custom implementations can return values that are not `idTokens` on the frontend. The reason for this suggestion is that I presume some plugins (core and non-core) already make use of `getIdToken` for sending authentication information and it might be harder to retrofit a newer method in the `Identity ` API onto the plugin.

See https://github.com/backstage/backstage/issues/1435#issuecomment-730219831 above for how to customize the entire `SignInPage`. You then pass the entire custom component to the components option of `createApp`.

**Comment by erikxiv** [comment]
After some struggle attempting to fit into existing design with as little refactoring as possible, here is a suggestion: https://github.com/backstage/backstage/pull/3916 + https://github.com/backstage/backstage/pull/3914

WDYT? @GoWind I went with @Rugvip suggestion that adopters should be able to inject a custom token and optional use of custom passport strategies on the backend. Do you think that gives you the flexibility you need in your case?

Some of ☝️ belongs in documentation rather than code, but I wanted your input and approval on how example code looks like first (as well as a guide on where to document it).

**Comment by kenyee** [comment]
Would this also be able to hook into OIDC solutions like Okta or Duo or Google Logins?

**Comment by benjdlambert** [comment]
No really, only for backstage token. Not ID or acces.

**Comment by erikxiv** [comment]
@kenyee not sure I understood your question fully, but if the question was: can you use Okta/Google login client-side and use the experimental method described in the contrib section to allow these users to access Backstagr backend apis, then yes. Choose any of the auth providers provider by backstage. On login, a backstage token will be issued that will be sent to backend to authorize requests. The backend will not know/care which auth provider was used but can validate the backstage token and retrieve the user id.

If the question was, can a user logged in via Google access Googles services such as calendar/mail via Backstage, then probably not at this moment. There is some support to send requests from client-side (github pull requests plugin work this way), but I am not sure all auth providers provide this opportunity. These credentials are not sent to the backend atm, but could in theory support this in the future.

**Comment by kenyee** [comment]
Sorry...was hoping this would be able to pass a JWT token to a service backed Backstage plugin.  Use case is if you're logged into your company OIDC provider (Okta in our case), then hit backstage, then use a Backstage plugin that talks to a service API that needs to know your identity/email before handling the API call from the plugin via a passed JWT token.

**Comment by freben** [comment]
So the login (authorization) flow will result in backstage (the auth-backend plugin) issuing its own JWT token that contains proof of the user's established identity. THAT token can be passed down to backend plugins, which can unpack and verify it according to what this issue discusses

**Comment by marcosnils** [comment]
> THAT token can be passed down to backend plugins, which can unpack and verify it according to what this issue discusses

IIRC that's already implemented by the authn forward middleware that sends the token to all API calls. I believe what's missing in this PR is some helper functions to allow backend plugins to validate that token. That correct?

**Comment by erikxiv** [comment]
> IIRC that's already implemented by the authn forward middleware that sends the token to all API calls. I believe what's missing in this PR is some helper functions to allow backend plugins to validate that token. That correct?

I would say that there is _experimental_ support, as in it works but might benefit from more real world use-cases before stabilizing a design for it. Here is a guide on how to use the experimental helper function to validate the token on backend API requests: https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md

**Comment by OrkoHunter** [comment]
@GoWind I just re-assigned this to myself since this is now in our radar. Hope that's alright!

**Comment by OrkoHunter** [comment]
> Export a BackstageIdentity middleware from `backend-common` that allows verification of Backstage ID Tokens passed from the frontend or other services.

@Rugvip The use of `backend-common` and "frontend" in the same line threw me off a bit. 😅 Do we want to export a middleware from `@backstage/backend-common` package based on [this verify token logic in the auth-backend](https://github.com/backstage/backstage/blob/71cf82deee69d13aa985016e74711afa2aa80609/plugins/auth-backend/src/identity/IdentityClient.ts#L43-L73)? And, do we also want to provide a way to authenticate Backstage token in frontend plugins, perhaps using the existing `IdentityApi`?

My initial thought is having a [route on auth-backend](https://github.com/backstage/backstage/blob/71cf82deee69d13aa985016e74711afa2aa80609/plugins/auth-backend/src/identity/router.ts#L53-L55) which the frontend plugins can call (via `IdentityApi`) to verify a Backstage ID Token, and the route uses the same logic provided by `@backstage/backend-common` to respond. The backend plugins can directly use the middleware provided by `@backstage/backend-common`. Please correct if I'm wrong somewhere, thanks!

**Comment by marcosnils** [comment]
> The backend plugins can directly use the middleware provided by `@backstage/backend-common`. Please correct if I'm wrong somewhere, thanks!

SGTM!

**Comment by freben** [comment]
@OrkoHunter The frontend is involved in the sense that it triggers the sign-in cycle and gets the token back from the auth backend. The token can then be grabbed [from the identityApi](https://github.com/backstage/backstage/blob/master/packages/core-api/src/apis/definitions/IdentityApi.ts#L45) and sent to other backends that want to verify the calling user's credentials.

For anybody that wants to validate that a received token actually was issued by the auth backend and not somebody else, the [jwks endpoint](https://github.com/backstage/backstage/blob/71cf82deee69d13aa985016e74711afa2aa80609/plugins/auth-backend/src/identity/router.ts#L48) will probably be involved, but @Rugvip knows best here. I don't think you'll send an actual token to the auth backend to get it verified; instead you'll just validate the signing key used on the received token based on the known-good public keys that the auth backend exposes.

**Comment by GoWind** [comment]
The `/jwks` route will be used by downstream clients of Backstage (who are the ones that actually get the token) to verify if it was indeed, signed by the `auth-backend`. 

As for backend plugins, The ideal solution would be the `plugin-auth-backend` returning a middleware function wrapping over the `TokenIssuer` used by the authentication router, capable of verifying the Backstage tokens generated at the end of the authentication flow.

**Comment by erikxiv** [comment]
If one gets to submit a wish list, I would love something along the lines of https://github.com/backstage/backstage/issues/5210#issuecomment-812851729, wrapping both client-side and backend-side request in some Backstage-managed code that allows for future evolution of tokens without the need to rewrite all plugins.

I have been trying to keep up with new plugin releases and updates and it is fairly common that auth has been forgotten, either not sending the token from client-side, or not forwarding the client token in backend-to-backend requests.

**Comment by freben** [comment]
@GoWind Remember that we consider the backend pieces as separate. They MAY be co-deployed in one service, but that's not an assumption we want to make. So all plugins will, whether they are local or not, act as if they are separate and use the HTTP layer for talking to the auth backend.

**Comment by freben** [comment]
@erikxiv We are also looking at context propagation in and behavior injection, to make it easier to get these kinds of thing to traverse the boundaries without the plugin code even having to explicitly make sure that it happens.

**Comment by larkintuckerllc** [comment]
So, it is not clear if there is a solution in this discussion.  Thought to share a working example of securing a backend Plugin API endpoint using the JWT token supplied by Backstage.  Wrote this up as an article [1] as it was a bit complicated.
[1] https://john-tucker.medium.com/backstage-plugins-by-example-part-3-fd8b7d302b5b

**Comment by Rugvip** [comment]
This has been implemented in the [new auth system](https://github.com/backstage/backstage/tree/7ee0e13eb2e9fce0e2fc04163ad3a5685e37102b/beps/0003-auth-architecture-evolution)
