### ISSUE TITLE
Github Actions plugin: support using the app it self instead of user sign-in

### ISSUE THREAD

**Issue by ehrnst** [backstage/backstage#14364]
## Feature Suggestion

I would like the github actions plugin to authenticate with github using the app it self, and not end-user only. As of my understanding it needs a backend component to do this.
However, it should be possible to use the entity provider that already scrapes the repos without user credentials.

Additionally, a configuration option for disabling the feature where you can re-run the workflow from Backstage should be available. At least if my above request is implemented

**Comment by jhaals** [comment]
Hi @ehrnst! I don't understand fully what you would like to achieve. Could you perhaps provide some additional context to this feature suggestion?

**Comment by jhaals** [comment]
Hi @ehrnst! I don't understand fully what you would like to achieve. Could you perhaps provide some additional context to this feature suggestion?

**Comment by ehrnst** [comment]
> Hi @ehrnst! I don't understand fully what you would like to achieve. Could you perhaps provide some additional context to this feature suggestion?

Hi. I can at least try!

Today backstage has the ability to crawl github and read `catalog-info` files from the repos. To do this backstage is configured to authenticate using an app and a certificate, or using a personal token.
When one enables the frontend plugin for GitHub actions, you also have to enable the GitHub authentication provider, meaning a user need to use h*s personal credentials and sign in to github through backstage.

What I would like is for this to be a configurable option. Using end-user credentials, or let backstage backend pull the information about the pipelines using "its" credentials.

If that is implemented, a solution to perform re-deploys, etc from backstage should be a configurable option.

**Comment by freben** [comment]
Right. Yeah that would require a "helper" backend plugin which forwards requests and enriches them with the app token if a personal one wasn't given from the caller.
