### ISSUE TITLE
plugin-stack-overflow-backend doesn't appear to support the oauth config to support SO Teams

### ISSUE THREAD

**Issue by rayterrill** [backstage/backstage#14378]
plugin-stack-overflow-backend doesn't appear to support the oauth config to support SO Teams

## Feature Suggestion

Add support for passing an access token, which is required when access team-specific data.

## Possible Implementation

Amend StackOverflowQuestionsCollatorFactory.ts to support passing in a new parameter accessToken from the Backstage config, then using that in the call to the SO API.

## Context

StackOverflow plugin should allow returning results from SO teams, in addition to public SO.

I have this working in a forked copy of the Backstage plugin.

**Comment by jhaals** [comment]
FIY @emmaindal  :)

**Comment by iamEAP** [comment]
Thanks for the report @rayterrill!  I believe the functionality you're looking for was added here https://github.com/backstage/backstage/pull/14941, and shipped in the Backstage v1.9.0 release.  Give that a try!

If you're still encountering issues, feel free to re-open!  But closing this for now.
