### ISSUE TITLE
Github actions using deprecated set-output commands

### ISSUE THREAD

**Issue by kevinneville** [backstage/backstage#14377]
## Expected Behavior

Workflows should complete without warnings.
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

## Actual Behavior

The workflow shows warnings.

## Steps to Reproduce

Actions using old commands gives a warning like https://github.com/backstage/backstage/actions/runs/3228335759.

**Comment by Rugvip** [comment]
Closing this as we've replaced all of our own usages of `set-output` in #14784. There are still some warnings from external actions, but will leave those version bumps to renovate.
