### ISSUE TITLE
🚀 Feature: Support DisplayName on all Default Catalog Entities

### ISSUE THREAD

**Issue by antoniordz96** [backstage/backstage#14398]
### 🔖 Feature description

Today the `group` and `user` entities support the field `DisplayName: xxxxx`.  Our `Domains` don't follow the standard naming convention  set forth by Backstage and we would like `Domains` to support this field as well. 

Example Domain: `Digital Loyalty, CoBrand, and 3rd Party Partnerships`

### Today
- Domain: `name: "digital-loyalty-cobrand-3rd-part-relationships"`
### Expected
- Domain: 
   ```yaml
    name: "digital-loyalty-cobrand-3rd-part-relationships"
    displayName: "Digital Loyalty, CoBrand, and 3rd Party Partnerships"
   ``` 

This would actually be nice for all default entities

### 🎤 Context

I want to display properly in the UI the domain names

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by awanlin** [comment]
Hi @antoniordz96, I can totally understand that it's not very clear but this is what the `metadata.title` can be used for and is found on all Kinds. The documentation on this is here: https://backstage.io/docs/features/software-catalog/descriptor-format#title-optional. Hope that helps?

**Comment by antoniordz96** [comment]
Oh wow I completely missed this field but this solves our use cases. Thanks @awanlin

**Comment by awanlin** [comment]
You're welcome, happy to help :)
