### ISSUE TITLE
🐛 Bug Report: The subscribe button for Newsletter is not aligned with the rest of the buttons making the look somewhat inconsistent.

### ISSUE THREAD

**Issue by Rupsnigdha** [backstage/backstage#14390]
### 📜 Description

![image](https://user-images.githubusercontent.com/83987752/198878263-217eb793-b0da-4417-8289-cbd86ef60842.png)
The subscribe button for newsletter is not aligned with the rest of the buttons, making the look somewhat inconsistent.

### 👍 Expected behavior

The buttons are not lined up

### 👎 Actual Behavior with Screenshots

The buttons should be lined up.

### 👟 Reproduction steps

Go to https://backstage.io/community
Scroll down to Stay tuned to the latest developments

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rupsnigdha** [comment]
This is my first time reporting an issue in a public repo; hopefully I get this assigned to me and can work on fixing it! Cheers!!

**Comment by Rugvip** [comment]
@Rupsnigdha of course, thank you! 👍

**Comment by Rupsnigdha** [comment]
Are the files for the website in this repo as well? I do apologise as this is my first time contributing to an actual project...

**Comment by Rugvip** [comment]
Yes they are! That particular section is over here: https://github.com/backstage/backstage/blob/a8cf285b8f6dd799ca75d10acee64efb06f13201/microsite/pages/en/community.js#L98

You can preview by running `yarn install` + `yarn start` in `microsite/`

**Comment by Rupsnigdha** [comment]
I fixed those buttons. Should I also fix the alignment of the community initiatives buttons?
![image](https://user-images.githubusercontent.com/83987752/199030597-6081c39b-4cf4-4160-9977-c8554a901441.png)
(original) 
(again, new to open source so I don't know if I am supposed to do more than the issue I reported :P)

**Comment by Rupsnigdha** [comment]
Created a pull request; 14394 awaiting review. #14394

**Comment by Rupsnigdha** [comment]
Created a PR; awaiting review! #14395 (Closed 14394 because I forgot to sign off)

**Comment by Rupsnigdha** [comment]
#14395

**Comment by Rugvip** [comment]
Closed by #14395
