### ISSUE TITLE
🐛Facing Knex DB migration issue while updating Backstage to 1.7 from 1.5

### ISSUE THREAD

**Issue by Nitinvonage** [backstage/backstage#14401]
### 📜 Description

Upgrading backstage to 1.7 from 1.5 throws below error at the time of server start. 

`**The migration directory is corrupt, the following files are missing: 20220129100000_created_by.js**`

### 👍 Expected behavior

It should not throw any error in upgradation to latest backstage version

### 👎 Actual Behavior with Screenshots

Throwing error while running yarn dev command locally after updated all dependencies in package.json file

### 👟 Reproduction steps

1. Upgrading all the package.json files (app/backend/root) as per the update helper guide
2. removing **yarn.lock** file
3. running **yarn install** to fetch updated npms
4 **yarn dev** to run it locally, server failed to restart and throw this error - `**The migration directory is corrupt, the following files are missing: 20220129100000_created_by.js**`

### 📃 Provide the context for the Bug.

Server is not getting restarted because of this issue, hence not able to access backstage locally.

### 🖥️ Your Environment

S:   Darwin 21.6.0 - darwin/arm64
node: v16.17.0
yarn: 1.22.19
cli:  0.20.0 (installed)
backstage:  1.7.0

Dependencies:
  @backstage/app-defaults                               1.0.7
  @backstage/backend-common                             0.13.5, 0.15.2
  @backstage/backend-plugin-api                         0.1.3
  @backstage/backend-tasks                              0.3.6
  @backstage/catalog-client                             0.9.0, 1.1.1
  @backstage/catalog-model                              0.13.0, 1.1.2
  @backstage/cli-common                                 0.1.10
  @backstage/cli                                        0.20.0
  @backstage/config-loader                              1.1.5
  @backstage/config                                     0.1.15, 1.0.3
  @backstage/core-app-api                               1.1.1
  @backstage/core-components                            0.11.2, 0.9.5
  @backstage/core-plugin-api                            0.8.0, 1.0.7
  @backstage/dev-utils                                  1.0.7
  @backstage/errors                                     0.2.2, 1.1.2
  @backstage/integration-react                          0.1.25, 1.1.5
  @backstage/integration                                0.8.0, 1.3.2
  @backstage/plugin-api-docs                            0.8.10
  @backstage/plugin-app-backend                         0.3.37
  @backstage/plugin-auth-backend                        0.17.0
  @backstage/plugin-auth-node                           0.1.6, 0.2.6
  @backstage/plugin-catalog-backend-module-github       0.1.8
  @backstage/plugin-catalog-backend                     0.24.0, 1.5.0
  @backstage/plugin-catalog-common                      0.2.2, 1.0.7
  @backstage/plugin-catalog-graph                       0.2.22
  @backstage/plugin-catalog-import                      0.9.0
  @backstage/plugin-catalog-node                        1.2.0
  @backstage/plugin-catalog-react                       0.9.0, 1.2.0
  @backstage/plugin-catalog                             1.6.0
  @backstage/plugin-explore-react                       0.0.22
  @backstage/plugin-explore                             0.3.41
  @backstage/plugin-github-actions                      0.5.10
  @backstage/plugin-github-deployments                  0.1.41
  @backstage/plugin-home                                0.4.26
  @backstage/plugin-org                                 0.5.10
  @backstage/plugin-permission-common                   0.5.3, 0.6.4, 0.7.0
  @backstage/plugin-permission-node                     0.5.5, 0.7.0
  @backstage/plugin-permission-react                    0.3.4, 0.4.6
  @backstage/plugin-proxy-backend                       0.2.31
  @backstage/plugin-scaffolder-backend                  0.18.0, 1.7.0
  @backstage/plugin-scaffolder-common                   0.3.0, 1.2.1
  @backstage/plugin-scaffolder                          1.7.0
  @backstage/plugin-search-backend-module-elasticsearch 1.0.3
  @backstage/plugin-search-backend-module-pg            0.4.1
  @backstage/plugin-search-backend-node                 1.0.3
  @backstage/plugin-search-backend                      1.1.0
  @backstage/plugin-search-common                       0.3.4, 0.3.5, 1.1.0
  @backstage/plugin-search-react                        1.2.0
  @backstage/plugin-search                              1.0.3
  @backstage/plugin-sonarqube-backend                   0.1.2
  @backstage/plugin-sonarqube                           0.4.2
  @backstage/plugin-stack-overflow                      0.1.6
  @backstage/plugin-tech-radar                          0.5.17
  @backstage/plugin-techdocs-backend                    1.4.0
  @backstage/plugin-techdocs-module-addons-contrib      1.0.5
  @backstage/plugin-techdocs-node                       1.4.1
  @backstage/plugin-techdocs-react                      1.0.5
  @backstage/plugin-techdocs                            1.3.3
  @backstage/plugin-user-settings                       0.5.0
  @backstage/release-manifests                          0.0.6
  @backstage/search-common                              0.3.4
  @backstage/test-utils                                 1.2.1
  @backstage/theme                                      0.2.16
  @backstage/types                                      0.1.3, 1.0.0
  @backstage/version-bridge                             0.1.2, 1.0.1
### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
That duplicate scaffolder backend version doesn't look good, and is likely the cause of the issue:

```
@backstage/plugin-scaffolder-backend 0.18.0, 1.7.0
```

Could you trace where that is coming from with `yarn why @backstage/plugin-scaffolder-backend`? You want to get to the point where you only have the latest version installed.

**Comment by Nitinvonage** [comment]
works like a charm, thanks for the quick response....
