### ISSUE TITLE
💬 RFC: BitBucket catalog-import Pull Requests

### ISSUE THREAD

**Issue by gocapa** [backstage/backstage#14408]
### 🔖 Need

Hi, how can I use Pull Requests functionality for BitBucket when a repository doesn't have catalog-info.yaml anda open a PR?

Thanks

### 🎉 Proposal

.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by pjungermann** [comment]
this doesn't sounds like an RFC but rather like a support question. I suggest to join the [support channel on Discord](https://discord.com/channels/687207715902193673/1006844959170764851) or use the discussion feature here (even though Discord is more active I assume)

**Comment by Rugvip** [comment]
Yep, please post this question on Discord or in the GitHub discussions. This is not what the RFC format is for.
