### ISSUE TITLE
🔌 Plugin:  opencost.io based Cost Analysis Plugin 

### ISSUE THREAD

**Issue by hemuvemula** [backstage/backstage#14411]
### 🔖 Summary

[open cost ](https://www.cncf.io/projects/opencost/) is a CNCF sandbox project that provides cost insights in a cloud-native way agnostic of the cloud provider  I do understand that a plugin called [cost-insights](https://github.com/backstage/backstage/tree/master/plugins/cost-insights) exist which does the similar thing but having an open cost based plugin would benefit the larger CNCF community. 

### 🌐 Project website (if applicable)

https://www.opencost.io/
https://github.com/opencost/opencost

### ✌️ Context

- Real-time cost allocation, broken down by Kubernetes concepts down to the container level 
- Dynamic asset pricing, through integrations with AWS, Azure, and GCP billing APIs
- Support for on-prem Kubernetes clusters, using custom pricing sheets
- Allocation for in-cluster resources like CPU, GPU, memory, load balancers and persistent volumes
- Integrations with other open source tooling, such as easy pricing data exports to Prometheus

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Sounds like a great plugin to have, much wanted! 👏

**Comment by cthtrifork** [comment]
Very interesting. Definitely wanted

**Comment by Mihir-SRE** [comment]
This will be very helpful!

**Comment by WintonHuang1893** [comment]
+1

**Comment by CLL-leary** [comment]
+1

**Comment by mattray** [comment]
I'm looking into this on the OpenCost side. If anyone has any recommendations or want to assist, feel free to contact me.

**Comment by Rugvip** [comment]
@mattray If you find some way to work on this I'd be happy to support by clarifying anything on the Backstage side. I can grab some people who worked on the existing Cost Insights plugin too.

**Comment by andrewthauer** [comment]
We built a `cost-insights-backend` internally for a couple cloud resources we are tracking costs for. However, I'm interested in eventually adapting this to use either opencost and/or kubecost in the future.

So, I am also interested in keeping tabs on any progress towards this and/or bouncing some ideas around. However, I probably don't have the capacity to contribute much as far code in the short term though.

**Comment by mattray** [comment]
@andrewthauer happy to collaborate on this, I'm new to Backstage and hoping to get a better understanding how folks would use OpenCost/Kubecost in this context.

**Comment by andrewthauer** [comment]
@mattray - I'm the opposite when it comes to familiarity with OpenCost/KubeCost. I'm curious if you think this would be a new new frontend plugin / UI for Backstage or possibly leveraging the existing CostInsights plugin in some way. Correct me if I'm wrong, but from my understanding OpenCosts/KubeCosts only used to tracks costs for K8s resources? To me it might make sense to consolidate all cloud costs under a universal platform if possible. Assuming the API's support what is required, I believe that would be possible.

**Comment by CLL-leary** [comment]
> @mattray - I'm the opposite when it comes to familiarity with OpenCost/KubeCost. I'm curious if you think this would be a new new frontend plugin / UI for Backstage or possibly leveraging the existing CostInsights plugin in some way. Correct me if I'm wrong, but from my understanding OpenCosts/KubeCosts only used to tracks costs for K8s resources? To me it might make sense to consolidate all cloud costs under a universal platform if possible. Assuming the API's support what is required, I believe that would be possible.

correct. kubecost only shows k8s specific costs. however, you can map cloud infra tags to labels and then view high level cloud costs in kubecost. but my assumption is most backstage users already utilize cost insights for cloud cost. therefore i think your point is valid that maybe the best solution is to integrate kubecost into cost insights. 

either way, high level the goal is to provide one place to view the costs of something properly labeled/tagged from the cloud infrastructure down to the pod level.

**Comment by rmnicholson0612** [comment]
We are implementing kubecost at our org and are also building out backstage for developers. Being able to provide the developers kubecost in their services catalog page would be huge for helping hold them accountable for resource management.

**Comment by mattray** [comment]
https://github.com/backstage/backstage/pull/18383 if you want to review/give feedback

**Comment by mattray** [comment]
I think this issue can be closed https://github.com/backstage/backstage/tree/master/plugins/opencost
