### ISSUE TITLE
🚀 Feature: Add the ability to generate a web-library plugin with backstage-cli 

### ISSUE THREAD

**Issue by taras** [backstage/backstage#14417]
### 🔖 Feature description

`backstage-cli` can bundle different kinds of Backstage plugins. You can see a complete list of [available package roles](https://github.com/backstage/backstage/blob/master/packages/cli/src/lib/role/packageRoles.ts#L23) in the source code. There are several packages that use this role: [`@backstage/theme`](https://github.com/backstage/backstage/tree/master/packages/theme/package.json) and  [`@backstage/version-bridge`](https://github.com/backstage/backstage/tree/master/packages/version-bridge/package.json) . 

Unfortunately, `backstage-cli` doesn't support creating a plugin with a `web-library` role.

### 🎤 Context

One of our clients has new contributors to their inner source Backstage portal. They would like to be able to create `web-library` plugins. They would like to be able to tell their developers to use the CLI, but this is not currently possible.

### ✌️ Possible Implementation

This [conversation came up in Discord](https://discord.com/channels/687207715902193673/1024597193497247744) where @Rugvip suggested that to implement this, we need to add a factory and a template. 

Several [existing factories](https://github.com/backstage/backstage/tree/master/packages/cli/src/lib/new/factories) can be used for inspiration. There are also [existing templates](https://github.com/backstage/backstage/tree/master/packages/cli/templates) that can be found here.

### 👀 Have you checked if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes, I am willing to submit a PR!

**Comment by taras** [comment]
This is a "good first contribution".

**Comment by kurtaking** [comment]
Hi @taras , I've set up a [few files](https://github.com/backstage/backstage/compare/master...kurtaking:backstage:web-library-plugin) in preparation for working on this later.

I know that when I create a default plugin, I get a components directory, and when I create a backend plugin, I get router files.  What is the best way to determine what files need to be generated for a web-library plugin?

**Comment by taras** [comment]
@kurtaking 👋 thank you for picking this up. [@backstage/plugin-explore-react](https://github.com/backstage/backstage/tree/master/plugins/explore-react) is a good example of a web-library. 

A good place to start could be to include the following,

- /package.json
- /README.md
- /.eslintrc.js
- /src/index.ts
- /src/setupTests.ts

@Rugvip do we need to add anything else?

**Comment by kurtaking** [comment]
> @kurtaking 👋 thank you for picking this up.
> 
> [@backstage/plugin-explore-react](https://github.com/backstage/backstage/tree/master/plugins/explore-react) is a good example of a minimal web-library.
> 
> A good place to start could be to include the following,
> 
> * /package.json
> * /README.md
> * /.eslintrc.js
> * /src/index.ts
> * /src/setupTests.ts
> 
> @Rugvip do we need to add anything else?

I have opened https://github.com/backstage/backstage/pull/14840 with the files I've added so far. I am running into an issue with `/.eslintrc.js`. Can anyone help me with [this](https://github.com/backstage/backstage/pull/14840#issuecomment-1326672501)?

**Comment by kurtaking** [comment]
@Rugvip @taras this can be closed out 😄

**Comment by jhaals** [comment]
👏  Thanks!
