### ISSUE TITLE
[Gitlab] Allow Backstage to refer to Gitlab artifacts

### ISSUE THREAD

**Issue by maxm0rt** [backstage/backstage#14415]
### 📜 Description

Gitlab's URL resolver fails when trying to handle URLs that point at job artifacts. [There is an API](https://docs.gitlab.com/ee/api/job_artifacts.html#download-a-single-artifact-file-from-specific-tag-or-branch) to refer to those artifacts, so it is a well known format.

If one puts a link to the artifact in a `$text: <url>` placeholder in either the web UI or API friendly format the Gitlab URL resolver will return an error rather than processing the url.

This happens because the current Gitlab URL resolver only handles `/blob/` URLs. It also assumes those URLs need to be translated from a web UI format to an API-compatible format.

Ideally an `api.yaml` that looks like:
```
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-service-apis
  description: My Service APIs
spec:
  type: openapi
  lifecycle: production
  owner: MyTeam
  system: MyPlatform
  definition:
    $text: https://mygitlab.example.com/api/v4/projects/15244/jobs/artifacts/develop/raw/public/openapi/openapi.json?job=pages
```
would work.

### 👍 Expected behavior

When given an artifact url, the Gitlab URL resolver should at least allow it to pass.

### 👎 Actual Behavior with Screenshots

```
[1] 2022-11-02T18:35:44.397Z catalog warn Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location https://mygitlab.example.com/api/v4/projects/15245/jobs/artifacts/develop/raw/my-service/build/openapi.json?job=test, Error: Please provide full path to yaml file from GitLab type=plugin entity=api:default/my-service-apis
```

### 👟 Reproduction steps

1. Enable the Gitlab catalog provider or point Backstage at a Gitlab repository another way 
2. Create an API resource which contains a placeholder `$text:` pointing at a stable artifact URL
3. Allow the processor to run

### 📃 Provide the context for the Bug.

In my use case, OpenAPI specs are generated as a part of our repository's gitlab CI pipeline in our standard workflow. Some service owners will check those Open API specs back into their source control, others don't. I encountered this while trying to get one of the services which does not check their spec into source control integrated with Backstage.

With a small monkey patch in `getGitLabFileFetchUrl` I was able to verify that Backstage can handle the API urls if the resolver allows them:
```
async function getGitLabFileFetchUrl(url, config) {
+ if (isJobArtifact(url)) {
+   return url.toString();
+ }
  const projectID = await getProjectId(url, config);
  return buildProjectUrl(url, projectID, config).toString();
}
+ function isJobArtifact(url) {
+   return JSON.stringify(url).includes("/jobs/artifacts/");
+ }
```
Presumably `isJobArtifact` should be more robust than my implementation though. 

### 🖥️ Your Environment

yarn run v1.22.19
$ /Users/mamorton/Work/avengers/backstage-playground/maxtest/node_modules/.bin/backstage-cli info
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.16.0
yarn: 1.22.19
cli:  0.20.0 (installed)
backstage:  1.7.0

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-common                        0.15.2
  @backstage/backend-plugin-api                    0.1.3
  @backstage/backend-tasks                         0.3.6
  @backstage/catalog-client                        1.1.1
  @backstage/catalog-model                         1.1.2
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0
  @backstage/config-loader                         1.1.5
  @backstage/config                                1.0.3
  @backstage/core-app-api                          1.1.1
  @backstage/core-components                       0.11.2
  @backstage/core-plugin-api                       1.0.7
  @backstage/errors                                1.1.2
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.3.2
  @backstage/plugin-api-docs                       0.8.10
  @backstage/plugin-app-backend                    0.3.37
  @backstage/plugin-auth-backend                   0.17.0
  @backstage/plugin-auth-node                      0.2.6
  @backstage/plugin-catalog-backend-module-gitlab  0.1.8
  @backstage/plugin-catalog-backend                1.5.0
  @backstage/plugin-catalog-common                 1.0.7
  @backstage/plugin-catalog-graph                  0.2.22
  @backstage/plugin-catalog-import                 0.9.0
  @backstage/plugin-catalog-node                   1.2.0
  @backstage/plugin-catalog-react                  1.2.0
  @backstage/plugin-catalog                        1.6.0
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-org                            0.5.10
  @backstage/plugin-permission-common              0.7.0
  @backstage/plugin-permission-node                0.7.0
  @backstage/plugin-permission-react               0.4.6
  @backstage/plugin-proxy-backend                  0.2.31
  @backstage/plugin-scaffolder-backend             1.7.0
  @backstage/plugin-scaffolder-common              1.2.1
  @backstage/plugin-scaffolder                     1.7.0
  @backstage/plugin-search-backend-module-pg       0.4.1
  @backstage/plugin-search-backend-node            1.0.3
  @backstage/plugin-search-backend                 1.1.0
  @backstage/plugin-search-common                  1.1.0
  @backstage/plugin-search-react                   1.2.0
  @backstage/plugin-search                         1.0.3
  @backstage/plugin-tech-radar                     0.5.17
  @backstage/plugin-techdocs-backend               1.4.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5
  @backstage/plugin-techdocs-node                  1.4.1
  @backstage/plugin-techdocs-react                 1.0.5
  @backstage/plugin-techdocs                       1.3.3
  @backstage/plugin-user-settings                  0.5.0
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Totally doable! The place this needs to be implemented is in the `GitlabUrlReader` over [here](https://github.com/backstage/backstage/blob/19b0030ace47a583e93b00f4652c652d7db38dd8/packages/backend-common/src/reading/GitlabUrlReader.ts#L76), which of course also quickly takes you to the `getGitLabFileFetchUrl` that you pointed out.

The only tweak I'd say is the input URL. The one you used there is for fetching it straight via the API. Is there a different URL that a user would find in the GitLab GUI instead? To be clear we can support both, but there needs to be a nice flow for the user where they don't have to do manual URL conversion imo.

**Comment by maxm0rt** [comment]
Agreed with respect to avoiding manual conversion. I'll do a bit more research on that front. In the mean time, I will get started on a PR for this!

**Comment by maxm0rt** [comment]
[I've created a PR for this](https://github.com/backstage/backstage/pull/14586)

The only unexpected part of the PR (I think) is the bit I added about naively passing api URLs. To me it doesn't make much sense blocking them or assuming they are blob urls like it was initially written, but I can change the PR to return to that behavior if desired
