### ISSUE TITLE
🐛 Bug Report: FeatureFlag API is not using the StorageAPI

### ISSUE THREAD

**Issue by Sabrina0614** [backstage/backstage#14418]
### 📜 Description

We are excited to see user-settings-backend plugin being added in `v1.6.0` release, which allows backstage to save user specific settings to DB, and we are also thrilled to try it out.

Shortcuts and started entities seems to be working properly. However, it seems that `feature flags` is not being updated to use `StorageAPI` based on the current newest release, as shown in the [code](https://github.com/backstage/backstage/blob/v1.8.0-next.1/packages/core-app-api/src/apis/implementations/FeatureFlagsApi/LocalStorageFeatureFlags.tsx#L93), the [comment](https://github.com/backstage/backstage/blob/v1.8.0-next.1/packages/core-app-api/src/apis/implementations/FeatureFlagsApi/LocalStorageFeatureFlags.tsx#L46-L47), and [another code](https://github.com/backstage/backstage/blob/v1.8.0-next.1/packages/core-app-api/src/app/AppManager.tsx#L495-L499)

### 👍 Expected behavior

- When a user toggles the featured flags and also happens to open up the developer tool's networking tab, a user should see the networking call to update the featureFlags settings. 
- When a user click the `Feature Flags` tab in the setting, a user should also see a networking call to get the Feature Flags setting

### 👎 Actual Behavior with Screenshots

When loading the feature flags tab or changing the feature flags toggle:

1. there is no networking call happens from the developer tool's networking tab
2. user can see the feature flag setting is being updated in the `Local Stoarge` from the developer tool's Application tab

#### Prerequisite
1. Go to settings in the UI, where the feature flags tab is located at
2. Before Clicking the feature flags tab, opens up the networking tab in the developer's tool

#### Loading Feature Flags
1. Click on the feature flags tab
2. Notice that there is no networking call to get the feature flags setting

#### Updating the Feature Flags
1. Change the setting of one of the feature flag
2. Notice that there is no networking call to put/update the feature flags setting
3. Click on the Application tab in the developer's tool
4. Click on the `Local Storage` from the side bar
5. Click on the `featureFlags` key
6. Change the setting of one of the feature flag
7. Noticed that the feature flags got updated accordingly in the local storage

### 📃 Provide the context for the Bug.

Not able to completely move our user settings to DB

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by freben** [comment]
Hi!

This one's possibly not entirely clear-cut. I see where you're coming from, but some feature flags are pretty testing- or device-specific in such a way that you may or may not be interested in having them have the same value everywhere. Maybe you're developing something that's just functional on desktop for now but breaks badly on mobile, so you want different flag states.

One possibility for now could be to keep the current LocalStorageFeatureFlags and let that stay as the default implementation for now, and maybe you could contribute a different UserSettingsFeatureFlags class that an adopter can pick as the implementation for that feature if they so choose? That would be a great contribution, I think! 🙏
