### ISSUE TITLE
🐛 Bug Report: Scaffolder documentation recommends insecure approach to mask secrets

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#14428]
### 📜 Description

The documentation at https://backstage.io/docs/features/software-templates/writing-templates#hide-or-mask-sensitive-data-on-review-step suggests usage of `ui:widget: password` to hide input. This is a pretty big footgun, since these values get stored in the tasks execution without being treated as secrets. They can therefore be viewed by other users.

### 👍 Expected behavior

Either our implementation needs to handle these values as secrets, or we need to recommend against the usage of `ui:widget: password`, or something else.

### 👎 Actual Behavior with Screenshots

We recommend an insecure approach that leaks secrets.

### 👟 Reproduction steps

1. Create a template with a field that uses `ui:widget: password`
2. Execute the template by filling out the form
3. Go to the task list and select the task run from (2), and click "Start Over"
4. Edit the DOM properties of the input to remove `type="password"` to reveal the secret that you entered in (2)

### 📃 Provide the context for the Bug.

https://github.com/backstage/backstage/pull/11154#issuecomment-1302055861

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by brahimk** [comment]
Hello everyone,

I would like to disable/hide the 'All' button which displays all tasks from all users.

I want to display only the tasks I own without giving the possibility to see those of others.

THANKS

**Comment by Panfilwk** [comment]
just noting that the secret will also appear in the query string of the URL of the page navigated to in step 3 of the repro

**Comment by Panfilwk** [comment]
@Rugvip, in the original issue that this one split from you mentioned:
> To enter a password in a secure way you'd need a custom field extension that communicates its value via a secret instead.

I've been looking through the [docs](https://backstage.io/docs/features/software-templates/writing-custom-field-extensions) and [source](https://github.com/backstage/backstage/tree/master/plugins/scaffolder-react/src/extensions) and it appears that custom field extensions can only modify the UI of a field and not the method by which it passes data to scaffolder steps/actions, is there something that I'm missing or is this not a viable path forward?

**Comment by freben** [comment]
Not sure it's well documented yet, but at least in the updated new version of the scaffolder, you can pass secrets to the template through a dedicated mechanism. Main entry point for fields is [useTemplateSecrets](https://github.com/backstage/backstage/blob/3ce57434f055541e43547aad893ae7405b6bf5b6/plugins/scaffolder-react/src/secrets/SecretsContext.tsx#L72)

**Comment by benjdlambert** [comment]
Thinking that we should create a `CustomFieldExtension` that can make use of `useTemplateSecrets` to set secrets automatically, and update the Documentation to instead of using the `ui:widget: password` we use our `ui:field:` instead.
