### ISSUE TITLE
🐛 Bug Report: PinSideBar is not using the StorageAPI

### ISSUE THREAD

**Issue by Sabrina0614** [backstage/backstage#14436]
### 📜 Description

We are excited to see user-settings-backend plugin being added in v1.6.0 release, which allows backstage to save user specific settings to DB, and we are also thrilled to try it out.

Shortcuts and started entities seems to be working properly. However, it seems that pinSideBar is not being updated to use StorageAPI based on the current newest release, as shown in the [code](https://github.com/backstage/backstage/blob/v1.8.0-next.1/packages/core-components/src/layout/Sidebar/localStorage.ts#L21)

### 👍 Expected behavior

When a user toggles the pinSideBar and also happens to open up the developer tool's networking tab, a user should see the networking call to update the pinSideBar settings.
When a user clicks the pinSideBar tab in the setting, a user should also see a networking call to get the pinSideBar setting

### 👎 Actual Behavior with Screenshots

When loading the general tab in settings or changing the pinSideBar toggle:

there is no networking call happens from the developer tool's networking tab
user can see the pinSideBar setting is being updated in the Local Stoarge from the developer tool's Application tab****

#### Prerequisite
1. Before going to the settings, opens up the networking tab in the developer's tool

#### Loading pinSideBar
1.  Go to settings in the UI, where the pinSideBar is located at
2. Notice that there is no networking call to get the feature flags setting

#### Updating the pinSideBar
1. Change the setting of pinSideBar
2. Notice that there is no networking call to put/update the pinSideBar setting
3. Click on the Application tab in the developer's tool
4. Click on the `Local Storage` from the side bar
5. Click on the `sideBarPinState` key
6. Change the setting of one of the feature flag
7. Noticed that the pinSideBar got updated accordingly in the local storage

### 📃 Provide the context for the Bug.

Not able to completely move our user settings to DB

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Sabrina0614** [comment]
Similar to https://github.com/backstage/backstage/issues/14418 but a different component

**Comment by freben** [comment]
Similar to my comment on the other ticket - is this always the case? Do you want the same setting on all devices, always, unconditionally? :)

This one isn't too controversial though. I think it could make sense to update this one as you describe. Is it something you might be interested in contributing? 🙏
