### ISSUE TITLE
🐛 Bug Report: TechDocs documentation generation fails on windows

### ISSUE THREAD

**Issue by ZatoIchi** [backstage/backstage#14456]
### 📜 Description

Running generation of documentation for example Backstage documented component results in error on Windows.

if I remove techdocs-core plugin from mkdocs.yml, the documentation gets built alright.

### 👍 Expected behavior

Documentation gets built.

### 👎 Actual Behavior with Screenshots

```
λ npx @techdocs/cli generate --no-docker
info: Using source dir c:\temp\backstage-KtkUGP
info: Will output generated files in c:\temp\backstage-KtkUGP\site
info: Generating documentation...
Failed to generate docs from c:\temp\backstage-KtkUGP into c:\temp\backstage-KtkUGP\site; caused by unknown error 'Command mkdocs failed, exit code: 1'
```

mkdocs build gives:
```
λ mkdocs build
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: c:\temp\backstage-KtkUGP\site
ERROR    -  Error reading page 'index.md': join() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\Lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs\__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs\commands\build.py", line 308, in build
    _populate_page(file.page, config, files, dirty)
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs\commands\build.py", line 172, in _populate_page
    page = config.plugins.run_event('pre_page', page, config=config, files=files)
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs\plugins.py", line 517, in run_event
    result = method(item, **kwargs)
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs_monorepo_plugin\plugin.py", line 71, in on_pre_page
    set_edit_url(config, page, self)
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs_monorepo_plugin\edit_uri.py", line 105, in set_edit_url
    page.edit_url = edit_url.build()
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs_monorepo_plugin\edit_uri.py", line 98, in build
    if self.__has_repo():
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs_monorepo_plugin\edit_uri.py", line 85, in __has_repo
    page_config_file_yaml = self.__get_page_config_file_yaml()
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs_monorepo_plugin\edit_uri.py", line 80, in __get_page_config_file_yaml
    abs_page_config_file_path = self.__get_page_config_file_path()
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs_monorepo_plugin\edit_uri.py", line 51, in __get_page_config_file_path
    alias = self.__get_page_dir_alias()
  File "C:\Users\P905120\AppData\Local\Programs\Python\Python310\lib\site-packages\mkdocs_monorepo_plugin\edit_uri.py", line 35, in __get_page_dir_alias
    alias = path.join(*parts)
TypeError: join() missing 1 required positional argument: 'path'
```

### 👟 Reproduction steps

1. Download example documentation from here:
https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/examples/documented-component/
navigate to the documentation root directory

2. Run `npm install -g @techdocs/cli`
3. Run `python -m pip install mkdocs-techdocs-core==1.*`
4. Run `npx @techdocs/cli generate --no-docker`

### 📃 Provide the context for the Bug.

I am trying to follow CI/CD configuration described here https://backstage.io/docs/features/techdocs/configuring-ci-cd

### 🖥️ Your Environment

yarn run v1.22.19
$ c:\temp\1\tmp-bckstage\node_modules\.bin\backstage-cli info
OS:   Windows_NT 10.0.19044 - win32/x64
node: v16.17.0
yarn: 1.22.19
cli:  0.20.0 (installed)
backstage:  1.7.1

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-common                        0.15.2
  @backstage/backend-plugin-api                    0.1.3
  @backstage/backend-tasks                         0.3.6
  @backstage/catalog-client                        1.1.1
  @backstage/catalog-model                         1.1.2
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0
  @backstage/config-loader                         1.1.5
  @backstage/config                                1.0.3
  @backstage/core-app-api                          1.1.1
  @backstage/core-components                       0.11.2
  @backstage/core-plugin-api                       1.0.7
  @backstage/errors                                1.1.2
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.3.2
  @backstage/plugin-api-docs                       0.8.10
  @backstage/plugin-app-backend                    0.3.37
  @backstage/plugin-auth-backend                   0.17.0
  @backstage/plugin-auth-node                      0.2.6
  @backstage/plugin-catalog-backend                1.5.0
  @backstage/plugin-catalog-common                 1.0.7
  @backstage/plugin-catalog-graph                  0.2.22
  @backstage/plugin-catalog-import                 0.9.0
  @backstage/plugin-catalog-node                   1.2.0
  @backstage/plugin-catalog-react                  1.2.0
  @backstage/plugin-catalog                        1.6.0
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-org                            0.5.10
  @backstage/plugin-permission-common              0.7.0
  @backstage/plugin-permission-node                0.7.0
  @backstage/plugin-permission-react               0.4.6
  @backstage/plugin-proxy-backend                  0.2.31
  @backstage/plugin-scaffolder-backend             1.7.0
  @backstage/plugin-scaffolder-common              1.2.1
  @backstage/plugin-scaffolder                     1.7.0
  @backstage/plugin-search-backend-module-pg       0.4.1
  @backstage/plugin-search-backend-node            1.0.3
  @backstage/plugin-search-backend                 1.1.0
  @backstage/plugin-search-common                  1.1.0
  @backstage/plugin-search-react                   1.2.0
  @backstage/plugin-search                         1.0.3
  @backstage/plugin-tech-radar                     0.5.17
  @backstage/plugin-techdocs-backend               1.4.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5
  @backstage/plugin-techdocs-node                  1.4.1
  @backstage/plugin-techdocs-react                 1.0.5
  @backstage/plugin-techdocs                       1.3.3
  @backstage/plugin-user-settings                  0.5.0
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 0.94s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by AndyMcKenna** [comment]
I'm also running into this exact same issue with the same environment and results

**Comment by javaface** [comment]
I'm also running into this exact same issue with the same environment and results

**Comment by fabiano-amaral** [comment]
Hey, anyone has a solution or workaround for this issue?

**Comment by tycoeur** [comment]
I just got this issue and tracked it.

On Windows function `__is_root()` of file `edit_uri.py` check if the a page is in hierarchy of docs_dir or not.
Parent is checked by looking strings with "in" operator, but one path is a normalized (the page path), and the second isn't.

For example (to be more concret), for me it was like this in Python:
```python
# original code: return abs_root_config_docs_dir in self.page.file.abs_src_path
return "C:\Users\frederic.xxxxxxxxx-exte\AppData\Local\Temp\backstage-1do7mr\docs" in "c:\Users\FREDER~1.XXX\AppData\Local\Temp\backstage-1do7mr\docs\write-your-doc\doc-sample.md"
```

As you got it, this cannot work... 

Workaround: 
* use another temp directory, just define env variable TEMP to point something simple like c:\temp (create the directory!)
* try to work with a "short" name user (less than 8 chars) 😆 
* fix the code

To fix the code, there's multiple way, do:
```python
  def __is_root(self):
    root_config_docs_dir = self.__get_root_docs_dir()
    abs_root_config_file_dir = self.__get_root_config_file_path()
    abs_root_config_docs_dir = path.join(abs_root_config_file_dir, root_config_docs_dir)

    # normalizing abs_src_path was done, but in case code someone change abs_src_path settings, it's safer 
    import os
    return os.path.normpath(abs_root_config_docs_dir) in os.path.normpath(self.page.file.abs_src_path)
```

Note: 
* The issue isn't consistent, I don't know why but sometimes it works with the same kind of paths (with both short names or both long names);
* If you try to run mkdocs directly with a given name type (`cd` in directory with short or long name), it will change the behavior also!

Hope that will help you.
I'll submit a bugfix proposal for this issue (ASAP).

**Comment by axiac** [comment]
It still happens on Windows.
The workaround described in [tycoeur's comment](https://github.com/backstage/backstage/issues/14456#issuecomment-1836646422) works.

If you either set the `TEMP` environment variable or the configuration property `backend.workingDirectory` to a short path (f.e. `C:\Temp`), the error vanishes and the documentation is built properly.

However, the issue is still there and it would be nice to have it fixed in the code, if possible.
