### ISSUE TITLE
🚀 Feature: Prevent reloading the page when theme changes

### ISSUE THREAD

**Issue by omerfarukdogan** [backstage/backstage#14479]
### 🔖 Feature description

Changing the theme should only cause the components to re-render without losing their state. Currently, when the theme changes, all the state is lost and the whole page reloads.

### 🎤 Context

I'm developing a quick theme switcher component which is accessible from the sidebar (similar to [SidebarThemeSwitcher](https://github.com/backstage/backstage/blob/a68d86eaa61bcee1529309159daa462a1534b8f4/packages/dev-utils/src/devApp/SidebarThemeSwitcher.tsx)). When the theme is switched, the whole page reloads, and every data is fetched again. Ideally, this should not happen since only the styling changes. This is not a good user experience.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jhaals** [comment]
Hi!

I just did a quick test on the demo site and it does not look like this is a problem at least when changing theme at https://demo.backstage.io/settings/general
I was not able to see anything obvious in the SidebarThemeSwitcher when looking at the code. Have you identified what might cause problems?

**Comment by jhaals** [comment]
Hi @omerfarukdogan.
You are correct that it is indeed reloading, thanks for double checking! 👍 
[AppThemeSelector](https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/apis/implementations/AppThemeApi/AppThemeSelector.ts) is the underlying API that switches the theme for anyone interested in troubleshooting this 🙏

**Comment by omerfarukdogan** [comment]
Not stale.

**Comment by omerfarukdogan** [comment]
Not stale.

**Comment by karthikjeeyar** [comment]
FYI @jhaals @omerfarukdogan I have opened a PR to fix this issue. Could you please reopen this issue?
