### ISSUE TITLE
[scaffolder-backend] Bitbucket Cloud scaffolder actions

### ISSUE THREAD

**Issue by akundrock** [backstage/backstage#14501]
### 🔖 Need

Using the software templates (scaffolder) it would be helpful to have some of the functionality for Bitbucket Cloud that is already available for Github.
Some examples include:

- github:actions:dispatch
- - Dispatches a GitHub Action workflow for a given branch or tag
- github:webhook
- - Creates webhook for a repository on GitHub.
- github:repo:push
- - Initializes a git repository of contents in workspace and publishes it to GitHub.
- publish:github:pull-request
- - No description

My particular need is to create a bitbucket branch in an existing repo, template some code, and open a pull request back to the main branch. Since Atlassian / Bitbucket doesn't seem to offer a JavaScript SDK the particular actions would have to use their REST API instead.

Additional actions could include:

- Bitbucket default branch restrictions
- Enabling Bitbucket pipelines
- Open a pull request from an existing branch
- Create a branch (optionally templating the working directory)

### 🎉 Proposal

I propose to create a group of functions / createActions under the scaffolder backend to support the additional actions under a directory for Bitbucket Cloud (similar to the github folder). This new directory could include helper functions that are specific to Bitbucket Cloud. Here is a link to the existing file structure: https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin

New actions could have a name such as 'bitbucket-cloud:pull-request' or 'bitbucket-cloud:*' and  would help to bring the maturity of Bitbucket Cloud up to the level of Github's actions

### 〽️ Alternatives

Creating a new scaffolder module specific to Bitbucket Cloud actions:
- Similar to scaffolder-backend-module-yeoman or scaffolder-backend-module-rails
- Would make the plugin optional instead of bundling with the base scaffolder-backend

Reaching out to Atlassian to create this plugin for us
- May take much longer to be implemented

### ❌ Risks

Atlassian may want to take over / own the code base if they do start developing for backstage

New Bitbucket Cloud actions may be confused with existing publish:bitbucket-cloud action (Should all new actions start with bitbucket-cloud:* ? )

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by pjungermann** [comment]
FYI:
If you look at `builtin/publish/` you will see that all of them start with `publish:` there (`publish:github`, `publish:azure`, `publish:bitbucketCloud`). Even `publish:github:pull-request` or `publish:gitlab:merge-request`.

And then you see `builtin/github/` with actions all with prefix `github:`. Sort of, it is following the directory name as prefix.

**Comment by pjungermann** [comment]
> Atlassian may want to take over / own the code base if they do start developing for backstage

I don't think this is a real risk to be honest. They have a too big backlog and even drop topics considered important to the community.

Also, they follow their own strategy of integrating everything into their own UI and even work on a proprietary solution which has parts in common with Backstage.

**Comment by pjungermann** [comment]
PS: I also thought about ways to abstract that more so we could maintain this a bit easier. Need to order my thoughts still and write an RFC about that.

**Comment by pjungermann** [comment]
cool, looking forward to it! Feel free to tag me on the PR to provide a review.

**Comment by akundrock** [comment]
#14709 

Created the first scaffolder action with this PR. Basically, a copy of the publish:bitbucketCloud action with the added ability to enable pipelines upon repo creation. This creates a new folder to break out bitbucket-specific actions that i had asked about in this RFC.

Let me know if any changes should be made!

**Comment by akundrock** [comment]
Can we switch this from an "RFC" to a "plugin" tag?

I have learned a lot about the Backstage ecosystem in the last month and feel comfortable turning this into a claim on "plugin/scaffolder-backend-module-bitbucket-cloud".

I am willing to close this issue and open an official "Issue:Plugin" but I would be copying and pasting pretty much everything here.

It has become clear that a scaffolder-backend-module-bitbucket-cloud would be the most appropriate, and would be an optional include packaged with backstage (due to the use of OpenAPI spec plugin/bitbucket-cloud-common). Any additions from this new plugin may import new models from the OpenAPI spec, which may be difficult to coordinate from both an internal and external plugin.

I already have several scaffolder actions ready and can stage them once we figure out where it is most appropriate. I would prefer not to publish to NPM outside of Backstage.

Also thanks to @pjungermann for your continued support and comments!

**Comment by pjungermann** [comment]
> Can we switch this from an "RFC" to a "plugin" tag?
> [...]
> I am willing to close this issue and open an official "Issue:Plugin" but I would be copying and pasting pretty much everything here.

The "rfc" label was already removed. Let's just continue here :)

**Comment by pjungermann** [comment]
> Any additions from this new plugin may import new models from the OpenAPI spec, which may be difficult to coordinate from both an internal and external plugin.

Which difficulties do you see? I assume you refer to `plugins/bitbucket-cloud-common`, right?

It is meant to represent the Bitbucket Cloud API with its models. And I wanted to make it the single place which communicates with Bitbucket Cloud and remove all direct calls. This can provide more control for e.g. topics like rate limiting, etc.
It is not a full implementation of all API operations and models yet to keep the API surface minimal. (Breaking) changes to the spec might not impact what we use of it.
And it is relatively easy to add more if it is needed. Maybe documentation or anything else for DX can be improved though. Feedback welcome.

Just to add a bit more context.

Let me know where you see difficulties.

**Comment by pjungermann** [comment]
> It has become clear that a scaffolder-backend-module-bitbucket-cloud would be the most appropriate
> [...]
> once we figure out where it is most appropriate. I would prefer not to publish to NPM outside of Backstage.

I think I miss what is still unclear here ;-)

I would vouch for using `plugins/scaffolder-backend-module-bitbucket-cloud` to provide those scaffolder actions.

Feel free to share your considerations and concerns. I think we can clear that up and move forward :)

**Comment by victor-ribamar-verzel** [comment]
@akundrock could you help me? do u had any success on triggering a bitbucket pipeline with a template on backstage? if so, how?
