### ISSUE TITLE
Tech docs React syntax highlighting🚀 Feature: 

### ISSUE THREAD

**Issue by asotog** [backstage/backstage#14502]
### 🔖 Feature description

Able to highlight react code whether it is JSX or TSX extensions (typescript)

### 🎤 Context

Right now React is not highlighted properly even if I use readthedocs theme on the mkdocs.yaml file  https://mkdocs.readthedocs.io/en/latest/getting-started/ :

<img width="263" alt="image" src="https://user-images.githubusercontent.com/813023/200406508-c710a02d-3ed1-4293-ba05-455e91ec9aec.png">

### ✌️ Possible Implementation

As a docs maintainer I would like to be able to do like 

<img width="266" alt="image" src="https://user-images.githubusercontent.com/813023/200406962-98d27c30-9b4a-45d6-8714-bc20d35826f9.png">

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by maiagripp** [comment]
We are facing the same issue.

![image](https://github.com/backstage/backstage/assets/44818833/63f629b2-671f-4c41-bb80-999d949a32d5)
