### ISSUE TITLE
🚀 Feature: Restrict Catalog Import to only allow imports from an organization's internal repositories

### ISSUE THREAD

**Issue by jpdeburgo** [backstage/backstage#14520]
### 🔖 Feature description

This feature would allow catalog owners to restrict catalog imports, so the catalog import plugin only allows imports from an organization's internal repositories.

### 🎤 Context

Currently, any public GitHub repository can be imported into my organization's catalog. This would allow repos to be imported that are not under my organization's umbrella and don't receive the same level of scrutiny as our repositories do. 

- #13055 is a similar issue, but the suggested solution is not satisfactory for my organization.

### ✌️ Possible Implementation

Add an optional filter prop to the `CatalogImportPage`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Agreed, the safest thing is probably to make a policy, or a processor that does some checking in the preProcessEntity method and throws an exception, based on some regex rules or similar.

The best user experience would probably if we made sure to reject early as well. For example, when pasting a URL into the Create page, the result should ideally be an error message upfront. That might require adding rules to the location store as well, or possibly even doing it in a custom frontend.

**Comment by pjungermann** [comment]
@jpdeburgo I assume your PR was resolving this issue, right?

**Comment by jpdeburgo** [comment]
Yes! It has resolved this issue. Thank you! @pjungermann
