### ISSUE TITLE
🚀 Feature: Being able to search for entities on title AND name

### ISSUE THREAD

**Issue by alper98** [backstage/backstage#14530]
### 🔖 Feature description

Able to search for entities on their title (IF EXISTENT) AND their name.

### 🎤 Context

In my org, we have a use case for being able to search for entities based on either metadata.name OR metadata.title.

```    
backstage/plugins/catalog-backend/src/search/DefaultCatalogCollator.ts

return response.items.map((entity: Entity): CatalogEntityDocument => {
      return {
        title: entity.metadata.title ?? entity.metadata.name,
        location: this.applyArgsToFormat(this.locationTemplate, {
          namespace: entity.metadata.namespace || 'default',
          kind: entity.kind,
          name: entity.metadata.name,
        }),
        text: this.getDocumentText(entity),
        componentType: entity.spec?.type?.toString() || 'other',
        type: entity.spec?.type?.toString() || 'other',
        namespace: entity.metadata.namespace || 'default',
        kind: entity.kind,
        lifecycle: (entity.spec?.lifecycle as string) || '',
        owner: (entity.spec?.owner as string) || '',
        authorization: {
          resourceRef: stringifyEntityRef(entity),
        },
      };
    });
```

Currently, the indexing is NOT taking both into consideration, but uses a nullish coalescing operator to determine only one of them.

### ✌️ Possible Implementation

Adding both in their own? maybe some checks if either is null, but searching for name should not be dependent on the title, and vice versa. 
```    
backstage/plugins/catalog-backend/src/search/DefaultCatalogCollator.ts

return response.items.map((entity: Entity): CatalogEntityDocument => {
      return {
        name: entity.metadata.name,
        title: entity.metadata.title,
        location: this.applyArgsToFormat(this.locationTemplate, {
          namespace: entity.metadata.namespace || 'default',
          kind: entity.kind,
          name: entity.metadata.name,
        }),
        text: this.getDocumentText(entity),
        componentType: entity.spec?.type?.toString() || 'other',
        type: entity.spec?.type?.toString() || 'other',
        namespace: entity.metadata.namespace || 'default',
        kind: entity.kind,
        lifecycle: (entity.spec?.lifecycle as string) || '',
        owner: (entity.spec?.owner as string) || '',
        authorization: {
          resourceRef: stringifyEntityRef(entity),
        },
      };
    });
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by iamEAP** [comment]
Thanks for reporting @alper98!  We recently ran into a situation where things would have been easier with access to the `name` specifically too.

In Search, the `document.title` field is required while in the Catalog, the `entity.metadata.title` field is optional.  So if you (or anyone) want to implement, I'd recommend keeping the coalesce on the title, and just explicitly adding a `name` field that always reads from the name.

**Comment by iamEAP** [comment]
Hey everyone following along on this issue!  I'm consolidating this feature idea (as well as others) into a single issue.

I encourage you to continue the discussion (and perhaps, implementation? 😉) here: https://github.com/backstage/backstage/issues/14961
