### ISSUE TITLE
AuthenticationError: "alg" (Algorithm) Header Parameter not allowed stack

### ISSUE THREAD

**Issue by kumarnil** [backstage/backstage#14545]
### 📜 Description

When working on the permissions framework for backstage I’m seeing this error related to authentication. 

**Console Error:**
s://github.com/bitinn/node-fetch" type=incominaRequest
[1] 2022-11-08T14:41:12.827Z backstage error Request failed with 401 AuthenticationError type=errorHandler name=ResponseError response=[object Response] body=[object Object] cause=AuthenticationError: "alg"
(Algorithm) Header Parameter not allowed stack=ResponseError: Request failed with 401 AuthenticationError
[11
at Function. fromResponse(/Users/AAAAA/app-code/node_modules/@backstage/errors/dist/index.cjs.js:151:12

### 👍 Expected behavior

  Permission framework should work with 'RS256' algorithm.
 

### 👎 Actual Behavior with Screenshots

**Console Error:**
s://github.com/bitinn/node-fetch" type=incominaRequest
[1] 2022-11-08T14:41:12.827Z backstage error Request failed with 401 AuthenticationError type=errorHandler name=ResponseError response=[object Response] body=[object Object] cause=AuthenticationError: "alg"
(Algorithm) Header Parameter not allowed stack=ResponseError: Request failed with 401 AuthenticationError
[11
at Function. fromResponse(/Users/AAAAA/app-code/node_modules/@backstage/errors/dist/index.cjs.js:151:12

### 👟 Reproduction steps

1. Configure permission framework as per backstage docs https://backstage.io/docs/permissions/getting-started.
2. Start the server to run the app. It will  throw error.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by freben** [comment]
Our own token signatures only use `HS256`, intentionally. What's the use case here, do you know how it came to be that this alg was chosen? I'm looking through our own source code, and I only see any mentions of `RS256` in the internal needs for the OIDC and Cloudflare Access integrations and how they communicate with the outside world.

**Comment by kumarnil** [comment]
Looks like if I do not passing any algo value in the below code default value is 'ES256'.  When I tried to pass 'HS256' it is not throwing unauthorized error. Could you please suggest how to pass 'HS256' algo for the below code.

**app/backedn/index.ts**
identity = DefaultIdentityClient.create({
    discovery,
   });

**Comment by freben** [comment]
What is the underlying need here? I'd like to understand why it is that you are needing to change the alg, to better decide what's the best course of action.

`createRouter` for the auth backend has a `tokenFactoryAlgorithm` parameter that needs to match what the client here sends. But the thing is, the auth backend exposes the public parts of asymmetric keys by design, so symmetric algs aren't in scope in either case.

**Comment by dhoizner** [comment]
After having configured the application to sign in users using the Okta provider (following the [Auth and Identity](https://backstage.io/docs/auth/) docs), and the backend to authenticate incoming requests using the `tokenManager` (following the [Authenticate API Requests](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md?plain=1) docs), when making requests using the [FetchApi](https://github.com/backstage/backstage/tree/master/packages/core-app-api/src/apis/implementations/FetchApi) we are running into a similar issue, with the following `AuthenticationError`:
```
{
  "cause":{},
  "level":"error",
  "message":"Invalid server token; caused by TypeError: Key for the RS256 algorithm must be one of type KeyObject or CryptoKey. Received an instance of Buffer",
  "name":"AuthenticationError",
  "plugin":"app",
  "service":"backstage",
  "stack":"AuthenticationError: Invalid server token; caused by TypeError: Key for the RS256 algorithm must be one of type 
  KeyObject or CryptoKey. Received an instance of Buffer
    at ServerTokenManager.authenticate (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:3949:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async authMiddleware (/app/packages/backend/dist/index.cjs.js:195:11)",
  "type":"plugin"
}
```

The user is signed in successfully, and can be seen as signed in under `Backstage Identity` in the `Settings` page.

The frontend call to `/refresh` is successful, and the token that is received is passed on as the bearer token in the `authorization` header.

When decoded, the JWT contents that are passed to the frontend from the `/refresh` route and subsequently passed on via the `authorization` header are the following:
```
[{"iss"=>"http://<FQDN_HERE>/api/auth",
  "sub"=>"user:default/dan.hoizner",
  "ent"=>["user:default/dan.hoizner"],
  "aud"=>"backstage",
  "iat"=>1670970458,
  "exp"=>1670974058},
 {"alg"=>"ES256", "kid"=>"<KID_HERE>"}
```
It seems like the algorithm included in the JWT headers does not match the one specified in the documentation (HS256), is there some additional configuration that needs to happen or documentation that we should be referencing to resolve this?

Thank you!

**Comment by Rugvip** [comment]
@dhoizner do you have this snippet as it appears in the contrib docs?

```ts
try {
  req.user = await appEnv.identity.getIdentity({ request: req });
} catch {
  await appEnv.tokenManager.authenticate(token);
}
```

The server and user identity tokens currently aren't interchangeable, so you need the fallback.

Now if you have that setup you'll want to dig into the error that makes the user auth fail, for example temporarily adding this:

```ts
try {
  req.user = await appEnv.identity.getIdentity({ request: req });
} catch (error) {
  console.error('user auth error', error);
  await appEnv.tokenManager.authenticate(token);
}
```

**Comment by kumarnil** [comment]
I tried to setup permission framework again. However getting the below 401 AuthenticationError.

**Reproduce the issue**
1. Configure permission framework as per backstage docs https://backstage.io/docs/permissions/getting-started.
2. Start the server to run the app.  App started and I can see settings page with all user profile details info.
3. When try to click  on catalog or docs or template page it throw the below errors.

Browser Console Error-  
{"error":{"name":"AuthenticationError","message":"no applicable key found in the JSON Web Key Set","stack":"AuthenticationError: no applicable key found in the JSON Web Key Set\n    at DefaultIdentityClient.getIdentity (/Users/User_Name/Work/node_modules/@backstage/plugin-auth-node/dist/index.cjs.js:36:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /Users/User_Name/Work/node_modules/@backstage/plugin-permission-backend/dist/index.cjs.js:152:20"},"request":{"method":"POST","url":"/authorize"},"response":{"statusCode":401}}


Server Console Error- 
backstage error Request failed with 401 AuthenticationError type=errorHandler name=ResponseError response=[object Response] body=[object Object] cause=AuthenticationError: no applicable key found in the JSON Web Key Set stack=ResponseError: Request failed with 401 AuthenticationError

**Comment by seppo0010** [comment]
Hello, everyone. I've been debugging a similar problem and found a solution, but it might not be the same one.

In my case, I wanted to get the user identity from a backend plugin. I followed the [Authenticate API requests](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md) guide and it was working fine on my dev machine, but failing in production with an exception similar to the one in this issue.

It took me some time to realize the first problem: I was getting an error as an exception in `getIdentity`, which was caught and then handled, incorrectly, by `tokenManager.authenticate`, as it was a user token. At that point, I was getting this message:
```
AuthenticationError: Invalid server token; caused by TypeError: Key for the RS256 algorithm must be one of type 
  KeyObject or CryptoKey. Received an instance of Buffer
```

**Comment by seppo0010** [comment]
Hello, everyone. I've been debugging a similar problem and found a solution, but it might not be the same one.

In my case, I wanted to get the user identity from a backend plugin. I followed the [Authenticate API requests](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md) guide and it was working fine on my dev machine, but failing in production with an exception similar to the one in this issue.

It took me some time to realize the first problem: I was getting an error as an exception in `getIdentity`, which was caught and then handled, incorrectly, by `tokenManager.authenticate`, as it was a user token. At that point, I was getting this message:

```
AuthenticationError: Invalid server token; caused by TypeError: Key for the RS256 algorithm must be one of type 
  KeyObject or CryptoKey. Received an instance of Buffer
```

Then, following the discussion on this thread, I got the exception that was incorrectly caught, and found out it was an `Invalid URL`. Huh? What URL? After some debugging (and having my national team win the world cup), I fixed it with this change:

```
diff --git a/app-config.production.yaml b/app-config.production.yaml
index 98c062e..c78ddc5 100644
--- a/app-config.production.yaml
+++ b/app-config.production.yaml
@@ -12,7 +12,8 @@ backend:

   # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
   # all interfaces, the most permissive setting. The right value depends on your specific deployment.
-  listen: ':7007'
+  listen:
+    port: 7007
```

Not sure if this is useful for OP, but it might help someone else that finds this issue.

**Comment by kumarnil** [comment]
> Rugvip

Could you please assist me on this issue? Due to this issue I am not able to configure permission framework in my app.

**Comment by dhoizner** [comment]
> @dhoizner do you have this snippet as it appears in the contrib docs?
> 
> ```ts
> try {
>   req.user = await appEnv.identity.getIdentity({ request: req });
> } catch {
>   await appEnv.tokenManager.authenticate(token);
> }
> ```
> 
> The server and user identity tokens currently aren't interchangeable, so you need the fallback.
> 
> Now if you have that setup you'll want to dig into the error that makes the user auth fail, for example temporarily adding this:
> 
> ```ts
> try {
>   req.user = await appEnv.identity.getIdentity({ request: req });
> } catch (error) {
>   console.error('user auth error', error);
>   await appEnv.tokenManager.authenticate(token);
> }
> ```

Sorry for the late reply, it turns out that something in our network stack might have been mucking with the `authorization` header. Once we removed the infra-layer oauth flow, things started working again.

Thanks for looking into it 😄 .
