### ISSUE TITLE
🐛 Bug Report: Install Docs out of date - npm LTS is now 18

### ISSUE THREAD

**Issue by dgiacomo** [backstage/backstage#14541]
### 📜 Description

On 2022-10-25 npm version 18 became the new LTS version. Yarn expects either 14 or 16.  https://github.com/nodejs/release#release-schedule

Aspiration of the project seems to be to keep on pace with the latest npm LTS release, but it is slightly behind. `The engine "node" is incompatible with this module. Expected version "14 || 16". Got "18.12.1"`

I couldn't find any other issues referencing this and wonder if this is the first major switch over of this sort. Should the docs be updated to call out targeting 16 for now or is work in play to move to 18? I'm guessing this can be painful as it might impact installations that are currently out there.

My intent of filing this was to get a place holder started that others could look at to get a sense of what to expect / foster discussion and see if the docs need temporary updates. If there is discussion outside of Github or if it missed it, my apologies. 

It's pretty easy to see what the issue is and switch to 16, but surfacing the larger challenge of intent to switch to new LTS is what I was hoping to ask about since I couldn't find anything on quick search.

### 👍 Expected behavior

Followed docs:
``
nvm install --lts
npm install --global yarn
npx @backstage/create-app
``
NPM 18 installed - hit error that 14 or 16 is required.  Expected app creation to succeed.

Docs could be updated with version 16 (replacing references like `nvm install --lts`) or a link could be added to refer to an Issue documenting work in progress to upgrade the accepted versions of Node 

### 👎 Actual Behavior with Screenshots

Followed docs for creating app:
``
nvm install --lts
npm install --global yarn
npx @backstage/create-app
``
Got this errror:
``
  executing     yarn install ◝ error root@1.0.0: The engine "node" is incompatible with this module. Expected version "14 || 16". Got "18.12.1"
error Found incompatible module.
``

### 👟 Reproduction steps

``
nvm install --lts
npm install --global yarn
npx @backstage/create-app
``

### 📃 Provide the context for the Bug.

``
nvm install --lts
npm install --global yarn
npx @backstage/create-app
``

### 🖥️ Your Environment

OSX
NVM: 16.18.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
For reference here's the PR that started this back in July: https://github.com/backstage/backstage/pull/12558

**Comment by awanlin** [comment]
You're welcome. The live version of the Release & Versioning Policy is here: https://backstage.io/docs/overview/versioning-policy
