### ISSUE TITLE
New Snyk vulnerability that originated from backstage/cli latest version

### ISSUE THREAD

**Issue by PutuPhoton** [backstage/backstage#14562]
### 📜 Description

There is new vulnerability that is reported by Snyk when scanning backstage based organization repo. Below is the detailed path from latest backstage/cli package:

Introduced through: app@0.0.0 › @backstage/cli@0.20.0 › react-dev-utils@12.0.0 › loader-utils@3.2.0
Fix: No remediation path available.
Introduced through: app@0.0.0 › @backstage/cli@0.20.0 › @sucrase/webpack-loader@2.0.0 › loader-utils@1.4.1
Fix: No remediation path available.
Introduced through: app@0.0.0 › @backstage/cli@0.20.0 › yml-loader@2.1.0 › loader-utils@1.4.1
Fix: No remediation path available.
Introduced through: app@0.0.0 › @backstage/cli@0.20.0 › @pmmmwh/react-refresh-webpack-plugin@0.5.8 › loader-utils@2.0.3
Fix: No remediation path available.
Introduced through: app@0.0.0 › @backstage/cli@0.20.0 › esbuild-loader@2.18.0 › loader-utils@2.0.3
Fix: No remediation path available.
Introduced through: app@0.0.0 › @backstage/cli@0.20.0 › rollup-plugin-postcss@4.0.2 › postcss-modules@4.3.0 › generic-names@4.0.0 › loader-utils@3.2.0
Fix: No remediation path available.

### 👍 Expected behavior

The latest version of backstage/cli should not have any vulnerability reported by Snyk. 

### 👎 Actual Behavior with Screenshots

Detail information about vulnerability reported: https://security.snyk.io/vuln/SNYK-JS-LOADERUTILS-3105943

### 👟 Reproduction steps

Scan repo with Snyk app

### 🖥️ Your Environment

OS:   Darwin 21.4.0 - darwin/x64
node: v16.14.2
yarn: 1.19.0
cli:  0.20.0 (installed)
backstage:  1.3.1

Dependencies:
  @backstage/app-defaults              1.0.6, 1.0.7
  @backstage/backend-common            0.15.1, 0.15.2
  @backstage/backend-plugin-api        0.1.3
  @backstage/backend-tasks             0.3.6
  @backstage/catalog-client            1.0.3, 1.1.0, 1.1.1
  @backstage/catalog-model             1.0.3, 1.1.2
  @backstage/cli-common                0.1.10
  @backstage/cli                       0.20.0
  @backstage/config-loader             1.1.5
  @backstage/config                    0.1.15, 1.0.1, 1.0.3
  @backstage/core-api                  0.2.23
  @backstage/core-app-api              1.0.3, 1.1.1, 1.1.0
  @backstage/core-components           0.11.2, 0.9.5
  @backstage/core-plugin-api           0.1.13, 1.0.6, 1.0.7
  @backstage/core                      0.7.14
  @backstage/dev-utils                 1.0.7
  @backstage/errors                    0.1.5, 1.1.2
  @backstage/integration-react         1.1.1, 1.1.5, 1.1.4
  @backstage/integration               1.3.1, 1.3.2
  @backstage/plugin-api-docs           0.8.9
  @backstage/plugin-app-backend        0.3.36
  @backstage/plugin-auth-backend       0.16.0
  @backstage/plugin-auth-node          0.2.5, 0.2.6
  @backstage/plugin-badges             0.2.30
  @backstage/plugin-catalog-backend    1.4.0, 1.5.0
  @backstage/plugin-catalog-common     1.0.6, 1.0.7
  @backstage/plugin-catalog-graph      0.2.18
  @backstage/plugin-catalog-import     0.8.12
  @backstage/plugin-catalog-node       1.2.0
  @backstage/plugin-catalog-react      1.1.4, 1.2.0
  @backstage/plugin-catalog            1.3.0, 1.5.1
  @backstage/plugin-org                0.5.6
  @backstage/plugin-permission-common  0.6.2, 0.6.4, 0.7.0
  @backstage/plugin-permission-node    0.6.5, 0.7.0
  @backstage/plugin-permission-react   0.4.6
  @backstage/plugin-scaffolder-backend 1.7.0
  @backstage/plugin-scaffolder-common  1.2.1
  @backstage/plugin-scaffolder         1.6.0
  @backstage/plugin-search-common      0.3.5, 1.1.0
  @backstage/plugin-search-react       0.2.1, 1.1.0
  @backstage/plugin-search             0.9.0
  @backstage/plugin-tech-radar         0.5.13
  @backstage/plugin-techdocs-react     1.0.4
  @backstage/plugin-techdocs           1.3.2
  @backstage/plugin-user-settings      0.4.5
  @backstage/release-manifests         0.0.6
  @backstage/test-utils                1.1.1, 1.2.1
  @backstage/theme                     0.2.15, 0.2.16
  @backstage/types                     0.1.3, 1.0.0
  @backstage/version-bridge            0.1.2, 1.0.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
Thank you for reporting! We'll likely be ignoring this one as it's a ReDoS vulnerability in build tooling, so not really a big issue. We're a bit blocked by issues with the Snyk CLI at the minute though.

**Comment by Rugvip** [comment]
Fixed by #14646, even if it has pretty slim impact it's a simple bump and I encourage anyone to bump their local dependencies as well.
