### ISSUE TITLE
🐛 Bug Report: Isolated API Report builds cause different results

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#14578]
### 📜 Description

Build API reports for the `scaffolder-backend` in isolation produces a different API report than the on you get when generating all API reports in the entire project.

### 👍 Expected behavior

Be able to run the following without causing changes in master:

```bash
yarn build:api-reports:only plugins/scaffolder-backend
```

### 👎 Actual Behavior with Screenshots

The following change is made when building the report in isolation:

```diff
-  commitAction?: 'update' | 'create' | 'delete' | undefined;
+  commitAction?: 'update' | 'delete' | 'create' | undefined;
```

### 👟 Reproduction steps

Run `yarn build:api-reports:only plugins/scaffolder-backend` in a clean repo, it should not cause any changes.

### 📃 Provide the context for the Bug.

Discovered in #13817

We've had situations before where the difference in the packages that are part of the TypeScript compilation will cause various differences. For example, we make sure to always include [`packages/cli/asset-types/asset-types.d.ts`](https://github.com/backstage/backstage/blob/a750071c8b5d8e7aabe98c2e6db60b2cc34c2159/scripts/api-extractor.ts#L279).

This case seems different though, since it's just a union being reordered.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by kuangp** [comment]
I've also noticed this too in other plugins which ends up failing the PR check and forces me to run the full report in order to make the CI happy 😛
