### ISSUE TITLE
🚀 Feature: Allow for extensions to `backstage-cli new`

### ISSUE THREAD

**Issue by Pike** [backstage/backstage#14585]
### 🔖 Feature description

The templates in https://github.com/backstage/backstage/tree/master/packages/cli/src/lib/new/factories are great, but it'd also be nice for CLIs in instances to extend that with their own code templates.

### 🎤 Context

Ideas I'd like to experiment with in terms of template creation would be:

* combo of backend, frontend, common, all on the same feature, already with deps between FE and BE to common.
* new-backend style template for a not-backstage-but-backstage server

### ✌️ Possible Implementation

Add an API to https://github.com/backstage/backstage/blob/master/packages/cli/src/lib/new/FactoryRegistry.ts to allow additions to the `factoryMap`.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
Yep totally, it's somewhat build with that future extension in mind. 👍 I think a reasonable pattern might be to have some form of library exported from the CLI that can be used to make factories, and then you'd have internal packages that you point to for the extensions? It'd be important for those to both be implemented in TypeScript and at the same time be executable from source.

**Comment by Pike** [comment]
Alternatively, we could look at how hard it is to enable a CLI for one's own version of backstage, based on the upstream one.

So more of a composability approach than extensibility?

**Comment by andrewthauer** [comment]
> So more of a composability approach than extensibility?

We are doing something round about like composing over the `techdocs-cli` ([see discussion](https://github.com/backstage/backstage/discussions/14567#discussioncomment-4221823))

I wouldn't say it's an elegant or easily re-usable solution atm though. However, it does seem to work well. I'd +1 having some pattern/support for composing and/or doing pre/post hooks for both the `backstage-cli` & `techdocs-cli`.
