### ISSUE TITLE
🚀 Feature: Search ResultListItems as Plugin Extensions

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#14603]
### 🔖 Feature description

Search Result List Item components should be plugin extensions that App Integrators register in the location(s) where search results are rendered.  This would reduce the API surface area that App Integrators would have to be aware of and keep up-to-date with, while maintaining the same level of flexibility.

### 🎤 Context

There are three parties involved in creating the experience of displaying search results.  They, and their responsibilities, are roughly as follows:

- **Search Platform Developer**: Provides information required to render a search result item (e.g. highlights, rank, and other metadata)
- **Other Plugin Developer**: Provides a component that takes in search result metadata and displays it appropriately
- **App Integrator**: Provides logic on which component to use when rendering specific results, and passes result metadata into the component.

This is problematic in situations where _new_ functionality is introduced by plugin developers (for Search or otherwise), because the App Integrator is then required to update integration code to take advantage of this new functionality (e.g. passing through new, optional props like `rank` or `highlight`).

Ideally, an App Integrator would only be responsible for choosing _which_ components can be used to render specific results, and the rest would be taken care of by the Search Platform.  e.g.

```tsx
<SearchResults>
  <CatalogSearchResultListItem />
  <TechDocsSearchResultListItem lineClamp={2} />
  <DefaultResultListItem />
</SearchResults>
```

### ✌️ Possible Implementation

A prior attempt at this can be found here: https://github.com/backstage/backstage/pull/10151.  Additional thinking can be found here:

With Search Result List Items as extensions, we (as the Search Platform) should be able to take responsibility for firing `discover` events when result items are clicked, rather than relying on Plugin Developers to implement that instrumentation themselves.  Wrapping rendered result items in a component that has an `onClickCapture` handler would be a promising approach.  Some sketching on that can be found here: https://codesandbox.io/s/elated-flower-tlk8qd?file=/packages/app/src/App.tsx

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Sounds splendid! 👍

**Comment by iamEAP** [comment]
Just linking https://github.com/backstage/backstage/issues/13723 (making result list items plugin extensions would help reduce the type of linked type issue)

**Comment by iamEAP** [comment]
Just noting that this would also skirt around type issues that commonly crop up, such as https://github.com/backstage/backstage/issues/13723.
