### ISSUE TITLE
🙏 [Help Wanted] Clean up deprecations

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#14602]
The Backstage CLI providers the `repo list-deprecations` command to list all usages of deprecated symbols. We have a lot of these in the main repo, and would like to clean them up. I think this is a good first issue for anyone that wants to get involved in the project and help out.

## Steps

1. Run the following command in the project root:

```bash
yarn backstage-cli repo list-deprecations
```

2. You will not get a long list of deprecated usages, looking something like this:

```log
...
packages/backend-common/src/reading/index.ts:19:10 - 'BitbucketUrlReader' is deprecated. in favor of BitbucketCloudUrlReader and BitbucketServerUrlReader
packages/backend-common/src/reading/index.ts:19:10 - 'BitbucketUrlReader' is deprecated. in favor of BitbucketCloudUrlReader and BitbucketServerUrlReader
...
```

3. Pick a couple of related deprecations to fix, not too many at once, but be sure to for example fix all deprecations in a single file at the same time. Generally the deprecation message should provide guidance for how to migrate. If that's not the case, please chime in this issue so that we can help clarify an perhaps improve the deprecation message. Note that the deprecated symbols themselves should not be removed, we don't want to change the API surface at this stage.

**Comment by Kd-Here** [comment]
Hello Rugvip I wanted to learn contribute opensource!
I will try to learn and make reserach for it.
Can you help me with this. It's my first contribution to real life project

**Comment by Rugvip** [comment]
@Kd-Here of course! You can find our documentation for how to get started as a contributor over [here](https://backstage.io/docs/getting-started/contributors), and more general contribution docs over [here](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md). Let me know if there's anything specific. 👍

**Comment by Znarvl** [comment]
Hello! I also would like to contribute to this issue! Is it possible to split it into categories based on what folder the deprecation is in (for example taking all backend-common)? Or do you want all deprecation complete in one PR?

**Comment by Znarvl** [comment]
Another question: Are you supposed to fix deprecations in deprecated files? For example BitBucketUrlReader is not used anymore because of BitBucketCloudReader. In the BitBucketUrlReader test one should use instead BitBucketCloudReader which kinda defeats its purpose. Should you fix the deprecation or just straight up delete the file because it is not used anymore?

**Comment by Kd-Here** [comment]
> @Kd-Here of course! You can find our documentation for how to get started as a contributor over [here](https://backstage.io/docs/getting-started/contributors), and more general contribution docs over [here](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md). Let me know if there's anything specific. 👍

Hey Rugvip thanks for your kind help.
After reading from backstage docs I found I am too noob for such great project.
I tried my best to install backstage but still could not do. I would love to contribute with you is there something begineer task for CS student.

**Comment by akundrock** [comment]
There are quite a few deprecations that show up using that command. Using `yarn backstage-cli repo list-deprecations | wc -l 783`

I would like to point out one in particular though. The auth provider for Auth0 is no longer in the code base. It is still shown in the microsite here: https://backstage.io/docs/auth/auth0/provider but the 'auth0AuthApi' export no longer exists and is documented as deprecated almost a year ago: https://backstage.io/docs/api/deprecations#generic-auth-api-refs

I have not been able to use the example code correctly though. Wondering how we can handle the microsite side of things (just link to the deprecation page for Auth0 as a provider?)

**Comment by Rugvip** [comment]
> Is it possible to split it into categories based on what folder the deprecation is in (for example taking all backend-common)? Or do you want all deprecation complete in one PR?

Definitely not all deprecations in a single PR, there's way too many! Anything else goes though, but if there's a particularly tricky one it can be best to send a small PR for just that individual one, and perhaps highlight the ongoing work here.

> The auth provider for Auth0 is no longer in the code base.

Indeed! That entire documentation section can probably be removed, just gotta double check if something needs to be moved over to https://backstage.io/docs/auth/oidc. It's a bit outside the scope of this issue though perhaps, but happy if you want to help out with that!

> I would love to contribute with you is there something begineer task for CS student.

Don't give up trying to set the project up! You can also try smaller, simpler projects from scratch, like setting one up a separate instance with `npx @backstage/create-app`, or just a plain React app with `npx create-react-app`. If you encounter errors you can try to figure out the cause through Google or search Stackoverflow. Give it a bit of time before you ask for help, CS is often about bashing your head against the same problems for hours on end before you figure things out. I'd also recommend watching video tutorials that guide you through the complete project setups, or blog posts if you prefer written content.

**Comment by Znarvl** [comment]
@Rugvip Cool, I'll send in a PR with the work I've done today or tomorrow. I've been working top down ignoring some of the deprecations that did not provide an alternative solution

**Comment by Znarvl** [comment]
I've created a PR now, it is the first time I'm creating a PR contributing to backstage so it might be a bit of a mess. But I've understood the guidelines now.

@Rugvip Do you want me to continue push updates to the PR or should it be reviewed? I've only done about 10 out of the many listings so there are a lot more to be done.

Some comments I have trying to migrate is that like I stated previously, should deprecated files be left alone without migrating? 
For example changing the BitBuckerURLReader tests to BitbucketCloudUrlReader is not that productive.
```
packages/backend-common/src/reading/BitbucketUrlReader.test.ts:60:20 - 'BitbucketUrlReader' is deprecated. in favor of BitbucketCloudUrlReader and BitbucketServerUrlReader
```

Also, there are a lot of deprecations that has no migrating solution. For example 
```
packages/core-app-api/src/app/AppThemeProvider.tsx:61:16 - 'addListener' is deprecated. 
```
Should they just be ignored?

**Comment by Rugvip** [comment]
@Znarvl thank you, and no worries!

It's best to leave the existing PR for review. If you want to continue with more fixes then it's best to ship that in a separate PR. Otherwise there's a risk that the PR gets stuck in never ending review.

Yep any code that is directly related to a deprecated symbol can be left alone, such as the `BitBuckerURLReader` example.

I believe there's a migration solution for `addListener`, just that it's not documented as part of the deprecation (it's not ours :grin:). If it's unclear what to do then I'd say go ahead and skip. In this case I believe it needs to be migrated to `addEventListener`.

**Comment by Znarvl** [comment]
Alright thanks for the answer! I'll fix the PR then and continue working on other deprecations

**Comment by vorbrodt** [comment]
I will be working on fixing the deprecations in the `packages/core-components/src/layout/` directory.

**Comment by casje896** [comment]
Hi! I also want to help, I will work in `plugins/catalog-backend` directory.

**Comment by kurtaking** [comment]
I will help out, starting with `plugins/cost-insights`.

**Comment by kurtaking** [comment]
@Znarvl please continue! I only have one commit with 6 files changed.

**Comment by Rugvip** [comment]
Big thank you to everyone that has been helping out so far! 🚀 

I wanted to highlight something that's been a somewhat common confusion, which is that we don't want to remove the deprecated symbols themselves, including any re-exports of them and so on. There are also cases where a deprecated symbol depends on another deprecated symbol, in which case there's no need to change the usage. The main guideline here is that we don't want the public API of any of the packages to change at this point. When running `yarn build:api-reports` there should be no changes to any of the `api-report.md` files.
