### ISSUE TITLE
🐛 Bug Report: Scaffolding Backstage with yarn 3.2.4 does not work

### ISSUE THREAD

**Issue by robdodson** [backstage/backstage#14622]
### 📜 Description

I did not have yarn installed on my machine, so I followed the [yarn installation instructions](https://yarnpkg.com/getting-started/install#updating-the-global-yarn-version) which recommend getting the latest stable version, which was 3.2.4 in my case.

When I tried to scaffold Backstage with `npx @backstage/create-app` I would get an error saying `Error: Could not execute command yarn install`

The workaround was to downgrade to yarn 1.22.19

### 👍 Expected behavior

Installation would work

### 👎 Actual Behavior with Screenshots

The terminal says `Error: Could not execute command yarn install`

### 👟 Reproduction steps

1. Install yarn 3.2.4 or great
2. Run npx @backstage/create-app

### 🖥️ Your Environment

- Apple M1 Pro, macOs Monterey
- node 16.18.1
- yarn 3.2.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by robdodson** [comment]
I forgot to mention — I think it's totally fine for the project to not support yarn 3, but it might be worth stating which version of yarn should be used in the docs. I was following [this guide](https://backstage.io/docs/getting-started/).

**Comment by freben** [comment]
Oh we do support yarn 3 for sure, I am personally on 3.2.3 and also on an M1 mac. Now I'm wondering if just 3.2.4 is problematic or if there's something else amiss in your env. I saw that you [posted a gist](https://gist.github.com/robdodson/7adc367df943cae28af57fb7b71cbb30) with some output but it seems to be incomplete; was there no more information at the end of that?

**Comment by robdodson** [comment]
oh I don't have the output anymore but after listing the missing dependencies it just says `Error: Could not execute command yarn install`

**Comment by Rugvip** [comment]
Projects can be migrated to Yarn 3, but the template itself only supports Yarn classic at the moment. If can update the template, but for now I'm just suggesting this clarification in the docs: #14683
