### ISSUE TITLE
🔌 Plugin: Azure Spring Apps Enterprise

### ISSUE THREAD

**Issue by ch-enfuse** [backstage/backstage#14623]
### 🔖 Summary

Plugin is aimed for users hosting their Spring applications on Azure Spring Apps Enterprise service. The plugin will collect general information about different components the service offers, statuses and logs from applications hosted on the service

Current working functionality:
-
- List available Tanzu Builders in the service. Along with the supported languages from each builder.

Potential features:
-
- List applications instances running on the service. Along with configuration information.
- View logs from individual applications
- View information about Configuration Service (settings, bindings)

### 🌐 Project website (if applicable)

https://github.com/enfuse/asae-backstage-plugin

### ✌️ Context

We, at Enfuse.io, use Azure Spring Apps Enterprise (ASAE) to create spring application workflows that can be developed and provisioned fast using the service's built in Spring components. 

The plugin will help anyone hosting their applications on ASAE to view information about their service components. 

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
🎉 , seeing as this plugin already exists, I suggest you simply [add it to the marketplace](https://backstage.io/docs/plugins/add-to-marketplace) 😁

**Comment by ch-enfuse** [comment]
@Rugvip [just created a PR for it](https://github.com/backstage/backstage/pull/14744)!

**Comment by ch-enfuse** [comment]
@Rugvip I created a new [ PR](https://github.com/backstage/backstage/pull/14791) to get the correct image displayed in the marketplace page. :)

**Comment by freben** [comment]
added!
