### ISSUE TITLE
🚀 Feature: Button helps in navigating to proper kind at the end of each catalog-import 

### ISSUE THREAD

**Issue by skgandikota** [backstage/backstage#14633]
### 🔖 Feature description

I have personally created a button which helps in navigating to the right kind after  import.  Say If I import single component then I can navigate to component by name similar as show below . While importing too many component I hided the button and left user to click on the entity and navigate 

![image](https://user-images.githubusercontent.com/24265936/201905255-c1937210-82a0-4b45-8c82-929624817fa5.png)

### 🎤 Context

catalog-import 

### ✌️ Possible Implementation

Yes !  I can implement and its very simple and straight forward 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Could you elaborate a little bit more? Not quite following

If you already have the change ready to go then you could open up a draft PR too if that's easier

**Comment by skgandikota** [comment]
Sure ! Will raise a pr and share it here
