### ISSUE TITLE
🐛 Bug Report: AbortController is not defined

### ISSUE THREAD

**Issue by testn** [backstage/backstage#14647]
### 📜 Description

After bump the version from 1.7.2 to 1.8.0 and I try to do version bump again, I get this

```
$ yarn backstage-cli versions:bump
yarn run v1.22.17
$ ............./.bin/backstage-cli versions:bump
Using default pattern glob @backstage/*

ReferenceError: AbortController is not defined
```

### 👍 Expected behavior

It should work fine

### 👎 Actual Behavior with Screenshots

```
Using default pattern glob @backstage/*

ReferenceError: AbortController is not defined

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### 👟 Reproduction steps

Just do 

```yarn backstage-cli versions:bump```

on backstage 1.8.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by testn** [comment]
It seems to generate this error only if yarn is executed on node@14. If it is running on node@16, it would be fine. I guess that we need to perform some check whether yarn is running on the right version of node

**Comment by Rugvip** [comment]
Yep, we not longer support Node.js 14, only 16 and 18 since the 1.8 release. You can find more information in the [versioning policy](https://backstage.io/docs/overview/versioning-policy#nodejs-releases).

**Comment by Rugvip** [comment]
Gonna close this, please upgrade to Node.js 16 or 18, and I also recommend you set the `engines` field locally in your root `package.json` as well.
