### ISSUE TITLE
🚀 Feature: Links redirect when a .md filename changes 

### ISSUE THREAD

**Issue by anilazaidi** [backstage/backstage#14644]
### 🔖 Feature description

When a .md filename changes, URLs from the old filename to the new are redirected automatically.

### 🎤 Context

_Current UX:_
When a .md filename changes, links from the old filename or new aren't redirected automatically. For example, in Google Drive when you change the title of a doc, the link remains consistent b/c the file URL uses ids rather than the file/page name. For example:

```
https://docs.google.com/document/d/1tuvazWr5m1A9uwDAcUUy9fsLhT_9wf6e8
```

Backstage URLs use folders and filenames from a repo, so links aren't redirected automatically when either one changes :/ 
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/52043997/201982223-7c758601-0fc8-45f0-b170-fb974cb8eeed.png">

### ✌️ Possible Implementation

_Proposals_
- Use IDs in URLs like Google Drive
- Offer link redirects as a plugin

_Not ideal solution_
From experience, asking software owners to manage link redirect files (e.g., [mkdocs-redirects](https://github.com/mkdocs/mkdocs-redirects)) isn't the most ideal solution either b/c of maintenance. Also, the file can become **extremely** long if you have to change the information architecture for a set of docs.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by andrewthauer** [comment]
We ended up building a simple but more general purpose redirect system into our Backstage instance that is based on a yaml file. Would there be a appetite for up streaming this as a plugin? It was  inspired by this comment https://github.com/backstage/backstage/pull/14730#issuecomment-1332088299.
