### ISSUE TITLE
🐛 Bug Report: Failed to create app

### ISSUE THREAD

**Issue by pkruk** [backstage/backstage#14661]
### 📜 Description

I'm following tutorial and npx @backstage/create-app fails on yarn txc

### 👍 Expected behavior

It should pass without any problems.

### 👎 Actual Behavior with Screenshots

```
yarn run v1.22.19
$ tsc
packages/backend/src/plugins/catalog.ts:9:47 - error TS2345: Argument of type 'PluginEnvironment' is not assignable to parameter of type 'CatalogEnvironment'.
  The types of 'reader.readUrl' are incompatible between these types.
    Type '((url: string, options?: ReadUrlOptions | undefined) => Promise<ReadUrlResponse>) | undefined' is not assignable to type '(url: string, options?: ReadUrlOptions | undefined) => Promise<ReadUrlResponse>'.
      Type 'undefined' is not assignable to type '(url: string, options?: ReadUrlOptions | undefined) => Promise<ReadUrlResponse>'.

9   const builder = await CatalogBuilder.create(env);
                                                ~~~

packages/backend/src/plugins/scaffolder.ts:17:5 - error TS2322: Type 'import("/Users/piotrkruk/paas/backstage/packages/backend/node_modules/@backstage/backend-common/dist/index").UrlReader' is not assignable to type 'import("/Users/piotrkruk/paas/backstage/node_modules/@backstage/backend-common/dist/index").UrlReader'.

17     reader: env.reader,
       ~~~~~~

  node_modules/@backstage/plugin-scaffolder-backend/dist/index.d.ts:730:5
    730     reader: UrlReader;
            ~~~~~~
    The expected type comes from property 'reader' which is declared here on type 'RouterOptions'

packages/backend/src/plugins/techdocs.ts:18:5 - error TS2322: Type 'import("/Users/piotrkruk/paas/backstage/packages/backend/node_modules/@backstage/backend-common/dist/index").UrlReader' is not assignable to type 'import("/Users/piotrkruk/paas/backstage/node_modules/@backstage/backend-common/dist/index").UrlReader'.

18     reader: env.reader,
       ~~~~~~

  node_modules/@backstage/plugin-techdocs-node/dist/index.d.ts:22:5
    22     reader: UrlReader;
           ~~~~~~
    The expected type comes from property 'reader' which is declared here on type 'PreparerConfig'


Found 3 errors in 3 files.

Errors  Files
     1  packages/backend/src/plugins/catalog.ts:9
     1  packages/backend/src/plugins/scaffolder.ts:17
     1  packages/backend/src/plugins/techdocs.ts:18
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  executing     yarn tsc ✖ 

Error: Could not execute command yarn tsc

It seems that something went wrong when creating the app 🤔

🔥  Failed to create app!

```

### 👟 Reproduction steps

Simple run of npx @backstage/create-app

### 🖥️ Your Environment

MacOS intel processor.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
I'm not able to reproduce this in a new app. It could be that you end up with an older template, does creating the app with `npx @backstage/create-app@latest` solve the issue?

**Comment by sabre1041** [comment]
@Rugvip @pkruk i too ran into this issue. i was on node `v16.18.0` and ran into the same failures

Updated to `v18.12.1` and command ran successfully

**Comment by pkruk** [comment]
I use a :
```
➜  /tmp yarn --version
1.22.19
➜  /tmp node --version
v16.18.0
➜  /tmp
```
in tutorial node 16 is recommended, when I try the v18.12.1 then I got this error:
`  executing     yarn install ◞ error root@1.0.0: The engine "node" is incompatible with this module. Expected version "14 || 16". Got "18.12.1"`

**Comment by Rugvip** [comment]
@pkruk the most recent template points to `"16 || 18"`, so that'd definitely be an older version of the template.

When trying to reproduce I was running `v16.14.2`

**Comment by pkruk** [comment]
you're right, my fault. Thanks and sorry for hassle ;)!
