### ISSUE TITLE
🐛 Bug Report: pg search indexer leaking transactions

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#14666]
### 📜 Description

Periodically we can see that the pg indexer leaking transactions. When this occurs we can see the following error in the logs:

Cannot read properties of undefined (reading 'rollback')

### 👍 Expected behavior

It should not leak transactions.

### 👎 Actual Behavior with Screenshots

Transactions accumulate in the database until it runs out of connections.

### 👟 Reproduction steps

1. Create a custom indexer
2. add a little sleep to the initializer
3. configure a collator with nothing to index
4. start up backstage

### 📃 Provide the context for the Bug.

This causes search to stop working when it runs out of connections.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by iamEAP** [comment]
Gonna go ahead and close this out, now that #14665 is merged!  Thanks again for reporting and fixing.

If you find yourself here in the future from the web, this fix was released as of [v1.0.5-next.0](https://github.com/backstage/backstage/blob/master/plugins/search-backend-node/CHANGELOG.md#105-next0).
