### ISSUE TITLE
🚀 Feature: conditionally render Kubernetes error notice

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#14677]
### 🔖 Feature description

Error block should only be rendered when there are errors.

### 🎤 Context

Currently, the errors block consumes a lot of unnecessary spaces when there is no error.

![Screen Shot 2022-11-17 at 11 39 03](https://user-images.githubusercontent.com/2513586/202425058-b836155b-f307-431d-bb9d-b91e2c547fd1.png)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by pjungermann** [comment]
@sydorovdmytro maybe you want to have a look at this?

**Comment by Linneaiv** [comment]
Is the solution to this to only remove the ErrorEmptyState component entierly and clean up the code, or do we want to replace it with something else? If so then I can have a quick look at it and fix a PR

**Comment by pjungermann** [comment]
@Linneaiv I didn't look at the implementation. For me, the goal would be to have the error notice only if there is an error. "No error" messages are unnecessarily consuming space. The absence of an error notice is enough to express the same.

What you wrote makes sense.

**Comment by Linneaiv** [comment]
![backstage-errorstate](https://user-images.githubusercontent.com/78484334/203073643-3fd848d9-fc35-48e2-a753-f71cd4939f18.PNG)
I have now removed the component so an empty errorlist does not display anything (as the image is showing), and the table is rendered as before if there are errors. Is this what you were looking for? :)

**Comment by pjungermann** [comment]
@Linneaiv yes, that looks good. I guess the horizontal line above "Your Clusters" could be removed, too. (Probably, in general.)

Thanks 👍

**Comment by Rugvip** [comment]
Closing as this was fixed by #14807
