### ISSUE TITLE
🚀 Feature: Edit StarredEntities default message when no entities are starred

### ISSUE THREAD

**Issue by estherannorzie** [backstage/backstage#14676]
### 🔖 Feature description

If no entitles are starred, a call to action message displays.

### 🎤 Context

"You do not have any starred entities yet!" text displays if a user has not starred an entity. Replacing the text with a call to action can help users understand how to use starred entities. Currently, the text cannot be edited directly.

![Screen Shot 2022-11-16 at 3 32 01 PM](https://user-images.githubusercontent.com/86447069/202292777-44a1ec6f-2abe-4b9e-ade0-75b3befc6215.png)

### ✌️ Possible Implementation

Add a prop to the StarredEntities to allow developers to edit the default message or change the default message.

For example: "Click the star beside an entity name to add the entity to this list!"

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
I think this makes sense, we can probably both add a prop that makes the empty state configurable, as well as update the default messaging. What do you think @backstage/techdocs-core?

**Comment by vorbrodt** [comment]
Are you planning to work on this @estherannorzie? Otherwise I would be happy to give it a go. 😄

**Comment by estherannorzie** [comment]
> Are you planning to work on this @estherannorzie? Otherwise I would be happy to give it a go. smile

Thanks for asking! I am already working on it. 🙂
