### ISSUE TITLE
🚀 Feature: Wiki

### ISSUE THREAD

**Issue by BND10706** [backstage/backstage#14674]
### 🔖 Feature description

We currently are looking to replace our Docs with a new application. Part of our docs is a support PD that we like to edit on the fly in the form of a wiki.

I feel like a Wiki is a useful feature to add for companies who are looking to create several subsets of documentation.

### 🎤 Context

In my use case we are a production support team who supports cloud and web applications for a fortune 100 company. We have an on call rotation and need to respond to hundreds of different problems.

We have a document and API library and a support Wiki that we use for troubleshooting and researching quick responses that we can link to our Docs.

The support wiki currently resides in Azure and does not contain needed features or search. Moving to a more robust wiki would be helpful that can we link to docs and keep everything in one place.

### ✌️ Possible Implementation

It could be another core feature, or a plugin.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by VeithBuergerhoff** [comment]
Possibly related to #12543.
