### ISSUE TITLE
🚀 Feature: Allow users to see related entities from the current entity

### ISSUE THREAD

**Issue by anilazaidi** [backstage/backstage#14687]
### 🔖 Feature description

As a Backstage user, it would be nice to see related entities from the entity you're viewing. This feature would be different from the entities shown in the **Relations** card because some entities have a parallel relationship rather than a parent/child relationship.

 

### 🎤 Context

_Current UX_
Discovering other entities is possible if there's a parent/child relationship; e.g., using either `dependsOn`, `dependencyOf`, `providesApi`, `consumesApi`, or `spec.system` attributes. These parent/child relationships are shown in the **Relations** card:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/52043997/202566451-7b5fe2cf-4bac-4ff3-b6b3-c67f8ccb7fb8.png">

This isn't always ideal because some entities are related to each other due to a general topic such as "Web performance". For example, let's say there's a `web-performance` entity with `kind: Component` and `spec.type: documentation`. From this entity, is difficult to discover any `spec.type: library` entity that's related to `web-performance`. In other words, it's difficult to relate documentation only entities (i.e., `kind: Component` with `spec.type: documentation`) with _software_ entities such as `kind: Component` with `spec.type: library` or `kind: API` with `spec.type: openapi`.

### ✌️ Possible Implementation

- Extend the data model with an attribute like `related-entities` to allow software owners to list related entities in their catalog files
    -  If this is implemented, possibly generate a **Related entities** card
- Make tags interactive. If a user clicks on a tag from an entity's **Overview** page, all entities with that tag are returned (possibly in a new window, external link etc.)
    - This feature might 'crowd' the UI; please consult with designers (I will as well :D)

_This feature was discussed in [Discord](https://discord.com/channels/687207715902193673/1034497390545207356) as well and mentioned in this [RFC](https://github.com/backstage/backstage/issues/3122#issuecomment-748606764)_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by kuangp** [comment]
Perhaps the [Playlist plugin](https://github.com/backstage/backstage/tree/master/plugins/playlist) may be a good fit for your use case? This plugin allows you to create custom groupings of any entities so you can hypothetically create a `Web Performance` playlist and include any related entities as part of it. 

It might also be valuable to extend this plugin to provide something like a `Related Playlists` card that you can display on entity pages to show which playlists includes said entity.

**Comment by anilazaidi** [comment]
Interesting @kuangp, didn't realize something like this was available. Let me talk to my team to see how they feel about this.

Thank you!!

**Comment by freben** [comment]
Relationships aren't meant to be just parent-child, they are _any_ type of directed relation from one entity to another. It's entirely possible to add a `documents/documentedBy` custom relation pair. It could be powered in any way you see fit; maybe the documentation component has

```yaml
spec:
  documents: api:other
```

or the api has

```yaml
spec:
  documentation: component:some-docs
```

Or it could be deduced some other way if applicable.

Then, a custom processor extracts that into relation pairs and emits them.

https://backstage.io/docs/features/software-catalog/extending-the-model

(it's a known shortcoming that there's not a ton of docs on _how_ to implement these extensions,. but we're happy to help and the [builtin kinds entity processor](https://github.com/backstage/backstage/blob/e42560af32fb3ee6a9d873201661a8485d502f3c/plugins/catalog-backend/src/modules/core/BuiltinKindsEntityProcessor.ts#L59) may be of interest as an example.

**Comment by anilazaidi** [comment]
Wow, super helpful to know all this @freben -- infinite thanks! I'm in discussion w/ my team right now. Stay tuned :)

**Comment by anilazaidi** [comment]
Hi @freben and @kuangp, my team spoke about the Playlist Plugin and extending the data model quite a bit, a few comments below. But to recap, we requested this feature mainly to establish relationships between a docs-only repo/entity  with other software entities. (We're currently using `kind: Component` with `spec.type: documentation` for docs-only repos.)

* Is there a reason why the Playlist Plugin saves the playlist data in Backstage itself rather than catalog files? Just curious! The workflow feels like a departure from catalog files
* We haven't begun using `kind: Domain` and `kind: System` yet, mainly b/c we'd like to fully understand these `kind` before educating others. Would you recommend docs-only repos about a broad topic (e.g., "Web Performance") to also include a catalog file for `kind: Domain` with `name: Web Performance` so software entities can relate to this topic via the `partOf` attribute in their catalog files?

Any insight will be greatly appreciated -- thank you!!

**Comment by kuangp** [comment]
There a few reasons the Playlist plugin has its own datastore:
- Interactivity was deemed an important feature of this plugin. Giving the ability for users to easily create and edit playlists adhoc provides a smooth UX without the hassle of updating yaml files. This was largely modeled after Spotify playlists and how easy it is to create and share custom lists.
- Playlists depart from the traditional entity relation model in that they are meant to be more adhoc and entirely up to the user how they wish to relate entities together. They may have no real semantic relation besides "My list of favorite components". Therefore it didn't make sense to extend the existing catalog entity model and the yaml files that back it.
- It's common for plugins to implement their own data store so they are more decoupled from each other. The [bazaar](https://github.com/backstage/backstage/tree/master/plugins/bazaar) plugin is example of another plugin that has its own datastore yet links to entities from the catalog.

**Comment by anilazaidi** [comment]
Ahh, it all makes sense! Thanks so much @kuangp :)

**Comment by anilazaidi** [comment]
Yes, I believe so @freben! Many thanks for the feedback, as always :)
