### ISSUE TITLE
🐛 Bug Report: Missing barrel files?

### ISSUE THREAD

**Issue by alper98** [backstage/backstage#14684]
### 📜 Description

It seems there are certain areas of the code, where barrel files are missing?

### 👍 Expected behavior

```
import {
  EntityStatusItem,
  AlphaEntity,
} from '@backstage/catalog-model';
```

### 👎 Actual Behavior with Screenshots

```
import {
  EntityStatusItem,
  AlphaEntity,
} from '@backstage/catalog-model/dist/index.alpha';
```

### 👟 Reproduction steps

1. Import EntityStatusItem or AlphaEntity
2. See import

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
You should be able to import those from `@backstage/catalog-model/alpha` does that work?

**Comment by alper98** [comment]
> You should be able to import those from `@backstage/catalog-model/alpha`, does that work?

Yes it does! Apologies. I should have checked that :)

**Comment by Rugvip** [comment]
Great! Will close this as resolved
