### ISSUE TITLE
🐛 Bug Report: failing to start backend, top-level-await not enabled

### ISSUE THREAD

**Issue by GVelnicu** [backstage/backstage#14680]
### 📜 Description

After following the Azure Sites Backend configuration steps and attempting to start the back-end with yarn start-backend I am being met with :

"Error: Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enable it)
File was processed with these loaders:
* ../../node_modules_swc-loader/src/index.js
You may need an additional loader to handle the result of these loaders."

### 👍 Expected behavior

Run succesfully to be able to go to http://localhost:7007/api/azure/health and see a {"status":"ok"} .

### 👎 Actual Behavior with Screenshots

![MicrosoftTeams-image](https://user-images.githubusercontent.com/112381119/202446009-5983dd98-0789-43a2-b15f-4cf228095072.png)

I've tried looking for a webpack.config.js file to make the change it's asking but I can't seem to find anything matching what would be required.

### 👟 Reproduction steps
Followed the Readme file from https://github.com/backstage/backstage/tree/master/plugins/azure-sites-backend
Simply followed the steps from the Readme file.

### 🖥️ Your Environment

If relevant, using node version 16.13.1 and this is being run on a Linux VM.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
I'm not able to reproduce this, are you sure you followed https://github.com/backstage/backstage/tree/master/plugins/azure-sites-backend correctly? You shouldn't end up with any top-level awaits.

**Comment by GVelnicu** [comment]
As far as I can tell, I have.
-The app-config.yaml has been filled with the required details from azure. 
-yarn add --cwd packages/backend @backstage/plugin-azure-sites-backend has been run
-Azure.ts has been filled in
![image](https://user-images.githubusercontent.com/112381119/203555289-461af514-e225-4a78-8378-17ebbb42ad74.png)
-Index.ts has been filled with 
![image](https://user-images.githubusercontent.com/112381119/203555466-7a1da593-1603-4564-9443-c0a9b7c32002.png)
![image](https://user-images.githubusercontent.com/112381119/203555628-c0e4b8ee-8cc4-44a0-a4e2-7beb1e7da2fa.png)
![image](https://user-images.githubusercontent.com/112381119/203555730-7c9478f5-6b07-4d2c-8cd0-0f5afb6d1d1b.png)

**Comment by jhaals** [comment]
Have you tried installing the plugin in a fresh backstage installation? We are not able to reproduce this currently. You should try to verify if you have any top level `await` in your existing code.

**Comment by jhaals** [comment]
![](https://user-images.githubusercontent.com/112381119/203555730-7c9478f5-6b07-4d2c-8cd0-0f5afb6d1d1b.png)

Looks like there's a closing curly here in the end that might be the issue? 🤞

**Comment by GVelnicu** [comment]
The curly was the culprit, that was embarrassing.
Thank you kindly.
