### ISSUE TITLE
🐛 Bug Report: Location is not orphaned in github integration

### ISSUE THREAD

**Issue by SerenaIce** [backstage/backstage#14690]
### 📜 Description

We have github integrated, and we set the organization and catalogPath in the provider under the catalog.

We found that when the catalog-info.yaml was removed, all the related entities were orphaned. And then we call the API to delete the orphaned entities, but only the Location was not orphaned as expected. 

### 👍 Expected behavior

We found that when the catalog-info.yaml was removed, all the related entities were orphaned. And then we call the API to delete the orphaned entities, but only the Location was not orphaned as expected. 

### 👎 Actual Behavior with Screenshots

We found that when the catalog-info.yaml was removed, all the related entities were orphaned. And then we call the API to delete the orphaned entities, but only the Location was not orphaned as expected. It still shows normally as it was, no orphaned annotation and no changes in the Ancestry, although all its related entities were deleted and the source location catalog file is gone.

### 👟 Reproduction steps

1. Remove the catalog-info.yaml from github repo which was already register in backstage before
2. Check the entities, all the entities including the location entity should be orphaned
3. If the location entity is still active, remove the related orphaned entities, then double check if the location entity become orphaned.

### 🖥️ Your Environment

![Image](https://user-images.githubusercontent.com/43363062/202605576-07b653ed-1cbe-4859-bf8b-d362158b2817.jpeg)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
Thank you for reporting!

What kind of ingestion method are you using? is it a discovery setup, and in that case, is it using a provider or processor?

**Comment by SerenaIce** [comment]
@Rugvip , thanks for your reply. For our GitHub integration, we're not using discovery, but using a provider. And specify the catalogPath under catalog in the app-config.yaml. And we created a customized github provider implemented the EntityProvider  which is a 1-hour frequency scheduler task. And we also set the catalog process interval to 1 hour by calling builder.setProcessingInterval().

During my tests, I encountered three different  cases including what I mentioned above with the same action.

**Case 1 in github repository A**:
Entities in catalog-info.yaml of repository A are all been emitted into backstage, and the location entity shows there.
Then I deleted the catalog-info.yaml  from repository A
The entities registered from catalog-info.yaml become orphaned, the location entity still active
Then I explicitly remove the orphaned entities, Location one is still no changes
But when I added the original catalog-info.yaml back, the Ancestry of the entities lost the location parent in the graph, but in the colocated area still can see the parent location.

**Case 2 in github repository B**:
Entities in catalog-info.yaml of repository B are all been emitted into backstage, and the location entity shows there.
Then I deleted the catalog-info.yaml  from repository B
after a unsure time, all the entities are automatically deleted incuding the location, without any orphaned status
When I added the catalog-info.yaml back to the repository, they can be normally emitted again, and the Ancestry normally shows the Location(parent) -> entity(child) graph like before.

**Case 3 github repository C**:
Entities in catalog-info.yaml of repository C are all been emitted into backstage, and the location entity shows there.
Then I deleted the catalog-info.yaml  from repository C
after a unsure time, the location is deleted automatically, and after a while, the related entities become orphaned
Then I deleted the orphaned ones
When I added the catalog-info.yaml back to the repository, they can be normally emitted again, and the Ancestry normally shows the Location(parent) -> entity(child) graph like before.


So I'm really confused about how the processors and providers are working. 

What causes these diffrent cases although my actions are the same by deleting one repo's catalog-info.yaml?
I read the documentation, but still not sure when will the entities be orphaned and when will be implicitly deleted?

I'm not sure if the scheduler or the time interval for the processors and providers makes things different. Because sometimes I found they are not exactly running by the time interval what we set.

So please help explain the who process for github. I'm suspecting this might be a bug.

**Comment by SerenaIce** [comment]
@Rugvip , thanks for your reply. For our GitHub integration, we're not using discovery, but using a provider. And specify the catalogPath under catalog in the app-config.yaml. And we created a customized github provider implemented the EntityProvider  which is a 1-hour frequency scheduler task. And we also set the catalog process interval to 1 hour by calling builder.setProcessingInterval().

During my tests, I encountered three different  cases including what I mentioned above with the same action.

**Case 1 in github repository A**:
Entities in catalog-info.yaml of repository A are all been emitted into backstage, and the location entity shows there.
Then I deleted the catalog-info.yaml  from repository A
The entities registered from catalog-info.yaml become orphaned, the location entity still active
Then I explicitly remove the orphaned entities, Location one is still no changes
But when I added the original catalog-info.yaml back, the Ancestry of the entities lost the location parent in the graph, but in the colocated area still can see the parent location.

**Case 2 in github repository B**:
Entities in catalog-info.yaml of repository B are all been emitted into backstage, and the location entity shows there.
Then I deleted the catalog-info.yaml  from repository B
after a unsure time, all the entities are automatically deleted incuding the location, without any orphaned status
When I added the catalog-info.yaml back to the repository, they can be normally emitted again, and the Ancestry normally shows the Location(parent) -> entity(child) graph like before.

**Case 3 github repository C**:
Entities in catalog-info.yaml of repository C are all been emitted into backstage, and the location entity shows there.
Then I deleted the catalog-info.yaml  from repository C
after a unsure time, the location is deleted automatically, and after a while, the related entities become orphaned
Then I deleted the orphaned ones
When I added the catalog-info.yaml back to the repository, they can be normally emitted again, and the Ancestry normally shows the Location(parent) -> entity(child) graph like before.


So I'm really confused about how the processors and providers are working. 

What causes these diffrent cases although my actions are the same by deleting one repo's catalog-info.yaml?
I read the documentation, but still not sure when will the entities be orphaned and when will be implicitly deleted?
I suspect the case 3 should be the expected behavior for github provider integration, right?

**Comment by SerenaIce** [comment]
BTW, not sure if this is the similar issue with https://github.com/backstage/backstage/issues/12883

I'm also curious about the logic in Backstage. Where does the synchronization happen to 'final_entities' when deleting the entities from the 'refresh_state' table?

**Comment by SerenaIce** [comment]
Hello @Rugvip, after debug the code, I think I can guess these cases might be cause by the running time difference between the provider's appluMutation() and the DefaultCatalogEngine's Stitch().

But now there's still a unsure part for me is, how is the entity deleted from 'final_entities' table? Could you please point out the implementation of this part firstly? I just noticed the deleting in 'refresh_state' and 'refresh_state_reference' tables, how does the deleting happen in 'final_entities'?

This is really important for our development.

**Comment by jhaals** [comment]
Hi @SerenaIce! Sorry to hear that you're experiencing problems. 

> But now there's still a unsure part for me is, how is the entity deleted from 'final_entities' table? Could you please point out the implementation of this part firstly? I just noticed the deleting in 'refresh_state' and 'œ' tables, how does the deleting happen in 'final_entities'?

There's a cascading delete configured in the database schema so that when the row is deleted from the `refresh_state` table it will also be deleted from `final_entities` https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/migrations/20210302150147_refresh_state.js#L86

> And we created a customized github provider implemented the EntityProvider which is a 1-hour frequency scheduler task.

Could you elaborate a bit more about your customised for the entity provider? Is it completely custom or just that the schedule is decided by you?


I suggest to dig a bit deeper into case 1 as I find it weird that the location is not deleted as well. The location in this example is created by the entityProvider right?
You can inspect the `refresh_state_references` to see if there are still references to the location in the example, it won't be deleted if there are active references to it.

**Comment by SerenaIce** [comment]
@jhaals , Thanks for your answer. 

For case 1, actually I can't reproduce it with a new repo anymore. I think that must be related to some special operation which broke the ancestry between the location entity and the children ones. And it's in `refresh_state_references`, but the `source_entity_ref` is null. This should be a weird case and it's hard to reproduce because I don't know what kind of actions other folks did to it before I touched it. Will try to find the cause.

And for the case 3 which I think should be an expected one. The` replaceUnprocessedEntities() `function could remove the location when the catelog-info.yaml is gone, and then the `stitchOne()` function in processor could orphan the related entities.

But for case 2, it looks like some other processor which immediately delete both the location entity and the related entities when it finds the catalog-info.yaml was gone. **So what's the process for case 2? And what kind of scenario will trigger this?**

And for the github provider, we just overwrite the existing plugin and the functions are almost the same.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/43363062/203985001-ad157418-5502-495c-8688-cc6c1bba9377.png">

**Comment by jhaals** [comment]
`source_entity_ref` will/should be set to `null` for locations generated directly by the entityProvider as there are no parent other than the provider itself. There should however be a `source_key` that's your entityProvider's id for those rows. It's worth checking that you do not have historic/old entity providers that reference entities because that will lead to problems with old entities laying around. For example if you used the "default" GithubEntityProvider and then switched to your `GithubCustomEntityProvider`, in case you didn't purge entities from the other provider you might have some conflicts and duplicates that are causing issues.

**Comment by SerenaIce** [comment]
@jhaals , thanks for your answers.  We don't have other old entities laying around and do not ever use the default `GithubEntityProvider` provided by Backstage. But as I asked other folks, they did rename our customer one from `GithubEntityProvider` to `GithubCustomEntityProvider`, this change might cause case 1.

But could you please help explain how case 3 could happen? Just did exactly actions like case 2 without any other changes and can be reproduced sometimes.
