### ISSUE TITLE
🚀 Feature: Embed Scaffolder create flow into Catalog entity page  

### ISSUE THREAD

**Issue by taras** [backstage/backstage#14706]
### 🔖 Feature description

We would like to be able to invoke Scaffolder workflows in the context of a component without leaving it's entity page.

![Embed Scaffolder create flow into Catalog entity page](https://user-images.githubusercontent.com/74687/202740505-7eac8a99-bbf2-4993-b6d9-0ddb323eb4c7.png)

It would be helpful for us to be able to do the following,

1. Create a custom wizard page or embed the stepper components into another React component. This will allow us to render it in the entity page of a component.
2. Hide some fields from a template when used in this context because we can pull existing information from the entity.
3. Skip confirmation screen on the last page of the wizard
4. Show the workflow run in the context of the entity page
5. Control what displays after the workflow successfully executes

### 🎤 Context

One of our clients wants to be able to use the Scaffolder plugin to configure existing components. 

For example, they want to be able to add onboard an existing component to use Security checks. The onboarding process requires providing some form input, create issues in GitHub Issues, notify 3rd party service and create a PR with an annotation. 

They have a bunch of these kinds of operations so it's important to be able to easily make these kinds of flows without having to do lots of copy and paste.

### ✌️ Possible Implementation

**Note**: Frontside can implement these changes once we agree on the design.

This should be added to Scaffolder next because it'll require some API changes. We need to make the components provided by Scaffolder next more composable so we could package them into a reusable component.

We'd like some direction on how the maintainers would like to make these components composable.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
I think this makes sense and can be used for a bunch of different patterns. Are there any blockers we need to get out of the way to be able to support this?

**Comment by taras** [comment]
No blockers. I wanted to check if maintainers have any comments before we proceed to make a proposal. 

@dagda1 and I will look at what it'll take to implement this. We'll work on it next week.

**Comment by taras** [comment]
This was implemented in #15162

**Comment by abkura** [comment]
@taras do you have any documentation to how can we use this feature?

**Comment by taras** [comment]
@abkura it's not released yet. It's scheduled for release on Feb 14. I believe it'll available as a `next` preview on Thursday. 

@dagda1 do you have an example of how to use this component?

**Comment by dagda1** [comment]
> @abkura it's not released yet. It's scheduled for release on Feb 14. I believe it'll available as a `next` preview on Thursday.
> 
> @dagda1 do you have an example of how to use this component?

I can certainly write documentation but I have no idea were it should go, I can't see anything else on the `NextScaffolderPage`

**Comment by abkura** [comment]
@taras 'ui:widget': 'hidden' is not working from Embed Scaffolder flows. Any thoughts?

**Comment by abkura** [comment]
@taras @dagda1 I'm using EmbeddableWorkflow and the below snippet to hide a field from the review step is presenting as "Undefined"

```
test:
          title: Test
          type: string
          ui:backstage:
            review:
              show: false
```

![image](https://github.com/backstage/backstage/assets/52422980/76d36a48-5686-44b8-a66f-91b418d8fdd2)

**Comment by jgrumboe** [comment]
Is this feature officially released, and where to find proper documentation about it?

**Comment by ScottGuymer** [comment]
I am too missing some docs on how to use this feature.

Can it be used alone or does it need to be coupled with https://github.com/thefrontside/playhouse/tree/main/plugins/scaffolder-frontend-workflow to be functional?

I am trying it out and it seems to render the scaffolder form but doesnt seem to actually trigger the workflow and complete it. Not sure if this is something I am doing wrong and missing something out or if its just not intended to work like that.

**Comment by jgrumboe** [comment]
@dagda1 Could you probably help us here since you also worked on https://github.com/backstage/backstage/pull/15162?
Would be highly appreciated 🙇‍♂️

**Comment by jgrumboe** [comment]
@Roshick, since I saw your comment in #29638, where you mentioned that you're heavily using embedded Scaffolder workflows, it would be great if you could share an example or links to documentation on how to use it? 🙇

**Comment by Roshick** [comment]
@jgrumboe to be honest, I would not recommend to rely on or even use this feature, as it's super finicky and not really officially supported. This causes many issues on updates to the scaffolder which we have to port ourselves (if possible, which is often not the case). 

The scaffolder is not really designed to be used this way. We will probably get rid of this and use something like Argo Workflows (or any other workflow engine, which is what we kinda use the scaffolder for atm), embedded via iframe.

**Comment by benjdlambert** [comment]
`EmbeddedScaffolderWorkflow` is definitely experimental and hasn't had that much love.

We're looking at some options for the future, and the future of that component especially with the new frontend system and how all this fits together.

Will come back with some updates in the coming weeks :pray:
