### ISSUE TITLE
Unable to provide custom implementation of IdentityAPI

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#14715]
### 📜 Description

As per the docs on [Custom implementations of Utility APIs](https://backstage.io/docs/api/utility-apis#custom-implementations-of-utility-apis), I am trying to provide a custom implementation of the Identity API. In my `packages/app/src/apis.ts`, I have 

```ts

class MyCustomIdentityApi implements IdentityApi {
  async getProfileInfo() {
    const profileInfo: ProfileInfo = getCustomProfile();
    return profileInfo;
  }
  async getBackstageIdentity() {
    const backstageUserIdentity: BackstageUserIdentity = getCustomBackstageIdentity();
    return backstageUserIdentity;
  }
  async getCredentials() {
    return 'token';
  }
  async signOut() {}
}

export const apis: AnyApiFactory[] = [
  createApiFactory(identityApiRef, new MyCustomIdentityApi()),
];
```

However, when I start the Backstage app, it gives me the error `Plugin catalog tried to register duplicate or forbidden API factory for apiRef{plugin.catalog.service}`

<img width="746" alt="Screenshot 2022-11-20 at 1 43 16 PM" src="https://user-images.githubusercontent.com/8065913/202892233-185548f8-c89e-4d16-ab5a-f5879b613881.png">

### 👍 Expected behavior

I should be able to provide the custom implementation of the Identity API.

### 👎 Actual Behavior with Screenshots

Provided.

### 👟 Reproduction steps

N/A

### 📃 Provide the context for the Bug.

Some additional context of the problem.

We at [Harness](https://harness.io) are working on having the Backstage app embedded on our frontend as a "micro-frontend". Users sign in to the Harness website with the Harness sign in page. After signing in, they open the Backstage app as one of the embedded apps at a `/backstage` route.

It's not ideal for users to sign in twice (once on Harness and then on Backstage), so we skipped the Backstage SignInPage and wanted to use Harness identity to populate the Backstage Identity so that plugins are able to retrieve the Backstage User Identity. We thought the best way to do this is to provide a custom implementation of the Identity API.

Digging deeper into the code for [AppManager](https://github.com/backstage/backstage/blob/3c99dadef713b78676e6bf860ff1d88bef1fb4e0/packages/core-app-api/src/app/AppManager.tsx#L487-L491) I found that the IdentityApi is registered as a "static" api. So maybe it's not even possible to provide a custom implementation of it?

We'd love to know if there's a way to get access to set the Backstage User Identity when we are not using the Backstage SignIn Page. Thanks!

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Yep it's not possible to override, we could definitely update the app to throw a more informative error if someone is trying to do that.

The way to implement it is via the `SignInPage` component, which is supposed to provide an implementation of the `IdentityApi` to the app. In this case it sounds like you might want to use the [`ProxiedSignInPage`](https://backstage.io/docs/reference/core-components.proxiedsigninpage) or something similar to that.

**Comment by OrkoHunter** [comment]
Thanks for the response @Rugvip - we'll go ahead and use the ProxySignInPage. :) I'll close the issue - and maybe open a new one for a clear error message when someone is trying to override the `identityApiRef`. Are there any other such non-overridable APIs though? Looks like `config` and `appTheme`.
