### ISSUE TITLE
🚀 Feature: Exclude certain entity kinds from search

### ISSUE THREAD

**Issue by omerfarukdogan** [backstage/backstage#14719]
### 🔖 Feature description

It should be possible to prevent entities of certain kinds/types from showing up on search results (in both `SidebarSearchModal` and `SearchPage`).

### 🎤 Context

For example, we have tons of generated Location entities created by the Bitbucket integration plugin. I want to hide these from search results since they are not relevant to the end user. They overcrowd the results, and make it hard to find relevant results.

I have tried to use `SearchFilter.Select` for `SearchPage`, but when "All" is selected, other kinds are listed anyway.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
I think you'll be able to achieve this using the `filter` option of the [`DefaultCatalogCollator`](https://backstage.io/docs/reference/plugin-catalog-backend.defaultcatalogcollator), right @backstage/techdocs-core? 😁

**Comment by iamEAP** [comment]
Indeed! Have a look at [this tutorial](https://backstage.io/docs/features/search/how-to-guides#how-to-limit-what-can-be-searched-in-the-software-catalog) on exactly this!

**Comment by omerfarukdogan** [comment]
Hello @Rugvip, @iamEAP,

Thanks for pointing this out (and sorry for wasting your time). I tried that solution and it is indeed exactly what I wanted. TBH, I had not checked that section in the documentation. I read [Customizing Search](https://backstage.io/docs/features/search/getting-started#customizing-search) and I couldn't find any related information, so I thought there was no such feature. Would it be better to move that information into Customizing Search?

**Comment by emmaindal** [comment]
Great suggestion @omerfarukdogan, do you think its enough to link to that how to guide from the customizing search section? and if so do you have any suggestion of where?
