### ISSUE TITLE
🚀 Feature: Allow embedding videos from the document repository

### ISSUE THREAD

**Issue by omerfarukdogan** [backstage/backstage#14722]
### 🔖 Feature description

Videos which are present in the document repository should be able to be embedded in the documentation using `iframe` tags.

### 🎤 Context

Authors might want to embed videos to enhance the documentation. Currently, videos must be uploaded to an external source to be embedded into a documentation.

I am trying to add a video, which is not uploaded to any external source, into a documentation. I have added the video into the document repository. When I try to embed it into the documentation using `<iframe src="./sample-video.mp4"></iframe>` element, it doesn't work.

### ✌️ Possible Implementation

Currently, the sanitizer can't determine if the host of the source is in the allowedIframeHosts list, because when it [tries to parse](https://github.com/backstage/backstage/blob/cd41320ad04c1d507d7a60b3f2b3bb82edecb3dc/plugins/techdocs/src/reader/transformers/html/hooks/iframes.ts#L33) the host of the src using `new URL(src)`, an `Error` is thrown, therefore the element is considered as unsafe.

Relative links should be detected and allowed (preferably without any additional configuration). We need to determine a reliable method to detect relative links. Would `url.startsWith("./")` be sufficient?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by omerfarukdogan** [comment]
Not stale.

**Comment by benjdlambert** [comment]
Does this help you? https://github.com/backstage/backstage/issues/7393

**Comment by omerfarukdogan** [comment]
Hello @benjdlambert,

I added `<video src="videos/vid.mp4"></video>` to the document and updated `media-src` in the config. But it doesn't work. The video file is present in the generated documentation folder on the filesystem, but I don't think backstage is even trying to serve the video file. It thinks that the `videos/vid.mp4` part belongs to a page in the document.

Request:
> http://localhost:3000/documentshub/docs/default/component/test-201/videos/vid.mp4

Response:
> You need to enable JavaScript to run this app.

When I view the url in the browser, I see the following page:

![image](https://user-images.githubusercontent.com/8117265/218443396-857f2593-c037-4325-baad-0423fa6cb441.png)

**Comment by iamEAP** [comment]
Yeah, I may no longer be the best person to speak to this.  Perhaps @agentbellnorm could take a look?

**Comment by darrenyung** [comment]
Following this thread as well. I got a request from one of our writers that they would like to embed html with dynamic diagrams. I tried using **pymdownx.snippets** but the DOMPurify feature is stripping the **script** tag off. IFrame was my next option but seems like self-hosted is not yet supported.

**Comment by EXPErdelfavero** [comment]
https://backstage.io/docs/features/techdocs/how-to-guides/#how-to-enable-iframes-in-techdocs explains how iframes are limited to serving content from the servers on the allow list. I haven't tried allowing the server where the video is stored, but would try that.

About the later question about using iframes for dynamic diagrams, I have no idea -- that's not something we've tried where I use Backstage. I'd try allow-listing the server your diagram is hosted on, but have no idea if that actually works.

For both use cases, if using a relative path in the <iframe> tag doesn't work, I'd try giving a complete URL. Depending on how the allow list check is implemented, relative paths might not work as expected. (No guarantees, I'm a tech writer not a web developer...)

**Comment by alexef** [comment]
not stale
