### ISSUE TITLE
🐛 Bug Report: Feature and Plugin issue templates link to Code of Conduct but say Contributor Guidelines 

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#14740]
### 📜 Description

When creating an issue for a Feature of Plugin the section for the Code of Conduct says "I have read the Contributing Guidelines" but links to the Code of Conduct correctly.

### 👍 Expected behavior

The text should say: "I have read the Conde of Conduct"

### 👎 Actual Behavior with Screenshots

When creating an issue for a Feature of Plugin the section for the Code of Conduct says "I have read the Contributing Guidelines" but links to the Code of Conduct correctly.

Feature: https://github.com/backstage/backstage/blame/master/.github/ISSUE_TEMPLATE/feature.yaml#L44
Plugin: https://github.com/backstage/backstage/blame/master/.github/ISSUE_TEMPLATE/plugin.yaml#L42

It's not easy to link to these files, it only shows the rendered version so had to use blame to get links 🤔 

### 👟 Reproduction steps

1. Got to create a Feature or Plugin issue
2. Scroll down to the Code of Conduct section

Notice: The text says: "I have read the Contributing Guidelines"

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by kurtaking** [comment]
You have a small type in your Expected Behavior section
> "I have read the Conde of Conduct"

I have used the following in my PR
> "I have read the Code of Conduct"

**Comment by awanlin** [comment]
Good catch @kurtaking! Thanks for running with this 🚀
