### ISSUE TITLE
🐛 Bug Report: UseEntityOwnership comparison is case sensitive

### ISSUE THREAD

**Issue by griesd** [backstage/backstage#14787]
### 📜 Description

We store our ownership entity refs claim with mixed case in the group name. On the catalog page, the Owned filter fails to recognize ownership correctly because the comparison made between the claims and the catalog entity ownership are compared with case sensitivity. Most other comparisons in Backstage are case insensitive, so we believe this one should be as well.

### 👍 Expected behavior

We expect the comparison in UseEntityOwnership.ts to be case insensitive. The owned filter on the catalog page should show that entities are owned when the cases don't match up. 

### 👎 Actual Behavior with Screenshots

<img width="1561" alt="Screen Shot 2022-11-22 at 3 55 20 PM" src="https://user-images.githubusercontent.com/48453465/203419690-b0ad7d76-7e18-4692-9db9-36479c3a36d3.png">
<img width="747" alt="Screen Shot 2022-11-22 at 3 55 33 PM" src="https://user-images.githubusercontent.com/48453465/203419703-fc6792eb-99ae-49ad-872c-c63103189b5a.png">

### 👟 Reproduction steps

1. Pass through an OwnershipEntityRef with mixed case in the group name
2. Register an Entity with that same group name
3. Go to catalog page

### 📃 Provide the context for the Bug.

This is a unique case because we do not use StringifyEntityRef when making our ownership claims in auth.ts. Instead, we pass through our own string that is mixed case, so the comparison that takes place in https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/hooks/useEntityOwnership.ts
Does not work as intended for us. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
For interested readers - the discussion is held in https://github.com/backstage/backstage/pull/14788
