### ISSUE TITLE
🐛 Bug Report: Pull requests board show PRs from archived repos

### ISSUE THREAD

**Issue by TarasZubreiFiverr** [backstage/backstage#14805]
### 📜 Description

I started using `@backstage/plugin-github-pull-requests-board` and I noticed there it was showing active in-review PR from one of the archived repository.
![image](https://user-images.githubusercontent.com/76960985/203505271-7b44d95c-14ea-4f8d-9f0f-3c38e14141a8.png)
I can't close the PR since repo is archived so it keeps showing in the board.
<img width="853" alt="image" src="https://user-images.githubusercontent.com/76960985/203504595-519c2628-8c5b-4acc-80e3-9296219e46d7.png">

### 👍 Expected behavior

I think we should filter out PRs in arrived repos and don't show it at all

### 👎 Actual Behavior with Screenshots

There's a PR from archived repository shown in the board.

### 👟 Reproduction steps

1. Create a PR in the repo
2. Archive the repo
3. Add `@backstage/plugin-github-pull-requests-board` to your backstage project
4. Add the board to group entity page 
```typescript
<EntityLayout.Route path="/pull-requests" title="Pull Requests">
  <EntityTeamPullRequestsContent />
</EntityLayout.Route>
```
5. Open your group page
6. Go to Pull Requests tab
7. Toggle Show PRs from your team

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Sounds like something we should fix 😅 Could you submit a PR? :)
