### ISSUE TITLE
🚀 Feature: Surface Git Commit Hashes in all Scaffolder SCM Actions

### ISSUE THREAD

**Issue by LukvonStrom** [backstage/backstage#14828]
### 🔖 Feature description

The utility of the `publish` scaffolder actions could be increased by returning the commitHash of the initial commit done as part of repository creation.
This would for example allow a better integration of diverse CI/CD systems into the scaffolder.

### 🎤 Context

Each inbuilt `publish` scaffolder action should return the commitHash as part of its return values.
As the commitHash is discarded at the moment, but readily available via `isomorphic-git`, the implementation would be fairly straightforward.
Please see below for an implementation suggestion.

### ✌️ Possible Implementation

Please find below a sequential description of the changes needed to surface the commitHash for the inbuilt actions.    

#### Surfacing the commitHash in the SCM Helper of the backend-common package

https://github.com/backstage/backstage/blob/6b33267ada75fbcbac2f72c0459f18cea4c68d96/packages/backend-common/src/scm/git.ts#L115

Await `git.commit`, as it returns a `Promise<string>`, which resolves to the Git Commit Hash (https://isomorphic-git.org/docs/en/commit)

#### Returning the commitHash in the Scaffolder Git Helper Methods

Return the commitHash at the following places:

`initRepoAndPush`
https://github.com/backstage/backstage/blob/6b33267ada75fbcbac2f72c0459f18cea4c68d96/plugins/scaffolder-backend/src/scaffolder/actions/builtin/helpers.ts#L113
and
`commitAndPushRepo`
https://github.com/backstage/backstage/blob/6b33267ada75fbcbac2f72c0459f18cea4c68d96/plugins/scaffolder-backend/src/scaffolder/actions/builtin/helpers.ts#L167    

And subsequently in the separate github helper function `initRepoPushAndProtect`
https://github.com/backstage/backstage/blob/6b33267ada75fbcbac2f72c0459f18cea4c68d96/plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts#L280    

    
#### Output the commitHash via the Scaffolder Action Context

Finally return it in every 'normal' (i.e. non PR/MR) publish action via the context:
https://github.com/backstage/backstage/blob/6b33267ada75fbcbac2f72c0459f18cea4c68d96/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts#L219

for example via 
```typescript
const { commitHash } = await initRepoPushAndProtect(
  // (snip)
);

ctx.output('commitHash', commitHash);
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jhaals** [comment]
Sounds like a good idea!
Perhaps someone is interested in drafting a proposal for this? 🙏 
FYI @benjdlambert

**Comment by benjdlambert** [comment]
Sorry I totally dropped the ball on this and hadn’t seen it. Think this sounds reasonable if anyone wants to pick this up!
