### ISSUE TITLE
🚀 Feature: Dynamically disable options (try-it / authorize buttons) on Swagger page in API Catalog

### ISSUE THREAD

**Issue by whitemanthedj** [backstage/backstage#14824]
### 🔖 Feature description

There are some APIs in the catalog that need to disable the try-it and the authorize buttons in the API Swagger page. I see this feature as a way to pass in the [definitions](https://github.com/backstage/backstage/blob/master/plugins/api-docs/src/components/ApiDefinitionCard/ApiDefinitionWidget.tsx#L37) as well as customizable [plugins](https://swagger.io/docs/open-source-tools/swagger-ui/customization/plugin-api/) / options to the Swagger page (options and plugins used interchangeably going forward when talking about the SwaggerUI).

This would allow developers to send in options for APIs and have the Swagger page apply them. Note that it would be up to the developers passing in the options to correctly format options, but then it would allow for any of the Swagger UI options to be configurable based on the options passed. It should not affect APIs without the custom options, so it would only be an add on for APIs that require custom options. 

### 🎤 Context

Some APIs in the catalog need to dynamically disable some of the Swagger configurable options via a [plugin](https://github.com/swagger-api/swagger-ui/issues/3725#issuecomment-334899276), specifically disabling the try-it button and the Authorize button. The Try-it button setups a test call and provides a sample response in the UI, and the Authorize button creates a sample authorization token for users to use when calling certain APIs. 

Further extending the Swagger page to accept options / plugins for would allow for further extensibility and control over what APIs show. By making the Swagger page take options, any other customizable aspect of the Swagger UI would be configurable now at an API level.

### ✌️ Possible Implementation

The Swagger UI will need to be passed plugin options in order to customize it:

`<SwaggerUI spec={def} url="" plugins={plugins} deepLinking />` 

where the plugins are passed in through the props as seen [here](https://github.com/backstage/backstage/blob/master/plugins/api-docs/src/components/OpenApiDefinitionWidget/OpenApiDefinition.tsx#L152).

The plugins will also need to be propagated through this [file](https://github.com/backstage/backstage/blob/master/plugins/api-docs/src/components/ApiDefinitionCard/ApiDefinitionWidget.tsx#L37).

Additionally, the options will need to be set and retrieved prior to being sent to the Swagger page, and I would imagine that having a predefined spec attribute would be a good way of doing this, and will have to be set prior to [here](https://github.com/backstage/backstage/blob/6b33267ada75fbcbac2f72c0459f18cea4c68d96/plugins/api-docs/dev/index.tsx#L65). 

Though I have not have a lot of time to really figure out how this might look, I would imagine that an API Processor could look for an Entity's `spec.swaggerPlugins` (or something of that sort) and transform it into what the SwaggerUI could process. Then, in addition to passing the `definition` to the SwaggerUI, it could also pass the `swaggerPlugins`.

By propagating the options from an API, the Swagger page can dynamically render the Swagger pages differently for different APIs. It is important to make sure that the APIs without any options are not affected, but by processing the Entity's options prior to passing the options to the SwaggerUI element, there should not be any negative effect on APIs that don't pass options. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Hi! I think this make sense to be able to do that. Feel free to submit a proposal as a PR 👍

**Comment by whitemanthedj** [comment]
Hey @jhaals, 
I am running into some typing errors due to the fact that all spec attributes need to be a `JsonObject` which will recursively simplify down to all primitive types. The plugins will likely need to be more complex, including a lamda function as a valid attribute of the JsonObject: `() => () => false`. One way to bypass this using the current approach is to store the plugins as a string until right before the SwaggerUI gets it (and convert it using something like `JSON.parse(plugins_string_representation)`), but I don't think that is a great way to go about this. Do you have any recommendations for where else this information could be stored at the entity level so it would not have to be translated into a string and back again (or any other ideas under the current constraints)? 
Thanks!
![Screenshot 2022-12-07 at 4 02 44 PM](https://user-images.githubusercontent.com/44525898/206323521-bb1fe856-5c91-48e7-841d-89ed7d86377d.png)
![Screenshot 2022-12-07 at 4 06 46 PM](https://user-images.githubusercontent.com/44525898/206324073-551706b9-6d26-466e-9ef0-ab7cd1e77e86.png)

**Comment by Rugvip** [comment]
@whitemanthedj you won't be able to store anything else than `JsonObject` in the catalog, that's a constraint to work with x)

I think a reasonably light-weight way forward for this is to add one or more annotations that are known by the API docs plugin, that are read and used to configure the UI.

**Comment by whitemanthedj** [comment]
If I understand correctly, then that will lose the generic ability for any of the Swagger plugins. If apis need additional plugins in the future that I don't codify now for the swagger page, then they would have to update this repo, is that what you meant?

**Comment by Rugvip** [comment]
@whitemanthedj kind of, you could also add some customization points that makes it possible for users of the API docs plugin to customize the logic. That way you may not need to change code in this repo, but your own repo.

**Comment by freben** [comment]
For future readers: see closing comments in #16169. It may be best to not so much focus on explicit customizability of the api-docs plugin's top level components themselves (such as `EntityApiDefinitionCard`/`ApiDefinitionCard`). Instead, the base idea should probably be that users supply entirely custom views (by means of the [`apiDocsConfigRef`](https://github.com/backstage/backstage/blob/780ce04d7275ea556c71f2206c72974f50005665/plugins/api-docs/src/config.ts#L22)). Then, any work related to the ask in here, might want to focus on what can be done to make it less copy-paste-heavy to make such custom views. Are there any helper components that need to be created or exported, for example? Then the onus on passing in plugins, or giving custom props, is put entirely on the adopter without having to go through the layers of the framework as such.
