### ISSUE TITLE
🚀 Feature: Documentation as reference

### ISSUE THREAD

**Issue by jrwpatterson** [backstage/backstage#14844]
### 🔖 Feature description

Have multiple components point to the same documentations without adding the different systems to the docs catalog page duplicated

### 🎤 Context

Hi we have some items where we want multiple items in the catalogue for example we might from the same folder structure want to have 
- server 
- frontend
- api
- system
- domain
In the mono repo we would like the documentation to be a single documentation as its all one system with different components. However if we put the documentation stub on all the components in the tech docs pages we get multiple duplicates of the docs one for each page. 

### ✌️ Possible Implementation

either a dedupe of the documents, or better being able to reference another projects docs one, where one would be the owner but if I reference the owner project in the techdocs annotation it references it shows the techdocs in all the links but doesn't add a new one to the docs catalog

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by andrewthauer** [comment]
Could be related to this last proposal discussion? https://github.com/backstage/backstage/issues/5913
