### ISSUE TITLE
🐛 Bug Report: 7007/api/catalog/entities ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by jethers** [backstage/backstage#14874]
### 📜 Description

I installed the backstage app and after I open it in a browser, after some minutes, the browser returned errors (I tried firefox, chrome and opera).

### 👍 Expected behavior

Backstage's frontend app should loads the information from backend in the browser.

### 👎 Actual Behavior with Screenshots

Browser errors: 
`Failed to load entity kinds`
`Error: Could not fetch catalog entities : TypeError: Failed to fetch`

Looking at Chrome's browser console I got the following datails:
`index.esm.js:1420          GET http://<Server IP address>:7007/api/catalog/entities?filter=kind=component net::ERR_CONNECTION_RESET`
`index.esm.js:1420          GET http://<Server IP address>:7007/api/catalog/entity-facets?facet=metadata.tags net::ERR_CONNECTION_RESET`
`index.esm.js:1420          GET http://<Server IP address>:7007/api/catalog/entities?filter=kind=api net::ERR_CONNECTION_RESET`

On the server side it looked like everything was fine:
`2022-11-27T00:45:35.961Z search info Collating documents for software-catalog succeeded type=plugin documentType=software-catalog`

`2022-11-27T00:45:54.627Z backstage info <local IP Address> - - [27/Nov/2022:00:45:54 +0000] "GET /api/catalog/entity-facets?facet=kind HTTP/1.1 200 225 "http://<server IP address>:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" type=incomingRequest`

`2022-11-27T00:45:54.631Z backstage info <local IP Address> - - [27/Nov/2022:00:45:54 +0000] "GET /api/catalog/entity-facets?facet=metadata.tags HTTP/1.1" 200 31 "http://<server IP address>:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" type=incomingRequest`

`2022-11-27T00:45:54.635Z backstage info <local IP Address> - - [27/Nov/2022:00:45:54 +0000] "GET /api/catalog/entity-facets?facet=metadata.tags HTTP/1.1" 200 31 "http://<server IP address>:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" type=incomingRequest`

`2022-11-27T00:45:54.637Z backstage info <local IP Address> - - [27/Nov/2022:00:45:54 +0000] "GET /api/catalog/entity-facets?facet=kind HTTP/1.1" 200 225 "http://<server IP address>:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" type=incomingRequest`

`2022-11-27T00:45:54.638Z backstage info <local IP Address> - - [27/Nov/2022:00:45:54 +0000] "GET /api/catalog/entities?filter=kind=api HTTP/1.1" 200 - "http://<server IP address>:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" type=incomingRequest`

`2022-11-27T00:45:54.772Z backstage info <local IP Address> - - [27/Nov/2022:00:45:54 +0000] "GET /api/catalog/entity-facets?facet=kind HTTP/1.1" 200 225 "http://<server IP address>:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" type=incomingRequest`

### 👟 Reproduction steps

1. I followed the installation procedure described here: https://backstage.io/docs/getting-started/

2. I configured the file app-config.yaml:
app:
  title: Scaffolded Backstage App
  baseUrl: http://[Server IP Address]:8080
organization:
  name: My Company
backend:
  baseUrl: http://[Server IP Address]:7007
  listen:
    port: 7007
    host: [Server IP Address]
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://[Server IP Address]:8080
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
  cache:
    store: memory
4. I started the app:
yarn dev

### 📃 Provide the context for the Bug.

I'm just trying to install Backstage to use Software Catalog.

### 🖥️ Your Environment

#yarn backstage-cli info
yarn run v1.22.19
$ /opt/backstage/catalogo/node_modules/.bin/backstage-cli info
OS:   Linux 4.14.296-222.539.amzn2.x86_64 - linux/x64
node: v16.18.1
yarn: 1.22.19
cli:  0.21.1 (installed)
backstage:  1.8.0

 
Dependencies:
  @backstage/app-defaults                          1.0.8
  @backstage/backend-common                        0.16.0
  @backstage/backend-plugin-api                    0.1.4
  @backstage/backend-tasks                         0.3.7
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.21.1
  @backstage/config-loader                         1.1.6
  @backstage/config                                1.0.4
  @backstage/core-app-api                          1.2.0
  @backstage/core-components                       0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/errors                                1.1.3
  @backstage/integration-react                     1.1.6
  @backstage/integration                           1.4.0
  @backstage/plugin-api-docs                       0.8.11
  @backstage/plugin-app-backend                    0.3.38
  @backstage/plugin-auth-backend                   0.17.1
  @backstage/plugin-auth-node                      0.2.7
  @backstage/plugin-catalog-backend                1.5.1
  @backstage/plugin-catalog-common                 1.0.8
  @backstage/plugin-catalog-graph                  0.2.23
  @backstage/plugin-catalog-import                 0.9.1
  @backstage/plugin-catalog-node                   1.2.1
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.6.1
  @backstage/plugin-github-actions                 0.5.11
  @backstage/plugin-org                            0.6.1
  @backstage/plugin-permission-common              0.7.1
  @backstage/plugin-permission-node                0.7.1
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.32
  @backstage/plugin-scaffolder-backend             1.8.0
  @backstage/plugin-scaffolder-common              1.2.2
  @backstage/plugin-scaffolder                     1.8.0
  @backstage/plugin-search-backend-module-pg       0.4.2
  @backstage/plugin-search-backend-node            1.0.4
  @backstage/plugin-search-backend                 1.1.1
  @backstage/plugin-search-common                  1.1.1
  @backstage/plugin-search-react                   1.2.1
  @backstage/plugin-search                         1.0.4
  @backstage/plugin-tech-radar                     0.5.18
  @backstage/plugin-techdocs-backend               1.4.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.6
  @backstage/plugin-techdocs-node                  1.4.2
  @backstage/plugin-techdocs-react                 1.0.6
  @backstage/plugin-techdocs                       1.4.0
  @backstage/plugin-user-settings                  0.5.1
  @backstage/release-manifests                     0.0.7
  @backstage/test-utils                            1.2.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1
  @backstage/version-bridge                        1.0.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and I find similar issue (https://github.com/backstage/backstage/issues/10323#issuecomment-1312547124) but I opend another issue with some more details.

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by jethers** [comment]
I found the root cause of the issue. Despite of the connection from browser to the backend service had happened (I could see it at the server side using the comand 'netstat -an | grep 7007') something in the infrastructure was resetting the connection. I changed the backend port from 7007 to 80 and it started to work :)

**Comment by hamzamaan** [comment]
@jethers can we connect privately, if you dont mind. I am facing this issue since 15 days, Not able to resolve this. Thanks

**Comment by m0un10** [comment]
i'm getting the same issue. the browser is trying to access `:7007` without any hostname specified. what is causing this?

**Comment by jethinho** [comment]
> @jethers can we connect privately, if you dont mind. I am facing this issue since 15 days, Not able to resolve this. Thanks

Sorry for the late reply. In my environment I had some network rule that block port 7007. When I replaced the port to 80 it started to work.

**Comment by jethinho** [comment]
> i'm getting the same issue. the browser is trying to access `:7007` without any hostname specified. what is causing this?

The hostname should be configured at backstage configuration file: https://github.com/backstage/backstage/blob/master/app-config.yaml#:~:text=%2D%20secret%3A%20%24%7BBACKEND_SECRET%7D-,baseUrl,-%3A%20http%3A//localhost

**Comment by premnttdata** [comment]
> I found the root cause of the issue. Despite of the connection from browser to the backend service had happened (I could see it at the server side using the comand 'netstat -an | grep 7007') something in the infrastructure was resetting the connection. I changed the backend port from 7007 to 80 and it started to work :)

thanks, it works like charm

**Comment by djmeph** [comment]
> I found the root cause of the issue. Despite of the connection from browser to the backend service had happened (I could see it at the server side using the comand 'netstat -an | grep 7007') something in the infrastructure was resetting the connection. I changed the backend port from 7007 to 80 and it started to work :)

This is not the root cause, and it's not a solution that suits everyone for a couple main reasons:

1. In many containerized systems, some OSes won't let you bind port 80 unless you are the root user, which precludes you from deploying this solution as non-root user. 
2. Many containerized systems use a reverse proxy like Nginx or Istio that is bound to port 80, which also prevents you from binding to port 80, even as root. 

The root cause of this is a bug in Node v18. The bug was introduced in v18 and fixed in v20. (Now LTS) The bug is detailed in here: https://github.com/node-fetch/node-fetch/issues/1624

The bug causes Node to default to the first entry in /etc/hosts when doing the localhost lookup. In many OSes, the first localhost entry is `::1` or the IPv6 entry, by default. 

The fix for this is to use `127.0.0.1` instead of `localhost`. 

We are using a recent build of Backstage and some of the dependencies require Node v10-18, and are not compatible yet with Node 20, so upgrading to Node 20 is not an option. 

I would also not suggest downgrading to Node 16, which reached EOL on September 11, 2023. Node 16 includes support for a version of OpenSSL that has a major security bug. That version of OpenSSL also reached EOL on September 11, 2023. I won't get into the weeds on that bug, but it can expose some major security issues.
