### ISSUE TITLE
🐛 Bug Report: Button component is confusing

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#14889]
### 📜 Description

Our [`Button`](https://github.com/backstage/backstage/blob/773f3b51ed35e0ad4121f81672126c75d784acd8/packages/core-components/src/components/Button/Button.tsx#L49) component isn't actually a button, it's a link. I think we should rename it to `LinkButton` or something like that.

### 👍 Expected behavior

That it's a regular `Button` component, perhaps with a bit of click tracking via the analytics API.

### 👎 Actual Behavior with Screenshots

It requires the `to` prop and is based on the `Link` component: https://github.com/backstage/backstage/blob/773f3b51ed35e0ad4121f81672126c75d784acd8/packages/core-components/src/components/Button/Button.tsx#L37

### 👟 Reproduction steps

Try to use the `Button` component from `@backstage/core-components`.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by gibsonliketheguitar** [comment]
I'd like to claim this!

**Comment by kurtaking** [comment]
Hey 👋🏼

This caused some confusion for me recently, so I'll do what I can to help out. Is the MVP for this to migrate `Button` to `LinkButton` in `@backstage/core-components`? Do you still want some sort of `Button` component in addition?

**Comment by Rugvip** [comment]
@kurtaking yep thinking deprecation + rename is the first step. Then after removal we could consider reintroducing a button component

**Comment by kurtaking** [comment]
> @kurtaking yep thinking deprecation + rename is the first step. Then after removal we could consider reintroducing a button component

Awesome, I have https://github.com/backstage/backstage/pull/15353 up if you want to take a look. I'll follow up with any discussion there.

**Comment by kurtaking** [comment]
> @kurtaking yep thinking deprecation + rename is the first step. Then after removal we could consider reintroducing a button component

> @kurtaking yep thinking deprecation + rename is the first step. Then after removal we could consider reintroducing a button component

@Rugvip Awesome! 

I have https://github.com/backstage/backstage/pull/15353 up if you want to take a look. I'll follow up with any discussion there.

**Comment by benjdlambert** [comment]
Closing as fixed in #15353
