### ISSUE TITLE
🐛 Bug Report: [Vault-Plugin-Backend] Not able list all the secret fetch request fails

### ISSUE THREAD

**Issue by Sonu875** [backstage/backstage#14880]
### 📜 Description

When making a fetch request it fails to get the secret because the API call to populate the list secret is failing.

### 👍 Expected behavior

api/vault/v1/secrets/<path-to-secret> should return list of secret
![image](https://user-images.githubusercontent.com/30748433/204235049-d6516ffa-6289-42c7-84a3-c12fa1704c37.png)

### 👎 Actual Behavior with Screenshots

API call fails to this error:
![Screenshot 2022-11-28 at 2 27 11 PM](https://user-images.githubusercontent.com/30748433/204235568-ae17c994-31b8-4f8a-9258-4111d575e0f5.png)

### 👟 Reproduction steps

1. Run the backstage in local.
2. Integrate the vault backstage using app-config.yaml
3.  Open PostMan
4. Do a get request to https://localhost:<backstage-port>/api/vault/v1/secrets/<path>
5. Check the error in the logs for the backstage backend

### 📃 Provide the context for the Bug.

This bug is major issue as it defeats the purpose of this plugin.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Looks like `data` does not include `keys`, are you sure the token is correct? I could suggest logging on vault itself to debug. The vault-backend should probably have some additional checking before entering the map and throw an appropriate message to guide the user. CC @ivangonzalezacuna that contributed the plugin.

**Comment by ivangonzalezacuna** [comment]
Yes, that looks like the return object is not the expected one, or that it's empty, and therefore it fails. Adding a check before might be safe then, haven't thought on this edge case at that time. I've seen there's a PR to fix it (https://github.com/backstage/backstage/pull/14881), but anyways, I would add an extra check before, and return an error message or anything similar to display that no keys where found
