### ISSUE TITLE
🐛 Bug Report: AsyncAPI rendering is sometime not working for examples and payload

### ISSUE THREAD

**Issue by mist3r3** [backstage/backstage#14892]
### 📜 Description

When adding a rendering as asyncapi doesn't show example and payload This is the view I get:

![image](https://user-images.githubusercontent.com/16564723/204283658-1c51e8a6-3a47-4520-b0f0-e4594a403bdb.png)

### 👍 Expected behavior

Show payload and example

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/16564723/204283789-3f10f1f3-eb27-4ff5-8bd4-76ad52e5f006.png)

### 👟 Reproduction steps

Create api with asyncapi spec

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Alright, this is not something that I know enough of to give specific guidance at this time. Added a help wanted label for now.
