### ISSUE TITLE
🚀 Feature: Keep quick search open if clicking to open link in a new tab or window

### ISSUE THREAD

**Issue by aitherios** [backstage/backstage#14903]
### 🔖 Feature description

When using quick search if you click on a search result and decide to open it in a new tab or window using <kbd>ctrl</kbd>/<kbd>cmd</kbd> + click or <kbd>shift</kbd> + click closes the quick search dialog. Example:
![Screen Recording 2022-11-28 at 16 22 48](https://user-images.githubusercontent.com/187639/204321526-c01b2389-f4b0-4c5c-8e50-127ae2cb456e.gif)

This feature request argues that a better user experience is keeping the dialog modal open on the original tab.

### 🎤 Context

When using the quick search function is common that multiple results are candidates for what you are searching for. Being able to open tabs for interesting search results without having to re-open the quick search is a better experience.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by efenner-cambia** [comment]
This is a great idea

**Comment by aitherios** [comment]
After the follow up on https://github.com/backstage/backstage/pull/14930 I've written two different proposals for this issue ((option 1)[https://github.com/backstage/backstage/pull/16136] and (option 2)[https://github.com/backstage/backstage/pull/16137]).

On https://github.com/backstage/backstage/pull/14930 it was proposed an inversion of control. Instead of the click handler being responsible for understanding if that event should result in the modal being opened or not the hook could do so by monitoring the url.

Option 1 is just a rebase of the first closed PR. It monitors the click event and checks if keys like ctrl or shift were pressed as a way to check if the user wants to open in a new tab or window. I kept this one due to some considerations on the next draft.

Option 2 accomplishes the same as option 1 but by monitoring the url change it knows when to close the modal by itself. This was done following a suggestion written by @freben on https://github.com/backstage/backstage/pull/14930. This seems a more reasonable solution but I was stuck because it might introduce a breaking change and for that I think I need more feedback on.

Since option 2 assumes the responsibility of closing the modal it has the potential of clashing with a user's implementation that currently relies on calling `toggleModal`. I wish this was the default behavior but to avoid a breaking change this behaviour (auto closing) could be opt in)

**Comment by jhaals** [comment]
Fixed by https://github.com/backstage/backstage/pull/16137 👏
