### ISSUE TITLE
🚀 Feature: Add highlighting of legend item and show bubble on hover (Tech Radar)

### ISSUE THREAD

**Issue by mponss** [backstage/backstage#14924]
### 🔖 Feature description

We would like to have this feature similar than the one provided by [zalando/tech-radar/pull/29](https://github.com/zalando/tech-radar/pull/29), which consist of adding the functionality of highlighting of legend items and showing the bubble on hover in the Tech Radar.

![image](https://user-images.githubusercontent.com/41468474/204501380-2a7df8b1-eb00-4742-8352-43d1bf1ff2ed.png)

### 🎤 Context

In this way, it makes easier to identify the items being checked. You can see the live example here: https://opensource.zalando.com/tech-radar/

### ✌️ Possible Implementation

The PR provided by [zalando/tech-radar/pull/29](https://github.com/zalando/tech-radar/pull/29), can be used as a reference.

As an idea of usage, the feature could be managed by an optional flag through the `TechRadarComponentProps`: https://backstage.io/docs/reference/plugin-tech-radar.techradarcomponentprops

Example:
```
const techRadarComponentProps = {
  width: 1500,
  height: 730,
  highlightLegendItems: true
  }
};
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by freben** [comment]
Alright.

[This PR](https://github.com/backstage/backstage/pull/14038) might be related; there have been issues with rerenders and flickering related to the hover; maybe this needs to be looked at again.
