### ISSUE TITLE
🐛 Bug Report: Github connectivity issue - Could not fetch from Github

### ISSUE THREAD

**Issue by db-cataloge-db** [backstage/backstage#14922]
### 📜 Description

Added the following entry in app-config.yaml file and in 

```
integrations:
  github:
    - host: github.com
      token: <auth_token>
      apiBaseUrl: https://api.github.com
```

![image](https://user-images.githubusercontent.com/115448749/204485230-27dd8cc0-c938-4412-8ce0-21e22b8d0de9.png)

1> Setup the Egress proxy in Openshift Cluster and have whitelisted the Outbound IPs

2> Tested the connectivity between Openshift cluster and Github and it was working fine.

3> Created a <auth_token> in github and execute following, it is working fine. The command is able to download data from into Openshift cluster from Github

**curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer <auth_token>" https://api.github.com/repos/XXXX/YYYY**

4> However when I am trying to access the github endpoint from Backstage application, **it is not working.**

### 👍 Expected behavior

Backstage should be able to connect to Github

### 👎 Actual Behavior with Screenshots

Backstage is not able to connect

### 👟 Reproduction steps

browser log
If I input https://github.com/backstage/backstage/blob/master/catalog-info.yaml then click ANALYZE:

![image](https://user-images.githubusercontent.com/115448749/204486003-4aa7584f-b517-4bf6-900f-d2b23c555901.png)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by freben** [comment]
Your screenshot leaves out what the response and reason was, but maybe I can guess. Seems you are running on localhost, both the frontend on :3000 and then trying to talk to a backend on :7000. Yet you talk about OpenShift. 🤔 Also those are two red request rows; did you press the button twice? I was wondering if the first one was an OPTIONS preflight CORS request but it has a payload so I guess that's not it.

Anyway, seems to me that the first thing to do is to double check the `backend.baseUrl` in your config, and that you're really running the frontend that you think you are. The default port our backends use when on localhost is 7007 as well, not 7000.
