### ISSUE TITLE
🐛 Bug Report: upgrade-helper (diff) misses next versions

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#14939]
### 📜 Description

https://backstage.github.io/upgrade-helper/ only contains main releases and no next releases which makes the upgrade to next releases harder.

### 👍 Expected behavior

https://backstage.github.io/upgrade-helper/ contains the support for next releases, too.

### 👎 Actual Behavior with Screenshots

only contains main releases.

### 👟 Reproduction steps

see https://backstage.github.io/upgrade-helper/

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
@vinzscam Any input here?

I believe we skipped over -next versions intentionally, but don't remember the full context.

**Comment by vinzscam** [comment]
yeah we removed because there were some issues with next releases in the upgrade helper.
So I would see this more as a feature request than a bug report.

**Comment by pjungermann** [comment]
Maybe some additional input:

When upgrading to a next release, we will receive an output like
```
Upgraded from release 1.8.2 to 1.9.0-next.1, please review these template changes:

  https://backstage.github.io/upgrade-helper/?from=1.8.2&to=1.9.0-next.1
```

This link will not work though. Also, there is no real alternative to what the upgrade helper provides besides trying to generate the diff yourself.

Hence, for me this was rather a bug. However, I don't mind if you want to label it differently. Still, I think it is needed to make using next releases at least as easy as main releases.

**Comment by Rugvip** [comment]
Yeah it's not great that the link is broken. Perhaps it makes sense to generate diffs for all the versions, but to hide `next` releases in the UI?

**Comment by pjungermann** [comment]
> but to hide next releases in the UI?

maybe with a toggle as some people might be interested still. At the end, it is a choice whether to use a pre-release version or not.
However, I understand that you want to give more focus/weight to release versions and remove unnecessary clutter for those not interested in them.

**Comment by jhaals** [comment]
Having a toggle for next releases sounds like a good idea 👍 @vinzscam is this something that we could do or clarify for a community member to pick up?

**Comment by vinzscam** [comment]
Closed by https://github.com/backstage/upgrade-helper/pull/11

Note: Only next versions from this current cycle and future ones will show up, we haven't backported older next versions as it would be a bit extra work that we decided not to do unless it was needed.
