### ISSUE TITLE
🐛 Bug Report: `HeaderTabs` have a bad `aria-label`

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#14949]
### 📜 Description

The `HeaderTabs` component seem to render some example `aria-label` made a possible copy paste from Mui docs? 😅 

### 👍 Expected behavior

Either respect the `aria-label` being passed in from outside, or remove entirely, or set to something reasonable.

### 👎 Actual Behavior with Screenshots

https://github.com/backstage/backstage/blob/56b70f2f03d382549096e70169d056838af9d45e/packages/core-components/src/layout/HeaderTabs/HeaderTabs.tsx#L107

### 👟 Reproduction steps

Open the inspector and check the `aria-label`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by linkwithsaurav** [comment]
Can I take up this issue.

**Comment by freben** [comment]
Alright, assigned!

**Comment by valdidar** [comment]
aria-label, with what i understood should describe the function of that element to help visually impaired users.
we could write
aria-label="automatic scroll button"
i am just starting to contribute. are we suppose to discuss the solution to the bug in comments?

**Comment by Rugvip** [comment]
I'd say it's best to switch out the aria label to one that is a generic description of the component. If that's tricky I think we can remove the label instead.

At this point I think it's best to open up a PR with a proposed solution, typically you don't want to get too far into problem solving specifics in issues.
