### ISSUE TITLE
🚀 Feature: Surfacing errors for entities committed via direct ingestion

### ISSUE THREAD

**Issue by taras** [backstage/backstage#14942]
### 🔖 Feature description

One of the benefits of using a `kind: Location` is that we can attach errors to the location of an entity previously emitted from that location. This is especially helpful when the location points to a YAML file which can become improperly formatted. In this case, the parsing error can be attached to the location and shown on the entity page. Similar functionality is missing on Incremental Entity Providers; furthermore, it exposes a limitation of Incremental Entity Providers that may lead to missing data in the catalog.

We need a way to show that an entity previously ingested can not be updated because of an error. Imagine these use cases,

1. An incremental entity provider finds a YAML file and parses it on the first ingestion. This will make the entity available in the catalog as expected.
2. A user edited the YAML file with incorrect formatting.
3. The incremental entity provider runs ingestion again, it finds the file, but it can not parse the YAML document because it's malformed.
4. Since we can not extract the entity from this location, it'll disappear from the catalog. 

Instead, the entity should remain in the catalog, and we should be able to report an error on this entity. 

### 🎤 Context

We're building a GitHub Enterprise ingestion system for one of our clients, which uses direct ingestion without intermediate locations. We're using incremental entity providers to ingest repositories. We want users to be able to take over the management of component metadata by adding a `catalog-info.yaml` file to the repository. Once the file is in the repository, the component becomes managed by that file instead of metadata extracted from the repository.

I want to ensure that we don't lose the entity from the catalog if the user mistakes editing the file.

### ✌️ Possible Implementation

One option may be to provide a way to signal to the ingestion backend that it should reuse previously ingested entities for a given location. We currently return `{ done, cursor, entities}` from an ingestion burst. 

We could include errors with that payload: `{ done, cursor, entities, errors }`. The interface for errors could be something like this,

```ts
interface IngestionError extends Error {
  location: string
  ref?: string
}

type IngestionErrors = IngestionError[]
```

The ingestion backend could use `location` to look up what entities were successfully returned previously for this location. We can filter by the ref if we want to attach errors to only a specific entity at the location. The error would be attached to the previous entity data and committed by the entity provider.

### 👀 Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Frontside can implement this improvement once we agree on the approach.

**Comment by dekoding** [comment]
I like this. Since a location can contain multiple entities, we'd need to make sure this mechanism can differentiate between entities that failed (reusing the existing ones) and entities that succeeded.

You should see #14904 - I think the redesign for the `ingestion_mark_entities` table has a good synergy with this proposal.

**Comment by freben** [comment]
Being able to return errors in a structured way sounds sensible. This way it's easily to exclude them from the final `remove` delta. We'd probably address them by ref for the exclusion purpose, but the location is valuable contextual information.

The problem is that we can't really transmit that error state meaningfully right now. I don't believe you can add an `errors` array to the input entities, and besides, re-submitting with errors would require reading from the catalog again which is a place where we don't want to be because of consistency concerns.

To be able to place these errors on the final entities, we'd have to invent a way for providers to emit error information across the connection.

**Comment by taras** [comment]
> We'd probably address them by ref for the exclusion purpose, but the location is valuable contextual information.

We might not know the refs of the entities that have errors. For example, if you have a `catalog-info.yaml` file that has 3 documents in it and we can't parse the document because it's malformed. We only know the location of this document, but not the documents that were in it previously.

> The problem is that we can't really transmit that error state meaningfully right now.

What if we transmitted errors as `kind: IngestionError`? We could attach error entities as relationships to entities.

> To be able to place these errors on the final entities, we'd have to invent a way for providers to emit error information across the connection.

How about the following,

1. We store location and initial entities returned from a location in Ingestion Backend database table.
2. We allow to return error entities either via `errors` or `entities`
3. When Ingestion Backend encounters an error entity
    1. It checks what entities were discovered previously at that location
    2. It retrieves the previously discovered entity's initial value
    3. It attaches the error to the initial entity via a relationship
    4. It commits both the ingestion error entity and previously ingested entity
4. The initial entity will go through the processing pipeline with errors attached as relationships
5. The UI can show the error attached to the entity
