### ISSUE TITLE
🚀 Feature: SAML Integration for Backstage

### ISSUE THREAD

**Issue by riginoommen** [backstage/backstage#14952]
### 🔖 Feature description

There is some partial support for the SAML in the backend but it's not completely available. I request to redevelop the SAML integration backstage and share it with the community with production readiness

Also update the Docs for the SAML Integration - https://github.com/backstage/backstage/issues/14826

Communication Channel Link - https://discord.com/channels/687207715902193673/1045050111266410639

### 🎤 Context

Integrate SAML login with backstage as auth provider

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by riginoommen** [comment]
https://janus-idp.io/blog/initial-plugins

**Comment by marcindulak** [comment]
This issue is part of https://github.com/backstage/backstage/issues/15999, so I guess it should not be auto-closed.

@Rugvip - maybe the github-actions bot needs improvements so triaged issues are not auto-closed?

**Comment by riginoommen** [comment]
> This issue is part of #15999, so I guess it should not be auto-closed.
> 
> @Rugvip - maybe the github-actions bot needs improvements so triaged issues are not auto-closed?

Yes
