### ISSUE TITLE
🚀 Feature: Configurable document mapping in `DefaultCatalogCollatorFactory` 

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#14961]
### 🔖 Feature description

There have been a variety of proposals and requests for adding fields to to the default collator, including https://github.com/backstage/backstage/issues/5943, https://github.com/backstage/backstage/issues/11407, and https://github.com/backstage/backstage/issues/14530.

Rather than handling these individually, it might make sense to open up the `DefaultCatalogCollatorFactory` to additional configuration so that adopters can make these decisions themselves.

### 🎤 Context

While there are already mechanisms that exist for allowing adopters to supply custom fields, including...

- Registering a decorator that adds fields to documents (which has the disadvantage, in this case, of unnecessarily duplicating data retrieval from the catalog)
- Effectively _forking_ the collator and maintaining it indefinitely (whose disadvantages are self-evident)

...There's clearly a need to be able to extend the Catalog collator.

### ✌️ Possible Implementation

The simplest approach might be configuration-driven.  Adopters could supply a map  whose keys are search document field names and whose values are entity field names.  A bonus of this approach would be that we could supply the given fields (plus the default fields provided by the plugin) to the Catalog Client's `fields` argument, potentially improving resource utilization (memory/bandwidth) in the indexing process.  This might look something like...

```ts
indexBuilder.addCollator({
  schedule,
  factory: DefaultCatalogCollatorFactory.fromConfig(env.config, {
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    fieldMap: {
      imageUrl: 'spec.profile.picture',
      name: 'metadata.name',
      annotations: 'annotations',
    },
  }),
});
```

Another approach would be to allow adopters to provide a mapping _function_ to do more or less the same.  Benefits to this approach are the ability to supply conditional logic, as well as perhaps simpler type safety handling.

```ts
indexBuilder.addCollator({
  schedule,
  factory: DefaultCatalogCollatorFactory.fromConfig(env.config, {
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    mapDocument: (entity: Entity): CatalogEntityDocument => ({
      imageUrl: entity.spec?.profile?.picture,
      name: entity.metadata.name,
      annotations: entity.annotations,
    }),
  }),
});
```

^ Although care should be made to prevent adopters from doing things they shouldn't (e.g. this function should not be allowed to be asynchronous).

In either case: we will need to consider how we merge the values defined by adopters with the default values provided by the collator already (which we should maintain for backwards compatibility).  Do the custom mappings override the defaults?  Do we only allow net-new values?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by emmaindal** [comment]
Awesome! The only thing that comes to mind - `default` vs `custom`. And I wonder if we should keep the `default` as it is, and have a custom version where all you specified is possible. Or that it should just be “CatalogCollator” if its not a default one anymore.
