### ISSUE TITLE
🚀 Feature: OwnerPicker to support filtering entities by `spec.type`

### ISSUE THREAD

**Issue by rikez** [backstage/backstage#14979]
### 🔖 Feature description

The scaffolder built-in component [`OwnerPicker` only supports filtering entities by `kind`](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/EntityPicker/EntityPicker.tsx#L54). We would like to be able to filter entities by `spec.type`.

### 🎤 Context

In my use-case we have created various Scaffolder Templates to create Git repositories and other resources. Part of this process is to define an owner for these repositories and resources, and so we use the `OwnerPicker` component.

The problem we're facing at the moment is that we started defining `Group` entities to map **business units**, **pillars** and **organizations** besides **teams**. We're using the field `spec.type`  to distinguish these Group entities. With the addition of these groups, they are now being displayed in the `OwnerPicker` dropdown as an option. However, for some templates it doesn't make sense a **business unit** to be an option. For example, a git repository should be owned by a team (`kind: Group`, `spec.type: team`) because we're mapping these teams 1:1 with GitHub teams (CODEOWNERS). 

To get this feature out faster in our Backstage instance, we temporarily created a custom OwnerPicker that supports this feature, but we would love to contribute and enhance the existing component.

### ✌️ Possible Implementation

[EntityPicker](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/EntityPicker/EntityPicker.tsx#L54)
```ts

type EntityPickerProps = {
  ...
  allowedTypes?: string[];
  ...
}

export const EntityPicker = (props: EntityPickerProps) => {
  ...
  
  const allowedKinds = uiSchema['ui:options']?.allowedKinds;
  const allowedTypes = uiSchema['ui:options']?.allowedTypes;
  ...
  
  const filter: GetEntitiesRequest['filter'] = {};

  if (allowedKinds) {
    filter['kind'] = allowedKinds;
  }
  if (allowedTypes) {
    filter['spec.type'] = allowedTypes;
  }

  const catalogApi = useApi(catalogApiRef);

  const { value: entities, loading } = useAsync(() =>
    catalogApi.getEntities(
      Object.keys(filter).length > 0 ? { filter } : undefined,
    ),
  );

```
[OwnerPicker](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/OwnerPicker/OwnerPicker.tsx)
```ts

type OwnerPickerProps = {
  ... 
  allowedTypes: string[]
 ...
}

export const OwnerPicker = (props: OwnerPickerProps) => {
 ..

  const ownerUiSchema = {
    ...uiSchema,
    'ui:options': {
      ...
      allowedTypes: uiSchema['ui:options']?.allowedTypes,
      ...
    },
  };

  return (
    <EntityPicker
      {...restProps}
      schema={{ title, description }}
      uiSchema={ownerUiSchema}
    />
  );
};
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Note that not all kinds have types (especially when you account for orgs making customisations to the catalog model), and it might be confusing to specify an `allowedTypes` then. "I specified `team` in the allowed types and now it no longer shows users in the list" for example.

Maybe we've reached the point where it's better to let users specify a `catalogFilter: ...` instead, [on the shape](https://github.com/backstage/backstage/blob/774c42003782121d3d6b2aa5f2865d53370c160e/packages/catalog-client/src/types/api.ts#L74) that you can pass into the catalog client. That way you can slice out any subset of the catalog that you like, to show in there.

Happy to assign you to the issue if you feel up to adding that!

**Comment by rikez** [comment]
@freben That makes sense. 

Feel free to assign to work to me. Going to start this soon.

**Comment by rikez** [comment]
@freben Opened a PR with the proposed changes. Would appreciate any feedback.

**Comment by rikez** [comment]
@freben should we close this?

**Comment by jhaals** [comment]
Yes, thanks!
