### ISSUE TITLE
🚀 Feature: search engine supports in-house opensearch .

### ISSUE THREAD

**Issue by jinnjwu** [backstage/backstage#14987]
### 🔖 Feature description

search enginer supports in-house opensearch .

### 🎤 Context

search enginer supports in-house opensearch .

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jinnjwu** [comment]
https://github.com/backstage/backstage/pull/14988/files

**Comment by iamEAP** [comment]
Thanks for the report and the contribution!  Closing this out, as it should now be possible (as of Backstage v1.9.0): https://github.com/backstage/backstage/pull/15174#issuecomment-1348488035
