### ISSUE TITLE
Search functionality in Backstage

### ISSUE THREAD

**Issue by shashirsu** [backstage/backstage#1499]
## Feature Suggestion

* Add federated search functionality to search tech documents, [data catalog items](https://github.com/spotify/backstage/blob/0ba4cca3c8dbffe95b8877a2bf14c3704afce02c/docs/architecture-decisions/adr002-default-catalog-file-format.md), templates served through the backstage portal.

## Possible Implementation

* User Interface i.e., Search Results UI - Should this be implemented as a plugin in Backstage?
* Search backend available as an API 
* Federated Search
    * Search all contents simultaneously and then categorize under each of them (e.g., Catalog, FAQ, ADR, etc.)
* Implementation of crawler component - How will the content be submitted to the backstage search engine? Most complex to implement as we need to crawl through multiple different catalog backends? - database, s3, google cloud storage, web content types i.e., as defined below (Techdocs, APIs, FAQs, Articles, How TOs, etc.)
* Index content on publish or when new items are added/updated in the catalog
* Most would use the out of the box search implementation, but some might have an internal Search Engine they may want to use. So a pluggable search implementation would be proper.

Possible implementation ideas:
* Possible search backend implementations - Elasticsearch, [MeiliSearch](https://github.com/meilisearch/MeiliSearch), [Sonic](https://github.com/valeriansaliou/sonic)
* Search can be implemented in the frontend, but only for local Techdoc site content using [Lunr](https://github.com/olivernn/lunr.js)

Questions:
* Crawler for finding docs from different locations i.e., s3 buckets, filesystem, blob store, etc. for Techdocs, catalog backend (Github, GitLab, etc.) - custom?
* How will the locations to be crawled be submitted to the Backstage crawler?
* Should search be exposed as a plugin?

## Context

* Backstage needs to search across structured data (data catalog) and unstructured data (tech docs) to locate content quickly.
* Search is required across following:(not exhaustive)
    * Technology documentation (External)
    * Technology documentation (Internal)
    * FAQs
    * Tutorials
    * Articles
    * How-To Guides
    * ADRs
    * API Documentation
    * Catalog Components 
* Based on the [Backstage System Model](https://github.com/spotify/backstage/issues/390), the need to restrict searches to a specific context will be helpful to the users. Documentation would be maintained across Domain, Systems, Components, and APIs. It's better to keep this in a federated manner in individual S3 buckets rather than creating a central bucket and have teams publish the docs based on a pre-defined structure. 
* Consider the following example:
    * Domain - **Public Cloud**, Private Cloud, Tools Platform, Business Domain i.e., Playlists
    * Systems - **AWS**, Azure, Google Cloud
    * Components 
       **Custom Terraform Modules** (Code and documentation owned and maintained by multiple teams) 
*  The user would like to query for specific functionality (standardized RDS module based on organizational security standards) implemented for AWS Cloud (i.e., System boundary) rather than across all domains and retrieve the documents.

**Comment by Rugvip** [comment]
Internally we have an Elasticsearch cluster that is essentially indexes the contents of the software catalog + tech-docs. I don't think we want to jump on that solution straight away though. Most likely we start off by defining a frontend search API that we back be an in-memory index in the frontend, and/or a simple endpoints in the backend.

**Comment by garyniemen** [comment]
Watching this discussion. During Q3, we are planning to work on Search. Our team within Spotify, Pulp Fiction, are down to take over Backstage Search from @Rugvip 's team, Tools. Our scope is Discoverability and there is a large need to solve Search internally. Will share when we know more.

**Comment by stefanalund** [comment]
> Most likely we start off by defining a frontend search API that we back be an in-memory index in the frontend, and/or a simple endpoints in the backend.

I think this is the way to go for the initial version of search.

**Comment by iammuho** [comment]
Is there any progress on this issue ? When the docs search will be released?

**Comment by freben** [comment]
@garyniemen ^

**Comment by freben** [comment]
See also discussion on Discord: https://discord.com/channels/687207715902193673/714754240933003266/768762581635563550

**Comment by stefanalund** [comment]
@emmaindal perhaps you have some teasers to share from your hack project? 😏

**Comment by freben** [comment]
Or indeed @Nek !

**Comment by benjdlambert** [comment]
See #3086 for more details!

**Comment by emmaindal** [comment]
Oh haven't seen this! Thanks for sharing the PR here @benjdlambert

**Comment by stefanalund** [comment]
@emmaindal what do you think about closing this "umbrella" issue for search? The basic functionality is now implemented.

**Comment by emmaindal** [comment]
@stefanalund yes, I was planning to write up an RFC for a potential backend search plugin but it will hopefully be more of a priority during Q1 for us so lets close this for now and I'll come back to this!
