### ISSUE TITLE
Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process.

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#15003]
### 📜 Description

During the deployment to UAT, I got following error(screenshot). I am not sure, How can we optimize backstage?
I have 2000 apis on backstage and 4 core cpu and 4 GB RAM for 1 pod. But still my application breaks on api page. 

Is there any way, if we can improve this?

![image](https://user-images.githubusercontent.com/225961/205397556-689bb1c4-cb02-4c6d-af97-15451af7eb72.png)

### 👍 Expected behavior

It should not take too much memory. 

### 👎 Actual Behavior with Screenshots

Please see screenshot.
![image](https://user-images.githubusercontent.com/225961/205399091-c5886711-690d-4274-9d6d-ca22fd73bd44.png)

### 👟 Reproduction steps

Step 1: Add 2000 apis in api catalog.
Step 2: Open api page
Step 3: then open catalog page
Step 4: repeat same for few time.
Step 5: you will see the memory issue.

### 🖥️ Your Environment

QAT and UAT

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by lalit774** [comment]
https://github.com/backstage/backstage/discussions/7578

**Comment by freben** [comment]
I'm pretty sure that the MemoryStore message isn't a culprit at least. The catalog just allocated too much memory as part of its normal operation, I suspect.

The views currently load everything in one huge request. Both the frontend and the backend bear the burden of loading every single item, without pagination. This is probably at the root of the issue. See the performance section [in this issue](https://github.com/backstage/backstage/issues/14574) for some links to ongoing and future work in this area.
