### ISSUE TITLE
🐛 Bug Report: [Scaffolder] stops eventstream refresh in the page after disconnect

### ISSUE THREAD

**Issue by angeliski** [backstage/backstage#15002]
### 📜 Description

We have some users complaint about the time a task needs to finish. After some investigation we discover the task is finishing, but the UI isn't showing this information. A simple F5 resolves the problem, because the task is running at the backend

### 👍 Expected behavior

I expected after the task completed, this information is shown to the end user

### 👎 Actual Behavior with Screenshots

The user starts the process to create a new service and receive a error without any message. Just a yellow banner.

![image](https://user-images.githubusercontent.com/1574240/205384631-2f4a4c6e-2472-4778-9ff9-e29413e9dc30.png)

After a really long time the users give up
![image](https://user-images.githubusercontent.com/1574240/205384766-1d4482c4-9b15-4c1d-a62f-27fdf28d5958.png)

But in reality, the task is over a long time ago (with error in this case, but could successed)
A refresh in the page shows the result
![image](https://user-images.githubusercontent.com/1574240/205384834-8103025f-ba15-44a2-9980-20ec2008c809.png)

### 👟 Reproduction steps

1. Start a task in Scaffolder
2. Create a disconnection from the Backend (in my case I turned off the wifi), locally you can shutdown the backend only
3. Reconnect your Front-end (the stream will get logs again)
![streamlogs](https://user-images.githubusercontent.com/1574240/205385388-9431ce50-7be0-4087-9dcf-79df63b2ab59.png)
4. The front-end will stay in progress forever

### 📃 Provide the context for the Bug.

We are getting some issues with that because our users are running VPN some times, and when they connect (or disconnect) using the scaffolder they got stuck waiting for the UI success.

I dig a little and found the problem:

When a problem happens in the `EventSource` we send a `error` event for the subscriber ([here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/api.ts#L269)). 
The problem is: `zen-observable` understands this is a moment to close the operation ([here](https://github.com/zenparsing/zen-observable/blob/master/src/Observable.js#L111)), so our `EventSource` is waiting for a reconnection, but the subscriber isn't listenning anymore.

I was thinking about `skip` the error from the Observable and only use the `next` function:
```typescript
// emit
eventSource.addEventListener('error', event => {
  subscriber.next({ type: 'fail', error: event});
});

//handle
subscription = observable.subscribe({
    next: event => {
      console.log('ev',event)
      switch (event.type) {
        case 'log':
          return collectedLogEvents.push(event);
        case 'completion':
          emitLogs();
          dispatch({ type: 'COMPLETED', data: event });
          return undefined;
        case 'fail':
          emitLogs();
          dispatch({ type: 'ERROR', data: event.error });
          return undefined;
        default:
          throw new Error(
            `Unhandled event type ${event.type} in observer`,
          );
      }
    }
  });
```
In this case, when I have a new "good" event, the subscriber is listening to the change

### 🖥️ Your Environment

yarn run v1.22.18
$ /home/ROGERIO.ANGELISKI/workspace/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.14.0-1054-oem - linux/x64
node: v16.14.0
yarn: 1.22.18
cli:  0.21.1 (installed)
backstage:  1.8.2

Dependencies:
  @backstage/app-defaults                               1.0.8
  @backstage/backend-common                             0.16.0
  @backstage/backend-plugin-api                         0.1.4
  @backstage/backend-tasks                              0.3.7
  @backstage/catalog-client                             1.1.2
  @backstage/catalog-model                              1.1.3
  @backstage/cli-common                                 0.1.10
  @backstage/cli                                        0.21.1
  @backstage/config-loader                              1.1.6
  @backstage/config                                     1.0.4
  @backstage/core-app-api                               1.2.0
  @backstage/core-components                            0.11.2, 0.12.0
  @backstage/core-plugin-api                            1.1.0
  @backstage/errors                                     1.1.3
  @backstage/integration-react                          1.1.6
  @backstage/integration                                1.4.0
  @backstage/plugin-analytics-module-ga                 0.1.22
  @backstage/plugin-api-docs                            0.8.11
  @backstage/plugin-app-backend                         0.3.38
  @backstage/plugin-auth-backend                        0.17.1
  @backstage/plugin-auth-node                           0.2.7
  @backstage/plugin-catalog-backend-module-github       0.2.1
  @backstage/plugin-catalog-backend                     1.5.1
  @backstage/plugin-catalog-common                      1.0.8
  @backstage/plugin-catalog-graph                       0.2.23
  @backstage/plugin-catalog-import                      0.9.1
  @backstage/plugin-catalog-node                        1.2.1
  @backstage/plugin-catalog-react                       1.2.1
  @backstage/plugin-catalog                             1.6.1
  @backstage/plugin-circleci                            0.3.11
  @backstage/plugin-github-actions                      0.5.11
  @backstage/plugin-github-issues                       0.2.0
  @backstage/plugin-github-pull-requests-board          0.1.5
  @backstage/plugin-home                                0.4.27
  @backstage/plugin-org                                 0.6.0
  @backstage/plugin-pagerduty                           0.5.4
  @backstage/plugin-permission-common                   0.7.1
  @backstage/plugin-permission-node                     0.7.1
  @backstage/plugin-permission-react                    0.4.7
  @backstage/plugin-proxy-backend                       0.2.32
  @backstage/plugin-rollbar-backend                     0.1.35
  @backstage/plugin-rollbar                             0.4.11
  @backstage/plugin-scaffolder-backend-module-rails     0.4.6
  @backstage/plugin-scaffolder-backend                  1.8.0
  @backstage/plugin-scaffolder-common                   1.2.2
  @backstage/plugin-scaffolder                          1.8.0
  @backstage/plugin-search-backend-node                 1.0.4
  @backstage/plugin-search-backend                      1.1.1
  @backstage/plugin-search-common                       1.1.1
  @backstage/plugin-search-react                        1.2.1
  @backstage/plugin-search                              1.0.4
  @backstage/plugin-stack-overflow                      0.1.7
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.22
  @backstage/plugin-tech-insights-backend               0.5.4
  @backstage/plugin-tech-insights-common                0.2.8
  @backstage/plugin-tech-insights-node                  0.3.6
  @backstage/plugin-tech-insights                       0.3.3
  @backstage/plugin-tech-radar                          0.5.18
  @backstage/plugin-techdocs-backend                    1.4.1
  @backstage/plugin-techdocs-module-addons-contrib      1.0.6
  @backstage/plugin-techdocs-node                       1.4.2
  @backstage/plugin-techdocs-react                      1.0.6
  @backstage/plugin-techdocs                            1.4.0
  @backstage/plugin-user-settings                       0.5.1
  @backstage/release-manifests                          0.0.7
  @backstage/test-utils                                 1.2.2
  @backstage/theme                                      0.2.16
  @backstage/types                                      1.0.1
  @backstage/version-bridge                             1.0.2
Done in 0.42s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Thanks for looking into the problem so carefully! Ping @benjdlambert

Hmmmm. I see what you are saying with the diagnosis, but I'm not sure it correlates with the disconnection thing you mention. Like, if an error is signaled, it SHOULD be safe to disconnect because the remote is done, right? But then it seems that this happens "too soon", so that the rest of the logs including the actual error condition haven't been emitted yet? So the alert box has nothing to display and the error can't be seen in the log itself.

Maybe it's something like that instead, that it needs to make sure to "pump" the last bits of state before erroring out?

**Comment by freben** [comment]
(essentially i'm also wondering ... IS there even any reconnection logic in the first place, but even if there is or isn't, it may be kind of a separate to the issue at hand?)

**Comment by benjdlambert** [comment]
So looks like it is reconnecting right? but maybe the subscription to the observable gets lost after the disconnect? Not really sure what's happening to be honest. Do you mind digging a little deeper @angeliski and maybe raising an issue with a suggested fix so we can discuss it a little more there?

**Comment by angeliski** [comment]
I will try to explain for a different angle, maybe helps. The `EventSource` is ok, we got a disconnection (emit `error`), and after some time a reconnection from the backend (`logs` are back).

But when the `Observable` listenens the error(from the disconnect), they stop listening the `EventSource` events.

Some time after that, the `EventSource` comes back (reconnect) but the `Observable` stopped from listenning all events.

@freben we "pump" the logs before disconnect [here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/hooks/useEventStream.ts#L194)

I draw this to show to my team, could help.

![event flow](https://user-images.githubusercontent.com/1574240/205675483-0f2f53f4-7877-43c2-86b8-bfccf6ea57a4.png)

My example is bad, because it is a error after a error, but for most cases we got success after the disconnection.

In most of the cases, a `error` should be terminal: we don't need to update the UI anymore. But for the disconnection error, we need to update the UI if the backend comes back.

I will open a PR (probably next week) so we can discuss a bitter more

**Comment by freben** [comment]
PIng @angeliski did you ever get the time to look into a fix for this?

**Comment by angeliski** [comment]
Sorry @freben got a new year and chaos between this, but I will raise a PR soon

**Comment by eltonwelsch** [comment]
Hi @angeliski, thanks for the update. We are also in the same situation, but I will try to fit this demand into our backlog.

**Comment by gocapa** [comment]
Hi @angeliski what if there is inactivity for more than 45 seconds and more than 3 times? this would lead to the same problem right? Is there anyway these timeout values can get parameterized via configuration?
