### ISSUE TITLE
🚀 Feature: Export `isBazaarAvailable` helper function in bazaar plugin

### ISSUE THREAD

**Issue by stephanschielke** [backstage/backstage#15013]
### 🔖 Feature description

Introduction of an exported `isBazaarAvailable` helper function:

`isBazaarAvailable` should return `true` if the `entityRef` can be found by `bazaarClient.getProjectByRef(entityRef)`.

### 🎤 Context

By exposing a helper function `isBazaarAvailable` the user of the plugin and cards is able to easily use `EntitySwitch`:

```
    <EntitySwitch>
      <EntitySwitch.Case if={isBazaarAvailable}>
        <Grid item>
          <EntityBazaarInfoCard/>
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>
```

### ✌️ Possible Implementation

Currently, the user is forced to get the bazaar API, to get to the private `bazaarClient` to utilize the private `getProjectByRef` function for this:

```
interface BazaarClient {
  getProjectByRef(entityRef: string): Response
}

async function isBazaarAvailable(entity: Entity, context: { apis: ApiHolder; }): Promise<boolean> {
  const bazaarApiRef = bazaarPlugin.getApis()[Symbol.iterator]().next().value
  const bazaarClient: BazaarClient | undefined = context.apis.get(bazaarApiRef.api.config)
  if (bazaarClient === undefined) {
    return false
  }
  const entityRef = stringifyEntityRef({
    kind: entity.kind,
    name: entity.metadata.name,
    namespace: entity.metadata.namespace,
  });
  const response = await bazaarClient.getProjectByRef(entityRef)
  const project = await response.json()
  return project.data.length > 0
}
```

Exporting a helper function `isBazaarAvailable` could avoid having to find all the above private information.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Sure, that sounds like it would work. The Case [if function](https://github.com/backstage/backstage/blob/774c42003782121d3d6b2aa5f2865d53370c160e/plugins/catalog/src/components/EntitySwitch/EntitySwitch.tsx#L32) is given an `ApiHolder` as a context so it should be able to reach the required API instance and make some calls.
