### ISSUE TITLE
🐛 Bug Report: Missing required config value at 'azureSites'

### ISSUE THREAD

**Issue by GVelnicu** [backstage/backstage#15015]
### 📜 Description

For the https://github.com/backstage/backstage/tree/master/plugins/azure-sites-backend plugin ,filling out the .yaml file with the required information(redacted for screenshots), it is unable to read the azure details and start the backend : 
![image](https://user-images.githubusercontent.com/112381119/205602206-0aea7ca8-2c3d-4475-915b-85a5ce9397e5.png)

I have tried filling in the azure sites in a couple of ways, as presented in the readme with : 
azureSites:
  domain:
  tenantId:
  clientId:
  clientSecret:
  allowedSubscriptions:
    - id:
  
and trying to match the above format from git (see screenshots)
![image](https://user-images.githubusercontent.com/112381119/205602421-8b474179-149c-4709-aa11-cd856940ddff.png)
and
![image](https://user-images.githubusercontent.com/112381119/205601854-ec67d0b3-8373-46c3-bae7-3dafdb774507.png)

### 👍 Expected behavior

It should be able to open http://localhost:7007/api/azure/health in a browser, it should return {"status":"ok"}

### 👎 Actual Behavior with Screenshots

It currently fails to start the backend citing a failiure to read the azure sites details 
![image](https://user-images.githubusercontent.com/112381119/205603563-6c37c9c5-d759-442e-9a73-c2fc0459e81a.png)

### 👟 Reproduction steps

-Fill in the app-config.yaml with the required azure information.
-Start the backend.

### 🖥️ Your Environment

This is being run on a linux VM in microsoft Azure.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Sonu875** [comment]
Can you try with config something like this:
`azureSites:
  domain:
  tenantId:
  clientId:
  clientSecret:
  subscriptions:
    - id:`

**Comment by GVelnicu** [comment]
Sorted.
