### ISSUE TITLE
🚀 Feature: Catalog Inspection

### ISSUE THREAD

**Issue by freben** [backstage/backstage#15021]
### 🔖 Feature description

There should be an inspection feature of the catalog, that allows for the detection and resolution of bad / unexpected / hard-to-diagnose situations. This may include unprocessable entities that never appear in the output, misbehaving sets of entity references, and much more. This would be a feature that is mainly targeted at operators and particular advanced catalog users, aiding in the resolutions of internal problems or on behalf of others, and replacing manual digging through the database layer.

### 🎤 Context

There are cases where it can be challenging to understand why a certain problem manifests itself in the catalog, and there is fairly little tooling to help operators resolve them. Sometimes we ask operators to manually look at the database and logs, which aren't always readily available to inspect. This proposal hopes to build support structures for those "fringe"/advanced situations, by allowing some level of organised peeking into the box that lies between original input data and the outputs.

### ✌️ Possible Implementation

Develop a dedicated frontend and backend for advanced inspection cases.

#### Target Persona

The primary target persona is a Backstage operator at an adopter organisation. They are expected to be fairly familiar with catalog concepts as understood from the documentation. They are, however, not necessarily familiar with database operations or the deep technical innards of the catalog. They want to ensure the smooth operation of the catalog, aid their own catalog end users to get their data safely in place, and provide technical information to support personnel on demand to help diagnose issues.

The desired user interface is a set of web pages, inside Backstage itself. It may or may not be possible to reach by non-operator personas; likely covered by the permissions framework. It is powered by a backend REST API. The interface will likely be of a technical nature, and should not end up being a necessary part of end user workflows. Their needs should instead be met through additions in the regular parts of the user interface, by means that are intentionally not covered in this ticket. If parts of this ticket end up proving useful for end users, then that can be "graduated" to that purpose at a later time, after maturing and reaching stability.

#### Proposed Features

In its barest form, this could have been implemented in the form of a pure, one-to-one, navigator of the database structure. But to provide real value, I believe it should instead perform more specific inspections that may require composed or complex queries to deduce, and presenting them in an understandable way to the operators.

These are some of the features that might be useful to expose as part of this interface. If you have moire ideas, please do suggest them.

1. The list of currently installed entity providers
2. The list of currently installed processors and the order that they are in
3. When we implement better observability (error reporting / logging / event emitters / health checks, or whatever we come up with) from entity providers and processors, this would be a good home for being able to inspect that
4. Listing entries in `refresh_state` that do not have a corresponding `final_entities` entry (with or without errors)
5. Listing "root" entities that are referencing an entity provider that isn't currently installed
6. Listing entities that have a broken reference / ancestor chain (don't seem properly anchored, and therefore should have been deleted)
7. Searching through the database by more technical filters, such as by location URL prefix (trying to diagnose issues in a certain org / repo for example), full entity ref, etc
8. Insights around the processing loop, e.g. max / avg / median / min time since entities were last processed etc, to help understand congestion levels

In some of the views above, the operator should likely be offered the ability to delete offending entities as well, and/or mark them for refresh, clear out their hashes to trigger processing or stitching, etc.

#### How it's Installed

These will be power user APIs, that one may desire to have stricter control over. It may be useful to make the backend parts optional, e.g. having to choose to install them, or at least bing possible to enable/disable through config. At the same time they will by their very design need low level access to the catalog tables.

The internal database structure was always meant to behave like a black box. This enables us to iterate on the catalog innards more freely without breaking contracts. The inspection APIs offer views into the data that may be "closer to the metal" than the regular APIs. Therefore, it would be prudent to create them with weaker guarantees than the regular public API (which is on version 1.x, and hence must obey semver).

We could create the backend parts in the form of a catalog backend module `@backstage/plugin-catalog-backend-module-inspection`, which happens to access the same database tables as the catalog itself. This is normally not recommended, but we would in this case let the module have a form of elevated status that makes it be essentially part of the core offering but separated out only for technical reasons. We would also have to solve where the corresponding frontend bits would live - in the catalog itself as part of the core offering, or separately?

Alternatively, we could add the API in the catalog backend itself (maybe in a very distinctly named route like `/_private` or `/_unstable` and just bear in mind that parts of it does NOT affect semver.

#### Risks

_Scope creep:_ The intended scope is to help operators with difficult corner use cases. It will not be constructed in such a way that its results are readily digestible or actionable by end users. There is a risk that this tool starts getting conflated with intended end user flows or opened up to everyone, which may be less helpful than hoped. We may try to counter this with proper documentation and not surfacing it by default.

_Being the wrong solution:_ There is a risk that this tool ends up being a fair bit of effort to produce and maintain, when there might be things to improve that are more directly in the user flows that better helps them. I do think that a tool like this is useful and needed for the catalog _as it is today_, and hopefully bits and learnings from this tool will be incorporated in user flows in the future, in more user friendly forms, once they mature.

_Maintenance:_ This touches "hidden" parts of the database more directly in the request path. This presents an additional maintenance burden and may slightly slow down feature development since there's an entire new surface to take into account when iterating on the internal models.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
@freben, thanks for putting your thoughts down on this subject. As someone who doesn't have access to our database once Backstage is deployed any tooling/support in this area will be really helpful. 

For the UI side of this do you think maybe the DevTools plugin #14642 could be a good starting place? It's designed to easily add parts like this and the permissions framework is also in place. Might not be the only place we'd want this but would give us a bit of a head start
