### ISSUE TITLE
💬 RFC: passport-saml v3 deprecated in favor of @node-saml/passport-saml v4

### ISSUE THREAD

**Issue by graynk** [backstage/backstage#15020]
### 🔖 Need

Already mentioned in #14112, but figured I should create a separate issue.
`passport-saml` depends on vulnerable version of `@xmldom/xmldom`, see here: https://github.com/advisories/GHSA-crh6-fp67-6883

But we can't just update the version of transitive dependency in our Backstage instance, because there it seems like there are some breaking changes between 0.7 and 0.8 versions of xmldom.
`passport-saml` did update to 0.8 version in version 4. But we also can't just bump the version of `passport-saml`, because they have published v4 as `@node-saml/passport-saml`, [deprecating](https://www.npmjs.com/package/passport-saml) `passport-saml` in the process.

### 🎉 Proposal

Replace `passport-saml` with `@node-saml/passport-saml` in plugin-auth-backend

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by graynk** [comment]
@SaumyaBhushan yep, but I'm not sure if there were any breaking changes or not. It's a major version bump, but I didn't see anything about the breaking changes in the [changelog](https://github.com/node-saml/passport-saml/blob/master/CHANGELOG.md)

**Comment by SaumyaBhushan** [comment]
Ok so Can I work on this one ?

**Comment by graynk** [comment]
@SaumyaBhushan it's not up to me to decide, I just opened the issue :)

I'd like to get some of the codeowners to chime in on this, but I'm not sure who owns backend-auth plugin. @freben or @Rugvip, maybe?

**Comment by SaumyaBhushan** [comment]
No issue @graynk

**Comment by Rugvip** [comment]
@SaumyaBhushan sure! For any work on this issue it's good to keep #14952 in mind, that is the current SAML implementation isn't production ready. Don't expect a complete implementation, but also if you want to fill in the gaps, like session storage, that would be valuable too. Either way I suggest doing this bump first.

**Comment by riginoommen** [comment]
https://janus-idp.io/blog/initial-plugins
