### ISSUE TITLE
🐛 Bug Report: Yarn 3 migration issue after migrating from 1.4.0 to 1.8.2

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#15053]
### 📜 Description

Our upgrade process doesn't use backstage-cli, rather git clone and then we use only those plugins and packages which are relevant for us. This is mainly because we have extended the capability of some of the community plugin such as explore/catalog/scaffolder etc.

Followed the process as per https://github.com/backstage/backstage/blob/v1.8.2/docs/tutorials/yarn-migration.md to migrate to use yarn 3.

When I do yarn install after some of the steps followed gives the below error.

![image](https://user-images.githubusercontent.com/86959288/206003542-ad9da65b-eaab-4c00-82fc-946a1622e350.png)

How do we actually resolve the "workspace:^" versioning of the backstage plugins on 1.8.2?

### 👍 Expected behavior

As Above

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/86959288/206003647-b1fa7d7c-c880-4295-8316-3e73544e92f8.png)

### 👟 Reproduction steps

As Above

### 📃 Provide the context for the Bug.

As Above

### 🖥️ Your Environment

As Above

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
Sorry you're going to be mostly on your own with this one. The clone workflow isn't something that we support, I strongly recommend using `npx @backstage/create-app` instead and adding copies of any packages you want to override.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Understood. Thanks or this. I have changed all the versions to be absolute versions and it worked.
