### ISSUE TITLE
🐛 Bug Report: location-analyzer returns an internal server error 500 when analyzing fails

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#15051]
### 📜 Description

The `POST /api/catalog/analyze-location` returns a 500 error code when the analyzing fails. 500 indicates that the server has failed. Whereas this is simply the analyzing failing.

### 👍 Expected behavior

 It should have a known response code for this or include the status of the analyzing to the body of the response as a 200 code.

### 👎 Actual Behavior with Screenshots

It returns 500 internal server error.

### 👟 Reproduction steps

Provide a badly formatting catalog-info.yaml file to the analyze-location api

### 📃 Provide the context for the Bug.

500 errors should be reserved for when an unexpected error occurs. I would not consider this one an expected error.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by kissmikijr** [comment]
@Rugvip  Can you assign this to me?

**Comment by freben** [comment]
Assigned.

**Comment by punkle** [comment]
This is still an issue.
