### ISSUE TITLE
🔌 Plugin: Betterscan.io Security Automation Software plugin (Uses many Open Source tools for scanning Code and Cloud)

### ISSUE THREAD

**Issue by marcinguy** [backstage/backstage#15054]
### 🔖 Summary

I made first stab at the plugin, it could show at first Security posture of scanned project across the organization with badges (you just need to get Bearer token and running Betterscan Platform)

More here:
https://github.com/marcinguy/backstage-plugin-betterscan

### 🌐 Project website (if applicable)

https://github.com/marcinguy/betterscan-ce

https://betterscan.io

### ✌️ Context

Betterscan is a simple and powerful software to automate thousands of checks (orchestration) and eliminate human errors in Code and Cloud Infrastructure. Our software uses multiple very known and state of the art Open Source components as plugins (in that sense it is a "wrapper", "Meta" scanner) and provides you with unified one report and very fast results due to using of project state (no need to rescan the whole project every time) and unification (no duplicates). Software is very modular and any Open Source tool or proprietary check can be added as a plugin. Supports all major Programming languages and Cloud technologies. Software is available as Open Source in Community Edition and paid Professional/Business variants.

It is a useful project and having it in Backstage to show project findings/security posture could be nice.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Cool! Do you plan to keep working on the plugin? Once it's ready you could [add it to backstage.io](https://backstage.io/docs/plugins/add-to-marketplace)

**Comment by marcinguy** [comment]
@Rugvip Awesome! Yes, I plan to max out my TS skills and make it useable. Now stuck at making a npm package from the source.

I also think to maybe build new Frontend with Backstage.

Contributors, with better skills, to help, bounce off ideas are always welcome 😊

P.S Thank you for positive and welcoming message

**Comment by marcinguy** [comment]
FYI @Rugvip Made a PR to add it to Marketplace:

https://github.com/backstage/backstage/pull/15128

I hope that is what you meant

**Comment by Rugvip** [comment]
@marcinguy thanks! 👍, gonna close this since it's added
