### ISSUE TITLE
🚀 Feature:  To download template created in backstage 

### ISSUE THREAD

**Issue by ghost** [backstage/backstage#15078]
### 🔖 Feature description

In backstage template creation feature we can choose template then fill some details and it will push it to repository on github/bitbucket. instead there should be option to newly created repository to be downloaded by the user.

### 🎤 Context

Organisation does not support repositpory creation by employees, they have to raise a ticket and someone will create a repo to github/bitbucket/gitlab. 

so instead user should have option to download the template, so locally they can play with that.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by punkle** [comment]
The `publish:github` step provides an output `remoteUrl` which refers to the repo that has been created.

**Comment by Va-asu** [comment]
yeah you are right, that defines it can publish on github, if it is been removed then we cant publish on github... but the question is how to download locally that template in local system.

**Comment by punkle** [comment]
Do you want to clone the new repoitory with git or download it as a zip or something else?

**Comment by Rugvip** [comment]
I think a custom action that uploads to S3/GCS or something like that could make sense for now? and then provide a link to that file.

There may be an opportunity for a more elaborate solution where you download the contents directly from the scaffolder backend. That's a bit tricker to implement and nothing we can prioritize right now. If there's someone that wants to implement that I'd say the next step is an implementation proposal, and we can take it from there.

**Comment by scprek** [comment]
A trick I did for now is have a repo that's only purpose is for publishing draft PRs. Then I have a "dry-run" mode in the template and can look at the PR to see it looks ok. We have a setup that's harder to run the whole app locally so this works nice for easy testing.
