### ISSUE TITLE
🚀 Feature: memcache and redis support

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#15116]
### 🔖 Feature description

As per documentation. Backstage can be configured to use one of three cache stores: memory, which is mainly used for local testing, memcache or Redis, which are cache stores better suited for production deployment. 
https://backstage.io/docs/overview/architecture-overview#use-memory-for-cache

It seems like, we don't have support for memcache and Redis for backstage. 

### 🎤 Context

In our case, we have configured 4GB memory for production. If multiple people are using backstage, we see heap out of memory. Now we cannot assigned more memory. As compare other application take less than 4 GB memory.

### ✌️ Possible Implementation

We should configure redis and memcache. so we can use less memory on production instance. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
@lalit774 was this the intended repository for this issue? It sounds as though you indeed should configure your instance to use Memcache or Redis 😅 

I'm not entirely sure that it'd use quite that much memory either way though, it ofc depends on your usage. Could be worth doing some heap profiling to make sure there's not leak going on.

**Comment by lalit774** [comment]
@rugvip I am getting this issue due to backend catalog does not have paging and we have only 2000 ish apis. I am getting this issue only on api page. we are unable to load the api page. can you please guide me right diection for same. I thought may be redis will help to reduce the memory load.

**Comment by parifuture** [comment]
Due to high database usage, I'm also looking into redis. This is only possible by pulling the catalog-backend code and modifying it to use redis cache. I am worried that it might become tough to upgrade the package when new versions of backstage are released.
Do you have a suggestion?

**Comment by Rugvip** [comment]
@lalit774 ah alright, see #12247 for discussions around pagination.

@parifuture in what way do you want to use redis? The catalog already has built-in caching as part of the processing loop, although you'll need to be fetching from a source that implements ETags. Could you provide some more details on where the bottlenecks are or where you're seeing high usage, as well as some rough numbers for your catalog?

**Comment by davjhan-doordash** [comment]
@Rugvip 

> The catalog already has built-in caching as part of the processing loop

Just to clarify, because it doesn't explicitly say in the docs, does setting the configs like so (as told by the [documentation](https://backstage.io/docs/overview/architecture-overview#use-memory-for-cache)):
```
backend:
  cache:
    store: redis
    connection: redis://user:pass@cache.example.com:6379
    ```

Sufficient to get catalog to use *redis* as its cache?

**Comment by benjdlambert** [comment]
>Just to clarify, because it doesn't explicitly say in the docs, does setting the configs like so (as told by the [documentation](https://backstage.io/docs/overview/architecture-overview#use-memory-for-cache)):

Unfortunately not, the Cache API is not used by the catalog, it has it's own cache for each entity which is stored in postgres and cannot be changed, although that cache is only used for the processing loop as @rugvip mentioned.

You can use the Cache API (which can be configured with redis) by passing this into your processor upon creation before you pass it to the catalog backend.
