### ISSUE TITLE
🚀 Feature: Add documentation outlining when to use each option when running yarn new

### ISSUE THREAD

**Issue by kurtaking** [backstage/backstage#15141]
### 🔖 Feature description

A page or documentation section should be added explaining the different options when running `yarn new`.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/14222009/206721709-d49b5aec-d09a-4779-b15f-a81fb047a20c.png">

### 🎤 Context

Users may find it hard to understand when to use each option, especially as the list grows. Also, as Backstage matures, not everything will be considered a "plugin" moving forward. For example, selecting `web-library` generates a frontend package that is not a plugin. 

### ✌️ Possible Implementation

A new page under **Plugins**, the **CLI Docs** or a section under **Create a Backstage Plugin**. 

<img width="263" alt="image" src="https://user-images.githubusercontent.com/14222009/206722079-b2300482-0b26-4bd1-ac4c-e9bfdca2d9bd.png">

This could include a table with 

1. The name of the create option
2. A description of when to use it
3. An example of something (a plugin, package, etc) generated from the option

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kurtaking** [comment]
This [page](https://backstage.io/docs/local-dev/cli-build-system#package-roles) may work, but it took some time to find.

https://backstage.io/docs/local-dev/cli-build-system#package-roles

**Comment by awanlin** [comment]
Might be worth also considering adding this to this page: https://backstage.io/docs/local-dev/cli-commands, that way everything is documented.

The Create a Backstage Plugin page would be a good spot to add more detailed information beyond just the commands though.

**Comment by kurtaking** [comment]
I have a [draft PR](https://github.com/backstage/backstage/pull/15155) up for this now

**Comment by awanlin** [comment]
Just notice that there's also this in-flight, might be worth coordinating: https://github.com/backstage/backstage/pull/15107
