### ISSUE TITLE
🚀 Feature: Expand catalog processing metrics to allow split by entity kind

### ISSUE THREAD

**Issue by jessicamarcomini** [backstage/backstage#15159]
### 🔖 Feature description

The catalog processor currently enables a few default collected metrics that can be used to get insights on processing queue delay, how long the whole processing flows takes, etc.

This feature would be an extension to the current metrics collector in order to allow the same type metrics to be collected per entity type giving us an overview of how much the impacted metrics are corresponding to an specific type of entity.

For example, considering the processing queue delay, this feature would show us what percentage of the queue delay is due to the  processing of kind X entities.

### 🎤 Context

Considering the processing queue delay example, having a split of affected processing time per entity type can allow a better overview of which sources/data structures and processes most impact the current delay. 
This enables us to specifically target improvements and implementation enhacements to a processor that has a greater impact in the queue delay.

The focus of this feature is mainly to obtain metrics and data about the processing flow to allows us to make the whole catalog refresh and flow more efficient.

### ✌️ Possible Implementation

Just an idea that needs further thinking/discussion - allowing these metrics to be labelled by `kind` would enable the mapping of the desired split:

![image](https://user-images.githubusercontent.com/13108925/206908720-5cf3ae2c-9542-472a-9749-0054bc770dd4.png)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by taras** [comment]
I added this as a topic for discussion during [Catalog SIG on Jan 10th](https://discord.gg/backstage-687207715902193673?event=1055436524491112488).

**Comment by taras** [comment]
Let's keep this ALIVE!

**Comment by RedlineTriad** [comment]
@Rugvip I think this is still relevant?
I have a large catalog_processing_queue_delay_sum and it difficult to figure out why, since it doesn't have any extra information.
