### ISSUE TITLE
🐛 Bug Report: backstage-cli repo build doesn't accept '--config' args

### ISSUE THREAD

**Issue by alexandrepesant** [backstage/backstage#15157]
### 📜 Description

This behaviour is not a technical bug, but rather a limitation that ends up looking like a bug?

### Here's what I'm trying to do

I have integrated Datadog RUM like [described in the docs](https://backstage.io/docs/integrations/datadog-rum/installation), i.e I added a conditional script in my `index.html`. 

This works completely fine if I put the Datadog RUM config in my `app-config.yaml`. However, we don't want to run Datadog RUM in our local and test envs but only in prod.

The way of doing this would be to add the `datadogRum` settings in `app-config.production.yaml`, but it isn't possible to define `--config` options when using `yarn build` (and therefore `backstage-cli repo build --all`), which we need in this case since the config needs to be read at build time to generate the `app` `index.html`, not at runtime like it is for all other plugins.

Am I missing something?

### 👍 Expected behavior

I would expect to be able to run `yarn build --config app-production.yaml`, just like one can do on a package level.

### 👎 Actual Behavior with Screenshots

The config file cannot be defined with `yarn build` and therefore only `app-config.yaml` is parsed, meaning that the Datadog RUM config must be present in `app-config.yaml`.

### 👟 Reproduction steps

1. Set up a backstage app
2. Enable datadogRum in `app-config.yaml` like described [here](https://backstage.io/docs/integrations/datadog-rum/installation) 
3. Run `yarn build` and verify that the generated `index.html` contains the datadog RUM script
4. Move that config to a separate config file like `app-config.production.yaml`
5. Wonder how to pass that config to the frontend build step? :D

### 📃 Provide the context for the Bug.

See the bug description

I want to use different config of datadog rum per environment, and not include it at all in our local dev environments (ie not in `app-config.yaml`

### 🖥️ Your Environment

OS:   Darwin 21.6.0 - darwin/arm64
node: v16.15.1
yarn: 1.22.19
cli:  0.21.1 (installed)
backstage:  1.8.3

Dependencies:
  @backstage/app-defaults                          1.0.8
  @backstage/backend-common                        0.16.0
  @backstage/backend-plugin-api                    0.1.4
  @backstage/backend-tasks                         0.3.7
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.21.1
  @backstage/config-loader                         1.1.6
  @backstage/config                                1.0.4
  @backstage/core-app-api                          1.2.0
  @backstage/core-components                       0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/errors                                1.1.3
  @backstage/integration-react                     1.1.6
  @backstage/integration                           1.4.0
  @backstage/plugin-adr-backend                    0.2.3
  @backstage/plugin-adr-common                     0.2.3
  @backstage/plugin-adr                            0.2.3
  @backstage/plugin-api-docs                       0.8.11
  @backstage/plugin-app-backend                    0.3.38
  @backstage/plugin-auth-backend                   0.17.1
  @backstage/plugin-auth-node                      0.2.7
  @backstage/plugin-catalog-backend-module-github  0.2.1
  @backstage/plugin-catalog-backend                1.5.1
  @backstage/plugin-catalog-common                 1.0.8
  @backstage/plugin-catalog-graph                  0.2.23
  @backstage/plugin-catalog-import                 0.9.1
  @backstage/plugin-catalog-node                   1.2.1
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.6.1
  @backstage/plugin-github-actions                 0.5.11
  @backstage/plugin-org                            0.6.1
  @backstage/plugin-permission-common              0.7.1
  @backstage/plugin-permission-node                0.7.1
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.32
  @backstage/plugin-scaffolder-backend             1.8.0
  @backstage/plugin-scaffolder-common              1.2.2
  @backstage/plugin-scaffolder                     1.8.0
  @backstage/plugin-search-backend-module-pg       0.4.2
  @backstage/plugin-search-backend-node            1.0.4
  @backstage/plugin-search-backend                 1.1.1
  @backstage/plugin-search-common                  1.1.1
  @backstage/plugin-search-react                   1.2.1
  @backstage/plugin-search                         1.0.4
  @backstage/plugin-tech-radar                     0.5.18
  @backstage/plugin-techdocs-backend               1.4.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.6
  @backstage/plugin-techdocs-node                  1.4.2
  @backstage/plugin-techdocs-react                 1.0.6
  @backstage/plugin-techdocs                       1.4.0
  @backstage/plugin-user-settings                  0.5.1
  @backstage/release-manifests                     0.0.7
  @backstage/test-utils                            1.2.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1
  @backstage/version-bridge                        1.0.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
I'm thinking that the best fix for this is to move the datadog configuration out from `index.html` and into an analytics module, so that it can read from the injected config at runtime. That way we remove the need for a separate frontend build in many situations.

Adding a config flag to the repo build is problematic because it builds all packages, including potentially multiple frontends. The intended way to build a frontend with a specific config is to only build the frontend package by itself, i.e `yarn workspace app build --config ...`

**Comment by connorads** [comment]
> @alexandrepesant Wonder how to pass that config to the frontend build step? 

Managed to do this by [passing environment variables to set app config values](https://backstage.io/docs/conf/#supplying-configuration) in CI.

For illustrative purposes, an example in GitHub Actions:
```yml
      - name: Build Backend
        run: yarn build:backend
        env:
          APP_CONFIG_app_datadogRum_clientToken: ${{ secrets.DD_CLIENT_TOKEN }}
          APP_CONFIG_app_datadogRum_applicationId: ${{ secrets.DD_APPLICATION_ID }}
          APP_CONFIG_app_datadogRum_site: datadoghq.eu

```
