### ISSUE TITLE
🚀 Feature: Add last modified timestamp to UrlReader responses

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#15160]
### 🔖 Feature description

It would be useful to support an new optional `mtime` field indicating the last modified date/time of UrlReader responses. This would be supported by `readUrl`, `readTree` & possibly `search`.

### 🎤 Context

We've started creating some customized `"Reader"` classes to fetch & parse the contents of certain files stored in remote locations (e.g. an S3 bucket or GitHub). This has been useful to both enrich catalog data or display additional information on EntityPages.

Sometimes these files could be stale or out of date. Having a new optional `lastModifiedTime`, `mtime`, etc. would be really useful from both an end user and programmatic perspective.

The `UrlReader.readTree` & `UrlReader.readUrl` have been really helpful for doing (especially with `etag` support). Currently these only return the contents of the file + the path (for `readTree`). However, we think it would be quite beneficial to also return the last modified date of the file. I've checked both `GitHubUrlReader` & `AwsS3Reader` and they seem have this data it's just not passed down through the responses.

### ✌️ Possible Implementation

The various `UrlReader` response objects would include a new optional `mtime` field (or other name). Each specific `UrlReader` implementations can provide information. Once the field is included, Each implementation that supports something that can be for the `mtime` would be updated to provide this information.

```diff
export type ReadUrlResponse = {
  buffer(): Promise<Buffer>;
  stream?(): Readable;
  etag?: string;
+ mtime?: Date; // or `lastModified`
};

export type ReadTreeResponseFile = {
  path: string;
  content(): Promise<Buffer>;
+ mtime?: Date; // or `lastModified`
};
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Possibly, but it might be a little while until I can get to this. I'm happy to collaborate on a PR with someone else in the mean time.

**Comment by Rugvip** [comment]
Yep, makes sense! 👍 Naming-wise I think something like `lastModifiedAt` provides a bit more clarity.

We should also consider adding `ifModifiedSince` or similar to the read methods.

**Comment by andrewthauer** [comment]
Still being worked on
