### ISSUE TITLE
🐛 Bug Report: default-backend-plugin contains copyright notices

### ISSUE THREAD

**Issue by mtlewis** [backstage/backstage#15184]
### 📜 Description

The files in the default-backend-plugin contain copyright notices.

### 👍 Expected behavior

The template files shouldn't contain copyright notices, so that when creating a new backend plugin with the CLI, the files don't include the notices.

### 👎 Actual Behavior with Screenshots

Copyright notices are included :D 

### 👟 Reproduction steps

1. Create a backend plugin using `yarn backstage-cli create-plugin --backend`
2. Note that all files under `src/` have a copyright notice.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
Fixed in #15198
