### ISSUE TITLE
🚀 Feature: Change defaultBranch value for publish GitLab, Bitbucket and Azure actions

### ISSUE THREAD

**Issue by redgardner** [backstage/backstage#15196]
### 🔖 Feature description

The `master` nomenclature branch naming is outdated. We have a growing number of templates we use with backstage. It would be nice if we could set a defaultBranch for all templates, or update the defaultBranch to be `main`,  or pull this information from our gitlab settings and use this value. 

### 🎤 Context

We have a growing number of templates in backstage and having to set this value on each template can get tedious. 

Having a global default that we can set, or some way to more programmatically set this value would help us.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Hi! Thanks for raising this, we currently have an option to pass in the defaultBranch when running the scaffolder actions however it currently default to master, for example in https://github.com/backstage/backstage/blob/bf42a75e74020491bbf7134308564de6446e7d83/plugins/scaffolder-backend/src/scaffolder/actions/builtin/helpers.ts#L80

We are not able to change the default without bumping to a new major version but I think we should track this for our next scaffolder major release.

**Comment by djetelina** [comment]
It'd be really awesome if the default branch was able to be pulled from settings of each project. Not only for scaffolder, but also for discovery. We have a fairly mature GitLab instance with hundreds of repositories that will stay on `master` as the default branch. As it stands, the only reasonable thing to do from my perspective is keeping `master` the default for new projects, so that nothing breaks.

**Comment by Shocktrooper** [comment]
I would like to pull the default branch on a per project basis as this value can change from project to project even if your company has a standard

**Comment by Rugvip** [comment]
I think it would make sense to be able to globally configure the default branch used by git actions, similar to how it's possible to configure the default author info and commit message.

**Comment by manuelscurti** [comment]
hey there! do we have any update on this? 
I believe it would be helpful to have a single source of truth where to look for the default branch of a Backstage instance
