### ISSUE TITLE
Embedding iframe though backstage proxy

### ISSUE THREAD

**Issue by amirkkn** [backstage/backstage#15204]
### 📜 Description

Hi, 
I'm trying to embed an opensearch dashboard's Iframe in our backstage via backstage proxy. I created a separate plugin and inside it I return the iframe.  The iframe source is backstage proxy, because I want to add some headers like basieAuth.

```
return  <iframe src="http://localhost:7777/api/proxy/logging/goto/c0f5123e99b42dc161b822298f979b9a"></iframe>
```
My proxy setting in app-config looks like so:

```
proxy:
  '/logging':
     target: https://opensearch-log-example.net
     headers:
       Authorization: Basic ABcdEFghIjKL
      pathRewrite:
        '^/api/proxy/logging/': '/'

```

Only the first request to logging server goes through the proxy and other requests go directly to target server and i get 404. E.g. there is a script inside the main page which read the bootstrap.js file: 

```
<html>...<script src="/bootstrap.js"></script></html>
```

The request which be sent to, is:
```
Request URL: http://localhost:7777/bootstrap.js
Request Method: GET
Status Code: 404 Not Found
Remote Address: [::1]:7777
Referrer Policy: no-referrer
```
It cuts "/api/proxy/logging" subpath from request and of course I get the error 404. 

I tried to use _pathRewrite_ or added content-location headers to bypass it but got no result. Then tried to manipulate in source code without any success. For example, one attempt was to create the base url and add to <head>, but it doesn't work:

``` 
var iframe = document.createElement("iframe");
iframe.id = 'myFrame';
iframe.src = "goto/c0f5123e99b42dc161b822298f979b9a";


var base = document.createElement("base");
base.href = "http://localhost:7777/api/proxy/logging/";
document.head.appendChild(base);

document.body.appendChild(iframe);
```

Can you please give me a hint how I can solve the problem? 
Thanks

### 👍 Expected behavior

I expect "api/proxy/logging/" is appended to each request to reach the target. something like that:

``` 
GET /api/proxy/logging/bootstrap.js HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: token=eyJhbGci....
Host: localhost:7777
...
```

### 👎 Actual Behavior with Screenshots

**Request**: 
``` 
GET /bootstrap.js HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: token=eyJhbGci....
Host: localhost:7777
Pragma: no-cache
Sec-Fetch-Dest: script
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
sec-ch-ua-platform: "macOS"
```

**Response**:
``` 
HTTP/1.1 404 Not Found
Content-Security-Policy: default-src 'self';base-uri 'self';font-src 'self' https: data:;frame-ancestors 'self' http:;img-src 'self' data:;object-src 'none';script-src 'self' 'unsafe-inline';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests;connect-src 'self' http: https:
X-DNS-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer
Date: Tue, 13 Dec 2022 11:46:09 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```

### 👟 Reproduction steps

Above steps

### 📃 Provide the context for the Bug.

Maybe helps to add, if I use nginx container locally instead of using the backstage proxy, it works and all requests are proxied to logging server:

```
return  <iframe src="http://localhost:8081/goto/c0f5123e99b42dc161b822298f979b9a"></iframe>
```

### 🖥️ Your Environment

Mac OS, testing locally.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Your `<base>` needs to be INSIDE the html document of the iframe, right? Not in the surrounding document.

I'll also note that the proxy does that pathRewrite automatically, and it should be safe to leave out.

**Comment by freben** [comment]
Essentially, you want to put that base tag inside `iframe.contentDocument.getElementsByTagName("head")` or so.

**Comment by amirkkn** [comment]
Thanks @freben for quick reply. 
`iframe.contentDocument` returns always null and it is not possible to add innerHTML into iframe, My wish would be implement a logic in order to send all requests with proxy base. Following doesn't work definitely, only to show what i mean :

``` 
      return <iframe src="goto/c0f5123e99b42dc161b822298f979b9a">
        <html>
        <head>
          <base href="http://localhost:7777/api/proxy/logging/" />
        </head>
        </html>
      </iframe>
```

**Comment by freben** [comment]
Ah right, even though it's on the same domain in this case as seen by the browser, the `contentDocument` would anyway not be accessible until _after_ the contents are loaded, at which time it's too late.

I think it's safe to say that at this point this isn't a use case that the proxy supports. If you can't control the remote, you will have to use some form of a layer-7 aware proxy that can dynamically rewrite the HTML it serves or something like that. Or put a basic proxy at a root CNAME such that `/` is the base URL and an unmodified `/bootstrap.js` stays correct.

**Comment by amirkkn** [comment]
Yes, as you said i think it is not the proxy use case. I decided send request directly to logging server with Oauth authentication and therefore i don't need the headers anymore. Also I close the ticket, thanks anyways!
