### ISSUE TITLE
🚀 Feature: AWS CodeCommit

### ISSUE THREAD

**Issue by jjghali** [backstage/backstage#15210]
### 🔖 Feature description

It would be nice to have the following features:
- Retrieving list of repositories and projects from CodeCommit
- Retrieving all the PRs from a given repositories

### 🎤 Context

We want to use backstage at work but we use AWS CodeCommit for our repos.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by gianluca-sabena** [comment]
I asked AWS if they can improve AWS codeservices plugin <https://github.com/awslabs/aws-codeservices-plugins-for-backstage/issues/124>

**Comment by Michaell99** [comment]
Actually it would be great if they could make a code commit integration

**Comment by namrataahuja** [comment]
Dear Team,

We are looking forward for AWS Code Commit integration. Do we have any update which release this integration be available?

PR: https://github.com/backstage/backstage/pull/23828

Thanks,
Namrata

**Comment by stijnbrouwers** [comment]
To complete on this request, the following topics discuss integration with CodeCommit in the [AWS Code Services](https://github.com/awslabs/aws-codeservices-plugins-for-backstage#readme) plugin:
- https://github.com/awslabs/backstage-plugins-for-aws/issues/6
- https://github.com/awslabs/backstage-plugins-for-aws/issues/13

**Comment by awanlin** [comment]
@stijnbrouwers, should this issue be re-opened then?

**Comment by stijnbrouwers** [comment]
Yes, I think it should
