### ISSUE TITLE
🐛 Bug Report: code-coverage-plugin - Unable to parse body as jacoco","stack":"InputError: Unable to parse body as jacoco

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#15224]
### 📜 Description

When using the code-coverage plugin and adding a jacoco-report.xml report as documented here: https://github.com/backstage/backstage/tree/master/plugins/code-coverage-backend#adding-a-jacoco-report 

`curl -k -X POST -H "Content-Type:text/xml" -d @jacoco.xml "https://backstage-instance/api/code-coverage/report?entity=component:default/bitbucket-parser-test&coverageType=jacoco"`

Reponse: 
`{"error":{"name":"InputError","message":"Unable to parse body as jacoco","stack":"InputError: Unable to parse body as jacoco\n    at /opt/app-root/src/node_modules/@backstage/plugin-code-coverage-backend/dist/index.cjs.js:422:13\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"},"request":{"method":"POST","url":"/report?entity=component:default/bitbucket-test&coverageType=jacoco"},"response":{"statusCode":400}}`

### 👍 Expected behavior

`{"links":[{"rel":"coverage","href":"https://backstage-instance/api/code-coverage/report?entity=component:default/bitbucket-test"}]}`

### 👎 Actual Behavior with Screenshots

cobertura reports work as expected, expect to see a response like as documented:

`curl -k -X POST -H "Content-Type:text/xml" -d @cobertura.xml "https://backstage-instance/api/code-coverage/report?entity=component:default/bitbucket-test&coverageType=cobertura"`

`{"links":[{"rel":"coverage","href":"https://backstage-instance/api/code-coverage/report?entity=component:default/bitbucket-test"}]}`

### 👟 Reproduction steps

Open CMD and run:

`curl -k -X POST -H "Content-Type:text/xml" -d @jacoco.xml "https://backstage-instance/api/code-coverage/report?entity=component:default/bitbucket-parser-test&coverageType=jacoco"`

### 📃 Provide the context for the Bug.

`curl -k -X POST -H "Content-Type:text/xml" -d @jacoco.xml "https://backstage-instance/api/code-coverage/report?entity=component:default/bitbucket-parser-test&coverageType=jacoco"`

### 🖥️ Your Environment

Node 16

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jhaals** [comment]
Sorry to hear that you're having issues! If possible it would be great if you could attach some a failing jacoco output to aid debugging. Going to have to defer to @alde to help out debugging this as he has been heavily involved in that plugin

**Comment by TarasZubreiFiverr** [comment]
What is the `backstage.io/code-coverage` annotation value of your entity? I remember having similar issues integrating my jacoco reports into code coverage plugin and after deeper debugging I found that the issue wasn't with the report itself. Plugin failed to connect report to source files so I had to change `backstage.io/code-coverage` value to `scm-only` and then everything worked. I haven't tried cobertura so I cannot comment whether this behavior is limited to jacoco or is plugin-wide

**Comment by regicsolutions** [comment]
> What is the `backstage.io/code-coverage` annotation value of your entity? I remember having similar issues integrating my jacoco reports into code coverage plugin and after deeper debugging I found that the issue wasn't with the report itself. Plugin failed to connect report to source files so I had to change `backstage.io/code-coverage` value to `scm-only` and then everything worked. I haven't tried cobertura so I cannot comment whether this behavior is limited to jacoco or is plugin-wide

I am just using enabled does scm-only work when I simply just post the report using the api endpoint where the report is not stored in a scm repository?

**Comment by TarasZubreiFiverr** [comment]
Yes. It's only the source files that the plugin fetches from SCM. Report itself you provide via rest api, same as you've done before.

**Comment by alde** [comment]
Yes, if I recall right (it was a while ago now) scm-only means that only files tracked by SCM will be considered when counting coverage, so generated files not covered by tests won't tank your percentage.

**Comment by regicsolutions** [comment]
> Yes, if I recall right (it was a while ago now) scm-only means that only files tracked by SCM will be considered when counting coverage, so generated files not covered by tests won't tank your percentage.

I tested again using the following annotation: `backstage.io/code-coverage: scm-only` which results in the same 400 Bad Request error for both cobertura and jacoco :( 

I posted the following sample reports for testing:
- [cobertura-testdata-1.xml](https://github.com/backstage/backstage/blob/master/plugins/code-coverage-backend/src/service/__fixtures__/cobertura-testdata-1.xml)
- [jacoco-testdata-1.xml](https://github.com/backstage/backstage/blob/master/plugins/code-coverage-backend/src/service/__fixtures__/jacoco-testdata-1.xml)

request: `curl -k -X POST -H "Content-Type:text/xml" -d @jacoco.xml "https://backstage-instance/api/code-coverage/report?entity=component:default/test-component&coverageType=jacoco"`

response:
```
{
    "error": {
        "name": "InputError",
        "message": "Illegal Content-Type",
        "stack": "InputError: Illegal Content-Type\n    at CoverageUtils.validateRequestBody (/opt/app-root/src/node_modules/@backstage/plugin-code-coverage-backend/dist/index.cjs.js:121:13)\n    at CoverageUtils.processCoveragePayload (/opt/app-root/src/node_modules/@backstage/plugin-code-coverage-backend/dist/index.cjs.js:88:23)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /opt/app-root/src/node_modules/@backstage/plugin-code-coverage-backend/dist/index.cjs.js:419:53"
    },
    "request": {
        "method": "POST",
        "url": "/report?entity=component:default/test-component&coverageType=jacoco"
    },
    "response": {
        "statusCode": 400
    }
}
```

**Comment by freben** [comment]
Are you sure that that's the exact command that triggered the "Illegal Content-Type" error? I have been trying to reproduce this and cannot get that problem to happen, even when copy-pasting your exact command line and using those files. I DID see that it's a bit hard to reproduce things because the local dev experience of the plugin wasn't great, so I made #15393 which also improves the logging to say WHAT content type it found and what the valid value would have been.

**Comment by freben** [comment]
Let me also add that yes, "Unable to parse body as jacoco" unfortunately is what's printed if it is in scm-only mode and cannot for some reason load the source tree where the entity was stored. Then it sees it as if there are NO files in the scm store, and therefore skips over every single entry in the input file even though it happened to be correctly formed, and returns no data - which an upper layer treats as "unable to parse" even though the reality was "parsed just fine but skipped over all entries in the file". Misleading.

The failed read of SCM files could happen for many reasons:

- the source location annotation of the entity could be wrong for some reason,
- the integration config for that provider where the entity is stored for some reason isn't right (less likely if it got into the catalog in the first place),
- the read-tree command fails because of e.g. rate limits or wrong permissions or whatnot

Unfortunately a bit of a chain - not easy to know immediately what might be causing this. You could try running the backend with `LOG_LEVEL=debug` in the env to see if something useful is printed while reading the files.

**Comment by regicsolutions** [comment]
> Let me also add that yes, "Unable to parse body as jacoco" unfortunately is what's printed if it is in scm-only mode and cannot for some reason load the source tree where the entity was stored. Then it sees it as if there are NO files in the scm store, and therefore skips over every single entry in the input file even though it happened to be correctly formed, and returns no data - which an upper layer treats as "unable to parse" even though the reality was "parsed just fine but skipped over all entries in the file". Misleading.
> 
> 
> 
> The failed read of SCM files could happen for many reasons:
> 
> 
> 
> - the source location annotation of the entity could be wrong for some reason,
> 
> - the integration config for that provider where the entity is stored for some reason isn't right (less likely if it got into the catalog in the first place),
> 
> - the read-tree command fails because of e.g. rate limits or wrong permissions or whatnot
> 
> 
> 
> Unfortunately a bit of a chain - not easy to know immediately what might be causing this. You could try running the backend with `LOG_LEVEL=debug` in the env to see if something useful is printed while reading the files.

So it should work for jacoco by setting the code-coverage annotation as enabled? 

Does the source-location annotation need to point to the repository path or the path to the jacoco.xml report? 
Right now it's pointing to https://bitbucket-server/projects/projectKey/repos/repoSlug/browse which brings you to the repository

To set the log level to debug is that just setting an environment variable of LOG_LEVEL=debug?
