### ISSUE TITLE
🐛 Bug Report: plugin-cloudbuild rerun workflow is blocked by CORS error

### ISSUE THREAD

**Issue by ciprianna** [backstage/backstage#15221]
### 📜 Description

The plugin `@backstage/plugin-cloudbuild` is great and loads initial requests for build history without any issues. However, when the `Rerun workflow` button is pressed, the request is blocked by a CORS error `Reason: CORS header ‘Access-Control-Allow-Origin’ missing`. This is true in local development as well as our production instance.

### 👍 Expected behavior

The `Rerun workflow` button can be used in backstage without being blocked by CORS errors.

### 👎 Actual Behavior with Screenshots

The builds load, but the rerun workflow button fails:

<img width="1171" alt="Screen Shot 2022-12-13 at 5 13 08 PM" src="https://user-images.githubusercontent.com/8051967/207465544-b3bd801e-f50b-4049-989d-758073d64a82.png">

Requests to `/builds` are successful, whereas a request to retry a single row's workflow is blocked by CORS.

<img width="1333" alt="Screen Shot 2022-12-13 at 5 03 46 PM" src="https://user-images.githubusercontent.com/8051967/207464736-31b1f25f-18d2-49d9-a663-b31673adcac5.png">

### 👟 Reproduction steps

Click on the `Rerun workflow` button from the plugin-cloudbuilds builds table.

### 🖥️ Your Environment

OS:   Darwin 21.6.0 - darwin/x64
node: v16.18.1
yarn: 1.22.0
cli:  0.20.0 (installed)
backstage:  1.7.0

Dependencies:
  @backstage/app-defaults                          1.0.7, 1.0.8
  @backstage/backend-common                        0.15.2, 0.16.0
  @backstage/backend-plugin-api                    0.1.3, 0.1.4
  @backstage/backend-tasks                         0.3.6, 0.3.7
  @backstage/catalog-client                        1.1.1, 1.1.2
  @backstage/catalog-model                         1.1.2, 1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0
  @backstage/config-loader                         1.1.5, 1.1.6
  @backstage/config                                1.0.4, 1.0.3
  @backstage/core-app-api                          1.1.1, 1.2.0
  @backstage/core-components                       0.11.2, 0.12.0, 0.9.5
  @backstage/core-plugin-api                       1.1.0, 1.0.7
  @backstage/dev-utils                             1.0.8
  @backstage/errors                                1.1.3, 1.1.2
  @backstage/integration-react                     1.1.5, 1.1.6
  @backstage/integration                           1.3.2, 1.4.0
  @backstage/plugin-adr-backend                    0.2.2
  @backstage/plugin-adr-common                     0.2.2
  @backstage/plugin-adr                            0.2.2
  @backstage/plugin-api-docs                       0.8.10
  @backstage/plugin-app-backend                    0.3.37
  @backstage/plugin-auth-backend                   0.17.0
  @backstage/plugin-auth-node                      0.2.6
  @backstage/plugin-catalog-backend-module-github  0.1.8
  @backstage/plugin-catalog-backend                1.5.0
  @backstage/plugin-catalog-common                 1.0.7, 1.0.8
  @backstage/plugin-catalog-graph                  0.2.22
  @backstage/plugin-catalog-import                 0.9.0
  @backstage/plugin-catalog-node                   1.2.0, 1.2.1
  @backstage/plugin-catalog-react                  1.2.0, 1.2.1
  @backstage/plugin-catalog                        1.6.0, 1.6.1
  @backstage/plugin-cloudbuild                     0.3.11
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-home                           0.4.27
  @backstage/plugin-org                            0.5.10
  @backstage/plugin-permission-common              0.7.0, 0.7.1
  @backstage/plugin-permission-node                0.7.0
  @backstage/plugin-permission-react               0.4.6, 0.4.7
  @backstage/plugin-proxy-backend                  0.2.31
  @backstage/plugin-scaffolder-backend             1.7.0
  @backstage/plugin-scaffolder-common              1.2.1
  @backstage/plugin-scaffolder                     1.7.0
  @backstage/plugin-search-backend-module-pg       0.4.1
  @backstage/plugin-search-backend-node            1.0.3
  @backstage/plugin-search-backend                 1.1.0
  @backstage/plugin-search-common                  1.1.0, 1.1.1
  @backstage/plugin-search-react                   1.2.0, 1.2.1
  @backstage/plugin-search                         1.0.3
  @backstage/plugin-stack-overflow                 0.1.7
  @backstage/plugin-tech-radar                     0.5.17
  @backstage/plugin-techdocs-backend               1.4.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5
  @backstage/plugin-techdocs-node                  1.4.1
  @backstage/plugin-techdocs-react                 1.0.6, 1.0.5
  @backstage/plugin-techdocs                       1.3.3
  @backstage/plugin-todo-backend                   0.1.35
  @backstage/plugin-todo                           0.2.13
  @backstage/plugin-user-settings                  0.5.0
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1, 1.2.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0, 1.0.1
  @backstage/version-bridge                        1.0.1, 1.0.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by jhaals** [comment]
Sorry to hear that you're having issues, I was not expecting an OPTIONS request given that's for a GET request. Have this worked in your instance previously? We have not received any other reports of this issue. Perhaps @ebarriosjr that authored the plugin could provide some guidance or verify with his installation.

**Comment by shahkv95** [comment]
quick-bit-suggestion:

To fix this issue, you will need to ensure that the server handling the request is properly configured to allow cross-origin requests from the domain that is making the request. This can typically be done by adding the appropriate CORS headers to the server's response.

For example, to allow all domains to make cross-origin requests to the server, you could add the following header to the server's response:

Access-Control-Allow-Origin: *

Alternatively, you can specify a specific domain or list of domains that are allowed to make cross-origin requests by replacing the asterisk with the domain or list of domains.

You may also need to configure the server to allow other CORS headers, such as 'Access-Control-Allow-Methods' and 'Access-Control-Allow-Headers', depending on the requirements of your application.

Once you have properly configured the server to allow cross-origin requests, the CORS error should be resolved and the request should be able to complete successfully.

**Comment by ciprianna** [comment]
Thank you both for responding!

Configuring `app-config.yaml` with CORS server settings seems to have no effect on this. I receive the same response back about the missing access-control-allow-origin CORS header. Is there a different place I should be configuring it for this plugin?

```yaml
  cors:
    origin: ${APP_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
    Access-Control-Allow-Origin: '*'
```

The retry workflow has never worked on our project, it was just added and the initial load for builds works as expected, just not the retry workflow.

That's why this one is particularly confusing, because the original request is great, which also has CORS referrer type but succeeds. There's no preflight OPTIONS request with those, though. The requests are made from the plugin, so I don't have control over that part.

Maybe I'm missing configuration for it? Any help is appreciated.

**Comment by freben** [comment]
@ciprianna What they meant was, you need to ensure that the _target_ system returns CORS headers, so that particular thing isn't something that can be configured in Backstage itself. This is just how browser CORS security is implemented. It just refuses entirely to speak to external systems unless permitted to, under certain circumstances, for security reasons.

**Comment by freben** [comment]
But yeah I agree though, since the initial load works, it's a bit odd that this fails. Maybe the CORS thing is a red herring after all?

The retry callback actually triggered, is [this one](https://github.com/backstage/backstage/blob/330fad5046cc90249f4738d506ac5a11c8c54258/plugins/cloudbuild/src/components/useWorkflowRuns.ts#L50). It's part of how `useAsyncRetry` works; it's just a function it returns that you can call to tell it to do the same thing it already did once more. So ... yeah I am not sure why that wouldn't work if the first one did.

Only thing I can think of off the top of my mind is, could the browser be treating the two events differently? Is one seen as a user interaction but the other one is seen as a "background" one, such that the latter is treated more harshly? Honestly not sure.

**Comment by ciprianna** [comment]
@freben , thank you for clarifying and for your response. I was checking out the documentation for cloud build, and the retry is supposed to be a [POST](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds/retry). So it's not authorizing correctly because that route isn't set up as a GET. If I add the method to the fetch request:

```js
async reRunWorkflow(options) {
    await fetch(
      `https://cloudbuild.googleapis.com/v1/projects/${encodeURIComponent(
        options.projectId
      )}/builds/${encodeURIComponent(options.runId)}:retry`,
      {
        method: 'POST',
        headers: new Headers({
          Accept: "*/*",
          Authorization: `Bearer ${await this.getToken()}`,
        })
      }
    );
  }
```
then it works as expected with Google cloud build. I wonder if this is happening for anyone else, though? Is this only the case for my instance?

**Comment by ciprianna** [comment]
I double-checked this in the Backstage repo. When hooking up my cloudbuild credentials there, it had the same issue. I opened a PR to fix the method here: https://github.com/backstage/backstage/pull/15729.

**Comment by ciprianna** [comment]
Fixed in https://github.com/backstage/backstage/pull/15729
