### ISSUE TITLE
🐛 Bug Report: Lighthouse links does not respect the URL prefix

### ISSUE THREAD

**Issue by CSalih** [backstage/backstage#15231]
### 📜 Description

Some of the Lighthouse Plugin links does not respect the URL prefix. For example clicking on a audit in `AuditViewContent` will point to `/audit/<id>` but it should be `/lighthouse/audit/<id>` or `/<global-prefix>/lighthouse/audit/<id>` when the root of Backstage is not `/`. The `CREATE NEW AUDIT` button has also the same behavior.  Because of that wrong URL, we will see the 404 Page. 

### 👍 Expected behavior

Anchor element (or Button) should respect the own prefix and should not redirect to the 404 page.

### 👎 Actual Behavior with Screenshots

Anchor element does not respect the prefix.

Example of `AuditViewContent`
![Screenshot from 2022-12-14 10-16-39](https://user-images.githubusercontent.com/17460013/207555459-952dfb8f-a42a-4447-88f5-e0dba38aad37.png)

### 👟 Reproduction steps

1) Go to the Lighthouse Page (e.g. `/lighthouse`)
2) Go to any Website URL (if not available create any audit)
3) Click on "CREATE NEW AUDIT" or any Date (see Screenshot above)
4) You should know see a 404 Page

### 🖥️ Your Environment

OS:   Linux 5.14.0-1052-oem - linux/x64
node: v16.14.2
yarn: 1.22.19
cli:  0.20.0 (installed)
backstage:  1.7.2

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-common                        0.15.2
  @backstage/backend-plugin-api                    0.1.3
  @backstage/backend-tasks                         0.3.6
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0
  @backstage/config-loader                         1.1.5
  @backstage/config                                1.0.4
  @backstage/core-app-api                          1.1.1
  @backstage/core-components                       0.11.2, 0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/errors                                1.1.3
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.4.0
  @backstage/plugin-api-docs                       0.8.10
  @backstage/plugin-app-backend                    0.3.37
  @backstage/plugin-auth-backend                   0.17.0
  @backstage/plugin-auth-node                      0.2.6
  @backstage/plugin-catalog-backend                1.5.0
  @backstage/plugin-catalog-common                 1.0.8
  @backstage/plugin-catalog-graph                  0.2.22
  @backstage/plugin-catalog-import                 0.9.0
  @backstage/plugin-catalog-node                   1.2.0
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.6.0
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-lighthouse                     0.3.11
  @backstage/plugin-org                            0.5.10
  @backstage/plugin-permission-common              0.7.1
  @backstage/plugin-permission-node                0.7.0
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.31
  @backstage/plugin-scaffolder-backend             1.7.0
  @backstage/plugin-scaffolder-common              1.2.1
  @backstage/plugin-scaffolder                     1.7.0
  @backstage/plugin-search-backend-module-pg       0.4.1
  @backstage/plugin-search-backend-node            1.0.3
  @backstage/plugin-search-backend                 1.1.0
  @backstage/plugin-search-common                  1.1.1
  @backstage/plugin-search-react                   1.2.0
  @backstage/plugin-search                         1.0.3
  @backstage/plugin-tech-radar                     0.5.17
  @backstage/plugin-techdocs-backend               1.4.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5
  @backstage/plugin-techdocs-node                  1.4.1
  @backstage/plugin-techdocs-react                 1.0.5
  @backstage/plugin-techdocs                       1.3.3
  @backstage/plugin-user-settings                  0.5.0
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1
  @backstage/version-bridge                        1.0.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Fixed by #15234
