### ISSUE TITLE
🚀 Feature: add --no-install to backstage-cli versions:bump

### ISSUE THREAD

**Issue by wrighbr** [backstage/backstage#15230]
### 🔖 Feature description

Added the parameter `--no-install` to `backstage-cli version:bump` command

### 🎤 Context

I have a CI pipeline that semi updates backstage that uses the command `backstage-cli version:bump`.

However it can take a long time to install the packages. I really don't need these packages to installed as apart of the pipeline it would be nice to have an option to skip the install of these packages. I just need the package.json files and yarn.lock file to be updated. So can I commit these files to git,

This option would speed up the pipeline by several minutes.

### ✌️ Possible Implementation

on line https://github.com/backstage/backstage/blob/master/packages/cli/src/commands/versions/bump.ts#L258 we could create an if statement something like the below

```
if (!opts.noInstall) {
   await runYarnInstall();
} 
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by wunderdogneo** [comment]
We're also using the command in the CI, to check if versions are correct. In other words, the pipeline fails if `version:bump <current version>` would introduce any changes. It would definitely be helpful if we could avoid the `yarn install` :)

**Comment by jhaals** [comment]
Thanks for the suggestion, I think it's a good one. We should make sure that it is `--skip-install` to align with other commands that offer the same functionality. PR's welcome! 🙏
