### ISSUE TITLE
🐛 Bug Report: makeFieldSchemaFromZod not exported from @backstage/plugin-scaffolder

### ISSUE THREAD

**Issue by marianheinsen** [backstage/backstage#15255]
### 📜 Description

I'm writing a custom field extension but when importing the helper function makeFieldSchemaFromZod from the @backstage/plugin-scaffolder package, it says: "Module '"@backstage/plugin-scaffolder"' has no exported member 'makeFieldSchemaFromZod'"

### 👍 Expected behavior

I expect the import to work

### 👎 Actual Behavior with Screenshots

The import doesn't work but shows an error message

<img width="808" alt="Screenshot 2022-12-15 at 14 30 08" src="https://user-images.githubusercontent.com/43065575/207871502-1d27ce4d-ce5a-43da-b118-6339893afff8.png">

### 👟 Reproduction steps

Create a new .ts file inside of the packages/app/src directory and try to import:

import { makeFieldSchemaFromZod } from '@backstage/plugin-scaffolder';

### 🖥️ Your Environment

I'm on the latest release of Backstage with the latest version of the @backstage/plugin-scaffolder installed (1.8.0)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by roman-shandurenko** [comment]
Have the same.
As a temporary solution, you can use a copy of the func from `utils` to unblock development https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/utils.ts

**Comment by jhaals** [comment]
Sorry to hear you're having problems, I believe this is a case of our docs being updated before the release being out. This should be fixed in version 1.9 which is due for release tomorrow! Please give that a try once it's released and report back. Sorry for your inconvenience 🙏

**Comment by benjdlambert** [comment]
Think this should be fixed now with the release of v1.9 yesterday! Sorry we were a little eager updating the docs before the release went out!
