### ISSUE TITLE
🐛 Bug Report: github:actions:dispatch doesn't handle boolean parameters from Template

### ISSUE THREAD

**Issue by RonnyA** [backstage/backstage#15268]
### 📜 Description

When triggering a GitHub workflow from a template that collects Boolean values the HTTP request fails with "invalid request".
And with extra info 
   For 'additionalProperties', true is not a string.

The reason for this is that I believe that the githubActionsDispatch.ts in 'builtin/github' doesnt convert boolean to string when doing the HTTP request.

### 👍 Expected behavior

The Boolean should be converted to "1" (true) and "0" (false) or just "true"/"false" - and the GitHub workflow would use a string input.

Even better, it could be converted to the format that GitHub workflow expects for Boolean input.

### 👎 Actual Behavior with Screenshots

Beginning step Trigger GitHub workflow 
info: Dispatching workflow workflow-name.yml for repo github.com?repo=your-repo&owner=your-owner on main 

HttpError: Invalid request.

For 'additionalProperties', true is not a string.
    at /app/node_modules/@octokit/request/dist-node/index.js:88:218   
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Job.doExecute (/app/node_modules/bottleneck/light.js:405:18)

### 👟 Reproduction steps

Template
---------

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: call-github
  title: Call githib workflow
spec:
  owner: team-iam
  type: service
  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in details for your subscription
      required:
        - subName
        - envTest
      properties:
        subName:
          title: Subscription name
          type: string
          description: Name of subscription
        envTest:
          title: Is it test
          type: boolean
          default: false
          ui:widget: radio

 steps:
    - id: trigger_gh_workflow
      name: Trigger GitHub workflow 
      action: github:actions:dispatch
      input:
        repoUrl: github.com?repo=your-repo&owner=your-owner
        branchOrTagName: main
        workflowId: workflow-name.yml
        workflowInputs:
          subName: ${{ parameters.subName }}
          envTest: ${{ parameters.envTest }}

### 📃 Provide the context for the Bug.

Supporting boolean values in the template through the GitHub integration would make the module much more flexible and useful for automating tasks in GitHub from Backstage.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jhaals** [comment]
Thanks, for reporting. This might be a bug, could you possibly convert it in the template as a workaround?

**Comment by freben** [comment]
Could you try `envTest: ${{ parameters.envTest | dump }}` ? That should stringify it.

**Comment by RonnyA** [comment]
I tried to add " | dump" and it removed the error "For 'additionalProperties', true is not a string." in Backstage.
However, now "nothing" is transferred to the the GitHub workflow, and the workflow doesn't start.
> HttpError: Required input 'envTest' not provided

Not sure what "|dump" is supposed to do with a Boolean value.

**Comment by freben** [comment]
`dump` makes the substitution into the raw original data dumped straight into the target. So `envTest: ${{ parameters.envTest | dump }}` would become `envTest: true` if `parameters.envTest` had true as its value.

What's the parameter schema for the workflow inputs? Something's odd here, not sure why `parameters.envTest` seems so incompatible with the input.

As a side note, there's also the ternary if/else syntax, eg `${{ "1" if envTest else "0" }}` and similar that you can experiment with if needed.
