### ISSUE TITLE
🐛 Bug Report: Github events model no longer works with monorepo

### ISSUE THREAD

**Issue by vonjones** [backstage/backstage#15265]
### 📜 Description

The new Github events model no longer works with monorepo style integrations which can include `catalog-info.yaml` files in any directory. I believe there are a couple of errors with [this line](https://github.com/backstage/backstage/blob/ba9ae05052b6622b442e3d49f6bd34eebe4d05b3/plugins/catalog-backend-module-github/src/providers/GithubEntityProvider.ts#L393)

1. the catalogPath allows globs, so a simple include is not going to work
2. I believe the order is incorrect. I think it should be `file.includes(catalogFile)` rather than `catalogFile.includes(file)`. Actually something more like `file.matches(catalogFile)` assuming you convert the glob to a regex.

### 👍 Expected behavior

A modified file like `dir1/dir2/dir3/catalog-info.yaml` should be matched by a provider config with `catalogPath: '**/catalog-info.yaml'`

### 👎 Actual Behavior with Screenshots

log shows
```
Processed Github push event: added 0 - removed 0 - modified 0
```

### 👟 Reproduction steps

put `catalog-info.yaml` files in subdirectories and change them

### 📃 Provide the context for the Bug.

Unable to monitor for changes in a [TechDocs monorepo](https://github.com/backstage/mkdocs-monorepo-plugin) style implementation.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jhaals** [comment]
I don't think that events is supported for mono repos at this point. Perhaps @kissmikijr could shed some light on that and perhaps if there are anyone working on implementing it currently.

**Comment by pjungermann** [comment]
> The new Github events model no longer works

As this is a recent addition, I assume it never worked, right? :) Or did a change break anything?

Without being too deep into this, I assume that your suggestion at (2.) is the way to go.

@angeliski was the one who contributed the event-based update support for GitHub at PR #14758 .
What do you think?

**Comment by angeliski** [comment]
Hey @vonjones I will try to put a unit test to see if this case is happening

Probably the glob solution is the best case.

Just to be sure: The problem is not about `monorepo` but the case where the `catalog-info.yaml` is in a subdirectory, right?

**Comment by vonjones** [comment]
I suppose so. A monorepo is enabled by allowing multiple `catalog-info.yaml` files within a single repo. But we have such a requirement in standard repos. For example, we may have documentation for a provided API separated from the base service documentation, so the two documentation sets, within the same Github repo, can be specialized. You want the docs to be with the code, which can result in multiple `catalog-info.yaml` files. So it's not just about the `catalog-info.yaml` file being somewhere else, but also about there possibly being several in a given repo.

The [configuration documentation](https://backstage.io/docs/integrations/github/discovery#configuration) for the provider clearly provides guidance that the catalogPath is a glob pattern. Elsewhere, like if you have a scheduled repo scan, the provider is going to interpret the catalogPath as a glob. It's only in the event support that you are actually precluded from using the glob.

FWIW I had to create a scheduled scan and initialize using fromConfig in order for the connection to be initialized. This bug means I cannot include a glob in conjunction with events, which means I still need both the catalog scan and the event config.
