### ISSUE TITLE
🚀 Feature: Plugin-catalog, missing EntityDependencyOfResourcesCard for EntityPage ?

### ISSUE THREAD

**Issue by etiennechabert** [backstage/backstage#15283]
### 🔖 Feature description

It would be nice to have a Card so that a list of resources dependent on another resource could be displayed on the entityPage:
- EntityDependencyOfResourcesCard

It feels really missing when you see that these 3 cards exists:
- EntityDependsOnComponentsCard
- EntityDependsOnResourcesCard
- EntityDependencyOfComponentsCard

At the moment, the DependencyOfResource can only be shown on the Graph, but not in the tables from what I can tell...

### 🎤 Context

In the service catalog, I was able to describe the relations between my resources using `dependsOn` and `dependencyOf`, both of which are creating relations between my resources.

I now would be able to display via a card these dependencies from my resource page, `EntityDependencyOfComponentsCard` is solving 50% of the problem, but `EntityDependencyOfResourcesCard` is missing.

### ✌️ Possible Implementation

I imagine an implementation almost identical as `EntityDependencyOfComponentsCard` would give us the `EntityDependencyOfResourcesCard` ?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by etiennechabert** [comment]
So I believe in the spirit of this:
https://github.com/backstage/backstage/tree/master/plugins/catalog/src/components/DependencyOfComponentsCard

We could build the other-side of the dependency: 
https://github.com/backstage/backstage/tree/master/plugins/catalog/src/components/DependsOnResourcesCard

**Comment by jhaals** [comment]
Hi! Just to confirm, you have resources that depend on other resources that you want to display?
Would be nice if we could consolidate this into a single Card that could be configured with props as most of these dependency cards are likely quite similar.

**Comment by etiennechabert** [comment]
Hi @jhaals, thanks for your message,

Indeed, I have a series of resources that all depends on one resource. From this resource perspective, I would like to have a list of all the resources declaring a dependency to it. And from what I can see, it's not possible yet since `EntityDependencyOfResourcesCard` is missing.

If my resources were components, I would be able to do exactly that since the cards exists: `EntityDependencyOfComponentsCard`

And I totally agree with you that a generic way would be better to avoid too much duplication in the cards code 👍
