### ISSUE TITLE
🐛 Bug Report: Data labels in `Cloud Cost` section are unreadable with small window size

### ISSUE THREAD

**Issue by vorbrodt** [backstage/backstage#15292]
### 📜 Description

When you go to` Cost Insights` with a small window size, the data labels in section `Cloud Cost`  are unreadable.

### 👍 Expected behavior

Data labels `COST TREND`  and `DAILY ACTIVE USERS TREND` are readable.

![image](https://user-images.githubusercontent.com/64839037/208297749-7177e6cd-d51b-4643-ae05-3e1ff6e25686.png)

### 👎 Actual Behavior with Screenshots

Data labels `COST TREND`  and `DAILY ACTIVE USERS TREND` are  unreadable.

![actual_behaviour](https://user-images.githubusercontent.com/64839037/208297665-e1178671-56eb-4d75-8899-dee9bdeb8552.png)

### 👟 Reproduction steps

1. Run `yarn dev`
2. Go to Cost Insights with a fairly small window size. (e.g. http://localhost:3000/cost-insights?group=group-a + a small window)

If you make the window size larger the data labels become readable, however if you shrink the window again and refresh the page, the data labels will become unreadable again.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by jhaals** [comment]
Thanks for pointing it out, some help fixing this would be great 🙏
