### ISSUE TITLE
🐛 Bug Report: Running tests with extra jest config in package.json

### ISSUE THREAD

**Issue by ScottGuymer** [backstage/backstage#15311]
### 📜 Description

When running `yarn backstage-cli repo test` from the root of the workspace when i have some additional jest config in the package.json i get errors when running at the repo root but not when running inside each package.

### 👍 Expected behavior

Tests should run and include config from package.json, in this case the extra reporter should run and i should get junit xml file in each package.

### 👎 Actual Behavior with Screenshots

I get the following in the command line when running `CI=true yarn backstage-cli repo test` 

The tests do still run but without any of the extra config.

```
yarn run v1.22.19
$ /Users/scott/Code/greenroom/backstage/node_modules/.bin/backstage-cli package test
● Validation Warning:

  Unknown option "coverageDirectory" with value "/Users/scott/Code/greenroom/backstage/packages/app/coverage" was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration

● Validation Warning:

  Unknown option "coverageProvider" with value "v8" was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration

● Validation Warning:

  Unknown option "collectCoverageFrom" with value ["**/*.{js,jsx,ts,tsx,mjs,cjs}", "!**/*.d.ts"] was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration

● Validation Warning:

  Unknown option "reporters" with value ["default", "jest-github-actions-reporter", ["jest-junit", {"ancestorSeparator": " › ", "classNameTemplate": "{classname}", "outputDirectory": "reports", "outputName": "report", "suiteNameTemplate": "{filepath}", "titleTemplate": "{title}", "uniqueOutputName": "true"}]] was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

but when running inside a package/plugin I don't see this issue and the extra config is picked up correctly and i get the junit reports created..

### 👟 Reproduction steps

Add the following in the package.json

```json
...
"jest": {
    "testPathIgnorePatterns": [
      "/node_modules/",
      "/__fixtures__/"
    ],
    "reporters": [
      "default",
      "jest-github-actions-reporter",
      [
        "jest-junit",
        {
          "outputDirectory": "reports",
          "outputName": "report",
          "uniqueOutputName": "true",
          "ancestorSeparator": " › ",
          "suiteNameTemplate": "{filepath}",
          "classNameTemplate": "{classname}",
          "titleTemplate": "{title}"
        }
      ]
    ]
  }
...
```

And then run `CI=true yarn backstage-cli repo test` results in some validation errors from jest like this

### 📃 Provide the context for the Bug.

I want to enable to extra reporters for jest so i can use the test results for futher reporting.

This did used to work but has stopped at some point and i have come across this error when debugging.

### 🖥️ Your Environment

yarn run v1.22.19
$ /Users/scott/Code/greenroom/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 21.6.0 - darwin/arm64
node: v18.12.1
yarn: 1.22.19
cli:  0.21.1 (installed)
backstage:  1.8.2

Dependencies:
  @backstage/app-defaults                          1.0.8
  @backstage/backend-common                        0.16.0
  @backstage/backend-plugin-api                    0.1.4
  @backstage/backend-tasks                         0.3.7
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0, 0.21.1
  @backstage/config-loader                         1.1.6
  @backstage/config                                1.0.4
  @backstage/core-app-api                          1.2.0
  @backstage/core-components                       0.11.2, 0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/dev-utils                             1.0.8
  @backstage/errors                                1.1.3
  @backstage/integration-react                     1.1.6
  @backstage/integration                           1.4.0
  @backstage/plugin-api-docs                       0.8.11
  @backstage/plugin-app-backend                    0.3.38
  @backstage/plugin-auth-backend                   0.17.1
  @backstage/plugin-auth-node                      0.2.7
  @backstage/plugin-catalog-backend-module-github  0.2.1
  @backstage/plugin-catalog-backend                1.5.1
  @backstage/plugin-catalog-common                 1.0.8
  @backstage/plugin-catalog-graph                  0.2.23
  @backstage/plugin-catalog-import                 0.9.1
  @backstage/plugin-catalog-node                   1.2.1
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.6.1
  @backstage/plugin-github-actions                 0.5.11
  @backstage/plugin-home                           0.4.27
  @backstage/plugin-org                            0.6.1
  @backstage/plugin-permission-common              0.7.1
  @backstage/plugin-permission-node                0.7.1
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.32
  @backstage/plugin-scaffolder-backend             1.8.0
  @backstage/plugin-scaffolder-common              1.2.2
  @backstage/plugin-scaffolder                     1.8.0
  @backstage/plugin-search-backend-node            1.0.4
  @backstage/plugin-search-backend                 1.1.1
  @backstage/plugin-search-common                  1.1.1
  @backstage/plugin-search-react                   1.2.1
  @backstage/plugin-search                         1.0.4
  @backstage/plugin-stack-overflow-backend         0.1.7
  @backstage/plugin-stack-overflow                 0.1.7
  @backstage/plugin-tech-radar                     0.5.18
  @backstage/plugin-techdocs-backend               1.4.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.6
  @backstage/plugin-techdocs-node                  1.4.2
  @backstage/plugin-techdocs-react                 1.0.6
  @backstage/plugin-techdocs                       1.4.0
  @backstage/plugin-user-settings                  0.5.1
  @backstage/release-manifests                     0.0.6, 0.0.7
  @backstage/test-utils                            1.2.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1
  @backstage/version-bridge                        1.0.2
Done in 0.61s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ScottGuymer** [comment]
No, it's not just coverage that is triggering this. We don't have any explicit coverage settings in the `package.json` (root or package).

The errors above are just a snippet of the output. It seems to repeat the same errors for each package that it runs test for when you run `repo test`. From what I can see in the code in the cli it constructs a config from combining default config in the cli package with things in the `package.json` and then feeds that into jest.

**Comment by ScottGuymer** [comment]
I think i can see a potential issue (or at least a difference)

When running `CI=true yarn test --showConfig` in both the root and then within a package.

When running in the package i can see the `reporters` config from the root `package.json` is being put into the `globalConfig.reporters` in the output

But when running in the root i can see it is put in `globalConfig.projects[x].reporters` im not sure if this is the cause.. 

But it seems like this per project config is what you were saying but not just for coverage and some change is now putting the "extra" config from the `packages.json` in `globalConfig.projects` rather than in directly in `globalConfig`.

I suspect any config in the root `packages.json` should go direct into the `globalConfig` object.

**Comment by ScottGuymer** [comment]
A temporary workaround here is as you mention to run `lerna run test`

**Comment by qutax** [comment]
I think it has to do with the jest.js file of backstage-cli:
https://github.com/backstage/backstage/blob/v1.9.1/packages/cli/config/jest.js

It looks like the config we put into the root package.json is never applied as root global config but instead added to every project configuration.

**Comment by Rugvip** [comment]
@qutax indeed, I think a good fix here might be to only apply config from the local `package.json` in the case where `getRootConfig()` runs in workspace mode where it loads in all configurations from the repo. So each package config would only look at its own `package.json`, and the root config would look at the root `package.json`. We'd still do the search upwards when loading the config for a single package though, although it might be better to make it explicitly only look at the root and local package json rather than a full search. I'm not entirely sure this approach makes sense in practice either, so it would need some validation.

I'll open this up for contributions for anyone that wants to pick this up, let us know if any more details are needed.

**Comment by Sergio-Mira** [comment]
Looking into this issue now 👋

**Comment by ScottGuymer** [comment]
This isn't stale it still seems to be an issue.

**Comment by jiho-kr** [comment]
I also wait for this issue to be resolved

**Comment by kmarkow** [comment]
I'd like to work on this just want to clarify the expectation. I'm trying to reproduce and added this section to root `package.json`.

```
"jest": {
    "testPathIgnorePatterns": [
      "/node_modules/",
      "/__fixtures__/"
    ],
    "reporters": [
      "default",
      "jest-github-actions-reporter",
      [
        "jest-junit",
        {
          "outputDirectory": "reports",
          "outputName": "report",
          "uniqueOutputName": "true",
          "ancestorSeparator": " › ",
          "suiteNameTemplate": "{filepath}",
          "classNameTemplate": "{classname}",
          "titleTemplate": "{title}"
        }
      ]
    ]
  },
```

Currently when I run this command in backstage root
```
CI=true yarn backstage-cli repo test --showConfig
```

it is adding the reporters section into each project like this:
```
{
  ...
  "globalConfig": {
    "projects": [
      {
        "displayName": "example-app",
        "reporters": [                                                             << reporters is being added here
          "default",
          "jest-github-actions-reporter",
          [
            "backstage/node_modules/jest-junit/index.js",
            {
              "outputDirectory": "reports",
              "outputName": "report",
              "uniqueOutputName": "true",
              "ancestorSeparator": " › ",
              "suiteNameTemplate": "{filepath}",
              "classNameTemplate": "{classname}",
              "titleTemplate": "{title}"
            }
          ]
        ],
        "id": "backstage_cli_8615e494b5adaa65202bbf6f7574df18"
      },
      ...
    ]
  }
}
```

and instead the desired behavior is to have something like this
```
{
  "reporters": [                                                             << reporters should be added at root only
          "default",
          "jest-github-actions-reporter",
          [
            "backstage/node_modules/jest-junit/index.js",
            {
              "outputDirectory": "reports",
              "outputName": "report",
              "uniqueOutputName": "true",
              "ancestorSeparator": " › ",
              "suiteNameTemplate": "{filepath}",
              "classNameTemplate": "{classname}",
              "titleTemplate": "{title}"
            }
          ]
        ],
  "globalConfig": {
    "projects": [
      {
        "displayName": "example-app",
        "id": "backstage_cli_8615e494b5adaa65202bbf6f7574df18"
      },
      ...
    ]
  }
}
```

**Comment by ScottGuymer** [comment]
I think that looks about right from what i understand from the jest docs

**Comment by mjoyce91** [comment]
Is there any activity on this issue?

**Comment by sapher** [comment]
Just stumble upon this one, and still no workaround or fix ?
