### ISSUE TITLE
🐛 Bug Report:  SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ch-enfuse** [backstage/backstage#15314]
### 📜 Description

Hi, I'm attempting to create a new custom action for the scaffolder by following the steps [here] (https://backstage.io/docs/features/software-templates/writing-custom-actions). My implementation requires fetching configuration values using by using this line import { useApi, configApiRef } from '@backstage/core-plugin-api';

When that is present in my custom action file, i get this error  **SyntaxError: Cannot use import statement outside a module**. 

Not sure if I'm allowed to use these here or maybe there is another way to read configuration from these custom actions. I have a [repo](https://github.com/enfuse/enfuse-backstage/tree/demo-test) with the code that shows this issue in the **demo-test** branch in case that is useful.

Any help is appreciated, Thank you!

### 👍 Expected behavior

Action registered to the catalog

### 👎 Actual Behavior with Screenshots

[1] import { createVersionedContext, createVersionedValueMap, useVersionedContext, getOrCreateGlobalSingleton } from '@backstage/version-bridge';
[1] ^^^^^^
[1] 
[1] SyntaxError: Cannot use import statement outside a module
[1]     at compileFunction (<anonymous>)
[1]     at Object.compileFunction (node:vm:360:18)
[1]     at wrapSafe (node:internal/modules/cjs/loader:1084:15)
[1]     at Module._compile (node:internal/modules/cjs/loader:1119:27)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
[1]     at Module.load (node:internal/modules/cjs/loader:1033:32)
[1]     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1057:19)
[1]     at require (node:internal/modules/cjs/helpers:103:18)
[1]     at Object.@backstage/core-plugin-api (/Users/chris/enfuse/backstage/enfuse-backstage-main/enfuse-backstage/packages/backend/dist/main.js:203:18)

### 👟 Reproduction steps

Follow the steps to create a new action and include the following import
 **import { useApi, configApiRef } from '@backstage/core-plugin-api';**
to read from config. Have the action registered in the scaffolder as explained in the guide.

### 🖥️ Your Environment

OS:   Darwin 20.6.0 - darwin/arm64
node: v16.18.1
yarn: 1.22.19
cli:  0.19.0 (installed)
backstage:  1.6.0

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-common                        0.15.2
  @backstage/backend-plugin-api                    0.1.2
  @backstage/backend-tasks                         0.3.5
  @backstage/catalog-client                        1.1.1
  @backstage/catalog-model                         1.1.2
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.19.0
  @backstage/config-loader                         1.1.5
  @backstage/config                                1.0.3
  @backstage/core-app-api                          1.1.1
  @backstage/core-components                       0.11.2
  @backstage/core-plugin-api                       1.0.7
  @backstage/dev-utils                             1.0.7
  @backstage/errors                                1.1.1, 1.1.2
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.3.2
  @backstage/plugin-api-docs                       0.8.9
  @backstage/plugin-app-backend                    0.3.36
  @backstage/plugin-auth-backend                   0.16.0
  @backstage/plugin-auth-node                      0.2.5
  @backstage/plugin-azure-devops-backend           0.3.15
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.2.0
  @backstage/plugin-catalog-backend                1.4.0
  @backstage/plugin-catalog-common                 1.0.7
  @backstage/plugin-catalog-graph                  0.2.21
  @backstage/plugin-catalog-import                 0.8.12
  @backstage/plugin-catalog-node                   1.1.0
  @backstage/plugin-catalog-react                  1.2.0
  @backstage/plugin-catalog                        1.5.1
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-org                            0.5.9
  @backstage/plugin-permission-common              0.6.4, 0.7.0
  @backstage/plugin-permission-node                0.6.5
  @backstage/plugin-permission-react               0.4.6
  @backstage/plugin-proxy-backend                  0.2.30
  @backstage/plugin-scaffolder-backend             1.6.0
  @backstage/plugin-scaffolder-common              1.2.0
  @backstage/plugin-scaffolder                     1.6.0
  @backstage/plugin-search-backend-module-pg       0.4.0
  @backstage/plugin-search-backend-node            1.0.2
  @backstage/plugin-search-backend                 1.0.2
  @backstage/plugin-search-common                  1.1.0
  @backstage/plugin-search-react                   1.1.0
  @backstage/plugin-search                         1.0.2
  @backstage/plugin-tech-radar                     0.5.16
  @backstage/plugin-techdocs-backend               1.3.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.4
  @backstage/plugin-techdocs-node                  1.4.0
  @backstage/plugin-techdocs-react                 1.0.4
  @backstage/plugin-techdocs                       1.3.2
  @backstage/plugin-user-settings                  0.4.8
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Actions are backend. `@backstage/core-plugin-api` is for frontend. These worlds cannot import each other - they are just completely incompatible.

If you wanted to get access to the config, it's available directly from the env that your backend service holds and passes down to plugins. See for example https://github.com/backstage/backstage/blob/a85af4ff836735b003c2bcff3767cbebe7717103/packages/backend/src/plugins/app.ts#L26

**Comment by ch-enfuse** [comment]
Thank you! that definitely clears things out 😃

**Comment by alexef** [comment]
also ran into this today while trying to organize catalog customizations into a plugin. had to split them into two plugins, one for frontend and one for backend. wish this was more intuitive
