### ISSUE TITLE
🐛 Bug Report: iframe not showing up in techdocs for youtube.com

### ISSUE THREAD

**Issue by sqsp-rwatkins** [backstage/backstage#15343]
### 📜 Description

I placed an `iframe` in a markdown page rendered by techdocs and added the necessary config to app-config.yaml.

The iframe was missing on the rendered HTML file.

This works with `drive.google.com` but not `youtube.com`

### 👍 Expected behavior

backstage should attempt to render iframe content.

### 👎 Actual Behavior with Screenshots

`iframe`s are scrubbed from the generated HTML.

iframe placed in markdown:
```
# Video example

Lorem ipsum dolor sit amet test

<div class="test">
<iframe src="https://www.youtube.com/embed/LXb3EKWsInQ" width="640" height="480" allow="autoplay"></iframe>
</div>
```

The rendered HTML. Notice the `div` with classname `test` is empty
![image](https://user-images.githubusercontent.com/114502094/208727553-10e089c1-45d4-446d-b0a2-8f97e480edd8.png)

### 👟 Reproduction steps

1. Add the following config to `app-config.yaml`:
```
techdocs:
  sanitizer:
    allowedIframeHosts:
      - youtube.com
```
2. Register a component with a valid mkdocs.yaml file and markdown file in `docs/` containing an iframe
3. View the component's documentation in backstage and note the missing iframe

### 📃 Provide the context for the Bug.

Attempting to allow people to add iframes, specifically videos to documentation

### 🖥️ Your Environment

```
OS:   Linux 5.10.124-linuxkit - linux/arm64
node: v16.19.0
yarn: 1.22.19
cli:  0.19.0 (installed)
backstage:  1.6.0

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-common                        0.15.2, 0.16.0
  @backstage/backend-plugin-api                    0.1.3
  @backstage/backend-tasks                         0.3.6, 0.3.7
  @backstage/catalog-client                        1.1.1, 1.1.2
  @backstage/catalog-model                         1.1.2, 1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.19.0
  @backstage/config-loader                         1.1.5, 1.1.6
  @backstage/config                                1.0.3, 1.0.4
  @backstage/core-app-api                          1.1.1
  @backstage/core-components                       0.11.2, 0.12.0, 0.9.5
  @backstage/core-plugin-api                       1.0.7, 1.1.0
  @backstage/dev-utils                             1.0.7
  @backstage/errors                                1.1.2, 1.1.3
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.3.2, 1.4.0
  @backstage/plugin-api-docs                       0.8.10
  @backstage/plugin-app-backend                    0.3.37
  @backstage/plugin-auth-backend                   0.16.0
  @backstage/plugin-auth-node                      0.2.6
  @backstage/plugin-catalog-backend-module-github  0.1.8
  @backstage/plugin-catalog-backend                1.5.0
  @backstage/plugin-catalog-common                 1.0.7, 1.0.8
  @backstage/plugin-catalog-graph                  0.2.22
  @backstage/plugin-catalog-import                 0.8.12
  @backstage/plugin-catalog-node                   1.2.0
  @backstage/plugin-catalog-react                  1.2.0, 1.2.1
  @backstage/plugin-catalog                        1.6.0
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-home                           0.4.26
  @backstage/plugin-kubernetes-backend             0.7.3
  @backstage/plugin-kubernetes-common              0.4.3
  @backstage/plugin-kubernetes                     0.7.3
  @backstage/plugin-lighthouse                     0.3.10
  @backstage/plugin-org                            0.5.10
  @backstage/plugin-pagerduty                      0.5.3
  @backstage/plugin-permission-common              0.6.4, 0.7.0, 0.7.1
  @backstage/plugin-permission-node                0.6.5, 0.7.0
  @backstage/plugin-permission-react               0.4.6, 0.4.7
  @backstage/plugin-proxy-backend                  0.2.31
  @backstage/plugin-scaffolder-backend             1.7.0
  @backstage/plugin-scaffolder-common              1.2.1
  @backstage/plugin-scaffolder                     1.7.0
  @backstage/plugin-search-backend-module-pg       0.4.2
  @backstage/plugin-search-backend-node            1.0.3, 1.0.4
  @backstage/plugin-search-backend                 1.1.0
  @backstage/plugin-search-common                  1.1.0, 1.1.1
  @backstage/plugin-search-react                   1.2.0
  @backstage/plugin-search                         1.0.3
  @backstage/plugin-sonarqube-backend              0.1.3
  @backstage/plugin-sonarqube                      0.5.0
  @backstage/plugin-stack-overflow                 0.1.6
  @backstage/plugin-tech-radar                     0.5.17
  @backstage/plugin-techdocs-backend               1.4.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5
  @backstage/plugin-techdocs-node                  1.4.1
  @backstage/plugin-techdocs-react                 1.0.5
  @backstage/plugin-techdocs                       1.3.3
  @backstage/plugin-user-settings                  0.4.8
  @backstage/plugin-xcmetrics                      0.2.30
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0, 1.0.1
  @backstage/version-bridge                        1.0.1, 1.0.2
Done in 1.23s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by carlo-colombo** [comment]
Hi, I thought to have the same issue and started debugging. 

I found out that  not closing the `iframe` tag cause DOMPurify (that is used to sanitize) to discard the node because it entered in one of the conditions (/* Detect mXSS attempts abusing namespace confusion */). An additional symptom was that everything after the iframe was also thrown out (as the parser was adding it as a child of the iframe.

Out of curiosity I tried with your example and the iframe is not thrown out.

We are using `@backstage/plugin-techdocs@1.4.0` it depends on `dompurify@2.4.1`

**Comment by sqsp-rwatkins** [comment]
> Hi, I thought to have the same issue and started debugging.
> 
> I found out that not closing the `iframe` tag cause DOMPurify (that is used to sanitize) to discard the node because it entered in one of the conditions (/* Detect mXSS attempts abusing namespace confusion */). An additional symptom was that everything after the iframe was also thrown out (as the parser was adding it as a child of the iframe.
> 
> Out of curiosity I tried with your example and the iframe is not thrown out.
> 
> We are using `@backstage/plugin-techdocs@1.4.0` it depends on `dompurify@2.4.1`

I've looked into this some more and it looks like it is working for Google Drive links but not Youtube links. I've edited the issue title and description to reflect that.

**Comment by soapraj** [comment]
Hi! @sqsp-rwatkins 

It seems to work with the same iframe code for me if you set the host to `www.youtube.com` instead of `youtube.com`, Can you check?

**Comment by sqsp-rwatkins** [comment]
Hey @soapraj

Thanks, that works. Will close the issue.
