### ISSUE TITLE
🐛 Bug Report: TechDocs reader, going to another page in techdocs via link keeps old page vert position

### ISSUE THREAD

**Issue by adrianke77** [backstage/backstage#15356]
### 📜 Description

Hi team, appears to have an error with TechDocs reader where when navigating from one page to another within the Techdocs set, the new page retains the vertical position of the old page instead of going to the top of the new page as normal.

### 👍 Expected behavior

go to top of page when navigating to new page

### 👎 Actual Behavior with Screenshots

goes to middle/bottom of page when navigating to new page (might be retaining same distance from page top as old page? not sure)

### 👟 Reproduction steps

1) go to any long TechDocs page eg https://demo.backstage.io/docs/default/component/backstage/deployment/k8s/

2) scroll down and click on a hotlink that goes to somewhere else in the same set of docs, for above page an example is 'auth provider' about 18 lines up from the bottom of the page

3) after navigating to the new page, the vertical page position is in the middle/bottom of the page instead of at the top

### 📃 Provide the context for the Bug.

Seems duplicatable on any backstage instance, eg the demo instance mentioned in Reproduction steps above

### 🖥️ Your Environment

Seems duplicatable on any backstage instance, eg the demo instance mentioned in Reproduction steps above

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by zcason** [comment]
Can someone assign this issue to me?
