### ISSUE TITLE
🐛 Bug Report: Running Backstage Locally on Apple Silicon

### ISSUE THREAD

**Issue by AndreasPrang** [backstage/backstage#15395]
### 📜 Description

I can not start Backstage as described in documentation on macOS 13.1 running on Apple Silicon. 

https://backstage.io/docs/getting-started/running-backstage-locally

### 👍 Expected behavior

Backend & Frontend is running

### 👎 Actual Behavior with Screenshots

➤ YN0000: └ Completed in 0s 526ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 3s 113ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 976ms
➤ YN0000: Done with warnings in 5s 51ms
❯ yarn start

Error: No existing version was accepted for range ^0.12.0, searching through 0.11.2,0.0.0-use.local, for package @backstage/core-components

❯ yarn dev
[0] 
[0] **Error: No existing version was accepted for range ^0.12.0, searching through 0.11.2,0.0.0-use.local, for package @backstage/core-components**
[0] 
[0] yarn start exited with code 1
[1] Build succeeded

### 👟 Reproduction steps

cd backstage_repo
yarn install
yarn dev

### 🖥️ Your Environment

OS:   Darwin 22.2.0 - darwin/arm64
node: v18.12.1
yarn: 3.2.3
cli:  0.22.0 (local)
backstage:  N/A

Dependencies:
  @backstage/app-defaults                                        0.0.0-use.local
  @backstage/backend-app-api                                     0.0.0-use.local
  @backstage/backend-common                                      0.0.0-use.local
  @backstage/backend-defaults                                    0.0.0-use.local
  @backstage/backend-plugin-api                                  0.0.0-use.local
  @backstage/backend-tasks                                       0.0.0-use.local
  @backstage/backend-test-utils                                  0.0.0-use.local
  @backstage/catalog-client                                      0.0.0-use.local
  @backstage/catalog-model                                       0.0.0-use.local
  @backstage/cli-common                                          0.0.0-use.local
  @backstage/cli                                                 0.0.0-use.local
  @backstage/codemods                                            0.0.0-use.local
  @backstage/config-loader                                       0.0.0-use.local
  @backstage/config                                              0.0.0-use.local
  @backstage/core-app-api                                        0.0.0-use.local
  @backstage/core-components                                     0.0.0-use.local, 0.11.2
  @backstage/core-plugin-api                                     0.0.0-use.local
  @backstage/create-app                                          0.0.0-use.local
  @backstage/dev-utils                                           0.0.0-use.local
  @backstage/errors                                              0.0.0-use.local
  @backstage/integration-aws-node                                0.0.0-use.local
  @backstage/integration-react                                   0.0.0-use.local
  @backstage/integration                                         0.0.0-use.local
  @backstage/plugin-adr-backend                                  0.0.0-use.local
  @backstage/plugin-adr-common                                   0.0.0-use.local
  @backstage/plugin-adr                                          0.0.0-use.local
  @backstage/plugin-airbrake-backend                             0.0.0-use.local
  @backstage/plugin-airbrake                                     0.0.0-use.local
  @backstage/plugin-allure                                       0.0.0-use.local
  @backstage/plugin-analytics-module-ga                          0.0.0-use.local
  @backstage/plugin-apache-airflow                               0.0.0-use.local
  @backstage/plugin-api-docs-module-protoc-gen-doc               0.0.0-use.local
  @backstage/plugin-api-docs                                     0.0.0-use.local
  @backstage/plugin-apollo-explorer                              0.0.0-use.local
  @backstage/plugin-app-backend                                  0.0.0-use.local
  @backstage/plugin-auth-backend                                 0.0.0-use.local
  @backstage/plugin-auth-node                                    0.0.0-use.local
  @backstage/plugin-azure-devops-backend                         0.0.0-use.local
  @backstage/plugin-azure-devops-common                          0.0.0-use.local
  @backstage/plugin-azure-devops                                 0.0.0-use.local
  @backstage/plugin-azure-sites-backend                          0.0.0-use.local
  @backstage/plugin-azure-sites-common                           0.0.0-use.local
  @backstage/plugin-azure-sites                                  0.0.0-use.local
  @backstage/plugin-badges-backend                               0.0.0-use.local
  @backstage/plugin-badges                                       0.0.0-use.local
  @backstage/plugin-bazaar-backend                               0.0.0-use.local
  @backstage/plugin-bazaar                                       0.0.0-use.local
  @backstage/plugin-bitbucket-cloud-common                       0.0.0-use.local
  @backstage/plugin-bitrise                                      0.0.0-use.local
  @backstage/plugin-catalog-backend-module-aws                   0.0.0-use.local
  @backstage/plugin-catalog-backend-module-azure                 0.0.0-use.local
  @backstage/plugin-catalog-backend-module-bitbucket-cloud       0.0.0-use.local
  @backstage/plugin-catalog-backend-module-bitbucket-server      0.0.0-use.local
  @backstage/plugin-catalog-backend-module-bitbucket             0.0.0-use.local
  @backstage/plugin-catalog-backend-module-gerrit                0.0.0-use.local
  @backstage/plugin-catalog-backend-module-github                0.0.0-use.local
  @backstage/plugin-catalog-backend-module-gitlab                0.0.0-use.local
  @backstage/plugin-catalog-backend-module-incremental-ingestion 0.0.0-use.local
  @backstage/plugin-catalog-backend-module-ldap                  0.0.0-use.local
  @backstage/plugin-catalog-backend-module-msgraph               0.0.0-use.local
  @backstage/plugin-catalog-backend-module-openapi               0.0.0-use.local
  @backstage/plugin-catalog-backend                              0.0.0-use.local
  @backstage/plugin-catalog-common                               0.0.0-use.local
  @backstage/plugin-catalog-graph                                0.0.0-use.local
  @backstage/plugin-catalog-graphql                              0.0.0-use.local
  @backstage/plugin-catalog-import                               0.0.0-use.local
  @backstage/plugin-catalog-node                                 0.0.0-use.local
  @backstage/plugin-catalog-react                                0.0.0-use.local
  @backstage/plugin-catalog                                      0.0.0-use.local
  @backstage/plugin-cicd-statistics-module-gitlab                0.0.0-use.local
  @backstage/plugin-cicd-statistics                              0.0.0-use.local
  @backstage/plugin-circleci                                     0.0.0-use.local
  @backstage/plugin-cloudbuild                                   0.0.0-use.local
  @backstage/plugin-code-climate                                 0.0.0-use.local
  @backstage/plugin-code-coverage-backend                        0.0.0-use.local
  @backstage/plugin-code-coverage                                0.0.0-use.local
  @backstage/plugin-codescene                                    0.0.0-use.local
  @backstage/plugin-config-schema                                0.0.0-use.local
  @backstage/plugin-cost-insights-common                         0.0.0-use.local
  @backstage/plugin-cost-insights                                0.0.0-use.local
  @backstage/plugin-dynatrace                                    0.0.0-use.local
  @backstage/plugin-events-backend-module-aws-sqs                0.0.0-use.local
  @backstage/plugin-events-backend-module-azure                  0.0.0-use.local
  @backstage/plugin-events-backend-module-bitbucket-cloud        0.0.0-use.local
  @backstage/plugin-events-backend-module-gerrit                 0.0.0-use.local
  @backstage/plugin-events-backend-module-github                 0.0.0-use.local
  @backstage/plugin-events-backend-module-gitlab                 0.0.0-use.local
  @backstage/plugin-events-backend-test-utils                    0.0.0-use.local
  @backstage/plugin-events-backend                               0.0.0-use.local
  @backstage/plugin-events-node                                  0.0.0-use.local
  @backstage/plugin-explore-backend                              0.0.0-use.local
  @backstage/plugin-explore-common                               0.0.0-use.local
  @backstage/plugin-explore-react                                0.0.0-use.local
  @backstage/plugin-explore                                      0.0.0-use.local
  @backstage/plugin-firehydrant                                  0.0.0-use.local
  @backstage/plugin-fossa                                        0.0.0-use.local
  @backstage/plugin-gcalendar                                    0.0.0-use.local
  @backstage/plugin-gcp-projects                                 0.0.0-use.local
  @backstage/plugin-git-release-manager                          0.0.0-use.local
  @backstage/plugin-github-actions                               0.0.0-use.local
  @backstage/plugin-github-deployments                           0.0.0-use.local
  @backstage/plugin-github-issues                                0.0.0-use.local
  @backstage/plugin-github-pull-requests-board                   0.0.0-use.local
  @backstage/plugin-gitops-profiles                              0.0.0-use.local
  @backstage/plugin-gocd                                         0.0.0-use.local
  @backstage/plugin-graphiql                                     0.0.0-use.local
  @backstage/plugin-graphql-backend                              0.0.0-use.local
  @backstage/plugin-home                                         0.0.0-use.local
  @backstage/plugin-ilert                                        0.0.0-use.local
  @backstage/plugin-jenkins-backend                              0.0.0-use.local
  @backstage/plugin-jenkins-common                               0.0.0-use.local
  @backstage/plugin-jenkins                                      0.0.0-use.local
  @backstage/plugin-kafka-backend                                0.0.0-use.local
  @backstage/plugin-kafka                                        0.0.0-use.local
  @backstage/plugin-kubernetes-backend                           0.0.0-use.local
  @backstage/plugin-kubernetes-common                            0.0.0-use.local
  @backstage/plugin-kubernetes                                   0.0.0-use.local
  @backstage/plugin-lighthouse                                   0.0.0-use.local
  @backstage/plugin-newrelic-dashboard                           0.0.0-use.local
  @backstage/plugin-newrelic                                     0.0.0-use.local
  @backstage/plugin-org-react                                    0.0.0-use.local
  @backstage/plugin-org                                          0.0.0-use.local
  @backstage/plugin-pagerduty                                    0.0.0-use.local
  @backstage/plugin-periskop-backend                             0.0.0-use.local
  @backstage/plugin-periskop                                     0.0.0-use.local
  @backstage/plugin-permission-backend                           0.0.0-use.local
  @backstage/plugin-permission-common                            0.0.0-use.local
  @backstage/plugin-permission-node                              0.0.0-use.local
  @backstage/plugin-permission-react                             0.0.0-use.local
  @backstage/plugin-playlist-backend                             0.0.0-use.local
  @backstage/plugin-playlist-common                              0.0.0-use.local
  @backstage/plugin-playlist                                     0.0.0-use.local
  @backstage/plugin-proxy-backend                                0.0.0-use.local
  @backstage/plugin-rollbar-backend                              0.0.0-use.local
  @backstage/plugin-rollbar                                      0.0.0-use.local
  @backstage/plugin-scaffolder-backend-module-cookiecutter       0.0.0-use.local
  @backstage/plugin-scaffolder-backend-module-rails              0.0.0-use.local
  @backstage/plugin-scaffolder-backend-module-yeoman             0.0.0-use.local
  @backstage/plugin-scaffolder-backend                           0.0.0-use.local
  @backstage/plugin-scaffolder-common                            0.0.0-use.local
  @backstage/plugin-scaffolder                                   0.0.0-use.local
  @backstage/plugin-search-backend-module-elasticsearch          0.0.0-use.local
  @backstage/plugin-search-backend-module-pg                     0.0.0-use.local
  @backstage/plugin-search-backend-node                          0.0.0-use.local
  @backstage/plugin-search-backend                               0.0.0-use.local
  @backstage/plugin-search-common                                0.0.0-use.local
  @backstage/plugin-search-react                                 0.0.0-use.local
  @backstage/plugin-search                                       0.0.0-use.local
  @backstage/plugin-sentry                                       0.0.0-use.local
  @backstage/plugin-shortcuts                                    0.0.0-use.local
  @backstage/plugin-sonarqube-backend                            0.0.0-use.local
  @backstage/plugin-sonarqube-react                              0.0.0-use.local
  @backstage/plugin-sonarqube                                    0.0.0-use.local
  @backstage/plugin-splunk-on-call                               0.0.0-use.local
  @backstage/plugin-stack-overflow-backend                       0.0.0-use.local
  @backstage/plugin-stack-overflow                               0.0.0-use.local
  @backstage/plugin-tech-insights-backend-module-jsonfc          0.0.0-use.local
  @backstage/plugin-tech-insights-backend                        0.0.0-use.local
  @backstage/plugin-tech-insights-common                         0.0.0-use.local
  @backstage/plugin-tech-insights-node                           0.0.0-use.local
  @backstage/plugin-tech-insights                                0.0.0-use.local
  @backstage/plugin-tech-radar                                   0.0.0-use.local
  @backstage/plugin-techdocs-addons-test-utils                   0.0.0-use.local
  @backstage/plugin-techdocs-backend                             0.0.0-use.local
  @backstage/plugin-techdocs-module-addons-contrib               0.0.0-use.local
  @backstage/plugin-techdocs-node                                0.0.0-use.local
  @backstage/plugin-techdocs-react                               0.0.0-use.local
  @backstage/plugin-techdocs                                     0.0.0-use.local
  @backstage/plugin-todo-backend                                 0.0.0-use.local
  @backstage/plugin-todo                                         0.0.0-use.local
  @backstage/plugin-user-settings-backend                        0.0.0-use.local
  @backstage/plugin-user-settings                                0.0.0-use.local
  @backstage/plugin-vault-backend                                0.0.0-use.local
  @backstage/plugin-vault                                        0.0.0-use.local
  @backstage/plugin-xcmetrics                                    0.0.0-use.local
  @backstage/release-manifests                                   0.0.0-use.local
  @backstage/repo-tools                                          0.0.0-use.local
  @backstage/test-utils                                          0.0.0-use.local
  @backstage/theme                                               0.0.0-use.local
  @backstage/types                                               0.0.0-use.local
  @backstage/version-bridge                                      0.0.0-use.local

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
This was addressed in a pull request a few hours ago. https://github.com/backstage/backstage/pull/15364 Unfortunately that has therefore not yet been released. The next release (on a `-next` line) is on Tuesday.

**Comment by AndreasPrang** [comment]
This solved my problem: 
**yarn add @backstage/core-components@0.12.2**
yarn dev

**Comment by benjdlambert** [comment]
@AndreasPrang if you're just running from a fork of the main repo and not using `npx @backstage/create-app` then you can just pull from upstream as @freben mentioned it was fixed recently. I don't think this bug affected any `npx @backstage/create-app` installations, just the main repository.

**Comment by AndreasPrang** [comment]
@benjdlambert Right. npx @backstage/create-app works perfect. 

For main repository I have to... 

nvm install 18
git clone  https://github.com/backstage/backstage.git
cd backstage
yarn install
yarn add @backstage/core-components@0.12.2
yarn dev

**Comment by Rugvip** [comment]
Gonna close as this was fixed in #15364
