### ISSUE TITLE
🐛 Bug Report: empty `metadata.description` causes entity to fail ingestion, even though description is optional

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#15410]
### 📜 Description

Whilst `metadata.description` is listed as optional, having an empty description will cause an entity to fail to be ingested 

### 👍 Expected behavior

As the description is optional, the entity should be injected the same was as it would have been if `metadata.description` had not been provided.

### 👎 Actual Behavior with Screenshots

> [1] 2022-12-23T12:45:58.126Z catalog warn Policy check failed for component:default/foo; caused by Error: Malformed envelope, /metadata/description must be string type=plugin entity=component:default/foo location=...

### 👟 Reproduction steps

Try to ingest the following: 
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: foo
  description:
spec:
  type: service
  lifecycle: experimental
  owner: foo
```

### 📃 Provide the context for the Bug.

Because this error causes an entity to fail ingestion, it can be very challenging to work out what is goign on w/out reviewign the backstage logs.  We are noticing several of these errors in our logs as we are onboarding teams

### 🖥️ Your Environment

I can repro this in our prod isntance running 1.7.1, 1.83 as well as my local version just upgraded to 1.9.1

```
OS:   Linux 5.15.79.1-microsoft-standard-WSL2 - linux/x64
node: v16.14.0
yarn: 1.22.19
cli:  0.22.0 (installed)
backstage:  1.8.3

Dependencies:
  @backstage/app-defaults                          1.0.8
  @backstage/backend-common                        0.16.0
  @backstage/backend-plugin-api                    0.1.4
  @backstage/backend-tasks                         0.3.7
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.21.1
  @backstage/config-loader                         1.1.6
  @backstage/config                                1.0.4
  @backstage/core-app-api                          1.2.0
  @backstage/core-components                       0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/dev-utils                             1.0.8
  @backstage/errors                                1.1.3
  @backstage/integration-react                     1.1.6
  @backstage/integration                           1.4.0
  @backstage/plugin-api-docs                       0.8.11
  @backstage/plugin-app-backend                    0.3.38
  @backstage/plugin-auth-backend                   0.17.1
  @backstage/plugin-auth-node                      0.2.7
  @backstage/plugin-azure-devops-backend           0.3.17
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.2.2
  @backstage/plugin-catalog-backend-module-azure   0.1.9
  @backstage/plugin-catalog-backend-module-github  0.2.1
  @backstage/plugin-catalog-backend-module-msgraph 0.4.4
  @backstage/plugin-catalog-backend                1.5.1
  @backstage/plugin-catalog-common                 1.0.8
  @backstage/plugin-catalog-graph                  0.2.23
  @backstage/plugin-catalog-import                 0.9.1
  @backstage/plugin-catalog-node                   1.2.1
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.6.1
  @backstage/plugin-explore-react                  0.0.23
  @backstage/plugin-explore                        0.3.42
  @backstage/plugin-github-actions                 0.5.11
  @backstage/plugin-github-pull-requests-board     0.1.5
  @backstage/plugin-home                           0.4.27
  @backstage/plugin-org                            0.6.1
  @backstage/plugin-permission-common              0.7.1
  @backstage/plugin-permission-node                0.7.1
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.32
  @backstage/plugin-scaffolder-backend             1.8.0
  @backstage/plugin-scaffolder-common              1.2.2
  @backstage/plugin-scaffolder                     1.8.0
  @backstage/plugin-search-backend-module-pg       0.4.2
  @backstage/plugin-search-backend-node            1.0.4
  @backstage/plugin-search-backend                 1.1.1
  @backstage/plugin-search-common                  1.1.1
  @backstage/plugin-search-react                   1.2.1
  @backstage/plugin-search                         1.0.4
  @backstage/plugin-stack-overflow                 0.1.7
  @backstage/plugin-tech-radar                     0.5.18
  @backstage/plugin-techdocs-backend               1.4.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.6
  @backstage/plugin-techdocs-node                  1.4.2
  @backstage/plugin-techdocs-react                 1.0.6
  @backstage/plugin-techdocs                       1.4.0
  @backstage/plugin-user-settings                  0.5.1
  @backstage/release-manifests                     0.0.7
  @backstage/test-utils                            1.2.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1
  @backstage/version-bridge                        1.0.2
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
If you parse that YAML, it'll actually end up being `description: null`, and we have no idea whether the user explicitly wrote `null` there or whether it is implicit.

Some possible remediations:

1. Blanket-remove all null-valued keys at a framework level and hope there's never a real use case for actual nulls
2. Have some kind of special treatment for known optional fields in the [BuiltinKindsEntityProcessor](https://github.com/backstage/backstage/blob/6ab9bfd301aca4b91be74e83aa9e0f79ffca8321/plugins/catalog-backend/src/modules/core/BuiltinKindsEntityProcessor.ts#L59) so it can clear them away before validation happens
3. Write a custom private processor which in its `preProcessEntity` method does the same field clearing to make your particular installation more forgiving than the default; this will happen before validation, so should achieve the goal too

The last one is a way for you to get unblocked immediately without code change. The rest I think is up for discussion; do we WANT to be forgiving or strict?

How did you end up with the empty value in the first place? Is it because of template/variable expansion or something similar?

**Comment by afscrome** [comment]
Did some more digging on this, and all the errors were coming from a single `catalog-info.yaml` file, so I'm guessing someone made that mistake initially, then copypasta.

Following on from our discord discussion, my inclination is that the real issue here is that errors around first time entity errors aren't surfaced well.  My original thinking was that the catalog was expected to be as permissive as possible to start with so we can get enough of entity to show users the error.  Once there's a better way of surfacing these errors, I'm not sure this is too important.

**Comment by freben** [comment]
Yeah but as a consumer of the catalog, you want to be able to trust that the data you read actually is valid according to the expected schema and TS types. So the two desires are incompatible with one another :/ Therefore the error signaling mechanism might have to not be on the entity itself, or something like that, to make this work.

**Comment by afscrome** [comment]
Oh sorry, I should have been more specific - I meant that once there's a better way of surfacing errors, I'm not sure it's as important to change the current behaviour of rejecting null descriptions.

That said, it may be useful to get access to the partially processed state for diagnostic purposes.  (Particularly if the entity got far enough to give you an owner who can action the error).  But if that is done, it shouldn't in a way that someone has to explicitly opt in to getting broken entities.  (e.g. a seperate diagnostics api)
