### ISSUE TITLE
🚀 Feature: Programatically setting knex database options

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#15416]
### 🔖 Feature description

To use knex to authenticate with a short lived token, you need to pass in an `expirationChecker` function to the knex configuration object.  However the database configuration is only exposed through yaml, which has no way of passing such a function.

https://knexjs.org/guide/#configuration-options
```js
    return {
      host : 'your_host',
      port : 3306,
      user : 'your_database_user',
      database : 'myapp_test',
      password : token,
      expirationChecker: () => {
        return tokenExpiration <= Date.now();
      }
``` 

### 🎤 Context

In my case, I'm specifically looking at authenticating with PosgreSql using Azure AD authentication, which involves using a short lived access token as the password.

https://learn.microsoft.com/en-us/azure/postgresql/single-server/how-to-configure-sign-in-azure-ad-authentication#authenticate-with-azure-ad-as-a-single-user

https://discordapp.com/channels/687207715902193673/687235481154617364/1054814021846577254

### ✌️ Possible Implementation

Suggested by @freben in discord
> Could be that it'd be possible to add additional knex runtime options to the database manager at runtime, but there's no such mechanism at the moment
like, to these options https://github.com/backstage/backstage/blob/415cd3245064d10e63688fd3c5cf8601893205e1/packages/backend-common/src/database/DatabaseManager.ts#L47

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
+1, let's add something to `DatabaseManagerOptions`. I think we can make it pretty low level as this should be a pretty low-level customization. We could for example add an option param that is something like `getOptionsForPlugin(pluginId: string, configuredOptions: object)`
