### ISSUE TITLE
🚀 Feature: Improve first run experience after running npx @backstage/create-app`

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#15415]
### 🔖 Feature description

After creating an a new backstage app with `npx @backstage/create-app`, it suggests you 
![image](https://user-images.githubusercontent.com/289860/209367831-83af45f9-1b05-490c-b822-16ede41a2795.png)

OK, let's run that command:
![image](https://user-images.githubusercontent.com/289860/209367868-757b3871-a807-4682-9547-1e94f596baeb.png)

A few other warnigns also show up
![image](https://user-images.githubusercontent.com/289860/209368295-2b91354a-0a60-4171-a745-3d38fedfca77.png)
![image](https://user-images.githubusercontent.com/289860/209368356-0988aba2-2246-4b98-8e7e-a943dc025b0b.png)

A slightly unnerving start after following the installation instructions.

### 🎤 Context

My expectation after following the installation instructions would be for there to be no errors or warnings.  Especially consider that quite a few things have gone on for hte setup (installing node, pre-requisite packages etc.), so someone may be feeling a bit unsure of themselves.

If there are any warnings, I'd expect to be clear why the warning.  

### ✌️ Possible Implementation

The git errors seem to be caused as the create-app template doesn't initalise a git repo.  I beleive at one point the template did initalise a git repo, but I think that was rolled back, so a second option would be to either supress the warnigns completely (I assume this is used to populate the commit hash in `BUILD_INFO` which isn't used by anything by default.  Alternatively replace it with a warning with an action on how to fix the problem:

> Unable to detect commit version.  To fix this, run "git init && git commit -m 'Initial Commit'" to create a repository and initial commit. 

For the `Can't serve static app content from ${staticDir}, directory doesn't exist` warning, as far as I can tell, you wouldn't typically expect the `dist` directory to be there in development, so maybe this warning could be supressed if `NODE_ENV` is development.  Alternatively the message could be rephrased to better explain what the problem is, and what action needs to be taken. e.g.
 
> Backstage front end hasn't been prebuild.  This is fine for local dev, but should be avoided in production.  See https://backstage.io/docs/local-dev/cli-build-system for details."

Similarly I suspect hte Techdocs warning can either be removed, or rephrased to provide details on how to fix the warning.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Thank you, good call!

A git repo is actually initialized, I think you might need to `npx @backstage/create-app@latest` to make sure you're getting the latest version. Docs are updated to suggest that too.

Fixed the app backend bit over in #15460. @backstage/techdocs-core could you have a look at the search bit?

**Comment by afscrome** [comment]
I can't reproduce the git issue with `npx @backstage/create-app@latest` so thats all good.

**Comment by jhaals** [comment]
Great! Closing this issue

**Comment by afscrome** [comment]
@jhaals Can you re-open - there is still a warning coming from techdocs 
![image](https://user-images.githubusercontent.com/289860/210777175-c233dad8-c53a-4cc3-9865-e50cf0d0874b.png)
