### ISSUE TITLE
🐛 Bug Report: Techdocs mkdocs default background styling looks weird

### ISSUE THREAD

**Issue by BeneStem** [backstage/backstage#15420]
### 📜 Description

The techdocs mkdocs styling `--md-default-bg-color: #fff` causes Mkdocs Navbar title `md-nav__title` and Table of contents title `same class` to have a strangely looking white background.

### 👍 Expected behavior

Not have a background at all.

### 👎 Actual Behavior with Screenshots

<img width="1830" alt="image" src="https://user-images.githubusercontent.com/2619581/209454738-671229b3-f378-453c-8b72-40ea707f2e34.png">

### 👟 Reproduction steps

Open default docs of sample techdocs entity.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by soapraj** [comment]
HI! @BeneStem 

Can you give some more info about your environment and the version of packages you are running? 

For package versions you can get them from `yarn backstage-cli info`. 

I am unable to repro this issue in our demo environment in light mode. For ex in this page: https://demo.backstage.io/docs/default/component/backstage/getting-started/create-an-app/

**Comment by BeneStem** [comment]
Hey there. Sorry for my late response. I found the issue.

I used my local material-mkdocs installation which already uses a newer version than backstage supports.

Some styling was changed in that newer version thus the strange looking backgrounds.
