### ISSUE TITLE
🐛 Bug Report: Overriding style of some components breaks the styling

### ISSUE THREAD

**Issue by omerfarukdogan** [backstage/backstage#15427]
### 📜 Description

We noticed that when we try to override style of some components, they get broken. For example, `BackstageSidebarDivider`.`root` and `BackstageSidebar`.`drawer`.

### 👍 Expected behavior

The styling should be applied without breaking the component.

### 👎 Actual Behavior with Screenshots

It breaks the component.        

### 👟 Reproduction steps

1. Apply the following theme override:

        BackstageSidebarDivider: {
            root: {
                backgroundColor: "red",
            }
        },

2. The divider component gets broken and becomes a point. Moreover, its color is not changed.

Before:
![image](https://user-images.githubusercontent.com/8117265/209556955-d4abe3c3-9d82-44f6-aafb-c83a5317fbc7.png)

After:
![image](https://user-images.githubusercontent.com/8117265/209557022-e31a3b86-3ff2-44cd-a2cb-a36b59bae599.png)

### 📃 Provide the context for the Bug.

We didn't have such an issue for `BackstageSidebarDivider` with Backstage v1.7.1. It appeared when we updated to v1.9.1. The bug for this specific component might be introduced with [this commit](https://github.com/backstage/backstage/commit/b0efeb8221188f3a8094d3eeb9378c64e9f7ae00#diff-228bdd0b6adf4855d9d3da007abd163ea5257be38fd779f9b9f884638fd887e1R623-R630).

### 🖥️ Your Environment

OS:   Linux 5.10.16.3-microsoft-standard-WSL2 - linux/x64
node: v16.16.0
yarn: 1.22.19
cli:  0.22.0 (installed)
backstage:  1.9.1

Dependencies:
  @backstage/app-defaults                            1.0.10
  @backstage/backend-common                          0.17.0
  @backstage/backend-plugin-api                      0.2.0
  @backstage/backend-tasks                           0.4.0
  @backstage/catalog-client                          1.2.0
  @backstage/catalog-model                           1.1.4
  @backstage/cli-common                              0.1.11
  @backstage/cli                                     0.22.0
  @backstage/config-loader                           1.1.7
  @backstage/config                                  1.0.5
  @backstage/core-app-api                            1.3.0
  @backstage/core-components                         0.12.2
  @backstage/core-plugin-api                         1.2.0
  @backstage/dev-utils                               1.0.10
  @backstage/errors                                  1.1.4
  @backstage/integration-aws-node                    0.1.0
  @backstage/integration-react                       1.1.8
  @backstage/integration                             1.4.1
  @backstage/plugin-api-docs                         0.8.13
  @backstage/plugin-app-backend                      0.3.39
  @backstage/plugin-auth-backend                     0.17.2
  @backstage/plugin-auth-node                        0.2.8
  @backstage/plugin-bitbucket-cloud-common           0.2.2
  @backstage/plugin-catalog-backend-module-bitbucket 0.2.6
  @backstage/plugin-catalog-backend                  1.6.0
  @backstage/plugin-catalog-common                   1.0.9
  @backstage/plugin-catalog-graph                    0.2.25
  @backstage/plugin-catalog-import                   0.9.3
  @backstage/plugin-catalog-node                     1.3.0
  @backstage/plugin-catalog-react                    1.2.3
  @backstage/plugin-catalog                          1.7.1
  @backstage/plugin-github-actions                   0.5.13
  @backstage/plugin-home                             0.4.29
  @backstage/plugin-org                              0.6.3
  @backstage/plugin-permission-common                0.7.2
  @backstage/plugin-permission-node                  0.7.2
  @backstage/plugin-permission-react                 0.4.8
  @backstage/plugin-proxy-backend                    0.2.33
  @backstage/plugin-scaffolder-backend               1.9.0
  @backstage/plugin-scaffolder-common                1.2.3
  @backstage/plugin-scaffolder                       1.9.1
  @backstage/plugin-search-backend-module-pg         0.5.0
  @backstage/plugin-search-backend-node              1.1.0
  @backstage/plugin-search-backend                   1.2.0
  @backstage/plugin-search-common                    1.2.0
  @backstage/plugin-search-react                     1.3.1
  @backstage/plugin-search                           1.0.6
  @backstage/plugin-sonarqube-backend                0.1.4
  @backstage/plugin-sonarqube-react                  0.1.0
  @backstage/plugin-sonarqube                        0.6.1
  @backstage/plugin-stack-overflow                   0.1.9
  @backstage/plugin-tech-radar                       0.5.20
  @backstage/plugin-techdocs-backend                 1.5.0
  @backstage/plugin-techdocs-module-addons-contrib   1.0.8
  @backstage/plugin-techdocs-node                    1.4.3
  @backstage/plugin-techdocs-react                   1.1.1
  @backstage/plugin-techdocs                         1.4.2
  @backstage/plugin-user-settings-backend            0.1.3
  @backstage/plugin-user-settings                    0.6.1
  @backstage/release-manifests                       0.0.8
  @backstage/test-utils                              1.2.3
  @backstage/theme                                   0.2.16
  @backstage/types                                   1.0.2
  @backstage/version-bridge                          1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
This seems like a MUI bug to me, but not sure. From what I can tell it's because of the `theme` access via callback in the styled `SidebarDivider` component. Refactoring it to only use hardcoded values work, but that also breaks the spacing. It could also be that it's simply unsupported from the MUI side.

A workaround for now would be to define your own divider component, seeing as that's all set up in the app anyway.

**Comment by relaxedleaf** [comment]
@Rugvip Do you mind sharing some of the resources to show how I can replace all the `SidebarDivider` with custom ones? Thank you

**Comment by relaxedleaf** [comment]
> This seems like a MUI bug to me, but not sure. From what I can tell it's because of the `theme` access via callback in the styled `SidebarDivider` component. Refactoring it to only use hardcoded values work, but that also breaks the spacing. It could also be that it's simply unsupported from the MUI side.
> 
> A workaround for now would be to define your own divider component, seeing as that's all set up in the app anyway.

Do you mind sharing some of the resources to show how I can replace all the SidebarDivider with custom ones? Thank you

**Comment by Rugvip** [comment]
@relaxedleaf sure! The current divider is defined like this:

```tsx
const SidebarDivider = styled('hr')(({ theme }) => ({
  height: 1,
  width: '100%',
  background: '#383838',
  border: 'none',
  margin: theme.spacing(1.2, 0),
}));
```

Just copy that and replace the styling with whatever you need, and use that component in place of the current divider.

**Comment by Rugvip** [comment]
Let's continue this discussion in #16693
