### ISSUE TITLE
🐛 Bug Report: FilterRow component is not working

### ISSUE THREAD

**Issue by goodryanboy** [backstage/backstage#15428]
### 📜 Description

So I want to customized the Filter to meet our Figma design, So i try to override the filter component using **FilterRow** but its not updating instead its just showing the default filter
this is my code

      <Table
          components={{
            FilterRow: (rowProps) => {
              const { columns, onFilterChanged } = rowProps;
              return (
                <>
                  <tr>
                    {columns.map((col) => {
                      if (col.field) {
                        return (
                          <td>
                            <input
                              placeholder="custom filter"
                              id={col.field}
                              onChange={(e) => {
                                onFilterChanged(col.tableData.id, e.target.value);
                              }}
                            />
                          </td>
                        );
                      }
                    })}
                  </tr>
                </>
              );
            },
          }}
        />

### 👍 Expected behavior

It should update the UI on the filter

### 👎 Actual Behavior with Screenshots

It actually just display the default UI

### 👟 Reproduction steps

Its Component Issue

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
As far as I know you also need to enable filtering for the filter row to show up, try adding `options={{ filtering: true }}` to the table component.

**Comment by goodryanboy** [comment]
Yeah I did try that, but its not showing the custom components on the left side of the table instead its only showing above each column, So its not possible to customized the Backstage Table filter right?

**Comment by Rugvip** [comment]
@goodryanboy Ah yeah no you can't customize the ones to the left

**Comment by goodryanboy** [comment]
Thanks for confirming @Rugvip
