### ISSUE TITLE
🚀 Feature: Field Extension to display group entities a user is part of

### ISSUE THREAD

**Issue by rikez** [backstage/backstage#15456]
### 🔖 Feature description

A new Custom Field Extension that recursively lists all the groups (and groups that have other groups as children) that have the signed in users as a member.

Feature suggested in https://github.com/backstage/backstage/pull/15063#issuecomment-1365774248

### 🎤 Context

In my use-case we have created various Scaffolder Templates to create Git repositories and other resources. Part of this process is to define an owner for these repositories and resources, and so we use the OwnerPicker component. However, we would like to restrict the displayed groups to only the ones the user is a member of, including groups that have groups as children. With this, we can ensure users can only select groups they belong to.

### ✌️ Possible Implementation

I couldn't think of a way to get all groups (recursively) in a single query, but something like this might work. My concern is the performance of this component given the number of requests it might make.

```ts
async function getGroupsForUserInContext(entities: Entity[], filters: any): Promise<Entity[]> {
  const resultEntities = await catalogApi.getEntities(filters);
  
  const concatEntities = entities.concat(resultEntities);
  
  const children = entities.map((e) => e.children.map((c) => c.name)).flat()
  if (children.length === 0) {
    return concatEntities;
  }

  return getGroupsForUserInContext(concatEntities, {
    kind: 'Group',
    'metadata.name': children
  })
}

export const GroupPicker = (props: GroupPickerProps) => {
  const {
    schema: { title = 'Group', description = '...' },
    uiSchema,
    ...restProps
  } = props;

  const catalogFilter = {
    kind:'Group',
    'spec.members':  <current user ref>
  };

  const { value: groups, loading } = useAsync(() =>
    getGroupsForUserInContext([], catalogFilter),
  );

  return (
    <>
      groups
    </>
  );
};
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Makes sense! 👍 

I feel perhaps the simplest and probably correct way to go about this is to either extend or have a separate `OwnerPicker` that uses the `IdentityApi` to fetch `ownershipEntityRefs` and display those as the options. The ownership entity refs are by definition the org entities that a user is able to claim ownership through, and so I think it makes sense to display those as the available options. More info available over here: https://backstage.io/docs/auth/identity-resolver#backstage-user-identity, and docs for `identityApiRef` over here: https://backstage.io/docs/reference/core-plugin-api.identityapiref.

**Comment by jhaals** [comment]
in progress here #17608

**Comment by rikez** [comment]
Should we close this issue since https://github.com/backstage/backstage/pull/17608 got merged?

**Comment by freben** [comment]
Yes!
