### ISSUE TITLE
🐛 Bug Report: `initialState` of `CatalogGraphPage` is not respected

### ISSUE THREAD

**Issue by omerfarukdogan** [backstage/backstage#15458]
### 📜 Description

Setting `initialState` prop of `CatalogGraphPage` is not respected, because it's being overwritten by `EntityCatalogGraphCard`. This seems to be introduced with #14466. We'd like this change to be reverted, since it makes initialState of `CatalogGraphPage` pointless.

### 👍 Expected behavior

When I set `maxDepth: 1` as the initial state of `CatalogGraphPage`, I expect the page to open with maxDepth set to 1.

### 👎 Actual Behavior with Screenshots

maxDepth is initially set to 2.

### 👟 Reproduction steps

1. Have the following configuration for CatalogGraphPage:
```
<Route path="/catalog-graph" element={
  <CatalogGraphPage initialState={{ maxDepth: 1 }} />
}/>
```

2. Go to an entity page.
3. Click the "View more" button in "Relations" card.
4. The page opens with maxDepth set to 2 (because it's in the generated url `&maxDepth=2`)

### 📃 Provide the context for the Bug.

We want to set the default `maxDepth` to 1 in Catalog Graph page because otherwise it becomes unresponsive. We have been using `initialState` prop of `CatalogGraphPage` to achieve this. When we were on v1.7.1, it worked as we expected. Upon upgrading to v1.9.1, we noticed that the initialState is no longer respected, because "View graph" button of the `EntityCatalogGraphCard` is setting `maxDepth` parameter explicitly.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Fixing this over in #15504. It is actually respected, but the query parameters have higher priority.
