### ISSUE TITLE
🚀 Feature: Ability to have `uiSchema` or `ui:options` in the validation function

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#15465]
### 🔖 Feature description

Want to be able to see the props that were passed into the `CustomFieldExtension` when calling the validation function without having to pass additional context into the `onChange` handler.

### 🎤 Context

Want to be able to grab maybe the `regex` pattern that a field was called with the validate it in the `validation` function.

### ✌️ Possible Implementation

Pass through `uiSchema` part of the `context` option to the field validators.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by hostsamurai** [comment]
Is anybody working on this? I wouldn't mind picking this up.

**Comment by benjdlambert** [comment]
It’s all yours!

**Comment by benjdlambert** [comment]
Fixed by https://github.com/backstage/backstage/pull/16492
