### ISSUE TITLE
🐛 Profile picture does not load for a user.

### ISSUE THREAD

**Issue by gaurav517** [backstage/backstage#15473]
### 📜 Description

trying to load google profile picture of users by setting `picture` in `User.metadata.profile` section.

### 👍 Expected behavior

Profile picture should load without any error.

### 👎 Actual Behavior with Screenshots

```
Refused to load the image 'https://lh3.googleusercontent.com/a/AEdFTp4YsomeGoogleUrl' because it violates the following Content Security Policy directive: "img-src 'self' data:".
```
![image](https://user-images.githubusercontent.com/15346341/210084218-47ebffcf-6d28-4bda-8377-fdcf1b649896.png)

### 👟 Reproduction steps

Set google profile picture url in `User` definition.
Check settings in backstage, picture is not loaded with an error in browser console.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @gaurav517, pretty sure you can fix this with your `backend.csp.img-src` setting in your `app-config.yaml`. I'm just not sure what the exact value would be. I think this might work:

```yaml
img-src: ["'self'", 'https://lh3.googleusercontent.com']
```

**Comment by gaurav517** [comment]
Thanks a lot. Following solved the issue 
```
backend:
    csp:
      connect-src: ["'self'", 'http:', 'https:']
      img-src: ["'self'", 'data:', 'www.google.com', 'lh3.googleusercontent.com']
```
Also including an article that was useful to understand this: https://john-tucker.medium.com/backstage-by-example-part-3-5a1efec3bcb1

Will close the issue.
