### ISSUE TITLE
🐛 Bug Report: Entities not deleted/orphaned properly if they were in an error state before being deleted

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#15521]
### 📜 Description

If an entity is an an error state AND has never been successfully ingested due to errors, it is not properly removed from backstage when removed from the source `catalog-info.yaml` file.  Backstage continues to report processing errors around the deleted entity.  The old entity name is also reserved preventing a valid entity being created in a new location.

### 👍 Expected behavior

Once the entity has been removed from the underlying file:
1. Logs should stop showing errors for the entity.
2. If the entity had never been successfully ingested, the entity name should be freed up so it can be used elsewhere.

The second scenario is problematic as there is no way to free up the entity name so it can be used elsewhere - as the entity wasn't fully ingested, there is no UI to go to to "Unregsiter" the entity.  I know there is an ongoing debate around orphaning vs deletion in general, however I'd argue that specifically int he case where the entity has never been successfully ingested, deletion is the correct move.

### 👎 Actual Behavior with Screenshots

After removing the entity from the original file, the logs continue to report processing errors around the now deleted entity

> [1] 2023-01-03T11:58:48.346Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while postprocessing; caused by Error: Entity reference "INVALID" had missing or empty kind (e.g. did not start with "component:" or similar) type=plugin entity=component:default/bar location=file:REDACTED/catalog-info.yaml

If you try to ingest an entity with the same name from a new location, the entity fails to ingest.  However as the original entity never fully ingested, there is no UI to "Unregister entity" that will free up the name again for use.

> [1] 2023-01-03T12:15:12.068Z catalog warn Detected conflicting entityRef component:default/foo already referenced by file:/REDACTED/catalog-info2.yaml and now also file:/REDACTED/catalog-info.yaml type=plugin

I know there are open questions around whether entities should be deleted or orphaned when they're removed from the underlying catalog files.  Regardless of those, in the case that the entity has never been fully processed, I'd argue it should be deleted regardless.  (As it has never been fully ingested, nothing should realistically be depending on it.

### 👟 Reproduction steps

(Setting ` builder.setProcessingIntervalSeconds(5)` in `catalog.ts` before these stesp speeds everything up`

1. Create a `catalog-info.yaml` file containing the following.  (The component name should be new to your backstage instnace)
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bar
spec:
  type: service
  lifecycle: production
  owner: whatever
  dependsOn:
    - INVALID #This should be fully qualified with the entity kind
```
2.  See a warning (as expected) due to the invalid `dependsOn`
> [1] 2023-01-03T11:58:48.346Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while postprocessing; caused by Error: Entity reference "INVALID" had missing or empty kind (e.g. did not start with "component:" or similar) type=plugin entity=component:default/bar location=file:REDACTED/catalog-info.yaml
3. Remove the entity from the catalog file by replacing the file contents with
```yaml
---
```
4. Create a valid entity with the same namein a new location (e.g. `catalog-info2.yaml`)

### 📃 Provide the context for the Bug.

We're currently onboarding to backstage, and are monitoring the logs to help users fix any errors.  We've encountered a few situations where users have hit this scenario, causign the logs to report spurious errors around entities that no longer exist.

We're also seeing our dev and non prod environments showing different sets of entities, even though they're reading from the same sources, and beleive this to be contributing to that.

### 🖥️ Your Environment

I see this in both my prod & dev environments.  Below is the cli info for my dev machine:
```
OS:   Linux 5.15.79.1-microsoft-standard-WSL2 - linux/x64
node: v16.14.0
yarn: 1.22.19
cli:  0.22.0 (installed)
backstage:  1.8.3

Dependencies:
  @backstage/app-defaults                          1.0.8
  @backstage/backend-common                        0.16.0
  @backstage/backend-plugin-api                    0.1.4
  @backstage/backend-tasks                         0.3.7
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.21.1
  @backstage/config-loader                         1.1.6
  @backstage/config                                1.0.4
  @backstage/core-app-api                          1.2.0
  @backstage/core-components                       0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/dev-utils                             1.0.8
  @backstage/errors                                1.1.3
  @backstage/integration-react                     1.1.6
  @backstage/integration                           1.4.0
  @backstage/plugin-api-docs                       0.8.11
  @backstage/plugin-app-backend                    0.3.38
  @backstage/plugin-auth-backend                   0.17.1
  @backstage/plugin-auth-node                      0.2.7
  @backstage/plugin-azure-devops-backend           0.3.17
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.2.2
  @backstage/plugin-catalog-backend-module-azure   0.1.9
  @backstage/plugin-catalog-backend-module-github  0.2.1
  @backstage/plugin-catalog-backend-module-msgraph 0.4.4
  @backstage/plugin-catalog-backend                1.5.1
  @backstage/plugin-catalog-common                 1.0.8
  @backstage/plugin-catalog-graph                  0.2.23
  @backstage/plugin-catalog-import                 0.9.1
  @backstage/plugin-catalog-node                   1.2.1
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.6.1
  @backstage/plugin-explore-react                  0.0.23
  @backstage/plugin-explore                        0.3.42
  @backstage/plugin-github-actions                 0.5.11
  @backstage/plugin-github-pull-requests-board     0.1.5
  @backstage/plugin-home                           0.4.27
  @backstage/plugin-org                            0.6.1
  @backstage/plugin-permission-common              0.7.1
  @backstage/plugin-permission-node                0.7.1
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.32
  @backstage/plugin-scaffolder-backend             1.8.0
  @backstage/plugin-scaffolder-common              1.2.2
  @backstage/plugin-scaffolder                     1.8.0
  @backstage/plugin-search-backend-module-pg       0.4.2
  @backstage/plugin-search-backend-node            1.0.4
  @backstage/plugin-search-backend                 1.1.1
  @backstage/plugin-search-common                  1.1.1
  @backstage/plugin-search-react                   1.2.1
  @backstage/plugin-search                         1.0.4
  @backstage/plugin-stack-overflow                 0.1.7
  @backstage/plugin-tech-radar                     0.5.18
  @backstage/plugin-techdocs-backend               1.4.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.6
  @backstage/plugin-techdocs-node                  1.4.2
  @backstage/plugin-techdocs-react                 1.0.6
  @backstage/plugin-techdocs                       1.4.0
  @backstage/plugin-user-settings                  0.5.1
  @backstage/release-manifests                     0.0.7
  @backstage/test-utils                            1.2.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1
  @backstage/version-bridge                        1.0.2
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Right, let's see if I get this right.

I think you are right in your observations - that things are working as intended here, but with bad consequences. The entity in `refresh_state` is "effectively" orphaned, but since there's no `final_entities` entry, there's no place to mark it as orphaned in a way that's visible to end users. This surely leads to confusion.

We are looking at whether it's possible to remove the orphaning mechanism _entirely_ some time down the line. But before then, it might be possible to actually implement special-case treatment of these outliers (joining with the final entities table and detecting nulls?) when writing down the results of processing.

I can't commit to looking into addressing it short term personally however. Adding a help wanted label in the mean time.

**Comment by SoccerBoyMalloy** [comment]
My team recently implemented Slack notifications whenever an ingestion error occurs. This issue is causing noise in our alerts since we have no way of removing these entities - we're seeing and being notified about this error on every single ingestion loop.

It'd be great if we could even get a manual workaround for removing these entities.
