### ISSUE TITLE
🚀 Feature: Encrypted user settings store

### ISSUE THREAD

**Issue by manuelscurti** [backstage/backstage#15549]
### 🔖 Feature description

Introduce a layer of encryption to user settings being stored in a database. This layer will be an optional extension of the `DatabaseUserSettingsStore` implementation (that is the only implementation of the `UserSettingsStore` interface at the moment) and it will encrypt and decrypt user settings flowing from/to frontend.  

At the moment, I was thinking of symmetric encryption with a cryptographic key provided by `app-config`. Yet still, a potentially malicious user in the platform team will still be able to decrypt personal user settings (e.g. a personal GitLab token). So I'm also open to suggestions on how to prevent this (without storing any user password).  

### 🎤 Context

In my use case, users of Backstage can set their personal GitLab token. We would like to, at least, not store them in plain text.

### ✌️ Possible Implementation

This could be a possible implementation of a composable `EncryptedUserSettingsStore`:
```ts

export class EncryptedUserSettingsStore implements UserSettingsStore {
  constructor(
    private readonly store: UserSettingsStore,
    private readonly crypto: {
      key: Buffer;
      iv: Buffer;
      algorithm: string;
    },
  ) {
    // We could rely on existing crypto libraries e.g. `crypto`
  }

  async get(options: {
    userEntityRef: string;
    bucket: string;
    key: string;
  }): Promise<UserSetting> {
    const object = await this.store.get(options);

    return {
      ...object,
      value: this.decrypt(object.value),
    };
  }

  async set(options: {
    userEntityRef: string;
    bucket: string;
    key: string;
    value: JsonValue;
  }): Promise<void> {
    return this.store.set({ ...options, value: this.encrypt(options.value) });
  }

  async delete(options: {
    userEntityRef: string;
    bucket: string;
    key: string;
  }): Promise<void> {
    return this.store.delete(options);
  }

  encrypt(value: JsonValue): JsonValue {
    // TODO
  }

  decrypt(value: JsonValue): JsonValue {
    // TODO
  }
}


```

Store encryption will be enabled if a cryptographic key is found in `app-config`. To switch on this feature into existing Backstage deployments, the platform team should manually encrypt already existing settings.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
How come you have your users set a personal access token rather than using OAuth? 😅

**Comment by manuelscurti** [comment]
Users are not authenticated in Backstage using GitLab, but on top of that, we have a custom plugin that allows them to handle the lifecycle of some special entities directly through Backstage (e.g. making commits to the entity's repository, bumping version numbers, etc.).
Perhaps I should have given more context 😅

**Comment by Rugvip** [comment]
@manuelscurti You can have extra auth providers configured, in addition to the one you use for sign-in. Those would just be used for access delegation, i.e. OAuth, which sounds like exactly what you want in this case. You'd configure the GitLab auth and then use the `gitlabAuthApiRef` to grab access tokens with the scopes that you need.

**Comment by manuelscurti** [comment]
That would be great, thanks for pointing out a better solution :) I will close this issue!
