### ISSUE TITLE
🔌 Plugin: Gitlab API to create Deploy Tokens and Access Tokens

### ISSUE THREAD

**Issue by dpfaffenbauer** [backstage/backstage#15544]
### 🔖 Summary

I really enjoy using the Scaffolder, in order for us to make that work, we already implemented some custom plugins. One for example, is to create some Gitlab Tokens (Deploy Tokens and Access Tokens, as well as Project Variables) with the Scaffolder. This can (and should) also implement further Gitlab APIs.

Would you like to have such plugin? i currently don't have the resources to implement the remaining API's though.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Sure! Create a new package named `@backstage/plugin-scaffolder-backend-module-gitlab`, ideally we want to move all gitlab related scaffolder actions into that page as well :)

**Comment by kratosmat** [comment]
Hello,
I am trying to use gitlab:projectAccessToken:create, but it seems not working.
When I try to use the step the result is empty string, but I have tested also the gitlab api using the body in your code and I receive an error:

{
    "error": "expires_at is missing"
}

So, am I wronging something?

Thanks a lot,
Matteo.

**Comment by tudi2d** [comment]
Thanks for the feedback @kratosmat! If I understand you correctly you are running in to an issue with `createGitlabProjectAccessTokenAction`, which was added in the linked PR, correct? The linked PR fixed this issue already so I will close it. I would like to encourage you to create a new issue on the repository to highlight the issue you are running into. Hope we can help you, than to fix your issue there! :)
