### ISSUE TITLE
🔌 Plugin: Scaffolder Sentry API

### ISSUE THREAD

**Issue by dpfaffenbauer** [backstage/backstage#15543]
### 🔖 Summary

I really enjoy using the Scaffolder, in order for us to make that work, we already implemented some custom plugins. One for example, is to create a Sentry Project with the Scaffolder. Would you be happy with me adding that to the official Sentry Plugin?

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Hi @dpfaffenbauer, glad to hear that! Sure, but it's best to create a new package named `@backstage/plugin-scaffolder-backend-module-sentry` so the different concerns are separated :)
