### ISSUE TITLE
🚀 Feature:  Add custom components to the header on Scaffolder Page

### ISSUE THREAD

**Issue by victormorfin97** [backstage/backstage#15563]
### 🔖 Feature description

Currently, if you want to add a custom button or make any customization to the scaffolder page you need to create a custom one. It would be great to allow some customization on it

### 🎤 Context

I want to add another button to the [header content](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/ScaffolderPage/ScaffolderPage.tsx#L94-L106) on scaffolder page like the create button or the support button.

### ✌️ Possible Implementation

Maybe we can add an optional prop to pass the header content and that way we can avoid customizing all the scaffolder page just to add a single button.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Hi! Yes indeed the Scaffolder page is not customisable at this point and needs to be recreated to change. We do want things to be customisable but simply adding new props to the ScaffolderPage component is doing to add a lot of clutter especially if we want to allow customisation further down in it's sub components. We want to tackle this with Adaptable Components which is worked on in https://github.com/backstage/backstage/pull/11819 by @grantila

**Comment by victormorfin97** [comment]
> Hi! Yes indeed the Scaffolder page is not customisable at this point and needs to be recreated to change. We do want things to be customisable but simply adding new props to the ScaffolderPage component is doing to add a lot of clutter especially if we want to allow customisation further down in it's sub components. We want to tackle this with Adaptable Components which is worked on in #11819 by @grantila

Awesome, then I will be following that PR for updates on this. Thanks for the heads up!
