### ISSUE TITLE
🐛 Bug Report: `FetchUrlReader` scheme detection is broken

### ISSUE THREAD

**Issue by mstergianis** [backstage/backstage#15560]
### 📜 Description

I believe it's always been the recommendation to only include the hostname for entries in `backend.reading.allow[].host`, however change in [e3b19937](https://github.com/backstage/backstage/commit/e3b19937884a635bc9028610208637a69fe6b0a9) has had the side effect such that if you include the URL scheme it fails with the following 

```
Backend failed to start up, Error: Port range is not valid: //gitlab.example.com/some-group/some-repo/-/blob/main/catalog-info.yaml
```

Previously the module would accept a scheme.

### 👍 Expected behavior

Not super opinionated, I think this is just a place where we as a community could do a little better. Ultimately it all comes down to better parsing, but what we do with that better parsing is up to opinion.
1. better error messaging. If we want users to not be able to provide the scheme and instead only provide the host (as the key name would suggest) maybe this is an opportunity to give better feedback.
2. Better overall parsing to get the information we want and optionally ignore the scheme. Currently [the approach](https://github.com/backstage/backstage/blob/36adf34001d11cb57544d40a230b4ca2c77177df/packages/backend-common/src/reading/FetchUrlReader.ts#L98) is to assume that after splitting you only receive two elements, but maybe some validation around length here? Perhaps attempting to parse the host as a URL (`try { new URL(host) } catch (e) { }`). I'm trying to avoid a bespoke regex in my suggestions :grimacing: 

### 👎 Actual Behavior with Screenshots

```yaml
# app-config.yaml

# ... any other necessary startup values
backend:
  reading:
    allow:
      - host: http://gitlab.example.com/some-group/some-repo/-/blob/main/catalog-info.yaml
```

Leads to the backend logs
```
Backend failed to start up, Error: Port range is not valid: //gitlab.example.com/some-group/some-repo/-/blob/main/catalog-info.yaml
```

### 👟 Reproduction steps

Create a backstage instance that has an entry in `backend.reading.allow[].host = scheme://hostname.tld/`

Watch it burn

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by jhaals** [comment]
Hi @mstergianis!

The host `host` option needs to be a hostname which makes it `gitlab.example.com` instead of a URL as used in your example. The error message could definitely be better and we would happily accept such a PR 🙏
