### ISSUE TITLE
🐛 Bug Report: Collating search indexing is slow and failed at inserting data from documents_to_insert table to documents table

### ISSUE THREAD

**Issue by iriswang233** [backstage/backstage#15606]
### 📜 Description

Collating documents for techdocs and software-catalog keep failling with timeout error like .

{"level":"error","message":"Collating documents for techdocs failed: error: insert into documents (type, document, hash) select \"type\", \"document\", \"hash\" from \"documents_to_insert\" on conflict (\"hash\") do nothing - canceling statement due to statement timeout","plugin":"search","service":"backstage","type":"plugin"} {"level":"error","message":"Collating documents for software-catalog failed: error: insert into documents (type, document, hash) select \"type\", \"document\", \"hash\" from \"documents_to_insert\" on conflict (\"hash\") do nothing - canceling statement due to statement timeout","plugin":"search","service":"backstage","type":"plugin"}

Current statement_timeout is 5s, it works fine for staging with less data (documents table is 250 MB ), although production has more data, documents table is 360 MB, 5s should also be sufficient.

### 👍 Expected behavior

Collating documents for techdocs and software-catalog  works fine.

### 👎 Actual Behavior with Screenshots

Collating documents for software-catalog and techdocs failed at 
`insert into documents (type, document, hash) select \"type\", \"document\", \"hash\" from \"documents_to_insert\" on conflict (\"hash\") do nothing - canceling statement due to statement timeout`
when there is more data in production.

For staging, this query is successful after a long time. I have checked the `pg_stat_statements ` in staging using 
`select * from pg_stat_statements  where query = 'insert into documents (type, document, hash) select "type", "document", "hash" from "documents_to_insert" on conflict ("hash") do nothing';`

`

calls | total_time | min_time | max_time | mean_time | stddev_time | rows | shared_blks_hit | shared_blks_read | shared_blks_dirtied | shared_blks_written | local_blks_hit | local_blks_read | local_blks_dirtied | local_blks_written | temp_blks_read | temp_blks_written | blk_read_time | blk_write_time
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 4679.825284 | 4679.825284 | 4679.825284 | 4679.825284 | 0 | 0 | 139071 | 7453 | 0 | 0 | 3 | 1896 | 0 | 1023 | 0 | 0 | 3286.667592 | 0
1 | 11371.131656 | 11371.131656 | 11371.131656 | 11371.131656 | 0 | 0 | 221909 | 8543 | 0 | 0 | 23695 | 7342 | 0 | 1021 | 0 | 0 | 423.288968 | 0
1 | 4197.742147 | 4197.742147 | 4197.742147 | 4197.742147 | 0 | 1 | 139107 | 7488 | 8 | 0 | 1 | 1899 | 0 | 1023 | 0 | 0 | 2875.815587 | 0
1 | 10825.297827 | 10825.297827 | 10825.297827 | 10825.297827 | 0 | 0 | 222233 | 8219 | 0 | 0 | 23695 | 7342 | 0 | 1021 | 0 | 0 | 78.340588 | 0
1 | 1286.8494780000000 | 1286.8494780000000 | 1286.8494780000000 | 1286.8494780000000 | 0 | 0 | 142457 | 4067 | 0 | 0 | 3 | 1896 | 0 | 1023 | 0 | 0 | 30.875488 | 0

`
### 👟 Reproduction steps

it happens when there are many documents like 360 MB.

### 📃 Provide the context for the Bug.

Now the searching indexing keeps failing.

I am wondering whether this issue is related to query 
`insert into documents (type, document, hash) select \"type\", \"document\", \"hash\" from \"documents_to_insert\" on conflict (\"hash\") do nothing`

Would it be caused by there is no index on documents_to_insert?

And since documents_to_insert is a temp table, i am not sure how to analyse this query's performance.

### 🖥️ Your Environment

yarn backstage-cli info
yarn run v1.22.18

OS:   Darwin 21.6.0 - darwin/x64
node: v16.14.2
yarn: 1.22.18
cli:  0.18.1 (installed)
backstage:  1.5.1

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-common                        0.15.1
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3, 1.1.4
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.4
  @backstage/config                                1.0.4, 1.0.5
  @backstage/core-app-api                          1.2.0
  @backstage/core-components                       0.11.2, 0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/errors                                1.1.0, 1.1.3, 1.1.4
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.4.0
  @backstage/plugin-analytics-module-ga            0.1.19
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-app-backend                    0.3.35
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.5
  @backstage/plugin-catalog-backend-module-gitlab  0.1.6
  @backstage/plugin-catalog-backend-module-ldap    0.5.2
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.8, 1.0.9
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-import                 0.8.11
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-explore-react                  0.0.20
  @backstage/plugin-explore                        0.3.39
  @backstage/plugin-home                           0.4.24
  @backstage/plugin-kubernetes-backend             0.7.1
  @backstage/plugin-kubernetes-common              0.4.1
  @backstage/plugin-kubernetes                     0.7.1
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-pagerduty                      0.5.1
  @backstage/plugin-permission-backend             0.5.10
  @backstage/plugin-permission-common              0.6.4, 0.7.1, 0.7.2
  @backstage/plugin-permission-node                0.6.4
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.1
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-module-pg       0.3.6
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.1.1, 1.2.0
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-shortcuts                      0.3.0
  @backstage/plugin-stack-overflow                 0.1.4
  @backstage/plugin-tech-radar                     0.5.15
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.2.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1, 1.0.2
  @backstage/version-bridge                        1.0.2
✨  Done in 2.13s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by iriswang233** [comment]
hi , team,
is there any comment about this issue?

**Comment by freben** [comment]
`conflict ("hash")` might be costly if that column does not have an index - could you check if it has one? I see the migration declares the column as `primary()` but I'd like to double check if that implied actually making it indexed as well or if that'll need to be added separately.

**Comment by freben** [comment]
Alright confirmed - it does have a btree index on the hash. Never mind.

![Screenshot 2023-02-03 at 11 01 15](https://user-images.githubusercontent.com/3097461/216571152-921435a2-7657-4b49-ac6a-8d18310cf67d.png)

When you say 5s _should_ be sufficient - it's a pretty large amount of data, are you sure that that's a safe assumption to make? How beefy is the database server?

**Comment by freben** [comment]
Could also be that [this insert](https://github.com/backstage/backstage/blob/92579fa67e88438c3d51216792ff2d3324fbd477/plugins/search-backend-module-pg/src/database/DatabaseDocumentStore.ts#L135) could be split into pages, possibly also using `batchInsert` [like we do in the catalog](https://github.com/backstage/backstage/blob/92579fa67e88438c3d51216792ff2d3324fbd477/plugins/catalog-backend/src/database/DefaultProcessingDatabase.ts#L136) in some places. We've found that operation to be significantly faster.

Would you be willing to experiment with that?

**Comment by iriswang233** [comment]
hi @freben , 

Thanks for your comment. i have tried several things.

1) When set hash column in  documents_to_insert as primary key, inserting data in documents_to_insert table was failed at 
```
{"level":"error","message":"Collating documents for techdocs failed: error: insert into \"documents_to_insert\" (\"document\", \"type\") values ($1, $2), ($3, $4), ($5, $6), ($7, $8), ($9, $10), ($11, $12), ......
($1999, $2000) - duplicate key value violates unique constraint \"documents_to_insert_pk\"","plugin":"search","service":"backstage","type":"plugin"}
```
2)  When set hash column in  documents_to_insert as normal index, the statement timeout issue still happened.
```
insert into documents (type, document, hash) select \"type\", \"document\", \"hash\" from \"documents_to_insert\" on conflict (\"hash\") do nothing - canceling statement due to statement timeout
```
The index is like this
```
 documents_to_insert                           | documents_to_insert_hash_index                     | CREATE INDEX documents_to_insert_hash_index ON pg_temp_10.documents_to_insert USING btree (hash)
```
When i tried to analysis the query locally after changing temp documents_to_insert to be a normal table,
```
EXPLAIN insert into documents ( type, document, hash ) select type, document, hash from documents_to_insert on conflict ( hash ) do nothing;
                                  QUERY PLAN                                  
------------------------------------------------------------------------------
 Insert on documents  (cost=0.00..16.50 rows=0 width=0)
   Conflict Resolution: NOTHING
   Conflict Arbiter Indexes: documents_pkey
   ->  Seq Scan on documents_to_insert  (cost=0.00..16.50 rows=650 width=128)
(4 rows)
```
This index **documents_to_insert_hash_index** is not used.

3) Increasing statement timeout to 10s, the statement timeout issue still happened.

I am wondering for 
1. does documents_to_insert table contain unnecessary data? Because there is data with same hash getting inserted in documents_to_insert table.
2. Was index set wrongly so it's not been used?
3. "split into pages" does this possible for "being transferred into the actual documents table" step?

**Comment by freben** [comment]
Not sure about the hashes. Maybe you _actually_ have multiple identical documents coming in. That should really not be the case if they are full entities though - there should never be two identical entities. So ... could the hash algorithm actually be not doing the right thing? Could it be that it returns the wrong value and therefore leads to collisions? I am not sure - going to have to defer to @iamEAP or others on the search team at this point I think.

**Comment by iriswang233** [comment]
Hi, after explaining the queries that take long time to run.
This delete query took about 10+mins.
```
Explain (format yaml) delete from documents where type = ? and hash not in ( select hash from documents_to_insert )
  - Plan: 
    Node Type: \"ModifyTable\" 
    Operation: \"Delete\"
    Parallel Aware: false
    Async Capable: false
    Relation Name: \"documents\"
    Alias: \"documents\"
    Startup Cost: 0.42
    Total Cost: 692474800.74
    Plan Rows: 0
    Plan Width: 0
    Plans: 
      - Node Type: \"Index Scan\"
        Parent Relationship: \"Outer\"
        Parallel Aware: false
        Async Capable: false
        Scan Direction: \"Forward\"
        Index Name: \"documents_type_index\"
        Relation Name: \"documents\"
        Alias: \"documents\"
        Startup Cost: 0.42
        Total Cost: 692474800.74
        Plan Rows: 36109
        Plan Width: 6
        Index Cond: \"(type = 'techdocs'::text)\"
        Filter: \"(NOT (SubPlan 1))\"
        Plans:
          - Node Type: \"Materialize\"
            Parent Relationship: \"SubPlan\"
            Subplan Name: \"SubPlan 1\"
            Parallel Aware: false
           Async Capable: false
            Startup Cost: 0.00
            Total Cost: 17969.32
            Plan Rows: 482755
            Plan Width: 32
            Plans: 
              - Node Type: \"Seq Scan\"
                Parent Relationship: \"Outer\"
                Parallel Aware: false
                Async Capable: false
                Relation Name: \"documents_to_insert\"
                Alias: \"documents_to_insert\"
                Startup Cost: 0.00
                Total Cost: 12254.55
                Plan Rows: 482755
                Plan Width: 32"
	```

This insert query takes about 20 seconds.

```
Explain (format yaml) insert into documents ( type, document, hash ) select type, document, hash from documents_to_insert on conflict ( hash ) do nothing

- Plan:
    Node Type: ModifyTable
    Operation: Insert
    Parallel Aware: false
    Async Capable: false
    Relation Name: documents
    Alias: documents
    Startup Cost: 0
    Total Cost: 12254.55
    Plan Rows: 0
    Plan Width: 0
    Conflict Resolution: NOTHING
    Conflict Arbiter Indexes:
    - documents_pkey
    Plans:
    - Node Type: Seq Scan
      Parent Relationship: Outer
      Parallel Aware: false
      Async Capable: false
      Relation Name: documents_to_insert
      Alias: documents_to_insert
      Startup Cost: 0
      Total Cost: 12254.55
      Plan Rows: 482755
      Plan Width: 128
```
Please help me understand
1. Is the long execution time expected?
2. Is there any improvement about search indexing is going on related to them ?
3. Currently the search indexing is either all update successfully or all fail. This approach may not be suitable for large number of entities and TechDocs. Is it possible to commit on each update success so at least some update can success? Or for search indexing TechDocs, is it possible to do it individually along Techdocs built process?

**Comment by iriswang233** [comment]
hi @iamEAP , could you help here?

**Comment by iamEAP** [comment]
Hey there!  Just getting caught up on this thread.  First, to provide some context on your questions:

> _Is the long execution time expected?_

At Spotify, we only run the ES indexer, so I couldn't say whether or not what you're experiencing is normal.  I _might_ expect that the time to re-index a set of documents of about this size _could_ take up to 7 minutes _in total_, but I would expect most of that time being the actual gathering of documents, not the last insertion/commit step.  A 7 minute delete definitely doesn't sound right.

> _Is there any improvement about search indexing is going on related to them?_

My understanding of the priorities of the team(s) at Spotify responsible for search and discoverability is that the PG search engine is not currently a priority, so you'll have to lean on the community for support (with that in mind: I'm going to re-open this issue).

> _Is it possible to commit on each update success so at least some update can success?_

Incremental and event-based updates of search indices was a non-goal when we originally designed the search engine indexing process, so this is unfortunately not possible today.  There have been community members interested in adding this support, but the efforts appear dormant.  You can read more here: https://github.com/backstage/backstage/issues/13681.

---

On your point about the delete query specifically:

> _After explaining the queries that take long time to run. This delete query took about 7 mins._

Maybe this will have no impact, but I wonder if the `NOT IN` subquery is problematic?  Could be simplified to a LEFT JOIN with a `NULL` check on the joined table: https://github.com/backstage/backstage/blob/4b2a9b5/plugins/search-backend-module-pg/src/database/DatabaseDocumentStore.ts#L120-L126

On @freben's point:

> _Maybe you actually have multiple identical documents coming in... Could the hash algorithm actually be not doing the right thing? Could it be that it returns the wrong value and therefore leads to collisions?_

Now that I'm looking at the code a little more closely, I'm wondering if the hash is actually not behaving as it should.  The hash actually seems to be used for two distinct purposes: as a primary document identifier (used to know when documents have been deleted in the source system, so they can be deleted in the search index), as well as a representation of document _content_ (used to minimize duplicated work of inserting/updating data that is already there).

But a document isn't just its text content!  So if other fields on a document changes, the search index isn't picking up those changes.  And if a document's text happens to be duplicated with another (a higher likelihood in TechDocs, where perhaps you have some default TechDocs content in your Scaffolder templates), you'll likely be missing a lot of content in the index (with potentially a high number of hash collisions).

Makes me think maybe instead of the hash, we should rely on the `location` (in combination with `type`) as a de-duplicating key.  And instead of ignoring on conflict during insert, just perform an update instead.

**Comment by djamaile** [comment]
Hey @iriswang233 ! Was wondering if this is still a relevant issue? 😄

**Comment by mariia-maksimova** [comment]
+1
We've experienced a similar issue, only for us the collating was taking ±20 min every hour. After larger refreshes of various entities, it took up to 7h to finish (with subsequent runs piling up on each other :( ).

> Maybe this will have no impact, but I wonder if the NOT IN subquery is problematic? Could be simplified to a LEFT JOIN with a NULL check on the joined table: https://github.com/backstage/backstage/blob/4b2a9b5/plugins/search-backend-module-pg/src/database/DatabaseDocumentStore.ts#L120-L126

This option did help a lot: bringing us from 20 min down to 3 min. 
We will probably look further into indexes as well, but replacing NOT IN definitely helped. 
It would be great to integrate it into the codebase :)

**Comment by freben** [comment]
Great find! We're off this week but hopefully we'll get to this ASAP after that!

**Comment by nikolaik** [comment]
We are also seeing similar query times for the problematic DELETE query

**Comment by nikolaik** [comment]
Looks like https://github.com/backstage/backstage/pull/20936 fixed the immediate issue with performance, thanks @mariia-maksimova ⚡

**Comment by emmaindal** [comment]
Awesome, thank you again @mariia-maksimova. Are we good to close this issue with https://github.com/backstage/backstage/pull/20936 in place or do you still see failures of the indexing related to this?
