### ISSUE TITLE
🚀 Feature: Support AntD Theme

### ISSUE THREAD

**Issue by goodryanboy** [backstage/backstage#15628]
### 🔖 Feature description

Ability to add Antd theme. 
https://ant.design/

### 🎤 Context

By default the theme used on Backstage is Material UI but we want to implement Antd theme.
How hard is it to implement given that the existing components are based on Material UI

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jhaals** [comment]
Hi, I'm sorry but Backstage is very centered around Material UI and we are not able to provide any support for other UI frameworks, you basically have to create your own components but can still use the core API. This is not something that we're planning to support at this point.
