### ISSUE TITLE
🐛 Bug Report: Sorting on table columns is not working correctly

### ISSUE THREAD

**Issue by sqsp-rwatkins** [backstage/backstage#15642]
### 📜 Description

Clicking the arrow to sort by ASC / DESC on table items.

### 👍 Expected behavior

Sort either ASC or DESC

### 👎 Actual Behavior with Screenshots

Appears to have 3 states, ASC, DESC and another state that appears random to me

### 👟 Reproduction steps

We discovered this in our own instance but it is also present in [the demo](https://demo.backstage.io/catalog?filters%5Bkind%5D=location&filters%5Buser%5D=all)

1. Visit https://demo.backstage.io/catalog?filters%5Bkind%5D=location&filters%5Buser%5D=all
2. Click the arrow beside the `Targets` column to sort it a few times
3. Notice how it has 3 states
 

https://user-images.githubusercontent.com/114502094/211356925-04742ee6-841f-4d6e-bf0b-415549f393a8.mov

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Thanks for your report!

This is very intentional, and just how the underlying table library does things. It's very useful as an end user to "cancel" the sort and going back to the natural sort of the original data - which is what happens in the third state.

Closing as working as intentional.
