### ISSUE TITLE
🔌 Plugin: Matomo Analytics Module

### ISSUE THREAD

**Issue by Silthus** [backstage/backstage#15644]
### 🔖 Summary

You should add a `analytics-module-matomo` to allow tracking events using [Matomo](https://matomo.org/). Matomo is self hostable open source tracking alternative to Google Analytics.

### 🌐 Project website (if applicable)

https://matomo.org/

### ✌️ Context

There is an existing Javascript library that implements the Matomo tracking API and can be used. We at our company already implemented it pretty much copy pasting the Google Analytics module and I am willing to submit a PR if wanted.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Sounds nice!

**Comment by lcjury** [comment]
@Silthus any updates on this :)?? We're planning on integrating Matomo in our backstage instance. Having a plugin would be really nice!

**Comment by Silthus** [comment]
> @Silthus any updates on this :)?? We're planning on integrating Matomo in our backstage instance. Having a plugin would be really nice!

Hey @lcjury,

we are already using the plugin in production, just did not have the time to contribute it yet and I am currently on parental leave. I can ping one of my colleagues and see if they can contribute the source code or at least give an example.

**Comment by lcjury** [comment]
@Silthus I really appreciate your answer. We're not in a hurry right now, so we can wait a few weeks, it would be awesome if any of your colleagues can do that contribution, thanks a lot!

p.d: congratulations on becoming a new father!

**Comment by serenamarie125** [comment]
We have a contribution coming in the Janus community, here's the [associated issue](https://github.com/janus-idp/backstage-plugins/issues/360) where you can find more details.

**Comment by serenamarie125** [comment]
@Rugvip should we take assignment of this?

**Comment by awanlin** [comment]
Hi @serenamarie125, I'm not sure these are the same, this issue is asking to have the usage data being tracked by Backstage via the Analytics API passed to Matomo. Where as the issue and PR you've shared looks to be showing Matomo data in Backstage.

**Comment by riginoommen** [comment]
We have developed the plugin for collecting the analytics and pushing to matomo for the backstage we will be publishing it soon

**Comment by 4lch4** [comment]
Hey @riginoommen, would you happen to have any updates on this?

I'd love to help out if any help is needed as we'd like something like this for our instance of Backstage.

**Comment by riginoommen** [comment]
Yes we have developed it we will be publishing it to upstream by this week

**Comment by serenamarie125** [comment]
What is upstream ? Is it Janus or Backstage.io. .. i assume it is under Red
Hat umbrella ?

**Comment by 4lch4** [comment]
Thanks for the info!

**Comment by 4lch4** [comment]
Just to confirm, once the Janus-IDP version of the plugin is made available would there be a desire for the same thing in this backstage repo?

If so, I'd be happy to rework whatever is pushed up to the Janus-IDP repo so it'll work for this version.

**Comment by awanlin** [comment]
Hi @4lch4, there should need to be any changes as it would just be a module that implements the `AnalyticsApi` which is what they did with their Segment module: https://github.com/janus-idp/backstage-plugins/tree/main/plugins/analytics-provider-segment/src/apis/implementations/AnalyticsApi. Also keep in mind this RFC: https://github.com/backstage/backstage/issues/20266

**Comment by 4lch4** [comment]
Thank you for the clarification, @awanlin! Much appreciated.

**Comment by riginoommen** [comment]
@deshmukhmayur have opened the pull request for this feature in the Janus Repository.

**Comment by riginoommen** [comment]
Package has been published to npm - https://www.npmjs.com/package/@janus-idp/backstage-plugin-analytics-module-matomo

**Comment by awanlin** [comment]
Hi @riginoommen, could you add this to the Plugin Directory? That would be awesome! https://backstage.io/docs/plugins/add-to-directory

**Comment by deshmukhmayur** [comment]
Hey @awanlin, I just raised a PR to add the plugin to the plugin directory: #20643

**Comment by deshmukhmayur** [comment]
Hey @awanlin Since the plugin has been added to the marketplace now, can we take ownership of this issue and close it?

**Comment by awanlin** [comment]
Hi @deshmukhmayur, thanks for all your work on this, very happy to see this as an option for Backstage Adopters. Sorry for the slow reply, I've been away on vacation and I'm now at BackstageCon/KubeCon. 

Thanks for the help with this @vinzscam 🚀
