### ISSUE TITLE
🐛 Bug Report: [TechDocs] Next link overlays the content preventing from accessing links

### ISSUE THREAD

**Issue by oodamien** [backstage/backstage#15653]
### 📜 Description

When reading a documentation, the content below the Next/Previous actions container is not accessible.

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/487067/211526429-a4cea809-8acc-41f8-ae1a-d488061e3d0b.png">

### 👍 Expected behavior

The content should be accessible, clickable

### 👎 Actual Behavior with Screenshots

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/487067/211527098-64f5956d-bf72-44d4-ac56-83144afb02ec.png">

The user can not click on `installation instructions for Docker`.

### 👟 Reproduction steps

1. Navigate to https://demo.backstage.io/
2. Menu > Docs
3. Open Backstage documentation
4. Navigate to Getting Started > Getting Started

Links and Next/Previous actions are present in the page.

**Comment by caleygoff-invitae** [comment]
`pointer-events: none` effectively disables the `next` and `previous` buttons from working in the techdocs `reader` plugin, our users are complaining about it, as a result we will need to override it with a `makeStyles()`

**Comment by caleygoff-invitae** [comment]
the addition of the `pointer-events: none` in this PR effectively disables the `next` and `previous` buttons from working in the techdocs `reader` plugin, our users are complaining about it, as a result we will need to override it with a `makeStyles()`
