### ISSUE TITLE
🐛 Bug Report: Can't publish to minio bucket from the techdocs cli

### ISSUE THREAD

**Issue by Robunnin** [backstage/backstage#15669]
### 📜 Description

I am unable to publish techdocs to a minio bucket from the techdocs cli. 

### 👍 Expected behavior

When I set the --awsEndpoint option to point to a minio host it should be able to upload to the minio bucket just like it can directly from Backstage.

### 👎 Actual Behavior with Screenshots

It connects to the official aws api, in my case trying to connect to sts.us-east-1.amazonaws.com. It fails with the error "The security token included in the request is invalid."

I can confirm it is trying to connect to the official aws because if I change the region to a nonexistent region or set the ip address of sts.us-east-1.amazonaws.com to a nonexistent ip I get either address lookup errors or connection errors. 

### 👟 Reproduction steps

1. Generate techdocs using the cli
2. Try to publish the techdocs, specifying the --awsEndpoint option to be the minio host. Configure bucket and environment variables as needed. 

Example commands I ran:
(The region, access key id, and secret access key are configured as environment variables)

techdocs-cli publish --publisher-type awsS3 --storage-name _bucket name_ --entity _entity_ --awsEndpoint _minio server_ --directory _generated techdocs folder_ --awsS3ForcePathStyle true

techdocs-cli publish --publisher-type awsS3 --storage-name _bucket name_ --entity _entity_ --awsEndpoint _minio server_ --directory _generated techdocs folder_ --awsRoleArn _arn_ --awsS3ForcePathStyle true

### 📃 Provide the context for the Bug.

Publishing to a minio bucket from Backstage itself is working, but I would like to have it working from the cli to be able to use this within a ci/cd pipeline. 

When using techdocs from Backstage itself there are more configuration options that you can set, for instance an account id. The techdocs cli has no option for an account id and seems to start breaking down because of this. I traced through the cli's code and found that it tries to connect to sts.us-east-1.amazonaws.com when trying to call [GetCallerIdentity to fill in the accountid](https://github.com/backstage/backstage/blob/8de027608642a038aa2bc1c2bd0eac6e7c6add17/packages/integration-aws-node/src/DefaultAwsCredentialsManager.ts#L51).

If I throw in some options so it doesn't have to fill in the account id, the next place it breaks down is [when calling HeadBucket to get the bucket status as part of the readiness check](https://github.com/backstage/backstage/blob/8de027608642a038aa2bc1c2bd0eac6e7c6add17/plugins/techdocs-node/src/stages/publish/awsS3.ts#L242). The error is the exact same with it trying to reach out to sts. 

### 🖥️ Your Environment

Tested on the following techdocs-cli versions:

- 1.1.3
- 1.2.4
- 1.2.5-next.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sebasnabas** [comment]
I have exactly the same issue.
I found a workaround by wrapping the techdocs-cli in a docker image with `@techdocs/cli` pinned to "1.2.3" and `@backstage/plugin-techdocs-node` pinned to "1.4.2".
