### ISSUE TITLE
🚀 Feature: enable Feature Flags tab to be hidden when no feature flags is available

### ISSUE THREAD

**Issue by claudiahub** [backstage/backstage#15666]
### 🔖 Feature description

Add a property that gives users the possibility to hide the Feature Flags tab, in the Settings page.

![image](https://user-images.githubusercontent.com/54085737/211628079-77d1ec6f-ba3c-4090-991d-518d6647d4fc.png)

### 🎤 Context

Feature Flags tab is always visible currently and there isn't any custom property to use in order to hide it from the Settings page. On our Backstage implementation we've found some use cases where this tab is not useful and we'd just need to remove it from this page.

### ✌️ Possible Implementation

In the @backstate/plugin-user-settings plugin a property could be set in order to allow users to specify if they wish to have the Feature Flags tab visible.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Hm. Probably not in the form of a prop for that single purpose. Could perhaps add an `if` prop to that particular tab that makes sure it's only visible if there are any feature flags at all?

Then as an additional layer, if you want to hide that tab dynamically for some people _even if_ there are flags, you could implement a custom version of the `featureFlagsApiRef` that just returns an empty array no matter what, for logged-in users that shouldn't see it.

**Comment by claudiahub** [comment]
Adding an `if` prop makes sense and implementing a specific version of the `featureFlagsApiRef ` would add even more value in terms of customization. I'll put these in a PR, thanks @freben.
