### ISSUE TITLE
🚀 Feature: Add ability to pass title and subtitle to Bazaar page plugin

### ISSUE THREAD

**Issue by accezar** [backstage/backstage#15670]
### 🔖 Feature description

Add ability to pass `title` and `subtitle` to Bazaar Plugin Page allowing us to customize the plugin page header. 

### 🎤 Context

Today the header content for Bazaar plugin is defined inside the plugin. It would be nice to make these props available for editing.

### ✌️ Possible Implementation

`<Route path="/bazaar" element={<BazaarPage title={} subtitle={} />} />`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Ping @anicke @fridajac 

This sounds like a reasonable thing to do. I'd technically prefer if we had used the soon-to-be-more-established patterns of customizable components to avoid prop explosions, but let's not go that far right now, the proposed solution is OK under the circumstances.

**Comment by anicke** [comment]
Yes, sounds like a good addition, I would be tempted change the default.
