### ISSUE TITLE
🚀 Feature: Add search to Backstage.io plugins page

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#15685]
### 🔖 Feature description

Add a search input to the plugin page in Backstage.io. Allow users to search for plugins that contain some words in the title, description, or tags. 

### 🎤 Context

As the number of plugins continues to grow, it starts to get harder to find plugins from the list in Backstage.io. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Makes sense. Might be best to do once #12019 is in perhaps.
