### ISSUE TITLE
🐛 Bug Report: Search explore link on microsite

### ISSUE THREAD

**Issue by efenner-cambia** [backstage/backstage#15716]
### 📜 Description

The "Explore" Link on the Backstage Search tile of the Plugins page links to the [Software Catalog Overview](https://backstage.io/docs/features/software-catalog/software-catalog-overview) doc page rather than the [Search Overview](https://backstage.io/docs/features/search/search-overview) doc.

### 👍 Expected behavior

The link should point to the [Search Overview](https://backstage.io/docs/features/search/search-overview) page

### 👎 Actual Behavior with Screenshots

The "Explore" Link on the Backstage Search tile of the Plugins page links to the [Software Catalog Overview](https://backstage.io/docs/features/software-catalog/software-catalog-overview)

### 👟 Reproduction steps

1. Go to the [Plugin Marketplace](https://backstage.io/plugins)
2. Click the Explore button in the Backstage Search tile ![Screen Shot 2023-01-11 at 17 20 54](https://user-images.githubusercontent.com/105249079/211953745-7591a2d5-5af6-4388-9ecc-6ca14a55e685.png)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Hi! Makes sense, we'd appreciate a PR.

**Comment by efenner-cambia** [comment]
PR Submitted!

**Comment by efenner-cambia** [comment]
With @Rugvip 's approval and merge of https://github.com/backstage/backstage/pull/15732 this should be resolved. Closing.
