### ISSUE TITLE
🐛 Bug Report: UX on search pop up the X button on the corner is not working

### ISSUE THREAD

**Issue by alileza** [backstage/backstage#15717]
### 📜 Description

X on the corner should reflect canceling the pop-up box, but it's not
pop-up

### 👍 Expected behavior

It should close the search when you click the X

<img width="738" alt="Screenshot 2023-01-12 at 01 58 17" src="https://user-images.githubusercontent.com/1962129/211954167-40ec9b1c-cead-47d5-9df4-f34ec431e6f7.png">
<img width="1252" alt="Screenshot 2023-01-12 at 01 59 31" src="https://user-images.githubusercontent.com/1962129/211954181-96c420a8-6d8b-4718-9872-4d9568a5606d.png">

### 👎 Actual Behavior with Screenshots

the button just didn't respond when I click, even showing the Text insertion cursor

### 👟 Reproduction steps

```
$ npx @backstage/create-app@latest
$ npm run start-backend
$ npm start
```

### 📃 Provide the context for the Bug.

it's just a small thing when I try to set up backstage doing a search 

### 👀 Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes, I am willing to submit a PR!

**Comment by efenner-cambia** [comment]
I noticed this as well. The current behavior of the x is to clear out the search box if text has been entered, so it does currently seem to serve a function. Would the ideal behavior be to clear the search box if text has been entered and close the modal only if the search box is empty?

**Comment by freben** [comment]
Aha! So that means it IS a clear button since it's on the text box itself. It was never intended to be a close button in the first place, it's just that its placement is confusing.

**Comment by freben** [comment]
(I totally agree that this is super confusing though. Maybe there should be no clear functionality, and instead having a proper close-X)

**Comment by emmaindal** [comment]
Hello, thanks a lot for opening the issue @alileza 

I think we **do want to keep the clear button for the input field**, but maybe we can add a label to it and make it a bit smaller? Today it looks like its almost a bit outside the input field itself so I think we can improve the styling there for sure. 

I also think we can add a close button to the modal which will clarify the differences on the clear button and the close button. 

Do you want to open a PR for this? otherwise I'll pick it up and assign to me.

**Comment by emmaindal** [comment]
I think to start with just something like this can improve:
| Before | After | 
| ------------- | ---------- |
| <img src="https://user-images.githubusercontent.com/25153114/213125118-5ee84eda-ff42-4cfc-b98f-13dda5307360.png" width="600px"/> | <img src="https://user-images.githubusercontent.com/25153114/213125128-6b6c11cf-9f4f-463b-9149-9e8b7584f40e.png" width="600px"/> |

**Comment by alileza** [comment]
Hi @emmaindal, let me try to pick it up now 🤞

**Comment by alileza** [comment]
@emmaindal I don't think I could fix this up quickly, it takes me some time to drill down the component and stuff. So seems like it'll be pretty fast for you to do it 🙏 , if you would be dear to ping me on the pr, I'm curious how's those CSS configured

I see that the element actually already has an event listener, so I think it might be some other hidden element covering it up


```js
const endAdornment = (
        <InputAdornment position="end">
          <IconButton aria-label="Clear" size="small" onClick={handleClear}>
            <ClearButton />
          </IconButton>
        </InputAdornment>
      );
```

I see that [this](https://github.com/alileza/backstage/blob/master/plugins/search-react/src/components/SearchBar/SearchBar.tsx#L142) component already handles the clear command, unfortunately, I'm not super familiar with how backstage handle the material UI

**Comment by diggyk** [comment]
@emmaindal if I wanted to try hacking on a fix for this sort of thing, is there a set of directions I can follow?  I tried following https://backstage.io/docs/local-dev/linking-local-packages but that did not seem to work for me. I also tried changing the `dependency` from version to file path of my local checkout of the backstage repo but that also didn't work (webpack complaining about not being able to import stuff).

I'd love some help getting a dev environment setup to work on backstage PRs so I can help contribute fixes.

**Comment by alileza** [comment]
I had same exact problem as what @diggyk, I think maybe we can create a new issue for improvement documentation for plugins contributors. Or maybe it's somewhere in the docs I couldn't find?

**Comment by diggyk** [comment]
I tried some more to get this to work so i could create a PR.  No luck.  I tried adding:
```
      "../../backstage/plugins/*",
      "../../backstage/packages/*"
```
... to both `package.json` and `lerna.json` and they all blow up spectacularly when doing `yarn install` as per the instructions.

**Comment by aitherios** [comment]
@alileza, I posted some suggestions on your draft https://github.com/backstage/backstage/pull/15840 could you take a look?

**Comment by diggyk** [comment]
@aitherios can you take a look at https://github.com/backstage/backstage/pull/15923?  The CI/tests are failing but those don't seem related to my single line change so I don't know why.

**Comment by camilaibs** [comment]
Hi @alileza and @diggyk, cross-postin a suggestion gave here: https://github.com/backstage/backstage/pull/15923#issuecomment-1408974891.

> As explained [here](https://github.com/backstage/backstage/issues/15717#issuecomment-1386683691), this is not intended to close a modal but to clear the input text when using type "_search_"; for [example](https://codesandbox.io/s/unruffled-wing-sgmtpn?file=/src/App.tsx), if you render a standard input with type "_search_" and enter a value into it, you will see a small clear icon on the right. It clears the input text when clicked; the same happens with the Material UI `InputBase` component.
> 
> https://user-images.githubusercontent.com/6290749/215540493-0ee3f3b2-8b83-44ca-8002-74cbe4ea63f0.mov
> 
> As this is the expected default behavior for inputs of type "_search_", we show the icon and you can hide it by passing the `clearButton` property to the `<SearchBar clearButton={false} / >` component, see an [example](https://backstage.io/storybook/?path=/story/plugins-search-searchbar--without-clear-button).
> 
> That said, I would recommend:
> 
> 1. Show the "clear" icon only when there is an input value and reduce the icon size in the `SearchBarBase` component.
> 2. Add a modal close button in the title of the `SearchModal`, as in [this](https://v4.mui.com/components/dialogs/#customized-dialogs) example, and keep the `SearchBar` component as it is since it could be used in other cases, like in a search page, not only in models.

Sounds good to you both? It would be so nice to have you two contributing with us; maybe @alileza could do the `SearchBar` changes and the @diggyk the `SearchModal` changes 🙂

**Comment by diggyk** [comment]
I've created a new issues: https://github.com/backstage/backstage/issues/16089
