### ISSUE TITLE
🐛 Bug Report: Scaffolder template only works towards GitHub

### ISSUE THREAD

**Issue by alexjia823** [backstage/backstage#15719]
### 📜 Description

I am creating a component in development mode, and I want to create my new component onto self-hosted gitLab instead of gitHub, but I found that the "host" dropdown list is gray and I couldn't choose a different repo, so what should I do to resolve it?
![image](https://user-images.githubusercontent.com/40494631/212021225-9cac44a3-f194-40cd-9db0-80863aa4eacb.png)

### 👍 Expected behavior

I can choose the gitlab as the host repo.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/40494631/212021351-70df20c5-ec69-44b7-9019-51348099731c.png)

### 👟 Reproduction steps

1. Go to "create a new component"
2. select the host repo.
3. The host repo is gray.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by alexjia823** [comment]
Hi freben, thank you for the reply and I need to check it and get back to you thank you.

**Comment by alexjia823** [comment]
> This is using a `RepoUrlPicker` right? Like [in this example](https://github.com/backstage/backstage/blob/353d891cb9164a0705e1ccb6eb3ea3be8a724e04/plugins/scaffolder-backend/sample-templates/bitbucket-demo/template.yaml#L19).
> 
> That control leverages the `integrations` key in your app-config. Did you [set up integrations](https://backstage.io/docs/integrations/gitlab/locations) for your target system?
> 
> Bit of another long shot to check: Have you accidentally added an `allowedHosts` that might be empty or so?

As I checked the code and found that the template.yaml is getting from url: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/docs-template/template.yaml on my side, and you can see the allowedHosts is gitHub only, you can see it from below code:

- title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

Can you tell me how can I integrate gitlab to the template? Thank you in advance.

**Comment by freben** [comment]
Oh, you probably won't be able to use the open source templates verbatim; you'll be writing your own in general. See the docs for the Scaffolder, starting here but also in neighboring sections https://backstage.io/docs/features/software-templates/adding-templates
