### ISSUE TITLE
New backend plugin return 404 for health

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#15714]
### 📜 Description

I am checking the backend plugin documentation. It does not work as mentioned in the documentation.

**Creating a Backend Plugin**
A new, bare-bones backend plugin package can be created by issuing the following command in your Backstage repository root:

yarn new --select backend-plugin
Please also see the --help flag for the new command for some further options that are available, notably the --scope and --no-private flags that control naming and publishing of the newly created package. Your repo root package.json will probably also have some default values already set up for these.

Creating the plugin will take a little while, so be patient. It will helpfully run the initial installation and build commands, so that your package is ready to be hacked on! It will be located in a new folder in your plugins directory, in this example plugins/carmen-backend.

For simple development purposes, a backend plugin can actually be started in a standalone mode. You can do a first-light test of your service:

cd plugins/carmen-backend
yarn start
This will think for a bit, and then say Listening on :7007. In a different terminal window, now run

curl localhost:7007/carmen/health
This should return {"status":"ok"}. Success!

### 👍 Expected behavior

It should return the This should return {"status":"ok"}. Success!

### 👎 Actual Behavior with Screenshots

It return 404.

### 👟 Reproduction steps

1) create a new application using following command.
     npx @backstage/create-app
2)  yarn new --select backend-plugin
3) cd plugins/carmen-backend
     yarn start
4) curl localhost:7007/carmen/health

### 📃 Provide the context for the Bug.

It should work as mention in the documentation or we should update the documentation.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sennyeya** [comment]
Wasn't able to verify on my end, can you try with `curl localhost:7007/carmen-backend/health`. The standaloneServer uses the full plugin name as the prefix.

For reference, I created a plugin called `test-backend` and here's my `startStandaloneServer` function from `standaloneServer.ts`:
```
export async function startStandaloneServer(
  options: ServerOptions,
): Promise<Server> {
  const logger = options.logger.child({ service: 'test-backend-backend' });
  logger.debug('Starting application server...');
  const router = await createRouter({
    logger,
  });

  let service = createServiceBuilder(module)
    .setPort(options.port)
    .addRouter('/test-backend', router);
  if (options.enableCors) {
    service = service.enableCors({ origin: 'http://localhost:3000' });
  }

  return await service.start().catch(err => {
    logger.error(err);
    process.exit(1);
  });
}
```

**Comment by lalit774** [comment]
Thank you for the quick reply. it works perfectly. I will update the documentation.  
https://backstage.io/docs/plugins/backend-plugin

**Comment by sennyeya** [comment]
@lalit774 Ended up deleting my reply as it's not really correct. The documentation is correct but the code isn't generating as expected.

This seems to be an issue with the templating in general. The id parameter in the Handlebars template is being passed in as `carmen-backend` instead of just `carmen`. From https://github.com/backstage/backstage/blob/378790a581386aeb275fda7a3501dc3769ccc4a9/packages/cli/src/lib/new/factories/backendPlugin.ts#L41. The old createPlugin method didn't have this issue.

I created a new backend plugin and the URL is now, `/carmen-backend/health` and `const logger = options.logger.child({ service: 'carmen-backend-backend' });` also gets changed which is a bit confusing.

For now, I'd suggest just updating the `standaloneServer.ts` file.

**Comment by bruno-watt-wcq** [comment]
So this is still happening. Ive tried to curl to the endpoint with -backend but it doesn't work
