### ISSUE TITLE
🚀 Feature: Catalog Table item totals also include quick filter impact

### ISSUE THREAD

**Issue by FredrikFolkeryd** [backstage/backstage#15726]
### 🔖 Feature description

Currently the catalog table displays the total item count based on the entity selection drop downs as `All | <user-selected-entity-kind> (<total-number-of-entities>)` . It would be clarifying to extend (or replace) this with the "quick-filtered" count (<number-of-selected-kind-of-entities-currently-matching-quick-filter>) when the user is filtering the selection further using the quick filter.

### 🎤 Context

It is a very common practice in general to have table totals reflect the visible (filtered) set, either instead of or together with totals for the entire set in the table. This reduces confusion about what the number represents.

### ✌️ Possible Implementation

For example:
| Quick filter is empty  | Quick filter = 'foo' | Comment |
| ------------- | ------------- | ------------- |
|`All (123)` |`All (42/123)` | 'foo' matched in 42 out of 123 possible rows|
|`All (123)` |`All (123) – Filtered (42)` | |

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by FredrikFolkeryd** [comment]
I'm probably going to investigate a custom catalog index page in our instance of Backstage soon, I'll have a second look then and see if there's bandwidth to do something on this also and contribute.

**Comment by efenner-cambia** [comment]
I would love to see this

**Comment by vinzscam** [comment]
Hi @FredrikFolkeryd,
we are currently in a situation where we are rethinking the `CatalogTable`, as described in #12247.
It would probably make sense to add this feature as part of #12247, in order to minimize the amount of work.

**Comment by efenner-cambia** [comment]
bump
