### ISSUE TITLE
🐛 Bug Report: Azure Devops repository redirect

### ISSUE THREAD

**Issue by RicardoCarvalhoo** [backstage/backstage#15724]
### 📜 Description

Hello! I'm having trouble dealing with the "View Source" button, the url redirect to the Azure DevOps gives a blank page.
I was able to detect that the redirect url uses "https://organization@dev.azure.com/organization/...", and with that url I get the blank page but when I remove the "organization@" I can access the repo just fine.
It seems to me that it is doing a double redirect...
Is there a way for me to debug this for the azure integration?

### 👍 Expected behavior

I should click on View Source

![button view source](https://user-images.githubusercontent.com/107133819/212056084-bb7e202d-d9fe-4ad1-8174-9a2f7d26ef21.png)

And then I would go to my repository in Azure DevOps.

![repo azure](https://user-images.githubusercontent.com/107133819/212056195-f08ed0bd-b3af-4c94-b526-7fe657855e0d.png)

### 👎 Actual Behavior with Screenshots

Instead I click on View Source and get this

![bug url](https://user-images.githubusercontent.com/107133819/212056289-442331eb-cd1c-4470-a673-c2dd77082f23.png)

### 👟 Reproduction steps

1. Create component via template
2. Click in View Source of component and the redirect gives blank page

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Oh I haven't personally seen the username/password part of the URL used before. That's odd indeed.

How did the entity enter the catalog? As in, what method of ingestion was used - was there some discovery provider/processor or similar?

If you open up the entity inspector view (in the three-dots menu at the top right of the entity page in Backstage), what does its annotations look like? Do they have that URL format on the `*managed_by*` annotations?

**Comment by RicardoCarvalhoo** [comment]
Hello! It looks like yes, in the annotations of the entity the url is formatted that way, with the "organization@".

![image](https://user-images.githubusercontent.com/107133819/213156166-ae4f1a37-1bd9-42c7-b410-422689bf8d0e.png)

Well the component is being registered to the catalog via template, the code of the template is shown below.

**template.yaml**
![template code 1](https://user-images.githubusercontent.com/107133819/213154276-fffd1459-c8d7-4410-b18b-f0df88130d11.png)
![template code 2](https://user-images.githubusercontent.com/107133819/213154391-57c82089-35ba-47f6-b2e5-0f08751d6d96.png)

**catalog-info.yaml** (inside template)
![template catalog-info](https://user-images.githubusercontent.com/107133819/213154725-53d36189-3bcf-46e0-b0a8-71f4e6e3cae3.png)

Also in the app-config I configured azure integration and azure devops plugin this way:
![app config integrations](https://user-images.githubusercontent.com/107133819/213154909-0b7d2c92-b8a6-4625-aa36-b95103f866aa.png)

**Comment by JetteBke** [comment]
This is still an issue for us, will it be fixed at some point?

**Comment by VaseemFathima-36** [comment]
Facing the same issue. Any solution?
