### ISSUE TITLE
🐛 Bug Report: Lighthouse plugin does not render pagination

### ISSUE THREAD

**Issue by cakeinpanic** [backstage/backstage#15727]
### 📜 Description

Hi, we are using LH plugin with our own backend implementation.
It worked great while we had less then 10 websited. Now we have 12 of them, but pagination element is not rendered and we can't see everything.

According to [this code](https://github.com/backstage/backstage/blob/59004176d29146f54ac7599dc6cc7f0155c121e2/plugins/lighthouse/src/components/AuditList/index.tsx#L78) it should work correctly, but I can’t see the pagination, can you please assist?

### 👍 Expected behavior

Pagination is rendered

### 👎 Actual Behavior with Screenshots

No pagination rendered
<img width="1440" alt="Screen Shot 2023-01-12 at 16 52 02" src="https://user-images.githubusercontent.com/588916/212099177-0e74328f-2769-4304-9723-bb437696aafe.png">
<img width="1438" alt="Screen Shot 2023-01-12 at 16 51 52" src="https://user-images.githubusercontent.com/588916/212099250-7c06e648-2145-4953-b479-8e82edd894b0.png">

### 👟 Reproduction steps

Go to Lighthouse plugin page

### 📃 Provide the context for the Bug.

Response to this request `https://our-own-backstage-lighthouse-service.companyName.com/v1/websites?limit=10&offset=0`
looks like 
```
{
websites: [10 items],
total: 12
}
```
<img width="624" alt="Screen Shot 2023-01-12 at 16 54 41" src="https://user-images.githubusercontent.com/588916/212099567-8f309a61-55e2-41f1-b6f6-8ac97a28165e.png">

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
The code expects the response to have a `limit` field as well (`items`, `total`, and `limit`). If both aren't present, it returns zero for the `pageCount` so it won't show the pagination. I'm not sure if this is correct or whether the response shape can vary across Lighthouse versions or so. We'd welcome a fix for it though, preferably by someone who has Lighthouse on hand and can try it out so it works.

**Comment by cakeinpanic** [comment]
thank you @freben!
I tried it and it worked! Issues of implementing our own server :)
