### ISSUE TITLE
🚀 Feature: Scaffolder template chaining/combining

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#15739]
### 🔖 Feature description

Scaffolder templates could be chained or combined so that small templates can make one big (like a golden path kind of template with multiple sub-templates). 

### 🎤 Context

Having specific, small, templates is very good from maintenance perspective but it can get confusing to the user what to run next. Having possibility to link the templates in on top template would make it easier for the users to jump to next step. For example:

1. Template1: Create a new repository
2. Template2: Populate repository with skeleton
3. Template3: Add CI configuration to repository

Each of these templates work very well alone but if the user would like to start project from scratch, each of these templates would need to be run one by one. This is unnecessary work and requires also that the user knows what to do next.

### ✌️ Possible Implementation

The template switching could be either by having some "Next step" buttons or something to jump to the next template or even combining all parameter inputs from the templates on a single page.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Related somewhat to https://github.com/backstage/backstage/issues/15241

**Comment by drodil** [comment]
Yes, you are correct. Templates frequently share the same steps and sharing them sounds very helpful feature. But still, I would say this is a slightly different feature as the user might want to opt-out of continuing to the following template.

**Comment by rocha-bruno** [comment]
@drodil I wrote a comment in #15241 that might help you :)
