### ISSUE TITLE
🐛 Bug Report: Kubernetes Backend Plugin causing errors after upgrading from 0.8.0 to 0.9.0

### ISSUE THREAD

**Issue by Lucas-Desouza** [backstage/backstage#15733]
### 📜 Description

We were recently trying to upgrade our backstage version and ran into an issue with the Kubernetes backend plugin. After upgrading it suddenly started giving us 403 on all calls. 

After some digging we found that there was a change in how the url is created which was a breaking change for how our app is configured. 

our cluster details url include a route prefix from rancher so `https://example.com/k8s/clusters/:id` but the call actually being sent out was: `https://example.com/apis/apps/v1/deployments?labelSelector=backstage.io/kubernetes-id=xxxx`

Looking at the code it seems to be happening here:   [ `url.pathname = resourcePath;`](https://github.com/backstage/backstage/blob/76110d7787a0b8d4fc64db3250c3168232768326/plugins/kubernetes-backend/src/service/KubernetesFetcher.ts#L206)

I pulled the repo locally and tested changing it to: `url.pathname += resourcePath;` and that resolved the issue. 

### 👍 Expected behavior

Expected the resourcePath to be appended to the url

### 👎 Actual Behavior with Screenshots

resourcePath was replacing the entire pathname.

### 👟 Reproduction steps

in your Kubernetes config

```
kubernetes:
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://example.com/k8s/clusters/someid
```

### 📃 Provide the context for the Bug.

Anything that uses the K8s backend stops working on the latest version. 

### 🖥️ Your Environment

Backstage upgraded to version 1.9.1 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jamieklassen** [comment]
yep this totally makes sense; didn't think about clusters with a base path when I rewrote the Fetcher...

**Comment by Lucas-Desouza** [comment]
This one had me chasing my tail for a little while but made sense when I saw it. I also checked if maybe there was some sort of prefix option for the resourcePath but didn't seem like it. Not sure If you would prefer to make the change of I should open a PR for it. Either way works for me.

**Comment by jamieklassen** [comment]
My team doesn't have bandwidth to create a fix immediately so feel free to pick it up. If you don't get to it, we will eventually!

**Comment by Lucas-Desouza** [comment]
I have a draft tagged just need to work on some adding a test
