### ISSUE TITLE
🐛 Bug Report: Firefox screenshots do not work beyond "above the fold"

### ISSUE THREAD

**Issue by ericis** [backstage/backstage#15754]
### 📜 Description

Related to the printing issue #15239, Firefox can only screenshot the first visible content on the page and fails on anything below that requires scrolling.

### 👍 Expected behavior

Firefox can screenshot any element, no matter how big it is and if part of the element is not visible on the screen due to scrolling.

### 👎 Actual Behavior with Screenshots

The screenshot will be cutoff to only what is visible rather than the entire, rendered element already on the page.

## Reproduce Backstage demo fail to screenshot

1. Go to https://demo.backstage.io/catalog/default/component/searcher
2. Resize the browser window such that the primary `<article>` within `<main>` is not entirely visible without scrolling
3. Use Firefox's built-in "Take Screenshot" capability to select the `<article>` element and note that the boundaries go below the visible content to cover the entire element
4. The browser may be "frozen" and you may be unable to scroll to the "Download" button because of this issue. So, press "Enter" or "Return" to automatically trigger the "Download" button click
5. View the downloaded image and notice that it is cutoff to only what is visible

## Compare backstage.io screenshot behavior

1. Go to https://backstage.io/
2. Resize the browser window such that any element is partially visible above the scrolling area
3. Use Firefox's built-in "Take Screenshot" capability to select the element and note that the boundaries go below the visible content to cover the entire element
4. Scroll down to the "Download" button. And click the button or press "Enter" or "Return" to download the screenshot as an image.
5. View the downloaded image and notice that the entire element is visible

### 📃 Provide the context for the Bug.

We cannot effectively screenshot larger sections of our Backstage instance without browser plugins that automatically scroll the page and cannot print due to issue #15239.

### 🖥️ Your Environment

- Windows 10 Enterprise and Professional
- Firefox and Chrome (latest evergreen)
- Backstage version:

    Live demo (assuming latest or near latest) as well as an internal version using the dependencies below...

    ```json
    
        "@backstage/app-defaults": "^1.0.10",
        "@backstage/catalog-client": "^1.2.0",
        "@backstage/catalog-model": "^1.1.4",
        "@backstage/cli": "^0.22.0",
        "@backstage/config": "^1.0.5",
        "@backstage/core-app-api": "^1.3.0",
        "@backstage/core-components": "^0.12.2",
        "@backstage/core-plugin-api": "^1.2.0",
        "@backstage/errors": "^1.1.4",
        "@backstage/integration-react": "^1.1.8",
        "@backstage/plugin-api-docs": "^0.8.13",
        "@backstage/plugin-catalog": "^1.7.1",
        "@backstage/plugin-catalog-common": "^1.0.9",
        "@backstage/plugin-catalog-graph": "^0.2.25",
        "@backstage/plugin-catalog-import": "^0.9.3",
        "@backstage/plugin-catalog-react": "^1.2.3",
        "@backstage/plugin-home": "^0.4.29",
        "@backstage/plugin-org": "^0.6.3",
        "@backstage/plugin-permission-react": "^0.4.8",
        "@backstage/plugin-scaffolder": "^1.9.1",
        "@backstage/plugin-search": "^1.0.6",
        "@backstage/plugin-search-common": "^1.2.0",
        "@backstage/plugin-search-react": "^1.3.1",
        "@backstage/plugin-shortcuts": "^0.3.5",
        "@backstage/plugin-stack-overflow": "^0.1.9",
        "@backstage/plugin-tech-radar": "^0.5.20",
        "@backstage/plugin-techdocs": "^1.4.2",
        "@backstage/plugin-user-settings": "^0.6.1",
        "@backstage/theme": "^0.2.16",
        "@backstage/types": "^1.0.2",
    ```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by maapteh** [comment]
We are also using the print to PDF option and experienced the same. We patched it by injecting:
```
@media print {
	#root > div main {
	     height: auto;
    	     display: block;
	}
```

but if you can fix it in your core that would be awesome, just add the height and display to this MAIN container. We just overrule it to patch it. Since the default is 100vh it will not print more then one page.

then there is something weird in the inner content as well (which has a shadow root for techdocs, which i also couldnt find), that has a default specific width, which for print we enlarge to 100% and remove the sidebar.

so in the end i also have hidden the nav and sidebar to make the most importent (doc content) nicely printable.

i would like to assist and fix it, if you can point me to the two lines where that css is in your setup...

**Comment by maapteh** [comment]
This shadow DOM is in https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/components/TechDocsReaderPageContent/TechDocsReaderPageContent.tsx#L22

**Comment by maapteh** [comment]
not stale

**Comment by maapteh** [comment]
not stale

if adding in total 6 css lines is so problematic to make all pages nicely printable...

**Comment by benjdlambert** [comment]
@maapteh do you want to contribute something to help us here? :pray:

**Comment by maapteh** [comment]
Yes, we have this backstage running in my company. But if you can tell me how to run it locally i can make a pr for it.
It is mainly at this part:
https://github.com/search?q=repo%3Abackstage%2Fbackstage%20calc(100%25%20-%2010px)&type=code
