### ISSUE TITLE
🐛 Bug Report: AzureDevOps Plugin - PullRequestPage not working for 2 Filters

### ISSUE THREAD

**Issue by deepan10** [backstage/backstage#15760]
### 📜 Description

Hi, 

In 'azure-devops' plugin, [PullRequestPage](https://github.com/backstage/backstage/blob/master/plugins/azure-devops/src/components/PullRequestsPage/PullRequestsPage.tsx) works great except the below two filters 

1. AssignedToCurrentUsersTeams
2. CreatedByCurrentUsersTeams

When we use these filter in **AzurePullRequestsPage** it always remains empty.

### 👍 Expected behavior

It should returns the pull-requests for the requested filter

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/5843888/212569523-9da83cf8-0b3d-4cce-a07e-44e7002a36d1.png)

### 👟 Reproduction steps

Go to **AzurePullRequestsPage** component with the below filters

```
{
    title: 'Assigned to my Teams',
    filters: [{ type: FilterType.AssignedToCurrentUsersTeams }],
    simplified: false,
  }, 
  {
    title: 'Created by my Teams',
    filters: [{ type: FilterType.CreatedByCurrentUsersTeams }],
    simplified: false,
  }
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
Maybe @awanlin knows more about this one?

**Comment by awanlin** [comment]
Hi @deepan10, are you on Azure DevOps Server or Azure DevOps Services the Cloud version? If you are on Server then I know we ran into issues with these due to how unique name works for the user.

**Comment by deepan10** [comment]
Hello @awanlin ,
I am using the Cloud version of Azure DevOps Service. 
I little bit explored about this issue and found, **useUserTeamIds** function on [useFilterProcessor.ts](https://github.com/backstage/backstage/blob/master/plugins/azure-devops/src/components/PullRequestsPage/lib/hooks/useFilterProcessor.ts) returns _undefined_ for **teamIds**, even for an valid userEmail after async.

If I do a Hot updated on the App manually by adding a comment on the file [useFilterProcessor.ts](https://github.com/backstage/backstage/blob/master/plugins/azure-devops/src/components/PullRequestsPage/lib/hooks/useFilterProcessor.ts) then the filters working.

**Comment by deepan10** [comment]
I figured out the solution, will submit the PR.

**Comment by deepan10** [comment]
Pull Request #15779  is submitted.

**Comment by awanlin** [comment]
Awesome, glad to hear you have a fix and even a PR to go with it. I've done a review and left a small optional comment. The Backstage maintainers will also need to review before it gets merged but having one of the plugin authors (I helped contribute the initial version of the Azure DevOps plugin) do an early review should help speed things up.

**Comment by Rugvip** [comment]
Closing since #15779 is now merged
