### ISSUE TITLE
🐛 Bug Report: [Tech insights plugin] the expired facts won't be cleared if the source entity is deleted

### ISSUE THREAD

**Issue by namco1992** [backstage/backstage#15762]
### 📜 Description

The tech insights plugin fact retriever supports [setting TTLs](https://github.com/backstage/backstage/tree/master/plugins/tech-insights-backend#adding-fact-retrievers) for the facts, and the expired records should be cleaned up automatically.

All of the fact retrievers we enabled have `lifecycle` set to `{ timeToLive: { weeks: 2 } }`. However, when I check the `facts` table, we see many records are clearly out of the 2 weeks range and not being cleared.

### 👍 Expected behavior

All the expired records in the `facts` table should be cleared.

### 👎 Actual Behavior with Screenshots

Many expired records are still in the database, and all of them are from entities that are removed from the catalog.

### 👟 Reproduction steps

```
=> select count(*) from tech_insights.facts where timestamp< now() - INTERVAL '14 DAY';
 count
--------
 237381
(1 row)
```

### 📃 Provide the context for the Bug.

The expired items cleanup happens in the `insertFacts`:
https://github.com/backstage/backstage/blob/7b47138d9a655625f17dbb372796a07a18bf1c23/plugins/tech-insights-backend/src/service/persistence/TechInsightsDatabase.ts#L120-L126

[`deleteExpiredFactsByDate`](https://github.com/backstage/backstage/blob/master/plugins/tech-insights-backend/src/service/persistence/TechInsightsDatabase.ts#L201) and [`deleteExpiredFactsByNumber`](https://github.com/backstage/backstage/blob/master/plugins/tech-insights-backend/src/service/persistence/TechInsightsDatabase.ts#L215) are the two methods that handle the actual deletion of the records, and both of them accept `factRows`, which are the latest facts from fact retrievers. **The `factRows` restrain the scope of the deletion to only the currently present entities. In other words, if an entity was present and then deleted, all the fact items related to that entity will be left in the database forever.**

For `deleteExpiredFactsByDate`, we can tweak the SQL query to make it delete all the expired records that match the fact retriever `id`. It would roughly be equivalent to the following statement:

```sql
delete from facts where id="entityMetadataFactRetriever" and timestamp < now() - INTERVAL '14 DAY'
```

We can delete in batch (say 5000 records at a time) so it won't choke the database.

However, it's a bit more complicated for `deleteExpiredFactsByNumber`. Since it means "delete all but N latest facts for each id/entity pair", it has to be aware what's the entity it's acting on. We could:
- Join the table in catalog. But it breaks the assumption that all the plugins should be isolated.
-  Query the catalog backend endpoint to check if the entity is still available, but I'm not sure if it will incur too much load on the backend.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
You can indeed not join with the catalog table. If you do need to make an existence check, you can use the new `/entities/by-refs` endpoint which, which can batch fetch any number of things by ref, returning nulls where there was no match. That can be combined with `fields` limiting to e.g. only get some placeholder like the `kind` to keep the response size down.

But would it have to have the existence check? Haven't checked the code, but sounds like it could group by ref no matter what, and leaving the actual "final" termination of things to the other janitor function to deal with.

**Comment by namco1992** [comment]
> But would it have to have the existence check? Haven't checked the code, but sounds like it could group by ref no matter what, and leaving the actual "final" termination of things to the other janitor function to deal with.

It's not needed for `deleteExpiredFactsByDate` coz the timestamp is the only thing we care about. 

On second thought, we might not need to have the existence check for `deleteExpiredFactsByNumber` either, but we need to leverage the scheduled task `cadence`.

For example, if we have a fact retriever registered like below:

```javascript
createFactRetrieverRegistration({
  cadence: '0 */6 * * *', // Run every 6 hours - https://crontab.guru/#0_*/6_*_*_*
  factRetriever: entityOwnershipFactRetriever,
  lifecycle: { maxItems: 7 },
}),
```

So the task runs every 6 hours, and we will keep the last 7 items. If the entity still exists, every run should generate an item. Therefore, if the first (id, entity) pair timestamp is earlier than 7 runs (which is 6*7=42 hours), but the total count of that (id, entity) pair is less than 7, then it means the entity disappears in between. That logic is a bit convoluted but I think it should be doable. 

It would be great if you and others can shed some light on this too!

**Comment by Xantier** [comment]
The PR linked will fix this for time based queries (as a side effect, the purpose of the PR wasn't initially to fix this). The `maxItems` variant is still unaddressed.

**Comment by Xantier** [comment]
For `maxItems` variant I believe a separate janitor job is probably the best approach. The implementation from the linked PR will eventually stale out timed facts but will leave `n` amount `maxItems` facts behind because the queries don't know which entities' facts should have `0` records and which entities' facts should have `n` records.

The janitor task can query the entites endpoint from catalog and find a difference between facts table references and those entities and then run the existing queries to rectify the DB. Note that for a large amount of entities the where-clause of the query will slow down query execution a lot (which is fixed in the linked PR) so I wouldn't add this as part of a scheduled task to ingest facts. Fact ingestion will happen at a more frequent cadence than deletion of stale data is necessary as well.

**Comment by freben** [comment]
I thought it was an option to also delete ANY data for ANY reason that's older than N days (whether the entity exists or not). But I'm honestly not up to speed on this one.

**Comment by Xantier** [comment]
Yup, there are two options to automatically clean the DB:
1. time based
2. amount of records based

#1 will now (after linked PR) remove all records when they stale out. 
#2 will _keep_ `n` records for each entity regardless if the entity is still present in the catalog or not

**Comment by namco1992** [comment]
Thanks for the fix @Xantier!

I have a question about the fix. After your PR the deletion query is this:
https://github.com/backstage/backstage/blob/3adb716e587608b9d5d0ceea2e20b708e2f8a065/plugins/tech-insights-backend/src/service/persistence/TechInsightsDatabase.ts?rgh-link-date=2023-01-16T09%3A35%3A04Z#L206-L212

May I ask what's the purpose for the `whereIn` here?

```javascript
   .and.whereIn('entity', db => 
     db.distinct('entity').where({ id: factRetrieverId }), 
   ) 
```

> For maxItems variant I believe a separate janitor job is probably the best approach. 

I agree with this too. Especially after your PR, it seems not necessary to be tied to the fact retriever's cadence anymore. Perhaps we should turn both of cleanup methods to a separate janitor task. @Xantier @freben WDYT?

**Comment by Xantier** [comment]
Thanks @namco1992. That's correct, for the timed queries we don't case about the entity so the `whereIn` is not needed. I'll create a subsequent PR to take that away.

**Comment by Rugvip** [comment]
@Xantier does this resolve this overall issue, or just a separate finding?

**Comment by efenner-cambia** [comment]
bump

**Comment by Xantier** [comment]
Thanks Evan, 

Will you provide a pull request for so we can get this merged in? There are at least two ways you can approach this:
1. Use the now added eventing functionality to inform when an entity is deleted and do the needed actions based on that
2. Add a scheduled job to remove facts for entities that are not present in the system anymore
