### ISSUE TITLE
[scaffolder] TypeScript Web Library as a default scaffold

### ISSUE THREAD

**Issue by fastfrwrd** [backstage/backstage#1576]
## Feature Suggestion

Saw a great demo of the scaffolder today, and realized that it probably wouldn't be too hard to support our nice [TypeScript Library (powered by web-scripts)](https://github.com/spotify/web-scripts-library-template) as a scaffold, as it is already open-source.

## Possible Implementation

It could be interesting to formally support using [GitHub's template repo](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) concept out-of-the-box for scaffolder. There would need to be some kind of transformation step to plug in/decorate the template with the additional files (such as the component-info), of course.

Some things to think about supporting:

- we should consider having a checkbox that, when selected, scaffolds the library as a CLI (with the bin entry and stuff), as that's a pretty common setup I end up with when using it.

## Context

Having a TypeScript Library fits in well to the list of default scaffolds, and could additionally provide a nice platform for showing people web-scripts, which I of course am selfishly drawn to. :)

**Comment by stefanalund** [comment]
@fastfrwrd that would be a great addition. Are you up for helping out? 😏  💯
