### ISSUE TITLE
🚀 Feature: [Kubernetes Plugin] collect CRDs for CustomResourceMatcher

### ISSUE THREAD

**Issue by DaisyGXSoon-InfraCanva** [backstage/backstage#15786]
### 🔖 Feature description

Dear Team,

I'm working on integrating backstage with kubernetes on my own cluster. And the majority of resources in my cluster are custom resources, so I want to edit the plugin a bit so that it could

- collect all the Custom Resource Definitions I'm interested in from cluster
- store the `group`, `version`, and `plural` from custom resource definitions as `customResourceMatcher[]`
- feed the `customResourceMatcher[]` along with `entityRef` and `auth` to `@kubernetes/src/api/KubernetesBackendClient/getCustomObjectsByEntity()`  to fetch all the custom resources defined by the CRDs collected 

### 🎤 Context

In my use case, I'll use this feature in the backend to fetch custom resources without the need of hardcoding the `customResourceMatcher` in the codebase. And I'll implement related frontend UI to display the custom resources since all my custom resources have a similar shape.

### ✌️ Possible Implementation

The only part to implement for this feature is to make a function return the CRDs in the cluster in the form of `customResourceMatcher[]`. I tried implement the function myself as following using the [kubernetes client library](https://github.com/kubernetes-client/javascript) provided.

```
export async function getCustomResourceMatchers():Promise<CustomResourceMatcher[]>{
  // make kubernetes client
  const kc = new KubeConfig();
  kc.loadFromDefault();
  const apiExts = kc.makeApiClient(ApiextensionsV1Api);
  // find all the crds -> filter interested crds
  const crds = await apiExts.listCustomResourceDefinition();
  const crdsToCheck = crds.body.items.filter(crd => crd.spec.group.endsWith('{the suffix of the CRDs I'm interested in}'));
  // the `group, version, plural` info -> `customResourceMatcher`
  const matchers : CustomResourceMatcher [] = []
  for (const crd of crdsToCheck) {
    for (const version of crd.spec.versions) {
      matchers.push({
        group: crd.spec.group,
        apiVersion: version.name,
        plural: crd.spec.names.plural
      })
    }
  }
  
  return matchers
} 
```
however, the problem is that the kubernetes client cannot be used in a browser as advised [here](https://github.com/kubernetes-client/javascript/issues/717), so I'm wondering where is the perfect place to put this function. Thank you for any suggestions!

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jamieklassen** [comment]
Sorry, I just realized that you're talking about using the new `getCustomObjectsByEntity` method on `KubernetesBackendClient`, which makes use of the `/resources/custom/query` which allows dynamically specifying the resource types to query. If you really want to keep your logic in the frontend, another option would be to hit the proxy endpoint, doing something like
```js
fetch(
  `${await this.discoveryApi.getBaseUrl('kubernetes')}/proxy/apis/apiextensions.k8s.io/v1/customresourcedefinitions`,
  {
    method: 'GET',
    headers: {
      'X-Kubernetes-Cluster': '{cluster name}',
      'Authorization': 'Bearer {token}'
    },
  },
)
```

and then do the filtering like you describe. Only problem is getting hold of a token, which is easier if your cluster uses a [client-side auth provider](https://backstage.io/docs/features/kubernetes/authentication#client-side-providers), and not very feasible at the moment if it uses a server-side one.

**Comment by DaisyGXSoon-InfraCanva** [comment]
Hi @jamieklassen , thank you for the detailed explanation! I looked into the endpoint you mentioned and added another route for the fetch of CRD, and now it works! Thank you!

**Comment by jamieklassen** [comment]
@DaisyGXSoon-InfraCanva were you planning to contribute this back as a PR, or were you just looking for guidance on how to patch your own Backstage? Wondering if we should close this issue (or convert it to a discussion? Not sure if that's a thing)

**Comment by DaisyGXSoon-InfraCanva** [comment]
@jamieklassen  i'm just seeking solution to patch my own! I'll close it! Thx
