### ISSUE TITLE
🐛 Bug Report: 'If Then' is not working on scaffolder yaml template

### ISSUE THREAD

**Issue by SerenaIce** [backstage/backstage#15789]
### 📜 Description

Based on the example in https://rjsf-team.github.io/react-jsonschema-form/, I used 'If Then' schema in my yaml template, but the condition doesn't work. Please let me know whether support the 'If Then' schema in Backstage now and how should I use it.

<img width="1748" alt="image" src="https://user-images.githubusercontent.com/43363062/212862998-08fb314f-487d-4b6a-9c0a-d3da3637b8e7.png">

### 👍 Expected behavior

It should work also like the examples listed in https://rjsf-team.github.io/react-jsonschema-form/ .

### 👎 Actual Behavior with Screenshots

Conditions don't work.

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/43363062/212863615-63bc88c7-11a6-4f3c-ab34-82fa954076af.png">

### 👟 Reproduction steps

My test template:

`apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ccc
  title: bbb
  description: aaa
spec:
  owner: xxx
  type: service
  parameters:
    title: Test
    type: object
    properties:
      animal:
        enum:
          - Cat
          - Fish
    allOf:
      - if:
          properties:
            animal:
              const: Cat
        then:
          properties:
            food:
              type: string
              enum:
                - meat
                - grass
                - fish
          required:
            - food
      - if:
          properties:
            animal:
              const: Fish
        then:
          properties:
            food:
              type: string
              enum:
                - insect
                - worms
            water:
              type: string
              enum:
                - lake
                - sea
          required:
            - food
            - water
      - required:
          - animal
`

<img width="469" alt="image" src="https://user-images.githubusercontent.com/43363062/212864418-552b1449-8358-4432-be6c-0439f0c8cdbe.png">

### 🖥️ Your Environment

macOS

Backstage: 1.8.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey :wave: so this is expected as `v3` of `react-jsonschema-form` doesn't support it. It was shipped in `v4` however that had incompatibles with the `material-ui` theme, so we have to wait for `v5`. The good news is that the work has been done to implement `v5` already, but we're just waiting for it to reach stable before we can start to roll it out to users to test and experiment with. Hopefully we think there should be a `v5-stable` release around the end of this month so watch this space and will update when it's available for testing.

**Comment by nthings** [comment]
any update?

**Comment by awanlin** [comment]
@nthings, you'll want to read the docs for the `scaffolder/next` here: https://backstage.io/docs/features/software-templates/testing-scaffolder-alpha

**Comment by carlbjor** [comment]
also interested in this feature

**Comment by aaronnickovich** [comment]
When using saffolder/next you can do something like the following. This will make a second field required if the first field equals a specific string, in this case when foo = bar, then baz becomes required.

parameters:
  - title: test field dependencies
    properties:
      foo:
        type: string
      baz:
        type: string
    if:
      properties:
        foo:
          enum:
            - bar
    required:
      - foo
    then:
      required:
        - baz
    else: false

**Comment by benjdlambert** [comment]
Closing this as it's fixed in `scaffolder/next` :tada:
