### ISSUE TITLE
🐛 Bug Report: TechDocs page reloads when clicking anchor links

### ISSUE THREAD

**Issue by sqsp-rwatkins** [backstage/backstage#15804]
### 📜 Description

I visit _catalog_ docs on our own backstage instance, or the demo instance and click a heading anchor link the page reloads and does not scroll to the heading.

The following issues are related but pertain to Docs instead of Catalog > Docs:
https://github.com/backstage/backstage/issues/10803
https://github.com/backstage/backstage/issues/11003

### 👍 Expected behavior

The page should not reload and visit the heading.

### 👎 Actual Behavior with Screenshots

It reloads and misses the heading.

https://user-images.githubusercontent.com/114502094/212944630-4de1ebfe-cde8-4ed2-a8c8-c6b788086172.mov

### 👟 Reproduction steps

1. Go to https://demo.backstage.io/catalog/default/component/backstage/docs/conf
2. Click any anchor heading link
3. Note that the page reloads and does not visit the link

### 🖥️ Your Environment

I have replicated this using Chrome, Brave and Safari. It works fine in Firefox. It also works ok when running locally.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GunnerStraiker1** [comment]
We (EG) have the same issue even when we click a link in the primary sidebar, in our case when we click on the primary sidebar to change to another doc page, it reloads, shows the previous doc for a little moment, and then shows the desired page

**Comment by benjdlambert** [comment]
What version are you all running? We had a similar issue that the page would end up re-rendering if the query string parameters change, but this was fixed and shipped in 1.9 wondered if this still occurs on versions later than that?

**Comment by sqsp-rwatkins** [comment]
@benjdlambert We're on 1.9 and still seeing the issue.

**Comment by benjdlambert** [comment]
@backstage/techdocs-core for visibility

**Comment by unixunion** [comment]
Im experiencing this issue with my techdocs, on latest versions.  Clicking any anchor link in Markdown techdocs is just refreshing the page. Also my markdowns are long, so really need this. 

OS:   Darwin 22.1.0 - darwin/x64
node: v16.16.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.14.2

Dependencies:
  @backstage/app-defaults                                   1.3.1
  @backstage/backend-app-api                                0.4.3
  @backstage/backend-common                                 0.18.5
  @backstage/backend-dev-utils                              0.1.1
  @backstage/backend-plugin-api                             0.5.2
  @backstage/backend-tasks                                  0.5.2
  @backstage/catalog-client                                 1.4.1
  @backstage/catalog-model                                  1.3.0
  @backstage/cli-common                                     0.1.12
  @backstage/cli-node                                       0.1.0
  @backstage/cli                                            0.22.7
  @backstage/config-loader                                  1.3.0
  @backstage/config                                         1.0.7
  @backstage/core-app-api                                   1.8.0
  @backstage/core-components                                0.13.1
  @backstage/core-plugin-api                                1.5.1
  @backstage/dev-utils                                      1.0.15
  @backstage/errors                                         1.1.5
  @backstage/eslint-plugin                                  0.1.3
  @backstage/integration-aws-node                           0.1.3
  @backstage/integration-react                              1.1.13
  @backstage/integration                                    1.4.5
  @backstage/plugin-adr-backend                             0.3.3
  @backstage/plugin-adr-common                              0.2.9
  @backstage/plugin-adr                                     0.6.1
  @backstage/plugin-api-docs                                0.9.4
  @backstage/plugin-app-backend                             0.3.45
  @backstage/plugin-auth-backend                            0.18.3
  @backstage/plugin-auth-node                               0.2.14
  @backstage/plugin-bitbucket-cloud-common                  0.2.6
  @backstage/plugin-catalog-backend-module-bitbucket-server 0.1.10
  @backstage/plugin-catalog-backend-module-bitbucket        0.2.12
  @backstage/plugin-catalog-backend-module-msgraph          0.5.4
  @backstage/plugin-catalog-backend                         1.9.1
  @backstage/plugin-catalog-common                          1.0.13
  @backstage/plugin-catalog-graph                           0.2.30
  @backstage/plugin-catalog-import                          0.9.8
  @backstage/plugin-catalog-node                            1.3.6
  @backstage/plugin-catalog-react                           1.6.0
  @backstage/plugin-catalog                                 1.11.1
  @backstage/plugin-explore-backend                         0.0.7
  @backstage/plugin-explore-common                          0.0.1
  @backstage/plugin-explore-react                           0.0.28
  @backstage/plugin-explore                                 0.4.4
  @backstage/plugin-github-actions                          0.5.18
  @backstage/plugin-jenkins-backend                         0.2.0
  @backstage/plugin-jenkins-common                          0.1.15
  @backstage/plugin-jenkins                                 0.8.0
  @backstage/plugin-kubernetes-backend                      0.11.0
  @backstage/plugin-kubernetes-common                       0.6.3
  @backstage/plugin-kubernetes                              0.9.1
  @backstage/plugin-lighthouse-common                       0.1.1
  @backstage/plugin-lighthouse                              0.4.3
  @backstage/plugin-org                                     0.6.8
  @backstage/plugin-permission-common                       0.7.5
  @backstage/plugin-permission-node                         0.7.8
  @backstage/plugin-permission-react                        0.4.12
  @backstage/plugin-proxy-backend                           0.2.39
  @backstage/plugin-scaffolder-backend                      1.14.0
  @backstage/plugin-scaffolder-common                       1.3.0
  @backstage/plugin-scaffolder-node                         0.1.3
  @backstage/plugin-scaffolder-react                        1.4.0
  @backstage/plugin-scaffolder                              1.13.1
  @backstage/plugin-search-backend-module-catalog           0.1.1
  @backstage/plugin-search-backend-module-explore           0.1.1
  @backstage/plugin-search-backend-module-pg                0.5.6
  @backstage/plugin-search-backend-module-techdocs          0.1.1
  @backstage/plugin-search-backend-node                     1.2.1
  @backstage/plugin-search-backend                          1.3.1
  @backstage/plugin-search-common                           1.2.3
  @backstage/plugin-search-react                            1.6.1
  @backstage/plugin-search                                  1.3.1
  @backstage/plugin-sonarqube-backend                       0.1.10
  @backstage/plugin-sonarqube-react                         0.1.5
  @backstage/plugin-sonarqube                               0.6.7
  @backstage/plugin-tech-radar                              0.6.4
  @backstage/plugin-techdocs-backend                        1.6.2
  @backstage/plugin-techdocs-module-addons-contrib          1.0.13
  @backstage/plugin-techdocs-node                           1.7.1
  @backstage/plugin-techdocs-react                          1.1.6
  @backstage/plugin-techdocs                                1.6.3
  @backstage/plugin-user-settings                           0.7.3
  @backstage/release-manifests                              0.0.9
  @backstage/test-utils                                     1.3.1
  @backstage/theme                                          0.3.0
  @backstage/types                                          1.0.2
  @backstage/version-bridge                                 1.0.4

**Comment by benjdlambert** [comment]
@agentbellnorm what's the update here?
