### ISSUE TITLE
🚀 Feature: Templates from external git source

### ISSUE THREAD

**Issue by hsbacot** [backstage/backstage#15818]
### 🔖 Feature description

Extend the yarn new plugin command to use templates defined externally.

### 🎤 Context

At LinkedIn we’re using backstage across multiple projects. We’d like to leverage the existing backstage cli to be able to generate plugins from templates with internal patterns and tools. Using the backstage cli would be a win for us because it would keep teams from learning an additional tool/cli, and would keep the workflow consistent. We also believe this would be a beneficial addition to the cli that others could use. 

Alternatively, we’d need to create our own cli to handle this functionality if this is not seen as a realistic addition to the backstage cli. This would fragment our users’ usage of backstage when developing plugins.

Note: [#14585](https://github.com/backstage/backstage/issues/14585) appears similar in idea but the discussion focuses on creating the templates within a plugin in the same project to house the templates. We’d need this to be more general and are proposing to import templates from an external git source.

### ✌️ Possible Implementation

Extend the createPlugin.ts file to look for a named argument. (ex: template ). This would look for existing templates within backstage (frontend, backend, etc.) but could also be passed a git repository URL. If passed a repository URL, clone and use the contents of the repository as the template for the new plugin.

An example of it being used could be:
```bash
backstage-cli new --select plugin —-template=https://github.com/awesome-team/backstage-plugin-template
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tonedef** [comment]
Would love this! It's a pattern I see in other frameworks/platforms (e.g. Ember Blueprints). Generating a plugin that has all the boilerplate specific to your backstage instance without having to refactor much, if anything, for what's generated would be awesome!

**Comment by Rugvip** [comment]
For sure! This has been planned for some time but haven't been able to prioritize it. Would you like to outline an idea for an initial implementation @hsbacot? I could see a couple of different ways in which the different factories and templates could be extended and brought in. I think something like this could exist in parallel to #14585 as well.

**Comment by hsbacot** [comment]
Awesome, I'll put an outline together 🤠

**Comment by hsbacot** [comment]
## Option 1 

We're thinking of extending the `--select` option to provide a git URL. Overloading the `--select` keeps it simple for the end user by not introducing new options. 


Pass it a Git URL that points to a repo that contains a plugin template.

```bash
backstage-cli new --select git@github.com:USER/my-plugin.git
```
## Option 2

Alternatively, we could add an extra option to specify the plugin factory and the URL as an option:

```bash
backstage-cli new --select git-plugin --option git-url=git@github.com:USER/my-plugin.git
```

Does anyone have a preference between these two options?

**Comment by Rugvip** [comment]
@hsbacot overloading `--select` heads into #14585 territory to be honest, which is likely going to be a bit more complex. If we want to keep this a bit more simple then we'd want to keep this limited to only replacing the template content, rather than replacing the entire factory. Maybe something like a `--template <url/path>` flag. To clarify, the `--select` both chooses which template to use, but also the factory that executes the change and decides what input should be gathered.
