### ISSUE TITLE
🐛 Bug Report: It is unclear that feature flag toggle requires refresh

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#15845]
### 📜 Description

When turning feature flag on or off, a page refresh is required to make it take effect

### 👍 Expected behavior

Switching feature flag on or off should re-render the current page 

### 👎 Actual Behavior with Screenshots

Feature flags don't affect the current state of UI before page is refreshed

### 👟 Reproduction steps

1. Add a feature flag to the application
2. Make one of the menu items to be behind a feature flag
3. Go to user settings
4. Toggle feature flag on
5. Menu item is not visible until page refresh

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
This is very intentional, as it makes it significantly easier to implement feature flags at any point in the app or plugins. We could add some form of API for watching feature flag state, but the worry then is that some flags will work that way and others wont, and the user has no idea. To be able to do this I think we need to attack that problem directly, with some way to register a feature flag as "live", and then inform users whether they need to reload the page after changing a flag or not.

**Comment by drodil** [comment]
Yeah, at least informing the user to refresh the page when changing a flag would be a good thing. It would work as a first step before jumping into the implementation of "live" flags

**Comment by Rugvip** [comment]
Yep, totally! Let us know if you want to submit a PR for that, I've opened it up either way

**Comment by Parsifal-M** [comment]
Hey @Rugvip :wave: 

Seems fairly straightforward, are you thinking of some kind of message here in the UI with what @drodil mentions?

:point_right: https://demo.backstage.io/settings/feature-flags

I.e. maybe a message in the card saying `Please refresh the page when enabling feature flags`

LMK?

**Comment by drodil** [comment]
Yes that would be the correct place. Even better would be changing the phrasing to `Please refresh the page when toggling feature flags` as it also applies to disabling those. And in implementation POV the message should only be shown when toggle is changed, what do you think?

**Comment by Parsifal-M** [comment]
Sounds good to me, is this something you want to raise a pr for @drodil? Otherwise, I have some spare time today/tomorrow I could give it a shot :muscle: 

Also of course if @Rugvip agrees :wink:

**Comment by drodil** [comment]
I could but not sure when I have time so go ahead if you do :)

**Comment by Parsifal-M** [comment]
Very K.I.S.S approach (always the best) :smile: 

![image](https://user-images.githubusercontent.com/13601053/214043043-e24fc718-b718-4c69-be75-df3e82e9c31e.png)

Will make a PR later today, what do you think @Rugvip, @drodil?

Thanks!

**Comment by drodil** [comment]
Message added by @Parsifal-M , will close this issue now.
