### ISSUE TITLE
🐛 Bug Report: GitHub Issues plugin's README.md usage examples refers to wrong/misspelled components

### ISSUE THREAD

**Issue by divyanshiGupta** [backstage/backstage#15848]
### 📜 Description

In the GitHub Issues plugin's [README.md](https://github.com/backstage/backstage/tree/master/plugins/github-issues#github-issues-plugin) the provided usage examples does not refer to the correct components.

### 👍 Expected behavior

The provided example should use `GithubIssuesPage` and `GithubIssuesCard`.
  
  

### 👎 Actual Behavior with Screenshots

It actually uses `GitHubIssuesPage` and `GitHubIssuesCard` instead which doesnt exist.

### 👟 Reproduction steps

https://github.com/backstage/backstage/tree/master/plugins/github-issues#usage

1. Go to above link 
2. Notice the examples are referring to the wrong/misspelled components.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by adamdmharvey** [comment]
I think this one may be resolved now, thanks to your awesome contribution. Would you agree @divyanshiGupta ?

**Comment by benjdlambert** [comment]
Going to close this ticket, feel free to reach out if there's something that's missing! :pray:
