### ISSUE TITLE
🚀 Feature: Make template source tool tip more understandable in template card

### ISSUE THREAD

**Issue by Teemukoivumaa** [backstage/backstage#15850]
### 🔖 Feature description

Currently on the template card, the location tool tip of where the template is stored, only tells you what integration it uses.
![image](https://user-images.githubusercontent.com/35847478/213425358-ccb9eb9e-569b-4554-bb81-c99cddeaf9a8.png)

This isn't really helpful information for the end user.

My proposal would be to change the tooltip to be something like this: "See template code in X". The X would be the integration type. For example: "See template code in github"
![image](https://user-images.githubusercontent.com/35847478/213426320-a202ec0e-0847-46ab-90c3-eacc05dae377.png)

### 🎤 Context

Would offer more helpful information for the end user about what this link does.

### ✌️ Possible Implementation

Not the hardest thing to implement and I'm willing to do it. Only need to add some logic here: https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/TemplateCard/TemplateCard.tsx#L262

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Hey :wave: So these components are actually changing a little bit in an upcoming version of the scaffolder. Here's a little sneak peek:

![image](https://user-images.githubusercontent.com/3645856/214016883-3ef12bb9-cd64-4e10-ab26-ab323a084005.png)

I think that it would make sense for us just to provide a simple component out of the box like the above, and the ability to provide your own version of the card to which you can add more things to like the `Link to source..` parts. Does this make sense and we can close this ticket?

**Comment by Teemukoivumaa** [comment]
Yeah I'm good with that. Clad to hear that it will offer more customization options in the future!😄

**Comment by benjdlambert** [comment]
Thanks!
