### ISSUE TITLE
🚀 Feature: Support for tRPC as an API type

### ISSUE THREAD

**Issue by RobotSail** [backstage/backstage#15877]
### 🔖 Feature description

tRPC is an alternative to GraphQL and REST endpoints which has been rising in popularity and usage over the past few years. It would be nice to see an integration added for it.

### 🎤 Context

I don't personally have this as a use-case yet, but I imagine that if there is already support for GraphQL, REST, and gRPC, adding tRPC as an API type would be a natural conclusion.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Sounds reasonable to explore. I'm wondering what this might look like in practice, i.e. what definition would be placed in the entity spec, and what tools are there that could help us render docs? In case those things don't really exist we could probably look at alternate solutions, but of course that requires some exploration too. In the end if the API is too tied to the implementation it might be that it doesn't quite fit as an API entity.

**Comment by RobotSail** [comment]
I'm not certain on how the other APIs work in the context of Backstage, I would imagine that tRPC would be most similar to GraphQL, but the process of making network requests seems to be abstracted to making calls through the tRPC library. 
And if consuming a tRPC API just looks like running `yarn add my-library`, what would this look like, and would we even need support for tRPC APIs within Backstage?

**Comment by RobotSail** [comment]
So it does look like calling tRPC APIs externally is a thing, and there's an OpenAPI plugin here that will allow your tRPC APIs to be documented: [trpc-openapi](https://github.com/jlalmes/trpc-openapi/tree/master).
I couldn't find it on the tRPC website, but the create-t3-app project documents how tRPC can be called externally here: [Calling your tRPC API Externally](https://create.t3.gg/en/usage/trpc#how-do-i-call-my-api-externally).

**Comment by benjdlambert** [comment]
I think that it makes more sense from the tRPC POV to include the actual typescript client definitions in the API definition rather than the `openapi` spec, as the main entrypoint to a tRPC server is not to call it directly right? It's to use the tRPC generated client to communicate with the server somewhat similar to `GRPC`. We have tooling in our repository that can take the exports from a typescript library and convert it to markdown, I wonder if this is what we want to expose here rather than the `openapi` definition?

**Comment by RobotSail** [comment]
@benjdlambert That's correct, I imagine that probably 90-95% of tRPC usage would be directly through the client or router definitions.

Where I imagine it would still be useful to expose the OpenAPI spec would be if a team had put together a Next.js server, and other MicroServices not part of the monorepo. I imagine that this would be less of a use-case but might still exist, so whatever solution would be extended to include this, if needed.

**Comment by taras** [comment]
I shared this link in another chat on this topic https://github.com/backstage/backstage/blob/master/plugins/api-docs/src/components/ApiDefinitionCard/ApiDefinitionWidget.tsx#L31

This is where you can add a renderer specific for tRPC. Would that be just a syntax highlighter of the TS file?

**Comment by RobotSail** [comment]
So I've created a pull-request for this issue at #16092. This takes the simple approach of displaying the associated router definition. 
I'm not sure if there's anything else that needs to happen besides displaying the various router definitions on the API page. The only other thing I could think of is exposing tRPC via OpenAPI for external services to interface with, but this would probably need to be handled in a separate PR, similar to #15667, since there also exists [trpc-openapi](https://github.com/jlalmes/trpc-openapi).
