### ISSUE TITLE
🐛 Bug Report: `RepoUrlPickerHost` field extension in scaffolder has wrong font

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [backstage/backstage#15882]
### 📜 Description

The font getting displayed in the select box for selecting the repo URL in the scaffolder is not showing the font used elsewhere.

### 👍 Expected behavior

The select element should be of the same font as the rest of the application.

### 👎 Actual Behavior with Screenshots

This is how the picker element looks like
![image](https://user-images.githubusercontent.com/13748882/213848719-552695a8-14bd-4867-8dfb-2215e5b0212b.png)
As you can see, the font is a serif font and some analysis tells me its in the Times New Roman font family whereas the rest of the app uses the Helevtica neue sans serif font family.

I believe the reason is because this element is using the `Select` component from Backstage core which is turn is using the native `<Select>` tag. Now, [`<Select>` is notoriously difficult to style](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#styling_with_css) and its no wonder that the options are not taking up the correct font.

My suggestion would be to use the `Autocomplete` element from material ui like used elsewhere which has much better styling and control.

### 👟 Reproduction steps

1. Run the example app from the backstage repo
2. Go to the Create scaffolder section and choose an existing scaffolder, say spring boot.
3. Fill up the first step and go to the second step
4. Check the font family of the Host select

### 🖥️ Your Environment

This issue happens in the current master at 974e5f28645cda7943355936e2291e732ba3908f

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by SayakMukhopadhyay** [comment]
Ignore my analysis that this is due to `<Select>` element. Now, it seems like the `<Select>` core component in `packages/core-components` is getting defined with custom input styling. The below change is enough to fix the select box
![image](https://user-images.githubusercontent.com/13748882/213930258-5a2433c4-1ddb-47a0-8637-4197d798347c.png)
Updated Select
![image](https://user-images.githubusercontent.com/13748882/213930298-f0fd6885-1386-4c2e-9222-147efdd5463b.png)

**Comment by Rugvip** [comment]
I think this line in particular is what we'd want to fix in this case right? https://github.com/ayshiff/backstage/blob/ea4ebc58b3517869d02e315d0005f2f890b37169/packages/core/src/components/Select/Select.tsx#L54. Maybe it can simply be removed, otherwise we'd want to grab the font from the theme.

**Comment by SayakMukhopadhyay** [comment]
Yes, removing that line fixes that font. But I don't get the point of the whole of the styles that are being added. The input element in the select already looks the same (imo) without the additional styling given to it. It just seems redundant to me and extra points of failure in the future.

**Comment by SayakMukhopadhyay** [comment]
Not stale

**Comment by benjdlambert** [comment]
Wonder if we should just use the `mui` select instead, as it would also probably fix some of the other styling bugs that we've noticed.

**Comment by SayakMukhopadhyay** [comment]
Sorry for the delayed response. I have 2 thoughts on this.

1. `Select` from `core-components` is already using `mui`. I think tweaking the core component a bit could be helpful. Or better yet, use mui@5 since we are making the migration anyway.
2. We update the field extensions using `Select` to instead use something like `FieldTemplate` from #17952 to bring some cohesion to the styling.

**Comment by SayakMukhopadhyay** [comment]
Not stale

**Comment by benjdlambert** [comment]
@SayakMukhopadhyay probably don't want to switch to mui5 yet, as people might still only be using mui4 until we're ready to make the switch for all plugins in this repo. Do you want to whip up a PR with a suggested fix?
