### ISSUE TITLE
🐛 Bug Report: Unable to read URL

### ISSUE THREAD

**Issue by VJ1243** [backstage/backstage#15880]
### 📜 Description

When trying to register existing API

### 👍 Expected behavior

Register the API

### 👎 Actual Behavior with Screenshots

Error

![image](https://user-images.githubusercontent.com/7876511/213820661-bf69494e-ffc9-48b7-aed8-d19c04210853.png)

### 👟 Reproduction steps

API -> Register Existing API -> Enter valid github URL - > click Analyze

### 📃 Provide the context for the Bug.

Trying to test locally, followed the documentation to set up github integration

### 🖥️ Your Environment

Development

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Does the URL you're using match the example to the right under "Link to an existing entity file"? It's looking quite short

**Comment by VJ1243** [comment]
Closing the issue, its due to a configuration issue. thanks.

**Comment by akathecoder** [comment]
Hey @VJ1243 , can you update how you resolved this error? Thanks.
