### ISSUE TITLE
🚀 Feature: App description should come from config

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#15893]
### 🔖 Feature description

Currently, the application description is hardcoded to https://github.com/backstage/backstage/blob/master/packages/app/public/index.html#L9

This, like the title, should come from the application config if available. 

### 🎤 Context

Description change requires now that the index page is modified instead of app config. This makes changing the title and description work differently.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
I think we'll want to leave this to be configurable manually in `packages/app/public/index.html`. The title is already available in config so it makes sense to grab it by default, but I'm feeling it's not worth adding a new configuration key for the description, at least not at this point.

**Comment by drodil** [comment]
Ok, it's just a bit weird that these live in different places 😄 I wouldn't mind having another config value for description. Or removing the title; just as long as it's consistent.

**Comment by benjdlambert** [comment]
@drodil yeah I appreciate that and it's a little unfortunate that if we were to remove the title from config it would be a breaking change. We were just thinking that it's one of the most common use cases and that option was in config from the beginning. Happy to keep this open to see if there's others that want to chime in too on maybe adding some other options in config.
