### ISSUE TITLE
🐛 Bug Report: `techdocs-cli serve` is not working.

### ISSUE THREAD

**Issue by vonjones** [backstage/backstage#15903]
### 📜 Description

techdocs-cli serve is not working. When I run it, it launches my local browser, but never loads

### 👍 Expected behavior

The techdocs-cli serve command should render my documents.

### 👎 Actual Behavior with Screenshots

![Screen Shot 2023-01-23 at 2 55 48 PM](https://user-images.githubusercontent.com/16352323/214148566-34f665f4-8d0a-4537-bd21-6e0eddf6c58e.png)

### 👟 Reproduction steps

I'm just running

```
npm install -g @techdocs/cli
techdocs-cli serve
```

### 📃 Provide the context for the Bug.

I'd like to allow teams in my company to preview docs before they merge.  They presently have to use

```
docker run --rm -v `pwd`:/mnt/pwd -w /mnt/pwd -p 8000:8000 -i spotify/techdocs:latest serve -a 0.0.0.0:8000
```

but this doesn't render documents as they would render in Backstage. For example, it does not render mermaid, since that requires a Backstage plugin. It's styled like Mkdocs rather than Backstage. I'd prefer the approach of the techdocs-cli to render something closer to what the user will see after they merge their doc changes.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by vonjones** [comment]
I see this error in my browser console log:

`react_devtools_backend.js:4012 DEPRECATION WARNING: All elements within <FlatRoutes> must be of type <Route> with an element prop. Existing usages of <Navigate key=[path] to=[to] /> should be replaced with <Route path=[path] element={<Navigate to=[to] />} />.`

**Comment by vonjones** [comment]
The page looks like it's at least partially loading from the mkdocs server. I see an element called #shadow_root, with an opacity 0. If I disable that opacity setting, I get this.

![image](https://user-images.githubusercontent.com/16352323/217976126-e46b1c88-7f80-43f1-b587-2a5a1b748261.png)

Here's the output of `techdocs-cli serve --verbose`:
```
von.jones@von-jones backstage-catalog % techdocs-cli serve --verbose
info: Starting mkdocs server.
verbose: [docker/mkdocs] INFO     -  Building documentation...
verbose: [docker/mkdocs] WARNING  -  Config value: 'dev_addr'. Warning: The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead.
verbose: [docker/mkdocs] INFO     -  Cleaning site directory
verbose: [docker/mkdocs] INFO     -  Documentation built in 0.67 seconds
verbose: [docker/mkdocs] INFO     -  [01:00:13] Watching paths for changes: 'docs', 'mkdocs.yaml'
verbose: [docker/mkdocs] INFO     -  [01:00:13] Serving on http://0.0.0.0:8000/
info: [techdocs-preview-bundle] Running local version of Backstage at http://localhost:3000
                                                                                           info: Serving docs in Backstage at http://localhost:3000/docs/default/component/local/
                                                                              Opening browser.
                                                                                              verbose: [docker/mkdocs] INFO     -  [01:00:14] Browser connected: http://localhost:8000/CONTRIBUTING/
```

**Comment by vonjones** [comment]
This was my error. I had not run `techdocs-cli generate` beforehand.

**Comment by alexef** [comment]
I also ran into this today. It was not clear in [the docs](https://backstage.io/docs/features/techdocs/cli/) that `generate` must run before `serve`
