### ISSUE TITLE
🐛 Bug Report: AzureSites Plugin TypeError and not loading UI

### ISSUE THREAD

**Issue by deepan10** [backstage/backstage#15904]
### 📜 Description

Hi,
With a fresh [AzureSites ](https://github.com/backstage/backstage/tree/master/plugins/azure-devops)Plugin on Backstage, `EntityAzureSitesOverviewWidget` Component failed with TypeError

### 👍 Expected behavior

It should show the table with the Azure Sites details

### 👎 Actual Behavior with Screenshots

As soon as the `EntityAzureSitesOverviewWidget` component loaded UI failed with below error
![image](https://user-images.githubusercontent.com/5843888/214156685-7acd73ae-b70d-4f58-9055-e63780a2c026.png)

### 👟 Reproduction steps

Install a Azure Sites Plugin and add `<EntityAzureSitesOverviewWidget />` component into your service entity page, with the proper annotation and App config run Backstage.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Fixed by #15911, thanks! 👍
