### ISSUE TITLE
🐛 Bug Report: backstage-cli versions:bump doesn't respect http_proxy

### ISSUE THREAD

**Issue by joewood** [backstage/backstage#15905]
### 📜 Description

When trying to version bump an installation of inside a corporate network environment, the backstage-cli errors out with a network error accessing the versions.backstage.io domain. 

This is closely related to https://github.com/backstage/backstage/issues/13892 - but the fix is simpler in this case as the backstage cli should respect convention and use the configured corporate proxy if one is available (via https_proxy/http_proxy).

### 👍 Expected behavior

The backstage-cli should use the http_proxy environment variable and successfully upgrade. 

The fix is to simply configure a global agent on http if the environment variable is set.

### 👎 Actual Behavior with Screenshots

Errors out with:

```
FetchError: request to https://versions.backstage.io/v1/tags/main/manifest.json failed, reason: connect ECONNREFUSED 185.199.108.153:443
```

### 👟 Reproduction steps

In any backstage repo, run the command:

```
export https_proxy=http://myproxy.mycompany.com:8080
npx backstage-cli versions: bump
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
So unfortunately the `HTTP_PROXY` vars are not respected by default in `node`. We'd have to include something like one of the options mentioned in this document thhttps://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md in the CLI. Is this something you would want to contribute?

**Comment by myplaybooks** [comment]
@joewood
I am facing the same issue and tried @benjdlambert solution and it didn't work for me. May I know how you have resolved this?

**Comment by myplaybooks** [comment]
@joewood
I am facing the same issue and tried @benjdlambert solution and it didn't work for me. May I know how you have resolved this?

**Comment by myplaybooks** [comment]
@joewood
I am facing the same issue and tried @benjdlambert solution and it didn't work for me. May I know how you have resolved this?

**Comment by myplaybooks** [comment]
GLOBAL_AGENT_HTTP_PROXY=$HTTP_PROXY
GLOBAL_AGENT_NO_PROXY=$NO_PROXY
resolved my issue

**Comment by satrox28** [comment]
> GLOBAL_AGENT_HTTP_PROXY=$HTTP_PROXY GLOBAL_AGENT_NO_PROXY=$NO_PROXY resolved my issue

Hi @myplaybooks 

I am facing same issue, did you install the global agent package?

**Comment by myplaybooks** [comment]
export GLOBAL_AGENT_HTTP_PROXY=$HTTP_PROXY
export GLOBAL_AGENT_NO_PROXY=$NO_PROXY

this fixed my issue.

**Comment by gokceng-intertech** [comment]
> export GLOBAL_AGENT_HTTP_PROXY=$HTTP_PROXY export GLOBAL_AGENT_NO_PROXY=$NO_PROXY
> 
> this fixed my issue.

Can you please explain where did you use those commands and did you also install global agent package?
