### ISSUE TITLE
🐛 Bug Report: AzureSites Plugin Start & Stop throws 404

### ISSUE THREAD

**Issue by deepan10** [backstage/backstage#15907]
### 📜 Description

Hi,
With a new [AzureSites ](https://github.com/backstage/backstage/tree/master/plugins/azure-devops) Plugin on Backstage, Start & Stop action throws 404 error.

![image](https://user-images.githubusercontent.com/5843888/214231849-56476388-1491-461d-ba52-b5d7e5df05c3.png)

### 👍 Expected behavior

- The Stop action should stop the Azure App Service /Function 
- The Start action should start the Azure App Service /Function

### 👎 Actual Behavior with Screenshots

For both action it returns 404 error

![image](https://user-images.githubusercontent.com/5843888/214232318-7f8a9533-69cd-4d31-a0c2-278dfbe536fe.png)

### 👟 Reproduction steps

Install a new Azure Sites Plugin and add Azure App Service/Function service entity with the proper annotation and App config run Backstage. Try to start & stop the Azure App Service/Function service via Backstage.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Fixed by #15911, thanks! 👍
