### ISSUE TITLE
🐛 Bug Report: plugin-scaffolder-backend-module-sentry builds as ES module, while backend is commonjs

### ISSUE THREAD

**Issue by pmrcunha** [backstage/backstage#15916]
### 📜 Description

When installing `@backstage/plugin-scaffolder-backend-module-sentry` from NPM, when running the server it fails with `SyntaxError: Cannot use import statement outside a module`.

Only an ES build is being published, and the backend builds as commonjs. The `tsconfig.json` has `"module": "ESNext"` so it doesn't get transpiled either.

I believe this package should be built as commonjs, like other backend plugins.

### 👍 Expected behavior

The published package should be built as commonjs so that it can run in the backend server.

### 👎 Actual Behavior with Screenshots

The package is published as an ES module only.

### 👟 Reproduction steps

Follow the installation steps in the README of the package.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Aww shucks, this seemed to a slipped through the net. We've got a PR to fix this, but it won't get released until next tuesday part of the `-next` release train. Hope that's OK! :pray:

**Comment by pmrcunha** [comment]
All good, thanks a lot!
