### ISSUE TITLE
🚀 Feature: Catalog UI should consistently use metadata.title for entity hyperlinks

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#15965]
### 🔖 Feature description

The UI currently lacks consistency when rendering hyperlinks or autocomplete pickers for entities. 

**Catalog table**
Uses metadata.title for the name column, but uses metadata.name for the linked owner column

**Catalog Graph**
Consistently uses metadata.title for all entities in the catalog graph

**User overview page**
Uses metadata.name for the groups that the user is part of

**Group overview page**
Uses metadata.name for the parent and child groups

**Scaffolder OwnerPicker**

Uses metadata.name for all users / groups in the autocomplete picker

It seems like this really needs to be made consistent and should prefer metadata.title always to metadata.name. For my use case in particular, metadata.name uses uuids imported from other systems and often are not helpful at all to the end user.

### 🎤 Context

My organization imports Groups and Components into backstage from external systems. For these imported entities, the `metadata.name` is usually incomprehensible and unsearchable to an end user, often times being a UUID. These entities also have human readable display names which are set in the `metadata.title`, however these could not have been used for the `metadata.name` because they aren't unique.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hmm - I think this could require some larger refactoring here for us to use the data that we already have in place when making the query to the Catalog. For instance we don't want to enrich the `EntityLink` component directly, as it doesn't make sense to query the catalog again when we already have the data like we might do in the `CatalogTable`. It certainly should batch all these together if it's going to do it, and have some form of caching too.

Happy for some explorations on how we can do it the best through contributions however :pray:

**Comment by drodil** [comment]
Somewhat related https://github.com/backstage/backstage/issues/15987

**Comment by sennyeya** [comment]
FWIW: I've run into a similar issue with no resolution. Would love to see the title for owner links.

@benjdlambert I wonder if https://github.com/backstage/backstage/pull/16021 would start the ball rolling with this? The new `EntityStreamContext` would allow for caching and could be used to pull Group/User owner definitions. It would probably end up with more round trips to the catalog API, but that could be mitigated if we exposed another method on the `useEntityStream` hook to pull through the `by-refs` endpoint.

**Comment by Rugvip** [comment]
I think more generally some form of lightweight client-side caching is the way to get this snappy enough for it to make sense. We'd definitely want to avoid refetching the same entities for multiple table cells etc.

Caching is always hard though, so requires a bit of an investigation into how to do it safely. If we can build caching into the system then implementing this should be a quite simple followup.

**Comment by awanlin** [comment]
Feel like this is related: https://github.com/backstage/backstage/pull/17474
