### ISSUE TITLE
🐛 Bug Report: Auth Tutorial not working as described

### ISSUE THREAD

**Issue by voodooGQ** [backstage/backstage#15977]
### 📜 Description

https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md

The above tutorial was followed to implement the service-to-service authentication for Techdocs (and other libraries), and although it's working with our internal plugins, it's not working as described when it comes to Techdocs asset or event stream retrieval. 

After doing some fiddling around with the node_modules was able to determine that the authorization header gets sent "sometimes" and the cookie is forwarded consistently, however, we still receive a 401 since it can't find the authorization header.

We attempted to also add the `permissions` framework as it appears that it's a requirement of the `techdocs` item from what was displayed in the code.

Found a similar issue here https://github.com/backstage/backstage/issues/5041, but reports make it seem like the issue was fixed by using the tutorial.

### 👍 Expected behavior

The authorization header is pulled from the cookie and passed along to the services requiring it.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/1512028/214702776-9fa903a0-2582-4360-aff8-1ee29504e1ca.png)
401 errors when trying to retrieve assets

![image](https://user-images.githubusercontent.com/1512028/214702855-9124f62e-87ed-4eec-97b7-6f10c7c5d339.png) 401 from event stream

### 👟 Reproduction steps

- Install backstage
- Follow steps in this tutorial: https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md

### 📃 Provide the context for the Bug.

Our company is having a hard time moving forward with the service-to-service auth structure

### 🖥️ Your Environment

OS:   Linux 5.15.0-58-generic - linux/x64
node: v18.12.1
yarn: 1.22.19
cli:  0.22.1 (installed)
backstage:  1.10.1

Dependencies:
  @backstage/app-defaults                               1.1.0
  @backstage/backend-app-api                            0.3.1
  @backstage/backend-common                             0.18.1
  @backstage/backend-plugin-api                         0.3.1
  @backstage/backend-tasks                              0.4.2
  @backstage/catalog-client                             0.9.0, 1.3.0
  @backstage/catalog-model                              0.13.0, 1.1.5
  @backstage/cli-common                                 0.1.11
  @backstage/cli                                        0.22.1
  @backstage/config-loader                              1.1.8
  @backstage/config                                     0.1.15, 1.0.6
  @backstage/core-api                                   0.2.23
  @backstage/core-app-api                               1.4.0
  @backstage/core-components                            0.11.2, 0.12.3, 0.9.5
  @backstage/core-plugin-api                            0.1.13, 0.8.0, 1.3.0
  @backstage/core                                       0.7.14
  @backstage/dev-utils                                  1.0.11
  @backstage/errors                                     0.1.5, 0.2.2, 1.1.4
  @backstage/integration-aws-node                       0.1.1
  @backstage/integration-react                          0.1.25, 1.1.9
  @backstage/integration                                0.8.0, 1.4.2
  @backstage/plugin-analytics-module-ga                 0.1.25
  @backstage/plugin-api-docs                            0.8.14
  @backstage/plugin-app-backend                         0.3.41
  @backstage/plugin-auth-backend                        0.17.4
  @backstage/plugin-auth-node                           0.2.10
  @backstage/plugin-catalog-backend-module-github       0.2.4
  @backstage/plugin-catalog-backend                     1.7.1
  @backstage/plugin-catalog-common                      1.0.10
  @backstage/plugin-catalog-graph                       0.2.26
  @backstage/plugin-catalog-import                      0.9.4
  @backstage/plugin-catalog-node                        1.3.2
  @backstage/plugin-catalog-react                       0.9.0, 1.2.4
  @backstage/plugin-catalog                             1.7.2
  @backstage/plugin-events-node                         0.2.2
  @backstage/plugin-github-actions                      0.5.14
  @backstage/plugin-github-issues                       0.2.3
  @backstage/plugin-home                                0.4.30
  @backstage/plugin-org                                 0.6.4
  @backstage/plugin-permission-common                   0.5.3, 0.6.4, 0.7.3
  @backstage/plugin-permission-node                     0.7.4
  @backstage/plugin-permission-react                    0.3.4, 0.4.9
  @backstage/plugin-proxy-backend                       0.2.35
  @backstage/plugin-scaffolder-backend                  1.10.1
  @backstage/plugin-scaffolder-common                   1.2.4
  @backstage/plugin-scaffolder-react                    1.0.1
  @backstage/plugin-scaffolder                          1.10.1
  @backstage/plugin-search-backend-module-elasticsearch 1.1.2
  @backstage/plugin-search-backend-module-pg            0.5.2
  @backstage/plugin-search-backend-node                 1.1.2
  @backstage/plugin-search-backend                      1.2.2
  @backstage/plugin-search-common                       0.3.4, 1.2.1
  @backstage/plugin-search-react                        1.4.0
  @backstage/plugin-search                              1.0.7
  @backstage/plugin-shortcuts                           0.3.6
  @backstage/plugin-stack-overflow                      0.1.10
  @backstage/plugin-tech-radar                          0.6.0
  @backstage/plugin-techdocs-addons-test-utils          1.0.9
  @backstage/plugin-techdocs-backend                    1.5.2
  @backstage/plugin-techdocs-module-addons-contrib      1.0.9
  @backstage/plugin-techdocs-node                       1.4.5
  @backstage/plugin-techdocs-react                      1.1.2
  @backstage/plugin-techdocs                            1.4.3
  @backstage/plugin-user-settings                       0.6.2
  @backstage/release-manifests                          0.0.8
  @backstage/search-common                              0.3.4
  @backstage/test-utils                                 1.2.4
  @backstage/theme                                      0.2.16
  @backstage/types                                      0.1.3, 1.0.2
  @backstage/version-bridge                             0.1.2, 1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by voodooGQ** [comment]
This is causing us some major issues in our business, any chance someone can take a peek?

**Comment by rdgb** [comment]
I am encountering the same problem. It did not happen a few months ago, it seems to have been an issue introduced since updating backstage recently.

**Comment by Rugvip** [comment]
Ping @Pike, @erikxiv, @jh-sh, @hillmandj as contributors to this tutorial

**Comment by erikxiv** [comment]
👋 It was a while ago I looked at this but the original implementation still seems to work for me (we're running Backstage 1.9.1 at the moment).

> it's working with our internal plugins, it's not working as described when it comes to Techdocs asset or event stream retrieval.

This suggests to me that there is an issue with the cookie. Most client plugins send an authorization header with any API request, and it sounds as if this still works. Techdocs assets (and the Scaffolder event stream) is a bit different, as these asset requests are sent by the browser in response to other protocols, e.g. when Techdocs loads a HTML document the browser tries to load the related javascript/css assets - without Backstage being involved and able to inject the Authorization header. This is the cookie trick in the guide, where the client regularly pings the backend to set a token cookie that gets forwarded on asset and event stream requests.

Could you double-check if this cookie is set on your browser, and maybe specifically on which domain it is set? I'm wondering if there could be some discrepancy there causing this to fail:
* When running locally, the client and api can run on different ports/domains. This might cause the cookie to be set on one, but not the other
* Is the techdocs / scaffolder api being served on a different domain? E.g. a domain where the cookie is not forwarded?

The cookie is simply called `token` and should contain a JWT token.

**Comment by Pike** [comment]
I also had a look. For us, it still works on 1.10.1. I cross-checked the history of the files in our repo, and all the relevant changes are upstreamed to the doc.

On the original problem description, it should be OK for the authorization header to be missing, that's what the fallback to the cookie in

```ts
      const token =
        getBearerTokenFromAuthorizationHeader(req.headers.authorization) ||
        (req.cookies?.token as string | undefined);
```

is for.

The other small difference I noticed is that we're still running on node 16, and you seem to be on node 18?

**Comment by voodooGQ** [comment]
@erikxiv thanks for your reply. We are running the local on different ports, however, this problem is happening on our production instance as well which does not. When we checked last the cookie was being set (and seemed to be appropriate) and being passed along, but there was nowhere that the cookie was being picked up. Maybe my scaffolder plugins our out of date?

@Pike thanks for your reply alos. Yup, we're running 18 currently. I'll try seeing if this works with 16

I should be able to dig into this a bit tomorrow to test the theories. I'll reply back with my findings.

**Comment by voodooGQ** [comment]
@erikxiv  @Pike  Tried on 16 & 18 with the same results. Here's the code where I have the `authMiddleware` set on the routes in packages/backend/src/index.ts:

```typescript
 apiRouter.use("/scaffolder", authMiddleware, await scaffolder(scaffolderEnv));
  apiRouter.use("/techdocs", authMiddleware, await techdocs(techdocsEnv));
```

Here's the 401 I'm receiving in Techdocs:

![image](https://user-images.githubusercontent.com/1512028/218616946-5d73c673-67b5-46a5-840a-63e3f7e66d82.png)

And as you can see, the cookie is being set with the token:

![image](https://user-images.githubusercontent.com/1512028/218617313-ecb09532-5357-4338-96b3-5fa6f81fdaa8.png)

I don't know a lot about cookie auth, but from what I can tell with my Googling this looks like a valid cookie. As mentioned in the initial comment, I had done some debugging with the `@backstage/plugin-scaffolder-backend` plugin in node modules and was getting results where sometimes the auth header was available, and other times it was not. I'll try to recreate that scenario and get you the relevant data that I find.

Appreciate the help.

**Comment by Pike** [comment]
The only thing that should be sending 401 responses is the auth middleware. What's making it to the actual plugins won't care about the cookie anymore, that's taken care of in 

```ts
      if (!req.headers.authorization) {
        // Authorization header may be forwarded by plugin requests
        req.headers.authorization = `Bearer ${token}`;
      }
```

One thing I noticed is that the request above was the port 7025, is that the normal port for your backend? Not that you're asking the wrong thing on your machine to serve those.

Another data point, if the user doesn't have access to the entity that's documented, the error should be a 404, and not a 401, if I read the code right. Just to back up that this should be solely inside the middleware.

**Comment by voodooGQ** [comment]
@Pike yes, sorry I may have misworded my previous items, but what I'm suggesting is that when I actually made it to the plugin sometimes the Authorization header wasn't being set. There would be times when I could see it for one invocation, but then other invocations would have it missing. This leads me to believe we're losing the Authorization header somewhere along the line and the authMiddleware/cookie is doing its job, something else is blocking it. This is just a theory based on the research I did, but to be honest I don't even remember where I set the console.logs in before to debug, so it may be a lost cause.

Yes, our backend port is 7025 on local instances, but 7000 on production.

At the moment we don't have the permissions framework setup (though I do remember seeing something in the code when digging that suggests it may be an undocumented requirement for Techdocs).

**Comment by voodooGQ** [comment]
I'm using `"express": "^4.17.1"` across the board for my backend and plugins, just in case that does end up being the difference.

**Comment by Pike** [comment]
Do you have the `cookie-parser` middleware set up?

```ts
  const apiRouter = Router();
  apiRouter.use(cookieParser());
```

**Comment by voodooGQ** [comment]
@Pike Nope, I can look into setting it up if that's a requirement. Did I miss that in the tutorial somewhere? Seems a lot better than my solution, but had no idea it was an option.

Regardless, it's odd because every other endpoint works as expected with the `authMiddleware` even without the `cookieParser()` middleware. It's just the Events Stream and Techdocs asset downloads that seem to be affected.

**Comment by Pike** [comment]
Yep, it's in https://github.com/backstage/backstage/blob/2cc2155bcf823145d6ce910b228eda2d5c1daf50/contrib/docs/tutorials/authenticate-api-requests.md#L98

That could probably be highlighted a bit in the doc.

Erik commented on why the API requests work, they set up the auth header directly.

**Comment by voodooGQ** [comment]
Ahhh yes, I assumed that was standard boiler from the file, didn't even bother to look at it. Yeah I think a small comment above it just stating that it's a middleware that needs to be integrated would be enough to avoid this with future devs.

**Comment by voodooGQ** [comment]
Replaced my home-rolled parser with the official express `cookie-parser`, integrated, and all is working as expected :D.

Thanks a lot for both of your help @erikxiv and @Pike, and thanks for pulling them into the fray @Rugvip!

I still suggest adding a note, I'm happy to create a PR for that if you'd like. Otherwise I'm going to call this closed!
