### ISSUE TITLE
🚀 Feature: Fetch GraphQL Schema under the authentication with kind: API.

### ISSUE THREAD

**Issue by riginoommen** [backstage/backstage#15976]
### 🔖 Feature description

Support for 

- authentication for schema pulling with the specs

### 🎤 Context

building an api catalog with the graphql endpoints

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
👋  hey! Think I need a little more information here - is this when you're processing the Entity and loading in the `.graphql` schema and need authentication server side, or is this when you want to do introspection and need the authentication on the frontend in the plugin?

**Comment by riginoommen** [comment]
I ment the first one 

```processing the Entity and loading in the .graphql schema from a authenticated endpoint```

**Comment by riginoommen** [comment]
Message which throws like this
```{"error":{"name":"InputError","message":"InputError: Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location https://company.com/api/graphql, Error: could not read https://company.com/api/graphql, 400 Bad Request","stack":"InputError: InputError: Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location https://company.com/api/graphql, Error: could not read https://company.com/api/graphql, 400 Bad Request\n at DefaultLocationService.processEntities (/Users/roommen/Work/dx-backstage/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:2188:15)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at async DefaultLocationService.dryRunCreateLocation (/Users/roommen/Work/dx-backstage/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:2219:22)\n at async /Users/roommen/Work/dx-backstage/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:3512:22"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}```

**Comment by riginoommen** [comment]
Graphql endpoint has the authentication

**Comment by benjdlambert** [comment]
Hey :wave: sorry this kind of slipped through the net a little bit here.

So what I think is the best option here is to create your own `URLReader` implementation which gets passed to the `createRouter` method of the catalog in `packages/backend/plugins/catalog.ts` which then would be used in the `YAMLPlaceholderProcessor`

I think that you will need to implement `readUrl` which would get called with your `graphql` endpoint, and you are then responsible for returning the data from that URL, and you can add your own authentication there and then delegate back to the original implementation when the URL does not match your GraphQL endpoint.

**Comment by riginoommen** [comment]
> 

Thanks, i will try this out. But I request to provide this feature to the API Kind in a native way because in terms of graphql I see most of the schemas are behind the authentication.

With this suggestion I like to know any active example which I can refer for the custom ```URLReader``` implementation and some resources which I can look to

**Comment by freben** [comment]
There's not really any examples of a custom ´UrlReader´ I think. What you can do is to look at what the default does, which [is here](https://github.com/backstage/backstage/blob/cc08d60324668ea6c029907d3baf9da50f260849/packages/backend-common/src/reading/UrlReaders.ts#L81). Note that there's a `create` static method that you can use to pick the exact ones that should be added, instead of the standard list. And then you can study the individual factories [such as the GitHub one](https://github.com/backstage/backstage/blob/cc08d60324668ea6c029907d3baf9da50f260849/packages/backend-common/src/reading/GithubUrlReader.ts#L60) for example.

**Comment by riginoommen** [comment]
> There's not really any examples of a custom ´UrlReader´ I think. What you can do is to look at what the default does, which [is here](https://github.com/backstage/backstage/blob/cc08d60324668ea6c029907d3baf9da50f260849/packages/backend-common/src/reading/UrlReaders.ts#L81). Note that there's a `create` static method that you can use to pick the exact ones that should be added, instead of the standard list. And then you can study the individual factories [such as the GitHub one](https://github.com/backstage/backstage/blob/cc08d60324668ea6c029907d3baf9da50f260849/packages/backend-common/src/reading/GithubUrlReader.ts#L60) for example.

I have tried this not working as expected

**Comment by riginoommen** [comment]
Any update on this issue to provide introspection support to authenticated endpoint

**Comment by benjdlambert** [comment]
> I have tried this not working as expected

What do you mean by this? What happened when you tried to do this? What was your approach? 

Using a custom processor or URLReader for this should help you get access to the protected endpoint.
