### ISSUE TITLE
🐛 Bug Report: Star filter slow

### ISSUE THREAD

**Issue by weiyilang123** [backstage/backstage#15978]
### 📜 Description

We have over 2000 application entities, then when click on Star filter, the site freeze for long time then successfully display filtered started list of entities, just wondering if there are anything can do to improve the performance?

### 👍 Expected behavior

Click on the star filter, should not freeze the site, if it does need to take a while, then show some progress indicators.

### 👎 Actual Behavior with Screenshots

Click on Star filter, the site freeze for long time

### 👟 Reproduction steps

Have more then 2000 entities, then star couple entities, then click on the star filter

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
This is free for someone to do some investigation as to where the slowness is :pray:

**Comment by Depado** [comment]
Hey,
Curious if you ever found a solution for this. I'm facing a similar situation with other filters.
