### ISSUE TITLE
🚀 Feature: Confluence to MkDocs Scaffolder workflow

### ISSUE THREAD

**Issue by tradcliffe-expediagroup** [backstage/backstage#15979]
### 🔖 Feature description

This feature would take a confluence doc and convert it to a markdown file. This file would then be added to a GitHub repo that is set up for Techdocs. It would add the new markdown file along with updating the mkdocs.yml file to include the new md file in the nav. 

### 🎤 Context

In my use case, we have a lot of documentation in Confluence at my company and we are trying to increase Techdocs adoption. Creating a simple converter via scaffolder would help migrate docs to Techdocs easily, quickly and drive adoption. We are currently building this internally and wanted to contribute it back if open source was interested. 

### ✌️ Possible Implementation

Our feature is not fully built out yet but we are grabbing docs from Confluence(specifically the html version of confluence), using a html to markdown converter to create the markdown file and pushing it to a GitHub repo. We are doing with via scaffolder, asking the users to input a confluence repo, a GitHub repo and asking if the GitHub repo is onboarded onto TechDocs. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
This could be a useful action as the scaffolder already knows how to create repositories and pull requests. One thing I would say though, I would only put things in the scaffolder that are intended to be used multiple times rather than just single one-shot scripts that migrate a lot of things. Is this the former or the latter? Maybe something you can give a list of confluence pages to and it can create some markdown docs for you?

**Comment by tradcliffe-expediagroup** [comment]
HI. We are building this action and workflow to be used multiple times. Adoption of Techdocs within EG is still an ongoing process, with docs both in Confluence and Backstage. So even a team that has some docs in Backstage, they are still creating docs in Confluence that may need to be migrated at a later date. And also our design is to update one repo at a time with the action/workflow. So each team would need to use the workflow as many times as they have repos worth of docs on confluence. 
The idea/design behind the action itself is to give the action a confluence link(or multiple links) and a GitHub link, get the confluence page(s), convert to markdown and add them to the repo in `ctx.workspace` while follow up actions in the workflow publish and merge the new md files to the given GitHub link.

**Comment by benjdlambert** [comment]
@tradcliffe-expediagroup ah ok, seems resonable, go ahead! :)

**Comment by tradcliffe-expediagroup** [comment]
Great. I will get started soon on this. Thanks.

**Comment by taras** [comment]
@tradcliffe-expediagroup using Scaffolder to convert Confluence pages to Techdocs is an excellent idea.

**Comment by tradcliffe-expediagroup** [comment]
Here is the PR for this issue: https://github.com/backstage/backstage/pull/16820

Please let me know what you think and if I am missing anything. Thanks

**Comment by tradcliffe-expediagroup** [comment]
PR above has been merged. I will move this to done/closed
