### ISSUE TITLE
🐛 Bug Report: OwnerPicker does not work with default user

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#15988]
### 📜 Description

In OwnerPicker it's not possible to set the current user as default value

### 👍 Expected behavior

Default value of current user can be set

### 👎 Actual Behavior with Screenshots

Default value is shown as string `${{ user.entity }}`

### 👟 Reproduction steps

Create software template with following input

```yaml
owner:
  title: Owner of the component
  type: string
  default: ${{ user.entity }}
  ui:field: OwnerPicker
  ui:options:
    catalogFilter:
      kind: [ User ]
```

### 📃 Provide the context for the Bug.

Many times people want to set themselves as the owner. Due to this bug, they cannot and they have to select themselves from the list.

### 🖥️ Your Environment

OS:   Darwin 22.1.0 - darwin/arm64
node: v16.19.0
yarn: 1.22.19
cli:  0.22.1 (installed)
backstage:  1.10.0

Dependencies:
  @backstage/app-defaults                                   1.1.0
  @backstage/backend-app-api                                0.3.0
  @backstage/backend-common                                 0.17.0, 0.18.0
  @backstage/backend-plugin-api                             0.3.0
  @backstage/backend-tasks                                  0.4.1
  @backstage/backend-test-utils                             0.1.32
  @backstage/catalog-client                                 1.3.0
  @backstage/catalog-model                                  1.1.5
  @backstage/cli-common                                     0.1.11
  @backstage/cli                                            0.22.1
  @backstage/config-loader                                  1.1.8
  @backstage/config                                         1.0.6
  @backstage/core-app-api                                   1.4.0
  @backstage/core-components                                0.11.2, 0.12.3
  @backstage/core-plugin-api                                1.3.0
  @backstage/dev-utils                                      1.0.11
  @backstage/errors                                         1.1.4
  @backstage/integration-aws-node                           0.1.1
  @backstage/integration-react                              1.1.9
  @backstage/integration                                    1.4.2
  @backstage/plugin-api-docs                                0.8.14
  @backstage/plugin-app-backend                             0.3.40
  @backstage/plugin-auth-backend                            0.17.3
  @backstage/plugin-auth-node                               0.2.9
  @backstage/plugin-catalog-backend-module-bitbucket-server 0.1.5
  @backstage/plugin-catalog-backend-module-msgraph          0.4.6
  @backstage/plugin-catalog-backend                         1.7.0
  @backstage/plugin-catalog-common                          1.0.10
  @backstage/plugin-catalog-graph                           0.2.26
  @backstage/plugin-catalog-import                          0.9.4
  @backstage/plugin-catalog-node                            1.3.1
  @backstage/plugin-catalog-react                           1.2.4
  @backstage/plugin-catalog                                 1.7.2
  @backstage/plugin-github-actions                          0.5.14
  @backstage/plugin-jenkins-backend                         0.1.30
  @backstage/plugin-jenkins-common                          0.1.12
  @backstage/plugin-jenkins                                 0.7.13
  @backstage/plugin-org                                     0.6.4
  @backstage/plugin-permission-common                       0.7.3
  @backstage/plugin-permission-node                         0.7.3
  @backstage/plugin-permission-react                        0.4.9
  @backstage/plugin-proxy-backend                           0.2.34
  @backstage/plugin-scaffolder-backend                      1.10.0
  @backstage/plugin-scaffolder-common                       1.2.4
  @backstage/plugin-scaffolder-react                        1.0.0
  @backstage/plugin-scaffolder                              1.10.0
  @backstage/plugin-search-backend-module-elasticsearch     1.1.1
  @backstage/plugin-search-backend-module-pg                0.5.1
  @backstage/plugin-search-backend-node                     1.1.1
  @backstage/plugin-search-backend                          1.2.1
  @backstage/plugin-search-common                           1.2.1
  @backstage/plugin-search-react                            1.4.0
  @backstage/plugin-search                                  1.0.7
  @backstage/plugin-sonarqube-react                         0.1.1
  @backstage/plugin-sonarqube                               0.6.2
  @backstage/plugin-techdocs-backend                        1.5.1
  @backstage/plugin-techdocs-module-addons-contrib          1.0.9
  @backstage/plugin-techdocs-node                           1.4.4
  @backstage/plugin-techdocs-react                          1.1.2
  @backstage/plugin-techdocs                                1.4.3
  @backstage/plugin-user-settings                           0.6.2
  @backstage/release-manifests                              0.0.8
  @backstage/test-utils                                     1.2.4
  @backstage/theme                                          0.2.16
  @backstage/types                                          1.0.2
  @backstage/version-bridge                                 1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Templating is not available in the `parameters` section of the manifest, however there is an upcoming RFC about this.

Maybe we can add this as a `ui:option` / `prop` to the `OwnerPicker` that you can `defaultToSignedInUser` or something like that?

**Comment by drodil** [comment]
The option could work for me until parameters are available!

**Comment by benjdlambert** [comment]
Actually wonder if we should just implement this and have it as default.

We should use the `identityApi` to grab the claims and put a the `groups` that you belong to first, then your own user, and then rest of the groups or something and default it to the first one if there is no default value provided.

Thinking that it's better for ownership if it's a group rather than a person, as people disappear more often that groups so at least theres some accountability to creating components :)

**Comment by benjdlambert** [comment]
The RFC is WIP right now from the folks over at frontside. Coming soon - more info to follow

**Comment by drodil** [comment]
Not stale, waiting for more info @benjdlambert :)
