### ISSUE TITLE
Profile framework that allows to map CRs to the proper K8s cluster

### ISSUE THREAD

**Issue by waldirmontoya25** [backstage/backstage#15994]
### 🔖 Feature description

Implement a "profile" framework that allows mapping CRs to the proper K8s cluster

### 🎤 Context

A typical pattern in Kubernetes clusters is to have clusters for different purposes. Currently, the Kubernetes backend plugin allows to specify CRs at an individual level, but there is no notion of grouping.

### ✌️ Possible Implementation

We would like to introduce a Introduce a first-class notion of "profile" (or "archetype" as it has been [discussed in the past](https://github.com/backstage/backstage/issues/12095))

kubernetes: 
  customResourceProfiles: 
    build: 
      - group: 'argoproj.io'
        apiVersion: 'v1alpha1'
        plural: 'rollouts'
    run: 
     - # knative, other CRDs that appear on run clusters, etc
# ...
  clusterLocatorMethods: 
  - type: config
    clusters: 
      - name: build
        customResourceProfile: build

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by waldirmontoya25** [comment]
Updating the status: We'll start working on this next week.

**Comment by RubenV-dev** [comment]
Currently working out a solution for this.

**Comment by waldirmontoya25** [comment]
Closing the issue given the following comment:

https://github.com/backstage/backstage/pull/17411#discussion_r1184914112
