### ISSUE TITLE
🚀 Feature: scope Gitlab Org Data integration to a single group

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#16025]
### 🔖 Feature description

The `group` field for a `GitlabProviderConfig` is described as

https://github.com/backstage/backstage/blob/e9e5da25b832d2bbfaaadb2e73ec2ea6a8e1edb9/plugins/catalog-backend-module-gitlab/config.d.ts#L32-L36

and

https://github.com/backstage/backstage/blob/e9e5da25b832d2bbfaaadb2e73ec2ea6a8e1edb9/docs/integrations/gitlab/discovery.md?plain=1#L25

This is consistent with the behaviour of the `GitlabDiscoveryEntityProvider`, which uses the parameter to filter projects:

https://github.com/backstage/backstage/blob/e9e5da25b832d2bbfaaadb2e73ec2ea6a8e1edb9/plugins/catalog-backend-module-gitlab/src/providers/GitlabDiscoveryEntityProvider.ts#L155-L162

Since the `GitlabOrgDiscoveryEntityProvider` also consumes a `GitlabProviderConfig`, it could interpret the same parameter in a corresponding fashion regarding groups and users:
* the only groups ingested are the referenced group itself and its descendants.
* the only users ingested are direct members of the referenced group or its descendants.

### 🎤 Context

Narrowing the set of users and groups to ingest is helpful when your organization is using a GitLab instance shared with other software projects that are not tracked in Backstage. Also, if your GitLab instance contains a lot of data, it can be helpful to narrow the scope of ingestion to get faster feedback while testing and iterating on your provider config.

### ✌️ Possible Implementation

In #16023 I mention a GraphQL query that can fetch a group and its descendant groups, as well as direct memberships at each level of the hierarchy. That's a pretty good fit for this issue too!

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Thanks for creating this and #16023. Think they both seem reasonable! :pray:

**Comment by sbarrypoppulo** [comment]
Still needs to be implemented

**Comment by cthtrifork** [comment]
Anyone up for this? Right now we are using the public gitlab.com and backstage tries to list/discover all users which are hundreds of thousands..

**Comment by sbarrypoppulo** [comment]
My team is currently working on this. Hoping to have some changes to review and collect feedback in the coming days

**Comment by matteosilv** [comment]
Hi, just wanted to comment that this stuff is risky as in GitLab self-hosted it's reasonable that you want all users (of the whole instance) but just a subgroup for teams, and that's why I worked on a merged MR in the past to allow fetch only subgroups of a specific group:

            group: org/teams # Optional. Must not end with slash. Accepts only groups under the provided path (which will be stripped)

Instead in the SaaS instance you still want the second option as your teams description will definitely be under some subgroup, but you only want the user that are member of your root level group, so we should probably add an option that tell us which is the root level group.

**Comment by matteosilv** [comment]
@sbarrypoppulo if you need help I'd be happy to work with you on this

**Comment by sbarrypoppulo** [comment]
@matteosilv Yes, having to support slightly different logic for Self-Managed GitLab and GitLab.com is a bit of a challenge. We've handled this in our implementation like so:

- For GitLab Self-Managed: Continue to use the `/users` and `/groups` endpoints (`group` parameter is optional)
- For GitLab.com: Use GraphQL queries to fetch group and it's descendant groups and fetch the direct members of the groups (`group` is required for GitLab.com)

We're fairly close to opening a PR for review, so would appreciate any feedback and testing of the proposed changes! Our solution is potentially geared towards our Orgs particular group and membership structure, but will hopefully provide something that can be built upon.

**Comment by matteosilv** [comment]
For example with your current implementation you seem to be breaking the assumption I made with my MR:

In my case I have my root level group that is `my-company` and my teams are under the subgroup `my-company/teams`, so when I list user I'd like them t be listed under the root level group and not under `my-company/teams`, so I think we should change this line:

      users = (await client.listSaasUsers(this.config.group)).items;
      
and pass the root level group, stripping out any subgroup.

What do you think?

**Comment by matteosilv** [comment]
I commented in your fork. I can help and test it on my instance if needed

**Comment by vinzscam** [comment]
Closing this as resolved by #18889
