### ISSUE TITLE
🐛 Bug Report: Running 'npx @backstage/create-app@latest' fails

### ISSUE THREAD

**Issue by weyert** [backstage/backstage#16028]
### 📜 Description

I am trying to start fresh with Backstage and followed the Getting Started but it's failing when running the command `npx @backstage/create-app@latest`.

```bash
[etc]
➤ YN0013: │ mini-css-extract-plugin@npm:2.7.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ minimalistic-assert@npm:1.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ minimalistic-crypto-utils@npm:1.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ minimatch@npm:3.1.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ minimatch@npm:5.1.6 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ minimalistic-assert@npm:1.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ minimalistic-crypto-utils@npm:1.0.1 can't be found in the cache and will be fetched from the remote registry
  executing     yarn install ✖

Error: Could not execute command yarn install

It seems that something went wrong when creating the app 🤔

🔥  Failed to create app!
```

### 👍 Expected behavior

Able to successfully install `backstage`

### 👎 Actual Behavior with Screenshots

See above the `yarn install` is failing for some reason but unclear why

### 👟 Reproduction steps

1. Open Terminal
2. Create a new directory `temporary`
3. `cd temporary`
4. Install yarn `npm install -g yarn`
5. Check yarn successfully installed by running `yarn --version` this returns something similar to `3.2.1`
6. Run the command `npx @backstage/create-app@latest`
7. Notice the error fails with the error above

### 🖥️ Your Environment

Fails to run but based on `info.ts` in the repo you want this:

Operation System: macOS Monterey 12.6.2 (21G320)
Model: MacBook Pro (14-inch, 2021) (Apple Sillicon)
Yarn:  3.2.1
Node: v18.3.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Created #16039 to address this. We don't support Yarn 3 in create-app yet, and we don't really want to encourage creation of Yarn 3 repos yet either. The actual error you're seeing is that an `exec` call is hitting the max output buffer limit, but fixing that there's more stuff like setting config to ensure that the node linker is used, and we'd also need separate templating of the Dockerfile.

**Comment by awanlin** [comment]
Thanks @Rugvip!

@weyert with this working for you know and the change mentioned above do you think this can be closed?

Related Discord thread: https://discord.com/channels/687207715902193673/1069005093464191057

**Comment by weyert** [comment]
> Created #16039 to address this. We don't support Yarn 3 in create-app yet, and we don't really want to encourage creation of Yarn 3 repos yet either. The actual error you're seeing is that an `exec` call is hitting the max output buffer limit, but fixing that there's more stuff like setting config to ensure that the node linker is used, and we'd also need separate templating of the Dockerfile.

Yeah, I personally don't use Yarn only `Pnpm` and `npm` so it was a struggle to get it working. I find the Yarn version stuff pretty confusing. @awanlin suggested I could run a command to set the version to `classic`. Maybe it's work mentioned that as part of the version check.
