### ISSUE TITLE
🚀 Feature: Set ReadOnly for AzureSites Component to protect start & stop action

### ISSUE THREAD

**Issue by deepan10** [backstage/backstage#16035]
### 🔖 Feature description

The `AzureSites` has start/stop action for all users who are owner/had access to `AzureSite` component, which leads anyone can perform start/stop. 

To protect this we can set read-only `AzureSites` component.

### 🎤 Context

To protect unwanted start/stop action of Azure Site on `AzureSite` plugin. The Backstage Portal developer can set read-only access to all team members.

### ✌️ Possible Implementation

Create an optional flag(readOnly) on the `AzureSitesOverview`. Then we can use the flag on the `EntityAzureSitesOverviewWidget`
Example:
```
<EntityAzureSitesOverviewWidget  readOnly />
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
This seems reasonable, there could be scope to include some of the permissions framework here, but maybe that's a followup ticket instead. Is this something that you want to contribute?

**Comment by deepan10** [comment]
Yes, I can. Plugin permission is more suitable, I will submit the PR once I am done with the implementation.

**Comment by deepan10** [comment]
@benjdlambert @vinzscam 
Can we re-open this?
