### ISSUE TITLE
🚀 Feature: reusable kubernetes-backend proxy client

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#16065]
### 🔖 Feature description

Extend the [`KubernetesApi` interface](https://github.com/backstage/backstage/blob/0fcedaa881f6e8713c6862c78ce464f4420abc31/plugins/kubernetes/src/api/types.ts#L29-L46) with something super [`fetch`-like](https://github.com/microsoft/TypeScript/blob/39a9ac84fdf307e7b36bbb889d2faba74b46126d/lib/lib.dom.d.ts#L1589-L1616):

```typescript
export interface KubernetesApi {
  // ... existing methods
  proxy(
    clusterName: string,
    path: string,
    init?: RequestInit,
  ): Promise<Response>;
}
```

### 🎤 Context

Consuming the proxy endpoint currently requires some knowledge of the spec (usage of the `X-Kubernetes-Cluster` header), and there is some boilerplate around negotiating tokens that could be extracted into library code to make life easier for contributors. You can see the weight of this in the snippet in #16046.

This change would allow that snippet to be replaced with some pretty slick plugin code like

```typescript
const kubernetesApi = useApi(kubernetesApiRef);
await kubernetesApi.proxy(CLUSTER_NAME, '/api/v1/namespaces');
```

### ✌️ Possible Implementation

Modify [`KubernetesBackendClient`](https://github.com/backstage/backstage/blob/master/plugins/kubernetes/src/api/KubernetesBackendClient.ts) as follows (this is written off the top of my head with no guarantee it even compiles) --
```typescript
export class KubernetesBackendClient implements KubernetesApi {
  // new member variable
  private readonly kubernetesAuthProvidersApi: KubernetesAuthProvidersApi;
  // ... existing code
  async proxy(
    clusterName: string,
    path: string,
    init?: RequestInit,
  ): Promise<Response> {
    const { authProvider } = await this.getCluster(clusterName);
    const token = await this.getBearerToken(authProvider);
    const url = `${
      await this.discoveryApi.getBaseUrl('kubernetes')
    }/proxy${path}`;
    
    const headers = {
      ['X-Kubernetes-Cluster']: clusterName,
      Authorization: `Bearer ${token}`,
      ...init?.headers,
    };
    return fetch(url, {headers, ...init});
  }

  private async getCluster(clusterName: string): Promise<{ name: string; authProvider: string }> {
    const clusters = await this.getClusters(); // could memoize
    return clusters.find(c => c.name === clusterName);
  }

  private async getBearerToken(
    authProvider: keyof KubernetesRequestAuth,
  ): Promise<string> {
    // abuse of the KubernetesAuthProvidersApi interface --
    // would be better if there was an interface that just got
    // tokens independent of the logic to embed those tokens
    // in a request body
    const { auth } = await this.kubernetesAuthProvidersApi
      .decorateRequestBodyForAuth(
        authProvider,
        {
          entity: {
            apiVersion: 'v1',
            kind: 'Placeholder',
            metadata: {name: 'placeholder'},
          },
        },
      );
    return auth[authProvider];
  }
}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Makes a lot of sense! @mclarke47 for viz

**Comment by mclarke47** [comment]
lgtm

**Comment by jamieklassen** [comment]
With #16237 merged, let's take the time to make this client library "permissions-compatible" -- I'd revise the last few lines of the `proxy` implementation sketched above to ensure that the request to the proxy endpoint includes:

* a k8s token in the `Backstage-Kubernetes-Authorization` header
* a Backstage token in the `Authorization` header

in the same manner as the [new-and-improved snippet](https://github.com/backstage/backstage/blob/b9fa372c840326ca39bcbe48fbe0817dd8e8aae3/docs/features/kubernetes/proxy.md?plain=1#L47-L51) in the docs. I imagine something like:

```typescript
  async proxy(
    clusterName: string,
    path: string,
    init?: RequestInit,
  ): Promise<Response> {
    // ... start of method as above
    const { token: idToken }  = await this.identityApi.getCredentials();
    const headers = {
      ['Backstage-Kubernetes-Cluster']: clusterName,
      ['Backstage-Kubernetes-Authorization']: `Bearer ${token}`,
      Authorization: `Bearer ${idToken}`,
      ...init?.headers,
    };
    return fetch(url, {headers, ...init});
  }
```

**Comment by RubenV-dev** [comment]
Currently on my agenda of tasks to tackle. Have some unit tests and an implementation ready but am working through covering edge cases we might encounter when using the client. Also backfilled missing unit tests which will be a part of the PR that I make. Just an update incase anyone is following this issue here.
