### ISSUE TITLE
🐛 Bug Report: cli `repo lint` commands do not catch errors in monorepo rules

### ISSUE THREAD

**Issue by mtlewis** [backstage/backstage#16074]
### 📜 Description

When running `backstage-cli repo lint` (e.g. via the `lint` script in the root of this repository), linting errors for monorepo rules are not reported.

### 👍 Expected behavior

When linting errors exist in the code, they should consistently be reported by `repo lint`.

### 👎 Actual Behavior with Screenshots

Right now, running `repo lint` misses monorepo errors. Based on the repro steps below, I suspect this could be down to `repo lint` running `eslint` from inside each package in the monorepo - it looks like monorepo rules only work when eslint is run from the root of the monorepo.

### 👟 Reproduction steps

1. Update `packages/core-app-api/src/plugins/collectors.ts`, replacing line 17 with:

   ```ts
   import { BackstagePlugin } from '@backstage/core-plugin-api';
   import { getComponentData } from '@backstage/core-plugin-api/src/extensions/componentData';
   ```

2. Run `yarn lint` from the package root. Note no errors occur.
3. Run `./node_modules/.bin/eslint ./packages/core-app-api` to run eslint directly from the repo root. Note the error being caught, as expected.
4. Change to the `packages/core-app-api` directory.
5. Run `../../node_modules/.bin/eslint .`. Note again the missing error.

### 📃 Provide the context for the Bug.

Noticed that we were missing lint errors in a separate Backstage plugin monorepo.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
I'm actually working on some new [custom lint rule](https://github.com/backstage/backstage/pull/15816/files#diff-0f09d6ea557ace55164950bb51e3bf4c5a6793648d1e377d43df315adf31d2ea)s as part of #15816, since as far as I can tell the rule we want doesn't exist en the ESLint ecosystem.

**Comment by Rugvip** [comment]
Oh and to add a bit more context, the reason for the error you're reporting is that it's [hardcoded into the monorepo lint rule](https://github.com/azz/eslint-plugin-monorepo/blob/266bd60511b4441074a7ad09d6aed1fb3b164d46/src/rules/no-internal-import.js#L30) to use `process.cwd()` to scan for monorepo packages, which only works from the root. There are other things we need from that rule though so ended up with a custom one.
