### ISSUE TITLE
🐛 Bug Report: clicking outside of search modal does not close search modal

### ISSUE THREAD

**Issue by diggyk** [backstage/backstage#16089]
### 📜 Description

When the search modal is opened via the sidebar, clicking outside of the search modal does not close it. The search modal cannot be closed until an item is selected from the search results.

### 👍 Expected behavior

When clicking outside of the search modal (or clicking on a close button, to be added), the search modal should be closed.

### 👎 Actual Behavior with Screenshots

![backstagesearch](https://user-images.githubusercontent.com/11878464/215834951-66baba57-05df-478a-812c-abdb409b2dd3.gif)

### 👟 Reproduction steps

1. Open the search modal from the side bar
2. Click outside of the search modal

### 📃 Provide the context for the Bug.

Users are complaining that they cannot dismiss the search modal and are therefore "stuck" on the search.

### 🖥️ Your Environment

OS:   Linux 5.15.0-1028-aws - linux/x64
node: v16.19.0
yarn: 1.22.19
cli:  0.22.0 (installed)
backstage:  1.9.1

Dependencies:
  @backstage/app-defaults                          1.0.10
  @backstage/backend-app-api                       0.2.4
  @backstage/backend-common                        0.17.0
  @backstage/backend-plugin-api                    0.2.0
  @backstage/backend-tasks                         0.4.0
  @backstage/backend-test-utils                    0.1.31
  @backstage/catalog-client                        1.2.0, 1.3.0
  @backstage/catalog-model                         1.1.4, 1.1.5
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.0
  @backstage/config-loader                         1.1.7
  @backstage/config                                1.0.5, 1.0.6
  @backstage/core-app-api                          1.3.0
  @backstage/core-components                       0.11.1, 0.12.2, 0.12.3
  @backstage/core-plugin-api                       1.2.0, 1.3.0
  @backstage/dev-utils                             1.0.10
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.0
  @backstage/integration-react                     1.1.8
  @backstage/integration                           1.4.1, 1.4.2
  @backstage/plugin-api-docs                       0.8.13
  @backstage/plugin-app-backend                    0.3.39
  @backstage/plugin-auth-backend                   0.17.2
  @backstage/plugin-auth-node                      0.2.8
  @backstage/plugin-catalog-backend-module-github  0.2.2
  @backstage/plugin-catalog-backend                1.6.0
  @backstage/plugin-catalog-common                 1.0.10, 1.0.9
  @backstage/plugin-catalog-graph                  0.2.25
  @backstage/plugin-catalog-import                 0.9.3
  @backstage/plugin-catalog-node                   1.3.0
  @backstage/plugin-catalog-react                  1.2.3, 1.2.4
  @backstage/plugin-catalog                        1.7.1
  @backstage/plugin-events-node                    0.2.0
  @backstage/plugin-github-actions                 0.5.13
  @backstage/plugin-home                           0.4.29
  @backstage/plugin-kubernetes-backend             0.9.0
  @backstage/plugin-kubernetes-common              0.5.0
  @backstage/plugin-kubernetes                     0.7.6
  @backstage/plugin-org                            0.6.3
  @backstage/plugin-pagerduty                      0.5.6
  @backstage/plugin-permission-common              0.7.2, 0.7.3
  @backstage/plugin-permission-node                0.7.2
  @backstage/plugin-permission-react               0.4.8, 0.4.9
  @backstage/plugin-proxy-backend                  0.2.33
  @backstage/plugin-scaffolder-backend             1.9.0
  @backstage/plugin-scaffolder-common              1.2.3
  @backstage/plugin-scaffolder                     1.9.1
  @backstage/plugin-search-backend-module-pg       0.5.0
  @backstage/plugin-search-backend-node            1.1.0
  @backstage/plugin-search-backend                 1.2.0
  @backstage/plugin-search-common                  1.2.0, 1.2.1
  @backstage/plugin-search-react                   1.3.1, 1.4.0
  @backstage/plugin-search                         1.0.7
  @backstage/plugin-stack-overflow                 0.1.9
  @backstage/plugin-tech-radar                     0.5.20
  @backstage/plugin-techdocs-backend               1.5.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.8
  @backstage/plugin-techdocs-node                  1.4.3
  @backstage/plugin-techdocs-react                 1.1.1
  @backstage/plugin-techdocs                       1.4.2
  @backstage/plugin-user-settings                  0.6.1
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by diggyk** [comment]
@camilaibs your solution in https://github.com/backstage/backstage/pull/15923 worked.  Closing.

**Comment by camilaibs** [comment]
> @camilaibs your solution in https://github.com/backstage/backstage/pull/15923 worked.  Closing.
> 
> 
Thanks for letting me know!
Hope to see you contributing more with us in the future 🙌🏻
