### ISSUE TITLE
🐛 Bug Report: Github events support should cause the changed catalog entity to be immediately processed

### ISSUE THREAD

**Issue by vonjones** [backstage/backstage#16084]
### 📜 Description

I'm seeing some interplay between GitHub events support and the catalog processing interval. To stay within GitHub rate limits, we have had to use `builder.setProcessingIntervalSeconds` to set the processing interval to 2 hours. Otherwise, with an organization of our size the processing where the catalog wakes up and calls out to GitHub to see if a known, existing catalog entity may have changed is what drives our hitting rate limits.

Note this is separate from any scheduled scan for [GitHub Discovery](https://backstage.io/docs/integrations/github/discovery#configuration), which looks for new `catalog-info.yaml` files. This is about how often we look for updates to catalog files we already know about.

I believe the events mechanism should force immediate processing of the `catalog-info.yaml` files in the event, basically marking that the processing interval is due immediately, moving entities in the (possibly multiple) files to the top of the reprocessing queue.

Presently, when we get an event for a known entity, what I see is it basically has no effect. We already know about the entity, and it waits until the next processing interval to pick up the change. So the event mechanism only seems to address discovery of new catalog files. This doesn't help so much to overcome GitHub rate limit concerns.

### 👍 Expected behavior

When Backstage processes a GitHub change event, the changed entities should update immediately. My users should not have to wait 2 hours to see their updates.

### 👎 Actual Behavior with Screenshots

Users have to wait until the processing interval, in my case 2 hours, to see the impact of their changes to catalog-info.yaml files.

### 👟 Reproduction steps

Change the processing interval to something large, and observe the impact of a GitHub event on the updates to an entity.

### 📃 Provide the context for the Bug.

My users are complaining of the time it takes to see and test their changes.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
Let me start out by saying that the events system is brand new and contributed by the community, and still under development. It requires deliberate installation and wiring-up and configuration and a specific backend plugin with its add-on modules - did you perform those installation steps?

After everything is installed and functional, the intent is indeed that refreshes can be made to trigger immediately, or at least as soon as a worker node finds the entity bubbled up to the top of the processing queue.

**Comment by vonjones** [comment]
Yes, I followed the documented steps.

**Comment by freben** [comment]
Pinging @pjungermann for info here, he's the original author of this system!

**Comment by freben** [comment]
And just double checking - these are the instructions I referred to https://github.com/backstage/backstage/blob/master/plugins/events-backend-module-github/README.md

**Comment by pjungermann** [comment]
What you describe depends on the integration at the `GithubEntityProvider`. I wrote the event system incl. the `events-backend-module-github` plugin which provides an event router accepting general `github` events and routing them to more specific topics which then are used e.g. at the entity provider.

Also, I've added the integration at the `BitbucketCloudEntityProvider` as part of the initial setup. The integration for GitHub was done by other contributors (general entities and org data).

In general, you are right, there are different settings to consider:

- general processing loop which e.g., picks up new Location entities and fetches their targets, etc. (`builder.setProcessingIntervalSeconds`)
- the schedule for the entity provider, doing a full mutation/update which will e.g. find new catalog files
- event-based refresh

In order to be immediate, we need to schedule a refresh.

I had a quick look into the `GithubEntityProvider` and I can see that there is a refresh for modified Locations and a delta mutation for added and removed ones.
Likely it was done similarly at all the other entity providers which roughly followed the original example.

I didn't do any test for your scenario, yet.

A quick assumption is that the delta update is not executed immediate (Locations will be added, however they only get picked up by the next processing loop execution) -- without issuing a refresh for them, too.

@freben What do you think about this?

**Comment by pjungermann** [comment]
and thanks for filing the issue! 👍

**Comment by pjungermann** [comment]
not stale

**Comment by benkeil** [comment]
Are there any news? We are facing the same issue.

**Comment by pjungermann** [comment]
I plan to have a look at all of them and I would like to get it into the next main release 1.14.0. I wanted to finish something else first, though.

Contributions are welcome, of course. (Please let us know here.)

**Comment by pjungermann** [comment]
@vonjones @benkeil In my reply above I thought that added/removed ones are delayed, however, after re-reading it it seems like it is about modified ones.

Can you clarify which change type is affected? add, remove, modify, multiple?

**Comment by pjungermann** [comment]
CC: @angeliski

**Comment by vonjones** [comment]
The goal would be that when a pull request concerns a `catalog-info.yaml` file, it is processed immediately, regardless of whether it is a newly added entity, a change, or deletion. Given GitHub API rate limits, in our Backstage we have to wait 2 hours for entity adds/changes/deletions to show up in Backstage from the time they are merged. This makes sense if we have to schedule scans to go see if something may have changed. But when we get a GitHub push event and we know exactly what changed, I'd like to make this almost instantaneous.

My recollection was that this ticket was mostly a concern for changed or deleted entities, since they wait for the next scheduled scan / change interval even though the GitHub event was seen.

**Comment by vonjones** [comment]
This ticket was mostly a concern for changed or deleted entities, since they wait for the next scheduled scan / processing interval even though the GitHub event was seen.

**Comment by angeliski** [comment]
Hey @vonjones and @benkeil can you share more info about the problem?

I tried a really simple reproduction and works as expected.
I enabled the Github event ([PR](https://github.com/backtostage/angeliski-stage/pull/1)) configured webhook in the org and pushed [a change in the description ](https://github.com/backtostage/github-event-test/commit/59e7c576d42bc1f97fd047e3545d26046b3ef6b7). I can see the result after the event is processed.

Did you can see the logs in your app? Something like that:

```
[1] 2023-05-17T00:18:17.676Z catalog info Processed Github push event: added 0 - removed 0 - modified 1 type=plugin target=github-provider:backtostage
```
Maybe we are missing something more specific about the problem.

Can you try to setup a example so we can see the issue happening and reproduce that?

**Comment by benkeil** [comment]
Can you share your project?

**Comment by angeliski** [comment]
Done @benkeil , I forget to put visibility public

**Comment by benkeil** [comment]
Thanks! I had 2 issues:

1. I didn't add `setEventBroker(env.eventBroker)`
2. I use the events via SQS and not HTTP and I forgot to forward the `X-GitHub-Event` header.

So in general everything works as expected. For my 2 issues I will check if I can improve the README of the plugins.

But there are 2 more open points: 

1. `GithubEntityProvider.fromConfig()` forces me to add a schedule. I think it's still a good idea to sync the system like once in the night, but maybe we should let decide the user.
2. The same thing is for `CatalogBuilder.setProcessingIntervalSeconds()`.

Do I need both schedules? Do I need them at all?

**Comment by pjungermann** [comment]
@vonjones 

> for changed and deleted entities

That's what is putting me off.

Actually, add + delete share the same implementation. They cause a delta mutation.

changed entities are handled a bit differently. Here, we already trigger a refresh directly.

I would have expected "added + deleted" instead of "changed + deleted".

**Comment by pjungermann** [comment]
@benkeil re your open points:

the event support is a rather recent addition.

I think it is still good to have a full refresh to recover from any potentially missed event.

The processing interval is global and affects all Location entities. This and many other entity providers are based on these under the hood.

Basically, the providers discover catalog files and (de)register Location entities for these.

The processing interval refreshes what their targets (catalog files) contain.

There are a couple of discussions around that matter on different issues with different scopes.

**Comment by benkeil** [comment]
In theory, if everything comes from GitHub, there is no need to refresh the catalog, or? Everything should already be handled by the events.

To make a refresh like everyday sounds still like a good idea.

**Comment by pjungermann** [comment]
yeah, or even weekly. Whatever makes sense.

In theory, you should get all events, etc. However, everything can break.

Also, as far as I remember, GitHub might truncate the file list, e.g., for big PRs. In that case, we might not be able to detect it properly.

**Comment by angeliski** [comment]
@vonjones Did you have time to look at this?

**Comment by vonjones** [comment]
We were hoping to change the scheduled Github scans to be less frequent, like daily overnight, once events are working. There are other gaps, like https://github.com/backstage/backstage/issues/15878, which preclude us from this.

I believe the processing interval is also a separate setting from the schedule for GitHub repo scans. I think the former is more about how often you look for updates in the entities you already know about.

**Comment by pjungermann** [comment]
FYI: I did a bigger test using the BitbucketCloudEntityProvider which was the prototype for the event support and with regards to the update mechanism, they follow the same logic. However, there might be differences in provider-specific logic.

For my test, I used

- BitbucketCloudEntityProvider
- a single isolated project at bitbucket.org using `catalogPath: catalog-test.yaml`
- schedule.frequency of 5 h at the BitbucketCloudEntityProvider (full refresh)
- processing interval of 5 h configured at the CatalogBuilder
- SQS-based event ingestion with event data flow: webhook -> [...] -> SQS -> AwsSqsConsumingEventPublisher -> BitbucketEventRouter -> BitbucketCloudEntityProvider.onEvent

Environment:

- entity provider
  - config under `catalog.providers.bitbucketCloud`
  - provider added to the CatalogBuilder (`builder.addEntityProvider(provider);`)
  - provider registered as a subscriber (`env.eventBroker.subscribe(provider);`)
- events
  - general event setup prepared
  - [...]EventRouter added as publisher *and* subscriber (`BitbucketCloudEventRouter`, `GithubEventRouter`, etc.)
  - `HttpPostIngressEventPublisher` and/or `AwsSqsConsumingEventPublisher` to retrieve events from external
  - webhook subscription which is sent and received successfully (e.g., you see logs from the provider which is supposed to handle it)

Scenario:

- wait for initial discovery to be completed
- add catalog file + verify
- modify catalog file + verify
- delete catalog file

All changes were applied immediately.

Originally, I assumed that there might be some issue with the difference between modification and add/remove as modifications will issue a refresh for the already existing entry (similar to the refresh button at the UI) while add/remove use the delta mutation.

However, as described, all cases worked as expected and updates were applied immediately.

**Comment by pecatadev** [comment]
Hello, @pjungermann can you please share your code for the last test you have done with BitbucketCloudEntityProvider? I'm trying to setup it, but I'm missing something because I can't see the updated version after receiving the event

**Comment by SayakMukhopadhyay** [comment]
For what its worth, I was able to set up events with my GitHub org and pushes are immediately reflected in backstage. The changes I made were as follows:
`backend/src/plugins/catalog.ts`
```diff
...
- builder.addEntityProvider(
-   GithubEntityProvider.fromConfig(env.config, { ...loggerAndScheduler }),
- );
+ const githubEntityProvider = GithubEntityProvider.fromConfig(env.config, {
+   ...loggerAndScheduler,
+ });
+ env.eventBroker.subscribe(githubEntityProvider);
+ builder.addEntityProvider(githubEntityProvider);
...
```
`backend/src/plugins/events.ts`
New File:
```ts
// imports
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const eventsRouter = Router();
  const githubEventRouter = new GithubEventRouter();

  const http = HttpPostIngressEventPublisher.fromConfig({
    config: env.config,
    logger: env.logger,
    ingresses: {
      github: {
        validator: createGithubSignatureValidator(env.config),
      },
    },
  });
  http.bind(eventsRouter);

  await new EventsBackend(env.logger)
    .setEventBroker(env.eventBroker)
    .addPublishers(http, githubEventRouter)
    .addSubscribers(githubEventRouter)
    .start();

  return eventsRouter;
}
```
`backend/src/index.ts`
```diff
//imports
...
function makeCreateEnv(config: Config) {
  const root = getRootLogger();
  const reader = UrlReaders.default({ logger: root, config });
  const discovery = SingleHostDiscovery.fromConfig(config);
  const cacheManager = CacheManager.fromConfig(config);
  const databaseManager = DatabaseManager.fromConfig(config, { logger: root });
  const tokenManager = ServerTokenManager.noop();
  const taskScheduler = TaskScheduler.fromConfig(config);

  const identity = DefaultIdentityClient.create({
    discovery,
  });
  const permissions = ServerPermissionClient.fromConfig(config, {
    discovery,
    tokenManager,
  });

+ const eventBroker = new DefaultEventBroker(root.child({ type: 'plugin' }));
+
  root.info(`Created UrlReader ${reader}`);

  return (plugin: string): PluginEnvironment => {
    const logger = root.child({ type: 'plugin', plugin });
    const database = databaseManager.forPlugin(plugin);
    const cache = cacheManager.forPlugin(plugin);
    const scheduler = taskScheduler.forPlugin(plugin);
    return {
      logger,
      database,
      cache,
      config,
      reader,
+     eventBroker,
      discovery,
      tokenManager,
      scheduler,
      permissions,
      identity,
    };
  };
}

async function main() {
  const config = await loadBackendConfig({
    argv: process.argv,
    logger: getRootLogger(),
  });
  const createEnv = makeCreateEnv(config);

  const catalogEnv = useHotMemoize(module, () => createEnv('catalog'));
  const scaffolderEnv = useHotMemoize(module, () => createEnv('scaffolder'));
  const authEnv = useHotMemoize(module, () => createEnv('auth'));
  const proxyEnv = useHotMemoize(module, () => createEnv('proxy'));
  const techdocsEnv = useHotMemoize(module, () => createEnv('techdocs'));
  const searchEnv = useHotMemoize(module, () => createEnv('search'));
  const appEnv = useHotMemoize(module, () => createEnv('app'));
  const healthcheckEnv = useHotMemoize(module, () => createEnv('healthcheck'));
  const techRadarEnv = useHotMemoize(module, () => createEnv('tech-radar'));
+ const eventsEnv = useHotMemoize(module, () => createEnv('events'));

  const apiRouter = Router();
  apiRouter.use('/catalog', await catalog(catalogEnv));
  apiRouter.use('/scaffolder', await scaffolder(scaffolderEnv));
  apiRouter.use('/auth', await auth(authEnv));
  apiRouter.use('/techdocs', await techdocs(techdocsEnv));
  apiRouter.use('/proxy', await proxy(proxyEnv));
  apiRouter.use('/search', await search(searchEnv));
  apiRouter.use('/tech-radar', await techradar(techRadarEnv));
+ apiRouter.use('/events', await events(eventsEnv));

  // Add backends ABOVE this line; this 404 handler is the catch-all fallback
  apiRouter.use(notFoundHandler());

  const service = createServiceBuilder(module)
    .loadConfig(config)
    .addRouter('', await healthcheck(healthcheckEnv))
    .addRouter('/api', apiRouter)
    .addRouter('', await app(appEnv));

  await service.start().catch(err => {
    console.log(err);
    process.exit(1);
  });
}
...
```
`backend/src/types.ts`
```diff
//imports
export type PluginEnvironment = {
  logger: Logger;
  database: PluginDatabaseManager;
  cache: PluginCacheManager;
  config: Config;
  reader: UrlReader;
+ eventBroker: EventBroker;
  discovery: PluginEndpointDiscovery;
  tokenManager: TokenManager;
  scheduler: PluginTaskScheduler;
  permissions: PermissionEvaluator;
  identity: IdentityApi;
};
```

**Comment by AlanWaiteDSG** [comment]
I'm also running into this problem, I've matched up the event code to nearly exactly the same as the examples shown above but it will not refresh until the builder.setProcessingIntervalSeconds interval is up.

My changes include:
* Updated app-config.yaml for the events fields
* Updated  packages/backend/src/index.ts to include the setup for eventsBroker
* Updated packages/backend/src/plugins/catalog.ts to include the GithubEntityProvider and subscribe it to the eventBroker
* Created the events plugin repo that is logically identical to the above example
* Updated packages/backend/src/types.ts to include eventBroker.

I can verify that the webhook is getting "Accepted" but it just doesn't result in any kind of update until the interval is up.

**Comment by freben** [comment]
If things take a while to update, it might be that the catalog is struggling to keep up with processing fast enough. Essentially, the processing loop will keep pulling out items and putting them at `now() plus deltaT` for the next round. If it takes longer than `deltaT` to work away everything else that was due before that entity, things will start having a due date in the past. An event coming in and saying "you should process this thing now" still leaves other entities before it in the queue.

We don't have much documentation on catalog optimization. But in general, having a powerful-enough database server and horizontally scaling the number of catalog worker nodes brings things up to speed.

**Comment by wanisfahmyDE** [comment]
@pjungermann we just implemented it with GitHub and can confirm that all additions, modifications and deletions are reflected instantly 🚀

In case it helps anyone, our complete `catalog.ts` config looks like this:

```TypeScript
import {CatalogBuilder} from '@backstage/plugin-catalog-backend';
import {ScaffolderEntitiesProcessor} from '@backstage/plugin-scaffolder-backend';
import {Router} from 'express';
import {PluginEnvironment} from '../types';
import {
    GithubEntityProvider,
    GithubOrgEntityProvider,
} from '@backstage/plugin-catalog-backend-module-github';

/*
 The sequence works as follows:
    1. The eventBroker kicks in with every new/modified changes on catalog-info.yaml.
    2. If the event is dropped for any reason, a fallback with builder.setProcessingIntervalSeconds(3600) kicks in for existing entities only.
    3. Twice per day our complete GitHub organization is scanned and onboards/updates the Components in Backstage (scheduler).
 */
export default async function createPlugin(
    env: PluginEnvironment,
): Promise<Router> {
    const builder = await CatalogBuilder.create(env);
    // The org URL below needs to match a configured integrations.github entry
    // specified in your app-config.
    builder.addEntityProvider(
        GithubOrgEntityProvider.fromConfig(env.config, {
            id: '<some-id>',
            orgUrl: 'https://github.com/<org-name>',
            logger: env.logger,
            schedule: env.scheduler.createScheduledTaskRunner({
                frequency: {minutes: 60},
                timeout: {minutes: 15},
            }),
        }),
    );
    const githubProvider = GithubEntityProvider.fromConfig(env.config, {
        logger: env.logger,
        schedule: env.scheduler.createScheduledTaskRunner({
            frequency: {minutes: 720}, /* twice per day checking all repos and importing/refreshing in the catalog */
            timeout: {minutes: 30},
        })
    });
    env.eventBroker.subscribe(githubProvider); /* any new add/delete/modify actions in catalog-info.yaml will be handled by the event broker */
    builder.addEntityProvider(githubProvider);
    builder.setProcessingIntervalSeconds(3600) /* only for existing entities, they would be refreshed if the eventBroker didn't catch the event - currently set every 1 hour */
    builder.addProcessor(new ScaffolderEntitiesProcessor());
    const {processingEngine, router} = await builder.build();
    await processingEngine.start();
    return router;
}

```

**Comment by pjungermann** [comment]
Thank you @wanisfahmyDE for sharing your experience. All my tests and cases I've investigated ended similarly so far.

@freben 's comment might lead to a direction that could be the source of issues for some.

If anyone has more details, we are happy to look further into the matter. However, we need more details about your case. For now, I would consider the events to work as expected.

**Comment by shivanand7283** [comment]
@pjungermann 
Thanks for the above updates. 

after adding the same changes in the catalog.ts,  I am getting the below error while loading the backend,

`Backend failed to start up ReferenceError: DefaultEventBroker is not defined`

I have added the DefaultEventBroker in index.ts file 

`const eventBroker = new DefaultEventBroker(root.child({ type: 'plugin' }));`

 ```
  discovery,
      tokenManager,
      eventBroker,
```

I have added this two plugin as well 

# From your Backstage root directory
yarn add --cwd packages/backend @backstage/plugin-events-backend-module-github

yarn add --cwd packages/backend @backstage/plugin-events-backend @backstage/plugin-events-node

Can you please confirm am I missing something here?

**Comment by maurosch** [comment]
I am also having trouble with github web-hooks not trigerring refresh on entities when using wildcards on github discovery.

Looking at the code:
`onRepoPush` function in [`GithubEntityProvider`](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/providers/GithubEntityProvider.ts) calls refresh of entities using repository name as key.

But on `refresh_keys` db table, we can have keys with wildcards and [`refreshByRefreshKeys`](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/database/operations/provider/refreshByRefreshKeys.ts) does not take wildcards into account.

**Comment by anooprehman** [comment]
> I'm also running into this problem, I've matched up the event code to nearly exactly the same as the examples shown above but it will not refresh until the builder.setProcessingIntervalSeconds interval is up.
> 
> My changes include:
> 
> * Updated app-config.yaml for the events fields
> * Updated  packages/backend/src/index.ts to include the setup for eventsBroker
> * Updated packages/backend/src/plugins/catalog.ts to include the GithubEntityProvider and subscribe it to the eventBroker
> * Created the events plugin repo that is logically identical to the above example
> * Updated packages/backend/src/types.ts to include eventBroker.
> 
> I can verify that the webhook is getting "Accepted" but it just doesn't result in any kind of update until the interval is up.

This can happen if proper header is not send when calling the API (if testing in local). Eg: You need to pass the `x-github-event` header with value `push`.
