### ISSUE TITLE
🐛 Bug Report: LDAP plugin-catalog-backend-module-ldap schedule does not work.

### ISSUE THREAD

**Issue by antoniomuso** [backstage/backstage#16102]
### 📜 Description

The LDAP plugin schedule does not work.

### 👍 Expected behavior

I expect that every 60 minutes, the plugin scans LDAP to find new entries.

### 👎 Actual Behavior with Screenshots

The new entries are not added into Backstage.

### 👟 Reproduction steps

1. Setup LDAP with:
```ts
builder.addEntityProvider(
    LdapOrgEntityProvider.fromConfig(env.config, {
      id: 'immobiliare-ldap',
      target: ldapAddress,
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: Duration.fromDurationLike({ minutes: 60 }),
        timeout: Duration.fromDurationLike({ minutes: 15 }),
      }),
      groupTransformer: customGroupTransform,
      userTransformer: (vendor, config, user) =>
        customUserTransform(vendor, config, user, env.config),
    }),
  );
```
2. Add a new user into LDAP.
3. Wait for the task schedule.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by riginoommen** [comment]
@antoniomuso 

try like this 
```bash
schedule: env.scheduler.createScheduledTaskRunner({
      frequency: { minutes: 1 },
      timeout: { minutes: 15 },
    }),
```

**Comment by antoniomuso** [comment]
Thank you, I was using an old version configuration of the plugin. It works!
