### ISSUE TITLE
🚀 Feature: CatalogPage to support filter and sort by namespace

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#16118]
### 🔖 Feature description

Currently there is no way to filter entities in the default Catalog page by namespace. This seems like a pretty helpful way to search through entities and could be a namespace picker dropdown similar to the existing pickers like kind, type, and tags.

If providing a namespace filter, that Catalog table should also be updated to clearly display the namespace an Entity is in. This namespace column should be a sortable column like other columns in the table. 

### 🎤 Context

In very large organizations, using namespaces is a great way to provide additional context / groupings to an entity. A namespace filter would be a great addition to searchability / discovery.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
That would make sense! It would be in the form of a filter component on the left hand side of the screen, I presume. I'll add a help wanted label on the issue.

**Comment by DavidAn830** [comment]
I would like to work on this request if possible!

**Comment by bforbis** [comment]
Just one thought around how this is implemented, perhaps this should be made configurable so that backstage users that don't utilize namespaces don't have their UI cluttered? Maybe include these filters / columns by default, but have a way to opt-out?

**Comment by freben** [comment]
Right, it could be an opt-in control (a custom filter that you would choose to add to your catalog page). It could also be implemented such that after querying the catalog (using the facets endpoint) for the list of possible namespaces, if it finds "default" to be the only one available, it just hides itself.

**Comment by prijithvrgs90** [comment]
@freben How to filter user entities based on user email ID in CatalogTable ? My entities has spec.profile.email. Thanks in advance

**Comment by DavidAn830** [comment]
Hey! I just made a [pull request!](https://github.com/backstage/backstage/pull/16348) . Please let me know if there needs to be any changes to be made!

**Comment by belech** [comment]
Hi @DavidAn830 , any updates to this? we'd have exactly this use case, where we just want show initially the default namespace when opening the catalog page - but also want to have other entities in other namespaces, thus not clutter the catalog page on initial load.

**Comment by DavidAn830** [comment]
@belech just need to address those changes. I'm looking that to be done by this week.

**Comment by coopernetes** [comment]
Just to add one more use case that this would address: name collisions. 

We have a pretty sprawling environment and namespaces give entities an additional "key space" for naming them that would help a large org such as ours. It's difficult to ingest & model existing software into the catalog  without the ability to having at least one depth of grouping built into the names. Additionally, the 63 character limit on names can be a bit restrictive.

**Comment by Rugvip** [comment]
Gonna close this as the original ask was implemented in #16348. Let's move any additional features requests in to separate issues
