### ISSUE TITLE
💬 RFC: Auth with Gitlab

### ISSUE THREAD

**Issue by kamenskiyyyy** [backstage/backstage#16123]
### 🔖 Need

Hi, everybody,

Please tell me how to set up authorization with Gitlab correctly? I couldn't find this information in the documentation and in the examples.

### 🎉 Proposal

I did everything according to the instructions. 

I also use Org Data from Gitlab for authorization.  The documentation is described in [detail with GitHub](https://backstage.io/docs/integrations/github/org), I would like to get the same [instructions for GitLab](https://backstage.io/docs/integrations/gitlab/org).

`UI Backstage`
<img width="916" alt="Screenshot 2023-02-01 at 21 52 03" src="https://user-images.githubusercontent.com/72261703/216139284-0f19e15d-0b20-4997-9ede-ad255f4cb437.png">

`packages/app/src/App.tsx`
<img width="694" alt="image" src="https://user-images.githubusercontent.com/72261703/216138319-17b7a681-3079-47f8-9337-6dccdea7d554.png">

`app-config.yaml`
<img width="688" alt="image" src="https://user-images.githubusercontent.com/72261703/216138435-6cf23c28-d05a-42ee-89e8-43506ffde95f.png">

`packages/backend/src/plugins/auth.ts`
<img width="532" alt="image" src="https://user-images.githubusercontent.com/72261703/216139494-4798899f-3ceb-4a0a-8c36-ac6abcffe5b8.png">

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
In `packages/backend/src/plugins/auth.ts` it should be `gitlab: providers.gitlab.create({`, you've currently got `github` as the key.

Please reach out on Discord for support or open a bug report if you think you've found a bug. The RFC format is for suggesting changes or additions to the project.

**Comment by kamenskiyyyy** [comment]
Sorry, it's my mistake. You're absolutely right. Thank you for the quick response🙈🤗
