### ISSUE TITLE
🐛 Bug Report: action publish:gitlab failes with error 404

### ISSUE THREAD

**Issue by TalZiv** [backstage/backstage#16134]
### 📜 Description

Hi,

We have created a sample software template on our Gitlab private repository and registered it in Backstage.
After filling in all the details when creating the template, the templating step is successful but the publish step failed
with a 404 error.

 We just took this https://github.com/backstage/software-templates/blob/main/scaffolder-templates/springboot-grpc-template/template.yaml and replaced to our host and chnaged the action to "publish:gitlab"

### 👍 Expected behavior

Publish the skeleton to Gitlab after templating.

### 👎 Actual Behavior with Screenshots

`2023-02-01T12:36:15.444Z Beginning step Publish[2](https://xxxxxxxxx/create/tasks/962efe65-66ca-48bf-a85a-721d40302f81#line-2)2023-02-01T12:36:15.586Z HTTPError: Response code 404 (Not Found)[3](https://xxxxxxxxx/create/tasks/962efe65-66ca-48bf-a85a-721d40302f81#line-3)    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:118:42)[4](https://xxxxxxxxxx/create/tasks/962efe65-66ca-48bf-a85a-721d40302f81#line-4)    at runMicrotasks (<anonymous>)[5](https://xxxxxxxxxx/create/tasks/962efe65-66ca-48bf-a85a-721d40302f81#line-5)    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

### 👟 Reproduction steps

- Register software template 
- create new software template
- fill out the deatils
- run the process

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
A lot of systems respond with 404 when you don't have authorization to perform an action. Could it be that you haven't configured the auth tokens yet?

**Comment by TalZiv** [comment]
The issue was that the owner in the template did not exist in Backstage prior to the lunching of the software template.
