### ISSUE TITLE
🐛 Bug Report: Inconsistent display of the list of entities

### ISSUE THREAD

**Issue by mohBobo** [backstage/backstage#16138]
### 📜 Description

Hello,
There is an inconsistency in the sorting of the list of entities. When the title is different from the name in the yaml file of an entity, the sorting is done by the name but it is the title that is displayed in the table.

<img width="115" alt="list_des_apis" src="https://user-images.githubusercontent.com/91227023/216305821-3b831729-fdb4-4f43-aac9-2704d325a0c6.PNG">

### 👍 Expected behavior

Either sort and display by name or sort and display by title.

### 👎 Actual Behavior with Screenshots

<img width="115" alt="list_des_apis" src="https://user-images.githubusercontent.com/91227023/216307880-08baa367-9b26-4ef1-abdf-81032eb44fb5.PNG">

### 👟 Reproduction steps

click on the button of the sidebar displaying the list of published entities.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Note also that this may be complicated in a future where we have pagination, and not all entities are in memory at the same time. But I've reviewed the PR now.

**Comment by Rugvip** [comment]
Closing as this was fixed by #16178
