### ISSUE TITLE
🚀 Feature: Support multiple hostname (app URL) names for the app

### ISSUE THREAD

**Issue by kvmw** [backstage/backstage#16149]
### 🔖 Feature description

Sometimes a single deployment needs to have multiple hostnames. For example public url and internal url. 

Currently the `backend.baseUrl` needs to be statically defined in configuration. therefore all backend calls will be using the same url which is defined in the config. 

### 🎤 Context

Having multiple urls (hostnames) for the app enables customers to redirect traffic from other domains to the app. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sennyeya** [comment]
What does your deployment look like? Are you using the `app-backend` package? Is your backend URL the same as your front end URL for both public and internal sites, ie backend and front end are hosted at either http://backstage.internal-site.com or https://backstage.external-site.com.

I did some work to support the case where backend and front end are hosted on the same domain, see https://github.com/backstage/backstage/pull/13927. If that fits your use case, the only issue would be CORS in your backend configuration.

**Comment by kvmw** [comment]
@sennyeya 
yes, the backend and frontend have the same URL.  
It is deployed in k8s cluster and using `ingress` we want to forward traffic from 2 or more addresses to the same deployment. 

Let's say we have `internal` and `external`  urls and the app (both backend and frontend) is configured with `internal` url. when user access the website using `external` url, the javascript calls to backend are still using the `internal` url. one can see that in browser dev-tools.

**Comment by sennyeya** [comment]
Can you expand on your Backstage version? The above mentioned features were released as part of 1.9.1.

**Comment by freben** [comment]
In regards to "needs to have" - what's the actual use case? What does it unlock?

**Comment by kvmw** [comment]
> 

@freben  in general, application image should not know/care about the host/url which is being  served.  Imagine I've the backstage image used in a k8s deployment. I should be able to expose this  deployment using ingress without any further configuration change.  so the public endpoint can change from `app.foo.io`  to `app.bar.io` (in ingress) without changing the deployment, app image or its configuration.  

In my specific case, as i've mentioned earlier, i'd like to have two endpoints for the app. one would be for users within company VPN and another for users who are connecting outside of VPN.  the authentication methods are different for each network (which is taken care of in ingress). And of course URLs are different for each network.

**Comment by Rugvip** [comment]
@kvmw as long as you host the frontend app on the same origin as the backend it should automatically adapt the frontend config for each env.

While the backend mostly doesn't care about the frontend app origin there are security sensitive pieces where it does. One is CORS, but if you're hosting on the same origin you won't have that issue. The other one is the auth flow. If you want the auth backend to support multiple domains that's not officially supported, but it's possible to do using an experimental option, https://github.com/backstage/backstage/blob/e8f2ac13e7032f7db33ea0d9adf643233833034b/plugins/auth-backend/src/service/router.ts#LL203C6-L203C10.

I think it'd be the following in config:

```yaml
auth:
  experimentalExtraAllowedOrigins:
  - app.foo.io
  - app.bar.io
```

There are some auth providers that may not support multiple origins, in which case you'd need to use separate auth environments with two separate configurations for that provider.

**Comment by kvmw** [comment]
@Rugvip  this might  be because i'm on older version of backstage, but as you know i can only configure **one** url for the app.  so If i configure the app url to be `app.foo.io`  and try to access the app using `app.bar.io`  I'll get the CORS error
```
Access to fetch at 'https://app.foo.io/api/catalog/entity-facets?facet=metadata.tags' 
from origin 'https://app.bar.io' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
```

The ingress configuration is working fine and forwarding both `app.foo.io/*` and `app.bar.io/*` requests to the app but the problem is the javascript calls which are using the URL which is configured in the app and not the one that is in the browser address bar.

**Comment by taras** [comment]
@Rugvip Is it possible to configure this via the injection system? I never tried, but it seems like it could be possible in theory.

**Comment by wKich** [comment]
<img width="906" alt="Screenshot 2023-07-18 at 22 51 53" src="https://github.com/backstage/backstage/assets/6397708/9904bf51-2a55-4df0-ba57-ea624aed1be5">
