### ISSUE TITLE
🔌 Plugin: Azure Sites

### ISSUE THREAD

**Issue by jpitapeva** [backstage/backstage#16146]
### 🔖 Summary

I am with a problem when i use the azure sites plugin, i added in AD the app registration and the added the config below, but i try the test in portal, is showed 403(forbidden), i don't if i need app more permitions 

azureSites:
  domain: xxxx.onmicrosoft.com
  tenantId: xxx
  clientId: xxx
  clientSecret: xxx

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by deepan10** [comment]
Hello @jpitapeva
You need to add your `App Registration(Service Principle) - ClientID` as a Contributor in to your `Azure Sites(App/Function)` resource.

**Comment by jpitapeva** [comment]
@deepan10 thank you to much, is working

**Comment by jpitapeva** [comment]
Thank you too much
