### ISSUE TITLE
🚀 Feature: enable PagerDuty plugin "read only mode" configuration option

### ISSUE THREAD

**Issue by mdb** [backstage/backstage#16147]
### 🔖 Feature description

In current implementation, the PagerDuty plugin exposes a link through which users can create new incidents. However, in service of those organizations who prefer the Backstage PagerDuty plugin serve exclusively as a "read only" mechanism for browsing PagerDuty data -- and not for modifying it -- it would be useful to expose a PagerDuty plugin configuration option through which the actionable "Create Incident" link can be omitted from the rendered UI.

### 🎤 Context

In addition to making the frontend UX more configurable, a `readOnly` configuration arguably has some security benefits too...

The current plugin implementation -- and its reliance on a backend proxy to the PagerDuty API -- inadvertently requires exposing an unprotected PagerDuty API endpoint through the Backstage backend.

As a result -- and assuming the PagerDuty API key with which the Backstage backend proxy is configured is authorized to do so -- the current plugin frontend implementation grants any Backstage user the escalated privilege to create, modify, and/or destroy PagerDuty data, which is arguably an anti-pattern for those Backstage users whose Backstage privileges don't directly map to their PagerDuty privileges (While this could presumably be avoided by specifying a `allowedMethods: ['GET']` on the PagerDuty proxy configuration, suppressing the rendering of actionable links and buttons altogether would offer UX that better matches the proxy functionality).

### ✌️ Possible Implementation

I'm imagining something similar to what was done via https://github.com/backstage/backstage/pull/9635 for the Splunk OnCall plugin and what seems planned for the AzureSite plugin via https://github.com/backstage/backstage/issues/16035:

```ts
<PagerDuty readOnly />
```
 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
This sounds like it'd benefit from being implemented in terms of [the permissions system](https://backstage.io/docs/permissions/overview) instead of via just a hard binary config. That way you can actually steer _who_ can do it or not. Note that the Azure PR you linked received the same feedback, and are adjusting accordingly.

**Comment by mdb** [comment]
> This sounds like it'd benefit from being implemented in terms of [the permissions system](https://backstage.io/docs/permissions/overview) instead of via just a hard binary config. That way you can actually steer who can do it or not. Note that the Azure PR you linked received the same feedback, and are adjusting accordingly.

@freben Thanks for the feedback! I recognize that @benjdlambert  suggested #16035 (implemented via https://github.com/backstage/backstage/pull/16171) leverage the permissions system. However, before I dig into doing so for PR #16148 too, do you feel the PagerDuty plugin might _also_ benefit from a `readOnly` binary config to suppress the rendering of the "Create Incident" button altogether? If not, I'm happy to chase leveraging the permissions system to implement this instead :)

**Comment by mdb** [comment]
This can be closed per the merging of PR https://github.com/backstage/backstage/pull/16148
