### ISSUE TITLE
🔌 Plugin: StackStorm

### ISSUE THREAD

**Issue by pamelin** [backstage/backstage#16154]
### 🔖 Summary

This plugin should add the integration with [StackStorm](https://docs.stackstorm.com/index.html). The work is already done and I have opened a PR https://github.com/backstage/backstage/pull/16152

Users should be able to add this plugin to their backstage instance and connect it to their StackStorm instance to view workflow executions, packs and actions.

### ✌️ Context

StackStorm is a platform for integration and automation across services and tools. This plugin will give users access to details about their st2 instance, workflows, actions, sensors. In the future it can be expanded to allow users to trigger workflows, re-run actions etc...

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by pamelin** [comment]
PR with the StackStorm plugin has been merged 🎉

**Comment by ryanmerolle** [comment]
I know this is a long closed issue, but I’m generally interested in infra orchestration including backstage, stwckstorm, etc.

I’ve been hesitant to go in on stackstorm given it seems not as active as I would expect it to given the orchestration problem it solves. @pamelin may I get your thoughts on this?
