### ISSUE TITLE
🐛 Bug Report: Github Discovery Catalogs via Wildcard config

### ISSUE THREAD

**Issue by darrenyung** [backstage/backstage#16161]
### 📜 Description

Performance has been inconsistent between manual catalog upload via **/catalog-import** and Github Discovery feature with Wild Card entry.

I have a file with 48 OpenAPI catalogues injected into it. When performing import on the WebUI, it validated and imported successfully. 

However, we have automated processes in the background which involves auto-gen catalog-info files and when Backstage background process performs catalog discovery, I get an error and thus failed to Add/Update the components. 

I noticed the github URL path that its trying to call to retrieve the artifact is different from what is defined in the **$text**.

FYI: I'm currently running on 2 instances of Backstage in my environment.

### 👍 Expected behavior

Catalog added/updated successfully.

### 👎 Actual Behavior with Screenshots

Console log

```
"[2m2023-02-03T02:00:46.189Z[22m [34mcatalog[39m [33mwarn[39m Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location https://github.com/org/file.yaml, Error: Incorrect URL: https://github.com/org//tree/-/specs/file.yaml, Error: Invalid GitHub URL or file path [36mtype[39m=plugin [36mentity[39m=api:default/<api_name>"
```

### 👟 Reproduction steps

Have a yaml file containing over 40 catalogs. (Note: We have generated over 50 catalogs but noticed that it would result in timeout, so we capped it at 50)

Config
```
wildcardProviderId:
        organization: '<orgname>'
        catalogPath: '/backstage/**/*.yaml'
```

Sample Catalog

```
...
spec:
  system: <system_name>
  owner: <team_name>
  type: openapi
  lifecycle: experimental
  definition:
    $text: https://github.com/org/repo/blob/main/specs/file.yaml
```

**Github Discovery**

1. Configure Github discovery with wildcard matching. 
2. Run backstage and let the GH discovery process run.

**Via WebUI**

1. Go to 'catalog-import' page.
2. Import the generated file.
3. Notice that validation is successful and ready to import

### 🖥️ Your Environment

OS:   Darwin 22.3.0 - darwin/x64
node: v16.13.0
yarn: 1.22.19
cli:  0.20.0 (installed)
backstage:  1.7.2

Dependencies:
  @backstage/app-defaults                               1.0.7
  @backstage/backend-app-api                            0.2.2
  @backstage/backend-common                             0.15.2
  @backstage/backend-plugin-api                         0.1.3
  @backstage/backend-tasks                              0.3.6
  @backstage/backend-test-utils                         0.1.29
  @backstage/catalog-client                             1.1.1
  @backstage/catalog-model                              1.1.2
  @backstage/cli-common                                 0.1.10
  @backstage/cli                                        0.20.0
  @backstage/config-loader                              1.1.5
  @backstage/config                                     1.0.3
  @backstage/core-app-api                               1.1.1
  @backstage/core-components                            0.11.2
  @backstage/core-plugin-api                            1.0.7
  @backstage/dev-utils                                  1.0.7
  @backstage/errors                                     1.1.2
  @backstage/integration-react                          1.1.5
  @backstage/integration                                1.3.2
  @backstage/plugin-api-docs                            0.8.10
  @backstage/plugin-app-backend                         0.3.37
  @backstage/plugin-auth-backend                        0.17.0
  @backstage/plugin-auth-node                           0.2.6
  @backstage/plugin-badges-backend                      0.1.31
  @backstage/plugin-badges                              0.2.34
  @backstage/plugin-bazaar-backend                      0.2.0
  @backstage/plugin-bazaar                              0.1.25
  @backstage/plugin-catalog-backend-module-github       0.1.8
  @backstage/plugin-catalog-backend                     1.5.0
  @backstage/plugin-catalog-common                      1.0.7
  @backstage/plugin-catalog-graph                       0.2.22
  @backstage/plugin-catalog-import                      0.9.0
  @backstage/plugin-catalog-node                        1.2.0
  @backstage/plugin-catalog-react                       1.2.0
  @backstage/plugin-catalog                             1.6.0
  @backstage/plugin-cost-insights-common                0.1.1
  @backstage/plugin-cost-insights                       0.11.32
  @backstage/plugin-explore-react                       0.0.22
  @backstage/plugin-explore                             0.3.41
  @backstage/plugin-github-actions                      0.5.10
  @backstage/plugin-github-issues                       0.1.2
  @backstage/plugin-github-pull-requests-board          0.1.4
  @backstage/plugin-home                                0.4.26
  @backstage/plugin-kubernetes-backend                  0.7.3
  @backstage/plugin-kubernetes-common                   0.4.3
  @backstage/plugin-kubernetes                          0.7.3
  @backstage/plugin-org                                 0.5.10
  @backstage/plugin-permission-common                   0.7.0
  @backstage/plugin-permission-node                     0.7.0
  @backstage/plugin-permission-react                    0.4.6
  @backstage/plugin-proxy-backend                       0.2.31
  @backstage/plugin-scaffolder-backend                  1.7.0
  @backstage/plugin-scaffolder-common                   1.2.1
  @backstage/plugin-scaffolder                          1.7.0
  @backstage/plugin-search-backend-module-elasticsearch 1.0.3
  @backstage/plugin-search-backend-module-pg            0.4.1
  @backstage/plugin-search-backend-node                 1.0.3
  @backstage/plugin-search-backend                      1.1.0
  @backstage/plugin-search-common                       1.1.0
  @backstage/plugin-search-react                        1.2.0
  @backstage/plugin-search                              1.0.3
  @backstage/plugin-shortcuts                           0.3.2
  @backstage/plugin-sonarqube-backend                   0.1.2
  @backstage/plugin-sonarqube                           0.4.2
  @backstage/plugin-stack-overflow                      0.1.6
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.21
  @backstage/plugin-tech-insights-backend               0.5.3
  @backstage/plugin-tech-insights-common                0.2.7
  @backstage/plugin-tech-insights-node                  0.3.5
  @backstage/plugin-tech-insights                       0.3.2
  @backstage/plugin-tech-radar                          0.5.17
  @backstage/plugin-techdocs-addons-test-utils          1.0.5
  @backstage/plugin-techdocs-backend                    1.4.0
  @backstage/plugin-techdocs-module-addons-contrib      1.0.5
  @backstage/plugin-techdocs-node                       1.4.1
  @backstage/plugin-techdocs-react                      1.0.5
  @backstage/plugin-techdocs                            1.3.3
  @backstage/plugin-todo-backend                        0.1.34
  @backstage/plugin-todo                                0.2.12
  @backstage/plugin-user-settings                       0.5.0
  @backstage/release-manifests                          0.0.6
  @backstage/test-utils                                 1.2.1
  @backstage/theme                                      0.2.16
  @backstage/types                                      1.0.0
  @backstage/version-bridge                             1.0.1
✨  Done in 3.71s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Alright, am I understanding it correctly that the generated file contained `$text: https://github.com/<org>/<repo>/blob/main/specs/<file>.yaml` - that it was a full URL, not relative? Yet, at the time that the processor tried to read it, it seems it had been mangled to `https://github.com/<org>/<file>.yaml `?

**Comment by freben** [comment]
For reference, the active parts of the code [are here](https://github.com/backstage/backstage/blob/cc08d60324668ea6c029907d3baf9da50f260849/plugins/catalog-backend/src/modules/core/PlaceholderProcessor.ts#L135). You see the `textPlaceholderResolver` right below that. Tracing the code a bit, you find that it'll ultimately call `integrations.resolveUrl(url, base)`, where the first argument is the URL mentioned above, and the second argument is whatever's in `location.target`. So I think what happens is, at that point the target is a glob URL instead of the actual URL of the file. Then the [implementation of the resolver](https://github.com/backstage/backstage/blob/cc08d60324668ea6c029907d3baf9da50f260849/packages/integration/src/github/GithubIntegration.ts#L54) probably borks out. But it's yet to be confirmed; I'm not in a position to properly reproduce and debug right now.

**Comment by darrenyung** [comment]
Hi @freben , apologies for the late response. After countless hours of debugging and running unit tests, I figured out the code was doing perfectly ok. What happened was the engineer has actually changed the file name of the generated files containing the catalogues.

Somehow the discovery was still referencing the old name. The app has gone through several restarts, I'm wondering why is the github discovery processor still processing the old version? I've checked twice on the main default repo, it does not contain any of the old names.

```
[2m2023-03-15T11:17:41.119Z[22m [34mcatalog[39m [33mwarn[39m Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location https://github.com/org/repo/blob/-/specs/openapi.yaml, Error: Incorrect URL: https://github.com/org/repo/tree/-/openapi.yaml, Error: Invalid GitHub URL or file path [36mtype[39m=plugin [36mentity[39m=api:default/open-api-name
[36mlocation[39m=url:https://github.com/org/remote-repo/tree/master/backstage/backstage.<team>.catalog-info.yaml
```

**Comment by darrenyung** [comment]
Hi @freben , unfortunately no. I've fixed the WIP branch import with the filter but somehow it is still referencing the deleted (old file name) files in the master branch as I'm still seeing the PlaceholderProcessor errors.

**Comment by darrenyung** [comment]
Hello. 

Just providing an update as I'm going to move this ticket to closure. The engineer responsible was performing refactoring on his repo as part of the development lifecycle. Thus, this changed the way it produces the **catalog-info.yaml** files getting generated.

After taking a look at the database, I noticed the **refresh_state** table still locked and looking at the old directory, thus causing a lot of noise during the lookup. This added to the performance degradation during the entity import cycle to go beyond the timeout set in the app. I've manually removed those entries so we could gain back the performance manually on the database and have extended the timeout just to cope with the volume of data that my organization has loaded into Backstage.

Would appreciate if there's some ways we could tackle or advise on how to handle this. I noticed the manual import vs discovery import also produced a warning log output of Location Conflict during refresh. 

CC: @freben

**Comment by darrenyung** [comment]
Hi @mscam ,

For my case, I'd run the following checklist

1. Does the catalog-file exists in the expected location? If so, using your lower envs, can you manual import it via `catalog-import` page? Any errors?
2. Is there logs containing the following text `Error: Incorrect URL`? If so, you might have the same problem as I do where the location has changed but the refresh state is still stuck with the old one. To solve this, you'll have to manually delete the entries via a script.
3. What is your timeout set for the Catalog Processor? If the content has grown, it might take longer to process. 

Hope this helps.

**Comment by mscam** [comment]
1.  yes, the catalog exists in the expected location. when importing that using catalog import, only a location entity is added. 
2. no errors with incorrect url
3. timeout is set to 5 minutes

Thanks @darrenyung I will try to increase timeout. maybe 5 mins aren't enough... what's the value you have set? we are talking about roughly 174 catalog entites to be imported. Some are referencing APIs and none of them are missing

**Comment by darrenyung** [comment]
I'm not near my work pc atm but from memory, I've increased mine to 1 hour with frequency level at 1 hour and 10 minutes.

In terms of data, I have nearly triple the amount that you have (including APIs and Documentations). I haven't gone into multi events for processing yet. IIRC, its the latest feature that is available for implementation.

**Comment by mscam** [comment]
@mscam I tried to increase frequency and timeout values as you suggested, 25 catalog entities missing are still missing 😭  I will double check the logs again while using catalog-import

**Comment by darrenyung** [comment]
@mscam - Perhaps try manual import one of the missing entity. I don't think I ever recall a catalog going missing. Existing ones are usually orphaned if the original location has changed. The sync is one way and the deletion has to be explicit by the user as designed.

**Comment by mscam** [comment]
@darrenyung the problem has been fixed. missing catalog entities are back. we had both GitLab and AWS s3 discovery enabled, that's probably why. Increasing timeout and setting different values for each made catalog import working again

**Comment by darrenyung** [comment]
@mscam - That's great! I was curious about the issue and was about to suggest another possibility in the config that I experienced when my org had templates in different repos and we had to add another rule for Location as it was importing the templates.

Good that you have resolved the issue.

**Comment by mscam** [comment]
definitely yes. I would try providing a Location entity that acts as an "index" for all service entities 💯 maybe it helps
