### ISSUE TITLE
🚀 Feature: Update code blocks TypeScript-React code blocks from `diff` to `tsx`

### ISSUE THREAD

**Issue by schultzp2020** [backstage/backstage#16160]
### 🔖 Feature description

Change the TypeScript-React code blocks from `diff` to `tsx` with the built-in [line highlighting](https://docusaurus.io/docs/markdown-features/code-blocks#line-highlighting) support from Docusaurus. 

Note: This feature can be implemented before the migration to Docusaurus 2.X is complete (`microsite-next`) using the [metadata string property](https://docusaurus.io/docs/markdown-features/code-blocks#highlighting-with-metadata-string); however, the highlighted lines will not be rendered until the migration is complete. 

References: https://github.com/backstage/backstage/issues/12019

### 🎤 Context

Currently, the majority of the TypeScript code blocks use the `diff` language to show what has been added in the code. However, by using a `diff` it's very difficult for users to copy and paste the necessary code block to add. 

Example
````md
```diff
+ import { githubAuthApiRef } from '@backstage/core-plugin-api';
+ import { SignInPage } from '@backstage/core-components';

 const app = createApp({
   apis,
+  components: {
+    SignInPage: props => (
+      <SignInPage
+        {...props}
+        auto
+        provider={{
+          id: 'github-auth-provider',
+          title: 'GitHub',
+          message: 'Sign in using GitHub',
+          apiRef: githubAuthApiRef,
+        }}
+      />
+    ),
+  },
   bindRoutes({ bind }) {
```
````

would become

````md
```tsx {1-2,6-19}
import { githubAuthApiRef } from '@backstage/core-plugin-api';
import { SignInPage } from '@backstage/core-components';

const app = createApp({
  apis,
  components: {
    SignInPage: props => (
      <SignInPage
        {...props}
        auto
        provider={{
          id: 'github-auth-provider',
          title: 'GitHub',
          message: 'Sign in using GitHub',
          apiRef: githubAuthApiRef,
        }}
      />
    ),
  },
  bindRoutes({ bind }) {
```
````

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Sounds cool, i like it! Thanks for pointing it out. Maybe best to hold off until they actually render though, so that we don't start editing code and the lines get out of sync etc because they aren't visible yet.

**Comment by jhaals** [comment]
@schultzp2020 we are now on the latest version so it would be fantastic with some help updating the relevant documentation 👏

**Comment by schultzp2020** [comment]
@jhaals I will start working on a pr today.

**Comment by schultzp2020** [comment]
Any ideas why I can't run `yarn --cwd microsite-next/ start` on Windows 10 or Fedora through WSL? Here's my error.

```log
Error: Can't resolve '/img/logo.svg' in 'C:\backstage\microsite-next\src\css'
Error: Can't resolve '/img/logo.svg' in 'C:\backstage\microsite-next\src\css'
-- inner error --
Error: Can't resolve '/img/logo.svg' in 'C:\backstage\microsite-next\src\css'
Generated code for C:\backstage\microsite-next\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[6].use[1]!C:\backstage\microsite-next\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[6].use[2]!C:\Programming\Work\backstage\microsite-next\src\css\customTheme.css
client (webpack 5.75.0) compiled with 2 errors
Watchpack Error (initial scan): Error: ENOTDIR: not a directory, scandir 'C:\backstage\microsite-next\static'
```
