### ISSUE TITLE
🚀 Feature: Customize catalog's EntityLayout component's header

### ISSUE THREAD

**Issue by kavispires** [backstage/backstage#16173]
### 🔖 Feature description

Extend EntityLayout with props that allow header customization

### 🎤 Context

At LinkedIn, we use Backstage's Catalog to catalog data on our numerous products (components). We tailor the entity pages to meet each product's user requirements by customizing their Cards. While we have complete control over the EntityPage content, the [EntityLayout](https://github.com/backstage/backstage/tree/master/plugins/catalog/src/components/EntityLayout)'s Header displays information that is not relevant to our ecosystem. It would be more beneficial if we could customize the information in the Header.

<img width="339" alt="EntityLayoutHeader-example" src="https://user-images.githubusercontent.com/10953022/216729449-a9aee0e8-2f82-48b7-9bb0-476242df8539.png">

For instance, the "Owner" field is irrelevant to our pages as components do not have a single owner. The same goes for the lifecycle, unregistering, and inspecting the entity information on the right side of the header, which does not provide any value to our users.

The EntityLayout already provides two props [UNSTABLE_extraContextMenuItems](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityLayout/EntityLayout.tsx#L180) and [UNSTABLE_contextMenuOptions](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityLayout/EntityLayout.tsx#L181) that allow us to make some changes to the header, but it doesn't let us replace the information not relevant to us.

### ✌️ Possible Implementation

I suggest the implementation of a prop, such as "extra" or "action", similar to MaterialUI's CardHeader. When present, this prop would replace the entire right side of the Header with new information.

```
<EntityLayout action={<CoolComponent />}>
    <EntityLayout.Route path="/" title="Overview">
      <OverviewContent />
     ...
```

Additional props to make it even more useful are possible. For example, in addition to `action`, we have:
- `override` - a boolean that when `true` replaces the default right side content with the extra prop content otherwise it adds the content between the lifecycle and the context menu.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
First a bit of background that may be of interest: There is a steady stream of request for customizing bits and pieces all over the default experience. We've needed a proper, solid, consistent, scalable strategy for that for a long time, but haven't had the time to formalize one yet. In the vacuum that follows, various little sprawling point-efforts have been made to fill in the most egregious gaps, often in the form of complex props that need to be drilled through layers. This quickly gets unmaintainable.

What we've been saying in general, when pushing back, is that we encourage adopters to make entirely new custom components instead. Hopefully we export enough of the underlying atoms, such that composing your own wrapper around them isn't prohibitively complex. I suppose you'd be able to take that approach for your own use case too.

We have in the back of our minds to try to sit down and design a _real_ formal system for how to inject behaviors and styles in a coordinated way basically anywhere, without having to resort to case-by-case hacks. But it's not there yet.

That all being said, I think what you suggest is one of the best approaches in an imperfect world. A prop that replaces an entire piece of the experience, with no props being passed through so there's no real contract, instead being in the form of raw JSX. I like that you make it about the _entire_ right hand side. Then the only contact surface between the container and the contents is, "you are in a flex box stacked to the right". Which is pretty slim.

I'd prefer to skip the `override`. It is a simpler contract if all you can do is to replace everything or nothing. That can then be combined with exporting a `DefaultEntityLayoutActions` component, which MAY then offer additional lightweight prop-adaptations. It's much easier to keep _that_ adaptation surface limited and be able to draw a line in the sand where we can say "no, that suggested new adaptation is one step too far, just make your own action thingy instead". And then we export for example the owner/lifecycle component and the three-dots menu as well, as components, that you can piece together in your own wrapper.

**Comment by kavispires** [comment]
@freben I created a PR. (above^ #16629)  with the change. I'd like to have your eyes on it to see if the approach is okay. It was simpler than I thought as it didn't require any new special types, just like you suggested, an "override" for all or nothing. Please let me know.

Thanks!
