### ISSUE TITLE
🚀 Feature: Optionally adjust the max number of boxes in OwnershipCard 

### ISSUE THREAD

**Issue by belech** [backstage/backstage#16233]
### 🔖 Feature description

Right now the OwnershipCard of the org-plugin only can show a maximum number of 6 boxes - we'd like to be able to show more or even all boxes of different accumulated ownerships. 

### 🎤 Context

`<EntityOwnershipCard showAll/>`

`<EntityOwnershipCard showMax='8' />`

### ✌️ Possible Implementation

Putting the given props from above into something like this here:
https://github.com/backstage/backstage/blob/master/plugins/org/src/components/Cards/OwnershipCard/useGetEntities.ts#L193

showMax defaulting to 6

```
const topN = showAll ? counts.sort((a, b) => b.count - a.count) : counts.sort((a, b) => b.count - a.count).slice(0, showMax);;
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Yep makes sense! 👍  I think keep it a single prop with the ability to just use `showMax={Infinity}`

**Comment by shubhamjajoo** [comment]
Can I pick this issue ?
Created PR as well : https://github.com/backstage/backstage/pull/17098

**Comment by benjdlambert** [comment]
Closing as completed in #17098
