### ISSUE TITLE
🚀 Feature: Add an option to automatically include built in actions when adding a custom scaffolder actions

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [backstage/backstage#16242]
### 🔖 Feature description

This is more of an enhancement than a feature request. This feature would allow users to include built in scaffolder actions when defining a custom action. This will be done via an extra option in the `createRouter` method of the `scaffolder-backend`.

### 🎤 Context

Right now, if I am defining a custom scaffolder action and want to include the built-in actions too, I will need to
```ts
const builtInActions = createBuiltinActions({
  integrations,
  catalogClient,
  config: env.config,
  reader: env.reader,
});

const actions = [...builtInActions, myCustomAction()];

return await createRouter({
  actions,
  logger: env.logger,
  config: env.config,
  database: env.database,
  reader: env.reader,
  catalogClient,
  identity: env.identity,
});
```

This seems a bit redundant to me. Instead of calling `createBuiltinActions`, which takes in most of the options taken by `createRouter`, one can pass an extra option to `createRouter` which then handles the build in actions accordingly.

### ✌️ Possible Implementation

Imagine if we passed an option like `includeBuiltinActions: true`
```ts
return await createRouter({
  actions,
  includeBuiltinActions: true,
  logger: env.logger,
  config: env.config,
  database: env.database,
  reader: env.reader,
  catalogClient,
  identity: env.identity,
});
```
And in the `router.ts` at 
https://github.com/backstage/backstage/blob/0870577bd4ac6922ff999a0207c2aed71512d499/plugins/scaffolder-backend/src/service/router.ts#L230-L240
we can add something like the following
```ts
if (includeBuiltinActions) {
  actionsToRegister.push(
    ...createBuiltinActions(
      integrations,
      catalogClient,
      reader,
      config,
      additionalTemplateFilters,
      additionalTemplateGlobals,
    ),
  );
}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by andrewthauer** [comment]
I agree the registration of custom actions might be a bit redundant. However, one advantage of the current pattern is you could  override an existing builtin action. This gives the integrator full control over what is used for better or worse.

**Comment by SayakMukhopadhyay** [comment]
> but this couples the 2 params behaviourally which may be undesirable?

Yeah, that is indeed my only gripe. I would even prefer if I can generate the builtin actions by a function call without passing parameters but I don't see how that can be done. I really don't want to pass the same parameters 2 times in functions that are related to each other.

**Comment by andrewthauer** [comment]
I haven't been following the new backend system work in too much detail, but it's possible this could be done different as I recall there is the concept similar to the `apiRef` which might make it more feasible to have a factory function that takes less arguments.

**Comment by Rugvip** [comment]
Yep I think it makes sense to leave this for the shape of the scaffolder plugin in the new system tbh.

**Comment by SayakMukhopadhyay** [comment]
> shape of the scaffolder plugin in the new system tbh.

Do you mean next release of scaffolder?

**Comment by Rugvip** [comment]
@SayakMukhopadhyay nah the new backend system, there will be more info about that next week

**Comment by Pike** [comment]
Personally, I had a good time when I removed most of the built-in actions from our installation. For the most part, because the installed actions page is tricky enough to use as is. And limiting that to the actions that are actually useful is good. We also ordered the actions, so that they have a flow, which doesn't work if you just concat upstream and downstream ;-) .

My goal was to pay a little on the setup cost to boost DX for template authors. Not that I got more template authors yet ;-)

**Comment by SayakMukhopadhyay** [comment]
> @SayakMukhopadhyay nah the new backend system, there will be more info about that next week

@Rugvip Is this new backend system getting tracked somewhere (as an issue or PR)? I would like to follow up with it. Maybe attach this issue there.

**Comment by SayakMukhopadhyay** [comment]
Not stale

**Comment by freben** [comment]
@SayakMukhopadhyay The backend system as such is in place since some time back. Now it's up to each plugin to design their interaction surfaces around the new backend system. For the scaffolder specifically, it has this [extension point](https://backstage.io/docs/backend-system/architecture/extension-points):

https://github.com/backstage/backstage/blob/54f741d1f0229f0b7026f485d48307a8cb33ba8f/plugins/scaffolder-node/src/extensions.ts#L25

You'll find that in its current basic form, it can _only_ do exactly what you wanted, which is to add actions on top of the default ones.

I think this issue might be worth closing, possibly replacing it with a new issue or PR adjusting the extension point if it is found to be insufficient.

**Comment by Pike** [comment]
I agree on closing this one. I'd like to have the option to define the actually relevant actions, and I also see value in being able to order them. That said, I think ordering is just a cheap way of discoverability and search.

**Comment by SayakMukhopadhyay** [comment]
> @SayakMukhopadhyay The backend system as such is in place since some time back. Now it's up to each plugin to design their interaction surfaces around the new backend system. For the scaffolder specifically, it has this [extension point](https://backstage.io/docs/backend-system/architecture/extension-points):

@freben Not sure how to use that extension point in my app though. I can see that https://github.com/backstage/backstage/blob/e0506af8fc54074a160fb91c83d6cae8172d3bb3/plugins/scaffolder-backend/src/ScaffolderPlugin.ts exists which uses the extension point. Right now, I am using `createRouter` to handle scaffolder just like how the `create-app` generated

```ts
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const catalogClient = new CatalogClient({
    discoveryApi: env.discovery,
  });
  const integrations = ScmIntegrations.fromConfig(env.config);

  const builtInActions = createBuiltinActions({
    integrations,
    catalogClient,
    config: env.config,
    reader: env.reader,
  });

  const actions = [...builtInActions, runCustomAction({ config: env.config })];

  return await createRouter({
    actions,
    logger: env.logger,
    config: env.config,
    database: env.database,
    reader: env.reader,
    catalogClient,
    identity: env.identity,
    permissions: env.permissions,
  });
}
```

But I see that `ScaffolderPlugin.ts` has an implementation of the `ScaffolderActionsExtensionPoint` interface and is exposing a `scaffolderPlugin` method which calls the `createRouter`. And on digging deeper I find that this `scaffolderPlugin` method is getting called in `BackendNext` package.

Do I need to use `BackendNext` for this?
