### ISSUE TITLE
🐛 Bug Report: Backstage transpiles already transpiled GLSL (OpenGL Shading Language) files

### ISSUE THREAD

**Issue by doganyazar** [backstage/backstage#16243]
### 📜 Description

Webpack configuration transpiles the already transpiled glsl files instead of ignoring them. 

Running into this issue when trying react-sigma library. It uses sigma.js under the hood which in turn uses WebGL to render the graphs. For example, 
yarn build gets this file `node_modules/sigma/rendering/webgl/shaders/node.fast.frag.glsl.js` and prints 
`555 B      dist/static/node.fast.frag.glsl.62494f1a..js`

### 👍 Expected behavior

Webpack shall exclude glsl files.

### 👎 Actual Behavior with Screenshots

<img width="491" alt="Screenshot 2023-02-08 at 11 04 47" src="https://user-images.githubusercontent.com/1618686/217504252-f3e8d386-18ef-4d42-93b2-87cd2ed4e050.png">

### 👟 Reproduction steps

1. Install react-sigma: https://sim51.github.io/react-sigma/docs/start-installation
2. Create and render a basic component using react-sigma: https://sim51.github.io/react-sigma/docs/start-setup

In the browser this error will be shown:
```
Error
loadShader: error while compiling the shader:
ERROR: 0:1: '/' : syntax error

/static/node.fast.frag.glsl.5eb46b11..js
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Thank you for reporting! 👍 

Fixed in #16306
