### ISSUE TITLE
🔌 Plugin: Octopus Deploy

### ISSUE THREAD

**Issue by jmezach** [backstage/backstage#16241]
### 🔖 Summary

Octopus Deploy is a popular tool in the .NET ecosystem for continuous deployment, but it can also deploy a host of other types of projects. It has been around for quite some time now and we've been using it at our company for a long time.

I think that as a starting point a Backstage plugin for Octopus would allow you to see:
- Which versions of a particular project (setup through an annotation probably) are deployed in which environment(s) (much like Octopus Deploys own dashboard)
- See the current state of an active deployment (ie. if somebody is currently deploying a version to an environment it would be nice to see that in Backstage)

I guess this could be expanded in the future to also support deploying a version to an environment straight from Backstage.

### 🌐 Project website (if applicable)

https://octopus.com/

### ✌️ Context

As Octopus Deploy has been built with an API-first approach you can do pretty much everything in Octopus Deploy through its API. I guess that should make it relatively easy to developed a Backstage plugin for it.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jmezach** [comment]
I've created a very rough initial version of such a plugin that currently looks like this:

![Screenshot 2023-02-14 at 16 02 02](https://user-images.githubusercontent.com/1225489/218778330-3361f66e-a66c-4db5-a23d-842cc6c16348.png)

It basically shows the status of deployments for the last couple of releases across the different environments. If anyone's interested I'd be more than happy to make the source code available.

**Comment by toftstade** [comment]
I'm interested!

**Comment by freben** [comment]
done!
