### ISSUE TITLE
🐛 Bug Report: ADR plugin does not render the images

### ISSUE THREAD

**Issue by athifongoqa** [backstage/backstage#16255]
### 📜 Description

Within a registered service's ADR folder on GitHub (`./docs/adr`), alongside my markdown files, I have a folder that I use to render images in the markdown. When viewing the ADRs from my own running Backstage instance, the images are not rendered. 

### 👍 Expected behavior

All images used within the ADR markdown files are to be rendered the same on GitHub and on my Backstage ADR plugin tab.

### 👎 Actual Behavior with Screenshots

The ADR has an image provided (shown in 2nd picture), but it doesn't get rendered on Backstage.

<img width="1260" alt="Bildschirm­foto 2023-02-08 um 14 16 44" src="https://user-images.githubusercontent.com/113907694/217541208-e8fa2bc4-1a9f-4eb1-8d06-5773d6296005.png">

<img width="973" alt="Bildschirm­foto 2023-02-08 um 14 18 00" src="https://user-images.githubusercontent.com/113907694/217541216-d238042a-364f-49e0-8cfe-e7c62f664bc8.png">

### 👟 Reproduction steps

- Install the ADR-plugin on your Backstage instance
- Register a service to the catalog with a `./docs/adr` folder
- Within this folder, create a folder with images and reference an image in an ADR markdown file. (`./docs/adr/images`)
- Make sure the image is rendered on GitHub
- Navigate to the service's ADR tab on your Backstage instance
- Click on the respective sub-page which should have an image

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dweber019** [comment]
We have similar issues when using BitBucket server. The Image link will actually point to the correct file on BitBucket but as the link isn't requesting the file as raw it can't be displayed.

Additionally it's strange that link in the ADR are pointing to BitBucket and not TechDocs.

**Comment by efenner-cambia** [comment]
I still think this would be useful to have implemented as an enhancement

**Comment by sblausten** [comment]
We've implemented solutions to two of our plugins that could be used here also if anyone has time - https://github.com/RoadieHQ/roadie-backstage-plugins/pull/777/files  
https://github.com/RoadieHQ/roadie-backstage-plugins/pull/784/files#diff-a544f89199f32545eec1687460527ab610144d47fcdd60de7257d0267d5c8920
