### ISSUE TITLE
🐛 Bug Report: 401s when making requests to GitHub with Multiple GitHub Integrations

### ISSUE THREAD

**Issue by AndrewZurn** [backstage/backstage#16260]
### 📜 Description

I have two GitHub integrations setup to query two different Organizations that our company runs.
```
integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-ORG-ONE-credentials.yaml
        - $include: github-app-ORG-TWO-credentials.yaml
```

When Backstage makes calls to the repos that are in the `ORG-ONE` Organization, calls succeed as expected. However, when it attempts to make calls to any repos that are contained in the `ORG-TWO` Organization, calls fail with a 401/Unauthorized. If remove the first organization credentials from the list above, calls succeed.

I was able to track down the potential issue (I believe there was a similar issue noted as an issue on here, but cannot find it at the moment) to an issue in @backstage/integration where it it will look at the two credentials that are setup, and the first one that is not `null` is what will be used, regardless if an `accessToken` is null within it. This may not be the real fix to be honest, but does alleviate the symptom and fixes my issue.

Here is the whole of the fix that I created as a local patch:
```
az0916 $ cat patches/@backstage+integration+1.4.2.patch
diff --git a/node_modules/@backstage/integration/dist/index.cjs.js b/node_modules/@backstage/integration/dist/index.cjs.js
index a85e29a..9227328 100644
--- a/node_modules/@backstage/integration/dist/index.cjs.js
+++ b/node_modules/@backstage/integration/dist/index.cjs.js
@@ -1354,7 +1354,7 @@ class GithubAppCredentialsMux {
         )
       )
     );
-    const result = results.find((resultItem) => resultItem.credentials);
+    const result = results.find((resultItem) => resultItem.credentials.accessToken);
     if (result) {
       return result.credentials.accessToken;
     }
```

Here, `resultItem.credentials` does not check if the credential actually has a valid `accessToken` within it, and upon checking to see if `accessToken` is truthy it'll allow calls to each organization to complete as expected (get a 200 response and get the needed repository data into Backstage). The check above should probably check to make sure `resultItem.credentials` is truthy and then check to see if `accessToken` is there to ensure we don't run into any sort of nil/undefined issues.

### 👍 Expected behavior

Backstage should be able to use the appropriate token between the two configured integrations for the organization when making calls to the GitHub API.

### 👎 Actual Behavior with Screenshots

When running with both integrations, I see these errors in the logs for ORG-TWO.

![image](https://user-images.githubusercontent.com/2126119/217613236-5a1ee94f-b30e-444e-8427-c25ccde7b7ed.png)

### 👟 Reproduction steps

1. Setup two separate GitHub organizations as integrations.
2. Setup at least a single catalog provider that will try to read from each Organization that is configured in step one. The repos that will be scanned by these integrations should either be 'internal' or 'private'.
3. See that the first Organization's repos are pulled in.
4. See the second Organizations's repos are not pulled in and the error above is observed in the logs.

### 📃 Provide the context for the Bug.

We are unable to pull the repositories and catalogs within them for ORG-TWO.

### 🖥️ Your Environment

OS:   Darwin 21.6.0 - darwin/x64
node: v16.17.0
yarn: 1.22.19
cli:  0.22.1 (installed)
backstage:  1.10.1

Dependencies:
  @backstage/app-defaults                          1.1.0
  @backstage/backend-app-api                       0.3.1
  @backstage/backend-common                        0.18.1
  @backstage/backend-plugin-api                    0.3.1
  @backstage/backend-tasks                         0.4.2
  @backstage/catalog-client                        1.3.0
  @backstage/catalog-model                         1.1.5
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.1
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.4.0
  @backstage/core-components                       0.12.3
  @backstage/core-plugin-api                       1.3.0
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.9
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.8.14
  @backstage/plugin-app-backend                    0.3.41
  @backstage/plugin-auth-backend                   0.17.4
  @backstage/plugin-auth-node                      0.2.10
  @backstage/plugin-catalog-backend-module-github  0.2.4
  @backstage/plugin-catalog-backend                1.7.1
  @backstage/plugin-catalog-common                 1.0.10
  @backstage/plugin-catalog-graph                  0.2.26
  @backstage/plugin-catalog-import                 0.9.4
  @backstage/plugin-catalog-node                   1.3.2
  @backstage/plugin-catalog-react                  1.2.4
  @backstage/plugin-catalog                        1.7.2
  @backstage/plugin-events-node                    0.2.2
  @backstage/plugin-github-actions                 0.5.14
  @backstage/plugin-org                            0.6.4
  @backstage/plugin-permission-backend             0.5.16
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.4
  @backstage/plugin-permission-react               0.4.9
  @backstage/plugin-proxy-backend                  0.2.35
  @backstage/plugin-scaffolder-backend             1.10.1
  @backstage/plugin-scaffolder-common              1.2.4
  @backstage/plugin-scaffolder-react               1.0.1
  @backstage/plugin-scaffolder                     1.10.1
  @backstage/plugin-search-backend-module-pg       0.5.2
  @backstage/plugin-search-backend-node            1.1.2
  @backstage/plugin-search-backend                 1.2.2
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.4.0
  @backstage/plugin-search                         1.0.7
  @backstage/plugin-tech-radar                     0.6.0
  @backstage/plugin-techdocs-backend               1.5.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.9
  @backstage/plugin-techdocs-node                  1.4.5
  @backstage/plugin-techdocs-react                 1.1.2
  @backstage/plugin-techdocs                       1.4.3
  @backstage/plugin-user-settings                  0.6.2
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.4
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
✨  Done in 2.60s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Are you using the `allowedInstallationOwners` configuration? I think the logic might be a bit off there currently, where specifying that option with multiple providers will break the lookup. I think there's a risk you proposed fix will break the fallback to access public repos, but as long as we make sure the support that I think something like your fix is the way to go 👍

**Comment by AndrewZurn** [comment]
@Rugvip - we are indeed using `allowedInstallationOwners`.

I'll have to dig a bit, but I'm curious about the risk to breaking public repo access. I'm pretty naive to the other inner workings around this particular function, but it seems like since we are returning `result.credentials.accessToken` a few lines down from the check, that we'd want said `accessToken` to not be null/undefined.

I'll see what I can do about grabbing the latest from this repo, making the small tweak (including the check on `.credentials` first, and cross my fingers no tests break (and try to add one as well 😄).

**Comment by AndrewZurn** [comment]
Following up on this - looks like this may have been fixed in this commit: https://github.com/backstage/backstage/commit/5d12393bc9a04c57e277cc7c05892a7ec0601057
