### ISSUE TITLE
🚀 Feature: Make nunjucks configureable, such as trimBlocks or lstripBlocks

### ISSUE THREAD

**Issue by aitchjoe** [backstage/backstage#16267]
### 🔖 Feature description

This feature would allow users to config nunjucks such as [trimBlocks or lstripBlocks](https://mozilla.github.io/nunjucks/api.html#configure).

### 🎤 Context

Right now, if I am defining a template file:

```
option 1
{% if values.option2NotEmpty %}
option 2
{% endif %}
option 3
```

when option 2 is empty, what I want is:

```
option 1
option 3
```

but not:

```
option 1

option 3
```

Nunjucks [trimBlocks](https://mozilla.github.io/nunjucks/api.html#configure) config can "_automatically remove trailing newlines from a block/tag_", but I did not find how to config this via backstage. From [SecureTemplater.ts](https://github.com/backstage/backstage/blob/v1.10.1/plugins/scaffolder-backend/src/lib/templating/SecureTemplater.ts#L32):

```
  const env = module.exports.configure({
    autoescape: false,
    tags: {
      variableStart: '\${{',
      variableEnd: '}}',
    },
  });
```

Backstage change nunjucks `autoescape` config from default `true`, but leave `trimBlocks` to default `false`, and no more config on the followed codes (`additionalTemplateGlobals` is for [another purpose](https://mozilla.github.io/nunjucks/api.html#addglobal)). I have hacked "node_modules/@backstage/plugin-scaffolder-backed/dist/index.cjs.js" which embedded SecureTemplater.ts:

```
  const env = module.exports.configure({
    autoescape: false,
    ......
    trimBlocks: true,
  });
```

then the result is what I want, so I am sure this config works.

### ✌️ Possible Implementation

There are some options:

* Like [make nunjucks' globals configureable](https://github.com/backstage/backstage/pull/13704), make nunjucks configureable.
* Set node env `NUNJUCKS_TRIM_BLOCKS=true` and change SecureTemplater.ts to use this, I am not sure that backstage can use node env var in SecureTemplater.ts?
* Like nunjucks [whitespace control](https://mozilla.github.io/nunjucks/templating.html#whitespace-control) (`{{-`), we need some signs to "trim blocks" at the block/tag scope. I think this is more flexible than global scope config, of course this is not backstage but nunjucks issue, I did not find this solution at [nunjucks](https://github.com/mozilla/nunjucks/issues/) or [jinja](https://jinja.palletsprojects.com/en/3.1.x/templates/#whitespace-control).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by SayakMukhopadhyay** [comment]
I was having a related issue with the `{% raw %}` tag. This tag doesn't accept whitespace controls and hence I can't write these tags in their own lines at all. I was discussing this on the Backstage Discord server, so if you want to join that conversation you can go here https://discord.com/channels/687207715902193673/1072187171634688060/1072187171634688060

**Comment by benjdlambert** [comment]
Thinking that this is probably something that we would want to expose as an option to the `createFetchTemplate` action and pass it through there rather than it being something on the router. Maybe it doesn't make sense to apply these options to the templating in the `template.yaml` for instance.

**Comment by krisdock** [comment]
this would be useful 😃

**Comment by kissmikijr** [comment]
> Thinking that this is probably something that we would want to expose as an option to the `createFetchTemplate` action and pass it through there rather than it being something on the router. Maybe it doesn't make sense to apply these options to the templating in the `template.yaml` for instance.

@benjdlambert Do you still think this would be an acceptable way to add this feature ? I'd like to add it, it would be quite nice to have this available
