### ISSUE TITLE
🐛 Bug Report: special characters not supported in tags

### ISSUE THREAD

**Issue by Kris-B** [backstage/backstage#16278]
### 📜 Description

In catalog entities, tags can only be a string that is sequences of [a-z0-9+#] separated by [-] is currently supported. This is very limitating as special characters (like accents, umlauts, ...) are commonly used in many not english contexts.

### 👍 Expected behavior

Special characters should be supported.

### 👎 Actual Behavior with Screenshots

Policy check failed for api:default/gestion-authentification-anca; caused by Error: "tags.0" is not valid; expected a string that is sequences of [a-z0-9+#] separated by [-], at most 63 characters in total but found "sécurité". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md

### 👟 Reproduction steps

Example:

```
metadata:
    name: x-y-z
    title: x y z 
    description: my api des
    tags:
      - sécurité
    ...
 ```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
These are just the default rules; you [can change them](https://github.com/backstage/backstage/blob/57c393e1596332ecea05b400e1404f1d3cac55b5/plugins/catalog-backend/src/service/CatalogBuilder.ts#L278).

**Comment by Kris-B** [comment]
Thanks for your answer.

This can certainly be implemented in the deployed version on my side. But in fact, I would have preferred my request to be taken into account in the Backstage code base.

I find that this difference in treatment with other displayed fields (title, description, lifecycle, owner, etc.) brings an inconsistency, which does not seem justified.

This constraint is an irritant in my context which favors the local language, and I don't think I'm the only one in this case.

Support for special characters for tags as standard in Backstage would be greatly appreciated.

**Comment by benjdlambert** [comment]
@Kris-B, yeah I think your request has some validity, I guess for me it also opens up concerns around if things that process tags, and maybe even our catalog internally, do they all support special characters? Thinking about charsets for databases, and maybe things that ingest the tags like search etc? 

Another question I have is what do you think would be a good range of characters to support? I think it's hard to come up with a list that we can be sure just works™️ everywhere apart from the one that we already have.

**Comment by Kris-B** [comment]
@benjdlambert actually I've no idea about technical impacts nor what would be a good range of characters to support.

Personally I'm only interested in alphabetical special characters like:
![image](https://user-images.githubusercontent.com/4072515/233993798-656cac85-0f6d-4e57-9d9e-ce647f012467.png)

But ideally the same character set shoud be used for all displayed fields: title, description, lifecycle, owner, ... and tags.

Sorry, not sure that I can help more than that.
