### ISSUE TITLE
🐛 Bug Report: <Deprecation and vulnerability warning for techdocs/cli>

### ISSUE THREAD

**Issue by mustafazeya** [backstage/backstage#16277]
### 📜 Description

When running `sudo npm install -g @techdocs/cli` to install etchdocs/cli we get multiple warnings.

### 👍 Expected behavior

It shouldn't throw any warning about severe vulnerabilities and the vulnerabilities should be fixed

### 👎 Actual Behavior with Screenshots

Output of  `sudo npm install -g @techdocs/cli`
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.[23](https://github.com/flysas-cdx-dev/builders-library/actions/runs/4134226235/jobs/7145103895#step:5:24).3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 916 packages, and audited 917 packages in 43s

76 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

```

### 👟 Reproduction steps

When running `sudo npm install -g @techdocs/cli` to install etchdocs/cli we get multiple warnings.

### 📃 Provide the context for the Bug.

We are running CI/CD to build techdocs and these vulnerabilities warnings are popping up during installation of techdocs/cli

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Ping @agentbellnorm for visibility here too
