### ISSUE TITLE
🚀 Feature: CI on validating catalog entities

### ISSUE THREAD

**Issue by zinizhu** [backstage/backstage#16284]
### 🔖 Feature description

A CI workflow to validate the catalog entities declared in a GitHub repo. The validation should cover:
* if the entity declaration is vallid
* if the entity includes the required fields like `metadata`
* if the entities referenced in another entity exist

### 🎤 Context

We use a GitHub repo to host all the software catalog entities. When updating an entity, it's hard to discover all the places it is referenced and update the refs manually. It will be nice if there's a CI workflow that can catch this error ahead before users hit a 404 error in Backstage UI.

### ✌️ Possible Implementation

I am working on a GitHub Action that parses all the yaml documents and collect all the entities declared in the repo. Then the action will collect all the entities that are referenced by others and check if they really exist.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sennyeya** [comment]
For your first two questions, this work should already exist in the catalog (assuming your CI system has access to your catalog), see https://github.com/backstage/backstage/issues/11179. 
For the third question, that seems like a hard problem, especially around desync/entity doesn't exist yet. I'm not sure there's a ready solution that scales well and works for other systems.

**Comment by zinizhu** [comment]
@sennyeya Thanks for pointing out the validation endpoint, that's very useful!

For the third point, I agree with that. I guess I will just write some scripts to satisfy the needs of our own org for now.
