### ISSUE TITLE
🐛 Bug Report: Icon for New Relic Dashboard plugin broken on plugins page

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#16307]
### 📜 Description

Noticed on the plugins page, the icon for the New Relic Dashboard is broken.

https://backstage.io/plugins

### 👍 Expected behavior

Icon should display.

### 👎 Actual Behavior with Screenshots

<img width="345" alt="image" src="https://user-images.githubusercontent.com/33203301/218263172-b18fb7ec-cd09-4362-83ba-b4cf6d0f81d4.png">

### 👟 Reproduction steps

Click https://backstage.io/plugins, scroll down to New Relic Dashboard plugin, see broken image! :x

### 📃 Provide the context for the Bug.

It seems to link to an image on the New Relic site which isn't there anymore:
https://newrelic.com/themes/custom/curio/assets/mediakit/NR_logo_Horizontal_Rev.svg

### 🖥️ Your Environment

Safari, latest backstage.io URL

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by adamdmharvey** [comment]
This plugin was added via https://github.com/backstage/backstage/pull/8615; might you have any insight or a new icon, @mufaddal7 ? If so, thanks!

**Comment by Sonu875** [comment]
Create a pull request : https://github.com/backstage/backstage/pull/16345

**Comment by Hemanthhari2000** [comment]
Hello, 
Has this bug been fixed? If not, I'll work on that.

**Comment by adamdmharvey** [comment]
Closing as the image isn't broken on the plugins page anymore; thx!
