### ISSUE TITLE
🐛 Bug Report: Scaffolder EntityFields use `humanizeEntityRef` for form data as an identifier

### ISSUE THREAD

**Issue by sennyeya** [backstage/backstage#16301]
### 📜 Description

While trying to work on a solution for https://github.com/backstage/backstage/issues/15987, I tried to update `humanizeEntityRef` to return `title` instead of `name`. This caused the `OwnerPicker` and `OwnedEntityPicker` to use the humanized version instead of the ID, causing weirdness when trying to standup components and during API requests.

### 👍 Expected behavior

The form should use `stringifyEntityRef` or pass an entity object through the form instead of using `humanizeEntityRef`. It should display a human readable name for the object.

### 👎 Actual Behavior with Screenshots

The form uses whatever is in the `TextField` as the form value.

### 👟 Reproduction steps

Update `humanizeEntityRef` to include non-identifier attributes. The form picks up those attributes.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Ah yep, `OwnedEntityPicker` should be updated to pass through the full entity ref in the `onChange` callback. Do you want to contribute a fix for that?

**Comment by sennyeya** [comment]
Happy to, I was already taking a look and ran into the issue of free solo entry. Basically, we're allowing any text to be entered by default. Any preference on how to go forward on that? Current thinking is just to attempt to parse it into an entity ref with the defaultKind and defaultNamespace provided by the form.

https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/EntityPicker/EntityPicker.tsx#L95
