### ISSUE TITLE
🚀 Feature: Allow hiding software template behind feature flag

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#16324]
### 🔖 Feature description

Software templates (or why not other catalog entities as well) could add feature-flag metadata field that would register a new application level feature flag that could be used to show these templates in the UI.

### 🎤 Context

Sometimes software templates are not necessarily complete and it might be useful to be able to hide these behind feature flags.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@drodil I like this, but one thing that concerns me is that FeatureFlags only hold a true or false value by default, so you would end up having a feature flag for each template. Is that too much? And anyone can turn them on or off by default.

Would maybe permissions be a better fit for this too? Maybe having them labelled as `development` or something and only being shown to the users that are in the `template-authors` group or something?

Just trying to understand the options here and if there's any other path.

**Comment by drodil** [comment]
Depends on how many templates you need to put behind the feature flag 😄 In our case it would be just 0-2 at the same time but of course, if you have lots of those, the feature flag UI might get messy. 

Permission could be an option too though I wonder where would the configuration be for this? In the template, RBAC plugin or app config? If it's in the template, I think it would be sufficient.

**Comment by benjdlambert** [comment]
The configuration would be in the catalog plugin, as the templates are in the catalog, you'd need to add some custom rules to the builder. There's some docs here: https://backstage.io/docs/permissions/custom-rules

**Comment by drodil** [comment]
That could be an option. Would it work by adding some new field for spec or metadata, I haven't checked the permission system out yet. Also it seems that is in alpha stage, how well does it work?

**Comment by benjdlambert** [comment]
Gonna ping @vinzscam here to answer some of these questions 👍

**Comment by vinzscam** [comment]
yeah I think the using the permission framework is the best way to achieve that.
I'm gonna redirect you to a Discord thread where the same question has been answered in details 😄https://discord.com/channels/687207715902193673/935836080563966042/1067831772311715992

**Comment by drodil** [comment]
Nice, thanks for the responses. I think I can start tinkering with that. The only problem with the solution is that the permissions are set in the backend statically. Would it be possible to do something like this:

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
permission:
  read:
    - group:default/my-group
metadata:
  name: v1beta3-demo
  title: Test Action template
  description: scaffolder v1beta3 template demo
spec:
  owner: backstage/techdocs-core
  type: service
...
```
This could actually work for other entities as well 🤔

**Comment by ainhoaL** [comment]
@drodil working from a similar entity to your suggestion, I wrote a custom rule and policy to make this work for templates, hope it helps!

Template:
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: v1beta3-demo
  title: Test Action template
  description: scaffolder v1beta3 template demo
spec:
  owner: backstage/techdocs-core
  type: service
  permissions:
    delete:
      - group:default/my-group
    read:
      - group:default/team-a
      - group:default/my-group
...
```
Multiple permission types can be added there: delete, read, update and create. Of course this could be simplified if you just want to limit the read permission.

Custom rule:
```typescript
export const areClaimsInPermissionSpecRule = createCatalogPermissionRule({
  name: 'ARE_CLAIMS_IN_PERMISSION_SPEC',
  description:
    'Allows entities with the permission type that include user claims',
  resourceType: 'catalog-entity',
  paramsSchema: z.object({
    claims: z
      .array(z.string())
      .describe('Claims to check against the permission type in the entity'),
    type: z
      .enum(['read', 'create', 'delete', 'update'])
      .optional()
      .describe(
        'Permission type to check in the permission spec in the entity',
      ),
  }),
  apply: (resource: Entity, { claims, type }) => {
    if (!type) return true; // No permission type provided - allow

    if (
      !resource.spec ||
      !resource.spec.permissions ||
      !resource.spec.permissions[type]
    ) {
      return false; // Permission type not present in entity - deny
    }

    // Permission type is present in entity - check that it includes claims
    return resource.spec.permissions[type].some(allowedRef =>
      claims.includes(allowedRef),
    );
  },
  toQuery: ({ claims, type }) => {
    return {
      key: `spec.permissions.${type}`,
      values: claims,
    };
  },
});

const areClaimsInPermissionSpec = createConditionFactory(
  areClaimsInPermissionSpecRule,
);

```
This rule allows performing the permission type action (read|delete|create|update) on an entity that has that permission type in its spec and includes the claims from the user. If, for example, we don't include `permissions: read` in the entity spec, then nobody would be able to see it. This could be changed so the default is allow instead of deny.

Policy:
```typescript
class TemplatePermissionPolicy implements PermissionPolicy {
  async handle(
    request: PolicyQuery,
    user?: BackstageIdentityResponse,
  ): Promise<PolicyDecision> {
    if (isResourcePermission(request.permission, 'catalog-entity')) {
      return createCatalogConditionalDecision(request.permission, {
        anyOf: [
          {
            not:
              // Allow everyone to take actions on entities that are not templates
              catalogConditions.isEntityKind({
                kinds: ['Template'],
              }),
          },
          // Apply rule for templates to only be seen or modified by users specified in the entity
          {
            allOf: [
              catalogConditions.isEntityKind({ kinds: ['Template'] }),
              areClaimsInPermissionSpec({
                claims: user?.identity.ownershipEntityRefs ?? [],
                type: request.permission.attributes.action,
              }),
            ],
          },
        ],
      });
    }

    return { result: AuthorizeResult.ALLOW };
  }
}
```
This policy applies the custom rule only to Templates, passing the user claims and the permission action that is being requested.

**Comment by drodil** [comment]
@ainhoaL this is awesome, great work! Are you planning to push this upstream?

**Comment by vinzscam** [comment]
> @ainhoaL this is awesome, great work! Are you planning to push this upstream?

I don't think this is something ready to be included in the main repository, since adopters might have different needs.
But you can definitely take inspiration from and use it right away.
Here are some docs describing what you need to do for providing custom rules to the catalog: https://backstage.io/docs/permissions/custom-rules#provide-the-rule-during-plugin-setup

**Comment by awanlin** [comment]
@vinzscam @drodil @ainhoaL Could this be added as a contrib tutorial then? https://github.com/backstage/backstage/tree/master/contrib/docs/tutorials

**Comment by drodil** [comment]
Ah, forgot to add it to the builder with `builder.addPermissionRules`. Now the error is gone but catalog is still empty. Even if I return true from the rule directly.

**Comment by franzqueissner** [comment]
@drodil Hi, I got the same behaviour like you when trying to add a custom permission rule... were you able to solve this issue?

**Comment by drodil** [comment]
@franzqueissner yes I managed to get this working. Here is the final rule:

```ts
import { createCatalogPermissionRule } from '@backstage/plugin-catalog-backend/alpha';
import { Entity } from '@backstage/catalog-model';
import { createConditionFactory } from '@backstage/plugin-permission-node';
import { z } from 'zod';
import { JsonObject } from '@backstage/types';
import { RESOURCE_TYPE_CATALOG_ENTITY } from '@backstage/plugin-catalog-common/alpha';

const paramsSchema = z.object({
  claims: z
    .array(z.string())
    .describe('Claims to check against the permission type in the entity'),
  type: z
    .enum(['read', 'create', 'delete', 'update'])
    .optional()
    .describe('Permission type to check in the permission spec in the entity'),
});

// @ts-ignore
export const entitySpecRule = createCatalogPermissionRule({
  name: 'HAS_SPEC_PERMISSION',
  description:
    'Allows entities with the permission type that include user claims',
  resourceType: RESOURCE_TYPE_CATALOG_ENTITY,
  paramsSchema,
  apply: (
    resource: Entity,
    { claims, type }: { claims: string[]; type?: string },
  ) => {
    if (claims.length === 0) return false;
    if (!type) return true; // No permission type provided - allow

    if (
      !resource.spec ||
      !resource.spec.permissions ||
      !resource.spec.permissions.hasOwnProperty(type)
    ) {
      return true; // Permissions not in spec, allow
    }

    const permissionObj = resource.spec.permissions as JsonObject;
    const permissions = Array.isArray(permissionObj[type])
      ? (permissionObj[type] as string[])
      : [permissionObj[type] as string];
    return permissions.some((allowedRef: string) =>
      claims.includes(allowedRef),
    );
  },
  toQuery: ({ claims, type }: { claims: string[]; type?: string }) => {
    return {
      anyOf: [
        // Either spec.permissions match the claims
        {
          key: `spec.permissions.${type}`,
          values: claims,
        },
        {
          // Or spec.permissions is not set
          not: {
            key: `spec.permissions.${type}`,
          },
        },
      ],
    };
  },
});

export const entitySpecConditionFactory =
  createConditionFactory(entitySpecRule);

```

and then you add it to the catalogBuilder in `catalog.ts`:

```ts
  builder.addPermissionRules([entitySpecRule]);
```

Hope this helps!

**Comment by Rugvip** [comment]
Gonna close since the functionality is available. Some additional docs could still be useful but there's always this issue for anyone running into this too.
