### ISSUE TITLE
🚀 Feature: Ability to select multiple entities in scaffolder.

### ISSUE THREAD

**Issue by gaurav517** [backstage/backstage#16334]
### 🔖 Feature description

Ability to select multiple entities in scaffolder.

### 🎤 Context

Currently, with `EntityPicker`, we can only select one item of an entity type. However in many cases, we might have a need to select multiple entities. For example, when using a scaffolder template for a library, a user should be able to select from all known libraries and they can be populated in `catalog-info.yaml` file in `dependsOn` section.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Think that this could either be implemented as part of a separate component, or maybe with a `multiple: true` `ui:option` which would pass that through as a prop to the Autocomplete. If we can keep it in the same component and it's not too much code then I feel it would be worth it. We should also look what happens when you have `type: string` in the `jsonschema` but return `string[]` from the component and make sure that the error messaging is clear if you have defined the schema wrong.

**Comment by gaurav517** [comment]
Very new to this, but will be happy to have a look over next weekend.. if its not done by then. 
Feel free to give pointers to save time in that case. :) Thanks.

**Comment by gaurav517** [comment]
looks like `value/onChange` in [Autocomplete](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/EntityPicker/EntityPicker.tsx#L87) would also change in case of multiple selects. Still wrapping my head around what they would look like in case of multiple selects. Whats the purpose of `formData`?

**Comment by gaurav517** [comment]
Can I please get help in an initial review (Draft PR): https://github.com/backstage/backstage/pull/16606 It seems working (including type validation)

However I see following: 
```
Material-UI: A component is changing the uncontrolled value state of Autocomplete to be controlled.
Elements should not switch from uncontrolled to controlled (or vice versa).
Decide between using a controlled or uncontrolled Autocomplete element for the lifetime of the component.
The nature of the state is determined during the first render, it's considered controlled if the value is not `undefined`.
More info: https://fb.me/react-controlled-components 
    at Autocomplete (webpack-internal:///../../node_modules/@material-ui/lab/esm/Autocomplete/Autocomplete.js:299:35)
```
I will have a better look next time.. but please let me know if you already know this. (I am more a backend person, I try frontend stuff time to time :))

**Comment by gaurav517** [comment]
ok.. so following works:
```
value={multipleSelect ? (formData as string[]) || [] : (formData as string) || ''}
```
I will update documentation and set PR for review.

**Comment by gaurav517** [comment]
hmm just noticed that `Custom Field Explorer` does not show `EntityPicker` correctly. Will need to fix that.. keep PR as draft. Pointers are welcome.

**Comment by benjdlambert** [comment]
@gaurav517 yep I think having a separate picker for this makes most sense now. Think that's fine! :pray:

**Comment by gaurav517** [comment]
Thanks. Hoping to create a PR this week.

**Comment by gaurav517** [comment]
Sorry, haven't been able to get to this yet.. too many things happening on my side.. I might be able to look at it after 2 weeks or so if still unassigned that time.. but feel free to assign this to yourself @benjdlambert in the meantime.. This can be useful feature for many. Thanks.

**Comment by z-sourcecode** [comment]
Hi Team , anyone figured this out? i'm looking for some code samples to do multi entity picker. thanks.

**Comment by mkochanek** [comment]
Any update on this?

**Comment by benjdlambert** [comment]
This is also still open for contributions - don't think any work has been started on this yet :pray:

**Comment by mrooding** [comment]
I was looking for the same functionality and created a new MultiEntityPicker in #19800

**Comment by mbenson** [comment]
Note that you can also simply declare your field of `type: array` with the entityPicker attached to its `item` and use the `+` functionality supported by RJSF.

**Comment by benjdlambert** [comment]
It looks like the PR from @mrooding went stale and got closed, but if anyone also wants to pick up this work and complete the picker seperately, please do build ontop of that PR and address to address the comments. I think that it's all DCO signed, so should be OK to re-use the work there.

**Comment by benjdlambert** [comment]
Closing as the attached PR is merged :tada:
