### ISSUE TITLE
Feature: Ability to add more that one `sites` to `azure.com/microsoft-web-sites` annotation

### ISSUE THREAD

**Issue by jpitapeva** [backstage/backstage#16337]
### 🔖 Summary

How to add more than 1 different web app

### ✌️ Context

How to add more than 1 different web app, in the documentation I saw that we can use the initials of the web app, but I didn't see how to add different ones

Example
azure.com/microsoft-web-sites: abc
azure.com/microsoft-web-sites: dfg

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jpitapeva** [comment]
@deepan10 Hi Deepan, do you know how to add more than 1 different web app

Example
azure.com/microsoft-web-sites: abc
azure.com/microsoft-web-sites: dfg

**Comment by luchillo17** [comment]
Not sure what you mean by a web app in the context of backstage, could you link the docs you're referring to?

**Comment by jpitapeva** [comment]
@jamieklassen  thank u to much
