### ISSUE TITLE
🚀 Feature: Set ownership for new Postgres schema's

### ISSUE THREAD

**Issue by joeppeeters** [backstage/backstage#16355]
### 🔖 Feature description

Currently backstage creates new postgres schema's by running [`CREATE SCHEMA IF EXISTS new_schema`](https://github.com/backstage/backstage/blob/master/packages/backend-common/src/database/connectors/postgres.ts#L145-L160).

This creates schema's owned by the current user. However, this current user is not always the user which needs to access the schema's (see Context section).

To get around this, it would be great to be able to set the ownership for new schema's. Postgres offers the `AUTHORIZATION` keyword for that: [`CREATE SCHEMA IF EXISTS new_schema AUTHORIZATION role;`](https://www.postgresql.org/docs/current/sql-createschema.html)

This feature request is about adding a config parameter to set the `role` of the newly created schema's.

### 🎤 Context

Our infrastructure is a HashiCorp stack (Nomad, Vault, ...). When we spin up a new allocation (ie. job/container/..) it gets postgres credentials from Vault. The way this works is that Vault provisions postgres with a temporary user and password (`v-username-<random_id>`). These users are member of a parent role.

When migrations are triggered, schema's get created by a random `v-user-..`. This sets the PG Schema ownership to be that specific user:

```
backstage_d=> \dn
                List of schemas
    Name    |              Owner               
------------+----------------------------------
 app        | v-backstage-d-f87FlaQV61pl4MEFoE
 auth       | v-backstage-d-f87FlaQV61pl4MEFoE
 catalog    | v-backstage-d-f87FlaQV61pl4MEFoE
 public     | postgres
 scaffolder | v-backstage-d-f87FlaQV61pl4MEFoE
 search     | v-backstage-d-f87FlaQV61pl4MEFoE
 ```
 
When a new allocation comes up, it gets provisioned with a different user. This user cannot access the schema's owned by the previous user and thus fails. Currently our only way to get around this is to manually reassign the schema's to the parent role.
 
By allowing to set the correct autorizations during schema creation, we could automate this.

### ✌️ Possible Implementation

replacing [this function](https://github.com/backstage/backstage/blob/master/packages/backend-common/src/database/connectors/postgres.ts#L152-L154) with something along the lines of:

```typescript
const ensureSchema = async (database: string) => {
  if(dbConfig.setRole) {
    await admin.raw(`CREATE SCHEMA IF NOT EXISTS ?? AUTHORIZATION ??`, [database, dbConfig.setRole]);
  } else {
    await admin.raw(`CREATE SCHEMA IF NOT EXISTS ??`, [database]);
  }
}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by iniinikoski** [comment]
Hi @joeppeeters - noticed this as well with Vault - and was a bit surprised :) Didn't know this was possible with Postgres, so I decided to use "static role" in Postgres - so the user does not change all the time - and Vault just rotates the password. An ok workaround I guess, but... :)

And for "human" access - we also have a "dynamic" role into Postgres.

**Comment by benjdlambert** [comment]
@joeppeeters I think this seems reasonable - go ahead a shoot a PR!

**Comment by joeppeeters** [comment]
@benjdlambert PR is ready for review, please let me know if something needs to change.
