### ISSUE TITLE
🚀 Feature: Allow for entity kind selection when using the Linguist plugin

### ISSUE THREAD

**Issue by elizabeth-a-hobbs** [backstage/backstage#16379]
### 🔖 Feature description

At the moment, the Linguist plugin [retrieves entities](https://github.com/backstage/backstage/blob/e86c47d3b5087bafd87fcbc52692fe3a4a19f519/plugins/linguist-backend/src/api/LinguistBackendApi.ts#L93-L99) of kinds `API`, `Component`, and `Template` for language processing. 

Adding the ability to specify the kinds for which the Linguist plugin processes would be a great feature.

### 🎤 Context

We are mainly interested in having the Linguist plugin process `Component` entities. Additionally, we might be interested in rolling up the Linguist plugin information to the `System` kind level.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ahhhndre** [comment]
Hi @elizabeth-a-hobbs, thanks for logging this. If you want to take this on it should be pretty easy.

I would add a `string[]` of Kinds as a `PluginOption` here: 

https://github.com/backstage/backstage/blob/e86c47d3b5087bafd87fcbc52692fe3a4a19f519/plugins/linguist-backend/src/service/router.ts#L35

Then that would get used here:

https://github.com/backstage/backstage/blob/e86c47d3b5087bafd87fcbc52692fe3a4a19f519/plugins/linguist-backend/src/api/LinguistBackendApi.ts#L95

I'm away on vacation for the rest of the month so won't be able to take this on till I get back in March if you can't run with this
