### ISSUE TITLE
🐛 Bug Report: linguist-backend plugin skips the initial batch

### ISSUE THREAD

**Issue by elizabeth-a-hobbs** [backstage/backstage#16370]
### 📜 Description

The lingluist-backend plugin skips the initial batch.

### 👍 Expected behavior

Entities [0, batchSize) should be processed.

### 👎 Actual Behavior with Screenshots

Entities [0, batchSize) are not being processed.

### 👟 Reproduction steps

When attempting to use the Linguist plugin with 5 entities and a batchSize of 20, the 5 entities are never processed. We believe this to be due to only one argument being provided to `slice` [here](https://github.com/backstage/backstage/blob/72d1919298047eaf9b76ba5c8ddca9620948e436/plugins/linguist-backend/src/api/LinguistBackendApi.ts#L116-L118). The `slice` [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) indicates that if only one argument is provided then it will be used as the `start` parameter.

### 🖥️ Your Environment

@backstage/plugin-linguist-backend:0.1.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ahhhndre** [comment]
Thanks for reporting and working on a PR to fix this @elizabeth-a-hobbs! I totally missed this, but I'm confused as to how it worked at all. 🤔

**Comment by ahhhndre** [comment]
Ah, now I understand what you mean by "initial batch" you mean the `n` number of entities before the slice. Not the total batch of entities that Linguist tries to process. Based on that yeah, this doesn't work, 🍳  on my face 😭
