### ISSUE TITLE
🔌 Plugin: Dagster / Airflow / Prefect

### ISSUE THREAD

**Issue by rokity** [backstage/backstage#16384]
### 🔖 Summary

Create a plugin to monitor the pipeline orchestrator , status updates, notifications ect ect 
Dagster has the our platform and a grpc server to check and integrate.
Airflow has CLI and Python API.
Prefect has Python API and can be also integrated on Sentry.

Let me know what you think to create a management plugin for orchestrator like Dagster,Airflow,Prefect.

Thanks

### ✌️ Context

Pipeline Orchestrator 

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Hey :wave: so it looks like there is some functionality for Airflow https://github.com/backstage/backstage/pull/8348 maybe it makes sense to extend some of that plugin to enable what you want?

**Comment by freben** [comment]
closing for now then
