### ISSUE TITLE
🐛 Bug Report: Linguist `processed_date` has default to current date

### ISSUE THREAD

**Issue by ahhhndre** [backstage/backstage#16394]
### 📜 Description

In the Linguist database the `processed_date` has a default to the current date which for unprocessed entities is confusing

### 👍 Expected behavior

The `processed_date` column should not have a default

### 👎 Actual Behavior with Screenshots

When new entities are added they get inserted fine but the `processed_date` gets a value which isn't technically correct as they have not been processed yet.

### 👟 Reproduction steps

Setup the Linguist plugin as documented. Query the database and you'll see that unprocessed entities have a value for the `processed_date` column.

### 📃 Provide the context for the Bug.

As the author of the Linguist plugin I'm logging this to get feedback as to how I should move forward.

I'm busy working on adding tests and discovered this issue as part of that. I can easily create a migration script but to make it work with both Postgres and SQLite I'll need to create a new column - `generated_date` - without the default, copy the contents of `processed_date` to it, and then drop `processed_date`. There'd be some other refactoring to use the new column elsewhere in code as well.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ahhhndre** [comment]
@elizabeth-a-hobbs @ThomasAwesome @GoFightNguyen looking for some feedback on this. Should I move forward with fixing this when I get back from vacation or should I leave it as is? 

Technically speaking there isn't any impact to people who are using the plugin. But if someone starts diving into the database for whatever reason then it gets confusing IMO.

Personally feel like it should be changed and doing it sooner then later would be better.

Thanks in advance for any comments!

**Comment by ThomasAwesome** [comment]
> Personally feel like it should be changed and doing it sooner then later would be better.

I also feel like it should be changed as well. I think it is best to address tech debt early on.
