### ISSUE TITLE
🐛 Bug Report: entity-validation: file location is immutable

### ISSUE THREAD

**Issue by GoFightNguyen** [backstage/backstage#16406]
### 📜 Description

In the [entity-validation plugin](https://github.com/backstage/backstage/tree/master/plugins/entity-validation), the `File Location` input is immutable.

The issue is likely caused by `value={defaultLocation}`. Maybe it should be `value={locationUrl}`.
https://github.com/backstage/backstage/blob/b25b4bda4e8af306732bba92ec22e986b28aad27/plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx#L71-L81

### 👍 Expected behavior

The `File Location` input should be mutable.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/6308176/219501040-75068574-450c-426c-95cd-ae79f0c42c8e.png)

### 👟 Reproduction steps

Run the frontend. Navigate to the UI for the plugin. Try to change the `File Location`

### 🖥️ Your Environment

`@backstage/plugin-entity-validation@0.1.0`

Bug exists on multiple browsers.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by webark** [comment]
Opened a PR #16409

This url is also only used as the location ref of the file, it does not actually pull the catalog file from the location (this is what I thought it would originally do).

Perhaps the wording could be updated a bit?
