### ISSUE TITLE
🐛 Bug Report: search collator run should result an index to ElasticSearch even if no documents are emitted

### ISSUE THREAD

**Issue by zcmander** [backstage/backstage#16423]
### 📜 Description

When you have a search collator that does not emit documents at all then [search-backend-module-elasticsearch](https://github.com/backstage/backstage/tree/master/plugins/search-backend-module-elasticsearch) does not produce index and alias for it.

Normally this is not an issue but if you select specific type with give Type filter given in the advanced search view:

![image](https://user-images.githubusercontent.com/2142965/219667033-3292aa3f-8687-4052-bd78-eb5630f3b9f8.png)

[https://demo.backstage.io/search?query=&types%5B%5D=techdocs](https://demo.backstage.io/search?query=&types%5B%5D=techdocs)

_Or if you have permissions enabled that causes all aliases/indexes to be expanded in search query which in turn causes "All" filter to fail._

Then you run into an error that is cause by the fact that there is no index created.

### 👍 Expected behavior

There should be a empty index created and related alias for it.

### 👎 Actual Behavior with Screenshots

Search API returns:

```
Request failed with status 500 Missing index for software-catalog__search. This means there are no documents to search through.
```

### 👟 Reproduction steps

Sorry, I didn't have time to prepare ready-to-use repository with all the details filled in but you could end up into such situation by:

1. Enable QETA plugin (https://github.com/drodil/backstage-plugin-qeta)
3. Enable Elastic Search plugin
4. (Enable permissions for search if you want to have an error with "All" filter too!)
5. See how search query catastrophically fails due to missing index  

### 📃 Provide the context for the Bug.

I think Q&A plugin (https://github.com/drodil/backstage-plugin-qeta) is perfect example of a search collator that does not emit any documents and it's still valid run. How networks issues & other errors are communicated via collator API is different thing, but maybe, just maybe, this is related to another issue that was causing orphan indexes: https://github.com/backstage/backstage/issues/14810

### 🖥️ Your Environment

Backend issue, so my browser does not matter. Node 16 in use.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by drodil** [comment]
The exception is thrown here https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-elasticsearch/src/engines/ElasticSearchSearchEngine.ts#L387

This also happens if you have enabled `DefaultTechDocsCollatorFactory` in your search but there are no TechDocs to index. 

Fix would probably be to check that the selected indices exist before doing the search but it doesn't work when the search alias is `*`.

**Comment by zcmander** [comment]
Maybe just add `ignore_unavailable` parameter to the search query? As described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/api-conventions.html#api-multi-index
I'm not sure if multi-target syntax is used but FYI.

**Comment by drodil** [comment]
Oh true, that might help. I was already thinking if empty indices should not be removed here https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-elasticsearch/src/engines/ElasticSearchSearchEngineIndexer.ts#L149 but your solution might be better
