### ISSUE TITLE
🚀 Feature: Support MADRv3 in ADR plugin

### ISSUE THREAD

**Issue by gaurav517** [backstage/backstage#16437]
### 🔖 Feature description

Support [MADRv3](https://raw.githubusercontent.com/adr/madr/3.0.0/template/adr-template.md) in ADR plugin.
One noticeable difference is the `status` key. In [v2](https://raw.githubusercontent.com/adr/madr/2.1.2/template/template.md), its a part of list whereas in `v3`, its not.

### 🎤 Context

I would like to use [MADRv3](https://raw.githubusercontent.com/adr/madr/3.0.0/template/adr-template.md).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kuangp** [comment]
this was implemented in https://github.com/backstage/backstage/pull/16491, thanks @gaurav517 !
