### ISSUE TITLE
Docs to newrelic plugin

### ISSUE THREAD

**Issue by juniorsdj** [backstage/backstage#16431]
### 🔖 Need

Having a start guide for using a new relic plugin on the Backstage portal is of utmost importance because it provides users with a step-by-step approach to understanding and utilizing the plugin's features. It serves as a comprehensive reference to help new users familiarize themselves with the plugin and helps existing users to become more proficient in using it. 

The current [New relic plugin README](https://github.com/backstage/backstage/tree/master/plugins/newrelic) isn't enough to to understand and use that plugin and When the docs isn't sufficient to understand a product or service, it can be frustrating and confusing for users.

### 🎉 Proposal

I recently stumbled upon an [article](https://roadie.io/backstage/plugins/newrelic) that I believe can be used as documentation for this proposal. The article was well-written and provided clear, concise explanations of the plugin's use. Including the author is an active member of this community [roadie.io](https://roadie.io/backstage/plugins/newrelic).

We can improve this doc or just use the content of the article as doc.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by benjdlambert** [comment]
Think this makes sense, do you want to to contribute some better documentation to help us out? Maybe @timmywheels can help too as I think they wrote the documentation on the roadie article?

**Comment by juniorsdj** [comment]
Sure, I can use this article as base and improve that docs

**Comment by plinioaugusto** [comment]
Up 👍

**Comment by juniorsdj** [comment]
PR was accepted and merged,  I am closing this issue.
