### ISSUE TITLE
🐛 Bug Report: Linguist handling of isLinguistAvailable

### ISSUE THREAD

**Issue by dweber019** [backstage/backstage#16434]
### 📜 Description

When one uses the plugin like described
```
<EntitySwitch>
      <EntitySwitch.Case if={isLinguistAvailable}>
        <Grid item md={6} xs={12}>
          <EntityLinguistCard />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>
```

and configures `useSourceLocation: true` the card will never show as the annotation `backstage.io/linguist` is not configured.

What do you think about it?

### 👍 Expected behavior

isLinguistAvailable should check for annotation or existence of DB entry.

### 👎 Actual Behavior with Screenshots

isLinguistAvailable will only respect annotation.

### 👟 Reproduction steps

Configure `useSourceLocation: true`.

### 📃 Provide the context for the Bug.

https://github.com/backstage/backstage/blob/master/plugins/linguist/src/plugin.ts#L29 

### 🖥️ Your Environment

backstage:  1.11.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ahhhndre** [comment]
Hi @dweber019, thanks for reporting this. Going to the DB seems like a lot. Could this maybe be handled by an ‘isLinguistSourceLocationAvailable’ that would just look for the source location annotation?

**Comment by dweber019** [comment]
Hi @ahhhndre

Depends on result we are looking for. As far as I understood the source location annotation is most of the time present. So the card would be displayed most of the time and probably it would not make sense to use a condition at all?

Thinking about it, I think it's fine as it is.
Maybe the the README could be improved to state this, so copy&past people like me aren't starting a bug hunt 😉

**Comment by bforbis** [comment]
FWIW, I ended up using this code:

```jsx
    <EntitySwitch>
      <EntitySwitch.Case
        if={entity => {
          if (
            entity.kind === 'Component' &&
            entity.metadata.annotations &&
            entity.metadata.annotations['backstage.io/source-location']
          ) {
            return true;
          }
          return false;
        }}
      >
        <Grid item md={6}>
          <EntityLinguistCard />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>
```

It would be nice to just have a param property that can be passed into `isLinguistEnabled`

```jsx
      <EntitySwitch.Case if={isLinguistAvailable({ useSourceLocation: true })}>
        <Grid item md={6}>
          <EntityLinguistCard />
        </Grid>
      </EntitySwitch.Case>
```

This would require changing the return type to a function as opposed to a boolean.

**Comment by Rugvip** [comment]
I wonder whether the condition is necessary at all when we're at the point of checking for the source location? I think in most setups that would mean that the plugin is available for all entities, or none?

**Comment by bforbis** [comment]
In my case, we have a good amount of components ingested into backstage that aren't git repos (ie: ingested through custom providers), so wouldn't be able to just turn it on for all entities.

**Comment by awanlin** [comment]
I do plan on working on this, so not totally stale, but may not get done right away

**Comment by benjdlambert** [comment]
Will unstale @awanlin :tada:
