### ISSUE TITLE
🚀 Feature: Support user-defined dynamic redirect in Backstage

### ISSUE THREAD

**Issue by Sumu-Ning** [backstage/backstage#16446]
### 🔖 Feature description

Support user-defined dynamic redirect in Backstage.

Give a user defined URL path and user defined rules, automatically redirect to another URL dynamically.

### 🎤 Context

We have Backstage entities identified by UUID, and it is not human readable, and the URL cannot be composed without doing a lookup first. The lookup is nearly impossible for non-tech users.

We would like to provide another redirect URL, containing human-readable external keys. And we would like to redirect from this human-readable URL to corresponding Backstage entity URL (the one with the UUID as `metadta.name`)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
Do you have any example of how the redirect would be configured? We have also somewhat the same problem with some of the entities having a technical name in `metadata.name` which does not translate to human-friendly URLs.

Would it be sufficient to have for example URL `/catalog/<namespace>/<kind>/title/<metadata.title>`? The problem with this is if there are two entities with the same title.

**Comment by benjdlambert** [comment]
Hey @Sumu-Ning, I think that this would best be placed in your own plugin, which can call the `catalogApi` to get lookup the entry in the catalog and re-direct you to the right places. We've not looked into any form of redirection as of yet, so think it's best you try and solve this for your use case. Does that make sense?

**Comment by Sumu-Ning** [comment]
Thank you [benjdlambert](https://github.com/benjdlambert)! 
I think the lookup is not the problem, but I have been struggling to get 'redirect' fit into the Backstage Plugin Framework (I am not really a front end developer). It would be great if you have any example about how to do a redirect within the Backstage framework. 
Thank you!

**Comment by benjdlambert** [comment]
So you'd need a React component that can return a `<Redirect />`component from `react-router` i believe.

There's an instance of a redirect here: https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/Router.tsx#L108-L120

Which gets rendered here: https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/Router.tsx#L135-L138

I think you might want to take a look at some [getting started guides for writing plugins](https://backstage.io/docs/plugins/create-a-plugin) to get you on your way.

**Comment by Sumu-Ning** [comment]
@benjdlambert Thank you for your help! I was able to get it work end to end now. 
Feel free to mark this issue as closed.

**Comment by benjdlambert** [comment]
Thanks! Nice work!
