### ISSUE TITLE
Create a more up to date Architecture Diagram

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#1645]
## Feature Suggestion
Would be good to update our architecture diagram with something that's high level and what we provide by default.
Maybe covering the Service Catalog and the Scaffolder would be a good start.

**Comment by stefanalund** [comment]
This might be interesting https://github.com/mingrammer/diagrams (via @JimHaughwout)

**Comment by prakhargurunani** [comment]
Hey @stefanalund @benjdlambert I would like to contribute on this..

**Comment by stefanalund** [comment]
@prakhargurunani in order to provide a good architecture overview you would need pretty deep understanding of the project and its parts. Do you feel like you have that?

**Comment by prakhargurunani** [comment]
Can just going through the docs help me @stefanalund ?

**Comment by stefanalund** [comment]
@prakhargurunani you are more than welcome to try :) But this might not be the easiest issue to pick up.

**Comment by prakhargurunani** [comment]
@stefanalund Ok. For now, let me explore backstage more deeply. You can assign this issue to others.
