### ISSUE TITLE
🐛 Bug Report: Github-app credentials or `app-config.yaml` should be manage outside the dockerfile

### ISSUE THREAD

**Issue by prasoon-pxc** [backstage/backstage#16520]
### 📜 Description

I am using github app for Github integration with backstage, I am defining the file name in `app-config.yaml` as below:

```
integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-test-backstage-app-credentials.yaml 
```

And to build docker image from all the setting , I need to copy this `app-config.yaml` in docker image and also I need to copy this `github-app-test-backstage-app-credentials.yaml ` file also , 

Dockerfile Snippet
---
```
COPY --chown=node:node app-config.yaml ./
COPY --chown=node:node github-app-test-backstage-app-credentials.yaml ./ 
```

I am building this docker image using github actions and as of now I need to commit this `github-app-test-backstage-app-credentials.yaml` file to github repository to successfull build docker image of backstage, but it is very big security issue to commit credentials file to github repo.

### 👍 Expected behavior

I wanted to use this credentials file externally to the docker image , such as using with configmap or k8s secrets or as a ENV variable.

### 👎 Actual Behavior with Screenshots

Currently , It is not possible to build docker image without copying this `app-config.yaml` into docker image.

### 👟 Reproduction steps

Use Github app as a integration to Github in place of Personal-access-Token (PAT). 

### 🖥️ Your Environment

Output of `yarn backstage-cli info`
---

```yarn run v1.22.19
$ /home/il58d0/smb/backstage-conf-repo/backstage-conf-repo-original/node_modules/.bin/backstage-cli info
OS:   Linux 5.14.0-1057-oem - linux/x64
node: v16.14.0
yarn: 1.22.19
cli:  0.22.2 (installed)
backstage:  1.11.0

Dependencies:
  @backstage/app-defaults                          1.2.0
  @backstage/backend-app-api                       0.4.0
  @backstage/backend-common                        0.17.0, 0.18.2
  @backstage/backend-dev-utils                     0.1.0
  @backstage/backend-plugin-api                    0.4.0
  @backstage/backend-tasks                         0.4.3
  @backstage/catalog-client                        1.3.1
  @backstage/catalog-model                         1.2.0
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.2
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.5.0
  @backstage/core-components                       0.12.4
  @backstage/core-plugin-api                       1.4.0
  @backstage/errors                                1.1.4
  @backstage/eslint-plugin                         0.1.0
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.10
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.9.0
  @backstage/plugin-app-backend                    0.3.42
  @backstage/plugin-auth-backend                   0.18.0
  @backstage/plugin-auth-node                      0.2.11
  @backstage/plugin-bazaar-backend                 0.2.5
  @backstage/plugin-bazaar                         0.2.4
  @backstage/plugin-catalog-backend-module-github  0.2.5
  @backstage/plugin-catalog-backend                1.7.2
  @backstage/plugin-catalog-common                 1.0.11
  @backstage/plugin-catalog-graph                  0.2.27
  @backstage/plugin-catalog-import                 0.9.5
  @backstage/plugin-catalog-node                   1.3.3
  @backstage/plugin-catalog-react                  1.3.0
  @backstage/plugin-catalog                        1.8.0
  @backstage/plugin-events-node                    0.2.3
  @backstage/plugin-github-actions                 0.5.15
  @backstage/plugin-home                           0.4.31
  @backstage/plugin-org                            0.6.5
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.5
  @backstage/plugin-permission-react               0.4.10
  @backstage/plugin-playlist-backend               0.2.5
  @backstage/plugin-playlist-common                0.1.4
  @backstage/plugin-playlist                       0.1.6
  @backstage/plugin-proxy-backend                  0.2.36
  @backstage/plugin-scaffolder-backend             1.11.0
  @backstage/plugin-scaffolder-common              1.2.5
  @backstage/plugin-scaffolder-node                0.1.0
  @backstage/plugin-scaffolder-react               1.1.0
  @backstage/plugin-scaffolder                     1.11.0
  @backstage/plugin-search-backend-module-pg       0.5.3
  @backstage/plugin-search-backend-node            1.1.3
  @backstage/plugin-search-backend                 1.2.3
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.5.0
  @backstage/plugin-search                         1.1.0
  @backstage/plugin-shortcuts                      0.3.7
  @backstage/plugin-sonarqube-backend              0.1.7
  @backstage/plugin-sonarqube-react                0.1.2
  @backstage/plugin-sonarqube                      0.6.3
  @backstage/plugin-tech-radar                     0.6.1
  @backstage/plugin-techdocs-backend               1.5.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.10
  @backstage/plugin-techdocs-node                  1.5.0
  @backstage/plugin-techdocs-react                 1.1.3
  @backstage/plugin-techdocs                       1.5.0
  @backstage/plugin-todo-backend                   0.1.39
  @backstage/plugin-todo                           0.2.17
  @backstage/plugin-user-settings                  0.7.0
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.5
  @backstage/theme                                 0.2.17
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
Done in 0.98s.

```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
You should probably not copy the secrets file into the container - ideally it should be mounted from the outside instead. You could mount that file from a secret using a configmap.

**Comment by prasoon-pxc** [comment]
thanks @freben, earlier when I tried  to build docker image without copying the `githubapp` file it was giving error(may be due to old version of backstage) but this time it works successfully and then I mount the `githubapp`  file using  k8s-secret and volume feature in k8s, and it works!! Thanks again.

**Comment by prasoon-pxc** [comment]
But one things is to note here, if your `githubapp` file is not present in  GitHub repo,  from where you are building the docker image then it will give following error on building:

```
Error: Failed to read static configuration file; caused by Error: error at .integrations.github[0].apps[0], ENOENT: no such file or directory, open '/app/github-app-test-backstage-app-credentials.yaml'
```
- To prevent this error from happening, you need to create a dummy file in your GitHub repo as you mentioned in your `app-config.yaml` 


```
integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-test-backstage-app-credentials.yaml
```

- Create `github-app-test-backstage-app-credentials.yaml` with contents like this, make sure it is in object form:

`github-app-test-backstage-app-credentials.yaml`
```
test: do not delete
```
And that's all to build docker image successfully!!
---
And after that , you can mount actual credentials file from k8s secret.

**Comment by miguelpuiggarcia** [comment]
Hi @prasoon-pxc How did you end up doing it? Im in the same situation where I have:
```
integrations:
  github:
    - host: github.com
      apps:
        - $include: backstage-app-credentials-github.yaml
        
        but docker build still firing:
```

        
```
 cause: Error: error at .integrations.github[0].apps[0], ENOENT: no such file or directory, open '/app/backstage-app-credentials-github.yaml'
```

Thanks!

**Comment by prasoon-pxc** [comment]
@miguelpuiggarcia --> As per your docker file , you are copying `github-app-test-backstage-app-credentials.yaml` file which is different from the integration file configuration i.e `backstage-app-credentials-github.yaml`.

 Also I would suggest not copy the `backstage-app-credentials-github.yaml` in your docker-image, You just need to create a dummy `backstage-app-credentials-github.yaml` in the same directory where `app-config.yaml` file is present , and the content of the file would be something like below:

---

`backstage-app-credentials-github.yaml`
```
test: dummyfile
```
---
And then make your actual `backstage-app-credentials-github.yaml`  available through K8s-secret or something like that.

**Comment by miguelpuiggarcia** [comment]
Thanks @prasoon-pxc . Got it now working
