### ISSUE TITLE
🐛 Bug Report: Docker: the --mount option requires BuildKit

### ISSUE THREAD

**Issue by richorama** [backstage/backstage#16536]
### 📜 Description

running this command:
```
docker image build . --file packages/backend/Dockerfile 
```

### 👍 Expected behavior

It should build the docker image

### 👎 Actual Behavior with Screenshots

It reports this error:

```
Step 2/11 : RUN --mount=type=cache,target=/var/cache/apt,sharing=locked     --mount=type=cache,target=/var/lib/apt,sharing=locked     apt-get update &&     apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential &&     yarn config set python /usr/bin/python3
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
Error: Process completed with exit code 1.
```

Please see this GH action for an example: https://github.com/richorama/ra-backstage/actions/runs/4243175631/jobs/7375582325

### 👟 Reproduction steps

1. Create fresh backstage app and follow the instructions
2. Run `docker image build . --file packages/backend/Dockerfile `
3. Fail

### 🖥️ Your Environment

I have tried this locally on WSL 2.0 and from a GH action.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
This is intended - maybe it could be documented more clearly somewhere? If so, feel free to submit a PR to clarify it! Perhaps in the Dockerfile itself as a comment? 🙏

**Comment by richorama** [comment]
ah ha, I see the docker file already says 
```
# If this occurs, then ensure BuildKit is enabled (`DOCKER_BUILDKIT=1`) so the app dir is correctly created as `node`.
```
