### ISSUE TITLE
🐛 Bug Report: `backstage.io/techdocs-ref` value for `builder: external` techdocs

### ISSUE THREAD

**Issue by joshbranham** [backstage/backstage#16547]
### 📜 Description

When using an external builder for techdocs (such as `awsS3`), techdocs only loads in the UI if you have the `backstage.io/techdocs-ref` annotation on the component set to `backstage.io/techdocs-ref: dir:.`.

Removing this value, as you would expect to since the techdocs are not relative to the component's repo when using an external builder, causes Backstage to tell you to set a value.

The docs [here](https://backstage.io/docs/features/techdocs/how-to-guides/#how-to-understand-techdocs-ref-annotation-values) provide examples of using URLs, but nothing related to `awsS3`.

I started a discussion here https://github.com/backstage/backstage/discussions/16478 as well.

### 👍 Expected behavior

I would expect this value to be safely omitted if using an external builder, _or_, have a more concise value like `backstage.io/techdocs-ref: external`.

### 👎 Actual Behavior with Screenshots

Removing the `backstage.io/techdocs-ref` annotation prevents Backstage from displaying techdocs for a project, even though they exist in S3.

### 👟 Reproduction steps

1. Configure backstage for external techdocs builder
```
techdocs:
  builder: external
  publisher:
    type: awsS3
    awsS3:
      bucketName: some-bucket
```
2. Configure a `kind: Component` with no `backstage.io/techdocs-ref`, then view it in the UI. It will give you an error saying it is not configured.
3. Add the annotation `backstage.io/techdocs-ref: dir:.`, then load the UI, and the docs will load from S3.

### 📃 Provide the context for the Bug.

I am just trying to understand what the expected value is here so I can update https://github.com/RoadieHQ/roadie-backstage-plugins/blob/bf05f65e4b6b92865bb330eeb6d9bcd5f26a184e/utils/roadie-backstage-entity-validator/src/relativeSpaceValidation.js#L15-L37 to do proper validation when using an external techdocs backend.

### 🖥️ Your Environment

```
❯ yarn backstage-cli info
yarn run v1.22.18
$ /Users/joshbranham/git/engineering-portal/node_modules/.bin/backstage-cli info
OS:   Darwin 21.5.0 - darwin/arm64
node: v16.14.0
yarn: 1.22.18
cli:  0.22.1 (installed)
backstage:  1.10.1

Dependencies:
  @backstage/app-defaults                           1.1.0
  @backstage/backend-app-api                        0.3.1
  @backstage/backend-common                         0.18.1
  @backstage/backend-plugin-api                     0.3.1
  @backstage/backend-tasks                          0.4.2
  @backstage/catalog-client                         1.3.0
  @backstage/catalog-model                          1.1.5
  @backstage/cli-common                             0.1.11
  @backstage/cli                                    0.22.1
  @backstage/config-loader                          1.1.8
  @backstage/config                                 1.0.6
  @backstage/core-app-api                           1.4.0
  @backstage/core-components                        0.12.3
  @backstage/core-plugin-api                        1.3.0
  @backstage/dev-utils                              1.0.11
  @backstage/errors                                 1.1.4
  @backstage/integration-aws-node                   0.1.1
  @backstage/integration-react                      1.1.9
  @backstage/integration                            1.4.2
  @backstage/plugin-api-docs                        0.8.14
  @backstage/plugin-app-backend                     0.3.41
  @backstage/plugin-auth-backend                    0.17.4
  @backstage/plugin-auth-node                       0.2.10
  @backstage/plugin-catalog-backend-module-github   0.2.4
  @backstage/plugin-catalog-backend                 1.7.1
  @backstage/plugin-catalog-common                  1.0.10
  @backstage/plugin-catalog-graph                   0.2.26
  @backstage/plugin-catalog-import                  0.9.4
  @backstage/plugin-catalog-node                    1.3.2
  @backstage/plugin-catalog-react                   1.2.4
  @backstage/plugin-catalog                         1.7.2
  @backstage/plugin-events-node                     0.2.2
  @backstage/plugin-explore-common                  0.0.1
  @backstage/plugin-explore-react                   0.0.25
  @backstage/plugin-explore                         0.3.45
  @backstage/plugin-github-actions                  0.5.14
  @backstage/plugin-org                             0.6.4
  @backstage/plugin-permission-common               0.7.3
  @backstage/plugin-permission-node                 0.7.4
  @backstage/plugin-permission-react                0.4.9
  @backstage/plugin-proxy-backend                   0.2.35
  @backstage/plugin-scaffolder-backend-module-rails 0.4.9
  @backstage/plugin-scaffolder-backend              1.10.1
  @backstage/plugin-scaffolder-common               1.2.4
  @backstage/plugin-scaffolder-react                1.0.1
  @backstage/plugin-scaffolder                      1.10.1
  @backstage/plugin-search-backend-module-pg        0.5.2
  @backstage/plugin-search-backend-node             1.1.2
  @backstage/plugin-search-backend                  1.2.2
  @backstage/plugin-search-common                   1.2.1
  @backstage/plugin-search-react                    1.4.0
  @backstage/plugin-search                          1.0.7
  @backstage/plugin-tech-radar                      0.6.0
  @backstage/plugin-techdocs-backend                1.5.2
  @backstage/plugin-techdocs-module-addons-contrib  1.0.9
  @backstage/plugin-techdocs-node                   1.4.5
  @backstage/plugin-techdocs-react                  1.1.2
  @backstage/plugin-techdocs                        1.4.3
  @backstage/plugin-user-settings                   0.6.2
  @backstage/release-manifests                      0.0.8
  @backstage/test-utils                             1.2.4
  @backstage/theme                                  0.2.16
  @backstage/types                                  1.0.2
  @backstage/version-bridge                         1.0.3
✨  Done in 1.01s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by soapraj** [comment]
Hi! @joshbranham like pointed out in the discussion the techdocs-ref is meant to point to where the source files live (mkdocs.yaml and the docs folder with markdown files) and not the transformed output (HTML) used to render in Backstage.

Even in the case you are suggesting setting techdocs-ref to `external` doesn't seem right as the source might still be living in the same repo. In you particular use case where are the source .md files stored? in the same repo or a different location?

When the builder is set to external the value set to techdocs-ref is not used except that it is used by the frontend as a marker to know if Techdocs exists for a component. I agree it is a bit weird but the logic here seems to be 

If techdocs-ref exists -> there is a mkdocs.yaml and docs folder -> we can expect documentation for this component
If no techdocs-ref -> no mkdocs.yaml and docs folder -> no documentation

irrespective of where the documentation gets build and published (local or external[CICD])

**Comment by joshbranham** [comment]
In our case we are using a monorepo with all the `catalog-info.yml` files, but in the individual repos, the `.md` lives in `docs/*.md` with `mkdocs.yml` in the root.

**Comment by taras** [comment]
@joshbranham techdocs uses URLReader under the hood to read docs. If your docs source code is stored in repositories, then you value would point to the url where the docs are. if they're stored in github, it would be `backstage.io/techdocs-ref: url:https://github.com/backstage/backstage/blob/master/docs`

**Comment by joshbranham** [comment]
Setting the value with the format `url:https://github.com/backstage/backstage/blob/master/docs` is working. I think the docs need some work to clarify this is the value you should be using, not `dir:.` when using a monorepo for your `catalog-info.yaml` files. I can try and take a stab at doing that.

**Comment by joshbranham** [comment]
I'm not sure what that `generator` key is but we don't have that. Something is expecting docker-in-docker and my guess is that `generator` key.

For `backstage.io/techdocs-ref` we just set ours like:
```
backstage.io/techdocs-ref: url:https://github.com/org/repo/blob/master/docs
```

**Comment by nicolasfagotti** [comment]
Hi @joshbranham, I'm looking into the same issue and it seems if the TechDocs generated are stored in s3, the value of `backstage.io/techdocs-ref` is only decorative. Why bothering to set the real url source when using a different location?

We built a centralized repository for managing entities and we are using AWS s3 to store TechDocs. Because of this, I'm trying something like:
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testService
  description: Test Service
  annotations:
    backstage.io/techdocs-entity: component:default/test-service-documentation
  tags:
  (...)
spec:
  type: service
  lifecycle: xxx
  owner: yyy
  system: zzz
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-service-documentation
  title: Test Service Documentation
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: xxx
  owner: yyy
```
