### ISSUE TITLE
🚀 Feature: Make the ring node text and ring legend text customizable (Tech Radar)

### ISSUE THREAD

**Issue by marcpsdev** [backstage/backstage#16556]
### 🔖 Feature description

Zalando's Tech Radar ([GitHub](https://github.com/zalando/tech-radar)) allows to customize both the ring node texts and the ring legend ones.

![image](https://user-images.githubusercontent.com/126147175/220859813-05fa9207-61f5-45b5-ab81-2dec6e269cfd.png)

By default, I did not find the way to do it so I would like to have a mechanism to add some styles or at least make the elements identifiable so it can be done though css.

### 🎤 Context

In my use case, I would use it to give the Tech Radar a better look and feel in a similar fashion than the [Zalando's one](https://opensource.zalando.com/tech-radar/).

### ✌️ Possible Implementation

Not sure if is there a more fancy way to do it but an option would be to add the `data-testid` attribute to the text so they would be identified easier to add some styling:
- Ring Node: [RadarGrid.tsx#L60](https://github.com/backstage/backstage/blob/37d8402c06f37c886eeecbbacf3d9871da70ea5b/plugins/tech-radar/src/components/RadarGrid/RadarGrid.tsx#L60)
- Ring Legend: [RadarLegendRing.tsx#L40](https://github.com/backstage/backstage/blob/6c4f9237d695c564a6a8075437c36550dcfe743d/plugins/tech-radar/src/components/RadarLegend/RadarLegendRing.tsx#L40)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sennyeya** [comment]
You should be able to override the existing `TechRadarApi` implementation with these values, see https://github.com/backstage/backstage/blob/master/plugins/tech-radar/src/sample.ts. 

See https://github.com/backstage/backstage/tree/master/plugins/tech-radar#how-do-i-load-in-my-own-data for how to do this.

**Comment by marcpsdev** [comment]
Thank you @sennyeya for your quick response.  I have been playing around with the `TechRadarApi` and my current approach looks very similar to the sample you provided. Unfortunately, I cannot see how can I add these styles to the Rings elements from the description given it is not a matter of data (`TechRadarLoaderResponse`) and the `RadarRing` possibilities seem limited: https://backstage.io/docs/reference/plugin-tech-radar.radarring

An example would be really helpful!🙏 Thank you in advance.

**Comment by sennyeya** [comment]
Ah, @marcpsdev apologies, I misread the initial post and thought you were trying to update the text not the styling of the text. You're right that this would require a code change. It looks like the colors of the dots and the title match and there's an added opacity to make the ring titles fade (https://github.com/zalando/tech-radar/blob/master/docs/radar.js#L248), is that what you're looking to do as well or do you need more customization?

**Comment by marcpsdev** [comment]
Don't worry @sennyeya 👍.

No I don't need more for the time being. Having this level of customization would be great. I imagine some mechanism to have it by configuration (within the [RadarRing ](https://backstage.io/docs/reference/plugin-tech-radar.radarring/)options) or being able to provide a class where to include opacity, color/fill, font (family, size, weight).

**Comment by ahhhndre** [comment]
I’m wondering if anything from the MUI docs here could help with the styling: https://v4.mui.com/customization/components/ or from the Backstage docs here: https://backstage.io/docs/getting-started/app-custom-theme#overriding-backstage-and-material-ui-components-styles

In the end I have a feeling a PR is needed to add names to the styles as per the docs so they can be changed more easily

**Comment by sennyeya** [comment]
The font and opacity can be easily controlled with existing MUI/theme overrides, the issue is in the text color I think. There's no easy way to define that as part of the theme, and I would think it should probably just be a function of the ring colors. Zalando does that by updating the opacity, we may want more customization but that seems like a sane place to start.

I took a quick look at matching this to the Zalando version, https://github.com/backstage/backstage/compare/master...sennyeya:tech-radar-text-color.

**Comment by sennyeya** [comment]
@marcpsdev Following up on this as #16597 got merged. Thoughts on the updated colors of https://demo.backstage.io/tech-radar? We're also [added a name](https://github.com/backstage/backstage/pull/16597/files#diff-887c04d32c2856265465ba2c8d9948f4d733660c90e7179a2dc812ff4d6012c1R47) to the styles for the ring which allows further customization.

**Comment by marcpsdev** [comment]
@sennyeya thank you for providing the feature. It looks great from my perspective 🙌.
