### ISSUE TITLE
🐛 Bug Report: Conflicting EntityRefs with Orphans are not Discoverable

### ISSUE THREAD

**Issue by jerroydmoore** [backstage/backstage#16579]
### 📜 Description

Moving an Entity from one Location to another, causes the Entity to be orphaned, and the "new" Entity at the "new" location to be lost forever, as the backstage's refresh_state table believes it's already processed everything at the new location and doesn't have any more deferredEntities that need to be upserted.

After tracing the code, I believe the bug lies in the [DefaultCatalogProcessingEngine.processTask](https://github.com/backstage/backstage/blob/feb1cb63b51a8c615c812787019319a888de6bfc/plugins/catalog-backend/src/processing/DefaultCatalogProcessingEngine.ts#L154-L160) comparing the `resultHash` it has from the last run to this current run. Because the `ochestrator.process()` returns the exact same object for both runs, the hash will be the same. It is only after the hash check is validated (and the hash saved to the `refresh_state` table, that the [DefaultProcessingDatabase runs checkLocationKeyConflict](https://github.com/backstage/backstage/blob/feb1cb63b51a8c615c812787019319a888de6bfc/plugins/catalog-backend/src/database/DefaultProcessingDatabase.ts#L350-L359) and ultimately rejects the duplicate Entity. But, since the hash was saved to the Location row in `refresh_state`, the hash comparison will always result in prematurely bailing early before saving the unprocessed entity.

One fix would be to clear our the `result_hash` for the Location in `refresh_state` if the `DefaultProcessingDatabase.updateProcessedEntity` encountered related errors. This is easy enough to implement.

A more interesting (and performant) fix would be to also check if the one of the conflicting EntityRefs was an orphan and adopt the Entity entirely.

### 👍 Expected behavior

The preferred behavior would be that the entity would automatically switch locations, if the entity was marked as an orphan.

A suboptimal behavior would be that deleting the orphaned entity allows entity at the new location to be processed.

### 👎 Actual Behavior with Screenshots

The entity that moved locations was lost, could not be processed and did not emit any errors.

### 👟 Reproduction steps

1. Move an existing Entity from one Location to another.
2. Wait until the new Location is read by Backstage, notice the `warn Detected conflicting entityRef` in the app logs.
3. Go to the entity's web page. Notice the orphan message, delete the entity

### 📃 Provide the context for the Bug.

I'm working on breaking up my company's single repo that contains all Backstage entities into one where each service repo contains a catalog-info.yaml file. This will require opening a PR against each repo, and each owner of the repo to evaluate and accept the PR, so doing this at scale is a requirement and with an long tail for all the PRs to be merged is expected.

To that end, I decided to move 1 Entity's location from one repo to another to test my base case. When I did, I learned that Entities are tied to Locations. So the Entity was essentially orphaned and marked a duplicate by the processors. I deleted the orphaned entity, so backstage could rediscover it, but the Entity.

### 🖥️ Your Environment

Feb 23 15:59:28 backstage-backend-6df6496959-btbjl backstage-backend 2023-02-23T23:59:28.929Z catalog warn Detected conflicting entityRef component:default/service-foo already referenced by url:https://github.com/company/backstage-catalog/tree/master/entities/services/service-foo.yaml and now also url:https://github.com/company/service-foo/tree/master/catalog-info.yaml type=plugin

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
i just wanted to acknowledge that I did indeed read this. Sorry that it took so long to respond.

The current behaviour is by design. The early bailing-out by hash is "fine" so to speak, given the fact that we chose (1) to have orphans stay around, and (2) to refuse to overwrite orphans (or non-orphans, for that matter).

That being said, I fully agree that this design is cumbersome to work with in big refactoring scenarios and that _something_ needs to be done to facilitate these use cases. Making orphans specifically permissible for overwrites might be one way. It'd be worth exploring probably. But ultimately, what we might want to do is to remove the orphaning mechanism instead: if the file effectively disappears from version control, it also disappears from the catalog. That would automatically let a different location, competing for the same entity ref, "win". This is a big change and a bit scary, but it's been raised in the catalog SIG as a decision that might be relevant to make.
