### ISSUE TITLE
🐛 Bug Report: `backstage-cli repo lint` hangs when encounters a very large file

### ISSUE THREAD

**Issue by taras** [backstage/backstage#16571]
### 📜 Description

I encountered this issue in a project that has many workspaces. One of the projects had a very large file that `eslint` took a very long time to process. In CI and locally, it would get stuck and hang forever. It was difficult to troubleshoot because it didn't output what was hanging. I had to figure it out through process of elimination. 

### 👍 Expected behavior

It shouldn't hang and maybe timeout after a few minutes. It should show what is file is causing the problem.

**Note**: I noticed that `backstage/backstage` has `**/public/*` in `.eslintignore`, but `@backstage/create-app` template doesn't have an eslintignore file. This issue wouldn't come up eslint ignored the content of `**/public/*`. It wouldn't fix the underlying problem with the CLI, but it would eliminate this particular papercut. Should we add an `.eslintignore` file to `@backtage/create-app`?

### 👎 Actual Behavior with Screenshots

![2023-02-23 12 31 30](https://user-images.githubusercontent.com/74687/220985532-a639c78b-e422-4e4b-8020-39546bfd9751.gif)

### 👟 Reproduction steps

1. Clone https://github.com/taras/eslint-repro
2. Run `yarn`
3. Run `yarn backstage-cli repo lint`

### 📃 Provide the context for the Bug.

I found this problem when installing `@backstage/plugin-graphql-voyager`. It needs the [`voyager.worker.js`](https://github.com/taras/eslint-repro/blob/main/packages/app/public/voyager.worker.js) to be copied to `packages/app/public`. 

### 🖥️ Your Environment

Reproduction was created using `npx @backstage/create-app@latest`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by andrewthauer** [comment]
I may have encountered the same thing running my fork of the Backstage repo yesterday. It would just stop and hang at one spot and I would need to Ctrl-C. NOTE: This was locally on my M1 MacBook Pro.

**Comment by freben** [comment]
Yeah adding an eslintignore file makes sense. Perhaps it can be a little stricter than `**/public/*`? Happy to review and merge a contribution to add that.

**Comment by taras** [comment]
@freben https://github.com/backstage/backstage/pull/16630 I'm not really sure what a more strict eslintignore would look like because it pretty much only makes sense to check JS file. I don't know what other files we might need to lint in the public directory.

**Comment by benjdlambert** [comment]
Closing this as fixed by adding the `public` dir to `eslintignore`
