### ISSUE TITLE
🐛 Bug Report: (create-app) Couldn't find package "@swagger-api/apidom-reference@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.

### ISSUE THREAD

**Issue by mitchhentgesspotify** [backstage/backstage#16589]
### 📜 Description

`npx @backstage/create-app@latest` fails to `yarn install`.
Note that this happens both with `0.4.36` and `0.4.37`.

### 👍 Expected behavior

Backstage should've been bootstrapped successfully.

### 👎 Actual Behavior with Screenshots

```
...
 > @trendyol-js/openstack-swift-sdk > axios-cached-dns-resolve > babel-polyfill > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
warning workspace-aggregator-99a6b024-9430-4465-a192-1a1df1c4f627 > backend > @backstage/plugin-techdocs-backend > @backstage/plugin-techdocs-node > @trendyol-js/openstack-swift-sdk > axios-cached-dns-resolve > babel-polyfill > babel-runtime > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
Error: Couldn't find package "@swagger-api/apidom-json-pointer@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@swagger-api/apidom-reference@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@swagger-api/apidom-ns-openapi-3-1@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/mhentges/.nvm/versions/node/v16.19.1/lib/node_modules/yarn/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  executing     yarn install ✖
```

### 👟 Reproduction steps

`npx @backstage/create-app@latest`, but due to (I'm assuming?) unpinned dependencies, this may be un-reproducible in the future.

### 🖥️ Your Environment

```
$ yarn backstage-cli info
yarn run v1.22.19
error Command "backstage-cli" not found.
```
😔 

I'm on an Apple M1 Max

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by triha74** [comment]
Same here

**Comment by mitchhentgesspotify** [comment]
Note that this is affecting multiple platforms (Linux and macOS for me), and also applies to _old_ create-app'd instances: I cloned one I created a month+ ago, then did a `git clean -dfx && yarn` and it's failing for the same reason.
`rm yarn.lock && git clean -dfx && yarn` fails as well 😔

**Comment by mitchhentgesspotify** [comment]
This is caused by `@backstage/plugin-api-docs@^0.9.0` specifically, the repro has been updated

**Comment by jhaals** [comment]
Hi! Looks like there's a problem with [swagger-ui](https://github.com/swagger-api/swagger-ui/issues/8418), release went out 3 hours ago and this issue just opened. Hoping for a swift new release 🤞

**Comment by mitchhentgesspotify** [comment]
Hah, I checked both [`@swagger-api/apidom-core`](https://github.com/swagger-api/apidom/issues) and [`swagger-client`](https://github.com/swagger-api/swagger-js/issues), but missed `swagger-ui`. Thanks for the upstream ref 👍

**Comment by ymoreiratiti** [comment]
Do we have some workaround?

**Comment by sennyeya** [comment]
It looks like the `@swagger-api` namespaced packages in `swagger-client` are listed as `bundleDependencies` in https://github.com/swagger-api/swagger-js/blob/v3.19.0-beta.1/package.json#L131 which Yarn 2.x has [no support for](https://yarnpkg.com/getting-started/migration#dont-use-bundledependencies). `npm` has support for `bundleDependencies` in v8 after 8.5.5, or v7 generally, https://github.com/npm/cli/issues/4332.

Assuming the package release gets reverted, there shouldn't be any issues. If not, until https://github.com/swagger-api/apidom/issues/2290 gets completed, we'd need to force a specific version with [`resolution: ...`](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)

**Comment by mali-pravin** [comment]
I am also facing the same issue on the Mac M1. Do you know if anyone was able to use the workaround successfully?

**Comment by danncasey** [comment]
I don't really node at all, so I'm having some difficulty with this.  Looking at the error below:

```Error: Couldn't find package "@swagger-api/apidom-reference@=0.68.1" required by "swagger-client@=3.19.0-beta.7" on the "npm" registry.```

I believe i need to force the previous version of swagger-client.  Look like it was 3.18.5, so I added the following to `backstage/package.json` right after DevDependencies

```    "overrides": {
          "swagger-client": "3.18.5"
  },
  ```
  
  However,  `npx @backstage/create-app@latest` will not run unless i remove the backstage directory first.    Is there a proper approach to this?

**Comment by rushabhdream11** [comment]
Same issue

**Comment by chloyka** [comment]
It is a bad idea, but. For those who get this error when trying to run `yarn install` or `yarn add` on an existing project - you can replace swagger-client 3.18.5 with version 3.18.4 on yarn.lock directly.

**Comment by sapher** [comment]
hope it got resolved soon

**Comment by ibotdotout** [comment]
FYI: I used [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it) as a workaround 

packages.json
```
  "resolutions": {
    "swagger-client": "3.18.4"
  }
```

**Comment by dagda1** [comment]
this is breaking all build jobs on CI.  Can the resolution be set there?

**Comment by char0n** [comment]
Please have a look at this comment: https://github.com/swagger-api/swagger-ui/issues/8418#issuecomment-1445155732

The fix release of SwaggerUI will be comming shortly.

**Comment by asennyey** [comment]
Upstream is getting fixed, see https://github.com/swagger-api/swagger-ui/issues/8418.

**Comment by char0n** [comment]
Fix released in https://github.com/swagger-api/swagger-ui/releases/tag/v4.16.1

**Comment by danncasey** [comment]
npx was able to create-app backstage now.  ty

**Comment by pierrevillard** [comment]
Same here ! This issue can be closed

**Comment by benjdlambert** [comment]
Thanks all 👍
