### ISSUE TITLE
🐛 Bug Report: "https://backstage.io/docs/" redirect link is incorrect

### ISSUE THREAD

**Issue by mitchhentgesspotify** [backstage/backstage#16588]
### 📜 Description

Going to [`https://backstage.io/docs/`](https://backstage.io/docs/) implies that the docs have been moved, but the link redirects to the same page.

<img width="748" alt="Screenshot 2023-02-24 at 11 34 20" src="https://user-images.githubusercontent.com/110673802/221157327-78b4841a-d744-4561-9ff2-60410aee886e.png">

### 👍 Expected behavior

The redirect link should go to the same page as if you click ["Docs"](https://backstage.io/docs/overview/what-is-backstage) in the header

### 👎 Actual Behavior with Screenshots

The redirect link goes to the same page.

### 👟 Reproduction steps

1. Go to https://backstage.io/docs/overview/what-is-backstage

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Fixed by https://github.com/backstage/backstage/pull/16593
