### ISSUE TITLE
🐛 Bug Report: The Picker component (Entity/Lifecycle/Tags/Processing Status) closes the select window on each select

### ISSUE THREAD

**Issue by Jegan-Kunniya** [backstage/backstage#16582]
### 📜 Description

The usability of the Picker component (Entity/Lifecycle/Tags/Processing Status) is annoying when the select window had to be opened after every option select and makes it even more difficult when there are more items and more criteria to be selected.

### 👍 Expected behavior

The Picker component (Entity/Lifecycle/Tags/Processing Status) should allow multiple selection and avoid a lot number of clicks and context.

### 👎 Actual Behavior with Screenshots

![Picker Single Select](https://user-images.githubusercontent.com/61824674/221131251-fab2815f-0c7a-4a78-829c-5459c8a4039e.gif)

### 👟 Reproduction steps

1. Navigate to [Backstage Demo Homepage](https://demo.backstage.io)
2. Choose an Owner from the OwnerPicker
3. See that the OwnerPicker closes after a selection

### 📃 Provide the context for the Bug.

The usability of the Pickers becomes annoying when there are more values to select.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Yeah that's a bit annoying. It MAY be the case that it's tricky to address - the location bar and filter change are applied immediately so I believe a repaint happens that may affect the currently open popover. I'll add a help wanted label on the issue, if you get the chance to look into this it'd be very appreciated.

**Comment by freben** [comment]
Oh scratch that. I just noticed that the Autocomplete component has a `disableCloseOnSelect` prop :D https://github.com/backstage/backstage/pull/16610

**Comment by Jegan-Kunniya** [comment]
Thanks, @freben for the change. Much appreciated.
