### ISSUE TITLE
🐛 Bug Report: e2e tests failing with 404 for @swagger-api/apidom-core@npm:*

### ISSUE THREAD

**Issue by dagda1** [backstage/backstage#16596]
### 📜 Description

I have created [this PR](https://github.com/backstage/backstage/pull/16528) but the e2e tests are failing for an esoteric error during a `yarn install`:

>   ➤ YN0035: │ @swagger-api/apidom-core@npm:*: The remote server failed to provide the requested resource
  ➤ YN0035: │   Response Code: 404 (Not Found)
  ➤ YN0035: │   Request Method: GET
  ➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@swagger-api%2fapidom-core

[here is an example output](https://github.com/backstage/backstage/actions/runs/4264450417/jobs/7422542750)

### 👍 Expected behavior

`e2e` should install

### 👎 Actual Behavior with Screenshots

![e2e](https://user-images.githubusercontent.com/118328/221253703-72962ef5-32d0-4983-93a7-831492be0d91.png)

### 👟 Reproduction steps

1. Create PR
2. wait...

### 📃 Provide the context for the Bug.

I am trying to create a PR

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ahhhndre** [comment]
@dagda1 possibly related? https://github.com/backstage/backstage/issues/16589#issuecomment-1443645881

**Comment by dagda1** [comment]
@ahhhndre looks like the same thing.  I'll close this.
