### ISSUE TITLE
🐛 Bug Report: Lack of input validation

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#16590]
### 📜 Description

# Summary

The application contains HTTP requests where it is possible to inject malicious payloads in the URL parameters.

This can be done with all the URL parameters in the following requests:
GET <HOST>/api/catalog/entities?filter=kind=component,spec.type=system
GET <HOST>/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all&filters%5Btype%5D=system

# Impact

This could allow an attacker to enter malicious inputs into the system, but we were not able to trigger anything, and that is why this is low severity. Input validation prevents improperly formed data from entering an information system. Because it is difficult to detect a malicious user who is trying to attack software, applications should check and validate all input entered into a system. Even if nothing was triggered by the payloads we used, it is still possible that an attacker could inject malicious code or scripts into the application.

# Mitigation

Input validation should be applied on both syntactical and Semantic levels.

`Syntactic` validation should enforce the correct syntax of structured fields (e.g. SSN, date, currency symbol).

`Semantic` validation should enforce the correctness of their values in the specific business context (e.g. start date is before the end date, and the price is within the expected range).

It is always recommended to prevent attacks as early as possible in the processing of the user's (attacker's) request. Input validation can be used to detect unauthorized input before it is processed by the application.

# Supporting Material

https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html

### 👍 Expected behavior

Invalid request parameters should make the server return an error to the user

### 👎 Actual Behavior with Screenshots

The response is normal even though the parameters include malicious payloads

### 👟 Reproduction steps

1. Modify any of the parameters and forward the request:

```
GET /catalog?filters%5Bkind%5D=component&filters%5Buser%5D={base}%0aDATA%0afoo%0a%2e%0aMAIL+FROM:+<youremail>%0aRCPT+TO:+<youremail>%0aDATA%0aFrom:+<youremail>%0aTo:+<youremail>%0aSubject:+tst%0afoo%0a%2e%0a&filters%5Btype%5D=system HTTP/2 
```

2. Notice the response is normal, meaning that the application does not validate the input.

### 🖥️ Your Environment

OS:   Darwin 22.3.0 - darwin/arm64
node: v16.19.0
yarn: 1.22.19
cli:  0.22.3 (installed)
backstage:  1.11.1

Dependencies:
  @backstage/app-defaults                                   1.2.0
  @backstage/backend-app-api                                0.4.0
  @backstage/backend-common                                 0.17.0, 0.18.2
  @backstage/backend-dev-utils                              0.1.0
  @backstage/backend-plugin-api                             0.4.0
  @backstage/backend-tasks                                  0.4.3
  @backstage/backend-test-utils                             0.1.34
  @backstage/catalog-client                                 1.3.1
  @backstage/catalog-model                                  1.2.0
  @backstage/cli-common                                     0.1.11
  @backstage/cli                                            0.22.3
  @backstage/config-loader                                  1.1.8
  @backstage/config                                         1.0.6
  @backstage/core-app-api                                   1.5.0
  @backstage/core-components                                0.12.4
  @backstage/core-plugin-api                                1.4.0
  @backstage/dev-utils                                      1.0.12
  @backstage/errors                                         1.1.4
  @backstage/eslint-plugin                                  0.1.1
  @backstage/integration-aws-node                           0.1.1
  @backstage/integration-react                              1.1.10
  @backstage/integration                                    1.4.2
  @backstage/plugin-api-docs                                0.9.0
  @backstage/plugin-app-backend                             0.3.42
  @backstage/plugin-auth-backend                            0.18.0
  @backstage/plugin-auth-node                               0.2.11, 0.2.9
  @backstage/plugin-catalog-backend-module-bitbucket-server 0.1.7
  @backstage/plugin-catalog-backend-module-msgraph          0.5.1
  @backstage/plugin-catalog-backend                         1.7.2
  @backstage/plugin-catalog-common                          1.0.11
  @backstage/plugin-catalog-graph                           0.2.27
  @backstage/plugin-catalog-import                          0.9.5
  @backstage/plugin-catalog-node                            1.3.3
  @backstage/plugin-catalog-react                           1.3.0
  @backstage/plugin-catalog                                 1.8.0
  @backstage/plugin-github-actions                          0.5.15
  @backstage/plugin-jenkins-backend                         0.1.32
  @backstage/plugin-jenkins-common                          0.1.13
  @backstage/plugin-jenkins                                 0.7.14
  @backstage/plugin-org                                     0.6.5
  @backstage/plugin-permission-backend                      0.5.17
  @backstage/plugin-permission-common                       0.7.3
  @backstage/plugin-permission-node                         0.7.5
  @backstage/plugin-permission-react                        0.4.10
  @backstage/plugin-proxy-backend                           0.2.36
  @backstage/plugin-scaffolder-backend                      1.11.0
  @backstage/plugin-scaffolder-common                       1.2.5
  @backstage/plugin-scaffolder-node                         0.1.0
  @backstage/plugin-scaffolder-react                        1.1.0
  @backstage/plugin-scaffolder                              1.11.0
  @backstage/plugin-search-backend-module-elasticsearch     1.1.3
  @backstage/plugin-search-backend-module-pg                0.5.3
  @backstage/plugin-search-backend-node                     1.1.3
  @backstage/plugin-search-backend                          1.2.3
  @backstage/plugin-search-common                           1.2.1
  @backstage/plugin-search-react                            1.5.0
  @backstage/plugin-search                                  1.1.0
  @backstage/plugin-sonarqube-react                         0.1.3
  @backstage/plugin-sonarqube                               0.6.4
  @backstage/plugin-techdocs-backend                        1.5.3
  @backstage/plugin-techdocs-module-addons-contrib          1.0.10
  @backstage/plugin-techdocs-node                           1.5.0
  @backstage/plugin-techdocs-react                          1.1.3
  @backstage/plugin-techdocs                                1.5.0
  @backstage/plugin-user-settings                           0.7.0
  @backstage/release-manifests                              0.0.8
  @backstage/test-utils                                     1.2.5
  @backstage/theme                                          0.2.17
  @backstage/types                                          1.0.2
  @backstage/version-bridge                                 1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Thanks for the report, but I'll just respectfully disagree on the premise here. :)

The parameters in question are used for filtering. They are converted into database filter queries. I will argue that defense in depth here is more harmful than helpful; there is no amount of logic or care in the "front" part of this, that can capture what an intentful attacker can try to conjure up, and there is absolutely no replacement for precompiled statements at the "back" part of things (the database layer) which make this a complete non-issue.
