### ISSUE TITLE
🐛 Bug Report: Cookiecutter image is not updated anymore

### ISSUE THREAD

**Issue by dschwank** [backstage/backstage#16609]
### 📜 Description

The [`spotify/backstage-cookiecutter` image](https://hub.docker.com/r/spotify/backstage-cookiecutter) is not updated since November 2020. It seems like the mentioned integration between DockerHub and GitHub does not work properly anymore:

> This is handled by an integration between DockerHub and GitHub. The integration handles updating the container image when a new release is made.
> 
> -- https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/scripts

For sure, one could build an own image, but it would be nice to keep the provided image up-to-date. Right now it is still based on cookiecutter 1.7.2.

### 👍 Expected behavior

The image is update & published automatically.

### 👎 Actual Behavior with Screenshots

Currently it is not updated - the last publish is 2 years ago.

<img width="1283" alt="Bildschirm­foto 2023-02-27 um 11 52 38" src="https://user-images.githubusercontent.com/8232196/221545016-955218dc-d20f-4458-ab2a-38c395e1309b.png">

### 👟 Reproduction steps

1. Go to DockerHub and check the tags: https://hub.docker.com/r/spotify/backstage-cookiecutter/tags

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Thanks for reporting this @dschwank  - looks like since we moved the repo it might have been broken. We're looking into why it's not building internally and will update this ticket when we find out more!

**Comment by christopher-cudennec** [comment]
Any updates @benjdlambert ?

**Comment by benjdlambert** [comment]
Sorry this totally slipped my mind - will try to get this updated next week

**Comment by christopher-cudennec** [comment]
Any updates @benjdlambert ?

**Comment by christopher-cudennec** [comment]
@freben / @benjdlambert reopen? I still don't see new images on Docker hub.

**Comment by gonzalovazquez** [comment]
Is there documentation on how to use the current image?
