### ISSUE TITLE
Instructions for building and deploying backstage using paketo buildpacks

### ISSUE THREAD

**Issue by srisek** [backstage/backstage#16615]
### 🔖 Feature description

Currently we are using paketo buildpacks to build code in our CI pipeline. It would be nice if we ca get some instructions or directions on how we can build the custom backstage code base using buildpacks.

### 🎤 Context

I am trying to see if the backstage app can be built using paketo buildpacks to integrate the build with my existing tekton and paketo buildpacks CI pipeline.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
The main build artefacts that we document as part of this project are [Docker images](https://backstage.io/docs/deployment/docker), as well as [frontend](https://backstage.io/docs/local-dev/cli-build-system#frontend-production) and [backend](https://backstage.io/docs/local-dev/cli-build-system#backend-production) production builds. We try to avoid getting too detailed beyond that as there's a huge amount of potential documentation we could write that would be a large maintenance burden. I think something like this would for example make sense as an external blog post.

I'll close this issue as it's not actionable.
