### ISSUE TITLE
🚀 Feature: EntityLinksCard filter

### ISSUE THREAD

**Issue by jen13501** [backstage/backstage#16620]
### 🔖 Feature description

I'd like to filter links shown on the [EntityLinksCard](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityLinksCard/EntityLinksCard.tsx#L32) by type - filtering by type is a pretty quick change but I'm curious if there's interest in additional filtering (the other fields are url, title, icon) that I should add support for

### 🎤 Context

This would allow us to reuse the existing links data structure but filter them for display - ie. a tab called "dashboards" would only show "dashboard" type links.

### ✌️ Possible Implementation

Add an optional filter parameter to the EntityLinksCardProps. For just type filtering - filter by type in the EntityLinksCard. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Discussed this a bit and we're feeling that for now it's perhaps best if you implement your own entity links card with the capability that you want. This isn't a request we've heard a lot so far and we hesitate to build new local customization points as we're looking to make larger changes to the system instead. If this is something that more people want to see we can revisit. Do be inspired by this: https://github.com/backstage/backstage/blob/e47ad933adbeaca513ee4b84bd9d3cbbe7bcb910/plugins/catalog/src/components/EntityLinksCard/EntityLinksCard.tsx#L32

**Comment by jen13501** [comment]
Sounds good, thanks!
