### ISSUE TITLE
🐛 Bug Report: Broken link on backstage.spotify.com site

### ISSUE THREAD

**Issue by ksurendra** [backstage/backstage#16626]
### 📜 Description

On the home page https://backstage.spotify.com , under "Three ways Backstage makes an engineer’s life easier" section, "Manage" tab, the url to "Backstage Software Catalog" should redirect/open valid url "https://backstage.io/docs/features/software-catalog/" instead of "https://backstage.io/docs/features/software-catalog/software-catalog-overview".

### 👍 Expected behavior

The link on "Backstage Software Catalog" should open the page properly.

### 👎 Actual Behavior with Screenshots

As of now this link shows a page not found.
![Screenshot 2023-02-27 at 2 25 07 PM](https://user-images.githubusercontent.com/902972/221677538-96baee7c-2551-4888-b38e-19040114ed84.png)

### 👟 Reproduction steps

1. Go to home page https://backstage.spotify.com
2. Under "Three ways Backstage makes an engineer’s life easier" section, "Manage" tab, click the link to "Backstage Software Catalog"

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Parsifal-M** [comment]
Interesting, I don't think `https://backstage.spotify.com/` is part of the repo. But @freben can probably confirm :smile:

**Comment by freben** [comment]
That's correct. I can help to report internally, but closing for now since it's not part of the open source project!

**Comment by freben** [comment]
Alright, should be fixed now.
