### ISSUE TITLE
🐛 Bug Report: Can't override BackstagePage root CSS

### ISSUE THREAD

**Issue by taras** [backstage/backstage#16631]
### 📜 Description

Using a Custom Theme with `BackstagePage.root` override removes the CSS but doesn't accept override values. 

Here is the override that I'm trying to apply, All of this is directly from https://backstage.io/docs/getting-started/app-custom-theme/#overriding-backstage-and-material-ui-components-styles

```ts
export const createCustomThemeOverrides = (
  theme: BackstageTheme,
): BackstageOverrides => {
  return {
    BackstagePage: {
      root: {
        height: '100%',
      },
    },
  };
};


const customTheme: BackstageTheme = {
  ...lightTheme,
  overrides: {
    // These are the overrides that Backstage applies to `material-ui` components
    ...lightTheme.overrides,
    // These are your custom overrides, either to `material-ui` or Backstage components.
    ...createCustomThemeOverrides(lightTheme),
  },
};

const app = createApp({
  apis,
  bindRoutes({ bind }) {
    bind(catalogPlugin.externalRoutes, {
      createComponent: scaffolderPlugin.routes.root,
      viewTechDoc: techdocsPlugin.routes.docRoot,
    });
    bind(apiDocsPlugin.externalRoutes, {
      registerApi: catalogImportPlugin.routes.importPage,
    });
    bind(scaffolderPlugin.externalRoutes, {
      registerComponent: catalogImportPlugin.routes.importPage,
    });
    bind(orgPlugin.externalRoutes, {
      catalogIndex: catalogPlugin.routes.catalogIndex,
    });
  },
  themes: [{
    id: 'my-theme',
    title: 'My Custom Theme',
    variant: 'light',
    Provider: ({ children }) => (
      <ThemeProvider theme={customTheme}>
        <CssBaseline>{children}</CssBaseline>
      </ThemeProvider>
    ),
  }]
});
```

### 👍 Expected behavior

I would expect `.BackstagePage_root_{number}` to have `height: 100%` as I specified in the override. 

### 👎 Actual Behavior with Screenshots

The class is completely missing and doesn't have any styles at all.

### 👟 Reproduction steps

![2023-02-27 19 30 33](https://user-images.githubusercontent.com/74687/221725612-0d5d8a4f-1e6b-461d-8ec2-cdd2c67cb9ae.gif)

1. Clone https://github.com/taras/backstage-page-override
2. Run yarn
3. Run yarn dev
4. Look at style of `main` element with class `BackstagePage_root`, it'll be missing.

### 📃 Provide the context for the Bug.

I have a page with a header. The presence of the header causes the entire page to extend beyond page height because `main` is set to `height: 100vh`. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by patrickacioli** [comment]
I've the same problem with `BackstageSidebar`. 


```
export const createCustomThemeOverrides = (
  theme: BackstageTheme,
): BackstageOverrides => {
  return {
    BackstageSidebar: {
      drawer: {},
    },
  };
};
```

If I put any value inside `BackstageSidebar.drawer`, the component miss the classes. And the result is the same, for any input. 


![image](https://user-images.githubusercontent.com/6707011/222155429-857c9b05-c111-40f1-b2df-7c99488d82b7.png)

**Comment by taras** [comment]
Ok, so I did a bit of digging and found something interesting. `getStylesCreator` is called to create styles that are converted into style code blocks. It's responsible for merging overrides into base configuration. It's attempting to merge the overrides into an object which results in an empty object.

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/74687/222224426-6f55fbfa-4f4d-4c75-9fb7-a9c0f51dd144.png">

**Comment by taras** [comment]
Something is very wrong with overrides. I spent a bunch of time digging through this and I believe the problem is that theme overrides do not support hook props. 

For example,

```ts
const useStyles = makeStyles<BackstageTheme, { isMobile?: boolean }>(
  () => ({
    root: ({ isMobile }) => ({
      display: 'grid',
      gridTemplateAreas:
        "'pageHeader pageHeader pageHeader' 'pageSubheader pageSubheader pageSubheader' 'pageNav pageContent pageSidebar'",
      gridTemplateRows: 'max-content auto 1fr',
      gridTemplateColumns: 'auto 1fr auto',
      height: isMobile ? '100%' : '100vh',
      overflowY: 'auto',
    }),
  }),
  { name: 'BackstagePage' },
);
```

If you try to override `BackstagePage`, material-ui styles will try to merge your override with the root function that receives props. I'm not sure how it's supposed to work because `getStylesCreator` doesn't know about props that are being passed in.

**Comment by taras** [comment]
This works as expected. I'm essentially passing `BackstagePage.root` via theme props. The type is not compatible with this but it works.

```ts
const useStyles = makeStyles<BackstageTheme, { isMobile?: boolean }>(
  (theme) => {
    return {
      root: props => {
        const defaults = {
          display: "grid",
          gridTemplateAreas: "'pageHeader pageHeader pageHeader' 'pageSubheader pageSubheader pageSubheader' 'pageNav pageContent pageSidebar'",
          gridTemplateRows: "max-content auto 1fr",
          gridTemplateColumns: "auto 1fr auto",
          height: props.isMobile ? "100%" : "100vh",
          overflowY: "auto"
        };
        return typeof theme.props.BackstagePage.root === 'function' ? theme.props.BackstagePage.root(defaults, props) : defaults;
      },
    }
  },
  { name: 'BackstagePage' },
);
```

With this setup,

```ts
export const createCustomThemeOverrides = (
  theme: BackstageTheme,
): BackstageOverrides => {
  return {
  };
};

const customTheme: BackstageTheme = {
  ...lightTheme,
  props: {
    BackstagePage: {
      root: (style, props) => ({
        ...style,
        height: '100%'
      })
    }
  },
  overrides: {
    // These are the overrides that Backstage applies to `material-ui` components
    ...lightTheme.overrides,
    // These are your custom overrides, either to `material-ui` or Backstage components.
    ...createCustomThemeOverrides(lightTheme),
  },
};
```

**Comment by taras** [comment]
@patrickacioli  can you please create a separate issue `BackstageSidebar`, I will add it to meta issue. Would you be open to contributing a fix for `BackstageSidebar`?

**Comment by patrickacioli** [comment]
> @patrickacioli can you please create a separate issue `BackstageSidebar`, I will add it to meta issue. Would you be open to contributing a fix for `BackstageSidebar`?

Yes, I'll open a issue and contribute.
