### ISSUE TITLE
🚀 Feature: Default TechDocs search results made more relevant 

### ISSUE THREAD

**Issue by peaky76** [backstage/backstage#16668]
### 🔖 Feature description

The `initialState.term` on `TechDocsSearch` is an empty string, so initial search results can be anything and not very meaningful to the user. This would set the default to something more meaningful - like the entity name - or suspend search results until a term is entered. 

### 🎤 Context

Users have reported confusion when first entering the TechDocs search box. The initial set of results does not seem to show any pattern. It is often a seemingly random list of headings from within the document. It would be less confusing if no results were shown until the user had entered a string or if the results were otherwise more meaningful and structured.  

### ✌️ Possible Implementation

Alter `initialState.term` in `TechDocsSearch` to be e.g. the entity name by default, or disable the Autocomplete results until `term` is set.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by JordiPolo** [comment]
Pinging this, I've just set search + techdocs and notice the same confusion

**Comment by agentbellnorm** [comment]
Hey @peaky76, thanks for bringing this up!

> Alter initialState.term in TechDocsSearch to be e.g. the entity name by default, or disable the Autocomplete results until term is set.

My initial thought is that it's probably safer to disable the autocomplete results initially, as the entity name is also quite arbitrary and risk not solving the problem.

Will you be able to work on this? I'd be happy to review a PR!
