### ISSUE TITLE
🚀 Feature: Alerts Subscription and Alerts creation

### ISSUE THREAD

**Issue by anantharamakrishnans** [backstage/backstage#16666]
### 🔖 Feature description

As a developer or user I would be able to create alerts and subscribe to it. This can be helpful to keep myself updated about atopic or teams work etc. 

### 🎤 Context

Rather than checking and discovering a item this gives additional level of control for users to keep tap on ever growing and fast paced technology implementations. 

### ✌️ Possible Implementation

I am thinking of a RSS feed kind of feature which any user can subscribe based on their interests.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
Thanks @drodil! Yep I agree, gonna close this as a duplicate. While I see that there are some slightly different nuances to this suggestion I feel that there's enough overlap that it's best to consolidate the discussions.
