### ISSUE TITLE
🐛 Bug Report: Broken link for default plugin icon

### ISSUE THREAD

**Issue by kubealex** [backstage/backstage#16687]
### 📜 Description

In the _microsite/pages/plugin.js_ file, there was a link to the wrong path for the default icon for plugins, causing plugins with no custom logo to show as a broken image.

### 👍 Expected behavior

Show default icon for plugins

### 👎 Actual Behavior with Screenshots

![Screenshot from 2023-03-03 09-34-56](https://user-images.githubusercontent.com/4215912/222672725-fe4ecdc7-90a3-4252-ac25-89b5fab10508.png)

### 👟 Reproduction steps

1. Go to https://backstage.io/plugins/
2. Move to "Azure Resources" and "Azure Sites" plugins
3. experience the broken link

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by adamdmharvey** [comment]
With the merge of the referenced #16686, I believe this is now fixed?

<img width="703" alt="image" src="https://user-images.githubusercontent.com/33203301/224216041-7a7005df-3ecf-4ea9-ab10-5f7e56a64f07.png">

Going to close but feel free to open if you think there's more to it.  Thanks!
