### ISSUE TITLE
💬 RFC: Standardization on entity provider clientside throttling

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#16692]
### 🔖 Need

Ensuring that backstage doesn't become a problem for external systems when fetching data requires careful consideration on concurrency control / maximum throughput. Without clientside throttling support, backstage could hit an external system fast enough that it could cause degradation of services or temporary outages.

Take the Bitbucket server discovery provider for example. The current crawler implementation right now will fetch from every single repository in an organization using a simple `for await (const repo of repositories) {}` loop. Without throttle control, this could send a massive amount of requests against bitbucket in large organizations.

### 🎉 Proposal

Entity providers should begin to standardize on strategies for adding configurable support for throttling requests against external systems. One possibility would be to add functionality from either the [bottleneck](https://github.com/SGrondin/bottleneck) or [limiter](https://github.com/jhurliman/node-rate-limiter) projects and add standard properties to the task scheduler configurations that can be used by entity provider implementations.

An example of how either of these might be configured in a provider could be:

```ts
BitbucketServerEntityProvider.fromConfig(env.config, {
  schedule: {
    frequency: { hours: 6 },
    timeout: { minutes: 15 },
  },
  // Using limiter API
  limiter: {
    tokensPerInterval: 5,
    interval: 'second',
  },
  // Using bottleneck API
  bottleneck: {
    maxConcurrent: 5,
    minTime: 200
  },
});
```

### 〽️ Alternatives

As @taras suggests in the comments, providers could be standardized on using "Incremental Entity Providers" which may have some form of throttle control built into them by controlling burst and rests.

### ❌ Risks

It is unlikely to be able to update all entity providers to have uniform throttling features at once, so the standardization won't be there initially. We would also need to be extra vigilant that contributors adhere to the throttling standard.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by taras** [comment]
@bforbis another option worth looking into is to refactor Bitbucket Entity Provider to an Incremental Entity Provider. Then the provider will automatically backoff when it hits rate limit. We could even extend Incremental Ingestion backend to support proactively backing-off before hitting the rate limit. You can read more about it here https://backstage.io/blog/2023/01/31/incremental-entity-provider

**Comment by bforbis** [comment]
Interesting idea @taras, that certainly does look useful. My organization does not have rate limiting turned on for bitbucket right now, so that is why I was thinking client-side throttle control would be useful here.

I suppose the nature of how the incremental entity provider approach works would naturally add a little bit of throttling between bursts, but the peak requests during a burst is still unlimited if the target server does not have rate limiting enabled on the API.

**Comment by taras** [comment]
You can use it for throttling too because you can control `burstLength` and `restLength` for each entity provider. `bustLength` controls how long the entity provider will attempt to paginate before resting. For example, you could say 1 second burst length, which means that it'll attempt to process as many pages as it can in 1 second. `restLength` is how long it rests between bursts. It gives the processing loop time to process the entities. The result is effectively a throttle but we could also add the ability to control burst length based on number of requests.

**Comment by bforbis** [comment]
@Rugvip, after reading up on how `BitbucketServerEntityProvider` is implemented along with `BitbucketServerClient`, I think actually the right configuration would look more like:

```yaml
integrations:
  bitbucketServer:
    - host: bitbucket.mycompany.com
       apiBaseUrl: https://bitbucket.mycompany.com/rest/api/latest
       token: ${BITBUCKET_TOKEN}
       bottleneck:
         maxConcurrent: 5
         minTime: 200
```

Doing it this way means the rate limiter applies to all bitbucket operations on the server side that utilizes this integration configuration, not just this individual entity provider.
