### ISSUE TITLE
💬 RFC: Do not use style hook props in core-components

### ISSUE THREAD

**Issue by taras** [backstage/backstage#16693]
### Table of Contents

- [🔖 Need](#---need)
  * [What is props in a style hook?](#what-is-props-in-a-style-hook-)
    * [Example in Page Component](#example-in-page-component---source--https---githubcom-backstage-backstage-blob-master-packages-core-components-src-layout-page-pagetsx-l26-l34--)
    * [Example in Sidebar](#example-in-sidebar---source--https---githubcom-backstage-backstage-blob-master-packages-core-components-src-layout-sidebar-bartsx-l42-l76--)
  * [How do you override a core-component?](#how-do-you-override-a-core-component-)
- [🎉 Proposal](#---proposal)
  * [Avoid using props by rendering a different component](#avoid-using-props-by-rendering-a-different-component)
  * [Use Media Queries instead of isMobile prop](#use-media-queries-instead-of-ismobile-prop)
  * [Use theme props instead of hook props](#use-theme-props-instead-of-hook-props)
  * [Eliminate conditional CSS](#eliminate-conditional-css)
- [〽️ Alternatives](#---alternatives)
- [❌ Risks](#--risks)

----

### 🔖 Need

Backstage Adopters need to be able to override styles of core-components. Unfortunately, it looks like it's not possible to override core-components styles with a custom theme when the core-component is using props in style hooks.

The problem was originally identified in https://github.com/backstage/backstage/issues/16631

#### What is props in a style hook?

A style hook is used when `useStyles` hook needs to accept props. 

##### Example in Page Component ([source](https://github.com/backstage/backstage/blob/master/packages/core-components/src/layout/Page/Page.tsx#L26-L34))

For example, in the Page component, the style hook takes `isMobile` prop to control the height.

```ts
const useStyles = makeStyles<BackstageTheme, { isMobile?: boolean }>(
  () => ({
    root: ({ isMobile }) => ({
      display: 'grid',
      gridTemplateAreas:
        "'pageHeader pageHeader pageHeader' 'pageSubheader pageSubheader pageSubheader' 'pageNav pageContent pageSidebar'",
      gridTemplateRows: 'max-content auto 1fr',
      gridTemplateColumns: 'auto 1fr auto',
      height: isMobile ? '100%' : '100vh',
      overflowY: 'auto',
    }),
  }),
  { name: 'BackstagePage' },
);
```

##### Example in Sidebar ([source](https://github.com/backstage/backstage/blob/master/packages/core-components/src/layout/Sidebar/Bar.tsx#L42-L76))

It's also used extensively in the Sidebar component. In this case, it's `isMobile` is used to [render a different component](https://github.com/backstage/backstage/blob/master/packages/core-components/src/layout/Sidebar/Bar.tsx#L232) which could be one of the mitigating strategies for this problem. 

In this case, the problem is with the `width` which comes from `props.sidebarConfig.drawerWidthClosed`. which comes from SidebarConfig context. 

```ts
const useStyles = makeStyles<BackstageTheme, { sidebarConfig: SidebarConfig }>(
  theme => ({
    drawer: props => ({
      display: 'flex',
      flexFlow: 'column nowrap',
      alignItems: 'flex-start',
      position: 'fixed',
      left: 0,
      top: 0,
      bottom: 0,
      zIndex: theme.zIndex.appBar,
      background: theme.palette.navigation.background,
      overflowX: 'hidden',
      msOverflowStyle: 'none',
      scrollbarWidth: 'none',
      width: props.sidebarConfig.drawerWidthClosed,
      transition: theme.transitions.create('width', {
        easing: theme.transitions.easing.sharp,
        duration: theme.transitions.duration.shortest,
      }),
      '& > *': {
        flexShrink: 0,
      },
      '&::-webkit-scrollbar': {
        display: 'none',
      },
      '& .MuiButtonBase-root': {
        textTransform: 'none',
      },
    }),
    drawerOpen: props => ({
      width: props.sidebarConfig.drawerWidthOpen,
      transition: theme.transitions.create('width', {
        easing: theme.transitions.easing.sharp,
        duration: theme.transitions.duration.shorter,
      }),
    }),
    visuallyHidden: {
      top: 0,
      position: 'absolute',
      zIndex: 1000,
      transform: 'translateY(-200%)',
      '&:focus': {
        transform: 'translateY(5px)',
      },
    },
  }),
  { name: 'BackstageSidebar' },
);
```

#### How do you override a core-component?

The docs provide a [guide on how to override components in Material UI and Backstage core-components ](https://backstage.io/docs/getting-started/app-custom-theme/#overriding-backstage-and-material-ui-components-styles)

It requires creating a custom theme and provide styles for Backstage components in overrides.

```ts
import { BackstageOverrides } from '@backstage/core-components';

export const createCustomThemeOverrides = (
  theme: BackstageTheme,
): BackstageOverrides => {
  return {
    BackstageHeader: {
      header: {
        width: 'auto',
        margin: '20px',
        boxShadow: 'none',
        borderBottom: `4px solid ${theme.palette.primary.main}`,
      },
    },
  };
};

const customTheme: BackstageTheme = {
  ...lightTheme,
  overrides: {
    // These are the overrides that Backstage applies to `material-ui` components
    ...lightTheme.overrides,
    // These are your custom overrides, either to `material-ui` or Backstage components.
    ...createCustomThemeOverrides(lightTheme),
  },
};

const app = createApp({
  apis: ...,
  plugins: ...,
  themes: [{
    id: 'my-theme',
    title: 'My Custom Theme',
    variant: 'light',
    Provider: ({ children }) => (
      <ThemeProvider theme={customTheme}>
        <CssBaseline>{children}</CssBaseline>
      </ThemeProvider>
    ),
  }]
});
```

### 🎉 Proposal

The root of the problem is how MUI4 merges overrides into [component's styles](https://github.com/mui/material-ui/blob/v4.12.4/packages/material-ui-styles/src/getStylesCreator/getStylesCreator.js#L58). When it encounters a style object with functions as values, it attempts to merge an object with the function which results in an empty object.

We don't know how receptive MUI team would be to fixing the merge logic in MUI4 when MUI5 is latest and MUI6 is in beta. It's also unclear how you'd actually fix this because we don't have props to use for overrides. There might be a way to apply overrides to already computed styles, but we have to find out from the MUI team. 

In the mean time, we might have a few mitigating strategies that we could apply as conventions in `core-components` to allow Adopters to style `core-components`.

#### Avoid using props by rendering a different component

This is the strategy used in the Sidebar component. 

```ts
  return isMobile ? (
    <MobileSidebar>{children}</MobileSidebar>
  ) : (
    <SidebarConfigContext.Provider value={{ sidebarConfig, submenuConfig }}>
      <DesktopSidebar
        openDelayMs={openDelayMs}
        closeDelayMs={closeDelayMs}
        disableExpandOnHover={disableExpandOnHover}
      >
        {children}
      </DesktopSidebar>
    </SidebarConfigContext.Provider>
  );
```

#### Use Media Queries instead of isMobile prop

`isMobile` is set by [reading the Media Query](https://github.com/backstage/backstage/blob/905141aa08c9c9aba8cea4d4fc4c1cdbc5eb1aa7/packages/core-components/src/layout/Sidebar/Page.tsx#L107) but JSS, which MUI4 usesm allows to specify [Media Queries in styles](https://cssinjs.org/jss-syntax?v=v10.10.0#media-queries)

Here is what that looks like, see #16697

```ts
const useStyles = makeStyles<BackstageTheme>(
  theme => ({
    root: {
      display: 'grid',
      gridTemplateAreas:
        "'pageHeader pageHeader pageHeader' 'pageSubheader pageSubheader pageSubheader' 'pageNav pageContent pageSidebar'",
      gridTemplateRows: 'max-content auto 1fr',
      gridTemplateColumns: 'auto 1fr auto',
      overflowY: 'auto',
      height: '100vh',
      [theme.breakpoints.down('xs')]: {
        height: '100%',
      },
    },
  }),
  { name: 'BackstagePage' },
);
```

#### Use theme props instead of hook props

Sidebar component is an excellent candidate for using this approach to theming. Instead of making the sidebar configurable via configuration that's passed through props, we can use theme props instead. This eliminate the needs for hooks props. 

You'd specify the configs in the custom theme like this,

```ts
const customTheme: BackstageTheme = {
  ...lightTheme,
  props: {
     ...lightTheme.props,
     BackstageSidebar: {
        drawerWidthClosed: '40px',
        drawerWidthOpen: '250px'
     }
  },
  overrides: {
    // These are the overrides that Backstage applies to `material-ui` components
    ...lightTheme.overrides,
    // These are your custom overrides, either to `material-ui` or Backstage components.
    ...createCustomThemeOverrides(lightTheme),
  },
};
```

Here is what that looks like,

```ts
const useStyles = makeStyles<BackstageTheme>(
  theme => ({
    drawer: {
      display: 'flex',
      flexFlow: 'column nowrap',
      alignItems: 'flex-start',
      position: 'fixed',
      left: 0,
      top: 0,
      bottom: 0,
      zIndex: theme.zIndex.appBar,
      background: theme.palette.navigation.background,
      overflowX: 'hidden',
      msOverflowStyle: 'none',
      scrollbarWidth: 'none',
      width: theme.props.BackstageSidebar.drawerWidthClosed,
      transition: theme.transitions.create('width', {
        easing: theme.transitions.easing.sharp,
        duration: theme.transitions.duration.shortest,
      },
      '& > *': {
        flexShrink: 0,
      },
      '&::-webkit-scrollbar': {
        display: 'none',
      },
      '& .MuiButtonBase-root': {
        textTransform: 'none',
      },
    }),
    drawerOpen: {
      width: theme.props.BackstageSidebar.drawerWidthOpen,
      transition: theme.transitions.create('width', {
        easing: theme.transitions.easing.sharp,
        duration: theme.transitions.duration.shorter,
      }),
    },
    visuallyHidden: {
      top: 0,
      position: 'absolute',
      zIndex: 1000,
      transform: 'translateY(-200%)',
      '&:focus': {
        transform: 'translateY(5px)',
      },
    },
  }),
  { name: 'BackstageSidebar' },
);
```

#### Eliminate conditional CSS

In some cases, we might be able to eliminate conditional CSS completely by fixing the CSS. 

For example, in the Page component, we use `display: grid` which shouldn't require `100vh`. We might be able to eliminate props by fixing the CSS so `100vh` is not necessary. 

### 〽️ Alternatives

We need a more permanent solution for https://github.com/backstage/backstage/issues/7094 but these are just workarounds. 

### ❌ Risks

Applying these is going to be a decent amount of work and it'll impact existing Adopters who modified the theme. 

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Implementation

- [x] BackstagePage #16631 
- [ ] [MobileSidebar.tsx (doesn't have override)](https://github.com/backstage/backstage/blob/270529ff2f196daec626b04b3165d8cdc3a3b3cf/packages/core-components/src/layout/Sidebar/MobileSidebar.tsx#L63)
- [ ] [SidebarGroup.tsx (doesn't have override)](https://github.com/backstage/backstage/blob/270529ff2f196daec626b04b3165d8cdc3a3b3cf/packages/core-components/src/layout/Sidebar/SidebarGroup.tsx#L51)
- [ ] [BackstageSidebarIntro](https://github.com/backstage/backstage/blob/270529ff2f196daec626b04b3165d8cdc3a3b3cf/packages/core-components/src/layout/Sidebar/Intro.tsx#L42)
- [ ] [BackstageSidebar](https://github.com/backstage/backstage/blob/270529ff2f196daec626b04b3165d8cdc3a3b3cf/packages/core-components/src/layout/Sidebar/Bar.tsx#L40)

**Comment by Rugvip** [comment]
👍 to the suggested refactor, or really any refactor that avoid the prop callback. Do you think it's worth highlighting or enforcing this in some other way other than an effort through this RFC?

**Comment by taras** [comment]
> Do you think it's worth highlighting or enforcing this in some other way other than an effort through this RFC?

Like ESLint rule?

**Comment by taras** [comment]
@Rugvip removing props from sidebar is going to be more complicated because Sidebar allows to pass `SidebarConfig` via props to the component. 

1. `Sidebar` component is part of public API. Making `BackstageSidebar` and `BackstageSidebarIntro` overridable will require a breaking change.
2. `MobileSidebar` and `SidebarGroup` components are not overridable. Should they be?
