### ISSUE TITLE
Detail workflow for plugins that are not open source

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#167]
So I create a plugin and it gets added to the main app. What if this plugin should not be open sourced? How do we I move it to an internal repo and stil use it in the main Backstage app?

This needs to be documented, and ideally supported in the CLI.

**Comment by Rugvip** [comment]
Should document this as a part of #287. The scaffolded app should be able to create it's own plugins.

**Comment by adamdmharvey** [comment]
Some of this now exists in the https://backstage.io/docs/plugins/ .

But I think specifically closure of this issue involves authoring the page here:

https://backstage.io/docs/plugins/publish-private

![image](https://user-images.githubusercontent.com/33203301/105800214-3675f300-5f64-11eb-968c-8bd475d9a727.png)

Still open for contributors, esp those who may be doing this already.

**Comment by andrewthauer** [comment]
Curious if this publish private page is intended to document just plugins that are published to a private repo and/or for custom plugins within an orgs backstage instances monorepo?

**Comment by freben** [comment]
Both, right? I think the dev experience should be fairly similar.

**Comment by andrewthauer** [comment]
Partially the same I would think. However, separate repos requires more setup and are more work to test from my experience. I don't think there is much of a difference between publishing open ba private in the latter. So probably makes sense to cover all scenarios and rename the docs page accordingly.

**Comment by Parsifal-M** [comment]
Hey Team!

Is anything pending on this? I am sorting the `good first issue` backlog on age to see if I can help cleanup :smile: 

Its not 100% clear to me whats still pending on this... Please let me know if I can help out?

Thanks!

**Comment by Rugvip** [comment]
@Parsifal-M thank you for doing that! 😁

To be honest this one doesn't seem vary actionable at this point, so going to close it. Glad if you want to have a look at a different one though!
