### ISSUE TITLE
🚀 Feature: Allow customisation of text in CatalogKindHeader drop-down

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#16714]
### 🔖 Feature description

Instead of simply calling `pluralize(kind)` as we do now, allow users to override the appearance of names in the catalog table kind filter. 

### 🎤 Context

Kind identifiers, following the generat trend in the cloud-native space, are typically singular in grammar, and in Pascal case (`FooBarBaz`). 

The kind selection dropdown simply pluralizes whatever the kind happens to be. This is suboptimal in a few cases:
1. kinds which are multiple words long. For example, I'm experimenting with adding a kind called `GoldenPath`. Ideally, I would want this to be listed as `Golden Paths`, not `Goldenpaths`, which is the current behaviour.
2. non-standard pluralisations that are not implemented by the `pluralize` function. (Admittedly, I haven't managed to trick it yet ... )

### ✌️ Possible Implementation

- add an optional prop to the component that maps kind identifiers to display name overrides
- integrate it into localisation ... somehow?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
We've actually stopped using this component mostly; it's not put in the view in default scaffolded repos anymore. It had usability / discoverability issues (it wasn't clear that it even was a picker!) and thus we did lean into the kind picker in the side bar instead. So the component is a bit left in a corner one might say. :)

Thinking about it, I wouldn't really mind a `label?: ({ kind: string }) => { label: string }` optional prop on the component so much. Then you can pass in a callback function. That would only point-solve it there though, so if there's other places that do the same thing, they'd need similar props. The ownership cards come to mind. Maybe that's OK to turn a blind eye towards for now.

The other alternative is to either stop using the `CatalogKindHeader`, or to copy-paste its implementation to make your own. [It's fairly small](https://github.com/backstage/backstage/blob/082111cf2eca92712568f9bba6a8794ab1f057dc/plugins/catalog/src/components/CatalogKindHeader/CatalogKindHeader.tsx#L63).

**Comment by tragiclifestories** [comment]
Interesting that it's been taken out of the default app. What's the replacement, just a search filter or something like that?

**Comment by awanlin** [comment]
The `EntityKindPicker` replaced it, for a bit they were both there if I remember correctly, it's been a while: https://github.com/backstage/backstage/blob/7d7ef671194afca91a4156092745ac6606450d3b/plugins/catalog-react/src/components/EntityKindPicker/EntityKindPicker.tsx#L85

If you go to the demo site you'll see it: https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned
