### ISSUE TITLE
🚀 Feature: TechDocs preview

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#16711]
### 🔖 Feature description

As a developer, I would like to see a preview of TechDocs from my PR branch before merging it into the main branch. 

### 🎤 Context

Reviewing documentation changes in the target environment could be made using this kind of feature. Currently, the only possibility is to use the techdocs-cli locally or in CI but it does not support custom theming out-of-the-box which affects the rendering of the documentation a lot. 

### ✌️ Possible Implementation

The TechDocs could take a parameter of GitHub/GitLab/BitBucket address to specific repo and branch and show the preview of the content inside Backstage. Configuration should be also added to disable/enable this feature and maybe from specific integrations only.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by marrws** [comment]
Use the CLI[^1] to preview your documentation before pushing or create an MR/PR. This will serve a skeleton backstage app in `localhost:3000`:

`techdocs-cli serve`

The CLI also supports generating a static site with your docs:

`techdocs-cli generate`

If you don't want to use a docker image, use the `--no-docker` parameter but you'll need `mkdocs` and `mkdocs-techdocs-core` installed from the python `pip` package manager.


[^1]: https://backstage.io/docs/features/techdocs/cli/

**Comment by jtreher** [comment]
I could swear that I saw a presentation with something similar for previewing backstage entities. Maybe I'm just imagining that, and it was only for techdocs.

On initial rollout, there is a lot of experimenting with the catalog-info.yaml and we end up with a lot of churn on branches/PRs to get the right content there. Validation of the YAML isn't a problem, it's more about the content of the YAML.

**Comment by pwalleni** [comment]
TechDocs cli local preview works well for authoring. What needs to be added is the ability to share a server-side preview with a group of PR reviewers.

**Comment by thor** [comment]
Gently bumping the thread to poke the stale bot.

**Comment by thor** [comment]
Another gentle bump to remove the stale tag.

**Comment by camilaibs** [comment]
What are your thoughts, @backstage/techdocs-maintainers?

**Comment by dgiacomo** [comment]
One suggestion for this is to run a staging Backstage and have you CI publication pipeline publish techdocs from PR branches to staging. You can have your CI update the PR with a link to the docs on staging associated to the PR once they get pushed out. This is what I've done internally.

**Comment by dfl-aeb** [comment]
We ended up writing a ci pipeline that builds the docs for merge requests and publishes them to a separate subfolder (versions/) in our S3 storage. Additionally we wrote a Techdocs frontend plugin that checks for this folder and then displays a dropdown with the different versions. It was an enormous effort and in retrospect I thought whether it wouldn't have been more expedient to use read-the-docs.io (like e.g. [ArgoCD does](https://argo-cd.readthedocs.io/en/stable/)) or something similar that has this functionality ootb instead

![image](https://github.com/backstage/backstage/assets/128792991/bb34e57a-fb33-4ad7-a22a-d5556c8d8f37)

I would like to see this feature integrated into Backstage, but I feel that there is not much focus on TechDocs at the moment.

**Comment by kunickiaj** [comment]
> We ended up writing a ci pipeline that builds the docs for merge requests and publishes them to a separate subfolder (versions/) in our S3 storage. Additionally we wrote a Techdocs frontend plugin that checks for this folder and then displays a dropdown with the different versions. It was an enormous effort and in retrospect I thought whether it wouldn't have been more expedient to use read-the-docs.io (like e.g. [ArgoCD does](https://argo-cd.readthedocs.io/en/stable/)) or something similar that has this functionality ootb instead
> 
> ![TechDocs-Versions](https://private-user-images.githubusercontent.com/128792991/324443720-7ad6d964-c8cf-4586-acf0-d54bb66b9e7f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDI1NjMsIm5iZiI6MTcxMzgwMjI2MywicGF0aCI6Ii8xMjg3OTI5OTEvMzI0NDQzNzIwLTdhZDZkOTY0LWM4Y2YtNDU4Ni1hY2YwLWQ1NGJiNjZiOWU3Zi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNjExMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzVmMWExNDM4MWI1ZTUwMDQwNTlhM2E1MDhjNzc4MTcyY2Q3YzU0YWIzODE2NWZlNWI4NDY2ZjUwMjBmNWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CQwh9wnaf7dQ47tTmjU8ZIztraolrOrngYebpatCH_I) [ ![TechDocs-Versions](https://private-user-images.githubusercontent.com/128792991/324443720-7ad6d964-c8cf-4586-acf0-d54bb66b9e7f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDI1NjMsIm5iZiI6MTcxMzgwMjI2MywicGF0aCI6Ii8xMjg3OTI5OTEvMzI0NDQzNzIwLTdhZDZkOTY0LWM4Y2YtNDU4Ni1hY2YwLWQ1NGJiNjZiOWU3Zi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNjExMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzVmMWExNDM4MWI1ZTUwMDQwNTlhM2E1MDhjNzc4MTcyY2Q3YzU0YWIzODE2NWZlNWI4NDY2ZjUwMjBmNWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CQwh9wnaf7dQ47tTmjU8ZIztraolrOrngYebpatCH_I) ](https://private-user-images.githubusercontent.com/128792991/324443720-7ad6d964-c8cf-4586-acf0-d54bb66b9e7f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDI1NjMsIm5iZiI6MTcxMzgwMjI2MywicGF0aCI6Ii8xMjg3OTI5OTEvMzI0NDQzNzIwLTdhZDZkOTY0LWM4Y2YtNDU4Ni1hY2YwLWQ1NGJiNjZiOWU3Zi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNjExMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzVmMWExNDM4MWI1ZTUwMDQwNTlhM2E1MDhjNzc4MTcyY2Q3YzU0YWIzODE2NWZlNWI4NDY2ZjUwMjBmNWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CQwh9wnaf7dQ47tTmjU8ZIztraolrOrngYebpatCH_I) [ ](https://private-user-images.githubusercontent.com/128792991/324443720-7ad6d964-c8cf-4586-acf0-d54bb66b9e7f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDI1NjMsIm5iZiI6MTcxMzgwMjI2MywicGF0aCI6Ii8xMjg3OTI5OTEvMzI0NDQzNzIwLTdhZDZkOTY0LWM4Y2YtNDU4Ni1hY2YwLWQ1NGJiNjZiOWU3Zi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNjExMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzVmMWExNDM4MWI1ZTUwMDQwNTlhM2E1MDhjNzc4MTcyY2Q3YzU0YWIzODE2NWZlNWI4NDY2ZjUwMjBmNWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CQwh9wnaf7dQ47tTmjU8ZIztraolrOrngYebpatCH_I)
> 
> I would like to see this feature integrated into Backstage, but I feel that there is not much focus on TechDocs at the moment.

This is exactly something I've been wanting to build but if it exists it'd be amazing to get merged. Is this built as an Add On?

**Comment by dfl-aeb** [comment]
Yes it is built as a techdocs addon, but still quite hacky and it currently only supports S3 as storage provider. I'm trying to make time for it, but I'm not a react developer myself. If someone helps me with the MR into the community-plugins repo, I'm confident we'll get it merged.

**Comment by kunickiaj** [comment]
> 

Please feel free to open a PR or share a branch and we can help you get through it.

**Comment by drodil** [comment]
Absolutely we can help polish it out 👌

**Comment by pwalleni** [comment]
Can we please re-open? Sounds promising.

**Comment by drodil** [comment]
@freben @Rugvip can we get this re-opened? thanks!

**Comment by dfl-aeb** [comment]
Not stale, not forgotten. Only time is missing.

**Comment by dfl-aeb** [comment]
Sorry for the delay, I finally managed to publish the techdocs addon and the backend part in this repo:
https://github.com/dfl-aeb/backstage-plugin-techdocs-addon-versioning

It includes documentation on how to integrate and use it. Feedback and contributions are welcome!
