### ISSUE TITLE
🐛 Bug Report: the "null" is shown in the kind and type dropdown after upgrade to backstage v1.11.1

### ISSUE THREAD

**Issue by shambhand** [backstage/backstage#16712]
### 📜 Description

After upgrading from backstage v1.4.0 to v1.11.0 the `null` text is shown in the `kind` and `type` dropdowns.

Also, the drop-down text is shown as lowercase instead of Title case

### 👍 Expected behavior

* It should not show null populated in the `kind` and `type` dropdowns.
* It should show the dropdown text in the Title case as in v1.4.0

### 👎 Actual Behavior with Screenshots

<img width="204" alt="Screenshot 2023-03-06 at 5 11 49 PM" src="https://user-images.githubusercontent.com/33409682/223100640-c6d83a45-be5d-4683-928e-82a210430e41.png">
<img width="192" alt="Screenshot 2023-03-06 at 5 11 27 PM" src="https://user-images.githubusercontent.com/33409682/223100657-2fc481b4-6b07-4859-bfc6-370fb5d7f91f.png">

### 👟 Reproduction steps

Upgrade to the backstage from v1.4.0(with some catalog) to v1.11.1

### 📃 Provide the context for the Bug.

This is also reported and discussed in the backstage Discord messages

* https://discord.com/channels/687207715902193673/687207715902193679/1060104878032166942

* https://discord.com/channels/687207715902193673/687235481154617364/1060977432871575752

### 🖥️ Your Environment

OS:   Darwin 21.6.0 - darwin/x64
node: v16.17.0
yarn: 1.22.19
cli:  0.22.3 (installed)
backstage:  1.11.1

Dependencies:
  @backstage/app-defaults                          1.2.0
  @backstage/backend-app-api                       0.4.0
  @backstage/backend-common                        0.18.2
  @backstage/backend-dev-utils                     0.1.0
  @backstage/backend-plugin-api                    0.4.0
  @backstage/backend-tasks                         0.4.3
  @backstage/catalog-client                        1.3.1
  @backstage/catalog-model                         1.2.0
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.3
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.5.0
  @backstage/core-components                       0.12.4
  @backstage/core-plugin-api                       1.4.0
  @backstage/dev-utils                             1.0.12
  @backstage/errors                                1.1.4
  @backstage/eslint-plugin                         0.1.1
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.10
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.9.0
  @backstage/plugin-app-backend                    0.3.42
  @backstage/plugin-auth-backend                   0.18.0
  @backstage/plugin-auth-node                      0.2.11
  @backstage/plugin-catalog-backend-module-github  0.2.5
  @backstage/plugin-catalog-backend                1.7.2
  @backstage/plugin-catalog-common                 1.0.11
  @backstage/plugin-catalog-graph                  0.2.27
  @backstage/plugin-catalog-import                 0.9.5
  @backstage/plugin-catalog-node                   1.3.3
  @backstage/plugin-catalog-react                  1.3.0
  @backstage/plugin-catalog                        1.8.0
  @backstage/plugin-events-node                    0.2.3
  @backstage/plugin-explore-common                 0.0.1
  @backstage/plugin-explore-react                  0.0.26
  @backstage/plugin-explore                        0.4.0
  @backstage/plugin-github-actions                 0.5.15
  @backstage/plugin-home                           0.4.31
  @backstage/plugin-org                            0.6.5
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.5
  @backstage/plugin-permission-react               0.4.10
  @backstage/plugin-proxy-backend                  0.2.36
  @backstage/plugin-scaffolder-backend             1.11.0
  @backstage/plugin-scaffolder-common              1.2.5
  @backstage/plugin-scaffolder-node                0.1.0
  @backstage/plugin-scaffolder-react               1.1.0
  @backstage/plugin-scaffolder                     1.11.0
  @backstage/plugin-search-backend-module-pg       0.5.3
  @backstage/plugin-search-backend-node            1.1.3
  @backstage/plugin-search-backend                 1.2.3
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.5.0
  @backstage/plugin-search                         1.1.0
  @backstage/plugin-tech-radar                     0.6.1
  @backstage/plugin-techdocs-backend               1.5.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.10
  @backstage/plugin-techdocs-node                  1.5.0
  @backstage/plugin-techdocs-react                 1.1.3
  @backstage/plugin-techdocs                       1.5.0
  @backstage/plugin-todo-backend                   0.1.39
  @backstage/plugin-todo                           0.2.17
  @backstage/plugin-user-settings                  0.7.0
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.5
  @backstage/theme                                 0.2.17
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
Hi @shambhand, did you check this conversation: https://discord.com/channels/687207715902193673/1050457284762947686

**Comment by shambhand** [comment]
@drodil I have not looked at that specific message https://github.com/backstage/backstage/issues/16712

but did check the below two which are related.

https://discord.com/channels/687207715902193673/687207715902193679/1060104878032166942

https://discord.com/channels/687207715902193673/687235481154617364/1060977432871575752

My expectation is that it should have been taken care of smoothly in the migration without manual intervention to the DB.

**Comment by shambhand** [comment]
Hi @freben 
I ran the below query(as mention on Discord thread) and able to fix  null entry under the `Kind` Dropdown

```
select count(*) from public.search where key = 'kind' and original_value is null;
select * from public.search where key = 'kind' and original_value is null;

UPDATE public.search SET original_value = 'Group' WHERE key = 'kind' AND original_value is null AND value = 'group';
UPDATE public.search SET original_value = 'System' WHERE key = 'kind' AND original_value is null AND value = 'system';
UPDATE public.search SET original_value = 'API' WHERE key = 'kind' AND original_value is null AND value = 'api';
UPDATE public.search SET original_value = 'Domain' WHERE key = 'kind' AND original_value is null AND value = 'domain';
UPDATE public.search SET original_value = 'Template' WHERE key = 'kind' AND original_value is null AND value = 'template';
UPDATE public.search SET original_value = 'User' WHERE key = 'kind' AND original_value is null AND value = 'user';
UPDATE public.search SET original_value = 'Component' WHERE key = 'kind' AND original_value is null AND value = 'component';
UPDATE public.search SET original_value = 'Resource' WHERE key = 'kind' AND original_value is null AND value = 'resource';
``` 
How to fix the same for API and `Type` dropdown?

**Comment by shambhand** [comment]
Currently I am seeing these two API's are returning null entry.

* /api/catalog/entity-facets?facet=metadata.tags
```
{
	"facets": {
		"spec.type": [{
			"value": "null",
			"count": 1
		}, {
			"value": "graphql",
			"count": 6
		}, {
			"value": "openapi",
			"count": 42
		}]
	}
}
```
* /api/catalog/entity-facets?filter=kind=api&facet=metadata.tags
