### ISSUE TITLE
🚀 Feature: Azure DevOps Discovery - Add branch support

### ISSUE THREAD

**Issue by ymoreiratiti** [backstage/backstage#16745]
### 🔖 Feature description

Add support to use another branch than the default one to search for entity catalog

### 🎤 Context

In my case, we use the git-flow with the production branch as default. 

Our idea is to publish the entity catalog from the development branch. 

We can see that GitHub Discovery support [filters by branch](https://backstage.io/docs/integrations/github/discovery/#configuration), but this seems not to be possible with Azure DevOps

### ✌️ Possible Implementation

I`ve achieved this locally with two changes:

1. Adding `&version=` on the URL generated
https://github.com/backstage/backstage/blob/36e81329174addc261646bae19eeead8d5a0fd93/plugins/catalog-backend-module-azure/src/providers/AzureDevOpsEntityProvider.ts#L181

```typescript
- return encodeURI(`${baseUrl}/_git/${file.repository.name}?path=${file.path}`)
+ return encodeURI(`${baseUrl}/_git/${file.repository.name}?path=${file.path}&version=GB${this.config.branch}`)
```

2. Adding the the desired branch on [Searchable branches](https://learn.microsoft.com/en-us/azure/devops/repos/git/repository-settings?view=azure-devops&tabs=browser#searchable-branches-setting)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ymoreiratiti** [comment]
I created a PR draft on #16749 with the proposal solution.
Need some refinement

**Comment by ymoreiratiti** [comment]
Is this feature already available?

**Comment by awanlin** [comment]
Yes, it should in the `1.12.0` release that just came out today: https://github.com/backstage/backstage/releases/tag/v1.12.0

**Comment by freben** [comment]
Closing as fixed!
