### ISSUE TITLE
🚀 Feature: better docs for `backstage-cli config:check`

### ISSUE THREAD

**Issue by rmartine-ias** [backstage/backstage#16750]
### 🔖 Feature description

You should add information to the config:check documentation that indicates that `--config` must be specified once per config file.

### 🎤 Context

`backstage-cli config:check --help` prints this option:

`--config <path>   Config files to load instead of app-config.yaml (default: [])`

---

This indicated to me that since the default is an empty array, and it said "config file**s**", `--config` takes an array argument. I was confused when:

`backstage-cli config:check --config app-config.yaml app-config.production.yaml`

did not merge the configs, and was ready to write the command off as broken.

---

When writing an issue, I went and read the CLI code -- it turns out the correct invocation was:

`backstage-cli config:check --config app-config.yaml --config app-config.production.yaml`

In hindsight, this is somewhat obvious. The docs say `<path>`, not `<paths>`, and config is loaded when actually running the app with one `--config` per config. But maybe an extra sentence along the lines of "must be specified once per config file" could've saved the headache. That, or printing an error message when invoked with multiple arguments to `--config`, instead of just loading the first one.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Two-dash arguments to _any_ CLI arguably always work like this - your example of space separating the config file names, will always be interpreted as `--config app-config.yaml` as one thing, and then `app-config.production.yaml` as a second thing (a positional argument to the script, not part of any switch.

We could change the text `Config files to load instead of app-config.yaml` to add a clarification that you can provide multiple `--config` flags, but then we'd have to do that for all multi-valued switches on all our CLIs. 🤔

**Comment by rmartine-ias** [comment]
Most of the time, but not *always* -- for example, I was recently using the `cyclonedx` cli, which has `--input-files` as an option to `cyclonedx merge`, which takes multiple arguments: https://github.com/CycloneDX/cyclonedx-cli#merge-command

I'd be in favor of specifying when flags can be multiple, or erroring on unexpected arguments, but can see how that would be a big ask to change everywhere, for fairly small benefit. Maybe you can close as `wontfix` and revisit if this ends up confusing other people?

**Comment by freben** [comment]
Alright, yeah I think we can close then.
