### ISSUE TITLE
🐛 Bug Report: Missing in documentation about identity property in playlist backend plugin

### ISSUE THREAD

**Issue by antoniobergas** [backstage/backstage#16777]
### 📜 Description

Hi Backstage fellas! 

I tried to add the playlist backend plugin following the documentations but the identity property in the PluginEnvironment (types.ts) was missing so my RouterOptions in the playlist.ts was complaining and was not able to compile.

I finally make it work cause I found in the PR of the playlist plugin that I was missing the configuration of DefaultIdentityClient for the PluginEnvironment in the index.ts of the backend (I need to install also the plugin-auth-node)

Could be something that is usually set up? Cause I didn't have it with the default Backstage app

Will be great to clarify if its something missing from the docs of the playlist plugin or something missing in the default configuration of the Backstage backend and fix it if is neccessary.

PD: I think this plugin its super useful for those that are trying to adopt Backstage, make easier and quicker to see a collection of entities from an X module :)

### 👍 Expected behavior

Following all the steps in the documentation of the playlist backend plugin I can successfully add the plugin and compile.

### 👎 Actual Behavior with Screenshots

Identity property doesnt exist in PluginEnvironment at create the playlist.ts
![image](https://user-images.githubusercontent.com/26031467/223817030-4417bd57-4c06-44dd-ab23-c8406d0aa096.png)

### 👟 Reproduction steps

I followed this documentation https://github.com/backstage/backstage/tree/master/plugins/playlist-backend

### 📃 Provide the context for the Bug.

I tried to add the playlist plugin to my Backstage instance

### 🖥️ Your Environment

  @backstage/app-defaults                          1.2.0
  @backstage/backend-app-api                       0.4.0
  @backstage/backend-common                        0.18.2
  @backstage/backend-dev-utils                     0.1.0
  @backstage/backend-plugin-api                    0.4.0
  @backstage/backend-tasks                         0.4.3
  @backstage/catalog-client                        1.3.1
  @backstage/catalog-model                         1.2.0
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.3
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.5.0
  @backstage/core-components                       0.12.4, 0.9.5
  @backstage/core-plugin-api                       1.4.0
  @backstage/errors                                1.1.4
  @backstage/eslint-plugin                         0.1.1
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.10
  @backstage/integration                           1.4.2
  @backstage/plugin-analytics-module-ga            0.1.26
  @backstage/plugin-api-docs                       0.9.0
  @backstage/plugin-app-backend                    0.3.42
  @backstage/plugin-auth-backend                   0.18.0
  @backstage/plugin-auth-node                      0.2.11
  @backstage/plugin-azure-devops-backend           0.3.21
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.2.6
  @backstage/plugin-catalog-backend-module-azure   0.1.13
  @backstage/plugin-catalog-backend                1.7.2
  @backstage/plugin-catalog-common                 1.0.11
  @backstage/plugin-catalog-graph                  0.2.27
  @backstage/plugin-catalog-import                 0.9.5
  @backstage/plugin-catalog-node                   1.3.3
  @backstage/plugin-catalog-react                  1.3.0
  @backstage/plugin-catalog                        1.8.0
  @backstage/plugin-github-actions                 0.5.15
  @backstage/plugin-home                           0.4.31
  @backstage/plugin-org                            0.6.5
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.5
  @backstage/plugin-permission-react               0.4.10
  @backstage/plugin-playlist-backend               0.2.5
  @backstage/plugin-playlist-common                0.1.4
  @backstage/plugin-playlist                       0.1.6
  @backstage/plugin-proxy-backend                  0.2.36
  @backstage/plugin-scaffolder-backend             1.11.0
  @backstage/plugin-scaffolder-common              1.2.5
  @backstage/plugin-scaffolder-node                0.1.0
  @backstage/plugin-scaffolder-react               1.1.0
  @backstage/plugin-scaffolder                     1.11.0
  @backstage/plugin-search-backend-module-pg       0.5.3
  @backstage/plugin-search-backend-node            1.1.3
  @backstage/plugin-search-backend                 1.2.3
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.5.0
  @backstage/plugin-search                         1.1.0
  @backstage/plugin-shortcuts                      0.3.7
  @backstage/plugin-sonarqube-backend              0.1.7
  @backstage/plugin-sonarqube-react                0.1.3
  @backstage/plugin-sonarqube                      0.6.4
  @backstage/plugin-tech-radar                     0.6.1
  @backstage/plugin-techdocs-backend               1.5.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.10
  @backstage/plugin-techdocs-node                  1.5.0
  @backstage/plugin-techdocs-react                 1.1.3
  @backstage/plugin-techdocs                       1.5.0
  @backstage/plugin-user-settings                  0.7.0
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.5
  @backstage/theme                                 0.2.17
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by kuangp** [comment]
hmm the `identity` prop of the `PluginEnvironment` interface is actually already included in the default Backstage template: https://github.com/backstage/backstage/blob/1af49d62e78b470898238be1f0ecb455dbcc9a85/packages/create-app/templates/default-app/packages/backend/src/types.ts#L24

Perhaps you scaffolded out your Backstage app before this was updated? (change looks like it was made back in Sept. 2022)


PS: glad to hear you like this plugin 😄

**Comment by antoniobergas** [comment]
Thats answer why it was failing, thanks a lot :)

Does exist some mechanism to check differences between my current app and the default template? Can this happen frequently?

**Comment by antoniobergas** [comment]
I did some googling and I found this <https://backstage.github.io/upgrade-helper/>

Thanks a lot again and sorry for the misunderstanding!
