### ISSUE TITLE
🐛 Bug Report: NextScaffolderPage shows a timer under skipped steps

### ISSUE THREAD

**Issue by afalco103** [backstage/backstage#16772]
### 📜 Description

The /create/tasks page in scaffolder alpha is showing skipped steps as still running by displaying a timer thats counting up.

### 👍 Expected behavior

If I have template steps that get skipped when triggering a template, I would expect the tasks page to show a clear indication that they are not running and were in fact skipped.

### 👎 Actual Behavior with Screenshots

I get what appears to be a skipped icon (circle with dash in middle) but I also get a timer under the icon which makes it appear like the task is still running, and my interpretation of the icon becomes 'incomplete' instead of 'skipped'. 

![image](https://user-images.githubusercontent.com/5334229/223765184-5a251976-c9f1-496a-8829-b70e6e96600a.png)

logs
```
[53](http://localhost:3000/create/tasks/b10575ba-2f0c-4fe5-b354-5641618755e9#line-53)2023-03-08T15:52:31.367Z Beginning step Register Repository Ownership[54](http://localhost:3000/create/tasks/b10575ba-2f0c-4fe5-b354-5641618755e9#line-54)2023-03-08T15:52:31.371Z Skipping step registerRepositoryOwnership because its if condition was false[55](http://localhost:3000/create/tasks/b10575ba-2f0c-4fe5-b354-5641618755e9#line-55)2023-03-08T15:52:31.372Z Beginning step Configure Deployment[56](http://localhost:3000/create/tasks/b10575ba-2f0c-4fe5-b354-5641618755e9#line-56)2023-03-08T15:52:31.376Z Skipping step configureDeployment because its if condition was false
```

### 👟 Reproduction steps

Run a template with some steps you expect to be skipped. It's possible these skipped steps need to be at the end of the template, I have not tested it with skipped steps that are in the middle and get followed by steps that run and complete. I would imagine its very possible the skip displays as intended there.

### 📃 Provide the context for the Bug.

A user running a template would like a clear confirmation that their task is done, even if steps are skipped. The small green bar is usually sufficient, but the timer counting up under the skipped steps contradicts it. An appropriate fix here would be to ensure the timer doesnt show under skipped steps.

### 🖥️ Your Environment

Chrome Version 110.0.5481.177 (Official Build) (x86_64)
```
% yarn backstage-cli info
yarn run v1.22.19
...
OS:   Darwin 22.3.0 - darwin/x64
node: v16.19.0
yarn: 1.22.19
cli:  0.22.3 (installed)
backstage:  1.11.0

Dependencies:
  @backstage/app-defaults                 1.2.0
  @backstage/backend-app-api              0.4.0
  @backstage/backend-common               0.18.2
  @backstage/backend-dev-utils            0.1.0
  @backstage/backend-plugin-api           0.4.0
  @backstage/backend-tasks                0.4.3
  @backstage/catalog-client               1.3.1
  @backstage/catalog-model                1.2.0
  @backstage/cli-common                   0.1.11
  @backstage/cli                          0.22.3
  @backstage/config-loader                1.1.8
  @backstage/config                       1.0.6
  @backstage/core-app-api                 1.5.0
  @backstage/core-components              0.12.4
  @backstage/core-plugin-api              1.4.0
  @backstage/dev-utils                    1.0.12
  @backstage/errors                       1.1.4
  @backstage/eslint-plugin                0.1.1
  @backstage/integration-aws-node         0.1.1
  @backstage/integration-react            1.1.10
  @backstage/integration                  1.4.2
  @backstage/plugin-api-docs              0.9.0
  @backstage/plugin-app-backend           0.3.42
  @backstage/plugin-auth-backend          0.18.0
  @backstage/plugin-auth-node             0.2.11
  @backstage/plugin-catalog-backend       1.7.2
  @backstage/plugin-catalog-common        1.0.11
  @backstage/plugin-catalog-graph         0.2.27
  @backstage/plugin-catalog-import        0.9.5
  @backstage/plugin-catalog-node          1.3.3
  @backstage/plugin-catalog-react         1.3.0
  @backstage/plugin-catalog               1.8.0
  @backstage/plugin-circleci              0.3.15
  @backstage/plugin-cost-insights-common  0.1.1
  @backstage/plugin-cost-insights         0.12.4
  @backstage/plugin-github-actions        0.5.15
  @backstage/plugin-home                  0.4.31
  @backstage/plugin-org                   0.6.5
  @backstage/plugin-permission-backend    0.5.17
  @backstage/plugin-permission-common     0.7.3
  @backstage/plugin-permission-node       0.7.5
  @backstage/plugin-permission-react      0.4.10
  @backstage/plugin-proxy-backend         0.2.36
  @backstage/plugin-scaffolder-backend    1.11.0
  @backstage/plugin-scaffolder-common     1.2.5
  @backstage/plugin-scaffolder-node       0.1.0
  @backstage/plugin-scaffolder-react      1.1.0
  @backstage/plugin-scaffolder            1.11.0
  @backstage/plugin-search-backend-node   1.1.3
  @backstage/plugin-search-backend        1.2.3
  @backstage/plugin-search-common         1.2.1
  @backstage/plugin-search-react          1.5.0
  @backstage/plugin-search                1.1.0
  @backstage/plugin-techdocs-backend      1.5.3
  @backstage/plugin-techdocs-node         1.5.0
  @backstage/plugin-techdocs-react        1.1.3
  @backstage/plugin-techdocs              1.5.0
  @backstage/plugin-user-settings-backend 0.1.6
  @backstage/plugin-user-settings         0.7.0
  @backstage/release-manifests            0.0.8
  @backstage/test-utils                   1.2.5
  @backstage/theme                        0.2.17
  @backstage/types                        1.0.2
  @backstage/version-bridge               1.0.3
✨  Done in 1.58s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Sounds like a bug! Happy to accept a PR 🙏

**Comment by afalco103** [comment]
Taking this issue on then!

**Comment by afalco103** [comment]
Looking at the code base, there's a couple ways to resolve this. One would be to provided skipped steps with an 'endedAt' value so the front end component recognizes them as complete, however without knowing if there's an existing reason to keep that field null for them I dont want to presume that's a safe thing to do. Otherwise I can add a status check to the StepTime component in /next easily enough. Any recommendation here?

**Comment by afalco103** [comment]
gonna go with the latter in the mean time, since it seems like the easy fix here
