### ISSUE TITLE
🚀 Feature: Playlist dynamic UI naming

### ISSUE THREAD

**Issue by antoniobergas** [backstage/backstage#16789]
### 🔖 Feature description

I wanna propose to make dynamic the naming in the UI of the plugin Playlist

### 🎤 Context

This plugin its super useful and looks like you can use it in a sort of ways,  depending on that, can be confuse to the users the naming of "Playlists" in all the components of the UI (In our case something like Modules or Collections make it self-explanatory for what we wanna use it that its just grouping entities).

The purpose of this change it's to facilitate the understanding of the plugin for new adopters. Does that make sense for the rest?

### ✌️ Possible Implementation

Add a shared parameter through all the components of the Playlist UI that include a plugin-name and be able to replace the naming everywhere on the UI just like other components usually have (like the HomePageToolkit)
![image](https://user-images.githubusercontent.com/26031467/224044693-2d058bf4-6ad8-4270-b048-b01bda94efad.png)
![image](https://user-images.githubusercontent.com/26031467/224044838-3f2cdfdf-4439-4787-a95f-2e6706395f89.png)

E.g:
export const PlaylistIndexPage = (props: PlaylistProps) => (
  <PageWithHeader themeId="home" title="{{ props.pluginName }}">
   

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by antoniobergas** [comment]
Great to hear that we agree :) 

I don't have that much experience with React and never make any contribution to Backstage at all (so kinda new about how everything works internally) But I can make a try at least.

Documentation to start it's on the official backstage.io docs?

**Comment by kuangp** [comment]
Best place to start would probably be taking a look at the [contributing docs](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md)!

For this specific change the following docs will also be helpful:
- https://backstage.io/docs/conf/defining
- https://backstage.io/docs/conf/reading#accessing-configapi-in-frontend-plugins

The source for this plugin is here: https://github.com/backstage/backstage/tree/master/plugins/playlist, if you note which areas of the UI displays the name "Playlist" that should be configured dynamically, I can help guide you to the actual component source

**Comment by antoniobergas** [comment]
Thanks I'll give it a try when I have time

**Comment by antoniobergas** [comment]
Hi @kuangp, sorry for the dumb question but which is the best way should I start to trying to contribute without having permissions?

Just create my local branch? Fork the repo and add the upstream dependency?

**Comment by antoniobergas** [comment]
Hi @kuangp 

Something like this it's what you had in mind?
![image](https://user-images.githubusercontent.com/26031467/226106380-f8345e59-6284-46be-a307-2bdaa7b2f087.png)

![image](https://user-images.githubusercontent.com/26031467/226106397-5e9a4d2a-c35f-4451-837c-f89467895182.png)

![image](https://user-images.githubusercontent.com/26031467/226106406-95241f90-f9e4-4db5-8011-6c3232083bca.png)

![image](https://user-images.githubusercontent.com/26031467/226106422-eb683dc8-be56-4715-8da2-9280c7131a00.png)

So in this case we will need the plural and singular for cover all the components of the plugin and also maybe it's redundant to duplicate the call to the config.

As I mentioned not to much experienced in React so what you think it's the best way to have such a utils place where declare 2 global variables plural and singular (in this case maybe its enough to build the string from the groupName) to spread over the components?

Thanks for the help :)

**Comment by antoniobergas** [comment]
Forget about the last part, that will not work depending of what you want to use as naming. 😅

I will start easy, with 2 paremeters 1 per plural and 1 for singular and use theGetOptinalString in the needed components.

Let me know any suggestions to do it better😁

**Comment by antoniobergas** [comment]
I made a PR, I tried to follow all the guidelines but maybe I forgot something, review will be appreciated :)
