### ISSUE TITLE
🐛 Bug Report: close button in search popup window doesn't work properly

### ISSUE THREAD

**Issue by giocolas** [backstage/backstage#16797]
### 📜 Description

When you select the search function from the sidebar a pop-up form opens and if you want to close this window with the close button at the top right, clicking on the button does not close the window. If you press the ESC key on the keyboard then form closes correctly!

### 👍 Expected behavior

Popup form can be closed when you click on the close button

### 👎 Actual Behavior with Screenshots

Popup form does not close
![SearchCloseButtonDoNotFunctionProperly](https://user-images.githubusercontent.com/38323213/224102059-03b53eeb-1d27-4d62-8df4-805d06c74cea.png)

### 👟 Reproduction steps

1. Create a new backstage app with command: "npx @backstage/create-app"
2. Wait app creation completely until message "successfully created"
3. Run app with command "yarn dev"
4. Wait browser open new page with url "http://localhost:3000" and shows Backstage initial screen
5. Click "Search" on the sidebar
6. **Click close button** => **popup form does not close!**
7. Only way to close search popup form is to press ESC key on the keyboard

### 📃 Provide the context for the Bug.

I am upgrading to the latest version (1.11.1) and I would like the whole system and all features to work properly.

### 🖥️ Your Environment

OS:   Darwin 22.3.0 - darwin/x64
node: v16.17.0
yarn: 1.22.5
cli:  0.22.3 (installed)
backstage:  1.11.0

Dependencies:
  @backstage/app-defaults                          1.2.0
  @backstage/backend-app-api                       0.4.0
  @backstage/backend-common                        0.18.2
  @backstage/backend-dev-utils                     0.1.0
  @backstage/backend-plugin-api                    0.4.0
  @backstage/backend-tasks                         0.4.3
  @backstage/catalog-client                        1.3.1
  @backstage/catalog-model                         1.2.0
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.3
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.5.0
  @backstage/core-components                       0.12.4
  @backstage/core-plugin-api                       1.4.0
  @backstage/errors                                1.1.4
  @backstage/eslint-plugin                         0.1.1
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.10
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.9.0
  @backstage/plugin-app-backend                    0.3.42
  @backstage/plugin-auth-backend                   0.18.0
  @backstage/plugin-auth-node                      0.2.11
  @backstage/plugin-catalog-backend                1.7.2
  @backstage/plugin-catalog-common                 1.0.11
  @backstage/plugin-catalog-graph                  0.2.27
  @backstage/plugin-catalog-import                 0.9.5
  @backstage/plugin-catalog-node                   1.3.3
  @backstage/plugin-catalog-react                  1.3.0
  @backstage/plugin-catalog                        1.8.0
  @backstage/plugin-github-actions                 0.5.15
  @backstage/plugin-org                            0.6.5
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.5
  @backstage/plugin-permission-react               0.4.10
  @backstage/plugin-proxy-backend                  0.2.36
  @backstage/plugin-scaffolder-backend             1.11.0
  @backstage/plugin-scaffolder-common              1.2.5
  @backstage/plugin-scaffolder-node                0.1.0
  @backstage/plugin-scaffolder-react               1.1.0
  @backstage/plugin-scaffolder                     1.11.0
  @backstage/plugin-search-backend-module-pg       0.5.3
  @backstage/plugin-search-backend-node            1.1.3
  @backstage/plugin-search-backend                 1.2.3
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.5.0
  @backstage/plugin-search                         1.1.0
  @backstage/plugin-tech-radar                     0.6.1
  @backstage/plugin-techdocs-backend               1.5.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.10
  @backstage/plugin-techdocs-node                  1.5.0
  @backstage/plugin-techdocs-react                 1.1.3
  @backstage/plugin-techdocs                       1.5.0
  @backstage/plugin-user-settings                  0.7.0
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.5
  @backstage/theme                                 0.2.17
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @giocolas, I think there may be another issue logged for this, I'll try and find it. But the problem is that the "X" isn't the close button but is used to clear the search box which is clearly confusing. The dialog will also close if you click anywhere outside of it.

**Comment by awanlin** [comment]
This was the issue I was thinking of: https://github.com/backstage/backstage/issues/15717

**Comment by awanlin** [comment]
Sweet, even found a PR with a fix to improve this here: https://github.com/backstage/backstage/pull/16647

**Comment by giocolas** [comment]
ok @awanlin, so I think this issue can be closed!
