### ISSUE TITLE
🐛 Bug Report: aperture theme is not user friendly

### ISSUE THREAD

**Issue by db-cataloge-db** [backstage/backstage#16812]
### 📜 Description

Aperture theme is not user friendly

### 👍 Expected behavior

The backstage header contains the href's/ links which is not visible

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/115448749/224363139-6e33d6a4-dbfb-423b-846d-2c020f429c51.png)

### 👟 Reproduction steps

Enable "aperture" theme

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by timbonicus** [comment]
Definitely not intentional, good spot @db-cataloge-db! Fixes are referenced above, one component correction in the main repo and some additional overrides on the demo site.
