### ISSUE TITLE
🚀 Feature: Drone CI plugin

### ISSUE THREAD

**Issue by cmcdowell-red** [backstage/backstage#16827]
### 🔖 Feature description

A CI/CD plugin for the Drone CI tool.

### 🎤 Context

I want to be able to see and interact with the Drone CI/CD tool in the CI/CD tab of the component entity page.
This includes:

- Viewing an overview of recent builds
  - commit message and hash of commit that triggered the build
  - status of the build (success/failed/running) etc.
  - build duration
  - build timestamp
- Viewing the detail of a particular build 
  - everything from the overview page
  - logs for each build step
- Ability to terminate/restart builds

### ✌️ Possible Implementation

Drone provides an [API](https://docs.drone.io/api/overview/) that can be used to achieve all the use cases for this plugin. The implementation could use the api and create front-end components to be used in the backstage app. This would be very similar to the Circle-CI plugin.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by timbze** [comment]
Looks like Drone (Harness) may have built this already. I did not test yet: https://github.com/harness/backstage-plugins
