### ISSUE TITLE
Upgrade an Existing Backstage App via CLI

### ISSUE THREAD

**Issue by javaniecampbell** [backstage/backstage#1682]
## Feature Suggestion
Hey guys just released something, shouldn't the `cli` support upgrading an existing version of backstage app and/or have a way of upgrading the version so as to get the benefits of the community?

## Possible Implementation
```bash
npx @backstage/cli upgrade
```

```bash
npx @backstage/cli upgrade --version 1.0.8
```

**Comment by tragiclifestories** [comment]
Having just had an 'interesting' afternoon with this problem, I think it would be a good idea. 

Doing it robustly would introduce ongoing maintenance burden for releases (automating the bump I just did would require changing a bunch of dependency versions and codemods for several scaffolded TS files, for example), so it may be too early in the project's lifestyle to implement right now. But automation around this is a lifesaver in comparable scenarios (eg upgrading major versions of a framework like React or Ember or whatever).

**Comment by freben** [comment]
@tragiclifestories there's now a `yarn backstage-cli versions:bump` - did you try that one out?

**Comment by freben** [comment]
@Rugvip is this one covered by #3391 and ready to close?

**Comment by Rugvip** [comment]
It's not possible to bump to a specific version, but at this point that's just more of a missing feature to be implemented than something that's super tricky :p. It also doesn't attempt any form of codemods, although I have a pending change that'll link to the changelogs of any `@backstage` packages that could have breaking changes.

The command is now at least also documented in the FAQ too, so thinking we could close.
