### ISSUE TITLE
[Plugin] BACKSTAGE PACKAGE MANAGER PLUGIN AKA UPGRADE PLUGINS & BACKSTAGE VIA UI

### ISSUE THREAD

**Issue by javaniecampbell** [backstage/backstage#1683]
## Summary
Hey guys just released something, it would be great support to have a plugin that handles upgrading an existing version of backstage app and/or components via UI. 

Should have a way via a page added after plugin is installed to upgrading the version of a component/plugin or viewing list of installed components/plugins with the currently installed version displayed and a potential selection list of newer versions to upgrade/downgrade to so as to get the benefits of the community support. 

Should allow for searching of available plugins available via npm repository tagged as backstage plugins or via git repository and selected to be installed into backstage app.

**Comment by soapraj** [comment]
Hey! @javaniecampbell 

Great suggestion :)

Are you planning to work on this? or currently, taking a stab at this? If so do you want me to assign this to you?

We do plan to work on this at a later point in the roadmap. Feel free to add any more ideas you have around this to this issue.

**Comment by javaniecampbell** [comment]
Hey @soapraj

Thanks, I am currently still wrapping my head around the code base i understand some parts of it but it is a bit over my head currently. I recognize a lot of the patterns used in the core, common and backend but it's a lot to go through currently this one is above my head currently.

But I believe this would be heavily dependent on the cli api or an api endpoint that can list existing packages/plugins from some plugin registry so that mean a potential addition to the backend maybe.
