### ISSUE TITLE
🐛 Bug Report: Codemod

### ISSUE THREAD

**Issue by SorsOps** [backstage/backstage#16839]
### 📜 Description

Running `npx @backstage/codemods apply core-imports packages plugins ` on a freshly created backstage app via `@backstage/create-app` throws errors around missing deps 

### 👍 Expected behavior

It should perform the code modifications without error 

### 👎 Actual Behavior with Screenshots

Throws errors relating to missing dependencies. See the context below.
```
<REDACTED>\backstage\backstage>npx @backstage/codemods apply core-imports packages/app/src
Running jscodeshift with these arguments: --parser=tsx --extensions=tsx,js,ts,tsx --transform <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\@backstage\codemods\transforms\core-imports.js --ignore-pattern=**/node_modules/** packages/app/src
Processing 12 files... 
Spawning 11 workers...
Sending 2 files to free worker...
Sending 2 files to free worker...
Sending 2 files to free worker...
Sending 2 files to free worker...
Sending 2 files to free worker...
Sending 2 files to free worker...
 ERR packages\app\src\apis.ts Transformation error (Cannot find module 'lodash' Require stack: - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\Worker.js)
Error: Cannot find module 'lodash'
Require stack:
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js
 ERR packages\app\src\index.tsx Transformation error (Cannot find module 'lodash' Require stack: - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\Worker.js)
Error: Cannot find module 'lodash'
Require stack:
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js
 ERR packages\app\src\App.test.tsx Transformation error (Cannot find module 'lodash' Require stack: - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\Worker.js)
Error: Cannot find module 'lodash'
Require stack:
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js
 ERR packages\app\src\App.tsx Transformation error (Cannot find module 'lodash' Require stack: - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\Worker.js)
Error: Cannot find module 'lodash'
Require stack:
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js
 ERR packages\app\src\auth.tsx Transformation error (Cannot find module 'lodash' Require stack: - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\Worker.js)
Error: Cannot find module 'lodash'
Require stack:
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js
 ERR packages\app\src\setupTests.ts Transformation error (Cannot find module 'lodash' Require stack: - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\Worker.js)
Error: Cannot find module 'lodash'
Require stack:
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js
 ERR packages\app\src\components\Root\LogoIcon.tsx Transformation error (Cannot find module 'lodash' Require stack: - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\Worker.js)
Error: Cannot find module 'lodash'
Require stack:
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js
 ERR packages\app\src\components\Root\index.ts Transformation error (Cannot find module 'lodash' Require stack: - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\Worker.js)
Error: Cannot find module 'lodash'
Require stack:
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js
 ERR packages\app\src\components\Root\LogoFull.tsx Transformation error (Cannot find module 'lodash' Require stack: - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\Worker.js)
Error: Cannot find module 'lodash'
Require stack:
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js
 ERR packages\app\src\components\Root\Root.tsx Transformation error (Cannot find module 'lodash' Require stack: - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\Worker.js)
Error: Cannot find module 'lodash'
Require stack:
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js
 ERR packages\app\src\components\catalog\EntityPage.tsx Transformation error (Cannot find module 'lodash' Require stack: - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\Worker.js)
Error: Cannot find module 'lodash'
Require stack:
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js
 ERR packages\app\src\components\search\SearchPage.tsx Transformation error (Cannot find module 'lodash' Require stack: - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js - <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\Worker.js)
Error: Cannot find module 'lodash'
Require stack:
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\parser\tsx.js
- <REDACTED>\AppData\Local\npm-cache\_npx\d4a7efee46ae6348\node_modules\jscodeshift\src\getParser.js
```

 Specifically `lodash`

### 👟 Reproduction steps

npx @backstage/create-app
cd backstage 
npx @backstage/codemods apply core-imports packages plugins

### 📃 Provide the context for the Bug.

Looking at [jscodeshift](https://www.npmjs.com/package/jscodeshift?activeTab=dependencies) I see that lodash is not listed as a direct dependency despite it requiring it in the dist 

![image](https://user-images.githubusercontent.com/80043879/224942491-73c5bff5-256b-4d6d-ba37-80c9c394f9c5.png)

I believe adding lodash as a direct dependency will work to fix the issue for now , but looks like this needs a PR opened with the upstream

### 🖥️ Your Environment

$ backstage-cli info
OS:   Windows_NT 10.0.19044 - win32/x64
node: v18.12.1
yarn: 1.22.19
cli:  0.22.3 (installed)
backstage:  1.11.0      

Dependencies:
  @backstage/app-defaults                          1.2.0
  @backstage/backend-app-api                       0.4.0 
  @backstage/backend-common                        0.18.2
  @backstage/backend-dev-utils                     0.1.0 
  @backstage/backend-plugin-api                    0.4.0 
  @backstage/backend-tasks                         0.4.3 
  @backstage/catalog-client                        1.3.1 
  @backstage/catalog-model                         1.2.0 
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.3
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.5.0
  @backstage/core-components                       0.12.4
  @backstage/core-plugin-api                       1.4.0
  @backstage/errors                                1.1.4
  @backstage/eslint-plugin                         0.1.1
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.10
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.9.0
  @backstage/plugin-app-backend                    0.3.42
  @backstage/plugin-auth-backend                   0.18.0
  @backstage/plugin-auth-node                      0.2.11
  @backstage/plugin-catalog-backend-module-github  0.2.5
  @backstage/plugin-catalog-backend                1.7.2
  @backstage/plugin-catalog-common                 1.0.11
  @backstage/plugin-catalog-graph                  0.2.27
  @backstage/plugin-catalog-import                 0.9.5
  @backstage/plugin-catalog-node                   1.3.3
  @backstage/plugin-catalog-react                  1.3.0
  @backstage/plugin-catalog                        1.8.0
  @backstage/plugin-events-node                    0.2.3
  @backstage/plugin-github-actions                 0.5.15
  @backstage/plugin-org                            0.6.5
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.5
  @backstage/plugin-permission-react               0.4.10
  @backstage/plugin-proxy-backend                  0.2.36
  @backstage/plugin-scaffolder-backend             1.11.0
  @backstage/plugin-scaffolder-common              1.2.5
  @backstage/plugin-scaffolder-node                0.1.0
  @backstage/plugin-scaffolder-react               1.1.0
  @backstage/plugin-scaffolder                     1.11.0
  @backstage/plugin-search-backend-module-pg       0.5.3
  @backstage/plugin-search-backend-node            1.1.3
  @backstage/plugin-search-backend                 1.2.3
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.5.0
  @backstage/plugin-search                         1.1.0
  @backstage/plugin-tech-radar                     0.6.1
  @backstage/plugin-techdocs-backend               1.5.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.10
  @backstage/plugin-techdocs-node                  1.5.0
  @backstage/plugin-techdocs-react                 1.1.3
  @backstage/plugin-techdocs                       1.5.0
  @backstage/plugin-user-settings                  0.7.0
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.5
  @backstage/theme                                 0.2.17
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
Done in 0.94s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by SorsOps** [comment]
Created an issue on the jscodeshift repo https://github.com/facebook/jscodeshift/issues/550

**Comment by SorsOps** [comment]
I believe so, however lodash is a heavy package, whilst it would be a temporary fix, it does add some overhead https://bundlephobia.com/package/lodash@4.17.21

Also looking at why lodash is there, its only there as part of their transpilation effort to support `...` spreads, the jscodeshift team need to update their compilation flow to either inline operations like that as a part of a polyfill  or at least note the additional runtime libs its using to support <ES6

**Comment by Daniel15** [comment]
Which version of jscodeshift are you using? lodash hasn't been required since jscodeshift 0.13.0, released on 2021-06-26.
