### ISSUE TITLE
🐛 Bug Report: Running backstage locally

### ISSUE THREAD

**Issue by Vegim** [backstage/backstage#16832]
### 📜 Description

I recently updated backsage packages using bump command and now cannot install packages using yarn install anymore.

### 👍 Expected behavior

Should successfully install all the dependencies.

### 👎 Actual Behavior with Screenshots

esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: C:\Users\vegim_l\Documents\repos\backstage\node_modules\esbuild-loader\node_modules\esbuild
Output:
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: C:\Program Files\nodejs\node.exe C:\Users\vegim_l\Documents\repos\backstage\node_modules\esbuild-loader\node_modules\esbuild\bin\esbuild --version
node:child_process:924
    throw err;
    ^

<ref *1> Error: spawnSync C:\Users\vegim_l\Documents\repos\backstage\node_modules\esbuild-windows-64\esbuild.exe UNKNOWN
    at Object.spawnSync (node:internal/child_process:1110:20)
    at spawnSync (node:child_process:871:24)
    at Object.execFileSync (node:child_process:914:15)
    at Object.<anonymous> (C:\Users\vegim_l\Documents\repos\backstage\node_modules\esbuild-loader\node_modules\esbuild\bin\esbuild:209:28)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawnSync C:\\Users\\vegim_l\\Documents\\repos\\backstage\\node_modules\\esbuild-windows-64\\esbuild.exe',
  path: 'C:\\Users\\vegim_l\\Documents\\repos\\backstage\\node_modules\\esbuild-windows-64\\esbuild.exe',
  spawnargs: [ '--version' ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}

Node.js v18.15.0

    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at validateBinaryVersion (C:\Users\vegim_l\Documents\repos\backstage\node_modules\esbuild-loader\node_modules\esbuild\install.js:90:32)
    at C:\Users\vegim_l\Documents\repos\backstage\node_modules\esbuild-loader\node_modules\esbuild\install.js:241:5 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(1323) [Uint8Array] [
      110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
      114, 111,  99, 101, 115, 115,  58,  57,  50,  52,  13,  10,
       32,  32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114,
      114,  59,  13,  10,  32,  32,  32,  32,  94,  13,  10,  13,
       10,  60, 114, 101, 102,  32,  42,  49,  62,  32,  69, 114,
      114, 111, 114,  58,  32, 115, 112,  97, 119, 110,  83, 121,
      110,  99,  32,  67,  58,  92,  85, 115, 101, 114, 115,  92,
      118, 101, 103, 105, 109,  95, 108,  92,  68, 111,  99, 117,
      109, 101, 110, 116,
      ... 1223 more items
    ]
  ],
  pid: 20508,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(1323) [Uint8Array] [
    110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
    114, 111,  99, 101, 115, 115,  58,  57,  50,  52,  13,  10,
     32,  32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114,
    114,  59,  13,  10,  32,  32,  32,  32,  94,  13,  10,  13,
     10,  60, 114, 101, 102,  32,  42,  49,  62,  32,  69, 114,
    114, 111, 114,  58,  32, 115, 112,  97, 119, 110,  83, 121,
    110,  99,  32,  67,  58,  92,  85, 115, 101, 114, 115,  92,
    118, 101, 103, 105, 109,  95, 108,  92,  68, 111,  99, 117,
    109, 101, 110, 116,
    ... 1223 more items
  ]

### 👟 Reproduction steps

Update backstage packages using cli bump command.
Execute yarn install with node 18.15.0 and windows 10 machine. 

### 📃 Provide the context for the Bug.

I'm blocked doing local developments because of this bug.

### 🖥️ Your Environment

  @backstage/app-defaults                               1.2.0
  @backstage/backend-app-api                            0.4.0
  @backstage/backend-common                             0.18.2
  @backstage/backend-dev-utils                          0.1.0
  @backstage/backend-plugin-api                         0.4.0
  @backstage/backend-tasks                              0.4.3
  @backstage/catalog-client                             1.3.1
  @backstage/catalog-model                              1.2.0
  @backstage/cli-common                                 0.1.11
  @backstage/cli                                        0.22.3
  @backstage/config-loader                              1.1.8
  @backstage/config                                     0.1.15, 1.0.6
  @backstage/core-api                                   0.2.23
  @backstage/core-app-api                               1.5.0
  @backstage/core-components                            0.12.4
  @backstage/core-plugin-api                            0.1.13, 1.4.0
  @backstage/core                                       0.7.14
  @backstage/dev-utils                                  1.0.12
  @backstage/errors                                     0.1.5, 1.1.4
  @backstage/eslint-plugin                              0.1.1
  @backstage/integration-aws-node                       0.1.1
  @backstage/integration-react                          1.1.10
  @backstage/integration                                1.4.2
  @backstage/plugin-api-docs                            0.9.0
  @backstage/plugin-app-backend                         0.3.42
  @backstage/plugin-auth-backend                        0.18.0
  @backstage/plugin-auth-node                           0.2.11
  @backstage/plugin-bitbucket-cloud-common              0.2.3
  @backstage/plugin-catalog-backend-module-bitbucket    0.2.9
  @backstage/plugin-catalog-backend-module-github       0.2.5
  @backstage/plugin-catalog-backend                     1.7.2
  @backstage/plugin-catalog-common                      1.0.11
  @backstage/plugin-catalog-graph                       0.2.27
  @backstage/plugin-catalog-import                      0.9.5
  @backstage/plugin-catalog-node                        1.3.3
  @backstage/plugin-catalog-react                       1.3.0
  @backstage/plugin-catalog                             1.8.0
  @backstage/plugin-cost-insights-common                0.1.1
  @backstage/plugin-cost-insights                       0.12.4
  @backstage/plugin-events-node                         0.2.3
  @backstage/plugin-github-actions                      0.5.15
  @backstage/plugin-org                                 0.6.5
  @backstage/plugin-permission-common                   0.7.3
  @backstage/plugin-permission-node                     0.7.5
  @backstage/plugin-permission-react                    0.4.10
  @backstage/plugin-proxy-backend                       0.2.36
  @backstage/plugin-scaffolder-backend                  1.11.0
  @backstage/plugin-scaffolder-common                   1.2.5
  @backstage/plugin-scaffolder-node                     0.1.0
  @backstage/plugin-scaffolder-react                    1.1.0
  @backstage/plugin-scaffolder                          1.11.0
  @backstage/plugin-search-backend-module-pg            0.5.3
  @backstage/plugin-search-backend-node                 1.1.3
  @backstage/plugin-search-backend                      1.2.3
  @backstage/plugin-search-common                       1.2.1
  @backstage/plugin-search-react                        1.5.0
  @backstage/plugin-search                              1.1.0
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.26
  @backstage/plugin-tech-insights-backend               0.5.8
  @backstage/plugin-tech-insights-common                0.2.10
  @backstage/plugin-tech-insights-node                  0.4.0
  @backstage/plugin-tech-insights                       0.3.7
  @backstage/plugin-tech-radar                          0.6.1
  @backstage/plugin-techdocs-backend                    1.5.3
  @backstage/plugin-techdocs-node                       1.5.0
  @backstage/plugin-techdocs-react                      1.1.3
  @backstage/plugin-techdocs                            1.5.0
  @backstage/plugin-user-settings                       0.7.0
  @backstage/release-manifests                          0.0.8
  @backstage/test-utils                                 1.2.5
  @backstage/theme                                      0.2.17
  @backstage/types                                      0.1.3, 1.0.2
  @backstage/version-bridge                             0.1.2, 1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Hm that's odd - the end-to-end tests run on windows with that exact same versions and those seem to work out.

Maybe you could first try running the same thing with node 16 instead of 18.

Then I wonder if it's actually worth nuking node_modules and reinstalling it all clean - maybe something got really confused in there, it happens.
