### ISSUE TITLE
🐛 Bug Report: Type coercion of environment-based config is inconsistent

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#16842]
### 📜 Description

Broadly, there are two mechanisms for supplying app configuration via environment variables: **1)** using specially named `APP_CONFIG_*` variables to set specific values, or **2)** using environment variable substitution in `app-config.yaml` files like this:

```yaml
backend:
  database:
    ensureExists: ${DB_ENSURE_EXISTS}

# or
backend:
  database:
    ensureExists:
      $env: DB_ENSURE_EXISTS
```

It appears as though the way that type coercion of strings (all environment variables are strings) to boolean values works in these cases differs.

The net-effect is that we're unable to take advantage of the updates in https://github.com/backstage/backstage/pull/15423, which made it so that `getBoolean()` and `getOptionalBoolean()` config reads would coerce appropriate string values at runtime.  ...The problem is that we never get to runtime because the app never starts (due to configuration not matching schema).

### 👍 Expected behavior

Regardless of how I supply a boolean configuration via environment variables, it should validate and allow the app to boot up if it matches a sane coercion value.

### 👎 Actual Behavior with Screenshots

I'm only able to supply boolean config values via environment variables using the `APP_CONFIG_*` prefixed variables.

### 👟 Reproduction steps

1. In this monorepo, update `app-config.yaml` with the following change:
   ```diff
   backend:
     database:
       client: better-sqlite3
       connection: ':memory:'
   +   ensureExists:
   +     $env: DB_ENSURE_EXISTS
   ```
2. Run the following command:
   ```terminal
   DB_ENSURE_EXISTS=false yarn backstage-cli config:check
   ```
3. Then run the following command:
   ```terminal
   APP_CONFIG_backend_database_ensureExists=false yarn backstage-cli config:check
   ```

My expectation is that I never see an error like

```
Config must be boolean { type=boolean } at /backend/database/ensureExists
```

...However as things are today, I get that error running the command in step 2.

### 🖥️ Your Environment

```
OS:   Darwin 22.3.0 - darwin/x64
node: v18.12.1
yarn: 3.2.3
cli:  0.22.4-next.1 (local)
backstage:  N/A
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Hmm, I wonder if we can make the config check do this coercion instead? Otherwise I think we'd need to bring the schema into the load transform. For example:  `APP_CONFIG_scaffolder_workerCount=1`. We also can't really make the other `get*` methods coerce back from bool, it'd cause strings to switch value.
