### ISSUE TITLE
🐛 Bug Report: I can implement a backstage backend plugin that causes the whole backend to crash 

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#16841]
### 📜 Description

It is possible to create an express-promise router that does not handle promises failures correctly and results in the whole backend going down when calling the failing api.

### 👍 Expected behavior

If a plugin does not handle a failing promise correctly, it returns the correct data, however its crashing.

### 👎 Actual Behavior with Screenshots

The whole Application crashes.

### 👟 Reproduction steps

Implement the following api:

```
  router.get('/exercise-failure', async (_, response) => {
    logger.info('PONG!');
    new Promise((res) => {
      res(({} as any).nope.noWay)
    })
    response.json({ status: 'ok' });
  });
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by punkle** [comment]
Would using a sandbox per backend plugin work to solve this issue? I wonder is there an express plugin that provides a sandbox.

**Comment by Rugvip** [comment]
We considered process separation back in #8712, but decided against it. It could be reconsidered though. VM sandboxes aren't really an option afaik, they don't really isolate more than variable scope

**Comment by freben** [comment]
Does this happen both in prod and when running locally? The CLI [has an `unhandledRejection` handler](https://github.com/backstage/backstage/blob/2584660394107ede9ef548f3a2896b2f73340228/packages/cli/src/index.ts#L45) that forcibly closes the process.

**Comment by punkle** [comment]
It does for Roadie. However I am unsure if there is a prod mode we should have enabled or something that would cause the exception not to be ignored.

**Comment by punkle** [comment]
I think its an uncaughtException rather than an unhandledRejection that we are seeing here.

**Comment by freben** [comment]
Would you have the opportunity to experiment with adding handlers for those? Maybe we should have that as a builtin behaviour always, that we capture and log (and then continue without exploding) for all unhandled exceptions.

**Comment by punkle** [comment]
I can. :)

**Comment by Rugvip** [comment]
Ended up throwing #16960 together for this
