### ISSUE TITLE
🚀 Feature: plugin-catalog-backend-module-gitlab support custom

### ISSUE THREAD

**Issue by michaelvogtmobi** [backstage/backstage#16859]
### 🔖 Feature description

We use the Gitlab catalog discovery plugin, this works as defined. In our use case we want to use a specific `type` and `catalogFile`. The custom type is working fine if we import manually. The issue is that the Gitlab discovery import only supports the default `url` type. 

### 🎤 Context

- Support custom yaml file implementations for the gitlab discovery
- Not sure if other discovery plugins have similar needs

### ✌️ Possible Implementation

source file `src/providers/GitlabDiscoveryEntityProvider.ts``

```
  private createLocationSpec(project: GitLabProject): LocationSpec {
    const project_branch = project.default_branch ?? this.config.fallbackBranch;
    return {
      type: this.config.catalogType ?? 'url',
      target: `${project.web_url}/-/blob/${project_branch}/${this.config.catalogFile}`,
      presence: 'optional',
    };
  }
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Could also make it a callback that you pass to the provider.

```ts
GitlabDiscoveryEntityProvider.fromConfig(config, {
  logger, schedule,
  createLocation: (providerConfig, project) => {
    return { type: 'custom', target: '....' };
  }
})
```

**Comment by michaelvogtmobi** [comment]
Thanks @freben - this might be an option as well - can you give me an example how this would be passed in?
