### ISSUE TITLE
🐛 Bug Report: [Search] UI not responsive for mobile/xs-sized screens

### ISSUE THREAD

**Issue by tudi2d** [backstage/backstage#16867]
### 📜 Description

When searching on mobile devices the UI looks broken. The problem are the filters as there are text overflows & they won't wrap. `sm` screens tend to have issues as well

### 👍 Expected behavior

- The filter section would either wrap to to a full width (`xs={12}`) on mobile devices or disappear/ get's hidden in an accordion
- On `sm` screen it might be helpfull to look at the `span` elements conatining the lifecycle and add `ellipsis` on them smth. like the following

<img width="167" alt="Screenshot 2023-03-15 at 11 58 53" src="https://user-images.githubusercontent.com/8904624/225289588-661d6ded-ed6d-4461-a993-694bc6e0860f.png">

### 👎 Actual Behavior with Screenshots

|`sm`|`xs`|
|:---:|:---:|
|<img width="703" alt="Screenshot 2023-03-15 at 11 49 47" src="https://user-images.githubusercontent.com/8904624/225287612-e2863364-4204-4ca5-9dd2-003e563120be.png">|<img width="402" alt="Screenshot 2023-03-15 at 11 44 09" src="https://user-images.githubusercontent.com/8904624/225287597-01950682-5fec-413a-8365-c8407d85d06c.png">|

### 👟 Reproduction steps

1. You can test the behaviour here: https://demo.backstage.io/search
2. Tryout different width's in your Responsiveness settings of your favourite Browsers Developer Tool 
3. If not modified by the instance the default breakpoints are: 960px >= `sm` >= 600px > xs >= 0 (https://v4.mui.com/customization/breakpoints/#default-breakpoints) 

### 📃 Provide the context for the Bug.

Creating this issue related to the thread here on Discord: https://discord.com/channels/687207715902193673/696709358544879716/1085236389995622410 

### 🖥️ Your Environment

my environment is great - thanks for asking!

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Thanks for reporting and caring about smaller screen sizes!

**Comment by papercircuit** [comment]
Hi @tudi2d  @Yasir761 I would like to tackle this issue.

**Comment by Yasir761** [comment]
Hey! @tudi2d currently I'm working on this, if I need any help I'll reach you out.

**Comment by emmaindal** [comment]
Thanks @Yasir761 I've assigned this issue to you!

**Comment by Yasir761** [comment]
I was going through above mention issues but didn't find any responsive errors when I ran repo locally.

**Comment by tudi2d** [comment]
how does the `/search` page look for the mentioned width [breakpoints](https://v4.mui.com/customization/breakpoints/#default-breakpoints)? do you see any overflowing text?

**Comment by tudi2d** [comment]
How is it going @Yasir761? Happy to pass it on/ reopen it for contributors if you don't feel like working on it at the moment! :)

**Comment by Yasir761** [comment]
@tudi2d "Hello! I'm doing great,  I'm not currently working on an issue, but I'm happy to assist you with any questions or tasks you have.

**Comment by tudi2d** [comment]
alright - I take that as a reopen. @papercircuit still up for giving this a try? :)

**Comment by papercircuit** [comment]
@tudi2d I see the issue in the demo, however the UI seems to have been updated and differs from the demo. Perhaps someone more knowledgeable can help explain. 

When I run a local dev build I see this: 

<img width="160" alt="Screenshot 2023-04-07 at 1 56 31 PM" src="https://user-images.githubusercontent.com/105308787/230655192-bb42a79c-26e7-4740-bad3-9fa69c99830b.png">

Here software-catalog is wrapping but lifecycle spans are still overflowing.


@freben I see the relevant filter elements in the SearchPage component located at: 

backstage/packages/create-app/templates/default-app/packages/app/src/components/search/SearchPage.tsx.

Can you suggest where to find the SearchPage component outside of the create-app directory?
