### ISSUE TITLE
🐛 Bug Report: Playlist plugin add user issue

### ISSUE THREAD

**Issue by antoniobergas** [backstage/backstage#16871]
### 📜 Description

You try to add a User entity from the plus icon to add entities to a playlist. It throws an error in the console and you cannot add the user.

Could be related to some missing info in the entity?

Note: If you go directly to the entity page you can added without problem.

### 👍 Expected behavior

I can add any kind of component to any playlist without issues

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/26031467/225310291-4b67b7bd-7416-43d5-a734-957a2d7e5e54.png)

### 👟 Reproduction steps

- Create a new public playlist
- In the playlist list page click on add entities plus button
- Try to add a user into the playlist
- An error shown in the console

### 📃 Provide the context for the Bug.

Cannot create grouping of users

### 🖥️ Your Environment

Dependencies:
  @backstage/app-defaults                          1.2.0
  @backstage/backend-app-api                       0.4.0
  @backstage/backend-common                        0.18.2
  @backstage/backend-dev-utils                     0.1.0
  @backstage/backend-plugin-api                    0.4.0
  @backstage/backend-tasks                         0.4.3
  @backstage/catalog-client                        1.3.1
  @backstage/catalog-model                         1.2.0
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.3
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.5.0
  @backstage/core-components                       0.12.4, 0.9.5
  @backstage/core-plugin-api                       1.4.0
  @backstage/errors                                1.1.4
  @backstage/eslint-plugin                         0.1.1
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.10
  @backstage/integration                           1.4.2
  @backstage/plugin-analytics-module-ga            0.1.26
  @backstage/plugin-api-docs                       0.9.0
  @backstage/plugin-app-backend                    0.3.42
  @backstage/plugin-auth-backend                   0.18.0
  @backstage/plugin-auth-node                      0.2.11
  @backstage/plugin-azure-devops-backend           0.3.21
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.2.6
  @backstage/plugin-catalog-backend-module-azure   0.1.13
  @backstage/plugin-catalog-backend                1.7.2
  @backstage/plugin-catalog-common                 1.0.11
  @backstage/plugin-catalog-graph                  0.2.27
  @backstage/plugin-catalog-import                 0.9.5
  @backstage/plugin-catalog-node                   1.3.3
  @backstage/plugin-catalog-react                  1.3.0
  @backstage/plugin-catalog                        1.8.0
  @backstage/plugin-github-actions                 0.5.15
  @backstage/plugin-home                           0.4.31
  @backstage/plugin-org                            0.6.5
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.5
  @backstage/plugin-permission-react               0.4.10
  @backstage/plugin-playlist-backend               0.2.5
  @backstage/plugin-playlist-common                0.1.4
  @backstage/plugin-playlist                       0.1.6
  @backstage/plugin-proxy-backend                  0.2.36
  @backstage/plugin-scaffolder-backend             1.11.0
  @backstage/plugin-scaffolder-common              1.2.5
  @backstage/plugin-scaffolder-node                0.1.0
  @backstage/plugin-scaffolder-react               1.1.0
  @backstage/plugin-scaffolder                     1.11.0
  @backstage/plugin-search-backend-module-pg       0.5.3
  @backstage/plugin-search-backend-node            1.1.3
  @backstage/plugin-search-backend                 1.2.3
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.5.0
  @backstage/plugin-search                         1.1.0
  @backstage/plugin-shortcuts                      0.3.7
  @backstage/plugin-sonarqube-backend              0.1.7
  @backstage/plugin-sonarqube-react                0.1.3
  @backstage/plugin-sonarqube                      0.6.4
  @backstage/plugin-tech-radar                     0.6.1
  @backstage/plugin-techdocs-backend               1.5.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.10
  @backstage/plugin-techdocs-node                  1.5.0
  @backstage/plugin-techdocs-react                 1.1.3
  @backstage/plugin-techdocs                       1.5.0
  @backstage/plugin-user-settings                  0.7.0
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.5
  @backstage/theme                                 0.2.17
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by kuangp** [comment]
Hi @antoniobergas can you try updating to the latest release and confirming whether you still have this issue?

**Comment by kuangp** [comment]
hm this might be related to how you have your search collators set up, the results in that UI pulls from your search backend results - can you share how you have your search backend configured, specifically the catalog collator? are you indexing your User entities at all?

**Comment by antoniobergas** [comment]
Not at all, didn't touched the search backend configuration neither indexed the User entities.

Can you please point me where's the docs for configure It ? Thanks a lot

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kuangp** [comment]
Here are docs on configuring the search backend: https://backstage.io/docs/features/search/getting-started#adding-search-to-the-backend

I would also check if `User`s are currently be explicitly filtered out: https://backstage.io/docs/features/search/how-to-guides#how-to-limit-what-can-be-searched-in-the-software-catalog

**Comment by antoniobergas** [comment]
Hi @kuangp , sorry for the delay 😅

Now it's working correctly , thanks a lot for the help! I close this issue 😊
