### ISSUE TITLE
🐛 Bug Report: Modifying Entity Schema Defined In BuiltinKindsEntityProcessor

### ISSUE THREAD

**Issue by jbolda** [backstage/backstage#16886]
### 📜 Description

We are looking to adjust the `Domain` entity kind and adjust the owner field to be optional. The docs note this use case, but the `builder.replaceProcessors()` does not allow replacing or modifying the `BuiltinKindsEntityProcessor`.

### 👍 Expected behavior

It should allow for replacement or adjustment of the `kind`s processed by `BuiltinKindsEntityProcessor`.

### 👎 Actual Behavior with Screenshots

The `BuiltinKindsEntityProcessor` validation throws an error as the Entity does not match the default schema, and the Entity will not continue to any custom Entity processors further in the list.

```
Processor BuiltinKindsEntityProcessor threw an error while validating the entity domain:default/finance; caused by TypeError: /spec must have required property 'owner' - missingProperty: owner type=plugin entity=domain:default/finance. location=file:/~/backstage/fixtures/domain-finance.yaml
```

### 👟 Reproduction steps

A `Domain` without an owner such as the following will fail the default schema validation check as expected.

```yaml
apiVersion: backstage.io/v1beta1
kind: Domain
metadata:
  name: finance
spec: {}
```

Adding in a custom Domain Entity processor such as the following where `domainEntityV1alpha1Validator` sets the spec schema `"required": []`.

```js
import { Entity, entityKindSchemaValidator } from '@backstage/catalog-model';
import { CatalogProcessor } from '@backstage/plugin-catalog-node';
import { Logger } from 'winston';
import domainSchema from './domainEntityV1alpha1Validator';

export class DomainCustomEntityProcessor implements CatalogProcessor {
  getProcessorName(): string {
    return 'DomainCustomEntityProcessor';
  }

  async validateEntityKind(entity: Entity): Promise<boolean> {
    const validate = entityKindSchemaValidator(domainSchema);
    return validate(entity) === entity;
  }
}

```

Using this in the backend plugin catalog `createPlugin`, the `replaceProcessor()` does not affect the built-in Entities.
```js
  const defaultProcessors = builder.getDefaultProcessors();
  builder.replaceProcessors([
    new DomainCustomEntityProcessor({ logger }),
    ...defaultProcessors
  ]);
```

### 📃 Provide the context for the Bug.

There seems to be prior art that was moving towards enabling this such as #7834. The [docs imply that, while high risk, the capability should exist](https://github.com/backstage/backstage/blob/master/docs/features/software-catalog/extending-the-model.md?plain=1#L171). In `v1.9.0`, the validation step was [adjusted to continue through all registered processors](https://github.com/backstage/backstage/blob/master/docs/releases/v1.9.0-changelog.md?plain=1#L314).

The adjustment wasn't enough to enable this use case though as the `BuiltInKindsEntityProcessor` throws an error due to the failed validation and further processors are not run. [The `replaceProcessors()` only affects some of the processors, and `PlaceholderProcessor` and `BuiltinKindsEntityProcessor` are hardcoded first in the processor list.](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/CatalogBuilder.ts#L602-L618)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Yeah, indeed that's an omission right now; you can't replace that particular processor in its entirety.

What I could envision adding, while not super beautiful, is an `if` statement in the catalog builder [here](https://github.com/backstage/backstage/blob/c0fd622a96c6ff79526c1eeaa1c515a74eceb424/plugins/catalog-backend/src/service/CatalogBuilder.ts#L609), which _skips_ adding that processor, if the user has supplied a processor that returns [the exact same name](https://github.com/backstage/backstage/blob/c0fd622a96c6ff79526c1eeaa1c515a74eceb424/plugins/catalog-backend/src/modules/core/BuiltinKindsEntityProcessor.ts#L72). Would you like to make such a pull request? 🙏 

Ping @backstage/catalog-core here too.

**Comment by jbolda** [comment]
Aye, happy to tackle it. Thanks for the 👀 @freben.

**Comment by TBragi** [comment]
I am also running into this challenge at the moment.
We have made our own implementation of `System` entity, where it uses the following structure:
```yaml
apiVersion: our.very.own/apiVersion
kind: System
metadata:
  name: TEST
```
For some reason this ends up triggering on the `BuiltinKindsEntityProcessor` even though we have made our own `system-kind.ts`, `system-processor.ts`, `System.v1alpha1.schema.json` which all uses our own `apiVersion: our.very.own/apiVersion`, but it still throws following warning:
```
catalog warn Processor BuiltinKindsEntityProcessor threw an error while postprocessing;
  caused by TypeError:
    Cannot read properties of undefined (reading 'owner')
    type=plugin
    entity=system:default/test
    location=file:/app/backstage-app/catalog-info.yaml
```
But if I change our custom processor to use and validate for `kind: customKind` (still same `apiVersion` as mentioned above) or something else unique it works fine!
It also works fine if we introduce an empty `spec`
```yaml
apiVersion: our.very.own/apiVersion
kind: System
metadata:
  name: TEST
spec: {}
```

I thought the validators used the `apiVersion` defined in the `entity.schema.json` files to validate the Entities?
```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "SystemV1alpha1",
  "description": "This is our unique System, using our own apiVersion",
  "examples": [
    {
      "apiVersion": "our.very.own/apiVersion",
      "kind": "System",
      "metadata": {
        "name": "TEST",
        "description": "very nice description"
      }
    }
  ],
  "allOf": [
    {
      "$ref": "Entity"
    },
    {
      "type": "object",
      "properties": {
        "apiVersion": {
          "enum": ["our.very.own/apiVersion"]
        },
        "kind": {
          "enum": ["System"]
        }
      }
    }
  ]
}

```

**Comment by TBragi** [comment]
It seems like the validators doesn't check correctly for `apiVersion` as in our case it still reacts on the `builtinKindsEntityProcessor` [system part](https://github.com/backstage/backstage/blob/9e82f9ec2fd57eeb9854682ca811e77b5fc94251/plugins/catalog-backend/src/modules/core/BuiltinKindsEntityProcessor.ts#L273) even though our `apiVersion` is something entirely else than `"backstage.io/v1alpha1", "backstage.io/v1beta1"`.
Or we have set it up wrong 😢

**Comment by freben** [comment]
Oh and to be clear - I didn't intend for `BuiltinKindsEntityProcessor` itself to be configurable - or did you mean that you'd e.g. make it deal with all kinds except one which is custom, for example?

**Comment by freben** [comment]
Probably best to leave as is for now. As you've seen we do have exports for `apiEntityV1alpha1Validator` etc which helps in making the processor a lot smaller, but there's no similar thing for the relations.

I think this might make sense to defer until we have a great pattern for the catalog backend in terms of the new backend system. Maybe we'll end up packaging up the kinds as individual modules for the catalog so you can install them at will, one at a time or all of them at the same time. There should probably be a `@backstage/plugin-catalog-backend-module-system-model` or something like that, which contains all of the default system model parts nicely packaged up. Then we can start thinking about steering _away_ from the catalog builder entirely, and new ways of composing these changes.

**Comment by freben** [comment]
One more thing. There's nothing stopping you from using delegation as a pattern, right?

Completely untested but maybe conveys the idea:

```ts
class CustomKinds implements CatalogProcessor {
  readonly delegate = new BuiltinKindsEntityProcessor();
  
  getProcessorName(): string {
    return this.delegate.getProcessorName();
  }

  async validateEntityKind(entity: Entity): Promise<boolean> {
    if (entity.kind === 'System') {
      // custom code
    } else {
      return this.delegate.validateEntityKind(entity);
    }
  }

  // and the same for postProcessEntity
```

**Comment by taras** [comment]
Yeah, that's a good idea.

**Comment by jbolda** [comment]
Aye, agreed, that is the cleanest option given our current constraints.
