### ISSUE TITLE
🐛 Bug Report: Authentication with Oaut2-proxy development environment

### ISSUE THREAD

**Issue by borosilva** [backstage/backstage#16885]
### 📜 Description

Enable backstage authentication with oauth2-proxy.

### 👍 Expected behavior

Configure user authentication with keycloak and oauth2-proxy.

### 👎 Actual Behavior with Screenshots

**Error**

Request URL: http://localhost:7007/api/auth/oauth2Proxy/refresh
Request Method: GET
Status Code: 401 Unauthorized

### 👟 Reproduction steps

**1.- Keycloak**

- Start local keycloak in docker with: 
`docker run -p 9990:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin jboss/keycloak
`
- Add new Backstage realm and create user.

**2.- Oauth2-Proxy.**

- Downloaded the precompiled binary from this link: https://github.com/oauth2-proxy/oauth2-proxy/releases (version 7.4.0).

- Create file with name `oauth2_proxy.cfg` and the following contents:

```
http_address = "127.0.0.1:4180"

provider = "keycloak"
login_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/auth"
redeem_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/token"
profile_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/userinfo"
validate_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/userinfo"
oidc_issuer_url = "http://localhost:9990/auth/realms/backstage"

client_id = "oauth2-proxy"
client_secret = "B6U0bbjTB0SdqzaUJVCpNh3y2wMFkgYI"

redirect_url = "http://localhost:4180/oauth2/callback"

upstreams = [
    "http://127.0.0.1:3000/"
]

request_logging = true

pass_basic_auth = true
pass_user_headers = true
pass_host_header = true 

email_domains = [
    "*"
]

pass_access_token = true
ssl_insecure_skip_verify = false
cookie_secret = "lLYcG3L1khAS9Yz8hXb7mia1wSDk_eCDQFzl_Yx2rA4="
cookie_secure = false
set_authorization_header = "true"
pass_authorization_header = "true"
reverse_proxy = "true"
scope = "email"
whitelist_domains = "*"
skip_provider_button = "true"
set_xauthrequest = "true"
```
- run command:
```
./oauth2-proxy \
    --config=./oauth2_proxy.cfg
```

**3.- Backstage** 
- I started a new project with the command: `npx @backstage/create-app`
- the following files have been modified:

app-config.yaml:

```
<SNIP>
...
auth:
  providers:
    oauth2Proxy: {}
```

App.tsx:

```
<SNIP>
...

const app = createApp({
  ...
  components: {
    SignInPage: props => (
      <ProxiedSignInPage {...props} provider="oauth2Proxy" />
    ),
  },
});

<SNIP>
```

auth.ts
```
<SNIP>
...

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      ...defaultAuthProviderFactories,

      oauth2Proxy: providers.oauth2Proxy.create({
        signIn: {
          async resolver(info, ctx) {
            const name = result.getHeader('x-forwarded-user');
            if (!name) {
              throw new Error('Request did not contain a user')
            }

            // Create stub user
            const userEntityRef = stringifyEntityRef({
              kind: 'User',
              name: name,
              namespace: DEFAULT_NAMESPACE,
            });

            return ctx.issueToken({
              claims: {
                sub: userEntityRef,
                ent: [userEntityRef],
              },
            });

          },
        },
      }),

...
<SNIP>
```
- run command:

```
yarn dev
```

**4.- Test** 
- Enter http:localhost4180
- Login with user and password previously configured in keycloak.

### 🖥️ Your Environment

OS:   Darwin 22.3.0 - darwin/x64
node: v16.14.2
yarn: 1.22.19
cli:  0.22.3 (installed)
backstage:  1.11.0

Dependencies:
  @backstage/app-defaults                          1.2.0
  @backstage/backend-app-api                       0.4.0
  @backstage/backend-common                        0.18.2
  @backstage/backend-dev-utils                     0.1.0
  @backstage/backend-plugin-api                    0.4.0
  @backstage/backend-tasks                         0.4.3
  @backstage/catalog-client                        1.3.1
  @backstage/catalog-model                         1.2.0
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.3
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.5.0
  @backstage/core-components                       0.12.4
  @backstage/core-plugin-api                       1.4.0
  @backstage/dev-utils                             1.0.12
  @backstage/errors                                1.1.4
  @backstage/eslint-plugin                         0.1.1
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.10
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.9.0
  @backstage/plugin-app-backend                    0.3.42
  @backstage/plugin-auth-backend                   0.18.0
  @backstage/plugin-auth-node                      0.2.11
  @backstage/plugin-catalog-backend                1.7.2
  @backstage/plugin-catalog-common                 1.0.11
  @backstage/plugin-catalog-graph                  0.2.27
  @backstage/plugin-catalog-import                 0.9.5
  @backstage/plugin-catalog-node                   1.3.3
  @backstage/plugin-catalog-react                  1.3.0
  @backstage/plugin-catalog                        1.8.0
  @backstage/plugin-github-actions                 0.5.15
  @backstage/plugin-org                            0.6.5
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.5
  @backstage/plugin-permission-react               0.4.10
  @backstage/plugin-proxy-backend                  0.2.36
  @backstage/plugin-scaffolder-backend             1.11.0
  @backstage/plugin-scaffolder-common              1.2.5
  @backstage/plugin-scaffolder-node                0.1.0
  @backstage/plugin-scaffolder-react               1.1.0
  @backstage/plugin-scaffolder                     1.11.0
  @backstage/plugin-search-backend-module-pg       0.5.3
  @backstage/plugin-search-backend-node            1.1.3
  @backstage/plugin-search-backend                 1.2.3
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.5.0
  @backstage/plugin-search                         1.1.0
  @backstage/plugin-tech-radar                     0.6.1
  @backstage/plugin-techdocs-backend               1.5.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.10
  @backstage/plugin-techdocs-node                  1.5.0
  @backstage/plugin-techdocs-react                 1.1.3
  @backstage/plugin-techdocs                       1.5.0
  @backstage/plugin-user-settings                  0.7.0
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.5
  @backstage/theme                                 0.2.17
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
This provider is contributed by the community and I don't have any familiarity with it myself, so can't really check for signs of wrong config or similar.

Did you enable debug logging? Any interesting output from either the auth backend or from keycloak? Did you check if the sign-in resolver code (the `async resolver(info, ctx)`) in your backend is even reached? Did you do any tracing to see what the network traffic sent is?

**Comment by Rugvip** [comment]
@borosilva it looks like you've got `oauth2-proxy` set up in parallel with the Backstage deployment, but it needs to sit in front of it for all requests. The traffic should always take the following path: `browser -> oauth2-proxy -> backstage (frontend + backend)`.

**Comment by nabuskey** [comment]
I was running into the same issue in my local environment where headers were not passed to backend and found this issue. I was able to get it working with Keycloak + oAuth2-proxy + Backstage. I wanted to share what I did in case others run into the same issue. 
I found the notes found in the [yaml file ](https://github.com/backstage/backstage/blob/master/plugins/auth-backend/examples/docker-compose.oauth2-proxy.yaml)to be very useful. 

1. CORS origin must be updated. Otherwise, request will be blocked by your browser (at least in Firefox). 
```yaml
cors:
  origin: http://localhost:4180
```
2. Backend base URL must also be updated to make sure necessary headers are included in requests.
```yaml
backend:
  baseUrl: http://localhost:4180
```
3. Make sure upstreams in oAuth2-proxy is setup correctly
```
OAUTH2_PROXY_UPSTREAMS=http://localhost:3000,http://localhost:7007/api/
```

**Comment by borosilva** [comment]
> I was running into the same issue in my local environment where headers were not passed to backend and found this issue. I was able to get it working with Keycloak + oAuth2-proxy + Backstage. I wanted to share what I did in case others run into the same issue. I found the notes found in the [yaml file ](https://github.com/backstage/backstage/blob/master/plugins/auth-backend/examples/docker-compose.oauth2-proxy.yaml)to be very useful.
> 
> 1. CORS origin must be updated. Otherwise, request will be blocked by your browser (at least in Firefox).
> 
> ```yaml
> cors:
>   origin: http://localhost:4180
> ```
> 
> 2. Backend base URL must also be updated to make sure necessary headers are included in requests.
> 
> ```yaml
> backend:
>   baseUrl: http://localhost:4180
> ```
> 
> 3. Make sure upstreams in oAuth2-proxy is setup correctly
> 
> ```
> OAUTH2_PROXY_UPSTREAMS=http://localhost:3000,http://localhost:7007/api/
> ```

thank you very much @nabuskey for sharing this configuration. I was able to test it and it works!

**Comment by regicsolutions** [comment]
@borosilva i am seeing similar errors when trying to enable the OAuth2 Proxy using Okta using the following [config](https://developer.okta.com/blog/2022/07/14/add-auth-to-any-app-with-oauth2-proxy) any idea what i am missing?

When accessing http://localhost:4180
![Screenshot 2023-06-06 at 6 10 10 PM](https://github.com/backstage/backstage/assets/6157895/9ad93bf6-0934-4915-bda9-8d9a82f73644)

When accessing http://localhost:7007 and http://localhost:3000
![Screenshot 2023-06-06 at 6 11 34 PM](https://github.com/backstage/backstage/assets/6157895/dea8efcb-12f5-4053-9c44-8fd086cab53d)

![Screenshot 2023-06-06 at 6 06 10 PM](https://github.com/backstage/backstage/assets/6157895/1aa3f026-e7e3-4c48-909c-f5f81ee564bf)

**Comment by weicnao** [comment]
@regicsolutions  I encountered the same issue. Has the problem been resolved?

**Comment by borosilva** [comment]
> @borosilva i am seeing similar errors when trying to enable the OAuth2 Proxy using Okta with the following [config](https://developer.okta.com/blog/2022/07/14/add-auth-to-any-app-with-oauth2-proxy) any idea what i am missing?
> 
> When accessing http://localhost:4180 ![Screenshot 2023-06-06 at 6 10 10 PM](https://user-images.githubusercontent.com/6157895/243844602-9ad93bf6-0934-4915-bda9-8d9a82f73644.png)
> 
> When accessing http://localhost:7007 and http://localhost:3000 ![Screenshot 2023-06-06 at 6 11 34 PM](https://user-images.githubusercontent.com/6157895/243845426-dea8efcb-12f5-4053-9c44-8fd086cab53d.png)
> 
> ![Screenshot 2023-06-06 at 6 06 10 PM](https://user-images.githubusercontent.com/6157895/243844005-1aa3f026-e7e3-4c48-909c-f5f81ee564bf.png)

@regicsolutions 
can you share your backstage setup, to get a better idea, please?

**Comment by brunobastosg** [comment]
@borosilva Hi, can you share your Keycloak realm configuration?

**Comment by borosilva** [comment]
> @borosilva Hi, can you share your Keycloak realm configuration?

Hi @brunobastosg .

I have followed these steps to set up keycloak:
https://janus-idp.io/blog/2023/01/17/enabling-keycloak-authentication-in-backstage#configuring-keycloak

**Comment by brunobastosg** [comment]
> > @borosilva Hi, can you share your Keycloak realm configuration?
> 
> Hi @brunobastosg .
> 
> I have followed these steps to set up keycloak: https://janus-idp.io/blog/2023/01/17/enabling-keycloak-authentication-in-backstage#configuring-keycloak

Thanks for the reply. I also followed these steps, but I'm getting an error after entering the user credentials.

I'm gonna redo the Keycloak config just in case.

**Comment by brunobastosg** [comment]
Figured it out. I had to add `openid` to the scope in oauth2-proxy.cfg.

This warning from Keycloak pointed me in the right direction:

```
WARN [org.keycloak.services] (default task-13) KC-SERVICES0091: Request is missing scope 'openid' so it's not treated as OIDC, but just pure OAuth2 request.
```

**Comment by orlando2116** [comment]
@borosilva @regicsolutions @nabuskey  i have a similar issue
this request **_http://localhost:7007/api/auth/oauth2Proxy/refresh_** return the following error:
```
`{
    "error": {
        "name": "Error",
        "message": "Request did not contain a user",
        "stack": "Error: Request did not contain a user\n    at resolver (/Users/oegonzalezz/Documents/backstage/packages/backend/src/plugins/auth.ts:61:21)\n    at Object.refresh (/Users/oegonzalezz/Documents/backstage/node_modules/@backstage/plugin-auth-node/src/proxy/createProxyRouteHandlers.ts:66:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    },
    "request": {
        "method": "GET",
        "url": "/api/auth/oauth2Proxy/refresh"
    },
    "response": {
        "statusCode": 500
    }
}`
```
- this is my oauth2_proxy.cfg:

```
http_address = "127.0.0.1:4180"

provider = "keycloak"
login_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/auth"
redeem_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/token"
profile_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/userinfo"
validate_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/userinfo"
oidc_issuer_url = "http://localhost:9990/auth/realms/backstage"

client_id = "oauth2-proxy"
client_secret = "B6U0bbjTB0SdqzaUJVCpNh3y2wMFkgYI"

redirect_url = "http://localhost:4180/oauth2/callback"

upstreams = [
    "http://127.0.0.1:3000/",
    "http://localhost:7007/api"
]

request_logging = true

pass_basic_auth = true
pass_user_headers = true
pass_host_header = true 

email_domains = [
    "*"
]

pass_access_token = true
ssl_insecure_skip_verify = false
cookie_secret = "lLYcG3L1khAS9Yz8hXb7mia1wSDk_eCDQFzl_Yx2rA4="
cookie_secure = false
set_authorization_header = "true"
pass_authorization_header = "true"
reverse_proxy = "true"
scope = "email"
whitelist_domains = "*"
skip_provider_button = "true"
set_xauthrequest = "true"
``` 


- this is my auth.ts:
``` 
import {
  createRouter,
  providers,
  defaultAuthProviderFactories,
} from '@backstage/plugin-auth-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';
import { DEFAULT_NAMESPACE, stringifyEntityRef } from '@backstage/catalog-model';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      ...defaultAuthProviderFactories,

      oauth2Proxy: providers.oauth2Proxy.create({
        signIn: {
          async resolver({ result }, ctx) {
            console.log("--------------------RESULT AUTH--------------")
            console.log(result)
            console.log("--------------------END RESULT AUTH--------------")
            const name = result.getHeader('x-forwarded-preferred-username');
            if (!name) {
              throw new Error('Request did not contain a user');
            }

           // Create stub user
           const userEntityRef = stringifyEntityRef({
            kind: 'User',
            name: name,
            namespace: DEFAULT_NAMESPACE,
          });

          return ctx.issueToken({
            claims: {
              sub: userEntityRef,
              ent: [userEntityRef],
            },
          });
          },
        },
      }),
      
    },
  });
}
``` 

- this is backstage front

![image](https://github.com/backstage/backstage/assets/20132141/bbdef94c-ab9f-4e9d-9c5c-eaf3d3512e80)

- when i accessing to [http://localhost:4180](http://localhost:4180), this error show me:

![image](https://github.com/backstage/backstage/assets/20132141/a65e65e1-29d3-4f7c-a2dc-225f9c848440)



- In keycloack, i create 1 realm called backstage with this client config:
![image](https://github.com/backstage/backstage/assets/20132141/1da8f313-3107-4574-be02-a54d13679cc5)


Any idea what i'm missing?
Please, can you help me?

**Comment by borosilva** [comment]
> @borosilva @regicsolutions @nabuskey i have a similar issue
> 
> this request **_http://localhost:7007/api/auth/oauth2Proxy/refresh_** return the following error:
> 
> ```
> `{
>     "error": {
>         "name": "Error",
>         "message": "Request did not contain a user",
>         "stack": "Error: Request did not contain a user\n    at resolver (/Users/oegonzalezz/Documents/backstage/packages/backend/src/plugins/auth.ts:61:21)\n    at Object.refresh (/Users/oegonzalezz/Documents/backstage/node_modules/@backstage/plugin-auth-node/src/proxy/createProxyRouteHandlers.ts:66:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
>     },
>     "request": {
>         "method": "GET",
>         "url": "/api/auth/oauth2Proxy/refresh"
>     },
>     "response": {
>         "statusCode": 500
>     }
> }`
> ```
> 
> * this is my oauth2_proxy.cfg:
> 
> ```
> http_address = "127.0.0.1:4180"
> 
> provider = "keycloak"
> login_url = "http://localhost:8080/auth/realms/backstage/protocol/openid-connect/auth"
> redeem_url = "http://localhost:8080/auth/realms/backstage/protocol/openid-connect/token"
> profile_url = "http://localhost:8080/auth/realms/backstage/protocol/openid-connect/userinfo"
> validate_url = "http://localhost:8080/auth/realms/backstage/protocol/openid-connect/userinfo"
> oidc_issuer_url = "http://localhost:8080/auth/realms/backstage"
> 
> client_id = "backstage"
> client_secret = "XeC6jBFPbC1bg3CNa7Ifn1cj0tCnoSbP"
> 
> redirect_url = "http://localhost:4180/oauth2/callback"
> 
> upstreams = [
>     "http://127.0.0.1:3000/",
>     "http://localhost:7007/api"
> ]
> 
> request_logging = true
> 
> pass_basic_auth = true
> pass_user_headers = true
> pass_host_header = true 
> 
> email_domains = [
>     "*"
> ]
> 
> pass_access_token = true
> ssl_insecure_skip_verify = false
> cookie_secret = "lLYcG3L1khAS9Yz8hXb7mia1wSDk_eCDQFzl_Yx2rA4="
> cookie_secure = false
> set_authorization_header = "true"
> pass_authorization_header = "true"
> reverse_proxy = "true"
> scope = "email"
> whitelist_domains = "*"
> skip_provider_button = "true"
> set_xauthrequest = "true"
> ```
> 
> * this is my auth.ts:
> 
> ```
> import {
>   createRouter,
>   providers,
>   defaultAuthProviderFactories,
> } from '@backstage/plugin-auth-backend';
> import { Router } from 'express';
> import { PluginEnvironment } from '../types';
> import { DEFAULT_NAMESPACE, stringifyEntityRef } from '@backstage/catalog-model';
> 
> export default async function createPlugin(
>   env: PluginEnvironment,
> ): Promise<Router> {
>   return await createRouter({
>     logger: env.logger,
>     config: env.config,
>     database: env.database,
>     discovery: env.discovery,
>     tokenManager: env.tokenManager,
>     providerFactories: {
>       ...defaultAuthProviderFactories,
> 
>       oauth2Proxy: providers.oauth2Proxy.create({
>         signIn: {
>           async resolver({ result }, ctx) {
>             console.log("--------------------RESULT AUTH--------------")
>             console.log(result)
>             console.log("--------------------END RESULT AUTH--------------")
>             const name = result.getHeader('x-forwarded-preferred-username');
>             if (!name) {
>               throw new Error('Request did not contain a user');
>             }
> 
>            // Create stub user
>            const userEntityRef = stringifyEntityRef({
>             kind: 'User',
>             name: name,
>             namespace: DEFAULT_NAMESPACE,
>           });
> 
>           return ctx.issueToken({
>             claims: {
>               sub: userEntityRef,
>               ent: [userEntityRef],
>             },
>           });
>           },
>         },
>       }),
>       
>     },
>   });
> }
> ```
> 
> * this is my app-config.yaml
> 
> ```
> ...
> 
> backend:
>   # Used for enabling authentication, secret is shared by all backend plugins
>   # See https://backstage.io/docs/auth/service-to-service-auth for
>   # information on the format
>   # auth:
>   #   keys:
>   #     - secret: ${BACKEND_SECRET}
>   baseUrl: http://localhost:4180
>   listen:
>     port: 7007
>     # Uncomment the following host directive to bind to specific interfaces
>     # host: 127.0.0.1
> 
>   cors:
>     origin: http://localhost:4180
>     methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
>     credentials: true
> 
> 
> auth:
>   providers:
>     oauth2Proxy: {}
> 
> 
> ...
> ```
> 
> for backstage configuration i follow [this documentation](https://janus-idp.io/blog/2023/01/17/enabling-keycloak-authentication-in-backstage/)
> 
> <img alt="image" width="1213" src="https://private-user-images.githubusercontent.com/20132141/304150803-74d11652-edde-459f-8f11-386abfa048d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NzgwOTcsIm5iZiI6MTcxNDQ3Nzc5NywicGF0aCI6Ii8yMDEzMjE0MS8zMDQxNTA4MDMtNzRkMTE2NTItZWRkZS00NTlmLThmMTEtMzg2YWJmYTA0OGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDExNDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkOTZjZjdkZjViZmJlM2ZjNjY0YTY5OTQyOTU4YzUzYTI5NGM3ZDA3ZDZmOWU0ZGJkNmUxMzA0NGY4MmFiMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cIexOJgvPBfjgQ3wvL1ysVJZgbAxrJGqmekMzqTTlgU">
> Any idea what i'm missing? please, can you help me?

Hola Orlando!
Me percate por tus repositorios que hablas español. 

¿Aún necesitas ayuda?
