### ISSUE TITLE
🚀 Feature: Add an --exclude flag to backstage-repo-tools api-reports command

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#16903]
### 🔖 Feature description

```console
$ backstage-repo-tools api-reports --exclude 'packages/*'
```

### 🎤 Context

The `api-reports` command on `backstage-repo-tools` is a great way to help a distributed group of people maintain software quality within a backstage ecosystem.

A common pattern for organizing a backstage monorepo is to put plugins under the `plugins/*` folder, and packages that _consume_  those plugins under the `packages/*` folder (e.g. your typical frontend/backend apps).

In such a setup, while it's important to maintain and review API reports for the `plugins/*`, it may not at all be important to do so for anything under `packages/*` (because of that consumption-only relationship).  ...And so one might naturally use the paths to specify `plugins/*` when invoking the report check.

...Doing so, however, only uses typescript config for those filtered packages, which may result in API reports being generated which differ from when they are checked again later as a whole in CI.

What if we provided an `--exclude` flag that took precedence over the existing path argument in terms of typescript config?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
👍, the actual relationship between packages is a lil bit different though. We already skip API reports for frontend app and backend app packages, so the packages in question are internal libraries in `packages/`. It could be argued that it makes sense to generate API report for these packages too, as a way of keeping track of the internal API surface. But either way I think it makes sense to provide this option.
