### ISSUE TITLE
🐛 Bug Report: Workspace 'backend' not found while running 

### ISSUE THREAD

**Issue by ramhariganesh** [backstage/backstage#16904]
### 📜 Description

we are trying to build docker image from git repo. while doing host build, 
yarn install - success
yarn tsc - success
yarn build:backend - fails with error 
**Usage Error: Workspace 'backend' not found. Did you mean any of the following:
  - @backstage/app-defaults
  - @backstage/back**
Can some one please help if we missing some step?

### 👍 Expected behavior

# Build the backend, which bundles it all up into the packages/backend/dist folder.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/125381703/225678760-2a7859c9-e03a-4e76-9333-084b70b89007.png)

### 👟 Reproduction steps

1. Clone github repo 
2. enter into backstage folder
3. yarn install
4. yarn tsc
5. yarn build:backend - failure

### 📃 Provide the context for the Bug.

its stopping to build docker image 

### 🖥️ Your Environment

local

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ramhariganesh** [comment]
@awanlin thanks for the prompt response. how can we package it to run in docker environment?

**Comment by awanlin** [comment]
You would use the results of running `npx @backstage/create-app@latest`. I really recommend you read through the documentation I shared as it will really help

**Comment by ramhariganesh** [comment]
Thanks now managed to build a dcoker image. Happy to close this ticket
