### ISSUE TITLE
🚀 Feature: Customizing security for registration and syncing projects in "Service Catalog"

### ISSUE THREAD

**Issue by Alan18081** [backstage/backstage#16924]
### 🔖 Feature description

When user register, import, sync project or does any action that interacts with VCS like Bitbucket, user provides its own credentials for performing specific API call instead of backstage storing the access tokens in database or environment variables. It could be some UI popup that requests token, use it for API call and then gets rid of it

### 🎤 Context

In our use case we have multiple projects in Bitbucket, where it is not secure to generate god-like token that can be used across multiple projects and it will be very useful and secure from our perspective for backstage to not store the tokens, but just request them from users when it is needed to sync some information. We use Bitbucket server integration.

### ✌️ Possible Implementation

UI component that requests the token every time, when user wants to do some interaction with VCS. Token is just passed to the API call, but never stored in database or ENV variable.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
It does sound awkward from a user perspective to do things that way. Would they go to their entities in the frontend and manually press some refresh button that then triggers an auth flow and does some work in the backend afterwards? I suppose you could do something like that if you made a custom entity provider for that and some custom frontend components to match it - but I question whether the experience will be nice in the end.

Bitbucket has the concept of bitbucket apps right? We leverage that type of concept in the GitHub integration where there's an encapsulated [`GithubCredentialsProvider`](https://github.com/backstage/backstage/blob/44586f71fdd24ef881dbaacb76cbaf8dd6e9a910/packages/integration/src/github/types.ts#L4) that can hand out special tokens based on the complete URL of the things being targeted, using either different tokens or GitHub apps integration.
