### ISSUE TITLE
🐛 Bug Report: `AwsS3UrlReader` in `catalog-backend` forces to use `us-central-1` region

### ISSUE THREAD

**Issue by zcmander** [backstage/backstage#16941]
### 📜 Description

This behaviour has been introduced in Backstage 0.1.17 when `AwsS3UrlReader` upgraded to use aws-sdk v3:

https://github.com/backstage/backstage/commit/87f0bbec175877acde20e82a1a69cd129dbb3545#diff-111378e8aeaef0ed427b92d03ec262915a4704b703697c1042831c33035615e2R50

As you can clearly see, it feeds `DEFAULT_REGION` into configuration which then overrides region given in `app-config.yaml`.

### 👍 Expected behavior

If no region given then let aws-sdk to decide which region should be used. This is because a region can be given via environment variables (`AWS_REGION` and `AWS_DEFAULT_REGION`) or configuration file (`.aws/config`), so let's avoid duplicating aws-sdk logic here and use default behaviour.

### 👎 Actual Behavior with Screenshots

Error in location entity:

```
Unable to read url, AuthorizationHeaderMalformed: Could not retrieve file from S3; caused by AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1'
```

### 👟 Reproduction steps

Config file:

```
integrations:
  awsS3:
    - endpoint: https://s3.eu-central-1.amazonaws.com
       s3ForcePathStyle: true

catalog:
  providers:
    awsS3:
      bucketName: foobar
      prefix: yaml
      region: eu-central-1
```

The issue relates to `AwsS3UrlReader`, so catalog entity provider is not the meaningful thing here but helps in reproducing the issue.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by drodil** [comment]
Screenshot of entity page located in S3 bucket outside us-east-1:
![image](https://user-images.githubusercontent.com/1178319/226338333-3d8fc22d-9547-48ae-890d-fc518d556f62.png)

**Comment by zcmander** [comment]
This is actually a bit on-hold at the moment, because it seems like the initial ingestion for YAML files works, but the later stage where each YAM file are processed fails. I guess it falls under `UrlReader` functionality,  but investigation for it still on-going. The initial description is a bit unclear or even invalid from what I now know about the inner workings.

**Comment by zcmander** [comment]
Apparently I got it working by removing the whole `integrations.awsS3` configuration and rely on default url reader. The root cause is still unknow.

**Comment by malte-behrendt-gr** [comment]
I've the same issue - lots of errors in the logs.
Not sure about the impact yet.

**Comment by malte-behrendt-gr** [comment]
> Apparently I got it working by removing the whole `integrations.awsS3` configuration and rely on default url reader. The root cause is still unknown.

@zcmander How did you switch to default url reader while still discovering from aws s3? Or do you provide the catalog.yaml via another mechanism?

**Comment by zcmander** [comment]
I was able to get it working like this in`app-config.yaml`:
```yaml
catalog:
  providers:
    awsS3:
      foobar:
        bucketName: foobar
        prefix: reports
        region: eu-central-1
```
If I remember correctly, provider does not use `UrlReader` but uses aws-sdk directly. So, that's why the `region` setting is there. After all locations are discovered then `UrlReader` comes into play. So, I can define AWS region in provider-level and that seems to do the trick (my best guess if that the default reader parses region from URL while adding a custom integration disables the parsing feature).

---

I experimented on replacing the default AWS Url reader with a custom one like this:
```typescript
const reader = UrlReaders.create({
      logger,
      config,
      factories: factories.concat([
        AzureUrlReader.factory,
        BitbucketCloudUrlReader.factory,
        BitbucketServerUrlReader.factory,
        BitbucketUrlReader.factory,
        GerritUrlReader.factory,
        GithubUrlReader.factory,
        GiteaUrlReader.factory,
        GitlabUrlReader.factory,
        GoogleGcsUrlReader.factory,
        MyCustomAwsS3UrlReader.factory,
        FetchUrlReader.factory
      ])
    });
```
But I could not get it working, not sure why. But that's how you can build your own custom `UrlReader` if you want to see if it works that way.

**Comment by pjungermann** [comment]
https://backstage.io/docs/integrations/aws-s3/discovery

As stated there, the default region is used if no region is provided. (us-east-1)

Did you check the targets at ingested Location entities? What does the URL look like? Is there any region inside?

The AwsS3UrlReader depends on valid S3 object URLs. These contain the region with the exception of the default region us-east-1.

The discovery may use the environment variables, the output URLs need to be correct still, though. I could imagine that these look like us-east-1 URLs.

https://backstage.io/docs/integrations/aws-s3/locations
As far as I remember, there were some changes to the credential configuration after migration to v3 (config below `aws`). Need to check further, though.


Also, personally, I would not rely on env vars at the UrlReader for resolving the region. That would be a bit unstable for me. E.g., reading from the buckets could break if you move your backstage deployment to another region or if you change the env vars (maybe for another part of the stack). The aws-sdk requires the bucket region, and this region does not change.

For the discovery part, it might be possible, though. And maybe that is where tweaking is needed.

**Comment by Rugvip** [comment]
Yep looks like the `AwsS3UrlReader` might be applying the default region too broadly now. @lucasguariscobr do you have more context around the change in #16652? Specifically that the non-`amazonaws.com` URLs now also default the region to `us-east-1` at https://github.com/backstage/backstage/blob/56fa4924f3ea9d0757d0de4b4d280ebb92e8c694/packages/backend-common/src/reading/AwsS3UrlReader.ts#L115-L125

As far as I can tell it was previously left to the SDK to determine the region, did that break in v3?

**Comment by lucasguariscobr** [comment]
@Rugvip Adding some context: The AwsS3UrlReader was using AWS global configuration, with v3 we're building a S3Client and configuring the region in the client. The region wasn't a required field in the configuration, so the solution was to retrieve it from the URL to avoid making it required. The understanding was that other S3-like solutions were compliant with AWS' URL syntax, and if no region was present, then the default region would be us-east-1, just as in S3.
