### ISSUE TITLE
🚀 Feature: allow displaying aggregated membership in catalog Group details view

### ISSUE THREAD

**Issue by alexef** [backstage/backstage#16959]
### 🔖 Feature description

When viewing a Group, one can select between direct relations / agregated relations for components.

However, for members, only direct relations are considered.

As we have nested groups, I believe a similar toggle would be beneficial.

<img width="1259" alt="Screenshot 2023-03-20 at 09 43 16" src="https://user-images.githubusercontent.com/346576/226290737-db9c7167-40ed-47fb-b2ab-48774f578541.png">

### 🎤 Context

All our nested groups display 0 members at the moment, because viewing agregated members (from child groups) is not possible.

### ✌️ Possible Implementation

A similar toggle as the OwnershipCard or a parameter MembersListCard component.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Alright, that could be useful. You thinking that the switch could look the same as the ownership one? With like `Direct members` and `Include subgroup members` for example?

Might be useful then to render the table in such a way that when the second option is set, you can see which ones are direct and which are farther down. Maybe a column titled "Via" or some sensible wording, that contains their actual group (or groups!) below us that they are in.

**Comment by alexef** [comment]
@freben members are not a table, rather a grid with avatars: 
<img width="1625" alt="Screenshot 2023-03-20 at 12 58 29" src="https://user-images.githubusercontent.com/346576/226333011-f662d5b5-ad13-429b-9966-d981a0c0bda5.png">

agree it makes sense to add a visual differentiator. no idea how it should look like

**Comment by pjungermann** [comment]
That sounds pretty useful actually!

**Comment by wss-rbunning** [comment]
@jtreher I can contribute the changes I am working on internally for this feature when I am finished 👍

**Comment by ahochsteger** [comment]
@freben I've got a question in the context of nested group memberships which might be related to this issue:
Are nested group memberships taken into account in permission conditions - specifically `catalogConditions.isEntityOwner`?

**Comment by benjdlambert** [comment]
I think that @vinzscam might be best placed to answer that @ahochsteger 🙏

**Comment by vinzscam** [comment]
> @freben I've got a question in the context of nested group memberships which might be related to this issue: Are nested group memberships taken into account in permission conditions - specifically `catalogConditions.isEntityOwner`?

nope, only direct relationships are taken into consideration. Unless you pass claims of the user to `isEntityOwner` (in case you want to conditionally allow a decision based on entities owned by the user). In that case it is possible to get nested group memberships if you properly customize your [identity resolver](https://backstage.io/docs/auth/identity-resolver/).
