### ISSUE TITLE
🐛 Bug Report: Sonarqube - Hotspots Reviewed wrong link 

### ISSUE THREAD

**Issue by tantran-earnin** [backstage/backstage#16950]
### 📜 Description

- Under the Sonarqube Code Quality card, when you click on Hotspots Reviewed link, it takes you to an invalid link.

### 👍 Expected behavior

It should take you to a valid link https://sonarqube-url/security_hotspots?id=component-name

### 👎 Actual Behavior with Screenshots

It takes you to https://sonarqube-url/project/security_hotspots?id=component-name

### 👟 Reproduction steps

1. Go to a Component
2. Under Code Quality card, click on Hotspots Reviewed
3. Takes you to https://sonarqube-url/**project**/security_hotspots?id=component-name

### 📃 Provide the context for the Bug.

https://github.com/backstage/backstage/blob/0182d61b9802ac314bf67fab4896a151f88c4385/plugins/sonarqube/src/api/SonarQubeClient.ts#L130

### 🖥️ Your Environment

Self-hosted Sonarqube (Developer EditionVersion 9.9 (build 65466))

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Alright - I'll have to take your word for it as I'm not using sonarqube myself :) Feel free to issue a PR and we'll review it. Ping @dhenneke as the original maker.

**Comment by dhenneke** [comment]
I don't actively work with SonarQube/SonarCloud (or backstage) anymore. But what I see is that it might differ between SonarQube and SonarCloud. But I'm not sure if this a general behavior in all SonarQube versions or if that changed recently.

Some public examples I found:
* SonarCloud: Must use `/project/security_hotspots`: https://sonarcloud.io/project/security_hotspots?id=matrix-react-sdk
* SonarQube: Must use `/security_hotspots`: https://next.sonarqube.com/security_hotspots?id=org.sonarsource.flex%3Aflex&inNewCodePeriod=true

A solution might be to change the URL template depending on whether the base url is `https://sonarcloud.io` or not. But I can't help with a PR for that 🙂.

**Comment by freben** [comment]
Thanks for pitching in!
