### ISSUE TITLE
🐛 Bug Report: Can't uncheck selected tags when reloading page after checked

### ISSUE THREAD

**Issue by cklewin** [backstage/backstage#17021]
### 📜 Description

Can't uncheck tag on pages with a `Tags` filter when reloading page with it checked.

This seems to be limited to the `Tags` filter, other filters allow unchecking.

This was not happening with Backstage 1.10.1, started happening to me after upgrading to 1.12.1.

### 👍 Expected behavior

It should allow me to uncheck a `Tags` filter at any time.

The `Tags` filter should behave the same as the other filter dropdowns.

### 👎 Actual Behavior with Screenshots

It actually prevents me from unchecking a `Tags` filter if the page reloads with it checked.

The `Tags` filter does not behave the same as the other filter dropdowns.

### 👟 Reproduction steps

This bug is reproducable in the Backstage demo site:

https://demo.backstage.io/

Select a tag from the Tags dropdown to filter the results.  Uncheck the tag to unfilter the results, should work as expected.  Check the tag again, and reload the page while the tag is checked.  You should no longer be able to uncheck the selected tag.

Following this link, the "data" tag cannot be unchecked:
https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all&filters%5Btags%5D=data

Following this link, the "team-a" owner can be unchecked as expected:
https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all&filters%5Bowners%5D=team-a&filters%5Btags%5D=data

### 📃 Provide the context for the Bug.

The link to `Create...` in the side bar is preset to show only templates tagged with "default"

src/components/Root/Root.tsx
```
        <SidebarItem
          icon={CreateComponentIcon}
          to="create?filters[kind]=template&filters[user]=all&filters[tags]=default"
          text="Create..."
        />
```

We do this so we can show only the most common templates to the user, while still grouping them.  If the user wants to see all the templates, they just need to uncheck `default` from the tags dropdown.

### 🖥️ Your Environment

Doesn't seem to be browser specific.  Tested with latest Chrome / Safari / Firefox.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
Thank you for the detailed report! This is indeed a bug

**Comment by Parsifal-M** [comment]
Hey @Rugvip I can pick this one up on the weekend I have some spare time again finally 😅 👍

**Comment by Rugvip** [comment]
@Parsifal-M awesome, thank you! 🎉

**Comment by headphonejames** [comment]
This issue is here: https://github.com/backstage/backstage/blob/b268dab386518a2bb59c5020fa1a228939e20a57/plugins/catalog-react/src/components/EntityAutocompletePicker/EntityAutocompletePicker.tsx#L102

caused by: https://github.com/backstage/backstage/commit/f5a9b0ac7fc5db0d358519a55974b3a59fb8d375

**Comment by Parsifal-M** [comment]
> This issue is here:
> 
> https://github.com/backstage/backstage/blob/b268dab386518a2bb59c5020fa1a228939e20a57/plugins/catalog-react/src/components/EntityAutocompletePicker/EntityAutocompletePicker.tsx#L102
> 
> caused by: [f5a9b0a](https://github.com/backstage/backstage/commit/f5a9b0ac7fc5db0d358519a55974b3a59fb8d375)

Ah nice, thanks @headphonejames, shall I leave this in your hands then? 👍

**Comment by headphonejames** [comment]
yes please, I'll have a PR today. Thanks.
