### ISSUE TITLE
Add githubApp authentication to scaffolder plugin

### ISSUE THREAD

**Issue by ebarriosjr** [backstage/backstage#1702]
Right now the github authentication for the scaffolder plugin depends on a GITHUB_TOKEN env variable.

## Feature Suggestion
It would be nice to pass a token from the frontend scaffolder plugin to the scaffolder-backend plugin to authenticate to github via githubApp.

## Possible Implementation
Add authentication on the scaffolder plugin and add and extra field (token) to be passed to the backend to execute the command to github.

## Context
I am trying to use a githubApp instead of a github token.

**Comment by benjdlambert** [comment]
This work is planned, theres an RFC here: #1565 

If you've got any input would be appreciated there! :)

**Comment by stefanalund** [comment]
@benjdlambert should this be closed?

**Comment by benjdlambert** [comment]
@stefanalund good question - not sure if we should close it when it's actually done? The work isn't complete yet. We are creating the tickets for work on this at the next architecture meeting.

**Comment by benjdlambert** [comment]
maybe we close it after we've made tickets to implement it

**Comment by stefanalund** [comment]
@benjdlambert would this be needed to support GitHub Enterprise? If so I think this is highly relevant.

**Comment by benjdlambert** [comment]
I think it would help, would make it easier at least

**Comment by benjdlambert** [comment]
I will create some tickets and put them until scaffolder beta

**Comment by adamdmharvey** [comment]
Just updating to note, seems `@backstage/scaffolder-backend` still relies on only a passed token from the Integrations, but I believe still doesn't support a true GitHub App yet:
https://github.com/backstage/backstage/blob/1b424445874f2704abcf6388339bf8e38159beec/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts#L115-L118

**Comment by benjdlambert** [comment]
This can be closed. It uses the credentials provider which takes into account the `githubApps` config too in the `integrations` config.

https://github.com/backstage/backstage/blob/1b424445874f2704abcf6388339bf8e38159beec/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts#L105-L107

https://backstage.io/docs/plugins/github-apps#docsNav

**Comment by benjdlambert** [comment]
Think this was just hanging around :)

**Comment by kuangp** [comment]
@benjdlambert does this mean https://github.com/backstage/backstage/issues/4126 can be closed as well?
