### ISSUE TITLE
🚀 Feature: Improve hover state and icon for Lightbox feature

### ISSUE THREAD

**Issue by anilazaidi** [backstage/backstage#17020]
### 🔖 Feature description

The hover state on images should be improved to let users know they can zoom in on an image.

### 🎤 Context

Currently the Lightbox feature doesn't have a hover state that let's me know that you can zoom in on an image. Also, when the feature is enabled, the default icon is a magnifying glass with a `minus` icon. I found this confusing b/c I didn't want to minimize the image. It took me a minute to realize that I could zoom in...

Please see gif to see all this in action:
![Screen Recording 2023-03-22 at 10 29 31 AM](https://user-images.githubusercontent.com/52043997/226940607-13f95849-8bd1-4e2f-a4bf-aa15e45f6580.gif)

### ✌️ Possible Implementation

Maybe have a finger pointer on images like Confluence? Please see gif:
![Screen Recording 2023-03-22 at 10 46 51 AM](https://user-images.githubusercontent.com/52043997/226942338-46e8851e-a98f-450f-9839-296e035b05b9.gif)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Makes sense! I think we need a well-placed `cursor: pointer` here right?

**Comment by gustavojms** [comment]
Hey guys, i'm willing to take this implemetation and i'd like to know more about this issu. Could you let me know where to find the file to make these changes and it is going to be just the cursor or we are going to make more modifications to this feature?

**Comment by dweber019** [comment]
You can find the lightBox code here https://github.com/backstage/backstage/tree/master/plugins/techdocs-module-addons-contrib/src/LigthBox. I think you can do this with https://photoswipe.com/styling/ and apply your css here https://github.com/backstage/backstage/blob/master/plugins/techdocs-module-addons-contrib/src/LigthBox/LightBox.tsx.

Maybe this is the solution => https://photoswipe.com/click-and-tap-actions/ (override zoom cursor)

**Comment by npiyush97** [comment]
@dweber019 steps to replicate?

**Comment by dweber019** [comment]
@npiyush97 My input was some help for implementing this, not to replicate something. Or what do you mean with steps to replicate?

**Comment by npiyush97** [comment]
> @npiyush97 My input was some help for implementing this, not to replicate something. Or what do you mean with steps to replicate?

like how to use lightbox locally ?

**Comment by kmarkow** [comment]
I opened a PR to fix this, please let me know if this is what you was hoping for @anilazaidi

**Comment by anilazaidi** [comment]
Apologies for the late response @kmarkow. This looks great though!!
