### ISSUE TITLE
"Looks like someone dropped the mic" in the ErrorPage component seems like a misuse of the colloquialism

### ISSUE THREAD

**Issue by kallayj** [backstage/backstage#17039]
### 📜 Description

"Dropping the mic" means doing something so impressive that you can just drop the mic and walk off the stage.
"Dropping the ball" means making a mistake.
"Looks like someone dropped the mic" on an error page appears (at least on its face) to be the result of mixing these two expressions up, maybe in an attempt to connect it to the musical theme that gave Backstage its name?

### 👍 Expected behavior

I think it should be "looks like someone dropped the ball," or maybe something more music-related that suggests making a mistake.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/118477617/227059634-2efe691d-1f6d-4194-bd8a-a46322958a01.png)

### 👟 Reproduction steps

Go to https://demo.backstage.io/foo, or any other url on a Backstage instance that would produce a 404.

### 📃 Provide the context for the Bug.

It is jarring/confusing to read a message that states the opposite of what it intends.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Parsifal-M** [comment]
Wouldn't really consider this a bug per-se 😅.

I understood it as someone just "dropped the mic and left" like an "Ah screw it" kind of drop.

It's up to interpretations of course but also something like "Is this thing on?" could work 😄

**Comment by kallayj** [comment]
I like "is this thing on?" for a 404!
