### ISSUE TITLE
🐛 Bug Report: New relation type for same source entity and target entity pair not reflected

### ISSUE THREAD

**Issue by alecjacobs5401** [backstage/backstage#17063]
### 📜 Description

Defining two unique relationships between two entities results in one of the Entities not having the relation reflected in the `final_entity` post processing.

Given the following scenario:
A `Group` is defined as follows and is ingested into the Software catalog
```yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: test-group
spec:
  type: team
  children: []
```

Some time later, a new `User` entity is defined that has a [custom defined relation type](https://backstage.io/docs/features/software-catalog/extending-the-model#adding-a-new-relation-type) of `company-riskOwner`
```yaml
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: test-user
spec:
  company-riskOwner: group:default/test-group
```

After `user:default/test-user` is ingested in the Catalog, we have two Entities that have proper relations emitted and defined in the respective final entities: `group:default/test-group` has a  relation `type` of `company-riskOwnedBy` with a target of `user:default/test-user` and  `user:default/test-user` has a relation `type` of `company-riskOwnerOf` with a target of `group:default/test-group`

Now, some time later, the `group:default/test-group` Entity definition is updated to include a `members` definition as follows:
```yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: test-group
spec:
  type: team
  members: [test-user]
  children: []
```

After the processing pipeline finishes, `group:default/test-group` now has **two** relations defined:
1. relation `type` of `company-riskOwnedBy` with a target of `user:default/test-user`
2. relation `type` of `hasMember` with a target of `user:default/test-user`

_however_, `user:default/test-user` still only has **one** relation defined in the finaly entity: `user:default/test-user` has a relation `type` of `company-riskOwnerOf` with a target of `group:default/test-group`. 

The `memberOf` relation is missing.

### 👍 Expected behavior

After processing finishes, the `user:default/test-user` Entity should also have two relations defined in its `final_entity`:
1. `user:default/test-user` has a relation `type` of `company-riskOwnerOf` with a target of `group:default/test-group`
2. `user:default/test-user` has a relation `type` of `memberOf` with a target of `group:default/test-group`

### 👎 Actual Behavior with Screenshots

The `memberOf` relation type is missing on the User entity

### 👟 Reproduction steps

See steps above

### 📃 Provide the context for the Bug.

As a result, the `test-user` does not show up as a Member in the `Group` entity page, which is misleading.

In our actual catalog, our User entities come from an Entity Provider where we don't have full control to add the `memberOf` field yet.

I believe I've honed it down to https://github.com/backstage/backstage/blob/v1.11.1/plugins/catalog-backend/src/processing/DefaultCatalogProcessingEngine.ts#L226-L238

Specifically, the 
```ts
const newRelationSources = new Set<string>(
  result.relations.map(relation =>
    stringifyEntityRef(relation.source),
  ),
);

...

newRelationSources.forEach(r => {
  if (!oldRelationSources.has(r)) {
    setOfThingsToStitch.add(r);
  }
});
```
when determining the stitching is only looking at the stringified entityRef for the relation source - it does _not_ include the type of relation. This means that stitching might not occur when it should given that the [Relation Row deduplication take source + target + type of relation into account](https://github.com/backstage/backstage/blob/v1.11.1/plugins/catalog-backend/src/database/DefaultProcessingDatabase.ts#L295-L300)

`setOfThingsToStitch` never is updated for the new relation since the _source_ is the same, but the type has changed.

### 🖥️ Your Environment

```
OS:   Darwin 22.3.0 - darwin/x64
node: v16.14.0
yarn: 1.22.17
cli:  0.22.3 (installed)
backstage:  1.11.1

Dependencies:
  @backstage/app-defaults                               1.2.0
  @backstage/backend-app-api                            0.4.0
  @backstage/backend-common                             0.18.2
  @backstage/backend-dev-utils                          0.1.0
  @backstage/backend-plugin-api                         0.4.0
  @backstage/backend-tasks                              0.4.3
  @backstage/backend-test-utils                         0.1.34
  @backstage/catalog-client                             1.3.1
  @backstage/catalog-model                              1.1.1, 1.2.0
  @backstage/cli-common                                 0.1.11
  @backstage/cli                                        0.22.3
  @backstage/config-loader                              1.1.8
  @backstage/config                                     1.0.6
  @backstage/core-app-api                               1.5.0
  @backstage/core-components                            0.11.1, 0.11.2, 0.12.4
  @backstage/core-plugin-api                            1.0.6, 1.4.0
  @backstage/dev-utils                                  1.0.12
  @backstage/errors                                     1.1.4
  @backstage/eslint-plugin                              0.1.1
  @backstage/integration-react                          1.1.10
  @backstage/integration                                1.4.2
  @backstage/plugin-analytics-module-ga                 0.1.26
  @backstage/plugin-api-docs-module-protoc-gen-doc      0.1.1
  @backstage/plugin-api-docs                            0.9.0
  @backstage/plugin-app-backend                         0.3.42
  @backstage/plugin-auth-backend                        0.18.0
  @backstage/plugin-auth-node                           0.2.11
  @backstage/plugin-catalog-backend-module-aws          0.1.16
  @backstage/plugin-catalog-backend-module-github       0.2.5
  @backstage/plugin-catalog-backend                     1.7.2
  @backstage/plugin-catalog-common                      1.0.11
  @backstage/plugin-catalog-graph                       0.2.27
  @backstage/plugin-catalog-node                        1.3.3
  @backstage/plugin-catalog-react                       1.1.4, 1.3.0
  @backstage/plugin-catalog                             1.8.0
  @backstage/plugin-events-backend-module-github        0.1.4
  @backstage/plugin-events-backend                      0.2.3
  @backstage/plugin-events-node                         0.2.3
  @backstage/plugin-github-actions                      0.5.15
  @backstage/plugin-github-pull-requests-board          0.1.9
  @backstage/plugin-home                                0.4.31
  @backstage/plugin-kubernetes-backend                  0.9.3
  @backstage/plugin-kubernetes-common                   0.6.0
  @backstage/plugin-kubernetes                          0.7.8
  @backstage/plugin-org                                 0.6.5
  @backstage/plugin-pagerduty                           0.5.8
  @backstage/plugin-permission-common                   0.6.4, 0.7.3
  @backstage/plugin-permission-node                     0.7.5
  @backstage/plugin-permission-react                    0.4.10
  @backstage/plugin-proxy-backend                       0.2.36
  @backstage/plugin-scaffolder-backend                  1.11.0
  @backstage/plugin-scaffolder-common                   1.2.5
  @backstage/plugin-scaffolder-node                     0.1.0
  @backstage/plugin-scaffolder-react                    1.1.0
  @backstage/plugin-scaffolder                          1.11.0
  @backstage/plugin-search-backend-module-elasticsearch 1.1.3
  @backstage/plugin-search-backend-module-pg            0.5.3
  @backstage/plugin-search-backend-node                 1.1.3
  @backstage/plugin-search-backend                      1.2.3
  @backstage/plugin-search-common                       1.2.1
  @backstage/plugin-search-react                        1.5.0
  @backstage/plugin-search                              1.1.0
  @backstage/plugin-shortcuts                           0.3.7
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.26
  @backstage/plugin-tech-insights-backend               0.5.8
  @backstage/plugin-tech-insights-common                0.2.10
  @backstage/plugin-tech-insights-node                  0.4.0
  @backstage/plugin-tech-insights                       0.3.7
  @backstage/plugin-user-settings-backend               0.1.6
  @backstage/plugin-user-settings                       0.7.0
  @backstage/release-manifests                          0.0.8
  @backstage/test-utils                                 1.2.5
  @backstage/theme                                      0.2.17
  @backstage/types                                      1.0.2
  @backstage/version-bridge                             1.0.3
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kpink224** [comment]
+1 to this. 

We have a similar issue with trying to assign `ownedBy` and a custom relation `activelyAuthoredBy` between a component and group. When processing is done, we do see that both relations are in the raw yaml when we inspect the entity:
```
...
relations:
  - type: activelyAuthoredBy
    targetRef: group:default/myteam
    target:
      kind: group
      namespace: default
      name: myteam
  - type: ownedBy
    targetRef: group:default/myteam
    target:
      kind: group
      namespace: default
      name: myteam
```
But the catalog-graph plugin makes assumptions to only show the first one. Looking through that code, it purposefully was designed that way and feeds the nodes and edges back to the DependencyGraph core component. 

Overall seems like we need to support multiple relations between the same nodes but also curious if the Backstage team has worked around this issue or have a reason on why this shouldn't be fixed. IMO @alecjacobs5401 presents a pretty common use case as well as ours.

**Comment by Rugvip** [comment]
Thank you for reporting! 👍  I think you found the cause for it, being the stitching detection logic that you point at. Would you like to contribute a fix?

**Comment by alecjacobs5401** [comment]
I'd be happy to put something together - might take a couple days to get a PR open, though.
