### ISSUE TITLE
Could not fetch catalog entities

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#17088]
### 📜 Description

I am getting this error. I have 2000 API's with swagger files.

"error": {
"name": "RangeError",
"message": "Invalid string length",
"stack": "RangeError: Invalid string length\n    at JSON.stringify (<anonymous>)\n    at stringify node_modules/express/lib/response.js:1150:12)\n    at ServerResponse.json node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:3594:11\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### 👍 Expected behavior

It should work fine.

### 👎 Actual Behavior with Screenshots

<img width="989" alt="image" src="https://user-images.githubusercontent.com/225961/227579825-70f8566a-8468-47ca-acc9-14eb24a7819c.png">

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/225961/227580539-a43abaf0-9d88-48d9-9c32-346850614fbc.png">

### 👟 Reproduction steps

1) Create New App.
    - npx @backstage/create-app
 2) Register 2000 API's with swaggers
 3) click on API page 
 

### 🖥️ Your Environment

yarn run v1.22.19
$ /developer-portal/node_modules/.bin/backstage-cli info
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.17.0
yarn: 1.22.19
cli:  0.22.5 (installed)
backstage:  1.12.0

Dependencies:
  @backstage/app-defaults                          1.2.1
  @backstage/backend-app-api                       0.4.1
  @backstage/backend-common                        0.18.3
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.0
  @backstage/backend-tasks                         0.5.0
  @backstage/catalog-client                        1.4.0
  @backstage/catalog-model                         1.2.1
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.22.5
  @backstage/config-loader                         1.1.9
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.6.0
  @backstage/core-components                       0.12.5
  @backstage/core-plugin-api                       1.5.0
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.2
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.11
  @backstage/integration                           1.4.3
  @backstage/plugin-api-docs                       0.9.1
  @backstage/plugin-app-backend                    0.3.43
  @backstage/plugin-auth-backend                   0.18.1
  @backstage/plugin-auth-node                      0.2.12
  @backstage/plugin-catalog-backend                1.8.0
  @backstage/plugin-catalog-common                 1.0.12
  @backstage/plugin-catalog-graph                  0.2.28
  @backstage/plugin-catalog-import                 0.9.6
  @backstage/plugin-catalog-node                   1.3.4
  @backstage/plugin-catalog-react                  1.4.0
  @backstage/plugin-catalog                        1.9.0
  @backstage/plugin-github-actions                 0.5.16
  @backstage/plugin-org                            0.6.6
  @backstage/plugin-permission-common              0.7.4
  @backstage/plugin-permission-node                0.7.6
  @backstage/plugin-permission-react               0.4.11
  @backstage/plugin-proxy-backend                  0.2.37
  @backstage/plugin-scaffolder-backend             1.12.0
  @backstage/plugin-scaffolder-common              1.2.6
  @backstage/plugin-scaffolder-node                0.1.1
  @backstage/plugin-scaffolder-react               1.2.0
  @backstage/plugin-scaffolder                     1.12.0
  @backstage/plugin-search-backend-module-pg       0.5.4
  @backstage/plugin-search-backend-node            1.1.4
  @backstage/plugin-search-backend                 1.2.4
  @backstage/plugin-search-common                  1.2.2
  @backstage/plugin-search-react                   1.5.1
  @backstage/plugin-search                         1.1.1
  @backstage/plugin-tech-radar                     0.6.2
  @backstage/plugin-techdocs-backend               1.6.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.11
  @backstage/plugin-techdocs-node                  1.6.0
  @backstage/plugin-techdocs-react                 1.1.4
  @backstage/plugin-techdocs                       1.6.0
  @backstage/plugin-user-settings                  0.7.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.2.6
  @backstage/theme                                 0.2.18
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
✨  Done in 3.19s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Yep there are some scaling limitations to the catalog, in this case it's likely that large API definitions are causing the issue. We improve the response logic to switch out to a streaming JSON serializer. If anyone would like to contribute that It should be fairly easy to ship.

Other ways to potentially work around this is to make sure you have enough memory on your catalog instance node(s). It seems like this is error is actually due to an OOM error.

**Comment by lalit774** [comment]
@Rugvip: it seem to catalog load all the fields. Even we are not using those to display on catalog page. for example spec.definition. I don't believe, if there is any reason to load definition for catalog page.

is there any way to remove definition field or set the require field. or if we can extend the useEntityListProvider

https://github.com/backstage/backstage/blob/a2fbdfde360d06a6c7c94ded4271f8ecaee907fb/plugins/catalog-react/src/hooks/useEntityListProvider.tsx#L113

```
        const response = await catalogApi.getEntities({
          filter: backendFilter,
          fields: [
            'kind, metadata.description, metadata.name, spec.lifecycle,  spec.type,  relations',
          ],
        });
```

**Comment by benjdlambert** [comment]
I think that the changes to the catalog table are going to be pretty difficult as there's nothing in place from the filters or the columns to notify the framework which value they are derived from in the response, this might be an option but this is going to take some time to build unfortunately.

**Comment by freben** [comment]
There's no really easy way to tweak that behaviour at this point. We do want to somehow make it possible for both columns and filters of a catalog page to declare exactly what fields they need, so that only those get fetched.

The only thing that comes to mind for me regarding filtering out fields right now, is to embed the entire catalog page in an `<ApiProvider>` that supplies a custom implementation of the `catalogApiRef` to its child elements. That client could tap into requests that pass through it and add a `fields` limiter as needed to the requests before they are sent to the backend.

Slightly hacky, but would work.
