### ISSUE TITLE
Add Backstage to the CNCF Project Summary Table

### ISSUE THREAD

**Issue by CathPag** [backstage/backstage#17081]
### 🔖 Feature description

Dear maintainers,

The CNCF Business Value Subcommittee has developed a project summary table to supplement the CNCF Landscape and includes further information about CNCF projects for the broader cloud native community. We would like to request your project to submit a PR to the CNCF Landscape repository with additional details that will help further inform the community about your project and its use cases through the popular landscape and this new addition.

The table is located here: https://landscape.cncf.io/summary
There are directions located here: https://github.com/cncf/landscape/blob/master/readme_summary.md

Many thanks for this - we hope it will help further get the word out about your project.

### 🎤 Context

Sorry, not the right issue template, but there is nothing for this type of request.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
Added them here https://github.com/cncf/landscape/pull/3214/files
