### ISSUE TITLE
🐛 Bug Report: Running builds in CircleCI table say "took" when not done

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#17093]
### 📜 Description

Via a small quirk in the CircleCI plugin, whenever there is an in progress job, the time column ends with the word "took" and nothing else. That's because it's not DONE yet, so it can't identify how long it took.

### 👍 Expected behavior

I would expect a running job just says how long ago it had been running, which is likely enough. Then when it's DONE, it could say it took X seconds.

### 👎 Actual Behavior with Screenshots

<img width="623" alt="image" src="https://user-images.githubusercontent.com/33203301/227644438-3417b992-7906-4caa-a8d4-b8b47f483d05.png">

### 👟 Reproduction steps

1. Install CircleCI plugin
2. Trigger a job.
3. View the CI/CD tab for a component while the job is still running.

### 📃 Provide the context for the Bug.

Likely just needs an if check that if the endtime hasn't been set yet, then don't show the entire typography set for the took seconds section.

https://github.com/backstage/backstage/blob/d8fea08f7c377fd8b8660bc9729d54375a5367a8/plugins/circleci/src/components/BuildsPage/lib/CITable/CITable.tsx#L199-L211

### 🖥️ Your Environment

OS:   Darwin 22.3.0 - darwin/x64
node: v16.19.0
yarn: 1.22.10
cli:  0.22.4 (installed)
backstage:  1.12.0

Dependencies:
  @backstage/app-defaults                          1.2.1
  @backstage/backend-app-api                       0.4.1
  @backstage/backend-common                        0.18.3
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.0
  @backstage/backend-tasks                         0.5.0
  @backstage/catalog-client                        1.4.0
  @backstage/catalog-model                         1.2.1
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.22.4
  @backstage/config-loader                         1.1.9
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.6.0
  @backstage/core-components                       0.12.5
  @backstage/core-plugin-api                       1.5.0
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.2
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.11
  @backstage/integration                           1.4.3
  @backstage/plugin-api-docs                       0.9.1
  @backstage/plugin-app-backend                    0.3.43
  @backstage/plugin-auth-backend                   0.18.1
  @backstage/plugin-auth-node                      0.2.12
  @backstage/plugin-catalog-backend-module-github  0.2.6
  @backstage/plugin-catalog-backend                1.8.0
  @backstage/plugin-catalog-common                 1.0.12
  @backstage/plugin-catalog-graph                  0.2.28
  @backstage/plugin-catalog-import                 0.9.6
  @backstage/plugin-catalog-node                   1.3.4
  @backstage/plugin-catalog-react                  1.4.0
  @backstage/plugin-catalog                        1.9.0
  @backstage/plugin-circleci                       0.3.16
  @backstage/plugin-events-node                    0.2.4
  @backstage/plugin-explore-backend                0.0.5
  @backstage/plugin-explore-common                 0.0.1
  @backstage/plugin-explore-react                  0.0.27
  @backstage/plugin-explore                        0.4.1
  @backstage/plugin-github-actions                 0.5.16
  @backstage/plugin-home                           0.4.32
  @backstage/plugin-org                            0.6.6
  @backstage/plugin-pagerduty                      0.5.9
  @backstage/plugin-permission-common              0.7.4
  @backstage/plugin-permission-node                0.7.6
  @backstage/plugin-permission-react               0.4.11
  @backstage/plugin-proxy-backend                  0.2.37
  @backstage/plugin-scaffolder-backend             1.12.0
  @backstage/plugin-scaffolder-common              1.2.6
  @backstage/plugin-scaffolder-node                0.1.1
  @backstage/plugin-scaffolder-react               1.2.0
  @backstage/plugin-scaffolder                     1.12.0
  @backstage/plugin-search-backend-module-pg       0.5.4
  @backstage/plugin-search-backend-node            1.1.4
  @backstage/plugin-search-backend                 1.2.4
  @backstage/plugin-search-common                  1.2.2
  @backstage/plugin-search-react                   1.5.1
  @backstage/plugin-search                         1.1.1
  @backstage/plugin-sonarqube-backend              0.1.8
  @backstage/plugin-sonarqube-react                0.1.4
  @backstage/plugin-sonarqube                      0.6.5
  @backstage/plugin-tech-radar                     0.6.2
  @backstage/plugin-techdocs-backend               1.6.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.11
  @backstage/plugin-techdocs-node                  1.6.0
  @backstage/plugin-techdocs-react                 1.1.4
  @backstage/plugin-techdocs                       1.6.0
  @backstage/plugin-user-settings                  0.7.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.2.6
  @backstage/theme                                 0.2.18
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
✨  Done in 1.26s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Parsifal-M** [comment]
Happy to look at fixing this, the only issue is I do not use CircleCI, is there a way I can test it without using CircleCI? 🤔 💭 

Thanks!

**Comment by adamdmharvey** [comment]
@Parsifal-M awesome!

I feel like the correct answer to that is to write a test suite for that module, which currently it lacks?  That way you could mock the API response and then entirely play with it within a testing call.  Now, whether or not a test suite gets added...

CircleCI is free for basic open source use and can connect to any GitHub account, so if you're REALLY interested, you could easily sign up for an account, and you'd immediately be able to follow all the instructions in the app which is raw cloned out of this repo (which I've done before). Roughly it's add a temporary CircleCI annotation to one of the sample entity files in the repo, create your API key (which you do once logged in) and configure `app-config.yaml` per the plugin README.md, launch the app locally, open your component, open the CI/CD tab, and then you can play around!!

https://app.circleci.com -> 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/33203301/228237571-e0bcd234-d510-46d9-bfd5-084d292407f5.png">

**Comment by Parsifal-M** [comment]
> @Parsifal-M awesome!
> 
> I feel like the correct answer to that is to write a test suite for that module, which currently it lacks?  That way you could mock the API response and then entirely play with it within a testing call.  Now, whether or not a test suite gets added...
> 
> CircleCI is free for basic open source use and can connect to any GitHub account, so if you're REALLY interested, you could easily sign up for an account, and you'd immediately be able to follow all the instructions in the app which is raw cloned out of this repo (which I've done before). Roughly it's add a temporary CircleCI annotation to one of the sample entity files in the repo, create your API key (which you do once logged in) and configure `app-config.yaml` per the plugin README.md, launch the app locally, open your component, open the CI/CD tab, and then you can play around!!
> 
> https://app.circleci.com -> 
> <img width="505" alt="image" src="https://user-images.githubusercontent.com/33203301/228237571-e0bcd234-d510-46d9-bfd5-084d292407f5.png">
> 
> I'm happy to help guide, just not able to try to fix this at the moment.

Thanks for the info! You are right 👍I will start looking into this today and maybe come back with a solution tomorrow 🚀
