### ISSUE TITLE
🐛 Bug Report: default browser behaviour with keyboard navigation for tabs wrongly overwritten

### ISSUE THREAD

**Issue by amosciatti** [backstage/backstage#17117]
### 📜 Description

Browsing a Backstage page with Tabs, it is not possible to use the default `Alt+←` shortcut to return to previous page, as it seams like this and all the shortcuts involving the arrow keys were changed to switch between tabs.

### 👍 Expected behavior

pressing `Alt+←` shortcut, it should return to previous visited page from your browsing history
pressing `Alt+→ ` shortcut, it should return to next visited page from your browsing history

### 👎 Actual Behavior with Screenshots

browser switch to previous or next tab of the visited page in sequence 

### 👟 Reproduction steps

1. go to https://demo.backstage.io/catalog/default/component/playback-order
2. click on one tab (i.e. API)
3. press `Alt+←` or even just the left or right arrows

### 📃 Provide the context for the Bug.

Behaviour is against browser rules

For the WCAG advice regarding keyboard interaction, check out this page https://www.w3.org/WAI/WCAG22/Understanding/keyboard.html

Also as handy references:
https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Ctab-window-shortcuts
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

### 🖥️ Your Environment

Not relevant as issue is available also in Backstage Demo https://demo.backstage.io/catalog/default/component/playback-order

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Looks like there's an issue here with either the mui tabs or us that grab the left and right arrows from the keyboard to cycle the tab contents which overrides the default behaviour. Think we should look at fixing this!
