### ISSUE TITLE
🐛 Bug Report: Catalog filtering with checkbox filters doesn't allow target on the word text

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#17119]
### 📜 Description

When using the checkbox filters that allow you to check/uncheck items in a catalog view, you can click the checkboxes themselves, or the whitespace, but turns out clicking the actual text of the entry doesn't activate the target to turn on the checkbox.

### 👍 Expected behavior

When opening the lifecycle filter, if I click the word "production" I'd expect that checkbox to be turned on without having to actually click the checkbox (or the whitespace).

### 👎 Actual Behavior with Screenshots

https://user-images.githubusercontent.com/33203301/227966016-e2e7c0cd-180c-4e72-8295-b051880786d3.mov

### 👟 Reproduction steps

1. Visit https://demo.backstage.io
2. In the filters panel, scroll down to the Lifecycle filter
3. Open Lifecycle filter
4. Try to click "experimental" the word.

This does not trigger the checkbox for lifecycle.

### 🖥️ Your Environment

OS:   Darwin 22.3.0 - darwin/x64
node: v16.19.0
yarn: 1.22.10
cli:  0.22.4 (installed)
backstage:  1.12.0

Dependencies:
  @backstage/app-defaults                          1.2.1
  @backstage/backend-app-api                       0.4.1
  @backstage/backend-common                        0.18.3
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.0
  @backstage/backend-tasks                         0.5.0
  @backstage/catalog-client                        1.4.0
  @backstage/catalog-model                         1.2.1
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.22.4
  @backstage/config-loader                         1.1.9
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.6.0
  @backstage/core-components                       0.12.5
  @backstage/core-plugin-api                       1.5.0
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.2
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.11
  @backstage/integration                           1.4.3
  @backstage/plugin-api-docs                       0.9.1
  @backstage/plugin-app-backend                    0.3.43
  @backstage/plugin-auth-backend                   0.18.1
  @backstage/plugin-auth-node                      0.2.12
  @backstage/plugin-catalog-backend-module-github  0.2.6
  @backstage/plugin-catalog-backend                1.8.0
  @backstage/plugin-catalog-common                 1.0.12
  @backstage/plugin-catalog-graph                  0.2.28
  @backstage/plugin-catalog-import                 0.9.6
  @backstage/plugin-catalog-node                   1.3.4
  @backstage/plugin-catalog-react                  1.4.0
  @backstage/plugin-catalog                        1.9.0
  @backstage/plugin-circleci                       0.3.16
  @backstage/plugin-events-node                    0.2.4
  @backstage/plugin-explore-backend                0.0.5
  @backstage/plugin-explore-common                 0.0.1
  @backstage/plugin-explore-react                  0.0.27
  @backstage/plugin-explore                        0.4.1
  @backstage/plugin-github-actions                 0.5.16
  @backstage/plugin-home                           0.4.32
  @backstage/plugin-org                            0.6.6
  @backstage/plugin-pagerduty                      0.5.9
  @backstage/plugin-permission-common              0.7.4
  @backstage/plugin-permission-node                0.7.6
  @backstage/plugin-permission-react               0.4.11
  @backstage/plugin-proxy-backend                  0.2.37
  @backstage/plugin-scaffolder-backend             1.12.0
  @backstage/plugin-scaffolder-common              1.2.6
  @backstage/plugin-scaffolder-node                0.1.1
  @backstage/plugin-scaffolder-react               1.2.0
  @backstage/plugin-scaffolder                     1.12.0
  @backstage/plugin-search-backend-module-pg       0.5.4
  @backstage/plugin-search-backend-node            1.1.4
  @backstage/plugin-search-backend                 1.2.4
  @backstage/plugin-search-common                  1.2.2
  @backstage/plugin-search-react                   1.5.1
  @backstage/plugin-search                         1.1.1
  @backstage/plugin-sonarqube-backend              0.1.8
  @backstage/plugin-sonarqube-react                0.1.4
  @backstage/plugin-sonarqube                      0.6.5
  @backstage/plugin-tech-radar                     0.6.2
  @backstage/plugin-techdocs-backend               1.6.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.11
  @backstage/plugin-techdocs-node                  1.6.0
  @backstage/plugin-techdocs-react                 1.1.4
  @backstage/plugin-techdocs                       1.6.0
  @backstage/plugin-todo-backend                   0.1.40
  @backstage/plugin-todo                           0.2.18
  @backstage/plugin-user-settings                  0.7.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.2.6
  @backstage/theme                                 0.2.18
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Seems like a good idea!

**Comment by FredericKayser** [comment]
Pull request is ready to review: https://github.com/backstage/backstage/pull/17173

**Comment by adamdmharvey** [comment]
Finally had a chance to test this locally; works like a charm!  Thanks @FredericKayser 👏🏻
