### ISSUE TITLE
localhost - Github authentication - Apps

### ISSUE THREAD

**Issue by DevOpsJazz** [backstage/backstage#17122]
### 📜 Description

HI

I have started Backstage on localhost, from this description: 
https://backstage.io/docs/getting-started/running-backstage-locally/

Also looked at:
https://github.com/backstage/backstage/tree/master/plugins/auth-backend#github

### 👍 Expected behavior

That I can create a repository from template

### 👎 Actual Behavior with Screenshots

I get this error, when tryin gto sign in under settings:

`{"error":{"name":"NotFoundError","message":"Auth provider registered for 'github' is misconfigured. This could mean the configs under auth.providers.github are missing or the environment variables used are not defined. Check the auth backend plugin logs when the backend starts to see more details.","stack":"NotFoundError: Auth provider registered for 'github' is misconfigured. This could mean the configs under auth.providers.github are missing or the environment variables used are not defined. Check the auth backend plugin logs when the backend starts to see more details.\n    at eval (webpack-internal:///../../plugins/auth-backend/src/service/router.ts:136:27)\n    at handleReturn (/home/<user>/code/backstage/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /home/<usre>/code/backstage/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at Layer.handle [as handle_request] (/home/<user>/code/backstage/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/<user>/code/backstage/node_modules/express/lib/router/index.js:328:13)\n    at /home/<user>/code/backstage/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/home/<user>/code/backstage/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/<user>/code/backstage/node_modules/express/lib/router/index.js:280:10)\n    at jsonParser (/home/<user>/code/backstage/node_modules/body-parser/lib/types/json.js:110:7)\n    at handleReturn (/home/<user>/code/backstage/node_modules/express-promise-router/lib/express-promise-router.js:24:23)"},"request":{"method":"GET","url":"/api/auth/github/start?scope=read%3Auser&origin=http%3A%2F%2Flocalhost%3A3000&flow=popup&env=development"},"response":{"statusCode":404}}`

### 👟 Reproduction steps

1. I have started- backstage with the followin commands:
```
export AUTH_GOOGLE_CLIENT_ID=<my id>
export AUTH_GOOGLE_CLIENT_SECRET=<my secret>
yarn dev
```
2. Settings / Authenticatation Providers / Github / "SIGN IN"

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Parsifal-M** [comment]
Hello! 👋 

Did you follow the docs on adding Auth with Github? You can find it here -> https://backstage.io/docs/auth/github/provider

**Comment by DevOpsJazz** [comment]
Thanks @Parsifal-M 

That got me to the next error. 
I was now able to login from settings using github.enterprise-domain.com
Note: We are running github on prem Enterprise.

When creating from template, I get "No token available for host: github.com, with owner <username>, and repo from-backstage".

And:
`[1](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-1)2023-03-29T08:21:32.000Z Beginning step Publish[2](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-2)2023-03-29T08:21:32.000Z InputError: No token available for host: github.com, with owner <user>, and repo from-backstage[3](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-3)    at getOctokitOptions (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts:63:15)[4](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-4)    at async Object.handler (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts:97:36)[5](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-5)    at async NunjucksWorkflowRunner.executeStep (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:196:13)[6](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-6)    at async NunjucksWorkflowRunner.execute (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:258:17)[7](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-7)    at async TaskWorker.runOneTask (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:88:33)[8](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-8)    at async run (/home/<user>/code/backstage/node_modules/p-queue/dist/index.js:163:29)`

It looks like it is trying github.com but we are on an Enterprise url. 

I did set "enterpriseInstanceUrl" even the doc. suggested not to set it.

Thanks again

**Comment by benjdlambert** [comment]
@DevOpsJazz this looks like a different issue. What template are you trying to run? It looks like the template is hard coded to create something at `github.com` and you don't have the  `integrations` config setup for that. Is that what you're trying to do? or do you want to create it at your enterprise domain?

**Comment by DevOpsJazz** [comment]
You are right, this is a new issue, that came up after the first one.. 

I will close and open a new: https://github.com/backstage/backstage/issues/17169
