### ISSUE TITLE
🐛 Bug Report: error:0200100D:system library:fopen:Permission denied node:internal/modules/cjs/loader:1021

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#17128]
### 📜 Description

I am able to run my container locally on macOS using port 7007 but when running it in a k8s environment i get this error:

```
node:internal/modules/cjs/loader:1021
Error: Cannot find module '/app/packages/backend'
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
at Function.Module._load (node:internal/modules/cjs/loader:866:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:22:47
```

I am using the app-backend plugin, serving a single container over port 7007 and require some extra ca certs so i placed the following in packages/backend/package.json:

` "certs": "NODE_EXTRA_CA_CERTS=./extra-ca-certs.pem node .",`

My Dockerfile is also the standard one and is sitting in packages/backend 

### 👍 Expected behavior

Container should run as expected in k8s env

### 👎 Actual Behavior with Screenshots

Warning: Ignoring extra certs from `./extra-ca-certs.pem`, load failed: error:0200100D:system library:fopen:Permission denied
node:internal/modules/cjs/loader:1021
Error: Cannot find module '/app/packages/backend'
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
at Function.Module._load (node:internal/modules/cjs/loader:866:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:22:47

### 👟 Reproduction steps

Warning: Ignoring extra certs from `./extra-ca-certs.pem`, load failed: error:0200100D:system library:fopen:Permission denied
node:internal/modules/cjs/loader:1021
Error: Cannot find module '/app/packages/backend'
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
at Function.Module._load (node:internal/modules/cjs/loader:866:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:22:47

### 🖥️ Your Environment

macOS with Node18.15.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Can you provide an example repo or production steps so that we can dig in a little deeper?

**Comment by regicsolutions** [comment]
I was able to resolve this issue by running yarn build first at the root and then yarn build-image
