### ISSUE TITLE
🚀 Feature: Improve links by adding external link icons

### ISSUE THREAD

**Issue by cstuart-sqsp** [backstage/backstage#17143]
### 🔖 Feature description

Links can be improved by adding **external link icons** to indicate when a link will open a new tab/page. Anytime that a link uses `<a target="_blank">...</a>`, an icon should appear with the link. This lets the reader know that the link won't open in the same tab or window, but rather in a new tab or window.

For example, this is what an external link icon (a square with an arrow) can look like: 
![Cross-references Google developer documentation style guide Google Developers 2023-03-28 at 3 41 17 PM](https://user-images.githubusercontent.com/96148783/228349319-6c1adfce-0285-4a64-8259-31c1c024e22f.jpg)

Here's another example (just a simple arrow):
![ext-link](https://user-images.githubusercontent.com/96148783/228352045-9037d895-0f69-4e2d-a78c-fa382115d4a8.jpg)

### 🎤 Context

It's a good accessibility practice to display an external link icon if a link opens a new tab/page. Some readers can get confused with the new windows or tabs if they are not expecting it.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
This seems like a good idea, we probably want to test this and and see how this works adding the external icon like the first example to the `BackstageLink` depending on how this looks we might want an opt-in behaviour.

**Comment by efenner-cambia** [comment]
Would this be resolved by https://github.com/backstage/backstage/pull/17679?
