### ISSUE TITLE
🚀 Feature: Document process.env.BUILD_INFO

### ISSUE THREAD

**Issue by nikolaik** [backstage/backstage#17153]
### 🔖 Feature description

Add documentation for `process.env.BUILD_INFO` which is search replaced by webpack DefinePlugin in frontend code. This is useful when you want to pass a sentry release name on to `Sentry.init()` when configuring Sentry for your backstage instance.

### 🎤 Context

Wanted to pass tag and/or commit SHA on to Sentry.init in our backstage instance, but using the app config system meant I head to wait with initialising sentry until after react mount.

### ✌️ Possible Implementation

Not sure where to add info about this, either add something to a deployment section, reading configuration section or write a tutorial under `contrib/docs/tutorials´ for the sentry use case.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
It's documented here https://backstage.io/docs/local-dev/cli-build-system#frontend-production 😁

**Comment by nikolaik** [comment]
Aha!
