### ISSUE TITLE
🐛 Bug Report: Search modal closes when clicking on text other than the link

### ISSUE THREAD

**Issue by dotboris** [backstage/backstage#17150]
### 📜 Description

When using the search modal (clicking search on the left sidebar), the modal will close when clicking on text other than the link in the modal. I find this pretty jarring as I would expect to be able to click inside that modal without it disappearing. I see two use cases for this:
- Users wanting to copy some of the text in there
- Users misclicking the result they were intending to open

I often get caught by the misclick because I intuitively assume that the whole search result row is going to lead me to my result. This would be easy to course correct but since the modal goes away, I have to reopen the search.

### 👍 Expected behavior

I would expect the modal to not close.

### 👎 Actual Behavior with Screenshots

The modal closes.

https://user-images.githubusercontent.com/1874242/228512309-07d496a6-e0ac-4220-a562-fbc13a255360.mp4

### 👟 Reproduction steps

1. Open https://demo.backstage.io/
2. Click on the search in the left sidebar
3. Click on the description of one of the search results

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Related #16137

**Comment by camilaibs** [comment]
The pull request that @benjdlambert mentioned got merged, and I was no longer able to reproduce the behavior. Do you mind trying to update the search modal package version and let us know if we can close the issue, @dotboris?

**Comment by dotboris** [comment]
@camilaibs I just updated to backstage v1.13.0 and the problem behaviour is gone. Feel free to close this issue.

**Comment by Rugvip** [comment]
Great!
