### ISSUE TITLE
🚀 Feature: Take into account number elements in a Table in the base theme

### ISSUE THREAD

**Issue by alethenorio** [backstage/backstage#17154]
### 🔖 Feature description

The Backstage base theme has a table component with a pagination toolbar at the bottom which allows you to choose how many elements should be displayed in a card with that table (from now on mentioned as page size). It seems the table layout does not care about the actual number of elements displayed in the table and sizes itself to whatever the page size is, which leads to a not so nice experience where the user can choose a page size of 100 for a table that only has 10 elements to display.

It would add to the user experience if the table size took into account the actual number of elements displayed in the table rather than the page size

### 🎤 Context

It improves the user experience of the product out of the box. This would prevent for example, the user seeing a table with 10 elements and changing the page size to 20 only to get a table which is mostly a white page because there are only 11 elements to display

### ✌️ Possible Implementation

Use the actual number of returned elements to be displayed rather than the page size to set the table size

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Can you find an example of a table in some other application or somewhere online that you can show us here with some idea on how you would like it to work? :pray:

**Comment by alethenorio** [comment]
Absolutely. The BigQuery UI is the one that comes to mind directly

See the 2 screenshots. Independent of the page size set at the bottom, the UI does not grow with the size of it but rather the number of rows shown (up to a limit of course)

![image](https://user-images.githubusercontent.com/2749771/228815355-4c36d0e7-8534-4453-aa47-a34ecda5344d.png)
![image](https://user-images.githubusercontent.com/2749771/228815479-0f1e08aa-eed1-4a8c-9bce-c58c0f2e7b27.png)

**Comment by alethenorio** [comment]
@Rugvip I marked that I could help with this issue so I could perform an attempt on a PR. I just need a pointer on where exactly in the code  this change would be and I should be able to figure my way out from there.

**Comment by efenner-cambia** [comment]
@Rugvip can you re-open?
