### ISSUE TITLE
🐛 Bug Report: Error attaching and running the plugin backend router

### ISSUE THREAD

**Issue by athifongoqa** [backstage/backstage#17165]
### 📜 Description

Followed the docs to create a new plugin backend. When trying to attach and run the plugin router, I receive the error: 
`error An unexpected error occurred: "https://registry.yarnpkg.com/@internal%2fplugin-flux-web-backend%5E0.1.0: Not found".`

### 👍 Expected behavior

The package should be found. 

### 👎 Actual Behavior with Screenshots

plugin-backend package.json:
<img width="1142" alt="Screenshot 2023-03-30 at 08 34 09" src="https://user-images.githubusercontent.com/59336133/228824023-4ba21242-96f0-458b-87ae-0128c9262132.png">

backend package.json:
<img width="1142" alt="Screenshot 2023-03-30 at 08 34 27" src="https://user-images.githubusercontent.com/59336133/228824035-e1c4c484-5e0a-4d8a-b6ca-a02c31bb6829.png">

error when trying to attach and run the plugin router:
<img width="1142" alt="Screenshot 2023-03-30 at 08 35 05" src="https://user-images.githubusercontent.com/59336133/228824046-de8c079e-17db-4c3a-b4d1-870d3a497e7c.png">

### 👟 Reproduction steps

Following [this doc](https://backstage.io/docs/plugins/backend-plugin)

1. Create new, bare-bones backend plugin package at root
2. Start backend plugin to test it is running in standalone mode
3. Try attach and run the plugin router

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Is the plugin in the `plugins` or `packages` directory? That's where the `yarn` workspaces are setup to look in when doing an install like this?

**Comment by athifongoqa** [comment]
the plugin is in the `plugins` folder, yes
