### ISSUE TITLE
Github Enterprise - "No token available for host: github.com, with owner , and repo from-backstage

### ISSUE THREAD

**Issue by DevOpsJazz** [backstage/backstage#17169]
### 📜 Description

Hi

I have started Backstage on localhost, from this description:
https://backstage.io/docs/getting-started/running-backstage-locally/

Running up against a Github Enterprise. I have added a provider from this doc:
https://backstage.io/docs/auth/github/provider

Backctage starts ok on localhost:3000
When creating from template, I get "No token available for host: github.com, with owner , and repo from-backstage".

I did set "enterpriseInstanceUrl" even the doc. suggested not to set it.

### 👍 Expected behavior

Create a repo on github enterprise.

### 👎 Actual Behavior with Screenshots

Error message in window:

`[1](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-1)2023-03-29T08:21:32.000Z Beginning step Publish[2](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-2)2023-03-29T08:21:32.000Z InputError: No token available for host: github.com, with owner <user>, and repo from-backstage[3](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-3)    at getOctokitOptions (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts:63:15)[4](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-4)    at async Object.handler (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts:97:36)[5](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-5)    at async NunjucksWorkflowRunner.executeStep (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:196:13)[6](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-6)    at async NunjucksWorkflowRunner.execute (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:258:17)[7](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-7)    at async TaskWorker.runOneTask (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:88:33)[8](http://localhost:3000/create/tasks/e5c57164-cc62-4a75-803b-07180a7e1aa1#line-8)    at async run (/home/<user>/code/backstage/node_modules/p-queue/dist/index.js:163:29)`

It looks like it is trying github.com but we are on an Enterprise url.

### 👟 Reproduction steps

1. Run installation:
https://backstage.io/docs/getting-started/running-backstage-locally/

2. Added provider:
https://backstage.io/docs/auth/github/provider

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by DevOpsJazz** [comment]
Thanks @Parsifal-M 

Good suggestion, I tought that using  GitHub Apps and setting `auth:providers:github` would do the trick - why do I need a token?

**Comment by Parsifal-M** [comment]
Hello! :wave: 

I can't say I have played around too much with the Github integration but I believe it because the tokens serve different purposes (i.e tokens have different claims/purposes). Still, I would not mind a second opinion on this maybe from @freben or @Rugvip :sweat_smile:

**Comment by benjdlambert** [comment]
It looks like the template is configure to be creating repositories at `github.com` instead of your own ghe instance. Can we see the template you're trying to use?

**Comment by kadel** [comment]
I have the same issue with GitHub Enterprise Server when using GitHub Apps.
When using `token`, everything works OK, but when I try configuration with `apps`, I get the same error.

I'm testing it with [`create-react-app-template`](https://github.com/backstage/software-templates/blob/main/scaffolder-templates/create-react-app/template.yaml). The only change I made is replacing `github.com` in `allowedHosts` with my GitHub Enterprise Server host.


Here is my configuration. Maybe something is missing there?
```yaml
integrations:
  github:
    - host: <redacted>
      apiBaseUrl: https://<redcated>/api/v3
      apps:
        - appId: 1
          clientId: <redacted>
          clientSecret: <redacted>
          webhookSecret: <redacted>
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            <redacted>
            -----END RSA PRIVATE KEY-----

```

The GH App has only permissions that are mentioned in https://backstage.io/docs/integrations/github/github-apps#app-permissions

**Comment by benjdlambert** [comment]
@kadel - when do you get this error? Is this when you run the templating itself? Can you grab the values from the `POST` request to the backend `/v1/tasks` I think it is? And paste the `values` that is passes through?

**Comment by kadel** [comment]
This is the payload for `POST` request to `http://localhost:7007/api/scaffolder/v2/tasks`
```json
{
    "templateRef": "template:default/create-react-app-template-my",
    "values": {
        "component_id": "rect-app",
        "owner": "group:default/acme-corp",
        "repoUrl": "<redacted>?owner=user&repo=react-app"
    },
    "secrets": {}
}
```

It happens during the publish step when running the template.

**Comment by kadel** [comment]
Yes it does.
<img width="740" alt="Screenshot 2023-05-15 at 15 46 03" src="https://github.com/backstage/backstage/assets/57206/ed21e870-2195-46eb-bb4a-46b54c1c5d8f">
I've tried creating a repo in users's namespace as well in the organization, and both with the same result.

**Comment by benjdlambert** [comment]
And the github app is definately installed into the org that you're creating it in, or under the user if you're trying to do it there? You should see it in this list for the org for instance?

https://GHE_BASE_URL/organizations/ORG_NAME/settings/installations

**Comment by kadel** [comment]
🤦 now I feel stupid; I did not install it. This fixed that error. Thank you @benjdlambert

**Comment by benjdlambert** [comment]
hehe no worries! glad it's all fixed! :pray:

**Comment by Rugvip** [comment]
🎉

**Comment by ddeath** [comment]
Hi, just wanted to mention that indeed setting up Github auth provider is not enough because scaffolder is ignoring it.

**You need to setup Github integration**: https://backstage.io/docs/integrations/github/github-apps
You can see it [here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/createBuiltinActions.ts#L145) that backstage is fetching credentials from integration only for builtin action:
