### ISSUE TITLE
🚀 Feature: Log response bodies from the SCM management APIs calls

### ISSUE THREAD

**Issue by artemptushkin** [backstage/backstage#17163]
### 🔖 Feature description

I'd like to see all the logs when BS calls SCM management API, Gitlab in my case

### 🎤 Context

I had to debug the source code to find why it returns 400, it would not be a need having logs in place

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
Hey :wave: thanks for the request! Is this everywhere in backstage? Or some place in particular?

**Comment by benjdlambert** [comment]
I think that we'd probably want to do this logging for all network requests that are using the `fetchApi` or what not. Might be pretty difficult in the backend until we start to use a `fetchApiRef` which I don't think we have yet. /cc @freben thoughts here?
