### ISSUE TITLE
💬 RFC: GraphQL Plugin 2.0

### ISSUE THREAD

**Issue by cowboyd** [backstage/backstage#17175]
### 🔖 Need

> 🏗️A robust concept implementation for this RFC is contained in #15519 

As a protocol for interacting with the Backstage backend, GraphQL is particularly well suited as a solution to some of the difficulties present in working with the `CatalogClient`. Because its developer experience is derived from a strong, statically type schema, and because of the unique character of Catalog data, it can provide not just a better way to exchange data between Backstage backends and frontends, but also a mechanism to catalyze learning about the shape and content of the system by the developers who use it.

### Graph as the medium

Despite using SQL as the primary loading and storage mechanism, the Backstage Catalog is, at is core, a graph database. It consists of a single flat table of uniquely identifiable nodes, each with a set of attributes. These nodes are then connected in arbitrary ways by *[relationships](https://backstage.io/docs/features/software-catalog/descriptor-format#common-to-all-kinds-relations)*, some of which are [pre-ordained by Backstage](https://backstage.io/docs/features/software-catalog/well-known-relations/), but many of which are [custom-defined as part of a company's unique operations model](https://backstage.io/docs/features/software-catalog/extending-the-model/). However, it is precisely because of the flexibility and adaptability of this model that working with it using the out-of-the-box [`CatalogClient`](https://backstage.io/docs/reference/catalog-client) can be awkward or even downright frustrating at times.

The Backstage catalog model is deliberately designed to be open to extension so that it can house whatever set of attributes a company might need to represent its entities. This means that the `spec` property of an Entity can contain anything (which is good), but at the cost of being awkward to work with because it is just a blob of un-typed JSON data over which each client must layer its own structure at the point of consumption. For example:

```jsx
let entity = await client.getEntityByRef("employee:cowboyd");

// let's say that "address" was changed to "location"
let employee.spec.address.country // TypeError: property 'country' does not exist on undefined
```

If the shape of the data changes, the client side types will just be straight up wrong, and as a result must be carefully kept in sync with the backend. Compare this with GraphQL where if we attempt to query a field that does not exist, it immediately triggers an error. This is because we cannot express the API without also expressing its shape.

```tsx
let employee = await client.query(`node(id: "employee:cowboyd") { address { country } }`);
// TypeError: field "address" does not exist on type "Employee"
```

Even better, we can use [GraphQL Codegen](https://the-guild.dev/graphql/codegen) to surface this category of error at _complile time_ which can yield enormous times savings for each dev cycle.

The story is similar when it comes to working with relationships. The flexibility of the catalog model in this regard is powerful in that any entity can be related to any other entity, and the type of relation that can join two entities together in this manner is unbounded. Once again however, [working](https://github.com/thefrontside/backstage/blob/master/plugins/catalog-react/src/utils/getEntityRelations.ts#L29-L48) with [these relationships](https://github.com/thefrontside/backstage/blob/master/plugins/catalog/src/components/AboutCard/AboutContent.tsx#L84-L97) can [be awkward](https://github.com/thefrontside/backstage/blob/master/plugins/catalog/src/components/SystemDiagramCard/SystemDiagramCard.tsx#L172-L265) using the `CatalogApi` by itself. 

Not only is it cumbersome, it can also be inefficient. This is because without a [bespoke batching mechanism](https://github.com/thefrontside/backstage/blob/master/plugins/catalog-graph/src/components/EntityRelationsGraph/useEntityStore.ts) at the point of consumption, the lowest activation energy solution is going to suffer from the N+1 problem.

By contrast, a GraphQL API has the possibility of both querying and traversing relationships as the natural expression of its schema. Rather than manually dereferencing each relationship:

```tsx
const [ownedByRelation] = getEntityRelations(entity, RELATION_OWNED_BY);
const owner = ownedByRelation ? await client.getEntityByRef(ownedByRelation.targetRef) ? null;
```

we can just access it directly.

```tsx
const owner = entity.ownedBy;
```

And, because resolution happens on the server, it can be responsible for properly batching entity loads according to the depth of the query, thereby removing [the burden](https://github.com/thefrontside/backstage/blob/master/plugins/catalog-graph/src/components/EntityRelationsGraph/useEntityStore.ts) from the shoulders of the developer.

In summary, the catalog is about as canonical a graph as you’re likely to find, and as such, a GraphQL API can represent it very effectively.

### Accelerate Learning about the Backstage model

Because of the complexity (and associated flexibility) of the entity type, and because of the high activation energy for working with relations between entities, The Backstage server API and the Backstage catalog model can be intimidating for new developers. It takes time to develop the necessary intuitions required to work with it effectively. A GraphQL API can supercharge this process and on-board developers to the concepts of the catalog in minutes and hours compared to what might have taken days and weeks by themselves. Because its schema is declared up front, a GraphQL API comes with an entire ecosystem of tools to support learning.

For starters, documentation can be included directly into schema source in the form of comments on types, fields, and queries rather than having to be maintained separately. 

```graphql
"""
An `Employee` is a special type of user that works at the company. All
`Employees` are `User`s, but not all `User`s are `Employee`s
"""
type Employee implements User {
  """
  The unique identifier for the employee profile on myportal.com
  """
  profileName: String!
}
```

This can be leveraged by any number of tools to automatically generate documentation sites for the API.

Beyond static documentation, there is also just the hands on experience you get out of the box with a proper playground like GraphiQL. Rather than *telling* developers about the API and the catalog model, we can let them feel it directly for themselves by placing it [directly into their hands.](https://graphql.org/swapi-graphql?query=%23%20Welcome%20to%20GraphiQL%0A%23%0A%23%20GraphiQL%20is%20an%20in-browser%20tool%20for%20writing%2C%20validating%2C%20and%0A%23%20testing%20GraphQL%20queries.%0A%23%0A%23%20Type%20queries%20into%20this%20side%20of%20the%20screen%2C%20and%20you%20will%20see%20intelligent%0A%23%20typeaheads%20aware%20of%20the%20current%20GraphQL%20type%20schema%20and%20live%20syntax%20and%0A%23%20validation%20errors%20highlighted%20within%20the%20text.%0A%23%0A%23%20GraphQL%20queries%20typically%20start%20with%20a%20%22%7B%22%20character.%20Lines%20that%20start%0A%23%20with%20a%20%23%20are%20ignored.%0A%23%0A%23%20An%20example%20GraphQL%20query%20might%20look%20like%3A%0A%23%0A%23%20%20%20%20%20%7B%0A%23%20%20%20%20%20%20%20field(arg%3A%20%22value%22)%20%7B%0A%23%20%20%20%20%20%20%20%20%20subField%0A%23%20%20%20%20%20%20%20%7D%0A%23%20%20%20%20%20%7D%0A%23%0A%23%20Keyboard%20shortcuts%3A%0A%23%0A%23%20%20%20Prettify%20query%3A%20%20Shift-Ctrl-P%20(or%20press%20the%20prettify%20button)%0A%23%0A%23%20%20Merge%20fragments%3A%20%20Shift-Ctrl-M%20(or%20press%20the%20merge%20button)%0A%23%0A%23%20%20%20%20%20%20%20%20Run%20Query%3A%20%20Ctrl-Enter%20(or%20press%20the%20play%20button)%0A%23%0A%23%20%20%20%20Auto%20Complete%3A%20%20Ctrl-Space%20(or%20just%20start%20typing)%0A%23%0A%0A) There is nothing like being able to execute requests, see their results, and use that create follow-on requests; all the while being supported by the learning aids of a full fledged IDE.

Another way in which the schema can be leveraged is to automatically generate TypeScript types to ensure now only that you consume it correcty, but also to provide field and type completions and documentation right inside your code editor. In fact, with tools like [GraphQL codegen](https://the-guild.dev/graphql/codegen), we can derive almost any kind of artifact from our GraphQL schema that you care to.

The point is that once we have a strongly typed schema around which to orient an API experience, we can bring the [full ecosystem of tooling](https://github.com/chentsulin/awesome-graphql) to bear on behalf of our users. 

### 🎉 Proposal

While there is currently a [GraphQL API that comes with Backstage](https://github.com/backstage/backstage/blob/master/plugins/catalog-graphql/src/schema.js), for the most part, it is a faithful re-creation of the standard REST API. As a result, it brings along with it the baggage outlined in the previous section. This is a proposal to *augment* that API with one that unlocks the graph-like nature of the Backstage catalog and is also easy to extend.

### Work with the data, not the envelope.

The entity format is great for representing the graph internally, but it imposes unnecessary ceremony when working with it from the outside. As an API consumer, nobody cares whether a description of a user’s role is in `metadata.description`, or if their name to display on a web page is inside `spec.profile.displayName`, they just want the data. By the same token, in order to work with related entities, nobody wants to have to go through the rigmarole of reading relations and assembling them by hand. Instead, they just want to access the related records directly. 

To make this happen, we define a set of [GraphQL directives](https://graphql.org/learn/queries/#directives) that allow us to directly map values from an entity to a GraphQL type and thereby generate the resolvers for it automatically. To map the fields like the ones above, we introduce a `@field` directive to pull data out of the envelope and give it directly to the developer.

```graphql
interface Entity {
  name: String! @field(at: "metadata.name")
  kind: String! @field(at: "kind")
  namespace: String! @field(at: "metadata.namespace", default: "default")
  title: String! @field(at: "metadata.title", default: "")
  description: String! @field(at: "metadata.description", default: "")
  tags: [String] @field(at: "metadata.tags")
  links: [EntityLink] @field(at: "metadata.links")
}
```

> 💡By default the `kind` of an entity is determined by the GraphQL type’s name, so in the preceding example, the entities to which this applies will be `kind: "User"` more on this mechanism later
> 

### Relationships

GraphQL provides the opportunity to navigate relationships in the same way as you would a simple data structure, and because the Backstage catalog has a normalized way of expressing relations between nodes, we can leverage it to automatically write the resolvers for related records. To do this, we introduce a `@relation` directive. Take this example snippet from the proposed catalog schema

```graphql
union Owner = User | Group

type System {
  owner: Owner! @relation(name: "ownedBy")
  domain: Domain @relation(name: "partOf")
}
```

This will tell the catalog loader to look up the relation of type “ownedBy” and use its target as the value of the `owner` property. 

```ts
system.owner.name //=> "team-a"
```

Because all relations are modeled as lists in the catalog backend, this will just use the first entry in the relations array of the given type. 

On the other hand, if the annotated field is of a list type, then the resulting relation will be an array corresponding to the targets.

```graphql
union Owner = User | Group
union Part = Component | Resource

type System {
  owner: Owner! @relation(name: "ownedBy")
  domain: Domain @relation(name: "partOf")
  parts: [Part] @relation(name: "hasPart")
}
```

This is nice, but in the case where you have polymorphic fields like `Part` which could be either a `Component` *or* a `Resource`, you may want to have a list of *just* the `Component`s, or *just* the `Resource`s. Instead of forcing every client to filter the list, we can provide a convenience to perform the filter on the server. The `@relation` directive will also take an optional “kind” attribute.

```graphql
union Owner = User | Group
union Part = Component | Resource

type System implements Entity {
  owner: Owner! @relation(name: "ownedBy")
  domain: Domain @relation(name: "partOf")
  parts: [Part] @relation(name: "hasPart")
  components: [Component] @relation(name: "hasPart", kind: "component")
  resources: [Component] @relation(name: "hasPart", kind: "resource")
}
```

### Loading and querying

The GraphQL API will depend on a “dataloader” architecture in order to find and present records no matter where they reside. This will allow for automatic and efficient batching of record loads from the catalog and other sources. It will also allow for types that are sourced from one location, such as the catalog, to be related to types sourced from other locations such as the task backend.

![GraphQL API uses sources to store and relate data by object id](https://user-images.githubusercontent.com/4205/228963886-519ef3c3-f1ec-41d9-adc1-4369e558d827.png)

GraphQL API uses sources to store and relate data by object id

To support this, every persistent type in the GraphQL API must implement the [Relay `Node` interface](https://relay.dev/docs/guides/graphql-server-specification/#object-identification). This is associates a unique identifier to each record, but from the perspective of the frontend, it is a completely opaque string. It is up to the GraphQL layer and the data sources themselves to negotiate the semantics of this id.

```graphql
interface Node {
  id: ID!
}
```

Under the hood, a Node’s `id` is a triple derived from the composite of its GraphQL typename, the name of the data source from which it is derived, and a special tag that is understood only by the source called a *ref*. For the included `catalog` source, the `ref` will just be the entity target ref. So for example, the id for the example `artist-lookup` service is comprised of:

1. **GraphQL typename**: `Service`
2. ****************Source name****************: `catalog`
3. ******ref******: `component:default/artist-lookup`

The GraphQL API can then look at the id of an object and route it to its source.

This allows us in the GraphQL layer to batch up ids that need to be resolved as they are encountered, and then send them to the loader in batches.

![Components of a GraphQL Node id](https://user-images.githubusercontent.com/4205/228963725-d3f55a38-eb75-4f72-ba45-367017fcec4d.png)

Components of a GraphQL Node id

A note on multiple sources:

> 💡Usually it is best to ingest records into the catalog and then use the GraphQL API provided by the catalog rather than define a new source. In our documentation and best practices, that is the course we should recommend. However there may be special circumstances may drive users to circumvent the catalog.
> 

### Expressing polymorphism

The GraphQL plugin will ship with an implementation of the Catalog which is arranged into a hierarchy of data types. At the very least, every type should be an `Entity`, but there are also abstract types like `Component`; all of which are entities, but of which there are many concrete subtypes.

![A partial diagram of the inheritance in the Backstage catalog model](https://user-images.githubusercontent.com/4205/228964127-fe8848ad-aace-4f89-865f-1060f5b9dcc3.png)

A partial diagram of the inheritance in the Backstage catalog model

To represent complex type hierarchies, we will use GraphQL interfaces. Specifically, concrete types are represented by GraphQL object types, and abstract types are represented by GraphQL interfaces. For example, in the above diagram, `Entity` and `Component` will be interfaces, but `Service`, `Website`, and `Resource` will be types.

To declare these relationships, we will use a custom `@implements` directive. This will automatically walk the chain of inheritance and copy over all fields and field mappings as well as add the actual interface declarations onto the time. For example, if we define the `Resource` type as:

```graphql
interface Node {
  id: ID!
}

interface Entity
   @implements(interface: "Node") {
   name: String! @field(at: "metadata.name")
   kind: String! @field(at: "kind")
   namespace: String! @field(at: "metadata.namespace", default: "default")
   apiVersion: String! @field(at: "apiVersion")
   title: String @field(at: "metadata.title")
   description: String @field(at: "metadata.description")
 }

type Resource 
   @implements(interface: "Entity") {
   system: System @relation(name: "partOf")
 }
```

Then after transforming the schema, we’ll output the *actual* type for `Resource`

```graphql
type Resource implements Entity & Node {
  id: ID!
  name: String!
  kind: String!
  namespace: String!
  apiVersion: String!
  title: String
  description: String
  system: System
}
```

There is one final piece to the polymorphism puzzle, and that is how do we know which concrete type a record is when all we have is the uniform envelope? The answer is that we use *discriminator fields*. Every interface that can be inherited from must say how we can tell its subtypes apart. With `Entity`, this is the `kind` field, and so we use the `@discriminates` directive to indicate that the kind will indicate the graphql type. Thus, we would more properly declare our `Entity` interface as.

```graphql
interface Entity
  @implements(interface: "Node")
  @discriminates(with: "kind") {
  
  #.... field declarations
}
```

This lets our generated resolvers know that any entity with a kind of “component” must either be of the type or interface “Component”. For multiple levels of inheritance, multiple discriminators must be specified. In the included catalog, `Component` is an interface, not a type, and its declaration starts with:

```graphql
interface Component
  @implements(interface: "Entity")
  @discriminates(with: "spec.type") {
}
```

Now, subtypes of `Component` such as `Service` must have *both* `kind = component` AND `spec.type = service`

### 〽️ Alternatives

1. **Do nothing** One option is to do nothing. There is already a REST API, so what do we need GraphQL for?
  -  we found using the catalog from external code and custom UI much more pleasant and robust to work with
  -  Developers we worked with were more able to quickly adapt their
3. **More manual schema management**. This proposal generates a _lot_ of schema for you. In fact, the output schema is quite a bit different than the input. One option is to do a lot more of the code maintenance by hand. 
  - We compromised by sticking to the constraint that at the very least the input schema must be valid SDL.                                                                                                       
1. **GraphQXL** A promising up and comer with schema expansion, this library came on to our radar recently. We may want to use it rather than custom directives.
  - after evaluating it, we decided that the potential exists to support both, especially since our input schema is always valid GraphQL.

### ❌ Risks

Beyond the benefits of using GraphQL for interacting with the Backstage catalog, there are some inherent challenges that also need to be addressed. Where as with a REST API you can just extend it by adding another endpoint, It is not always clear how to compose a GraphQL API from primitive components. Since Backstage is itself built as a host of a plugins, any  GraphQL solution must be able to answer to how to create a single coherent GraphQL schema from a multitude of constituent parts.

Also, the mode of thought required writing a REST server and a GraphQL server is substantially different, and so we need to minimize the impact of maintaining the server and writing resolvers.

- unclear how to handle non-query types such as mutations, and subscriptions, or if they can even be automatically generated in the same way with directives.
- heavy use of GQL directives which can seem odd to folks at first.
- is it a problem to have transparent ids such as `Service@catalog@default/component:artist-lookup` should we discourage folks from parsing them in any way by `base64` encoding, or storing them as base64 encoded JSON instead?

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by wKich** [comment]
@cowboyd That's awesome RFC. Great work 👍

**Comment by wKich** [comment]
@Rugvip @freben Could you please open this issue?

**Comment by benjdlambert** [comment]
@cowboyd @wKich what's the latest here, how's things going?

**Comment by wKich** [comment]
@benjdlambert hi, we've just released it from our own repository https://github.com/thefrontside/playhouse/tree/main/plugins/graphql-backend. We had a conversation with backstage maintainers and because the plugin adds some complexity and increase maintenance cost we decided to move it into our scope which more flexible.

**Comment by Rugvip** [comment]
Closing, the new plugin is at https://github.com/thefrontside/playhouse/tree/main/plugins/graphql-backend and our plugins have been deprecated and removed
