### ISSUE TITLE
🐛 Bug Report: TechDocs does not replace #{{values...}} in TechDocs rendering

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#17182]
### 📜 Description

When following the guide here: https://backstage.io/docs/features/techdocs/how-to-guides#how-to-add-the-documentation-setup-to-your-software-templates the software template documentation shows up nicely in the documentation listing but when going to the documentation itself, the values are not replaced anymore. See screenshots below.

### 👍 Expected behavior

The dynamic values are also replaced in the documentation page

### 👎 Actual Behavior with Screenshots

Documentation list view:
![image](https://user-images.githubusercontent.com/1178319/229123505-8b7afe4c-3f04-4c93-893c-d504deb3c53a.png)

The actual documentation page:
![image](https://user-images.githubusercontent.com/1178319/229123614-d6edf618-360b-4815-b30f-59e0d499bc4c.png)

### 👟 Reproduction steps

1. Create software template
2. Follow instructions here https://backstage.io/docs/features/techdocs/how-to-guides#how-to-add-the-documentation-setup-to-your-software-templates

### 🖥️ Your Environment

TechDocs builder, generator and publisher are done locally.

OS:   Darwin 22.3.0 - darwin/arm64
node: v16.19.0
yarn: 1.22.19
cli:  0.22.5 (installed)
backstage:  1.12.1

Dependencies:
  @backstage/app-defaults                                   1.2.1
  @backstage/backend-app-api                                0.4.1
  @backstage/backend-common                                 0.17.0, 0.18.3
  @backstage/backend-dev-utils                              0.1.1
  @backstage/backend-plugin-api                             0.5.0
  @backstage/backend-tasks                                  0.5.0
  @backstage/backend-test-utils                             0.1.35
  @backstage/catalog-client                                 1.4.0
  @backstage/catalog-model                                  1.2.1
  @backstage/cli-common                                     0.1.12
  @backstage/cli                                            0.22.5
  @backstage/config-loader                                  1.1.9
  @backstage/config                                         1.0.7
  @backstage/core-app-api                                   1.6.0
  @backstage/core-components                                0.12.5
  @backstage/core-plugin-api                                1.5.0
  @backstage/dev-utils                                      1.0.13
  @backstage/errors                                         1.1.5
  @backstage/eslint-plugin                                  0.1.2
  @backstage/integration-aws-node                           0.1.2
  @backstage/integration-react                              1.1.11
  @backstage/integration                                    1.4.3
  @backstage/plugin-api-docs                                0.9.1
  @backstage/plugin-app-backend                             0.3.43
  @backstage/plugin-auth-backend                            0.18.1
  @backstage/plugin-auth-node                               0.2.12
  @backstage/plugin-catalog-backend-module-aws              0.1.17
  @backstage/plugin-catalog-backend-module-bitbucket-server 0.1.8
  @backstage/plugin-catalog-backend-module-msgraph          0.5.2
  @backstage/plugin-catalog-backend                         1.8.0
  @backstage/plugin-catalog-common                          1.0.12
  @backstage/plugin-catalog-graph                           0.2.28
  @backstage/plugin-catalog-import                          0.9.6
  @backstage/plugin-catalog-node                            1.3.4
  @backstage/plugin-catalog-react                           1.4.0
  @backstage/plugin-catalog                                 1.9.0
  @backstage/plugin-github-actions                          0.5.16
  @backstage/plugin-jenkins-backend                         0.1.33
  @backstage/plugin-jenkins-common                          0.1.14
  @backstage/plugin-jenkins                                 0.7.15
  @backstage/plugin-kubernetes-common                       0.6.1
  @backstage/plugin-org                                     0.6.6
  @backstage/plugin-permission-backend                      0.5.18
  @backstage/plugin-permission-common                       0.7.4
  @backstage/plugin-permission-node                         0.7.6
  @backstage/plugin-permission-react                        0.4.11
  @backstage/plugin-proxy-backend                           0.2.37
  @backstage/plugin-scaffolder-backend-module-cookiecutter  0.2.18
  @backstage/plugin-scaffolder-backend                      1.12.0
  @backstage/plugin-scaffolder-common                       1.2.6
  @backstage/plugin-scaffolder-node                         0.1.1
  @backstage/plugin-scaffolder-react                        1.2.0
  @backstage/plugin-scaffolder                              1.12.0
  @backstage/plugin-search-backend-module-elasticsearch     1.1.4
  @backstage/plugin-search-backend-module-pg                0.5.4
  @backstage/plugin-search-backend-node                     1.1.4
  @backstage/plugin-search-backend                          1.2.4
  @backstage/plugin-search-common                           1.2.2
  @backstage/plugin-search-react                            1.5.1
  @backstage/plugin-search                                  1.1.1
  @backstage/plugin-sonarqube-backend                       0.1.8
  @backstage/plugin-sonarqube-react                         0.1.4
  @backstage/plugin-sonarqube                               0.6.5
  @backstage/plugin-techdocs-backend                        1.6.0
  @backstage/plugin-techdocs-module-addons-contrib          1.0.11
  @backstage/plugin-techdocs-node                           1.6.0
  @backstage/plugin-techdocs-react                          1.1.4
  @backstage/plugin-techdocs                                1.6.0
  @backstage/plugin-user-settings                           0.7.1
  @backstage/release-manifests                              0.0.9
  @backstage/test-utils                                     1.2.6
  @backstage/theme                                          0.2.18
  @backstage/types                                          1.0.2
  @backstage/version-bridge                                 1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by drodil** [comment]
Yeah that is the one with small modifications to owner etc. But basically the same template.

**Comment by jtreher** [comment]
@drodil This software template is supposed to be used as part of the scaffolder which should be creating a new repository or PR for you with that template filled in. If it's showing up in techdocs, I assume that your template process is not working correctly rather than it being anything related to techdocs because these should be replaced way before the techdocs engine goes about creating and publishing your docs.

**Comment by drodil** [comment]
@jtreher no, this is supposed to be the documentation of that template, not the documentation the template creates for some repository. And as it's working in the list view of the documentation, there's something wrong with the techdocs view not showing those values.

**Comment by awanlin** [comment]
Hi @drodil, TechDocs pulls those values from the `mkdocs.yml` file when it generates. On Discord you said those weren't being populated: https://discord.com/channels/687207715902193673/1091341655535267850/1092317347567636640 

TechDocs will only work with what it has and in this case it's not the culprit, but I'm happy to be proven wrong.

Could you post the Template's YAML as well as YAML for the `mkdocs.yml`, please? That could help us figure this out
