### ISSUE TITLE
🚀 Feature: Show TechDocs link in Scaffolder page and when running template

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#17183]
### 🔖 Feature description

If the template has an annotation for techdocs like described here https://backstage.io/docs/features/techdocs/how-to-guides/#how-to-add-the-documentation-setup-to-your-software-templates, the documentation link to /docs/{templateEntity} should be visible at least in the scaffolder page listing. It could also be shown somewhere when the template is selected and about to be run so users could check the docs before running it.

Wild idea would also be to put the documentation somewhere on the run page to be shown at the same time to give some context to what the template does.

### 🎤 Context

Users might not be aware of the documentation for each template so adding the links to the scaffolder page would help them get more information about the specific template and what it actually does.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by drodil** [comment]
Would be quite easy to add it at least for the TemplateCard here: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-react/src/next/components/TemplateCard/TemplateCard.tsx#L138

**Comment by benjdlambert** [comment]
This is implemented today, you just need to provide a route ref for `viewTechDocs`.

https://github.com/backstage/backstage/blob/391b7fbd28405d00b38769867b5cd4a7973ebcbf/plugins/scaffolder/src/next/TemplateListPage/TemplateListPage.tsx#L124-L141

You can do it by binding the routes in the `app` to the correct place and it will add a docs link to the `TemplateCard`

**Comment by drodil** [comment]
@benjdlambert great work! Did you also add information about this to the documentation somewhere? Didn't find the PR for this yet.

**Comment by benjdlambert** [comment]
Hmm I think that this has always been there, so I don't think we added anything special when moving it to next. I wonder if I can find the original PR that added it to see if there was any chat about documentation there. Otherwise happy to accept some docs on wiring this together! :pray:
