### ISSUE TITLE
🐛 Bug Report: Documentation is not available for this url https://backstage.io/link?scm-auth

### ISSUE THREAD

**Issue by riginoommen** [backstage/backstage#17197]
### 📜 Description

I tried to set the additional scopes for the gitlab and accessed the documentation it seems not available

### 👍 Expected behavior

Render the docs

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/3840244/229442179-f4b959f3-6791-4be5-b831-495e6ebc1e0d.png)

### 👟 Reproduction steps

Go to https://backstage.io/link?scm-auth

### 🖥️ Your Environment

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hmm woops, think we want to fix this. We had a page that used to do this all the client before. @jhaals can you point us in the right direction here so we can find the old links?

**Comment by freben** [comment]
Ah! Thanks for the ping. We'll look into it.
