### ISSUE TITLE
LICENSE: default-plugin uses API which is not licensed for commercial usage

### ISSUE THREAD

**Issue by flash-me** [backstage/backstage#17201]
### 📜 Description

The default-plugin generated by the CLI uses the API of https://randomuser.me: 

https://github.com/backstage/backstage/blob/master/packages/cli/templates/default-plugin/src/components/ExampleFetchComponent/ExampleFetchComponent.tsx.hbs#L79

- https://randomuser.me uses https://www.uifaces.co for generating data.
- https://www.uifaces.co/license in turn uses https://generated.photos/terms-and-conditions for generating photos
- https://generated.photos/terms-and-conditions is for non-commercial usage only (unless paid)

Why generating a plugin with CLI in an commercial context, this can be an issue.

### 👍 Expected behavior

The CLI should generate a plugin that is compatible with commercial environments.

### 👎 Actual Behavior with Screenshots

https://randomuser.me
![image](https://user-images.githubusercontent.com/5240450/229459055-7ddbc597-47b5-4d3f-8316-b677462753fd.png)

https://www.uifaces.co/licenses/
![image](https://user-images.githubusercontent.com/5240450/229459213-974cde08-0c5d-4642-99e4-235e01335e0f.png)

https://generated.photos/terms-and-conditions
![image](https://user-images.githubusercontent.com/5240450/229459297-58e304a8-c510-44bb-9428-4186a39dd91c.png)

### 👟 Reproduction steps

Generate a new plugin with the CLI:
```shell
yarn new --select plugin
```

### 📃 Provide the context for the Bug.

Backstage Plugin development

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Yep - let's remove this from the `ExampleFetchComponent` - let's replace with hardcoded list or some better example?

Also there's an occurrence here: https://github.com/backstage/backstage/blob/master/packages/cli/templates/default-plugin/src/components/ExampleFetchComponent/ExampleFetchComponent.tsx.hbs#L33

**Comment by flash-me** [comment]
> Yep - let's remove this from the `ExampleFetchComponent` - let's replace with hardcoded list or some better example?

I expect from an Example**Fetch**Component to provide an example for fetching data :) 

But good question regarding alternatives. Maybe https://reqres.in/ ?

cheers
flash ⚡

**Comment by jhaals** [comment]
I'm also opting for some hardcoded data to avoid this ever becoming a problem again. We can always sprinkle a bit of async in there as well and have a comment showing how you `fetch` and json parse from some example domain that does not exist.

**Comment by benjdlambert** [comment]
@ShadowWalker98 sure you can! Will assign to you! Be sure to [check out the contributing guide](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md) and good luck!

**Comment by ShadowWalker98** [comment]
Okay sure! If I need any help or have questions, I am to comment here, yes?

**Comment by npiyush97** [comment]
> > Yep - let's remove this from the `ExampleFetchComponent` - let's replace with hardcoded list or some better example?
> 
> I expect from an Example**Fetch**Component to provide an example for fetching data :)
> 
> But good question regarding alternatives. Maybe https://reqres.in/ ?
> 
> cheers flash zap

https://reqres.in/ is not free to use are backstage will to pay for fake data ?

**Comment by freben** [comment]
I think we just need images. Any random avatar service that DOES allow for this use (perhaps from open source projects specifically) should be good as a replacement

**Comment by npiyush97** [comment]
Hi @freben does it matter if users are static I curated a list of 20 users that should fix this issue.

**Comment by jhaals** [comment]
Human emoji from dicebear should be fine 👍

**Comment by npiyush97** [comment]
@jhaals  so it okay to put json in examplefetchcomponent ?
