### ISSUE TITLE
🚀 Feature: add the possibility to add a docs link to a Bazaar project

### ISSUE THREAD

**Issue by GustavoAdrianGimenez** [backstage/backstage#17245]
### 🔖 Feature description

It would be useful for us to add a `docs` link (optional) to a Bazaar project

### 🎤 Context

When we start a project, we write an RFC so all the engineer team can review it. Most of the times, we don't have the entity created in the early stages to link it in the project, so it would be great if we can have an optional docs link to fill it with a github issue link, google doc, etc.

### ✌️ Possible Implementation

I think it should be similar to the `Community` field that projects have today. We would be glad to submit a PR if you are agree with this feature!

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by lykkeaxlin** [comment]
It's been a while since me and Klara worked on the Bazaar, but any improvement to the Bazaar that makes it more useful is of course very welcomed 🥳

Maybe the people over at Axis, @GLundh?, knows where the Bazaar is headed and has an opinon on this feature?

**Comment by GLundh** [comment]
Sounds resonable to me! We wont have time to tackle this in the next few weeks. So a PR would be greatly appreciated. @lykkeaxlin : Thanks for bringing the feature request to my attention :+1:

**Comment by GustavoAdrianGimenez** [comment]
Great, we'll be working on it and will come back here when we have updates. Thank you!

**Comment by GustavoAdrianGimenez** [comment]
Here ir the [PR](https://github.com/backstage/backstage/pull/17293), thanks!
