### ISSUE TITLE
🚀 Feature: support extensible transformer in techdocs collator

### ISSUE THREAD

**Issue by alexef** [backstage/backstage#17244]
### 🔖 Feature description

Modify DefaultTechDocsCollatorFactory to allow a _techdocsTransformer_ (transform from `MkSearchIndexDoc` into a `TechDocsDocument`).

### 🎤 Context

When collating Catalog entities, one can bring their own entityTransformer and control the indexed fields. This is especially handy for us in order to index the tags.

However, for techdocs that is not possible at the moment, and rewriting the entire DefaultTechDocsCollatorFactory seems like a bad choice.

### ✌️ Possible Implementation

very similar to how DefaultCatalogCollatorFactory was done in: https://github.com/backstage/backstage/pull/15142

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by daniddelrio** [comment]
Agree, would definitely be nice to have this to allow more flexibility in configuring the TechDocs collator

**Comment by dfl-aeb** [comment]
Please reopen this issue because of the open pr: https://github.com/backstage/backstage/pull/20433
