### ISSUE TITLE
🐛 Bug Report: Entity persists an input error

### ISSUE THREAD

**Issue by miniengineer** [backstage/backstage#17254]
### 📜 Description

We have a provider which fetches information about users from Slack.

Yesterday we updated the Slack API token with insufficient permissions and it fetched almost all user data but **without email**.
Since email is used to generate UserEntity we started to see the following error which is correct 👍 

```
status:
  items:
    - type: backstage.io/catalog-processing
      level: error
      message: "InputError: Processor BuiltinKindsEntityProcessor threw an error while
        validating the entity user:default/minira; caused by TypeError:
        /spec/profile/email must NOT have fewer than 1 characters - limit: 1"
      error:
        name: InputError
        message: "Processor BuiltinKindsEntityProcessor threw an error while validating
          the entity user:default/minira; caused by TypeError:
          /spec/profile/email must NOT have fewer than 1 characters - limit: 1"
        cause:
          name: TypeError
          message: "/spec/profile/email must NOT have fewer than 1 characters - limit: 1"
          stack: >-
            TypeError: /spec/profile/email must NOT have fewer than 1 characters -
            limit: 1
                at throwAjvError (/app/node_modules/@backstage/catalog-model/dist/index.cjs.js:763:9)
                at /app/node_modules/@backstage/catalog-model/dist/index.cjs.js:860:11
```

However, yesterday we changed the Slack API token back to the one with all the necessary permissions

### 👍 Expected behavior

The error should have gone once the Slack provider fetched the user again and regenerated UserEntity. 
Currently it runs every 90 minutes.

### 👎 Actual Behavior with Screenshots

After a half day the error is still there, although we can confirm with EntityInspector and see the email with correct value in the entity YAML.

### 👟 Reproduction steps

1. Choose a Provider of your choice which needs a token to fetch and generate the entity
2. Give it a token with insufficient permissions
3. wait till it runs or trigger it manually
4. See the error
5. Provide the correct token
6. wait till it runs or trigger it manually
7. The error will still be there

### 📃 Provide the context for the Bug.

It seems like it persists that error although fetching with correct data happened already.
We just can't remove the error...

### 🖥️ Your Environment

```
OS:   Darwin 21.3.0 - darwin/x64
node: v18.7.0
yarn: 1.22.19
cli:  0.22.4 (installed)
backstage:  1.12.0

Dependencies:
  @backstage/app-defaults                               1.2.1
  @backstage/backend-app-api                            0.4.1
  @backstage/backend-common                             0.18.3
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.0
  @backstage/backend-tasks                              0.5.0
  @backstage/catalog-client                             1.4.0
  @backstage/catalog-model                              1.2.1
  @backstage/cli-common                                 0.1.12
  @backstage/cli                                        0.22.4
  @backstage/config-loader                              1.1.9
  @backstage/config                                     1.0.7
  @backstage/core-app-api                               1.6.0
  @backstage/core-components                            0.12.5
  @backstage/core-plugin-api                            1.5.0
  @backstage/dev-utils                                  1.0.13
  @backstage/errors                                     1.1.5
  @backstage/eslint-plugin                              0.1.2
  @backstage/integration-aws-node                       0.1.2
  @backstage/integration-react                          1.1.11
  @backstage/integration                                1.4.3
  @backstage/plugin-adr-common                          0.2.7
  @backstage/plugin-adr                                 0.4.1
  @backstage/plugin-api-docs                            0.9.1
  @backstage/plugin-app-backend                         0.3.43
  @backstage/plugin-auth-backend                        0.18.1
  @backstage/plugin-auth-node                           0.2.12
  @backstage/plugin-catalog-backend-module-aws          0.1.17
  @backstage/plugin-catalog-backend-module-github       0.2.6
  @backstage/plugin-catalog-backend                     1.8.0
  @backstage/plugin-catalog-common                      1.0.12
  @backstage/plugin-catalog-graph                       0.2.28
  @backstage/plugin-catalog-node                        1.3.4
  @backstage/plugin-catalog-react                       1.4.0
  @backstage/plugin-catalog                             1.9.0
  @backstage/plugin-events-node                         0.2.4
  @backstage/plugin-fossa                               0.2.48
  @backstage/plugin-github-actions                      0.5.16
  @backstage/plugin-github-pull-requests-board          0.1.10
  @backstage/plugin-home                                0.4.32
  @backstage/plugin-kubernetes-common                   0.6.1
  @backstage/plugin-org                                 0.6.6
  @backstage/plugin-permission-backend                  0.5.18
  @backstage/plugin-permission-common                   0.7.4
  @backstage/plugin-permission-node                     0.7.6
  @backstage/plugin-permission-react                    0.4.11
  @backstage/plugin-proxy-backend                       0.2.37
  @backstage/plugin-scaffolder-backend                  1.12.0
  @backstage/plugin-scaffolder-common                   1.2.6
  @backstage/plugin-scaffolder-node                     0.1.1
  @backstage/plugin-scaffolder-react                    1.2.0
  @backstage/plugin-scaffolder                          1.12.0
  @backstage/plugin-search-backend-node                 1.1.4
  @backstage/plugin-search-backend                      1.2.4
  @backstage/plugin-search-common                       1.2.2
  @backstage/plugin-search-react                        1.5.1
  @backstage/plugin-search                              1.1.1
  @backstage/plugin-sonarqube-backend                   0.1.8
  @backstage/plugin-sonarqube-react                     0.1.4
  @backstage/plugin-sonarqube                           0.6.5
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.27
  @backstage/plugin-tech-insights-backend               0.5.9
  @backstage/plugin-tech-insights-common                0.2.10
  @backstage/plugin-tech-insights-node                  0.4.1
  @backstage/plugin-tech-insights                       0.3.8
  @backstage/plugin-user-settings                       0.7.1
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.2.6
  @backstage/theme                                      0.2.18
  @backstage/types                                      1.0.2
  @backstage/version-bridge                             1.0.3
✨  Done in 1.87s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by miniengineer** [comment]
Btw, the issue somehow resolved after approximately 24 hours

We just refreshed and the error has been removed.
Does it have to do anything with the `refresh_table` ?

Probably it's important to mention that we saw the error only after ~24 hours of using the Slack token with insufficient permissions.

So time to see the error and time to resolve was approximately the same.

**Comment by jhaals** [comment]
Hi!
It does sound like the provider did emit entities incomplete entities with empty strings when it was not able to fetch the email, in that case it might be good to add some extra validation before emitting the entity. Perhaps the reason for it taking so long could be that the location being read was the same and remained in the processor cache? Would really need some code or reproduction steps using the open source providers/processors to help further :)

**Comment by miniengineer** [comment]
Thank you very much @jhaals 

yup, we're going to open source the SlackProvider, so hopefully it will be easier to reproduce. Will mention here once we do it 🙏 

> Perhaps the reason for it taking so long could be that the location being read was the same and remained in the processor cache?

Probably as we never changed / updated the location 🤔 
Is it something that is suggested to do if there's a need to "refresh" generated and processed entities? 👀

**Comment by miniengineer** [comment]
btw 

this will be our first time open-sourcing anything for backstage.
Is there any guide that we can follow to create a story for this? As it seems to be a lot of work to get this accepted by backstage 👀 

right now it's just one file in our custom plugin.

thank you 🙏

**Comment by jhaals** [comment]
> Probably as we never changed / updated the location 🤔 Is it something that is suggested to do if there's a need to "refresh" generated and processed entities? 👀



> btw
> 
> this will be our first time open-sourcing anything for backstage. Is there any guide that we can follow to create a story for this? As it seems to be a lot of work to get this accepted by backstage 👀
> 
> right now it's just one file in our custom plugin.
> 
> thank you 🙏

It's likely a new package as you probably already created internally. The main ways of contributing is documented in our [Contributing.md](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md) file, however there's is nothing stopping you starting with hosting the package in your own repository and still publishing it but there's a bit of overhead to configure your CI/CD and npm publishing. The upside is that you get more flexibility and can release more often.

**Comment by jhaals** [comment]
> Thank you very much @jhaals
> 
> yup, we're planning to open source the SlackProvider, so hopefully it will be easier to reproduce. Will mention here once we do it 🙏
> 
> > Perhaps the reason for it taking so long could be that the location being read was the same and remained in the processor cache?
> 
> Probably as we never changed / updated the location 🤔 Is it something that is suggested to do if there's a need to "refresh" generated and processed entities? 👀

Caching is entirely optional in a processor if you have created a processor that does not use caching it will re-fetch every time based on your processing interval. It can be beneficial to store some reference like an Etag if available in the API to potentially reduce the risk of getting rate limited if etag-calls does not count towards the quota for example. You can read more about it here  https://backstage.io/docs/features/software-catalog/external-integrations/#processors-and-the-ingestion-loop
I'd say that documentation is a very good read when creating your own processor or entity provider.
