### ISSUE TITLE
🐛 Bug Report: Project specification is required on Azure DevOps integration

### ISSUE THREAD

**Issue by EnmanuelParedes** [backstage/backstage#17251]
### 📜 Description

When configuring [Azure DevOps Discovery ](https://backstage.io/docs/integrations/azure/discovery) the 'project' variable is set as required when, by documentation, it is optional. 

![image](https://user-images.githubusercontent.com/78808997/229883443-81e8a25f-b68a-4ab6-b624-5e72dbd05c59.png)

On the _plugin-catalog-backend-module-azure_ the variable is being read as required:

![image](https://user-images.githubusercontent.com/78808997/229883822-24d77fcb-c962-431b-8671-dc64495e99ca.png)

But when calling the API Endpoint has the wildcard (but it would never be in the first place)

![image](https://user-images.githubusercontent.com/78808997/229884020-71248759-39a2-45ec-aee2-62575d03b0b9.png)

The error:

![image](https://user-images.githubusercontent.com/78808997/229884191-c3328c08-f262-4d43-b659-d1cd399bc22e.png)

I refer to index.js of the plugin instead of the source, so sorry about that. 

The plugin version: 0.1.14

### 👍 Expected behavior

It should let me use a wild card at the project property

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/78808997/229884191-c3328c08-f262-4d43-b659-d1cd399bc22e.png)

### 👟 Reproduction steps

Let the project variable empty and try to execute it

### 📃 Provide the context for the Bug.

N/A

### 🖥️ Your Environment

OS:   Windows_NT 10.0.19045 - win32/x64
node: v16.20.0
yarn: 1.22.19
cli:  0.22.5 (installed)
backstage:  1.12.0

Dependencies:
  @backstage/app-defaults                          1.2.1
  @backstage/backend-app-api                       0.4.1
  @backstage/backend-common                        0.18.3
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.0
  @backstage/backend-tasks                         0.5.0
  @backstage/catalog-client                        1.4.0
  @backstage/catalog-model                         1.2.1
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.22.5
  @backstage/config-loader                         1.1.9
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.6.0
  @backstage/core-components                       0.12.5
  @backstage/core-plugin-api                       1.5.0
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.2
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.11
  @backstage/integration                           1.4.3
  @backstage/plugin-api-docs                       0.9.1
  @backstage/plugin-app-backend                    0.3.43
  @backstage/plugin-auth-backend                   0.18.1
  @backstage/plugin-auth-node                      0.2.12
  @backstage/plugin-catalog-backend-module-azure   0.1.14
  @backstage/plugin-catalog-backend-module-msgraph 0.5.2
  @backstage/plugin-catalog-backend                1.8.0
  @backstage/plugin-catalog-common                 1.0.12
  @backstage/plugin-catalog-graph                  0.2.28
  @backstage/plugin-catalog-import                 0.9.6
  @backstage/plugin-catalog-node                   1.3.4
  @backstage/plugin-catalog-react                  1.4.0
  @backstage/plugin-catalog                        1.9.0
  @backstage/plugin-github-actions                 0.5.16
  @backstage/plugin-org                            0.6.6
  @backstage/plugin-permission-common              0.7.4
  @backstage/plugin-permission-node                0.7.6
  @backstage/plugin-permission-react               0.4.11
  @backstage/plugin-proxy-backend                  0.2.37
  @backstage/plugin-scaffolder-backend             1.12.0
  @backstage/plugin-scaffolder-common              1.2.6
  @backstage/plugin-scaffolder-node                0.1.1
  @backstage/plugin-scaffolder-react               1.2.0
  @backstage/plugin-scaffolder                     1.12.0
  @backstage/plugin-search-backend-module-pg       0.5.4
  @backstage/plugin-search-backend-node            1.1.4
  @backstage/plugin-search-backend                 1.2.4
  @backstage/plugin-search-common                  1.2.2
  @backstage/plugin-search-react                   1.5.1
  @backstage/plugin-search                         1.1.1
  @backstage/plugin-tech-radar                     0.6.2
  @backstage/plugin-techdocs-backend               1.6.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.11
  @backstage/plugin-techdocs-node                  1.6.0
  @backstage/plugin-techdocs-react                 1.1.4
  @backstage/plugin-techdocs                       1.6.0
  @backstage/plugin-user-settings                  0.7.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.2.6
  @backstage/theme                                 0.2.18
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by EnmanuelParedes** [comment]
If I set the parameter with the wildcard in the _yml_ file:

![image](https://user-images.githubusercontent.com/78808997/229886390-ba43d502-f577-441a-bafc-1493a8349e9d.png)

Is working as expected, but I don't think this is the expected behavior for an optional param. If I'm wrong just close the issue.

**Comment by awanlin** [comment]
Hi @EnmanuelParedes, thanks for the detailed issue. I think you are correct that something is not right here - either the code should be updated or the documentation should be changed to match that this is actually required. We should keep this open so that someone can do that.

I totally missed this when I did the testing on our on-prem Azure DevOps Server instance when PR #14847 was being worked on, must not have tried not setting the `project` and just used the wildcard :(

**Comment by awanlin** [comment]
@MarcBruins @Jtreher @cal5barton are you using this feature? Do you have any opinions on how this should be handled?

**Comment by cal5barton** [comment]
Yes we are actively using this feature. I would expect it to be a wildcard/all projects if not supplied.

**Comment by jpitapeva** [comment]
Hi, i am using with devops 2020 on premise it's working perfect this way

providers:
    azureDevOps:
      BDEstruturaConsignado:
        host: xxxxxxxx
        organization: xxxxx
        project: '*'
        repository: '*'
        path: /catalog/catalog-*info.yaml

**Comment by jtreher** [comment]
It looks like we are also specifying the '*' even though it is "optional" in the docs. I think this likely came up as a misunderstanding from discussion on the PR. 

Is the solution to just change it to `config.getOptionalString("project")` or just change the docs? I'm fine with either solution. I suppose explicitly requiring people to put in a * forces them to consider what they are doing rather than just omitting it until they learn later because not everyone reads the docs carefully on initial usage (eyes self).

**Comment by jpitapeva** [comment]
I understand, for me the ideal is change the docs, is very important your discussion ;)

**Comment by awanlin** [comment]
Alright, seems like updating the docs is the way forward, will one of you do that? If not I can. Also, this doesn't me we can't change the code to make this truly optional down the road if we really wanted to

**Comment by jpitapeva** [comment]
@awanlin and @jtreher, can you review please?

https://github.com/backstage/backstage/pull/17322

**Comment by EnmanuelParedes** [comment]
I'm almost sure this is not related, but in my configuration, I have a list of allowed kinds to be searched:

![image](https://user-images.githubusercontent.com/78808997/231277625-f4f98224-8c67-4ab6-99d3-7d481a42507c.png)

But when is founded the app throws a warning like this:

```
catalog warn Entity resource:default/enlinea-db at url:https://dev.azure.com/<path>?path=/catalog-info.yaml, originated at url:https://dev.azure.com/grupouniversal/<path>?path=/catalog-info.yaml, is not of an allowed kind for that location type=plugin entity=location:default/generated-dffd2a899a77f2d7a6b9368ff9d3d0a93b91315c location=url:https://dev.azure.com/<path>?path=/catalog-info.yaml
```
The global rule is not being used for the provider? I need to use the [alternate processor](https://backstage.io/docs/integrations/azure/discovery#alternative-processor) for this?  If I add a kind:component is being added successfully like it is the only valid

**Comment by jtreher** [comment]
Yep, I think this can be closed. Great job!
