### ISSUE TITLE
🐛 Bug Report: PgSearchEngineIndexer does not reliably release database connections when errors occur earlier in the pipeline

### ISSUE THREAD

**Issue by mtlewis** [backstage/backstage#17278]
### 📜 Description

The `PgSearchEngineIndexer` uses one transaction for each indexing run. This transaction is committed when finalizing the index operation, and has various calls to `rollback` when errors occur within the indexer.

However, it appears that when _other parts_ of the indexing pipeline throw errors, none of the error handling code in the indexer is hit, and so the transaction is not committed or rolled back.

This means that over time, the search backend continues to accumulate database connections, until no more are available.

### 👍 Expected behavior

The indexer (and/or the indexing system itself) should be updated to guarantee that `finalize` (or another hook) is called whenever indexing stops for any reason, so that the connection can be freed. In particular, when other parts of the indexing pipeline throw errors, it should not cause the indexer to leak connections.

### 👎 Actual Behavior with Screenshots

When errors occur in (say) decorators, as long as the indexer has been initialized, the connection is not freed, and the number of connections held by the search backend increases until no more are available, at which time messages like this start to appear:

```
2023-04-06T12:09:05.663Z backstage warn Database keepalive failed for plugin search, KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

Note: to check the number of active connections, you can use the following query:

```SQL
SELECT * FROM pg_stat_activity WHERE datname='backstage_plugin_search';
```

### 👟 Reproduction steps

The [branch `search-module-pg-connection-repro`](https://github.com/backstage/backstage/compare/search-module-pg-connection-repro) contains a reproduction of the issue. See the commit messages in the branch for specific details of the changes made to reproduce.

1. Check out `search-module-pg-connection-repro`
2. Configure a postgres database
3. Start the backend

Once the backend is running, note the periodic errors logged to the console, and watch the number of connections increase by using the DB query above.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by emmaindal** [comment]
Hello @mtlewis thanks for opening this issue with great details. As documented here https://backstage.io/docs/features/search/#supported and announced here https://backstage.io/blog/2022/07/19/releasing-backstage-search-1.0/ the postgres engine is community supported and nothing we from the @backstage/discoverability-maintainers actively work on. So adding a "help wanted" label to this issue as we would love to get help fixing it.

**Comment by mtlewis** [comment]
Cool, thanks for pointing it out @emmaindal! It's actually a little debatable whether this is purely a PgSearchEngine problem. Right now, the PgSearchEngine has no opportunity to release its connections, because finalize is not being called by the indexer, so it seems likely that we'll need some kind of central change to fix the issue. If for example it made sense for the search system to be updated to reliably call `finalize` when errors occur anywhere in the pipeline, this would resolve the issue without changes to `PgSearchEngine`. I'm not sure whether that's the right fix though!

**Comment by emmaindal** [comment]
Got it, thanks for clarifying that @mtlewis @iamEAP! We will look into if we can reproduce on the Elastic search engine as well and get back to you!

**Comment by emmaindal** [comment]
A couple of clarifying questions. This issue mentions the problem of not releasing database connections when errors occur? I'm just trying to understand the impact on other engines here because the pg search engine is the only one using the pg database to index the documents to, while other search engines just use it for the task scheduling. So is this a scheduling problem? then I can see its affecting more, or a indexing problem?

The reason why I ask because I were looking into this and I'm able to see a large number of connection (compared to other plugin specific databases) for search using your sql query in the description. Which gives me a count of the following:

```
postgres=# SELECT count(*) FROM pg_stat_activity WHERE datname='backstage_plugin_catalog';
 count
-------
     6
(1 row)

postgres=# SELECT count(*) FROM pg_stat_activity WHERE datname='backstage_plugin_techdocs';
 count
-------
     0
(1 row)

postgres=# SELECT count(*) FROM pg_stat_activity WHERE datname='backstage_plugin_scaffolder';
 count
-------
     3
(1 row)

postgres=# SELECT count(*) FROM pg_stat_activity WHERE datname='backstage_plugin_search';
 count
-------
    12
(1 row)

```

but when I configure search to use the Elasticsearch engine instead I get the following counts

```
postgres=# SELECT count(*) FROM pg_stat_activity WHERE datname='backstage_plugin_catalog';
 count
-------
     6
(1 row)

postgres=# SELECT count(*) FROM pg_stat_activity WHERE datname='backstage_plugin_techdocs';
 count
-------
     0
(1 row)

postgres=# SELECT count(*) FROM pg_stat_activity WHERE datname='backstage_plugin_scaffolder';
 count
-------
     3
(1 row)

postgres=# SELECT count(*) FROM pg_stat_activity WHERE datname='backstage_plugin_search';
 count
-------
     2
(1 row)
```

which gives us some sort of indicator that it at least doesn't fill up with connections when using elastic.  

It could of course be other underlying issues that we should look closer into but this was the first step I took.

**Comment by iamEAP** [comment]
> _I'm just trying to understand the impact on other engines here because the pg search engine is the only one using the pg database to index the documents to, while other search engines just use it for the task scheduling. So is this a scheduling problem? then I can see its affecting more, or a indexing problem?_

Oh yeah, great questions.  This happens to express itself in the PG search engine as an ever-increasing number of DB connections, but the overall (potential) problem is just inconsistent or incomplete teardown/cleanup handling, especially in the case of errors in other parts of the indexing pipeline.

So if it affects Elastic, it might look more like orphaned indices. If it affects Lunr, it might look like a memory leak or weird index states(?).  It's also possible there are already different mitigations in place for these engines (and if so, it _could_ be worth unifying the logic of how to handle those cases somewhere in `search-node`, rather than in each engine).

**Comment by emmaindal** [comment]
Got it. So reading this issue, the bug you have reported causes the following problem 
`... over time, the search backend continues to accumulate database connections, until no more are available.` 

and the error 

```
2023-04-06T12:09:05.663Z backstage warn Database keepalive failed for plugin search, KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

appears. 

But we know at this point that the above problem and errors you see will not happen for other search engines. 

So my recommendation to resolve the issue reported is to get it fixed for the postgres search engine, where we actually know the problem has been identified. 

And if we see bug reports related to the same problem for other search engines as well - we can streamline the different engine specific solutions to a platform wide solution for this. Which we in @backstage/discoverability-maintainers can look into in parallel. 

If you have examples already of Elasticsearch and/or Lunr issues related to this, please share them in this issue as well! Looks like for example https://github.com/backstage/backstage/pull/14957 is related and already looked at for elastic - which you might be able to provide more context around as you worked on it @iamEAP?

**Comment by iamEAP** [comment]
> _So my recommendation to resolve the issue reported is to get it fixed for the postgres search engine, where we actually know the problem has been identified._

Makes sense to me, @emmaindal!  PR for that is now open here: https://github.com/backstage/backstage/pull/17292

I opened up a separate feature idea that captures thoughts from this thread for your consideration here: https://github.com/backstage/backstage/issues/17291. I added todos in the PR that point to that issue.
