### ISSUE TITLE
FetchUrlReader does not implement readTree while using plugin-scaffolder-backend-module-confluence-to-markdown

### ISSUE THREAD

**Issue by db-cataloge-db** [backstage/backstage#17274]
### 📜 Description

I have tried to use the url for both bitbucket and github to fetch the mkdocs.yaml as part of the scaffolder action as mentioned under https://github.com/backstage/backstage/tree/v1.13.0-next.1/plugins/scaffolder-backend-module-confluence-to-markdown, they return the following error 

2023-04-06T00:29:52.072Z Error: FetchUrlReader does not implement readTree[5](http://localhost:3000/create/tasks/e4ec119e-5752-4455-b20d-f44a97850f11#line-5)    at _FetchUrlReader.readTree (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\backend-common\dist\index.cjs.js:3142:11)[6](http://localhost:3000/create/tasks/e4ec119e-5752-4455-b20d-f44a97850f11#line-6)    at UrlReaderPredicateMux.readTree (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\backend-common\dist\index.cjs.js:3211:29)[7](http://localhost:3000/create/tasks/e4ec119e-5752-4455-b20d-f44a97850f11#line-7)    at fetchContents (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\plugin-scaffolder-backend-module-confluence-to-markdown\node_modules\@backstage\plugin-scaffolder-backend\dist\cjs\ScaffolderEntitiesProcessor-21c74c4d.cjs.js:564:30)[8](http://localhost:3000/create/tasks/e4ec119e-5752-4455-b20d-f44a97850f11#line-8)    at Object.handler (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\plugin-scaffolder-backend-module-confluence-to-markdown\node_modules\@backstage\plugin-scaffolder-backend\dist\cjs\ScaffolderEntitiesProcessor-21c74c4d.cjs.js:640:13)[9](http://localhost:3000/create/tasks/e4ec119e-5752-4455-b20d-f44a97850f11#line-9)    at Object.handler (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\plugin-scaffolder-backend-module-confluence-to-markdown\dist\index.cjs.js:131:30)[10](http://localhost:3000/create/tasks/e4ec119e-5752-4455-b20d-f44a97850f11#line-10)    at NunjucksWorkflowRunner.execute (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\plugin-scaffolder-backend\dist\index.cjs.js:4831:24)[11](http://localhost:3000/create/tasks/e4ec119e-5752-4455-b20d-f44a97850f11#line-11)    at runMicrotasks (<anonymous>)[12](http://localhost:3000/create/tasks/e4ec119e-5752-4455-b20d-f44a97850f11#line-12)    at processTicksAndRejections (node:internal/process/task_queues:96:5)[13](http://localhost:3000/create/tasks/e4ec119e-5752-4455-b20d-f44a97850f11#line-13)    at async TaskWorker.runOneTask (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\@backstage\plugin-scaffolder-backend\dist\index.cjs.js:5042:26)[14](http://localhost:3000/create/tasks/e4ec119e-5752-4455-b20d-f44a97850f11#line-14)    at async run (D:\dev\GIT_REPOSITORY_GA\backstage-app\node_modules\p-queue\dist\index.js:163:29)

### 👍 Expected behavior

It should retrieve the file.

### 👎 Actual Behavior with Screenshots

It actually should retrieve the mkdocs.yaml file

### 👟 Reproduction steps

I have tried to use the url for both bitbucket and github to fetch the mkdocs.yaml as part of the scaffolder action as mentioned under https://github.com/backstage/backstage/tree/v1.13.0-next.1/plugins/scaffolder-backend-module-confluence-to-markdown, they return the following error 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
@db-cataloge-db can you share your Backstage version, please? The output from: `yarn backstage-cli info` would be helpful and it includes this

**Comment by db-cataloge-db** [comment]
OS:   Windows_NT 10.0.19044 - win32/x64
node: v16.14.0
yarn: 1.22.19
cli:  0.22.3 (installed)
backstage:  N/A

Dependencies:
  @backstage/app-defaults                                            1.2.0
  @backstage/backend-app-api                                         0.4.0, 0.4.2-next.2
  @backstage/backend-common                                          0.18.2, 0.18.4-next.2
  @backstage/backend-dev-utils                                       0.1.0, 0.1.1
  @backstage/backend-plugin-api                                      0.4.0, 0.5.1-next.2
  @backstage/backend-tasks                                           0.4.3, 0.5.1-next.2
  @backstage/catalog-client                                          1.3.1, 1.4.1-next.0
  @backstage/catalog-model                                           1.1.3, 1.2.0, 1.2.1
  @backstage/cli-common                                              0.1.11, 0.1.12
  @backstage/cli                                                     0.22.3
  @backstage/codemods                                                0.1.43
  @backstage/config-loader                                           1.1.8, 1.1.9
  @backstage/config                                                  1.0.4, 1.0.6, 1.0.7
  @backstage/core-app-api                                            1.5.0
  @backstage/core-components                                         0.12.0, 0.12.4, 0.9.5
  @backstage/core-plugin-api                                         1.1.0, 1.4.0
  @backstage/create-app                                              0.4.37
  @backstage/dev-utils                                               1.0.12
  @backstage/errors                                                  1.1.3, 1.1.4, 1.1.5
  @backstage/eslint-plugin                                           0.1.1
  @backstage/integration-aws-node                                    0.1.1, 0.1.2
  @backstage/integration-react                                       1.1.10
  @backstage/integration                                             1.4.0, 1.4.2, 1.4.4-next.0
  @backstage/plugin-app-backend                                      0.3.42
  @backstage/plugin-auth-node                                        0.2.11, 0.2.13-next.2
  @backstage/plugin-badges-backend                                   0.1.36
  @backstage/plugin-badges                                           0.2.39
  @backstage/plugin-catalog-backend-module-github                    0.2.5
  @backstage/plugin-catalog-backend                                  1.7.2, 1.8.1-next.2
  @backstage/plugin-catalog-common                                   1.0.11, 1.0.13-next.0
  @backstage/plugin-catalog-import                                   0.9.5
  @backstage/plugin-catalog-node                                     1.3.3, 1.3.5-next.2
  @backstage/plugin-catalog-react                                    1.3.0
  @backstage/plugin-entity-validation                                0.1.0
  @backstage/plugin-events-backend                                   0.2.3
  @backstage/plugin-events-node                                      0.2.3
  @backstage/plugin-explore-backend                                  0.0.4
  @backstage/plugin-explore-common                                   0.0.1
  @backstage/plugin-explore-react                                    0.0.26
  @backstage/plugin-home                                             0.4.31
  @backstage/plugin-jenkins-common                                   0.1.13
  @backstage/plugin-jenkins                                          0.7.14
  @backstage/plugin-linguist-common                                  0.1.0
  @backstage/plugin-linguist                                         0.1.0
  @backstage/plugin-org                                              0.6.5
  @backstage/plugin-permission-backend                               0.5.17
  @backstage/plugin-permission-common                                0.7.3, 0.7.5-next.0
  @backstage/plugin-permission-node                                  0.7.5, 0.7.7-next.2
  @backstage/plugin-permission-react                                 0.4.10
  @backstage/plugin-proxy-backend                                    0.2.36
  @backstage/plugin-scaffolder-backend-module-confluence-to-markdown 0.1.0-next.0
  @backstage/plugin-scaffolder-backend                               1.11.0, 1.13.0-next.2
  @backstage/plugin-scaffolder-common                                1.2.5, 1.2.7-next.1
  @backstage/plugin-scaffolder-node                                  0.1.0, 0.1.2-next.2
  @backstage/plugin-scaffolder-react                                 1.1.0
  @backstage/plugin-search-backend-module-catalog                    0.1.0-next.1
  @backstage/plugin-search-backend-module-elasticsearch              1.1.3
  @backstage/plugin-search-backend-module-pg                         0.5.3
  @backstage/plugin-search-backend-node                              1.1.3, 1.2.0-next.2
  @backstage/plugin-search-backend                                   1.2.3
  @backstage/plugin-search-common                                    1.2.1, 1.2.3-next.0
  @backstage/plugin-search-react                                     1.5.0
  @backstage/plugin-search                                           1.1.0
  @backstage/plugin-techdocs-module-addons-contrib                   1.0.10
  @backstage/plugin-techdocs-node                                    1.5.0
  @backstage/plugin-techdocs-react                                   1.0.6, 1.1.3
  @backstage/plugin-techdocs                                         1.5.0
  @backstage/plugin-user-settings                                    0.7.0
  @backstage/release-manifests                                       0.0.8
  @backstage/repo-tools                                              0.1.2
  @backstage/test-utils                                              1.2.5
  @backstage/theme                                                   0.2.16, 0.2.17
  @backstage/types                                                   1.0.1, 1.0.2
  @backstage/version-bridge                                          1.0.2, 1.0.3
Done in 4.13s.

**Comment by awanlin** [comment]
Thanks @db-cataloge-db, a few things worry me about the output you shared: that you don't have a Backstage version means you are possibly on a very old version and the number of duplicate package versions. 

I would say do an upgrade y running `yarn backstage-cli versions:bump`. That should create a `backstage.json` file in the root of the repo with the Backstage version which will get updated when you do this again in the future. It should also help fix the duplicate package versions. Once that's done I would try the Confluence to Markdown action again.

Just want to mention we use the UrlRead with both Bitbucket and GitHub the same way as the Confluence to Markdown action does. Now, if after you upgrade and still have issues I'll try and setup the Confluence to Markdown action on our instance as we want to use it ourselves

**Comment by db-cataloge-db** [comment]
The reason we don't have a backstage version is because we don't perform bump. We have extended the capabilities of some of the community plugins by extending the plugin itself. For example, if we were to extend the capabilities of the catalog frontend plugin, we copy the source code from github and put it in our repo and use the @backstage-extended rather than @backstage namespace, and replace all the references in our workspace. In this way, our entire project will use the extended version rather than the npm version of the plugin.

**Comment by awanlin** [comment]
Hi @db-cataloge-db, sorry for the slow response. I'm not sure how helpful I'm going to be based on the state of your Backstage being a pretty custom fork of the code base. What I can do is at least test out the `confluence:transform:markdown` action with our Backstage instance to at least confirm it is working in the expected setup. But I've gotten fairly busy so this may not happen quickly.

If you do get this working please post here to let me know

**Comment by awanlin** [comment]
I did get some time to try this out and it gets past the section that uses the `UrlReader` so there's something in you Backstage code that must not be setup properly but I have no idea what.

Worth noting that the `confluence:transform:markdown` action doesn't work with Confluence Cloud, I'm working on a PR to add support though

**Comment by awanlin** [comment]
PR for Confluence Cloud support is here: #17468

**Comment by db-cataloge-db** [comment]
> @db-cataloge-db I used GitHub

Ok. I tried with github, it works. It doesn't work with bitbucket.
Do we plan to support that?

**Comment by awanlin** [comment]
Oh, we use the `UrlReader.readTree()` with Bitbucket all the time in our custom plugins and it works fine. I just didn't test Bitbucket with this action as we don't actually have the `mkdocs.yml` files in any of those repos for those we let TechDocs generate it on the fly
