### ISSUE TITLE
🐛  export 'usePluginOptions' (imported as 'usePluginOptions') was not found in '@backstage/core-plugin-api'

### ISSUE THREAD

**Issue by yumigm** [backstage/backstage#17287]
### 📜 Description

I am having this issue regarding the 
yarn --cwd packages/app add @backstage/plugin-github-pull-requests-board

Everytime run this command I get this error 

WARNING in ../../node_modules/@backstage/plugin-catalog/dist/esm/index-d0312962.esm.js 31:38-54                                              [0] export 'usePluginOptions' (imported as 'usePluginOptions') was not found in '@backstage/core-plugin-api'

WARNING in ../../node_modules/@backstage/plugin-catalog/dist/esm/index-84e3a83e.esm.js 884:31-50                                             [0] export 'useEntityPermission' (imported as 'useEntityPermission') was not found in '@backstage/plugin-catalog-react'

WARNING in ../../node_modules/@backstage/plugin-jenkins/dist/index.esm.js 393:37-56                                                          [0] export 'useEntityPermission' (imported as 'useEntityPermission') was not found in '@backstage/plugin-catalog-react'

Can someone please help me with this warning?

### 👍 Expected behavior

I don't think it should compile with warnings or errors

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/110480295/230484734-cbe7ecd4-2463-41ca-927c-9c9ef36589b5.png)

### 👟 Reproduction steps

1. I go to location of my project file.
2. I run the command yarn --cwd packages/app add @backstage/plugin-github-pull-requests-board (yarn install worked before)
3. I get Compiling errors

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jhaals** [comment]
Sorry to hear that you're having problems. It does look like this issue could be related to forking Backstage or potentially an old version. Just to confirm, have you created backstage using `npx @backstage/create-app` or do you maintain a fork of the project? In any case I would try to update Backstage itself beforehand.

**Comment by b-afshar** [comment]
I had the same issue
running `yarn backstage-cli versions:bump` helped in my case

**Comment by Alok650** [comment]
Hi guys,
I have got this error and its not resolve even with `yarn backstage-cli versions:bump ` 
It was previously working fine, but started getting this error after rebuilding the node_modules

**Comment by alfred-stokespace** [comment]
The issue seems to be that core-plugin-api exposed that type as an `@alpha` type which negatively impacted how to was referencable from the built js. If you track the import side you see that plugin-catalog was miss-referencing the type (ie. without the alpha) prior to v1.12.1

after the fix... https://github.com/backstage/backstage/blame/v1.12.1/plugins/catalog/src/options.ts
before the fix ... https://github.com/backstage/backstage/blame/v1.11.1/plugins/catalog/src/options.ts
