### ISSUE TITLE
🐛 Bug Report: Check for organization/owner when passing collaborators

### ISSUE THREAD

**Issue by Gladdstone** [backstage/backstage#17309]
### 📜 Description

There is currently a behavioral inconsistency in the Github scaffolder-backend between the access and collaborators parameters where when passed a value, access will check for and split the organization/owner value from the team slug in order to pass the correct value to octokit.

```
if (access?.startsWith(`${owner}/`)) {
  const [, team] = access.split('/');
  await client.rest.teams.addOrUpdateRepoPermissionsInOrg({
    org: owner,
    team_slug: team,
    owner,
    repo,
    permission: 'admin',
  });
}
```

The collaborators value does not currently make this check. Partially for this reason it also does not make an attempt to validate that the teams passed to it are valid within the organization.

### 👍 Expected behavior

Both parameters should be configured to accept the `@organization/team` format. May also validate team access when able to do so.

### 👎 Actual Behavior with Screenshots

`access` parameter takes the format of `@organization/team`, collaborators expects the format `team`.

### 👟 Reproduction steps

https://github.com/sfc-gh-kleonhard/backstage/blob/bf70a939e64679bb61fb4b7a48e116868ff8f233/plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts#L176-L222

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@Gladdstone do you want to whip up a PR to see what this looks like in practice? Happy to change this just would rather not break backward compatibility if we can avoid it too.

**Comment by ltdonner-bah** [comment]
Unstale, please

**Comment by benjdlambert** [comment]
This is still open for contributions if someone wants to create a PR? :pray:
