### ISSUE TITLE
🐛 Bug Report: Installing the ADR Plugin

### ISSUE THREAD

**Issue by voodooGQ** [backstage/backstage#17323]
### 📜 Description

There are a few things happening with this (these?) bug(s). I followed all the [instructions here](https://github.com/backstage/backstage/tree/master/plugins/adr-backend) to install the backend plugin, and then the [instructions here](https://github.com/backstage/backstage/tree/master/plugins/adr) to install the front end application, and although I didn't see it mentioned I also installed the [adr-common](https://github.com/backstage/backstage/tree/master/plugins/adr-common) plugin due to dependencies.

First thing we noticed is that the annotation with a relative path doesn't seem to work. When reviewing the logs we noticed that an annotation of `backstage.io/adr-location: docs/adrs` and an annotation of `backstage.io/source-location: url:https://github.com/{ORG}/{REPO}` was producing an api call that omitted the `{REPO}` and did not point to the `tree` url. An example of the call would be `GET /api/adr/list?url=https%3A%2F%2Fgithub.com%2F{ORG}%2Fdocs%2Fadrs` or effectively a url of `https://github.com/{ORG}/docs/adrs`. We fixed this error by supplying a full url of `backstage.io/adr-location: https://github.com/{ORG}/{REPO}/tree/main/docs/adrs`, however, based on the docs it seems like the original version should be possible.

Next, when going to the `ADR` tab of an entity we're getting the following error `Routable extension component with mount point routeRef{type=absolute,id=adr} was not discovered in the app element tree. Routable extension components may not be rendered by other components and must be directly available as an element within the App provider component.`. No where in the docs does it say to add anything to the App router, but we gave it a try to see what happens. Initially, pulling up the tab did list out the ADRs, however when you click on any of the adrs it crashes with an `Entity context not available` error. Unfortunately, there's no `element` that can be passed to the root level routes, when adding  `<Route path="/adrs" element={<EntityAdrContent />} />` to the `App.tsx` file it fails because it's expecting entity context.

Finally, this plugin doesn't appear to support [this tutorial for authenticating api requests in the backend](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md). When we add the `authMiddleware` to the handler we get consistent unauthorized requests back. I really don't know if this is a major issue or not, we left it off for testing, but does seem like a thing to bring up.

I'm probably doing something wrong here, but my code matches the tutorial.

### 👍 Expected behavior

Plugin README installation tutorial should work as expected.

### 👎 Actual Behavior with Screenshots

Errors with displaying the plugin:

![image](https://user-images.githubusercontent.com/1512028/231274129-561f0bf9-632a-41ec-94c1-df24fc1e567e.png)

### 👟 Reproduction steps

Follow the README installation instructions for the `adr` and `adr-backend` plugins

### 📃 Provide the context for the Bug.

We want to start displaying ADRs, but we can't at the moment.

### 🖥️ Your Environment

```
OS:   Linux 5.19.0-38-generic - linux/x64
node: v18.12.1
yarn: 1.22.19
cli:  0.22.2 (installed)
backstage:  1.11.0

Dependencies:
  @backstage/app-defaults                               1.2.0
  @backstage/backend-app-api                            0.4.0, 0.4.1
  @backstage/backend-common                             0.18.2, 0.18.3
  @backstage/backend-dev-utils                          0.1.0, 0.1.1
  @backstage/backend-plugin-api                         0.4.0, 0.5.0
  @backstage/backend-tasks                              0.4.3, 0.5.0
  @backstage/catalog-client                             0.9.0, 1.3.1, 1.4.0
  @backstage/catalog-model                              0.13.0, 1.2.0, 1.2.1
  @backstage/cli-common                                 0.1.11, 0.1.12
  @backstage/cli                                        0.22.2, 0.22.3
  @backstage/config-loader                              1.1.8, 1.1.9
  @backstage/config                                     0.1.15, 1.0.6, 1.0.7
  @backstage/core-api                                   0.2.23
  @backstage/core-app-api                               1.5.0
  @backstage/core-components                            0.11.2, 0.12.4, 0.12.5, 0.9.5
  @backstage/core-plugin-api                            0.1.13, 0.8.0, 1.4.0, 1.5.0
  @backstage/core                                       0.7.14
  @backstage/dev-utils                                  1.0.12
  @backstage/errors                                     0.1.5, 0.2.2, 1.1.4, 1.1.5
  @backstage/eslint-plugin                              0.1.0, 0.1.1
  @backstage/integration-aws-node                       0.1.1, 0.1.2
  @backstage/integration-react                          0.1.25, 1.1.10, 1.1.11
  @backstage/integration                                0.8.0, 1.4.2, 1.4.3
  @backstage/plugin-adr-backend                         0.3.1
  @backstage/plugin-adr-common                          0.2.7
  @backstage/plugin-adr                                 0.4.1
  @backstage/plugin-analytics-module-ga                 0.1.26
  @backstage/plugin-api-docs                            0.9.0
  @backstage/plugin-app-backend                         0.3.42
  @backstage/plugin-auth-backend                        0.18.0
  @backstage/plugin-auth-node                           0.2.11, 0.2.12
  @backstage/plugin-catalog-backend-module-github       0.2.5
  @backstage/plugin-catalog-backend-module-openapi      0.1.8
  @backstage/plugin-catalog-backend                     1.7.2
  @backstage/plugin-catalog-common                      1.0.11, 1.0.12
  @backstage/plugin-catalog-graph                       0.2.27
  @backstage/plugin-catalog-import                      0.9.5
  @backstage/plugin-catalog-node                        1.3.3
  @backstage/plugin-catalog-react                       0.9.0, 1.3.0, 1.4.0
  @backstage/plugin-catalog                             1.8.0
  @backstage/plugin-entity-feedback-backend             0.1.0
  @backstage/plugin-entity-feedback-common              0.1.0
  @backstage/plugin-entity-feedback                     0.1.0
  @backstage/plugin-entity-validation                   0.1.0
  @backstage/plugin-events-node                         0.2.3
  @backstage/plugin-github-actions                      0.5.15
  @backstage/plugin-github-issues                       0.2.4
  @backstage/plugin-home                                0.4.31
  @backstage/plugin-org                                 0.6.5
  @backstage/plugin-permission-common                   0.5.3, 0.6.4, 0.7.3, 0.7.4
  @backstage/plugin-permission-node                     0.7.5, 0.7.6
  @backstage/plugin-permission-react                    0.3.4, 0.4.10, 0.4.11
  @backstage/plugin-proxy-backend                       0.2.36
  @backstage/plugin-scaffolder-backend                  1.11.0
  @backstage/plugin-scaffolder-common                   1.2.5
  @backstage/plugin-scaffolder-node                     0.1.0
  @backstage/plugin-scaffolder-react                    1.1.0
  @backstage/plugin-scaffolder                          1.11.0
  @backstage/plugin-search-backend-module-elasticsearch 1.1.3
  @backstage/plugin-search-backend-module-pg            0.5.3
  @backstage/plugin-search-backend-node                 1.1.3
  @backstage/plugin-search-backend                      1.2.3
  @backstage/plugin-search-common                       0.3.4, 1.2.1, 1.2.2
  @backstage/plugin-search-react                        1.5.0, 1.5.1
  @backstage/plugin-search                              1.1.0
  @backstage/plugin-shortcuts                           0.3.7
  @backstage/plugin-stack-overflow                      0.1.11
  @backstage/plugin-tech-radar                          0.6.1
  @backstage/plugin-techdocs-addons-test-utils          1.0.10
  @backstage/plugin-techdocs-backend                    1.5.3
  @backstage/plugin-techdocs-module-addons-contrib      1.0.10
  @backstage/plugin-techdocs-node                       1.5.0
  @backstage/plugin-techdocs-react                      1.1.3
  @backstage/plugin-techdocs                            1.5.0
  @backstage/plugin-user-settings                       0.7.0
  @backstage/release-manifests                          0.0.8
  @backstage/search-common                              0.3.4
  @backstage/test-utils                                 1.2.5
  @backstage/theme                                      0.2.17, 0.2.18
  @backstage/types                                      0.1.3, 1.0.2
  @backstage/version-bridge                             0.1.2, 1.0.3
Done in 0.74s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by voodooGQ** [comment]
Thanks for the reply @Rugvip. Yes, the entries I have on my entity pages match what you have in the previous. One thing to note, though not sure how much it matters, we have our EntityPage split up into various components to try and keep the `EntityPage.tsx` file sane which I don't think is the "standard" based on [the main file on the Backstage repo](https://github.com/backstage/backstage/blob/master/packages/app/src/components/catalog/EntityPage.tsx). 

I can't imagine how that would impact this, but it is a "difference" so want to point it out. Here's a rough example of what the `ServiceEntityPage` looks like:

```
export const ServiceEntityPage: React.FC<Props> = (): JSX.Element => {
  return (
    <EntityLayout>
      {/* Overview */}
      <EntityLayout.Route path="/" title="Overview">
        <Grid container spacing={3} alignItems="stretch">
          <EntityWarningSwitch />
          <Grid item md={6}>
            <AboutCard variant="gridItem" />
          </Grid>
          <Grid item md={6}>
            <EntityCatalogGraphCard />
          </Grid>
          <Grid item md={12}>
            <EntityHasApisCard variant="gridItem" />
          </Grid>
          <Grid item md={12}>
            <EntityHasComponentsCard variant="gridItem" />
          </Grid>
        </Grid>
      </EntityLayout.Route>
      {/* ADR */}
      <EntityLayout.Route if={isAdrAvailable} path="/adrs" title="ADRs">
        <EntityAdrContent />
      </EntityLayout.Route>
   </EntityLayout>
  )
}
```

That's then called to from our `ComponentEntityPage`:

```
export const ComponentEntityPage: React.FC<Props> = (): JSX.Element => {
  return (
    <EntitySwitch>
      <EntitySwitch.Case if={isComponentType("service")}>
        <ServiceEntityPage />
      </EntitySwitch.Case>

       //...
       
      <EntitySwitch.Case>
        <DefaultEntityPage />
      </EntitySwitch.Case>
    </EntitySwitch>
  );
};
```

And finally from the `EntityPage` proper:

```
export const entityPage = (
  <EntitySwitch>
    <EntitySwitch.Case if={isKind("component")}>
      <ComponentEntityPage />
    </EntitySwitch.Case>

    //...
    
    <EntitySwitch.Case>
      <DefaultEntityPage />
    </EntitySwitch.Case>
  </EntitySwitch>
);
```

**Comment by freben** [comment]
Regarding the source location:

https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageiosource-location

> If the URL points to a folder, it is important that it is suffixed with a '/' in order for relative path resolution to work consistently.

I think that's what's happening here. It may seem like an odd requirement, but the thing is that generic path resolver logic can't know whether what a URL is pointing to is a folder or a file. It's just being passed as the base to the two-argument URL constructor to resolve into a full URL, and this is how it ends up working.

**Comment by freben** [comment]
Regarding missing route / context:

```tsx
const ComponentEntityPage: React.FC
```

is the source of that. You need to make it

```tsx
const componentEntityPage = (
  <EntitySwitch>
    ...
```

(note the lowercase c)

essentially the entire tree there needs to be static JSX elements, _no components_ (functions or classes) at all.

**Comment by freben** [comment]
Regarding auth:

It seems that the [`AdrClient` correctly uses the `fetchApi`](https://github.com/backstage/backstage/blob/54f741d1f0229f0b7026f485d48307a8cb33ba8f/plugins/adr/src/api/AdrClient.ts#L40). That _should_ be enough to ensure that it injects a Backstage auth token with every request to the backend. Could you add a debugging log in your routes on the backend (plus check the browser network inspector) to ensure that the Authorization header is sent along properly?

May be worth noting that this does NOT work in guest user mode; only properly authenticated sessions have a Backstage token to inject in requests.

**Comment by voodooGQ** [comment]
Update:

- Moving all the components to the main EntityPage and setting them as basic JSX fixed the `Routable extension component` issue.
- We haven't tested the added `/` to the end of the url yet, but will give that a try next.
- The plugin is still giving a `401` when we add the `authMiddleware` to the route. @freben more then willing to debug this, however, could you point me to the best place to send a console statement? I assumed in the main backend `index.ts` file, but not seeing anything to actually output the headers.

**Comment by kuangp** [comment]
> It seems that the [`AdrClient` correctly uses the `fetchApi`](https://github.com/backstage/backstage/blob/54f741d1f0229f0b7026f485d48307a8cb33ba8f/plugins/adr/src/api/AdrClient.ts#L40). That _should_ be enough to ensure that it injects a Backstage auth token with every request to the backend.

This was actually just released in the latest version that came out today. @voodooGQ can you try updated to the latest and  re-testing?

**Comment by voodooGQ** [comment]
@kuangp I went ahead and updated to the latest versions:

- @backstage/plugin-adr: ^0.5.0
- @backstage/plugin-adr-common: ^0.2.8
- @backstage/plugin-adr-backend: ^0.3.2

This actually completely broke my build from a TS compilation scenario. Prior to upgrading I had 0 warnings/errors for the tsc compile. Updating the plugins and running `yarn tsc` produces 15 errors accross 11 files:

```
packages/app/src/App.test.tsx:23:47 - error TS2786: 'App' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<{}, any, any> | null' is not a valid JSX element.
    Type 'Component<{}, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<{}, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'React.ReactNode' is not assignable to type 'import("/home/shane/Code/github.com/{ORG}/{REPO}/node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.

23     const rendered = await renderWithEffects(<App />);
                                                 ~~~

packages/app/src/components/catalog/overrides/EntityLinksCard/IconLink.tsx:43:6 - error TS2786: 'Box' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<BoxProps, any, any> | null' is not a valid JSX element.
    Type 'Component<BoxProps, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<BoxProps, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'React.ReactNode' is not assignable to type 'import("/home/shane/Code/github.com/{ORG}/{REPO}/node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.
            Type '{}' is not assignable to type 'ReactNode'.

43     <Box display="flex">
        ~~~

packages/app/src/components/catalog/overrides/EntityLinksCard/IconLink.tsx:44:8 - error TS2786: 'Box' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<BoxProps, any, any> | null' is not a valid JSX element.

44       <Box mr={1} className={classes.svgIcon}>
          ~~~

packages/app/src/components/catalog/overrides/EntityLinksCard/IconLink.tsx:46:20 - error TS2786: 'Icon' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<{ fontSize?: "small" | "default" | "large" | undefined; }, any, any> | null' is not a valid JSX element.
    Type 'Component<{ fontSize?: "small" | "default" | "large" | undefined; }, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<{ fontSize?: "small" | "default" | "large" | undefined; }, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'React.ReactNode' is not assignable to type 'import("/home/shane/Code/github.com/{ORG}/{REPO}/node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.

46           {Icon ? <Icon /> : <LanguageIcon />}
                      ~~~~

packages/app/src/components/catalog/overrides/EntityLinksCard/IconLink.tsx:49:8 - error TS2786: 'Box' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<BoxProps, any, any> | null' is not a valid JSX element.

49       <Box flexGrow="1">
          ~~~

packages/app/src/index.tsx:6:18 - error TS2786: 'App' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<{}, any, any> | null' is not a valid JSX element.

6 ReactDOM.render(<App />, document.getElementById("root"));
                   ~~~

plugins/collators/src/components/CodeSearchResultList/CodeSearchResultListItem.tsx:39:10 - error TS2786: 'Box' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<BoxProps, any, any> | null' is not a valid JSX element.

39         <Box flexWrap="wrap">
            ~~~

plugins/collators/src/components/EnvVarSearchResultListItem/EnvVarSearchResultListItem.tsx:39:10 - error TS2786: 'Box' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<BoxProps, any, any> | null' is not a valid JSX element.

39         <Box flexWrap="wrap">
            ~~~

plugins/collators/src/components/FeatureFlagSearchResultListItem/FeatureFlagSearchResultListItem.tsx:39:10 - error TS2786: 'Box' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<BoxProps, any, any> | null' is not a valid JSX element.

39         <Box flexWrap="wrap">
            ~~~

plugins/ops-review/src/components/InformationTooltip/InformationTooltip.tsx:39:6 - error TS2786: 'CustomTooltip' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<Pick<TooltipProps, "slot" | "style" | "title" | "ref" | "children" | "className" | "innerRef" | "color" | "id" | "lang" | ... 264 more ... | "TransitionProps"> & StyledComponentProps<...>, any, any> | null' is not a valid JSX element.
    Type 'Component<Pick<TooltipProps, "slot" | "style" | "title" | "ref" | "children" | "className" | "innerRef" | "color" | "id" | "lang" | "role" | "tabIndex" | "aria-activedescendant" | ... 261 more ... | "TransitionProps"> & StyledComponentProps<...>, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<Pick<TooltipProps, "slot" | "style" | "title" | "ref" | "children" | "className" | "innerRef" | "color" | "id" | "lang" | "role" | "tabIndex" | "aria-activedescendant" | ... 261 more ... | "TransitionProps"> & StyledComponentProps<...>, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'React.ReactNode' is not assignable to type 'import("/home/shane/Code/github.com/{ORG}/{REPO}/node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.

39     <CustomTooltip
        ~~~~~~~~~~~~~

plugins/ops-review/src/components/TeamBreakdown/TeamCarousel/v1/TeamCarousel.tsx:124:8 - error TS2786: 'Carousel' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<CarouselProps, any, any> | null' is not a valid JSX element.
    Type 'Component<CarouselProps, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<CarouselProps, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'React.ReactNode' is not assignable to type 'import("/home/shane/Code/github.com/{ORG}/{REPO}/node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.

124       <Carousel autoPlay={false} navButtonsAlwaysVisible>
           ~~~~~~~~

plugins/ops-review/src/components/TeamBreakdown/TeamCarousel/v2/TeamCarousel.tsx:140:8 - error TS2786: 'Carousel' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<CarouselProps, any, any> | null' is not a valid JSX element.

140       <Carousel autoPlay={false} navButtonsAlwaysVisible>
           ~~~~~~~~

plugins/ops-review/src/views/OpsReviewEditForm/Editor.tsx:63:8 - error TS2786: 'TinyEditor' cannot be used as a JSX component.
  Its instance type 'Editor' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'ReactElement<{ ref: RefObject<HTMLElement>; id: string; }, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
        Property 'children' is missing in type 'ReactElement<{ ref: RefObject<HTMLElement>; id: string; }, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.

63       <TinyEditor
          ~~~~~~~~~~

  node_modules/@types/react-transition-group/node_modules/@types/react/index.d.ts:182:9
    182         children: ReactNode;
                ~~~~~~~~
    'children' is declared here.

plugins/opsgenie-api/src/components/PostMortemTab/PostMortemTab.tsx:23:10 - error TS2786: 'Box' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<BoxProps, any, any> | null' is not a valid JSX element.

23         <Box sx={{ p: 3 }}>
            ~~~

plugins/opsgenie-api/src/components/PostMortemTab/PostMortemTab.tsx:42:8 - error TS2786: 'Box' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<BoxProps, any, any> | null' is not a valid JSX element.

42       <Box sx={{ borderBottom: 1, borderColor: "divider" }}>
          ~~~


Found 15 errors in 11 files.

Errors  Files
     1  packages/app/src/App.test.tsx:23
     4  packages/app/src/components/catalog/overrides/EntityLinksCard/IconLink.tsx:43
     1  packages/app/src/index.tsx:6
     1  plugins/collators/src/components/CodeSearchResultList/CodeSearchResultListItem.tsx:39
     1  plugins/collators/src/components/EnvVarSearchResultListItem/EnvVarSearchResultListItem.tsx:39
     1  plugins/collators/src/components/FeatureFlagSearchResultListItem/FeatureFlagSearchResultListItem.tsx:39
     1  plugins/ops-review/src/components/InformationTooltip/InformationTooltip.tsx:39
     1  plugins/ops-review/src/components/TeamBreakdown/TeamCarousel/v1/TeamCarousel.tsx:124
     1  plugins/ops-review/src/components/TeamBreakdown/TeamCarousel/v2/TeamCarousel.tsx:140
     1  plugins/ops-review/src/views/OpsReviewEditForm/Editor.tsx:63
     2  plugins/opsgenie-api/src/components/PostMortemTab/PostMortemTab.tsx:23
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by freben** [comment]
As mentioned in a discord thread, you may want to add resolutions for the react types in your _root_ package.json [like the main Backstage repo does](https://github.com/backstage/backstage/blob/master/package.json#L46), because for some reason React 18 types are being pulled in and mixed up across your packages [and they are unfortunately incompatible](https://stackoverflow.com/questions/71831601/ts2786-component-cannot-be-used-as-a-jsx-component) across majors

**Comment by voodooGQ** [comment]
@freben we're already doing this in our setup. React and React-DOM are being set to `17.0.2`. It was this way before we installed the plugin, but still are having installation issues:

![image](https://user-images.githubusercontent.com/1512028/233089019-647714e4-8179-421b-bd22-09884230f60f.png)

**Comment by drodil** [comment]
You have to replace those with `@types/react` and `@types/react-dom`. See example here https://github.com/drodil/backstage-plugin-qeta/commit/d972168210a40b85f54b9748ac86c71e580c54d2

**Comment by voodooGQ** [comment]
Added the resolutions for `@types/react` and `@types/react-dom`. TSC is compiling normally again.

Checking the new plugin does appear as though the auth middleware is working as expected.

However, we're still seeing that the url that gets pulled from the plugin does not work with an added `/` to the end of the `source-location` annotations. This is easily fixable by adding a full url for the adr annotation, but want to point out that it's still not working as described.

![image](https://user-images.githubusercontent.com/1512028/233118701-74c6d687-fdca-483a-a772-23a11b319ea7.png)
![image](https://user-images.githubusercontent.com/1512028/233118812-92818b02-4c78-4664-a580-f98dc187094b.png)

**Comment by voodooGQ** [comment]
`https://api.github.com/repos/{ORG}/{REPO}/docs/adrs` is what is being hit with a 404 not found

**Comment by kuangp** [comment]
How is your `backstage.io/source-location` annotation being set? 

The default form of this annotation (for GitHub) is `url:https://github.com/{ORG}/{REPO}/tree/{BRANCH}/` which is typically automatically set by the [`AnnotateLocationEntityProcessor`](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/CatalogBuilder.ts#L354) as a default processor in the `CatalogBuilder`. This plugin relies on evaluating paths using the built-in [`ScmIntegration`](https://github.com/backstage/backstage/blob/master/plugins/adr-common/src/index.ts#L63-L66) that expects source urls to follow this standard format.

**Comment by voodooGQ** [comment]
@kuangp it's manually being set on the entity as `backstage.io/source-location: url:https://github.com/{ORG}/{REPO}/`. No tree or branch was supplied to the annotation, which coincides with [this documentation article](https://backstage.io/docs/features/software-catalog/well-known-annotations/#backstageiosource-location). In the documentation the example they provide has no `/tree/{BRANCH}/` as part of it's annotation, and in the blurb itself it does not mention having to do this.

We can omit this, or go back to the original annotation that had the full url. However, we definitely have some inconsistencies in the docs if the `/tree/{BRANCH}/` is expected.

**Comment by Gianluska** [comment]
Hey @voodooGQ! How you been?

How did you fix it? x.x

**Comment by voodooGQ** [comment]
@Gianluska 
> How did you fix it? x.x

The thread here outlines the various issues and fixes. No other steps were taken besides those described in the previous comments.
