### ISSUE TITLE
🐛 Bug Report: Catalog Placeholder Resolvers

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#17337]
### 📜 Description

I discussed this issue with @freben and he suggested posting an issue

If an organization doesn't give everyone read access to all the repositories backstage has access to, the catalog placeholder mechanisms can be used to exfiltrate source code / files from repos the user wouldn't normally have access to.

### 👍 Expected behavior

Raw source code shouldn't from repos you don't have access to shouldn't be accessible through backstage.  Only processed files (i.e. processed `catalog-info.yaml` should be accessible)

### 👎 Actual Behavior with Screenshots

Source code from repos you dont' have access to can be embedded into entity definitions via placeholders in entity definitions (`$text`)

### 👟 Reproduction steps

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: attack
spec:
  type: vulnerability
  lifecycle: production
  owner: foo
  foo:
    - $text: https://github.com/myorg/repo-i-dont-have-access-to/README.md
    - $text: https://github.com/myorg/repo-i-dont-have-access-to/ANOTHER-FILE.md
```

### 📃 Provide the context for the Bug.

Whilst the [threat model](https://backstage.io/docs/overview/threat-model/#common-backend-configuration) does discuss this when it talks about `UrlReader`, it's suggestion of controlling access through `backend.reader.allow` doesn't due to the built in url readers for github, azure etc.  Even if these could be removed, you wouldn't want to remove these completely as you still want backstage to be able to read the `catalog-info.yaml` files from these repos, you don't want to backstage exposing raw, unprocessed files.

You can currently mitigate against this by replacing the built in placeholder resolvers with no-op implementations, although it feels like there could be a better way to do this.

```ts
builder.setPlaceholderResolver('json', async (params) => {return {[`\$${params.key}`]: params.value}});
builder.setPlaceholderResolver('text', async (params) => {return {[`\$${params.key}`]: params.value}});
builder.setPlaceholderResolver('yaml', async (params) => {return {[`\$${params.key}`]: params.value}});
```

Another mitigation could be to add an option which only allows relative paths to be used in the placeholder processors.  This seems like it should be possible through `PlaceholderResolverParams.baseUrl` .

Finally, it may be that this is all by design.  Even if you were able to lock down backstage so it only read yaml files and only yaml files that had been through the processing loop, you could exfiltrate files that look close enough to backstage entities (e.g. kubenetes manifests).  If this is the case, I think there could be some clarification to the threat model to make this a bit clearer.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Thank you for reporting! This is indeed something to mention in the threat model, is that something you'd want to take a stab at?

Regarding fixing this more broadly and making it secure by default, we've discussed the idea of changing the default to allow reading of URLs in the same repo, as well as an explicit allow list of URLs for things like common infra repos. Would need to figure out how to roll that out with minimal impact, but I think it can be done. What do you think? and is that perhaps very close to your idea of relative paths?

Regarding Kubernetes manifests, it's a security feature that you can not ingest those into the catalog by default. It's not been designed that way explicitly, but in doing some research on breaking the catalog that's one of the things I found useful and provided an additional layer of protection.

**Comment by afscrome** [comment]
Yup, defaulting to only allowing references within the same repo is a better solution than faffing with relative paths.

I can give a go at updating the threat model - may not be until the weekend.

**Comment by Rugvip** [comment]
Ended up proposing #17506

**Comment by benjdlambert** [comment]
@afscrome do you think we can close this given @Rugvip's changes?

**Comment by afscrome** [comment]
Yup, that's sufficient.
