### ISSUE TITLE
🚀 Feature: SearchPage component supports custom initial state

### ISSUE THREAD

**Issue by rikez** [backstage/backstage#17348]
### 🔖 Feature description

We would like to be able to render the SearchPage route with custom initial state. The [SearchContextProvider](https://github.com/backstage/backstage/blob/HEAD//plugins/search-react/src/context/SearchContext.tsx?L238:14-238:35#L238) can be initialized with a custom search config initial state. However, in the [SearchPage](https://github.com/backstage/backstage/blob/b975a04a58298cd05f39a217fa263e84fc111b2f/plugins/search/src/components/SearchPage/SearchPage.tsx#L92) component, the SearchContextProvider is used, but we're unable to pass an initial state.

### 🎤 Context

I would like to be able to customize the SearchPage to have a default page limit. I found a workaround, but I believe it would be this simple feature would be beneficial to others.

#### `plugins/search/src/components/SearchPage/SearchPage.tsx`
```tsx
export const SearchPage = (prop) => {
  const outlet = useOutlet();

  return (
    <SearchContextProvider initialState={prop.initialState}>
      <UrlUpdater />
      {outlet}
    </SearchContextProvider>
  );
};
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Letting @backstage/discoverability-maintainers decide whether it's worth exposing this, but I'd lean towards sticking to the existing way to customize the search page.

**Comment by camilaibs** [comment]
I would recommend setting the default limit via `app-config.yaml`, what do you think?

**Comment by rikez** [comment]
@camilaibs That definitely works. Is it possible to do it via `app-cnfogi.yaml` right now? I might have missed this in the docs.

**Comment by camilaibs** [comment]
@rikez currently it is possible on the backend side as per [this](https://github.com/backstage/backstage/pull/15097) pull request, but the configuration is not consumed on the frontend side. We would appreciate it if you could contribute with us by making this improvement 🙂

**Comment by rikez** [comment]
@camilaibs Sounds good to me. I'm willing to contribute.

**Comment by camilaibs** [comment]
> @camilaibs Sounds good to me. I'm willing to contribute.

Thanks a lot and don't hesitate to ping us whenever you need support 🙌🏻

**Comment by camilaibs** [comment]
Hi @rikez, just checking to see if you've had the opportunity to start working on this? Feel free to ping us on this issue in case you need some support.

**Comment by rikez** [comment]
Hey @camilaibs, I haven't started, but it's on my radar to get this done this week.

**Comment by camilaibs** [comment]
Perfect, thanks again for helping us 🙌🏻

**Comment by rikez** [comment]
@camilaibs Can this be closed?

**Comment by camilaibs** [comment]
> @camilaibs Can this be closed?

Yes! Thanks again for your help on this issue 🙌🏻
