### ISSUE TITLE
🐛 Bug Report: Microsoft Calendar plugin uses Outlook logo on marketplace

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#17340]
### 📜 Description

The Microsoft Calendar plugin uses Outlook logo on the [Plugin marketplace](https://backstage.io/plugins) which we can't do without permission from Microsoft: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks

![image](https://user-images.githubusercontent.com/67169551/231571189-76cb6df2-378a-4f96-a533-22b2d6470f3d.png)

### 👍 Expected behavior

We use a different logo on the marketplace for Microsoft Calendar plugin

### 👎 Actual Behavior with Screenshots

The Microsoft Calendar plugin uses Outlook logo on marketplace which we can't do without permission from Microsoft: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks

### 👟 Reproduction steps

N/A

### 📃 Provide the context for the Bug.

We could get into hot water with this, easier to just use something else

### 🖥️ Your Environment

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
@abhay-soni-developer @NishkarshRaj can you look into this as soon as possible? Sorry this got missed when this was submitted in #16869

**Comment by Rugvip** [comment]
Thank you for reporting! Fixing this by removing the existing logo for now #17355
