### ISSUE TITLE
🚀 Feature: Apply analytics context/attributes to `navigate` events

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#17387]
### 🔖 Feature description

It should be possible for plugin developers (stretch goal: perhaps app integrators too?) to attach analytics context and attributes to `navigate` analytics events.

### 🎤 Context

We have a system where plugin developers and app integrators can provide `<AnalyticsContext>` around analytics events that are triggered within the Backstage react application.

However, `navigate` events are a special action that is fired when the route changes in react router.  Thanks to the magic of routable extensions, we're able to decorate these events with some useful metadata (e.g. the ID of the plugin that provided the routable extension, the ID of the route itself, and the name of the extension itself)...  But it can be useful to provide additional metadata.

For example: it would be useful to provide an `entityRef` when pages related to entities are navigated to.  ...Today, this is not possible.

### ✌️ Possible Implementation

- We could expose a new function property on the `createRoutableExtension` interface that could take in route parameters and return values that could be merged into the analytics context?  We may have to bury this down into the route object structure in some way...
- ???

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
A callback like that would only in practice have access to the route params right, or are there any other valuable inputs that come to mind? The reason I'm asking - and I'm not at all knowledgeable about this so bear with me - is that I was under the impression that analytics systems often have special facilities to extract variable path segments anyway. Would the value here be mainly in being able to compose the full entity ref as a string upfront, from the three parts?

**Comment by iamEAP** [comment]
> _Would the value here be mainly in being able to compose the full entity ref as a string upfront, from the three parts?_

That would be the concrete value of having access to the route params, yes.  ...But I guess the more important bit is that the logic for that would be able to live with the plugin that declares/uses those route params.

Whereas right now, we might be able to get access to the route params where the `navigate` event gets fired, but there's no guarantee that just because there are three params, and they happen to be named `name`, `kind`, and `namespace`, that they correspond to the parts of an entity ref.

The suggested solution on its own wouldn't solve this problem, but another use-case would be to allow app integrators to supply arbitrary analytics context to `navigate` events.  You could imagine a scenario, for example, where plugins are owned by teams, and perhaps you want to decorate all events for a given plugin (including `navigate` events on its routable extensions) with an `owner` property.

**Comment by Rugvip** [comment]
I think analytics data is core and stable enough that we could add this directly to `CatalogEntityPage` or the `EntityProvider` tbh. Skipping an abstraction for now.

**Comment by iamEAP** [comment]
> _I think analytics data is core and stable enough that we could add this directly to `CatalogEntityPage` or the `EntityProvider` tbh. Skipping an abstraction for now._

We do have this tucked away in `EntityProvider`, and it applies to all _other_ events, it's just that the `navigate` events are triggered in a totally different way.

The one pressing use-case that comes to mind (constructing entity refs) is taken care of via https://github.com/backstage/backstage/pull/17480

I'll leave this open in case others find a different need for this kind of thing!  ...But if it goes stale, feel free to let it close itself.

**Comment by Rugvip** [comment]
Ah right. Hmm, I guess the analytics context could communicate the additional values upwards to the root and have those be added to navigation events? It seems a bit awkward though with for example many small cards with different context on a page. In particular there are very many cases where a particular route has many different plugins on it for example.

Adding some new known component data and then extending `createRoutableExtension` seems like the most sensible way to do this idd. Not entirely sure if worth though 🤔
