### ISSUE TITLE
🐛 Bug Report: Unable to use additional configuration sources at startup

### ISSUE THREAD

**Issue by ilya-kochetkov-cko** [backstage/backstage#17380]
### 📜 Description

Version https://github.com/backstage/backstage/releases/tag/v1.13.0-next.2

https://github.com/backstage/backstage/pull/16643 introduced a new feature that should allow additional sources of configuration to be provided on startup (e.g. secrets from AWS Secret Manager).

However, there's a type mismatch in the signatures of `loadBackendConfig`  in `packages/backend-common/src/config.ts` and `loadBackendConfig` in `packages/backend-app-api/src/config/config.ts`.

One `loadBackendConfig` expects a non-array `AppConfig`
https://github.com/backstage/backstage/blob/32bf9ff91457184e075dc4ee578c0e753bc6e2c9/packages/backend-common/src/config.ts#L37
while the other expects an array `AppConfig[]`
https://github.com/backstage/backstage/blob/32bf9ff91457184e075dc4ee578c0e753bc6e2c9/packages/backend-app-api/src/config/config.ts#L74

This prevents me from using this new functionality, unfortunately. 

### 👍 Expected behavior

When I pass a static AppConfig to `loadBackendConfig` at startup

```
async function main() {
	const appConfig: AppConfig = {
		context: '/path/to/config',
		data: {
		  foo: 'bar',
		}
	  };

	const config = await loadBackendConfig({
		argv: process.argv,
		logger: getRootLogger(),
		additionalConfig: appConfig
	});

	console.log(config.getString('foo'));

```

I expect to see `bar` in the console log when I run backstage locally

### 👎 Actual Behavior with Screenshots

In the current state, Backstage fails to startup because 
`[1] Backend failed to start up, Error: Missing required config value at 'foo'`,

### 👟 Reproduction steps

1. Pass an instance of AppConfig to `loadBackendConfig` during backend initialization
3. Try to log a value off that AppConfig after the initialization
4. Start Backstage locally
5. Check logs and see if it reports an issue or a value 

See `Expected behavior` for code samples

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Oh I see what you mean now. It's not really about the types, but it never gets passed down and we didn't notice because it is an optional options field. Alright, made a fix:

https://github.com/backstage/backstage/pull/17400

This should get released tomorrow.
