### ISSUE TITLE
🚀 Feature: Provide Backstage API documentation

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#17418]
### 🔖 Feature description

Provide API documentation of the backstage's own APIs. 

### 🎤 Context

Sometimes there is a need to call the Backstage application from outside and thus having API documentation in place helps with this.

### ✌️ Possible Implementation

This could be done dynamically for example utilizing this https://github.com/mpashkovskiy/express-oas-generator

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
We have started the process of getting OpenAPI definitions in place for the major plugins, and building tooling for that. One of the things we want to produce out of those definitions, is definitely auto generated API docs. So stay tuned, or perhaps continue on the work that @sennyeya started in https://github.com/backstage/backstage/pull/15667

**Comment by Rugvip** [comment]
Gonna close this since as mentioned it's already tracked. In particular see #17482

**Comment by sennyeya** [comment]
@drodil Following up on this, though it is tracked in #17482, initial support for this was delivered in #17535 which was part of the 1.20 release. Currently only `catalog`, `search`, and `todo` have specs and would have documentation to show, but looking at adding new ones in the next few months and any help there would be appreciated.
