### ISSUE TITLE
💬 RFC: Increase UX on Scaffolder Plugin

### ISSUE THREAD

**Issue by chicoribas** [backstage/backstage#17417]
### 🔖 Need

At Grupo Boticário we have been using Backstage as a portal solution since the beginning of our platform engineering. Few weeks ago we started using our UX team to increase the user experience of our platform and some tips about Backstage were given by them.
It is important to observe that we are committed to assume these changes and contribute to Backstage more consistently.

### 🎉 Proposal

1. Add documentation on template card
There are two suggestions:
If the template has some Techdocs, it should be accessible from the template card. It is important to open documentation on a new tab.
The opções "CHOOSE" should be highlighted

The final result should be something like this:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/5077079/232621837-d71897de-b982-4ffe-835b-c1ea6e237ddf.png">

2. Title and subtitle of form page
Change the fixed title and subtitle of the form page on create to the name and description of the template that have been chosen by the user, giving a better context to the user.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/5077079/232621914-22b8d53d-e7be-4418-be7b-81a5312b850a.png">

3 - Information on scaffold form 
It is important to show some information about the template when the user is filling the form. It would be great to have a custom component on the form page that receives the events and data from the form and show custom insights about the results of that scaffold.

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/5077079/232633497-f5f265b9-7b1d-43bb-bb89-4049a792fabc.png">

This custom component should be loaded on startup, the same way as custom fields, and can vary between templates throughout the `spec.parametesOverview` parameter.

4 - Feedback after Scaffold

The outputs of the scaffold process are shown as links and the start over should be a secondary action.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/5077079/232633576-9c2feadb-a138-4c4f-9681-34c1aaea60a8.png">

The solution maybe is to enable a custom component to show scaffold results. This custom component should be loaded on startup, the same way as custom fields, and can vary between templates throughout the `spec.success` parameter.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/5077079/232633617-8587302a-e131-4aee-81a0-648ca4ffb9b9.png">

### 〽️ Alternatives

Grupo Boticário could build a new customized plugin based on the existing one.

### ❌ Risks

Impacts on existing templates.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by awanlin** [comment]
Hi @chicoribas, thanks for submitting this, there are some really worthwhile suggestions here. I do think though that you may want to look at the upcoming `scaffolder/next` which is a redesign of the scaffolder which is in Alpha and can be tested following the documentation here: https://backstage.io/docs/features/software-templates/testing-scaffolder-alpha. Some of your ideas are actually already implemented - being able to provide you own component in places or completely - but they will be laid out in different places.

Same with the TechDocs link, seems it's mostly in place already: https://github.com/backstage/backstage/issues/17183

**Comment by awanlin** [comment]
Oh, I should have also mentioned I have a UX related PR here around some of the buttons: https://github.com/backstage/backstage/pull/17391

**Comment by chicoribas** [comment]
It sounds very cool @awanlin...

Is there any roadmap to see and evaluate if we can help on delevopment?
