### ISSUE TITLE
🚀 Feature: Fuzzy Search with PgSearch

### ISSUE THREAD

**Issue by Hennnnes** [backstage/backstage#17423]
### 🔖 Feature description

The feature shall allow users to include fuzzy search matches when using PgSearch.

### 🎤 Context

In our use-case we would love to include fuzzy search with PgSearch as we don't get results for `wa yba ck`, but for `wayback`.
After a quick first observation it would be simple to write a custom `SearchTranslator` that solves the whitespace Issue, but we would appreciate an approach that fixes the issue on a larger base.

### ✌️ Possible Implementation

I am no expert in search algorithms or fuzzy searches, but there seem to be multiple ways to implement fuzzy searches in postgres, e.g. using `levenshtein` or`LIKE`. Additionally here are links to the PostgreSQL documentation about [pgtrgm](https://www.postgresql.org/docs/current/pgtrgm.html) and [fuzzystrmatch](https://www.postgresql.org/docs/current/fuzzystrmatch.html).

It would be great to supply a config option that indicates wether fuzzy searches shall be supported or not.
The implementation should probably take place here: https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-pg/src/database/DatabaseDocumentStore.ts#L158-L162.

A simple test for correct implementation could be that `Hello World`, `hello world`, `hallo world`, `HelloWorld`, `Hel lowo rld` return the same results.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by emmaindal** [comment]
Hello @Hennnnes, thanks a lot for opening this issue! I can see you would be open for submitting a PR, that would be awesome. Do you want me to assign you to this issue?

**Comment by Hennnnes** [comment]
Hey @emmaindal, thanks for your reply.
I'd prefer discussing which of the possible fuzzy search options would suite backstage's needs best first. Because unfortunately I have no idea about the pros and cons of each... Afterwards I'm open to providing a Pull Request 😊

**Comment by SonilPro** [comment]
I see a use case where we could add an option to supply a LIKE query which would be concatenated to the already existing query. Currently I am looking for a solution to search for partial words in a document, so this could be useful for that as well. Or maybe even be able to create a custom query all together.

**Comment by SonilPro** [comment]
@emmaindal  @tikabom I created a PR that could potentially fix this issue. I left some comments in the PR, discussing different possible solutions. Could someone please take a look when they catch some time?
