### ISSUE TITLE
🚀 Feature: Link to Software Template from the Catalog Kind:Template object

### ISSUE THREAD

**Issue by waldirmontoya25** [backstage/backstage#17434]
### 🔖 Feature description

Add a link in the software catalog objects of Kind: Template, pointing back to the software template execution workflow.

### 🎤 Context

When you use the Global Search and type a software template name, the result takes you to the Software Catalog object with the Kind: Template, which could be confusing if the user is actually trying to find and execute the software template.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Makes sense. But you'd still land on the catalog page first right, and _that_ page has the button on it?

**Comment by waldirmontoya25** [comment]
Yes, that's what I was thinking.  So we'll go ahead and add it. Any thoughts about what would be the best place for the link? In the "about" card next to "view source and view techdocs" or maybe in the "links" card?

**Comment by luchillo17** [comment]
Have a draft PR, need to add tests for the new button, as well as make it system icon aware
(system icon-aware; e.g. [useApp()](https://backstage.io/docs/reference/core-plugin-api.useapp/).[getSystemIcon("scaffolder")](https://backstage.io/docs/reference/core-plugin-api.appcontext/))

**Comment by luchillo17** [comment]
PR is ready for review.
