### ISSUE TITLE
🐛 Bug Report: 404 in Techdocs for existing HTML file

### ISSUE THREAD

**Issue by dannief** [backstage/backstage#17447]
### 📜 Description

I have an mkdocs.yml file that looks like the following:

```yaml
site_name: Database Docs

nav:
  - Home: index.md
  - Data Dictionary: datadict.html
  - Schema: schema.md
```

The docs are successfully generated when adding the catalog info to Backstage. However, Backstage reports a 404 error when trying to load 'datadict.hmtl`. (This scenario works in mkdocs 1.4.2 on my local machine)

The error is due to Backstage making a request to this URL: `https://backstage.example.com/api/techdocs/static/docs/default/resource/db/datadict.html/index.html`

However the following URL returns the correct HTML
`https://backstage.example.com/api/techdocs/static/docs/default/resource/db/datadict.html`

It seem that Backstage is assuming that `datadict.html` is a folder and looking for an `index.html` within it

### 👍 Expected behavior

I expected that the same functionality of mkdocs would apply. That any non-markdown file would be copied to the server as-is and can be linked to like other static files such as images.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/6110488/232941521-c58f46b1-f200-456f-a6bb-ed20b7532865.png)

### 👟 Reproduction steps

1. Create a docs folder and mkdocs.yml file in a sub-folder in your repository for a database resource
2. Add an index.md file and and html file to the docs folder
3. Update the mkdocs.yml file as below
  ```yaml
site_name: My Database Docs

nav:
  - Home: index.md
  - Data Dictionary: datadict.html
```
4.  Create a catalog-info.yml file with kind `Resource` for the component and the techdocs annotation
5. Add the component to Backstage
6. Navigate to the tech docs and wait for the docs to load
7. Navigate to `Data Dictionary` from the navigation panel

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by duqcyxwd** [comment]
Curious if there's a plan to support this? Since HTML might become the new markdown for AI Agent, can we support it?
