### ISSUE TITLE
🐛 Bug Report: build docker image failed

### ISSUE THREAD

**Issue by gongshishao** [backstage/backstage#17462]
### 📜 Description

I tring to build&run docker image from local by this deployment doc: https://backstage.io/docs/deployment/docker

Step1:
yarn install --frozen-lockfile

yarn tsc

yarn build:backend --config app-config.yaml

Step2:
run **yarn build-image** or  **docker image build . -f packages/backend/Dockerfile --tag backstage**
but all failed at this stage:
 ERROR [stage-0 2/8] RUN --mount=type=cache,target=/var/cache/apt,sharing=locked     --mount=type=cache,target=/var/lib/apt,sharing=locked     apt-get update &&     apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential &&     yarn config set python                                         

### 👍 Expected behavior

expect image build success, so that I can run this image from local

### 👎 Actual Behavior with Screenshots

![截屏2023-04-20 15 05 20](https://user-images.githubusercontent.com/43381611/233287573-78a3d16c-b0e1-43f2-9ce2-2fd090e4497a.png)
![截屏2023-04-20 15 08 28](https://user-images.githubusercontent.com/43381611/233287748-4e702127-727a-4902-bbd5-44aba416015d.png)

### 👟 Reproduction steps

As Description

### 🖥️ Your Environment

yarn backstage-cli info
yarn run v1.22.19
$ /Users/renhuazhang/MyWork/Projects/PAAS/pulse-backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 22.3.0 - darwin/x64
node: v18.14.2
yarn: 1.22.19
cli:  0.22.3 (installed)
backstage:  1.11.0

Dependencies:
  @backstage/app-defaults                                   1.2.0
  @backstage/backend-app-api                                0.4.0, 0.4.1
  @backstage/backend-common                                 0.18.2, 0.18.3
  @backstage/backend-dev-utils                              0.1.0, 0.1.1
  @backstage/backend-plugin-api                             0.4.0, 0.5.0
  @backstage/backend-tasks                                  0.4.3, 0.5.0
  @backstage/catalog-client                                 1.3.1, 1.4.0
  @backstage/catalog-model                                  1.2.0, 1.2.1
  @backstage/cli-common                                     0.1.11, 0.1.12
  @backstage/cli                                            0.22.3
  @backstage/config-loader                                  1.1.8, 1.1.9
  @backstage/config                                         1.0.6, 1.0.7
  @backstage/core-app-api                                   1.5.0
  @backstage/core-components                                0.12.4, 0.12.5, 0.13.0
  @backstage/core-plugin-api                                1.4.0, 1.5.0, 1.5.1
  @backstage/errors                                         1.1.4, 1.1.5
  @backstage/eslint-plugin                                  0.1.1
  @backstage/integration-aws-node                           0.1.1, 0.1.2
  @backstage/integration-react                              1.1.10
  @backstage/integration                                    1.4.2, 1.4.3
  @backstage/plugin-api-docs                                0.9.0
  @backstage/plugin-app-backend                             0.3.42
  @backstage/plugin-auth-backend                            0.18.0
  @backstage/plugin-auth-node                               0.2.11, 0.2.12
  @backstage/plugin-catalog-backend-module-bitbucket-server 0.1.8
  @backstage/plugin-catalog-backend                         1.7.2
  @backstage/plugin-catalog-common                          1.0.11, 1.0.12
  @backstage/plugin-catalog-graph                           0.2.27
  @backstage/plugin-catalog-import                          0.9.5
  @backstage/plugin-catalog-node                            1.3.3, 1.3.4
  @backstage/plugin-catalog-react                           1.3.0, 1.4.0
  @backstage/plugin-catalog                                 1.8.0
  @backstage/plugin-github-actions                          0.5.15
  @backstage/plugin-jenkins-backend                         0.1.33
  @backstage/plugin-jenkins-common                          0.1.14
  @backstage/plugin-jenkins                                 0.7.15
  @backstage/plugin-org                                     0.6.5
  @backstage/plugin-permission-common                       0.7.3, 0.7.4
  @backstage/plugin-permission-node                         0.7.5, 0.7.6
  @backstage/plugin-permission-react                        0.4.10, 0.4.11
  @backstage/plugin-proxy-backend                           0.2.36
  @backstage/plugin-scaffolder-backend                      1.11.0
  @backstage/plugin-scaffolder-common                       1.2.5
  @backstage/plugin-scaffolder-node                         0.1.0
  @backstage/plugin-scaffolder-react                        1.1.0
  @backstage/plugin-scaffolder                              1.11.0
  @backstage/plugin-search-backend-module-pg                0.5.3
  @backstage/plugin-search-backend-node                     1.1.3
  @backstage/plugin-search-backend                          1.2.3
  @backstage/plugin-search-common                           1.2.1, 1.2.2
  @backstage/plugin-search-react                            1.5.0
  @backstage/plugin-search                                  1.1.0
  @backstage/plugin-tech-radar                              0.6.2
  @backstage/plugin-techdocs-backend                        1.5.3
  @backstage/plugin-techdocs-module-addons-contrib          1.0.10
  @backstage/plugin-techdocs-node                           1.5.0
  @backstage/plugin-techdocs-react                          1.1.3
  @backstage/plugin-techdocs                                1.5.0
  @backstage/plugin-user-settings                           0.7.0
  @backstage/release-manifests                              0.0.8
  @backstage/test-utils                                     1.2.5
  @backstage/theme                                          0.2.17, 0.2.18, 0.2.19
  @backstage/types                                          1.0.2
  @backstage/version-bridge                                 1.0.3, 1.0.4
✨  Done in 1.96s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Seems like there's actual problems for your docker env to speak to the debian servers. Not sure how to address that - probably a temporary error

**Comment by Rugvip** [comment]
Gonna close this as it doesn't seem to be related to Backstage
