### ISSUE TITLE
🐛 Bug Report: Catalog sorting by-query fails for Boolean values

### ISSUE THREAD

**Issue by yousifalraheem** [backstage/backstage#17464]
### 📜 Description

I've been working on developing a catalog table based on [the newly added APIs for backend pagination](https://github.com/backstage/backstage/pull/12246) and I found an issue while trying to sort a column that has a Boolean value. See the example below:

```json
{
  "kind": "Component",
  "metadata": {
    "name": "my-app"
    "needsReview": true,
  }
}
```

Now if I try the catalog API `queryEntities` with the following:

```ts
catalogApi.queryEntities(
  {
    limit: pageSize,
    cursor: page.cursor,
    filter: {
      kind: 'Component',
      'spec.type': 'service',
    },
    orderFields: { field: 'metadata.name', order: 'asc' },
  }
)
```

This will work and return an array of entities. But If I try to use this sort `{ field: 'metadata.needsReview', order: 'asc' }` then I get nothing.

### 👍 Expected behavior

Ideally: I should get the list of entities ordered by the Boolean value. This can be done by converting the Boolean value into a number `+value` which returns either `0` or `1` depending on the Boolean value.

Less ideally: I should get the list of entities not ordered by the Boolean value. But at least I should get something because I'm trying to sort not filter. Getting an empty list is just bizarre.

### 👎 Actual Behavior with Screenshots

I'm getting an empty list of entities.

### 👟 Reproduction steps

- Create a simply table
- Use `catalog.queryEntities` to fetch entities from the catalog but point the `orderFields` to a Boolean value in the object
- See the issue

### 📃 Provide the context for the Bug.

We have a field in the catalog called `needsReview` which refers to the applications that needs review from their owners about how prepare it is for high traffic events like cyber week. We usually let users sort their applications by this columns so they can see applications grouped by `yes` or `no` (`true` or `false`). I'm trying to implement the same with the new API.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
This seems to work from the server's point of view. It being boolean should not make any difference; [it all gets stringified](https://github.com/backstage/backstage/blob/abe96d48374904bc894c12a802bbc35b40914285/plugins/catalog-backend/src/stitching/buildEntitySearch.ts#L150) in the end so in the database search table it becomes the key-value pair of `'metadata.needsReview'` and `'true'`.

What I did was to add a `test: true` inside the metadata [of one of the example entities](https://github.com/backstage/backstage/blob/abe96d48374904bc894c12a802bbc35b40914285/packages/catalog-model/examples/acme/team-a-group.yaml#L40) and then starting the backend, and then issuing

```bash
$ curl -s 'localhost:7007/api/catalog/entities/by-query?fields=metadata.name,metadata.test&orderField=metadata.test,asc' | jq

{
  "items": [
    {
      "metadata": {
        "name": "nigel.manning",
        "test": true
      }
    }
  ],
  "totalItems": 1,
  "pageInfo": {}
}
```

I wonder what might be happening here, is that your query actually is not seen as [an initial request](https://github.com/backstage/backstage/blob/abe96d48374904bc894c12a802bbc35b40914285/packages/catalog-client/src/types/api.ts#L386)? The first request is not meant to have a cursor passed in to it at all. After the first request, the following ones [do not specify the order at all](https://github.com/backstage/backstage/blob/abe96d48374904bc894c12a802bbc35b40914285/packages/catalog-client/src/types/api.ts#L417).

**Comment by Rugvip** [comment]
Seems like there's a TypeScript issue here, ideally this particular request should lead to a type errors, as you shouldn't be allowed to provide both a `cursor` and `filter` for example. I'm preparing a change that switches the interface to an overload, but ran into some trouble with the documentation syntax for that so that will come a bit later.

**Comment by vinzscam** [comment]
I think this might be due to the fact that `needsReview` is transformed to `needsreview` in the search table.
Could you try with `{ field: 'metadata.needsreview', order: 'asc' }` ?

**Comment by vinzscam** [comment]
> Seems like there's a TypeScript issue here, ideally this particular request should lead to a type errors, as you shouldn't be allowed to provide both a `cursor` and `filter` for example. I'm preparing a change that switches the interface to an overload, but ran into some trouble with the documentation syntax for that so that will come a bit later.

Possible fix:
https://github.com/backstage/backstage/compare/vinzscam/fix-query-entities-cursor-request-typings?expand=1
