### ISSUE TITLE
🐛 Bug Report: backend.baseUrl doesn't affect api route

### ISSUE THREAD

**Issue by TheAschr** [backstage/backstage#17475]
### 📜 Description

Changing the following configuration options

- `app.baseUrl` to `http://localhost:3000/documentation`
- `backend.baseUrl` to  `http://localhost:7007/documentation`

causes the client to attempt make api requests to `http://localhost:7007/documentation/api` however the api is still mounted at `http://localhost:7007/api`. This causes pages to not load correctly.

### 👍 Expected behavior

The api should be mounted using the `backend.baseUrl` pathname.

Example:

`http://localhost:7007/documentation/api/catalog/entities?filter=kind=component`

### 👎 Actual Behavior with Screenshots

Changing the `backend.baseUrl` configuration to `http://localhost:7007/documentation` the api stays mounted at `/`.

Example:

`http://localhost:7007/api/catalog/entities?filter=kind=component`

### 👟 Reproduction steps

1. Create a fresh setup of the application using the [getting started guide](https://backstage.io/docs/getting-started/) 
2. Change `app.baseUrl` in app-config.yaml to  `http://localhost:3000/documentation`
3. Change `backend.baseUrl` in app-config.yaml to `http://localhost:7007/documentation`
4. Run yarn dev

### 📃 Provide the context for the Bug.

I am trying to serve the entire application (api and client) under the suburl `/documentation`.

### 🖥️ Your Environment

OS:   Linux 4.15.0-209-generic - linux/x64
node: v17.9.1
yarn: 1.22.19
cli:  0.22.6 (installed)
backstage:  1.13.0

Dependencies:
  @backstage/app-defaults                          1.3.0
  @backstage/backend-app-api                       0.4.2
  @backstage/backend-common                        0.18.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.1
  @backstage/backend-tasks                         0.5.1
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.6
  @backstage/config-loader                         1.2.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.7.0
  @backstage/core-components                       0.13.0
  @backstage/core-plugin-api                       1.5.1
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.12
  @backstage/integration                           1.4.4
  @backstage/plugin-api-docs                       0.9.2
  @backstage/plugin-app-backend                    0.3.44
  @backstage/plugin-auth-backend                   0.18.2
  @backstage/plugin-auth-node                      0.2.13
  @backstage/plugin-catalog-backend                1.9.0
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.29
  @backstage/plugin-catalog-import                 0.9.7
  @backstage/plugin-catalog-node                   1.3.5
  @backstage/plugin-catalog-react                  1.5.0
  @backstage/plugin-catalog                        1.10.0
  @backstage/plugin-github-actions                 0.5.17
  @backstage/plugin-org                            0.6.7
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.7
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.38
  @backstage/plugin-scaffolder-backend             1.13.0
  @backstage/plugin-scaffolder-common              1.2.7
  @backstage/plugin-scaffolder-node                0.1.2
  @backstage/plugin-scaffolder-react               1.3.0
  @backstage/plugin-scaffolder                     1.13.0
  @backstage/plugin-search-backend-module-catalog  0.1.0
  @backstage/plugin-search-backend-module-pg       0.5.5
  @backstage/plugin-search-backend-module-techdocs 0.1.0
  @backstage/plugin-search-backend-node            1.2.0
  @backstage/plugin-search-backend                 1.3.0
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.5.2
  @backstage/plugin-search                         1.2.0
  @backstage/plugin-tech-radar                     0.6.3
  @backstage/plugin-techdocs-backend               1.6.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.12
  @backstage/plugin-techdocs-node                  1.7.0
  @backstage/plugin-techdocs-react                 1.1.5
  @backstage/plugin-techdocs                       1.6.1
  @backstage/plugin-user-settings                  0.7.2
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.0
  @backstage/theme                                 0.2.19
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by TheAschr** [comment]
By looking at the source code I was able to figure out that the `SingleHostDiscovery.fromConfig()` function in `./src/backend/index.ts` takes an optional second argument where you can specify the basePath for the api.

Example:

```ts
  const discovery = SingleHostDiscovery.fromConfig(config, {
    basePath: `/documentation/api`,
  });
```

It seems like it would be reasonable for new apps to be initialized with:

```ts
function getBasePath(config: Config) {
  return new URL(config.get('backend.baseUrl')).pathname;
}

/* ... */

const discovery = SingleHostDiscovery.fromConfig(config, {
  basePath: `${getBasePath(config)}/api`,
});

/* ... */

const service = createServiceBuilder(module)
  .loadConfig(config)
  .addRouter(`${getBasePath(config)}/api`, apiRouter)
  .addRouter(`${getBasePath(config)}`, await app(appEnv));
```

but maybe there is a better way.

**Comment by Rugvip** [comment]
This is the intended behavior, the default mount path for backend plugins is `/api/:pluginId` regardless of what the external URL is. The expectation is that you have a proxy that sits in front of the backend and strips away any prefix. If you want the backend itself to receive the prefix in the path directly, then you'll need to update the `SingleHostDiscovery` and `.addRouter()` calls as you described.
