### ISSUE TITLE
🐛 Bug Report: Techdocs navigation broken

### ISSUE THREAD

**Issue by lauraceconi** [backstage/backstage#17481]
### 📜 Description

After upgrading Backstage to version 11.0.1, our Techdocs navigation to internal links stoped working completely. The problem is related to [this specific change](https://github.com/backstage/backstage/pull/16682/files#diff-d9e9e7187d6b87acda3c8ae7ca44a17b0c44853033f6d006cf626877edb788e5R36), that is removing the trailing slash at the end of the URL. Currently, our nginx configuration for MkDocs requires `/` at the end of the URL for the page to be rendered.

From the related [Issue](https://github.com/backstage/backstage/issues/16544) and the [PR](https://github.com/backstage/backstage/pull/16682) I wasn't able to identify what is the specific reason to remove the `/` at the end. So, my question is: would it be an option to remove [this line of code](https://github.com/backstage/backstage/pull/16682/files#diff-d9e9e7187d6b87acda3c8ae7ca44a17b0c44853033f6d006cf626877edb788e5R36)?

```
...
// Remove any leading and trailing slashes.
.replace(/\/+$/, '')
...
```

### 👍 Expected behavior

Techdocs navigation should allow links to have a trailing slash at the end of the URL.

### 👎 Actual Behavior with Screenshots

Backstage tries to render a page that does not exist in MkDocs.

### 👟 Reproduction steps

...

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by lauraceconi** [comment]
@sennyeya @Rugvip @agentbellnorm Mentioning you, as you were in the PR's discussions :)

**Comment by sennyeya** [comment]
@lauraceconi This should be fine to revert, have run into issues with URLs before so wanted to head those off, but this was an over optimisation. Apologies for the issues caused.

**Comment by lauraceconi** [comment]
Thanks for the quick response, @sennyeya. I'll open a PR soon.
