### ISSUE TITLE
🚀 Feature: Glean search engine support

### ISSUE THREAD

**Issue by kunickiaj** [backstage/backstage#17494]
### 🔖 Feature description

(Glean)[https://www.glean.com/] is an enterprise search appliance. It would be useful to support:

1. Glean universal search results in Backstage search
2. Indexing Catalog / TechDocs entities in Glean

### 🎤 Context

Multiple community users have reported interest in Glean on the community Discord.

In our organization we use Glean to power universal search and is the primary interaction point on our pre-Backstage dev portal.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kunickiaj** [comment]
Wanted to share an update on progress on this -- though I'm not sure what it'll take to get a version I could potentially contribute back to the project. If nothing else hope this can help spark some ideas.

Created a new `SearchPage.tsx` that has a glean search input component and results component. It has to also handle query params and fetching a user auth token (redirect url).

This also replaces the SearchModal from the side bar. Also added the search component to the homepage.

This is definitely not an end-state but a starting point to a deeper integration. For now this is behind a feature flag in our instance.

**Comment by dweber019** [comment]
I could imagine some options.
1. Integrate glean into the backstage search like this https://github.com/K-Phoen/backstage-plugin-confluence, think would be easy to do and backstage users can find everything in backstage
2. Replace the search completely with glean and therefor index everything in backstage with glean. Probably would make more sense to first integrate data from backstage into glean and then think about the replacement of search in backstage

Just some thoughts

**Comment by kunickiaj** [comment]
Yeah it's our plan to have glean index everything in backstage. I'm also exploring the option of neatly integrating it as a search backend for the Backstage native search pieces but I think it'll take some additional work since glean allows us to search far more than just backstage.

**Comment by dweber019** [comment]
Do you know what the Backstage connector at https://www.glean.com/connectors is doing?

**Comment by kunickiaj** [comment]
> Do you know what the Backstage connector at https://www.glean.com/connectors is doing?

https://developers.glean.com/docs/sdk/readme/#introduction I believe the Push API label just means that you could integrate using the Push API though I'll try to find out if maybe they've already written something for this.

**Comment by nia-potato** [comment]
any updates on this?

**Comment by freben** [comment]
No, the issue was an expression of interest in such a thing being built but nobody in the community took it upon themselves to do it.

**Comment by nia-potato** [comment]
i will work on this, please assign it to me.
