### ISSUE TITLE
🐛 Bug Report: @backstage/plugin-newrelic does not support API pagination

### ISSUE THREAD

**Issue by wss-cadenwheeler** [backstage/backstage#17512]
### 📜 Description

The @backstage/plugin-newrelic plugin currently calls the New Relic API endpoint GET /v2/applications.json. This endpoint supports pagination but the plugin does not. This results in an incomplete list of applications returned to this plugin / frontend. It doesn't look like there is a universal limit for results per page but the "Link" header in the response of this API call will be used to determine if there are multiple pages.

https://docs.newrelic.com/docs/apis/rest-api-v2/basic-functions/pagination-api-output/

### 👍 Expected behavior

The New Relic API call from this plugin should support pagination.

### 👎 Actual Behavior with Screenshots

The plugin returns a limited amount of results due to pagination on the New Relic API and the lack of support for pagination in the plugin.

### 👟 Reproduction steps

1. Have a New Relic account with several applications (for me, it was over 100 applications but due to there not being a universal limit, this can vary).
2. Use this plugin to return application metrics in Backstage.
3. Observe that not all applications are returned from this plugin in Backstage.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Saha-7** [comment]
Based on the description of the issue, it seems that you are encountering an error when trying to run Backstage using the command yarn start. Specifically, it appears that you are receiving an error related to a missing swagger.yml file.

**Comment by Saha-7** [comment]
I cannot find the  `NewRelicClient.ts` file in this directory `backstage/backstage/blob/master/plugins/newrelic-backend/src/NewRelicClient.ts`.  Is this happening to some permission issue?

**Comment by jhaals** [comment]
> Based on the description of the issue, it seems that you are encountering an error when trying to run Backstage using the command yarn start. Specifically, it appears that you are receiving an error related to a missing swagger.yml file.

No the problem is that the API only return the first 100 since the endpoint is paginated.

The filepath and `NewRelicClient.ts` that you are trying to access does not exist. The client that needs updating exists in https://github.com/backstage/backstage/blob/master/plugins/newrelic/src/api/index.ts

**Comment by Saha-7** [comment]
Don't know actually how much it will work, but I have created 2 pull requests #17658 & #17659.
changed the `app-config.yaml` file & `backstage\plugins\newrelic\src\api\index.ts` file.
