### ISSUE TITLE
🚀 Feature: proxy-backend with permissions

### ISSUE THREAD

**Issue by dweber019** [backstage/backstage#17513]
### 🔖 Feature description

Be able to use https://backstage.io/docs/permissions/overview with some dynamic input like url etc for plugin https://github.com/backstage/backstage/blob/master/plugins/proxy-backend/README.md.

### 🎤 Context

We expose some services with the proxy plugin. But we have some cases where we expose to much and would like to narrow down what requests are allowed based on URL or the method.

Other options would be to use pathRewrite but feels more like a hack.
We could also provide a custom backend plugin but some plugins like https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/backstage-plugin-jira/README.md aren't able to use the custom backend.

### ✌️ Possible Implementation

Use the https://backstage.io/docs/permissions/overview where policies can use some dynamic input like url, method.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
I think with how the `proxy-backend` just being a simple wrapper around a library, it's going to be pretty tricky to introduce functionality like this. I think we'd strongly suggest that you move the proxying to your own backend plugin in which case that you can control the requests, shape the data, and do permissions etc there instead.

**Comment by dweber019** [comment]
Thanks for the response.
I think we can do this for most plugins we have. Only one missing is Jira where we could do a redirection from the proxy to a backend plugin.

**Comment by dfl-aeb** [comment]
Is there an example of such an advanced proxy backend plugin with permissions support etc?

Imho it needs to be something that' provided within backstage, cause missing permissions open up security risks.
