### ISSUE TITLE
🚀 Feature: Allow additional statement_timeout configuration for postgres database client

### ISSUE THREAD

**Issue by iriswang233** [backstage/backstage#17520]
### 🔖 Feature description

Currently db client only allows overriding database name
https://github.com/backstage/backstage/blob/master/packages/backend-common/src/database/DatabaseManager.ts#L324
https://github.com/backstage/backstage/blob/master/packages/backend-common/src/database/connection.ts#L70

However, there are several other options available for pg client https://node-postgres.com/apis/client, it would be good to allow additional configurations so we can set different statement_timeout for different pod.

```
type Config = {
  user?: string, // default process.env.PGUSER || process.env.USER
  password?: string or function, //default process.env.PGPASSWORD
  host?: string, // default process.env.PGHOST
  database?: string, // default process.env.PGDATABASE || user
  port?: number, // default process.env.PGPORT
  connectionString?: string, // e.g. postgres://user:password@host:5432/database
  ssl?: any, // passed directly to node.TLSSocket, supports all tls.connect options
  types?: any, // custom type parsers
  statement_timeout?: number, // number of milliseconds before a statement in query will time out, default is no timeout
  query_timeout?: number, // number of milliseconds before a query call will timeout, default is no timeout
  application_name?: string, // The name of the application that created this Client instance
  connectionTimeoutMillis?: number, // number of milliseconds to wait for connection, default is no timeout
  idle_in_transaction_session_timeout?: number // number of milliseconds before terminating any session with an open idle transaction, default is no timeout
}
```

```
export function createDatabaseClient(
  dbConfig: Config,
  overrides?: Partial<Knex.Config>,
  deps?: {
    lifecycle: LifecycleService;
    pluginMetadata: PluginMetadataService;
  },
) {
  const client: DatabaseClient = dbConfig.getString('client');

  return (
    ConnectorMapping[client]?.createClient(dbConfig, overrides, deps) ??
    knexFactory(mergeDatabaseConfig(dbConfig.get(), overrides))
  );
}
```

### 🎤 Context

Recently our search indexing failed due to statements are cancelled by 10s statement timeout, but we can't increase it further since it may affect db performance if we allow long statement timeout for all queries. So we would like to only increase the statement timeout for search pod connecting to postgres.

### ✌️ Possible Implementation

Maybe we can allow config for search.client.options, then apply these options when creating database client for plugin.

In https://github.com/backstage/backstage/blob/master/packages/backend-common/src/database/DatabaseManager.ts#L324

```
/**
   * Provides a partial `Knex.Config`• database name override for a given plugin.
   *
   * @param pluginId - Target plugin to get database name override
   * @returns Partial `Knex.Config` with database name override
   */
  private getClientOptionsOverrides(pluginId: string): Knex.Config {
    const clientOptions = configure.get(`${pluginId}.client.options`);
    return clientOptions
      ? clientOptions
      : {};
  }
```

In https://github.com/backstage/backstage/blob/master/packages/backend-common/src/database/connection.ts#L70

```
/**
 * Creates a knex database connection
 *
 * @public
 * @param dbConfig - The database config
 * @param overrides - Additional options to merge with the config
 */
export function createDatabaseClient(
  dbConfig: Config,
  overrides?: Partial<Knex.Config>,
  deps?: {
    lifecycle: LifecycleService;
    pluginMetadata: PluginMetadataService;
  },
clientOptions
) {
  const client: DatabaseClient = dbConfig.getString('client');

  return (
    ConnectorMapping[client]?.createClient(dbConfig, clientOptions, overrides, deps) ??
    knexFactory(mergeDatabaseConfig(dbConfig.get(), overrides))
  );
}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by iriswang233** [comment]
I have tried this but it's not working.
```yaml
  database:
    client: pg
    connection:
      host:
        $env: xx
      port:
        $env: xx
      user:
        $env: xx
      password:
        $env: xx
      statement_timeout: 480000
```
by trying knexConfig, you mean like this?

```yaml
 knexConfig:
     statement_timeout: 480000
```

**Comment by Rugvip** [comment]
If it needs to be in the connection config there's no way to do that atm afaik. The currently supported method would be the following:

```yaml
  database:
    ...
    knexConfig:
      statement_timeout: 480000
```

But I think that'd end up in the wrong place right?

I could see it making sense to merge in the `connection` object if it exists, so that you can do the following:

```yaml
  database:
    ...
    knexConfig:
      connection:
        statement_timeout: 480000
```

**Comment by iriswang233** [comment]
This works for me in the end. Thanks

```
plugin:
  search:
        connection:
          statement_timeout: xxxxx
```
