### ISSUE TITLE
💬 RFC: Add GCP project id parameter to techdocs-cli publish

### ISSUE THREAD

**Issue by FiloSanza** [backstage/backstage#17524]
### 🔖 Need

Hi everyone!
I would like to propose the addition of a flag that allows to specify which GCP project the bucket used by `techdocs-cli publish` belongs to.

As the documentation states the parameter is currently only read from the `app-config.yaml` file which in our case is not present when the tool is run in the CircleCI environment.
The only workaround I found is to set the environment variable `GCLOUD_PROJECT` ([official GCP Storage API for Node.js](https://googleapis.dev/nodejs/storage/latest/global.html#StorageOptions)) but this is not documented nor mentioned in the backstage docs.

The reason I'm proposing this change is the following:
We have different GCP projects involved:
- backstage
- workload identity federation that handles the creation of credentials for service accounts of other projects (in this case backstage's service account for techdocs-cli publish)
- any other project that wants to publish its documentation to backstage (let's call it `projectA`)

Having the credentials generated in the `workload identity federation` project and exposed via `GOOGLE_APPLICATION_CREDENTIALS` implies that for some reason the `Storage` API looks for the bucket in the `workload identity federation` GCP project instead of `projectA` leading to failure since the service account does not have permissions to do so (and it would be useless anyway).

### 🎉 Proposal

The changes I would propose are two:
- updating the techdocs-cli docs to either point to the GCP StorageOptions documentation linked above or mention the GCLOUD_PROJECT variable.
- adding the possibility to specify a gcp project using a techdocs-cli publish option (something like `--gcpProject`)

I've taken a look at the code and I believe that this should not be a big change, I am willing to work on it if you believe this could be valuable also to others.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by zinizhu** [comment]
We have a similar set up and it would be nice to have the support for WIF, thanks!
