### ISSUE TITLE
🐛 Bug Report: Jenkins plugin - problems with slashes in the branch name 

### ISSUE THREAD

**Issue by fraPace** [backstage/backstage#17542]
### 📜 Description

The branch name is not properly encoded prior to the API call.
This results in 404 or 500 depending on the target system.

### 👍 Expected behavior

The branch name is properly encoded to support special char in the name, like '/' for branches that follow conventions like 'release', 'features', etc.

### 👎 Actual Behavior with Screenshots

The branch name is not encoded, making the API call fail and resulting in information missing in the UI.

Sorry, but I cannot upload images to any site due to company policies.

### 👟 Reproduction steps

1. Create a Backstage app
2. Add the Jenkins Plugin backend
3. Add the Jenkins Plugin frontend
4. Add a component with a target job that has branches with slashes in it.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Gave this a try in https://github.com/backstage/backstage/pull/17613 - I think that's the only place where they weren't encoded. Give it a look if you think it makes sense.
