### ISSUE TITLE
🐛 Bug Report: catalog processing engine metrics are not exported by the metrics endpoint

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#17540]
### 📜 Description

There are 5 metrics that are produced by the `DefaultCatalogProcessingEngine` that do not appear to be exported by the `/metrics` endpoint in the backstage default app. 

### 👍 Expected behavior

When I run the following command:

```curl http://localhost:7007/metrics | grep catalog_stitched_entities_count```
```curl http://localhost:7007/metrics | grep catalog_processed_entities_count```
```curl http://localhost:7007/metrics | grep catalog_processing_duration_seconds```
```curl http://localhost:7007/metrics | grep catalog_processors_duration_seconds```
```curl http://localhost:7007/metrics | grep catalog_processing_queue_delay_seconds```

It should show each of those metrics.

### 👎 Actual Behavior with Screenshots

1. It does not show those metrics.

### 👟 Reproduction steps

1. Run `yarn start-backend`.
2. run `curl http://localhost:7007/metrics`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by punkle** [comment]
I seem to have version 14.2.0.

```
Brians-MacBook-Pro:backstage brianfletcher$ yarn why prom-client
├─ @backstage/plugin-catalog-backend@workspace:plugins/catalog-backend
│  └─ prom-client@npm:14.2.0 (via npm:^14.0.1)
│
├─ @backstage/plugin-scaffolder-backend@workspace:plugins/scaffolder-backend
│  └─ prom-client@npm:14.2.0 (via npm:^14.0.1)
│
└─ example-backend@workspace:packages/backend
   └─ prom-client@npm:14.2.0 (via npm:^14.0.1)
```

**Comment by punkle** [comment]
I wonder are you seeing those metrics on the metrics api?

**Comment by benjdlambert** [comment]
Also the metrics work on our internal software catalog deployment which is a `create-app` with just the backend.

**Comment by punkle** [comment]
@benjdlambert you know what.. I do see them. I dont really know what I was seeing now.. I am wondering now if I was too quick on the mark earlier. Maybe I called the metrics api before the metrics had been registered. I dont know. Sorry about the confusion, and thanks for humouring me. :/

**Comment by benjdlambert** [comment]
HA. No worries. Glad I could help! 😅
