### ISSUE TITLE
🚀 Feature: Support Multiple Order By Fields in `entities/by-query`

### ISSUE THREAD

**Issue by sennyeya** [backstage/backstage#17560]
### 🔖 Feature description

Support multiple order by fields in the `DefaultEntitiesCatalog.queryEntities` method. Currently, due to constraints on how we're querying the data, only the first field is considered when sorting and when resuming sort with a cursor. Ideally, we would support sorting by all fields.

### 🎤 Context

As a user, I want to be able to search the catalog efficiently with a nested sorting. An example would be sorting by `metadata.namespace` then by `metadata.name` or `spec.profile.displayName` then by `metadata.title` then by `metadata.name`. I also want those sortings to be sustained across cursor usage.

### ✌️ Possible Implementation

See [WIP here](https://github.com/sennyeya/backstage/blob/6126c6662f5f726433db1899a76186670253415f/plugins/catalog-backend/src/service/DefaultEntitiesCatalog.ts). 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by aramissennyeydd** [comment]
Closing this as well, we can reopen when this becomes prioritized.
