### ISSUE TITLE
🐛 Bug Report: Support button on domains tab in Explore plugin wraps oddly

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#17564]
### 📜 Description

The support button on the explore page for domains has a very odd line break that I can't explain.

### 👍 Expected behavior

I would expect the sentence "Explore the domains in your ecosystem" to be listed on one line, like other support buttons and the  other two pages in the explore page.

### 👎 Actual Behavior with Screenshots

| Domains | Tools | Groups |
| --- | --- | --- |
| <img width="291" alt="image" src="https://user-images.githubusercontent.com/33203301/235243028-c69ab1d1-babc-49f8-879c-0fb29f66057c.png"> | <img width="291" alt="image" src="https://user-images.githubusercontent.com/33203301/235243137-34c5c0e6-e086-429d-99c3-8dbaec146a1e.png"> | <img width="291" alt="image" src="https://user-images.githubusercontent.com/33203301/235243160-77c701e5-a820-40fb-8bdd-eba119eb1f27.png"> |

### 👟 Reproduction steps

1. Go to Demo site: http://demo.backstage.io
2. Go to Explore page: https://demo.backstage.io/explore/domains
3. Click the Support button at top right

### 📃 Provide the context for the Bug.

I thought I'd go try to fix this, but I actually can't figure out what is going wrong!

The relevant code is here:

https://github.com/backstage/backstage/blob/8444b0834f99233cd1ebca7e875b53902f884d1c/plugins/explore/src/components/DomainExplorerContent/DomainExplorerContent.tsx#L92

Which looks simple enough. So then I thought, maybe there's a bug in the SupportButton component?

And the SupportButton component here:

https://github.com/backstage/backstage/blob/8444b0834f99233cd1ebca7e875b53902f884d1c/packages/core-components/src/components/SupportButton/SupportButton.tsx#L150-L154

Interestingly, if I wrap the child like `[ {child} ]` then the button displays like,

```
[Discover the ]
[domains ]
[in your ecosystem]
```

So it seems like perhaps the loop is breaking up the sentence as different React child nodes?  But this DOESN'T seem to happen with this:

https://github.com/backstage/backstage/blob/8444b0834f99233cd1ebca7e875b53902f884d1c/plugins/explore/src/components/ToolExplorerContent/ToolExplorerContent.tsx#L73

:shrug:

### 🖥️ Your Environment

Here's my info, but this happens as well if I clone off `backstage/backstage` and I can see it in your deployed demo.backstage.io app.

---

OS:   Darwin 22.4.0 - darwin/x64
node: v18.15.0
yarn: 1.22.10
cli:  0.22.6 (installed)
backstage:  1.13.0

Dependencies:
  @backstage/app-defaults                          1.3.0
  @backstage/backend-app-api                       0.4.2
  @backstage/backend-common                        0.18.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.1
  @backstage/backend-tasks                         0.5.1
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.6
  @backstage/config-loader                         1.2.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.7.0
  @backstage/core-components                       0.13.0
  @backstage/core-plugin-api                       1.5.1
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.12
  @backstage/integration                           1.4.4
  @backstage/plugin-api-docs                       0.9.2
  @backstage/plugin-app-backend                    0.3.44
  @backstage/plugin-auth-backend                   0.18.2
  @backstage/plugin-auth-node                      0.2.13
  @backstage/plugin-catalog-backend-module-github  0.2.7
  @backstage/plugin-catalog-backend                1.9.0
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.29
  @backstage/plugin-catalog-import                 0.9.7
  @backstage/plugin-catalog-node                   1.3.5
  @backstage/plugin-catalog-react                  1.5.0
  @backstage/plugin-catalog                        1.10.0
  @backstage/plugin-circleci                       0.3.17
  @backstage/plugin-events-node                    0.2.5
  @backstage/plugin-explore-backend                0.0.6
  @backstage/plugin-explore-common                 0.0.1
  @backstage/plugin-explore-react                  0.0.28
  @backstage/plugin-explore                        0.4.2
  @backstage/plugin-github-actions                 0.5.17
  @backstage/plugin-home                           0.5.0
  @backstage/plugin-org                            0.6.7
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.7
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.38
  @backstage/plugin-scaffolder-backend             1.13.0
  @backstage/plugin-scaffolder-common              1.2.7
  @backstage/plugin-scaffolder-node                0.1.2
  @backstage/plugin-scaffolder-react               1.3.0
  @backstage/plugin-scaffolder                     1.13.0
  @backstage/plugin-search-backend-module-catalog  0.1.0
  @backstage/plugin-search-backend-module-explore  0.1.0
  @backstage/plugin-search-backend-module-pg       0.5.5
  @backstage/plugin-search-backend-module-techdocs 0.1.0
  @backstage/plugin-search-backend-node            1.2.0
  @backstage/plugin-search-backend                 1.3.0
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.5.2
  @backstage/plugin-search                         1.2.0
  @backstage/plugin-tech-radar                     0.6.3
  @backstage/plugin-techdocs-backend               1.6.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.12
  @backstage/plugin-techdocs-node                  1.7.0
  @backstage/plugin-techdocs-react                 1.1.5
  @backstage/plugin-techdocs                       1.6.1
  @backstage/plugin-user-settings                  0.7.2
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.0
  @backstage/theme                                 0.2.19
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4
✨  Done in 1.44s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Yep that's silly, thanks for reporting. Iterating the children like that was probably not an awesome idea, but did the immediate fix for now. ^
