### ISSUE TITLE
🚀 Feature: Plugins using proxies with credential headers

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#17595]
### 🔖 Feature description

In proxy section of the [threat model](https://backstage.io/docs/overview/threat-model/#proxy) states 
> It is recommended to avoid injecting authentication

However several of the plugins in this repro go against that advise work by passing `Authorization` (or applications pecific API Key headers) with static credentials.  

* [apache-airflow](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/apache-airflow/README.md?plain=1#L84)
* [bitrise](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/bitrise/README.md?plain=1#L51)
* [circleci](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/circleci/README.md?plain=1#L45)
* [code-climate](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/code-climate/README.md?plain=1#L43)
* [codescene](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/codescene/README.md?plain=1#L58)
* [dynatrace](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/dynatrace/README.md?plain=1#L66)
* [firehydrant](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/firehydrant/README.md?plain=1#L45)
* [fossa](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/fossa/README.md?plain=1#L44)
* [gocd](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/gocd/README.md?plain=1#L48)
* [ilert](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/ilert/README.md?plain=1#L103)
* [newrelic](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/newrelic/README.md?plain=1#L35)
* [newrelic-dashboard](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/newrelic-dashboard/README.md?plain=1#L24)
* [octopus-deploy](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/octopus-deploy/README.md?plain=1#L23)
* [pagerduty](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/pagerduty/README.md?plain=1#L108)
* [sentry](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/sentry/README.md?plain=1#L62)
* [splunk-on-call](https://github.com/backstage/backstage/blob/d1797f0e91de2be2770e4932320d05a492680ae3/plugins/splunk-on-call/README.md?plain=1#L79)

### 🎤 Context

Because the proxy configurations in most of these plugins exposes the entire 3rd party api, silently adding the authentication credentials, the proxy could be abused for operations other than those intended by the plugin.  For a readonly accounts, things may not be too bad, but could be disastrous for write permission accounts.

Some plugins configuration do mitigate against this by setting `allowedMethods` on the proxy, however there is still risk of privilege escalation beyond the intended purposes (e.g. read privileged system logs), or to cause damage if the 3rd party API has GET endpoints which do change state.

### ✌️ Possible Implementation

In an ideal world, all of these plugins would have been written in a manner that doesn't require these credentials to be given to the proxy, or more narrowly define the proxy access than "Whole API", but that ship has sailed

In the interim, a mitigation would be to add a warning to the documentation of each of the plugins highlighting the risk of putting credentials in a generic proxy endpoint, and advising that careful attention should be given to permissions the credentials have.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Hey :wave: thanks for this!

Just to elaborate more a little bit on the ideal world solution - thinking that all of these plugins should have an accompanying backend plugin which can basically act as the proxy but to only allow certain requests. Of course you could even go as far as to adding the permissions framework into there to add an additional layer of security there too. Also it would give the ability for the backend plugin to become more of a view service to the frontend plugin, maybe making multiple requests to the upstream and transforming it as sort of a presentation layer.

**Comment by Shocktrooper** [comment]
I just came here to talk about Sentry which it appears to be in the list.  With the current implementations for the proxy with these plugins an end user will have full access to the 3rd party API through the backend which is a security issue.

**Comment by Shocktrooper** [comment]
bump
