### ISSUE TITLE
🚀 Feature: CatalogTable to have the ability to extend columns[] and actions[]

### ISSUE THREAD

**Issue by amanb014** [backstage/backstage#17599]
### 🔖 Feature description

We want the ability to extend `defaultActions` and `defaultColumns` in [CatalogTable](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx) so we don't have to overwrite all the default columns.

I am proposing that we keep actions and columns the way they are, but add 2 new props:
- `additionalColumns`: Adds the columns to the end of the list (before actions), overwriting any columns that have the same [field](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/columns.tsx#L171) value
- `additionalActions`: Adds the additional actions at the end of the list of [defaultActions](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L139).

Any thoughts? Happy to work on this if this is OK to add.

### 🎤 Context

# Why
Currently we have this component here ([CatalogTable](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx)) that has some "default" columns and actions, and they're great!

Used here in [API plugin](https://github.com/backstage/backstage/blob/8444b0834f99233cd1ebca7e875b53902f884d1c/plugins/api-docs/src/components/ApiExplorerPage/DefaultApiExplorerPage.tsx#L102).

However, if we want to update the columns just a little bit, it requires duplication of all the other columns that we want to not change.

For example, we want to **Add** a new column: we have to recreate all the columns with our own new column.

And, if we want to **Add** a new "action", it requires us to recreate all the default ones, and add our new one.

### ✌️ Possible Implementation

The end result may be something like:

New Props:
```
columnBehavior: "extend" | "replace";
actionsBehavior: "extend" | "replace";
```

Example for Columns being added instead of replaced:
```typescript
<CatalogTable 
  columns={[ ...custom columns ]}
  columnBehavior="extend"
/>
```

The new custom columns get added to the end of the table.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Hey :wave: thanks for this suggestion! Whilst I'm thinking that this is a good idea, I think that we should first look at how https://github.com/backstage/backstage/issues/16876 might affect this and how we can implement features using this RFC to avoid adding more props to components.

**Comment by amanb014** [comment]
Thanks @benjdlambert! I was wondering if there is some context that I am missing before really starting to work on this.

While I do agree that components must be composable, I think having a guideline on what strategy we want to take in Backstage would be helpful for contributors. I see that the RFC is still in progress. I'll think about this a bit, and see what can be done to avoid adding props that change behavior!

In general, I also think that props are not all evil, but adding necessary props are okay for components to have :)

**Comment by roman-shandurenko** [comment]
+1 for this one. Not easy to extend the columns.
I would also really appreciate it if someone can point out examples of how can I update catalog columns for a specific entity, e.g., catalog index table for User entity.
Do you have any in mind @amanb014 ?

**Comment by spencerrichardhenry** [comment]
@roman-shandurenko What I had done a year ago was make a columnFactory with all defaults (i.e. name) and then a switch case for which columns to add on a per-entity basis. this requried forking the CatalogTable component. Sadly, based on current implementation (CatalogPage knows inital kind, but is not informed of changes), I believe this will still require a catalogTable fork. 


What would be nice would be if the column prop accepted a map like so:
{"<<kind>>.<<type>>": [Columns for that kind and type],
"Component.service": [CatalogTable.columns.createOwnerColumn, CatalogTable.columns.createSpecTypeColumn()...]

Then you could customize columns, create new columns for your own non-default fields, and change which columns are displayed, all on a per kind/type basis, without forking the CatalogTable page.

**Comment by benjdlambert** [comment]
@spencerrichardhenry not all `kinds` have `types` unfortunately. How about some form of API where you can provide the selected filters as an input and it can return the columns for you?
