### ISSUE TITLE
🚀 Feature: Inconsistency around whether array relation properties are mandatory or not 

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#17593]
### 🔖 Feature description

There inconsistency around whether the array relation properties are optional vs which are required (for which you have to explciitly provide an empty array if you don't want to use them)

Required:
* `group.children`
* `user.members`

Optional:
* `group.members`
* `component.subcomponentOf`
* `component.providesApis`
* `component.consumesApis`
* `component.dependsOn`
* `resource.dependsOn`
* `resource.dependencyOf`

e.g. for a leaf group with no children

```yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []

```

### 🎤 Context

You could justify the current implementation as different entity types having different expectations.  With users & groups typically being more centrally defined, you could justify having a more explicit model, whilst being more permissive with the more typically user defined entities.  This works for `User` entities, but still leaves `Groups` internally inconsistent with `members` being optional but `children` being required.  I would at minimum expect `members` and `children` on groups to be either both required, or both optional, not a mix of the two.

### ✌️ Possible Implementation

My inclination here would be to make `group.children` and `user.memberOf` optional.  There are many scenarios in which it's valid to have those relationships be empty, so it makes sense for them to optional like the relationship prperties on `Component` and `Resource` entities.

For `user.memberOf`, you may have chosen to define membership on the group (via group.members) rather than from the user perspective.  In this scenario, you'd typically expect `user.memberOf` to be empty.

For groups, leaf groups will always have empty children.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Think this makes sense, let's make the `children` optional. I think there might be a few places where typescript will just complain and need updating to check that there's a value instead if we do this, but thinking that overall it's a good change.
