### ISSUE TITLE
🚀 Feature: Scaffolder Text Output

### ISSUE THREAD

**Issue by voximity** [backstage/backstage#17596]
### 🔖 Feature description

Currently, the only form of documented output for a software template are `links`. A second output type, `text`, would display the user some arbitrary text output based on the success of a template, e.g. some JSON data resulting from the execution of the template.

Adding a second type of output will open the doors for future additions that may require their own routes/views in the UI, as viewing a text output would require its own view, similar to how step logs can be viewed in the Task Activity view.

### 🎤 Context

At RackN, we have used software templates to streamline the creation of objects in our service, such as clusters. Internally, our objects are represented as JSON data, and it would be very handy to view such data directly in Backstage as if the output of a template were another step whose log is visible to the user -- at this time, the only viable solution to this issue is to create a dummy step that always outputs some data from a previous step (image below).

### ✌️ Possible Implementation

A second output type, `text`, is introduced to the `outputs` field in the template schema, following closely to the `links` output type:

```yml
output:
  text:
    - title: Output
      text: ${{ steps['create'].output.data }}
```

Links to text outputs could be placed near other steps in the task activity view, roughly here:

![image](https://user-images.githubusercontent.com/11506439/235485495-17f09876-2f06-4ead-9b6e-719bef2a27f7.png)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by voximity** [comment]
Thanks for sharing @awanlin! I've forked the repository and begun playing with this code base. My initial thought was to write an analog to `LinkOutputs` that deals with text outputs -- adding a reference to it in the `DefaultTemplateOutputs` component. Does this implementation fit with the goals of `scaffolder/next`, or should I go about this in a different way?

Thanks!

**Comment by awanlin** [comment]
You're welcome, to be honest I'm not sure what the pattern is to build variations or new ones. Our best bet is to ask @benjdlambert as he's the lead maintainer for the scaffolder and for `scaffolder/next`.

**Comment by benjdlambert** [comment]
Hey :wave: Yep thanks for this tag @awanlin.

So with the new `scaffolder/next` work you can provide a `TemplateOutputComponent` to the router to render your Outputs in your custom way, however, feeling that with the `scaffolder/next` work, the UI now is completely redesigned and thinking that it perhaps makes sense to accept this as a contribution to the core rather than just a DIY thing. 

I'd recommend that we extend the `DefaultTemplateOutputs` component that it could render something like your schema but uses the `MarkdownContent` component so that people can provide markdown there too to link to other places, or just more rich content.

**Comment by voximity** [comment]
Perfect, thank you @benjdlambert! I'll see what I can come up with.

**Comment by benjdlambert** [comment]
Closing this as fixed!
