### ISSUE TITLE
🐛 Bug Report: Keyboard navigation to search filters

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#17610]
### 📜 Description

Using keyboard navigation, its not possible to navigate to the second filter group on the Search page and check "experimental" or "production" check boxes.

### 👍 Expected behavior

Be able to check "experimental" or "production" check boxes using keyboard navigation

### 👎 Actual Behavior with Screenshots

When navigating to search filters it skips over the second filter group and takes me to the search results directly after the select filters. 

<img width="1728" alt="Screenshot 2023-04-28 at 11 52 13" src="https://user-images.githubusercontent.com/25153114/235636779-b910be8f-31ba-454e-9b10-f059d739dfd5.png">

### 👟 Reproduction steps

Go to https://demo.backstage.io/search?query=&types%5B%5D=software-catalog

1. use your keyboard only to navigate through the page.
2. try to check the "experimental" or "production" check boxes

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by siddhant1** [comment]
Let me fix this!

**Comment by emmaindal** [comment]
Thats awesome @siddhant1 I'll assign you to the issue. Let us know if you have any questions. Thank you!
