### ISSUE TITLE
💬 RFC: Obtain the index of the rating button in StarredRatingButtons.

### ISSUE THREAD

**Issue by yuanfu111** [backstage/backstage#17625]
### 🔖 Need

Currently, the [StarredRatingButtons](https://github.com/backstage/backstage/blob/master/plugins/entity-feedback/src/components/StarredRatingButtons/StarredRatingButtons.tsx) is wrapped as a single component that consists of 5 star buttons. I want to know if the user just rated the component the same as before. If the user rated the component differently, a notification will be sent to the component owner. The issue now is I cannot obtain the index of the rating button so that I know what rating the user just gave.

### 🎉 Proposal

An endpoint to expose what rating the user just clicked. Maybe just the index of the star buttons.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by sennyeya** [comment]
Can you expand a little on your end goal here? Are you trying to send a notication outside of Backstage (email, SMS, push, etc) or would this be inside of the interface through the AlertApi? Does it have to happen at time of insert or is a polling based approach acceptable as well?

**Comment by yuanfu111** [comment]
> Can you expand a little on your end goal here? Are you trying to send a notication outside of Backstage (email, SMS, push, etc) or would this be inside of the interface through the AlertApi? Does it have to happen at time of insert or is a polling based approach acceptable as well?

Thank you for replying. Here we already have a notification sender inside the Backstage using alertApi. The notification happens whenever a user leaves or changes his/her rating so I will compare if there is a change between the current rating just clicked and the previous rating. So it is better event-driven instead of polling.

**Comment by freben** [comment]
Ping @kuangp here too

**Comment by freben** [comment]
I still don't fully get what the end goal is. Or rather - what is the _problem_ that you're solving? Your original problem statement revolves around "cannot obtain the index of the rating button", but that's not the actual problem is it, there's some other thing that you feel that this leads to. You mention alertApi, do you mean that if user A leaves a rating, than user B on another machine gets a popup about it?

If that's the case, then is the problem rather that events are being sent _at all_ when the rating didn't change? Should the sending end just add an `if (newRating !== oldRating)` check before persisting? Maybe that doesn't make sense, just checking.

**Comment by yuanfu111** [comment]
> I still don't fully get what the end goal is. Or rather - what is the _problem_ that you're solving? Your original problem statement revolves around "cannot obtain the index of the rating button", but that's not the actual problem is it, there's some other thing that you feel that this leads to. You mention alertApi, do you mean that if user A leaves a rating, than user B on another machine gets a popup about it?
> 
> If that's the case, then is the problem rather that events are being sent _at all_ when the rating didn't change? Should the sending end just add an `if (newRating !== oldRating)` check before persisting? Maybe that doesn't make sense, just checking.

You are right. I want to use `if (newRating !== oldRating)` check. What troubles me is how to obtain the newRating when the user just clicked. My idea is to give every star button an index representing the rating so that I can know the newRating by knowing which button the use clicked.

**Comment by kuangp** [comment]
At first glance, a simple way to achieve this might be to just add a `onChange` prop on the `StarredRatingButtons` component which gets called [here](https://github.com/backstage/backstage/blob/master/plugins/entity-feedback/src/components/StarredRatingButtons/StarredRatingButtons.tsx#L109) when the rating is changed. You can then pass a callback handler to the component to handle any such alerting behavior you want to define. The handler could also be passed the new rating if that value is necessary to inspect as well. 

Is this something you would be willing to contribute? 

Also, this may relate to the future [`notification API`](https://github.com/backstage/backstage/issues/10652) which this plugin may eventually tap into to publish such events to.

**Comment by yuanfu111** [comment]
> At first glance, a simple way to achieve this might be to just add a `onChange` prop on the `StarredRatingButtons` component which gets called [here](https://github.com/backstage/backstage/blob/master/plugins/entity-feedback/src/components/StarredRatingButtons/StarredRatingButtons.tsx#L109) when the rating is changed. You can then pass a callback handler to the component to handle any such alerting behavior you want to define. The handler could also be passed the new rating if that value is necessary to inspect as well.
> 
> Is this something you would be willing to contribute?
> 
> Also, this may relate to the future [`notification API`](https://github.com/backstage/backstage/issues/10652) which this plugin may eventually tap into to publish such events to.

That's great. I will create a PR for this feature!
