### ISSUE TITLE
🚀 Feature: <UnregisterEntityDialog /> allow to full delete an entity that spawned by a Location

### ISSUE THREAD

**Issue by kissmikijr** [backstage/backstage#17635]
### 🔖 Feature description

I propose an extension to the <UnregisterEntityDialog /> component to handle all Location entities the same as the entities coming from `locations`,
The current implementation treats entities that aren't coming from the DefaultLocationService as they would not have parent locations so it only offers to delete them but their Location entity would be left behind and on the next refresh cycle the entity will be spawned again.

The GithubEntityProvider works like this the provider emits Location entities and when these Locations are processed they emit the entities.

### 🎤 Context

I think this dialog should be able to delete every entity and its Location not only the ones that are added via the DefaultLocationService.

### ✌️ Possible Implementation

https://github.com/backstage/backstage/blob/021cfbb5152ccb97e008ff61ade65e71ceb48193/plugins/catalog-react/src/components/UnregisterEntityDialog/useUnregisterEntityDialogState.ts#L70

the useUnregisterEntityDialogState hook could fetch all of the Locations from the catalog via the CatalogApi.getEntities method instead of using the CatalogApi.getLocationByRef. The getLocationByRef only returns the locations that are added to the `locations` table. If it would fetch the locations from the catalog directly it would know about the actual `kind: Location` entities and it could handle all deletions.

Similar change would be needed for the actual deletion but here we should keep the original call to make sure if an entity got added by the DefaultLocationService it will be deleted from the `locations` table as well.  After the CatalogApi.removeLocationById call we could use the CatalogApi.removeEntityByUid to delete the entities. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
So this would likely need to use the `.../ancestry` endpoint to look up through the relations tree from the target, to ensure that we only have a single immediate `kind: Location` parent. And then you would probably need to query the entire catalog for entities that also are spawned out of that Location, so we don't inadvertently delete a parent that has two children, when all we wanted to do was to delete one of the children.

Is this a common case? Isn't it common that a Location is owned by some form of discovery-like mechanism anyway, and would be reconstructed soon after by the entity provider that sourced it originally?

**Comment by kissmikijr** [comment]
> Is this a common case? Isn't it common that a Location is owned by some form of discovery-like mechanism anyway, and would be reconstructed soon after by the entity provider that sourced it originally?

This is correct. In the current implementation of the backstage/backstage providers they would be reconstructed based on the source. However it can take some time becuase the deletion depends on the schedule you run your providers.

I think actually an even better solution would be to not allow to delete the entities that are sourced from outside of backstage.
Currently there is an option on this dialog to disable the unregister button in the menu but it disables for every entity I think.
 
Adding support for properly deleting every entity from the catalog could be useful when your providers/processing loops are configured to run on infrequently like once every 30 mintues. When you wanna cleanup something for example.

An entity that is coming from an entity provider will disappear from the catalog based on these:
- the cadence of your provider's full refresh
- the cadence of the refresh of the `generated-...` location entity

**Comment by freben** [comment]
So is this mainly about being faster to do something that would eventually happen anyway mostly? I can imagine some recovery scenarios too like after missing webhook events or similar.

Either way a thing like this needs some consideration on how it's built and how the user experience works out.

It should probably steer toward the "normal unregister" flow whenever possible, and then offer anything else only as a really advanced option full of warning texts and "Are you really sure" type messaging. Maybe it'd even need to be a little wizard that lets you see what the ancestry looks like and offering checkboxes to select how much to delete or something.

**Comment by kissmikijr** [comment]
> So is this mainly about being faster to do something that would eventually happen anyway mostly? 

In the current implementation of the GithubEntityProvider this is the case, that actually this deletion is not really needed as all of the providers are running on a schedule (even if they have the events listening enabled) and they do a `full` mutation on a schedule so eventually the state would be the same.

> I can imagine some recovery scenarios too like after missing webhook events or similar.

We modified a little bit this provider and we do not run `full` mutation ( we did this to use less rate limits). So for our case this deletion would be able to help to recover in case of a missed event.

> It should probably steer toward the "normal unregister" flow whenever possible, and then offer anything else only as a really advanced option full of warning texts and "Are you really sure" type messaging. Maybe it'd even need to be a little wizard that lets you see what the ancestry looks like and offering checkboxes to select how much to delete or something.

I agree, I like the idea of a wizard to be able to pick which entities you want from the ancestry tree. 🤔
