### ISSUE TITLE
🚀 Feature: pagerduty - ability to configure a homepage plugin

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#17646]
### 🔖 Feature description

It would be great if there was an ability to configure the pagerduty plugin on the backstage homepage. Instead of taking the integration key from an entity's annotation it could be passed in via a component prop.

### 🎤 Context

In some cases, companies have 1 on-call rota across the whole organization, so it makes more sense for the plugin to appear on the homepage rather than on the component page.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@punke this can be closed right?
