### ISSUE TITLE
💬 RFC: Independant UrlReaders in catalog template

### ISSUE THREAD

**Issue by The1hauntedX** [backstage/backstage#17642]
### 🔖 Need

If I register an API from a template stored in Gitlab, Bitbucket, Github, etc, I should be able to use a substitution in that references the API definition stored in a location separate the template location.

In this example with my API template stored in Gitlab, I cannot register the example API as shown in the [Substitutions In The Descriptor Format doc](https://backstage.io/docs/features/software-catalog/descriptor-format/#substitutions-in-the-descriptor-format) because the software catalog uses the `GitlabUrlReader` for both my Backstage template in Gitlab _**and**_ the substitution target, rather than identifying the appropriate `UrlReader` to use for the substitution (`FetchUrlReader` for https://petstore.swagger.io/v2/swagger.json).

The error output is a little misleading here...I have given my local (testing) environment `*` permissions for `backend.reading.allow`, however the issue ultimately lies in Backstage using the wrong UrlReader for the API specification.
![image](https://user-images.githubusercontent.com/13578289/236076542-245b89a7-bfb2-4060-8a91-46166c0ab318.png)

Let me know what y'all think! Is this expected behavior (Aligning with Backstage's philosophy of keeping entity metadata stored alongside its code)? Or is this a bug that should be addressed?

### 🎉 Proposal

Decouple the `UrlReader`s used to read external templates from any substitutions stored inside the template

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by jhaals** [comment]
Hi!
Sorry to hear that you're having problems. The URLReaders are designed to disallow reading from everywhere(`*`) since it wouldn't be very secure and open up for attacks by a malicious user. You can however configure prefix wildcards so in this case your template will work if you allow  `*.swagger.io` inside `backend.reading.allow`

**Comment by freben** [comment]
Alright, closing then! THanks.
