### ISSUE TITLE
🚀 Feature: Set Author for GitHub Pull Request

### ISSUE THREAD

**Issue by eytanhanig** [backstage/backstage#17644]
### 🔖 Feature description

Allow users to specify the author's name and email when opening a PR using the template action `publish:github:pull-request`.

### 🎤 Context

Implementing this would make the action `publish:github:pull-request` achieve greater parity with other similar actions that already support this feature, such as `publish:gitlab` and `github:repo:push`.

Having a company email associated with a commit & PR is mandatory at many organizations, and is often enforced using tests. Because the `publish:github:pull-request` action defaults to using the Primary email on the GitHub account, for many users (such as myself) this results in PRs that are impossible to merge.

### ✌️ Possible Implementation

Support this feature is as simple as upgrading a dependency and then adding inputs to an action:
1. Update `plugin-scaffolder-backend` to use version `4.1.0` or higher of its dependency `octokit-plugin-create-pull-request`, which [added support for `author` and `committer` options](https://github.com/gr2m/octokit-plugin-create-pull-request/releases/tag/v4.1.0).
2. Update [githubPullRequest.ts](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/githubPullRequest.ts) to take the inputs `gitAuthorName` and `gitAuthorEmail` and pass them to octokit.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by pc-bob** [comment]
Requesting that we re-open this issue. I think this would be useful. Looks like the 2 PRs to implement it did not quite make it across the line.

**Comment by freben** [comment]
Sure

**Comment by david-christ** [comment]
@freben I also currently stumbled upon this and would appreciate this to be implemented.

**Comment by saifelse** [comment]
It looks like this has been implemented by https://github.com/backstage/backstage/pull/24628

**Comment by cdavidnt** [comment]
> In case anyone stumbles upon this issue, it looks like this has been implemented by [#24628](https://github.com/backstage/backstage/pull/24628)

https://github.com/backstage/backstage/pull/24628 is not quite the same issue being fixed. The PR author remains the identity of the backstage application runner and the commits are associated to the individuals with those fields.

We should also be able to pass along the credentials of the user running the action to create the PR.
