### ISSUE TITLE
🐛 Bug Report: Azure EasyAuth

### ISSUE THREAD

**Issue by darrenyung** [backstage/backstage#17645]
### 📜 Description

Is there suppose to be something to be entered in the config file? The doc specifies it but no further information supplied.

https://backstage.io/docs/auth/microsoft/easy-auth#backstage-changes 

Current Azure Auth config I've set up is from this doc

https://backstage.io/docs/auth/microsoft/provider#configuration

### 👍 Expected behavior

Azure Login successfully

### 👎 Actual Behavior with Screenshots

After following the documentation, I get the following

```
Error: You do not appear to be signed in. Please try reloading the browser page

Error
ResponseError

Message
Request failed with 404 NotFoundError
```

![image](https://user-images.githubusercontent.com/9360520/236131473-c91c4b11-a650-4e9b-afb9-e2e2fee0e8bb.png)

### 👟 Reproduction steps

Follow config set up from this doc,

https://backstage.io/docs/auth/microsoft/provider

Follow up with changes from this page

https://backstage.io/docs/auth/microsoft/easy-auth

### 🖥️ Your Environment

OS:   Darwin 22.4.0 - darwin/x64
node: v16.13.0
yarn: 1.22.19
cli:  0.22.6 (installed)
backstage:  1.13.2

Dependencies:
  @backstage/app-defaults                               1.3.0
  @backstage/backend-app-api                            0.4.2
  @backstage/backend-common                             0.18.4
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.1
  @backstage/backend-tasks                              0.5.1
  @backstage/backend-test-utils                         0.1.36
  @backstage/catalog-client                             1.4.1
  @backstage/catalog-model                              1.3.0
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.0
  @backstage/cli                                        0.22.6
  @backstage/config-loader                              1.2.0
  @backstage/config                                     1.0.7
  @backstage/core-app-api                               1.7.0
  @backstage/core-components                            0.11.2, 0.13.0
  @backstage/core-plugin-api                            1.5.1
  @backstage/dev-utils                                  1.0.14
  @backstage/errors                                     1.1.5
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.2
  @backstage/integration-react                          1.1.12
  @backstage/integration                                1.4.4
  @backstage/plugin-api-docs                            0.9.2
  @backstage/plugin-app-backend                         0.3.44
  @backstage/plugin-auth-backend                        0.18.2
  @backstage/plugin-auth-node                           0.2.13
  @backstage/plugin-badges-backend                      0.1.38
  @backstage/plugin-badges                              0.2.41
  @backstage/plugin-bazaar-backend                      0.2.7
  @backstage/plugin-bazaar                              0.2.7
  @backstage/plugin-catalog-backend-module-github       0.2.7
  @backstage/plugin-catalog-backend                     1.9.0
  @backstage/plugin-catalog-common                      1.0.13
  @backstage/plugin-catalog-graph                       0.2.29
  @backstage/plugin-catalog-import                      0.9.7
  @backstage/plugin-catalog-node                        1.3.5
  @backstage/plugin-catalog-react                       1.5.0
  @backstage/plugin-catalog                             1.10.0
  @backstage/plugin-cost-insights-common                0.1.1
  @backstage/plugin-cost-insights                       0.12.6
  @backstage/plugin-entity-validation                   0.1.2
  @backstage/plugin-events-node                         0.2.5
  @backstage/plugin-explore-common                      0.0.1
  @backstage/plugin-explore-react                       0.0.28
  @backstage/plugin-explore                             0.4.2
  @backstage/plugin-github-actions                      0.5.17
  @backstage/plugin-github-issues                       0.2.6
  @backstage/plugin-github-pull-requests-board          0.1.11
  @backstage/plugin-home                                0.5.1
  @backstage/plugin-kubernetes-backend                  0.10.0
  @backstage/plugin-kubernetes-common                   0.6.2
  @backstage/plugin-kubernetes                          0.8.0
  @backstage/plugin-org                                 0.6.7
  @backstage/plugin-permission-common                   0.7.5
  @backstage/plugin-permission-node                     0.7.7
  @backstage/plugin-permission-react                    0.4.12
  @backstage/plugin-proxy-backend                       0.2.38
  @backstage/plugin-scaffolder-backend                  1.13.1
  @backstage/plugin-scaffolder-common                   1.2.7
  @backstage/plugin-scaffolder-node                     0.1.2
  @backstage/plugin-scaffolder-react                    1.3.0
  @backstage/plugin-scaffolder                          1.13.0
  @backstage/plugin-search-backend-module-catalog       0.1.0
  @backstage/plugin-search-backend-module-elasticsearch 1.2.0
  @backstage/plugin-search-backend-module-pg            0.5.5
  @backstage/plugin-search-backend-module-techdocs      0.1.0
  @backstage/plugin-search-backend-node                 1.2.0
  @backstage/plugin-search-backend                      1.3.0
  @backstage/plugin-search-common                       1.2.3
  @backstage/plugin-search-react                        1.5.2
  @backstage/plugin-search                              1.2.0
  @backstage/plugin-shortcuts                           0.3.9
  @backstage/plugin-sonarqube-backend                   0.1.9
  @backstage/plugin-sonarqube-react                     0.1.5
  @backstage/plugin-sonarqube                           0.6.6
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.28
  @backstage/plugin-tech-insights-backend               0.5.10
  @backstage/plugin-tech-insights-common                0.2.10
  @backstage/plugin-tech-insights-node                  0.4.2
  @backstage/plugin-tech-insights                       0.3.9
  @backstage/plugin-tech-radar                          0.6.3
  @backstage/plugin-techdocs-addons-test-utils          1.0.12
  @backstage/plugin-techdocs-backend                    1.6.1
  @backstage/plugin-techdocs-module-addons-contrib      1.0.12
  @backstage/plugin-techdocs-node                       1.7.0
  @backstage/plugin-techdocs-react                      1.1.5
  @backstage/plugin-techdocs                            1.6.1
  @backstage/plugin-todo-backend                        0.1.41
  @backstage/plugin-todo                                0.2.19
  @backstage/plugin-user-settings                       0.7.2
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.3.0
  @backstage/theme                                      0.2.19
  @backstage/types                                      1.0.2
  @backstage/version-bridge                             1.0.4
✨  Done in 3.47s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jhaals** [comment]
Hi, sorry to hear that you're having issues. Could you possibly see the 404 request being made in your browser by opening devtools? It would be good to know what it fails to access.

Perhaps @afscrome could shed some light on the setup needed for this provider.

**Comment by afscrome** [comment]
If you look at your browser's dev tools, there should be a call to `/api/auth/azure-easyauth/refresh`, any details on that response as to what's wrong.  Also check the server side logs - any errors around easy auth?

There are a bunch of App Service configuration issues that can cause the integration to not work, the server logs should tell you what's missing.  However I'd expect those to result in 500s, not 404s

**Comment by afscrome** [comment]
Looks like a config section is missing from the docs.  Can you ensure your app-config contains the following.

```yaml
auth:
  environment: development
  providers:
    azure-easyauth:
      development: { }
```

The easy auth plugin itself doesn't need any configuration (it gets it from App Service Environment variables), but backstage needs a section for it.  Without this section, backstage silently ignores hte provider without providing any errors.

**Comment by darrenyung** [comment]
Thank you @afscrome and @jhaals. I've updated the config as advised.

In regards to the error on the front page, the 404 error is coming when trying to hit `/api/auth/azure-easyauth/refresh`. 

The route on the backend is already setup as the app is currently using Github Auth. I'm trying to switchover to AzureAD as per company requirements.

**Comment by afscrome** [comment]
Yup, Azure Easy Auth is specifically only for deployments to Azure PASS services that support £Easy Auth (such as Azure App Services).

If running in another cloud, you should look towards that cloud's offering instead.  Google Identity-Aware Proxy may be appropriate for you.  An alternative is to follow 
https://backstage.io/docs/auth/google/gcp-iap-auth/
https://backstage.io/docs/auth/oauth2-proxy/provider

**Comment by darrenyung** [comment]
Thank you for your guidance. Will take a look at this. In the meantime, this issue can be closed now.

**Comment by phil1234567891011** [comment]
please improve doc as it is not clear if this is supposed to be used with on premise or cloud
how/where do we even set the target host ?
