### ISSUE TITLE
🐛 Bug Report: Lunr search returning weird results

### ISSUE THREAD

**Issue by carlos-martini-v** [backstage/backstage#17669]
### 📜 Description

When searching for certain things it seems that the lunar search implementation is a bit broken.  For example: when I search for stars it returns and highlights things such as stores and Tara.  [https://demo.backstage.io/search?query=stars&types%5B%5D=software-catalog ](https://demo.backstage.io/search?query=stars&types%5B%5D=software-catalog )

Another example would be searching for opa.  Things like Eva and api are returned and highlighted. [https://demo.backstage.io/search?query=opa&types%5B%5D=software-catalog](https://demo.backstage.io/search?query=opa&types%5B%5D=software-catalog)

### 👍 Expected behavior

I know Lunr is just meant for demo purposes but would expect the results to be somewhat accurate.  Results should somewhat match what's being search for.  It's a bit confusing what's actually coming back and why.

### 👎 Actual Behavior with Screenshots

https://demo.backstage.io/search?query=stars&types%5B%5D=software-catalog 
https://demo.backstage.io/search?query=opa&types%5B%5D=software-catalog

### 👟 Reproduction steps

1. Go to demo.backstage.io
2. search for stars or opa
3. Get back weird search results.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by githoober** [comment]
I have the same issue, search for the term 'misc' finds entries such as 'mess', 'lists', 'disco', 'list', 'ms', and some others.
