### ISSUE TITLE
🚀 Feature: Improve faceted Search with PgSearchEngine

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#17662]
### 🔖 Feature description

The PgSearchEngine should allow faceted search on fields that has multiple values, e.g. a `tags` field with a list of tags as value `["circleci", "ci", "dev"]`. So that one can narrow down a search based on one specific tag.

### 🎤 Context

When using search, its possible to narrow down your search results with filters to find what you are looking for faster. Something that the `ElasticSearchSearchEngine` supports today. But if you decide to use the PgSearchEngine this is an issue. It is today possible for any adopter to add their custom translator based on needs by overwriting [the default one](https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-pg/src/PgSearchEngine/PgSearchEngine.ts#L157-L173), however this feels like something that everyone using the PgSearchEngine can benefit from. 

### ✌️ Possible Implementation

I've limited experience of using postgres as a search engine, but been able to trace the issue down (I think) to how we handle field values https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-pg/src/database/DatabaseDocumentStore.ts#L170-L181 

For success, a query like `http://localhost:7007/api/search/query?types[]=tools&filters[tags]=ci` should return search results where for example the tags field include a `ci` value. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by rdeepc** [comment]
Hi @emmaindal,

I would like to work on this. Thanks

**Comment by rdeepc** [comment]
Hi @Rugvip @emmaindal ,

PR #17922 
I have created a PR to support field search in the array for this issue. Thanks
