### ISSUE TITLE
Explore using ProBot to manage auth for Plugins

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#1767]
## Feature Suggestion
- Following on from the RFC in #1565 it would be good to explore if using https://probot.github.io/ would be a good way of managing the app creation on a per plugin basis.
- Can plugins request to create an app in the users organisation with some predefined manifest
- Can we get webhooks working as predicted and do we have a nice way to store this information
- Can we also get access to a token that we can make requests with independent of the webhooks
    - IE, can we make a request outside of the webhook context that has the authorization of the application installation?

**Comment by adamdmharvey** [comment]
For context, relatively recently GitHub published a very nice flow chart for help in selecting the authentication type:

https://docs.github.com/en/free-pro-team@latest/developers/apps/about-apps

![image](https://user-images.githubusercontent.com/33203301/97516916-8eec2300-196a-11eb-9145-39ad5e6d43af.png)

I would suggest Probot is not the way to go, but agree PAT is not the path forward either.

There may still be use cases where either a GitHub App or an OAuth App may be valuable. I think it boils down to, does a plugin act as if it's Ben accessing GitHub (OAuth App), or does it act as Backstage to get data that Ben may (or may not) regularly have access to (a GitHub App).

There may be use cases for both, where you may want Backstage to respect whether or not Jane Doe can or can't get pull request data for a certain repo.  BUT you may also want plugins that do much broader info, for example calculating organizational statistics or metrics, where a GitHub App is preferred.

Not sure if that helps or complicates it, but I think those are likely the two paths forward now, and the new page GitHub posted above is really great with their new details.

**Comment by benjdlambert** [comment]
So I guess our thoughts internally is that in order to reduce complexity, the backend auth part of github would be powered by a github app and then that app could be installed into different organisations and different repositories in which it required authorization. 

Our idea is that the App should have enough scopes to do everything, but deployments for certain components would be based around ownership of those components.

Internally @ Spotify, every engineer can see deployments for every thing that's running, as well see graphs etc, but deploying through backstage is limited to only people that own that component.

Probot was an idea that we could use it to reduce some of the complexity of creating apps and the API for webhooks which will also need to be support for both local development and when backstage is deployed.

We have also thought about the idea that every plugin could have it's own Github App with it's own scopes, but we thought we'd start somewhere and start simple.

**Comment by benjdlambert** [comment]
Can close this now, as we have a solution for github apps.
