### ISSUE TITLE
🐛 Bug Report: Sourcemaps for typescript are broken

### ISSUE THREAD

**Issue by davjhan-doordash** [backstage/backstage#17676]
### 📜 Description

Stack traces on backend code show incorrect line numbers, making it very difficult to debug. It seems that stack traces for `.ts` are not working as intended.

This comment from rugvip in 2021 captures the problem perfectly:
https://github.com/backstage/backstage/pull/5368#pullrequestreview-639857555

### 👍 Expected behavior

Stack traces should show the correct line location.

### 👎 Actual Behavior with Screenshots

```
TypeError: Cannot set properties of undefined (setting 'allParentGroups')
[0]     at eval (webpack-internal:///../../plugins/catalog/catalog-backend-module-doordash/src/providers/doordashRelationsBuilder.ts:69:66)
[0]     at Array.forEach (<anonymous>)
[0]     at processRelations (webpack-internal:///../../plugins/catalog/catalog-backend-module-doordash/src/providers/doordashRelationsBuilder.ts:65:7)
[0]     at AssetsServiceEntityProvider.fullSync (webpack-internal:///../../plugins/catalog/catalog-backend-module-doordash/src/providers/AssetsServiceEntityProvider.ts:85:88)
```

This is a sample stack trace. `doordashRelationsBuilder.ts:65:7` is not near any callsite of trying to access the`.allParentGroups` property in that file.

### 👟 Reproduction steps

Create a backend project with typescript and throw an error and observe the stack trace.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jhaals** [comment]
Hi!

Just to confirm, which version of backstage and specifically the CLI are you on currently?

**Comment by davjhan-doordash** [comment]
Hi, 

we are using:

```
    "@backstage/cli": "^0.22.6-next.2",
```

As for the different plugins, they have different versions, but for the catalog-backend plugin in particular, it's

```
"@backstage/plugin-catalog-backend": "^1.8.1-next.2"
```

**Comment by benjdlambert** [comment]
@taras you were mentioned on the previous issue did you ever dig into this and work out what's going on? :pray:
