### ISSUE TITLE
🚀 Feature: Allow orphanCleanupIntervalMs to be configured

### ISSUE THREAD

**Issue by jen13501** [backstage/backstage#17670]
### 🔖 Feature description

I'd like to set orphanCleanupIntervalMs but it's not a value included in [CatalogBuilder](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/CatalogBuilder.ts#L523) and it's readonly in [DefaultCatalogProcessingEngine](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/processing/DefaultCatalogProcessingEngine.ts#L85)

### 🎤 Context

The default 30 seconds is too frequent for our use case and it spams the logs.

### ✌️ Possible Implementation

I'd add orphanCleanupIntervalMs to the config instead of passing it in through the constructor. Could also set it via a method in CatalogBuilder, similar to setProcessingIntervalSeconds. Is there a preference? 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jen13501** [comment]
I just submitted a [PR](https://github.com/backstage/backstage/pull/17673) with a new method since that is most backwards compatible but happy to do something different if prefered.

**Comment by jhaals** [comment]
Thanks for the suggestion!
The existing orphan cleanup strategy deliberately avoid referencing any form of schedule as it's an implementation detail that we preferably want to replace with immediate deletions but this was added as a stop-gap solution. Adding new methods on the builder specifically about cleanup scheduling would be harder to remove and replace given that we consider the APIs to be stable and would force us to release a new major version of catalog. 

To your point about spamming the logs, could we possibly reduce them somehow? I'm thinking if we could move output to debug as it might not be the most important information to log for users opting in to the behaviour

**Comment by jen13501** [comment]
That makes sense, thank you for sharing! Changing logs to debug would work for us. Another solution might be to log "0 orphans removed" as debug and anything > 0 is info.

**Comment by freben** [comment]
Oh totally, we shouldn't log the zeroes at least!

**Comment by benjdlambert** [comment]
Closing this as it looks fixed in #17673
