### ISSUE TITLE
🐛 Bug Report: EntityOwnerPicker failed to initialize: Request failed with 404 on `/catalog` page - related to "spec.profile.displayName" in payload for `entities/by-refs` api endpoint 

### ISSUE THREAD

**Issue by 0xStarcat** [backstage/backstage#17683]
### 📜 Description

On 1.13.0, when i go to `/catalog` in my browser, an error message pops up saying: `EntityOwnerPicker failed to initialize: Request failed with 404`. I've determined this happens because 1.13.0 is now hitting the `/catalog/entities/by-refs` endpoint on this page whereas my previous 1.11.0 version does not.

I can reproduce the 404 in both versions of backstage though by CURLing the endpoint. However, I noticed when I slightly modify the parameters to omit `spec.profile.displayName` from the fields, the endpoint works fine. 

[the standard payload](https://github.com/backstage/backstage/blob/a99f49567ad24679bca4f1b43ddd4681d7459236/plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx#L105):

```json
{
  "entityRefs": ["lots","of","refs"]
  "fields": ["kind", "metadata.name", "metadata.title", "metadata.namespace", "spec.profile.displayName"]
}
```

Note: this also happens in requests when `entityRefs` is empty!

To further complicate things, this endpoint works **just fine** on my localhost instance of backstage (on 1.13.0). 

Any help on figuring out a way to remove the error from popping up would be appreciated!

### 👍 Expected behavior

This error popup should not appear when visiting `/catalog`, and the `/catalog/entities/by-refs` endpoint shouldn't 404 

### 👎 Actual Behavior with Screenshots

<img width="1613" alt="Screen Shot 2023-05-05 at 10 41 57 PM" src="https://user-images.githubusercontent.com/17187192/236594449-9f7569cd-47e4-4122-a491-a8ba9f4f9af1.png">

This is the popup screenshot with the networking browser tools open to inspect the 404

### 👟 Reproduction steps

- have some entities populated (like the example ones and ones you've made from the example template)
- some of the component entities may have owners which are not actually linking to a user / group / any entity (ie, they 404 when clicking the svc-* owner link)
- on version 1.11.0+ visit `/catalog` 

### 📃 Provide the context for the Bug.

I caught this in middle of upgrading from 1.11.0 -> 1.13.0. The error message only appears in 1.13.0, but the api error occurs in 1.11.0 too.

This error message appears, which doesn't appear to affect functionality, but is nonetheless unexpected and makes things look bad :D 

might delay me upgrading to 1.13.0 in my production instance of backstage

### 🖥️ Your Environment

yarn backstage-cli info
yarn run v1.22.19

OS:   Darwin 21.6.0 - darwin/x64
node: v16.18.1
yarn: 1.22.19
cli:  0.22.6 (installed)
backstage:  1.13.2

Dependencies:
  @backstage/app-defaults                          1.3.0
  @backstage/backend-app-api                       0.4.2
  @backstage/backend-common                        0.18.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.1
  @backstage/backend-tasks                         0.5.1
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.6
  @backstage/config-loader                         1.2.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.7.0
  @backstage/core-components                       0.13.0, 0.9.5
  @backstage/core-plugin-api                       1.5.1
  @backstage/dev-utils                             1.0.14
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.12
  @backstage/integration                           1.4.4
  @backstage/plugin-api-docs                       0.9.2
  @backstage/plugin-app-backend                    0.3.44
  @backstage/plugin-auth-backend                   0.18.2
  @backstage/plugin-auth-node                      0.2.13
  @backstage/plugin-catalog-backend-module-gitlab  0.2.0
  @backstage/plugin-catalog-backend                1.9.0
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.29
  @backstage/plugin-catalog-import                 0.9.7
  @backstage/plugin-catalog-node                   1.3.5
  @backstage/plugin-catalog-react                  1.5.0
  @backstage/plugin-catalog                        1.10.0
  @backstage/plugin-github-actions                 0.5.17
  @backstage/plugin-org                            0.6.7
  @backstage/plugin-permission-backend             0.5.19
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.7
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.38
  @backstage/plugin-scaffolder-backend             1.13.1
  @backstage/plugin-scaffolder-common              1.2.7
  @backstage/plugin-scaffolder-node                0.1.2
  @backstage/plugin-scaffolder-react               1.3.0
  @backstage/plugin-scaffolder                     1.13.0
  @backstage/plugin-search-backend-module-catalog  0.1.0
  @backstage/plugin-search-backend-module-pg       0.5.5
  @backstage/plugin-search-backend-module-techdocs 0.1.0
  @backstage/plugin-search-backend-node            1.2.0
  @backstage/plugin-search-backend                 1.3.0
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.5.2
  @backstage/plugin-search                         1.2.0
  @backstage/plugin-tech-radar                     0.6.3
  @backstage/plugin-techdocs-backend               1.6.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.12
  @backstage/plugin-techdocs-node                  1.7.0
  @backstage/plugin-techdocs-react                 1.1.5
  @backstage/plugin-techdocs                       1.6.1
  @backstage/plugin-user-settings                  0.7.2
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.0
  @backstage/theme                                 0.2.19
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by sennyeya** [comment]
Can you share more about your set up? Is this happening in localhost, or in one of your higher environments? This is working as expected in [the demo site](https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned), so I expect it's a config issue/firewall/payload size issue. Can you share any backend logs of what's happening?

**Comment by 0xStarcat** [comment]
Hi! thanks for replying.

It could very well be a config issue. The api endpoint works fine in localhost and the issue is only happening in one of the higher environments. 

I'm not sure if it is relevant to the `/entities/by-refs` endpoint, but in the higher environments, we do have a custom `StaticPolicyChecker` to assign permissions based on a User's group so in the logs you'll see some custom console logs relating to who was granted what permissions w/ each request. In these environments, my user was given wildcard "*" access to all plugins, resources, and permissions. 

Other differences in our higher environments are that we are using a Google IAP proxy for login to provide the auth, identity & group claims, which we integrated with the `@backstage/plugin-auth-backend` plugin.

Here's some backend logs from one of the higher environments:


```
{"level":"info","message":" - - [06/May/2023:19:06:17 +0000] \"GET /api/catalog/entity-facets?facet=metadata.tags HTTP/1.1\" 304 - \"-\"\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36\"","service":"backstage","type":"incomingRequest"}                                                                                                                                │
│ {"level":"info","message":" - - [06/May/2023:19:06:18 +0000] \"POST /api/catalog/entities/by-refs HTTP/1.1\" - - \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36\"","service":"backstage","type":"incomingRequest"}                                                                                                                                                  │
│ User user:default/_<omitted>_ granted catalog access on "plugin" based on wildcard permission (*)                                                     │
│ User user:default/_<omitted>_ granted entity access on "resource" based on wildcard permission (*)                                                    │
│ User user:default/_<omitted>_ granted read access on "permission" based on wildcard permission (*)                                                    │
│ {"level":"info","message":"127.0.0.1 - - [06/May/2023:19:06:18 +0000] \"POST /api/permission/authorize HTTP/1.1\" 200 74 \"-\" \"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)\"","service":"backstage","type":"incomingRequest"}

```

the log for `POST /api/catalog/entities/by-refs` doesn't include a status code for some reason, even though on localhost the same log contains a 200. 

Let me know if I can provide any more information & thank you!

**Comment by 0xStarcat** [comment]
Sidenote: most/all of our `User` entities don't have `spec.profile.displayName` specified in the YAML. would this cause a problem with the endpoint?

**Comment by sennyeya** [comment]
Does the status code not show with both CURL and the web request? Can you share the response body/status code? Your original screenshots just have the output, but the full might be more helpful.

That shouldn't cause issues, the `fields` query param is just use for resolving fields on the JSON of your entity and wouldn't cause the issue.

**Comment by 0xStarcat** [comment]
Correct, the status code for the 404s do not appear in the backend logs with either the curl or the web request.

The status code does appear in the response though:

```sh
curl 'https://backstage.dev.mvnapp.net/api/catalog/entities/by-refs' \
-H 'content-type: application/json' \
...<omitted sensitive headers>...
--data-raw '{"entityRefs":[],"fields":["kind","metadata.name","metadata.title","metadata.namespace","spec.profile.displayName"]}' \
--compressed
```
```sh
<!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>404</title>404 Not Found

```

And in the browser dev-tools its the same:

<img width="1025" alt="Screen Shot 2023-05-06 at 4 27 50 PM" src="https://user-images.githubusercontent.com/17187192/236645361-bdaadc96-bc95-4154-ac24-d3520bb19c66.png">

**Comment by sennyeya** [comment]
Weird, running those commands against localhost gives no response. Is it possible you have a firewall or something that isn't allowing that endpoint to be called? Weird that it's showing in the logs, but I don't think the error handling is happening in the application. 

Here's the output I get for `➜ curl 'localhost:7007/api/catalog/entities/123' \       
-H 'content-type: application/json' -v  \
--data-raw '{"entityRefs":[],"fields":["kind","metadata.name","metadata.title","metadata.namespace","spec.profile.displayName"]}' \
--compressed`

```
*   Trying 127.0.0.1:7007...
* Connected to localhost (127.0.0.1) port 7007 (#0)
> POST /api/catalog/entities/123 HTTP/1.1
> Host: localhost:7007
> User-Agent: curl/7.84.0
> Accept: */*
> Accept-Encoding: deflate, gzip
> content-type: application/json
> Content-Length: 116
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Security-Policy: default-src 'self';base-uri 'self';font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self' 'unsafe-eval';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests;connect-src 'self' http: https:
< X-DNS-Prefetch-Control: off
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=15552000; includeSubDomains
< X-Download-Options: noopen
< X-Content-Type-Options: nosniff
< X-Permitted-Cross-Domain-Policies: none
< Referrer-Policy: no-referrer
< X-XSS-Protection: 0
< Date: Sat, 06 May 2023 20:59:51 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
```

The endpoint is not a real endpoint, but just to demonstrate the expected return value for a missing route.

**Comment by 0xStarcat** [comment]
Very interesting! I'll have to check the infrastructure on Monday - I agree that this HTML 404 response is very uncharacteristic of a backstage backend API response serving JSON, and it's possible that something else could be returning that response.

**Comment by sennyeya** [comment]
Sounds good, here's the [notFound middleware](https://github.com/backstage/backstage/blob/a99f49567ad24679bca4f1b43ddd4681d7459236/packages/backend-app-api/src/http/MiddlewareFactory.ts#L105) for reference, which just sets the status.

**Comment by 0xStarcat** [comment]
Update: you were right! This 404 is a result of a false positive from our newly configured WAF (web app firewall) rules. Specifically the `lfi-canary` group and rule `owasp-crs-v030001-id930120-lfi`. The description described it as an `OS File Access Attempt`.

Apparently this rule can't tell the difference between a YAML path and an OS file path in the payload 😓 . The solution on our end is going to be re-configuring the WAF rules and potentially allowlisting this endpoint.

Thank you for helping me through debugging this! I'll close this issue.
