### ISSUE TITLE
🐛 Bug Report: Google Calendar Plugin Refresh With Scopes Causes Sign-out

### ISSUE THREAD

**Issue by benjmac** [backstage/backstage#17703]
### 📜 Description

The google calendar plugin isn't passing all the required scopes in order for the refresh to be completed. It will error out with a 401 due to an additional scope missing, which should be passed. In order to reproduce, you can login, then hard refresh the page in order for the refresh to take place, you will then see a 401 Invalid Credentials error and the user is logged out. This was introduced in the 1.13.0 upgrade when scopes started being passed to the refresh API.  With a little digging, it turns out you also have to request the `https://www.googleapis.com/auth/userinfo.email` scope as well as the calendar scope. Google returns the email in the credentials hash and thus, I believe, if you haven't requested access to it you can't read it. I made this change in my local repo and confirmed it resolves the issue.

https://github.com/backstage/backstage/blob/master/docs/releases/v1.13.0-changelog.md#backstagecore-app-api170

### 👍 Expected behavior

User should be a able to log into the google calendar plugin, refresh or revisit the page and have the refresh API be successful to keep them logged in.

### 👎 Actual Behavior with Screenshots

User logs in, closes and revisits, or hard refreshes page, and the user will be logged out of the google calendar plugin.

<img width="860" alt="Screenshot 2023-05-08 at 12 44 48 PM" src="https://user-images.githubusercontent.com/25201407/236881785-ff7418f2-792b-496b-9445-25f641196106.png">

Here is the error stack:
`"UserInfoError: Invalid Credentials\n    at /app/node_modules/passport-google-oauth20/lib/strategy.js:97:21\n    at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)\n    at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)\n    at IncomingMessage.emit (node:events:525:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"`

### 👟 Reproduction steps

1. Login the google calendar plugin.
2. Hard refresh, or close and revisit, the page. Then you will see the failed refresh call. 

### 📃 Provide the context for the Bug.

The issue is causing users to be frustrated with having to log in every time they visit home page plugin. In addition, elevated errors within our application. In short, want to correct and enhance the user experience.

https://github.com/backstage/backstage/blob/master/docs/releases/v1.13.0-changelog.md#backstagecore-app-api170

Error is coming from this hook in the plugin
https://github.com/backstage/backstage/blob/master/plugins/gcalendar/src/hooks/useSignIn.ts#L28

Resolved would look like this, by only adding the email scope as well.

<img width="540" alt="Screenshot 2023-05-08 at 12 58 52 PM" src="https://user-images.githubusercontent.com/25201407/236884748-78aebdbb-d9ff-4808-9abc-9c63c6665a72.png">

### 🖥️ Your Environment

OS:   Darwin 22.4.0 - darwin/x64
node: v16.14.0
yarn: 1.22.17
cli:  0.22.6 (installed)
backstage:  1.13.2

Dependencies:
  @backstage/app-defaults                               1.3.0
  @backstage/backend-app-api                            0.4.2
  @backstage/backend-common                             0.18.4
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.1
  @backstage/backend-tasks                              0.5.1
  @backstage/catalog-client                             1.4.1
  @backstage/catalog-model                              1.3.0
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.0
  @backstage/cli                                        0.22.6
  @backstage/config-loader                              1.2.0
  @backstage/config                                     1.0.7
  @backstage/core-app-api                               1.7.0
  @backstage/core-components                            0.12.5, 0.13.0
  @backstage/core-plugin-api                            1.5.1
  @backstage/dev-utils                                  1.0.14
  @backstage/errors                                     1.1.5
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.2
  @backstage/integration-react                          1.1.12
  @backstage/integration                                1.4.4
  @backstage/plugin-api-docs                            0.9.2
  @backstage/plugin-app-backend                         0.3.44
  @backstage/plugin-auth-backend                        0.18.2
  @backstage/plugin-auth-node                           0.2.13
  @backstage/plugin-catalog-backend-module-github       0.2.7
  @backstage/plugin-catalog-backend                     1.9.0
  @backstage/plugin-catalog-common                      1.0.13
  @backstage/plugin-catalog-graph                       0.2.29
  @backstage/plugin-catalog-import                      0.9.7
  @backstage/plugin-catalog-node                        1.3.5
  @backstage/plugin-catalog-react                       1.5.0
  @backstage/plugin-catalog                             1.10.0
  @backstage/plugin-events-node                         0.2.5
  @backstage/plugin-gcalendar                             0.3.13
  @backstage/plugin-github-actions                      0.5.17
  @backstage/plugin-github-pull-requests-board          0.1.11
  @backstage/plugin-home                                0.5.0, 0.5.1
  @backstage/plugin-org                                 0.6.7
  @backstage/plugin-permission-backend                  0.5.19
  @backstage/plugin-permission-common                   0.7.5
  @backstage/plugin-permission-node                     0.7.7
  @backstage/plugin-permission-react                    0.4.12
  @backstage/plugin-playlist-backend                    0.3.0
  @backstage/plugin-playlist-common                     0.1.6
  @backstage/plugin-playlist                            0.1.8
  @backstage/plugin-proxy-backend                       0.2.38
  @backstage/plugin-scaffolder-backend                  1.13.1
  @backstage/plugin-scaffolder-common                   1.2.7
  @backstage/plugin-scaffolder-node                     0.1.2
  @backstage/plugin-scaffolder-react                    1.3.0
  @backstage/plugin-scaffolder                          1.13.0
  @backstage/plugin-search-backend-module-catalog       0.1.0
  @backstage/plugin-search-backend-module-elasticsearch 1.2.0
  @backstage/plugin-search-backend-module-pg            0.5.5
  @backstage/plugin-search-backend-module-techdocs      0.1.0
  @backstage/plugin-search-backend-node                 1.2.0
  @backstage/plugin-search-backend                      1.3.0
  @backstage/plugin-search-common                       1.2.3
  @backstage/plugin-search-react                        1.5.2
  @backstage/plugin-search                              1.2.0
  @backstage/plugin-sonarqube-backend                   0.1.9
  @backstage/plugin-sonarqube-react                     0.1.5
  @backstage/plugin-sonarqube                           0.6.6
  @backstage/plugin-tech-radar                          0.6.3
  @backstage/plugin-techdocs-addons-test-utils          1.0.12
  @backstage/plugin-techdocs-backend                    1.6.1
  @backstage/plugin-techdocs-module-addons-contrib      1.0.12
  @backstage/plugin-techdocs-node                       1.7.0
  @backstage/plugin-techdocs-react                      1.1.5
  @backstage/plugin-techdocs                            1.6.1
  @backstage/plugin-user-settings                       0.7.2
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.3.0
  @backstage/theme                                      0.2.19
  @backstage/types                                      1.0.2
  @backstage/version-bridge                             1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
https://github.com/backstage/backstage/pull/17704

**Comment by freben** [comment]
Closed by #17704
