### ISSUE TITLE
🚀 Feature: Error name handling

### ISSUE THREAD

**Issue by idakucamupeva** [backstage/backstage#17718]
### 🔖 Feature description

In this feature, I want to propose better error handling, specifically for the classes described here https://backstage.io/docs/reference/errors/. As much as I have looked into the code, those classes are just serving as name handlers(e.g. CustomErrorBase class just reads the name of the class that is extending it and writes it down in the error message by setting `this.name = this.constructor.name;` in its constructor). Your current implementation: 

https://github.com/backstage/backstage/blob/master/packages/errors/src/errors/common.ts

and

https://github.com/backstage/backstage/blob/master/packages/errors/src/errors/CustomErrorBase.ts#L56

### 🎤 Context

The problem with this approach starts after obfuscation or minification of the code when class names are given some random characters(e.g. "w" like in the image I am attaching) so the error alert starts looking meaningless and ugly.
![Screenshot_2](https://github.com/backstage/backstage/assets/61310737/da0edce6-ac48-42a1-8d8c-0619a1c276e5)

### ✌️ Possible Implementation

In this example, I am just implementing the necessary for my use case(**giving classes the name attribute instead of referencing their actual name**), but this could also be extended in some other way. This implementation shows the right error name displayed even after obfuscation or minification of the code.

```javascript
diff --git a/node_modules/@backstage/errors/dist/index.cjs.js b/node_modules/@backstage/errors/dist/index.cjs.js
index c27afdc..0129203 100644
--- a/node_modules/@backstage/errors/dist/index.cjs.js
+++ b/node_modules/@backstage/errors/dist/index.cjs.js
@@ -73,24 +73,52 @@ class CustomErrorBase extends Error {
     }
     super(fullMessage);
     (_a = Error.captureStackTrace) == null ? void 0 : _a.call(Error, this, this.constructor);
-    this.name = this.constructor.name;
+    this.name = 'Error';
     this.cause = isError(cause) ? cause : void 0;
   }
 }
 
 class InputError extends CustomErrorBase {
+  constructor(message, cause) {
+    super(message, cause);
+    this.name = 'InputError';
+  }
 }
 class AuthenticationError extends CustomErrorBase {
+  constructor(message, cause) {
+    super(message, cause);
+    this.name = 'AuthenticationError';
+  }
 }
 class NotAllowedError extends CustomErrorBase {
+  constructor(message, cause) {
+    super(message, cause);
+    this.name = 'NotAllowedError';
+  }
 }
 class NotFoundError extends CustomErrorBase {
+  constructor(message, cause) {
+    super(message, cause);
+    this.name = 'NotFoundError';
+  }
 }
 class ConflictError extends CustomErrorBase {
+  constructor(message, cause) {
+    super(message, cause);
+    this.name = 'ConflictError';
+  }
 }
 class NotModifiedError extends CustomErrorBase {
+  constructor(message, cause) {
+    super(message, cause);
+    this.name = 'NotModifiedError';
+  }
 }
 class NotImplementedError extends CustomErrorBase {
+  constructor(message, cause) {
+    super(message, cause);
+    this.name = 'NotImplementedError';
+  }
 }
 class ForwardedError extends CustomErrorBase {
   constructor(message, cause) {
```

It is possible that I am misusing the classes in some way and if that is the case, could you tell me the recommended way to approach this issue?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Makes sense! Are you able to make a PR? 🙏

**Comment by idakucamupeva** [comment]
Yes, I will make it in the week that is after the next one(22 May-26 May). Thank you a lot for the fast response!
