### ISSUE TITLE
🐛 Bug Report: Okta Provider doesn't seems to have option to add custom scopes

### ISSUE THREAD

**Issue by panditha** [backstage/backstage#17724]
### 📜 Description

Okta Auth Provider doesn't seems to be having an option to provide custom scope while requesting for access token. 

### 👍 Expected behavior

Okta Auth Provider must provide an option to provide custom scopes while configuring.

### 👎 Actual Behavior with Screenshots

The currently Okta provider configuration doesn't have option to add custom scope.

### 👟 Reproduction steps

Current documentation in Back stage doesn't provide where we can provide custom scopes.

### 📃 Provide the context for the Bug.

Our enterprise identity is Okta and it requires to pass a custom scope in order to get groups member ship information to be provided.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Hi! Scopes are chosen by the calling code; the client side picks the set of scopes that it wants to request a token for. Are you saying that _in addition_ to that you want some form of an extraScopes parameter or similar that's always added on top of whatever the caller requests, no matter what?

And just to double check - are we talking about the `oktaAuthApiRef` being used here? It has a [certain set of default scopes](https://github.com/backstage/backstage/blob/667c490cc10fdb6dea06ccfe7ef2ab92364d7d45/packages/core-app-api/src/apis/implementations/auth/okta/OktaAuth.ts#L52); is yours a new one separate from these?

**Comment by panditha** [comment]
Yes. I am referring to **oktaAuthApiRef** which has  defaultScopes = ['openid', 'email', 'profile', 'offline_access'], but in our we need to add a custom scope for example something like **backstage.groups** but we don't find a way to do this while using oktaAuthApiRef.

I didn't get your point that **"Hi! Scopes are chosen by the calling code; the client side picks the set of scopes that it wants to request a token for. "** I don't see where in client side I can pass additional scopes while initiating a token request.

Is there a way to add additional scopes without doing whole custom implementation of oktaAuthApiRef ?

**Comment by freben** [comment]
[This is the signature](https://github.com/backstage/backstage/blob/4ba256846f0beb18dde458eca24238c4ed4b974b/packages/core-plugin-api/src/apis/definitions/auth.ts#L129) for getting an authorization token. The comment in there goes into some more detail. See also [here in the MS calendar plugin](https://github.com/backstage/backstage/blob/4ba256846f0beb18dde458eca24238c4ed4b974b/plugins/microsoft-calendar/src/hooks/useSignIn.ts#L27) where they leverage this.

If you still want to replace the _default_ scopes (which are always _in addition to_ the explicitly requested ones), then no, you have to replace the api factory indeed. But it's really easy. Copy paste [the default one](https://github.com/backstage/backstage/blob/4ba256846f0beb18dde458eca24238c4ed4b974b/packages/app-defaults/src/defaults/apis.ts#L170), add the default scopes argument to `OktaAuth.create`, and slap that in your `packages/app/src/apis.ts`.

**Comment by panditha** [comment]
Hi,
This did help us and thanks for the inputs. I was able to make it work by overriding api factory and adding it to "packages/app/src/apis.ts". 

However I have a query. 
Do we also need to add to the providerFactories in  **/packages/backend/src/plugins/auth.ts**?  Because it is working irrespective of whether I add in auth.ts or not.  We didn't understand how it is working and does it have any internal implications later?

Thanks in advance for the help.

**Comment by benjdlambert** [comment]
Hey :wave:

Not if you override on that already exists. Did yours not exist in there already

**Comment by panditha** [comment]
Here are my files 

packages\app\src\apis.ts:

![image](https://github.com/backstage/backstage/assets/1615122/9893f33a-9c82-4b6a-ae2a-7759674ba42a)

packages\backend\src\plugins\auth.ts:

![image](https://github.com/backstage/backstage/assets/1615122/bb419ca4-4bf7-473d-a8ae-f7f07a300c17)

The observation is that in auth.ts even if I comment out line number 87 still I am able to perform OAuth process get access token with custom scope defined in api.ts.

Apart from above, I observed another issue. After logging to Microsoft and getting the token, If I refresh the web page in browser my access token lost and again I have to go through OAtuth sign process. When I debug in network traffic in browser (screenshot below) I see that call to https://localhost:7007/api/auth/microsoft/refresh?optional&env=development is failing with 401 error. 

![image](https://github.com/backstage/backstage/assets/1615122/51ae8142-b08f-4fe3-a926-dc556abf8f37)

Any Idea what I am doing wrong here?

**Comment by LZING** [comment]
May I ask if you have solved this problem, do you have any ideas? We also return a 401 error when refreshing, and the error content: the refresh token is also invalid

**Comment by freben** [comment]
I think you need to add an offline scope to your token requests to be able to use refreshes, I think.

**Comment by LZING** [comment]
Yes, I've tried it and it doesn't require a login anymore

**Comment by Rugvip** [comment]
@panditha regarding your first observation, that's intended. It's because the microsoft auth provider is installed by default. It will only be active if you give it config though.

Regarding the second observation, access is lost because you no longer include the `'offline_access'` scope in the set of default scopes for the `MicrosofyAuth` provider. When you configure a new set of default scopes that completely replaces the old ones.

In general anyone that is facing problems with session refreshes after configuring a custom set of default scopes for an auth provider should make sure that the new scopes provide the necessary scopes to receive a refresh token, often called "offline access"

**Comment by panditha** [comment]
@Rugvip , Thank you. offline_access solved the probem.
