### ISSUE TITLE
🐛 Bug Report: Regression scaffolder action with combided zod schemas fails validation

### ISSUE THREAD

**Issue by Andy2003** [backstage/backstage#17721]
### 📜 Description

Given the schema ([adjusted from tests](https://github.com/backstage/backstage/blob/9ab7a4b5382fb225226fd3537efe225cc96b71a0/plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.test.ts#L121-L133)):

```typescript
      createTemplateAction({
        id: 'jest-zod-validated-action',
        description: 'Mock action for testing',
        handler: fakeActionHandler,
        supportsDryRun: true,
        schema: {
          input: z
            .object({
              foo: z.number(),
            })
            .and(z.object({ bar: z.string() })),
        },
      })
```

The following input:

```typescript
{ foo: 1, bar: 'bar' }
```

results in an validation error:

> InputError: Invalid input passed to action jest-zod-validated-action, instance does not match allOf schema [subschema 0] with 1 error[s]:, instance is not allowed to have the additional property "bar", instance does not match allOf schema [subschema 1] with 1 error[s]:, instance is not allowed to have the additional property "foo"

This is because the zod schema is converted to the following JsonSchema:

```json
{
  "allOf": [
    {
      "type": "object",
      "properties": {
        "foo": {
          "type": "number"
        }
      },
      "required": [
        "foo"
      ],
      "additionalProperties": false
    },
    {
      "type": "object",
      "properties": {
        "bar": {
          "type": "string"
        }
      },
      "required": [
        "bar"
      ],
      "additionalProperties": false
    }
  ],
  "$schema": "http://json-schema.org/draft-07/schema#"
}
```

The Problem is, that the `additionalProperties` in both `allOf`-schemas resullts in failing each separate sub-schema validation. This seems to be a [common problem in JsonSchema-Validation](https://stackoverflow.com/a/23001194/1666829).

To fix such issues, one can use `nonstrict()` on each of the combined zod schemas, like:

```typescript
z
    .object({
        foo: z.number(),
    })
    .nonstrict()
.and(
    z.object({ bar: z.string() })
      .nonstrict()
)
```

But with this in place, the user can add additional keys to the input, like:

```typescript
{ foo: 1, bar: 'bar', x: 1 }
```

The JSON-Schema which is validating everything as expected looks like:

```json
{
  "allOf": [
    {
      "type": "object",
      "properties": {
        "foo": {
          "type": "number"
        }
      },
      "required": [
        "foo"
      ],
    },
    {
      "type": "object",
      "properties": {
        "bar": {
          "type": "string"
        }
      },
      "required": [
        "bar"
      ],
    }
  ],
  "$schema": "http://json-schema.org/draft-07/schema#",
  "unevaluatedProperties": false
}
```

Note the `unevaluatedProperties` and the missing `additionalProperties`.

---

Since we already introduced the `and` operation in #16990 for the next release, this issue is an regression for:

- gitlab:group:ensureExists
- gitlab:projectAccessToken:create
- gitlab:projectDeployToken:create
- gitlab:projectVariable:create

### 👍 Expected behavior

scaffolder actions with intersected zod schemas as input should validate correctly

### 👎 Actual Behavior with Screenshots

see description

### 👟 Reproduction steps

see description

### 📃 Provide the context for the Bug.

Zod-Schema with intersected input types

### 🖥️ Your Environment

backstage 1.13, 1.14-next

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Yeah I see. Indeed, `.and` doesn't look to be the right thing here. Looking at your ticket, I believe `.intersection` is the exact same. The way that zod works, it totally makes sense that it'd generate the JSONSchema it does.

Could you look into using [merge](https://github.com/colinhacks/zod#merge) instead of `and`? 🙏  That's the semantic operation we want to perform, not multiple strict but distinct schemas applying at the same time.
