### ISSUE TITLE
🐛 Bug Report: Link to PDF doesn't throws 404 error

### ISSUE THREAD

**Issue by grvpandey11** [backstage/backstage#17734]
### 📜 Description

I have a reference to PDF in my docs/onboarding.md file as below
**For reference:** 
```
This is a basic example of documentation. [here](./assets/onboarding.pdf)
```

When I click on it I am getting 404 error.
Is there any way to render the content of the PDF on the page

### 👍 Expected behavior

PDF should open on Techdocs page.

### 👎 Actual Behavior with Screenshots

It throws 404 Not Found

### 👟 Reproduction steps

1. Upload a pdf file under docs/assets/<file-name.pdf>
2. Use the PDF file reference in any .md file  as below
  ```
  This is a basic example of documentation. [here](./assets/onboarding.pdf)
  ```
3. Import the component in Backstage, visit component Techdocs and click on "here" hyperlink.
4. It will give you 404 error

### 🖥️ Your Environment

node: v16.15.0
yarn: 1.22.19
cli:  0.22.5 (installed)
backstage:  1.12.1
```
Dependencies:
  @backstage/app-defaults                          1.2.1
  @backstage/backend-app-api                       0.4.1 
  @backstage/backend-common                        0.18.3
  @backstage/backend-dev-utils                     0.1.1 
  @backstage/backend-plugin-api                    0.5.0 
  @backstage/backend-tasks                         0.5.0 
  @backstage/catalog-client                        1.4.0 
  @backstage/catalog-model                         1.2.1 
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.22.5
  @backstage/config-loader                         1.1.9 
  @backstage/config                                1.0.7 
  @backstage/core-app-api                          1.6.0 
  @backstage/core-components                       0.12.5
  @backstage/core-plugin-api                       1.5.0 
  @backstage/dev-utils                             1.0.13
  @backstage/errors                                1.1.5 
  @backstage/eslint-plugin                         0.1.2 
  @backstage/integration-aws-node                  0.1.2 
  @backstage/integration-react                     1.1.11
  @backstage/integration                           1.4.3 
  @backstage/plugin-api-docs                       0.9.1 
  @backstage/plugin-app-backend                    0.3.43
  @backstage/plugin-auth-backend                   0.18.1
  @backstage/plugin-auth-node                      0.2.12
  @backstage/plugin-catalog-backend-module-github  0.2.6 
  @backstage/plugin-catalog-backend                1.8.0 
  @backstage/plugin-catalog-common                 1.0.12
  @backstage/plugin-catalog-graph                  0.2.28
  @backstage/plugin-catalog-import                 0.9.6
  @backstage/plugin-catalog-node                   1.3.4
  @backstage/plugin-catalog-react                  1.4.0
  @backstage/plugin-catalog                        1.9.0
  @backstage/plugin-events-node                    0.2.4
  @backstage/plugin-github-actions                 0.5.16
  @backstage/plugin-home                           0.4.32
  @backstage/plugin-org                            0.6.6
  @backstage/plugin-permission-common              0.7.4
  @backstage/plugin-permission-node                0.7.6
  @backstage/plugin-permission-react               0.4.11
  @backstage/plugin-proxy-backend                  0.2.37
  @backstage/plugin-scaffolder-backend             1.12.0
  @backstage/plugin-scaffolder-common              1.2.6
  @backstage/plugin-scaffolder-node                0.1.1
  @backstage/plugin-scaffolder-react               1.2.0
  @backstage/plugin-scaffolder                     1.12.0
  @backstage/plugin-search-backend-module-pg       0.5.4
  @backstage/plugin-search-backend-node            1.1.4
  @backstage/plugin-search-backend                 1.2.4
  @backstage/plugin-search-common                  1.2.2
  @backstage/plugin-search-react                   1.5.1
  @backstage/plugin-search                         1.1.1
  @backstage/plugin-sentry                         0.5.1
  @backstage/plugin-stack-overflow-backend         0.1.12
  @backstage/plugin-stack-overflow                 0.1.12
  @backstage/plugin-tech-radar                     0.6.2
  @backstage/plugin-techdocs-backend               1.6.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.11
  @backstage/plugin-techdocs-node                  1.6.0
  @backstage/plugin-techdocs-react                 1.1.4
  @backstage/plugin-techdocs                       1.6.0
  @backstage/plugin-user-settings                  0.7.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.2.6
  @backstage/theme                                 0.2.18
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by MonicaG** [comment]
I am having the same issue. Is there a work around for this?

**Comment by MonicaG** [comment]
The workaround I found was to add the download attribute as discussed in issue #13940.

I did notice one curiosity when using the download attribute. When running backstage locally on my machine, the PDF would display in a new tab. However, in the deployed version (runs on OpenShift), the PDF file would download instead. Both local and the deployed version use the same file in the object storage.

The files are published to the object storage via the techdocs-cli tool. The files in the object store have a content-type of application/octet-stream.

Downloading the file is an ok work-around. But it would be nice to view the PDF in the browser.

**Comment by MonicaG** [comment]
Would still like this to be resolved, if possible.

**Comment by agentbellnorm** [comment]
@MonicaG Can you try using `[a document](./assets/doc.pdf){: download target="_blank"}`? My hope is that this will make the file open in a new tab also in your production environment.

If this doesn't work, could you also confirm that the behavior persists across browsers and make sure no plugins are interfering?

**Comment by MonicaG** [comment]
@agentbellnorm - Thanks! I updated to use the `[a document](./assets/doc.pdf){: download target="_blank"}` code as suggested. 

In FireFox it opened a new tab and dowloaded. In Safari and Chrome it did NOT open a new tab. It only downloaded the file.

**Comment by MonicaG** [comment]
> @agentbellnorm - Thanks! I updated to use the `[a document](./assets/doc.pdf){: download target="_blank"}` code as suggested.
> 
> In FireFox it opened a new tab and dowloaded. In Safari and Chrome it did NOT open a new tab. It only downloaded the file.

Also noticed the file is downloaded as download.pdf vs the file's name

**Comment by martinus** [comment]
Through trial and error I found out that its possible to specify the download name like so:

```md
[a document](./assets/doc.pdf){: download="doc.pdf"}
```

Which is unfortunately completely unintuitive

**Comment by vinzscam** [comment]
Perhaps there is an opportunity to document this in https://backstage.io/docs/features/techdocs/how-to-guides
