### ISSUE TITLE
🔌 Plugin: Break out a `@backstage/plugin-home-react`

### ISSUE THREAD

**Issue by freben** [backstage/backstage#17737]
### 🔖 Summary

The `@backstage/plugin-home` package exports some symbols, in particular `createCardExtension` and the types that come out of it, which other plugins might be interested in importing. That function and its types should be exported instead from a new `@backstage/plugin-home-react` package, and deprecated in their old place, so that plugins don't need to import plugins (which isn't normally allowed).

### 🌐 Project website (if applicable)

https://github.com/backstage/backstage/tree/master/plugins/home

### ✌️ Context

See for example #17692, in which the pagerduty plugin ends up importing the entire home plugin instead of a `-react` package, because it wants to expose home page features.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by kmarkow** [comment]
Hello!

I'd like to work on this but want to clarify the requirements.

- [ ] Create a new @backstage/plugin-home-react package
- [ ] Move following functions to the new package createCardExtension, CardExtensionProps, ComponentParts, ComponentRenderer, RendererProps, CardLayout,  CardSettings
- [ ] Update imports to refer to the new package

Let me know if this is what is expected here.

**Comment by malikahmontgomery** [comment]
@freben @kmarkow 

Agreed changes have been added to [Pull request](https://github.com/backstage/backstage/pull/17806)
