### ISSUE TITLE
🚀 Feature: support for mkdocs-autolinks-plugin

### ISSUE THREAD

**Issue by SilentGlasses** [backstage/backstage#17745]
### 🔖 Feature description

[mkdocs-autolinks-plugin](https://github.com/zachhannum/mkdocs-autolinks-plugin) is a valuable plugin that makes life easy for authors to link to pages and images without having to add full ~r uls~ urls or `../../` paths to things.

### 🎤 Context

When deploying our mkdocs site to Backstage, It would be great to be able to keep using this plugin and have URLs rendered properly.

For example:

```
![Image](siteicon.png)
```

gets generated as this locally:

```
![Image](../images/siteicon.png)
```

but gets generated as in Backstage:

```
![Image](../../../../../tmp/docs_veebg344/images/siteicon.png)
```

or 

```
https://backstage.domain.com/api/techdocs/static/docs/tmp/docs_gvhrd6rl/images/siteicon.png
```

### ✌️ Possible Implementation

Not sure how this would be implemented to be honest

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by pwalleni** [comment]
Yes, please. 🙏🏼

**Comment by SilentGlasses** [comment]
Hey there, any word on this?
