### ISSUE TITLE
🐛 Bug Report: TechDocs Live preview breaks down when clicking a page on sidebar

### ISSUE THREAD

**Issue by zcmander** [backstage/backstage#17753]
### 📜 Description

When changing page via sidebarmenu the techdocs page rendering falls apart.

### 👍 Expected behavior

It should render the page as the last screenshot without needed manually refresh the page.

### 👎 Actual Behavior with Screenshots

I tried TechDocs Live preview environment but it seems to break down massively just by changing page from sidebar

When starting up the environment, everything is fine: 
![image](https://github.com/backstage/backstage/assets/2142965/5ba813f4-b44d-4fce-b112-6fd5a4e16179)
After clicking *World!* from the sidebar it breaks down:
![image](https://github.com/backstage/backstage/assets/2142965/ab0f8fb6-0a24-408d-8434-c65ac2116d02)

After refreshing the page it's fine again:
![image](https://github.com/backstage/backstage/assets/2142965/022e6a95-4129-45d2-9ebf-3ffa4f1589dd)

### 👟 Reproduction steps

I started the environment by running:

```
npx @techdocs/cli@latest serve
```

I'm pretty sure that I'm using the latest released techdocs cli package:

**@techdocs/cli**: 1.4.1

### 📃 Provide the context for the Bug.

This behaviour is new but not sure in which version it works correctly.

### 🖥️ Your Environment

Chrome 113.0.5672.92 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by sbarrypoppulo** [comment]
I'm seeing the same behaviour serving docs locally and clicking any sidebar nav links, with latest 1.4.1 version - https://www.npmjs.com/package/@techdocs/cli

**Comment by steven-terrana-bah** [comment]
this issue appears to be resolved in version 1.4.2

**Comment by avaliaexpert** [comment]
I can confirm that I was seing this problem with 1.4.1, and that it works fine with 1.4.2.

**Comment by Rugvip** [comment]
Sweet, closing!
