### ISSUE TITLE
🐛 Bug Report: Jenkins Plugin Throws 500 Error Browsing Individual Build Info

### ISSUE THREAD

**Issue by matarnold-dev** [backstage/backstage#17760]
### 📜 Description

After the Jenkins plugin has been added / configured with the DefaultJenkinsInfoProvider the "Jenkins" tab starts working.  However, when you click on an individual build in the list a separate screen is displayed but with blank fields.  Inspection of the log files and code lead me to believe this is related to https://github.com/backstage/backstage/pull/17613 .  It looks like having a combination of encoded/unencoded forward-slashes in the Jenkins full job name cause this issue. 

### 👍 Expected behavior

Show the specific build info for the build clicked on.

### 👎 Actual Behavior with Screenshots

Shows a screen with blank form data.

### 👟 Reproduction steps

1. Login to backstage
2. Open the catalog
3. Find a service item that would contain a Jenkins job with "/" in it's branch name
4. Open the service's entity page in backstage and click on the "Jenkins" tab
5. Note: a list of all the service's builds should be displayed
6. Click on one of the builds
7. Note: a new screen appears with a vertical form showing build data, but the values are blank

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
So [this is probably](https://github.com/backstage/backstage/pull/17613/files#diff-3b12e42f444c2d312865de6e96813435ae1b4d5a4a3ac4835af78bdbd540ded5R83) the offending line then?

I will need help with this one since I do not have a jenkins instance to test the fix with. Could you show what the URL looks like today that it requests, and also what a functional correct URL would have been? With sensitive bits faked out of course so you don't divulge any secrets.

**Comment by Rugvip** [comment]
@timja 👀 in case you know what might be going on here and if it's an issue you've seen before

**Comment by Alok650** [comment]
Facing the same issue when configuring jenkins plugin

app-config.yaml configs
jenkins:
  baseUrl: ${JENKINS_URL}
  username: ${JENKINS_USERNAME}
  apiKey: ${JENKINS_TOKEN}
  
Request URL:
http://localhost:7007/api/jenkins/v1/entity/default/Jenkins/sample-app-stg/projects?branch=master
Request Method:
GET
Status Code:
500 Internal Server Error

The jenkins pipeline name is sample-app-stg

@timja 
![image](https://github.com/backstage/backstage/assets/58817460/9d12b73c-596c-49cb-a937-970ba52f22db)
