### ISSUE TITLE
🚀 Feature: push Entity updates to an external System like Kafka

### ISSUE THREAD

**Issue by benkeil** [backstage/backstage#17775]
### 🔖 Feature description

Entity updates should get pushed to Kafka or SQS, etc.

At the moment you run all kind of custom processes inside of backstage with the scheduler.
I think a better approach and to separate the concerns would be to send Entity updates to Kafka, where these entities could be processed.

### 🎤 Context

We enriched the `Component` with a custom property to specify security relevant information.
Our CSO wan't this information in Jira and we wrote a cronjob in backstage which export the data. But now Backstage needs to know a lot of stuff like, mapping between Jira fields and the Entity, credentials and URLs. 

### ✌️ Possible Implementation

Not sure if a simple `CatalogProcessor` would be enough, or if the `Sticher` could implement a similar interface where only updated entities get emitted.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benkeil** [comment]
No, you understand me wrong. We have some recesses that, for my opinion, don't belong into backstage (e.g. export service information into Jira). I just want the final entity to get pushed to Kafka, so that external systems could do things with other external systems.

**Comment by awanlin** [comment]
@benkeil perhaps https://github.com/backstage/backstage/issues/8219 and https://github.com/backstage/backstage/pull/17174 would be of interest to you?
