### ISSUE TITLE
🐛 Bug Report: wrong fields for relation type in AJV schema

### ISSUE THREAD

**Issue by SpyQuel** [backstage/backstage#17779]
### 📜 Description

In the AJV schema packages/catalog-model/src/schema/shared/common.schema.json, the relation is defined to have both target *and* targetRef fields, but this is never the case.
This is preventing me from using a validator for entities that extend the basic Entity type, e.g. any schema that has the 
```
  "allOf": [
    {
      "$ref": "Entity"
    },
    { ... my constraints here ... }
```

### 👍 Expected behavior

The common.schema.json should have both fields not required, to match old entities and new ones, like:
```
    "relation": {
      "$id": "#relation",
      "type": "object",
      "description": "A directed relation from one entity to another.",
      "required": ["type"],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1,
          "pattern": "^\\w+$",
          "description": "The type of relation."
        },
        "target": {
          "$ref": "#reference"
        },
        "targetRef": {
          "type": "string",
          "minLength": 1,
          "description": "The entity ref of the target of this relation."
        }
      }
    }
```

### 👎 Actual Behavior with Screenshots

The definition instead now requires "target" field to be there:
```
    "relation": {
      "$id": "#relation",
      "type": "object",
      "description": "A directed relation from one entity to another.",
      "required": ["type", "target"],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1,
          "pattern": "^\\w+$",
          "description": "The type of relation."
        },
        "target": {
          "$ref": "#reference"
        },
        "targetRef": {
          "type": "string",
          "minLength": 1,
          "description": "The entity ref of the target of this relation."
        }
      }
    }
```

### 👟 Reproduction steps

Try to use any validator for entities, like the `systemEntityV1alpha1Validator` passing a "new" entity, without the target field in the relations, and that is not usable.

### 📃 Provide the context for the Bug.

I would like to use validators in my code, but I can't create them extending the base one, which will grant my code to be more compliant with Backstage's types.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Alright. Yeah the current behavior since a long time back is indeed that the `type` and `targetRef` are the only "official" fields, and `target` is a historical remnant that's only there to not break contract with really really ancient consumers. The `target` field [is actually considered for actual deletion](https://github.com/backstage/backstage/pull/17457) even, but it may take some time.

If anything is to be fixed, it should be that `targetRef` is required, and `target` isn't.

**Comment by kmarkow** [comment]
> If anything is to be fixed, it should be that `targetRef` is required, and `target` isn't.

Opened a PR [here](https://github.com/backstage/backstage/pull/17824)
