### ISSUE TITLE
🐛 Bug Report: Microsoft auth provider reporting scopes from multiple Azure resources

### ISSUE THREAD

**Issue by nBerg** [backstage/backstage#17784]
### 📜 Description

When testing out an upgrade from backstage 1.12.1 to 1.13.2 the microsoft auth provider starting returning this error when requesting an access token:
```
Requested access token with scopes from multiple Azure resources: 00000003-0000-0000-c000-000000000000, 00000003-0000-0000-c000-000000000000. Access tokens can only have a single audience.
```

I am requesting 2 scopes ("User.read" and "Group.read.all"), but these are both for the same resource, MS Graph.

I believe this is occurring due to the change here: https://github.com/backstage/backstage/commit/85adf6943b8c756fe44a34fa2577d8109ad81077

If I understand correctly, my use case should be supported, but some deduping is needed before checking the audiences length. I will try to open a fix if time allows.

### 👍 Expected behavior

Multiple scopes for the same resource should be supported. A token should be returned with the requested scopes.

### 👎 Actual Behavior with Screenshots

An error occurred saying `Requested access token with scopes from multiple Azure resources: 00000003-0000-0000-c000-000000000000, 00000003-0000-0000-c000-000000000000. Access tokens can only have a single audience.` 

### 👟 Reproduction steps

1. Try to request an access token with more than one scope, for the same resource:
```
    const accessToken = await this.microsoftApi.getAccessToken(
      ['User.read', 'Group.read.all'],
      {
        optional: false,
        instantPopup: true,
      },
    );
```

### 🖥️ Your Environment

Experienced while upgrading from backstage 1.12.1 to 1.13.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jamieklassen** [comment]
I made this change and  I feel foolish -- good catch and thanks for filing the bug. I want to give you the chance to open your own PR (assuming you're still interested -- please confirm) so I won't jump on this yet; here are some thoughts:

1. Let's add a new a unit test in this `describe`:
    https://github.com/backstage/backstage/blob/19479172bc0d4832c9b5eb8820c2ca61ef188004/packages/core-app-api/src/apis/implementations/auth/microsoft/MicrosoftAuth.test.ts#L84
    where multiple scopes from the same resource are requested.
1. Implementation-wise we could replace this:
    https://github.com/backstage/backstage/blob/19479172bc0d4832c9b5eb8820c2ca61ef188004/packages/core-app-api/src/apis/implementations/auth/microsoft/MicrosoftAuth.ts#L94-L97
    with something like
    ```typescript
        const audiences = [
          ...new Set(
            scope
              .split(" ")
              .map(MicrosoftAuth.resourceForScope)
              .filter((aud) => aud !== "openid")
          ),
        ];
    ```
