### ISSUE TITLE
🚀 Feature: Adding optional pgp signatures to git scm

### ISSUE THREAD

**Issue by Semiarty** [backstage/backstage#17791]
### 🔖 Feature description

Add the possibility of optional PGP signatures to git-scm commits in [backend-common](https://github.com/backstage/backstage/tree/master/packages/backend-common/src/scm)

### 🎤 Context

In our company all of our commits need to be signed and when we are using backstage backend to push content to internal gitlab we are required to sign commits otherwise they get denied.

### ✌️ Possible Implementation

We have made a workaround where we clone the backstage repo and change source code of https://github.com/backstage/backstage/blob/master/packages/backend-common/src/scm/git.ts
by adding https://github.com/isomorphic-git/pgp-plugin, rebuilding backend-common and overwriting /dist/node_modules/@backstage/backend-common/dist.
This as you can imagine is really cumbersome and takes up both space and time, especially during our backstage app container image builds.
We have added the following bits in 
https://github.com/backstage/backstage/blob/master/packages/backend-common/src/scm/git.ts#L22
`const { pgp } = require('@isomorphic-git/pgp-plugin')`

https://github.com/backstage/backstage/blob/master/packages/backend-common/src/scm/git.ts#L114
`return git.commit({ fs, dir, message, author, committer, onSign: pgp.sign, signingKey: process.env.PGPKEY})`

I am not sure though how feasible it would be to add optional signing of commits.
P.S. I am new to open source contributions and I don't have much expertise in ts so please bear with me :) 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
This is a bit of a larger undertaking that probably would take some more dedicated thought. We'd probably want to sit down and break out the git functionality into its own service API instead that people can replace or shim with their own behaviours. And that's not something we have on our radar at this very moment.

Until then, I think the easiest way forward for you is to make your own custom action instead, that does exactly what you need.
