### ISSUE TITLE
Missing instructions for adding GitlabOrgDiscoveryEntityProvider to backstage

### ISSUE THREAD

**Issue by Shocktrooper** [backstage/backstage#17808]
### 📜 Description

I have been looking through the documentation to try and utilize my self hosted GitLab instance for org data but after implementing everything in the documentation underneath [these pages](https://backstage.io/docs/integrations/gitlab/locations/) it does not work. After digging around a bit I found that there is the GitlabOrgDiscoveryEntityProvider provider definition which is not documented anywhere for usage that I could find. I imagine [this](https://backstage.io/docs/integrations/gitlab/org) plus the scaffolding code is what is needed to make this work. It would be appreciated to get a direction on how to make this work and also add the documentation to the org ingestion page.

Note: I found what I needed in a closed ticket in this repository. [here](https://github.com/backstage/backstage/issues/17735) but it is not documented in the official docs

### 👍 Expected behavior

N/A

### 👎 Actual Behavior with Screenshots

N/A

### 👟 Reproduction steps

N/A

### 📃 Provide the context for the Bug.

N/A

### 🖥️ Your Environment

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by jamieklassen** [comment]
I think #17685 handles this?

**Comment by Shocktrooper** [comment]
> I think #17685 handles this?

Thats's it! It just never had a corresponding issue so I couldn't find that PR
