### ISSUE TITLE
🐛 Bug Report: Linguist fails when entites are removed from catalog

### ISSUE THREAD

**Issue by dweber019** [backstage/backstage#17800]
### 📜 Description

We use the plugin linguist (https://github.com/backstage/backstage/tree/master/plugins/linguist-backend).
When we remove entities from the catalog, Linguist fails with the following message:
```
{
	"level": "error",
	"message": "Unable to process \"component:default/base-image-oauth2-proxy\" using \"\", message: Invalid URL, stack: TypeError [ERR_INVALID_URL]: Invalid URL\n at new NodeError (node:internal/errors:399:5)\n at new URL (node:internal/url:560:13)\n at UrlReaderPredicateMux.readTree (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:3127:20)\n at LinguistBackendApi.generateEntityLanguages (/app/node_modules/@backstage/plugin-linguist-backend/dist/index.cjs.js:124:51)\n at /app/node_modules/@backstage/plugin-linguist-backend/dist/index.cjs.js:89:20\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
	"plugin": "linguist",
	"service": "backstage",
	"type": "plugin"
}
```

### 👍 Expected behavior

Entities removed from the catalog are either ignored or removed from the linguist table.

### 👎 Actual Behavior with Screenshots

Error throw, see description.

### 👟 Reproduction steps

1. Add an entity to catalog
2. Wait for linguist to process the entity
3. Remove the entity form the catalog
4. Error thrown

### 🖥️ Your Environment

OS:   Windows_NT 10.0.19044 - win32/x64
node: v18.16.0
yarn: 1.22.17
cli:  0.22.6 (installed)
backstage:  1.13.0      

Dependencies:
  @backstage/app-defaults                                   1.3.0
  @backstage/backend-app-api                                0.4.2       
  @backstage/backend-common                                 0.18.4      
  @backstage/backend-dev-utils                              0.1.1       
  @backstage/backend-plugin-api                             0.5.1       
  @backstage/backend-tasks                                  0.5.1       
  @backstage/catalog-client                                 1.4.1       
  @backstage/catalog-model                                  1.1.5, 1.3.0
  @backstage/cli-common                                     0.1.12      
  @backstage/cli-node                                       0.1.0       
  @backstage/cli                                            0.22.6      
  @backstage/config-loader                                  1.2.0
  @backstage/config                                         1.0.7
  @backstage/core-app-api                                   1.7.0
  @backstage/core-components                                0.12.5, 0.13.0
  @backstage/core-plugin-api                                1.5.1
  @backstage/dev-utils                                      1.0.14
  @backstage/errors                                         1.1.5
  @backstage/eslint-plugin                                  0.1.3
  @backstage/integration-aws-node                           0.1.2
  @backstage/integration-react                              1.1.12
  @backstage/integration                                    1.4.4
  @backstage/plugin-adr-backend                             0.3.2
  @backstage/plugin-adr-common                              0.2.8
  @backstage/plugin-adr                                     0.5.0
  @backstage/plugin-api-docs                                0.9.2
  @backstage/plugin-app-backend                             0.3.44
  @backstage/plugin-auth-backend                            0.18.2
  @backstage/plugin-auth-node                               0.2.13
  @backstage/plugin-badges-backend                          0.1.38
  @backstage/plugin-badges                                  0.2.41
  @backstage/plugin-bitbucket-cloud-common                  0.2.5
  @backstage/plugin-catalog-backend-module-bitbucket-server 0.1.9
  @backstage/plugin-catalog-backend-module-bitbucket        0.2.11
  @backstage/plugin-catalog-backend-module-ldap             0.5.11
  @backstage/plugin-catalog-backend                         1.9.0
  @backstage/plugin-catalog-common                          1.0.13
  @backstage/plugin-catalog-graph                           0.2.29
  @backstage/plugin-catalog-import                          0.9.7
  @backstage/plugin-catalog-node                            1.3.5
  @backstage/plugin-catalog-react                           1.2.4, 1.5.0
  @backstage/plugin-catalog                                 1.10.0
  @backstage/plugin-github-actions                          0.5.17
  @backstage/plugin-home                                    0.5.0
  @backstage/plugin-jenkins-backend                         0.1.34
  @backstage/plugin-jenkins-common                          0.1.15
  @backstage/plugin-jenkins                                 0.7.16
  @backstage/plugin-kubernetes-backend                      0.10.0
  @backstage/plugin-kubernetes-common                       0.6.2
  @backstage/plugin-kubernetes                              0.8.0
  @backstage/plugin-linguist-backend                        0.2.1
  @backstage/plugin-linguist-common                         0.1.0
  @backstage/plugin-linguist                                0.1.2
  @backstage/plugin-org                                     0.6.7
  @backstage/plugin-permission-common                       0.7.5
  @backstage/plugin-permission-node                         0.7.7
  @backstage/plugin-permission-react                        0.4.12
  @backstage/plugin-proxy-backend                           0.2.38
  @backstage/plugin-scaffolder-backend                      1.13.0
  @backstage/plugin-scaffolder-common                       1.2.7
  @backstage/plugin-scaffolder-node                         0.1.2
  @backstage/plugin-scaffolder-react                        1.3.0
  @backstage/plugin-scaffolder                              1.13.0
  @backstage/plugin-search-backend-module-catalog           0.1.0
  @backstage/plugin-search-backend-module-pg                0.5.5
  @backstage/plugin-search-backend-module-techdocs          0.1.0
  @backstage/plugin-search-backend-node                     1.2.0
  @backstage/plugin-search-backend                          1.3.0
  @backstage/plugin-search-common                           1.2.3
  @backstage/plugin-search-react                            1.5.2
  @backstage/plugin-search                                  1.2.0
  @backstage/plugin-shortcuts                               0.3.9
  @backstage/plugin-sonarqube-backend                       0.1.9
  @backstage/plugin-sonarqube-react                         0.1.5
  @backstage/plugin-sonarqube                               0.6.6
  @backstage/plugin-tech-insights-backend-module-jsonfc     0.1.28
  @backstage/plugin-tech-insights-backend                   0.5.10
  @backstage/plugin-tech-insights-common                    0.2.10
  @backstage/plugin-tech-insights-node                      0.4.2
  @backstage/plugin-tech-insights                           0.3.9
  @backstage/plugin-tech-radar                              0.6.3
  @backstage/plugin-techdocs-backend                        1.6.1
  @backstage/plugin-techdocs-module-addons-contrib          1.0.12
  @backstage/plugin-techdocs-node                           1.7.0
  @backstage/plugin-techdocs-react                          1.1.5
  @backstage/plugin-techdocs                                1.6.1
  @backstage/plugin-user-settings                           0.7.2
  @backstage/release-manifests                              0.0.9
  @backstage/test-utils                                     1.3.0
  @backstage/theme                                          0.2.19
  @backstage/types                                          1.0.2
  @backstage/version-bridge                                 1.0.4
Done in 5.61s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dweber019** [comment]
FYI @ahhhndre

**Comment by awanlin** [comment]
Hi @dweber019, thanks for logging this and I actually have a PR that addresses this: https://github.com/backstage/backstage/pull/16954 (@ahhhndre is me)

**Comment by dweber019** [comment]
Awesome. looking forward to this, as we stuck in processing or have to manually clean up the table.

**Comment by dweber019** [comment]
Nice thx, will close the issue.
