### ISSUE TITLE
🚀 Feature: Use readme file in root when index.md is missing in docs directory

### ISSUE THREAD

**Issue by artemptushkin** [backstage/backstage#17815]
### 🔖 Feature description

Currently, `techdocs` CLI same as `mkdocs` needs the file `index.md` in [the root documentation directory (`docs` by default)](https://www.mkdocs.org/user-guide/writing-your-docs/#index-pages) though sometimes this file is missing and the whole documention will be broken.

The idea is to use the `README.md` in the root project directory if that exists because it replaces the index file nicely.

This feature should be toggleable with a CLI parameter.

### 🎤 Context

We set this up like this and now techdocs CLI is applicable to any arbitrary project, i.e. no need to have anything specifics - just markdown docs

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by asos-robbell** [comment]
Looks as though this may have already been implemented, although I'm struggling to find documentation:

https://github.com/backstage/backstage/pull/7080

**Comment by squid-ney** [comment]
Hey there, I believe you should be able to use a `README.md` file as an entry point to your docs site. Based on this PR, https://github.com/backstage/backstage/pull/7080, it should work out of the box so no need for a CLI parameter.

Locally, I tested this using the [example-docs](https://github.com/backstage/backstage/tree/master/packages/techdocs-cli/src/example-docs) directory and running `techdocs-cli serve:mkdocs`. When I changed the `docs/index.md` file to `docs/README.md`, the mkdocs site still loaded with the `README.md` file as the Home. Have you ran into issues using README.md as an entry point? If yes, then could you share steps to replicate?

**Comment by TanjaZzz** [comment]
I'm struggling with the same question: how to make README.md an entry point, when it's placed in the root (same where mkdocs.yml is placed).

**Comment by drewgingerich** [comment]
We're also looking for this feature. We're migrating to Backstage from using a plain `README.md` file in each repo, and we'd like get the content of these existing `README.md` files into Backstage. We see a few options.

- Leave `README.md` at the repo root. We don't get visibility in Backstage but keep visibility in GitHub.
- Move the `README.md` file from the root to `docs/index.md`. We gain visibility in Backstage but lose visibility in GitHub.
- Duplicate `README.md` in the project root and `docs/index.md`. We get visibility in both Backstage and GitHub, but take on a maintenance burden. We may be able to use a symlink instead, which is less maintenance but adds some complexity.

None of these exactly fulfill our needs. We'd like content visibility in both Backstage and GitHub without duplication and minimal complexity (from the user perspective). Being able to point the techdocs at the root-level `README.md` file seems like it would do everything we need.

**Comment by artemptushkin** [comment]
We have an on-site solution in the end just doing this in bash because we had issues with the backstage one `--legacyCopyReadmeMdToIndexMd`

**Comment by dannyhanford** [comment]
I would really like this feature for issues that @drewgingerich brought up
