### ISSUE TITLE
🐛 Bug Report: `SidebarConfigContext` not respecting config prop values

### ISSUE THREAD

**Issue by seanblonien** [backstage/backstage#17811]
### 📜 Description

When configuring the [`<Sidebar/>` component](https://github.com/backstage/backstage/blob/master/packages/core-components/src/layout/Sidebar/Bar.tsx), when `sidebarOptions` and `submenuOptions` props are passed to the component, the component styling (in this case, width of the sidebar) does not update/react to the override values.

### 👍 Expected behavior

Passing in sidebar options for overriding width values should propagate and change styling/widths accordingly.

### 👎 Actual Behavior with Screenshots

The main content still has the default `padding-left`, and the padding is not recalculated.

![image](https://github.com/backstage/backstage/assets/33133478/a4d40341-5d14-4307-a1be-7604c0f9ba4a)
![image](https://github.com/backstage/backstage/assets/33133478/abe44655-c9cc-49c1-9f03-a085f60a9cc9)
![image](https://github.com/backstage/backstage/assets/33133478/feaac7eb-06fe-4a80-9011-63518ddc9650)

### 👟 Reproduction steps

1. Run `npx @backstage/create-app@latest`
1. Go to `packages/app/src/components/Root/Root.tsx`
1. Add this prop to the `<Sidebar/>` component
    - `sidebarOptions={{drawerWidthOpen: 180}}`
1. Run `yarn start`
1. View the front end not rendering the sidebar correctly with the smaller width

### 📃 Provide the context for the Bug.

Related #9539, not sure if this PR changes were fully tested with smalle sidebar values

### 🖥️ Your Environment

yarn run v1.22.19
$ /home/seanblonien/git/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.15.90.1-microsoft-standard-WSL2 - linux/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.22.6 (installed)
backstage:  1.13.0

Dependencies:
  @backstage/app-defaults                          1.3.0
  @backstage/backend-app-api                       0.4.2
  @backstage/backend-common                        0.18.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.1
  @backstage/backend-tasks                         0.5.1
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.6
  @backstage/config-loader                         1.2.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.7.0
  @backstage/core-components                       0.13.0
  @backstage/core-plugin-api                       1.5.1
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.12
  @backstage/integration                           1.4.4
  @backstage/plugin-api-docs                       0.9.2
  @backstage/plugin-app-backend                    0.3.44
  @backstage/plugin-auth-backend                   0.18.2
  @backstage/plugin-auth-node                      0.2.13
  @backstage/plugin-catalog-backend                1.9.0
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.29
  @backstage/plugin-catalog-import                 0.9.7
  @backstage/plugin-catalog-node                   1.3.5
  @backstage/plugin-catalog-react                  1.5.0
  @backstage/plugin-catalog                        1.10.0
  @backstage/plugin-github-actions                 0.5.17
  @backstage/plugin-org                            0.6.7
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.7
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.38
  @backstage/plugin-scaffolder-backend             1.13.1
  @backstage/plugin-scaffolder-common              1.2.7
  @backstage/plugin-scaffolder-node                0.1.2
  @backstage/plugin-scaffolder-react               1.3.0
  @backstage/plugin-scaffolder                     1.13.0
  @backstage/plugin-search-backend-module-catalog  0.1.0
  @backstage/plugin-search-backend-module-pg       0.5.5
  @backstage/plugin-search-backend-module-techdocs 0.1.0
  @backstage/plugin-search-backend-node            1.2.0
  @backstage/plugin-search-backend                 1.3.0
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.5.2
  @backstage/plugin-search                         1.2.0
  @backstage/plugin-tech-radar                     0.6.3
  @backstage/plugin-techdocs-backend               1.6.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.12
  @backstage/plugin-techdocs-node                  1.7.0
  @backstage/plugin-techdocs-react                 1.1.5
  @backstage/plugin-techdocs                       1.6.1
  @backstage/plugin-user-settings                  0.7.2
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.0
  @backstage/theme                                 0.2.19
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4
Done in 0.45s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by CVamsi27** [comment]
Hello, I am trying to reproduce this bug, if I am able to fix it, I will submit a PR.

**Comment by seanblonien** [comment]
@CVamsi27 I have managed to reproduce again [on Codesandbox](https://codesandbox.io/p/github/seanblonien/backstage/master?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clhs08w0c000a3n6ntrnujrmv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clhs08w0c000c3n6nbbw2jmup%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B42.96273101961755%252C57.03726898038245%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clhs08w0c000a3n6ntrnujrmv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clhs08w0b00093n6nopyoeuhg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clhs08w0c000a3n6ntrnujrmv%2522%252C%2522activeTabId%2522%253A%2522clhs08w0b00093n6nopyoeuhg%2522%257D%252C%2522clhs08w0c000c3n6nbbw2jmup%2522%253A%257B%2522id%2522%253A%2522clhs08w0c000c3n6nbbw2jmup%2522%252C%2522activeTabId%2522%253A%2522clhs2sdhx00o53n6ng5roqh38%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clhs2lxe700it3n6njtpbzbt2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clhs2m7f008k9fygjeuiqb288%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clhs2sdhx00o53n6ng5roqh38%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

let me know if this works for you and you can reproduce the error

**Comment by seanblonien** [comment]
@CVamsi27 ok now i was able to reproduce using Github codespaces which i hope you can preview: https://seanblonien-congenial-cod-x95qwx5rxxp3977w-3000.preview.app.github.dev/

which is just running this repos branch: https://github.com/seanblonien/backstage/tree/main

**Comment by CVamsi27** [comment]
@seanblonien I was not able to access your [link](https://seanblonien-congenial-cod-x95qwx5rxxp3977w-3000.preview.app.github.dev/).
I see your branch/repo is not in sync with main repo.

**Comment by seanblonien** [comment]
@CVamsi27 you're right it was not. not it is in sync and up to date

all i did was clone, install, and run the start script and I am defintiely able to reproduce with the sample app on this branch:
https://github.com/seanblonien/backstage/tree/master
![image](https://github.com/backstage/backstage/assets/33133478/5b622366-1dc7-4719-a104-861fe52dd89b)

**Comment by seanblonien** [comment]
@CVamsi27  Still reproducible easily with the 1 code line difference. Repo is up-to-date
https://github.com/seanblonien/backstage/tree/master
![image](https://github.com/backstage/backstage/assets/33133478/7f70f992-a007-451d-a008-4283cd4301ec)

**Comment by desprit** [comment]
Custom width doesn't work as this code:
```
@media (min-width: 600px) {
    .BackstageSidebarPage-root-26 {
        padding-left: 224px;
    }
}
```
isn't re-calculated. No matter what the padding is always 224px.

**Comment by benediktSHornbach** [comment]
Any update on this?
We have plugin titles that exceed the default sidebar width and are eclipsed (...)
Passing drawerWidthOpen: 300 does not update the main content of the App
