### ISSUE TITLE
🚀 Feature: Allow configuring AzureBlobStoragePublish with connection string

### ISSUE THREAD

**Issue by x3ro** [backstage/backstage#17819]
### 🔖 Feature description

Allow usage of a [connection string](https://github.com/Azure/Azurite#connection-strings) to configure the `AzureBlobStoragePublish`, enabling local testing through [Azurite](https://github.com/Azure/Azurite).

### 🎤 Context

The `AzureBlobStoragePublish` class is currently [hard-coded](https://github.com/backstage/backstage/blob/93daeb898f77076049c4862b0c24a94721344671/plugins/techdocs-node/src/stages/publish/azureBlobStorage.ts#L106) to connect to `blob.core.windows.net`:

```ts
    const storageClient = new BlobServiceClient(
      `https://${accountName}.blob.core.windows.net`,
      credential,
    );
```

This prevents usage of Azurite, the local emulator for Azure Blob Storage (among other things). 

### ✌️ Possible Implementation

Instead of creating the `BlobServiceClient` using an account URL (as is currently the case), there's also an option to use a connection string, like so:

```ts
# Example from Microsoft Docs, not an actual secret
const connectionString = 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;';
const storageClient = BlobServiceClient.fromConnectionString(connectionString);
```

With the connection string being provided via the configuration files / the environment.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by titanventura** [comment]
I can work on this. Please assign !

**Comment by freben** [comment]
@titanventura you still up for this one? 🙏

**Comment by titanventura** [comment]
Hi @freben , Yup, I'm planning to work on this !

**Comment by kallayj** [comment]
@titanventura , I would like to see this done as well, I believe it should be straightforward, let me know if I can help.

**Comment by titanventura** [comment]
Hey @kallayj @x3ro , please take a look at the PR, Thanks !
