### ISSUE TITLE
🐛 Bug Report: Sidebar isLocationMatch says location is same when it is not

### ISSUE THREAD

**Issue by hspitzley-czi** [backstage/backstage#17826]
### 📜 Description

The `isLocationMatch` is using the `isMatch` method from lodash instead of `isEqual` for object equality.

### 👍 Expected behavior

Parse query string `{ foo: 'abc', bar: 'xyz' }` should not be considered the same as `{ foo: 'abc' }`

### 👎 Actual Behavior with Screenshots

The code uses `isMatch` which leads to the following unexpected behavior:
```
> isEqual({ foo: 'abc', bar: 'xyz' }, { foo: 'abc' })
false
> isMatch({ foo: 'abc', bar: 'xyz' }, { foo: 'abc' })
true
```

### 👟 Reproduction steps

Make submenu items with routes with the following query strings:
- `?foo=abc&bar=xyz`
- `?foo=abc`
And see that when you navigate to one, both are highlighted as if they are the same and you are on the page of both

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
This is intended behavior since we want to have the sidebar item stay highlighted even if additional filters are added. Do you have a concrete example of this is causing trouble?

**Comment by hspitzley-czi** [comment]
Having an `exact` prop would be great 👍. I can cut a PR if you like. I started writing one but didn't have permission to push to a feature branch

**Comment by benjdlambert** [comment]
You'll need to fork the repository and then push to yours to open a PR :pray: please do open a PR :)

**Comment by hspitzley-czi** [comment]
@benjdlambert / @Rugvip I opened a PR. Let me know if you want any changes. I didn't include a changeset because it was a pretty simple change but can add that if necessary. Thanks for reviewing!

**Comment by hspitzley-czi** [comment]
Fixed by the linked PR
