### ISSUE TITLE
🚀 Feature: Utility for Testing Express Handlers with SuperTest

### ISSUE THREAD

**Issue by RubenV-dev** [backstage/backstage#17867]
### 🔖 Feature description

We want a simple way to test request handlers in error scenarios with behaviors that match a real backstage app.

### 🎤 Context

current behavior:
If i use a default express app, and I register an async request handlers, that request handler throws an error, my supertest invocation will hang.

```typescript
import express from 'express'
import request from 'supertest'

it("the request hangs and test times out", async() => {
    const app = express();
    app.get('/', async (req, res) => {
        throw new Error()
    })
    await request(app).get('/')
})
```

desired behavior:
if i use the new testing utility, and I register  it an async request handler that throws an error, I want my supertest invocation to resolve.

```typescript
import { testExpressApp } from '@backstage/backend-test-utils'
import request from 'supertest'

it("the request resolves", async() => {
    const app = testExpressApp();
    app.get('/', async (req, res) => {
        throw new Error()
    })
    const response = await request(app).get('/')
    expect(response.status).toEqual(500)

})
```

current behavior:
If i use a default express app, and I register a requestHandler that throws a [`NotAllowedError`](https://backstage.io/docs/reference/errors.notallowederror/), my supertest invocation resolves with  a 500-status response

```typescript
import express from 'express'
import request from 'supertest'
import { NotAllowedError} from '@backstage/errors'

it("the request resolves with a 500 status regardless of the error",async() => {
    const app = express();
    app.get('/', (req, res) => {
        throw new NotAllowedError()
    })
    const response = await request(app).get('/')
    expect(response.status).toEqual(500)
})
```

desired behavior:
If i use the new testing utility, and I register a requestHandler that throws a [`NotAllowedError`](https://backstage.io/docs/reference/errors.notallowederror/), my supertest invocation resolves with  a 403-status response

```typescript
import { testExpressApp } from '@backstage/backend-test-utils'
import request from 'supertest'
import { NotAllowedError} from '@backstage/errors'

it("the response status reflects the error thrown", async() => {
    const app = testExpressApp();
    app.get('/', (req, res) => {
        throw new NotAllowedError()
    })
    const response = await request(app).get('/')
    expect(response.status).toEqual(403)

})
```

we want the new testing util to have the same status mapping as a default backstage backend. Example above was for [`NotAllowedError`](https://backstage.io/docs/reference/errors.notallowederror/) specifically. 

Stretch goals/Nice to have:
we want the new testing util to have the same overall behavior as a backstage backend when it comes to error handling (eg. Json serialization and stack traces)

### ✌️ Possible Implementation

A real backstage app currently does this:
https://github.com/backstage/backstage/blob/19479172bc0d4832c9b5eb8820c2ca61ef188004/packages/backend-common/src/service/lib/ServiceBuilderImpl.ts#L148-L182 

It would be great if our test utility did everything in the above example except binding a server to a real port, instead returning the fully-set-up express app.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Hi!

Problem is, adopters are fully under control of their backend route "trunks", which means that there's no one single way of making the mock version of it. Not everybody has the same set of middlewares.

We carefully use express-promise-router everywhere ([example](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/createRouter.ts#L28)) because it handles sync and async errors better. That helps with the "hanging" bit.

What you could consider is to make a shared private library in `packages/` that has the code to create a route trunk. Then you can use that both in the actual service and in tests.

**Comment by Rugvip** [comment]
This is actually something we've added in the new backend system, you can see it in action here: https://github.com/backstage/backstage/blob/661734ae7519e683b637ed066dd9bad2404d179f/packages/backend-test-utils/src/next/wiring/TestBackend.test.ts#L200C40-L222

There's no plan to add this for the old system, but migration to the new system is still in progress

**Comment by RubenV-dev** [comment]
Thanks for the feedback, will take this to the team and see if there is a way to leverage that startTestBackend helper from @backstage/backend/test-utils and make use of it in the testing suite for the kubernetes plugin.
