### ISSUE TITLE
🐛 Bug Report: text falls off the screen if it is too long

### ISSUE THREAD

**Issue by sand4rt** [backstage/backstage#17863]
### 📜 Description

Text falls off the screen if it is too long

### 👍 Expected behavior

The text in the header should be truncated with ellipses, and a tooltip may be needed when this happens. 

The text in the grid/content section should be broken down, perhaps with: `word-break: break-word`?

### 👎 Actual Behavior with Screenshots

<img width="1695" alt="Screenshot 2023-05-19 at 12 57 14" src="https://github.com/backstage/backstage/assets/17591696/49072413-bc61-4e61-bf47-b5369d852830">

### 👟 Reproduction steps

Navigate to the entity page with an email that is very long

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Possible approach for this is to use https://backstage.io/storybook/?path=/story/data-display-overflowtooltip--default
