### ISSUE TITLE
🐛 Bug Report: (Homepage plugin): Custom homepage does not allow adding certain components

### ISSUE THREAD

**Issue by wss-rbunning** [backstage/backstage#17873]
### 📜 Description

When creating a custom homepage, I do not seem to be able to add certain cards to the homepage. What happens is when the page loads, an error is shown saying "No implementation available for apiRef{\<ref name\>}":

![image](https://github.com/backstage/backstage/assets/129326788/36871eea-bdf1-42e8-a28f-f44e070d032a)

I have seen this happen with the following components:
- The ```microsoft-calendar``` plugin's ```MicrosoftCalendarCard``` card.
NOTE: If I add the ```MicrosoftCalendarCard``` to the entity page (packages/app/src/catalog/EntityPage.tsx) the card will work correctly on both the entity page and the custom home page.
- K-Phoen's ```backstage-plugin-announcements``` plugin's ```AnnouncementsCard``` (link to the plugin: https://github.com/K-Phoen/backstage-plugin-announcements)
NOTE: If I add a sidebar link to go to the plugin's announcements page the ```AnnouncementsCard``` will start working on the custom homepage. If I remove this sidebar link, the card will break down. 
- A custom card I created. This card uses its own api internally and the no implementation found error named this api even though it was configured correctly. Unlike the other two, I did not try anything special with this card because I did not understand what was going on at the time. I have since deleted this and went a different route. 

### 👍 Expected behavior

The guide for setting up the homepage says that making the homepage "is no different from creating a regular React Component, i.e. the App Integrator is free to include whatever content they like." (https://backstage.io/docs/getting-started/homepage/#composing-your-homepage).

You should be able to add any component and have it work as it would in any other React Component. 

### 👎 Actual Behavior with Screenshots

It seems that components that use an api that is not used elsewhere throw the "No implementation available for apiRef{\<ref name\>}" error

### 👟 Reproduction steps

Instructions to replicate with
1. Install and configure the homepage plugin according to this guide (https://backstage.io/docs/getting-started/homepage/#homepage)
2. Install the ```microsoft-calendar``` plugin according to these instructions: https://github.com/backstage/backstage/tree/master/plugins/microsoft-calendar
3. Add the ```MicrosoftCalendarCard``` to the homepage and run Backstage (it should not work)
4. Add the ```MicrosoftCalendarCard``` to the entity page and run Backstage (it should now work on both the homepage and entity pages)

### 🖥️ Your Environment

I have had this issue on Backstage versions 1.13.2 and 1.14.0.

yarn backstage-cli info (when using Backstage version 1.13.2):
OS:   Windows_NT 10.0.19044 - win32/x64
node: v16.19.1
yarn: 1.22.19
cli:  0.22.6 (installed)
backstage:  1.13.2

Dependencies:
  @backstage/app-defaults                               1.3.0
  @backstage/backend-app-api                            0.4.2, 0.4.3
  @backstage/backend-common                             0.18.4, 0.18.5
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.1, 0.5.2
  @backstage/backend-tasks                              0.5.1, 0.5.2
  @backstage/catalog-client                             1.4.1
  @backstage/catalog-model                              1.3.0
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.0
  @backstage/cli                                        0.22.6
  @backstage/config-loader                              1.2.0, 1.3.0
  @backstage/config                                     1.0.7
  @backstage/core-app-api                               1.7.0, 1.8.0
  @backstage/core-components                            0.12.5, 0.13.0, 0.13.1
  @backstage/core-plugin-api                            1.5.1
  @backstage/dev-utils                                  1.0.14
  @backstage/errors                                     1.1.5
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.2, 0.1.3
  @backstage/integration-react                          1.1.12
  @backstage/integration                                1.4.4, 1.4.5
  @backstage/plugin-adr-backend                         0.3.2
  @backstage/plugin-adr-common                          0.2.8
  @backstage/plugin-adr                                 0.5.0
  @backstage/plugin-api-docs                            0.9.2
  @backstage/plugin-app-backend                         0.3.44
  @backstage/plugin-auth-backend                        0.18.2
  @backstage/plugin-auth-node                           0.2.13, 0.2.14
  @backstage/plugin-azure-devops-backend                0.3.23
  @backstage/plugin-azure-devops-common                 0.3.0
  @backstage/plugin-azure-devops                        0.2.8
  @backstage/plugin-catalog-backend-module-azure        0.1.15
  @backstage/plugin-catalog-backend                     1.9.0
  @backstage/plugin-catalog-common                      1.0.13
  @backstage/plugin-catalog-graph                       0.2.29
  @backstage/plugin-catalog-import                      0.9.7
  @backstage/plugin-catalog-node                        1.3.5
  @backstage/plugin-catalog-react                       1.5.0
  @backstage/plugin-catalog                             1.10.0
  @backstage/plugin-entity-feedback-backend             0.1.2
  @backstage/plugin-entity-feedback-common              0.1.1
  @backstage/plugin-entity-feedback                     0.2.0
  @backstage/plugin-entity-validation                   0.1.2
  @backstage/plugin-github-actions                      0.5.17
  @backstage/plugin-home                                0.5.1
  @backstage/plugin-linguist-backend                    0.2.1
  @backstage/plugin-linguist-common                     0.1.0
  @backstage/plugin-linguist                            0.1.2
  @backstage/plugin-microsoft-calendar                  0.1.3
  @backstage/plugin-newrelic-dashboard                  0.2.10
  @backstage/plugin-org                                 0.6.7
  @backstage/plugin-permission-backend                  0.5.19
  @backstage/plugin-permission-common                   0.7.5
  @backstage/plugin-permission-node                     0.7.7, 0.7.8
  @backstage/plugin-permission-react                    0.4.12
  @backstage/plugin-proxy-backend                       0.2.38
  @backstage/plugin-scaffolder-backend                  1.13.1
  @backstage/plugin-scaffolder-common                   1.2.7
  @backstage/plugin-scaffolder-node                     0.1.2
  @backstage/plugin-scaffolder-react                    1.3.0
  @backstage/plugin-scaffolder                          1.13.0
  @backstage/plugin-search-backend-module-catalog       0.1.0
  @backstage/plugin-search-backend-module-pg            0.5.5
  @backstage/plugin-search-backend-module-techdocs      0.1.0
  @backstage/plugin-search-backend-node                 1.2.0
  @backstage/plugin-search-backend                      1.3.0
  @backstage/plugin-search-common                       1.2.3
  @backstage/plugin-search-react                        1.5.2
  @backstage/plugin-search                              1.2.0
  @backstage/plugin-sentry                              0.5.2
  @backstage/plugin-sonarqube-backend                   0.1.9
  @backstage/plugin-sonarqube-react                     0.1.5
  @backstage/plugin-sonarqube                           0.6.6
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.28
  @backstage/plugin-tech-insights-backend               0.5.10
  @backstage/plugin-tech-insights-common                0.2.10
  @backstage/plugin-tech-insights-node                  0.4.2
  @backstage/plugin-tech-insights                       0.3.9
  @backstage/plugin-tech-radar                          0.6.3
  @backstage/plugin-techdocs-backend                    1.6.1
  @backstage/plugin-techdocs-module-addons-contrib      1.0.12
  @backstage/plugin-techdocs-node                       1.7.0
  @backstage/plugin-techdocs-react                      1.1.5
  @backstage/plugin-techdocs                            1.6.1
  @backstage/plugin-user-settings                       0.7.2
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.3.0, 1.3.1
  @backstage/theme                                      0.2.19, 0.3.0
  @backstage/types                                      1.0.2
  @backstage/version-bridge                             1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by grvpandey11** [comment]
I am also facing similar issue while installing Microsoft Calendar plugin to Home page.

**Comment by Rugvip** [comment]
This is because your home page is declared as a React component rather than an element, which means the app won't be able to discover the plugins used on the homepage and therefore not load in the required APIs. There's a workaround to this which is to pass the plugin instance to the `createApp({ plugins: ... })`, but I'd recommend instead changing the shape of the homepage to this:

```tsx
    <Route path="/home" element={<HomepageCompositionRoot />}>
      {homePage}
    </Route>
```

And

```tsx

export const homePage = (
  <Page themeId="home">
    ...
  </Page>
);
```

@backstage/discoverability-maintainers it looks like the home page declaration uses this pattern in the example app in this repo, but the documentation recommends the component approach: https://backstage.io/docs/getting-started/homepage/#homepage. The documentation needs to be updated right?

**Comment by wss-rbunning** [comment]
@grvpandey11 I was able to get it working. @Rugvip's advice is correct, although I think it would be helpful if the documentation/ guide that is shown on the Backstage website for the homepage is updated to reflect the proper way of creating the homepage. 

The home page cannot be a functional component, it has to be a plain element. Here's the changes I would recommend that should get you up and running:

- Pull ```defaultConfig``` outside of ```DefaultTemplate```. This is probably a good idea anyways since it doesn't seem to need to change and having it inside the component means it would be reassigned anytime the component refreshed. 
- Convert ```DefaultTemplate``` to a plain element. Instead of assigning it to a function with a return statement, you can just assign it to everything you have after the return statement, parenthesis included. 

The result should look something like this:
HomePage.tsx:
```
import {
  HomePageStarredEntities,
  HomePageRandomJoke,
  CustomHomepageGrid,
} from '@backstage/plugin-home';
import { HomePageSearchBar } from '@backstage/plugin-search';
import { MicrosoftCalendarCard } from '@backstage/plugin-microsoft-calendar';
import React from 'react';

// This is the default configuration that is shown to the user
// when first arriving to the homepage.
const defaultConfig = [
  {
    component: 'HomePageSearchBar',
    x: 0,
    y: 0,
    width: 12,
    height: 5,
  },
  {
    component: 'HomePageRandomJoke',
    x: 0,
    y: 2,
    width: 6,
    height: 16,
  },
  {
    component: 'HomePageStarredEntities',
    x: 6,
    y: 2,
    width: 6,
    height: 12,
  },
];

export const HomePage = (
  <CustomHomepageGrid config={defaultConfig} rowHeight={10}>
    // Insert the allowed widgets inside the grid. User can add, organize and
    // remove the widgets as they want.
    <HomePageSearchBar />
    <HomePageRandomJoke />
    <MicrosoftCalendarCard />
    <HomePageStarredEntities />
  </CustomHomepageGrid>
);
```
And in App.tsx:
```
...
<Route path="/" element={<HomepageCompositionRoot />}>
      {HomePage}
 </Route>
...
```

You can also have a look at the homepage they have on the Backstage repo as an example: https://github.com/backstage/backstage/blob/92b39f13cd551129dc11ccefd53652568368c361/packages/app/src/components/home/HomePage.tsx#LL58C1-L123C3

**Comment by emmaindal** [comment]
Thanks all, I'll update the example app and documentation! 💯
