### ISSUE TITLE
🐛 Bug Report: New plugins are no longer badged in the Plugin Marketplace

### ISSUE THREAD

**Issue by efenner-cambia** [backstage/backstage#17877]
### 📜 Description

The [Plugin Marketplace](https://backstage.io/plugins/) on the microsite used to show a "New" tag in the corner of the cards for plugins that had recently been added. I have not seen that badge on any new plugins since the microsite Docusaurus 2 upgrade. As the plugin library continues to grow I want to continue to check out new plugins, but it is harder to identify them without the badge

### 👍 Expected behavior

There should still be a "New" badge indicating plugins that have recently been added to the marketplace

### 👎 Actual Behavior with Screenshots

No plugins have the badge any more

### 👟 Reproduction steps

Go to the[Plugin Marketplace](https://backstage.io/plugins/) on the microsite

### 📃 Provide the context for the Bug.

As the plugin library continues to grow I want to continue to check out new plugins, but it is harder to identify them without the badge

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Thanks for logging this. I'm pretty sure this was a "victim" of the migration to v2 of Docusaurus, if I remember correctly there was some performance issues and this got disabled. I'll try and find the details for whoever pick this up

**Comment by awanlin** [comment]
Here's the PR that added the "New" banner: https://github.com/backstage/backstage/pull/14254

And this is there the change should be made in the migrated version: https://github.com/backstage/backstage/blob/master/microsite/src/pages/plugins/index.tsx

**Comment by awanlin** [comment]
Sadly I can't find anything about why this didn't get migrated over, here's the meta issue for that: https://github.com/backstage/backstage/issues/12019

@jhaals @luchillo17 do you remember if there was any reason this got removed during the migration?

**Comment by luchillo17** [comment]
Probably my lacking knowledge of the features this page was supposed to have, this page is not from a Docusaurus plugin, instead, it's a custom React page, meaning when I refactored the page for v2 I missed anything about a `New` badge, or any other feature like that.

**Comment by efenner-cambia** [comment]
@luchillo17 I found this screenshot: 
![image](https://github.com/backstage/backstage/assets/105249079/b531824b-bd6b-483c-850e-a5ba118f13eb)

**Comment by luchillo17** [comment]
I'll speak with my team to add this to our board.
C.C: @waldirmontoya25

**Comment by luchillo17** [comment]
Nice this one went fast.

**Comment by efenner-cambia** [comment]
Very happy to see this come back! Thanks for jumping on it, @luchillo17

Have we validated that the contrast on the ribbon meets accessibility standards? To my eye, it seems a little harder to read than the older iteration

**Comment by luchillo17** [comment]
The Docusaurus 2 theme is indeed using a lighter primary color, and now that I look carefully I forgot to use bold weight fonts.

**Comment by luchillo17** [comment]
Hmm would like a designer input on the theme colors & stuf, I guess I could at least put a PR for the bold font...

**Comment by efenner-cambia** [comment]
That certainly helps!

I am not a designer, but looking at the UI, I am noticing that these ribbons are the only place where the green is used as a background for light colored text. It looks like currently the text is inheriting `--ifm-font-color-base` from the base `html` tag. Based on the ribbon color of `--ifm-color-primary`, I think `--ifm-color-primary-contrast-foreground` could be a good choice for the text color.  Alternatively, `--ifm-badge-color`, `--ifm-color-content-secondary`, or `--ifm-font-color-secondary` (which are all just pure white) could be semantically appropriate.

**Comment by efenner-cambia** [comment]
@luchillo17 is this something you would be able to change, or should I make a PR for it myself?

**Comment by luchillo17** [comment]
I am currently working on the Proxy, would look at this next week around Thursday maybe
