### ISSUE TITLE
🚀 Feature: Show logs when clicking step in Scaffolder UI

### ISSUE THREAD

**Issue by javoire** [backstage/backstage#17870]
### 🔖 Feature description

The steps in the stepper component are clickable after task completion:
<img width="591" alt="image" src="https://github.com/backstage/backstage/assets/642869/24296c1a-7f94-4983-a272-024c8f6af8d0">
Or rather, there's the MUI feedback effect when clicking, but nothing happens.

A intuitive expectation may be that _that step will show/expand_ to show the logs (both for success and failures). 

Though all logs are available here...
<img width="287" alt="image" src="https://github.com/backstage/backstage/assets/642869/8502fb36-6c67-4dda-ba5a-1ebb66c47aeb">

...this could be a nice UX enhancement.

### 🎤 Context

It's a UX enhancement 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by efenner-cambia** [comment]
Makes sense to me

**Comment by benjdlambert** [comment]
This is free if anyone would like to help contribute :pray:
