### ISSUE TITLE
🐛 Bug Report: Unable to use the Helm chart to deploy an instance

### ISSUE THREAD

**Issue by Seb147** [backstage/backstage#17890]
### 📜 Description

I'm trying to setup Backstage on a Kubernetes cluster, using this documentation : https://demo.backstage.io/docs/default/Component/backstage/getting-started/deployment-helm/

The Helm chart for the PostgreSQL dependency doesn't seem to exist anymore.

From what I've seen in the git history (more specifically here : https://github.com/backstage/backstage/commit/0e91c38450d1190fba36dcd355b53221ae8b238d), the version of the PostgreSQL instance was rolled back from a 11.x version to the current version specified in the backstage Chart (11.2.4 => 9.8.12), because of 

> I am reverting this because this was a breaking change and needs more work and testing.

I tried on the master branch of the backstage repository, and also on the latest tag (`v1.14.0`), and the behavior is the same.

### 👍 Expected behavior

The `helm dependency update` should complete successfully :

```
➜  backstage git:(v1.14.0) ✗ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

➜  backstage git:(v1.14.0) ✗ helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading postgresql from repo https://charts.bitnami.com/bitnami
Deleting outdated charts

```

### 👎 Actual Behavior with Screenshots

Result when executing helm dependency update :

```
➜  backstage git:(v1.14.0) ✗ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

➜  backstage git:(v1.14.0) ✗ helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: can't get a valid version for repositories postgresql. Try changing the version constraint in Chart.yaml
```

As we can see, this version of the postgresql Helm chart doesn't exist anymore :
```

➜  backstage git:(v1.14.0) ✗ yq -P '.dependencies[] | select(.name=="postgresql")' Chart.yaml
name: postgresql
condition: postgresql.enabled
version: 9.8.12
repository: https://charts.bitnami.com/bitnami

➜  backstage git:(v1.14.0) ✗ helm search repo 'bitnami/postgresql' --version 9.8.12

No results found
```

### 👟 Reproduction steps

```
git clone https://github.com/backstage/backstage.git
cd contrib/chart/backstage
helm dependency update
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @Seb147, sorry you ran into problems. I would highly recommend using the Documentation from https://backstage.io/ and not the Demo site. This is the current docs for Kubernetes deployment but it doesn't use Helm: https://backstage.io/docs/deployment/k8s. There is now an official Helm chart here though: https://github.com/backstage/charts

**Comment by benjdlambert** [comment]
I wonder if we should move this issue to the charts repo instead? :pray:

**Comment by Seb147** [comment]
Thanks for your reply @awanlin, I have other issues with this one, but at least I'm able to deploy an instance :)

**Comment by awanlin** [comment]
You're welcome. I'm a little confused, what does"I have other issues with this one" mean?
