### ISSUE TITLE
🐛 Bug Report: can't set update = true when submitting Github Pull Request in scaffolding

### ISSUE THREAD

**Issue by adamdabbracci** [backstage/backstage#17911]
### 📜 Description

When re-running a scaffolding workflow that submits a PR, if the PR already exists, you get the following error:

> Pull request creation failed; caused by Error: [octokit-plugin-create-pull-request] Pull request already exists: <YOUR PR>. Set update=true to enable updating

There is an [option in the Octokit plugin](https://github.com/gr2m/octokit-plugin-create-pull-request#usage) that would update the PR, but that option isn't exposed to Backstage.

### 👍 Expected behavior

There should be a way to override the `update` parameter available on [the Octokit plugin](https://github.com/gr2m/octokit-plugin-create-pull-request#usage). However, I can't find one documented anywhere. I think update=true would be a good default as well, but that might not be true for everyone.

### 👎 Actual Behavior with Screenshots

<img width="1507" alt="image" src="https://github.com/backstage/backstage/assets/3945646/b9e54bf3-2afd-4fb7-88a0-a65bfd9b6a37">

### 👟 Reproduction steps

1. Run a scaffolding workflow that uses `publish:github:pull-request` to publish a PR to an existing repo
2. Submit the PR successfully the first time
3. Go through the same workflow with the same values again
4. Receive the error "Pull request creation failed; caused by Error: [octokit-plugin-create-pull-request] Pull request already exists: <YOUR_PR>. Set update=true to enable updating"
5. There doesn't seem to be a way to set that value.

### 📃 Provide the context for the Bug.

We were experiencing [this known issue](https://github.com/backstage/backstage/issues/15002). The first run of the task would successfully submit a PR, but error out for the user due to the EventStream issue. If the user re-submitted the same scaffolding task again, it would throw the "set update=true" error, which confused the user.

### 🖥️ Your Environment

node: v16.15.1
yarn: 1.22.19
cli:  0.22.3 (installed)
backstage:  1.13.0

**Related Dependencies** (*note that I removed unrelated and private dependencies*)
  @backstage/app-defaults                          1.3.0
  @backstage/backend-app-api                       0.4.2
  @backstage/backend-common                        0.18.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.1
  @backstage/backend-tasks                         0.5.1
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.6
  @backstage/config-loader                         1.2.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.7.0
  @backstage/core-components                       0.13.0
  @backstage/core-plugin-api                       1.5.1
  @backstage/errors                                1.1.5
  @backstage/integration                           1.4.4
  @backstage/plugin-github-actions                 0.5.17
  @backstage/plugin-scaffolder-backend             1.13.0
  @backstage/plugin-scaffolder-common              1.2.7
  @backstage/plugin-scaffolder-node                0.1.2
  @backstage/plugin-scaffolder-react               1.3.0
  @backstage/plugin-scaffolder                     1.13.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
Think that we can add this as another option to the scaffolder input. :pray:

**Comment by electrofelix** [comment]
Still relevant
