### ISSUE TITLE
@backstage/catalog-model - Error: Unknown field relations

### ISSUE THREAD

**Issue by seanevans** [backstage/backstage#17917]
### 📜 Description

When adding "relations" to the catalog-info.yaml for a component I get the following error:

stack: >-
            Error: Unknown field relations
                at NoForeignRootFieldsEntityPolicy.enforce (/mnt/d/Projects/BackstageIO/web-backstage-app/node_modules/@backstage/catalog-model/dist/index.cjs.js:1044:15)
                at AllEntityPolicies.enforce (/mnt/d/Projects/BackstageIO/web-backstage-app/node_modules/@backstage/catalog-model/dist/index.cjs.js:1078:35)
                at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                at async DefaultCatalogProcessingOrchestrator.runPolicyStep (/mnt/d/Projects/BackstageIO/web-backstage-app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-6a9091b7.cjs.js:2745:30)
                at async DefaultCatalogProcessingOrchestrator.processSingleEntity (/mnt/d/Projects/BackstageIO/web-backstage-app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-6a9091b7.cjs.js:2678:16)
                at async processTask (/mnt/d/Projects/BackstageIO/web-backstage-app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-6a9091b7.cjs.js:1562:26)

### 👍 Expected behavior

The yaml appears to be correct when comparing it to the samples provided with backstage as well as the documentation.
I would expect that the catalog is loaded without error and the relations graph should be visible.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/643630/eff4e174-f816-4d53-940f-fdf066bed5a4)

### 👟 Reproduction steps

1. Create a git repo
2. Add a catalog-info.yaml
3. include the following

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: TestComponent
  description: A web UI using AI models. 
  labels:
    domain/custom: webai
  # Example for optional annotations
  annotations:
    domain/project-default: default-project
    domain/techdocs-ref: dir:.
  tags:
    - python
  links:
    - url: https://domain/tfs/ExperimentCollection/Experiment/_git/TestComponent
      title: TestComponent
      icon: dashboard
      type: website
relations:
  - type: providesApi
    targetRef: api:default/web-api
    target:
      kind: api
      namespace: default
      name: web-api
spec:
  type: website
  owner: Team default
  lifecycle: experimental
  system: default-internal

4. Browse to the component page in backstage and select this component.
5. The error should appear at the top.

### 📃 Provide the context for the Bug.

Inital look at the code suggests it may be using the default constructor with the following default fields. This does not include relations.

const defaultKnownFields = ["apiVersion", "kind", "metadata", "spec"];

If the following relation is tried in the file, we get envelope errors saying that fields like "name" are missing. So there are some checks that are working as expected.

relations:
  - type: providesApi
    targetRef: api:default/web-api
    target:
      kind: api
      namespace: default

### 🖥️ Your Environment

OS:   Linux 5.15.90.1-microsoft-standard-WSL2 - linux/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.14.0

Dependencies:
  @backstage/app-defaults                          1.3.1
  @backstage/backend-app-api                       0.4.3
  @backstage/backend-common                        0.18.5
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.2
  @backstage/backend-tasks                         0.5.2
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.7
  @backstage/config-loader                         1.3.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.8.0
  @backstage/core-components                       0.13.1
  @backstage/core-plugin-api                       1.5.1
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.3
  @backstage/integration-react                     1.1.13
  @backstage/integration                           1.4.5
  @backstage/plugin-api-docs                       0.9.3
  @backstage/plugin-app-backend                    0.3.45
  @backstage/plugin-auth-backend                   0.18.3
  @backstage/plugin-auth-node                      0.2.14
  @backstage/plugin-catalog-backend-module-azure   0.1.16
  @backstage/plugin-catalog-backend                1.9.1
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.30
  @backstage/plugin-catalog-import                 0.9.8
  @backstage/plugin-catalog-node                   1.3.6
  @backstage/plugin-catalog-react                  1.6.0
  @backstage/plugin-catalog                        1.11.0
  @backstage/plugin-github-actions                 0.5.18
  @backstage/plugin-org                            0.6.8
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.8
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.39
  @backstage/plugin-scaffolder-backend             1.14.0
  @backstage/plugin-scaffolder-common              1.3.0
  @backstage/plugin-scaffolder-node                0.1.3
  @backstage/plugin-scaffolder-react               1.4.0
  @backstage/plugin-scaffolder                     1.13.1
  @backstage/plugin-search-backend-module-catalog  0.1.1
  @backstage/plugin-search-backend-module-pg       0.5.6
  @backstage/plugin-search-backend-module-techdocs 0.1.1
  @backstage/plugin-search-backend-node            1.2.1
  @backstage/plugin-search-backend                 1.3.1
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.6.0
  @backstage/plugin-search                         1.3.0
  @backstage/plugin-tech-radar                     0.6.4
  @backstage/plugin-techdocs-backend               1.6.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.13
  @backstage/plugin-techdocs-node                  1.7.1
  @backstage/plugin-techdocs-react                 1.1.6
  @backstage/plugin-techdocs                       1.6.2
  @backstage/plugin-user-settings                  0.7.3
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.1
  @backstage/theme                                 0.3.0
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sennyeya** [comment]
Relations aren't supported in the `catalog-info.yaml` files. You'll have to register a processor to add the relations between entities. From [the documentation](https://backstage.io/docs/features/software-catalog/descriptor-format#common-to-all-kinds-relations), 

> Entity descriptor YAML files are not supposed to contain this field. Instead, catalog processors analyze the entity descriptor data and its surroundings, and deduce relations that are then attached onto the entity as read from the catalog.

Based on the example data you gave, I would look at the https://backstage.io/docs/features/software-catalog/descriptor-format#specprovidesapis-optional and https://backstage.io/docs/features/software-catalog/descriptor-format#specconsumesapis-optional options. They populate the relations with the same names.

**Comment by seanevans** [comment]
Thanks for the quick response @sennyeya 
I didn't read that section carefully enough. I see what you mean.
Thanks for the documentation links!
