### ISSUE TITLE
Running build-image in backend makes yarn postpack run twice for each package

### ISSUE THREAD

**Issue by jaygurnani** [backstage/backstage#1794]
Running the docker builds commands returns an error

## Expected Behavior
Build should complete successfully

## Current Behavior
$ backstage-cli postpack
$ backstage-cli postpack
success Wrote tarball to "/tmp/dist-workspaceNZqVLn/temp-package-8.tgz".
success Wrote tarball to "/tmp/dist-workspaceNZqVLn/temp-package-7.tgz".
$ backstage-cli postpack
success Wrote tarball to "/tmp/dist-workspaceNZqVLn/temp-package-9.tgz".
$ backstage-cli postpack
$ backstage-cli postpack
$ backstage-cli postpack

Error: ENOENT: no such file or directory, stat 'package.json-prepack'

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Error: ENOENT: no such file or directory, stat 'package.json-prepack'

Command 'yarn' exited with code 1

## Possible Solution
NA

## Steps to Reproduce
1. Follow the steps outlined here: https://github.com/spotify/backstage/blob/master/docs/getting-started/deployment-other.md

## Context
Get backstage running

## Your Environment
Node v12.15.0
MacBookPro Catalina
Version: 10.15.6
Yarn Version: 1.22.4

**Comment by Rugvip** [comment]
The `postpack` is currently invoked manually because of a bug in yarn, but if the bug was fixed it would be invoked twice and you'd get this error. Do you actually get yarn version `1.22.4` when running `yarn --version` inside the repo? We're using policies to pin it to `1.22.1` right now.

WIP fix for the bug in yarn: https://github.com/yarnpkg/yarn/pull/8190

**Comment by Rugvip** [comment]
#1796 fixes the build, but would still produce a warning in this case, which it shouldn't. Renaming and leaving this open until we've figured out why postpack would be run twice.

**Comment by jaygurnani** [comment]
Actually yeah you are right - I ran `yarn --version` in the wrong directory. It actually comes at 1.22.1 when I run it in the `backstage` repo.
