### ISSUE TITLE
🐛 Bug Report: Techdocs Flashing on Navigation

### ISSUE THREAD

**Issue by alper98** [backstage/backstage#17944]
### 📜 Description

Whenever you navigate around on a techdocs page (I.e clicking a navigation item, or pressing "Next/Previous" in the bottom, it "flashes" 1-2 times before it renders the next page. 

### 👍 Expected behavior

As you click a navigation item, the content that you were previously viewing should remain visible (and stable) until the new content is loaded. At that time, the content should change to the new content.

### 👎 Actual Behavior with Screenshots

It flashes whenever you navigate before it goes to the next page.

### 👟 Reproduction steps

1. Navigate to a doc set like https://demo.backstage.io/docs/default/component/backstage/getting-started/create-an-app/.
2. Click the next link down in the left hand nav
3. Notice the blinking page.
4. Sometimes it's a bar then blinking. Sometimes just blinking.

### 📃 Provide the context for the Bug.

This is incredibly distracting, and destroys the user experience for our users. As techdocs is one of our most visited features, we fear that this would potentially keep people away. 

### 🖥️ Your Environment

OS:   Darwin 22.4.0 - darwin/arm64
node: v16.16.0
yarn: 1.22.19
cli:  0.22.6 (installed)
backstage:  1.13.2

Dependencies:
  @backstage/app-defaults                          1.3.0
  @backstage/backend-app-api                       0.4.2
  @backstage/backend-common                        0.15.2, 0.18.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.1
  @backstage/backend-tasks                         0.4.3, 0.5.1
  @backstage/backend-test-utils                    0.1.36
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.6
  @backstage/config-loader                         1.2.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.7.0
  @backstage/core-components                       0.11.2, 0.12.4, 0.13.0
  @backstage/core-plugin-api                       1.5.1
  @backstage/dev-utils                             1.0.14
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.12
  @backstage/integration                           1.4.4
  @backstage/plugin-api-docs                       0.9.2
  @backstage/plugin-auth-backend                   0.18.2
  @backstage/plugin-auth-node                      0.2.13
  @backstage/plugin-catalog-backend-module-github  0.2.7
  @backstage/plugin-catalog-backend                1.9.0
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.29
  @backstage/plugin-catalog-import                 0.9.7
  @backstage/plugin-catalog-node                   1.3.5
  @backstage/plugin-catalog-react                  1.3.0, 1.5.0
  @backstage/plugin-catalog                        1.10.0
  @backstage/plugin-events-backend-module-aws-sqs  0.1.6
  @backstage/plugin-events-backend-module-github   0.1.6
  @backstage/plugin-events-backend                 0.2.5
  @backstage/plugin-events-node                    0.2.5
  @backstage/plugin-explore-backend                0.0.6
  @backstage/plugin-explore-common                 0.0.1
  @backstage/plugin-explore-react                  0.0.28
  @backstage/plugin-explore                        0.4.2
  @backstage/plugin-github-actions                 0.5.17
  @backstage/plugin-github-deployments             0.1.48
  @backstage/plugin-home                           0.4.31, 0.5.1
  @backstage/plugin-org                            0.6.7
  @backstage/plugin-permission-backend             0.5.19
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.7
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.38
  @backstage/plugin-scaffolder-backend             1.13.1
  @backstage/plugin-scaffolder-common              1.2.7
  @backstage/plugin-scaffolder-node                0.1.2
  @backstage/plugin-scaffolder-react               1.3.0
  @backstage/plugin-scaffolder                     1.13.0
  @backstage/plugin-search-backend-module-catalog  0.1.0
  @backstage/plugin-search-backend-module-explore  0.1.0
  @backstage/plugin-search-backend-module-pg       0.5.5
  @backstage/plugin-search-backend-module-techdocs 0.1.0
  @backstage/plugin-search-backend-node            1.2.0
  @backstage/plugin-search-backend                 1.3.0
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.5.2
  @backstage/plugin-search                         1.2.0
  @backstage/plugin-tech-radar                     0.6.3
  @backstage/plugin-techdocs-addons-test-utils     1.0.12
  @backstage/plugin-techdocs-backend               1.6.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.12
  @backstage/plugin-techdocs-node                  1.7.0
  @backstage/plugin-techdocs-react                 1.1.5
  @backstage/plugin-techdocs                       1.6.1
  @backstage/plugin-user-settings                  0.7.2
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.0
  @backstage/theme                                 0.2.19
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by alper98** [comment]
I will link to an issue i found that explains it as well, but as its closed i figured i would open this one hoping it would get noticed.
https://github.com/backstage/backstage/issues/13696

**Comment by benjdlambert** [comment]
@alper98 I will close this issue as a duplicate and re-open the other one as it looks like theres more information in the other one.
