### ISSUE TITLE
🚀 Feature: Support not queries in CatalogClient

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#17987]
### 🔖 Feature description

Allow specifying `not` queries in the CatalogClient EntityFilterQuery. 

### 🎤 Context

Currently, it's not possible to fetch for example all entity kinds except Components, all entities without the specific owner or any other negation. This feature would enhance the filtering quite a lot and allow more things to be done with the catalog client.

### ✌️ Possible Implementation

See parsing here https://github.com/backstage/backstage/blob/7dd8b39a92d9824ccee196e2cfd41fd92c47e250/plugins/catalog-backend/src/service/request/parseEntityFilterParams.ts#L41

Would it be enough to have the filter to start with for example exclamation mark so that it's considered to be not?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Closing for now, I hope that's OK. Let us know if there's anything else you want to mention here

**Comment by hspitzley-czi** [comment]
@freben has there been any progress on a new client that would allow negative conditions or "greater than" / "less than" qualifiers?

**Comment by freben** [comment]
No, the filters are the same as always.
