### ISSUE TITLE
🚀 Feature: Link to source template yaml file in Scaffolder UI

### ISSUE THREAD

**Issue by javoire** [backstage/backstage#17986]
### 🔖 Feature description

A link from the scaffolder form page to the source file of the template.yaml

### 🎤 Context

When wanting to make modifications to a scaffolder template, by having a direct link to the template yaml file on the form page it saves a ton of time finding the yaml file to edit. 

### ✌️ Possible Implementation

E.g could in the top right corner of the header
<img width="1321" alt="image" src="https://github.com/backstage/backstage/assets/642869/19279647-efad-4d06-abe6-70a4a8ac99eb">

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by kosukeKK** [comment]
Sorry to be so abrupt, but can you assign me this issue?
i already created PR .

https://github.com/backstage/backstage/pull/22058

**Comment by Rugvip** [comment]
Closing as implemented by #23363
