### ISSUE TITLE
🚀 Feature: Group Ownership/Leadership

### ISSUE THREAD

**Issue by mharrah** [backstage/backstage#17996]
### 🔖 Feature description

I would like a way to model (in the YAML file) who the leader(s) of a group is/are.

All of the members of a group are currently treated as peers, and there is no way to identify which of the members is the manager/leader/chair/spokesperson/point-of-contact. In a corporate environment, it will be the norm (or at least incredibly common) for any group of people to have a chair or manager who has accountability/responsibility for the group as a whole (at some level above that of a peer team member), but there is no clear way to model this in the catalog with the current YAML formats. 
**This makes it impractical to find the right person in an organization that is responsible** for its APIs/Components/Resources and the teams that own those entities...a pretty important and useful bit of metadata about code.

### 🎤 Context

In my use-case, we would want to know who in a group is the leader, and who the leader is of its parent group, recursively, so we can:
1. Determine what are all the items that a user is the accountable/responsible party for (both directly and indirectly) by virtue of being the leader of a group that owns those items
2. Know what individual(s) are directly (and indirectly) responsible/accountable for any given entity in the catalog 
3. Use this information to roll up metrics about entities to leaders at all the various levels of the organization

### ✌️ Possible Implementation

I would like to be able (and not required) to define, in a group's `spec` section, a user entity reference to its leader, and have the catalog manage a ledBy/leaderOf relationship between users and groups, similar to but distinguishable from membership. 

- The ownerOf/ownedBy relationship would be usable in theory, but there is no owner support on the Group entity kind...and the semantics of "owner" for a group are not _exactly_ the best word choice.  "Leader" is the most generic term that I can think of. 
- Using an annotation on the group to be an entity reference to the leader of the group would be possible without changing the backend model, but has a few serious shortcomings:
  - Annotations only support single-string key/value pairs
    - There would be no way to model the reverse relationship where a user leads multiple groups
    - There's no way to model a user with multiple leaders (this is a special case that might occur, but is not the norm)
  - Annotations are a pretty kludgy way to handle a relationship between catalog entities when there is already support for other relationships between entities.
  - While it would be easy to tell who the leader is of a given group with an annotation on the group, finding the groups that a user leads would require scanning through all the groups' annotations for matches, which would be rather inefficient at scale (O(n<sup>2</sup>) exponential??)
- Using Systems and Domains would support assigning owners to larger organizational items, but would only support two "levels" above APIs/Components/Resources
- The best solution I can think of would be to implement a new leaderOf/ledBy relationship between Users and Groups
  - Easiest to implement would be a group can have zero-or-one user as its leader, and one user can lead many groups
    - I put in a PR to make this extension to the catalog, but the request was turned down as too fundamental to the core of the catalog backend model
  - A many-to-many relationship would also work, but could become difficult

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mharrah** [comment]
Relevant discussion thread on Discord: https://discord.com/channels/687207715902193673/1088175199091957890

**Comment by freben** [comment]
This would fit [as a private extension](https://backstage.io/docs/features/software-catalog/extending-the-model) to the model.

I agree that a `ledBy` edge being defined from the `Group` side (in the form of `spec.leader` or whatnot) is the right approach! And it'll be accompanied by an automatic reverse `leaderOf` edge of course; no need to have it defined from the `User` side as well.

**Comment by jgrigg** [comment]
We've run up against a slightly different use-case. Before i investigate an extension I'm wondering if you'd be open to a little change? We use the github org provider to pull in github teams. However in our world (SEEK) we are trying to move away from github teams as being 'owners' toward them being thing that are owned. We have a separate `Group` entity representing owners. The obvious choice here is to treat github teams as something that has `spec.owner` and therefore can be owned e.g a `Resource`. However we loose all sorts of other goodies when we do that, specifically membership and hierarchy.

Would supporting a `spec.owner` field that behaves much like any other _ownable_ entity on the `Group` kind be something you'd be open to?

**Comment by mharrah** [comment]
Hi jgrigg - if there were an owner supported in the catalog model for Groups, I would already be using that! I think that there are some connotation problems by saying a group of people is owned -- some folks might object to that. 

That said, either way (calling it the spec.owner or calling it the spec.leader) you'd either need to do it as a private extension (as freben said), or the backstage team would have to be open to modifying the core catalog model, which they've been unwilling to do (at least so far).  

I would think that identifying some sort of "responsible party" for a group is such a common case among the types of organizations likely to adopt Backstage, that I find it surprising that the model doesn't have that support already out of the box. It seems that a lot of adopters either need to custom-write a private extension that would be very similar to that of many other companies, or that adopters need to just live without being able to tell from Backstage who the point-person is for groups and having to guess who to contact as a spokesperson, or look in some other source of truth who is leading that group.

But I recognize that I don't have the same wider perspective as the backstage team and why this might be impractical/impossible in ways I haven't considered.

**Comment by jgrigg** [comment]
Thanks for your feedback Matthew. I might open a PR and see where it goes. It's good to know there's other in a similar predicament as us. I'm loathed to do down the private extension route so as to avoid a diverging fork.

**Comment by awanlin** [comment]
Hi @jgrigg, I probably wouldn't open a PR for this, but I see you did already, seeing as one of the Core Backstage Maintainers - @freben  in this case - has already suggested the way forward for this is by extending the model.

**Comment by jgrigg** [comment]
Yes sorry too late. I think the tact I'm going with is somewhat more in line with existing ownership semantics i.e the `owner` field as opposed to the `leader` field so I'm holding on to a sliver of hope ;)

**Comment by awanlin** [comment]
As for this issue I really think the focus should be on making it easer, well documented, and less worrisome to extend the model. We've done this ourselves with great success specifically around the User and Group Kinds. We found simply adding in a Job Title solved the "leader" question but also the "Product Owner", "Architect" and other similar questions.

What I've seen over the last two years contributing and helping people on Discord is that when it comes to Org concerns on the surface it's easy to think there is a lot of things in common but once you get past that every Org has different patterns of organization. This issue is a good example the two people who had posted both wanted to use the same field in different ways. Which is why I think making customization easier is the better long term solution.

**Comment by jgrigg** [comment]
Thanks Andre. You're right I'm scared of customising the model because of the potential for maintenance burden. Sounds like it's not as scary as i think. Are there any public examples of this you could point me to?

**Comment by awanlin** [comment]
I'll be honest there really isn't and I'm part of that problem as I've had it on my TODO list to build up the documentation in this area and simply have not been able to get to it. The documentation on creating providers and processors are good. Where the gaps are is around how to extend the existing types. I feel like if you search Discord for anything that `freben` has posted, though it's going to be a lot, you'd find everything you need. I'm for sure not suggesting this is how it should be though.

For our simplistic needs we simply copied the Kinds we wanted to extend from here: https://github.com/backstage/backstage/tree/master/packages/catalog-model/src/kinds. They all got names with our Org as the prefix so `KeyloopUser` and `KeyloopGroup`. The we added the properties we wanted under the `spec`. Then in our custom views we could just case the entity as one of those and were able to get at the things we needed. We also added a new kind of our own `Subdomain` which is a combination of Domain and System Kinds following the same pattern. Then we built a processor to handle emitting the needed relations

**Comment by jgrigg** [comment]
Awesome that's a good start I'll have a tinker :) Thank you!

**Comment by jgrigg** [comment]
Yeah i think you'd need to augment the ingestion somehow. The github catalog plugin (users and groups) takes a transform function these days so you can enrich there. we use this pattern quite a bit reaching out to s3 resources for example to enrich various things.

**Comment by awanlin** [comment]
@mharrah @jgrigg looks like perhaps there has been some change on this as PR #18751 seems to be adding this in (at least for @jgrigg use case but I think @mharrah  said that would work for them as well)

**Comment by pjungermann** [comment]
I've implemented the following for our org:

```
Group:
spec.leaders (array)

User:
spec.leaderOf (array)

relations:
ledBy / leaderOf
```

An alternative based on lead vs leader (some would have preferred lead):

```
Group:
spec.leads (array)

User:
spec.leadOf (array)

relations:
ledBy / leadOf
```

While doing so, I found it not so easy to extend an existing kind as you cannot reference it in the schema. Only Entity and a few others have been added to ajv for validation and URL refs are not supported either. I will create a separate issue for that topic, though.

**Comment by freben** [comment]
@pjungermann Additions on top of the standard model, like this seems to be, can be done "additively" by making a new processor that _only_ deals with the new fields. Was that what you did, and did you hit issues doing so? The intent is, that the `spec` is "open" (doesn't reject unknown keys) in the core schemas

**Comment by pjungermann** [comment]
@freben Yeah, just wanted to share our current approach related to these issues/RFCs. Their outcome could potentially supersede our solution.

I've created a similar `catalog-model` package internally extending the `@backstage/catalog-model` package to provide types, schemas, and validators for our extensions. I've used a processor similar to the `BuiltInKindsProcessor` to validate the extended core kinds as well as emit the relations.

Providing a schema that extends a core kind schema was a bit tricky as it cannot be used at a `ref` (only `Entity` and other `refDependencyCandidates` can be used there). And `ajvCompiledJsonSchemaValidator` could be exported as well. I've ended up creating a schema for the extension only and then, I've created a combined validator out of the core kind's validator and one for the extension only.

Of course, there might be different approaches to that.

**Comment by freben** [comment]
Yeah the "extend an existing schema" thing is not very fleshed out; it's a first stab at how that could be done, and I'm not sure it's all that useful. For example, the way refs work, as in not being able to reference files with it etc - it's pretty limiting.

I'd say at this point, the blessed path is mostly to add new processors that "stack" on top of the builtin one, and them doing whatever _they_ feel is most productive when validating the delta. For example using zod or whatnot, and ignoring the whole pre-existing schemas business.

**Comment by dweber019** [comment]
Just released the following plugin, which could support some use cases here
https://github.com/dweber019/backstage-plugins/tree/main/plugins/relations

Feedback welcome 😉
