### ISSUE TITLE
[MUI v5] Type Error when using Icons from @mui/icons-material

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#18018]
### 📜 Description

When upgrading to MUI v5 we are getting a type error when using Icons from `@mui/icons-material`. We see this in the following places:

- The `icon` prop of the `SidebarItem`, `SidebarSubmenuItem`, and `MyGroupsSidebarItem` components
- The `UNSTABLE_extraContextMenuItems` prop of the `EntityLayout` component
- When passing in icons to the `icons` section of `createApp` in the `App.tsx`

The error is:

```text
Type 'OverridableComponent<SvgIconTypeMap<{}, "svg">> & { muiName: string; }' is not assignable to type 'ComponentType<{ fontSize?: "default" | "large" | "small" | undefined; }>'.
  Type 'OverridableComponent<SvgIconTypeMap<{}, "svg">> & { muiName: string; }' is not assignable to type 'FunctionComponent<{ fontSize?: "default" | "large" | "small" | undefined; }>'.
    Types of parameters 'props' and 'props' are incompatible.
      Type 'PropsWithChildren<{ fontSize?: "default" | "large" | "small" | undefined; }>' is not assignable to type '{ component: any; } & { children?: ReactNode; classes?: Partial<SvgIconClasses> | undefined; color?: OverridableStringUnion<"inherit" | "disabled" | "primary" | ... 5 more ... | "warning", SvgIconPropsColorOverrides> | undefined; ... 6 more ...; viewBox?: string | undefined; } & CommonProps & Omit<...>'.
        Property 'component' is missing in type 'PropsWithChildren<{ fontSize?: "default" | "large" | "small" | undefined; }>' but required in type '{ component: any; }'.t
```

### 👍 Expected behavior

You should be able to use icons from `@mui/icons-material` without any type errors

### 👎 Actual Behavior with Screenshots

We get this error:

```text
Type 'OverridableComponent<SvgIconTypeMap<{}, "svg">> & { muiName: string; }' is not assignable to type 'ComponentType<{ fontSize?: "default" | "large" | "small" | undefined; }>'.
  Type 'OverridableComponent<SvgIconTypeMap<{}, "svg">> & { muiName: string; }' is not assignable to type 'FunctionComponent<{ fontSize?: "default" | "large" | "small" | undefined; }>'.
    Types of parameters 'props' and 'props' are incompatible.
      Type 'PropsWithChildren<{ fontSize?: "default" | "large" | "small" | undefined; }>' is not assignable to type '{ component: any; } & { children?: ReactNode; classes?: Partial<SvgIconClasses> | undefined; color?: OverridableStringUnion<"inherit" | "disabled" | "primary" | ... 5 more ... | "warning", SvgIconPropsColorOverrides> | undefined; ... 6 more ...; viewBox?: string | undefined; } & CommonProps & Omit<...>'.
        Property 'component' is missing in type 'PropsWithChildren<{ fontSize?: "default" | "large" | "small" | undefined; }>' but required in type '{ component: any; }'.t
```

### 👟 Reproduction steps

To keep things simple I'm going to base this on the main Backstage repo but you can easily do the same with a fresh instance created with `npx @backstage/create-app@latest`

1. Add `"@mui/icons-material": "^5.11.16"` to the `package/app/package.json`
2. Run `yarn install`
3. In the `packages/app/src/components/Root/Root.tsx` change this import `import HomeIcon from '@material-ui/icons/Home';` to be like this `import HomeIcon from '@mui/icons-material/Home';`
4. Run `yarn tsc`

Notice: You'll get a type error

### 📃 Provide the context for the Bug.

While upgrading to MUI v5 we ran into a number of cases like this. Now we can work around this by adding `as IconComponent` but we feel this should probably been something that is resolved in the Backstage itself as it would make this upgrade smoother and with less manual changes

### 🖥️ Your Environment

This really isn't an environment specific issue more around the usage of `@mui/icons-material`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
I've been playing around to see if I could come up with a fix for this before I submit a PR. The type for the `IconComponent` is located here: https://github.com/backstage/backstage/blob/36a139d1362f73f2075eb1ba1a928442cfe99a33/packages/core-plugin-api/src/icons/types.ts#L35

If I change this to be like this the errors for away:

```ts
export type IconComponent =
  | ComponentType<{
      fontSize?: 'default' | 'small' | 'large' | undefined;
    }>
  | ComponentType<{}>;
```

But I think this might be very naive on my part?

**Comment by tudi2d** [comment]
This is a good discovery. I ran into a similar issue[ when hacking on MUI v5 `core-components`](https://github.com/backstage/backstage/pull/17713/files#diff-d0f36083b04e80ffa6516008f14d0f788088725580f15e52d7575600fead6afcR249-R251). I temporarily solved it like the following:

```ts
type SidebarItemBaseProps = {
    icon: typeof SvgIcon;
    text?: string`
...
```

We might want to rethink the `IconComponent` type as the 2 year old comment says: 

>"If you have the need to forward additional props from SvgIconProps, you can
> * open an issue or submit a PR to the main Backstage repo. When doing so please
> * also describe your use-case and reasoning of the addition."

**Comment by tudi2d** [comment]
yes, you are right! it's not great. hopefully I have some time tommorrow to look at this & related MUI 5 issues

**Comment by freben** [comment]
I think we're generally open and grateful for the help investigating and suggesting a fix. I know that the IconComponent was added quite some time back because of similar type issues and we wanted to narrow the type to the absolute minimum that we needed at the time to avoid minor inconsequential type differences causing issues. Now, it seems like even this very narrow slice of the type still can cause issues :)

Sidestepping it with some clever typeof sounds compelling - if it actually works in the mixed-mui-major case etc.

**Comment by tudi2d** [comment]
added a PR with a possible solution, which worked for me - happy about feedback

**Comment by awanlin** [comment]
Sadly it seems this error has not been resolved or has cropped up in some other variation. This came up again recently in this Discord thread: https://discord.com/channels/687207715902193673/1192389833235120239. I took a run at migrating the Demo site as that needs to happen eventually anyway and ran into the error there as well: https://github.com/backstage/demo/pull/212

**Comment by awanlin** [comment]
What's interesting is that the original error message in this Issue is only there once but the others are now just this:

`Type 'OverridableComponent<SvgIconTypeMap<{}, "svg">> & { muiName: string; }' is not assignable to type 'IconComponent'.`

See the detailed errors here: https://github.com/backstage/demo/actions/runs/7425731911/job/20207991237?pr=212

**Comment by rmwondolleck** [comment]
In the process of upgrading and running into the same issue as well.

```
$ tsc
packages/app/src/App.tsx:101:9 - error TS2322: Type 'OverridableComponent<SvgIconTypeMap<{}, "svg">> & { muiName: string; }' is not assignable to type 'IconComponent'.

101         code: CodeIcon,
            ~~~~

packages/app/src/App.tsx:102:9 - error TS2322: Type 'OverridableComponent<SvgIconTypeMap<{}, "svg">> & { muiName: string; }' is not assignable to type 'IconComponent'.

102         alarm: AlarmIcon,
            ~~~~~
```

**Comment by awanlin** [comment]
This needs to be fixed as it's blocking clean migrations to MUI v5

**Comment by praphull-purohit** [comment]
I tried migrating to MUI v5 today, before upgrading backstage to 1.24.0. I've resolved all other issues, but stuck on this one. If there's any workaround available, please share. For now, I'm postponing MUI v5 migration in our instance for later

**Comment by webark** [comment]
we do like this.

`icon={() => <Category />}`

so you get like

```
  icons: {
    alert: () => <Alarm />,
    menuBook: () => <MenuBook />,
    code: () => <Code />,
    'kind:product': () => <Flare />,
    'kind:feature': () => <DonutSmall />,
  },
```
or 
```
<SidebarItem icon={() => <Category />} to="catalog" text="Catalog" />
```

**Comment by johnnyhuy** [comment]
Did a type assertion as a workaround:

```tsx
import { IconComponent } from '@backstage/core-plugin-api';

...
<SidebarItem icon={Home as IconComponent} to="catalog" text="Home" />
```

Hope that helps.

**Comment by awanlin** [comment]
Thanks @johnnyhuy that does work but really it should not be needed. Everyone who goes to do the migration would need to do this and in some cases you might have many files to updates. We should really fix this so it "just works" without error. 👍

**Comment by benjdlambert** [comment]
Hmm, not sure what the `muiName` prop is, but it look like the reason that this isn't compatible. Wonder if we can work around that somehow to statisfy the type.

**Comment by secustor** [comment]
I have found this in the docs: 

> If you encounter this issue, you need to use the same tag for your wrapping component that is used with the wrapped component. In addition, you should forward the properties, as the parent component may need to control the wrapped components props.

```typescript
const WrappedIcon = props => <Icon {...props} />;
WrappedIcon.muiName = Icon.muiName;
```
https://v4.mui.com/guides/composition/#wrapping-components
https://mui.com/material-ui/guides/composition/#wrapping-components

**Comment by camilaibs** [comment]
Hi @awanlin, do you think this would be the proper solution you are hoping for? If so, would you like to try implementing it?

> I have found this in the docs:
> 
> > If you encounter this issue, you need to use the same tag for your wrapping component that is used with the wrapped component. In addition, you should forward the properties, as the parent component may need to control the wrapped components props.
> 
> ```ts
> const WrappedIcon = props => <Icon {...props} />;
> WrappedIcon.muiName = Icon.muiName;
> ```
> 
> https://v4.mui.com/guides/composition/#wrapping-components https://mui.com/material-ui/guides/composition/#wrapping-components

**Comment by awanlin** [comment]
I'll try and take a look but I'm not sure how soon that will be 🤔

**Comment by secustor** [comment]
As [v6](https://github.com/mui/material-ui/releases/tag/v6.0.0) has been released now and [v7](https://github.com/mui/material-ui/issues/43629) seems to remove commonjs. I have taken a look myself again. 

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/59e91ff4-86a1-42a1-90c0-ae2e34d5cd28">

From what I could figure out the issue seems to be the `component` attribute of `OverrideableComponent`s first overload.

https://github.com/mui/material-ui/blob/dcc17031aa37b251678c39628b15637ec758d6b4/packages/mui-material/src/OverridableComponent.d.ts#L15-L22. 

Usually this shouldn't matter as it is only a overload and therefore TS should pick the default option without the component in the props

https://github.com/mui/material-ui/blob/dcc17031aa37b251678c39628b15637ec758d6b4/packages/mui-material/src/OverridableComponent.d.ts#L24. 

But the SvgIcon sets an optional component prop, which results in choosing the overload. 
https://github.com/mui/material-ui/blob/dcc17031aa37b251678c39628b15637ec758d6b4/packages/mui-material/src/SvgIcon/SvgIcon.d.ts#L110

I have tried to solve this with conditional types so but failed. 
Not sure how to solve this without importing the types from material ui at least as a dev dependency.

**Comment by freben** [comment]
I've been poking at this for a bit.

This does not work:

```ts
export type IconComponent = ComponentType<
  | {
      fontSize?: 'large' | 'small' | 'default' | 'inherit';
    }
  | {
      fontSize?: 'medium' | 'large' | 'small' | 'inherit';
    }
>;
```

But this does:

```ts
export type IconComponent = ComponentType<
  {
    fontSize?: 'medium' | 'large' | 'small' | 'inherit';
  }
>;
```

Which is odd. It seems that the very act of making it a union type breaks inference. Now I'm considering whether it's fine to just use the latter form, and ship that as a breaking change. You can pass in MUI4 and MUI6 icons just fine to that (e.g. when passing them to `createApp`). The result is just that end users now see the breaking change that they no longer can render icons with `fontSize="default"` - but that was probably not safe to do either way.

**Comment by freben** [comment]
Alright, attempted to make a PR that takes away the old font size option.
