### ISSUE TITLE
🐛 Bug Report: Accessibility "Skip to content" link goes to the wrong location

### ISSUE THREAD

**Issue by matthewpennell** [backstage/backstage#18042]
### 📜 Description

When tabbing through links on the page using the keyboard or a screenreader, there is an invisible link (a button) at the top of the sidebar navigation labelled "Skip to content". Activating that link jumps the focus of the keyboard/screenreader down to the main content of the page (the first `<article>` element, that appears right after the current plugin navigation bar).

### 👍 Expected behavior

It seems that Backstage has implemented WCAG's recommended [Technique G1](https://www.w3.org/WAI/WCAG21/Techniques/general/G1.html) to bypass repeated blocks of content and allow the user to jump directly to the content.

However, it is my opinion that the term "repeated block" on every Backstage page could only accurately be applied to the sidebar navigation. The plugin-based architecture means that the header and navigation of a plugin are _not_ the same on every page, and therefore are not a "repeated block" of content.

Therefore, I think that the "Skip to content" link should properly send the keyboard/screenreader focus to the H1 heading in the header/banner. This would allow screenreader users to understand what page they are on, and access the plugin navigation items. (Arguably it might make sense to implement a second "Skip to content" link in that header, to jump past the header and navigation. Or alternatively, provide multiple "skip links" in the original location, allowing the user to "Skip to banner", "Skip to main content", "Skip to navigation", etc.)

### 👎 Actual Behavior with Screenshots

N/A

### 👟 Reproduction steps

1. Open Backstage page.
2. Use the keyboard to tab through all links.
3. Tab to the first invisible link on the page to reveal "Skip to content" button.
4. Activate button with spacebar.
5. Note focus has moved down to the main body of the page, bypassing the sidebar, header and plugin navigation.

You can also reproduce this with Voiceover or other screenreader software. Note that in many cases there is no heading present at the top of the main body of the page, meaning that screenreader users are given no context for where their focus has moved to.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by snehaljos** [comment]
Hi can i work on this issue

**Comment by soapraj** [comment]
I can assign this to you @snehaljos 

Let us know if you need any help.

**Comment by snehaljos** [comment]
oh thank you

**Comment by snehaljos** [comment]
Hi raised PR for this issue.https://github.com/backstage/backstage/pull/18418

**Comment by snehaljos** [comment]
Already made the changes you can check in the PR.

**Comment by camilaibs** [comment]
Hello @matthewpennell, thanks again for reporting this issue, we are closing this issue since https://github.com/backstage/backstage/pull/18418 has been merged 🙂 .
Thanks also @snehaljos for contributing with us, hope to see you creating other pull requests 🙌🏻
