### ISSUE TITLE
🐛 Bug Report: <Rename the child YAML file name causing the Orphaning>

### ISSUE THREAD

**Issue by alexjia823** [backstage/backstage#18044]
### 📜 Description

I have one parent yaml file which is named parent.yaml, and one child yaml file named relations.yaml which is included in the parent.yaml. 
Firstly I changed the relations.yaml name to childen.yaml and also changed the corresponding lines in parent.yaml from relations.yaml to children.yaml. However, the entities in the children.yaml still became orphan entities and start not work, so what can I do to make these orphan entities back to normal? I tried to restart backstage but the error still exists.

### 👍 Expected behavior

After rename the yaml filename, the entities in the renamed yaml still work.

### 👎 Actual Behavior with Screenshots

After rename the yaml filename, the entities in the renamed yaml became orphan and start not work.

### 👟 Reproduction steps

1. Change the filename of children YAML.
2. Change the corresponding lines in the parent YAML.
3. the entities in the children YAML didn't work and became orphan entities.
4. orphan entities still didn't work after restarting backstage.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by alexjia823** [comment]
Hi Jhaals:

It's so nice to hear back from you, I included the parent.yaml in app-config.yaml:
Locations:
    - type: url
      target: https://<repo url>/parent.yaml
      rules:
        - allow: [Component, System, API, Group, Resource, Location, Domain, User]
      
This is the content of parent.yaml:

apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: source
spec:
  type: url
  targets:
    - ./children.yaml    #This yaml filename changed from relations.yaml to children.yaml which cause the problem


This is the content of children.yaml, all of these entities below start not to work after renaming the relations.yaml to children.yaml:

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: caas
  description: Communications 
spec:
  owner: caas
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: noah
  description: Noah 
spec:
  type: team
  profile:
    displayName: Noah
    email: damo@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-b@example.com.svg?background=%23fff&margin=25
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: yao
spec:
  profile:
    displayName: yao
    email: yao
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [noah]

**Comment by jhaals** [comment]
Thanks for the clarification, in your case I believe the expected behaviour is to have the entity be orphaned because it's no longer referenced from the location. To make it go away you can however set the `catalog.orphanStrategy` to `delete` which will delete instead of keep the entity orphaned.

**Comment by alexjia823** [comment]
Thank you, let me try it and I will get back to you soon.

**Comment by alexjia823** [comment]
Hi jhaals:

I have set the catalog.orphanStrategy to delete and the orphaned entity is deleted by the system, but they couldn't be reloaded into the system using the static configuration even after I reboot the backstage, this is my configuration of locations in the app-config.yaml:

    - type: url
      target: https://<repo url>/parent.yaml
      rules:
        - allow: [Component, System, API, Group, Resource, Location, Domain, User]

Best.

**Comment by Rugvip** [comment]
@alexjia823 does the issue resolve itself after a while? There's a processing interval that you need to wait for, which is stored in the DB unless you're running with SQLite.

If it doesn't fix itself in a while, are there any errors in the logs indicating a failure to read the catalog location? You can also try looking up the parent location in the frontend catalog UI to see if it lists any errors there.
