### ISSUE TITLE
🐛 Bug Report: `AwsOrganizationCloudAccountProcessor` no longer respects provided `roleArn` in configuration

### ISSUE THREAD

**Issue by alecjacobs5401** [backstage/backstage#18052]
### 📜 Description

In our Backstage instance, we utilize the `AwsOrganizationCloudAccountProcessor` to consume AWS accounts from our Principal Org (Backstage runs in a different AWS account). To do this, we assume a role outside of the AWS account our Backstage instance runs in order to have access to the `ListAccounts` organization endpoint.

Here is what our configuration looks like for `AwsOrganizationCloudAccountProcessor`
```yaml
catalog:
  processors:
    awsOrganization:
      provider:
        roleArn: 'arn:aws:iam::<other-account-id>:role/<list-organizations-role-name>'
```

After upgrading to `1.14.1`, we noticed that there was now new necessary required configuration to support the new [`DefaultAwsCredentialsManager`](https://github.com/backstage/backstage/blob/v1.14.1/packages/integration-aws-node/src/DefaultAwsCredentialsManager.ts) since the `AwsOrganizationCloudAccountProcessor` uses the credentials manager to find the Credentials to use for the `<other-account-id>` specified in our `roleArn` ([source](https://github.com/backstage/backstage/blob/v1.14.1/plugins/catalog-backend-module-aws/src/processors/AwsOrganizationCloudAccountProcessor.ts#L59-L63))

_However_, the creds determined there **do not** respect the `catalog.processors.awsOrganization.provider.roleArn` configuration since `awsCredentialsManager.getCredentialProvider()` does not use the provided ARN to assume the role _unless_ we use the following full set of configuration

```yaml
catalog:
  processors:
    awsOrganization:
      provider:
        roleArn: 'arn:aws:iam::<other-account-id>:role/<list-organizations-role-name>'

aws:
  accounts:
    - accountId: "<other-account-id>"
      roleName: <list-organizations-role-name>
```

We want to always utilize the default provider credential chain and be able to optionally assume roles for specific processors/providers. This configuration makes it so that is not possible, we will _always_ cache credentials assumed as `<list-organizations-role-name>` anywhere else we want to access the `<other-account-id>` AWS account.

### 👍 Expected behavior

The `AwsOrganizationCloudAccountProcessor` should still properly assume the `catalog.processors.awsOrganization.provider.roleArn` role with the following minimal configuration

```yaml
catalog:
  processors:
    awsOrganization:
      provider:
        roleArn: 'arn:aws:iam::<other-account-id>:role/<list-organizations-role-name>'

aws:
  accounts:
    - accountId: "<other-account-id>"
```

This makes it so that we always use the default credentials chain and are able to assume arbitrary roles for specific purposes

### 👎 Actual Behavior with Screenshots

We must globally configure a specific `roleName` for a specific `accountId`, which prevents us from having dedicated roles for specific providers/processors 

Without specifying `roleName` in the `aws.accounts` configuration, we receive the following error:
```
2023-05-31T20:40:36.328Z catalog warn Processor AwsOrganizationCloudAccountProcessor threw an error while reading aws-cloud-accounts:<ID>; caused by AccessDeniedException: You don't have permissions to access this resource. 
```

### 👟 Reproduction steps

1. create a specific AWS Role that grants `ListAccounts` access that Backstage should assume
2. add the following config
```yaml
catalog:
  processors:
    awsOrganization:
      provider:
        roleArn: 'arn:aws:iam::<other-account-id>:role/<list-organizations-role-name>'

aws:
  accounts:
    - accountId: "<other-account-id>"
```
3. integrate the `AwsOrganizationCloudAccountProcessor` with a location entity for the org to consume accounts from
4. Run backstage with AWS credentials in the environment for a role that can assume `arn:aws:iam::<other-account-id>:role/<list-organizations-role-name>`
5. hit the error

### 📃 Provide the context for the Bug.

Currently, the duplication of specifying the `roleArn` and `roleName` is annoying and not ideal, but moving forward, we would love to be able to not be tied to a specific role for any given AWS account for the `DefaultAwsCredentialsManager`.

We heavily make use of AWS roles to limit exposure and would like to not grant multiple unrelated permissions globally to our application role if not necessary.

### 🖥️ Your Environment

```
OS: Darwin 22.4.0 - darwin/x64
node: v16.14.0
backstage: 1.14.1
Dependencies:
    @backstage/app-defaults: 1.3.1
    @backstage/backend-app-api: 0.4.3
    @backstage/backend-common: 0.18.5
    @backstage/backend-dev-utils: 0.1.1
    @backstage/backend-plugin-api: 0.5.2
    @backstage/backend-tasks: 0.5.2
    @backstage/backend-test-utils: 0.1.37
    @backstage/catalog-client: 1.4.1
    @backstage/catalog-model: 1.2.0, 1.3.0
    @backstage/cli-common: 0.1.12
    @backstage/cli-node: 0.1.0
    @backstage/cli: 0.22.7
    @backstage/config-loader: 1.3.0
    @backstage/config: 1.0.7
    @backstage/core-app-api: 1.8.0
    @backstage/core-components: 0.12.4, 0.12.5, 0.13.1
    @backstage/core-plugin-api: 1.0.6, 1.5.1
    @backstage/dev-utils: 1.0.15
    @backstage/errors: 1.1.5
    @backstage/eslint-plugin: 0.1.3
    @backstage/integration-aws-node: 0.1.3
    @backstage/integration-react: 1.1.13
    @backstage/integration: 1.4.5
    @backstage/plugin-analytics-module-ga: 0.1.29
    @backstage/plugin-api-docs-module-protoc-gen-doc: 0.1.2
    @backstage/plugin-api-docs: 0.9.3
    @backstage/plugin-app-backend: 0.3.45
    @backstage/plugin-auth-backend: 0.18.3
    @backstage/plugin-auth-node: 0.2.14
    @backstage/plugin-catalog-backend-module-aws: 0.2.0
    @backstage/plugin-catalog-backend-module-github: 0.3.0
    @backstage/plugin-catalog-backend: 1.9.1
    @backstage/plugin-catalog-common: 1.0.13
    @backstage/plugin-catalog-graph: 0.2.30
    @backstage/plugin-catalog-node: 1.3.6
    @backstage/plugin-catalog-react: 1.2.1, 1.6.0
    @backstage/plugin-catalog: 1.11.0
    @backstage/plugin-devtools-backend: 0.1.0
    @backstage/plugin-devtools-common: 0.1.0
    @backstage/plugin-devtools: 0.1.0
    @backstage/plugin-events-backend-module-github: 0.1.7
    @backstage/plugin-events-backend-test-utils: 0.1.7
    @backstage/plugin-events-backend: 0.2.6
    @backstage/plugin-events-node: 0.2.6
    @backstage/plugin-explore-backend: 0.0.7
    @backstage/plugin-explore-common: 0.0.1
    @backstage/plugin-explore-react: 0.0.28
    @backstage/plugin-explore: 0.4.3
    @backstage/plugin-github-actions: 0.5.18
    @backstage/plugin-github-pull-requests-board: 0.1.12
    @backstage/plugin-home: 0.5.2
    @backstage/plugin-kubernetes-backend: 0.11.0
    @backstage/plugin-kubernetes-common: 0.6.3
    @backstage/plugin-kubernetes: 0.9.1
    @backstage/plugin-org: 0.6.8
    @backstage/plugin-pagerduty: 0.5.11
    @backstage/plugin-permission-common: 0.7.5
    @backstage/plugin-permission-node: 0.7.8
    @backstage/plugin-permission-react: 0.4.12
    @backstage/plugin-proxy-backend: 0.2.39
    @backstage/plugin-scaffolder-backend: 1.14.0
    @backstage/plugin-scaffolder-common: 1.3.0
    @backstage/plugin-scaffolder-node: 0.1.3
    @backstage/plugin-scaffolder-react: 1.4.0
    @backstage/plugin-scaffolder: 1.13.1
    @backstage/plugin-search-backend-module-catalog: 0.1.1
    @backstage/plugin-search-backend-module-elasticsearch: 1.3.0
    @backstage/plugin-search-backend-module-explore: 0.1.1
    @backstage/plugin-search-backend-module-pg: 0.5.6
    @backstage/plugin-search-backend-node: 1.2.1
    @backstage/plugin-search-backend: 1.3.1
    @backstage/plugin-search-common: 1.2.3
    @backstage/plugin-search-react: 1.6.0
    @backstage/plugin-search: 1.3.0
    @backstage/plugin-shortcuts: 0.3.10
    @backstage/plugin-tech-insights-backend-module-jsonfc: 0.1.29
    @backstage/plugin-tech-insights-backend: 0.5.11
    @backstage/plugin-tech-insights-common: 0.2.10
    @backstage/plugin-tech-insights-node: 0.4.3
    @backstage/plugin-tech-insights: 0.3.10
    @backstage/plugin-user-settings-backend: 0.1.9
    @backstage/plugin-user-settings: 0.7.3
    @backstage/release-manifests: 0.0.9
    @backstage/test-utils: 1.3.1
    @backstage/theme: 0.2.19, 0.3.0
    @backstage/types: 1.0.2
    @backstage/version-bridge: 1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jhaals** [comment]
Hi @alecjacobs5401, sorry to hear that you're having issues. Which version did you bump from? That might help the debugging of this as there has been quite a bit of changes related to AWS authentication in the past months.

Perhaps @clareliguori could help out with some pointers here 🙏

**Comment by alecjacobs5401** [comment]
Hey @jhaals - we just upgraded from `1.13.2`. We've been keeping pretty up to date

I think part of the issue here (at least specifically for `AwsOrganizationCloudAccountProcessor` is that when credentials are created by the `DefaultAwsCredentialsManager` with an `arn` provided to `getCredentialProvider`, only the [`accountId` is pulled](https://github.com/backstage/backstage/blob/v1.14.1/packages/integration-aws-node/src/DefaultAwsCredentialsManager.ts#LL231C7-L231C16) and used to lookup matching credentials, so the onus is still on `AwsOrganizationCloudAccountProcessor` to assume the proper role ([which doesn't happen here](https://github.com/backstage/backstage/blob/v1.14.1/plugins/catalog-backend-module-aws/src/processors/AwsOrganizationCloudAccountProcessor.ts#L77-L80))

**Comment by blandes** [comment]
@niallthomson

**Comment by alecjacobs5401** [comment]
Bumping this discussion again

**Comment by wanisfahmyDE** [comment]
hey @alecjacobs5401,

Do you mind sharing a snippet from your `catalog.ts`? I'm currenlty not able to get it running even when specifying the roleName :/

```yaml
# app-config.yaml
catalog:
  processors:
    awsOrganization:
      provider:
        roleArn: '<role-arn>'
aws:
  accounts:
    - accountId: "some-account-id"
      roleName: "role-name"
```

```TypeScript
// packages/backend/src/plugins/catalog.ts
import {AwsOrganizationCloudAccountProcessor} from '@backstage/plugin-catalog-backend-module-aws';
export default async function createPlugin(
    env: PluginEnvironment,
): Promise<Router> {
    const builder = await CatalogBuilder.create(env);
    builder.addProcessor(
        // not sure who should resolve this promise?
        await AwsOrganizationCloudAccountProcessor.fromConfig( 
            env.config,
            {logger: env.logger}
        )
    );
...
}
```

no errors are displayed in the logs, but navigating to the Catalog --> Resources doesn't show any `cloud-account` type items.

Thanks in advance

**Comment by alecjacobs5401** [comment]
@wanisfahmyDE Thats about what we have configured for our `app-config.yaml` and `packages/backend/src/plugins/catalog.ts`.

Do you have a `Location` entity defined to tell the processor to where to consume AWS accounts from?

You'll need one that looks like
```yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: aws-organization
spec:
  type: aws-cloud-accounts
  target: <aws-org-id>
```

Can't find the docs for it specifically, but some [code spelunking](https://github.com/backstage/backstage/blob/v1.17.1/plugins/catalog-backend-module-aws/src/processors/AwsOrganizationCloudAccountProcessor.ts#L101-L110) highlights the need

**Comment by wanisfahmyDE** [comment]
thank you @alecjacobs5401, the `location` was the missing part!
I'll create a PR to update the [Readme](https://github.com/backstage/backstage/tree/v1.17.1/plugins/catalog-backend-module-aws)

**Comment by benjdlambert** [comment]
@alecjacobs5401 sorry I couldn't quite understand where we're at with this ticket, Is there some work that still needs to be done in order to fix this issue? :pray:

**Comment by alecjacobs5401** [comment]
Hey @benjdlambert, 

I think the original issue presented is still a problem:
* The `catalog.processors.awsOrganization.provider.roleArn` is necessary configuration for the `AwsOrganizationCloudAccountProcessor` to run when AWS organization details are not available in the default AWS account (e.g., Backstage runs in an AWS account that is part of but an organization but is not the organizations management account)
* Since Backstage 1.14, The role ARN defined in `catalog.processors.awsOrganization.provider.roleArn` is [only used to determine the AWS account ID](https://github.com/backstage/backstage/blob/v1.17.2/packages/integration-aws-node/src/DefaultAwsCredentialsManager.ts#L227-L232) and the role is _not_ assumed, so extra `aws.accounts` configuration is necessary to define the role again

I guess the issue is more of a question of what is the intent of `catalog.processors.awsOrganization.provider.roleArn` is and how AWS roles are used in integrations.

The current AWS integration really only enables one role in each AWS for Backstage to assume and that role must be granted wide access for various integrations to succeed for that AWS account.

**Comment by benjdlambert** [comment]
@alecjacobs5401 ok, so what do you think the solution looks like here? Should the roles be assumed? I know there was some steps to standardizing aws auth #12844 so is there something that can be done with that authentication instead?

**Comment by alecjacobs5401** [comment]
Hey @benjdlambert, sorry for a late response here!

It feels like still assuming the role when provided feels prudent..otherwise its misleading and surprising to have the role ARN be required by the processor but the only thing the processor cares about is the account ID the Role is associated with.

**Comment by alecjacobs5401** [comment]
bumping to keep alive if necessary

**Comment by freben** [comment]
Just commenting to note that this is still on a "help wanted" status. @niallthomson's comment does ring true - is it the case that the processor should ideally have only pointed to the account ID that it wanted to ingest from, and `aws.accounts` maps those to roles to assume etc? Or is that also too limiting, eg if several different processors want to attach to different roles on the same account?

We aren't active users of AWS ourselves and so aren't fully up to date on the best practices, and any contribution nudging this in the right direction would be appreciated 🙏

**Comment by niallthomson** [comment]
Is there value is being able to assume a different role for each plugin? Sure, it helps with least privilege and could in theory limit blast radius.

However, at this stage I believe that none of the other integrations like TechDocs and EKS Kubernetes authentication are offering this level of control over the role being used. Its also not something we're currently building in to our [own new AWS plugins](https://github.com/awslabs/backstage-plugins-for-aws) until we have reason to do so.

From my perspective that means that this integration is just currently a bit of an oddity and has a parameter that no longer works. I would bias towards removing the `roleArn` field until there is a consistent effort to implement this pattern across the various integrations.

**Comment by freben** [comment]
Thanks for that input, super valuable. @alecjacobs5401 @wanisfahmyDE or others - would you be up for trying to make that change?

**Comment by alecjacobs5401** [comment]
> From my perspective that means that this integration is just currently a bit of an oddity and has a parameter that no longer works. I would bias towards removing the roleArn field until there is a consistent effort to implement this pattern across the various integrations.

Happy to move forward with removing the configuration as well! I likely won't have time immediately to contribute anything upstream for it (since it will require some changes, I believe. Last I checked, the roleArn was only used to extract an AWS Account ID that _was_ used for something, but not assuming that role)

**Comment by niallthomson** [comment]
Yes I think the change would be more accurately described as:

Bring the `AwsOrganizationCloudAccountProcessor` configuration in line with other integrations such as TechDocs S3, explicitly breaking out `accountId` and `region` parameters and removing `roleArn` since it is misleading.

Example TechDocs S3 configuration:

```yaml
techdocs:
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: 'name-of-techdocs-storage-bucket'
      accountId: '123456789012'
      region: ${AWS_REGION}
```

**Comment by ooiyeefei** [comment]
Hi @freben, I'm happy to help make the changes. Thanks!

**Comment by niallthomson** [comment]
This change is ready. Are we fine with a breaking change removing the `roleArn` and replacing it with `accountId`? If so are there any additional considerations in the PR?

**Comment by freben** [comment]
@niallthomson If it was decidedly broken in its old place, we can consider it to be a bugfix.

It can still be helpful to end users to try to read the old field and emit a log warning telling them to change it to the new way. And make sure that the changeset has migration instructions showing a diff of the changes

**Comment by codingdiaz** [comment]
Hey everyone!

I took a shot at creating a new catalog module that breaks the AWS Org processor into its own module and Entity Provider here: https://github.com/backstage/backstage/pull/24976. I wanted to comment here for context as I believe it is related.
