### ISSUE TITLE
Documentation for GraphQL Extensions

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#1806]
## Feature Suggestion
- Document how to create GraphQL extensions to the schema
- Document how to share dataloaders
- Document how to call the catalog from your own extension

**Comment by taras** [comment]
Not sure how far along this is but for what it's worth, Apollo Federation could be a very good solution for Backstage. Happy to talk about it if you're interested.

**Comment by benjdlambert** [comment]
Hey @taras, we'd ideally like to avoid federation, and have opted for an approach like https://github.com/Urigo/graphql-modules. Currently this library is implemented, but it might not stick around. We end up creating a thinner version ourselves, and the DI might be a little overkill.

**Comment by andrewthauer** [comment]
Hey @benjdlambert - I'm curious to understand the pros & cons of apollo federation vs graphql-modules myself. Would this discussion happen to be in another issue or elsewhere?

**Comment by benjdlambert** [comment]
@andrewthauer its something we’ve been contemplating internally so I don’t think the docs are on public GitHub. Let me see if I can get back to you with some reasoning. Happy to discuss again if something has changed too

**Comment by Rugvip** [comment]
@andrewthauer Discussion happened on Discord, but in voice, so bleh :<

Apollo federation we think works well for stitching of large schemas where things are tied in through IDs. In this case I think we're looking more at stitching together much smaller pieces, usually individual resolvers, especially things like lookups based on annotations in entities etc.

One of the main reasons would be to share data loaders and context as well. For example, I think we want to avoid hammering the catalog with requests for individual entities for every federated piece of the schema. Using modules we can fetch an entity once from the catalog, and then provide it to all child resolvers through context.

**Comment by andrewthauer** [comment]
All good. More curious than anything else at this point.
