### ISSUE TITLE
🚀 Feature: catalog-graph elements limit

### ISSUE THREAD

**Issue by vullakularajesh** [backstage/backstage#18061]
### 🔖 Feature description

In catalog-graph there is option to limit no of columns(horizontal length) using maxDepth. But there is no such option for no.of rows (number of horizontal entries this cause the memory issue.

suppose there is one group with 1000 user and you are checking the graph for this group. Now this 1000 horizontal entries creates browser memory issue. Suppose every element is fetched via network call to backend.

### 🎤 Context

By limiting number of elements loading with options on top and bottom to load X more will make browser happy.

### ✌️ Possible Implementation

Just like maxDepth there should be an option to limit horizontal entries depth.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by tperehinets** [comment]
Is there someone working on this issue?

**Comment by freben** [comment]
I don't think there is. Would you like to contribute? 🙏

**Comment by tperehinets** [comment]
> I don't think there is. Would you like to contribute? 🙏

I'd love to!
