### ISSUE TITLE
🚀 Feature:  Able to fully use the features in react-jsonschema-form

### ISSUE THREAD

**Issue by aswathysen** [backstage/backstage#18076]
### 🔖 Feature description

There are so many cool features in REACT-JSONSCHEMA-FORM but not every feature is available while buidling a software Template to make the template look good and easy to use. 

### 🎤 Context

In my usecase i need some of the features (apart from the default features that we already have) from react json schema form, but not able to implement those UI:features .

eg:   

```
    ui:enableMarkdownInDescription: true,
    ui:description: Make text **bold** or *italic*. Take a look at other options [here](https://probablyup.com/markdown-to-jsx/).
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Oh this looks like a new feature thats dropped in the latest version. Whilst I don't think that we're using this recent of version you'll want to use the `scaffolder/next` preview to get access to the most recent version of `react-jsonschema-form` as the current stable plugin is locked at v3.

There's some [docs](https://backstage.io/docs/features/software-templates/testing-scaffolder-alpha) about how to migrate to test the new version, which will hopefully be released in the upcoming minor releases for Backstage.

About this feature specifically, we recently added https://github.com/backstage/backstage/pull/17952 which fixes this exact use case actually, but maybe we don't need that now anyways.

I'll make sure that we get `react-jsonschema-form` ahead of the `next` release tomorrow too so you can try out these new features then!
