### ISSUE TITLE
🐛 Bug Report: Compound references are not parsed from yaml files

### ISSUE THREAD

**Issue by hewe-saxo** [backstage/backstage#18093]
### 📜 Description

Using the example of compound reference from the official documentation does not work.

[Entity Reference](https://backstage.io/docs/features/software-catalog/references/#compound-references)

### 👍 Expected behavior

Resources with compound references are ingested into backstage catalog.

### 👎 Actual Behavior with Screenshots

The catalog processor shows a warning that the entity doesn't contain a string in the relationship link.

`[1] 2023-06-02T14:00:02.719Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity component:default/petstore; caused by TypeError: /spec/owner must be string - type: string type=plugin entity=component:default/petstore location=file:[SNIP]/backstage/examples/entities.yaml`

### 👟 Reproduction steps

1. Insert the following component into a yaml file

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  description: Petstore
spec:
  type: service
  lifecycle: experimental
  owner:
    kind: Group
    name: aegis-imports/pet-managers
```

2. Configure the yaml file to be ingested into the catalog
3. Start backstage

### 📃 Provide the context for the Bug.

We want to use the compound reference in order to add some additional information on the relationship. For example have APIs that have role/claims based permissions. We want to use compound references for consumes/producesApis and dependsOn relationships.

```
consumesApis:
- name: myapi
  role: myapi.admin
- name: myapi2
  role: myapi2.reviewer
```

### 🖥️ Your Environment

OS:   Linux 5.10.16.3-microsoft-standard-WSL2 - linux/x64
node: v18.15.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.13.0

Dependencies:
  @backstage/app-defaults                          1.3.1
  @backstage/backend-app-api                       0.4.3
  @backstage/backend-common                        0.18.5
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.2
  @backstage/backend-tasks                         0.5.2
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.7
  @backstage/config-loader                         1.3.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.8.0
  @backstage/core-components                       0.13.1
  @backstage/core-plugin-api                       1.5.1
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.3
  @backstage/integration-react                     1.1.13
  @backstage/integration                           1.4.5
  @backstage/plugin-api-docs                       0.9.3
  @backstage/plugin-app-backend                    0.3.45
  @backstage/plugin-auth-backend                   0.18.3
  @backstage/plugin-auth-node                      0.2.14
  @backstage/plugin-catalog-backend-module-azure   0.1.16
  @backstage/plugin-catalog-backend-module-msgraph 0.5.4
  @backstage/plugin-catalog-backend                1.9.1
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.30
  @backstage/plugin-catalog-import                 0.9.8
  @backstage/plugin-catalog-node                   1.3.6
  @backstage/plugin-catalog-react                  1.6.0
  @backstage/plugin-catalog                        1.11.0
  @backstage/plugin-github-actions                 0.5.18
  @backstage/plugin-org                            0.6.8
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.8
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.39
  @backstage/plugin-scaffolder-backend             1.14.0
  @backstage/plugin-scaffolder-common              1.3.0
  @backstage/plugin-scaffolder-node                0.1.3
  @backstage/plugin-scaffolder-react               1.4.0
  @backstage/plugin-scaffolder                     1.13.1
  @backstage/plugin-search-backend-module-catalog  0.1.1
  @backstage/plugin-search-backend-module-pg       0.5.6
  @backstage/plugin-search-backend-module-techdocs 0.1.1
  @backstage/plugin-search-backend-node            1.2.1
  @backstage/plugin-search-backend                 1.3.1
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.6.0
  @backstage/plugin-search                         1.3.0
  @backstage/plugin-tech-radar                     0.6.4
  @backstage/plugin-techdocs-backend               1.6.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.13
  @backstage/plugin-techdocs-node                  1.7.1
  @backstage/plugin-techdocs-react                 1.1.6
  @backstage/plugin-techdocs                       1.6.2
  @backstage/plugin-user-settings                  0.7.3
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.1
  @backstage/theme                                 0.2.19, 0.3.0
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Documentation fixed by #18095.

What you want to do in terms of expressing additional metadata is unfortunately not possible at all. Sorry that the documentation was misleading. Refs are only ever single strings.

There's been some related types of requests before, see discussion here for example https://github.com/backstage/backstage/issues/14875
