### ISSUE TITLE
🚀 Feature: proxy endpoint supports websocket upgrades

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#18099]
### 🔖 Feature description

Since the k8s API and `kubectl proxy` both support WebSocket upgrades, let's have our proxy endpoint do the same to enable shelling into pods over WebSockets, like
```console
% wscat -s channel.k8s.io -H 'Backstage-Kubernetes-Cluster: local' -c 'ws://localhost:7007/api/kubernetes/proxy/api/v1/namespaces/default/pods/dice-roller-676dc8c999-4dgfn/exec?command=ls&container=nginx&stdout=true'
Connected (press CTRL+C to quit)
<
< bin
boot
dev
etc
home
lib
lib64
media
mnt
opt
proc
product_uuid
root
run
sbin
srv
sys
tmp
usr
var

Disconnected (code: 1000, reason: "")
```

### why it should be implemented

Together with #18097, to unblock the use of the proxy as a backend for #18024, at least in the very simple case where Backstage has exactly one cluster with a server-side auth provider.

### how it would be used (or at least tested)
1. Apply the dice-roller manifests in your cluster
1. Run `kubectl proxy --reject-paths "^/api/./pods/./attach"`
1. Run `yarn start-backend` with app-config:
    ```yaml
    kubernetes:
      clusterLocatorMethods:
        - type: localKubectlProxy
    ```
1. Execute the following node script, replacing `dice-roller-676dc8c999-4dgfn` with the name of a running dice-roller pod in the default namespace:
    ```javascript
    const WebSocket = require('ws');

    new WebSocket(
      'ws://localhost:7007/api/kubernetes/proxy/api/v1/namespaces/default/pods/dice-roller-676dc8c999-4dgfn/exec?command=ls&container=nginx&stdout=true',
      'channel.k8s.io',
      { headers: {['Backstage-Kubernetes-Cluster']: 'local'}},
    ).on('message', x => console.log(x.toString()));
    ```

### ✌️ Possible Implementation

In theory, it should be as simple as
```patch
diff --git a/plugins/kubernetes-backend/src/service/KubernetesProxy.ts b/plugins/kubernetes-backend/src/service/KubernetesProxy.ts
index b4ca87d6f01..b73f78e3ba4 100644
--- a/plugins/kubernetes-backend/src/service/KubernetesProxy.ts
+++ b/plugins/kubernetes-backend/src/service/KubernetesProxy.ts
@@ -138,6 +138,7 @@ export class KubernetesProxy {
         logProvider: () => logger,
         secure: !originalCluster.skipTLSVerify,
         changeOrigin: true,
+        ws: true,
         router: async req => {
           // Re-evaluate the cluster on each request, in case it has changed
           const cluster = await this.getClusterForRequest(req);
```

However, when I tried this out, there were still issues:
* it seems upgraded WebSocket requests no longer have a `header()` method, making the check for the `Backstage-Kubernetes-Cluster` header a bit awkward
* in general when I hit errors (for example, when I tried to `exec` with a command that didn't exist) while spiking on this, the backend would crash completely

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
The websocket upgrade might be tricky to achieve from within a plugin and will probably need to be handled further up in the http server. There's some ongoing events work that likely will tackle this in #17997

**Comment by luchillo17** [comment]
Is the dice-roller manifest mentioned in the steps this one? https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/examples/dice-roller/dice-roller-manifests.yaml

**Comment by luchillo17** [comment]
Hi @freben, wanted to ask a bit of information about this proxy's `router` here, as far as I can tell the 2 things that matter is that it intercepts all requests and reforms the url per request, and the certificate authority right?
The issue as I see it is that this `router` intercepts all requests, including WebSockets ones which do not have a `header` method, I was wondering if there's a way to tell those requests for WebSockets apart, or should I just check if the headers method exist?
https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesProxy.ts#L140-L150

**Comment by freben** [comment]
@luchillo17 see the comment above from jhaals - code that supports the websocket upgrade is far higher up in the stack, so we'd need framework support higher up to actually deal with that

**Comment by luchillo17** [comment]
`http-proxy-middleware` does support the upgrade, the issue is we have a `router` prop (it's basically a middleware for all requests) that currently check the headers for the request, the issue is that when the request is a WebSocket one, that middleware receives as well the socket stream, which doesn't have a `headers` function (though it does have a `rawHeaders` prop), so what I want to do is differentiate between a normal HTTP req and a WS one, so I can conditionally skip the header check, worst case I would just check if the function exists with a null check.

**Comment by luchillo17** [comment]
Got it working finally, here's how the code looks now:
![Screenshot 2023-06-15 at 6 26 16 PM](https://github.com/backstage/backstage/assets/9698639/c67c378a-daaa-46d8-9269-3d0b82e95a99)
