### ISSUE TITLE
🚀 Feature: retitle ADR plugin to "Any Decision Record"

### ISSUE THREAD

**Issue by ericis** [backstage/backstage#18138]
### 🔖 Feature description

The ADR plug-in is currently titled "Architecture Decision Record".

This is a feature request to provide a configuration override to support the title and guidance for "Any Decision Record" rather than specifically "Architecture".

### 🎤 Context

The ADR plug-in [currently references](https://github.com/backstage/backstage/blob/master/plugins/adr/README.md#custom-adr-formats) the "Markdown Any Decision Record (MADR) 3.x template".

With a hard-coded title as "Architecture", users who are reading an "Any" Decision Record, may be confused by how it specifically relates to an "Architecture" decision.

### ✌️ Possible Implementation

Provide plug-in configuration for the title.

Implement "Architecture Decision Record" as the default text for the title for backwards compatibility.

Offer the ability to toggle the configuration to use "Any Decision Record" (or perhaps any title text the implementer wishes).

Update plug-in documentation to either use "Any" everywhere except when describing the configuration default or update the references to "[Any or Architecture] Decision Record (ADR)".

BTW: I believe the implementer should avoid using the format "Any / Architecture Decision Record" as it may not read as intended; some people may read it as "Any Record" or "Any Architecture ...".

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by kuangp** [comment]
Just want to note that is a similar request to what was done in the playlist plugin: https://github.com/backstage/backstage/pull/16955 and a similar solution could apply to this plugin as well, essentially providing a way to "rebrand" the plugin title (if anyone's willing to contribute 😁)

Additionally, again as with the playlist plugin request, this relates to https://github.com/backstage/backstage/issues/16876 which is still unsettled so wanted to cc @benjdlambert in case he thinks we should hold off for now.

**Comment by Rugvip** [comment]
I think the i18n work is really the way forward here tbh, as that would allow for customization of these messages. It's ongoing in #17436, also see #4454
