### ISSUE TITLE
🐛 Home and End keys don't work in docs search boxes

### ISSUE THREAD

**Issue by david-prior** [backstage/backstage#18145]
### 📜 Description

When focus is on a search box for docs, and
1. the Home key is pressed on the keyboard
2. the End key is pressed on the keyboard
3. Shift+Home is pressed
4. Shift+End is pressed

### 👍 Expected behavior

1. The text cursor should move to the start of the search box
2. The text cursor should move to the end of the search box
3. The text cursor should move to the start of the search box, and the text between there and wherever the cursor was previously should be selected
4. The text cursor should move to the end of the search box, and the text between there and wherever the cursor was previously should be selected

### 👎 Actual Behavior with Screenshots

The cursor does not move

### 👟 Reproduction steps

1. Go to https://demo.backstage.io/docs/default/component/backstage
2. In the "Search backstage docs" box, type anything
3. Press Home (or End, or Shift-Home, or Shift-End)
4. See that the text cursor does not move

### 🖥️ Your Environment

Happens on:
- Chromium 108.0.5359.99 (Official Build) (64-bit)
- Chrome 113.0.5672.127 (Official Build) (64-bit) (cohort: Stable)
- Firefox 113.0.2 (64-bit)
- Microsoft Edge 114.0.1823.37 (Official build) (64-bit)

All on Windows 11 Version 22H2 (Build 22621.1702)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by MohdMusharraf** [comment]
Cursor is working completely fine.

**Comment by david-prior** [comment]
Hi @MohdMusharraf , not sure I understand your comment.

Do you mean it doesn't behave the way I describe, or that it does behave that way but that is somehow intended?

I've been able to additionally reproduce it on another device running Kubuntu 22.04 - all three browsers on this device (Chromium 113.0.5672.126, Google Chrome 114.0.5735.90, Firefox 113.0.2) behave the same as I saw on my Windows device.

**Comment by Suryansh-23** [comment]
Hi, @david-prior I tried recreating the bug on Microsoft Edge & Firefox on Windows 11, as you've mentioned. What I believe you mean to say is that on pressing the Home or End key, instead of going to the start/end of the search string, it goes to the beginning or end of the search results popup. Also, due to this behavior, the SHIFT + _  combination doesn't work either. I'm not sure if this could strictly be classified as a bug. 

But either way, even if it is considered a bug, I would be happy to contribute! @soapraj

**Comment by squid-ney** [comment]
Hi @Suryansh-23 and @david-prior 

I did a little more digging into this behavior. The [TechDocsSearchBar](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/search/components/TechDocsSearch.tsx#L60) uses Material UI's [Autocomplete](https://mui.com/material-ui/api/autocomplete/) component. 

The Autocomplete component has a prop, `handleHomeEndKeys` which changes the default behavior of the "Home" and "End" keys. The default value of  `handleHomeEndKeys` is the negative of the `freeSolo` (boolean value) prop, `!props.freeSolo`. 
>handleHomeEndKeys:  
If true, the component handles the "Home" and "End" keys when the popup is open. It should move focus to the first option and last option, respectively.

When the `handleHomeEndKeys` value is `false`, the Home and End keys move the focus to the start/end of the search string like you both are proposing. However, I did notice there is a page jump on the "Home" and "End" when I was playing around with the component in the browser via MaterialUI page/Code Sandbox which could be a problem.

I also did a bit of research on accessibility guidelines for the Combobox and it seems the requested behavior is optional: 
https://www.w3.org/WAI/ARIA/apg/patterns/combobox/#keyboard_interaction
> Home (Optional): Either moves focus to and selects the first option or, if the combobox is editable, returns focus to the combobox and places the cursor on the first character.
End (Optional): Either moves focus to the last option or, if the combobox is editable, returns focus to the combobox and places the cursor after the last character.

I don't think the current behavior is a bug, but the component may be more usable if the focus is returned to the search string on "Home" and "End" key press. @Suryansh-23 are you planning to propose a change for this?

**Comment by HimanshuBarak** [comment]
Hi @freben  (and others!) - Is this still an issue that can be picked up? Looking to be a first-time contributor.

**Comment by camilaibs** [comment]
Hi @HimanshuBarak, thanks for wanting to contribute with us 🎉! The issue is still pending so I just signed for you 🙂

**Comment by vinzscam** [comment]
Hi @HimanshuBarak 👋
let me know if you are still working on fixing the issue 🙂

**Comment by HimanshuBarak** [comment]
Hey @vinzscam. I am working on this. I was in between places so I wasn't able to dedicate time but will pick this again this weekend.
