### ISSUE TITLE
🚀 Feature: Autologout

### ISSUE THREAD

**Issue by manuelscurti** [backstage/backstage#18146]
### Description

The Autologout feature enables platform engineers to add a mechanism to log out users after a configurable amount of time of inactivity, and redirect them to the login page.

When enabled, the mechanism will track user actions (mouse movement, mouse click, key pressing, taps, etc.) in order to determine if they are active or not. After a certain amount of inactivity/idle time, the user session is invalidated and they are required to sign in again.

### Glossary

An `inactive user` is either:
- a user that is not performing any action on the app (no click, no mouse movement, no keyboard press) 
- a user whose session is still valid but has not open tabs in the browser pointing to Backstage

`Idle timeout`: it is the amount of time after which the user is automatically logged out

`prompt message`: it is a small prompt displayed to users some seconds before being automatically logged out. it is to inform them what it is going to happen if they don't perform any action. 

### User stories
- **R1**: As a platform engineer, I can enable/disable the autologout mechanism through the `app-config`
- **R2**: As a platform engineer, I can configure the idle timeout in the `app-config`
- **R3**: As a platform engineer, I can enable/disable the prompt message before idle
- **R4**: As a platform engineer, I can configure the amount of time before idle when the prompt message will be shown
- **R5**: As a platform engineer, I can configure the list of DOM events to track to determine if the user is active
- **R6**: As a user, I am automatically logged out after X minutes of inactivity
- **R7**: As a user, a prompt is shown by the app, X seconds before idle timeout, to ask me if I'm still active
- **R8**: As a user, I am automatically logged out after X minutes of inactivity even if I have no Backstage app tabs open
- **R9**: As a user, I am automatically logged out after X minutes of inactivity from every Backstage app tabs open in my current browser

### 🎤 Context

In my use-case, we have an internal constraint so that applications should log users out automatically after 60 minutes of inactivity.

### ✌️ Possible Implementation

The implementation could leverage the [React-Idle-Timer](https://github.com/SupremeTechnopriest/react-idle-timer) library which I already tested on different browsers and with different tabs of the same app open.

There will be a provider called `<AutologoutProvider>` that wraps the timers management provided by the `react-idle-timer` library. When `onIdle` event is triggered, the autologout provider will make a call to `identityApi` to sign out the user. 

The `<AutologoutProvider>` will be installed in the `App.tsx` entrypoint, and will wrap the `<Root>` component of Backstage in this way:
```typescript
// ... App.tsx contents
<AutoLogoutProvider>
    <Root>{routes}</Root>
</AutoLogoutProvider>
```

The behaviour of `AutologoutProvider` can be configured through some properties on the `app-config`. An example configuration could be this:
```yaml
autologout:
    enabled: true
    idleTimeoutMinutes: 60
    promptBeforeIdleSeconds: 10
```

My only doubt at this point is, which plugin can export the `AutologoutProvider`?
Some options came into my mind:
- A new `auth` plugin for frontend components related to Auth stuff
- A whole new frontend plugin which just exports this `AutologoutProvider` 

I am open for suggestions  and to hear your feedbacks on this feature request :)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Yep I think it could makes sense to add this as an optional extra. Probably coupled with a dialog that pops up that warns the user that they're about to be logged out? That's typically how I see this implemented anyway. Depending on the complexity of the implementation I think it could be placed in a few different places, maybe `@backstage/core-components` if it's small, but a new `@backstage/plugin-auth-react` if it's a bit larger. Could figure that out in a potential PR

**Comment by manuelscurti** [comment]
Yep! the user will be informed with a dialog (I called it prompt) on what is going to happen, this is requirement R7.
I'll create a PR 🕺
