### ISSUE TITLE
🐛 Bug Report: Invalid string length from catalog

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#18143]
### 📜 Description

Having 7000+ components in the catalog does not work with the catalog but instead, the request fails. The request is `GET /api/catalog/entities?filter=kind=component`

The request works if adding `&limit=5000` but if increasing it to 6000, the situation is the same.

### 👍 Expected behavior

The entities are returned without a problem

### 👎 Actual Behavior with Screenshots

`{"error":{"name":"RangeError","message":"Invalid string length"},"request":{"method":"GET","url":"/entities?filter=kind=component"},"response":{"statusCode":500}}`

Souce is /app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-6a9091b7.cjs.js:3430:11

![image](https://github.com/backstage/backstage/assets/1178319/5a55515d-5121-4bce-95e9-2975ba442cb2)

### 👟 Reproduction steps

1. Fill the catalog with lots of components
2. Go to catalog page 
3. Död.

### 📃 Provide the context for the Bug.

Might be related: https://github.com/nodejs/node-v0.x-archive/issues/14170

https://stackoverflow.com/questions/29175877/json-stringify-throws-rangeerror-invalid-string-length-for-huge-objects

### 🖥️ Your Environment

OS:   Darwin 22.5.0 - darwin/arm64
node: v16.20.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.14.0

Dependencies:
  @backstage/app-defaults                                   1.3.1
  @backstage/backend-app-api                                0.4.3
  @backstage/backend-common                                 0.17.0, 0.18.5
  @backstage/backend-dev-utils                              0.1.1
  @backstage/backend-plugin-api                             0.5.2
  @backstage/backend-tasks                                  0.5.2
  @backstage/backend-test-utils                             0.1.37
  @backstage/catalog-client                                 1.4.1
  @backstage/catalog-model                                  1.3.0
  @backstage/cli-common                                     0.1.12
  @backstage/cli-node                                       0.1.0
  @backstage/cli                                            0.22.7
  @backstage/config-loader                                  1.3.0
  @backstage/config                                         1.0.7
  @backstage/core-app-api                                   1.8.0
  @backstage/core-components                                0.12.5, 0.13.1
  @backstage/core-plugin-api                                1.5.1
  @backstage/dev-utils                                      1.0.15
  @backstage/errors                                         1.1.5
  @backstage/eslint-plugin                                  0.1.3
  @backstage/integration-aws-node                           0.1.3
  @backstage/integration-react                              1.1.13
  @backstage/integration                                    1.4.5
  @backstage/plugin-api-docs                                0.9.3
  @backstage/plugin-app-backend                             0.3.45
  @backstage/plugin-auth-backend                            0.18.3
  @backstage/plugin-auth-node                               0.2.14
  @backstage/plugin-catalog-backend-module-aws              0.2.0
  @backstage/plugin-catalog-backend-module-bitbucket-server 0.1.10
  @backstage/plugin-catalog-backend-module-msgraph          0.5.4
  @backstage/plugin-catalog-backend                         1.9.1
  @backstage/plugin-catalog-common                          1.0.13
  @backstage/plugin-catalog-graph                           0.2.30
  @backstage/plugin-catalog-node                            1.3.6
  @backstage/plugin-catalog-react                           1.6.0
  @backstage/plugin-catalog                                 1.11.0
  @backstage/plugin-github-actions                          0.5.18
  @backstage/plugin-home                                    0.5.2
  @backstage/plugin-jenkins-backend                         0.2.0
  @backstage/plugin-jenkins-common                          0.1.15
  @backstage/plugin-jenkins                                 0.8.0
  @backstage/plugin-kubernetes-common                       0.6.3
  @backstage/plugin-microsoft-calendar                      0.1.3
  @backstage/plugin-org                                     0.6.8
  @backstage/plugin-permission-backend                      0.5.20
  @backstage/plugin-permission-common                       0.7.5
  @backstage/plugin-permission-node                         0.7.8
  @backstage/plugin-permission-react                        0.4.12
  @backstage/plugin-proxy-backend                           0.2.39
  @backstage/plugin-scaffolder-backend-module-cookiecutter  0.2.21
  @backstage/plugin-scaffolder-backend                      1.14.0
  @backstage/plugin-scaffolder-common                       1.3.0
  @backstage/plugin-scaffolder-node                         0.1.3
  @backstage/plugin-scaffolder-react                        1.4.0
  @backstage/plugin-scaffolder                              1.13.1
  @backstage/plugin-search-backend-module-catalog           0.1.1
  @backstage/plugin-search-backend-module-elasticsearch     1.3.0
  @backstage/plugin-search-backend-module-pg                0.5.6
  @backstage/plugin-search-backend-module-techdocs          0.1.1
  @backstage/plugin-search-backend-node                     1.2.1
  @backstage/plugin-search-backend                          1.3.1
  @backstage/plugin-search-common                           1.2.3
  @backstage/plugin-search-react                            1.6.0
  @backstage/plugin-search                                  1.3.0
  @backstage/plugin-sonarqube-backend                       0.1.10
  @backstage/plugin-sonarqube-react                         0.1.5
  @backstage/plugin-sonarqube                               0.6.7
  @backstage/plugin-techdocs-backend                        1.6.2
  @backstage/plugin-techdocs-module-addons-contrib          1.0.13
  @backstage/plugin-techdocs-node                           1.7.1
  @backstage/plugin-techdocs-react                          1.1.6
  @backstage/plugin-techdocs                                1.6.2
  @backstage/plugin-user-settings                           0.7.3
  @backstage/release-manifests                              0.0.9
  @backstage/test-utils                                     1.3.1
  @backstage/theme                                          0.2.19, 0.3.0
  @backstage/types                                          1.0.2
  @backstage/version-bridge                                 1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
Apparently, this is due to a huge amount of relations between the components.

**Comment by drodil** [comment]
Yeah, backend paging support would probably fix this alltogether.

**Comment by freben** [comment]
Indeed. The backend does have pagination, the frontend and plugins may not leverage it.

https://chromium-review.googlesource.com/c/v8/v8/+/2030916

**Comment by Rugvip** [comment]
Adding JSON streaming in some select places might not hurt, but really the solution here is to utilize the catalog pagination everywhere. See #12247
