### ISSUE TITLE
🐛 Bug Report: Azure DevOps entity provider does not support searching/filtering by the branch property

### ISSUE THREAD

**Issue by alharto** [backstage/backstage#18152]
### 📜 Description

When reading the documentation for [Azure DevOps Discovery](https://backstage.io/docs/integrations/azure/discovery/) it doesn't seem clear what the "branch" property for the azureDevOps provider does. This may just be me but I first thought it was used to search/filter against a specific branch given in the notes it mentions that to use the branch parameter the desired branch much be added to the "Searchable branches". This would have been useful as I could test that my yaml files were being picked up and valid before committing to main.

However, when debugging it became clear that the codeSearch method doesn't support [filtering by branch](https://learn.microsoft.com/en-us/rest/api/azure/devops/search/code-search-results/fetch-code-search-results?view=azure-devops-rest-7.0&tabs=HTTP#examples).

### 👍 Expected behavior

Either:
1. The documentation should be updated to make clear that the "branch" property is used only to create Locations and not for filtering.
2. The code should be updated to filter by branch (in the codeSearch method) (happy to create a PR if this is the intended functionality?).

### 👎 Actual Behavior with Screenshots

The azureDevOps provider does not search/filter by ADO branch.

### 👟 Reproduction steps

Pass a "branch" property to the "azureDevOps" provider.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
I think this is likely working as intended in that locations are created for each repo, and then the processing loop will take care of discovering whether there actually are any entities in that location later. It's always nice to be able to make the location discovery as precise as possible though, so if we can do branch filtering upfront that would be a nice addition 👍
