### ISSUE TITLE
🚀 Feature: Function to emit symmetrical relations

### ISSUE THREAD

**Issue by efenner-cambia** [backstage/backstage#18151]
### 🔖 Feature description

I would like to propose the introduction of an `emitRelations()` function that would wrap the two emit calls required to create a relation into a single call in order to simplify processor code and reduce the chance for errors.

### 🎤 Context

According to the [code comments](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/kinds/relations.ts) and the [documentation on relations](https://backstage.io/docs/features/software-catalog/well-known-relations), relations should be symmetrical and usually emitted in pairs. This means that when implementing a custom processor, the `emit()` function has to be called twice for each relation being applied with nearly the same information. This seems like unnecessary code duplication that could be simplified.

### ✌️ Possible Implementation

Not sure where exactly this function would belong, but it would look something like this:

```TypeScript
function emitRelations(
      source: CompoundEntityRef,
      target: CompoundEntityRef,
      relation: [string, string],
    ) {
      emit(
        processingResult.relation({
          source: source,
          target: target,
          type: relation[0],
        }),
      );
      emit(
        processingResult.relation({
          source: target,
          target: source,
          type: relation[1],
        }),
      );
    }
```

With the above, both dependency relations could be emitted by a processor with a single line like this:

```TypeScript
emitRelations(selfRef, targetRef, [ RELATION_DEPENDS_ON, RELATION_DEPENDENCY_OF ]);
```

To make the calls even more elegant, we could also export pre-wrapped tuples of the relation pairs from `packages/catalog-model/src/kinds/relations.ts`:

```TypeScript
export const RELATIONS_DEPENDENCY = [ RELATION_DEPENDS_ON, RELATION_DEPENDENCY_OF ];
```

Which would mean the emit call could simply be:

```TypeScript
emitRelations(selfRef, targetRef, RELATIONS_DEPENDENCY);
```

I could see this pre-wrapping as potentially causing confusion as to which is the primary relation. It would only be for convenience and should be clearly documented. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Probably not something that wraps `emit`, and it makes the API an bit awkward, lots of things to pass through. Perhaps we could extend the `processingResult` helpers though?

**Comment by efenner-cambia** [comment]
I would still like to see this happen, but am unable to work on a PR for it
