### ISSUE TITLE
🐛 Bug Report: AAD login drastically slowed down after keeping a vanilla backstage running for few hours

### ISSUE THREAD

**Issue by bbasu** [backstage/backstage#18163]
### 📜 Description

We are facing a strange issue:

1. We took a vanilla backstage and deployed it in Azure Kubernetes Service - It works as normal for hours
2. We apply AAD login on top of it and let it run for long hours - we observe that after 8-10 hours, the login calls are drastically slowed down. it takes around mins to get the login calls resolved. 

We followed the standard backstage documentation to implement AAD login and did no customizations apart from this. A restart of the above makes the application healthy again.

we are struggling with this issue for a long time now..initially, we thot it might be our custom code/db connections/ our own infrastructure, etc
we started eliminating things one by one and eventually have vanilla+AAD running in one of the instance now
we are using backstage for more than a year now and started noticing this performance slowness since the last 2 months
we are unable to determine what change might have caused this
everytime a restart of the pod makes the application healthy and normal only to go down after a certain period in a non-deterministic way

any insight as to why such a thing can happen? 

### 👍 Expected behavior

The application should be responsive consistently.

### 👎 Actual Behavior with Screenshots

1st time login
<img width="1455" alt="image" src="https://github.com/backstage/backstage/assets/14269816/4c631a0b-b9de-4c37-9178-9462e72727d3">

subsequent page refresh

<img width="1295" alt="image" src="https://github.com/backstage/backstage/assets/14269816/1ae5e5fa-18de-4f58-b8f0-d2b0d1c2285f">

### 👟 Reproduction steps

1. Take a vanilla backstage implementation and deploy in Azure Kubernetes Service
2. Apply AAD on top of it as per the doc https://backstage.io/docs/auth/microsoft/provider/
3. Keep the application running idly for some hours and observe

### 🖥️ Your Environment

OS:   Windows_NT 10.0.19045 - win32/x64
node: v16.14.0
yarn: 1.22.17
cli:  0.22.6 (installed)
backstage:  1.14.1     
 
Dependencies:
  @backstage/app-defaults                         1.3.1
  @backstage/backend-app-api                      0.4.3
  @backstage/backend-common                       0.18.5
  @backstage/backend-dev-utils                    0.1.1
  @backstage/backend-plugin-api                   0.5.2
  @backstage/backend-tasks                        0.5.2
  @backstage/backend-test-utils                   0.1.37
  @backstage/catalog-client                       1.4.1
  @backstage/catalog-model                        1.3.0
  @backstage/cli-common                           0.1.12
  @backstage/cli-node                             0.1.0
  @backstage/cli                                  0.22.7
  @backstage/config-loader                        1.3.0
  @backstage/config                               1.0.7
  @backstage/core-app-api                         1.8.0
  @backstage/core-components                      0.13.1
  @backstage/core-plugin-api                      1.5.1
  @backstage/dev-utils                            1.0.15
  @backstage/errors                               1.1.5
  @backstage/eslint-plugin                        0.1.3
  @backstage/integration-aws-node                 0.1.3
  @backstage/integration-react                    1.1.13
  @backstage/integration                          1.4.5
  @backstage/plugin-api-docs                      0.9.3
  @backstage/plugin-app-backend                   0.3.45
  @backstage/plugin-auth-backend                  0.18.3
  @backstage/plugin-auth-node                     0.2.14
  @backstage/plugin-catalog-backend-module-azure  0.1.16
  @backstage/plugin-catalog-backend               1.9.1
  @backstage/plugin-catalog-common                1.0.13
  @backstage/plugin-catalog-graph                 0.2.30
  @backstage/plugin-catalog-import                0.9.8
  @backstage/plugin-catalog-node                  1.3.6
  @backstage/plugin-catalog-react                 1.6.0
  @backstage/plugin-catalog                       1.11.0
  @backstage/plugin-github-actions                0.5.18
  @backstage/plugin-home                          0.5.2
  @backstage/plugin-org                           0.6.8
  @backstage/plugin-permission-backend            0.5.20
  @backstage/plugin-permission-common             0.7.5
  @backstage/plugin-permission-node               0.7.8
  @backstage/plugin-permission-react              0.4.12
  @backstage/plugin-proxy-backend                 0.2.39
  @backstage/plugin-scaffolder-backend            1.14.0
  @backstage/plugin-scaffolder-common             1.3.0
  @backstage/plugin-scaffolder-node               0.1.3
  @backstage/plugin-scaffolder-react              1.4.0
  @backstage/plugin-scaffolder                    1.13.1
  @backstage/plugin-search-backend-module-catalog 0.1.1
  @backstage/plugin-search-backend-module-pg      0.5.6
  @backstage/plugin-search-backend-node           1.2.1
  @backstage/plugin-search-backend                1.3.1
  @backstage/plugin-search-common                 1.2.3
  @backstage/plugin-search-react                  1.6.0
  @backstage/plugin-search                        1.3.0
  @backstage/plugin-user-settings                 0.7.3
  @backstage/release-manifests                    0.0.9
  @backstage/test-utils                           1.3.1
  @backstage/theme                                0.3.0
  @backstage/types                                1.0.2
  @backstage/version-bridge                       1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Hmm, tricky to debug this or reproduce from our side. It's not something we've seen before. Do the backend logs provide any clues? In particular when the incoming request is logged in relation to when it's sent from the browser.

Does the slowness happen with the auth `.../handler/frame` endpoint too, or is it only for `.../refresh`? What the refresh endpoint does is a bit of talking to the upstream identity provider, as well as calling the sign-in resolvers, which might in turn be sending requests to the catalog. Any of those things could be slow, and while catalog requests from the client seem fast enough, it could be that service-to-service requests are slow?

**Comment by bbasu** [comment]
this happens in both the endpoints `...handler/frame` as well as `...refresh`
we did some basic profiling and a timeline break of such a call shows the following:

/start
node/express takes milliseconds
login.microsoft takes mins
graph.microsoft takes mins
update db takes milliseconds

we also observed in the profiling that while such slowness happens there is no sign of any memory leaks, high CPU usage, etc. the telemetrics of the system is well within limits

'When the incoming request is logged in relation to when it's sent from the browser' - there is not much delay on this. the network does not seem to take a lot of time propagation the calls to and fro.

there is nothing in the log too which points to what can be wrong here. do you have any suggestions on how to enable any extra logs? We did try to enable the knex logs and time to time we see this error (although we are not sure whether this is direct consequence)
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
We tried to know more about this log, but this is a very generic statement, we tried to tweak the knexConfig to assign greater pool connections but that does not prevent this bug to reoccur.

Please suggest how can we move forward on this.

**Comment by miguelfsm** [comment]
Also worth mentioning that when the slowness occurs, the metrics we are logging from the auth plugin database pool remain the same as they are since the application start, namely:
used conns: 0, free conns: 1, pending acquires: 0, pending creates: 0 

For comparison, logging the same metrics for the catalog plugin we do see the free connections going up and down as we use the catalog.

**Comment by Rugvip** [comment]
> /start
> node/express takes milliseconds
> login.microsoft takes mins
> graph.microsoft takes mins
> update db takes milliseconds

That's not all in the `/start` handler right? I'm assuming the last ones are in the `/frame/handler` callback?

I would just dig into the calls to the microsoft API, it seems a bit unlikely to be DB related given the stats you posted and since that code is the same for all providers and we're only seeing the issue with AAD.
