### ISSUE TITLE
🚀 Feature: DOCKER_BUILDKIT=1 kaniko, buildahm buildkit

### ISSUE THREAD

**Issue by nightmareze1** [backstage/backstage#18168]
### 🔖 Feature description

For running backstage in containers you need configure DOCKER_BUILDKIT=1 and compile the container.

### 🎤 Context

Today! Kubernetes is running with containerd and the new compile tools are: kaniko, buildah, buildkit.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Could you provide some more information? It's not quite clear what you're asking for at this point

**Comment by nightmareze1** [comment]
Is it possible to build a container using Buildkit, Kaniko, or Buildah for backstage, considering that I don't have the option to use DOCKER_BUILDKIT=1 without Docker?

**Comment by nightmareze1** [comment]
<img width="587" alt="Screenshot 2023-06-08 at 16 23 09" src="https://github.com/backstage/backstage/assets/30803628/070a753f-ed1a-4624-8fc5-964b6c082729">
