### ISSUE TITLE
🚀  Feature: Using Event-Based Entity Discovery via `catalog:promote` scaffolder action

### ISSUE THREAD

**Issue by Andy2003** [backstage/backstage#18160]
### 🔖 Need

Currently, there is no direct way to make an entity created by the scaffolder immediately visible in Backstage, especially if the entity is meant to be discovered by a DiscoveryEntityProvider like GitlabDiscoveryEntityProvider.

Although there is a scaffolder action called `catalog:register`, using it can lead to conflicts if the entity is also discovered by the entity discovery, as discussed [here](https://github.com/backstage/backstage/pull/17820#issuecomment-1567003040).

Ensuring that an entity is visible in the catalog immediately after creation serves two purposes: enhancing user-friendliness and simplifying end-to-end (E2E) tests.

### 🎉 Proposal

This proposal suggests using an event-based approach to trigger entity discovery when a new entity is created. By introducing a new scaffolder action, such as `catalog:promote`, a corresponding event will be propagated to all EntityProviders. The EntityProvider capable of handling the new entity should then initiate a rerun of the discovery process specifically for that entity.

1. `catalog:promote` Action:
    * Introduce a new scaffolder action, such as `catalog:promote`, to serve as the trigger for entity discovery.
    * When this action is executed, it will create an event that indicates the promotion of a new entity.
2. Event Propagation:
    * Utilize the [existing event propagation](https://backstage.io/docs/reference/plugin-events-node) mechanism within Backstage to broadcast the promotion event to all EntityProviders.
    * Ensure that the event is sent via the appropriate channels, such as the message bus or event bus, to reach the relevant components.
3. EntityProvider Discovery:
   * A EntityProvider can listen for the promotion event and determine if it is capable of handling the newly promoted entity.
   * The EntityProvider capable of handling the entity should initiate a rerun of the discovery process specifically for that entity.

### ❌ Risks

1. Inconsistent Event Handling: Different EntityProviders might handle the promotion event inconsistently, leading to varying behavior and potential discrepancies in entity discovery. It is crucial to establish clear guidelines and documentation to ensure consistent and predictable behavior across different providers.
2. Event Synchronization and Consistency: Coordinating the promotion events and subsequent entity discovery processes across distributed and asynchronous workers can introduce synchronization challenges. It is important to handle concurrent events and updates carefully to maintain data consistency and avoid conflicts.
3. Integration Complexity: The introduction of a new scaffolder action, event propagation, and modifications to EntityProviders can increase the overall complexity of the system. Proper documentation, guidelines, and best practices should be provided to assist developers in understanding and integrating the new mechanism effectively.
4. Limited Discovery Capabilities: Depending on the design and capabilities of EntityProviders, some providers may have limited or incomplete discovery mechanisms. This can impact the completeness and accuracy of entity discovery for certain types of entities.
5. Semantic Uniformity:
    * Determining the semantics of the message sent to EntityProviders requires careful consideration.
    * Different providers may require different sets of parameters for handling the promotion of catalog descriptors.
    * Uniform notification to various providers, including both LDAP and GitLab providers, as well as unknown or closed-source providers, may prove challenging.
    * Provider-specific handling of the message might be necessary to accommodate the diverse requirements and capabilities of different providers.
6. Asynchronous and Distributed Workers:
    * EntityProviders often operate as distributed and asynchronous workers, running across horizontally scaled nodes in different data centers.
    * Coordinating updates and avoiding conflicts is crucial to ensure data integrity.
    * Special attention must be given to scenarios where multiple hosts receive the promotion message simultaneously but perform different update operations.
    * Proper synchronization and conflict resolution mechanisms need to be implemented to prevent unintended data destruction or inconsistencies.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
Yep, I think this idea makes sense! 👍 It's quite tricky to implement right now as we don't really have a way to handle refresh requests in providers, so would need to work that our first.

**Comment by Andy2003** [comment]
@Rugvip is there anything to do in this RFC or can it be closed?

**Comment by Rugvip** [comment]
@Andy2003 do you plan to drive or do any work yourself towards it? Otherwise it's more of a feature request, and we could rebrand it as such

**Comment by Andy2003** [comment]
I don't know if I will have enough time for this rebuild in the near future. I think it will be better to change the issue to a feature request.

**Comment by Andy2003** [comment]
up
