### ISSUE TITLE
🐛 Bug Report: Additional secret fields exposed via DevTools config info

### ISSUE THREAD

**Issue by benjmac** [backstage/backstage#18176]
### 📜 Description

In working with the newly released DevTools plugin, there have been secrets exposed in the UI and via the API for certain app config fields. I've cross referenced the ones already resolved is a previous [issue](https://github.com/backstage/backstage/issues/17855) and created a new list of the ones that still exist.

Two are from plugins within the proxy config

`proxy '/jira/api' headers Authorization`
`proxy '/pagerduty' headers Authorization`

One is the scaffolder token provided from Github
`scaffolder.github.token`

One is the processor Github org provider token
`processors.githubOrg.providers.token`

Depending upon my availability within the next few weeks, I could help in investigating / resolving the issue.

### 👍 Expected behavior

Expected behavior is that the secrets / tokens would be redacted in the config load for the DevTools api and page.

### 👎 Actual Behavior with Screenshots

Actual behavior cannot be shown due to the nature of it. But those field within the config that should be redacted contain secrets.

### 👟 Reproduction steps

Configure the following fields within your app config

`proxy '/jira/api' headers Authorization`
`proxy '/pagerduty' headers Authorization`
`scaffolder.github.token`
`processors.githubOrg.providers.token`

The load the config info page within the dev tools plugin. You will see those fields are not redacted.

### 📃 Provide the context for the Bug.

We would like to be able to use the config info page within dev tools to help us understand and visualize the configs in use within our various deployed environments. Currently we cannot due to what it exposes.

### 🖥️ Your Environment

OS:   Darwin 22.5.0 - darwin/x64
node: v16.14.0
yarn: 1.22.17
cli:  0.22.7 (installed)
backstage:  1.14.0

Dependencies:
  @backstage/app-defaults                               1.3.1
  @backstage/backend-app-api                            0.4.3
  @backstage/backend-common                             0.18.5
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.2
  @backstage/backend-tasks                              0.5.2
  @backstage/backend-test-utils                         0.1.37
  @backstage/catalog-client                             1.4.1
  @backstage/catalog-model                              1.3.0
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.0
  @backstage/cli                                        0.22.7
  @backstage/config-loader                              1.3.0
  @backstage/config                                     1.0.7
  @backstage/core-app-api                               1.8.0
  @backstage/core-components                            0.12.5, 0.13.1
  @backstage/core-plugin-api                            1.5.1
  @backstage/dev-utils                                  1.0.15
  @backstage/errors                                     1.1.5
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.3
  @backstage/integration-react                          1.1.13
  @backstage/integration                                1.4.5
  @backstage/plugin-api-docs                            0.9.3
  @backstage/plugin-app-backend                         0.3.45
  @backstage/plugin-auth-backend                        0.18.3
  @backstage/plugin-auth-node                           0.2.14
  @backstage/plugin-catalog-backend-module-github       0.3.0
  @backstage/plugin-catalog-backend                     1.9.1
  @backstage/plugin-catalog-common                      1.0.13
  @backstage/plugin-catalog-graph                       0.2.30
  @backstage/plugin-catalog-import                      0.9.8
  @backstage/plugin-catalog-node                        1.3.6
  @backstage/plugin-catalog-react                       1.6.0
  @backstage/plugin-catalog                             1.11.0
  @backstage/plugin-devtools-backend                    0.1.0
  @backstage/plugin-devtools-common                     0.1.0
  @backstage/plugin-devtools                            0.1.0
  @backstage/plugin-events-node                         0.2.6
  @backstage/plugin-gcalendar                           0.3.14
  @backstage/plugin-github-actions                      0.5.18
  @backstage/plugin-github-pull-requests-board          0.1.12
  @backstage/plugin-home                                0.5.2
  @backstage/plugin-org                                 0.6.8
  @backstage/plugin-permission-backend                  0.5.20
  @backstage/plugin-permission-common                   0.7.5
  @backstage/plugin-permission-node                     0.7.8
  @backstage/plugin-permission-react                    0.4.12
  @backstage/plugin-playlist-backend                    0.3.1
  @backstage/plugin-playlist-common                     0.1.6
  @backstage/plugin-playlist                            0.1.9
  @backstage/plugin-proxy-backend                       0.2.39
  @backstage/plugin-scaffolder-backend                  1.14.0
  @backstage/plugin-scaffolder-common                   1.3.0
  @backstage/plugin-scaffolder-node                     0.1.3
  @backstage/plugin-scaffolder-react                    1.4.0
  @backstage/plugin-scaffolder                          1.13.1
  @backstage/plugin-search-backend-module-catalog       0.1.1
  @backstage/plugin-search-backend-module-elasticsearch 1.3.0
  @backstage/plugin-search-backend-module-pg            0.5.6
  @backstage/plugin-search-backend-module-techdocs      0.1.1
  @backstage/plugin-search-backend-node                 1.2.1
  @backstage/plugin-search-backend                      1.3.1
  @backstage/plugin-search-common                       1.2.3
  @backstage/plugin-search-react                        1.6.0
  @backstage/plugin-search                              1.3.0
  @backstage/plugin-sonarqube-backend                   0.1.10
  @backstage/plugin-sonarqube-react                     0.1.5
  @backstage/plugin-sonarqube                           0.6.7
  @backstage/plugin-tech-radar                          0.6.4
  @backstage/plugin-techdocs-addons-test-utils          1.0.13
  @backstage/plugin-techdocs-backend                    1.6.2
  @backstage/plugin-techdocs-module-addons-contrib      1.0.13
  @backstage/plugin-techdocs-node                       1.7.1
  @backstage/plugin-techdocs-react                      1.1.6
  @backstage/plugin-techdocs                            1.6.2
  @backstage/plugin-user-settings                       0.7.3
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.3.1
  @backstage/theme                                      0.2.19, 0.3.0
  @backstage/types                                      1.0.2
  @backstage/version-bridge                             1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by adamdmharvey** [comment]
Regarding the proxy, I have a feeling this is may be a bug in how the config loader identifies if a value is secret or not?

For the Proxy Backend plugin, it already defines the Authorization header as secret here:

https://github.com/backstage/backstage/blob/e6a95ed3d7a7c04f0216ca356fb9f79f9bb683db/plugins/proxy-backend/config.d.ts#L34-L38

Which should thus hide it in the DevTools plugin.  But I can see on a sample instance with a fake proxy config and a blank token, that I too see a potentially exposed variable for another plugin that

**Comment by sennyeya** [comment]
@adamdmharvey It looks like @benjmac is on `0.2.39`, but these changes were included as part of the prerelease [`0.2.40-next-1`](https://github.com/backstage/backstage/blob/e6a95ed3d7a7c04f0216ca356fb9f79f9bb683db/plugins/proxy-backend/CHANGELOG.md#0240-next1). Can you try bumping your `@backstage/plugin-proxy-backend` plugin to `0.2.40.next-1` and see if the proxy issues still show up?

We should probably add a note in DevTools for this as a minimum version thing.

**Comment by adamdmharvey** [comment]
Oh great catch, @sennyeya !

That would be officially coming out in Backstage v1.15 if I'm not mistaken?

Ref this fix: https://github.com/backstage/backstage/pull/17959

**Comment by sennyeya** [comment]
@adamdmharvey Yup, should be out next week if I understand the release schedule correctly.

@benjmac If you want to update this before the release, take a look at [this doc](https://backstage.io/docs/getting-started/keeping-backstage-updated/#updating-backstage-versions-with-backstage-cli), specifically `yarn backstage-cli versions:bump --release next`.

**Comment by adamdmharvey** [comment]
For the others, I'm going to guess `scaffolder.github.token` is exposed because it's not defined here:

https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/config.d.ts

@benjmac In your config, if you run,

```
yarn backstage-cli config:check --config app-config.yaml --strict --lax
```

do you get this error:

> Config must NOT have additional properties { additionalProperty=github } at /scaffolder

(note you may get others :) but i'd bet this one is erroring)

If so then I'd guess scaffolder backend needs a patch to support the full extended config schema.

**Comment by freben** [comment]
Note that `scaffolder.github.token` is deprecated and you should use integrations instead.

**Comment by benjmac** [comment]
@adamdmharvey Confirmed I am getting that error. @freben also noted that we should alter our config to use integrations for the scaffolder. Thank you.

**Comment by TBragi** [comment]
I also experience this bug for the [`catalog.providers.microsoftGraph.Org.<instanceName>.clientSecret`](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/config.d.ts#L239) which is set to `@visibility secret`

**Comment by sennyeya** [comment]
@TBragi Can you open a separate bug ticket with your issue and include version numbers? Thanks!

**Comment by TBragi** [comment]
> @TBragi Can you open a separate bug ticket with your issue and include version numbers? Thanks!

@sennyeya, @tomasmota has been kind enough to do it for me! 😄 
https://github.com/backstage/backstage/issues/18812

**Comment by Rugvip** [comment]
I found that we have a couple of invalid configuration schemas that are contributing to this problem. Shipping #18837 to reject those schemas upfront to make sure schema errors aren't silently ignored.

**Comment by awanlin** [comment]
As @Rugvip noted PR #18837 does resolve a number of this issues which is great. I've gone over the items listed in this issue and most are now fixed.

@benjmac I can't find where this `processors.githubOrg.providers.token` is from, based on the details you shared you are using `0.3.0` of `@backstage/plugin-catalog-backend-module-github` but when I look at it's config file I don't see a token anywhere: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/config.d.ts 🤔

**Comment by awanlin** [comment]
Hi everyone, I'd like to close this so that way if someone comes across it they can see it was actioned and closed intentionally and not by the stale bot. If there are more issues like this please open a new issue for the specific item 👍
