### ISSUE TITLE
🐛 Bug Report: SAML Auth Provider NotFoundError

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#18171]
### 📜 Description

When attempting to make use of the saml auth provider i get the following error:
```
"error": {
"name": "NotFoundError",
"message": "Auth provider registered for 'saml' is misconfigured. This could mean the configs under auth.providers.saml are missing or the environment variables used are not defined. Check the auth backend plugin logs when the backend starts to see more details.",
```

```
// app-config.yaml
auth:
  environment: development
  providers:
    saml: # Okta IDP SAML with SCIM Provisioning
      development:
        entryPoint: 'https://oktapreview.com/app/insertsionxxxx';
        issuer: 'http://www.okta.com/xxx'
```

```
// packages/app/api.ts

 const samlAuthApiRef: ApiRef<
    ProfileInfoApi & 
    BackstageIdentityApi & 
    SessionApi
  > = createApiRef({
    id: 'internal.auth.saml',
  });

export const apis: AnyApiFactory[] = [
  createApiFactory({
    api: discoveryApiRef,
    deps: { configApi: configApiRef },
    factory: ({ configApi }) => AuthProxyDiscoveryApi.fromConfig(configApi),
  }),

  createApiFactory({
    api: scmIntegrationsApiRef,
    deps: { configApi: configApiRef },
    factory: ({ configApi }) => ScmIntegrationsApi.fromConfig(configApi),
  }),

  // Okta SAML / SCIM Error
  createApiFactory({
    api: samlAuthApiRef,
    deps: {
      configApi: configApiRef,
      discoveryApi: discoveryApiRef,
    },
    factory: ({ discoveryApi, configApi }) =>
      SamlAuth.create({
        discoveryApi,
        environment: configApi.getString('auth.environment'),
      }),
    }),
  ];
```

Error when re-directed to: http://localhost:7007/api/auth/saml/start?env=development

 "NotFoundError: Auth provider registered for 'saml' is misconfigured. This could mean the configs under auth.providers.saml are missing or the environment variables used are not defined. Check the auth backend plugin logs when the backend starts to see more details

"response": {
"statusCode": 404

### 👍 Expected behavior

Authenticate 

### 👎 Actual Behavior with Screenshots

N/A

### 👟 Reproduction steps

Launch IDP using the `samlAuthApiRef` - 

```
  const providers = [
    {
      id: 'saml-auth-provider',
      title: 'SAML',
      message: 'Sign In using SAML',
      apiRef: samlAuthApiRef,
    },
]
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
The SAML provider doesn't have the same env separation as the OAuth providers do, so you'll want to drop the `development:` part of the config and list things straight under `saml:`
