### ISSUE TITLE
🐛 Bug Report: Auth response is missing cookie nonce

### ISSUE THREAD

**Issue by darrell-hart** [backstage/backstage#18170]
### 📜 Description

I try and access CI/CD.

https://backstage-dev.mydomain.com/api/auth/github/handler/frame?env=development. renders a blank screen.
This is the callback URL I have in the github app.

This is running on K8

Here are some entries from app-config.yaml

app:
  title: Developer Portal
  baseUrl: http://localhost.  <--- No idea what this is supposed to be or whether it is even relevant.
organization:
  name: My Org
backend:
  baseUrl: http://localhost.  <--- No idea what this is supposed to be.  I have tried lots of combinations.  localhost:7007 etc
  listen:
    port: 7007

auth:
  experimentalExtraAllowedOrigins:
    - "https://*.mydomain.com"

The documentation is great for getting a local deployment up and running.  `yarn dev` works great.  The docs are not so great for getting anything up and running in production though.

### 👍 Expected behavior

prompt me to log into github

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-06-07 at 7 05 20 PM](https://github.com/backstage/backstage/assets/131400327/3df068d0-5b40-4f73-b4eb-7f60d0227051)

### 👟 Reproduction steps

deploy on kubernetes

### 🖥️ Your Environment

I try and access CI/CD.

https://backstage-dev.mydomain.com/api/auth/github/handler/frame?env=development. renders a blank screen.
This is the callback URL I have in the github app.

This is running on K8

Here are some entries from app-config.yaml

app:
  title: Developer Portal
  baseUrl: http://localhost.  <--- No idea what this is supposed to be or whether it is even relevant.
organization:
  name: My Org
backend:
  baseUrl: http://localhost.  <--- No idea what this is supposed to be.  I have tried lots of combinations.  localhost:7007 etc
  listen:
    port: 7007

auth:
  experimentalExtraAllowedOrigins:
    - "https://*.mydomain.com"

The documentation is great for getting a local deployment up and running.  `yarn dev` works great.  The docs are not so great for getting anything up and running in production though.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
There's likely something that prevents cookies from working in your setup. Double check that you don't have any proxies in-between the browser and the auth-backend that would break cookies. 

The callback at `.../handler/frame` is supposed to render a blank screen. All it does is send the session information to the parent window.

Both the app and backend base URLs should be the externally reachable URLs for each of them. In your case it's likely what you actually have instead of `https://backstage-dev.mydomain.com`

Any suggestions for how we could improve the documentation are welcome! 🙏

**Comment by darrell-hart** [comment]
I tried the suggestion provided but I am still seeing the same error.  

In the UI
```
GitHub
Auth response is missing cookie nonce
```
In the logs
`{"level":"info","message":"::ffff:10.133.0.16 - - [21/Jun/2023:14:16:32 +0000] \"GET /api/auth/github/refresh?optional&scope=repo&env=development HTTP/1.1\" 401 - \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36\"","service":"backstage","type":"incomingRequest"}`


Below is the output from backstage-cli info


OS:   Darwin 22.5.0 - darwin/arm64
node: v16.20.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.13.0

Dependencies:
  @backstage/app-defaults                          1.3.1
  @backstage/backend-app-api                       0.4.3
  @backstage/backend-common                        0.18.5
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.2
  @backstage/backend-tasks                         0.5.2
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.7
  @backstage/config-loader                         1.3.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.8.0
  @backstage/core-components                       0.13.1
  @backstage/core-plugin-api                       1.5.1
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.3
  @backstage/integration-react                     1.1.13
  @backstage/integration                           1.4.5
  @backstage/plugin-api-docs                       0.9.3
  @backstage/plugin-app-backend                    0.3.45
  @backstage/plugin-auth-backend                   0.18.3
  @backstage/plugin-auth-node                      0.2.14
  @backstage/plugin-catalog-backend-module-github  0.3.0
  @backstage/plugin-catalog-backend                1.9.1
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.30
  @backstage/plugin-catalog-import                 0.9.8
  @backstage/plugin-catalog-node                   1.3.6
  @backstage/plugin-catalog-react                  1.6.0
  @backstage/plugin-catalog                        1.11.0
  @backstage/plugin-events-node                    0.2.6
  @backstage/plugin-github-actions                 0.5.18
  @backstage/plugin-org                            0.6.8
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.8
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.39
  @backstage/plugin-scaffolder-backend             1.14.0
  @backstage/plugin-scaffolder-common              1.3.0
  @backstage/plugin-scaffolder-node                0.1.3
  @backstage/plugin-scaffolder-react               1.4.0
  @backstage/plugin-scaffolder                     1.13.1
  @backstage/plugin-search-backend-module-catalog  0.1.1
  @backstage/plugin-search-backend-module-pg       0.5.6
  @backstage/plugin-search-backend-module-techdocs 0.1.1
  @backstage/plugin-search-backend-node            1.2.1
  @backstage/plugin-search-backend                 1.3.1
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.6.0
  @backstage/plugin-search                         1.3.0
  @backstage/plugin-tech-radar                     0.6.4
  @backstage/plugin-techdocs-backend               1.6.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.13
  @backstage/plugin-techdocs-node                  1.7.1
  @backstage/plugin-techdocs-react                 1.1.6
  @backstage/plugin-techdocs                       1.6.2
  @backstage/plugin-user-settings                  0.7.3
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.1
  @backstage/theme                                 0.3.0
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4

**Comment by Rugvip** [comment]
@darrell-hart both the app and backend baseUrls should be the externally reachable URLs, i.e. what you put in your browser address bar. Most likely that does not include the `:7007` port as that's generally not the port that is used externally. I would try to remove the trailing `/`'s in both URLs though. We aim to support them but it may be that there is some case where they break the login flow.

**Comment by Punit12057** [comment]
Is this issue resolved for you. If yes please can you provide the solution here also.

**Comment by davidkarlsen** [comment]
I'm seeing the same - did you ever solve it @darrell-hart ?

**Comment by mg-i-ale-for** [comment]
I have the same problem, I don't know how to proceed

<img width="619" alt="Screenshot 2023-12-14 alle 15 59 06" src="https://github.com/backstage/backstage/assets/143388357/dd4bcd7b-692e-4770-9e0b-1a41e201a55d">

**Comment by davidkarlsen** [comment]
Try to upgrade to latest backstage release - then you are rid of this problem but get a new.

**Comment by mg-i-ale-for** [comment]
I updated to 1.20.3 and the error persists :(

**Comment by vinzscam** [comment]
Hi @davidkarlsen, could you share the new issue you are getting?

**Comment by davidkarlsen** [comment]
@vinzscam that was my own ignorance in #21865
