### ISSUE TITLE
%0A Newline at the end of talentID when using Microsoft auth provider

### ISSUE THREAD

**Issue by Mehmoodhassan** [backstage/backstage#18206]
### 📜 Description

Hi everyone,
I have deployed backstage at AKS-cluster using host-build docker image and configured Microsoft auth provider like this

```
microsoft:
      development:
        clientId: ${AUTH_MICROSOFT_CLIENT_ID}
        clientSecret: ${AUTH_MICROSOFT_CLIENT_SECRET}
        tenantId: ${AUTH_MICROSOFT_TENANT_ID}
```
When I click on signin button at backstage under providers section: it try to authenticate but produce an error 
`Bad Request - Invalid URL
HTTP Error 400. The request URL is invalid.`
But when I look closer to the URL, backstage is adding newline after the talentID like this 
`https://login.microsoftonline.com/talentID%0A/oauth2/v2.0/authorize?response_typ.........`
 when I removed that newline and tested manually I starts working.

### 👍 Expected behavior

I want to authenticate all aks cluster using Microsoft auth provider.

### 👎 Actual Behavior with Screenshots

Backstage reads the env from kubernetes  secret with newline at the end, causing issue with Microsoft authentication. 

### 👟 Reproduction steps

Enable Microsoft authentication in app-config.yaml
Configure Microsoft provider to use secret for the provider credentials.

### 🖥️ Your Environment

Backstage is deployed to kubernetes, with a  secrets containing provider credentials.

Output of yarn `backstage-cli info:`
`OS:   Linux 5.15.0-73-generic - linux/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.14.0

Dependencies:
  @backstage/app-defaults                          1.3.1
  @backstage/backend-app-api                       0.4.3
  @backstage/backend-common                        0.18.5
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.2
  @backstage/backend-tasks                         0.5.2
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.7
  @backstage/config-loader                         1.3.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.8.0
  @backstage/core-components                       0.13.1, 0.9.5
  @backstage/core-plugin-api                       1.5.1
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.3
  @backstage/integration-react                     1.1.13
  @backstage/integration                           1.4.5
  @backstage/plugin-api-docs                       0.9.3
  @backstage/plugin-app-backend                    0.3.45
  @backstage/plugin-auth-backend                   0.18.3
  @backstage/plugin-auth-node                      0.2.14
  @backstage/plugin-catalog-backend-module-github  0.3.0
  @backstage/plugin-catalog-backend-module-gitlab  0.2.1
  @backstage/plugin-catalog-backend                1.9.1
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.30
  @backstage/plugin-catalog-import                 0.9.8
  @backstage/plugin-catalog-node                   1.3.6
  @backstage/plugin-catalog-react                  1.6.0
  @backstage/plugin-catalog                        1.11.0
  @backstage/plugin-events-node                    0.2.6
  @backstage/plugin-github-actions                 0.5.18
  @backstage/plugin-kubernetes-backend             0.11.0
  @backstage/plugin-kubernetes-common              0.6.3
  @backstage/plugin-kubernetes                     0.9.1
  @backstage/plugin-org                            0.6.8
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.8
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.39
  @backstage/plugin-scaffolder-backend             1.14.0
  @backstage/plugin-scaffolder-common              1.3.0
  @backstage/plugin-scaffolder-node                0.1.3
  @backstage/plugin-scaffolder-react               1.4.0
  @backstage/plugin-scaffolder                     1.13.1
  @backstage/plugin-search-backend-module-catalog  0.1.1
  @backstage/plugin-search-backend-module-pg       0.5.6
  @backstage/plugin-search-backend-module-techdocs 0.1.1
  @backstage/plugin-search-backend-node            1.2.1
  @backstage/plugin-search-backend                 1.3.1
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.6.0
  @backstage/plugin-search                         1.3.0
  @backstage/plugin-tech-radar                     0.6.4
  @backstage/plugin-techdocs-backend               1.6.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.13
  @backstage/plugin-techdocs-node                  1.7.1
  @backstage/plugin-techdocs-react                 1.1.6
  @backstage/plugin-techdocs                       1.6.2
  @backstage/plugin-user-settings                  0.7.3
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.1
  @backstage/theme                                 0.2.19, 0.3.0
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4
Done in 1.03s.`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Mehmoodhassan** [comment]
@Rugvip @benjdlambert

**Comment by freben** [comment]
At least after a cursory search for all of the usages of tenantID usage in the code, I can't find anything that seems that it'd be able to insert odd extra characters. Did you perhaps accidentally have a newline inside the `AUTH_MICROSOFT_TENANT_ID` env variable?

**Comment by Mehmoodhassan** [comment]
I have dockerized the backstage and passing evns values using k8s secret.

**Comment by freben** [comment]
Alright. Yeah I feel pretty confident that this line feed somehow ended up in the input environment variable. Would be nice if you could validate that somehow, eg by echoing it followed by something else
