### ISSUE TITLE
🚀 Feature: Preferably use the title field when displaying entity related information

### ISSUE THREAD

**Issue by nanjingfm** [backstage/backstage#18212]
### 🔖 Feature description

Currently entity is displayed in most places using the `metadata.title` field, but the `metadata.name` is still used when displaying entity association information. e.g:

![image](https://github.com/backstage/backstage/assets/18688410/d0dc3cc6-8427-4279-afd6-1a32e1f5e19f)

When filtering by owner in the catalog page, the list displayed and the filtered items do not match, which can be confusing.

![image](https://github.com/backstage/backstage/assets/18688410/1bdb2a6e-a040-4317-b17a-0774fc0defca)

### 🎤 Context

Using a unified field display can be more user-friendly.

### ✌️ Possible Implementation

Is it possible to use the `api/catalog/entities/by-refs` api to query the title field and display it where needed.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @nanjingfm, pretty sure this is related to: https://github.com/backstage/backstage/issues/15965

Also, worth mentioning that for Users and Groups it will often use the `spec.profile.displayName` as that is the value I see for most of the items your have pointed out in your screenshot. I think System is the only one that for sure is using `metadata.name` still in the Catalog table.
