### ISSUE TITLE
🚀 Feature: configurable width of tech-docs

### ISSUE THREAD

**Issue by drummerwolli** [backstage/backstage#18214]
### 🔖 Feature description

You should add a config option to specify the max-width of the tech-docs.

### 🎤 Context

On bigger screens, the tech-docs become hard to read due to long lines:

![image](https://github.com/backstage/backstage/assets/3867569/c65d4982-64d0-4379-af5c-44ab8a80ea07)

It would be good if administrators of backstage deployments can specify a max length (default: current behaviour, so 100%) to improve readability:

![Untitled](https://github.com/backstage/backstage/assets/3867569/6b265447-eed7-49af-a358-ac796383f8ca)

### ✌️ Possible Implementation

a tech docs config where people could specify a pixel value or any other css value to specify the width.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by drummerwolli** [comment]
I tried to check and fix this myself but struggled in the codebase. any pointers on how to implement this would be great, as I'm not the best Frontend expert. But I guess If you take the time to guide me through, you would be quick also to implement this yourself, I assume.

**Comment by mtvx** [comment]
Also wondering about the same. Tried a few apparoches, but the techdocs being embedded in the _shadow DOM_ make it more difficult, ie. the usual CSS selectors don't work.

Did not find solution yet.
