### ISSUE TITLE
🚀 Feature: Create missing entities from template using discovery providers

### ISSUE THREAD

**Issue by dawilk** [backstage/backstage#18218]
### 🔖 Feature description

I would like to add a flag (e.g. `createEntitiesWithoutLocations: true`) on a discovery provider that would effectively generate entities from the repositories that don't have catalog-info.yaml (yet). This would essentially be an additional way to handle the Location entities excluded by the flag `validateLocationsExist` as is currently available in the GitHub discovery provider.
After catalog-info.yaml files are added and discovered, the generated entities would then get updated/replaced during the next discovery / webhook event.
This feature would also flow nicely into a potential plugin integration between discovery and the CatalogImportApi to automatically open PRs with the generated custom/templated entity information.

### 🎤 Context

I have a use-case where it would help to pre-generate entities for repositories that pass the `filters` checks during discovery, but which don't yet have a catalog-info.yaml in them. There can be hundreds or thousands of these - especially after a product or company is acquired and we want to bulk load the software into the catalog.
A feature like this would allow a rapid initial import, and kickstart filling the catalog without the need to create PRs across hundreds of microservice repos using `/catalog-import`. It would also provide a useful way to tag/highlight all the software that needs catalog-info created/updated.

### Example scenario:

Let's say I have 2000 repos in a GitHub org, and my discovery configuration filters down to 1500, but only 200 have catalog-info files. I want the discovery provider to create the missing 1300 entities from an entity template (perhaps configurable in the discovery provider). Those 1300 entities will then be updated/replaced by that repo's catalog-info.yaml once it is eventually added.

### ✌️ Possible Implementation

This is what I did locally with a few small modifications to `@backstage/plugin-catalog-backend-module-github`, and I propose something similar be done here:

1. Move the `this.config.validateLocationsExist` check up one level in `GithubEntityProvider` from `findCatalogFiles()` to the `refresh()` function. Also, possibly rename this function to something like `findCatalogRepositories()` since it's ultimately returning repository information, not just files.
2. If `this.config.createEntitiesWithoutLocations` is set, map an additional `DeferredEntity[]` list of non-Location entities based on `!repository.isCatalogInfoFilePresent`.
3. combine the Location and non-Location entities when calling `applyMutation()`.

A template would also need to be defined for the default entity configuration. Ideally, a global default entity type with a deep merge from provider-specific project/repo properties, and then addition merge if a custom template or overrides are configured.

I'm doing all this in my local implementation by something like this:
```diff
async refresh(logger: Logger) {
...
-    const entities = matchingTargets
+    const entities: DeferredEntity[] = matchingTargets
+      .filter(repository => repository.isCatalogInfoFilePresent
+        || !this.config.validateLocationsExist)
      .map(repository => this.createLocationUrl(repository))
      .map(GithubEntityProvider.toLocationSpec)
      .map(location => {
        return {
          locationKey: this.getProviderName(),
          entity: locationSpecToLocationEntity({ location }),
        };
      });
+    let missingEntities: DeferredEntity[] = []
+    if (this.config.createEntitiesWithoutLocations) {
+      missingEntities = matchingTargets
+        .filter(repository => !repository.isCatalogInfoFilePresent)
+        .map(this.repositoryToEntity)
+        .map(entity => {
+          return {
+            locationKey: this.getProviderName(),
+            entity,
+          }}
+        );
+    }

    await this.connection.applyMutation({
      type: 'full',
-      entities,
+      entities: [...entities, ...missingEntities],
    });
...

  private async findCatalogFiles(): Promise<Repository[]> {
...

-    if (this.config.validateLocationsExist) {
-      return repositories.filter(
-        repository => repository.isCatalogInfoFilePresent,
-      );
-    }

    return repositories;
  }
```

...and then the `repositoryToEntity` function is currently pretty static below. NOTE: since a valid `owner` is required to pass processing checks, this might have to be provided input or use some kind of placeholder/default.

```diff
+  private repositoryToEntity(
+    repository: Repository,
+  ): Entity {
+    const defaultBranchName = repository.defaultBranchRef!.replace(/refs\/heads\//, '') || 'main'
+    const locationUrl = `${repository.url}/blob/${defaultBranchName}/catalog-info.yaml`
+    const type = 'unknown'
+    const lifecycle = (repository.repositoryTopics.filter(topic => topic.match(/experimental|production/))).pop() || 'unknown'
+    const owner = 'default-team'

+    return {
+      apiVersion: 'backstage.io/v1alpha1',
+      kind: 'Component',
+      spec: {
+        type,
+        lifecycle,
+        owner,
+      },
+      metadata: {
+        name: repository.name,      
+        description: repository.description ?? undefined,
+        tags: [
+          'catalog-info-missing',
+          ...(repository.repositoryTopics ?? undefined),
+        ],
+        annotations: {
+          'backstage.io/source-location': `url:${repository.url}/tree/${defaultBranchName}/`,
+          'backstage.io/managed-by-location': `url:${locationUrl}`,
+          'backstage.io/managed-by-origin-location': `url:${locationUrl}`,
+        },
+      }
+    };
+  }
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dawilk** [comment]
Just to add a quick update on this - Since last week, I've also implemented equivalent functionality in my local copy of the gitlab and azure plugins. I'm exploring how to centralize some functionality in the common catalog modules, and then make it extendable for each provider.

**Comment by mikeyhc** [comment]
Hey @dawilk, thanks for your work on this. However after discussion amongst the maintainers we don't believe this functionality is not aligned with the direction we want for the Catalog. The creation of skeleton style Entities would fill the Catalog with a lot of low-value information, and this is a pattern we are trying to avoid. If you have any questions feel free to reach out.
