### ISSUE TITLE
🚀 Feature: Expose `humanizeEntityRef` as a filter

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [backstage/backstage#18232]
### 🔖 Feature description

Expose the `humanizeEntityRef` function in `@backstage/plugin-catalog-react` as a filter in `@backstage/plugin-scaffolder-backend` so that this filter can be used after `parseEntityRef` like

```
${{ values.owner | parseEntityRef | humanizeEntityRef({defaultKind: 'group'}) }}
```

### 🎤 Context

This is in relation to #17053 and #16577. These issues and PR have removed the ability to get a humanized response based on a default `Kind` and `Namespace`. This is useful when we don't want the full entity ref for a given default `Kind` and `Namespace`.

The `pick` filter is not sufficient as complex logic to determine whether values are default or not makes things complicated. Since the `humanizeEntityRef` already exists and works nicely with the `parseEntityRef ` filter, exposing it by default would be great!

### ✌️ Possible Implementation

https://github.com/backstage/backstage/blob/5f5727189aff6217cf4f4da996fd68692d5b4377/plugins/scaffolder-backend/src/lib/templating/filters.ts#L16-L37
can be updated as
```ts
import { CompoundEntityRef, parseEntityRef } from '@backstage/catalog-model';
import { ScmIntegrations } from '@backstage/integration';
import { JsonValue } from '@backstage/types';
import { humanizeEntityRef } from '@backstage/plugin-catalog-react';
import { TemplateFilter } from '..';
import { parseRepoUrl } from '../../scaffolder/actions/builtin/publish/util';
import get from 'lodash/get';

export const createDefaultFilters = ({
  integrations,
}: {
  integrations: ScmIntegrations;
}): Record<string, TemplateFilter> => {
  return {
    parseRepoUrl: url => parseRepoUrl(url as string, integrations),
    parseEntityRef: ref => parseEntityRef(ref as string),
    humanizeEntityRef: (ref, opts) =>
      humanizeEntityRef(
        ref as CompoundEntityRef,
        opts as { defaultKind?: string; defaultNamespace?: string },
      ),
    pick: (obj: JsonValue, key: JsonValue) => get(obj, key as string),
    projectSlug: repoUrl => {
      const { owner, repo } = parseRepoUrl(repoUrl as string, integrations);
      return `${owner}/${repo}`;
    },
  };
};
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Sounds like a sensible feature addition. Feel free to make a pull request for it! However, your example shows `parseEntityRef` followed by `humanizeEntityRef` - it would probably be a useful feature to let `humanizeEntityRef` accept strings directly (that are assumed to be refs which it parses internally) as a convenience.

**Comment by SayakMukhopadhyay** [comment]
> it would probably be a useful feature to let humanizeEntityRef accept strings directly (that are assumed to be refs which it parses internally) as a convenience.

Yeah, its how I am doing it internally. I agree that having a single level filter would be better.

But there are certain issues with using the `humanizeEntityRef` function as is. It's defined in a frontend plugin and importing that function into a backend plugin throws module issues in imports. Any idea how to get around it? Maybe carve off the `util` module?

**Comment by SayakMukhopadhyay** [comment]
> However, your example shows `parseEntityRef` followed by `humanizeEntityRef` - it would probably be a useful feature to let `humanizeEntityRef` accept strings directly (that are assumed to be refs which it parses internally) as a convenience.

On second thought @freben , I think it would be better to not have the `parseEntityRef` logic in this filter as that would create a difference in implementation of this filter and how `humanizeEntityRef` is actually implemented. The function as defined in https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/components/EntityRefLink/humanize.ts and I don't think we should change the types in the signature for the filter as it might create confusion down the line. Moreover, in my example, I am showing how this filter can be used after a `parseEntityRef` but looking at the signature of `humanizeEntityRef` we can even pass a full fledged `Entity` object to it.

There is a blocker though. `humanize.ts` is in `catalog-react` and importing functions from there is causing import issue. I feel like we can move `humanize.ts` to `packages/catalog-model/entity`.

**Comment by benjdlambert** [comment]
So I don't think that we should change the interface for either `parseEntityRef` or `humanizeEntityRef`. I think that the filter would be able to work out what the input type is, and then be able to pass the correct input type to `humanizeEntityRef` under the hood. The filter wouldn't just be the function inline, it would wrap up the underlying implementation.

@freben thoughts on moving the `humanize` logic? Wondering if we should just duplicate it for now?

**Comment by SayakMukhopadhyay** [comment]
> The filter wouldn't just be the function inline, it would wrap up the underlying implementation.

I think this would be a bit of a departure of how the other filters are implemented, which are essentially the functions themselves.
