### ISSUE TITLE
🚀 Feature: Allow configuring the `readMoreUrl` field in TechDocs MissingAnnotations component.

### ISSUE THREAD

**Issue by zinizhu** [backstage/backstage#18241]
### 🔖 Feature description

Allow configuring the `readMoreUrl` field in [TechDocs MissingAnnotations component](https://github.com/backstage/backstage/blob/864cdace032a5deebbc935bae1022ee6dc3ee11d/plugins/techdocs/src/Router.tsx#L60).

### 🎤 Context

The `MissingAnnotationEmptyState` component allows to configure the [`readMoreUrl`](https://github.com/backstage/backstage/blob/e6a95ed3d7a7c04f0216ca356fb9f79f9bb683db/packages/core-components/src/components/EmptyState/MissingAnnotationEmptyState.tsx#L96) property. In TechDocs, this field is [not configured](https://github.com/backstage/backstage/blob/864cdace032a5deebbc935bae1022ee6dc3ee11d/plugins/techdocs/src/Router.tsx#L81) so the default value is used. 

In our org, we want to link to our internal TechDocs guide instead of the Backstage doc. Can we make this field configurable via app-config.yaml? 

### ✌️ Possible Implementation

Add `techdocs.missingAnnotationReadMoreUrl` field in `app-config.yaml`.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by snehaljos** [comment]
Hi, can i work on this

**Comment by zinizhu** [comment]
> Hi, can i work on this

That'd be great, thank you!

**Comment by snehaljos** [comment]
Working on this
