### ISSUE TITLE
🚀 Feature: Align SonarQube plugin with ADR on Luxon date formats

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#18259]
### 🔖 Feature description

Noticed that the date formats being printed out by the SonarQube frontend plugin are custom:

https://github.com/backstage/backstage/blob/77d59204854e92ff23209b90737f87b677cc9f38/plugins/sonarqube/src/components/SonarQubeCard/SonarQubeCard.tsx#L273-L284

They're also only displayed in a US friendly format, which isn't great for an international audience.

They should likely be updated to align to the Backstage ADR indicating alignment to the Luxon date library for consistent date formatting:

https://backstage.io/docs/architecture-decisions/adrs-adr012/

### 🎤 Context

In reviewing some of the code, I noticed a toDateLocale string and remembered the ADR.

### ✌️ Possible Implementation

Refactoring of the code referenced with the ADR referenced. There may be other date strings in the plugin, I didn't look in depth.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this. could you please describe in simple words what the proposed changes will be?

**Comment by freben** [comment]
@tarunsamanta2k20 The linked ADR shows what the actual desired code should look like. The description of this issue shows the non-conformant code. You'll want to run the plugin and see that the changed code makes for a nicely looking user interface.

I'll assign you for now.

**Comment by mclarke47** [comment]
@freben I'm wondering if there should be components to wrap datetimes so they can be rendered the same every time?

**Comment by npiyush97** [comment]
@adamdmharvey have a look
