### ISSUE TITLE
🚀 Feature: Make Entity AboutCard easy to customize

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#18262]
### 🔖 Feature description

Allow for backstage users to easily customize an entity `AboutCard` to include additional info without having to build their own cards from scratch.

### 🎤 Context

I have begun to attach custom annotations to my entities and would like to surface them in the AboutCard. Currently my options are:

- Completely re-implement the about card from scratch, which is a lot of work to re-implement / copy paste
- Add another card underneath the about card with additional info

Neither of these solutions feel great if all I want to do is add a few pieces of info. The first one seems like too much work and the second one doesn't look nice in the UI

### ✌️ Possible Implementation

Allow for a user to pass in a list of additional <AboutField> headers to the AboutCard which will be appended to the end of the card content.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
I agree with you on this but want to just share that there is a lot of prior conversations on this:

- https://github.com/backstage/backstage/issues/15643
- https://github.com/backstage/backstage/pull/12651
- https://github.com/backstage/backstage/pull/15069
- https://github.com/backstage/backstage/pull/15306
- https://github.com/backstage/backstage/pull/14544
- https://github.com/backstage/backstage/pull/14391

And I think this RFC is really where we are going to get what we want if I remember all the discussion on this topic: https://github.com/backstage/backstage/issues/16876
