### ISSUE TITLE
🐛 Bug Report: Microsoft auth provider fails to refresh token

### ISSUE THREAD

**Issue by sanderaernouts** [backstage/backstage#18271]
### 📜 Description

Whenever I refresh a backstage page or when I have had backstage open for a while, I have to sign in again. 

In the network tab of the dev tools I see that calls to `api/auth/microsoft/refresh` fail with status code `401`. The response from the server is `Refresh failed; caused by InputError: Missing session cookie`. A `microsoft.refreshtoken` cookie is available but the `path` seems wrong. As you can see in the screenshot below the path is `//api/auth/microsoft` instead of `/api/auth/microsoft`. If I edit the cookie an change the path to `/api/auth/microsoft` calls to `api/auth/microsoft/refresh` work as expected.

![image](https://github.com/backstage/backstage/assets/6184673/6c6f5a8e-a791-4ac4-83eb-26fe432cbf5c)

### Full error message
```json
{
  "error": {
    "name": "AuthenticationError",
    "message": "Refresh failed; caused by InputError: Missing session cookie",
    "cause": {
      "name": "InputError",
      "message": "Missing session cookie",
      "stack": "InputError: Missing session cookie\n    at OAuthAdapter.refresh (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:457:15)\n    at OAuthEnvironmentHandler.refresh (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:206:58)\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/app/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)"
    }
  },
  "request": {
    "method": "GET",
    "url": "/api/auth/microsoft/refresh?optional&env=development"
  },
  "response": {
    "statusCode": 401
  }
}
```

### 👍 Expected behavior

Given that I have signed in once using the Microsoft authentication provider, when I refresh my browser window I do not have to sign in again.

### 👎 Actual Behavior with Screenshots

When I refresh my browser window, I must sign in again because the call to `/api/microsoft/refresh` fails with status code `401`.
![image](https://github.com/backstage/backstage/assets/6184673/a4a1ead3-d5c8-4d54-a324-a00877c0ef08)

### 👟 Reproduction steps

0. Make sure you have the Microsoft authentication provider configured
1. Sign in to Backstage using a Microsoft account
2. Refresh the page
3. You have to sign in again

### 📃 Provide the context for the Bug.

Calls to `/api/microsoft/refresh` fails with status code `401`.
![image](https://github.com/backstage/backstage/assets/6184673/a4a1ead3-d5c8-4d54-a324-a00877c0ef08)

This happens because the browser does not send any cookies with this request:
![image](https://github.com/backstage/backstage/assets/6184673/f3458e67-7d3a-4ac5-aefd-3d65654f60a3)

The required cookies are present in cookie storage, but they have the wrong path (`//api/auth/microsoft` instead of `/api/auth/microsoft`):
![image](https://github.com/backstage/backstage/assets/6184673/347bbe54-94c9-43b1-9cf2-7a5209289142)

I followed the auth flow manually by invoking `https://my-backstage.instance/api/auth/microsoft/start?env=development&scope=openid`, and the issue is in the redirect to `api/microsoft/handler/frame`. I end up at this URL  `https://my-backstage.instance//api/auth/microsoft/handler/frame`. As you can see, the path is `//api/auth/microsoft/handler/frame`, which the `OAuthAdapter` converts to `//api/auth/microsoft` as the `path` for the cookies.

The `redirect_uri` passed to `login.microsoftonline.com` is wrong. The following URL is used: 
`https://login.microsoftonline.com/<tenant>/oauth2/v2.0/authorize?response_type=code&redirect_uri=https%3A%2F%2Fmy-backstage.instance%2F%2Fapi%2Fauth%2Fmicrosoft%2Fhandler%2Fframe&scope=openid&state=<state>&client_id=<id>` which contains `redirect_uri=https://my-backstage.instance//api/auth/microsoft/handler/frame`

### 🖥️ Your Environment

OS:   Windows_NT 10.0.22621 - win32/x64
node: v18.15.0
yarn: 3.5.0
cli:  0.22.6 (installed)
backstage:  1.13.2

Dependencies:
  @backstage/app-defaults                          1.3.0
  @backstage/backend-app-api                       0.4.2, 0.4.3
  @backstage/backend-common                        0.15.2, 0.18.4, 0.18.5
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.1, 0.5.2
  @backstage/backend-tasks                         0.5.1, 0.5.2
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.6
  @backstage/config-loader                         1.2.0, 1.3.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.7.0
  @backstage/core-components                       0.12.5, 0.13.0
  @backstage/core-plugin-api                       1.5.1
  @backstage/dev-utils                             1.0.14
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.2, 0.1.3
  @backstage/integration-react                     1.1.12
  @backstage/integration                           1.4.4, 1.4.5
  @backstage/plugin-api-docs                       0.9.2
  @backstage/plugin-app-backend                    0.3.44
  @backstage/plugin-auth-backend                   0.18.2
  @backstage/plugin-auth-node                      0.2.13, 0.2.14
  @backstage/plugin-azure-devops-backend           0.3.23
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.2.8
  @backstage/plugin-catalog-backend-module-azure   0.1.15
  @backstage/plugin-catalog-backend-module-msgraph 0.5.3
  @backstage/plugin-catalog-backend                1.9.0, 1.9.1
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.29
  @backstage/plugin-catalog-import                 0.9.7
  @backstage/plugin-catalog-node                   1.3.5, 1.3.6
  @backstage/plugin-catalog-react                  1.5.0
  @backstage/plugin-catalog                        1.10.0
  @backstage/plugin-github-actions                 0.5.17
  @backstage/plugin-org                            0.6.7
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.7, 0.7.8
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.38
  @backstage/plugin-scaffolder-backend             1.13.1, 1.14.0
  @backstage/plugin-scaffolder-common              1.2.7, 1.3.0
  @backstage/plugin-scaffolder-node                0.1.2, 0.1.3
  @backstage/plugin-scaffolder-react               1.3.0
  @backstage/plugin-scaffolder                     1.13.0
  @backstage/plugin-search-backend-module-catalog  0.1.0, 0.1.1
  @backstage/plugin-search-backend-module-pg       0.5.5
  @backstage/plugin-search-backend-module-techdocs 0.1.0
  @backstage/plugin-search-backend-node            1.2.0, 1.2.1
  @backstage/plugin-search-backend                 1.3.0
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.5.2
  @backstage/plugin-search                         1.2.0
  @backstage/plugin-tech-radar                     0.6.3
  @backstage/plugin-techdocs-backend               1.6.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.12
  @backstage/plugin-techdocs-node                  1.7.0
  @backstage/plugin-techdocs-react                 1.1.5
  @backstage/plugin-techdocs                       1.6.1
  @backstage/plugin-user-settings                  0.7.2
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.0
  @backstage/theme                                 0.2.19
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sanderaernouts** [comment]
I did some more digging, and the issue seems to originate from `backstage.baseUrl`. If you configure a `baseUrl` with a trailing `/`, then you end up with a redirect_url with two leading slashed in the path ( `//api`)

**Comment by freben** [comment]
Thanks for reporting. Would you like to contribute a fix that makes this particular piece of code resilient to the trailing slash? 🙏

**Comment by Rugvip** [comment]
I would! :p #18277
