### ISSUE TITLE
🚀 Feature: [Tech Insights plugin] allow the ability to trigger FactRetrievers for a specific component

### ISSUE THREAD

**Issue by sonikro** [backstage/backstage#18286]
### 🔖 Feature description

Create a new **POST** endpoint in the Tech-Insights Plugin backend, to allow for triggering the FactRetrievers for a specific component.

### 🎤 Context

Currently, FactRetrievers will only run on a schedule, and the backend plugin does not expose any other way to allow us to trigger a "recalculation of facts" to a specific component.

This means that the users are stuck with stale data (because it will wait until the FactRetriever job gets triggered, to fetch everything again).

I want to allow users of the Tech-Insights plugin to trigger a "recalculation of the facts", if they want, so they don't have to wait for the next CronJob to run.

This would be specially useful in big systems where you have thousands of components, and you don't want to be running that  big job all the time.

This would also allow us to add a **Refresh** button in the Scorecard Card, so if changes were made to the repository, users could force a Refresh of the Facts, to get the most up-to-date information, without having to wait for the next cronjob to run.

### ✌️ Possible Implementation

Create a **POST /facts/:namespace/:kind/:name** endpoint, that would trigger the **FactRetrieverHandler** where **entityFilter** is set to only filter that specific component.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Ping @Xantier not sure if you'd seen this?

**Comment by Xantier** [comment]
> Ping @Xantier not sure if you'd seen this?

I have now. Thanks @sonikro, this makes perfect sense and would be a good addition to the package. PR would be very much appreciated

**Comment by hballangan-mdsol** [comment]
+1 on this

**Comment by hballangan-mdsol** [comment]
Any update on this? Facing the same issue as we only schedule once a week. We want to manually trigger retrieval for new facts

**Comment by sonikro** [comment]
> Any update on this? Facing the same issue as we only schedule once a week. We want to manually trigger retrieval for new facts

I have a PR open already. I just got back from vacation I'll try to wrap it up this weekend.

**Comment by efenner-cambia** [comment]
@sonikro What happened with your PR?

**Comment by sonikro** [comment]
> @sonikro What happened with your PR?

I've been having some trouble getting the time to wrap it up. If someone wants to continue the work on my PR feel free to do it. If I manage to get some time to work on it next week I'll reopen the PR.
