### ISSUE TITLE
🐛 Bug Report: Tech radar plugin - data source issue - i.date.toLocaleDateString is not a function

### ISSUE THREAD

**Issue by thomasmebin** [backstage/backstage#18293]
### 📜 Description

Trying to define the data source for the tech-radar, and using below json data the radar is able to plot the required content, but we are facing an exception, when we click on the radar entries, instead of a pop-up, we are getting an error.

![image](https://github.com/backstage/backstage/assets/77664686/4ba7d03c-5d8f-40c7-9a2d-a6da8ac873e1)

**Sample source data is plotted below,**

```json
{
  "title": "Sample",
  "quadrants": [
    {
      "id": "Languages",
      "name": "Languages"
    },
    {
      "id": "Process",
      "name": "Process"
    },
    {
      "id": "Tools",
      "name": "Tools"
    },
    {
      "id": "infrastructure",
      "name": "infrastructure"
    }
  ],
  "rings": [
    {
      "id": "adopt",
      "name": "ADOPT",
      "color": "#93c47d"
    },
    {
      "id": "trial",
      "name": "TRIAL",
      "color": "#93d2c2"
    },
    {
      "id": "assess",
      "name": "ASSESS",
      "color": "#fbdb84"
    },
    {
      "id": "hold",
      "name": "HOLD",
      "color": "#efafa9"
    }
  ],
  "entries": [
    {
      "id": "typescript",
      "title": "Typescript",
      "description": "Typescript",
      "url": "https://www.typescriptlang.org/",
      "quadrant": "Languages",
      "timeline": [
        {
          "moved": 0,
          "ringId": "adopt",
          "date": "2022-02-08",
          "description": "Long description for adopt"
        }
      ]
    },
    {
      "id": "CS-tool",
      "title": "CS-tool",
      "description": "CS-tool",
      "key": "CS-tool",
      "url": "https://www.CS-tool.org/",
      "quadrant": "Tools",
      "timeline": [
        {
         "moved": 0,
          "ringId": "adopt",
          "date": "2022-02-08",
          "description": "Long description for adopt"
        }
      ]
    }
  ]
}
```

### 👍 Expected behavior

Upon clicking radar entries, a pop-up show show with further details, like below,

![image](https://github.com/backstage/backstage/assets/77664686/c0660721-3219-4715-ad71-a90aa87fa5fa)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/77664686/0f4a3c29-d159-4104-83f5-ccf1e31f40c1)

### 👟 Reproduction steps

1. open tech-radar
2. click on the entries

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
The types define `date` [to be of type Date](https://github.com/backstage/backstage/blob/cad6af7cfd0720d6f07b27155f332722338943d1/plugins/tech-radar/src/utils/types.ts#L74), not strings.
