### ISSUE TITLE
🚀 Feature: Addon support for ADR plugin

### ISSUE THREAD

**Issue by axdotl** [backstage/backstage#18294]
### 🔖 Feature description

Currently the ADR plugin does not support the Addon concept like TechDocs.
It would be great to have that support for ADRs as well.

### 🎤 Context

Like for TechDocs it would be also great to have Addon support for ADRs as well, for example to support rendering of Mermaid diagrams (see [techdocs-addon-mermaid](https://github.com/johanneswuerbach/backstage-plugin-techdocs-addon-mermaid).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by JetteBke** [comment]
I would find that feature very useful as well!

**Comment by kuangp** [comment]
hmm interesting proposal! Would definitely welcome If someone would be willing to put together a contribution or write up a some kind of RFC of how this could work 😁

**Comment by djetelina** [comment]
I'm curious whether addons are necessary, or if we all aren't simply interested in just mermaid, which could be baked in

**Comment by cmdkeen** [comment]
We're interested in PlantUML rendering for the ADR plugin - @axdotl did you get anywhere with this?

**Comment by axdotl** [comment]
> We're interested in PlantUML rendering for the ADR plugin - @axdotl did you get anywhere with this?

No, I haven't done anything to it.
