### ISSUE TITLE
🚀 Feature: process placeholder template steps

### ISSUE THREAD

**Issue by Teemukoivumaa** [backstage/backstage#18297]
### 🔖 Feature description

As stated in this issues comments: https://github.com/backstage/backstage/issues/15241 there is a use case of being able to read relative template file locations.

There should be an integration, that can read templates from the filesystem, so that templates can be split up into multiple files and then used with `- $yaml: ./step.yaml`.

As stated in this [comment](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/modules/core/PlaceholderProcessor.ts#L249) there is a security risk with this, but we could limit the paths by adding a config option that specifies the path from where the integration can read.

### 🎤 Context

This would allow to read templates that have `- $yaml: ./step.yaml` annotations if they are file-types

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by drodil** [comment]
Relates to #18296
