### ISSUE TITLE
🚀 Help migrate backend plugins to the new backend system

### ISSUE THREAD

**Issue by jhaals** [backstage/backstage#18301]
The new [backend system](https://backstage.io/docs/backend-system/) has been available in alpha since the v1.11.0 release in February and we hope to make it the default in a newly created backstage app later this year.

Since first launch, integrators have been able to run legacy plugins in the new systems using the compatibility layer created with the `legacyPlugin()` function documented in the [migration guide](https://backstage.io/docs/backend-system/building-backends/migrating).

We do however want all backend plugins available in the new system without using the compatibility layer to ease the ongoing transition. That is why we kindly request that existing backend plugins are migrated to the new [backend system](https://backstage.io/docs/backend-system/). As most plugins remain on version 0.x we recommend that the new export is marked `@public` to avoid additional changes once the API has been promoted to stable.

To avoid an ever changing target of plugins to migrate we are now requiring that new backend plugin contributions are also made available in the new system.

#### How do I know if the plugin is migrated already?

The plugin’s `api-report.md` file will contain an export returning a `BackendFeature`. In the example below, substitute `foobar` with the plugin name.
 
```ts
// @public
export const foobarPlugin: () => BackendFeature
```

See also [the todo-backend’s api-report](https://github.com/backstage/backstage/blob/master/plugins/todo-backend/api-report.md?plain=1#L94) for an example.

#### Are there examples of migrated plugins?

Here’s a couple but you can also search for `createBackendPlugin` in the repository to find implementations and read more about how the new backend system works [in the documentation](https://backstage.io/docs/backend-system/).

* [todo-backend](https://github.com/backstage/backstage/blob/99afc096e209dbee41fd9a52245d5ac4cecab05a/plugins/todo-backend/src/plugin.ts)
* [kubernetes-backend](https://github.com/backstage/backstage/blob/99afc096e209dbee41fd9a52245d5ac4cecab05a/plugins/kubernetes-backend/src/plugin.ts)
* [kafka-backend](https://github.com/backstage/backstage/blob/99afc096e209dbee41fd9a52245d5ac4cecab05a/plugins/kafka-backend/src/plugin.ts)
* [events-backend](https://github.com/backstage/backstage/blob/99afc096e209dbee41fd9a52245d5ac4cecab05a/plugins/events-backend/src/service/EventsPlugin.ts)

**Comment by awanlin** [comment]
I have plans to do the Azure DevOps, Linguist, and DevTools plugins but if someone else takes them on I won't be upset 😉

**Comment by awanlin** [comment]
> I have plans to do the Azure DevOps, Linguist, and DevTools plugins but if someone else takes them on I won't be upset 😉

PR for this is here: https://github.com/backstage/backstage/pull/18320, hopefully that might help for others as well, more examples and I also updated the `README` for these

**Comment by shivance** [comment]
@jhaals Can I contribute?

**Comment by awanlin** [comment]
Hi @shivance, for sure, just grab one of the plugins with a backend (but make sure there isn't an open PR for it already) and submit a PR with the changes. Feel free to look at the ones mentioned in this issue if you need examples! 

Many thanks for wanting to help out 🚀

**Comment by Josh-Uvi** [comment]
Created a [PR](https://github.com/backstage/backstage/pull/20504) to add support for the new backend system for the GraphQL backend plugin.

**Comment by kborchers** [comment]
Hello team. I was just wondering if there is any update on moving to the new backend system for newly created apps. I might be able to help if there are still plugins needing migration but it's hard to tell which ones still need migration.

**Comment by benjdlambert** [comment]
Hey @kborchers :wave:

> is any update on moving to the new backend system for newly created apps. 

We actually have a PR open which enables this by default #22456 

We're wrapping up some auth related work, which might bring up some more smaller changes for some plugins which you can also follow here; https://github.com/backstage/backstage/tree/master/beps/0003-auth-architecture-evolution

**Comment by camilaibs** [comment]
We are closing this issue as most of the plugins have already been migrated. It would not have been possible without everyone's help. Thanks to all of you 🙌🏻

**Comment by awanlin** [comment]
Yes, just wanted to echo @camilaibs comment, many thanks everyone!!! 🚀

**Comment by rahulsaw2003** [comment]
Does library-check plugin supports the new backend system? I dont think so, I would be happy if someone can help me to use it in the new backend system.

**Comment by awanlin** [comment]
Hi @rahulsaw2003, no idea, that plugin isn't one I'm familiar with, have you reached out to the author in their repo with an issue? That would be the best place to start 👍
