### ISSUE TITLE
🐛 Bug Report: Dynatrace plugin "view entity in dynatrace" button redirects to a 404 error page.

### ISSUE THREAD

**Issue by Zaperex** [backstage/backstage#18310]
### 📜 Description

When using the [dynatrace plugin](https://github.com/backstage/backstage/tree/master/plugins/dynatrace), the "view entity in dynatrace" button at the bottom of the [ProblemsList](https://github.com/backstage/backstage/blob/master/plugins/dynatrace/src/components/Problems/ProblemsList/ProblemsList.tsx) component redirects the user to a 404 error page.

### 👍 Expected behavior

It should load the dynatrace entity in the dynatrace webpage.

### 👎 Actual Behavior with Screenshots

Dynatrace webpage returns a 404 error.

[Video](https://github.com/backstage/backstage/assets/50030060/f67b3f12-d74a-473a-b3b5-bf6a7f9d0c51)

### 👟 Reproduction steps

1. Follow the instructions in [installing the plugin and configuring it](https://github.com/backstage/backstage/tree/master/plugins/dynatrace#getting-started) with a [valid dynatrace entity id](https://github.com/backstage/backstage/tree/master/plugins/dynatrace#view-recent-application-problems) and valid credentials. (This will require a dynatrace account)
2. Add the `DynatraceTab` into your entity page, and load a component with the dynatrace annotations in it's `catalog-info.yaml`
3. Click on the "View Entity in Dynatrace ->" button in the ProblemsList component

### 🖥️ Your Environment

OS:   Linux 6.3.6-200.fc38.x86_64 - linux/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.13.0

Dependencies:
  @backstage/app-defaults                          1.3.1
  @backstage/backend-app-api                       0.4.3
  @backstage/backend-common                        0.18.5
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.2
  @backstage/backend-tasks                         0.5.2
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.7
  @backstage/config-loader                         1.3.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.8.0
  @backstage/core-components                       0.13.1
  @backstage/core-plugin-api                       1.5.1
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.3
  @backstage/integration-react                     1.1.13
  @backstage/integration                           1.4.5
  @backstage/plugin-api-docs                       0.9.3
  @backstage/plugin-app-backend                    0.3.45
  @backstage/plugin-auth-backend                   0.18.3
  @backstage/plugin-auth-node                      0.2.14
  @backstage/plugin-azure-devops-backend           0.3.24
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.3.0
  @backstage/plugin-catalog-backend-module-github  0.3.0
  @backstage/plugin-catalog-backend-module-openapi 0.1.11
  @backstage/plugin-catalog-backend                1.9.1
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.30
  @backstage/plugin-catalog-import                 0.9.8
  @backstage/plugin-catalog-node                   1.3.6
  @backstage/plugin-catalog-react                  1.6.0
  @backstage/plugin-catalog                        1.11.0
  @backstage/plugin-dynatrace                      5.0.0
  @backstage/plugin-events-node                    0.2.6
  @backstage/plugin-github-actions                 0.5.18
  @backstage/plugin-github-issues                  0.2.7
  @backstage/plugin-home                           0.5.2
  @backstage/plugin-jenkins-backend                0.2.0
  @backstage/plugin-jenkins-common                 0.1.15
  @backstage/plugin-jenkins                        0.8.0
  @backstage/plugin-kubernetes-backend             0.11.0
  @backstage/plugin-kubernetes-common              0.6.3
  @backstage/plugin-kubernetes                     0.9.1
  @backstage/plugin-org                            0.6.8
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.8
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.39
  @backstage/plugin-scaffolder-backend             1.14.0
  @backstage/plugin-scaffolder-common              1.3.0
  @backstage/plugin-scaffolder-node                0.1.3
  @backstage/plugin-scaffolder-react               1.4.0
  @backstage/plugin-scaffolder                     1.13.1
  @backstage/plugin-search-backend-module-catalog  0.1.1
  @backstage/plugin-search-backend-module-pg       0.5.6
  @backstage/plugin-search-backend-module-techdocs 0.1.1
  @backstage/plugin-search-backend-node            1.2.1
  @backstage/plugin-search-backend                 1.3.1
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.6.0
  @backstage/plugin-search                         1.3.0
  @backstage/plugin-sonarqube-backend              0.1.10
  @backstage/plugin-sonarqube-react                0.1.5
  @backstage/plugin-sonarqube                      0.6.7
  @backstage/plugin-tech-radar                     0.6.4
  @backstage/plugin-techdocs-backend               1.6.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.13
  @backstage/plugin-techdocs-node                  1.7.1
  @backstage/plugin-techdocs-react                 1.1.6
  @backstage/plugin-techdocs                       1.6.2
  @backstage/plugin-user-settings                  0.7.3
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.1
  @backstage/theme                                 0.4.0-next.0, 0.2.19, 0.3.0
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
What's the URL it tries to go to? Does that look distinctly wrong to you?

For that link to work, the entity needs to have a `dynatrace.com/dynatrace-entity-id` annotation set. It then goes to a URL formed like this https://github.com/backstage/backstage/blob/dd739c26d754d42da236d5ea4aaa0f9946ad85fa/plugins/dynatrace/src/components/Problems/ProblemsList/ProblemsList.tsx#L68

**Comment by Zaperex** [comment]
The URL that is formed is `https://vrl18709.live.dynatrace.com/#serviceOverview;id=SYNTHETIC_TEST-00ACC8F1F7995D88` and it tries to go to `https://vrl18709.live.dynatrace.com/#serviceOverview;id=SYNTHETIC_TEST-00ACC8F1F7995D88;gtf=-2h;gf=all`. However, I noticed that there appears to no longer be a serviceOverview section in the dynatrace website which is why it's returning a 404 page instead.

**Comment by freben** [comment]
Alright, tagging this as help wanted so that someone with dynatrace access (you? 🙏) can contribute a better page to link to, or remove the feature if it no longer makes sense.

**Comment by Zaperex** [comment]
So it appears that there is no longer a one-size fit all link, with each entityType having different links.
Currently I have identified some links that appear to work for certain entityTypes:

- Web Applications (`APPLICATION`)
`${dynatraceBaseUrl}/#uemapplications/uemappmetrics;uemapplicationId=${dynatraceEntityId}`
- Mobile Applications (`MOBILE_APPLICATION`) (note: this is taken from their example mobile app entity, so this format might not be correct)
`${dynatraceBaseUrl}/#mobileappoverview;appID=${dynatraceEntityId}`
- Services (`SERVICE`)
`${dynatraceBaseUrl}/#services/serviceOverview;id=${dynatraceEntityId}`
- Hosts (`HOST`)
`${dynatraceBaseUrl}/ui/entity/{dynatraceEntityId}`
- Synthetic Tests (`SYNTHETIC_TESTS`)
`${dynatraceBaseUrl}/ui/browser-monitor/${dynatraceEntityId}`

Unfortunately, I currently don't have instances setup to test the other entityTypes so it would be appreciated if someone can help identify links that work for the other entityTypes.

**Comment by Zaperex** [comment]
So currently, the `DynatraceTab` renders the `ProblemsList` for the entities and the `SyntheticsCard` for the synthetics. The `ProblemsList` only displays the "Problems" of the dynatrace entity. However, I noticed that not all the dynatrace entities  have a dedicated problems list section in the corresponding entry overview on the dynatrace website. 

As I will no longer have access to the dynatrace free trial soon, I was thinking of restricting the supported entityTypes for the `ProblemsList` to only those with a "Problems" section in the dynatrace website for now. I will update the documentation to reflect on this change. 

This can later be extended to the other entityTypes when needed.

**Comment by Zaperex** [comment]
UPDATE: There appears to be a new "universal" prefix for the link `ui/entity/` that seems to work for all the entityTypes I have access to. However, the website page it sends you to look worse than the ones specifically made for the entity, so I will continue using the identified links above, and place `ui/entity/` as a default case.
