### ISSUE TITLE
💬 RFC: User online status on avatars

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#18321]
### 🔖 Need

I truly believe in backstage's ability to be an operations tool. Its ability to show users / groups that own software components means that during an incident triage, the right people can be reached out to by a triage commander.

There are already integrations into backstage that allow you to page a team's on-call rotation through various paging systems, however for certain situations a paging system may be inappropriate to use or unavailable in certain companies, and it would be better to just chat with a team member in whatever enterprise chat app which is being used by your company.

This proposal will allow for tightly integrating the online presence status of a user in their chat app into backstage avatars. The benefit of this means that by looking at an ownership group in backstage, you will be able to quickly know which of the team members are currently online and can be reached out to in your chat app without needing to open up a bunch of chat windows.

This is a critical flow for incident triage, where every second counts when it comes to trying to find a person to reach out to. Furthermore, if the ownership group in backstage for a component does not map directly to a channel or otherwise existing group in your chat app, it can take quite some time cycling through chat windows to try to find who on a team is actually online.

### 🎉 Proposal

My company uses Microsoft Teams, so I am going to focus on this approach, but in theory there can be a base integration layer built out that allows integrating online presence data from other chat apps like slack or other chat apps in the future.

## Bulk Fetching User Presence
In Microsoft's case, we will utilize the Microsoft Graph API to fetch online presence info for multiple users at a time. 

[GetPresencesbyUserId](https://learn.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&tabs=http)
**OAuth Permission Required**: Presence.Read.All
```
POST /communications/getPresencesByUserId
```

## Retaining the Microsoft UserID

This would require on each screen in backstage UI to have available the Microsoft UserID for the user entity in backstage. There are two approaches that can be done here for retrieving that UserID

### Option 1

Fetch the UserIDs from Microsoft Graph API using the email address of the user in backstage straight from the frontend using the Azure login token (requires using Microsoft as a sign-in provider).

[ListUsers](https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http) 
**OAuth Permission Required**: User.ReadBasic.All

```
GET /users?$select=mail, id&$filter=mail in ('user1@company.com', 'user2@company.com', 'user3@company.com')
```
- Pros: Allows users entities in backstage to be provided by other User providers which may not know the Microsoft UserID. If alternate user providers exist, it is still likely that the email of the user is available
- Pros: Makes use of existing frontend 3-legged auth credentials provided by microsoft auth provider.
- Cons: Extra fetch in the frontend to convert email to UserID

### Option 2

While adding users to backstage from whichever provider, ensure the microsoft UserID is added to the User entity using a well known annotation, for example the 'graph.microsoft.com/user-id' annotation, [as listed here](https://github.com/backstage/backstage/blob/127048f92be4611747a6ac83a46dc7bcd8af0d2e/plugins/catalog-backend-extension-msgraph/src/microsoftGraph/constants.ts#L32).

If users are provided from a different provider that isn't Microsoft, then a secondary processor pass could be made that appends this annotation to the user entity.

This would use the same API request as in option 1, but it would be done during entity processing using backend service-to-service Microsoft credentials rather than 3-legged user based OAuth credentials.

- Pros: No need for additional userID conversion fetches on the frontend, as long as the full entity of the Users is available on the frontend then the annotation can be read
- Cons: A more complicated setup / configuration. This makes use of both user based Microsoft credentials and service-to-service backend credentials during processing.

## Auth Details

This would rely on using [Microsoft Auth Provider](https://backstage.io/docs/auth/microsoft/provider). By default, it only selects the User.Read permission, but depending on which APIs above we use, we will need to modify this sign-in flow to request more scopes ( User.ReadBasic.All and Presence.Read.All )

For companies that have multiple identity providers configured and sign-in may not be delegated to Microsoft, they may need some sort of nudge to get people to sign in with microsoft as well as the primary sign-in provider. Has this been discussed before? As far as I know, the only way to know to do this is to go to the user settings page in backstage and realize you aren't signed in to other configured providers.

## UI Presentation

Since we use Material UI for avatars in backstage, there seems to already be support for adding online presence badges to an avatar. Refer to [Avatar with Badge](https://v4.mui.com/components/avatars/#with-badge).

## UI Caching / Refresh

There should be some cache store in the frontend that controls refresh of user-presence data such that data doesn't have to constantly be re-fetched from the presence API on every group page viewed.

Some sort of global time based cache with a TTL at around 1 minute seems like it would be sufficient.

### ❌ Risks

Integrating this with other chat apps may not be as straight-forward as Microsoft teams. It is convenient that microsoft is a sign-in provider already which allows for requesting user-based permissions for fetching presence details

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by freben** [comment]
This sounds nice, but probably a step too far for something to build into "the core" so to speak at this point. It'll be pretty involved, with the frontend APIs and most likely backend backing APIs too depending on how it gets built, and then making use of those in relevant places throughout where user avatars are rendered.

I started work on #17474 some time ago to look into the possibility to control how you render entity information in general - just as a hack, not sure it'll ever be accepted and merged. Anyway, it's meant to let you dynamically plug more info into the core entity presentation layer, without changing the core itself. Maybe there's a future where that PR lands making this possible to build as an auxiliary thing instead of into the core.

If you were to want to build something like this as you suggested without the presentation API , I think it would fit best as separate packages like `plugin-presence`, `plugin-presence-react`, and `plugin-presence-backend` rather than in the core. Possibly even outside the main repo, but in either case something that can be imported at will.
