### ISSUE TITLE
🚀 Feature: ADR Plugin - Serve relatively linked Content through ADR backend Plugin

### ISSUE THREAD

**Issue by tstollin** [backstage/backstage#18367]
### 🔖 Feature description

It would be great if... 

- ...the ADR backend plugin would serve all relatively linked files contained in the ADRs
- ...all relative links contained in the ADRs are rewritten during rendering in the ADR plugin to use this new route

### 🎤 Context

Currently, all relative links in the plain markdown content of ADRs are rewritten to absolute links before being rendered in the EntityAdrContent. 

This is done by the AdrReader using Decorators: https://github.com/backstage/backstage/blob/master/plugins/adr/src/components/AdrReader/decorators.ts 
The base for this rewrite is the url from the `backstage.io/adr-location` annotation of the entity. 

Hence, all relative links now point to the source location of the ADR, which seems resonable. 

Unfortunately for us, our ADRs are stored in a restricted Azure Storage Account (we implemented a custom integration/UrlReader). 
Thus, the ADR-Plugin backend  may access the markdown files using the integration and serve their content through the ` /file` route (https://github.com/backstage/backstage/blob/master/plugins/adr-backend/src/service/router.ts#L97), but all rewritten links do not work because the user's browser does not have access to the blobs in the Storage Account.

### ✌️ Possible Implementation

There is already a similar implementation for Techdocs in the form of the `/static/docs` route of the techdocs-backend plugin: https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/service/router.ts#L293

The change to the already existing decorators for rewriting the relative links should be minimal.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by kuangp** [comment]
hmm see my comment [here](https://github.com/backstage/backstage/issues/16255#issuecomment-1422828447) for a possible workaround for this (and suggestion for refactoring the decoration mechanism into the backend if you're willing to contribute 😁)

I"m not too sure if the plugin should be responsible (by default) for reading and sourcing all relative content - it brings up the question of how far down the tree of linked content should we crawl? eg. if a linked file also contains relative links to addition files and so on

**Comment by tstollin** [comment]
Hi, 
Thanks for your reply. 
We basically implemented the mentioned workaround (custom plugin routing static content using a custom UrlReader handling the auth). Our problem with this approach are the limited options within the  custom ContentDecorators: we may not use Hooks inside them. Therefore we are not able to get the backend url from the config for the replacement (the url is different for our deployment environments). 

Regarding crawling depth: I don't see a problem: any relative links are either embeds (like images) which are then rendered inside the AdrViewer or are links to files, which would be opened in the browser directly (either as plain text or as a download) and not be rendered inside the AdrReader (just as it is the case with the Techdocs). Hence, there would be no need for crawling depth beyond directly linked files.

**Comment by kuangp** [comment]
> Therefore we are not able to get the backend url from the config for the replacement (the url is different for our deployment environments).

Would it be possible to rewrite these as relative links? 
For example if you have a link like: `[link](https://azure.com/some-file)` you can rewrite this using a ContentDecorator to something like `[link](/api/adr/customStaticFileEndpoint)` and it should route to the same backend of the current frontend deployment env or is your front and backend deployed separately?
