### ISSUE TITLE
🚀 Feature: `plugin-app-backend` renders `index.html` with runtime configuration

### ISSUE THREAD

**Issue by zhammer** [backstage/backstage#18378]
### 🔖 Feature description

As a developer who maintains and hosts a Backstage instance
When I deploy the Backstage app via `plugin-app-backend`
I want to see an `index.html` that reflects my deployed backend's Backstage configuration

### 🎤 Context

Given I have the following two configuration files, `app-config.yml` and `app-config.production.yml`
```yml
# app-config.yml
app:
  baseUrl: http://127.0.0.1:3000
```
```yml
# app-config.production.yml
app:
  baseUrl: https://backstage.example.com
```
And I build my Backstage docker container in CI using `--config app-config.yaml`
When I deploy my Backstage instance to production using `plugin-app-backend` with the configuration `--config app-config.yaml --config app-config.production.yaml` 
Then frontend and backend plugins reading `app.baseUrl` will see "https://backstage.example.com" ([docs](https://backstage.io/docs/conf/reading#accessing-configapi-in-frontend-plugins))

**However, this is not the case for the `index.html` file.** The `index.html`, it seems, is only rendered at build time using build time configuration. This causes issues for anything that depends on config-based `index.html` rendering, like the [datadog RUM installation](https://backstage.io/docs/integrations/datadog-rum/installation/).

We can work around this for now, but wanted to raise as a feature request as we've seen [other developers with the same issue](https://discord.com/channels/687207715902193673/1107687002079502416/1113897761675411467). At the least there could  be more documentation about how & when the `index.html` is rendered.

### ✌️ Possible Implementation

A naïve approach would just be to re-render the `index.html` via the `plugin-app-backend` at some point in the app's lifecycle (on load? on first request?).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
I think this is worth investigating! Moving this along I think it's worth a bit more detailed plan for how it would work and how users would interact with this capability. Could be a minimal PR, but I think it's perhaps best to outline the idea here instead.

**Comment by zhammer** [comment]
ah so i poked around a bit at how app-backend does the config injection for the js bundle and then went looking for how the `index.html` templating works... struggling to find anything beside this note from you on discord from early 2022. curious about where in the webpack config this happens.

![screenshot from discord chat](https://github.com/backstage/backstage/assets/6956487/95ad2442-81e2-4beb-b1ed-7bd257a5017b)

**Comment by zhammer** [comment]
is this it? https://github.com/backstage/backstage/blob/b5344d21db5ec259a1a13982afeca69e767cb0f5/packages/cli/src/lib/bundler/config.ts#L126-L134

**Comment by zhammer** [comment]
from a quick look at [the docs](https://webpack.js.org/plugins/html-webpack-plugin/) it seems that html webpack plugin is using [lodash .template](https://lodash.com/docs/4.17.15#template) under the hood which i imagine wouldn't be too hard to replicate in app-backend. will dig a bit deeper here but hopefully something like the following should work:

- on build, save a raw version of the source `index.html` called something like `.index.template.html` (similar to existing `.config.schema.json`).
- in app-backend `createRouter`, [when we inject our config into the js bundle](https://github.com/backstage/backstage/blob/b5344d21db5ec259a1a13982afeca69e767cb0f5/plugins/app-backend/src/service/router.ts#L117), also run lodash template on `.index.template.html`, overwriting existing `index.html` 

as long as lodash templating works independent of the webpack plugin, i don't *see* any issues here. anything stand out to you?
