### ISSUE TITLE
🐛 Bug Report: createTheme and createUnifiedTheme do not support all custom theme properties

### ISSUE THREAD

**Issue by cchawn** [backstage/backstage#18398]
### 📜 Description

Previously, when creating a custom theme as described in the [documentation here](https://backstage.io/docs/getting-started/app-custom-theme/#creating-a-custom-theme), you could pass in custom palette values for the `navigation` (amongst other things). But now the accepted type has been changed from `SimpleV4ThemeOptions` to `SimpleThemeOptions` — which has dropped support for many `palette` fields.

**Previously:**

https://github.com/backstage/backstage/blob/1b7f1124524622933ed7307cf024bc4c0a5c823b/packages/theme/src/v4/types.ts#L82-L88

**Currently:**

https://github.com/backstage/backstage/blob/24e91ed76dbac2f19f2d704dd94a2f5c984c41c4/packages/theme/src/v4/types.ts#L86-L92

I saw this related issue: https://github.com/backstage/backstage/issues/16631

### 👍 Expected behavior

I should be able to override all properties (including custom ones!) of the default Backstage theme.

### 👎 Actual Behavior with Screenshots

I get a type error when creating the following custom theme (but the `navigation` styles are still applied correctly):

```tsx
export const customLightTheme = createTheme({
  palette: {
    ...lightTheme.palette,
    type: 'light',
    background: { // this is fine
      paper: '#FFFFFF',
      default: '#FAFAFA',
    },
  	navigation: { // Object literal may only specify known properties, and 'navigation' does not exist in type 'PaletteOptions'.ts(2322)
      background: '#FAFAFA',
      indicator: '#FFFFF',
      color: '#666666',
      selectedColor: '#000000',
      navItem: {
        hoverBackground: '#FFFFFF',
      },
      submenu: {
        background: '#FAFAFA',
      },
    },
});

// type error womp womp
```

![image](https://github.com/backstage/backstage/assets/6462356/735cc45d-9c27-46a5-a76e-2d1bb60b522c)

To resolve the type error, I can remove the `navigation` block, but as far as I can tell, there is no other way to override the theme values for `navigation` (etc.).

```tsx
export const customLightTheme = createTheme({
  palette: {
    ...lightTheme.palette,
    type: 'light',
    background: { // this is fine
      paper: '#FFFFFF',
      default: '#FAFAFA',
    },
  	// removed 'navigation' block
});
```

![image](https://github.com/backstage/backstage/assets/6462356/5700a7d6-b889-4041-920c-af937aed52c7)

In the above screenshot, you can see that we are falling back to the default Backstage colour palette defined here:

https://github.com/backstage/backstage/blob/24e91ed76dbac2f19f2d704dd94a2f5c984c41c4/packages/core-components/src/layout/Sidebar/Bar.tsx#L52

https://github.com/backstage/backstage/blob/24e91ed76dbac2f19f2d704dd94a2f5c984c41c4/packages/theme/src/base/palettes.ts#L73-L92

It also seems like the `createCustomOverrides` method for a theme, and even the `BackstageTheme` itself are deprecated — so those are probably not what I should be using?

### 👟 Reproduction steps

1. Create a custom theme

```tsx
export const customLightTheme = createTheme({
  palette: {
    ...lightTheme.palette,
    type: 'light',
    background: { // this is fine
      paper: '#FFFFFF',
      default: '#FAFAFA',
    },
  	navigation: {
      background: '#FAFAFA',
      indicator: '#FFFFF',
      color: '#666666',
      selectedColor: '#000000',
      navItem: {
        hoverBackground: '#FFFFFF',
      },
      submenu: {
        background: '#FAFAFA',
      },
    },
});
```

2. Attempt to use said theme in your app to change the look and feel of the navigation sidebar, encounter a type error ☹️ 

### 📃 Provide the context for the Bug.

Due to this change, I have to coerce the type (gross) or give up on our organization's custom theming for our instance of Backstage.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by zjpersc** [comment]
I am experiencing the same issue currently.

**Comment by awanlin** [comment]
Hi @cchawn and @zjpersc, so there's an solution to this but will mention if you have overrides I haven't figured that out yet. Can you try this?

```tsx
const theme = createUnifiedTheme({
  ...createBaseThemeOptions({
    palette: {
      ...palettes.light,
      primary: {
        main: '#008489',
      },
      secondary: {
        main: '#FF385C',
      },
      status: {
        ok: '#008A05',
        warning: '#E07912',
        error: '#C13515',
        running: '#428BFF',
        pending: '#FFED51',
        aborted: '#757575',
      },
      navigation: {
        color: '#d5d6db',
        selectedColor: '#ffffff',
      },
    },
  }),
  defaultPageTheme: 'home',
  fontFamily: "'IBM Plex Sans', Roboto, Arial, sans-serif",
  /* below drives the header colors */
  pageTheme: {
    home: genPageTheme({
      colors: ['#d5d6db', '#d5d6db'],
      shape: shapes.customSquare,
    }),
  }
});
```

This is purely an example and is not complete but just to show you the shape needed, it should work with all the existing properties except for any overrides

Please feel free to join/read this Discord thread: https://discord.com/channels/687207715902193673/1121117177328709673

**Comment by awanlin** [comment]
Sorry, missed this in my rush to reply but I'm assuming you have upgraded to the latest version which is 1.15.0 and followed this from the release notes: https://backstage.io/docs/releases/v1.15.0#more-movement-toward-material-ui-v5-and-react-v18-compatibility

And this is what you'll want to import: 

```ts
import {
  palettes,
  genPageTheme,
  createUnifiedTheme,
  createBaseThemeOptions,
} from '@backstage/theme';
```

**Comment by cchawn** [comment]
> Sorry, missed this in my rush to reply but I'm assuming you have upgraded to the latest version which is 1.15.0 and followed this from the release notes: [backstage.io/docs/releases/v1.15.0#more-movement-toward-material-ui-v5-and-react-v18-compatibility](https://backstage.io/docs/releases/v1.15.0#more-movement-toward-material-ui-v5-and-react-v18-compatibility)

@awanlin 👍 yes I'm upgrading to 1.15.0 now, and encountered this issue!

>Please feel free to join/read this Discord thread: [discord.com/channels/687207715902193673/1121117177328709673](https://discord.com/channels/687207715902193673/1121117177328709673)

Thanks! I will check this out 👀

**Comment by cchawn** [comment]
> Hi @cchawn and @zjpersc, so there's an solution to this but will mention if you have overrides I haven't figured that out yet. Can you try this?
> 
> ```tsx
> const theme = createUnifiedTheme({
>   ...createBaseThemeOptions({
>     palette: {
>       ...palettes.light,
>       primary: {
>         main: '#008489',
>       },
>       secondary: {
>         main: '#FF385C',
>       },
>       status: {
>         ok: '#008A05',
>         warning: '#E07912',
>         error: '#C13515',
>         running: '#428BFF',
>         pending: '#FFED51',
>         aborted: '#757575',
>       },
>       navigation: {
>         color: '#d5d6db',
>         selectedColor: '#ffffff',
>       },
>     },
>   }),
>   defaultPageTheme: 'home',
>   fontFamily: Roboto, Arial, sans-serif",
>   /* below drives the header colors */
>   pageTheme: {
>     home: genPageTheme({
>       colors: ['#d5d6db', '#d5d6db'],
>       shape: shapes.customSquare,
>     }),
>   }
> });
> ```
> 
> This is purely an example and is not complete but just to show you the shape needed, it should work with all the existing properties except for any overrides
> 
> Please feel free to join/read this Discord thread: [discord.com/channels/687207715902193673/1121117177328709673](https://discord.com/channels/687207715902193673/1121117177328709673)

@awanlin this works! thank you! (I forgot to check Discord for discussion before posting this issue 🙈)

**Comment by awanlin** [comment]
No worries @cchawn, I would not expect you to check Discord first but it does seem like things get reported there first and wanted to give you options if what I shared didn't end up working for you 👍
