### ISSUE TITLE
💬 RFC: Is it possible to use `yarn resolutions` as mechanism to handle backstage package versions?

### ISSUE THREAD

**Issue by x3ro** [backstage/backstage#18404]
### 🔖 Need

I've been working with Backstage for close to a year now, and in that time frame we have gone through a number of updates, which have mostly been quite easy, thank you backstage maintainers 🙏🏼. We had some accidental version divergences, where we referenced a version of a @backstage plugin that's not compatible. This led us to introduce `version:bump` into our CI pipeline in order to make sure that all versions are compatible with the selected backstage version.

On the other hand we also had the need to copy some of the backstage plugins into our own code base, due to mostly minor, sometimes bigger modifications. In this case, we would have to replace the `workspace:^` versions used with the actual versions to be imported, which `version:bump` handles well. However, updating these plugins then becomes a bit of a hassle, because they are not part of the original git tree (`backstage/backstage`) anymore. So it's more difficult than just doing a quick rebase and checking if there are conflicts.

So from our end, we were wondering: "can't we just make a private fork of backstage, make our modifications, and then rebase when we upgrade to a new version?". This seemed easy on the surface, e.g.:

```json
"resolutions": {
    "@backstage/plugin-techdocs": "file:../backstage/plugins/techdocs"
},
```

in our root `package.json`, and we're done. But this does not work, since the plugin we would be referencing has all of those pesky `workspace:^` versions that yarn can't resolve. So then we end up with something like this instead:

```json
"resolutions": {
    "@backstage/catalog-model": "^1.3.0",
    "@backstage/config": "^1.0.7",
    "@backstage/core-components": "^0.13.1",
    "@backstage/core-plugin-api": "^1.5.1",
    "@backstage/errors": "^1.1.5",
    "@backstage/integration": "^1.4.5",
    "@backstage/integration-react": "^1.1.13",
    "@backstage/plugin-catalog-react": "^1.6.0",
    "@backstage/plugin-search-common": "^1.2.3",
    "@backstage/plugin-search-react": "^1.6.0",
    "@backstage/plugin-techdocs-react": "^1.1.6",
    "@backstage/theme": "^0.2.17",
    "@backstage/cli": "^0.22.7",
    "@backstage/core-app-api": "^1.8.0",
    "@backstage/dev-utils": "^1.0.15",
    "@backstage/plugin-techdocs-module-addons-contrib": "^1.0.13",
    "@backstage/test-utils": "^1.3.1",
    "@backstage/plugin-techdocs": "file:../backstage/plugins/techdocs"
  },
```

Not so simple anymore, and then we'd have to maintain these versions by hand whenever we upgrade.

### 🎉 Proposal

Long story short: I was wondering whether it would be possible to do the version resolution for all backstage plugins via yarn resolutions by default. That way, all `plugins/` would continue to reference `workspace:^` or something similar, and `resolutions` would be in charge of resolving that to the correct package version for the current backstage version. All versions could be viewed at a glance in the project root, and it would not be possible anymore to accidentally use two different versions of the same plugin.

An additional benefit would be that we could reference plugins directly from the `backstage` repository. I'm aware that this may not be straight forward, as one then has to make sure that the commit / state one is referencing is actually compatible with the current backstage version. But from a maintenance point of view, I think it would beat how we are handling modifications to `@backstage` plugins at the moment.

Now, this may be a terrible idea for reasons I'm not aware of. And apologies in case I'm duplicating a previous discussion. The closest thing I could find was #13994, which seems related but not the same.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by benjdlambert** [comment]
I'd really like to try and stay away from resolutions if possible, at least by default, as they're a pretty big footgun sometimes with things being resolved in different ways and it add some complexity,

I wonder if there's an alternative solution though, could you not add your fork of backstage plugins to the workspaces directory under the `root` package.json? You it might be that it needs to be under the `root` package.json but then in that case you could probably use a git submodule or something to bring in your fork of plugins.

It's a little clunky and basic but maybe it gets you to the solution you need?

**Comment by x3ro** [comment]
I will give it a try, thanks for the input! Do you have a good resource documenting the caveats of resolutions, by any chance?

**Comment by benjdlambert** [comment]
@x3ro good question - there's a few things at the bottom here: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-limitations-Caveats but mostly this is just from experience of us unfortunately having to ship resolutions from time to time to fix issues with upstream dependencies.
