### ISSUE TITLE
🚀 Feature: Update `BackstageApp.createRoot` to be closer to React's `createRoot`

### ISSUE THREAD

**Issue by schultzp2020** [backstage/backstage#18415]
### 🔖 Feature description

Change `BackstageApp.createRoot()` to return an object that contains a render method like [React's `createRoot()`](https://react.dev/reference/react-dom/client/createRoot#usage). This change would allow multiple calls to the new render method. 

### 🎤 Context

The current implementation of `BackstageApp.createRoot()` does not allow the removal of `BackstageApp.getProvider()` from the source code. This is because `BackstageApp.getProvider()` is called directly inside `BackstageApp.createRoot()`. If `BackstageApp.createRoot()` returned an object with a render method, we could call `BackstageApp.createRoot()` once and the render method multiple times.

This change would enable the removal of the deprecated methods used in `createTestAppWrapper()` in `@backstage/test-utils`.

### ✌️ Possible Implementation

Old way
```tsx
app.createRoot(<Element />)
```

New way with one render
```tsx
app.createRoot().render(<Element />)
```

New way with multiple renders
```tsx
const root = app.createRoot()

root.render(<Element1 />)
root.render(<Element2 />)
root.render(<Element3 />)
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Just wanna point to the discussion at https://github.com/backstage/backstage/pull/18416#discussion_r1272229196 for anyone coming across this issue

**Comment by schultzp2020** [comment]
not stale
