### ISSUE TITLE
🐛 Bug Report: Kubernetes documentation is broken - getting 404

### ISSUE THREAD

**Issue by gowthamshankar99** [backstage/backstage#18421]
### 📜 Description

https://backstage.io/docs/features/kubernetes/overview - getting a 404 when trying to hit the above endpoint 

### 👍 Expected behavior

should be able to reach - https://backstage.io/docs/features/kubernetes/overview 

### 👎 Actual Behavior with Screenshots

NA

### 👟 Reproduction steps

na

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Ah I think we're going to want to add a redirect in the microsite to this page from that URL https://backstage.io/docs/features/kubernetes/

**Comment by gowthamshankar99** [comment]
I would love to contribute. I will work on this now - thanks

**Comment by benjdlambert** [comment]
Closing as this is now fixed :tada:
