### ISSUE TITLE
🚀 Feature: Add support to database connection for object or a function returning an object

### ISSUE THREAD

**Issue by andriyun** [backstage/backstage#18425]
### 🔖 Feature description

The Knex library currently used for database connection supports [different configuration options](https://knexjs.org/guide/#configuration-options) for the connection itself.
> The connection options are passed directly to the appropriate database client to create the connection and may be either an object, a connection string, or a function returning an object

Adding support for these options allow configuring connection with a better level of flexibility and security

### 🎤 Context

In our case, we are using an Azure PostgreSQL Flexible server via  Azure AD authentification. Accordingly, with documentation, we need to use an access token, acquired for each connection session. So the connection snippet in `app-config.yaml` needs to be adjusted so that we can provide an access token as a password later in a runtime.
Possible usage after added support of using function/object support:
```
...
database:
  client: postgres
  connection: !!js/function |
    async () => {
      const { 
        token, 
        tokenExpiration 
      } = await someCallToGetTheToken();
      return {
        host : 'ph_host',
        port : 5432,
        user : 'pg_admin',
        password : token,
        expirationChecker: () => {
          return tokenExpiration <= Date.now();
        }
      };
    }
...
```
Additional libraries needed `js-yaml`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey :wave: thanks for this idea!

I wonder if you had seen https://github.com/backstage/backstage/issues/7466, as this probably has an approach that we want to implement along with the config subscribing function mentioned in some of the comments there.

I don't think that adding js to yaml is going to be a path we want to explore too much, theres a lot of security and other implications that come with that unfortunately.

I think what we want to be able to do is be able pass a `getConnection` method or something to the `PluginDatabaseManager` that will be able to re-evaluate the connection string. That coupled with the config automatically re-loading when there's new credentials saved should be a complete solution, and I think that config subscriptions are a work in progress #18358 right now.

**Comment by andriyun** [comment]
Hey @benjdlambert 
I implemented changes related to the issue and added them as draft-PR. Part of the changes was inspired by PR #18358.

I would be appreciated for feedback and ideas for making PR changes more generic. So it will cover different auth providers and db drivers.
