### ISSUE TITLE
🐛 Bug Report: Post unregistering an entity, user gets redirected to "/" instead of "/catalog"

### ISSUE THREAD

**Issue by jenil-harness** [backstage/backstage#18436]
### 📜 Description

Post unregistering an entity, user gets redirected to "/" instead of "/catalog"

### 👍 Expected behavior

It should get redirected to "/catalog"

### 👎 Actual Behavior with Screenshots

Post unregistering it got redirected to default route "/".

### 👟 Reproduction steps

1. Go To the Catalog Page.
2. Go to entity details Page.
3. Unregister the entity.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by aakankshabhende** [comment]
@benjdlambert @jenil-harness  I would like to work on this issue. Could you please assign me this?

**Comment by benjdlambert** [comment]
Done! Thanks for picking this up! :tada:

**Comment by AmbrishRamachandiran** [comment]
@aakankshabhende are you working on this ? is the issue got fixed?

**Comment by aakankshabhende** [comment]
Yes I'm working on it

**Comment by benjdlambert** [comment]
Going to re-open this as theres work currently in progress :tada:
