### ISSUE TITLE
🐛 Bug Report: MUI 5 Paper shading in dark theme is inconsistent with MUI 4

### ISSUE THREAD

**Issue by TarasZubreiFiverr** [backstage/backstage#18430]
### 📜 Description

I started migration to MUI 5 in my company and faced a few issues, specifically inconsistent Paper-based components shading in dark theme. It's better illustrated in EntityPage where I have custom AboutCard that I migrated to MUI 5 `<Card/>` and a bunch of `<InfoCard/>` components from backstage-core that still use MUI 4 under the hood.

![image](https://github.com/backstage/backstage/assets/76960985/99e7ee3f-6e81-48f0-94c3-f5db342c07e2)

Exploring styles in Chrome Dev tools I found that this comes from extra `background-image` css prop:

<img width="1511" alt="image" src="https://github.com/backstage/backstage/assets/76960985/c32f7abf-62f0-47f0-b800-25bdfa4ae204">

Furthermore, [official MUI docs](https://mui.com/material-ui/react-paper/#elevation) mention this as well:
> The change of shade in dark mode is done by applying a semi-transparent gradient to the `background-image` property. This can lead to confusion when overriding the styles of `Paper`, as setting just the `background-color` property will not affect the elevation-related shading. To ignore the shading and set the background color that is not affected by elevation in dark mode, override the `background` property (or both `background-color` and `background-image`).

Since Paper is a very common base for a lot of components, I see this shading in different pages, though EntityPage overview  catches the eye the most since I have MUI 4 and 5 components on the same page.

### 👍 Expected behavior

We should have a consistent shading between core components and MUI 5 ones. I am not sure in which direction should we lean, maybe it's easier to add an override to conform to MUI 4 styling

### 👎 Actual Behavior with Screenshots

Right now MUI 5 Paper-based components are slightly brighter than their MUI 4 counterparts. This becomes harder since I am not using MUI 4 directly, but they come from `backstage-core` wrapper components instead.

### 👟 Reproduction steps

1. Create an MUI 5 card component (`import { Card } from '@mui/material';`) and backstage-core InfoCard (`import { InfoCard } from '@backstage/core-components';`)
2. Select dark theme

### 📃 Provide the context for the Bug.

We forked AboutCard components to change some layout and add extra links. Therefore, during MUI 5 migration we migrated Card component used under the hood. We don't have any custom themes, styling overrides, etc.

### 🖥️ Your Environment

```
OS:   Darwin 22.3.0 - darwin/arm64
node: v18.16.0
yarn: 3.6.0
cli:  0.22.8 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                               1.4.0
  @backstage/backend-app-api                            0.4.4
  @backstage/backend-common                             0.19.0
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.3
  @backstage/backend-tasks                              0.5.3
  @backstage/catalog-client                             1.4.2
  @backstage/catalog-model                              1.4.0
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.1
  @backstage/cli                                        0.22.8
  @backstage/config-loader                              1.3.1
  @backstage/config                                     1.0.8
  @backstage/core-app-api                               1.8.1
  @backstage/core-components                            0.12.5, 0.13.2
  @backstage/core-plugin-api                            1.5.2
  @backstage/dev-utils                                  1.0.16
  @backstage/errors                                     1.2.0
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.4
  @backstage/integration-react                          1.1.14
  @backstage/integration                                1.5.0
  @backstage/plugin-api-docs                            0.9.5
  @backstage/plugin-app-backend                         0.3.46
  @backstage/plugin-auth-backend                        0.18.4
  @backstage/plugin-auth-node                           0.2.15
  @backstage/plugin-catalog-backend-module-github       0.3.1
  @backstage/plugin-catalog-backend-module-unprocessed  0.1.0
  @backstage/plugin-catalog-backend                     1.10.0
  @backstage/plugin-catalog-common                      1.0.14
  @backstage/plugin-catalog-graph                       0.2.31
  @backstage/plugin-catalog-import                      0.9.9
  @backstage/plugin-catalog-node                        1.3.7
  @backstage/plugin-catalog-react                       1.7.0
  @backstage/plugin-catalog-unprocessed-entities        0.1.0
  @backstage/plugin-catalog                             1.11.2
  @backstage/plugin-circleci                            0.3.19
  @backstage/plugin-code-coverage-backend               0.2.12
  @backstage/plugin-code-coverage                       0.2.12
  @backstage/plugin-events-node                         0.2.7
  @backstage/plugin-github-actions                      0.6.0
  @backstage/plugin-github-pull-requests-board          0.1.13
  @backstage/plugin-home-react                          0.1.0
  @backstage/plugin-home                                0.5.3
  @backstage/plugin-org                                 0.6.9
  @backstage/plugin-permission-common                   0.7.6
  @backstage/plugin-permission-node                     0.7.9
  @backstage/plugin-permission-react                    0.4.13
  @backstage/plugin-proxy-backend                       0.2.40
  @backstage/plugin-scaffolder-common                   1.3.1
  @backstage/plugin-search-backend-module-catalog       0.1.2
  @backstage/plugin-search-backend-module-pg            0.5.7
  @backstage/plugin-search-backend-module-techdocs      0.1.2
  @backstage/plugin-search-backend-node                 1.2.2
  @backstage/plugin-search-backend                      1.3.2
  @backstage/plugin-search-common                       1.2.4
  @backstage/plugin-search-react                        1.6.2
  @backstage/plugin-search                              1.3.2
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.30
  @backstage/plugin-tech-insights-backend               0.5.12
  @backstage/plugin-tech-insights-common                0.2.11
  @backstage/plugin-tech-insights-node                  0.4.4
  @backstage/plugin-tech-radar                          0.6.5
  @backstage/plugin-techdocs-backend                    1.6.3
  @backstage/plugin-techdocs-module-addons-contrib      1.0.14
  @backstage/plugin-techdocs-node                       1.7.2
  @backstage/plugin-techdocs-react                      1.1.7
  @backstage/plugin-techdocs                            1.6.4
  @backstage/plugin-todo-backend                        0.1.43
  @backstage/plugin-todo                                0.2.21
  @backstage/plugin-user-settings                       0.7.4
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.4.0
  @backstage/theme                                      0.2.19, 0.4.0
  @backstage/types                                      1.1.0
  @backstage/version-bridge                             1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by webark** [comment]
@TarasZubreiFiverr did you ever find a workaround for this?

**Comment by webark** [comment]
I ended up just doing an elevation of zero for those.

**Comment by tudi2d** [comment]
Happy to pick this up & will look into this. Also just a heads-up that I tried covering the migration in this doc: https://backstage.io/docs/tutorials/migrate-to-mui5. As booth of you have exerienced with it I would highly appreciate any feedback!:)
