### ISSUE TITLE
🚀 Feature: Allow adding custom actions without the need to edit scaffolder.ts

### ISSUE THREAD

**Issue by antweiss** [backstage/backstage#18431]
### 🔖 Feature description

Allow adding custom actions without the need to edit https://github.com/backstage/backstage/blob/3f304f6211620ed9386d905c53822d46e574a48f/packages/create-app/templates/default-app/packages/backend/src/plugins/scaffolder.ts

Custom actions should be able to call into scaffolder in order to instantiate themselves not the other way around.

### 🎤 Context

Currently in order to add custom actions to one's Backstage instance it's necessary to:

-  import the actions in `packages/backend/src/plugins/scaffolder.ts` 
- create the builtin actions in `packages/backend/src/plugins/scaffolder.ts` 
- append the custom actions to the builtin actions array 
- pass the resulting array of actions into the scaffloder `createRouter` function

Actions addition shouldn't require making changes to the default app code.

### ✌️ Possible Implementation

this may be a naive approach - happy to hear what I got wrong

- Add a new input parameter to the scaffolder's `createRouter` function called `customActions` - empty by default.
- Add a `customActions` module  in `https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/src/scaffolder/actions` which would export `createCustomActions` , `appendCustomActions`  and `getCustomActions` for custom actions implementers to call
- Always call both `createBuiltinActions` and `getCustomActions` (empty array by default) in https://github.com/backstage/backstage/blob/3f304f6211620ed9386d905c53822d46e574a48f/packages/create-app/templates/default-app/packages/backend/src/plugins/scaffolder.ts#L4 
- At https://github.com/backstage/backstage/blob/3f304f6211620ed9386d905c53822d46e574a48f/plugins/scaffolder-backend/src/service/router.ts#L293 - no need to call `createBuiltinActions`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by taras** [comment]
Thank you for making this suggestion. 

Can you provide a code example of what it would look like to register an action with your suggestion?

It could also help to explain the proposal with words without referencing code.

**Comment by benjdlambert** [comment]
I think that a lot of this becomes simpler with the new backend system. Adding actions are going to be as easy as adding one line of `backend.add(myScaffolderActionsModule())` which should just get autowired together. 

I wonder if we should be focusing our efforts on making these modules easier to create for addition to the new [backend system](https://backstage.io/docs/backend-system/architecture/index)

**Comment by antweiss** [comment]
Thanks a lot @benjdlambert ! Definitely looks like I need to dive into the new backend system first.
Is there a branch where one can try it too?

**Comment by taras** [comment]
I was going to suggest the same, but I wasn't sure if this was precisely what @antweiss meant that's why I asked for clarification.

**Comment by benjdlambert** [comment]
@antweiss so you can actually migrating things to the new backend system today, but it's not something we've come out and said that we recommend people do yet - that should come in the next few weeks when the other maintainers are back from their holidays.

If you look in the [backend-next](https://github.com/backstage/backstage/tree/master/packages/backend-next) folder in the main repo, you can see what it looks like to setup something similar to what you might have locally using the new backend system.

Like I said we're hoping to roll this out and make it the default for new `create-apps` over the coming months, see #18394 which was a bit too early to move everything over just yet.

**Comment by antweiss** [comment]
Thanks @benjdlambert will check it out. Hope to become an early adopter ;)

**Comment by Rugvip** [comment]
Closing as this is now implemented through the actions extension point for the new backend system: https://github.com/backstage/backstage/blob/ae4b12b42b37730dd94300b4d0bf07663c257668/plugins/scaffolder-node/src/alpha.ts#L25-L42
