### ISSUE TITLE
🐛 Bug Report: Direct relations flag doesn't work on User page

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#18455]
### 📜 Description

The "direct relations" / "aggregated relations" button in the Org plugin only works on groups, but not on users.

The button maybe seems disabled, but if it's not possible on this page, it should likely be hidden.

### 👍 Expected behavior

If I own one entity myself, and my team might own three. I'd expect to view my name, and see I own one DIRECT relationship. And if I click aggregated, I should see four.

### 👎 Actual Behavior with Screenshots

https://github.com/backstage/backstage/assets/33203301/a92ff83b-68c2-4cb3-98b0-ceca665c9b64

### 👟 Reproduction steps

1. Visit the demo site
2. Visit the Team C page; button works
3. Visit the page for the first user in the team Callum Leavy's page, button is not clickable, no hover, no feedback.

### 🖥️ Your Environment

Backstage's live demo environment: https://demo.backstage.io

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by npiyush97** [comment]
button is disabled because user != group 
https://github.com/backstage/backstage/blob/02f9d469d0075b182cdf79dd51fb525993369d0e/plugins/org/src/components/Cards/OwnershipCard/OwnershipCard.tsx#L105

**Comment by callebstrom** [comment]
Hey,

I'll take a look at this. There does indeed seem to be some implicit behaviour related to the direct relationships of these leaf nodes not aligning with expectations.

**Comment by benjdlambert** [comment]
Assigned! Feeling that it might be more useful just to hide the toggles if it's not going to be possible to work for those types - save's confusing other people I'm feeling.

**Comment by callebstrom** [comment]
It seems to me that this toggle is not really intended to be used on leaf nodes (such as user) as there is nothing to aggregate (hence the `disabled` state), and considering this I do agree with the conclusion to hide it however, this does contradict the "direct relations" at the moment as for `User` entities we show the parent groups ownership.

As I see it we have a couple of options:
1. Hide toggle and only display direct relationships (and not parent group owned)
2. Keep toggle but change the semantics when used on leaf nodes (such as user), and have it aggregate upwards instead (same behaviour as now but also allowing for only showing direct relationships)

Any takes on either of these approaches?

**Comment by callebstrom** [comment]
To be a bit more concrete, I am thinking something along the lines of https://github.com/backstage/backstage/pull/18540

**Comment by awanlin** [comment]
Just some feedback: we would not like to see a toggle in the UI and we also aren't interested in this functionality. Whatever direction you take we would like for it to be opt in and not suddenly start showing up, please 👍

**Comment by callebstrom** [comment]
@awanlin Thanks for the input! I think it makes perfect sense for this to be opt-in provided we can agree on a sane default for the ownership card itself. With that said, would you mind describing this opt-in feature as a new issue as my PR merely tackles the confusion behind the toggle and does not alter how or when it is presented in the UI.

**Comment by adamdmharvey** [comment]
(sorry, had a bit of summer holiday and just looping back to this)

I'm all for erring on the side of simplicity here, and therefore removing the direct relationship toggle altogether. 👍🏻 

From a user understanding perspective, I have had some folks ask me why it says they own something when they didn't think they did? This usually stemmed from them being in a group that maybe they shouldn't have been, or they didn't know they had been put in the group. (e.g., my director was surprised she owned anything, and i noted that's because she had been put in a few info only groups which ALSO happened to be marked as owners of entities)

I wonder if on the user page, this card might have a subtitle to say "Includes entities owned by this user or groups his user is a member of" or "Includes all entities owned by groups this user is in" or something. (maybe those aren't the best) But somehow explaining that Backstage has identified the aggregated ownership?
