### ISSUE TITLE
🐛 Bug Report: Postgres Database config check failing with host, port and user parameters in connection string

### ISSUE THREAD

**Issue by tcnaganath** [backstage/backstage#18450]
### 📜 Description

Below configuration in `app-config.production.yaml` was working with `backstage-v1.14.0` but it is not working with `backstage-v1.15.0` when we validate the config using the command `yarn backstage-cli config:check --config app-config.yaml --config app-config.production.yaml --lax --strict`. Due to this issue, we are forced to remove `--strict` in order to proceed with `backstage-v1.15.0`.

```
database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
```

I noticed that `packages/backend-common/config.d.ts` got the below changes in the below link, with v1.0.14 connection strings was host, port, user and password and now with v1.0.15 it has been changed to password and key string unknown;

https://github.com/backstage/backstage/commit/447270a7d9083fdd7fd8a76c002ff945544c9be2

### 👍 Expected behavior

Config check command should not fail with strict `yarn backstage-cli config:check --config app-config.yaml --config app-config.production.yaml --lax --strict` against the database section which is correct.

### 👎 Actual Behavior with Screenshots

Config check command is currently failing with strict `yarn backstage-cli config:check --config app-config.yaml --config app-config.production.yaml --lax --strict`

```
yarn backstage-cli config:check --config app-config.yaml --config app-config.production.yaml --lax --strict
yarn run v1.22.19
config:check --config app-config.yaml --config app-config.production.yaml --lax --strict
Loaded config from app-config.yaml, app-config.production.yaml

Error: Configuration does not match schema

  Config must NOT have additional properties { additionalProperty=host } at /backend/database/connection
  Config must NOT have additional properties { additionalProperty=port } at /backend/database/connection
  Config must NOT have additional properties { additionalProperty=user } at /backend/database/connection
  Config must be string { type=string } at /backend/database/connection
  Config must match a schema in anyOf {  } at /backend/database/connection

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### 👟 Reproduction steps

Please execute the below command at the root directory of the backstage v1.0.15 tag version

`yarn backstage-cli config:check --config app-config.yaml --config app-config.production.yaml --lax --strict`

app-config.production.yaml should have this configuration for postgres:

```
database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
```

### 📃 Provide the context for the Bug.

I noticed that `packages/backend-common/config.d.ts` got the below changes in the below link, with v1.0.14 connection strings was host, port, user and password and now with v1.0.15 it has been changed to password and key string unknown;

https://github.com/backstage/backstage/commit/447270a7d9083fdd7fd8a76c002ff945544c9be2

_No response_

### 🖥️ Your Environment

```
OS:   Darwin 22.5.0 - darwin/arm64
node: v18.0.0
yarn: 1.22.19
cli:  0.22.8 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                          1.4.0
  @backstage/backend-app-api                       0.4.4
  @backstage/backend-common                        0.19.0
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.3
  @backstage/backend-tasks                         0.5.3
  @backstage/catalog-client                        1.4.2
  @backstage/catalog-model                         1.4.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.1
  @backstage/cli                                   0.22.8
  @backstage/config-loader                         1.3.1
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.8.1
  @backstage/core-components                       0.13.2
  @backstage/core-plugin-api                       1.5.2
  @backstage/errors                                1.2.0
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.4
  @backstage/integration-react                     1.1.14
  @backstage/integration                           1.5.0
  @backstage/plugin-api-docs                       0.9.5
  @backstage/plugin-app-backend                    0.3.46
  @backstage/plugin-auth-backend                   0.18.4
  @backstage/plugin-auth-node                      0.2.15
  @backstage/plugin-catalog-backend-module-github  0.3.1
  @backstage/plugin-catalog-backend                1.10.0
  @backstage/plugin-catalog-common                 1.0.14
  @backstage/plugin-catalog-graph                  0.2.31
  @backstage/plugin-catalog-import                 0.9.9
  @backstage/plugin-catalog-node                   1.3.7
  @backstage/plugin-catalog-react                  1.7.0
  @backstage/plugin-catalog                        1.11.2
  @backstage/plugin-circleci                       0.3.19
  @backstage/plugin-devtools-backend               0.1.1
  @backstage/plugin-devtools-common                0.1.1
  @backstage/plugin-devtools                       0.1.1
  @backstage/plugin-events-node                    0.2.7
  @backstage/plugin-explore-backend                0.0.8
  @backstage/plugin-explore-common                 0.0.1
  @backstage/plugin-explore-react                  0.0.29
  @backstage/plugin-explore                        0.4.5
  @backstage/plugin-github-actions                 0.6.0
  @backstage/plugin-home-react                     0.1.0
  @backstage/plugin-home                           0.5.3
  @backstage/plugin-org                            0.6.9
  @backstage/plugin-permission-backend             0.5.21
  @backstage/plugin-permission-common              0.7.6
  @backstage/plugin-permission-node                0.7.9
  @backstage/plugin-permission-react               0.4.13
  @backstage/plugin-proxy-backend                  0.2.40
  @backstage/plugin-scaffolder-backend             1.15.0
  @backstage/plugin-scaffolder-common              1.3.1
  @backstage/plugin-scaffolder-node                0.1.4
  @backstage/plugin-scaffolder-react               1.5.0
  @backstage/plugin-scaffolder                     1.14.0
  @backstage/plugin-search-backend-module-catalog  0.1.2
  @backstage/plugin-search-backend-module-explore  0.1.2
  @backstage/plugin-search-backend-module-pg       0.5.7
  @backstage/plugin-search-backend-module-techdocs 0.1.2
  @backstage/plugin-search-backend-node            1.2.2
  @backstage/plugin-search-backend                 1.3.2
  @backstage/plugin-search-common                  1.2.4
  @backstage/plugin-search-react                   1.6.2
  @backstage/plugin-search                         1.3.2
  @backstage/plugin-sonarqube-backend              0.2.0
  @backstage/plugin-sonarqube-react                0.1.6
  @backstage/plugin-sonarqube                      0.7.0
  @backstage/plugin-tech-radar                     0.6.5
  @backstage/plugin-techdocs-backend               1.6.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.14
  @backstage/plugin-techdocs-node                  1.7.2
  @backstage/plugin-techdocs-react                 1.1.7
  @backstage/plugin-techdocs                       1.6.4
  @backstage/plugin-todo-backend                   0.1.43
  @backstage/plugin-todo                           0.2.21
  @backstage/plugin-user-settings                  0.7.4
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.0
  @backstage/theme                                 0.3.0, 0.4.0
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@ahhhndre do you wanna poke around a little bit here and see if there's anything that stands out?

**Comment by awanlin** [comment]
Alright, took some time to look into this and it's pretty easy to reproduce but I'm not sure the right way to fix it:

1. We can rollback the changes but then we run into the issue that the password is visible in clear text in the DevTools plugin
2. We leave it but then we can't use the `--strict` flag which means other config issues could get in
3. We figure out some way for the schema to work with the `[key: string]: unknown`, I'm just not seeing that being possible
4. We wait for #18187  to get merged in at which point we revert the changes and then use the parent secret to secure the password

I think option 4 is our best path forward, what do you think @benjdlambert?

@tcnaganath sorry this ended up causing you this issue, I'll do my best to get this resolved but as you can see there's some things we need to balance out

**Comment by awanlin** [comment]
Kept digging. I think this is where we might make a change for option 3:

https://github.com/backstage/backstage/blob/b5344d21db5ec259a1a13982afeca69e767cb0f5/packages/config-loader/src/schema/compile.ts#L104-L114

But again, I'm not sure how this should be changed or what the impacts of it being changed

**Comment by benjdlambert** [comment]
@awanlin I'm thinking that we go through with option 4, I will try and get that PR in today, so that we can make a next release with it and get this fixed in tomorrows release but no promises 🤞

**Comment by awanlin** [comment]
Now that #18187 has been merged in I'll get a PR in place to roll back my changes and use this new feature instead. I should have that done by end of day Friday @tcnaganath

**Comment by awanlin** [comment]
@Rugvip would https://github.com/backstage/backstage/pull/18837 resolve this as well? I never got back to this but I have time now so was going to start but not sure if I should

**Comment by Rugvip** [comment]
@awanlin Oh, yes I think it does! I'll ship it so all that's left is to validate it in master

**Comment by awanlin** [comment]
Confirmed, PR #18837 fixes this issue 🚀 

@tcnaganath, so the fix for this will get published as part of the weekly release on Tuesday August 1st and then the monthly release on August 15th

**Comment by Rugvip** [comment]
🎉 , closing
