### ISSUE TITLE
🐛 Bug Report: k8s plugin container info sidebar does not stay open

### ISSUE THREAD

**Issue by langeno** [backstage/backstage#18471]
### 📜 Description

When using the k8s plugin to view detailed pod information a sidebar opens.
This sidebar however closes on its own with a ~1-20 seconds again, making it hard to read logs etc.

### 👍 Expected behavior

The opened pod information sidebar should stay open until manually closed.

### 👎 Actual Behavior with Screenshots

It is hard to snap shot a disappearing bar, but below screenshot shows the sidebar the vanishes after some seconds:
![image](https://github.com/backstage/backstage/assets/128791938/4d28c2f1-74ea-4721-a71a-d052c9a8a560)

### 👟 Reproduction steps

1. Install a backstage instance, register a catalog component which uses k8s plugin, configure the k8s plugin in the app-config.yaml file.
2. Navigate to the kubernetes plugin tab of the component that uses the k8s plugin, open the dropdowns until your pod(s) are shown, click on a pod name to see the pod information sidebar
3. Wait some seconds (less than a minute likely, although that might be related to the refresh interval of the k8s plugin)
4. See how the pod information sidebar closes again

### 📃 Provide the context for the Bug.

This bug makes e.g. reading the logs of a pod very cumbersome, as the window closes again before you find the relevant information.

I noticed that the "Network" tab of my firefox developer tools shows that each time the sidebar opens a GET/POST request is triggered (I think by the k8s plugin). Interestingly however, the information for Deployment (which has a similar sidebar as pods) stays open during those reloads. Also changing the refresh interval in the typescript code from the default 10s to 30s seems to improve the issue as reloads are more rare then.

### 🖥️ Your Environment

yarn backstage-cli info
yarn run v1.22.19
$ /home/olangen/git_repos/backstage-sasd/node_modules/.bin/backstage-cli info
OS:   Linux 5.15.0-72-generic - linux/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.22.8 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                               1.4.0
  @backstage/backend-app-api                            0.4.4
  @backstage/backend-common                             0.18.5, 0.19.0
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.3
  @backstage/backend-tasks                              0.5.3
  @backstage/backend-test-utils                         0.1.38
  @backstage/catalog-client                             1.4.2
  @backstage/catalog-model                              1.4.0
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.1
  @backstage/cli                                        0.22.8
  @backstage/codemods                                   0.1.44
  @backstage/config-loader                              1.3.1
  @backstage/config                                     1.0.8
  @backstage/core-app-api                               1.8.1
  @backstage/core-components                            0.13.2
  @backstage/core-plugin-api                            1.5.2
  @backstage/create-app                                 0.5.2
  @backstage/dev-utils                                  1.0.16
  @backstage/errors                                     1.2.0
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.4
  @backstage/integration-react                          1.1.14
  @backstage/integration                                1.5.0
  @backstage/plugin-adr-backend                         0.3.4
  @backstage/plugin-adr-common                          0.2.10
  @backstage/plugin-adr                                 0.6.2
  @backstage/plugin-api-docs                            0.9.5
  @backstage/plugin-app-backend                         0.3.46
  @backstage/plugin-auth-backend                        0.18.4
  @backstage/plugin-auth-node                           0.2.15
  @backstage/plugin-badges-backend                      0.2.1
  @backstage/plugin-badges                              0.2.43
  @backstage/plugin-catalog-backend-module-msgraph      0.5.5
  @backstage/plugin-catalog-backend                     1.10.0
  @backstage/plugin-catalog-common                      1.0.14
  @backstage/plugin-catalog-graph                       0.2.31
  @backstage/plugin-catalog-graphql                     0.3.21
  @backstage/plugin-catalog-import                      0.9.9
  @backstage/plugin-catalog-node                        1.3.7
  @backstage/plugin-catalog-react                       1.7.0
  @backstage/plugin-catalog                             1.11.2
  @backstage/plugin-events-backend                      0.2.7
  @backstage/plugin-events-node                         0.2.7
  @backstage/plugin-explore-backend                     0.0.8
  @backstage/plugin-explore-common                      0.0.1
  @backstage/plugin-explore-react                       0.0.29
  @backstage/plugin-explore                             0.4.5
  @backstage/plugin-graphiql                            0.2.51
  @backstage/plugin-graphql-backend                     0.1.36
  @backstage/plugin-home-react                          0.1.0
  @backstage/plugin-home                                0.5.3
  @backstage/plugin-jenkins-backend                     0.2.1
  @backstage/plugin-jenkins-common                      0.1.16
  @backstage/plugin-jenkins                             0.8.1
  @backstage/plugin-kubernetes-backend                  0.11.1
  @backstage/plugin-kubernetes-common                   0.6.4
  @backstage/plugin-kubernetes                          0.9.2
  @backstage/plugin-microsoft-calendar                  0.1.4
  @backstage/plugin-org                                 0.6.9
  @backstage/plugin-permission-backend                  0.5.21
  @backstage/plugin-permission-common                   0.7.6
  @backstage/plugin-permission-node                     0.7.9
  @backstage/plugin-permission-react                    0.4.13
  @backstage/plugin-proxy-backend                       0.2.40
  @backstage/plugin-scaffolder-backend                  1.15.0
  @backstage/plugin-scaffolder-common                   1.3.1
  @backstage/plugin-scaffolder-node                     0.1.4
  @backstage/plugin-scaffolder-react                    1.5.0
  @backstage/plugin-scaffolder                          1.14.0
  @backstage/plugin-search-backend-module-catalog       0.1.2
  @backstage/plugin-search-backend-module-explore       0.1.2
  @backstage/plugin-search-backend-module-pg            0.5.7
  @backstage/plugin-search-backend-module-techdocs      0.1.2
  @backstage/plugin-search-backend-node                 1.2.2
  @backstage/plugin-search-backend                      1.3.2
  @backstage/plugin-search-common                       1.2.4
  @backstage/plugin-search-react                        1.6.2
  @backstage/plugin-search                              1.3.2
  @backstage/plugin-shortcuts                           0.3.11
  @backstage/plugin-sonarqube-backend                   0.2.0
  @backstage/plugin-sonarqube-react                     0.1.6
  @backstage/plugin-sonarqube                           0.7.0
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.30
  @backstage/plugin-tech-insights-backend               0.5.12
  @backstage/plugin-tech-insights-common                0.2.11
  @backstage/plugin-tech-insights-node                  0.4.4
  @backstage/plugin-tech-radar                          0.6.5
  @backstage/plugin-techdocs-backend                    1.6.3
  @backstage/plugin-techdocs-module-addons-contrib      1.0.14
  @backstage/plugin-techdocs-node                       1.7.2
  @backstage/plugin-techdocs-react                      1.1.7
  @backstage/plugin-techdocs                            1.6.4
  @backstage/plugin-todo-backend                        0.1.43
  @backstage/plugin-todo                                0.2.21
  @backstage/plugin-user-settings                       0.7.4
  @backstage/release-manifests                          0.0.9
  @backstage/repo-tools                                 0.3.1
  @backstage/test-utils                                 1.4.0
  @backstage/theme                                      0.3.0, 0.4.0
  @backstage/types                                      1.1.0
  @backstage/version-bridge                             1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR! (assuming the fix does not get too complicated and figuring out the root cause is manageable with some support)

**Comment by benjdlambert** [comment]
ping @backstage/kubernetes-maintainers here to take a look :tada:

**Comment by rmartine-ias** [comment]
Experiencing the same issue, nothing indicative in the console.

**Comment by mclarke47** [comment]
IIRC this happens when we refresh the data from the backend and a component gets re-rendered so it is no longer shown

**Comment by Lucas-Desouza** [comment]
Anyone have any update on this? We're also seeing this issue.

**Comment by mclarke47** [comment]
@Lucas-Desouza I haven't had a chance to look at this yet

**Comment by mclarke47** [comment]
I had a quick look today and it seems like it happens most often when the pods are changing e.g. a pod is being removed from the current table page.


<img width="1723" alt="Screenshot 2023-07-25 at 7 00 27 PM" src="https://github.com/backstage/backstage/assets/6514980/d4c974c7-61ef-4f4e-bb36-5bb3e4c4c4b8">

It doesn't seem to happen for me when nothing is changing, I had to delete a pod on the same page of the table but not the one I was looking at to get it to trigger.

**Comment by mclarke47** [comment]
Ok here's a weird ask, when this happens can you check *it's definitely the same pod open in the drawer*

I just noticed that after the pod logs dialog close the drawer is actually now open with a different pod!

Open pod logs:
<img width="1190" alt="Screenshot 2023-07-25 at 9 58 36 PM" src="https://github.com/backstage/backstage/assets/6514980/04788b56-58c7-4d16-8f55-736672c119d2">

Deleted some _other_ pods

<img width="1133" alt="Screenshot 2023-07-25 at 9 58 52 PM" src="https://github.com/backstage/backstage/assets/6514980/0ff2b44a-ecc9-489c-b9c8-0329a7f75a20">

Now a totally different pod is selected!

**Comment by simonstamm** [comment]
Hey @mclarke47, debugged it a little bit and if I change in `PodsTable.tsx` in `<Table>` the data to `pods.map((pod: Pod) => ({ ...pod, id: pod?.metadata?.uid }))` it's working and will not close anymore. So adding an id property is quite important for the table.

**Comment by benjdlambert** [comment]
@simonstamm this sounds like a good fix - do you want to pick this up a contribute a fix? :pray:

**Comment by langeno** [comment]
@simonstamm if you did not already start work on a fix I can also try to provide one myself if you don't mind. With the input you gave above I feel like I should be able to fix it.

**Comment by benjdlambert** [comment]
@langeno go ahead, this hasn't been contributed yet! ❤️

**Comment by simonstamm** [comment]
@langeno I tried implementing it but was not able to resolve the

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

So I'm really looking forward to your contribution. 🎉

**Comment by langeno** [comment]
Just an update, I have a "fix" that seems to be working (combination of what @simonstamm did + ~3 additional lines that introduce an id property for the table), but still give warnings in the browser console. The same seems to be the case for the techdocs table displayer for the docs, so I assume this is some deeper issue with material-table and backstage and hopefully can be ignored.

I am a tad bound privateley right now so it will take a few days until I can open up an merge request. If anyone is faster of course feel free to open up a MR yourself.

**Comment by langeno** [comment]
I opened a PR for my changes: https://github.com/backstage/backstage/pull/19875/files

This was done in tad of a hurry and I am worried by the still existing warning messages (as mentioned above already).
So if someone has the time/setup to cross-check if this also fixes the issues on their end it would be really appreciated.

**Comment by lpborges** [comment]
Any news about this fix?

**Comment by langeno** [comment]
@lpborges See the comments in the PR and feel free to restart it/start a new one to get the fixes in. I might do so too, but no clue when I get around to that :(
