### ISSUE TITLE
🐛 Bug Report: Okta auth provider returns an error on endpoint /api/auth/okta/handler/frame 

### ISSUE THREAD

**Issue by vgauzziexaring** [backstage/backstage#18486]
### 📜 Description

when calling  /api/auth/okta/handler/frame I get the following message "{"error":{"name":"InputError","message":"Must specify 'env' query to select environment","stack":"InputError: Must specify 'env' query to select environment\n " regardless of the node env

### 👍 Expected behavior

It should return a 200

### 👎 Actual Behavior with Screenshots

the following error is displayed

`{"error":{"name":"InputError","message":"Must specify 'env' query to select environment","stack":"InputError: Must specify 'env' query to select environment\n    at OAuthEnvironmentHandler.getProviderForEnv (/Users/user/projects/test/backstage/backstage/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:232:13)\n    at OAuthEnvironmentHandler.frameHandler (/Users/user/projects/test/backstage/backstage/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:203:27)\n    at handleReturn (/Users/user/projects/test/backstage/backstage/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound frameHandler (/Users/user/projects/test/backstage/backstage/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at handleReturn (/Users/user/projects/test/backstage/backstage/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound frameHandler (/Users/user/projects/test/backstage/backstage/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at Layer.handle [as handle_request] (/Users/user/projects/test/backstage/backstage/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/user/projects/test/backstage/backstage/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/Users/user/projects/test/backstage/backstage/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/Users/user/projects/test/backstage/backstage/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/user/projects/test/backstage/backstage/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/Users/user/projects/test/backstage/backstage/node_modules/express/lib/router/index.js:346:12)\n    at next (/Users/user/projects/test/backstage/backstage/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/Users/user/projects/test/backstage/backstage/node_modules/express/lib/router/index.js:175:3)\n    at router (/Users/user/projects/test/backstage/backstage/node_modules/express/lib/router/index.js:47:12)\n    at handleReturn (/Users/user/projects/test/backstage/backstage/node_modules/express-promise-router/lib/express-promise-router.js:24:23)"},"request":{"method":"GET","url":"/api/auth/okta/handler/frame"},"response":{"statusCode":400}}`

### 👟 Reproduction steps

1. Create a new backstage instance using `npx @backstage/create-app@latest`
2. Add the configuration snippet

```
auth:
  environment: production
  providers:
    okta:
      production:
        audience: xxx
        clientId: xxx
        clientSecret: xxx
``` 
3. configure okta as instructed here: https://backstage.io/docs/auth/okta/provider
4. start backstage
5. call https://url/api/auth/okta/handler/frame 

### 📃 Provide the context for the Bug.

No matter what I do i cannot get the expected behaviour from the end point as described in the documentation  https://backstage.io/docs/auth/okta/provider 

The suggestion here: https://github.com/backstage/backstage/issues/4464 did not help with the issue at all

### 🖥️ Your Environment

```
node: v18.16.0
yarn: 1.22.19
cli:  0.22.8 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                          1.4.0
  @backstage/backend-app-api                       0.4.4
  @backstage/backend-common                        0.19.0
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.3
  @backstage/backend-tasks                         0.5.3
  @backstage/catalog-client                        1.4.2
  @backstage/catalog-model                         1.4.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.1
  @backstage/cli                                   0.22.8
  @backstage/config-loader                         1.3.1
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.8.1
  @backstage/core-components                       0.13.2
  @backstage/core-plugin-api                       1.5.2
  @backstage/errors                                1.2.0
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.4
  @backstage/integration-react                     1.1.14
  @backstage/integration                           1.5.0
  @backstage/plugin-api-docs                       0.9.5
  @backstage/plugin-app-backend                    0.3.46
  @backstage/plugin-auth-backend                   0.18.4
  @backstage/plugin-auth-node                      0.2.15
  @backstage/plugin-catalog-backend                1.10.0
  @backstage/plugin-catalog-common                 1.0.14
  @backstage/plugin-catalog-graph                  0.2.31
  @backstage/plugin-catalog-import                 0.9.9
  @backstage/plugin-catalog-node                   1.3.7
  @backstage/plugin-catalog-react                  1.7.0
  @backstage/plugin-catalog                        1.11.2
  @backstage/plugin-events-node                    0.2.7
  @backstage/plugin-github-actions                 0.6.0
  @backstage/plugin-org                            0.6.9
  @backstage/plugin-permission-common              0.7.6
  @backstage/plugin-permission-node                0.7.9
  @backstage/plugin-permission-react               0.4.13
  @backstage/plugin-proxy-backend                  0.2.40
  @backstage/plugin-scaffolder-backend             1.15.0
  @backstage/plugin-scaffolder-common              1.3.1
  @backstage/plugin-scaffolder-node                0.1.4
  @backstage/plugin-scaffolder-react               1.5.0
  @backstage/plugin-scaffolder                     1.14.0
  @backstage/plugin-search-backend-module-catalog  0.1.2
  @backstage/plugin-search-backend-module-pg       0.5.7
  @backstage/plugin-search-backend-module-techdocs 0.1.2
  @backstage/plugin-search-backend-node            1.2.2
  @backstage/plugin-search-backend                 1.3.2
  @backstage/plugin-search-common                  1.2.4
  @backstage/plugin-search-react                   1.6.2
  @backstage/plugin-search                         1.3.2
  @backstage/plugin-tech-radar                     0.6.5
  @backstage/plugin-techdocs-backend               1.6.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.14
  @backstage/plugin-techdocs-node                  1.7.2
  @backstage/plugin-techdocs-react                 1.1.7
  @backstage/plugin-techdocs                       1.6.4
  @backstage/plugin-user-settings                  0.7.4
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.0
  @backstage/theme                                 0.4.0
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Closing since the `env` query parameter is required, explained by https://github.com/backstage/backstage/issues/18486#issuecomment-1612637405
