### ISSUE TITLE
🚀 Feature: add links to system entities

### ISSUE THREAD

**Issue by mkleint** [backstage/backstage#18501]
### 🔖 Feature description

even though links metadata is allowed on systems, they never appear in the backstage ui. This would be useful for things ike design pages or oncall support pages that are relevant to entire systems and not just single component.

### 🎤 Context

can't submit PR because not fluent with javascript , but is either a bug or feature request

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by mkleint** [comment]
looks like we are using 1.14

**Comment by benjdlambert** [comment]
@mkleint do you have the `EntityLinksCard` component under the systems entity page in your copy of `EntityPage.tsx` in your backstage app?

**Comment by mkleint** [comment]
thanks for your support. we do now and it works.
