### ISSUE TITLE
🐛 Bug Report: common-library plugin not being added

### ISSUE THREAD

**Issue by gocapa** [backstage/backstage#18506]
### 📜 Description

Hi, I created a plugin that can be used for frontend and backend doing this command yarn backstage-cli create --select plugin-common

I creates perfectly but when I try to add it to the backend it doesn't work. It says not found.

### 👍 Expected behavior

I expectedit to be added to either frontend and backend.

### 👎 Actual Behavior with Screenshots

Not found.

### 👟 Reproduction steps

1. yarn backstage-cli create --select plugin-common
2. yarn --cwd packages/backend add <my-plugin-name>

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by gocapa** [comment]
@Rugvip https://github.com/backstage/backstage/issues/10283 saw you answered this could you please help me?

**Comment by benjdlambert** [comment]
You need to run `yarn --cwd packages/backend add PACKAGE_NAME` you can find the package name in the created folders package.json. Does that still not work?

**Comment by Athira-Sabu** [comment]
Hey I just encountered with this error and got stuck now. 
Context - I created a common plugin, when trying to add using command `yarn --cwd packages/backend add @internal/backstage-plugin-notifications-common`, getting below error

```shell
❯ yarn --cwd packages/backend add @internal/backstage-plugin-notifications-common
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@internal%2fbackstage-plugin-notifications-common: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/athira.sabu/Athira/backstage/packages/backend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
@benjdlambert
