### ISSUE TITLE
🐛 Bug Report: Catalog import does not validate component name during PR creation

### ISSUE THREAD

**Issue by CPerry26** [backstage/backstage#18508]
### 📜 Description

Hi! I hope you're all doing really well. I wanted to report a bug we've run into with Catalog Import when you provide a GitHub repository without an existing catalog-info.yaml file. On the second step you can edit the component name from what is set during the analyze step. You can rename the component to something that does not conform to the ADR described [here](https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md) (like "My First Component"). The PR is created successfully and can be merged without issue. However, the component is never imported. If you try to import the component again using the newly created catalog-info.yaml, you get an error that the metadata name does not conform to the expected format, blocking you from importing the component. 

### 👍 Expected behavior

I would expect the UI component to validate the given name, and display an error if it doesn't match the expected scheme.

### 👎 Actual Behavior with Screenshots

Here is a screenshot of clicking into a different field with the name being set to something invalid:
![Screen Shot 2023-06-30 at 10 25 38 AM](https://github.com/backstage/backstage/assets/7538203/24a3bf40-2bea-4e5d-9f67-fbb8f8711f1e)

Here is a screenshot of the error:
![Screen Shot 2023-06-30 at 10 24 39 AM](https://github.com/backstage/backstage/assets/7538203/496447b8-d7be-496c-a2ba-8c469e2f2f93)

### 👟 Reproduction steps

1. Navigate to the Catalog section of the nav.
2. Click "New".
3. Click "Register new component".
4. Enter GitHub repo URL without a catalog-info.yaml.
5. Alter the component name to something invalid like "My First Component".
6. Merge the created PR.
7. Refresh and verify the component is not registered.
8. Try and reimport the component using the new catalog-info.yaml file (i.e. repoURL/blob/main/catalog-info.yaml).
9. Error should show up.

### 📃 Provide the context for the Bug.

Teams registering components are unaware of the restrictions in place for component names. We've had teams mistakenly register a component, alter the name, but then be unable to find their component in the catalog. This causes confusion, and bug reports on our end, although we are using the out of the box React plugin.

### 🖥️ Your Environment

Our environment is deployed to Kubernetes. I was able to reproduce it using Chrome Version 114.0.5735.198 on a MacBook. We are using Backstage version `1.13.2` and plugin-catalog-import `^0.9.7`. I did some checking and couldn't see a case where this bug was fixed in a new version but I may have missed something so please correct me if I'm wrong! I'm happy to provide any more info that would help. Thanks in advance!

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by CPerry26** [comment]
Bump

**Comment by CPerry26** [comment]
Bump

**Comment by Edje-C** [comment]
Hi, this has not yet been prioritized and we're open for community contributions for this update.

**Comment by CPerry26** [comment]
No worries! I'm just bumping to avoid it being stale. Unfortunately I'm very unfamiliar with React so I'm probably not much help here :(

**Comment by npiyush97** [comment]
@CPerry26 can you try this once ?
[here] (https://github.com/backstage/backstage/blob/52941b26399487b7b80c2771a8bc3e4c19be981d/packages/catalog-model/src/validation/KubernetesValidatorFunctions.ts#L52)
```
 /^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$/.test(value)
 with
/^([A-Za-z0-9][-A-Za-z0-9_. ]*)?[A-Za-z0-9]$/.test(value)
```
