### ISSUE TITLE
🐛 Bug Report: Bazaar Plugin 'Join' not working

### ISSUE THREAD

**Issue by dlaird-ovo** [backstage/backstage#18516]
### 📜 Description

We hgave deployed the 'Bazaar' plugin and are able to add projects etc to the list.
However when people click on the Join+ button nothing happens.

Interestingly - when running the codebase locally (yarn dev) this is not the case.

### 👍 Expected behavior

When Deployed we should be able to Join 

### 👎 Actual Behavior with Screenshots

Nothing happens :-(
The card appears with the Join+ button - but clicking does nothing.

### 👟 Reproduction steps

When running locally it works - so I believe we have a deployment issue.
But is it expecting to speak to an API end point or similar which is available locally - but maybe blocked when deployed?

### 🖥️ Your Environment

We are running 1.15.0 - and are deployed within a container, hosted in AWS.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Is there any logs in the console that might help us work out what's going on here when you click the button? any failed network requests or timeouts?

**Comment by anicke** [comment]
IIRC the "Join Project" api call uses "identityApi" to get the current user. That would typically be different on local and production.

**Comment by dlaird-ovo** [comment]
So running locally I can see nothing in the console - but following the network tab (Chrome - Dev Tools)
I can see the following - after I click Join
`Request URL: PUT
http://localhost:7007/api/bazaar/projects/1/member/User%20Name`

Followed by 
`Request URL: GET
http://localhost:7007/api/bazaar/projects/1/members`

And it works.

When deployed in Prod I can see instead the following:
`Request URL: POST
https://prod-URL/api/permission/authorize`. And it gets a 200 response and nothing else.

In prod we have Permission Framework enabled (and not in Local) - so could that be creating the problem?
