### ISSUE TITLE
🐛 Bug Report: Cannot read properties of undefined (reading 'redacter')

### ISSUE THREAD

**Issue by donivvinod** [backstage/backstage#18514]
### 📜 Description

I created a brand new backstage project using the command npx @backstage/create-app.
When I started the app with yarn dev, I got the below error.  The backend component fails to start.

(base) xxxxxx@ xxxxxxs-mbp test-backstage-app % yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[1] Build succeeded
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/xxxxxx/Data/projects/test-backstage-app/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] /Users/xxxxxx/Data/projects/test-backstage-app/packages/backend/dist/main.js:323
[1] /******/ 			throw e;
[1]          			^
[1] 
[1] TypeError: Cannot read properties of undefined (reading 'redacter')
[1]     at Object.<anonymous> (/Users/xxxxxx/Data/projects/test-backstage-app/node_modules/@backstage/backend-common/dist/index.cjs.js:110:46)
[1]     at Module._compile (node:internal/modules/cjs/loader:1155:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
[1]     at Module.load (node:internal/modules/cjs/loader:1033:32)
[1]     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1057:19)
[1]     at require (node:internal/modules/cjs/helpers:103:18)
[1]     at Object.<anonymous> (/Users/xxxxxx/Data/projects/test-backstage-app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:24:21)
[1]     at Module._compile (node:internal/modules/cjs/loader:1155:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
[0] webpack compiled successfully

### 👍 Expected behavior

The backend should start without errors.

### 👎 Actual Behavior with Screenshots

The backend fails to start.

### 👟 Reproduction steps

1. Run the command npx @backstage/create-app
2. Enter a name for the app [required] test-backstage-app
3. Everything is ok till yarn install. 
4. yarn tsc fails with the below errors. 
executing     yarn tsc ◞ error Command failed with exit code 2.
yarn run v1.22.19
$ tsc
packages/backend/src/plugins/catalog.ts:9:47 - error TS2345: Argument of type 'PluginEnvironment' is not assignable to parameter of type 'CatalogEnvironment'.
  Types of property 'scheduler' are incompatible.
    Property 'getScheduledTasks' is missing in type 'import("/Users/xxxxxx/Data/projects/test-backstage-app/packages/backend/node_modules/@backstage/backend-tasks/dist/index").PluginTaskScheduler' but required in type 'import("/Users/xxxxxx/Data/projects/test-backstage-app/node_modules/@backstage/backend-tasks/dist/index").PluginTaskScheduler'.

9   const builder = await CatalogBuilder.create(env);
                                                ~~~

  node_modules/@backstage/backend-tasks/dist/index.d.ts:304:5
    304     getScheduledTasks(): Promise<TaskDescriptor[]>;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'getScheduledTasks' is declared here.

packages/backend/src/plugins/techdocs.ts:49:5 - error TS2322: Type 'import("/Users/xxxxxx/Data/projects/test-backstage-app/packages/backend/node_modules/@backstage/backend-common/dist/index").PluginCacheManager' is not assignable to type 'import("/Users/xxxxxx/Data/projects/test-backstage-app/node_modules/@backstage/backend-common/dist/index").PluginCacheManager'.
  The types returned by 'getClient(...)' are incompatible between these types.
    Property 'withOptions' is missing in type 'CacheClient' but required in type 'CacheService'.

49     cache: env.cache,
       ~~~~~

  node_modules/@backstage/backend-plugin-api/dist/index.d.ts:682:5
    682     withOptions(options: CacheServiceOptions): CacheService;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'withOptions' is declared here.
  node_modules/@backstage/plugin-techdocs-backend/dist/index.d.ts:62:5
    62     cache: PluginCacheManager;
           ~~~~~
    The expected type comes from property 'cache' which is declared here on type 'RouterOptions'


Found 2 errors in 2 files.

Errors  Files
     1  packages/backend/src/plugins/catalog.ts:9
     1  packages/backend/src/plugins/techdocs.ts:49
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  executing     yarn tsc ✖ 

Error: Could not execute command yarn tsc

It seems that something went wrong when creating the app 🤔

🔥  Failed to create app!

6. I went ahead and did a yarn dev and got the error. 

(base) xxxxxx@ xxxxxxs-mbp projects % cd test-backstage-app 
(base) xxxxxx@ xxxxxxs-mbp test-backstage-app % yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[1] Build succeeded
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/xxxxxx/Data/projects/test-backstage-app/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] /Users/xxxxxx/Data/projects/test-backstage-app/packages/backend/dist/main.js:323
[1] /******/ 			throw e;
[1]          			^
[1] 
[1] TypeError: Cannot read properties of undefined (reading 'redacter')
[1]     at Object.<anonymous> (/Users/xxxxxx/Data/projects/test-backstage-app/node_modules/@backstage/backend-common/dist/index.cjs.js:110:46)
[1]     at Module._compile (node:internal/modules/cjs/loader:1155:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
[1]     at Module.load (node:internal/modules/cjs/loader:1033:32)
[1]     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1057:19)
[1]     at require (node:internal/modules/cjs/helpers:103:18)
[1]     at Object.<anonymous> (/Users/xxxxxx/Data/projects/test-backstage-app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:24:21)
[1]     at Module._compile (node:internal/modules/cjs/loader:1155:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
[0] webpack compiled successfully

^[
^C
[0] <i> [webpack-dev-server] Gracefully shutting down. To force exit, press ^C again. Please wait...                                                                 
(base) xxxxxx@ xxxxxxs-mbp test-backstage-app % [1] yarn start-backend exited with code SIGINT
[0] yarn start exited with code SIGINT
^C


### 📃 Provide the context for the Bug.

I am also experiencing a similar issue on a working backstage app in Windows after I did a yarn install last week. yarn tsc does not report any error. But when I run yarn dev the same error regarding the redactor throws up.

So I tried a brand new application using my MacBook and the redactor issue shows up. So I guess something has gone wrong with the latest  1.15.0 release

### 🖥️ Your Environment

OS:   Darwin 22.5.0 - darwin/arm64
node: v16.18.1
yarn: 1.22.19
cli:  0.22.8 (installed)
backstage:  1.9.0

Dependencies:
  @backstage/app-defaults                          1.4.0
  @backstage/backend-app-api                       0.4.4
  @backstage/backend-common                        0.17.0, 0.18.5, 0.19.0
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.3
  @backstage/backend-tasks                         0.4.3, 0.5.3
  @backstage/catalog-client                        1.4.2
  @backstage/catalog-model                         1.4.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.1
  @backstage/cli                                   0.22.8
  @backstage/config-loader                         1.3.1
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.8.1
  @backstage/core-components                       0.12.5, 0.13.2
  @backstage/core-plugin-api                       1.5.2
  @backstage/errors                                1.2.0
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.4
  @backstage/integration-react                     1.1.14
  @backstage/integration                           1.5.0
  @backstage/plugin-api-docs                       0.8.14
  @backstage/plugin-app-backend                    0.3.46
  @backstage/plugin-auth-backend                   0.17.4
  @backstage/plugin-auth-node                      0.2.15
  @backstage/plugin-catalog-backend                1.10.0
  @backstage/plugin-catalog-common                 1.0.14
  @backstage/plugin-catalog-graph                  0.2.31
  @backstage/plugin-catalog-import                 0.9.9
  @backstage/plugin-catalog-node                   1.3.7
  @backstage/plugin-catalog-react                  1.7.0
  @backstage/plugin-catalog                        1.11.2
  @backstage/plugin-events-node                    0.2.7
  @backstage/plugin-github-actions                 0.5.18
  @backstage/plugin-org                            0.6.9
  @backstage/plugin-permission-common              0.7.6
  @backstage/plugin-permission-node                0.7.9
  @backstage/plugin-permission-react               0.4.13
  @backstage/plugin-proxy-backend                  0.2.40
  @backstage/plugin-scaffolder-backend             1.15.0
  @backstage/plugin-scaffolder-common              1.3.1
  @backstage/plugin-scaffolder-node                0.1.4
  @backstage/plugin-scaffolder-react               1.5.0
  @backstage/plugin-scaffolder                     1.14.0
  @backstage/plugin-search-backend-module-catalog  0.1.2
  @backstage/plugin-search-backend-module-pg       0.5.7
  @backstage/plugin-search-backend-module-techdocs 0.1.2
  @backstage/plugin-search-backend-node            1.2.2
  @backstage/plugin-search-backend                 1.3.2
  @backstage/plugin-search-common                  1.2.4
  @backstage/plugin-search-react                   1.6.2
  @backstage/plugin-search                         1.3.2
  @backstage/plugin-tech-radar                     0.5.20
  @backstage/plugin-techdocs-backend               1.6.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.14
  @backstage/plugin-techdocs-node                  1.7.2
  @backstage/plugin-techdocs-react                 1.1.7
  @backstage/plugin-techdocs                       1.6.4
  @backstage/plugin-user-settings                  0.6.2
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.0
  @backstage/theme                                 0.2.19, 0.3.0, 0.4.0
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
✨  Done in 0.75s.



 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@donivvinod it looks like you have some duplicate packages and duplicate types getting in the way here. Can you try doing `yarn backstage-cli versions:bump` to get to the latest versions on all the packages?

Notice how this: `import("/Users/xxxxxx/Data/projects/test-backstage-app/packages/backend/node_modules/@backstage/backend-common/dist/index"` has nested `node_modules` and it's not compatible with `import("/Users/xxxxxx/Data/projects/test-backstage-app/node_modules/@backstage/backend-common/dist/index").PluginCacheManager` which is the one at the root.

**Comment by takamuffin** [comment]
I wanted to comment that this error popped up for me in our build pipeline with no changes on our end. Which tells me one of the ^ versions picked up the problem. I tried to determine which package update might have caused it but was completely unsuccessful.

`yarn backstage-cli versions:bump` fixed it for me.

**Comment by benjdlambert** [comment]
@donivvinod did the bump work for you too?

**Comment by emre06ylmz** [comment]
> @donivvinod it looks like you have some duplicate packages and duplicate types getting in the way here. Can you try doing `yarn backstage-cli versions:bump` to get to the latest versions on all the packages?
> 
> Notice how this: `import("/Users/xxxxxx/Data/projects/test-backstage-app/packages/backend/node_modules/@backstage/backend-common/dist/index"` has nested `node_modules` and it's not compatible with `import("/Users/xxxxxx/Data/projects/test-backstage-app/node_modules/@backstage/backend-common/dist/index").PluginCacheManager` which is the one at the root.

Thank you, it worked for me too.
