### ISSUE TITLE
[Plugin] KFServing scaffolder

### ISSUE THREAD

**Issue by swiftdiaries** [backstage/backstage#1851]
## Summary

KFServing scaffolder for serverless ML inference.

## Project website (if applicable)
www.kubeflow.org

## Context

https://github.com/spotify/backstage/issues/1850

**Comment by stefanalund** [comment]
Do you think this would be possible to realise using our recently announced Software Templates feature?

https://backstage.io/blog/2020/08/05/announcing-backstage-software-templates

**Comment by swiftdiaries** [comment]
Yes, I was trying to figure out how to use one and then build a template

**Comment by benjdlambert** [comment]
@swiftdiaries I'd love to try and get this working with what we've built with software templates. Are you on Discord? If you could reach out to me `@blam` and we can work together to see how we can do it! 👍
