### ISSUE TITLE
🔌 Plugin: Analytics module New Relic Browser

### ISSUE THREAD

**Issue by jmezach** [backstage/backstage#18529]
### 🔖 Summary

Monitoring the usage of Backstage is a very important aspect of figuring out the overall adoption of it within an organization. Out-of-the-box Backstage already has support for Google Analytics, but there are more tools out there. One of those is [New Relic Browser](https://newrelic.com/platform/browser-monitoring) and it is what we are using internally. It would be great if there was an analytics plugin that integrated with New Relic Browser.

### 🌐 Project website (if applicable)

https://newrelic.com/platform/browser-monitoring

### ✌️ Context

There is some talk about New Relic in #8398, although that appears to be a larger scope than just providing an implementation of the `AnalyticsApi` interface specifically for New Relic.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
implemented!
