### ISSUE TITLE
🚀 Feature: Add support for customizable language in WelcomeTitle component

### ISSUE THREAD

**Issue by grvpandey11** [backstage/backstage#18520]
### 🔖 Feature description

The WelcomeTitle component currently displays greetings based on the time of day. However, it would be beneficial to provide the option to customize the language used for the greetings. This feature aims to enhance the WelcomeTitle component by allowing users to pass a language variable (optional), which will determine the language used for the greetings. This customization will enable a more personalized and localized experience for users.

### 🎤 Context

By introducing an optional language variable, users will have the flexibility to pass their preferred language to the component. The component will then fetch the respective greeting from a JSON file containing language-specific greetings.

### ✌️ Possible Implementation

Add an optional language parameter to the WelcomeTitle component's props. 
Modify the getTimeBasedGreeting function in the timeUtil file to accept an optional language parameter.
Within the getTimeBasedGreeting function, if the language parameter is provided, fetch the respective language-specific greetings from the corresponding JSON file.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Hmm I think that this probably falls under some of the i18n experiments that we're looking at right now #17777 #17436

**Comment by awanlin** [comment]
Hi @grvpandey11, looking at your PR this statement is not correct: "This feature enhancement will significantly improve the user experience by providing greetings in the user's desired language." as it won't be in the user's desired language but in the language you've hard coded via the provided prop. Maybe you can just remove that from this issue? 

@benjdlambert I do think this is a bit of a unique edge case as the `WelcomeTitle` randomly displays a given language, I'm not sure that the i18n experiments would handle or cover this.

**Comment by grvpandey11** [comment]
@awanlin I have updated the issue now

**Comment by awanlin** [comment]
Thanks, I've done a full review of your PR and left some comments @grvpandey11 👍

**Comment by benjdlambert** [comment]
> @benjdlambert I do think this is a bit of a unique edge case as the WelcomeTitle randomly displays a given language, I'm not sure that the i18n experiments would handle or cover this.

Apologies I misunderstood what was happening in the PR, I saw language and straight away assumed i18n. Although maybe it would be possible to drive that language from the current i18n language that is set :shrug:

**Comment by awanlin** [comment]
Going to close this seeing at the PR to add this has been merged in. Great work and thanks for your patience working through the PR @grvpandey11 🚀

**Comment by grvpandey11** [comment]
Special thanks to you @awanlin for all the suggestions and helping me in merging the Pull request.
Thanks to you too @camilaibs
