### ISSUE TITLE
[Plugin] Buildkite

### ISSUE THREAD

**Issue by jessebye** [backstage/backstage#1854]
## Summary

Show a list of builds in Buildkite and allow users to drill down to get more information.

## Project website (if applicable)

https://buildkite.com/docs/apis/webhooks

## Context

A CI view is one of the essential and most used plugins inside Spotify. As an example, our CI environment adds deep links into Backstage in the Pull Request view(s) in GitHub. From there engineers can drill down further and follow the status of PRs as they make their way into production.

**Comment by freben** [comment]
Nice! Is this something you would like to contribute?

**Comment by jessebye** [comment]
I think @mikeandersen was considering contributing this 😁

**Comment by stefanalund** [comment]
I think you could borrow a lot of stuff from the CircleCI plugin: https://github.com/spotify/backstage/tree/master/plugins/circleci

**Comment by dtuite** [comment]
We have started working on a Buildkite plugin. The code will be here: https://github.com/RoadieHQ/backstage-plugin-buildkite

**Comment by lewtakm** [comment]
Hello,
plugin is almost finished now, we are preparing now to publish it to NPM and then open a PR to Backstage sample app 👍 
Preview: https://www.loom.com/share/4fa2756a6f5f47428305233ab9ce17e9

Since there are more and more plugins following similar pattern to show CI/CD stuff, maybe it will be a good idea to create a Backstage component for it?

**Comment by andrewthauer** [comment]
I also see a need to display multiple CI providers at once, which is something that's not currently possible with the example setup. Using GitHub actions for a small portion of things via app integrations and an 3rd party provider for the rest is coming up occasionally.

**Comment by freben** [comment]
@andrewthauer Hm. Yeah so, even though you could implement your own page that renders two tables (one for each plugin), it for sure isn't very convenient, and we'd have to make sure to establish patterns for what plugins export to make that work in general. Also the build details page routes will be colliding.

@Rugvip as per our discussions today - this would be one of those places in what I talked about, where one would override `githubActionsDetailsRouteRef`'s path to not be `/:id` but instead `/gh/:id` or whatever, to remove the collision.

**Comment by dtuite** [comment]
We have developed and open sourced [a Buildkite plugin](https://roadie.io/backstage/plugins/buildkite). The code is [here](https://github.com/RoadieHQ/backstage-plugin-buildkite).

It follows the same patterns as all the other CI plugins but here's a screenshot anyway.

![buildkite-plugin](https://user-images.githubusercontent.com/562403/99903173-a9d85b80-2cba-11eb-929b-2e96942bb138.png)

**Comment by benjdlambert** [comment]
Can we close this issue now give the plugin is ready?
