### ISSUE TITLE
🐛 Bug Report: Backstage Plugin Sentry "No implementation available for apiRef{plugin.sentry.service}"

### ISSUE THREAD

**Issue by david-christ** [backstage/backstage#18562]
### 📜 Description

I installed the Sentry plugin. When `export`ing the `$SENTRY_TOKEN` and running the dev mode locally, I get the error message

> No implementation available for apiRef{plugin.sentry.service}

There are no log messages other than the `GET` requests from my browser in the Backstage logs.

If using `MockSentryApi` as per instructions, it works fine. But that also registers an API Ref via `packages/app/src/apis.ts`.

### 👍 Expected behavior

It should show the Sentry data. If for some reason credentials are wrong, it should still render the page (and not a full-page error overlay), and logs should indicate a failed API communication attempt.

### 👎 Actual Behavior with Screenshots

<img width="954" alt="Screenshot 2023-07-05 at 11 16 05 am" src="https://github.com/backstage/backstage/assets/90661517/4b529006-ea5e-4b23-991f-9da29260e08d">

### 👟 Reproduction steps

Installed the plugin following instructions on https://github.com/backstage/backstage/blob/patch/v1.14.0/plugins/sentry/README.md

### 🖥️ Your Environment

```
$ yarn backstage-cli info
OS:   Darwin 22.5.0 - darwin/arm64
node: v18.12.1
yarn: 3.2.3
cli:  0.22.8 (installed)
backstage:  1.14.0

Dependencies:
  @backstage/app-defaults                         1.3.1
  @backstage/backend-app-api                      0.4.3, 0.4.4
  @backstage/backend-common                       0.18.5, 0.19.0
  @backstage/backend-dev-utils                    0.1.1
  @backstage/backend-plugin-api                   0.5.2, 0.5.3
  @backstage/backend-tasks                        0.5.2, 0.5.3
  @backstage/backend-test-utils                   0.1.37
  @backstage/catalog-client                       1.4.1, 1.4.2
  @backstage/catalog-model                        1.3.0, 1.4.0
  @backstage/cli-common                           0.1.12
  @backstage/cli-node                             0.1.1
  @backstage/cli                                  0.22.8
  @backstage/config-loader                        1.3.0, 1.3.1
  @backstage/config                               1.0.7, 1.0.8
  @backstage/core-app-api                         1.8.0
  @backstage/core-components                      0.13.1, 0.13.2
  @backstage/core-plugin-api                      1.5.1, 1.5.2
  @backstage/dev-utils                            1.0.15
  @backstage/errors                               1.1.5, 1.2.0
  @backstage/eslint-plugin                        0.1.3
  @backstage/integration-aws-node                 0.1.3, 0.1.4
  @backstage/integration-react                    1.1.13
  @backstage/integration                          1.4.5, 1.5.0
  @backstage/plugin-analytics-module-ga4          0.1.0
  @backstage/plugin-app-backend                   0.3.46
  @backstage/plugin-auth-backend                  0.18.3
  @backstage/plugin-auth-node                     0.2.14, 0.2.15
  @backstage/plugin-catalog-backend-module-github 0.3.0
  @backstage/plugin-catalog-backend               1.10.0, 1.9.1
  @backstage/plugin-catalog-common                1.0.13, 1.0.14
  @backstage/plugin-catalog-graph                 0.2.30
  @backstage/plugin-catalog-import                0.9.8
  @backstage/plugin-catalog-node                  1.3.6, 1.3.7
  @backstage/plugin-catalog-react                 1.6.0, 1.7.0
  @backstage/plugin-catalog                       1.11.0
  @backstage/plugin-events-node                   0.2.6, 0.2.7
  @backstage/plugin-github-actions                0.5.18
  @backstage/plugin-home                          0.5.2
  @backstage/plugin-kubernetes-common             0.6.3
  @backstage/plugin-org                           0.6.8
  @backstage/plugin-permission-backend            0.5.20
  @backstage/plugin-permission-common             0.7.5, 0.7.6
  @backstage/plugin-permission-node               0.7.8, 0.7.9
  @backstage/plugin-permission-react              0.4.12, 0.4.13
  @backstage/plugin-proxy-backend                 0.2.39
  @backstage/plugin-scaffolder-backend            1.15.0
  @backstage/plugin-scaffolder-common             1.3.0, 1.3.1
  @backstage/plugin-scaffolder-node               0.1.4
  @backstage/plugin-scaffolder-react              1.4.0
  @backstage/plugin-scaffolder                    1.13.1
  @backstage/plugin-search-backend-module-catalog 0.1.1, 0.1.2
  @backstage/plugin-search-backend-module-pg      0.5.6
  @backstage/plugin-search-backend-node           1.2.1, 1.2.2
  @backstage/plugin-search-backend                1.3.1
  @backstage/plugin-search-common                 1.2.3, 1.2.4
  @backstage/plugin-search-react                  1.6.0
  @backstage/plugin-search                        1.3.0
  @backstage/plugin-sentry                        0.5.4
  @backstage/plugin-user-settings                 0.7.3
  @backstage/release-manifests                    0.0.9
  @backstage/test-utils                           1.3.1
  @backstage/theme                                0.3.0, 0.4.0
  @backstage/types                                1.0.2, 1.1.0
  @backstage/version-bridge                       1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by david-christ** [comment]
Small update, just upgraded to Backstage 1.15.0, error still happens.

**Comment by david-christ** [comment]
Update: I figured out that I have to manually register the plugin in `apis.ts`. The documentation shows how to do that for the mock, but not for production. Maybe you could add this to the documentation.

```ts
  createApiFactory({
    api: sentryApiRef,
    deps: {
      configApi: configApiRef,
      discoveryApi: discoveryApiRef,
      identityApi: identityApiRef,
    },
    factory: ({ configApi, discoveryApi, identityApi }) => {
      return new ProductionSentryApi(
        discoveryApi,
        configApi.getString('sentry.organization'),
        identityApi,
      );
    },
  }),
```

**Comment by david-christ** [comment]
There is another error when following the README examples. Setting up the route leads to a `routeRef` error. This time, I could not figure out whether/where there is any manual config missing, or whether that is a genuine error.

I just added the suggested entity route

```ts
        <EntityLayout.Route path="/sentry" title="Sentry">
          <EntitySentryContent />
        </EntityLayout.Route>
```

and am seeing this error:

<img width="1694" alt="Screenshot 2023-07-05 at 3 05 27 pm" src="https://github.com/backstage/backstage/assets/90661517/9240407d-3313-4f2b-8b78-4ee95435c517">

**Comment by grvpandey11** [comment]
@david-christ We followed the documentation as it is and were able to install the plugin at one go.
Did you add proxy and organization name in app-config.yaml?

**Comment by david-christ** [comment]
@grvpandey11 yes, we did add the app-config parameters 😕

**Comment by benjdlambert** [comment]
@david-christ can you try adding `sentryPlugin` to the list of plugins in the `createApp` call and see if that fixes some issues?

You might have `packages/app/src/plugins.ts` where you can just export it like we have [in the main repo](https://github.com/backstage/backstage/blob/99978bb0ab0175047340af9453e86cd9004af8e5/packages/app/src/plugins) or you can add it here as an element in an array [here](https://github.com/backstage/backstage/blob/9a8d34ab36c8ffe435279a2158775a8745a433f9/packages/app/src/App.tsx#L118)

**Comment by david-christ** [comment]
@benjdlambert thanks for your response. Our layout is that same pattern as in backstage. I have added the plugin to `packages/app/src/plugins.ts`, without success. `/catalog/default/component/my-component/sentry` still shows the same error.
