### ISSUE TITLE
🐛 Bug Report: Unable to register existing entities in my GitHub org

### ISSUE THREAD

**Issue by venkatasandeep506** [backstage/backstage#18571]
### 📜 Description

I am getting 404 not found error when i try to register an existing entity by providing the url to the yaml file available in one of my Github org repository. I have created Github app under my org and added the appId, clientId, clientSecret and privateKey values to my app-config.yaml file.e

### 👍 Expected behavior

The entity should have been imported.

### 👎 Actual Behavior with Screenshots

<img width="1778" alt="Screenshot 2023-07-05 at 12 29 31 PM" src="https://github.com/backstage/backstage/assets/121848274/ce2c3b92-a2a5-49f5-b5ea-5ef2d5c765b4">

### 👟 Reproduction steps

Screenshot provided.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by AmbrishRamachandiran** [comment]
@venkatasandeep506 This issue comes because of backstage backend needs GitHub personal access tokens , which will help to access your catalog.yaml file of template.

steps to be followed:
go to github settings -> developer setting -> create the personal access token -> tokens 

once token created  go to app.config.yaml file  in github integration add your token by replacing the 

token: ${GITHUB_TOKEN}

alternative way:

go to following path in cli -> cd backstage/packages/backend 
then use following command

export GITHUB_TOKEN=yourtoken 

hope this should work let me know if any issues

**Comment by venkatasandeep506** [comment]
@AmbrishRamachandiran I have tried this for my personal github account and it works for repositories owned by me but for the repositories owned by my organization, should we also create access token for my organization and use it ? Backstage documentation says we need to configure a GitHub App under the organization and use it.

https://backstage.io/docs/integrations/github/github-apps

My github url for the catalog.yaml file will look like this.

https://github.com/{orgName}/{repoName}blob/master/catalog.yaml

**Comment by AmbrishRamachandiran** [comment]
@venkatasandeep506 Yes !! you have to create a access token for your orgnization to import the existing templates ,

note: github app is only for the login authentication

**Comment by grvpandey11** [comment]
@venkatasandeep506 You should be owner of the organization than only your GitHub token will work.

**Comment by benjdlambert** [comment]
> note: github app is only for the login authentication

You can use a github app for reading from organizations the app is installed into too. https://backstage.io/docs/integrations/github/github-apps/#including-in-integrations-config

**Comment by venkatasandeep506** [comment]
can we store the private key for github app as an environment variable and use it while running instead of using $include as this method is trying to fetch the app credentials during the build process ?

**Comment by benjdlambert** [comment]
@venkatasandeep506 yes - just be sure that the it's well formed as env variables can be a bit tricky - but it's possible.

**Comment by jobin-mathew** [comment]
Is this issue resolved for you @venkatasandeep506

**Comment by venkatasandeep506** [comment]
Yes @jobin-mathew 
It is resolved now. Thanks.

**Comment by jobin-mathew** [comment]
> Yes @jobin-mathew It is resolved now. Thanks.

How? I also faced same issue. Only PAT works. 
App token not working, I gave the configs like this https://backstage.io/docs/integrations/github/github-apps/#including-in-integrations-config

Can you please help @venkatasandeep506

**Comment by jobin-mathew** [comment]
My configurations is like below.

  github:
    - host: github.com
      apps:
        - appId: ${AUTH_ORG_APP_ID}
          clientId: ${AUTH_ORG_CLIENT_ID}
          clientSecret: ${AUTH_ORG_CLIENT_SECRET}
          privateKey: ${AUTH_ORG1_PRIVATE_KEY}
          webhookSecret: ${AUTH_ORG_WEBHOOK_SECRET}

**Comment by venkatasandeep506** [comment]
hi @jobin-mathew 

I have created a GIthub app and configured it this way in the app-config.yaml file.
Note : `GITHUB_APP_PRIVATE_KEY` is the private key value in an environment variable in a single line with `\n` as separator between lines.

```
integrations:
  github:
    - host: github.com
      apps:
        - appId: ${GITHUB_APP_ID}
          clientId: ${GITHUB_APP_CLIENT_ID}
          clientSecret: ${GITHUB_APP_CLIENT_SECRET}
          webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
          privateKey: |
            ${GITHUB_APP_PRIVATE_KEY}
```
