### ISSUE TITLE
🚀 Feature: Provide an option to disable refresh cycle in catalog processing

### ISSUE THREAD

**Issue by taras** [backstage/backstage#18588]
### 🔖 Feature description

[`setProcessingIntervalSeconds`](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/CatalogBuilder.ts#L220C3-L220C31) control `how often entities should be processed.` but it doesn't provide an option to disable the refresh cycle altogether. I can set it to some crazy high number, but we'd like to disable it altogether.

### 🎤 Context

Our ingestion systems don't use the processing loop for asynchronous operations. We remove the URLReaderProcessor, so utilizing the processing loop to read external sources is impossible in our setup. Even though there is no work to do, the processing loop spins continuously, processing entities that do not need to be refreshed. The only way that they'll be refreshed is via an event. 

### ✌️ Possible Implementation

Provide an option to disable refresh loop or pass infinity to setProcessingIntervalSeconds.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
It's probably sane to still have this processing loop set, events are not guaranteed in all cases right? But I understand the request to be able to start the processing engine, but maybe not the re-queueing  behaviour after an entity has been picked up for processing.

**Comment by taras** [comment]
We take of synchronizing missed events with daily incremental ingestion. The event ingestion is built on top of incremental ingestion so the same entity provider is ingesting events and synchronizing to make sure nothing is missed. It's working very well. It's pretty much real time. It's ingested faster than it takes to switch tabs. We want to keep it that way by removing unnecessary work from the processing loop.

**Comment by benjdlambert** [comment]
OK - so it looks like the behaviour here then is after processing, don't re-add it to the queue? Entities still need to be processed for stitching etc. I wonder what the implementation looks like as the `refresh_state` table contains the next timestamp things need to be processed at, and you can't just remove something from the `refresh_state` table as it will cascade delete the entity everywhere.

**Comment by Rugvip** [comment]
Wanna mention that a potential way forward here is to flip around the interval decision to have it be made by the processors instead, which we've discussed before. Basically a processor would emit a result along with optionally requesting a time in the future for the next refresh, with the min of all requested intervals being used. This does mean that the processing interval needs to be configured per processor instead, but it also means that we'll automatically not trigger any refreshes when no polling processor is involved.

**Comment by taras** [comment]
That would work well IMO

**Comment by pjungermann** [comment]
> but it also means that we'll automatically not trigger any refreshes when no polling processor is involved.

I guess you think about static Location entities (from config) and those added manually, right?

Those could be handled in a similar fashion. E.g., the option to configure a refresh schedule for Location entities from the config as well as for manually registered ones. For the latter, it could even be possible to allow a custom selection when you register them (even though, I would assume that most orgs would like to have one value there).
