### ISSUE TITLE
🚀 Feature: Copy only commands in docs

### ISSUE THREAD

**Issue by JunedKhan101** [backstage/backstage#18602]
### 🔖 Feature description

This is more closer to a small enhancement for docs instead of a feature.

When you copy a bash command it copies the '$' as well.
Can we make modifications such that it copies only the command and not the '$' sign.

![Screenshot (6)](https://github.com/backstage/backstage/assets/47941768/e4750ff7-5b1b-4d09-879e-b77256ae2a5a)

Not sure if its possible or even necessary, feel free to close the issue if thats the case.

### 🎤 Context

The user has to get rid of the '$' sign separately which is a small extra effort. It'd be great if the copy icon doesn't copy the '$' sign but just the command.

### ✌️ Possible Implementation

Not sure, Need to do R&D for this.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@JunedKhan101 this sounds like it would be good to have! If you can come up with a fix for this would be great :pray:

**Comment by JunedKhan101** [comment]
@benjdlambert Do you know how can I view docs on my local dev setup? I have a possible fix for this and if it works I shall create a PR.

**Comment by awanlin** [comment]
Hi @JunedKhan101, it's not super obvious but you'll find the information you are looking for in the `microsite` folder here: https://github.com/backstage/backstage/tree/master/microsite. Basically navigate to that folder in your local copy, then run `yarn install`, and then `yarn start` which will give you a local copy of the backstage.io site 🚀

**Comment by JunedKhan101** [comment]
@awalin The fix that I tested didn't work. Do you know where the code of the copy code function is written?

**Comment by awanlin** [comment]
I think it's built in functionality of Docusaurus just adding that to code blocks: https://docusaurus.io/docs/markdown-features/code-blocks. For reference here is the MarkDown file for the example you used: https://github.com/backstage/backstage/blob/master/docs/getting-started/contributors.md?plain=1#L44

**Comment by Ash-KODES** [comment]
Hey, @JunedKhan101 Can I work on this ? 
I trying to get involved in the backstage project, and I think it's a simple one.

**Comment by JunedKhan101** [comment]
@Ash-KODES Go for it.

**Comment by benjdlambert** [comment]
@Ash-KODES assigned! :pray:

**Comment by efenner-cambia** [comment]
bump

**Comment by vinzscam** [comment]
I guess the simplest way would be to just remove the dollar from the docs

**Comment by efenner-cambia** [comment]
@Ash-KODES is this still on your radar?

**Comment by Ash-KODES** [comment]
@efenner-cambia I will do it,on it

**Comment by Ash-KODES** [comment]
Is this fixed,i am not able to reproduce it,didnt found any $ in docs ? @efenner-cambia  @vinzscam

**Comment by camilaibs** [comment]
Hi @Ash-KODES 👋🏻 , we did a recent cleaning but it still needs fixing
Here is an example:https://backstage.io/docs/deployment/heroku

**Comment by Ash-KODES** [comment]
I didnt find a relevant tag that can help only copy command and neglect `$`,so i just removed the dollar,but the now the issue is ,the places (eg :https://backstage.io/docs/deployment/k8s) where we show command along with with its output,how can we differentiate between that ? any suggestions

**Comment by tudi2d** [comment]
It would be ok to leave them for now. If you have ideas to better solve this feel free to suggest them!
