### ISSUE TITLE
🐛 Bug Report: [docs] @backstage/plugin-events-node needs to be installed to import EventBroker

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [backstage/backstage#18606]
### 📜 Description

https://github.com/backstage/backstage/blob/master/plugins/events-backend/README.md#installation should be updated to install @backstage/plugin-events-node too as https://github.com/backstage/backstage/blob/26125da35e6f76284076e18dc23c238b071c8763/plugins/events-backend/README.md?plain=1#L44-L44 needs that dependency to work

### 👍 Expected behavior

Docs should mention the installation of @backstage/plugin-events-node

### 👎 Actual Behavior with Screenshots

Docs doesn't mention the installation of @backstage/plugin-events-node

### 👟 Reproduction steps

See https://github.com/backstage/backstage/blob/26125da35e6f76284076e18dc23c238b071c8763/plugins/events-backend/README.md?plain=1#L44

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@SayakMukhopadhyay do you want to fix the docs for this? :pray:

**Comment by SayakMukhopadhyay** [comment]
Yep, just opened #18684
