### ISSUE TITLE
🚀 Feature: Export EntityAutocompletePicker to use in custom filters

### ISSUE THREAD

**Issue by roman-shandurenko** [backstage/backstage#18600]
### 🔖 Feature description

Export [EntityAutocompletePicker](https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/components/EntityAutocompletePicker/EntityAutocompletePicker.tsx) from the catalog so one can implement custom filters without copy-pasting/duplication of components within one's project.

### 🎤 Context

I want to implement a custom view with a drop-down list to select components from the catalog. I'd like to have the same UX as the filter drop-downs of the catalog page, where you can use both checkboxes and search by text.

I see the catalog uses [EntityAutocompletePicker](https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/components/EntityAutocompletePicker/EntityAutocompletePicker.tsx) to implement the filters, but that component isn't exported from the module.

I believe it would really make it easy to implement custom filters for different components/entities.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by roman-shandurenko** [comment]
Another request from Discord: https://discord.com/channels/687207715902193673/687235481154617364/1122913151680249967

**Comment by alper98** [comment]
Bump ! Want Want Want!

**Comment by freben** [comment]
Leaving this open to contribution!

**Comment by namco1992** [comment]
@freben I also hit this today. Pls assign this to me and I will create a PR shortly, thanks!
