### ISSUE TITLE
🚀 Feature: Phase-Out Items on Tech Radar

### ISSUE THREAD

**Issue by msvechla** [backstage/backstage#18616]
### 🔖 Feature description

Add the possibility to "phase-out" or "hide" specific `RadarItems` from the Tech Radar.
It should be possible to filter the radar based on the phased-out state then as well.

Additionally all phased-out items could be shown in a simple table-view below the radar.

### 🎤 Context

Over time the tech-radar grows as more and more items get tracked.

This can be overwhelming and looking at a radar with many items. Especially if some of the items did not receive an update for a long time and have already been well-established in the company.

Instead of simply deleting established items from the radar, it would be nice to be able to phase them out in some way, which hides them from the main graph. This way the main overview would stay clean and we could still have the full history of all `RadarItems` available

Ideally there would be a filter to show these phased-out items or not.
Also all phased-out items could be shown below the radar in a simple table view or similar.

### ✌️ Possible Implementation

Add a new field like `phasedOut` to the [RadarEntry](https://backstage.io/docs/reference/plugin-tech-radar.radarentry).

Another idea would be to add a new [MovedState](https://backstage.io/docs/reference/plugin-tech-radar.movedstate/) like `PhasedOut`, that will trigger this behaviour, if `PhasedOut` is the most recent state in the [timeline](https://backstage.io/docs/reference/plugin-tech-radar.radarentry.timeline).

I am open for other suggestions here of course.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by msvechla** [comment]
Thanks for your quick reply!

Let me quote the description of Thoughtworks, one of the first companies to publish such a radar:

> The Radar represents technologies that are currently on our mind. Given how fast technology is advancing, the default rule is that blips only appear on the Radar for one edition unless they move rings. However, members of the Thoughtworks Technology Advisory Board (TAB) can always make an argument to keep a blip, for example when something noteworthy has happened warranting a refresh of the writeup. Older blips remain searchable under the full A-Z index.


> We think it’s important to keep older blips in the index for completeness and visibility, but please be aware that we’re not updating them. In some cases, Thoughtworks teams may continue to work with and recommend these technologies; in others, the advice could be outdated. If you’re looking at a blip from our archive, do keep this in mind.

See also: https://www.thoughtworks.com/en-de/radar/faq-and-more

Maybe this gives a bit more context.

For us it would not be just things on hold, also things in adopt that have been there for many years.

E g. "containers" to package and run your application is in adopt for many years and no one is disputing this anymore. It's already in our DNA. Such items will clutter the radar, but it will still be beneficial to reference them when required.

**Comment by sennyeya** [comment]
Interesting, thanks for sharing! The Backstage tech radar is based off of Zalando, https://opensource.zalando.com/tech-radar/, (which seems to be based off of the older Thoughtworks tech radar). Taking a look through [their repository](https://github.com/zalando/tech-radar/tree/master) and their [tech radar](https://opensource.zalando.com/tech-radar/), it seems like they keep their tech radar filled with older "Adopted" items. Though, I agree it makes it cluttered and adding new technologies would exacerbate that problem.

I would push for this to be created as a new ring, maybe something like `Recommended`/`Use` and then we'd just need to add a `visibility` toggle in the upstream definition. 

I also really like your idea of a table/search view for these items/all items, similar to Thoughtworks'.

Is this something you could contribute? I can take a stab if not.

**Comment by msvechla** [comment]
Thanks a lot for the feedback, your approach seems valid!

Unfortunately I will not have time to contribute right now, so if you want to take a stab at it that would be awesome!

**Comment by sennyeya** [comment]
Hey @msvechla, working on this a little today. Can you take a look at https://pr-18762-deployment-31570-backstage.app.uffizzi.com/tech-radar/radar and https://pr-18762-deployment-31570-backstage.app.uffizzi.com/tech-radar/search and let me know your thoughts? Still have to clean up the PR quite a bit 😅 , but wanted to get early feedback.

**Comment by msvechla** [comment]
Great! Unfortunately I can not access the  environment. I get a 503 there at the moment

**Comment by sennyeya** [comment]
@msvechla That's slightly annoying, here's the full like from the PR, https://app.uffizzi.com/github.com/backstage/backstage/pull/18762. Try navigating to "Tech Radar" and then the two tabs on that screen.

The testing data I have is a hidden ring named "USE" and an item called "Docker" in that "USE" ring.

**Comment by msvechla** [comment]
Perfect, that looks exactly like what we needed! Thanks a lot for the fast Implementation!

**Comment by elizabethsjudd** [comment]
Did this ever get implemented? It looks like work was being done but I can't tell if it was ever released.
