### ISSUE TITLE
🐛 Bug Report: OAuthApi.getAccessToken breaks session with Microsoft auth

### ISSUE THREAD

**Issue by dylanjustice** [backstage/backstage#18619]
### 📜 Description

I tried to use the oauthApiRef in my plugin. I have my App Registration set up with permissions to openid, offline_access, profile, User.Read, and user_impersionation for our xMatters app registration.
In my api client class, I'm passing the microsoftAuthApiRef as a dependency
```ts
/** @public */
export const xmattersPlugin = createPlugin({
  id: 'xmatters',
  apis: [
    createApiFactory({
      api: xMattersApiRef,
      deps: {
        discoveryApi: discoveryApiRef,
        configApi: configApiRef,
        fetchApi: fetchApiRef,
        oauthApi: microsoftAuthApiRef,
      },
      factory: ({ configApi, discoveryApi, fetchApi, oauthApi }) =>
        XMattersClient.fromConfig(configApi, {
          discoveryApi,
          fetchApi,
          oauthApi,
        }),
    }),
  ],
});
```
Then in my request, I use OAuthApi.getAccessToken to request a token for the user_impersionation scope.
```ts
  private async findByUrl<T>(url: string): Promise<T> {
    const token = await this.config.oauthApi.getAccessToken('https://my.hosted.xmatters.com/user_impersonation');

    const options = {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${token}`,
      },
    };
    const response = await this.request(url, options);
    return response.json();
  }
  ```
This method gets the token, but the API request to xmatters fails with Unable to convert token to JSON.
Additionally, when I refresh my page in backstage, I'm kicked out to the login page with an error "The Microsoft provider is not configured to support sign-in".

### 👍 Expected behavior

The API request to the third party succeeds. And calling `oauthApi.getAccessToken` should return an access token using the assertion from the user's identity without changing the audience of the session token.

### 👎 Actual Behavior with Screenshots

The API request to the 3rd party fails as unauthorized. Response is `Unable to convert token to JSON`. When refreshing the page, the user is kicked to the login screen with the message `The Microsoft provider is not configured to support sign-in`. 

### 👟 Reproduction steps

Reproducing will require a 3rd party api secured with Azure AD oauth authentication, and backstage will need to be using the same.
1. App registrations in Azure portal for both apps
2. `user_impersonation` scope created for the third party api under Expose an API.
3. Add permission to `user_impersonation` scope to backstage app registration
4. Use `microsoftAuthApiRef.getAccessToken('https://my-third-party/user_impersonation')` to get the token in the backstage environment 
5. Refresh the page.

### 📃 Provide the context for the Bug.

This issue stemmed from this discussion: https://github.com/backstage/backstage/discussions/18584
It sounds like I'm not the only one having trouble with it. We secure all of our tools internally with Azure AD. I'd really like to be able to use OAuth to delegate access to the data through backstage. Hopefully, there is just something I'm missing!

I have also tried using the @azure/msal-node package to acquire the token without luck. Seems to be issues with the signing key, or the algorithm. 
`AADSTS5002730: Invalid JWT token. Unsupported key for the signing algorithm.\r\nTrace ID: 1e5d9ec0-5f45-4296-858f-79b8d0803600\r\nCorrelation ID: 79d962f2-af7a-4c53-9a2f-46eb18a7ca23\r\nTimestamp: 2023-07-05 13:59:59Z",`

`AADSTS50013: Assertion failed signature validation. [Reason - Key was found, but use of the key to verify the signature failed.`

### 🖥️ Your Environment

OS:   Windows_NT 10.0.19044 - win32/x64
node: v16.16.0
yarn: 1.22.19
cli:  0.22.8 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                          1.4.0
  @backstage/backend-app-api                       0.4.4
  @backstage/backend-common                        0.19.0
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.3
  @backstage/backend-tasks                         0.5.3
  @backstage/catalog-client                        1.4.2
  @backstage/catalog-model                         1.4.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.1
  @backstage/cli                                   0.22.8
  @backstage/config-loader                         1.3.1
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.8.1
  @backstage/core-components                       0.13.2
  @backstage/core-plugin-api                       1.5.2
  @backstage/dev-utils                             1.0.16
  @backstage/errors                                1.2.0
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.4
  @backstage/integration-react                     1.1.14
  @backstage/integration                           1.5.0
  @backstage/plugin-adr-backend                    0.3.4
  @backstage/plugin-adr-common                     0.2.10
  @backstage/plugin-adr                            0.6.2
  @backstage/plugin-api-docs                       0.9.5
  @backstage/plugin-app-backend                    0.3.46
  @backstage/plugin-auth-backend                   0.18.4
  @backstage/plugin-auth-node                      0.2.15
  @backstage/plugin-catalog-backend-module-azure   0.1.17
  @backstage/plugin-catalog-backend-module-github  0.3.1
  @backstage/plugin-catalog-backend-module-msgraph 0.5.5
  @backstage/plugin-catalog-backend                1.10.0
  @backstage/plugin-catalog-common                 1.0.14
  @backstage/plugin-catalog-graph                  0.2.31
  @backstage/plugin-catalog-import                 0.9.9
  @backstage/plugin-catalog-node                   1.3.7
  @backstage/plugin-catalog-react                  1.7.0
  @backstage/plugin-catalog                        1.11.2
  @backstage/plugin-events-node                    0.2.7
  @backstage/plugin-github-actions                 0.6.0
  @backstage/plugin-home-react                     0.1.0
  @backstage/plugin-home                           0.5.3
  @backstage/plugin-org                            0.6.9
  @backstage/plugin-permission-common              0.7.6
  @backstage/plugin-permission-node                0.7.9
  @backstage/plugin-permission-react               0.4.13
  @backstage/plugin-proxy-backend                  0.2.40
  @backstage/plugin-scaffolder-backend             1.15.0
  @backstage/plugin-scaffolder-common              1.3.1
  @backstage/plugin-scaffolder-node                0.1.4
  @backstage/plugin-scaffolder-react               1.5.0
  @backstage/plugin-scaffolder                     1.14.0
  @backstage/plugin-search-backend-module-catalog  0.1.2
  @backstage/plugin-search-backend-module-pg       0.5.7
  @backstage/plugin-search-backend-module-techdocs 0.1.2
  @backstage/plugin-search-backend-node            1.2.2
  @backstage/plugin-search-backend                 1.3.2
  @backstage/plugin-search-common                  1.2.4
  @backstage/plugin-search-react                   1.6.2
  @backstage/plugin-search                         1.3.2
  @backstage/plugin-sonarqube-backend              0.2.0
  @backstage/plugin-sonarqube-react                0.1.6
  @backstage/plugin-sonarqube                      0.7.0
  @backstage/plugin-tech-radar                     0.6.5
  @backstage/plugin-techdocs-backend               1.6.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.14
  @backstage/plugin-techdocs-node                  1.7.2
  @backstage/plugin-techdocs-react                 1.1.7
  @backstage/plugin-techdocs                       1.6.4
  @backstage/plugin-user-settings                  0.7.4
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.0
  @backstage/theme                                 0.3.0, 0.4.0
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@jamieklassen I know that you were doing some tinkering around in this area recently, is there anything that stands out?

**Comment by jamieklassen** [comment]
I don't have a strong theory for why this is happening. The story that plays out as I read this is something like:
1. xMatters plugin requests `https://my-third-party/user_impersonation`-scoped access token (stored in memory) with refresh token (stored in cookie)
1. refreshing the page prompts a call to `/api/auth/microsoft/refresh` with no `scope` parameter -- so microsoft gives an access token for the same scope (just `user_impersonation` with no microsoft graph privileges, so inadequate for sign-in) as above, instead of the default scopes required for sign-in:
    https://github.com/backstage/backstage/blob/083a4022e573f993c65f596ee77d4f9526136c68/packages/core-app-api/src/apis/implementations/auth/microsoft/MicrosoftAuth.ts#L59-L65

If it's accurate, this goes a little ways to explaining the "kicked out on refresh" symptom, but not the "Unable to convert token to JSON" symptom -- could that one be xMatters-specific? I'm feeling out of my depth here -- I only skimmed some docs about the `user_impersonation` scope while I was putting together #16323, and kinda dreading that it may have some special semantics that I never understood.

As for getting kicked out on refresh, it would be ideal if we could make sure that the call to `/api/auth/microsoft/refresh` that occurs on refresh includes the correct scopes for sign-in; I didn't think too carefully about how to do this properly the first time around because it involved reasoning about a few different contexts at once:
* [MicrosoftAuth](https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/apis/implementations/auth/microsoft/MicrosoftAuth.ts) depends on
* [OAuth2](https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/apis/implementations/auth/oauth2/OAuth2.ts) depends on
* [RefreshingAuthSessionManager](https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/lib/AuthSessionManager/RefreshingAuthSessionManager.ts) depends on
* [DefaultAuthConnector](https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/lib/AuthConnector/DefaultAuthConnector.ts)

And this whole chain gets invoked by something else in the frontend on page load (which also doesn't immediately come to mind right now)... maybe there's a way to thread the `defaultScopes` through all those dependencies at the right moment, but it's not jumping out at me.

Wish I could be more helpful off the top of my head, but I think I'd have to carefully follow the steps and do some learning to properly reproduce this. I'm willing to do this, I just have a few other priorities to take care of right at the moment; can't make promises but I'd loosely estimate that I can pick this up in the next couple weeks.

**Comment by dylanjustice** [comment]
It's very possible the invalid token is a symptom of the xmatters api. I haven't taken the time to prove out another app connecting to xmatters with oauth. I wanted to try connecting to sonarqube with oauth as well so I could request those permissions this week to see if I can at least access the service with the token.
I thought it may have something to do with #18043, but it's just a hunch.
I'm not attached to the `user_impersonation` scope if that could be an issue. My org adds it by default on an app registration for AD access. At a glance, it looks like that scope is used for on-behalf-of access, which is the intent. 

Looking through the OAuth code, it seems like `getAccessToken` overwrites the session token. Since the token returned is for a new audience not including the previous (graph) scopes, I assume that's breaking the session.

**Comment by alper98** [comment]
Was this solved? we have the same problem

**Comment by jamieklassen** [comment]
kinda the same as #20608 but this issue is better

**Comment by waqasali47** [comment]
I have the same problem as well.

**Comment by camilaibs** [comment]
Hello, Is it still possible to reproduce the error in the recent next release? Just checking to see if it's already been fixed 🙂

**Comment by alper98** [comment]
@camilaibs i just bumped to `1.20.3` and face no issues! Awesome :)

**Comment by dylanjustice** [comment]
I can also confirm the redirect issue has been corrected in the latest release. I still get a 401 from the 3rd party but that sounds like a _me_ problem and not a backstage problem. Closing the issue.
