### ISSUE TITLE
🐛 Bug Report: `orphanStrategy: 'delete'` removes conflicted entities

### ISSUE THREAD

**Issue by jbolda** [backstage/backstage#18610]
### 📜 Description

It is up for debate if this is considered a bug, but at the very least we might consider it unexpected functionality. With the orphan strategy set to `delete` and we have a conflicted entity, the original entity is deleted when the orphan strategy task runs. This seems at least partially related to #17083.

### 👍 Expected behavior

It seems that orphans are considered separately from conflicted entities and that the orphan strategy should not delete conflicted entities.

### 👎 Actual Behavior with Screenshots

The scheduled ingestion process within our Backstage instance runs once a day. If the related files are resolved such that there is no conflict, a scheduled ingestion process appears properly resolve the entities. If the orphan strategy task runs prior to ingestion, there is a period where this entity is completely removed until the next ingestion. We do have tests reproducing this behavior.

### 👟 Reproduction steps

With a sufficiently long scheduled ingestion process to allow the orphan strategy task to run:

1. Create a file that adds an entity to the catalog
2. Run a scheduled ingestion
3. Create a second file that adds the same entity to the catalog
4. Wait for the orphan cleanup task to run
5. After it runs, observe the entity has been deleted
6. Next scheduled ingestion should ingest the entity again

### 📃 Provide the context for the Bug.

This has resulted in some confusing situations as the entity conflict situation tends to be opaque to the user. It seems as if an entity simply disappears, and then a day later it appears again. If the conflict goes unnoticed, it seems to "loop" where an orphan strategy will delete the entity, the next ingestion will bring it back into the catalog, the ingest afterward will mark it conflicted again, and the orphan strategy will delete it; rinse and repeat.

### 🖥️ Your Environment

```
OS:   Darwin 22.5.0 - darwin/arm64
node: v16.20.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.14.1

Dependencies:
  @backstage/app-defaults                                        1.3.1
  @backstage/backend-app-api                                     0.4.3
  @backstage/backend-common                                      0.18.5
  @backstage/backend-dev-utils                                   0.1.1
  @backstage/backend-plugin-api                                  0.5.2
  @backstage/backend-tasks                                       0.5.2
  @backstage/catalog-client                                      1.4.1
  @backstage/catalog-model                                       1.3.0
  @backstage/cli-common                                          0.1.12
  @backstage/cli-node                                            0.1.0, 0.1.1
  @backstage/cli                                                 0.22.8, 0.22.7
  @backstage/config-loader                                       1.3.0, 1.3.1
  @backstage/config                                              1.0.7, 1.0.8
  @backstage/core-app-api                                        1.8.0
  @backstage/core-components                                     0.13.1
  @backstage/core-plugin-api                                     1.5.1
  @backstage/dev-utils                                           1.0.15
  @backstage/errors                                              1.1.5, 1.2.0
  @backstage/eslint-plugin                                       0.1.3
  @backstage/integration-aws-node                                0.1.3
  @backstage/integration-react                                   1.1.13
  @backstage/integration                                         1.4.5, 1.5.0
  @backstage/plugin-api-docs                                     0.9.3
  @backstage/plugin-app-backend                                  0.3.45
  @backstage/plugin-auth-backend                                 0.18.3
  @backstage/plugin-auth-node                                    0.2.14
  @backstage/plugin-catalog-backend-module-github                0.3.0
  @backstage/plugin-catalog-backend-module-incremental-ingestion 0.3.2
  @backstage/plugin-catalog-backend-module-unprocessed           0.1.0
  @backstage/plugin-catalog-backend                              1.9.1
  @backstage/plugin-catalog-common                               1.0.13
  @backstage/plugin-catalog-graph                                0.2.30
  @backstage/plugin-catalog-import                               0.9.8
  @backstage/plugin-catalog-node                                 1.3.6
  @backstage/plugin-catalog-react                                1.6.0
  @backstage/plugin-catalog                                      1.11.0
  @backstage/plugin-cost-insights-common                         0.1.1
  @backstage/plugin-cost-insights                                0.12.7
  @backstage/plugin-events-backend-module-github                 0.1.7
  @backstage/plugin-events-backend                               0.2.6
  @backstage/plugin-events-node                                  0.2.6
  @backstage/plugin-github-actions                               0.5.18
  @backstage/plugin-github-issues                                0.2.7
  @backstage/plugin-graphiql                                     0.2.50
  @backstage/plugin-graphql-voyager                              0.1.3
  @backstage/plugin-org                                          0.6.8
  @backstage/plugin-permission-common                            0.7.5
  @backstage/plugin-permission-node                              0.7.8
  @backstage/plugin-permission-react                             0.4.12
  @backstage/plugin-proxy-backend                                0.2.39
  @backstage/plugin-scaffolder-backend                           1.14.0
  @backstage/plugin-scaffolder-common                            1.3.0
  @backstage/plugin-scaffolder-node                              0.1.3
  @backstage/plugin-scaffolder-react                             1.4.0
  @backstage/plugin-scaffolder                                   1.13.1
  @backstage/plugin-search-backend-module-catalog                0.1.1
  @backstage/plugin-search-backend-module-pg                     0.5.6
  @backstage/plugin-search-backend-module-techdocs               0.1.1
  @backstage/plugin-search-backend-node                          1.2.1
  @backstage/plugin-search-backend                               1.3.1
  @backstage/plugin-search-common                                1.2.3
  @backstage/plugin-search-react                                 1.6.0
  @backstage/plugin-search                                       1.3.0
  @backstage/plugin-tech-radar                                   0.6.4
  @backstage/plugin-techdocs-backend                             1.6.2
  @backstage/plugin-techdocs-module-addons-contrib               1.0.13
  @backstage/plugin-techdocs-node                                1.7.1
  @backstage/plugin-techdocs-react                               1.1.6
  @backstage/plugin-techdocs                                     1.6.2
  @backstage/plugin-user-settings                                0.7.3
  @backstage/release-manifests                                   0.0.9
  @backstage/test-utils                                          1.3.1
  @backstage/theme                                               0.3.0
  @backstage/types                                               1.0.2, 1.1.0
  @backstage/version-bridge                                      1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
cc @backstage/catalog-maintainers

**Comment by benjdlambert** [comment]
ping @freben here too as this was brought up in the SIG and we thought to bring it up with you when back from vacation :tada:

**Comment by freben** [comment]
Interesting. I'd love to see the reproduction case for it - especially if it's in a unit test form. If you can make a pull request with just a failing test added, it will be easier to try to fix it.

For my understanding, what do you mean here with a conflicting entity? My interpretation of a conflict is that the entity was never written into the database at all in the first place, because an entity existed that had the same kind, namespace, and name. That leads to a database conflict error, so it should not be possible to have two entities with the same ref present to be deleted. So we're probably thinking about slightly different things?

**Comment by camilaibs** [comment]
Ping @backstage/catalog-maintainers

**Comment by Edje-C** [comment]
Hi, we made a fix to something around this problem. Have you noticed the issue persisting?
@jbolda

**Comment by jbolda** [comment]
@Edje-C do you know which version we would expect these changes in?

**Comment by LZING** [comment]
I think I know what the problem is. Suppose I now have a catalog-info on branch A. Then migrate to branch B. Then I will show that the component does not exist in the backstage after clicking unregister. The following error will be reported. Unless the user clicks delete entity in advance options and then re-registers, it will work normally. I think this is rather unreasonable.

`
{"error":{"name":"NotFoundError","message":"Entity component:default/open-source.devops not found"},"request":{"method":"POST","url" :"/refresh"},"response":{"statusCode":404}}`
