### ISSUE TITLE
🐛 Bug Report: External Backend Auth Header Issue

### ISSUE THREAD

**Issue by Blackbaud-CameronBeacham** [backstage/backstage#18622]
### 📜 Description

I am trying to make a request from a .NET core service to backstage's backend on the same host using external backend to backend authentication following [this documentation](https://backstage.io/docs/auth/service-to-service-auth#usage-in-external-callers). However, the JWT I'm sending is failing validation with the following error:
```
{
    "error": {
        "name": "AuthenticationError",
        "message": "\"alg\" (Algorithm) Header Parameter not allowed"
    },
    "request": {
        "method": "POST",
        "url": "/api/scaffolder/v2/tasks"
    },
    "response": {
        "statusCode": 401
    }
}
```
I am creating my JWT exactly as specified in the docs and using the setProtectedHeader on the alg header. I use that JWT to attempt to initiate a backstage task using postman calling `POST api/scaffolder/v2/tasks` with the `Authorization` containing the generated JWT and getting the above error. I copied my JWT generating implementation from the [backend-common code](https://github.com/backstage/backstage/blob/master/packages/backend-common/src/tokens/ServerTokenManager.ts#L151-L160C8) that generates the token for backstage itself so I'm surprised I'm hitting this issue.

I've also added temp logging in the backend-common auth code to log the secret and verified that it is in fact the secret I am setting in the app config under `backend.auth.keys.secret`. I even went as far as to log a token from the token manager, paste that token into postman and then call directly into backstage from the same machine and I get the same error. I did verify that if I get a token from the token manager and then pass it right back into the `TokenManager.authenticate()` that it authenticates successfully. So it seems as though its something to do with the way that backstage is ingesting and passing along the token from the request or using different code to authenticate.

[It looks as though other users are also experiencing this](https://github.com/backstage/backstage/discussions/18137)

### 👍 Expected behavior

Making a request directly to the backend api from the same machine backstage is running on providing a token as specified in [the documentation](https://backstage.io/docs/auth/service-to-service-auth#usage-in-external-callers) should authenticate successfully.

### 👎 Actual Behavior with Screenshots

Here is an example token that I am using with the auth secret: "mysupersecretkey":
`eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWNrc3RhZ2Utc2VydmVyIiwiZXhwIjoxNjg5MDAxNTAyfQ.k35bGWmIYnKSvW4UjjNvqc8KhEr3Rq5SHoGUV8igaRA`

The request fails with a 401 and the following message:

```
{
    "error": {
        "name": "AuthenticationError",
        "message": "\"alg\" (Algorithm) Header Parameter not allowed"
    },
    "request": {
        "method": "POST",
        "url": "/api/scaffolder/v2/tasks"
    },
    "response": {
        "statusCode": 401
    }
}
```

### 👟 Reproduction steps

Following the [Service to Service Auth Documentation](https://backstage.io/docs/auth/service-to-service-auth), setup the proper config to pass in your auth secret and change from the Noop token manager.

Then, I wrote up the following code to generate a token (assuming my `backend.auth.keys.secret` is "bXlzdXBlcnNlY3JldGtleQ==" which is the base64 encoded string for "mysupersecretkey" below)

```javascript
import * as jose from 'jose'

const secret = btoa("mysupersecretkey");
const encoded_secret = new TextEncoder().encode(
  secret,
);
const TOKEN_SUB = 'backstage-server';
let exp = Math.round(new Date().getTime() / 1000) + 3600; // UTC now + 1 hour

const jwt = await new jose.SignJWT({})
  .setProtectedHeader({ alg: 'HS256' })
  .setSubject(TOKEN_SUB)
  .setExpirationTime(exp)
  .sign(encoded_secret);

console.log(jwt);
```

Using the JWT logged from the above code, I create a postman request to `POST <mybackstageserver>/api/scaffolder/v2/tasks` with the Authorization header `Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWNrc3RhZ2Utc2VydmVyIiwiZXhwIjoxNjg5MDAxNTAyfQ.k35bGWmIYnKSvW4UjjNvqc8KhEr3Rq5SHoGUV8igaRA`

This should give you the response: 
```
{
    "error": {
        "name": "AuthenticationError",
        "message": "\"alg\" (Algorithm) Header Parameter not allowed"
    },
    "request": {
        "method": "POST",
        "url": "/api/scaffolder/v2/tasks"
    },
    "response": {
        "statusCode": 401
    }
}
```

### 📃 Provide the context for the Bug.

We have a .NET core service that we are running on the same host as backstage to act as a proxy so that we can enforce our existing service to service authentication and then proxy authenticated requests by generating a JWT to call backstage. However, all proxied requests are failing because of the authorization issue. While the original request does have its own Authorization header, we have intercepting code to remove and replace that auth header with the one that contains the backstage JWT. Also, during my debugging I completely removed the .NET core service from the picture and used postman to make a request directly to backstage and got the same error. 

### 🖥️ Your Environment

```OS:   Darwin 22.5.0 - darwin/arm64
node: v18.16.1
yarn: 1.22.19
cli:  0.22.8 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                                        1.4.0
  @backstage/backend-app-api                                     0.4.4
  @backstage/backend-common                                      0.18.5, 0.19.0
  @backstage/backend-dev-utils                                   0.1.1
  @backstage/backend-plugin-api                                  0.5.3
  @backstage/backend-tasks                                       0.5.3
  @backstage/catalog-client                                      1.4.2
  @backstage/catalog-model                                       1.4.0
  @backstage/cli-common                                          0.1.12
  @backstage/cli-node                                            0.1.1
  @backstage/cli                                                 0.22.8
  @backstage/config-loader                                       1.3.1
  @backstage/config                                              1.0.8
  @backstage/core-app-api                                        1.8.1
  @backstage/core-components                                     0.13.2
  @backstage/core-plugin-api                                     1.5.2
  @backstage/errors                                              1.2.0
  @backstage/eslint-plugin                                       0.1.3
  @backstage/integration-aws-node                                0.1.4
  @backstage/integration-react                                   1.1.14
  @backstage/integration                                         1.5.0
  @backstage/plugin-api-docs                                     0.9.5
  @backstage/plugin-app-backend                                  0.3.46
  @backstage/plugin-auth-backend                                 0.18.4
  @backstage/plugin-auth-node                                    0.2.15
  @backstage/plugin-azure-devops-backend                         0.3.25
  @backstage/plugin-azure-devops-common                          0.3.0
  @backstage/plugin-azure-devops                                 0.3.1
  @backstage/plugin-catalog-backend-module-azure                 0.1.17
  @backstage/plugin-catalog-backend-module-incremental-ingestion 0.3.3
  @backstage/plugin-catalog-backend                              1.10.0
  @backstage/plugin-catalog-common                               1.0.14
  @backstage/plugin-catalog-graph                                0.2.31
  @backstage/plugin-catalog-import                               0.9.9
  @backstage/plugin-catalog-node                                 1.3.7
  @backstage/plugin-catalog-react                                1.7.0
  @backstage/plugin-catalog                                      1.11.2
  @backstage/plugin-cost-insights-common                         0.1.1
  @backstage/plugin-cost-insights                                0.12.8
  @backstage/plugin-events-node                                  0.2.7
  @backstage/plugin-github-actions                               0.6.0
  @backstage/plugin-graphiql                                     0.2.51
  @backstage/plugin-home-react                                   0.1.0
  @backstage/plugin-home                                         0.5.3
  @backstage/plugin-org                                          0.6.9
  @backstage/plugin-permission-backend                           0.5.21
  @backstage/plugin-permission-common                            0.7.6
  @backstage/plugin-permission-node                              0.7.9
  @backstage/plugin-permission-react                             0.4.13
  @backstage/plugin-proxy-backend                                0.2.40
  @backstage/plugin-scaffolder-backend                           1.15.0
  @backstage/plugin-scaffolder-common                            1.3.1
  @backstage/plugin-scaffolder-node                              0.1.4
  @backstage/plugin-scaffolder-react                             1.5.0
  @backstage/plugin-scaffolder                                   1.14.0
  @backstage/plugin-search-backend-module-catalog                0.1.2
  @backstage/plugin-search-backend-module-pg                     0.5.7
  @backstage/plugin-search-backend-module-techdocs               0.1.2
  @backstage/plugin-search-backend-node                          1.2.2
  @backstage/plugin-search-backend                               1.3.2
  @backstage/plugin-search-common                                1.2.4
  @backstage/plugin-search-react                                 1.6.2
  @backstage/plugin-search                                       1.3.2
  @backstage/plugin-tech-radar                                   0.6.5
  @backstage/plugin-techdocs-backend                             1.6.3
  @backstage/plugin-techdocs-module-addons-contrib               1.0.14
  @backstage/plugin-techdocs-node                                1.7.2
  @backstage/plugin-techdocs-react                               1.1.7
  @backstage/plugin-techdocs                                     1.6.4
  @backstage/plugin-user-settings                                0.7.4
  @backstage/release-manifests                                   0.0.9
  @backstage/test-utils                                          1.4.0
  @backstage/theme                                               0.4.0
  @backstage/types                                               1.1.0
  @backstage/version-bridge                                      1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by sennyeya** [comment]
This seems to happen because the `PermissionBackend` is calling `identityClient.getIdentity(...)` https://github.com/backstage/backstage/blob/8b6067f885a22d0f92e801aeae9ea8656cb4a54b/plugins/permission-backend/src/service/router.ts#L191 which attempts to use `ES256` to decode the token. https://github.com/backstage/backstage/blob/8b6067f885a22d0f92e801aeae9ea8656cb4a54b/plugins/auth-node/src/DefaultIdentityClient.ts#L76-L78 That's the default for the internal tokens, but the external tokens default to `HS256`. This is causing the error you're getting. 

Changing the token to use `ES256` signing gives me a separate error, `no applicable key found in the JSON Web Key Set`. Querying `http://localhost:7007/api/auth/.well-known/jwks.json` returns 
```
{
	"keys": []
}
```
which seems unexpected and the cause of the new error. This may be because I'm in local development.

@Rugvip Any thoughts on the above?

**Comment by Rugvip** [comment]
The scaffolder backend behaves a bit weirdly here because of backwards compatibility, main piece of that is here:

https://github.com/backstage/backstage/blob/65b8af189ec993ee2ea40415ecfa9b7bfc24fd19/plugins/scaffolder-backend/src/service/router.ts#L244-L245

If you pass in an explicit identity API, that'll be used, and if you use the default implementation that won't support backend tokens. If you are currently passing an identity API to the scaffolder backend then you could either try removing it or provide it with a similar workaround to the one used by the default instance.

You won't be able to generate a user token, they can only be generated by the auth backend during sign-in. The `ES256` tokens are users tokens.

If you hit the permission backend while trying to use service auth then then there's something up with the flow before that. Requests with valid service auth tokens should never be forwarded to the permissions backend.

**Comment by Blackbaud-CameronBeacham** [comment]
We are currently providing identity to the scaffolder because we have a single host configuration. However, I did try providing the `HS256` algorithm in our identity client.

```typescript
  const identity = DefaultIdentityClient.create({ discovery, algorithms: ['ES256', 'HS256'] });
```

That does get me a bit farther (maybe) but now when I make a request from my external service:

```
{
    "error": {
        "name": "AuthenticationError",
        "message": "Unsupported \"alg\" value for a JSON Web Key Set"
    },
    "request": {
        "method": "POST",
        "url": "/api/scaffolder/v2/tasks"
    },
    "response": {
        "statusCode": 401
    }
}
```

**Comment by Blackbaud-CameronBeacham** [comment]
@Rugvip Any ideas given that the solution you proposed didn't work for us?

**Comment by Rugvip** [comment]
@Blackbaud-CameronBeacham the `DefaultIdentityClient` will always throw if it encounters a backend token. From my understanding of your setup you would be able to simply not pass the `identity` option to the scaffolder. If that's not the case could you please elaborate a bit more on your setup?

**Comment by Blackbaud-CameronBeacham** [comment]
@Rugvip Ok it looks like removing the identity client works for backend calls. Can you explain why we don't need the identity client in the scaffolder or point me to some docs on why it would be safe to omit it?

**Comment by nextrevision** [comment]
I'm seeing the same thing when generating a JWT using the script above calling the `/api/catalog/entities` endpoint.

```json
{
  "error": {
    "name": "ResponseError",
    "message": "Request failed with 401 AuthenticationError",
    "response": {
      "size": 0,
      "timeout": 0
    },
    "body": {
      "error": {
        "name": "AuthenticationError",
        "message": "\"alg\" (Algorithm) Header Parameter not allowed"
      },
      "request": {
        "method": "POST",
        "url": "/authorize"
      },
      "response": {
        "statusCode": 401
      }
    },
    "cause": {
      "name": "AuthenticationError",
      "message": "\"alg\" (Algorithm) Header Parameter not allowed"
    }
  },
  "request": {
    "method": "GET",
    "url": "/entities?filter=kind=component"
  },
  "response": {
    "statusCode": 500
  }
}
```

**Comment by hballangan-mdsol** [comment]
Added a PR to fix this issue. Kindly take a look and review
