### ISSUE TITLE
🐛 Bug Report: Package metadata missing

### ISSUE THREAD

**Issue by vergilfromadyen** [backstage/backstage#18639]
### 📜 Description

Some backstage plugins don't have a `repository` object in their package.json while others do. This helps with discoverability  of this repository via `npm docs` and when browsing packages via npmjs.org.

### 👍 Expected behavior

All packages have a `repository` entry in their package.json

### 👎 Actual Behavior with Screenshots

Some backstage plugins don't have a `repository` object in their package.json while others do

### 👟 Reproduction steps

1. Go to https://www.npmjs.com/package/@backstage/plugin-bazaar
2. Check the sidebar
3. It should feature a "Repository" reference like [other Backstage plugins](https://www.npmjs.com/package/@backstage/plugin-catalog-backend-module-openapi/v/0.1.2-next.0?activeTab=dependencies)

### 📃 Provide the context for the Bug.

In this particular case my employer uses a package scanner to check if developers are using suspicious packages, and marks Backstage as suspicious because it's missing a reference to its source code.

I opened a PR #18528 but I'm unable to run yarn install in a Docker container so I cannot complete the PR. Please feel free to use the contents of the PR, with or without attribution.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Thanks for the report and the pull request!

Going forward, we should probably add some code to the Backstage CLI, such that when you use the `new` command it'll look into the root `package.json` and reuse any `homepage` and `repository` settings that are in there, and just fill in the actual relative path of the new thing.
