### ISSUE TITLE
🚀 Feature: Add maxDepth parameter into CatalogGraphCard 

### ISSUE THREAD

**Issue by gsasanelli** [backstage/backstage#18659]
### 🔖 Feature description

From a customization point of view there is no possibility to pass the maxDepth default value to the link "View graph" created by CatalogGraphCard (at line 108 while creating catalogGraphParams no value can be passed for maxDepth).

### 🎤 Context

In our company, there is a large number of component and subcomponent (IE around 407 only for one team) and in this situation if we render the dependency graph without a limit it will never end the rendering or the result can not be read

### ✌️ Possible Implementation

In my idea there are 2 solution:

- use the maxDepth value that is already comping from the Entity configuration (so the Entity dependency graph and the "View graph" button will use the same value)
- introduce a new variable that will be used for the "View graph" case

We prefer the first solution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
This sounds like a sane idea, contributions are welcome! :pray:

**Comment by gsasanelli** [comment]
I'm waiting company authorization to proceed (it should come by next week)

**Comment by tperehinets** [comment]
I would love to work on this one

**Comment by snehaljos** [comment]
@tperehinets  are ou working on this issue?

**Comment by tperehinets** [comment]
yes
