### ISSUE TITLE
🐛 Bug Report: RepoUrlPicker is not checking the owner existence

### ISSUE THREAD

**Issue by gsasanelli** [backstage/backstage#18658]
### 📜 Description

The RepoUrlPicker is not checking the owner existence or availability and while executing his value is the one associated with the token

### 👍 Expected behavior

While choosing the repository owner, if it is not existing, the FE should raise an error

### 👎 Actual Behavior with Screenshots

No check is done and instead of using the owner written by the user a "default" one is used

### 👟 Reproduction steps

Create a template like this:
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: example
  title: Example with RepoUrlPicker 
  description: This is a multicloud example done with Crossplane and Argo pipeline
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.repoUrl }}
        repoUrl: ${{ parameters.repoUrl }}
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
  

Then while filling the parameter, use an unexisting owner, having the integration config for github configured into backend, and at the end the repository initialization will be done on the wrong owner (instead of the "non existing" owner, the token owner will be used)

### 🖥️ Your Environment

I'm using backstage version 1.14.2 but the same happens with last version

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Yeah, I think that theres some room for improvement here. It would be great if the `RepoUrlPIcker` could use your token for the SCM and be able to list the places that you have access to create so that it's an autocomplete box rather than free text. This ensures that the owner already exists, and that you also have read/write access to the org or owner repo already.

**Comment by gsasanelli** [comment]
Ok so instead of checking while the flow is executing are you thinking to add the check while making field validation? Because I was thinking to add the check on the backend side during the flow execution, where it is supposed to have the usable token but maybe it's not the correct place for this kind of check

**Comment by gsasanelli** [comment]
Yes I agree but this means that we need to include the logic on FE to understand if we have to use the integration token or the user token (this logic seems already present in the backend). The worst thing here is that I need to understand how to check the owner existence, I'm not an expert of the single library used to integrate Github/Gitlab/Bitbucket etc.. (and I don't know if the owner concept is spammed on all the platform). In the mean time I'm checking if it's possible for me (I need a company authorization before proceeding) to make the fix and publish it

**Comment by benjdlambert** [comment]
Just coming back to this to give a little more direction on ideas for implementation. Thinking that we should add some more routes to the `scaffolder-backend` that can help surface the available options for each integration.

`/v1/integrations/:provider/orgs` or something like this, could produce a list of available ID's where the scaffolder has write permissions to, either using a provided `github_token` which could come from the user, or using the `GITHUB_TOKEN` in the integrations config.

Each provider has different API's, so I'd suggest that we start simple with like the github API to find out all the orgs that are available to these tokens, and return then in the JSON response and those can be consumed by the `RepoUrlPicker`.
