### ISSUE TITLE
🐛 Bug Report: publish:gitlab:merge-request changes symlinks to files

### ISSUE THREAD

**Issue by gdolfen** [backstage/backstage#18665]
### 📜 Description

In our project we want to add some symlinks through a scaffolding template into a gitlab MR.
We fetch the symlinks byt the fetch:template step and create a MR by the publish:gitlab:merge-request step.
But the result in gitlab is not a symlink. Instead we get a normal file with the target path as content.

### 👍 Expected behavior

The publish:gitlab:merge-request step should publish symlinks

### 👎 Actual Behavior with Screenshots

The fetch:template step works fine. After this step, there is a correct symlink in the temp workdir folder.

### 👟 Reproduction steps

Create a template with this structure:

/template.yaml
/skeleton/mysymlink.lnk

with the following template.yaml
`...
  steps:
    - id: fetch
      name: Fetch
      action: fetch:template
      input:
        url: ./skeleton
    - id: publish
      name: Publish
      action: publish:gitlab:merge-request
      input: ...
`

### 🖥️ Your Environment

Production: Docker, Linux
Local: Windows 10

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Where does the symlink resolve to? I remember that we added some logic in here to make sure that the symlink only resolved to something local inside the template directory, or that we only copy the link when templating to ensure that someone can't create a symlink to `/var/secrets` or whatever, and be able to run the template to get ahold of this folder in the published template.

**Comment by gdolfen** [comment]
In the gitlab repo we have a file "terraform/common/inputs.tf" (this is not existent in the scaffolding temp folder).
And the merge requests adds a symlink to "terraform/dev/common.inputs.tf" with the target "../common/inputs.tf".

**Comment by benjdlambert** [comment]
OK, I wonder if this is actually something to do with the gitlab merge request action itself and it not telling gitlab when creating the files in the merge request that it's a symlink? Could you perhaps test this against github and see if it doesn't work there either? Will help us narrow down where the issue lies.

**Comment by gdolfen** [comment]
Yes, I'll try it against github

**Comment by gdolfen** [comment]
Github is working.
You can reproduce the bug with the template in the following repo:
https://github.com/gdolfen/backstage_symlink_template/tree/main

**Comment by benjdlambert** [comment]
@gdolfen my assumption is that we will need to do something like we do in the github pull request action to see the filemode of the created file in the merge request properly according to if it's a symlink or not.

https://github.com/backstage/backstage/blob/91fd39cd7eaa515590fbbf7476f3b00a0e8f1238/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/githubPullRequest.ts#L285

**Comment by gdolfen** [comment]
There is some work on the gitlab side to implement the feature for pushing symlinks via the api: https://gitlab.com/gitlab-org/gitlab/-/issues/426728
So if this is done, there should be a way to support it in Backstage, too.
