### ISSUE TITLE
🐛 Bug Report: ArgoCD plugin usage results in 500 error

### ISSUE THREAD

**Issue by twanbeeren** [backstage/backstage#18667]
### 📜 Description

I've got the following error when using the argocd plugin in my backstage environment

Request failed with status 500 Invalid character in header content ["Cookie"]

I've followed the [official Roadie documentation](https://roadie.io/backstage/plugins/argo-cd/) to implement the plugin but something is wrong either with the proxy or with my Authentication token..

I'm running backstage in a kubernetes environment

### 👍 Expected behavior

It should see the following argoapplication

![image](https://github.com/backstage/backstage/assets/36261352/1043e1b6-768b-4e55-8a42-f9b85028e7d2)

I've referenced to it with an annotation to the argoapp "scraper-service-test"

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "argocd-test"
  description: "Test argocd plugin"
  annotations:
    github.com/project-slug: Simac-IT-NL-backstage/argo-component-test
    argocd/app-name: scraper-service-test
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "microservices"
```

### 👎 Actual Behavior with Screenshots

When I go in developer mode on the browser I see this

![image](https://github.com/backstage/backstage/assets/36261352/19a43f23-b16f-4618-82f2-cc499cf1b18f)

The logs of the container show me this

```
error Request failed with status 500 Invalid character in header content ["Cookie"] type=errorHandler code=ERR_INVALID_CHAR stack=TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
```

### 👟 Reproduction steps

I created an API token in argocd by generating a new API token on a new account "manager" I created ([the docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/)):

![image](https://github.com/backstage/backstage/assets/36261352/7bd81f7e-ed64-4704-9d27-1c466cb441ec)

(The token usually starts with ey.....)

The account didn't have enough permissions to read the argoapp so I gave the manager account read access. See the docs I used for that [here](https://www.opsmx.com/blog/how-to-configure-rbac-in-argo-cd/)

After that the app was visible on the application view of my account 

![image](https://github.com/backstage/backstage/assets/36261352/042f0221-dda8-47f0-a95d-8262e0b85799)

I added the widgets to the application as stated [here](https://roadie.io/backstage/plugins/argo-cd/) and added the proxy to the configuration. For the argocd server instance I used the service that I can call locally in my cluster

```
proxy:
      '/argocd/api':
        target: https://argocd-server.argocd.svc.cluster.local/api/v1/
        changeOrigin: true
        # only if your argocd api has self-signed cert
        secure: false
        headers:
          Cookie:
            $env: ARGOCD_AUTH_TOKEN
```

I've got a backstage-secrets file with all the secrets and environment variables used by backstage like the ARGOCD_AUTH_TOKEN variable.

Here I added the API token I created before from my manager argocd account. 

I used this format.

![image](https://github.com/backstage/backstage/assets/36261352/47596b03-f02f-49b5-b3fe-87b42a5d7900)

To put it in the backstage-secrets file I base64 encoded the API token and base64 encoded the whole variable.

So it was basically this:
ARGOCD_AUTH_TOKEN=(base64-encoded-'argocd.token=(base64-encoded-token)')

Maybe I did something wrong with encoding of the token which causes the 500 invalid character error. Not encoding at all is not an option because it has to be put in the secrets file and therefore there should be some encoding of the environment variable.

### 📃 Provide the context for the Bug.

I'm trying to implement the argo plugin so we can let developers monitor their own argo application from the main backstage menu

### 🖥️ Your Environment

```
OS:   Linux 5.10.16.3-microsoft-standard-WSL2 - linux/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.22.1 (installed)
backstage:  1.10.0

Dependencies:
  @backstage/app-defaults                          1.1.0
  @backstage/backend-app-api                       0.3.1, 0.4.0, 0.4.1, 0.4.2
  @backstage/backend-common                        0.18.1, 0.18.2, 0.18.3, 0.18.4
  @backstage/backend-dev-utils                     0.1.0, 0.1.1
  @backstage/backend-plugin-api                    0.3.1, 0.4.0, 0.5.0, 0.5.1
  @backstage/backend-tasks                         0.4.2, 0.4.3, 0.5.0, 0.5.1
  @backstage/catalog-client                        1.3.0, 1.3.1, 1.4.0, 1.4.2
  @backstage/catalog-model                         1.1.5, 1.2.0, 1.2.1, 1.3.0, 1.4.0
  @backstage/cli-common                            0.1.11, 0.1.12
  @backstage/cli                                   0.22.1
  @backstage/config-loader                         1.1.8, 1.1.9, 1.2.0
  @backstage/config                                1.0.6, 1.0.7, 1.0.8
  @backstage/core-app-api                          1.4.0
  @backstage/core-components                       0.12.3, 0.12.4, 0.12.5, 0.13.2
  @backstage/core-plugin-api                       1.3.0, 1.4.0, 1.5.0, 1.5.2
  @backstage/errors                                1.1.4, 1.1.5, 1.2.0
  @backstage/integration-aws-node                  0.1.1, 0.1.2
  @backstage/integration-react                     1.1.9
  @backstage/integration                           1.4.2, 1.4.3, 1.4.4, 1.5.0
  @backstage/plugin-api-docs                       0.8.14
  @backstage/plugin-app-backend                    0.3.41
  @backstage/plugin-auth-backend                   0.17.4
  @backstage/plugin-auth-node                      0.2.10, 0.2.11, 0.2.12, 0.2.13
  @backstage/plugin-azure-devops-backend           0.3.22
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.2.7
  @backstage/plugin-catalog-backend                1.7.1
  @backstage/plugin-catalog-common                 1.0.10, 1.0.11, 1.0.12, 1.0.14
  @backstage/plugin-catalog-graph                  0.2.26
  @backstage/plugin-catalog-import                 0.9.4
  @backstage/plugin-catalog-node                   1.3.2
  @backstage/plugin-catalog-react                  1.2.4, 1.3.0, 1.4.0, 1.7.0
  @backstage/plugin-catalog                        1.7.2
  @backstage/plugin-github-actions                 0.5.14
  @backstage/plugin-kubernetes-backend             0.9.3
  @backstage/plugin-kubernetes-common              0.6.0
  @backstage/plugin-kubernetes                     0.7.8
  @backstage/plugin-org                            0.6.4
  @backstage/plugin-permission-common              0.7.3, 0.7.4, 0.7.5, 0.7.6
  @backstage/plugin-permission-node                0.7.4, 0.7.5, 0.7.6, 0.7.7
  @backstage/plugin-permission-react               0.4.10, 0.4.11, 0.4.13, 0.4.9
  @backstage/plugin-proxy-backend                  0.2.35
  @backstage/plugin-scaffolder-backend             1.10.1
  @backstage/plugin-scaffolder-common              1.2.4, 1.2.7
  @backstage/plugin-scaffolder-node                0.1.2
  @backstage/plugin-scaffolder-react               1.0.1
  @backstage/plugin-scaffolder                     1.10.1
  @backstage/plugin-search-backend-module-pg       0.5.2
  @backstage/plugin-search-backend-node            1.1.2
  @backstage/plugin-search-backend                 1.2.2
  @backstage/plugin-search-common                  1.2.1, 1.2.2, 1.2.4
  @backstage/plugin-search-react                   1.4.0
  @backstage/plugin-search                         1.0.7
  @backstage/plugin-tech-radar                     0.6.0
  @backstage/plugin-techdocs-backend               1.5.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.9
  @backstage/plugin-techdocs-node                  1.4.5
  @backstage/plugin-techdocs-react                 1.1.2
  @backstage/plugin-techdocs                       1.4.3
  @backstage/plugin-user-settings                  0.6.2
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.4
  @backstage/theme                                 0.2.16, 0.2.17, 0.2.18, 0.4.0
  @backstage/types                                 1.0.2, 1.1.0
  @backstage/version-bridge                        1.0.3, 1.0.4
Done in 12.07s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by twanbeeren** [comment]
The 500 error normally would mean there would something wrong with my proxy but there error makes it seem like there is an issue with an unrecognizable char in the auth token.

**Comment by joeunlog** [comment]
@twanbeeren Hi! I have same issue.
My error log : Invalid character in header content [\"Cookie\"]
I generate new token but it still getting error. I'm using oauth2-proxy for authorization of backstage.
There is any assumtion about this?
