### ISSUE TITLE
🚀 Feature: <Adding validations to catalog entity details page Rate this entity  feedback form>

### ISSUE THREAD

**Issue by AmbrishRamachandiran** [backstage/backstage#18661]
### 🔖 Feature description

It is best practice to add form validations so that we will get some feedback response from the user without getting it as empty. The rate this entity section in the entity details page allows users to give feedback by clicking the dislike button, but the form doesn't have any validations and accepts empty feedback from users.

![feedback dislike](https://github.com/backstage/backstage/assets/133481507/884d63f2-cf25-4cf2-a64a-a0b9da8ea2b4)

### 🎤 Context

It is best practice to add form validations so that we will get some feedback response from the user without getting it as empty. The rate this entity section in the entity details page allows users to give feedback by clicking the dislike button, but the form doesn't have any validations and accepts empty feedback from users.

### ✌️ Possible Implementation

1.Disable the submit button if form values are empty
2.Show the error message below the checkboxes if none of the values are selected
3.Show the Additional comments box if user select the other checkbox or else not needed
4.Show the error message if comments box are empty 

![image](https://github.com/backstage/backstage/assets/133481507/9ae03201-a213-44e3-893a-e05d47f63bb0)
![image](https://github.com/backstage/backstage/assets/133481507/eb31a5bd-4bb8-4aa4-ac26-0594f88cb883)
![image](https://github.com/backstage/backstage/assets/133481507/6f81ab91-2c80-43e0-933a-cb77f4445499)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by AmbrishRamachandiran** [comment]
Assign this to me i have some work around in my local

**Comment by kuangp** [comment]
@AmbrishRamachandiran assigned to you! Thanks for volunteering to contribute!

I also wanted to mention that this was intentionally implemented as "optional additional feedback" when a user clicked dislike. For implementing validation, it would be nice to allow it to default to optional to preserve the current behavior, with the ability to enforce validation if desired

**Comment by AmbrishRamachandiran** [comment]
@kuangp PR raise please review https://github.com/backstage/backstage/pull/18666
