### ISSUE TITLE
🚀 Feature: Render a custom component beside scaffold form.

### ISSUE THREAD

**Issue by Gianluska** [backstage/backstage#18673]
### 🔖 Feature description

Hey!

We are testing the new scaffolder plugin here at Grupo Boticario. We think that it would be great if the scaffolder plugin start supporting render a custom component inside the scaffold `<Page />`.

### 🎤 Context

We need to render a custom component beside the scaffold form, something like that:

![image](https://github.com/backstage/backstage/assets/47386889/bda65a72-0bfb-4986-b344-90cc34ee9ac1)

Our goal is to show some information about the template while the user is filling the form. To do so, we need to receive the events and data from the form.

I didn't find anything like that on the documentation, so i'm assuming that this feature is not possible on the current version of scaffolder/next.

The good news is that we will love to contribute to backstage with this feature :)).

### ✌️ Possible Implementation

I really think that we can use the [Compound Design Pattern](https://medium.com/@mohandere/react-compound-components-pattern-in-10-mins-c0de9c5aa3c1) on this component.

Resulting in something like that:

```jsx
<ScaffolderPage>
   <ScaffolderHeader>
      <h1>Typescript Component </h1>
      <p>Some description about this template</p>
   </ScaffolderHeader>
   
   <ScaffolderForm> ... </ScaffolderForm>

   <MyCustomComponent />
   
   ...
</ScaffolderPage>
```

Doing so, it would be super easy to make it customizable. :))

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Gianluska** [comment]
Btw, this is a extension of this RFC: #17417.

**Comment by benjdlambert** [comment]
Hmm - I'm feeling that we just take the same approach to how we did the `TaskPage` which allows you to provide your own Page that's going to be rendered and you can implement this however you like ontop of the default plugin. We're thinking of shipping the `scaffolder/next` work after this mainline release tomorrow, so we probably just want to add a prop to the Router that enables us to provide a custom page component.

**Comment by tperehinets** [comment]
Hi! I would like to work on Custom Component. Could you please specify what information about the template you would like to be displayed?

**Comment by Gianluska** [comment]
> Hmm - I'm feeling that we just take the same approach to how we did the `TaskPage` which allows you to provide your own Page that's going to be rendered and you can implement this however you like ontop of the default plugin. We're thinking of shipping the `scaffolder/next` work after this mainline release tomorrow, so we probably just want to add a prop to the Router that enables us to provide a custom page component.

Cool! I don't see any problems with this approach :))

**Comment by Gianluska** [comment]
> Hi! I would like to work on Custom Component. Could you please specify what information about the template you would like to be displayed?

Hey!
So, we want to show some estimated cost data on our custom component and the template data itself aligned with the form input.

We really want to contribute to this feature and it's already on our roadmap, but feel free to join the discussion! :))
