### ISSUE TITLE
🐛 Bug Report: catalog-unprocessed-entities plugin: Filter and column sorting doesn't work

### ISSUE THREAD

**Issue by gracemkas** [backstage/backstage#18694]
### 📜 Description

After installing the catalog-unprocessed-entities plugin and the catalog-backend-module-unprocessed plugin and then navigating to the catalog-unprocessed-entities page, the filter and column sorting doesn't work.
When I try to enter any letters into the filter, I get no results in the unprocessed entities list even though there are items that match those letters.
Column sorting also doesn't work. If I select the arrow next to ENTITYREF, KIND, OWNER, or RAW labels, the order of items doesn't change.

### 👍 Expected behavior

When I type letters into the Filter search bar, I should see results show up that match those letters.
When I click the arrow next to the head of a column, that should sort the column's items.

### 👎 Actual Behavior with Screenshots

When I type letters into the Filter search bar, no items show up. The results are completely empty even though there are items that match the letters.
When I click the arrow next to the head of a column, the list of items stays the same and doesn't get sorted.

### 👟 Reproduction steps

1. Install and configure the [catalog-backend-module-unprocessed plugin](https://github.com/backstage/backstage/tree/v1.15.0/plugins/catalog-backend-module-unprocessed) 
2. Install and configure the [catalog-unprocessed-entities plugin](https://github.com/backstage/backstage/tree/v1.15.0/plugins/catalog-unprocessed-entities)
3. Start your application locally
4. Navigate to [/catalog-unprocessed-entities](http://localhost:3000/catalog-unprocessed-entities)
5. You will need a list of unprocessed entities already showing up under the Failed tab in order to test the filter
6. Type any letter into the Filter search bar to see the filter issue
7. Click the arrow next to the ENTITYREF, KIND, OWNER, or RAW labels to see the column sorting issue

### 🖥️ Your Environment

node: v16.14.2
yarn: 1.22.19
backstage:  1.15.0

Dependencies:
  @backstage/plugin-catalog-backend-module-unprocessed  0.1.0
  @backstage/plugin-catalog-unprocessed-entities: 0.1.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@gracemkas sounds like we should fix this - is this something you want to contribute and help? :pray:

**Comment by freben** [comment]
Also ping @alde

**Comment by KatharinaSick** [comment]
Hey there :slightly_smiling_face: 

We are facing the same issue and unfortunately, we don't have time to take this right now. Would it be okay to [disable search](https://github.com/backstage/backstage/blob/master/plugins/catalog-unprocessed-entities/src/components/FailedEntities.tsx#L129) until somebody has time to look at this bug? If yes, I would open a PR.
