### ISSUE TITLE
🐛 Bug Report: k8s pugin: Cannot read properties of null (reading 'scrollWidth')

### ISSUE THREAD

**Issue by jenil-harness** [backstage/backstage#18691]
### 📜 Description

When clicking on the Kubernetes tab and clicking on the detail view for a pod, the screen errors out with the above error.

### 👍 Expected behavior

Should show details of the pod.

### 👎 Actual Behavior with Screenshots

Failed with the error. Cannot read properties of null (reading 'scrollWidth')
![Screenshot 2023-07-17 at 3 29 36 PM](https://github.com/backstage/backstage/assets/62697923/af73859b-9bac-4354-89ec-1cdc7c6071cb)

### 👟 Reproduction steps

1. Go to the Kubernetes tab.
2. In the list of clusters, expand one of the clusters having pods.
3. In the list of pods, expand the pod details.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by djetelina** [comment]
One of our components has the same issue, but others work, so it's not a global bug.

**Comment by djetelina** [comment]
As far as my confirmation goes, over time it went away, probably due to some upgrade. I cannot replicate it now.

**Comment by benjdlambert** [comment]
@jenil-harness is this still an issue for you? :pray:

**Comment by jenil-harness** [comment]
Not happening for me as well. Closing the issue.
