### ISSUE TITLE
🐛 Bug Report: Techdocs - Navigation and Table of context overlapping in documentation

### ISSUE THREAD

**Issue by max-bojorquez** [backstage/backstage#18695]
### 📜 Description

We are getting ready to release to version 1.16.0, so we upgraded the latest next version. [v1.16.0-next.2](https://github.com/backstage/backstage/releases/tag/v1.16.0-next.2). We checked our backstage and we noticed within the documentation there was overlap between the Navigation and the Table of Context. Appears to be that there's only one column for both information.

### 👍 Expected behavior

Documentation should appear as normal as we have seen before; Navigation on the left and Table Of Context on the right.

### 👎 Actual Behavior with Screenshots

Navigation and Table of context overlapping in documentations

<img width="1563" alt="Screen Shot 2023-07-17 at 8 47 50 AM" src="https://github.com/backstage/backstage/assets/49626447/dafadd14-491b-4907-9bc4-d57f0c8d19ea">

### 👟 Reproduction steps

Create a doc folder and include your documentation in that directory
Create a mkdocs.yaml file and bind it to an entity
Create a catalog-info.yaml file and add that file to your backstage. 

**mkdocs.yaml:**
```
site_name: 'Introduction to Developer Portal'
site_description: 'Getting to know the Developer Portal'

plugins:
  - techdocs-core

nav:
  - How To Contribute: 
      - Documentation: index.md
      - Register Components: registering_components.md
  - Developer Training Resources:
      - Docker: developer_training/docker.md
      - Kubernetes: developer_training/kubernetes.md
      - Git/GitLab: developer_training/git_gitlab.md
      - Selenium: developer_training/selenium.md
      - Appium: developer_training/appium.md
      - Helm: developer_training/helm.md
  - Setting Up Your Local Development Environment:
      - Docker: local_development_environment/docker.md
      - IntelliJ: local_development_environment/intellij.md
      - VSCode: local_development_environment/vscode.md

```

**catalog-info.yaml**

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  x-redeploydocs: 'Done on 02/16/2022'
  name: Introduction_to_Developer_Portal
  description: Learn more about our Developer Portal including how to use and contribute documentation. etc.etc.etc.
  tags:
    - mkdocs
  annotations:
    backstage.io/techdocs-ref: dir:.
    jira/project-key: DET
spec:
  type: website
  lifecycle: production
  owner: TEAM-DevOps_Platform
```
```



### 📃 Provide the context for the Bug.

When i am running things locally on localhost:3000 seems like the issue isn't there, but when we deploy the dev instance with version 1.16.0-next.2 thats where we seem to have the problem. We are trying to get ready for version 1.16.0, but this overlapping issue is stopping us from continueing to upgrade. Although, version 1.16.0 is not yet released we want to prepare for it.


### 🖥️ Your Environment

```
OS:   Darwin 21.6.0 - darwin/x64
node: v16.19.1
yarn: 1.22.19
cli:  0.22.5 (installed)
backstage:  1.16.0-next.2

Dependencies:
  @backstage/app-defaults                          1.4.1-next.1
  @backstage/backend-app-api                       0.4.4, 0.4.5-next.0
  @backstage/backend-common                        0.18.5, 0.19.0, 0.19.1-next.0
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.3, 0.5.4-next.0
  @backstage/backend-tasks                         0.5.3, 0.5.4-next.0
  @backstage/catalog-client                        1.4.2, 1.4.3-next.0
  @backstage/catalog-model                         1.4.0, 1.4.1-next.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.2-next.0
  @backstage/cli                                   0.22.9-next.0
  @backstage/config-loader                         1.3.1, 1.3.2-next.0
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.8.2-next.0
  @backstage/core-components                       0.11.2, 0.13.2, 0.13.3-next.1
  @backstage/core-plugin-api                       1.5.2, 1.5.3-next.0
  @backstage/errors                                1.2.0, 1.2.1-next.0
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.4, 0.1.5-next.0
  @backstage/integration-react                     1.1.15-next.1
  @backstage/integration                           1.5.0, 1.5.1-next.0
  @backstage/plugin-api-docs                       0.9.6-next.1
  @backstage/plugin-app-backend                    0.3.47-next.0
  @backstage/plugin-auth-backend                   0.18.5-next.1
  @backstage/plugin-auth-node                      0.2.15, 0.2.16-next.0
  @backstage/plugin-badges                         0.2.44-next.1
  @backstage/plugin-catalog-backend-module-ldap    0.5.14-next.0
  @backstage/plugin-catalog-backend                1.11.0-next.0
  @backstage/plugin-catalog-common                 1.0.14, 1.0.15-next.0
  @backstage/plugin-catalog-graph                  0.2.32-next.1
  @backstage/plugin-catalog-import                 0.9.10-next.1
  @backstage/plugin-catalog-node                   1.4.0-next.0
  @backstage/plugin-catalog-react                  1.7.0, 1.7.1-next.1
  @backstage/plugin-catalog                        1.11.3-next.1
  @backstage/plugin-events-node                    0.2.8-next.0
  @backstage/plugin-github-actions                 0.6.1-next.1
  @backstage/plugin-graphiql                       0.2.52-next.1
  @backstage/plugin-home-react                     0.1.1-next.1
  @backstage/plugin-home                           0.5.4-next.1
  @backstage/plugin-kubernetes-backend             0.11.2-next.1
  @backstage/plugin-kubernetes-common              0.6.5-next.0
  @backstage/plugin-kubernetes                     0.9.3-next.1
  @backstage/plugin-org                            0.6.10-next.1
  @backstage/plugin-permission-common              0.7.6, 0.7.7-next.0
  @backstage/plugin-permission-node                0.7.10-next.0, 0.7.9
  @backstage/plugin-permission-react               0.4.13, 0.4.14-next.1
  @backstage/plugin-proxy-backend                  0.2.41-next.0
  @backstage/plugin-scaffolder-backend             1.15.1-next.0
  @backstage/plugin-scaffolder-common              1.3.2-next.0
  @backstage/plugin-scaffolder-node                0.1.5-next.0
  @backstage/plugin-scaffolder-react               1.5.1-next.1
  @backstage/plugin-scaffolder                     1.14.1-next.1
  @backstage/plugin-search-backend-module-catalog  0.1.3-next.0
  @backstage/plugin-search-backend-module-pg       0.5.8-next.0
  @backstage/plugin-search-backend-module-techdocs 0.1.3-next.0
  @backstage/plugin-search-backend-node            1.2.3-next.0
  @backstage/plugin-search-backend                 1.3.3-next.0
  @backstage/plugin-search-common                  1.2.4, 1.2.5-next.0
  @backstage/plugin-search-react                   1.6.3-next.1
  @backstage/plugin-search                         1.3.3-next.1
  @backstage/plugin-shortcuts                      0.3.12-next.1
  @backstage/plugin-sonarqube-backend              0.2.1-next.1
  @backstage/plugin-sonarqube-react                0.1.7-next.1
  @backstage/plugin-sonarqube                      0.7.1-next.1
  @backstage/plugin-tech-radar                     0.6.6-next.1
  @backstage/plugin-techdocs-backend               1.6.4-next.0
  @backstage/plugin-techdocs-node                  1.7.3-next.0
  @backstage/plugin-techdocs-react                 1.1.8-next.1
  @backstage/plugin-techdocs                       1.6.5-next.1
  @backstage/plugin-user-settings                  0.7.5-next.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.1-next.1
  @backstage/theme                                 0.2.19, 0.4.0, 0.4.1-next.0
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
✨  Done in 0.73s.

```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by agentbellnorm** [comment]
Hey @max-bojorquez, I've not been able to reproduce this on the `v1.6.0-next.2` tag unfortunately!

I've tried it with a couple of techdocs images: `spotify/techdocs:v1.0.0`, `spotify/techdocs:v1.1.0`, `spotify/techdocs:v1.2.1`. Which one do you use?

It's also interesting that you cannot reproduce this locally! If you haven't tried already, can you make sure the documentation site is regenerated to see if the issue persists (by e.g. making changes to the document)?

I've assumed you are using the 
```yaml
techdocs:
  builder: 'local'
```
setup, in case you are using the external builder, what version of the techdocs-cli are you using?
