### ISSUE TITLE
🐛 Bug Report: "Region" is missing in techdocs publisher type "awsS3" 

### ISSUE THREAD

**Issue by jfrverdasca** [backstage/backstage#18692]
### 📜 Description

Changing the configuration of techdocs/publisher to type "awsS3" and providing the configuration described in [,](https://backstage.io/docs/features/techdocs/using-cloud-storage/) at startup the backstage always throws an exception saying that "Region is missing" even if this configuration is present.

Exception stack text:
`
Backend failed to start up Error: Region is missing
    at default (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/config.js:10:15)
    at /home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/node-config-provider/dist-cjs/fromStatic.js:6:83
    at /home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
    at async coalesceProvider (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
    at async /home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:26:28
    at async useFipsEndpoint (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:21:74)
    at async resolveParams (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:29:40)
    at async getEndpointFromInstructions (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:7:28)
    at async /home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/endpointMiddleware.js:8:26
    at async /home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async fillInAccountId (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@backstage/integration-aws-node/dist/index.cjs.js:128:16)
    at async DefaultAwsCredentialsManager.getCredentialProvider (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@backstage/integration-aws-node/dist/index.cjs.js:273:5)
    at async AwsS3Publish.buildCredentials (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:914:15)
    at async AwsS3Publish.fromConfig (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:865:35)
    at async Publisher.fromConfig (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:2307:16)
    at async createPlugin (webpack-internal:///./src/plugins/techdocs.ts:33:23)
    at async main (webpack-internal:///./src/index.ts:119:32)
`

### 👍 Expected behavior

The backstage accepts the given configuration for awsS3 in the specified region, in techdocs/publisher and starts normally in order to allow using the awsS3 services as expected.

### 👎 Actual Behavior with Screenshots

The configuration shown below (hidden sensitive information)
![Captura de ecrã de 2023-07-17 14-25-34](https://github.com/backstage/backstage/assets/11158686/6ae06655-1144-4440-9edb-6bd3d4cf708d)

throws the exception below on backstage startup
![Captura de ecrã de 2023-07-17 14-33-35](https://github.com/backstage/backstage/assets/11158686/43a0195c-ad9c-4fa3-8584-fe7fe4c6ac39)

### 👟 Reproduction steps

In the app-config.local.yaml or app-config.yaml file in the "techdocs" section, under "publisher", set "type" to "awsS3". Then create the "awsS3" section and provide the configuration expected by the backstage for the awsS3 service [(),](https://backstage.io/docs/features/techdocs/using-cloud-storage/) including the "region" parameter, as shown in the image below:

![Captura de ecrã de 2023-07-17 14-54-05](https://github.com/backstage/backstage/assets/11158686/5f31f005-c1ee-492b-ace4-b9a5970c0ae1)

then, in terminal do "yarn dev" and then just wait for the described exception to be thrown.

### 📃 Provide the context for the Bug.

This way, it is not possible to access the existing tech docs in awsS3.

### 🖥️ Your Environment

yarn run v1.22.19
$ (hidden path)/.bin/backstage-cli info
OS:   Linux 6.2.0-25-generic - linux/x64
node: v18.15.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.14.0

Dependencies:
  @backstage/app-defaults                          1.3.1
  @backstage/backend-app-api                       0.4.3
  @backstage/backend-common                        0.13.5, 0.14.1, 0.18.5
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.2
  @backstage/backend-tasks                         0.5.2
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.2.0, 1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.7
  @backstage/config-loader                         1.3.0, 1.3.1
  @backstage/config                                1.0.7, 1.0.8
  @backstage/core-app-api                          1.8.0
  @backstage/core-components                       0.12.4, 0.12.5, 0.13.1, 0.9.5
  @backstage/core-plugin-api                       1.0.6, 1.5.1, 1.5.2
  @backstage/errors                                1.1.5, 1.2.0
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.3
  @backstage/integration-react                     1.1.13
  @backstage/integration                           1.4.5, 1.5.0
  @backstage/plugin-api-docs                       0.9.3
  @backstage/plugin-app-backend                    0.3.45
  @backstage/plugin-auth-backend                   0.17.4, 0.18.3
  @backstage/plugin-auth-node                      0.2.14
  @backstage/plugin-catalog-backend                1.9.1
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.30
  @backstage/plugin-catalog-import                 0.9.8
  @backstage/plugin-catalog-node                   1.3.6
  @backstage/plugin-catalog-react                  1.2.1, 1.6.0
  @backstage/plugin-catalog                        1.11.0
  @backstage/plugin-github-actions                 0.5.18
  @backstage/plugin-org                            0.6.8
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.8
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.39
  @backstage/plugin-scaffolder-backend             1.14.0
  @backstage/plugin-scaffolder-common              1.3.0
  @backstage/plugin-scaffolder-node                0.1.3
  @backstage/plugin-scaffolder-react               1.4.0
  @backstage/plugin-scaffolder                     1.13.1
  @backstage/plugin-search-backend-module-catalog  0.1.1
  @backstage/plugin-search-backend-module-pg       0.5.6
  @backstage/plugin-search-backend-module-techdocs 0.1.1
  @backstage/plugin-search-backend-node            1.2.1
  @backstage/plugin-search-backend                 1.3.1
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.6.0
  @backstage/plugin-search                         1.3.0
  @backstage/plugin-sentry                         0.5.3
  @backstage/plugin-sonarqube-backend              0.1.10
  @backstage/plugin-sonarqube-react                0.1.5
  @backstage/plugin-sonarqube                      0.6.7
  @backstage/plugin-tech-radar                     0.6.4
  @backstage/plugin-techdocs-backend               1.6.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.13
  @backstage/plugin-techdocs-node                  1.7.1
  @backstage/plugin-techdocs-react                 1.1.6
  @backstage/plugin-techdocs                       1.6.2
  @backstage/plugin-user-settings                  0.7.3
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.1
  @backstage/theme                                 0.2.19, 0.3.0
  @backstage/types                                 1.0.2, 1.1.0
  @backstage/version-bridge                        1.0.4
Done in 0.62s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by johnphilip283** [comment]
> ### 📜 Description
> Changing the configuration of techdocs/publisher to type "awsS3" and providing the configuration described in [,](https://backstage.io/docs/features/techdocs/using-cloud-storage/) at startup the backstage always throws an exception saying that "Region is missing" even if this configuration is present.
> 
> Exception stack text: `Backend failed to start up Error: Region is missing at default (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/config.js:10:15) at /home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/node-config-provider/dist-cjs/fromStatic.js:6:83 at /home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28 at async coalesceProvider (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24) at async /home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:26:28 at async useFipsEndpoint (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:21:74) at async resolveParams (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:29:40) at async getEndpointFromInstructions (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:7:28) at async /home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/endpointMiddleware.js:8:26 at async /home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 at async fillInAccountId (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@backstage/integration-aws-node/dist/index.cjs.js:128:16) at async DefaultAwsCredentialsManager.getCredentialProvider (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@backstage/integration-aws-node/dist/index.cjs.js:273:5) at async AwsS3Publish.buildCredentials (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:914:15) at async AwsS3Publish.fromConfig (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:865:35) at async Publisher.fromConfig (/home/jverdasca/Documentos/Projetos/backstage/backstage/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:2307:16) at async createPlugin (webpack-internal:///./src/plugins/techdocs.ts:33:23) at async main (webpack-internal:///./src/index.ts:119:32)`
> 
> ### 👍 Expected behavior
> The backstage accepts the given configuration for awsS3 in the specified region, in techdocs/publisher and starts normally in order to allow using the awsS3 services as expected.
> 
> ### 👎 Actual Behavior with Screenshots
> The configuration shown below (hidden sensitive information) ![Captura de ecrã de 2023-07-17 14-25-34](https://user-images.githubusercontent.com/11158686/253957548-6ae06655-1144-4440-9edb-6bd3d4cf708d.jpg)
> 
> throws the exception below on backstage startup ![Captura de ecrã de 2023-07-17 14-33-35](https://user-images.githubusercontent.com/11158686/253958078-43a0195c-ad9c-4fa3-8584-fe7fe4c6ac39.png)
> 
> ### 👟 Reproduction steps
> In the app-config.local.yaml or app-config.yaml file in the "techdocs" section, under "publisher", set "type" to "awsS3". Then create the "awsS3" section and provide the configuration expected by the backstage for the awsS3 service [(),](https://backstage.io/docs/features/techdocs/using-cloud-storage/) including the "region" parameter, as shown in the image below:
> 
> ![Captura de ecrã de 2023-07-17 14-54-05](https://user-images.githubusercontent.com/11158686/253963837-5f31f005-c1ee-492b-ace4-b9a5970c0ae1.png)
> 
> then, in terminal do "yarn dev" and then just wait for the described exception to be thrown.
> 
> ### 📃 Provide the context for the Bug.
> This way, it is not possible to access the existing tech docs in awsS3.
> 
> ### 🖥️ Your Environment
> yarn run v1.22.19 $ (hidden path)/.bin/backstage-cli info OS: Linux 6.2.0-25-generic - linux/x64 node: v18.15.0 yarn: 1.22.19 cli: 0.22.7 (installed) backstage: 1.14.0
> 
> Dependencies: @backstage/app-defaults 1.3.1 @backstage/backend-app-api 0.4.3 @backstage/backend-common 0.13.5, 0.14.1, 0.18.5 @backstage/backend-dev-utils 0.1.1 @backstage/backend-plugin-api 0.5.2 @backstage/backend-tasks 0.5.2 @backstage/catalog-client 1.4.1 @backstage/catalog-model 1.2.0, 1.3.0 @backstage/cli-common 0.1.12 @backstage/cli-node 0.1.0 @backstage/cli 0.22.7 @backstage/config-loader 1.3.0, 1.3.1 @backstage/config 1.0.7, 1.0.8 @backstage/core-app-api 1.8.0 @backstage/core-components 0.12.4, 0.12.5, 0.13.1, 0.9.5 @backstage/core-plugin-api 1.0.6, 1.5.1, 1.5.2 @backstage/errors 1.1.5, 1.2.0 @backstage/eslint-plugin 0.1.3 @backstage/integration-aws-node 0.1.3 @backstage/integration-react 1.1.13 @backstage/integration 1.4.5, 1.5.0 @backstage/plugin-api-docs 0.9.3 @backstage/plugin-app-backend 0.3.45 @backstage/plugin-auth-backend 0.17.4, 0.18.3 @backstage/plugin-auth-node 0.2.14 @backstage/plugin-catalog-backend 1.9.1 @backstage/plugin-catalog-common 1.0.13 @backstage/plugin-catalog-graph 0.2.30 @backstage/plugin-catalog-import 0.9.8 @backstage/plugin-catalog-node 1.3.6 @backstage/plugin-catalog-react 1.2.1, 1.6.0 @backstage/plugin-catalog 1.11.0 @backstage/plugin-github-actions 0.5.18 @backstage/plugin-org 0.6.8 @backstage/plugin-permission-common 0.7.5 @backstage/plugin-permission-node 0.7.8 @backstage/plugin-permission-react 0.4.12 @backstage/plugin-proxy-backend 0.2.39 @backstage/plugin-scaffolder-backend 1.14.0 @backstage/plugin-scaffolder-common 1.3.0 @backstage/plugin-scaffolder-node 0.1.3 @backstage/plugin-scaffolder-react 1.4.0 @backstage/plugin-scaffolder 1.13.1 @backstage/plugin-search-backend-module-catalog 0.1.1 @backstage/plugin-search-backend-module-pg 0.5.6 @backstage/plugin-search-backend-module-techdocs 0.1.1 @backstage/plugin-search-backend-node 1.2.1 @backstage/plugin-search-backend 1.3.1 @backstage/plugin-search-common 1.2.3 @backstage/plugin-search-react 1.6.0 @backstage/plugin-search 1.3.0 @backstage/plugin-sentry 0.5.3 @backstage/plugin-sonarqube-backend 0.1.10 @backstage/plugin-sonarqube-react 0.1.5 @backstage/plugin-sonarqube 0.6.7 @backstage/plugin-tech-radar 0.6.4 @backstage/plugin-techdocs-backend 1.6.2 @backstage/plugin-techdocs-module-addons-contrib 1.0.13 @backstage/plugin-techdocs-node 1.7.1 @backstage/plugin-techdocs-react 1.1.6 @backstage/plugin-techdocs 1.6.2 @backstage/plugin-user-settings 0.7.3 @backstage/release-manifests 0.0.9 @backstage/test-utils 1.3.1 @backstage/theme 0.2.19, 0.3.0 @backstage/types 1.0.2, 1.1.0 @backstage/version-bridge 1.0.4 Done in 0.62s.
> 
> ### 👀 Have you spent some time to check if this bug has been raised before?
> * [x]  I checked and didn't find similar issue
> 
> ### 🏢 Have you read the Code of Conduct?
> * [x]  I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
> 
> ### Are you willing to submit PR?
> None

Hey there @jfrverdasca! I think you may be missing this configuration in your `app-config.yaml` that properly builds your AWS credentials:

```
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker'
    # dockerImage: my-org/techdocs # use a custom docker image
    # pullImage: true # or false to disable automatic pulling of image (e.g. if custom docker login is required)
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: 'name-of-techdocs-storage-bucket'
      bucketRootPath: '/'
      accountId: '123456789012'
      credentials:
        accessKeyId: '1234'
        secretAccessKey: '5678'
      region: eu-central-1
aws:
  accounts:
    - accountId: '123456789012'
      accessKeyId: '1234'
      secretAccessKey: '5678'
```
This should properly build your AWS credential provider, which is what was causing your issue earlier. You can read more about the AWS Node integration for Backstage [here](https://www.npmjs.com/package/@backstage/integration-aws-node).
