### ISSUE TITLE
🚀 Feature: Expose the table data after the filter based on search text gets updated in the table tool bar

### ISSUE THREAD

**Issue by airavichandra** [backstage/backstage#18698]
### 🔖 Feature description

We want to expose the table data in the [Table](https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/Table/Table.tsx) component whenever a search text in the table tool bar gets updated.

### 🎤 Context

We have a custom button to export the catalog table data to CSV. It works fine when we export all catalog data or filter catalog data specified in the `CatalogFilterLayout`. But the problem is, we cannot export the updated table data when we filter based on a search term from the table tool bar.
<img width="1413" alt="Screenshot 2023-07-17 at 5 42 21 PM" src="https://github.com/backstage/backstage/assets/94489758/bda977af-bd43-4467-b5c8-9192e05f42ba">

The `MTableToolBar` has an internal property `onSearchChanged` that takes care of updating the table and as a result the [tableData](https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/Table/Table.tsx#L328) state does not get updated.

We need to change this `onSearchChanged` callback to update the state, so that we can use the data to export.

### ✌️ Possible Implementation

We can use the `data` prop of `MTableToolbar` to expose the updated table data inside the `onSearchChanged` callback. 

```
const onSearchChanged = useCallback(
    (searchText: string) => {
      toolbarProps.onSearchChanged(searchText);
      data = toolbarProps.data; //use this to update the `setTableData` hook
      setSearch(searchText);
    },
    [toolbarProps, setSearch],
  );
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by airavichandra** [comment]
I would like to assign this issue to myself

**Comment by benjdlambert** [comment]
Sure I can assign it to you!

A little guidance would be that we should have some other state for which deals with the `visibleData` or something an use that to drive the exporting. Setting the `data` like that in a hook is probably not what we want to do.
