### ISSUE TITLE
🐛 Bug Report: <Add Shortcut shouldn't accept duplicate url & duplicate name>

### ISSUE THREAD

**Issue by AmbrishRamachandiran** [backstage/backstage#18705]
### 📜 Description

Add short cut feature accepts duplicate name as well as duplicate url
when user click on the add shortcut and gives same url and names for multiple times its creates without any error message

### 👍 Expected behavior

If shortcut url or name already exist or created its should show the popup or error as "short cut url or name already exist"

### 👎 Actual Behavior with Screenshots

If shortcut url or name already exist or created its keep on accepting duplicates and getting created

![image](https://github.com/backstage/backstage/assets/133481507/101e30a3-3788-4191-a089-6802f30882a2)

### 👟 Reproduction steps

1.Go to add shortcut section click on it 
2.Create a shortcut by filling the form, once shortcut created 
3.Again Create a shortcut with same name and url it will create duplicates

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tperehinets** [comment]
I am really interested in working on this one.

**Comment by AmbrishRamachandiran** [comment]
closing this as iam gonna work on https://github.com/backstage/backstage/issues/18733
