### ISSUE TITLE
🐛 Bug Report: Configuration property visibility does not work from /plugins

### ISSUE THREAD

**Issue by Vity01** [backstage/backstage#18701]
### 📜 Description

I try to adopt and extend abandoned [Confluence plugin](https://github.com/K-Phoen/backstage-plugin-confluence). I would like to add an option to search selected Confluence spaces from SearchPage.tsx. This `spaces` property is defined in the configuration at location `conflunce: spaces: <array of strings>` and its description is at [`config.d.ts` file](https://github.com/K-Phoen/backstage-plugin-confluence/blob/main/plugins/search-confluence-backend/config.d.ts#L14).
I changed my SearchPage and I copied content of the plugin into `/plugins` directory and changed the `spaces` property visibility to `frontend` (+linked App frontend with the changed /plugins/Confluence plugin).
` backstage-cli config:print --frontend` indicates that the property should be visible from frontend, but during a runtime it's not there. 
I tried multiple things to resolve that. I think the reason is that the build process does not reflect changes in config.d.ts if the code is placed under `/plugins`. When I run full build (`yarn build`) this file `node_modules\app\dist\.config-schema.json ` does not contain the `spaces` property.

### 👍 Expected behavior

Changes in config.dt.s under /plugins should be reflected.

### 👎 Actual Behavior with Screenshots

Property is not available from frontend.

### 👟 Reproduction steps

Define/update any plugin under and make any property visibility to `frontend`. Property should be available during runtime in frontend App.

### 🖥️ Your Environment

`backstage-cli --version` 0.22.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Arrays are a bit tricky since with the existing setup only the array itself is marked as visible, not the items. It'll need to be switched to `@items.visibility`, see the example at https://backstage.io/docs/conf/defining#schema-collection-and-definition

**Comment by Vity01** [comment]
Hi Patrick,
I forgot to mention I tried the `@items.visibility` flag too. It has no effect. 
The property is visible for `backstage-cli config:print --frontend`, but it's not in the `.config-schema.json`/runtime

**Comment by Vity01** [comment]
I also tried to add this file under `/packages/backend/config.d.ts` as a workaround
```
export interface Config {
  confluence: {

    /**
     * Spaces to index
     * @items.visibility frontend
     */
    spaces: string[];
  };
}
```

+ updated package.json

```
  "files": [
    "dist",
    "config.d.ts"
  ],
  "configSchema": "config.d.ts"
```

I would expect it should work, but no luck.

**Comment by nkydrwr** [comment]
Any update on this? Is the app config only design to work for backstage not for plugins?

**Comment by vinzscam** [comment]
just to clarify that frontend plugins can access app-config. If you have a frontend plugin defined in `plugins/my-awesome-plugin` which needs to access some app-config properties, you need to define the properties you want to access in `plugins/my-awesome-plugin/config.d.ts`

**Comment by raphtalia** [comment]
I'm seeing the same issue with `@items.visibility` where it's shown in `backstage-cli config:print --frontend` but not in effect during runtime.

**Comment by veenarm** [comment]
Is this still a thing, just spent a while trying to figure out why adding visiblity to a plugin backend isn't working. The console throws error sayings it's not visible even though it is set. and using the `backstage-cli config:print --frontend` shows it there.
