### ISSUE TITLE
🚀 Feature: Adding remove button near to edit button in Add shortcuts list of shortcuts

### ISSUE THREAD

**Issue by AmbrishRamachandiran** [backstage/backstage#18706]
### 🔖 Feature description

When a user uses the Add Shortcut button to create several shortcuts, a list will be created; however, under the current functionality, a user must first click on Edit before they may delete a shortcut.
Keep the remove button and icon close to the edit button so that users can quickly remove the shortcut.

![image](https://github.com/backstage/backstage/assets/133481507/a9f25fd9-77dc-4ed9-a08e-8fcde328a318)
![image](https://github.com/backstage/backstage/assets/133481507/73215dd7-9bed-4c99-86a0-2f0775ad1b0b)

### 🎤 Context

When a user uses the Add Shortcut button to create several shortcuts, a list will be created; however, under the current functionality, a user must first click on Edit before they may delete a shortcut.
Keep the remove button and icon close to the edit button so that users can quickly remove the shortcut.

### ✌️ Possible Implementation

Keep the remove button and icon close to the edit button so that users can quickly remove the shortcut.

![image](https://github.com/backstage/backstage/assets/133481507/094c4363-d12d-48f0-8017-91dacb8e8087)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by AmbrishRamachandiran** [comment]
assign it to me

**Comment by awanlin** [comment]
Hi @AmbrishRamachandiran, I've assigned it to you. I like the idea you've suggested but I might make it opt-in. There is not a lot of space in this location and that would give people the choice to have it display or not 👍
