### ISSUE TITLE
🐛 Bug Report: Spring Boot gRPC Service form java package name field don't have validations

### ISSUE THREAD

**Issue by AmbrishRamachandiran** [backstage/backstage#18702]
### 📜 Description

Spring Boot gRPC Service form java package name field don't have validations , when user enters some specials characters like 
@@###^^ in Java Package Name its accepts instead of showing an error message validation.

**Java Package names (both source and binary, see Package) must consist only of lower case letters ( a-z ), digits ( 0-9 ), plus ( + ) and minus ( - ) signs, and periods ( . )** 

### 👍 Expected behavior

When user enters only the special characters in the Java Package Name textbox and submit its shouldn't accept & should show the error message validation

### 👎 Actual Behavior with Screenshots

When user enters only the special characters in the Java Package Name textbox its accepts the form.

![image](https://github.com/backstage/backstage/assets/133481507/8a94d14d-cf73-471a-8b38-9be99e60be34)

### 👟 Reproduction steps

1.GO TO catalog page and click on create 
2. choose Spring Boot gRPC Service 
3.fill the form in the Java Package Name textbox  enter @@@@@@@ and click on next button its accepts the form

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by gsasanelli** [comment]
Uhm... based on my experience you are using the example that the Backstage team is providing. You can take it, change it accordingly your need and index it from your convenient location

**Comment by benjdlambert** [comment]
@AmbrishRamachandiran yep, exactly as @gsasanelli says, it's purely a sample template, but if you want to raise a PR adding better validation to that template which could demo how to do it then sure! :Pray:
