### ISSUE TITLE
🐛 Bug Report: Sidebar Items and React 18

### ISSUE THREAD

**Issue by RobotSail** [backstage/backstage#18714]
### 📜 Description

When upgrading the `@backstage/core-components` package to React 18, there is a problem where the props for WorkaroundNavLink as well as the Sidebar items don't align with what is expected in React 18. 

Since React 18 updated its types, the `Link` component from `react-router-dom` expects `children` to be of type `ReactNode`. Whereas `NavLinkProps` specifies `children` as being:

```ts
export interface NavLinkProps extends Omit<LinkProps, "className" | "style" | "children"> {
    children?: React.ReactNode | ((props: {
        isActive: boolean;
        isPending: boolean;
    }) => React.ReactNode);
    caseSensitive?: boolean;
    className?: string | ((props: {
        isActive: boolean;
        isPending: boolean;
    }) => string | undefined);
    end?: boolean;
    style?: React.CSSProperties | ((props: {
        isActive: boolean;
        isPending: boolean;
    }) => React.CSSProperties | undefined);
}
```

To handle this condition, one can check to see whether or not `children` is of type function and then apply the appropriate logic. One unknown here though, is how do we handle the case when `children` is actually a function type? 
Should we invoke it and pass the `ReactNode` result into the link, or do we need to modify the code somehow so that any components consuming it can invoke it when needed? 

Another issue is that `SidebarItem` also gets this `children` prop as a type of either ReactNode or function. The definition is as follows:
```tsx
/**
 * Creates a `SidebarItem`
 *
 * @remarks
 * If children contain a `SidebarSubmenu` component the `SidebarItem` will have a expandable submenu
 */
export const SidebarItem = forwardRef<any, SidebarItemProps>((props, ref) => {
  // Filter children for SidebarSubmenu components
  const [submenu] = useElementFilter(props.children, elements =>
    // Directly comparing child.type with SidebarSubmenu will not work with in
    // combination with react-hot-loader
    //
    // https://github.com/gaearon/react-hot-loader/issues/304#issuecomment-456569720
    elements.getElements().filter(child => child.type === sidebarSubmenuType),
  );

  if (submenu) {
    return (
      <SidebarItemWithSubmenu {...props}>
        {submenu as React.ReactElement<SidebarSubmenuProps>}
      </SidebarItemWithSubmenu>
    );
  }

  return <SidebarItemBase {...props} ref={ref} />;
}) as (props: SidebarItemProps) => JSX.Element;
```

The `useElementFilter` hook only accepts types of ReactNode, and not the function that is being passed. 

### 👍 Expected behavior

n/a

### 👎 Actual Behavior with Screenshots

n/a

### 👟 Reproduction steps

n/a

### 🖥️ Your Environment

n/a

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by RobotSail** [comment]
One of the issues with `children` potentially being a function per the above definition is needing to provide values for the `isActive` and `isPending` parameters. 

How do we want to go about handling this?

**Comment by RobotSail** [comment]
We solved this issue in [the react 18 upgrade PR](https://github.com/RobotSail/backstage/pull/2)

**Comment by freben** [comment]
Nice, closing!
