### ISSUE TITLE
🐛 Bug Report: Inconsistency of viewing Group names

### ISSUE THREAD

**Issue by Vity01** [backstage/backstage#18721]
### 📜 Description

We use LDAP and LDAP transformer to set up correct `metadata.name` property to be valid against FieldNamePolicy. We also set up original `metadata.title` when creating/updating entity in BS. Unfortunately the `metadata.title` is not used on all pages where the Group names are listed. It's correctly viewed on Catalog List, on Group Detail info page and wrong on UserProfileCard. The reason is it's viewing directly CompoundEntityRef, which contains just `metadata.name` property.

### 👍 Expected behavior

Group names on UserProfileCard should use `metadata.title` in the name of link.

### 👎 Actual Behavior with Screenshots

Group in Catalog - Correct:
![image](https://github.com/backstage/backstage/assets/2512959/5521ca4e-2c51-41bb-8c9c-835516dda630)
Group Detail - Correct:
![image](https://github.com/backstage/backstage/assets/2512959/1f5548c1-972e-4b4b-8b37-4251799f23e1)
User detail page - Incorrect:
![image](https://github.com/backstage/backstage/assets/2512959/3959c215-ce99-45e1-8713-8ea8a7c2241d)

### 👟 Reproduction steps

Define Group with a `metadata.title`. This property should be used everywhere. 

### 🖥️ Your Environment

1.15

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Think that this is probably closely related to #17474

**Comment by Vity01** [comment]
@benjdlambert  yes, possibly. it could help to resolve it, or to update current UserProfileCard code.

**Comment by benjdlambert** [comment]
I wonder if we should close this issue in favour of the new meta issue for using the presentation ref: https://github.com/backstage/backstage/issues/20955

**Comment by camilaibs** [comment]
Hello, closing this issue in favour of the new meta issue for using the presentation ref: https://github.com/backstage/backstage/issues/20955
