### ISSUE TITLE
🐛 Bug Report: react-json-schema-form link has been moved to a new location

### ISSUE THREAD

**Issue by floresjma** [backstage/backstage#18728]
### 📜 Description

The link to the `react-json-schema-form` has been moved to a different location.

One example where is pointed to the old location:
-  [Writing custom steps layouts](https://backstage.io/docs/features/software-templates/writing-custom-step-layouts/)

In `Writing custom steps layouts`, _react-json-schema-form_ is used whereas _react-jsonschema-form_ is used in other places e.g.   `Input Examples` section.

### 👍 Expected behavior

The link should point to the right location: https://rjsf-team.github.io/react-jsonschema-form/docs/

`react-jsonschema-form` should be the correct term.  

### 👎 Actual Behavior with Screenshots

The link points to the old location: https://react-jsonschema-form.readthedocs.io/en/latest/

### 👟 Reproduction steps

Go to [Writing custom steps layouts](https://backstage.io/docs/features/software-templates/writing-custom-step-layouts/), click on the [react-json-schema-form](https://react-jsonschema-form.readthedocs.io/) link that will take you to the old location.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@floresjma do you want to raise a PR with a fix for this please? :pray:

**Comment by floresjma** [comment]
@benjdlambert yes please, happy to do it :)

**Comment by abhijeetgauravm** [comment]
I want to work on it. Can u assign me?

**Comment by floresjma** [comment]
Going through an internal approval in my company at the moment, PR will be created shortly

**Comment by abhijeetgauravm** [comment]
Can I work on this issue? @freben @floresjma

**Comment by Rugvip** [comment]
Fixed by #18896
