### ISSUE TITLE
🐛 Bug Report: Two many rows are rendered in the (Catalog) table in the background, causing unresponsive page

### ISSUE THREAD

**Issue by aximusnl** [backstage/backstage#18727]
### 📜 Description

I noticed a bug in @material-table/core, which only becomes apparent when you have a lot of entities in your catalog.
The bug is quite severe, it makes the page unresponsive for x seconds depending on the amount of entities. I've seen hick-ups of over 20 seconds.

I've tried updating @material-table/core. Backstage is currently using ^3.1.0, but the latest version is 6.2.1. The latest version compatible with MUI 4 is @material-table/core 5.x. Updating to 5.1.9 did not solve the problem(s).

### 👍 Expected behavior

It should not render more rows than the page size

### 👎 Actual Behavior with Screenshots

It renders all rows (in the background) in the set, disregarding page size.

### 👟 Reproduction steps

In the catalog, set to a kind filter so that it has a lot of entities, let's say 5,000. Now change the kind filter to a kind that has less entities then the page size (20 by default).
What happens is that the pagination in the table is removed before the new entities are loaded and thus all 5,000 entities are rendered.

Another problem is that every time the loading prop changes in the table, all visible rows are re-rendered. Leading to a lot of unnecessary renders.

### 📃 Provide the context for the Bug.

Short term solution:
Instead of using the @material-table/core Table's loading prop, use a loading indicator (LinearProgress for example) with an early exit. So the Table is not rendered while loading is true. This fixes the above two issues, but it's visually different.

Long term solution:
Maybe this problem is fixed in @material-table/core 6.x (didn't check), but it requires MUI 5
Use MUI's Data Grid (question: why was this not used in the first place?)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Yeah fortunately there's been some steps towards making this catalog page paginated. 

You can read more and get involved here #12247

**Comment by sennyeya** [comment]
Thanks for the report, I don't believe the core issue is re-rendering here. Currently, the catalog does not have support for large numbers of catalogs in the view you're talking about. All entities are loaded at once and filter client side. While we could adjust this by changing the table library or other optimizations, the right direction to end up is defined in #12247. That ticket is to make all filtering happen server side and only return a single page of entities.

We're working towards #12247 which would cause the table to only render the single relevant page and have the backend do the filtering and loading. The performance issues with large catalogs are a known issue that #12247 should fix.

**Comment by aximusnl** [comment]
Sorry for the late reply.

Pagination will not fix this issue. This is about a rendering problem in the table.

**Comment by benjdlambert** [comment]
Pagination will fix the issue as we won't be rendering 5000 rows anymore, just pages from the API instead. Cc @vinzscam

**Comment by aximusnl** [comment]
Pagination will hide the issue. There will still be unnecessary re-renders of table rows.

**Comment by sennyeya** [comment]
Pagination would be set to the table page size (I think), which would solve the issue of massively unnecessary rerenders. The two impacts of that that you describe seem more like upstream issues in the table library (as you mention) and should be investigated there.

**Comment by aximusnl** [comment]
Why is @material-table used? Why not [MUI's data grid](https://mui.com/x/react-data-grid/)?

**Comment by vinzscam** [comment]
> Pagination will hide the issue. There will still be unnecessary re-renders of table rows.

when we refer to pagination, we refer to server side pagination. So instead of returning all the entities present in the database, we return and render a bunch of them and then the frontend will fetch the next batch once the user want to navigate to the next page. 
This approach will actually solve any frontend performance issues.

> Why is https://github.com/material-table used? Why not [MUI's data grid](https://mui.com/x/react-data-grid/)?

I guess this project was started before datagrid was a thing. Anyway, by switching to server side pagination we won't need any of these advanced data libraries.

**Comment by benjdlambert** [comment]
Related #12247
