### ISSUE TITLE
🚀 Feature: custom EntityFilter should support OR relation or regex matching

### ISSUE THREAD

**Issue by zinizhu** [backstage/backstage#18720]
### 🔖 Feature description

The `EntityFilter` type's `getCatalogFilters()` function can allow configuring multiple filtering rules with `OR` relation. Alternatively, filtering by matching the annotation prefix can also work.

### 🎤 Context

I am trying to use `useEntityList` and a custom `EntityFilter` to fetch entities that has at least one of the required annotations, for example:

Entity1:
```
metadata:
    annotations:
        my.org/prefix-value1: <some value>
```

Entity2:
```
metadata:
    annotations:
        my.org/prefix-value2: <other value>
```

The custom EntityFilter:

```
class CustomFilter implements EntityFilter {
  getCatalogFilters(): Record<string, string | symbol | (string | symbol)[]>[] {
    return [
        {
            'my.org/prefix-value1': CATALOG_FILTER_EXISTS,
        },
        {
            'my.org/prefix-value2': CATALOG_FILTER_EXISTS,
        }
    ];
  }
}

```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by tperehinets** [comment]
I am looking into this one

**Comment by freben** [comment]
Those should be on the form `metadata.annotations.my.org/prefix-value1`, not just `my.org/prefix-value1`. Does that resolve the problem?

**Comment by zinizhu** [comment]
@freben thanks for pointing that out, though my question was if it's possible to use the filter like `metadata.annotations.my.org/prefix` to fetch both entities with `metadata.annotations.my.org/prefix-value1` and `metadata.annotations.my.org/prefix-value2`. I just tried:

```
export class MyFilter implements EntityFilter {
  getCatalogFilters(): Record<string, string | symbol | (string | symbol)[]> {
    return {
      'metadata.annotations.my.org/prefix': CATALOG_FILTER_EXISTS,
    };
  }
}
```

which does not work.

**Comment by zinizhu** [comment]
Ha, thanks for the advice, I will look into it!

**Comment by frankfarzan** [comment]
Is there a reason for extending `.metadata` instead of `.spec`? Following k8s api conventions, `metadata` struct is standardized across all resource kinds, and you don't typically extend it (beyond extensibility offered through label and annotations).

From a conceptual point of view: effectively all Backstage entities are "metadata", so distinction between `.metadata` vs `.spec` is more fuzzy.

**Comment by Rugvip** [comment]
@frankfarzan spec works too! We use the same distinction, metadata is common across all entity kinds in any given catalog model. Where you put the data just depends on your own use-case, i.e. whether it's specific to a particular kind or not.

**Comment by Rugvip** [comment]
Gonna close this. We already support OR matching and we do not want to add regex matching to the filtering. For anyone running into this we suggest the approach described in my previous comments.

**Comment by zinizhu** [comment]
> We already support OR matching 

Is this true, from the [`EntityFilter`](https://github.com/backstage/backstage/blob/a9f1417fd601e1af687bb0997dcdf128c472106c/plugins/catalog-react/src/types.ts#L27) definition it seems it only supports `AND`?

**Comment by Rugvip** [comment]
Ah yep, seems it might not expose all the capabilities of the API. I'll reopen for investigation at least

**Comment by zinizhu** [comment]
Any update on this one?

**Comment by Rugvip** [comment]
Yep discussed it a bit more today, and at least short term it would be quite messy to add support for `OR` filters for the `EntityFiler`s. Gets a bit complex and might potentially hurt performance quite a lot to merge them together under the hood. Thinking that we'll avoid adding support for it for now.

Do you have a use-case in mind that is not the one that we discussed previously?

**Comment by zinizhu** [comment]
No, it's still about the use case above, though I was able to find a workaround. I will close this ticket for now and feel free to re-open it if there's a plan to add the support, thanks!
