### ISSUE TITLE
🐛 Bug Report: `scaffolder/next` doesnt support feature flags inside templates

### ISSUE THREAD

**Issue by ScottGuymer** [backstage/backstage#18739]
### 📜 Description

When trying to use `backstage:featureFlag` inside a template it does not work.

Following example in https://backstage.io/docs/features/software-templates/writing-templates/#remove-sections-or-fields-based-on-feature-flags

### 👍 Expected behavior

Expected that the specified parts of the template should show/hide based on the flag

### 👎 Actual Behavior with Screenshots

`backstage:featureFlag` is ignored and sections always render.

### 👟 Reproduction steps

Follow example in https://backstage.io/docs/features/software-templates/writing-templates/#remove-sections-or-fields-based-on-feature-flags

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
ahh - nice find. Looks like we need to move some of this logic to a nice place in the `Workflow` component.

Probably as like a little helper or hook to keep the component pretty clean.

https://github.com/backstage/backstage/blob/73537f9cff8bb6fcdbbea3950b231a1a9e1e1d04/plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx#L98-L134

**Comment by tperehinets** [comment]
I would love to work on it. Could you assign this one to me?

**Comment by tperehinets** [comment]
@freben is scaffolder/next on the master branch, or does it have its own branch?

**Comment by freben** [comment]
@tperehinets It's on master, yep

**Comment by tperehinets** [comment]
@ScottGuymer I have been been trying to use backtage:featureFlag in a template, and it worked. Could you please elaborate on your issue?

**Comment by ScottGuymer** [comment]
Nothing much to elaborate really..

I tried to use the feature flag in a template that is being rendered by the vnext scaffolder and nothing happened. The section that should have been removed was not and remained in place 


It could be that the section mentioned by @benjdlambert has been added in the meantime and this issue not linked to the PR..

**Comment by benjdlambert** [comment]
@tperehinets I think that you will need to use the `scaffolder/next` work, which is what is currently shipped in `master` but you'll need to turn on the `scaffolder-next-preview` feature flag for it to use that code path for now.

Can you try turning that on under `/settings` and give it another go.

**Comment by tperehinets** [comment]
@benjdlambert thank you! I have been trying to import filterOutProperties function from the MultistepJsonForm.tsx to keep Workflow.tsx clean. However, I am thinking that maybe I should copy function if the previous scaffolder version will be deprecated.

**Comment by benjdlambert** [comment]
@tperehinets I'd recommend duplicating it and making it into a nice hook or something in React. We're looking at moving the scaffolder/next work to default over the next releases so it's going to be easier just to delete the old stuff :tada: #19484

**Comment by Rugvip** [comment]
Fixed by #20281 afaik
