### ISSUE TITLE
TypeError this._listeners[I] is not a function Call Stack

### ISSUE THREAD

**Issue by ravar17** [backstage/backstage#18736]
### 📜 Description

I would like to add the Graphql Voyager in Backstage Developer portal. I followed the code, however getting the below error on the browser.

TypeError
this._listeners[I] is not a function
Call Stack
 Worker.eval
  node_modules/graphql-voyager/dist/voyager.lib.js:1674:765 . 
  
  
voyager.lib.js:1674 Uncaught TypeError: this._listeners[I] is not a function
    at Worker.eval (voyager.lib.js:1674:1)
voyager.lib.js:1674
  
  
  

### 👍 Expected behavior

I should be able to see the Voyager in the TAB, without I need to refresh to avoid the Error.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/134925809/1816276a-f13d-48b6-b9aa-7686e10cd3b9)

### 👟 Reproduction steps

https://github.com/backstage/backstage/tree/master/plugins/graphql-voyager

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ravar17** [comment]
Schema is getting load, if I refresh again, what could be the reason ?

**Comment by benjdlambert** [comment]
@MitchWijt do you have any ideas here?

**Comment by MitchWijt** [comment]
@benjdlambert @ravar17 I will have a look later today / tomorrow!

**Comment by MitchWijt** [comment]
@ravar17 Alright, I just tried to reproduce it creating a new Backstage instance and installing the plugin, but for me it works without errors. 

Could you show me the way you have set it up? 

Also which NPM version are you using?

**Comment by ravar17** [comment]
Hello @MitchWijt 

I am trying to run from the localhost, Below are my local npm, nodejs and yarn version.. 

npm -v ------ 8.11.0
yarn -v -------3.2.3
node v -------v16.15.1


Furthermore, I did some changes in the createApiFactory method to fetch the schema. 

here is the code for that 


  createApiFactory({
    api: graphQlVoyagerApiRef,
    deps: { errorApi: errorApiRef, githubAuthApi: githubAuthApiRef, identityApi: identityApiRef },
    factory: ({ errorApi, identityApi }) => {
      let data = getData();
      let mockUrl = getMockUrl();
      return GraphQLVoyagerEndpoints.from([
        {
          id: 'github-schema',
          //title: 'Github Schema',
          title: 'Backend - ' + data[1],
          introspectionErrorMessage:
            'Unable to perform introspection, make sure you are on the correct environment.',
            introspection: async (query: any) => {
              try {
                //const token = await githubAuthApi.getAccessToken();
                const token = identityApi.getBackstageIdentity();
                 // eslint-disable-next-line no-console

                //const res = await fetch(mockUrl, {
                const res = await fetch(data[0], {
                  method: 'POST',
                  body: JSON.stringify({ query }),
                  headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${token}`,
                  },
                });
                
                return res.json();
              } catch (error) {
                errorApi.post(error);
                throw error;
              }
              
            },
          voyagerProps: {
            hideDocs: true,
          },
        },
        {
          id: 'local',
          //title: 'Local Schema',
          title: 'Backend Mock - ' +  data[1],
          introspectionErrorMessage:
            'Unable to perform introspection, make sure you are on the correct environment.',
            introspection: async (query: any) => {
              try {
                const token = await identityApi.getCredentials();
                const res = await fetch(mockUrl, {
                  method: 'POST',
                  body: JSON.stringify({ query }),
                  headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${token.token}`,
                  },
                });
                
                return res.json();
              } catch (error) {
                errorApi.post(error);
                throw error;
              }
              
            },
          voyagerProps: {
            hideDocs: true,
          },
        },
      ]);
    },
  }),

];

**Comment by MitchWijt** [comment]
@ravar17 Are you sure all those variables are set whenever you enter the page for the first time? Since it loads correctly upon refresh

**Comment by SatyaIngka** [comment]
I'm having the same issue as well. The page loads correctly the first time and upon refresh. The error appears when switching between the different endpoint tabs

**Comment by ravar17** [comment]
@MitchWijt , what is happening, its working fine for the first time, when I open the page, Schema is loading in Graphql Voyager tab, but When I am trying to open voyager for  another API , I see the below error, When I refresh again the error disappear and another api is schema is getting loaded successfully,

![image](https://github.com/backstage/backstage/assets/134925809/2e415bc8-9757-4166-a2d5-9165dba0c68b)

**Comment by ravar17** [comment]
@MitchWijt will you please provide your inputs ?

**Comment by MitchWijt** [comment]
@ravar17 Will have a look at this tomorrow and share my inputs, will also do an in-depth reproduction of it.

**Comment by MitchWijt** [comment]
@ravar17 I did some searching and replicating. I reproduced the issue. And it seems to be a problem in the graphql-voyager repository. Their UseEffect() hook does not have a cleanup function, so a subsequent render call to the <Voyager/> Component results in a: 

`Can't perform a React state update on an unmounted component.` error. 

I am looking what I can do to fix this issue at the moment. And will also open an issue to the graphql-voyager repo

**Comment by MitchWijt** [comment]
@ravar17 @benjdlambert I found the issue in the graphql-voyager repo. I opened a PR to fix the issue. Once this has been merged into the voyager repo, I will update the plugin to work with the new version. 

PR can be found here if you want to keep track of it: https://github.com/graphql-kit/graphql-voyager/pull/336

**Comment by ravar17** [comment]
@MitchWijt  
Thanks for fixing the issue, however This PR is still open, how can we quickly merge ?

Thanks

**Comment by benjdlambert** [comment]
@ravar17 there's nothing we can do until the upstream PR is merged unfortunately, you could look into maybe applying the upstream change with `yarn patch` or `patch-package` to amend your locally installed node module so that you don't have to wait for the change to be merged https://bereghici.dev/blog/patch-an-npm-dependency-with-yarn

**Comment by ravar17** [comment]
Hello @benjdlambert @MitchWijt , Seems like PR(https://github.com/graphql-kit/graphql-voyager/pull/336) has been closed and issue has been merged in the another PR.  Could you please update the plugin to work with the new version. Also guide us which version of Graphql Voyager we need to use. 

Thanks

**Comment by MitchWijt** [comment]
hey @ravar17 I just sent him a message, it's indeed merged, but from what I can see not published to NPM yet

**Comment by ravar17** [comment]
Hello @MitchWijt, any updates on NPM yet ?

**Comment by MitchWijt** [comment]
Yes, will update the plugin today and test it out

**Comment by MitchWijt** [comment]
@ravar17 created the PR: https://github.com/backstage/backstage/pull/19317
