### ISSUE TITLE
🚀 Feature: Displaying an alert popup everytime the Playlist is created or deleted, similar to other backstage activities

### ISSUE THREAD

**Issue by AmbrishRamachandiran** [backstage/backstage#18747]
### 🔖 Feature description

Displaying an alert popup every time the Playlist is created or deleted, similar to other backstage activities.
The popup will be disappeared after some seconds
This will help users to experience good UI experience

### 🎤 Context

Displaying an alert popup every time the Playlist is created or deleted, similar to other backstage activities.
The popup will be disappeared after some seconds
This will help users to experience good UI experience

### ✌️ Possible Implementation

On Successful of creating playlist show below:
![image](https://github.com/backstage/backstage/assets/133481507/b7c7a86d-8053-479d-8b6d-c87997da434f)

On Successful of deleting playlist show below:

![image](https://github.com/backstage/backstage/assets/133481507/0071724b-1c6c-4885-b9b6-85794f2d401f)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by AmbrishRamachandiran** [comment]
Please assign this to me as iam willing to submit PR

**Comment by kuangp** [comment]
Makes sense - @AmbrishRamachandiran assigned to you. Thanks!
