### ISSUE TITLE
🐛 Bug Report: Visibility filter in the GithubEntityProvider is case-sensitive

### ISSUE THREAD

**Issue by alper98** [backstage/backstage#18745]
### 📜 Description

When utilizing the `GithubEntityProvider` with events support and applying the visibility filter to either `private` or `internal`, an issue arises due to inconsistent casing in the visibility field of the payload received in the `findCatalogFiles` and `onRepoPush` functions. The problem stems from the fact that these functions use `matchesFilters`, which, in turn, employs `satisfiesVisibilityFilter` to validate the visibility of repositories. Unfortunately, `satisfiesVisibilityFilter` is case-sensitive, causing potential mismatches.

Here is an example of a repository from findCatalogFiles
```json
{
  url: "https://github.com/REDACTED/REDACTED",
  name: "REDACTED",
  defaultBranchRef: "main",
  repositoryTopics: [
  ],
  isArchived: false,
  isFork: false,
  isCatalogInfoFilePresent: true,
  visibility: "INTERNAL",  <--- Capitalized
}
```
Here is an example of a repository from onRepoPush
```json
{
  url: "https://github.com/REDACTED/REDACTED",
  name: "REDACTED",
  defaultBranchRef: "main",
  repositoryTopics: [
  ],
  isArchived: false,
  isFork: false,
  isCatalogInfoFilePresent: true,
  visibility: "internal",  <--- Lowercase
}
```
Notice the difference in casing in visibility. This becomes an issue in `matchesFilters` that uses `satisfiesVisibilityFilter` to validate the visibility, and `satisfiesVisibilityFilter` is case sensitive

### 👍 Expected behavior

`satisfiesVisibilityFilter` becomes case-insensitive, and both `INTERNAL` and `internal` satifies the filter

### 👎 Actual Behavior with Screenshots

Here is an example of a repository from findCatalogFiles
```json
{
  url: "https://github.com/REDACTED/REDACTED",
  name: "REDACTED",
  defaultBranchRef: "main",
  repositoryTopics: [
  ],
  isArchived: false,
  isFork: false,
  isCatalogInfoFilePresent: true,
  visibility: "INTERNAL",  <--- Capitalized
}
```
Here is an example of a repository from onRepoPush
```json
{
  url: "https://github.com/REDACTED/REDACTED",
  name: "REDACTED",
  defaultBranchRef: "main",
  repositoryTopics: [
  ],
  isArchived: false,
  isFork: false,
  isCatalogInfoFilePresent: true,
  visibility: "internal",  <--- Lowercase
}
```

### 👟 Reproduction steps

In `app-config.yml`provide a valid provider with events support under github under catalog, and set the visibility to internal.

Ingest into your catalog, and then try to modify the catalog.yml file.

### 📃 Provide the context for the Bug.

Changes in catalog.yml files are not reflected or entities from the org is not ingested as both cases can not be satisfied

### 🖥️ Your Environment

OS:   Darwin 22.5.0 - darwin/arm64
node: v16.16.0
yarn: 1.22.19
cli:  0.22.6 (installed)
backstage:  1.13.2

Dependencies:
  @backstage/app-defaults                          1.3.0
  @backstage/backend-app-api                       0.4.2, 0.4.4, 0.4.5
  @backstage/backend-common                        0.15.2, 0.18.4, 0.19.0, 0.19.1
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.1, 0.5.3, 0.5.4
  @backstage/backend-tasks                         0.4.3, 0.5.1, 0.5.3, 0.5.4
  @backstage/catalog-client                        1.4.1, 1.4.2, 1.4.3
  @backstage/catalog-model                         1.3.0, 1.4.0, 1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.6
  @backstage/config-loader                         1.2.0, 1.3.1, 1.3.2
  @backstage/config                                1.0.7, 1.0.8
  @backstage/core-app-api                          1.7.0, 1.8.0
  @backstage/core-components                       0.11.2, 0.12.4, 0.12.5, 0.13.0, 0.13.1, 0.13.2
  @backstage/core-plugin-api                       1.5.2, 1.5.1
  @backstage/dev-utils                             1.0.14
  @backstage/errors                                1.1.5, 1.2.0, 1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.2, 0.1.4, 0.1.5
  @backstage/integration-react                     1.1.12, 1.1.13
  @backstage/integration                           1.4.4, 1.4.5, 1.5.0, 1.5.1
  @backstage/plugin-api-docs                       0.9.2
  @backstage/plugin-auth-backend                   0.18.2
  @backstage/plugin-auth-node                      0.2.13, 0.2.15, 0.2.16
  @backstage/plugin-catalog-backend-module-github  0.2.7
  @backstage/plugin-catalog-backend                1.9.0
  @backstage/plugin-catalog-common                 1.0.13, 1.0.14, 1.0.15
  @backstage/plugin-catalog-graph                  0.2.29
  @backstage/plugin-catalog-import                 0.9.7
  @backstage/plugin-catalog-node                   1.3.5, 1.4.0
  @backstage/plugin-catalog-react                  1.7.0, 1.5.0, 1.6.0
  @backstage/plugin-catalog                        1.10.0, 1.11.0
  @backstage/plugin-events-backend-module-aws-sqs  0.1.6
  @backstage/plugin-events-backend-module-github   0.1.6
  @backstage/plugin-events-backend                 0.2.5
  @backstage/plugin-events-node                    0.2.5
  @backstage/plugin-explore-backend                0.0.6
  @backstage/plugin-explore-common                 0.0.1
  @backstage/plugin-explore-react                  0.0.28
  @backstage/plugin-explore                        0.4.2
  @backstage/plugin-github-actions                 0.5.17
  @backstage/plugin-github-deployments             0.1.48
  @backstage/plugin-home                           0.4.31, 0.5.1
  @backstage/plugin-org                            0.6.7
  @backstage/plugin-permission-backend             0.5.19
  @backstage/plugin-permission-common              0.7.5, 0.7.6, 0.7.7
  @backstage/plugin-permission-node                0.7.10, 0.7.7, 0.7.9
  @backstage/plugin-permission-react               0.4.12, 0.4.13
  @backstage/plugin-proxy-backend                  0.2.38
  @backstage/plugin-scaffolder-backend             1.13.1
  @backstage/plugin-scaffolder-common              1.2.7
  @backstage/plugin-scaffolder-node                0.1.2
  @backstage/plugin-scaffolder-react               1.3.0
  @backstage/plugin-scaffolder                     1.13.0
  @backstage/plugin-search-backend-module-catalog  0.1.0
  @backstage/plugin-search-backend-module-explore  0.1.0
  @backstage/plugin-search-backend-module-pg       0.5.5
  @backstage/plugin-search-backend-module-techdocs 0.1.0
  @backstage/plugin-search-backend-node            1.2.0
  @backstage/plugin-search-backend                 1.3.0
  @backstage/plugin-search-common                  1.2.3, 1.2.4, 1.2.5
  @backstage/plugin-search-react                   1.5.2, 1.6.0
  @backstage/plugin-search                         1.2.0
  @backstage/plugin-tech-radar                     0.6.3
  @backstage/plugin-techdocs-addons-test-utils     1.0.13
  @backstage/plugin-techdocs-backend               1.6.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.12
  @backstage/plugin-techdocs-node                  1.7.0
  @backstage/plugin-techdocs-react                 1.1.6, 1.1.5
  @backstage/plugin-techdocs                       1.6.1, 1.6.2
  @backstage/plugin-user-settings                  0.7.2
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.0, 1.3.1
  @backstage/theme                                 0.2.19, 0.3.0, 0.4.0
  @backstage/types                                 1.0.2, 1.1.0
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Alright, that's unfortunate that they have inconsistent casing. Feel free to get a fix started, it's very welcome! 🙏

**Comment by freben** [comment]
Assigned! 🙏

**Comment by npiyush97** [comment]
@freben help me if I got it right or wrong satisfiesVisibilityFilter is case sensitive and returns false if visibility is INTERNAL, internal
```
  const lowerCaseVisibilities = visibilities.map(v => v.toLowerCase());
  const lowerCaseVisibility = visibility.toLowerCase();

  return lowerCaseVisibilities.includes(lowerCaseVisibility);
```

**Comment by Rugvip** [comment]
@npiyush97 it's important to convert case using explicit locale, since some languages have logic that will conflict with the check. We stick to using `.toLocaleLowerCase('en-US')`

**Comment by npiyush97** [comment]
> @npiyush97 it's important to convert case using explicit locale, since some languages have logic that will conflict with the check. We stick to using `.toLocaleLowerCase('en-US')`

okay, but is the solution acceptable for pull request?

**Comment by npiyush97** [comment]
@alper98  can you test if this fix your issue
