### ISSUE TITLE
🚀 Feature: Make backstage-cli extensible

### ISSUE THREAD

**Issue by Antrakos** [backstage/backstage#18756]
### 🔖 Feature description

Provide extension points to `backstage-cli` in order to reuse some of its infra for custom goals. In particular, I'd like to configure my own plugin templates with injected best practices. For example, setup Material UI 5 instead of 4 which comes from default template when bootstraping FE plugin.

### 🎤 Context

Material UI migration highlighted need for custom templates as default ones always come with inherent delay. There may be more examples of customizations for `backstage-cli` in general and its templates in particular. The reasoning is very similar to Scaffolder, which `backstage-cli new` mimics on a repo level.

Well, it's technically possible and to some may be even more applicable to use Scaffolder templates for this. That's their main goal - bootstrapping component with best practices baked in.
However I'd argue that it's a bit of overkill for plain code generation of Backstage plugins as it also requires to have them catalogued, which may not be desired by some companies (for example, because those plugins could be private to the Backstage repo and may confuse devs when mixed with public reusable components).
Furthermore, `backstage-cli new` is the go-to solution for plugin development so it makes sense to build on top of it to keep the flow familiar.

### ✌️ Possible Implementation

The simplest solution would probably be the specific folder structure in your Backstage monorepo where custom templates are stored. Then this is read by the `backstage-cli` and displayed as option, maybe with some configuration file to select only subset of options, etc.
More complicated, but versatile option would be a plugin architecture when extra templates come from some npm packages, that can be wired as devDependencies. `backstage-cli` would scan for them, recognise and load all the extensions. This would allow to separate those extensions from main monorepo if someone chooses so, or even share those packages publicly for open source use.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by ahhhndre** [comment]
Some related links as this has come before but is still a good idea!

https://github.com/backstage/backstage/issues/14585
https://github.com/backstage/backstage/issues/15818

**Comment by Rugvip** [comment]
Just wanted to say that this is something that we've been wanting to add, but don't have the capacity to design or implement. If anyone wants to take on driving this we can help out with guidance.
