### ISSUE TITLE
🚀 Feature: hook to run function when user logs out

### ISSUE THREAD

**Issue by hspitzley-czi** [backstage/backstage#18752]
### 🔖 Feature description

It would be nice to be able to run a function in response to a user logging out

### 🎤 Context

In my use case I cache some user-specific entries in the browser's localstorage and want to clear it when a user logs out

### ✌️ Possible Implementation

Pass an `onLogout` to the settings page (see PR)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by hspitzley-czi** [comment]
I made a PR here https://github.com/backstage/backstage/pull/18753

**Comment by freben** [comment]
Continuing the discussion [in the PR](https://github.com/backstage/backstage/pull/18753#issuecomment-1647734660)
