### ISSUE TITLE
🚀 Feature: Enable a group bookmarks that shares the most important links for team

### ISSUE THREAD

**Issue by younky-yang** [backstage/backstage#18765]
### 🔖 Feature description

For group kind of entity, it usually to list something that belongs to the team and can be shared with each team member. Though we have the links property, but it doesn't provide a good approach to share more bookmarks with detail description for developer to use. 

So propose a new plugin to implement a group bookmark card for the group kind entity, which allows team to define the bookmarks with a yaml file that specified through the group's entity annotation. 

Then when open the group entity page, the members of the group can easily get the bookmarks, also they can easily update the bookmark yaml file to keep all these information up to date.

### 🎤 Context

in many cases we have new members join our project, and members need to spend some effort to guide the developers to setup their environment and familiar with the websites, resources, tools they used, and they will bookmark all these information from their browser, but with time going, these information usually out of date or inconsistent between different members, so the group bookmark plugin should solve this problem and provide a better on boarding experience for a new project.

### ✌️ Possible Implementation

Develop a plugin(both backend and fronend) to handle the group kind entity's special annotation. If it has the annotation, then load the bookmark yaml file and parse the file, return the result to frontend plugin. 

Front end plugin will render the bookmarks into the card with different category, and also support paganition and search with the build in capability of backstage components. 

We have now an implementation on this and only support the bookmarks yaml file in github by using the github integration credential. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
<img width="1520" alt="Screenshot 2023-07-25 at 13 44 56" src="https://github.com/backstage/backstage/assets/10388011/7bfb3f76-21e7-4fcd-9a23-c2e7497b045f">

**Comment by freben** [comment]
Hm. Isn't this just a perfect fit for a techdocs page linked to by the group? That page can have any amount of rich information, not just a fixed links set.

**Comment by younky-yang** [comment]
> Hm. Isn't this just a perfect fit for a techdocs page linked to by the group? That page can have any amount of rich information, not just a fixed links set.

In some cases we didn't enable tech docs, also with this we can just have the information associated with the group entity. So you can starred the group entity and then easily to get the links.

**Comment by Rugvip** [comment]
We discussed the options here a bit but in the end we think it's best if you make this an internal customization for now, rather than something that we add to the main repo.

**Comment by younky-yang** [comment]
Sure. I may publish this as a standalone one in our own repo.

**Comment by nitinsj** [comment]
+1 We recently discussed this requirement in our organization. Our use case includes:

- Predefined organization-wide bookmarks
- Group/squad-level bookmarks
- Personal bookmarks
