### ISSUE TITLE
🐛 Bug Report: Broken links in documentation

### ISSUE THREAD

**Issue by keongalvin** [backstage/backstage#18763]
### 📜 Description

Some of the links in https://backstage.io/docs page are broken. 

### 👍 Expected behavior

Link should go to https://backstage.io/docs/overview/architecture-overview/#package-architecture instead.

### 👎 Actual Behavior with Screenshots

Redirected to https://backstage.io/docs/overview/architecture-overview.md#package-architecture, however no such page exist.

### 👟 Reproduction steps

1. Navigate to https://backstage.io/docs/backend-system/architecture/index#package-structure
2. Click on the link text titled "Backstage Architecture Overview"
3. Redirected to non-existent page https://backstage.io/docs/overview/architecture-overview.md#package-architecture

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
@keongalvin would you like to contribute the fix? 🙏

**Comment by abhijeetgauravm** [comment]
Can I work on this issue?

**Comment by KannappanChida** [comment]
@freben can i contribute ?
