### ISSUE TITLE
📖 Documentation: Write a guide about search decorators

### ISSUE THREAD

**Issue by camilaibs** [backstage/backstage#18764]
### 📜 Description

Improve the search plugins' how-to guides on Backstage official documentation to support adopters with "decorators" examples.

### 👍 Expected behavior

Have search decorator code examples on the [Backstage official documentation](https://backstage.io/), including recommendations about how to test them.

- As decorators are pretty similar to search collators, here are [collators examples](https://backstage.io/docs/features/search/getting-started#backend) to serve as inspiration for the decorator's guide;
- It is important write examples using and not the search backend system;
- Also, see [here](https://backstage.io/docs/reference/plugin-search-backend-node.testpipeline) a reference for testing search collators.

### 👎 Actual Behavior with Screenshots

There is only an explanation related to the [search decorator concept](https://backstage.io/docs/features/search/concepts#decorators), but there are no code examples in the [plugin guide](https://backstage.io/docs/features/search/how-to-guides).

### 👟 Reproduction steps

Access the official documentation, navigate to the [search plugin guides](https://backstage.io/docs/features/search/how-to-guides), and search for "decorator".
You will not find examples on how to create decorators.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
The steps for writing decorators are very similar to the decorators:

#### 1. Define the decorator and its factory classes

```tsx
import { Config } from '@backstage/config';
import { CatalogEntityDocument } from '@backstage/plugin-catalog-common';
import { DecoratorBase } from '@backstage/plugin-search-backend-node';
import { DocumentDecoratorFactory } from '@backstage/plugin-search-common';
import { Logger } from 'winston';

type CatalogDecoratorOptions = {
  logger: Logger;
};

/**
   * Decorators are classes responsible for extending collator documents with extra fields.
   * /
class CatalogDecorator extends DecoratorBase {
  private readonly logger: Logger;

  /**
   * Receives dependencies and options used by the decorator.
   * /
  constructor(_config: Config, logger: Logger) {
    super();
    this.logger = logger;
  }

  /**
   * Here you can perform a request or other asynchronous action to load the data that will extend the collator documents.
   * This method is called once, only when the decorator is initialized.
   * /
  async initialize(): Promise<void> {
    this.logger.info(
      `Requesting decorator data`,
    );
  }

/**
 *  Here is where we expected the decorations logic to live.
 * This method is called for each collator document, so we recommend memoizing heavy operations performed with the documents to avoid performance issues.
 * A decorated document is a collator document extended with extra fields added by a search decorator.
 * /
  async decorate(
    document: CatalogEntityDocument,
  ): Promise<CatalogEntityDocument> {
   // Here you return the extended document based on a particular condition or return the document as it was received in case the condition is not valid.
    return document;
  }

  /**
   * This method is called only once when the decoration process is finished, use this to unlock shared resources like to close database connections for example.
   * /
  async finalize(): Promise<void> {
    this.logger.info(
      `Completed catalog decoration process`,
    );
  }
}

/**
 * Decorator factories build decorator instances for a particular index type list, which means that the decorator will be applied only on documents that its type is included on the factory types array.
 */
export class CatalogDecoratorFactory implements DocumentDecoratorFactory
{
  private readonly config: Config;
  private readonly logger: Logger;
  /**
   * This is a required property and should define de collator types this factory builds decorators for.
  public readonly types: string[] = ['software-catalog'];

  private constructor(
    config: Config,
    options: CatalogDecoratorOptions,
  ) {
    this.config = config;
    this.logger = options.logger;
  }

  static fromConfig(
    config: Config,
    options: CatalogDecoratorOptions,
  ) {
    return new CatalogDecoratorFactory(config, options);
  }

  async getDecorator() {
    return new CatalogDecorator(this.config, this.logger);
  }
}
```

2. Add the decorator on the search index builder:

**Comment by tikabom** [comment]
@camilaibs anything actionable here?

**Comment by camilaibs** [comment]
> @camilaibs anything actionable here?

Hi @tikabom I would recommend you discuss it with the team and add it to @backstage/discoverability-maintainers backlog or ask the community for help by adding the "help wanted" label 🙂 .

**Comment by Adibov** [comment]
I needed this document for implementing a decorator and randomly found it through a search. Is this issue accepted so that I can create a PR to add documentation for decorators?
@camilaibs
