### ISSUE TITLE
🚀 Feature: Scaffolder Plugin, clickable URLs for task errors notification component

### ISSUE THREAD

**Issue by stanislavec** [backstage/backstage#18810]
### 🔖 Feature description

Alert component for Scaffolder plugin shows only error message ([source code](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/TaskPage/TaskErrors.tsx)). 
If message uncludes URL user can't click URL to proceed.

![telegram-cloud-photo-size-2-5334852133780048707-y](https://github.com/backstage/backstage/assets/34837948/e3dd487e-1881-4a96-8515-395a9b345f31)

### 🎤 Context

If error message contains URL, will be good to be able to click it. Check example below.

![telegram-cloud-photo-size-2-5334852133780048699-y](https://github.com/backstage/backstage/assets/34837948/46106afe-f40f-40ed-913c-664cdf1af0f5)

### ✌️ Possible Implementation

Since v. 1.13.0 same functionality is presented in [LogViewer](https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/LogViewer/LogLine.tsx). 

According to the [code](https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/DismissableBanner/DismissableBanner.tsx), DismissableBanner accepts message as ReactNode. So we can pass react component. 

Possible implementation is shown below:

```
const renderLink = ({
  attributes,
  content,
}: {
  attributes: { [attr: string]: any };
  content: string;
}) => {
  const { href, ...props } = attributes;
  return (
    <Link to={href} {...props}>
      {content}
    </Link>
  );
};

<DismissableBanner
        id={id.current}
        variant="warning"
        message={<Linkify options={{ render: renderLink }}>{error.message}</Linkify>}
 />
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
This alert is being replaced with our error panel in the next scaffolder iteration. That one won't support clickable links either though, but the links in the logs should be clickable since #17286
