### ISSUE TITLE
🐛 Bug Report: No kubernetes tab shows on service page

### ISSUE THREAD

**Issue by renexu** [backstage/backstage#18811]
### 📜 Description

No kubernetes tab shows on service page

### 👍 Expected behavior

the Kubernetes tab should be there

### 👎 Actual Behavior with Screenshots

![backstage](https://github.com/backstage/backstage/assets/1875056/660654ad-f7bd-4e50-984b-8d42151249e2)

### 👟 Reproduction steps

I followed the  instructions here https://backstage.io/docs/features/kubernetes/installation
did both frontend and backend

Configured my cluster in app-config.yaml

run `yarn dev`

also tried troubleshooting method and confirmed it was working

### 🖥️ Your Environment

OS:   Darwin 22.4.0 - darwin/x64
node: v16.15.0
yarn: 1.22.19
cli:  0.22.9 (installed)
backstage:  1.16.0

Dependencies:
  @backstage/app-defaults                          1.4.1
  @backstage/backend-app-api                       0.4.5
  @backstage/backend-common                        0.19.1
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.4
  @backstage/backend-tasks                         0.5.4
  @backstage/catalog-client                        1.4.3
  @backstage/catalog-model                         1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.2
  @backstage/cli                                   0.22.9
  @backstage/config-loader                         1.3.2
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.9.0
  @backstage/core-components                       0.13.3
  @backstage/core-plugin-api                       1.5.3
  @backstage/errors                                1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.5
  @backstage/integration-react                     1.1.15
  @backstage/integration                           1.5.1
  @backstage/plugin-api-docs                       0.9.6
  @backstage/plugin-app-backend                    0.3.47
  @backstage/plugin-auth-backend                   0.18.5
  @backstage/plugin-auth-node                      0.2.16
  @backstage/plugin-catalog-backend                1.11.0
  @backstage/plugin-catalog-common                 1.0.15
  @backstage/plugin-catalog-graph                  0.2.32
  @backstage/plugin-catalog-import                 0.9.10
  @backstage/plugin-catalog-node                   1.4.0
  @backstage/plugin-catalog-react                  1.8.0
  @backstage/plugin-catalog                        1.12.0
  @backstage/plugin-events-node                    0.2.8
  @backstage/plugin-github-actions                 0.6.1
  @backstage/plugin-kubernetes-backend             0.11.2
  @backstage/plugin-kubernetes-common              0.6.5
  @backstage/plugin-kubernetes                     0.9.3
  @backstage/plugin-org                            0.6.10
  @backstage/plugin-permission-common              0.7.7
  @backstage/plugin-permission-node                0.7.10
  @backstage/plugin-permission-react               0.4.14
  @backstage/plugin-proxy-backend                  0.2.41
  @backstage/plugin-scaffolder-backend             1.15.1
  @backstage/plugin-scaffolder-common              1.3.2
  @backstage/plugin-scaffolder-node                0.1.5
  @backstage/plugin-scaffolder-react               1.5.1
  @backstage/plugin-scaffolder                     1.14.1
  @backstage/plugin-search-backend-module-catalog  0.1.3
  @backstage/plugin-search-backend-module-pg       0.5.8
  @backstage/plugin-search-backend-module-techdocs 0.1.3
  @backstage/plugin-search-backend-node            1.2.3
  @backstage/plugin-search-backend                 1.3.3
  @backstage/plugin-search-common                  1.2.5
  @backstage/plugin-search-react                   1.6.3
  @backstage/plugin-search                         1.3.3
  @backstage/plugin-tech-radar                     0.6.6
  @backstage/plugin-techdocs-backend               1.6.4
  @backstage/plugin-techdocs-module-addons-contrib 1.0.15
  @backstage/plugin-techdocs-node                  1.7.3
  @backstage/plugin-techdocs-react                 1.1.8
  @backstage/plugin-techdocs                       1.6.5
  @backstage/plugin-user-settings                  0.7.5
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.1
  @backstage/theme                                 0.4.1
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jamieklassen** [comment]
The page you appear to be viewing in the screenshot is for a catalog Entity of kind `Component` and type `website` -- the linked instructions and the title of this issue are for Components of type `service`.
1. Is this a mistake? Do you also not see the tab on a proper service page?
1. Do you want the tab to _also_ appear on website pages?

**Comment by renexu** [comment]
> 

thanks for pointing out there are actually two different pages. 
I added the kubernetes to the websiteEntityPage and now it works just fine. 

thank you
