### ISSUE TITLE
🐛 Bug Report: Linguist plugin seeing errors for most entities

### ISSUE THREAD

**Issue by carlossmartini** [backstage/backstage#18826]
### 📜 Description

I'm seeing an error in the logs from the linguist plugin when trying to process most entities.  The error is :
path should be a `path.relative()`d string, but got /tmp/backstage-kuEEZ8

### 👍 Expected behavior

It should work or provide a better error message

### 👎 Actual Behavior with Screenshots

It actually fails and I'm not sure what the error is referring to especially considering there's at least 1 entity that it works for.

### 👟 Reproduction steps

1. Setup plug per the directions
2. Set useSourceLocation:true 
3. Set offline: true
4. Deploy and look at logs.

I also tried setting the relativePaths option to both true and false.  Seems like if set to true then I get less errors, but I still see the errors for a lot of entities.

### 📃 Provide the context for the Bug.

Only thing I changed from instructions was I set the useSourceLocation flag to true and the offline flag to true.

### 🖥️ Your Environment

1. Backstage version 1.13.2
2. Existing catalog which already had annotations for source location.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by awanlin** [comment]
Hi @carlossmartini, just a heads up that this has been fixed in PR https://github.com/backstage/backstage/pull/18757

If you want to use this now you can upgrade `@backstage/plugin-linguist-backend` to `0.3.2-next.0` which is the version with the fix. This won't be in the monthly release until August 15th.

**Comment by carlossmartini** [comment]
Thanks for letting me know @awanlin!  good to know I wasn't going crazy :) Sorry I missed the original issue, but appreciate you pointing me in the right direction!

**Comment by awanlin** [comment]
Oh, no worries @carlossmartini, there wasn't an issue for this. Started from a post on Discord and then went straight to a PR with a fix

**Comment by Rugvip** [comment]
Closing as fixed! 😁
