### ISSUE TITLE
🚀 Feature: Re-enable FOSSA license scanning for CNCF compliance?

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#18821]
### 🔖 Feature description

Is there interest in continuing some of the work to enable Backstage's FOSSA license compliance scanning? I noticed there was a flag in the CNCF CLO Monitor site suggesting Backstage didn't yet align to this aspect.  Seems since its last attempt, the FOSSA config file has changed from v2 to v3, in addition the `verify-fossa.yaml` workflow was manually disabled.

Is there interest in having the community attempt to try to get this fixed up and working?  The FOSSA API Key is statically hardcoded in the repo, so open source contributors could help, but there may be other nuance I or the community am lacking which infers this was either intentionally dropped or should not be picked back up.

Just wanted to check?

Current CNCF CLO Monitor report for Backstage which could also be improved as part of this work (if FOSSA enabled):
<img width="921" alt="image" src="https://github.com/backstage/backstage/assets/33203301/dcfa0691-2dc2-463b-a2ca-c0e857159a60">

### 🎤 Context

Originally attempted in Jan 2021:

FOSSA attempt was originally contributed by a member of CNCF: https://github.com/backstage/backstage/pull/4077
Then an attempt to improve it here: https://github.com/backstage/backstage/pull/4171

Workflow is currently disabled.

### ✌️ Possible Implementation

Running FOSSA locally, I notice the config file versioning has changed to now be v3 so there may have been some significant CLI updates since this was last attempted.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Yep let's try it again! 👍 It would be nice to have it enabled.

**Comment by adamdmharvey** [comment]
Is there any chance to add me to your Backstage FOSSA org account?  My user ID on FOSSA is "adaharve@cisco.com"; I can see my own free account, but the permissions in FOSSA I believe are entirely separate than those through GitHub and have to be explicitly set.

If you feel like there's any risk in that absolutely no problem. I'll continue to just play around with my free account for now!

**Comment by adamdmharvey** [comment]
@martina-if Noticed you had opened an issue in the FOSSA project issues list (https://github.com/fossas/fossa-cli/issues/1111) for the same issue I'm seeing scanning the Backstage repo.

Wondering, were you able to work around it, or somehow mark the two packages which lack a scope (e.g., `@backstage/`) to be ignored in some way?

Error:

```text
yarn project in "/Users/adaharve/Documents/github/backstage-backstage/": failed

>>> Relevant errors

  Error

    Couldn't find package for descriptor: Descriptor {descriptorScope = Nothing, descriptorName = "techdocs-cli-embedded-app", descriptorRange = "link:../techdocs-cli-embedded-app"}

    Traceback:
      - Validating lockfile
      - Lockfile V2 analysis
      - Project Analysis: YarnProjectType

  Error

    Couldn't find package for descriptor: Descriptor {descriptorScope = Nothing, descriptorName = "example-app", descriptorRange = "link:../app"}

    Traceback:
      - Validating lockfile
      - Lockfile V2 analysis
      - Project Analysis: YarnProjectType
```

**Comment by adamdmharvey** [comment]
Just for kicks, tried with the latest FOSSA CLI v3.8.4; same error, so the bug hasn't been patched yet.

```
Scan Summary
------------
fossa-cli version 3.8.34 (revision b78c3ba13e53 compiled with ghc-9.4)
fossa endpoint server version: N/A

6 projects scanned;  4 skipped,  1 succeeded,  1 failed,  1 analysis warning

* yarn project in "/Users/adamharvey/Documents/github/backstage/": failed
* npm project in "/Users/adamharvey/Documents/github/backstage/packages/cli/asset-types/": succeeded with 1 warning
* yarn project in "/Users/adamharvey/Documents/github/backstage/microsite/": skipped (exclusion filters)
* npm project in "/Users/adamharvey/Documents/github/backstage/packages/create-app/templates/default-app/examples/template/content/": skipped (non-production path filtering)
* npm project in "/Users/adamharvey/Documents/github/backstage/packages/eslint-plugin/src/__fixtures__/monorepo/": skipped (exclusion filters)
* yarn project in "/Users/adamharvey/Documents/github/backstage/storybook/": skipped (exclusion filters)
-
----------
yarn project in "/Users/adamharvey/Documents/github/backstage/": failed

>>> Relevant errors

  Error

    Couldn't find package for descriptor: Descriptor {descriptorScope = Nothing, descriptorName = "techdocs-cli-embedded-app", descriptorRange = "link:../techdocs-cli-embedded-app"}

    Traceback:
      - Validating lockfile
      - Lockfile V2 analysis
      - Project Analysis: YarnProjectType

  Error

    Couldn't find package for descriptor: Descriptor {descriptorScope = Nothing, descriptorName = "example-app", descriptorRange = "link:../app"}

    Traceback:
      - Validating lockfile
      - Lockfile V2 analysis
      - Project Analysis: YarnProjectType

----------
npm project in "/Users/adamharvey/Documents/github/backstage/packages/cli/asset-types/": succeeded with 1 warning

  Could not analyze edges between dependencies.

  Could not analyze deep dependencies.

  >>> Details

    We could not perform lockfile analysis for your nodejs project.

      Ensure valid lockfile exist and is readable prior to running fossa.
        For yarn package manager, you can perform: `yarn install` to install dependencies and generate lockfile.
        For node package manager, you can perform: `npm install` to install dependencies and generate lockfile.

    Refer to:
      - https://github.com/fossas/fossa-cli/blob/v3.8.34/docs/references/strategies/languages/nodejs/nodejs.md
      - https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json
      - https://classic.yarnpkg.com/lang/en/docs/yarn-lock/
      - https://yarnpkg.com/getting-started/qa#should-lockfiles-be-committed-to-the-repository

  Warning

    Lock files - yarn.lock or package-lock.json were not discovered.
```
