### ISSUE TITLE
🚀 Feature: Adding alert popup whenever user delete the entities from playlist entity table

### ISSUE THREAD

**Issue by AmbrishRamachandiran** [backstage/backstage#18836]
### 🔖 Feature description

Adding a pop-up notification anytime a user deletes an entity from the playlist entity table.

![image](https://github.com/backstage/backstage/assets/133481507/1d8b157b-d0a5-45ee-a6ef-29bab4ebddf4)

### 🎤 Context

Adding alert popup whenever user delete the entities from playlist entity table

### ✌️ Possible Implementation

Adding a pop-up notification anytime a user deletes an entity from the playlist entity table.

![image](https://github.com/backstage/backstage/assets/133481507/7f596464-e6d3-4e07-836a-647736b13223)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by AmbrishRamachandiran** [comment]
Assign it to me please as iam willing to submit PR

**Comment by Pavilion-devs** [comment]
@AmbrishRamachandiran @freben assign it to me. Willing to fix it if it has not

**Comment by AmbrishRamachandiran** [comment]
@Pavilion-devs @freben  i have fixed it in my forked repo just waiting for maintainers to assign it to me so that i can raise a PR

**Comment by Rugvip** [comment]
@AmbrishRamachandiran assigned! No need to wait for an assignment to raise a PR though, you can create a PR whenever. 😁

**Comment by AmbrishRamachandiran** [comment]
closing this as it got merged !!!
