### ISSUE TITLE
AzureDevOpsEntityProvider does not work with old <org>.visualstudio.com setup

### ISSUE THREAD

**Issue by JarrodJ83** [backstage/backstage#18877]
### 📜 Description

We use ADO but have not updated to using the latest URLs with "dev.azure.com" as the host. The `AzureDevOpsEntityProvider` checks to for this host to see if it ADO "isCloud" which determines which URL to use for search to crawl for new entities. In our case we are cloud hosted but still on "<org>.visualstudio.com" so the `isCloud` check returns false and causes a 404 not found to be returned when trying to run the host. 

I've changed this line to the following and it seems to fix things. I am happy to submit a PR for the change:

`const isCloud = (host) => host === "dev.azure.com" || host.endsWith('visualstudio.com');`

### 👍 Expected behavior

Successful response from search and entities found.

### 👎 Actual Behavior with Screenshots

404 response returned from search request

### 👟 Reproduction steps

Use the `AzureDevOpsEntityProvider` with a cloud hosted version of ADO that still uses the "visualstudio.com" domain.

### 📃 Provide the context for the Bug.

Service catalog is unable to do discovery

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @JarrodJ83, I'm one of the authors of the Azure DevOps plugin and generally help support Azure DevOps features/bugs/testing. I just wanted to adds some details and feedback:

The line in questions is here: https://github.com/backstage/backstage/blob/f39afab29f81825cbcd421bf22a6c94e243f0da6/plugins/catalog-backend-module-azure/src/lib/azure.ts#L40

Which is then only used here:
https://github.com/backstage/backstage/blob/f39afab29f81825cbcd421bf22a6c94e243f0da6/plugins/catalog-backend-module-azure/src/lib/azure.ts#L51-L54

Now the move away from `visualstudio.com` domains started in roughly 2018 (https://learn.microsoft.com/en-us/azure/devops/release-notes/2018/sep-10-azure-devops-launch#switch-existing-organizations-to-use-the-new-domain-name-url) but based on how small this change is I think it's safe to move forward with. 

Feel free to open a PR and tag me in it so I can help with the review, I'll also assign this issue to you 👍
