### ISSUE TITLE
🚀 Feature: Improve Kafka plugin UI for better lag visualisation for many partitions.

### ISSUE THREAD

**Issue by Dnomyar** [backstage/backstage#18873]
### 🔖 Feature description

The kafka plugin is great to visualise the lag across partitions and topics but very limited for a large number of partitions. The current table view does not allow an overall view. Having a view summing up the lag would be very beneficial.

Here is the page of the plugin: https://github.com/backstage/backstage/tree/master/plugins/kafka

### 🎤 Context

The context is when there are a lot of (100+) partitions. However, a very visual display would also be helpful for less partitions.

### ✌️ Possible Implementation

Some kind of (bar?) chart maybe. It would allow to see at a glance the lag across the partititons

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Alright, ideas are likely welcome here. If you make a PR with a suggestion it'd be appreciated. 🙏
