### ISSUE TITLE
🐛 Bug Report: TechDocs search does not include code snippets

### ISSUE THREAD

**Issue by KatharinaSick** [backstage/backstage#18884]
### 📜 Description

When searching in a TechDocs document, it is possible to search for any text but not for text inside code snippets. Code snippets should be searchable as well.

### 👍 Expected behavior

Text inside code snippets should be returned in the search results as well

### 👎 Actual Behavior with Screenshots

Text inside code snippets is not returned as a search result.

### 👟 Reproduction steps

1. Go to the [Running Backstage locally document](https://demo.backstage.io/docs/default/component/backstage/getting-started/running-backstage-locally/)
2. Enter "nvm install" in the search bar on top
3. The results do not include the `nvm install` from the code snippet in this document

### 🖥️ Your Environment

We reproduced this on the demo environment

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Thanks for logging this @KatharinaSick 👍 

Just wanted to note that as of this writing the Demo site is running the `1.17.0-next.0` release of Backstage and uses the Lunr search engine.

**Comment by KatharinaSick** [comment]
Thanks for the addition :slightly_smiling_face: 

We also observe this behavior on our internal Backstage instance which is running on a stable version and uses the Pg search engine.

If it's ok, we would contribute a fix soonish (probably in one or two weeks)

**Comment by awanlin** [comment]
Yes, if you have a fix that would be great. I'll assign this to you then 👍

**Comment by agentbellnorm** [comment]
@KatharinaSick, are you planning to work on this? If yes we can keep you assigned. If not, can you unassign yourself so others can pick it up?

**Comment by KatharinaSick** [comment]
I'm sorry - we actually planned to implement it within the last two weeks but then some unexpected issues came up. I'll release the ticket and just assign it to me again in case I start working on it :)

**Comment by agentbellnorm** [comment]
@KatharinaSick When I follow your reproduction steps I see the search term in the first two results, can you confirm this is still an issue?

Search: https://demo.backstage.io/search?query=nvm%20install



![Image](https://github.com/backstage/backstage/assets/7231170/cb405068-2dc9-4d7d-b65e-f99ce1995135)

**Comment by KatharinaSick** [comment]
Hi @agentbellnorm, I'm sorry for my slow reply but I somehow missed the notification. 

Unfortunately, it doesn't seem to be fully resolved. It works in this case but when searching for `npx @backstage/create-app` in [Getting started](https://demo.backstage.io/docs/default/component/backstage/getting-started/) the code result doesn't show up.
