### ISSUE TITLE
🐛 Bug Report: TechDocs search does not highlight a search result after clicking it

### ISSUE THREAD

**Issue by KatharinaSick** [backstage/backstage#18885]
### 📜 Description

When searching something in a TechDocs document and then clicking on a search result, I get to the correct section but have a hard time finding my result because it is not highlighted.

### 👍 Expected behavior

After clicking a search result, the searched text should be highlighted in the document

### 👎 Actual Behavior with Screenshots

I get to the correct section in the document but the search result is not highlighted which makes it hard to find it

### 👟 Reproduction steps

1. Navigate to the ]Backstage docs in the demo instance[(https://demo.backstage.io/docs/default/component/backstage)
2. Search for any word you want
3. Click on a search result

### 🖥️ Your Environment

Was reproduced in the demo environment

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Thanks for logging this @KatharinaSick 👍 

Just wanted to note that as of this writing the Demo site is running the `1.17.0-next.0` release of Backstage and uses the Lunr search engine.

**Comment by KatharinaSick** [comment]
Thanks for the addition :slightly_smiling_face: 

We also observe this behavior on our internal Backstage instance which is running on a stable version and uses the Pg search engine.

If it's ok, we would contribute a fix soonish (probably in one or two weeks)

**Comment by awanlin** [comment]
Yes, if you have a fix that would be great. I'll assign this to you then 👍

**Comment by agentbellnorm** [comment]
@KatharinaSick, are you planning to work on this? If yes we can keep you assigned. If not, can you unassign yourself so others can pick it up?

**Comment by KatharinaSick** [comment]
I'm sorry - we actually planned to implement it within the last two weeks but then some unexpected issues came up. I'll release the ticket and just assign it to me again in case I start working on it :)

**Comment by knowacki23** [comment]
Hey @awanlin,
May I ask you to assign this issue to me?
(I think that I'm unable to assign it myself - I cannot find the `assign` button anywhere :sweat_smile:)

**Comment by awanlin** [comment]
Sure @knowacki23, this issue has ben assigned to you

**Comment by tikabom** [comment]
Hello, @knowacki23 do you intend to pick work on this issue up again?

**Comment by emmaindal** [comment]
Hello @knowacki23 I'll open this up for the community to pick up, if you are working on it please let us know and I'll assign you again! Thank you
