### ISSUE TITLE
🚀 Feature: parseRepoUrl should provide an output url without parameters

### ISSUE THREAD

**Issue by electrofelix** [backstage/backstage#18909]
### 🔖 Feature description

It would be useful if the parseRepoUrl filter provided a more recognized formated version of the repository URL in addition to the separate fields as the RepoUrlPicker output that it parses is not well suited to appear in docs as a hyperlink.

### 🎤 Context

When generating the initial documents that are hosted on a backstage instance, it's useful to provide links directly to the repository inline at various points. However the current output of RepoUrlPicker is in the form `<host>?owner=<owner>&repo=<repo>` where as typically it would be useful to have `https://<host>/<owner>/<repo>` depending on which hosting service is being used.

It's also common for various files such as package.json or setup.py to include the repository URL which is then linked by package hosting services. While some might be able to handle the original format, many expect to have the form `<schema>://<host>/<path>`. While I've not tested it, I expect that most end up needing to construct something like the following to work around this:
```
https://${{ parameters.repoUrl | parseRepoUrl | pick('host') }}/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
```

For markdown files, rendering a URL will work, provided it is recognized, while it's been a while since I checked it, I'm pretty sure the default output of the RepoUrlPicker doesn't provide enough for most markdown rendering to spot that it's a URL.

Instead it would be more useful if it was possible to simply use the following in any location that benefits from the full URL:
```
${{ parameters.repoUrl | parseRepoUrl | pick('url') }}
```

While it's possible to get the final URL after a repository has been created, templating files as the initial contents usually need to be completed before this output would be available.

### ✌️ Possible Implementation

Update parseRepoUrl to add a url field as part of the output. Since there is already a switch statement for handling the different type of source control services, it should be possible to set the value appropriately within each block https://github.com/backstage/backstage/blob/5623a818b957b0ef3d44434cd4b8afbf9ae43f7d/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/util.ts#L74-L98

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
First, I'll mention that I believe you can replace the builtin function with your own, which does essentially `return { ...parseRepoUrl(input), url: computeUrlFor(input) }`, to get unblocked.

But besides that, yeah that sounds convenient. The only thing that concerns me is that then this function will have even more random per-provider code in it :) That's not a big deal though. Go ahead and make a PR and we'll review it.

**Comment by electrofelix** [comment]
Still relevant, just busy with other stuff and not yet got back to this.
