### ISSUE TITLE
🚀 Feature: Enable catalog Health

### ISSUE THREAD

**Issue by aswathysen** [backstage/backstage#18907]
### 🔖 Feature description

This can be a front end + backend plugin integration where we should be able to identify if the catalog / documentation associated with the catalog is recent or stale with a proper timestamp giving visibilty to the consumers of the particular catalog. 

### 🎤 Context

In My case i want to display and possible create an issue if the catalog is stale or when modified

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by aswathysen** [comment]
@freben this plugin suggestion is to identify if the component that is added is recently updated or stale. whether the services are currently used, updated or not which includes the documentation and so on.

**Comment by aswathysen** [comment]
Can the plugin be modified based on each use case or is it general, i feel like tech-insights is more or less like a preset scorecard. and i believe we can customize more than that. But is it possible to make it based on a catalog component

**Comment by Rugvip** [comment]
@aswathysen you can customize the checks quite a lot, see https://roadie.io/backstage/plugins/tech-insights/ as well. If it doesn't fit then I think it likely makes sense for you to build a bespoke internal solution for this use-case.
