### ISSUE TITLE
🐛 Bug Report: Virtual Vehicle Docs "Not found"

### ISSUE THREAD

**Issue by ZieglmeierS** [backstage/backstage#18901]
### 📜 Description

We're not able to access the documentation for Virtual Vehicle. It was working yesterday last time.
Now we get a "Not found" error page saying: Looks like someone dropped the mic!

Link: https://techdocs.apps.mega.cariad.cloud/docs/default/component/vwac/virtual-veh/vv00-quick-start/

### 👍 Expected behavior

Documentation should be available.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/116161116/f5921867-9eca-45b3-95b3-d99b67d7a12a)

### 👟 Reproduction steps

Go to https://techdocs.apps.mega.cariad.cloud/docs/default/component/vwac/virtual-veh/vv00-quick-start/

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
This seems to be an accidental issue that shouldn't have been in the mainline project.
