### ISSUE TITLE
Kubernetes Backend plugin is not using caFile configuration in all the cases

### ISSUE THREAD

**Issue by gsasanelli** [backstage/backstage#18924]
### 📜 Description

The file 
plugins\kubernetes-backend\src\service\KubernetesProxy.ts
at line 161 is omitting the caFile configuration usage:
ca: bufferFromFileOrString('', cluster.caData)?.toString(),

### 👍 Expected behavior

caFile configuration must be used when it is configured. The fix could be something like:
ca: bufferFromFileOrString(cluster.caFile, cluster.caData)?.toString(),

### 👎 Actual Behavior with Screenshots

Line 161 in file plugins\kubernetes-backend\src\service\KubernetesProxy.ts
ca: bufferFromFileOrString('', cluster.caData)?.toString(),

### 👟 Reproduction steps

configure only caFile in kubernetes plugin configuration, will cause the problem

### 🖥️ Your Environment

Backstage 1.16.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jamieklassen** [comment]
A nice sample of a test covering a similar scenario:

https://github.com/backstage/backstage/blob/a359209c6d07f2c56423a517f7dafe9badf07236/plugins/kubernetes-backend/src/service/KubernetesFetcher.test.ts#L723-L766
