### ISSUE TITLE
🔌 Plugin: SDK Generation from OpenAPI or Postman Collection

### ISSUE THREAD

**Issue by dphuang2** [backstage/backstage#18920]
### 🔖 Summary

SDKs simplify inter-service communication by providing ergonomic and strongly-typed interfaces. At [Konfig](https://konfigthis.com/), we generate SDKs from OpenAPIs and Postman Collections. Our SDK generator could help internal engineering teams move faster and break less things.

### 🌐 Project website (if applicable)

https://konfigthis.com/

### ✌️ Context

- SDKs handle a lot of boilerplate code when integrating APIs
- SDKs help catch typos or type errors at compile time
- Engineering teams that operate in different languages can easily communicate over APIs
- SDKs are difficult to create and maintain for APIs, especially when they are changing often
- For engineering teams that haven't adopted gRPC or have a lot of existing REST APIs, OpenAPI or Postman may be the only path to generating SDKs for inter-service communication

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Anything that's remotely associated with accounts and/or cost - either for the maintainers or for adopters out there - will probably be a poor fit for the project. Also, we're not quite there in terms of establishing the OpenAPI contracts in the project in the first place, as an input to the journey towards generated SDKs. There's efforts ongoing on these topics already, eg #17470

**Comment by dphuang2** [comment]
Thanks for the reply.

1. What do you mean by “accounts and/or cost”?
1. I saw https://github.com/backstage/backstage/pull/17470 but I thought that PR is about the internal Backstage APIs as opposed to API type entities in the software catalog, which would be different than what I am proposing in this plugin.

**Comment by dphuang2** [comment]
@freben i've[ created a plugin](https://github.com/konfig-dev/backstage-plugin-konfig/tree/main/plugins/backstage-plugin-konfig) that integrates our own OpenAPI linter and looking for early users who are interested in SDK generation for their Backstage API entities. It is published and working.

Is this something I could add to the Backstage marketplace? Its free / requires no signup.

**Comment by freben** [comment]
Alright, I thought this referred to making SDKs for our own internal APIs, hence the "accounts or cost" comment. Could you describe some more then what the user flows and value add is, that you envision here?

**Comment by dphuang2** [comment]
@freben I just created a [pull request for the Plugin](https://github.com/backstage/backstage/pull/19261) :). Could you take a look?
