### ISSUE TITLE
🐛 Bug Report: Invalid @deprecated import paths provided across multiple files

### ISSUE THREAD

**Issue by Coderrob** [backstage/backstage#18932]
### 📜 Description

# Incorrect deprecated import paths

Multiple areas using `@deprecated` reference an invalid import path and will result in failure when a user attempts to actually import the non-existent packages. The comments reference the folder name _not_ the actual package name.

## backstage\plugins\catalog-backend\src\index.ts\
```
  39,29:  * @deprecated import from `@backstage/search-backend-module-catalog` instead
  45,29:  * @deprecated import from `@backstage/search-backend-module-catalog` instead
  57,29:  * @deprecated import from `@backstage/search-backend-module-catalog` instead
  64,29:  * @deprecated import from `@backstage/search-backend-module-catalog` instead
```

^^ should be `@backstage/plugin-search-backend-module-catalog`

## backstage\plugins\explore-backend\src\index.ts

```
  39,29:  * @deprecated import from `@backstage/search-backend-module-explore` instead
  45,29:  * @deprecated import from `@backstage/search-backend-module-explore` instead
  51,29:  * @deprecated import from `@backstage/search-backend-module-explore` instead
```

^^ should be `@backstage/plugin-search-backend-module-explore`

## backstage\plugins\techdocs-backend\src\search\index.ts
```
  28,29:  * @deprecated import from `@backstage/search-backend-module-techdocs` instead
  34,29:  * @deprecated import from `@backstage/search-backend-module-techdocs` instead
```

^^ should be `@backstage/plugin-search-backend-module-techdocs`

### 👍 Expected behavior

Documentation and references should be correct.

### 👎 Actual Behavior with Screenshots

N/A

### 👟 Reproduction steps

Please see comment with code paths along with the specific line numbers of the invalid deprecated code comments.

### 📃 Provide the context for the Bug.

Noticed deprecated warnings / strikethrough on my Backstage implementations around search. Noted that they were related to deprecations.

Went to the comments and attempted to import the correct packages to update the code. The package imports failed and I noted that the `plugin-` was missing from the prefix of the package references. 

Confirmed with the package.json for the specific packages that these deprecated comments were specified with invalid imports.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Makes sense! A PR to fix this would be very welcome 🙏

**Comment by Coderrob** [comment]
@freben posted up a PR => https://github.com/backstage/backstage/pull/18935

**Comment by Coderrob** [comment]
PR merged - closing
