### ISSUE TITLE
🐛 Bug Report: Renamed entities are not being picked up after renaming and deleting the orphan

### ISSUE THREAD

**Issue by miniengineer** [backstage/backstage#19069]
### 📜 Description

Today as an experiment I have changed the name of the catalog which is the source of component called `hyperion`.

Before renaming:
`hyperion.yaml`

After renaming:
`hyperion-test.yaml`

Backstage has picked that up, logging errors of having a conflict, now `hyperion-test.yaml` has `hyperion` but `hyperion.yaml` also has `hyperion` so backstage can't tell which one is the one, which is expected behaviour 👍 

Knowing that the previous `hyperion.yaml` is gone, going to the UI , to the `hyperion` component it tells me the source is gone and I can delete. Seeing the errors I though, ok, let's delete.

So now hyperion is gone. I waited like 1 hour, still gone. I've redeployed, still gone...

So, how is supposed this to come back?
I found [related issue](https://github.com/backstage/backstage/issues/14042#issuecomment-1280816922) and it mentions that

>he old entity remains with an orphan marker, and if you delete it (in the three-dots top right menu of the entity page, and note - delete, not unregister) **the new one will take its place as expected.**

But the new entity doesn't appear(

Important ❗❗❗

All our catalogs are stored in a single github repository and we use `GithubEntityProvider` to fetch them.
this is our catalogs setup from `app-config.yaml`

```
catalog:
  readonly: true
  rules:
    - allow: [Component, Domain, System, API, Group, User, Resource, Location]
  providers:
    github:
      generatedFactbooks:
        organization: '...'
        catalogPath: 'blabla-path/generated/*.yaml'
        filters:
          branch: 'develop'
          repository: 'repository-name'
```

### 👍 Expected behavior

After we delete the orphan entity, the new one should be picked up by the provider and appear in the catalog.

### 👎 Actual Behavior with Screenshots

Renamed entity doesn't appear in the catalog after re-running the provider.

### 👟 Reproduction steps

1. Rename any catalog `.yaml` file of an entity to `blabla-test.yaml`.
2. Re-deploy, wait for the conflict error to appear
3. Delete the old entity
4. Re-deploy

### 🖥️ Your Environment

```
OS:   Darwin 21.3.0 - darwin/x64
node: v18.7.0
yarn: 1.22.19
cli:  0.22.9 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                               1.4.1
  @backstage/backend-app-api                            0.4.5
  @backstage/backend-common                             0.19.1
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.3, 0.5.4
  @backstage/backend-tasks                              0.5.4
  @backstage/catalog-client                             1.4.3
  @backstage/catalog-model                              1.4.1
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.2
  @backstage/cli                                        0.22.9
  @backstage/config-loader                              1.3.2
  @backstage/config                                     1.0.8
  @backstage/core-app-api                               1.9.0
  @backstage/core-components                            0.12.5, 0.13.3
  @backstage/core-plugin-api                            1.5.3
  @backstage/dev-utils                                  1.0.17
  @backstage/errors                                     1.2.1
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.5
  @backstage/integration-react                          1.1.15
  @backstage/integration                                1.5.1
  @backstage/plugin-adr-common                          0.2.11
  @backstage/plugin-adr                                 0.6.3
  @backstage/plugin-api-docs                            0.9.6
  @backstage/plugin-app-backend                         0.3.47
  @backstage/plugin-auth-backend                        0.18.5
  @backstage/plugin-auth-node                           0.2.16
  @backstage/plugin-catalog-backend-module-aws          0.2.2
  @backstage/plugin-catalog-backend-module-github       0.3.2
  @backstage/plugin-catalog-backend                     1.11.0
  @backstage/plugin-catalog-common                      1.0.15
  @backstage/plugin-catalog-graph                       0.2.32
  @backstage/plugin-catalog-node                        1.4.0
  @backstage/plugin-catalog-react                       1.8.0
  @backstage/plugin-catalog                             1.12.0
  @backstage/plugin-events-node                         0.2.8
  @backstage/plugin-fossa                               0.2.52
  @backstage/plugin-github-actions                      0.6.1
  @backstage/plugin-github-pull-requests-board          0.1.14
  @backstage/plugin-home-react                          0.1.1
  @backstage/plugin-home                                0.5.4
  @backstage/plugin-kubernetes-backend                  0.11.2
  @backstage/plugin-kubernetes-common                   0.6.5
  @backstage/plugin-kubernetes                          0.9.3
  @backstage/plugin-org                                 0.6.10
  @backstage/plugin-permission-backend                  0.5.22
  @backstage/plugin-permission-common                   0.7.7
  @backstage/plugin-permission-node                     0.7.10
  @backstage/plugin-permission-react                    0.4.14
  @backstage/plugin-proxy-backend                       0.2.41
  @backstage/plugin-scaffolder-common                   1.3.2
  @backstage/plugin-search-backend-module-catalog       0.1.3
  @backstage/plugin-search-backend-module-elasticsearch 1.3.2
  @backstage/plugin-search-backend-module-techdocs      0.1.3
  @backstage/plugin-search-backend-node                 1.2.3
  @backstage/plugin-search-backend                      1.3.3
  @backstage/plugin-search-common                       1.2.5
  @backstage/plugin-search-react                        1.6.3
  @backstage/plugin-search                              1.3.3
  @backstage/plugin-sonarqube-backend                   0.2.1
  @backstage/plugin-sonarqube-react                     0.1.7
  @backstage/plugin-sonarqube                           0.7.1
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.31
  @backstage/plugin-tech-insights-backend               0.5.13
  @backstage/plugin-tech-insights-common                0.2.11
  @backstage/plugin-tech-insights-node                  0.4.5
  @backstage/plugin-tech-insights                       0.3.12
  @backstage/plugin-techdocs-backend                    1.6.4
  @backstage/plugin-techdocs-module-addons-contrib      1.0.15
  @backstage/plugin-techdocs-node                       1.7.3
  @backstage/plugin-techdocs-react                      1.1.8
  @backstage/plugin-techdocs                            1.6.5
  @backstage/plugin-user-settings                       0.7.5
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.4.1
  @backstage/theme                                      0.2.19, 0.4.1
  @backstage/types                                      1.1.0
  @backstage/version-bridge                             1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sanderaernouts** [comment]
I ran into something similar recently, although it was about renaming entities inside a YAML file: #18054
If I understand correctly, you did not rename an entity inside a YAML file, but you renamed the YAML file itself.

I think this happened: Backstage ingests `hyperion-test.yaml` as a location entity and detects that `hyperion.yaml` is no longer there. The ingestion pipeline then tries to read entities from the `hyperion-test.yaml`, and there is a conflict because an orphaned entity already exists from `hyperion.yaml`. You then deleted the orphaned entity and expected Backstage to pick up the entity from the`hyperion-test.yaml`. That does not happen, and I think the reason is that Backstage already processed `hyperion-test.yaml` when it detected the conflict. Since the `hyperion-test.yaml` has not changed, there is no reason for Backstage to reprocess the location; thus, the entity is not read from the renamed file. 

If this is the case, then forcing a refresh of the `hyperion-test.yaml` location entity should fix it:
- Go to `https://<your-backstage>/catalog?filters[kind]=location&filters[user]=all` and find the location entity for `hyperion-test.yaml`. 
- On the entity page, in the `about card`, click the `Schedule entity refresh` button:
![image](https://github.com/backstage/backstage/assets/6184673/a287fe78-6d95-47ac-8140-14a75d0c299c)

I don't know if this is a bug or just how the ingestion pipeline works, I'll leave that up to the maintainers. It would be nice if Backstage could somehow detect that the conflict is no longer there and reprocess the relevant files.

**Comment by miniengineer** [comment]
Wow, thank you so much for the reply 🙏 !!!

>If I understand correctly, you did not rename an entity inside a YAML file, but you renamed the YAML file itself.

Indeed  💯 

>On the entity page, in the about card, click the Schedule entity refresh button:

Thank you, I just clicked the button and hope it's going to refresh  and show the `hyperion` 🙏 

> Since the hyperion-test.yaml has not changed, there is no reason for Backstage to reprocess the location; thus, the entity is not read from the renamed file.

Oh, well kind of makes sense 🤷‍♀️ 

If the manual refresh works, then I have no issues 🙏

**Comment by miniengineer** [comment]
@sanderaernouts 

We have all the components in one github repository, so there's only one location.
I clicked the button and got notification `Refresh scheduled` and waited for an hour but so far no changes 🤔 

I checked backend tasks for `backstage_plugin_catalog`, but the schedule for `github-provider:generatedFactbooks:refresh` didn't change and it says that next run will start on August 7 👀 
`2023-08-07 17:22:33.1273+00`

So I am not sure whether me clicking the button in the UI actually triggers the refresh 🤔

**Comment by sanderaernouts** [comment]
The refresh should be near instant in my experience so that did not help it seems.

>We have all the components in one GitHub repository, so there's only one location.

Are all your entities in the same YAML file? As far as I know, a location in Backstage is a single YAML file, at least that is how it works for Azure DevOps. So you have to refresh the location entity for the specific YAML file. The GitHub provider might be different though.

**Comment by miniengineer** [comment]
>The refresh should be near instant in my experience so that did not help it seems.

😭  I was hoping it would help.

>Are all your entities in the same YAML file?

Each entity has its own factbook (YAML file), but we store them in a single repository in `generated_factbook` folder 👀 
But the location is indeed a single YAML file.

<img width="318" alt="Screen Shot 2023-08-04 at 17 50 50" src="https://github.com/backstage/backstage/assets/47711385/748f258c-0616-47eb-a7cb-9afe6bc46863">


I attached our `app-config.yaml` configuration for the github provider in the main post 👀

**Comment by sanderaernouts** [comment]
> Each entity has its own factbook (YAML file), but we store them in a single repository in generated_factbook folder 👀
But the location is indeed a single YAML file.

And this location is not `...........hyperion-test.yaml`?

> I attached our app-config.yaml configuration for the github provider in the main post 👀

Your config looks OK to me, but we don't use the GitHub provider, so I can't be sure.

**Comment by miniengineer** [comment]
nope, the location for all entities is the screenshot I added
`location:generated-cc...`

We don't have any locations other than that one 🤔

**Comment by sanderaernouts** [comment]
It should show in the targets:
![image](https://github.com/backstage/backstage/assets/6184673/2b0d66d8-276f-4cee-b1b0-3d0d262246e8)

**Comment by JordiPolo** [comment]
I work in the same team, first, thanks for all your answers.
I've checked the target for this one only location we have and it is:
`https://github.com/<org>/<repo>/blob/develop/test_factbooks/generated/*.yaml`

I think at some point in the past we did have many locations here, somehow that's all we got now.

**Comment by JordiPolo** [comment]
More information.
After deletion I've checked the following tables and I can't find any reference to the component name or the file.
- final_entities
- refresh_keys
- refresh_state
- refresh_state_references

 Still the new renamed file will not be ingested (and we have run that process multiple times, killed the container, etc). No idea how Backstage know to not ingest this particular file

**Comment by freben** [comment]
I believe that this may be another symptom of the state [described in this comment](https://github.com/backstage/backstage/issues/17083#issuecomment-1653164737).

Short summary: the new location DID try to emit the entity in a new place, which threw away the entity due to the conflict, and then due to the hashing optimization, didn't try emitting again. This is as of yet unresolved.

It's possible that changing the `result_hash` to some random string in the new location will make the entity magically appear again. Could you try that to confirm?

**Comment by miniengineer** [comment]
@freben 

Thank you for the answer.
>It's possible that changing the result_hash to some random string in the new location will make the entity magically appear again. Could you try that to confirm?

Since we don't have hyperion anymore in non of the tables (see https://github.com/backstage/backstage/issues/19069#issuecomment-1666666152) , I am not sure which record's `refresh_state.result_hash` should I edit? 🤔

**Comment by miniengineer** [comment]
ok, @freben thank you again very much.

I changed the `refresh_state.result_hash` of the location
`https://github.com/<org>/<repo>/blob/develop/test_factbooks/generated/*.yaml`

which I think you meant to do in the first place 👍 

It did work 👍 
however, the mysterious thing is that while it worked on my local after applying the suggested solution, `hyperion` appeared in our production by itself...

We didn't touch anything there 🤔

**Comment by miniengineer** [comment]
So in general I assume that it's not a good idea to rename a factbook without removing the soon-to-become-old factbook first so that issues like this won't occur?

**Comment by miniengineer** [comment]
I think we can close this issue since we found a solution.

Btw, if you use a [static location](https://backstage.io/docs/features/software-catalog/configuration/#static-location-configuration) instead of `GithubEntityProvider` plugin and fetching catalog from a github repository, this issue doesn't emerge.
