### ISSUE TITLE
🐛 Bug Report: Tech radar timeline component formatting

### ISSUE THREAD

**Issue by codingdiaz** [backstage/backstage#19222]
### 📜 Description

The formatting for table headers in the radar timeline component in the tech-radar plugin is a little off currently, with no clear way to update it via props. 

<img width="599" alt="Screenshot 2023-08-04 at 8 37 53 AM" src="https://github.com/backstage/backstage/assets/20445982/d3709e5c-d47e-4e5b-bb7d-10a36a060c20">

Some example styling could help fix this. 

```
div[data-testid="radar-description"] div[role="dialog"] {
    max-width: 900px
}

div[data-testid="radar-description"] table thead th:nth-child(1) {
    min-width: 6em;
    max-width: 8em;
}

div[data-testid="radar-description"] table thead th:nth-child(2) {
    min-width: 10em;
    max-width: 12em;
}

div[data-testid="radar-description"] table thead th:nth-child(3) {
    min-width: 8em;
    max-width: 10em;
}

div[data-testid="radar-description"] table thead th:nth-child(4) {
    min-width: 8em;
}
```

### 👍 Expected behavior

The table headers should show text on a single line along with ring and date items for table rows. 

### 👎 Actual Behavior with Screenshots

<img width="599" alt="Screenshot 2023-08-04 at 8 37 53 AM" src="https://github.com/backstage/backstage/assets/20445982/6ba13a96-0b74-4dab-9b60-5eeea303e7bf">

### 👟 Reproduction steps

1. Install the tech radar plugin
2. Add a tech radar item that has history
3. Click on the item to see it's history

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Sure, would appreciate help fixing this. Could be done even with inline styles if needed. Also, do avoid selecting on `testid` for production code.

**Comment by npiyush97** [comment]
@freben update on pull request review?
