### ISSUE TITLE
🚀 Feature: Add AWS Annotations to Kubernetes Cluster Resource

### ISSUE THREAD

**Issue by clementblaise** [backstage/backstage#19225]
### 🔖 Feature description

Add ability to define annotations to authenticate kubernetes clusters with AWS

### 🎤 Context

The feature would allow using `clusterLocatorMethods ` with the catalog to authenticate against kubernetes-clusters Resource. It would offer a generic ways to define (non-private) connection details instead using a static configuration file.

### ✌️ Possible Implementation

There are currently annotations that allows setting configuration parameters for Kubernetes clusters
https://github.com/backstage/backstage/blob/eac59a3d0b110a0e1a1aa4a9ee14d85f4e730538/plugins/kubernetes-common/api-report.md?plain=1#L23-L52

We could introduce annotations to support the AWS parameters:
https://github.com/backstage/backstage/blob/eac59a3d0b110a0e1a1aa4a9ee14d85f4e730538/plugins/kubernetes-backend/src/cluster-locator/ConfigClusterLocator.ts#L71-L75

The annotations could be :
* kubernetes.io/aws-assume-role
* kubernetes.io/aws-external-id

In he CatalogClusterLocator the annotation will have to be passed down to `ClusterDetails`
https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/cluster-locator/CatalogClusterLocator.ts#L57-L85

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jamieklassen** [comment]
Seems fair to me -- we overlooked the AWS-specific config values when we did #15812, since #15088 focused on the generic `ClusterDetails` fields. We were really mainly interested in `oidcTokenProvider` at the time, as I recall.

**Comment by jamieklassen** [comment]
#19304 actually resolved this!
