### ISSUE TITLE
🐛 Bug Report: Todo Search Filter in Entity page

### ISSUE THREAD

**Issue by vigneshTw** [backstage/backstage#19269]
### 📜 Description

In Backstage Application, When the Users select any of the Entity, when the user navigate to Todo , We are getting 400 error if no todos are available while filtering it. 

### 👍 Expected behavior

<img width="1717" alt="Screenshot 2023-08-08 at 6 55 59 PM" src="https://github.com/backstage/backstage/assets/118976569/cdb9da71-19d5-4200-8936-8634e7106a6d">

### 👎 Actual Behavior with Screenshots

We are getting 400: InputError

<img width="1717" alt="Screenshot 2023-08-08 at 6 51 56 PM" src="https://github.com/backstage/backstage/assets/118976569/87eee515-c223-44d2-9f2b-6d2cc3b519ec">

<img width="1717" alt="Screenshot 2023-08-08 at 6 52 45 PM" src="https://github.com/backstage/backstage/assets/118976569/770c5a53-0ca2-4fb8-8de0-95bff431b17e">

### 👟 Reproduction steps

Step:

1. Go to Live Backstage Application [https://demo.backstage.io/catalog/default/component/playback-order/todos](url)
2. Now user can able to see the catalog Page
3. Click any of the entities
4. In entity page, In top we have some tabs(Overview, Ci/Cd, etc...) 
5. Navigate to TODOS
6. User can able to see the filter options in the todos page(Default its empty)
7. Enter some values in filter options(Expected: No result found, Actual: 400: InputError)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by atchaya-suresh** [comment]
I have also seen this same error occurring to me when I try to reproduce this steps.

**Comment by npiyush97** [comment]
have a look => https://github.com/backstage/backstage/blob/master/plugins/todo/README.md

**Comment by npiyush97** [comment]
@Rugvip , can you help me with how to encode filters here.
https://github.com/backstage/backstage/blob/8f48d188a12616d20aa2df95f9213a4220e173b8/plugins/todo/src/api/TodoClient.ts#L70
filter should be "text%3D%2Axyz%2A" but instead fetching "text%3D*xyz*"

**Comment by Rugvip** [comment]
Thank you for the report! I ended up fixing this directly in #19321, sorry 😅. It turned out to be a quite weird issue where everything is URL encoded as much as it needs to be on the frontend, but the request is still rejected by the OpenAPI validator. Perhaps there's something we can configure in how the OpenAPI validators to make them more permissive? CC @sennyeya

**Comment by sennyeya** [comment]
@Rugvip There's an 'allowReserved' option for parameters that adds non-URL encoded characters that I use in catalog-backend. https://swagger.io/docs/specification/describing-parameters/ 

I'm on mobile right now so can't share a link, but it should be on the filter parameter there as well.

**Comment by Rugvip** [comment]
@sennyeya nice, thank you! 👍 As mentioned in the PR it would be nice to have some form of broader solution, but I think it's enough to add that option where needed for now.
