### ISSUE TITLE
🐛 Bug Report: service factory circular dependencies silently fail

### ISSUE THREAD

**Issue by marleypowell** [backstage/backstage#19264]
### 📜 Description

When creating a custom `rootConfig` service factory that depended on `rootLogger` the application would build successfully but the backend service would never start up and just silently hangs.

This is likely happening due to a circular dependency in service factories: `rootConfig -> rootLogger -> rootConfig`

### 👍 Expected behavior

Some kind of circular dependency warning similar to how angular webpack shows them:
![image](https://github.com/backstage/backstage/assets/55280588/0e467807-f1f5-4a67-bc75-bf8e46be4c21)

Also would it ideally make sense for the `rootLogger` to have no direct dependencies as to me seems like an essential dependency that can be used by any dependency?

### 👎 Actual Behavior with Screenshots

Custom `rootConfig` service factory that depends on `rootLogger`:
![image](https://github.com/backstage/backstage/assets/55280588/acc2b382-6b2d-4cf9-b7b3-dd9529740af0)

`rootLogger` service factory that depends on `rootConfig`:
![image](https://github.com/backstage/backstage/assets/55280588/364c1e5c-08e5-4f08-bab6-b503b10b23b8)

Console logs when running the backend. It builds successfully but the runtime doesn't seem to startup (it's hanging silently on something):
![image](https://github.com/backstage/backstage/assets/55280588/f1db7716-d9af-4ac3-b262-2f8891507158)

### 👟 Reproduction steps

Create a custom `rootConfig` service factory that depends on `rootLogger` to create a circular dependency in service factories: `rootConfig -> rootLogger -> rootConfig`

### 📃 Provide the context for the Bug.

I noticed that the `rootConfigServiceFactory` used `console.log` instead of the `LoggerService`. So for my custom config service factory I tried using the `rootLogger`.

![image](https://github.com/backstage/backstage/assets/55280588/18db39ca-dc66-476e-9d1e-cf7648a5291a)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
This will likely be a check to add in [ServiceRegistry](https://github.com/backstage/backstage/blob/cf66e1cd40fd2c2b7d1c5d039751e7d6186eaa99/packages/backend-app-api/src/wiring/ServiceRegistry.ts#L59).

**Comment by marleypowell** [comment]
> This will likely be a check to add in [ServiceRegistry](https://github.com/backstage/backstage/blob/cf66e1cd40fd2c2b7d1c5d039751e7d6186eaa99/packages/backend-app-api/src/wiring/ServiceRegistry.ts#L59).

I've had a go at fixing the issue and added additional test coverage.
