### ISSUE TITLE
🐛 Bug Report: MembersListCard link uses hardcoded catalog route path

### ISSUE THREAD

**Issue by ypetrych** [backstage/backstage#19289]
### 📜 Description

In case of using different from 'catalog' route paths clicking on any member in Group page leads to hardocded `/catalog/:namespace/user/${metaName}` path. 
It shouldn't be hardcoded and allow to use route paths different from 'catalog'.

### 👍 Expected behavior

Dynamic route path should be used here: 
https://github.com/backstage/backstage/blob/e8bebb6f5f7e20539511720778afc478510a5cc9/plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx#L108

### 👎 Actual Behavior with Screenshots

Hardcoded route path is used during navigation: 

<img width="399" alt="image" src="https://github.com/backstage/backstage/assets/36443694/f56cd74d-01f3-42ac-a004-a1036086806d">

### 👟 Reproduction steps

1. Setup Backstage with custom catalog route path:

`<Route path="custom-catalog" element={<CatalogIndexPage />} />`

2. Open any Group entity with Members.
3. Click on any Member.
4. User should be navigate to corresponding user page.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by steff-petro** [comment]
Hi @ypetrych, I can look into this bug. If someone is able to assign it to me I would appreciate it.
