### ISSUE TITLE
🐛 Bug Report: Plugin-catalog-backend-module-unprocessed version 0.1.1 error

### ISSUE THREAD

**Issue by ronballesteros** [backstage/backstage#19281]
### 📜 Description

Following the documentation and running docker build, we get the following:
```
6.827 packages/backend/src/plugins/catalog.ts:5:10 - error TS2724: '"@backstage/plugin-catalog-backend-module-unprocessed"' has no exported member named 'UnprocessedEntitiesModule'. Did you mean 'UnprocessedEntitesModule'?
6.827 
6.827 5 import { UnprocessedEntitiesModule } from '@backstage/plugin-catalog-backend-module-unprocessed';
6.827            ~~~~~~~~~~~~~~~~~~~~~~~~~
6.827 
6.828 
6.828 Found 1 error in packages/backend/src/plugins/catalog.ts:5
6.828 
6.897 error Command failed with exit code 2.
6.897 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Changing it to `UnprocessedEntitesModule` and running `yarn tsc` or docker build results in the following:
```
6.316 packages/backend/src/plugins/catalog.ts:17:5 - error TS2345: Argument of type 'import("/app/node_modules/knex/types/index").Knex<any, any[]>' is not assignable to parameter of type 'import("/app/node_modules/@backstage/plugin-catalog-backend-module-unprocessed/node_modules/knex/types/index").Knex<any, any[]>'.
6.316   The types of 'raw(...).transacting' are incompatible between these types.
6.316     Type '(trx: import("/app/node_modules/knex/types/index").Knex.Transaction<any, any[]>) => import("/app/node_modules/knex/types/index").Knex.Raw<any>' is not assignable to type '(trx: import("/app/node_modules/@backstage/plugin-catalog-backend-module-unprocessed/node_modules/knex/types/index").Knex.Transaction<any, any[]>) => import("/app/node_modules/@backstage/plugin-catalog-backend-module-unprocessed/node_modules/knex/types/index").Knex.Raw<any>'.
6.316       Types of parameters 'trx' and 'trx' are incompatible.
```

### 👍 Expected behavior

Should not run into any issues.

### 👎 Actual Behavior with Screenshots

N/A

### 👟 Reproduction steps

Follow the readme here: https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-unprocessed

### 📃 Provide the context for the Bug.

Want to keep up to date on failed/pending entity requests.

### 🖥️ Your Environment

```
```
OS:   Darwin 22.6.0 - darwin/arm64
node: v18.0.0
yarn: 1.22.19
cli:  0.22.9 (installed)
backstage:  1.16.0

Dependencies:
  @backstage/app-defaults                              1.4.1
  @backstage/backend-app-api                           0.4.5
  @backstage/backend-common                            0.19.1
  @backstage/backend-dev-utils                         0.1.1
  @backstage/backend-plugin-api                        0.5.4
  @backstage/backend-tasks                             0.5.4
  @backstage/catalog-client                            1.4.3
  @backstage/catalog-model                             1.4.1
  @backstage/cli-common                                0.1.12
  @backstage/cli-node                                  0.1.2
  @backstage/cli                                       0.22.9
  @backstage/config-loader                             1.3.2
  @backstage/config                                    1.0.8
  @backstage/core-app-api                              1.9.0
  @backstage/core-components                           0.12.5, 0.13.3
  @backstage/core-plugin-api                           1.5.3
  @backstage/errors                                    1.2.1
  @backstage/eslint-plugin                             0.1.3
  @backstage/integration-aws-node                      0.1.5
  @backstage/integration-react                         1.1.15
  @backstage/integration                               1.5.1
  @backstage/plugin-api-docs                           0.9.6
  @backstage/plugin-app-backend                        0.3.47
  @backstage/plugin-auth-backend                       0.18.5
  @backstage/plugin-auth-node                          0.2.16
  @backstage/plugin-catalog-backend-module-unprocessed 0.1.1
  @backstage/plugin-catalog-backend                    1.11.0
  @backstage/plugin-catalog-common                     1.0.15
  @backstage/plugin-catalog-graph                      0.2.32
  @backstage/plugin-catalog-import                     0.9.10
  @backstage/plugin-catalog-node                       1.4.0
  @backstage/plugin-catalog-react                      1.8.0
  @backstage/plugin-catalog-unprocessed-entities       0.1.1
  @backstage/plugin-catalog                            1.12.0
  @backstage/plugin-events-node                        0.2.8
  @backstage/plugin-github-actions                     0.6.1
  @backstage/plugin-org                                0.6.10
  @backstage/plugin-permission-common                  0.7.7
  @backstage/plugin-permission-node                    0.7.10
  @backstage/plugin-permission-react                   0.4.14
  @backstage/plugin-proxy-backend                      0.2.41
  @backstage/plugin-scaffolder-backend                 1.15.1
  @backstage/plugin-scaffolder-common                  1.3.2
  @backstage/plugin-scaffolder-node                    0.1.5
  @backstage/plugin-scaffolder-react                   1.5.1
  @backstage/plugin-scaffolder                         1.14.1
  @backstage/plugin-search-backend-module-catalog      0.1.3
  @backstage/plugin-search-backend-module-pg           0.5.8
  @backstage/plugin-search-backend-module-techdocs     0.1.3
  @backstage/plugin-search-backend-node                1.2.3
  @backstage/plugin-search-backend                     1.3.3
  @backstage/plugin-search-common                      1.2.5
  @backstage/plugin-search-react                       1.6.3
  @backstage/plugin-search                             1.3.3
  @backstage/plugin-tech-radar                         0.6.6
  @backstage/plugin-techdocs-backend                   1.6.4
  @backstage/plugin-techdocs-module-addons-contrib     1.0.15
  @backstage/plugin-techdocs-node                      1.7.3
  @backstage/plugin-techdocs-react                     1.1.8
  @backstage/plugin-techdocs                           1.6.5
  @backstage/plugin-user-settings                      0.7.5
  @backstage/release-manifests                         0.0.9
  @backstage/test-utils                                1.4.1
  @backstage/theme                                     0.2.19, 0.4.1
  @backstage/types                                     1.1.0
  @backstage/version-bridge                            1.0.4
✨  Done in 2.04s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @ronballesteros, there was a typo in the code which was fixed in this PR: https://github.com/backstage/backstage/pull/18649. This change has been released as part of the `next` weekly releases already and will be released as part of the `main` monthly release next week on August 15th

Based on this can we close this issue?

**Comment by ronballesteros** [comment]
Sounds good.  Thank you @awanlin
