### ISSUE TITLE
🐛 Bug Report: Database timeouts during CI Tests

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#19299]
### 📜 Description

I've seen numerous CI failures for PRs, mostly for renovate patches, where the CI Test steps are timing out (in particular on Node 18, anecdotally) due to ETIMEDOUT reset timeouts, and a few Knex database time outs.

It seems specifically related to the databases.

https://github.com/backstage/backstage/blob/8f48d188a12616d20aa2df95f9213a4220e173b8/.github/workflows/ci.yml#L201-L207

### 👍 Expected behavior

There should be no timeouts in the tests, and the tests should be able to run smoothly to validate the inherent changes, rather than being flaky.

### 👎 Actual Behavior with Screenshots

In this first one, Node 18 (the one which anecdotally I see failing a lot) with an ETIMED OUT error:

<img width="1332" alt="image" src="https://github.com/backstage/backstage/assets/33203301/2d608bd2-922e-498e-9db9-16ba870d8eaf">

https://github.com/backstage/backstage/actions/runs/5809934041/job/15749962778

```
Summary of all failing tests
FAIL plugins/catalog-backend/src/database/operations/provider/deleteWithEagerPruningOfChildren.test.ts (50.859 s)
  ● deleteWithEagerPruningOfChildren › works for the simple path, "MYSQL_8"

    Failed to connect to the database to make sure that 'backstage_plugin_dbab70e8466dd2c427647388af1e6aa072' exists, Error: connect ETIMEDOUT

      354 |           await ensureDatabaseExists(pluginConfig, databaseName);
      355 |         } catch (error) {
    > 356 |           throw new Error(
          |                 ^
      357 |             `Failed to connect to the database to make sure that '${databaseName}' exists, ${error}`,
      358 |           );
      359 |         }

      at ../../../packages/backend-common/src/database/DatabaseManager.ts:356:17
      at TestDatabases.init (../../../packages/backend-test-utils/src/database/TestDatabases.ts:154:24)
      at createDatabase (database/operations/provider/deleteWithEagerPruningOfChildren.test.ts:32:18)
      at database/operations/provider/deleteWithEagerPruningOfChildren.test.ts:83:20
```

---

Another one, slightly different. In this one below, the Node 16 has a Knex timeout failure, while the Node 18 has the previous ETIMED error.

<img width="1332" alt="image" src="https://github.com/backstage/backstage/assets/33203301/6420646e-141c-47e3-8b9e-695c61c68732">

https://github.com/backstage/backstage/actions/runs/5803657262/job/15732165571

```
Summary of all failing tests
FAIL packages/backend-test-utils/src/database/TestDatabases.test.ts (42.235 s)
  ● TestDatabases › each create › creates distinct "POSTGRES_13" databases

    Failed to connect to the database to make sure that 'backstage_plugin_db7162f99179b0e51243f0f6b3f8b502c8' exists, KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

      354 |           await ensureDatabaseExists(pluginConfig, databaseName);
      355 |         } catch (error) {
    > 356 |           throw new Error(
          |                 ^
      357 |             `Failed to connect to the database to make sure that '${databaseName}' exists, ${error}`,
      358 |           );
      359 |         }

      at ../../backend-common/src/database/DatabaseManager.ts:356:17
      at TestDatabases.init (database/TestDatabases.ts:154:24)
      at database/TestDatabases.test.ts:48:21
```

### 👟 Reproduction steps

Can't cleanly reproduce, but you can see the failures in the Actions view here:
https://github.com/backstage/backstage/actions/workflows/ci.yml?query=is%3Afailure

(Note ALL of these aren't the same, but checking, all of the ones on branches with `renovate/` in the front DO seem to be related.)

### 📃 Provide the context for the Bug.

The tests in question take from 20-30 minutes to run; so having them be flaky is particularly impacting as rerunning takes a long time.

### 🖥️ Your Environment

GitHub Actions CI environment.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Yep we've tried a few things but nothing has been a proper fix. Any insights or ideas for how to fix this from anyone would be appreciated! 🙏

**Comment by PeteLevineA** [comment]
@freben Have the flakes mentioned above been solved with the above merge requests? Or still need help wanted?

**Comment by freben** [comment]
Mine above had no effect but other fixes merged after that reduced it to happen much more seldom. It's still an issue and still not completely understood, but not as blocking as before

**Comment by benjdlambert** [comment]
Gonna close this as I've not seen this in a while :tada: can re-open if it rears it's head again!
