### ISSUE TITLE
🚀 Feature: Add warning when using dummy tokenManager

### ISSUE THREAD

**Issue by VladMasarik** [backstage/backstage#19313]
### 🔖 Feature description

Add log into the `noop()` function that only a dummy token manager is initiated.

### 🎤 Context

When setting up service to service authentication I spent a lot of time debugging why the token manager is not working properly, and returning empty strings as tokens.
https://backstage.io/docs/auth/service-to-service-auth

Eventually I found out that the token manager was never properly initiated. It is even the first thing that the documentation suggests. However, considering how easy it is to start the token manager, just pass in config and logger, and how critical part it seems to be, I assumed it was already initiated. This unfortunately, led to a lot of frustration and wasted time, arguably I shouldn't be assuming things so it is fully my fault.

Arguably though, it might be tricky to implement since the dummy token manager has no access to logger, and maybe we want a low barrier of entry when creating new projects. I would fully agree with it, in such a case feel free to close this issue. I would however argue that keeping the dummy token manager as a default is not worth it, especially if the initialization is so simple, and I would argue that service to service communication is very common. Especially, if your company has need for Backstage, then more than likely it will be a heavy user of it.

### ✌️ Possible Implementation

I feel that having just a single log saying that the token manager is a dummy / mock would be very helpful for very low effort. In any of these places seems good?
https://github.com/backstage/backstage/blob/master/packages/backend-common/src/tokens/ServerTokenManager.ts#L36
https://github.com/backstage/backstage/blob/master/packages/backend-common/src/tokens/ServerTokenManager.ts#L73

Maybe even better, instead of generating new project with
```
const tokenManager = ServerTokenManager.noop();
```
as default, just create the new project with
```
const tokenManager = ServerTokenManager.fromConfig(config, { logger: root });
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Happy to move towards deprecating `ServerTokenManager.noop()`. I think the proper implementation behaves fairly well in most cases, including not getting in the way during development. There might be some cases where it interacts poorly with authentication, but we'll want to uncover those. In the new backend system we're installing a proper token manager by default.
