### ISSUE TITLE
🐛 Bug Report: Github Actions Plugin does not correctly display the number of github actions in table when filter is applied

### ISSUE THREAD

**Issue by Zaperex** [backstage/backstage#19310]
### 📜 Description

After registering [my catalog entry](https://github.com/janus-idp/backstage-showcase/blob/main/catalog-entities/components/showcase.yaml), the table of Github Actions from the [Github Actions Plugin](https://github.com/backstage/backstage/tree/master/plugins/github-actions), specifically the `EntityGithubActionsContent` component, does not display the correct number of Github Actions per page when a filter is applied. 

 It can also be observed that no matter what filter is applied, the total number of items in the table does not change.

### 👍 Expected behavior

Each page will have the right amount of actions when a filter is applied no matter what the size of each page is (5, 10 or 20)
When a filter is applied, all actions that do not match the filter are removed from the table (the number of github actions in the table should decrease, and so should the number of pages in the table)

It should function similar to how the Github Pull Requests plugin's `EntityGithubPullRequestsContent` component (from [roadiehq](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/backstage-plugin-github-pull-requests)) functions when filtering.

[Github Pull Request Plugin Demonstration](https://github.com/backstage/backstage/assets/50030060/f4f1f9a3-e6c0-4bf4-a3ca-555a99c81eca)

### 👎 Actual Behavior with Screenshots

The filter will only display the actions that match the filter for each page (actions that do not match the filters are not displayed but will still take up the slot in the page).

This means if I filter for something like Docker Build on a page with 5 entries where only 1 Action is a Docker Build, then the page of 5 entries will only display 1 entry with Docker build rather than 5 entries with Docker build.

The same behavior occurs when you change the page size to 10 or 20 entries.

Additionally, if no actions match the filter, the user will be left with a bunch of empty pages instead of one empty page.

[Github Actions Plugin Demonstration](https://github.com/backstage/backstage/assets/50030060/4d62eb50-83ca-465f-9052-cef9940b6125)

### 👟 Reproduction steps

1. Have a github repository with a few github actions/workflows completed.
2. Register the github repository as a component into backstage
3. Try to filter the github actions by something (enter anything)
4. Observe empty gaps between actions that match the filter resulting in incorrect number of actions per page. 

### 🖥️ Your Environment

OS:   Linux 6.4.8-200.fc38.x86_64 - linux/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.22.9 (installed)
backstage:  1.16.0

Dependencies:
  @backstage/app-defaults                            1.4.1
  @backstage/backend-app-api                         0.4.5
  @backstage/backend-common                          0.18.5, 0.19.1
  @backstage/backend-dev-utils                       0.1.1
  @backstage/backend-plugin-api                      0.5.4
  @backstage/backend-tasks                           0.5.4
  @backstage/catalog-client                          1.4.3
  @backstage/catalog-model                           1.4.1
  @backstage/cli-common                              0.1.12
  @backstage/cli-node                                0.1.2
  @backstage/cli                                     0.22.9
  @backstage/config-loader                           1.3.2
  @backstage/config                                  1.0.8
  @backstage/core-app-api                            1.9.0
  @backstage/core-components                         0.13.3
  @backstage/core-plugin-api                         1.5.3
  @backstage/errors                                  1.2.1
  @backstage/eslint-plugin                           0.1.3
  @backstage/integration-aws-node                    0.1.5
  @backstage/integration-react                       1.1.15
  @backstage/integration                             1.5.1
  @backstage/plugin-api-docs                         0.9.6
  @backstage/plugin-app-backend                      0.3.47
  @backstage/plugin-auth-backend                     0.18.5
  @backstage/plugin-auth-node                        0.2.16
  @backstage/plugin-azure-devops-backend             0.3.26
  @backstage/plugin-azure-devops-common              0.3.0
  @backstage/plugin-azure-devops                     0.3.2
  @backstage/plugin-catalog-backend-module-github    0.3.2
  @backstage/plugin-catalog-backend-module-openapi   0.1.13
  @backstage/plugin-catalog-backend                  1.11.0
  @backstage/plugin-catalog-common                   1.0.15
  @backstage/plugin-catalog-graph                    0.2.32
  @backstage/plugin-catalog-import                   0.9.10
  @backstage/plugin-catalog-node                     1.4.0
  @backstage/plugin-catalog-react                    1.8.0
  @backstage/plugin-catalog                          1.12.0
  @backstage/plugin-dynatrace                        7.0.0
  @backstage/plugin-events-node                      0.2.8
  @backstage/plugin-github-actions                   0.6.1
  @backstage/plugin-github-issues                    0.2.9
  @backstage/plugin-home-react                       0.1.1
  @backstage/plugin-home                             0.5.4
  @backstage/plugin-jenkins-backend                  0.2.2
  @backstage/plugin-jenkins-common                   0.1.17
  @backstage/plugin-jenkins                          0.8.2
  @backstage/plugin-kubernetes-backend               0.11.2
  @backstage/plugin-kubernetes-common                0.6.5
  @backstage/plugin-kubernetes                       0.9.3
  @backstage/plugin-lighthouse-common                0.1.2
  @backstage/plugin-lighthouse                       0.4.5
  @backstage/plugin-org                              0.6.10
  @backstage/plugin-pagerduty                        0.6.1
  @backstage/plugin-permission-common                0.7.7
  @backstage/plugin-permission-node                  0.7.10
  @backstage/plugin-permission-react                 0.4.14
  @backstage/plugin-proxy-backend                    0.2.41
  @backstage/plugin-scaffolder-backend-module-gitlab 0.2.2
  @backstage/plugin-scaffolder-backend               1.15.1
  @backstage/plugin-scaffolder-common                1.3.2
  @backstage/plugin-scaffolder-node                  0.1.5
  @backstage/plugin-scaffolder-react                 1.5.1
  @backstage/plugin-scaffolder                       1.14.1
  @backstage/plugin-search-backend-module-catalog    0.1.3
  @backstage/plugin-search-backend-module-pg         0.5.8
  @backstage/plugin-search-backend-module-techdocs   0.1.3
  @backstage/plugin-search-backend-node              1.2.3
  @backstage/plugin-search-backend                   1.3.3
  @backstage/plugin-search-common                    1.2.5
  @backstage/plugin-search-react                     1.6.3
  @backstage/plugin-search                           1.3.3
  @backstage/plugin-sonarqube-backend                0.2.1
  @backstage/plugin-sonarqube-react                  0.1.7
  @backstage/plugin-sonarqube                        0.7.1
  @backstage/plugin-tech-radar                       0.6.6
  @backstage/plugin-techdocs-backend                 1.6.4
  @backstage/plugin-techdocs-module-addons-contrib   1.0.15
  @backstage/plugin-techdocs-node                    1.7.3
  @backstage/plugin-techdocs-react                   1.1.8
  @backstage/plugin-techdocs                         1.6.5
  @backstage/plugin-user-settings                    0.7.5
  @backstage/release-manifests                       0.0.9
  @backstage/test-utils                              1.4.1
  @backstage/theme                                   0.2.19, 0.3.0, 0.4.1
  @backstage/types                                   1.1.0
  @backstage/version-bridge                          1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Ah, looks like the filtering is done on the frontend only, as opposed to in a query to the backend. Would be awesome to have that fixed! 😁

**Comment by Zaperex** [comment]
I'll take a look at this and try to get a PR submitted soon

**Comment by Zaperex** [comment]
So based on my investigation, it appears that the way the plugin currently works is that it only requests a page size (default = 5) of actions per page when the user navigates to the page. That means we can essentially imagine each page having it's own separate array holding it's 5 (or whatever the page size is) actions. If this line of thinking is correct, then the filtering is actually just filtering the actions in each page separately. That is mostly likely the reason why each items from next page don't get moved to the 1st page.

The [github pull requests plugin](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/backstage-plugin-github-pull-requests) I mentioned above uses their own filter searchbar, but also requests a page size worth of PRs per page at a time. However, what's different is that you can actually search for issues and PRs using the github API, so that is a non-issue for them.

I also found that there's currently no way to filter for actions by title or commits. Instead the [documentation](https://octokit.github.io/rest.js/v20#actions-list-workflow-runs) states that we can only filter by:
- `actor` aka the individual who triggered the workflow
- `branch` aka the branch that the workflow was triggered for
- `event` aka what type of event triggered the workflow?
- `status` aka the status of the workflow
- `workflow` what workflow was triggered

![image](https://github.com/backstage/backstage/assets/50030060/55da4c74-e411-4de3-acda-7c489e71b903)
Anything else appears to just be ignored
![image](https://github.com/backstage/backstage/assets/50030060/d4f8de31-16bf-4bbb-9703-b60365c38bef)

I'm thinking to either: 
- Completely remove the filter/searchbar
- Follow the footsteps of the [github pull requests plugin](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/backstage-plugin-github-pull-requests) and replace the filter with our own to be able to filter by `actor`, `branch`, `event`, `status` and `workflow` directly through the API
- Try to overhaul the way the API calls are made
  - Potentially try to call them all at once when the page loads like the [quay plugin](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/quay)? 
  - Will need to see what downsides this would pose (especially when the number of actions being queried is large)

**Comment by Rugvip** [comment]
Ah alright. We'd really like to avoid querying for a large number of actions and filtering client-side. That's gonna cause issues 😅 

Tbh I think at this point the best fix for this might be to disable the filters for any columns where the GitHub API doesn't support filtering, since it's not particularly useful. Or alternatively leave it as is.

**Comment by Zaperex** [comment]
For the querying a large number of actions, I was thinking we could just query up to the latest 1000 (or even just 100) actions (with each API call querying 100 actions).

However for the filter disabling, can I ask what you mean by "disabling filters for any columns where the Github API doesn't support filtering"? Currently, the filter searchbar looks for the matching filter through the entirety of the `data[]` array provided to the Table. I could turn off the default search bar and implement a custom searchbar that will only accept the github API ones or something.

**Comment by Rugvip** [comment]
@Zaperex ah wasn't aware it was a global search, was thinking it was a search per column. Yep whatever makes sense, main thing is to remove the bad search experience 😅 

My main worry with search X number of items is that what if there's a match at X+1? The user would've expected to find that. If we instead continue search we risk fetching X*Y items, which can be a lot. In the end you really need support from the backend API if you want to filter large datasets. Frontend filtering really only makes sense for datasets that you know will be very small.

**Comment by Zaperex** [comment]
I'll see if I can create the custom searchbar to only query for what is supported by the API
