### ISSUE TITLE
🚀 Feature: Download contents of Scaffolder dry-run as .zip File / Blob ( PR open )

### ISSUE THREAD

**Issue by fyyyyy** [backstage/backstage#19318]
### 🔖 Feature description

The dry-run results should be downloadable as a zip file.

### 🎤 Context

For larger template projects using skeleton repos, it would be necessary to download the generated dry-run files as a .zip file.
This is necessary for larger projects to
* Run the generated repository and check if everything works as expected
* Do some automatic tests on the generated repository.

Copy / pasting the contents of each file from html is not convenient.

### ✌️ Possible Implementation

To test it, the directoryContents Array can be copy/pasted from react dev tools. I haven't found a way to extract it from the DOM without using react dev tools. 

If its merged into the[ scaffolder plugin](https://github.com/backstage/backstage/pull/11173/files#diff-0f3ac61a12b2443bfec912c2932eb97037dda42dab7a48c4300fa5c4435822acR393), it would have access to directoryContents from React Context.

```js
// needs zip.js
// https://raw.githubusercontent.com/gildas-lormeau/zip.js/master/dist/zip-full.min.js

// Creates a BlobWriter object where the zip content will be written.
const zipFileWriter = new zip.BlobWriter();

// Creates a ZipWriter object writing data via `zipFileWriter`, adds the entry
const zipWriter = new zip.ZipWriter(zipFileWriter);

for (const d of directoryContents) {
  // Convert text from base64 to ascii
  const converted = atob(d.base64Content);
  
  // Creates a TextReader object storing the text of the entry to add in the zip
  // (i.e. "Hello world!").
  const fileReader = new zip.TextReader(converted);

  await zipWriter.add(d.path, fileReader);
}

// Closes the writer.
await zipWriter.close();

// Retrieves the Blob object containing the zip content into `zipFileBlob`. It
// is also returned by zipWriter.close() for more convenience.
const zipFileBlob = await zipFileWriter.getData();

// download zip
a = document.createElement('a');
a.href = URL.createObjectURL(zipFileBlob);
a.download = `dry-run.zip`;
a.click();
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes, see https://github.com/backstage/backstage/pull/19388
```[tasklist]
### Tasks
- [x] PR
```

**Comment by Rugvip** [comment]
I think this would be a good addition! The `DryRunResults` is where this would be added, starting somewhere here: https://github.com/backstage/backstage/blob/2b0ba754da6e6cb2b7a484d917562ffa1d1186b3/plugins/scaffolder/src/components/TemplateEditorPage/DryRunResults/DryRunResults.tsx#L50

**Comment by fyyyyy** [comment]
I would like to create a PR, but i cant get my local backstage to run the cloned scaffolder plugin. 
So i cant see the code changes im doing reflected in my local backstage instance.
I tried this:

  "workspaces": {
    "packages": [
      "packages/*",
      "plugins/*",
      "../backstage/plugins/scaffolder"
    ]

**Comment by fyyyyy** [comment]
Relates to #15078

**Comment by camilaibs** [comment]
Closed by https://github.com/backstage/backstage/pull/19388
