### ISSUE TITLE
🚀 Feature/Bugish: Add title to props for Has<kind>Cards over hard-coded values of "Has <kind>".

### ISSUE THREAD

**Issue by CiscoRob** [backstage/backstage#19323]
### 🔖 Feature description

Requesting support to customize the titles of Card components displayed on the catalog entity pages. The ability to rename a card title is inconsistent across the components and across libraries. 

When viewing a catalog entity page it's easy to see that there is a naming inconsistency in card titles, and the inability to remove "Has" from a card makes duplication much much more likely to fix inconsistencies. 

![image](https://github.com/backstage/backstage/assets/133238823/aab675be-be8d-4fe3-af0e-69d463078cd2)

It's worth noting that all the DependsOn*Card components _do_ have customizable titles:

![image](https://github.com/backstage/backstage/assets/133238823/a554959a-f3fe-44e6-adbc-95f8ff3724f6)

## EntityHasAPIsCard naming convention differs from Has*Card

When viewing a catalog page that contains the Has*Card components it's worth noting that _one_ of these *has* components does _not_ abide by this naming convention. 

> NOTE: The `EntityHasApisCard` is imported from another Backstage library `@backstage/plugin-api-docs` where it has a fixed title, except unlike the `@backstage/plugin-catalog` Has*Card components it is "APIs".
>  

When viewed together it's easy for someone to go... well change the titles to be consistent, which they are not, and they're not customizable.

![image](https://github.com/backstage/backstage/assets/133238823/c144df97-99da-4d66-a2ae-8253f18dfe81)

## Has Card Source Locations

HasComponentsCard
https://github.com/backstage/backstage/blob/5501bca80a68b48a4da57b736b47ebb3a65d19f9/plugins/catalog/src/components/HasComponentsCard/HasComponentsCard.tsx#L37

HasResourcesCard
https://github.com/backstage/backstage/blob/5501bca80a68b48a4da57b736b47ebb3a65d19f9/plugins/catalog/src/components/HasResourcesCard/HasResourcesCard.tsx#L37

HasSubComponentsCard
https://github.com/backstage/backstage/blob/5501bca80a68b48a4da57b736b47ebb3a65d19f9/plugins/catalog/src/components/HasSubcomponentsCard/HasSubcomponentsCard.tsx#L37

HasSystemsCard
https://github.com/backstage/backstage/blob/5501bca80a68b48a4da57b736b47ebb3a65d19f9/plugins/catalog/src/components/HasSystemsCard/HasSystemsCard.tsx#L37

### 🎤 Context

In order to reduce code duplication, fix inconsistencies in Backstage's own naming conventions, and to satisfy product managers who request renamed card titles.

This feature improvement is a must.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Closed by https://github.com/backstage/backstage/pull/19382.
