### ISSUE TITLE
🔌 Plugin: Rehome pagerduty

### ISSUE THREAD

**Issue by sparklingrobots** [backstage/backstage#19347]
### 🔖 Summary

I propose that PagerDuty officially maintain the [PagerDuty plugin for Backstage](https://github.com/backstage/backstage/tree/master/plugins/pagerduty).  

We would like to provide support for the plugin as well as expand the feature set in collaboration with the Backstage community. Initially, our plan is to address existing issues, but we have ideas for future features and are excited to hear what would most help the community.

I don't yet have details about where the plugin will move or the new package name, but I wanted to open the issue to let the community know about our intention and give time for discussion and questions. @t1agob will be leading this effort on the PagerDuty side, with some support from me. 

### 🌐 Project website (if applicable)

https://www.pagerduty.com

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Awesome, love it! 😁 🎉 Happy to help out and along the way!

A quick bit on the process: Our preference for handing over ownership of plugins/systems like this one is to have the new owner copy the package(s) to a new repository and continue development there. Of course keeping in mind our Apache 2.0 license on the existing code. The packages won't be able to keep using the `@backstage/` scope on NPM, so our existing packages will be deprecated point to the new packages in the README once they are available. This process is something we of course want clearly laid out in documentation, please bear with us until we get there 😅, ideally this is the starting point of that.

I'd also love to hear from the community if there are any concerns with re-homing plugins. The specific case we're looking at is where a service provider wants to take on ownership of a plugin that integrates with their service, but was originally built by members of the community.

**Comment by t1agob** [comment]
Thanks for the quick tips @Rugvip. I'll be in charge of the process from PagerDuty's side and this is really helpful. Happy to help on documenting the process and contribute it back to the docs.

My main priority here is to make this transition as smooth as possible for developers using this plugin. The last thing I want is that the re-homing of the plugin breaks something in their Backstage deployments.

**Comment by t1agob** [comment]
Hi!
Just wanted to let you know that this plugin is now hosted at https://github.com/PagerDuty/backstage-plugin and therefore this task as been completed I believe.

@Rugvip I have outline in the readme file the steps to migrate from the plugin hosted in the Backstage account to the one hosted in PagerDuty's account. **Are there any additional steps that I need to perform at this point?** Like removing the PagerDuty plugin from the plugins folder. Or should we leave it for a bit longer?

**Comment by benjdlambert** [comment]
Hey @t1agob!

This is awesome to see :tada:

I think that we should follow a similar process to what we did with the `@backstage/plugin-graphql` plugin.

We first mark the package as deprecated and create a release to point to the new one, and then after that mainline release we can delete the code from the repo. Next mainline release is 19th of December.

Deprecation PR might look similar to [this](https://github.com/backstage/backstage/pull/20523).

Do you feel like you can raise a PR with the deprecations? :pray:

**Comment by t1agob** [comment]
Sure @benjdlambert! 

I'll do that and submit a PR. Thanks for sharing the example for graphql.

**Comment by tudi2d** [comment]
Closing this as done. Thanks @t1agob for your work!
