### ISSUE TITLE
🐛 Bug Report: Backstage does not have a way to configuration token expiry duration

### ISSUE THREAD

**Issue by bbasu** [backstage/backstage#19341]
### 📜 Description

Backstage does not have a way to configuration token expiry duration

### 👍 Expected behavior

Backstage should have a way to configure the token expiry duration.

### 👎 Actual Behavior with Screenshots

Backstage does not have a way configure the token expiry duration. Currently its hardcoded to 3600 seconds

![image](https://github.com/backstage/backstage/assets/14269816/23ba4eed-0bbc-40ab-85c2-e43a9ddd3492)

![image](https://github.com/backstage/backstage/assets/14269816/f0dacd79-93b5-40b9-bcb5-22738b77d534)

Files referred:

plugins\auth-backend\src\service\router.ts
plugins\auth-backend\src\lib\session\constants.ts

### 👟 Reproduction steps

Start a backstage application. 

Check the exp of the token issued.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by bbasu** [comment]
Currently we had to to verride the whole of the backend auth router and related dependencies which are not exposed in the backstage/plugin-auth-backend in our application code to change the one liner to read from the configuration to achieve this customisation. 

Is there any better way to do this at the moment? From what I can see its just defining this value in the app-config and referring that from the code.

**Comment by Rugvip** [comment]
The TODO comment pretty much sums it up 😁 

Out of interest though, how come you want to configure the token expiration?

**Comment by bbasu** [comment]
Hi,

We use backstage for a customer facing application. We were trying to reduce the token expiration from the default to around 10mins for that instance. 

Any timeline on when this can be taken up by the team? Also, If we open a PR on this, will this be included in the next release?

**Comment by benjdlambert** [comment]
@bbasu I think it probably makes sense to configure this, but maybe say that the roof is 1hr, so you can't configure token expiry for like 2 years or whatever which promotes bad practices. Contributions for this are welcome, and maybe we can carry on the discussion in the PR? When the PR is merged it will be included in one of the `-next` releases that happen weekly, and then the `mainline` releases which happen once a month.

**Comment by Rugvip** [comment]
This will be a lot simpler once #19462 lands, as we won't need other workarounds to make sure sessions are refreshed when needed.
