### ISSUE TITLE
🐛 Bug Report: non RFC compliant URI for retrieving members and relations

### ISSUE THREAD

**Issue by ypetrych** [backstage/backstage#19357]
### 📜 Description

Issue appears because of partially encoded query parameter, which creates non RFC compliant URI. It violates - https://datatracker.ietf.org/doc/html/rfc3986#section-2.2

 In case of using Spring Gateway Service between Backstage FE and Backstage BE the query params get double encoded by this filter - https://www.javadoc.io/static/org.springframework.cloud/spring-cloud-gateway-core/2.2.0.RELEASE/org/springframework/cloud/gateway/filter/RouteToRequestUrlFilter.html#filter-org.springframework.web.server.ServerWebExchange-org.springframework.cloud.gateway.filter.GatewayFilterChain-

Best course of action would be to avoid special characters altogether(even encoded ones). You can`t be sure that processing of such request will be same on different technology stacks.

These kind of requests return empty array for results.

### 👍 Expected behavior

For getting the members for specific group the correct query parameter should look like this: `filter=kind%3DUser%2Crelations.memberof-group%3Adefault%2Fteamname`

### 👎 Actual Behavior with Screenshots

Instead of partially encoded `filter=kind=User,relations.memberof-group%3Adefault%2Fteamname`

### 👟 Reproduction steps

1. Setup infrastructure like this: Backstage FE -> Spring Gateway Service -> additional infrastructure parts -> Backstage BE
2. Make call for members
3. Make sure that the call will return empty array

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hmm ok, I think we probably want to dig into `CatalogClient` and ensure that we `encodeURIComponent` on all the different filters when it's being constructed. We'd also want to ensure that this doesn't break anything in the parsing from the `catalog-backend` plugin too and make sure that it's updated to support both if something is awry.

Just a small note also it look like `filter=kind%3DUser%2Crelations.memberof-group%3Adefault%2Fteamname` is also wrong. Think it should be `memberOf=` not `memberOf-`? Not sure if that's just a mistype or smth tho 😅

**Comment by ypetrych** [comment]
> Hmm ok, I think we probably want to dig into `CatalogClient` and ensure that we `encodeURIComponent` on all the different filters when it's being constructed. We'd also want to ensure that this doesn't break anything in the parsing from the `catalog-backend` plugin too and make sure that it's updated to support both if something is awry.
> 
> Just a small note also it look like `filter=kind%3DUser%2Crelations.memberof-group%3Adefault%2Fteamname` is also wrong. Think it should be `memberOf=` not `memberOf-`? Not sure if that's just a mistype or smth tho 😅

Thank you @benjdlambert! It was a mistype when I typed the query, thank you for the noticing it!

**Comment by benjdlambert** [comment]
@backstage/catalog-maintainers here too

**Comment by sennyeya** [comment]
Definitely agree, also makes my OpenAPI work a little simpler :). 

Can you explain a little more about the output URL that Spring is creating? Is it due just to the unencoded characters in the URL? 

Here's the method that handles that logic to encode the characters. You probably just have to switch the inline characters (`=`, `,`) with the correctly encoded characters or run a `encodeUriComponent` on the end product.
https://github.com/backstage/backstage/blob/c48221c36a2e08d3640c2b802cdff6ecefa56cc7/packages/catalog-client/src/CatalogClient.ts#L526-L551

And any changes would have to be validated against this. If I had to guess that's where the properly encoded characters are creating incorrect filters. https://github.com/backstage/backstage/blob/c48221c36a2e08d3640c2b802cdff6ecefa56cc7/plugins/catalog-backend/src/service/request/parseEntityFilterParams.ts#L48-L54

**Comment by benjdlambert** [comment]
Curious if this is now fixed with the recent changes or if there's some other things to do @ypetrych? :pray:

**Comment by sennyeya** [comment]
@benjdlambert I don't think this has been fixed yet, 1.17 patches were related to validation layer, this is for CatalogClient encoding fixes. I can take a look at this, but it might take me a while to get to it.

**Comment by fru2zzy** [comment]
waiting for it 🙏

**Comment by sennyeya** [comment]
@fru2zzy @ypetrych  Can you take a look at this in the latest release? This should have gone out as part of #17470 which was released as part of 1.21 and added much better URI encoding enforcement.
