### ISSUE TITLE
🐛 Bug Report: Techdocs does not escape mkdocs fields which may result in invalid JSON metadata

### ISSUE THREAD

**Issue by marcus-crane** [backstage/backstage#19369]
### 📜 Description

When onboarding with techdocs, one of our users created an `mkdocs.yml` file that included the following line:

```yaml
site_description: 'Documentation for the X-Series PHP Monolith ("Monoliph")'
```

Upon visiting their newly ingested techdocs and triggering the build process, they were surprised to find that their content hadn't rendered.

The underlying issue was that the double quotes present in `site_description` were exported into `techdocs_metadata.json` unescaped, causing the build process to fail when it tried to parse the metadata file which was now invalid JSON.

### 👍 Expected behavior

YAML inputs should be escaped rather than passed straight into `techdocs_metadata.json`

### 👎 Actual Behavior with Screenshots

Upon the build process kicking off, an invalid `techdocs_metadata.json` was generated due to the double quotes present in `site_description` breaking out of the JSON structure

![CleanShot 2023-08-15 at 15 50 40](https://github.com/backstage/backstage/assets/14816406/d966c614-6057-416e-af51-e618d277ad10)

Here is what the user saw on their end:

![CleanShot 2023-08-15 at 15 44 05](https://github.com/backstage/backstage/assets/14816406/fe507ae9-dd13-42d9-ade7-b585ae7d8f5c)

Here's the relevant excerpt from the build logs:

```console
info: Successfully generated docs from /tmp/backstage-acuTNp into /tmp/techdocs-tmp-aBWPrr using local mkdocs {"timestamp":"2023-08-15T03:22:29.784Z"}
error: Invalid JSON at /tmp/techdocs-tmp-aBWPrr/techdocs_metadata.json with error /tmp/techdocs-tmp-aBWPrr/techdocs_metadata.json: Unexpected token M in JSON at position 98 {"timestamp":"2023-08-15T03:22:29.785Z"
error: Failed to build the docs page: Invalid JSON at /tmp/techdocs-tmp-aBWPrr/techdocs_metadata.json with error /tmp/techdocs-tmp-aBWPrr/techdocs_metadata.json: Unexpected token M in JSON at position 98 {"timestamp":"2023-08-15T03:22:29.785Z"}
```

### 👟 Reproduction steps

1. Create a `mkdocs.yml` that includes a field containing double quotes, presumably captured within single quotes
2. Ingest some techdocs into Backstage
3. Check the techdocs builder and see a failure when the latest docs are attempted to be built

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Hmm, wondering if this is something on the `techdocs` side, as it looks like the YAML that you pasted in the first snippet is valid right - so probably not something that the scaffolder is doing, otherwise you'd just need to escape the values that are templated into there.

**Comment by marcus-crane** [comment]
> wondering if this is something on the `techdocs` side

Ah sorry, I completely overlooked that I wrote Scaffolder in the title which caused the label to be wrong too 🤦

Probably I was looking at the build output from techdocs which reminds me of the scaffolder and my brain farted while writing up this issue hah

To clarify, this bug is only about techdocs and specifically the `techdocs_metadata.json` file that gets created when rendering out documentation.

**Comment by benjdlambert** [comment]
No worries! I added the label! Something for @backstage/techdocs-maintainers!

**Comment by fedy97** [comment]
Hi @marcus-crane I am not able to reproduce this, in fact I successfully edited the `site_description`
<img width="474" alt="Screenshot 2023-08-18 at 14 46 14" src="https://github.com/backstage/backstage/assets/47827254/fb2b4a16-9ea0-4caf-9d7a-d5109ca3d9c9">

this is the `techdocs_metadata.json` generated
`"site_description":"Documentation for the X-Series PHP Monolith (\"Monoliph\")"`
