### ISSUE TITLE
💬 RFC: Building forms with YAML

### ISSUE THREAD

**Issue by taras** [backstage/backstage#19385]
### 🔖 Need

We need a way to make it easier to build forms. Scaffolder has an excellent way to build forms using RJSF. It would be great to create a form using YAML or JSON. Ideally, this could be done from TypeScript or YAML without creating an entity. 

### 🎉 Proposal

Introduce a new plugin for presenting forms. It would be great if we could custom field extensions from Scaffolder with this new plugin. We could refactor Scaffolder to use this custom form mechanism in the future. 

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by codesandtags** [comment]
Please could you provide some examples about the use cases for this plugin or the process that it could follow?

**Comment by taras** [comment]
This suggestion was in part motivated by this [thread in Discord](https://discord.com/channels/687207715902193673/1138432889831313510), but we also have a situation on a project where we need to provide a sample plugin for new teams being onboarded to a Backstage project. We provide a structure of a plugin, but we also want to allow them to create forms quickly. Scaffolder makes it super easy to create forms with YAML; we'd like the same outside of Scaffolder. They might use these to capture information and send it to a backend service through a proxy.

**Comment by koozz** [comment]
One alternative might be to parse the GitHub Actions [`workflow_dispatch`-inputs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs).

**Pro**: The form in Backstage would then be 'dynamic', no need to make adjustments in Backstage, just point it to a workflow_dispatch URL.

**Con**: Integration limited to GitHub.

**Ideas**

* On submitting, it can trigger that workflow, either fire-and-forget or some state with polling or callback URL.
* Some fields could be prefilled (input type=hidden) by convention, like Backstage username or email, this convention can be configured on the Backstage side to prevent data exfiltration. Useful fields would be username, email and a callback_url where a workflow can post a predefined result response.
* Could be combined with the initial proposal, where a `location` of the form with the value `remote` or `github` could read this workflow_dispatch variant.

**Comment by taras** [comment]
> One alternative might be to parse the GitHub Actions [`workflow_dispatch`-inputs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs).

We could create a translation that would generate forms YAML from GitHub Actions. The combination would probably be best as a separate plugin.

**Comment by benjdlambert** [comment]
Is it not possible just to use the `Form` component from `plugin-scaffolder-react`? Or maybe at least building on top of that? Maybe creating another component which can do the splitting of the input data to create the `ui:schema` and the `schema` like we also do in the scaffolder?

**Comment by TheDukeDK** [comment]
So, we have our own little in-house built self services portal done with python flask. We want to replace this and are looking at multiple options. One of them was, of course, backstage, which we have zero experience with. Another is Port. My colleague is looking at port and was blown away by how easy it was to build forms which could call our own API's.

It would be a really good if backstage could do the same.

So a big +1 for this functionality.

**Comment by efenner-cambia** [comment]
+1
