### ISSUE TITLE
🐛 Bug Report: PR 18919 prevents Warning: Entity Not Found from Appearing

### ISSUE THREAD

**Issue by Joshua-Liong-vw** [backstage/backstage#19418]
### 📜 Description

In https://github.com/backstage/backstage/pull/18919, there was an implementation change where "If the entity is missing or there is an error, render nothing." The prior behavior, "If the entity is missing or there is an error, render the default page", was removed. The user is then served a blank page, instead of a a useful error experience.

### 👍 Expected behavior

Show a warning page "Warning: Entity not found" when loading an entity that does not exist.

![image](https://github.com/backstage/backstage/assets/67614786/7160ab0c-1024-42c9-9e30-57864c342bf6)

### 👎 Actual Behavior with Screenshots

The page is completely blank.

![image](https://github.com/backstage/backstage/assets/67614786/3d31f550-d6b5-48d4-a342-362a33bfed02)

### 👟 Reproduction steps

It is reproducible in the demo site. For example:
https://demo.backstage.io/catalog/default/user/idonotexist

### 📃 Provide the context for the Bug.

This PR seems directly related to the issue. https://github.com/backstage/backstage/pull/18919

### 🖥️ Your Environment

Reproducible in the demo backstage environment.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
@vinzscam do you want to see if there's something that we can do to fix this, otherwise I think we might have to revert this change.

**Comment by benjdlambert** [comment]
@Joshua-Liong-vw ok, we're going to ship v1.17.1 with this change reverted I think, and then have a followup PR for the `-next` release which fixes this in a different way and moves some of that handling logic elsewhere.
