### ISSUE TITLE
🐛 Bug Report: Double Scroll Bar and NO Search Text Bar in Catalog Docs Tab

### ISSUE THREAD

**Issue by iriswang233** [backstage/backstage#19427]
### 📜 Description

In docs tab /catalog/:namespace/:kind/:name/docs, there is double scroll bar and no search text bar comparing to docs page /catalog/:namespace/:kind/:name.

<img width="1029" alt="image" src="https://github.com/backstage/backstage/assets/49713904/2bd55670-b072-445f-8d01-45480343784d">

This is caused by EntityTechdocsContent is using EmbeddedDocsRouter, which is using element: <EntityPageDocs entity={entity} />. However, EntityPageDocs is using TechDocsReaderPage which contains a <Page> causing scroll bar and  <TechDocsReaderPageContent withSearch={false} /> which disables search text bar.

Is there a way to fix this EntityPageDocs through passing input to TechDocsReaderPage to remove the <Page>  and enabling withSearch in TechDocsReaderPageContent of EntityPageDocs?

Please see more source code below
```
/**
 * Routable extension used to render docs on Entity page
 *
 * @public
 */
export const EntityTechdocsContent = techdocsPlugin.provide(
  createRoutableExtension({
    name: 'EntityTechdocsContent',
    component: () => import('./Router').then(m => m.EmbeddedDocsRouter),
    mountPoint: rootCatalogDocsRouteRef,
  }),
);

/**
 * Responsible for registering route to view docs on Entity page
 *
 * @public
 */
export const EmbeddedDocsRouter = (props: PropsWithChildren<{}>) => {
  const { children } = props;
  const { entity } = useEntity();

  // Using objects instead of <Route> elements, otherwise "outlet" will be null on sub-pages and add-ons won't render
  const element = useRoutes([
    {
      path: '/*',
      element: <EntityPageDocs entity={entity} />,
      children: [
        {
          path: '*',
          element: children,
        },
      ],
    },
  ]);

  const projectId = entity.metadata.annotations?.[TECHDOCS_ANNOTATION];

  if (!projectId) {
    return <MissingAnnotationEmptyState annotation={TECHDOCS_ANNOTATION} />;
  }

  return element;
};

export const EntityPageDocs = ({ entity }: EntityPageDocsProps) => {
  const entityRef = getCompoundEntityRef(entity);

  return (
    <TechDocsReaderPage entityRef={entityRef}>
      <TechDocsReaderPageSubheader />
      <TechDocsReaderPageContent withSearch={false} />
    </TechDocsReaderPage>
  );
};
```

### 👍 Expected behavior

Docs tab /catalog/:namespace/:kind/:name/docs is same with docs page /catalog/:namespace/:kind/:name, which doesn't have double scroll bar and have search text bar.

### 👎 Actual Behavior with Screenshots

In docs tab /catalog/:namespace/:kind/:name/docs, there is double scroll bar and no search text bar comparing to docs page /catalog/:namespace/:kind/:name.

<img width="1029" alt="image" src="https://github.com/backstage/backstage/assets/49713904/2bd55670-b072-445f-8d01-45480343784d">

### 👟 Reproduction steps

Open a long techdoc in docs tab /catalog/:namespace/:kind/:name/docs 

### 📃 Provide the context for the Bug.

This is caused by EntityTechdocsContent is using EmbeddedDocsRouter, which is using element: <EntityPageDocs entity={entity} />. However, EntityPageDocs is using TechDocsReaderPage which contains a <Page> causing scroll bar and  <TechDocsReaderPageContent withSearch={false} /> which disables search text bar.

### 🖥️ Your Environment

OS:   Darwin 22.6.0 - darwin/x64
node: v16.14.2
yarn: 1.22.19
cli:  0.20.0 (installed)
backstage:  1.7.2

Dependencies:
  @backstage/app-defaults                          1.4.0
  @backstage/backend-app-api                       0.4.4
  @backstage/backend-common                        0.15.2, 0.16.0, 0.18.5, 0.19.0
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.3
  @backstage/backend-tasks                         0.5.3
  @backstage/catalog-client                        1.4.2
  @backstage/catalog-model                         1.4.0
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.18.1, 0.20.0
  @backstage/config-loader                         1.3.1
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.8.1
  @backstage/core-components                       0.11.2, 0.12.5, 0.13.2
  @backstage/core-plugin-api                       1.5.2
  @backstage/errors                                1.2.0
  @backstage/integration-aws-node                  0.1.4
  @backstage/integration-react                     1.1.14
  @backstage/integration                           1.5.0
  @backstage/plugin-api-docs                       0.8.14
  @backstage/plugin-app-backend                    0.3.46
  @backstage/plugin-auth-backend                   0.17.4
  @backstage/plugin-auth-node                      0.2.15
  @backstage/plugin-catalog-backend-module-gitlab  0.1.14
  @backstage/plugin-catalog-backend-module-ldap    0.5.13
  @backstage/plugin-catalog-backend                1.10.0
  @backstage/plugin-catalog-common                 1.0.14
  @backstage/plugin-catalog-graph                  0.2.31
  @backstage/plugin-catalog-import                 0.9.9
  @backstage/plugin-catalog-node                   1.3.7
  @backstage/plugin-catalog-react                  1.7.0
  @backstage/plugin-catalog                        1.11.2
  @backstage/plugin-events-node                    0.2.7
  @backstage/plugin-explore-common                 0.0.1
  @backstage/plugin-explore-react                  0.0.25
  @backstage/plugin-explore                        0.3.45
  @backstage/plugin-home                           0.4.32
  @backstage/plugin-kubernetes-backend             0.7.3
  @backstage/plugin-kubernetes-common              0.4.4, 0.6.4
  @backstage/plugin-kubernetes                     0.7.9
  @backstage/plugin-org                            0.5.10
  @backstage/plugin-pagerduty                      0.5.11
  @backstage/plugin-permission-backend             0.5.21
  @backstage/plugin-permission-common              0.7.6
  @backstage/plugin-permission-node                0.7.9
  @backstage/plugin-permission-react               0.4.13
  @backstage/plugin-proxy-backend                  0.2.40
  @backstage/plugin-scaffolder-backend             1.15.0
  @backstage/plugin-scaffolder-common              1.3.1
  @backstage/plugin-scaffolder-node                0.1.4
  @backstage/plugin-scaffolder-react               1.5.0
  @backstage/plugin-scaffolder                     1.14.0
  @backstage/plugin-search-backend-module-catalog  0.1.2
  @backstage/plugin-search-backend-module-pg       0.4.2
  @backstage/plugin-search-backend-module-techdocs 0.1.2
  @backstage/plugin-search-backend-node            1.2.2
  @backstage/plugin-search-backend                 1.3.2
  @backstage/plugin-search-common                  1.2.4
  @backstage/plugin-search-react                   1.6.2
  @backstage/plugin-search                         1.3.2
  @backstage/plugin-shortcuts                      0.3.11
  @backstage/plugin-tech-radar                     0.5.20
  @backstage/plugin-techdocs-backend               1.6.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5
  @backstage/plugin-techdocs-node                  1.3.0, 1.7.2
  @backstage/plugin-techdocs-react                 1.0.5
  @backstage/plugin-techdocs                       1.3.3
  @backstage/plugin-user-settings                  0.5.1
  @backstage/release-manifests                     0.0.5, 0.0.6
  @backstage/test-utils                            1.4.0
  @backstage/theme                                 0.2.19, 0.3.0, 0.4.0
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
✨  Done in 3.04s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GLundh** [comment]
Some more info here in regards to the the scrollbars:
https://github.com/backstage/backstage/issues/13717
Also a PR here that was not merged: https://github.com/backstage/backstage/pull/14138

It is a huge issue that essentially breaks TechDocs. Not sure why it is not taken seriously.
