### ISSUE TITLE
🐛 Bug Report: Catalog-import doesn't search base GitHub repo url for catalog-info.yaml

### ISSUE THREAD

**Issue by devonpaluso** [backstage/backstage#19426]
### 📜 Description

Attempting catalog-import with a base GitHub repo url does not find the existing catalog-info.yaml.

Using the example REPO url provided will not work: https://github.com/backstage/backstage

Using the example BLOB url will work: https://github.com/backstage/backstage/blob/master/catalog-info.yaml

Exactly the same behavior on the Janus backstage showcase for reference: https://showcase.janus-idp.io/catalog-import

### 👍 Expected behavior

Behavior as described: 
<img width="706" alt="image" src="https://github.com/backstage/backstage/assets/55293990/7c0aca67-e07c-450b-8696-884d36a0c77e">

### 👎 Actual Behavior with Screenshots

<img width="512" alt="image" src="https://github.com/backstage/backstage/assets/55293990/bf72de8e-fcc9-43fd-b4ee-c26f5057b330">
<img width="403" alt="image" src="https://github.com/backstage/backstage/assets/55293990/4e904c0d-03dd-4194-baf1-b116f7d1aa03">
<img width="721" alt="image" src="https://github.com/backstage/backstage/assets/55293990/92016689-3390-406f-a8ee-d5693e54b702">

This DOES work with the direct link.

<img width="671" alt="image" src="https://github.com/backstage/backstage/assets/55293990/2833de64-ba15-4db0-a5aa-ec7920957ae5">
<img width="707" alt="image" src="https://github.com/backstage/backstage/assets/55293990/2e984546-26cc-45c9-ae12-0a234deb6e9c">
<img width="724" alt="image" src="https://github.com/backstage/backstage/assets/55293990/a5db5e5c-2248-41bc-9e39-791c6e1c70e3">

### 👟 Reproduction steps

1. Go to {backstage_instance}/catalog-import
2. Import example GitHub repo url: https://github.com/backstage/backstage

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Yeah unfortunately this isn't built to scan the top level repo to see what files might be there.

I know that @timbonicus did some hack work on trying to improve this workflow to make it easier to import things, but I think that work kind of stalled and we never picked it back up again.

Also going to ping @backstage/catalog-maintainers here too to see if this is something that we would look at improving!
