### ISSUE TITLE
🚀 Feature: Allow to choose multiple options for EntityTypePicker filter

### ISSUE THREAD

**Issue by roman-shandurenko** [backstage/backstage#19425]
### 🔖 Feature description

Provide an input argument to allow selecting multiple values from `Type` [filter picker](https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/components/EntityTypePicker/EntityTypePicker.tsx).

### 🎤 Context

Describing our use-case. There are multiple **types** of _Components_ we use in Backstage.
And engineering managers would like to filter the catalog by multiple types.

### ✌️ Possible Implementation

I want to choose multiple values from EntityTypePicker filter.
To avoid breaking changes, it could make sense to create a separate filter for that, e.g., `EntityMultipleTypePicker` or something along the lines.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Hey :wave: this sounds like a good addition, do you want to create a PR for this? Sounds like it might be best to do as a separate filter entirely though just in order not to break the API contract, but it might be possible?

**Comment by morganmspencer** [comment]
Just opened a PR https://github.com/backstage/backstage/pull/19930 to do something similar with kinds and then found this issue. Thought it would be good to share

**Comment by roman-shandurenko** [comment]
> Just opened a PR #19930 to do something similar with kinds and then found this issue. Thought it would be good to share

Great! Thanks for that!
Could you also, please, attach the issue to your PR for track-reference?
