### ISSUE TITLE
🐛 Bug Report: azure devops provider producing duplicate locations

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#19432]
### 📜 Description

The azure devops provider uses code search to find catalog info files matching, sometimes it finds multiple instances of the same file, which breaks the cataloging of the duplicates.

### 👍 Expected behavior

I expect the duplications to be removed or handled before commiting the files to the catalog.

### 👎 Actual Behavior with Screenshots

The following failure shows in the logs:

```
Source AzureDevOpsEntityProvider:dUcXXasIbQfndEmf detected conflicting entityRef location:default/generated-ecd31864f366a58ab40adfc6a9d50de698778935 already referenced by url:https://dev.azure.com/name/repo/_git/path?path=/something/something/catalog-info.yaml and now also AzureDevOpsEntityProvider:dUcXXasIbQfndEmf
```

### 👟 Reproduction steps

I am not sure how to get the azure search to return multiple instances of the same file but it happens sometimes.

### 📃 Provide the context for the Bug.

It sesms to be causing the catalog to drop those entities that are duplicated, and then they might come back later if there is no duplicates in the next search.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@punkle is this good to close?

**Comment by punkle** [comment]
Yes we can close this @benjdlambert. I have since found a follow up issue with the provider whereby the provider is providing different numbers of entities each time it runs depending as the search index in azure is changing. See here https://github.com/backstage/backstage/pull/19478
