### ISSUE TITLE
🐛 Bug Report: Cant resolve swagger-ui-react

### ISSUE THREAD

**Issue by matt-prinold** [backstage/backstage#19443]
### 📜 Description

When following the getting started guide to creating a backstage app. running `yarn dev` results in the error: Module not found: Error: Can't resolve 'swagger-ui-react in '.../node_modules/@backstage/plugin-api-docs/dist/esm'

### 👍 Expected behavior

Should load the backstage application without errors

### 👎 Actual Behavior with Screenshots

<img width="1562" alt="Screenshot 2023-08-17 at 16 53 25" src="https://github.com/backstage/backstage/assets/82093576/d6157271-5ccb-4a1d-8f60-4d171d410e97">

![Screenshot 2023-08-17 at 16 55 17](https://github.com/backstage/backstage/assets/82093576/b89d74ba-b1da-42b4-86de-1281c1b1cba9)

### 👟 Reproduction steps

- having installed all the prerequisites

1. run `npx @backstage/create-app@latest`
2. enter a app name and wait for it to succesfully create the app
3. cd into the app
4. run `yarn dev`

### 📃 Provide the context for the Bug.

no changes made

### 🖥️ Your Environment

yarn run v1.22.19
$ /Users/matt_prinold/Documents/repos/work/backstage-playground/backstage-app/node_modules/.bin/backstage-cli info
OS:   Darwin 22.6.0 - darwin/x64
node: v18.16.1
yarn: 1.22.19
cli:  0.22.10 (installed)
backstage:  1.17.0

Dependencies:
  @backstage/app-defaults                          1.4.2
  @backstage/backend-app-api                       0.5.0
  @backstage/backend-common                        0.19.2
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-openapi-utils                 0.0.3
  @backstage/backend-plugin-api                    0.6.0
  @backstage/backend-tasks                         0.5.5
  @backstage/catalog-client                        1.4.3
  @backstage/catalog-model                         1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.3
  @backstage/cli                                   0.22.10
  @backstage/config-loader                         1.4.0
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.9.1
  @backstage/core-components                       0.13.4
  @backstage/core-plugin-api                       1.5.3
  @backstage/errors                                1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.5
  @backstage/integration-react                     1.1.16
  @backstage/integration                           1.6.0
  @backstage/plugin-api-docs                       0.9.7
  @backstage/plugin-app-backend                    0.3.48
  @backstage/plugin-app-node                       0.1.0
  @backstage/plugin-auth-backend                   0.18.6
  @backstage/plugin-auth-node                      0.2.17
  @backstage/plugin-catalog-backend                1.12.0
  @backstage/plugin-catalog-common                 1.0.15
  @backstage/plugin-catalog-graph                  0.2.33
  @backstage/plugin-catalog-import                 0.9.11
  @backstage/plugin-catalog-node                   1.4.1
  @backstage/plugin-catalog-react                  1.8.1
  @backstage/plugin-catalog                        1.12.1
  @backstage/plugin-events-node                    0.2.9
  @backstage/plugin-github-actions                 0.6.2
  @backstage/plugin-org                            0.6.11
  @backstage/plugin-permission-common              0.7.7
  @backstage/plugin-permission-node                0.7.11
  @backstage/plugin-permission-react               0.4.14
  @backstage/plugin-proxy-backend                  0.3.0
  @backstage/plugin-scaffolder-backend             1.16.0
  @backstage/plugin-scaffolder-common              1.4.0
  @backstage/plugin-scaffolder-node                0.2.0
  @backstage/plugin-scaffolder-react               1.5.2
  @backstage/plugin-scaffolder                     1.14.2
  @backstage/plugin-search-backend-module-catalog  0.1.4
  @backstage/plugin-search-backend-module-pg       0.5.9
  @backstage/plugin-search-backend-module-techdocs 0.1.4
  @backstage/plugin-search-backend-node            1.2.4
  @backstage/plugin-search-backend                 1.4.0
  @backstage/plugin-search-common                  1.2.5
  @backstage/plugin-search-react                   1.6.4
  @backstage/plugin-search                         1.3.4
  @backstage/plugin-tech-radar                     0.6.7
  @backstage/plugin-techdocs-backend               1.6.5
  @backstage/plugin-techdocs-module-addons-contrib 1.0.16
  @backstage/plugin-techdocs-node                  1.7.4
  @backstage/plugin-techdocs-react                 1.1.9
  @backstage/plugin-techdocs                       1.6.6
  @backstage/plugin-user-settings                  0.7.6
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.2
  @backstage/theme                                 0.4.1
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @matt-prinold, I think you're hitting this upstream issue: https://github.com/swagger-api/swagger-ui/issues/9143

Basically when you run create-app it will pull in the latest packages to start and version `5.4.1` of `swagger-ui-react` seems to be a bad release, sadly

**Comment by awanlin** [comment]
A temporary fix might be to add this to your root `package.json`:

```json
"resolutions": {
    "swagger-ui-react": "5.3.2",
  }
```

**Comment by robertsa1-els** [comment]
I am also seeing an issue with `Error: Invalid configuration schema in ../../node_modules/@backstage/plugin-proxy-backend/config.d.ts`

Is this related or a separate issue? 

Thanks for the help

```
❯ yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[1] Build succeeded
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/robertsa1/src/scratch/dev10/bleh/backstage/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all
[1] Backend failed to start up Error: Invalid configuration schema in ../../node_modules/@backstage/plugin-proxy-backend/config.d.ts, the following definitions are not supported:
[1]
[1]   Partial<{[key:string]:string;Authorization:string;authorization:string;'X-Api-Key':string;'x-api-key':string;}>
[1]     at /Users/robertsa1/src/scratch/dev10/bleh/backstage/node_modules/@backstage/config-loader/dist/index.cjs.js:348:15
[1]     at Array.map (<anonymous>)
[1]     at compileTsSchemas (/Users/robertsa1/src/scratch/dev10/bleh/backstage/node_modules/@backstage/config-loader/dist/index.cjs.js:322:27)
[1]     at async collectConfigSchemas (/Users/robertsa1/src/scratch/dev10/bleh/backstage/node_modules/@backstage/config-loader/dist/index.cjs.js:299:21)
[1]     at async Object.loadConfigSchema (/Users/robertsa1/src/scratch/dev10/bleh/backstage/node_modules/@backstage/config-loader/dist/index.cjs.js:481:15)
[1]     at async Object.createConfigSecretEnumerator (/Users/robertsa1/src/scratch/dev10/bleh/backstage/node_modules/@backstage/backend-app-api/dist/index.cjs.js:195:18)
[1]     at async loadBackendConfig (/Users/robertsa1/src/scratch/dev10/bleh/backstage/node_modules/@backstage/backend-common/dist/index.cjs.js:400:28)
[1]     at async main (webpack-internal:///./src/index.ts:83:20)
[0] ERROR in ../../node_modules/@backstage/plugin-api-docs/dist/esm/OpenApiDefinition-31f0d6c2.esm.js 3:0-41
[0] Module not found: Error: Can't resolve 'swagger-ui-react' in '/Users/robertsa1/src/scratch/dev10/bleh/backstage/node_modules/@backstage/plugin-api-docs/dist/esm'
```

**Comment by awanlin** [comment]
With a fresh create-app this resolutions does fix the issue until a proper package has been published up stream:

```json
"resolutions": {
    "@types/react": "^17",
    "@types/react-dom": "^17",
    "swagger-ui-react": "5.3.2"
  },
  ```

**Comment by awanlin** [comment]
Hi @robertsa1-els, not related, seems you have some bad config, please log an issue for that. There's no proxy setup in a default create-app

**Comment by robertsa1-els** [comment]
> Hi @robertsa1-els, not related, seems you have some bad config, please log an issue for that. There's no proxy setup in a default create-app

Thanks for the help. I will do that 👍

**Comment by webark** [comment]
the upstream issue has been resolved, so I ran into this when I upgraded yesterday, but upgrading the transitive dependency (the release was a patch and is within the ranges laid out) will get it working again.

**Comment by matt-prinold** [comment]
> A temporary fix might be to add this to your root `package.json`:
> 
> ```json
> "resolutions": {
>     "swagger-ui-react": "5.3.2",
>   }
> ```

@awanlin Thanks, this has resolved the issue while we wait for the swagger-ui-react upstream dependency to be resolved

**Comment by awanlin** [comment]
> the upstream issue has been resolved, so I ran into this when I upgraded yesterday, but upgrading the transitive dependency (the release was a patch and is within the ranges laid out) will get it working again.

@webark, I upgraded the Demo site just a few hours before this hit and was very confused when someone posted about it on Discord. Guess it's live by packages die by packages 🤷

**Comment by awanlin** [comment]
@matt-prinold, a new version of `swagger-ui-react` has been released, can you try again? If it works can you close this issue, please?

**Comment by matt-prinold** [comment]
@awanlin I can confirm the new version works fine one fresh app. Thanks

**Comment by asotog** [comment]
I installed a clean backstage today, still happening the issue, this is the workspace package if you need it
```
➜  demo git:(master) ✗ cat package.json
{
  "name": "root",
  "version": "1.0.0",
  "private": true,
  "engines": {
    "node": "16 || 18"
  },
  "scripts": {
    "dev": "concurrently \"yarn start\" \"yarn start-backend\"",
    "start": "yarn workspace app start",
    "start-backend": "yarn workspace backend start",
    "build:backend": "yarn workspace backend build",
    "build:all": "backstage-cli repo build --all",
    "build-image": "yarn workspace backend build-image",
    "tsc": "tsc",
    "tsc:full": "tsc --skipLibCheck false --incremental false",
    "clean": "backstage-cli repo clean",
    "test": "backstage-cli repo test",
    "test:all": "backstage-cli repo test --coverage",
    "lint": "backstage-cli repo lint --since origin/master",
    "lint:all": "backstage-cli repo lint",
    "prettier:check": "prettier --check .",
    "new": "backstage-cli new --scope internal"
  },
  "workspaces": {
    "packages": [
      "packages/*",
      "plugins/*"
    ]
  },
  "devDependencies": {
    "@backstage/cli": "^0.22.10",
    "@spotify/prettier-config": "^12.0.0",
    "concurrently": "^8.0.0",
    "lerna": "^4.0.0",
    "node-gyp": "^9.0.0",
    "prettier": "^2.3.2",
    "typescript": "~5.0.0"
  },
  "resolutions": {
    "@types/react": "^17",
    "@types/react-dom": "^17"
  },
  "prettier": "@spotify/prettier-config",
  "lint-staged": {
    "*.{js,jsx,ts,tsx,mjs,cjs}": [
      "eslint --fix",
      "prettier --write"
    ],
    "*.{json,md}": [
      "prettier --write"
    ]
  }
}
```

**Comment by awanlin** [comment]
Hi @asotog, they published a new package version which also has some issues, this fixes it for us:

```json
"resolutions": {
    "swagger-ui-react": "5.5.0",
  }
  ```

**Comment by asotog** [comment]
thanks @awanlin, fixed with this approach, lately days, no body seems to care about semantic versioning
