### ISSUE TITLE
🐛 Bug Report: User entity not found error 

### ISSUE THREAD

**Issue by Pvv7707** [backstage/backstage#19468]
### 📜 Description

When I open my profile in backstage instance where i can see 2 options
 User Entity: [user:default/username]
Ownership Entities: [user:default/username]
after clicking on one I am getting this user entity not found error 

I am using GitHub Oauth app for login authentication

### 👍 Expected behavior

why i am getting this error after clicking on my username 
i thought it will show my identity 

### 👎 Actual Behavior with Screenshots

![bs1](https://github.com/backstage/backstage/assets/142504329/b0a61dc8-dfc7-489b-a223-c031544e91b6)
![bs](https://github.com/backstage/backstage/assets/142504329/077891b0-77b6-49c2-a847-77daa633c546)

### 👟 Reproduction steps

go to profile 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Parsifal-M** [comment]
Hey! 👋

Are you doing this?

https://backstage.io/docs/integrations/github/org

By the looks of it, you have authentication set up, but don't have an associated user in backstage created (which have to come from somewhere). 

👍

**Comment by Pvv7707** [comment]
Hi! 👋
how can we create user in backstage ?
I am somewhat new to this whole thing

this is my code from catalog.ts

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addEntityProvider(
    GithubEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      // optional: alternatively, use scheduler with schedule defined in app-config.yaml
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { minutes: 30 },
        timeout: { minutes: 3 },
      }),
      // optional: alternatively, use schedule
      scheduler: env.scheduler,
    }),
  );
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  builder.addProcessor(new EntityAnnotationPreprocessor());
  const { processingEngine, router } = await builder.build();
  await processingEngine.start();

  const unprocessed = new UnprocessedEntitiesModule(
    await env.database.getClient(),
    router,
  );
  unprocessed.registerRoutes();
  return router;
}
this is my auth.ts

 github: providers.github.create({
        signIn: {
          resolver: async (info, ctx) => {
            const username = info.result.fullProfile.username;
            if (!username) {
              // This should never happen...
              throw new Error('No username found for the user.');
            }
            const userRef = `user:default/${username}`;

            return ctx.issueToken({
              claims: {
                sub: userRef,
                ent: [userRef],
              },

**Comment by benjdlambert** [comment]
@Pvv7707 is this a brand new project or have you done some form of upgrade, wondering if this has started to break recently with a change or if there's something else happening here.

**Comment by Pvv7707** [comment]
Yes its a new project i needed these user identities to check the entity feedback plugin to work because without the user identities we cant see the feedback responses 

below code is my catalog.ts 
after using this GithubOrgEntityProvider instead of GithubEntityProvider i am not able to see the components loading in catalog 
is there anything i am missing ?
```
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
    builder.addEntityProvider(
        GithubOrgEntityProvider.fromConfig(env.config, {
            // this is the ID you've configured in your config. 
            // your config example shows you set one up called "development"
            id: 'development',
            // the host and org you want to ingest; you likely don't want to load this org,
            orgUrl: 'url',
            logger: env.logger,
            schedule: env.scheduler.createScheduledTaskRunner({
                frequency: { minutes: 30 },
                timeout: { minutes: 3 },
            }),
        }),
    );
```

**Comment by Parsifal-M** [comment]
> Yes its a new project i needed these user identities to check the entity feedback plugin to work because without the user identities we cant see the feedback responses
> 
> below code is my catalog.ts after using this GithubOrgEntityProvider instead of GithubEntityProvider i am not able to see the components loading in catalog is there anything i am missing ?
> 
> ```
> export default async function createPlugin(
>   env: PluginEnvironment,
> ): Promise<Router> {
>   const builder = await CatalogBuilder.create(env);
>     builder.addEntityProvider(
>         GithubOrgEntityProvider.fromConfig(env.config, {
>             // this is the ID you've configured in your config. 
>             // your config example shows you set one up called "development"
>             id: 'development',
>             // the host and org you want to ingest; you likely don't want to load this org,
>             orgUrl: 'url',
>             logger: env.logger,
>             schedule: env.scheduler.createScheduledTaskRunner({
>                 frequency: { minutes: 30 },
>                 timeout: { minutes: 3 },
>             }),
>         }),
>     );
> ```

Hey!

Sorry, I think I miss-read your initial issue, with the `GithubEntityProvider` it looks like (although you have omitted it in your screenshot I assume) you do get a user entity which is `user:default/your-username` but I am not sure how you got that user there in the first place 😅 did you import it with a `.yaml`?

The `GithubOrgEntityProvider` will only import `users` and `groups` automatically AFAIK. However, I think you should still be able to use both providers they are not mutually exclusive.

The `GithubEntityProvider` will automatically pull in catalog-info.yaml files I believe, or at least it says [here](https://backstage.io/docs/integrations/github/discovery):

> The GitHub integration has a discovery provider for discovering catalog entities within a GitHub organization. The provider will crawl the GitHub organization and register entities matching the configured path. 

Please correct me if I am wrong @benjdlambert 

Hope this helps 👍

**Comment by Pvv7707** [comment]
Hi @Parsifal-M
i was able to add the user identity (myself) inside backstage manually through ts file and providing the location in app config yaml. 
But i need to add all my org groups and users individually, how is that possible? 
can you please provide some insight? 
thanks in advance :)

**Comment by awanlin** [comment]
Hi @Pvv7707, the GitHub Org Provider is what you are looking for an it's documented here: https://backstage.io/docs/integrations/github/org

**Comment by Pvv7707** [comment]
Thanks @awanlin for quick response
i have org provider added in my catalog.ts but i was not able to see the user identities when i click on profile and then on my identity as i mentioned in my first comment i am getting this error
https://user-images.githubusercontent.com/142504329/261859270-b0a61dc8-dfc7-489b-a223-c031544e91b6.png

**Comment by awanlin** [comment]
Right, the GitHub Org provider will bring in all the users and group that you have access to from GitHub. If you go to http://localhost:3000/catalog?filters%5Bkind%5D=group&filters%5Buser%5D=all or http://localhost:3000/catalog?filters%5Bkind%5D=user&filters%5Buser%5D=all you should be able to see the Groups or Users that have been imported. 

Once that's in place then you can update your `auth.ts` to do the mapping which is the initial issue you logged.

**Comment by awanlin** [comment]
The dos on how to setup the `auth.ts` are here: https://backstage.io/docs/auth/identity-resolver

In you case you might want to use this: `providers.github.resolvers.usernameMatchingUserEntityName()`

The code for how that works is here: https://github.com/backstage/backstage/blob/263e3846d8e0d2270800f7ddc224da902912f53e/plugins/auth-backend/src/providers/github/provider.ts#L135

**Comment by Pvv7707** [comment]
Thanks again
I can see the groups and all in this http://localhost:3000/catalog?filters%5Bkind%5D=group&filters%5Buser%5D=all 
I also need  modifying the user for some conditional to check if the user exists in the DB. if they do not, you would create them there before issuing a token.
is that condition possible something like this 
```
if (!userExists) {
  createuser(userRef); // or username, whichever the plugin needs to work
}
```

**Comment by awanlin** [comment]
That's actually not a recommended pattern and will cause a bad user experience when they log in. 

I'd recommend figuring our why Groups get ingested by the GitHub Org Provider and not Users. You should be able to pull in Users this way, it's how many Backstage Adopters do this

@Parsifal-M, any tips on this? I haven't used this myself

**Comment by Parsifal-M** [comment]
Hey @Pvv7707 

Can we close this one out? Unless you need more help on this topic? 👍

**Comment by Pvv7707** [comment]
Thanks for all the help provided
