### ISSUE TITLE
🐛 Bug Report: CatalogProcessor.postProcessEntity does not update entity annotations

### ISSUE THREAD

**Issue by matarnold-dev** [backstage/backstage#19465]
### 📜 Description

I have implemented a CatalogProcessor.  The processor overrides the "postProcessEntity" function.  Inside that function I update the Entity's "metadata.annotations" array with a custom annotation.

entity.metadata.annotations['my-custom-annotation'] = 'my value'

At the end of the function I return the updated Entity.  But, the next time the entity comes through the processor, it doesn't have the annotation on it?  I've waited for multiple cycles of the entity to process through, but it never receives the annotation.

### 👍 Expected behavior

Store the custom annotation on the entity object during postProcessEntity and have it saved in the catalog on the entity.

### 👎 Actual Behavior with Screenshots

does nothing

### 👟 Reproduction steps

1. create a custom CatalogProcessor and inject into the catalog's global builder.
2. inside your custom CatalogProcessor, override the "postProcessEntity" method
3. inside the postProcessEntity method, add an annotation to the entity
4. watch the entity come through the postProcessEntity method at a later time, and notice it doesn't have the annotation

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Processors rebuild the Entity every time they run, so you won't be able to access the previous state of the Entity and the annotation that you saved before, but it should be available out of the Catalog API once you've saved it.

If you're wanting to reuse state between processor runs, we'd recommend you use the `ProcessorCache` instead.

What's you use case here?

**Comment by freben** [comment]
@smoothzz It's not a problem - it's how the processors work. They are given the same unmodified input over and over again, and are expected to produce the output likewise again. You can never, in any way, do anything in the processor that changes its _input_ - only its output.

https://backstage.io/docs/features/software-catalog/life-of-an-entity

Note how the flow of data is one-directional.
