### ISSUE TITLE
🐛 Bug Report: Azure devops entity provider is providing inconsistent numbers of locations

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#19479]
### 📜 Description

The search feature in azure devops is not consistent across pages of search results. This is especially true if the search is using the default sort order which is based on a search score. See here 

https://learn.microsoft.com/en-us/azure/search/search-pagination-page-layout#paging-results

This is causing the azure entity provider to miss some entities as the index in search is changing.

### 👍 Expected behavior

It should always return the same number of locations if there has been no change to the catalog info files.

### 👎 Actual Behavior with Screenshots

It is providing varying numbers of locations, and it is causing to delete entities that are valid.

### 👟 Reproduction steps

Its hard to reproduce, because we cannot control the behaviour of the search feature in azure.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
fixed by https://github.com/backstage/backstage/pull/19478
