### ISSUE TITLE
🙏 Help Wanted: Auth Backend Module Migrations

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#19476]
The auth backend recently introduced a new architecture as it was migrated to support the [new backend system](https://backstage.io/docs/backend-system/) in #19280. The new architecture implements the auth provider specific logic as "authenticators". There are currently two different kinds of authenticators, OAuth and proxy, along with accompanying route handlers and provider factories.

As part of this we also move all auth providers to be separate modules, and then use that new module for the implementation in `auth-backend` for backwards compatibility.

## Process

For any given OAuth provider implementation, the following is a good starting point for migrating any provider:

1. Duplicate the `plugins/auth-backend-module-gitlab-provider` directory to `plugins/auth-backend-module-<provider-id>-provider`
2. Case sensitive search and replace all occurrences of `GitLab` with `<ProviderName>`, use the name of the provider as it appears in text.
3. Case sensitive search and replace all occurrences of `Gitlab` with `<ProviderId>`, use the PascalCase version of the provider name as it appears in code, this might be the same as the previous step.
4. Case sensitive search and replace all occurrences of `gitlab` with `<providerId>`, use the camelCase version of the provider name as it appears in code.
5. Now passport strategy and any other provider-specific logic and configuration from `plugins/auth-backend/src/providers/<providerId>/provider.ts`. If there are tests for this specific logic then you can migrate those to authenticator or module tests, but other than that the existing provider tests can be deleted. If there are particular tests that you would like too keep, check if it makes sense to add them to https://github.com/backstage/backstage/blob/master/plugins/auth-node/src/oauth/createOAuthRouteHandlers.test.ts.
6. Update `config.d.ts` in the new module, move over and remove any related configuration in `plugins/auth-backend/config.d.ts`.
7. Now refactor `plugins/auth-backend/src/providers/<providerId>` to use the new module, adding a dependency for the new module to `auth-backend`. Use the legacy helpers as shown in [#19475](https://github.com/backstage/backstage/pull/19475/files#diff-cd63feb8b4e2c55a658d7d8b39fba458b31e95cf342ebf3b1a7ebd2c2fccee32), do not add additional resolvers, options, or other API.

The process for migrating a proxy provider is similar, but use `plugins/auth-backend-module-gcp-iap-provider` as a starting point instead.

## Migration Status

This is the current migration status of all auth providers that need migration. Let us know if you want to help out! 🙏 

- [x] atlassian #21007
- [x] auth0 #26421
- [x] aws-alb #22103
- [x] azure-easyauth #23909
- [x] bitbucket #24287
- [x] bitbucketServer #26407
- [x] cloudflare-access #23997
- [x] gcp-iap #19280
- [x] github #19473
- [x] gitlab #19475
- [x] google #19280
- [x] microsoft #20120 #22208
- [x] oauth2 #19696
- [x] oauth2-proxy #20685
- [x] oidc #20282
- [x] okta #21325
- [x] onelogin #24353
- [x] pinniped #19846
- [x] VMware Cloud #21337

**Comment by mihrab34** [comment]
Hi @Rugvip  I'd like to help out

**Comment by Rugvip** [comment]
@mihrab34 @IvyJeptoo great! 🎉 Best pick a single provider to start with

**Comment by Rugvip** [comment]
@mihrab34 seems like there's an issue with the isolated-vm installation, most likely you'll want to have a look at https://github.com/laverdet/isolated-vm#requirements and make sure that's covered for your OS

**Comment by awanlin** [comment]
Alright, that works for me, also forgot about the whole name change for Azure AD. Then feel free to work on this who every wants!

Thanks for the feedback @Rugvip @TheGemmell @afscrome 👍

**Comment by IvyJeptoo** [comment]
@Rugvip I just wanted to ask if it possible if we can mention the modules that each will be handling so that two people dont work on the same module(just a suggestion)

**Comment by Rugvip** [comment]
@IvyJeptoo yep makes sense, done

**Comment by awanlin** [comment]
I'll be running with `oauth2` as this is something we need internally 👍

**Comment by mihrab34** [comment]
@Rugvip  I opened a PR for `bitbucket` on #19665

**Comment by awanlin** [comment]
PR for the `oauth2` provider is here: https://github.com/backstage/backstage/pull/19696

**Comment by RubenV-dev** [comment]
I will be working on the oidc migration

**Comment by ahhhndre** [comment]
@TheGemmell what’s the ETA on the Microsoft auth module? This is blocking us from using the new backend system

**Comment by TheGemmell** [comment]
@ahhhndre 
Apologies, I actually finished the code changes, then had to go on leave for an emergency. Got back and had forgotten about it. I'll test and raise a PR by end of the weekend

**Comment by TheGemmell** [comment]
PR for `microsoft` provider is here: #20120

**Comment by awanlin** [comment]
Oh wow, hope everything is fine now @TheGemmell? That's for sure a more important priority but thanks for submitting the PR!

**Comment by jamieklassen** [comment]
PR for `oidc`: #20282

**Comment by guibes** [comment]
Hello, will be my first open source contribution, I can make for **atlassian**. I'll use some open PR to check how to make it easier.

**Comment by Josh-Uvi** [comment]
Hi @Rugvip, I opened a PR for the Okta Provider - #20854.

**Comment by handsamtw** [comment]
Hi @Rugvip , I opened a PR for the Atlassian Provider - #21007 , but there're some yarn install pipeline issue i haven't figured out, would you mind taking a look, thank you!

**Comment by Parsifal-M** [comment]
Is anyone looking at the `aws-alb` one? If not, I may take a shot at this one. 👍

**Comment by GuptaNavdeep1983** [comment]
@Parsifal-M, could you make some progress on aws-alb one? I did not realize that somebody is already working on it and started spending some time. Nevertheless, let me know if I can help as we use that one.

**Comment by Parsifal-M** [comment]
> @Parsifal-M, could you make some progress on aws-alb one? I did not realize that somebody is already working on it and started spending some time. Nevertheless, let me know if I can help as we use that one.
> 

Hey!

I had planned to start this weekend! But if you've already made progress that's fine! I will hold off for now ✌️

Could you tag me in the PR so I can also take a look once it's ready? I'm quite curious about it 👌

Thanks for the heads up!

**Comment by GuptaNavdeep1983** [comment]
Hi @Rugvip, I opened a PR for AWS ALB provider - https://github.com/backstage/backstage/pull/21810

**Comment by GuptaNavdeep1983** [comment]
@Rugvip Is there anything else I can do on this PR https://github.com/backstage/backstage/pull/21810?

**Comment by hasson82** [comment]
Hi, I'm willing to take azure-easyauth.

**Comment by yaegashi** [comment]
@hasson82 Have there been any updates regarding the azure-easyauth migration on your side?

I’m currently working on setting up DevOps for Backstage on Azure Container Apps and have ported azure-easyauth to the new backend system for internal use, as it has become the default configuration in Backstage v1.24.0.

https://github.com/yaegashi/dx2devops-backstage-containerapp

**Comment by yaegashi** [comment]
I'm working on the new azure-easyauth auth provider: https://github.com/backstage/backstage/pull/23909

The migration in the older provider is not yet implemented but coming soon.  Any comments or suggestions would be appreciated.

**Comment by salemgolemugoo** [comment]
Anyone can pick up Onelogin please?

**Comment by freben** [comment]
I made one for cfaccess https://github.com/backstage/backstage/pull/23997

**Comment by matteosilv** [comment]
> Anyone can pick up Onelogin and/or JumpCloud please?

I started taking a look at this, but I don't know how much effort I can put on it:

https://github.com/backstage/backstage/pull/24353

**Comment by matteosilv** [comment]
Made progresses with OneLogin impl. If anybody wants to review, I think is pretty much ready

**Comment by JeevaRamanathan** [comment]
Hello [Rugvip](https://github.com/Rugvip), I would like to confirm is bitbucketServer an OAuth provider or proxy provider?

**Comment by JeevaRamanathan** [comment]
Hi @freben,  is bitbucketServer based on OAuth provider

**Comment by Rugvip** [comment]
@JeevaRamanathan yes it is, the current implementation is over here: https://github.com/backstage/backstage/blob/f5e04e39d2e7da549309a21f008cc9f01c0b1e71/plugins/auth-backend/src/providers/bitbucketServer/provider.ts#L83

**Comment by Rugvip** [comment]
Properly closing this to mark it as done 😁 🎉 

Big thank you to everyone that contributed towards this! 🙏
