### ISSUE TITLE
🐛 Bug Report: GET api/catalog/entity-facets endpoint does not support multiple facets after version 1.17.0

### ISSUE THREAD

**Issue by danangarbansa** [backstage/backstage#19470]
### 📜 Description

After upgrading backstage to version 1.17.0 and forward, the api/catalog/entity-facets endpoint does not support multiple facets anymore. 

Here's the error I get upon calling this endpoint GET /api/catalog/entity-facets?filter=kind=Component&facet=kind&facet=spec.owner

```
{
"error": {
"name": "InputError",
"message": "request/query/facet must be string"
},
"request": {
"method": "GET",
"url": "[/entity-facets?filter=kind=Component&facet=kind&facet=spec.owner](https://galaxy.canva-internal.com/entity-facets?filter=kind=Component&facet=kind&facet=spec.owner)"
},
"response": {
"statusCode": 400
}
}
```

Looks like this happened after the schema validation is added in this [commit](https://github.com/backstage/backstage/pull/17875). 

The problem is, the client interface stated that this is still supported (See [here](https://github.com/backstage/backstage/blob/v1.17.1/packages/catalog-client/src/types/api.ts#L313)).

For more context, we rely on this API because we are using a custom catalog table that builds the filters section using the facets received from the get-entities endpoint.

### 👍 Expected behavior

I expect the GET /entity-facets to support getting multiple facets

```
{
"facets": {
"kind": [
{
"value": "Component",
"count": //redacted
}
],
"spec.owner": //redacted
},
```

### 👎 Actual Behavior with Screenshots

N/A, error is mentioned in the description

### 👟 Reproduction steps

Run backstage version 1.17.0 (or forward), and hit the GET `api/catalog/entity-facets` endpoint with multiple facets query param as array of string, e.g. `api/catalog/entity-facets?facet=kind&facet=spec.owner`. This should returns 400 error.

Alternatively, call the endpoint via the catalogApi in the FE code:

```
   const catalogApi = useApi(catalogApiRef);
   const { facets } = await catalogApi.getEntityFacets({
      facets: ['kind', 'spec.owner'],
    });
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Looks like the schema needs updating? @sennyeya do you have a quick fix for this? :pray:
