### ISSUE TITLE
🐛 Bug Report: Auth Provider - override JWT Token with new issuer

### ISSUE THREAD

**Issue by ayeletdeRoos** [backstage/backstage#19483]
### 📜 Description

We're using the [okta jwt backstage provider](https://backstage.io/docs/auth/okta/provider/) to verify users in backstage.
We want to pass on the Token in the header for some request in the backstage backend to internal services.

We noticed the token isn't the token OKTA provided, it's a backstage generated token, with the backstage api as the issuer instead of our okta issuer.

I need for security reasons - to use the same token okta provided, not the new Token backstage generated.
Is there a way to enforce that? 

### 👍 Expected behavior

Get the same Token that was issued on the user OKTA login to backstage

### 👎 Actual Behavior with Screenshots

We get backstage generated token with a different issuer.
![Screenshot 2023-08-21 at 13 20 56](https://github.com/backstage/backstage/assets/132264355/46c6d11f-26e1-427c-aee5-cab1ff5b9dbf)

instead of our company okta issuer

### 👟 Reproduction steps

login to backstage and send authorization header to internal service 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ayeletdeRoos** [comment]
Also - I'm trying to verify my token with the backstage jwks public key, and the kid of the token isn't found there.
is this the correct api to check - https://<backstage-url>/api/auth/.well-known/jwks.json  ?

**Comment by Rugvip** [comment]
You can get hold of the Okta access token with `.getAccessToken()`, or `.getIdToken()` for the ID token.

**Comment by ayeletdeRoos** [comment]
Hi, thanks for your replu.

I need this in the backend (to pass on as authorization header), the functions you mentioned are in the core-plugin-api pk -  that as far as I know are for the frontend

**Comment by Rugvip** [comment]
@ayeletdeRoos ah alright, in that case you need to grab the access token on the frontend using the before mentioned API, and pass it along to the backend for use there.

If you need to access the Okta API without a user token then you'll need to use service-to-service auth instead of user auth, we do not have a system in place that stores refresh tokens of users for use in backend request, and it's not something we want to add at this point.

**Comment by ayeletdeRoos** [comment]
Thanks for your reply!

another question - if we do you the backstage given token (that I get in the authorization header in the backend). is there a way to add more info on the payload (in the okta token we have a info like - groups, user email, etc)?

**Comment by tudi2d** [comment]
Exactly - `getAccessToken` will give you the actual okta token.

A custom [Sign-in resolver](https://backstage.io/docs/auth/identity-resolver/#sign-in-resolvers) could help passing through the payload. Specifically in the code example for the [cusomt ownership resolution](https://backstage.io/docs/auth/identity-resolver/#custom-ownership-resolution) you can see how to issue a token & add `claims` to it :)

**Comment by ayeletdeRoos** [comment]
@tudi2d I will check that out. thanks a lot!
