### ISSUE TITLE
🐛 Bug Report: Calls to CatalogApi.queryEntities results in 400 (fullTextFilterFields must be url encoded)

### ISSUE THREAD

**Issue by jslott2sigma** [backstage/backstage#19499]
### 📜 Description

With the following call (in my own code, but very similar to https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/components/EntityOwnerPicker/useQueryEntities.ts#L48):
```
      const response = await catalogApi.queryEntities({
        fullTextFilter: {
          term: initialRequest.text || '',
          fields: [
            'metadata.name',
            'kind',
            'spec.profile.displayname',
            'metadata.title',
          ],
        },
        filter: { kind: ['User'] },
        orderFields: [{ field: 'metadata.name', order: 'asc' }],
        limit,
      });
```
I get a 400 error with the following response body:
```
{
    "error": {
        "name": "InputError",
        "message": "Parameter 'fullTextFilterFields' must be url encoded. Its value may not contain reserved characters.",
        "stack": "InputError: Parameter 'fullTextFilterFields' must be url encoded. Its value may not contain reserved characters"
    },
    "request": {
        "method": "GET",
        "url": "/entities/by-query?filter=kind=User&limit=20&orderField=metadata.name,asc&fullTextFilterFields=metadata.name,kind,spec.profile.displayname,metadata.title"
    },
    "response": {
        "statusCode": 400
    }
}
```

### 👍 Expected behavior

This API call should return a successful response.

### 👎 Actual Behavior with Screenshots

The API call returned a 400, see error response above.

### 👟 Reproduction steps

Invoke the API call above from client code.

### 📃 Provide the context for the Bug.

I first saw this bug in 1.17.0 (upgrading from 1.15.0), but it also exists in 1.17.2.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sennyeya** [comment]
@Rugvip This is another issue with the OpenAPI spec. Similar to #19357, the `CatalogClient` is creating invalid URL segments. I unfortunately won't have time to fix this until tonight. 

\There's 2 solutions here,
1. Rollback the OpenAPI changes to the catalog from #17875, and then start to add them back in later releases with more rigorous testing.
2. Add `allowReserved: true` to all query parameters and we can start to remove it where it makes sense to. This would be my pick, as it just removes some added strictness with the validation. It would be equivalent to the protection we had before applying OpenAPI router changes.

I will be writing a large number of test cases for the catalog router in either case.
