### ISSUE TITLE
🔌 Plugin: Jira Plugin for the Backstage

### ISSUE THREAD

**Issue by riginoommen** [backstage/backstage#19500]
### 🔖 Summary

Integrating the JIra with the Backstage can be the best option for collaborating on software pieces. A plugin which simply list the issues associated with the software component will be helpful along with the filters

### 🌐 Project website (if applicable)

https://www.atlassian.com/software/jira

### ✌️ Context

* Service Details page should have a dedicated card to display Jira issues
* The Jira section should show blockers, last 7 days and work in progress issues (Default setting)

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @riginoommen, Roadie.io actually created a Jira plugin - https://roadie.io/backstage/plugins/jira/ - maybe you that will fill your needs? If not you can always make a request here: https://github.com/RoadieHQ/roadie-backstage-plugins

**Comment by riginoommen** [comment]
Yes i made some contributions anthere and closing this
