### ISSUE TITLE
🚀 Feature: Scaffolder parseEntityRef filter enhancement

### ISSUE THREAD

**Issue by rikez** [backstage/backstage#19519]
### 🔖 Feature description

We would like to add `defaultNamespace` and `defaultKind` optional args to the [`parseEntityRef` Scaffolder filter](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/lib/templating/filters.ts#L30). 

### 🎤 Context

We utilize this filter in various templates and in some cases we would like to infer default kind and/or namespace for these entities. Here's an example:

``` yaml
if: ${{ (steps['fetch-component-details'].output.entity.spec.owner | parseEntityRef | pick('name')) != 'group-example' }}
```

The above expressions logs an error if `spec.owner` isn't in the entity ref format.

### ✌️ Possible Implementation

On https://github.com/backstage/backstage/blob/v1.17.2/plugins/scaffolder-backend/src/lib/templating/filters.ts#L30:

```typescript
parseEntityRef: (ref: string, defaultKind?: string, defaultNamespace?: string) => {
  return parseEntityRef(ref as string, { defaultKind, defaultNamespace })
}
```

Example:
``` yaml
${{ steps['fetch-component-details'].output.entity.spec.owner | parseEntityRef('group') }}
${{ steps['fetch-component-details'].output.entity.spec.owner | parseEntityRef('resource', 'org') }}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by vinzscam** [comment]
yeah it makes total sense! 🚀

**Comment by freben** [comment]
closing as fixed!
