### ISSUE TITLE
🚀 Feature: integrators bring their own kubernetes auth providers

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#19530]
### 🔖 Feature description

Clusters with exotic [webhook token authentication](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#webhook-token-authentication) schemes, or clusters with a Pinniped concierge installed (see #14011) and configured to [validate webhook tokens](https://pinniped.dev/docs/howto/concierge/configure-concierge-webhook/) may require tokens to come from highly flexible sources which cannot easily be described with pure YAML config. In such cases, integrators may wish to customize both the front- and back-end to acquire appropriate tokens before submitting them to the cluster in question.

### 🎤 Context

It'd be nice if, when installing the Kubernetes Backend plugin as documented [here](https://backstage.io/docs/features/kubernetes/installation#adding-kubernetes-backend-plugin), you could do something like

```typescript
export class CustomWebhookAuthTranslator {
  async decorateClusterDetailsWithAuth(
    clusterDetails: ClusterDetails,
    auth: KubernetesRequestAuth,
  ): Promise<ClusterDetails> {
    const authDataFromFrontend = auth['customWebhook'];
    const webhookToken = await doSomeExoticAsynchronousStuff(authDataFromFrontend);
    return { ..clusterDetails, serviceAccountToken: webhookToken };
  }
}

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await KubernetesBuilder.createBuilder({
     logger: env.logger,
     config: env.config,
  }).build();
  builder.addAuthTranslator('customWebhook', new CustomWebhookAuthTranslator());
  const { router } = await builder.build();
  return router;
}
```

and then override the utility API factory for [`kubernetesAuthProvidersApiRef`](https://backstage.io/docs/reference/plugin-kubernetes.kubernetesauthprovidersapiref/) with an implementation which handles the new `'customWebhook'` auth provider like

```typescript
class CustomKubernetesAuthProviders extends KubernetesAuthProviders {
  async getCredentials(authProvider: string) : Promise<{token?: string}> {
    if (authProvider === 'customWebhook') {
      return { token: await someAuthApi.getAccessToken() };
    }
    return super.getCredentials(authProvider);
  }
}
```

to then allow specifying clusters in your config or catalog like

```yaml
kubernetes:
  clusterLocatorMethods:
    - type: config
      clusters:
        - name: cluster-with-custom-authprovider
          url: https://my.cluster
          authProvider: customWebhook
```

### ✌️ Possible Implementation

Here are the rough pieces I think need to be addressed for this to be possible:
* Create an `addAuthTranslator` method on the `KubernetesBuilder`, similar to the `addEntityProvider` method on `CatalogBuilder` -- this should be straightforward.
* Make the [`KubernetesRequestAuth`](https://backstage.io/docs/reference/plugin-kubernetes-common.kubernetesrequestauth) type a bit more flexible, to allow adding new `auth.*` fields without changing the type definition -- this is also probably not too controversial, hopefully we can add an appropriate [index signature](https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures) while maintaining backwards compatibility.
* We'd need the ConfigClusterLocator to be parameterized in such a way that it no longer cares about the specific `authProvider` values -- maybe we expand the "auth translator" concept to include "reading from config" as well as doing auth translation?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mclarke47** [comment]
Sounds like a good use of extension points, I think there might be some boilerplate to set up all that in the first place
