### ISSUE TITLE
🐛 Bug Report: Receive HttpError: fetch failed when creating GitHub Repo with Documentation Template 

### ISSUE THREAD

**Issue by ChiaraKr** [backstage/backstage#19540]
### 📜 Description

When trying to use the documentation template available under [software templates](https://github.com/backstage/software-templates/tree/main/scaffolder-templates/docs-template) and trying to push it to public github the operation breaks during the publishing process. 

### 👍 Expected behavior

I wanted to create a GitHub Documentation Repository with the documentation template. 

### 👎 Actual Behavior with Screenshots

After inserting all information in the form and clicking create the process starts and throws the following error: 

![262446625-51e5ff7f-face-4547-9845-b316d283ff20](https://github.com/backstage/backstage/assets/60965659/51e22625-c8cc-44c0-8fe2-c1819c74916c)

Analyzing the process with the web-developer tool, I received the following logs: 

![262594181-1fff4046-5826-465c-ab3a-ddb1d260e83a](https://github.com/backstage/backstage/assets/60965659/06c9acc7-6a8d-4f4e-94bc-5b1fcc91e3d3)

### 👟 Reproduction steps

Configured GitHub integration in app-config.yaml:

![grafik](https://github.com/backstage/backstage/assets/60965659/1373c8a5-70b5-4b79-83a5-80f9ea392ed9)

Use the documentation template available at [software templates](https://github.com/backstage/software-templates/tree/main/scaffolder-templates/docs-template).

Add the template to the catalog:

![grafik](https://github.com/backstage/backstage/assets/60965659/980db9e5-cca1-48a6-bed9-cb2aefd29e8c)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by rahulv5** [comment]
Hey @ChiaraKr , did you end up fixing this issue? I've encountered something similar and logged here https://github.com/backstage/backstage/issues/22206
