### ISSUE TITLE
Sonarqube Backstage Integration Issue : Getting 404 Error

### ISSUE THREAD

**Issue by shrinathkrish** [backstage/backstage#19541]
### 📜 Description

I have deployed a backstage application in on premise kubernetes cluster.
It is up and running successfully.
While I tried to Integrate backstage with our sonarqube instance getting 404 Error

App-config configuration in backstage :

```yaml
sonarqube:
  baseUrl: http://sonarqube.********************.com
  apiKey: 42*************************************cef
```
  
  
  Catalog.yaml :
  
```yaml
apiVersion: backstage.io/v1alpha1`
kind: Component
metadata:
  annotations:
    sonarqube.org/project-key: 'sonarqube.************.com/Central-idp
```

Central-idp is the project key i got it from the administration tab in Sonarqube UI

Followed this particular document for backend and frontend sonarqube plugin installation :
https://github.com/backstage/backstage/blob/master/plugins/sonarqube-backend/README.md
https://github.com/backstage/backstage/blob/master/plugins/sonarqube/README.md

### 👍 Expected behavior

The Sonarqube plugin needs to show data from sonarqube instance

<img width="451" alt="sonar-card" src="https://github.com/backstage/backstage/assets/97064460/32033488-7070-4aed-9bfe-e321ebb9cd6c">

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/97064460/8d389b34-67de-46f8-9b52-82ad0142776e)

Error message from log :

`{"level":"info","message":"::ffff:10.233.76.29 - - [23/Aug/2023:06:19:44 +0000] \"GET /api/sonarqube/instanceUrl?instanceKey=sonarqube.**********.com HTTP/1.1\" 404 - \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36\"","service":"backstage","type":"incomingRequest"}
`

### 👟 Reproduction steps

- Build the backstage application with sonarqube plugin

- Using the catalog.yaml registered the component

- After successfully registering the component scroll to the Code Quality

- Similar error will be there
![image](https://github.com/backstage/backstage/assets/97064460/5e12efaf-02ea-438d-bb28-b6e82a2beab8)

### 🖥️ Your Environment

$ yarn backstage-cli info
yarn run v1.22.19
OS:   Windows_NT 10.0.19045 - win32/x64
node: v16.20.1
yarn: 1.22.19
cli:  0.22.10 (installed)
backstage:  1.17.0

Dependencies:
  @backstage/app-defaults                          1.4.2
  @backstage/backend-app-api                       0.4.3, 0.5.0, 0.5.1
  @backstage/backend-common                        0.18.5, 0.19.2, 0.19.3
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-openapi-utils                 0.0.3
  @backstage/backend-plugin-api                    0.5.2, 0.6.0, 0.6.1
  @backstage/backend-tasks                         0.5.2, 0.5.5, 0.5.6
  @backstage/catalog-client                        1.4.1, 1.4.3
  @backstage/catalog-model                         1.4.1, 1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.3
  @backstage/cli                                   0.22.10
  @backstage/config-loader                         1.3.0, 1.4.0
  @backstage/config                                1.0.8, 1.0.7
  @backstage/core-app-api                          1.8.0, 1.9.1
  @backstage/core-components                       0.12.5, 0.13.4
  @backstage/core-plugin-api                       1.5.3, 1.5.1
  @backstage/errors                                1.1.5, 1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.3, 0.1.5
  @backstage/integration-react                     1.1.16
  @backstage/integration                           1.4.5, 1.6.0, 1.6.1
  @backstage/plugin-api-docs                       0.9.7
  @backstage/plugin-app-backend                    0.3.48
  @backstage/plugin-app-node                       0.1.0
  @backstage/plugin-auth-backend                   0.18.6
  @backstage/plugin-auth-node                      0.2.14, 0.2.17, 0.2.18
  @backstage/plugin-catalog-backend                1.12.0, 1.9.1
  @backstage/plugin-catalog-common                 1.0.15, 1.0.13
  @backstage/plugin-catalog-graph                  0.2.33
  @backstage/plugin-catalog-import                 0.9.11
  @backstage/plugin-catalog-node                   1.3.6, 1.4.1
  @backstage/plugin-catalog-react                  1.8.2, 1.8.1
  @backstage/plugin-catalog                        1.12.1
  @backstage/plugin-events-node                    0.2.9
  @backstage/plugin-github-actions                 0.6.2
  @backstage/plugin-org                            0.6.11
  @backstage/plugin-permission-common              0.7.5, 0.7.7
  @backstage/plugin-permission-node                0.7.11, 0.7.12, 0.7.8
  @backstage/plugin-permission-react               0.4.14
  @backstage/plugin-proxy-backend                  0.3.0
  @backstage/plugin-scaffolder-backend             1.14.0, 1.16.0
  @backstage/plugin-scaffolder-common              1.3.0, 1.4.0
  @backstage/plugin-scaffolder-node                0.1.3, 0.2.0
  @backstage/plugin-scaffolder-react               1.5.2
  @backstage/plugin-scaffolder                     1.14.2
  @backstage/plugin-search-backend-module-catalog  0.1.1, 0.1.4
  @backstage/plugin-search-backend-module-pg       0.5.9
  @backstage/plugin-search-backend-module-techdocs 0.1.4
  @backstage/plugin-search-backend-node            1.2.1, 1.2.4
  @backstage/plugin-search-backend                 1.4.0
  @backstage/plugin-search-common                  1.2.3, 1.2.5
  @backstage/plugin-search-react                   1.6.4
  @backstage/plugin-search                         1.3.4
  @backstage/plugin-sonarqube-backend              0.2.3
  @backstage/plugin-sonarqube-react                0.1.7
  @backstage/plugin-sonarqube                      0.7.3
  @backstage/plugin-tech-radar                     0.6.7
  @backstage/plugin-techdocs-backend               1.6.5
  @backstage/plugin-techdocs-module-addons-contrib 1.0.16
  @backstage/plugin-techdocs-node                  1.7.4
  @backstage/plugin-techdocs-react                 1.1.9
  @backstage/plugin-techdocs                       1.6.6
  @backstage/plugin-user-settings                  0.7.6
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.2
  @backstage/theme                                 0.2.19, 0.4.1
  @backstage/types                                 1.0.2, 1.1.0
  @backstage/version-bridge                        1.0.4
Done in 1.70s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by shrinathkrish** [comment]
I have tried by changing the format in Catalog.yaml as follows :

```yaml
  annotations:
    sonarqube.org/project-key: 'Central-idp'
```

```yaml
  annotations:
    sonarqube.org/project-key: '/Central-idp'
```

```yaml
  annotations:
    sonarqube.org/project-key: http://sonarqube.**********.com'Central-idp'
```

But did not worked for any of those

**Comment by HazemAbdelmagid** [comment]
I am facing the same issue, any solution yet?

**Comment by camilaibs** [comment]
Hi, @backstage/sda-se-reviewers do you have any recommendations 🙂 ?

**Comment by freben** [comment]
[Here are](https://github.com/backstage/backstage/blob/62f448edb0b56b2e8c659a0b51331e0536379eca/plugins/sonarqube-react/src/hooks/useProjectInfo.ts#L48) some comments in the code showing how it treats this annotation.

**Comment by HazemAbdelmagid** [comment]
I have tried the 3 combination of Instance, Tenant and Project, none of them fetches any data from Sonar qube.

![Screenshot 2023-08-28 at 3 35 20 PM](https://github.com/backstage/backstage/assets/43639906/f1c2dd02-f212-421c-82ab-18efa59f7cba)

**Comment by Rugvip** [comment]
@HazemAbdelmagid given that error I'd expect a sonarqube instance called `vfgroup-tvois-cicd` to be registered in your config, do you have that? Something like this:

```yaml
sonarqube:
  instancesl
  - name: vfgroup-tvois-cicd
    baseUrl: ...
    apiKey: ...
```

**Comment by HazemAbdelmagid** [comment]
@Rugvip Acutally it isn't, I have tried the 3 following example annotations:
//   instanceA/projectA  -> projectInstance = "instanceA" & projectKey = "projectA"
//   instanceA/tenantA:projectA -> projectInstance = "instanceA" & projectKey = "tenantA:projectA"
//   instanceA/tenantA/projectA -> projectInstance = "instanceA" & projectKey = "tenantA/projectA"
and vfgroup-tvois-cicd is the tenant for vfgroup-tvois-cicd-demo project and I have taken screenshot from this state but in all 3 configurations, it didn't work.

**Comment by Hennnnes** [comment]
Hey 😊

Sorry for the late reply.
It's hard for me to fully identify the issue here as I am rather new to backstage and more on the frontend-side of things 😊

We're using it like this:
`app-config.yaml`:
```yaml
sonarqube:
    baseUrl: https://sonarcloud.io
    apiKey: API_KEY
```
`catalog-info.yaml`:
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    sonarqube.org/project-key: PROJECT_KEY
```
where `PROJECT_KEY` is the one that we use when taking a look at the sonarqube project using `https://sonarcloud.io/project/information?id=PROJECT_KEY`.

That setup works as expected for us.

I can try to debug further if I find time but would rather encourage taking a look at the code yourself and maybe add testcases for the cases that are throwing errors for you. That could be a nice way to identify possible issues and provide fixes for them directly 😊

On an additional note: We're currently rather short on capacity, therefore replies might be late 😊

**Comment by vjanz** [comment]
Having the exact same problem. I tried to setup using proxy as documented [here](https://roadie.io/backstage/plugins/sonarqube/#:~:text=Add%20the%20proxy%20config%20for%20SonarCloud%20(auth%20token%20is%20read%20from%20the%20environment%20variables)) and also based on the documentation in the [backstage repo](https://github.com/backstage/backstage/blob/master/plugins/sonarqube-backend/README.md#config-1). None of them work 🤔

**Comment by benjdlambert** [comment]
@vjanz I think that this documentation is out of date, You'll need to follow the `sonarqube-backend` plugin installation notes as it doesn't use the `proxy` setup which is documented in the Roadie docs. https://www.npmjs.com/package/@backstage/plugin-sonarqube-backend

**Comment by vjanz** [comment]
Hi @benjdlambert , thank you for taking the time to reply on the thread.


> Having the exact same problem. I tried to setup using proxy as documented [here](https://roadie.io/backstage/plugins/sonarqube/#:~:text=Add%20the%20proxy%20config%20for%20SonarCloud%20(auth%20token%20is%20read%20from%20the%20environment%20variables)) and also based on the documentation in the [backstage repo](https://github.com/backstage/backstage/blob/master/plugins/sonarqube-backend/README.md#config-1). None of them work 🤔

On the second link, I mentioned that I also tried the other way (not only the docs in Roadie). Still didn't work. (There is no sonarqube project with a key...)

**Comment by benjdlambert** [comment]
@backstage/sda-se-reviewers do you have any input here :pray:

**Comment by m0un10** [comment]
I'm getting the same issue and I suspect it's related to incompatibility with a new version of Backstage. I could be wrong but I make the assumption because I have an older backstage instance where it works and a newer one where it doesn't work. Is there any way to get good debugging information out of the plugin? I tried with `LOG_LEVEL=debug` but it didn't seem to add any extra logs related to SonarQube.

**Comment by camilaibs** [comment]
Hi @m0un10, `LOG_LEVEL=debug` is correct, but as it doesn't seem to add extra information, let's ping the plugin authors for help.
Hi @backstage/sda-se-reviewers 👋🏻 , could you provide us support on this issue?

**Comment by vjanz** [comment]
Hi @backstage/sda-se-reviewers. Any input here?

**Comment by Hennnnes** [comment]
Hey,

unfortunately since the [re-write of the sonarqube plugin towards using an own backend and no proxy anymore](https://github.com/backstage/backstage/pull/11925), we (@backstage/sda-se-reviewers) are not familiar with the depths of that code. On an additional note: We're currently rather short on capacity.

The problem kind of looks like the one mentioned in https://github.com/backstage/backstage/issues/20542. You could try the things suggested in the comments over there. 

Otherwise I cannot really help debugging the plugin, but I'd suggest you peeking into the code yourself in a local git clone of https://github.com/backstage/backstage.
The piece of code that might be helpful when debugging the case yourself are:
- https://github.com/backstage/backstage/blob/8e741a1bd29b92c767e9b308f151d10468be1980/plugins/sonarqube-backend/src/service/sonarqubeInfoProvider.ts#L305-L308

It should be possible to see what the Sonarqube API returns in that case for you when adding a `debugger`-statement or logging some stuff :)

We can have a deeper look when we have the capacity, but we cannot promise anything.

**Comment by vinzscam** [comment]
perhaps @Neemys can help out? 🤔

**Comment by MoChakmakchi** [comment]
I had the same issue, and it was a permissions issue on SonarQube.

Backstage showed the error `There is no project with key..`

So I called the API from postman and the actual response was:

```
{
    "errors": [
        {
            "msg": "Insufficient privileges"
        }
    ]
}
```

It worked when i changed the SonarQube token to the one of "user" type

**Comment by vinzscam** [comment]
@shrinathkrish have you tried the latest suggestion? @MoChakmakchi perhaps the error message in the plugin could be improved 😏

**Comment by vjanz** [comment]
> I had the same issue, and it was a permissions issue on SonarQube.
> 
> Backstage showed the error `There is no project with key..`
> 
> So I called the API from postman and the actual response was:
> 
> ```
> {
>     "errors": [
>         {
>             "msg": "Insufficient privileges"
>         }
>     ]
> }
> ```
> 
> It worked when i changed the SonarQube token to the one of "user" type

Didn't quite understand, can you give me more context on what you changed.

**Comment by m0un10** [comment]
Thank you @vjanz , I really appreciate you sharing this, at least for me, that was the issue.
Perhaps the plugin only supports the user-type token. When I changed from a `sqa_*` token to an `squ_*` token, it just worked.

Can I trouble you to ask how you got the extra debugging information? That's what I wanted (printing the response from Sonarqube) but didn't find any easy way to do that and had to park it.

In any case, thanks again for sharing this! Made my day.

**Comment by MoChakmakchi** [comment]
> 
> Didn't quite understand, can you give me more context on what you changed?

@vjanz when you issue the SonarQube token, choose the one labeled "user":
<img width="1399" alt="image" src="https://github.com/backstage/backstage/assets/121301684/02ff6ba2-7b30-4eed-a3ef-53a6f2db109c">



> 
> Can I trouble you to ask how you got the extra debugging information? That's what I wanted (printing the response from Sonarqube) but didn't find any easy way to do that and had to park it.
> 

I have [mitmproxy](https://mitmproxy.org/) enabled on my local env, which shows outbound API requests. I copied the request to postman to get the SQ response.

**Comment by vjanz** [comment]
> > Didn't quite understand, can you give me more context on what you changed?
> 
> @vjanz when you issue the SonarQube token, choose the one labeled "user": <img alt="image" width="1399" src="https://user-images.githubusercontent.com/121301684/284441979-02ff6ba2-7b30-4eed-a3ef-53a6f2db109c.png">
> 
> > Can I trouble you to ask how you got the extra debugging information? That's what I wanted (printing the response from Sonarqube) but didn't find any easy way to do that and had to park it.
> 
> @m0un10 I have [mitmproxy](https://mitmproxy.org/) enabled on my local env, which shows outbound API requests. I copied the request to postman to get the SQ response.

Awesome, definitely gonna try this and will let you know!

**Comment by jeremy-haakma** [comment]
> > Didn't quite understand, can you give me more context on what you changed?
> 
> @vjanz when you issue the SonarQube token, choose the one labeled "user": <img alt="image" width="1399" src="https://private-user-images.githubusercontent.com/121301684/284441979-02ff6ba2-7b30-4eed-a3ef-53a6f2db109c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODI4NzAsIm5iZiI6MTczMDc4MjU3MCwicGF0aCI6Ii8xMjEzMDE2ODQvMjg0NDQxOTc5LTAyZmY2YmEyLTdiMzAtNGVlZC1hM2VmLTUzYTZmMmRiMTA5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQwNDU2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTAzMTk0MTQwNDE0ZjA4OGNmYzA1NzQ0ZDAxZjA5OTVjNzFmNWYxMDY4OWEyNGRiN2Q4ZWIwY2ZmMjliNTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MDtfRUy6kz5v0V6qVvJ_4czlkiodokpddOL5dOY3WHg">
> 
> > Can I trouble you to ask how you got the extra debugging information? That's what I wanted (printing the response from Sonarqube) but didn't find any easy way to do that and had to park it.
> 
> @m0un10 I have [mitmproxy](https://mitmproxy.org/) enabled on my local env, which shows outbound API requests. I copied the request to postman to get the SQ response.

I'm having the same issue. I am using SonarCloud, and there doesn't seem to be an option to select a "type" when creating an access token.

**Comment by m0un10** [comment]
@jeremy-haakma what version of Sonarqube? Maybe post a screenshot of what you see

**Comment by jeremy-haakma** [comment]
@m0un10 As I said I'm using sonarcloud.io, not SonarQube. In SonarCloud, creating a token looks like this:
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/bbd208b6-c18d-4a25-9d97-c0cb1518bd59">

**Comment by LeBaronDeCharlus** [comment]
Hi @jeremy-haakma 

It should work if your current user has enough rights to get info.

For example on my own (SonarCloud too) I can reach infos through my current User token : 
```shell
curl -s --header 'Authorization: Bearer ******' 'https://sonarcloud.io/api/measures/component?metricKeys=ncloc%2Ccode_smells%2Ccomplexity&component=mysuperproject' | jq

{
  "component": {
    "id": "AZL9SETRNU-esx",
    "key": "myorg_mysuperproject",
    "name": "mysuperproject",
    "qualifier": "TRK",
    "measures": [
      {
        "metric": "complexity",
        "value": "44"
      },
      {
        "metric": "code_smells",
        "value": "10",
        "bestValue": false
      },
      {
        "metric": "ncloc",
        "value": "2159"
      }
    ]
  }
}
```

**Comment by LeBaronDeCharlus** [comment]
I've found a way to make it works.

In fact, there is a key/value missing in `app-config.yaml` which is `instanceKey`.

From the code we can see in `router.test.ts`
```
it('query default instance when instanceKey not provided', async () => {
      getBaseUrlMock.mockReturnValue({ baseUrl: DUMMY_INSTANCE_URL });
      const response = await request(app).get('/instanceUrl').send();
      expect(getBaseUrlMock).toHaveBeenCalledTimes(1);
      expect(getBaseUrlMock).toHaveBeenCalledWith({
        instanceName: undefined,
      });
      expect(response.status).toEqual(200);
      expect(response.body).toEqual({ instanceUrl: DUMMY_INSTANCE_URL });
    });
```

That helped me to see there is a fallback on default instance which is localhost if not provided, which is of course not the case because I use sonarcloud.io.

By updating my config like bellow it works : 
```yaml
sonarqube:
  name: myName
  instanceKey: myInstance
  baseUrl: https://sonarcloud.io
  apiKey: *************************
```

I've made a PR to update README here : https://github.com/backstage/community-plugins/pull/2026
