### ISSUE TITLE
🐛 Bug Report: cannot access owner page if the name contains # character

### ISSUE THREAD

**Issue by ypetrych** [backstage/backstage#19543]
### 📜 Description

Navigation to the page of the owner with # character in name results in broken page. It happens because request to BE is sent with part of owner name (the part before #)

### 👍 Expected behavior

It should be possible to view the page with route group/team-name-part1#team-name-part2. Request to BE should be catalog/entities/by-name/group/default/team-name-part1#team-name-part2

### 👎 Actual Behavior with Screenshots

The page with route group/team-name-part1#team-name-part2 has an error.

This happens because not correct request is sent to BE: 
catalog/entities/by-name/group/default/team-name-part1 
(#team-name-part2 is cut)

<img width="1725" alt="image" src="https://github.com/backstage/backstage/assets/36443694/912864e3-8403-45e3-a88e-eb3b7973e100">

### 👟 Reproduction steps

1. Have some owner with # in name, e.g. team-name-part1#team-name-part2
2. Click to open it in catalog
3. Page with route group/team-name-part1#team-name-part2 has an error.

Not correct request is sent to BE: 
catalog/entities/by-name/group/default/team-name-part1 
(#team-name-part2 is cut)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by fedy97** [comment]
are you sure you want to use the fragment identifier? the fragment identifier won't be included in the request because it's meant for client-side navigation within the webpage. Have you considered using another separator for example `-`?

**Comment by ypetrych** [comment]
@fedy97 We have pretty large company where we started the integration with Backstage. We already have some teams with # and it'll be complicated to change their titles. Maybe having the urls encoded will resolve this issue?

**Comment by vinzscam** [comment]
make sense @ypetrych, let me check whether this is something doable

**Comment by ypetrych** [comment]
> make sense @ypetrych, let me check whether this is something doable

hi @vinzscam do you have any updates on it? thank you

**Comment by fru2zzy** [comment]
any updates on this? i have the same problem

**Comment by vinzscam** [comment]
Closed by #19575
