### ISSUE TITLE
🚀 Feature: Horizontally Scaling the catalog

### ISSUE THREAD

**Issue by davjhan-doordash** [backstage/backstage#19559]
### 🔖 Feature description

Hi! It's David from Doordash. I have some questions on behalf of my team to the Backstage team on how you recommend we support 2 simultaneous goals.

1. **Goal 1: Horizontally scale Backstage.** We would like to have more than 2+ instances of the Backstage Backend running at all times for seamless green/blue deployments, better reliability, and the assurance that we can always take on more scale by spinning up more machines.

2. **Goal 2: Support Write operations on catalog entities via the UI**. We would like to support Upserts to catalog data from our backstage app itself.

So far, as we understand it Backstage's Catalog is not built to be horizontally scaled. This is because:

1. After all entities have been processed, entities live in the Backstage backend's in-memory cache. Therefore, different compute nodes of Backstage Backend will not be reading from the same source. While Backstage supports using Redis to share a cache *Between Entity Processors*, the final processed entities still live in an in-memory cache (that cannot be configured).

2. For as long as each compute node running a Backstage Catalog backend has its own in-memory cache, there will be cache invalidation issues after we upsert an entity.

Example:
```
1. Backstage FE App makes a request to update the name of an entity.
2. The request is handled by Backstage Backend instance A. This backend forwards the request to our backing CRUD service. It invalidates the cached entity in it's its in-memory catalog cache.
3. Backstage FE App makes a read request to the changed entity, but the request gets routed to Backstage Backend instance B, which shows the old name.
```

# Question

1. Will the Backstage catalog plugin expose a way to use a Redis cache to hold entities?
2. Has Spotify or other advanced Backstage users experienced this problem?

Thanks.

### 🎤 Context

See Feature Description above.

### Architecture

```

 ┌─────────────────┐     ┌─────┐     ┌────────────────┐       ┌───────────────┐
 │                 ├─────►     ├─────►                ├───────►               │
 │ Backstage React │     │     │     │ Backstage node │       │  Entity CRUD  │
 │     App         │     │     │     │   Backend 1    │ ┌─────►    Service    │
 │                 │     │     │     │                │ │     │               │
 └─────────────────┘     │     │     └────────────────┘ │     └───────────────┘
                         │     │                        │
                         │     │     ┌────────────────┐ │
                         │     │     │                │ │
                         │ LB  ├─────► Backstage node ├─┘
                         │     │     │   Backend 2    │
                         │     │     │                │
                         │     │     └────────────────┘
                         │     │
                         │     │     ┌────────────────┐
                         │     │     │      ...       │
                         │     │     │                │
                         └─────┘     └────────────────┘
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Let me wind back a couple of assumptions first 😅 The catalog IS horizontally scalable. It stores the result in the database which it then also uses for the read API. The work of processing entities is also scaled out across the available nodes. There are a few more details about options and constraints in the [deployment scaling docs](https://backstage.io/docs/deployment/scaling).

> 1. Will the Backstage catalog plugin expose a way to use a Redis cache to hold entities?

The cache does not hold any entities, but depending on the setup it may hold cache data that helps speed up the catalog processing. You can read more about the different available options and how to configure them [here](https://backstage.io/docs/overview/architecture-overview#cache).

> 2. Has Spotify or other advanced Backstage users experienced this problem?

For this I'm assuming you're talking about an Upsert API, otherwise it's covered above 😁

Early on we used to have an API for mutating entities directly, but didn't like that approach and have since removed it. It is however possible to implement using a separate `EntityProvider` with it's own Upsert API and storage, more on that [here](https://backstage.io/docs/features/software-catalog/external-integrations#custom-entity-providers).

**Comment by davjhan-doordash** [comment]
Thanks Rugvip!

You were right, the catalog *does* have ready made support to plug in a PSQL database! This is great news! I checked our app, and it looks like we're still using the SQLite client, which is why it's acting as a per-compute-node datasource. But this looks like a trivial change.

Thanks for the correction.

**Comment by sevedkim** [comment]
Hi David! I'm Seve a PM on Backstage. I wanted to ask if you or someone from your team would be willing to talk through your Backstage experience at Doordash? I'd be very interested to learn more from you all!

Feel free to [book time on my calendar](https://calendar.app.google/1G8Z6Z2QjuJrq7f4A) or reach out to me via email (sevek@spotify.com)

**Comment by Rugvip** [comment]
Going to close this as I think the original issue has been resolves. Let us know if we missed anything, and don't hesitate to open a new issue for other discussions!

**Comment by 0xts** [comment]
> The work of processing entities is also scaled out across the available nodes.

@Rugvip I had a doubt that I wanted to clear in regards to your quoted statement. The `DefaultCatalogProcessingEngine` [uses](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/processing/DefaultCatalogProcessingEngine.ts#L144) `DefaultProcessingDatabase` to get the entities to process, and by the [looks](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/database/DefaultProcessingDatabase.ts#L202-267) of it, it just fetches the rows that its looking to process without any locking. Wouldn't other catalog deployment might process the same data if the its promise gets resolved between the `select` & the `update` query of `getProcessableEntities`? Or am I missing something?

EDIT: All I'm trying to understand is if there'll be duplicate work across catalog service deployments.

**Comment by Rugvip** [comment]
@0xts the key bit is [this part](https://github.com/backstage/backstage/blob/9e88165368eafc6744b8c41c9912260e853ec11b/plugins/catalog-backend/src/database/DefaultProcessingDatabase.ts#L219-L224), which ends up generating a `SELECT ... FOR UPDATE SKIP LOCKED` statement that is [very good at scaling workloads horizontally](https://www.inferable.ai/blog/posts/postgres-skip-locked).

**Comment by 0xts** [comment]
@Rugvip The lock works in purview of a transaction, so, it's only applicable for the `itemsQuery`, as soon as that's executed, the rows can be fetched again (unless the update query runs immediately of course). It should all happen in a single transaction, and it seems that it isn't (unless I'm missing something and my understanding of how `knex` works is incorrect).
