### ISSUE TITLE
🐛 Bug Report: In 1.17.4, calls to CatalogApi.queryEntities results in 400 (Invalid fullTextFilterFields, not a string)

### ISSUE THREAD

**Issue by jslott2sigma** [backstage/backstage#19557]
### 📜 Description

This related to Issue #19499 where after upgrading to 1.17.4, I get the following error:
```
{
    "error": {
        "name": "InputError",
        "message": "Invalid fullTextFilterFields, not a string",
        "stack": "InputError: Invalid fullTextFilterFields, not a string\n <stack trace omitted>
    },
    "request": {
        "method": "GET",
        "url": "/entities/by-query?filter=kind=Group&limit=20&orderField=metadata.name,asc&fullTextFilterFields=metadata.name,kind,spec.profile.displayname,metadata.title"
    },
    "response": {
        "statusCode": 400
    }
}
```
The client call is:
```
            const response = await catalogApi.queryEntities({
                fullTextFilter: {
                    term: initialRequest.text || '',
                    fields: ['metadata.name', 'kind', 'spec.profile.displayname', 'metadata.title'],
                },
                filter: { kind },
                orderFields: [{ field: 'metadata.name', order: 'asc' }],
                limit,
            });
```

### 👍 Expected behavior

API call should return 200

### 👎 Actual Behavior with Screenshots

API call returns 400

### 👟 Reproduction steps

Invoke the code above from the client

### 🖥️ Your Environment

node: v18.14.2
backstage: 1.17.4
Dependencies:
    @backstage/app-defaults: 1.4.2
    @backstage/backend-app-api: 0.5.2
    @backstage/backend-common: 0.19.4
    @backstage/backend-dev-utils: 0.1.1
    @backstage/backend-openapi-utils: 0.0.3
    @backstage/backend-plugin-api: 0.6.2
    @backstage/backend-tasks: 0.5.7
    @backstage/catalog-client: 1.4.3
    @backstage/catalog-model: 1.4.1
    @backstage/cli-common: 0.1.12
    @backstage/cli-node: 0.1.3
    @backstage/cli: 0.22.12
    @backstage/config-loader: 1.4.0
    @backstage/config: 1.0.8
    @backstage/core-app-api: 1.9.1
    @backstage/core-components: 0.13.4
    @backstage/core-plugin-api: 1.5.3
    @backstage/dev-utils: 1.0.20
    @backstage/errors: 1.2.1
    @backstage/eslint-plugin: 0.1.3
    @backstage/integration-aws-node: 0.1.5
    @backstage/integration-react: 1.1.18
    @backstage/integration: 1.6.2
    @backstage/plugin-adr-backend: 0.3.8
    @backstage/plugin-adr-common: 0.2.14
    @backstage/plugin-adr: 0.6.6
    @backstage/plugin-api-docs: 0.9.10
    @backstage/plugin-app-backend: 0.3.50
    @backstage/plugin-app-node: 0.1.2
    @backstage/plugin-auth-backend: 0.18.8
    @backstage/plugin-auth-node: 0.2.19
    @backstage/plugin-catalog-backend-module-github: 0.3.6
    @backstage/plugin-catalog-backend-module-gitlab: 0.2.6
    @backstage/plugin-catalog-backend-module-unprocessed: 0.2.2
    @backstage/plugin-catalog-backend: 1.12.3
    @backstage/plugin-catalog-common: 1.0.15
    @backstage/plugin-catalog-graph: 0.2.35
    @backstage/plugin-catalog-import: 0.9.13
    @backstage/plugin-catalog-node: 1.4.3
    @backstage/plugin-catalog-react: 1.8.3
    @backstage/plugin-catalog-unprocessed-entities: 0.1.2
    @backstage/plugin-catalog: 1.12.4
    @backstage/plugin-devtools-backend: 0.1.5
    @backstage/plugin-devtools-common: 0.1.3
    @backstage/plugin-devtools: 0.1.3
    @backstage/plugin-events-node: 0.2.11
    @backstage/plugin-github-actions: 0.6.4
    @backstage/plugin-home-react: 0.1.2
    @backstage/plugin-home: 0.5.7
    @backstage/plugin-org: 0.6.13
    @backstage/plugin-permission-common: 0.7.7
    @backstage/plugin-permission-node: 0.7.13
    @backstage/plugin-permission-react: 0.4.14
    @backstage/plugin-proxy-backend: 0.3.2
    @backstage/plugin-scaffolder-backend: 1.16.4
    @backstage/plugin-scaffolder-common: 1.4.0
    @backstage/plugin-scaffolder-node: 0.2.2
    @backstage/plugin-scaffolder-react: 1.5.4
    @backstage/plugin-scaffolder: 1.14.4
    @backstage/plugin-search-backend-module-catalog: 0.1.6
    @backstage/plugin-search-backend-module-pg: 0.5.11
    @backstage/plugin-search-backend-module-techdocs: 0.1.6
    @backstage/plugin-search-backend-node: 1.2.6
    @backstage/plugin-search-backend: 1.4.2
    @backstage/plugin-search-common: 1.2.5
    @backstage/plugin-search-react: 1.6.4
    @backstage/plugin-search: 1.3.6
    @backstage/plugin-tech-insights-backend-module-jsonfc: 0.1.34
    @backstage/plugin-tech-insights-backend: 0.5.16
    @backstage/plugin-tech-insights-common: 0.2.11
    @backstage/plugin-tech-insights-node: 0.4.8
    @backstage/plugin-tech-insights: 0.3.15
    @backstage/plugin-tech-radar: 0.6.7
    @backstage/plugin-techdocs-backend: 1.6.7
    @backstage/plugin-techdocs-module-addons-contrib: 1.0.18
    @backstage/plugin-techdocs-node: 1.7.6
    @backstage/plugin-techdocs-react: 1.1.9
    @backstage/plugin-techdocs: 1.6.8
    @backstage/plugin-user-settings: 0.7.8
    @backstage/release-manifests: 0.0.9
    @backstage/test-utils: 1.4.2
    @backstage/theme: 0.4.1
    @backstage/types: 1.1.0
    @backstage/version-bridge: 1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
Thanks for reporting this @jslott2sigma 🙏
Fix is coming in #19572
