### ISSUE TITLE
🐛 Bug Report: Github Enterprise Authentication: Github App

### ISSUE THREAD

**Issue by Lowballs** [backstage/backstage#19562]
### 📜 Description

We have Backstage running in an Enterprise environment and are going through a migration of one instance of Backstage running in Kubernetes and pulling information from github.com, to another running in Kubernetes and pulling information from internally hosted Github Enterprise.

I am relatively new to Backstage so I might be missing something in the codebase. I was unable to find in the documentation how Backstage treats Github App installations with Enterprise, based on Githubs own documentation: https://docs.github.com/en/enterprise-cloud@latest/apps/creating-github-apps/authenticating-with-a-github-app

We have configured discovery following the documentation and it works well on startup of a pod:
https://backstage.io/docs/integrations/github/discovery#configuration

However, when the discovery processor runs on the specific timing we have set, authentication to our GHE instance fails when using a Github App. I have tried multiple timings to account for Github token expiry with no success. 

### 👍 Expected behavior

The behaviour above and below may be expected, but I'm not entirely sure so am asking for assistance. If I am able to understand something that may be missed in the codebase, a configuration for the [entityProvider](https://backstage.io/docs/integrations/github/discovery) perhaps, or the like, then that would be great.

We have configured both the   GithubOrgReaderProcessor and GithubEntityProvider at present.

### 👎 Actual Behavior with Screenshots

There are two things I have noticed in some testing I've performed between my local environment using a PAT for both github.com and GHE vs a Github App:

1. Upon starting Backstage when using a PAT it will verify auth successful to both Githubs I see the following:

backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=github.com,authed=true},github{host=**enterpriseurl,authed=true},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{} 

I've redacted the enterprise url, but you get the idea. I know the URL processor is different, but wondered how this works with GH Apps as both of these always appear as false when using a Github APP, the authentication issue also doesn't occur with a PAT.

3. When the discovery processor time rolls around I see the following in the logs when using a GH App:

catalog error github-provider:providerId-Enterprise refresh failed This endpoint requires you to be authenticated. type=plugin target=github-provider:providerId-Enterprise class=GithubEntityProvider taskId=github-provider:providerId-Enterprise:refresh taskInstanceId=06615473-b253-4aac-8a08-7dcf86fdc7d0 name=HttpError status=401 response=[object Object] request=[object Object] stack=HttpError: This endpoint requires you to be authenticated.
    at /app/node_modules/@octokit/request/dist-node/index.js:122:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async queryWithPaging (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-41bd0d1e.cjs.js:867:22)
    at async getOrganizationRepositories (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-41bd0d1e.cjs.js:824:24)
    at async GithubEntityProvider.findCatalogFiles (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-41bd0d1e.cjs.js:1138:54)
    at async GithubEntityProvider.refresh (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-41bd0d1e.cjs.js:1109:21)
    at async TaskWorker.fn (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-41bd0d1e.cjs.js:1097:13)
    at async TaskWorker.runOnce (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:360:7)
    at async /app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:308:31

### 👟 Reproduction steps

Delete active pods and have new ones spawn in their place using PAT and Github App.

### 📃 Provide the context for the Bug.

catalog error github-provider:providerId-Enterprise refresh failed This endpoint requires you to be authenticated. type=plugin target=github-provider:providerId-Enterprise class=GithubEntityProvider taskId=github-provider:providerId-Enterprise:refresh taskInstanceId=06615473-b253-4aac-8a08-7dcf86fdc7d0 name=HttpError status=401 response=[object Object] request=[object Object] stack=HttpError: This endpoint requires you to be authenticated.
    at /app/node_modules/@octokit/request/dist-node/index.js:122:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async queryWithPaging (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-41bd0d1e.cjs.js:867:22)
    at async getOrganizationRepositories (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-41bd0d1e.cjs.js:824:24)
    at async GithubEntityProvider.findCatalogFiles (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-41bd0d1e.cjs.js:1138:54)
    at async GithubEntityProvider.refresh (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-41bd0d1e.cjs.js:1109:21)
    at async TaskWorker.fn (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/cjs/GithubEntityProvider-41bd0d1e.cjs.js:1097:13)
    at async TaskWorker.runOnce (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:360:7)
    at async /app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:308:31

### 🖥️ Your Environment

OS:   Darwin 22.6.0 - darwin/arm64
node: v16.16.0
yarn: 1.22.19
cli:  0.22.12 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                               1.4.0
  @backstage/backend-app-api                            0.4.4
  @backstage/backend-common                             0.19.0
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.3
  @backstage/backend-tasks                              0.5.3
  @backstage/backend-test-utils                         0.1.38
  @backstage/catalog-client                             1.4.2
  @backstage/catalog-model                              1.4.0
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.1
  @backstage/cli                                        0.22.8
  @backstage/config-loader                              1.3.1
  @backstage/config                                     1.0.8
  @backstage/core-app-api                               1.8.1
  @backstage/core-components                            0.11.2, 0.13.2
  @backstage/core-plugin-api                            1.5.2
  @backstage/dev-utils                                  1.0.16
  @backstage/errors                                     1.2.0
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.4
  @backstage/integration-react                          1.1.14
  @backstage/integration                                1.5.0
  @backstage/plugin-api-docs                            0.9.5
  @backstage/plugin-app-backend                         0.3.46
  @backstage/plugin-auth-backend                        0.18.4
  @backstage/plugin-auth-node                           0.2.15
  @backstage/plugin-badges-backend                      0.2.1
  @backstage/plugin-badges                              0.2.43
  @backstage/plugin-bazaar-backend                      0.2.9
  @backstage/plugin-bazaar                              0.2.10
  @backstage/plugin-catalog-backend-module-github       0.3.1
  @backstage/plugin-catalog-backend                     1.10.0
  @backstage/plugin-catalog-common                      1.0.14
  @backstage/plugin-catalog-graph                       0.2.31
  @backstage/plugin-catalog-import                      0.9.9
  @backstage/plugin-catalog-node                        1.3.7
  @backstage/plugin-catalog-react                       1.7.0
  @backstage/plugin-catalog                             1.11.2
  @backstage/plugin-cost-insights-common                0.1.1
  @backstage/plugin-cost-insights                       0.12.8
  @backstage/plugin-devtools-backend                    0.1.1
  @backstage/plugin-devtools-common                     0.1.1
  @backstage/plugin-devtools                            0.1.1
  @backstage/plugin-entity-validation                   0.1.4
  @backstage/plugin-events-node                         0.2.7
  @backstage/plugin-explore-common                      0.0.1
  @backstage/plugin-explore-react                       0.0.29
  @backstage/plugin-explore                             0.4.5
  @backstage/plugin-github-actions                      0.6.0
  @backstage/plugin-github-issues                       0.2.8
  @backstage/plugin-github-pull-requests-board          0.1.13
  @backstage/plugin-home-react                          0.1.0
  @backstage/plugin-home                                0.5.3
  @backstage/plugin-kubernetes-backend                  0.11.1
  @backstage/plugin-kubernetes-common                   0.6.4
  @backstage/plugin-kubernetes                          0.9.2
  @backstage/plugin-org                                 0.6.9
  @backstage/plugin-permission-common                   0.7.6
  @backstage/plugin-permission-node                     0.7.9
  @backstage/plugin-permission-react                    0.4.13
  @backstage/plugin-proxy-backend                       0.2.40
  @backstage/plugin-scaffolder-backend                  1.15.0
  @backstage/plugin-scaffolder-common                   1.3.1
  @backstage/plugin-scaffolder-node                     0.1.4
  @backstage/plugin-scaffolder-react                    1.5.0
  @backstage/plugin-scaffolder                          1.14.0
  @backstage/plugin-search-backend-module-catalog       0.1.2
  @backstage/plugin-search-backend-module-elasticsearch 1.3.1
  @backstage/plugin-search-backend-module-pg            0.5.7
  @backstage/plugin-search-backend-module-techdocs      0.1.2
  @backstage/plugin-search-backend-node                 1.2.2
  @backstage/plugin-search-backend                      1.3.2
  @backstage/plugin-search-common                       1.2.4
  @backstage/plugin-search-react                        1.6.2
  @backstage/plugin-search                              1.3.2
  @backstage/plugin-shortcuts                           0.3.11
  @backstage/plugin-sonarqube-backend                   0.2.0
  @backstage/plugin-sonarqube-react                     0.1.6
  @backstage/plugin-sonarqube                           0.7.0
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.30
  @backstage/plugin-tech-insights-backend               0.5.12
  @backstage/plugin-tech-insights-common                0.2.11
  @backstage/plugin-tech-insights-node                  0.4.4
  @backstage/plugin-tech-insights                       0.3.11
  @backstage/plugin-tech-radar                          0.6.5
  @backstage/plugin-techdocs-addons-test-utils          1.0.15
  @backstage/plugin-techdocs-backend                    1.6.3
  @backstage/plugin-techdocs-module-addons-contrib      1.0.14
  @backstage/plugin-techdocs-node                       1.7.2
  @backstage/plugin-techdocs-react                      1.1.7
  @backstage/plugin-techdocs                            1.6.4
  @backstage/plugin-todo-backend                        0.1.43
  @backstage/plugin-todo                                0.2.21
  @backstage/plugin-user-settings                       0.7.4
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.4.0
  @backstage/theme                                      0.2.19, 0.3.0, 0.4.0
  @backstage/types                                      1.1.0
  @backstage/version-bridge                             1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
hey, could you share your `app-config.yaml`? It might be that some config related to ghe weren't specified.

**Comment by Lowballs** [comment]
@vinzscam - here it is. I've redacted some sensitive stuff, but hopefully it makes sense.

app:
  title: Backstage
  baseUrl: internalurl
  support:
    url: internalgheorg
    items:
      - title: Issues
        icon: github
        links:
          - url: internalgheorg
            title: GitHub Issues
      - title: Slack
        icon: chat
        links:
          - url: internalslack
            title: '#backstage'
      - title: Upload a catalog
        icon: catalog
        links:
          - url: /docs/default/Component/backstage/software-catalog/
            title: Onboarding

organization:
  name: org

backend:
  baseUrl: internalurl
  listen:
    port: 7000
  csp:
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
    img-src:
      - "'self'"
      - 'data:'
      - 'https://*.github.com'
      - 'https://*.githubusercontent.com'
      - 'https://github.com'
      - 'https://cdnjs.cloudflare.com'
      - 'https://img.shields.io'
      - 'https://progress-bar.dev'
      - 'https://via.placeholder.com'
  cors:
    origin: internalurl

  database:
    client: pg
    connection:
      host: 127.0.0.1
      port: 5432
      user: ${BACKSTAGE_POSTGRES_USER}
      password: ${BACKSTAGE_POSTGRES_PASSWORD}
    knexConfig:
      pool:
        min: 3
        max: 12
        acquireTimeoutMillis: 60000
        idleTimeoutMillis: 60000
    ensureExists: false

  cache:
    store: memory

integrations:
  googleGcs: {}
  github:
    - host: github.com
      apps:
        - appId: ${GHAPP_ID}
          clientId: ${GHAPP_CLIENT_ID}
          clientSecret: ${GHAPP_CLIENT_SECRET}
          privateKey:
            $file: '/path/to/pem'
          webhookSecret: ${GHAPP_WEBHOOK_SECRET}

    - host: internalgheorg
      apiBaseUrl: https://internalgheorg/api/v3
      rawBaseUrl: https://raw.internalgheorg
      apps:
        - appId: ${GITHUB_APP_ID_GHE_SYSL}
          clientId: ${GITHUB_APP_CLIENT_ID_GHE_SYSL}
          clientSecret: ${GITHUB_APP_CLIENT_SECRET_GHE_SYSL}
          privateKey:
            $file: '/path/to/pem'
          webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET_GHE_SYSL}

auth:
  environment: development
  providers:
    microsoft:
      development:
        clientId: ${BACKSTAGE_AZURE_APP_CLIENT_ID}
        clientSecret: ${BACKSTAGE_AZURE_APP_SECRET}
        tenantId: ${BACKSTAGE_AZURE_APP_TENANT_ID}
        
techdocs:
  requestUrl: internalurl
  storageUrl: internalurl
  builder: 'external'
  publisher:
    type: 'googleGcs'
    googleGcs:
      bucketName: 'internalbucket'

catalog:
  rules:
    - allow: [Component, System, API, Template, Location, Resource, User, Group, Domain]
  locations:
    - type: github-org
      target:  internalgheorg
      rules:
        - allow: [User, Group]
    - type: url
      target: internalgheorg
      rules: 
        - allow: [Component, System, API]

  providers:
    github:
      providerId-Enterprise:
        organization: 'gheorg'
        catalogPath: '/catalog-info.yaml'
        validateLocationsExist: true
      wildcardProviderId-Enterprise:
        organization: 'gheorg'
        catalogPath: '/backstage/**/*.yaml'
      backstageManagedEntitiesProviderId-Enterprise:
        organization: 'gheorg'
        catalogPath: '/entities/**/*.yaml'
        filters:
          branch: 'develop'
          repository: 'backstage'
      providerId:
        organization: 'ghcomorg'
        catalogPath: '/catalog-info.yaml'
        validateLocationsExist: true
      wildcardProviderId:
        organization: 'ghcomorg'
        catalogPath: '/backstage/**/*.yaml'
      backstageManagedEntitiesProviderId:
        organization: 'ghcomorg'
        catalogPath: '/entities/**/*.yaml'
        filters:
          branch: 'main'
          repository: 'backstage'

  backend:
    github:
      processFrequency: 45 # in minutes
      timeout: 40 # in minutes
    processingInterval: 300 # in seconds

search:
  techdocs:
    indexBuilder:
      frequency: 360
      timeout: 60
      initialDelay: 5
      scope: local

kubernetes:
  apiVersionOverrides:
    cronjobs: v1beta1
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: internal.url
          name: internalcluster
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: true

scaffolder:
  defaultAuthor:
    name: Backstage
    email: email.com

**Comment by Rugvip** [comment]
To debug the config itself you can use `yarn backstage-cli config:print --with-secrets` to print the loaded config including secrets. Or skip the `--with-secrets` flag to just make sure that the secrets are set, they'll be replaced with `<secret>`.

Something else you can try out is to create a test GitHub app towards public GitHub using `yarn backstage-cli create-github-app` and then double check that the config format matches on all the files.

**Comment by Lowballs** [comment]
I might close this for now as other priorities have come up, but I'll report back when I get a chance to do some thorough testing on this. Thanks for the tips guys.

**Comment by nitneuk** [comment]
Hi! I was facing the exact same issue (`refresh failed This endpoint requires you to be authenticated.`) when wanted to get org data from a GitHub App installed in the organization. The GitHub App has to be **installed** in the organization : 
![image (3)](https://github.com/backstage/backstage/assets/52654545/109ccf04-0c9a-4839-86cf-aaa53789d8d2)
(click install button) 
Beware, only an organization owner could do this action (being  an admin of the app is not sufficient)

**Comment by petercort** [comment]
Ran into the same issue, found that by adding the host to the catalog/providers/github section resolved the issue. Config looks something like this. 

`
integrations:
  github:
    - host: github.my-enterprise.com
       apiBaseUrl: https://github.my-enterprise.com/api/v3
       token: ${token} 

catalog: 
  providers:
    github:
      my-enterprise:
        organization: my-org
        catalogPath: './path/*'
        host: github.my-enterprise.com
`

**Comment by freben** [comment]
> The other issue I have is at one point in the catalog config there was a wildcard discovery entry. Even when I remove this and redeploy the pods with a new configmap, Backstage is still attempting to query those repositories. Is there something I can do to clean that up? The endpoints are not orphaned, they literally don't exist.
> 
> Do provider entries in the catalog-info.yaml persist in the pg database?

No but every discovered repo ended up becoming a `kind: Location` entity in the database, which the catalog dutifully keeps polling. They are most likely marked as orphaned by now if the original URL with the wildcard has been removed. I mean, you mention that "endpoints" are not orphaned, but I thought maybe there's a misunderstanding here.

You may want to try to list all your Location entries in the catalog and deleting the ones that point to those repos.

**Comment by Lowballs** [comment]
Thanks @freben - I had to delete them all manually. I found that when selecting 'is orphan' in the catalog section of Backstage yielded zero results and these entries have been there for some months.

What essentially occurred was another team who run a separate Backstage environment had a wildcard entry that looks like this: /backstage/**/*.yaml (we are migrating this env to a different space) and if you clicked a 'location' it would go to a 404 doesn't exist page in github.

This entry essentially from what I can tell, scan things like commit statuses, not to mention every branch in a repository, but ultimately, that path probably only exists in one or two of their 400+ repositories hitting the limits pretty quickly.

Is there a better way natively to remove these entries? how long do things technically take to be orphaned? Am I better off using the 'delete' orphan strategy to speed things up? I feel like because 'is orphan' didn't register these as orphaned after months, they're never going to be.

Finally, where would they be located in the database and if I clear them from there, does that clear them from Backstage  sorry not a DB guy :) If I could blow them away that way, it'd be much easier that clickops deleting of 400 odd entities.

Thanks for your help.

**Comment by freben** [comment]
> Thanks @freben - I had to delete them all manually. I found that when selecting 'is orphan' in the catalog section of Backstage yielded zero results and these entries have been there for some months.

That's odd - I wonder if something else kept them from showing up. Like another filter in the view leading to them not being included (did you make sure to select the Location kind, and All, for example?)

Did you double check the annotations of those locations, did they in fact have the orphaned annotation in them?

> What essentially occurred was another team who run a separate Backstage environment had a wildcard entry that looks like this: /backstage/**/*.yaml (we are migrating this env to a different space) and if you clicked a 'location' it would go to a 404 doesn't exist page in github.
> 
> This entry essentially from what I can tell, scan things like commit statuses, not to mention every branch in a repository, but ultimately, that path probably only exists in one or two of their 400+ repositories hitting the limits pretty quickly.

Oof, yeah that would do it. Should only visit the default branch though, not all of them.

> Is there a better way natively to remove these entries? how long do things technically take to be orphaned? Am I better off using the 'delete' orphan strategy to speed things up? I feel like because 'is orphan' didn't register these as orphaned after months, they're never going to be. We have two other higher environments I have to clean up so I'm wondering if I remove that entry from there, at what point will Backstage recognise them as orphaned? How many polling attempts are required.

I'd vouch for the delete strategy personally.

Their orphan status gets updated on each stitcher run. That is, every time the final shape of the entity gets regenerated for any reason at all (changed input data, changed set of relations to/from it, removed parents, etc).

> Finally, where would they be located in the database and if I clear them from there, does that clear them from Backstage sorry not a DB guy :) If I could blow them away that way, it'd be much easier that clickops deleting of 400 odd entities.

Yeah the delete strategy might help here.

All entities are rooted in the `refresh_state` table. Deleting entries there makes all associated data get deleted too. But you may want to do some more hand holding afterwards then, to make sure that everything gets re-stitched too afterwards. That's normally triggered by catalog code, so when you circumvent it you may need to clear out some other marker fields by hand IF you find that you need to (may not be needed)

**Comment by Lowballs** [comment]
@freben - awesome. Thanks so much for this. I'll close this one now and continue to plug away.
