### ISSUE TITLE
🐛 Bug Report: getGithubFileFetchUrl function does not work with branchnames containing slashes

### ISSUE THREAD

**Issue by mharrah** [backstage/backstage#19626]
### 📜 Description

The function getGithubFileFetchUrl in packages/integration/src/github/core.ts fails to determine the correct url to fetch if the branch name for a file contains a slash.   This seems to be due to a bug in the git-url-parse npm package (https://github.com/IonicaBizau/git-url-parse/issues/104), which can't tell whether a slash in a url is part of a branch name or a delimiter for a path.

### 👍 Expected behavior

The function should either work with branches containing slashes, or have a mechanism for escaping the slashes when a URL is passed in so the function can tell which part of the URL is the branch name and which part is the path/filename.

### 👎 Actual Behavior with Screenshots

The yaml fails to be processed, and has the following error:

```json
[
    {
        "name": "InputError",
        "message": "Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location https://github.com/MyOrg/MyRepo/blob/branchpart1/branchpart2/branchpart3/path/file.ext, NotFoundError: https://github.com/MyOrg/MyRepo/tree/branchpart1/branchpart2/branchpart3/path/file.ext could not be read as https://api.github.com/repos/MyOrg/MyRepo/contents/branchpart2/branchpart3/path/file.ext?ref=branchpart1, 404 Not Found",
        "cause": {
            "name": "Error",
            "message": "Placeholder $text could not read location https://github.com/MyOrg/MyRepo/blob/branchpart1/branchpart2/branchpart3/path/file.ext, NotFoundError: https://github.com/MyOrg/MyRepo/tree/branchpart1/branchpart2/branchpart3/path/file.ext could not be read as https://api.github.com/repos/MyOrg/MyRepo/contents/branchpart2/branchpart3/path/file.ext?ref=branchpart1, 404 Not Found",
            "stack": "Error: Placeholder $text could not read location https://github.com/MyOrg/MyRepo/blob/branchpart1/branchpart2/branchpart3/path/file.ext, NotFoundError: https://github.com/MyOrg/MyRepo/tree/branchpart1/branchpart2/branchpart3/path/file.ext could not be read as https://api.github.com/repos/MyOrg/MyRepo/contents/branchpart2/branchpart3/path/file.ext?ref=branchpart1, 404 Not Found\n    at readTextLocation (/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-21da853f.cjs.js:587:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async textPlaceholderResolver (/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-21da853f.cjs.js:577:28)\n    at async process (/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-21da853f.cjs.js:525:9)\n    at async Promise.all (index 3)\n    at async process (/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-21da853f.cjs.js:500:25)\n    at async Promise.all (index 3)\n    at async process (/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-21da853f.cjs.js:500:25)\n    at async PlaceholderProcessor.preProcessEntity (/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-21da853f.cjs.js:536:22)\n    at async DefaultCatalogProcessingOrchestrator.runPreProcessStep (/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-21da853f.cjs.js:2811:17)\n    at async DefaultCatalogProcessingOrchestrator.processSingleEntity (/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-21da853f.cjs.js:2766:16)\n    at async processTask (/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-21da853f.cjs.js:1628:26)"
        }
    }
]
```

### 👟 Reproduction steps

Create a branch on a repo in GitHub, with slashes in the name (such as "feature/newFeature" or "legacy/production/releases" or whatever.  In that branch add a file (contents don't matter) named 'file.ext' to the repo that the GitHubEntityProvider will find and attempt to process from a $text item. 

Back in the default branch of the repo, create a yaml file (for the GitHubEntityProvider to find) referencing the "file.ext", in the "path" directory of the "branchpart1/branchpart2/branchpart3" branch of the MyOrg/MyRepo repo in GitHub:

```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-api-entity
  description: The best API in the universe
spec:
  type: openapi
  owner: my-team
  definition:
    $text: https://github.com/MyOrg/MyRepo/blob/branchpart1/branchpart2/branchpart3/path/file.ext
```

The entity cannot be read into the catalog properly because the URL for the $text entry is converted (by the function) to
`https://api.github.com/repos/MyOrg/MyRepo/contents/branchpart2/branchpart3/path/file.ext?ref=branchpart1`
(which returns a 404).  The URL should actually be 
`https://api.github.com/repos/MyOrg/MyRepo/contents/path/file.ext?ref=branchpart1/branchpart2/branchpart3`

### 📃 Provide the context for the Bug.

This is preventing us from registering some of our material, which lives in a different branch than the default repo and which contains slashes in the branch name.  It appears our only way to resolve (at present) is to move or copy the referenced file to a different location in the same branch as the yaml file referencing it.

### 🖥️ Your Environment

This is using Backstage 1.16.0.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by camilaibs** [comment]
This is duplicated with this #2815 .
