### ISSUE TITLE
🐛 Bug Report: Newrelic plugin's page does not sort all columns correctly

### ISSUE THREAD

**Issue by wss-rbunning** [backstage/backstage#19621]
### 📜 Description

With the newrelic plugin's page, some of the columns in the table appear to be sorted alphabetically rather than by numeric value.

For instance, the responseTime column:
![image](https://github.com/backstage/backstage/assets/129326788/0ea0e047-5617-40d6-8ecb-50b70b1784c9)

This is likely because when setting up the table, the numeric values are interpolated into a string to add on the units (ms, rpm, %):
https://github.com/backstage/backstage/blob/49b2ea4cf8e5224aaa6c0335e3b0fb308cb710c1/plugins/newrelic/src/components/NewRelicFetchComponent/NewRelicFetchComponent.tsx#L34-L62

### 👍 Expected behavior

All columns showing numeric values should be sorted by the numeric value.

### 👎 Actual Behavior with Screenshots

Certain numeric columns that have units in the row sort alphabetically and not numerically. This leads to incorrect sorting.

![image](https://github.com/backstage/backstage/assets/129326788/0ea0e047-5617-40d6-8ecb-50b70b1784c9)

### 👟 Reproduction steps

- Setup the newrelic plugin [according to the instructions](https://github.com/backstage/backstage/tree/master/plugins/newrelic).
- Go to the newrelic page and click the columns that have units suffixed (ms, rpm, %) to sort them. The sorting is not correct.

### 🖥️ Your Environment

OS:   Windows_NT 10.0.19045 - win32/x64
node: v18.16.1
yarn: 1.22.19
cli:  0.22.9 (installed)
backstage:  1.16.0

Dependencies:
  @backstage/app-defaults                               1.4.1
  @backstage/backend-app-api                            0.4.5
  @backstage/backend-common                             0.18.5, 0.19.1
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.4
  @backstage/backend-tasks                              0.5.4
  @backstage/catalog-client                             1.4.3
  @backstage/catalog-model                              1.4.1
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.2
  @backstage/cli                                        0.22.9
  @backstage/config-loader                              1.3.2
  @backstage/config                                     1.0.8
  @backstage/core-app-api                               1.9.0, 1.9.1
  @backstage/core-components                            0.12.5, 0.13.3, 0.13.4
  @backstage/core-plugin-api                            1.5.3, 0.0.0
  @backstage/dev-utils                                  1.0.17
  @backstage/errors                                     1.2.1
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.5
  @backstage/integration-react                          1.1.15
  @backstage/integration                                1.5.1, 1.6.1, 1.6.2
  @backstage/plugin-adr-backend                         0.3.5
  @backstage/plugin-adr-common                          0.2.11
  @backstage/plugin-adr                                 0.6.3
  @backstage/plugin-api-docs                            0.9.6
  @backstage/plugin-app-backend                         0.3.47
  @backstage/plugin-auth-backend                        0.18.5
  @backstage/plugin-auth-node                           0.2.16
  @backstage/plugin-azure-devops-backend                0.3.26
  @backstage/plugin-azure-devops-common                 0.3.0
  @backstage/plugin-azure-devops                        0.3.2
  @backstage/plugin-catalog-backend-module-azure        0.1.18
  @backstage/plugin-catalog-backend                     1.11.0
  @backstage/plugin-catalog-common                      1.0.15
  @backstage/plugin-catalog-graph                       0.2.32
  @backstage/plugin-catalog-import                      0.9.10
  @backstage/plugin-catalog-node                        1.4.0
  @backstage/plugin-catalog-react                       1.8.0, 1.8.2, 1.8.3
  @backstage/plugin-catalog                             1.12.0
  @backstage/plugin-entity-feedback-backend             0.1.5
  @backstage/plugin-entity-feedback-common              0.1.1
  @backstage/plugin-entity-feedback                     0.2.3
  @backstage/plugin-entity-validation                   0.1.5
  @backstage/plugin-events-node                         0.2.8
  @backstage/plugin-github-actions                      0.6.1
  @backstage/plugin-home-react                          0.1.1
  @backstage/plugin-home                                0.5.4
  @backstage/plugin-linguist-backend                    0.3.1
  @backstage/plugin-linguist-common                     0.1.0
  @backstage/plugin-linguist                            0.1.5
  @backstage/plugin-microsoft-calendar                  0.1.5
  @backstage/plugin-newrelic-dashboard                  0.2.13
  @backstage/plugin-newrelic                            0.3.39
  @backstage/plugin-org                                 0.6.10
  @backstage/plugin-permission-backend                  0.5.22
  @backstage/plugin-permission-common                   0.7.7
  @backstage/plugin-permission-node                     0.7.10
  @backstage/plugin-permission-react                    0.4.14
  @backstage/plugin-proxy-backend                       0.2.41
  @backstage/plugin-scaffolder-backend                  1.15.1
  @backstage/plugin-scaffolder-common                   1.3.2
  @backstage/plugin-scaffolder-node                     0.1.5
  @backstage/plugin-scaffolder-react                    1.5.1
  @backstage/plugin-scaffolder                          1.14.1
  @backstage/plugin-search-backend-module-catalog       0.1.3
  @backstage/plugin-search-backend-module-pg            0.5.8
  @backstage/plugin-search-backend-module-techdocs      0.1.3
  @backstage/plugin-search-backend-node                 1.2.3
  @backstage/plugin-search-backend                      1.3.3
  @backstage/plugin-search-common                       1.2.5
  @backstage/plugin-search-react                        1.6.3
  @backstage/plugin-search                              1.3.3
  @backstage/plugin-sentry                              0.5.5
  @backstage/plugin-sonarqube-backend                   0.2.1
  @backstage/plugin-sonarqube-react                     0.1.7
  @backstage/plugin-sonarqube                           0.7.1
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.31
  @backstage/plugin-tech-insights-backend               0.5.13
  @backstage/plugin-tech-insights-common                0.2.11
  @backstage/plugin-tech-insights-node                  0.4.5
  @backstage/plugin-tech-insights                       0.3.12
  @backstage/plugin-tech-radar                          0.6.6
  @backstage/plugin-techdocs-backend                    1.6.4
  @backstage/plugin-techdocs-module-addons-contrib      1.0.15
  @backstage/plugin-techdocs-node                       1.7.3
  @backstage/plugin-techdocs-react                      1.1.8
  @backstage/plugin-techdocs                            1.6.5
  @backstage/plugin-user-settings                       0.7.5
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.4.1, 1.4.2
  @backstage/theme                                      0.2.19, 0.4.1
  @backstage/types                                      1.1.0
  @backstage/version-bridge                             1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by wss-rbunning** [comment]
What would be the preferred way to address this? Would it be okay if the units were pulled up into the column header and the values passed to the table for those columns are kept numeric? Or would we rather have the units still in the entries in the row?

**Comment by camilaibs** [comment]
Hi @wss-rbunning, we would want the table cells be numeric.

**Comment by joshgrime** [comment]
Hey, had a go at fixing this in [PR 19771](https://github.com/backstage/backstage/pull/19771/)

**Comment by vinzscam** [comment]
Closed by #19771
