### ISSUE TITLE
🚀 Feature: Transitive group memberships for LDAP backend plugin

### ISSUE THREAD

**Issue by lshwayne96** [backstage/backstage#19629]
### 🔖 Feature description

Plugin: https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-ldap
Add functionality to enable building of transitive group memberships; i.e. _if a user/group is a member of group A, and group A is a member of group B, then the user/group is a member of group B._

### 🎤 Context

To allow the use case where a user/group is considered to be a member of all its ancestor groups.

### ✌️ Possible Implementation

Currently there seems to be an existing function `buildMemberOf()` which performs the requested functionality: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-ldap/src/ldap/org.ts#L61
However, this function does not seem to be used within the plugin (other than in tests).

Would it be possible to add an additional option to toggle this functionality in `LdapOrgEntityProviderOptions`:
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-ldap/src/processors/LdapOrgEntityProvider.ts#L46
If the option is enabled, the function `resolveRelations()` could call `buildMemberOf()` after `buildOrgHierarchy()`:
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-ldap/src/ldap/read.ts#L350

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Could you elaborate a bit more on why you want this? If it is related to ownership I recommend that you look into defining a [custom sign-in resolver](https://backstage.io/docs/auth/identity-resolver/#custom-ownership-resolution) instead that provides the desired ownership entity references that the user should claim ownership though.

**Comment by lshwayne96** [comment]
Hi Rugvip, thanks for the reply.

For our case, it is not only related to ownership; one major use case among others is with regards to permissions, where all descendants of a group may be allowed to perform certain actions related to that group.

We figured that rather than providing similar custom logic for multiple such use cases, it would probably be easier to generate the transitive group membership relations which other plugins can make use of. 
(For example, in the case of ownership, the default ownership entity references generated by Backstage are based on the group membership relations of the user.)

**Comment by lshwayne96** [comment]
Hi Ben, I understand the concerns you have raised; I think for now we will maintain our own custom LDAP module to fit our needs. Thanks.

**Comment by winterji** [comment]
Hi, I'd also be interested in this. Would it be possible to implement it with the optional config value? Or could you at least point me towards to necessary tweak? Thanks.
