### ISSUE TITLE
🐛 Bug Report: EntityLayout.Route does not work with subroutes

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#19635]
### 📜 Description

When a component inside `EntityLayout.Route` has its own subroutes attached and when navigating to subroute, clicking the tab does not return to the original tab content. This leads to a problem that every subpage inside needs to have a separate back button to return the user to the root. 

### 👍 Expected behavior

When clicking a tab that is already active, it should redirect to the root page of the content in case the root points to a different location than the current one.

### 👎 Actual Behavior with Screenshots

Nothing happens

### 👟 Reproduction steps

1. Add Jenkins plugin according to instructions (https://github.com/backstage/backstage/blob/2c91a2bb60d44c6522f2818cc43a68b38422c54d/plugins/jenkins/README.md)
2. Add annotation to add a job for some entity and necessary UI changes to add the CI/CD entity layout route
3. Run Jenkins build so that it's visible in the Backstage
4. Click on the build in Backstage to go to the DetailedViewPage
5. Click the CI/CD tab again -> Nothing happens

### 📃 Provide the context for the Bug.

Router defined here: https://github.com/backstage/backstage/blob/2c91a2bb60d44c6522f2818cc43a68b38422c54d/plugins/jenkins/src/components/Router.tsx

### 🖥️ Your Environment

OS:   Darwin 22.6.0 - darwin/arm64
node: v16.20.1
yarn: 1.22.19
cli:  0.22.11 (installed)
backstage:  1.17.2

Dependencies:
  @backstage/app-defaults                                            1.4.2
  @backstage/backend-app-api                                         0.4.5, 0.5.1, 0.5.2
  @backstage/backend-common                                          0.17.0, 0.18.5, 0.19.3, 0.19.4
  @backstage/backend-dev-utils                                       0.1.1
  @backstage/backend-openapi-utils                                   0.0.3
  @backstage/backend-plugin-api                                      0.5.4, 0.6.1, 0.6.2
  @backstage/backend-tasks                                           0.5.6, 0.5.7
  @backstage/backend-test-utils                                      0.2.1
  @backstage/catalog-client                                          1.4.3
  @backstage/catalog-model                                           1.4.1
  @backstage/cli-common                                              0.1.12
  @backstage/cli-node                                                0.1.3
  @backstage/cli                                                     0.22.11
  @backstage/config-loader                                           1.4.0
  @backstage/config                                                  1.0.8
  @backstage/core-app-api                                            1.9.1
  @backstage/core-components                                         0.12.5, 0.13.4
  @backstage/core-plugin-api                                         1.5.3
  @backstage/dev-utils                                               1.0.19
  @backstage/errors                                                  1.2.1
  @backstage/eslint-plugin                                           0.1.3
  @backstage/integration-aws-node                                    0.1.5
  @backstage/integration-react                                       1.1.17
  @backstage/integration                                             1.6.1, 1.6.2
  @backstage/plugin-api-docs                                         0.9.9
  @backstage/plugin-app-backend                                      0.3.49
  @backstage/plugin-app-node                                         0.1.1
  @backstage/plugin-auth-backend                                     0.18.7
  @backstage/plugin-auth-node                                        0.2.18, 0.2.19
  @backstage/plugin-catalog-backend-module-aws                       0.2.4
  @backstage/plugin-catalog-backend-module-bitbucket-server          0.1.14
  @backstage/plugin-catalog-backend-module-msgraph                   0.5.8
  @backstage/plugin-catalog-backend                                  1.12.1
  @backstage/plugin-catalog-common                                   1.0.15
  @backstage/plugin-catalog-graph                                    0.2.34
  @backstage/plugin-catalog-node                                     1.4.2
  @backstage/plugin-catalog-react                                    1.8.2
  @backstage/plugin-catalog                                          1.12.3
  @backstage/plugin-devtools-backend                                 0.1.4
  @backstage/plugin-devtools-common                                  0.1.3
  @backstage/plugin-devtools                                         0.1.3
  @backstage/plugin-entity-feedback-backend                          0.1.7
  @backstage/plugin-entity-feedback-common                           0.1.2
  @backstage/plugin-entity-feedback                                  0.2.5
  @backstage/plugin-events-node                                      0.2.10
  @backstage/plugin-github-actions                                   0.6.3
  @backstage/plugin-home-react                                       0.1.2
  @backstage/plugin-home                                             0.5.6
  @backstage/plugin-jenkins-backend                                  0.2.4
  @backstage/plugin-jenkins-common                                   0.1.18
  @backstage/plugin-jenkins                                          0.8.4
  @backstage/plugin-kubernetes-common                                0.6.5
  @backstage/plugin-microsoft-calendar                               0.1.6
  @backstage/plugin-org                                              0.6.12
  @backstage/plugin-permission-backend                               0.5.24
  @backstage/plugin-permission-common                                0.7.7
  @backstage/plugin-permission-node                                  0.7.12, 0.7.13
  @backstage/plugin-permission-react                                 0.4.14
  @backstage/plugin-proxy-backend                                    0.3.1
  @backstage/plugin-scaffolder-backend-module-confluence-to-markdown 0.2.2
  @backstage/plugin-scaffolder-backend-module-cookiecutter           0.2.25
  @backstage/plugin-scaffolder-backend                               1.16.2
  @backstage/plugin-scaffolder-common                                1.4.0
  @backstage/plugin-scaffolder-node                                  0.2.1
  @backstage/plugin-scaffolder-react                                 1.5.3
  @backstage/plugin-scaffolder                                       1.14.3
  @backstage/plugin-search-backend-module-catalog                    0.1.5
  @backstage/plugin-search-backend-module-elasticsearch              1.3.4
  @backstage/plugin-search-backend-module-pg                         0.5.10
  @backstage/plugin-search-backend-module-techdocs                   0.1.5
  @backstage/plugin-search-backend-node                              1.2.5
  @backstage/plugin-search-backend                                   1.4.1
  @backstage/plugin-search-common                                    1.2.5
  @backstage/plugin-search-react                                     1.6.4
  @backstage/plugin-search                                           1.3.5
  @backstage/plugin-sonarqube-backend                                0.2.3
  @backstage/plugin-sonarqube-react                                  0.1.7
  @backstage/plugin-sonarqube                                        0.7.3
  @backstage/plugin-techdocs-backend                                 1.6.6
  @backstage/plugin-techdocs-module-addons-contrib                   1.0.17
  @backstage/plugin-techdocs-node                                    1.7.5
  @backstage/plugin-techdocs-react                                   1.1.9
  @backstage/plugin-techdocs                                         1.6.7
  @backstage/plugin-user-settings                                    0.7.7
  @backstage/release-manifests                                       0.0.9
  @backstage/test-utils                                              1.4.2
  @backstage/theme                                                   0.2.19, 0.4.1
  @backstage/types                                                   1.1.0
  @backstage/version-bridge                                          1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Yep that doesn't seem like desirable behavior, let's fix it! 😁 It seems like the tab change callback is only called when changing tab, I think the best fix here might be to call it any time a tab is clicked, even if it's already the main one? https://github.com/backstage/backstage/blob/0870577bd4ac6922ff999a0207c2aed71512d499/packages/core-components/src/components/TabbedLayout/RoutedTabs.tsx#L83

**Comment by drodil** [comment]
Yeah, that sounds like a good fix. Now we always have to have a back button if creating subviews inside the tabs and it's not very good for the UX.

**Comment by npiyush97** [comment]
@drodil @Rugvip help me understand what we want to achieve here with example.
Like if im on **todo** tab and click todo tab again onTabchange  does not run but header tab onchange runs.

**Comment by Rugvip** [comment]
Suggested the above fix in #20228
