### ISSUE TITLE
I wanted to make groups which is mentioned inside the NextScaffolderPage as dynamic reading from array.

### ISSUE THREAD

**Issue by Saiprasad2021** [backstage/backstage#19642]
### 🔖 Feature description

```tsx
<NextScaffolderPage
      groups={[
        {
          title: 'Recommended',
          filter: entity =>
            entity?.metadata?.tags?.includes('recommended') ?? false,
        },
      ]} />
```

i wanted to make groups object as dynamic by reading from array of string , and iterate each string and assign instead of title and entity comparison. how can i able to achieve it.

### 🎤 Context

```tsx
array = ['test', 'test two'];

<NextScaffolderPage
      groups={fetchTemplates()} />

fetchTempaltes(entity){
const template = [];
 array.foreach(item=>{
  template.push(  {
          title: item,
          filter: entity =>
            entity?.metadata?.tags?.includes(item) ?? false,
        },)
})
return template
}
```

something above .

### ✌️ Possible Implementation

i wanted to make somthing above please help me. how to make it done.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
In the alpha API you can replace the template list page via the `components.TemplateListPageComponent` prop. That should let you wrap up the default `TemplateListPage` component in one that first fetched the remote data in order the create the filters, and then renders the `TemplateListPage`.
