### ISSUE TITLE
🚀 CI Feature: Use uffizzi clusters for backstage's preview environments

### ISSUE THREAD

**Issue by waveywaves** [backstage/backstage#19655]
### 🔖 Feature description

Uffizzi now supports cluster creation and I would like to upgrade [backstage's existing preview workflow](https://github.com/backstage/backstage/blob/master/.github/workflows/uffizzi-preview.yaml) to support creating previews in uffizzi clusters. Instead of docker-compose we will be using kubernetes manifests to create a backstage deployment. This will also allow backstage developers to better test the kubernetes plugin and kubernetes related functionality.

More information in the articles/documentation below:
An overview of the support for virtual clusters
https://www.uffizzi.com/blog/introducing-uffizzi-virtual-clusters
How we will be implementing virtual cluster environment support for the backstage project
https://docs.uffizzi.com/virtual-cluster-environment/ 

### 🎤 Context

Create preview environments for backstage which are more versatile. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Interesting! My initial question would be whether we actually get access to the kubernetes API in a useful way if deploying in the cluster? Just because we're running in k8s doesn't necessarily mean we have access to it 😅

**Comment by waveywaves** [comment]
@Rugvip the developer who opens the PR and the admin of backstage project will be able to access the cluster via the CLI. You would be able to check backstage logs and debug on a cluster level as well.
