### ISSUE TITLE
🚀 Feature: extend usePermission hook to take an array of permissions

### ISSUE THREAD

**Issue by fedy97** [backstage/backstage#19650]
### 🔖 Feature description

Right now the front-end hook `usePermission` (plugins/permission-react/src/hooks/usePermission.ts) only takes in input a single permission.

### 🎤 Context

If I want to chain more permissions in AND/OR this hook must be called for each permission and this is not optimal. The idea is to implement a `usePermissions` hook or extend the current `usePermission` in order to take in input either a single permission or an array of permissions, with the possibility, in the array case, to specify if the conditions must be put in AND or OR.

A possible use case may be this one: for a specific entity, my user has both read and write permissions. Let's say I want to read the entity. In this case I just need either read or write permissions. but with the actual implementation I need to run twice the hook and put the 2 results in OR.

Right now we can only do this:

```
const viewPermission = usePermission({
    permission: entityView,
  }).allowed;

  const enabled =
    usePermission({
      permission: entityWrite,
    }).allowed || viewPermission;
```

I want to achieve something similar to this

```
const enabled =
    usePermissions(
      [{permission: entityWrite}, {permission: entityView}], 
      Operator.OR
    ).allowed;
```

### ✌️ Possible Implementation

Leverage the `permissionClient.authorize` (that already takes in input an array of permissions) and implement this extension by taking in input the array of permissions and passing it to the authorize method inside the extended hook. `permissionApi` must also be extended because right now it only takes one permission, and calls `permissionClient` by passing the single permission as array

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Hmm, wondering what the use-case for this actually is, I feel in many cases this should be solved on the handler end? Considering your example, I would expect the `entityView` permission to be enough, and really it would be an error in the implementation of the permission handler if you allow `entityWrite` but not `entityView`.

I'd also say that the typical way to handle the logic part of this would probably be with `anyOf`/`allOf` keys, for example:

```ts
usePermissions({ anyOf: [entityWrite, entityView] })
```

Leaving continued discussion to @backstage/discoverability-maintainers

**Comment by fedy97** [comment]
thanks for the reply @Rugvip 

> Hmm, wondering what the use-case for this actually is, I feel in many cases this should be solved on the handler end? Considering your example, I would expect the `entityView` permission to be enough, and really it would be an error in the implementation of the permission handler if you allow `entityWrite` but not `entityView`.
> 

you are right the example I gave is not a good one, but the point is that maybe for some actions I would need more than one permission to be checked.

> I'd also say that the typical way to handle the logic part of this would probably be with `anyOf`/`allOf` keys, for example:
> 
> ```ts
> usePermissions({ anyOf: [entityWrite, entityView] })
> ```
> 

in the first place it would be enough to have the possibility to pass an array of permissions threated as `allOf`.

The point is, I don't get why the method `authorize` defined in the interface `PermissionApi` on the frontend only accepts a single request object instead of an array of `EvaluatePermissionRequest`. I would extend it to be coherent with the  `authorize` method defined in the interface `PermissionEvaluator` on the backend, that in fact accepts an array of requests. Than the custom policy can use `anyOf` and `allOf` as you mentioned to make a conditional decision.
