### ISSUE TITLE
🐛 Bug Report: scaffolder "catalog:register" step fails to fetch component.yaml from github.com

### ISSUE THREAD

**Issue by ryanj** [backstage/backstage#19678]
### 📜 Description

The scaffolder `catalog:register` action fails to read the newly uploaded `component.yaml` from github following a successful `publish:github` action

### 👍 Expected behavior

Files that are uploaded using the `publish:github` action are normally available without any delay (available for use in the following `catalog:register` scaffolder action step)

### 👎 Actual Behavior with Screenshots

The scaffolder's `catalog:register` action fails to fetch the newly published `component.yaml` from github (404 error)

![image](https://github.com/backstage/backstage/assets/17562/01b61a7d-9db0-43c1-89ba-47e768435e5c)

<img width="1609" alt="Screenshot 2023-08-25 at 1 15 03 PM" src="https://github.com/backstage/backstage/assets/17562/ac06d494-f916-49cf-93fb-731f36d5706c">

### 👟 Reproduction steps

1. Set up backstage on Azure using GitHub and the following template: https://github.com/janus-idp/software-templates/blob/main/templates/github/spring-boot-backend/template.yaml
2. Use the template to create a new software component
3. The error should appear in the scaffolder output

### 📃 Provide the context for the Bug.

This bug was encountered by 100% of the users in a recent workshop.  We were able to reproduce the issue with 100% reliability on our backup cluster as well.  

We were able to successfully work around the issue by [adding a small delay before reading from Github](https://github.com/redhat-scholars/backstage-workshop/blob/master/scaffolder-templates/poi-map/template.yaml#L92-L96)

### 🖥️ Your Environment

I experienced this bug while using backstage in a "production" deployment on Azure in "eastus2"

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
I think I'd be good if we add a wait at the end of all publish/create/push actions where we poll the API to make sure that the repo or content we just created is ready to be used. That way any followup action won't need to worry about the repo or new repo contents potentially not existing yet.

Leaving this open for contributions
