### ISSUE TITLE
🚀 Feature: Scaffolder Component Creation as part of Entity Management

### ISSUE THREAD

**Issue by zhammer** [backstage/backstage#19676]
### 🔖 Feature description

We would like the scaffolder plugin to be the core pathway through which developers in our organization add resources to their existing applications. The flow we imagine would be something like this:

1. I visit the entity overview page for my application, "Users Service"
2. There is a `ScaffolderCard` or `ScaffolderContent` where I can browse through resource templates which I can apply to "Users Service".
    * For example, one may be a "New Postgres DB" template. This template would create a pull request in my "Users Service" repository that adds IaC code for the creation of a new Postgres DB.
3. When I click the "New Postgres DB" template,  the "entity" field is automatically populated with `component:users-service`.

The current scaffolder plugin misses a few key features that allows this to work. Specifically:
- There is no `Scaffolder(Card|Content)` publicly exposed from the plugin
- There is no way to autopopulate fields for a specific entity

### 🎤 Context

Creating pull requests is already a core feature of all the scaffolder scm integrations. Integrating the scaffolder plugin frontend with the entity overview page direclty presents a clear and intuitive experience to developers who can discover the extensions that can be added to their applications and seamlessly begin the process of adding them.

### ✌️ Possible Implementation

> There is no `Scaffolder(Card|Content)` publicly exposed from the plugin

At most, a new component for displaying available templates for an entity. Can use existing filter logic, e.g. templates filtered by `Kind: Resource` or `tags includes "pull_requests"`.

At least, pubilcly expose [TemplateList](https://github.com/backstage/backstage/blob/ac1ca7ce15d3ca079e9cfd85ec83b294b89268c3/plugins/scaffolder/src/components/TemplateList/TemplateList.tsx#L49-L56) so that developers can add it into a custom `ScaffolderContent` card.

> There is no way to autopopulate fields for a specific entity

One idea: autofill form fields based on query parameters in url, e.g. `?field_entity=component%2Fusers-service`. This would also require some updates the [href logic](https://github.com/backstage/backstage/blob/ac1ca7ce15d3ca079e9cfd85ec83b294b89268c3/plugins/scaffolder/src/components/TemplateCard/TemplateCard.tsx#L198C22-L198C22) in the `TemplateCard` (if this component is used in the entity overview page.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by zhammer** [comment]
In the discord I found a similar request: https://discord.com/channels/687207715902193673/923143744176418836/992254161720725575

**Comment by awanlin** [comment]
This is a cool idea, I think some of these things are actually in place just not the initial UI to view/discover related templates

Some foundational work I think has been done as part of this: https://github.com/backstage/backstage/issues/14706

Also, I would make sure that any thinking you do on this subject is based off the Scaffolder Next work documented here as that will soon be the default: https://backstage.io/docs/features/software-templates/testing-scaffolder-alpha

Some related Discord links:

- https://discord.com/channels/687207715902193673/1095329028010950666
- https://discord.com/channels/687207715902193673/1095393671874093096

**Comment by zhammer** [comment]
ah thank you. i guess @taras did follow up on his discord note. guess my searching didn't turn up everything. will take a look at the resources you shared.

**Comment by zhammer** [comment]
was able to get the following together. looks pretty good so far! signing off for the day, will update tomorrow:

```tsx
import { stringifyEntityRef } from '@backstage/catalog-model';
import { EntityKindFilter, EntityListProvider, useEntity, useEntityList } from '@backstage/plugin-catalog-react';
import { TemplateEntityV1beta3 } from '@backstage/plugin-scaffolder-common';
import { SecretsContextProvider } from '@backstage/plugin-scaffolder-react';
import { TemplateGroups } from '@backstage/plugin-scaffolder-react/alpha';
import { EmbeddedScaffolderWorkflow } from '@frontside/backstage-plugin-scaffolder-workflow';
import React, { PropsWithChildren, useCallback, useEffect, useState } from 'react';

const TemplateListProviderInner = (props: PropsWithChildren<{}>) => {
    const { updateFilters } = useEntityList();
    useEffect(() => {
        updateFilters({
            kind: new EntityKindFilter('template'),
        })
    }, [updateFilters]);

    return <>{props.children}</>
}


const TemplateListProvider = (props: PropsWithChildren<{}>) => {
    return <EntityListProvider><TemplateListProviderInner {...props} /></EntityListProvider>
}

export const EntityScaffolderContent = () => {
    const { entity } = useEntity();
    const [selectedTemplate, setSelectedTemplate] = useState<TemplateEntityV1beta3 | null>(null);
    const handleTemplateSelected = useCallback((template: TemplateEntityV1beta3) => {
        setSelectedTemplate(template);
    }, []);
    return (
        <SecretsContextProvider>
            <TemplateListProvider>
                {selectedTemplate ? (
                    <EmbeddedScaffolderWorkflow
                        namespace={selectedTemplate.metadata.namespace || 'default'}
                        templateName={selectedTemplate.metadata.name}
                        initialState={{ system: stringifyEntityRef(entity) }}
                        onError={(error: Error | undefined) => (
                            <h2>{error?.message ?? 'Houston we have a problem.'}</h2>
                        )}
                    />
                ) : (
                    <TemplateGroups
                        groups={[{
                            title: "Resources",
                            filter: (e) => e.spec.type.toLowerCase() === "resource",
                        }]}
                        onTemplateSelected={handleTemplateSelected}
                    />
                )}
            </TemplateListProvider>
        </SecretsContextProvider>
    )
}
```

**Comment by zhammer** [comment]
if i were to contribute something like this back to OS i'd also probably want to add some sort of callback prop to `Workflow` along the lines of `onBackFirstStep`, so that if i'm on the first step of the template workflow i can hit back and go back to the `<TemplateGroups/>` view

<img width="182" alt="Screen Shot 2023-08-31 at 3 37 54 PM" src="https://github.com/backstage/backstage/assets/6956487/07a75fd3-79bd-477d-ab8a-d402e900702c">
