### ISSUE TITLE
🐛 Bug Report: I cannot use `useLoaderData` hook from react-router

### ISSUE THREAD

**Issue by mailok** [backstage/backstage#19681]
### 📜 Description

When we use the ﻿[useLoaderData](https://reactrouter.com/en/main/hooks/use-loader-data) hook from [react-router](https://reactrouter.com/en/main) within a Plugin, we encounter an error that says:

`useLoaderData must be used within a data router. See https://reactrouter.com/routers/picking-a-router.`

From what I understand, the `AppRouter` component in Backstage is not using the `<RouterProvider />` from `react-router`. But it's just a suspicion

### 👍 Expected behavior

I hope to be able to use the ﻿`useLoaderData` hook from `react-router` in my nested routes within my Plugin, for example:

```
export const Main = () => {
  return (
    <Page themeId="home">
      <Header />
      <Content>
        <Routes>
          <Route index element={<Home />} loader={fetchPosts} />
          <Route path=":post" element={<Post />} />
          <Route path=":post/edit" element={<EditPost />} />
        </Routes>
      </Content>
    </Page>
  );
};
```

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/3769277/47ec9480-2769-4f9f-bb49-95d018222774)

### 👟 Reproduction steps

1. Create a plugin
2. Define routes:

```
export const rootRouteRef = createRouteRef({
  id: 'plugin-name',
});

export const postRouteRef = createSubRouteRef({
  id: 'post',
  parent: rootRouteRef,
  path: '/:post',
});

export const editGroupRouteRef = createSubRouteRef({
  id: 'edit',
  parent: rootRouteRef,
  path: '/edit',
});

```

3. Create a loader function:

```
export async function fetchPosts() {
  const posts = await getPosts();
  return { posts };
}

```

4. Use the loader function in the Route component(The Route component has a Prop for that)

```
export const Main = () => {
  return (
    <Page themeId="home">
      <Header />
      <Content>
        <Routes>
          <Route index element={<Home />} loader={fetchPosts} />
          <Route path=":post" element={<Post />} />
          <Route path=":post/edit" element={<EditPost />} />
        </Routes>
      </Content>
    </Page>
  );
};
```

5. Trying to access the data within the component:
```
function Home() {
  const data = useLoaderData();
  return (
    <div>some children here</div>
  );
}

```

### 📃 Provide the context for the Bug.

I am creating a plugin that will be responsible for managing some data. I am trying to use the basic react-router API to fetch the data and perform some actions.

### 🖥️ Your Environment

OS:   Darwin 22.6.0 - darwin/x64
node: v16.18.1
yarn: 1.22.19
cli:  0.22.9 (installed)
backstage:  1.16.0

Dependencies:
  @backstage/app-defaults                          1.4.1
  @backstage/backend-app-api                       0.4.5, 0.5.2
  @backstage/backend-common                        0.19.1, 0.19.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.4, 0.6.2
  @backstage/backend-tasks                         0.5.4, 0.5.7
  @backstage/catalog-client                        1.4.3
  @backstage/catalog-model                         1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.2, 0.1.3
  @backstage/cli                                   0.22.9
  @backstage/config-loader                         1.3.2, 1.4.0
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.9.0, 1.9.1
  @backstage/core-components                       0.13.3
  @backstage/core-plugin-api                       1.5.3
  @backstage/dev-utils                             1.0.17
  @backstage/errors                                1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.5
  @backstage/integration-react                     1.1.15
  @backstage/integration                           1.5.1, 1.6.2
  @backstage/plugin-api-docs                       0.9.6
  @backstage/plugin-app-backend                    0.3.47
  @backstage/plugin-auth-backend                   0.18.5
  @backstage/plugin-auth-node                      0.2.16, 0.2.19
  @backstage/plugin-catalog-backend-module-gitlab  0.2.3
  @backstage/plugin-catalog-backend                1.11.0
  @backstage/plugin-catalog-common                 1.0.15
  @backstage/plugin-catalog-graph                  0.2.32
  @backstage/plugin-catalog-import                 0.9.10
  @backstage/plugin-catalog-node                   1.4.0
  @backstage/plugin-catalog-react                  1.8.0
  @backstage/plugin-catalog                        1.12.0
  @backstage/plugin-events-node                    0.2.8
  @backstage/plugin-github-actions                 0.6.1
  @backstage/plugin-org                            0.6.10
  @backstage/plugin-permission-backend             0.5.22
  @backstage/plugin-permission-common              0.7.7
  @backstage/plugin-permission-node                0.7.10, 0.7.13
  @backstage/plugin-permission-react               0.4.14
  @backstage/plugin-proxy-backend                  0.2.41
  @backstage/plugin-scaffolder-backend             1.15.1
  @backstage/plugin-scaffolder-common              1.3.2
  @backstage/plugin-scaffolder-node                0.1.5
  @backstage/plugin-scaffolder-react               1.5.1
  @backstage/plugin-scaffolder                     1.14.1
  @backstage/plugin-search-backend-module-catalog  0.1.3
  @backstage/plugin-search-backend-module-pg       0.5.8
  @backstage/plugin-search-backend-module-techdocs 0.1.3
  @backstage/plugin-search-backend-node            1.2.3
  @backstage/plugin-search-backend                 1.3.3
  @backstage/plugin-search-common                  1.2.5
  @backstage/plugin-search-react                   1.6.3
  @backstage/plugin-search                         1.3.3
  @backstage/plugin-tech-radar                     0.6.6
  @backstage/plugin-techdocs-backend               1.6.4
  @backstage/plugin-techdocs-module-addons-contrib 1.0.15
  @backstage/plugin-techdocs-node                  1.7.3
  @backstage/plugin-techdocs-react                 1.1.8
  @backstage/plugin-techdocs                       1.6.5
  @backstage/plugin-user-settings                  0.7.5
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.1, 1.4.2
  @backstage/theme                                 0.4.1
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Indeed! For now the state of this is that it needs investigation to see if it fits well with our plugin architecture or whether it should be discouraged / not available. If the data loading can be isolated to individual plugins then this is likely something that we can add support for, but if it creates and implicit cross plugin communication pattern in might not be something that we want to support. It might also be something that we only encourage use of for bespoke internal plugins.

We won't be able to pick this up in the near term, so if anyone wants to investigate this, let us know! 😁

**Comment by nodify-at** [comment]
Hello everyone,

I've been exploring a potential solution to the issue at hand and are currently in the testing phase. For those who are still interested, I've found that I can pass a custom Router while initialising the Backstage application. Specifically, I can pass the router provider with createBrowserRouter, making the data API available.

Here's a snippet of the implementation:

```ts
const app = createApp({
  components: {
    Router: props => {
      const router = createBrowserRouter([
        { path: "*", Component: () => <>{props.children}</> },
      ]);

      return <RouterProvider router={router} />;
    }
  },
  // ... rest of your configuration
});
```
I hope this proves helpful to you! I'm eager to hear your feedback and any results from your own testing with this approach :)
