### ISSUE TITLE
🐛 Bug Report: Switching between techdocs pages causes odd behavior

### ISSUE THREAD

**Issue by steff-petro** [backstage/backstage#19686]
### 📜 Description

When switching between two techdocs pages using the sidebar navigation it takes you to the middle of the clicked page.

### 👍 Expected behavior

Clicking between pages should land you at the top of the page clicked page, not somewhere in the middle.

### 👎 Actual Behavior with Screenshots

When clicking on the sidebar navigation to another page it defaults to displaying from somewhere in the middle of that page not the top.

### 👟 Reproduction steps

1. Browse any page that requires you to scroll to view the entire page
2. Scroll to the bottom of that page or somewhere that is not the top
3. Click to another page using the sidebar navigation (the clicked page needs to be long enough for it to work)
4. This will show that page from somewhere in the middle not the top.

### 📃 Provide the context for the Bug.

Not a breaking bug but annoying behavior that causes a disturbance to our users techdocs experience

### 🖥️ Your Environment

- Browser chrome
- This is replicable on backstage demo site or any backstage instance that is deployed

OS:   Windows_NT 10.0.19044 - win32/x64
node: v18.15.0
yarn: 1.22.19
cli:  0.22.9 (installed)
backstage:  1.16.0

Dependencies:
  @backstage/app-defaults                               1.4.1
  @backstage/backend-app-api                            0.4.5, 0.5.1
  @backstage/backend-common                             0.19.1, 0.19.3
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.4, 0.6.1
  @backstage/backend-tasks                              0.5.4, 0.5.6
  @backstage/catalog-client                             1.4.3
  @backstage/catalog-model                              1.4.1
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.2, 0.1.3
  @backstage/cli                                        0.22.9
  @backstage/config-loader                              1.3.2, 1.4.0
  @backstage/config                                     1.0.8
  @backstage/core-app-api                               1.9.0
  @backstage/core-components                            0.12.5, 0.13.3, 0.13.4
  @backstage/core-plugin-api                            1.5.3
  @backstage/dev-utils                                  1.0.17
  @backstage/errors                                     1.2.1
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.5
  @backstage/integration-react                          1.1.15
  @backstage/integration                                1.5.1, 1.6.1
  @backstage/plugin-api-docs                            0.9.6
  @backstage/plugin-app-backend                         0.3.47
  @backstage/plugin-auth-backend                        0.18.5
  @backstage/plugin-auth-node                           0.2.16, 0.2.18
  @backstage/plugin-catalog-backend-module-github       0.3.2
  @backstage/plugin-catalog-backend                     1.11.0
  @backstage/plugin-catalog-common                      1.0.15
  @backstage/plugin-catalog-graph                       0.2.32
  @backstage/plugin-catalog-import                      0.9.10
  @backstage/plugin-catalog-node                        1.4.0, 1.4.2
  @backstage/plugin-catalog-react                       1.8.0, 1.8.2
  @backstage/plugin-catalog                             1.12.0
  @backstage/plugin-events-node                         0.2.8
  @backstage/plugin-github-actions                      0.6.1
  @backstage/plugin-github-pull-requests-board          0.1.14
  @backstage/plugin-home-react                          0.1.1
  @backstage/plugin-home                                0.4.32, 0.5.4
  @backstage/plugin-kubernetes-backend                  0.11.4
  @backstage/plugin-kubernetes-common                   0.6.5
  @backstage/plugin-kubernetes                          0.10.1
  @backstage/plugin-org                                 0.6.10
  @backstage/plugin-permission-common                   0.7.7
  @backstage/plugin-permission-node                     0.7.10, 0.7.12
  @backstage/plugin-permission-react                    0.4.14
  @backstage/plugin-proxy-backend                       0.2.41
  @backstage/plugin-scaffolder-backend                  1.15.1
  @backstage/plugin-scaffolder-common                   1.3.2
  @backstage/plugin-scaffolder-node                     0.1.5
  @backstage/plugin-scaffolder-react                    1.5.1
  @backstage/plugin-scaffolder                          1.14.1
  @backstage/plugin-search-backend-module-catalog       0.1.3
  @backstage/plugin-search-backend-module-pg            0.5.8
  @backstage/plugin-search-backend-module-techdocs      0.1.3
  @backstage/plugin-search-backend-node                 1.2.3
  @backstage/plugin-search-backend                      1.3.3
  @backstage/plugin-search-common                       1.2.5
  @backstage/plugin-search-react                        1.6.3
  @backstage/plugin-search                              1.3.3
  @backstage/plugin-sentry                              0.5.5
  @backstage/plugin-stack-overflow-backend              0.2.3
  @backstage/plugin-stack-overflow                      0.1.18
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.31
  @backstage/plugin-tech-insights-backend               0.5.13
  @backstage/plugin-tech-insights-common                0.2.11
  @backstage/plugin-tech-insights-node                  0.4.5
  @backstage/plugin-tech-insights                       0.3.12
  @backstage/plugin-tech-radar                          0.6.6
  @backstage/plugin-techdocs-backend                    1.6.4
  @backstage/plugin-techdocs-module-addons-contrib      1.0.15
  @backstage/plugin-techdocs-node                       1.7.3
  @backstage/plugin-techdocs-react                      1.1.8
  @backstage/plugin-techdocs                            1.6.5
  @backstage/plugin-user-settings                       0.7.5
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.4.1
  @backstage/theme                                      0.2.18, 0.3.0, 0.4.1
  @backstage/types                                      1.1.0
  @backstage/version-bridge                             1.0.4
Done in 3.15s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by kajahanne** [comment]
We're experiencing the same behaviour, also when using **_Next_** and _**Previous**_ buttons on the bottom of TechDoc pages.
I can also see that the same behaviour exists on the [Backstage demo-site](https://demo.backstage.io/docs/default/component/backstage/conf/writing/), so it can easily be replicated here.

**Comment by user1bh** [comment]
The following issue might be also related, because Techdocs navigation seems seriously broken: https://github.com/backstage/backstage/issues/20159

**Comment by squid-ney** [comment]
Hi there! I've been looking into this issue. The current logic that controls scroll to the correct anchor/heading when a page refresh happens is this transformer , [scrollIntoAnchor.ts](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/transformers/scrollIntoAnchor.ts).  If there is no `hash` present in `window.location.hash`, then I believe having the page scroll to the top would fix this issue.

```
if (window.location.hash) {
      const hash = window.location.hash.slice(1);
      dom?.querySelector(`[id="${hash}"]`)?.scrollIntoView();
}
else{
     // scroll to top of page
}
```

**Comment by steff-petro** [comment]
@squid-ney Thank you for solving this issue, very much appreciated!
