### ISSUE TITLE
🐛 Bug Report: Output text types are not actually supported in scaffodler

### ISSUE THREAD

**Issue by Andrei-Predoiu** [backstage/backstage#19691]
### 📜 Description

Output text types are not actually supported in scaffodler
https://backstage.io/docs/features/software-templates/writing-templates#outputs

### 👍 Expected behavior

Create template outputs as expected:

### 👎 Actual Behavior with Screenshots

Ignores text outputs

### 👟 Reproduction steps

1. Try to make a template as described in the docs. here:
https://backstage.io/docs/features/software-templates/writing-templates#outputs
2. You can replace the `${{ steps['publish'].output.remoteUrl }}` Nunjucks with Hello world for good measure 
3. Run the template
4. Text output is missing

### 📃 Provide the context for the Bug.

The page is completely missing support for text output:

https://github.com/backstage/backstage/blob/e27ddc36dade80b41389f87ddad17875fc2c98f4/plugins/scaffolder/src/components/TaskPage/TaskPage.tsx#L357

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Just clarifying that this feature does exist but just with the newer scaffolder as mentioned in my comment above 👍
