### ISSUE TITLE
🐛 Bug Report: Techdocs sometimes get stuck with an infinite loader

### ISSUE THREAD

**Issue by yousifalraheem** [backstage/backstage#19716]
### 📜 Description

There are a few of our embedded techdocs experience an issue of an infinite loader showing up and no content. After inspecting the code, I can see the HTML content is loaded and ready to be rendered by the container's opacity is set to `0`. I'm guessing this is happening because Backstage is preparing a few things before turning off the loader and showing the content, but the loader goes indefinitely.

### 👍 Expected behavior

The loader should disappear after the HTML content is loaded revealing the content.

### 👎 Actual Behavior with Screenshots

There is a loader that runs indefinitely and the content is hidden because the html element's opacity is set to `0`

![Screenshot 2023-09-01 at 14 43 14](https://github.com/backstage/backstage/assets/10633734/85fcb097-24cd-448f-b674-a1d24afeb777)

### 👟 Reproduction steps

I don't know why it is happening for some documentation pages but not others. But I think the logic related to showing the loader and hiding the content needs to be inspected to find possible reasons for this behavior. Maybe the function responsible for turning off the loader is never invoked in some cases.

### 🖥️ Your Environment

```
OS:   Darwin 22.5.0 - darwin/arm64
node: v18.16.0
yarn: 3.3.0
cli:  0.22.9 (installed)
backstage:  1.16.0

Dependencies:
  @backstage/app-defaults                         1.4.1
  @backstage/backend-app-api                      0.4.2, 0.4.5
  @backstage/backend-common                       0.18.4, 0.19.1
  @backstage/backend-dev-utils                    0.1.1
  @backstage/backend-plugin-api                   0.5.1, 0.5.4
  @backstage/backend-tasks                        0.5.1, 0.5.4
  @backstage/catalog-client                       1.4.1, 1.4.3
  @backstage/catalog-model                        1.3.0, 1.4.1
  @backstage/cli-common                           0.1.12
  @backstage/cli-node                             0.1.2
  @backstage/cli                                  0.22.9
  @backstage/config-loader                        1.2.0, 1.3.2
  @backstage/config                               1.0.7, 1.0.8
  @backstage/core-app-api                         1.7.0, 1.9.0
  @backstage/core-components                      0.12.5, 0.13.0, 0.13.3
  @backstage/core-plugin-api                      1.5.1, 1.5.3
  @backstage/dev-utils                            1.0.17
  @backstage/errors                               1.1.5, 1.2.1
  @backstage/eslint-plugin                        0.1.3
  @backstage/integration-aws-node                 0.1.2, 0.1.5
  @backstage/integration-react                    1.1.15
  @backstage/integration                          1.4.4, 1.5.1
  @backstage/plugin-api-docs                      0.9.6
  @backstage/plugin-auth-backend                  0.18.5
  @backstage/plugin-auth-node                     0.2.13, 0.2.16
  @backstage/plugin-catalog-backend               1.11.0
  @backstage/plugin-catalog-common                1.0.13, 1.0.15
  @backstage/plugin-catalog-import                0.9.10
  @backstage/plugin-catalog-node                  1.4.0
  @backstage/plugin-catalog-react                 1.5.0, 1.8.0
  @backstage/plugin-catalog                       1.12.0
  @backstage/plugin-events-node                   0.2.8
  @backstage/plugin-org                           0.6.10
  @backstage/plugin-permission-backend            0.5.22
  @backstage/plugin-permission-common             0.7.5, 0.7.7
  @backstage/plugin-permission-node               0.7.10, 0.7.7
  @backstage/plugin-permission-react              0.4.12, 0.4.14
  @backstage/plugin-proxy-backend                 0.2.41
  @backstage/plugin-scaffolder-common             1.3.2
  @backstage/plugin-scaffolder-react              1.5.1
  @backstage/plugin-scaffolder                    1.14.1
  @backstage/plugin-search-backend-module-catalog 0.1.3
  @backstage/plugin-search-backend-node           1.2.3
  @backstage/plugin-search-common                 1.2.3, 1.2.5
  @backstage/plugin-search-react                  1.5.2, 1.6.3
  @backstage/plugin-search                        1.3.3
  @backstage/plugin-shortcuts                     0.3.12
  @backstage/plugin-tech-radar                    0.6.6
  @backstage/plugin-techdocs-react                1.1.8
  @backstage/plugin-techdocs                      1.6.5
  @backstage/plugin-user-settings                 0.7.5
  @backstage/release-manifests                    0.0.9
  @backstage/test-utils                           1.4.1
  @backstage/theme                                0.2.19, 0.4.1
  @backstage/types                                1.0.2, 1.1.0
  @backstage/version-bridge                       1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kneyugn** [comment]
What does your mkdocs look like to build these specific repos? Our team finds that if you omit the techdocs plugin in the mkdocs file, it doesn't always render and will show this infinite loader.

**Comment by sennyeya** [comment]
Might be related #13696

**Comment by ypetrych** [comment]
This issue is very often reproducible for me in such case (I use README files) 
1. Open some tech docs page first time. 
2. The request for index.md fails. 
3. Backstage retries to load it.
4. The second request for index.md fails also. Maybe the documentation is not still built.
5. Not Found Error page is shown.
6. I refresh the page in browser. Infinite scroll appears.

**Comment by ypetrych** [comment]
Could you reopen the ticket?

**Comment by stijnbrouwers** [comment]
Facing the exact same issue but in a slightly different setup.
I am generating the docs in pipelines and publishing to S3.
So when viewing the docs, I retrieve index.html files from S3 but like mentioned by @yousifalraheem :
"There is a loader that runs indefinitely and the content is hidden because the html element's opacity is set to 0"
When manually setting the opacity to 1 for the html element, the docs are visible.

I noticed in my browsers "network" tab (dev tools) that the retrieval of the index.html yields a "304 Not Modified".
I am wondering if this might be the culprit...

**Comment by hanjos** [comment]
This issue is reproducible for me as well, with repos with only HTML files (no Markdown). 

It shows up with a local `techdocs-cli serve --no-docker`, and in an internal Backstage instance. 

`mkdocs serve` on the same repo renders the HTML with no issue.

**Comment by Ginger0913** [comment]
Did this end up getting resolved? I am also experiencing the issue where it appears that the techdoc is infinitely loading, however the shadow dom contains all of the rendered markdown, but the html in the dom has a hard style of opacity 0.

**Comment by jessicamann** [comment]
I am also experiencing this issue with generated html. The contents appear to be on the page but not visible; if my mouse goes around the page, I can click on the (invisible) "navigation links"

**Comment by cecobask** [comment]
I'm experiencing the same problem. Is there a reason this is happening? Can this issue please be reopened?

**Comment by cecobask** [comment]
After some debugging, I pinpointed the problem to the `mkdocs.yml` file.
The problematic component's mkdocs config looked like that:
```
site_name: example
```
After I changed it to this, it worked again:
```
site_name: example
plugins:
  - techdocs-core
```

**Comment by daanrijpkemacb** [comment]
I still have this exact same issue, while the mkdocs.yaml already contains the techdocs-core plugin. 
The content is already searchable and visible in the HTML, simply not shown on the page.

Any additional input is appreciated!

**Comment by Ginger0913** [comment]
> I still have this exact same issue, while the mkdocs.yaml already contains the techdocs-core plugin. 
> The content is already searchable and visible in the HTML, simply not shown on the page.
> 
> Any additional input is appreciated!

Are you self hosting behind a firewall that prevents outbound connections?

**Comment by daanrijpkemacb** [comment]
> Are you self hosting behind a firewall that prevents outbound connections?

Yes, we are.
We do also see this console error:

```
Refused to apply style from 'https://<URL>/api/techdocs/static/docs/default/system/sitemap/assets/stylesheets/main.6f8fc17f.min.css' because its MIME type ('application/json') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
which might be related.

**Comment by daanrijpkemacb** [comment]
Side note: It is most likely also related to this [issue](https://github.com/backstage/backstage/issues/6015).
At the end of the thread, there is an indication it might have to do with [the permissions framework](https://backstage.io/docs/permissions/getting-started/#optionally-add-cookie-based-authentication)
yet that is not anymore documented in the 'newer' version of Backstage.

**Comment by alecjacobs5401** [comment]
Bumping this, it appears to happen inconsistently for users in our deploy environments. Impacts some but not all...
