### ISSUE TITLE
🐛 Bug Report: <The values of the components that belong to a dependency are not getting reseted after unmount>

### ISSUE THREAD

**Issue by kostalexis89** [backstage/backstage#19711]
### 📜 Description

I am using the dependencies for conditional rendering as it is described here:
https://react-jsonschema-form.readthedocs.io/en/v1.8.1/dependencies/

`{
  "title": "Person",
  "type": "object",
  "properties": {
    "Do you have any pets?": {
      "type": "string",
      "enum": [
        "No",
        "Yes: One",
        "Yes: More than one"
      ],
      "default": "No"
    }
  },
  "required": [
    "Do you have any pets?"
  ],
  "dependencies": {
    "Do you have any pets?": {
      "oneOf": [
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "No"
              ]
            }
          }
        },
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "Yes: One"
              ]
            },
            "How old is your pet?": {
              "type": "number"
            }
          },
          "required": [
            "How old is your pet?"
          ]
        },
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "Yes: More than one"
              ]
            },
            "Do you want to get rid of any?": {
              "type": "boolean"
            }
          },
          "required": [
            "Do you want to get rid of any?"
          ]
        }
      ]
    }
  }
}`

If I choose **Yes: One** and then I choose how old is my pet and then change it and choose **No** (that I dont have pets)
and then **Yes: One** again, the data from my previous choice is not getting reseted. And I am carrying those formData if i selected them from before

### 👍 Expected behavior

I am expecting the dependecie's properties to be reseted if the user deselect the dependency and not to carry those formdata

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-09-01 at 11 28 32](https://github.com/backstage/backstage/assets/91941827/701d2755-740d-454b-940d-0c4bac89b8f6)

### 👟 Reproduction steps

Roproduce:

Go here: https://rjsf-team.github.io/react-jsonschema-form/

Paste the code above

Select that u have one pet

Set the age

Then Select that u dont have a pet

Then Select that u have one pet

And the age that u previous selected will be there

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by tudi2d** [comment]
Thanks for reporting. As you have already pointed out in _"Reproduction steps"_ this is a specific behaviour of JSON Schema Form & not tied to our implementation in Backstage. Please refer to [their documentation](https://react-jsonschema-form.readthedocs.io/en/v1.8.1/) for possible options to change the default behaviour & report the issue with them in case you think this is a bug :)
