### ISSUE TITLE
🐛 Bug Report: Authentication backstage with Oaut2-proxy development environment 

### ISSUE THREAD

**Issue by kalyanikor** [backstage/backstage#19782]
### 📜 Description

Enable backstage authentication with oauth2-proxy.

### 👍 Expected behavior

Configure user authentication with keycloak and oauth2-proxy.

### 👎 Actual Behavior with Screenshots

Request URL: http://localhost:4180/oauth2/callback/api/auth/oauth2
Request Method: GET
Status Code: 200 OK

![image](https://github.com/backstage/backstage/assets/143597782/74636a87-e7fe-4960-84ea-65e695cb5339)

but not able to connect with backstage.

### 👟 Reproduction steps

**1.- Keycloak**

- Start local keycloak in docker with:

- docker run -p 9990:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin jboss/keycloak 

- Add new Backstage realm and create user.

**2.- Oauth2-Proxy.**

- Downloaded the precompiled binary from this link: https://github.com/oauth2-proxy/oauth2-proxy/releases (version 7.4.0).

- Create file with name oauth2_proxy.cfg and the following contents:

http_address = "127.0.0.1:4180"

              provider = "keycloak"
              login_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/auth"
              redeem_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/token"
              profile_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/userinfo"
              validate_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/userinfo"
              oidc_issuer_url = "http://localhost:9990/auth/realms/backstage"
              
              client_id = "oauth2-proxy"
              client_secret = "B6U0bbjTB0SdqzaUJVCpNh3y2wMFkgYI"
              
              redirect_url = "http://localhost:4180/oauth2/callback"
              
              upstreams = [
                  "http://127.0.0.1:3000/" ,"http://localhost:3000" ,"http://localhost:7007/api/"
              ]
              
              request_logging = true
              
              pass_basic_auth = true
              pass_user_headers = true
              pass_host_header = true 
              
              email_domains = [
                  "*"
              ]
              
              pass_access_token = true
              ssl_insecure_skip_verify = false
              cookie_secret = "lLYcG3L1khAS9Yz8hXb7mia1wSDk_eCDQFzl_Yx2rA4="
              cookie_secure = false
              set_authorization_header = "true"
              pass_authorization_header = "true"
              reverse_proxy = "true"
              scope = "email"
              whitelist_domains = "*"
              skip_provider_button = "true"
              set_xauthrequest = "true"

**run command:**
```
./oauth2-proxy \
    --config=./oauth2_proxy.cfg
```

**3.- Backstage**

I started a new project with the command: npx @backstage/create-app
the following files have been modified:

**app-config.yaml:**
<SNIP>

auth:
```
  providers:
    oauth2Proxy: {}

 baseUrl: http://localhost:4180


cors:
  origin: http://localhost:4180

```

 **#App.tsx:**
```

<SNIP>

const app = createApp({
  ...
  components: {
    SignInPage: props => (
      <ProxiedSignInPage {...props} provider="oauth2Proxy" />
    ),
  },
});

<SNIP>

```

**auth.ts**

<SNIP>
...

```
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      ...defaultAuthProviderFactories,

      oauth2Proxy: providers.oauth2Proxy.create({
        signIn: {
          async resolver(info, ctx) {
            const name = result.getHeader('x-forwarded-user');
            if (!name) {
              throw new Error('Request did not contain a user')
            }

            // Create stub user
            const userEntityRef = stringifyEntityRef({
              kind: 'User',
              name: name,
              namespace: DEFAULT_NAMESPACE,
            });

            return ctx.issueToken({
              claims: {
                sub: userEntityRef,
                ent: [userEntityRef],
              },
            });

          },
        },
      }),
```

...
<SNIP>

**run command:**
`yarn dev`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by craigtracey** [comment]
This looks like you have an issue with your oauth2-proxy configuration. From your screenshot, you are receiving HTML when you expect JSON, while `GET`ing the oauth2 callback. 

Minimally, it seems that the oauth2-proxy configuration you have added to this bug is not correct. 
```          
upstreams = [
              "http://127.0.0.1:3000/" "http://localhost:3000" ,"http://localhost:7007/api/"
]
```
is invalid syntax for oauth2-proxy configuration. I think what you may be looking for is:
```
upstreams = [
    "http://localhost:3000" ,
    "http://localhost:7007/api/"
]
```

Could you give that a try?

[This](https://janus-idp.io/blog/2023/01/17/enabling-keycloak-authentication-in-backstage) is a fantastic resource for configuring Backstage with Keycloak and oauth2-proxy.

**Comment by kalyanikor** [comment]
we have fix that not working
