### ISSUE TITLE
🐛 Bug Report: create project access token (gitlab:projectAccessToken:create) fails in gitlab 16.x

### ISSUE THREAD

**Issue by thomastroschke** [backstage/backstage#19791]
### 📜 Description

It brings the bug out, when you use the action gitlab:projectAccessToken:create to create a gitlab project access token in gitlab 16.x. 

Since gitlab 16 it is required to provide an expire date, when you create an project access token.

https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html

### 👍 Expected behavior

The project access token would be created in the action. 

### 👎 Actual Behavior with Screenshots

No error Message while creating:

![image](https://github.com/backstage/backstage/assets/127211395/95036945-8144-43d4-8cf1-fec93c02a2f3)

But no project access token was created.

![image](https://github.com/backstage/backstage/assets/127211395/710ae7b2-593a-47d1-9335-ea7d328e7e5b)
![image](https://github.com/backstage/backstage/assets/127211395/da46ff26-0894-41e7-ad2b-e146cd9a84be)

### 👟 Reproduction steps

1. use the action gitlab:projectAccessToken:create in a template
2. check if a project access token was created

### 🖥️ Your Environment

backstage 1.17.5 --> experimental backend
self hosted gitlab v16.2.2-ee

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Perhaps @dpfaffenbauer or @Andy2003 has some spare cycles to help out here.

**Comment by freben** [comment]
@Thomas1001101 did you have a chance to look into a fix for this?

**Comment by Thomas1001101** [comment]
Hi, i'm on vacation this week. I will do a fix next week. Thx for the reminder.

**Comment by Thomas1001101** [comment]
Hi, I created the PR for the https://github.com/backstage/backstage/pull/21483 Issue
