### ISSUE TITLE
🚀 Feature: Render a single template file similar to fetch:plain:file

### ISSUE THREAD

**Issue by alex-b-duplessis** [backstage/backstage#19795]
### 🔖 Feature description

The `fetch:template` action currently supports fetching and rendering template files as an entire directory.  I would like the ability to selectively fetch and render an individual template file (and/or filter a subset of directory files) with variables.  

### 🎤 Context

This feature could be very useful when attempting to reuse template files (avoiding duplication) and combine them with other files, where necessary.  Multiple `fetch:template` steps could be used to prepare the workspace files before publishing, some fetching and rendering an entire directory from one location, and others fetching and rendering individual files from other locations.

### ✌️ Possible Implementation

This request seems to have parallels with the `fetch:plain:file` action that was implemented from [Issue 15538](https://github.com/backstage/backstage/issues/15388).  Perhaps creating a new `fetch:template:file` action would address similar concerns.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jhaals** [comment]
Sounds like a good idea!

**Comment by Ivaylo-Korakov** [comment]
This sounds awesome. I am looking for exactly this atm.

**Comment by benjdlambert** [comment]
@Ivaylo-Korakov do you want to contribute this functionality? :pray:

**Comment by 63070054** [comment]
waiting for this

**Comment by talron23** [comment]
We use backstage templates a lot, and we would really like to see this feature coming to backstage.

**Comment by stephenglass** [comment]
I'm working on this. I've created the action, just working on tests now. Should have a PR out for it soon.
