### ISSUE TITLE
🐛 Bug Report: Catalog is unusable as a guest user

### ISSUE THREAD

**Issue by sennyeya** [backstage/backstage#19794]
### 📜 Description

I'm unable to test anything as a guest user in my local environment due to a propogated error message that I have to click through to see the Entity page. I was able to do this locally as expected on branches from last month, but am no longer able to. Logging in through Github OAuth causes the issue to disappear.

https://github.com/backstage/backstage/assets/34432188/314432dd-92ab-47ba-bc79-d1c01baac8dc

I think this was introduced by https://github.com/backstage/backstage/pull/19434/files#diff-b49f50e782910892a50ac2d8092e3c1aa9498c9569da8574c3555f81a92b07b7R79 as the stack trace has that as the line causing it,
```
eval @ webpack-internal:///../core-app-api/src/apis/implementations/FetchApi/IdentityAuthInjectorFetchMiddleware.ts:43
eval @ webpack-internal:///../core-app-api/src/apis/implementations/FetchApi/PluginProtocolResolverFetchMiddleware.ts:40
getAllPlaylists @ webpack-internal:///../../plugins/playlist/src/api/PlaylistClient.ts:57
PlaylistEditDialog @ webpack-internal:///../../plugins/playlist/src/components/PlaylistEditDialog/PlaylistEditDialog.tsx:82
renderWithHooks @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:14985
updateFunctionComponent @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:17356
beginWork @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:19063
beginWork$1 @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:23935
performUnitOfWork @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22771
workLoopSync @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22702
renderRootSync @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22665
performSyncWorkOnRoot @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22288
eval @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:11327
unstable_runWithPriority @ webpack-internal:///../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:11276
flushSyncCallbackQueueImpl @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:11322
flushSyncCallbackQueue @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:11309
discreteUpdates$1 @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22415
discreteUpdates @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3756
dispatchDiscreteEvent @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:5889
```

### 👍 Expected behavior

The page should either
1. Throw an alert when I am unauthorized for the playlist plugin.
2. Now load playlists until I open the playlist modal.

### 👎 Actual Behavior with Screenshots

Every entity page has an error boundary like so and the alert box telling me I'm unauthorized.

<img width="1510" alt="Screen Shot 2023-09-05 at 5 07 59 PM" src="https://github.com/backstage/backstage/assets/34432188/66304c71-15cf-42b3-a646-1897228f6347">

Network response is
```
{"error":{"name":"NotAllowedError","message":"Unauthorized","stack":"NotAllowedError: Unauthorized\n    at evaluateRequestPermission (webpack-internal:///../../plugins/playlist-backend/src/service/router.ts:65:19)\n    at async eval (webpack-internal:///../../plugins/playlist-backend/src/service/router.ts:94:36)"},"request":{"method":"GET","url":"/"},"response":{"statusCode":403}}
```

Network stack trace is
```
eval @ webpack-internal:///../core-app-api/src/apis/implementations/FetchApi/IdentityAuthInjectorFetchMiddleware.ts:43
eval @ webpack-internal:///../core-app-api/src/apis/implementations/FetchApi/PluginProtocolResolverFetchMiddleware.ts:40
getAllPlaylists @ webpack-internal:///../../plugins/playlist/src/api/PlaylistClient.ts:57
PlaylistEditDialog @ webpack-internal:///../../plugins/playlist/src/components/PlaylistEditDialog/PlaylistEditDialog.tsx:82
renderWithHooks @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:14985
updateFunctionComponent @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:17356
beginWork @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:19063
beginWork$1 @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:23935
performUnitOfWork @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22771
workLoopSync @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22702
renderRootSync @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22665
performSyncWorkOnRoot @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22288
eval @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:11327
unstable_runWithPriority @ webpack-internal:///../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:11276
flushSyncCallbackQueueImpl @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:11322
flushSyncCallbackQueue @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:11309
discreteUpdates$1 @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22415
discreteUpdates @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3756
dispatchDiscreteEvent @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:5889
```

### 👟 Reproduction steps

1. Log in as the guest user for a local Backstage environment.
2. Navigate to any entity page.
3. See the errors that follow.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by sennyeya** [comment]
Hey @kuangp, yup, I get that. However, I think this is still a bug and not something that should be fixed at the EntityPage level. My change was for a change wrt #18186 in this repo, which I can't remove the `EntityPlaylistDialog` EntityPage from.

I think this is caused by the lack of error handling at line https://github.com/backstage/backstage/pull/19434/files#diff-b49f50e782910892a50ac2d8092e3c1aa9498c9569da8574c3555f81a92b07b7R79 which is causing the error boundary to show. Would it be possible to adjust the change to just show an alert or something similar (or validate in the backend)? As is, any errors from the backend for calls for `playlistApi.getAllPlaylists` will result in an error boundary showing.

Also, it seems like we're calling `playlistApi.getAllPlaylists` at every render with `useRef`, causing things like tab changes to make a network call and throw the error boundary again. Is that expected behavior?

**Comment by freben** [comment]
> I think this is caused by the lack of error handling at line https://github.com/backstage/backstage/pull/19434/files#diff-b49f50e782910892a50ac2d8092e3c1aa9498c9569da8574c3555f81a92b07b7R79 which is causing the error boundary to show. Would it be possible to adjust the change to just show an alert or something similar (or validate in the backend)? As is, any errors from the backend for calls for `playlistApi.getAllPlaylists` will result in an error boundary showing.

Hm that one's async and should safely return a promise rather than throwing right there.

> Also, it seems like we're calling `playlistApi.getAllPlaylists` at every render with `useRef`, causing things like tab changes to make a network call and throw the error boundary again. Is that expected behavior?

Yeah that's my bad that I didn't catch that - should probably be a callback instead. Either way, the results will be thrown away after the first render, so at least the current value of the ref doesn't spuriously change due to repaints.


Anyway, I'll try to look into this one unless y'all come up with something before me.

**Comment by freben** [comment]
Alright, made a quick fix. https://github.com/backstage/backstage/pull/19841
