### ISSUE TITLE
🐛 Bug Report: Backstage does not immediately apply new schedules for scheduled items

### ISSUE THREAD

**Issue by wss-ycabrera** [backstage/backstage#19792]
### 📜 Description

There is a bug where if you change the schedule for a backend task it will not apply the new schedule for that task until it has hit the previously scheduled time.

### 👍 Expected behavior

When the schedule changes, it should use the new schedule right away 

### 👎 Actual Behavior with Screenshots

It waits for the previously schedule time to pass until it uses the new schedule 

### 👟 Reproduction steps

This was noticed with the Soundcheck plugin by doing these steps:

Create a custom fact collector and with a frequency of  '*/10 * * * *'
Verify in the DB that the "soundcheck.backstage_backend_tasks__tasks.next_run_start_at" column is scheduled to run at the next 10th minute.
Stop Backstage
Update the frequency to '* * * * *' and start Backstage
Verify in the DB that the "soundcheck.backstage_backend_tasks__tasks.next_run_start_at" column is still scheduled to run at the next 10th minute rather than the next minute.

### 🖥️ Your Environment

OS:   Windows_NT 10.0.19045 - win32/x64
node: v18.16.1
yarn: 1.22.19
cli:  0.22.12 (installed)
backstage:  1.17.5       

Dependencies:
  @backstage/app-defaults                               1.4.2
  @backstage/backend-app-api                            0.4.5, 0.5.2, 0.5.3-next.2   
  @backstage/backend-common                             0.18.5, 0.19.4, 0.19.5-next.2
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-openapi-utils                      0.0.3
  @backstage/backend-plugin-api                         0.5.4, 0.6.2, 0.6.3-next.2
  @backstage/backend-tasks                              0.5.7
  @backstage/backend-test-utils                         0.2.3-next.2
  @backstage/catalog-client                             1.4.3, 1.4.4-next.1
  @backstage/catalog-model                              1.4.1, 1.4.2-next.1
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.3
  @backstage/cli                                        0.22.12, 0.22.13-next.2
  @backstage/config-loader                              1.4.0, 1.5.0-next.2
  @backstage/config                                     1.0.8, 1.1.0-next.1
  @backstage/core-app-api                               1.9.1
  @backstage/core-components                            0.12.5, 0.13.4
  @backstage/core-plugin-api                            1.5.3
  @backstage/dev-utils                                  1.0.20
  @backstage/errors                                     1.2.1
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.5, 0.1.6-next.1
  @backstage/integration-react                          1.1.18
  @backstage/integration                                1.6.2, 1.7.0-next.2
  @backstage/plugin-adr-backend                         0.3.8
  @backstage/plugin-adr-common                          0.2.14
  @backstage/plugin-adr                                 0.6.6
  @backstage/plugin-api-docs                            0.9.10
  @backstage/plugin-app-backend                         0.3.50
  @backstage/plugin-app-node                            0.1.2
  @backstage/plugin-auth-backend                        0.18.8
  @backstage/plugin-auth-node                           0.2.19, 0.3.0-next.2
  @backstage/plugin-azure-devops-backend                0.3.29
  @backstage/plugin-azure-devops-common                 0.3.0
  @backstage/plugin-azure-devops                        0.3.5
  @backstage/plugin-catalog-backend-module-azure        0.1.21
  @backstage/plugin-catalog-backend                     1.12.4
  @backstage/plugin-catalog-common                      1.0.15
  @backstage/plugin-catalog-graph                       0.2.35
  @backstage/plugin-catalog-import                      0.9.13
  @backstage/plugin-catalog-node                        1.4.3
  @backstage/plugin-catalog-react                       1.8.3
  @backstage/plugin-catalog                             1.12.4
  @backstage/plugin-entity-feedback-backend             0.1.8
  @backstage/plugin-entity-feedback-common              0.1.2
  @backstage/plugin-entity-feedback                     0.2.6
  @backstage/plugin-entity-validation                   0.1.8
  @backstage/plugin-events-node                         0.2.11
  @backstage/plugin-github-actions                      0.6.4
  @backstage/plugin-home-react                          0.1.2
  @backstage/plugin-home                                0.5.7
  @backstage/plugin-linguist-backend                    0.4.2
  @backstage/plugin-linguist-common                     0.1.1
  @backstage/plugin-linguist                            0.1.8
  @backstage/plugin-microsoft-calendar                  0.1.6
  @backstage/plugin-newrelic-dashboard                  0.2.16
  @backstage/plugin-newrelic                            0.3.39
  @backstage/plugin-org                                 0.6.13
  @backstage/plugin-permission-backend                  0.5.25
  @backstage/plugin-permission-common                   0.7.7, 0.7.8-next.1
  @backstage/plugin-permission-node                     0.7.13, 0.7.14-next.2
  @backstage/plugin-permission-react                    0.4.14
  @backstage/plugin-proxy-backend                       0.3.2
  @backstage/plugin-scaffolder-backend                  1.16.5
  @backstage/plugin-scaffolder-common                   1.4.0
  @backstage/plugin-scaffolder-node                     0.2.2
  @backstage/plugin-scaffolder-react                    1.5.4
  @backstage/plugin-scaffolder                          1.14.4
  @backstage/plugin-search-backend-module-catalog       0.1.6
  @backstage/plugin-search-backend-module-pg            0.5.11
  @backstage/plugin-search-backend-module-techdocs      0.1.6
  @backstage/plugin-search-backend-node                 1.2.6
  @backstage/plugin-search-backend                      1.4.2
  @backstage/plugin-search-common                       1.2.5
  @backstage/plugin-search-react                        1.6.4
  @backstage/plugin-search                              1.3.6
  @backstage/plugin-sentry                              0.5.8
  @backstage/plugin-sonarqube-backend                   0.2.4
  @backstage/plugin-sonarqube-react                     0.1.7
  @backstage/plugin-sonarqube                           0.7.4
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.34
  @backstage/plugin-tech-insights-backend               0.5.16
  @backstage/plugin-tech-insights-common                0.2.11
  @backstage/plugin-tech-insights-node                  0.4.8
  @backstage/plugin-tech-insights                       0.3.15
  @backstage/plugin-tech-radar                          0.6.7
  @backstage/plugin-techdocs-backend                    1.6.7
  @backstage/plugin-techdocs-module-addons-contrib      1.0.18
  @backstage/plugin-techdocs-node                       1.7.6
  @backstage/plugin-techdocs-react                      1.1.9
  @backstage/plugin-techdocs                            1.6.8
  @backstage/plugin-user-settings                       0.7.8
  @backstage/release-manifests                          0.0.10-next.0, 0.0.9
  @backstage/test-utils                                 1.4.2
  @backstage/theme                                      0.2.19, 0.4.1
  @backstage/types                                      1.1.0
  @backstage/version-bridge                             1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
This is fixed by #19793!
