### ISSUE TITLE
🐛 Bug Report: Inconsistent capitalization Of entity Kinds And entityRefs

### ISSUE THREAD

**Issue by spencerrichardhenry** [backstage/backstage#19828]
### 📜 Description

When you provide an entity, kinds are expected to be Uppercase (Domain, System, Component)

When you get an entityRef, and obviously URLs, it's all lowercase (domain, system, component)

This creates some very odd behavior where I need to capitalize things sometimes, then de-capitalize them later... uniformity would be nice. Since the kind is so prevelant in the urls, I'd recommend enforcing lowercase.

### 👍 Expected behavior

It should be consistently cased.

### 👎 Actual Behavior with Screenshots

Uppercase is expected in providers, lowercase pretty much everywhere else.

### 👟 Reproduction steps

n/a

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by spencerrichardhenry** [comment]
Right, I'm aware of that. The problem is that `domain` is not defaulted to lowercase on entities, while both `type` and `name` are. Which leads to all sorts of hiccups whenever you're building logic that checks data by pulling from entityRefs or vice versa -- because it has to lowercase for one and uppercase for the other. Why not just make them all lowercase?

**Comment by freben** [comment]
The base format follows kubernetes convention. This is entrenched and cannot change at this point. The kinds are fixed strings and the catalog is strict about their casing in the input format as you've noted. However this is not really any different to type and name. You can give those fields any casing you want, I dare say there's even not a standard to have them lowercased; people frequently mix cases there. There's likewise nothing stopping you inventing new all-lowercase kinds, we just chose to follow old conventions when we made the default ones.

It seems to me that you're doing all kinds of lower- and uppercasing operations in code. That seems like it should be reconsidered. The only thing we embrace doing is case insensitive comparisons, in some cases, for example when handling entity refs.
