### ISSUE TITLE
🐛 Bug Report: GitlabOrgDiscoveryEntityProvider uses a non unique value when creating group entities

### ISSUE THREAD

**Issue by elaine-mattos** [backstage/backstage#19838]
### 📜 Description

We are using Backstage with a self-hosted GitLab instance. While using the GitlabOrgDiscoveryEntityProvider to ingest the groups in our organization, we found two interesting situations:

1. Because the `metadata.name` is created based on the group's full path and slashes (/) get changed to dashes (-) , we face the issue where subgroup "parent/child1/child2" and group "parent-child1-child2" are treated as the same group entity. This causes the first created group entity to be replaced  by the second one (the same uid gets updated). 
2. When the group/subgroup hierarchy is too deep, we end up surpassing the 63 chars limit and the group entity is not created. A warning is issued. 

We wonder if it would be possible to use another value for the `metadata.name`, for example, the group ID, since this value is unique. This would also solve the problem with the 63 chars. 
The group name could then be shown in the frontend with the complete path using the `metadata.title` field (so to make it easier to distinguish the groups).

### 👍 Expected behavior

- Groups whose path hierarchy are too long should also be easily ingested;
- Groups that could potentially be treated as the same after the string transformation will be treated as unique groups. 

### 👎 Actual Behavior with Screenshots

- When a GitLab group "**parent-child1-child2**" is ingested, a new row on the **refresh_state** table on the **backstage_plugin_catalog** database is created. The column **entity_ref** (unique key) gets the value "group:default/parent-child1-child2". 
When the GitLab subgroup "**parent/child1/child2**" is ingested, the same row gets updated and the reference to the first ingested group is lost. 

- Warnings of the type: catalog warn Policy check failed for group:default/my-super-long-path-my-super-long-and-cool-subpath1-my-super-long-and-cool-subpath1; caused by Error: "metadata.name" is not valid; expected a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total but found "my-super-long-path-my-super-long-and-cool-subpath1-my-super-long-and-cool-subpath1". 

### 👟 Reproduction steps

On a GitLab instance:
- create group A-B-C on your top level group;
- create subgroup A, then a subgroup inside it called B and then a subgroup inside it called C. The full path would be topLevel/A/B/C. 

On Backstage, check on the Catalog, which/how many groups were created. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jamieklassen** [comment]
This seems like a legit bug, I just changed the text to mention Gitlab_Org_DiscoveryEntityProvider, which is the class that does the work of ingesting groups specifically

**Comment by freben** [comment]
Oh interesting, that's gotta be fairly statistically unlikely that that particular naming structure happened that led to collisions 😅 Now I'm almost curious how that came about.

But to be a bit more constructive - one thing that most org providers has gravitated towards, is to let users pass in callbacks to adjust how the entity forming happens, including the naming patterns. See [this one](https://github.com/backstage/backstage/blob/79c4079ab892140b48093cefc4b0526013541a74/plugins/catalog-backend-module-msgraph/src/processors/MicrosoftGraphOrgEntityProvider.ts#L144) for example. Adding such callbacks to `GitlabOrgDiscoveryEntityProvider` too, would be a nice addition.

**Comment by elaine-mattos** [comment]
> Oh interesting, that's gotta be fairly statistically unlikely that that particular naming structure happened that led to collisions 😅 Now I'm almost curious how that came about.
> 
> But to be a bit more constructive - one thing that most org providers has gravitated towards, is to let users pass in callbacks to adjust how the entity forming happens, including the naming patterns. See [this one](https://github.com/backstage/backstage/blob/79c4079ab892140b48093cefc4b0526013541a74/plugins/catalog-backend-module-msgraph/src/processors/MicrosoftGraphOrgEntityProvider.ts#L144) for example. Adding such callbacks to `GitlabOrgDiscoveryEntityProvider` too, would be a nice addition.
> 
> Another addition, whether the callbacks are added or not, could be to double check one's generated output for duplicates before even trying to submit them to the catalog. But the question is what to do in the case of collisions. Abort completely? Pick the first one and log? Pick the last one and log?

When we saw that the group names get concatenated by the GitlabOrgDiscoveryEntityProvider  we started testing stuff and playing a bit with it. Then we found out that such manipulation is possible and the unique key "refresh_table.entity_ref" was not being respected, as its value was getting replaced by the last ingested group name.
Groups can be seen by every one and someone could intentionally create a group that would hack into other teams' groups.  Another issue is that GitLab groups can be renamed... 
If a company uses the GitlabOrgDiscoveryEntityProvider as is to build their own RBAC version, couldn't this be a security issue? 
We have decided to patch the code and use  GitLab group IDs instead. It works fine in our test instance. 
The problem is that in some of the screens like the Catalog group's details we see the ID and not the name (metadata.name gets shown instead of the metadata.title). We saw some issues related to this as well: #15965

<img width="321" alt="Bildschirmfoto 2023-09-20 um 14 47 55" src="https://github.com/backstage/backstage/assets/79633988/9cbbb741-d483-46e7-8b76-507a8237b7fc">

Don't you think that using the GitLab group IDs would be a better solution for ingesting the group entities? In GitLab, even if groups and projects are transferred or renamed they keep their IDs.  Group and project IDs are the de facto immutable identificators in GitLab.

**Comment by freben** [comment]
Yeah you can, but it's cumbersome.

The thing about the name is that it's not just used as a unique key, people interact directly with it. If you want to pick an owner for your component, you can no longer write just `owner: my-team` in your yaml files; now you have to have this entire lookup thing going to find the ID to use.

Also as you've seen, until we land #17474 and start using it pervasively, you'll have a lot of places in the code where you will just see names instead of titles.

**Comment by aknauf** [comment]
It seems to me that there are two issues here:
1. Trying to use a friendly name as a unique key, when the friendly name can change is always going to be a problem. This is further exacerbated by the fact that simply moving the group will change its "name" in this structure.
2. Trying to fit a potentially-vast nested structure into 63 characters, while maintaining the "friendliness" of the names is just not going to scale.

I agree with @elaine-mattos that the overwriting of existing groups also makes this is a security issue.

In an enterprise of significant size, I would expect this to be a show stopper. (It certainly is where I work.)

In my view, the correct solution here is (as @elaine-mattos suggests) to use the GitLab group id. While I agree that using the GitLab group id is cumbersome, it seems like Hobson's choice? Cumbersome is better than not working at all.

**Comment by freben** [comment]
I'll just note that #17474 had landed and now we can work on making it used in more places of the interface.
