### ISSUE TITLE
Allow applications to register their Authentication Handlers with the `auth-backend`

### ISSUE THREAD

**Issue by GoWind** [backstage/backstage#1984]
To make the `auth-backend` more generic and support more OAuth and or non-OAuth based setups, please consider exposing the Authentication Handler classes to the application, so that applications 

## Feature Suggestion

When the `auth-backend` 's router is being created or before, allow applications to register custom `AuthProvider`s .

## Possible Implementation

1. Export the `AuthProviderRouteHandlers` interface in `src/providers/types.ts` publicly, so that an application can implement it.
2. Optionally expose the `OAuthProvider` from `src/lib/OAuthProvider.ts` as it is a very wrapper for `OAuth` based Auth handlers.
3. Add a `registerAuthRouterHandler` fn that takes a `providerId` and a factory fn and adds it to the list of available `AuthProviderRouterHandler` factory methods.
This factory method, when passed arguments,  returns an  instance of a `AuthProviderRouterHandler`, similar to how it works in `src/providers/factories.ts`

## Context

Currently, logging-in with our  (Zalando's) SSO doesn't fully work with Backstage.
A successful login returns a profile and a backstage identity object from the backend to the frontend application. When logging with our SSO, this is not happening.

The reason for this is, Backstage assumes that at the end of the authorization flow, the response from the /token endpoint contains an id token.

Backstage uses the email information in the id token to create a Profile/Backstage Identity object for the Frontend after authentication. This identity object is used for session/profile information in the application.

In our SSO setup, we do not obtain an id token , but only an Access and a refresh token.
To obtain a user's information, a request is made separately to a different   API with the ACCESS_TOKEN.

Backstage assumes implicitly that it will only be dealing with openIDConnect compatible OAuth2 servers. openIDConnect is an extension of the OAuth2 mechanism, which in addition to the access and the refresh tokens, provide an id token that contains claims or info about the user.
Our OAuth2 setup is not openID Connect compliant.

The current `OAuth2` wrapper solves a lot of the problem of implementing OAuth for us, but we would like to customize it a little so tha we can use a separate profile service to fetch profile information.

It is possible that many other institutions and companies also might have OAuth setups that are not OIDC compliant or will have variations to the authentication mechanisms where the current setup might be limiting for them.

For entities that would like to use backstage without an OAuth based setup using for example, an username, password combination, The `AuthProviderRouterHandlers` interface is still suitable as the `frameHandler` and the `refresh` interface methods are marked optional. 
The implementation can use the `start` method to return a `postMessage` with the backstage identity information and the `logout` method to handle logouts.

**Comment by dhenneke** [comment]
It can also happen that the existing OAuth2 implementation does not work because the identity provider doesn't know the default scopes or expect others (e.g. `email` instead of `userinfo.email`). Or that one wants to add a custom mapping of token claims to profile attributes.

**Comment by Rugvip** [comment]
@GoWind A lot of work towards this has been merged into master now, for example https://github.com/spotify/backstage/pull/2268, https://github.com/spotify/backstage/pull/2293 and https://github.com/spotify/backstage/pull/2393. Remaining work involves coming up with a decent way to expose things to the backend properly

**Comment by GoWind** [comment]
@Rugvip : Thanks! Just got back from a long vacation. I will take a look at the changes and maybe see if I can suggest some changes.

**Comment by bleathem** [comment]
>  Backstage assumes that at the end of the authorization flow, the response from the /token endpoint contains an id token.
> 
> Backstage uses the email information in the id token to create a Profile/Backstage Identity object for the Frontend after authentication. This identity object is used for session/profile information in the application.
> 
> In our SSO setup, we do not obtain an id token , but only an Access and a refresh token.
> To obtain a user's information, a request is made separately to a different API with the ACCESS_TOKEN.

We are hitting this same issue.  The response form the authorization endpoint has a token, and we use that token against a subsequent endpoint to request user information.

I can develop a custom auth provider implementing this flow, but as I understand it, I won't be able to use that auth provider unless it is shipped with the `auth-backend` plugin.  Is that understanding correct?

**Comment by Rugvip** [comment]
@bleathem Yep, but being able to supply custom providers to the `auth-backend` plugin from the backend package is what this issue is about. It's something we want to add

**Comment by GoWind** [comment]
Please correct me if I am wrong on any of this. 

@Rugvip  : I see that in the PRs mentioned above the `OAuthAdapter` class has been created to provide that can serve as a `AuthProviderRouterHandler` and is exported . This goes a long way to solve the issue. 

However, the `createRouter` in the `service/router.ts` uses the `createAuthProvider` from `src/providers/factories.ts` (which is also the only exported function). 

Users/Companies are still not able to register their wrapper for `OAuth` as there is no way to register one's custom `AuthProvider` in the factory method.

I think it would be very useful for users if we provider a `registerAuthProvider` fn in `lib/providers/factories.ts` that takes a `providerId` and a `AuthProviderFactory` , that can then be used to register a custom `auth` mechanism that still conforms to the same interface. 

I would like to raise a PR for this , if you think this proposal is reasonable.

**Comment by Rugvip** [comment]
@GoWind Yup, that summarizes it. Most likely we'll want the `createRouter` function to accept an array of providers or provider factories, whatever makes the most sense. Then we'd export the equivalent function that is able to construct all the default auth providers from config, which would also serve as the default list of providers if no specific ones are passed it.

I *think* the bit left to explore is really whether it makes sense to export and work with factories or providers directly, or overall what the relationship between the router, factories, and provider implementations is.
