### ISSUE TITLE
🐛 Bug Report: Packages with esm output fail when imported into node modules

### ISSUE THREAD

**Issue by davidscodex** [backstage/backstage#19854]
### 📜 Description

Importing backstage packages with esm output breaks in a node module.

Without `"type": "module"` specified in the nearest package.json, node treats all `.js` files as commonjs. See https://nodejs.org/api/packages.html#determining-module-system 

### 👍 Expected behavior

Import successfully.

### 👎 Actual Behavior with Screenshots

```
file:///Users/davidsullivan/projects/git/backstage-module-failure/index.js:1
import { entitySchemaValidator } from "@backstage/catalog-model";
         ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'entitySchemaValidator' not found. The requested module '@backstage/catalog-model' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@backstage/catalog-model';
const { entitySchemaValidator } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Node.js v18.17.1
```

### 👟 Reproduction steps

package.json
```
{
  "name": "backstage-module-failure",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "node": "node index.js",
    "fix-module": "mv node_modules/@backstage/catalog-model/dist/index.esm.js node_modules/@backstage/catalog-model/dist/index.mjs && sed -i -- \"s/index.esm.js/index.mjs/g\" node_modules/@backstage/catalog-model/package.json"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@backstage/catalog-model": "^1.4.1"
  }
}

```
index.js
```
import { entitySchemaValidator } from "@backstage/catalog-model";

console.log("Success!");
```
Setup
npm i

Fails
npm run node

Passes
npm run fix-module
npm run node

### 📃 Provide the context for the Bug.

Trying to validate catalog-info files outside of backstage. Eg in a github action.
Other dependencies require our library to be esm.

### 🖥️ Your Environment

% npm --version
9.6.7
% node --version
v18.17.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by davidscodex** [comment]
PR is here: https://github.com/backstage/backstage/pull/19855

**Comment by awanlin** [comment]
Hi @davidscodex, wondering if you saw this issue: https://github.com/backstage/backstage/issues/8242, feels related and I'm not sure, based on my reading, that things are in a place where we can move forward with your proposed PR

**Comment by davidscodex** [comment]
#8242 is to support dynamic imports. These packages are failing during static imports.
There is esm code generated during the packaging that is referenced by the "import" subpath export. However as that esm file is named *.js node treats it as commonjs. Either that subpath should be removed, or renamed to .mjs in order to be imported by node.

**Comment by Rugvip** [comment]
This is indeed related to #8242, because one of the reasons that we can't simply start supporting `.mjs` everywhere right now is that we have plenty of places in code with both dynamic `import(...)` and `require(...)` + `require.resolve(...)` calls. Back when I looked at this last time the dynamic imports are transpiled to `require` in CommonJS too, and I think that's still the case. That means that basically all of these calls would break if we switch away from just CommonJS for node. This won't exist in any of the current packages that build both ESM + CJS though, which means it could be an alright starting point. We do want to add proper module support, so appreciate any help in this area. As a side note we're just about to switch to Node v18 + v20 in case that helps.
