### ISSUE TITLE
Include dockerfile for frontend with npx @backstage/create-app

### ISSUE THREAD

**Issue by timja** [backstage/backstage#1985]
## Feature Suggestion

The backend package includes a Dockerfile but the frontend doesn't have it

**Comment by Fox32** [comment]
This might not be required if one had  #1986

**Comment by timja** [comment]
Sure that would solve it too.

**Comment by Rugvip** [comment]
Closing since we're now shipping `@backstage/plugin-app-backend` by default, which handles serving of the frontend
