### ISSUE TITLE
🐛 Bug Report: Sidebar open-on-hover not functioning in major browsers?

### ISSUE THREAD

**Issue by kallayj** [backstage/backstage#19857]
### 📜 Description

The open-on-hover behavior of an unpinned sidebar doesn't seem to work consistently across browsers. It doesn't work on my version of Edge on my work Windows machine, but does work on my version of Firefox. It works on personal machine of mine, a Chromebook, in Chrome, but on yet another personal Windows machine, works in neither Edge nor Chrome. 

### 👍 Expected behavior

When the sidebar is unpinned, hovering over it with the mouse should open it.

### 👎 Actual Behavior with Screenshots

Doesn't open consistently across machines/browsers.

### 👟 Reproduction steps

1. Go to demo.backstage.io/settings and toggle Pin Sidebar to Off, to collapse the sidebar
2. Hover the mouse over the collapsed sidebar

### 📃 Provide the context for the Bug.

This is not a big deal so long as it's a known issue; the ability to toggle sidebar pinning on and off per browser means that if you happen to be in a browser where hover-on-open doesn't work, you can just pin it. It is a problem when you're an organization's Backstage maintainer using as your primary browser one where it doesn't work and then you don't know that the pinning/hover-on-open is how the UI is supposed to function... I was therefore surprised to not find it as a documented issue.

### 🖥️ Your Environment

Edge: Version 116.0.1938.69 (Official build) (64-bit) -- doesn't work
Firefox: 102.11.0esr (64-bit) -- works fine

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Hi! Could this possibly be the screen size related? This option won't show unless there's enough room on the page.

**Comment by kallayj** [comment]
Yes, that was it. My Edge installation had a right sidebar that was shrinking the Backstage app window size below the threshold for auto-expanding the left sidebar.
