### ISSUE TITLE
🚀 Feature: i want a Jenkins plugin that can show me the latest job runs with some metadata, such as time, status, buildNumber, and link to directly jump over that job.

### ISSUE THREAD

**Issue by Abhay-soni-developer** [backstage/backstage#19864]
### 🔖 Feature description

I want a Jenkins plugin that can show me the latest job runs with some metadata, such as time, status, buildNumber, and link to directly jump over that job.

### 🎤 Context

In my use case, i do not want my team to hop from one website to another for different tools and their records, i want to provide my product holders and team members with all of their daily needs from one place that is backstage. 

this would make their life a lot easier to manage and monitor, plus saving a lot of time and energy which can be put into something productive.

### ✌️ Possible Implementation

i am gonna extend the current jenkins plugin to support this table

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Contributions welcome 🙏

**Comment by Abhay-soni-developer** [comment]
https://github.com/backstage/backstage/pull/19874 
this is the pull request for this resolve this issue @jhaals  @benjdlambert

**Comment by Abhay-soni-developer** [comment]
https://github.com/backstage/backstage/pull/19881 
please do the needful @benjdlambert @NishkarshRaj @jhaals
