### ISSUE TITLE
🚀 Feature: Display total results with PgSearchEngine

### ISSUE THREAD

**Issue by ivangonzalezacuna** [backstage/backstage#19866]
### 🔖 Feature description

We were using the `LunrSearchEngine` for our search functionality, but we recently switched to the postgres engine, which is giving us a better search experience. However, we discovered something that seems to not be implemented in this engine yet.

We have a SearchPage like the one here: https://github.com/backstage/backstage/blob/master/packages/app/src/components/search/SearchPage.tsx. If you set the `setCounts` to true, in Lunr it displays the total results found. But in postgres it just shows `--`.

### 🎤 Context

Even thought it's not a crucial behavior or game changer, it would be nice to have this counting feature supported in PostgreSQL as well. This can give the users a bit more of info about the search they are applying.

### ✌️ Possible Implementation

We did some investigation, and looks like there is a possible way to solve this. Check out this link: https://stackoverflow.com/questions/58139531/get-total-hit-count-with-postgres-full-text-search

As nobody in our team has a lot of experience with PostgreSQL, we wanted to create an issue first and see if any of the maintainers is willing to try this out/think it makes sense to add such thing.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by awanlin** [comment]
Agree, this would be nice. I haven't had time to create a PR though but would be happy to help review one 🚀

**Comment by ivangonzalezacuna** [comment]
This would still be nice to do. But I don't have much time to work on it, someone with more knowledge in knex willing to work on this?
