### ISSUE TITLE
🚀 Feature: Provide Support for Yarn "Zero Installs" Feature

### ISSUE THREAD

**Issue by matarnold-dev** [backstage/backstage#19878]
### 🔖 Feature description

Please provide the community with a version of Backstage that supports Yarn's "Zero Installs" feature.

https://yarnpkg.com/features/caching#zero-installs

### 🎤 Context

The feature would be a welcome enhancement for developers who are in environments that aren't internet connected.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
We use PnP [in the actions repo](https://github.com/backstage/actions) but not in the main repo. The number of dependencies is very large here, and they change very rapidly. I'm not sure what the effect would be to the repository and its users.

Would you like to investigate this and report what the effect is in terms of repo sizes and times taken for various operations etc? It might be worth considering, but sounds like it can be both good and bad, depending on the contributor.
