### ISSUE TITLE
🐛 Bug Report: TextEncoder is not defined error when running `App.test.tsx` and using Kubernetes plugin

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#19925]
### 📜 Description

When we upgraded to the latest next release - `1.18.0-next.3` in we started to get the following error when running the `App.test.tsx` test: 

```shell
FAIL  src/App.test.tsx
  ● Test suite failed to run

    ReferenceError: TextEncoder is not defined

      14 | } from '@backstage/plugin-catalog';
      15 | import {
    > 16 |   EntityKubernetesContent,
         |                           ^
      17 |   isKubernetesAvailable,
      18 | } from '@backstage/plugin-kubernetes';
      19 |
```

We found that the solution was to add the following to our `packages/app/src/setupTests.ts` file: 

https://github.com/backstage/backstage/blob/5f7ce0d289505e26488afbee20d1446a40513ab4/packages/app/src/setupTests.ts#L25C1-L27C34

### 👍 Expected behavior

The test should pass without any errors

### 👎 Actual Behavior with Screenshots

The test fails with the following error:

```shell
FAIL  src/App.test.tsx
  ● Test suite failed to run

    ReferenceError: TextEncoder is not defined

      14 | } from '@backstage/plugin-catalog';
      15 | import {
    > 16 |   EntityKubernetesContent,
         |                           ^
      17 |   isKubernetesAvailable,
      18 | } from '@backstage/plugin-kubernetes';
      19 |
```

### 👟 Reproduction steps

1. Create a Backstage instance using the `1.18.0-next.3` next release version
2. Setup the Kubernetes plugin, only the frontend steps for this particular bug are needed but make sure to use the `0.10.3-next.3` version of the `@backstage/plugin-kubernetes` package
3. Run `yarn test`

Notice: that the `App.test.tsx` fails with the error: TextEncoder is not defined

### 📃 Provide the context for the Bug.

We were just doing our normal weekly upgrade process when the PR failed due to this test failing.

### 🖥️ Your Environment

This isn't an environment specific problem but the use of the `0.10.3-next.3` version of the `@backstage/plugin-kubernetes` package and running the `App.test.tsx` test

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Related Discord thread: https://discord.com/channels/687207715902193673/1151519926281048207

**Comment by freben** [comment]
I made https://github.com/backstage/backstage/pull/19947 to see if the other maintainers think that it's a viable approach.

**Comment by Rugvip** [comment]
Figured I'd chip in with a fix too 😅 #19953

**Comment by Rugvip** [comment]
Closing this as fixed by #19953, validated in #19970

**Comment by CptnFizzbin** [comment]
For others who have encountered this issue in 2025:

Check that you're not accidentally importing a node library into a common or front-end plugin.

**Comment by MaeIsBad** [comment]
For those who have encountered this issue late 2025/2026:

TextEncoder/Decoder are a part of the browser env([mdn](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder)) and can be used by frontend plugins. Unfortunately this API is [not implemented](https://github.com/jsdom/jsdom/issues/2524) by jsdom as of jsdom 27.2.0.
 
To fix your tests you can polyfill them yourself in setupTests.ts, for example how backstage does it in the api docs plugin

https://github.com/backstage/backstage/blob/f7aef07e509251ce3145d7f502a8e537aa0060c4/plugins/api-docs/src/setupTests.ts#L20
(note that this is not a perfect polyfill, but it should work for most cases)

The previous commenter accidentally drove me insane trying to figure out what was causing this

**Comment by ChALkeR** [comment]
Node.js implementation of TextDecoder is significantly broken, unfortunately

jsdom now ships a proper version as of version 27.4.0

**Comment by MaeIsBad** [comment]
I really wish they did that a month earlier 😅

**Comment by ChALkeR** [comment]
@MaeIsBad There was no proper TextDecoder implementation a month earlier 🙃
