### ISSUE TITLE
🐛 Bug Report: Importing userGroupMembers using Azure AD org data requires group filter 

### ISSUE THREAD

**Issue by erdebee** [backstage/backstage#19920]
### 📜 Description

I have found a bug or documentation issue with the `catalog-backend-module-msgraph` plugin. Depending on perspective.

The documentation currently does not state that a `group` filter is also required when using a `userGroupMembers` filter. 

In fact, quite the opposite is mentioned here: 
https://github.com/backstage/backstage/blob/master/docs/integrations/azure/org.md?plain=1#L138

I interpeted that when I'd use a `userGroupMembers` filter that it would import all users of 1 group by UUID. Documentation states, without using a `group` filter, this plugin should import everything. 
This is not the case however, and the code hangs without reaching completion. To make it worse, the system does not log an error but just hangs at a certain point in the code. 

I got the following log statements:
```
catalog info Reading msgraph users and groups
catalog info Read users from group membership groupCount = 1 userCount = 250
catalog debug Finished transforming users
```

But the statement `Read xx msgraph users and xx msgraph groups` is never logged. 
I suspect that the call to `resolveRelations` step in the code at 
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/src/microsoftGraph/read.ts#L421

Freezes up the plugin.

### 👍 Expected behavior

One or more of the following should be improved IMO:
Ideally:
- The resolveRelations step should work, even when no group is returned so that we can import all userGroupMembers without having to import the group

OR

- The documentation should reflect the requirement for the presence of groups in the filtered set
- The logging should indicate that no result can be produced because of missing groups

### 👎 Actual Behavior with Screenshots

Currently we do not know what we have done wrong from logging or validation of the system. This caused a lot of confusion and time waste.

- No documentation indicating the requirement of having to set a group filter
- No logging of any error or misconfiguration
- No validation of misconfiguration

### 👟 Reproduction steps

1. Setup backstage with the microsoftGraphOrg plugin, as indicated by the documentation
2. use the following configuration:
```
catalog:
  providers:
    microsoftGraphOrg:
      default:
        clientSecret: **redacted**
        tenantId: 4a2a-9bdf-15531181d65ecd-99fef8-8dec
        queryMode: basic
        userGroupMember:
          # Keep only users of MS Teams Group "Foo Bar" in backstage
          filter: "id eq '4a9e-a0c3-75a79c4ff7af-9d2b8df5'"
```
3. this will indicate that all XX group members have been found, but it will not actually import them.
4. Now apply the following configuration instead, to see it working:
```
catalog:
  providers:
    microsoftGraphOrg:
      default:
        clientSecret: **redacted**
        tenantId: 4a2a-9bdf-15531181d65ecd-99fef8-8dec
        queryMode: basic
        group:
          filter: "id eq '4a9e-a0c3-75a79c4ff7af-9d2b8df5'"
        userGroupMember:
          # Keep only users of MS Teams Group "Foo Bar" in backstage
          filter: "id eq '4a9e-a0c3-75a79c4ff7af-9d2b8df5'"
```

### 📃 Provide the context for the Bug.

We have wasted alot of time trying to find why our members would not be imported. The logging and documentation does not help.

### 🖥️ Your Environment

OS:   Darwin 22.5.0 - darwin/x64
node: v18.16.1
yarn: 1.22.19
cli:  0.22.12 (installed)
backstage:  1.17.4

Dependencies:
  @backstage/app-defaults                          1.4.2
  @backstage/backend-app-api                       0.4.5, 0.5.2
  @backstage/backend-common                        0.18.5, 0.19.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-openapi-utils                 0.0.3
  @backstage/backend-plugin-api                    0.5.4, 0.6.2
  @backstage/backend-tasks                         0.5.7
  @backstage/catalog-client                        1.4.3
  @backstage/catalog-model                         1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.3
  @backstage/cli                                   0.22.12
  @backstage/config-loader                         1.4.0
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.9.1
  @backstage/core-components                       0.11.2, 0.12.5, 0.13.4
  @backstage/core-plugin-api                       1.5.3
  @backstage/dev-utils                             1.0.20
  @backstage/errors                                1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.5
  @backstage/integration-react                     1.1.18
  @backstage/integration                           1.6.2
  @backstage/plugin-adr-backend                    0.3.8
  @backstage/plugin-adr-common                     0.2.14
  @backstage/plugin-adr                            0.6.6
  @backstage/plugin-api-docs                       0.9.10
  @backstage/plugin-app-backend                    0.3.50
  @backstage/plugin-app-node                       0.1.2
  @backstage/plugin-auth-backend                   0.18.8
  @backstage/plugin-auth-node                      0.2.19
  @backstage/plugin-azure-devops-backend           0.3.29
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.3.5
  @backstage/plugin-catalog-backend-module-github  0.3.6
  @backstage/plugin-catalog-backend-module-ldap    0.5.17
  @backstage/plugin-catalog-backend-module-msgraph 0.5.9
  @backstage/plugin-catalog-backend                1.12.4
  @backstage/plugin-catalog-common                 1.0.15
  @backstage/plugin-catalog-graph                  0.2.35
  @backstage/plugin-catalog-import                 0.9.13
  @backstage/plugin-catalog-node                   1.4.3
  @backstage/plugin-catalog-react                  1.8.3
  @backstage/plugin-catalog                        1.12.4
  @backstage/plugin-events-node                    0.2.11
  @backstage/plugin-home-react                     0.1.2
  @backstage/plugin-home                           0.4.32
  @backstage/plugin-kubernetes-backend             0.11.5
  @backstage/plugin-kubernetes-common              0.6.5
  @backstage/plugin-kubernetes                     0.10.2
  @backstage/plugin-org                            0.6.13
  @backstage/plugin-pagerduty                      0.6.4
  @backstage/plugin-permission-common              0.7.7
  @backstage/plugin-permission-node                0.7.13
  @backstage/plugin-permission-react               0.4.14
  @backstage/plugin-proxy-backend                  0.3.2
  @backstage/plugin-scaffolder-backend             1.16.4
  @backstage/plugin-scaffolder-common              1.4.0
  @backstage/plugin-scaffolder-node                0.2.2
  @backstage/plugin-scaffolder-react               1.5.4
  @backstage/plugin-scaffolder                     1.14.4
  @backstage/plugin-search-backend-module-catalog  0.1.6
  @backstage/plugin-search-backend-module-pg       0.5.11
  @backstage/plugin-search-backend-module-techdocs 0.1.6
  @backstage/plugin-search-backend-node            1.2.6
  @backstage/plugin-search-backend                 1.4.2
  @backstage/plugin-search-common                  1.2.5
  @backstage/plugin-search-react                   1.6.4
  @backstage/plugin-search                         1.3.6
  @backstage/plugin-sentry                         0.5.8
  @backstage/plugin-sonarqube-react                0.1.7
  @backstage/plugin-sonarqube                      0.7.4
  @backstage/plugin-tech-radar                     0.6.7
  @backstage/plugin-techdocs-backend               1.6.7
  @backstage/plugin-techdocs-module-addons-contrib 1.0.18
  @backstage/plugin-techdocs-node                  1.7.6
  @backstage/plugin-techdocs-react                 1.1.9
  @backstage/plugin-techdocs                       1.6.8
  @backstage/plugin-user-settings                  0.7.8
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.2
  @backstage/theme                                 0.2.19, 0.4.1
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
✨  Done in 1.69s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by hntrdglss** [comment]
Hey @afscrome! As a recent contributor to that section of the docs, would you mind taking a look at this?

**Comment by afscrome** [comment]
`group.filter` (or `group.search`) is not required.  That said, I would strongly recommend providing them, (or not ingesting groups at all by providing a dummy filter).   My experience is that whilst active directory users are usually a good data source groups are often a total mess.

When you don't provide a filter or search pattern for groups, backstage will load all groups in your company.  For each group, it'll then load the members of the groups to work out which groups to assign.  For any non trivial directory, this is a significant amount of work.  

Based on your logs - this appears to be exactly what has happened.  Backstage has read all the users, and has now started groups.  The group ingestion has neither finished, nor logged an error, suggesting that either:
1. The group ingestion is still running due to the volume of data
2. The schedule's timeout was configured too low, meaning the scheduler kills the job before it can complete

For reference, a previous company only had 20k groups, and that ingestion process could not complete when left overnight.  I'm sure there's a lot of performance work that could be done to improve the group & membership side of the ingestion, however neither of the companies I've worked at have had anywhere a quality enough active directory that we decided to get group membership from other data sources, so it's not an area I've looked at in much detail.

The `group` filters are distinct `userGroupMembers` as the two aren't necessarily the same.  e.g. you may only want to load users from the `Backstage Users` group, but you will still want to import their organisational membership (e.g. import that Jane is a member of the "Engineering" and "Payments Team" groups)

The docs do mention this issue, although the gotchas with group ingestion could do with being highlighted better.
