### ISSUE TITLE
🐛 Bug Report: NotFoundPage redirects to external URL (OWASP)

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#19935]
### 📜 Description

The application does not verify URL values taken from the request properly when assigning it to the "GO BACK" link. This allows an attacker to redirect users to an arbitrary url.

### 👍 Expected behavior

The go back link redirects to the root of the application

### 👎 Actual Behavior with Screenshots

The go back link redirects to url in path, in the reproduction steps this would be www.google.com

### 👟 Reproduction steps

1. Go to https://demo.backstage.io///www.google.com
2. Click the "Go back" link in the not found page

### 📃 Provide the context for the Bug.

https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html

### 🖥️ Your Environment

OS:   Darwin 22.6.0 - darwin/arm64
node: v18.15.0
yarn: 1.22.19
cli:  0.22.12 (installed)
backstage:  1.17.5

Dependencies:
  @backstage/app-defaults                                            1.4.2
  @backstage/backend-app-api                                         0.4.5, 0.5.2
  @backstage/backend-common                                          0.17.0, 0.18.5, 0.19.4
  @backstage/backend-dev-utils                                       0.1.1
  @backstage/backend-openapi-utils                                   0.0.3
  @backstage/backend-plugin-api                                      0.5.4, 0.6.2
  @backstage/backend-tasks                                           0.5.7
  @backstage/backend-test-utils                                      0.2.2
  @backstage/catalog-client                                          1.4.3
  @backstage/catalog-model                                           1.4.1
  @backstage/cli-common                                              0.1.12
  @backstage/cli-node                                                0.1.3
  @backstage/cli                                                     0.22.12
  @backstage/config-loader                                           1.4.0
  @backstage/config                                                  1.0.8
  @backstage/core-app-api                                            1.9.1
  @backstage/core-components                                         0.12.5, 0.13.4
  @backstage/core-plugin-api                                         1.5.3
  @backstage/dev-utils                                               1.0.20
  @backstage/errors                                                  1.2.1
  @backstage/eslint-plugin                                           0.1.3
  @backstage/integration-aws-node                                    0.1.5
  @backstage/integration-react                                       1.1.18
  @backstage/integration                                             1.6.0, 1.6.2
  @backstage/plugin-api-docs                                         0.9.10
  @backstage/plugin-app-backend                                      0.3.50
  @backstage/plugin-app-node                                         0.1.2
  @backstage/plugin-auth-backend                                     0.18.8
  @backstage/plugin-auth-node                                        0.2.19
  @backstage/plugin-catalog-backend-module-aws                       0.2.5
  @backstage/plugin-catalog-backend-module-bitbucket-server          0.1.15
  @backstage/plugin-catalog-backend-module-msgraph                   0.5.9
  @backstage/plugin-catalog-backend-module-unprocessed               0.2.2
  @backstage/plugin-catalog-backend                                  1.12.4
  @backstage/plugin-catalog-common                                   1.0.15
  @backstage/plugin-catalog-graph                                    0.2.35
  @backstage/plugin-catalog-node                                     1.4.3
  @backstage/plugin-catalog-react                                    1.8.1, 1.8.3
  @backstage/plugin-catalog-unprocessed-entities                     0.1.2
  @backstage/plugin-catalog                                          1.12.4
  @backstage/plugin-devtools-backend                                 0.1.5
  @backstage/plugin-devtools-common                                  0.1.3
  @backstage/plugin-devtools                                         0.1.3
  @backstage/plugin-entity-feedback-backend                          0.1.8
  @backstage/plugin-entity-feedback-common                           0.1.2
  @backstage/plugin-entity-feedback                                  0.2.6
  @backstage/plugin-events-node                                      0.2.11
  @backstage/plugin-github-actions                                   0.6.4
  @backstage/plugin-home-react                                       0.1.2
  @backstage/plugin-home                                             0.5.7
  @backstage/plugin-jenkins-backend                                  0.2.5
  @backstage/plugin-jenkins-common                                   0.1.18
  @backstage/plugin-jenkins                                          0.8.5
  @backstage/plugin-kubernetes-common                                0.6.5
  @backstage/plugin-microsoft-calendar                               0.1.6
  @backstage/plugin-org                                              0.6.13
  @backstage/plugin-permission-backend                               0.5.25
  @backstage/plugin-permission-common                                0.7.7
  @backstage/plugin-permission-node                                  0.7.13
  @backstage/plugin-permission-react                                 0.4.14
  @backstage/plugin-proxy-backend                                    0.3.2
  @backstage/plugin-scaffolder-backend-module-confluence-to-markdown 0.2.3
  @backstage/plugin-scaffolder-backend-module-cookiecutter           0.2.26
  @backstage/plugin-scaffolder-backend                               1.16.5
  @backstage/plugin-scaffolder-common                                1.4.0
  @backstage/plugin-scaffolder-node                                  0.2.2
  @backstage/plugin-scaffolder-react                                 1.5.4
  @backstage/plugin-scaffolder                                       1.14.4
  @backstage/plugin-search-backend-module-catalog                    0.1.6
  @backstage/plugin-search-backend-module-elasticsearch              1.3.5
  @backstage/plugin-search-backend-module-pg                         0.5.11
  @backstage/plugin-search-backend-module-techdocs                   0.1.6
  @backstage/plugin-search-backend-node                              1.2.6
  @backstage/plugin-search-backend                                   1.4.2
  @backstage/plugin-search-common                                    1.2.5
  @backstage/plugin-search-react                                     1.6.3, 1.6.4
  @backstage/plugin-search                                           1.3.6
  @backstage/plugin-sonarqube-backend                                0.2.4
  @backstage/plugin-sonarqube-react                                  0.1.7
  @backstage/plugin-sonarqube                                        0.7.4
  @backstage/plugin-techdocs-backend                                 1.6.7
  @backstage/plugin-techdocs-module-addons-contrib                   1.0.18
  @backstage/plugin-techdocs-node                                    1.7.6
  @backstage/plugin-techdocs-react                                   1.1.9
  @backstage/plugin-techdocs                                         1.6.8
  @backstage/plugin-user-settings                                    0.7.8
  @backstage/release-manifests                                       0.0.9
  @backstage/test-utils                                              1.4.2
  @backstage/theme                                                   0.2.19, 0.4.1
  @backstage/types                                                   1.1.0
  @backstage/version-bridge                                          1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
Probably easiest fix would be to just use `history.back()` in the `onClick` handler

**Comment by freben** [comment]
But now I'm wondering ... why doesn't `useNavigate()(-1)` work as expected? :) https://github.com/backstage/backstage/blob/b6b04d84f850675f482f51270b61059b11eaa887/packages/core-components/src/layout/ErrorPage/ErrorPage.tsx#L88

**Comment by drodil** [comment]
That's a good question :D Would it make sense to repost this report to react router?
