### ISSUE TITLE
🚀 Feature: I want to modify EntityJenkinsContent Table column

### ISSUE THREAD

**Issue by Abhay-soni-developer** [backstage/backstage#19950]
### 🔖 Feature description

Extended EntityJenkinsContent Table to support passing of columns as props

### 🎤 Context

in my use-case i want to build duration and timestamp too in EntityJenkinsContent table.

### ✌️ Possible Implementation

we can pass down a prop by name column to modify the table columns to show or modify the data as per our requirement.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Abhay-soni-developer** [comment]
@NishkarshRaj  @jhaals  @awanlin 
Here is the PR to resolve this issue 
https://github.com/backstage/backstage/pull/19951

**Comment by benjdlambert** [comment]
Can we close this issue @Abhay-soni-developer?
