### ISSUE TITLE
🐛 Bug Report: DevTools exposes proxy-backend settigns

### ISSUE THREAD

**Issue by dweber019** [backstage/backstage#19966]
### 📜 Description

In change https://github.com/backstage/backstage/commit/7daf65bfcfa1be447d9a48bd1c935e5227dcc06c proxies have been moved to `endpoints`. With the change the deprecated method to define proxies like this
```
proxy:
    '/proxy1':
      target: https://xxx
      headers:
        Authorization:
          $env: TOKEN
```
The token is exposed as the https://github.com/backstage/backstage/blob/7daf65bfcfa1be447d9a48bd1c935e5227dcc06c/plugins/proxy-backend/config.d.ts#L34 only protects secrets under `endpoints`.

FYI @Rugvip @awanlin 

### 👍 Expected behavior

Protect all available methods.

### 👎 Actual Behavior with Screenshots

Deprecated config is not protected anymore.

### 👟 Reproduction steps

Use example above.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
@awanlin what do you think about locking down backend reading in the devtools plugin to a set of configured admins, or something along those lines? I don't feel that marking config visibility is something we should rely on for security, it's not what it was intended for.

**Comment by awanlin** [comment]
Hi @Rugvip, yes I'm open to that. We do have the permission framework setup for plugin and for this specific features but clearly adopters need to implement it. Also, just for clarity the idea of an Admin came up in this PR https://github.com/backstage/backstage/pull/17711 and it wasn't something the maintainers wanted or were ready for. I'm assuming that's no longer the case?

I had two possible solutions come to mind for this:

1. We could add an admin array to the DevTools config, could use an `entityRef` and then use that with the current user
2. We could maybe force the permissions to be on for this endpoint for it to work, not sure how to do this but I feel like it must be possible

**Comment by freben** [comment]
Does this make sense in the mean time? https://github.com/backstage/backstage/pull/20011
