### ISSUE TITLE
🚀 Feature: Support Gitea in TechDocs

### ISSUE THREAD

**Issue by mecseid** [backstage/backstage#19960]
### 🔖 Feature description

It would be nice if TechDocs supports Gitea as a source code hosting provider.

Based on https://github.com/backstage/backstage/issues/13873 and https://github.com/backstage/backstage/issues/13873#issuecomment-1362647171 it should work, but at the moment it throws an error that `GiteaUrlReader` does not implement `readTree`.

As far as I know, Gitea API is mostly based on Github, so maybe the implementation will be straightforward.
(I don't know what else is missing to make it work.)

### 🎤 Context

With Gitea support in TechDocs, the users can read and update their tech documentation without checkout the repository and write the mkdocs manually.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Hey, I took the liberty of removing the TechDocs specific label on this. Implementing `readTree` in that reader will benefit everybody, not just TechDocs! So, come to think of it, adding a help wanted label too.

**Comment by mecseid** [comment]
I think we can close this issue as it resolved by #20214
