### ISSUE TITLE
🐛 Bug Report: cannot use custom reporters for tests

### ISSUE THREAD

**Issue by ypetrych** [backstage/backstage#19967]
### 📜 Description

In case of usage of custom reporter for tests it fails with the error: 

`Error: Could not resolve a module for a custom reporter.`

### 👍 Expected behavior

Reporters can be used with `backstage-cli repo test`

### 👎 Actual Behavior with Screenshots

<img width="545" alt="image" src="https://github.com/backstage/backstage/assets/36443694/13ab8fc2-908c-46c1-b8c3-ca15449bfa8f">

### 👟 Reproduction steps

1. Add custom reporter for jest
2. Call tests like this: `backstage-cli repo test --coverage --reporters=./reporters`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Hey! You may want to try using an absolute path for the reporter argument. Let us know how it goes.

**Comment by benjdlambert** [comment]
@ypetrych Did this work? :pray:
