### ISSUE TITLE
🚀 Feature: Language selector

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#19972]
### 🔖 Feature description

It would be awesome to have the ability to switch languages now that there is support for them

### 🎤 Context

There may be cases where someone may wish to work using a language that might be different from the default:

- As a Canadien I might want to have use Backstage in French instead of English
- As a Belgian I might want to use Flemish instead of French
- etc.

Having a language selector would allow this

### ✌️ Possible Implementation

This could be a drop down listing all the available languages and the user can just select the one they want. This would probably go in the setting section.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
There is one :grin: https://github.com/backstage/backstage/blob/01a723498ded830565c0fa85547ce3257039256c/plugins/user-settings/src/components/General/UserSettingsLanguageToggle.tsx#L86

**Comment by awanlin** [comment]
Awesome, guess I should look at that PR more closely 👀
