### ISSUE TITLE
🚀 Feature: Include AWS account status in the AwsOrganizationCloudAccount Processor

### ISSUE THREAD

**Issue by rikez** [backstage/backstage#19975]
### 🔖 Feature description

The AWS Account entity in Backstage provides essential information about AWS accounts. However, it would be nice if it also included the account status. The [AwsOrganizationCloudAccountProcessor](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-aws/src/processors/AwsOrganizationCloudAccountProcessor.ts#L145C34-L145C46) utilizes the AWS listAccount API which already returns the [account status as part of this response](https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListAccounts.html).

### 🎤 Context

Before full deletion, AWS accounts get in `suspended` and `pending closure` state. Consequently, it is difficult to track these in the catalog. It would be nice if we could visualize these statuses in the catalog to efficiently track our AWS accounts.

### ✌️ Possible Implementation

If we proceed with the change, where do you think this should be stored?
* metadata.labels
* metadata.tags
* metadata.annotations 
* spec

```TypeScript
private mapAccountToComponent(account: Account): ResourceEntityV1alpha1 {
    ...
    return {
      apiVersion: 'backstage.io/v1alpha1',
      kind: 'Resource',
      metadata: {
        annotations: {
          [ACCOUNTID_ANNOTATION]: accountId,
          [ARN_ANNOTATION]: account.Arn || '',
          [ORGANIZATION_ANNOTATION]: organizationId,
        },
        labels: {
          [ACCOUNT_STATUS_LABEL]: this.normalizeAccountStatus(account.Status) // active, suspended, pending_closure
        }
        name: this.normalizeName(account.Name || ''),
        namespace: 'default',
      },
      spec: {
        type: 'cloud-account',
        owner: 'unknown',
      },
    };
  }
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by rikez** [comment]
@benjdlambert Thanks for reviewing this. I'm going to open a PR to include it then.

**Comment by benjdlambert** [comment]
@rikez Did you manage to get anywhere with this?

**Comment by raduciopraga** [comment]
Would it make sense to add the AWS account e-mail to the `metadata.labels` and the account name as `metadata.title` with this issue? The information is already in the `Account` object.

**Comment by benjdlambert** [comment]
@raduciopraga I don't know how far @rikez got with this, maybe it's up to you if you want to go ahead an implement something like this and whip up a PR?
