### ISSUE TITLE
🚀 Feature: Changelog link to PR or commit

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#19973]
### 🔖 Feature description

It would be really handy if the entries in the Changelogs could link to the related PR or commit so that way if you wanted to know more about something it would be quick to get to the information

### 🎤 Context

As someone who upgrades regularly and from time to time wants to know more about a change, maybe it's not clear how a new prop works being able to jump to the PR is super handy or if not even the commit would be great.

### ✌️ Possible Implementation

I'm not sure exactly how but looking over issues in the https://github.com/changesets/changesets repo it's clearly possible I'm just not finding the exact config to do this.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Sounds like a great contribution if someone finds out how!

**Comment by angeliski** [comment]
I tried @awanlin help me find how to test this 😅
