### ISSUE TITLE
🚀 Feature: make vault plugin support multiple vault server configurations

### ISSUE THREAD

**Issue by ikatlinsky** [backstage/backstage#19990]
### 🔖 Feature description

Currently, the vault plugin supports the configuration of only single vault servers, which is quite limited. Plugin configuration and logic should be updated to allow integration with multiple vault servers.

### 🎤 Context

In many cases, projects and applications use different vault servers for different environments: dev, stage, prod etc. In such scenarios, the plugin is very limited and does not allow the assignment of different catalogue entities to existing vault servers.

### ✌️ Possible Implementation

In terms of the catalog entity configuration proposal is to add a new annotation: `vault.io/secrets-server`, which can be applied in the following way:

```diff
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-lookup
  description: Artist Lookup
  annotations:
    backstage.io/linguist: 'https://github.com/backstage/backstage/tree/master/plugins/playlist'
    vault.io/secrets-path: path
    vault.io/secrets-engine: engine
+   vault.io/secrets-server: stg
```

In terms of backend configuration, there are two options:

- backwards compatible 
- breaking change

**Backward compatible**

```diff
vault:
  baseUrl: url
  token: token
  secretEngine: secrets
+  additionalServers:
+    stg:
+      baseUrl: url
+      token: token
+      secretEngine: secrets
+    prod:
+      baseUrl: url
+      token: token
+      secretEngine: secrets
```

In this approach `vault.{baseUrl, token, secretEngine}` will be used as a default setting, and `additionalServers` will be used in case the catalogue entity is marked with the annotation.

**Breaking changes**

In this option, we should completely replace the current configuration in the following way

```diff
vault:
-  baseUrl: url
-  token: token
-  secretEngine: secrets
+  stg:
+    baseUrl: url
+    token: token
+    secretEngine: secrets
+    default: true
+  prod:
+    baseUrl: url
+    token: token
+    secretEngine: secrets
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ikatlinsky** [comment]
@freben hi, can you please look at the proposal?

**Comment by ikatlinsky** [comment]
@vinzscam @freben sorry for pinging, would be glad to hear some opinions on this ticket, thanks

**Comment by freben** [comment]
There's a middle ground like we did for the proxy: https://github.com/backstage/backstage/pull/18915/files . Treating the old keys as deprecated basically, and just hoping that nobody tries to make a server with the ID `baseUrl`.

I'm wondering though. You aren't meant to have multiple entities for multiple envs; that's an antipattern. So I'm not sure how you'd best leverage this config change in a sensible way.

**Comment by ikatlinsky** [comment]
I see the problems here, after looking closely it looks like a better solution is to create our own plugin based on the current one. In our case we have
- multiple vault clusters
- single entity can be linked to multiple secrets from multiple different vault clusters

It will take quite a time to make needed updates directly backstage, and it will not be backwards compatible in any case.

I am closing the issue for now, in case we will produce something generic, i will come back with a PR, thanks

**Comment by JonJam** [comment]
My company also has the same setup as yourself @ikatlinsky so if you get something working would love for you to share.

**Comment by nia-potato** [comment]
@ikatlinsky we also have the same problem, please let us know if there were any updates, thanks.
