### ISSUE TITLE
🐛 Bug Report: Cannot Install Backstage On Node 20

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#20001]
### 📜 Description

Installing yarn/npm dependencies fails due to an engine compatibility check from the transitive dependency `@azure/msal-node`

### 👍 Expected behavior

Installation should succeed

### 👎 Actual Behavior with Screenshots

Installation fails due to a few reasons:

1. The package.json created for backstage projects using the create-app script needs to specify node v20 as a supported engine runtime.
2. @backstage/integration -> @azure/identity -> @azure/msal-node dependency currently does not allow for node v20

### 👟 Reproduction steps

1. Set node version to v20
2. Run `yarn install` in a backstage project

### 📃 Provide the context for the Bug.

```
#0 2.740 error @azure/msal-node@1.18.3: The engine "node" is incompatible with this module. Expected version "10 || 12 || 14 || 16 || 18". Got "20.6.1"
```

### 🖥️ Your Environment

NodeJS version 20.6.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by bforbis** [comment]
I did some investigation and found that the current dependencies do not yet have packages available to upgrade to which will resolve this problem. This is blocked on https://github.com/Azure/azure-sdk-for-js/issues/26886 which will release a new major version of `@azure/identity` which can then pull in the latest version of `@azure/msal-node` which then updates the NodeJS engine restriction.

The latest comments there says that this new package will likely be released in either October / November.

**Comment by awanlin** [comment]
Just some related items:

- Node 20 isn't active LTS yet so isn't supported officially: https://backstage.io/docs/overview/versioning-policy#nodejs-releases
- Preparing to support Node 18 + 20 has started here: https://github.com/backstage/backstage/pull/19565

**Comment by bforbis** [comment]
Thanks for clarifying the versioning policy @awanlin . Will close this ticket now. That linked PR will need to wait to resolve the dependency on `@azure/identity`, so will drop a comment in there.

**Comment by awanlin** [comment]
Or maybe just change the title to the fact that `@azure/msal-node` would block Node 20 support?

**Comment by awanlin** [comment]
Going to re-open this until we have a proper solution as this has come up a few times on Discord: https://discord.com/channels/687207715902193673/1167075428679299103

**Comment by awanlin** [comment]
Based on my digging you currently have two options:

1. Use Node 18 for the time being
2. Add a resolutions entry in your `package.json` to use the current v4 beta of the `@azure/identity` package

I'm basing this off of this comment: https://github.com/Azure/azure-sdk-for-js/issues/26886#issuecomment-1767407851

**Comment by bforbis** [comment]
I see this issue is related

https://github.com/backstage/backstage/issues/20881

**Comment by wanisfahmyDE** [comment]
`@azure/identity` v4 is now released but i still needed to add a resolution in the package.json to make it run against node 20. running on backstage 1.20.3

**Comment by camilaibs** [comment]
Closing this as the package dependency was bumped to V4: https://github.com/backstage/backstage/blob/master/packages/integration/package.json#L36
