### ISSUE TITLE
🐛 Bug Report: Super tiny, but logo192.png doesn't exist

### ISSUE THREAD

**Issue by adamdavis40208** [backstage/backstage#20000]
### 📜 Description

https://github.com/backstage/backstage/blob/f4abd00ac2137aaac6be25b81a8b9731d0e73305/packages/app/public/index.html#L11-L27

There's a logo192.png specified, with a ref of apple-touch-icon (which 404s) and there's a duplicate apple-touch-icon ref just below it that is set correctly

### 👍 Expected behavior

No 404s, just trying to clean up backstage logs a bit on our side and noticed this was in the upstream as well

### 👎 Actual Behavior with Screenshots

404s,  I don't really need to add a screenshot do I :P 

### 👟 Reproduction steps

Spin up backstage
Look at logs 👀 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Thank you for reporting! Figured it makes sense to simply remove, fixed over in #20072
