### ISSUE TITLE
🚀 Feature: Create a Jira ticket from a Techdoc

### ISSUE THREAD

**Issue by kurtaking** [backstage/backstage#20005]
### 🔖 Feature description

A TechDoc addon that allows users to create Jira issues. This functionality currently exists for GitHub and GitLab via the `<ReportIssue />` [component](https://backstage.io/docs/reference/plugin-techdocs-module-addons-contrib.reportissue).

### 🎤 Context

_How can we make it easier for our users to provide faster feedback on outdated documentation? How can we hold owning teams accountable for keeping the documentation updated?_

In my use case, we do not use GitHub Issues. We instead use Jira. Creating tickets directly from the documentation, similar to how `<ReportIssue />` creates GitHub issues, would be a huge value add. 

### ✌️ Possible Implementation

Our catalog processor adds a `company.com/jira-project-key` annotation to every group entity. In this example, we could query the group entity based on the owner of the documentation. From there, you can have a Jira client that can create issues with your organization.

I would first explore leveraging the existing functionality in `<ReportIssue />`. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by wss-ycabrera** [comment]
I wonder if it is also possible to do it with Azure DevOps.

**Comment by efenner-cambia** [comment]
I would be interested in this too

**Comment by efenner-cambia** [comment]
Still interested in this. Having a component for easy creation of Jira issues could be useful beyond just TechDocs. Not sure if it would be the same plugin, but I can see use cases for creating issues straight from the main catalog page for a component, and from a scaffolder template too

**Comment by efenner-cambia** [comment]
bump

**Comment by alexlorenzi** [comment]
Hey @efenner-cambia 

Are you looking to create a Jira ticket for TechDoc pages, or catalog entities in general? The original feature request is related to the TechDocs Addon feature, but if you're looking for something on the entity page, it might be better to create a new feature request and tag Catalog since it's a bit out of the scope of TechDocs in that case.
