### ISSUE TITLE
🐛 Bug Report: "Invalid URL" Error in plugin-api-docs (swagger ui) when schema is present in OpenAPI spec

### ISSUE THREAD

**Issue by DomKal11** [backstage/backstage#20017]
### 📜 Description

Hi,  
I have encountered an issue with the `@backstage/plugin-api-docs` package (version 0.9.10) in conjunction with the `swagger-ui-react` package.  
   
Due to some changes in `swagger-ui`, using the mentioned version of `@backstage/plugin-api-docs` causes errors when a schema is present in the OpenAPI specification.
   
This issue seems to be associated with a known bug in `swagger-ui` (https://github.com/swagger-api/swagger-ui/issues/9215). The recommended solution is to reinstall the `swagger-ui-react` npm module as outlined in this comment: https://github.com/swagger-api/swagger-ui/issues/9215#issuecomment-1723065278.  
   
In the context of `@backstage/plugin-api-docs`, it appears that the package will need to be updated to point to a newer version of `swagger-ui-react` to function correctly when a schema is present.  
   
For reference, I am currently on Backstage version 1.17.5 and the version of `swagger-ui-react` in `@backstage/plugin-api-docs` is 5.0.0.  - [here](https://github.com/backstage/backstage/blob/master/plugins/api-docs/package.json#L52).
   
As a temporary solution, I was able to pin the version locally using resolutions in my package.json, which resolved the issue:  
   
```json  
"resolutions": {  
  "swagger-ui-react": "5.7.2"  
}  
```   
   
Thank you for your attention to this matter.  

### 👍 Expected behavior

This issue is to request an update of the `swagger-ui-react` version in `@backstage/plugin-api-docs` to prevent this issue for other users.  

### 👎 Actual Behavior with Screenshots

 The errors are depicted in the attached image.  
<img src="https://github.com/backstage/backstage/assets/77433173/fb8f84b4-3f3e-4443-94bd-25b97f9710aa" data-canonical-src="https://github.com/backstage/backstage/assets/77433173/fb8f84b4-3f3e-4443-94bd-25b97f9710aa" height="250" />

### 👟 Reproduction steps

API definition tab - collapse the swagger endpoint (having scheme present). It'll show the error mentioned above (printscreen).

### 🖥️ Your Environment
I am currently on Backstage version 1.17.5 and the version of swagger-ui-react in @backstage/plugin-api-docs is 5.0.0.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@DomKal11 is this something you want to contribute?

**Comment by DomKal11** [comment]
@benjdlambert Hi Ben, sure, I would like to. I think bumping the swagger-ui-react in plugin-api-docs would be the easiest way to fix this https://github.com/backstage/backstage/blob/master/plugins/api-docs/package.json#L54

I'll look into it, primarily to check the backward compatibility.

**Comment by camilaibs** [comment]
Hi @DomKal11, we assigned the issue to you.
Do you still be able to check it out 🙂?

**Comment by DomKal11** [comment]
@camilaibs Hi Camila, sure. Sorry for the delay, I didn't notice you answered. I'll look into it :-) Thanks

**Comment by DomKal11** [comment]
This is no longer relevant, as the latest version of plugin-api-docs does not exhibit these issues. I've tested it both locally and on my project's development environment. The package manager will install swagger-ui-react@5.9.2, which works well. The schema in the API's spec path is also being rendered correctly on Backstage's definition tab.
