### ISSUE TITLE
🐛 Bug Report: workflowInputs of github:actions:dispatch returning 'Unexpected inputs provided'

### ISSUE THREAD

**Issue by hs14428** [backstage/backstage#20023]
### 📜 Description

Hi all,

I am trying to use the github:actions:dispatch step, with workflowInputs, in a software template I have written to trigger a GitHub Actions workflow and I am getting hit with the "Unexpected inputs provided" error.

I have looked at the action example for workflowInputs [here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/githubActionsDispatch.examples.ts#L48), and as far as I can tell, I just need to pass a key value pair and it should pass it to the GitHub Actions workflow file.

### 👍 Expected behavior

Values submitted from software template frontend form are substituted into the GitHub Actions workflow yaml and the workflow triggers the steps with the values taken from backstage frontend.

### 👎 Actual Behavior with Screenshots

Template task activity is failing with the following error:
Unexpected inputs provided: ["instanceName", "projectId", "deploymentRegion", "deploymentZone", "instanceMachineType", "deploymentEnvironment", "instanceDiskOS", "instanceDiskSize"]
![image](https://github.com/backstage/backstage/assets/57953964/031a20f2-7c5b-4cf6-ad96-f1d60956c0c0)

### 👟 Reproduction steps

Triggered via create a new component page on backstage, filling in the parameters as you would, and submitting the form, and the workflow fails on the trigger-github-actions step

### Snippet of template file:

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: google-compute-engine-template-actions
  title: GCP Compute Engine via Github Actions backstage action
  description: Spin up a GCP Compute Engine instance
  tags:
    - gcp
    - compute
    - gh-actions
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Instance Name
      required:
        - instanceName
      properties:
        instanceName:
          title: Enter GCE Instance Name
          type: string
          description: The name of the instance. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)
          ui:options:
            rows: 5
etc..
....
  steps:
   ....
   ....

    - id: trigger-github-actions
      name: Trigger github actions workflow
      if: ${{ parameters.deploymentEnvironment == 'dev' or parameters.deploymentEnvironment == 'test' }}
      action: github:actions:dispatch
      input:
        repoUrl: ${{ parameters.repoUrl }}
        workflowId: gce_workflow.yaml
        branchOrTagName: master
        workflowInputs:
          instanceName: ${{ parameters.instanceName }}
          projectId: ${{ parameters.projectId }}
          deploymentRegion: ${{ parameters.deploymentRegion }}
          deploymentZone: ${{ parameters.deploymentZone }}
          instanceMachineType: ${{ parameters.instanceMachineType }}
          deploymentEnvironment: ${{ parameters.deploymentEnvironment }}
          instanceDiskOS: ${{ parameters.instanceDiskOS }}
          instanceDiskSize: ${{ parameters.instanceDiskSize }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}

In the GitHub Actions workflow file, I have tried accessing the parameters from the backstage frontend with "${{ values.projectId }}" and "${{ vars.projectId }}", but I am not sure it's even getting to that stage, so unsure which is the correct syntax at the moment.

### 🖥️ Your Environment

OS:   Darwin 21.6.0 - darwin/arm64
node: v18.17.1
yarn: 1.22.19
cli:  0.21.1 (installed)
backstage:  1.8.0

I know my backstage version is a little bit behind, but I tried in v1.16 as well and received the same error.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by vinzscam** [comment]
It looks like the issue was thrown by github. I would recommend to check whether the inputs match what the workflow is expecting
