### ISSUE TITLE
🔌 Plugin:  Kafka Plugin Error Message Customization

### ISSUE THREAD

**Issue by MasthanSK121** [backstage/backstage#20033]
### 🔖 Summary

This is for customising the error message for Kafka Plugin. 
When user is opened the component and navigates to the kafka tab and selects the invalid consumer group from the instance drop down. it is showing the message like "No records to display". From the user experience perspective need to show the message like "Please enter a valid instance and try again" instead of "No records to display".

### ✌️ Context

For Kafka Plugin the message is not clear for invalid data. 
Suppose when user is created a new component and provided the invalid consumer group name and saved it and activated the kafka plugin.
When user is opened the component and navigates to the kafka tab and selects the consumer group from the instance drop down. it is showing the message like "No records to display". From the user experience perspective need to show the message like "Please enter a valid instance and try again".
So is there any way to provide our own message.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by MasthanSK121** [comment]
Hi @vinzscam , Could you please confirm , do you have any ETA for this enhancement.

**Comment by Rugvip** [comment]
@MasthanSK121 we'll be relying on community contributions in this areas, it is not scheduled to be implemented by the core maintainers. Letting you know about this as well @andrewthauer in case you have capacity

**Comment by MasthanSK121** [comment]
Thanks for the update @Rugvip.

**Comment by andrewthauer** [comment]
Are there any error messages that are being suppressed here (eg in the console or backend)? This likely comes  what `kafkajs` is both reporting and supports for detection of any non existent consumer group. My work moved away from `kafkajs` to `node-rdkafka` a long time ago so I don't have as much experience with it anymore.

As far as capacity, I personally don't have any to focus on this at the moment. However, if someone can help narrow in on the issue or a way to detect if the group is valid, I might be able to code this up reasonably quick.

**Comment by MasthanSK121** [comment]
Hi @andrewthauer ,
Currently we can see the error message like "no records to display" when the cluster name is valid and consumer group is invalid. The error message is not appropriate for this use case.
