### ISSUE TITLE
Debug Log Disclosure

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#20057]
### 📜 Description

We are try to setting up LOG_LEVEL=info for backstage for prod. But it seems to it work on node level only.

Backstage is using [winston](https://github.com/winstonjs/winston). can we set log level for whole backstage project. How can we do that.

### 👍 Expected behavior

We should able to set LOG_LEVEL project wise.

### 👎 Actual Behavior with Screenshots

We can set for Node level. i did not see any other method.

### 👟 Reproduction steps

see logs

### 🖥️ Your Environment

UAT and PROD

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
Hi! Backstage is already using `LOG_LEVEL` to globally set the log level. Here is where the root logger is initialized:

https://github.com/backstage/backstage/blob/b8467dcca38b16d3a1ae38b19ab402dade9c9c30/packages/backend-app-api/src/services/implementations/rootLogger/rootLoggerServiceFactory.ts#L36

Are you having issues with any particular plugin or?
