### ISSUE TITLE
🚀 Feature: Linguist Dashboard

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#20094]
### 🔖 Feature description

It could help get a better feel for the state of processing of Entities by Linguist if we had a dashboard showing various status details.

For example: 

![Screenshot 2023-09-21 at 1 44 22 PM](https://github.com/backstage/backstage/assets/67169551/5ef8ec0d-9e0a-46d1-aba0-b1f41a22f1f3)

This shows a table of all applicable entities and their status, the overall state of processing, the breakdown by state - pending, stale, processed. It also has the details on when the processing is scheduled to run next and the Linguist configuration being used.

Possible features not shown: being able to trigger a refresh for a given entity and also to be able to see the Language breakdown as JSON in a sidebar panel (this would be helpful for tuning the Linguist Tag Processor)

### 🎤 Context

When onboarding the Linguist plugin it's very invisible where it's at in it's processing to the end user without having to just look at all the entities. Having a dashboard to view these details would help with that as well as any future troubleshooting.

### ✌️ Possible Implementation

There would be a new route that would show a dashboard of Linguist information as described above. This could also be added as a tab in the DevTool plugin (this is how we have our internal version setup)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by andym0457** [comment]
Hey @awanlin,

I like the idea of this and would be interested in getting involved in working on this if you like? And of course if its something that the backstage owners want to get implemented?
