### ISSUE TITLE
🚀 Feature: Support for api-reports generation in create-app template

### ISSUE THREAD

**Issue by P1llus** [backstage/backstage#20106]
### 🔖 Feature description

The ability to generate API Reports as explained here:  https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#api-reports 

Currently its only available to developers that are forking the https://github.com/backstage/backstage/ github repo, however for plugin developers that might be running on their own version or even using `create-app` instead.

While the main purpose of the API docs is most likely for backstage documentation and core developers, they are quite useful and I would love to be able to easily add them for my own custom plugins as well.

This could also be useful for plugins that is hosted other places than `https://github.com/backstage/backstage/plugins`

### 🎤 Context

I would like to easily generate API reports to help me develop clean plugins, and give me an overview on the current status of exported/private/undocumented functions and types without having to set it up manually.

### ✌️ Possible Implementation

I think there are 2 ways to go about this.

1. Offering a guide on how to run api-reports when doing local plugin development outside of the backstage repository. While the output itself might be mostly useful as a doc reference, its still good to educate plugin developers about the state of their own types and functions.

2. Adding the necessary parameters and dependencies to the package.json generated with `create-app`, or even just to the template for `backstage-cli` when creating a plugin(frontend/backend)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by vinzscam** [comment]
api-reports are actually exposed through `@backstage/repo-tools` so it should be possible to run it in your Backstage application.
Usually you need to install repo-tools globally in your monorepo by running:

`yarn add -D @backstage/repo-tools`

and then you should be able to run `yarn backstage-repo-tools api-reports`.

Let us know if you have troubles
