### ISSUE TITLE
🐛 Bug Report: [@backstage/plugin-auth-node] Session scope is not persisted in OAuth response

### ISSUE THREAD

**Issue by gusevda** [backstage/backstage#20103]
### 📜 Description

In Backstage `1.18.0` on a catalog entity page when a user navigates between `CI/CD` and `PULL REQUESTS` tabs, "Login Required" popup is being triggered multiple times. This is happening because popup's `authorization_response` does not include granted scopes (for GitHub authentication provider) and, as a result, saved session does not contain information about granted scopes and will not be used for the next authorization check.

### 👍 Expected behavior

When authorization is requested for the same scopes multiple times the previously saved session should be used instead of asking a user to authorize again. It used to work like this in Backstage `1.17`.

### 👎 Actual Behavior with Screenshots

<img width="1535" alt="Screenshot 2023-09-22 at 13 08 18" src="https://github.com/backstage/backstage/assets/445309/a58281f6-ef90-43ac-9c77-df8dfc52ff0b">

### 👟 Reproduction steps

Start Backstage `1.18.0` locally, go to the [backstage component page](http://localhost:3000/catalog/default/component/backstage), navigate between `Overview`, `CI/CD`, `PULL REQUESTS` tabs multiple times and see that "Login Required" popup is being triggered every time.

### 📃 Provide the context for the Bug.

According to the [OAuthRouteHandlers implementation](https://github.com/backstage/backstage/blob/master/plugins/auth-node/src/oauth/createOAuthRouteHandlers.ts#L213-L218) if an authentication provider (GitHub in this case) does not return granted scopes the one saved in the authorization flow state should be used. But it's being persisted only in cookies but not in the web message response.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Oops! Thank you for reporting, fix for this is over in #20146, patch release of this for `0.18` in #20147

**Comment by Rugvip** [comment]
@gusevda indeed! I've updated both with that additional fix 🙏

**Comment by kunickiaj** [comment]
I've upgraded from 1.17.5 to 1.18.3 and am experiencing this issue -- are there any manual steps involved in fixing this?
