### ISSUE TITLE
🐛 Bug Report: Unnecessary Pagination Controls present on the TechDocs Page

### ISSUE THREAD

**Issue by knottAutodesk** [backstage/backstage#20118]
### 📜 Description

I'm new to Backstage, and I noticed the TechDoc Plugin was adding Pagination controls when none were necessary.

### 👍 Expected behavior

If there were greater than the pageSize number of items, we should present the pagination controls, otherwise we should not. This is how the Catalog page works.

### 👎 Actual Behavior with Screenshots

An unnecessary vertical scrollbar is presented. From https://demo.backstage.io/docs?filters%5Buser%5D=all

![TechDoc_Top](https://github.com/backstage/backstage/assets/143034967/47b8e339-fbcf-46a0-a9de-4bb0574c04e7)

![TechDoc_Bottom](https://github.com/backstage/backstage/assets/143034967/b045ccfb-e738-481a-aede-865701f79e82)

### 👟 Reproduction steps

Goto: https://demo.backstage.io/docs?filters%5Buser%5D=all
Select the Documentation page
See above

### 📃 Provide the context for the Bug.

We are adopting Backstage, and I noticed our Documentation page has the undesirable behaviour. Turns out we inherited it. Fixing upstream would help all future adopters.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by knottAutodesk** [comment]
Potential fix:
[Only show pagination controls when necessary by knottAutodesk · Pull Request #20117 · backstage/backstage](https://github.com/backstage/backstage/pull/20117)

**Comment by johnphilip283** [comment]
This issue was fixed via https://github.com/backstage/backstage/pull/20117!
