### ISSUE TITLE
🐛 Bug Report: Theme icon are broken

### ISSUE THREAD

**Issue by zcmander** [backstage/backstage#20139]
### 📜 Description

Every theme icon is the same. They used to have diffend icons next to the theme name.

### 👍 Expected behavior

If I'm not wrong these theme icons used to have different icons for each one of them, but now they are looking the same. Also, "A" in the center of the icon should indicate that the theme is automatically changes between dark and light theme depending on your OS setting, and that's not the case for light and dark themes.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/2142965/c69ccc25-386c-48bd-8c10-f2b94cdbaa65)

### 👟 Reproduction steps

1. Go to demo site: https://demo.backstage.io/settings

### 🖥️ Your Environment

The bug exists in the demo environment & locally.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
This was fixed in #20142, to be released in `1.19.0` on October 17th
