### ISSUE TITLE
🚀 Feature: [Docs] Guide for setting up and using OpenTelemetry metrics and traces

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#20155]
### 🔖 Feature description

As there are more and more metrics and traces being setup in Backstage it would be really helful to have a guide that shows you how to set up and use OpenTelemetry

### 🎤 Context

We'd like to use the metrics and traces that have been added but it feels very open as to how one would set things up and start using them

### ✌️ Possible Implementation

This could be as simple as a Contrib guide like the one for Prometheus here: https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/prometheus-metrics.md

But it would be even better if it was part of the main Documentation under the Tutorials heading here: https://github.com/backstage/backstage/tree/master/docs/tutorials

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
@awanlin thanks for raising this! Yep indeed, we should have docs around this. I'm hoping to also throw together an RFC for a `metricsApiRef` for plugins to use and promote the use of these OT metrics more, so it's looking like it's going to become pretty useful to have this indeed :tada:

**Comment by awanlin** [comment]
Oh, a `metricsApiRef` for plugins to use sounds very nice! Would be happy to help just a bit slammed these days

**Comment by GabrielSten** [comment]
I am very much interested in docs for openTelemetry and a `metricsApiRef` for plugins 🙂

**Comment by tcardonne** [comment]
@awanlin I guess this one should remain open as you requested

**Comment by awanlin** [comment]
Not stale, some updates going on here: https://github.com/backstage/backstage/pull/22648

**Comment by freben** [comment]
Fixed!
