### ISSUE TITLE
🚀 Feature: Modify Location headers in 3xx redirection response in Proxy Plugin

### ISSUE THREAD

**Issue by davyboyhayes** [backstage/backstage#20156]
### 🔖 Feature description

The Location header in the response for a 3xx redirection does not always reflect the correct location when the proxy plugin is configured with a path rewrite. When the proxy receives a 3xx response it should (by a configuration option) inspect the Location header and attempt to rewrite it back into the appropriate request the caller should make to Backstage (where the origin and path in the configured backend match the Location header).

### 🎤 Context

In my use case we have an end point which issues a 307 redirection to another resource held on the server (actually a 307 to the same resource but with a specific set of query parameters to make the request long cacheable). We have path rewrites enabled to enable us to proxy multiple backends.

Backend https://a.com proxy exposed on https://mybackstage.com/a

Outside of Backstage, when someone wants to request `https://a.com/my_api?id=last`, they would get 307'd with a Location Header of `https://a.com/my_api?id=123456`.

With Backstage, the request goes to `https://mybackstage.com/a/my_api?id=last`. The request gets proxied to `https://a.com/my_api?id=last`, which the server responds to the proxy with a Location Header of `https://a.com/my_api?id=123456`. This URL is not reachable (hence why Backstage proxy was being used).

Being able to rewrite the Location URL back into the `https://mybackstage.com/a/my_api?id=123456` format means that the browser gets to follow this redirection, and take advantage of caching `https://mybackstage.com/a/my_api?id=123456` which may have a long cache associated with it.

### ✌️ Possible Implementation

One possible solution: in [onProxyRes](https://github.com/backstage/backstage/blob/master/plugins/proxy-backend/src/service/router.ts#L180-L192), detect for redirection and Location headers, and match against the configured backend... modifying the Location Header accordingly.

Alternatively, a way for a custom function (supplied by the implementor) to call to enhance the existing onProxyRes function.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
I'm wondering if the `hostRewrite` option could help out here?

**Comment by davyboyhayes** [comment]
I'm not sure I follow. Wouldn't `hostRewrite` only be replacing `mybackstage.com` to `a.com`, and not alter the path element of the URL (i.e. from `/a/my_api` to `/my_api`)?

Or are you suggesting that `hostRewrite` could be useful in an otherwise not yet developed solution?

**Comment by Rugvip** [comment]
Ah yep didn't spot the `/a/` difference, probably a bit trickier then.

If anyone has any suggestions on a way forward, let us know 🙏
