### ISSUE TITLE
🚀 Feature: request for building a hook for starredEntities to be saved in database for cross browser data 

### ISSUE THREAD

**Issue by Priyankabm564** [backstage/backstage#20153]
### 🔖 Feature description

Hi, 

I am currently using useStarredEntities hook for accessing and updating list of my starredEntities. But as useStarredEntities hook is storing the list in the local storage in the browser, the data is not consistent accross the browser, users loose the starred data on a different browser or on clearing local storage. So I am looking for hook or a function that we can use to store the starredEntities in our database and get it from db. 

We tried to implement it, but we couldn't implement it. As we need useStarredEntities hook to get the starredEntities, we are not able find any other hook/function that we can use to get starredEntities data. 

And also there's a dependency on backstage's react component to display the users/group details in the UI, so we are not able to call our custom function onClick of starIcon from the app. So if we can get the hook from the backstage that would be helpful for maintaining data across different browsers.

Thank you.

### 🎤 Context

I my use-case, this feature would be helpful for maintaining data across different browsers. and improve User Experiance.

### ✌️ Possible Implementation

ideas may be, please implement a react hook that can accept our database and other required data from  owner and it can return starredEntities(data from db), functions that can called when user wants to add something to star or remove. and may beother required details.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
This is already supported if you use the user-settings-backend.

See the instructions here

https://github.com/backstage/backstage/tree/master/plugins/user-settings-backend

**Comment by Priyankabm564** [comment]
Hi, 

Could you please explain the exact use case of this plugin?

**Comment by Rugvip** [comment]
@Priyankabm564 the purpose of the user settings backend is exactly what you requested here. It stores settings for each user in order for them to be synchronized across browsers.

I'm going to close this since the requested feature is already implemented.
