### ISSUE TITLE
OVERFLOW BUTTON IN MOBILE VIEW

### ISSUE THREAD

**Issue by Roar022** [backstage/backstage#20187]
### 📜 Description

There is a button "OFFICE HOURS" in which content is coming out of its div/box.

### 👍 Expected behavior

The button content should be inside its box/div 

### 👎 Actual Behavior with Screenshots

Content of button is coming outside the box/div, It should be inside the box/div.
![Screenshot_2023-09-27-17-12-25-675_com android chrome](https://github.com/backstage/backstage/assets/111555339/5056de21-5092-4fcc-a6de-bfe346b0407b)

### 👟 Reproduction steps

1. Go to backstage.io
2. Scroll a little in mobile view
3. You will find button as "OFFICE HOURS" which is overflowing.
4. It's need to be fixed for good user experience.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by fedy97** [comment]
I am opening a PR for this
