### ISSUE TITLE
🚀 [TechDocs] Enhance PlantUML support in the techdocs container to include external puml or pu files

### ISSUE THREAD

**Issue by lavanya-sainik-ericsson** [backstage/backstage#20184]
### 🔖 Feature description

We wanted to add plantuml diagrams in our repo documentation using techdocs where plantUML is one of the widely used tool for software documentation.
When we started our integration with techdocs, could not found enough supporting documentation in existing guides of backstage for how to refer plantuml diagrams using techdocs-cli.

Thus we investigated on our side and provided those support and felt this enhancement can be contributed and will be useful to the community. This will help others to quickly integrate backstage techdocs features and will save time thereby give nice user readability experience by integrating diagrams from anywhere in the repo.

### 🎤 Context

PlantUMl is one of the widely used tool for software documentation. And with backstage powerful feature of techdocs, which promotes doc like code approach, its easy to have even diagrams rendered on the fly in the documentation. So with this enhancement, users can easily add embedded and referenced plantuml diagrams using techdocs-cli in techdocs.
This will help in 

- Easy Diagram rendering in techdocs which gives good readability experience.
- Saving time as with  good documentation and examples, end user don't have to invest time in research and use the 
   examples directly.
- Organized doc repo, where one can have separate repo for all plantuml diagram files.
- Increased User Experience with texts and diagrams.

### ✌️ Possible Implementation

We have done these changes and would like to contribute and appreciate if you could accept that and found useful.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @lavanya-sainik-ericsson, this would be greatly appreciated! Anything to make it easer to use TechDocs is a win in my opinion. I do have a few questions just to understand what you would like to contribute: is this just documentation, like a tutorial or is it also code changes?

For documentation this would be a good place to add a guide on using PlantUML with TechDocs: https://github.com/backstage/backstage/blob/master/docs/features/techdocs/how-to-guides.md

For code, if it's just changes to the TechDocs container that's actually in its own repo here: https://github.com/backstage/techdocs-container/blob/main/Dockerfile

Excited to see this get put in place! 🚀

**Comment by lavanya-sainik-ericsson** [comment]
Thanks [awanlin](https://github.com/awanlin) for your response. I would like to contribute at both documentation and code. First I will be sharing a PR for Code in TechDocs container and then Guide so that it can refer the updated Docker file. I will link the PR here for reference. Hope that's ok or let me know if any suggestions.

**Comment by awanlin** [comment]
That sounds great @lavanya-sainik-ericsson, feel free to ping me on the PRs as I can help review. 👍

**Comment by lavanya-sainik-ericsson** [comment]
Hey [awanlin](https://github.com/awanlin), 

As discussed yesterday, I have done changes for both code and documentation. Please have a look and let me know if I need to make any more corrections and if these changes are acceptable.

**Comment by johnphilip283** [comment]
Hey @lavanya-sainik-ericsson! Given your PRs have been merged, I'm going to close this issue for now. Please feel free to re-open if you think there are any other gaps we can address in the scope of this issue.
