### ISSUE TITLE
🐛 Bug Report: LinguistTagsProcessor Emits Warnings Everytime Backstage Starts

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#20192]
### 📜 Description

The linguist tags processor makes HTTP requests to the linguist backend, however there is a sequencing issue right now where the tags processor starts before the service starts listening for API requests, causing warnings to occur every time backstage starts.

### 👍 Expected behavior

No warnings should emit

### 👎 Actual Behavior with Screenshots

Warnings are emitted from the linguist tags processor until the service fully starts

```
[1] 2023-09-27T12:31:24.745Z catalog warn Processor LinguistTagsProcessor threw an error while preprocessing; caused by FetchError: request to http://localhost:7007/api/linguist/entity-languages?entityRef=component%3Adefault%2Feventing-subscription-service failed, reason: connect ECONNREFUSED 127.0.0.1:7007 type=plugin entity=component:default/eventing-subscription-service location=file:/Users/bforbis/athena/git/bforbis/athena-backstage/config/platform/interop/eventing/eventing.yaml
```

### 👟 Reproduction steps

Add the [linguist plugin](https://github.com/backstage/backstage/tree/master/plugins/linguist-backend) and start the service to see the warnings 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by bforbis** [comment]
Maybe the simplest solution is to add something like a configurable delay for the processor to start processing? I suppose I shouldn't delay the whole processing engine, but the linguist tags processor could check a constructor arg like a passed in delay timestamp before making requests.

**Comment by Rugvip** [comment]
This is actually solved in the new backend system by pausing incoming requests until the plugin has started up: https://github.com/backstage/backstage/blob/f1aed1de7cff84b5cf835915012b83264a31809e/packages/backend-app-api/src/services/implementations/httpRouter/createLifecycleMiddleware.ts#L52

Gonna close this since we consider it a solved issue

**Comment by bforbis** [comment]
@Rugvip can you tell me more about how / when I can use this new system? The docs says to not use this in production yet, so I've mostly been waiting to dig into it.

https://backstage.io/docs/backend-system/

**Comment by Rugvip** [comment]
@bforbis since 1.18 we no longer discourage use in production, try it out! :tada:
