### ISSUE TITLE
🚀 Feature: API versioning support

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#20209]
### 🔖 Feature description

Currently backstage support only 1 version of the API in the catalog. In order to handle the multiple versions, users have to create multiple instance of the semantically same API, which can lead to many other problems.

PS: This feature was requested in the past via the #11027, but was closed, starting a new thread for fresh discussion. 

### 🎤 Context

There are different usecases of the API catalog, i.e.

1. Allow the API consumers to explore the published versions of the API
2. Facilitate the collaboration between the stakeholders during the design phase of the API, while the implementation may not be there yet.
3. Tracking the API promotion across the environments during the delivery lifecycle.

Backstage api catalog is currently only useful for #1 above, but does not have a support for #2 and #3.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
I've reopened #11027, let's keep that discussion going instead 👍
