### ISSUE TITLE
🐛 Bug Report: Website "Watch Now" link doesn't work

### ISSUE THREAD

**Issue by cdrage** [backstage/backstage#20222]
### 📜 Description

Unsure where to file an issue for the website?

Watch Now button doesn't work on https://backstage.io/demos/

### 👍 Expected behavior

Watch now should work

### 👎 Actual Behavior with Screenshots

https://github.com/backstage/backstage/assets/6422176/24f09519-a514-463b-b94d-8d070ece27e9

### 👟 Reproduction steps

1. Go to https://backstage.io/demos/
2. Click watch now

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by fedy97** [comment]
The first demo item does not have a video attached, only an image. We could remove the `Watch Now` button
