### ISSUE TITLE
🚀 Feature: Add versioning to the docs on backstage.io

### ISSUE THREAD

**Issue by ghost** [backstage/backstage#20231]
### 🔖 Feature description

Start using some kind of versioning in the docs on backstage.io, so I can avoid linking to doc pages that mention features my local Backstage instance hasn't adopted yet.

### 🎤 Context

My team likes to link to docs on backstage.io for features we haven't modified or where the docs there go into more detail than our local docs do.

My team doesn't always upgrade to the latest version of Backstage as soon as it's released.

This leaves us in the position of having links in our docs that point to relevant content in the backstage.io docs, that end up mentioning Backstage features for new versions we don't offer yet. 

It would be nice if we could link to a particular version of a backstage.io doc page, so that links in our docs go to a version that's appropriate for the Backstage release we're currently using. (And yes, we'd then have to maintain those links when we deploy a new release, but we have a whole process around updating to a new release, and could add link maintenance to that process.)

### ✌️ Possible Implementation

Something like what mkdocs-material offers would be good. https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by awanlin** [comment]
This would really help for those that might be a bit slow to upgrade and run into issue where the docs have newer content 👍

**Comment by awanlin** [comment]
This is something we could really use still

**Comment by homeaidepi** [comment]
Def could use this. What good is an API Portal if the API's "versioning" cant be reasonably filtered, searched and a major part of the UI for which its meant to explain deprecation and upgrade to the customer.   Am I missing something here?  Cause yeah if the repo is different and the name of the system is different (say suffixed or named with dev,test,prod, d,t,p etc.) then it will show in the UI but they arent grouped in any way. They are just atomic things and thats only good for repos that are environment specific. What if you have a mono repo and version merely by path or branch name, etc...  So how in Backstage are these variety of "versioning of an API" as it relates to source code locations handled?

**Comment by awanlin** [comment]
Hi @homeaidepi, just a heads up this issue is for the Documentation for Backstage located here - https://backstage.io/docs/ - and not for Backstage itself.
