### ISSUE TITLE
🐛 Bug Report: converting circular structure to JSON error

### ISSUE THREAD

**Issue by dimitri-segard** [backstage/backstage#20256]
### 📜 Description

We are using `oneOf` in our scaffolder templates to generate select fields with labels and values.
We recently upgraded from Node 16 to Node 18 and we started getting this error.
I was also able to reproduce the error on a fresh Backstage install with scaffolder/next enabled.

### 👍 Expected behavior

Form should go to the review step without any error.

### 👎 Actual Behavior with Screenshots

`Converting circular structure to JSON --> starting at object with constructor 'Object' | property 'oneOfSchema' -> object with constructor 'Object' | property 'oneOf' -> object with constructor 'Array' --- index 0 closes the circle`

<img width="1488" alt="image" src="https://github.com/backstage/backstage/assets/138414831/5c939c57-05d3-470d-af95-64bdb5a8b826">

Stack trace:
<img width="467" alt="image" src="https://github.com/backstage/backstage/assets/138414831/f037c74c-4d80-4b3d-8da0-453dbbf0838b">

### 👟 Reproduction steps

- Enable scaffolder/next
- Add the following custom template to your Backstage instance:

```yaml
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: circular-json-minimal-reproduction
  title: Circular JSON Issue
  description: Reproduce circular JSON Issue.
spec:
  owner: team
  type: some-type
  parameters:
    - title: Parameters
      properties:
        value1:
          title: Value 1
          type: string
          default: value1
          oneOf:
            - const: "value1"
              title: "Value 1"
            - const: "value2"
              title: "Value 2"
  steps:
    - id: debug
      name: Debug
      action: debug:log
      input:
        message: "debug message"
  output: {}
```

- Click on "Review"

### 📃 Provide the context for the Bug.

- We are using scaffolder/next
- It works fine when using `enum` and `enumNames`. `enumNames` seems to be [deprecated](https://rjsf-team.github.io/react-jsonschema-form/docs/migration-guides/v5.x%20upgrade%20guide/#non-standard-enumnames-property). We are temporarily using this as a workaround.
- Not sure if this is relevant but the following JSON doesn't generate any error on https://rjsf-team.github.io/react-jsonschema-form/
```json
{
  "title": "Value 1",
  "type": "string",
  "default": "value1",
  "oneOf": [
    {
      "const": "value1",
      "title": "Value 1"
    },
    {
      "const": "value2",
      "title": "Value 2"
    }
  ]
}
```

### 🖥️ Your Environment

```
yarn backstage-cli info
yarn run v1.22.19
OS:   Darwin 22.6.0 - darwin/arm64
node: v18.18.0
yarn: 1.22.19
cli:  0.22.13 (installed)
backstage:  1.18.0

Dependencies:
  @backstage/app-defaults                                          1.4.3
  @backstage/backend-app-api                                       0.5.4
  @backstage/backend-common                                        0.19.6
  @backstage/backend-dev-utils                                     0.1.1
  @backstage/backend-openapi-utils                                 0.0.4
  @backstage/backend-plugin-api                                    0.6.4
  @backstage/backend-tasks                                         0.5.9
  @backstage/catalog-client                                        1.4.4
  @backstage/catalog-model                                         1.4.2
  @backstage/cli-common                                            0.1.12
  @backstage/cli-node                                              0.1.4
  @backstage/cli                                                   0.22.13
  @backstage/config-loader                                         1.5.0
  @backstage/config                                                1.1.0
  @backstage/core-app-api                                          1.10.0
  @backstage/core-components                                       0.13.5
  @backstage/core-plugin-api                                       1.6.0
  @backstage/errors                                                1.2.2
  @backstage/eslint-plugin                                         0.1.3
  @backstage/integration-aws-node                                  0.1.6
  @backstage/integration-react                                     1.1.19
  @backstage/integration                                           1.7.0
  @backstage/plugin-api-docs                                       0.9.11
  @backstage/plugin-app-backend                                    0.3.52
  @backstage/plugin-app-node                                       0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.1.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.1
  @backstage/plugin-auth-backend-module-google-provider            0.1.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.1
  @backstage/plugin-auth-backend                                   0.19.1
  @backstage/plugin-auth-node                                      0.3.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.1
  @backstage/plugin-catalog-backend                                1.13.2
  @backstage/plugin-catalog-common                                 1.0.16
  @backstage/plugin-catalog-graph                                  0.2.36
  @backstage/plugin-catalog-import                                 0.10.0
  @backstage/plugin-catalog-node                                   1.4.5
  @backstage/plugin-catalog-react                                  1.8.4
  @backstage/plugin-catalog                                        1.13.0
  @backstage/plugin-events-node                                    0.2.13
  @backstage/plugin-github-actions                                 0.6.5
  @backstage/plugin-org                                            0.6.14
  @backstage/plugin-permission-common                              0.7.8
  @backstage/plugin-permission-node                                0.7.15
  @backstage/plugin-permission-react                               0.4.15
  @backstage/plugin-proxy-backend                                  0.4.1
  @backstage/plugin-scaffolder-backend                             1.17.2
  @backstage/plugin-scaffolder-common                              1.4.1
  @backstage/plugin-scaffolder-node                                0.2.4
  @backstage/plugin-scaffolder-react                               1.5.5
  @backstage/plugin-scaffolder                                     1.15.0
  @backstage/plugin-search-backend-module-catalog                  0.1.8
  @backstage/plugin-search-backend-module-pg                       0.5.13
  @backstage/plugin-search-backend-module-techdocs                 0.1.8
  @backstage/plugin-search-backend-node                            1.2.8
  @backstage/plugin-search-backend                                 1.4.4
  @backstage/plugin-search-common                                  1.2.6
  @backstage/plugin-search-react                                   1.7.0
  @backstage/plugin-search                                         1.4.0
  @backstage/plugin-tech-radar                                     0.6.8
  @backstage/plugin-techdocs-backend                               1.7.1
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.0
  @backstage/plugin-techdocs-node                                  1.8.1
  @backstage/plugin-techdocs-react                                 1.1.11
  @backstage/plugin-techdocs                                       1.7.0
  @backstage/plugin-user-settings                                  0.7.10
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.3
  @backstage/theme                                                 0.4.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.5
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
This might be an issue here: https://github.com/backstage/backstage/blob/53b7c7668d0f783e50359e091d63ddc429aee05b/plugins/scaffolder-react/src/next/components/Stepper/createAsyncValidators.ts#L77 where the `definitionInSchema` ends up being an error rather than a JSONSchema, although it could be something else, best add a check there either way.

It's also probably worth switching https://github.com/backstage/backstage/blob/518a34646b79ec2028cc0ed6bc67d4366c51c4d6/plugins/scaffolder-react/src/next/lib/schema.ts#L126 to be a deep copy instead.

👀 @benjdlambert

**Comment by benjdlambert** [comment]
Yep, I think that these suggestions make sense @Rugvip. @dimitri-segard do you want to go ahead and make the suggested changes and whip up a PR :pray:

**Comment by dimitri-segard** [comment]
Sure I can try to whip up a PR. 👍 

> where the definitionInSchema ends up being an error rather than a JSONSchema, although it could be something else, 
 best add a check there either way.

@Rugvip What should be the behavior if `definitionInSchema` is not a JSONSchema?

**Comment by benjdlambert** [comment]
@dimitri-segard think you can treat `definitionInSchema` as undefined instead. It should follow the same code path as if it was that at least.

**Comment by benjdlambert** [comment]
@dimitri-segard did you manage to take a look at this? :pray:

**Comment by Vity01** [comment]
I can confirm this bug persists in 
```
    "@backstage/plugin-scaffolder": "^1.17.1-next.2",
    "@backstage/plugin-scaffolder-react": "^1.7.1-next.2",
```
so https://github.com/backstage/backstage/issues/21992 is not a solution for this problem.

**Comment by Vity01** [comment]
I am not sure if it's related, but we have started to encounter complete freeze of the browser tab when pressing "Next" button (some validation occurs). It happens randomly.

**Comment by acierto** [comment]
Fix: https://github.com/backstage/backstage/pull/22566

**Comment by Vity01** [comment]
I can confirm @acierto  fix is working. Please integrate&release it ASAP. It's a blocker. Probably not only for us. 
I have also discovered a reason for the browser freeze. The EntityPicker used for owner definition is loading User&Group full data about these entities (~50 megs in our case...). I am going to prepare some PR with field limitation.

**Comment by freben** [comment]
It's already merged so it's going out in all future releases.
