### ISSUE TITLE
TechDocs: As a consumer of docs in Backstage, I want to be able to watch a doc site for changes

### ISSUE THREAD

**Issue by garyniemen** [backstage/backstage#2027]
This is a feature request from one of our early TechDocs users:
"I would like it to be possible to Watch (as in GHE Watch) a document (repo) directly from TechDocs. This allows me to be notified about changes and issues submitted to the repo using standard GHE mechanisms. I think this is a killer feature, and probably pretty simple to implement."

**Comment by OrkoHunter** [comment]
Backstage does not have a notifications feature. Creating watch feature is difficult to implement.

**Comment by OrkoHunter** [comment]
Closing this issue for now because it's stale and not trivial to implement given the features in Backstage/TechDocs frontend. However, the feature is still in TechDocs Roadmap. Critically speaking - You could still watch the repository for changes.
