### ISSUE TITLE
TechDocs: Improve TechDocs homepage which shows list of current documentation sites

### ISSUE THREAD

**Issue by garyniemen** [backstage/backstage#2028]

**Comment by OrkoHunter** [comment]
I think this has been shipped with TechDocs V1 i.e. we can browse the list of documentation websites.
@spotify/techdocs-core I'm closing this, but we can re-open if this means something else.

**Comment by emmaindal** [comment]
@OrkoHunter Can we leave this issue open but just rename it a little? I think we can definitely work more on the TechDocs Homepage which is what I think you refer to as the list of current sites. That page doesn't deliver a good UX for more than 10 sites I would say.

**Comment by OrkoHunter** [comment]
@emmaindal Sure, absolutely!

**Comment by OrkoHunter** [comment]
Hi @katz95 cc @soapraj ! We need some design inspiration on how the techdocs plugin's home page should look like and what features it should have. We can take our internal techdocs homepage as an inspiration as well. Few thoughts to consider from the team -

* Pagination: The homepage shows the list of all documentation sites but what should we do for a large number of them (~500). How should we paginate?
* Categorization of documentation sites
* Have an `all/owned` section just like the entity page
* Favorites: Can users star/fav doc sites. (Favs will have to be implemented separately)
* Should there be a create docs component on homepage? We can just redirect to the right scaffolder page for this.

We will then split this issue into separate issues after the design decision has been made. Thank you!
(I am happy to jump in on a team sync including @garyniemen if that helps)

**Comment by katz95** [comment]
@OrkoHunter thanks for tagging me :) spoke to @soapraj yesterday and will be looking into this! will get something to you by next week

**Comment by katz95** [comment]
Been going over some of these design decisions with @garyniemen and @emmaindal and we were thinking along these lines.

**Overview page**

- Has a prominent search bar that allows users to quick search (pulls up 5 results). If user clicks 'enter' or clicks 'advanced search', they will be directed to the 'All Documents' page, which is a comprehensive page with all the docs.
- Also has 'Your Favorite' documents and 'Recently Read' documents sections. For the Favorites section, we will likely need to add a 'View More' button - once we figure out where we can store an archive of all Favorites (perhaps as another tab within TechDocs?)
- Bottom section includes 'Recommended for You' section featuring docs represented in cards that have tags on them

**All Documents**

- Filter capabilities allows users to hone in on the docs they're looking for
- Users ideally can favorite and share docs

**Owned Documents**

- Empty state if users don't have any documents
- Once users have their own docs, they can see a table similar to the table under the 'All Documents' page, where perhaps they can view metrics for their documents (views, interactions, shares, etc.)

Any comments/feedback would be appreciated!!

![techdocs-home](https://user-images.githubusercontent.com/61153904/97576207-2777b700-19ee-11eb-8eab-66a87148a80d.gif)

**Comment by katz95** [comment]
![All docs](https://user-images.githubusercontent.com/61153904/97577097-4296f680-19ef-11eb-8bc1-47d3615e47c5.png)

![quick search](https://user-images.githubusercontent.com/61153904/97577096-4296f680-19ef-11eb-87bd-e63b6085e537.png)

![filter](https://user-images.githubusercontent.com/61153904/97577085-3f9c0600-19ef-11eb-9746-7f9807ade009.png)



![Overview](https://user-images.githubusercontent.com/61153904/97577103-432f8d00-19ef-11eb-87bf-f6ed46df9154.png)

![Owned docs](https://user-images.githubusercontent.com/61153904/97577110-4460ba00-19ef-11eb-8194-62c923b5cb00.png)

**Comment by katz95** [comment]
complete GIF

![td](https://user-images.githubusercontent.com/61153904/97588253-99ef9380-19fc-11eb-8ca9-bbb253c7fb7c.gif)

**Comment by katz95** [comment]
complete GIF 

![td](https://user-images.githubusercontent.com/61153904/97588804-2732e800-19fd-11eb-8f87-10dacddf53fb.gif)

**Comment by emmaindal** [comment]
Hey @katz95, thanks so much for these designs. Its great! As search isn't ready yet I suggest we create some separate issues out of this, based on the following user stories:

1.
- As a user, I should be able to favorite any docs page. 
- As a user, I should be able to see my list of favorited docs pages on the docs landing page (see design above).

2. 
- As a user, I should be able to create a new component based on the docs template from the TechDocs HomePage, by clicking on a "create component" button (see design above).

3.
- As a user, I should be able to view support information on the TechDocs HomePage (see design above)

4. 
- As a user, I should be able to view what documents I own rom the TechDocs HomePage (see design above - all documents). 

And then we wait with, search, "recently viewed" as well as "recommended for you". If needed we can replace "recommended for you" with displaying all documents that exist (no matter if you own them or not) together with some filters but without search. 


What do you think @OrkoHunter @garyniemen @katz95?

**Comment by OrkoHunter** [comment]
Agree to splitting up into several issues. I like how you broke this down into several pieces, it's awesome!

**Comment by emmaindal** [comment]
@garyniemen @OrkoHunter @soapraj I've created all the sub issues above as discussed, feel free to add any missing information if you feel its needed.

**Comment by OrkoHunter** [comment]
Thank you for creating them @emmaindal ! ⭐

**Comment by OrkoHunter** [comment]
Closing this issue now, since we have split it into multiple smaller issues.
