### ISSUE TITLE
[TechDocs] As a producer of doc sites, I want to be able to remove my doc site

### ISSUE THREAD

**Issue by garyniemen** [backstage/backstage#2030]
It is often the case that teams create a documentation site and then need to remove it for some reason. This could be, for example, because the original site was a test site or they want to replace the old site with a new one. Removing a doc site should be as easy as creating a site.

Removing a site is done by "Unregistering an entity".

![Screenshot 2020-10-05 at 14 40 07](https://user-images.githubusercontent.com/8065913/95081965-a1cc5880-071a-11eb-8184-16c35f2ed4f1.png)

# Possible Implementation

Depending on the storage solution (techdocs-backend, GCS, AWS S3, etc.), clean the generated files for techdocs as a side effect of unregistering backstage component/entity.
Look to use/create an API for this - hook into unregister entity API of Backstage (if there is any).

**Comment by ron-debajyoti** [comment]
I would like to give it a try. Please assign it to me.

**Comment by soapraj** [comment]
Hey! @ron-debajyoti - Awesome! I have assigned this to you.

**Comment by emmaindal** [comment]
Hey @ron-debajyoti just checking in here to see what the status of this issue is and if there is questions that we can answer? 🎉

**Comment by ron-debajyoti** [comment]
Hey @emmaindal I got stuck in school work last week. Will definitely make a PR by the end of the week!

**Comment by ron-debajyoti** [comment]
Hi! 
As far as I understand, unregistering an entity automatically deletes the Techdocs from the `localhost:3000/docs`. We want to add the feature to remove just the docs right ?

**Comment by OrkoHunter** [comment]
@ron-debajyoti Unregistering an entity is the correct and only way to delete a docs site since docs sites are also entities.

But unregistering an entity may not delete everything related to techdocs. For example, the process will not clean up TechDocs generated HTML files from GCS, S3 or local file system - whatever storage solution we are using.

The issue is especially targeting this particular use case for TechDocs. Also see the possible implementation section in the issue description.

**Comment by ron-debajyoti** [comment]
Hi !,
Thanks for the detailed explanation @OrkoHunter !

I found out that Unregistering an entity is done under `catalog/src/components/UnregisterEntityDialog` in the catalog plugin. Earlier the day I was trying to perform the cleanup in `techdocs` and `techdoc-backend` plugins, but then it became tough to make a call from `catalog` to `techdocs`. I also didn't find any unregister API in `backstage/core` for such a task .

Is it possible to make a hook/call from `catalog` to `techdocs` or `catalog-backend`?

**Comment by OrkoHunter** [comment]
Aah, good question @ron-debajyoti ! I don't know the definite answer to it. @hooloovooo What are your thoughts on this ?

> Is it possible to make a hook/call from catalog to techdocs or catalog-backend?

**Comment by ron-debajyoti** [comment]
@hooloovooo ! Would appreciate your views in this !

**Comment by hooloovooo** [comment]
Sorry about the slow response!
I don't think there are any hooks in the catalog we can use to figure out when to delete the content right now, but a solution like that sounds like a good idea to me. Maybe @freben knows more of how we can interact with catalog to find out when a entity is deleted.

**Comment by freben** [comment]
Correct, there are no such hooks. Ideally, there would be an event bus from the catalog that pushes additions/updates/deletions, but there is no such thing at the moment. I added an issue for that now to track it.

https://github.com/backstage/backstage/issues/3221

**Comment by OrkoHunter** [comment]
Thank you @freben ! I think it makes sense to mark this issue as blocked for now.

**Comment by ron-debajyoti** [comment]
Should this issue be still assigned then ?

**Comment by OrkoHunter** [comment]
@ron-debajyoti Thanks! Un-assigned this for now. Apologies that this task turned out to be blocked. 🙇

**Comment by ron-debajyoti** [comment]
Hey no problem! @OrkoHunter

**Comment by pedronastasi** [comment]
Our team is also trying to accomplis this task, we have some ideas.

**Comment by GunnerStraiker1** [comment]
Hi @OrkoHunter is this still an issue? My team and I created a method to delete techdocs every time you delete an entity using the unregister entity button and we'd like to share it here

**Comment by patrickwyler** [comment]
@GunnerStraiker1 could you share your solution? I’d be very interested to see how you did it.
