### ISSUE TITLE
🐛 Bug Report: oauth2-proxy and CORS setup not working

### ISSUE THREAD

**Issue by mdundek** [backstage/backstage#20311]
### 📜 Description

When using oauth2-proxy and keycloak on my development machine to implement authentication for Backstage, I get a CORS error when the auth flow tries to redirect the user to "http://localhost:4180/api/auth/oauth2Proxy/refresh". 

### 👍 Expected behavior

Browser redirects user to the keycloak authentication page

### 👎 Actual Behavior with Screenshots

When accessing the backstage UI on localhost:3000, the following happens:

__In my `oauth2-proxy` server, I see the following log:__

```sh
[2023/10/02 13:26:05] [oauthproxy.go:970] No valid authentication in request. Initiating login.
127.0.0.1 - 4a802df9-a60e-4ddd-9f59-0d8d656c1c72 - - [2023/10/02 13:26:05] localhost:4180 OPTIONS - "/api/auth/oauth2Proxy/refresh" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" 302 0 0.000
```

it looks like oauth2-proxy returns a `302` towards `/api/auth/oauth2Proxy/refresh`, which is what I was expecting.

__When checking the console in my Chrome / Firefox browser, I see the following error:__

```sh
Access to fetch at 'http://localhost:4180/api/auth/oauth2Proxy/refresh' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

## Keycloak 

Started Keycloak using the command:

```sh
docker run --platform=linux/amd64 -p 9990:8080 \
    -e KEYCLOAK_ADMIN=admin \
    -e KEYCLOAK_ADMIN_PASSWORD=admin \
    quay.io/keycloak/keycloak:22.0.3 start-dev
```

Created a realm named "backstage" and a client for the realm named "oauth2-proxy".

## Oauth2-proxy

Created a `oauth2_proxy.cfg` file the following config:

```
http_address="127.0.0.1:4180"

provider="keycloak"
provider_display_name="Keycloak"
login_url = "http://localhost:9990/realms/backstage/protocol/openid-connect/auth"
redeem_url = "http://localhost:9990/realms/backstage/protocol/openid-connect/token"
profile_url = "http://localhost:9990/realms/backstage/protocol/openid-connect/userinfo"
validate_url = "http://localhost:9990/realms/backstage/protocol/openid-connect/userinfo"
oidc_issuer_url = "http://localhost:9990/realms/backstage"

client_id = "oauth2-proxy"
client_secret = "<my keycloak client secret>"

redirect_url = "http://localhost:4180/oauth2/callback"

upstreams = [
    "http://localhost:3000" ,
    "http://localhost:7007/api/"
]

request_logging = true

pass_basic_auth = true
pass_user_headers = true
pass_host_header = true 

email_domains = [
    "*"
]

pass_access_token = true
ssl_insecure_skip_verify = false
cookie_secret = "OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
cookie_secure = false
set_authorization_header = "true"
pass_authorization_header = "true"
reverse_proxy = "true"
scope = "email"
whitelist_domains = "*"
skip_provider_button = "true"
set_xauthrequest = "true"
```

started the oauth2-proxy:

```sh
./bin/oauth2-proxy --config=./oauth2_proxy.cfg
```

## Backstage

Created a backstage app:

```sh
npx @backstage/create-app
```

__app-config.yaml:__

```yaml
app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000
...
backend:
  baseUrl: http://localhost:4180
  listen:
    port: 7007
  ...
  cors:
    origin: http://localhost:4180
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE] # tried without this as well
    credentials: true # tried without this as well
...
auth:
  providers:
    oauth2Proxy: {}
...
```

__App.tsx:__

```javascript
...
const app = createApp({
  apis,
  bindRoutes({ bind }) {
    ...
  },
  components: {
    SignInPage: props => (
      <ProxiedSignInPage {...props} provider="oauth2Proxy" />
    ),
  },
});
...
```

__auth.ts:__

```javascript
import {
  DEFAULT_NAMESPACE,
  stringifyEntityRef,
} from '@backstage/catalog-model';
...
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      ...defaultAuthProviderFactories,
      oauth2Proxy: providers.oauth2Proxy.create({
        signIn: {
          async resolver({ result }, ctx) {
            const name = result.getHeader('x-forwarded-preferred-username');
            if (!name) {
              throw new Error('Request did not contain a user');
            }

            try {
              // Attempts to sign in existing user
              const signedInUser = await ctx.signInWithCatalogUser({
                entityRef: { name },
              });

              return Promise.resolve(signedInUser);
            } catch (e) {
              // Create stub user
              const userEntityRef = stringifyEntityRef({
                kind: 'User',
                name: name,
                namespace: DEFAULT_NAMESPACE,
              });
              return ctx.issueToken({
                claims: {
                  sub: userEntityRef,
                  ent: [userEntityRef],
                },
              });
            }
          },
        },
      }),
    },
  });
}

```

then started backstage with:

```yaml
yarn dev
```

I have investigated different bug reports on this page already, tried to fiddle with the "cors" settings in backstage but always get the same error in the browser.

### 🖥️ Your Environment

Mac M1 (ARM64)
oauth2-proxy version 22 - running on port 4180
Keycloak version 22 - running in Docker on port 9990
backstage cli version 0.22.13 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Zaperex** [comment]
Just wondering, but shouldn't the `backend.cors.origin` value be the frontend (http://localhost:3000) and not the backend (http://localhost:4180)?

**Comment by mdundek** [comment]
Thanks @Zaperex for your comment, I tried both already, same result. The backend URL also seems to make sense, it is to tell the Backstage frontend what backend URL it is allowed to invoke and that is not identical to the frontend URL (port 3000). I also tried "*", it's as if this value is not used by backstage in this context at all.

**Comment by mdundek** [comment]
Still stuck, any help would be greatly appreciated. The error seems to come from the React frontend web-pack server that is serving the frontend using "yarn workspace app start". The backend is the part that has CORS configured, yet the frontend is not served by the backstage backend when in development mode so the fact that CORS is not set is not a surprise to me. 

Given that for oauth2-proxy to work, we need to proxy frontend requests to port 4180, therefore we need to tell webpack to allow this CORS rule. Where is this configuration located within backstage?

**Comment by benjdlambert** [comment]
@mdundek I'm pretty sure that this is an oauth2-proxy issue, I don't think that 302 is valid in an options request which is why you're getting the CORS issue. Have you tried searching through their issues?

**Comment by mdundek** [comment]
Thanks @benjdlambert , I don't know if oauth2-proxy has a bug that would explain this (I doubt it), if the latest Backstage is confirmed to be working with the latest version of oauth2-proxy and Keycloak, then it's more probable that it is a miss-configuration on my part somewhere.  If so, it would be great if someone could share a working config that uses keycloak and oauth2-proxy.
I tested the oauth2-proxy directly by accessing the URL `http://localhost:4180/api/v1/users/me` and it redirected me to Keycloak in order to authenticate myself, so that part seems to work as expected.

**Comment by mdundek** [comment]
@benjdlambert I have spent hours trying to get this to work, without success. I added an Nginx server in front of oauth2-proxy so that I could set the "Access-Control-Allow-Origin" to what I need despite of what oauth2-proxy would set in there, unfortunately it felt like a goose chase where one error lead to the next (needed to set "Access-Control-Allow-Methods" to true, then "Access-Control-Allow-Headers" to allow "X-Requested-With", then return 204 if request method was "OPTIONS", but whatever I tweaked in the response headers, there was always another error following the previous one).
I followed the instructions from [this link](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#keycloak-oidc-auth-provider) by the letter, still the same issue. I tried all sorts of flags and configs for oauth2-proxy (inc. skip_auth_preflight), without success.
I will give up for now, need to move on from this, but if anyone has had success making backstage work with oauth2-proxy and Keycloak (using http, maybe that has some side effects that would explain it?), please feel free to share your config and make my day!

**Comment by benjdlambert** [comment]
Tagging @tumido if you have any ideas of folks from the RedHat side that might have done something similar like this with keycloak and have this same setup and working? :pray:

**Comment by brunobastosg** [comment]
@mdundek , I'm also struggling to configure Keycloak login with oauth2-proxy in Backstage.

However, my problem is a bit different than yours. In my CORS configuration, I put the frontend URL (instead of the oauth2-proxy URL as in your original post):

```yaml
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
```
I also kept the backend baseUrl as the default (http://localhost:7007).

The OPTIONS request succeeds, but then I get a 401 error in the following GET request:

![image](https://github.com/backstage/backstage/assets/320122/317a131c-ab57-46cc-8406-0b69574f85cf)

If I change the CORS origin to http://localhost:4180 and/or the backend baseUrl to http://localhost:4180, then I get the same problem as you (CORS error in the OPTIONS request).

**Comment by brunobastosg** [comment]
Got it working thanks to [this issue](16885)

**Comment by benjdlambert** [comment]
@mdundek it looks like maybe this blog post could help you too? https://janus-idp.io/blog/2023/01/17/enabling-keycloak-authentication-in-backstage/#configuring-keycloak

**Comment by orlando2116** [comment]
I have a similar error


this request **_http://localhost:7007/api/auth/oauth2Proxy/refresh_** return the following error:
```
`{
    "error": {
        "name": "Error",
        "message": "Request did not contain a user",
        "stack": "Error: Request did not contain a user\n    at resolver (/Users/oegonzalezz/Documents/backstage/packages/backend/src/plugins/auth.ts:61:21)\n    at Object.refresh (/Users/oegonzalezz/Documents/backstage/node_modules/@backstage/plugin-auth-node/src/proxy/createProxyRouteHandlers.ts:66:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    },
    "request": {
        "method": "GET",
        "url": "/api/auth/oauth2Proxy/refresh"
    },
    "response": {
        "statusCode": 500
    }
}`
```

- this is my oauth2_proxy.cfg:

```
http_address = "127.0.0.1:4180"

provider = "keycloak"
login_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/auth"
redeem_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/token"
profile_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/userinfo"
validate_url = "http://localhost:9990/auth/realms/backstage/protocol/openid-connect/userinfo"
oidc_issuer_url = "http://localhost:9990/auth/realms/backstage"

client_id = "oauth2-proxy"
client_secret = "XeC6jBFPbC1bg3CNa7Ifn1cj0tCnoSbP"

redirect_url = "http://localhost:4180/oauth2/callback"

upstreams = [
    "http://127.0.0.1:3000/",
    "http://localhost:7007/api"
]

request_logging = true

pass_basic_auth = true
pass_user_headers = true
pass_host_header = true 

email_domains = [
    "*"
]

pass_access_token = true
ssl_insecure_skip_verify = false
cookie_secret = "lLYcG3L1khAS9Yz8hXb7mia1wSDk_eCDQFzl_Yx2rA4="
cookie_secure = false
set_authorization_header = "true"
pass_authorization_header = "true"
reverse_proxy = "true"
scope = "email"
whitelist_domains = "*"
skip_provider_button = "true"
set_xauthrequest = "true"
``` 


- this is my auth.ts:
``` 
import {
  createRouter,
  providers,
  defaultAuthProviderFactories,
} from '@backstage/plugin-auth-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';
import { DEFAULT_NAMESPACE, stringifyEntityRef } from '@backstage/catalog-model';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      ...defaultAuthProviderFactories,

      oauth2Proxy: providers.oauth2Proxy.create({
        signIn: {
          async resolver({ result }, ctx) {
            console.log("--------------------RESULT AUTH--------------")
            console.log(result)
            console.log("--------------------END RESULT AUTH--------------")
            const name = result.getHeader('x-forwarded-preferred-username');
            if (!name) {
              throw new Error('Request did not contain a user');
            }

           // Create stub user
           const userEntityRef = stringifyEntityRef({
            kind: 'User',
            name: name,
            namespace: DEFAULT_NAMESPACE,
          });

          return ctx.issueToken({
            claims: {
              sub: userEntityRef,
              ent: [userEntityRef],
            },
          });
          },
        },
      }),
      
    },
  });
}
``` 

- this is my app-config.yaml
``` 
...

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:4180
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1

  cors:
    origin: http://localhost:4180
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true


auth:
  providers:
    oauth2Proxy: {}


...



``` 
for backstage configuration i follow [this documentation](https://janus-idp.io/blog/2023/01/17/enabling-keycloak-authentication-in-backstage/)

<img width="1022" alt="image" src="https://github.com/backstage/backstage/assets/20132141/c11a12c7-367a-460c-9df9-f5f54ac28286">

Any idea what i'm missing?
@mdundek  @brunobastosg please, can you help me?
