### ISSUE TITLE
🐛 Bug Report: auth.getAccessToken doesn't survive page reloads anymore

### ISSUE THREAD

**Issue by kunickiaj** [backstage/backstage#20322]
### 📜 Description

When calling auth.getAccesToken for the GitHub provider, it forces the user to login even if they're already logged in. This session can withstand route changes and subsequent calls, but not a page reload. The user will see a login popup again.

### 👍 Expected behavior

It should work as it used to where if the provider has already been authorized, a token should be returned.

### 👎 Actual Behavior with Screenshots

It actually props the user to login on every page load.

<img width="529" alt="Screenshot 2023-10-02 at 12 34 20" src="https://github.com/backstage/backstage/assets/746474/d051953b-eaa2-4f04-8c7c-7c1c4dce882b">

### 👟 Reproduction steps

Using backstage 1.18.3 try something like the PR plugin (https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/backstage-plugin-github-pull-requests)

I'm experiencing the same behavior on an internal techdocs addon that calls the GH api.

### 🖥️ Your Environment

Chrome Version 117.0.5938.132 (Official Build) (arm64)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kunickiaj** [comment]
Relates to https://github.com/backstage/backstage/issues/20103 which doesn't seem to be fully fixed

**Comment by kunickiaj** [comment]
Can anyone else confirm that they're experiencing this issue?

**Comment by shoeletz** [comment]
@kunickiaj I updated and am encountering this issue as well, using Okta auth.

**Comment by kunickiaj** [comment]
> @kunickiaj I can confirm the issue.
> 
> After some investigation I think there is a problem in the session [refresh handler](https://github.com/backstage/backstage/blob/master/plugins/auth-node/src/oauth/createOAuthRouteHandlers.ts?rgh-link-date=2023-10-04T13%3A14%3A24Z#L279). I see that the `scope` previously saved in cookie is [being used](https://github.com/backstage/backstage/blob/master/plugins/auth-node/src/oauth/createOAuthRouteHandlers.ts?rgh-link-date=2023-10-04T13%3A14%3A24Z#L299) to refresh a session but is missed in the response. I guess [this line](https://github.com/backstage/backstage/blob/master/plugins/auth-node/src/oauth/createOAuthRouteHandlers.ts?rgh-link-date=2023-10-04T13%3A14%3A24Z#L323) should be fixed, like this e.g.:
> 
> ```
> scope: authenticator.shouldPersistScopes ? scope : result.session.scope,
> ```

Not very familiar with this implementation so going to try to add some more details to what i'm observing if it helps..

When loading a page that has a plugin that wants gh repo scope (to make some gh requests) i see:
`/api/auth/github/refresh?optional&scope=repo&env=production` called in the browser -- which is correct afaict

it returns a response that even includes the accessToken, however scope is `""`
e.g.
```json
{
...
  "providerInfo": {
    "accessToken": "ghu_....",
    "scope": "",
    "expiresInSeconds: "28800"
  }
...
}
```

Once i click on the login popup i see that GH requests are made with a different `ghu_` token from the one above.

I _think_ this might confirm your suspicions that the requested scope is not being returned in the response.

**Comment by kunickiaj** [comment]
nvm, was able to repro/verify fix using `yarn dev` on the demo backstage. will work on getting a PR together shortly.
