### ISSUE TITLE
🐛 Bug Report: Unable to compile the application after installing opencost plugin

### ISSUE THREAD

**Issue by Nayaksonal** [backstage/backstage#20333]
### 📜 Description

Backstage (v.1.18.0) application fails to compile after installing opencost plugin, with error of unable to find image pig.png in the required folder within node_modules

Application is able to compile and build  properly once image(any image) is placed in folder node_modules/@backstage/plugin-opencost/images/pig.png

### 👍 Expected behavior

Application should compile without any issues with standard opencost plugin (getting necessary assets into node_modules as per the import)

### 👎 Actual Behavior with Screenshots

When run locally I get following message after compiling the application with yarn: build 
**Error Message :** 
Failed to compile.
Module not found: Can't resolve '../../images/pig.png' in '../backstage/node_modules/@backstage/plugin-opencost/dist/esm'
node_modules/@backstage/plugin-opencost/dist/esm/index-d492edb0.esm.js

### 👟 Reproduction steps

1. Followed all steps in the [document](https://github.com/backstage/backstage/tree/master/plugins/opencost), 
2. Compile the application.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Yep this doesn't work: https://github.com/backstage/backstage/blob/7accd01a2cde796a4ee474e56dd2b7057cd404e0/plugins/opencost/src/components/OpenCostPage/OpenCostPage.tsx#L31

Something you could look into @mattray?

**Comment by mattray** [comment]
Assign it to me and I'll see about getting a patch ASAP.

**Comment by mattray** [comment]
I wrote the plugin using `yarn install` - `yarn dev` without the `npx @backstage/create-app@latest` step, so I never ran into this. I'll likely need to update the instructions as well as provide a patch.

**Comment by mattray** [comment]
I believe this fixes it, the `backstage-cli package build` has the png file in the right place and it renders.

**Comment by sdelbusto** [comment]
> I believe this fixes it, the `backstage-cli package build` has the png file in the right place and it renders.

Hi guys! any update how to integrate this plugin inside a project created with npx as a common plugin? not sure the best way to run this 'backstage-cli package build' without a rg role.

ta!
