### ISSUE TITLE
🐛 Bug Report: Github Action Plugin 404 error

### ISSUE THREAD

**Issue by darrell-hart** [backstage/backstage#20347]
### 📜 Description

After I consent the redirect url / popup window returns a  `ERROR 404: PAGE NOT FOUND Looks like someone dropped the mic!`

https://backstage-mydomain.com/api/auth/github/handler/frame?code=0a8290a1aa4d2c93cc81&state=6e6f6e63653d657176774e43316e32424d4c41514862566f42374c4125334425334426656e763d646576656c6f706d656e74266f726967696e3d68747470732533412532462532466261636b73746167652d6e65772e6f62736572766162696c6974792e7372652e6c7974782e636f6d26666c6f773d706f7075702673636f70653d72656164253341757365722b7265706f2b726561642533416f7267

If I navigate directly to https://backstage-mydomain.com/api/auth/github/handler/frame?env=development. I get the same result `ERROR 404: PAGE NOT FOUND Looks like someone dropped the mic!`

There are no errors in the log (not even the 404). 

### 👍 Expected behavior

The consent screen is controlled by the OAuth provider, and will do things like prompting the user to log in with an account, and possibly reviewing the set of requested scopes. If the login request is accepted, the popup window will be redirected back to the /handler/frame endpoint of the auth backend. The redirect URL will contain a short-term authorization code, which is picked up by the backend and exchanged for long-term tokens via a call to the OAuth provider. The Access and possibly ID Token is then handed back to the main Backstage page via postMessage. If the OAuth provider implements offline refresh, a refresh token will be stored in an HTTP-only cookie scoped to the specific provider in the auth-backend plugin.

### 👎 Actual Behavior with Screenshots

<img width="1613" alt="Screenshot 2023-10-03 at 1 47 25 PM" src="https://github.com/backstage/backstage/assets/131400327/cc626864-8a13-482f-bf97-fc7541695961">

### 👟 Reproduction steps

Follow the documentation for setting up github action plugin, run it on K8 / minikube.    All the localhost examples work but that's not particularly useful.   

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by darrell-hart** [comment]
I finally figured out that I was incorrectly configuring the ingress on K8.  Once I commented out the path to port 7007 it worked.  

`        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backstage_svc
                port:
                  number: 80
          # - path: /api/auth/github/handler/frame
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: backstage_svc
          #       port:
          #         number: 7007`

**Comment by benjdlambert** [comment]
Hmm this is strange, how do you have the Backstage deployed? It looks like `/api` is hitting the `frontend` instead of being proxied through to the Backstage. Could be some misconfiguration in the ingress or something like that.
