### ISSUE TITLE
🚀 Feature: Update various search docs

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#20368]
### 🔖 Feature description

I'm attempting to follow the instructions to integrate the ADR plugin into backstage which includes the search extensions. I've found a few things are out of date.

1. [plugin-adr](https://github.com/backstage/backstage/tree/master/plugins/adr#search) uses an outdated search extension method. It doesn't include an example of the proper way to integrate it.
2. [plugins integrated with search](https://backstage.io/docs/features/search/#plugins-integrated-with-backstage-search) does not list adr as supported
3. [Search template HBS file](https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/packages/backend/src/plugins/search.ts.hbs#L9) for the backstage create-app script makes use of a deprecated `DefaultTechDocsCollatorFactory` from `@backstage/plugin-techdocs-backend`. This should be updated to use the one from `@backstage/plugin-search-backend-module-techdocs`. A similar issue also exists for the catalog collator.

### 🎤 Context

Ensure that all search related documents are up-to-date.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Possibly, though want to be sure by a maintainer that all these things I called out should be updated.

**Comment by benjdlambert** [comment]
@backstage/discoverability-maintainers do these docs look out of date? Should we fix them up? :pray:

**Comment by emmaindal** [comment]
Hello @bforbis thanks for opening this issue, I'm sure the search docs needs a proper review for updates. Our the discoverability maintainers don't have search as part of our current roadmap but would love to open this up for the community to help out with. Regarding your list of potential updates

> [plugin-adr](https://github.com/backstage/backstage/tree/master/plugins/adr#search) uses an outdated search extension method. It doesn't include an example of the proper way to integrate it.

Yes. would be great to update these docs to use the [AdrSearchResultListItem](https://github.com/backstage/backstage/blob/master/plugins/adr/src/plugin.ts#L70) created using the search result list item extension to align with the docs over at https://backstage.io/docs/features/search/how-to-guides/#2-using-an-extension-in-your-backstage-app


> [plugins integrated with search](https://backstage.io/docs/features/search/#plugins-integrated-with-backstage-search) does not list adr as supported

Yes. would be great to list the ADR plugin there with a note that it is community supported 

> [Search template HBS file](https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/packages/backend/src/plugins/search.ts.hbs#L9) for the backstage create-app script makes use of a deprecated DefaultTechDocsCollatorFactory from @backstage/plugin-techdocs-backend. This should be updated to use the one from @backstage/plugin-search-backend-module-techdocs. A similar issue also exists for the catalog collator.

this seems to have been updated to `@backstage/plugin-search-backend-module-techdocs` already so no action needed here.
