### ISSUE TITLE
🔌 Plugin: Komodor Backend 

### ISSUE THREAD

**Issue by TalFrum** [backstage/backstage#20370]
### 🔖 Summary

Komodor is a dev-first, kubernetes platform, that lets the developer operate, troubleshoot and optimize their kubernetes apps.
The plugin requires installing of the Komodor (frontend) plugin in and an API key of Komodor in order to make it work.

### 🌐 Project website (if applicable)

https://komodor.com/

### ✌️ Context

The backend plugin that constantly communicates with the Komodor agent, fetches clusters data (workloads) and updates the users.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hi @TalFrum thanks for the idea 🎉 ! We would like to close this issue and keep everything at https://github.com/backstage/backstage/issues/20369. Please, feel free to add more information about the backend there 🙌🏻
