### ISSUE TITLE
🐛 Bug Report: Localization - Changing the current language doesn't apply to components consistently

### ISSUE THREAD

**Issue by gashcrumb** [backstage/backstage#20381]
### 📜 Description

I've set up an [example Backstage installation](https://github.com/gashcrumb/backstage-i18n-discovery-nightly) with localization applied to a few different areas of the web app against last night's nightly to pick up [this PR](https://github.com/backstage/backstage/pull/20344).

1)  The main app has it's [own translations](https://github.com/gashcrumb/backstage-i18n-discovery-nightly/commit/317cda793b042e72f039b78c74eea9cce94f8e29#diff-2d6eea6932e73947413887c8547a8756f34d08cb3c08ae70d70922e5c3f2102aR47-R53) for the[ sidebar](https://github.com/gashcrumb/backstage-i18n-discovery-nightly/commit/317cda793b042e72f039b78c74eea9cce94f8e29#diff-cd085a2f1a86eff4863b006db1203a150fd1b39177f487f79cad3d82e9ad4aadR62-R96)
2)  A plugin that [is set up](https://github.com/gashcrumb/backstage-i18n-discovery-nightly/commit/317cda793b042e72f039b78c74eea9cce94f8e29#diff-805348be826d3b82291e805bc65bada1662a2c56f9af4e9429d4f57dbccade62R17) to [work with localization](https://github.com/gashcrumb/backstage-i18n-discovery-nightly/commit/317cda793b042e72f039b78c74eea9cce94f8e29#diff-2d6eea6932e73947413887c8547a8756f34d08cb3c08ae70d70922e5c3f2102aR54-R62)
3)  [Some translations](https://github.com/gashcrumb/backstage-i18n-discovery-nightly/commit/317cda793b042e72f039b78c74eea9cce94f8e29#diff-2d6eea6932e73947413887c8547a8756f34d08cb3c08ae70d70922e5c3f2102aR63-R69) for the existing user settings plugin

When selecting an alternate language, it's applied to the components from the user settings plugin, however the app's sidebar is not updated:

![image](https://github.com/backstage/backstage/assets/351660/e281e575-7e69-4c81-aa3f-5000de0c069a)

The example plugin does render as expected however the sidebar remains in English:

![image](https://github.com/backstage/backstage/assets/351660/f320c390-7be9-4523-ba40-8c9a43100c02)

And then when switching back from English to German, only the Language selector component updates:

![image](https://github.com/backstage/backstage/assets/351660/3f8e4398-71bb-427a-941d-58c674bbaaf2)

Interacting with the Theme component at this point will cause it to rerender and it'll then switch back to English

### 👍 Expected behavior

The language selected should be applied to all elements that support that particular translation.

### 👎 Actual Behavior with Screenshots

see above

### 👟 Reproduction steps

- Clone [this repo](https://github.com/gashcrumb/backstage-i18n-discovery-nightly)
- `yarn install`
- `yarn dev` and access the UI
- Go to the settings page and click on "DE" for the Language selector
- Click on "Language" and verify that this page is mostly in German
- Go back to "Settings" and click "EN"

### 📃 Provide the context for the Bug.

I'm specifically investigating the localization support to see if we can adopt it.  Happy to look into this as well.

### 🖥️ Your Environment

latest chrome stable on Linux

OS:   Linux 6.5.5-200.fc38.x86_64 - linux/x64
node: v18.17.1
yarn: 1.22.19
cli:  0.23.0-next.1 (installed)
backstage:  1.19.0-next.1

Dependencies:
  @backstage/app-defaults                                          0.0.0-nightly-20231005021327, 1.4.3
  @backstage/backend-app-api                                       0.5.5
  @backstage/backend-common                                        0.19.7
  @backstage/backend-dev-utils                                     0.1.1
  @backstage/backend-openapi-utils                                 0.0.4
  @backstage/backend-plugin-api                                    0.6.5
  @backstage/backend-tasks                                         0.5.10
  @backstage/catalog-client                                        1.4.4
  @backstage/catalog-model                                         1.4.2
  @backstage/cli-common                                            0.0.0-nightly-20231005021327, 0.1.12, 0.1.13-next.0
  @backstage/cli-node                                              0.0.0-nightly-20231005021327, 0.1.4, 0.1.5-next.0
  @backstage/cli                                                   0.0.0-nightly-20231005021327, 0.22.13, 0.23.0-next.1
  @backstage/config-loader                                         0.0.0-nightly-20231005021327, 1.5.0, 1.5.1-next.0
  @backstage/config                                                1.1.0
  @backstage/core-app-api                                          0.0.0-nightly-20231005021327, 1.10.0, 1.10.1-next.1
  @backstage/core-components                                       0.0.0-nightly-20231005021327, 0.13.5, 0.13.6-next.1
  @backstage/core-plugin-api                                       0.0.0-nightly-20231005021327, 1.6.0, 1.7.0-next.0
  @backstage/dev-utils                                             1.0.21
  @backstage/e2e-test-utils                                        0.0.0-nightly-20231005021327
  @backstage/errors                                                1.2.2
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.0.0, 0.2.0-next.1
  @backstage/frontend-plugin-api                                   0.0.0, 0.1.0, 0.1.1-next.1
  @backstage/integration-aws-node                                  0.1.6
  @backstage/integration-react                                     0.0.0-nightly-20231005021327, 1.1.19, 1.1.20-next.1
  @backstage/integration                                           0.0.0-nightly-20231005021327, 1.7.0, 1.7.1-next.0
  @backstage/plugin-api-docs                                       0.0.0-nightly-20231005021327
  @backstage/plugin-app-backend                                    0.3.53
  @backstage/plugin-app-node                                       0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.1.2
  @backstage/plugin-auth-backend-module-github-provider            0.1.2
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.2
  @backstage/plugin-auth-backend-module-google-provider            0.1.2
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.2
  @backstage/plugin-auth-backend                                   0.19.2
  @backstage/plugin-auth-node                                      0.3.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.2
  @backstage/plugin-catalog-backend                                1.14.0-next.1
  @backstage/plugin-catalog-common                                 1.0.16
  @backstage/plugin-catalog-graph                                  0.2.37-next.1
  @backstage/plugin-catalog-import                                 0.10.1-next.1
  @backstage/plugin-catalog-node                                   1.4.6
  @backstage/plugin-catalog-react                                  0.0.0-nightly-20231005021327, 1.8.4, 1.8.5-next.1
  @backstage/plugin-catalog                                        0.0.0-nightly-20231005021327
  @backstage/plugin-events-node                                    0.2.14
  @backstage/plugin-github-actions                                 0.6.6-next.1
  @backstage/plugin-graphiql                                       0.2.54, 0.2.55-next.1
  @backstage/plugin-org                                            0.6.15-next.1
  @backstage/plugin-permission-common                              0.7.8
  @backstage/plugin-permission-node                                0.7.16
  @backstage/plugin-permission-react                               0.0.0-nightly-20231005021327, 0.4.15, 0.4.16-next.0
  @backstage/plugin-proxy-backend                                  0.4.2
  @backstage/plugin-scaffolder-backend                             1.18.0-next.1
  @backstage/plugin-scaffolder-common                              1.4.1
  @backstage/plugin-scaffolder-node                                0.2.5
  @backstage/plugin-scaffolder-react                               0.0.0-nightly-20231005021327
  @backstage/plugin-scaffolder                                     0.0.0-nightly-20231005021327
  @backstage/plugin-search-backend-module-catalog                  0.1.9
  @backstage/plugin-search-backend-module-pg                       0.5.14
  @backstage/plugin-search-backend-module-techdocs                 0.1.9
  @backstage/plugin-search-backend-node                            1.2.9
  @backstage/plugin-search-backend                                 1.4.5
  @backstage/plugin-search-common                                  1.2.6
  @backstage/plugin-search-react                                   0.0.0-nightly-20231005021327, 1.7.1-next.1
  @backstage/plugin-search                                         1.4.1-next.1
  @backstage/plugin-tech-radar                                     0.6.9-next.1
  @backstage/plugin-techdocs-backend                               1.7.2
  @backstage/plugin-techdocs-module-addons-contrib                 0.0.0-nightly-20231005021327
  @backstage/plugin-techdocs-node                                  1.8.2
  @backstage/plugin-techdocs-react                                 0.0.0-nightly-20231005021327
  @backstage/plugin-techdocs                                       0.0.0-nightly-20231005021327
  @backstage/plugin-user-settings                                  0.0.0-nightly-20231005021327
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            0.0.0-nightly-20231005021327, 1.4.3
  @backstage/theme                                                 0.4.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.5
Done in 1.26s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by gashcrumb** [comment]
I should also ask if there's any issue with my localization setup, I kinda figured it out from the tests and how I would perhaps want to set it up.  Thanks!

**Comment by gashcrumb** [comment]
With a bit of debugging I found that the first issue mentioned where the sidebar doesn't update actually turned out to be user error, I missed that I had forgotten to give the translation ref in the app [it's own unique ID](https://github.com/gashcrumb/backstage-i18n-discovery-nightly/commit/35d16fd30120ce6f91c2d1fa44d4f44a0896d1dc).  So there's just one issue remaining, the language toggle only takes effect on the Language component, the change isn't reflected in the sidebar or the theme selector component:

![image](https://github.com/backstage/backstage/assets/351660/00b0ff74-dcbc-4f11-9910-fdfa65a97004)

**Comment by gashcrumb** [comment]
With a bit more debugging it seems like to ensure the language change is propagated across the app one option could be to add a listener on the observable that this selector posts events at one of the higher level contexts, like AppContext which would ensure everything re-renders when the selector is interacted with.  Like this sledgehammer approach to fixing the issue:

![Screenshot from 2023-10-06 08-48-44](https://github.com/backstage/backstage/assets/351660/d66c9e89-55de-478f-aaf0-6c043f8e65b8)

Maybe creating a LanguageContext that does something like this would be the way to go.

**Comment by Rugvip** [comment]
A language switch is supposed to propagate to observables down to the `useTranslationRef` effect hook [here](https://github.com/backstage/backstage/blob/69652049adb331b441c4bb586e767831d6553988/packages/core-plugin-api/src/translation/useTranslationRef.ts#L59-L74). It starts at the language API subject when the language is switched [here](https://github.com/backstage/backstage/blob/69652049adb331b441c4bb586e767831d6553988/packages/core-app-api/src/apis/implementations/AppLanguageApi/AppLanguageSelector.ts#L121), which in turn is listened to and handled by the translation API implementation [here](https://github.com/backstage/backstage/blob/69652049adb331b441c4bb586e767831d6553988/packages/core-app-api/src/apis/implementations/TranslationApi/I18nextTranslationApi.ts#L283). I'd expect there to be a bug somewhere along this chain that causes the language switching to not properly cause all components to rerender.

**Comment by gashcrumb** [comment]
Thanks for that, very helpful!  It looks like [this could be the disconnect](https://github.com/backstage/backstage/blob/69652049adb331b441c4bb586e767831d6553988/packages/core-app-api/src/apis/implementations/TranslationApi/I18nextTranslationApi.ts#L267-L277) and the subscriber isn't called in some cases.  This seems to fix it for me:

![Screenshot from 2023-10-11 07-20-16](https://github.com/backstage/backstage/assets/351660/f431bb89-0b29-4424-ad06-b0c6390c4071)

I haven't noticed any side effects with this change.

**Comment by camilaibs** [comment]
Thanks for finding a possible solution @gashcrumb, would you mind opening a pull request to fix the bug? We will appreciate the contribution 🙂

**Comment by gashcrumb** [comment]
Thanks!  Found I could tidy things up a little bit too, opened https://github.com/backstage/backstage/pull/20567
