### ISSUE TITLE
🐛 Bug Report: application crashes with OOM on certain search queries

### ISSUE THREAD

**Issue by a-kochetov** [backstage/backstage#20385]
### 📜 Description

Application crashes with FatalProcessOutOfMemory when search request contains specific symbols.

### 👍 Expected behavior

It should return search results.

### 👎 Actual Behavior with Screenshots

It crashes.

<img width="1604" alt="Screenshot 2023-09-21 at 10 57 30" src="https://github.com/backstage/backstage/assets/56634746/c1d82392-1b84-4ee2-86da-dbb1b3318bc7">

<img width="1604" alt="Screenshot 2023-09-21 at 10 58 06" src="https://github.com/backstage/backstage/assets/56634746/79471812-a93c-40a1-b632-444a93d9b4c8">

```
11: 0x16ef479  [node]
10: 0x12c265f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
 9: 0xefed6a v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 8: 0xf1db97 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 7: 0xf1c7ce v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 6: 0xf420cd v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 5: 0xf2fbe5  [node]
 4: 0xd524e7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 3: 0xd52140 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 2: 0xa806a6  [node]
 1: 0xb6b850 node::Abort() [node]
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
<--- JS stacktrace --->

```

### 👟 Reproduction steps

1. Go to search page, i.e. https://demo.backstage.io/search?query=&types%5B%5D=software-catalog
2. Enter following string to search input:
`` jaVasCript:/*-/*`/*\`/*'/*"/**/(/* */oNcliCk=alert())//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/–!>\x3csVg/<sVg/oNloAd=alert()//>\x3e ``
3. Submit search (submit several times if backend served by multiple instances).

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by fedy97** [comment]
Reproducing it locally using the query string provided, the backend does not crash. However, if I try to use a very long string, the backend crashes. So the problem seems to be the length of the query itself.

**Comment by benjdlambert** [comment]
@backstage/discoverability-maintainers can you take a look at this? Is this something that we actually want to fix, or should we re-iterate that it's not recommended to use the in-memory search index, especially when running on heroku. Not sure what the limit that we have there is, but my guess is it's not a lot 😅

**Comment by camilaibs** [comment]
https://github.com/orgs/backstage/teams/discoverability-maintainers gentle ping 🙂

**Comment by djamaile** [comment]
I can reproduce the original issue after submitting and refreshing a couple of times. But that could be related to refreshing and firing of queries to the backend, eventually making it OOM.
