### ISSUE TITLE
🐛 Bug Report: No token provided error in Scaffolder (New AzureDevOps multi org config)

### ISSUE THREAD

**Issue by djflocko** [backstage/backstage#20419]
### 📜 Description

I tried the new azure integration with mullti org like this

```
integrations:
  azure:
    - host: dev.azure.com
      credentials:
        - personalAccessToken: ${PERSONAL_ACCESS_TOKEN}
```

But when I try to execute the Scaffolder Template a error message occurs saying:

```
No token provided for Azure Integration dev.azure.com
```

### 👍 Expected behavior

Scaffolder works with new Azure Multi Orgs

### 👎 Actual Behavior with Screenshots

Error 
```
No token provided for Azure Integration dev.azure.com
```

<img width="1106" alt="image001" src="https://github.com/backstage/backstage/assets/15978502/d7b107d9-5db1-458a-a9dd-5b9a900470fd">

### 👟 Reproduction steps

1. Go to Software Templates
2. Select a template that should be published to Azure Devops 
3. Select the org in the repopicker
4. Execute
5. --> Error

### 📃 Provide the context for the Bug.

use the software templates

### 🖥️ Your Environment

OS:   Darwin 22.5.0 - darwin/arm64
node: v18.16.1
yarn: 1.22.19
cli:  0.22.12 (installed)
backstage:  1.18.3

Dependencies:
  @backstage/app-defaults                                          1.4.3
  @backstage/backend-app-api                                       0.5.4
  @backstage/backend-common                                        0.19.6
  @backstage/backend-dev-utils                                     0.1.1
  @backstage/backend-openapi-utils                                 0.0.4
  @backstage/backend-plugin-api                                    0.6.4
  @backstage/backend-tasks                                         0.5.9
  @backstage/catalog-client                                        1.4.4
  @backstage/catalog-model                                         1.4.2
  @backstage/cli-common                                            0.1.12
  @backstage/cli-node                                              0.1.4
  @backstage/cli                                                   0.22.13
  @backstage/config-loader                                         1.5.0
  @backstage/config                                                1.1.0
  @backstage/core-app-api                                          1.10.0
  @backstage/core-components                                       0.12.5, 0.13.5
  @backstage/core-plugin-api                                       1.6.0
  @backstage/errors                                                1.2.2
  @backstage/eslint-plugin                                         0.1.3
  @backstage/integration-aws-node                                  0.1.6
  @backstage/integration-react                                     1.1.19
  @backstage/integration                                           1.7.0
  @backstage/plugin-api-docs                                       0.9.11
  @backstage/plugin-app-backend                                    0.3.52
  @backstage/plugin-app-node                                       0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.1.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.1
  @backstage/plugin-auth-backend-module-google-provider            0.1.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.1
  @backstage/plugin-auth-backend                                   0.19.1
  @backstage/plugin-auth-node                                      0.3.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.1
  @backstage/plugin-catalog-backend                                1.13.2
  @backstage/plugin-catalog-common                                 1.0.16
  @backstage/plugin-catalog-graph                                  0.2.36
  @backstage/plugin-catalog-import                                 0.10.0
  @backstage/plugin-catalog-node                                   1.4.5
  @backstage/plugin-catalog-react                                  1.8.4
  @backstage/plugin-catalog                                        1.13.0
  @backstage/plugin-devtools-backend                               0.2.1
  @backstage/plugin-devtools-common                                0.1.4
  @backstage/plugin-devtools                                       0.1.4
  @backstage/plugin-events-node                                    0.2.13
  @backstage/plugin-github-actions                                 0.6.5
  @backstage/plugin-home-react                                     0.1.3
  @backstage/plugin-home                                           0.5.8
  @backstage/plugin-org                                            0.6.14
  @backstage/plugin-permission-common                              0.7.8
  @backstage/plugin-permission-node                                0.7.15
  @backstage/plugin-permission-react                               0.4.15
  @backstage/plugin-proxy-backend                                  0.4.1
  @backstage/plugin-scaffolder-backend                             1.17.2
  @backstage/plugin-scaffolder-common                              1.4.1
  @backstage/plugin-scaffolder-node                                0.2.4
  @backstage/plugin-scaffolder-react                               1.5.5
  @backstage/plugin-scaffolder                                     1.15.0
  @backstage/plugin-search-backend-module-catalog                  0.1.8
  @backstage/plugin-search-backend-module-pg                       0.5.13
  @backstage/plugin-search-backend-module-techdocs                 0.1.8
  @backstage/plugin-search-backend-node                            1.2.8
  @backstage/plugin-search-backend                                 1.4.4
  @backstage/plugin-search-common                                  1.2.6
  @backstage/plugin-search-react                                   1.7.0
  @backstage/plugin-search                                         1.4.0
  @backstage/plugin-tech-radar                                     0.6.8
  @backstage/plugin-techdocs-backend                               1.7.1
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.0
  @backstage/plugin-techdocs-node                                  1.8.1
  @backstage/plugin-techdocs-react                                 1.1.11
  @backstage/plugin-techdocs                                       1.7.0
  @backstage/plugin-user-settings                                  0.7.10
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.3
  @backstage/theme                                                 0.2.19, 0.4.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.5

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by fstoerkle** [comment]
You might need to specify the organization in the config, like so:

```yaml
integrations:
  azure:
    - host: dev.azure.com
      credentials:
        - organizations:
            - ORG_NAME
          personalAccessToken: THE_ACCESS_TOKEN
```

See the Azure integration docs (https://backstage.io/docs/integrations/azure/locations) and the new multi-org support introduced in https://github.com/backstage/backstage/pull/18213
