### ISSUE TITLE
🙏  Help Wanted: Replacing mock-fs in tests

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#20436]
While [mock-fs](https://www.npmjs.com/package/mock-fs) has been a great utility for mocking filesystem operations in tests, it requires quite a lot of maintenance to keep up to date with Node.js updates. This is because it mocks the internal bindings of the filesystem module, which is not stable API. We've recently seen an increasing number of breakages, while `mock-fs` has remained largely unmaintained and not merging fixes or releasing new versions. Because of this we've made the decision to move away from using `mock-fs` in tests.

As a replacement for `mock-fs` we instead use temporary directories that we clean up tests have completed. This has been wrapped up in an API from `@backstage/backend-test-utils` that lets you create a directory, populate it with contents using an API similar to `mock-fs`, and also read back contents from the directory. It's called `createMockDirectory` and you can see all the details of it in the [API reference](https://backstage.io/docs/reference/backend-test-utils.createmockdirectory).

We still have a couple of usage of `mock-fs` left however, and would love some help in refactoring theses tests to get some feedback on the new API. To find existing usages, search for `'mock-fs'` and you'll find the imports. The following PR can be used as a reference for how to migrate a couple of the different patterns we use in tests: https://github.com/backstage/backstage/pull/20404/

Some pointers:
- `mockFs({...})` is replaced by `mockDir.setContent({...})`
- Any pass-through of existing files via `mockFs.load` can be removed, we no longer mock the entire filesystem access
- There is no need to explicitly clean up the mock directory after the tests have run, that happens automatically
- `mockFs.restore()` can be removed and does not need to be replaced
- `mockFs.directory()` is replaced with an empty object: `{}`
- A common pattern with `mock-fs` was to use something like a virtual `/root` dir and then pass that to test subject. Remove the `/root` layer from the `mockDir.setContent()` call and pass `mockDir.path` to the subject instead.

Appreciate any and all help! 🙏 ❤️ 

If you do pick something up, please mentioned in a comment which tests you're working on

**Comment by gibsonliketheguitar** [comment]
Hello there friends, I'd like to help on this task

**Comment by Atharva1723** [comment]
Can I work on this ?

**Comment by kurtaking** [comment]
I will work on `packages/cli`, and likely all `cli`-related packages.

**Comment by benjdlambert** [comment]
Hey @gibsonliketheguitar @Atharva1723 please go ahead and pick some things up!

This ticket scope is quite large, so maybe just scope your PR's to one or two packages at a time so we can review them easier.

Just drop a comment on which ones you're planning to pick up so we don't stand on each others toes! :pray:

**Comment by Naycon** [comment]
I have plans on joining in on this as well. Started working on the `cli` package.

**Comment by iamshabell** [comment]
I'm joining on this as well, took `cli-node` and `repo-tools` packages.

**Comment by Atharva1723** [comment]
@benjdlambert on what packages should i work? Can you assign me a package ,just to ensure i am not interfering in any other packages !!

**Comment by Atharva1723** [comment]
@benjdlambert One small question can you just tell me what is need to be done in the kubernetes-backend??

**Comment by kurtaking** [comment]
Can anyone provide a migration example for this mockFs code?
```
mockFs({
      '/root': {
        plugins: mockFs.directory(),
      },
      [paths.resolveOwn('templates')]: mockFs.load(
        paths.resolveOwn('templates'),
      ),
    });
```

**Comment by benjdlambert** [comment]
@kurtaking @Atharva1723 you should be able to see some examples of the migration that needs to happen in this PR: https://github.com/backstage/backstage/pull/20404/files or https://github.com/backstage/backstage/pull/20505

**Comment by Rugvip** [comment]
@kurtaking `mockFs.directory()` is replaced by an empty object, `{}`, and the `mockFs.load` entry can be removed completely since we now always have access to the real filesystem

**Comment by kurtaking** [comment]
> @kurtaking `mockFs.directory()` is replaced by an empty object, `{}`, and the `mockFs.load` entry can be removed completely since we now always have access to the real filesystem

Thank you, I was looking this past weekend, and got caught up on a few of them. I'll post if I get time to pick up something.

**Comment by cindycs212** [comment]
hey! I'm working on the confluenceToMarkdown tests

**Comment by awanlin** [comment]
> hey! I'm working on the confluenceToMarkdown tests

Hi @cindycs212, tag me in the PR for that and I can help review, I've done work in the action before 🚀

**Comment by cindycs212** [comment]
Hi @awanlin ! I've tagged you :) thanks!
