### ISSUE TITLE
🐛 Bug Report: TechDocsDocument should be in common package

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#20476]
### 📜 Description

https://github.com/backstage/backstage/blob/master/plugins/techdocs-node/src/techdocsTypes.ts#L23 is now in `node` plugin and not usable in the frontend

### 👍 Expected behavior

TechDocsDocument should be moved to `techdocs-common` plugin

### 👎 Actual Behavior with Screenshots

Cannot import `TechDocsDocument` in `app` as it is `node` plugin

### 👟 Reproduction steps

Try to use `TechDocsDocument` in `app`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by fedy97** [comment]
did you consider using `TechDocsEntityMetadata` in react?

**Comment by drodil** [comment]
Well, it's not the same thing. When doing customization of search results, you need the type that extends `IndexableDocument` to access the fields. Just like `CatalogEntityDocument`.

**Comment by fedy97** [comment]
There is no `techdocs-common` plugin. A fast fix would be to dulicate the code of `TechDocsDocument` inside `techdocs-react` plugin

**Comment by drodil** [comment]
Or just make it properly and create `techdocs-common` plugin and deprecate the `TechDocsDocument` from the `node` plugin

**Comment by fedy97** [comment]
I am wondering if there is any reason of why there is not yet present a `techdocs-common` plugin

**Comment by freben** [comment]
@drodil Are you up for this?

**Comment by drodil** [comment]
Not stale
