### ISSUE TITLE
🚀 Feature: Make page size for getOrganizationRepositories configurable in githubEntityProvider

### ISSUE THREAD

**Issue by Revyy** [backstage/backstage#20475]
### 🔖 Feature description

Make the page size configureable for the `getOrganizationRepositories` query used by the `GithubEntityProvider`.
This could be extended to the other queries as well I suppose but we have not had any issues with those yet.

Reopening https://github.com/backstage/backstage/issues/15982.

### 🎤 Context

As explained in the previous issue(https://github.com/backstage/backstage/issues/15982) , the query fails on the Github side due to too much data being requested. 

The issue has ramped up for us and now we are at the level where we can't ingest new entities from Github using the provider.

Copied error from previous issue:
```json
{"class":"GithubEntityProvider","level":"error","message":"Unknown error: {\"data\":null,\"errors\":[{\"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `XXXXXXXXXXXXXXXX` when reporting this issue.\"}]}","name":"HttpError","plugin":"catalog","request":{"body":"{\"query\":\"\\n    query repositories($org: String!, $catalogPathRef: String!, $cursor: String) {\\n      repositoryOwner(login: $org) {\\n        login\\n        repositories(first: 100, after: $cursor) {\\n          nodes {\\n            name\\n            catalogInfoFile: object(expression: $catalogPathRef) {\\n              __typename\\n              ... on Blob {\\n                id\\n                text\\n              }\\n            }\\n            url\\n            isArchived\\n            repositoryTopics(first: 100) {\\n              nodes {\\n                ... on RepositoryTopic {\\n                  topic {\\n                    name\\n                  }\\n                }\\n              }\\n            }\\n            defaultBranchRef {\\n              name\\n            }\\n          }\\n          pageInfo {\\n            hasNextPage\\n            endCursor\\n          }\\n        }\\n      }\\n    }\",\"variables\":{\"org\":\"myorg\",\"catalogPathRef\":\"HEAD:.backstage/**/*.yaml\",\"cursor\":\"Y3Vyc29yOnYyOpHOElzwKQ==\"}}","headers":{"accept":"application/vnd.github.v3+json","authorization":"Bearer [REDACTED]","content-type":"application/json; charset=utf-8","user-agent":"octokit-graphql.js/5.0.1 Node.js/16.19.0 (linux; x64)"},"method":"POST","url":"https://api.github.com/graphql"},"response":{"data":{"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `XXXXXXXXXXXXXXXX` when reporting this issue."}]},"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset","connection":"close","content-type":"application/json","date":"Sun, 22 Jan 2023 11:47:25 GMT","server":"GitHub.com","transfer-encoding":"chunked","vary":"Accept-Encoding, Accept, X-Requested-With","x-github-request-id":"XXXXXXXXXXXXXXXX"},"status":502,"url":"https://api.github.com/graphql"},"service":"backstage","stack":"HttpError: Unknown error: {\"data\":null,\"errors\":[{\"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `XXXXXXXXXXXXXXXX` when reporting this issue.\"}]}\n    at /app/node_modules/@octokit/request/dist-node/index.js:88:21\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async queryWithPaging (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:346:22)\n    at async getOrganizationRepositories (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:304:24)\n    at async GithubEntityProvider.findCatalogFiles (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:907:54)\n    at async GithubEntityProvider.refresh (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:879:21)\n    at async TaskWorker.fn (/app/node_modules/@backstage/plugin-catalog-backend-module-github/dist/index.cjs.js:867:13)\n    at async TaskWorker.runOnce (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:349:7)\n    at async /app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:302:31","status":502,"target":"github-provider:myorg_services","taskId":"github-provider:myorg_services:refresh","taskInstanceId":"fa122bd6-5c1e-4b43-a560-ceb9de5356a7","type":"plugin"}
```

As commented by @JedGilbert in the previous issue(https://github.com/backstage/backstage/issues/15982#issuecomment-1715660730), the Github support team suggests tweaking the page size to reduce the amount of data being processed. I can also confirm that changing the value in the node-modules folder does fix the issue for us as well.

### ✌️ Possible Implementation

A simple solution would be to add a way to configure the page size of (at least) the query executed by the `getOrganizationRepositories` function. 

The value can still default to 100 if not overridden.

You could update https://github.com/backstage/backstage/blob/414dd72078f9c0127e7a5257b748ef9fed6c95f8/plugins/catalog-backend-module-github/src/lib/github.ts#L448 to take another parameter to tweak the page size.

Then change the query by adding a pageSize parameter.

```typescript
  const query = `
    query repositories($org: String!, $catalogPathRef: String!, $pageSize: Int!, $cursor: String) {
      repositoryOwner(login: $org) {
        login
        repositories(first: $pageSize, after: $cursor) {
...
`
```

Don't have any great suggestions for how to structure this in the configuration though as this is a fairly low level thing to configure.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Nice, thanks for hunting this down! If I understand it correctly, it'd be pretty fine to just hard code that page limit to, say, 50 to be conservative. Putting it all the way up to 100 probably won't make a huge difference performance wise, for most reasonable installations, so better safe than sorry.

Would you like to make a PR for that? 🙏

**Comment by Revyy** [comment]
@freben Thank you for making the PR, I was away for a bit so didn't keep track on the issue.
