### ISSUE TITLE
Upgrade lerna

### ISSUE THREAD

**Issue by JoseHervas** [backstage/backstage#20484]
### 🔖 Feature description

Currently new generated apps with Backstage are using an outdated version of lerna (v4.0.0). New apps should use the latest version of lerna (currently v7.3.0)

### 🎤 Context

Lerna v4 has some security vulnerabilities that have been fixed on the newest versions

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @JoseHervas, my understanding is that with the upgrade to Yarn 3 Lerna is no longer needed and can be removed. That's been the case for our Backstage instance. 

There's a migration guide to Yarn 3 here: https://backstage.io/docs/tutorials/yarn-migration

@Rugvip, when you have some time can you confirm that I've got this right?

**Comment by Rugvip** [comment]
Yep, still makes sense to bump Lerna in the template though since it's what we ship by default.

Appreciate any help here and thank you for the heads up!

**Comment by awanlin** [comment]
Thanks @Rugvip for following up, somehow forgot about create-app 🤦 

Many thanks @JoseHervas for the PR to update this 🚀
