### ISSUE TITLE
🚀  [LightHouse] Feature: UI Error Message Handling

### ISSUE THREAD

**Issue by MasthanSK121** [backstage/backstage#20485]
### 🔖 Feature description

In the lighthouse plugin when user is provided the invalid url, the API returning error message is not showing in the UI.
I am not sure, why UI showing different message and API is showing different message.
Need to show the API returning error message in the UI for better user experience.

### 🎤 Context

Suppose when user is provided invalid url(https://spotify/) in the managed plugin section and saved it. When user is opened the component and navigates to the lighthouse tab and seeing the error message like "No records to display" in the audit table but the API is showing the error message like "no audited website found for url "https://spotify/" in the network tab.
I am not sure, why UI showing different message and API is showing different message.
Need to show the API returning error message in the UI for better user experience.

### ✌️ Possible Implementation

None

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by tudi2d** [comment]
Hej - thanks for reporting. I will convert this into a feature request for the LightHouse Plugin as this is not a new plugin request.

**Comment by MasthanSK121** [comment]
Hi @tudi2d , Thanks for the update. sorry, i am unable to contribute due to the other priorities.
