### ISSUE TITLE
🚀 Feature: Adding private and public filters in playlist plugin

### ISSUE THREAD

**Issue by AmbrishRamachandiran** [backstage/backstage#20528]
### 🔖 Feature description

![image](https://github.com/backstage/backstage/assets/133481507/1257c3ff-6464-491f-9565-3ad5b4b661f7)

In a playlist plugin page if a user quickly wants to filter out all the public playlist there is no options currently , user needs to scroll and check the each of the icons whether lock icon or without it. 

It will consume the time of the user so keeping a public/private filter similar to the owned/following filter may help user to filter and find out easily.

### 🎤 Context

In a playlist plugin page if a user quickly wants to filter out all the public playlist there is no options currently , user needs to scroll and check the each of the icons whether lock icon or without it. 

It will consume the time of the user so keeping a public/private filter similar to the owned/following filter may help user to filter and find out easily.

### ✌️ Possible Implementation

1. Keeping a public / private filter similar to owned / following
2. Keeping a dropdown filter with public/private checkbox similar to Owner filter
3. Suggestions are welcome

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by AmbrishRamachandiran** [comment]
@All suggestions are welcome , if any other users also thinks in a similar way

**Comment by camilaibs** [comment]
Thank you @AmbrishRamachandiran for being willing to contribute to us 🎉 
Hi @kuangp, any recommendations? Feel free to reopen the pull request too 🙂

**Comment by kuangp** [comment]
I think this feature makes sense - eventually I do want to make this page fully customizable similar to the catalog page but for now I think it's useful to add this filter to the default page. I would still recommend my suggestion I made in the original PR to not put it inside the "Personal" section since public and private are not "personal filters" - perhaps create a separate dropdown "Visibility" filter instead?
