### ISSUE TITLE
🚀 Feature: option to create multiple branches in publish:github action

### ISSUE THREAD

**Issue by pascalgulikers** [backstage/backstage#20525]
### 🔖 Feature description

For the publish:gitlab action, some additional options were provided based on https://github.com/backstage/backstage/issues/19958

See: https://github.com/backstage/backstage/pull/19959/files and
https://github.com/backstage/backstage/blob/815d7986337c376d835795c4577d77ff14372d0d/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/gitlab.ts#L59

Could the same be implemented for the publish:github action as well? Especially the creation of multiple branches would be nice.

### 🎤 Context

By initializing a new Github repo based on a template, it would be nice to create a release and develop branch together with a default branch (main).

### ✌️ Possible Implementation

Same implementation as for Gitlab: see https://github.com/backstage/backstage/issues/19958 and related PR https://github.com/backstage/backstage/pull/19959

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Thank you for opening this issue! 👍

We'll leave this one open to community contributions. If anyone wants to work on this, please chime in, any help is appreciated! 🙏
