### ISSUE TITLE
🚀 Feature: export SecureTemplater and createDefaultFilters

### ISSUE THREAD

**Issue by fedy97** [backstage/backstage#20529]
### 🔖 Feature description

In our application, we need to extend the `handler` function of `createFetchTemplateAction` in order to add a custom behaviour. In order to do that, by importing the function `createFetchTemplateAction` in our codebase, we realized that 2 of its imports are not exported in backstage in the `index.ts`: `SecureTemplater` and `createDefaultFilters`.

### 🎤 Context

It would be great to export `SecureTemplater` and `createDefaultFilters` in order not to have to import their code too in our codebase but just import them from backstage

### ✌️ Possible Implementation

export `SecureTemplater` and `createDefaultFilters` in the `index.ts`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hi @fedy97, thanks for your interest in contributing to us, we appreciate it 🙂 .
Let me put you in contact with @benjdlambert, he has a context that makes us consider not proceeding with this feature request. Could you share it here, Ben?

**Comment by fedy97** [comment]
Thank you for your answer. So right now I have imported `SecureTemplater` and `createDefaultFilters` in our application so that we can extend the `handler` function of the `fetch:template` action. Is there a better way to do that?

**Comment by benjdlambert** [comment]
@fedy97 what is it you're wanting to extend with that handler exactly? We've also been exploring the ability to execute other steps part of an action, something like `ctx.invoke({...})` or something.

**Comment by fedy97** [comment]
> @fedy97 what is it you're wanting to extend with that handler exactly? We've also been exploring the ability to execute other steps part of an action, something like `ctx.invoke({...})` or something.

I want to add to the `catalog-info.yaml` generated, a new key that contains an object of all the input raw values coming from the template wizard. To do that, I need to access the `ctx.input.value` object that is available inside that handler function.

**Comment by benjdlambert** [comment]
Hey @fedy97 so just so I understand properly, you want to run `fetch:template` but then put template all the values from `{{ values }}` somewhere? 

I'm not quite understanding what you want to do fully. So if you could elaborate a bit more might help.

But you should be able to pass in `{{ values | dump }}` or something to print all values I think?

**Comment by fedy97** [comment]
this can be closed for now
