### ISSUE TITLE
🚀 Feature: allow to use template parameters in EntityPicker catalogFilter

### ISSUE THREAD

**Issue by ikatlinsky** [backstage/backstage#20533]
### 🔖 Feature description

We need the ability to provide EntityPicker catalogFilter restriction based on the value of another EntityPicker or other field type in scaffolder templates.

For example

```diff
parameters:
    - title: Service Settings
      properties:
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Domain
            defaultKind: Domain
            allowArbitraryValues: false
         product:
            title: Product
            type: string
            ui:field: EntityPicker
            ui:options:
              catalogFilter:
                - kind: System
+                 spec.domain: '{{ parameters.system }}'
              defaultKind: System
              allowArbitraryValues: false
```

### 🎤 Context

In our use case, we have Domains and Systems, each System is related to a specific Domain. When in the template we are selecting a specific Domain in one EntityPicker, we expect that System-related EntityPicker will show only Systems, which are related to a selected Domain.

The current implementation of EntityPicker has a catalogFilter, but it does not support nunjucks templating, which does not allow us to implement the described case.

### ✌️ Possible Implementation

EntityPicker can make use of nunjucks templating support to allow dynamic catalogFilter. As an example implementation:

- update [convertSchemaFilterToQuery](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/EntityPicker/EntityPicker.tsx#L200C10-L200C37)

```diff
+ import { renderString } from 'nunjucks';

function convertSchemaFiltersToQuery(
  schemaFilters: EntityPickerFilterQuery,
+ context: object,
): Exclude<EntityFilterQuery, Array<any>> {
  const query: EntityFilterQuery = {};

  for (const [key, value] of Object.entries(schemaFilters)) {
+   if (typeof value === 'string') {
+     query[key] = renderString(value, context);
+   } else if (Array.isArray(value)) {
+     query[key] = value.map(v => renderSting(v, context));
    } else {
      query[key] = convertOpsValues(value);
    }
  }

  return query;
}
```

- update [buildCatalogFilter](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/EntityPicker/EntityPicker.tsx#L224C10-L224C28)

add new context parameter

- update [catalogFilter build logic](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/EntityPicker/EntityPicker.tsx#L62)

```diff
- const catalogFilter = buildCatalogFilter(uiSchema);

+ const [catalogFilter, setCatalogFilter] = useState<EntityFilterQuery>();

  const { value: entities, loading } = useAsync(async () => {
    const { items } = await catalogApi.getEntities(
      catalogFilter ? { filter: catalogFilter } : undefined,
    );
    return items;
- });
+ }, [catalogFilter]);

+ useEffect(() => {
+    setCatalogFilter(buildCatalogFilter(uiSchema, {
+      parameters: formContext.formData,
+    }));
+   }, [formContext.formData]);
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hi @ikatlinsky 👋🏻 , thanks for opening this issue.
In conversation with @benjdlambert, he shared that there is an RFC  https://github.com/backstage/backstage/issues/16275 for this feature request, so we are centralizing the conversation there.
You are more than welcome to share your proposal there as well 🙌🏻 , we are going to close this issue.
