### ISSUE TITLE
🚀 Feature: Add status indicator to the github-pull-requests-board

### ISSUE THREAD

**Issue by efenner-cambia** [backstage/backstage#20546]
### 🔖 Feature description

When looking at a list of PRs in GitHub, there is generally an ❌, ✅, or 🟡 icon next to the PR title that indicates whether or not any pipelines or checks associated with the latest commit on that PR have passed. It would be useful to include this on the PR cards in the github-pull-requests-board plugin.

### 🎤 Context

When looking at a collection of PRs like what is shown on the github-pull-requests-board, being able to see which ones are already passing their checks without having to click into each one makes prioritizing them for review much faster. For example, a PR generated by a bot like Renovate would be easy to go ahead and merge as long as it is passing its checks.

### ✌️ Possible Implementation

The GitHub API does not return the statuses directly, but it does return a `statuses_url` that can be called to retrieve the list of statuses associated with the latest commit. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by camilaibs** [comment]
Hello @gregorytalita, do you have any recommendations for someone who wants to try to work on this issue 🙂 ?

**Comment by gregorytalita** [comment]
Hello 👋

That is such a good suggestion 🤩 It will definitely improve how the board sorts the Pull Requests to be reviewed! 

I have found the [Github API ](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28) mentioned by @efenner-cambia and we can collect the _combined status by reference_ (which would be the over all PR status 🥳) as [mentioned here](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#get-the-combined-status-for-a-specific-reference) on the documentation.

Although! Might be easier to continue using the GraphQL APIs 🤗 We can update the query within [useGetPullRequestDetails](https://github.com/backstage/backstage/blob/master/plugins/github-pull-requests-board/src/api/useGetPullRequestDetails.ts) to collect the **last commit** and its **status**.
I have found [this example](https://github.com/isaacs/github/issues/1710#issuecomment-870418239) by @kevinmukuna (from 2021 😅 but I hope it still relevant). We can also see the GraphQL reference itself for [PullRequest](https://docs.github.com/en/graphql/reference/objects#pullrequest)

I'm happy to jump on this issue as soon as I can if no one jump in first 🤓

**Comment by camilaibs** [comment]
Thanks for the recommendations @gregorytalita, it would be awesome if you could help us with this contribution too and @efenner-cambia is more than welcome to review the pull request 🙌🏻

**Comment by efenner-cambia** [comment]
@gregorytalita Are you still working on this?

**Comment by efenner-cambia** [comment]
bump

**Comment by Rugvip** [comment]
@efenner-cambia I checked with @gregorytalita and she's not working on this at the moment, so this is open to community contributions. If anyone wants to work on this, please chime in, any help is appreciated! 🙏

**Comment by Josh-Uvi** [comment]
Hello @Rugvip, I would like to work on this feature request.

**Comment by kevinmukuna** [comment]
@Josh-Uvi let me know if you need hand

**Comment by Josh-Uvi** [comment]
@Rugvip @kevinmukuna PR opened [here](https://github.com/backstage/backstage/pull/22792)

**Comment by freben** [comment]
Done!

**Comment by efenner-cambia** [comment]
Small enhancement idea to follow up on this. It would be great to add color chips next to the text status like [the status component in the storybook](https://backstage.io/storybook/?path=/story/data-display-status--default)

**Comment by efenner-cambia** [comment]
@Josh-Uvi should I create a separate feature request over in the [community-plugins](https://github.com/backstage/community-plugins) repo?

**Comment by juvi07** [comment]
> @Josh-Uvi should I create a separate feature request over in the [community-plugins](https://github.com/backstage/community-plugins) repo?

Hi @efenner-cambia, apologies for the delayed response. Please feel free to add it to the [community-plugins](https://github.com/backstage/community-plugins) repository.
