### ISSUE TITLE
🐛 Bug Report: Sonarqube Plugin Not Rendering Content

### ISSUE THREAD

**Issue by stu039** [backstage/backstage#20542]
### 📜 Description

Setup followed from docs, using this in app-configuration

```
sonarqube:
  instances:
    - name: default
      baseUrl: https://sonarqube.myorg.org
      apiKey: xxxxx
```

and the annotation on the entity as follows:

```
  annotations:
    sonarqube.org/project-key: myprojectkey
```

The backend returns 200 with an empty response, so I would expect to see some kind of error/warning if there was a setup issue.

I have also tested out the api calls that the plugin makes internally to the sonarqube API, and they have returned the expected data, so the issue is not with my sonarqube instance/ it's setup.

Not sure how else to debug this my side so raising this issue here.

### 👍 Expected behavior

It should render the sonarqube entity card with the data for the given project

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/48241332/63698bab-845b-4490-916b-9d42db9023ed)

### 👟 Reproduction steps

Follow setup steps of sonarqube plugin

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sennyeya** [comment]
👋 thanks for this! Can you share the request and response from your browser to the backend? The config looks correct.

**Comment by stu039** [comment]
![image](https://github.com/backstage/backstage/assets/48241332/960203fd-c78e-41b3-8a64-7af652de6a24)

![image](https://github.com/backstage/backstage/assets/48241332/72ce182e-7843-48bb-995f-0d435a03877e)

Interestingly today this does have content in the response - must have tweaked something as yesterday I was seeing it blank. Still have the same result in the app though

**Comment by camilaibs** [comment]
Hi @backstage/sda-se-reviewers 👋🏻 , do you have any recommendations for @stu039 ? He wants to contribute with a fix 🙂

**Comment by jsfpdn** [comment]
Hi, we had the same problem - the issue is that the sonarqube-backend plugin returned 200 to the frontend even though sonarqube responded with 401 unauthorized (we had to check the sonarqube access log to find out). In our case, we used the wrong credentials, I suggest you double check the creds as well :)

**Comment by Hennnnes** [comment]
Hey @stu039,
I think the peace of code that needs to be improved is this one right here:
https://github.com/backstage/backstage/blob/8e741a1bd29b92c767e9b308f151d10468be1980/plugins/sonarqube-backend/src/service/sonarqubeInfoProvider.ts#L305-L308

That function should additionally be handy to figure out what the sonarqube api returns right now in your case :)

**Comment by Sahana-Nagaraja** [comment]
I was facing a similar issue. I had initially used a Global analysis token as an apiKey in Backstage, I later changed that to a User token and it worked for me
