### ISSUE TITLE
🐛 Bug Report: ExpandableNavigation causes copy code button to be in the wrong place

### ISSUE THREAD

**Issue by kunickiaj** [backstage/backstage#20552]
### 📜 Description

ExpandableNavigation TechDocs Addon is enabled.

### 👍 Expected behavior

Not change how other components are rendered and the copy code button should be well aligned on the right.

### 👎 Actual Behavior with Screenshots

<img width="863" alt="Screenshot 2023-10-11 at 16 32 01" src="https://github.com/backstage/backstage/assets/746474/14f853eb-f08d-416d-86d8-062191ab672f">
<img width="864" alt="Screenshot 2023-10-11 at 16 32 15" src="https://github.com/backstage/backstage/assets/746474/31be6c89-466f-4b83-9102-2ee8c25df1e7">

Note: enabling the TextSize addon seems to fix this behavior.

Instead its rendered on the left and kinda squished.

### 👟 Reproduction steps

1. Enable the ExpandableNavigation TechDocs Addon
2. View docs with a fenced code block

### 🖥️ Your Environment

Backstage 1.18.5
Chrome (latest)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hi @kunickiaj, thanks for willing to submit a pull request, I assigned the issue to you 🙌🏻
Do you have any recommendations @backstage/techdocs-maintainers ?

**Comment by agentbellnorm** [comment]
@kunickiaj Can you provide your techdocs config? I am not able to reproduce on the current master (6bad140c57257802d0ce6b1271622d5d88b269c5) with the default image `spotify/techdocs:v1.2.3` building in docker.

I've tried with and without the `<TextSize/>` addon.
