### ISSUE TITLE
🚀 Feature: Icons for Custom Kinds

### ISSUE THREAD

**Issue by HydraShield** [backstage/backstage#20583]
### 🔖 Feature description

Regarding Icon provide by backstage

### 🎤 Context

currently there are some icon provide by backstage like kind:api, kind:component etc...
sometimes to develop portal we have database, bucket, thirdpartyservice or some more and uncatalogued kind for that there is no icon so if it possible to add new icons

### ✌️ Possible Implementation

just to add new icon with key and icon from material-ui/icons/ or other library

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @HydraShield, there's some good documentation on how to add custom icons and how to use them here: https://backstage.io/docs/getting-started/app-custom-theme#icons

Where there is a gap is how to make them work with custom Kinds that you might add yourself based on your needs. For example if I add a new Kind called "Product" I have no way to associate that with a specific icon I've added following the docs linked above. At least that I know of.

Hope this helps a little?

**Comment by awanlin** [comment]
Oh, I also updated the title to be a bit more descriptive, if what I used is not right feel free to change it 👍

**Comment by freben** [comment]
You can give additional such icons [to `createApp` in your app](https://github.com/backstage/backstage/blob/master/packages/app/src/App.tsx#L128). Name them e.g. `'kind:product': MyIcon`.

**Comment by awanlin** [comment]
Oh, sweet! Didn't know it was that simple, thanks @freben

**Comment by sharknoon** [comment]
@freben Thank you for this clarification. I have tried your suggestion but unfortunately it doesn't work for me. There is still a question mark as the icon. Has this implementation changed?

**Comment by Chris-Lee-Ca** [comment]
I have also tried your suggestion, but it doesn't work for me either.

**Comment by midskyey** [comment]
As of 1.38.1, for the use-case of displaying the kind icon beside the entity link in Catalog, managed to get it working customizing `entityPresentationApiRef` (which is originally [here](https://github.com/backstage/backstage/blob/v1.38.1/plugins/catalog/src/plugin.ts#L79-L84)) with custom `kindIcons` in `App.tsx` (doesn't seem to be in the docs at the moment, and I'm not sure if it's the blessed way)

```ts

import { createApiFactory } from '@backstage/core-plugin-api';
import {
  catalogApiRef,
  entityPresentationApiRef,
} from '@backstage/plugin-catalog-react';
import { DefaultEntityPresentationApi } from '@backstage/plugin-catalog';
import AcUnitIcon from '@material-ui/icons/AcUnit';
import { apis } from './apis';

const app = createApp({
  apis: [
    ...apis,
    createApiFactory({
      api: entityPresentationApiRef,
      deps: { catalogApi: catalogApiRef },
      factory: ({ catalogApi }) =>
        DefaultEntityPresentationApi.create({
          catalogApi,
          kindIcons: {
            // your kinds, something like
            workload: AcUnitIcon,
          },
        }),
    }),
  ],

  // ...
```
