### ISSUE TITLE
🐛 Bug Report: Multiple Selects UI

### ISSUE THREAD

**Issue by paulpruteanu-cbi** [backstage/backstage#20588]
### 📜 Description

```js
import { Select } from '@backstage/core-components';
<Select
            multiple
            placeholder="All"
            label="Team filter"
            items={items}
            selected={value}
            onChange={items => onChange((items || []) as string[])}
          />
```
pressing the X button pops up the multiple select values rather than deselecting the selected option

### 👍 Expected behavior

to drop the selected value from the list and not pop up the list of all options

### 👎 Actual Behavior with Screenshots

pops up the list of all options and does not select the selected option to be "x"-ed.

### 👟 Reproduction steps

use the behavior of any <Select> core component.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by krunalhinguu** [comment]
@paulpruteanu-cbi is there any way to replicate this issue?

**Comment by tudi2d** [comment]
Thanks for the report @paulpruteanu-cbi! For reference: I can reproduce it in[ the Storybook for the `Select` component](https://backstage.io/storybook/?path=/story/inputs-select--multiple). In most places where this behaviour is needed in Backstage, like the Catalog, we are using the [`Autocomplete` component from Material UI](https://mui.com/material-ui/react-autocomplete/#multiple-values), which does not face this issue. This could be a valid & future proof work around in your case.

That said - the component should be fixed.
