### ISSUE TITLE
🐛 Bug Report: npx @backstage/create-app@latest generates broken docker file

### ISSUE THREAD

**Issue by r331** [backstage/backstage#20581]
### 📜 Description

The generated docker image doesn't work.

### 👍 Expected behavior

Docker image should start

### 👎 Actual Behavior with Screenshots

                            
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'express-promise-router'
Require stack:
- /app/packages/backend/dist/index.cjs.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/app/packages/backend/dist/index.cjs.js:3:14)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/packages/backend/dist/index.cjs.js' ]
}

Node.js v18.18.1

### 👟 Reproduction steps

My steps:

1. yarn set version 1.22.19
2. npx @backstage/create-app@latest
3. cd my-project
4. yarn install --frozen-lockfile
5. yarn tsc
6. yarn build:backend

Then explicitly change node 16 image to node:18-bookworm-slim in docker file because I get an error
Then add yarn version 
RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn set version 1.22.19 \
    yarn install --frozen-lockfile --production --network-timeout 300000

Now docker can build image but after start I get an error:

```
 docker run -it -p 7007:7007 backstage:1.0.1                              
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'express-promise-router'
Require stack:
- /app/packages/backend/dist/index.cjs.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/app/packages/backend/dist/index.cjs.js:3:14)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/packages/backend/dist/index.cjs.js' ]
}

Node.js v18.18.1
```

### 🖥️ Your Environment

MacOs M1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by awanlin** [comment]
Hi @r331, I'm taking a look at this, I'm able to easily reproduce but don't have any solutions yet. Just want to add some notes:

- I edited the Dockerfile in `/packages/backend/Dockerfile`, then used `docker image build . -f packages/backend/Dockerfile --tag backstage` to build the image, and then `docker run -it -p 7007:7007 backstage` to start it up at which point I get the same error: "Error: Cannot find module 'express-promise-router'
- The Node 18 issue will be resolved next week when the changes in this PR https://github.com/backstage/backstage/pull/19565 get released on October 17th.
- I'm not sure why you would need to add `yarn set version 1.22.19`, not something I've done or seen done before, but when I remove that I get different errors.
- One thing that I find odd using your exact setup is how fast the docker image build, it's too fast IMO, like it should take more then 2-3 seconds it's taking for me 🤔

**Comment by Rugvip** [comment]
The `yarn install` line needs to be separate, or it will be ignored.

Replace

```dockerfile
RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn set version 1.22.19 \
    yarn install --frozen-lockfile --production --network-timeout 300000
```

with

```dockerfile
RUN yarn set version 1.22.19

RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn install --frozen-lockfile --production --network-timeout 300000
```

and the install will run correctly with a fixed version.

**Comment by r331** [comment]
It also doesn't work:
` => ERROR [stage-0  8/10] RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000     yarn install --frozen-lockfile --production --network-timeout 300000                                                                                                                           7.5s
------                                                                                                                                                                                                                                                                                                                  
 > [stage-0  8/10] RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000     yarn install --frozen-lockfile --production --network-timeout 300000:                                                                                                                                      
0.392 yarn install v1.22.19                                                                                                                                                                                                                                                                                             
0.478 [1/5] Validating package.json...                                                                                                                                                                                                                                                                                  
0.483 [2/5] Resolving packages...
1.052 [3/5] Fetching packages...
1.066 warning Pattern ["app@link:packages/app"] is trying to unpack in the same destination "/home/node/.cache/yarn/v6/npm-app-0.0.0/node_modules/app" as pattern ["app@0.0.0","app@0.0.0"]. This could result in non-deterministic behavior, skipping.
1.830 [4/5] Linking dependencies...
1.833 warning "@backstage/cli > rollup-plugin-dts@4.2.3" has incorrect peer dependency "typescript@^4.1".
5.875 [5/5] Building fresh packages...
6.736 info This module is OPTIONAL, you can safely ignore this error
6.736 warning Error running install script for optional dependency: "/app/node_modules/cpu-features: Command failed.
6.736 Exit code: 127
6.736 Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
6.736 Arguments: 
6.736 Directory: /app/node_modules/cpu-features
6.736 Output:
6.736 /bin/sh: 1: node-gyp: not found"
6.981 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
6.981 error /app/node_modules/isolated-vm: Command failed.
6.981 Exit code: 127
6.981 Command: prebuild-install || (node-gyp rebuild --release -j 4 && node-gyp clean)
6.981 Arguments: 
6.981 Directory: /app/node_modules/isolated-vm
6.981 Output:
6.981 prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=arm64 libc= platform=linux)
6.981 /bin/sh: 1: node-gyp: not found
------
Dockerfile:47
--------------------
  46 |     
  47 | >>> RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
  48 | >>>     yarn install --frozen-lockfile --production --network-timeout 300000
  49 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn install --frozen-lockfile --production --network-timeout 300000" did not complete successfully: exit code: 127
`

**Comment by r331** [comment]
Here is the solution - add one run 
RUN apt-get update && apt-get install -y python3 make g++ && npm install -g node-gyp

**Comment by awanlin** [comment]
Yeah, I also ran into the need to add `node-gyp`, this was not something I've seen required before 🤔
