### ISSUE TITLE
🚀 Feature: add type to EntityNodeData

### ISSUE THREAD

**Issue by benkeil** [backstage/backstage#20594]
### 🔖 Feature description

For custom styling of the entity graph, it would be great to also have the type of a "component" available.

### 🎤 Context

You can have specific color in the entity graph for different components.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
It sounds like a good idea! Would it make sense to have the entire entity available?

**Comment by benkeil** [comment]
Sounds even better

**Comment by benkeil** [comment]
Turns out type is part of spec and spec is already part of the node. Maybe it makes sense to add `type` as a dedicated property on the root level (like `name` or `namespace`).
I would also like to add `apiVersion`, `labels`, `annotations` and `tags`. 
What do you think?

**Comment by tudi2d** [comment]
Let's go with the entire entity - will give us some flexibility for future features :)
