### ISSUE TITLE
🐛 Bug Report:  Jira Plugin UI error message is not syncing with API return error message

### ISSUE THREAD

**Issue by MasthanSK121** [backstage/backstage#20597]
### 📜 Description

![image](https://github.com/backstage/backstage/assets/31499795/5da758d9-f2dc-49f8-89c4-aabfa0ded5f0)

### 👍 Expected behavior

UI should display the back end returning error message.

### 👎 Actual Behavior with Screenshots

<img width="1502" alt="image" src="https://github.com/backstage/backstage/assets/31499795/009885d8-6200-49da-8c59-1877b73e9016">

### 👟 Reproduction steps

1. Select the any component
2. Go to the manage plugin
2. Select Jira plugin
3. Enter invalid project key and save it
4. go back to the component 
5. go to the jira section

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by TheShiveshNetwork** [comment]
Can you assign this to me?

**Comment by awanlin** [comment]
Hi @MasthanSK121, this is a good suggestion but the Jira plugin is from Roadie and the repo you'll want to log this issue in is over here: https://github.com/RoadieHQ/roadie-backstage-plugins

FYI @TheShiveshNetwork
