### ISSUE TITLE
🚀 Feature: Module federation capability in Backstage

### ISSUE THREAD

**Issue by phenomuser** [backstage/backstage#20601]
### 🔖 Feature description

Hello,

We aim to enable module federation capabilities in Backstage UI to seamlessly load our existing module federated child apps into Backstage.

Could you please advise if there are any possible ways to achieve this?

We attempted to convert Backstage UI to Webpack, but we encountered issues while reading the app-config.yaml file. In Webpack, to initiate the application, it uses webpack serve, whereas in Backstage, it utilizes backstage-cli package start.

Could you provide any guidance on how to load the app-config.yaml using custom scripts?

For more information on module federation, [https://webpack.js.org/concepts/module-federation/](please refer to https://webpack.js.org/concepts/module-federation/
Thank you.

### 🎤 Context

Module federation, microfrontends ui https://webpack.js.org/concepts/module-federation/

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
There's actually quite a lot of ongoing work in this area! See #17054 as well as #18372 and #19545 for how the frontend system is being evolved to support this.

If you want this right now then you'll indeed need to set up your own Webpack configuration, which is somewhat tricky. The starting point for this is over here: https://github.com/backstage/backstage/blob/9468a67b92f47964044ff3516e119799db695097/packages/cli/src/lib/bundler/config.ts#L93. Bit of a warning that we're also in the process of switching out Webpack though, see #20331
