### ISSUE TITLE
🚀 Feature: Convert the display name value from name to title in Entity Feedback plugin

### ISSUE THREAD

**Issue by LZING** [backstage/backstage#20600]
### 🔖 Feature description

I would like to ask the Entity Feedback plug-in developer to change the displayed user field from name to title? 

### 🎤 Context

Because the name value we are using now is the employee's job number, we cannot see the employee's name. And it also supports using title as the display name in backstage.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by kuangp** [comment]
I think this feature makes sense and might depend a bit on https://github.com/backstage/backstage/pull/17474 - right now only the user entityRef is stored with responses and it would require an extra fetch from the catalog to retrieve the title metadata

**Comment by krunalhinguu** [comment]
Hi @LZING are you currently working on this issue?

**Comment by LZING** [comment]
> Hi @LZING are you currently working on this issue?
I did think it was just a new field. You can replace it with display title. After further in-depth research, I found that it was indeed what kuangp said. If it is just a simple replacement, he may need to query multiple pieces of user information. After BS officially adjusts the entityPresentationApiRef in [#17474](https://github.com/backstage/backstage/pull/17474), I think we should be able to achieve the functions we want soon.

**Comment by freben** [comment]
That PR is merged and released since Tuesday, so feel free to start to use that API.

**Comment by LZING** [comment]
> That PR is merged and released since Tuesday, so feel free to start to use that API.

Hello freben! Thank you for your contribution.I saw that the PR has been updated. But Feedback is a plug-in officially maintained by BS. Can you help me contact the developers of Feedback so that they can carry out the next development?

**Comment by freben** [comment]
That's not necessarily how it works. It's an open repo, anybody can contribute. Phil who answered at the top was the original maker but he's not a maintainer and besides it's not always the case that a desire for a feature ends up being developed by the same person - or at all - especially if they don't have dedicated time to work on the feature.

I added a "help wanted" label on it for now, to see if someone pitches in.
