### ISSUE TITLE
🐛 Bug Report: Microsoft Auth keeps requesting consent in 1.19.0

### ISSUE THREAD

**Issue by jmezach** [backstage/backstage#20641]
### 📜 Description

After upgrading to Backstage 1.19.0 I could no longer login using Microsoft Auth. I keep getting a message stating that I need admin consent. After further investigation we've noticed that the request to Azure AD / Entra ID now includes a prompt=consent query string parameter that wasn't there before. Removing that query string parameter manually allows us to sign in normally.

### 👍 Expected behavior

I would expect to be able to login using Microsoft Auth as I did using previous versions of Backstage.

### 👎 Actual Behavior with Screenshots

Instead after logging in I'm seeing the following screen:

![Screenshot 2023-10-17 at 14 45 42](https://github.com/backstage/backstage/assets/1225489/dbc1390d-b2db-478a-a6ec-d5b582e9213c)

Clicking "Return to the application without granting consent" results in the message "Authentication rejected," within Backstage. Signing in using an admin account and granting consent on behalf of my organization also results in an authentication failure.

### 👟 Reproduction steps

1. Setup a Backstage instance using Microsoft Auth as described in the [docs](https://backstage.io/docs/auth/microsoft/provider)
2. Make sure the instance is running Backstage 1.19.0
3. Go to the instance
4. Click on the Sign In button
5. Be greeted by the error message shown in the screenshot above

### 🖥️ Your Environment

  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.5.6
  @backstage/backend-common                                        0.15.2, 0.19.8
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.6.6
  @backstage/backend-tasks                                         0.5.11
  @backstage/catalog-client                                        1.4.5
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5
  @backstage/cli                                                   0.23.0
  @backstage/config-loader                                         1.5.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.11.2, 0.13.6
  @backstage/core-plugin-api                                       1.7.0
  @backstage/dev-utils                                             1.0.22
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7
  @backstage/integration-react                                     1.1.20
  @backstage/integration                                           1.7.1
  @backstage/plugin-adr-backend                                    0.4.3
  @backstage/plugin-adr-common                                     0.2.16
  @backstage/plugin-adr                                            0.6.8
  @backstage/plugin-analytics-module-newrelic-browser              0.0.3
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.0
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.0
  @backstage/plugin-azure-devops-backend                           0.4.3
  @backstage/plugin-azure-devops-common                            0.3.1
  @backstage/plugin-azure-devops                                   0.3.7
  @backstage/plugin-catalog-backend-module-azure                   0.1.25
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.13
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-import                                 0.10.1
  @backstage/plugin-catalog-node                                   1.4.7
  @backstage/plugin-catalog-react                                  1.8.5
  @backstage/plugin-catalog-unprocessed-entities                   0.1.4
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-devtools-backend                               0.2.3
  @backstage/plugin-devtools-common                                0.1.5
  @backstage/plugin-devtools                                       0.1.5
  @backstage/plugin-entity-feedback-backend                        0.2.3
  @backstage/plugin-entity-feedback-common                         0.1.3
  @backstage/plugin-entity-feedback                                0.2.8
  @backstage/plugin-entity-validation                              0.1.10
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-explore-backend                                0.0.16
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.32
  @backstage/plugin-explore                                        0.4.11
  @backstage/plugin-github-actions                                 0.6.6
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-home-react                                     0.1.4
  @backstage/plugin-home                                           0.5.9
  @backstage/plugin-octopus-deploy                                 0.2.7
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-permission-common                              0.7.9
  @backstage/plugin-permission-node                                0.7.17
  @backstage/plugin-permission-react                               0.4.16
  @backstage/plugin-proxy-backend                                  0.4.3
  @backstage/plugin-scaffolder-backend                             1.18.0
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.6
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-explore                  0.1.10
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-sonarqube-backend                              0.2.8
  @backstage/plugin-sonarqube-react                                0.1.9
  @backstage/plugin-sonarqube                                      0.7.6
  @backstage/plugin-tech-radar                                     0.6.9
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.1
  @backstage/plugin-techdocs-node                                  1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.2.19, 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.6

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Just wanted to add on that we had this issue with `v1.19.0-next.2` but I had assumed at that time it was on the Azure AD / Entra ID side, we also happen to be updating tokens as they were set to expired so that also made us think it was related to that.

This was not an issue with `v1.19.0-next.1` which means something in `v1.19.0-next.2` is the cause, will do some digging

**Comment by awanlin** [comment]
Discord thread on the topic: https://discordapp.com/channels/687207715902193673/1163801858809266307

**Comment by awanlin** [comment]
Thanks for the details @afscrome, very helpful!

@TheGemmell do you think you can run with this based on these details? I think if we made this configurable it would be the best route forward

**Comment by afscrome** [comment]
@Rugvip  I think we'll need to hotfix this.

The impact of this depends on how the company has configured consents.  ![image](https://github.com/backstage/backstage/assets/289860/3dceafd2-710a-442c-af4d-85439af49341)

1. The green option only causes an irritation - every time you log in to backstage, you'll be prompted to re-consent 
![image](https://github.com/backstage/backstage/assets/289860/cfb89e77-c84c-4b5d-b6b5-f9c213754188)

2. The red options will prevent anyone who isn't a directory admin from authenticating (i.e. hopefully everyone but High Privilege IT accounts)
![image](https://github.com/backstage/backstage/assets/289860/40e994e5-845d-444b-9bbe-0c1b4d9ea06d)
