### ISSUE TITLE
🐛 Bug Report: Since 1.19, no profile picture anymore with microsoft auth

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#20677]
### 📜 Description

Since the upgrade to 1.19.1, the profile picture for the logged-in user is not available anymore. With the previous release 1.18.x it still worked. Hence, I assume it is a regression related to the migration of the Microsoft auth provider to a separate module.

### 👍 Expected behavior

`$.profile.picture` has a value.

### 👎 Actual Behavior with Screenshots

`$.profile.picture` has no value.

### 👟 Reproduction steps

1. Login using Microsoft auth provider
2. Go to a view with the profile picture like the settings page

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by pjungermann** [comment]
Probably, related to https://github.com/backstage/backstage/pull/20120/files#diff-6c2c237c10082bb5cf04f35e6f81f66dfd6f00724a431403b877ff08020c280fL174-L175 which took care of getting the picture previously.

**Comment by afscrome** [comment]
Thinking aloud here, rather than having the auth provider get the photo, should backstage populate the photo based on `user.spec.profile.picture`?

**Comment by pjungermann** [comment]
> Thinking aloud here, rather than having the auth provider get the photo, should backstage populate the photo based on `user.spec.profile.picture`?

In general, this could be an option. 🤔 Without a user present, the login would fail.

The resolver that will execute `signInWithCatalogUser` will be executed after the profile creation. We would need to look up the user entity twice, I guess, etc. The logic for mapping the profile to the user entity is part of the resolver.

Looking up the photo via Graph API is one API call. Also, the profile is only used for the login session.

I worked on re-adding the photo lookup locally. Works well so far.

I was wondering why we don't use `passport-microsoft`. At (some) other auth providers, we use similar packages. Didn't try it yet. Might not make sense, though.
