### ISSUE TITLE
🐛 Bug Report: in tests; mocking @backstage/plugin-catalog-react fails since 1.19

### ISSUE THREAD

**Issue by clanghout** [backstage/backstage#20678]
### 📜 Description

After attempting to upgrade from 1.18 to 1.19, tests suddenly fail with `ReferenceError: Cannot access '_useEntityde64059aesm' before initialization`. 

Reproduced in a fresh generated backstage instance with a new test file with the contents that are provided as Reproduction steps. I reduced the example down as much as possible.

### 👍 Expected behavior

test passes

### 👎 Actual Behavior with Screenshots

<img width="647" alt="image" src="https://github.com/backstage/backstage/assets/5969237/7ce7521a-cfa6-4623-9cbd-bf8bcb93a5e8">

    ReferenceError: Cannot access '_useEntityde64059aesm' before initialization

      10 |     () =>
      11 |         ({
    > 12 |             ...jest.requireActual('@backstage/plugin-catalog-react'),
         |                     ^
      13 |         }) as unknown,
      14 | );
      15 |

### 👟 Reproduction steps

Example failing test:
```
import {renderWithEffects, wrapInTestApp} from "@backstage/test-utils";
import React, {Suspense} from "react";
import {CatalogEntityPage} from "@backstage/plugin-catalog";

jest.mock(
    '@backstage/plugin-catalog-react',
    () =>
        ({
            ...jest.requireActual('@backstage/plugin-catalog-react'),
        }) as unknown,
);

describe('test', () => {
    it('should render', async () => {
        const rendered = await renderWithEffects(
            wrapInTestApp(
                <Suspense fallback="test">
                    <EntityProvider entity={{
                        apiVersion: 'backstage.io/v1alpha1',
                        kind: 'Component',
                        metadata: {
                            name: 'testEntity',
                        },
                    }}>
                        <CatalogEntityPage/>
                    </EntityProvider>
                </Suspense>,
            ),
        );
    });
});

```

### 🖥️ Your Environment

OS:   Darwin 22.6.0 - darwin/arm64
node: v18.15.0
yarn: 1.22.19
cli:  0.23.0 (installed)
backstage:  1.19.0

Dependencies:
  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.5.6
  @backstage/backend-common                                        0.19.8
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.6.6
  @backstage/backend-tasks                                         0.5.11
  @backstage/catalog-client                                        1.4.5
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5
  @backstage/cli                                                   0.23.0
  @backstage/config-loader                                         1.5.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.13.6
  @backstage/core-plugin-api                                       1.7.0
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7
  @backstage/integration-react                                     1.1.20
  @backstage/integration                                           1.7.1
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.3
  @backstage/plugin-auth-node                                      0.4.0
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-import                                 0.10.1
  @backstage/plugin-catalog-node                                   1.4.7
  @backstage/plugin-catalog-react                                  1.8.5
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-github-actions                                 0.6.6
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-permission-common                              0.7.9
  @backstage/plugin-permission-node                                0.7.17
  @backstage/plugin-permission-react                               0.4.16
  @backstage/plugin-proxy-backend                                  0.4.3
  @backstage/plugin-scaffolder-backend                             1.18.0
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.6
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-tech-radar                                     0.6.9
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.1
  @backstage/plugin-techdocs-node                                  1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.6

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Not entirely sure what the issue is, but are you able to remove the mock altogether? We try to provide the necessary utilities for mocks not to be necessary, in this case `EntityProvider` seems to do the trick?

**Comment by Rugvip** [comment]
Nice! 👍 

It's not really the kind of thing we promise API stability for, but if it's a simple fix we could perhaps roll it out. Hesitant to make it a patch release though. It is indeed the kind of thing we discourage either way

**Comment by clanghout** [comment]
Allright! I'll leave it be then and close this issue
