### ISSUE TITLE
🐛 Bug Report: backend does not start with `yarn dev` on newly scaffolded app

### ISSUE THREAD

**Issue by sanderaernouts** [backstage/backstage#20680]
### 📜 Description

I created a new backstage app using `npx @backstage/create-app@latest`. In my case, `latest` is version `0.5.6`, When I run the app using `yarn dev` the front-end starts but the back-end doesn't. When I run `yarn start-backend` separately the back-end does start.

### 👍 Expected behavior

I would expect the back-end to start when running `yarn dev`.

### 👎 Actual Behavior with Screenshots

This is the output from `yarn dev`:
```text
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace backend start
$ yarn workspace app start
$ backstage-cli package start
$ backstage-cli package start
[1] (node:20084) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
[1] (Use `node --trace-warnings ...` to show where the warning was created)
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from 'C:\repos\github\sanderaernouts\backstage-issue-repro\packages\app\public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all
[0] webpack compiled successfully
```

The front-end starts but the back-end does not:
![image](https://github.com/backstage/backstage/assets/6184673/2ae29e77-0d59-4329-a8ab-05aae6141041)

### 👟 Reproduction steps

1. Scaffold a new backstage app using `npx @backstage/create-app@0.5.6`
2. `cd` into the app directory
3. run `yarn dev`

I created a repro here: https://github.com/sanderaernouts/backstage-issue-20680-repro

### 📃 Provide the context for the Bug.

I only scaffolded a new app with `@backstage/create-app@0.5.6`. I made no other changes.

### 🖥️ Your Environment

OS:   Windows_NT 10.0.22621 - win32/x64
node: v18.15.0
yarn: 1.22.19
cli:  0.23.0 (installed)
backstage:  1.19.0

Dependencies:
  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.5.6
  @backstage/backend-common                                        0.19.8
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.6.6
  @backstage/backend-tasks                                         0.5.11
  @backstage/catalog-client                                        1.4.5
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5
  @backstage/cli                                                   0.23.0
  @backstage/config-loader                                         1.5.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.13.6
  @backstage/core-plugin-api                                       1.7.0
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7
  @backstage/integration-react                                     1.1.20
  @backstage/integration                                           1.7.1
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.3
  @backstage/plugin-auth-node                                      0.4.0
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-import                                 0.10.1
  @backstage/plugin-catalog-node                                   1.4.7
  @backstage/plugin-catalog-react                                  1.8.5
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-github-actions                                 0.6.6
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-permission-common                              0.7.9
  @backstage/plugin-permission-node                                0.7.17
  @backstage/plugin-permission-react                               0.4.16
  @backstage/plugin-proxy-backend                                  0.4.3
  @backstage/plugin-scaffolder-backend                             1.18.0
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.6
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-tech-radar                                     0.6.9
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.1
  @backstage/plugin-techdocs-node                                  1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.6

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kosoj** [comment]
Same on my Ntb. But it is possible to run _backend_ and _frontend_ separately by cli `yarn start-backend` and `yarn start`

**Comment by Rugvip** [comment]
Thank you for reporting! Managed to reproduce on Windows and this seems to fix it: #20705. Could you verify? and we'll ship it along with a patch release

**Comment by kuangp** [comment]
Not sure if exactly related but cross referencing a similar discussion on discord about issues running the new experimental backend: https://discord.com/channels/687207715902193673/1164091672855064596

**Comment by sanderaernouts** [comment]
@Rugvip appologies for the late reply. Do you still want me to test this? If so, how do I go about testing it? Can I simply checkout the repo and `yarn start` the `create-app` package?

**Comment by Rugvip** [comment]
@sanderaernouts no worries! about to ship this as a patch in #20763 so please try it out with that 😁

**Comment by sanderaernouts** [comment]
Just ran into the issue after a `yarn backstage-cli version bump`, so eagerly awaiting the patch 😃.

**Comment by sanderaernouts** [comment]
Just updated my app to `1.19.4` and the `yarn dev` command works again 😄. Thanks @Rugvip

**Comment by MrMarga** [comment]
Having the same issue .. Is there any fixes .?????
![Uploading issue main.png…]()

**Comment by MrMarga** [comment]
![issue main](https://github.com/backstage/backstage/assets/134916723/5e3f7905-19e2-4509-8c0d-25efc92e7226)
Having the same issue .. Is there any fixes .?????

**Comment by ZaradarBH** [comment]
I have run into this issue as well on a new installation, 1.30.4, which ends up throwing this error in my face:

`C:\Users\tobia\source\repos\emma-backstage-plugins>yarn dev
yarn run v1.22.21
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from 'C:\Users\tobia\source\repos\emma-backstage-plugins\packages\app\public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] C:\Users\tobia\source\repos\emma-backstage-plugins\node_modules\@backstage\core-plugin-api\dist\index.esm.js:1
[1] export { AnalyticsContext } from './analytics/AnalyticsContext.esm.js';
[1] ^^^^^^
[1] 
[1] SyntaxError: Unexpected token 'export'
[1]     at internalCompileFunction (node:internal/vm:77:18)
[1]     at wrapSafe (node:internal/modules/cjs/loader:1288:20)
[1]     at Module._compile (node:internal/modules/cjs/loader:1340:27)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[1]     at Object.newLoader [as .js] (C:\Users\tobia\source\repos\emma-backstage-plugins\node_modules\pirates\lib\index.js:121:7)
[1]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[1]     at Module._load (node:internal/modules/cjs/loader:1023:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1235:19)
[1]     at require (node:internal/modules/helpers:176:18)
[1]     at Object.<anonymous> (c:\Users\tobia\source\repos\emma-backstage-plugins\plugins\emma-common\src\api\EmmaApi.ts:16:14)
[1]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[1]     at Module._compile (C:\Users\tobia\source\repos\emma-backstage-plugins\node_modules\pirates\lib\index.js:117:24)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[1]     at Object.newLoader [as .ts] (C:\Users\tobia\source\repos\emma-backstage-plugins\node_modules\pirates\lib\index.js:121:7)
[1]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[1]     at Module._load (node:internal/modules/cjs/loader:1023:12)
[1] 
[1] Node.js v20.10.0
[0] webpack compiled successfully`

I tried to run `yarn backstage-cli versions:bump` which succeeded and then I did a yarn install to update dependencies. Still no luck, when I run `yarn backstage-cli info` i get the following output, with everything looking fine:

`OS:   Windows_NT 10.0.22631 - win32/x64
node: v20.10.0
yarn: 1.22.21
cli:  0.27.0 (installed)
backstage:  1.30.4

Dependencies:
  @backstage/app-defaults                                          1.5.10
  @backstage/backend-app-api                                       0.9.3
  @backstage/backend-common                                        0.24.1
  @backstage/backend-defaults                                      0.4.4
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.17
  @backstage/backend-plugin-api                                    0.8.1
  @backstage/backend-tasks                                         0.6.1
  @backstage/backend-test-utils                                    0.5.1
  @backstage/catalog-client                                        1.6.6
  @backstage/catalog-model                                         1.6.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.27.0
  @backstage/config-loader                                         1.9.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2
  @backstage/core-compat-api                                       0.2.8
  @backstage/core-components                                       0.14.10
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.37
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.7.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30
  @backstage/integration                                           1.14.0
  @backstage/plugin-api-docs                                       0.11.8
  @backstage/plugin-app-backend                                    0.3.73
  @backstage/plugin-app-node                                       0.1.24
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.17
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.7
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.7
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.2.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.19
  @backstage/plugin-auth-backend-module-github-provider            0.1.21
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.21
  @backstage/plugin-auth-backend-module-google-provider            0.1.21
  @backstage/plugin-auth-backend-module-guest-provider             0.1.10
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.19
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.17
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.6
  @backstage/plugin-auth-backend-module-okta-provider              0.0.17
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.5
  @backstage/plugin-auth-backend                                   0.22.12
  @backstage/plugin-auth-node                                      0.5.1
  @backstage/plugin-auth-react                                     0.1.5
  @backstage/plugin-bitbucket-cloud-common                         0.2.22
  @backstage/plugin-catalog-backend-module-logs                    0.0.4
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.22
  @backstage/plugin-catalog-backend                                1.25.2
  @backstage/plugin-catalog-common                                 1.0.26
  @backstage/plugin-catalog-graph                                  0.4.8
  @backstage/plugin-catalog-import                                 0.12.2
  @backstage/plugin-catalog-node                                   1.12.6
  @backstage/plugin-catalog-react                                  1.12.3
  @backstage/plugin-catalog                                        1.22.0
  @backstage/plugin-events-node                                    0.3.10
  @backstage/plugin-kubernetes-backend                             0.18.5
  @backstage/plugin-kubernetes-common                              0.8.2
  @backstage/plugin-kubernetes-node                                0.1.18
  @backstage/plugin-kubernetes-react                               0.4.2
  @backstage/plugin-kubernetes                                     0.11.13
  @backstage/plugin-org                                            0.6.28
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.21
  @backstage/plugin-permission-backend                             0.5.48
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.2
  @backstage/plugin-permission-react                               0.4.25
  @backstage/plugin-proxy-backend                                  0.5.5
  @backstage/plugin-scaffolder-backend-module-azure                0.1.16
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.14
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.16
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.14
  @backstage/plugin-scaffolder-backend-module-github               0.4.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.6
  @backstage/plugin-scaffolder-backend                             1.24.1
  @backstage/plugin-scaffolder-common                              1.5.5
  @backstage/plugin-scaffolder-node                                0.4.10
  @backstage/plugin-scaffolder-react                               1.11.0
  @backstage/plugin-scaffolder                                     1.24.0
  @backstage/plugin-search-backend-module-catalog                  0.2.1
  @backstage/plugin-search-backend-module-pg                       0.5.34
  @backstage/plugin-search-backend-module-techdocs                 0.2.1
  @backstage/plugin-search-backend-node                            1.3.1
  @backstage/plugin-search-backend                                 1.5.16
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.7.14
  @backstage/plugin-search                                         1.4.15
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.12
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.13
  @backstage/plugin-techdocs-node                                  1.12.10
  @backstage/plugin-techdocs-react                                 1.2.7
  @backstage/plugin-techdocs                                       1.10.8
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.11
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.10
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
Done in 0.45s.`

However as it stands the backend is 100% unavailable for my frontend :)

**Comment by ZaradarBH** [comment]
I figured out the issue. I had a dependency in the backend-plugin on core-api-plugins, which is no bueno :)

**Comment by cliffAtOsaic** [comment]
I am having this same issue on a newly created app.

OS:   Linux 6.8.0-40-generic - linux/x64
node: v20.11.1
yarn: 4.4.1
cli:  0.27.1 (installed)
backstage:  1.31.1 

Is there something I can check on to fix this?

**Comment by cliffAtOsaic** [comment]
Worth noting, if I try to start them separately, `yarn start-backend` starts fine but `yarn start` gives me this error:

Error: Failed to read config file at "/home/adm.605473/git/devops-backstage/backstage/app-config.yaml", error at .backend.https.certificate.cert, $file substitution value was undefined

**Comment by junaidaj86** [comment]
I am facing the same issue with AWS Linux node.
yarn 4.4.1
node v18.20.4
cli 0.27.1
backstage 1.31.1

My front end is not loading .
[app]: Loaded config from app-config.yaml
[app]: fatal: not a git repository (or any of the parent directories): .git
[app]: fatal: not a git repository (or any of the parent directories): .git
[app]: NOTE: Did not compute git version or commit hash, could not execute the git command line utility
[app]: <i> [webpack-dev-server] Project is running at:
[app]: <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[app]: <i> [webpack-dev-server] Content not from webpack is served from '/home/ec2-user/backstage/packages/app/public' directory
[app]: <i> [webpack-dev-server] 404s will fallback to '/index.html'
[app]: webpack compiled successfully

**Comment by cliffAtOsaic** [comment]
I see that the `yarn dev` command was updated in a recent version.

There used to be a dependency on a package called "concurrently" which was called in the `yarn dev` script:
`"dev": "concurrently \"yarn start\" \"yarn start-backend\""`

The new Backstage app scaffolding has removed the dependency and calls a new script for `yarn dev`:
`"dev": "yarn workspaces foreach -A --include backend --include app --parallel -v -i run start"`

It seems that the old script using concurrently was working for me and the new script calling workspaces does not.

**Comment by Rugvip** [comment]
@cliffAtOsaic we've seen that issues in the wild too, although it seems very rare. Could you perhaps share what environment you're running it in?

**Comment by cliffAtOsaic** [comment]
> @cliffAtOsaic we've seen that issues in the wild too, although it seems very rare. Could you perhaps share what environment you're running it in?

Ubuntu 22.04.5 LTS (GNU/Linux 6.8.0-40-generic x86_64)
Node v20.11.1 
Yarn 4.4.1 
@backstage/cli@npm:0.27.1
