### ISSUE TITLE
🚀 Feature: Entity as URL in link

### ISSUE THREAD

**Issue by vinnie-jog-on** [backstage/backstage#20684]
### 🔖 Feature description

Update url to take an entity under metadata.links as well as a full URL

### 🎤 Context

In catalog file for say a component or group etc it should be possibe to add a link to an entity in backstage 
```
metadata:
  links:
    - url: user:default/jimmy
      title: SPOC
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by camilaibs** [comment]
Hi @vinnie-jog-on we see it could be convenient for sure but the `user:default/jimmy` appears a little magic.
What do you think about translating it as an entity relation or just fallback to the Backstage entity URL?

**Comment by vinnie-jog-on** [comment]
> Hi @vinnie-jog-on we see it could be convenient for sure but the `user:default/jimmy` appears a little magic. What do you think about translating it as an entity relation or just fallback to the Backstage entity URL?

Hi @camilaibs 

So the example i used of a SPOC is one of many I can think of for groups and components.
Would a new entity relation have to be created for all of these?

A fallback to the backstage URL sounds like it could also work, is there other examples of this or how would it work?

**Comment by freben** [comment]
> A fallback to the backstage URL sounds like it could also work, is there other examples of this or how would it work?

We were just referring to entering an actual URL as usual, like `https://backstage.mycompany.net/catalog/user/default/jimmy`.

There are some alternatives here if you don't mind NOT using the actual links functionality. You could make your own custom fields in `metadata`, or adding these extra properties as dedicated `metadata.labels` entries that do refer to entity refs. Then you can have a card or similar adaptation in your catalog page, that renders those in a helpful way when present.

See [Extending the model](https://backstage.io/docs/features/software-catalog/extending-the-model).
