### ISSUE TITLE
🐛 Bug Report: HomePage Top and Recent Visited don't display data when using UserSettingsStorage

### ISSUE THREAD

**Issue by benjmac** [backstage/backstage#20715]
### 📜 Description

This issue arose when attempting to use the new homepage components below

<HomePageTopVisited />
<HomePageRecentlyVisited />

I noticed no data was being shown so I investigated the API in control of registering visits data. I saw that every time I entered a route it would post data, but the hit count was always 1, even after repeat visits to the same route. I looked into the source code for VisitsStorageApi for saving and noticed this snippet

```
  async save(saveParams: VisitsApiSaveParams): Promise<Visit> {
    const visits: Visit[] = [...(await this.retrieveAll())];

    const visit: Visit = {
      ...saveParams.visit,
      id: window.crypto.randomUUID(),
      hits: 1,
      timestamp: Date.now(),
    };

    // Updates entry if pathname is already registered
    const visitIndex = visits.findIndex(e => e.pathname === visit.pathname);
    if (visitIndex >= 0) {
      visit.id = visits[visitIndex].id;
      visit.hits = visits[visitIndex].hits + 1;
      visits[visitIndex] = visit;
    } else {
      visits.push(visit);
    }

    // Sort by time, most recent first
    visits.sort((a, b) => b.timestamp - a.timestamp);
    // Keep the most recent items up to limit
    await this.persistAll(visits.splice(0, this.limit));
    return visit;
  }
```

This confirmed my assumption that no visits were being returned, as there was no data on display and no data to reference and update the hit count.

The `retrieveAll` method above directly references the storageApi to get visits.
```
visits = this.storageApi.snapshot<Array<Visit>>(storageKey).value ?? [];
```

To confirm it's an issue with the `UserSettingsStorage`, I disabled and defaulted to local storage. At that point the hit count and visits were rendering fine from local storage.

Upon investing the `snapshot` method in `UserSettingsStorage` I noticed it was hard coded returned presence unknown.

```
  snapshot<T extends JsonValue>(key: string): StorageValueSnapshot<T> {
    return { key, presence: 'unknown' };
  }
```

This seems to be the root of the cause, not allowing any of the saved data in the user settings backend to be displayed or updated with the correct hit count per route.

### 👍 Expected behavior

The components should fetch rendered data when using UserSettingsStorage.

### 👎 Actual Behavior with Screenshots

No data about visits was being displayed even though visits data was being posted.

<img width="1655" alt="Screenshot 2023-10-20 at 4 03 51 PM" src="https://github.com/backstage/backstage/assets/25201407/8f92e4b5-73c9-4a36-b119-14ff6ce916b9">

### 👟 Reproduction steps

Install user settings backend and frontend. Connect the storageApiRef to UserSettingsStorage. Setup the visitsApiRef to then reference the created storage api.

```
  createApiFactory({
    api: storageApiRef,
    deps: {
      discoveryApi: discoveryApiRef,
      errorApi: errorApiRef,
      fetchApi: fetchApiRef,
      identityApi: identityApiRef,
    },
    factory: deps => UserSettingsStorage.create(deps),
  }),
  createApiFactory({
    api: visitsApiRef,
    deps: {
      storageApi: storageApiRef,
      identityApi: identityApiRef,
    },
    factory: ({ storageApi, identityApi }) => VisitsStorageApi.create({ storageApi, identityApi }),
  }),
```

Import and reference `<VisitListener />` in the App.tsx file at the top level within `AppRouter`

Lastly add these two components on the home page

<HomePageTopVisited />
<HomePageRecentlyVisited />

Click around, you'll see network calls to post data, but it won't render. Comment out this code and then it will work with local storage

```
  createApiFactory({
    api: storageApiRef,
    deps: {
      discoveryApi: discoveryApiRef,
      errorApi: errorApiRef,
      fetchApi: fetchApiRef,
      identityApi: identityApiRef,
    },
    factory: deps => UserSettingsStorage.create(deps),
  }),
```

### 📃 Provide the context for the Bug.

It's not allowing components we'd like to usee to work as expected.

### 🖥️ Your Environment

OS:   Darwin 23.0.0 - darwin/x64
node: v18.16.1
yarn: 1.22.19
cli:  0.23.0 (installed)
backstage:  1.19.1

Dependencies:
  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.4.5, 0.5.6
  @backstage/backend-common                                        0.18.5, 0.19.8
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.5.4, 0.6.6
  @backstage/backend-tasks                                         0.5.11
  @backstage/backend-test-utils                                    0.2.7
  @backstage/catalog-client                                        1.4.5
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5
  @backstage/cli                                                   0.23.0
  @backstage/config-loader                                         1.5.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.12.5, 0.13.6
  @backstage/core-plugin-api                                       1.7.0
  @backstage/dev-utils                                             1.0.22
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7
  @backstage/integration-react                                     1.1.20
  @backstage/integration                                           1.7.1
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.0
  @backstage/plugin-catalog-backend-module-github                  0.4.4
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-import                                 0.10.1
  @backstage/plugin-catalog-node                                   1.4.7
  @backstage/plugin-catalog-react                                  1.8.5
  @backstage/plugin-catalog-unprocessed-entities                   0.1.4
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-devtools-backend                               0.2.3
  @backstage/plugin-devtools-common                                0.1.5
  @backstage/plugin-devtools                                       0.1.5
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-firehydrant                                    0.2.9
  @backstage/plugin-gcalendar                                      0.3.19
  @backstage/plugin-github-actions                                 0.6.6
  @backstage/plugin-github-pull-requests-board                     0.1.19
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-home-react                                     0.1.4
  @backstage/plugin-home                                           0.5.9
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-permission-backend                             0.5.29
  @backstage/plugin-permission-common                              0.7.9
  @backstage/plugin-permission-node                                0.7.17
  @backstage/plugin-permission-react                               0.4.16
  @backstage/plugin-playlist-backend                               0.3.10
  @backstage/plugin-playlist-common                                0.1.11
  @backstage/plugin-playlist                                       0.1.17
  @backstage/plugin-proxy-backend                                  0.4.3
  @backstage/plugin-scaffolder-backend                             1.18.0
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.6
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-elasticsearch            1.3.9
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-shortcuts                                      0.3.15
  @backstage/plugin-sonarqube-backend                              0.2.8
  @backstage/plugin-sonarqube-react                                0.1.9
  @backstage/plugin-sonarqube                                      0.7.6
  @backstage/plugin-tech-radar                                     0.6.9
  @backstage/plugin-techdocs-addons-test-utils                     1.0.22
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.1
  @backstage/plugin-techdocs-node                                  1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings-backend                          0.2.4
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.2.19, 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.6

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @benjmac, thanks for logging this and including all the details, awesome stuff! When might you submit a PR? Would be nice to get this into the weekly release 🚀

**Comment by camilaibs** [comment]
Thanks for reporting the issue @benjmac 🙏🏻
I'm looping @backstage/discoverability-maintainers in the conversation 🙂

**Comment by djamaile** [comment]
Assigned to you, thanks! @benjmac

**Comment by benjmac** [comment]
@awanlin I should have a better idea by the end of day about other tasks that might end up being prioritized. I'll report back though.

**Comment by benjmac** [comment]
For an update, should be able to take this on. There is just a race case that previously hasn't been a problem in user settings, like shortcuts, due to their nature. Route navigation changes from the VisitListener on load are triggering an update call that overwrites all previous visits data before it can even load in the existing state to append to in the save. Problem being in this [file](https://github.com/backstage/backstage/blob/master/plugins/user-settings/src/apis/StorageApi/UserSettingsStorage.ts#L141-L203) that `observe$` is the only way to fetch the data that is exposed and we lack the ability to make it synchronous before updating visits data. Currently investigating and I'll add any updates.

**Comment by benjmac** [comment]
@awanlin I have the [PR](https://github.com/backstage/backstage/pull/20768) ready now

**Comment by awanlin** [comment]
Thanks for getting this resolved @benjmac! I think it's fine being part of the weekly `next` releases before going out with `1.20.0` in mid-November
