### ISSUE TITLE
🐛 Bug Report: Entities not removed from catalog when the repo is renamed and archived at the same time

### ISSUE THREAD

**Issue by efenner-cambia** [backstage/backstage#20718]
### 📜 Description

Entities provided by the GithubEntityProvider are not being removed from the catalog if the repo is renamed just before it is archived.

### 👍 Expected behavior

The entity should be removed from the catalog.

### 👎 Actual Behavior with Screenshots

Entity remains in the catalog with the location pointing to the pre-rename repo.

### 👟 Reproduction steps

1. Append `-retired` to the name of a repo that has already been discovered by the GitHub entity provider
2. Immediately after renaming, archive the repo
3. Wait for the provider/processing loop to give it a chance to remove the entity
4. Check that the entity has not been removed

### 📃 Provide the context for the Bug.

We have a practice of appending `-retired` to the names of repos before archiving from when Github search didn't have a good way to filter out archived repositories. 

We noticed that when an archive happened without the rename, the relevant entities would be removed from the catalog. Same if the the discovery/processing loop had reconciled a name change before archiving. But most of the time, we would have to do manual cleanup from the catalog because the rename and archive operations often happen at the same time. 

### 🖥️ Your Environment

Backstage version 1.17.5
@backstage/plugin-catalog-backend-module-github | 0.3.7
@backstage/plugin-catalog | 1.12.4
@backstage/plugin-catalog-common | 1.0.15
@backstage/plugin-catalog-backend | 1.12.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by wanisfahmyDE** [comment]
@efenner-cambia out of curiosity, are the entities removed if you're only archiving without renaming?
If so, can you please share your config? it doesn't seem to work for us.
see https://github.com/backstage/backstage/issues/5239#issuecomment-1857978700

**Comment by efenner-cambia** [comment]
@wanisfahmyDE Yes, entities do seem to be removed if we archive without renaming. Config looks like this:
```yaml
providers:
    github:
      providerId:
        host: ${GITHUB_HOST}
        organization: 'myorg'
        catalogPath: '/catalog-info.yml'
```

```typescript
//packages/backend/src/plugins/catalog.ts
...
const builder = CatalogBuilder.create(env);
...
builder.addEntityProvider(
    GithubEntityProvider.fromConfig(env.config, {
        logger: env.logger,
        schedule: env.scheduler.createScheduledTaskRunner({
          frequency: { minutes: 75 },
          timeout: { minutes: 60 },
        }),
      },
    ),
  )
...
builder.setProcessingIntervalSeconds(1800);
...
```

We haven't tried to shift to event-based yet but it looks like you have something tied to events, so that could be contributing to the change in behavior. Or the `validateLocationsExist: true` since I could see that keeping the provider from updating correctly when a location goes from existing to not existing.

**Comment by wanisfahmyDE** [comment]
@efenner-cambia thanks for sharing the configs and the hint.
I tried switching `validateLocationsExist` but it didn't help :/

The events for archiving are both published by github and also subscribed to in Backstage, but beyond logging the event request, nothing else really happens on the catalog front. 

I'll keep investigating.

Thanks <3

**Comment by efenner-cambia** [comment]
Oops, please re-open. Still seeing this issue

**Comment by pjungermann** [comment]
We will treat this as a duplicate of issue #21906 which is still open and resolve it there.

**Comment by pjungermann** [comment]
As a resolution to #21906, we will add support for additional event types including repository archived and renamed.

However, this will require the event support to be enabled for the provider to have an impact.

This issue here might describe an issue with the full refresh. On a first glance, I wouldn't expect it to happen. I didn't look into or reproduced it, though.

The full fresh will get all repositories and then filter archived ones. If there is a repo that was renamed and archived or even only archived, I would expect it not to show up in the resulting set of expected entities anymore. Everything not contained there is supposed to be cleaned up automatically as per general entity provider behavior.

I will re-open the issue for now.
