### ISSUE TITLE
🐛 Bug Report: 401 in DefaultTechDocsCollator

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#20731]
### 📜 Description

If there are a lot of TechDocs to index, the `DefaultTechDocsCollator` will fail to do indexing as the token used gets old and the endpoints start to return `401 Unauthorized`. 

The problem is on this line https://github.com/backstage/backstage/blob/2d39c1dbdf065c588464c6c0c4fc44bb469aeca0/plugins/techdocs-backend/src/search/DefaultTechDocsCollator.ts#L146

For the fix, the token should be renewed for all `fetch` calls or only if `401` is returned. 
Or even better, the entities should be handled in batches using the catalog API pagination feature.

### 👍 Expected behavior

TechDocs indexing works without 401 errors

### 👎 Actual Behavior with Screenshots

`Failed to index documents for type techdocs Request failed with 401 Error
Collating documents for techdocs failed: ResponseError: Request failed with 401 Error
Request failed with 401 Error`

### 👟 Reproduction steps

1. Have a lot of TechDocs for entities
2. Use DefaultTechDocsCollator to index those
3. Wait?

### 🖥️ Your Environment

OS:   Darwin 22.6.0 - darwin/arm64
node: v18.15.0
yarn: 1.22.19
cli:  0.23.0 (installed)
backstage:  1.19.0

Dependencies:
  @backstage/app-defaults                                            1.4.4
  @backstage/backend-app-api                                         0.5.6
  @backstage/backend-common                                          0.17.0, 0.19.8
  @backstage/backend-dev-utils                                       0.1.2
  @backstage/backend-openapi-utils                                   0.0.5
  @backstage/backend-plugin-api                                      0.6.6
  @backstage/backend-tasks                                           0.5.11
  @backstage/backend-test-utils                                      0.2.7
  @backstage/catalog-client                                          1.4.5
  @backstage/catalog-model                                           1.4.3
  @backstage/cli-common                                              0.1.13
  @backstage/cli-node                                                0.1.5
  @backstage/cli                                                     0.23.0
  @backstage/config-loader                                           1.5.1
  @backstage/config                                                  1.1.1
  @backstage/core-app-api                                            1.11.0
  @backstage/core-components                                         0.12.5, 0.13.6
  @backstage/core-plugin-api                                         1.7.0
  @backstage/dev-utils                                               1.0.22
  @backstage/errors                                                  1.2.3
  @backstage/eslint-plugin                                           0.1.3
  @backstage/frontend-app-api                                        0.2.0
  @backstage/frontend-plugin-api                                     0.2.0
  @backstage/integration-aws-node                                    0.1.7
  @backstage/integration-react                                       1.1.20
  @backstage/integration                                             1.7.1
  @backstage/plugin-api-docs                                         0.9.12
  @backstage/plugin-app-backend                                      0.3.54
  @backstage/plugin-app-node                                         0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider             0.2.0
  @backstage/plugin-auth-backend-module-github-provider              0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider              0.1.3
  @backstage/plugin-auth-backend-module-google-provider              0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider           0.1.0
  @backstage/plugin-auth-backend-module-oauth2-provider              0.1.3
  @backstage/plugin-auth-backend                                     0.19.3
  @backstage/plugin-auth-node                                        0.2.19, 0.3.1, 0.4.0
  @backstage/plugin-catalog-backend-module-aws                       0.3.0
  @backstage/plugin-catalog-backend-module-msgraph                   0.5.13
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model   0.1.3
  @backstage/plugin-catalog-backend-module-unprocessed               0.3.3
  @backstage/plugin-catalog-backend                                  1.14.0
  @backstage/plugin-catalog-common                                   1.0.17
  @backstage/plugin-catalog-graph                                    0.2.37
  @backstage/plugin-catalog-node                                     1.4.7
  @backstage/plugin-catalog-react                                    1.8.5
  @backstage/plugin-catalog-unprocessed-entities                     0.1.4
  @backstage/plugin-catalog                                          1.14.0
  @backstage/plugin-devtools-backend                                 0.2.3
  @backstage/plugin-devtools-common                                  0.1.5
  @backstage/plugin-devtools                                         0.1.5
  @backstage/plugin-entity-feedback-backend                          0.2.3
  @backstage/plugin-entity-feedback-common                           0.1.3
  @backstage/plugin-entity-feedback                                  0.2.8
  @backstage/plugin-events-node                                      0.2.15
  @backstage/plugin-github-actions                                   0.6.6
  @backstage/plugin-graphiql                                         0.2.55
  @backstage/plugin-home-react                                       0.1.4
  @backstage/plugin-home                                             0.5.9
  @backstage/plugin-jenkins-backend                                  0.3.0
  @backstage/plugin-jenkins-common                                   0.1.20
  @backstage/plugin-jenkins                                          0.9.0
  @backstage/plugin-kubernetes-common                                0.7.0
  @backstage/plugin-org                                              0.6.15
  @backstage/plugin-permission-backend                               0.5.29
  @backstage/plugin-permission-common                                0.7.9
  @backstage/plugin-permission-node                                  0.7.17
  @backstage/plugin-permission-react                                 0.4.16
  @backstage/plugin-proxy-backend                                    0.4.3
  @backstage/plugin-scaffolder-backend-module-confluence-to-markdown 0.2.7
  @backstage/plugin-scaffolder-backend-module-cookiecutter           0.2.30
  @backstage/plugin-scaffolder-backend                               1.18.0
  @backstage/plugin-scaffolder-common                                1.4.2
  @backstage/plugin-scaffolder-node                                  0.2.6
  @backstage/plugin-scaffolder-react                                 1.5.6
  @backstage/plugin-scaffolder                                       1.15.1
  @backstage/plugin-search-backend-module-catalog                    0.1.10
  @backstage/plugin-search-backend-module-elasticsearch              1.3.9
  @backstage/plugin-search-backend-module-techdocs                   0.1.10
  @backstage/plugin-search-backend-node                              1.2.10
  @backstage/plugin-search-backend                                   1.4.6
  @backstage/plugin-search-common                                    1.2.7
  @backstage/plugin-search-react                                     1.7.1
  @backstage/plugin-search                                           1.4.1
  @backstage/plugin-sonarqube-backend                                0.2.8
  @backstage/plugin-sonarqube-react                                  0.1.9
  @backstage/plugin-sonarqube                                        0.7.6
  @backstage/plugin-techdocs-backend                                 1.8.0
  @backstage/plugin-techdocs-node                                    1.9.0
  @backstage/plugin-techdocs-react                                   1.1.12
  @backstage/plugin-techdocs                                         1.8.0
  @backstage/plugin-user-settings                                    0.7.11
  @backstage/release-manifests                                       0.0.10
  @backstage/test-utils                                              1.4.4
  @backstage/theme                                                   0.2.19, 0.4.3
  @backstage/types                                                   1.1.1
  @backstage/version-bridge                                          1.0.6

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Thanks for reporting the issue 🙏🏻 
It seems that this is the best solution, do you have any other suggestions @backstage/techdocs-maintainers?

**Comment by isanjit3** [comment]
Hi there,
I'd like to tackle this issue by implementing token renewal for each call. I'm getting started on this—any pointers would be welcome!

**Comment by johnphilip283** [comment]
> Hi there, I'd like to tackle this issue by implementing token renewal for each call. I'm getting started on this—any pointers would be welcome!

Hey there @isanjit3, thanks so much for taking point on fixing this! I'd go along with @drodil's suggestion and retry the failed requests if a 401 is returned for them. Perhaps it might be a good starting point to take the error returned in case the request fails, check for the error code being 401 and conditionally regenerate the token, retry the request, and then map back the result in the same way as it's being handled in the happy path. Feel free to follow up on this thread with any questions you may have!
