### ISSUE TITLE
🐛 Bug Report: NotFound middleware is noop in new backend system

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#20742]
### 📜 Description

In the new backend system the default configured [`notFound` middleware](https://github.com/backstage/backstage/blob/master/packages/backend-app-api/src/services/implementations/rootHttpRouter/rootHttpRouterServiceFactory.ts#L64) is essentially noop since it can never be reached. 

This seems to be due to how the `DefaultRootHttpRouter` handles unmatched requests by attaching an `indexRouter`: https://github.com/backstage/backstage/blob/a7e3499c6a8020c637cfc35314cd63e787ce4ab6/packages/backend-app-api/src/services/implementations/rootHttpRouter/DefaultRootHttpRouter.ts#L70

My understanding is this is done to allow the `app-backend` to handle serving the UI by pointing the unmatched `/` path to `/api/app` and then attaching the `app-backend` handler accordingly:
https://github.com/backstage/backstage/blob/a7e3499c6a8020c637cfc35314cd63e787ce4ab6/packages/backend-app-api/src/services/implementations/rootHttpRouter/DefaultRootHttpRouter.ts#L57
https://github.com/backstage/backstage/blob/a7e3499c6a8020c637cfc35314cd63e787ce4ab6/packages/backend-app-api/src/services/implementations/rootHttpRouter/DefaultRootHttpRouter.ts#L87-L89
however this results in unmatched api requests to return UI content instead of a 404

### 👍 Expected behavior

API calls to the backend for non-existent routes should return 404

### 👎 Actual Behavior with Screenshots

Request returns a 200 status with UI content 
![Screenshot 2023-10-23 at 12 48 07 PM](https://github.com/backstage/backstage/assets/6998196/a63dd023-985c-4d63-bc64-f5cb10dd3ed0)
![Screenshot 2023-10-23 at 12 48 16 PM](https://github.com/backstage/backstage/assets/6998196/f86b7f0f-7039-475f-b515-59c2441704e0)

### 👟 Reproduction steps

This can be observed in this repos demo app by serving the `example-backend-next` backend and hitting a non-existent route like `http://localhost:7007/api/not-found`

### 🖥️ Your Environment

Applicable in latest version `1.19.3`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Oh this is an excellent find. Thanks for reporting. This used to be on the API router, but in the migration to the new system it ended up at the top instead. It should be added to every plugin route individually instead.

**Comment by freben** [comment]
... and gave it a go!

**Comment by Rugvip** [comment]
Potential fix for this in #24023

**Comment by benjdlambert** [comment]
Closing as fixed
