### ISSUE TITLE
🐛 Bug Report: GitHub Actions Plugin status field does not sort for completed items

### ISSUE THREAD

**Issue by haagenson** [backstage/backstage#20779]
### 📜 Description

When sorting the plugin by status, the [sub statuses](https://github.com/backstage/backstage/blob/419e4ffaafa9db58f6b66308a5e156dbaed0c04c/plugins/github-actions/src/components/WorkflowRunStatus/WorkflowRunStatus.tsx#L49) that roll up to `completed` are not actually sorted.  Pressing the sort button leaves them in the same order.

### 👍 Expected behavior

Items within the completed status should be sorted alphabetically based on the conclusion (e.g. Aborted, Timed Out, Error, etc)

### 👎 Actual Behavior with Screenshots

Pressing the Status header keeps the items in the same order even when sorting ascending or descending.

<img width="1284" alt="image" src="https://github.com/backstage/backstage/assets/7874037/b2d3eb30-1e97-458b-ad8d-472bc4cab3f6">

### 👟 Reproduction steps

1. Load Backstage
2. Click the Catalog
3. Click a component that has workflow runs on GitHub Actions
4. Click the CI/CD plugin
5. Click the STATUS header to sort 
6. Click the STATUS header to sort again

### 📃 Provide the context for the Bug.

Users are unable to sort similar items together for review.  The status column is also not included in the filter meaning the only way to find them is to page through the results.

### 🖥️ Your Environment

Latest version of Chrome with Backstage 1.16.x

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Just wanted to note you can reproduce this here: https://demo.backstage.io/catalog/default/component/backstage-demo/ci-cd

Also, my experience when using a render like this is that you need to provide your own sort logic: 

https://github.com/backstage/backstage/blob/419e4ffaafa9db58f6b66308a5e156dbaed0c04c/plugins/github-actions/src/components/WorkflowRunsTable/WorkflowRunsTable.tsx#L88C5-L92C7
