### ISSUE TITLE
🚀 Feature: Techdocs "Watch documentation"

### ISSUE THREAD

**Issue by alper98** [backstage/backstage#20832]
### 🔖 Feature description

Currently, it appears that there isn't a way to determine if techdocs documentation has been modified.

Introducing a feature that enables users to receive alerts when updates occur in the documentation they are monitoring would be a valuable addition. This could seamlessly integrate with the issue mentioned here (https://github.com/backstage/backstage/issues/10652) and enhance user experience. By providing real-time notifications, users can stay informed about changes in the documentation, ensuring they are always up-to-date with the latest information.

### 🎤 Context

In our organization, we currently host over 30 documents on our Backstage instance. Keeping track of when these documents become outdated or undergo changes is crucial, especially as we plan to introduce many more documents, potentially reaching into the hundreds. 

The absence of a "watch" feature, similar to the one in Confluence, makes it challenging for us to promote widespread adoption of our Backstage instance for documentation among the broader audience within our organization.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by efenner-cambia** [comment]
This sounds super useful

**Comment by efenner-cambia** [comment]
Bump

**Comment by alper98** [comment]
Bumping this. Could play out really nice with the new notifications system

**Comment by byan1197** [comment]
hey @alper98 while this could potentially be a very useful feature, it is largely dependent on the Backstage Notification System which is not currently being worked on. We can revisit this feature request when the notification API is built out and in a usable state. 

For now, is the "Last Updated" date at the top of each TechDoc page useful enough to convey document recency?
