### ISSUE TITLE
🐛 DCO check is not required?

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#20844]
### 📜 Description

I've noticed that a number of prs (e.g. #20666, #20841) don't have the DCO check listed as a required check?  I'd have thought htis should be a required check.

### 👍 Expected behavior

I'd have though the DCO check should be a required check

### 👎 Actual Behavior with Screenshots

The DCO check doesn't seem to be required
![image](https://github.com/backstage/backstage/assets/289860/14d2f48c-b892-4bcd-84d4-d53bf429567f)

### 👟 Reproduction steps

Look at status checks on any pr (e.g. #20666, #20841)

### 📃 Provide the context for the Bug.

N/A

### 🖥️ Your Environment

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
Thank you for the heads up! It should indeed be required, updated.
