### ISSUE TITLE
🐛 Bug Report: `ConfigReader` incorrectly reads `fallback`

### ISSUE THREAD

**Issue by schultzp2020** [backstage/backstage#20877]
### 📜 Description

In our environment we have a "builder" `app-config` and a "production" `app-config`. Currently the `ConfigReader` will default to reading the fallback config (builder) if there is no specified value in the loaded config (production). We do not want this behavior because some default values in our builder config will be incorrect in the production config. 

### 👍 Expected behavior

The `ConfigReader` should not default to the config located at `this.fallback.data` when there is a config at `this.data`. 

### 👎 Actual Behavior with Screenshots

The `ConfigReader` reads the `this.fallback.data` config after not finding a value in the `this.data` config.

![Screenshot from 2023-10-27 15-21-15](https://github.com/backstage/backstage/assets/52387464/f4dbf9ff-1b5c-4f4b-8623-634069356a7d)
![Screenshot from 2023-10-27 15-22-07](https://github.com/backstage/backstage/assets/52387464/ab22f3d2-a5ef-4725-8268-39e6a4270487)

### 👟 Reproduction steps

https://github.com/backstage/backstage/blob/master/packages/config/src/reader.ts#L115-L120

### 📃 Provide the context for the Bug.

This bug currently affects helms charts because users cannot have a default loaded config and then override it with their own.

### 🖥️ Your Environment

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sennyeya** [comment]
Hey! Could you share a little more about your use case here? From a config override point of view, the existing logic _I think_ makes sense. The example that comes to mind is a `app-config.local.yaml` and a default `app-config.yaml`, presumably we'd still want to use the fallback config to read from config. I think the concern here might be this merging logic [here](https://github.com/backstage/backstage/blob/master/packages/config/src/reader.ts#L168-L170)?

**Comment by Rugvip** [comment]
Iirc we don't treat `null` in any special way yet, which I think we should. So from your example, it should be possible to explicitly set `auth.providers.oauth2Proxy: null` to cause all values at that part of the config and below to be treated as `undefined`.
