### ISSUE TITLE
🐛 Bug Report: GitlabOrgDiscoveryEntityProvider for  no self hosted  gitlab,  is not getting inherited users members from groups

### ISSUE THREAD

**Issue by pushit-tech** [backstage/backstage#20891]
### 📜 Description

In version [v1.19.6](https://github.com/backstage/backstage/releases/tag/v1.19.6) the discovery provider only gets users who belongs to the first group `company/teams`

As I use a no self hosted gitlab instance with users inside sub grops, I would like to be able to see all the users including inherited

### 👍 Expected behavior

To see all users including inherited users members on backstage platform.

### 👎 Actual Behavior with Screenshots

When you have a gitlab where not all your users belongs to the first group, the discovery pattern dosent gets innerited users of subgroups.

### 👟 Reproduction steps

On gitlab 
1. Create a base group with some users  'company/teams'
2. Crete other subgroups with diferent users 

On Backstage 
Configure the GitlabOrgDiscoveryEntityProvider as documented in https://backstage.io/docs/integrations/gitlab/org

### 📃 Provide the context for the Bug.

In this commit https://github.com/backstage/backstage/commit/753b35afb56268a2080875159f65ca1f449e51a2 
@matteosilv hel us with the creation of the function `listSaaSUsers`, this functions use the `/group/id/members` API wich help us to get membes of a group (with not inherited) members, what will be grate is to have also the inherited members to,

By default, the REST API [only returns direct members and excludes inherited ones](https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project), which may result in the query only fetching the users of the first group.

### 🖥️ Your Environment

Backstage v1.19.6

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by pushit-tech** [comment]
I havent make any contribution to backstage, I can do it but i dont know if probably @matteosilv can have more context around it.

**Comment by freben** [comment]
Anybody is welcome to contribute!

**Comment by pushit-tech** [comment]
Alright, I've created the PR. Since I'm new to this process, I've made it up to [this point](https://github.com/backstage/backstage/pull/20893). Is there anything else that needs to be done? Should I tag the reviewers?

Thanks.
