### ISSUE TITLE
TechDocs plugin entity page routing inconsistent with other plugins

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#2091]
The `techdocs` plugin currently does not use the same route syntax for entities as some of the other plugins with use 
`EntityCompoundName` & `useEntityCompoundName`. It also defines a new `ParsedEntityId` type which is exactly the same as `EntityCompoundName` except not exported (even though it is part of the plublic `ApiRef)

NOTE: This is somewhat related to #2082 

## Expected Behavior

Other plugins (e.g. `github-actions`) use the route definition `[plugin]/:kind/:optionalNamespaceAndName/`. They also use the `useEntityCompoundName` & `EntityCompoundName`.

## Current Behavior

The route is defined as `/docs/:entityId/*`. This means the url format is also different and the namespace is also required (e.g `docs/Component:default:component-name` vs `docs/Component/component-name`)

## Possible Solution

Make the `techdocs` entity route and behavour work and use the same shared code other plugins use.

**Comment by emmaindal** [comment]
Hey @andrewthauer thanks for reporting. I'll link to this RFC here for further reading https://github.com/spotify/backstage/issues/1947.

**Comment by OrkoHunter** [comment]
@hooloovooo I wonder if this issue can be closed now. #2812 was merged and maybe this issue got solved. Please correct if I am wrong. :)

**Comment by hooloovooo** [comment]
Closing this now, the spec has changed and we should be following the new specification decided upon here https://backstage.io/docs/architecture-decisions/adrs-adr009
If I'm wrong we can create a new issue that explains what differs from the spec.
