### ISSUE TITLE
🐛 Bug Report: `file /plugins/github-actions/examples/sample.yaml does not exist` in docker image utilizing local catalog file targets + other inconsistencies when indexing catalog entities from in-Docker filesystem

### ISSUE THREAD

**Issue by dimisjim** [backstage/backstage#20940]
### 📜 Description

Hey there,

I am trying to run backstage and test it out, but having issues with Index Search specifically getting this error: https://backstage.io/docs/reference/plugin-search-backend-node.missingindexerror/

Previous gh issues that I found are the following:
- https://github.com/backstage/backstage/issues/15260
- https://github.com/backstage/backstage/issues/14402

I am using the defaults (thus the in-memory engine)

Thanks a lot for the help.

### 👍 Expected behavior

Index entities, components, plugins etc and not get the missingindexerror

### 👎 Actual Behavior with Screenshots

logs before getting below error, which indicate some sort of a problem with the indexer:

```
{"documentType":"adr","level":"warn","message":"Index for adr was not created: indexer received 0 documents","plugin":"search","service":"backstage","type":"plugin"}
{"documentType":"software-catalog","level":"warn","message":"Index for software-catalog was not created: indexer received 0 documents","plugin":"search","service":"backstage","type":"plugin"}
{"documentType":"techdocs","level":"warn","message":"Index for techdocs was not created: indexer received 0 documents","plugin":"search","service":"backstage","type":"plugin"}
```

and what one can see when trying use the search function in the GUI:

![image](https://github.com/backstage/backstage/assets/6890249/b1cce3ad-b51a-472f-ba3f-79a73f80f75e)

I am not sure if this is normal or related, but I am also getting these:

```
{"entity":"location:default/generated-58b6f58d4077040fa0ffc3173afb4b5a8d3469f3","level":"warn","location":"file:/catalog-model/examples/all.yaml","message":"file /catalog-model/examples/all.yaml does not exist","plugin":"catalog","service":"backstage","type":"plugin"}
{"entity":"location:default/generated-a4deb700bdf111e8c68fa8612af943d4b9efc201","level":"warn","location":"file:/catalog-model/examples/acme-corp.yaml","message":"file /catalog-model/examples/acme-corp.yaml does not exist","plugin":"catalog","service":"backstage","type":"plugin"}
{"entity":"location:default/generated-17fabba6cc3ac1238ac94c2254a6f6e3b3d5fbe1","level":"warn","location":"file:/plugins/github-actions/examples/sample.yaml","message":"file /plugins/github-actions/examples/sample.yaml does not exist","plugin":"catalog","service":"backstage","type":"plugin"}
{"entity":"location:default/generated-00ef9e1b5d22fd97e8b9a1605e80ad3aeefb7be5","level":"warn","location":"file:/plugins/techdocs-backend/examples/documented-component/catalog-info.yaml","message":"file /plugins/techdocs-backend/examples/documented-component/catalog-info.yaml does not exist","plugin":"catalog","service":"backstage","type":"plugin"}
{"entity":"location:default/generated-963389f5df5c2dda44c09e07fa4eeb19742a118c","level":"warn","location":"file:/plugins/adr/examples/component/catalog-info.yaml","message":"file /plugins/adr/examples/component/catalog-info.yaml does not exist","plugin":"catalog","service":"backstage","type":"plugin"}
{"entity":"location:default/generated-69c0de6498e7e0283b47d85d5c4dd6b51f147ba3","level":"warn","location":"file:/plugins/scaffolder-backend/sample-templates/all-templates.yaml","message":"file /plugins/scaffolder-backend/sample-templates/all-templates.yaml does not exist","plugin":"catalog","service":"backstage","type":"plugin"}
```

### 👟 Reproduction steps

1. using the example app-config.yaml as mentioned in the docs, with localhost as its base url
2. build image with host build method (including yarn install, tsc, build cmds before) and Dockerfile found in packages/backend, using node v20 (issue is there in node 18 too)
3. docker run it locally 
4. issue manifests when trying to search for anything

### 🖥️ Your Environment

1. Mac M1 machine with buildx and using platform linux/amd64 for the builds
2. node v20
3. yarn v3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by emmaindal** [comment]
Hello @dimisjim Thanks a lot for opening this issue.

I see you point out missing indices for `adr`, `software catalog` and `techdocs`. Do you still see search results if you click on `tools`? 

I'm able to go through the steps you provided to reproduce (thanks for providing those), and I am able to reproduce the issue you are seeing. I can see in my logs for example:

```
{"documentType":"software-catalog","level":"warn","message":"Index for software-catalog was not created: indexer received 0 documents","plugin":"search","service":"backstage","type":"plugin"}
```

but then right after
```
{"documentType":"software-catalog","level":"info","message":"Collating documents for software-catalog succeeded","plugin":"search","service":"backstage","type":"plugin"}
```

I think this happens because of the lines over at https://github.com/backstage/backstage/blob/master/plugins/search-backend-node/src/engines/LunrSearchEngine.ts#L170-L172. 

Because if I then register a new entity that I have created. So that we actually have something to index, its working fine and I can see only the following log:

```
{"documentType":"software-catalog","level":"info","message":"Collating documents for software-catalog succeeded","plugin":"search","service":"backstage","type":"plugin"}
```

+ the expected entity appear in search result.

Can you check on your side if you start to see a different behaviour if you have entities to index? If so I think this is by design. 

As a followup, if you see the same behaviour as I've outlined above, we can talk about if we should change [this code](https://github.com/backstage/backstage/blob/master/plugins/search-backend-node/src/engines/LunrSearchEngine.ts#L170-L172) to not check for number of documents to index when deciding to set the index or not.

**Comment by dimisjim** [comment]
hey @emmaindal 

Thanks for your response.

I think the issue lies primarily with these warnings (I've started from scratch and created a new app via `npx @backstage/create-app@0.5.6` - and not used the code directly as is in the repo):

```
Loaded config from app-config.yaml, app-config.production.yaml
{"entity":"location:default/generated-eeed3503740b7c4b80f2aad3e417fafee7a3803d","level":"warn","location":"file:/examples/entities.yaml","message":"file /examples/entities.yaml does not exist","plugin":"catalog","service":"backstage","type":"plugin"}
{"entity":"location:default/generated-0ca6551527608b8e42ccccd463f27d4113d35ff1","level":"warn","location":"file:/examples/org.yaml","message":"file /examples/org.yaml does not exist","plugin":"catalog","service":"backstage","type":"plugin"}
{"entity":"location:default/generated-c4d4a3f82d0b7ecef1bd7d6a1991be94fded46aa","level":"warn","location":"file:/examples/template/template.yaml","message":"file /examples/template/template.yaml does not exist","plugin":"catalog","service":"backstage","type":"plugin"}
```

when I package the docker image, it looks like it can't find the yamls relatively, as it can when running `yarn dev`

**Comment by dimisjim** [comment]
I actually solved this by adding some extra steps in the Dockerfile that copy the example catalog files into the image, but it actually doesn't index all of them, some are stuck in an indexing loop, seen in the logs trying to index them but not properly displaying them in backstage.

**Comment by emmaindal** [comment]
@dimisjim would you say it could be helpful with some additional docs around how to add these extra steps in the Dockerfile? (even if these are just example files). If so, would you like to share what you added and where that info would be useful to have. 

on the second note - indexing loop, what errors do you see here?

**Comment by dimisjim** [comment]
@emmaindal 

It would be nice to add a note so that it's clearer that local in-repo catalog files in the demo repo & the ones included  during generating a new app via the create-app process one are not included by default in the provided Dockerfile.

>on the second note - indexing loop, what errors do you see here?

I think the indexing is somehow done properly (for example I can find them in the search page), but when clicking on them I get: `There is no system with the requested kind, namespace, and name, Opens in a new window.`

The reverse happens as well, for some other components, I see them correctly in the catalog list (type: service), but when iI click to view their system, I get same `There is no system with the requested kind, namespace, and name, Opens in a new window.` error as above

Again, by searching them, I see the entities as expected, but some of them are missing their catalog detailed pages somehow. For example I see a service, but its system outputs this error when clicking on it. In some other cases, I only see the system, but don't see the service that uses it.

This does not happen when I run the same application locally with `yarn dev`. I do have a default app-config.yaml and another, prod one, but in both I have the same top level catalog configuration (according to their respective relative locations of course).

How could it be that the details pages of the entities that seem to be indexed are missing?

**Comment by dimisjim** [comment]
possibly related issue: https://github.com/backstage/backstage/issues/15260
