### ISSUE TITLE
🚀 Feature: Support the '--dirtyreload' option in 'techdocs-cli serve'

### ISSUE THREAD

**Issue by wtchnm** [backstage/backstage#20972]
### 🔖 Feature description

Enhance the functionality of 'techdocs-cli serve' to accommodate the 'mkdocs --dirtyreload' option. See https://github.com/mkdocs/mkdocs/pull/997.

### 🎤 Context

Currently, the process of building ~20 PlantUML diagrams with `plantuml-markdown` takes approximately 35 seconds on my M1 Max. With the integration of the '--dirtyreload' option, the update time for modified diagrams reduces significantly to around 3 seconds.

### ✌️ Possible Implementation

```
--- a/dist/cjs/mkdocsServer-107b8efd.cjs.js
+++ b/dist/cjs/mkdocsServer-107b8efd.cjs.js
@@ -76,6 +76,7 @@ const runMkdocsServer = async (options) => {
         ...options.dockerOptions || [],
         dockerImage,
         "serve",
+        "--dirtyreload",
         "--dev-addr",
         `0.0.0.0:${port}`,
         ...options.mkdocsConfigFileName ? ["--config-file", options.mkdocsConfigFileName] : []
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @wtchnm, would this PR provide what you asking for? https://github.com/backstage/backstage/pull/21403

**Comment by wtchnm** [comment]
Hey @awanlin, yes it does!
