### ISSUE TITLE
Vault Backend Plugin, not showing secrets, even when present in vault

### ISSUE THREAD

**Issue by iamsourabh-in** [backstage/backstage#20977]
### 📜 Description

When try to implement vault and vault-backend plugin

I have a secret placed in the path 'kubeos/dev/three-api'

Where,

mountEngine : kubeos
secret path : dev/three-api

Tried both Annotations added to catalog

vault.io/secrets-path: dev/three-api

vault.io/secrets-path: kubeos/dev/three-api

The vault front end plugin shows below errors respectively.

![image](https://github.com/backstage/backstage/assets/22702292/25dfb54d-b551-4df9-928f-b6008d31644f)

![image](https://github.com/backstage/backstage/assets/22702292/d96791fc-b2a7-4c6b-94c3-60e5071c69a8)

---

I can see the secret in Vault UI:

![image](https://github.com/backstage/backstage/assets/22702292/98c11841-7452-4409-8a73-81937aaac251)

![image](https://github.com/backstage/backstage/assets/22702292/1ff71c4c-d487-4c5f-8534-09cdfc0ef9a7)

---- When accesing the vault backend api directly give me the below error:

![image](https://github.com/backstage/backstage/assets/22702292/dbb03c95-9e0d-4e08-9913-67706ec9a7f4)

Any help is really appreciated. Thanks

### 👍 Expected behavior

IT should list down the secrets

API is responding with metadata, when working with the same token
![image](https://github.com/backstage/backstage/assets/22702292/b473e348-7bfb-40bf-abfd-a9c9de01e3c5)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/22702292/fe45b0dc-34cb-433e-a9aa-fbce33037617)

### 👟 Reproduction steps

 yarn add --cwd packages/app @backstage/plugin-vault 
yarn add --cwd packages/backend @backstage/plugin-vault-backend

vault is running locally, and the config is:

vault:
  baseUrl: http://127.0.0.1:8200
  token: hvs.UnboJQkUw6dM5gLZ2N6ien5y
  secretEngine: 'kubeos' # Optional. By default it uses 'secrets'. Can be overwritten by the annotation of the entity

### 📃 Provide the context for the Bug.

command used to Enable Engine in Vault Kv

vault secrets enable -version=2 -path="kubeos" kv

### 🖥️ Your Environment

yarn dev, running it locally

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by ivangonzalezacuna** [comment]
Which version of vault are you using? In our company we had a version 1.14.X and we updated it to 1.15.0 last week. Now it looks like the endpoints are not working anymore, even with the CURL commands. I will check if there was any API changes that might need changes in the plugin

**Comment by ivangonzalezacuna** [comment]
> Which version of vault are you using? In our company we had a version 1.14.X and we updated it to 1.15.0 last week. Now it looks like the endpoints are not working anymore, even with the CURL commands. I will check if there was any API changes that might need changes in the plugin

Ok, that issue was unrelated. Something was wrong in our deployment, a restart fixed it. In your case, my next guess:

Your secret is called `dev/devtree-api`. I think what you need to do is using just `dev` as the secret-path. If you make the api call `<ENDPOINT>/v1/kubeos/metadata/dev?list=true` (what the API does internally), you should get the secret as part of the response. What, I guess, is happening there, is that you're trying to list over an actual secret, so the API complains.

**Comment by iamsourabh-in** [comment]
This works @ivangonzalezacuna Thanks. Can the error be a bit developer friendly. I will try to add few details in docs

**Comment by ivangonzalezacuna** [comment]
Hi @iamsourabh-in, not sure if a better error message would be possible here. That's a thing that the Vault API should change, because we cannot really distinguish between a not-found and a listing-key-instead-of-directory. Adding some information about it in the docs would be the best solution in my opinion.
