### ISSUE TITLE
🐛 Bug Report: Broken Table filters for invalid Initial States

### ISSUE THREAD

**Issue by jasongornall-dd** [backstage/backstage#20971]
### 📜 Description

Broken filters occur if there is an invalid initialState that doesn't match some of the data coming in
https://codesandbox.io/s/sleepy-field-nmypkz?file=/src/App.tsx

### 👍 Expected behavior

It should remove the invalid state

### 👎 Actual Behavior with Screenshots

A broken UI appears 
![image](https://github.com/backstage/backstage/assets/113055843/f17994e1-d3a9-407c-91e7-1c39530c2b75)

### 👟 Reproduction steps

See CodeSandbox for repro https://codesandbox.io/s/sleepy-field-nmypkz?file=/src/App.tsx 

### 🖥️ Your Environment

CodeSandbox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by vinzscam** [comment]
thanks for reporting this!

Yeah, it looks like the issue is related to the `<Select />` component
