### ISSUE TITLE
🚀 Feature: built-in support for Azure key vault and Azure app configuration

### ISSUE THREAD

**Issue by sanderaernouts** [backstage/backstage#20982]
### 🔖 Feature description

Support loading secrets from Azure key vault and configuration values from Azure app configuration in Backstage's configuration system.

Something similar was discussed for Vault, but that issue went stale and was closed: https://github.com/backstage/backstage/issues/10278

### 🎤 Context
In Azure, you can use managed identities and workload identities to delegate the secret handling to Azure, but this is not always an option. 

Azure key vault is meant to store your application secrets, and Azure app configuration is meant to store your application's configuration. In Azure app configuration, you can [reference secrets from key vault](https://learn.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-dotnet-core?tabs=core6x) so that you can have both your regular configuration and secrets in one place.

The current way to leverage these services, provided that you are hosting in Azure App Services, is to use [app configuration references](https://learn.microsoft.com/en-us/azure/app-service/app-service-configuration-references#reference-syntax) and/or [key vault references](https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli#source-app-settings-from-key-vault) in your app settings. The downside is the app settings are passed on as environment variables and anyone with sufficient access to the app service can access the environment variables through the [app service editor (kudu)](https://github.com/projectkudu/kudu).

For Kubernetes, you could use the [Azure key vault secrets provider](https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-driver) but I think to use mounted secrets Backstage would have to support Kubernetes secrets. For Azure app configuration, there is no good alternative, it seems, beyond [passing values to helm install](https://learn.microsoft.com/en-us/azure/azure-app-configuration/integrate-kubernetes-deployment-helm), which makes them static.

Built-in support for Azure key vault and Azure app configuration would allow you to keep the secrets secret and only allow access to them in-process. We would then also enable [dynamic configuration](https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core?tabs=core6x) for Backstage using the `push` or `poll` model.

### ✌️ Possible Implementation

I think there are generally two ways to go about this:
- either load secrets and configuration directly from key vault and app configuration
- or add a reference similar to the environment variables: `${ENV_VAR}`

## Load secrets and configuration directly from key vault and app configuration

The configuration system in .NET is very similar to the one in Backstage. It supports loading config from multiple sources and merges all sources into a single `IConfiguration` object.  Both Azure key vault and Azure app configuration have a predefined separator (`:`) to specify how the configuration/secret key maps to the configuration object structure.

So a `config` like this: 
```yaml
config:
  secret: value
```

Would result in an entry like this:
```text
Config:Secret-> value
```

It is common to provide a prefix that the provider strips. So, adding the prefix `Backstage` would result in a key like this:
```text
Backstage:Config:Secret-> value
```

_NOTE: In Azure app configuration, `value` refers to a key vault secret._

## Custom transformations

Inspired by [key vault references for Azure App Services](https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli#source-app-settings-from-key-vault):
```yaml
config:
  secret: @Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mysecret/)
```

And [app configuration references for Azure App Services](https://learn.microsoft.com/en-us/azure/app-service/app-service-configuration-references#reference-syntax):
```yaml
config:
  key: @Microsoft.AppConfiguration(Endpoint=https://myAppConfigStore.azconfig.io; Key=myAppConfigKey; Label=myKeysLabel)​
  secret: @Microsoft.AppConfiguration(Endpoint=https://myAppConfigStore.azconfig.io; Key=myAppConfigSecret; Label=myKeysLabel)​
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sanderaernouts** [comment]
Tagging @Rugvip, @freben, and @jhaals since you were involved in the discussion around #10278. Looks the discussion (sort of) settled on custom transformations, is that still the way to go in your opinion?

**Comment by freben** [comment]
@Rugvip will know best, but after https://github.com/backstage/backstage/pull/17209 there's now also the ability to add a completely custom config source that is fed off of remote data, if that's of interest. I guess the drawback there is that that source would also need to know where in the config tree to place values, so maybe it's cleaner anyway to work out what some placeholder format would be in the files themselves instead.

**Comment by sanderaernouts** [comment]
Azure key vault and app configuration can deal with trees using the `:` separator. So `Backend:Database:Connection:Token` could be placed into the tree at:
```yaml
backend:
  database:
    connection:
      token: ...
```
With a placeholder, you would not have to match Backstage's config schema. But can placeholder values be reloaded at runtime? Or does the require a restart?

**Comment by Rugvip** [comment]
Discussed this a bit now and thinking that the cleanest implementation is to implement this as a custom config `SubstitutionFunc`. By default we use `(name: string) => process.env[name]` to translate `${<name>}` in config, but you can provide arbitrary `string => Promise<string | undefined>` logic there. We could for example have a prefix like `azure-key-vault:` that translates into fetching credentials from a separate source, for example:

```yaml
backend:
  database:
    connection:
      token: '${azure-key-vault:backendDatabaseToken}'
```

Regardless of if we ship that as part of the default setup or not I think it'd be best to introduce a bit of an abstraction around this too, something like this:

```ts
ConfigSources.default({
  substitutionFunc: ConfigSubstitutions.merge(
    azureKeyVaultConfigSubsitution(), // or ConfigSubsitutions.azureKeyVault()
    ConfigSubstitutions.env(),
  ),
})
```

The base for that might be an interface that looks something like

```ts
interface ConfigSubsitution {
  predicate(str: string) => boolean; // Checks for certain prefix or similar
  resolve(str: string) => Promise<string | undefined> | AsyncGenerator<{ value?: string }, void, void>
}
```

Threw in `AsyncGenerator` there too since one other missing piece here is to allow for watching also for substitutions. Tbh we probably skip the `Promise<string | undefined>` version altogether if we got straight for that since that's pretty trivial to implement with an async generator anyway. We'd prolly move away from the `substitutionFunc` name as well and make that an `substitution` option instead.

---

Another much simpler but less neat direction is to create a separate config source that allows you to map key stored in the vault to certain config paths. That's much simpler to implement but more config and formats to manage so not as neat of a long-term solution. Probably something to ship as a separate package outside of this repo that can fill this gap in the meantime if needed.

**Comment by sanderaernouts** [comment]
@Rugvip would an `AsyncGenerator` also allow refreshing settings/secrets at runtime? One more thing we need to think about is how you configure which key vault or app configuration endpoint to use. You'll use different ones for different environments. Or, in the case of app configuration, you can also use labels. Does a substitution have access to the rest of the config? So that you could have a section like this:

**Comment by sanderaernouts** [comment]
@Rugvip any thoughts on the above? I'm happy to start working on a draft PR to implement this as a custom config `SubstitutionFunc` once those details are (somewhat) settled.

I'll probably need some help and guidance, though as I haven't touched the config part of Backstage before 👼

**Comment by Rugvip** [comment]
@sanderaernouts sourcing the endpoint from other parts of the config is gonna leave us with some awkward chicken and egg problems I worry. The config loader substitution runs on the entire config data object so we'd need to split that up into steps where some config features read from the pre-substitution config and the rest read from the resulting config, which I worry might be very confusing. Do you think it would be feasible to stick to using the full secret URI everywhere or is that gonna be ridiculously verbose?

Implementation-wise the starting point is kind of in this area: https://github.com/backstage/backstage/blob/160ff1a532c78479db438abcc9ee72515b0f6295/packages/config-loader/src/sources/transform/apply.ts#L28

The transformer there is what does all of the substitutions, and if we turn them into async generators that part of the code is gonna need a significant refactor.

**Comment by Rugvip** [comment]
@sanderaernouts yep tbh I think we could give it a go. Most likely as a config transform that accepts a `ConfigSource` and produces a new `ConfigSource`, while it's able to read from the incoming config to configure itself. It's easier than messing with the substitution func, but it does mean we need to use a separate substitution syntax that our existing one unless we install an explicit passthrough substitution like `str => '${' + str + '}'`.

**Comment by sanderaernouts** [comment]
I'll see if I can get started on a draft PR soon to iron out this feature

**Comment by sanderaernouts** [comment]
I haven't gotten around to this, but it's still on my to do list.
