### ISSUE TITLE
🐛 Bug Report: Display Problems on Cluster View

### ISSUE THREAD

**Issue by eceeeren** [backstage/backstage#20991]
### 📜 Description

Hello,

My company displays Clusters with the help of EntityKubernetesContent view in @backstage/plugin-kubernetes plugin. However in some sections, the displaying of the information is not formatted well. Please let me know if there can be anything done about this issue.

Thanks

### 👍 Expected behavior

It should format the information in a more readable way.

### 👎 Actual Behavior with Screenshots

![cluster](https://github.com/backstage/backstage/assets/23586149/5889cd3e-4b3b-4af7-bf9c-3b98327870d3)

![taskruns](https://github.com/backstage/backstage/assets/23586149/613b12fb-c861-4c87-8bec-d156c0b1ee25)

### 👟 Reproduction steps

1. '@backstage/plugin-catalog' is added
2. EntityKubernetesContent apge from '@backstage/plugin-kubernetes' is added
3. In the Backstage Dashboard, navigate to Catalog
4. Inside the Catalog, navigate to Kubernetes tab
5. Inside Kubernetes tab, scroll down to "Your Clusters"
6. Observe "Pipeline Specs" and "Task Runs"

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jamieklassen** [comment]
@mclarke47 I think I've seen this kind of weird formatting in the pod drawer too, wdyt?

**Comment by mclarke47** [comment]
This looks like a [structured-metadata-table](https://backstage.io/storybook/?path=/story/data-display-structured-metadata-table--default) with a very nested object.

I think the solution for this would be to revisit https://github.com/backstage/backstage/issues/5511 so that you could bring your own UI for Custom resources
