### ISSUE TITLE
🐛 Bug Report: Additional note in the documentation when changing the font

### ISSUE THREAD

**Issue by Ninosaurier** [backstage/backstage#21026]
### 📜 Description

I had tried to change the font using mkdocs.yaml. I wanted to avoid accessing Google fonts when creating documentation.

I realized that the documentation (https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/) is incomplete. The configuration:

```
theme:
  font: false
```

### 👍 Expected behavior

It should prevent the download of Google fonts.

### 👎 Actual Behavior with Screenshots

It does not work. 
It works only with the addition "name: material", the download of Google fonts is prevented. Solution:

```
theme:
  name: material
  font: false
```

I would like to add this information to the documentation. Do you have a suggestion where to add it?

### 👟 Reproduction steps

1. Create a simple Backstage Component in GitHub or GitLab and add it in backstage
2. Install mkDocs and follow the example (https://backstage.io/docs/features/techdocs/getting-started)
3. Add the following in the mkdocs.yaml :

```
site_name: 'example-docs'
nav:
  - Home: index.md
theme:
  font: false
plugins:
  - techdocs-core

```
4. Create the folder "docs" at the root of the repo and inside a simple index.md
5. Try to view the documentation in Backstage

### 🖥️ Your Environment

OS:   Linux 5.15.0-53-generic - linux/x64
node: v18.18.2
yarn: 1.22.19
cli:  0.22.13 (installed)
backstage:  1.18.0

Dependencies:
  @backstage/app-defaults                                          1.4.3
  @backstage/backend-app-api                                       0.5.5, 0.5.6
  @backstage/backend-common                                        0.19.7, 0.19.8
  @backstage/backend-dev-utils                                     0.1.1, 0.1.2
  @backstage/backend-openapi-utils                                 0.0.4
  @backstage/backend-plugin-api                                    0.6.5, 0.6.6
  @backstage/backend-tasks                                         0.5.10, 0.5.11
  @backstage/catalog-client                                        1.4.4, 1.4.5
  @backstage/catalog-model                                         1.4.2, 1.4.3
  @backstage/cli-common                                            0.1.12, 0.1.13
  @backstage/cli-node                                              0.1.4, 0.1.5
  @backstage/cli                                                   0.22.13
  @backstage/config-loader                                         1.5.0, 1.5.1
  @backstage/config                                                1.1.0, 1.1.1
  @backstage/core-app-api                                          1.10.0, 1.11.0
  @backstage/core-components                                       0.13.5, 0.13.6
  @backstage/core-plugin-api                                       1.6.0, 1.7.0
  @backstage/errors                                                1.2.2, 1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.6, 0.1.7
  @backstage/integration-react                                     1.1.19, 1.1.20
  @backstage/integration                                           1.7.0, 1.7.1
  @backstage/plugin-api-docs                                       0.9.11
  @backstage/plugin-app-backend                                    0.3.53
  @backstage/plugin-app-node                                       0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.1.2
  @backstage/plugin-auth-backend-module-github-provider            0.1.2
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.2
  @backstage/plugin-auth-backend-module-google-provider            0.1.2
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.2
  @backstage/plugin-auth-backend                                   0.19.2
  @backstage/plugin-auth-node                                      0.3.2, 0.4.0
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.2
  @backstage/plugin-catalog-backend                                1.13.3
  @backstage/plugin-catalog-common                                 1.0.16, 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.36
  @backstage/plugin-catalog-import                                 0.10.0
  @backstage/plugin-catalog-node                                   1.4.6, 1.4.7
  @backstage/plugin-catalog-react                                  1.8.4, 1.8.5
  @backstage/plugin-catalog                                        1.13.0
  @backstage/plugin-events-node                                    0.2.14
  @backstage/plugin-github-actions                                 0.6.5
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-org                                            0.6.14
  @backstage/plugin-permission-common                              0.7.8, 0.7.9
  @backstage/plugin-permission-node                                0.7.16, 0.7.17
  @backstage/plugin-permission-react                               0.4.15, 0.4.16
  @backstage/plugin-proxy-backend                                  0.4.2
  @backstage/plugin-scaffolder-backend                             1.17.3
  @backstage/plugin-scaffolder-common                              1.4.1
  @backstage/plugin-scaffolder-node                                0.2.5
  @backstage/plugin-scaffolder-react                               1.5.5
  @backstage/plugin-scaffolder                                     1.15.0
  @backstage/plugin-search-backend-module-catalog                  0.1.9
  @backstage/plugin-search-backend-module-pg                       0.5.14
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10, 1.2.9
  @backstage/plugin-search-backend                                 1.4.5
  @backstage/plugin-search-common                                  1.2.6, 1.2.7
  @backstage/plugin-search-react                                   1.7.0, 1.7.1
  @backstage/plugin-search                                         1.4.0
  @backstage/plugin-tech-radar                                     0.6.8
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.0
  @backstage/plugin-techdocs-node                                  1.9.0
  @backstage/plugin-techdocs-react                                 1.1.11, 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.10
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.3
  @backstage/theme                                                 0.4.2, 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.5, 1.0.6

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @Ninosaurier, it would make sense to add this information here: https://github.com/backstage/backstage/blob/master/docs/features/techdocs/how-to-guides.md. Would you be willing to submit a PR with this addition? If yes please just tag me so I can help review 👍

**Comment by awanlin** [comment]
Fixed by https://github.com/backstage/backstage/pull/21277
