### ISSUE TITLE
🚀 Feature: Support custom middleware declarations/configurations on startTestBackend helper

### ISSUE THREAD

**Issue by RubenV-dev** [backstage/backstage#21053]
### 🔖 Feature description

Provide an options field to the `startTestBackend` helper thats lets you configure middleware on the helper similar to the `configure` option in [rootHttpRouterServiceFactory](https://backstage.io/docs/backend-system/core-services/index/#configuring-the-service-1)

### 🎤 Context

WHEN testing the `oidc-auth-provider/module` or the `pinniped-auth-module` and trying to set up an express server/test bed using the `startTestBackend` helper 
AND you have configured your app-config with all the necessary configurations required to use the oidc auth-provider 
AND you have an authentication authority configured like microsoft-azure with credentials defined in your app-config

You will run into an error that states "session support is required"

In previous testing setups I would resolve that error with a test implementation like the following:
```
const secret = 'secret';
      app = express()
        .use(cookieParser(secret))
        .use(
          session({
            secret,
            saveUninitialized: false,
            resave: false,
            cookie: { secure: false },
          }),
        )
        .use(passport.initialize())
        .use(passport.session());
      await new Promise(resolve => {
        backstageServer = app.listen(0, '0.0.0.0', () => {
          appUrl = http://127.0.0.1:${
            (backstageServer.address() as AddressInfo).port
          };
          resolve(null);
        });
      });
```
where middleware's were appended to the express server that would allow the oidc passport strategies used in the oidc auth provider to make use of sessions.

### ✌️ Possible Implementation

After speaking with @Rugvip and looking at the file in question [here](https://github.com/backstage/backstage/blob/ae810386bed7b46ee404bf6be8cf634bc6129bae/packages/backend-test-utils/src/next/wiring/TestBackend.ts#L204),

A possible implementation here could be to add a option to `startTestBackend` similar to the `configure` one for the `rootHttpRouterServiceFactory` that lets you configure the middleware. For that use a better name is prolly configureRootHttpRouter.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
You'd rather do this by supplying a replacement rootHttpRouter implementation, right?

**Comment by RubenV-dev** [comment]
> You'd rather do this by supplying a replacement rootHttpRouter implementation, right?

Yeah thats the general idea.

**Comment by freben** [comment]
What I mean is, you'd rather add that as any other test feature.

```ts
startTestBackend({
  features: [
    myReplacementRootRouter
  ]
})
```

Then maybe there can be helpers for making a root router with added middleware or so. But not as a param to `startTestBackend` itself.

**Comment by luchillo17** [comment]
@freben Any update on this? I'm about to try and tackle this and the way I have come up with so far is to add a `rootHttpRouterConfig` variable to the `startTestBackend` helper options, that would work kind of like the config variable of the original `rootHttpRouterFactory`.

**Comment by freben** [comment]
Ping @Rugvip for ideas here too.

It's unfortunate that the root router isn't "pure" (it sets internal hidden state as part of its creation). Not at my computer now but I'll ponder it. Would have been great if it were possible to just use the regular DI mechanisms but maybe it's not an option at this point.

**Comment by luchillo17** [comment]
@andmagom on my team asked if we can make either the `config` function option in the `rootHttpRouterFactory` be an extension point, sounds like an interesting way to provide that instead of it being in the options but I see no benefit for this issue in doing so.

The main issue is how to return the `server` instance so `supertest` can make requests to it, if we manage to do that we can remove the custom `rootHttpRouterFactory` we have inside the `TestBackend.ts`.

**Comment by Rugvip** [comment]
@luchillo17 I proposed #21445 as a solution from a different angle. Thinking about this a bit I realized that plugins and modules shouldn't really need to depend on the behavior of a particular root http router configuration. It might be useful to mock in some cases, but that's a bit different from what we're doing here and you'd prolly use the real `createBackend` at that point rather than `startTestBackend`.

**Comment by luchillo17** [comment]
Did I miss something? you removed the session part and added it to the auth config, does that bit enable session support?

**Comment by Rugvip** [comment]
@luchillo17 a key bit is that I'm installing the auth plugin in the test backend as well, the `import('@backstage/plugin-auth-backend')` line. The plugin takes care of installing route handlers for the module, as well as adding middleware for session support.

**Comment by luchillo17** [comment]
Hmm I thought there was no session support and that's why both VMware & pinniped providers had issues with `startTestBackend`, did we miss something or someone added support recently?

**Comment by Rugvip** [comment]
@luchillo17 ah, forgot this was gonna be closed on merge 😅. Either way I think the current state of things are fine in that there really shouldn't be any reason for plugins or modules to need to reconfigure the root http router. Just to reiterate: session support is provided by the auth backend plugin, so by including that plugin as part of the test it works as expected. It also ends up being a better integration test compared to wiring up the module handlers manually.
