### ISSUE TITLE
🐛 Bug Report: Getting Started Kubernetes Docs Improvement

### ISSUE THREAD

**Issue by emlance** [backstage/backstage#21061]
### 📜 Description

For newbies like me that don’t know React, I started putting up a test website entity and wondered why it doesn't show the Kubernetes tab. After going around back and forth many times in my configurations if i missed anything - I finally realized that the comment in https://backstage.io/docs/features/kubernetes/installation#adding-the-kubernetes-frontend-plugin 

`"// You can add the tab to any number of pages, the service page is shown as an". `

This comment is actually telling me to add it to the websiteEntityPage, so then I tried and it worked. 

Even the troubleshooting docs https://backstage.io/docs/features/kubernetes/troubleshooting does not mention that possibly the code in the frontend was not added accordingly.

### 👍 Expected behavior

I notice that by default, during initial setup, there are 3 EntityPages, and so it will be clearer if these EntityPages were mentioned in the documentation.

I propose the documentation should show like this: (or anything similar to easily notice that there are indeed different EntityPages.

```
// You can add the tab to any number of pages, the service page is shown as an
// examples here
const serviceEntityPage = (
  <EntityLayout>
    {/* other tabs... */}
    <EntityLayout.Route path="/kubernetes" title="Kubernetes">
      <EntityKubernetesContent refreshIntervalMs={30000} />
    </EntityLayout.Route>
  </EntityLayout>
);

//This is entity page for websites
const websiteEntityPage = (
  <EntityLayout>
    {/* other tabs... */}
    <EntityLayout.Route path="/kubernetes" title="Kubernetes">
      <EntityKubernetesContent refreshIntervalMs={30000} />
    </EntityLayout.Route>
  </EntityLayout>
);
 
//This is the default entity page
const defaultEntityPage = (
  <EntityLayout>
    {/* other tabs... */}
    <EntityLayout.Route path="/kubernetes" title="Kubernetes">
      <EntityKubernetesContent refreshIntervalMs={30000} />
    </EntityLayout.Route>
  </EntityLayout>
);
```
or mention this in the https://backstage.io/docs/features/kubernetes/troubleshooting 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/48013217/66e6cb91-1ca4-45b4-b568-a4fd1f52ad8c)

### 👟 Reproduction steps

https://backstage.io/docs/features/kubernetes/installation
https://backstage.io/docs/features/kubernetes/troubleshooting

This issue I encountered appears to be similar with: https://github.com/backstage/backstage/issues/18811 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by tudi2d** [comment]
Hej @emlance - welcome to the community 🎉  Thanks for highlighting this & breaking it down clearly. Our docs are far from perfect & we are always open to improve them. Would you be up to create a PR out of your suggestions? :)

**Comment by emlance** [comment]
Hi @tudi2d thank you for the warm welcome. Sure, I will work on that. Cheers! 🍻
