### ISSUE TITLE
🚀 Feature: Commenting and Suggestions Addon for TechDocs Plugin

### ISSUE THREAD

**Issue by theparthshukla** [backstage/backstage#21091]
### 🔖 Feature description

This addon will introduce the ability for users to comment and leave suggestions on documentation right within the TechDocs plugin. It will allow:

- Inline comments and suggestions.
- Threaded discussions for each comment.
- Resolving comments once they have been addressed.
- A moderation system for reviewing and managing comments and suggestions.

### 🎤 Context

The TechDocs plugin in Backstage is a powerful tool for technical documentation. However, there is a lack of features for collaborative feedback from the users. Introducing a commenting and suggestions addon can bridge this gap and enhance the collaborative nature of documentation.

### ✌️ Possible Implementation

1. Backend Service:

- Create a new microservice or extend the existing techdocs-backend plugin to handle the storage, retrieval, and management of comments and suggestions.
- Implement authentication and authorization to ensure that only authorized users can comment, reply, and moderate.
- Database:
- Use a relational database like PostgreSQL to store comments and suggestions with relations to the documents and users.

2. Frontend:

- Extend the TechDocs frontend plugin to include a new UI component for displaying, adding, replying to, and moderating comments and suggestions.
- Implement a new context menu for highlighting text and adding inline comments and suggestions.
3. APIs:
- Define new APIs for creating, retrieving, updating, and deleting comments and suggestions.
- Implement real-time updates to display new comments and suggestions without requiring a page refresh.

4. Testing:

- Write unit and integration tests to cover the new functionality.
- Document the new APIs and create example use cases.

5. Documentation:

- Update the Backstage documentation to include information about the new addon, how to install it, and how to use it.
```

│
├── plugins
│   ├── techdocs
│   │   ├── src
│   │   │   ├── components
│   │   │   │   ├── TechDocsPage.tsx
│   │   │   │   ├── CommentingUI.tsx       # New UI component for comments and suggestions
│   │   │   │   └── ...
│   │   │   ├── api.ts                     # API client for interacting with the backend
│   │   │   └── ...
│   │   └── ...
│   ├── techdocs-comments-addon            # New plugin directory
│   │   ├── src
│   │   │   ├── components
│   │   │   │   ├── Comment.tsx            # Component for rendering a comment
│   │   │   │   ├── Suggestion.tsx         # Component for rendering a suggestion
│   │   │   │   └── ...
│   │   │   ├── api.ts                     # API client for interacting with the backend
│   │   │   └── ...
│   │   └── ...
│   └── ...
├── backend
│   ├── src
│   │   ├── plugins
│   │   │   ├── techdocs.ts
│   │   │   ├── techdocs-comments-addon.ts # New backend plugin for comments and suggestions
│   │   │   └── ...
│   │   └── ...
│   └── ...
├── db                                       # Database directory (if a separate db is used)
│   ├── migrations
│   │   ├── create_comments_table.sql        # Migration for creating comments table
│   │   ├── create_suggestions_table.sql     # Migration for creating suggestions table
│   │   └── ...
│   └── ...
└── ...
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by alper98** [comment]
To me, this sounds like a job that the techdocs addon https://backstage.io/docs/reference/plugin-techdocs-module-addons-contrib.reportissue/ would solve

**Comment by hballangan-mdsol** [comment]
@theparthshukla any update on this? This is a really helpful feature, it's a wonder why no one has contributed yet? Have you started working on this effort?

**Comment by theparthshukla** [comment]
@hballangan-mdsol  haven't had the capacity yet, but something I would like to work on eventually (or contribute to if the effort is started)

**Comment by gauravbalyan** [comment]
@theparthshukla  any luck, do we have any update on this.

**Comment by briemarie** [comment]
My team would also find this very useful! The feedback we're getting from users is that we can't expect all docs to go into Backstage instead of using Google docs and Confluence until there is at least a comment feature. Teams need to be able to collab and leave feedback on docs.
