### ISSUE TITLE
🐛 Bug Report: Techdocs in-content edit link leads to missing page if techdocs annotation isn't ending with a /

### ISSUE THREAD

**Issue by luca-ballerini** [backstage/backstage#21146]
### 📜 Description

We are setting up multiple documentation folders in a single repository therefore we have created nested folder in order to keep the docs folder separated. We have followed the guidelines and example in https://backstage.io/docs/features/techdocs/how-to-guides#how-to-understand-techdocs-ref-annotation-values for adding our docs in a nested folder, and we set the techdocs annotation value to the folder containing the mkdocs file.

This is what the folders look like:
```
├── service1 
   └── mkdocs.yml
   ├──docs
       └── index.md
```
The annotation value:
`backstage.io/techdocs-ref: url:https://github.com/sqsp-scratchpad/backstage-staging-components/tree/master/service1`

With this configuration the docs site is created correctly however when the docs page are rendered the edit icon within the page content leads to a 404 page, instead of the respective .md file

### 👍 Expected behavior

If the annotation value is set to `https://github.com/sqsp-scratchpad/backstage-staging-components/tree/master/service1`, given the following directory structure:

```
├── service1 
   └── mkdocs.yml
   ├──docs
       └── index.md
```

The edit icon displayed in the content should link to `https://github.com/sqsp-scratchpad/backstage-staging-components/edit/master/service1/docs/index.md`

 

### 👎 Actual Behavior with Screenshots

The current behaviour is instead showing the link in the edit icon directing to `https://github.com/sqsp-scratchpad/backstage-staging-components/edit/master/docs/index.md`, ignoring `service1` in the filepath.

![inccorect_url](https://github.com/backstage/backstage/assets/54008768/83380276-bed9-49c6-8023-340c775c6b26)

![404_page](https://github.com/backstage/backstage/assets/54008768/a5feeba3-1b7a-42ea-83bc-d007e2f8b897)

### 👟 Reproduction steps

1. Nest the docs folder and the mkdocs.yaml file in a directory at least 1 level under the root.
2. Set the `backstage.io/techdocs-ref:` annotation to the absolute path to the folder containing the mkdocs file.
3. Refresh the component, visit the generated doc and hover/click over the edit icon

### 📃 Provide the context for the Bug.

We have found a fix for this behaviour, and the solution is to end the `backstage.io/techdocs-ref:` with a `/`

So this will direct to a 404 page:
`backstage.io/techdocs-ref: url:https://github.com/sqsp-scratchpad/backstage-staging-components/tree/master/service1`

This will direct to the correct file in github in edit mode:
`backstage.io/techdocs-ref: url:https://github.com/sqsp-scratchpad/backstage-staging-components/tree/master/service1/`

The example in the how-to guide doesn't mention the need of the `/`, this is an extract from the page:

```
Note, just as it's possible to specify a subdirectory with the dir: prefix, you can also provide a path to a non-root directory inside the repository which contains the mkdocs.yml file and docs/ directory.

e.g. url:https://github.com/backstage/backstage/tree/master/plugins/techdocs-backend/examples/documented-component
```

I think the correct behaviour should generate the correct link regardless if the annotation value ends with or without a `/` however if this isn't doable making it explicit in the documentation examples should help.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by johnphilip283** [comment]
Thank you for the comprehensive review of the bug! Since you marked yourself as willing to submit a PR, I'm going to assign you to this issue for now @luca-ballerini - feel free to unassign and leave a comment in case you're not able to raise a PR for this!
