### ISSUE TITLE
💬 RFC: Consolidate Entra ID Authentication Configuration

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#21158]
### 🔖 Need

Currently we have several Microsoft related plugins using Entra ID (previously known as Azure Active Directory) authentication.  
* Techdocs (Reader & Publisher)
* Microsoft Authentication provider
* Microsoft Graph EntityProvider/Processor
* Azure Devops
* Azure Sites
* Kubenetes

Each plugin has a slightly different implementation , supporting slightly different authentication methods.
(e.g. the Azure Devops plugin doesn't provide a way to use Workload Identity)
This is both duplicative from a code perspective, and also results in a lot of duplicate configuration in the YAML.

It also means we have inconsistent documentation on how to authenticate with azure.  It's also not always clear that you can share the same authentication details between the plugins. So it seems quite reasonable that if a user follows the docs on 4 different plugins, they'll end up with 4 separate app registrations with 4 separate client secrets, each of which likely have different expiration dates & rotation requirements.  Whilst there's nothing wrong with this approach, it adds additional complexity and sets users up for failure around credential expiration.

### 🎉 Proposal

1. We should introduce a single service that all plugins can use to get credentials from common configuration / code path.
2. When no configuration is provided, the configuration should have a reasonable default, meaning that in many cases users won't need to explicitly configure Entra ID credentials.

### EntraIDCredentialService

`TokenCredential` is an interface from the Azure SDK with one method `getToken(scopes, options)`, which returns a token that can be used to access azure services.
The idea of this type is to abstract away needing to know the method of getting a token (e.g. Workload Identity, Managed Identity, Open ID Connect Client ID / Secret etc.).
Different implementations of this type handle different scenarios (see https://learn.microsoft.com/en-us/javascript/api/overview/azure/identity-readme?view=azure-node-latest#credential-classes ).  This interface is used by almost all the Azure SDKs when authenticating with Azure.  

Our common service should provide a common way to get such a `TokenCredential`.  

```ts
import { TokenCredential } from "@azure/core-auth";

export interface EntraIDCredentialService {
    getCredential(opts: {
        name: string | undefined
    }): TokenCredential
}
```

#### Default Implementation
The default implementation of `EntraIDCredentialProvider` would read credentials from a configuration file.
Each credential has a name, which can be used by other plugins to reference an explicit set of credentials.
A default set of credentials can be specified by setting `defaultCredential` - when specified, calls to `getCredential` without a `name` will return the credential named by `defaultCredential`
 
```yaml
integrations:
  entra:
    # defaultCredential: NAME # reference to object in `integrations.entra.credentials`
    credentials:
      # DefaultAzureCredential
      defaultExample:
        authenticationMethod: default

      # WorkloadIdentityCredential
      workloadIdentityExample:
        authenticationMethod: workloadIdentity
        # tenantId: ${AZURE_TENANT_ID}
        # clientId: ${AZURE_CLIENT_ID}
        # tokenFilePath: ${AZURE_FEDERATED_TOKEN_FILE}
      
      # ManagedIdentityCredential
      managedIdentityExample:
        authenticationMethod: managedIdentity
        #clientId: /subscriptions/SUBSCRIPTION/resourceGroups/RESORUCE-GROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/NAME

      #ClientSecretCredential
      clientSecretExample:
        authenticationMethod: clientSecret
        tenantId: ${AZURE_TENANT_ID}
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}

```

#### A sensible Default

Whilst on the face of it, it may seem impossible to provide a default for credentials, that is actually not the case.
The Azure SDK provides a `DefaultAzureCredential` implementation of `TokenCredential` which tries to work out the most appropriate credential type:

* If well known environment variables are set, use those
* When deployed to Azure Kubenetes Service, auto detect the workload identity configuration and use that 
* When deployed to a resource with a system assigned identity (e.g. Azure App Services, VM)
* See if various try various local development tools are availble (Azure CLi, Visual Studio etc.).
  If so, use those to authenticate to azure.
  (This has the big advantage of meaning you don't have to put secrets in your local configuration files, meaning you can't accidently push them to git!)

By using this as our default credential type when there is no configuration provided, there is a good chance that Entra Id authentication will work without any additional configuration required.

See https://learn.microsoft.com/en-us/javascript/api/overview/azure/identity-readme?view=azure-node-latest#defaultazurecredential for more details.

#### Credential Caching

To ensure tokens are cached, the implementation should ensure that the `TokenCredential` objects created for each credentials are reused, and not recreated on every call to `getCredentials`.

### Plugins

Calling plugins would then use this service to get the credentials, rather than implementing their own logic / configuration
For example, the current microsoft graph configuration with an explicitly specified client id & client secret looks like:

```yaml
catalog:
  providers:
    microsoftGraphOrg:
      myCompany:
        tenantId: ${AZURE_TENANT_ID}
        clientId: ${AZURE_CLIENT_ID}
        clientSecret : ${AZURE_CLIENT_ID}
        # ...
```

In the new world, this would become:
```yaml
catalog:
  providers:
    microsoftGraphOrg:
      myCompany:
        credential: clientSecretCredentials # reference to object in `integrations.entra.credentials`
        # ...

integrations:
  entra:
    credentials:
      myCredentials:
        tenantId: ${AZURE_TENANT_ID}
        clientId: ${AZURE_CLIENT_ID}
        clientSecret : ${AZURE_CLIENT_ID}
```
And from a code, the plugin would get the credentials via the 
```ts
const tokenCredential = entraIdCredentialService.getCredential({ name: })
```

Whilst this second case is a bit more verbose than it was previously, things get significantly simpler for all further plugins.
For example, if adding the azure devops integration, rather than adding

```yaml
integrations:
  azure:
    - host: dev.azure.com
      credentials:
        - clientId: ${AZURE_CLIENT_ID}
          clientSecret: ${AZURE_CLIENT_SECRET}
          tenantId: ${AZURE_TENANT_ID}
```

you would only need to add

```yaml
integrations:
  azure:
    - host: dev.azure.com
      credentials:
        - name: myCredentials
```

Things get even simpler if you don't need explicit credentials and can rely on the default credentials, in which case the following would be sufficient to enable BOTH microsoft graph
```yaml
catalog:
  providers:
    microsoftGraphOrg:
      myCompany:
        # ...
# No azure devops integration configuration needed as the default instance will use the default entra authentication method
```

### Azure Devops
Unifying on this methodology will introduce an edge case breaking change.
Currently if no credentials are provided, no authentication is used.
But with this change, I'm proposing that such requests would 
This would break two scenarios

1. Azure Devops Server (on premise version)
2. Azure Devops Services (hosted https://dev.azure.com/) with public repos

The first can be easily fixed - only azure `dev.azure.com` supports Entra authentication, so for all other hosts, we can continue to send no credentials.

The second case is trickier, but I beleive it to be an edge case.
Whilst I know this can be done in theory, I'm not sure I've ever seen any public ADO repos in the wild.
This is an edge case I'm happy to break to make the most common case work more seamlessly.
We can provide an `anonymousAuthentication` option to allow users to explicitly specify that they don't want to authenticate, effectively opting in to hte old behaviour.

```
integrations:
  azure:
    - host: dev.azure.com
      credentials:
        - anonymousAuthentication: true
```

### Techdocs Publisher

The azure blob storage publisher won't be able to fully unify on this concept - Techdocs CLI doesn't have YAML configuration, so will either need to provide it's own implementation of `EntraIdCredentialProvider` that gets the credentials from the command line arguments, or maintain it's own way of creating `TokenCredential`

### Microsoft Authentication Provider

Because the Microsoft Authentication provider is used for user authentication rather than server side authentication,  clientSecret is the only entra authentication method supported.

Whilst we could use the new unified configuration for this, and provide some kind of restriction around validatign it gets back a client secret credential type, I think it may be simpler to leave it for now using it's own configuration, rather than using the unified `EntraIdCredentialProvider`

### Postgress

There is an in progress pr (#18507) to add Entra ID auth to postgress.  Whislt this conflicts conceptually, I don't think it should conflict much from a code perspective.  

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
Thank you for starting this up! 👍  For sure something that would provide a lot of benefit.

Let's keep it close to #12844 and build on top of learnings from that in whatever way we can. The design we ended up with was merged in #14125. In particular we ended up with a bit of a double wrapping compared to our other credential provider APIs. There's an outer credential manager that you plugins would use to ask for credentials, while the inner credential manager is an AWS SDK thing that is able to provide live credentials, see https://github.com/clareliguori/backstage/blob/e4d8420996b53a08ae3d33bb3b837ce5693a7c4c/packages/integration-aws-node/api-report.md. It could be that we want something similar here.

I think the most important thing to figure out here is likely what a plugin build should use to ask for credentials. In the AWS case it was an account ID and/or ARN, which ofc doesn't apply here. Are there any similar identifiers that we could use for Azure to enable a bit more indirection in how credentials are acquired? I think the direct name mapping is likely a little bit too inflexible when it comes to supporting multiple project-type things, fallbacks, etc. It's likely the case that individual plugins need to indirectly browse through all credentials and select the best match.

**Comment by awanlin** [comment]
Thanks for this @afscrome! I just wanted to share some of my thoughts purely coming from someone who only uses Azure DevOps and has mostly experienced the Happy Path using Azure AD with auth and identity. My comments on this are not intended to be blockers but to better understand this part of the RFC. I'll roll with whatever this ends up as to be honest 👍 

How would you see this fitting with the `AzureDevOpsCredentialProvider` - details here https://github.com/backstage/backstage/pull/18213 - that was added about 3 months ago? I'm currently working on integrating it with the Azure DevOps plugin so it can support multi-orgs. Have you thought of a migration strategy? I can't pivot as this is a feature I have committed to. Though I would be fine migrating at a later date.

Regarding "A sensible Default", based on my work to support multi-orgs I'm not sure that would work. But I'll admit we are getting into a place where I have gaps in my understanding of how things work in Azure AD. If I own several Orgs in Azure DevOps and I use a service principle is it for sure going to be available in all Orgs? Even if that's possible if I own several Orgs I may have security reasons for not having them all together. I'd prefer no default, it fails with a helpful error that I need to setup something.

**Comment by awanlin** [comment]
@sanderaernouts would be great to hear your thoughts on this as well

**Comment by sanderaernouts** [comment]
Happy that you started this @afscrome, I currently have a config with several Azure credential configurations and I'd be happy to consolidate those in some way.

[`DefaultAzureCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) is a good default in my opinion. It is actually is a chain of `TokenCredential` implementation that are in a sensible order. It allows you to use your own credentials, from the [`AzureCliCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.azureclicredential?view=azure-dotnet) for example, locally whilst using a [`ManagedIdentity`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet) or a [`WorkloadIdentity`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.workloadidentitycredential?view=azure-dotnet) without any configuration changes.

The `TokenCredential` implementation often support providing configuration values or overriding defaults through environment variables like `AZURE_TENANT_ID` or `AZURE_CLIENT_ID`.

The same applies to the below:
> - When deployed to Azure Kubenetes Service, auto detect the workload identity configuration and use that

Auto detecting the workload identity configuration is a no-op if you go with [`DefaultAzureCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) (see the [docs](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet#azure-identity-client-libraries). The [`WorkloadIdentity`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.workloadidentitycredential?view=azure-dotnet) is the second in the chain and in it's default configuration it will take the values from the `AZURE_TENANT_ID`, `AZURE_CLIENT_ID` and `AZURE_FEDERATED_TOKEN_FILE` environment variables.  Those environment variables should be set on the pod by the workload identity feature.

For Azure DevOps it makes sense to only use a [`DefaultAzureCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) for `dev.azure.com`, this actually what the current integration for Azure (DevOps) does as well. Having some option to force no credentials like a `anonymousAuthentication: true` or a `none` would be good but I don't think it should be the default for `dev.azure.com` or any of the other Azure API's because those simply authentication and a [`DefaultAzureCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) could make that work out-of-the-box.

Regarding how to reference the credentials from the shared credential config, maybe the client ID would be sufficient to reference specific credentials? Though it is less readable than using a name for reference. 

You might still want to provide a way to specify a specific credential for a plugin without having to put it in the `integration.entra` config section. Maybe we should offer both a way to reference an existing credential and a way to specify a specific credential per config. The config types and code to handle that would still be shared. I'm talking about something like this:
```yaml
integrations:
  azure:
    - host: dev.azure.com
      credentials:
        - name: myCredentials
        - tenantId: TENANT_ID
          clientId:  CLIENT_ID
          clientSecret: CLIENT_SECRET
```

**Comment by afscrome** [comment]
Thanks for the feedback everyone.  Still a few details to iron out, the big one being how to link credentials from a consuming plugin (i.e. azure devops, microsoft graph), to the consolidated Entra configuration.

> Are there any similar identifiers that we could use for Azure to enable a bit more indirection in how credentials are acquired

Unfortunately I don't think there are - the unique identifiers vary by authentication method.  (e.g. for managed identities, the unique identifier is the azure resource id). The closes I could think of is Tenant Id as I would generally expect you to have a single set of credentials per tenant. However generally speaking the tenantId is derived from the credentials, not hte other way around, so using the tenantId as the key to lookup would typically mean adding tenantId in places that didn't need to know it before. In addition, whilst you shouldn't ever **need** more than one set of credentials per tenant.  (Although I can see politics and other reasons coming in to place resulting in multiple sets of credentials within a tenant, so I don't want to pick a configuration that forces just one set of credential per tenant).


> I think the direct name mapping is likely a little bit too inflexible when it comes to supporting multiple project-type things, fallbacks, etc. It's likely the case that individual plugins need to indirectly browse through all credentials and select the best match.

I'm not familiar with AWS's authentication model, so I'll need to do some reading up on this. Based on my Entra experience, the idea of having to browse through and pick credentials seems a bit alien. The Entra model is that your app (i.e. backstage) has a single principal representing it. This principal is then granted permissions to the various resources it needs access to. From your application's perspective, authentication is easy - your app has one set of credentials it uses everywhere. So my initial thoughts are that the need to browse through credentials and select one may not be as big a problem in Entra world as it is in AWS world.
That said, I will heavily caveat that statement by the fact I have only done a few minutes reading on AWS authentication, so it's quite possible I'm wrong.

Additionally, part of my goal with this design was to explicitly not allow plugins to know details about the credential type. One of the challenges faced today is that each plugin has to understand each different authentication method Entra ID supports. In practice, what that has meant is that each plugin has ended up supporting a different set of authentication methods. As well as making it challenging to add support for a new authentication method (as you have to go to every plugin individually). This is probably why each plugins supports a different mix of credentials - people (myself included) raise prs to add the auth methods they care about to the plugins they use, but not the other plugins.


> How would you see this fitting with the AzureDevOpsCredentialProvider

I haven't gotten to implementation, so there may be some some more nuance here, but ultimately I would expect `AzureDevOpsCredentialProvider` to be refactored to use `EntraIDCredentialService` under the hood for getting Entra credentials. If you are doing other work to build upon `AzureDevOpsCredentialProvider`, I would hope that most of this work can be done without you noticing a thing.  


> If I own several Orgs in Azure DevOps and I use a service principle is it for sure going to be available in all Orgs?

It depends whether your Azure Devops organisations are linked to the same tenant or not. If they're linked to the same tenant, then yes you can create a single principal that can be added to all the Azure Devops organisations linked to the same tenant. If they linked to different, then you will need most likely different credentials for each tenant. (I believe there are some ways to add a principal across multiple tenants, but they get complicated and are probably more trouble than maintaining separate sets of credentials)


> I'd prefer no default, it fails with a helpful error that I need to setup something.

Obviously implementation hasn't been done yet so this could be messed up, however if the default credentials were used, I'd expect each integration to fail the same way they would as if you provided bad credentials.  (i.e. a 401 or 403 error).  


> Auto detecting the workload identity configuration is a no-op if you go with DefaultAzureCredential

Yes, I'd expect this to work well in simple environments.  However I can see a multi-tenant scenario where you need multiple workload identities.
(both could use the same federated token, but each would use a different clientId / tenantId pair).
So I still think there is value in allowing explicit configuration of a Workload Identity


> Regarding how to reference the credentials from the shared credential config, maybe the client ID would be sufficient to reference specific credentials?

The challenge with that is not all authentication methods have a client id.  (e.g. a System Assigned Managed Identity, Azure CLI)

Selfishly, I have enough problems with mixing up the various GUIDs used by an app registration that I'd like to steer clear of anything that looks like a guid as a way of linking between plugins and the consolidated configuration.  (client id, object id, object id of the service principal backing the app registration).  If I got money every time I mixed up these guids, I'd be long retired!


> You might still want to provide a way to specify a specific credential for a plugin without having to put it in the integration.entra config section

Pragmatically, we're going to have to support this as we'll want backward compatibility with the way things were configured before this consolidation. So if you have a unique set of credentials you don't want shared elsewhere, you can just leave it however you've got it configured today. Where possible, I'd like to consolidate this to be based on some common/shared code, however backward compatibility quirks may mean we won't be able to re-use as much as I'd like.

**Comment by afscrome** [comment]
Been thinking about this some more and I think are ultimately two options for keying credentials
1. Name
2. TenantId

Name is the original proposal.  This maps very nicely into how plugins are configured today, with every existing configuration able to migrate to the new schema without needing to make permission changes in Azure.  It does however come with a catch - whilst this model works fine for the currently built in plugins (e.g. entity providers), it does cause problems if you want to say map back from a catalog item to an Azure resource - if there is more than one set of credentials, how do you know what to use?

When a credential is created in Azure (be it managed identity or app registration), it is created within a single Tenant, and it can then be granted permissions to access resources throughout the tenant.  (Even if a managed identity is created in a specific subscription, it can still granted permissions in other subscriptions or even tenant wide.).  Azure resources always exist within a tenant, so as long as we store/get the tenant id along with any other resource identifiers, we can always pick exactly one set of credentials to use.  (In most cases, a company has a single tenant, so making some of this selection process moot). 

So far, sounds like Tenant is the clear winner?  It would be if designing all of this stuff from scratch, however this will result in a breaking change to the current behaviour.  They key to allow plugins to get credentials for a resource in a standard manner requires that we allow only one set of credentials per tenant - this would be a breaking change to the the existing configuration.

Whilst there shouldn't ever be a need for more than one set of credentials per tenant, up until now the docs haven't really linked up, with most plugins documenting creating a new set of credentials (typically a new app registration) as part of the setup guide, rather than recommending re-use.  Thus I suspect it's more likely than not that any backstage user using multiple azure plugins has probably created multiple credentials within a tenant.  (I'll be clear, this is an assumption - I'd love to be proven wrong).  That said, anyone in such a setup could migrate to the single credentials per tenant by picking one set of credentials to use, then granting that account all the permissions granted individually to the other credentials.

This breaking change would only be required when migrating to the central entra configuration - as part of the refactor to use this service plugins would likely still support the existing credential definitions for a period of time.  Although it is likely that at some point those configurations would be deprecated forcing users to finally accept the breaking change.

The only risk I can think of is if my assertion that you only ever need one set of credentials per tenant is false.  The closes case I could think of is with managed identities being in a specific subscription, it may mean you need a high level administrator to assign some of the permissions for you as you may need someone with access to both the subscription containing backstage, and the resources you want to access.  That said, I'm not sure if that's a big problem as in general you'll probably want to grant backstage access at a management group or tenant level rather than individual subscriptions, and those will almost certainly require a high level administrator anyway.


So in summary, Name involves the least change of concepts, but does meant that plugins will all need to define their own logic to pick what credentials to use.   This in turn makes defining the fields that should go on the central configuration as we don't know what information plugins will need to use to pick what credentials to use.

TenantId on the other hand simplifies the authentication model - both from the backstage user's side so it's harder to fall into the pit of failure, but more importantly from the plugin author's side.  Plugin authors can then get a standard way of getting credentials to access resources.  In particular this opens up ways for plugins to get from a catalog item, to a set of credentials to use in a standard way - as long as the catalog has a `tenantId` attribute, the credentials can be chosen.

Originally I was strongly leaning towards Name as it's the least intrusive change.  However as I think about it more and more (and in particular think about the catalog linking example), I'm becoming more and more convinced that TenantId is the way to go.  Does anyone know of a scenario in which you would **need** more than one credential within a single tenant?

**Comment by freben** [comment]
On the Entra topic - this one seems to contain a lot of changes to Entra if one looks at the diff, could you check out if that upgrade seems non-breaking so we can get it in and get additional movement toward this? https://github.com/backstage/backstage/pull/21393

**Comment by sanderaernouts** [comment]
> Been thinking about this some more and I think are ultimately two options for keying credentials
> 
> 1. Name
> 2. TenantId

Maybe a sensible default is to resolve credential by `TenantId` and fallback to `DefaultAzureCredential`. We then provide an option to select a specific credential, by `name`, if you want to have multiple set's of credentials with a smaller scope. This way the default is almost zero-config but you can be more specific if you want to (or have to).

To request a token you'll always have to specify the tenant and the scope of the token, i.e. `AzureDevOps`, so `tenantId` can be a required parameter for the `EntraIDCredentialService`. I think this does require abstracting the `TokenCredential.GetToken` call away and expose the resulting `AccessToken` instead:
```typescript
import { AccessToken } from "@azure/core-auth";

export type GetAccessTokenOptions = {
  tentantId: string,
  scope: string[]
} | {
  name:string,
  scope: string[]
}

export interface EntraIDCredentialService {
    getAccessToken(opts:GetAccessTokenOptions ): Promise<AccessToken>
}
```

Azure DevOps ([dev.azure.com](https://dev.azure.com)) works with organizations and are (optionally) backed by an Entra ID tenant. So a mapping between organization and tenant is required in the `integrations.azure` config. Azure DevOps specific plugins can leverage the `AzureDevOpsCredentialsProvider` which deals with this mapping and in turn uses the `EntraIDCredentialService` to get the actual credentials in case of an Entra ID backed organization. It think this would only require a small change in the `DefaultAzureDevOpsCredentialsProvider` and `CachedAzureDevOpsCredentialsProvider` implementations to offload calling `TokenCredential.getToken(...)` to the `EntraIDCredentialService` instead.

Regarding caching:
> Credential Caching
> To ensure tokens are cached, the implementation should ensure that the `TokenCredential` objects created for each credentials are > reused, and not recreated on every call to `getCredentials`.

The `TokenCredential` objects themselves do not represent access tokens and do not require network calls, they are just a wrapper for a credential type to get an access token for the requested scopes. The resulting [`AccessToken`](https://learn.microsoft.com/en-us/javascript/api/@azure/identity/accesstoken?view=azure-node-latest) objects should be cached to prevent unnecessary network calls. Looks like there is a built-in, secure caching mechanism available we can leverage:
https://learn.microsoft.com/en-us/javascript/api/@azure/identity/tokencachepersistenceoptions?view=azure-node-latest

**Comment by sanderaernouts** [comment]
On second thought abstracting away `@azure/identity` is probably a mistake. Most of the Azure SDK libraries expect you to pass in a `TokenCredential` that the library will use to request tokens with the correct scope. So it makes more sense to stick to something like this:
```typescript
export type GetAccessTokenOptions = {
  tentantId: string
} | {
  name:string
}

export interface EntraIDCredentialService {
    getAccessToken(opts:GetAccessTokenOptions ): TokenCredential
}
```

**Comment by awanlin** [comment]
@afscrome do you have enough feedback here to move forward? Should this be closed in favor of a more detailed issue or should we continue to refine things?

CC @sanderaernouts

**Comment by afscrome** [comment]
I think we're in a good place with this.  I hope to have a go at working on this int he next few weeks, but I do have a few things going on right now so can't promise anything.  If someone else wants to push this forward feel free to do so - just post on this thread so we don't go duplicating effort.

**Comment by awanlin** [comment]
Thanks! I have no plans in this space so it's all yours 🚀

**Comment by jmezach** [comment]
Just wondering if someone is actively working on this. We rely heavily on Azure with our Backstage instance so could really benefit from this as well. I'm particularly interested in simplifying our local dev experience with Backstage, which currently requires our devs to create secrets and personal access tokens in various systems for things to work locally.

**Comment by afscrome** [comment]
@jmezach This is still on my wish list to do, although not an active priority.  That said this issue is more about unifying existing configuration rather than implementing new features

That said in terms of not needing secrets locally that should be possible today.  Most things fall back to `DefaultAzureCredentials`, so as long as you're logged in to the azure CLI locally, things should work.  At my company we do this for Microsoft Graph, Azure Devops, Techdocs storage account etc, and those can all be used straight away after cloning the repo for local dev.  The only exception I know of is authentication as to the best of my knowledge there's no way to do OIDC without an App Registration, however for this use the `guest` authentication method locally so that's not a problem.

**Comment by jmezach** [comment]
Interesting, because I can't seem to get it to work for Azure DevOps if I don't specify a personal access token in the config. Do I need to put anything into the config for that?

**Comment by sanderaernouts** [comment]
If you specify `dev.azure.com` without any credential it will default to the `DefaultAzureCredential` indeed. For Azure DevOps server it default to anonymous (or no) authentication IIRC.

**Comment by Sarabadu** [comment]
Just to bring a +1 here (thanks @awanlin for link it to me)

While working in some azure resources provider, and some scaffolder actions that also uses azure resource graph i was expecting something like this.

I tried things like:

```yaml
integrations:
  azure:
    - host: management.azure.com
      credentials:
        - name: myCredentials
        - tenantId: TENANT_ID
          clientId:  CLIENT_ID
          clientSecret: CLIENT_SECRET
```
but then saw azure integration is = azureDevOps

maybe we could have a default with DefaultCredentials and then be able to specify by scope host and plugins can get it ion that way too

```yaml
integrations:
  azure:
    defaultCredentials:
        - name: myCredentials
        - tenantId: TENANT_ID
          clientId:  CLIENT_ID
          clientSecret: CLIENT_SECRET
    - host: management.azure.com
      credentials:
        - name: myCredentials
        - tenantId: TENANT_ID
          clientId:  CLIENT_ID
          clientSecret: CLIENT_SECRET
```

```js
integrations.azure.byUrl(scopeUrl) // search per host -> defaultCredentials -> DefaultAzureCredential
```
