### ISSUE TITLE
🐛 Bug Report: gcp-projects plugin sets the projectName for the URI in the query parameters in the project details page

### ISSUE THREAD

**Issue by dimisjim** [backstage/backstage#21150]
### 📜 Description

Basically what the title describes. When clicking GCP or Logs buttons in the project details page, a query parameter of `project=<projectId>` is malformed to `projectName` instead, which leads to the buttons not working properly and then having to manually select the project in the the console gui

### 👍 Expected behavior

It should use `projectId` instead of `projectName` in the query parameter value

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/6890249/7d95d9fc-9846-4848-b0c0-d0f913ba087a)

### 👟 Reproduction steps

Use latest version of backstage and of the plugin, yarn v1, node 18.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes

**Comment by dimisjim** [comment]
I think problem lies in these 2 lines: 

1.https://github.com/backstage/backstage/blob/master/plugins/gcp-projects/src/components/ProjectDetailsPage/ProjectDetailsPage.tsx#L141
1. https://github.com/backstage/backstage/blob/master/plugins/gcp-projects/src/components/ProjectDetailsPage/ProjectDetailsPage.tsx#L130

should be `details.id` rather than `details.name`

**Comment by Rugvip** [comment]
Nice! Sounds like a reasonable fix 👍

**Comment by benjdlambert** [comment]
@dimisjim do you want to contribute this? :pray:

**Comment by dimisjim** [comment]
Sure, there you go: https://github.com/backstage/backstage/pull/21385

**Comment by dimisjim** [comment]
Hey @freben , @Rugvip , @benjdlambert 

I've added the new version in my project via: `yarn add @backstage/plugin-gcp-projects@0.3.43 -W` but still the URI is using the name of the project, not the projectId. Could you reproduce? No sure why it's still using the name field. Sorry typescript newb here.

**Comment by benjdlambert** [comment]
@dimisjim hey :wave: so this only got merged 2 days ago, so I think it's not hit the tuesday release cycle yet.

**Comment by dimisjim** [comment]
So it won't work if I separately only add the plugin's new version in my own project as it was with the yarn command in my previous comment?

**Comment by benjdlambert** [comment]
Nope, it's been merged, but it hasn't been released yet. The releases go out every Tuesday, so it will be in the release then.

I has been released in the nightly release however, so you could do `yarn add @backstage/plugin-gcp-projects@nightly` I think, but there could be some dragons using that release.

**Comment by dimisjim** [comment]
Cool, nightly works as expected! Thanks for the tip!
