### ISSUE TITLE
🚀 Feature: add acr_values for oidc provider

### ISSUE THREAD

**Issue by romph** [backstage/backstage#21172]
### 🔖 Feature description

Hi,
I'm opening this issue because i didn't find out how to configure acr_values for an oidc provider (from scratch)

### 🎤 Context

It's an optional value that can be used in the authentication request : https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

It's a must have when the provider offers several levels of authentication

### ✌️ Possible Implementation

Allowing to configure the acr_value to use in the configuration of the auth provider : https://backstage.io/docs/auth/oidc#the-configuration

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@romph do you want to contribute this? :pray:
