### ISSUE TITLE
🚀 Feature: Add support for re-using Gitlab SCM integration for cicd-statistics-module-gitlab

### ISSUE THREAD

**Issue by JonJam** [backstage/backstage#21173]
### 🔖 Feature description

The `cicd-statistics-module-gitlab` currently only supports authenticating to Gitlab via OAuth as per https://backstage.io/docs/auth/gitlab/provider.

Gitlab is also integrated via https://backstage.io/docs/integrations/gitlab/locations/ using an authentication token.

`cicd-statistics-module-gitlab` should support re-using the same authentication token form the previous.

### 🎤 Context

My Backstage implementation integrates with Gitlab via https://backstage.io/docs/integrations/gitlab/locations/ and uses a Microsoft Azure AD as the authentication mechanism .

Rather than supporting an additional mechanism, it would be nice to reuse the Gitlab integration.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by DavidRayner** [comment]
I would like this too, however I think the issue should be moved to https://github.com/backstage/community-plugins
