### ISSUE TITLE
🚀 Feature: Forwarding user reference in service to service communication

### ISSUE THREAD

**Issue by RobertSimonDB** [backstage/backstage#21195]
### 🔖 Feature description

Forwarding user reference in service to service communication.

### 🎤 Context

We need access to user stored settings on service to service level on behalf of the user.
For example using user settings for personalized background scheduled data imports.
Or any other service to service call where you want to forward also user entity ref.

### ✌️ Possible Implementation

Are there any specific best practices regarding running something on behalf of the user with [service2service](https://backstage.io/docs/auth/service-to-service-auth/) token?
For example which header to use? 
I just skimmed the repo and was not able to identify similar occurrence.
So for now just changing (in user-settings-backend)

```
  /**
   * Helper method to extract the userEntityRef from the request.
   */
  const getUserEntityRef = async (req: Request): Promise<string> => {
    // throws an AuthenticationError in case the token exists but is invalid
    const identity = await options.identity.getIdentity({ request: req });
    if (!identity) {
      throw new AuthenticationError(`Missing token in 'authorization' header`);
    }

    return identity.identity.userEntityRef;
  };
```

to something like this
```
  /**
   * Helper method to extract the userEntityRef from the request.
   */
  const getUserEntityRef = async (req: Request): Promise<string> => {
    // throws an AuthenticationError in case the token exists but is invalid
    const identity = await options.identity.getIdentity({ request: req });
    if (!identity) {
      const token = getBearerTokenFromAuthorizationHeader(
        req.headers.authorization,
      );

      if (!token) {
        throw new AuthenticationError(
          `Missing token in 'authorization' header`,
        );
      }
      // check if token is valid service to service token
      const validToken = await options.tokenManager
        .authenticate(token.toString())
        .then(
          () => true,
          () => false,
        );

      if (!validToken) {
        throw new AuthenticationError(
          `Invalid token in 'authorization' header`,
        );
      }
      return req.header('user-entity-ref');
    }
```

I am mainly looking for confirmation or help how/where would be best to place the header constant or if name is good. So it could be made an example for other plugins for "on behalf of user" functionality.
For me it would make sense to export it from `@backend/common` as there is TokenManager type and ServerTokenManager located. 
`export const USER_ENTITY_REF_HEADER_KEY = 'user-entity-ref';`

Or should we instead use some minimal construct inspired by SignInResolver to generate user token in our backend plugin and call the API with user token?

I can prepare PR with tests and updated documentation if this is approved.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Thank you for the suggestion! 👍

This is planned as part of the work tracked in #15999, I've added a separate item there now too and linked to this issue.

I'm a bit hesitant to move this work forward before we pick up that part of #15999 though tbh. It's pretty intertwined the token manager and changes that we would make to it. For example one refactor that could be useful now is to have the token manager take the entire `req` rather than just the token, allowing us to extract a header like that too. That's a high impact change though and we'd want to sync that up with any other changes we want to make as part of #15999 at the same time, so in the end I think it's best to let this one sit for a bit. Curious about any suggestions or use-cases here though to help drive design.
