### ISSUE TITLE
🚀 Feature: Plugin aware global support modal

### ISSUE THREAD

**Issue by alper98** [backstage/backstage#21191]
### 🔖 Feature description

A floating action button, located at the bottom right, serves as a universal support button. When on a plugin page, this button displays support links specific to that plugin. If not on a plugin page, the links provided will come from the useSupportConfig hook.

### 🎤 Context

Here at my org, our adoption of Backstage continues to grow, our core team is receiving an increasing number of support inquiries. Many of these questions are not related to the core setup but are associated with plugins developed by internal plugin teams. To enhance user support and streamline the process, we propose the implementation of a global support button that is context-aware and recognizes the current plugin being used. This button will display relevant support links for users to access assistance efficiently.

### ✌️ Possible Implementation

While not quite sure, i could imagine the following setup, just like we're setting up the analytics context for each plugin, we could enable the support button as welll
```
      <Suspense fallback={<Progress />}>
            <PluginErrorBoundary app={app} plugin={plugin}>
              <AnalyticsContext
                attributes={{
                  pluginId: plugin.getId(),
                  ...(name && { extension: name }),
                  ...(mountPoint && { routeRef: mountPoint.id }),
                }}
              >
                <SupportModal
                  pluginId: plugin.getId(),
                  open={open}
                  setOpen={setOpen}
                />
                <Fab
                  color="primary"
                  onClick={() => setOpen(prev => !prev)}
                >
                  ?
                </Fab>
                <Component {...props} />
              </AnalyticsContext>
            </PluginErrorBoundary>
          </Suspense>
```
the links would then come from `createPlugin` with an optional prop of links

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Totally want something like this too! A floating one is nice for pages but it gets a bit tricker when you consider pages with multiple plugins like the entity pages overview tab. I've been thinking that we should have a global support menu item in the sidebar that allows you to select any plugin element on the page to show info and support contacts. Our existing plugin boundary component would help out creating the targets to highlight and select as part of that. What do you think?

**Comment by Rugvip** [comment]
@alper98 Ah yep could definitely make the same feature available via other controls as well. Keyboard shortcut, floating button, rage shake 😁

**Comment by alper98** [comment]
I'd love to start the work on this. But not sure i have the time. If others would like to chip in, feel free :)

**Comment by alper98** [comment]
> Our existing plugin boundary component would help out creating the targets to highlight and select as part of that.

Could you point me in a direction for this? I want to start the work on this :)

**Comment by jamieklassen** [comment]
Wow this reminds me of @remerle's [talk](https://www.youtube.com/watch?v=PbI0-ucrgSo&t=1222s) (timestamped link) at BackstageCon

**Comment by Rugvip** [comment]
@alper98 best place to experiment right now would be to try making this part of the existing system where we wrap extension components: https://github.com/backstage/backstage/blob/bf65f1c80f6aa96ed3f2e3e73deb087a501bb254/packages/core-plugin-api/src/extensions/extensions.tsx#L260

The bar for adding anything there is pretty high though, so best consider this an experiment to help figure out the direction rather than something that we could ship immediately.

**Comment by alper98** [comment]
> @alper98 best place to experiment right now would be to try making this part of the existing system where we wrap extension components:
> 
> https://github.com/backstage/backstage/blob/bf65f1c80f6aa96ed3f2e3e73deb087a501bb254/packages/core-plugin-api/src/extensions/extensions.tsx#L260
> 
> The bar for adding anything there is pretty high though, so best consider this an experiment to help figure out the direction rather than something that we could ship immediately.

Sounds good! Ill try some stuff and make an experimentation PR for further discussion

**Comment by dweber019** [comment]
We had similar requirements. Our users aren't used to terms introduced by Backstage or need some more context information for a page.
For this I created a plugin https://github.com/dweber019/backstage-plugin-tips/tree/main/plugins/tips

**Comment by alper98** [comment]
Sorry, have had zero time to have a look at this. If anyone wants to help, or take over. Please feel free. This will be an awesome feature, if it could be done correctly

**Comment by waqasali47** [comment]
It would be great to have something like this. We have made a custom solution for this.
