### ISSUE TITLE
🚀 Feature: Postgres Version Policy

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#21234]
### 🔖 Feature description

Currently there are nicely defined version policies for Node and TypeScript here: https://backstage.io/docs/overview/versioning-policy#nodejs-releases. It would be great to have the same for what version of Postgres are supported

### 🎤 Context

It's currently unclear what versions of Postgres are supported as it's not documented anywhere.

### ✌️ Possible Implementation

Add a section for Postgres below this section in the docs: https://backstage.io/docs/overview/versioning-policy#typescript-releases

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Just a couple of notes:

- Search docs mention the need of Postgres 12: https://backstage.io/docs/features/search/search-engines#postgres
- The E2E tests seem to be running off of a `postgres:latest` docker image: https://github.com/backstage/backstage/blob/master/.github/workflows/verify_e2e-linux.yml#L21

**Comment by awanlin** [comment]
It doesn't look like there's an LTS policy for Postgres, here's there Versioning Policy: https://www.postgresql.org/support/versioning/

**Comment by awanlin** [comment]
@freben, when you have some time could you share your thoughts on this, please? Once I know what we want to do I can update the docs with the details 👍

**Comment by Rugvip** [comment]
Thank you @awanlin, good initiative! 👍

Discussed this during sync and we figured it makes sense to mirror the PostgreSQL window. For simplicity I think it's best to simply say that we support the last 5 major versions. There seems to be a small window on every major release where there are 6 supported major versions in total but the last one of those is dropped pretty soon after.

In additional I think we could also make it part of the policy that we test towards the newest and oldest of those versions, so currently we would support any versions in the 12-16 range, but we only test towards 12 and 16.

**Comment by awanlin** [comment]
This is great @Rugvip, I'll think on this for a bit on how to structure and words this. Probably have a PR in a week or so 🚀

**Comment by freben** [comment]
For reference [here](https://github.com/backstage/backstage/blob/3269d67b3a63778837f8d8b509ae3a9f9eccbd5f/packages/backend-test-utils/src/database/types.ts#L48) is the list of databases tested against; it'll be nice to cut that down a bit and have a proper structure to how it moves along.

**Comment by awanlin** [comment]
Took a bit longer than expected to get at this but submitted #21510 for this 👍

**Comment by awanlin** [comment]
Thanks @Rugvip and @freben 🚀
