### ISSUE TITLE
🚀 Feature: Support entity filter in HomePageTopVisited and HomePageRecentlyVisited

### ISSUE THREAD

**Issue by shmaram** [backstage/backstage#21243]
### 🔖 Feature description

Allow the ability to filter out entities from the list, for example, showing only entities that are Kind=component and Type=Service

### 🎤 Context

Currently in both HomePageTopVisited and HomePageRecentlyVisited we see "other" entities, those entities are usually "catalog" page or the root route, we would like to avoid showing these pages 

![image](https://github.com/backstage/backstage/assets/12017112/344b5efe-a545-4d39-a431-5916a438dfd1)

### ✌️ Possible Implementation

adding a new prop for filtering entities, the prop should be of type "function" and should return type"bool" 
for example: 
`filter: (entity) => entity?.spec?.type === 'service'`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tikabom** [comment]
Hi @shmaram! Could you share some background around if you're using the reference PageVisits implementation provided in the home plugin (that uses LocalStorage under the hood) in your Backstage or have a custom implementation in place?

**Comment by shmaram** [comment]
@tikabom 
We are using the same implementation that was provided [here](https://github.com/backstage/backstage/tree/master/plugins/home#page-visit-homepage-component-homepagetopvisited--homepagerecentlyvisited) 
The problem is that we added both plugins to the same page as the catalog, so that our home is the catalog and above it we have both plugins, this way every time we go to our "home" route it is registered as a visit so we will always see "catalog" entity in the "recent" page on the top

Let me know if this clears the issue

**Comment by tikabom** [comment]
I am more looking into identifying if you have a have a custom VisitsStorageApi implemented for your Backstage instance or if you're using the example VisitsWebStorageApi that uses LocalStorage under the hood.

Our suggested path of action is to extend [VisitsApi](https://github.com/backstage/backstage/blob/master/plugins/home/src/api/VisitsApi.ts) and implement the `list` and `save` methods based on your needs which in this case would be to ignore the home route in `save` or in `list` to handle existing home routes saved in your preferred data store.

Alternatively, the `list` method accepts parameters of type [VisitsApiQueryParams](https://github.com/backstage/backstage/blob/4378dba2b331958f7a4614e9b4c85493ee6e01e4/plugins/home/src/api/VisitsApi.ts#L54) that contains a `filterBy` attribute. You can contribute back to the home plugin by providing a way to pass `filterBy` values through the `RecentlyVisited` and `TopVisited` components in the home plugin [here](https://github.com/backstage/backstage/tree/master/plugins/home/src/homePageComponents/VisitedByType).
Support for `filterBy` would need to be added [here](https://github.com/backstage/backstage/blob/master/plugins/home/src/homePageComponents/VisitedByType/Content.tsx) where the `limit` and `orderBy` parameters are set depending on if recent or top visits must be rendered.
Use documentation provided [here](https://backstage.io/docs/conf/reading/#accessing-configapi-in-frontend-plugins) to create a config file for the home plugin in which you can pass filtering options for the HomePageTopVisited and HomePageRecentlyVisited cards. 

Let me know your preferred course of action:

1. Filtering unwanted routes/pages in the `list` and `save` methods of your custom `VisitsApi` implementation
2. Adding a configuration to the home plugin to accept filtering options for the HomePageTopVisited and HomePageRecentlyVisited cards.

I will be happy to provide further guidance depending on the solution you pick.

**Comment by shmaram** [comment]
@tikabom , I would go with the first suggested option, can you help me with guidance on it?

**Comment by shmaram** [comment]
@tikabom - Can you change the assignee to me?

**Comment by camilaibs** [comment]
Assigned to you @shmaram 🙌🏻

**Comment by shmaram** [comment]
@tikabom 
I'm thinking of adding an optional `filterBy` into VisitedByTypeProps.
WDYT?
