### ISSUE TITLE
🌐 Feature: Establish i18n naming patterns

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#21267]
As we expand support for i18n in plugins it's important that we do so with a thought through and well established naming and usage patterns for translation keys. In the end these keys end up being public API that we want to avoid changing too often. Duplicate usage of keys of course makes it impossible to configure them separately, but it can also make it simpler to manage and populate keys.

Before we start migrating plugins to use i18n we want to establish some initial set of rules. These rules can change over time, but we want to have something in place initially. There is also a discussion to be had about stability of message keys wrt versioning policy, but it's not as urgent as it's all still in alpha.

**Before** we merge any more i18n migrations these rules need to be documented at https://backstage.io/docs/plugins/internationalization/.

An additional complication here is that we've started using `snake_case` keys, which we need to change. Underscores are used to denote [pluralization patterns](https://www.i18next.com/translation-function/plurals) in i18next, while keys are `camelCase`. I believe we want to move to using dot-separated keys instead, and supporting keys defined as nested objects while at it, but open to suggestions.

**Comment by Rugvip** [comment]
Opened #21541 to address the underscore issue, as well as add support for nested keys for better grouping. See for example https://github.com/backstage/backstage/pull/21541/files#diff-cff1b5489607cdaf0de41baa20759f64568e4ee90578a1105bf9708197b6f3ef

What's left to do on top of this is some more detailed documentation on design guidelines for the message keys and structure.

**Comment by camilaibs** [comment]
Hi @Rugvip 👋🏻 , is this the issue you have a list of pull requests to link to?

**Comment by Rugvip** [comment]
@gashcrumb we've avoided using text keys as since the keys end up being an API that we want to keep reasonably stable. If the message is the same as the key it ends up meaning that over time we either end up in the awkward situation that a lot of them don't actually match the message, or we have to make a lot of breaking changes. There's also the added benefit (imo) that there's less of a risk of re-use of keys that in practice shouldn't be shared.

The nested keys in #21541 are unrelated to interpolation in i18next, they're just a way to group message definitions, it doesn't mean you need to use interpolation. +1 to the concern about interpolation being troublesome though, it's something I think we're gonna end up needing to figure out how to tackle somehow though since we have a fair number of user defined enums displayed to end users.

**Comment by gashcrumb** [comment]
> If the message is the same as the key it ends up meaning that over time we either end up in the awkward situation that a lot of them don't actually match the message, or we have to make a lot of breaking changes.

Yes, these would need to be kept in sync, so if these strings aren't finalized for components it'd be breaking changes.

Would this key structure help with making tooling easier, for example CLI tooling for adding a component to a plugin?

**Comment by Rugvip** [comment]
Fixed by #21801
