### ISSUE TITLE
🚀 Feature: Enable addition of permission rules for Catalog plugin in the new backend system

### ISSUE THREAD

**Issue by lshwayne96** [backstage/backstage#21271]
### 🔖 Feature description

In the legacy backend system, we could call `builder.addPermissionRules(...)` on the catalog builder directly to add permission rules for the Catalog plugin. 

However, in the new backend system, the `CatalogProcessingExtensionPoint` interface/implementation does not seem to support this: 
https://github.com/backstage/backstage/blob/master/plugins/catalog-node/src/extensions.ts
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/CatalogPlugin.ts

Proposal: Enable addition of permission rules for Catalog plugin in the new backend system.

### 🎤 Context

To enable permissions for Catalog plugin.

### ✌️ Possible Implementation

- Add a new function `addPermissionRules` to the `CatalogProcessingExtensionPoint` interface/implementation.
https://github.com/backstage/backstage/blob/master/plugins/catalog-node/src/extensions.ts#L27
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/CatalogPlugin.ts#L35
- Call `builder.addPermissionRules(...)` when creating the Catalog plugin.
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/CatalogPlugin.ts#L93

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by RobertSimonDB** [comment]
Why would you even need permission rules to be added to plugin itself?
It is not like you need to apply them to router to be permission aware as there is no router.
Why not just use them directly from your module?

**Comment by lshwayne96** [comment]
@RobertSimonDB Could you elaborate further? The docs suggest that custom permission rules need to be added to the catalog builder before they can be used in a policy: https://backstage.io/docs/permissions/custom-rules

**Comment by vinzscam** [comment]
> Why would you even need permission rules to be added to plugin itself? It is not like you need to apply them to router to be permission aware as there is no router. Why not just use them directly from your module?

yeah as @lshwayne96 mentioned there is a possibility to provide custom permission rules to the catalog in case the default rules are not enough for you, but the functionality is currently missing in the new backend system.
So glad that is coming in #21275 🤩
