### ISSUE TITLE
🐛 Bug Report: Error when importing same plugin twice.

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#21283]
### 📜 Description

In migrating to the new backend system, I accidently imported the same plugin twice.  This failed with the error `ExtensionPoint with ID 'catalog.microsoftGraphOrgEntityProvider.transforms' is already registered`, however I'd have expected it to fail before it gets to extension points with an error more like `Module 'microsoftGraphOrgEntityProvider' is already registered on the 'catalog' plugin`

### 👍 Expected behavior

An error that more clearly indicates that the `microsoftGraphOrgEntityProvider` module has been imported twice

### 👎 Actual Behavior with Screenshots

```
[1] /home/alex/src/PlatformEngineering.Backstage/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1687
[1]             throw new Error(
[1]                   ^
[1] 
[1] 
[1] Error: ExtensionPoint with ID 'catalog.microsoftGraphOrgEntityProvider.transforms' is already registered
[1]     at BackendInitializer.doStart_fn (/home/alex/src/PlatformEngineering.Backstage/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1687:19)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at BackendInitializer.start (/home/alex/src/PlatformEngineering.Backstage/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1583:5)
[1]     at BackstageBackend.start (/home/alex/src/PlatformEngineering.Backstage/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1853:5)
```

### 👟 Reproduction steps

```
backend.add(import('@backstage/plugin-catalog-backend-module-msgraph/alpha'));
backend.add(import('@backstage/plugin-catalog-backend-module-msgraph/alpha'));
```

### 🖥️ Your Environment

OS:   Linux 5.15.90.1-microsoft-standard-WSL2 - linux/x64
node: v18.15.0
yarn: 1.22.19
cli:  0.23.1 (installed)
backstage:  1.19.6

Dependencies:
  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.5.7
  @backstage/backend-common                                        0.19.8
  @backstage/backend-defaults                                      0.2.6
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.6.6
  @backstage/backend-tasks                                         0.5.11
  @backstage/catalog-client                                        1.4.5
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5
  @backstage/cli                                                   0.23.1
  @backstage/config-loader                                         1.5.2
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.13.7
  @backstage/core-plugin-api                                       1.7.0
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7
  @backstage/integration-react                                     1.1.20
  @backstage/integration                                           1.7.1
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.0
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.4
  @backstage/plugin-auth-node                                      0.4.0
  @backstage/plugin-azure-devops-backend                           0.4.3
  @backstage/plugin-azure-devops-common                            0.3.1
  @backstage/plugin-azure-devops                                   0.3.7
  @backstage/plugin-catalog-backend-module-azure                   0.1.25
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.13
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-node                                   1.4.7
  @backstage/plugin-catalog-react                                  1.8.5
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-entity-validation                              0.1.10
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-github-actions                                 0.6.6
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-home-react                                     0.1.4
  @backstage/plugin-home                                           0.5.9
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-permission-common                              0.7.9
  @backstage/plugin-permission-node                                0.7.17
  @backstage/plugin-permission-react                               0.4.16
  @backstage/plugin-proxy-backend                                  0.4.4
  @backstage/plugin-scaffolder-backend                             1.18.1
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.7
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-tech-radar                                     0.6.9
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.1
  @backstage/plugin-techdocs-node                                  1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.6
Done in 0.45s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Ah yep would make sense if we can make the handling of that case a bit cleaner. The issue is that we're checking for that specific conflict before the module/plugin ID conflict: https://github.com/backstage/backstage/blob/cb7fc410ed99055977d986f5ef11f20627a0e662/packages/backend-app-api/src/wiring/BackendInitializer.ts#L190
