### ISSUE TITLE
🚀 Feature: Migrate create-app to the new backend system

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#21288]
### 🔖 Feature description

As part of moving to the new backend system we want to migrate the [template in @backstage/create-app](https://github.com/backstage/backstage/tree/master/packages/create-app/templates/default-app/packages/backend) to use the new backend system.

### 🎤 Context

Part of #11611, #18301

### ✌️ Possible Implementation

We'll want to move over `packages/backend/src/index.ts` to use the new system and cleanup the other files.

One decision that needs to be made as part of this is what to do with the auth backend, most likely we migrate it and show example usage of one of the modules, but in the end we need to update the [backend migration docs](https://backstage.io/docs/backend-system/building-backends/migrating#cleaning-up-the-plugins-folder) to mention more patterns for how to create custom resolvers or even fall back to the legacy helper to support modules that haven't been migrated yet.

Tangentially related are the templates for `backstage-cli new` as well, which could be updated as part of this effort or separately. When updating those templates it's likely best to keep compatiblity with both systems simply through how we structure the code, i.e. keep the pattern of a `createRouter` function that we still export for use in the old system.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
@minkimcello is this something that you were going to pick up? :pray:

**Comment by benjdlambert** [comment]
Nice! I've assigned you to it, godspeed! :tada:

**Comment by Rugvip** [comment]
@minkimcello yep indeed, you'd need to stick to the old version of the plugin for now in that case

**Comment by awanlin** [comment]
@Rugvip @freben can we close this now?

**Comment by camilaibs** [comment]
> @Rugvip @freben can we close this now?

Closing this for now 🙂
