### ISSUE TITLE
🐛 Bug Report: ScaffolderPage does not follow headerOptions after 1.20 update

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#21313]
### 📜 Description

Passing headerOptions to <ScaffolderPage> does not work anymore after 1.20 update.

### 👍 Expected behavior

Page title, title and subtitle should be what set in the headerOptions

### 👎 Actual Behavior with Screenshots

Defaults are always visible from https://github.com/backstage/backstage/blob/ca4063dd2704eebc630d946bf94cb435e7efd742/plugins/scaffolder/src/next/TemplateListPage/TemplateListPage.tsx#L156

### 👟 Reproduction steps

Add headerOptions for the ScaffolderPage

### 🖥️ Your Environment

OS:   Darwin 23.1.0 - darwin/arm64
node: v18.15.0
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.20.1

Dependencies:
  @backstage/app-defaults                                            1.4.5
  @backstage/backend-app-api                                         0.5.8
  @backstage/backend-common                                          0.17.0, 0.19.9
  @backstage/backend-dev-utils                                       0.1.2
  @backstage/backend-openapi-utils                                   0.1.0
  @backstage/backend-plugin-api                                      0.6.7
  @backstage/backend-tasks                                           0.5.12
  @backstage/backend-test-utils                                      0.2.8
  @backstage/catalog-client                                          1.4.6
  @backstage/catalog-model                                           1.4.3
  @backstage/cli-common                                              0.1.13
  @backstage/cli-node                                                0.2.0
  @backstage/cli                                                     0.24.0
  @backstage/config-loader                                           1.5.3
  @backstage/config                                                  1.1.1
  @backstage/core-app-api                                            1.11.1
  @backstage/core-components                                         0.12.5, 0.13.8
  @backstage/core-plugin-api                                         1.8.0
  @backstage/dev-utils                                               1.0.23
  @backstage/errors                                                  1.2.3
  @backstage/eslint-plugin                                           0.1.3
  @backstage/frontend-plugin-api                                     0.3.0
  @backstage/integration-aws-node                                    0.1.8
  @backstage/integration-react                                       1.1.21
  @backstage/integration                                             1.7.2
  @backstage/plugin-api-docs                                         0.10.0
  @backstage/plugin-app-backend                                      0.3.55
  @backstage/plugin-app-node                                         0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider             0.2.1
  @backstage/plugin-auth-backend-module-github-provider              0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider              0.1.4
  @backstage/plugin-auth-backend-module-google-provider              0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider              0.1.4
  @backstage/plugin-auth-backend                                     0.20.0
  @backstage/plugin-auth-node                                        0.2.19, 0.4.1
  @backstage/plugin-catalog-backend-module-aws                       0.3.1
  @backstage/plugin-catalog-backend-module-msgraph                   0.5.14
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model   0.1.4
  @backstage/plugin-catalog-backend-module-unprocessed               0.3.4
  @backstage/plugin-catalog-backend                                  1.15.0
  @backstage/plugin-catalog-common                                   1.0.18
  @backstage/plugin-catalog-graph                                    0.3.0
  @backstage/plugin-catalog-node                                     1.5.0
  @backstage/plugin-catalog-react                                    1.9.0
  @backstage/plugin-catalog-unprocessed-entities                     0.1.5
  @backstage/plugin-catalog                                          1.15.0
  @backstage/plugin-devtools-backend                                 0.2.4
  @backstage/plugin-devtools-common                                  0.1.6
  @backstage/plugin-devtools                                         0.1.6
  @backstage/plugin-entity-feedback-backend                          0.2.4
  @backstage/plugin-entity-feedback-common                           0.1.3
  @backstage/plugin-entity-feedback                                  0.2.9
  @backstage/plugin-events-node                                      0.2.16
  @backstage/plugin-github-actions                                   0.6.7
  @backstage/plugin-home-react                                       0.1.5
  @backstage/plugin-home                                             0.5.10
  @backstage/plugin-jenkins-backend                                  0.3.1
  @backstage/plugin-jenkins-common                                   0.1.21
  @backstage/plugin-jenkins                                          0.9.1
  @backstage/plugin-kubernetes-common                                0.7.1
  @backstage/plugin-org                                              0.6.16
  @backstage/plugin-permission-backend                               0.5.30
  @backstage/plugin-permission-common                                0.7.10
  @backstage/plugin-permission-node                                  0.7.18
  @backstage/plugin-permission-react                                 0.4.17
  @backstage/plugin-proxy-backend                                    0.4.5
  @backstage/plugin-scaffolder-backend-module-confluence-to-markdown 0.2.8
  @backstage/plugin-scaffolder-backend-module-cookiecutter           0.2.31
  @backstage/plugin-scaffolder-backend                               1.19.0
  @backstage/plugin-scaffolder-common                                1.4.3
  @backstage/plugin-scaffolder-node                                  0.2.8
  @backstage/plugin-scaffolder-react                                 1.6.0
  @backstage/plugin-scaffolder                                       1.16.0
  @backstage/plugin-search-backend-module-catalog                    0.1.11
  @backstage/plugin-search-backend-module-elasticsearch              1.3.10
  @backstage/plugin-search-backend-module-techdocs                   0.1.11
  @backstage/plugin-search-backend-node                              1.2.11
  @backstage/plugin-search-backend                                   1.4.7
  @backstage/plugin-search-common                                    1.2.8
  @backstage/plugin-search-react                                     1.7.3
  @backstage/plugin-search                                           1.4.2
  @backstage/plugin-sonarqube-backend                                0.2.9
  @backstage/plugin-sonarqube-react                                  0.1.10
  @backstage/plugin-sonarqube                                        0.7.8
  @backstage/plugin-techdocs-backend                                 1.9.0
  @backstage/plugin-techdocs-node                                    1.10.0
  @backstage/plugin-techdocs-react                                   1.1.13
  @backstage/plugin-techdocs                                         1.9.0
  @backstage/plugin-user-settings                                    0.7.12
  @backstage/release-manifests                                       0.0.11
  @backstage/test-utils                                              1.4.5
  @backstage/theme                                                   0.2.19, 0.4.4
  @backstage/types                                                   1.1.1
  @backstage/version-bridge                                          1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by kuangp** [comment]
I also want to note that as a related issue the theme changed from `home` to `website`: https://github.com/backstage/backstage/blob/ca4063dd2704eebc630d946bf94cb435e7efd742/plugins/scaffolder/src/legacy/TemplatePage/TemplatePage.tsx#L147
https://github.com/backstage/backstage/blob/ca4063dd2704eebc630d946bf94cb435e7efd742/plugins/scaffolder/src/next/TemplateListPage/TemplateListPage.tsx#L154

**Comment by drodil** [comment]
Works now with 1.20.3 on the ScaffolderPage but when choosing some template, the default header is still used here: https://github.com/backstage/backstage/blob/b5ae2e5a62d61f188e1f7b6ac4aeabb8429c6f89/plugins/scaffolder/src/next/TemplateWizardPage/TemplateWizardPage.tsx#L87

 So this does not work like it used to. I suggest re-opening @benjdlambert ?

**Comment by benjdlambert** [comment]
@drodil isn't this exactly the same behaviour? https://github.com/backstage/backstage/blob/b5ae2e5a62d61f188e1f7b6ac4aeabb8429c6f89/plugins/scaffolder/src/legacy/TemplatePage/TemplatePage.tsx#L149-L151

**Comment by drodil** [comment]
Yes but previously the header options were passed also to the single template page, not only to index page.
