### ISSUE TITLE
🐛 Bug Report: 'Owned by a user' filter in catalog is broken in v1.20

### ISSUE THREAD

**Issue by gusevda** [backstage/backstage#21339]
### 📜 Description

After updating backstage packages to v1.20 `owned by a user` filter in catalog stoped working. I tested version 1.19.6 and everything works as expected.

### 👍 Expected behavior

When you go to the catalog, preselected user filter should be the one provided [here](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogPage/DefaultCatalogPage.tsx#L101).

### 👎 Actual Behavior with Screenshots

When you go to the catalog you see all the components, not owned by a user.

The bug is present only for `Owned` filter, `Starred` filter works as expected.

### 👟 Reproduction steps

**Scenario 1:**
1. Start backstage locally.
2. Go to `http://localhost:3000/catalog`
3. You are being redirected to `http://localhost:3000/catalog?filters[kind]=component&filters[user]=all`

`filters[user]` is expected to be `owned` since it's [default value](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogPage/DefaultCatalogPage.tsx#L101).

**Scenario 2:**
1. Start backstage locally
2. Go to `http://localhost:3000/catalog?filters[kind]=component&filters[user]=owned`
3. You are being redirected to `http://localhost:3000/catalog?filters[kind]=component&filters[user]=all`

Redirect is not expected in this case.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by fedy97** [comment]
the problem is on `loading` that returns false even if entities are not still fetched. That triggers the `useEffect` at line 190
```
useEffect(() => {
    if (
      !loading &&
      !!selectedUserFilter &&
      selectedUserFilter !== 'all' &&
      filterCounts[selectedUserFilter] === 0
    ) {
      setSelectedUserFilter('all');
    }
  }, [loading, filterCounts, selectedUserFilter, setSelectedUserFilter]);
```

**Comment by vinzscam** [comment]
thanks for reporting and debugging this @fedy97 🙏
Fix is coming
