### ISSUE TITLE
🐛 Bug Report: Transitive group ownership not recognized

### ISSUE THREAD

**Issue by fstoerkle** [backstage/backstage#21347]
### 📜 Description

We are ingesting our users and groups from Azure EntraID (former ActiveDirectory) via the [`catalog-backend-module-msgraph`](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/README.md) plugin. This works fine. Groups and users are ingested, and visible in the catalog.

**Org structure**

Now, we have two levels of groups, small visualization to make it easier to talk about it:
```
            Group A
         /    |     \
  Group 1  Group 2  Group 3
  /  |   \
 u1  u2  u3
```

User `u1` is member of `Group 1` which in turn is member of `Group A`.
User `u1` is not a direct member of `Group A`.
(We have no control over how users and groups are related to each other, i.e. we can't rearrange these relationships in Azure EntraID, but have to use them as-is.)

Our goal is to include `Group A` in the ownership entities of `u1` (we need that for our permission system implementation), so we need to check not only for immediate but also transitive group ownership.

Looking at the source code of the `catalog-backend-module-msgraph` plugin, there is actually code to support this:
[`buildMemberOf` in `./src/microsoftGraph/org.ts`](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/src/microsoftGraph/org.ts#L57)

However, it has not the effect one would expect.

### 👍 Expected behavior

The above mentioned function should return all groups a user is member of, both taking direct and indirect/transitive memberships into account.

In the above example, for User `u1`, this would result in the user's `memberOf` property to contain `['group:default/group-1', 'group:default/group-A']`. 

### 👎 Actual Behavior with Screenshots

The above mentioned function does **only** return all groups a user is direct member of, but not taking indirect/transitive memberships into account.

In the above example, for User `u1`, this results in the user's `memberOf` property to contain only `['group:default/group-1']`. 

I debugged `buildMemberOf` a bit, and found a potential cause and fix for this behavior:

The lookup table `const groupsByName = new Map(groups.map(g => [g.metadata.name, g]));` takes the groups name (`g.metadata.name`) as key, which is in the format of `group-name`. However, in the iteration further below, the lookup (`const group = groupsByName.get(current);`) uses `current` as lookup key, which also comes from (another set of groups') metadata name, but in the format of `group:default/group-name`. Since the keys are different, there is never a match, and a transitive relationship is never established/found.

The following fix/workaround makes this behavior work again:
```patch
  export function buildMemberOf(groups: GroupEntity[], users: UserEntity[]) {
-  const groupsByName = new Map(groups.map(g => [g.metadata.name, g]));
+  const groupsByName = new Map(groups.map(g => [`group:default/${g.metadata.name}`, g]));
 
   users.forEach(user => {
     const transitiveMemberOf = new Set<string>();
```

### 👟 Reproduction steps

Tried to come up with a reproducible example, but it's tricky since it relies on the specific org structure we're ingesting from our Azure EntraID.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
A user is only expected to have `memberOf` relations to the groups they are direct members of according the the upstream org data source system, so that's all OK.

What you wanted though, is to have transitive _ownership_, and that's an entirely other world than membership. They don't have to be connected to one another at all. Your auth backend sign-in resolver is responsible for returning a set of ownership refs that get issued inside the Backstage token. It COULD do so by looking at the catalog and computing (!) the transitive membership dynamically. But it could also do it in any number of other ways. Our own sign in resolver, for example, communicates with an internal HR system to get some of the data it needs, no matter what the catalog says.

So you need to check your sign in resolver, and implement it in the way that works best for your particular org.

**Comment by fstoerkle** [comment]
Thanks for the explanation, that does make sense. This was also our initial idea, so we'll use our sign in resolver for this.
