### ISSUE TITLE
🐛 Bug Report: Vale link in contributing.md not working 

### ISSUE THREAD

**Issue by iwarra** [backstage/backstage#21346]
### 📜 Description

There is a link in the contributing.md to a Vale page that no longer exists.

### 👍 Expected behavior

Should be connected to a working Vale page.

### 👎 Actual Behavior with Screenshots

Links to page that doesn't exist.

### 👟 Reproduction steps

In ## Coding Guidelines in contributing.md by clicking on the link to install Vale. 

### 📃 Provide the context for the Bug.

The link is not working, making the documentation not up to date. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Happy to accept a fix! maybe something like https://vale.sh/docs/vale-cli/installation/ right?

**Comment by iwarra** [comment]
@freben PR already submitted.

**Comment by freben** [comment]
Alright, it wasn't linked so I missed that. Thanks!
