### ISSUE TITLE
🚀 Feature: Trigger an bitbucket pipeline with an action similar to github:dispatch

### ISSUE THREAD

**Issue by wunderkind-exe** [backstage/backstage#21365]
### 🔖 Feature description

i would greatly appreciate if i could trigger an bitbucket cloud pipeline on my backstage template

### this triggers an pipeline on github that creates an S3 Bucket on AWS
We have this on github
    - id: github-action
      name: Trigger GitHub Action
      action: github:actions:dispatch
      input:
        workflowId: s3-aws.yml
        repoUrl: 'github.com?repo=S3-AWS&owner=owner'
        branchOrTagName: 'main'
        workflowInputs:
          bucket_name: ${{ parameters.bucket_name }}
          region: ${{ parameters.region }}
          action: ${{ parameters.action }}
        
i would like to do the same with bitbucket, but i cant seem to find anything on how to do it

### 🎤 Context

My company only uses bitbucket cloud

Im creating a pipeline that have numerous terraform modules

my goal with backstage is to create an infra-as-a-code platform with the terraform modules templates, in a way that my devs can create any infra with my terraform code

i want to publish the content of the template, and then trigger the terraform pipeline with the specific parameters set by the template

### ✌️ Possible Implementation

I would like to pass the repoUrl, or the branch, or make an commit that triggers the pipeline

maybe something like bitbucketCloud:actions:triggerpipeline

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
This sounds sensible, do you want to contribute these actions? :pray:

**Comment by NeuralEvolution** [comment]
@benjdlambert im happy to pick this up.

**Comment by benjdlambert** [comment]
Nice @NeuralEvolution!

I'm just in the process of implementing https://github.com/backstage/backstage/issues/21442, so there might be some rebase work need after it lands, but go ahead!
