### ISSUE TITLE
💬 RFC: `auth-node` passport helpers JWT verify with JOSE

### ISSUE THREAD

**Issue by luchillo17** [backstage/backstage#21366]
### 🔖 Need

Right now in [PassportHelpers.ts#L30-L52][0] we have a `decodeJwtPayload` function that decodes JWT tokens, this function is currently internal and is used in [PassportHelpers.ts#L81][1] to decode the idToken.

Based on the official JWT.io page's [JWT JS libraries][2] it seems JOSE is supposed to be the defacto JWT library for JS, even the `jwt-decode` library mentions they only decode the token, but do not verify it, and our own code in Backstage already uses JOSE in multiple plugins and even a package, at the time of writing these ones:

- @backstage/backend-common
- @backstage/plugin-auth-backend
- @backstage/plugin-auth-backend-module-microsoft-provider
- @backstage/plugin-auth-backend-module-pinniped-provider
- @backstage/plugin-auth-node

[0]: https://github.com/backstage/backstage/blob/master/plugins/auth-node/src/passport/PassportHelpers.ts#L30-L52
[1]: https://github.com/backstage/backstage/blob/master/plugins/auth-node/src/passport/PassportHelpers.ts#L81
[2]: https://jwt.io/libraries?language=JavaScript

### 🎉 Proposal

We should probably remove the internal `decodeJwtPayload` in favor of using JOSE to decode it, maybe even check if we can add JWT verification as well:

[JOSE util_decode_jwt.decodeJwt.md](https://github.com/panva/jose/blob/main/docs/functions/util_decode_jwt.decodeJwt.md)
[JOSE jwt_verify.jwtVerify.md](https://github.com/panva/jose/blob/main/docs/functions/jwt_verify.jwtVerify.md)

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by benjdlambert** [comment]
@luchillo17 Think that this makes sense, probably doesn't need to be an RFC. Do you want to whip up a PR to contribute this? :pray:

**Comment by benjdlambert** [comment]
Yeah I think that if we can't verify the token without the secret using JOSE then we probably need to keep the code as is as we can't do that unfortunately.

**Comment by jamieklassen** [comment]
In general to verify a JWT you don't need a _secret_ per se, but you do need a JWK(S) or public key -- OIDC servers should advertise a `jwks_uri` where you can download their key set, but it might be a little extra work to make sure this data has been acquired in all cases where we're currently just decoding a JWT without verifying its signature
