### ISSUE TITLE
🚀 Feature: 'title' field for clusters

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#21398]
### 🔖 Feature description

I want a way to specify a nice human-readable name for clusters, especially in cases where those clusters are sourced from the catalog or other custom cluster supplier.

### 🎤 Context

I think [this comment](https://github.com/backstage/backstage/issues/13793#issuecomment-1699749223) captures the necessary background. This is, of course, _very_ similar to the problem solved by #14681 and #14712; however, I believe the 'title' keyword is significant.

### ✌️ Possible Implementation

This field could be used to display the headings in the summary portion of the cluster accordion:

https://github.com/backstage/backstage/blob/297e9a5d801bdbce87ed035ba696e274c666176c/plugins/kubernetes-react/src/components/Cluster/Cluster.tsx#L134-L138

as well as throughout the `kubernetes-cluster` plugin.

For clusters sourced from the catalog, it makes sense to pull this value from the `metadata.title` field on their corresponding `Resource` entity, and for clusters sourced from config I think we could add a new `title` field.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sabrina-lo** [comment]
+1, Would love to see this feature request get accepted/implemented. I am not a maintainer but it looks like this could be implemented by the new presentation API and is related to [this open issue](https://github.com/backstage/backstage/issues/20955)

**Comment by jamieklassen** [comment]
Hmm, opening a PR which mentions an issue doesn't seem to count as "activity" for staleness purposes
