### ISSUE TITLE
🚀 Feature: Allow enums to use EnunNames value in step review page

### ISSUE THREAD

**Issue by nabiltntn** [backstage/backstage#21404]
### 🔖 Feature description

When using scaffolder with properties having `enum` and `enumNames`, the step review is currently displaying the enum value and not the label from `enumNames` .

**Example**

```yaml
 enum:
- gp2
- gp3
- io1
enumNames:
- 'General Purpose SSD (gp2)'
- 'General Purpose SSD (gp3)'
- 'Provisioned IOPS (io1)'
```

If I select `gp2`, it would better to display the equivalent `General Purpose SSD (gp2)` in step review.

Links :
- https://backstage.io/docs/features/software-templates/input-examples/#array-with-custom-titles

### 🎤 Context

For  better UI/UX, I think it would be better to display the `label` and use the value only for the parameters to send to action. So the user can really validate the value he/she selected in the form and not the hidden value

### ✌️ Possible Implementation

I think it would coherent to add a new field under ui:backstage.review  like `mask` and `show` , maybe `useEnumName` to tell that when enum and enumNames are available, then use the equivalent enumNames item.

Change to do at this level : https://github.com/backstage/backstage/blob/master/plugins/scaffolder-react/src/next/components/ReviewState/ReviewState.tsx#L48

```js
if (backstageReviewOptions) {
  if (backstageReviewOptions.mask) {
    return [key, backstageReviewOptions.mask];
  }
  if (backstageReviewOptions.show === false) {
    return [];
  }
  // Add this code
  if (backstageReviewOptions.useEnumName && definitionInSchema['enum'] && definitionInSchema['enumNames']) {
    return [key, definitionInSchema['enumNames'][definitionInSchema['enum'].indexOf(value)]]
  }
}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Think that we should probably always use `enumNames` if they're present. Don't think it's worth us adding an option to configure this behaviour as it's just confusing if it's different IMO.

Do you want to contribute this fix? :pray:

**Comment by nabiltntn** [comment]
PR #21439 created
