### ISSUE TITLE
🚀 Feature: unique cluster names

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#21434]
### 🔖 Feature description

Let's ensure that the `name` field of a cluster is a unique identifier. More specifically, if I make a request to the `/api/kubernetes/clusters` endpoint, the JSON array returned should contain objects such that each `name` value appears exactly once.

### 🎤 Context

From my perspective, a nice thing about this is that the bug #15901 would no longer occur. Moreover, having some kind of unique identifier is probably intuitive for integrators (I know I would have expected it when I first started with Backstage), and is a small step towards #13727.

Now there have been some valid [criticisms](https://github.com/backstage/backstage/issues/13793#issuecomment-1387169175) of the difficulty of generating consistently unique names, and also the likelihood that such names will not be human-readable. The latter I hope should be addressed by #21398.

### ✌️ Possible Implementation

The first thing I would try is modifying the `CombinedClustersSupplier` to check every single cluster it processes and make sure it hasn't seen its name before, throwing an error if it sees a duplicate:

https://github.com/backstage/backstage/blob/fc92656e4290aece5f332c2f4f54af50903afe5d/plugins/kubernetes-backend/src/cluster-locator/index.ts#L27-L41

At first, though, this might be too aggressive. Maybe we setup a migration plan for this; first just have the combined supplier log a warning to learn a bit more about possible sources of duplication.

As of now, I can think of two such sources:
* I'm pretty sure that, based on issues like #13793 and #15668, the presence of [`AwsEKSClusterProcessor`s](https://backstage.io/docs/reference/plugin-catalog-backend-module-aws.awseksclusterprocessor/) in the ingestion system can result in ambiguous cluster names.
* the [`ConfigClusterLocator`](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/cluster-locator/ConfigClusterLocator.ts) itself doesn't validate that the clusters it processes have unique names -- this would be pretty easy validation to add on startup.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@mclarke47 can this be closed? :pray:

**Comment by mclarke47** [comment]
I would like to find time to fix this but that doesn't seem like it's gonna happen soon
