### ISSUE TITLE
💬 RFC: Migrate Builtin Scaffolder Actions Into Separate Modules

### ISSUE THREAD

**Issue by aaronnickovich** [backstage/backstage#21442]
### 🔖 Need

I would like if we could break out the builtin scaffolder actions out of the core backend scaffolder package so we can reduce the scope of packages that may contain CVEs for adopters and provide a clear home for the various scaffolder integrations. They are currently buried in the scaffolder backend which is a rather difficult place to find the builtin actions for contributors like myself.

As an adopter, I do not have an integration for gitlab or azure. Yet, the scaffolder include code that may contain CVEs for those integrations that I cant remove.

### 🎉 Proposal

I think to avoid disrupting adopters multiple times with this change for each module, we should probably take this as a migration in phases so it impacts adopters fewer times. For instance, this is my initial plan:

- Phase 1: Move all the builtin actions into their own modules, but maintain that the backend builtin actions still include them as they start to get migrated. such as:
  -  `@backstage/plugin-scaffolder-module-github`
  - `@backstage/plugin-scaffolder-module-gitlab`
  - `@backstage/plugin-scaffolder-module-azure`

- Phase 1.5: Create a `@backstage/plugin-scaffolder-module-builtins` to include each of the builtin modules above as they are migrated over above. The backend scaffolder would use this new 'builtins' module that included the 'createBuiltActions' function instead of referencing each module.

- Phase 2: Create a breaking change to the backend scaffolder that removes all of the references to the scaffolder modules and the 'builtins' module. Then create migration and release documentation to show people how to include the new builtin module, or include the integrations they want for more granular way to pick and choose the actions they want.

### 〽️ Alternatives

My proposal seems like the best way forward to reducing the size of the included code for the default scaffolder plugin. This is what the modules system was designed to do - make plugins smaller and extensible with modules.

There are alternative release mechanisms like doing a big bang release or creating breaking changes to the scaffolder for each time another integration is migrated off of the core codebase. I generally like migration phases since it gives more time to move large code without as much risk to external users.

### ❌ Risks

The risk to adopters after my plan for phase 2 is that it is a planned breaking change. People will need to include the code they want to use, but I want to also have a 'builtins' module that people can use to get the same exact behavior they have now without the embedded actions as separate modules.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by awanlin** [comment]
Hi @aaronnickovich, thanks for this! Overall this seems very reasonable to me, it's a lot like what's done with the existing modules - auth, catalog, events, etc.

I do have comments around phase 1.5 and 2:
 - For 1.5 why do we need this? I haven't seen that done before and I'm not sure it's needed. If we end up with a breaking change then this seems like a chance for Adopters to just install the modules they need.
 - For 2 generally both patterns run at the same time and eventually the old is removed. This is how the new backend system was introduced, the recent refactoring of the auth providers, and most general deprecations. Guess what I'm trying to say is that the migration docs should come in advance of this and make the breaking change a non-event more or less as everyone would already be using the new pattern

Also, just for my own curiosity you mention CVEs a few times, can you share some examples?

**Comment by aaronnickovich** [comment]
Hi @awanlin,
Thanks for the quick response!

I was trying to keep the equivalent of the out-of-box 'createBuiltinActions' functionality for new adopters with the proposed 'builtins' module. I personally would rather just not have a catch-all module and let the adopters make their own choices. Maybe I can keep the out-of-box functionality by just including all the default behaviors in the create-app template and then new adopters can delete what they dont use later.

Part of my proposal was to delete the actions from the backend and move it to the new modules in the same release but forgot about the deprecation policy for backstage. So, I should just keep the 2 codebases until migration is complete, then slowly deprecate / delete the builtins from the backend code once the new modules are OK.

**Comment by aaronnickovich** [comment]
closing as the features were implemented in #21752

**Comment by Pike** [comment]
Is #21965 effectively tracking phase 2?
