### ISSUE TITLE
🚀 Feature: Allow running plugin in isolation

### ISSUE THREAD

**Issue by t1agob** [backstage/backstage#21454]
### 🔖 Feature description

I am building a Backstage backend plugin and I want to run it in isolation, the same way that I can for frontend plugins but I'm unable to. 

If I run `yarn start` command it gets stuck on execution and nothing happens. In order to be able to run the backend plugin in isolation I need to use the `LEGACY_BACKEND_START` environment variable and then it runs without any problem.

I am not sure if this is due to the new backend system being introduced but according to the docs it is still in _alpha_.

### 🎤 Context

I took ownership of one of the plugins previously maintained by Backstage in the main project repo but I have moved it to my companies GitHub account (PagerDuty). 

In order to introduce some features I need to deploy a backend plugin and for that reason I wanted to run the backend plugin in an isolated project and be able to execute it locally for development purposes. This doesn't seem to be possible with the code provided when I run `yarn new` command and it is not documented anywhere. 

Having this capability would allow contributors to develop and execute backend plugins without the need of adding it to a Backstage project. In the end we are talking about a simple express server running that we can interact with from any REST API client.

### ✌️ Possible Implementation

Currently my workaround is to add `LEGACY_BACKEND_START` environment variable on `yarn start` command. This can easily be added to the code generated or at least document this corner case. 

Ideally this wouldn't be required and it would work with `yarn start` command immediately. 

There are some issues where this workaround is mentioned but no issue was created to find a solution for this problem (https://github.com/backstage/backstage/issues/21338).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Thank you for reporting! 👍

Fixed by #21547 as we're now provided better error messaging. There's still work to be done to update the templates, but that part is already tracked by #21288
