### ISSUE TITLE
🐛 Bug Report: The `GitlabDiscoveryEntityProvider` leaks the gitlab integration token in the logs when a token with a newline character is provided.

### ISSUE THREAD

**Issue by Zaperex** [backstage/backstage#21503]
### 📜 Description

The `GitlabDiscoveryEntityProvider` leaks the gitlab integration token in the logs when a token with a newline character is provided.

### 👍 Expected behavior

The token should be `[REDACTED]`.

### 👎 Actual Behavior with Screenshots

The `GitlabDiscoveryEntityProvider` leaks the gitlab integration token in the logs when a token with a newline character is provided.
```
backend:start: 2023-11-23T16:15:58.878Z catalog error GitlabDiscoveryEntityProvider:my-test-provider refresh failed, TypeError: [REDACTED] is not a legal HTTP header value [REDACTED] is not a legal HTTP header value type=plugin target=GitlabDiscoveryEntityProvider:my-test-provider class=GitlabDiscoveryEntityProvider$1 taskId=GitlabDiscoveryEntityProvider:my-test-provider:refresh taskInstanceId=3ce9e6da-1bfa-4f42-8489-7361e574da5a stack=TypeError: glpat-<rest of exposed token>
backend:start:  is not a legal HTTP header value
backend:start:     at validateValue (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/backstage-plugin-catalog-backend-module-gitlab-dynamic/node_modules/node-fetch/lib/index.js:684:9)
backend:start:     at Headers.append (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/backstage-plugin-catalog-backend-module-gitlab-dynamic/node_modules/node-fetch/lib/index.js:836:3)
backend:start:     at new Headers (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/backstage-plugin-catalog-backend-module-gitlab-dynamic/node_modules/node-fetch/lib/index.js:761:11)
backend:start:     at new Request (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/backstage-plugin-catalog-backend-module-gitlab-dynamic/node_modules/node-fetch/lib/index.js:1231:19)
backend:start:     at /home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/backstage-plugin-catalog-backend-module-gitlab-dynamic/node_modules/node-fetch/lib/index.js:1449:19
backend:start:     at new Promise (<anonymous>)
backend:start:     at Object.fetch [as default] (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/backstage-plugin-catalog-backend-module-gitlab-dynamic/node_modules/node-fetch/lib/index.js:1447:9)
backend:start:     at GitLabClient.pagedRequest (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/backstage-plugin-catalog-backend-module-gitlab-dynamic/dist/index.cjs.js:300:53)
backend:start:     at GitLabClient.listProjects (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/backstage-plugin-catalog-backend-module-gitlab-dynamic/dist/index.cjs.js:68:19)
backend:start:     at paginated.archived (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/backstage-plugin-catalog-backend-module-gitlab-dynamic/dist/index.cjs.js:469:27)
backend:start:     at paginated (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/backstage-plugin-catalog-backend-module-gitlab-dynamic/dist/index.cjs.js:321:17)
backend:start:     at paginated.next (<anonymous>)
backend:start:     at GitlabDiscoveryEntityProvider$1.refresh (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/backstage-plugin-catalog-backend-module-gitlab-dynamic/dist/index.cjs.js:481:22)
backend:start:     at fn (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/backstage-plugin-catalog-backend-module-gitlab-dynamic/dist/index.cjs.js:446:24)
backend:start:     at TaskWorker.fn (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/@backstage/backend-tasks/dist/index.cjs.js:599:15)
backend:start:     at TaskWorker.runOnce (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/@backstage/backend-tasks/dist/index.cjs.js:350:18)
```

### 👟 Reproduction steps

1. Setup the `GitlabDiscoveryEntityProvider` from '@backstage/plugin-catalog-backend-module-gitlab'
2. Setup Gitlab Integration with a token that includes a newline character. Ex:
```yaml
integrations:
  gitlab:
    - host: gitlab.com
      token: |
        glpat-<rest of the token>
```
3. Configure the `GitlabDiscoveryEntityProvider`
4. Start the backstage instance and observe the leaked token in the error log

### 🖥️ Your Environment

OS:   Linux 6.5.12-300.fc39.x86_64 - linux/x64
node: v18.18.0
yarn: 1.22.19
cli:  0.23.1 (installed)
backstage:  1.19.6

Dependencies:
  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.5.7
  @backstage/backend-common                                        0.19.8, 0.19.7
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.6.6, 0.5.4
  @backstage/backend-plugin-manager                                0.0.2-janus.5
  @backstage/backend-tasks                                         0.5.11
  @backstage/catalog-client                                        1.4.5, 1.4.4
  @backstage/catalog-model                                         1.4.3, 1.4.2
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5
  @backstage/cli                                                   0.23.1
  @backstage/config-loader                                         1.5.2
  @backstage/config                                                1.1.1, 1.1.0
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.13.7
  @backstage/core-plugin-api                                       1.7.0, 1.6.0
  @backstage/errors                                                1.2.3, 1.2.2
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7
  @backstage/integration-react                                     1.1.20, 1.1.19
  @backstage/integration                                           1.7.1, 1.7.0
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.4
  @backstage/plugin-auth-node                                      0.4.0, 0.2.19
  @backstage/plugin-azure-devops-backend                           0.4.3
  @backstage/plugin-azure-devops-common                            0.3.1
  @backstage/plugin-azure-devops                                   0.3.7
  @backstage/plugin-catalog-backend-module-github-org              0.1.0
  @backstage/plugin-catalog-backend-module-github                  0.4.4
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.3
  @backstage/plugin-catalog-backend-module-openapi                 0.1.23
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-import                                 0.10.1
  @backstage/plugin-catalog-node                                   1.4.7
  @backstage/plugin-catalog-react                                  1.8.5, 1.8.4
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-dynatrace                                      7.0.5
  @backstage/plugin-events-backend                                 0.2.15
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-github-actions                                 0.6.6
  @backstage/plugin-github-issues                                  0.2.14
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-home-react                                     0.1.4
  @backstage/plugin-home                                           0.5.9
  @backstage/plugin-jenkins-backend                                0.3.0
  @backstage/plugin-jenkins-common                                 0.1.20
  @backstage/plugin-jenkins                                        0.9.0
  @backstage/plugin-kubernetes-backend                             0.13.0
  @backstage/plugin-kubernetes-common                              0.7.0
  @backstage/plugin-kubernetes-node                                0.1.0
  @backstage/plugin-kubernetes-react                               0.1.0
  @backstage/plugin-kubernetes                                     0.11.0
  @backstage/plugin-lighthouse-common                              0.1.4
  @backstage/plugin-lighthouse                                     0.4.10
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-pagerduty                                      0.6.6
  @backstage/plugin-permission-backend                             0.5.29
  @backstage/plugin-permission-common                              0.7.9
  @backstage/plugin-permission-node                                0.7.17
  @backstage/plugin-permission-react                               0.4.16, 0.4.15
  @backstage/plugin-proxy-backend                                  0.4.4
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.9
  @backstage/plugin-scaffolder-backend                             1.18.1
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.7
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-sonarqube-backend                              0.2.8
  @backstage/plugin-sonarqube-react                                0.1.9
  @backstage/plugin-sonarqube                                      0.7.7
  @backstage/plugin-tech-radar                                     0.6.9
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.1
  @backstage/plugin-techdocs-node                                  1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.6

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Sure

**Comment by freben** [comment]
Interesting. Could be that the redacter should be set up with the `.trim()`ed version of each value. Is this something you might want to contribute? 🙏

**Comment by Zaperex** [comment]
Sure, I can take a look at this. It seems that the redactor does work for the `message` part of the log as shown in the logs I sent earlier. However, the token was exposed in the stack trace in the logs which the redactor does not seem to redact. https://github.com/backstage/backstage/blob/e77d833c6958e85ffe2ffc7f0da6c830dcb25ebe/packages/backend-app-api/src/logging/WinstonLogger.ts#L82-L84

Do you think it would be sufficient to just redact the stack trace of a log (if it exists) for now?
