### ISSUE TITLE
🚀 Feature: Path aliases for module importing

### ISSUE THREAD

**Issue by nicolaslima321** [backstage/backstage#21507]
### 🔖 Feature description

The possibility to provide a few aliases for paths, for instance:

```json
  "path": {
    "@/": ["./src"],
    "@tests/": ["./tests"],
    ...
  }
```
Obs: Very identical to what we got on the **"path" attribute**, provided by **tsconfig.json**. Or even make the Backstage recognize these aliases from **tsconfig**..

What is expected with this feature, for instance, is this:
```ts
import { User } from '../../user/model';
import { HttpClient } from '../../http/axios';
```

Could be turned into something like this:
```ts
import { User } from '@/entities/user/model';
import { HttpClient } from '@/clients/http/axios';
```

### 🎤 Context

The main problem that makes this feature a nice approach is that relative paths can easily turn into a mess.

I thought about using the "path" aliases provided in tsconfig.json along with the library tsconfig-paths (https://www.npmjs.com/package/tsconfig-paths). But to use that, I believe I would need to change the way the backstage-cli executes the app, and I was looking for a less invasive approach.

I didn't find anything in the posts or in the community, so I thought of opening that issue.

A possible example of that feature in practice would be:

With this configuration in tsconfig.json (for instance):
```json
  "path": {
    "@/": ["./src"]
    ...
  }
```

turn this
```ts
import { User } from '../../user/model';
import { HttpClient } from '../../http/axios';
```

into this
```ts
import { User } from '@/entities/user/model';
import { HttpClient } from '@/clients/http/axios';
```

### ✌️ Possible Implementation

Maybe implement the tsconfig-paths, and make possible to recognize the **path** property from tsconfig file.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
I know opinions differ here, but to me personally, imports have become basically a non-issue. The editor constructs them, organizes them, and mostly also maintains them during refactors. We lint against most actual mistakes. I spend little time looking at them.

Adding features like this adds significant complexity / risk (it has to work in all environments, for any build / bundler system we might want to switch to, etc) for what at least I perceive as small amounts of benefit.

You carefully need to make it work fully both in regular builds, local dev server scenarios, in jest runs, in storybook, potentially the microsite, local tooling and the runners they might be under, and more. You need to not confuse dev env plugins and similar. Sometimes, that turns out to be a petty hefty task.

We used to have some abilities that were tangentially similar to this that messed with what import syntax was used. We removed and streamlined that because of the maintenance burden and the minute differences between different environments.

**Comment by Rugvip** [comment]
Had to go digging a bit 😁 This isn't the exact same thing, but close enough: #729

But yep, not something we're really considering right now as it's very painful to support in a monorepo setup like ours that is geared towards performing well for project-wide TypeScript compilation and completions.

**Comment by nicolaslima321** [comment]
For testing purposes, ["_moduleNameMapper_"](https://jestjs.io/pt-BR/docs/configuration#modulenamemapper-objectstring-string--arraystring) prop  in the Jest configuration did the trick. I just added this in my root (workspace) **package.json**:

```json
...
  "jest": {
    "rootDir": "./",
    "moduleNameMapper": {
      "^@app/(.*)$": "<rootDir>/packages/app/src/$1",
      "^@backend/(.*)$": "<rootDir>/packages/backend/src/$1"
    },
  }
...
```

Just a observation, in my backend **package.json**, I'm using this ["_testMatch_"](https://jestjs.io/pt-BR/docs/configuration#testmatch-arraystring):
```json
...
  "jest": {
    "testMatch": ["<rootDir>/packages/backend/tests/**/*.test.{js,ts,mjs,cjs}"]
  }
...
```

---

Now instead of this importing:

```ts
import { PluginEnvironment } from '../../src/types';
import { PluginEnvironment } from '@backend/types';

describe('test', () => {
  it('unbreaks the test runner', () => {
    const unbreaker = {} as PluginEnvironment;
    expect(unbreaker).toBeTruthy();
  });
});
```

I can work with this:

```ts
import { PluginEnvironment } from '@backend/types';

describe('test', () => {
  it('unbreaks the test runner', () => {
    const unbreaker = {} as PluginEnvironment;
    expect(unbreaker).toBeTruthy();
  });
});
```

---

It's not at dev/build level, but I hope this helps someone! I'll keep updating here whenever I discover something new..

**Comment by Rugvip** [comment]
@nicolaslima321 hold up, you can already do that with our existing setup though? :sweat_smile:

**Comment by Rugvip** [comment]
@nicolaslima321 ah didn't pay attention to the full example, thought it was `@backstage/types`
