### ISSUE TITLE
🚀 Feature: Backstage Theme Creator

### ISSUE THREAD

**Issue by tudi2d** [backstage/backstage#21504]
### 🔖 Feature description

Customizing the theme of Backstage can be tricky. Not only are there several Material UI `ThemeOptions`, but there are also custom options for Backstage that have been added over time. It is not always easy to understand which theme variables are used where and what the impact of changes will be. Furthermore, customizing the theme can be tricky for people without knowledge of TypeScript & Material UI.

With the Backstage Theme Creator, you can customize the theme variables of Material UI & Backstage through both a UI and a code editor on a single web page. The application is designed to make it easy for anyone to create a custom theme.

### ✌️ Possible Implementation

> [!NOTE]
> Repository: https://github.com/tudi2d/backstage-theme-creator
> Backstage Theme Creator: https://backstage-theme-creator.vercel.app

<img width="1452" alt="Screenshot 2023-11-23 at 16 40 27" src="https://github.com/backstage/backstage/assets/8904624/0560d2f1-be08-4a00-be3d-7465c6a0a380">

With forking the original [`mui-theme-creator`](https://github.com/bareynol/mui-theme-creator) project, there are a lot of nice features supported out of the box, but also a lot of legacy code that needs to be either removed or updated.

Features:
- Monaco Code Editor with code highlighting & suggestions for Backstage `ThemeOptions`
- UI to change Material UI palette colors, font & add common patterns
- Save & load different themes
- Visualize most Material UI components separately to see the impact of theme changes

----

The current implementation is a MVP and still has a lot of open TODO's listed [here](https://github.com/tudi2d/backstage-theme-creator#to-be-done). The goal is to find out if there is interest in a theme creator for Backstage. If there is genuine interest in the idea I would be more than happy to move the repository to the Backstage organisation.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
This is so awesome! 🔥

**Comment by sennyeya** [comment]
+1 really awesome work! 🔥

**Comment by awanlin** [comment]
I feel like this should be shared in some of the other forums we have, not sure if this came up in the Community session today? I missed most of it.

**Comment by tudi2d** [comment]
Yeah - might makes sense - I will consider it.

**Comment by vinzscam** [comment]
> I feel like this should be shared in some of the other forums we have, not sure if this came up in the Community session today? I missed most of it.

@awanlin I suggested the same yesterday 😄
