### ISSUE TITLE
🐛 Bug Report: Unclear lineage for some of the custom action package

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#21513]
### 📜 Description

This isn't a bug so much as it's unclear the lineage for some of the customer action packages listed here: https://backstage.io/docs/features/software-templates/writing-custom-actions#list-of-custom-action-packages

The packages that are marked as owned by Drew Hill who's username is `arhill05` link to NPM packages with the scope `@mdude2314` and aren't linked back to a repo to help validate them.

### 👍 Expected behavior

Ideally the packages should use a scope that matches their used name but should for sure have a link back to the code repository

### 👎 Actual Behavior with Screenshots

The user name does not match the scope and their is no link to the code repository

### 👟 Reproduction steps

Simply look at the packages listed here: https://backstage.io/docs/features/software-templates/writing-custom-actions#list-of-custom-action-packages

### 📃 Provide the context for the Bug.

I was looking up the package for the git clone actions to help someone on Discord and when I could not get to the code I was a bit confused and then noticed the names didn't match. This feels a bit concerning from a security perspective

### 🖥️ Your Environment

Not applicable in this case

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @arhill05, I'm really sorry, I don't mean to call you out. We don't have a good policy around this and I'm working on it. Is there any way you can add a link back to your code repo for these actions? It should be as simple as adding it you your `package.json` and then publishing a new version with that. If I get time over the weekend I'll submit some PRs to help with that 👍

**Comment by awanlin** [comment]
I've created a PR to provide some tips around this: https://github.com/backstage/backstage/pull/21514

**Comment by arhill05** [comment]
Hey @awanlin! No worries on the call out, I'm happy to make the changes.

However, I'm out of town for the holidays. I'll make this change as soon as I get back, but if you end up making PRs before I get to it I'll gladly take a look. 

Thanks for letting me know!

**Comment by awanlin** [comment]
Ok, great, thanks for the super fast reply @arhill05. I'll try and submit the PRs over the weekend, you enjoy the time off!

**Comment by arhill05** [comment]
Hi @awanlin!

I've added the `repository` field to all of the `@mdude2314` scoped npm packages used in Backstage and published new versions of each. Sorry for the confusion, I wasn't aware that was a best practice. Please let me know if this fixes what you were concerned with!

I'll add something to my todo list to get these changed to an `@arhill05` scope sometime in the future.

Happy holidays!
