### ISSUE TITLE
Icons for custom kinds in new Catalog version

### ISSUE THREAD

**Issue by Alok650** [backstage/backstage#21529]
### 📜 Description

Hello!
I am facing issues with adding icons for the custom kind entities I have in my catalog. However, the icons are not getting used and it's showing a question mark icon instead. Refer to the image shared from the catalog table for the custom kind

<img width="29" alt="image" src="https://github.com/backstage/backstage/assets/58817460/9c394ef7-6a9e-4e5f-b092-1e24d9a0efdd">

### 👍 Expected behavior

It should ideally use the custom icons defined in the packages/app/api.ts file

### 👎 Actual Behavior with Screenshots

It is not using these apis and instead showing the question mark icon

### 👟 Reproduction steps

in packages/app/api.ts

  createApiFactory({
    api: entityPresentationApiRef,
    deps: {
      catalogApi: catalogApiRef,
    },
    factory({ catalogApi }) {
      return DefaultEntityPresentationApi.create({
        catalogApi,
        kindIcons: {
          jenkins: WorkIcon,
        },
      });
    },
  }),
  
 However this is not getting used.
 Packages being used:
 
 import { catalogApiRef, entityPresentationApiRef,
 } from '@backstage/plugin-catalog-react';
 import WorkIcon from '@material-ui/icons/Work';
  import { DefaultEntityPresentationApi } from '@backstage/plugin-catalog';
  
  versions:
      "@backstage/plugin-catalog-react": "^1.8.5",

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Thanks! I made #21546 to hopefully address it.

**Comment by Alok650** [comment]
Hi @freben 
Thanks for taking it up on such a shorten notice. I wanted to understand, after this change, what would be the steps required to set the custom kinds. Will it be setup using 

file: packages/app/api.ts
```
import {
  catalogApiRef,
  entityPresentationApiRef,
} from '@backstage/plugin-catalog-react';
import { DefaultEntityPresentationApi } from '@backstage/plugin-catalog';

  createApiFactory({
    api: entityPresentationApiRef,
    deps: {
      catalogApi: catalogApiRef,
    },
    factory({ catalogApi }) {
      return DefaultEntityPresentationApi.create({
        catalogApi,
        kindIcons: {
          component: GitHubIcon,
          user: PeopleIcon,
          group: GroupIcon,
          aws: AWSIcon,
          jenkins: WorkIcon,
        },
      });
    },
  }),
  ```
  also I am not seeing this question mark icon on aws kind - only there in Jenkins. Want to understand which property from the entity schema is it using for reference?

**Comment by freben** [comment]
That looks right.

Indeed it uses just the kind field.

The api comes with a default set of icons for the well known kinds so you'll only have to specify the ones to override/add.

If you use the given code above, AFTER the fix PR, but only get one of the two kinds applied, then that does sound surprising.

**Comment by imbabamba** [comment]
isn't it supposed to be "type" icons? We use Kind: Component with type 'mongodb' and 'rabbitmq' for example, which present a (?) as icon. would be great to be able to set custom icons for custom TYPES. but that perhaps is the above examples too. or else, please add custom icons for both scenarios.

**Comment by freben** [comment]
We started out with a kind map since it's what existed beforehand (in the form of the app icons with `kind:` prefix). Updating it to be even callback based with full flexibility later on could be an option.

**Comment by imbabamba** [comment]
but if one could set a custom icon as default for all "other" types at least. since the (?) is quite ugly.
