### ISSUE TITLE
🚀 Feature: Add Events Support for GitlabDiscoveryEntityProvider and GitlabOrgDiscoveryEntityProvider

### ISSUE THREAD

**Issue by elaine-mattos** [backstage/backstage#21553]
### 🔖 Feature description

Hi dear Backstage Community!

the GitlabDiscoveryEntityProvider and GitlabOrgDiscoveryEntityProvider classes currently lack implementation of the EventSubscriber interface. This poses a limitation for us, as they are not equipped to handle Gitlab webhooks for new group and user entities. 
It would be great not having to rely on the scheduler to sync our whole GitLab instance every time a new group is created! :)

### 🎤 Context

While investigating asynchronous Gitlab group ingestion, we discovered that the GitHub entity provider already supports events ([reference](https://backstage.io/docs/integrations/github/discovery#installation-with-events-support) and [here](https://backstage.io/docs/integrations/github/org#installation-with-events-support)). This led us to explore the same functionality for GitLab. 
We have verified that the [events-backend-module](https://github.com/backstage/backstage/blob/master/plugins/events-backend-module-gitlab/README.md) for Gitlab was already implemented but found out that the GitLab Entity Provider is not ready to ingest groups and users based on events. 

### ✌️ Possible Implementation

- Extend GitlabDiscoveryEntityProvider and GitlabOrgDiscoveryEntityProvider to implement the EventSubscriber interface.
- Integrate methods to handle Gitlab events triggered via webhooks.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hey, thanks for opening this issue 🙌🏻 
Your proposal seems good to us, and we look forward to your contribution 🎉 !

**Comment by elaine-mattos** [comment]
Still wip

**Comment by vinzscam** [comment]
Closed by #23373
