### ISSUE TITLE
🚀 Feature: Dependency Graph Arrows

### ISSUE THREAD

**Issue by sergeyshevch** [backstage/backstage#21587]
### 🔖 Feature description

It will be great to have arrows on the dependency relations graph. It makes relations easier to understand.

### 🎤 Context

As I see arrows were removed in this PR https://github.com/backstage/backstage/pull/13673. Is it possible to enable it back with some props?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
It's perhaps not entirely trivial to decide the directions of those arrows, right? The thing is, every single relation (in the default model) is two way, so there would _always_ be a pair of arrows going back and forth between nodes, and it just plain renders very poorly. To get around that we'd have to decide which of a pair is the "primary" one, and that might be different based on circumstances and/or which node is currently selected.

If you look at the picture in the linked PR, and think carefully about what every single arrow should actually show - there are a couple of different possibilities. And you'd potentially slightly lose out on some information in doing so.

**Comment by sergeyshevch** [comment]
@freben I agree but there is always **main** relation and a reverse one. Like providesApi is main and apiProvidedBy is secondary. I guess it's the right way to define the arrow in merged relations mode. In non-merged there is no such problem

I reverted this PR locally and tried it. Looks like arrows was always on the end of the graph edge so it is mostly a new feature request

Also I guess it will be good to have both labels and arrows

**Comment by mhitkaohp** [comment]
@freben as for "every single relation is two way" - the way I understand the relations in Backstage, they are actually unidirectional, but they tend to come in pairs directed in the opposite directions if that's what you mean. While the Backstage core might not differentiate between primary and secondary relationships, the catalog graph does, see https://backstage.io/docs/reference/plugin-catalog-graph.relationpairs. As @sergeyshevch mentioned, if the merged relations mode is switched on, such pairs are merged into a single edge, where the "primary" relation is highlighted and is mentioned as first. I find it natural to expect the arrow to be directed in the way how you'd read the (primary) relationship aloud, e.g. if A dependsOn B I'd say that `A -> B` makes sense.

Note that the graph component used to show relationships this way before, you can still find quite Backstage screenshots with the arrow heads shown. In fact, the catalog-graph plugin README contains videos that still show the arrow heads: https://github.com/backstage/backstage/blob/master/plugins/catalog-graph/README.md

This would be very useful in my case as well. If not enabled by default, at least to have it as an configuration option. Without this one has to rely on the visual order (top-down or left-to-right), which however falls apart if there are cycles in the (primary) relationships. For example if A depends on B, B depends on C, C depends on A, one of the edges in the rendered graph will be actually "pointing" backwards, which is somehow hard to see if it does not have an arrow head. This is how Backstage renders that now (would you say that C depends on A or A depends on C based on that?):

![image](https://github.com/backstage/backstage/assets/92733935/92aaffb2-599c-4418-8228-80e74a3d7592)

**Comment by mhitkaohp** [comment]
BTW I'd be willing to submit a PR if needed.

**Comment by sergeyshevch** [comment]
@mhitkaohp I guess it will be very useful for me as well. Sadly I have no time now for implementation but it will be good if you submit PR

**Comment by vinzscam** [comment]
great addition, looking forward to a PR @mhitkaohp 🤩

**Comment by mhitkaohp** [comment]
For anybody interested, this was accepted as an opt-in feature only, you'll need to adjust your Backstage installation to show the arrow heads in diagrams (from the release 1.23.0).

In order to show arrow heads in the catalog graph page, add `showArrowHeads` attribute to `CatalogGraphPage` component
(typically in `packages/app/src/App.tsx`):

```diff
- <CatalogGraphPage />
+ <CatalogGraphPage showArrowHeads />
```

In order to show arrow heads in entity graphs, add `showArrowHeads` attribute to `EntityCatalogGraphCard` components
(typically multiple occurrences in `packages/app/src/components/catalog/EntityPage.tsx`):

```diff
- <EntityCatalogGraphCard variant="gridItem" height={400} />
+ <EntityCatalogGraphCard variant="gridItem" height={400} showArrowHeads />

**Comment by awanlin** [comment]
Great, work @mhitkaohp, thanks for following up on this here!

Just a heads up that 1.23.0 is out on February 20th, if you want this feature sooner it was part of the weekly `next` release, specifically `v1.23.0-next.2`.
