### ISSUE TITLE
💬 RFC: Installing a Specific Version

### ISSUE THREAD

**Issue by matarnold-dev** [backstage/backstage#21593]
### 🔖 Need

Is it possible to install an older version of Backstage?  The current instructions only outline how to install the latest version.  I was hoping "$ npx @backstage/create-app@latest --version x.x.x" or something similar is available.  I can not find it? 

### 🎉 Proposal

Add script to install old versions.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by tudi2d** [comment]
Hej @matarnold-dev - we would be interested in your use case for this. Depending on what a specific version means for you this should not be possible. Are you aiming to setup a test environment for specific versions our what is your intention?:)
