### ISSUE TITLE
🚀 Feature: Add Scaffolder Action to create GitLab Issues

### ISSUE THREAD

**Issue by elaine-mattos** [backstage/backstage#21608]
### 🔖 Feature description

Hi dear community,

we have developed a Scaffolder action that creates GitLab Issues. 
We wonder if it would be a 'nice to have' for you. 

### 🎤 Context

While building our IDP with Backstage we started developing some additional Scaffolder actions for GitLab and would like to contribute back to Backstage.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @elaine-mattos, I'm sure those who use GitLab will find them helpful! Feel free to publish them to NPM and then you can add them to the list here: https://backstage.io/docs/features/software-templates/writing-custom-actions#list-of-custom-action-packages and to the Plugin Directory following the docs here: https://backstage.io/docs/plugins/add-to-directory

**Comment by benjdlambert** [comment]
Hey @elaine-mattos! I also want to tag in this issue: https://github.com/backstage/backstage/issues/21442 as this is probably something we're going to look at doing sooner rather than later so that we can bundle all these actions together into one module that you can install for each provider.

**Comment by elaine-mattos** [comment]
Hi!

I finally managed to create a PR for this and as this is my first open source PR ever, I'm very excited to hear your feedback! :)
https://github.com/backstage/backstage/pull/21929

ps.: @awanlin, as I only added a new custom action for an existing plugin, I didn't publish it to NPM.

**Comment by elaine-mattos** [comment]
Done:) ! https://github.com/backstage/backstage/pull/21929
