### ISSUE TITLE
🚀 Feature: Support for overriding help links for plugins

### ISSUE THREAD

**Issue by nanjingfm** [backstage/backstage#21606]
### 🔖 Feature description

These links are hardcoded in the plugin and are expected to be rewritten in `packages/app` or in the config file.

empty card:
<img width="943" alt="image" src="https://github.com/backstage/backstage/assets/18688410/81b10d9e-ba51-46c6-ab2f-b2ffc7e1e70a">

relation card:
<img width="552" alt="image" src="https://github.com/backstage/backstage/assets/18688410/8b4688d6-cd88-49e7-8c83-9ca4bb19b68d">

### 🎤 Context

My company has translated the backstage documentation and would like to link these to the internal documentation address.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by tudi2d** [comment]
Thanks @nanjingfm for raising - this is a valid issue. We are looking into fixing this long term with the new frontend system moving a lot of customisability to be config driven #19545. Unfortuanelly this will take some time to be fully supported & used across the ecosystem. For now we unfortunately we can't give you a straight solution to this.
