### ISSUE TITLE
Test utils should use database name given in connection string

### ISSUE THREAD

**Issue by zcmander** [backstage/backstage#21619]
### 📜 Description

See: https://github.com/backstage/backstage/blob/master/packages/backend-test-utils/src/database/TestDatabases.ts#L154

I assume that generating database name is there to make possible to run multiple test cases in paraller. However, there is no way to drop those databases afterwards.

### 👍 Expected behavior

I can see two possible solutions for this:

### 1. Utilize database name given in the connection string

If one gives connection string via environment variable like this:

```
BACKSTAGE_TEST_DATABASE_POSTGRESXX_CONNECTION_STRING=postgresql://john.doe:secret@localhost/build_123_testdb
```

I would assume that backstage test helper would use the `build_123_testdb` database, so I could remove the database later with `dropdb` command.

This would be the most obvious solution but as far as I know, this requires running all tests with `--runInBand` flag that prevents test cases being run in parallel. 

### 2. Drop database in afterAll -hook

This is probably a better solution as it makes possible to run multiple tests cases at the same time by creating separate test database for each test case.

It would be great if backstage could add some note about connection string that it's used only for initial connection and tests will initialize their own databases.

### 👎 Actual Behavior with Screenshots

No screenshots needed in this case.

### 👟 Reproduction steps

1. Run unittests in CI pipeline while providing `BACKSTAGE_TEST_DATABASE_POSTGRESXX_CONNECTION_STRING` environment variable
2. After a while the test database suffers from low disk space error as there's no way to clean those test databases

### 📃 Provide the context for the Bug.

Look at the reproduction steps for context.

### 🖥️ Your Environment

Does not really matter in this case.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by zcmander** [comment]
> I'm curious, what made it so that you ended up needing this kind of feature? If you're going to perform creation and deletion yourself anyway, then I don't think that the TestDatabases class really offers you anything of value anyhow.

It's a really long story but in short: We have a docker hub mirror in place and network connections to the mirror is a bit unreliable and slow. In addition to that: our unittests run in isolation without possibility to cache things (sigh) which means each build has to download each and every docker image that it needs during unit tests. So, by having external database it minimizes the need for downloading same images again and again that way makes CI builds more reliable and faster.

I know, in the end, the issue is in our end but that was my best effort keep our builds running smoothly but unfortunately that plan backfired as database's disk space fills up over time without possibility to do proper clean up (without affecting running builds). I think I will either remove the external database based on this discussion or keep cleaning temporary databases from time to time.

**Comment by freben** [comment]
I guess actually deleting the databases it creates would be the low hanging fruit here right? We could decide whether to _always_ do it (including if it's a docker based database) for simplicity even though it adds a tiny sliver of runtime, or whether to be smarter / more configurable.

The original ask of respecting the db name in the connection string would probably be a bit awkward since, as you note, we do want to be able to run tests perfectly in isolation and concurrently. For pg specifically we could use the one database and then create per-test schemas in that database instead, but that's a very pg-distinct thing and won't cover the other ones.

If you contributed an addition tho the teardown hook that actually deletes created databases, I would think it'd be OK.
