### ISSUE TITLE
🐛 Bug Report: Template generated from @backstage/create-app@latest throws typeError

### ISSUE THREAD

**Issue by WilliamDahlen** [backstage/backstage#21610]
### 📜 Description

When i start the application using either yarn dev or the debug command LOG_LEVEL=debug yarn dev everything seems to work fine. I can browse the catalog and apis, but then i try to create a new component using the included node example template i recieve a `typeError` with the content `NetworkError when attempting to fetch resource`. Every subsequent  action, like browsing the api or catalog then results in the same message, and the logout stops. The backend port in use (7007) which was open when the application started also closes at the same time. The only option to get it running again is to restart the application.

I have tried both version 0.5.7 and 0.5.6, seeing the same error. In version 0.5.5 this error is not introduced.

Together with @awanlin on Discord we went through a few troubleshooting steps.
- Changing the template from the one included to https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml. Still the same error
- Deploying the versions on a seperate machine (both macos 13.6.1 22G313). Same error

### 👍 Expected behavior

Backstage should create a new component in my catalog and deploy a github repository as the template describes.

### 👎 Actual Behavior with Screenshots

When trying to create a new component using the included template Backstage throws a `typeError: NetworkError when attempting to fetch resource`

The backend port is manually changed to 7001 by me as a troubleshooting step, but it does the same on port 7007 aswell.
The pictured template in use is the one from the troubleshooting steps above.
![Screenshot 2023-11-27 at 14 44 32](https://github.com/backstage/backstage/assets/36991168/31c79538-45b3-4a0f-b1a1-62c9ce9e3e94)
![Screenshot 2023-11-27 at 14 44 39](https://github.com/backstage/backstage/assets/36991168/8da75204-9d50-42d9-ba66-313de7c7729a)
![Screenshot 2023-11-27 at 14 44 51](https://github.com/backstage/backstage/assets/36991168/d0e7a1b2-e1d0-477b-ac25-58ecc077f7e8)
![Screenshot 2023-11-27 at 14 45 05](https://github.com/backstage/backstage/assets/36991168/2f7d93bc-ce02-490b-a388-5fffe3260753)
![Screenshot 2023-11-27 at 14 45 12](https://github.com/backstage/backstage/assets/36991168/b83b7342-58db-4f75-b0de-ccfeba76c9b8)
![Screenshot 2023-11-27 at 14 45 20](https://github.com/backstage/backstage/assets/36991168/037aa825-d162-4da1-bcf4-6129a9a8f748)
![Screenshot 2023-11-27 at 14 45 26](https://github.com/backstage/backstage/assets/36991168/d3544950-6249-455c-9c38-b7dbba502440)

### 👟 Reproduction steps

```
npx @backstage/create-app@latest # or @0.5.7/@0.5.6
yarn dev
```
1. Go to Create
2. Choose the included template
3. Fill out the form
4. Finish

Bug should be visible. Any subsequent request will not be logged in the terminal and they will fail in the browser with the same typeError.

### 📃 Provide the context for the Bug.

https://gist.github.com/WilliamDahlen/f9a0d23d22ce824bd0b8e6d3564f920e

### 🖥️ Your Environment

MacOs 13.6.1 (22G313)
node lts (v20.10.0)
yarn 1.22.19

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by awanlin** [comment]
Discord thread for reference: https://discord.com/channels/687207715902193673/1178679071538950265

**Comment by WilliamDahlen** [comment]
Confirmed working with the `export NODE_OPTIONS=--no-node-snapshot` as described in https://backstage.io/docs/features/software-templates/#getting-started

**Comment by awanlin** [comment]
Got a PR to improve the docs on this, when that merges it will close this issue 👍
