### ISSUE TITLE
🚀 Feature: use a dropdown or menu for the i18n language selector

### ISSUE THREAD

**Issue by gashcrumb** [backstage/backstage#21626]
### 🔖 Feature description

The current language selector control works for cases when there aren't many languages installed.  But if a user sets up many translations the selection widget becomes more difficult to use.

### 🎤 Context

When many languages are set up for a backstage instance, the language selector becomes a bit unwieldy:

![272569004-d1a67b66-03c4-4588-8179-07bb344a96e7](https://github.com/backstage/backstage/assets/351660/9af542ae-e94b-4f4e-8cc0-465799f5336c)

### ✌️ Possible Implementation

What about using a drop-down style menu for this selection instead?  

Also it might be nicer to show language names instead of language codes, perhaps just passing the language codes through the translation layer would be enough, as that would allow users to supply translated names for each language.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by gashcrumb** [comment]
With a quick switchover to a Select component:

![image](https://github.com/backstage/backstage/assets/351660/48e061d8-672a-4b1a-9b2c-a00208b71d7c)

And if I use the same list as above, seems still like having the language name would be nicer:

![image](https://github.com/backstage/backstage/assets/351660/a8a70649-477b-4abb-bf72-a11f6bf34383)

**Comment by Rugvip** [comment]
👍 to this change from me 😁

**Comment by gashcrumb** [comment]
So then maybe it could be something like this:

![image](https://github.com/backstage/backstage/assets/351660/ac2b6261-b5cb-4060-9455-e22b4c110592)

it would require a smart way to allow the typing to work for the translation function without having to relax the typing too much, as that's a really nice feature of the current implementation.

**Comment by gashcrumb** [comment]
The simplest approach I guess would be to add a 2nd function returned by `useTranslationRef` that doesn't have the type restrictions called something like `untypedT` for special cases like this.  But I'll spend some more time thinking on this, maybe there's other options.

**Comment by Rugvip** [comment]
@gashcrumb maybe although I feel that would be the least desirable workaround tbh. It'd need to be accompanied by some equivalent ability to provide freeform keys in `createTranslationMessages` and `createTranslationResource` which might also get a bit messy.

Thinking that perhaps one of the optimal ways to handle this is if we could end up with a translation key with a type like `languageToggle.language.${string}`?

**Comment by gashcrumb** [comment]
Yep, agreed, I'd go with a select containing language codes over that workaround :-)

Good idea on the typing, I got side-tracked away from this last week but am planning on looking again this week, I'll start with that thought.

**Comment by freben** [comment]
Naive question from someone not deeply familiar with i18next yet etc: Isn't this a more generic need, should it really be scoped to the language toggle? Thinking something like `core.language.<code>.name` and then being able to add more things than the plain name if needed.

As a side track, there's also `new Intl.DisplayNames(languageCode, { type: 'language' }).of(languageCode)` in most modern browsers for this specific need if all one wants is the user's defined locale name for the language code :)

**Comment by freben** [comment]
Pssh, accidental edit instead of quote reply - sorry about that ... here comes the actual reply:

> Awesome, I wasn't aware of that but that'd be worth trying for sure.

Yeah I think so too. Especially behind a try-catch and falling back to the raw string in the off-chance it isn't working, I think might be The Right Thing to do for a frontend piece of code in general (even better than the explicit translations). But I am definitely no authority on these things.

**Comment by gashcrumb** [comment]
Yep, that approach works really nicely @freben.

With English selected:
![image](https://github.com/backstage/backstage/assets/351660/d36f4366-4fcf-4e3f-a5bc-abe4621c9de0)

Then I select German:
![image](https://github.com/backstage/backstage/assets/351660/bf65f472-4843-4e15-8b03-e38f398bfff5)

I'll see how the tests look and probably get a PR open.

**Comment by Rugvip** [comment]
Just a note that you'd typically wanna display the languages in its own language rather than the currently selected one to make them easy to find

**Comment by gashcrumb** [comment]
So like this:

![image](https://github.com/backstage/backstage/assets/351660/55df7798-1a5f-4ad6-95db-e3449ae28a51)

Which seems better too since the list doesn't change with the selection.

**Comment by freben** [comment]
That looks awesome ✨

**Comment by C-RoblesAutodesk** [comment]
> So like this:
> 
> ![image](https://private-user-images.githubusercontent.com/351660/287754472-55df7798-1a5f-4ad6-95db-e3449ae28a51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTQyNDcsIm5iZiI6MTcwMTc1Mzk0NywicGF0aCI6Ii8zNTE2NjAvMjg3NzU0NDcyLTU1ZGY3Nzk4LTFhNWYtNGFkNi05NWRiLWUzNDQ5YWUyOGE1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQwNTI1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTIxMzg2ZmUxZGY3MWE4YjYzZjNlYzMzY2YxYjk5MWIwYTc2YmY3YTc1NDA1NjA2Y2U4ZmRkZThmZTcwNjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VVufufw0hAah8Pej_QqqOrni3hu3Ksqs_wRIxeyLBJU)
> 
> Which seems better too since the list doesn't change with the selection.

I'll suggest to implement a popup/modal widget instead of dropdown, what do we expect if the list goes beyond than 20 items?

In my perspective implementing this as a popup/modal we can handle the height/width of the container that will display the languages, without taking the user to the bottom of the page after searching for the language (can also be implemented a search bar for this), what do you think?

**Comment by gashcrumb** [comment]
@C-RoblesAutodesk yep, that's a good idea, let me add that to the PR.

**Comment by gashcrumb** [comment]
@C-RoblesAutodesk so for this I opted for the Select component, which doesn't expose properties to set the maxHeight property for the menu which would achieve this.  I think this would warrant a separate issue, as I started to add this it starts to increase the scope of change beyond what I personally would want in a PR.
