### ISSUE TITLE
🐛 Bug Report: Backend dev server forces develpoment mode leading to "System limit for number of file watchers reached" error

### ISSUE THREAD

**Issue by taras** [backstage/backstage#21637]
### 📜 Description

Follow-up to the message in [discussion](https://discord.com/channels/687207715902193673/1007241314607321138).

We start the backend in CI from source code to run integration tests. We recently started encountering flaky CI because of  `System limit for number of file watchers reached` caused by `watchpack` used by Webpack to watch files. 

It stems from assuming that the Webpack dev server will only be used in development mode. It's [hardcoded here](https://github.com/backstage/backstage/blob/master/packages/cli/src/lib/bundler/backend.ts#L26) without a way to override the value.  

### 👍 Expected behavior

It would be helpful to be able to disable watchers in CI. 

### 👎 Actual Behavior with Screenshots

It's difficult to show with a screenshot - it happens in CI.

### 👟 Reproduction steps

Run `CI=true NODE_ENV=production yarn start-backstage` and it'll still watch the file system. 

### 📃 Provide the context for the Bug.

I'm still determining the best way to fix this because there is already a decent amount of confusion here. We have NODE_ENV, which can be `development` or `production,` but starting the backend with integration tests can happen in CI or locally in development. 

As a temporary solution, I will patch `@backstage/cli` package to `isDev: !env.process.CI` but I know if this is the right solution for the core. Thoughts?

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
We could probably add a `--no-watch` to get around the watch limit issue, since that might happen during development too. I'm hesitant to add any more support for running backend start in production though, it's not what it's designed or intended for, especially the old Webpack version. I'd recommend e2e testing towards a proper backend build, either a Docker image directly or setup equivalent to what the Dockerfile does with the `dist/bundle.tar.gz` from the backend.

**Comment by kvmw** [comment]
We are running to the exact same issue in our CI.  Having an option to disable the watch would be very useful.

**Comment by taras** [comment]
Just FYI, we moved away from running dev server in CI. We use the built artifacts instead.

**Comment by kvmw** [comment]
> Just FYI, we moved away from running dev server in CI. We use the built artifacts instead.

@taras Do you mean running by docker? Is there a way to run the built artifacts other than docker image?
