### ISSUE TITLE
💬 RFC: Software Template ordering

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#21649]
### 🔖 Need

Currently, it's very hard to find the most commonly used templates if there are lots of software templates on the scaffolder page. The only option is to categorize the templates manually which requires a code change every time some template needs to be raised as a "recommended" one. 

### 🎉 Proposal

Allow sorting of templates by one of the criterias:

- Name (title)
- Number of runs (most used, least used) 
- Starred
- Owner
- Something else? Tags? Created?

By allowing users to do this, it's easier to find the templates that are hot in the community.

### ❌ Risks

Number of runs of each template needs to be fetched from the backend that might slow the page load

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by drodil** [comment]
Hey! Thanks for the pointers, I was aware of the templateFilters. But still, the templates cannot be ordered inside a category or at all by some field. For example catalog allows ordering by different columns so I don't see why it wouldn't work in the template list?

Also, the most used template ordering should be dynamic so that the number of runs is fetched from the database (from maybe the last 30 days or something) to pop up the Hot 🔥 templates people are currently using.

**Comment by kurtaking** [comment]
I had the same thought recently when working on organizing our templates. I separated them using `templateFilters`, but still wanted them organized differently within the _grouping_.

**Comment by benjdlambert** [comment]
I think that we could look at adding a `sort: (a,b) => number` method to `TemplateGroupFilter` in order for us to sort the results. Feels like other things like `runCount` or whatnot, could be added as additional metadata somewhere to the variables to the sort handler.

**Comment by drodil** [comment]
Not stale

**Comment by drodil** [comment]
Still not stale. @benjdlambert any idea if this could be implemented?
