### ISSUE TITLE
🐛 Bug Report: docs: broken link

### ISSUE THREAD

**Issue by jjangga0214** [backstage/backstage#21646]
### 📜 Description

https://github.com/backstage/backstage/blob/8a6d4e617e1608e64170ba08b76211eab77caa6c/docs/overview/architecture-overview.md#L46

The link is 404.

### 👍 Expected behavior

.

### 👎 Actual Behavior with Screenshots

.

### 👟 Reproduction steps

.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by tudi2d** [comment]
Thanks for reporting @jjangga0214 - side effect of a reason change in the demo environment - @awanlin is on it!:)
