### ISSUE TITLE
🐛 Bug Report: backend does not start with yarn dev or yarn start-backend

### ISSUE THREAD

**Issue by TechHoops** [backstage/backstage#21658]
### 📜 Description

After upgrading the backstage to 1.20.2 backend fails to start, when I do `yarn dev` or `yarn start-backend`

### 👍 Expected behavior

Appication should start successfully.

### 👎 Actual Behavior with Screenshots

yarn start-backend
C:\repos\devx\node_modules\@backstage\core-components\dist\components\EmptyState\assets\missingAnnotation.svg:1
<svg xmlns=http://www.w3.org/2000/svg width="687" height="421" fill="none" viewBox="0 0 687 421"><path fill="#000" fill-opacity=".05" fill-rule="evenodd" d="M40.0514 109.914C26.8955 112.366 18.2179 125.018 20.6695 138.174C23.121 151.33 35.7733 160.007 48.9292 157.556L67.0549 154.178C62.008 159.609 59.5097 167.278 60.9722 175.127C63.4237 188.283 76.076 196.96 89.2319 194.509L218.279 170.462C218.305 170.617 218.333 170.773 218.362 170.929C219.824 178.778 224.917 185.032 231.582 188.281L223.663 189.757C210.507 192.208 201.83 204.861 204.281 218.016C206.733 231.172 219.385 239.85 232.541 237.398L608.658 167.311C621.814 164.86 630.492 152.208 628.04 139.052C626.578 131.203 621.485 124.949 614.821 121.7L627.489 119.339C640.645 116.888 649.322 104.236 646.871 91.0797C644.419 77.9238 631.767 69.2462 618.611 71.6977L393.02 113.735C392.994 113.579 392.966 113.423 392.937 113.267C391.475 105.419 386.382 99.1643 379.717 95.9156L401.619 91.8343C414.775 89.3828 423.453 76.7305 421.001 63.5746C418.55 50.4187 405.897 41.7411 392.742 44.1927L40.0514 109.914ZM59.146 298.224C56.6945 285.068 65.3721 272.416 78.528 269.964L464.483 198.044C477.639 195.592 490.292 204.27 492.743 217.426C495.195 230.582 486.517 243.234 473.361 245.685L462.309 247.745C463.599 248.374 464.83 249.115 465.987 249.959L599.731 225.037C612.887 222.585 625.539 231.263 627.991 244.419C629.453 252.267 626.955 259.937 621.908 265.368L624.601 264.866C637.757 262.414 650.41 271.092 652.861 284.248C655.313 297.404 646.635 310.056 633.479 312.507L232.561 387.216C219.405 389.667 206.752 380.99 204.301 367.834C201.849 354.678 210.527 342.026 223.683 339.574L252.958 334.119C251.668 333.49 250.437 332.749 249.279 331.905L70.8205 365.159C57.6646 367.611 45.0123 358.933 42.5608 345.777C40.1093 332.621 48.7869 319.969 61.9428 317.518L72.3657 315.575C65.7014 312.327 60.6085 306.072 59.146 298.224Z" clip-rule="evenodd"/><g filter="url(#filter0_d)"><path fill="#9E9E9E" d="M566.795 76.0288H124.842C119.604 76.0288 115.358 80.27 115.358 85.5018V113.921C115.358 119.153 119.604 123.394 124.842 123.394H566.795C572.033 123.394 576.279 119.153 576.279 113.921V85.5018C576.279 80.27 572.033 76.0288 566.795 76.0288Z"/><mask id="mask0" width="462" height="277" x="115" y="76" mask-type="alpha" maskUnits="userSpaceOnUse"><path fill="#404040" d="M566.795 76.0288H124.842C119.604 76.0288 115.358 80.27 115.358 85.5018V343.167C115.358 348.399 119.604 
352.64 124.842 352.64H566.795C572.033 352.64 576.279 348.399 576.279 343.167V85.5018C576.279 80.27 572.033 76.0288 566.795 76.0288Z"/></mask><g mask="url(#mask0)"><path fill="#EEE" d="M583.866 102.553H115.358V365.902H583.866V102.553Z"/><path fill="#fff" d="M523.169 184.021H187.436C185.341 184.021 183.643 185.717 183.643 187.81C183.643 189.903 185.341 191.599 187.436 191.599H523.169C525.264 191.599 526.962 189.903 526.962 187.81C526.962 185.717 525.264 184.021 523.169 184.021Z"/><path fill="#fff" d="M394.187 201.072H187.436C185.341 201.072 183.643 202.769 183.643 204.861C183.643 206.954 185.341 208.651 187.436 208.651H394.187C396.282 208.651 397.98 206.954 397.98 204.861C397.98 202.769 396.282 201.072 394.187 201.072Z"/><path fill="#fff" d="M274.689 149.918H187.436C185.341 149.918 183.643 151.615 183.643 153.707C183.643 155.8 185.341 157.497 187.436 157.497H274.689C276.784 157.497 278.482 155.8 278.482 153.707C278.482 151.615 276.784 149.918 274.689 149.918Z"/><path fill="#fff" d="M210.198 115.815H149.5C147.405 115.815 145.707 117.512 145.707 119.605C145.707 121.697 147.405 123.394 149.5 123.394H210.198C212.293 123.394 213.991 121.697 213.991 119.605C213.991 117.512 212.293 115.815 210.198 115.815Z"/><path fill="#F8F8F8" d="M132.429 119.605C132.429 117.512 130.731 115.815 128.636 115.815C126.54 115.815 124.842 117.512 124.842 119.605C124.842 121.697 126.54 123.394 128.636 123.394C130.731 123.394 132.429 121.697 132.429 119.605Z"/><path fill="#F8F8F8" 
d="M132.429 136.656C132.429 134.563 130.731 132.867 128.636 132.867C126.54 132.867 124.842 134.563 124.842 136.656C124.842 138.749 126.54 140.445 128.636 140.445C130.731 140.445 132.429 138.749 132.429 136.656Z"/><path fill="#F8F8F8" d="M132.429 153.707C132.429 151.615 130.731 149.918 128.636 149.918C126.54 149.918 124.842 151.615 124.842 153.707C124.842 155.8 126.54 157.497 128.636 157.497C130.731 
157.497 132.429 155.8 132.429 153.707Z"/><path fill="#F8F8F8" d="M132.429 170.759C132.429 168.666 130.731 166.969 128.636 166.969C126.54 166.969 124.842 168.666 124.842 170.759C124.842 172.851 126.54 174.548 128.636 174.548C130.731 174.548 132.429 172.851 132.429 170.759Z"/><path fill="#F8F8F8" d="M132.429 189.705C132.429 187.612 130.731 185.916 128.636 185.916C126.54 185.916 124.842 187.612 124.842 189.705C124.842 191.797 126.54 193.494 128.636 193.494C130.731 193.494 132.429 191.797 132.429 189.705Z"/><path fill="#F8F8F8" d="M132.429 204.861C132.429 202.769 130.731 201.072 128.636 201.072C126.54 201.072 124.842 202.769 124.842 204.861C124.842 206.954 126.54 208.651 128.636 208.651C130.731 208.651 132.429 206.954 132.429 204.861Z"/><path fill="#F8F8F8" d="M132.429 221.913C132.429 219.82 130.731 218.124 128.636 218.124C126.54 218.124 124.842 219.82 124.842 221.913C124.842 224.005 126.54 225.702 128.636 225.702C130.731 225.702 132.429 224.005 132.429 221.913Z"/><path fill="#F8F8F8" d="M132.429 238.964C132.429 236.872 130.731 235.175 128.636 235.175C126.54 235.175 124.842 236.872 124.842 238.964C124.842 241.057 126.54 242.753 128.636 242.753C130.731 242.753 132.429 241.057 132.429 238.964Z"/><path fill="#fff" d="M523.169 166.969H187.436C185.341 166.969 183.643 168.666 183.643 170.759C183.643 172.851 185.341 174.548 187.436 174.548H523.169C525.264 174.548 526.962 172.851 526.962 170.759C526.962 168.666 525.264 166.969 523.169 166.969Z"/><path fill="#fff" d="M208.301 235.175H149.5C147.405 235.175 145.707 236.872 145.707 238.964C145.707 241.057 147.405 242.753 149.5 242.753H208.301C210.396 242.753 212.094 241.057 212.094 238.964C212.094 236.872 210.396 235.175 208.301 235.175Z"/><path fill="#fff" d="M335.386 218.124H168.468C166.373 218.124 164.675 219.82 164.675 221.913C164.675 224.005 166.373 225.702 168.468 225.702H335.386C337.481 225.702 339.18 224.005 339.18 221.913C339.18 219.82 337.481 218.124 335.386 218.124Z"/><path fill="#fff" d="M246.237 132.867H168.468C166.373 132.867 164.675 134.563 164.675 136.656C164.675 138.749 166.373 140.445 168.468 140.445H246.237C248.332 140.445 250.03 138.749 250.03 136.656C250.03 134.563 248.332 132.867 246.237 132.867Z"/><path fill="#D9D9D9" d="M128.636 93.0771C130.731 93.0771 132.429 91.3813 132.429 89.2894C132.429 87.1975 130.731 85.5017 128.636 85.5017C126.54 85.5017 124.842 87.1975 124.842 89.2894C124.842 91.3813 126.54 93.0771 128.636 93.0771Z" opacity=".4"/><path fill="#D9D9D9" d="M142.12 93.0771C144.215 93.0771 145.913 91.3813 145.913 89.2894C145.913 87.1975 144.215 85.5017 142.12 85.5017C140.025 85.5017 138.326 87.1975 138.326 89.2894C138.326 91.3813 140.025 93.0771 142.12 93.0771Z" opacity=".4"/><path fill="#D9D9D9" d="M155.191 93.0771C157.286 93.0771 158.984 91.3813 158.984 89.2894C158.984 87.1975 157.286 85.5017 155.191 85.5017C153.096 85.5017 151.397 87.1975 151.397 89.2894C151.397 91.3813 153.096 93.0771 155.191 93.0771Z" opacity=".3"/></g></g><defs><filter id="filter0_d" width="500.921" height="316.611" x="97.358" y="60.029" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dx="2" dy="4"/><feGaussianBlur stdDeviation="10"/><feColorMatrix type="matrix" values="0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/><feBlend in2="BackgroundImageFix" mode="normal" result="effect1_dropShadow"/><feBlend in="SourceGraphic" in2="effect1_dropShadow" mode="normal" result="shape"/></filter></defs></svg>
^

SyntaxError: Unexpected token '<'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.j (C:\repos\devx\node_modules\tsx\dist\cjs\index.cjs:1:920)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at TabUI (c:\repos\devx\node_modules\@backstage\core-components\dist\index.esm.js:42:31)
    at Object.<anonymous> (c:\repos\devx\node_modules\@backstage\core-components\dist\index.esm.js:7225:10)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.j (C:\repos\devx\node_modules\tsx\dist\cjs\index.cjs:1:1197)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)

Node.js v18.16.0

### 👟 Reproduction steps

yarn dev

### 📃 Provide the context for the Bug.

After recent upgrade backstage is not starting

### 🖥️ Your Environment

OS:   Windows_NT 10.0.19045 - win32/x64
node: v18.16.0
yarn: 3.4.1
cli:  0.24.0 (installed)
backstage:  1.20.2

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.4.5, 0.5.2, 0.5.7, 0.5.8
  @backstage/backend-common                                        0.18.5, 0.19.4, 0.19.8, 0.19.9
  @backstage/backend-dev-utils                                     0.1.1, 0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.5.4, 0.6.2, 0.6.6, 0.6.7
  @backstage/backend-tasks                                         0.5.11, 0.5.12, 0.5.7
  @backstage/catalog-client                                        1.4.3, 1.4.5, 1.4.6
  @backstage/catalog-model                                         1.4.1, 1.4.3
  @backstage/cli-common                                            0.1.12, 0.1.13
  @backstage/cli-node                                              0.1.3, 0.1.5, 0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.2, 1.4.0, 1.5.3
  @backstage/config                                                1.1.1, 1.0.8
  @backstage/core-app-api                                          1.11.1, 1.9.1
  @backstage/core-components                                       0.12.5, 0.13.4, 0.13.6, 0.13.8
  @backstage/core-plugin-api                                       1.5.3, 1.7.0, 1.8.0
  @backstage/dev-utils                                             1.0.23
  @backstage/errors                                                1.2.1, 1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.7, 0.1.5, 0.1.8
  @backstage/integration-react                                     1.1.20, 1.1.21
  @backstage/integration                                           1.6.2, 1.7.1, 1.7.2
  @backstage/plugin-adobe-analytics                                0.0.0-use.local
  @backstage/plugin-api-docs                                       0.10.0
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.2.19, 0.4.0, 0.4.1
  @backstage/plugin-authorization-backend                          0.0.0-use.local
  @backstage/plugin-authorization-common-backend                   0.0.0-use.local
  @backstage/plugin-authorization                                  0.0.0-use.local
  @backstage/plugin-catalog-backend-module-ldap                    0.5.22
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.14
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.15, 1.0.17, 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.0
  @backstage/plugin-catalog-import                                 0.10.2
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.8.3, 1.8.5, 1.9.0
  @backstage/plugin-catalog                                        1.15.0
  @backstage/plugin-cost-insights-common                           0.1.2
  @backstage/plugin-cost-insights                                  0.12.15
  @backstage/plugin-dynatrace                                      8.0.0
  @backstage/plugin-entity-feedback-backend                        0.2.4
  @backstage/plugin-entity-feedback-common                         0.1.3
  @backstage/plugin-entity-feedback                                0.2.9
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-github-actions                                 0.6.7
  @backstage/plugin-home-react                                     0.1.2, 0.1.5
  @backstage/plugin-home                                           0.5.10, 0.5.7
  @backstage/plugin-jenkins-backend                                0.3.1
  @backstage/plugin-jenkins-common                                 0.1.21
  @backstage/plugin-jenkins                                        0.9.1
  @backstage/plugin-org                                            0.6.16
  @backstage/plugin-permission-backend                             0.5.30
  @backstage/plugin-permission-common                              0.7.10, 0.7.7, 0.7.9
  @backstage/plugin-permission-node                                0.7.13, 0.7.17, 0.7.18
  @backstage/plugin-permission-react                               0.4.14, 0.4.16, 0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.0, 1.4.2, 1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.5.6, 1.6.0
  @backstage/plugin-scaffolder                                     1.15.1, 1.16.0
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-elasticsearch            1.3.10
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-stack-overflow-collator  0.1.0
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.5, 1.2.7, 1.2.8
  @backstage/plugin-search-react                                   1.6.4, 1.7.3
  @backstage/plugin-search                                         1.4.2
  @backstage/plugin-session-manager-backend                        0.0.0-use.local
  @backstage/plugin-shortcuts                                      0.0.0-use.local
  @backstage/plugin-sonarqube-backend                              0.2.9
  @backstage/plugin-sonarqube-react                                0.1.10
  @backstage/plugin-sonarqube                                      0.7.8
  @backstage/plugin-stack-overflow-backend                         0.2.11
  @backstage/plugin-stack-overflow                                 0.1.22
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.39
  @backstage/plugin-tech-insights-backend                          0.5.21
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.4.13
  @backstage/plugin-tech-insights                                  0.3.18
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.0
  @backstage/plugin-todo-backend                                   0.3.5
  @backstage/plugin-todo                                           0.2.30
  @backstage/plugin-user-settings                                  0.7.12
  @backstage/plugin-user-tracking-backend                          0.0.0-use.local
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.2.19, 0.3.0, 0.4.1, 0.4.3, 0.4.4
  @backstage/types                                                 1.1.0, 1.1.1
  @backstage/version-bridge                                        1.0.4, 1.0.6, 1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Looks like you've got a dependency on a frontend package from a backend package somewhere by mistake. You could start by running `yarn why @backstage\core-components` to see if there are any obvious backend packages in the list and remove those dependencies.

**Comment by TechHoops** [comment]
It indeed, thanks a lot for your quick response!!

**Comment by Vity01** [comment]
for not only (future) me: in my case there was an import of plugin-catalog from the backend-plugin (with no package.json dependency).
