### ISSUE TITLE
🐛 Bug Report: EntityRefLinks component hangs when rendering too many entity links

### ISSUE THREAD

**Issue by stanislav-c** [backstage/backstage#21684]
### 📜 Description

In cases when a group contains too many children application freezes the browser while trying to render all child relations as entity ref links.

### 👍 Expected behavior

App should remain responsive.

### 👎 Actual Behavior with Screenshots

Application hangs when there are too many child entities. React eventually manages to render all refs after a while. However, page performance suffers drastically as browser copes with rendering all those elements. It is arguable if there is a value of rendering a seemingly endless `GroupProfileCard` that lists all the refs. Perhaps it would be better to only render the first dozen followed by "there are N more child references in this group..." text at the end.

### 👟 Reproduction steps

Simulate a group entity referring to a few hundred children (users or other groups). This can be a common issue in large organizations.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Makes sense. Making these paginated (both in the frontend UI and in the backend requests) would make sense. Are you able to submit a fix for that? 🙏
