### ISSUE TITLE
🚀 Feature: migrate from `webpack` to `rspack`

### ISSUE THREAD

**Issue by JounQin** [backstage/backstage#21682]
### 🔖 Feature description

https://www.rspack.dev

`Rspack` is

> A fast Rust-based web bundler
> Build a high-performance frontend toolchain

### 🎤 Context

`rspack` is much faster then `webpack` and it is compatible to migrate smoothly, at least that's what they claim.

### ✌️ Possible Implementation

N/A

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
If someone goes through the effort and posts a PR with timing results, it'd be interesting to see. But no promises that it'll be accepted :)

**Comment by JounQin** [comment]
I'd like to work on this.

**Comment by tudi2d** [comment]
We are trying out Vite already to replace some parts of our Webpack build pipeline. We would not be able to promise you, that we would actually want to ship `rspack`. Changing the build tool can be quite a big effort. If you want to work on this regardless you are free to do so.

**Comment by JounQin** [comment]
ping

I'll work on this soon.

**Comment by JounQin** [comment]
@freben @tudi2d 

Please help to review #22698

**Comment by Flexicon** [comment]
Would be really great to see this implemented!

@Rugvip - it looks like the above PR by @JounQin  was unfortunately overlooked thus far. Any chance you or another maintainer of Backstage could take a look? 🙏🏻

**Comment by awanlin** [comment]
I'm not a maintainer but fairly active and this is what I know. There's a lot of work being done around auth and a few other things that are keeping the core team pretty busy. Getting this after that work is probably the plan as this could have a large impact. It's just going to take time for them to get to it.

**Comment by Flexicon** [comment]
Thanks for the insight @awanlin - makes perfect sense.

**Comment by Rugvip** [comment]
@Flexicon it's actually stale from the author side. We discussed it in a SIG meeting and settled on adding experimental support behind a flag and optional peer dependencies. This is now waiting for a contribution to add that.

**Comment by awanlin** [comment]
Thanks @Rugvip, I thought there had been some discussions on this 👍

**Comment by JounQin** [comment]
I'm stuck on business work these days and will be back soon.

**Comment by JounQin** [comment]
ping

**Comment by JounQin** [comment]
Sorry I'm extremely late here, please help to review #25953.

**Comment by drodil** [comment]
Interesting. Are there any measurements of how much faster it is in this project?
