### ISSUE TITLE
🚀 Feature: Export model types of client generated from OpenAPI spec 

### ISSUE THREAD

**Issue by taras** [backstage/backstage#21699]
### 🔖 Feature description

What do you think about exporting the types for the generated models the same way we export the APIs so we can do `export * from './generated'` or at least `export { MyModel } from './generated'`

### 🎤 Context

Types of generated models are useful when writing components that consume these types. 

Currently, we only export the API client but not its types, which makes it difficult to type the presentation components that render these types. We can manually write types for the models, but that's potentially a lot of tedious work.

### ✌️ Possible Implementation

We'd need to update the template to include the exports.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sennyeya** [comment]
Closed by #21700
