### ISSUE TITLE
🐛 Bug Report: Cleanup of deleted documents in postgres index

### ISSUE THREAD

**Issue by gaurav517** [backstage/backstage#21729]
### 📜 Description

Deleted question shows up in search suggestion.

### 👍 Expected behavior

- Question should not come up in search suggestions in Backstage

### 👎 Actual Behavior with Screenshots

- Question comes up in search suggestions in Backstage (even after multiple days)
![image](https://github.com/backstage/backstage/assets/15346341/7228097e-3103-453c-ad72-6a7372d05986)

### 👟 Reproduction steps

- Delete a question from Qeta plugin
- Question still comes up in search suggestions in Backstage (even after multiple days)
- As per Qeta plugin, its related to postgres index cleanup. [issue](https://github.com/drodil/backstage-plugin-qeta/issues/107)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
I'll just note first that the pg documents store for the search plugin is a community maintained one. But I looked into it a bit:

[Tests indicate](https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-pg/src/database/DatabaseDocumentStore.test.ts#L638) that it indeed is expected to delete documents that no longer exist in the next run. As far as I know we haven't had any reports of this failing before at least.

But it seems that [the deletion is based on hashes](https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-pg/src/database/DatabaseDocumentStore.ts#L120) of the documents. Could it be that these documents actually change every single time for some reason? For example, is there an always-advancing timestamp inside it or something like that?

Pinging @backstage/discoverability-maintainers to perhaps continue on this one

**Comment by emmaindal** [comment]
Hello @gaurav517, thanks for opening the issue. And thanks for looking into it @freben. 

As @freben mentioned the pg search module is community maintained so we will not be able to pick this ticket up for now. However I'll add a "help wanted" label to it as it seems to at least need some investigation based on what @freben mentions above. 

@freben any chance you can clarify what you mean by "Could it be that these documents actually change every single time for some reason?"?

**Comment by freben** [comment]
> @freben any chance you can clarify what you mean by "Could it be that these documents actually change every single time for some reason?"?

Yeah I was wondering if it could be the case, that first an ingestion happens where the document had hash A, but the next ingestion the (from the user's point of view) same document had hash B. And then no deletion happens for A since the hash has changed for something that actually should have been considered the same document.

Maybe this doesn't apply here though 🤔 Mostly thinking out loud. Ideally A should have been deleted then, and if the original issue was that a deletion of remote data happened, then there shouldn't exist any B to replace it either. So I am probably following the wrong train of thought here.
