### ISSUE TITLE
🐛 Bug Report: Unit test failures on techdocs add-on plugin when using @backstage/plugin-techdocs-addons-test-utils package after upgrading to v1.20.3

### ISSUE THREAD

**Issue by darrenyung** [backstage/backstage#21734]
### 📜 Description

I have existing unit tests that seems to be failing after the upgrade, after removing custom add ons and only to run the bare minimum, error still persists.

### 👍 Expected behavior

Unit test passes

### 👎 Actual Behavior with Screenshots

```
A <Route> is only ever to be used as the child of <Routes> element, never rendered directly. Please wrap your <Route> in a <Routes>.

      26 |     const { getByText } = await TechDocsAddonTester.buildAddonsInTechDocs([])
      27 |       .withDom(<body>TEST_CONTENT</body>)
    > 28 |       .renderWithEffects();
         |        ^
      29 |
      30 |     expect(getByText('TEST_CONTENT')).toBeInTheDocument();
      31 |   });

      at Object.invariant [as UNSAFE_invariant] (../../../node_modules/@remix-run/router/dist/router.cjs.js:315:11)
      at UNSAFE_invariant (../../../node_modules/@backstage/plugin-techdocs-addons-test-utils/node_modules/react-router/dist/umd/react-router.development.js:1061:12)
      at renderWithHooks (../../../node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at mountIndeterminateComponent (../../../node_modules/react-dom/cjs/react-dom.development.js:17811:13)
      at beginWork (../../../node_modules/react-dom/cjs/react-dom.development.js:19049:16)
      at HTMLUnknownElement.callCallback (../../../node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (../../../node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (../../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
      at invokeEventListeners (../../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
      at HTMLUnknownElementImpl._dispatch (../../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
      at HTMLUnknownElementImpl.dispatchEvent (../../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
      at HTMLUnknownElement.dispatchEvent (../../../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
      at Object.invokeGuardedCallbackDev (../../../node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (../../../node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at beginWork$1 (../../../node_modules/react-dom/cjs/react-dom.development.js:23964:7)
      at performUnitOfWork (../../../node_modules/react-dom/cjs/react-dom.development.js:22779:12)
      at workLoopSync (../../../node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (../../../node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (../../../node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at scheduleUpdateOnFiber (../../../node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (../../../node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at ../../../node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (../../../node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (../../../node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (../../../node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at render (../../../node_modules/@backstage/plugin-techdocs-addons-test-utils/node_modules/@testing-library/react/dist/pure.js:101:25)
      at batchedUpdates$1 (../../../node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (../../../node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (../../../node_modules/@backstage/plugin-techdocs-addons-test-utils/node_modules/@testing-library/react/dist/pure.js:97:24)
      at ../../../node_modules/@backstage/plugin-techdocs-addons-test-utils/dist/index.esm.js:179:13
      at batchedUpdates$1 (../../../node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (../../../node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at TechDocsAddonTester.renderWithEffects (../../../node_modules/@backstage/plugin-techdocs-addons-test-utils/dist/index.esm.js:178:14)
      at Object.renderWithEffects (Mermaid/Mermaid.test.tsx:28:8)
```

### 👟 Reproduction steps

- Upgrade backstage according to [guide](https://backstage.io/docs/getting-started/keeping-backstage-updated/)
- Create unit test using current  @backstage/plugin-techdocs-addons-test-utils package
- Run the test
- Observe error

### 📃 Provide the context for the Bug.

We have a gatekeeper check for unit tests in our CI pipeline before every code merge. It is currently failing

### 🖥️ Your Environment

OS:   Darwin 23.1.0 - darwin/x64
node: v18.17.1
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.20.3

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8
  @backstage/backend-common                                        0.19.9
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/backend-test-utils                                    0.2.8
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.11.2, 0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/dev-utils                                             1.0.24
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-api-docs                                       0.10.1
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.2.19, 0.4.1
  @backstage/plugin-badges-backend                                 0.3.4
  @backstage/plugin-badges                                         0.2.51
  @backstage/plugin-bazaar-backend                                 0.3.5
  @backstage/plugin-bazaar                                         0.2.19
  @backstage/plugin-catalog-backend-module-github                  0.4.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.1
  @backstage/plugin-catalog-import                                 0.10.3
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.9.1
  @backstage/plugin-catalog-unprocessed-entities                   0.1.5
  @backstage/plugin-catalog                                        1.15.1
  @backstage/plugin-cost-insights-common                           0.1.2
  @backstage/plugin-cost-insights                                  0.12.16
  @backstage/plugin-devtools-backend                               0.2.4
  @backstage/plugin-devtools-common                                0.1.6
  @backstage/plugin-devtools                                       0.1.6
  @backstage/plugin-entity-validation                              0.1.12
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.33
  @backstage/plugin-explore                                        0.4.13
  @backstage/plugin-github-actions                                 0.6.8
  @backstage/plugin-github-issues                                  0.2.16
  @backstage/plugin-github-pull-requests-board                     0.1.21
  @backstage/plugin-home-react                                     0.1.5
  @backstage/plugin-home                                           0.5.11
  @backstage/plugin-kubernetes-backend                             0.13.1
  @backstage/plugin-kubernetes-common                              0.7.1
  @backstage/plugin-kubernetes-node                                0.1.1
  @backstage/plugin-kubernetes-react                               0.1.1
  @backstage/plugin-kubernetes                                     0.11.2
  @backstage/plugin-org                                            0.6.17
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-playlist-backend                               0.3.11
  @backstage/plugin-playlist-common                                0.1.12
  @backstage/plugin-playlist                                       0.2.1
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.1
  @backstage/plugin-scaffolder                                     1.16.1
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-elasticsearch            1.3.10
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.3
  @backstage/plugin-shortcuts                                      0.3.16
  @backstage/plugin-sonarqube-backend                              0.2.9
  @backstage/plugin-sonarqube-react                                0.1.10
  @backstage/plugin-sonarqube                                      0.7.9
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.39
  @backstage/plugin-tech-insights-backend                          0.5.21
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.4.13
  @backstage/plugin-tech-insights                                  0.3.19
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-addons-test-utils                     1.0.24
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.1
  @backstage/plugin-todo-backend                                   0.3.5
  @backstage/plugin-todo                                           0.2.31
  @backstage/plugin-user-settings                                  0.7.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.2.19, 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 3.95s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by darrenyung** [comment]
As per release [notes](https://github.com/backstage/backstage/releases/tag/v1.20.3), it was advised to **Move testing-library/react to peerDependencies to fix incompatibility with React 17**, so I did but error still persists. Here is my config in the techdocs plugin

```
"dependencies": {
    "@backstage/core-components": "^0.13.8",
    "@backstage/core-plugin-api": "^1.8.0",
    "@backstage/plugin-techdocs-react": "^1.1.13",
    "@backstage/theme": "^0.4.4",
    "@material-ui/core": "^4.12.2",
    "@material-ui/icons": "^4.11.3",
    "@material-ui/lab": "4.0.0-alpha.57",
    "mermaid": "^10.3.0",
    "react-use": "^17.2.4"
  },
  "peerDependencies": {
    "react": "^16.13.1 || ^17.0.0",
    "@testing-library/react": "^12.1.3"
  },
  "devDependencies": {
    "@backstage/cli": "^0.24.0",
    "@backstage/core-app-api": "^1.11.1",
    "@backstage/dev-utils": "^1.0.24",
    "@backstage/plugin-techdocs-addons-test-utils": "^1.0.24",
    "@backstage/test-utils": "^1.4.5",
    "@date-io/core": "^1.3.13",
    "@svgr/core": "^6.0.0",
    "@testing-library/dom": ">=7.21.4",
    "@testing-library/jest-dom": "^5.10.1",
    "@testing-library/user-event": "^14.0.0",
    "@types/jest": "*",
    "@types/node": "*",
    "@types/react": "^17.0.0",
    "cross-fetch": "^3.1.5",
    "msw": "^0.49.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.0",
    "react-router-dom": "^6.3.0",
    "typescript": "^4.0.0"
  },
```

**Comment by Rugvip** [comment]
Also double check if you have duplicate versions of React Router, as I think that could cause this issue. What's the output of `yarn why react-router`?

**Comment by vinzscam** [comment]
it looks like you have two different versions of react-router, which might have generate the issue. Also one of the versions is `react-router@6.0.0-beta.0` which we migrated away time ago. More info to help you migrate here https://backstage.io/docs/tutorials/react-router-stable-migration and in https://backstage.github.io/upgrade-helper

**Comment by darrenyung** [comment]
Thanks @vinzscam , I did the upgrade but I'm still facing with the following

```
  ● Mermaid › renders without exploding

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

       7 |
       8 | describe('Mermaid', () => {
    >  9 |   it('renders without exploding', async () => {
         |   ^
      10 |     const { getByText } = await TechDocsAddonTester.buildAddonsInTechDocs([
      11 |       <Mermaid config={{ themeVariables: { lineColor: '#00ff00' } }} />,
      12 |     ])

      at it (Mermaid/Mermaid.test.tsx:9:3)
      at Object.describe (Mermaid/Mermaid.test.tsx:8:1)

  ● Mermaid › renders fenced code blocks

    Reached ErrorBoundaryFallback Page with error, TypeError: _a2.scrollIntoView is not a function

      28 |         </body>,
      29 |       )
    > 30 |       .renderWithEffects();
         |        ^
      31 |
      32 |     expect(getByTestId('mermaid-test')).toHaveStyle('display: none');
      33 |   });
```

Results from `yarn why react-router`

```
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "react-router"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react-router@6.21.0"
info Reasons this module exists
   - "_project_#app" depends on it
   - Hoisted from "_project_#app#react-router"
   - Hoisted from "_project_#app#react-router-dom#react-router"
info Disk size without dependencies: "828KB"
info Disk size with unique dependencies: "3.09MB"
info Disk size with transitive dependencies: "3.09MB"
info Number of shared dependencies: 1
✨  Done in 1.63s.
```
