### ISSUE TITLE
🐛 Bug Report: Version Bump fails for multiple packages

### ISSUE THREAD

**Issue by eceeeren** [backstage/backstage#21730]
### 📜 Description

Hello, I would like to update Backstage using "yarn backstage-cli versions:bump --release next"

However some of the packages are not updated:

`Running yarn install to install new versions ✔

Version bump complete!

Error: Version bump failed for @backstage/core-app-api, @backstage/plugin-catalog-backend-module-scaffolder-entity-model, @backstage/plugin-catalog-backend, @backstage/plugin-home, @backstage/plugin-home, @backstage/plugin-kubernetes, @backstage/plugin-scaffolder-backend, @backstage/plugin-search-backend-module-catalog

error Command failed with exit code 1.`

"yarn backstage-cli versions:check --fix" does not help as well.

`Error: Failed versioning check`

### 👍 Expected behavior

All of the packages should be updated accordingly or stay in their own working versions.

### 👎 Actual Behavior with Screenshots

![bump1](https://github.com/backstage/backstage/assets/23586149/64a8090b-9021-46ae-b695-29b0dd64778a)
![bump2](https://github.com/backstage/backstage/assets/23586149/3463c221-1882-402c-ba42-94d42a2f87e0)
![bump3](https://github.com/backstage/backstage/assets/23586149/bf202a98-a5e4-46ef-94bd-ef22c6c9181c)

### 👟 Reproduction steps

1. Create the project with the given packages but in an older version
2. Execute "yarn backstage-cli versions:bump --release next"

### 🖥️ Your Environment

OS:   Windows_NT 10.0.22621 - win32/x64
node: v18.18.2
yarn: 1.22.19
cli:  0.25.0-next.1 (installed)
backstage:  1.21.0-next.2

Dependencies:
  @backstage/app-defaults                                          1.4.6-next.1
  @backstage/backend-app-api                                       0.5.8, 0.5.9-next.1
  @backstage/backend-common                                        0.19.9, 0.20.0-next.1
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0, 0.1.1-next.1
  @backstage/backend-plugin-api                                    0.5.4, 0.6.7, 0.6.8-next.1
  @backstage/backend-tasks                                         0.5.12, 0.5.13-next.1
  @backstage/catalog-client                                        1.4.6, 1.5.0-next.0
  @backstage/catalog-model                                         1.4.3   
  @backstage/cli-common                                            0.1.13  
  @backstage/cli-node                                              0.2.0   
  @backstage/cli                                                   0.25.0-next.1
  @backstage/config-loader                                         1.5.3   
  @backstage/config                                                1.1.1   
  @backstage/core-app-api                                          1.11.1, 1.11.2-next.1
  @backstage/core-compat-api                                       0.0.1-next.1
  @backstage/core-components                                       0.13.8, 0.13.9-next.1
  @backstage/core-plugin-api                                       1.8.0, 1.8.1-next.1
  @backstage/errors                                                1.2.3   
  @backstage/eslint-plugin                                         0.1.4-next.0
  @backstage/frontend-plugin-api                                   0.3.0, 0.4.0-next.1
  @backstage/integration-aws-node                                  0.1.8   
  @backstage/integration-react                                     1.1.21, 1.1.22-next.1
  @backstage/integration                                           1.7.2, 1.8.0-next.1
  @backstage/plugin-api-docs                                       0.10.2-next.2
  @backstage/plugin-app-backend                                    0.3.56-next.1
  @backstage/plugin-app-node                                       0.1.8-next.1
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.0-next.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.2-next.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.5-next.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.5-next.1
  @backstage/plugin-auth-backend-module-google-provider            0.1.5-next.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.5-next.1
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.0-next.0
  @backstage/plugin-auth-backend-module-okta-provider              0.0.1-next.1
  @backstage/plugin-auth-backend                                   0.20.1-next.1
  @backstage/plugin-auth-node                                      0.2.19, 0.4.1, 0.4.2-next.1
  @backstage/plugin-azure-devops-backend                           0.5.0-next.1
  @backstage/plugin-azure-devops-common                            0.3.2-next.0
  @backstage/plugin-azure-devops                                   0.3.10-next.1
  @backstage/plugin-catalog-backend-module-github                  0.4.6-next.1
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.5-next.1
  @backstage/plugin-catalog-backend-module-openapi                 0.1.25-next.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4, 0.1.5-next.1
  @backstage/plugin-catalog-backend                                1.15.0, 1.15.1-next.1
  @backstage/plugin-catalog-common                                 1.0.18  
  @backstage/plugin-catalog-graph                                  0.3.2-next.1
  @backstage/plugin-catalog-import                                 0.10.4-next.2
  @backstage/plugin-catalog-node                                   1.5.0, 1.5.1-next.1
  @backstage/plugin-catalog-react                                  1.9.1, 1.9.2-next.1
  @backstage/plugin-catalog                                        1.16.0-next.2
  @backstage/plugin-dynatrace                                      8.0.2-next.1
  @backstage/plugin-events-node                                    0.2.16, 0.2.17-next.1
  @backstage/plugin-github-actions                                 0.6.9-next.1
  @backstage/plugin-github-issues                                  0.2.17-next.1
  @backstage/plugin-home-react                                     0.1.5, 0.1.6-next.1
  @backstage/plugin-home                                           0.5.11, 0.6.0-next.1
  @backstage/plugin-jenkins-backend                                0.3.2-next.1
  @backstage/plugin-jenkins-common                                 0.1.21  
  @backstage/plugin-jenkins                                        0.9.3-next.1
  @backstage/plugin-kubernetes-backend                             0.14.0-next.1
  @backstage/plugin-kubernetes-common                              0.6.6, 0.7.2-next.1
  @backstage/plugin-kubernetes-node                                0.1.2-next.1
  @backstage/plugin-kubernetes-react                               0.1.2-next.1
  @backstage/plugin-kubernetes                                     0.11.3-next.1, 0.9.3
  @backstage/plugin-lighthouse-common                              0.1.4   
  @backstage/plugin-lighthouse                                     0.4.13-next.1
  @backstage/plugin-org                                            0.6.18-next.1
  @backstage/plugin-pagerduty                                      0.7.0-next.1
  @backstage/plugin-permission-backend                             0.5.31-next.1
  @backstage/plugin-permission-common                              0.7.10  
  @backstage/plugin-permission-node                                0.7.18, 0.7.19-next.1
  @backstage/plugin-permission-react                               0.4.17, 0.4.18-next.1
  @backstage/plugin-proxy-backend                                  0.4.6-next.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.11-next.1
  @backstage/plugin-scaffolder-backend                             1.19.1, 1.19.2-next.1
  @backstage/plugin-scaffolder-common                              1.4.3   
  @backstage/plugin-scaffolder-node                                0.2.8, 0.2.9-next.1
  @backstage/plugin-scaffolder-react                               1.6.2-next.1
  @backstage/plugin-scaffolder                                     1.16.2-next.1
  @backstage/plugin-search-backend-module-catalog                  0.1.11, 0.1.12-next.1
  @backstage/plugin-search-backend-module-pg                       0.5.17-next.1
  @backstage/plugin-search-backend-module-techdocs                 0.1.12-next.1
  @backstage/plugin-search-backend-node                            1.2.11, 1.2.12-next.1
  @backstage/plugin-search-backend                                 1.4.8-next.1
  @backstage/plugin-search-common                                  1.2.8   
  @backstage/plugin-search-react                                   1.7.3, 1.7.4-next.1
  @backstage/plugin-search                                         1.4.4-next.2
  @backstage/plugin-sonarqube-backend                              0.2.10-next.1
  @backstage/plugin-sonarqube-react                                0.1.11-next.1
  @backstage/plugin-sonarqube                                      0.7.10-next.1
  @backstage/plugin-tech-radar                                     0.6.11-next.2
  @backstage/plugin-techdocs-backend                               1.9.1-next.1
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.3-next.1
  @backstage/plugin-techdocs-node                                  1.11.0-next.1
  @backstage/plugin-techdocs-react                                 1.1.14-next.1
  @backstage/plugin-techdocs                                       1.9.2-next.2
  @backstage/plugin-user-settings                                  0.7.14-next.2
  @backstage/release-manifests                                     0.0.11  
  @backstage/test-utils                                            1.4.6-next.1
  @backstage/theme                                                 0.4.4, 0.5.0-next.0
  @backstage/types                                                 1.1.1   
  @backstage/version-bridge                                        1.0.7  

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
It would be interesting to know why all of those duplicates are there. Could you try running `yarn why <packagename>` of for example `@backstage/theme` and `@backstage/core-app-api` to see what packages that might be pulling in conflicts?

Sometimes one can do `npx dedupe` to get rid of duplicates in the lockfile, but I think in your case it won't suffice.
