### ISSUE TITLE
GitLab catalog discovery does not stop processing when schedule timeout is reached; task is not refreshed

### ISSUE THREAD

**Issue by rcoy-v** [backstage/backstage#21743]
### 📜 Description

When using the GitLab catalog discovery, if the discovery task does not complete within the scheduled timeout, the task continues to scan GitLab. This also leads to the task being lost and a refresh never being scheduled, meaning GitLab will not be scanned again.

### 👍 Expected behavior

The GitLab discovery task would stop scanning when the timeout is reached, and schedule another refresh for the task to scan again.

### 👎 Actual Behavior with Screenshots

A warning log message shows the task timed out.

```shell
warn Task timed out and was lost: GitlabDiscoveryEntityProvider:,my-gitlab:refresh type=taskManager
```

Debug logs also show that requests to GitLab are still being made.

Once the original task has finished searching for projects, another run of the discovery task never occurs.

### 👟 Reproduction steps

Use the example catalog config for the catalog discovery:

```yaml
catalog:
  providers:
    gitlab:
      my-gitlab:
        host: my-gitlab.com
        skipForkedRepos: true
        entityFilename: catalog-info.yaml
        projectPattern: '[\s\S]*'
        schedule:
          frequency: { minutes: 2 }
          timeout: { seconds: 1 }
```

Configure the schedule and target host to scan something such that, it will not be able to fully complete before the timeout.

### 📃 Provide the context for the Bug.

I'm not sure if this is the right direction, but the [GitlabDiscoveryEntityProvider](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-gitlab/src/providers/GitlabDiscoveryEntityProvider.ts#L126) does not appear to utilize the abort signal from the [TaskWorker](https://github.com/backstage/backstage/blob/master/packages/backend-tasks/src/tasks/TaskWorker.ts#L155). It seems like the [PluginTaskSchedulerJanitor](https://github.com/backstage/backstage/blob/master/packages/backend-tasks/src/tasks/PluginTaskSchedulerJanitor.ts#L54) clears information from the task, including the `current_run_ticket`. This may be affecting the [release of the task by the TaskWorker](https://github.com/backstage/backstage/blob/master/packages/backend-tasks/src/tasks/TaskWorker.ts#L353).

When checking for that signal with [these changes](https://github.com/backstage/backstage/compare/master...rcoy-v:backstage:gitlab-task-lost), the task stops scanning GitLab once the timeout is reached. As well, I can see a debug log for the task refresh now occuring, which eventually leads to a new task run.

```shell
debug task: GitlabDiscoveryEntityProvider:my-gitlab:refresh will next occur around 2023-12-05T16:20:47.563-06:00 type=taskManager task=GitlabDiscoveryEntityProvider:my-gitlab:refresh
```

I'm not sure if this is the right direction, because looking at other providers, such as Azure DevOps, BitBucket, and GitHub, none of them utilize the abort signal either.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
The task scheduler is a standalone library functionality that doesn't directly affect the scheduled work. All it does is to provide an `AbortSignal` that the scheduled work can choose to react to, or not. The reason for this is that in Node, we can't really pre-empt work or kill a thread or similar. Well, unless we start going into workers and stuff, but it's still often not desirable since it can leave external effects half-done etc.

https://github.com/backstage/backstage/blob/master/packages/backend-tasks/src/tasks/types.ts#L31

What's needed here is probably to add the feature of abortability to that provider., such that it properly reacts when the abort signal triggers. Adding a help wanted label.

**Comment by freben** [comment]
Yep, pretty much.
