### ISSUE TITLE
🐛 Bug Report: Config injected to the frontend by the backend should be updated when refreshing the frontend browser.

### ISSUE THREAD

**Issue by davidfestal** [backstage/backstage#21768]
### 📜 Description

The configuration injected in a Javascript asset when service the frontend from the backend, is never updated on the frontend side (even when refresing the browser), because the javascript assets in which the Config is injected in cached 	indefinitely.
When using dynamic plugins and adding additional configuration at runtime, even a restart of the backend application will not provide the new config to the frontend, because the javascript assets are not changed, since no recompilation occured.

### 👍 Expected behavior

We should not aggressively cache the Javascript asset that includes configuration injected from the backend.

### 👎 Actual Behavior with Screenshots

The Javascript asset containing the injected config is cached like the others assets, and this prevents receiving the updated config from the backend.

### 👟 Reproduction steps

- Start a backend application that also serves the frontend through the `app-backend` plugin
- Load the frontend application in the browser
- Add some frontend config to the configs passed to the backend application and restart the backend
- Confirm that the new frontend config value has not been updated on the browser side.

### 📃 Provide the context for the Bug.

This bug has been found when working on the dynamic plugins integration in the Janus Showcase.
The PR the fixed this as a workaround is here: https://github.com/janus-idp/backstage-showcase/pull/710.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Oh good catch! 😁

Having discussed this a bit we're thinking the best way forward is most likely to start injecting the config data into `index.html` instead. Thinking we'd use a separate `script` header element, either by assigning a global variable to using a specific script element type and parse the content. Either way we gotta eliminate any XSS risks. We'll of course also need to update the default config loader to check for this additional way of forwarding config.

Is that something you want to work on? or alternatively if you'd like to suggest a different approach

**Comment by davidfestal** [comment]
> Is that something you want to work on? or alternatively if you'd like to suggest a different approach

I won't have time to work on this soon (heading towards vacations today).

I assume that a design constraint here is related to frontend bootstrapping, and the need for the config to be available as soon as possible in the bootstrapping flow.

Any thoughs on this @tumido ?

Maybe this can be part of the discussions related to the frontend dynamic plugins that will happen in the adoption SIG WG ?

**Comment by davidfestal** [comment]
@tumido @gashcrumb What are your thoughts about this ?

**Comment by davidfestal** [comment]
@Rugvip Would you agree to assign @gashcrumb to this issue ?

**Comment by gashcrumb** [comment]
With the interim fix David provided this issue is sorted for now, however it will become relevant again when moving forward with [dynamic frontend plugins](https://github.com/backstage/backstage/issues/22423#issuecomment-1985416483).  Question is should this issue remain open to track this point?  My thought is to [update the BEP](https://github.com/backstage/backstage/tree/master/beps/0002-dynamic-frontend-plugins) with this requirement to ensure it doesn't get lost and close this issue.
