### ISSUE TITLE
🚀 Feature: [Microsite CI] Validate new plugin files have YAML extension

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#21779]
### 🔖 Feature description

When new plugins are submitted to the Plugin Directory it would be good if the Microsite CI would validate that they have the YAML file extension.

### 🎤 Context

There have been a few PRs where this was missed and then the person submitting was confused as to why their Plugin wasn't in the Plugin Directory.

Here is a recent example: https://github.com/backstage/backstage/pull/21628/files

### ✌️ Possible Implementation

All the files in this directory must be YAML files - https://github.com/backstage/backstage/tree/master/microsite/data/plugins - and it should be pretty easy to quickly validate that. Perhaps something like a not on the results of this: 

`find . \! \( -name '*.yaml' -o -name '*.yml' \)`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Yep makes sense 👍 

Looks like this got a bit trickier to implement as we no longer generate the list with a script: https://github.com/backstage/backstage/blob/ed7f5ebaca66fc4d0c7fd06986529dd39bc75bc9/microsite/src/pages/plugins/index.tsx#L18

I think it likely makes sense to introduce a script in the microsite dir that verifies the contents of `data/plugins`
