### ISSUE TITLE
🐛 Bug Report: OneLogin provider doesn't refresh token returning 401

### ISSUE THREAD

**Issue by ssliman** [backstage/backstage#21776]
### 📜 Description

Refreshing the page with the OneLogin setup, tries to log you in again.
The OneLogin provider tries to refresh the bearer token. resulting in a 401, because of a scope issue. 

### 👍 Expected behavior

The provider should handle refreshing tokens properly. The provider should allow the user to customize the scope.

### 👎 Actual Behavior with Screenshots

We've inspected the error below in our network tab when inspecting the website:

```json
{
  "error": {
    "name": "AuthenticationError",
    "message": "Refresh failed; caused by Error: Failed to refresh access token [object Object]",
    "cause": {
      "name": "Error",
      "message": "Failed to refresh access token [object Object]",
      "stack": "Error: Failed to refresh access token [object Object]\n    at /app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:526:18\n    at /app/node_modules/oauth/lib/oauth2.js:191:18\n    at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)\n    at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)\n    at IncomingMessage.emit (node:events:529:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
    }
  },
  "request": {
    "method": "GET",
    "url": "/api/auth/onelogin/refresh?optional&scope=openid%20email%20profile%20offline_access&env=development"
  },
  "response": { "statusCode": 401 }
}

```

Adding a console.log inside the file `@backstage/plugin-auth-backend/dist/index.cjs.js:526:18` gives us:

```bash
{
   statusCode: 400,
   data: '{"error":"invalid_scope","error_description":"refresh token missing requested scope","scope":"email profile offline_access"}'
}
```

### 👟 Reproduction steps

1. Setup OneLogin provider with backstage
2. Log in with your credentials
3. Inspect browsers network and filter on /refresh 
4. Refresh the page, redirects you to login page
5. 401 occurs
6. You're logged in again

### 📃 Provide the context for the Bug.

app.config.yaml

```yaml
auth:
  providers:
    onelogin:
      development:
        clientId: ${AUTH_ONELOGIN_CLIENT_ID}
        clientSecret: ${AUTH_ONELOGIN_CLIENT_SECRET}
        issuer: ${AUTH_ONELOGIN_ISSUER}
```

auth.ts

```ts
import {
  createRouter,
  defaultAuthProviderFactories,
  providers,
} from '@backstage/plugin-auth-backend';
import { Router } from 'express';

import { PluginEnvironment } from '../types';

export default async function createPlugin(env: PluginEnvironment): Promise<Router> {
  return createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      ...defaultAuthProviderFactories,
      onelogin: providers.onelogin.create({
        signIn: {
          async resolver(info, ctx) {
            const {
              profile: { email },
            } = info;
            if (!email) {
              throw new Error('User profile contained no email');
            }

            const [name] = email.split('@');

            return ctx.signInWithCatalogUser({
              entityRef: { name },
            });
          },
        },
      }),
     },
  });
}
```

### 🖥️ Your Environment

```bash
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8
  @backstage/backend-common                                        0.17.0, 0.19.9
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.2.0, 1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.12.4, 0.12.5, 0.13.8
  @backstage/core-plugin-api                                       1.0.6, 1.7.0, 1.8.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-api-docs                                       0.10.0
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.4.1
  @backstage/plugin-bitbucket-cloud-common                         0.2.14
  @backstage/plugin-catalog-backend-module-aws                     0.3.1
  @backstage/plugin-catalog-backend-module-bitbucket-cloud         0.1.22
  @backstage/plugin-catalog-backend-module-github                  0.4.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.0
  @backstage/plugin-catalog-import                                 0.10.2
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.2.1, 1.9.0, 1.9.1
  @backstage/plugin-catalog                                        1.15.0
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-github-actions                                 0.6.7
  @backstage/plugin-home-react                                     0.1.5
  @backstage/plugin-home                                           0.5.10
  @backstage/plugin-kubernetes-common                              0.7.1
  @backstage/plugin-org                                            0.6.16
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.0
  @backstage/plugin-scaffolder                                     1.16.0
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.2
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.0
  @backstage/plugin-user-settings                                  0.7.12
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.2.19, 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
I'm not super familiar with OneLogin, so this is a bit of a shot in the dark, but `offline` scope might be necessary for refreshes? Have you tried adding that scope?

**Comment by akira-personio** [comment]
Hi any update on this issue?

Having the same issue after an upgrade to backstage 1.22.2 from 1.19.3.

The [docs](https://developers.onelogin.com/openid-connect/scopes) don't seem to mention anything about the `offline` scope.

**Comment by benjdlambert** [comment]
@akira-personio the docs that you linked to mention `offline_access` scope. That's the exact scope that I think is going to help with refresh tokens. Do you provide that scope?

**Comment by akira-personio** [comment]
Hi, nope we aren't customizing the scopes at all, but it seems to be included... as we get the same error on refresh failure:

> {"statusCode":400,"data":"{\"error\":\"invalid_scope\",\"error_description\":\"refresh token missing requested scope\",\"scope\":\"email profile offline_access\"}"}

**Comment by akira-personio** [comment]
or i wonder if those scopes listed are the available scopes, not the scopes in the token... 🤔

**Comment by benjdlambert** [comment]
Hmm looks like `offline_access` is in the defualt list of scopes for `OneLogin`

**Comment by akira-personio** [comment]
when I log the refreshToken in the OneLoginProvider i get smth like:
`{"jti":"xxx","sub":"xxx","iss":"xxx,"iat":111,"exp":111,"scope":"openid","aud":"xxx"}`

**Comment by akira-personio** [comment]
The refresh token on the previous Backstage version (that works) looks pretty similar (same scope)... 😞

**Comment by akira-personio** [comment]
I do notice; however, that the refresh url is different:

old/works:
`"GET /api/auth/onelogin/refresh?optional&env=local HTTP/1.1" 200`

new/doesn't work:
`"GET /api/auth/onelogin/refresh?optional&scope=openid%20email%20profile%20offline_access&env=local HTTP/1.1" 401`

**Comment by benjdlambert** [comment]
@akira-personio hmm, well this is interesting. 

Looking at the diff for the two versions theres, not really much thats changed in the `auth-backend` apart from the Microsoft auth provider: https://github.com/backstage/backstage/compare/v1.22.2...v1.19.3

**Comment by akira-personio** [comment]
ok, thanks for sticking with me... for what it's worth... the refresh for onelogin appears to work if i remove the scope var entirely from:
https://github.com/backstage/backstage/blob/v1.22.2/plugins/auth-backend/src/lib/passport/PassportStrategyHelper.ts#L165

the url doesn't seem to matter, but it's could be generated from the contents of the scope var which is different now

**Comment by benjdlambert** [comment]
Hmm ok - I'm gonna bring in @Rugvip to this too, he might have some ideas, but it's good that you've found something that at least works so we can investigate this a little more.

**Comment by Rugvip** [comment]
@akira-personio, hmm, the old behaviour actually seems a bit strange, I'd expect the scopes to be present in the refresh call, and especially not cause any issues. Do you know if the same scopes are present during the initial login?

Something to try out would be to override the default onelogin provider API in the frontend with one that sets a different set of default scopes, in case either of those scopes are causing trouble. Something like this but with your own `defaultScopes` option passed to `OneLoginAuth.create` in `packages/app/src/apis.ts`: https://github.com/backstage/backstage/blob/05e6b8389703b7795fb25483ae1f3af1fa6a66f6/packages/app-defaults/src/defaults/apis.ts#L202-L216

**Comment by akira-personio** [comment]
Hi @Rugvip ... 
I'm not sure about the initial login, but In [start](https://github.com/backstage/backstage/blob/v1.22.2/plugins/auth-backend/src/providers/onelogin/provider.ts#L102) method we appear to be using a single hard-coded scope of 'openid'.
(login appears to fail, if this is changed to req.scope)

If I modify the scope var in the [executeRefreshTokenStrategy](https://github.com/backstage/backstage/blob/v1.22.2/plugins/auth-backend/src/lib/passport/PassportStrategyHelper.ts#L165) to 'openid', it seems to work, tho.

Will take a look at ur example and see if that works...

**Comment by akira-personio** [comment]
Yup, changing the defaultScopes to ["openid"] in the OAuth2.create seems to work... unfortunately, the options in the OneLoginAuth.create don't allow for that 😢

**Comment by Rugvip** [comment]
Yeah kind looks like we'll just want to hardcode [this](https://github.com/backstage/backstage/blob/a291688bc58ace6423b92b8a2e5d1d7cf2dbc015/plugins/auth-backend/src/providers/onelogin/provider.ts#L124) to just be `'openid'` tbh, to mirror the behavior in the `start` method. On the frontend we can then simply remove the scopes altogether, since they'll be ignored anyway.

**Comment by manuelfalcon** [comment]
hey team we are having same issue, is there any ongoing work to fix this? what is the temporal fix you are using? Thanks

**Comment by manuelfalcon** [comment]
Solved in https://github.com/backstage/backstage/pull/23582
