### ISSUE TITLE
🐛 Bug Report: Scaffolder Permissions Framework

### ISSUE THREAD

**Issue by darrenyung** [backstage/backstage#21786]
### 📜 Description

Apologies in advanced if I'm suppose to split it into 2 issues. Happy to be told otherwise. I'm trying to lockdown the **publish:github** and **publish:github:pull-request** action where it requires user token property in the action input. I tried implementing the permissions but I encountered 2 issues.

### 👍 Expected behavior

1. Print a friendly error message if a legitimate permission is denied when the permission rules says so and not technical information which is not useful for a non-tech user of Backstage. Sensitive information like tokens should be masked.
2. Is value expected when using scaffolderActionConditions.hasStringProperty()? I'm trying to enforce a token is required when using **publish:github:pull-request** action, I can't set the value since the token is randomized. If not, it should work and deny the user from executing since the token property is not defined in the action input?

### 👎 Actual Behavior with Screenshots

Issue 1

```
32023-12-08T10:24:14.000Z NotAllowedError: Unauthorized action: publish:github:pull-request. The action is not allowed. Input: {14  "repoUrl": "github.com, Opens in a new window?owner=xx&repo=backstage-test",15  "token": "xxx",16  "title": "Create base files required for Backstage TechDocs",17  "branchName": "create-base-techdocs-a",18  "update": true,19  "description": "Base files to start a documentation for Backstage\n"20}
```

Issue 2

```
122023-12-08T10:03:35.000Z Beginning step Publish132023-12-08T10:03:35.000Z InputError: Parameters to rule are invalid; caused by [14  {15    "code": "invalid_type",16    "expected": "string",17    "received": "undefined",18    "path": [19      "value"20    ],21    "message": "Required"22  }23]
```

### 👟 Reproduction steps

1. Enable Scaffolder permission framework
2. Create the following permission

To generate output reflected in Issue 1
``` 
if (isPermission(request.permission, actionExecutePermission)) {
      return createScaffolderActionConditionalDecision(request.permission, {
        not: {
          allOf: [
            scaffolderActionConditions.hasActionId({
              actionId: 'publish:github:pull-request',
            }),
          ],
        },
      });
    }
```

To generate output reflected in Issue 2

```
   if (isPermission(request.permission, actionExecutePermission)) {
      return createScaffolderActionConditionalDecision(request.permission, {
        not: {
          allOf: [
            scaffolderActionConditions.hasActionId({
              actionId: 'publish:github:pull-request',
            }),
            scaffolderActionConditions.hasStringProperty({
              key: 'token',
            }),
          ],
        },
      });
    }
```

### 📃 Provide the context for the Bug.

1. Verbose error printed out and if the token is part of the action, it is printed in plaintext.
2. The **scaffolderActionConditions.hasStringProperty** property expects a KeyVal pair but with the Val allowed to be nullable. However, an error happens at runtime because the value of the key is undefined. 

### 🖥️ Your Environment

OS: Darwin 23.1.0 - darwin/x64
node: v18.17.1
yarn: 1.22.19
cli: 0.24.0 (installed)
backstage: 1.20.3

Dependencies:
@backstage/app-defaults 1.4.5
@backstage/backend-app-api 0.5.8
@backstage/backend-common 0.19.9
@backstage/backend-dev-utils 0.1.2
@backstage/backend-openapi-utils 0.1.0
@backstage/backend-plugin-api 0.6.7
@backstage/backend-tasks 0.5.12
@backstage/backend-test-utils 0.2.8
@backstage/catalog-client 1.4.6
@backstage/catalog-model 1.4.3
@backstage/cli-common 0.1.13
@backstage/cli-node 0.2.0
@backstage/cli 0.24.0
@backstage/config-loader 1.5.3
@backstage/config 1.1.1
@backstage/core-app-api 1.11.1
@backstage/core-components 0.11.2, 0.13.8
@backstage/core-plugin-api 1.8.0
@backstage/dev-utils 1.0.24
@backstage/errors 1.2.3
@backstage/eslint-plugin 0.1.3
@backstage/frontend-plugin-api 0.3.0
@backstage/integration-aws-node 0.1.8
@backstage/integration-react 1.1.21
@backstage/integration 1.7.2
@backstage/plugin-api-docs 0.10.1
@backstage/plugin-app-backend 0.3.55
@backstage/plugin-app-node 0.1.7
@backstage/plugin-auth-backend-module-gcp-iap-provider 0.2.1
@backstage/plugin-auth-backend-module-github-provider 0.1.4
@backstage/plugin-auth-backend-module-gitlab-provider 0.1.4
@backstage/plugin-auth-backend-module-google-provider 0.1.4
@backstage/plugin-auth-backend-module-oauth2-provider 0.1.4
@backstage/plugin-auth-backend 0.20.0
@backstage/plugin-auth-node 0.2.19, 0.4.1
@backstage/plugin-badges-backend 0.3.4
@backstage/plugin-badges 0.2.51
@backstage/plugin-bazaar-backend 0.3.5
@backstage/plugin-bazaar 0.2.19
@backstage/plugin-catalog-backend-module-github 0.4.5
@backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
@backstage/plugin-catalog-backend-module-unprocessed 0.3.4
@backstage/plugin-catalog-backend 1.15.0
@backstage/plugin-catalog-common 1.0.18
@backstage/plugin-catalog-graph 0.3.1
@backstage/plugin-catalog-import 0.10.3
@backstage/plugin-catalog-node 1.5.0
@backstage/plugin-catalog-react 1.9.1
@backstage/plugin-catalog-unprocessed-entities 0.1.5
@backstage/plugin-catalog 1.15.1
@backstage/plugin-cost-insights-common 0.1.2
@backstage/plugin-cost-insights 0.12.16
@backstage/plugin-devtools-backend 0.2.4
@backstage/plugin-devtools-common 0.1.6
@backstage/plugin-devtools 0.1.6
@backstage/plugin-entity-validation 0.1.12
@backstage/plugin-events-node 0.2.16
@backstage/plugin-explore-common 0.0.2
@backstage/plugin-explore-react 0.0.33
@backstage/plugin-explore 0.4.13
@backstage/plugin-github-actions 0.6.8
@backstage/plugin-github-issues 0.2.16
@backstage/plugin-github-pull-requests-board 0.1.21
@backstage/plugin-home-react 0.1.5
@backstage/plugin-home 0.5.11
@backstage/plugin-kubernetes-backend 0.13.1
@backstage/plugin-kubernetes-common 0.7.1
@backstage/plugin-kubernetes-node 0.1.1
@backstage/plugin-kubernetes-react 0.1.1
@backstage/plugin-kubernetes 0.11.2
@backstage/plugin-org 0.6.17
@backstage/plugin-permission-common 0.7.10
@backstage/plugin-permission-node 0.7.18
@backstage/plugin-permission-react 0.4.17
@backstage/plugin-playlist-backend 0.3.11
@backstage/plugin-playlist-common 0.1.12
@backstage/plugin-playlist 0.2.1
@backstage/plugin-proxy-backend 0.4.5
@backstage/plugin-scaffolder-backend 1.19.1
@backstage/plugin-scaffolder-common 1.4.3
@backstage/plugin-scaffolder-node 0.2.8
@backstage/plugin-scaffolder-react 1.6.1
@backstage/plugin-scaffolder 1.16.1
@backstage/plugin-search-backend-module-catalog 0.1.11
@backstage/plugin-search-backend-module-elasticsearch 1.3.10
@backstage/plugin-search-backend-module-pg 0.5.16
@backstage/plugin-search-backend-module-techdocs 0.1.11
@backstage/plugin-search-backend-node 1.2.11
@backstage/plugin-search-backend 1.4.7
@backstage/plugin-search-common 1.2.8
@backstage/plugin-search-react 1.7.3
@backstage/plugin-search 1.4.3
@backstage/plugin-shortcuts 0.3.16
@backstage/plugin-sonarqube-backend 0.2.9
@backstage/plugin-sonarqube-react 0.1.10
@backstage/plugin-sonarqube 0.7.9
@backstage/plugin-tech-insights-backend-module-jsonfc 0.1.39
@backstage/plugin-tech-insights-backend 0.5.21
@backstage/plugin-tech-insights-common 0.2.12
@backstage/plugin-tech-insights-node 0.4.13
@backstage/plugin-tech-insights 0.3.19
@backstage/plugin-tech-radar 0.6.10
@backstage/plugin-techdocs-addons-test-utils 1.0.24
@backstage/plugin-techdocs-backend 1.9.0
@backstage/plugin-techdocs-module-addons-contrib 1.1.2
@backstage/plugin-techdocs-node 1.10.0
@backstage/plugin-techdocs-react 1.1.13
@backstage/plugin-techdocs 1.9.1
@backstage/plugin-todo-backend 0.3.5
@backstage/plugin-todo 0.2.31
@backstage/plugin-user-settings 0.7.13
@backstage/release-manifests 0.0.11
@backstage/test-utils 1.4.5
@backstage/theme 0.2.19, 0.4.4
@backstage/types 1.1.1
@backstage/version-bridge 1.0.7
✨ Done in 3.95s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Gonna bring in some of the @backstage/permission-maintainers here too to get some opinions!

**Comment by darrenyung** [comment]
Another observation I've noticed, the tokens generated are stored in plaintext as cookies in the user's browser. This could be seen as a security threat, would it be good it there's some level of encryption for it?

**Comment by benjdlambert** [comment]
Hey @darrenyung!

Which tokens are you referring to? I believe that the only token that we store in cookies is the refresh token, which to be able to use you need to have the `clientSecret` which is only stored in the backend anyways I think.

It's an interesting point about encryption, wondering if we should, maybe something to think about for the #15999, but really i'm wondering if it's worth it, as the decryption key would also need to be stored alongside the `clientSecret` anyways in this case, so is it really another layer of security at that point? Needs some thought I guess.

**Comment by darrenyung** [comment]
Hey there @benjdlambert, 

It is the access token generated after auth like you've mentioned. Strange that, I was able to use it with a postman request to the GitHub REST interface and get valid response without needing to know the `clientSecret`. At the moment, its not yet flagged by my GitHub maintainers as we have policies in place to set TTL of said tokens outside Backstage but this one raised my eyebrows.

![image](https://github.com/backstage/backstage/assets/9360520/88ddca76-0a9b-4b38-8cd1-6b91bed3c673)

But I digress, as per original post, I'm really keen to see how I can provide secured use of the Scaffolder Action with token input as described [here](https://backstage.io/docs/features/software-templates/writing-templates#using-the-users-oauth-token) with permissions framework to stop unauthorized access as it is the preferred way forward for my org. 👻

**Comment by vinzscam** [comment]
Hey @darrenyung,

> But I digress, as per original post, I'm really keen to see how I can provide secured use of the Scaffolder Action with token input as described [here](https://backstage.io/docs/features/software-templates/writing-templates#using-the-users-oauth-token) with permissions framework to stop unauthorized access as it is the preferred way forward for my org. 👻

could you clarify this? Do you wanna disable `publish:github:pull-request` if a custom token is provided or what's your goal here?

**Comment by darrenyung** [comment]
Sure thing @vinzscam , its the reverse. I would like to disable `publish:github:pull-request` if a token property is not provided in the template. My org would like to ensure that the user has to provide authorization to GitHub to act on their behalf when actioning templates.

**Comment by vinzscam** [comment]
amazing, thanks for clarifying! It looks like there is a bug in the `hasStringProperty` permission rule and a fix is coming.
In the meantime I've just noticed the conditional decision you are using above would produce incorrect results. The following should be correct:

```ts
      return createScaffolderActionConditionalDecision(request.permission, {
        anyOf: [
          {
            // allow any other action
            not: scaffolderActionConditions.hasActionId({
              actionId: 'publish:github:pull-request',
            }),
          },
          {
            allOf: [
              scaffolderActionConditions.hasActionId({
                actionId: 'publish:github:pull-request',
              }),
              // token must be provided in the action above
              scaffolderActionConditions.hasStringProperty({
                key: 'token',
              }),
            ],
          },
        ],
      });
```
