### ISSUE TITLE
🐛 Bug Report: EntityOwnerPicker is over the navigation bar

### ISSUE THREAD

**Issue by pablom555** [backstage/backstage#21781]
### 📜 Description

When you are in the backstage catalog and you open the `EntityOwnerPicker` menu and then without closing it you choose an item from the navigation bar, the EntityOwnerPicker items are above the navigation bar.

### 👍 Expected behavior

The `EntityOwnerPicker` must either be closed or below the navigation bar.

### 👎 Actual Behavior with Screenshots

The `EntityOwnerPicker` is above the navigation bar.

![image](https://github.com/backstage/backstage/assets/44613627/7a8f4f44-e3fa-41c7-b2a2-976be61b368e)

![image](https://github.com/backstage/backstage/assets/44613627/afa52a23-7375-42b6-b676-9e0ee7eb0519)

### 👟 Reproduction steps

1 - Open EntityOwnerPicker
2 - Without closing it go to the navigation bar

### 📃 Provide the context for the Bug.

`EntityOwnerPicker` is above the navigation bar

### 🖥️ Your Environment

Not really environment specific

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Thank you for reporting, this does indeed need a fix! 👍

Let us know if you have any questions 🙏

**Comment by vinzscam** [comment]
nice @pablom555,
your solution can be a good starting point for a discussion on finding the best way to fix the issue.
Looking forward to a PR 🤩

**Comment by JeevaRamanathan** [comment]
`PopperComponent={props => ( <div {...props} > {props.children} </div> )}` works, but this method results in a dropdown where items are always displayed below, rather than as a popover, which is different from the current view. If this is acceptable, I will raise a PR. @Rugvip  could you please provide your input on this?

**Comment by Rugvip** [comment]
@JeevaRamanathan hmm, sound like that might not be what we'd want to do. Not sure I fully understand what you mean though, could you perhaps share a screenshot of that?

**Comment by JeevaRamanathan** [comment]
Sure. This is the current view where the dropdown is as popover and overlaps on the next dropdowns.
![image](https://github.com/backstage/backstage/assets/64531160/137c30a0-819f-46e4-a3ea-b6bf81903d06)
![image](https://github.com/backstage/backstage/assets/64531160/496d17c3-5ae4-4d46-9c17-5cf6ef608723)

The updated  view on adding this `PopperComponent={props => ( <div {...props} > {props.children} </div> )}`
![image](https://github.com/backstage/backstage/assets/64531160/1eb1dc4e-b4ab-47c3-b494-80e3a944f93a)
(with dropdown and sidebar opened)
![image](https://github.com/backstage/backstage/assets/64531160/313e64e9-3de2-40ec-b524-2abbbb73bb91)

I hope this makes it clear.

**Comment by freben** [comment]
@JeevaRamanathan Am I understanding your screenshots correctly that they don't show any issue after the fix? If so, we would be happy to review a PR for it.

**Comment by JeevaRamanathan** [comment]
@freben I have rasied a PR, could you please have a look into it and add your suggestions

**Comment by JeevaRamanathan** [comment]
Hi @freben @Rugvip, I have rasied a PR #24903, could you please have a look into it and add your suggestions
