### ISSUE TITLE
🐛 Bug Report: Call to CatalogApi.getEntities() takes a long time in StarredEntities with large number of Components

### ISSUE THREAD

**Issue by jslott2sigma** [backstage/backstage#21798]
### 📜 Description

With a large number of entities (~15-20k Components), we have witnessed the `getEntities()` call take a long time on the server (15-20 seconds). In the case of `StarredEntities` (exposed on a Home page) there are only < 10 actual starred entities.

### 👍 Expected behavior

Since there are only a handful of entities desired and the entity refs are available, I would expect the server call to take < 100 ms or thereabouts.

### 👎 Actual Behavior with Screenshots

The call took 15-20 secs on the server (as seen via browser developer tools)

### 👟 Reproduction steps

1. Create an instance with a large number of entities (e.g. 15-20k)
2. Create a home page with the `HomePageStarredEntities` components
3. Observe it takes a while for that component to render fully

### 📃 Provide the context for the Bug.

We'd like Backstage to scale to tens of thousands of entities. There may be other places where the call to `CatalogApi.getEntities()` perhaps should be replaced by `CatalogApi.getEntitiesByRefs()` too. Alternatively, it also may be appropriate to optimize `getEntities()` for this use case. However, since the entity refs are available, it seems most correct to invoke the most appropriate function in `CatalogApi`.

### 🖥️ Your Environment

backstage:  1.20.3

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8
  @backstage/backend-common                                        0.19.9
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/dev-utils                                             1.0.24
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-adr-backend                                    0.4.4
  @backstage/plugin-adr-common                                     0.2.17
  @backstage/plugin-adr                                            0.6.10
  @backstage/plugin-api-docs                                       0.10.1
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.4.1
  @backstage/plugin-catalog-backend-module-github                  0.4.5
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.4
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.1
  @backstage/plugin-catalog-import                                 0.10.3
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.9.1
  @backstage/plugin-catalog-unprocessed-entities                   0.1.5
  @backstage/plugin-catalog                                        1.15.1
  @backstage/plugin-devtools-backend                               0.2.4
  @backstage/plugin-devtools-common                                0.1.6
  @backstage/plugin-devtools                                       0.1.6
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-github-actions                                 0.6.8
  @backstage/plugin-home-react                                     0.1.5
  @backstage/plugin-home                                           0.5.11
  @backstage/plugin-org                                            0.6.17
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.1
  @backstage/plugin-scaffolder                                     1.16.1
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.3
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.39
  @backstage/plugin-tech-insights-backend                          0.5.21
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.4.13
  @backstage/plugin-tech-insights                                  0.3.19
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.1
  @backstage/plugin-user-settings                                  0.7.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sennyeya** [comment]
Hey 👋 , I saw you already made a PR for this, which is a no-brainer update! However, I also wanted to dig a little deeper into what might be causing this with `getEntities`. AFAIK the query we're executing for this call is pretty optimized (index [here](https://github.com/sennyeya/backstage/blob/ec7b27def50455ce2dfbf83c1bf7d65c0cda472f/plugins/catalog-backend/migrations/20210302150147_refresh_state.js#L170) and [here](https://github.com/sennyeya/backstage/blob/ec7b27def50455ce2dfbf83c1bf7d65c0cda472f/plugins/catalog-backend/migrations/20210302150147_refresh_state.js#L89)). So this is a little surprising to hear it's _this_ bad performance wise.

Could you share a little more about your setup and where you're running this from? Is this happening locally or/and when deployed? How many components were in the instance you were testing with?

This might be an issue with one of the `select ... where in (select * from ...)` nested queries where `kind=component` and we're pulling a _bunch_ of components and filtering out almost all of them.
