### ISSUE TITLE
🐛 Bug Report: Issues with Sidebar Navigation to Catalog

### ISSUE THREAD

**Issue by sydris** [backstage/backstage#21799]
### 📜 Description

1. SidebarSubmenuItem navigation is overriding filters[user]=owned when navigating in the catalog
2. After clicking link in Sidebar to catalog, if you change the filters on the page the link still appears active and clicking the link in the Sidebar again updates the URL but doesn't re-render the page

### 👍 Expected behavior

Clicking on the item in the Sidebar should take you to the link as it is given.

### 👎 Actual Behavior with Screenshots

**First Issue**
When clicking on the link in the Sidebar to the catalog where the user owns something, it works as expected and takes you to the owned view.

However, if you first click on a link in the Sidebar on an item where a user doesn't own something, for example (the owned filter is there but currently none of our users can own a team): 
`<SidebarSubmenuItem
              title="Owning Teams"
              to="/catalog?filters[kind]=group&filters[user]=owned"
              exact
            />`
And then you click on a link in the Sidebar where the user should own something
` <SidebarSubmenuItem
              title="Components"
              to="catalog?filters[kind]=component&filters[user]=owned"
              exact
            />
`
The URL switches to all anyway

**Second Issue**
Page does not update back to original link

Video shows both issues:

https://github.com/backstage/backstage/assets/57731239/163a972e-9d0f-49e3-bf59-64b3553483f7

### 👟 Reproduction steps

In Root.tsx

>         <SidebarItem icon={CategoryIcon} text="Catalog">
>          {' '}
>          <SidebarSubmenu title="Catalog">
>            <SidebarSubmenuItem
>              title="Components"
>              to="catalog?filters[kind]=component&filters[user]=owned"
>              exact
>            />
>            <SidebarSubmenuItem
>              title="APIs"
>              to="catalog?filters[kind]=api&filters[user]=owned"
>              exact
>            />
>            <SidebarSubmenuItem
>              title="Owning Teams"
>              to="catalog?filters[kind]=group&filters[user]=owned"
>              exact
>            />
>          </SidebarSubmenu>{' '}
>        </SidebarItem>

**First Issue**
Use Sidebar to go to link where user doesn't own anything, then use Sidebar to go to link where user does own something.

**Second Issue**
1. Use Sidebar to go to one of the links
2. Change the Kind or Type on the catalog page
3. Click the same link in the Sidebar as you did in step 1

### 📃 Provide the context for the Bug.

We want the links to always filter to the owned view if users own something in that category

### 🖥️ Your Environment

Bug exists on Chrome, Firefox, and Edge
Output of yarn backstage-cli info
@backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.4.5, 0.5.8
  @backstage/backend-common                                        0.18.5, 0.19.9
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.5.4, 0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/backend-test-utils                                    0.2.8
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.4, 0.2.0
  @backstage/cli                                                   0.22.13, 0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.12.4, 0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/dev-utils                                             1.0.24
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-analytics-module-ga4                           0.1.6
  @backstage/plugin-api-docs                                       0.10.1
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.2.19, 0.4.1
  @backstage/plugin-catalog-backend-module-aws                     0.3.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.1
  @backstage/plugin-catalog-import                                 0.10.3
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.9.1
  @backstage/plugin-catalog                                        1.15.1
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-github-actions                                 0.6.8
  @backstage/plugin-home-react                                     0.1.5
  @backstage/plugin-home                                           0.5.11
  @backstage/plugin-kubernetes-common                              0.7.1
  @backstage/plugin-org                                            0.6.17
  @backstage/plugin-permission-backend                             0.5.30
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.1
  @backstage/plugin-scaffolder                                     1.16.1
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.3
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.1
  @backstage/plugin-user-settings                                  0.7.13
  @backstage/release-manifests                                     0.0.10, 0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.2.19, 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Thank you for opening this issue! 👍

We'll leave this one open to community contributions. If anyone wants to work on this, please chime in, any help is appreciated! 🙏

**Comment by mattprinold** [comment]
I'm able to reproduce the behaviour detailed in the issue, ill start looking into a fix.

**Comment by mattprinold** [comment]
@Rugvip  okay so i've found the offending culprit for issue 1. Essentially the UserListPicker overrides the User filter when there are no entities matching that filter and sets it to User="all"

<img width="618" alt="Screenshot 2024-01-29 at 12 15 49" src="https://github.com/backstage/backstage/assets/57544905/7ef9478d-bb7a-446d-8e59-178b214357e9">

It seems this behaviour was deliberately put in as there also a bunch of unit tests asserting on this behaviour. Though it seems an odd default to have as if there are no entities reflecting a set of filters surely you should show the user that rather than just changing the query.

<img width="795" alt="Screenshot 2024-01-29 at 12 17 00" src="https://github.com/backstage/backstage/assets/57544905/9af8c3bd-95e6-482b-b7b1-9c14dfdeeee5">

It can easly be changed by removing the useEffect hook but i want to get clarification that this is the direction we want to take before making the changes.

**Comment by mattprinold** [comment]
its also worth noting that the above does not apply to the case where a user does own entities, the reason this never gets re-rendered is because the  dependencies for the queryParamUserFilter useMemo hook never change so the selectedUserFilter never gets changed again as the useMemo will always return the cached value. Unless you navigate away from the catalog and then back to it.

**Comment by mattprinold** [comment]
@Rugvip as the two issues are separate would it be best to split this into two PR's?

**Comment by mattprinold** [comment]
@vinzscam What i've done is kept the behaviour but restricted it to kinds of type group or user, as it makes sense for the override to exist there, but for other kinds, i.e. component i've not applied the override as i feel the user would want to know if they dont' own any compoents or if they have non starred. Happy to refactor though as i havn't raised the PR for this yet.

**Comment by mattprinold** [comment]
> its also worth noting that the above does not apply to the case where a user does own entities, the reason this never gets re-rendered is because the dependencies for the queryParamUserFilter useMemo hook never change so the selectedUserFilter never gets changed again as the useMemo will always return the cached value. Unless you navigate away from the catalog and then back to it.

this can be ignored, it was incorrect.

**Comment by mattprinold** [comment]
@vinzscam @Rugvip could get some eyes on the PR please
