### ISSUE TITLE
🐛 Bug Report: [Scaffolder] Eventstream refresh stops after 3 retries if there was inactivity for 45 seconds

### ISSUE THREAD

**Issue by Aashrit-Harness** [backstage/backstage#21805]
### 📜 Description

This bug is in continuation to (https://github.com/backstage/backstage/issues/15002). Here the solution did not account for long time action as addressed by this comment (https://github.com/backstage/backstage/issues/15002#issuecomment-1715189148). 

### 👍 Expected behavior

It should retry/refresh as many times (currently only 3 retries happen) until the task is finished or the timeout value (which is currently 45 seconds) should be parameterised.

### 👎 Actual Behavior with Screenshots

After 3 retries, we get the below message which gets stuck until manually the page is refreshed and latest status is fetched.
<img width="807" alt="Screenshot 2023-12-11 at 3 04 09 AM" src="https://github.com/backstage/backstage/assets/139942493/932966c2-f884-4648-b16e-a1b92f587404">

### 👟 Reproduction steps

1. Start a long task in Scaffolder
2. Throttle the network to slow 3G to trigger retry
3. Wait for 3 retries and the the popup will appear which will not go away

### 📃 Provide the context for the Bug.

For tasks that take long to complete, the error message shows up and does not go away leading to bad user experience. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Thank you for reporting! We actually discussed this in the most recent scaffolder project area sync and concluded that we should keep polling even after the warning panel has appeared.

👀  @acierto

**Comment by Aashrit-Harness** [comment]
Hey @Rugvip, can you please share the timeline in which we can expect the above mentioned changes.

**Comment by vinzscam** [comment]
> Hey @Rugvip, can you please share the timeline in which we can expect the above mentioned changes.

unfortunately due to time restrictions the issue has been prioritized at the moment, but it's definitely up for grabs 😄

**Comment by benjdlambert** [comment]
Ping @backstage/scaffolder-maintainers

**Comment by benjdlambert** [comment]
Think that @acierto has fixed this in a PR over here: https://github.com/backstage/backstage/pull/21814/files#diff-7a7cf96d83688504b7d6c9178dddb09057d54545f93f9df0a9b0bcc1014cc7d9R220-R259

**Comment by benjdlambert** [comment]
Closing as fixed.

**Comment by Aashrit-Harness** [comment]
> Think that @acierto has fixed this in a PR over here: https://github.com/backstage/backstage/pull/21814/files#diff-7a7cf96d83688504b7d6c9178dddb09057d54545f93f9df0a9b0bcc1014cc7d9R220-R259

This PR was closed so the changes are not merged yet @benjdlambert. Can you please reopen this issue and give update regarding this issue? Thank you.

**Comment by benjdlambert** [comment]
@Aashrit-Harness the change was indeed merged. https://github.com/backstage/backstage/pull/22236 was a replacement of that PR because of DCO issues.
