### ISSUE TITLE
🐛 Bug Report: Installation Insturction mentions wrong nodejs version

### ISSUE THREAD

**Issue by alpalex** [backstage/backstage#21809]
### 📜 Description

https://backstage.spotify.com/learn/standing-up-backstage/standing-up-backstage/1-intro/

states nodejs 16 is required, but when running `npx @backstage/create-app` there is an error mesage
```console
  executing     yarn install ◠ error root@1.0.0: The engine "node" is incompatible with this module. Expected version "18 || 20". Got "16.20.2"
error Found incompatible module.
```

### 👍 Expected behavior

-

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/143097973/f0f42c94-687e-4caf-b873-2b7595b5ddf3)

### 👟 Reproduction steps

follow the installation instructions here (usinv nvm to install node): https://backstage.spotify.com/learn/standing-up-backstage/standing-up-backstage/2-install-app/

### 🖥️ Your Environment

debian 11

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by awanlin** [comment]
Just following up that this has been corrected 👍
