### ISSUE TITLE
🚀 Feature: Allow custom Node HTTP Server configuration in new Backend System

### ISSUE THREAD

**Issue by eipc16** [backstage/backstage#21808]
### 🔖 Feature description

Old backend system allows for modification of Node HTTP Server configuration by exposing `http.Server` class through `.start()` method in the ServiceBuilder class ([reference](https://backstage.io/docs/reference/backend-common.servicebuilder)). Unfortunately, this is no longer the case in the new Backend System where the `http.Server` object is completely encapsulated in the `rootHttpRouterServiceFactory`. 

I would like to propose implementing a way to update the server configuration during application startup.

### 🎤 Context

We are currently using this "feature" in the old backend system to modify server configuration like `keepAliveTimeout` ([docs](https://nodejs.org/api/http.html#serverkeepalivetimeout)). 

We need to modify those properties, because default value for `keepAliveTimeout` (and few other properties) does not play well with our infrastructure configuration. Basically, when Idle Timeout of Load Balancer is greater than Keep Alive Timeout of Application (which is 5s for Node) then 502s happen a lot and we really don't want to change Idle Timeout on our Load Balancer.

Currently, the only way to achieve this in the new backend system is to provide a completely custom implementation of the `rootHttpRouterServiceFactory` it would be nice if we could use the existing factory.

### ✌️ Possible Implementation

Two solutions come to my mind for now, but I'm open for discussing other proposals. I'm also willing to submit a PR, but want to know which approach will be better from your perspective before I start to work.

### Option 1: Server configuration in `app-config.yaml`

Allow configuration of selected server properties in `app-config.yaml` and load them in `readHttpServerOptions`. In this approach it's harder to "break" the server and is consistent with the more declarative approach of the new Backend System.

Few selected configuration options could be exposed under `http.server` key. The options that I'm most interested in are:

- [server.keepAliveTimeout](https://nodejs.org/api/http.html#serverkeepalivetimeout)
- [server.timeout](https://nodejs.org/api/http.html#servertimeout)
- [server.headersTimeout](https://nodejs.org/api/http.html#serverheaderstimeout)

Though, other properties could be useful to other Backstage users.

### Option 2: Server configuration in `RootHttpRouterFactoryOptions`

Expose a callback in `RootHttpRouterFactoryOptions` that would allow changing server configuration before (or after?) triggering the `.start()` method. It's more prone to user errors, but also more flexible.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
For full control of the HTTP server and express app the intention is actually that you reimplement the entirety of the root http service: https://github.com/backstage/backstage/blob/fb50191fa3a289a990e4de1098525da5d6c9f6ae/packages/backend-app-api/src/services/implementations/rootHttpRouter/rootHttpRouterServiceFactory.ts#L69-L107. In doing that you of course don't need to implement the `configure` option but can just list the middleware directly instead.

This pattern should be added to the docs over here: https://github.com/backstage/backstage/blob/652322515f5e4212ce7e6f04262cf42fd8a06cca/docs/backend-system/core-services/01-index.md#L108, is that something you want to help out with? 🙏  happy to provide any pointers

We can also lift out some configuration to `app-config.yaml` if they make sense, as in your first option.

**Comment by webark** [comment]
@Rugvip would you be open to having the default configure
https://github.com/backstage/backstage/blob/01843b1bf3f5ce8ef569f3d52b2b3bb5614ca8ac/packages/backend-app-api/src/services/implementations/rootHttpRouter/rootHttpRouterServiceFactory.ts#L57-L66
exportable or configurlble in some way so that didn't have to be copy and pasted when you only wanted to overwrite one? Maybe the middleware factory could pull from extentions or be a service? 🤷 I guess overwritting it isn't alot of code, but just want to leverage any new changes. Like the helmet stuff or things like that if it were to change.

**Comment by Rugvip** [comment]
@webark ordering of middleware is very important, which makes that a bit tricky. We could definitely provide more presets through the context though, stuff like `beforeRoutes`, `afterRoutes` or simply just `defaults` for the entire thing. Bit curious what kind of middleware you want to add though.

**Comment by webark** [comment]
We use it currently to override the morgan request logger with our own. There was a method in the old backend system for this, but this appears to be the way to extend it in the new system.

**Comment by freben** [comment]
I'll reopen this for a bit I think. This was asked for again

https://discord.com/channels/687207715902193673/1034089724664610938/1227001739949904014

In the context of for example avoiding ALB 502s:

https://adamcrowder.net/posts/node-express-api-and-aws-alb-502/

**Comment by Rugvip** [comment]
@webark ah alright, in that case you do need to list out all of them again. Since you need to remove the original logging middleware you can't really rely on the default set. At this point I don't think we'll be looking at any kind of more powerful API for replacing individual middleware anytime soon.

**Comment by freben** [comment]
I'll just note that the original issue asked for access to `http.Server` which doesn't apply to `configure` (which is called before the server is even started).

Unless it's actually safe [to call `createHttpServer`](https://github.com/backstage/backstage/blob/2ca9dc00b2a1d26cbf8f4700463bdeeb962fec55/packages/backend-app-api/src/services/implementations/rootHttpRouter/rootHttpRouterServiceFactory.ts#L94) _before_ calling `configure` to update routes? If that's the case, we could do so and pass the `server` variable through to `configure` to let people do what they want with it. Even though the risk of misuse registering routes "on the side" etc) is greater then :)

Alternatively, we could add a fixed set of app-config settings specifically for these timeouts etc, that the `rootHttpRouterServiceFactory` obeys.

**Comment by alecjacobs5401** [comment]
FWIW, having access to the server is also valuable for those who might want to use something like https://github.com/godaddy/terminus to handle more graceful shutdown.

I do see that there are more lifecycle hooks that are in place in the new backend system, but there is _a lot_ of configurability provided by terminus that makes pre/post shutdown easy to set up

**Comment by webark** [comment]
Maybe this is getting off topic. But should the server be a service, or maybe it gets resolved from the lifecycles? So if you opened into a lifecycle it could be a part of the context?

**Comment by freben** [comment]
To me, just reusing `configure` could be fine (if moving the server creation to be above it). If someone wants to get started with a PR, we could keep discussing there.

One drawback of putting a lot into a single `configure` is of course that it turns into an all-or-nothing affair where just because you want to add a single server timeout setting you have to copy-paste (and track over time) a bunch of unrelated code. But I think maybe that could be counteracted by helpers added to the context,

```ts
rootHttpRouterServiceFactory({
  configure({ applyDefaults, server }) {
    applyDefaults();
    server.headersTimeout = 600000;
  }),
  ...
```

**Comment by freben** [comment]
We discussed this briefly among the maintainers. Would someone be up for implementing:

- Move everything server _creation_ but _not the start command_ before `configure`
- Pass in the server to `configure`
- Add an `applyDefaults` function to the context passed to `configure` as well
- Make the default implementation of `configure` just run that `applyDefaults` function

Thanks 🙏

**Comment by freben** [comment]
> Maybe this is getting off topic. But should the server be a service, or maybe it gets resolved from the lifecycles? So if you opened into a lifecycle it could be a part of the context?

Hm `coreServices.rootHttpRouter` at the moment really _is_ the server, despite the naming. Yeah in theory we could add another layer of course. But it'd be a kind of a funky "reverse" thing then, that the server would depend on the router, or there would be an interface with like a setter that should only be called once or - Hm, not sure.

For now I think configure is good enough and leaves the abstraction "flatter" until we are forced to make it deeper.

Regarding lifecycles: maybe. In some callbacks in the frontend the `apiHolder` gets passed along just in case users need something out of it. But the thing is, the point that you do e.g. `addShutdownHook` is typically inside the module `init` - and at that point you just add the dependency to your module instead, and have it availably by closure when registering the lifecycle callback.

**Comment by alecjacobs5401** [comment]
I'll take a stab at a PR for this
