### ISSUE TITLE
🐛 Bug Report: tiny documentation spelling mistake

### ISSUE THREAD

**Issue by alpalex** [backstage/backstage#21818]
### 📜 Description

https://backstage.io/docs/deployment/docker#separate-frontend

at
3. Remove the @backstage/plugin-app-backend and the app package dependency (e.g. app) from `packages/backend/packages.json`.

it should instead say `packages/backend/package.json`

### 👍 Expected behavior

-

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/143097973/03885860-9f4b-4de6-8159-d68ba96348d2)

### 👟 Reproduction steps

-

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
Thanks, closed by #21827
