### ISSUE TITLE
🐛 Bug Report: Techdocs on S3, api calls 404

### ISSUE THREAD

**Issue by Vinzz** [backstage/backstage#21811]
### 📜 Description

Wen I want to display the doc of a component, say default/component/foobar, the doc, lying on S3 is rendered, but continuous calls to <url>/api/techdocs/metadata/techdocs/default/component/foobar are made, these are 404 and il makes the browser screen to flicker

### 👍 Expected behavior

Displayed documentation should not flicker, and the calls to the /api/techdoc shoud either don't occur, or be 200OK

### 👎 Actual Behavior with Screenshots

![BSDoc](https://github.com/backstage/backstage/assets/1025344/698769cd-f4fe-4c60-98ff-246cafee8c7a)

### 👟 Reproduction steps

Create a new component
Ad some html rendered mkdoc in an S3 bucket
Navigate the doc

### 🖥️ Your Environment

Backstage running in k8s, @backstage/create-app 0.5.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by aspic** [comment]
Do you consistently get 404 or is it random? 

We're experiencing something similar. Techdocs on S3 is randomly failing with 404. I suspect it's the underlying infra that's the problem (CEPH OBJECT GATEWAY S3 API) but have not yet been able to verify this. So seeing this seemingly related issue was interesting to me.

**Comment by Vinzz** [comment]
hi @aspic yes we do have it constantly, it fills the logs pretty fast

**Comment by Vinzz** [comment]
Well, no one to look à this issue?

**Comment by Vinzz** [comment]
As it seems, techdocs-cli publish does not generate any techdocs_metadata.json file which could cause this issue

**Comment by Vinzz** [comment]
ok, provided you use the techdocs-cli generate command, you will have a techdocs_metadata.json file
Had to dig in the source code to find out that.

It may be interesting to note in the documentation that using the techdocs-cli generate is mandatory
