### ISSUE TITLE
Add catalogApi endpoint for getLocationByEntity

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#21826]
### 🔖 Feature description

Currently we can not get location by entity/entity name. we have to get all locations and get a location id for a particular entity. If we want to unregister a location. we need location id.

### 🎤 Context

We are injecting data from backend(third party system) and we want to unregister or delete an entity. Now we have to get all locations and then map with target and get a location id. After that, we can delete the location by delete endpoint.

### ✌️ Possible Implementation

we should create a endpoint to return location id by entity name. or we can return location id in entity data. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Yep makes sense to provide something better here imo, but will leave decisions to @backstage/catalog-maintainers. One potential way to achieve this is to make the location ID part of the location entity data, that way you can use the ancestry API to quickly look up the root location and find the ID.

**Comment by alde** [comment]
Hello @lalit774 , I've opened a PR for a proposed solution to this.
