### ISSUE TITLE
🐛 Bug Report: Kubernetes plugin don't show resources created by ReplicaSet

### ISSUE THREAD

**Issue by belmirocneto** [backstage/backstage#21850]
### 📜 Description

When a Kubernetes Component is created by a **ReplicaSet** Kind, we can't see the details about it on the Catalog (Kubernetes TAB). 
With components created by Deployment or Stateful Set, we have lots of information.

I can see that in the API we have the data being retrieved, but it does't show on interface.

### 👍 Expected behavior

- ReplicaSet component being showed in Kubernetes Page with PodMetrics and another things.

### 👎 Actual Behavior with Screenshots

Kubernetes TAB in my Component:
![image](https://github.com/backstage/backstage/assets/140106271/3117dd73-2e66-45d4-b742-f932007b3d29)
My API return:
```json
{
    "items": [
        {
            "cluster": {
                "name": "clusterName"
            },
            "podMetrics": [
                {
                    //lots of information about my pods
                }
            ],
            "resources": [
                {
                    "type": "pods",
                    "resources": [
                        {
                          //lots of information about my pods
                        }
                    ]
                },
                {
                    "type": "services",
                    "resources": [
                        {
                          //lots of information about my services
                        }
                    ]
                },
                {
                    "type": "configmaps",
                    "resources": []
                },
                {
                    "type": "limitranges",
                    "resources": []
                },
                {
                    "type": "resourcequotas",
                    "resources": []
                },
                {
                    "type": "deployments",
                    "resources": []
                },
                {
                    "type": "replicasets",
                    "resources": [
                        {
                          //lots of information about my ReplicaSets
                        }
                    ]
                },
                {
                    "type": "horizontalpodautoscalers",
                    "resources": []
                },
                {
                    "type": "jobs",
                    "resources": []
                },
                {
                    "type": "cronjobs",
                    "resources": []
                },
                {
                    "type": "ingresses",
                    "resources": []
                },
                {
                    "type": "statefulsets",
                    "resources": []
                },
                {
                    "type": "daemonsets",
                    "resources": []
                }
            ],
            "errors": []
        }
    ]
}
```

### 👟 Reproduction steps

1. Followed the tutorial at this link to connect my Backstage instance with my EKS Cluster [Kubernetes Installation](https://backstage.io/docs/features/kubernetes/installation)
1.1. My cluster is a EKS
1.2. I using the assume role option to connect to my cluster
2. Setup my Backstage component manifest with this two labels:
2.1. `backstage.io/kubernetes-label-selector: app=app-name,type=app,role=backend`
2.2. `backstage.io/kubernetes-id: app-name`
3. Setup my K8S ReplicaSet and components with label: `backstage.io/kubernetes-id: backstage-component-name`

### 📃 Provide the context for the Bug.

My application components that are being created by ReplicaSet can't be viewed in the Kubernetes page.

### 🖥️ Your Environment

My current Kubernetes settings on the app-config are like. The scenario is the same on the Local Kubernetes configured as Service Account and with the AWS Configured one:
```yaml
    kubernetes:
      clusterLocatorMethods:
      - clusters:
        - authProvider: serviceAccount
          name: local-cluster
          serviceAccountToken: ${K8S_LOCAL_TOKEN}
          skipMetricsLookup: false
          skipTLSVerify: true
          url: ${K8S_LOCAL_URL}
        - assumeRole: ${K8S_AWS_ROLE_ARN}
          authProvider: aws
          caData: ${K8S_AWS_CA_DATA}
          externalId: Backstage-role
          name: aws-cluster
          skipMetricsLookup: false
          skipTLSVerify: true
          url: ${K8S_AWS_URL}
        type: config
```

My backstage-cli info:
```code
yarn backstage-cli info
yarn run v1.22.19
$ /Users/belmiro.neto/Documents/backstage/test_node20/trustly/node_modules/.bin/backstage-cli info
OS:   Darwin 23.1.0 - darwin/arm64
node: v18.18.2
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.20.0

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8
  @backstage/backend-common                                        0.19.9
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-api-docs                                       0.10.1
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.4.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.1
  @backstage/plugin-catalog-import                                 0.10.3
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.9.1
  @backstage/plugin-catalog                                        1.15.1
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-github-actions                                 0.6.8
  @backstage/plugin-kubernetes-backend                             0.13.1
  @backstage/plugin-kubernetes-common                              0.7.1
  @backstage/plugin-kubernetes-node                                0.1.1
  @backstage/plugin-kubernetes-react                               0.1.1
  @backstage/plugin-kubernetes                                     0.11.2
  @backstage/plugin-org                                            0.6.17
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.1
  @backstage/plugin-scaffolder                                     1.16.1
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.3
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.1
  @backstage/plugin-user-settings                                  0.7.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 2.09s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by belmirocneto** [comment]
> This is very similar in spirit to #21427 but regards `ReplicaSet`s instead of `DaemonSet`s, and much of [this](https://github.com/backstage/backstage/issues/21427#issuecomment-1819365491) explanatory comment is also relevant here.
> 
> It sounds like you're using a "naked" `ReplicaSet` in this case (i.e. not owned by a `Deployment`) -- is that right? What's the use-case? From what I can tell, `ReplicaSet`s are almost always more useful when managed by a `Deployment` as discussed in the [docs](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#when-to-use-a-replicaset). Not rejecting this issue, just curious.

We use naked ReplicaSet to simplify our deployment process today. 

I have reading [the mentioned comment](https://github.com/backstage/backstage/issues/21427#issuecomment-1819365491) and it looks like the same case with the DaemonSet.

I'm not a frontend developer, but it seems that if we implement the `Accordions` for the DaemonSet and the ReplicaSet we will be able to fix both scenarios, right?

**Comment by jamieklassen** [comment]
> I'm not a frontend developer, but it seems that if we implement the `Accordions` for the DaemonSet and the ReplicaSet we will be able to fix both scenarios, right?

That's right!

**Comment by belmirocneto** [comment]
Is there any documentation explaining how to build the plugin locally? I'm testing a possibly fix, but when I start to run `backstage-cli package build` I receive this error:
```log
Error: No declaration files found at ../../dist-types/plugins/kubernetes/src/index.d.ts, be sure to run yarn tsc to generate .d.ts files before packaging
```

When when I run `yarn tsc` I receive: 
```log
Usage Error: Couldn't find a script named "tsc".
```

**Comment by jamieklassen** [comment]
I usually run all my scripts from the root of the monorepo -- `yarn tsc` can be a little slow but that's typical of `tsc` and you can get faster typechecker feedback with a language server + IDE. You can manually test the plugin in the context of a full Backstage app with `yarn dev` -- the Kubernetes plugins are installed in the sample app:

https://github.com/backstage/backstage/blob/973bc8cf9060cb79bbd59af7ff16dda7e61eb279/packages/app/src/components/catalog/EntityPage.tsx#L537-L539

and sample backend:

https://github.com/backstage/backstage/blob/973bc8cf9060cb79bbd59af7ff16dda7e61eb279/packages/backend/src/index.ts#L188

I find this developer experience is decent.

**Comment by belmirocneto** [comment]
My problem using a local environment is that I can't connect externally to my Kubernetes as service role. So to test I'll need to change a lot of things to reproduce.

**Comment by jamieklassen** [comment]
> My problem using a local environment is that I can't connect externally to my Kubernetes as service role. So to test I'll need to change a lot of things to reproduce.

Maybe you can use a local Kubernetes for testing, like kind or minikube?

If that's an obstacle, I've never done it for real and I imagine @mclarke47 built most of this out, but you can run Kubernetes stuff on its own with a mock k8s with `yarn --cwd plugins/kubernetes start`. That gets driven by [`plugins/kubernetes/dev/index.tsx`](https://github.com/backstage/backstage/blob/master/plugins/kubernetes/dev/index.tsx) -- you could probably add/modify one of the fixtures to returns some naked `ReplicaSet`s.

**Comment by mclarke47** [comment]
It seems pretty unconventional to use replicaSets directly instead of through deployments. IMO I would hesitate to support this due to the increased number of edge cases and testing scenarios unless we can demonstrate it helps many users.

**Comment by belmirocneto** [comment]
The principal case that we use, is because in our application we can't have a rolling update. Even in a small amount of time, two different versions of the application can create a huge problem to us, so with the ReplicaSet we can create the new workloads and when they are Ready, we change the traffic (blue green scenario). 

We have implemented the adjusts in the package and are testing. If we can have future support, I can do a PR later.

**Comment by mclarke47** [comment]
I'm assuming you can't use the [`recreate` Deployment strategy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment)?

**Comment by belmirocneto** [comment]
> I'm assuming you can't use the [`recreate` Deployment strategy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment)?

In my case I need the new pods are Ready before I kill the old ones. If I do with the recreate, the docs says that I will have a unavailability with the `recreate` strategy.
> All existing Pods are killed before new ones are created

**Comment by patrik-j-nilsson** [comment]
We use [Argo Rollouts](https://argoproj.github.io/argo-rollouts/#how-does-it-work). I believe it replaces the standard Deployment, so that might be a good use case for allowing replica sets without deployments.

**Comment by belmirocneto** [comment]
I made a simple implementation to solve this by creating `Accordions` for the ReplicaSet. If they accept, I can carry out the PR to release it to more people who can benefit.

**Comment by patrik-j-nilsson** [comment]
@belmirocneto, nice! Where can I find this PR?
