### ISSUE TITLE
🚀 Feature: Add delete button in unprocessed entity plugin

### ISSUE THREAD

**Issue by efenner-cambia** [backstage/backstage#21858]
### 🔖 Feature description

I would love a button to delete an unprocessed entity to handle the case where an orphaned entity is stuck in the processing loop and would otherwise require enabling auto-deletion of orphaned entities or running queries against the database.

### 🎤 Context

The [Catalog Unprocessed Entities](plugins/catalog-unprocessed-entities) plugin does a great job at highlighting processing errors, but sometimes it is still difficult to resolve them. I have had several where the unprocessed entity is also orphaned, but unlike with a processed entity that later becomes orphaned, there is not yet a way to delete them from the UI.

If there was a big red button to delete each stuck entity (or an even bigger, redder one at the top to delete all), that would solve my problems.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by fedy97** [comment]
I think it is already present such a feature, what about this? https://github.com/backstage/backstage/blob/7b0199f2876c9d5417a954ea28271ce94d6c0fc7/plugins/catalog-react/src/components/UnregisterEntityDialog/UnregisterEntityDialog.tsx#L151

**Comment by vinzscam** [comment]
yeah definitely it would be a nice addition to have such button in the unprocessed-entities' plugin

**Comment by efenner-cambia** [comment]
@fedy97 That button is only available in the catalog. Items that are showing up in the unprocessed-entities plugin usually have not yet made it to the catalog, so it is not accessible yet

**Comment by freben** [comment]
@fedy97 correct me if I'm wrong but I believe they have made it to the catalog (the refresh_state table but may or may not have successfully completed processing and stitching (the final_entities table)

**Comment by fedy97** [comment]
yes guys you are right, we do not have it for unprocessed-entities

**Comment by rshakespearBHR** [comment]
This would be a very useful addition. For us we have a more complex configuration, and do not have direct access to the DB to be able to remove items from the refresh_state table. Having a simple button to do that would be soooo helpful!

**Comment by kurtaking** [comment]
We built what we call the **Entity Exception Report**, which surfaces _unprocessed entities_. We created this internally before the **devtools + unprocessed entities** plugins existed. One of the most recent features we added was removing the associated record from the `refresh_state` table via a backend API call.

It seems like what you are asking for is what we have already built, and I can take a look at what it would take to contribute the functionality to `backstage/backstage`. 

<img width="1365" alt="image" src="https://github.com/backstage/backstage/assets/14222009/ac9dd1ac-c644-4a93-b8c9-537316b6d8ad">

 I like the extensibility of the devtools plugin, and the unprocessed entities UI is better than what we have. 😄

**Comment by kurtaking** [comment]
I believe the `UnprocessedEntitiesDb` and `api` would need to live in a new `@backstage/plugin-catalog-unprocessed-entities-backend` plugin. 

Is that correct?

**Comment by awanlin** [comment]
Just wanted to comment that DevTools is just a possible container for the Unprocessed Entities plugin and it doesn't need to be used that way. This feature would be added to the Unprocessed Entities plugin itself 👍

**Comment by kurtaking** [comment]
Fair callout. 😅 My opinion is that DevTools is the perfect container for it! 😄

**Comment by camilaibs** [comment]
> PR has been merged - this will be available in the next release.
Thank you, closing the issue 🎉
