### ISSUE TITLE
🐛 Bug Report: Catalog can't process API entities with $text pointing at very long URL

### ISSUE THREAD

**Issue by Antrakos** [backstage/backstage#21863]
### 📜 Description

Recently our uses reached out to us that they don't see APIs in catalog even though they described them in `catalog-info.yaml` and the schema is correct. After initial investigation I found this message in logs:
```
{
  "code": "22001",
  "file": "varchar.c",
  "length": 99,
  "level": "warn",
  "line": "635",
  "message": "Processing of api:default/some-long-name-api failed insert into \"refresh_keys\" (\"entity_id\", \"key\") values ($1, $2) - value too long for type character varying(255)",
  "name": "error",
  "plugin": "catalog",
  "routine": "varchar",
  "service": "backstage",
  "severity": "ERROR",
  "stack": "error: insert into \"refresh_keys\" (\"entity_id\", \"key\") values ($1, $2) - value too long for type character varying(255)\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at TLSSocket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at TLSSocket.emit (node:events:514:28)\n    at TLSSocket.emit (node:domain:488:12)\n    at addChunk (node:internal/streams/readable:376:12)\n    at readableAddChunk (node:internal/streams/readable:349:9)\n    at Readable.push (node:internal/streams/readable:286:10)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)\n    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)"
}
```

Looking at the database, it seems that for API entities a row is inserted in `refresh_keys` table with `key` a URL for definition placeholder file. We have some services that use a very nested structure and complete Gitlab URL to that file is longer than 255 characters.

Example entity
```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: some-very-long-api-name
spec:
  type: grpc
  lifecycle: production
  owner: team
  system: system
  definition:
    $text: ./long-repeated-application-module-name/long-name-application-api-module/src/main/proto/com/company-a/group/long-service-name/a/few/more/inner/folders/some_grcp_operation.proto
```

Therefore to-be-inserted `key` looks like: `url:https://gitlab.com/company-a/some-group/potentially-long-team-name/service-name/-/blob/master/long-repeated-application-module-name/long-name-application-api-module/src/main/proto/com/company-a/group/long-service-name/a/few/more/inner/folders/some_grcp_operation.proto` - 272 characters.

I assume this table is used to monitor updates to the original file in Git and refetch it contents. Though it may be a bit redundant in our case since our catalog-info.yaml always sit in the same repo as definition files so any updates lead to a new commit and complete refresh for all entities in this repo. Regardless, is there any particular reason for having a limit of 255 characters?

### 👍 Expected behavior

Entity should appear in catalog with correct definition text

### 👎 Actual Behavior with Screenshots

Entity is not in the catalog. There are only warnings in logs. I also found this api mentioned in catalog-unprocessed-entities plugin, but it failed to display any useful info

### 👟 Reproduction steps

1. Create very nested folder structure and out some file in it
2. Create API entity with `definition: $text: ` pointing to the file resulting in long path
3. Register the entity

### 📃 Provide the context for the Bug.

As a quick remediation we manually increased character limits in the db with `ALTER TABLE refresh_keys ALTER COLUMN key TYPE varchar(500);`. However this is not the long-term solution and I am not aware of a way to put it in the code since I believe I can't add knex migrations to external plugins. Or even If I do I can't imagine potential issues of having multiple migration sources.
Do you know a way to make this configurable? Or some safe way to alter column definition without hindering future upgrades and migrations?

### 🖥️ Your Environment

```
OS:   Darwin 23.1.0 - darwin/arm64
node: v18.17.1
yarn: 4.0.2
cli:  0.24.0 (installed)
backstage:  1.20.3

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8
  @backstage/backend-common                                        0.19.9
  @backstage/backend-defaults                                      0.2.7
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/dev-utils                                             1.0.24
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-analytics-module-ga4                           0.1.6
  @backstage/plugin-api-docs                                       0.10.1
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.4.1
  @backstage/plugin-badges                                         0.2.51
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.4
  @backstage/plugin-catalog-backend-module-openapi                 0.1.24
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.1
  @backstage/plugin-catalog-import                                 0.10.3
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.9.1
  @backstage/plugin-catalog-unprocessed-entities                   0.1.5
  @backstage/plugin-catalog                                        1.15.1
  @backstage/plugin-devtools-backend                               0.2.4
  @backstage/plugin-devtools-common                                0.1.6
  @backstage/plugin-devtools                                       0.1.6
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-explore-backend                                0.0.17
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.33
  @backstage/plugin-explore                                        0.4.13
  @backstage/plugin-home-react                                     0.1.5
  @backstage/plugin-home                                           0.5.11
  @backstage/plugin-kubernetes-backend                             0.13.1
  @backstage/plugin-kubernetes-cluster                             0.0.3
  @backstage/plugin-kubernetes-common                              0.7.1
  @backstage/plugin-kubernetes-node                                0.1.1
  @backstage/plugin-kubernetes-react                               0.1.1
  @backstage/plugin-kubernetes                                     0.11.2
  @backstage/plugin-org                                            0.6.17
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend-module-cookiecutter         0.2.31
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.1
  @backstage/plugin-scaffolder                                     1.16.1
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-explore                  0.1.11
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.3
  @backstage/plugin-sentry                                         0.5.12
  @backstage/plugin-shortcuts                                      0.3.16
  @backstage/plugin-sonarqube-backend                              0.2.9
  @backstage/plugin-sonarqube-react                                0.1.10
  @backstage/plugin-sonarqube                                      0.7.9
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.1
  @backstage/plugin-user-settings                                  0.7.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Hi!

This was discussed a bit elsewhere - yes, this risks happening with anything that results in very large refresh keys. One way forward could be to either prune keys to the max length (which can lead to over-refreshing more than you asked for), or introduce hashing of these keys (which gives slightly worse introspection into the database).

**Comment by pedroknup** [comment]
I'm having a similar problem I guess.

Backstage fails to process an entity that has lots of nested properties as the keys could easily surpass the 255 limit. 

Changing the key column's type to a bigger varchar did the trick. But I wonder how reliable that change is, since the database is managed by Backstage. Is there a better way to do that? Maybe to disable indexing for certain parts of an entity. 

Thanks.

**Comment by freben** [comment]
That doesn't work in general since it's indexed, right? Db engines in general aren't fond of indexing massive values.

**Comment by pedroknup** [comment]
Could you elaborate on what wouldn't work in general? Would it primarily slow down query performance and result in slower searches? I'm keen to understand the trade-offs and explore potential solutions. What alternatives or optimizations would you recommend in this scenario? Thank you for your insights.

**Comment by freben** [comment]
Depends on the database engine.

In postgres, you are permitted to create large columns and indices for them, but at runtime if you try to insert a large value in the table you get an error thrown.

In mysql, you are permitted to create large columns of course, but it absolutely rejects upfront an attempt to even create an index for those columns.

Etc

**Comment by Herve-Moriou** [comment]
I had the same problem with locations > 255 characters with postgreSQL
I needed a quick fix, so I used an awfull workaround 
=> I added a knex js in my sources and copy it in node_modules/@backstage/plugin-catalog-backend/migrations/ in my build and start scripts
I'm very interested in a clean solution

- /**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function down(knex) {
  await knex.schema.alterTable('locations', table => {
    table.text('target').notNullable().alter();
  });
  await knex.schema.alterTable('refresh_keys', table => {
    table.text('key').notNullable().alter();
  });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function down(knex) {
  await knex.schema.alterTable('locations', table => {
    table.string('target').notNullable().alter();
  });
  await knex.schema.alterTable('refresh_keys', table => {
    table.string('key').notNullable().alter();
  });
};

**Comment by Rugvip** [comment]
I believe we moved to `.string` because MySQL doesn't like `.text`. We can bump the length of the string with the 2nd argument to `.string` though

**Comment by freben** [comment]
Yep see my comment above regarding indices of string values in both pg and mysql.

For fixes, I'd say, either introduce hashing of refresh keys (maybe only over a certain length), or strictly pruning refresh key lengths up to a certain maximum length. The former is more precise (but makes the values harder to understand when debugging in the database), while the latter may lead to over-refreshing (if there end up being too many matches because of string pruning).
