### ISSUE TITLE
🚀 Feature: Add README translated into Korean

### ISSUE THREAD

**Issue by yj-yoo** [backstage/backstage#21860]
### 🔖 Feature description

Add README translated into Korean

### 🎤 Context

Recently, many developers and companies in Korea are interested in Backstage. However, since there are no documents in Korean and there is a high barrier to entry, I plan to add documents in Korean.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by vinzscam** [comment]
안녕하세요 @yj-yoo!
This is a great suggestion. One way to move forward would be to create different READMEs per language and link all of them in the main README.md

**Comment by yj-yoo** [comment]
@vinzscam Hi 👋!  Thanks your comment!
I agree with you. README-ko_kr.md was added under the Backstage directory, and is cross-referenced with README.md as a link(https://github.com/backstage/backstage/pull/21874). There aren't many READMEs for each language, so I don't think a separate directory is needed yet.

**Comment by freben** [comment]
Merged, thanks!
