### ISSUE TITLE
🐛 Bug Report: The Azure provider is not configured to support sign-in, while it is

### ISSUE THREAD

**Issue by davidkarlsen** [backstage/backstage#21865]
### 📜 Description

https://myhost.mydomain/api/auth/microsoft/refresh?optional&env=production

fails with:
```
{
    "error": {
        "name": "AuthenticationError",
        "message": "Refresh failed; caused by InputError: Missing session cookie",
        "cause": {
            "name": "InputError",
            "message": "Missing session cookie",
            "stack": "InputError: Missing session cookie\n    at OAuthAdapter.refresh (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:390:15)\n    at OAuthEnvironmentHandler.refresh (/app/node_modules/@backstage/plugin-auth-node/dist/index.cjs.js:794:58)\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at bound refresh (/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/app/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at /app/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)\n    at next (/app/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)\n    at router (/app/node_modules/express/lib/router/index.js:47:12)\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)"
        }
    },
    "request": {
        "method": "GET",
        "url": "/api/auth/microsoft/refresh?optional&env=production"
    },
    "response": {
        "statusCode": 401
    }
}
```

### 👍 Expected behavior

Should work out of the box, or special configuration documented to make it work.

### 👎 Actual Behavior with Screenshots

see log

### 👟 Reproduction steps

Deploy backstage into an azure container apps, set backendurl to the intgress address, do the OIDC setup.

### 📃 Provide the context for the Bug.

See ossie

### 🖥️ Your Environment

container apps

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by davidkarlsen** [comment]
I have this:
```yaml

auth:
  environment: production
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    microsoft:
      production:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        domainHint: ${AZURE_TENANT_ID}
```

but still it will say:
<img width="485" alt="Screenshot 2023-12-14 at 19 25 22" src="https://github.com/backstage/backstage/assets/18299/75f8d7da-4b71-4c45-b494-646f20439306">

**Comment by jamieklassen** [comment]
That error comes from [here](https://github.com/backstage/backstage/blob/7b0199f2876c9d5417a954ea28271ce94d6c0fc7/packages/core-components/src/layout/SignInPage/SignInPage.tsx#L125-L129), and based on the [troubleshooting docs](https://backstage.io/docs/auth/troubleshooting#sign-in-fails-with--provider-is-not-configured-to-support-sign-in) for this error message -- how is your backend set up? do you have a sign-in resolver configured for this auth provider? Something like this:

https://github.com/backstage/backstage/blob/7b0199f2876c9d5417a954ea28271ce94d6c0fc7/packages/backend/src/plugins/auth.ts#L81-L86

**Comment by davidkarlsen** [comment]
ah, yes, I just realised that and was reading through it and getting rid of the default github one and adding ms.

**Comment by davidkarlsen** [comment]
So to sum up - the initially reported problem was avoided by upgrading BS. Errors after that was my negligence. Thanks @jamieklassen and sorry for the RTFM moment :)
