### ISSUE TITLE
🚀 Feature: Add a new builtin action to publish a scaffolded project to a gitea repository

### ISSUE THREAD

**Issue by cmoulliard** [backstage/backstage#21866]
### 🔖 Feature description

Add a new builtin action to publish a scaffolded project to a gitea repository

### 🎤 Context

This feature is needed as currently we can use gitea as backstage integration, that a RepoUrl Picker exists

### ✌️ Possible Implementation

- Add a `createPublishGiteaAction` within the index `plugins/scaffolder-backend/src/scaffolder/actions/index.ts`
- Create a `gitea.ts` defining the action needed to create a git repository under the folder /`/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/`
- Add a `gitea.test.ts` test case

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by cmoulliard** [comment]
Correction `index.ts` -> `createBuiltinActions.ts`

**Comment by vinzscam** [comment]
Nice addition 👏

**Comment by camilaibs** [comment]
Closing this issue as the linked pull request was merged 🙂
