### ISSUE TITLE
🚀 Feature: Add custom Kinds to default columns for CatalogTable

### ISSUE THREAD

**Issue by GoFightNguyen** [backstage/backstage#21873]
### 🔖 Feature description

We want the ability to extend the columns in [CatalogTable](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx) with a custom Kind, without overwriting, or duplicating the logic, for the default columns.

For example, we have a custom `BC` Kind. We want to specify the columns for it while leaving the default columns for the built-in Kinds alone.

### 🎤 Context

 [PR 21093](https://github.com/backstage/backstage/pull/21093) made it so that the [DefaultCatalogPageProps.columns](https://github.com/backstage/backstage/blob/7b0199f2876c9d5417a954ea28271ce94d6c0fc7/plugins/catalog/src/components/CatalogPage/DefaultCatalogPage.tsx#L99) prop can accept an array or a function. The PR also extracted the [defaultColumnsFunc](https://github.com/backstage/backstage/blob/7b0199f2876c9d5417a954ea28271ce94d6c0fc7/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L80C18-L80C18)

### ✌️ Possible Implementation

If [defaultColumnsFunc](https://github.com/backstage/backstage/blob/7b0199f2876c9d5417a954ea28271ce94d6c0fc7/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L80C18-L80C18) was publicly exported, then an implementation could look like this:

```ts
import { defaultColumnsFunc } from '@backstage/plugins-catalog';

const myColumnsFunc: CatalogTableColumnsFunc = ({filters, entities}) => {
  if (filters.kind?.value === 'mycustomkind') {
    return [
      CatalogTable.columns.createNameColumn(),
      ...
    ];
  } else {
    return defaultColumnsFunc(filters, entities);
  }
};

...

<Route path="/catalog" element={<CatalogIndexPage columns={myColumnsFunc} />} />

```

Another option is providing a seam to extend [createEntitySpecificColumns](https://github.com/backstage/backstage/blob/7b0199f2876c9d5417a954ea28271ce94d6c0fc7/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L86) with the custom Kind. This would be useful if you liked the core columns of Title (hidden), Name, Description, and Tags. I haven't thought this one through.

### 👀 Have you spent some time to check if this feature request has been raised before?
 
I believe this feature request is different than [Issue 17599](https://github.com/backstage/backstage/issues/17599), which hoped to add/replace columns across all Kinds. It might be possible for an implementation to also appease Issue 17599.

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR! But it would likely be after the New Year

**Comment by vinzscam** [comment]
I think your suggestion to export `defaultColumnsFunc` makes sense!
