### ISSUE TITLE
🐛 Bug Report: The ReportIssue component does not display correctly.

### ISSUE THREAD

**Issue by pablom555** [backstage/backstage#21871]
### 📜 Description

The ReportIssue component is truncated when you select the title text or when you select text near the top edge of the screen.

### 👍 Expected behavior

To be able to view tooltip correctly:

![image](https://github.com/backstage/backstage/assets/44613627/042c2a4b-c989-4c4e-9dba-190f5d0420c6)

### 👎 Actual Behavior with Screenshots

When title text is selected or when text is selected near the top edge of the screen the tooltip is not visible.

![image](https://github.com/backstage/backstage/assets/44613627/c75256a9-2d06-4beb-88bb-83591eca232d)

![image](https://github.com/backstage/backstage/assets/44613627/b0c4f8d4-481d-4ed1-aebd-1cedeb87ff43)

### 👟 Reproduction steps

- Go to Docs Menu
 - Select any text

### 📃 Provide the context for the Bug.

Is only a visual bug.

### 🖥️ Your Environment

Not really environment specific

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Closing this issue as the linked pull request was merged 🙂
