### ISSUE TITLE
🐛 Bug Report: Search analytics event not sent if total result count is unknown

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#21904]
### 📜 Description

Currently there is a check whether the total number of search results is known over [here](https://github.com/backstage/backstage/blob/f48cde800a2a40086f2acb1de86020532716c916/plugins/search-react/src/context/SearchContext.tsx#L141), and we then only send an event if that count is known. The total result count is not something that is always available for all search engines and configurations. Most notably, if you enable permissions, we don't report the total result count, as that would leak information.

### 👍 Expected behavior

We should send the `'search'` analytics event regardless of whether the total result count is known or not.

### 👎 Actual Behavior with Screenshots

The `'search'` analytics event is not sent if the total result count is unkown.

### 👟 Reproduction steps

Either enable permissions or use the PostgreSQL search engine and you'll see that the `'search'` analytics event is not sent.

### 📃 Provide the context for the Bug.

This was introduced by #21030, probably just an oversight.

### 🖥️ Your Environment

any

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by surya-prakash-susarla** [comment]
Would simply adding an else case with the analytics event sending a value of 0 be a good solution to this?
