### ISSUE TITLE
🚀 Feature: Extend catalog-backend-module-github to allow for different GitHub events (archiving, deleting, renaming, etc) repos

### ISSUE THREAD

**Issue by wanisfahmyDE** [backstage/backstage#21906]
### 📜 Description

we currently use the GitHub Entity Provider with events support (webhook). This works fine when adding/removing/modifying the catalog-info.yaml. But when a repo is archived, the entity in the catalog remains and doesn't get deleted.

We noticed that the GitHub events for archiving repos are published correctly from GitHub and also subscribed to in backstage, because when we enabled debug log we saw messages like: 

```
Event received: topic=github.repository, metadata={...,  payload={"action":"archived",....}
```

our config looks like this:
```yaml
events:
  modules:
    github:
      webhookSecret: xxx
  http:
    topics:
      - github
```

```yaml
catalog:
  providers:
    github:
      providerId:
        organization: 'myorg'
        catalogPath: '/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '.*'
        validateLocationsExist: true
  orphanStrategy: 'delete'
```

```TypeScript
// backend/src/plugins/catalog.ts
export default async function createPlugin(
    env: PluginEnvironment,
): Promise<Router> {
    const builder = await CatalogBuilder.create(env);
    // The org URL below needs to match a configured integrations.github entry
    // specified in your app-config.
    builder.addEntityProvider(
        GithubOrgEntityProvider.fromConfig(env.config, {
            id: 'production',
            orgUrl: 'https://github.com/myorg',
            logger: env.logger,
            schedule: env.scheduler.createScheduledTaskRunner({
                frequency: {minutes: 60},
                timeout: {minutes: 15},
            }),
        }),
    );
    const githubProvider = GithubEntityProvider.fromConfig(env.config, {
        logger: env.logger,
        schedule: env.scheduler.createScheduledTaskRunner({
            frequency: {minutes: 720}, /* twice per day checking all repos and importing/refreshing in the catalog */
            timeout: {minutes: 30},
        })
    });
    env.eventBroker.subscribe(githubProvider); /* any new add/delete/modify actions in catalog-info.yaml will be handled by the event broker */
    builder.addEntityProvider(githubProvider);
    builder.setProcessingIntervalSeconds(3600) /* only for existing entities, they would be refreshed if the eventBroker didn't catch the event - currently set every 1 hour */
    builder.addProcessor(new ScaffolderEntitiesProcessor());
    const {processingEngine, router} = await builder.build();
    await processingEngine.start();
    return router;
```

After checking the catalog-backend-module-github source code here:
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/providers/GithubEntityProvider.ts#L285 it seems that any event other than `github.push` is actually discarded.

If the maintainers can confirm that this is the case, I am willing to submit a PR to allow more events by default

### 👍 Expected behavior

When archiving repos, they should be unregistered from the Catalog

### 👎 Actual Behavior with Screenshots

Archiving events are received by Backstage, but nothing happens beyond that.

### 👟 Reproduction steps

1. Enable GitHub events support for the catalog based on https://backstage.io/docs/integrations/github/discovery#installation-with-events-support
2. Archive a GitHub repo that is already registered in the catalog.
3. Check the component in Backstage Catalog, it is still there.

### 📃 Provide the context for the Bug.

We are trying to have a clean catalog without any archived GitHub repos as components.

### 🖥️ Your Environment

```bash
OS:   Darwin 22.4.0 - darwin/arm64
node: v18.18.0
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.20.3

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8
  @backstage/backend-common                                        0.19.9
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.12.5, 0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/dev-utils                                             1.0.24
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-adr-backend                                    0.4.4
  @backstage/plugin-adr-common                                     0.2.17
  @backstage/plugin-api-docs                                       0.10.1
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.2.19, 0.4.1
  @backstage/plugin-catalog-backend-module-github                  0.4.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.1
  @backstage/plugin-catalog-import                                 0.10.3
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.9.1
  @backstage/plugin-catalog                                        1.15.1
  @backstage/plugin-devtools-backend                               0.2.4
  @backstage/plugin-devtools-common                                0.1.6
  @backstage/plugin-devtools                                       0.1.6
  @backstage/plugin-events-backend-module-github                   0.1.17
  @backstage/plugin-events-backend                                 0.2.16
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-explore-backend                                0.0.17
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.33
  @backstage/plugin-explore                                        0.4.13
  @backstage/plugin-github-actions                                 0.6.8
  @backstage/plugin-github-pull-requests-board                     0.1.21
  @backstage/plugin-home-react                                     0.1.5
  @backstage/plugin-home                                           0.5.11
  @backstage/plugin-org                                            0.6.17
  @backstage/plugin-permission-backend                             0.5.30
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.1
  @backstage/plugin-scaffolder                                     1.16.1
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-explore                  0.1.11
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.3
  @backstage/plugin-shortcuts                                      0.3.16
  @backstage/plugin-sonarqube-backend                              0.2.9
  @backstage/plugin-sonarqube-react                                0.1.10
  @backstage/plugin-sonarqube                                      0.7.9
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.1
  @backstage/plugin-user-settings                                  0.7.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.2.19, 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by larafonse** [comment]
Would be nice to have 🙏

**Comment by GeetaAhuja** [comment]
@wanisfahmyDE are you using the new backend? if yes . did you add the eventbroker to pluginEnvironment?

**Comment by alde** [comment]
I don't think I would classify this as a bug, we don't necessarily want to automatically remove things if they're archived.

This could be a feature request to be able to opt-in for this functionality.

**Comment by theurichde** [comment]
Hi @alde 👋🏻 

Shall we create a separate feature request, or can we use this issue to raise the request? Additionally, we (@wanisfahmyDE and me) are willing to provide that feature via PR

**Comment by alde** [comment]
I would say you can probably re-word and re-use this issue

**Comment by pjungermann** [comment]
For me, it's also rather an enhancement to handle additional events. 🙂 

I can confirm that so far, only `github.push` is used by the `GithubEntityProvider`. There might be other events that should be handled like the `github.repository` event with its `archived` action.

It seems like there is an interest to control the behavior when receiving "archived repo" events.

However, as there is still the full sync, the behavior for archived repos should be the same as for full syncs. If archived repos are ignored there, it makes sense to remove them from Backstage (as if they got deleted). If they are included, they should be kept.

**Comment by camilaibs** [comment]
Hi @pjungermann, do you have a preferred solution in mind 🙂 ?

**Comment by pjungermann** [comment]
@camilaibs We can add support for more GH event types at the entity provider. All of these, I would consider enhancements.

Each event type might need a specific action. In general, we need to respect the filter logic. The outcome should be same as if we had done a full refresh.

If a repository gets renamed, we likely want to unregister the `Locations` for the previous name and register the `Location` for the new name. If a repo gets archived, we also need to react to it.

If a repository is archived, we need to unregister its `Locations`. I checked the code and currently, archived repositories always get removed/filtered out. It's not configurable.
Seems easy to add the enhancement for it.

**Comment by pjungermann** [comment]
It makes sense to me to check for further event types we might want to have as well and missing still.

**Comment by pjungermann** [comment]
If nobody else wants to give it a try I can have a look as well.

**Comment by pjungermann** [comment]
I have identified the following event types that seem to make sense to be added:

- `RepositoryArchivedEvent`: remove registered `Location` entities from that repository
- `RepositoryDeletedEvent`: remove registered `Location` entities from that repository
  - caveat:

> A repository was deleted. GitHub Apps and repository webhooks will not receive this event.

- `RepositoryEditedEvent`: check based on filters whether it (still) matches or not
  - relevant due to topic-based filtering
- `RepositoryRenamedEvent`: remove registered `Location` entities for the old repository name, readd them for the new repository name if new name satisfies repo name filter
- `RepositoryTransferredEvent`: handle like `RepoPush` and check for catalog files, etc.
  - caveat: 

> Ownership of the repository was transferred to a user or organization account. This event is only sent to the account where the ownership is transferred. To receive the repository.transferred event, the new owner account must have the GitHub App installed, and the App must be subscribed to "Repository" events.

  - **_Question:_** Is there a `RepositoryDeletedEvent` at the old owner account?

- `RepositoryUnarchivedEvent`: rescan repository and readd potentially contained `Location` entities

To be skipped (share if you think otherwise):

- `RepositoryCreatedEvent`: If a new repo was created, it should not contain any content.

**Comment by pjungermann** [comment]
I have a draft for the repo events locally. I will share a PR when its ready.

**Comment by wanisfahmyDE** [comment]
hey @pjungermann, apologies for not being active here, Should I rename the title and description of the issue?

**Comment by pjungermann** [comment]
@wanisfahmyDE you can, sure. It would make it clearer I think.

**Comment by pjungermann** [comment]
btw: Not sure if there is already another issue for making the behavior for archived repositories configurable.

**Comment by wanisfahmyDE** [comment]
iirc (https://github.com/backstage/backstage/issues/20718) was the initial issue that drove me to create this one
