### ISSUE TITLE
🚀 Feature: Azure sites: show tags

### ISSUE THREAD

**Issue by davidkarlsen** [backstage/backstage#21919]
### 🔖 Feature description

It would be great if the plugin could show the tags on the site as well. We use tags to indicate version.

### 🎤 Context

Tags bring further informational elements - so it would be useful to display these alongside the name.

### ✌️ Possible Implementation

Show tags in an additional column beside the name.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by davidkarlsen** [comment]
Note to self: Seems like this should be as easy as extending this table: https://github.com/backstage/backstage/blob/master/plugins/azure-sites/src/components/AzureSitesOverviewTableComponent/AzureSitesOverviewTable.tsx as the data is already collected

**Comment by vinzscam** [comment]
thanks for reporting @davidkarlsen 🙏. Indeed it would be a nice addition
