### ISSUE TITLE
🐛 Bug Report: Owner filter filtering beyond boundaries.

### ISSUE THREAD

**Issue by C-RoblesAutodesk** [backstage/backstage#21918]
### 📜 Description

The problem starts when users filter by owner on the catalog page and move to groups/users that don't own this filter, the filter keeps applying when these kinds don't filter by owner.

other filters respect when a kind doesn't use the filter, so the table displays data correctly

### 👍 Expected behavior

I'd like to all filters behave in the same way. applied only to the kinds that own that filter, not to those that don't.

### 👎 Actual Behavior with Screenshots

![Captura de pantalla 2023-12-18 a la(s) 12 52 26](https://github.com/backstage/backstage/assets/147189820/d28e6113-f3a4-4b76-8594-402afd74801b)
![Captura de pantalla 2023-12-18 a la(s) 12 52 33](https://github.com/backstage/backstage/assets/147189820/9e5eff82-80a7-4d14-90a1-18d2052dceb1)
![Captura de pantalla 2023-12-18 a la(s) 13 05 21](https://github.com/backstage/backstage/assets/147189820/049c1170-ad94-4400-b670-f414f35e040e)

### 👟 Reproduction steps

1. Go to the catalog page, and filter by owner.
2. switch the kind to groups/users
3. The table displays no data because is filtered by owners, when owners is not an applicable filter for this kind.

### 📃 Provide the context for the Bug.

Users can apply owner filters and move to groups/users, data will not display because the filter is applied internally, but we don't know that this filter is applied, UI doesn't show the filter applied or something to know about what is happening.

### 🖥️ Your Environment

https://demo.backstage.io/catalog?filters%5Bkind%5D=user&filters%5Bowners%5D=group%3Abackstage%2Fmaintainers&filters%5Buser%5D=all

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
```[tasklist]
### Tasks
```

**Comment by vinzscam** [comment]
thanks for opening this @C-RoblesAutodesk. This is one of the  corner cases within the current UI. A quick fix would be probably to not hide the filters when kind user is selected

**Comment by johanhammar** [comment]
Related to #7264 ?

**Comment by C-RoblesAutodesk** [comment]
looks like it is, I'd like to submit a fix for this or do you think that is better to add a quick fix on our end to not hide the filters? @vinzscam @johanhammar

**Comment by benjdlambert** [comment]
@C-RoblesAutodesk please go ahead and raise a PR ad we can discuss further there! would love some contribution for this for sure! :pray:
