### ISSUE TITLE
🐛 Bug Report: Slowness with Loading TechDocs Page

### ISSUE THREAD

**Issue by iriswang233** [backstage/backstage#21931]
### 📜 Description

Techdoc page loading is slower than 5s, which confuses users if the doc is working when waiting for page load.

### 👍 Expected behavior

Ideally the page load can be within 1s. Checking the suggestion from lighthouse, it looks like the improvement can be done with webpack, like split js bundles, optimise script evalutation.

### 👎 Actual Behavior with Screenshots

Here is some investigation about this issue using Chrome DevTools, [Lighthouse](https://github.com/GoogleChrome/lighthouse) and [performance insights](https://developer.chrome.com/blog/performance-insights).

Both of these 2 tools are evaluating based on page load, but different page load may perform differently.  Attached results are showing similar performance on largest contentful paint, which is the main issue that slows down the page load. 
<img width="729" alt="image-2023-12-18_16-10-14" src="https://github.com/backstage/backstage/assets/49713904/414f45c1-bdc2-43ca-bef5-da9f56419c1e">
<img width="735" alt="image-2023-12-18_16-10-37" src="https://github.com/backstage/backstage/assets/49713904/9297a01e-65a6-44dd-9a9a-80b87515357c">

The longest time is render delay(4s). This means although resources and first byte of page are loaded, the main content of the page is not delayed 4s to load(gap between FCP and LCP).
<img width="1159" alt="image" src="https://github.com/backstage/backstage/assets/49713904/bc575066-e443-45c9-9522-172650eeb0d2">

Another long time task is following task to evaluate script before DCL(DOMContentLoaded).
<img width="786" alt="image" src="https://github.com/backstage/backstage/assets/49713904/0c00ea5f-b812-45ca-96a4-c3eb6147ef15">

### 👟 Reproduction steps

1. Go to the docs tab in entity with incognito chrome
2. nav between 2 pages
3. use lighthouse to analyse the performance
4. use performance to profile the page load

### 🖥️ Your Environment

OS:   Darwin 23.2.0 - darwin/x64
node: v18.18.2
yarn: 1.22.19
cli:  0.23.1 (installed)
backstage:  1.19.6

Dependencies:
  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.5.7
  @backstage/backend-common                                        0.15.2, 0.19.8
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.6.6
  @backstage/backend-tasks                                         0.5.11
  @backstage/catalog-client                                        1.4.5
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5
  @backstage/cli                                                   0.18.1, 0.23.1
  @backstage/config-loader                                         1.5.2
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.11.2, 0.13.7
  @backstage/core-plugin-api                                       1.7.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7
  @backstage/integration-react                                     1.1.20
  @backstage/integration                                           1.7.1
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.4
  @backstage/plugin-auth-node                                      0.4.0
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.3
  @backstage/plugin-catalog-backend-module-ldap                    0.5.21
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-import                                 0.10.1
  @backstage/plugin-catalog-node                                   1.4.7
  @backstage/plugin-catalog-react                                  1.8.5
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.32
  @backstage/plugin-explore                                        0.4.11
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-home-react                                     0.1.4
  @backstage/plugin-home                                           0.5.9
  @backstage/plugin-kubernetes-backend                             0.13.0
  @backstage/plugin-kubernetes-common                              0.7.0
  @backstage/plugin-kubernetes-node                                0.1.0
  @backstage/plugin-kubernetes-react                               0.1.0
  @backstage/plugin-kubernetes                                     0.11.0
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-pagerduty                                      0.6.6
  @backstage/plugin-permission-backend                             0.5.29
  @backstage/plugin-permission-common                              0.7.9
  @backstage/plugin-permission-node                                0.7.17
  @backstage/plugin-permission-react                               0.4.16
  @backstage/plugin-proxy-backend                                  0.4.4
  @backstage/plugin-scaffolder-backend                             1.18.1
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.7
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-shortcuts                                      0.3.15
  @backstage/plugin-tech-radar                                     0.6.9
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.1
  @backstage/plugin-techdocs-node                                  1.7.6, 1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/release-manifests                                     0.0.10, 0.0.5
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.2.19, 0.3.0, 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.6
✨  Done in 1.85s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
What does the network tab say? Is it waiting for a very long time to fetch the templates from the catalog backend?

**Comment by Parsifal-M** [comment]
Could this also be an issue with how it's being deployed? i.e. https://backstage.io/docs/features/techdocs/architecture 🤔 💭

**Comment by iriswang233** [comment]
hi @freben, what is the api to fetch the templates from the catalog backend? 
hi @Parsifal-M, i don't think so. Because loading techdoc will just load techdoc from s3? is there any other process?

**Comment by johnphilip283** [comment]
Hi there @iriswang233! Could you provide some more screenshots from performance insights once your page loads? I'm having a tough time deciphering where the time difference between FCP and LCP might be coming from, since I can't reproduce this locally. Running PI on https://demo.backstage.io/docs/default/Component/backstage yields this profile: 
<img width="243" alt="FCP occurs at 0.92s, while LCP occurs at 1.07s" src="https://github.com/backstage/backstage/assets/23266343/d0421fd0-350f-4141-8b75-8f63b973f7e7">

**Comment by johnphilip283** [comment]
Would you also be able to detail any other TechDocs addons or Chrome extensions you have running on your browser, as well as the size of the TechDoc you're attempting to render @iriswang233?
