### ISSUE TITLE
🐛 Bug Report: [TechDocs] PlantUML diagrams are not rendered

### ISSUE THREAD

**Issue by KatharinaSick** [backstage/backstage#21940]
### 📜 Description

When adding a PlantUML diagram to TechDocs the build succeeds but the diagram is not rendering. Backstage just shows the alt text ("uml diagram") and when opening the image in a new tab, it is empty: `data:image/png;base64,`.

### 👍 Expected behavior

I would expect the diagram to show up in the documenation.

### 👎 Actual Behavior with Screenshots

Just the alt text ("uml diagram") of the diagram is displayed and when opening the image in a new tab, it is empty.

![image](https://github.com/backstage/backstage/assets/9420018/3e9509b6-11be-4f93-be31-fa73f6add934)

When right clicking the "uml diagram" and selecting "Open Image in New Tab":

![image](https://github.com/backstage/backstage/assets/9420018/aa52656f-1149-4a05-99cd-e1b09a9ba8af)

### 👟 Reproduction steps

Configure Backstage to locally render TechDocs (in our case they are also published to S3 but that shouldn't matter):

```yaml
techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: ${TECHDOCS_S3_BUCKET}
      region: eu-central-1
      credentials:
        accessKeyId: ${TECHDOCS_S3_ACCESS_KEY}
        secretAccessKey: ${TECHDOCS_S3_SECRET_KEY}
```

Install PlantUML in the container just as in [techdocs-container/Dockerfile](https://github.com/backstage/techdocs-container/blob/main/Dockerfile) (see first comment for the full Dockerfile): 

```dockerfile
RUN pip install --upgrade pip && pip install mkdocs-techdocs-core
RUN curl -o plantuml.jar -L https://github.com/plantuml/plantuml/releases/download/v1.2023.10/plantuml-1.2023.10.jar && echo "527d28af080ae91a455e7023e1a726c7714dc98e plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar
RUN echo '#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml
```

Add a PlantUML diagram to the TechDocs:

````markdown
Generated graph:

```plantuml
@startuml
title Login Sequence
    ComponentA->ComponentB: Login Request
    note right of ComponentB: ComponentB logs message
    ComponentB->ComponentA: Login Response
@enduml
```
````

### 📃 Provide the context for the Bug.

We would like to use PlantUML diagrams in our TechDocs as it [should be possible](https://backstage.io/docs/features/techdocs/how-to-guides#how-to-render-plantuml-diagram-in-techdocs).

### 🖥️ Your Environment

```sh
OS:   Linux 6.6.4-200.fc39.x86_64 - linux/x64
node: v18.17.1
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.20.3

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8
  @backstage/backend-common                                        0.15.2, 0.19.9
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/dev-utils                                             1.0.24
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-adr-backend                                    0.4.4
  @backstage/plugin-adr-common                                     0.2.17
  @backstage/plugin-adr                                            0.6.10
  @backstage/plugin-api-docs                                       0.10.1
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.4.1
  @backstage/plugin-badges-backend                                 0.3.4
  @backstage/plugin-badges                                         0.2.51
  @backstage/plugin-catalog-backend-module-bitbucket-server        0.1.20
  @backstage/plugin-catalog-backend-module-github                  0.4.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.1
  @backstage/plugin-catalog-import                                 0.10.3
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.9.1
  @backstage/plugin-catalog-unprocessed-entities                   0.1.5
  @backstage/plugin-catalog                                        1.15.1
  @backstage/plugin-entity-validation                              0.1.12
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-github-actions                                 0.6.8
  @backstage/plugin-home-react                                     0.1.5
  @backstage/plugin-jenkins-backend                                0.3.1
  @backstage/plugin-jenkins-common                                 0.1.21
  @backstage/plugin-jenkins                                        0.9.2
  @backstage/plugin-org                                            0.6.17
  @backstage/plugin-permission-backend                             0.5.30
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.1
  @backstage/plugin-scaffolder                                     1.16.1
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-stack-overflow-collator  0.1.0
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.3
  @backstage/plugin-sonarqube-backend                              0.2.9
  @backstage/plugin-sonarqube-react                                0.1.10
  @backstage/plugin-sonarqube                                      0.7.9
  @backstage/plugin-stack-overflow-backend                         0.2.11
  @backstage/plugin-stack-overflow                                 0.1.22
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.39
  @backstage/plugin-tech-insights-backend                          0.5.21
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.4.13
  @backstage/plugin-tech-insights                                  0.3.19
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.1
  @backstage/plugin-user-settings                                  0.7.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
Done in 0.40s.
```

Note: I'm willing to submit a PR but would need help on identifying the issue.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by KatharinaSick** [comment]
Here's the full Dockerfile (I didn't want to make the reproduction steps too long):

```dockerfile
FROM node:18.17.1-bullseye-slim
ARG CONFIG_YAML
ARG IS_PROD

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev python3 python3-pip build-essential g++ curl && \
    rm -rf /var/lib/apt/lists/* && \
    yarn config set python /usr/bin/python3

RUN pip install --upgrade pip && pip install mkdocs-techdocs-core
RUN curl -o plantuml.jar -L https://github.com/plantuml/plantuml/releases/download/v1.2023.10/plantuml-1.2023.10.jar && echo "527d28af080ae91a455e7023e1a726c7714dc98e plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar
RUN echo '#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml

COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn install --frozen-lockfile --production=$IS_PROD --network-timeout 300000 && rm -rf "$(yarn cache dir)"

COPY packages/backend/dist/bundle.tar.gz app-config*.yaml ./
COPY catalog-info.yaml mkdocs.yaml ./
COPY docs ./docs

RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

ENV CONFIG_YAML=${CONFIG_YAML}

CMD ["sh", "-c", "node packages/backend --config app-config.yaml --config ${CONFIG_YAML}"]
```

**Comment by awanlin** [comment]
Hi @KatharinaSick, thanks for all the details. I'll give this a run some time in the next few days. In the mean time can you share what the values for theses would be, please?

```dockerfile
ARG CONFIG_YAML
ARG IS_PROD
```

**Comment by KatharinaSick** [comment]
Thank you @awanlin 🙂 

we’re using the same yaml files for dev, stg & prod deployments and therefore we are using those environment variables. You can assume ‘IS_PROD=true’ and the ‘CONFIG_YAML’ to contain the TechDocs config I posted.

**Comment by KatharinaSick** [comment]
Quick update: issue still occurs with Backstage 1.21

**Comment by awanlin** [comment]
Yeah, I would not have expected that to fix this. I know it works as I was helping someone on Discord a few weeks ago and they got it working but there are for use some rough edges around using PlantUML.

**Comment by awanlin** [comment]
Just a following up, got a test bed setup on Friday with the same state as you. Working on it today I think the issue is that you don't have all the dependencies installed. Specifcally the items from this line:

https://github.com/backstage/techdocs-container/blob/cfa8832c0479935c2c53239257f7a607044c0100/Dockerfile#L17

Debian does come with Java but not graphviz, when I installed that the diagram generated. I'm less sure on the need of the others ones. Here's what the install section looks like in my Dockerfile:

```dockerfile
RUN apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev \
    python3 python3-pip \
    build-essential g++ curl \
    graphviz fonts-dejavu fontconfig && \
    rm -rf /var/lib/apt/lists/* && \
    yarn config set python /usr/bin/python3
```

**Comment by KatharinaSick** [comment]
Thank you for helping me out here @awanlin :slightly_smiling_face: 

May I ask you to share you full Dockerfile? I added the `graphviz` dependency and then replaced my install section with yours but the result is still the same.

**Comment by awanlin** [comment]
Sure but I changed it as I was helping someone else with a multi-stage PlantUML error so this is from memory:

```
FROM node:18.17.1-bullseye-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev \
    python3 python3-pip \
    build-essential g++ curl \
    graphviz fonts-dejavu fontconfig && \
    rm -rf /var/lib/apt/lists/* && \
    yarn config set python /usr/bin/python3

RUN pip install --upgrade pip && pip install mkdocs-techdocs-core
RUN curl -o plantuml.jar -L https://github.com/plantuml/plantuml/releases/download/v1.2023.10/plantuml-1.2023.10.jar && echo "527d28af080ae91a455e7023e1a726c7714dc98e plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar
RUN echo '#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml

COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn install --frozen-lockfile --production=$IS_PROD --network-timeout 300000 && rm -rf "$(yarn cache dir)"

COPY packages/backend/dist/bundle.tar.gz app-config*.yaml ./
COPY catalog-info.yaml mkdocs.yaml ./
COPY docs ./docs

RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["sh", "-c", "node packages/backend --config app-config.yaml"]
```

I'll note that I had issues with TechDocs not refreshing when I made changes so I had to rebuild my app a few times so maybe that's the issue for you now?

**Comment by KatharinaSick** [comment]
Hmm that's weird. I compared my Dockerfile to yours and everything should be fine. Still, the diagram doesn't work. 

The refresh shouldn't be a problem because I tried it on two environments:
- A newly created dev instance which keeps everything in memory/on disk
- Our staging environment which stores it's docs in S3 but I just deleted the docs before
In both cases Backstage showed me that the documentation is created for the first time.

I'm sorry for keeping you busy for so long but do you have any other ideas what could be the issue?

**Comment by awanlin** [comment]
Took a look again and your are right, it's still not working. I must have mixed up someting with my local testing and my docker testing 😢 

BUT regardless for sure you need to have `graphviz` installed. One of the things I find helpful with TechDocs is to run `mkdocs` directly first just to confirm the docs are good. This was the first time using PlantUML on my laptop and without `graphviz` installed `mkdocs` would just throw a bunch of errors, once installed the docs generated.

**Comment by awanlin** [comment]
Looking closer at this when running in Docker I get this error as soon as I click on it to show the docs: "Request failed with status 500 Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation." I've seen this error before and I thought it was resolved/fixed. Might be a false direction but want to be sure. Will follow up when I know more. If you don't mind can you tell me if you have this error as well?

**Comment by awanlin** [comment]
Looks like that errors is search related but when I disable search I get a different error. Going to put this to the side for now and regroup later today or tomorrow if I make progress on my other priorities.

**Comment by awanlin** [comment]
Coming back to this now. What's interesting is that it's missing the actual `<data>` in the data url.

Given this Markdown:

```markdown
Generated graph:

```plantuml
@startuml
title Login Sequence
    ComponentA->ComponentB: Login Request
    note right of ComponentB: ComponentB logs message
    ComponentB->ComponentA: Login Response
@enduml```
```

I get this result when ran in Docker:

```html
<p>Generated graph:</p>
<p><img src="data:image/png;base64," class="uml" alt="uml diagram" title="" /></p>
```

But locally in Backstage, or running `techdocs-cli serve --no-docker` or `mkdocs serve` I get this:

```html
<p>Generated graph:</p><p><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAX4AAADeCAIAAAC-trucated-to-keep-example-simple=" class="uml" alt="uml diagram" title="" /></p>
```

Notice how all that encoding "stuff" is missing, like it gets stripped out? 🤔

**Comment by awanlin** [comment]
This is what it looks like in the UI:

![image](https://github.com/backstage/backstage/assets/67169551/369da3b0-d2bd-4f8c-8c53-53c6d3590550)

**Comment by awanlin** [comment]
OK, pretty sure I figured it out but not sure how I missed this or how I though it was working for me before. I'm also not sure why something didn't throw an error about it.

But **Java** is missing! Once I installed that then in my Docker container it works:

![image](https://github.com/backstage/backstage/assets/67169551/e94463ee-45bb-4740-bad8-c70affdcbcac)

Dockerfile:

```dockerfile
FROM node:18.17.1-bullseye-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev \
    python3 python3-pip \
    build-essential g++ curl \
    default-jre graphviz fonts-dejavu fontconfig && \
    rm -rf /var/lib/apt/lists/* && \
    yarn config set python /usr/bin/python3

RUN pip install --upgrade pip && pip install mkdocs-techdocs-core
RUN curl -o plantuml.jar -L https://github.com/plantuml/plantuml/releases/download/v1.2023.10/plantuml-1.2023.10.jar && echo "527d28af080ae91a455e7023e1a726c7714dc98e plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar
RUN echo '#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml

COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn install --frozen-lockfile --network-timeout 300000 && rm -rf "$(yarn cache dir)"

COPY packages/backend/dist/bundle.tar.gz app-config*.yaml ./
COPY catalog-info.yaml mkdocs.yaml ./
COPY docs ./docs

RUN java --version

RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["sh", "-c", "node packages/backend --config app-config.yaml"]
```

**Comment by awanlin** [comment]
Not sure why but once I added `format="svg_inline"` like this:

```markdown
```plantuml format="svg_inline"
@startuml
title Login Sequence
    ComponentA->ComponentB: Login Request
    note right of ComponentB: ComponentB logs message
    ComponentB->ComponentA: Login Response
@enduml```
```

I got an error about java missing in the Backstage UI logs you get when it generates. Why we didn't run into this before, I have no clue. In my example above where I say it works I had removed the `format="svg_inline"`. It's not needed but I had added it as part of my troubleshooting at it was mentioned here: https://backstage.io/docs/features/techdocs/troubleshooting#plantuml-with-svg_object-doesnt-render

**Comment by KatharinaSick** [comment]
First of all: Thank you for all the time you have put into this issue - you really helped me a lot!! :pray: :slightly_smiling_face: 

> But Java is missing!

I should definitely have noticed that :woman_facepalming: Especially because they are installing it in the [techdocs-container](https://github.com/backstage/techdocs-container/blob/main/Dockerfile) as well. Sorry for wasting your time with this stupid error.

**Comment by KatharinaSick** [comment]
![image](https://github.com/backstage/backstage/assets/9420018/77811510-64f0-43f1-aa2c-8cd6139d816b)

Thank you! :slightly_smiling_face: 
Oh, and happy new year :four_leaf_clover: :fireworks:

**Comment by KatharinaSick** [comment]
Closing, as everything works now :)

**Comment by awanlin** [comment]
@KatharinaSick glad you got it working on your end too! Happy New Year, all the best 🚀

**Comment by awanlin** [comment]
One last thing, you are using `node:18.17.1-bullseye-slim` and we recommend moving to `bookworm` as it's the current stable Debian version: https://www.debian.org/releases/. Generally it's a simple change but there are some extra changes for TechDocs around Python and virtual environments, more details are here: https://backstage.io/docs/features/techdocs/getting-started#disabling-docker-in-docker-situation-optional

**Comment by KatharinaSick** [comment]
Thank you! We'll change it then :) (We need to update to Node 20 anyways)

**Comment by Rycardas** [comment]
Thanks @awanlin , it helped a lot on my task. I followed the examples and finally plantuml get working!
