### ISSUE TITLE
🐛 Bug Report: GCS Location Wildcard Discovery

### ISSUE THREAD

**Issue by darrenyung** [backstage/backstage#21955]
### 📜 Description

I noticed this was [discussed](https://github.com/backstage/backstage/issues/12826) previously but there wasn't any conclusion. I did a test with wildcard as it was working for Github location discovery and it returned an error instead. Would appreciate some guidance in this space. 

Our team adoption is now growing very fast and it is starting to test the GitHub App rate limits. As an option, we are looking to move the catalog discovery to GCS. This also benefits a portion of our tribe that does not use GitHub or any version control system. 

### 👍 Expected behavior

Catalog discovery in GCS location works.

### 👎 Actual Behavior with Screenshots

Catalogues are not discovered in the bucket and error is printed out in the logs

### 👟 Reproduction steps

Set integration config as follows

```
    - type: url
      target: https://storage.cloud.google.com/{GCS_BUCKET}/catalogs/*.yaml
      rules:
        - allow: [Component]
```

### 📃 Provide the context for the Bug.

```
[1] 2023-12-20T03:46:03.727Z catalog warn Unable to read url, Error: No such object: {GCS_bucket}/catalogs/*.yaml type=plugin entity=location:default/generated-9167a33b97265a370fea11d42fbdf759e56b293d location=url:https://storage.cloud.google.com/{GCS_bucket}/catalogs/*.yaml
```

### 🖥️ Your Environment

OS:   Darwin 23.2.0 - darwin/x64
node: v18.17.1
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.20.3

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8
  @backstage/backend-common                                        0.19.9
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/backend-test-utils                                    0.2.8
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.11.2, 0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/dev-utils                                             1.0.24
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-api-docs                                       0.10.1
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.2.19, 0.4.1
  @backstage/plugin-badges-backend                                 0.3.4
  @backstage/plugin-badges                                         0.2.51
  @backstage/plugin-bazaar-backend                                 0.3.5
  @backstage/plugin-bazaar                                         0.2.19
  @backstage/plugin-catalog-backend-module-github                  0.4.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.1
  @backstage/plugin-catalog-import                                 0.10.3
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.9.1
  @backstage/plugin-catalog-unprocessed-entities                   0.1.5
  @backstage/plugin-catalog                                        1.15.1
  @backstage/plugin-cost-insights-common                           0.1.2
  @backstage/plugin-cost-insights                                  0.12.16
  @backstage/plugin-devtools-backend                               0.2.4
  @backstage/plugin-devtools-common                                0.1.6
  @backstage/plugin-devtools                                       0.1.6
  @backstage/plugin-entity-validation                              0.1.12
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.33
  @backstage/plugin-explore                                        0.4.13
  @backstage/plugin-github-actions                                 0.6.8
  @backstage/plugin-github-issues                                  0.2.16
  @backstage/plugin-github-pull-requests-board                     0.1.21
  @backstage/plugin-home-react                                     0.1.5
  @backstage/plugin-home                                           0.5.11
  @backstage/plugin-kubernetes-backend                             0.13.1
  @backstage/plugin-kubernetes-common                              0.7.1
  @backstage/plugin-kubernetes-node                                0.1.1
  @backstage/plugin-kubernetes-react                               0.1.1
  @backstage/plugin-kubernetes                                     0.11.2
  @backstage/plugin-org                                            0.6.17
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-playlist-backend                               0.3.11
  @backstage/plugin-playlist-common                                0.1.12
  @backstage/plugin-playlist                                       0.2.1
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.1
  @backstage/plugin-scaffolder                                     1.16.1
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-elasticsearch            1.3.10
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.3
  @backstage/plugin-shortcuts                                      0.3.16
  @backstage/plugin-sonarqube-backend                              0.2.9
  @backstage/plugin-sonarqube-react                                0.1.10
  @backstage/plugin-sonarqube                                      0.7.9
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.39
  @backstage/plugin-tech-insights-backend                          0.5.21
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.4.13
  @backstage/plugin-tech-insights                                  0.3.19
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-addons-test-utils                     1.0.24
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.1
  @backstage/plugin-todo-backend                                   0.3.5
  @backstage/plugin-todo                                           0.2.31
  @backstage/plugin-user-settings                                  0.7.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.2.19, 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 1.99s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
this looks like a limitation of the gcs url reader.
However there is a support for GitHub webhooks for pushing updates to Backstage, so that you don't get hit by rate limits. Here more info: https://backstage.io/docs/integrations/github/org#installation-with-events-support

**Comment by freben** [comment]
Note though that `target: https://storage.cloud.google.com/{GCS_BUCKET}/catalogs/*` might actually work (gcs only supports prefix filtering), but then it'll match all files, not just yaml if you mixed content there

**Comment by darrenyung** [comment]
> this looks like a limitation of the gcs url reader. However there is a support for GitHub webhooks for pushing updates to Backstage, so that you don't get hit by rate limits. Here more info: https://backstage.io/docs/integrations/github/org#installation-with-events-support

Thanks @vinzscam , I'll take a look.

> Note though that `target: https://storage.cloud.google.com/{GCS_BUCKET}/catalogs/*` might actually work (gcs only supports prefix filtering), but then it'll match all files, not just yaml if you mixed content there

@freben , I tried that but still met with the same error

```
2023-12-21T22:50:37.104Z catalog warn Unable to read url, Error: No such object: {GCS_BUCKET}/catalogs/* type=plugin entity=location:default/generated-8a0b5778932be92a083f4dc66e9fdcf1873d44a6 location=url:https://storage.cloud.google.com/{GCS_BUCKET}/*
```

On the other hand, single file works but this won't be a suitable solution for us if we were to make the directory a drop box for teams.

```
target: https://storage.cloud.google.com/{GCS_BUCKET}/catalogs/catalog.yaml
```

**Comment by Rugvip** [comment]
Looks like this is due to the following check here: https://github.com/backstage/backstage/blob/d8593ce0e6cd21c0ec61056dbb47d7a7c6b5ebf7/plugins/catalog-backend/src/modules/core/UrlReaderProcessor.ts#L127-L128

The `git-url-parse` doesn't properly parse the GCS URL, which we can't really expect it to do. What ends up happening is that `filepath` is empty and it fails the check for whether `readTree.search()` should be used. I **think** it should be safe to switch this over to a check with `new URL(...).pathname` instead, but would need to make sure that doesn't break anything.

**Comment by asoundarya96** [comment]
@Rugvip if URLReader is supporting GCS url, Git specific url parsing is not required. Also i can see `parseGitUrl ` is only used for check glob pattern. So it would be fine to use simple `URL().pathname`. Can i create a PR for this.

**Comment by armandocomellas1** [comment]
Hi all! just commenting that the pull request about this implementation has already submitted for more details you can redirecto to **https://github.com/backstage/backstage/issues/21955**

**Comment by darrenyung** [comment]
> Hi all! just commenting that the pull request about this implementation has already submitted for more details you can redirecto to **#22141**

Hey there @armandocomellas1! Just got back from my new year break. Many thanks for this! Had a quick look at this and tested it out after latest upgrade to 1.22.0. I'm wondering if I'm missing something? I'm getting this error in my local

```
2024-01-18T03:45:07.350Z catalog warn Unable to read url, Error: FetchUrlReader does not implement search type=plugin entity=location:default/generated-8a0b5778932be92a083f4dc66e9fdcf1873d44a6 location=url:https://storage.cloud.google.com/{GCS_BUCKET}/catalogs/*
```

**Comment by fable-creators** [comment]
> > Hi all! just commenting that the pull request about this implementation has already submitted for more details you can redirecto to **#22141**
> 
> Hey there @armandocomellas1! Just got back from my new year break. Many thanks for this! Had a quick look at this and tested it out after latest upgrade to 1.22.0. I'm wondering if I'm missing something? I'm getting this error in my local
> 
> ```
> 2024-01-18T03:45:07.350Z catalog warn Unable to read url, Error: FetchUrlReader does not implement search type=plugin entity=location:default/generated-8a0b5778932be92a083f4dc66e9fdcf1873d44a6 location=url:https://storage.cloud.google.com/{GCS_BUCKET}/catalogs/*
> ```

Hi @darrenyung,

thank for notice this. that is because the correct URL should be     
# Backstage Google Cloud Storage Location
    - type: url
      target: https://storage.cloud.google.com/{GCS_BUCKET}/*
      rules:
        - allow: [Component, Group, User]
    
So as you can notice the wildcard should be after the GCS_Bucket

Let me know if that worked for u

**Comment by freben** [comment]
Hey again - I think this might have been addressed by https://github.com/backstage/backstage/pull/22141 which was released two days ago. Could you give that a try?

**Comment by mgnisia** [comment]
@darrenyung I am facing this issue as well. It would be great if this already working to get an example how this is supposed to be working.

**Comment by darrenyung** [comment]
Apologies, yes its working to a certain degree. Set up guide I've followed is [here](https://backstage.io/docs/integrations/google-cloud-storage/locations).
