### ISSUE TITLE
🐛 Bug Report: AsyncAPI definition fails to load after 1.21.0 update

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#21950]
### 📜 Description

After updating to Backstage 1.21.0, the AsyncAPI definition cannot be rendered on component page anymore. 

### 👍 Expected behavior

The API definition is rendered like with version 1.20.3.

### 👎 Actual Behavior with Screenshots

![Screenshot 2023-12-20 at 9 44 02](https://github.com/backstage/backstage/assets/1178319/8c4be6f0-7c81-409c-9ffc-03ea4dcc4db8)

```
Error
SyntaxError

Message
Unexpected token ':'

Stack Trace
SyntaxError: Unexpected token ':'
    at new Function (<anonymous>)
    at Ajv.compileSchema (webpack-internal:///../../node_modules/@stoplight/spectral-core/node_modules/ajv/dist/compile/index.js:89:30)
    at Ajv._compileSchemaEnv (webpack-internal:///../../node_modules/@stoplight/spectral-core/node_modules/ajv/dist/core.js:472:37)
    at Ajv.compile (webpack-internal:///../../node_modules/@stoplight/spectral-core/node_modules/ajv/dist/core.js:159:38)
    at createRulesetFunction (webpack-internal:///../../node_modules/@stoplight/spectral-core/dist/ruleset/function.js:68:80)
    at eval (webpack-internal:///../../node_modules/@stoplight/spectral-functions/dist/alphabetical.js:30:64)
    at ../../node_modules/@stoplight/spectral-functions/dist/alphabetical.js (http://localhost:3000/vendors-node_modules_backstage_plugin-api-docs_dist_esm_AsyncApiDefinition-ed6a859d_esm_js.chunk.js:4696:1)
    at options.factory (http://localhost:3000/runtime.js:681:31)
    at __webpack_require__ (http://localhost:3000/runtime.js:36:33)
    at fn (http://localhost:3000/runtime.js:338:21)
```

### 👟 Reproduction steps

Create the following entity:

```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: streetlights
  description: The Smartylighting Streetlights API allows you to remotely manage the city lights.
  tags:
    - mqtt
  links:
    - url: https://github.com/asyncapi/asyncapi/blob/master/examples/1.2.0/streetlights.yml
      title: Source Code
      icon: code
spec:
  type: asyncapi
  lifecycle: production
  owner: team-c
  definition: |
    asyncapi: 2.0.0
    info:
      title: Streetlights API
      version: '1.0.0'
      description: |
        The Smartylighting Streetlights API allows you to remotely manage the city lights.
        ### Check out its awesome features:
        * Turn a specific streetlight on/off 🌃
        * Dim a specific streetlight 😎
        * Receive real-time information about environmental lighting conditions 📈
      license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0
    servers:
      production:
        url: api.streetlights.smartylighting.com:{port}
        protocol: mqtt
        description: Test broker
        variables:
          port:
            description: Secure connection (TLS) is available through port 8883.
            default: '1883'
            enum:
              - '1883'
              - '8883'
        security:
          - apiKey: []
          - supportedOauthFlows:
            - streetlights:on
            - streetlights:off
            - streetlights:dim
          - openIdConnectWellKnown: []
    defaultContentType: application/json
    channels:
      smartylighting/streetlights/1/0/event/{streetlightId}/lighting/measured:
        description: The topic on which measured values may be produced and consumed.
        parameters:
          streetlightId:
            $ref: '#/components/parameters/streetlightId'
        subscribe:
          summary: Receive information about environmental lighting conditions of a particular streetlight.
          operationId: receiveLightMeasurement
          traits:
            - $ref: '#/components/operationTraits/kafka'
          message:
            $ref: '#/components/messages/lightMeasured'
      smartylighting/streetlights/1/0/action/{streetlightId}/turn/on:
        parameters:
          streetlightId:
            $ref: '#/components/parameters/streetlightId'
        publish:
          operationId: turnOn
          traits:
            - $ref: '#/components/operationTraits/kafka'
          message:
            $ref: '#/components/messages/turnOnOff'
      smartylighting/streetlights/1/0/action/{streetlightId}/turn/off:
        parameters:
          streetlightId:
            $ref: '#/components/parameters/streetlightId'
        publish:
          operationId: turnOff
          traits:
            - $ref: '#/components/operationTraits/kafka'
          message:
            $ref: '#/components/messages/turnOnOff'
      smartylighting/streetlights/1/0/action/{streetlightId}/dim:
        parameters:
          streetlightId:
            $ref: '#/components/parameters/streetlightId'
        publish:
          operationId: dimLight
          traits:
            - $ref: '#/components/operationTraits/kafka'
          message:
            $ref: '#/components/messages/dimLight'
    components:
      messages:
        lightMeasured:
          name: lightMeasured
          title: Light measured
          summary: Inform about environmental lighting conditions for a particular streetlight.
          contentType: application/json
          traits:
            - $ref: '#/components/messageTraits/commonHeaders'
          payload:
            $ref: "#/components/schemas/lightMeasuredPayload"
        turnOnOff:
          name: turnOnOff
          title: Turn on/off
          summary: Command a particular streetlight to turn the lights on or off.
          traits:
            - $ref: '#/components/messageTraits/commonHeaders'
          payload:
            $ref: "#/components/schemas/turnOnOffPayload"
        dimLight:
          name: dimLight
          title: Dim light
          summary: Command a particular streetlight to dim the lights.
          traits:
            - $ref: '#/components/messageTraits/commonHeaders'
          payload:
            $ref: "#/components/schemas/dimLightPayload"
      schemas:
        lightMeasuredPayload:
          type: object
          properties:
            lumens:
              type: integer
              minimum: 0
              description: Light intensity measured in lumens.
            sentAt:
              $ref: "#/components/schemas/sentAt"
        turnOnOffPayload:
          type: object
          properties:
            command:
              type: string
              enum:
                - on
                - off
              description: Whether to turn on or off the light.
            sentAt:
              $ref: "#/components/schemas/sentAt"
        dimLightPayload:
          type: object
          properties:
            percentage:
              type: integer
              description: Percentage to which the light should be dimmed to.
              minimum: 0
              maximum: 100
            sentAt:
              $ref: "#/components/schemas/sentAt"
        sentAt:
          type: string
          format: date-time
          description: Date and time when the message was sent.
      securitySchemes:
        apiKey:
          type: apiKey
          in: user
          description: Provide your API key as the user and leave the password empty.
        supportedOauthFlows:
          type: oauth2
          description: Flows to support OAuth 2.0
          flows:
            implicit:
              authorizationUrl: 'https://authserver.example/auth'
              scopes:
                'streetlights:on': Ability to switch lights on
                'streetlights:off': Ability to switch lights off
                'streetlights:dim': Ability to dim the lights
            password:
              tokenUrl: 'https://authserver.example/token'
              scopes:
                'streetlights:on': Ability to switch lights on
                'streetlights:off': Ability to switch lights off
                'streetlights:dim': Ability to dim the lights
            clientCredentials:
              tokenUrl: 'https://authserver.example/token'
              scopes:
                'streetlights:on': Ability to switch lights on
                'streetlights:off': Ability to switch lights off
                'streetlights:dim': Ability to dim the lights
            authorizationCode:
              authorizationUrl: 'https://authserver.example/auth'
              tokenUrl: 'https://authserver.example/token'
              refreshUrl: 'https://authserver.example/refresh'
              scopes:
                'streetlights:on': Ability to switch lights on
                'streetlights:off': Ability to switch lights off
                'streetlights:dim': Ability to dim the lights
        openIdConnectWellKnown:
          type: openIdConnect
          openIdConnectUrl: 'https://authserver.example/.well-known'
      parameters:
        streetlightId:
          description: The ID of the streetlight.
          schema:
            type: string
      messageTraits:
        commonHeaders:
          headers:
            type: object
            properties:
              my-app-header:
                type: integer
                minimum: 0
                maximum: 100
      operationTraits:
        kafka:
          bindings:
            kafka:
              clientId: my-app-id
```

Go to that component page and see API definition.

### 🖥️ Your Environment

OS:   Darwin 23.1.0 - darwin/arm64
node: v18.15.0
yarn: 1.22.19
cli:  0.25.0 (installed)
backstage:  1.21.0

Dependencies:
  @backstage/app-defaults                                            1.4.6
  @backstage/backend-app-api                                         0.5.9
  @backstage/backend-common                                          0.17.0, 0.19.9, 0.20.0
  @backstage/backend-dev-utils                                       0.1.2
  @backstage/backend-openapi-utils                                   0.1.1
  @backstage/backend-plugin-api                                      0.6.8
  @backstage/backend-tasks                                           0.5.13
  @backstage/backend-test-utils                                      0.2.9
  @backstage/catalog-client                                          1.5.0
  @backstage/catalog-model                                           1.4.3
  @backstage/cli-common                                              0.1.13
  @backstage/cli-node                                                0.2.1
  @backstage/cli                                                     0.25.0
  @backstage/config-loader                                           1.6.0
  @backstage/config                                                  1.1.1
  @backstage/core-app-api                                            1.11.2
  @backstage/core-compat-api                                         0.1.0
  @backstage/core-components                                         0.12.5, 0.13.9
  @backstage/core-plugin-api                                         1.8.1
  @backstage/dev-utils                                               1.0.25
  @backstage/errors                                                  1.2.3
  @backstage/eslint-plugin                                           0.1.4
  @backstage/frontend-plugin-api                                     0.4.0
  @backstage/integration-aws-node                                    0.1.8
  @backstage/integration-react                                       1.1.22
  @backstage/integration                                             1.8.0
  @backstage/plugin-api-docs                                         0.10.2
  @backstage/plugin-app-backend                                      0.3.56
  @backstage/plugin-app-node                                         0.1.8
  @backstage/plugin-auth-backend-module-atlassian-provider           0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider             0.2.2
  @backstage/plugin-auth-backend-module-github-provider              0.1.5
  @backstage/plugin-auth-backend-module-gitlab-provider              0.1.5
  @backstage/plugin-auth-backend-module-google-provider              0.1.5
  @backstage/plugin-auth-backend-module-oauth2-provider              0.1.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider        0.1.0
  @backstage/plugin-auth-backend-module-okta-provider                0.0.1
  @backstage/plugin-auth-backend                                     0.20.1
  @backstage/plugin-auth-node                                        0.4.2
  @backstage/plugin-catalog-backend-module-aws                       0.3.2
  @backstage/plugin-catalog-backend-module-msgraph                   0.5.15
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model   0.1.5
  @backstage/plugin-catalog-backend-module-unprocessed               0.3.5
  @backstage/plugin-catalog-backend                                  1.16.0
  @backstage/plugin-catalog-common                                   1.0.19
  @backstage/plugin-catalog-graph                                    0.3.2
  @backstage/plugin-catalog-node                                     1.6.0
  @backstage/plugin-catalog-react                                    1.9.2
  @backstage/plugin-catalog-unprocessed-entities                     0.1.6
  @backstage/plugin-catalog                                          1.16.0
  @backstage/plugin-devtools-backend                                 0.2.5
  @backstage/plugin-devtools-common                                  0.1.7
  @backstage/plugin-devtools                                         0.1.7
  @backstage/plugin-entity-feedback-backend                          0.2.5
  @backstage/plugin-entity-feedback-common                           0.1.3
  @backstage/plugin-entity-feedback                                  0.2.11
  @backstage/plugin-events-node                                      0.2.17
  @backstage/plugin-github-actions                                   0.6.9
  @backstage/plugin-home-react                                       0.1.6
  @backstage/plugin-home                                             0.6.0
  @backstage/plugin-jenkins-backend                                  0.3.2
  @backstage/plugin-jenkins-common                                   0.1.22
  @backstage/plugin-jenkins                                          0.9.3
  @backstage/plugin-kubernetes-common                                0.7.2
  @backstage/plugin-org                                              0.6.18
  @backstage/plugin-permission-backend                               0.5.31
  @backstage/plugin-permission-common                                0.7.11
  @backstage/plugin-permission-node                                  0.7.19
  @backstage/plugin-permission-react                                 0.4.18
  @backstage/plugin-proxy-backend                                    0.4.6
  @backstage/plugin-scaffolder-backend-module-azure                  0.1.0
  @backstage/plugin-scaffolder-backend-module-bitbucket              0.1.0
  @backstage/plugin-scaffolder-backend-module-confluence-to-markdown 0.2.9
  @backstage/plugin-scaffolder-backend-module-cookiecutter           0.2.32
  @backstage/plugin-scaffolder-backend-module-gerrit                 0.1.0
  @backstage/plugin-scaffolder-backend-module-github                 0.1.0
  @backstage/plugin-scaffolder-backend-module-gitlab                 0.2.11
  @backstage/plugin-scaffolder-backend                               1.19.2
  @backstage/plugin-scaffolder-common                                1.4.4
  @backstage/plugin-scaffolder-node                                  0.2.9
  @backstage/plugin-scaffolder-react                                 1.7.0
  @backstage/plugin-scaffolder                                       1.17.0
  @backstage/plugin-search-backend-module-catalog                    0.1.12
  @backstage/plugin-search-backend-module-elasticsearch              1.3.11
  @backstage/plugin-search-backend-module-techdocs                   0.1.12
  @backstage/plugin-search-backend-node                              1.2.12
  @backstage/plugin-search-backend                                   1.4.8
  @backstage/plugin-search-common                                    1.2.9
  @backstage/plugin-search-react                                     1.7.4
  @backstage/plugin-search                                           1.4.4
  @backstage/plugin-sonarqube-backend                                0.2.10
  @backstage/plugin-sonarqube-react                                  0.1.11
  @backstage/plugin-sonarqube                                        0.7.10
  @backstage/plugin-techdocs-backend                                 1.9.1
  @backstage/plugin-techdocs-node                                    1.11.0
  @backstage/plugin-techdocs-react                                   1.1.14
  @backstage/plugin-techdocs                                         1.9.2
  @backstage/plugin-user-settings                                    0.7.14
  @backstage/release-manifests                                       0.0.11
  @backstage/test-utils                                              1.4.6
  @backstage/theme                                                   0.2.19, 0.4.4, 0.5.0
  @backstage/types                                                   1.1.1
  @backstage/version-bridge                                          1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
![image](https://github.com/backstage/backstage/assets/1178319/53411f32-a2ab-41bd-bab2-dd6bcf04e54c)
It's one of these updates that breaks the thing. Maybe there's a version mismatch with stoplight packages or something?

**Comment by drodil** [comment]
Here are the versions in use:
```
└─┬ app@0.0.0 -> ./packages/app
  └─┬ @backstage/plugin-api-docs@0.10.2
    └─┬ @asyncapi/react-component@1.2.6
      └─┬ @asyncapi/parser@3.0.2
        ├── @stoplight/spectral-core@1.18.3
        └─┬ @stoplight/spectral-functions@1.7.2
          ├── @stoplight/spectral-core@1.18.3 deduped
          └─┬ @stoplight/spectral-formats@1.6.0
            └── @stoplight/spectral-core@1.18.3 deduped
```

**Comment by freben** [comment]
This type of thing seems to have happened before. https://github.com/stoplightio/spectral/issues/2003

**Comment by freben** [comment]
See also the linked https://github.com/stoplightio/spectral/issues/1808 about possible ajv duplicates

**Comment by drodil** [comment]
Yeah it was ajv duplicate issue, will close this now.
