### ISSUE TITLE
🚀 Feature: allow whitelisting built-in scaffolder actions in the new backend system

### ISSUE THREAD

**Issue by zcmander** [backstage/backstage#21965]
### 🔖 Feature description

An another war story from my experimentation with the new backend system: There should be way to whitelist actions that will be registered by default. I guess the most sensible option would be moving all built-in actions into separate scaffolder module, so there's way to just replace the built-in plugin with customized one, or as we now have separate plugins for external services like:

* @backstage/plugin-scaffolder-module-github
* @backstage/plugin-scaffolder-module-gitlab
* @backstage/plugin-scaffolder-module-azure

It would make sense that they do not belong in the built-in plugin (maybe `@backstage/plugin-scaffolder-module-builtins` or something like that).

Relates to the RFC: https://github.com/backstage/backstage/issues/21442

The issue is in the scaffolder plugin itself:

https://github.com/backstage/backstage/blob/6ce9928c44c53a4ea939536cbe31ffc1a129c00d/plugins/scaffolder-backend/src/ScaffolderPlugin.ts#L97C14-L97C34

```typescript
        const actions = [
          ...addedActions,
          ...createBuiltinActions({
            integrations: ScmIntegrations.fromConfig(config),
            catalogClient,
            reader,
            config,
            additionalTemplateFilters,
            additionalTemplateGlobals,
          }),
        ];
```
So, in addition to initializing scaffolder plugin it also forces to register built-in plugin whether you want them or not.

### 🎤 Context

The context here relies on the RFC:

> As an adopter, I do not have an integration for gitlab or azure. Yet, the scaffolder include code that may contain CVEs for those integrations that I cant remove.

### ✌️ Possible Implementation

Please check the RFC for reference; it describes creation of the `@backstage/plugin-scaffolder-module-builtins` and that could adopt the new backend system as well.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
Thinking it would make sense to remove all built-in actions except the ones provided by the scaffolder backend itself for the `/alpha` plugin. Thoughts @backstage/scaffolder-maintainers?

**Comment by aaronnickovich** [comment]
The scaffolder plugins were added to their own modules so it's possible to add the modules without using the built-ins. Whitelisting is possible by just including github or whatever the integrator uses as a SCM. I like Rugvip's idea with /alpha
