### ISSUE TITLE
🐛 Bug Report: Unable to Unregister Entity From Catalog (v1.21.0)

### ISSUE THREAD

**Issue by cftad** [backstage/backstage#21962]
### 📜 Description

We recently upgraded from `1.20.3` to `1.21.0` and began to see the following issue with when attempting to unregister an entity from the catalog. 

### 👍 Expected behavior

It should unregister the entity.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/6119545/034990c0-fa54-4adc-8703-1895414b7d32)

### 👟 Reproduction steps

1. Go to a catalog entity
2. Attempt to 'Unregister entity'

### 📃 Provide the context for the Bug.

Stack Trace
```
error: select * from "locations" where "id" = $1 - invalid input syntax for type uuid: "url:https://dev.azure.com/company/project/_git/Repo?path=/catalog-info.yaml"
    at Parser.parseErrorMessage (C:\Dev\Repositories\Backstage
ode_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (C:\Dev\Repositories\Backstage
ode_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (C:\Dev\Repositories\Backstage
ode_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (C:\Dev\Repositories\Backstage
ode_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Readable.push (node:internal/streams/readable:245:10)
```    
    

### 🖥️ Your Environment

 yarn why pg
├─ @backstage/backend-common@npm:0.19.9
│  └─ pg@npm:8.11.3 (via npm:^8.11.3)
│
├─ @backstage/backend-common@npm:0.20.0
│  └─ pg@npm:8.11.3 (via npm:^8.11.3)
│
├─ @backstage/backend-common@npm:0.20.0 [19de8]
│  └─ pg@npm:8.11.3 [2959d] (via npm:^8.11.3 [2959d])
│
├─ @backstage/backend-common@npm:0.19.9 [3b8b1]
│  └─ pg@npm:8.11.3 [2959d] (via npm:^8.11.3 [2959d])
│
└─ backend@workspace:packages/backend
   └─ pg@npm:8.11.3 [2959d] (via npm:^8.11.3 [2959d])

**Backstage CLI Info** 

OS:   Windows_NT 10.0.22631 - win32/x64
node: v18.18.2
yarn: 4.0.2
cli:  0.25.0 (installed)
backstage:  1.21.0

Dependencies:
  @backstage/app-defaults                                          1.4.6
  @backstage/backend-app-api                                       0.5.9
  @backstage/backend-common                                        0.19.9, 0.20.0
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.1
  @backstage/backend-plugin-api                                    0.6.8
  @backstage/backend-tasks                                         0.5.13
  @backstage/catalog-client                                        1.5.0
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.1
  @backstage/cli                                                   0.25.0
  @backstage/config-loader                                         1.6.0
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.2
  @backstage/core-compat-api                                       0.1.0
  @backstage/core-components                                       0.13.9
  @backstage/core-plugin-api                                       1.8.1
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.4.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.22
  @backstage/integration                                           1.8.0
  @backstage/plugin-adr-backend                                    0.4.5
  @backstage/plugin-adr-common                                     0.2.18
  @backstage/plugin-adr                                            0.6.11
  @backstage/plugin-api-docs                                       0.10.2
  @backstage/plugin-app-backend                                    0.3.56
  @backstage/plugin-app-node                                       0.1.8
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.2
  @backstage/plugin-auth-backend-module-github-provider            0.1.5
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.5
  @backstage/plugin-auth-backend-module-google-provider            0.1.5
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.0
  @backstage/plugin-auth-backend-module-okta-provider              0.0.1
  @backstage/plugin-auth-backend                                   0.20.1
  @backstage/plugin-auth-node                                      0.2.19, 0.4.2
  @backstage/plugin-azure-devops-backend                           0.5.0
  @backstage/plugin-azure-devops-common                            0.3.2
  @backstage/plugin-azure-devops                                   0.3.10
  @backstage/plugin-bazaar-backend                                 0.3.6
  @backstage/plugin-bazaar                                         0.2.20
  @backstage/plugin-catalog-backend-module-azure                   0.1.27
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.15
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.5
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.5
  @backstage/plugin-catalog-backend                                1.16.0
  @backstage/plugin-catalog-common                                 1.0.19
  @backstage/plugin-catalog-graph                                  0.3.2
  @backstage/plugin-catalog-import                                 0.10.4
  @backstage/plugin-catalog-node                                   1.6.0
  @backstage/plugin-catalog-react                                  1.9.2
  @backstage/plugin-catalog-unprocessed-entities                   0.1.6
  @backstage/plugin-catalog                                        1.16.0
  @backstage/plugin-devtools-backend                               0.2.5
  @backstage/plugin-devtools-common                                0.1.7
  @backstage/plugin-devtools                                       0.1.7
  @backstage/plugin-events-node                                    0.2.17
  @backstage/plugin-explore-backend                                0.0.18
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.34
  @backstage/plugin-explore                                        0.4.14
  @backstage/plugin-github-actions                                 0.6.9
  @backstage/plugin-home-react                                     0.1.6
  @backstage/plugin-home                                           0.6.0
  @backstage/plugin-org                                            0.6.18
  @backstage/plugin-permission-backend                             0.5.31
  @backstage/plugin-permission-common                              0.7.11
  @backstage/plugin-permission-node                                0.7.19
  @backstage/plugin-permission-react                               0.4.18
  @backstage/plugin-playlist-backend                               0.3.12
  @backstage/plugin-playlist-common                                0.1.13
  @backstage/plugin-playlist                                       0.2.2
  @backstage/plugin-proxy-backend                                  0.4.6
  @backstage/plugin-scaffolder-backend-module-azure                0.1.0
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.0
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.0
  @backstage/plugin-scaffolder-backend-module-github               0.1.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.11
  @backstage/plugin-scaffolder-backend                             1.19.2
  @backstage/plugin-scaffolder-common                              1.4.4
  @backstage/plugin-scaffolder-node                                0.2.9
  @backstage/plugin-scaffolder-react                               1.7.0
  @backstage/plugin-scaffolder                                     1.17.0
  @backstage/plugin-search-backend-module-catalog                  0.1.12
  @backstage/plugin-search-backend-module-elasticsearch            1.3.11
  @backstage/plugin-search-backend-module-explore                  0.1.12
  @backstage/plugin-search-backend-module-techdocs                 0.1.12
  @backstage/plugin-search-backend-node                            1.2.12
  @backstage/plugin-search-backend                                 1.4.8
  @backstage/plugin-search-common                                  1.2.9
  @backstage/plugin-search-react                                   1.7.4
  @backstage/plugin-search                                         1.4.4
  @backstage/plugin-shortcuts                                      0.3.17
  @backstage/plugin-tech-radar                                     0.6.11
  @backstage/plugin-techdocs-backend                               1.9.1
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.3
  @backstage/plugin-techdocs-node                                  1.11.0
  @backstage/plugin-techdocs-react                                 1.1.14
  @backstage/plugin-techdocs                                       1.9.2
  @backstage/plugin-todo-backend                                   0.3.6
  @backstage/plugin-todo                                           0.2.32
  @backstage/plugin-user-settings                                  0.7.14
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.6
  @backstage/theme                                                 0.4.4, 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
Oh indeed, thanks for reporting - this was introduced during the recent OpenAPI schema rewrites. I'll make a patch for it ASAP during the day.

**Comment by Antrakos** [comment]
For those facing this issue even after the bump to 1.21.1 run `yarn dedupe @backstage/catalog-client`. 

In my case @backstage/plugin-catalog had 1.5.0 in `yarn.lock` so I had to force a refresh of the dependency version so that everything was aligned on 1.5.1
