### ISSUE TITLE
🚀 Feature: Smart Kubernetes proxy

### ISSUE THREAD

**Issue by jorgemoralespou** [backstage/backstage#21960]
### 🔖 Feature description

Currently there's a [Kubernetes proxy feature](https://backstage.io/docs/features/kubernetes/proxy) that should be as smart as the built-in kubernetes fetcher for local clusters. 

Quoting from [Backstage kubernetes config docs](https://backstage.io/docs/features/kubernetes/configuration) for the kubernetes integration:

> If a cluster has authProvider: serviceAccount and the serviceAccountToken field is omitted, Backstage will ignore the configured URL and certificate data, instead attempting to access the Kubernetes API via an in-cluster client

Kubernetes Proxy should function the same way when the cluster being accessed is a cluster configured in this way, so that skipTLSVerify is not needed, as certs are present at the pod level, and url is known as it's the internal kubernetes.svc

### 🎤 Context

I have a cluster configured with the following config:

```
  kubernetes:
    clusterLocatorMethods:
      - type: 'config'
        clusters:
          - url: kubernetes.default.svc.cluster.local:443
            name: local
            authProvider: 'serviceAccount'
            skipTLSVerify: false
            skipMetricsLookup: true
```

Since authProvider is `serviceAccount` all kubernetes core features just work fine. When using the proxy, with a code similar to this:
```
    try {
      // return this.kubernetesProxyApi.getPodLogs({
      //   podName: 'testapp-8478dc4679-blpb7',
      //   containerName: 'testapp',
      //   namespace: 'testapp',
      //   clusterName: this.CLUSTER_NAME,
      // });
      return await this.kubernetesApi
        .proxy({
          clusterName: 'local',
          path: `/apis/training.educates.dev/v1beta1/trainingportals`,
          init: {
            method: 'GET',
          },
        })
        .then(response => this.handleJson(response))
        .then(text => ({ text }));
    } catch (err) {
      // eslint-disable-next-line no-console
      console.error(err);
      return { text: 'Error' };
    }
```

Proxy functionality fails with following error:
```
{"error":{"name":"Error","message":"Cluster 'local' request error; caused by Error: connect ECONNREFUSED ::1:80","cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"::1","port":80,"name":"Error","message":"connect ECONNREFUSED ::1:80","stack":"Error: connect ECONNREFUSED ::1:80\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)"},"level":"error"},"request":{"method":"GET","url":"/api/kubernetes/proxy/apis/training.educates.dev/v1beta1/trainingportals"},"response":{"statusCode":500}}
```

As can be seen, it's trying to access port 80. We then add `https://` prefix to the url, leaving it like: `https://kubernetes.default.svc.cluster.local:443` and now we get this other error:

```
{"cluster":"local","level":"info","message":"[HPM] Proxy created: /  -> undefined","plugin":"kubernetes","service":"backstage","type":"plugin"}
{"cause":{"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"},"cluster":"local","level":"error","message":"Cluster 'local' request error; caused by Error: unable to verify the first certificate","name":"Error","plugin":"kubernetes","service":"backstage","stack":"Error: Cluster 'local' request error; caused by Error: unable to verify the first certificate\n    at ProxyServer.onError (/app/node_modules/@backstage/plugin-kubernetes-backend/dist/index.cjs.js:1268:32)\n    at ProxyServer.emit (/app/node_modules/eventemitter3/index.js:210:27)\n    at ClientRequest.proxyError (/app/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:165:18)\n    at ClientRequest.emit (node:events:529:35)\n    at TLSSocket.socketErrorListener (node:_http_client:501:9)\n    at TLSSocket.emit (node:events:517:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","type":"plugin"}
```

As it's trying to verify the certificate, and since it's the internal autogenerated cert, it fails. Adding `skipTLSVerify: true` finally get it working.

### ✌️ Possible Implementation

Kubernetes proxy should be as smart as Kubernetes integration and in case of `authProvider: serviceAccount` it should use internal endpoint and certs and not complain. 

In fact, in this scenario, minimal configuration should be like this:
```
  kubernetes:
    clusterLocatorMethods:
      - type: 'config'
        clusters:
          - name: local
            authProvider: 'serviceAccount'
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jamieklassen** [comment]
This is definitely a sensible feature. Implementation-wise, it's too bad this "in-cluster" logic is spread across two places: resolving the bearer token happens in the `ServiceAccountStrategy`:

https://github.com/backstage/backstage/blob/31783a711c95bb0b086ede100e77ed2390ae7110/plugins/kubernetes-backend/src/auth/ServiceAccountStrategy.ts#L34-L43

whereas resolving the CA happens in the fetcher itself:

https://github.com/backstage/backstage/blob/31783a711c95bb0b086ede100e77ed2390ae7110/plugins/kubernetes-backend/src/service/KubernetesFetcher.ts#L293-L303
