### ISSUE TITLE
🚀 Feature: Techdocs customized theme

### ISSUE THREAD

**Issue by luis-k0** [backstage/backstage#21999]
### 🔖 Feature description

Allows to customize the colors and presentation of some techdoc elements, initially for code snippets and tables but can be extended to other elements.
The proposal for this feature is based on this [Discord thread](https://discord.com/channels/687207715902193673/1144610457144008764).

### 🎤 Context

The colors and presentation of current code snippets and tables are difficult to visualize, here are some examples:

Code snippets in Backstage:
![image](https://github.com/backstage/backstage/assets/44954252/f24d63fa-93c5-4c2f-9e2c-5e4355deb23e)

Code snippets in Gitlab as an example:
![image](https://github.com/backstage/backstage/assets/44954252/7bf433af-2550-4e0c-a476-eb44f4a27ab1)

Tables in the Backstage:
![image](https://github.com/backstage/backstage/assets/44954252/05478216-6f7b-4def-86ee-994e4404cbb3)

Tables in Gitlab as an example:
![image](https://github.com/backstage/backstage/assets/44954252/fdedb5a9-a629-4d89-8cd2-53a4aaf07316)

### ✌️ Possible Implementation

Allow the techdocs plugin to receive customized color and presentation themes to present the techdoc.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @luis-k0, the Discord link doesn't seem to work for me, can you double check that, please?

**Comment by luis-k0** [comment]
> Hi @luis-k0, the Discord link doesn't seem to work for me, can you double check that, please?

Hi @awanlin , I checked and worked for me.
This is the link: https://discord.com/channels/687207715902193673/714754240933003266/1144610457144008764
Can you try again?

**Comment by awanlin** [comment]
Yeah, I was getting an error, now I think I got where you are pointing to. Thanks! 

Could we use the link to the thread instead, just makes it more clear exactly the content: https://discord.com/channels/687207715902193673/1144610457144008764

**Comment by luis-k0** [comment]
> Yeah, I was getting an error, now I think I got where you are pointing to. Thanks!
> 
> Could we use the link to the thread instead, just makes it more clear exactly the content: https://discord.com/channels/687207715902193673/1144610457144008764

Link fixed! thanks.

**Comment by luis-k0** [comment]
Hi guys! I opened this PR for this issue. Please take a look when you can:
https://github.com/backstage/backstage/pull/22110

**Comment by luis-k0** [comment]
Hi guys! I opened another PR changing how `code` tags are shown trying to improve table visualization: https://github.com/backstage/backstage/pull/22155

But this PR will change the way <code> tags will be shown in techdocs, I would like to discuss a way to make the application of this change customizable by the user, some configuration for the user to choose whether or not to use this way of presenting <code> tags in techdocs.

Feel free to comment on the PR.
