### ISSUE TITLE
🐛 Bug Report: Cant run standalone backend plugin 

### ISSUE THREAD

**Issue by swapnilp0x00** [backstage/backstage#21996]
### 📜 Description

https://backstage.io/docs/plugins/backend-plugin

Following these instructions to create backend plugin but seem, it doesn't work.
When I create a frontend plugin there is dev folder inside it.
When I create backend plugin there is NO dev folder inside it, but Readme.MD generated for backend plugin has this line
`It is only meant for local development, and the setup for it can be found inside the [/dev](/dev) directory.`

`cd plugins/<backend-plugin>`
`yarn start`

just stucks

### 👍 Expected behavior

It should start backend plugin node js server and API should be accessible on 

`localhost:7007/<plugin-name>`

### 👎 Actual Behavior with Screenshots

yarn start stucks.

### 👟 Reproduction steps

Following the steps in documentation itself - https://backstage.io/docs/plugins/backend-plugin

`yarn new --select backend-plugin`
`cd plugins/<backend-plugin>`
`yarn start`

### 📃 Provide the context for the Bug.

I created frontend plugin and I can run standalone frontend plugin by going into plugin directory
`cd plugins/<frontned-plugin>`
`yarn start`

Starts SPA with react components.

But similar thing is not working standalone backend plugin.

Yarn start just stucks forever.

### 🖥️ Your Environment

NVM version 20
Yarn version v1.22.21
MAC OS SONOMA 14.11

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @swapnilp0x00, sorry you had issues with this. There's a bit of a transition going on to a [New Backend System](https://backstage.io/docs/backend-system/) and this documentation isn't right as you have seen. If you run `LEGACY_BACKEND_START=true yarn start` that should get things working. A PR to update the docs with this just got merged today. Might take a bit for the docs to reflect the change though, that build is really slow 🐌

**Comment by jgentes** [comment]
I think what you're looking for is `yarn start-backend`
