### ISSUE TITLE
🐛 Bug Report: Table remounts whole MaterialTable on data change if emptyContent prop is present

### ISSUE THREAD

**Issue by zhammer** [backstage/backstage#22008]
### 📜 Description

If the `emptyContent` prop is provided to @backstage/core-components's `Table` component, every time the `data` prop changes, the entire underlying `MaterialTable` component will remount.

### 👍 Expected behavior

Row data should cause components in the `MaterialTable` to re-render, not re-mount, whether or not `emptyContent` is set.

### 👎 Actual Behavior with Screenshots

One a 1 second data update interval, we see the rows get remounted on our Table that has an `emptyContent` prop. See repo, provided below, for reproduction.

https://github.com/backstage/backstage/assets/6956487/8080f3b0-7e57-4a40-8448-f25ed0f933bd

### 👟 Reproduction steps

Here's a repo where you can reproduce the bug: https://github.com/zhammer/backstage-table-mount-bug/commit/8a19e8e45ab0c1092c52c177a97256413104a87c.

### 📃 Provide the context for the Bug.

We would like to use the `Table` component to show live data polled from APIs. Currently, when state is re-fetched, the entire `Table` re-mounts. It provides a poor UX: state is lost, components flicker, active `Tooltip`s on rows dissappear.

Luckily we've pinpointed this behavior to the presence of the `emptyContent=` prop so can work around it for now. (It took a _very_ long time.)

### 🖥️ Your Environment

```
OS:   Darwin 21.6.0 - darwin/arm64
node: v20.10.0
yarn: 1.22.19
cli:  0.25.0 (installed)
backstage:  1.21.0

Dependencies:
✨  Done in 0.48s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by zhammer** [comment]
i'm guessing it has something to do with this: https://github.com/backstage/backstage/blob/ddbed9a6dc34ffba78297c1788c73df05bcac5e0/packages/core-components/src/components/Table/Table.tsx#L418-L421

though i'm not sure why that `useMemo` hook is running at all

**Comment by Rugvip** [comment]
Thank you for reporting, good find! 👍 

The `useMemo` is triggering because `emptyContent` is switched on every render of the parent, since it's a new `<div>empty</div>` every time. One solution would be to memo the empty content in the parent, but that feels silly and like a huge foot-gun. Not entirely sure what the best fix is though, maybe there are some existing `MTableBody` props that we can use instead of creating a closure where we pass in our own?

**Comment by juvi07** [comment]
Hi @zhammer @Rugvip I did some digging into this issue and discovered the table component is not actually remounting but rather it's re-rendering when `data` props changes. The `emptyContent` prop is only shown when data is empty. The useMemo feels like a seperate optimisation issue and base on my findings I would suggest that this can be closed. If you still feel that this is an issue, I'll need more detailed steps for reproduction.

**Comment by Rugvip** [comment]
@juvi07 hmm, did you try that in a setup where you had the `emptyContent` element update on each render? For example this one: https://github.com/backstage/backstage/blob/1bdcf6bb7a84ce628b8c8a146585e2b9bdcab0e5/plugins/vault/src/components/EntityVaultTable/EntityVaultTable.tsx#L111
