### ISSUE TITLE
🐛 Bug Report: Gerrit +/refs/tag/x.x.x/  location not working!

### ISSUE THREAD

**Issue by emichaf** [backstage/backstage#22053]
### 📜 Description

Using Gerrit tags in source code repos containing catalog-info.yaml file to point at specific versions to be visualized in Backstage.

Uploading locations.yaml to S3 bucket, with content 
targets:
    - https://gerrit.mycompany.com/plugins/gitiles/microservice1/+/refs/tags/1.0.112/catalog-info.yaml

Backstage can't handle +/refs/tags/x.x.x  for location nor rendering techdocs

Note: its working when using branch master, ex .. +/refs/heads/master/catalog-info.yaml

### 👍 Expected behavior

Location paths containing gerrit...  +/refs/tags/x.x.x/catalog-info.yaml should work 

also techdocs rendering via ex backstage.io/techdocs-ref should work: url:https://gerrit.mycompany.com/plugins/gitiles/microservice1/+/refs/tags/1.0.112

### 👎 Actual Behavior with Screenshots

Error msg:

"Unable to read url, Error: Unable to parse branch from url: https://gerrit.mycompany.com/plugins/gitiles/microservice1/+/refs/tags/1.0.112/catalog-info.yaml","service_id":"backstage","severity":"info","timestamp":"2023-12-29T10:17:25.430Z","version":"1.2.0"}

Building a newer version of this documentation failed. Error: "Unable to parse branch from url: https://gerrit.mycompany.com/plugins/gitiles/microservice1/+/refs/tags/1.0.112"

error: Failed to build the docs page for entity component:default/microservice1: Unable to parse branch from url: https://gerrit.mycompany.com/plugins/gitiles/microservice1/+/refs/tags/1.0.112, Opens in a new window {"timestamp":"2023-12-29T11:20:31.417Z"}

### 👟 Reproduction steps

1. Create a location.yaml file:

apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ms-locations
spec:
  type: url
  targets:
    - https://gerrit.mycompany.com/plugins/gitiles/microservice1/+/refs/tags/1.0.112/catalog-info.yaml

Add location in Backstage, via UI or via S3 bucket (configured s3 provider)

Error msg:

"Unable to read url, Error: Unable to parse branch from url: https://gerrit.mycompany.com/plugins/gitiles/microservice1/+/refs/tags/1.0.112/catalog-info.yaml","service_id":"backstage","severity":"info","timestamp":"2023-12-29T10:17:25.430Z","version":"1.2.0"}

2. Create a catalog-info.yaml file:
including
backstage.io/techdocs-ref: url:https://gerrit.mycompany.com/plugins/gitiles/microservice1/+/refs/tags/1.0.112

When opening techdocs for component in UI: throws error
Building a newer version of this documentation failed. Error: "Unable to parse branch from url: https://gerrit.mycompany.com/plugins/gitiles/microservice1/+/refs/tags/1.0.112"

error: Failed to build the docs page for entity component:default/microservice1: Unable to parse branch from url: https://gerrit.mycompany.com/plugins/gitiles/microservice1/+/refs/tags/1.0.112, Opens in a new window {"timestamp":"2023-12-29T11:20:31.417Z"}

### 🖥️ Your Environment

OS:   Linux 5.15.133.1-microsoft-standard-WSL2 - linux/x64
node: v18.17.1
yarn: 3.2.3
cli:  0.24.0 (installed)
backstage:  1.20.3

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8, 0.5.9
  @backstage/backend-common                                        0.19.9, 0.20.0
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7, 0.6.8
  @backstage/backend-tasks                                         0.5.12, 0.5.13
  @backstage/backend-test-utils                                    0.2.8
  @backstage/catalog-client                                        1.4.6, 1.5.1
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0, 0.2.1
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3, 1.6.0
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/dev-utils                                             1.0.24
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2, 1.8.0
  @backstage/plugin-api-docs                                       0.10.1
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.19.4, 0.20.0
  @backstage/plugin-auth-node                                      0.3.1, 0.4.1, 0.4.2
  @backstage/plugin-catalog-backend-module-aws                     0.3.2
  @backstage/plugin-catalog-backend-module-gerrit                  0.1.23
  @backstage/plugin-catalog-backend-module-ldap                    0.5.22
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18, 1.0.19
  @backstage/plugin-catalog-graph                                  0.3.1
  @backstage/plugin-catalog-import                                 0.10.3
  @backstage/plugin-catalog-node                                   1.5.0, 1.6.0
  @backstage/plugin-catalog-react                                  1.9.0, 1.9.1
  @backstage/plugin-catalog                                        1.15.1
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-github-actions                                 0.6.8
  @backstage/plugin-home-react                                     0.1.5
  @backstage/plugin-jira-dashboard-backend                         0.0.0-use.local
  @backstage/plugin-jira-dashboard-common                          0.0.0-use.local
  @backstage/plugin-jira-dashboard                                 0.0.0-use.local
  @backstage/plugin-kubernetes-common                              0.7.2
  @backstage/plugin-org                                            0.6.17
  @backstage/plugin-permission-common                              0.7.10, 0.7.11
  @backstage/plugin-permission-node                                0.7.18, 0.7.19
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.1
  @backstage/plugin-scaffolder                                     1.16.1
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8, 1.2.9
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.3
  @backstage/plugin-sonarqube-backend                              0.2.9
  @backstage/plugin-sonarqube-react                                0.1.10
  @backstage/plugin-sonarqube                                      0.7.9
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.1
  @backstage/plugin-user-settings                                  0.7.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.3.0, 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by emichaf** [comment]
https://github.com/backstage/backstage/blob/master/packages/integration/src/gerrit/core.ts#L70    looks like only refs/heads/.. is supported, would it be possible to add support for refs/tags/.. also?

**Comment by tudi2d** [comment]
Thanks for highlighting this! Would you be up for submitting a PR to fix this?
