### ISSUE TITLE
🚀 Feature: [Getting Started] Korean translation.

### ISSUE THREAD

**Issue by yj-yoo** [backstage/backstage#22073]
### 🔖 Feature description

Happy New Year!!!
I added issue [111](https://github.com/backstage/backstage/issues/21860) last time, And now I'm trying to translate the "Getting started" document into Korean.

### 🎤 Context

After the last Korean translation work, Some Korean users seem to have responded well. Several Korean users responded positively to the last Korean translation work. However, since there are still a lot of English documents, it seems difficult to understand the system, so I plan to proceed with additional Korean translation (Getting started first).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
```[tasklist]
### Tasks
```

**Comment by benjdlambert** [comment]
Thanks! :pray: There's actually a large amount of work going on to restructure and rewrite some of our documentation. Think that it makes sense to start with the getting started, but wouldn't dive to much into the other parts of the documentation just yet.

**Comment by yj-yoo** [comment]
@benjdlambert 
Oh... I see. We've done a lot of work and sent out PRs, but the chances of it being merged are low. I'll have to contribute again when the document is restructure. Thanks :)

**Comment by yj-yoo** [comment]
@benjdlambert So would it be helpful to translate the README of the plugin (backstage/plugins/xxx)?

**Comment by camilaibs** [comment]
Hi @yj-yoo, we don't think it's worth translating README of plugins for now...
But the contribution guide is something we would like to translate and would appreciate your contribution 🙂

**Comment by yj-yoo** [comment]
@camilaibs 
hi.
Oh... I understand. I'll try it!
Thanks :)
