### ISSUE TITLE
🐛 Bug Report: Techdocs fail for large repositories

### ISSUE THREAD

**Issue by KatharinaSick** [backstage/backstage#22081]
### 📜 Description

Backstage fails to build TechDocs when the repositories are very large. The reason for this is, that when building TechDocs in the repository root, Backstage fetches the whole repository as an archive instead of just fetching the files it needs.

### 👍 Expected behavior

The described behavior is fine for most use-cases but this doesn't work for one of our repositories. Therefore, I would expect Backstage to only fetch the files it needs (`catalog-info.yaml`, `mkdocs.yaml` & the directory that contains the docs).

### 👎 Actual Behavior with Screenshots

Rendering TechDocs takes ages and then fails with the error `Premature close`.

![screenshot-2 (1)](https://github.com/backstage/backstage/assets/9420018/965323ee-d7de-45ae-9181-b74345e361d1)

### 👟 Reproduction steps

1. Have a very large repository
2. Add TechDocs
3. 🔥

### 🖥️ Your Environment

I reproduced the issue in multiple environments. My current one is in the standard Backstage repo because it makes debugging easier. Therefore, `yarn backstage-cli info` doesn't yield much results.

```
OS:   Linux 6.6.8-200.fc39.x86_64 - linux/x64
node: v20.10.0
yarn: 3.2.3
cli:  0.25.1-next.1 (local)
backstage:  N/A
```

## Are you willing to submit a PR?
I am already working on fixing the issue. I just wanted to open this bug first to make sure I'm not missing anything.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by squid-ney** [comment]
Hi there, thanks for looking into contributing a fix! The solution you pitched makes sense to me. I'm curious, how large is your repository that is timing out when building the docs?
