### ISSUE TITLE
Issue deploying Backstage in AKS

### ISSUE THREAD

**Issue by Pravina1** [backstage/backstage#22090]
### 📜 Description

0

We have deployed backstage application on AKS cluster and we used nginx ingress controller for our application , but application is not stable , it works for 2 mins and goes down for long time (working intermittently ) we are not able to find rootcuase , even we can not see any error in pod logs , same application working in another env without any issue

we see 502 error intermittently

we tried to redeployed nginx as well as backstage application ,but it did not help

### 👍 Expected behavior

it should work without issue

### 👎 Actual Behavior with Screenshots

NA

### 👟 Reproduction steps

NA

### 🖥️ Your Environment

dev

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Please provide more context for the issue, such as any logs or errors you are seeing, which versions you are using and method of deployment.

**Comment by Pravina1** [comment]
Hi @Rugvip 
we dont see any error in pod logs , we just see application gets up for 2 mins and goes down for 5 mins 
its happening intermittently

**Comment by jamieklassen** [comment]
I'm not volunteering to help with the problem, but I'd like to offer some feedback about the bug report that will hopefully be useful: you'll be much more likely to get useful help if you provide _much_ more detail. This is a nonexhaustive list of ideas for things to include:
* "deployed on AKS" may not be as clear a description as you think. If I were you, I'd provide complete k8s manifests/helm charts/whatever used to deploy, including full reproducible steps for "us(ing) nginx ingress controller" (what commands/files were used to install this controller? What are the ingress resources related to Backstage?)
* What are all the specs (CPU/memory/storage/base image/config flags for control plane + any node pools) of the AKS cluster; what were the exact steps followed to provision it? Maybe there's other relevant Azure config, like a VPC or special AKS options?
* The complete Backstage app config, the output from `yarn backstage-cli info` for a breakdown of all the versions of all the Backstage packages, maybe the Dockerfile used to build the app image.
* Exact and complete descriptions of all the troubleshooting steps that have already taken place, e.g. what precisely does "application up" and "goes down" mean? Are you using a dashboard or CLI commands or something to check these things? You say you don't see any error in the logs but you could actually attach the complete sanitized logs in case somebody notices something you didn't. You could even share screenshots of the browser showing a 502 including anything in the network tab or javascript console.

You mention that some part of the behaviour is intermittent, so if somebody chooses to help they might not ever even be able to reproduce. This means it's a good idea to give as much context as humanly possible, way more than a description of the symptoms; every possible piece of code, script or config file that might be even vaguely related to the problem.

**Comment by camilaibs** [comment]
Hi @Pravina1, are you using Node 20? Could you try passing the `--no-node-snapshot` flag to Node and tell us if it works?
Here is an example:
https://backstage.io/docs/getting-started/configuration/#create-a-new-component-using-a-software-template
