### ISSUE TITLE
🚀 Feature: Restructure backstage.io FAQ

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#22106]
### 🔖 Feature description

Our [FAQ](https://backstage.io/docs/FAQ/) isn't particularly easy to browse and has a fair number of outdated questions. There's an opportunity to clean up the questions a bit, but in particular I think the FAQ could benefit from being split into a couple of different sections, maybe even with entries for some of the core features? For example:

```
| FAQ
|- Product
|- Adoption
|- Framework
|- Deployment
|- Core Features
```

### 🎤 Context

Discussed in the [Jan 4, 2024 Adoption SIG meeting](https://docs.google.com/document/d/1zeYSzXYgh897bxPQmwy2btOwCFlEjlUDLf00riySLRc/edit#heading=h.9ilpeigexlh2)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by sennyeya** [comment]
@Rugvip Can we close this with the work from #22165?
