### ISSUE TITLE
🐛 `backstage-cli package build` fails due to `rollup-plugin-dts` errors

### ISSUE THREAD

**Issue by chriskilding** [backstage/backstage#22100]
### 📜 Description

I'm in the process of writing a Backstage plugin in Typescript. It has a reasonably vanilla set of dependencies, and all the usual recommended Backstage plugin scripts. (The problematic item - `@backstage/cli ^0.25.0` - is in the `devDependencies`.)

The one slightly unusual feature with the setup is that because I have a front-end and a back-end plugin, I've put them in a multi-module project using Yarn workspaces.

When I run the `backstage-cli package build` command on the plugin, it fails to build, instead producing an error from `rollup-plugin-dts` which the Backstage CLI uses internally.

### 👍 Expected behavior

When I run the `backstage-cli package build` command on a (valid) plugin, with `typescript` in its devDependencies, then it should just work.

### 👎 Actual Behavior with Screenshots

When I run the `backstage-cli package build` command on the plugin, I get the following error:

> Process started
>
> Error: rollup-plugin-dts tried to access typescript (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unused.
> Required package: typescript
> ...

I then tried adding `typescript` to the `devDependencies`, ran `yarn install` and re-ran the build. I got the same error.

I then tried moving `typescript` to the `dependencies`, ran `yarn install` and re-ran the build, just in case `rollup-plugin-dts` is prevented from accessing `devDependencies` (unlikely but possible). Once again, I got the same error.

### 👟 Reproduction steps

Unfortunately the code is private, so I am unable to share it

### 🖥️ Your Environment

Due to the multi-module setup I had to run `yarn workspaces foreach --all run backstage-cli info`:

```
Process started
OS: Darwin 22.6.0 - darwin/arm64
node: v18.19.0
yarn: 4.0.2
cli: 0.25.0 (installed)
backstage: N/A

Dependencies:

Error: ENOENT: no such file or directory, open '/Users/me/.../my-plugin/frontend/yarn.lock
```

```
Process started
OS: Darwin 22.6.0 - darwin/arm64
node: v18.19.0
yarn: 4.0.2
cli: 0.25.0 (installed)
backstage: N/A

Dependencies:

Error: ENOENT: no such file or directory, open '/Users/me/.../my-plugin/backend/yarn.lock
```

If I had to guess, the Backstage CLI is maybe making some assumptions about the location of `yarn.lock`, that are incorrect in multi-module projects.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hi @chriskilding, thank you for reaching out to us 🙌🏻 .
Could you try updating the rollup dependency to the latest version and tell us if that solves the issue?

**Comment by chriskilding** [comment]
Hi, I tried adding `rollup-plugin-dts` to my project's dependencies, but it seems that Backstage CLI doesn't use it, so I got the same error.

Perhaps Backstage CLI bundles its dependencies - I heard it may also be bundling its own copy of Yarn - in which case it would be unable to respond to this change by definition, and the only way to fix it would be to bump or otherwise fix the `rollup-plugin-dts` dependency in Backstage CLI itself.

**Comment by chriskilding** [comment]
Separately, I tried creating a new project by creating a minimal `package.json` in the project root like this:

```json
{
  "name": "@internal/root",
  # ...metadata
  "scripts": {
    "new": "backstage-cli new",
    "build": "backstage-cli repo build"
  },
  "devDependencies": {
    "@backstage/cli": "^0.25.0"
  },
  "workspaces": [
    "backstage-plugin-foo"
  ]
}
```

Side note: I had to pre-populate the `workspaces` with the plugin name that I was about to create, because if I did not, then the `yarn lint --fix` command would fail. This might be another bug.

I then did `yarn new` in the root, to create a new frontend plugin `foo` as a submodule.

When I then run `yarn build` in the project root, the build fails with the same error as before;

> rollup-plugin-dts tried to access typescript (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

I then removed the package.json from the root, jumped into the plugin subdirectory, and rebuilt it as if it were a regular non-workspace project in isolation. The build worked.

So **it looks like the plugin build system has a problem with running in a workspace / multi-module project**. If you don't use workspaces, it works.

This is, however, a big problem in the most common use case - when creating a plugin that has a frontend and backend component, where we would *really* like to use workspaces (and workspace dependencies) to keep Backstage dependency versions in sync.

**Comment by tudi2d** [comment]
Ok - interesting issue. Can you double check if you are having a `typescript` dependency in the root? In which way did you customise the workspace setup? On a first glance it looks similar to the way we setup workspaces inside of Backstage.
