### ISSUE TITLE
🚀 Feature: New configuration of Azure Mono Repositories for Azure Devops Plugin

### ISSUE THREAD

**Issue by juaparod** [backstage/backstage#22121]
### 🔖 Feature description

Currently, the Azure Devops plugin offers the functionality to reference Azure repositories using this structure:

`dev.azure.com/project-repo: <project-name>/<repo-name>`

An additional feature to repository referencing could be **monorepository referencing**, something like:

`dev.azure.com/project-repo: <project-name>/<repo-name>/<mono-repo-name>`

### 🎤 Context

Our organization has many products structured under Azure repositories, but these products are partitioned by bounded contexts; therefore, our 'kind: Component' in Backstage are all referencing the same repository.

### ✌️ Possible Implementation

Not counting with deep knowledge about the plugin, nor the stack needed, I would propose the posibility to reference monorepository with something along the lines:

`dev.azure.com/project-repo: <project-name>/<repo-name>/<mono-repo-name>`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @juaparod, could you provide more details as to what this would actually do? I could make some assumptions but it would be better to have you clarify this. Also, could you describe a bit more what individual items within the mono-repo look like, I'm curious do they each have their own builds?

**Comment by juaparod** [comment]
Hi @awanlin, thanks for response, I'm Sorry, my English is low. I try in the next image diagramming a little structure of one Azure Repository:

<img width="1332" alt="image" src="https://github.com/backstage/backstage/assets/109260129/a6fc6337-0e9c-4ec8-a9c1-e26ba37defcf">

When use Azure Devops Plugin for load specific information of my UserService or ProductService, my component view in Backstage load for example, the "Management" Readme for two specific services, but I Want to load UserService Readme... This happends to other artifact's, pipelines, etc...

**Comment by juaparod** [comment]
Of course, let's see some desired views versus current view of my **User_Service** component.

For _Pull Request,_ _Git Tags_ And _Pipelines/Build_ the same behavior is reproduced:

<img width="1195" alt="image" src="https://github.com/backstage/backstage/assets/109260129/8fe2047e-8f72-4d51-9e24-d0c0bbf8ecc4">

For **Readme** files, I have one per `User_Services` and one per `Product_Services`, but for both I get the **Readme** loaded from `Management_Services`:

<img width="1005" alt="image" src="https://github.com/backstage/backstage/assets/109260129/a37c80ea-73b3-44b4-9bec-8404a720356e">

**Comment by deepan10** [comment]
Hello @awanlin , @juaparod 
I did some checks on Azure DevOps API, only README.me & Builds we can fetch for the mono repo components.

1. REAME.md - Path Fetch is supported. I will submit the PR for this one.

https://github.com/backstage/backstage/blob/1f008c27a141d6912723bbacf0517ac863116055/plugins/azure-devops-backend/src/api/AzureDevOpsApi.ts#L532-L535

2. Build - We can set the build definition id it already on going issue #22082 

3. GitTag - Name Filter not supported. Alternate we can filter the items with the name before set date in to the `Table` or we can use the regular `Table Filter`

4. PullRequest - Path filter not supported

**Comment by awanlin** [comment]
Hi, just following up as I see work has already started:

1. `README` - I'm not against this but hesitant as there is an existing plugin that can support this request - https://github.com/AxisCommunications/backstage-plugins/blob/main/plugins/readme/README.md. 
2. There's a PR to address this indirectly - https://github.com/backstage/backstage/pull/22153 - being able to just provide a build definition name means you can use that as essentially a filter 
3. Git Tags - I need more information on how this would look, I still don't understand that part of it. Does each User_Service component get it's own tag? I think I'm having a hard time as tags are at a global level. Could you share a screen shot of your tags in Azure DevOps so I can get a better idea, please?
4. Pull Requests - This makes sense, just not sure what our options are for this. 

@deepan10, are these features that you would use at your Org?

**Comment by afscrome** [comment]
Only supporting mono repos in some of the azure devops cards but not all slightly concerns me - I think we need to put a bit more thought into how we'll handle these.  Having a world where some of the cards do get filtered down to just your microservice, whilst others show all microservices in the same repo seems like it'll cause a lot of confusion.  At the very minimum, we'll need to clearly document this.

My best thought right now is to add an `isAzureReposMonoRepo` condition, and use that in setup steps.  e.g. for pull requests:

```tsx
<EntityLayout.Route if={isAzureDevOpsAvailable && !isAzureReposMonoRepo} path="/pull-requests" title="Pull Requests">
```

**Comment by deepan10** [comment]
Yes, I agree with you. That is my intention too.  I totally forget that we have we have separate `README.md` plugin. 
Also its good if we use `dev.azure.com/build-definition` as a general Filter. I will close the PR #22190.

**Comment by awanlin** [comment]
Once we get things sorted out here it would be great if you submitted a PR @deepan10, if you have the time that is! 

I really appreciate the support from you and @afscrome. I can't do it all AND I'm getting further and further away from Azure DevOps itself - my previous employer stopped using it in favor of GitHub and now that I'm with Spotify my role really doesn't see me working in that space (also, they don't use Azure DevOps either). I'll continue supporting this for as long as I can but building up a community of people to support it makes the most sense. 🚀

**Comment by awanlin** [comment]
Back on topic, so regarding the `README` as you can see at the bottom of my comment here - https://github.com/backstage/backstage/issues/22121#issuecomment-1887666878 - I've had a change of heart. Mostly as you already have the Azure DevOps plugin installed and it would be pretty easy to add a way for the user to provide a URL that we use to pull the content. Gong this path we could even make the card support any Markdown file. 🤔

**Comment by deepan10** [comment]
@awanlin @afscrome 
Sorry I was away. 

Which means, will go with the annotation something like `dev.azure.com/markdown: '/monorepo/userservice/README.md'` to fetch any Markdown file and show it in `<EntityAzureReadmeCard>`  

Did I understood correctly?

**Comment by msweaver** [comment]
Hi friends! I am also interested in this implementation. Is there anything I can do to contribute?

**Comment by deepan10** [comment]
@awanlin @afscrome 
Continue with the last comment https://github.com/backstage/backstage/issues/22121#issuecomment-1889838751 

There is PR #22791 with yet another annotation `dev.azure.com/readme-path` but similar to what we are discussing here.

**Comment by awanlin** [comment]
Yes, saw that, will review on Friday when I have time allocated for it. My only real concern is if we should use a URL instead? My gut wants to say as soon as we merged in path support someone will want to use a URL that different then the components repo.

**Comment by awanlin** [comment]
Sorry for waffling, I think supporting path is fine, if people want to use an URL that's out of scope for this plugin.

It's too bad URLs are not currently supported by the README plugin here: https://github.com/AxisCommunications/backstage-plugins/blob/main/plugins/readme/README.md
