### ISSUE TITLE
New Adopters Issue

### ISSUE THREAD

**Issue by Beexoul** [backstage/backstage#22123]
### 📜 Description

# New Adopters Issue 

## Description
Hello, as a beginner programmer, I'm uncertain whether the issue lies in the UI/UX design or if it's related to my code. The labels for "First name" (with the ID "label-firstname-9a5aa2af-87f3-4a44-819f-88ee243bb61e") and "Last name" (with the ID "label-lastname-9a5aa2af-87f3-4a44-819f-88ee243bb61e") appear to be out of context or hidden when viewed at 100% or in a regular website view.

 

## Screen_Record

[Screencast from 2024-01-06 13-50-46.webm](https://github.com/backstage/backstage/assets/97790932/b04453f8-311d-44a0-ba64-9fb9760dcdbc)

## Expected Behavior
The expected behavior was that, upon zooming out the website to 80%, the layout or appearance would adjust accordingly.
![Screenshot from 2024-01-06 13-42-58](https://github.com/backstage/backstage/assets/97790932/3c4dfbaa-efbc-4890-94cf-d912fa13e890)

## 100% Zoom Behavior
The 100% behavior was that, after zooming the website form 80% to 100%, the layout or appearance did not adjust as expected.
![Screenshot from 2024-01-06 13-40-15](https://github.com/backstage/backstage/assets/97790932/80a96bea-9969-47fc-a461-2dda064624f6)

## What is the Issue ?
1-landed on website 
2- go to New Adopters
3-After clicking on "New Adopters," I observed the issue persisting even after refreshing the page.

![Screenshot from 2024-01-06 13-40-15](https://github.com/backstage/backstage/assets/97790932/80a96bea-9969-47fc-a461-2dda064624f6)

### 📃 Provide the context for the Bug.

The problem impacts the user experience by causing the omission of the "First Name" and "Last Name" sections, leaving only the email and some checkboxes visible. This situation can lead to confusion for the user.

### 🖥️ Your Environment

**OS :** Garud Linux ( Arch ) 
**Browser :** Google Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
This form is injected by a HubSpot script, perhaps we can try considering the app bar height in the form positioning to avoid the fields being hidden behind the bar and also try applying styling to make the internal form scrollable as well. Adding a help wanted label, contributions are welcome.
