### ISSUE TITLE
🐛 Bug Report: Validation of incomming EDIFACT messages

### ISSUE THREAD

**Issue by nicob61** [backstage/backstage#22138]
### 📜 Description

In Integration Accounts, when you configure an EDI Agreement you have the possibility to check an EDI Validation into the receive settings/validation. This is not working, if the check is empty and you look into the Json File you will see that the EDI Validation is active (probably per default) and that the ValidationOverrides Session is empty.

### 👍 Expected behavior

Validation should only be active if the check is set into the receive setting.

### 👎 Actual Behavior with Screenshots

![Receive Settings-Validation](https://github.com/backstage/backstage/assets/61002797/851540ad-4ce9-4ba9-a06e-f9bb5dcbb379)
![JSON-Validation Overrides](https://github.com/backstage/backstage/assets/61002797/0be28d68-c647-4acd-a604-b89093ef8882)

### 👟 Reproduction steps

Create a new EDI Agreement an test the EDI Validation part with an EDI message with and without errors. 

### 📃 Provide the context for the Bug.

I had to manualy adapt the JSON file to be able ta accept the EDI file from my supplier.
Interessting is also that the schema I used is a BizTalk "standard" schema and if I try to validate in VS the file is valid, it looks like the Azure validation is not doing the same as in VS.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by tudi2d** [comment]
Hey @nicob61 - what exactly does this relate to in Backstage? Please specify the issue.

**Comment by nicob61** [comment]
Hi Philipp

probably posted in the wrong place.
Where can I report a Logic Apps bug?

Regards Nicolas
________________________________
Von: Philipp Hugenroth ***@***.***>
Gesendet: Donnerstag, 11. Januar 2024 16:59
An: backstage/backstage ***@***.***>
Cc: nicob61 ***@***.***>; Mention ***@***.***>
Betreff: Re: [backstage/backstage] 🐛 Bug Report: Validation of incomming EDIFACT messages (Issue #22138)


Hey @nicob61<https://github.com/nicob61> - what exactly does this relate to in Backstage? Please specify the issue.
