### ISSUE TITLE
🐛 Bug Report: Request failed with 431 Error is displayed on the Ownership section of user entity

### ISSUE THREAD

**Issue by SrikanthAbbaraju** [backstage/backstage#22139]
### 📜 Description

We have a 431 error scenario on user entity when user is a member of over 150 groups and Ownership is set to Aggregated Relations. The default backend API call response is 431 Request Headers Fields Too Large. Sample API call /api/catalog/entities?filter=kind=Component,kind=API,kind=System,relations.ownedBy=group:ldap/group1,relations.ownedBy=group:ldap/group2,relations.ownedBy=group:ldap/group3..... In UI Error: Request failed with 431 Error is displayed on the Ownership section of user entity. Can Backstage fix this backend API call?

### 👍 Expected behavior

No error - show Ownership/ empty if nothing to show

### 👎 Actual Behavior with Screenshots

![IMG_2757](https://github.com/backstage/backstage/assets/155988874/15eba863-2d70-4ec2-a3f2-9bbb48fac803)

### 👟 Reproduction steps

Access a user entity with over 150 groups assigned to them, each group name has to be 50 characters or more. Above mentioned error will occur.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by viniciusclerod** [comment]
+1

**Comment by awanlin** [comment]
Do you only get this error with Aggregated Relations? Or does it also have an error on Direct Relations?

**Comment by dennysmvn** [comment]
We got same error, only with users that own a lot of entities and teams, as catalog frontend calls `/api/catalog/entities` passing all teams names into request header path, resulting in error HTTP 431.

I think this error may also happens to Direct Relations, if same approuch when constructing the api call was used.

**Comment by camilaibs** [comment]
Had a quick sync with @backstage/maintainers and a recommendation could be to reduce the number of ownership entity refs in the sign resolver, right @freben ?

**Comment by OSobky** [comment]
> Yes. Until the auth improvements work lands later this year, the best fix is probably to significantly reduce the ownership refs count to ensure that the token doesn't grow too large.

Hello @freben, I was wandering if the improvements has already landed for this since I am facing the same error right now.
