### ISSUE TITLE
🐛 Bug Report: Edit button of the About Card leads the user to a non-existing page if the entity is loaded from a tag

### ISSUE THREAD

**Issue by renatafaracobah** [backstage/backstage#22140]
### 📜 Description

Hello!
When the user has an entity loaded from a repository tag, the edit button in the About card leads the user to the page <repository-url>/edit/<tag>/catalog-info.yaml - which is an unexisting page for tags (this only works for branches).
![edit-button-about-card](https://github.com/backstage/backstage/assets/93277286/e8e012f7-4299-4a77-aa9d-12595c001011)

### 👍 Expected behavior

Since it's not possible to edit a tag, the button should be hidden. 

### 👎 Actual Behavior with Screenshots

The button leads the user to a not found page.
![gh-404-page](https://github.com/backstage/backstage/assets/93277286/654e5405-9d06-4c71-9ee9-d77b088763ff)

### 👟 Reproduction steps

1. Register an entity from a tagged yaml file. 
2. Go to the entity page in Backstage.
3. Select the edit button in the About Card.

### 📃 Provide the context for the Bug.

This issue is leading users to a broken page, and affects user usability.

### 🖥️ Your Environment

OS: Linux 6.4.16-linuxkit - linux/x64 
node: v18.18.0 
yarn: 3.6.0 cli: 0.22.13 (installed) 
backstage: v1.18.4
Dependencies: @backstage/app-defaults 1.4.3 @backstage/backend-app-api 0.5.5 @backstage/backend-common 0.19.7 @backstage/backend-dev-utils 0.1.1 @backstage/backend-openapi-utils 0.0.4 @backstage/backend-plugin-api 0.6.5 @backstage/backend-tasks 0.5.10 @backstage/catalog-client 1.4.4 @backstage/catalog-model 1.4.2 @backstage/cli-common 0.1.12 @backstage/cli-node 0.1.4 @backstage/cli 0.22.13 @backstage/config-loader 1.5.0 @backstage/config 1.1.0 @backstage/core-app-api 1.10.0 @backstage/core-components 0.13.5 @backstage/core-plugin-api 1.6.0 @backstage/dev-utils 1.0.21 @backstage/errors 1.2.2 @backstage/eslint-plugin 0.1.3 @backstage/integration-aws-node 0.1.6 @backstage/integration-react 1.1.19 @backstage/integration 1.7.0 @backstage/plugin-api-docs 0.9.11 @backstage/plugin-auth-backend-module-gcp-iap-provider 0.1.2 @backstage/plugin-auth-backend-module-github-provider 0.1.2 @backstage/plugin-auth-backend-module-gitlab-provider 0.1.2 @backstage/plugin-auth-backend-module-google-provider 0.1.2 @backstage/plugin-auth-backend-module-oauth2-provider 0.1.2 @backstage/plugin-auth-backend 0.19.2 @backstage/plugin-auth-node 0.2.19, 0.3.2 @backstage/plugin-catalog-backend-module-github 0.4.3 @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.2 @backstage/plugin-catalog-backend-module-unprocessed 0.3.2 @backstage/plugin-catalog-backend 1.13.3 @backstage/plugin-catalog-common 1.0.16 @backstage/plugin-catalog-graph 0.2.36 @backstage/plugin-catalog-import 0.10.0 @backstage/plugin-catalog-node 1.4.6 @backstage/plugin-catalog-react 1.8.4 @backstage/plugin-catalog-unprocessed-entities 0.1.3 @backstage/plugin-catalog 1.13.0 @backstage/plugin-circleci 0.3.24 @backstage/plugin-entity-feedback-backend 0.2.2 @backstage/plugin-entity-feedback-common 0.1.3 @backstage/plugin-entity-feedback 0.2.7 @backstage/plugin-events-backend-module-github 0.1.15 @backstage/plugin-events-backend-test-utils 0.1.15 @backstage/plugin-events-backend 0.2.14 @backstage/plugin-events-node 0.2.14 @backstage/plugin-github-actions 0.6.5 @backstage/plugin-home-react 0.1.3 @backstage/plugin-home 0.5.8 @backstage/plugin-org 0.6.14 @backstage/plugin-permission-backend 0.5.28 @backstage/plugin-permission-common 0.7.8 @backstage/plugin-permission-node 0.7.16 @backstage/plugin-permission-react 0.4.15 @backstage/plugin-proxy-backend 0.4.2 @backstage/plugin-scaffolder-backend-module-cookiecutter 0.2.29 @backstage/plugin-scaffolder-backend 1.17.3 @backstage/plugin-scaffolder-common 1.4.1 @backstage/plugin-scaffolder-node 0.2.5 @backstage/plugin-scaffolder-react 1.5.5 @backstage/plugin-scaffolder 1.15.0 @backstage/plugin-search-backend-module-catalog 0.1.9 @backstage/plugin-search-backend-module-techdocs 0.1.9 @backstage/plugin-search-backend-node 1.2.9 @backstage/plugin-search-backend 1.4.5 @backstage/plugin-search-common 1.2.6 @backstage/plugin-search-react 1.7.0 @backstage/plugin-search 1.4.0 @backstage/plugin-sonarqube-backend 0.2.7 @backstage/plugin-sonarqube-react 0.1.8 @backstage/plugin-sonarqube 0.7.5 @backstage/plugin-techdocs-backend 1.7.2 @backstage/plugin-techdocs-node 1.8.2 @backstage/plugin-techdocs-react 1.1.11 @backstage/plugin-techdocs 1.7.0 @backstage/plugin-user-settings 0.7.10 @backstage/release-manifests 0.0.10 @backstage/test-utils 1.4.3 @backstage/theme 0.4.2 @backstage/types 1.1.1 @backstage/version-bridge 1.0.5

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by tudi2d** [comment]
Thanks for reporting this issue, @renatafaracobah! Indeed - this should be fixed. To give a bit of context to the issue: What is happening is that the entity is coming from an integration & therefor runs throught the `AnnotateLocationEntityProcessor`. Here the edit url is resolved from using the ScmIntegration: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/modules/core/AnnotateLocationEntityProcessor.ts#L57-L61. The problem is that it is just assumed if the URL exists, that it can be edited. 

Would you be interested in giving it a go to fix it & raise a PR?

**Comment by npiyush97** [comment]
@tudi2d cant replicate this issue help ?

**Comment by vinzscam** [comment]
> @tudi2d cant replicate this issue help ?

@npiyush97 I think you should be able to reproduce it by finding one of the example entities in one of the PRs (for example [playback-lib-component.yaml](https://github.com/backstage/backstage/blob/f1ba2bc6097a757c2827ff97fa301cff626de137/packages/catalog-model/examples/components/playback-lib-component.yaml) ) and trying to register the entity in your `app-config.yaml`
