### ISSUE TITLE
🚀 Feature: Include Stack Trace in Error Page

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#22156]
### 🔖 Feature description

It would be helpful when debugging to include the Stack Trace in the Error Page. Optionally this could be setup to only show when working locally.

### 🎤 Context

When debugging only getting the error message is not always helpful and the stack trace can provide additional insight

### ✌️ Possible Implementation

The `DefaultBootErrorPage` currently gets an `Error` object as one of its props and the `ErrorPage` already has an `additionalInfo` prop, perhaps we could do this:

```tsx
<ErrorPage status="501" statusMessage={message} additionalInfo={error.stack ?? <></>} />
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jithenms** [comment]
I'm interested in working on this issue. Could it be assigned to me? Thanks!
