### ISSUE TITLE
🚀 Feature: Add latest_report_status to puppetdb backend provider

### ISSUE THREAD

**Issue by negast** [backstage/backstage#22167]
### 🔖 Feature description

Hello, It would be handy if I could quickly filter my resources by their last puppet run state. This way I can quickly read failed nodes etc.
I would like to add latest_report_status which is a parameter in the nodes endpoint as a tag. 

### 🎤 Context

as said I want to filter quickly on the status of my nodes

### ✌️ Possible Implementation

You would have to alter type.ts 
```
......
latest_report_status: string;
  /**
   *  The status of the latest report. Possible values come from Puppet's report status failed, changed, or unchanged.
   */
....
```
and transform.ts
```
.....
 const latest_report_status = node.latest_report_status;

  return {
    apiVersion: 'backstage.io/v1beta1',
    kind: 'Resource',
    metadata: {
      name: certName,
      annotations: {
        [ANNOTATION_PUPPET_CERTNAME]: certName,
      },
      namespace: DEFAULT_NAMESPACE,
      description: node.facts?.data
        ?.find(e => e.name === 'ipaddress')
        ?.value?.toString(),
      tags: kernel ? [kernel.toString().toLocaleLowerCase('en-US'), latest_report_status.toString().toLocaleLowerCase('en-US')] : [],
    },
    spec: {
      type: type,
      owner: DEFAULT_ENTITY_OWNER,
      dependsOn: [],
      dependencyOf: [],
    },
  };
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by negast** [comment]
I made a fork here with the changes https://github.com/negast/backstage

**Comment by tudi2d** [comment]
Awesome @negast! Please create a PR to the master branch & link it to the issue. Implementation details can than be discussed in the PR with the reviewers.
