### ISSUE TITLE
Repo Tooling: Switch to use Vale 3.0

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#22171]
### 🔖 Feature description

Vale 3.0 has just been [released](https://github.com/errata-ai/vale/releases/tag/v3.0.0). We should migrate this repo to use Value 3.0 instead, since we are currently using v2.

Appreciate any help with this effort! 🙏 

### 🎤 Context

#22172

### ✌️ Possible Implementation

The following needs to be considered in the migration:

- The configuration at `.vale.ini`
- The configuration in `.github/vale`
- The docs quality workflow at `.github/workflows/verify_docs-quality.yml`
- The script that generates arguments for the above at `scripts/check-docs-quality.js`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by professorabhay** [comment]
Hey, @Rugvip ! I would like to give it a try.

**Comment by Rugvip** [comment]
@professorabhay great, thank you! 👍 Let us know if you have any questions

**Comment by professorabhay** [comment]
Can you please provide some more details about that?
Does updating the version info in the file `.github/workflows/verify_docs-quality.yml` resolve this issue?
I also checked the Vale version release sheet but couldn't see any major upgrade because that term is new to me.

**Comment by freben** [comment]
That's one part of it. But we know for a fact that things started failing when v3 was pulled in, so you'll have to compensate for that

**Comment by freben** [comment]
Made #22171 since this started biting us in local dev as well
