### ISSUE TITLE
🐛 Bug Report: Link Resolution fails with split OpenApi Definitions with repos hosted Azure DevOps

### ISSUE THREAD

**Issue by theparthshukla** [backstage/backstage#22183]
### 📜 Description

Rcently, we started using the @backstage/plugin-catalog-backend-module-openapi plugin so we could resolve openapi specs that are divided using $refs. We can use the link and it works just fine for GitHub-based repos (which we used to test), but our repos are on Azure DevOps and the links aren't resolving correctly. The URL resolution seems to be broken for Azure

### 👍 Expected behavior

The nested link resolution should work and we should be able to see the divided openapi spec on Backstage.

### 👎 Actual Behavior with Screenshots

When we try to add the catalog-info file for an api that uses split definitions, we get an error that looks like this:
<img width="730" alt="error" src="https://github.com/backstage/backstage/assets/36262397/3dc2d992-8568-485b-9b2e-cabc982183e2">

`{"error":{"name":"InputError","message":"InputError: Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $openapi unable to bundle the file at ./apigeeAuth.yaml, ResolverError: Error reading file \"https://dev.azure.com/xyz-company/Project_name/openapi/specs/apigeeAuth/loadGroups/singleLoadGroup.yaml\"","stack":"InputError: InputError: Processor PlaceholderProcessor threw an error while preprocessing`

### 👟 Reproduction steps

1. Add the @backstage/plugin-catalog-backend-module-openapi plugin to your Backstage instance
2. Using the catalog-import, try to import the catalog-info file of a split open-api spec which is hosted on Azure Devops 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by tudi2d** [comment]
Thanks for opening the issue! Just to get the right eyes on it: @awanlin does the URL look alright to you & @pjungermann did you see a similar issue like this before? Thanks for your help!

**Comment by pjungermann** [comment]
@theparthshukla 
Does this URL `https://dev.azure.com/xyz-company/Project_name/openapi/specs/apigeeAuth/loadGroups/singleLoadGroup.yaml` point to a repository in AzureDev? (azure integration)

In case yes: Did you set up the integration for it so that the UrlReader / the AzureIntegration can resolve/access it?

In case no: other external URLs are blocked by default and you have to allow them.
```yaml
backend:
  reading:
    allow:
      - host: '....'
```

Just a few thoughts and ideas.

**Comment by afscrome** [comment]
What about if you try `https://dev.azure.com/xyz-company/Project_name/_git/openapi?path=/specs/apigeeAuth/loadGroups/singleLoadGroup.yaml` as your url?  (i.e the url that shows in your address bar when you view that file in the repo in your web browser)

**Comment by awanlin** [comment]
Related Discord thread: https://discord.com/channels/687207715902193673/1187435814838354021

**Comment by theparthshukla** [comment]
@afscrome @pjungermann those links do not work correctly. Sorry for the misleading wording of the link, the actual working link would look something like:

https://dev.azure.com/company-name/project-that-hosts-all-repos/_git/repo-name?path=/openapi/specs/apigeeAuth/loadGroups/singleLoadGroup.yaml
