### ISSUE TITLE
🚀 Feature: Kubernetes Api for Backend

### ISSUE THREAD

**Issue by jorgemoralespou** [backstage/backstage#22198]
### 🔖 Feature description

There might be some times where from the backend part of a plugin you need to query the kubernetes clusters like the frontend does. Currently, in the frontend you can use the `kubernetesApiRef` from `kubernetes-react` plugin, but this is not usable from the backend. We need a way to query the KubernetesFetcher and some other capabilities that the `KubernetesBuilder` provides.

### 🎤 Context

My plugin does provide new Kinds and while processing there's a need to query the Kubernetes clusters to discover some runtime information and annotate my entities, so that the frontend has all the relevant information and querying does not need to happen in every instance of the frontend.

### ✌️ Possible Implementation

I could create a new `KubernetesBuilder` in my `createPlugin` method so that I could provide the kubernetes fetcher to my backend plugin, but this would be cumbersome as I would be duplicating some runtime code.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jorgemoralespou** [comment]
Keep the issue

**Comment by jorgemoralespou** [comment]
Keep

**Comment by skfarhat** [comment]
Hey @jorgemoralespou, did you end up getting to the bottom of this? I have the same need

**Comment by jorgemoralespou** [comment]
No, just gave up on backstage

**Comment by skfarhat** [comment]
For anyone landing on this issue in the future, we ended up using `${backendUrl}/api/kubernetes/proxy/${path}` where `path` could be something like `/api/v1/namespaces`. 

The header `Backstage-Kubernetes-Cluster` needs to be provided as part of the request and should reference the name of a cluster as configured in `app-config*.yaml`
