### ISSUE TITLE
🚀 Feature: [Accessibility] Microsite - add lighthouse CI checks

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#22191]
### 🔖 Feature description

We currently run lighthouse checks in CI to prevent new accessibility issues being introduced. With recent improvements to the microsite as well (#21885, #21883, #21882) it would be nice if we can add a CI check to run against the microsite as well. 

### 🎤 Context

To prevent new accessibility issues to be introduced for microsite. We should at least cover all first level paths (e.g. `/docs`, `/plugins`, `/blog`, `/demos`, `community` but also `/docs/releases/`)

### ✌️ Possible Implementation

current [lighthouse config for plugins](https://github.com/backstage/backstage/blob/master/lighthouserc.js) and github workflows [verify_accessibility-noop.yml](https://github.com/backstage/backstage/blob/master/.github/workflows/verify_accessibility-noop.yml) and [verify_accessibility.yml](https://github.com/backstage/backstage/blob/master/.github/workflows/verify_accessibility.yml) that hopefully can be duplicated and tweaked to work for microsite instead. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jithenms** [comment]
@emmaindal I'd love to tackle this! Feel free to assign me. Thanks!

**Comment by emmaindal** [comment]
Awesome, thank you so much @jithenms, will do and let me know if you have any questions!
