### ISSUE TITLE
🐛 Bug Report: Backend services db queries not working when using SQLite instead of Postgres 

### ISSUE THREAD

**Issue by gabrielucido** [backstage/backstage#22207]
### 📜 Description

I just created a new backstage app from scratch and used Postgres for local development.
To do some tests where I needed to flush the db every time I wanted to disable it for a sec the Postgres connection and use the "in memory" SQLite database so I could facilitate the development workflow.

But when I disabled the Postgres in the app-config files and restarted my application all the endpoints stopped working and starting to respond with 500 (error bellow).
```json
{
	"error": {
		"name": "SqliteError",
		"message": "select * from `group` - no such table: group",
		"code": "SQLITE_ERROR",
		"stack": "SqliteError: select * from `group` - no such table: group\n    at Database.prepare (/Users/gabrielrodrigues/dev/backstage/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)\n    at Client_BetterSQLite3._query (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/dialects/better-sqlite3/index.js:35:34)\n    at executeQuery (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)\n    at Client_BetterSQLite3.query (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/client.js:154:12)\n    at Runner.query (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/execution/runner.js:141:36)\n    at ensureConnectionCallback (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)\n    at Runner.ensureConnection (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/execution/runner.js:318:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Runner.run (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/execution/runner.js:30:19)\n    at <anonymous> (/Users/gabrielrodrigues/dev/backstage/plugins/groups-backend/src/service/router.ts:31:20)"
	},
	"request": {
		"method": "GET",
		"url": "/"
	},
	"response": {
		"statusCode": 500
	}
}
```

### 👍 Expected behavior

The backend service, In this case, should work independently if I'm using SQLite or Postgres.

### 👎 Actual Behavior with Screenshots

The server crashes and returns a 500 status code response.

### 👟 Reproduction steps

1. Create a new backstage instance using the getting started cli
 
2. Create a backend service with a migration file that generates some tables for the backend.

My router.ts:
```ts
import {
  PluginDatabaseManager,
  errorHandler,
  resolvePackagePath,
} from '@backstage/backend-common';

import express from 'express';
import Router from 'express-promise-router';
import { Logger } from 'winston';

import { Config } from '@backstage/config';

const migrationsDir = resolvePackagePath(
  '@internal/plugin-core-backend',
  'migrations',
);

export interface RouterOptions {
  logger: Logger;
  database: PluginDatabaseManager;
  config: Config;
}

export async function createRouter(
  options: RouterOptions,
): Promise<express.Router> {
  const { database } = options;

  const db = await database.getClient();

  await db.migrate.latest({
    directory: migrationsDir,
  });

  const router = Router();
  router.use(express.json());

  router.get('/', async (_, response) => {
    const result = await db('group').select();
    response.json(result);
  });

  router.use(errorHandler());
  return router;
}
```

4. Try to query this database table in the backend service.

The error:
```JSON
{
	"error": {
		"name": "SqliteError",
		"message": "select * from `group` - no such table: group",
		"code": "SQLITE_ERROR",
		"stack": "SqliteError: select * from `group` - no such table: group\n    at Database.prepare (/Users/gabrielrodrigues/dev/backstage/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)\n    at Client_BetterSQLite3._query (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/dialects/better-sqlite3/index.js:35:34)\n    at executeQuery (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)\n    at Client_BetterSQLite3.query (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/client.js:154:12)\n    at Runner.query (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/execution/runner.js:141:36)\n    at ensureConnectionCallback (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)\n    at Runner.ensureConnection (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/execution/runner.js:318:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Runner.run (/Users/gabrielrodrigues/dev/backstage/node_modules/knex/lib/execution/runner.js:30:19)\n    at <anonymous> (/Users/gabrielrodrigues/dev/backstage/plugins/groups-backend/src/service/router.ts:31:20)"
	},
	"request": {
		"method": "GET",
		"url": "/"
	},
	"response": {
		"statusCode": 500
	}
}
```

My app-config in the backend section has no change at all, removed the comments in this description for shortness:

```yaml
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
```

### 📃 Provide the context for the Bug.

I'm using the new backend system.
I'm using Vite flag for APP.

### 🖥️ Your Environment

I'm using node v20.10.0 on a Mac m1, MacOs Sonoma Version 14.2.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sennyeya** [comment]
Hey 👋 , is this on a full restart of the app (SIGINT) or just a change of `app-config` and letting the hot reloading restart the app?

**Comment by gabrielucido** [comment]
Hi, it,s a full restart =\

For some reason hot reloading isn't working also. Just tried a full reboot on my machine and the problem still goes on...

**Comment by gabrielucido** [comment]
I mean, the backend does not have hot reload? Because the front-end hot reloads are normal

**Comment by sennyeya** [comment]
Alright, couple of different thoughts.

1. Can you share the migration file you're loading? 
2. Can you try this without the VITE flag?

**Comment by gabrielucido** [comment]
Yeah, for sure!

Tested without Vite and still had the same problem.

I'll make the repository public and share it here =)

[Backstage Repo](https://github.com/archangel-tech/backstage)

**Comment by gabrielucido** [comment]
I'm currently working on this project so I'll also make this **branch bug-report** (the only one other than main) so you can keep the state when Vite was disabled and in memory SQL database was the enabled.

![image](https://github.com/backstage/backstage/assets/36337762/3eb1b397-7ffb-45ac-b146-2442f596b504)

**Comment by sennyeya** [comment]
Hey, thanks for disabling Vite and sharing a copy of the repo. Just took a look and I think the code that's causing issues is this in each of the `roles`/`groups`/`permissions`/etc plugins you have,
```
const db = await DatabaseManager.fromConfig(config)
    .forPlugin('core')
    .getClient();
```
The base SQLite memory connection doesn't support multiple connections attaching to the same database, [this SO thread](https://stackoverflow.com/questions/15720700/can-two-processes-access-in-memory-memory-sqlite-database-concurrently) has a great explanation of why this happens in SQLite. Because we are creating a new `DatabaseManager`, we can't use the cached connection and so need to create a new one. To fix this you'll need to update your config to the below
```
- connection: ':memory:'
+ connection:
+       directory: db
```
This will cause SQLite to create files for the databases instead of holding them in memory (you'll also want to add this directory to .gitignore). Theoretically, you could also use `:memory:?cache=shared` but I don't think Backstage supports that. (@Rugvip 🤔 )

**Comment by sennyeya** [comment]
Also, given that all of your plugins interact with the same database and your schema is highly relational, I would recommend nesting your express routers instead of having separate plugins for each of the data types you have. That should save you headache here and in the future. Something like
```ts
const router = express();

router.use('/roles', roleRouter);
router.use('/groups', groupRouter);

return router;
```
that would then be called like `fetch('/api/core/roles')`.

You could also follow the set up that the unprocessed entities plugin uses, see [here](https://github.com/backstage/backstage/blob/ab070febb3a081dea43129fc994cff5286b17565/plugins/catalog-backend-module-unprocessed/src/module.ts#L28). That allows the main plugin to be a plugin and the others to be separate modules but still use the same database and router. This gets a bit more complex as you'd have to do something like,
```
// router.ts -> createRouter()

  return Router().use('/roles', router);

// plugin.ts
export const rolePlugin = createBackendModule({
  pluginId: 'core',
  moduleId: 'roles',
  register(env) {
    env.registerInit({
      deps: {
        logger: coreServices.logger,
        config: coreServices.rootConfig,
        database: coreServices.database,
        httpRouter: coreServices.httpRouter,
      },
      async init({ logger, database, httpRouter }) {
        const winstonLogger = loggerToWinstonLogger(logger);

        const router = await createRouter({
          logger: winstonLogger,
          database,
        });
        httpRouter.use(router);
      },
    });
  },
});
```

**Comment by gabrielucido** [comment]
Damn, you're a champ, I'll try to take this approach.

Any ideia on why the hot reloading isn't working for backend plugins?

**Comment by sennyeya** [comment]
Hmm, @ahhhndre probably has a better answer here, from what I can tell pressing "Enter" with `yarn start-backend` or using `LEGACY_BACKEND_PLUGIN=1 yarn start` gives me the behavior I was expecting (full restart of app). I'm not seeing the hot reload retrigger with the new backend start. Might be related to https://github.com/backstage/backstage/issues/21690?

**Comment by gabrielucido** [comment]
Good morning, I tested using LEGACY_BACKEND_PLUGIN=1  but it doesn't work, then looking into the issue mentioned above actually the env is LEGACY_BACKEND_**START**=1, and then it works =)

Let's close the issue for now. The reason why I opened this issue was the SQLite error and it has already been solved =)

Okey?

**Comment by gabrielucido** [comment]
Also, just wanted to thank you all for the support!
The backstage community has been so amazing to me!

❣️❣️❣️❣️
