### ISSUE TITLE
🐛 Bug Report: Catch error when delete location entity and then import the same location

### ISSUE THREAD

**Issue by mario-mui** [backstage/backstage#22209]
### 📜 Description

![image](https://github.com/backstage/backstage/assets/7720722/7cd6e0ad-1d59-46b3-960f-11e4c1522ede)

### 👍 Expected behavior

not have 404 error ? or location can only delete by using unregistry?

### 👎 Actual Behavior with Screenshots

no

### 👟 Reproduction steps

step 1，import a catalog from gitlab
![image](https://github.com/backstage/backstage/assets/7720722/479eea51-ca61-4054-9553-9fa277e074e4)

step2 only delete the location entity
![image](https://github.com/backstage/backstage/assets/7720722/0f56d984-7431-4be8-8e44-31f7db133317)

step3 use the same gitlab url to import catalog
![image](https://github.com/backstage/backstage/assets/7720722/0f9ca59f-e29b-4b21-8808-a4c14cbd3c03)

step 4 : click refresh button, I got 404 error
![image](https://github.com/backstage/backstage/assets/7720722/7cd6e0ad-1d59-46b3-960f-11e4c1522ede)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
```[tasklist]
### Tasks
```

**Comment by mario-mui** [comment]
The refresh action inside do two things
1. check if has entity_ref, look up to `refresh_state_reference` table
2. update `refresh_state` database table

and column `target_entity_ref` and `source_entity_ref` in `refresh_state_reference` table  are refer to  column `entity_ref` in `refresh_state` database table

**Comment by mario-mui** [comment]
delete entity do there things
1. update `refresh_state` 
<img width="578" alt="image" src="https://github.com/backstage/backstage/assets/7720722/09299bdb-84c7-4eb9-be1c-a0636920836d">
2. update `relations`
<img width="647" alt="image" src="https://github.com/backstage/backstage/assets/7720722/eb3813f0-151e-4122-83e8-c79a4b10a1a2">
3. delete `refresh_state` 
<img width="530" alt="image" src="https://github.com/backstage/backstage/assets/7720722/d11fdc0e-edcc-4ad6-a516-5d82d1e7cc8a">

when delete `refresh_state`  will trigger deleting `final_entity`.

When delete component type entity, first `refresh_state` and `final_entity` will be deleted, then they will be add again(I don't know how they be added). But location entity will not do the same follow

**Comment by alde** [comment]
This is expected behaviour as the "delete entity" is meant to be sort of an escape hatch that forces a re-ingesting of the location. To fully remove an entity you should unregister the location, and then the entity will eventually be cleaned up. The message above the "Delete Entity" button could maybe be improved some to be clearer around this.

**Comment by mario-mui** [comment]
> This is expected behaviour as the "delete entity" is meant to be sort of an escape hatch that forces a re-ingesting of the location. To fully remove an entity you should unregister the location, and then the entity will eventually be cleaned up. The message above the "Delete Entity" button could maybe be improved some to be clearer around this.

But delete location catalog and delete component catalog, I got different behavior.

**Comment by padupe** [comment]
We are experiencing similar behavior... we have had projects where the integration file has been removed. We have already deleted the `locations` and even so, the integration with GitHub brings the `locations` "back".

PSC @claudinei-ferreira

**Comment by alde** [comment]
When you say that the integration file was removed, do you mean that you removed the catalog-info.yaml from the repository? If so the GitHub ingester shouldn't be able to find the necessary information to re-add the location to the database.
If you unregistered the location but the file still exists in the repo, then the ingester will find the file and re-create the location, leading to a new entity to be created again.

**Comment by petercraft** [comment]
It appears that the issue surfaced after updating to Node 20, temporarily reverting to Node 18 resolved the problem. Additionally, I could only replicate it when utilizing a PostgreSQL connection, not in an in-memory db.
