### ISSUE TITLE
Issue with downloading backstage on Azure Devops agent

### ISSUE THREAD

**Issue by komorebivv** [backstage/backstage#22219]
### 📜 Description

I'm trying to set up a pipeline for building and deploying backstage. I tested backstage locally and everything worked. 
I'm using Azure DevOps pipeline and Microsoft-hosted agent.

I added a task like below:

- script: |
      npx @backstage/create-app@latest
  displayName: "Build application"

But when pipeline is running, the following warning occured:
npm WARN exec The following package was not found and will be installed: @backstage/create-app@0.5.8

Pipeline is cancelled after 1 hour and nothing was executing. The only output is like above.  I also added below task for validation.

- script: |
    #check availability registry
    npm config get registry
    #check  package availability
    npm show @backstage/create-app@0.5.8
  displayName: "check registry and package availability"

And everything looks fine in output, the package is available.

### 👍 Expected behavior

downloading backstage on agent

### 👎 Actual Behavior with Screenshots

backstage is not downloading

### 👟 Reproduction steps

I added validation task

### 🖥️ Your Environment

microsoft-hosted agent, azure devops pipeline

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by deepan10** [comment]
Hello @komorebivv ,

The problem is:

1. It will try to download the package `@backstage/create-app@latest` and run the CLI.  To download npx prompt you to say `yes`.
2. The CLI prompt another one to enter the `app name`

To solve these two:

1. Set an environmental variable `BACKSTAGE_APP_NAME` first
2. Then use this command line in script `npx --yes @backstage/create-app@latest` 

With this approach you can create a `Backstage App` via a Pipeline.

**Comment by komorebivv** [comment]
Hi @deepan10, it's working. Thank you for fast response!

**Comment by awanlin** [comment]
Hi @komorebivv, I'm very curious about this and also worried. Why are you running `npx @backstage/create-app@latest` in a build like this?

You should only be running this command once and then all future changes would be done to the git repo created by `@backstage/create-app`. In the normal journey of a Backstage Adopter you would run this once and then never again outside of perhaps some local debugging. Your pipeline should just be checking out the repo itself which is a very common pattern.
