### ISSUE TITLE
🚀 Feature: Early warning about protecting Backstage deployment

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#22216]
### 🔖 Feature description

We could add a step to the adoption flow where the integrator is warned when they configure a non-proxy auth provider for sign-in. The warning would should highlight the note at the top of https://backstage.io/docs/auth/ 

### 🎤 Context

@mtlewis 😁 

### ✌️ Possible Implementation

We'll want to make sure this is a warning that is possible to remove. It might make sense to add as a config flag that is disabled by default but set to true in our `create-app` template? For example:

```yaml
auth:
  showBackendProtectionWarning: true
```

And then we have the warning instruct users to remove that piece of config to get rid of the warning, but hopefully someone has read it at least once at that point 😁 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by professorabhay** [comment]
Hey, @Rugvip! As far as I understand, we have to show a warning when a user sets up a non proxy auth provider. It can be implemented by setting a flag to `true` by default and that will show an alert box and when the user clicks `ok` then it turns `false` for that user. Is it?

If, then please provide me some more details about the files that are responsible or anything that can help me to understand more as a beginner. 

Thanks!

**Comment by Rugvip** [comment]
Closing as not needed anymore due to the work in #22605
