### ISSUE TITLE
🐛 Bug Report: <User email address is not being fetched from identityApi>

### ISSUE THREAD

**Issue by ankitapandey1106** [backstage/backstage#22256]
### 📜 Description

Hi Team,
We are in the process of upgrading our custom backstage to 1.20 and facing some issue after the changes done for oauth2 authentication. The sign in works properly using the user email and token but the user email is somehow not being set in the identityApi as when we try to get the data from it calling identityApi.getProfileInfo(), it doesn't have any of the fields. I have checked the profile data while creating the signInResolver and that does have email.
Can someone please help, what we are missing here? We are facing this issue only after we changed the code of auth-backend plugin's oauth2 provider, to use adaptLegacyOAuthHandler and adaptLegacyOAuthSignInResolver instead of the old mechanism.

P.s: When we login using the guest user, it does have an email on the UI, but when we use sso, the email id is not present anywhere on the UI.

### 👍 Expected behavior

Email id should be available in the front end 

### 👎 Actual Behavior with Screenshots

logged in user's email Id is not available in the front end
Pasting below one of the screens where user email id is expected but not available

![image](https://github.com/backstage/backstage/assets/32476575/51c9dab9-a7b6-48aa-89ec-e5a6b8a8b161)

### 👟 Reproduction steps

After the user is logged in using sso, navigate to settings page, user email id is not available

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Hi, sorry for the delay.

`adaptLegacyOAuthHandler` is an internal function that we actually don't export, isn't it? 🤔 

Either way, it's just passing the entire passport profile straight through to your handler callback: https://github.com/backstage/backstage/blob/16d0520055524e751978a62327a07c26cd1a3c10/plugins/auth-backend/src/lib/legacy/adaptLegacyOAuthHandler.ts#L34

And the output is the full profile object including the email, but wrapped in a `{ profile: }` object: https://github.com/backstage/backstage/blob/16d0520055524e751978a62327a07c26cd1a3c10/plugins/auth-node/src/types.ts#L332

What does your code look like around where it gets added to your auth backend?

**Comment by ankitapandey1106** [comment]
Hi @freben, Thank you for your response, I missed it somehow though and we are working with a workaround but still looking to solve this issue.
To your point, yes adaptLegacyOAuthHandler is an internal function but it is exported.

And yes we can see the email as part of this code in adaptLegacyOAuthHandler 
fullProfile: result.fullProfile,
          accessToken: result.session.accessToken,
          email: decodingJWT(result.session.accessToken).email,
          
but this email is not available in the front end, on th UI, as per the images I have pasted in the original question.
We are trying to get the same from authHandler using in packages/backend/srs/plugins/auth.ts using this doc - https://backstage.io/docs/auth/identity-resolver

 providerFactories: {
      oauth2: providers.oauth2.create({
        authHandler: async ({
          fullProfile  // Type: passport.Profile,
          idToken      // Type: (Optional) string,
        }) => {
          //if I am trying to get the profile info, email display name etc here and return the same, it is all null b
          return {
            profile: {
              email,
              picture,
              displayName,
            }
          };
        }
      })
 
/if I am trying to get the profile info, email display name etc here and return the same, it is all null but if I hard code these values then I see them properly populated on the UI in the above image.
Appreciate your response

**Comment by Rugvip** [comment]
@ankitapandey1106 if your examples there are accurate then it seems as though your provider passes the email in an access token rather, while the default profile transforms looks for it in the ID token. You'll want to update your auth handler to grab the email from the access token rather than the ID token in that case.

**Comment by ankitapandey1106** [comment]
Hi @Rugvip, thank you for your response. I tried to fetch the email from accesstoken and it works fine, but I am trying to understand here, why wouldn't we get any data when I try to fetch fullProfile in my authHandler in auth.ts. 
authHandler: async ({
fullProfile // Type: passport.Profile,
}) => {
//fullProfile  is null here, I can't get any info from it
return {
profile: {
email,
picture,
displayName,
}
And I can see it is being set in the adaptLegacyOAuthHandler.ts- 
 authHandler(
        {
          fullProfile: result.fullProfile,
          accessToken: result.session.accessToken,
          email: decodingJWT(result.session.accessToken).email,
          params: {
            scope: result.session.scope,
            id_token: result.session.idToken,
            token_type: result.session.tokenType,
            expires_in: result.session.expiresInSeconds!,
          },
        },
        ctx,
      ))
