### ISSUE TITLE
🚀 Feature: Better Deployment model

### ISSUE THREAD

**Issue by GregJohnStewart** [backstage/backstage#22290]
### 🔖 Feature description

There should be a better deployment model than running an npm commamd. This model isn't particularly user friendly, less so when the user isn't familiar with npm.

Alternatively, should be made available as a container if possible.

### 🎤 Context

From the standpoint of a sysadmin, this deployment model feels sketchy and reliant on dev tooling (`yarn dev`). If this could be packaged and instalable from a `.deb` or `.rpm` package, it would greatly streamline the process of getting started.

### ✌️ Possible Implementation

Packages aren't hard to make, and by the looks of things, this could be a rather simple installer. There would also need to be a systemd service to handle the running of the app as well, probably under a system user created for running the app.

Alternatively, if this system is available as a container then that would also simplify things greatly. If it's already containerized, it needs added to the getting started docs.

I have some experience with orchestrating similar architected apps, so I am willing to share my experiences.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else. Or maybe so, with assistance.

**Comment by Rugvip** [comment]
The primary way of deploying your own Backstage project is through a Docker image that you [build yourself](https://backstage.io/docs/deployment/docker). Although if you don't deploy with Docker you can also use the lower level artifacts provided by the [frontend](https://backstage.io/docs/local-dev/cli-build-system#frontend-production) and [backend](https://backstage.io/docs/local-dev/cli-build-system#backend-production) bundle commands.

**Comment by GregJohnStewart** [comment]
So is there an official docker image then? It looks like there is in the kube instructions, but why advertise to build yourself? I'm okay with development steps, but just using the software should be a little more packaged.

**Comment by Rugvip** [comment]
@GregJohnStewart Backstage is a framework for building developer portals, not an application that you can run directly. I'll note that there are some ongoing initiatives to change that, but that's the current state.

**Comment by freben** [comment]
Open-source Backstage is a _framework_, not a pre-packaged one-size-fits-all product. What you get is a monorepo whose code you iterate on, and a lot of nice APIs and abstractions and plugins are available to you.

There may a bit of a misapprehension of what type of solution this is. You don't have a one-size-fits-all product image of WordPress either, if I may make a bit of a clumsy parallel.

**Comment by Rugvip** [comment]
@freben something like [Docusaurus](https://v1.docusaurus.io/docs/en/publishing) might be a better example, it doesn't have an [official docker image](https://hub.docker.com/_/wordpress) :p

**Comment by GregJohnStewart** [comment]
Interesting, I had assumed a more Jenkins-style thing where you can heavily configure a core deployable product. I'll just have to keep working on it then, thanks for the info!
