### ISSUE TITLE
🐛 Bug Report: Scaffolder Action publish:github:pull-request received an error response from GitHub

### ISSUE THREAD

**Issue by darrenyung** [backstage/backstage#22303]
### 📜 Description

Was testing out the fix for the [issue](https://github.com/backstage/backstage/issues/21786#event-11329386863) I've raised previously but now I'm encountering a new error after upgrading to 1.22.0. During execution, I encountered an error response from GitHub API 

### 👍 Expected behavior

Pull request is raised in GitHub as designed.

### 👎 Actual Behavior with Screenshots

Error log produced `GithubResponseError: Pull request creation failed; caused by Error: fetch is not set`

### 👟 Reproduction steps

1. Designed a scaffolder template with `publish:github:pull-request` action.
2. Process the template from Software Templating page
3. Observe error in the logs.

### 📃 Provide the context for the Bug.

```
92024-01-18T04:42:40.000Z GithubResponseError: Pull request creation failed; caused by Error: fetch is not set. Please pass a fetch implementation as new Octokit({ request: { fetch }}). Learn more at https://github.com/octokit/octokit.js/#fetch-missing10    at Object.handler (/Users/yungc/Documents/Projects/backstage/node_modules/@backstage/plugin-scaffolder-backend-module-github/src/actions/githubPullRequest.ts:357:15)11    at NunjucksWorkflowRunner.executeStep (/Users/yungc/Documents/Projects/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:343:9)12    at NunjucksWorkflowRunner.execute (/Users/yungc/Documents/Projects/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:431:9)13    at TaskWorker.runOneTask (/Users/yungc/Documents/Projects/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:145:26)14    at async run (/Users/yungc/Documents/Projects/backstage/node_modules/p-queue/dist/index.js:163:29)
```

### 🖥️ Your Environment

OS:   Darwin 23.2.0 - darwin/x64
node: v18.17.1
yarn: 1.22.19
cli:  0.25.1 (installed)
backstage:  1.22.0

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.5.10
  @backstage/backend-common                                        0.19.9, 0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.6.9
  @backstage/backend-tasks                                         0.5.14
  @backstage/backend-test-utils                                    0.2.10
  @backstage/catalog-client                                        1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.11.2, 0.13.10
  @backstage/core-plugin-api                                       1.8.2
  @backstage/dev-utils                                             1.0.26
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.3
  @backstage/plugin-badges-backend                                 0.3.6
  @backstage/plugin-badges                                         0.2.53
  @backstage/plugin-bazaar-backend                                 0.3.7
  @backstage/plugin-bazaar                                         0.2.21
  @backstage/plugin-catalog-backend-module-github                  0.4.7
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.6
  @backstage/plugin-catalog-backend                                1.16.1
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog-unprocessed-entities                   0.1.7
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-devtools-backend                               0.2.6
  @backstage/plugin-devtools-common                                0.1.8
  @backstage/plugin-devtools                                       0.1.8
  @backstage/plugin-entity-validation                              0.1.14
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.35
  @backstage/plugin-explore                                        0.4.15
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-github-issues                                  0.2.18
  @backstage/plugin-github-pull-requests-board                     0.1.23
  @backstage/plugin-home-react                                     0.1.7
  @backstage/plugin-home                                           0.6.1
  @backstage/plugin-kubernetes-backend                             0.14.1
  @backstage/plugin-kubernetes-common                              0.7.3
  @backstage/plugin-kubernetes-node                                0.1.3
  @backstage/plugin-kubernetes-react                               0.2.1
  @backstage/plugin-kubernetes                                     0.11.4
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-backend                             0.5.32
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.19
  @backstage/plugin-playlist-backend                               0.3.13
  @backstage/plugin-playlist-common                                0.1.14
  @backstage/plugin-playlist                                       0.2.3
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-elasticsearch            1.3.12
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-shortcuts                                      0.3.18
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.41
  @backstage/plugin-tech-insights-backend                          0.5.23
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.4.15
  @backstage/plugin-tech-insights                                  0.3.21
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-addons-test-utils                     1.0.26
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.4
  @backstage/plugin-techdocs-node                                  1.11.1
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-todo-backend                                   0.3.7
  @backstage/plugin-todo                                           0.2.33
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 4.55s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
That's odd. That version and newer of node should indeed have native fetch present; the way I interpret the error is that the client can't find the fallback global one to use. Can you double check that the right version of node is present, including inside the runtime environment (container or whatnot)?

**Comment by darrenyung** [comment]
> That's odd. That version and newer of node should indeed have native fetch present; the way I interpret the error is that the client can't find the fallback global one to use. Can you double check that the right version of node is present, including inside the runtime environment (container or whatnot)?

Interesting, I did turn off the native Fetch for Node18 because of this [issue](https://github.com/backstage/backstage/issues/15940). I might move to Node20 and try again as I noticed it has reached LTS.

**Comment by benjdlambert** [comment]
With Octokit 3, it requires 18+ of Node because it uses the global `fetch` rather than using a polyfill. By disabling `fetch` by using the `NODE_OPTIONS` you effectively break this package.

I think that the right solution for the other issue is more along the lines of https://github.com/backstage/backstage/issues/15940#issuecomment-1819182913

I wonder if global-agent has been updated to work with the built in `fetch` yet as that would fix both issues.

**Comment by darrenyung** [comment]
Thanks @benjdlambert , I'll need to dig further into this and test it out. I noticed that Node20 has reached LTS and will be looking at upgrading to that too while undoing the ENV. Hopefully the underlying issues with the proxy will not creep up again.

**Comment by darrenyung** [comment]
Thanks @benjdlambert . After updating to 1.22.2, Node to v20 and reverting the env changes I made [here](https://github.com/backstage/backstage/issues/15940#issuecomment-1717076003) and followed [this](https://github.com/backstage/backstage/issues/15940#issuecomment-1819182913). The scaffolder feature is working amongst the others again.
