### ISSUE TITLE
🐛 Bug Report: GithubOrgEntityProvider may fail to read Users and Groups depending on the size of the organization

### ISSUE THREAD

**Issue by sonikro** [backstage/backstage#22318]
### 📜 Description

When running the **GithubOrgEntityProvider** to populate **Users** and **Groups** based on Teams from a specific **GitHub** Organization, I'm getting intermittent timeout errors from Github. (github.com). The problem happens on this query:

https://github.com/backstage/backstage/blob/def682a59d66291a7c56de2f46f730ffd25bb037/plugins/catalog-backend-module-github/src/lib/github.ts#L186-L220

And it's happening because the organization I'm using has a huge number of Teams and Members inside of those teams, which causes **100** Teams to fetch too much data at once. It takes more than 10s for github.com to respond, and several times, Github will throw a 5xx error saying it couldn't respond in time.

This is an intermittent error, it comes and goes, since it depends on github.com response time. However, lowering the number of teams down to 50 allowed me to get a consistent response back.

### 👍 Expected behavior

Users and Groups should've been populated based on GitHub Teams

### 👎 Actual Behavior with Screenshots

> GithubOrgEntityProvider:github refresh failed, HttpError: Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include <REMOVED>` when reporting this issue."}]} Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `<REMOVED>` when reporting this issue."}]}

Request Body:

```graphql
{"query":"
    query teams($org: String!, $cursor: String) {
      organization(login: $org) {
        teams(first: 100, after: $cursor) {
          pageInfo { hasNextPage, endCursor }
          nodes {
            slug
            combinedSlug
            name
            description
            avatarUrl
            editTeamUrl
            parentTeam { slug }
            members(first: 100, membership: IMMEDIATE) {
              pageInfo { hasNextPage }
              nodes {
                avatarUrl,
                bio,
                email,
                login,
                name,
                organizationVerifiedDomainEmails(login: $org)
               }
            }
          }
        }
      }
    }","variables":{"org":"<REMOVED>"}}
```

### 👟 Reproduction steps

1. Setup GithubOrgEntityProvider to a org with hundreds of teams and each team might have thousands of users
2. Run the scheduled job to fetch Users and Groups
3. Wait for exception to happen

### 📃 Provide the context for the Bug.

My proposed solution would be to allow the size of the batch to be a parameter that defaults to 100, so if users need to tweak it in order to work for their massive orgs, they can.

### 🖥️ Your Environment

> OS:   Linux 5.15.133.1-microsoft-standard-WSL2 - linux/x64
node: v18.17.0
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.20.3

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.10, 0.5.8, 0.5.9
  @backstage/backend-common                                        0.19.9, 0.20.0, 0.20.1
  @backstage/backend-dev-utils                                     0.1.2, 0.1.3
  @backstage/backend-openapi-utils                                 0.1.0, 0.1.2
  @backstage/backend-plugin-api                                    0.6.9
  @backstage/backend-tasks                                         0.5.12, 0.5.13, 0.5.14
  @backstage/backend-test-utils                                    0.2.10
  @backstage/catalog-client                                        1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5, 0.2.0, 0.2.1, 0.2.2
  @backstage/cli                                                   0.22.13, 0.24.0
  @backstage/config-loader                                         1.5.3, 1.6.0, 1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1, 1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.13.10
  @backstage/core-plugin-api                                       1.8.2
  @backstage/dev-utils                                             1.0.24
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0, 0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.7.2, 1.8.0
  @backstage/plugin-api-docs                                       0.10.1
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.4.3
  @backstage/plugin-catalog-backend-module-github                  0.4.7
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend                                1.15.0, 1.16.1
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.5.0, 1.6.0, 1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog                                        1.15.1
  @backstage/plugin-events-backend-module-github                   0.1.19
  @backstage/plugin-events-backend                                 0.2.18
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-github-issues                                  0.2.18
  @backstage/plugin-github-pull-requests-board                     0.1.23
  @backstage/plugin-home-react                                     0.1.5
  @backstage/plugin-home                                           0.5.11
  @backstage/plugin-kubernetes-backend                             0.13.1
  @backstage/plugin-kubernetes-common                              0.7.1, 0.7.3
  @backstage/plugin-kubernetes-node                                0.1.1
  @backstage/plugin-kubernetes-react                               0.2.1
  @backstage/plugin-kubernetes                                     0.11.4
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-backend                             0.5.32
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.19
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.0
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.0
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.0
  @backstage/plugin-scaffolder-backend-module-github               0.1.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.11
  @backstage/plugin-scaffolder-backend                             1.19.2
  @backstage/plugin-scaffolder-common                              1.4.3, 1.4.4, 1.4.5
  @backstage/plugin-scaffolder-node                                0.2.9
  @backstage/plugin-scaffolder-react                               1.6.1
  @backstage/plugin-scaffolder                                     1.16.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-elasticsearch            1.3.12
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10, 1.2.8
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.41
  @backstage/plugin-tech-insights-backend                          0.5.23
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.4.15
  @backstage/plugin-tech-insights                                  0.3.21
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.4
  @backstage/plugin-techdocs-node                                  1.11.1, 1.10.0
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-user-settings                                  0.7.13
  @backstage/release-manifests                                     0.0.10, 0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.4.4, 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
As for me, if 50 works for you, I wouldn't mind if you made a contribution to reduce that default page size. It's big enough anyway that I think it should probably not significantly hurt other adopters with smaller member counts.

Ultimately of course, making it dynamically configurable would be best. But that's only if you want to go all the way for that

**Comment by sonikro** [comment]
I opened the PR to decrease it to 50 for now, this should fix my instance and give us time to come up with a more dynamic approach.

**Comment by awanlin** [comment]
This was address by this PR: https://github.com/backstage/backstage/pull/22523 and was release as part of `1.23.0` a few months ago. Have you upgraded to the latest @chicoribas? If you have and this is still an issue then please share more details to help understand the problem you are having better.

**Comment by chicoribas** [comment]
Hi @awanlin ... thanks for the response...

I understood that this was a provisory solution for this issue and some additional implementation is needed for a definitive fix. We have almost 560 teams on Github and we are facing some problems. 

But let me colect more evidences with my team. I think is better to open other issue to talk about this.

Thanks
