### ISSUE TITLE
🐛 Bug Report: UnifiedTheme Root Level FontFamily Doesnt work. 

### ISSUE THREAD

**Issue by DSmedley** [backstage/backstage#22354]
### 📜 Description

When migrating from the BackstageTheme to the UnifiedTheme, the fontFamily parameter at the top level of the `createUnifiedTheme` function doesnt apply the supplied fonts.

After doing some digging I found that there is a `typography` field in the `createBaseThemeOptions` function which contains another `fontFamily` field and this one does apply the supplied fonts. The problem is that you have to override the entire typography field in order to just override the fonts when doing it this way.

### 👍 Expected behavior

The provided fontFamily should be applied to the site

### 👎 Actual Behavior with Screenshots

Defining fontFamily at the root of `createUnifiedTheme` still defaults to `"Helvetica Neue", Helvetica, Roboto, Arial, sans-serif`.

### 👟 Reproduction steps

You can see this behavior right now on the demo site: https://demo.backstage.io

Change the theme to the Aperture theme and inspect to see that the fontFamily doesnt match the one provided in the theme: https://github.com/backstage/demo/blob/master/packages/app/src/theme/aperture.ts#L82

### 📃 Provide the context for the Bug.

As mentioned above the configuration for the demo site has fontFamily defined but its still using the default values.

This can be solved currently by simply removing the root level fontFamily in favor of fontFamily in typography, however, the `defaultTypography` constant in `createBaseThemeOptions.ts` is not exported and every field is required on the typography field. In order to override the fontFamily you have to override everything in typography. If defaultTypography was exported we could simply do:

``` js
typography: {
  ...defaultTypography,
  fontFamily: "custom fonts"
}
```

### 🖥️ Your Environment

I tested this in both Firefox and Chrome

I dont have the output of the cli info command

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
This is being fixed in the Demo site by this PR: https://github.com/backstage/demo/pull/240. For the Demo it makes sense to have the full object so that we can show how you might customize it.

But a proper solution to this is also needed. Personally think exporting `defaultTypography` would be the most straightforward. I'm still a little puzzled why the original `fontFamily` stopped working 🤔

**Comment by tudi2d** [comment]
So it is definitly unfortunate that TypeScript does not catch this at the moment - the types definitly need fixing. Currently the `UnifiedThemeOptions` & the `BaseThemeOptionsInput` have the `fontFamily` & I'm wondering if it should be removed from the top level..

With which function are you creating the theme? Do you use `createUnifiedTheme` & `UnifiedThemeOptions` or do you use `createUnifiedThemeFromV4` with a `v4` theme?

**Comment by awanlin** [comment]
I'm pretty sure they are just following what we did in the Aperture theme in the Demo site repo.

Discord thread: https://discord.com/channels/687207715902193673/1197265238756708412

**Comment by DSmedley** [comment]
> I'm pretty sure they are just following what we did in the Aperture theme in the Demo site repo.
> 
> 
> 
> Discord thread: https://discord.com/channels/687207715902193673/1197265238756708412

Yes i was following the demo changes so not the v4 function

**Comment by awanlin** [comment]
#22857 fixes this 🚀
