### ISSUE TITLE
💬 RFC: Event Subscription Mechanism for Cross-Plugin Module Integration in the New Backend System

### ISSUE THREAD

**Issue by elaine-mattos** [backstage/backstage#22393]
### 🔖 Need

Hey folks!

So, I've been working on adding event support for the GitlabDiscoveryEntityProvider and GitlabOrgDiscoveryEntityProvider modules for the Catalog Plugin. Ref. here: #21553 (inspired by #13931).

Now, the fun part: in the old backend system, event subscription was a breeze – just passed the eventBroker directly through the PluginEnvironment. But my team has decided to adopt the new backend system and after digging in, I realized the eventBroker should now be passed through extensionPoints, specifically the **eventsExtensionPoint**.

I have tried following what has been done for Bit Bucket Cloud [catalogModuleBitbucketCloudEntityProvider](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-bitbucket-cloud/src/module/catalogModuleBitbucketCloudEntityProvider.ts#L26C10-L26C30)  but I ran into the  [BackendInitilizer](https://github.com/backstage/backstage/blob/master/packages/backend-app-api/src/wiring/BackendInitializer.ts#L55C10-L55C21) throwing the error "Error: Illegal dependency: Module 'gitlab-discovery-entity-provider' for plugin 'catalog' attempted to depend on extension point 'events' for plugin 'events'. Extension points can only be used within their plugin's scope."

For now, I did a quick workaround by lifting the BackendInitilizer restriction, but I understand this is not the best solution. 

So, with this all in mind, I got a few questions:

Are there any cool tricks I might be missing? Some undiscovered stuff in the new backend system that I am not aware of?
In the new backend system, any legit ways to pass the eventBroker between different plugins? If yes, please don't hide it from me – how's it done? :D

### 🎉 Proposal

I haven't had the chance to dig into this more deeply, so I don't have a proposal ready as of now. Also, just a heads up, architecture isn't exactly my strongest suit...

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
This is indeed an issue! 👍 Fix is in the works: https://github.com/backstage/backstage/pull/22344 CC: @pjungermann

As for cross-plugin modules, it's not something we want to do because it breaks plugin isolation.

**Comment by pjungermann** [comment]
At least the use of the extension at other plugins or modules of these will be replaced with a service. About the final shape, there is still some room for change.

At the draft PR, you can already see how the dependency would be declared (like for other services).

**Comment by pjungermann** [comment]
@elaine-mattos the changes were released as part of the last main release. Please have a look.

**Comment by elaine-mattos** [comment]
Hi @pjungermann ,

thanks a ton! Yes, I saw it and have already submitted my [PR](https://github.com/backstage/backstage/pull/23373) as well. Sorry I forgot to close this RFC!
