### ISSUE TITLE
🐛 Bug Report: ERROR 404: PAGE NOT FOUND  Looks like someone dropped the mic!

### ISSUE THREAD

**Issue by nfaustina77** [backstage/backstage#22426]
### 📜 Description

Hello, 

Hope you are doing well. 
I am trying to take ownership of a table but i received "ERROR 404: PAGE NOT FOUND Looks like someone dropped the mic!"
Can you please help me to fix this issue? 

Thank you in advance. 
Kind regards,
Nita 

### 👍 Expected behavior

It should be able to transfer the ownertship of the table 

### 👎 Actual Behavior with Screenshots

![error](https://github.com/backstage/backstage/assets/157357061/4b76ac96-4dda-4c0a-ad46-07ed075dcfbf)

### 👟 Reproduction steps

https://bstage.prod.booking.com/notifications/team?orgunit_id=60001233

Click on notification: 

action approve/ reject --> approved 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Hi! Did you mean to report this internally?

**Comment by nfaustina77** [comment]
yes, i am sorry it is the first time for me to open a ticket. 
I guessed i made a mistake on this ticket?

**Comment by freben** [comment]
The thing is, you should probably not be on `https://github.com/backstage/backstage` at all. I expect you have some internal bug tracker of sorts. Reach out to the team that owns Backstage at your company for guidance.
