### ISSUE TITLE
🐛 Bug Report: Website Broken: Black Page 

### ISSUE THREAD

**Issue by Lazzaretti** [backstage/backstage#22421]
### 📜 Description

The webpage https://backstage.io/ is broken for me. The website showed only a black page.

### 👍 Expected behavior

See the content of the webpage :)

### 👎 Actual Behavior with Screenshots

It's black.

Console error:
```
Uncaught SyntaxError: Invalid or unexpected token (at runtime~main.85aede54.js:1:462148)
main.d0a60a9c.js:2 
Uncaught SyntaxError: Invalid or unexpected token (at main.d0a60a9c.js:2:1235520)
````

### 👟 Reproduction steps

Go to https://backstage.io/ with Chrome 120.0.6099.225.

### 📃 Provide the context for the Bug.

Chrome 120.0.6099.225

### 🖥️ Your Environment

not needed here

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Yeah, sorry about that - we have reverted the change that caused this.
