### ISSUE TITLE
[RFC] Golden Path to plugin development

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#2243]
# Need

While our [documentation](https://backstage.io/docs) is slowly getting better, there is a need for a more step-by-step tutorial that guides a new plugin developer through the full process of building a shipping a plugin. Inside Spotify we call these tutorials Golden Paths:

https://engineering.atspotify.com/2020/08/17/how-we-use-golden-paths-to-solve-fragmentation-in-our-software-ecosystem/ 

# Proposed solution

Create a **"Golden Path to plugin development"** with the following outline (details are out of scope for this RFC):

## Part 1: Creating a new plugin

- What to build (use PagerDuty example)
- Creating a new plugin
- Finding your plugin

## Part 2: Building the UI

- Layout and design
- Testing

## Part 3: Fetch external data

- Get a token from PagerDuty
- Add to the proxy
- Storing token and/or secrets

## Part 4: Add plugin to Service Catalog

- Add plugin to App
- Adding navigation and tab
- Link plugin to Component definition (`annotations:`) _should this **association** be elsewhere? 🤔_
- Integrate with a Backstage Software Template

## Part 5: Publish your plugin

- Distribute plugin via NPM
- Add plugin to Marketplace

**Comment by timbonicus** [comment]
We're still planning on this one 😄  Perhaps with some targeted high-value cases (catalog ingestion, for example).
