### ISSUE TITLE
🐛 Bug Report: techdocs-node fails to handle --defaultPlugin properly when extra config is used

### ISSUE THREAD

**Issue by jackmtpt** [backstage/backstage#22467]
### 📜 Description

IF you use the --defaultPlugin argument to techdocs-cli (which calls techdocs-node, where the bug actually is) AND you already have one of the plugin names that you pass to it in your mkdocs.yml file AND that plugin has configuration, THEN you will end up with a duplicate entry for the plugin - your original one with config and one without config that was added by the default plugin handling code.

### 👍 Expected behavior

If you already have the plugin specified with configuration, then it should not be added again - the instance that you've already defined should remain as-is.

### 👎 Actual Behavior with Screenshots

When running `techdocs-cli generate` you will see this in the debug logs:

```
DEBUG   -  Config value 'plugins' = {'techdocs-core': <src.core.TechDocsCore object at 0x7b2a0abff580>, 'custom-plugin': <custom_plugin.plugin.Rewriter object at 0x7b2a0a4d6aa0>, 'custom-plugin #2': <custom_plugin.plugin.Rewriter object at 0x7b2a0a2e9f00>}
```

that second instance should not be present.

### 👟 Reproduction steps

`techdocs-cli generate --no-docker --etag blah --techdocs-ref url:https://dev.azure.com/org/project/_git/repo.name --source-dir . --output-dir /azp/_work/1/a/techdocs/ --defaultPlugin custom-plugin --verbose`

with mkdocs.yml:

```
site_name: Product Documentation
docs_dir: docs
plugins:
  - techdocs-core
  - custom-plugin:
      config:
        option1: 1
        option2: asdf
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jackmtpt** [comment]
I'm going to work on a PR to fix this

**Comment by vinzscam** [comment]
thanks a lot @jackmtpt! 🙏
Issue assigned! 🚀

**Comment by jackmtpt** [comment]
Finally got approval to publish the fix - PR created.
