### ISSUE TITLE
 Scaffolder ui:widget:password docs update

### ISSUE THREAD

**Issue by delacruzmichael** [backstage/backstage#22476]
### 📜 Description

Explicitly calling out that `ui:widget:password` only masks in secrets in the UI, not in logs and template adopters should use the Secret extension added in scaffolder: `Secret` extension to hide secrets securely by benjdlambert · Pull Request [#21287](https://github.com/backstage/backstage/pull/21287) to ensure they're secure.

### 👍 Expected behavior

We want to update the docs in order to make it clear that `ui:widget:password` only masks in secrets in the UI, not in logs and template adopters should use the Secret extension added in scaffolder

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-01-23 at 2 10 17 PM](https://github.com/backstage/backstage/assets/156248611/cecf3df2-3fa3-4edc-8add-a64d937df7c2)

### 👟 Reproduction steps

Navigate to https://backstage.io/docs/features/software-templates/writing-templates/

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@delacruzmichael think that we should just remove this section from the docs entirely. Do you want to raise a PR to remove it so that we can encourage the correct way?

**Comment by delacruzmichael** [comment]
@benjdlambert - Sure I can do that
