### ISSUE TITLE
🚀 Feature: Add support for api-docs plugin components to use a different color from palette rather than default background color

### ISSUE THREAD

**Issue by chandanadatta9** [backstage/backstage#22516]
### 🔖 Feature description

Currently the components of api-docs plugin depend on `backgroundColor: theme.palette.background.default`
https://github.com/backstage/backstage/blob/206c6367a894e3c1547a290d3c1a35f507608929/plugins/api-docs/src/components/OpenApiDefinitionWidget/OpenApiDefinition.tsx#L31-L33

Above is one example of OpenApiDefinition component scheme container background color depending on the default background color. It would be great if it can have its own color from palette, that gives the flexibility to use different colors other than default color.

### 🎤 Context

This feature gives the flexibility to use different colors other than default color. Based on the custom theme created, there are cases where we could not use the default color for the components and gives more flexibility while creating new themes if the components can have their own color in the palette.

### ✌️ Possible Implementation

plugins/api-docs/src/components/OpenApiDefinitionWidget/OpenApiDefinition.tsx

`backgroundColor: theme.palette.plugins.apidocs.schemacontainer`

As an example
https://github.com/backstage/backstage/blob/8cea347e80ec76aa02d56e4ddd278c12d4a4fad6/packages/theme/src/base/palettes.ts#L22-L29

Adding a new color block in the theme palette
```...
     ...
     plugins: {
        apidocs: {
            schemacontainer: '#1b5e20'
        }
     }
     ...
 ```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tudi2d** [comment]
Thanks for raising this issue! What would be intended here is to allow overriding the styles through classes rather than having additional properties on the theme as that is hard to maintain. I think we wrote in this thread on Discord about the possible implementation - adding it here as well: 

**OpenApiDefinition.tsx**
```diff 
const useStyles = makeStyles(theme => ({
  root: {
    '& .swagger-ui': {
      // ...
      [`& .scheme-container`]: {
        backgroundColor: theme.palette.background.default,
      },
      //...
+  { name: 'PluginOpenApiDefinition' },
```

With this you would now be able to create overrides in the theme for all classes of the component (https://backstage.io/docs/getting-started/app-custom-theme#overriding-backstage-and-material-ui-components-styles).  So smth. like this would be possible: 

```tsx
export const createCustomThemeOverrides = (
  theme: BackstageTheme,
): OpenApiOverrides => {
  return {
    PluginOpenApiDefinition: {
      root: {
       '& .swagger-ui .scheme-container': {
         backgroundColor: "pink"
       }
      },
    },
  };
};
```

**Comment by chandanadatta9** [comment]
@Rugvip, will open a PR for this
