### ISSUE TITLE
🚀 Feature: Azure DevOps Plugin Support for Permissions

### ISSUE THREAD

**Issue by mattemoore** [backstage/backstage#22519]
### 🔖 Feature description

We would like to be able to limit the features in the Azure DevOps plugin to be only consumable by users declared in the catalog.  Extending Azure DevOps plugin to expose a few permissions would enable this and other similar functionality.

### 🎤 Context

Our Backstage is deployed behind a VPN.  As such no one external to our org can access Backstage.  This is good.

That being said, anyone inside of the organization can access data in Backstage.  Whereas we want to foster an open culture of code sharing etc. the reality is we have organizational security controls that must be met and one of them is limiting access to the data in a system to only those that are registered users of a system.

In my use case I would like to limit the data displayed by the various Azure DevOps plugin features (PRs, Readme, CI/CD ...) to only users registered in the catalog.

### ✌️ Possible Implementation

```
class PortalPermissionPolicy implements PermissionPolicy {
  async handle(
    request: PolicyQuery,
    user?: BackstageIdentityResponse,
  ): Promise<PolicyDecision> {
    // Only users registered in catalog can view summary of PRs via Backstage
    if (request.permission.name === 'devops.pullrequests.read') {
      if (user) {
        return {
          result: AuthorizeResult.ALLOW,
        };
      } else {
        return {
          result: AuthorizeResult.DENY,
        };
      }
// .... and so on for other DevOps plugin features
    }
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @mattemoore, I'm the initial author of the Azure DevOps plugin and maintainer. This sounds reasonable to me, it's not something I have time to work on myself so it will need to come from you or someone else in the Community. My only expectation around this is that we make it opt-in so as not to impact current Adopters of the plugin.

@deepan10, you've done some work around permissions for Azure Sites recently, do you happen to have some time to take this on? This would be as simple as adding a read permission for each feature, using that for each of the backend routes and then using `RequirePermission` for the frontend components.

**Comment by deepan10** [comment]
Hello @awanlin, Yes I am happy to take it, will implement the permission framework in `azure-devops` plugin for each feature and raise a PR.

**Comment by awanlin** [comment]
Awesome, many thanks in advance @deepan10! 🚀

**Comment by afscrome** [comment]
I'm pretty sure it wouldn't work for Azure Devops Server.  You may be able to get somethign similar if you rely on browser/windows auth but that would also require you to throw out the proxy and have the browser directly communicate with the Azure Devops Server which brings about a different set of complications.

As for examples, best example right now would be the Kubernetes provider - https://github.com/backstage/backstage/blob/f600aa87a3b3f7700544653b8560c86cba3cd479/plugins/kubernetes-react/src/kubernetes-auth-provider/AksKubernetesAuthProvider.ts#L35-L37 .

Slightly more Azure DevOps specific, a colleague and I are exploring using user auth in the scaffolder, but that's still work in progress right now (#22644 is somewhat related to that effort).

**Comment by awanlin** [comment]
Closing this at support for the permission framework was added and release with version `1.24.0` of Backstage
