### ISSUE TITLE
🚀 Feature: AsyncApi v3 Support

### ISSUE THREAD

**Issue by Lazzaretti** [backstage/backstage#22534]
### 🔖 Feature description

Is AsyncApi v3 officially supported for APIs?

### 🎤 Context

In objects [Kind: API](https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-api) there is nothing written about AsyncApi versions. For OpenApi versions are described.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Lazzaretti** [comment]
It looks like it is supported, so it would be nice if the versions were explicitly written up.

**Comment by CerosDev** [comment]
I can't seem that get the auto-generated UI to work with v3. My AsyncAPI is detected and categorized appropriately but for the UI I get

`Error: Version 3.0.0 is not supported.`

**Comment by Lazzaretti** [comment]
> I can't seem that get the auto-generated UI to work with v3. My AsyncAPI is detected and categorized appropriately but for the UI I get
> 
> `Error: Version 3.0.0 is not supported.`

Interesting! I have now created a PR to show the example and it works there: https://backstage-default-pr-22536-c2925.uclusters.app.uffizzi.com/catalog/default/api/streetlights/definition

Can it be that the npm package for asycnapi is not up to date?

**Comment by vinzscam** [comment]
Thank you for updating the docs @Lazzaretti 🙏

> I can't seem that get the auto-generated UI to work with v3. My AsyncAPI is detected and categorized appropriately but for the UI I get
>
> Error: Version 3.0.0 is not supported.

@CerosDev are you getting the error when you are opening the definition of the API?

**Comment by CerosDev** [comment]
I get that error when I look at the "AsyncApi" tab. The "Raw" tab is fine.

**Comment by Rugvip** [comment]
@CerosDev, what versions of the `@asyncapi/*` packages do you have installed? Have you tried updating them?
