### ISSUE TITLE
[Plugin] AWS CodePipeline

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#2256]
## Summary

This plugin would visualise builds and other CI/CD information from your AWS CodePipeline project.

> AWS CodePipeline automates your software release process, allowing you to rapidly release new features to your users. With CodePipeline, you can quickly iterate on feedback and get new features to your users faster.

## Project website (if applicable)

https://aws.amazon.com/codepipeline/

## Context

The existing CircleCI plugin can be used for inspiration:

https://github.com/spotify/backstage/tree/master/plugins/circleci

![](https://github.com/spotify/backstage/raw/master/plugins/circleci/src/assets/screenshot-1.png)

**Comment by YashishDua** [comment]
Hi, **good-first-issue** label attracted me here. I am looking to pick up this issue next week till then would spend some time reading the code, and understanding the flows.

 @stefanalund I see it's been a month since this issue was opened. Just poking you here to check the status of this. :)

**Comment by stefanalund** [comment]
@YashishDua great! Let us know if you need any support. There are quite a few CI plugins now so hopefully you should be able to use them as inspiration: https://backstage.io/plugins

**Comment by stefanalund** [comment]
@YashishDua great! Let us know if you need any support. There are quite a few CI plugins now so hopefully you should be able to use them as inspiration: https://backstage.io/plugins

**Comment by regicsolutions** [comment]
@YashishDua just checking in to see if you made any progress with this plugin?

**Comment by adamdmharvey** [comment]
Going to reopen this one, as I see a lot of industry use of it and as a parallel to Jenkins, Circle, and the others, I think it would be a key add to leave open for community controls!

**Comment by freben** [comment]
Yeah I think ALL plugin suggestion ones should be reopened and marked as hands-off  for stalebot!

**Comment by Amir-Abushanab** [comment]
Mind if I get assigned this one?

**Comment by adamdmharvey** [comment]
@Amir-Abushanab Awesome! Excited to see what you come up with; assigned.

**Comment by jamesrenaud** [comment]
@Amir-Abushanab I've added cross-account support (via roleArns) in https://github.com/RoadieHQ/backstage-plugin-aws-auth#using-an-iam-role-for-cross-account which would be extremely useful to include in your implementation (who doesn't use Organizations these days? 😄 )

**Comment by regicsolutions** [comment]
@Amir-Abushanab checking in to see if you were able to make any progress with this plugin?

**Comment by Amir-Abushanab** [comment]
Hi folks, haven't gotten a chance to make much progress, please feel free to reassign. As @jamesrenaud pointed, you'll almost definitely need to take a dependency on https://github.com/RoadieHQ/backstage-plugin-aws-auth#using-an-iam-role-for-cross-account

**Comment by niallthomson** [comment]
We're taking a look at this integration and have a working prototype. You can assign this to me for tracking if it helps.

**Comment by niallthomson** [comment]
Apologies I've been out on parental leave for a few weeks. We're working on a public repository!

**Comment by anshulgargamway** [comment]
@niallthomson : Any information on this prototype ?

**Comment by niallthomson** [comment]
Hi folks, we published a first pass at a AWS CodeSuite plugin that includes some support for CodePipeline. You can find it here:

https://github.com/awslabs/aws-codepipeline-plugins-for-backstage

We are still working on publishing NPM packages and getting it added to the Backstage plugin marketplace.

**Comment by arslan-raza-143** [comment]
> ## Summary
> This plugin would visualise builds and other CI/CD information from your AWS CodePipeline project.
> 
> > AWS CodePipeline automates your software release process, allowing you to rapidly release new features to your users. With CodePipeline, you can quickly iterate on feedback and get new features to your users faster.
> 
> ## Project website (if applicable)
> https://aws.amazon.com/codepipeline/
> 
> ## Context
> The existing CircleCI plugin can be used for inspiration:
> 
> https://github.com/spotify/backstage/tree/master/plugins/circleci
> 
> ![](https://github.com/spotify/backstage/raw/master/plugins/circleci/src/assets/screenshot-1.png)

#14794

**Comment by niallthomson** [comment]
Earlier this month the AWS CodeSuite plugin was published to NPM and added to the Backstage plugin marketplace.

https://github.com/awslabs/aws-codesuite-plugins-for-backstage

I'd say this issue can be closed and any further feature requests related to this service can be added to that repository.

**Comment by adamdmharvey** [comment]
Awesome @niallthomson !  I'd agree, that definitely seems to cover the original intent of this issue.

It's definitely in the plugin catalog (https://backstage.io/plugins) and at the link you suggested.  Closing!
