### ISSUE TITLE
🐛 Bug Report: Fix Readme of Techdocs

### ISSUE THREAD

**Issue by AntoniaAdler** [backstage/backstage#22578]
### 📜 Description

I was lacking the information where I have to persist the documentation pages

In the Readme file of the repo https://github.com/backstage/backstage/blob/master/plugins/techdocs/README.md it says 
> The default setup of TechDocs assumes that your documentation is accessed by reading a page with the format of `<storageUrl>/<entity kind>/<entity namespace>/<entity name>`. This can be configured by [implementing a new techdocs storage API](https://backstage.io/docs/features/techdocs/how-to-guides#how-to-implement-your-own-techdocs-apis).

This information seems wrong. I think the correct URL is `<storageUrl>/<entity namespace>/<entity kind>/<entity name>`

### 👍 Expected behavior

Ideally this information is accessible on the website https://backstage.io/docs/features/techdocs/ 

### 👎 Actual Behavior with Screenshots

misleading documentation

### 👟 Reproduction steps

- 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Parsifal-M** [comment]
Hey @AntoniaAdler :wave: 

Good catch! I do think this does indeed need updating, looks like it's not been touched for about 3 years :laughing:

**Comment by sagardesai1** [comment]
Hey! I am make this change on the Readme. Can you assign me?

**Comment by Rugvip** [comment]
@sagardesai1 thank you! 👍

**Comment by sagardesai1** [comment]
@Rugvip made a PR for those changes, would you mind reviewing?

**Comment by Rugvip** [comment]
@sagardesai1 it was assigned to TechDocs maintainers, but it's and obvious fix so I shipped it along. Thank you! 👍
