### ISSUE TITLE
🚀 Feature: Allow defining custom validation error for scaffolder parameters

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#22575]
### 🔖 Feature description

Currently, when there is a for example Regex pattern in the scaffolder parameter and the user inputs non-valid content to the input, an error is shown. Template developers should be able to modify this error message for a better user experience.

### 🎤 Context

For example, regex errors do not make sense to people who don't know the regex syntax. Therefore, adding a `validationError` (or similar) data to a parameter in the template yaml file that is shown to the user instead or beside the default validation error should be possible. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
I wonder if we should ask about this upstream in the RJSF library and see if it's something that can be supported in the `ui:schema` for when a `pattern` does not match? Feels like that would be the better solution for this I think.

**Comment by drodil** [comment]
The rjsf does not support that so they requested to do some customization on backstage side. Do you think we could take this forward?

**Comment by benjdlambert** [comment]
@drodil hmm ok, so we have the `ui:backstage` prefix that we could add this to, but I was thinking about deprecating that in upcoming versions too, and working out a better replacement for it. Perhaps either this is the reason it stays, or we find a better place to put this.

Do you have any ideas about what this could look like?

**Comment by drodil** [comment]
We have quite a lot of cases where we validate the input with regex pattern. In many cases the regex can be very hard to understand, especially for people with no dev background, so there could be additional error for example:

```
Please input correct email address (has to end with @domain.com) (Original error here, regex failed)
```

Don't really know where this would sit in the yaml file though. Any ideas for this?

**Comment by benjdlambert** [comment]
yeah, thats the exact use case that I think this would be perfect for.

What I'm thinking is that this could be a `CustomFieldExtension` at least at the beginning.

```yaml
parameters:
  email:
     type: string
     pattern: ^\S+@\S+\.\S+$"
     ui:field: Regex
     ui:options:
       error: Please input correct email address (has to end with @domain.com) (Original error here, regex failed)
```

Or at least something like this. It would then run the validation in the custom field extension validation handler and throw an error with the error text.

Thoughts?

**Comment by mbenson** [comment]
I am rather intrigued by the comment [here](https://stackoverflow.com/a/45202473) where the property schema is extended to support a `message` "subschema", if you will. Then it should be possible to implement a custom `[ErrorTransformer](https://rjsf-team.github.io/react-jsonschema-form/docs/usage/validation/#custom-error-messages)` to look up the specified message using the information that API receives. Might be one-and-done rather than a specific field extension for regex, and on and on.

**Comment by benjdlambert** [comment]
@mbenson hmm, I like it,  do you wanna whip up a PR and we can chat more? :pray:

**Comment by drodil** [comment]
Not stale
