### ISSUE TITLE
🐛 Bug Report: Group diagram in explore page, cards are way apart and overall style is too compact

### ISSUE THREAD

**Issue by LegendSebastianoL** [backstage/backstage#22573]
### 📜 Description

Referring to this Discord [thread](https://discord.com/channels/687207715902193673/687235481154617364/1200443061923229746) seems like there is a bug in the explore page precisely in the group panel where cards are too compacted and sometimes too separate for no apparent reason.

I'm opening this issue in case I can't open a PR for it

I know the demo page has fewer relationships compared to my group but look at the 3rd row, it has 2 direct children, one of them is directly below the card and the other one after the gap is again a child of the same group.

Children often end up below other groups instead of expanding the whole diagram.

![groups](https://github.com/backstage/backstage/assets/61748264/cdabf152-e5e9-4371-8d1e-9dc0d68d25e3)

### 👍 Expected behavior

I would expect the direct children to be near each other and not so far away especially if the previous level doesn't have children.
I'm also expecting the groups to expand a bit more and not be so compact in the overall style.

### 👎 Actual Behavior with Screenshots

as per the screenshot above, direct children are far apart for no reason and often under other groups.

### 👟 Reproduction steps

- 1 org
- 10 children
  - 1 with 4 children of which:
    - 1 have 4 children
    - 1 with 2
    - 1 with 0
    - 1 with 5
   - 1 with 12 of which:
     - 2 with 0
     - 1 with 7
     - 1 with 1
     - 1 with 0
     - 1 with 1
     - 1 with 0
     - 2 with 2
     - 1 with 3
     - 1 with 0
     - 1 with 2
   - 1 with 3 of which:
     - 2 with 0
     - 1 with 5
   - 1 with 0
   - 1 with 2 of which:
     - 2 with 0
   - 1 with 0
   - 1 with 4 of which:
     - 1 with 2
     - 3 with 0
   - 1 with 4 of which:
     - 1 with 5
     - 1 with 2
     - 1 with 1
     - 1 with 5
    - 1 with 5 of which:
      - 2 with 1
      - 1 with 4
      - 1 with 3
      - 1 with 0
    - 1 with 1 that has 4 children

you should end up with something like this: (sorry for the quality)
![fullgroup](https://github.com/backstage/backstage/assets/61748264/32b2bc5d-7aed-4971-aabe-df9852f479c3)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
thanks for suggesting this. Sure, it would make things look better.
