### ISSUE TITLE
Enable usage of OAuth2 provider in frontend

### ISSUE THREAD

**Issue by kingasieminiak** [backstage/backstage#2259]
There are two limitations in the current implementation of [OAuth2](https://github.com/spotify/backstage/blob/master/packages/core-api/src/apis/implementations/auth/oauth2/OAuth2.ts) provider used by the client:
- incompatible type of `oauth2ApiRef` (missing `BackstageIdentityApi` in type definition) causes type check error;
- an array of `defaultScopes` is set for `RefreshingAuthSessionManager` which causes those oauth2 flows that don't support them to break.

## Suggested changes
1) Extending the type definition of `oauth2ApiRef`:

```js
export const oauth2ApiRef = createApiRef<
  OAuthApi &
    OpenIdConnectApi &
    ProfileInfoApi &
    SessionStateApi &
    BackstageIdentityApi
>({
  id: 'core.auth.oauth2',
  description: 'Example of how to use oauth2 custom provider',
});
```
2) Allow passing an array of `defaultScopes` to `create` method of `OAuth2` class:

```js
static create({
    discoveryApi,
    environment = 'development',
    provider = DEFAULT_PROVIDER,
    oauthRequestApi,
    defaultScopes = [
      'openid',
      `${SCOPE_PREFIX}userinfo.email`,
      `${SCOPE_PREFIX}userinfo.profile`,
    ],

const sessionManager = new RefreshingAuthSessionManager({
      connector,
      defaultScopes: new Set(defaultScopes),
```

**Comment by Rugvip** [comment]
What are the use-cases for using the generic OAuth2 provider as a provider? Is it only sign-in or also usage inside the app?

Another change I could imagine is to remove the `oauth2ApiRef` and just export the generic `OAuth2` class. That way apps can create their own internal `ApiRef`s for whatever auth provider they're actually using, and use the `OAuth2` class as the implementation. Reasoning behind that being that `oauth2ApiRef` isn't really somewthing that plugins can use and rely on for any kind of functionality, as it doesn't specify what provider you will actually getting tokens for at runtime.

`defaultScopes` change should definitely make sense! They're set to the Google ones right now which is a bug, so those should also be removed.

**Comment by adamdmharvey** [comment]
Just following up - does the fact that #2326 was merged mean this ticket can be closed now?

**Comment by freben** [comment]
Indeed!
