### ISSUE TITLE
Can you provide an API to modify the relationships between entities?

### ISSUE THREAD

**Issue by umyonghyun** [backstage/backstage#22593]
### 🔖 Feature description

software catalog entities

### 🎤 Context

Our User entity is configured in conjunction with LDAP.
Component entities are created by querying the external API through CustumEntityProvider.

After all entities are created, I would like to specify a user as an owner in the component, but the related API does not seem to be provided.

### ✌️ Possible Implementation

I wish an API to update the final entity would be provided.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
That's not possible to do from the outside. Relations are created by entity processors during the processing loop. See the [the life of an entity](https://backstage.io/docs/features/software-catalog/life-of-an-entity) article.

Do you have an external source for this ownership mapping? If that data source doesn't exist, you can build it as a small Backstage backend plugin with a CRUD interface, and the processor can then consume that same interface.

Then your custom entity provider can insert the `spec.owner` field based on that data source. Then the default catalog model processor will translate that to a relation as per usual.

You can also write a processor whose job is just to emit [`ownerOf`/`ownedBy`](https://backstage.io/docs/features/software-catalog/well-known-relations#ownedby-and-ownerof) relations for entities, based on that external data source. But that's much less efficient; you will prefer to do it upfront in the entity provider if possible instead.
