### ISSUE TITLE
BEP: Auth Architecture Evolution

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#22605]
### 🔖 Feature description

This proposal outlines a new architecture for authenticating users and services in Backstage. It adds built-in access restriction to Backstage instances that protects them from outside access, and enables more granular access control for inter-plugin communication and access from external services.

It proposes a new `AuthService` interface that handles all user and service authentication and token management available to plugins, as well as a new `HttpAuthService` interface that is a higher level service used to protect endpoints of plugin routers. The `auth-backend` will also be extended to support issuing of user tokens with a reduced scope for cookie-based authentication of requests.

The changes to the service-to-service auth are aimed to be the minimum needed to get the necessary interfaces in place, and will rely on the existing symmetrical keys for now.

### 🎤 Context

https://github.com/backstage/backstage/blob/master/beps/0003-auth-architecture-evolution/README.md

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sennyeya** [comment]
Thanks for this! Excited to see this moving forward. My PRs couldn't have come at a worse time 😅. Couple of comments that I didn't see fitting into the BEP PR discussion.

> Built-in protection of Backstage instances such that it is safe to deploy Backstage directly towards the internet. 
> The proposed design leaves the decision for how different endpoints are protected to the implementation of the plugin backends themselves.

I'm concerned about the inter-meshing of these 2 points. I think I get the general premise, delegate to plugin owners and trust them to secure their plugin correctly. My concern is that if this requires additional work on the part of the plugin writer, adoption will be varied. Permission framework being a good example, plugins in this repository are still getting PRs to add permissions (#22591, #21044) and external repositories still have low adoption as well.

I can see this opening up a new avenue of supply chain "attack" for adopters as the actual authentication of their plugins is up to the plugins themselves. Positive case is this leads to awesome community work to get plugins to use this new authentication, negative case is this leads to per-company forks and fragmentation.

> This means that integrators do not need to - and do not have the ability to - configure access controls of individual endpoints, except for what the permission system already provides, and what is made available through static configuration or extension points.

Similar to the above, if we stick with a model of just opt-in authentication protection, I think this is likely to put more work on community plugins. If I want to use plugin A, I have to validate that they are using this middleware on _every_ route and if they're not, that they have a well documented reason for not. 

If I were to lean into the "It will no longer be a requirement to either set up protection of your Backstage instance", this introduces, IMO, a pretty legitimate supply chain risk for using community plugins. If my Backstage instance is using community plugin A and thus far they've been good to update their routes to use the middleware, but they forgot to include it on their new super secret endpoint. When I'm doing the upgrade, I should be doing my due diligence, but this seems like an easy thing to miss. Now my super secret data is available if I don't have additional protections on my Backstage instance.

As I had in my PR, thoughts on enforcing a "default" authentication on the `httpRouterService.use` method that could be overridden per plugin? Something like `httpRouterService.disableAuthentication()` and then having to use the middleware from `HttpAuthRouter`.

> type AuthTypes = 'user' | 'user-cookie' | 'service' | 'unauthorized';
> 
> export interface HttpAuthServiceMiddlewareOptions {
>   allow: AuthTypes[];
> }
>  middleware(options?: HttpAuthServiceMiddlewareOptions): Handler;

In a different vein, this also has ramifications for plugin owners that have different ideas of what should be authorized. I think I brought this up as part of the discussion for plugin owner defined policy groupings in the permission framework. If a plugin I'm using decides to allow unauthorized users and authorized users, how would I specify that I only want authorized users? That makes sense to sit at the `AuthService` level as a config value I think. However, the inverse, I want to allow external services to do everything an authorized user does, how would I enable that if plugin A wanted to restrict 'unauthorized', but forgot 'service' in its allowlist?

**Comment by Rugvip** [comment]
@sennyeya on the first point, totally, just forgot to include that goal in the initial PR, update in #22609

For the last point I'm sure I understand the exact concern, do you have some concrete example?

**Comment by sennyeya** [comment]
@Rugvip I can only think of contrived examples, which might not be helpful. The core concern was lack of options for integrators to override overly restrictive plugin implementations. The solution there should probably not be addressed, and handled instead by community help, either a PR/forking.

**Comment by Rugvip** [comment]
Highlighting the discussion about auth header size here as something to address: https://github.com/backstage/backstage/pull/22634#discussion_r1474637138

**Comment by Rugvip** [comment]
Initial implementation PR of this is now up here: https://github.com/backstage/backstage/pull/23054. It more or less fully introduces all interfaces needed for this work, but there are still quite a few underlying implementations that need to be added as followups.

**Comment by Rugvip** [comment]
Now implemented #24413
