### ISSUE TITLE
🐛 Bug Report: Update app-custom-theme docs

### ISSUE THREAD

**Issue by reece-stephenson** [backstage/backstage#22606]
### 📜 Description

The documentation for [`creating a custom theme`](https://backstage.io/docs/getting-started/app-custom-theme/)  is using deprecated imports, hence needs to be updated with the new correct method for creating a custom theme. 

### 👍 Expected behavior

Documentation for [app-custom-theme](https://backstage.io/docs/getting-started/app-custom-theme/) is up to date with current imports.

### 👎 Actual Behavior with Screenshots

The tutorial imports `createTheme `and `lightTheme `which are both deprecated. 

### 👟 Reproduction steps

1. Go to [https://backstage.io/docs/getting-started/app-custom-theme/](https://backstage.io/docs/getting-started/app-custom-theme/)
2. Follow the tutorial for creating a custom theme
3. See that some imports are deprecated and should not be used

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
For whoever might pick this issue up:

An example of an up to date theme would be here: https://github.com/backstage/demo/blob/master/packages/app/src/theme/aperture.ts - just example to help with the structure I would update the existing docs to match 

Then here's an example of how you would "register" the custom theme: https://github.com/backstage/demo/blob/baa97ae7465d72cd5c5a527148bb3a4de313cc3e/packages/app/src/App.tsx#L60-L89
