### ISSUE TITLE
🚀 Feature: Add BEPs to Backstage.io

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#22657]
### 🔖 Feature description

Just like ADRs, it would make sense to also show BEPs at backstage.io

### 🎤 Context

This allows users to follow BEPs and their evolution directly from the site instead of navigating to the GitHub

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Thanks @drodil, this was on my to do list to log! Plus 1 to this idea!

**Comment by Rugvip** [comment]
Good idea! happy for any help we can get to have this implemented 🙏

**Comment by awanlin** [comment]
I've been thinking about this one. There isn't a way to bring this into the current site as is via some easy existing Docusaurus config. The other options we have are:

- We could use the `docusaurus-plugin-remote-content` plugin but this feels heavy handed to me
- We could write a quick script to copy the `/bep` folder into the `/docs` folder as part of the build process
