### ISSUE TITLE
💬 RFC: [Azure DevOps] Use `entityRef`s to Communicate With The Backend

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#22668]
### 🔖 Need

Currently the Azure DevOps backend and frontend API is has become a bit of a mess with various routes, subpaths, and query string parameters. This is causing it to be harder to build on new features and maintain the current ones.

Frontend `AzureDevOpsApi`: https://github.com/backstage/backstage/blob/fe2e15d4582a154b8ef208248b69ff81e52ed676/plugins/azure-devops/src/api/AzureDevOpsApi.ts#L39-L81

Backend `router.ts`: https://github.com/backstage/backstage/blob/fe2e15d4582a154b8ef208248b69ff81e52ed676/plugins/azure-devops-backend/src/service/router.ts#L57-L227

### 🎉 Proposal

I propose passing the `entityRef` from the frontend to the backend which would then look up the entity from the catalog and take the needed steps from there. Inspiration for this came from the Jira Dashboard's approach.

Frontend `AzureDevOpsApi`: 

```ts
export interface AzureDevOpsApi {
  getRepoBuilds(
    entityRef: string
  ): Promise<{ items: RepoBuild[] }>;

  getGitTags(
    entityRef: string
  ): Promise<{ items: GitTag[] }>;

  getPullRequests(
    entityRef: string
  ): Promise<{ items: PullRequest[] }>;

  getDashboardPullRequests(
    entityRef: string
  ): Promise<DashboardPullRequest[]>;

  getAllTeams(): Promise<Team[]>;

  getUserTeamIds(userId: string): Promise<string[]>;

  getBuildRuns(
    entityRef: string
  ): Promise<{ items: BuildRun[] }>;

  getReadme(entityRef: string): Promise<Readme>;
}
```

Backend `router.ts`: 

This:

```ts
router.get('/builds/:projectName/:repoId', async (req, res) => {
    const { projectName, repoId } = req.params;
    const top = req.query.top ? Number(req.query.top) : DEFAULT_TOP;
    const host = req.query.host?.toString();
    const org = req.query.org?.toString();
    const buildList = await azureDevOpsApi.getBuildList(
      projectName,
      repoId,
      top,
      host,
      org,
    );
    res.status(200).json(buildList);
  });
```

Could become this:

```ts
router.get('/builds/:entityRef', async (req, res) => {
    const { entityRef } = req.params;
    const entity = catalogApi.getEntityByRef(entityRef)
    const buildList = await azureDevOpsApi.getBuildList(
      entity
    );
    res.status(200).json(buildList);
  });
```

Note: some of the logic would be moved around and into the `AzureDevOpsApi`

### 〽️ Alternatives

I'm not sure any alternatives. We could continue down the road we are going and things could end up being just be fine that way.

### ❌ Risks

I'm not aware of any other initiatives that would impact this. This aspect of the Azure DevOps plugin is pretty isolated.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by awanlin** [comment]
Once we settle on this and decided if it's the right direction I'm willing to do the work needed for this in the Spring (April-May).

@marleypowell @afscrome @deepan10 would like your thoughts on this? Am I making this a bigger deal then it needs to be?

**Comment by afscrome** [comment]
The one drawback I can see with taking an entityRef is it now means that every call to the azure devops api will result in an additional database call to load the entity.  A single call doesn't matter much, but the volume could add up.  Maybe the core backstage team have a general thought about whether backends should take an entity ref (simple, but extra db load), or whether the client side should process the entity annotations and send them to a backend.

If the focus is to remove some of the duplication in the azure devops api code, I wonder if there are some other ways we can do this without needing to load the entity again on the server.  

Off the top of my head, a couple of ideas - I'm not hugely familiar with this portion of the Azure Devops so if there's somethign small not lining up with your expectations, it is likely a mistake on my part.

## Idea 1

One way could be to introduce a type for the common azure devops info, with a common method to extract it. e.g.

```ts
type RepoInfo = {
    host: String,
    org: String
    projectName: String,
    repoId: String
}
```

That would then leave the AzureDevOps api being more like:

```ts
export interface AzureDevOpsApi {
  getRepoBuilds(
    repoInfo: RepoInfo,
    options?: RepoBuildOptions,
  ): Promise<{items: RepoBuild[];}>;

  getGitTags(
    repoInfo: RepoInfo,
  ): Promise<{items: GitTag[]; }>;

  getPullRequests(
    repoInfo: RepoInfo,
    options?: PullRequestOptions,
  ): Promise<{items: PullRequest[];}>;

  getAllTeams(): Promise<Team[]>;

  getUserTeamIds(userId: string): Promise<string[]>;

  getBuildRuns(
    repoInfo: RepoInfo, //The RepoInfo here is a bit odd - it's only used for org and host, repo & project are ignored
    definitionName?: string,
    definitionProject?: string,
    options?: BuildRunOptions,
  ): Promise<{items: BuildRun[]; }>;

  getDashboardPullRequests(
    repoInfo: RepoInfo,
  ): Promise<DashboardPullRequest[]>;

  getReadme(opts: ReadmeConfig): Promise<Readme>;
}
```

The router could then look like:
```ts
router.get('/builds/:projectName/:repoId', async (req, res) => {
    const repoInfo = extractRepoInfo(req);
    const top = req.query.top ? Number(req.query.top) : DEFAULT_TOP;
    const buildList = await azureDevOpsApi.getBuildList(
      repoInfo
      top
    );
    res.status(200).json(buildList);
  });

// This function would be shared by all routers
function extractRepoInfo(req) : RepoInfo
{
    return {
        projectName: req.params.projectName,
        repoId: req.params.repoId,
        host: req.query.host?.toString(),
        org: req.query.org?.toString(),
    }
}
```

## Idea 2

What if rather than having a single instance of `AzureDevOpsApi`, we instead had one per host/org.  

```ts
export interface AzureDevOpsApi {
    constructor(
        host: string,
        org?: string
    )

    getRepoBuilds(
        project: string,
        repoId: string,
        options?: RepoBuildOptions,
    ): Promise<{ items: RepoBuild[]; }>;

    getGitTags(
        project: string,
        repoId: string,
    ): Promise<{ items: GitTag[]; }>;

    getPullRequests(
        project: string,
        repoId: string,
        options?: PullRequestOptions,
    ): Promise<{ items: PullRequest[]; }>;

    getAllTeams(): Promise<Team[]>;

    getUserTeamIds(userId: string): Promise<string[]>;

    getBuildRuns(
        project?: string,
        definition?: string,
        options?: BuildRunOptions,
    ): Promise<{ items: BuildRun[]; }>;

    getDashboardPullRequests(
        project: string,
        repoId: string,
    ): Promise<DashboardPullRequest[]>;

    getReadme(opts: ReadmeConfig): Promise<Readme>;
}
```
With the router being somethign like
```ts
router.get('/builds/:projectName/:repoId', async (req, res) => {
    const { projectName, repoId } = req.params;
    const top = req.query.top ? Number(req.query.top) : DEFAULT_TOP;
    const buildList = await getAzureDevopsApi(req).getBuildList(
      projectName,
      repoId,
      top
    );
    res.status(200).json(buildList);
  });

// This function would be shared by all routers
function getAzureDevopsApi(req) : AzureDevopsApi {
    return AzureDevopsApiFactory.get(
        req.query.host,
        req.query.org);
}

Having one `AzureDevopsApi` instance per host/org, could help to resolve the need to rebuild the WebApi you mentioned in https://github.com/backstage/backstage/pull/21796#issuecomment-1850676417

**Comment by deepan10** [comment]
@awanlin, I was thinking the same when we implemented the permission framework with `azure-devops` plugin. We are passing the `entityRef` to the backend to utilize the resource-based permission. 

The setup has been implemented in `azure-sites` plugin, the only difference is it uses the `catalogApi` to get the entity to validate and perform `start` and `stop`. We are doing this way to avoid any possible threat of an external `Azure App/Web` application. So each backend call undergoes an API `discoverApi` call to get entity JSON by `entities/by-name/{kind}/{namespace}/{name}.

https://github.com/backstage/backstage/blob/36dbf7e6a161b8d7320e4ebc521cd00e58e1b79d/plugins/azure-sites-backend/src/service/router.ts#L76-L86

@afscrome I agree with you, we shouldn't overload the DB fetch, but again this approach will perform one more API call behind the scene. 

Also, it would be <ins>cleaner and more secure to get the PRs/Pipeline/Tags just passing by the `entityRef`<ins>

**Comment by awanlin** [comment]
Thanks for the feedback @afscrome, the performance hit is a valid concern, I would like to hear the maintainers thoughts on that 👍 

I think my over all issue is that we are passing around a lot of small bits either in the route or as query string parameters and it feels hard to track it all across the various features. The code is pretty settled but each time I or we make changes it means trying to remember all the history of why and how things work. Using the `entityRef` would help simplify things. But also, adding more tests could be the other way to help with my core concern.

**Comment by Rugvip** [comment]
I like it! 👍 (the original proposal). Deferring to an entity lookup in the backend is the most flexible and preferred (if advanced) approach. You may want to forward the `entityRef` all the way to the `AzureDevOpsApi` though since that'll let you do the entity lookup with a minimal number of `fields`. Performance concerns can be addressed by introducing a data loader or short-term cache, if needed.
