### ISSUE TITLE
🐛 Bug Report: Building a newer version of this documentation failed in Cloned Backstage Repo

### ISSUE THREAD

**Issue by cstahlhut** [backstage/backstage#22670]
### 📜 Description

Building a newer version of this documentation failed. Error: "Sorry! It took too long for the generated docs to show up in storage. Are you sure the docs project is generating an `index.html` file? Otherwise, check back later."

### 👍 Expected behavior

After cloing the main backstage git repo I should be able to access techdocs

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/2452099/8189d3b8-1e04-4d7e-a2b1-3b8d3e54a20c)

### 👟 Reproduction steps

1. Cloned repo
2. Tried to open backstage techdocs

### 📃 Provide the context for the Bug.

Learn more about techdocs and look at how the backstage ones are setup.

### 🖥️ Your Environment

Windows 11 Home using WSL2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by cstahlhut** [comment]
The logs seemed to indicate a successful build

![image](https://github.com/backstage/backstage/assets/2452099/81ba95a5-d9e6-44b5-a709-8293086e6ceb)

**Comment by awanlin** [comment]
Hi @cstahlhut, this is working for me locally, but I've run into this before, I'll dive into it when I have a bit more time.

In the mean time, in the Backstage Demo site I have examples of both the CI/CD and local generation working: https://demo.backstage.io/docs?filters%5Buser%5D=all. The `backstage` entity uses CI/CD to generate the TechDocs where as the `backstage-demo` generates them locally. The code for that is here: https://github.com/backstage/demo and the CI/CD workflow is here: https://github.com/backstage/demo/blob/master/.github/workflows/techdocs.yml. This is he "magic" that allows us to have both methods in place: https://github.com/backstage/demo/blob/master/packages/backend/src/extensions/docsBuildStrategy.ts

Hope that helps?

**Comment by samhine** [comment]
@awanlin 

Did you ever get a chance to look into this in more detail? I'm currently running into the same issue, my docs generation is local but is stored in a GCS bucket - when a new version of the docs is loaded it throws and error message despite the build being ultimately successful.

Perhaps a premature timeout due to the communication delay with GCS?
