### ISSUE TITLE
Actions column in Entities of Backstage

### ISSUE THREAD

**Issue by Yashit-G** [backstage/backstage#22693]
### 📜 Description

Hi Everyone,
I wanted my backstage catalog section records to have actions column enabled where user can edit, view and star the entities

I read from the discord channel that one has to provide the type:'url' in the app-config.yaml file with the github repo
Even after doing that my actions button are not enabled,  but when I provide the default github url of backstage it works I dont understand the why the default one works and the given by me does not 

URL given by me: https://github.com/Navdeep-12/Backstage/blob/main/packages/catalog-model/examples/all.yaml
Default URL provided: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

My folder structure is the same as that in the default backstage repo that is I have all the targets in the all.yaml file 

Please tell If I m missing something in the URL or there is any other change that I need to make 
![image](https://github.com/backstage/backstage/assets/116294051/2e5202f7-30ed-46f6-9b72-31cbfcce7616)
 

### 👍 Expected behavior

The actions should be enabled like it is enabled in the demo backstage application:- https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all

![image](https://github.com/backstage/backstage/assets/116294051/59e39ec3-6ae8-4d71-9a91-1fcb25d873c3)

### 👎 Actual Behavior with Screenshots

The actions are not enabled like it is enabled in the demo backstage application. The url that I giving in the app-config.yaml file is this https://github.com/Navdeep-12/Backstage/blob/main/packages/catalog-model/examples/all.yaml

Screenshot given for how actions column look now 
![image](https://github.com/backstage/backstage/assets/116294051/77a662c0-b7a7-43b5-8ce8-ba3e9a12218c)

### 👟 Reproduction steps

1. Clone the repo of demo backstage application
2. Create your own custom entities and update all.yaml file
3. Create github authorisation in backstage
4. Onboard your updated repo to github
5. Provide the github url under typ:'url' in app-config.yaml file

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by deepan10** [comment]
@Yashit-G 
I could see the URL given in the description is in a private repo on GitHub. Do you have the proper token with rights used in the Backstage App?

Check the token access scope and authentication as mentioned in the docs https://backstage.io/docs/integrations/github/locations

**Comment by Yashit-G** [comment]
After reading your reply I made my repo public and it worked, the actions column got enabled

But my next question is after providing the token under the integrations key and keeping my repo private
will actions column behave the same way?

**Comment by deepan10** [comment]
@Yashit-G 
Yes, if you have the `token` with right scope for your `private repo` you will get the same behavior in Action column in Backstage Catalog view.
