### ISSUE TITLE
Always use lower case URLs

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#2269]
Is it just me or does CamelCase URLs also hurt your eyes? 😬 

![Screenshot 2020-09-03 at 15 31 08](https://user-images.githubusercontent.com/190856/92121616-c4f1a880-edfa-11ea-9c84-7688045cbef5.png)

## Solution

Change catalog URLs like:

http://localhost:3000/catalog/Component/searcher

to

http://localhost:3000/catalog/component/searcher

**Comment by freben** [comment]
This currently needs a tweak to the catalog backend to work out, since its API is case sensitive.

**Comment by freben** [comment]
This is related to #1947 , that wants to uniformly make kinds case insensitive in general.

**Comment by adamdmharvey** [comment]
I believe this has now been fixed. On my instance all URLs are lower, and if I try uppercase for the kind, it rewrites it lower, so I'm thinking work spun out of the linked RFC was done.  Thinking this good to close - @freben / @Rugvip ?

**Comment by OrkoHunter** [comment]
The URLs in TechDocs are still case-sensitive with kind :/
https://demo.backstage.io/docs/default/Component/backstage
