### ISSUE TITLE
How to register another component if done once?

### ISSUE THREAD

**Issue by Yashit-G** [backstage/backstage#22744]
### 🔖 Need

Hi Everyone 
When I give the URL path while registering an existing component 
For example - https://github.com/XX-XX-XX/Backstage/tree/main/packages/catalog-model/examples/components/
if catalog-info.yaml file not provided, it creates a new one and then on the last step after merging the code with the main branch
It creates the catalog-info.yaml file in any other place which I have not specified
In the above scenario where I wanted to create a catalog-info.yaml file inside the components folder

it created the file in here - https://github.com/XX-XX-XX/Backstage/tree/main/catalog-info.yaml

Can you please help me in understanding why this is happening?

### 🎉 Proposal

I want my catalog-info.yaml file to be created inside the components folder as I have provide the same path in the app-config.yaml 

Please help me in understanding the same that why I this is happening and if I want the file to be created under a certain folder what should I be doing?

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by benjdlambert** [comment]
Don't think that this is supported using the `catalog-import` plugin, I think that it only creates a `catalog-info.yaml` file at the root of the repository if there isn't one already existing.
