### ISSUE TITLE
🚀 Feature: JFrog artifactory as techdocs file storage provider

### ISSUE THREAD

**Issue by chicobento** [backstage/backstage#22766]
### 🔖 Feature description

Support for JFrog Artifactory as techdocs file storage provider

### 🎤 Context

In our company we have a solution similar to techdocs.
The documentation is built by our CI pipelines and the resulting html files are pushed to a JFrog Artifactory that our portal is capable of rendering.
It should be an easy migration to techdocs if we had the capacity to consume the built documentation from a JFrog Artifactory folder.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @chicobento, this sounds totally reasonable to me. Just want to highlight that this would be something that would need to be contributed from the Community. 👍

**Comment by chicobento** [comment]
Hi @awanlin , makes sense. I'll be looking internally for an opportunity to implement this and contribute back. Thank you.

**Comment by dfl-aeb** [comment]
@chicobento any news from your internal evaluation? we would also be interested in this topic :)

**Comment by chicobento** [comment]
hi @dfl-aeb , sorry for the late reply. We have decided to put this on hold as we started using another in-house backend for storing the docs, so we'll probably at some point create custom storage provider for this backend that doesn't make sense to be shared.
