### ISSUE TITLE
🐛 Bug Report: Missing information in the AWS Fargate via Flightcontrol documentation. 

### ISSUE THREAD

**Issue by rpigu-i** [backstage/backstage#22803]
### 📜 Description

The Backstage documentation provides steps on using Flightcontrol to deploy to AWS Fargate:

[AWS Fargate via Flightcontrol](https://backstage.io/docs/deployment/flightcontrol)

Using this methodology, Flightcontrol is integrated into GitHub and pulls in the Dockerfile to kick off the process of deploying to AWS. However, the issue with this approach is that you need to pre-build some artifacts (zip files) to copy into the image for deployment. You can see more here in the Backstage docs where the precursor to building the image is described :

[Building a Docker image](https://backstage.io/docs/deployment/docker)

This approach creates a bit of a conundrum. Flightcontrol kicks off the deployment based on a change to a file in the repo, or via a webhook and then pulls _directly_ from the repo. This means the build artifacts need to already be in place in the package directory `packages/backend/dist/`.

Based on this approach you'd need the zip files to be stored in GitHub as there is no way Flightcontrol can access a GitHub runner to grab the files directly based on the currently documentation/methodology provided by the Backstage docs. Flightcontrol also has no way at present of checking out the source code, running a build script (e.g. a sh file with the yarn commands) prior to creating the image.

The quick work around for this is to use a multi-stage build, as demonstrated here:

https://github.com/moduslabs/modus-backstage-tips-tricks/tree/master/Flightcontrol/packages/backend

### 👍 Expected behavior

The documentation should be updated to note you need a multistage build or some other mechanism for the Flightcontrol steps to work as written. 
![example_working](https://github.com/backstage/backstage/assets/8628078/51d1cc60-e46c-465c-ae7f-e7650276b91d)

### 👎 Actual Behavior with Screenshots

When following the existing documentation, the deployment in Flightcontrol will fail. This is due to the zip files not being present.

### 👟 Reproduction steps

Setup a Flightcontrol account at:

https://www.flightcontrol.dev/

Using the default Dockerfile in the repository, follow the steps located at:

https://backstage.io/docs/deployment/flightcontrol

When Flightcontrol attempts to deploy to AWS it will fail due to the zip files referenced in the Dockerfile missing:

```
# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
COPY --chown=node:node yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn install --frozen-lockfile --production --network-timeout 300000

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY --chown=node:node packages/backend/dist/bundle.tar.gz app-config*.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz
```

### 📃 Provide the context for the Bug.

This gap in documentation was found when attempting to follow the official deploy steps to setup Backstage in AWS Fargate

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@rpigu-i can you raise a PR with the suggested documentation changes 👍  sounds good!

**Comment by rpigu-i** [comment]
@benjdlambert Absolutely!

**Comment by rpigu-i** [comment]
PR can be found here: 

https://github.com/backstage/backstage/pull/22844

Thanks!

**Comment by benjdlambert** [comment]
Closing as this seems to be fixed in the PR that was merged. :tada:
