### ISSUE TITLE
🚀 Feature: Discover APIs by route or OpenAPI tags

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#22802]
### 🔖 Feature description

A custom search provider for Backstage which has the ability to index metadata from OpenAPI specs, specifically routes and tags, and possibly configuration support to index custom OpenAPI attributes as well.

### 🎤 Context

My company has hundreds of OpenAPI specs which are sometimes vaguely grouped by business domain, but it's not great and there are a lot of problems searching all our APIs exacerbated by [Conway's law](https://en.wikipedia.org/wiki/Conway%27s_law) (Our APIs are organized by how our internal company is organized, not by product functionality) which make it difficult to discover certain endpoints / functionality.

This lack of discovery means that in some cases, Team A may build an API endpoint that has very similar functionality to an existing endpoint that Team B already created, but the two teams are far enough from each other in a large organization that they don't talk to each other to work out the requirements and build a single better supported general purpose API.

There are also cases where a team may have started migrating API functionality from a legacy system into a new greenfield service, but they never fully shutdown the legacy system. If API endpoints across two API specs could be organized together in backstage (ie: grouped by tag), it could provide visibility into the fact that the legacy endpoint still exists and there is tech-debt that needs to be addressed to fully deprecate it.

### ✌️ Possible Implementation

A search provider would

1. iterate through registered OpenAPI spec entities in backstage
2. Parse out routes / tags from the JSON/YAML spec
3. Include this info as a searchable index
4. Possibly also store this info in a relational database to build a "catalog view" of API routes too

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sennyeya** [comment]
👋 , thanks for this! This is something that came up when I was implementing Backstage and has come up in various forms when I've chatted about search with different folks. I think there's 2 separate pieces to this,
1. API duplication awareness
2. API versioning/deprecation

## API Duplication Awareness
This is an interesting direction and something that came up when my org was thinking about Backstage. My primary concern here is that this sounds like we're throwing a bunch of autogenerated stuff at a bigger issue. 

As I've seen and as you describe, duplicated APIs happen and happen more frequently than we'd probably be ready to admit. Driving that number down through better discovery of existing APIs seems like a good direction, but my concern here is that there's really no standard for API documentation and in many cases route level documentation isn't super useful. For example, from the OpenAI docs, ([1](https://github.com/openai/openai-openapi/blob/master/openapi.yaml#L1250), [2](https://github.com/openai/openai-openapi/blob/master/openapi.yaml#L1310), [3](https://github.com/openai/openai-openapi/blob/master/openapi.yaml#L1379)). In my experience, I usually want a more contextual document with information about the entire API and requirements/etc and then the ability to drill into the API either in code or through a spec. I haven't yet found that contextual information to be in the spec. 

With that being said, that level of documentation is difficult to push teams to prioritize especially in the early days of an API. I would say maybe a better direction would be being able to search where ever your organization stores the design/requirement documents. In my case, I've mostly gotten lucky that people were documenting in the older wiki and _not_ in Google Docs/Quip. Being able to do a quick search and get cross-organizational requirements docs or design docs IMO seems much more powerful than API descriptions.

In the case of Google Docs and Quip, that's a massive endeavor to index all of your documents and may not be at all feasible. There may be a small value add to just be able to search through the existing OpenAPI specs, but I'm not totally convinced as I outlined above.

## API Deprecation
I think this fits more into #20209 as a way to indicate that an API is deprecated but has a newer version or a newer API to use. I can definitely see the use case for surfacing this more clearly on the entity page. I don't think I would approach this through a grouping by tag, but more as an API version. There's definitely naming conflicts and whatnot to be had but I'd like to avoid using tags in general for grouping or organizing information across multiple specs.

**Comment by bforbis** [comment]
Hi @sennyeya , thank you for your response! I'll try to address some of your points below. I'm still thinking through some of this stuff myself :)

# API Duplication

> My primary concern here is that this sounds like we're throwing a bunch of autogenerated stuff at a bigger issue.

Even if OpenAPI specs are generated using a code-first design approach, the content within those specs are controlled by annotations which developers make conscious decisions on how to use and developer organizations may decide to try to strive towards certain conventions / uniformity.

> there's really no standard for API documentation

This is true, I agree with this! One of the powerful things I can see backstage playing a role here is its ability to be a centralized and opinionated documentation tool while still leaving some flexibility to the backstage implementers to decide what conventions they want to follow. I am fully ready to admit that developers at my company are not all documenting things or using API specs in a standardized way right now.

However, as I've seen with other things we've already added into the catalog, backstage is like ripping the top off a box and peering inside. You may not like what you see initially, but that provides you the reasons to try to establish a convention for people to follow, strive towards better uniformity, and ultimately better discoverability and documentation quality.

> route level documentation isn't super useful

Not sure I'm on board with this take entirely. Yes, it's not going to have the fidelity you would want for great documentation much of the time, but it certainly will have content in it that is worth indexing for search. For better documentation, OpenAPI provides operation level [externalDocs](https://swagger.io/specification/#operation-object) keys which can describe how to use a particular API endpoint in greater detail. I'd also be interested to see how this could be leveraged more natively in backstage for a true developer portal experience. For example, a way for it to link out to a specific techdocs page which can go into API workflow level detail?

> I would say maybe a better direction would be being able to search where ever your organization stores the design/requirement documents.

I really appreciate the suggestion, but I am trying to find an opportunity to make backstage the one shop stop for this situation rather than pulling in yet-another-docs-tool. 

# API Deprecation

My org's problems with API duplication is what has led us to additionally needing to address a large future API deprecation problem. However, it's not so simple to just say versioning is the answer here, because in the case of duplicate APIs built in a hurry to meet deadlines, the second set of them often was not built in any sort of versioned manner that would indicate it is the "V2" of anything (think transition from legacy to greenfield, but without any initially clear plan to ever address deprecation of legacy). 

Perhaps maybe my situation is uniquely bad, but I would expect this to be a problem that other similarly large dev orgs might have needed to address before stricter API governance / management can be put in place.

So how do you reverse yourself out of a situation where you have this at a large scale (this is kind of a ridiculous example, but I'm trying to explain the point):

- **Legacy Monolith**: GET /v1/FizzBuzz/{id}
- **Some New Microservice (team a)**: Get /v1/FizzBuzzes/{id}
- **Some Other New Microservice (team b)** Get /v1/FizBuzes/{id}

In hindsight, you would never want to ever end up in this situation and proper domain driven design would have prevented this, but software at scale can get messy.

One thought I'd have where backstage can be that "top ripped off the box" tool, is if we could just get some good governance in place where we can "bless" a tag called a `FizzBuzz` which represents a specific important business concept (the "resource" in a RESTful API), and then go and have developers retroactively tag their APIs with these resources. A quality approach to this may even allow us to build some sort of OpenAPI linter / quality reporter that can contact owners who have not done this properly (eg: maybe there is a golden list of these tags which we decide are ones we would look out for).

If our endpoints are then tagged with this convention, API duplication becomes very easy to see in backstage because you no longer have to worry about full text search and tokenizers and all that, you can just simply use filters which are way more reliable and have a company wide inventory of API operations associated with them.

**Comment by aramissennyeydd** [comment]
(new account, same me as @sennyeya) Thanks for the detailed response! Spent a few days thinking about this, 

I think documentation would be a solid value add alone and I don't want to block that with wanting to add context on top. A pattern I've seen that I've appreciated has been documenting APIs at the system level with more context, that could be something we pull from for adding context after the initial indexing is complete.

On the API deprecation front, I think I misunderstood a bit of your request, were you thinking of presenting the OpenAPI tags on the Entity? If that's the case, that would be an easy add and useful I think too. We'd be able to use the existing catalog table + filters. You'd still need to drill down into the spec to view the routes, but it would allow searching to work. I think API routes as entities would be a larger conversation 😅 .

We'll want to design either solution with #20209 in mind.

**Comment by bforbis** [comment]
> were you thinking of presenting the OpenAPI tags on the Entity?
That would be one way to approach it, and I think would be pretty simple and useful too. But it does have its limitations because you can't organization-wide route enumeration with this.

> I think API routes as entities would be a larger conversation 😅 .

So this is for my idea of a "table view of routes", which is a solution for API route inventory / spreadsheet exports / etc.

For implementation of something like this, I wasn't necessarily thinking of API routes as **Entities**.  A presentation layer view like this could look similar to the backstage catalog (ie: a big table with pagination), but there isn't a requirement for the backend table structure to conform to the backstage entity spec. Perhaps this functionality is bundled as a separate backend plugin that connects a processor to the backstage catalog and slurps this route data into a separate postgres table, similar to what the linguist plugin does.

**Comment by aramissennyeydd** [comment]
Sorry for the late reply, if you want to drive this, I'd be happy to look at PRs or talk through implementation details. Otherwise, it's gonna be a while before I get to this.

**Comment by bforbis** [comment]
@aramissennyeydd thanks, I'm planning to look more into this sometime in the next couple months. I've got a lot of things going on now too, but wanted to kickoff the discussion ahead of time to gauge interest.

**Comment by bforbis** [comment]
Still working on this internally at my company, though it will be a while before we have something to share here.

**Comment by camilaibs** [comment]
Hi @bforbis 👋🏻, just checking in to see if you are still able to contribute 🙂

**Comment by bforbis** [comment]
Hello, yes I still intend to contribute but it is taking much longer to get approval for open sourcing our internal plugins than originally anticipated. I'll be on break for the rest of the summer, but will come back to this when I get back.
