### ISSUE TITLE
🚀 Feature: Allow further filtering when using `GetEntitiesByRefs`

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#22839]
### 🔖 Feature description

Apart from filtering with references, it should be possible to also add `EntityFilterQuery` to the `GetEntitiesByRefsRequest` to filter even more of the wanted entities. 

### 🎤 Context

I have a list of entity references but would like to filter some of those out based on annotation values. I could do it by getting the `compoundEntityRef` for each and make a massive filter query to `getEntities` but I don't think that's the best way to go. `getEntities` does not support filtering by reference as far as I am aware.

### ✌️ Possible Implementation

This should be quite straight-forward as the catalog-backend `service` already supports adding filters to the `entitiesCatalog.entitiesBatch` call

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
Yes, nulls in the return array should be fine. Didn't check how the filtering is implemented in the db layer, but I don't think adding support for this slows things down, especially as it's optional.

**Comment by vinzscam** [comment]
One way to solve this I've used in the past was:

```ts
      const entityRefs = ['component:default/a', ...otherentities];
      const response = await catalogApi.queryEntities({
        // ...otherfilters
        filter: {
          'metadata.name': entityRefs.map(e => parseEntityRef(e).name),
        },
        limit: 100
      });


      const entities = response.items
      .map(e =>
        stringifyEntityRef({
          kind: e.kind,
          namespace: e.metadata.namespace,
          name: e.metadata.name,
        }),
      )
      .filter(e => entityRefs.includes(e));
```

but yeah #22845 looks nicer!
