### ISSUE TITLE
🚀 Feature: enforce user auth in scaffolder actions

### ISSUE THREAD

**Issue by dariozachow** [backstage/backstage#22867]
### 🔖 Feature description

This feature adds the possibility to enforce the usage of user authentication tokens like github, azure, gitlab, etc. by an env variable/config variable.

### 🎤 Context

Initially I've created a similar issue (#22643) due to security issues with our token, and one solution to this problem, was this feature. Having this option makes the usage of the scaffolder more safe in case there is a high privilege token configured for backstage, so that no user can have access to that token.

### ✌️ Possible Implementation

A possible implementation would be, to add a config variable like `scaffolder.forceUserAuth` and check for this flag in every scaffolder action which requires authentication, like `fetch:*`, `gitlab:*`, `github:*`...
Future Pull requests need to be aware of this feature and must implement a check for this flag, so new contribution do not open the same security issue.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by darrenyung** [comment]
Hi there! Would something like this [doc](https://backstage.io/docs/features/software-templates/writing-templates/#using-the-users-oauth-token) help?

In theory, combining with [this](https://backstage.io/docs/features/software-templates/authorizing-parameters-steps-and-actions) , it should deny all non-auth users from executing scaffolder features that you wish to block.

**Comment by dariozachow** [comment]
Hi, thanks for your answer.

I forgot to state, that we don't have full control over templates and therefore cannot enforce the backstage:permission key in every Template. Thus having the problem that everybody can use the token provided in Backstage if the token parameter in the custom action is not set.

**Comment by darrenyung** [comment]
Hi @dariozachow ,

No problem. I think I get what you mean. Its understandable that backstage maintainers should not have governance nor be able to over user-designed templates. 

What I was suggesting is, like [here](https://backstage.io/docs/features/software-templates/writing-templates/#using-the-users-oauth-token). With [permissions framework](https://backstage.io/docs/features/software-templates/authorizing-parameters-steps-and-actions/#authorizing-actions), you could define certain scaffolder actions (i.e source control actions) to must have the {{token}} parameter defined in their inputs. 

Example:
```
if (isPermission(request.permission, actionExecutePermission)) {
      return createScaffolderActionConditionalDecision(request.permission, {
        allOf: [
          scaffolderActionConditions.hasActionId({
            actionId: 'publish:github:pull-request',
          }),
          scaffolderActionConditions.hasStringProperty({
            key: 'token',
          }),
        ]
      });
    }

    return {
      result: AuthorizeResult.ALLOW,
    };
```

Hope this helps.

**Comment by dariozachow** [comment]
@darrenyung 

this was exactly what I was looking for! Thanks for your reply.

**Comment by benjdlambert** [comment]
@dariozachow yeah I think that right now the best workaround is to use the permissions framework to validate there's tokens in the actions. It's not ideal, and of course we'd like to make it better, but it's something you can do now.

You could also deploy the scaffolder separately, and split that out into its own container with it's own config, which would essentially drop these tokens, but that's also right now a little bit of effort which we're actively working on making simpler.

**Comment by dariozachow** [comment]
@benjdlambert thanks for your reply, this workaround works for now, but I'm open for better solutions to this problem in the future 👍
