### ISSUE TITLE
Index for techdocs was not created

### ISSUE THREAD

**Issue by alejandroestarlichmartinez** [backstage/backstage#22871]
### 🔖 Need

The problem is when im trying to access to documents int aws, kubernetes deploy pod sends this warn:
{"documentType":"techdocs","level":"warn","message":"Index for techdocs was not created: indexer received 0 documents","plugin":"search","service":"backstage","type":"plugin"}

### 🎉 Proposal

I have a backstage instance with version 1.19.0, I am using the front and back plugin from techdocs according to the documentation connected to documentation repositories with a separate lifecycle.

These documentation repositories deploy to an AWS bucket where we have a techdocs directory, inside this directory we have several subdirectories with each of the builds of the different documentation repos.

When we deploy backstage, the logs show that it is well connected to the bucket:
{"level":"info","message":"Successfully connected to the AWS S3 bucket {bucket_name}","plugin":"techdocs","service":"backstage","type":"plugin"}
 and we have the index in each of the documentation repositories. However we have this warn and it shows the page empty, as if we have no docs.
{"documentType":"techdocs","level":"warn","message":"Index for techdocs was not created: indexer received 0 documents","plugin":"search","service":"backstage","type":"plugin"}:

Here is the techdocs config in app-config:
techdocs:
  builder: 'external' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'awsS3'
    awsS3: 
      bucketName: {bucket_name}
      bucketRootPath: 'techdocs'
      region: {region}
      credentials:
        roleArn: {role_arn}
  # publisher:
  #   type: 'awsS3' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by camilaibs** [comment]
Friendly pinging @backstage/techdocs-maintainers  🙂

**Comment by PeaWarrior** [comment]
Hey @alejandroestarlichmartinez - Have you gone through this part of the how-to to get TechDocs documents indexed?

https://backstage.io/docs/features/search/how-to-guides/#how-to-index-techdocs-documents
