### ISSUE TITLE
🚀 Feature: Kubernetes Actions CRUD of Resources

### ISSUE THREAD

**Issue by sspreitzer** [backstage/backstage#22886]
### 🔖 Feature description

You should add the capability to create, update and delete Kubernetes resources via eg. Template actions.

### 🎤 Context

In my use-case I would like to template [crossplane](https://crossplane.io) custom resources via Kubernetes and by this enable developers and end users to create any infrastructure resource.

### ✌️ Possible Implementation

Probably this could be implemented by the Kubernetes backend plugin as actions for templates.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jamieklassen** [comment]
Though I may not have the bandwidth to contribute it, I think this idea is pretty neat. [`@janus-idp/backstage-scaffolder-backend-module-kubernetes`](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/kubernetes-actions) is nice prior art, though it only supports the creation of namespaces and doesn't integrate with the kubernetes-backend plugin to do so.

**Comment by novellat** [comment]
Any development on this one? I wonder, how others typically handle that? Feels that managing k8s resources is potentially one of the key aspects on backstage.
