### ISSUE TITLE
Enable 2 Sonarqube Project keys per component

### ISSUE THREAD

**Issue by l-abdelrahman** [backstage/backstage#22880]
### 🔖 Need

We have some components that read 2 separate sonarqube project keys. The current setup only allows for 1 project key per component.

### 🎉 Proposal

Enable more than one project key view per component

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by camilaibs** [comment]
Is there anything you would like to suggest @backstage/sda-se-reviewers?
Is there any other plugin with similar needs that you would like to share as example?
