### ISSUE TITLE
🚀 Feature: Allow community translations

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#22895]
### 🔖 Feature description

To improve internalization (https://backstage.io/docs/plugins/internationalization/), Backstage should start taking community translations in use for different languages. One good option for tooling could be Transifex (https://explore.transifex.com/)

### 🎤 Context

The community could translate things for Backstage in Transifex where the translations would be imported and added as part of the release package.

### ✌️ Possible Implementation

1. Tooling needed to export all translations used in the project in English to Transifex
2. Tooling needed to import all translations from Transifex to release package

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
Something @awanlin might have a say to 💯

**Comment by awanlin** [comment]
Cool! I'm open to anything that will help move this forward. I do think our challenge right now is that most of the core and plugins don't even support i18n yet so we can't ask people or a service for translations until that's done. Does that make sense?

I know @mario-mui has some PRs open around this that would help on that front but it's been slow to get them reviewed and merged:

- https://github.com/backstage/backstage/pull/20932
- https://github.com/backstage/backstage/pull/20841

**Comment by camilaibs** [comment]
Had a sync with @backstage/maintainers, and they also recommend waiting for more plugins to support translation
Thanks for opening the issue @drodil and also @awanlin for the quick reply 🎉

**Comment by mario-mui** [comment]
new PR for catalog translations 
https://github.com/backstage/backstage/pull/23392

**Comment by drodil** [comment]
Not stale
