### ISSUE TITLE
🚀 If GitLab is utilized as an entity provider, it would be good to generate additional annotations for the entities.

### ISSUE THREAD

**Issue by markussiebert** [backstage/backstage#22903]
### 🔖 Feature description

To enhance the value of the Entities extracted from GitLab, it would be helpful to add additional information to them, such as project ID, to facilitate GitLab integrations on these components, and visibility to support role-based access control (RBAC) initiatives. Further information could also be included as needed to increase the usefulness of these Entities.

### 🎤 Context

We are trying to use Backstage alongside our self-hosted GitLab instance and we have noticed that a significant amount of information that is available in GitLab is missing in Backstage.

### ✌️ Possible Implementation

at the moment I have no Idea ... maybe someone can point me where it's possible to modify annotations of entities found by the gitlab entity provider - are there something like modifiers / transformers?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Hey, I just wanted to mention that there are already a number of [well known annotations](https://backstage.io/docs/features/software-catalog/well-known-annotations), and it wouldn't be crazy to add some more where useful. That page isn't exhaustive by the way - there are more annotations in frequent use than what's in there
