### ISSUE TITLE
🐛 Bug Report: Scaffolder Permissions Framework automatically denies actions that is not explicitly specified in policy

### ISSUE THREAD

**Issue by darrenyung** [backstage/backstage#22907]
### 📜 Description

I'm following up on the integration on an issue that I've raised [here](https://github.com/backstage/backstage/issues/21786). I have created a policy specifically for git related actions. It seems like it is now automatically rejecting other scaffolder actions such as **fetch:template** . 

### 👍 Expected behavior

It should only run the policy against the scaffolder actions that is explicitly specified while default to ALLOW all the others.

### 👎 Actual Behavior with Screenshots

Scaffolder Template run returns an error with permissions denied.

```
Error
NotAllowedError

Message
Unauthorized action: fetch:template. The action is not allowed. Input: {
  "url": "./output/custom-component",
  "values": {
    "name": "a",
    "owner": "group:default/1-team"
  }
}
```

### 👟 Reproduction steps

1. Design template with the following scaffolder actions. (fetch:template, publish:github:pull-request)
2. Create a permission policy with the following
```typescript
if (isPermission(request.permission, actionExecutePermission)) {
      return createScaffolderActionConditionalDecision(request.permission, {
        allOf: [
          scaffolderActionConditions.hasActionId({
            actionId: 'publish:github:pull-request',
          }),
          scaffolderActionConditions.hasStringProperty({
            key: 'token',
          }),
        ]
      });
    }

    return {
      result: AuthorizeResult.ALLOW,
    };
```
3. Run template and observe error

### 📃 Provide the context for the Bug.

As per other issue I've [raised](https://github.com/backstage/backstage/issues/21786). With the latest update, I wanted to re-test again with the permissions framework for user authentication when performing git related actions but I'm not sure why I'm getting other steps to have access denied. 

### 🖥️ Your Environment

OS:   Darwin 23.3.0 - darwin/x64
node: v20.11.0
yarn: 1.22.19
cli:  0.25.1 (installed)
backstage:  1.22.2

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.5.10
  @backstage/backend-common                                        0.19.9, 0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.6.9
  @backstage/backend-tasks                                         0.5.14
  @backstage/backend-test-utils                                    0.2.10
  @backstage/catalog-client                                        1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.24.0, 0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.11.2, 0.13.10
  @backstage/core-plugin-api                                       1.8.2
  @backstage/dev-utils                                             1.0.26
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.3
  @backstage/plugin-badges-backend                                 0.3.6
  @backstage/plugin-badges                                         0.2.53
  @backstage/plugin-bazaar-backend                                 0.3.7
  @backstage/plugin-bazaar                                         0.2.21
  @backstage/plugin-catalog-backend-module-github                  0.4.7
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.6
  @backstage/plugin-catalog-backend                                1.16.2
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog-unprocessed-entities                   0.1.7
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-cost-insights-common                           0.1.2
  @backstage/plugin-cost-insights                                  0.12.18
  @backstage/plugin-devtools-backend                               0.2.6
  @backstage/plugin-devtools-common                                0.1.8
  @backstage/plugin-devtools                                       0.1.8
  @backstage/plugin-entity-validation                              0.1.14
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.35
  @backstage/plugin-explore                                        0.4.15
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-github-issues                                  0.2.18
  @backstage/plugin-github-pull-requests-board                     0.1.23
  @backstage/plugin-home-react                                     0.1.7
  @backstage/plugin-home                                           0.6.1
  @backstage/plugin-kubernetes-backend                             0.14.1
  @backstage/plugin-kubernetes-common                              0.7.3
  @backstage/plugin-kubernetes-node                                0.1.3
  @backstage/plugin-kubernetes-react                               0.2.1
  @backstage/plugin-kubernetes                                     0.11.4
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-backend                             0.5.32
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.19
  @backstage/plugin-playlist-backend                               0.3.13
  @backstage/plugin-playlist-common                                0.1.14
  @backstage/plugin-playlist                                       0.2.3
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-elasticsearch            1.3.12
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-shortcuts                                      0.3.18
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.41
  @backstage/plugin-tech-insights-backend                          0.5.23
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.4.15
  @backstage/plugin-tech-insights                                  0.3.21
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-addons-test-utils                     1.0.26
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.4
  @backstage/plugin-techdocs-node                                  1.11.1
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-todo-backend                                   0.3.7
  @backstage/plugin-todo                                           0.2.33
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 2.20s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@vinzscam could you take a look at this?

**Comment by darrenyung** [comment]
Sorry, my bad! 🙏  I just had a look back at the issue I've raised. I didn't realized I need to add another condition to allow other steps as mentioned [here](https://github.com/backstage/backstage/issues/21786#issuecomment-1866879831).

I've added them and it works again. Apologies again for the false alarm!

**Comment by benjdlambert** [comment]
Thanks :tada:
