### ISSUE TITLE
🚀 Feature: scaffolder optionally passes request to action handler

### ISSUE THREAD

**Issue by mrfixij** [backstage/backstage#22900]
### 🔖 Feature description

Either through the context object, or as a separate argument, it should be possible to expose the request object from the express router in case there is a need for headers or request metadata.

### 🎤 Context

In my use case, I'm calling a microservice from a scaffolder action, and the security team has requested user request information as part of the required fields which is not available during the action, since the scaffolder only forwards req.params from the express router.  This has also been mentioned in the backstage discord's #scaffolder channel by another group on January 19 2024.

I've seen someone raise an issue that this is potentially a security smell, but I'm not well-versed enough in security to be able to comment one way or the other.

### ✌️ Possible Implementation

Approximate concept:
### scaffolder-backend/src/service/router.ts

```
// existing code:
const values = req.body.values

const template = await authorizeTemplate( 
  { kind, namespace, name }, 
  token, 
);

// proposed addition, kludgy, can definitely be improved
if (template.spec.EXPERIMENTAL_contains_request) {
  values.req = {...req} // potentially do some kind of destructuring to avoid exposing auth headers.
}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Hey :wave:

Thanks for raising this!

Yeah, I think unfortunately, it's a little bit of a security problem here for us to store request objects. They can contain sensitive credentials which we don't want to expose to actions without explicitly marking them as secrets.

What's the use case here? Do you just want to decorate `user-agent` headers on the request to the downstream service?

You have access to the `backstageToken` in the actions which contains some user information from who triggered the request too if you're wanting to pass that along?
