### ISSUE TITLE
[RFC] Status API

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#2292]
**Status:** Open for comments 

## Need

The Backstage Software Catalog can be extended by building plugins. These additional plugins help manage and visualise different parts of software development process. Examples include CI plugins that show the ongoing builds, a security plugin that shows security vulnerabilities detected in a component, a monitoring plugin showing the health of a service, etc. For the user to see the information provided by the plugin, they will need to navigate from Home (Software Catalog) -> A specific component -> Plugin.

There is a need to provide the user with at-a-glance information related to components in the catalog. Showing these kinds of "statuses" early in the user experience requires Backstage to keep track of this information centrally, as apposed to it being contained inside various plugins.

<img width="1242" alt="Screenshot 2020-09-05 at 11 40 28" src="https://user-images.githubusercontent.com/190856/92302470-b0cdb880-ef6c-11ea-9da0-a00125f193b9.png">

## Proposal

Introduce a high-level **Backstage Status API**  where underlying infrastructure systems can report (WRITE) status information, relating to a component, back to Backstage. Backstage stores this information centrally and makes it available (READ) for the Software Catalog and plugins to consume.

### API categories

The Status API is divided into a few standardised categories: 

* CI
* Deployment (delivery?)
* Health
* Quality
* Security
* Cost (maybe)

The goal of these categories is that they should be able to provide _high-level information_ to the user, while at the same time _be specific enough_ to fit into different kinds of underlying systems. 

### Example use-cases

* A post-merge CI process detects a flaky test and a `warning` is reported it through the _Quality API_.
* A critical security vulnerability is detected and `alarm` is reported through the _Security API_.
* Your new deployment is rolled out successfully and an `ok` is reported through the _Deployment API_.
* Your SLO error budget is used up and an `alarm` is reported through the _Health API_.
* One of your service dependencies is not responding and your monitoring system reports a `warning` through the _Health API_.
* An increased crash rate for your App is reported as a `warning` message through the _Health API_ (or deployment? 🤔).

### Envelope of a status message

```
type: 'ci' | 'deployment' | 'health' | ...;
status: 'ok' | 'warning' | 'alarm';
message: string;
critical?: 'yes' | 'no';
url?: string;
```

### Handling conflicting messages

The `status` type is used to sort by severity.

## Alternatives

Keep information contained inside the respective plugins.

## Risks

This adds complexity to Backstage in a few ways:

* A wider API surface requires more work from plugin authors.
* Plugins need (?) a backend component.
* More complex to deploy and operate a Backstage instance.

**Comment by Rugvip** [comment]
Initial thought of standardized interfaces for this would be that we put it at two levels: catalog schema, and frontend API.

The catalog schema would basically just be extensions in the form of either annotations, or perhaps a separate `status` field that we can allow plugins to feed information to, e.g. 

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
spec:
  type: service
status:
  - type: ci
    status: alarm
    message: 'Master build is failing'
    critical: yes
    url: https://github.com/spotify/backstage/actions/runs/233966331
```

Obviously ^ would not be written by hand put populated through catalog processors :grin:

The frontend API would then build on that, but allow for frontend-only additions. Something like

```ts
type Status = {
  type: 'ci' | 'deployment' | 'health' | ...;
  status: 'ok' | 'warning' | 'alarm';
  message: string;
  critical?: boolean;
  url?: string;
}

type StatusApi {
  getEntityStatus(entity: Entity): Observable<Iterable<Status>>
}
```

With the above interface we can provide a default implementation that simply surfaces the status field from the underlying entity, but we also provide a way to hook in additional status sources in the app, along with realtime updates.

The status object itself is of course a tricky bit that we want to get right. Could do a collection of UI mockups for how to surface statuses, and then make sure we could support all of them :grin:

**Comment by dtuite** [comment]
The screenshot looks awesome. IMO some amazing Backstage power could be unlocked by this.

The main thought I have is that I would like to be able to create my own view into the catalog, with multiple columns each representing a status from a different plugin. For example, imagine I am on the security team, I might want to create a catalog table which shows the service name, the owner, the date it was last deployed, and the number of Snyk vulnerabilities, and then sort on the last two columns. This would give me a good basis for outreach into specific teams who have a lot of vulnerabilities. Or might show me services which are missing an active owner and thus are getting stale and accruing vulnerabilities.

This table building of course is a feature which can be built on top of the basic Status API.

**Comment by andrewthauer** [comment]
I agree with @dtuite. Having a status API which allows for a component to have any number of statuses (0..*) would be very useful. For instance a service might be `deployed` and `healthy`, but failing some custom verification check. It may also have a monitor alerts triggered (e.g. high latency).

**Comment by Rugvip** [comment]
@andrewthauer So I think we're aligned in supporting multiple different statuses. The discussions afaik is more about the presentation, and whether you aim to display all statuses at once, or just the one with the highest severity.

Personally I think it could be a stack of max some number of dots if you have multiple failing statues, with the highest severity one being showed in text. Then click or hover shows you details about every failing status.

**Comment by stefanalund** [comment]
I also imagine clicking into a specific component and going to its Overview page will show another card/widget (do we have a name for these?) with each status category listed individually. This would be a standard UI component similar to the current About card.

> This table building of course is a feature which can be built on top of the basic Status API.

@dtuite yes, I think the Status API should not add customisation options to the main Catalog table. Could definitely see a different view (or plugin) using the Status API to show a more holistic status grid though.

**Comment by Fox32** [comment]
Definitely on my list of most wanted features 😉

**Comment by freben** [comment]
I'll mention that as part of the catalog backend redesign, we're discussing whether to surface a `status` root field in entities. Not sure we'd want to build that out into a full "store any external status info" bag though. It could be the case that this kind of info lives better in a graphql integration layer

**Comment by freben** [comment]
Initial work on adding the status field is submitted, see above

**Comment by freben** [comment]
So the "read side" of this is now merged and about to be released as well. That is, entities can now contain a `status` root field that conveys the set of current statuses for the entity.

There's no "write side" in place for it, apart from the catalog's processing output landing there. So this issue is still relevant, if it should cover the ability to POST and/or processor-emit custom statuses.

**Comment by forrestwaters** [comment]
> There's no "write side" in place for it, apart from the catalog's processing output landing there. So this issue is still relevant, if it should cover the ability to POST and/or processor-emit custom statuses.

@freben are there any current patterns/examples of being able to write to an entity field outside of the typical processor ingestion flow? We are very interested in this but it's not clear to me where this would fit in in the current [entity lifecycle](https://backstage.io/docs/features/software-catalog/life-of-an-entity#key-concepts) .

**Comment by tekn0ir** [comment]
This would be a valuable addition to Backstage, and you don't need other input than custom processors or providers to write status information about each entity. Is there any news on when this can be included in a release?

**Comment by freben** [comment]
Sorry but it hasn't entered planning/design even at this point. We've had our focus on other parts of the system lately.

**Comment by efenner-cambia** [comment]
I think this is still a valuable feature to consider and should not be stale

**Comment by gandhiano** [comment]
I found this new issue/plugin contribution, which may be interesting to the readers of this closed issue: https://github.com/backstage/backstage/issues/21262

**Comment by efenner-cambia** [comment]
I think that plugin is looking at external services and this status API would be for monitoring internal service statuses
