### ISSUE TITLE
🐛 Bug Report:Illegal dependency: Module 'bitbucket-cloud-entity-provider' for plugin 'catalog' attempted to depend on extension point 'events' for plugin 'events'

### ISSUE THREAD

**Issue by davidfestal** [backstage/backstage#22932]
### 📜 Description

When trying to use the `bitbucket-cloud-entity-provider` with the new backend system, the following error prevents the system to start:
```
Illegal dependency: Module 'bitbucket-cloud-entity-provider' for plugin 'catalog' attempted to depend on extension point 'events' for plugin 'events'. Extension points can only be used within their plugin's scope.
```

### 👍 Expected behavior

The `bitbucket-cloud` catalog provider should initialize correctly. 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/686586/26c26a32-7bba-408c-8fea-8c9b187eb1aa)

### 👟 Reproduction steps

1 Add the lines:
```
backend.add(import('@backstage/plugin-catalog-backend-module-bitbucket-cloud/alpha'));
backend.add(import('@backstage/plugin-events-backend/alpha'));
```
in the `packages/backend-next/src/index.ts` file

2. Add the corresponding packages in the `packages/backend-next/package.json` file
3. run `yarn install again`
4. run `yarn start` in the `packages/backend-next` folder.
5. You should get the error.

### 📃 Provide the context for the Bug.

This bug seems to come from line 43 in the following code:

https://github.com/backstage/backstage/blob/10d67dd8395a422ca99cbef7536b9d14cbf6d131/plugins/catalog-backend-module-bitbucket-cloud/src/module/catalogModuleBitbucketCloudEntityProvider.ts#L37-L49

Maybe the event extension should be added by a distinct module ?

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by davidfestal** [comment]
cc @pjungermann

**Comment by davidfestal** [comment]
Should be simply remove the line 43 and events support for now, while waiting for RFC https://github.com/backstage/backstage/issues/22393 to be fully implemented by PR https://github.com/backstage/backstage/pull/22344 ?

**Comment by pjungermann** [comment]
@davidfestal yes, removing the vmevent support from the backend module plugin would have been a quick option to at least unblock the use without events.

As I hope that the resolution with events will make it into the next release, not sure if it still makes sense to invest into that.

**Comment by pjungermann** [comment]
@davidfestal As the changes were merged and released already, I assume that this issue could be closed, right?

**Comment by Rugvip** [comment]
Yep, closing as this should now be fixed
