### ISSUE TITLE
🐛 Bug Report: @rjsf/core or doc need an update?

### ISSUE THREAD

**Issue by rr-jino-jose** [backstage/backstage#22954]
### 📜 Description

hello i was going through this [doc](https://backstage.io/docs/features/software-templates/writing-custom-field-extensions/) and have created a custom extension

// customExtension.ts
```
import {scaffolderPlugin} from '@backstage/plugin-scaffolder';
import {createScaffolderFieldExtension} from '@backstage/plugin-scaffolder-react';
import { RewardsOrgField, CurrentUserField, rewardsOwnerValidation } from './RewardsOrgField';

export const OwnerExtension = scaffolderPlugin.provide(
    createScaffolderFieldExtension({
        name: 'OwnerExtension',
        component: RewardsOrgField,
        validation: rewardsOwnerValidation,
    }),
);
``` 

I see error like below which looks to be searching for FieldExtensionComponentProps but I have FieldProps. From doc it looks like its FieldProps. 

```
packages/app/src/components/scaffolder/CustomExtensions/CustomExtension.ts:17:9 - error TS2322: Type '({ onChange, rawErrors, formData, }: FieldProps<string>) => React.JSX.Element' is not assignable to type '(props: FieldExtensionComponentProps<any, { [key: string]: string | number | boolean | object | any[] | null; }>) => Element | null'.
  Types of parameters '__0' and 'props' are incompatible.
    Type 'FieldExtensionComponentProps<any, { [key: string]: string | number | boolean | object | any[] | null; }>' is not assignable to type 'FieldProps<string>'.
      The types of 'uiSchema['ui:field']' are incompatible between these types.
        Type 'string | Field<any, RJSFSchema, any> | undefined' is not assignable to type 'string | Field | undefined'.
          Type 'ComponentClass<FieldProps<any, RJSFSchema, any>, any>' is not assignable to type 'string | Field | undefined'.
            Type 'ComponentClass<FieldProps<any, RJSFSchema, any>, any>' is not assignable to type 'ComponentClass<FieldProps<any>, any>'.
              Types of property 'propTypes' are incompatible.
                Type 'WeakValidationMap<FieldProps<any, RJSFSchema, any>> | undefined' is not assignable to type 'WeakValidationMap<FieldProps<any>> | undefined'.
                  Type 'WeakValidationMap<FieldProps<any, RJSFSchema, any>>' is not assignable to type 'WeakValidationMap<FieldProps<any>>'.
                    Types of property 'uiSchema' are incompatible.
                      Type 'Validator<UiSchema<any, RJSFSchema, any> | null | undefined> | undefined' is not assignable to type 'Validator<UiSchema> | undefined'.
                        Type 'Validator<UiSchema<any, RJSFSchema, any> | null | undefined>' is not assignable to type 'Validator<UiSchema>'.
                          Type 'UiSchema<any, RJSFSchema, any> | null | undefined' is not assignable to type 'UiSchema'.
                            Type 'undefined' is not assignable to type 'UiSchema'.

17         component: RewardsOrgField,
           ~~~~~~~~~
```

I am using @rjsf/core version 

```
yarn info @rjsf/core version                                                                                                                 10:21:53 pm
yarn info v1.22.19
5.17.0
✨  Done in 0.34s.
```

Any help is appreciated. Thanks

### 👍 Expected behavior

should work as per doc with @rjsf/core

### 👎 Actual Behavior with Screenshots

<img width="897" alt="Screenshot 2024-02-14 at 10 50 09 PM" src="https://github.com/backstage/backstage/assets/103286934/f3284033-1a1e-4227-b30d-375152fecae1">

when I run `yarn tsc` it give the above error 

### 👟 Reproduction steps

try doc 

### 🖥️ Your Environment

yarn backstage-cli info                                                                                                                      10:46:25 pm
yarn run v1.22.19
$ /Users/jino.jose/rakuten/git/portal/node_modules/.bin/backstage-cli info
OS:   Darwin 22.6.0 - darwin/arm64
node: v18.19.0
yarn: 1.22.19
cli:  0.25.1 (installed)
backstage:  1.22.2

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.5.10
  @backstage/backend-common                                        0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.6.9
  @backstage/backend-tasks                                         0.5.14
  @backstage/catalog-client                                        1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.13.10
  @backstage/core-plugin-api                                       1.8.2
  @backstage/dev-utils                                             1.0.26
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.4.3
  @backstage/plugin-catalog-backend-module-github                  0.4.7
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend                                1.16.2
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-home-react                                     0.1.7
  @backstage/plugin-home                                           0.6.1
  @backstage/plugin-kubernetes-backend                             0.14.1
  @backstage/plugin-kubernetes-common                              0.7.3
  @backstage/plugin-kubernetes-node                                0.1.3
  @backstage/plugin-kubernetes-react                               0.2.1
  @backstage/plugin-kubernetes                                     0.11.4
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.19
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-node                                  1.11.1
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 0.76s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Hey @rr-jino-jose :wave:

Thanks for the issue report. Looks like we're missing some doc updates here, I think that the type you want to be using is this: https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/SecretInput/SecretInput.tsx#L22

If that works for you would you be happy opening up a PR and fixing the docs? :pray:

**Comment by rr-jino-jose** [comment]
hey yeah I will try this.

I also tried this way 
```
import {createScaffolderFieldExtension} from '@backstage/plugin-scaffolder-react';
```

And it looks to be taking it .. the issue i am facing now is for validation. I am bit confused on what type to use for validation. Let me share the sample code

```
# customExtension.ts

import {scaffolderPlugin} from '@backstage/plugin-scaffolder';
import {createScaffolderFieldExtension} from '@backstage/plugin-scaffolder-react';
import { RewardsOrgField, CurrentUserField, rewardsOwnerValidation } from './RewardsOrgField';

export const OwnerExtension = scaffolderPlugin.provide(
    createScaffolderFieldExtension({
        name: 'OwnerExtension',
        component: RewardsOrgField,
        validation: rewardsOwnerValidation,
    }),
);
```

From doc it was like this 

```
# RewardsOrgField
import {FieldProps, FieldValidation} from '@rjsf/core';
export const rewardsOwnerValidation = (
    value: string,
    validation: FieldValidation,
) => {
    if (!value) {
        validation.addError(
            'Must set both organization and team value',
        );
    }
};
```

wonder if you have any hint on what to use for validation? not sure if this is a good candiadate for replacement of fieldValidation ? `import { CustomFieldValidator } from '@backstage/plugin-scaffolder-react';`

**Comment by benjdlambert** [comment]
I think that should be changed to `@rjsf/utils` 👍 

https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/RepoUrlPicker/validation.ts#L17

**Comment by rr-jino-jose** [comment]
@benjdlambert I did raised a PR to update the fix worked for me

https://github.com/backstage/backstage/pull/23040

**Comment by benjdlambert** [comment]
@rr-jino-jose going to close this issue as the PR has been merged :tada: thanks!
