### ISSUE TITLE
Support for granular ACL when publishing techdoc to S3 endpoint

### ISSUE THREAD

**Issue by jonesbusy** [backstage/backstage#22979]
### 🔖 Feature description

Hi,

When publishing techdoc to S3 endpoint we need ACL `ListBucket` permission on the root bucket and not only to the published namespace. For example publishing via

```
techdocs-cli publish --publisher-type awsS3 --entity my-namespace/Component/my-component --awsEndpoint <endpoint> --awsS3ForcePathStyle --storage-name techdoc
```

We need 

```
{
 "Effect": "Allow",
 "Action": "s3:ListBucket",
 "Resource": "arn:aws:s3:::techdoc",
}
```

But I would like to set

```
{
 "Effect": "Allow",
 "Action": "s3:ListBucket",
 "Resource": "arn:aws:s3:::techdoc",
 "Condition": {
       "StringLike": {
          "s3:prefix": "my-namespace/*"
       }
 }
}
```

Where 'my-namespace' match the entity tripled that is being published.

Because of the separation of project we don't want those service account to list content at the root (even if it's just folder name)

Hope is clear enough.

I'm more than happy to submit a PR, but for the moment I'm not sure where to look

Thanks

### 🎤 Context

The use case  is that we are using different CI and teams/project to build the docs with each a separate service account / namespace to the S3 endpoint. We cannot grant each service account with `ListBucket` at the bucket root but only on the corresponding namespace/folder

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jonesbusy** [comment]
not stale

**Comment by Rugvip** [comment]
Do you have any suggestion on how we could surface this to users? It's probably some new CLI option right?

**Comment by jonesbusy** [comment]
Hi,

I didn't check the code, but I don't see why it's needed to list folder at the root level. Perhaps it's used only to verify the the bucket exists ?

I don't think any new parameter is necessary

**Comment by Rugvip** [comment]
If we can ship this without adding any new flags that's even better 👍. Not sure why the existing implementation works the way it does

**Comment by jonesbusy** [comment]
not stale

**Comment by kotowick** [comment]
Can anyone help post the right backstage config so that it pulls techdocs from an S3 repo in the same account? Backstage is in ECS and has enough permissions etc.

What I need is likely the right config in the app-config.yml file...

**Comment by darylgraham** [comment]
Under the hood, the `techdocs-cli publish` command is calling the AWS S3 sdk, so there won’t be much option to change how it works in a significant manner (imho). 

The reason it needs `s3:ListBucket` permission against the bucket itself is that the integration uses a `HeadBucket` call to establish that the bucket exists. [This call](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html) requires the `s3:ListBucket` permission.

@jonesbusy if you need to be able to provide segregation at the IAM level like this, I would suggest using a custom CI script to upload the docs to S3 within your permissions structure. As long as you use `techdocs-cli generate` to render the docs, the publish command is really just a sync of the local folder to the S3 bucket. I don’t believe it does anything special that can’t be achieved with the aws cli tools or a python script.

**Comment by darylgraham** [comment]
> Can anyone help post the right backstage config so that it pulls techdocs from an S3 repo in the same account? Backstage is in ECS and has enough permissions etc.
> 
> What I need is likely the right config in the app-config.yml file...

@kotowick This is my config:

```
# app-config.yaml
techdocs:
  builder: 'external'
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: ${TECHDOCS_S3_BUCKET}
      region: ${AWS_REGION}
      sse: AES256
```
And the policy statement on the ECS Task:
```
        {
            "Action": [
                "s3:GetBucket*",
                "s3:GetObject*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::<TECHDOCS_S3_BUCKET>",
                "arn:aws:s3:::<TECHDOCS_S3_BUCKET>/*"
            ],
            "Effect": "Allow"
        }
```

**Comment by jonesbusy** [comment]
> Under the hood, the `techdocs-cli publish` command is calling the AWS S3 sdk, so there won’t be much option to change how it works in a significant manner (imho).
> 
> The reason it needs `s3:ListBucket` permission against the bucket itself is that the integration uses a `HeadBucket` call to establish that the bucket exists. [This call](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html) requires the `s3:ListBucket` permission.
> 
> @jonesbusy if you need to be able to provide segregation at the IAM level like this, I would suggest using a custom CI script to upload the docs to S3 within your permissions structure. As long as you use `techdocs-cli generate` to render the docs, the publish command is really just a sync of the local folder to the S3 bucket. I don’t believe it does anything special that can’t be achieved with the aws cli tools or a python script.

Thanks for the details. I will try using the AWS CLI instead for the upload directly to the correct location
