### ISSUE TITLE
Kind and type form fields have wrong width for large screens

### ISSUE THREAD

**Issue by shubhangr** [backstage/backstage#22980]
### 📜 Description

In the following Backstage demo, the fields Kind and Type have shorter width compared to the rest for large screens. Can anyone confirm if its intended or if its a bug?

### 👍 Expected behavior

Either width of all fields expand to fill the space OR the width should be limited like type and kind

### 👎 Actual Behavior with Screenshots

Inconsistent behaviour for large screens
![Screenshot 2024-02-15 at 13 13 35](https://github.com/backstage/backstage/assets/42357333/914c4ea7-01a0-4931-b5f7-92f53e954278)

### 👟 Reproduction steps

Steps to reproduce:
- Open the link https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all
- Increase with of window more than 2500px (you need a large screen or use chrome dev tools)
- Notice that the width of other fields changes but not of kind and type.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by tudi2d** [comment]
Sure @dawitamene - feel free to go ahead with this!

**Comment by MdSadiqMd** [comment]
@camilaibs @tudi2d Hey, I'm Interested too to work on it can i go ahead with it

**Comment by awanlin** [comment]
Hi @MdSadiqMd and @waliamaheep, it was assigned to @dawitamene and they have a PR open for it. Appreciate your willing ness to help, feel free to check out the other issues as I'm sure there are other opportunities to help out! 🚀

**Comment by awanlin** [comment]
Sorry, @MdSadiqMd, you are right. Looks like @waliamaheep was the other to create a PR

**Comment by tudi2d** [comment]
oh sorry... that's not a cool move. I did close the first PR as a duplicate, eventhough the idea was right (went stale also before). Let's get @dawitamene's PR into a good state & merge it in.

**Comment by awanlin** [comment]
In the end neither of the PRs opened for this got merged, would be great to see this fixed though, feel like a great first issue for someone!

**Comment by MdSadiqMd** [comment]
I'm Interested in taking up this issue 
@awanlin would you please assign me this

**Comment by awanlin** [comment]
Sure @MdSadiqMd, I've assigned it to you 👍 

FYI @dawitamene just wanted to loop you in, your PR went stale and was closed

**Comment by MdSadiqMd** [comment]
please do only check [this](https://github.com/backstage/backstage/pull/24677) pull request other had some bug(I don't know why they occurred) that other commits of other users had also involved in my pull request 
and @awanlin a DCO check had failed in PR could you guide me to solve it or assign someone who can help me with it

**Comment by VamshiReddy02** [comment]
Hey @MdSadiqMd, thank you for your contribution. I have a question for you: Did you read the [CONTRIBUTING.md](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md) guide before raising the PR? Also, the reason other commits from different users are involved in your pull request is because you didn't create a separate `git branch` before making changes.

**Comment by MdSadiqMd** [comment]
Oh I am sorry about that can I Just make another PR

**Comment by moradebianchetti81** [comment]
hi, if this problem cannot be solved I would like to take it

**Comment by vinzscam** [comment]
> hi, if this problem cannot be solved I would like to take it

no need to ask, first green PR with proper changesets and DCO wins this issue 😄

**Comment by ismailmmd** [comment]
@vinzscam Create https://github.com/backstage/backstage/pull/25014 since this was a one-liner.
