### ISSUE TITLE
API calls return postgresql query string in browser

### ISSUE THREAD

**Issue by ana-c-stefan** [backstage/backstage#22982]
### 📜 Description

The backstage API returns the query string when we pass "%00" as filter. Is this a known issue?

**- api/catalog/entity-facets?facet=%00**
`{
"error": {
"name": "error",
"message": "select \"search\".\"original_value\" as \"value\", count(*) as \"count\" from \"search\" where \"search\".\"key\" = $1 and \"search\".\"original_value\" is not null group by \"search\".\"original_value\" - invalid byte sequence for encoding \"UTF8\": 0x00",
"length": 146,
"severity": "ERROR",
"code": "22021",
"where": "unnamed portal parameter $1",
"file": "mbutils.c",
"line": "1669",
"routine": "report_invalid_encoding"
},
"request": {
"method": "GET",
"url": "[/entity-facets?facet=%00](******/entity-facets?facet=%00)"
},
"response": {
"statusCode": 500
}
}`

**- /api/catalog/entities?filter=kind=%00&filter=kind=group**
`{
"error": {
"name": "error",
"message": "select \"final_entities\".* from \"final_entities\" where \"final_entities\".\"final_entity\" is not null and (((((\"final_entities\".\"entity_id\" in (select \"search\".\"entity_id\" from \"search\" where \"key\" = $1 and (\"value\" = $2)))))) or ((((\"final_entities\".\"entity_id\" in (select \"search\".\"entity_id\" from \"search\" where \"key\" = $3 and (\"value\" = $4))))))) order by \"final_entities\".\"entity_id\" asc - invalid byte sequence for encoding \"UTF8\": 0x00",
"length": 146,
"severity": "ERROR",
"code": "22021",
"where": "unnamed portal parameter $2",
"file": "mbutils.c",
"line": "1669",
"routine": "report_invalid_encoding"
},
"request": {
"method": "GET",
"url": "[/entities?filter=kind=%00&filter=kind=group](*****entities?filter=kind=%00&filter=kind=group)"
},
"response": {
"statusCode": 500
}
}`

### 👍 Expected behavior

It should just return not found. The error message should not contain sql statements.

### 👎 Actual Behavior with Screenshots

See description

### 👟 Reproduction steps

See description

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Thank you for opening the issue 🙌🏻  , adding a "help wanted" label.

**Comment by ana-c-stefan** [comment]
Hi @Rugvip 
Will we have this fix available on all version or we need to upgrade backstage?

**Comment by ana-c-stefan** [comment]
Nevermind, I saw it's available from 1.23.0, Thank you!
