### ISSUE TITLE
🚀 Feature: Add `--pattern` to `backstage-cli info` command

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#23002]
### 🔖 Feature description

It would be pretty handy to help diagnose issues with Backstage for those who create plugins outside the `@backstage` org to be able to include a `--pattern` to the `backstage-cli info` command. This would show all the current results from this command as well as any packages that match the pattern.

### 🎤 Context

For plugin authors like @roadie or @spotify or @janus-idp being able to do something like:

```
yarn backstage-cli info --pattern "@spotify/backstage*"
```

And the results would include the matched pattern as well as the Backstage details would make troubleshooting much easier.

### ✌️ Possible Implementation

There's some prior art for this in the `yarn backstage-cli version:bump` command as it supports a similar flag.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Makes sense to have something for this! 👍 

I'm thinking it could make sense to include all packages with a `"backstage"` field in their `package.json` by default? Just for safety it probably makes sense to exclude packages in the monorepo itself, perhaps unless an `--include-workspace` flag is provided or smth like that?

**Comment by awanlin** [comment]
I'd still like to see this feature and the possible solution that @Rugvip suggested would work fine. I'd work on this myself but I don't have the time. Happy to collaborate with someone! 🚀

**Comment by awanlin** [comment]
Oh, this will come in more handy now given that the `community-repo` is live and the NPM organization has changed for them. They won't get listed by this command any more.

**Comment by awanlin** [comment]
@Rugvip to a run at this and all we have is the lock file which won't have the package role:

https://github.com/backstage/backstage/blob/d57ebbca65fdfbd66b91bd3c8357d75ae1ecbee7/packages/cli/src/commands/info.ts#L49

Not sure the best way forward, digging into the Yarn packages is a bit of a rabbit hole. Any tips?

**Comment by Rugvip** [comment]
We'll need to resolve the actual `package.json`s within `node_modules`, for example like this: https://github.com/backstage/backstage/blob/d50f5f35f894e4b47d95889e3e73ee4a493f9f75/packages/cli/src/commands/versions/migrate.ts#L82-L86
