### ISSUE TITLE
🐛 Bug Report: TechDocs search missing from Catalog Docs tab

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#23004]
### 📜 Description

At some point the search bar has gone missing from the Catalog Docs tab 🤔 

Example Catalog Docs tab: https://demo.backstage.io/catalog/default/component/backstage-demo/docs
Docs view outside Catalog: https://demo.backstage.io/docs/default/component/backstage-demo

I believe this is caused by the `withSearch={false}` here:

https://github.com/backstage/backstage/blob/dcf9eb531e0ed0594809e6486656c156155328a2/plugins/techdocs/src/EntityPageDocs.tsx#L48

### 👍 Expected behavior

It should have the same search bar like the Docs view outside of the catalog: https://demo.backstage.io/docs/default/component/backstage-demo

### 👎 Actual Behavior with Screenshots

The search bar is missing in the Catalog Docs tab: https://demo.backstage.io/catalog/default/component/backstage-demo/docs

### 👟 Reproduction steps

1. Create a Backstage instance with: npx @backstage/create-app@latest
2. Setup TechDocs: https://backstage.io/docs/features/techdocs/getting-started
3. Got to an entity with TechDocs setup in the Catalog

**Notice:** there is no search bar on the Docs tab

### 📃 Provide the context for the Bug.

The search bar is handy to be able to quickly search for something in a longer document.

### 🖥️ Your Environment

```text
OS:   Darwin 23.3.0 - darwin/arm64
node: v18.18.2
yarn: 3.5.0
cli:  0.25.2-next.3 (installed)
backstage:  1.23.0-next.3

Dependencies:
  @backstage/app-defaults                                          1.5.0-next.3
  @backstage/backend-app-api                                       0.5.10, 0.5.11-next.3
  @backstage/backend-common                                        0.19.9, 0.20.1, 0.21.0-next.3
  @backstage/backend-defaults                                      0.2.10-next.3
  @backstage/backend-dev-utils                                     0.1.3, 0.1.4-next.0
  @backstage/backend-openapi-utils                                 0.1.3-next.3
  @backstage/backend-plugin-api                                    0.6.10-next.3, 0.6.9
  @backstage/backend-tasks                                         0.5.14, 0.5.15-next.3
  @backstage/catalog-client                                        1.5.2, 1.6.0-next.1
  @backstage/catalog-model                                         1.4.3, 1.4.4-next.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2, 0.2.3-next.0
  @backstage/cli                                                   0.25.2-next.3
  @backstage/config-loader                                         1.6.1, 1.6.2-next.0
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.12.0-next.1
  @backstage/core-compat-api                                       0.2.0-next.3
  @backstage/core-components                                       0.14.0-next.2
  @backstage/core-plugin-api                                       1.9.0-next.1
  @backstage/e2e-test-utils                                        0.1.1-next.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.5-next.0
  @backstage/frontend-plugin-api                                   0.6.0-next.3
  @backstage/integration-aws-node                                  0.1.8, 0.1.9-next.0
  @backstage/integration-react                                     1.1.24-next.2
  @backstage/integration                                           1.8.0, 1.9.0-next.1
  @backstage/plugin-api-docs                                       0.11.0-next.3
  @backstage/plugin-app-backend                                    0.3.58-next.3
  @backstage/plugin-app-node                                       0.1.10-next.3
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.2-next.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.0-next.2
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.4-next.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.7-next.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.7-next.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.7-next.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.5-next.3
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.7-next.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.2-next.3
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.0-next.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.3-next.3
  @backstage/plugin-auth-backend                                   0.21.0-next.3
  @backstage/plugin-auth-node                                      0.4.3, 0.4.4-next.3
  @backstage/plugin-badges-backend                                 0.3.7-next.3
  @backstage/plugin-badges                                         0.2.54-next.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.7-next.3
  @backstage/plugin-catalog-backend                                1.17.0-next.3
  @backstage/plugin-catalog-common                                 1.0.20, 1.0.21-next.0
  @backstage/plugin-catalog-graph                                  0.4.0-next.3
  @backstage/plugin-catalog-node                                   1.6.1, 1.6.2-next.3
  @backstage/plugin-catalog-react                                  1.10.0-next.3
  @backstage/plugin-catalog                                        1.17.0-next.3
  @backstage/plugin-cost-insights-common                           0.1.2
  @backstage/plugin-cost-insights                                  0.12.19-next.3
  @backstage/plugin-events-node                                    0.2.19-next.3
  @backstage/plugin-explore-backend                                0.0.20-next.3
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.36-next.1
  @backstage/plugin-explore                                        0.4.16-next.3
  @backstage/plugin-github-actions                                 0.6.11-next.3
  @backstage/plugin-graphiql                                       0.3.3-next.3
  @backstage/plugin-home-react                                     0.1.8-next.3
  @backstage/plugin-home                                           0.6.2-next.3
  @backstage/plugin-kubernetes-backend                             0.15.0-next.3
  @backstage/plugin-kubernetes-common                              0.7.4-next.2
  @backstage/plugin-kubernetes-node                                0.1.4-next.3
  @backstage/plugin-kubernetes-react                               0.3.0-next.3
  @backstage/plugin-kubernetes                                     0.11.5-next.3
  @backstage/plugin-org                                            0.6.20-next.3
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20, 0.7.21-next.3
  @backstage/plugin-permission-react                               0.4.20-next.1
  @backstage/plugin-proxy-backend                                  0.4.8-next.3
  @backstage/plugin-scaffolder-backend-module-azure                0.1.2-next.3
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.0-next.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.0-next.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.0-next.3
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.2-next.3
  @backstage/plugin-scaffolder-backend-module-github               0.2.0-next.3
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.13-next.3
  @backstage/plugin-scaffolder-backend                             1.21.0-next.3
  @backstage/plugin-scaffolder-common                              1.5.0-next.1
  @backstage/plugin-scaffolder-node                                0.3.0-next.3
  @backstage/plugin-scaffolder-react                               1.8.0-next.3
  @backstage/plugin-scaffolder                                     1.18.0-next.3
  @backstage/plugin-search-backend-module-catalog                  0.1.14-next.3
  @backstage/plugin-search-backend-module-explore                  0.1.14-next.3
  @backstage/plugin-search-backend-module-techdocs                 0.1.14-next.3
  @backstage/plugin-search-backend-node                            1.2.14-next.3
  @backstage/plugin-search-backend                                 1.5.0-next.3
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.6-next.3
  @backstage/plugin-search                                         1.4.6-next.3
  @backstage/plugin-tech-radar                                     0.6.13-next.3
  @backstage/plugin-techdocs-backend                               1.9.3-next.3
  @backstage/plugin-techdocs-node                                  1.11.2-next.3
  @backstage/plugin-techdocs-react                                 1.1.16-next.2
  @backstage/plugin-techdocs                                       1.10.0-next.3
  @backstage/plugin-todo-backend                                   0.3.8-next.3
  @backstage/plugin-todo                                           0.2.34-next.3
  @backstage/plugin-user-settings                                  0.8.1-next.3
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.6.0-next.3
  @backstage/theme                                                 0.5.1-next.1
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Related Discord thread: https://discord.com/channels/687207715902193673/1206955846836158494

**Comment by kuangp** [comment]
My assumption was that this was intentionally left out of the entity tab view since results in the search bar will link you to the full techdocs reader page (ie. navigates to the full page techdocs plugin pages) which leads to a UI confusion due to the context switch. Not sure if a workaround was ever implemented so that search result routing stays within the context of the entity tab parent route. Maybe @camilaibs can confirm here?

**Comment by awanlin** [comment]
Yes, what @kuangp said is correct, after removing the `withSearch={false}` here:

https://github.com/backstage/backstage/blob/dcf9eb531e0ed0594809e6486656c156155328a2/plugins/techdocs/src/EntityPageDocs.tsx#L48

Then trying out the Documented Component example, searching does bring me to the TechDocs view outside of the Catalog Entity view which is for sure a confusing context change. Looks like this is by design then but I'm wondering if this should be documented further? 🤔

**Comment by camilaibs** [comment]
Hi @kuangp and @awanlin, sorry for the late response, I haven't been working with TechDocs for a while now, but it seems that the search bar was hidden even before the introduction of the TechDocs add-ons as per [this](https://github.com/backstage/backstage/commit/ace749b785c61d96b570e6e64cc9be3b2617fa3b#diff-f383aa0cad31c9075aa5da9f96b6ced8f746edacb8b20a170370d184c817b83f) change. I think it was intentional not to show the search bar there. Let me ping @emmaindal to see if she remembers why.

**Comment by awanlin** [comment]
No worries @camilaibs, I actually did reach out to @emmaindal about this as well, and she wasn't sure, which is fair this was from two years ago ;)

The reality is that as @kuangp it's not a great UX/DX having it turned on. Now we can make it work or document this somehow. Not totally sure. I'll admit I was looking for an "easy button" on this one and though "oh, we can just make a prop" but it's a bit more than that now

**Comment by camilaibs** [comment]
It would be great to hear what @backstage/techdocs-maintainers think 🙂 .
One thing that came to mind is that the location used [here](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/search/components/TechDocsSearchResultListItem.tsx#L71) comes from the search results, so a solution could be modifying the location before passing it to the search result in case the component is rendered in the context of the entity page and adding a config so people can decide if they want to show the search bar or not (hand it over to the adopter to decide if the search bar on the docs tabs makes sense for them or not).

**Comment by camilaibs** [comment]
> I'm willing to put some time into this, if @kuangp's thoughts are the reasoning behind not showing the search. It makes much sense to me that searching in the docs _tab_ would redirect you to the /docs page being bad UI, and that being the reasoning.
> 
> 
> 
> I can look into redirecting the search results to the corresponding docs tab url's if search is performed in that context. It would be a similar UI as in the /docs pages.
> 
> 
> 
> @camilaibs would this approach work for you? I can start working on it if so.

It sounds a good approach to me, thank you in advance for the contribution 🙏. Let me just ping @backstage/techdocs-maintainers to hear their final recommendation 🙂

**Comment by byan1197** [comment]
Hey, just finished reading these comments and it sounds like the search bar + search result item modification would be a welcome addition in techdocs through the entity page! Thank you for looking into it 😄!
