### ISSUE TITLE
🐛 Bug Report: [1.23.0-next.3] errors in the console when using `createTheme` & `createUnifiedThemeFromV4`

### ISSUE THREAD

**Issue by mtlewis** [backstage/backstage#23014]
### 📜 Description

When using `createUnifiedThemeFromV4` with `createTheme`, it appears that some aspect of the default theme causes console errors. Appreciate `createTheme` is deprecated so fixing issues like this might be difficult to prioritize, but figured it would be useful to at least have it logged.

### 👍 Expected behavior

No errors should be produced in the console from the default theme options.

### 👎 Actual Behavior with Screenshots

The following error appears in the browser console:

```
createTheme.js:68 MUI: The `MuiTableSortLabel` component increases the CSS specificity of the `active` internal state.
You can not override it like this: 
{
  "root": {
    "color": "inherit",
    "&:hover": {
      "color": "inherit"
    },
    "&:focus": {
      "color": "inherit"
    }
  },
  "active": {
    "fontWeight": "bold",
    "color": "inherit"
  }
}

Instead, you need to use the '&.Mui-active' syntax:
{
  "root": {
    "&.Mui-active": {
      "fontWeight": "bold",
      "color": "inherit"
    }
  }
}

https://mui.com/r/state-classes-guide
```

### 👟 Reproduction steps

In the backstage example app:
1. Add a new minimal theme:
    ```typescript
    import {
      UnifiedThemeProvider,
      createTheme,
      createUnifiedThemeFromV4,
      palettes,
    } from '@backstage/theme';
    
    const theme = createUnifiedThemeFromV4(
      createTheme({
        palette: { ...palettes.light },
      }),
    );
    ```
2. Use the theme in createApp:
    ```typescript
    /* snip */
    themes: [
      {
        id: 'light',
        title: 'Light',
        variant: 'light',
        Provider: ({ children }) => (
          <UnifiedThemeProvider theme={theme} children={children} />
        ),
      },
    ],
    ```
3. Run `yarn dev`, the above error appears in the console.

### 📃 Provide the context for the Bug.

This issue occurred when upgrading from 1.23.0-next.2 to 1.23.0-next.3.

### 🖥️ Your Environment

OS:   Darwin 23.3.0 - darwin/arm64
node: v18.12.1
yarn: 3.2.3
cli:  0.25.2-next.3 (local)
backstage:  N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by tudi2d** [comment]
This is interesting. In the minimal example you are only adding a `palette`, but the error is comming from `overrides`. For the default `v5` theme this override istommorrowapplied correctly https://github.com/backstage/backstage/blob/master/packages/theme/src/v5/defaultComponentThemes.ts#L143-L146. It might be the case that this PR (https://github.com/backstage/backstage/pull/22793), which will be released tomorrow fixes this. 

Would you be up with testing this with tomorrow's next release to see if it fixes it? I would be interested in this!:)
