### ISSUE TITLE
🐛 Bug Report: Proxy settings on localhost using passport-microsoft

### ISSUE THREAD

**Issue by hghtwr** [backstage/backstage#23018]
### 📜 Description

Honestly, I'm not sure if this a bug or a feature request, so feel free to tell me :) 

I did set up Azure EntraID integration and I noticed that it failed with the error `Login failed; caused by Error: Authentication failed, failed to fetch user profile` when I tried to run it on my localhost. 

After some debugging, it seems like ```passport-microsoft``` is the culprit as it doesn't respect the local proxy settings. 
Everything started to work once I added the proxy settings manually in the libs.

I don't know what's the strategy for this project. Just tell me if I'd rather should open an issue in that particular project but I think it's good for transparency to have an issue here anyways as I assume I can't be the only one facing this.

### 👍 Expected behavior

After following the documentation about Azure OIDC and adopting the login page, you should be able to log in using MS Azure when running your application on localhost.

### 👎 Actual Behavior with Screenshots

It gives you an error message `Login failed; caused by Error: Authentication failed, failed to fetch user profile`
![image](https://github.com/backstage/backstage/assets/125581750/f2296c15-5ae1-4196-92b1-0ff7ded4cd4b)

As soon as I add the configuration for my local proxy to ```passport-microsoft/lib/strategy.js``` like this, it starts to work on my localhost: 
```
var HttpsProxyAgent = require('https-proxy-agent')
[...]

MicrosoftStrategy.prototype.userProfile = function (accessToken, done) {

    this._oauth2.setAgent(new HttpsProxyAgent(process.env['https_proxy'])) 
[...]
```

![image](https://github.com/backstage/backstage/assets/125581750/839b7e7d-209f-41a8-b8b4-bfda838cb414)

### 👟 Reproduction steps

I guess you need a company proxy setup...

### 📃 Provide the context for the Bug.

I assume it's necessary to either fix that npm package or to build some kind of wrapper that configures it correctly. 
I'm pretty new to Backstage but I'm willing to contribute to this issue.

### 🖥️ Your Environment

Localhost behind a company proxy.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hi @hghtwr 👋🏻 , here is a tutorial that might be useful to you:
https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md
