### ISSUE TITLE
🐛 Bug Report: While searching owner, the filtering criteria is not working on name of owner rather than it is taking metadata name

### ISSUE THREAD

**Issue by GV-SAAKETH** [backstage/backstage#23010]
### 📜 Description

While searching for an owner, the search option is not taking the owner of an cataloged entity to perform the search. Rather the name which in metadata of the cataloged entity is being taken to search that entity.

### 👍 Expected behavior

The search option should consider the owner name instead of metadata name

### 👎 Actual Behavior with Screenshots

The metadata name is being searched when we search for an owner tied to an entity

### 👟 Reproduction steps

Goto Backstage
Click on any 

### 📃 Provide the context for the Bug.

I would like to search owner of my entity based on the owner's name I gave it while creating. Right now it is not happening in that way. It is searching with the metadata owner name

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hi @GV-SAAKETH 👋🏻 , have you tried to set your own transformer in the collator?
Here is an example: https://backstage.io/docs/features/search/how-to-guides/#how-to-customize-fields-in-the-software-catalog-or-techdocs-index

**Comment by GV-SAAKETH** [comment]
Hey @camilaibs 
Thanks for your reply. I would confirm on this after a few checks from our end.
