### ISSUE TITLE
🐛 Bug Report: Atlassian Auth Provider Misconfiguration

### ISSUE THREAD

**Issue by rothenbergt** [backstage/backstage#23031]
### 📜 Description

The current authorization URL is constructed as `${baseUrl}/oauth/authorize`, which does not align with Atlassian's [expected path](https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/#1--direct-the-user-to-the-authorization-url-to-get-an-authorization-code). 

Additionally, the implementation might be missing the logic for resolving the user profile from the OAuth response.

### 👍 Expected behavior

The auth module should correctly construct the authorization URL without `/oauth/` in its path, adhering to Atlassian's official OAuth2 endpoint `https://auth.atlassian.com/authorize`. 

Upon successful authentication, the module should parse response to extract the user's profile information

### 👎 Actual Behavior with Screenshots

- When the pop-up window comes for the auth, we get a 404. 
- We can update the URL so the pop-up works. 
- Even when configured correctly, I can't get back any identity info from Atlassian callback. 

### 👟 Reproduction steps

1. Create Atlassian [OAuth app ](https://developer.atlassian.com/console/myapps/create-3lo-app)
2. Add the [Atlassian Authentication Provider](https://backstage.io/docs/auth/atlassian/provider/)
3. Attempt to authenticate thru Atlassian

### 📃 Provide the context for the Bug.

https://github.com/backstage/backstage/issues/19476

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Fixed by #23265
