### ISSUE TITLE
Add button to select all for each filter in filter table

### ISSUE THREAD

**Issue by kinnyk2** [backstage/backstage#23033]
### 🔖 Feature description

In filter table, there is 'CLEAR ALL' button for filters, it would be nice if we have a 'SELECT ALL' button for each filter option.

### 🎤 Context

In my use case, I want to select all in one of the filter option. It would be nice if there is a 'select all' button, so I don't need to check each one.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Friendly pinging @backstage/catalog-maintainers 🙂

**Comment by kinnyk2** [comment]
It's the table filter.

**Comment by freben** [comment]
@kinnyk2 there are many MANY tables throughout backstage and its many plugins. :) And several fonter concepts. Could you provide a screenshot and/or or a link on https://demo.backstage.io that show what you are referring to?

**Comment by kinnyk2** [comment]
I don't see the "CLEAR ALL" in the demo page. But if you refer to https://github.com/backstage/backstage/issues/12587, it's about the "CLEAR ALL" button to clear all currently set filters. It would be nice to have a button to select all filters as well.
Attached a screenshot to the table I saw and there's a "CLEAR ALL" button. Click on it will clear all set filters. I believe that table is using @backstage/core-components>TableFilter.
I'm new to backstage, sorry if I misunderstand anything.
![image](https://github.com/backstage/backstage/assets/131492782/a522413d-a520-48d3-9a98-3219d57aae8c)

**Comment by kinnyk2** [comment]
> Can I be assigned this?

Feel free, thanks for taking this.

**Comment by vinzscam** [comment]
but if you have a multiple select filter what do we do? Do we select all the options? I don't think it would make sense...
