### ISSUE TITLE
Gitea action to create a new repository wait till maxDuration is 20s

### ISSUE THREAD

**Issue by cmoulliard** [backstage/backstage#23049]
### 📜 Description

Gitea action to create a new repository blocks till the maxDuration is reaching the 20s even if the repository has been created.

the problem is due to a missing break within the while function when HTTP response is 200
See: https://github.com/backstage/backstage/blob/b4748b36eb875218ad7340ef19aa1f50bd83841b/plugins/scaffolder-backend-module-gitea/src/actions/gitea.ts#L178

```
  while (Date.now() - startTimestamp < maxDuration) {
    if (ctx.signal?.aborted) return;

    response = await checkGiteaContentUrl(integrationConfig, {
      owner,
      repo,
      defaultBranch,
    });

    if (response.status !== 200) {
      // Repository is not yet available/accessible ...
      await sleep(1000);
    }
  }
```

Should be
```
  while (Date.now() - startTimestamp < maxDuration) {
    if (ctx.signal?.aborted) return;

    response = await checkGiteaContentUrl(integrationConfig, {
      owner,
      repo,
      defaultBranch,
    });

    if (response.status !== 200) {
      // Repository is not yet available/accessible ...
      await sleep(1000);
    } else {
      break
   }
  }
```

### 👍 Expected behavior

The action should continue the process as soon as the gitea repository has been created

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-02-19 at 11 52 53](https://github.com/backstage/backstage/assets/463790/260ac344-46d6-4917-b4f0-74ff437628ce)

### 👟 Reproduction steps

N/A

### 📃 Provide the context for the Bug.

N/A

### 🖥️ Your Environment

yarn backstage-cli info
OS:   Darwin 22.6.0 - darwin/arm64
node: v20.11.0
yarn: 3.2.3
cli:  0.25.2-next.3 (local)
backstage:  N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tudi2d** [comment]
Closing this as the PR was merged - thanks for your contribution!
