### ISSUE TITLE
🐛 Bug Report: Extra scroll bars on TechDocs page

### ISSUE THREAD

**Issue by kmatyukhin** [backstage/backstage#23053]
### 📜 Description

When open TechDocs documentation I can see extra scroll bars on the left and right TOC blocks.

### 👍 Expected behavior

It shouldn't show scroll bars if content is not wrapped.

### 👎 Actual Behavior with Screenshots

![2024-02-19_13-19](https://github.com/backstage/backstage/assets/5629224/e8fd87ec-69b8-43ee-a0dd-d21565216634)

### 👟 Reproduction steps

Open documentation page on demo site
https://demo.backstage.io/docs/default/component/backstage

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @kmatyukhin, not sure, are these the same as https://github.com/backstage/backstage/issues/22745? They seem similar but maybe not exactly the same? 🤔

**Comment by kmatyukhin** [comment]
Seems so :)
I'm going to close this one in favor of the #22745.
