### ISSUE TITLE
🐛 Bug Report: Getting 200 even with an expired token

### ISSUE THREAD

**Issue by ana-c-stefan** [backstage/backstage#23078]
### 📜 Description

We are getting a 200 response even if the token is expired.

I see that auth-node token params are not having the exp claim:  https://backstage.io/docs/reference/plugin-auth-node.tokenparams/
Is this a known issue?

![image-20231026-061736](https://github.com/backstage/backstage/assets/7602567/f108ebf1-a35c-4d5f-bde1-e24604a7a17b)
![image-20231026-061716](https://github.com/backstage/backstage/assets/7602567/2f06bcc8-b7e0-4279-866f-02e899148b16)

### 👍 Expected behavior

see description

### 👎 Actual Behavior with Screenshots

see description

### 👟 Reproduction steps

see description

### 🖥️ Your Environment
**Our service is not using service to service auth**

yarn backstage-cli info

`OS:   Linux 5.15.133.1-microsoft-standard-WSL2 - linux/x64
node: v20.11.0
yarn: 1.22.19
cli:  0.25.1 (installed)
backstage:  1.22.0

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.4.0, 0.5.10
  @backstage/backend-common                                        0.15.2, 0.18.2, 0.19.4, 0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.4.0, 0.6.9
  @backstage/backend-tasks                                         0.4.3, 0.5.14
  @backstage/catalog-client                                        1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.13.10
  @backstage/core-plugin-api                                       1.8.2
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.3
  @backstage/plugin-bitbucket-cloud-common                         0.2.15
  @backstage/plugin-catalog-backend-module-azure                   0.1.28
  @backstage/plugin-catalog-backend-module-bitbucket-cloud         0.1.24
  @backstage/plugin-catalog-backend-module-github                  0.4.7
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.16
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend                                1.16.2
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.19
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.41
  @backstage/plugin-tech-insights-backend                          0.5.23
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.4.15
  @backstage/plugin-tech-insights                                  0.3.21
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.4
  @backstage/plugin-techdocs-node                                  1.11.1
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ana-c-stefan** [comment]
Hi @camilamaia 
Could you please help with this one as well?
thanks

**Comment by awanlin** [comment]
Hi @ana-c-stefan, pretty sure this is a known bug that never got logged. 

It would be really helpful to properly fill in the details in the issue though. People will search and find this but not be able to tell if they have done the same steps and setup. Can you please include the output from `yarn backstage-cli info` as part of the environment details. Can you also update the description to say if you setup service to service auth as per this: https://backstage.io/docs/auth/service-to-service-auth/ ?

**Comment by ana-c-stefan** [comment]
Hi @awanlin 
Thanks, I updated what you requested.
And you're right, If I call an api endpoint in postman, it responds even without a token. Is this then an issue bigger than what we thought?
How can we fix this?

**Comment by awanlin** [comment]
This is the current design, it's always important to read over the documentation, this would be helpful to read: https://backstage.io/docs/overview/threat-model. Now there is work being done to change this to be more secure by default, you can track that work here: https://github.com/backstage/backstage/tree/master/beps/0003-auth-architecture-evolution

**Comment by Rugvip** [comment]
Gonna close this. We have now shipped improvements to auth across the 1.24 to 1.26 releases that adds a default auth policy to Backstage backends which blocks unauthenticated requests.
