### ISSUE TITLE
🐛 Bug Report: Search does not return totalNumberOfItems with permissions

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#23086]
### 📜 Description

If permissions are enabled, the search does not return totalNumberOfItems for the frontend. The proposal is to change the documentation so that the `numberOfItems` is approximate of the total found items.

### 👍 Expected behavior

It should return at least an educated guess of how many items are found

### 👎 Actual Behavior with Screenshots

It returns undefined

### 👟 Reproduction steps

1. Enable permissions
2. Search for catalog items

### 📃 Provide the context for the Bug.

https://github.com/backstage/backstage/blob/b018060fe133cc1916786b71564a458f99ea5d73/plugins/search-backend/src/service/AuthorizedSearchEngine.ts#L208

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
And this is with the postgres backed search?

**Comment by drodil** [comment]
Alternatively the search engine could return approximate number of results. For example ElasticSearch can return an approximation of results in some cases. Currently the implementation does not check the `relation` field from the implementation even when not using permissions. Proposal is to add a new approximate number of results to the SearchApi response which is used by the authorized search engine as well as elastic engine. See #23091 for implementation details
