### ISSUE TITLE
🚀 Feature: Add a `--branch` flag to the `versions:bump` command in the `backstage-cli`

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#23080]
### 🔖 Feature description

It would be pretty awesome if there was a `--branch` flag added to the `backstage-cli versions:bump` command. This flag would create a branch with the release name as the branch name and commit the `version:bump` changes to it.

### 🎤 Context

Upgrading Backstage can be seen as time consuming but it's really not if you stay up to date. Being able to automate this process using this new `--branch` flag would help with this as you could easily run the command as part of a CI/CD workflow.  We do this for the Demo site here: https://github.com/backstage/demo/blob/master/.github/workflows/version-bump.yml

### ✌️ Possible Implementation

Much of what we do for the Demo site could be ported over to code: https://github.com/backstage/demo/blob/master/.github/workflows/version-bump.yml

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Eh, I feel this is a bit of a slippery slope we don't want to step on 😅. The amount of scripting you need to implement this with `git` commands is fairly low after all, so I'm not sure this provides enough value compared to the maintenance burden we'd be taking on to manage these git commands.
