### ISSUE TITLE
🚀 Feature: Scaffolder Clean Up

### ISSUE THREAD

**Issue by jpdeburgo** [backstage/backstage#23104]
### 🔖 Feature description

You should add a way to clean up the resources that are created by the scaffolder if one of the steps fails and is unable to run through successfully.

### 🎤 Context

My organization uses the scaffolder to create GitHub repos, various Azure resources, and Kubernetes deployments, among many other things. Sometimes, one of the steps fails. When this happens the user has to go to all the resources that were created by the scaffolder and delete them manually before attempting to rerun the scaffolder with all of the same input values.

### ✌️ Possible Implementation

- Keep track of all the tasks that were run successfully 
     - I believe this is already being done with the `TaskManager`
- Make a "catch" or "onFail" function for each built-in action 
     - It may be easier to make users implement these if they want this capability since there are a bunch of built-in actions
- Give custom actions the ability to have a "catch" or "onFail" function
- When an action fails, go through all of the completed actions and run the "catch" or "onFail" function
     - The "catch" or "onFail" function can be optional, so it will only run if it is there
     - Or there can be a value passed into the template that will run these "catch" or "onFail" functions when a task fails 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jpdeburgo** [comment]
> Would some of this be covered by BEP 0004: https://github.com/backstage/backstage/tree/master/beps/0004-scaffolder-task-idempotency?

Yes. Some cases would be covered, but there are other cases when it would not be covered. I think it would depend on what caused the action to fail. If the action failed because of a bug in the template, user input, or some other reason that will cause the action to fail every time then BEP 0004 would not cover it. I think that this should be added to BEP 0004, though. I think it would make sense to try to rerun a failed action a certain number of times and if it never runs successfully then it should run the cleanup functions for each action.

**Comment by Lucas-Desouza** [comment]
> Would some of this be covered by BEP 0004: https://github.com/backstage/backstage/tree/master/beps/0004-scaffolder-task-idempotency?

Possibly but not exactly. The issue we are running into is users running into issues during a few steps in then having issues running the template again later after resolving the issues. For example: the first step in a template creates a repo then it fails a few steps in because the team had some invalid parameters or some other issue. If the user resolves that and attempts to use the template it fails on the first step because the repo already exists. 

I would think an implementation where actions have a process to clean themselves up, like a create and destroy, would allow templates to be more transactional.  

BEP 0004 could cover this although it will really depend on the action.

**Comment by awanlin** [comment]
Thanks @jpdeburgo @Lucas-Desouza this is good feedback. I have no strong opinions but mostly wanted to share the BEP as it's a new process and I wasn't sure if you had seen it yet 👍 

FYI @benjdlambert @acierto not sure where this might fit into your plans 👀

**Comment by acierto** [comment]
Hey guys, we will discuss it together and come up with a shared vision if clean up should be a part of beps-0004 or not. 
The request is pretty sane though.

@Lucas-Desouza Regarding this one

> Possibly but not exactly. The issue we are running into is users running into issues during a few steps in then having issues running the template again later after resolving the issues. For example: the first step in a template creates a repo then it fails a few steps in because the team had some invalid parameters or some other issue. If the user resolves that and attempts to use the template it fails on the first step because the repo already exists.

It is already covered in BEP, the steps which were succeeded won't be executed again https://github.com/backstage/backstage/tree/master/beps/0004-scaffolder-task-idempotency#checkpoints That's the whole point to make task actions idempotent so that it is possible to rerun them multiple times

**Comment by blfrie** [comment]
We've been looking into this as well.  We just had an issue where a user was running the scaffolder and we pushed a deployment.  This left the workflow in an inconsistent state.  

We've read through BEP 0004 and can see a resolution for our use case if that is implemented.  Is anyone else making progress on that proposal?  Sounds like maybe @acierto ?

@wss-rbunning

**Comment by Alok650** [comment]
I think having a mechanism where we can provide a rollback action should solve. This rollback block can be optional like output. In the rollback block, we can provide a custom action which could be triggered if the stage fails.

This would help in case of resource deletion of previous stage / alerting in case the run fails.

**Comment by Lucas-Desouza** [comment]
> It is already covered in BEP, the steps which were succeeded won't be executed again https://github.com/backstage/backstage/tree/master/beps/0004-scaffolder-task-idempotency#checkpoints That's the whole point to make task actions idempotent so that it is possible to rerun them multiple times

Yeah I guess the only thing that wouldn't be covered is cleaning up junk if the action fails. Assuming you will retry its covered. 

Your other update about the undoAction does covered that second case.
