### ISSUE TITLE
🐛 Bug Report: Backstage 1.23.0 returns empty `providerInfo` when calling `/awsalb/refresh` endpoint

### ISSUE THREAD

**Issue by zcmander** [backstage/backstage#23117]
### 📜 Description

After upgrading to Backstage 1.23 from 1.22 we noticed that `providerInfo` object is empty:

```json
{
 "backstageIdentity": { ... }
 "profile": { ... }
 "providerInfo": {}
}
```

### 👍 Expected behavior

Earlier versions returned an object with `expiresAt` and `token` properties like this:

```json
{
 "backstageIdentity": { ... }
 "profile": { ... }
 "providerInfo": {
  "accessToken": "ey....",
  "expiresAt": 1234567
 }
}
```

### 👎 Actual Behavior with Screenshots

-

### 👟 Reproduction steps

I'm not sure if this relates to auth backend in general or just aws alb backend.

### 📃 Provide the context for the Bug.

That causes some issues as we no longer can detect when session is about to timeout.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by zcmander** [comment]
My best guess is that this relates to the change that refactors AWS ALB implementation:
https://github.com/backstage/backstage/commit/23a98f83cdfdc9bdff1e61865fc6172b500c828e#diff-fa51f4254a42fe68f32b1d2630bd48a8a5bfc66aa242f02975858001f7b08a87R28

**Comment by zcmander** [comment]
Well, I'm not entirely sure if that is done on purpose. By passing access token down to client might be a security risk in some cases (?) but that's the expected behaviour in our case and that's how it did work for AWS ALB before the latest version. I can try to open a PR for this but that's my main concern right now :)

**Comment by zcmander** [comment]
Thanks @drodil for the PR! I was about to investigate a similar solution myself :)

**Comment by benjdlambert** [comment]
Just merged a bonus release PR for this - should be out sometime in the next few hours :)
