### ISSUE TITLE
🐛 Bug Report: Reading Backstage Configurations from TechRadar "MyClient.ts"

### ISSUE THREAD

**Issue by iamdempa** [backstage/backstage#23126]
### 📜 Description

I have setup TechRadar plugin as mentioned in the docs here: https://github.com/backstage/backstage/tree/master/plugins/tech-radar

And According to the above documentation, I have to create a Class Components (`/app/src/lib/MyClient.ts`) as below:

```
// app/src/lib/MyClient.ts
. . . 
export class MyOwnClient implements TechRadarApi {
  async load(id: string | undefined): Promise<TechRadarLoaderResponse> {
    // if needed id prop can be used to fetch the correct data

    const data = await fetch('https://mydata.json').then(res => res.json());

    // For example, this converts the timeline dates into date objects
    return {
      ...data,
      entries: data.entries.map(entry => ({
        ...entry,
        timeline: entry.timeline.map(timeline => ({
          ...timeline,
          date: new Date(timeline.date),
        })),
      })),
    };
  }
}

// app/src/apis.ts
import { MyOwnClient } from './lib/MyClient';
import { techRadarApiRef } from '@backstage/plugin-tech-radar';

export const apis: AnyApiFactory[] = [
  createApiFactory(techRadarApiRef, new MyOwnClient()),
];
```

And I am trying to use Hooks for reading Backend configurations from here: https://backstage.io/docs/conf/reading

The problem is, since this is a class component, Hooks cannot be used as below:

```
const config = useApi(configApiRef);
```

### 👍 Expected behavior

Able to read backend config from the `/app/src/lib/MyClient.ts`

### 👎 Actual Behavior with Screenshots

N/A

### 👟 Reproduction steps

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
closing as answered in https://github.com/backstage/backstage/issues/661#issuecomment-1956571128
