### ISSUE TITLE
🐛 Bug Report: kubernetes plugin doesn't work for EKS on a different AWS account

### ISSUE THREAD

**Issue by aberenshtein** [backstage/backstage#23134]
### 📜 Description

I have backstage setup locally (for debugging) and I'm authenticated to Account A.
I want to get data about resources in EKS in account B.

This is my app_config:
`kubernetes:
  serviceLocatorMethod:
    type: 'singleTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: 'https://<eks-api-endpoint-in-account-b>'
          name: 'eks-clsuter-name-in-account-b'
          authProvider: 'aws'
          caData: "CA-from-eks-in-account-b"
          authMetadata:
            kubernetes.io/x-k8s-aws-id: "eks-clsuter-name-in-account-b"
            kubernetes.io/aws-assume-role: "arn of IAM role that has access to eks cluster in account B"`

Unfortunately, I get `error: UNAUTHORIZED_ERROR, status code: 401`        

I checked the source code and noticed that you use https://github.com/kubernetes-sigs/aws-iam-authenticator so I wanted to reproduce the issue.
To debug, I ran ` aws-iam-authenticator token -i <eks-cluster-in-account-b> -r <iam-role-arn-inaccount-b>`
and copied the token and then made the same request the plugin does
`
curl --location 'https://<eks-api-endpoint-in-account-b>/api/v1/namespaces/<namespace-in-eks-in-account-b>/pods' \
--header 'Authorization: Bearer <generated token>'
` and got a 200 response with the correct data.

So as far as I understand, the problem is not with my local setup

### 👍 Expected behavior

Display data about the entity in the kuberentes tab

### 👎 Actual Behavior with Screenshots

`error: UNAUTHORIZED_ERROR, status code: 401`
![Screenshot 2024-02-21 at 15 12 57](https://github.com/backstage/backstage/assets/12783883/30f9613a-3da3-4567-bd02-49f1b94d72be)

### 👟 Reproduction steps

Try to connect to a eks cluster in account B (different than your current account) with a IAM role from account B

### 📃 Provide the context for the Bug.

Also, I think there's a typo in the docs.
https://backstage.io/docs/features/kubernetes/authentication#aws
There's no key called `roleName` in `mainAccount` (only in accounts)

### 🖥️ Your Environment

`OS:   Darwin 22.6.0 - darwin/arm64
node: v18.19.0
yarn: 1.22.21
cli:  0.25.1 (installed)
backstage:  1.22.0

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.5.10
  @backstage/backend-common                                        0.19.9, 0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.6.9
  @backstage/backend-tasks                                         0.5.14
  @backstage/catalog-client                                        1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.13.10
  @backstage/core-plugin-api                                       1.8.2
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.4.3
  @backstage/plugin-catalog-backend-module-aws                     0.3.3
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.6
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend                                1.16.1
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-kubernetes-backend                             0.14.1
  @backstage/plugin-kubernetes-common                              0.7.3
  @backstage/plugin-kubernetes-node                                0.1.3
  @backstage/plugin-kubernetes-react                               0.2.1
  @backstage/plugin-kubernetes                                     0.11.4
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.19
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.4
  @backstage/plugin-techdocs-node                                  1.11.1
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by stijnbrouwers** [comment]
@aberenshtein Is the IAM role running backstage allowed to assume the role on account B?

**Comment by aberenshtein** [comment]
yes, it's the same IAM role I use locally

**Comment by stijnbrouwers** [comment]
I had the same issue, after trying multiple things it got resolved but I am not sure which one did it...
- I updated the packages ([npx backstage-cli versions:bump](https://backstage.io/docs/getting-started/keeping-backstage-updated/))
- I tried defining clusters through catalog instead of config:
```
kubernetes:
  serviceLocatorMethod:
    type: 'singleTenant'
  clusterLocatorMethods:
    - type: 'catalog'
```
&
```
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xxx
  annotations:
    kubernetes.io/api-server: 'https://xxx.xxx.xxx.eks.amazonaws.com'
    kubernetes.io/api-server-certificate-authority: "xxx"
    kubernetes.io/auth-provider: 'aws'
    kubernetes.io/aws-assume-role: 'arn:aws:iam::xxx:role/xxx'
spec:
  type: kubernetes-cluster
  owner: xxx
```
But beware, during the last action I faced a different issue (#23121 ) that I tried to resolve (See #23137 )

**Comment by aberenshtein** [comment]
Thanks @stijnbrouwers !!
[npx backstage-cli versions:bump](https://backstage.io/docs/getting-started/keeping-backstage-updated/) did the trick for me.
Still using with `clusterLocatorMethods: config` though
