### ISSUE TITLE
🚀 Feature: git release manager support for self hosted gitlab

### ISSUE THREAD

**Issue by nia-potato** [backstage/backstage#23162]
### 🔖 Feature description

it currently only supports github, can we add support for self hosted instances of gitlab for this plugin? 

### 🎤 Context

same as above

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by tudi2d** [comment]
Thanks @nia-potato - we are not actively working on the git release manager, but welcome contributions on it. If you are interested into contributing GitLab support feel free to pick it up.
