### ISSUE TITLE
🚀 Feature: support event hook

### ISSUE THREAD

**Issue by blackholll** [backstage/backstage#23195]
### 🔖 Feature description

my requirement is send email to somebody after component created via template.
I can write a custom action to send email.  but it need I add the custom action in all template. is there any other  way to realize my requirement?
such as component creation event hook? template's pre-step, post-step?

### 🎤 Context

component creation event hook or template's pre-step, post-step is very useful for integration with other system

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey :wave: thanks for raising this!

I want to try and get a few more use cases for hooks before committing to trying to introduce hooks. I'm thinking that this work relates pretty closely to the ongoing notifications work, specifically this BEP: https://github.com/backstage/backstage/tree/master/beps/0001-notifications-system although the external notifications system isn't in scope yet, like emails and slack etc.

But thinking that it would be something we would get for free if we were to integrate with the notifications backend to send notifications that scaffolder jobs + tasks have been completed.

**Comment by Rugvip** [comment]
What could make sense in both the short and long term would be to publish events via the `EventsService` when certain points in the scaffolder tasks are reached, along with metadata about the task. That'd make it possible to subscribe to those events already today for custom implementations, and in the future we'd likely make it possible to hook those events up to the notifications backend as well.
