### ISSUE TITLE
💬 RFC: ${{ values.name }} to @@values.name@@ it's posible ?

### ISSUE THREAD

**Issue by astounds** [backstage/backstage#23193]
### 🔖 Need

Hey guys ! thx you awesome tools !!! 
I have a question, how can I change value interpolation from ${{ values.name }} to @@values.name@@ to do replace in the templates, it's possible ?

### 🎉 Proposal

For now, it's an informative question.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by benjdlambert** [comment]
Hey @astounds :wave:

Unfortunately, this isn't possible, and I don't think that we will ever want to make this configurable.

It introduces complexity that the template language isn't going to be standard in both the `template.yaml` or in the skeletons themselves for `fetch:template`. What's the use case, why do you want to change them, and specifically why `@@` for beginning and end tokens?

If we lock this down and make it standard, theres better support for us to create migrations of templating syntax as we're also looking at moving away from nunjucks in future versions.
