### ISSUE TITLE
🚀 Feature: UserDocs

### ISSUE THREAD

**Issue by cope** [backstage/backstage#23201]
### 🔖 Feature description

Same as TechDocs but for User Documentation, to be delivered and available to users of the software.

### 🎤 Context

From https://www.archbee.com/blog/user-vs-technical-documentation

Technical documentation is geared towards developers and engineers, providing them with the technical information to understand the product's inner workings.

On the other hand, user documentation is created for end-users and provides clear and concise instructions on using the product effectively.

Understanding the differences between them is vital for delivering the right type of content to the right audience, ensuring the best possible experience.

### ✌️ Possible Implementation

Either extend TechDocs to handle multiple documentation types or create a separate identical plugin for UserDocs? I thinkn extending TechDocs might be a better idea.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by avila-m-6** [comment]
I think https://diataxis.fr/ should help by tailoring your techdocs content to match their guidelines

**Comment by tudi2d** [comment]
Thanks for raising this issue @cope! This is an interesting point. The goal of "TechDocs" as you mentioned is technical documentation, but I can't see why we wouldn't be able to handle this in theory. For technical documentation the benefit at the moment is that the documentation sits nex to the code. For user documentation this relationship between repository <-> documentation does not always hold. What we do at Spotify - e.g. for our [Golden Paths](https://engineering.atspotify.com/2020/08/how-we-use-golden-paths-to-solve-fragmentation-in-our-software-ecosystem/), which can be seen as user documentation aimed towards engineers - is to create seperate documentation repositories. They are totally isolated entities in the catalog with an own `catalog-info.yaml` & thereby also can have other owners than the code. 

Also something I want to mention is, that you can use a 3rd party documentation service & integrate it with Backstage. An example for this is the following https://github.com/K-Phoen/backstage-plugin-confluence. In the example this documenatin would be discoverable through Backstage. Alternatively you can also decorate an entity with metadata to link to an external service. It might be the easier, first step before fully building a new plugin.

**Comment by julian-alarcon** [comment]
> Thanks for raising this issue @cope! This is an interesting point. The goal of "TechDocs" as you mentioned is technical documentation, but I can't see why we wouldn't be able to handle this in theory. For technical documentation the benefit at the moment is that the documentation sits nex to the code. For user documentation this relationship between repository <-> documentation does not always hold. What we do at Spotify - e.g. for our [Golden Paths](https://engineering.atspotify.com/2020/08/how-we-use-golden-paths-to-solve-fragmentation-in-our-software-ecosystem/), which can be seen as user documentation aimed towards engineers - is to create seperate documentation repositories. They are totally isolated entities in the catalog with an own `catalog-info.yaml` & thereby also can have other owners than the code.
> 
> Also something I want to mention is, that you can use a 3rd party documentation service & integrate it with Backstage. An example for this is the following https://github.com/K-Phoen/backstage-plugin-confluence. In the example this documenatin would be discoverable through Backstage. Alternatively you can also decorate an entity with metadata to link to an external service. It might be the easier, first step before fully building a new plugin.
> 
> Looking for some @backstage/techdocs-maintainers opinions here as well - they might be able to give more elaborate advice! :)

This made me think about our documentation. Thanks!
