### ISSUE TITLE
🚀 Feature: Export `getOctokitOptions` from `scaffolder-backend-module-github`

### ISSUE THREAD

**Issue by RedlineTriad** [backstage/backstage#23211]
### 🔖 Feature description

Currently developers working on custom github scaffolder actions have to reimplement `getOctokitOptions` on their own.
https://github.com/backstage/backstage/blob/9406496cd7e718e0447c5897466954c9609ac7e7/plugins/scaffolder-backend-module-github/src/actions/helpers.ts#L42

### 🎤 Context

We use an "IssueOps" style of creating new GitHub repositories, and although there exists a builtin action for adding labels to issues, no action exists to actually create GitHub issues.
While developing my action I was basing it off of the label-issue action, however it used the `getOctokitOptions` which seems very convenient but is not exporter.

### ✌️ Possible Implementation

Export `getOctokitOptions` as a function of `scaffolder-backend-module-github`.

Alternative implementation:
Lift `scaffolder-backend-module-github` to a common module where it is exported from.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey @RedlineTriad :wave:

So long story short is that we used to export this from the `scaffolder-backend` package, but it just didn't feel right to have to maintain this export from there, so we encouraged people to duplicate it themselves.

That said, that decision was made before the `scaffolder-backend-module-github` package existed, so perhaps it could be exported from there instead now.

Do you want to whip up a PR and we can discuss more in there?

**Comment by RedlineTriad** [comment]
> Do you want to whip up a PR and we can discuss more in there?

Sure!

It's always nice to be able to contribute.

**Comment by benjdlambert** [comment]
Closing as completed :tada:
