### ISSUE TITLE
🐛 Bug Report: Hosting Backstage on AKS getting HTTP - HTTPS Discrepancy. 

### ISSUE THREAD

**Issue by owainow** [backstage/backstage#23247]
### 📜 Description

I am deploying Backstage on Azure Kubernetes Service. I am running into an issue where my application is attempting to load the backend modules using HTTPS. The start of the request chain is HTTP. When I run on localhost HTTP is used to make the calls. How do I force my application to use HTTP for these calls.

![image](https://github.com/backstage/backstage/assets/48108258/231b6819-79b7-4462-871c-d19560a17988)
 
The error seen in the console is "Failed to load resource: net::ERR_CONNECTION_TIMED_OUT".

It is worth adding that when using portforwarding outside of NGINX ingress controller from the same container that the application makes HTTP calls to the modules and loads successfully. I have used multiple ingress controllers with SSL rewriting etc with no luck. 

### 👍 Expected behavior

Make HTTP requests to the backend.

### 👎 Actual Behavior with Screenshots

HTTPS Calls from HTTP source. 

### 👟 Reproduction steps

Deploy created Backstage image.

### 🖥️ Your Environment

Azure Kubernetes Service V1.26&7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Hm could this be due to CSP? You could try to change it in your app-config:

```yaml
backend:
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    upgrade-insecure-requests: false
```

**Comment by gbranco** [comment]
Hey guys! I'm the exact same issue, @owainow did you figured out the solution?

**Comment by agifei53** [comment]
I have this issue, `upgrade-insecure-requests: false` did not help.

**Comment by tudi2d** [comment]
Just to get the full context: What is the app `baseUrl` & backend `baseUrl` in the `app-config` for this specific deployment? You don't have to share the exact URL, but at least if & what protocol is enforced.

**Comment by agifei53** [comment]
`http://localhost:7007`

**Comment by dirien** [comment]
Funny, I run into the same issue but using Oracle container instance.

**Comment by midan888** [comment]
> Hm could this be due to CSP? You could try to change it in your app-config:
> 
> ```yaml
> backend:
>   csp:
>     connect-src: ["'self'", 'http:', 'https:']
>     upgrade-insecure-requests: false
> ```

Worked for me

**Comment by nenkoru** [comment]
Tried to deploy a Helm chart@2.10 with backstage[1] and serve it using Ingress without TLS certs. 
What breaks this is this header `Strict-Transport-Security: max-age=time; includeSubDomains` which is returned when querying /. As described here[2] it essentially tells the browser to use https for other requests.

Should be reopened as this policy must not be enforced at the application layer, and is essentially a bug.

[1] https://artifacthub.io/packages/helm/backstage/backstage
[2] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

**Comment by grabnerandi** [comment]
Hi. I also just ran into this same issue and for me the fix was to add http to my img-src collection as by default it only had self and https. So - here is my final config that works

`        
connect-src: ["'self'", 'http:', 'https:']
img-src: ["'self'", 'http:', 'https:']
upgrade-insecure-requests: false
`

P.S: After changing that config you need to restart backstage as it reads the config during pod startup!

**Comment by Parms-d** [comment]
`  csp:
    connect-src: ["'self'", 'http:', 'https:']
    upgrade-insecure-requests: false`

This also worked for me :)
