### ISSUE TITLE
🐛 Bug Report: Broken AzureDevOpsEntityProvider ingestion with branch setting since 1.23

### ISSUE THREAD

**Issue by djflocko** [backstage/backstage#23248]
### 📜 Description

AzureDevOpsEntityProvider does not ingest (anymore) if a branch is defined in app-config.yaml

```yaml
catalog:
  providers:
    azureDevOps:
      yetAnotherProviderId: 
        organization: myorg
        project: '*'
        branch: development
        path: /catalog-info.yaml
```
Works somehow with 1.22. Works with default branch (or without branch setting).

### 👍 Expected behavior

Ingests entities from a AzureDevOps repo branch

### 👎 Actual Behavior with Screenshots

AzureDevops ingestion is skipped

### 👟 Reproduction steps

1. configure a branch app-config.yaml for catalog ingestion from AzureDevops
2. start app
3. ingestion for Azure DevOps always found 0 entities to ingest

### 🖥️ Your Environment

OS:   Darwin 23.3.0 - darwin/arm64
node: v20.11.0
yarn: 1.22.21
cli:  0.25.2 (installed)
backstage:  1.23.3

Dependencies:
  @backstage/app-defaults                                          1.5.0
  @backstage/backend-app-api                                       0.5.13
  @backstage/backend-common                                        0.19.9, 0.20.1, 0.21.2
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.5
  @backstage/backend-plugin-api                                    0.6.12
  @backstage/backend-tasks                                         0.5.17
  @backstage/catalog-client                                        1.6.0
  @backstage/catalog-model                                         1.4.4
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.3
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.6.2
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.12.0
  @backstage/core-compat-api                                       0.2.0
  @backstage/core-components                                       0.13.10, 0.14.0
  @backstage/core-plugin-api                                       1.9.0
  @backstage/dev-utils                                             1.0.27
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.5
  @backstage/frontend-plugin-api                                   0.6.0
  @backstage/integration-aws-node                                  0.1.9
  @backstage/integration-react                                     1.1.24
  @backstage/integration                                           1.9.0
  @backstage/plugin-api-docs                                       0.11.0
  @backstage/plugin-app-backend                                    0.3.60
  @backstage/plugin-app-node                                       0.1.12
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.4
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.7
  @backstage/plugin-auth-backend-module-github-provider            0.1.9
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.9
  @backstage/plugin-auth-backend-module-google-provider            0.1.9
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.7
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.9
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.5
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.2
  @backstage/plugin-auth-backend-module-okta-provider              0.0.5
  @backstage/plugin-auth-backend                                   0.21.2
  @backstage/plugin-auth-node                                      0.4.7
  @backstage/plugin-azure-devops-backend                           0.5.4
  @backstage/plugin-azure-devops-common                            0.3.2
  @backstage/plugin-azure-devops                                   0.3.12
  @backstage/plugin-catalog-backend-module-azure                   0.1.31
  @backstage/plugin-catalog-backend-module-github                  0.5.2
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.19
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.9
  @backstage/plugin-catalog-backend                                1.17.2
  @backstage/plugin-catalog-common                                 1.0.21
  @backstage/plugin-catalog-graph                                  0.4.0
  @backstage/plugin-catalog-import                                 0.10.6
  @backstage/plugin-catalog-node                                   1.7.2
  @backstage/plugin-catalog-react                                  1.10.0
  @backstage/plugin-catalog                                        1.17.0
  @backstage/plugin-devtools-backend                               0.2.9
  @backstage/plugin-devtools-common                                0.1.8
  @backstage/plugin-devtools                                       0.1.9
  @backstage/plugin-events-node                                    0.2.21
  @backstage/plugin-github-actions                                 0.6.11
  @backstage/plugin-github-issues                                  0.2.19
  @backstage/plugin-home-react                                     0.1.8
  @backstage/plugin-home                                           0.6.2
  @backstage/plugin-kubernetes-backend                             0.15.2
  @backstage/plugin-kubernetes-common                              0.7.4
  @backstage/plugin-kubernetes-node                                0.1.6
  @backstage/plugin-kubernetes-react                               0.3.0
  @backstage/plugin-kubernetes                                     0.11.5
  @backstage/plugin-org                                            0.6.20
  @backstage/plugin-permission-backend                             0.5.35
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.23
  @backstage/plugin-permission-react                               0.4.20
  @backstage/plugin-proxy-backend                                  0.4.10
  @backstage/plugin-scaffolder-backend-module-azure                0.1.4
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.2
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.2
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.2
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.4
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.2
  @backstage/plugin-scaffolder-backend-module-github               0.2.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.15
  @backstage/plugin-scaffolder-backend                             1.21.2
  @backstage/plugin-scaffolder-common                              1.5.0
  @backstage/plugin-scaffolder-node                                0.2.10, 0.3.2
  @backstage/plugin-scaffolder-react                               1.8.0
  @backstage/plugin-scaffolder                                     1.18.0
  @backstage/plugin-search-backend-module-catalog                  0.1.16
  @backstage/plugin-search-backend-module-pg                       0.5.21
  @backstage/plugin-search-backend-module-techdocs                 0.1.16
  @backstage/plugin-search-backend-node                            1.2.16
  @backstage/plugin-search-backend                                 1.5.2
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.6
  @backstage/plugin-search                                         1.4.6
  @backstage/plugin-tech-radar                                     0.6.13
  @backstage/plugin-techdocs-backend                               1.9.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.5
  @backstage/plugin-techdocs-node                                  1.11.4
  @backstage/plugin-techdocs-react                                 1.1.16
  @backstage/plugin-techdocs                                       1.10.0
  @backstage/plugin-user-settings                                  0.8.1
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.6.2
  @backstage/test-utils                                            1.5.0
  @backstage/theme                                                 0.5.1
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Phiph** [comment]
Hey @djflocko , will it work if you fully qualify the branch name? 

For example `refs/heads/development`

**Comment by Phiph** [comment]
Thanks - I'll be upgrading my instance to 1.23 this week so I'll try to take a look at it.

**Comment by djflocko** [comment]
> @djflocko Did you add the branch `development` as "Searchable Branch" in your Azure DevOps Repository setting? Ref: https://backstage.io/docs/integrations/azure/discovery#installation

@deepan10 I really hadn't set this, but unfortunately it has no effect. 
BTW: I use a location kind in the catalog-info.yaml to point to a target in the repo. Works for main but not here - not sure if that's related.

```yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: location-abc
  title: abc
  description: A collection of abc entities
spec:
  targets:
    - ./.backstage/components.yaml
    - ./.backstage/systems.yaml
```

**Comment by deepan10** [comment]
@djflocko 
Your `app-config.yaml` says you are fetching `catalog-info.yaml` from `developement` branch. And kept your location kind in `catalog-info-yaml` to add components. 

In this case, if you didn't set the searchable branch, Azure DevOps provider doesn't reach the `catalog-info.yaml` from your `developement` branch. 

And one more, do you have any rule configured in the catalog as mentioned below? 

https://github.com/backstage/backstage/blob/b9d9f4199fe005f1df83b6c03f1d11c9f162a4fd/app-config.yaml#L232-L244

**Comment by djflocko** [comment]
> @djflocko Your `app-config.yaml` says you are fetching `catalog-info.yaml` from `developement` branch. And kept your location kind in `catalog-info-yaml` to add components.
> 
> In this case, if you didn't set the searchable branch, Azure DevOps provider doesn't reach the `catalog-info.yaml` from your `developement` branch.
> 
> And one more, do you have any rule configured in the catalog as mentioned below?
> 
> https://github.com/backstage/backstage/blob/b9d9f4199fe005f1df83b6c03f1d11c9f162a4fd/app-config.yaml#L232-L244

I enabled the search option for the branch in ADO, but it had no effect (at least not within 20min - maybe I was too impatient ). Sure, I have the rules to allow these entity types.

**Comment by deepan10** [comment]
@djflocko Can your complete `app-config.yaml` and `catalog-info.yaml` I will try to replicate the same.
