### ISSUE TITLE
🐛 Bug Report: <title>Handle conclusion status as cancelled

### ISSUE THREAD

**Issue by codehubmanish** [backstage/backstage#23257]
### 📜 Description

There is an issue when we are fetching status of any workflow which is cancelled on github, as it is showing default status as Completed. Because there is a condition to check the conclusion as skipped || canceled with single l, but we are getting conclusion as cancelled with double l
https://github.com/backstage/backstage/blob/master/plugins/github-actions/src/components/WorkflowRunStatus/WorkflowRunStatus.tsx#L55

### 👍 Expected behavior

It should have one more value to check condition as case 'skipped' || 'canceled' || 'cancelled':

### 👎 Actual Behavior with Screenshots

It actually should consider conclusion status as cancelled also

### 👟 Reproduction steps

Try to fetch status of any cancelled github workflow

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
That sounds unfortunate. If you or anyone else has the ability to verify and make a fix PR for that, we'd be grateful 🙏

**Comment by codehubmanish** [comment]
Could anyone please help here, in testing and making the below change:
case 'completed':
      switch (conclusion?.toLocaleLowerCase('en-US')) {
        case 'skipped' || 'canceled' || 'cancelled':
          return 'Aborted';
        case 'timed_out':
          return 'Timed out';
        case 'failure':
          return 'Error';
        default:
          return 'Completed';
      }

**Comment by freben** [comment]
@codehubmanish `case` doesn't accept `||` expressions. You make multiple `case` statements instead with a single value each.

**Comment by karthikeyanjp** [comment]
Submitted PR #23365 .

Based on [this documentation](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-workflow), status can be `cancelled` and not `canceled`.  So, handled only `cancelled` conclusion code.

**Comment by codehubmanish** [comment]
Thanks @freben  and @karthikeyanjp for helping in fixing the issue, will test with 1.24 version upgrade.
Also, i noticed you forget to change the same in getStatusDescription() as this will, still be Completed

https://github.com/backstage/backstage/blob/master/plugins/github-actions/src/components/WorkflowRunStatus/WorkflowRunStatus.tsx#L86
