### ISSUE TITLE
🚀 Feature: Allow to customize HTTP timeout value used by OIDC auth providers

### ISSUE THREAD

**Issue by gusevda** [backstage/backstage#23267]
### 🔖 Feature description

Provide a possibility to configure HTTP options (timeout e.g.) used by OIDC auth provider when making requests to OIDC issuer.

### 🎤 Context

In my company we access kubernetes clusters by using custom OIDC auth providers. Sometimes it takes longer than 3500 ms for OIDC issuer to respond and we get timeout errors. It could happen during token/userinfo requests and during the initial metadata discovery request on app startup. We would like to be able to increase this setting.

<img width="466" alt="Screenshot 2024-02-26 at 19 16 39" src="https://github.com/backstage/backstage/assets/445309/89818575-7bc8-40ea-b67b-3cab86986113">

### ✌️ Possible Implementation

I am not sure what would be the correct way to provide custom options for OIDC auth providers. It would work for us if we could change HTTP timeout globally for all OIDC auth providers, but per provider configuration would also work.

There is a [documentation](https://github.com/panva/node-openid-client/blob/main/docs/README.md#customizing-http-requests) on how to customize default HTTP options for the `openid-client` library that is used by the `auth-backend-module-oidc-provider`.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Thank you for reporting! 👍 

Honestly I think we could bump the timeout to somewhere around 5-10s, 3.5 seems a bit tight. With that I'd prefer to skip adding a configuration value for it for now though, just to avoid doc bloat.
