### ISSUE TITLE
🚀 Feature: support http proxy

### ISSUE THREAD

**Issue by blackholll** [backstage/backstage#23276]
### 🔖 Feature description

in some companies, application need use http proxy to visit Internet site. but backstage does not support proxy which configured in env variable. 

### 🎤 Context

those situations need proxy:
- import template from github
- run 'yarn backstage-cli version:bump' to upgrade backstage

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Indeed, thanks for linking. I'll close this for now. The article has a little bit of rationale; the way proxying works in node is a bit special.
