### ISSUE TITLE
🚀 Feature: Moving away from `spotify/web-scripts`

### ISSUE THREAD

**Issue by tudi2d** [backstage/backstage#23277]
### 🔖 Feature description

Move away from the dependecy on `spotify/web-scripts` in the CLI & Microsite for Prettier & ESLint config.

### 🎤 Context

[`spotify/web-scripts`](https://github.com/spotify/web-scripts) is deprecated since December 2023. We depend on it for our Prettier config with `"@spotify/prettier-config"` in the Microsite. In the main workspace we depend on it for the Prettier config as well as using the ESLint Plugin with `"@spotify/eslint-plugin"`. 

Reminded about this by dependabot: https://github.com/backstage/backstage/pull/23259

### ✌️ Possible Implementation

**Prettier:** This should be straigthforward. The current dependency only exports the following config values ([source](https://github.com/spotify/web-scripts/blob/master/packages/prettier-config/index.js)): 
```js
module.exports = {
  singleQuote: true,
  trailingComma: 'all',
  arrowParens: 'avoid',
};
```
Let's check if this isn't enforced already & adjust the current configs if needed.

**ESLint Plugin:** I'm actually not sure if we need this at all. The plugins allows to discourage the use of certain words. Haven't looked into our configs, but if we haven't configured it with custom words it probably does not bring a benefit at the moment. For more context checkout [the code here](https://github.com/spotify/web-scripts/blob/master/packages/eslint-plugin/src/rules/best-practices/no-discouraged-words.ts).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by santoshyadavdev** [comment]
Hey team,

Let me know if I can work on this.

**Comment by tudi2d** [comment]
Awesome - feel free to raise a PR!:)

**Comment by santoshyadavdev** [comment]
@tudi2d just opened my first PR, sorry if I missed following some steps.
