### ISSUE TITLE
🐛 Bug Report: critical/high severity dependabot security issues in dependencies (in generated app)

### ISSUE THREAD

**Issue by gaurav517** [backstage/backstage#23272]
### 📜 Description

Dependabot reports several critical/high severity security issues in dependencies.

### 👍 Expected behavior

Critical/high severity security issues should not be present.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/15346341/56d06502-ded6-436e-871d-fcdc225fe1b1)

### 👟 Reproduction steps

Create a dependabot repot on generate app.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
As far as we can tell these are related to cli tooling and may not have an effect on your runtime risk levels.

I'll also note that we do expect users to use dependabot or similar to keep their installations secure. The versions picked up at creation time may not be the same ones as those that we have resolved to in the main repo at that point. The security landscape for these dependencies is a fast-moving target.

Do those issues have patch-level fixes out for them?

That being said, any help we can get in ensuring that the created apps have a record that is as clean as possible from the get-go.

**Comment by gaurav517** [comment]
> The versions picked up at creation time may not be the same ones as those that we have resolved to in the main repo at that point
We upgraded recently using https://backstage.github.io/upgrade-helper/. I was assuming that we would see the diff in generated code with that tool. That could help us in fixing them with upgrades.

> Do those issues have patch-level fixes out for them?
yes, those Dependabot gives patches to fix them (I haven't tested them yet).

**Comment by Rugvip** [comment]
Our threat model outlines the [integrator responsibilities](https://backstage.io/docs/overview/threat-model#integrator-responsibilities) in maintaining a Backstage installation, which includes keeping dependencies up to date.

Going to close this since this is the intended behavior.
