### ISSUE TITLE
🚀 Feature: Secure Base Image as part of `contrib/docker` Dockerfiles

### ISSUE THREAD

**Issue by karlhaworth** [backstage/backstage#23323]
## Description

Contribute to `contrib/docker` directory as an alternative Docker Base Image to reduce vulnerabilities.

I have created an alternative Dockerfile that reduces vulnerabilities based on [`wolfi-base`](https://github.com/wolfi-dev) to get the data below. The Dockerfile successfully runs the Backstage application and generated the techdocs locally in the container.

### Base Image Stats

|      | Official Backstage Image                                          | Wolfi-Base Image without Node                                  | Chainguard Node Image                                          | Devops Contrib Image                                            | Devops Contrib Image                                                      |
| ---- | ----------------------------------------------------------------- | -------------------------------------------------------------- | -------------------------------------------------------------- | --------------------------------------------------------------- | ------------------------------------------------------------------------- |
| CMD  | ❯ trivy image node:18-bookworm-slim                               | ❯ trivy image cgr.dev/chainguard/wolfi-base:latest             | ❯ trivy image cgr.dev/chainguard/node:latest-dev               | ❯ trivy image node:16-alpine                                    | ❯ trivy image node:16-buster                                              |
| OS   | Total: 75 (UNKNOWN: 0, LOW: 57, MEDIUM: 12, HIGH: 5, CRITICAL: 1) | Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0) | Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0) | Total: 10 (UNKNOWN: 0, LOW: 0, MEDIUM: 8, HIGH: 2, CRITICAL: 0) | Total: 1825 (UNKNOWN: 7, LOW: 1083, MEDIUM: 441, HIGH: 281, CRITICAL: 13) |
| Node | Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)    |                                                                |                                                                | Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 0, CRITICAL: 0)  | Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 0, CRITICAL: 0)            |

### Produced Image Stats
|        | Official Backstage Image                                              | Wolfi-Base Image                                               |
| ------ | --------------------------------------------------------------------- | -------------------------------------------------------------- |
| CMD    | ❯ trivy image example-backend:upstream                                | ❯ trivy image example-backend:wolfi-base                       |
| OS     | Total: 382 (UNKNOWN: 3, LOW: 227, MEDIUM: 114, HIGH: 37, CRITICAL: 1) | Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0) |
| Node   | Total: 8 (UNKNOWN: 0, LOW: 1, MEDIUM: 6, HIGH: 1, CRITICAL: 0)        | Total: 7 (UNKNOWN: 0, LOW: 1, MEDIUM: 5, HIGH: 1, CRITICAL: 0) |
| Python | Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 1, CRITICAL: 0)        | Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0) |

To obtain produced image stats, I ran `yarn docker-build` from the `master` branch that was freshly pulled.

### Contribution

To produce these results I did the following :
1. Duplicate `packages/backend/Dockerfile` -> `contrib/docker/secure-base-image/Dockerfile`
2. Updated Dockerfile `FROM` line to use Chainguard Wolfi-Base
3. Updated `apt` references to `apk` and replaced packages with relevant wolfi-base packages
4. Tested with `yarn build-docker`

### Notes

`wolfi-base` is designed for `glibc`, avoiding some of the issues we've seen in our environment when using `musl` based variants.

### Running Image

The techdocs generated just fine.

![image](https://github.com/backstage/backstage/assets/58607256/ff39c34d-bc1e-406e-9335-af65c8e0ede7)

### 🎤 Context

Secure Base Images -

Today the official base docker image used by Backstage along with the Dockerfiles in the `contrib` directory contain OS Vulnerabilities. Using standard images from Dockerhub in general does not seem to yield the best results to reduce vulnerabilities.

Internally we found Chainguard as an image supplier that focuses on secure base images by default with the right settings configured. For Backstage, Chainguard doesn't have an official image that supports Node and Python however we can use their [`wolfi-base`](https://github.com/wolfi-dev) image which ends up accomplishing the task with a lot less vulnerabilities. Chainguard releases the `latest` tag for the public and keeps other tags behind authentication.

Moving from the Backstage recommended image reduced the vulnerabilities by 100s. While not all vulnerabilities necessarily matter, reducing the noise helped quite a bit through the reduction of investigations and dismissing false positives.

### ✌️ Possible Implementation

Expected Outcome - A secure base image is available that reduces the vulnerabilities while being glibc compatible.

Possible Implementation - Add a Dockerfile utilizing image `cgr.dev/chainguard/wolfi-base:latest@sha256:3d6dece13cdb5546cd03b20e14f9af354bc1a56ab5a7b47dca3e6c1557211fcf`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @karlhaworth, the idea seems like a good one. I do have a question: how do you intend on keeping these up to date? Do you know if Renovate can be used to update these without a high amount of toil on the maintainers side?

I'm wondering if it would make more sense to add this as a suggestion to the docs instead? Perhaps a new section titled "Securing your Docker Image" here: https://backstage.io/docs/deployment/docker

**Comment by karlhaworth** [comment]
> how do you intend on keeping these up to date? Do you know if Renovate can be used to update these without a high amount of toil on the maintainers side?

We use Dependabot today to keep our docker image up to date. Renovatebot we also have experience with and it would also work just as well.

> I'm wondering if it would make more sense to add this as a suggestion to the docs instead? Perhaps a new section titled "Securing your Docker Image" here: https://backstage.io/docs/deployment/docker

I am open to it. I chose the `contrib/docker` folder since others already have Dockerfiles there. The Dockerfile differs enough from the upstream Dockerfile, so a simple docs section seemed like it might not work so well however the example could live there?

Please provide additional thoughts based on the above @awanlin. I already have a PR open for the Dockerfile contribution however happy to tweak it to whatever the community feels is best!

**Comment by awanlin** [comment]
Ok, was doing some digging and it seems we do have Renovate checking the files in this folder but we don't pin to the hash. 

Generally the contrib folder is a bit of a "use at your own risk" and the items that are in there aren't really well maintained. I'll be honest I'm not sure how well most of those Dockerfiles would work. I worry about this creating the false sense of security if they aren't being properly kept up to date. 

Yes, I saw the PR which is why I wanted to follow up here so that we can settle on the best path forward.

**Comment by karlhaworth** [comment]
> we don't pin to the hash.

The hash or image digest allows dependabot or renovatebot to know the exact image that is being used. `wolfi-base` uses `latest` which isn't that descriptive and `node:18-bookworm-slim` could also have many digests behind it. Using the image digest ensures dependabot/renovatebot/you know exactly what is deployed.

> contrib folder is a bit of a "use at your own risk"

This is somewhat at your own risk. It's not the general upstream supported Dockerfile?

> I worry about this creating the false sense of security if they aren't being properly kept up to date.

Sure. I could add a disclaimer if needed. I definitely don't want that.

> Perhaps a new section titled "Securing your Docker Image" here: https://backstage.io/docs/deployment/docker

So back to your original ask, do you think this is still best? Should I move the whole Dockerfile in the PR to the docs and mention the Dockerfile is an example and the digest needs to be watched by dependabot/renovatebot? Mention that the digest in the example is out of date and will need to be updated?

We could also point renovatebot in Backstage repo to this folder to ensure the digest is updated?

I am fine with any direction you prefer.

**Comment by awanlin** [comment]
Thanks for the follow up, I'm just waiting to get some feedback on the Maintainers side. 👍

**Comment by karlhaworth** [comment]
@vinzscam @freben thoughts on this?

**Comment by Rugvip** [comment]
Thank you for the suggestion, sounds good! 👍 

I'd suggests that we add a section in our [docker deployment docs](https://backstage.io/docs/deployment/docker) with a list of alternative base images, just to make it as visible as possible. I think it makes sense to have actual Dockerfiles live in `contrib` as you suggest, to highlight that they're maintained by the community and won't necessarily be updates if we update the main image.

+1 to @awanlin's concern, let's aim to not have any digests or versions that we need to bump frequently or at all, and instead document the procedure around those

**Comment by pjungermann** [comment]
@karlhaworth based on the issue description and trivy results, I wonder why not `chainguard/node` instead of `chainguard/wolfi-base` as both seem to have a total of 0 OS vulnerabilities.

**Comment by karlhaworth** [comment]
> @karlhaworth based on the issue description and trivy results, I wonder why not `chainguard/node` instead of `chainguard/wolfi-base` as both seem to have a total of 0 OS vulnerabilities.

backstage uses node and python due to techdocs. The chainguard node image doesn’t include python. The chainguard node image would need to change the user to root to install python and other items then switch back to the node user. The non-dev variant also doesn’t include yarn, however that could also be solved either with an install or multi-stage build. 
Either way it didn’t seem to matter much on Wolfi-base or node? I didn’t try the node image due to needing python.
Do you have differences of opinions or improvements that can be made?

**Comment by pjungermann** [comment]
@karlhaworth thank you for your answer and the additional details. I was just curious. However, I also realized that Chainguard only provides the latest version for free which would be problematic here. E.g., you have used node version 18.19. Backstage supports 18 and 20. The latest Chainguard node is 21.7.1.

**Comment by awanlin** [comment]
Oh, that's interesting, I didn't know they charged for some versions. Will that be an issue with `chainguard/wolfi-base` @karlhaworth? We might want to update this to note that then: https://github.com/backstage/backstage/tree/master/contrib/docker/minimal-harded-image

**Comment by pjungermann** [comment]
@awanlin, that's not a problem for wolfi-base. There is just version `1` == `latest`.

And as for all versions, they update them regularly, resulting in different digests that should be pinned (and causing Renovate/Dependabot/... to regularly update and cause new versions/releases/...).

As far as I got the discussion, the pinned digest was not used here not to cause this high frequency of PRs for this contrib version of the Dockerfile.

**Comment by awanlin** [comment]
Awesome, thanks for letting me know @pjungermann, I'm slowly learning more about Chainguard, been on my radar for a while but never really looked into it. 🚀

**Comment by karlhaworth** [comment]
> Awesome, thanks for letting me know @pjungermann, I'm slowly learning more about Chainguard, been on my radar for a while but never really looked into it. 🚀 

I wasn't going to reply unless more was needed however... I sent my work to a few at chainguard to ensure there would be no issue or conflict. The latest image is indeed used so we can properly control versions of python and node, a point @pjungermann made that I had forgotten to make. 
The packages such as node and python do need to be kept up to date, as with previous versions support dwindles. 

The below is a disclaimer I intend to add after talking with Chainguard last week. 

> Starting March 5, Chainguard will maintain one version of each Wolfi package at a time, which will track the latest version of the upstream software in the package. Chainguard will end patch support for previous versions of packages in Wolfi. Existing packages will not be removed from Wolfi, and you may continue to use them. Non-latest packages will no longer be updated and will accrue vulnerabilities over time. The tools we use to build packages and images remain freely available and open source in Wolfi.

Overall the Wolfi image is the best I've seen for a base while maintaining compatibility. It's freely provided, while having commercial interests tied to it however this is by no means an attempt for a sale as I'm not affiliated or a fast rug pull type of deal. Independently I have seen great value in the images both free and paid. Due to the huge amount of vulnerabilities squashed and it helping us internally, I felt it was worth a contribution. 

If there's more discussion needed, happy to participate. Also I think I'm presenting on this at the community session later this month. https://github.com/backstage/community/issues/128

**Comment by awanlin** [comment]
Thanks for the follow up @karlhaworth, just to make sure I understand but to stay in this nice CVE free state with Chainguard you need to be on the latest version of their images? Essentially the `latest` tag?

**Comment by karlhaworth** [comment]
> Thanks for the follow up @karlhaworth, just to make sure I understand but to stay in this nice CVE free state with Chainguard you need to be on the latest version of their images? Essentially the `latest` tag?

for free images `latest` is the only tag. I am referring to the package versions with python and node. Users must stay up to date on these packages.

**Comment by awanlin** [comment]
OK, that might be something to highlight then. That might be more then some Orgs can take on, often Backstage Adopters are not on the latest Backstage version. When CVEs for package dependencies come up they want to patch just that with minimal impact. So staying on `latest` might not be their cup of tea. 

To be clear, still think this is valuable, giving Adopters options or making them aware of them is a worthwhile endeavour!

**Comment by karlhaworth** [comment]
> OK, that might be something to highlight then.

@awanlin I made this PR that might help with that -> https://github.com/backstage/backstage/pull/24309
