### ISSUE TITLE
🔌 Plugin: StatusCake

### ISSUE THREAD

**Issue by mugioka** [backstage/backstage#23366]
### 🔖 Summary

I used to monitoring the my service with [StatusCake](https://www.statuscake.com/).
So i would like to view monitoring status of service in backstage.

StatusCake provides API that can use with API Key authentication.
https://www.statuscake.com/blog/how-to-use-the-statuscake-api/

### 🌐 Project website (if applicable)

https://www.statuscake.com/

### ✌️ Context

StatusCake plugin provides bellow features i expected:

- View ssl check that Component belongs to
  - https://developers.statuscake.com/api#tag/ssl/operation/get-ssl-test
- View uptime check that Component belongs to
  - https://developers.statuscake.com/api#tag/uptime/operation/get-uptime-test

This feature toggled by bellow annotation:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shuffle-api
  annotations:
    statuscake.com/ssl-checks: |
      [
        "test-id-1",
        "test-id-2"
      ]
    statuscake.com/uptime-checks: |
      [
        "test-id-1",
        "test-id-2"
      ]
``` 

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @mugioka, if this is something you'd like to contribute, I noticed you said you would submit a PR, just wanted to give you a heads up that the main repo isn't accepting new plugins. We are hard at work on a new https://github.com/backstage/community-plugins repo where you can submit it in the soon future!

Also, I mentioned this in another issue you posted but I would caution against using annotations in this way, they really aren't intended to be used with complex objects. 👍

**Comment by mugioka** [comment]
@awanlin 
Thank you for your reply!!

> We are hard at work on a new https://github.com/backstage/community-plugins repo where you can submit it in the soon future!

Thank you for backstage team working.
I will be create pr for this issue in above repository.

> Also, I mentioned this in another issue you posted but I would caution against using annotations in this way, they really aren't intended to be used with complex objects. 👍

Thanks!!
I have replied your comment in another issue.

So, i close this issue. thanks.
