### ISSUE TITLE
🚀 Feature: Add the possibility to disable watching files in the new backend system 

### ISSUE THREAD

**Issue by antoniomuso** [backstage/backstage#23374]
### 🔖 Feature description

```ts
  const config = await loadBackendConfig({
    argv: process.argv,
    logger,
    watch: false,
  });
```
Have the possibility to pass as input `watch: false` to the new backend system.

### 🎤 Context

To disable watching files and avoiding this issue: https://github.com/backstage/backstage/issues/19619

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by tudi2d** [comment]
Thanks for raising the issue & PR. For keeping the references - you fixed this for the old system here: https://github.com/backstage/backstage/pull/19718.

**Comment by antoniomuso** [comment]
Hi @tudi2d, when will the PR be merged?

**Comment by tudi2d** [comment]
Hej @antoniomuso - as soon as the PR has 2 approving reviews. As we have an active community & also work on other things than reviewing PRs this can take some days.
