### ISSUE TITLE
🐛 Bug Report: Overlap when expanding the contents on tech docs (UI/CSS issue)

### ISSUE THREAD

**Issue by sammbetts** [backstage/backstage#23381]
### 📜 Description

When expanding the contents on tech docs, if there are a lot of items it will overlap on the 'previous' button at the bottom.

### 👍 Expected behavior

Contents bar should not overlap the footer buttons, instead should scroll contents.

### 👎 Actual Behavior with Screenshots

Before:
<img width="233" alt="Screenshot 2024-03-04 at 11 06 24" src="https://github.com/backstage/backstage/assets/80050322/0e307d07-debc-44ec-a658-1a0ad0e45759">

After expanded:
<img width="206" alt="Screenshot 2024-03-04 at 11 06 34" src="https://github.com/backstage/backstage/assets/80050322/f5e95e17-fe74-4082-acab-c4be5adac07d">

### 👟 Reproduction steps

Happens on tech docs with a lot of items in a menu

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by vinzscam** [comment]
Thank you for raising this!
Cross linking #23420 as it should fix the issue.
