### ISSUE TITLE
🐛 Bug Report: Blank pages in Safari (MacOS) when deploying to local minikube

### ISSUE THREAD

**Issue by netgio** [backstage/backstage#23388]
### 📜 Description

Safari does not render the home page when backstage is deployed to a local minikube cluster following the documentation. 

 

### 👍 Expected behavior

The home page should be displayed

### 👎 Actual Behavior with Screenshots

Safari presents a blank page, the React root page is loaded but none of the dependencies. 
In the developer tools you will see that all script/image resources are being requested as https://localhost and cannot be loaded. 
<img width="1310" alt="backstage-safari-blank" src="https://github.com/backstage/backstage/assets/4880318/c91da572-e996-4eb8-bb02-0af66ed838da">

### 👟 Reproduction steps

Do a clean deploy to minikube on MacOS following the documentation https://backstage.io/docs/deployment/k8s and view the homepage using Safari. 

Navigate to http://localhost with Chrome on the same host, and see a complete default backstage home page, confirming that the app is deployed and operational. 

Navigate to http://localhost with Safari
See a blank page 

Navigate to http://localhost with Chrome on the same host, and see a complete default backstage home page, confirming that the app is deployed and operational. 

### 📃 Provide the context for the Bug.

I found a workaround - the issue is caused by Safari's treatment of the "upgrade-insecure-requests" header. 

The temporary solution I found (this is a local dev environment) is to add the following to app-config.yaml
```
backend:
    csp:
        upgrade-insecure-requests: false
```
[EDIT - I just retested this and it is no longer resolving the issue - I'm not sure whether this means I hallucinate last week, or if a dependency has been updated since]
        
I discovered this from the guidance on this is from patch 0.8.2 of backend-common.... 
https://github.com/backstage/backstage/blob/69fefc351105e3de307e208bdc2c0a107900c390/packages/backend-common/CHANGELOG.md?plain=1#L2517

This says that the config is no longer needed and that you should use "upgrade-insecure-requests: []" instead.   This does not work based on my testing.   Perhaps the behaviour of Helmet has changed again since this patch.  

### 🖥️ Your Environment

MacOS Ventura 13.6.4 (x86)
Safari 17.3.1
Docker Desktop 4.24.0
Docker Engine 24.0.6
Minikube v 1.32.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey :wave: thanks for raising this.

I think that this is most likely produced because you're running a container locally, which means that by default it will have some CSP rules which maybe aren't applied when running locally using `yarn dev`?

The option that you have supplied is one workaround for sure, but probably wouldn't encourage adding that in the container by default as it is a good thing to have for security in a production.

You could perhaps run the container in minikube with additional env flags, like `APP_CONFIG_backed_csp_update-insecure-requests=false`?
