### ISSUE TITLE
🐛 Bug Report: Logger appends log incorrectly

### ISSUE THREAD

**Issue by acierto** [backstage/backstage#23384]
### 📜 Description

With the change in "backend-app-api", using "Filtered internal error with logId=${logId} from response" now this logs goes into pod itself, though logs are configured to be send to Redis.

### 👍 Expected behavior

All logs to be redirected to Redis

### 👎 Actual Behavior with Screenshots

A lot of messages in pod console like:

{"level":"error","logId":"4729a95e626d6a80b2f8","message":"Filtered internal error with logId=4729a95e626d6a80b2f8 from response Encountered invalid error, not an object, got 'class NotFoundError extends CustomErrorBase {\n  constructor() {\n    super(...arguments);\n    __publicField$1(this, \"name\", \"NotFoundError\");\n  }\n}'","service":"backstage","stack":"Error: Encountered invalid error, not an object, got 'class NotFoundError extends CustomErrorBase {\n  constructor() {\n    super(...arguments);\n    __publicField$1(this, \"name\", \"NotFoundError\");\n  }\n}'\n    at Object.assertError (/app/node_modules/@backstage/errors/dist/index.cjs.js:22:11)\n    at applyInternalErrorFilter (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:603:12)\n    at /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:753:21\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /app/node_modules/express-promise-router/lib/express-promise-router.js:55:9\n    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)\n    at trim_prefix (/app/node_modules/express/lib/router/index.js:326:13)\n    at /app/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)\n    at next (/app/node_modules/express/lib/router/index.js:280:10)\n    at next (/app/node_modules/express/lib/router/route.js:136:14)\n    at /app/node_modules/express-promise-router/lib/express-promise-router.js:46:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","type":"errorHandler"}

Prior to 1.23 I never seen such error message, and no error messages in pod.

### 👟 Reproduction steps

Just upgraded from 1.23.next-0 to the latest version

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by vinzscam** [comment]
so with the new behaviour instead of sending out a database error as HTTP body response, the error is filtered out and logged internally, that's why you are seeing the new logs.
I think the issue might be related to a misconfiguration in the logger passed to `MiddlewareFactory.create()`. Probably we are passing a new logger instead of the one you have configured.
