### ISSUE TITLE
🚀 Feature: add data to a relations

### ISSUE THREAD

**Issue by benkeil** [backstage/backstage#23391]
### 🔖 Feature description

Like in a real graph database it would be sometimes helpful to add data to relations.

### 🎤 Context

We use an add-on on top of Kafka to model permissions. Users can subscribe with their applications to topics, but they must be approved by the owner. The subscription would be a relation in Backstage. But I would need to add the state as additional data to it.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Feel free to pitch in at #22358; closing for now as duplicate
