### ISSUE TITLE
🚀 Feature: Extract basic eslint configuration to root factory function

### ISSUE THREAD

**Issue by IlyaSavich** [backstage/backstage#23403]
### 🔖 Feature description

It's actually half-bug half-feature, but here I guess it will be more clear

What I propose is: extract basic eslint configuration in some factory function which will be callable from the root config. That way it will allow overwrite default configuration.

### 🎤 Context

I noticed that I cannot override eslint rules in the root config as these changes are being overwritten by package eslint config which runs eslint-factory with all basic rules, for example rule `curly`.

### ✌️ Possible Implementation

Create eslint-factory function with base configs as there https://github.com/backstage/backstage/blob/master/packages/cli/config/eslint-factory.js
Make it callable from root config

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Hey @IlyaSavich, sorry I think that this got lost before.

I think that we probably want to migrate to eslint@3.x and take this from there, as they've re-hauled the config a little.

**Comment by camilaibs** [comment]
> Hey @IlyaSavich, sorry I think that this got lost before.
> 
> I think that we probably want to migrate to [eslint@3.x](mailto:eslint@3.x) and take this from there, as they've re-hauled the config a little.

@IlyaSavich, the [migration issue](https://github.com/backstage/backstage/issues/25542) has been created, and contributions are welcome in case you'd like to give it a try 🙂

**Comment by IlyaSavich** [comment]
hey, thank you! unfortunately with my current schedule I won't be able to contribute

**Comment by tcardonne** [comment]
Hi,

I'm not sure if that's specifically related but I also noticed that this [`no-restricted-syntax` rule](https://github.com/backstage/backstage/blob/master/.eslintrc.js#L34) isn't enforced on all packages (but only on frontend plugins) in the repository because it's somehow overriden by the `eslint-factory`.

> I think that we probably want to migrate to [eslint@3.x](mailto:eslint@3.x)
Isn't backstage/backstage already [using eslint 8.x](https://github.com/backstage/backstage/blob/master/packages/cli/package.json#L95)? Or are you referring to something else? 😅

**Comment by benjdlambert** [comment]
@tcardonne sorry, I totally meant `eslint@9.x` 😅
