### ISSUE TITLE
backstage-cli versions:bump is stuck unable to upgrade with Node16 and fails with Node18 🐛 Bug Report: 

### ISSUE THREAD

**Issue by alfred-stokespace** [backstage/backstage#23406]
### 📜 Description

I'm stuck on backstage 1.8.3.  `versions:bump` calls fail for nodejs 16 and 18. 

I've seen https://github.com/backstage/backstage/issues/20881 & https://github.com/backstage/backstage/issues/14697, neither one allows for an answer that gets `yarn backstage-cli versions:bump` to work. 

```
yarn backstage-cli versions:bump --release 1.9.1
yarn run v1.22.19
error root@1.0.0: The engine "node" is incompatible with this module. Expected version "14 || 16". Got "18.19.1"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
So, I change to 16...
and I get this error 
`error @azure/identity@4.0.1: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.20.2"`
more context...
```
yarn backstage-cli versions:bump --release 1.9.1
 ...
warning workspace-aggregator-17f6cff2-115e-4ef9-b7ed-84e6ecb676af > backend > @backstage/plugin-scaffolder-backend > @backstage/plugin-scaffolder-backend
-module-gitlab > @gitbeaker/node@35.8.1: Please use its successor @gitbeaker/rest
warning workspace-aggregator-17f6cff2-115e-4ef9-b7ed-84e6ecb676af > backend > @backstage/plugin-catalog-backend > @backstage/repo-tools > @microsoft/api-
extractor > @rushstack/node-core-library > z-schema@5.0.6: has issues with node 14
[3/5] Fetching packages...
warning Pattern ["app@link:packages/app"] is trying to unpack in the same destination "/home/<REDACTED>/.cache/yarn/v6/npm-app-0.0.0/node_modules/app" as pa
ttern ["app@0.0.0","app@0.0.0"]. This could result in non-deterministic behavior, skipping.
error @azure/identity@4.0.1: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.20.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Command 'yarn' exited with code 1
```

### 👍 Expected behavior

`yarn backstage-cli versions:bump --release 1.9.1`

with no errors

### 👎 Actual Behavior with Screenshots

current backstage version is 1.8.3 _(you can see everything you need in the description)_

### 👟 Reproduction steps

1. have a 1.8.3 based backstage project
2. ensure git status shows no changes
3. set your Node version to 16.20.2 
4. ` yarn backstage-cli versions:bump --release 1.9.1`
5. try upgrading with nvm to 18
6. run ` yarn backstage-cli versions:bump --release 1.9.1` again
7. told now that you need node 16 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by alfred-stokespace** [comment]
from https://github.com/backstage/backstage/issues/20881 I see the suggestion to use `yarn install --ignore-engines` but... can I get some confirmation that the correct thing to do after a failed versions:bump I'm supposed to ignore the failure and run that `--ignore-engines`

**Comment by alfred-stokespace** [comment]
I'm going to try going whole hog and do a `yarn backstage-cli versions:bump --release 1.23.4` update and will report back what happens...
I'm guessing that I can be on Node16 when I start running it?  Not sure....
... and that failed ...

```

Upgraded from release 1.8.3 to 1.23.4, please review these template changes:

  https://backstage.github.io/upgrade-helper/?from=1.8.3&to=1.23.4

Running yarn install to install new versions ✖ 
```
with similar error message
```
warning Pattern ["app@link:packages/app"] is trying to unpack in the same destination "/home/alfreds/.cache/yarn/v6/npm-app-0.0.0/node_modules/app" as pa
ttern ["app@0.0.0","app@0.0.0"]. This could result in non-deterministic behavior, skipping.
error @azure/identity@4.0.1: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.20.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Command 'yarn' exited with code 1

error Command failed with exit code 1.
```

So now I guess we try that with Node18?...

**Comment by alfred-stokespace** [comment]
mmm... nope... 
```
nvm install 18
v18.19.1 is already installed.
Now using node v18.19.1 (npm v10.2.4)
```
```
$ yarn backstage-cli versions:bump --release 1.23.4 
yarn run v1.22.19
error root@1.0.0: The engine "node" is incompatible with this module. Expected version "14 || 16". Got "18.19.1"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
So, yea... I'm stuck no matter what version I try to upgrade to and no matter what Node version I have it is always the wrong version.

**Comment by alfred-stokespace** [comment]
... perhaps this is easier than I'm realizing...
I guess I just change that in the main package?, before I perform an versions:bump...? 
```
  "engines": {
    "node": "14 || 16"
  },
```
to
```
  "engines": {
    "node": "18"
  },
```
and then run my versions:bump...
If so that seems like something the backstage-cli should be adjusting for me..
... still waiting on command to run, it's taking forever...
```
Upgraded from release 1.8.3 to 1.23.4, please review these template changes:

  https://backstage.github.io/upgrade-helper/?from=1.8.3&to=1.23.4

Running yarn install to install new versions ◠ 
```

**Comment by awanlin** [comment]
Hi @alfred-stokespace, sorry you've had issues upgraded. The reality is that due to the way Backstage uses more open package versions it's very, very hard to be able to upgrade versions that are far back like yours. We moved to Node 18-20 with version `1.19.0` so in theory you should not have hit this issue but newer versions other packages are being pulled in that require the new Node versions.

As for changing the Node engines in the CLI we like to keep the migrations to new Node versions in the hands of Adopters as they may have their own timeline for things like that.

The best advice I can give you is to stay more up to date with the Backstage versions.

**Comment by alfred-stokespace** [comment]
> Hi @alfred-stokespace, sorry you've had issues upgraded. The reality is that due to the way Backstage uses more open package versions it's very, very hard to be able to upgrade versions that are far back like yours. We moved to Node 18-20 with version `1.19.0` so in theory you should not have hit this issue but newer versions other packages are being pulled in that require the new Node versions.
> 
> As for changing the Node engines in the CLI we like to keep the migrations to new Node versions in the hands of Adopters as they may have their own timeline for things like that.
> 
> The best advice I can give you is to stay more up to date with the Backstage versions.

Can you comment on how I should make progress toward that end of staying up to date given where I am now?  

Where I'm at now is I was able to get the `vesrions:bump` to succeed for an incremental update to `1.10.1` by changing the engines config to support `16 || 18` but I have not yet successfully evaluated the results for my backstage instances... am I on the right path or will that cause other issues? How stuck am I?

**Comment by awanlin** [comment]
Honestly, you are in a bad spot. Trying to go up release by release will be tedious but going to the latest version will be just as hard. Another options, but not sure how good this is either, is to create a new Backstage instance and then compare that to what you have to see what adjustments you might need to make. To be clear none of these are great.

Not sure what tooling you have but if you are using GitHub we have an automated workflow we use for our demo site that will do the upgrade and create a PR so it makes staying up to date a lot easier. It's here is you wanted to check that out: https://github.com/backstage/demo/blob/master/.github/workflows/version-bump.yml

Feel free to continue to post here if you have issue and I'll try and help as best I can.

**Comment by alfred-stokespace** [comment]
thanks @awanlin that helps me in so far as it relieves me from thinking there is some easier path that I'm just not aware of.

**Comment by alfred-stokespace** [comment]
Looks like I'm having a bit of success... I think the process and results are indicating something interesting about how backstage manages its dependencies.

Where I'm at now...
1. I did a `versions:bump` to `1.10.1`
2. I ran into `The engine "node"` incompatibilities. 
3. I checked out backstage github repo at the same tag version
4. I started doing `yarn why`'s on both my backstage project and the github backstage
   1. I did this under the theory that Backstage devs wouldn't have boxed themselves out at the time they tagged these releases. So by comparing dependencies with `yarn why` on the GH project, I was able to deduce a set of `"resolutions"`
6. After getting a basic set of yarn `"resolutions"` which allowed `yarn install` to succeed, I ended up getting runtime failures that killed the backend app.
7. I looked carefully at stack traces and deduced which backstage plugins/packages were failing and did similiar `why`'s compared those to GH backstage package versions of the same packages and then added `"resolutions"` for those.

The resulting `"resolutions"` came to 
```
  "resolutions": {
    "@backstage/config-loader": "1.1.8",
    "@backstage/integration": "1.4.2",
    "@backstage/plugin-catalog-backend-module-github": "0.2.4",
    "@backstage/plugin-catalog-backend-module-aws": "0.1.14",
    "@backstage/plugin-scaffolder-backend": "1.10.1",
    "@azure/identity": "2.1.0",
    "@react-hookz/web": "^20.0.0",
    "commander": "^9.1.0",
    "octokit": "^2.0.0"
  }
```
These all allowed me to start locally my backstage app and I'm able to use my custom plugins. So at the moment it looks like I'm upgraded to 1.10.1.

From what I understand about the journey I've just been on (and I'm **NOT** supper knowledgeable about yarn/npm) is that Backstage has been loosely managing versions and also probably not meeting typical expectations about SEMVER. So the result is that versions of packages are allowed to advance further than they should and that puts us out of date people in a more challenging bind as we get both transitive-dependencies that become incompatible and also internal-backstage-dependencies that break expectations. 

Some examples of internal breaks here are the errors that prompted resolutions for backstage packages...
```
] Backend failed to start up Error: Invalid configuration schema in ../../node_modules/@backstage/plugin-catalog-backend-module-aws/config.d.ts, the following definitions are not supported:
```
and
```
[1] Backend failed to start up Error: Invalid configuration schema in ../../node_modules/@backstage/plugin-catalog-backend-module-github/config.d.ts, th
e following definitions are not supported:
[1]
```

**Comment by alfred-stokespace** [comment]
upon attempting `yarn tsc` I discovered that prior list to be incomplete...

also didn't realize I already had an earlier "resolutions" section so the whole thing that passes `yarn tsc` 
is 
```
"resolutions": {
    "@types/react": "^17",
    "@types/react-dom": "^17",
    "@backstage/config-loader": "1.1.8",
    "@backstage/plugin-catalog": "1.7.2",
    "@backstage/core-components": "0.12.3",
    "@backstage/plugin-catalog-graph": "0.2.26",
    "@backstage/integration": "1.4.2",
    "@backstage/app-defaults": "1.1.0",
    "@backstage/dev-utils": "1.0.8",
    "@backstage/plugin-app-backend": "0.3.41",
    "@backstage/theme": "0.2.16",
    "@backstage/plugin-catalog-backend": "1.7.1",
    "@backstage/plugin-catalog-backend-module-github": "0.2.4",
    "@backstage/plugin-catalog-backend-module-aws": "0.1.14",
    "@backstage/plugin-scaffolder-backend": "1.10.1",
    "@backstage/core-plugin-api": "1.3.0",
    "@backstage/plugin-catalog-react": "1.2.4",
    "@azure/identity": "2.1.0",
    "@react-hookz/web": "^20.0.0",
    "commander": "^9.1.0",
    "octokit": "^2.0.0"
  },
```
the methodolgy was the same, despite the change.

You'd try a round of tsc run, find a problem, assume it's a version of backstage dependency that has been allowed to advance beyond a safe point due to lax semver and package ranging declerations, so you go to the source at the intended tag and assume the version of that package in question is at least close enough to what will satisfy tsc on your project and one by one you knock out complaints from tsc.

**Comment by awanlin** [comment]
@alfred-stokespace the details on versioning is here if you are curious and we do follow SemVer: https://backstage.io/docs/overview/versioning-policy. I do think you are just hitting the fact that the versions ranges for dependencies is much wider.

**Comment by alfred-stokespace** [comment]
> @alfred-stokespace the details on versioning is here if you are curious and we do follow SemVer: https://backstage.io/docs/overview/versioning-policy. I do think you are just hitting the fact that the versions ranges for dependencies is much wider.

@awanlin 
I see now what you mean, quoting from that doc (this statement suggests that really anything goes on a minor release) ... 
```
Each new minor version can contain new functionality, breaking changes, and bug fixes, according the [versioning policy](https://backstage.io/docs/overview/versioning-policy/#release-versioning-policy).
```
I think there is/was a problem that goes deeper then the stated policy however ( although if breaking changes are expected on minor version updates then I guess anything goes 😄 ) , please read on.

It does seem that what I'm blocked by at the moment, which is a runtime failure, is a disagreement between 
1. `@backstage/core-plugin-api`
2. `@backstage/plugin-catalog`

the upgrade helper (https://backstage.github.io/upgrade-helper/?from=1.8.3&to=1.10.1) suggests a particular combination 
```
"@backstage/core-plugin-api": "^1.3.0",
...
"@backstage/plugin-catalog": "^1.7.2",
...
``` 
but what you find with that combination is 
```
WARNING in ../../node_modules/@backstage/plugin-catalog/dist/esm/index-eb346a82.esm.js 32:38-54
[0] export 'usePluginOptions' (imported as 'usePluginOptions') was not found in '@backstage/core-plugin-api'
```

The pre-version-bump versions of those two had been
```
 "@backstage/plugin-catalog@1.6.1"
"@backstage/core-plugin-api@1.2.0"
```
What I'm confused about though, is how these two ever worked together because it seems that (v1.8.3 
 overall and v1.1.0 of c-p-a had `@alpha` on usePluginOptions https://github.com/backstage/backstage/blob/394d8cad7d0113af9eebad81de4e60952875c653/packages/core-plugin-api/src/plugin-options/usePluginOptions.tsx#L68
and 1.6.1 of p-c wasn't using the alpha export, https://github.com/backstage/backstage/blob/394d8cad7d0113af9eebad81de4e60952875c653/plugins/catalog/src/options.ts#L17

Since backstage uses the `^` often in dependency expressions, I'm guessing that's how I was using 1.2.0 of the that package even though I was on platform v1.8.3. So, 1.2.0 package version wasn't released until platform version v1.9.0. 

Perhaps the runtime activation code paths just didn't lead to this discrepancy until the overall release v1.10.1 ?  

Regardless I would expect these two dependencies to have worked together as advertised in the version bump and they clearly don't, unless there is a third dependency which is activating a code path involving the plugin-catalog....

**Comment by alfred-stokespace** [comment]
Perhaps a more specific example of how Backstage's use of `^` along with the minor versions-can-be-breaking policy would be `@backstage/config-loader` 

If you're like-me, and you innocently upgrade to an intermediate platform version of backstage, config-loader rockets up to 
```
=> Found "@backstage/config-loader@1.6.2"
```
when at the point in time for my destination-platform-version (v1.10.1) the highest that module got to was v1.1.8

And that version of config-loader is def not compatible, you discover that with aws module
```
[1] Backend failed to start up Error: Invalid configuration schema in ../../node_modules/@backstage/plugin-catalog-backend-module-aws/config.d.ts, the f
ollowing definitions are not supported:
[1]
[1]   Record<string,{bucketName:string;prefix?:string|undefined;region?:string|undefined;schedule?:any;}>
[1]     at REDACTED/node_modules/@backstage/config-loader/dist/index.cjs.js:367:15
[1]     at Array.map (<anonymous>)
[1]     at compileTsSchemas (REDACTED/node_modules/@backstage/config-loader/dist/index.cjs.js:341:27)
[1]     at async collectConfigSchemas (REDACTED/node_modules/@backstage/config-loader/dist/index.cjs.js:318:21)   
[1]     at async Object.loadConfigSchema (REDACTED/node_modules/@backstage/config-loader/dist/index.cjs.js:507:15)
[1]     at async Object.createConfigSecretEnumerator (REDACTED/node_modules/@backstage/backend-app-api/dist/index.
cjs.js:185:18)
```

which then requires that you to best effort CHANGELOG match up and do a package.json resolution
```
"@backstage/config-loader": "1.1.8",
```

**Comment by alfred-stokespace** [comment]
Okay... I think i'm ready to close this issue out.

My previous specific statements about versions were all wrong (sort of) but the methodology was correct. 

I took a big step back after playing whack-a-mole with backstage specific dependencies and realized that the several of the upgrade guide's changes which are made as a result of versions:bump were getting overridden by the liberal use of the `^` semantics in dependencies. 
So on the this latest step back I said, Hey! since the upgrade helper tool it telling me what versions are expected I'm just going to stick those into my top level package.json as resolutions and that helped a ton (BUT I had to remove the `^` because that's where the real damage happens).

So I'll break this down into the backstage-independent resolutions you need, and then what backstage-releveant resolutions you need.

```
    "@azure/identity": "2.1.0",
    "@react-hookz/web": "^20.0.0",
    "commander": "^9.1.0",
``` 
those are needed to get past the whole nodeJS version problem that was the original motivation for this issue.

Now after that you need the backstage specific callouts to get your particular version:bump working (tsc + runtime!)
The process here was to accumulate all of the upgrade guides' version changes into one big resultions section and remove the `^` as many have gone incompatible.
```
    "@backstage/config-loader": "1.1.8",
    "@backstage/plugin-scaffolder-react": "1.0.1",
    "@backstage/plugin-catalog-backend-module-github": "0.2.3",
    "@backstage/plugin-catalog-backend-module-aws": "0.1.13",
    "@backstage/app-defaults": "1.1.0",
    "@backstage/catalog-model": "1.1.5",
    "@backstage/cli": "0.22.1",
    "@backstage/core-app-api": "1.4.0",
    "@backstage/core-components": "0.12.3",
    "@backstage/core-plugin-api": "1.3.0",
    "@backstage/integration-react": "1.1.9",
    "@backstage/plugin-api-docs": "0.8.14",
    "@backstage/plugin-catalog": "1.7.2",
    "@backstage/plugin-catalog-common": "1.0.10",
    "@backstage/plugin-catalog-graph": "0.2.26",
    "@backstage/plugin-catalog-import": "0.9.4",
    "@backstage/plugin-catalog-react": "1.2.4",
    "@backstage/plugin-github-actions": "0.5.14",
    "@backstage/plugin-org": "0.6.4",
    "@backstage/plugin-permission-react": "0.4.9",
    "@backstage/plugin-scaffolder": "1.10.0",
    "@backstage/plugin-search": "1.0.7",
    "@backstage/plugin-search-react": "1.4.0",
    "@backstage/plugin-tech-radar": "0.6.0",
    "@backstage/plugin-techdocs": "1.4.3",
    "@backstage/plugin-techdocs-module-addons-contrib": "1.0.9",
    "@backstage/plugin-techdocs-react": "1.1.2",
    "@backstage/plugin-user-settings": "0.6.2",
    "@backstage/backend-common": "0.18.0",
    "@backstage/backend-tasks": "0.4.1",
    "@backstage/catalog-client": "1.3.0",
    "@backstage/config": "1.0.6",
    "@backstage/plugin-app-backend": "0.3.40",
    "@backstage/plugin-auth-backend": "0.17.3",
    "@backstage/plugin-auth-node": "0.2.9",
    "@backstage/plugin-catalog-backend": "1.7.0",
    "@backstage/plugin-permission-common": "0.7.3",
    "@backstage/plugin-permission-node": "0.7.3",
    "@backstage/plugin-proxy-backend": "0.2.34",
    "@backstage/plugin-scaffolder-backend": "1.10.0",
    "@backstage/plugin-search-backend": "1.2.1",
    "@backstage/plugin-search-backend-module-pg": "0.5.1",
    "@backstage/plugin-search-backend-node": "1.1.1",
    "@backstage/plugin-techdocs-backend": "1.5.1",
```

Some of these were never mentioned in the upgrade guide and for those you just have grind through the errors while looking at git checkout of backstage and make educated guesses.  
What really helped was examining the CHANGELOG.md files and matching up shared packages, that actually removed much of the amibiquity where it existed.

**Comment by alfred-stokespace** [comment]
thought I'd update again with success stories getting sort-of-updated.

Success with 1.8.3-> 1.10.1
Success with 1.10.1 ->1.12.1
Success with 1.12.1 -> 1.13.2

All have gone to production in my org.

**Comment by awanlin** [comment]
@alfred-stokespace, I'm curious but why haven't you kept your Backstage instance up to date?

**Comment by alfred-stokespace** [comment]
> @alfred-stokespace, I'm curious but why haven't you kept your Backstage instance up to date?

@awanlin good question!
The company I work for is a small startup and I'm the only software engineer with an understanding of Backstage and the interest in spending time to keep using it in our little company. 

I only anticipated needing to update our backstage instance once or twice a year. Now, I did get behind in 2023 due to competing priorities of a small company. 

So, perhaps I made a mistake choosing Backstage?  I'd like to think that Backstage creators had hoped to be capable of being supported by small startups with perhaps a single dev feeding it.  Did I make a mistake? I'd like to hear your thoughts on this topic.

Is Backstage a bad idea for only updating once/twice a year?  If y'all expected it more often I'd say that's a pretty heavy burden my dear fine backstage folks. 

I opted to use Backstage (rather than create a custom website) because I didn't want to write all the integrations (which are very useful) as well I didn't want to start form zero on UI and application framework. I liked that I could start within a foundation and add pages/backends without having to do that design work and implementation ahead of time.

**Comment by awanlin** [comment]
Thanks for sharing these details @alfred-stokespace 👍  

Let me try and answer your questions:

> So, perhaps I made a mistake choosing Backstage? I'd like to think that Backstage creators had hoped to be capable of being supported by small startups with perhaps a single dev feeding it. Did I make a mistake? I'd like to hear your thoughts on this topic.

For context I've been been personally involved with the project for about 3 years now, we initially ran off a fork due to some bugs, which have since been fixed, using it with Azure DevOps Server. I was the only one maintaining Backstage at a small to mid-size organization. Given my experience having a single Dev maintaining it is very realistic and also fairly common as a starting point. Each Org can be different and it may stay a single person for a while or they may invest and grow the team.

> Is Backstage a bad idea for only updating once/twice a year? If y'all expected it more often I'd say that's a pretty heavy burden my dear fine backstage folks.

Backstage is still in active development and evolving. There are releases every month with worth while features that Adopters are looking to use. Due to this only upgrading Backstage once or twice a year is going to lead you to the pain you've experienced. Once we moved off the fork one of the first things I did was create an automated job that would do the version bump, create a branch, commit the changes, and open a pull request. I'd have this run the day after the release early in the morning and then all I had to do was review it and look at the change log. What previously took me a day was down to about 15-45 minutes. I'm not sure what CI/CD tooling you are using but we have similar automation setup for the Backstage Demo site, the workflow is here: https://github.com/backstage/demo/blob/master/.github/workflows/version-bump.yml and here's an example PR: https://github.com/backstage/demo/pull/326

> I opted to use Backstage (rather than create a custom website) because I didn't want to write all the integrations (which are very useful) as well I didn't want to start form zero on UI and application framework. I liked that I could start within a foundation and add pages/backends without having to do that design work and implementation ahead of time.

Yes, this is all reasonable reasons to adopt Backstage and why many Orgs do. I know it was where we were - build it all or use Backstage as a starting point. 🚀 

Hope that helps?

**Comment by alfred-stokespace** [comment]
thanks @awanlin we do in fact use github and have many action workflows so I could certainly give the auto-bump a try. In the past I had not considered it since versions:bump is always has manual steps in the overall process but I can see how having it happen on the regular at least helps you stay updated with the simpler, less complex upgrades and would all me to judge when a more complex upgrade needs more time. 

Thanks.

**Comment by alfred-stokespace** [comment]
Good example @awanlin of how that automated update doesn't really help that much.
I implemented my own and when I finally looked at what it's accomplishing I realized it's not much...

Case in point I did not realize that I had been negatively effected by this bug https://github.com/backstage/backstage/issues/20251
since as the bug states, it only effects you if you are constructing a client of that type, which I was not. 

I failed to put enough testing time into evaluating that particular feature of my backstage instance and now I'm having to stop the upgrade-parade to figure out what to do.

So far I've spent a couple hours trying to understand which of the documents pertain to my situation and am still a little confused.  Point being, upgrading Backstage is not a trivial thing where having an auto version bump can really solve.  Some upgrades are quick and others break you. Again, I know the policy is to allow breaking changes in minor versions, so I guess I asked for this. 

I would warn adopters of Backstage that might be reading this,... complying with updates can be dangerous and time consuming.

**Comment by awanlin** [comment]
Just want to highlight that all my recommendations are once you are up to date. I'm also assuming that you have a solid CI that runs linters, does type checking, fails on deprecated code, runs tests, etc. The automation isn't fully automated, you still need to check the changelog and release notes but having most of this done for you save a ton of time and will let you know right away if there are major breaking changes. Sorry if these items were clear on my part!

Yes, given the fact that you are a year behind in updates and there have been a lot of changes since then the automation won't help you. In the three years I've been part of this project I've only run into you and maybe two to three others have had their instance get so far behind.

> I would warn adopters of Backstage that might be reading this,... complying with updates can be dangerous and time consuming.

I would politely but strongly push back against this as it's simply not correct. I think the warning, if any, is more what I've said a few times already in this issue that you let your Backstage instance fall very far behind and now it has been very hard to upgrade. This isn't how most Backstage Adopters approach upgrades and being 3-4 versions behind has been pretty easy to upgrade from my experience helping support such cases on Discord. Most Adopters stay on the latest or one version back.
