### ISSUE TITLE
spotify/backstage:latest image in helm chart not available

### ISSUE THREAD

**Issue by SriGitHubSri** [backstage/backstage#23429]
### 📜 Description

Hi Team,

I am trying to setup backstage using helm chart under contrib/kubernetes folder but when i try to install this chart , getting error with image spotify/backstage:latest
Please can you update this with a relevant image?

Thanks & Regards,
Sri

### 👍 Expected behavior

Backstage should be deployed fine in the cluster using helm chart and the pod should be in running state without any issues

### 👎 Actual Behavior with Screenshots

NA

### 👟 Reproduction steps

NA

### 📃 Provide the context for the Bug.

NA

### 🖥️ Your Environment

Ubuntu 22.04

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
if you want to use helm please use https://github.com/backstage/charts/tree/main/charts/backstage

However, note that you are still required to build and provide your own Docker image in order to install plugins and similar customization

**Comment by crazy-canux** [comment]
how to build docker image? which is the dockerfile?

**Comment by vinzscam** [comment]
> how to build docker image? which is the dockerfile?

so the Dockerfile should be in your repository under `packages/backend/Dockerfile`
