### ISSUE TITLE
🚀 Feature: Query the catalog backend for all relations of type X

### ISSUE THREAD

**Issue by manuelscurti** [backstage/backstage#23438]
### 🔖 Feature description

A new route in the catalog backend that allows other plugins to gather all involved entities for a given relation type.
The interaction will be something like:
`GET /api/catalog/relations`
That returns

```json
{
   "relations": [
     {
        "sourceEntityRef": "system:default/microservice-a",
        "targetEntityRef": "group:default/team-a",
        "type": "ownedBy"
     },
     ...other relations...
   ]
}
```

optionally, callers can specify some parameters to filter out the results:
`GET /api/catalog/relations?type=ownedBy`
`GET /api/catalog/relations?type=ownedBy&sourceEntityRef=system:default/microservice-a`
`GET /api/catalog/relations?type=ownedBy&targetEntityRef=group:default/team-a`

the allowed filtering parameters will be: `type`, `sourceEntityRef`, `targetEntityRef`

### 🎤 Context

In my context, I will benefit from this feature because I need to gather all users that own at least 1 resource in the catalog or are part of the development team of a resource (this can be seen by a relation that we emit from a custom processor that we have). 

By gathering that list of users, I can perform some actions on them e.g. send those users an email.

The catalog backend currently has no exposed API to retrieve all source or target entities which are linked by a given relation.
Currently, what I would do is:
1. get all users entities in the catalog
2. parse their relations looking for the `ownerOf` and `developerOf` relations

### ✌️ Possible Implementation

Create a `RelationService` on the `catalog-backend` plugin that is the service behind the above-mentioned API route, that will read relations from the `relations` table in the `catalog` schema.
I think it makes sense that only server-to-server auth will be supported by this API route, meaning that only server tokens will be acceptes while instead user tokens will be rejected.  

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
You can do this with the existing API I believe.

`?filter=kind=user,relations.ownerOf&filter=kind=user,relations.developerOf`

Typed out on my phone, but that's the gist of it; leave out the value to look for key existence.

Or using the actual CatalogClient,

```ts
getEntities({
  filter: [
    {
      kind: 'user',
      'relations.ownerOf': CATALOG_FILTER_EXIST,
    },
    {
      kind: 'user',
      'relations.developerOf': CATALOG_FILTER_EXIST,
    },
  ]
})
```

https://github.com/backstage/backstage/blob/3f56a14ff5fb2e0a5b52047368a0eea3e96ace15/packages/catalog-client/src/types/api.ts#L74

**Comment by freben** [comment]
Let me also add that if you're concerned with response sizes, you can add a `fields` query parameter too which cuts down all response entities to just the subset of fields that you require.

https://backstage.io/docs/features/software-catalog/software-catalog-api

**Comment by manuelscurti** [comment]
Thanks!
It's not clear to me how you can filter inside lists. is there a way to do the following?

given resource with entity ref: `system:default/microservice-a`, give me all resources which have a relation of type `readsFrom` towards microservice-a

I would expect to do something like: 

```ts
getEntities({
  filter: [
    {
      kind: 'system',
      'relations.readsFrom': 'system:default/microservice-a',
    },
  ]
})
```

I also tried:
```ts
getEntities({
  filter: [
    {
      kind: 'system',
      'relations.type': 'readsFrom'
      'relations.targetRef': 'system:default/microservice-a',
    },
  ]
})
```

but those attempts do not work.

**Comment by manuelscurti** [comment]
thanks! didn't know `getEntities` was looking into the `search` table, the `relations.ownerOf` in your example now makes much more sense.
