### ISSUE TITLE
💬 RFC: How to deal with packages that show TSC errors after upgrading

### ISSUE THREAD

**Issue by twanbeeren** [backstage/backstage#23444]
### 🔖 Need

So I haven't upgraded backstage in a while because of the constant release cycle. I wanted to test a minor upgrade from 1.10 to 1.11 in this example.

I changed all code according to the [upgrade helper](https://backstage.github.io/upgrade-helper/?from=1.10.0&to=1.11.1), which was really helpful.

But after deleting all present node_modules and the yarn.lock file I had issues after the yarn install.

In our pipeline we create a docker container for backstage which does a yarn install and then a yarn tsc.

In this case the yarn tsc shows issues (presumably linting errors) with the core-plugin-api package.

For example this one

```
node_modules/@backstage/core-plugin-api/dist/alpha.d.ts:123:59 - error TS1139: Type parameter declaration expected.

123 declare function createTranslationRef<TId extends string, const TNestedMessages extends AnyNestedMessages, TTranslations extends {
```

For more context I'll share my dockerfile here. I know it's still using node 16 but this is nearly a year old version of backstage.

```
# Stage 1 - Create yarn install skeleton layer
FROM node:16-bullseye-slim AS packages

WORKDIR /app
COPY package.json yarn.lock ./

COPY packages packages

COPY examples examples

# Comment this out if you don't have any internal plugins
# COPY plugins plugins

RUN find packages \! -name "package.json" -mindepth 2 -maxdepth 2 -exec rm -rf {} \+

# Stage 2 - Install dependencies and build packages
FROM node:16-bullseye-slim AS build

WORKDIR /app
COPY --from=packages /app .

# install postgres dependencies
RUN yarn add --cwd packages/backend pg

RUN yarn install --frozen-lockfile --network-timeout 600000 && rm -rf "$(yarn cache dir)"

COPY . .

RUN yarn tsc
RUN yarn --cwd packages/backend build

# If you have not yet migrated to package roles, use the following command instead:
# RUN yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies

# Stage 3 - Build the actual backend image and install production dependencies
FROM node:16-bullseye-slim

WORKDIR /app

# Copy the install dependencies from the build stage and context
COPY --from=build /app/yarn.lock /app/package.json /app/packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

# Install postgres dependencies
RUN yarn add --cwd packages/backend pg

RUN yarn install --frozen-lockfile --production --network-timeout 600000 && rm -rf "$(yarn cache dir)"

# Copy the built packages from the build stage
COPY --from=build /app/packages/backend/dist/bundle.tar.gz .
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

# Copy any other files that we need at runtime
COPY app-config.yaml ./
# RUN adduser simac
EXPOSE 3000
EXPOSE 7007
# USER simac
# Change healthcheck to target the DNS set in the app.config.yaml
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "curl", "--fail", "http://localhost:3000"]

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```

### 🎉 Proposal

I come from the OPS world so code source maintainance is not my strongest part of expertise. How do I deal with these kind of errors? And is this very common to happen with packages from typescript frameworks

It prevents my docker build to exceed which causes a lot of delay unfortunately.

### 〽️ Alternatives

I considered just not upgrading the packages that cause errors, but this seems like a bad alternative. Also removing the yarn tsc check from the Dockerfile is not prefered.

### ❌ Risks

If such errors prevent upgrades this causes a lot of issues because I want to keep track of the release cycle of every month in the near future.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by twanbeeren** [comment]
Seeing this issue made me realise that it's way harder than I think it would be 

https://github.com/backstage/backstage/issues/23406

**Comment by awanlin** [comment]
Hi @twanbeeren, sorry you are having issues. The real question for me is what is the friction point keeping you from upgrading? Can you elaborate on what this - "constant release cycle" - means? You are currently 12 release behind which is a year's worth of releases. The monthly releases are pretty stable from my experience and any major breakage is patched pretty quickly. I've personally run off the weekly releases with little to no issues (I recognize that's not a huge sample size).

**Comment by awanlin** [comment]
I think this is an important thing to note as it's a bit foundational: "Backstage is a code first framework for building an internal developer portal and thus will require writing and maintaining code to get the most out of it". 

Now, this isn't going to be the state in the future as the project is evolving to fit the needs of Adopters. In order to reach this goal the project moves quickly so staying up to date is key. It's pretty unusual to have someone upgrade from a year old instance, I'm active on the Backstage Discord server which is where I'm basing this on. I would say begin 3-4 versions behind is the most you can be and still have an easy upgrade path.

The problem you are running into is that Backstage uses wide package versions for it's dependencies - `^version` (accept new minor and patch versions). We do this to give adopters flexibility when say a CVE is found in a package. But if you are as far back as a year then dependencies may have update further and are now not compatible.

We keep the Demo site on the weekly `next` release line and have this automated, you can see the PRs here: https://github.com/backstage/demo/pulls?q=is%3Apr+is%3Aclosed+author%3Abackstage-service. If you look you'll see there there's rarely manual changes that are needed and we don't run into any `yarn tsc` errors.

Does this help give you more context?

**Comment by twanbeeren** [comment]
> Hi @twanbeeren! The issue you are having looks very much related to typescript. Which version of typescript are you using? I think bumping typescript might help solving the issue.

My package.json shows me the following:
`"devDependencies": {
    "@backstage/cli": "^0.22.2",
    "@spotify/prettier-config": "^12.0.0",
    "concurrently": "^6.0.0",
    "lerna": "^4.0.0",
    "node-gyp": "^9.0.0",
    "prettier": "^2.3.2",
    "typescript": "~4.6.4"
  },`

**Comment by vinzscam** [comment]
> So "typescript": "~4.6.4"

yeah exactly I think your issue requires typescript 4.7 to be fixed

**Comment by Rugvip** [comment]
Gonna need TypeScript v5.0+ at this point, the further you can bump the better
