### ISSUE TITLE
🚀 Feature: Allow using the scaffolder template to remove code using the pull-request action

### ISSUE THREAD

**Issue by shashankram** [backstage/backstage#23447]
### 🔖 Feature description

Hi, I am using the `action: publish:github:pull-request` action in a scaffolder template to make a PR. However, I would like to be able to remove files in a Git repo with this PR. Is that possible?

### 🎤 Context

With GitOps based workflows, it's common to remove manifests from a Git repo

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
Hmm, so I think looking at the code that the only way to delete files with the `github-pull-request` plugin in Octokit is to path `path: null` in the files object like this: https://github.com/gr2m/octokit-plugin-create-pull-request/blob/main/README.md?plain=1#L84

Which currently isn't possible with the scaffolder action right now as it serializes the directory contents to produce the `files` object.

I've been wanting to move all the operations with providers to use the `git` protocol natively as much as possible, which could be a fix, but that work hasn't really moved yet: https://github.com/backstage/backstage/issues/22244

**Comment by aayeshaarshad** [comment]
still a valid issue

**Comment by adsk-mukul** [comment]
this is still a valid issue.
