### ISSUE TITLE
azure-devops-backend: multi-org support

### ISSUE THREAD

**Issue by javedfaruquee1** [backstage/backstage#23440]
### 🔖 Summary

Can Azure devops plugin support multiple organizations? If yes, could you please update README document with sample configuration required to support multiple oganizations.
I tried something like below and other config. but didn't help.
integrations: 
  azure:
    - host: dev.azure.com
      credentials:
        - organizations: 
            - ORG1
          personalAccessToken: ffff  
        - organizations: 
            - ORG2
          personalAccessToken: gggg
azureDevOps:
  - host: dev.azure.com
    organization:  ORG1
    token: ffff 
  - host: dev.azure.com
    organization:  ORG2
    token: gggg

### 🌐 Project website (if applicable)

https://github.com/backstage/backstage/tree/master/plugins/azure-devops-backend

### ✌️ Context

Connect Azure Devops for multiple organizations

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by JD-Gonz** [comment]
+1 
In addition does Azure-devops-backend support additional configuration methods other than PAT? does it support managed identity, service principal?

**Comment by awanlin** [comment]
Hi @javedfaruquee1, yes it does support [Multi Organization & Service Principals](https://github.com/backstage/backstage/tree/master/plugins/azure-devops-backend#multi-organization--service-principals). You can find examples in the [Azure DevOps locations](https://backstage.io/docs/integrations/azure/locations) documentation. 

Does that help?

**Comment by awanlin** [comment]
Hi @JD-Gonz, it relies on the `integrations.azure` section for its credentials and supports PATs, Service Principals, and Managed Identity as described in the [Azure DevOps locations](https://backstage.io/docs/integrations/azure/locations) documentation.

I will admit that there is some confusion around the configuration and I'm currently working on a PR to make that more clear. Can you share what setup you have - single or or multi-org - and I can give you some recommendations?

**Comment by awanlin** [comment]
Here's the PR to try and make this more clear: https://github.com/backstage/backstage/pull/23462. 

One thing I'll note is that as the plugin relies on the Catalog and the Catalog won't work without a properly configured `integrations.azure` section I don't want to add examples to the plugin's `README`. If the examples in the [Azure DevOps locations](https://backstage.io/docs/integrations/azure/locations) documentation aren't clear then I think those should be updated.

**Comment by javedfaruquee1** [comment]
Hi, 

I tried with below config, but it didn't work, can you give a sample config for multiple org. for azureDevops?

azure:
  - host: dev.azure.com
    credentials:
       - organizations:
             - ORG1
               personalAccessToken: ffff
      - organizations:
           - ORG2
              personalAccessToken: gggg

azureDevOps:
  - host: dev.azure.com
    organization: ORG1
     token: ffff
  - host: dev.azure.com
     organization: ORG2
     token: gggg

**Comment by awanlin** [comment]
@javedfaruquee1, your first section looks correct, it's hard to be 100% sure as it's not formatted as YAML. The 2nd section is wrong, the `azureDevOps` config doesn't support multiple host like this as it uses the information from the `intergations.azure` section instead. For this config you can just use dummy values like this:

```yaml
azureDevOps:
  host: dev.azure.com
  token: dummy-value
  organization: dummy-org
```

You say "but it didn't work", can you provide more details as to what you mean? Are you getting errors? Is the Catalog able to pull data from your various Azure DevOps Orgs? Did you add the needed annotations? There's the possibility the config is correct but there are other issues so having all the details will make it easier for us to work together to resolve this 👍

**Comment by javedfaruquee1** [comment]
Mq question is how does the configration looks like for azureDevOps for multiple organizations, 
 will it be like:
````azureDevOps:
       - host: dev.azure.com
          token: dummy-value
          organization: dummy-org
       - host: dev.azure.com
          token: dummy-value
          organization: dummy-org```

**Comment by awanlin** [comment]
You don't need that as it read the values from `integrations.azure` instead. The idea is that you configure it in one place instead of having to duplicate it.

**Comment by awanlin** [comment]
You only need to put the dummy section I shared in my previous reply for a single org. I really won't use it but the way the code was written will fail if it's not present.

**Comment by awanlin** [comment]
Perhaps showing the code could help:

https://github.com/backstage/backstage/blob/87e9ed3ccc64074fe21d123e16199b54a55bc41e/plugins/azure-devops-backend/src/api/AzureDevOpsApi.ts#L107

The above function gets called each time a request comes into the backend. It expects a `host` and `org` which would come from the annotations on each Entity in the Catalog. If those are `undefined` then it will use the config values as that was how it worked historically for single orgs which was how the plugin was built initially. It then tries to look up the credentials from the `integrations.azure` section. From there is can proceed with the various calls to Azure DevOps itself.

As I mentioned previously, I agree this is a bit confusing, we added support for multiple orgs just last summer but then I've been very busy and haven't had the time to come back and clean this up. I've done that now but the Pr needs to be reviewed and merged. Hopefully it can make the March monthly release but I'm currently travelling so not sure that will be possible.

**Comment by JD-Gonz** [comment]
@awanlin Thank you for the insight. My biggest questionmark was around how we configure `azureDevOps` portion of the YAML. Knowing that we can use dummy values here and just leverage [Azure DevOps locations](https://backstage.io/docs/integrations/azure/locations) unblocks my use case.

**Comment by awanlin** [comment]
@JD-Gonz, sorry, I was under the impression you were also a multi-org user which is why I gave you the recommendations I did. Glad you were able to sort it out though. 👍

**Comment by javedfaruquee1** [comment]
Made changes as suggested and it worked for me, many thanks

**Comment by awanlin** [comment]
Awesome, glad things are working for you as well 🚀
