### ISSUE TITLE
🐛 Bug Report: Kind filters applied in CatalogGraphCard in an EntityPage not applied properly to CatalogGraphPage's filter UI components

### ISSUE THREAD

**Issue by peter-carriad** [backstage/backstage#23456]
### 📜 Description

When using the `kinds` filter in a catalog graph card displayed in an entity's page as follows:
```
<EntityCatalogGraphCard
    kinds={["API", "Component", "Domain", "Group", "Location", "System", "User"]}
    variant="gridItem"
    height={400} />
```

The behavior of the associated dedicated `CatalogGraphPage`'s filter section when accessed view the "view graph" link is incorrect (checkboxes for filtered `kinds` not selected properly, more info and details below). 

### 👍 Expected behavior

The `CatalogGraphPage` filter checkboxes and tagged fields should carry over from the `EntityPage`'s card which the user clicked "view graph" on to navigate to the `CatalogGraphPage`.

### 👎 Actual Behavior with Screenshots

Navigating from a `CatalogGraphCard` embedded in an `EntityPage` to the dedicated `CatalogGraphPage` (by clicking the "View Graph" link on the card) results in a graph page which has the correct `kind` filters applied **but** does not have them selected properly in the `kind` filter pane.

![image](https://github.com/backstage/backstage/assets/151267161/a9a38687-da28-4270-86eb-e2aa84a22c64)

**In the images below** you can see that after this flow the proper checkboxes (lower) are not ticked even though the filters are applied (upper). if the user ticks any of the checkboxes (lower), they will add an additional redundant tag to the pool of filters (upper) e.g. if you select API, another new API tag will be added to the upper section which already includes an API tag:

#### **Initial view:**
![image](https://github.com/backstage/backstage/assets/151267161/5b4b6176-29cc-4a9c-bef0-6f36c0c2fc6c)
#### **After selecting 'API' via checkbox: (note redundant API entry now present) **
![image](https://github.com/backstage/backstage/assets/151267161/fbcc9ee6-0d78-4584-9ad5-00bf65f7edbc)

This does not seem like intended behavior and is a bad user experience.

### 👟 Reproduction steps

1. apply a `kinds` or `relationships` filter to an `EntityPage`'s `CatalogGraphCard` as follows:
  ```
  <EntityCatalogGraphCard
      kinds={["API", "Component", "Domain", "Group", "System", "User"]}
      variant="gridItem"
      height={400} />
  ```
2. start your dev backstage instance with this code applied
3. navigate to an affected `EntityPage` instance with a `CatalogGraphCard`
4. click "view graph" on the graph card
5. observe the reported issue (outlined in previous steps) in the filter-related UI components
![image](https://github.com/backstage/backstage/assets/151267161/fbcc9ee6-0d78-4584-9ad5-00bf65f7edbc)

### 📃 Provide the context for the Bug.

We were trying to filter out a custom `ReleaseNote` `kind` from the graph when we encountered this bugged behavior.

### 🖥️ Your Environment

OS:   Linux 6.2.0-1019-azure - linux/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.25.2 (installed)
backstage:  1.23.4

Dependencies:
  @backstage/app-defaults                                          1.5.0
  @backstage/backend-app-api                                       0.5.14
  @backstage/backend-common                                        0.21.3
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.6
  @backstage/backend-plugin-api                                    0.6.13
  @backstage/backend-tasks                                         0.5.18
  @backstage/catalog-client                                        1.6.0
  @backstage/catalog-model                                         1.4.4
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.3
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.6.2
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.12.0
  @backstage/core-compat-api                                       0.2.0
  @backstage/core-components                                       0.14.0
  @backstage/core-plugin-api                                       1.9.0
  @backstage/dev-utils                                             1.0.27
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.5
  @backstage/frontend-plugin-api                                   0.6.0
  @backstage/integration-aws-node                                  0.1.9
  @backstage/integration-react                                     1.1.24
  @backstage/integration                                           1.9.0
  @backstage/plugin-analytics-module-ga4                           0.2.0
  @backstage/plugin-api-docs                                       0.11.0
  @backstage/plugin-app-backend                                    0.3.61
  @backstage/plugin-app-node                                       0.1.13
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.8
  @backstage/plugin-auth-backend-module-github-provider            0.1.10
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.10
  @backstage/plugin-auth-backend-module-google-provider            0.1.10
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.8
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.10
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.6
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.6
  @backstage/plugin-auth-backend                                   0.21.3
  @backstage/plugin-auth-node                                      0.4.8
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.10
  @backstage/plugin-catalog-backend                                1.17.3
  @backstage/plugin-catalog-common                                 1.0.21
  @backstage/plugin-catalog-graph                                  0.4.0
  @backstage/plugin-catalog-import                                 0.10.6
  @backstage/plugin-catalog-node                                   1.7.3
  @backstage/plugin-catalog-react                                  1.10.0
  @backstage/plugin-catalog                                        1.17.0
  @backstage/plugin-events-node                                    0.2.22
  @backstage/plugin-github-actions                                 0.6.11
  @backstage/plugin-home-react                                     0.1.8
  @backstage/plugin-home                                           0.6.2
  @backstage/plugin-org                                            0.6.20
  @backstage/plugin-permission-backend                             0.5.36
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.24
  @backstage/plugin-permission-react                               0.4.20
  @backstage/plugin-proxy-backend                                  0.4.11
  @backstage/plugin-scaffolder-backend-module-azure                0.1.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.3
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.5
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.3
  @backstage/plugin-scaffolder-backend-module-github               0.2.3
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.16
  @backstage/plugin-scaffolder-backend                             1.21.3
  @backstage/plugin-scaffolder-common                              1.5.0
  @backstage/plugin-scaffolder-node                                0.3.3
  @backstage/plugin-scaffolder-react                               1.8.0
  @backstage/plugin-scaffolder                                     1.18.0
  @backstage/plugin-search-backend-module-catalog                  0.1.17
  @backstage/plugin-search-backend-module-pg                       0.5.22
  @backstage/plugin-search-backend-module-techdocs                 0.1.17
  @backstage/plugin-search-backend-node                            1.2.17
  @backstage/plugin-search-backend                                 1.5.3
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.6
  @backstage/plugin-search                                         1.4.6
  @backstage/plugin-techdocs-backend                               1.9.6
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.5
  @backstage/plugin-techdocs-node                                  1.11.5
  @backstage/plugin-techdocs-react                                 1.1.16
  @backstage/plugin-techdocs                                       1.10.0
  @backstage/plugin-user-settings                                  0.8.1
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.6.3
  @backstage/test-utils                                            1.5.0
  @backstage/theme                                                 0.5.1
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
Done in 0.78s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by vinzscam** [comment]
The `EntityPage` doesn't have any filter, the filters are only present in `/catalog`. I think this would make sense if there was a direct link from `/catalog` to `/catalog-graph` but as it is right now there is `/catalog/default/component/xxx` in the middle which breaks this flow. Adding such a feature will add extra complexity which I am not sure it makes sense to add.
