### ISSUE TITLE
Send request to the scaffolder backend using backend.auth.keys works for some routes but not `/api/scaffolder/v2/tasks`

### ISSUE THREAD

**Issue by onyicho-cr** [backstage/backstage#23458]
### 🔖 Need

Apologize if issue type is incorrect, but just want to ask for any suggestion or help. 

I am trying to create a script to create new component from template without going through the UI. Currently, I am able to use the backend auth key (**backend.auth.keys** in YAML config) to create Bearer token, and then send an API call to Backstage successfully on both `/api/catalog/entities?filter=` and `/api/scaffolder/v2/actions` paths. However, when I try a POST request to `/api/scaffolder/v2/tasks` I got 401 Unauthorized back :( 

The only relevant issue I found is https://github.com/backstage/backstage/issues/18622, but I am not getting the same kind of error as mentioned in that issue. I've also look into source code but couldn't find any clue yet. Any suggestion or idea? Perhaps I am missing some configurations? Please let me know if I should provide any additional information. Thank you!

### 🎉 Proposal

N/A

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by vinzscam** [comment]
Which version of Backstage are you using? Are you using some of the next releases?

**Comment by onyicho-cr** [comment]
> Which version of Backstage are you using? Are you using some of the next releases?

I am using 1.18.3. Should I upgrade my backstage version?

**Comment by benjdlambert** [comment]
@onyicho-cr could you try the latest version of Backstage 1.27 and see if the problem persists? There's been a lot of things with auth that has changed over the last releases, and thinking that it might have been fixed.
