### ISSUE TITLE
🙏 Help Wanted: No Top Level Material UI 4 Imports

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#23467]
To make moving moving to Material UI 5 easier we need to stop using top level imports with Material UI 4 in all the frontend plugins. To help with this we have added an optional ESLint rule - `no-top-level-material-ui-4-imports` - which has an auto fix function to migrate the imports for us. 

We need help getting this added to each of the plugins and validating there are no regressions (CI will handle this, if it's green we are good).

## Process

The process is pretty easy, we'll use the `adr` plugin for this example:

1. Fork the `backstage/backstage` repo
2. Run `yarn install`
3. Open the project in your code editor
4. Navigate to the `/plugins/adr` folder
5. Open the `.eslintrc.js` file
6. Modify the file so it looks like this:

```js
module.exports = require('@backstage/cli/config/eslint-factory')(__dirname, {
  rules: {
    '@backstage/no-top-level-material-ui-4-imports': 'error',
  },
});
```

7. Now when you run `yarn lint` you should get errors saying: "Top level imports for Material UI are not allowed"
8. To fix the errors run: `yarn lint --fix`
9. At this point the process is complete, commit the changes and create a PR making sure to follow the [contributing guidelines](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md)

> Note: it's possible that there are errors in the CI from this, you'll need to address those as they come up. Feel free to comment on this issue if you get stuck along the way.

## Completed Examples

The [Azure DevOps](https://github.com/backstage/backstage/tree/master/plugins/azure-devops), [DevTools](https://github.com/backstage/backstage/tree/master/plugins/devtools), and [Linguist](https://github.com/backstage/backstage/tree/master/plugins/linguist) plugins have been completed already and you can look at those if you need examples.

## List of Plugins

The following list of plugins need to be migrated (as of 2024-04-07):

```text
@backstage/app-defaults
@backstage/dev-utils
@backstage/frontend-app-api
@backstage/frontend-plugin-api
@backstage/integration-react
@backstage/test-utils
@backstage/plugin-auth-react
@backstage/plugin-azure-sites
@backstage/plugin-catalog-react
@backstage/plugin-cicd-statistics
@backstage/plugin-config-schema
@internal/plugin-todo-list
@backstage/plugin-git-release-manager
@backstage/plugin-github-actions
@backstage/plugin-github-pull-requests-board
@backstage/plugin-graphiql
@backstage/plugin-home-react
@backstage/plugin-ilert
@backstage/plugin-kubernetes-react
@backstage/plugin-org-react
@backstage/plugin-scaffolder-react
@backstage/plugin-search-react
@backstage/plugin-signals-react
@backstage/plugin-techdocs-react
@backstage/plugin-todo
```

When https://github.com/backstage/backstage/pull/23466 gets merged you can generate an up to date list by running: `node scripts/list-no-top-level-material-ui-4-imports.js` but make sure to check for any active PRs as well

**Comment by aureliosaraiva** [comment]
Anyone looking at this?  I can do it if no one else is doing it.

**Comment by Sarabadu** [comment]
Note:
imports of ThemeProvider are autofixed to 
`import ThemeProvider from '@material-ui/core/ThemeProvider';` but should be 
`import { ThemeProvider } from '@material-ui/core/styles';`

**Comment by awanlin** [comment]
FYI - I've updated the list of plugins that need to be migrated yesterday (2024-04-07). I did not check if there are any open PRs for these so please do that before moving forward. Thanks!!!

**Comment by Sarabadu** [comment]
updated list:

#### WIP (following links to this issue):


#23913
```
@backstage/plugin-git-release-manager 
```
#23916
```
@backstage/plugin-home-react 
```
#24068
```
@backstage/plugin-techdocs-react  
```
#24134
```
@backstage/app-defaults  
app-next-example-plugin 
@backstage/frontend-app-api 
@backstage/frontend-plugin-api 
@backstage/integration-react 
```

#### pending: 
```
@backstage/plugin-auth-react
@backstage/plugin-azure-sites
@backstage/plugin-catalog-react
@backstage/plugin-cicd-statistics
@backstage/plugin-config-schema
@internal/plugin-todo-list
@backstage/plugin-github-actions
@backstage/plugin-github-pull-requests-board
@backstage/plugin-graphiql
@backstage/plugin-ilert
@backstage/plugin-kubernetes-react
@backstage/plugin-org-react
@backstage/plugin-scaffolder-react
@backstage/plugin-search-react
@backstage/plugin-signals-react

```

**Comment by Sarabadu** [comment]
Added a new fix for the fixer 😆 here https://github.com/backstage/backstage/pull/24138
this should solve all the wrong fixes on https://github.com/backstage/backstage/pull/23913 PR

**Comment by Tapudp** [comment]
Is this still open or left to continue?

**Comment by vinzscam** [comment]
Thanks everyone! 🙏
