### ISSUE TITLE
💬 RFC: enable DryRun for 2 scaffolder github actions

### ISSUE THREAD

**Issue by rewixe** [backstage/backstage#23477]
### 🔖 Need

We have a backstage template that uses two actions: 'github:webhook' and 'publish:github:pull-request'. We are trying to use the endpoint '/api/scaffolder/v2/dry-run' to test our template with dry run, but currently this is not working because the dry run skips these two actions as they do not seem to support dry run.

### 🎉 Proposal

I want to update the typescript files for both of these two actions such that they both have 'supportsDryRun' set to 'true' and will both work with the template dry run endpoint '/api/scaffolder/v2/dry-run'.

### 〽️ Alternatives

We have not found an alternative to enabling the dry run for both of these actions.

### ❌ Risks

There is a risk that enabling the dry run will have a knock on effect on other parts of the code for these two actions, so we will need to perform testing on both actions to ensure that the impact of this change is restricted to allowing the dry run to work with both these actions.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by rewixe** [comment]
I am happy to take on this work and make these changes.

**Comment by Rugvip** [comment]
@rewixe thank you, this does indeed need a fix! 🎉

Heads up that it may be the some of the outputs need to be mocked when running as a dry run, for example like this: https://github.com/backstage/backstage/blob/8b269e1879b580bc29b5852421cb33b29e3b8d40/plugins/scaffolder-backend-module-gerrit/src/actions/gerrit.ts#L206-L219

**Comment by rewixe** [comment]
Sure @Rugvip, sounds good. You can assign that work to me, I would be happy to do that.

**Comment by rewixe** [comment]
Hi @Rugvip, can this be assigned to us?
