### ISSUE TITLE
🐛 Bug Report: 'yarn start' not working on generated backend plugin

### ISSUE THREAD

**Issue by tomasmota** [backstage/backstage#23487]
### 📜 Description

When creating a backend plugin with `yarn new`, the readme states that it can be started by running `yarn start` in the plugin directory, but this is erroring out.

### 👍 Expected behavior

`yarn start` starts the backend plugin

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/25929015/b3b2777c-be57-4082-8eca-d99fb952a150)

### 👟 Reproduction steps

1. create project with `npx @backstage/create-app@latest`
2. go into root and run `yarn new`, selecting backend plugin and putting in a name
3. navigate to plugin directory and run `yarn start`

### 🖥️ Your Environment

```
OS:   Linux 5.15.146.1-microsoft-standard-WSL2 - linux/x64
node: v20.11.1
yarn: 1.22.19
cli:  0.25.2 (installed)
backstage:  1.23.0

Dependencies:
  @backstage/app-defaults                                          1.5.0
  @backstage/backend-app-api                                       0.5.14
  @backstage/backend-common                                        0.21.3
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.6
  @backstage/backend-plugin-api                                    0.6.13
  @backstage/backend-tasks                                         0.5.18
  @backstage/backend-test-utils                                    0.3.3
  @backstage/catalog-client                                        1.6.0
  @backstage/catalog-model                                         1.4.4
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.3
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.6.2
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.12.0
  @backstage/core-compat-api                                       0.2.0
  @backstage/core-components                                       0.14.0
  @backstage/core-plugin-api                                       1.9.0
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.5
  @backstage/frontend-plugin-api                                   0.6.0
  @backstage/integration-aws-node                                  0.1.9
  @backstage/integration-react                                     1.1.24
  @backstage/integration                                           1.9.0
  @backstage/plugin-api-docs                                       0.11.0
  @backstage/plugin-app-backend                                    0.3.61
  @backstage/plugin-app-node                                       0.1.13
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.8
  @backstage/plugin-auth-backend-module-github-provider            0.1.10
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.10
  @backstage/plugin-auth-backend-module-google-provider            0.1.10
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.8
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.10
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.6
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.6
  @backstage/plugin-auth-backend                                   0.21.3
  @backstage/plugin-auth-node                                      0.4.8
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.10
  @backstage/plugin-catalog-backend                                1.17.3
  @backstage/plugin-catalog-common                                 1.0.21
  @backstage/plugin-catalog-graph                                  0.4.0
  @backstage/plugin-catalog-import                                 0.10.6
  @backstage/plugin-catalog-node                                   1.7.3
  @backstage/plugin-catalog-react                                  1.10.0
  @backstage/plugin-catalog                                        1.17.0
  @backstage/plugin-events-node                                    0.2.22
  @backstage/plugin-github-actions                                 0.6.11
  @backstage/plugin-org                                            0.6.20
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.24
  @backstage/plugin-permission-react                               0.4.20
  @backstage/plugin-proxy-backend                                  0.4.11
  @backstage/plugin-scaffolder-backend-module-azure                0.1.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.3
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.5
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.3
  @backstage/plugin-scaffolder-backend-module-github               0.2.3
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.16
  @backstage/plugin-scaffolder-backend                             1.21.3
  @backstage/plugin-scaffolder-common                              1.5.0
  @backstage/plugin-scaffolder-node                                0.3.3
  @backstage/plugin-scaffolder-react                               1.8.0
  @backstage/plugin-scaffolder                                     1.18.0
  @backstage/plugin-search-backend-module-catalog                  0.1.17
  @backstage/plugin-search-backend-module-pg                       0.5.22
  @backstage/plugin-search-backend-module-techdocs                 0.1.17
  @backstage/plugin-search-backend-node                            1.2.17
  @backstage/plugin-search-backend                                 1.5.3
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.6
  @backstage/plugin-search                                         1.4.6
  @backstage/plugin-tech-radar                                     0.6.13
  @backstage/plugin-techdocs-backend                               1.9.6
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.5
  @backstage/plugin-techdocs-node                                  1.11.5
  @backstage/plugin-techdocs-react                                 1.1.16
  @backstage/plugin-techdocs                                       1.10.0
  @backstage/plugin-user-settings                                  0.8.1
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.6.3
  @backstage/test-utils                                            1.5.0
  @backstage/theme                                                 0.5.1
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
Done in 0.52s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Parsifal-M** [comment]
Hey @tomasmota :wave: 

To which docs/readme are you referring?

Thanks!

**Comment by tomasmota** [comment]
I'm referring to the readme in the actual generated plugin.

**Comment by Parsifal-M** [comment]
> I'm referring to the readme in the actual generated plugin.

Ah clear! I assume thats happening [here](https://github.com/backstage/backstage/blob/f9dac1ee6691c32b86beca5a691f7231e0aab882/packages/cli/templates/default-backend-plugin/README.md.hbs#L12) should this be `yarn start-backend` @Rugvip I guess we can just update that template file? Honestly I am not 100% sure how the templating works on the cli

**Comment by tomasmota** [comment]
As far as I remember the package.json also still has dev on the commands. If I get an indication of what to change I can make a pr on it :)

**Comment by Parsifal-M** [comment]
> As far as I remember the package.json also still has dev on the commands. If I get an indication of what to change I can make a pr on it :)

AFAIK if you want to serve it in **isolation** you'd need to do `yarn start-backend` as `yarn dev` spins up both the front end and backend concurrently. 

But lets see what @Rugvip or perhaps @awanlin thinks on this? as it should be a quick win :smile:

**Comment by Parsifal-M** [comment]
> As far as I remember the package.json also still has dev on the commands. If I get an indication of what to change I can make a pr on it :)

Sorry I was wrong, I think it should actually be `LEGACY_BACKEND_START=true yarn start` as it mentions here: https://backstage.io/docs/plugins/backend-plugin/ 

I assume some stuff still needs shuffling in order to not have to use the `LEGACY_BACKEND_START=true` part :sweat_smile:

**Comment by awanlin** [comment]
So, did some testing on this. Looks like migration/growing pains.

You want to be on version `1.24.x` which includes the update CLI where the backend template uses the new backend system which includes the `/dev/index`. PR that updated the template: https://github.com/backstage/backstage/pull/23485

Now `yarn start` works BUT the instructions in the `README` are still wrong as it says to use `http://localhost:3000/plugin-name` but that's for a frontend plugin. For this it would be `http://localhost:7007/api/plugin-name`. Now that won't really get you anything so it might make sense to update the `README` to use `http://localhost:7007/api/plugin-name/health` as that should get you some feedback in a browser or if you cURL it. The only thing is that gets an authentication error (at least in my testing with a fresh instance of `create-app`)

Hope that helps a little?

**Comment by Parsifal-M** [comment]
> So, did some testing on this. Looks like migration/growing pains.
> 
> You want to be on version `1.24.x` which includes the update CLI where the backend template uses the new backend system which includes the `/dev/index`. PR that updated the template: https://github.com/backstage/backstage/pull/23485
> 
> Now `yarn start` works BUT the instructions in the `README` are still wrong as it says to use `http://localhost:3000/plugin-name` but that's for a frontend plugin. For this it would be `http://localhost:7007/api/plugin-name`. Now that won't really get you anything so it might make sense to update the `README` to use `http://localhost:7007/api/plugin-name/health` as that should get you some feedback in a browser or if you cURL it. The only thing is that gets an authentication error (at least in my testing with a fresh instance of `create-app`)
> 
> Hope that helps a little?

Awesome, thanks for clarifying 👏 should we update the docs page now as well as the readme? 🤔 Or at least maybe a note in the docs page if you are on version 1.24.x e.g

**Comment by awanlin** [comment]
Yes, busy working on those items 👍

**Comment by awanlin** [comment]
Just submitted a PR #23821 to address this 👍
