### ISSUE TITLE
🚀 Feature: Enhancing EntityOwnershipCard's UX

### ISSUE THREAD

**Issue by pballandras** [backstage/backstage#23518]
### 🔖 Feature description

Improve the display of the EntityOwnershipCard to understand the ownership of an entity more easily. As it is currently, the card will display only the 6 top entities by default. This can, sometimes, lead to wrongfully display the ownership in cases where a lot of entity kind-type pairs exist.

The idea here is that we should be able to grasp the scale of an entity's ownership at a glance while preserving the screen real estate.

### 🎤 Context

Some teams/groups/entities will inevitably have ownership over a lot of different pairs of kind and type of entities. Instead of just cutting the entities after 6 or adding more rows, we could instead use different strategies to show the information.

For example some team could maintain 2 different types of API, a couple systems, 4 different component types, etc (i. The point is, you would lose some of that ownership data after 6. Yes you can increase the number of displayed entities, but then you must sacrifice screen real estate which would decrease UX.

### ✌️ Possible Implementation

Here are a couple of ideas that came to mind when thinking about this:

1. It could be made possible to only display the kind of an entity. With this you would run less frequently into more than 6 entity boxes to display. 
2. The number of entities owned could be displayed, potentially showing the fraction of entities showed over total numbers of entities owned. With this, you can have hidden entity boxes, but still have an indicator that has a _but wait, there's more_ kind of meaning/message.
3. Adding pagination to the display of the entity boxes. This way you keep screen real estate and still see all of the entity boxes.

The plus here is that they are not incompatible with each other and can be added in different PRs.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Happy to review any concrete suggestions, probably in a PR but could also be screenshots/wireframes.
