### ISSUE TITLE
🚀 Feature: Link to the template entity page from the template card

### ISSUE THREAD

**Issue by ltdonner-bah** [backstage/backstage#23524]
### 🔖 Feature description

It would be nice to be able to get to a template's entity page from the template cards. Right now there is only a direct link to the owner and to any links on the template entity, but not to the entity page itself. 

### 🎤 Context

In my use-case we generally have additional information in template entity pages that go above and beyond just the description (detailed readmes, etc)
Right now, if a user wants to see this additional information, they have to leave the create page and go back to the catalog to open the entity page for the template. It would be nice for them to have the option of going directly from the template card that interested them instead. 

### ✌️ Possible Implementation

This could be implemented a few ways - I was thinking either having the title be a clickable link on the card that takes you to the entity page, or to include an additional link in the footer around where the owner link is, something like that. Would be interested to hear other ideas though - I don't think it matters too much to me as long as it's easy to get from the template card to the template entity page.

I'm willing to submit a PR for this, though it might not be super timely depending on other work that comes up. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ltdonner-bah** [comment]
unstale please

**Comment by benjdlambert** [comment]
@ltdonner-bah what's the use case here? Wondering how valuable this would be to others. We've done something similar but to link to the template source code internally instead. We did this by providing our own implementation of `TemplateCard` to the `ScaffolderPlugin` so that could be an option for you if it's a special use case.

**Comment by ltdonner-bah** [comment]
We had something similar at one point where we had a custom card that linked to both the source code and also to the entity page, but we liked your designs better for other things. Basically the use case would be for anybody thinking of using a template having an easy way to get more information before continuing. 

For example, we show stuff like the README, GitHub repo info so users can know how often things are updated, GitHub issues, etc on our template entity pages, which could be useful to users if they're evaluating whether or not they want to use a template to start a project. Eventually if we can get Soundcheck, that would be another thing on the entity page that gives a user information about the maturity of the template before they waste any time with it. So without cluttering the card, it would be nice if a user had an easy way to get to the template's entity page from the create page to read up on things before launching the template without having to go back to the catalog, change the kind drop-down, then search for the template they're looking into, that kind of thing.

**Comment by acierto** [comment]
I can relate to this, I do this also when checking if template changes were really picked up or not. 
In some cases I witnessed a behaviour when template stopped updating, I had to unregister it to get a fresh version.
Didn't debug though what reason leads to template not being picked up by system anymore.

**Comment by ltdonner-bah** [comment]
Oops I didn't mean to let the stalebot kill this

**Comment by awanlin** [comment]
I'm pretty sure this was added by: https://github.com/backstage/backstage/pull/29274 and that was included in the `1.38.0` release. You can see it in action in the Backstage Demo site here: https://demo.backstage.io/create?filters%5Bkind%5D=template&filters%5Buser%5D=all&limit=20

**Comment by ltdonner-bah** [comment]
Yep you're right sorry I forgot to revisit this. It's great, thank you!

**Comment by awanlin** [comment]
No worries, this just came across my radar and I figured I'd mention it 👍
