### ISSUE TITLE
🐛 Bug Report: getAllTeams() in plugin-azure-devops-backend is capped at 100 teams

### ISSUE THREAD

**Issue by QuadmanSWE** [backstage/backstage#23533]
### 📜 Description

When importing @backstage/plugin-azure-devops-backend, if the account for your token has access to more than 100 teams, the function getAllTeams() can only return 100 because it is the default in the API from Microsoft unless you specify the $top parameter.

Relevant discussion on stackoverflow: https://stackoverflow.com/questions/59932094/azure-devops-rest-api-call-retrieving-only-100-records

The issue could be solved by adding an optional argument for "top" here: https://github.com/backstage/backstage/blob/master/plugins/azure-devops-backend/src/api/AzureDevOpsApi.ts#L390

### 👍 Expected behavior

Return as many teams as I want. When building my provider that references plugin-azure-devops-backend I want to be able to insert the max number of records instead of it always being 100.

### 👎 Actual Behavior with Screenshots

I am limited to at most 100 teams.

### 👟 Reproduction steps

Set up an Azure Devops organization with two or more projects. Add less than 100 teams to the first and more to the other to bring the total over 100. Create a user in Azure Devops with access only to the first project. Implement a catalog provider that uses getAllTeams() to populate the catalog with groups. Your catalog will now have all the teams of the first project.

Add access to the account to the second project and now no more than 100 teams split amongst the two project will show up in backstage.

To get around the issue we forked the plugin and added the top argument, resulting in us being able to pull more than 100 teams.

### 📃 Provide the context for the Bug.

We are using azure devops as a source of groups for backstage which we refer to as teams. We ran into issues when onboarding more regions and bringing on more teams.
When debugging the provider we build which uses the plugin-azure-devops-backend for its nice azure devops api implementation we found that we got exactly 100 teams back before our internal filtering. This lead to a lot of teams that existed before we started bringing in more regions.

The lack of the top parameter is not, to my knowledge at least, affecting the performance of any frontend plugin provided from backstage. Other parts of this backend plugin are using the top parameter for other things like pullrequestdashboard options.

It is how ever affecting us in the way we can support our internal azure devops teams provider, since it is relying on the backend plugin for the API tooling.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by QuadmanSWE** [comment]
I have written some code that fixes our issue. I will submit a PR from my fork during the weekend.

**Comment by awanlin** [comment]
Hi @QuadmanSWE, to be clear this API was created to support the Pull Request Dashboard and you are using for something entirely different. I do think having this as a prop for the Pull Request Dashboard seems reasonable but any PR making this change should include the needed frontend changes to make that work and not simply the backend. I think that's pretty reasonable to me - win/win. 👍 

@marleypowell any additional thoughts on this?

**Comment by QuadmanSWE** [comment]
I had a feeling you would say that. I fully intend to do so. Should the "I expect at most this number of teams to exist in my org" have a good name and be part of the config as optional?

**Comment by awanlin** [comment]
Thanks! I haven't look too closely at the code so `top` or `topTeams` would work. This doesn't need to be in the config. It would just be an optional prop from the frontend to the back, if it's not provided then the current default would apply.

**Comment by QuadmanSWE** [comment]
I was a bit puzzled about exactly how the front end and backend coordinate for the pullrequestdashboard provider. It seams to me right now that populating which teams exist in azure devops is left to chance. I settled on making it deterministic if you don't use the topTeams parameter and set it to 100. What worries me the most is that if you cache it into its private teams variable it doesn't ever refresh (no proper cache on the backend, just a private variable). So if you have only 5 teams and you create one you need to restart backstage for it to take effect in your plugin the way I understand it. I caught this while trying to understand why it would only use my topTeams parameter once and then return those same teams even if I raised the number.

Perhaps there is some more work to do with this but I think it is outside the scope for what I am experiencing.

Looking forward for a discussion on that and some feedback on the work @awanlin . Thanks in advance :)
