### ISSUE TITLE
🐛 Bug Report: <title> Link for using Kairos and using templates to escalate permissions is broken

### ISSUE THREAD

**Issue by anzb-cg** [backstage/backstage#23590]
### 📜 Description

On this page:
https://devhub.capgroup.com/docs/default/component/building-cloud-apps/banzai-quick-start-guide/
There is this section:
1. Provisioning Banzai Pipeline Account

that refers to using Kairos or accessing Kairos.  It points to this link:
(https://devhub.capgroup.com/docs/guides/cloud/new-cloud-app/banzai-pipeline-overview#banzai-pipeline-lifecycle-accounts)
but that link doesn't seem to be available.

In fact, the whole banzai-pipeline-overview is missing.  I know Helix is coming, but until then people might still want to use Banzai while they wait to convert to Helix.

### 👍 Expected behavior

The link should work.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/108835480/9c548df9-d6b6-470d-9ed9-01e15738596d)

### 👟 Reproduction steps

Here is a view of the page:
![image](https://github.com/backstage/backstage/assets/108835480/7bcc42c4-057b-4421-8a0b-5bce6acc1356)

Clicking on Kairos shows the broken link.

### 📃 Provide the context for the Bug.

I'm trying to follow/read through the Banzai steps so we can setup our AWS presence while we are waiting for Helix to happen.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hi @anzb-cg 👋🏻, is this open source? It appears that the links shared in the description are private.
