### ISSUE TITLE
🐛 Bug Report: P-Limit Deadlock

### ISSUE THREAD

**Issue by gaborando** [backstage/backstage#23633]
### 📜 Description

When I've to fetch more than five secrets with nested data a deadlock occurs.

### 👍 Expected behavior

Resole all the promises without a nested blocking call.

### 👎 Actual Behavior with Screenshots

Try to use a vault path that contains more than five nested secrets, the call remains pending.

### 👟 Reproduction steps

1. Create 10 kv secrets on vault like:
- secrets/foo/bar/s1
- secrets/foo/bar/s2
- secrets/foo/bar/s3
- secrets/foo/bar/s4
- secrets/foo/bar/s5
- secrets/foo/bar/s6

Inside a configuration for a component add:

  annotations:
    vault.io/secrets-path: 'foo'

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by gaborando** [comment]
The error comes form this variable:

https://github.com/backstage/backstage/blob/69d32eb3477d9f19f2c39b435164f692dd71f3f0/plugins/vault-backend/src/service/vaultApi.ts#L90

```js
export class VaultClient implements VaultApi {
  private vaultConfig: VaultConfig;
  private readonly limit = plimit(5); // <-- You've inserted a semaphore of 5 elements

  constructor(options: { config: Config }) {
    this.vaultConfig = getVaultConfig(options.config);
  }
```

Then in this line:

https://github.com/backstage/backstage/blob/69d32eb3477d9f19f2c39b435164f692dd71f3f0/plugins/vault-backend/src/service/vaultApi.ts#L140

you call the limit function decrement the semaphre, but this method calls himself at this line:

https://github.com/backstage/backstage/blob/69d32eb3477d9f19f2c39b435164f692dd71f3f0/plugins/vault-backend/src/service/vaultApi.ts#L151

an it is wrapped in the same limit function.

If the stack call is greater than 5 you reach a deadlock.

```js
  async listSecrets(
    secretPath: string,
    options?: {
      secretEngine?: string;
    },
  ): Promise<VaultSecret[]> {
    const mount = options?.secretEngine || this.vaultConfig.secretEngine;

    const listUrl =
      this.vaultConfig.kvVersion === 2
        ? `v1/${encodeURIComponent(mount)}/metadata/${secretPath}`
        : `v1/${encodeURIComponent(mount)}/${secretPath}`;
    const result = await this.limit(() => // <-- LIMIT CALL
      this.callApi<VaultSecretList>(listUrl, { list: true }),
    );

    const secrets: VaultSecret[] = [];

    await Promise.all(
      result.data.keys.map(async secret => {
        if (secret.endsWith('/')) {
          secrets.push(
            ...(await this.limit(() =>
              this.listSecrets(`${secretPath}/${secret.slice(0, -1)}`, { //  <-- Recursive call inside an other limit
                secretEngine: mount,
              }),
            )),
          );
        }
```

## Possible solution: Avoid the Semaphore and do all calls sequentially:

```js
    async listSecrets(
        secretPath: string,
        options?: {
            secretEngine?: string;
        },
    ): Promise<VaultSecret[]> {
        const mount = options?.secretEngine || this.vaultConfig.secretEngine;

        const listUrl =
            this.vaultConfig.kvVersion === 2
                ? `v1/${encodeURIComponent(mount)}/metadata/${secretPath}`
                : `v1/${encodeURIComponent(mount)}/${secretPath}`;
        const result = await this.callApi<VaultSecretList>(listUrl, {list: true})

        const secrets: VaultSecret[] = [];

        for (const secret of result.data.keys) {
            if (secret.endsWith('/')) {
                secrets.push(
                    ...(await this.listSecrets(`${secretPath}/${secret.slice(0, -1)}`, {
                        secretEngine: mount,
                    }))
                );
            } else {
                const vaultUrl =
                    this.vaultConfig.publicUrl || this.vaultConfig.baseUrl;
                secrets.push({
                    name: secret,
                    path: secretPath,
                    editUrl: `${vaultUrl}/ui/vault/secrets/${encodeURIComponent(
                        mount,
                    )}/edit/${secretPath}/${secret}`,
                    showUrl: `${vaultUrl}/ui/vault/secrets/${encodeURIComponent(
                        mount,
                    )}/show/${secretPath}/${secret}`,
                });
            }
        }


      return secrets;
    }
```
I've adopted this solution cause fits my purpose, so let me know your generic way.

**Comment by freben** [comment]
Hi! Would you like to contribute a fix for that?

Honestly I think we can just remove the limit inside the `Promise.all`. The point of the limit was to not have too many concurrent outbound API calls to Vault. And that's already achieved by the first occurrence of the limit

**Comment by gaborando** [comment]
Yea, thath should be fine

**Comment by benjdlambert** [comment]
Closing as fixed
