### ISSUE TITLE
🚀 Feature: Change Linked Column in CloudBuild Plugin's Table View from SOURCE to BUILD

### ISSUE THREAD

**Issue by ishikawa-pro** [backstage/backstage#23697]
### 🔖 Feature description

I am currently utilizing the CloudBuild Plugin and would like to propose a modification to its Table View. Specifically, I want to change the column that serves as a hyperlink from SOURCE to BUILD.

### 🎤 Context

As it stands, in the CloudBuild Plugin's WorkflowRunsTable, the SOURCE column contains hyperlinks that, when clicked, navigate to the details of the respective build.
While this functionality is useful, I believe it would be more appropriate and intuitive if the BUILD column were linked instead. 
The rationale behind this suggestion is that the BUILD column directly represents the build ID of the workflow. Enabling hyperlinks on the build ID would offer a more natural way to access detailed information about the build by clicking on it.

current
<img width="1196" alt="image" src="https://github.com/backstage/backstage/assets/12871716/6f0ce336-dbc3-4efc-b0c6-60841b258774">

ideal
<img width="1204" alt="image" src="https://github.com/backstage/backstage/assets/12871716/e2c979ad-be0f-4914-bca0-9ad873a2a263">

### ✌️ Possible Implementation

Currently, the hyperlink is set here:
https://github.com/backstage/backstage/blob/master/plugins/cloudbuild/src/components/WorkflowRunsTable/WorkflowRunsTable.tsx#L62-L72

I want to change it so that the hyperlink is set to this colum instead:
https://github.com/backstage/backstage/blob/master/plugins/cloudbuild/src/components/WorkflowRunsTable/WorkflowRunsTable.tsx#L51-L55

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Thanks for the suggestion, we appreciate your help in submitting a PR 🙂

**Comment by ishikawa-pro** [comment]
I'm closing this issue, because I complated this change.
thank you!
