### ISSUE TITLE
🐛 Bug Report: `useRouteRef` from `frontend-plugin-api` doesn't respect subpaths in `app.baseUrl`

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#23709]
### 📜 Description

Plugins that leverage `useRouteRef()` in `app-next` to resolve the path to a plugin ultimately resolve to a path that _includes_ subpaths set in `app.baseUrl`, whereas they should be returning paths _relative_ to `app.baseUrl`.

### 👍 Expected behavior

Route functions called from `useRouteRef()` in the `@backstage/frontend-plugin-api` should resolve to paths relative to the full `app.baseUrl` config.

### 👎 Actual Behavior with Screenshots

Such route functions resolve to a path that _contains_ the path part defined in `app.baseUrl`.

### 👟 Reproduction steps

1. Update the `app.baseUrl` config at the root to something like `http://localhost:3000/subpath`
2. Run `yarn dev:next`
3. Click the `Catalog` menu item

**Expected**: you should be navigated to the Catalog plugin page.
**Actual**: You're navigated to a `404` with path `/subpath/subpath/catalog`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by iamEAP** [comment]
It's reproducible in this repo. `yarn why react-router` shows `6.8.1`.

I have a suspicion this is more related to the diverging implementations of `RouteResolver.resolve` in [`frontend-app-api`](https://github.com/backstage/backstage/blob/bc621aa/packages/frontend-app-api/src/routing/RouteResolver.ts#L194) vs. [`core-app-api`](https://github.com/backstage/backstage/blob/c9d9bfe/packages/core-app-api/src/routing/RouteResolver.ts#L184) though.

**Comment by aramissennyeydd** [comment]
Ah, it's a new frontend issue, missed that initially. Not able to replicate the behavior in the old frontend, which I think gives weight to your theory.
