### ISSUE TITLE
🚀 Feature: Default filters in catalog index page

### ISSUE THREAD

**Issue by QuadmanSWE** [backstage/backstage#23710]
### 🔖 Feature description

There should be a way to configure the catalog index page so that for every kind you have a default filter applied in the url when you change which kind to view.

### 🎤 Context

When I click on Catalog in the menu on the left, it brings me to the route /catalog and I get redirected to /catalog?filters[kind]=component&filters[user]=owned

This is great, it allows me to filter by components that matter to me.

However when browsing the catalog there might be other kinds which you oftentimes want to create default filters for.

For example when changing to browsing templates, we would want to filter by default for templates tagged with golden-path.

![image](https://github.com/backstage/backstage/assets/8070109/a7caa009-9479-404f-9e2a-4251f54df2e7)

Or when browsing groups we want to filter by default by the type "team" which is our way of identifying which collection of people are part of the agile release train as agile teams.

![image](https://github.com/backstage/backstage/assets/8070109/9e28ae3e-a60a-4226-9a87-e1534b3f761e)

In our case our catalog is filled with groups through a provider which gives a bit of extra stuff that is irrelevant in most contexts but we are using the backstage catalog as a tool to get an overview of that and working with cleaning it up, so some stakeholders need it.

We would like to be able to define a default filter for groups. Set a certain tag or use the type=team so that when someone browses the groups in the catalog the non-relevant groups are by default hidden.

### ✌️ Possible Implementation

Allow the catalog index page to set optional default filters per kind via props.

Be able to specify those filter props when creating the routes in app.tsx
Be able to specify those filter props through app-config.yaml under something like catalog.kindDefaultFilters

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by hntrdglss** [comment]
Hey @QuadmanSWE! Thanks for submitting this request! We've added to our backlog in Spotify, but don't currently have the capacity to pick up. If you or anyone in the community are able to contribute to a PR in the meantime, please do! Feel free to add as a discussion topic in the [Catalog SIG agenda](https://docs.google.com/document/d/1xg57CDfX2R5jTGbbWANzifm2szEb664kuTwfEEvKgZU), too.

**Comment by QuadmanSWE** [comment]
> Hey @QuadmanSWE! Thanks for submitting this request! We've added to our backlog in Spotify, but don't currently have the capacity to pick up. If you or anyone in the community are able to contribute to a PR in the meantime, please do! Feel free to add as a discussion topic in the [Catalog SIG agenda](https://docs.google.com/document/d/1xg57CDfX2R5jTGbbWANzifm2szEb664kuTwfEEvKgZU), too.

This was brought up during the last catalog SIG and the outcome was that we registered this feature request. I can get started though.
