### ISSUE TITLE
🐛 Bug Report: TechDocs Preview is broken in 1.8.6 (1.24.0)

### ISSUE THREAD

**Issue by kunickiaj** [backstage/backstage#23726]
### 📜 Description

When running `npx @techdocs/cli serve` with version 1.8.6 TechDocs are always 404 I think due to an auth issue.
Older versions like 1.8.1 work fine. Running `npx @techdocs/clil serve:mkdocs` with version 1.8.6 works correctly.

### 👍 Expected behavior

Show TechDocs preview

### 👎 Actual Behavior with Screenshots

Shows a 404.
<img width="712" alt="Screenshot 2024-03-20 at 10 49 42 AM" src="https://github.com/backstage/backstage/assets/746474/878dae09-2192-4191-9b47-12a9394da08d">
<img width="1209" alt="Screenshot 2024-03-20 at 10 50 12 AM" src="https://github.com/backstage/backstage/assets/746474/22e08aea-528a-42da-a2ca-ec35ad25369b">

### 👟 Reproduction steps

`npx @techdocs/cli serve` for any techdocs.

### 🖥️ Your Environment

macOS M1 Max
TechDocs CLI 1.8.6

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Closing as a duplicate of #24452, which is now fixed
