### ISSUE TITLE
🐛 Bug Report: Software Templates hero video missing

### ISSUE THREAD

**Issue by sparecycles** [backstage/backstage#23723]
### 📜 Description

the video asset at the top of https://backstage.io/docs/features/software-templates/  is a 404 today.

https://github.com/backstage/backstage/blob/8cc47df993c7cd45eb4d55e8b763f144bcd44c64/docs/features/software-templates/index.md#L9-L16

<img width="879" alt="image" src="https://github.com/backstage/backstage/assets/719818/5feec89a-4d6b-45da-9b2f-bfc48c5fa93b">

### 👍 Expected behavior

a video! (or removed it!)

## Chrome
<img width="923" alt="image" src="https://github.com/backstage/backstage/assets/719818/55dbb160-e956-407f-bcf4-83acc08b32bf">

## Firefox
<img width="1181" alt="image" src="https://github.com/backstage/backstage/assets/719818/3c8b7394-92ec-4d80-8ecb-cb14deabc27b">

### 👟 Reproduction steps

1. click https://backstage.io/docs/features/software-templates/ 
2. look

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Interesting, the file still exists here: https://github.com/backstage/backstage/blob/master/microsite/blog/assets/2020-08-05/feature.mp4

I'm wondering if something in the deployment of the microsite went sideways and deleted it 🤔

**Comment by tico88612** [comment]
https://backstage.io/blog/2020/08/05/announcing-backstage-software-templates/

Also, this page has the same problem.

But I can fix it. Could you assign it to me?

**Comment by freben** [comment]
assigned.

**Comment by sparecycles** [comment]
Yay!

BTW a quick pass with something like
```
ffmpeg -i feature.mp4 -preset veryslow -tune animation feature-ff.mp4
```
makes a video of similar looking quality that's 1.8MB instead of 11.8MB. (I am very far from an expert here).

https://github.com/backstage/backstage/assets/719818/7e5bc03b-8e64-44ee-afa5-f554c5ba58eb

**Comment by tico88612** [comment]
Thanks @sparecycles 
@freben @awanlin, Should I replace this file?
