### ISSUE TITLE
🐛 Bug Report: scaffolder-backend tasklogger does not respect log format

### ISSUE THREAD

**Issue by tstollin** [backstage/backstage#23755]
### 📜 Description

After updating our Backstage to 1.24.0 we noticed that the scaffolder task logs are also included in the application logs. ([Commit](https://github.com/backstage/backstage/commit/f02e445cf52478e09c5742b2d3420dc16cc60732#diff-30eabd978c6d9838c6e26de4af50fce58cc70f1a75b1b577e27b19239db9109aR122))

Unfortunately, these new logs are not respecting the log format configured in our coreServices rootLogger.

In our company environment, we are required to create logs in ECS format. Hence, we provide a custom service factory for the coreServices.rootLogger where we create a WinstonLogger using the @elastic/ecs-winston-format. 

### 👍 Expected behavior

The log format of the coreServices.rootLogger configured by creating a custom service factory should be respected by the logging created during the execution of task in the scaffolder-backend.

### 👎 Actual Behavior with Screenshots

The task logs are part of our application logs, but they have a plain console format instead of the required ECS format.

![image](https://github.com/backstage/backstage/assets/84318361/944664e3-73db-4119-a32c-704edf5964c4)

### 👟 Reproduction steps

1. change coreServices.rootLogger log format to a different format with a custom service factory:

``` 
import { coreServices, createServiceFactory } from '@backstage/backend-plugin-api';
import { WinstonLogger } from '@backstage/backend-app-api';
import { transports } from 'winston';
import { ecsFormat } from '@elastic/ecs-winston-format';

export default createServiceFactory({
  service: coreServices.rootLogger,
  deps: { config: coreServices.rootConfig },
  factory() {
    return WinstonLogger.create({
      format: ecsFormat(),
      level: process.env.LOG_LEVEL ?? 'info',
      transports: [new transports.Console()],
    });
  },
});
```

2. start some scaffolding task and check logs

### 📃 Provide the context for the Bug.

suspected responsible code: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts#L113-L123

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
Thanks for raising this!

Yep, so I I'm thinking of a few things here.

We explicitly call `WinstonLogger.create` in the `scaffolder-backend` when creating tasks, I wonder if we should actually be calling `logger.child` from the logger that gets passed from the backend system.

Another option that I was thinking about is that we just ditch logging to the `console` totally for tasks related things, and only log to the console when there's an error. This would pretty much fix all of your issues as you should only see the logs from the `TaskBroker` which should already use a logger that's a child of the plugin logger.

Mostly leaning towards the second to be honest, thoughts?

**Comment by tstollin** [comment]
Thank you for having a look at it and for giving your ideas. 

I would prefer the first approach because this would enable us to use our warn/error-based alerts to work for problems occurring during task executions. We are currently employing a lot of custom actions where we are dependent on our users telling us about problems or failed tasks and then search the logs manually. Having access to the action logs in the application logs would be way easier because we would be able to use our log infrastructure.

The second approach seems to be a revert to the state before 1.24.0 where the task logs were exclusively accessible via the task view.
