### ISSUE TITLE
View docs on backstage

### ISSUE THREAD

**Issue by abhinavsgaikwad93** [backstage/backstage#23775]
### 📜 Description

I am unable to understand how to add documents in the Docs tab on Backstage. 

My documents are stored in Azure Repo. For testing purpose, i created a git repo and created a docs folder with index.md file and stored the contents of the document i need to view on Backstage.

Can someone please share the steps on how to do this?

### 👍 Expected behavior

Docs should be visible on Docs tab

### 👎 Actual Behavior with Screenshots

NA

### 👟 Reproduction steps

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by abhinavsgaikwad93** [comment]
@camilaibs  - Do you know anything about this ? :)

**Comment by camilaibs** [comment]
Just to confirm, are you trying to use the `TechDocs` plugin? If so, this would be the getting started guide 🙂 : https://backstage.io/docs/features/techdocs/getting-started
