### ISSUE TITLE
🐛 Bug Report:  Backstage cannot read Resource Entities from database intermittently

### ISSUE THREAD

**Issue by bruno-watt-wcq** [backstage/backstage#23783]
### 📜 Description

Now that we have moved into production we have an issue that occasionally comes up in local dev but happening all the time now. Originally it happened with a component we might look up. Now its only Resources.

Every few hours we need to kick the Backstage backend server as we start getting these errors when we navigate to one of two tabs we have created under the Resource page:
```
error FetchError: invalid json response body at http://localhost:7007/api/catalog/entities/by-query?filter=kind%3DResource%2Cmetadata.name%3Denv-prod reason: Unexpected token U in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async assembleHoistingPayload (/app/plugins/environment-management-backend/dist/index.cjs.js:264:37)
    at async /app/plugins/environment-management-backend/dist/index.cjs.js:323:39 {
  type: 'invalid-json'
}
```

We intiially assumed as this happened once every few weeks in local dev it was just a cluster thing with the DB. But now that we are in prod its happening all the time and to fix it we restart the backend. We don't need to change anything in the DB (the records that bckstage errors on are perfectly fine JSON. 

Once we restart the backend the whole thing is ok again for a few hours.

Is there any reason that the backend just starts getting JSON errors while talking to the db?

### 👍 Expected behavior

Present this form

<img width="1535" alt="Screenshot 2024-03-22 at 9 47 47 AM" src="https://github.com/backstage/backstage/assets/135942633/70259c2e-42ef-4816-90b5-ca1cfc2d9726">

### 👎 Actual Behavior with Screenshots

404's as per the error:

```
error FetchError: invalid json response body at http://localhost:7007/api/catalog/entities/by-query?filter=kind%3DResource%2Cmetadata.name%3Denv-prod reason: Unexpected token U in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async assembleHoistingPayload (/app/plugins/environment-management-backend/dist/index.cjs.js:264:37)
    at async /app/plugins/environment-management-backend/dist/index.cjs.js:323:39 {
  type: 'invalid-json'
}
```

### 👟 Reproduction steps

Run backstage. Go to Resource, go to the tab we created. It'll present fine most of the time, then it will start 404ing and we will need to reboot the backend service. This is happening in hours now not months.

### 📃 Provide the context for the Bug.

Manage our environments with backstage.

### 🖥️ Your Environment

OS:   Darwin 23.4.0 - darwin/arm64
node: v18.19.1
yarn: 4.1.1
cli:  0.25.2 (installed)
backstage:  1.23.4

Dependencies:
  @backstage/app-defaults                                          1.5.0
  @backstage/backend-app-api                                       0.5.14
  @backstage/backend-common                                        0.21.3
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.6
  @backstage/backend-plugin-api                                    0.6.13
  @backstage/backend-tasks                                         0.5.18
  @backstage/catalog-client                                        1.6.0
  @backstage/catalog-model                                         1.4.4
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.3
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.6.2
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.12.0
  @backstage/core-compat-api                                       0.2.0
  @backstage/core-components                                       0.14.0
  @backstage/core-plugin-api                                       1.9.0
  @backstage/dev-utils                                             1.0.27
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.5
  @backstage/frontend-plugin-api                                   0.6.0
  @backstage/integration-aws-node                                  0.1.9
  @backstage/integration-react                                     1.1.24
  @backstage/integration                                           1.9.0
  @backstage/plugin-api-docs                                       0.11.0
  @backstage/plugin-app-backend                                    0.3.61
  @backstage/plugin-app-node                                       0.1.13
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.8
  @backstage/plugin-auth-backend-module-github-provider            0.1.10
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.10
  @backstage/plugin-auth-backend-module-google-provider            0.1.10
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.8
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.10
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.6
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.6
  @backstage/plugin-auth-backend                                   0.21.3
  @backstage/plugin-auth-node                                      0.4.8
  @backstage/plugin-badges-backend                                 0.3.10
  @backstage/plugin-badges                                         0.2.54
  @backstage/plugin-catalog-backend-module-github                  0.5.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.10
  @backstage/plugin-catalog-backend                                1.17.3
  @backstage/plugin-catalog-common                                 1.0.21
  @backstage/plugin-catalog-graph                                  0.4.0
  @backstage/plugin-catalog-import                                 0.10.6
  @backstage/plugin-catalog-node                                   1.7.3
  @backstage/plugin-catalog-react                                  1.10.0
  @backstage/plugin-catalog                                        1.17.0
  @backstage/plugin-code-coverage                                  0.2.23
  @backstage/plugin-events-node                                    0.2.22
  @backstage/plugin-github-actions                                 0.6.11
  @backstage/plugin-github-pull-requests-board                     0.1.24
  @backstage/plugin-home-react                                     0.1.8
  @backstage/plugin-kafka                                          0.3.30
  @backstage/plugin-kubernetes-common                              0.7.4
  @backstage/plugin-kubernetes-react                               0.3.0
  @backstage/plugin-kubernetes                                     0.11.5
  @backstage/plugin-org                                            0.6.20
  @backstage/plugin-permission-backend                             0.5.36
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.24
  @backstage/plugin-permission-react                               0.4.20
  @backstage/plugin-playlist-common                                0.1.14
  @backstage/plugin-playlist                                       0.2.4
  @backstage/plugin-proxy-backend                                  0.4.11
  @backstage/plugin-scaffolder-backend-module-azure                0.1.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.3
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.5
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.3
  @backstage/plugin-scaffolder-backend-module-github               0.2.3
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.16
  @backstage/plugin-scaffolder-backend                             1.21.3
  @backstage/plugin-scaffolder-common                              1.5.0
  @backstage/plugin-scaffolder-node                                0.3.3
  @backstage/plugin-scaffolder-react                               1.8.0
  @backstage/plugin-scaffolder                                     1.18.0
  @backstage/plugin-search-backend-module-catalog                  0.1.17
  @backstage/plugin-search-backend-module-pg                       0.5.22
  @backstage/plugin-search-backend-module-techdocs                 0.1.17
  @backstage/plugin-search-backend-node                            1.2.17
  @backstage/plugin-search-backend                                 1.5.3
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.6
  @backstage/plugin-search                                         1.4.6
  @backstage/plugin-tech-radar                                     0.6.13
  @backstage/plugin-techdocs-backend                               1.9.6
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.5
  @backstage/plugin-techdocs-node                                  1.11.5
  @backstage/plugin-techdocs-react                                 1.1.16
  @backstage/plugin-techdocs                                       1.10.0
  @backstage/plugin-user-settings                                  0.8.1
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.6.3
  @backstage/test-utils                                            1.5.0
  @backstage/theme                                                 0.5.1
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

(managed to make it happen locally by letting backstage run overnight).

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
This sounds like perhaps the server is running out of memory or something like that. It would be interesting to see what it _actually_ responds with, instead of just that `Unexpected token U in JSON`. It's in position 0, which tells me that the server most likely responded with a text string like `Unable to ...` or `Unexpected ...` etc.

Is there anything of interest in the backend logs? Or in any system metrics, if you have any?

**Comment by bruno-watt-wcq** [comment]
<facepalm> 🤣...thats....lol thats a good point I didn't even bother playing around with the resources assigned to backstage in prod (we use a templated catalog with low defaults). Threes nothing else in the server side logs but this does ring true to me. I'm going to up some resources and let it run a few days.

Definitely down for that lil hack, I'm gonna let it play for a day or two and maybe have a fiddle around in there.

Thanks bud I'm going to close this out now and will reopen if giving some decent resources and my dive doesnt help.

**Comment by freben** [comment]
Are you using the same database for development and production? That is definitely not advisable. You'll get data collisions.

`Fast insert path failed` is not a problem in and of itself, it just notes that it failed to do the fast bulk insert (probably due to data collisions = unique constraint violations) so it did the vastly slower item-by-item inserts instead to try to get as much data as possible in. But it may be caused by misconfiguration as per below.

Some notes on entity providers:

- Those IDs are extremely important and must _never change_. Every provider must have a unique ID. When they send data to the catalog, it ends up in a "bucket" with that ID. If you change the ID, it will dutifully start putting data into a new bucket with that new ID, and immediately get collisions with all of the old data that already existed since before the ID change.
- Entity refs (kind + namespace + name, e.g. `component:default/my-component`) must be globally unique. If several sources try to insert entities that have colliding refs, the first one wins and all of the other sources will fail hard, with uniqueness constraint errors rejecting their attempts to store data

I'd take a look at the providers and checking that they don't try to ingest conflicting data. I'd point development and production at entirely different database instances. And possibly cleaning up the production db if it's now ended up in a complex state where there's a lot of lingering data to clean up

**Comment by bruno-watt-wcq** [comment]
No that's not what I'm saying, all our environments are isolated. 

I'm saying we pass the values in at build time, so the config file for each (as above) is consistent, in dev it just gets the dev values and prod it gets the prod values and on desktop desktop values.

The ID's don't change. As we only (seem) to need one and the environment changes at build time it seems(?) safe to not have two of them. they can have the same ID in different environments.

So yeah, we have all that. There aren't conflicts.

**The real question I was asking here is about if I really need that pair of Providers (the default one and the org one). My reading of the docs overnight led me to believe again the `GithubOrgEntityProvider` is only useful for users and groups. This seems to be supported by the fact we only ingest the users and groups if we drop the `GithubOrgEntityProvider`. Is this incorrect?**

This feels like it (could) be leading to what you are describing with uniqueness. Though ive not seen anything in the logs about rejection of data storage. I'll dig through some more logs tonight.

**Comment by vinzscam** [comment]
> The real question I was asking here is about if I really need that pair of Providers (the default one and the org one). My reading of the docs overnight led me to believe again the GithubOrgEntityProvider is only useful for users and groups. This seems to be supported by the fact we only ingest the users and groups if we drop the GithubOrgEntityProvider

could it be that you have `catalog-info.yaml` representing organizational data? Those are also ingested by `GithubEntityProvider`?
