### ISSUE TITLE
🐛 Bug Report: Failed to change Catalog Kind and Type labels color

### ISSUE THREAD

**Issue by echalegre** [backstage/backstage#23826]
### 📜 Description

I'm trying change Kind and Type label  color in /catalog, but only color defined at palette is showed.

### 👍 Expected behavior

Labels with color defined in my code

### 👎 Actual Behavior with Screenshots

Labels with color defined by palette light or dark

### 👟 Reproduction steps

Create a theme a file:

> packages/app/src/theme/myTheme.ts

Use the bellow code:

```typescript
import {
  createBaseThemeOptions,
  createUnifiedTheme,
  palettes,
} from '@backstage/theme';

export const myTheme = createUnifiedTheme({
  ...createBaseThemeOptions({
    palette: {
      ...palettes.dark,
      primary: {
        main: '#fffff',
      },
      secondary: {
        main: '#565a6e',
      },
      error: {
        main: '#8c4351',
      },
      warning: {
        main: '#8f5e15',
      },
      info: {
        main: '#34548a',
      },
      success: {
        main: '#485e30',
      },
      banner: {
        info: '#34548a',
        error: '#8c4351',
        text: '#343b58',
        link: '#565a6e',
      },
      background: {
        default: '#000b17',
        paper: '#000b17',
      },
      errorBackground: '#8c4351',
      warningBackground: '#8f5e15',
      infoBackground: '#343b58',
      navigation: {
        background: '#000f1e',
        indicator: '#8f5e15',
        color: '#d5d6db',
        selectedColor: '#ffffff',
      },
    },
  }),
  defaultPageTheme: 'home',
  fontFamily: 'Work Sans, sans-serif, Arial',
  /* below drives the header colors */
  components: {
    BackstageHeader: {
      styleOverrides: {
        header: {
          backgroundImage: '#000f1e',
        },
        title: {
          color: '#FFFFFF',
        },
      }
    },
    BackstagePage: {
      styleOverrides: {
        root: {
          background: '#000f1e',
        },
      },
    },
  },
});
```

Add to follow code to packages/app/src/App.tsx

```typescript
import {myTheme} from "./theme/myTheme";

const app = createApp({
  apis,
    themes: [
        {
        id: 'my-theme',
        title: 'My Theme',
        variant: 'dark',
        icon: <LightIcon />,
        Provider: ({ children }) => (
            <UnifiedThemeProvider theme={myTheme} children={children} />
        ),
    }],
...

```

Run the code

### 🖥️ Your Environment

yarn run v1.22.21
OS:   Darwin 23.4.0 - darwin/arm64
node: v18.19.0
yarn: 1.22.21
cli:  0.25.2 (installed)
backstage:  1.23.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hi @echalegre, could you share a screenshot of the page whose label color you are trying to change?

**Comment by tudi2d** [comment]
Like you can override the `Backstage...` components, you can also override specific catalog components. For example if you want to override styles the `CatalogReactUserListPicker` (which contains the `PERSONAL` label), you can do it in a similar manner like the demo site did it here: https://github.com/backstage/demo/blob/master/packages/app/src/theme/aperture.ts#L169-L175
