### ISSUE TITLE
🚀 Feature: Add code & documentation to inject signin resolvers using new backend system

### ISSUE THREAD

**Issue by giocolas** [backstage/backstage#23829]
### 🔖 Feature description

The release of version 1.24 made the new backend system mandatory; documentation and example code shown in this link (https://backstage.io/docs/auth/identity-resolver) relates only to the old backend system and not new. It would be interesting to have this documentation also available for the new backend system.

### 🎤 Context

My use case is as follows:
- enabled users are fully managed in used provider (Microsoft in my case)
- users are not necessarily defined as such in the catalog

With old versions this was possible both before the introduction of the new authentication mode and with the new one, since using old backend system it was possible to inject my own signin resolver.
While with new backend system it is no longer possible, in particular the affected section is following: https://backstage.io/docs/auth/identity-resolver/#sign-in-without-users-in-the-catalog

### ✌️ Possible Implementation

I have no idea how it could be implemented, but I expect it could be as simple as documented with the old backend system

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hello @giocolas 👋🏻 , is this documentation what you are looking for?
https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin
It is possible to create a resolver that does not depend on the Catalog.

**Comment by giocolas** [comment]
Hi @camilaibs,
I have already read the documentation you indicated, but in any case it's not clear how to proceed in order to inject my own SignInResolver because documentation is available only for old backend system, as I mentioned in my initial request.
Do you mean to say that it's possible to create a function that uses createBackendModule and that only implements adding custom parts?

```ts
export const authModuleMicrosoftProvider = createBackendModule({
  pluginId: 'auth',
  moduleId: 'microsoft-provider', // <- do I have to enter my own personalized name?
  register(reg) {
    reg.registerInit({
      deps: {
        providers: authProvidersExtensionPoint,
      },
      async init({ providers }) {
        providers.registerProvider({ // <- do I have to register my provider?
          providerId: 'microsoft',
          factory: createOAuthProviderFactory({ // <- can I omit this part?
            authenticator: microsoftAuthenticator,
            signInResolverFactories: { // <- is this where I need to implement my part?
              ...microsoftSignInResolvers,
              ...commonSignInResolvers,
            },
          }),
        });
      },
    });
  },
});
```

Thanks!

**Comment by camilaibs** [comment]
@giocolas here is an example:
https://backstage.io/docs/backend-system/building-backends/migrating/#custom-resolver

**Comment by giocolas** [comment]
@camilaibs thanks, I introduced these changes:

new backend module plugin with this code in module.ts:
```ts
import { createBackendModule } from '@backstage/backend-plugin-api';
import {
  authProvidersExtensionPoint,
  createOAuthProviderFactory,
} from '@backstage/plugin-auth-node';
import { microsoftAuthenticator } from '@backstage/plugin-auth-backend-module-microsoft-provider';
import {
  stringifyEntityRef,
  DEFAULT_NAMESPACE,
} from '@backstage/catalog-model';

export const authModuleCustomSigninResolver = createBackendModule({
  pluginId: 'auth',
  moduleId: 'microsoft-provider',
  register(reg) {
    reg.registerInit({
      deps: { providers: authProvidersExtensionPoint },
      async init({ providers }) {
        providers.registerProvider({
          providerId: 'microsoft',
          factory: createOAuthProviderFactory({
            authenticator: microsoftAuthenticator,
            async signInResolver({ profile }, ctx) {
              if (!profile.email) {
                throw new Error(
                  'Login failed, user profile does not contain an email',
                );
              }
              // Split the email into the local part and the domain.
              const [localPart, domain] = profile.email.split('@');
  
              // Next we verify the email domain. It is recommended to include this
              // kind of check if you don't look up the user in an external service.
              if (domain !== 'acme.org') {
                throw new Error(
                  `Login failed, this email ${profile.email} does not belong to the expected domain`,
                );
              }
  
              // By using `stringifyEntityRef` we ensure that the reference is formatted correctly
              const userEntity = stringifyEntityRef({
                kind: 'User',
                name: localPart,
                namespace: DEFAULT_NAMESPACE,
              });
              return ctx.issueToken({
                claims: {
                  sub: userEntity,
                  ent: [userEntity],
                },
              });
            },
          }),          
        });
      },
    });
  },
});
```

this code is a mix of your suggestions and what is indicated in the initial documentation that I mentioned, but which is instead related to the old backend!

Finally I made these changes in the index.ts file included in packages/backend:
```diff
// auth plugin
backend.add(import('@backstage/plugin-auth-backend'));
- backend.add(import('@backstage/plugin-auth-backend-module-microsoft-provider'));
+ backend.add(import('@internal/backstage-plugin-auth-backend-module-custom-signin-resolver'));
```

In this way I solved my use case.
I set up a repository containing the code I used here: https://github.com/giocolas/backstage-microsoft-auth

I'll let you maintainers decide whether it is appropriate to enrich the documentation.
Thanks for all the support!

**Comment by chussenot** [comment]
![image](https://github.com/backstage/backstage/assets/748507/e553747d-4d61-4675-8daa-955c702bfcd1)

You save my day, @giocolas Thx!

**Comment by brunobastosg** [comment]
Hi @giocolas , did your solution work with just this custom module? The reason I'm asking is because I adapted it for Keycloak authentication, but it worked partially. I can login, but can't access the catalog. It fails with error 401.

**Comment by tudi2d** [comment]
does this documentation help: https://backstage.io/docs/backend-system/building-backends/migrating#using-legacy-providers?

**Comment by brunobastosg** [comment]
> does this documentation help: https://backstage.io/docs/backend-system/building-backends/migrating#using-legacy-providers?

I believe this is not the case since the OAuth2 Proxy provider has already been migrated to the new backend system (see https://github.com/backstage/backstage/pull/20685/files)

**Comment by webark** [comment]
@giocolas based on your findings, woudl the best place to do this be an extention point where you just deine the resolver? That seems to be where this kind of thing wants to go. I'm still somewhat new to the backend systme though.

**Comment by freben** [comment]
Note that then, each provider would need to have its own extension point for that purpose, since the types used are different per provider. And you'll probably find that if you do add such extension points, the amount of code to write to inject it into a backend, will turn out to be roughly as much as the existing method of just declaring a provider module instead which uses the exported authenticator. Plus the extra code that the provider writer had to write to make the extension point. And you'll find that after all that, you won't be able to  instantiate multiple providers of the same type anyway (eg one for public github and one for internal github enterprise).

We deemed it not worth the complexity.

However, we are lacking in docs at the moment. Ideally you should have copy-pasteable code for eg "this is how you register the github provider with a custom sign in resolver".

**Comment by webark** [comment]
That makes sense. I'll review the extension point docs and see where they best fit. I was considering using them for something similar, so maybe i'll review the docs and re asses. 

Scaffolder actions are defined through extension points though correct? aren't these facilitating a similar pattern?

**Comment by freben** [comment]
Oh they are in general the perfect pattern for injecting behavior into plugins - scaffolder actions are a case of modules enriching a plugin. Providing sign in resolvers via extension points would be a case of enriching a module from another module though. Different use case, and less often applicable.

Still happens though. For example, the incremental entity provider module that allows its special incremental sources to, in turn, be injected into it.

**Comment by freben** [comment]
Rewriting the docs: https://github.com/backstage/backstage/pull/24154

**Comment by kurtaking** [comment]
Here is the skeleton code for our `@internal/auth-backend-module-custom-okta`. We use a custom sign-in resolver and got things working. Our code is similar to what @giocolas has working in this [comment](https://github.com/backstage/backstage/issues/23829#issuecomment-2019982106).

```ts
export const customAuthModuleOkta = createBackendModule({
  pluginId: 'auth',
  moduleId: 'okta-provider',
  register(env) {
    env.registerInit({
      deps: {
        logger: coreServices.logger,
        config: coreServices.rootConfig,
        providers: authProvidersExtensionPoint,
      },
      async init({ logger, config, providers }) {
        providers.registerProvider({
          providerId: 'okta',
          factory: createOAuthProviderFactory({
            authenticator: oktaAuthenticator,
            signInResolver: async (info, ctx) => {
              // custom logic goes here

              // eventually return something like this
              return ctx.issueToken({
                claims: {
                  sub: stringifyEntityRef(userEntity),
                  ent: ownershipRefs,
                },
              });
            },
          }),
        });
      },
    });
  },
});
```

and then in your `src/backend/index.ts`

```diff
- backend.add(import('@backstage/plugin-auth-backend-module-okta-provider'));
+ backend.add(import('@internal/backstage-plugin-auth-backend-module-custom-okta'));
```

it took a while for me to wrap my head around this so maybe it'll help someone else.

**Comment by freben** [comment]
I'll close this for now, since the docs PR has been merged and there's more provider-specific page updates coming soon too.
