### ISSUE TITLE
🐛 Bug Report: AuthMiddleware is not invalidating the Token on LogOut

### ISSUE THREAD

**Issue by iamdempa** [backstage/backstage#23830]
### 📜 Description

I am using this tutorial -[ https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md]( https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md) for authenticating the API requests. 

Everything works fine until I can still access my backend plugin at `/api/proxy/gitfetch` even after I log out. Here's my `authMiddleware.ts`

I have added a condition `if (req.url.indexOf('entities?filter=spec.profile.email=') == -1) { . . . }` so it won't block the SSO login.

```
function setTokenCookie(
   . . .
}

export const createAuthMiddleware = async (
    config: Config,
    appEnv: PluginEnvironment,
) => {
    const baseUrl = config.getString('backend.baseUrl');
    const secure = baseUrl.startsWith('https://');
    const cookieDomain = new URL(baseUrl).hostname;
    const authMiddleware: RequestHandler = async (
        req: Request,
        res: Response,
        next: NextFunction,
    ) => {
        try {
            if (req.url.indexOf('entities?filter=spec.profile.email=') == -1) {
                const token =
                    getBearerTokenFromAuthorizationHeader(req.headers.authorization) ||
                    (req.cookies?.token as string | undefined);
                if (!token) {
                    res.status(401).send('Hold your horses! This area is like a backstage pass-only concert, and you forgot to RSVP. Access Denied, Shoo! :man_detective::construction:');
                    return;
                }
                try {
                    req.user = await appEnv.identity.getIdentity({ request: req });
                } catch {
                    await appEnv.tokenManager.authenticate(token);
                }
                if (!req.headers.authorization) {
                    // Authorization header may be forwarded by plugin requests
                    req.headers.authorization = `Bearer ${token}`;
                }
                if (token && token !== req.cookies?.token) {
                    setTokenCookie(res, {
                        token,
                        secure,
                        cookieDomain,
                    });
                }
            }
            next();
        } catch (error) {
            res.status(401).send('Stop right there, party crasher! The code says \"no entry,\" and the servers are serious bouncers. Access Denied: Level Expert! :man_dancing::man_gesturing_no:');
        }
    };
    return authMiddleware;
};
```

### 👍 Expected behavior

`/api/proxy/gitfetch` should be **unauthorised** after the user is logged out

### 👎 Actual Behavior with Screenshots

Backend Plugin at `/api/proxy/gitfetch` can still access even after the user is logged out

### 👟 Reproduction steps

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hi @iamdempa 👋🏻, the tutorial you linked has been replaced with this one:
https://backstage.io/docs/tutorials/auth-service-migration
