### ISSUE TITLE
🚀 Feature: github:publish needs allow-update-branch option

### ISSUE THREAD

**Issue by anitakrueger** [backstage/backstage#23834]
### 🔖 Feature description

Currently the github:publish action does not allow to add the allow-update-branch flag. The only way to set this on a repo is either in the UI or via gh cli (`gh repo edit`) after the repo has been published by backstage.

### 🎤 Context

We would like to completely manage our github repository creation via backstage, for that it would be helpful if all the repository features including `allow-update-branch` were supported.

### ✌️ Possible Implementation

I think it will need adding here https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend-module-github/src/actions/github.ts.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by acierto** [comment]
Hey @anitakrueger,
Sounds good! 

Are you willing to submit PR for this feature?
