### ISSUE TITLE
🐛 Bug Report: Unable to see cluster after configuring in app-config

### ISSUE THREAD

**Issue by HarikaManchukonda** [backstage/backstage#23835]
### 📜 Description

Have below configuration for one of our openshift(k8s) clusters
url: https://XXXX
          name: E1 Cluster
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: true
          serviceAccountToken: 'sha*************'

### 👍 Expected behavior

Cluster should be listed.

### 👎 Actual Behavior with Screenshots

Cluster is not listing in the kubernetes tab, sometimes getting unable to verify first certificate error.

### 👟 Reproduction steps

Add cluster config to app-config
Run the app in local.

- Cluster is missing from list if i set NODE_EXTRA_CA_CERTS
-OR
- Getting unable to verify first certificate error with no NODE_EXTRA_CA_CERTS/caData

### 🖥️ Your Environment

backstage running in local

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
cc @backstage/kubernetes-maintainers

**Comment by mclarke47** [comment]
@HarikaManchukonda is this still an issue?
