### ISSUE TITLE
How to enable authorization in Q&A plugin

### ISSUE THREAD

**Issue by Durgakanna** [backstage/backstage#23845]
### 🔖 Summary

How can I restrict some users from editing Q&A created by other users?

### 🌐 Project website (if applicable)

https://github.com/drodil/backstage-plugin-qeta

### ✌️ Context

I want to restrict some action in plugin rather that catalog entity

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Parsifal-M** [comment]
Hey! 👋

You should be able to follow the standard permissions docs to set this up.

And I can see @drodil added permissions you can use here 😁

https://github.com/drodil/backstage-plugin-qeta/blob/main/plugins%2Fqeta-common%2Fsrc%2Fpermissions.ts

Permissions docs: https://backstage.io/docs/permissions/overview/

**Comment by drodil** [comment]
By default, users can only edit their own questions and answers, except for the moderators. Unfortunately, the permissions in Q&A plugin are missing possibility to restrict this in the permission framework (in my long list of TODOs). The permissions framework in Q&A can only be used to restrict who can post new questions and answers overall.

**Comment by vinzscam** [comment]
Closing the issue as the plugin is not part of this repo
