### ISSUE TITLE
🚀 Feature: Allow a user to build a scaffolder template with a two column layout

### ISSUE THREAD

**Issue by jmtingey** [backstage/backstage#23853]
### 🔖 Feature description

Today, when setting up a software template in the scaffolder, the resulting UI displays as one column that runs full width across the page content area. This feature would allow a developer to choose to configure the resulting UI to display in two columns. 
#### Key concepts
- In the second column, different content can be displayed at each stage of the template
- Links can be displayed in the text

![image](https://github.com/backstage/backstage/assets/127445644/b1a1022d-244e-4cd2-be55-31afbddd44f0)

<img width="1166" alt="image" src="https://github.com/backstage/backstage/assets/127445644/cf7345ad-c673-4d3b-93a2-43ce1dfa7bf7">

### 🎤 Context

My team has learned via usability testing and research that a key developer pain point is documentation. They can't find it, it isn't current, it isn't correct, it covers a different version of the software, and so on. The key enhancement this layout provides is the ability to present the documentation right beside the form it pertains to, with links out to more in-depth documentation if desired. This approach also keeps the documentation very close to the code, enabling updates to the documentation when there are updates to the form code.    

While my proposed use case is primarily to allow for documentation to be presented in context, the second column should be flexible enough to allow a developer to put whatever they want in the column. For example, a UX designer may decide that the form can be displayed more efficiently in two columns side-by-side instead of one long column. The second column should support this use case as well.

### ✌️ Possible Implementation

An engineer on my team proposed this could be implemented as an addition to the Scaffolder. My team has agreed to write the contribution if the feature is approved. 

![image](https://github.com/backstage/backstage/assets/127445644/031ae09e-de15-4654-b568-b8d5c9110309)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @jmtingey, have you looked at this? https://backstage.io/docs/features/software-templates/writing-custom-step-layouts

Not sure it's exactly what you are looking for but would be good to know how close it gets.

**Comment by jmtingey** [comment]
Thanks @awanlin. I will ask my engineers to take a look.

**Comment by jmtingey** [comment]
@awanlin, Thanks again for pointing me to the template page documentation. My team has a research spike to see if it will work to implement my design, but they won't get to it until the end of April. I'll close this issue and create a new one if it's required based on the results of their research.
