### ISSUE TITLE
🚀 Feature (kubernetes): Cluster filtering

### ISSUE THREAD

**Issue by magnusp** [backstage/backstage#23857]
### 🔖 Feature description

Provide an extension that can transform the return value of KubernetesClustersSupplier.getClusters.

### 🎤 Context

Currently we have no way to disable clusters returned by KubernetesClustersSupplier.getClusters. Being able to filter out clusters is particularly useful during cluster maintenance with no or partial availability.

### ✌️ Possible Implementation

Looking at the current extension points and how they are used with KubernetesBuilder it seems that we would need an additional builder method to take a filtering function. During KubernetesBuilder.build() we would wrap getClusterSupplier() with a FilteringClusterSupplier:
```ts
const clusterSupplier = new FilteringClusterSupplier(this.getClusterSupplier(), this.getClusterFilterFn());
```
The filtering function would be passed via an extensionpoint - possibly KubernetesClusterSupplierExtensionPoint.

The change should be backward compatible, but does add some debt seeing that we have #17853.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by magnusp** [comment]
Thoughts on this @mclarke47? I think the issue is sufficiently scoped and that I can bite into it straight away. Should I be wary of any future changes?

**Comment by mclarke47** [comment]
@magnusp Wondering how do you think this relates to https://github.com/backstage/backstage/pull/23509?

**Comment by magnusp** [comment]
Processors in combination with `CatalogRelationServiceLocator` could act as a filtering component. That is, the processor would/could add/remove relations to the cluster resource. This would on the other hand not work when passing requests through the proxy as it requests clusters straight from the clustersupplier, with no involvement of servicelocators. This leads us onto `CatalogClusterLocator` which is optimal, except for the limitation that it doesn't support the `serviceAccount` auth provider.

Taking the above into consideration, if `serviceAccount` was a supported auth strategy on `CatalogClusterLocator` then entity processors and providers would act as the filter. Perhaps the issue should be rephrased?
