### ISSUE TITLE
🐛 Bug Report: Broken link for `getting involved`

### ISSUE THREAD

**Issue by audgirka** [backstage/backstage#23854]
### 📜 Description

The current link for [getting involved](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md?plain=1#L11C83-L11C141) takes the user to the page not found view.

### 👍 Expected behavior

It should point the user to the correct page or remove the broken link from the docs.

### 👎 Actual Behavior with Screenshots

<img width="1672" alt="Screenshot 2024-03-26 at 23 32 35" src="https://github.com/backstage/backstage/assets/11896437/2e139ae4-7079-4bef-b87c-d8fc7c4d32e2">

### 👟 Reproduction steps

1. Go to https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md
2. Click on getting involved link
3. It will open a 404 (page not found) view instead of the contributor guide.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tudi2d** [comment]
Thanks for raising this - looks outdated.
