### ISSUE TITLE
🚀 Feature: extensionpoint for PublisherBase

### ISSUE THREAD

**Issue by magnusp** [backstage/backstage#23861]
### 🔖 Feature description

Provide an extensionpoint so that we can provide a custom publisher for techdocs-backend

### 🎤 Context

I'm in an environment where there are multiple storage providers with network isolation. One example is having Github based builds push techdocs to AWS S3, while on-prem Jenkins builds are pushing to a minio cluster.

Given that we have an extensionpoint for setting a publisher, this would allow us to create a RoutingPublisher or similar.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by johnphilip283** [comment]
Hi there! This PR was merged in fairly recently - does this address the functionality you need?https://github.com/backstage/backstage/pull/23930

**Comment by magnusp** [comment]
> Hi there! This PR was merged in fairly recently - does this address the functionality you need?#23930

Nah, preparers are the collecting bit of techdocs. I'm looking for a way to express a publisher (supporting multiple storage providers) for the sole purpose of reading what the generators have produced. So this is just for reading teachdocs, not the bit where techdocs are written to storage. Here we can use techdocs-cli and the existing publishers since only a single storage provider is used.

**Comment by tlanfer** [comment]
I would be interested in this as well. If i understand correctly, this would allow us to implement a publisher that retrieves techdocs form Gitlab Pages, skipping 3rd party storage alltogether.
