### ISSUE TITLE
🐛 Bug Report: Error 500 Kubernetes Plugin

### ISSUE THREAD

**Issue by clementblaise** [backstage/backstage#23876]
### 📜 Description

The backend returns a 500 when listing the Kubernetes resources associated with a Component.

### 👍 Expected behavior

List the Kubernetes resources associated with a Component.

### 👎 Actual Behavior with Screenshots

<img width="1091" alt="image" src="https://github.com/backstage/backstage/assets/32685572/a3c92099-9d10-42ec-b231-ca862783512a">

### 👟 Reproduction steps

1. Go on a Component
2. Go to the Kubernetes Tab

### 📃 Provide the context for the Bug.

When opening the Kubernetes tab, the frontend successfully receives the list of clusters on the `api/kubernetes/clusters` endpoint. The 500 is returned when the resources are looked up on the service endpoint `api/kubernetes/services/hello-world`

The frontend shows:
```
Errors: Request failed with 500 , {"error":"Cannot read properties of undefined (reading 'credentials')"}
```

On the backend, we can see a bit more details:
```
"level":"error","message":"action=retrieveObjectsByServiceId service=hello-world, error=TypeError: Cannot read properties of undefined (reading 'credentials')","plugin":"kubernetes","service":"backstage"}
```

With 1.24 using backend authentification by default, it appears the cluster-locator was [updated](https://github.com/backstage/backstage/commit/69d0217cba0e00bdf59194872ac91f1767273e17) to allow passing the `option.credentials` parameters on `clusterSupplier.getClusters`; I guess that the service-locator should have something similar as it currently uses `clusterSupplier.getClusters` without passing the Backstage Credential which cause the error seen in the backend logs (options is undefined):
- [MultiTenantServiceLocator](https://github.com/backstage/backstage/blob/560c6854cbe01a9f19daee5450fdce4fddba30ef/plugins/kubernetes-backend/src/service-locator/MultiTenantServiceLocator.ts#L39)
- [SingleTenantServiceLocator](https://github.com/backstage/backstage/blob/560c6854cbe01a9f19daee5450fdce4fddba30ef/plugins/kubernetes-backend/src/service-locator/SingleTenantServiceLocator.ts#L39-L52)
- [CatalogRelationServiceLocator](https://github.com/backstage/backstage/blob/560c6854cbe01a9f19daee5450fdce4fddba30ef/plugins/kubernetes-backend/src/service-locator/CatalogRelationServiceLocator.ts#L44-L51)

### 🖥️ Your Environment

OS:   Darwin 23.4.0 - darwin/arm64
node: v18.16.0
yarn: 1.22.21
cli:  0.26.1 (installed)
backstage:  1.24.0

Dependencies:
  @backstage/app-defaults                                          1.5.2
  @backstage/backend-app-api                                       0.5.14, 0.6.1
  @backstage/backend-common                                        0.20.2, 0.21.5
  @backstage/backend-defaults                                      0.2.15
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.8
  @backstage/backend-plugin-api                                    0.6.15
  @backstage/backend-tasks                                         0.5.20
  @backstage/backend-test-utils                                    0.3.5
  @backstage/catalog-client                                        1.6.2
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4
  @backstage/cli                                                   0.25.2, 0.26.1
  @backstage/config-loader                                         1.7.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.2
  @backstage/core-compat-api                                       0.2.2
  @backstage/core-components                                       0.14.2
  @backstage/core-plugin-api                                       1.9.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.2
  @backstage/integration-aws-node                                  0.1.11
  @backstage/integration-react                                     1.1.25
  @backstage/integration                                           1.9.1
  @backstage/plugin-api-docs                                       0.11.2
  @backstage/plugin-app-backend                                    0.3.63
  @backstage/plugin-app-node                                       0.1.15
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.7
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.10
  @backstage/plugin-auth-backend-module-github-provider            0.1.12
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.12
  @backstage/plugin-auth-backend-module-google-provider            0.1.12
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.10
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.12
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.8
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.6
  @backstage/plugin-auth-backend-module-okta-provider              0.0.8
  @backstage/plugin-auth-backend                                   0.22.2
  @backstage/plugin-auth-node                                      0.4.10
  @backstage/plugin-auth-react                                     0.0.2
  @backstage/plugin-catalog-backend-module-github                  0.5.6
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.13
  @backstage/plugin-catalog-backend                                1.20.0
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.2
  @backstage/plugin-catalog-import                                 0.10.8
  @backstage/plugin-catalog-node                                   1.10.0
  @backstage/plugin-catalog-react                                  1.11.1
  @backstage/plugin-catalog                                        1.18.1
  @backstage/plugin-events-node                                    0.3.1
  @backstage/plugin-github-actions                                 0.6.13
  @backstage/plugin-home-react                                     0.1.10
  @backstage/plugin-home                                           0.6.2
  @backstage/plugin-kubernetes-common                              0.7.5
  @backstage/plugin-kubernetes-node                                0.1.9
  @backstage/plugin-kubernetes-react                               0.3.2
  @backstage/plugin-kubernetes                                     0.11.7
  @backstage/plugin-org                                            0.6.22
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.12
  @backstage/plugin-permission-backend                             0.5.39
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.26
  @backstage/plugin-permission-react                               0.4.21
  @backstage/plugin-proxy-backend                                  0.4.13
  @backstage/plugin-scaffolder-backend-module-azure                0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.5
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.5
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.7
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.5
  @backstage/plugin-scaffolder-backend-module-github               0.2.5
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.1
  @backstage/plugin-scaffolder-backend                             1.22.2
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.1
  @backstage/plugin-scaffolder-react                               1.8.2
  @backstage/plugin-scaffolder                                     1.19.1
  @backstage/plugin-search-backend-module-catalog                  0.1.20
  @backstage/plugin-search-backend-module-pg                       0.5.24
  @backstage/plugin-search-backend-module-techdocs                 0.1.20
  @backstage/plugin-search-backend-node                            1.2.19
  @backstage/plugin-search-backend                                 1.5.5
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.8
  @backstage/plugin-search                                         1.4.8
  @backstage/plugin-tech-radar                                     0.7.1
  @backstage/plugin-techdocs-backend                               1.10.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.7
  @backstage/plugin-techdocs-node                                  1.12.1
  @backstage/plugin-techdocs-react                                 1.2.1
  @backstage/plugin-techdocs                                       1.10.2
  @backstage/plugin-user-settings                                  0.8.3
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.2
  @backstage/theme                                                 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Got a short-term fix for the error itself in #23933, although it's possible this still needs further fixing if credentials aren't being forwarded properly

**Comment by clementblaise** [comment]
Right, that's what I tested locally @Rugvip. I was already relying on the authenticated backend, now with Backstage 1.24, it's the default, so it's going to be blocking for people.
It's quite a big change, that's why I didn't propose to submit a PR, do you have any suggestion on who could have a look?

**Comment by Rugvip** [comment]
Gonna close as the provided fix seems to be enough, we have now also released `v1.25.1` as a patch release with this fix.

**Comment by clementblaise** [comment]
@Rugvip It does not solve the issue, changes the error to :
```
error action=retrieveObjectsByServiceId service=backstage, error=ResponseError: Request failed with 401 Unauthorized
```

**Comment by clementblaise** [comment]
To help narrow it down

https://github.com/backstage/backstage/blob/9d89aed378b3929ef6c01469825b33471498aff6/plugins/kubernetes-backend/src/cluster-locator/CatalogClusterLocator.ts#L55-L104
The 401 is returned from this function, because `options` is undefined, the ternary pass undefined to `this.catalogClient.getEntities()`

https://github.com/backstage/backstage/blob/9d89aed378b3929ef6c01469825b33471498aff6/plugins/kubernetes-backend/src/service-locator/MultiTenantServiceLocator.ts#L35-L40
`options` is undefined because `getClustersByEntity()` doesn't pass the parameter to this.clusterSupplier.getClusters()

https://github.com/backstage/backstage/blob/3b3d549a5f9fd563493b8c1470bf1f587358aee4/plugins/kubernetes-backend/src/service/KubernetesFanOutHandler.ts#L248-L251
`serviceLocator.getClustersByEntity()` gets called from `fanOutRequests()`

https://github.com/backstage/backstage/blob/3b3d549a5f9fd563493b8c1470bf1f587358aee4/plugins/kubernetes-backend/src/service/KubernetesFanOutHandler.ts#L231-L236
`fanOutRequests` get called from `getKubernetesObjectsByEntity()`

https://github.com/backstage/backstage/blob/9b1abac3cca3818fa165dc9795ae4942553a3328/plugins/kubernetes-backend/src/service/KubernetesBuilder.ts#L385-L400

`getKubernetesObjectsByEntity()` is initially called by POST /services/:serviceId'

**Comment by Rugvip** [comment]
Thank you :+1:, will have another look

**Comment by ZF-fredericvanlinthoudt** [comment]
@benjaminr  I've tested this with `1.26.0-next.1` but still getting a 401 error, the error message is:
```
Errors: Request failed with 401 Unauthorized, {"error":{"name":"ResponseError","message":"Request failed with 401 Unauthorized","response":{"size":0,"timeout":0},"body":{"error":{"name":"AuthenticationError","message":"Unable to call 'permissions' plugin on behalf of user, because the target plugin does not support on-behalf-of tokens","stack":"AuthenticationError: Unable to call 'permissions' plugin on behalf of user, because the target plugin does not support on-behalf-of tokens\n at DefaultAuthService.getPluginRequestToken (/Users/z0058456/backstage/backstage/node_modules/@backstage/backend-app-api/src/services/implementations/auth/authServiceFactory.ts:242:17)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at _ServerPermissionClient.authorizeConditional (/Users/z0058456/backstage/backstage/node_modules/@backstage/plugin-permission-node/src/ServerPermissionClient.ts:97:9)\n at AuthorizedEntitiesCatalog.entities (/Users/z0058456/backstage/backstage/node_modules/@backstage/plugin-catalog-backend/src/service/AuthorizedEntitiesCatalog.ts:55:7)\n at <anonymous> (/Users/z0058456/backstage/backstage/node_modules/@backstage/plugin-catalog-backend/src/service/createRouter.ts:132:40)"},"request":{"method":"GET","url":"/entities?filter=kind%3DResource%2Cspec.type%3Dkubernetes-cluster%2Cmetadata.annotations.kubernetes.io%2Fapi-server%2Cmetadata.annotations.kubernetes.io%2Fapi-server-certificate-authority%2Cmetadata.annotations.kubernetes.io%2Fauth-provider"},"response":{"statusCode":401}},"cause":{"name":"AuthenticationError","message":"Unable to call 'permissions' plugin on behalf of user, because the target plugin does not support on-behalf-of tokens","stack":"AuthenticationError: Unable to call 'permissions' plugin on behalf of user, because the target plugin does not support on-behalf-of tokens\n at DefaultAuthService.getPluginRequestToken (/Users/z0058456/backstage/backstage/node_modules/@backstage/backend-app-api/src/services/implementations/auth/authServiceFactory.ts:242:17)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at _ServerPermissionClient.authorizeConditional (/Users/z0058456/backstage/backstage/node_modules/@backstage/plugin-permission-node/src/ServerPermissionClient.ts:97:9)\n at AuthorizedEntitiesCatalog.entities (/Users/z0058456/backstage/backstage/node_modules/@backstage/plugin-catalog-backend/src/service/AuthorizedEntitiesCatalog.ts:55:7)\n at <anonymous> (/Users/z0058456/backstage/backstage/node_modules/@backstage/plugin-catalog-backend/src/service/createRouter.ts:132:40)"},"statusCode":401,"statusText":"Unauthorized","stack":"ResponseError: Request failed with 401 Unauthorized\n at Function.fromResponse (/Users/z0058456/backstage/backstage/node_modules/@backstage/errors/src/errors/ResponseError.ts:76:12)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at CatalogClient.requestRequired (/Users/z0058456/backstage/backstage/node_modules/@backstage/catalog-client/src/CatalogClient.ts:449:13)\n at CatalogClient.getEntities (/Users/z0058456/backstage/backstage/node_modules/@backstage/catalog-client/src/CatalogClient.ts:130:22)\n at CatalogClusterLocator.getClusters (/Users/z0058456/backstage/backstage/node_modules/@backstage/plugin-kubernetes-backend/src/cluster-locator/CatalogClusterLocator.ts:70:22)\n at async Promise.all (index 0)\n at CombinedClustersSupplier.getClusters (/Users/z0058456/backstage/backstage/node_modules/@backstage/plugin-kubernetes-backend/src/cluster-locator/index.ts:41:22)\n at KubernetesBuilder.fetchClusterDetails (/Users/z0058456/backstage/backstage/node_modules/@backstage/plugin-kubernetes-backend/src/service/KubernetesBuilder.ts:472:28)\n at <anonymous> (/Users/z0058456/backstage/backstage/node_modules/@backstage/plugin-kubernetes-backend/src/service/KubernetesBuilder.ts:416:30)"},"request":{"method":"GET","url":"/api/kubernetes/clusters"},"response":{"statusCode":401}}
```

Any thoughts?

**Comment by vinzscam** [comment]
thank you @ZF-fredericvanlinthoudt for reporting the issue 🙏
Fix is coming: https://github.com/backstage/backstage/pull/24145
