### ISSUE TITLE
🐛 Bug Report: `GitlabOrgDiscoveryEntityProvider` missing from the new backend system support

### ISSUE THREAD

**Issue by davidfestal** [backstage/backstage#23884]
### 📜 Description

When using the Catalog Backend Module for GitLab with the new backend system (using `@backstage/plugin-catalog-backend-module-gitlab/alpha`), [only the `GitlabDiscoveryEntityProvider` is added to the catalog](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-gitlab/src/module/catalogModuleGitlabDiscoveryEntityProvider.ts#L43), and the `GitlabOrgDiscoveryEntityProvider` is omitted.
This result is the unability to import users on groups when using Gitlab as the main source of data.
The `GitlabOrgDiscoveryEntityProvider` provider should:
- either be added along with  `GitlabDiscoveryEntityProvider` in the `@backstage/plugin-catalog-backend-module-gitlab/alpha` package.
- or be exposed in  dedicated distinct package named (@backstage/plugin-catalog-backend-module-gitlab-org), as it is [done for Github catalog providers](https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-github-org).

### 👍 Expected behavior

The `GitlabOrgDiscoveryEntityProvider`  should be usable when under the new backend system.

### 👎 Actual Behavior with Screenshots

The `GitlabOrgDiscoveryEntityProvider`  is not usable when under the new backend system.

### 👟 Reproduction steps

1. import the `@backstage/plugin-catalog-backend-module-gitlab/alpha` package in your new backend system backend app
2. Run backstage
3. The Gitlab users and groups will never be imported, though other catalog entities can be imported. 

### 📃 Provide the context for the Bug.

I can provide a PR for this bug, but I'd need to know which, of the 2 options mentioned in the description, we should choose. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by swnia** [comment]
I've raised #23762 for this.

Until this is implemented in the plugin itself, I added 
```js
import { GitlabOrgDiscoveryEntityProvider } from '@backstage/plugin-catalog-backend-module-gitlab';
[...]
const catalogModuleGitlabOrgDiscoveryEntityProvider =
  createBackendModule({
    pluginId: 'catalog',
    moduleId: 'gitlab-org-discovery-entity-provider',
    register(env) {
      env.registerInit({
        deps: {
          config: coreServices.rootConfig,
          catalog: catalogProcessingExtensionPoint,
          logger: coreServices.logger,
          scheduler: coreServices.scheduler,
        },
        async init({ config, catalog, logger, scheduler }) {
          catalog.addEntityProvider(
            GitlabOrgDiscoveryEntityProvider.fromConfig(config, {
              logger: loggerToWinstonLogger(logger),
              scheduler,
            }),
          );
        },
      });
    },
  });
[...]
backend.add(catalogModuleGitlabOrgDiscoveryEntityProvider);
```
To my `packages/backend/src/index.ts` to at least still have the data.

**Comment by brodo** [comment]
> I've raised #23762 for this.
> 
> Until this is implemented in the plugin itself, I added
> 
> ```js
> import { GitlabOrgDiscoveryEntityProvider } from '@backstage/plugin-catalog-backend-module-gitlab';
> [...]
> const catalogModuleGitlabOrgDiscoveryEntityProvider =
>   createBackendModule({
>     pluginId: 'catalog',
>     moduleId: 'gitlab-org-discovery-entity-provider',
>     register(env) {
>       env.registerInit({
>         deps: {
>           config: coreServices.rootConfig,
>           catalog: catalogProcessingExtensionPoint,
>           logger: coreServices.logger,
>           scheduler: coreServices.scheduler,
>         },
>         async init({ config, catalog, logger, scheduler }) {
>           catalog.addEntityProvider(
>             GitlabOrgDiscoveryEntityProvider.fromConfig(config, {
>               logger: loggerToWinstonLogger(logger),
>               scheduler,
>             }),
>           );
>         },
>       });
>     },
>   });
> [...]
> backend.add(catalogModuleGitlabOrgDiscoveryEntityProvider);
> ```
> 
> To my `packages/backend/src/index.ts` to at least still have the data.

I've got the same problem. Thanks for providing the code snippet. Where did you get `catalogProcessingExtensionPoint` from?

**Comment by swnia** [comment]
Ah... sorry. I updated the comment above with the relevant import.

**Comment by davidfestal** [comment]
> I've raised #23762 for this.

OK, I had not found it, sorry.
Should I close this one as duplicate ?

**Comment by swnia** [comment]
Yeah, I think having everything in one place would make it easier to get it implemented.

**Comment by elaine-mattos** [comment]
Hi guys

I submitted this [PR](https://github.com/backstage/backstage/pull/23373) and it addresses this problem as well.
Waiting for the reviews and merge. ;)
