### ISSUE TITLE
🚀 Feature: External developer Portal : Backstage Threat Model

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#23888]
### 🔖 Feature description

We are using backstage from past 2 years, we were building internal developer portal. Now more than 10 teams are contributing toward backstage internal portal. 

We are exploring external developer portal. It will be public.  It will open for external developers as well as a malicious actor outside our organization.

When we go through backstage trust model: It seems like, we should not build external portal on  backstage. it is not secure.

**for example a malicious actor outside of the organization. The security model of Backstage currently assumes that this group does not have any direct access to Backstage**

ref: https://backstage.io/docs/overview/threat-model/

### 🎤 Context

is there any future planning for backstage support external portal capabilities? or is there any other solution for this issue?
is backstage token is not secure if we using OIDC for azure/okta?

### ✌️ Possible Implementation

There are few thing. will this help to secure backstage external portal.

- separate frontend and backend server and backend doesn't expose to public.
- we don't use backstage auth plugin and create our own. we are planning to use OIDC flow for okta/azure etc.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @lalit774, there recent auth changes in `1.24.x` and `1.25.x` are working towards a more "secure by default" setup for Backstage which should get it closer to being able to have it more public.

There's some details on the plans for this in the State of Backstage talk at KubeCon EU in Paris that took place last week: https://www.youtube.com/watch?v=jBf3g79xcf4

**Comment by awanlin** [comment]
This also could be helpful: https://www.youtube.com/watch?v=qQcVHbXjU2Q
