### ISSUE TITLE
🐛 Bug Report: Blog posts all show `{/* truncate */}` in detail view

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#23891]
### 📜 Description

When you go to read almost all of the blog posts on Backstage.io you'll see the text `{/* truncate */}` in each of them. For example: https://backstage.io/blog/2024/02/28/security-notice

The exception being this one post: https://backstage.io/blog/2023/11/15/backstagecon-kubecon-23

**Note:** this isn't a bug with Backstage itself but with something in the Docusaurus config or setup.

### 👍 Expected behavior

We should not see the text `{/* truncate */}` 

### 👎 Actual Behavior with Screenshots

As you can see the text `{/* truncate */}` is visible in the detail view of the blog post

![Screenshot 2024-03-28 at 10 08 35 AM](https://github.com/backstage/backstage/assets/67169551/7128e787-a01b-4ec9-a35a-52d0326ef63a)

### 👟 Reproduction steps

1. Fork the Backstage repo
2. Navigate to `cd microsite`
3. Run `yarn install`
4. Run `yarn start`
5. Navigate to the Blog
6. Click on a blog post

**Note:** the text `{/* truncate */}` is visible in the detail view of the blog post

### 📃 Provide the context for the Bug.

While trying to add a new blog post we came across this and were unable to fix it. Logging this issue to see if someone from the Community wants to take a look and try to fix it.

### 🖥️ Your Environment

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by AmbrishRamachandiran** [comment]
@awanlin tried out a fix please check

**Comment by awanlin** [comment]
Thanks everyone for taking a look at this issue. I should have posted some of the things I tried:

- Changes the truncate marker to `<!--truncate-->` but that didn't work as expected as the files for our blog are all MDX - https://docusaurus.io/docs/3.1.1/blog#blog-list
- Set the `truncateMarker` in the config even though we are using the default, this didn't work - https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog#truncateMarker
- Our current Docusaurus setup isn't fully upgraded so I tried adding all the missing items and going to the proper versions, this also didn't work but I do feel we should do something about this - https://docusaurus.io/docs/migration/v3#upgrading-dependencies
