### ISSUE TITLE
🐛 Bug Report: Techradar plugin jest error (Jest encountered an unexpected token)

### ISSUE THREAD

**Issue by goququ** [backstage/backstage#23898]
### 📜 Description

Hi team. This is the problem:

1. I just installed the techradar plugin using the official documentation.
2. Run command: `backstage-cli repo test`
3. Got failed test:

### 👍 Expected behavior

It should work without jest errors

### 👎 Actual Behavior with Screenshots

Got an error related to the techradar plugin

### 👟 Reproduction steps

1) Install [techradar plugin ](https://www.npmjs.com/package/@backstage/plugin-tech-radar)
2) run `backstage-cli repo test` command

### 📃 Provide the context for the Bug.

error from `backstage-cli repo test` command:

```
Summary of all failing tests
FAIL packages/app/src/App.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/ruslan.nasyrov/cross/backstage/node_modules/react-use/esm/useCopyToClipboard.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import writeText from 'copy-to-clipboard';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      30 | import { TechRadarPage } from '@backstage/plugin-tech-radar';
      31 | import {
    > 32 |   TechDocsIndexPage,
         |                     ^
      33 |   TechDocsReaderPage,
      34 |   techdocsPlugin,
      35 | } from '@backstage/plugin-techdocs';

      at CachingJestRuntime.createScriptFromCode (../../../node_modules/jest-runtime/build/index.js:1505:14)
      at CachingJestRuntime.createScriptFromCode (../../../node_modules/@backstage/cli/config/jestCachingModuleLoader.js:28:22)
      at Object.<anonymous> (../../../node_modules/@backstage/plugin-tech-radar/node_modules/@backstage/core-components/dist/index.esm.js:350:68)
      at Object.<anonymous> (../../../node_modules/@backstage/plugin-tech-radar/dist/esm/RadarPage-B5v6w9DF.esm.js:22:25)
      at Object.<anonymous> (../../../node_modules/@backstage/plugin-tech-radar/dist/index.esm.js:37:31)
      at Object.<anonymous> (App.tsx:32:26)
      at Object.<anonymous> (App.test.tsx:8:53
```

### 🖥️ Your Environment

OS:   Darwin 23.3.0 - darwin/arm64
node: v18.19.1
yarn: 1.22.21
cli:  0.25.2 (installed)
backstage:  1.22.1

Dependencies:
  @backstage/app-defaults                                          1.5.0
  @backstage/backend-app-api                                       0.5.13
  @backstage/backend-common                                        0.19.10, 0.20.2, 0.21.2
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.5
  @backstage/backend-plugin-api                                    0.6.12
  @backstage/backend-tasks                                         0.5.17
  @backstage/backend-test-utils                                    0.2.10
  @backstage/catalog-client                                        1.6.0
  @backstage/catalog-model                                         1.4.4
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.3
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.6.2
  @backstage/config                                                1.1.1, 1.2.0
  @backstage/core-app-api                                          1.12.0, 1.12.3
  @backstage/core-compat-api                                       0.2.0, 0.2.3
  @backstage/core-components                                       0.13.10, 0.14.0, 0.14.3
  @backstage/core-plugin-api                                       1.9.0, 1.9.1
  @backstage/dev-utils                                             1.0.27
  @backstage/errors                                                1.2.3, 1.2.4
  @backstage/eslint-plugin                                         0.1.5
  @backstage/frontend-plugin-api                                   0.5.0, 0.6.0, 0.6.3
  @backstage/integration-aws-node                                  0.1.9
  @backstage/integration-react                                     1.1.24
  @backstage/integration                                           1.9.0
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.7
  @backstage/plugin-auth-backend-module-github-provider            0.1.9
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.9
  @backstage/plugin-auth-backend-module-google-provider            0.1.9
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.9
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.5
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.4.7
  @backstage/plugin-badges-backend                                 0.3.9
  @backstage/plugin-badges                                         0.2.54
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.9
  @backstage/plugin-catalog-backend-module-ldap                    0.5.27
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.9
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.9
  @backstage/plugin-catalog-backend                                1.17.2
  @backstage/plugin-catalog-common                                 1.0.21
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.6
  @backstage/plugin-catalog-node                                   1.7.2
  @backstage/plugin-catalog-react                                  1.10.0
  @backstage/plugin-catalog-unprocessed-entities                   0.1.8
  @backstage/plugin-catalog                                        1.17.0
  @backstage/plugin-entity-feedback-backend                        0.2.9
  @backstage/plugin-entity-feedback-common                         0.1.3
  @backstage/plugin-entity-feedback                                0.2.13
  @backstage/plugin-events-node                                    0.2.21
  @backstage/plugin-github-actions                                 0.6.11
  @backstage/plugin-org                                            0.6.20
  @backstage/plugin-permission-backend                             0.5.35
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.23
  @backstage/plugin-permission-react                               0.4.20
  @backstage/plugin-proxy-backend                                  0.4.10
  @backstage/plugin-scaffolder-backend-module-azure                0.1.4
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.2
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.2
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.2
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.4
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.2
  @backstage/plugin-scaffolder-backend-module-github               0.2.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.15
  @backstage/plugin-scaffolder-backend                             1.21.2
  @backstage/plugin-scaffolder-common                              1.5.0
  @backstage/plugin-scaffolder-node                                0.2.10, 0.3.2
  @backstage/plugin-scaffolder-react                               1.8.0
  @backstage/plugin-scaffolder                                     1.18.0
  @backstage/plugin-search-backend-module-catalog                  0.1.16
  @backstage/plugin-search-backend-module-pg                       0.5.21
  @backstage/plugin-search-backend-module-techdocs                 0.1.16
  @backstage/plugin-search-backend-node                            1.2.16
  @backstage/plugin-search-backend                                 1.5.2
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.6
  @backstage/plugin-search                                         1.4.6
  @backstage/plugin-sentry                                         0.5.15
  @backstage/plugin-tech-radar                                     0.7.2
  @backstage/plugin-techdocs-backend                               1.9.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.5
  @backstage/plugin-techdocs-node                                  1.11.4
  @backstage/plugin-techdocs-react                                 1.1.16
  @backstage/plugin-techdocs                                       1.10.0
  @backstage/plugin-user-settings                                  0.8.1
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.6.2
  @backstage/test-utils                                            1.5.0
  @backstage/theme                                                 0.4.4, 0.5.1, 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
This would seem to be related to https://github.com/backstage/backstage/pull/23565

**Comment by dianaarnos** [comment]
Hi all!
Just to add to this topic: I am facing the same issue but for the home plugin:

```shell
FAIL app packages/app/src/App.test.tsx
  ● Test suite failed to run
    Jest encountered an unexpected token
    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
    By default "node_modules" folder is ignored by transformers.
    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation
    Details:
    /builds/apps/backstage/backstage-app/node_modules/react-use/esm/useCopyToClipboard.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import writeText from 'copy-to-clipboard';
                                                                                      ^^^^^^
    SyntaxError: Cannot use import statement outside a module
      11 |   identityApiRef,
      12 | } from '@backstage/core-plugin-api';
    > 13 | import { visitsApiRef, VisitsWebStorageApi } from '@backstage/plugin-home';
         |                     ^
      14 |
      15 | export const apis: AnyApiFactory[] = [
      16 |   createApiFactory({
      at CachingJestRuntime.createScriptFromCode (../../../node_modules/jest-runtime/build/index.js:1505:14)
      at CachingJestRuntime.createScriptFromCode (../../../node_modules/@backstage/cli/config/jestCachingModuleLoader.js:28:22)
      at Object.<anonymous> (../../../node_modules/@backstage/plugin-home-react/node_modules/@backstage/core-components/dist/index.esm.js:350:68)
      at Object.<anonymous> (../../../node_modules/@backstage/plugin-home-react/dist/index.esm.js:22:25)
      at Object.<anonymous> (../../../node_modules/@backstage/plugin-home/dist/index.esm.js:86:26)
      at Object.<anonymous> (apis.ts:13:21)
      at Object.<anonymous> (App.tsx:26:15)
      at Object.<anonymous> (App.test.tsx:8:53)
```

As one can notice, the `Details` are giving the exact same message for me as for @goququ , even though we are facing this problem with different plugins:

>     /builds/apps/backstage/backstage-app/node_modules/react-use/esm/useCopyToClipboard.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import writeText from 'copy-to-clipboard';

**Comment by benjdlambert** [comment]
Hmm have you bumped the `@backstage/cli` package, or do you have maybe custom jest config that could be overwriting the `transformIgnorePatterns`? :pray:

**Comment by dianaarnos** [comment]
@benjdlambert your comment made me realize I haven't updated `@backstage/cli in a while`. Upgrading it to `0.26` solved it \o/
