### ISSUE TITLE
🐛 Bug Report: Badges picture giving 401 in latest 1.25.0

### ISSUE THREAD

**Issue by levanvunam** [backstage/backstage#23902]
### 📜 Description

![image](https://github.com/backstage/backstage/assets/12594238/412fe9f0-8c9a-459a-8c8f-1f9c210c3867)
The image is missing when select badges in entity page

It's also missing when embedded into md file. Accessing directly the url giving 401 error

```
{
  "error": {
    "name": "AuthenticationError",
    "message": "Missing credentials"
  },
  "request": {
    "method": "GET",
    "url": "/api/badges/entity/default/component/XXX/badge/pingback"
  },
  "response": {
    "statusCode": 401
  }
}
```

### 👍 Expected behavior

The image should be accessible

### 👎 Actual Behavior with Screenshots

Return 401 error

![image](https://github.com/backstage/backstage/assets/12594238/412fe9f0-8c9a-459a-8c8f-1f9c210c3867)

```
{
  "error": {
    "name": "AuthenticationError",
    "message": "Missing credentials"
  },
  "request": {
    "method": "GET",
    "url": "/api/badges/entity/default/component/XXX/badge/pingback"
  },
  "response": {
    "statusCode": 401
  }
}
```

### 👟 Reproduction steps

Go to entity page > Select "More" > Select "Badges"

### 📃 Provide the context for the Bug.

This issue seem to be due to the new auth system, when upgraded the 401 error appears

### 🖥️ Your Environment

latest 1.25.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Woops, looks like we need to make these unauthenticated routes for this to work. Does someone want to pick this up? :pray:

**Comment by sagardesai1** [comment]
Can I pick this up?

**Comment by benjdlambert** [comment]
Of course! Assigned!

**Comment by pjungermann** [comment]
This was resolved by PR 23994 and can be closed

**Comment by freben** [comment]
Yep, thanks!
