### ISSUE TITLE
🐛 Bug Report: Some auth plugins don't work because of unintended polyfilling. 

### ISSUE THREAD

**Issue by kenkoooo** [backstage/backstage#23906]
### 📜 Description

In certain auth-backend-modules, resolver factories are placed as shown in the following example:
https://github.com/backstage/backstage/blob/34217c5d377991d05f724a4c01c44e33573e7812/plugins/auth-backend-module-atlassian-provider/src/module.ts#L39-L42

These factories are utilized to generate a single `signInResolver`, as demonstrated below:
https://github.com/backstage/backstage/blob/34217c5d377991d05f724a4c01c44e33573e7812/plugins/auth-node/src/oauth/createOAuthProviderFactory.ts#L44-L49

Given that these lines are compiled into the following JavaScript, your factories will never be utilized, and `signInResolver` will be `undefined` if you haven't included `signInResolver`.

```javascript
const signInResolver = (_b = options.signInResolver) != null ? _b : readDeclarativeSignInResolver({
    config: envConfig,
    signInResolverFactories: (_a = options.signInResolverFactories) != null ? _a : {}
});
```

(`(_b = options.signInResolver) != null` will be `true` because `options.signInResolver` is `undefined`.)

### 👍 Expected behavior

If no `signInResolver` is provided, the specified factories should be used to initialize `signInResolver`. 

### 👎 Actual Behavior with Screenshots

N/A

### 👟 Reproduction steps

If you specify auth plugins such as `atlassian`, the factories won't function as intended. Here's the adjusted explanation:

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Whoa that's not how `??` is meant to work; it's supposed to by definition check for null OR undefined.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing#

That code has been transpiled wrong. Ping @Rugvip

**Comment by Rugvip** [comment]
That should be fine, only a strict equality check would treat `null` and `undefined` as different. `undefined != null` should be false

**Comment by freben** [comment]
Bah, I'm clearly blind.

**Comment by freben** [comment]
@kenkoooo So to advance, maybe you could provide some reproduction steps instead?

**Comment by kenkoooo** [comment]
I apologize for the confusion. It appears there was no issue to report in the first place. I will proceed to close the ticket accordingly. Thank you for taking the time to look into it.
