### ISSUE TITLE
🐛 Bug Report: Microsite Not Fully Upgraded to Docusaurus v3

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#23910]
### 📜 Description

While working on https://github.com/backstage/backstage/issues/23891 I noticed that the microsite is not fully upgraded to Docusaurus v3

### 👍 Expected behavior

The microsite should be full upgraded to Docusaurus v3

### 👎 Actual Behavior with Screenshots

There isn't really any errors right now but I think if we tried to use new features of Docusaurus v3 like around MDX we may run into issues.

### 👟 Reproduction steps

1. Look at the `dependencies` (and `devDependencies`) here: https://github.com/backstage/backstage/blob/fa512d2eecea48a838d5e60f940e96a20c8487af/microsite/package.json#L32

Notice they don't match up with what is in the upgrade guide here: https://docusaurus.io/docs/migration/v3#upgrading-dependencies

### 📃 Provide the context for the Bug.

I'm concerned that should we want to use new features from Docusaurus v3 we may run into issues that we spin out wheels on as we haven't properly upgraded.

### 🖥️ Your Environment

This isn't environment specific but what is in the `package.json` file here: https://github.com/backstage/backstage/blob/fa512d2eecea48a838d5e60f940e96a20c8487af/microsite/package.json#L32

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @npiyush97, would this be something you could run with? Should not be a huge amount of work IMO.

I would probably work though this entire guide to be safe: https://docusaurus.io/docs/migration/v3

**Comment by npiyush97** [comment]
> Hi @npiyush97, would this be something you could run with? Should not be a huge amount of work IMO.
> 
> I would probably work though this entire guide to be safe: https://docusaurus.io/docs/migration/v3

Yes ran their compile test 45/409 doc files failed to compile. I'm little under the weather if anyone wants to pick this up I'm happy with it otherwise I will look into this over weekend.

**Comment by awanlin** [comment]
Get well soon @npiyush97, this is for sure not a rush! 👍
