### ISSUE TITLE
🐛 Bug Report: /api/techdocs/cookie got 401 error when restaring backend (in dev environment) 

### ISSUE THREAD

**Issue by apc-kamezaki** [backstage/backstage#23914]
### 📜 Description

I've got error at /api/techdocs/cookie when I restarted backstage backend.

My environment was using in-memory db(sqlite) and implemented with new backend system.

It seemd it was happend because backend could not find the kid of JWT in the key store.

In my case ,it was occured only on develop environment.

### 👍 Expected behavior

I thin cookie api is protected by a valid token in authorization header, so I think it should  return 200 and valid cookie even if cookie was not valid.

### 👎 Actual Behavior with Screenshots

![318309530-4bb00dca-2759-406c-b34c-353ced3b9230](https://github.com/backstage/backstage/assets/14068604/8063d468-87cf-4aae-996f-23d7b3015d65)

### 👟 Reproduction steps

1. Signin and show to techdocs page
2. Stop backend
3. Restart backend
4. Signin and try to show the same techdocs page.

### 🖥️ Your Environment

OS:   Darwin 23.3.0 - darwin/x64
node: v18.18.2
yarn: 3.6.4
cli:  0.26.1 (installed)
backstage:  1.24.2

Dependencies:
  @backstage/app-defaults                                          1.5.2
  @backstage/backend-app-api                                       0.5.14, 0.6.2
  @backstage/backend-common                                        0.21.3, 0.21.4, 0.21.5, 0.21.6
  @backstage/backend-defaults                                      0.2.15
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.7, 0.1.8
  @backstage/backend-plugin-api                                    0.6.13, 0.6.14, 0.6.15, 0.6.16
  @backstage/backend-tasks                                         0.5.19, 0.5.18, 0.5.20, 0.5.21
  @backstage/backend-test-utils                                    0.3.5
  @backstage/catalog-client                                        1.6.0, 1.6.1, 1.6.2, 1.6.3
  @backstage/catalog-model                                         1.4.4, 1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4
  @backstage/cli                                                   0.26.1
  @backstage/config-loader                                         1.6.2, 1.7.0
  @backstage/config                                                1.1.1, 1.2.0
  @backstage/core-app-api                                          1.12.0, 1.12.2
  @backstage/core-compat-api                                       0.2.0, 0.2.2
  @backstage/core-components                                       0.14.0, 0.14.2
  @backstage/core-plugin-api                                       1.9.0, 1.9.1
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.3, 1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.0, 0.6.2
  @backstage/integration-aws-node                                  0.1.10, 0.1.11, 0.1.12, 0.1.9
  @backstage/integration-react                                     1.1.24, 1.1.25
  @backstage/integration                                           1.9.0, 1.9.1
  @backstage/plugin-api-docs                                       0.11.2
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.7
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.10
  @backstage/plugin-auth-backend-module-github-provider            0.1.12
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.12
  @backstage/plugin-auth-backend-module-google-provider            0.1.12
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.10
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.12
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.8
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.6
  @backstage/plugin-auth-backend-module-okta-provider              0.0.8
  @backstage/plugin-auth-backend                                   0.22.2
  @backstage/plugin-auth-node                                      0.4.10, 0.4.11, 0.4.8, 0.4.9
  @backstage/plugin-auth-react                                     0.0.2
  @backstage/plugin-catalog-backend-module-github-org              0.1.10
  @backstage/plugin-catalog-backend-module-github                  0.5.6
  @backstage/plugin-catalog-backend-module-openapi                 0.1.33
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.13
  @backstage/plugin-catalog-backend                                1.18.0, 1.20.0
  @backstage/plugin-catalog-common                                 1.0.21, 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.2
  @backstage/plugin-catalog-import                                 0.10.8
  @backstage/plugin-catalog-node                                   1.10.0, 1.7.3, 1.8.0
  @backstage/plugin-catalog-react                                  1.10.0, 1.11.1
  @backstage/plugin-catalog                                        1.18.1
  @backstage/plugin-events-backend-module-github                   0.2.1
  @backstage/plugin-events-backend                                 0.3.1
  @backstage/plugin-events-node                                    0.3.0, 0.3.1
  @backstage/plugin-github-actions                                 0.6.13
  @backstage/plugin-github-deployments                             0.1.63
  @backstage/plugin-github-issues                                  0.3.0
  @backstage/plugin-home-react                                     0.1.10, 0.1.8
  @backstage/plugin-home                                           0.7.1
  @backstage/plugin-org                                            0.6.22
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.12
  @backstage/plugin-permission-backend                             0.5.39
  @backstage/plugin-permission-common                              0.7.12, 0.7.13
  @backstage/plugin-permission-node                                0.7.24, 0.7.25, 0.7.26, 0.7.27
  @backstage/plugin-permission-react                               0.4.20, 0.4.21
  @backstage/plugin-proxy-backend                                  0.4.13
  @backstage/plugin-scaffolder-backend-module-azure                0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.5
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.5
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.7
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.5
  @backstage/plugin-scaffolder-backend-module-github               0.2.5
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.1
  @backstage/plugin-scaffolder-backend                             1.22.2
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.1
  @backstage/plugin-scaffolder-react                               1.8.2
  @backstage/plugin-scaffolder                                     1.19.1
  @backstage/plugin-search-backend-module-catalog                  0.1.18, 0.1.20
  @backstage/plugin-search-backend-module-pg                       0.5.24
  @backstage/plugin-search-backend-module-techdocs                 0.1.20
  @backstage/plugin-search-backend-node                            1.2.18, 1.2.19
  @backstage/plugin-search-backend                                 1.5.5
  @backstage/plugin-search-common                                  1.2.10, 1.2.11
  @backstage/plugin-search-react                                   1.7.6, 1.7.8
  @backstage/plugin-search                                         1.4.6, 1.4.8
  @backstage/plugin-techdocs-backend                               1.10.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.7
  @backstage/plugin-techdocs-node                                  1.12.1
  @backstage/plugin-techdocs-react                                 1.2.1
  @backstage/plugin-techdocs                                       1.10.2
  @backstage/plugin-user-settings                                  0.8.3
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.2
  @backstage/theme                                                 0.5.1, 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tudi2d** [comment]
fixed by #23915?
