### ISSUE TITLE
🐛 Bug Report: Not able to run app using relative path

### ISSUE THREAD

**Issue by apoorvkapil** [backstage/backstage#23937]
### 📜 Description

my application is running on docker and there is a specific requirement to run the app on basePath (/backstage). so i build my app using the relative path as mentioned in one of the issue [here](https://github.com/backstage/backstage/issues/13872).

App is starting fine on basepath calling the backend with base path as well but **backend returning an html page rather than json**. catalog entity is resulting in error  `example.com/backstage/api/catalog/entity-facets?facet=metadata.namespace` 

What am i missing here? 

### 👍 Expected behavior

Frontend app should be calling the backend APIs on example.com/backstage/api/catalog and backend should return the JSON output rather than the html.

### 👎 Actual Behavior with Screenshots

The APP is running on port 7007, calling the backend with base path as well, but the backend returning an html page rather than json. backend getting called from frontend and returning HTML  `example.com/backstage/api/catalog/entity-facets?facet=metadata.namespace` as you can see it below.
![image](https://github.com/backstage/backstage/assets/17564110/6f208913-a101-4dce-a310-008745df628b)

### 👟 Reproduction steps

using 3 app configs in the same order
 
app-config.yaml
app-config.local.yaml 
app-config.build.yaml

```
app-config.local.yaml
app:
    title: Scaffolded Backstage App
    baseUrl: http://localhost:7007/backstage
backend:
    baseUrl: http://localhost:7007/backstage

```

```
app-config.build.yaml
app:
    baseUrl: '.'

backend:
    baseUrl: '.'

```

I am building the app using `yarn build:backend --config ../../app-config.yaml --config ../../app.config.local.yaml --config ../../app.config.build.yaml`

### 📃 Provide the context for the Bug.

Try to run backstage on `example.com/backstage` using `yarn build:backend` and `yarn start-backend` command 

### 🖥️ Your Environment

OS:   Darwin 23.4.0 - darwin/arm64
node: v18.18.0
yarn: 4.1.0
cli:  0.25.2 (installed)
backstage:  1.23.4

Dependencies:
  @backstage/app-defaults                                          1.5.0
  @backstage/backend-app-api                                       0.5.14
  @backstage/backend-common                                        0.21.3
  @backstage/backend-defaults                                      0.2.13
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.6
  @backstage/backend-plugin-api                                    0.6.13
  @backstage/backend-tasks                                         0.5.18
  @backstage/catalog-client                                        1.6.0
  @backstage/catalog-model                                         1.4.4
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.3
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.6.2
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.12.0
  @backstage/core-compat-api                                       0.2.0
  @backstage/core-components                                       0.14.0
  @backstage/core-plugin-api                                       1.9.0
  @backstage/dev-utils                                             1.0.27
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.5
  @backstage/frontend-plugin-api                                   0.6.0
  @backstage/integration-aws-node                                  0.1.9
  @backstage/integration-react                                     1.1.24
  @backstage/integration                                           1.9.0
  @backstage/plugin-api-docs                                       0.11.0
  @backstage/plugin-app-backend                                    0.3.61
  @backstage/plugin-app-node                                       0.1.13
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.8
  @backstage/plugin-auth-backend-module-github-provider            0.1.10
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.10
  @backstage/plugin-auth-backend-module-google-provider            0.1.10
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.8
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.10
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.6
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.6
  @backstage/plugin-auth-backend                                   0.21.3
  @backstage/plugin-auth-node                                      0.4.8
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.10
  @backstage/plugin-catalog-backend                                1.17.3
  @backstage/plugin-catalog-common                                 1.0.21
  @backstage/plugin-catalog-graph                                  0.4.0
  @backstage/plugin-catalog-import                                 0.10.6
  @backstage/plugin-catalog-node                                   1.7.3
  @backstage/plugin-catalog-react                                  1.10.0
  @backstage/plugin-catalog                                        1.17.0
  @backstage/plugin-events-node                                    0.2.22
  @backstage/plugin-github-actions                                 0.6.11
  @backstage/plugin-org                                            0.6.20
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.24
  @backstage/plugin-permission-react                               0.4.20
  @backstage/plugin-proxy-backend                                  0.4.11
  @backstage/plugin-scaffolder-backend-module-azure                0.1.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.3
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.5
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.3
  @backstage/plugin-scaffolder-backend-module-github               0.2.3
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.16
  @backstage/plugin-scaffolder-backend                             1.21.3
  @backstage/plugin-scaffolder-common                              1.5.0
  @backstage/plugin-scaffolder-node                                0.3.3
  @backstage/plugin-scaffolder-react                               1.8.0
  @backstage/plugin-scaffolder                                     1.18.0
  @backstage/plugin-search-backend-module-catalog                  0.1.17
  @backstage/plugin-search-backend-module-pg                       0.5.22
  @backstage/plugin-search-backend-module-techdocs                 0.1.17
  @backstage/plugin-search-backend-node                            1.2.17
  @backstage/plugin-search-backend                                 1.5.3
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.6
  @backstage/plugin-search                                         1.4.6
  @backstage/plugin-tech-radar                                     0.6.13
  @backstage/plugin-techdocs-backend                               1.9.6
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.5
  @backstage/plugin-techdocs-node                                  1.11.5
  @backstage/plugin-techdocs-react                                 1.1.16
  @backstage/plugin-techdocs                                       1.10.0
  @backstage/plugin-user-settings                                  0.8.1
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.6.3
  @backstage/test-utils                                            1.5.0
  @backstage/theme                                                 0.5.1
  @backstage/types                                                 1.1.1
  @backstage/version-bridge

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by tudi2d** [comment]
It should be possible to run backstage on a relative path. At build time (so when running `yarn build`) you need to have the relatvive path in the config.

**Comment by apoorvkapil** [comment]
@tudi2d Backstage app is running but the backend is still running on the root domain, while frontend app is trying to resolve it on relative path, which is why i am getting the error shown above.
I am using relative path while building as mentioned in above `yarn build:backend` command

**Comment by Rugvip** [comment]
With a build-time baseUrl path of `.` the frontend will expect the backend to live at the root of the origin on the page. If your Backstage instance is hosted at `/backstage` then you should use `/backstage` as the `baseUrl` config for both your frontend and backend at build time.

**Comment by apoorvkapil** [comment]
I tried doing that but the backend is still live at root, and even the frontend is broken with this.

below is the build config i modified to and using following command for build

`yarn build:backend --config ../../app-config.yaml  --config ../../app-config.docker.build.yaml`

app-config.build.yaml
```
app:
    baseUrl: '/backstage'

backend:
    baseUrl: '/backstage'

```

Please note i am running the app as plugin for backend, using following command

`yarn start-backend --config ../../app-config.yaml --config ../../app-config.local.yaml`


app.config is same as provided by backstage. i am overriding the config using below local file.

app-config.local.yaml

```
app:
    title: Scaffolded Backstage App
    baseUrl: http://localhost:7007/backstage

backend:
    baseUrl: http://localhost:7007/backstage

```

**Comment by emilefokkema** [comment]
I created a minimal reproduction of this: [this repo](https://github.com/emilefokkema/backstage-test). Run `yarn install` and then `yarn dev`. When navigating to `localhost:3000/backstage`, you see the sign-in page. It makes a request to the back-end at path `/backstage/api/auth/guest/refresh`, which results in a 404.

**Comment by Rugvip** [comment]
@emilefokkema ah, if you set `backend.baseUrl` to `http://localhost:7007/backstage` that's where it'll need to be available, i.e. you need a proxy in front. What you might want for local development is the following:

```yaml
app:
    title: Scaffolded Backstage App
    baseUrl: http://localhost:7007/backstage

backend:
    baseUrl: http://localhost:7007
```

**Comment by emilefokkema** [comment]
@Rugvip Thank you for your clear answer. Unfortunately, our (@apoorvkapil 's and mine) use case is: we would like to host our instance on a domain `this.other.domain`, but there is this rule that is outside our control that says that our instance, be it front-end or back-end, can only be accessible from `this.other.domain/our-path`. So our back-end's `baseUrl` cannot be `this.other.domain`.

Would you be open to this being added as a feature? In other words: if the back-end's `baseUrl` is of the form `some.cool.domain/some-path/or-other`, that Backstage's backend will then respond to requests whose paths start with `/some-path/or-other`?

**Comment by Rugvip** [comment]
@emilefokkema ah I see what you mean. The fact that you have an existing domain and host apps on sub-paths implies that you have a proxy in the request path. Would you be able to configure that proxy so that it strips the path prefix for incoming requests? So that when it receives `some.cool.domain/backstage/some-path` it forwards the request to the Backstage instance as for example `backstage.internal/some-path`? That's the typical way to set this up and we'd prefer to avoid adding this configuration.
