### ISSUE TITLE
🐛 Bug Report: CatalogClient/catalogServiceRef do not work in backend modules

### ISSUE THREAD

**Issue by swnia** [backstage/backstage#23940]
### 📜 Description

Since the upgrade to 1.24.0, when using either the CatalogClient or the `catalogServiceRef` to access the catalog in the backend fail due to missing authentication.

### 👍 Expected behavior

The requests should be sent with the correct service token such that the requests are not rejected for missing authentication.

### 👎 Actual Behavior with Screenshots

All requests are rejected with a 401 due to the missing token.
<img width="1508" alt="401 when querying catalog" src="https://github.com/backstage/backstage/assets/119884634/b8cb7279-8a1f-496a-82b3-61b94e583afe">

### 👟 Reproduction steps

Run backstage v1.24.0+.
Create a backend plugin/module that utilises the `CatalogAPI` to look up anything in the catalog. Pass either a `CatalogClient` or a `catalogServiceRef` to the module and run it. No data will be returned as the requests trigger a 401.

To fix create the CatalogClient like this
```js
class CatalogFetchApi {
  constructor(
    private readonly logger: LoggerService,
    private readonly auth: AuthService,
  ) {}

  async fetch(input: any, init: RequestInit | undefined): Promise<Response> {
    const request = new Request(input as any, init);
    const { token } = await this.auth.getPluginRequestToken({
      onBehalfOf: await this.auth.getOwnServiceCredentials(),
      targetPluginId: 'catalog',
    });
    request.headers.set('Authorization', `Bearer ${token}`);
    this.logger.debug(`Added token to outgoing request to ${request.url}`);
    return fetch(request);
  }
}

[...]
           catalogApi: new CatalogClient({
              discoveryApi,
              fetchApi: new CatalogFetchApi(logger, auth),
            }),
[...]
```
Now all requests succeed.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
Yes, this is by design, you need to pass credentials to your client method calls - typically you use `auth.getPluginRequestToken` and pass it the right options for the circumstances.

This needs to be done explicitly, _by the caller_ instead of hidden inside the client, by design. Only the caller knows what type of credentials to supply (a pure service-to-service token, an on-behalf-of token, a pure forwarded user token,...).

**Comment by swnia** [comment]
Thanks for the explanation!
