### ISSUE TITLE
🐛 Bug Report: Tests using TechDocsAddonTester fail if resetAllMocks is called.

### ISSUE THREAD

**Issue by wss-dogara** [backstage/backstage#23943]
### 📜 Description

After upgrading from 1.23.3 to 1.25, our tests using `TechDocsAddonTester.buildAddonsInTechDocs` began failing with the error `Cannot read properties of undefined (reading 'ok')`.

After some debugging, I found that calling `jest.resetAllMocks()` in an `afterEach` call was removing the mocked implementation of the `fetchApi`. 

### 👍 Expected behavior

`TechDocsAddonTester` should not rely on jest mocks to be unchanged between tests. Using `jest.resetAllMocks()` is a common pattern to ensure tests are being isolated.

### 👎 Actual Behavior with Screenshots

`TechDocsAddonTester` declares API mocks at the top level of the file. This causes a call to `resetAllMocks` to remove the mocked implementation of the APIs passed to `TestApiProvider`.

### 👟 Reproduction steps

A minimal example test that fails from this bug:

```
describe('bugExample', () => {
  beforeEach(() => {
    jest.resetAllMocks();
  });

  test('Fails with an error', async () => {
    await TechDocsAddonTester.buildAddonsInTechDocs([])
      .withDom(
        <article>
          <div>Test Article</div>
        </article>,
      )
      .renderWithEffects();

    expect(true).toBe(true);
  });
});
```

### 📃 Provide the context for the Bug.

To ensure our tests are isolated we reset all mocks before each test runs. Currently working around this by calling mockReset on each mock used individually, but it's much simpler to use the global call.

### 🖥️ Your Environment

  @backstage/app-defaults                                          1.5.3
  @backstage/backend-app-api                                       0.5.14, 0.6.2
  @backstage/backend-common                                        0.19.10, 0.20.2, 0.21.6
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.9
  @backstage/backend-plugin-api                                    0.6.16
  @backstage/backend-tasks                                         0.5.21
  @backstage/backend-test-utils                                    0.3.6
  @backstage/catalog-client                                        1.6.3
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4
  @backstage/cli                                                   0.26.2
  @backstage/config-loader                                         1.7.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.3
  @backstage/core-compat-api                                       0.2.3
  @backstage/core-components                                       0.12.5, 0.13.10, 0.14.3
  @backstage/core-plugin-api                                       1.9.1
  @backstage/dev-utils                                             1.0.30
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.3
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.25
  @backstage/integration                                           1.9.1
  @backstage/plugin-adr-backend                                    0.4.13
  @backstage/plugin-adr-common                                     0.2.21
  @backstage/plugin-adr                                            0.6.16
  @backstage/plugin-api-docs                                       0.11.3
  @backstage/plugin-app-backend                                    0.3.64
  @backstage/plugin-app-node                                       0.1.16
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.8
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.8
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.11
  @backstage/plugin-auth-backend-module-github-provider            0.1.13
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.13
  @backstage/plugin-auth-backend-module-google-provider            0.1.13
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.11
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.13
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.9
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.7
  @backstage/plugin-auth-backend-module-okta-provider              0.0.9
  @backstage/plugin-auth-backend                                   0.22.3
  @backstage/plugin-auth-node                                      0.4.11
  @backstage/plugin-auth-react                                     0.0.3
  @backstage/plugin-azure-devops-backend                           0.6.3
  @backstage/plugin-azure-devops-common                            0.4.0
  @backstage/plugin-azure-devops                                   0.4.2
  @backstage/plugin-catalog-backend-module-azure                   0.1.36
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.14
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.14
  @backstage/plugin-catalog-backend                                1.21.0
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.3
  @backstage/plugin-catalog-import                                 0.10.9
  @backstage/plugin-catalog-node                                   1.11.0
  @backstage/plugin-catalog-react                                  1.11.2
  @backstage/plugin-catalog                                        1.18.2
  @backstage/plugin-entity-validation                              0.1.18
  @backstage/plugin-events-node                                    0.3.2
  @backstage/plugin-github-actions                                 0.6.14
  @backstage/plugin-home-react                                     0.1.11
  @backstage/plugin-home                                           0.7.2
  @backstage/plugin-linguist-backend                               0.5.14
  @backstage/plugin-linguist-common                                0.1.2
  @backstage/plugin-linguist                                       0.1.18
  @backstage/plugin-microsoft-calendar                             0.1.15
  @backstage/plugin-newrelic-dashboard                             0.3.8
  @backstage/plugin-org                                            0.6.23
  @backstage/plugin-permission-backend                             0.5.40
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.27
  @backstage/plugin-permission-react                               0.4.21
  @backstage/plugin-proxy-backend                                  0.4.14
  @backstage/plugin-scaffolder-backend-module-azure                0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.6
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.8
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.6
  @backstage/plugin-scaffolder-backend-module-github               0.2.6
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.2
  @backstage/plugin-scaffolder-backend                             1.22.3
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node-test-utils                     0.1.2
  @backstage/plugin-scaffolder-node                                0.4.2
  @backstage/plugin-scaffolder-react                               1.8.3
  @backstage/plugin-scaffolder                                     1.19.2
  @backstage/plugin-search-backend-module-catalog                  0.1.21
  @backstage/plugin-search-backend-module-pg                       0.5.25
  @backstage/plugin-search-backend-module-techdocs                 0.1.21
  @backstage/plugin-search-backend-node                            1.2.20
  @backstage/plugin-search-backend                                 1.5.6
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.9
  @backstage/plugin-search                                         1.4.9
  @backstage/plugin-sentry                                         0.5.18
  @backstage/plugin-sonarqube-backend                              0.2.18
  @backstage/plugin-sonarqube-react                                0.1.14
  @backstage/plugin-sonarqube                                      0.7.15
  @backstage/plugin-tech-radar                                     0.7.2
  @backstage/plugin-techdocs-addons-test-utils                     1.0.30
  @backstage/plugin-techdocs-backend                               1.10.3
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.8
  @backstage/plugin-techdocs-node                                  1.12.2
  @backstage/plugin-techdocs-react                                 1.2.2
  @backstage/plugin-techdocs                                       1.10.3
  @backstage/plugin-user-settings                                  0.8.4
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.3
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
@backstage/techdocs-maintainers and @wss-dogara what do you think about getting rid of the `jest.fn()` calls in [here](https://github.com/backstage/backstage/blob/2f138626ff2bfd1a6d2e2d7b39c7262aee815ffd/plugins/techdocs-addons-test-utils/src/test-utils.tsx#L185)? It has the side effect that people cannot assert calls on the default mocks, but in conversation with @backstage/maintainers, we believe that should not be expected.
