### ISSUE TITLE
🐛 Bug Report: Kubernetes POD resource utilization for Memory Limit show requested memory instead of limit 

### ISSUE THREAD

**Issue by deepan10** [backstage/backstage#23958]
### 📜 Description

Kubernetes POD resource utilization for Memory Limit show requested memory instead of total limit.

### 👍 Expected behavior

The Memory Limit should show the pod resource limit in Resource Utilization.

Since the PodDrawer calling ResoruceUtilization component for "Memory Limit" with `totalFormatted={bytesToMiB(podMetrics.memory.requestTotal)}`

https://github.com/backstage/backstage/blob/8bcf84bf3e43193c1fa9d2e4279e80461c740877/plugins/kubernetes-react/src/components/Pods/PodDrawer/PodDrawer.tsx#L128-L133

The below change potentially solves this issue
```typescript
<ResourceUtilization
  title="Memory limits"
  usage={podMetrics.memory.currentUsage}
  total={podMetrics.memory.limitTotal}
  totalFormatted={bytesToMiB(podMetrics.memory.limitTotal)}
/>
```

### 👎 Actual Behavior with Screenshots

It showing the pod resource request value. 

![image](https://github.com/backstage/backstage/assets/5843888/6e39565f-b981-4dbe-a692-1bc91152f353)

![image](https://github.com/backstage/backstage/assets/5843888/f02a8c81-964a-4708-aec2-1c3028851683)

### 👟 Reproduction steps

1. Go to Kubernetes Tab
2. Select the Cluster and then Pod 
3. View the Resource Utilization 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tudi2d** [comment]
cc @mclarke47
