### ISSUE TITLE
🚀 Feature: Workflow-Orchestration Plugin

### ISSUE THREAD

**Issue by alex-gunning** [backstage/backstage#23967]
### 🔖 Feature description

This feature aims to add a workflow-orchestration system into Backstage. This plugin would allow creating workflows which are generic enough to handle automating the work of a user-access team. This orchestration system should be able to save and load state from the database and transition according to the workflow rules.

More use-cases for generic workflows would most-likely be discovered in the future.

### 🎤 Context

Tooling access-control for developers is usually pain-point in companies. Sometimes it is controlled at an IDP level but more often than not requires some sort of manual process for onboarding - emails approvals, slack messages etc. 

Creating automated systems for onboarding can sometimes be complicated depending upon the use case. For example, to onboard a user onto security tooling one might need the following flow in Backstage.

- See if user's group is eligible in the catalog.
- Create a approval request (in-app and/or email) to user's line-manager.
- Approval Logic: 
  - Approved -> 
    - Create calls to SASS service to onboard user. 
    - Succeeded?
      - Send notification about approval.
      - Log domain event occurrence.
    - Failed?
      - Log failure.
      - Send error notification.
  - Rejected -> 
    - Send notification about rejection.

There multiple interactions here with different actors. (User, manager, API response) and these would all need their appropriate entrypoints into Backstage. The various entrypoints would not necessarily form part of this work. For example, exposing a router to listen to email clicks.

### ✌️ Possible Implementation

One fairly easy option would be to use something like [x-state](https://stately.ai/docs/state-machines-and-statecharts), which is a minimal-dependency typescript library. 
It can create complex state-machines, persist state and run side-effects. It has a nice visualisation library as well.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @alex-gunning, can you contrast this with the current Scaffolder and Software Templates? I feel like there's something I'm missing in why you are asking for this as I feel like the Scaffolder could do this.

Also, the idea of approvals or gates for the Scaffolder and Software Templates was requested here: https://github.com/backstage/backstage/issues/16622

**Comment by jbadeau** [comment]
Are you aware of https://github.com/janus-idp/backstage-plugins/tree/main/plugins/orchestrator

**Comment by alex-gunning** [comment]
@awanlin Thanks for the reply! You'll have to excuse my ignorance here as I'm not intimately familiar with scaffolder (My company has been mainly concerned with read-mode)

I had a similar intuition to you but from what I understand scaffolder is more of a resource/infrastructure creation tool. While it seems fairly flexible in what it can do, it seems very heavyweight and not suited to small complex interactions between steps (for instance parallelisation, races or logical retries). Yes, gating could go some ways in accomplishing what I want here.

Ideally, I'd like something that's lightweight, easy to build, and can persist and rehydrate on demand. Think an action occurring on a listener which pulls up a workflow, rehydrates it and advances it by the rules already present inside it before persisting it again. 

If that's possible and a realistic expectation in scaffolder's future then I guess I have my answer. I'm all in favour of not reinventing the wheel.

@jbadeau Thanks for this. I heard whispers. I'll take a look.

**Comment by awanlin** [comment]
Yeah, I just don't think that having multiple plugins with similar usage makes sense but I'm not sure what the full roadmap for the scaffolder is. Given your comments I'm not sure the Orchestrator plugin that @jbadeau mentioned would be any less "heavywieght" but I could be wrong it's pretty new to me.

It might be worth joining one of the Scaffolder SIGs to chat about this. The next one is actually tomorrow: https://calendar.google.com/calendar/u/0/embed?src=c_qup9gbhn9sqpuao6trttd8mk5s@group.calendar.google.com

**Comment by jbadeau** [comment]
In general, my feeling is that orchestrating things in scaffolding should be kept to a minimum as it’s not a workflow engine and has very basic or no support for common orchestration features. Running complex workflows should prob start with collecting user information in the scaffolder and then triggering workflows via a controlplane or api.  The Janus orchestration plugin is a frontend for sonataflow which support complex orchestrated and choreographed workflows.

**Comment by alex-gunning** [comment]
@jbadeau the capabilities seem very advanced but I think it's probably too much for what I was explaining above - given it's using an external process to orchestrate the workflows and all.

@awanlin Thanks for the link. I'll see if I can join tomorrow.

**Comment by alex-gunning** [comment]
Hey @awanlin I did bring this topic up at the SIG. You can see the writeup here 

https://docs.google.com/document/d/19VMhugnvmmX_F6tu-53_BsNknCxLme5VUzUCLa4nzSM/edit#heading=h.q3mrd0yojm8o

Just a TLDR I think we can conclude that scaffolder in its current form isn't really designed to handle workflows. In the future it may be able to handle certain aspects (retries, gating, resumes) but it's still a way off and even once there it still wouldn't be able to handle many common workflow actions.

**Comment by alex-gunning** [comment]
@awanlin Yeah, probably better rather not speculate about the adoption rate. What I know is what I mentioned above, this is a pain point for us and I imagine many other companies. Self-service is our aim here.

As you mentioned It's probably best I just build this with community help. After we get some adoption we'll be able to tell how useful it is where/if there is a place for it in the community.

**Comment by awanlin** [comment]
Awesome, sounds good to me @alex-gunning 🚀

**Comment by Alok650** [comment]
Hi @alex-gunning 
I have a use-case, which involves having an approval based workflow (maker-checker mechanism) within scaffolder templates. Please let me know if you were able to implement this gating feature.

**Comment by freben** [comment]
possibly related: #16622
