### ISSUE TITLE
🚀 Feature: Documentation Request: Guide on "Start Over" & Previewing Previous Template Tasks in Backstage

### ISSUE THREAD

**Issue by subbu-raj** [backstage/backstage#23966]
### 🔖 Feature description

I would like to request documentation on how to use the "Start Over" and "Preview Previous Template Tasks" features within the Backstage portal. 

### 🎤 Context

As a user of the Backstage portal, I often find myself needing to start over an already executed task or preview previous template tasks. However, I couldn't find any documentation on how to do these. Having a guide would be very helpful and improve the user experience.

### ✌️ Possible Implementation

The documentation should include:

1. A step-by-step guide on how to start over an already executed task.
2. Instructions on how to preview previous template tasks.
3. Screenshots or GIFs demonstrating the process.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by subbu-raj** [comment]
Thanks @tudi2d & @benjdlambert , Can you assign this issue to me, I can submit the PR with necessary documents

**Comment by tudi2d** [comment]
Sure - feel free to go ahead & draft a PR

**Comment by subbu-raj** [comment]
**Update on this issue:**

I have added the docs changes and they are currently being reviewed by the internal team in our company before I can create the PR.

Below is the snap of the changes for reference, these will appear under "docs/features/software-templates" in backstage.io. Can you have a look at it and let me know, if any changes needs to be made.

![Screenshot 2024-04-10 185438](https://github.com/backstage/backstage/assets/142309130/fb2719a4-4fca-4235-9740-65199364e8aa)
![Screenshot 2024-04-10 185509](https://github.com/backstage/backstage/assets/142309130/ec91428d-28f9-4f32-830b-2999800f70af)

**Comment by subbu-raj** [comment]
Thanks for the response @awanlin, 

We are trying to create the documentation that contains information for viewing the past template executions and executing the template with same input parameters used earlier. This documentation helps to make people aware of the options ("Task List" & "Start Over"). 
We were not aware of this options earlier, as we couldnt find the documentation.

The Template that we are using have more than 30 input parameters and they are split across various input sections, our template workflow also evaluates these inputs provided by the user and if they are valid it proceeds to create components and other elements.
If the inputs are invalid our template informs the user which fields are incorrect, so the user needs to execute the template again with different valid input. This "start over" & "task list" allowed us to edit the incorrect inputs used from previous run and execute the template again faster, even after few days.
These are very useful options and its easy to miss, thats why thought of documenting these features.

If you feel this should be documented else where, please do let me know.
