### ISSUE TITLE
🐛 Bug Report: Breaking change in auth breaks Backstage 1.23.x

### ISSUE THREAD

**Issue by mttwise** [backstage/backstage#23971]
### 📜 Description

Due to the addition of the new Auth Module, existing backstage instances have stopped working despite being built against the same package.json "^x.x.x" versions because breaking changes were included in the patch version bumps of some of the modules.

For example, in the search-backend-module-techdocs in commit `bb368a59` the original `tokenManager.getToken();` call was replaced with a call to the authPlugin.  This auth plugin doesn't exist in 1.23.x and therefore our deployments have started throwing a 500 error on an invalid token alg when trying to call techdocs.

![image](https://github.com/backstage/backstage/assets/24458226/3a600812-7eeb-4cc7-99ed-78a5656c5fef)

I am able to workaround this issue by pinning the versions in the package.json for both the frontend and backend to those listed on the lefthand side of the upgrade page (https://backstage.github.io/upgrade-helper/?from=1.23.4&to=1.24.0).

However, I have major concerns about the fact that a breaking change was released under a series of patch fixes which means that maintainability of the 1.23.x release is severely degraded  since any future bugs/vulnerability fixes cannot be easily picked up since the patch chain is now inclusive of these breaks.

Is it possible to correct this at this point and properly redo the package versioning bumps so the breaking change is moved to Major/Minor versioning bumps instead of patch?

### 👍 Expected behavior

Plugins that use the legacy auth token manager should continue to work as expected with the existing package.json provided by the 1.23.x version of bakcstage's recommended versions (coming from the backstage-cli and upgrade guide)

i.e. Techdocs should correctly render docs when selected by a user on the Docs page.

### The following error is observed in the backend logs when leveraging plugins that have been updated to use the new auth module:
```
backstage error Request failed with status 500 There was a problem performing the search query: "alg" (Algorithm) Header Parameter value not allowed type=errorHandler stack=Error: There was a problem performing the search query: "alg" (Algorithm) Header Parameter value not allowed
```

### The UI shows a 404 error, but the API call results in a 401:
![image](https://github.com/backstage/backstage/assets/24458226/a18e621c-0bdd-4a51-bb6e-aca6bf8d2508)

![image](https://github.com/backstage/backstage/assets/24458226/270b2a56-59cf-4cc4-9e96-009461a2d62f)

### 👟 Reproduction steps

1. Navigate to the Docs tab on the router
2. Try to open any doc

### 🖥️ Your Environment

```
OS:   Darwin 23.3.0 - darwin/arm64
node: v18.17.1
yarn: 1.22.21
cli:  0.25.2 (installed)
backstage:  1.23.4

Dependencies:
  @backstage/app-defaults                                          1.5.0, 1.5.3
  @backstage/backend-app-api                                       0.6.2
  @backstage/backend-common                                        0.21.6
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.9
  @backstage/backend-plugin-api                                    0.6.16
  @backstage/backend-tasks                                         0.5.21
  @backstage/backend-test-utils                                    0.3.6
  @backstage/catalog-client                                        1.6.3
  @backstage/catalog-model                                         1.4.4, 1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.7.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.3
  @backstage/core-compat-api                                       0.2.3
  @backstage/core-components                                       0.14.0, 0.14.3
  @backstage/core-plugin-api                                       1.9.0, 1.9.1
  @backstage/dev-utils                                             1.0.30
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.3
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.24, 1.1.25
  @backstage/integration                                           1.9.1
  @backstage/plugin-api-docs                                       0.11.0
  @backstage/plugin-app-backend                                    0.3.64
  @backstage/plugin-app-node                                       0.1.16
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.8
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.8
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.11
  @backstage/plugin-auth-backend-module-github-provider            0.1.13
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.13
  @backstage/plugin-auth-backend-module-google-provider            0.1.13
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.11
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.13
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.9
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.7
  @backstage/plugin-auth-backend-module-okta-provider              0.0.3, 0.0.9
  @backstage/plugin-auth-backend                                   0.21.0, 0.22.3
  @backstage/plugin-auth-node                                      0.4.8, 0.4.11
  @backstage/plugin-catalog-backend-module-aws                     0.3.11
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.14
  @backstage/plugin-catalog-backend                                1.21.0
  @backstage/plugin-catalog-common                                 1.0.21, 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.0
  @backstage/plugin-catalog-import                                 0.10.6
  @backstage/plugin-catalog-node                                   1.11.0
  @backstage/plugin-catalog-react                                  1.10.0, 1.11.2
  @backstage/plugin-catalog                                        1.17.0, 1.18.2
  @backstage/plugin-events-backend                                 0.2.22
  @backstage/plugin-events-node                                    0.2.22, 0.3.2
  @backstage/plugin-home-react                                     0.1.11
  @backstage/plugin-home                                           0.6.2
  @backstage/plugin-kubernetes-common                              0.7.5
  @backstage/plugin-org                                            0.6.20
  @backstage/plugin-permission-common                              0.7.12, 0.7.13
  @backstage/plugin-permission-node                                0.7.24, 0.7.27
  @backstage/plugin-permission-react                               0.4.20, 0.4.21
  @backstage/plugin-proxy-backend                                  0.4.14
  @backstage/plugin-scaffolder-backend-module-azure                0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.6
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.8
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.6
  @backstage/plugin-scaffolder-backend-module-github               0.2.6
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.2
  @backstage/plugin-scaffolder-backend                             1.22.3
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node-test-utils                     0.1.2
  @backstage/plugin-scaffolder-node                                0.4.2
  @backstage/plugin-scaffolder-react                               1.8.3
  @backstage/plugin-scaffolder                                     1.18.0
  @backstage/plugin-search-backend-module-catalog                  0.1.21
  @backstage/plugin-search-backend-module-pg                       0.5.25
  @backstage/plugin-search-backend-module-techdocs                 0.1.21
  @backstage/plugin-search-backend-node                            1.2.20
  @backstage/plugin-search-backend                                 1.5.6
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.6, 1.7.9
  @backstage/plugin-search                                         1.4.6
  @backstage/plugin-techdocs-backend                               1.10.3
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.5
  @backstage/plugin-techdocs-node                                  1.12.2
  @backstage/plugin-techdocs-react                                 1.1.16, 1.2.2
  @backstage/plugin-techdocs                                       1.10.0
  @backstage/plugin-user-settings                                  0.8.1
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.3
  @backstage/theme                                                 0.5.1, 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
  ```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Hmm, I don't think that's actually what's going on. The `auth` service that you're pointing to comes from a backwards compatibility wrapper which uses the `tokenManager` if the new `auth` service is not available: https://github.com/backstage/backstage/blob/d3b0655a0711b95d273bcfb86f991527c6533ee6/plugins/search-backend-module-techdocs/src/collators/DefaultTechDocsCollatorFactory.ts#L110-L114

The `alg` error is often a red herring, it's likely just not a valid backend token. Did you change anything related to config of backend secrets during the bump? Gonna need more specific reproduction steps to reproduce either way.

Regarding the versioning, see out https://backstage.io/docs/overview/versioning-policy#skew-policy, although I'll get it updated to explicitly mention the backend as well now that the backend system has an app package. TL;DR is that the app must be at the same or a more recent version compared to all plugins and modules that you install, i.e. you must always bump the app if you bump plugins, typically `@backstage/backend-defaults`

**Comment by mttwise** [comment]
@Rugvip, we haven't changed our code or package.json files at all. Our nightly build runs yarn to grab the latest patch packages and the issue started appearing as a result.
I have verified every package we are using is ^ marked against the values shown here https://backstage.github.io/upgrade-helper/?from=1.23.4&to=1.24.0 for 1.23.4.

To fix our instance, I needed to set "@backstage/plugin-techdocs-backend": "1.9.3" explicitly. If I change it to "@backstage/plugin-techdocs-backend": "^1.9.3" it breaks and starts giving the alg error.

Here is a working package.json vs non-working:

working:
```
{
  "name": "backend",
  "version": "1.1.0",
  "main": "dist/index.cjs.js",
  "types": "src/index.ts",
  "private": true,
  "license": "Apache-2.0",
  "description": "Backstage backend package",
  "backstage": {
    "role": "backend"
  },
  "scripts": {
    "start": "backstage-cli package start",
    "build": "backstage-cli package build",
    "lint": "backstage-cli package lint",
    "test": "backstage-cli package test --coverage --silent",
    "clean": "backstage-cli package clean",
    "build-image": "docker build ../.. -f Dockerfile --tag backstage"
  },
  "dependencies": {
    "@aws-sdk/client-cognito-identity-provider": "3.515.0",
    "@backstage/backend-common": "0.21.0",
    "@backstage/backend-tasks": "0.5.15",
    "@backstage/catalog-client": "1.6.0",
    "@backstage/catalog-model": "1.4.4",
    "@backstage/config": "1.1.1",
    "@backstage/plugin-app-backend": "0.3.58",
    "@backstage/plugin-auth-backend": "0.21.0",
    "@backstage/plugin-auth-node": "0.4.4",
    "@backstage/plugin-catalog-backend": "1.17.0",
    "@backstage/plugin-catalog-backend-module-aws": "0.3.7",
    "@backstage/plugin-events-backend": "0.2.22",
    "@backstage/plugin-permission-common": "0.7.12",
    "@backstage/plugin-permission-node": "0.7.21",
    "@backstage/plugin-proxy-backend": "0.4.8",
    "@backstage/plugin-scaffolder-backend": "1.21.0",
    "@backstage/plugin-search-backend": "1.5.0",
    "@backstage/plugin-search-backend-module-pg": "0.5.19",
    "@backstage/plugin-search-backend-node": "1.2.14",
    "@backstage/plugin-techdocs-backend": "1.9.3",
    "app": "file:../app",
    "jwt-decode": "^3.1.0",
    "prettier": "^3"
  },
  "devDependencies": {
    "@backstage/cli": "^0.25.2",
    "@types/cookie-parser": "1.4.3",
    "@types/dockerode": "3.3.17",
    "@types/lodash": "^4.17.0",
    "@types/luxon": "3.3.0",
    "@types/passport-oauth2": "1.4.12",
    "@types/uuid": "^9.0.2",
    "supertest": "^6.3.3"
  },
  "files": [
    "dist"
  ]
}

```
not working:
```
{
  "name": "backend",
  "version": "1.1.0",
  "main": "dist/index.cjs.js",
  "types": "src/index.ts",
  "private": true,
  "license": "Apache-2.0",
  "description": "Backstage backend package",
  "backstage": {
    "role": "backend"
  },
  "scripts": {
    "start": "backstage-cli package start",
    "build": "backstage-cli package build",
    "lint": "backstage-cli package lint",
    "test": "backstage-cli package test --coverage --silent",
    "clean": "backstage-cli package clean",
    "build-image": "docker build ../.. -f Dockerfile --tag backstage"
  },
  "dependencies": {
    "@aws-sdk/client-cognito-identity-provider": "3.515.0",
    "@backstage/backend-common": "0.21.0",
    "@backstage/backend-tasks": "0.5.15",
    "@backstage/catalog-client": "1.6.0",
    "@backstage/catalog-model": "1.4.4",
    "@backstage/config": "1.1.1",
    "@backstage/plugin-app-backend": "0.3.58",
    "@backstage/plugin-auth-backend": "0.21.0",
    "@backstage/plugin-auth-node": "0.4.4",
    "@backstage/plugin-catalog-backend": "1.17.0",
    "@backstage/plugin-catalog-backend-module-aws": "0.3.7",
    "@backstage/plugin-events-backend": "0.2.22",
    "@backstage/plugin-permission-common": "0.7.12",
    "@backstage/plugin-permission-node": "0.7.21",
    "@backstage/plugin-proxy-backend": "0.4.8",
    "@backstage/plugin-scaffolder-backend": "1.21.0",
    "@backstage/plugin-search-backend": "1.5.0",
    "@backstage/plugin-search-backend-module-pg": "0.5.19",
    "@backstage/plugin-search-backend-node": "1.2.14",
    "@backstage/plugin-techdocs-backend": "^1.9.3",
    "app": "file:../app",
    "jwt-decode": "^3.1.0",
    "prettier": "^3"
  },
  "devDependencies": {
    "@backstage/cli": "^0.25.2",
    "@types/cookie-parser": "1.4.3",
    "@types/dockerode": "3.3.17",
    "@types/lodash": "^4.17.0",
    "@types/luxon": "3.3.0",
    "@types/passport-oauth2": "1.4.12",
    "@types/uuid": "^9.0.2",
    "supertest": "^6.3.3"
  },
  "files": [
    "dist"
  ]
}

```

Also, regarding Algs, we are using the DefaultIdentityClient and setting the "RS256", but the alg error falls back to a different default list in the error that no longer contains RS256

![image](https://github.com/backstage/backstage/assets/24458226/a9689cd2-f090-4a7a-8f74-df252e2101cb)

**Comment by mttwise** [comment]
Just an update on this, the alg problem was not the direct issue.  The problem stemmed from the fact that our plugin environment did not implement the auth/httpAuth properties.  I still consider this breaking since it was working previously in 1.23.x until now.

The fix for this issue was to add the following logic when creating our PluginEnv and passing the auth/httpAuth to the affected createRouters (scaffolder/techdocs/search). 
```
  const { auth, httpAuth } = createLegacyAuthAdapters({
    auth: undefined,
    httpAuth: undefined,
    discovery: discovery,
    identity: identity,
  });
```

After implementing the code change, all of our modules are working with our existing auth code as expected.

**Comment by Rugvip** [comment]
@mttwise still likely something different going on tbh, best get to the bottom of why the tokens aren't valid in the original setup.

Do **not** call `createLegacyAuthAdapters` in legacy backend setup code, it's intended to be called within plugins, not in the backend wiring. The new auth services are not directly available for the old backend system. With your current code snippet you are disabling service auth for all backend plugins, which is potentially very dangerous.

**Comment by Rugvip** [comment]
@mttwise ah alright, would you be able to provide reproduction steps that lets us mimic your setup?

**Comment by mttwise** [comment]
@Rugvip I downloaded the 1.23.4 release and tried to reproduce the issue unsuccesfully. It seems that the issue is caused by one of a couple possible scenarios:

1. We started on 1.9 and have been upgrading each major release until now, so possible the default wiring has shifted from our fork
2. Our custom authorizer was implementing some logic incompatible with the new auth and it got exposed as a result of the patch bump for the new auth backwards compatibility support.

**Comment by aspic** [comment]
Hey! Adding to this since we're experiencing a similar issue. Specifically the frontend gets a 401 "(Algorithm) Header Parameter value not allowed" error from the backend. We're running with oauth2Proxy in front.

We've also been following major releases so in the same boat as @mttwise. However, we scrapped our custom auth code in favor of the oauth2Proxy provider and authentication seems to be working. But all backend calls when getting into Backstage results in 401s with the mentioned error message.

Ill see if I'm able to reproduce with a new backstage instance with our auth configuration.

**Comment by deedubs** [comment]
For the upgrade to 1.25 I went with creating a new backstage install and porting our config over, for our `oauth2proxy` configuration I have the following

```typescript
import { createBackendModule } from "@backstage/backend-plugin-api";
import { oauth2ProxyAuthenticator, OAuth2ProxyResult } from "@backstage/plugin-auth-backend-module-oauth2-proxy-provider";
import { authProvidersExtensionPoint, createProxyAuthProviderFactory, SignInInfo } from "@backstage/plugin-auth-node";

export default createBackendModule({
  pluginId: 'auth',
  moduleId: 'oauth2-proxy-provider',
  register(reg) {
    reg.registerInit({
      deps: {
        providers: authProvidersExtensionPoint,
      },
      async init({ providers }) {
        providers.registerProvider({
          providerId: 'oauth2Proxy',
          factory: createProxyAuthProviderFactory({
            authenticator: oauth2ProxyAuthenticator,
            signInResolver: async (
              info: SignInInfo<OAuth2ProxyResult>,
              ctx,
            ) => {
              const name = info.result.getHeader('X-Forwarded-Preferred-Username');
              if (!name) {
                throw new Error('Request did not contain a user')
              }
              const simplifiedUser = name.slice(0, name.lastIndexOf("@"));

              return ctx.signInWithCatalogUser({
                entityRef: { name: simplifiedUser },
              });
              }
            }),
          });
      }
    });
  }
});
```

Our `User` entities are synced in from KeyCloak hence the `simplifiedUser` business.  We are seeing the same error on backend calls.

>(Algorithm) Header Parameter value not allowed

We generate our backend secret via:
```hcl
resource "random_bytes" "backend_secret" {
  length = 24
}
```

And consume it as a env var

```yaml
backend:
  auth:
    keys:
      - secret: ${BACKEND_SECRET}
```

I can see a token getting issued in the logs:

```json
{"component":"token-factory","level":"info","message":"Issuing token for user:default/j.dan.williams, with entities user:default/j.dan.williams","plugin":"auth","service":"backstage"}
```

Not sure if there is any more information I can provide :)

**Comment by Rugvip** [comment]
Thank you for the extra info!

I'm not seeing anything obviously wrong here so I think it's best to try this on top of the 1.26 release going out tomorrow to help clarify what's going wrong. We've changed the authentication code to be a lot more explicit about incoming token types. The `alg` header error is usually a red herring where the actual error is that an incoming backend/frontend token is not valid and falls back to being validated as the wrong type of token.

**Comment by deedubs** [comment]
I've updated to 1.26 and you're correct about the `alg` being misdirection :)

```json
{
    "error": {
        "name": "AuthenticationError",
        "message": "Illegal token"
    },
    "request": {
        "method": "GET",
        "url": "/api/catalog/entity-facets?facet=relations.ownedBy"
    },
    "response": {
        "statusCode": 401
    }
}
```

When I decode the Authorization header that was sent with the above request I get:

```json
{
  "typ": "vnd.backstage.user",
  "alg": "ES256",
  "kid": "f1a1f46b-b991-4911-b668-db5dd78c9922"
}

{
  "iss": "https://staging.backstage.<redacted>/api/auth",
  "sub": "user:default/j.dan.williams",
  "ent": [
    "user:default/j.dan.williams"
  ],
  "aud": "backstage",
  "iat": 1713361575,
  "exp": 1713365175,
  "uip": "<redacted>"
}
```

**Comment by freben** [comment]
@deedubs It really looks OK ... can you double check that your `@backstage/backend-app-api` is on `0.7.0` and not older?

I'm starting to suspect that it's your oauth2proxy that's messing with the authorization header. Did you set it up with `pass-authorization-header` for example?

Do you have any way of tracking the exact token that gets _received_ by the backstage backend? Wireshark, a yarn patch that adds a console.log statement inside `DefaultAuthService.authorize`, or similar

**Comment by Rugvip** [comment]
@deedubs that looks like an extremely correct token x)

+1 to what Freben said, I don't think the token that is arriving in your backend is that one, or the `Authorization` header is malformed in some way. There's really no code path that'll get you that error if the token contains what you posted, regardless of the versions of different packages etc.

**Comment by deedubs** [comment]
Ah!

These are the settings we are passing `oauth2proxy`

```yaml
  OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST: "true"
  OAUTH2_PROXY_EMAIL_DOMAINS: <redacted>
  OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
  OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
  OAUTH2_PROXY_PASS_BASIC_AUTH: "true"
  OAUTH2_PROXY_PASS_USER_HEADERS: "true"
  OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
  OAUTH2_PROXY_SILENCE_PING_LOGGING: "true"
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
```

These are all over the place :/

After simplifying that down to:

```yaml
  OAUTH2_PROXY_EMAIL_DOMAINS: <redacted>
  OAUTH2_PROXY_SILENCE_PING_LOGGING: "true"
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
```

I'm no longer getting the "Illegal token" :(

Thanks so much for your help and work on Backstage @freben and @Rugvip, and apologies for the wild goose chase. Hopefully my ride on the struggle-bus will save someone else the same.

**Comment by Rugvip** [comment]
@deedubs nice! No worries, and glad that this clearer error let us narrow it down more quickly :+1:

**Comment by Rugvip** [comment]
Gonna close this as all known issues are resolved. Please open a new issue if you run into any problems with the `1.26` release.

**Comment by ggkoning** [comment]
> I realized that we had a custom legacy plugin adapter that wasn't forwarding the new Auth services (just the legacy identity and token manager). Once I updated it to do so, things started working again

@alecjacobs5401 I might have the same issue as you would you please show me your legacy plugin adapter before and after that change you made?
