### ISSUE TITLE
🐛 Bug Report: Parameter 'term' must be url encoded.

### ISSUE THREAD

**Issue by joaquin386** [backstage/backstage#23973]
### 📜 Description

When clicking on `Search` and trying to search with a space on the name `text text` (white space between both text strings) getting an error 400 back.

### 👍 Expected behavior

Search is able to be done with space in it

### 👎 Actual Behavior with Screenshots

<img width="1262" alt="image" src="https://github.com/backstage/backstage/assets/14437027/eed4368c-c28d-4f6f-a257-5d0168fcd1a0">

### 👟 Reproduction steps

- Backstage Home Page
- Top left panel click `Search`
- type `text text` into the search 

### 📃 Provide the context for the Bug.

Not able to search with a whitespace in the text.

OS: vf-cep-backstage-597db888f4-8qddm: Linux 5.10.210-201.855.amzn2.x86_64 - linux/x64
Resources: Memory: 4703/31737MB - Load: 2.00/2.10/2.16
node: v18.20.0
backstage: 1.25.1
Dependencies:
    @backstage/backend-app-api: 0.5.10, 0.5.14, 0.5.8, 0.6.2
    @backstage/backend-common: 0.19.10, 0.19.9, 0.20.1, 0.21.3, 0.21.6
    @backstage/backend-dev-utils: 0.1.2, 0.1.3, 0.1.4
    @backstage/backend-openapi-utils: 0.1.0, 0.1.6
    @backstage/backend-plugin-api: 0.6.13, 0.6.16, 0.6.7, 0.6.9
    @backstage/backend-tasks: 0.5.12, 0.5.14, 0.5.18, 0.5.21
    @backstage/catalog-client: 1.4.6, 1.5.2, 1.6.0, 1.6.3
    @backstage/catalog-model: 1.4.3, 1.4.4, 1.4.5
    @backstage/cli-common: 0.1.13
    @backstage/cli-node: 0.1.5, 0.2.0, 0.2.2, 0.2.3, 0.2.4
    @backstage/cli: 0.23.1
    @backstage/config-loader: 1.5.3, 1.6.1, 1.6.2, 1.7.0
    @backstage/config: 1.1.1, 1.2.0
    @backstage/e2e-test-utils: 0.1.0
    @backstage/errors: 1.2.3, 1.2.4
    @backstage/eslint-plugin: 0.1.3
    @backstage/integration-aws-node: 0.1.12, 0.1.8, 0.1.9
    @backstage/integration: 1.7.2, 1.8.0, 1.9.0, 1.9.1
    @backstage/plugin-auth-backend-module-gcp-iap-provider: 0.2.1
    @backstage/plugin-auth-backend-module-github-provider: 0.1.4
    @backstage/plugin-auth-backend-module-gitlab-provider: 0.1.4
    @backstage/plugin-auth-backend-module-google-provider: 0.1.4
    @backstage/plugin-auth-backend-module-oauth2-provider: 0.1.4
    @backstage/plugin-auth-backend: 0.19.4
    @backstage/plugin-auth-node: 0.4.1, 0.4.11, 0.4.3, 0.4.8
    @backstage/plugin-azure-devops-backend: 0.5.1
    @backstage/plugin-azure-devops-common: 0.3.2
    @backstage/plugin-catalog-backend-module-azure: 0.1.26
    @backstage/plugin-catalog-backend-module-github: 0.4.5
    @backstage/plugin-catalog-backend-module-scaffolder-entity-model: 0.1.4
    @backstage/plugin-catalog-backend-module-unprocessed: 0.3.6
    @backstage/plugin-catalog-backend: 1.15.0
    @backstage/plugin-catalog-common: 1.0.18, 1.0.20
    @backstage/plugin-catalog-node: 1.5.0, 1.6.1
    @backstage/plugin-devtools-backend: 0.2.6
    @backstage/plugin-devtools-common: 0.1.8
    @backstage/plugin-events-node: 0.2.16
    @backstage/plugin-linguist-backend: 0.5.4
    @backstage/plugin-linguist-common: 0.1.2
    @backstage/plugin-permission-backend: 0.5.32
    @backstage/plugin-permission-common: 0.7.10, 0.7.12, 0.7.13
    @backstage/plugin-permission-node: 0.7.18, 0.7.20, 0.7.24, 0.7.27
    @backstage/plugin-proxy-backend: 0.4.5
    @backstage/plugin-scaffolder-backend: 1.19.1
    @backstage/plugin-scaffolder-common: 1.4.3
    @backstage/plugin-scaffolder-node: 0.2.8
    @backstage/plugin-search-backend-module-catalog: 0.1.11
    @backstage/plugin-search-backend-module-pg: 0.5.22
    @backstage/plugin-search-backend-module-techdocs: 0.1.11
    @backstage/plugin-search-backend-node: 1.2.11, 1.2.17
    @backstage/plugin-search-backend: 1.4.7
    @backstage/plugin-search-common: 1.2.8, 1.2.10
    @backstage/plugin-tech-insights-backend-module-jsonfc: 0.1.48
    @backstage/plugin-tech-insights-backend: 0.5.30
    @backstage/plugin-tech-insights-common: 0.2.12
    @backstage/plugin-tech-insights-node: 0.4.15, 0.5.2
    @backstage/plugin-techdocs-backend: 1.9.0
    @backstage/plugin-techdocs-node: 1.10.0
    @backstage/plugin-todo-backend: 0.3.5
    @backstage/release-manifests: 0.0.10
    @backstage/repo-tools: 0.6.3
    @backstage/types: 1.1.1

### 🖥️ Your Environment

All pour environments are affected by this issue

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue
Maybe similar to this https://github.com/backstage/backstage/issues/19499 but not the same.

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by tudi2d** [comment]
This might be related to OpenAPI (cc @aramissennyeydd)

**Comment by awanlin** [comment]
Hi @joaquin386, it's really helpful to include your environment details by running `yarn backstage-cli info`, it would tell us what version you are on as well as the package versions. Can you please do that?

The Backstage Demo site is on the latest weekly release - `1.26.0-next.0` - and does not have this issue: https://demo.backstage.io/. There might be more to this error, I suspect it may have been fixed in a newer version though but without those details I can't say for sure.

**Comment by joaquin386** [comment]
@awanlin Sorry just added all the package information now to the OP.

**Comment by awanlin** [comment]
Thanks @joaquin386! So as I mentioned this works fine on the demo site. You are on the latest version but you also have many cases where multiple versions of the same packages are being used. I'm wondering if running `yarn dedupe` might help? Can you try that and see?

**Comment by aramissennyeydd** [comment]
Yeah, I think this is related to the OpenAPI tooling. @joaquin386 Do you have a custom search frontend? Can you share your frontend package versions?

**Comment by joaquin386** [comment]
Thanks guys for the support, I will try to dedupe as mention by @awanlin. I do not have a custom FrontEnd just the standard Bakcstage one but in the future we plan to customise it (not yet). Will let you know about the dedupe and see if it helps.

**Comment by joaquin386** [comment]
Checking a bit more from the FE I send correctly the request (from the DeveloperTools):
```
Request
:method: GET
:scheme: https
:authority: website.com
:path: /api/backstage/api/search/query?term=dop%20hello&types%5B0%5D=software-catalog
```
```
Response:
Response
:status: 400
```

Then inside the BE container:
```
$ curl http://127.0.0.1:7007/api/search/query?term=dop+hello
{"error":{"name":"InputError","message":"Parameter 'term' must be url encoded. Its value may not contain reserved characters."},"request":{"method":"GET","url":"/query?term=dop+hello"},"response":{"statusCode":400}}
```
```
$ curl http://127.0.0.1:7007/api/search/query?term=dop%20hello
{"results":[]}
```

**Comment by awanlin** [comment]
It should be including `%20` as that's an encoded space.

**Comment by aramissennyeydd** [comment]
Just a heads up, I have a PR out to allow the `+`, #23998.

**Comment by joaquin386** [comment]
We have this setup:
WAF->CloudFront->FE S3 Bucket->AWS API Gw -> BE k8s -> Any third party service.

So the problem from our side is that the AWS API GW will always return a `+` for a whitespace, I did open a ticket to AWS API Gw Team Support on AWS and they confirm me this behaviour and it is how the output to the BE works with spaces.

So the PR is pretty handy because it is the only way this issue can be solve (if there was a direct connection FE,BE then this issue would not have been present but adding extra layers does show up this limitation).

Thanks

**Comment by freben** [comment]
See discussion in the PR - I do argue that handling `+` as spaces should always have been the default without extra settings (it's quite correct in the query part - `+` has always been the default choice as far as I knew!) so I'm a bit confused. :) But yeah no matter how the technical bits turn out, the end result should be that we accept those pluses just fine.

**Comment by joaquin386** [comment]
FYI tested and working as expected now. Thanks for the quick response.
