### ISSUE TITLE
Support client secret rotation for oauth providers, proxies, and gateways

### ISSUE THREAD

**Issue by tkrop** [backstage/backstage#2397]
Currently, backstage has the convention to configure client secrets, e.g. for auth-providers, via the `app-config.yaml`, which is loaded only once at application startup. Since Zalando supports for security reasons automated rotation of (service) client secrets, we need to find a way to reconfigure auth-providers, regularly with new client secrets.

## Feature Suggestion
Support rotation of client secrets (an client ids) for authentication providers, proxies, and gateways, that need to authenticate service requests and where the user token is not applicable.

## Context
Zalando for security reasons requires and supports automated rotation of client secrets, i.e. service credentials. This makes support for dynamic rotation of client secrets obligatory to utilize backstage. To account for client secret rotation we usually implement a token provider, that is configured with the credentials directory to support the dynamic resolution of tokens as client credentials. The token provider is usually injected into all auth-provider, proxy, and gateway components to resolve a new token in case of authorization failures.

## Possible Implementation
To implement client secret rotation, we can see the following two generic approaches in backstage:

1. Improve the configuration mechanism in backstage to be aware of changes to configuration files. This may be focused very specifically on [file secrets](https://github.com/spotify/backstage/blob/master/docs/conf/writing.md#file-secrets) or much broader on any configuration file involved.
2. Change the authentication provider(s) to support the configuration/reading of secret files directly and make them aware of secret rotation. This can be accomplished by injecting a secret-provider, that  can be utilized by auth-providers, as well as other proxies and gatways in need of secrets, to dynamically provide the newest rotating secrets on after authentication failures.

While solution (1) tracking of all config changes is very appealing, efficient tracking usually requires native filesystem support. However, it is unclear whether TypeScript provides enough support. Also the different configuration methods, i.e. environment variable overriding, [env secrets](https://github.com/spotify/backstage/blob/master/docs/conf/writing.md#env-secrets), [file secrets](https://github.com/spotify/backstage/blob/master/docs/conf/writing.md#file-secrets), and [data file secrets](https://github.com/spotify/backstage/blob/master/docs/conf/writing.md#data-file-secrets) make such a solution complex.

The usually cheaper and most efficient solution applied in Zalando is to allow for configuration of client-id and client-secret via files and enable auth providers to react on an invalid token response by re-reading the secret files. This is well supported by our Kubernetes setup, since all Certificates are translated into files: see https://kubernetes-on-aws.readthedocs.io/en/latest/user-guide/zalando-iam.html.

**Comment by taras** [comment]
@tkrop have you considered allowing Kubernetes to take care of restarting pods when secrets change? There are several approaches for doing this,

1. https://github.com/pusher/wave - watches deployments & redeploys when secrets change
2. use readiness checks - check the validity of each secret in readiness checks, Kubernetes will check these every 10 seconds to figure out whether it needs to restart the process

Both of these approaches do not require any changes in Backstage.

**Comment by tkrop** [comment]
We have considered this carefully, however, we think, this is a very drastic and disruptive solution, that adds complexity by relying on orchestration of multiple services creating the risk of hard to predict failures during restarts. We think that such measurements should only be used as last resort. Besides, we are not aware of a single service in Zalando that requires restarts to rotate client secrets.

**Comment by taras** [comment]
> Besides, we are not aware of a single service in Zalando that requires restarts to rotate client secrets.

How do your services handle secret rotation now?

**Comment by tkrop** [comment]
All services implement a compensating pattern. Usually the service either reads the secret directly from a memory mapped file on each request, or it reacts on authorization failures by re-reading the secret from the file and retrying the request.

**Comment by tkrop** [comment]
@taras @Rugvip @freben have you had time to think about about our suggestions? We would like to move on being able to contribute?

**Comment by taras** [comment]
@tkrop thank you for entertaining my question. 

It sounds like storing secrets on the file system and re-reading them as necessary will do the trick. Special considerations may be necessary to ensure that plugins can participate. For example, if a plugin's request determines that a secret is invalid, how does it invalidate the secret and cause it to be re-fetched? 

I'll leave it to the core team to suggest an approach here.

**Comment by tkrop** [comment]
As I tried to describe as one solution above:

We usually have a `secret-provider` or `storage` that is injected into all locations, i.e. authorization providers, gateways, and proxies, that need access to a secrets. The contract may change a bit from implementation to implementation, but the general understanding is, that it provides a secret based on a `secret-id/name`. The name usually refer to a secret-set containing the `secret-id` and the `secret-key`. The set is primarily mapped to a pair of files located in a credentials directory, however, the content can usually be also overriden by environment variables. The secret provider usually caches the secret-set content and manages a lifetime to support rotation. Alternatively, it allows to enforce the invalidation of the secret.

Simple (specialized) implementations of a `secret-provider` are usually below `100` lines of go-code. However, I think we can implement this concept in a slightly more generic way so that smoothly fits into backstage's existing configuration concept without breaking configuration.

**Comment by tkrop** [comment]
@Rugvip @freben any opinion?

**Comment by tkrop** [comment]
Since we got no feedback on how to proceed for the community, we implement an internal solution for now.

**Comment by Rugvip** [comment]
@tkrop alright, probably best way forward for now for you to get unblocked. A proper implementation in the config system is a bit more work.

The way forward imo is to start by making the `ConfigReader` be backed by a mutable state that is shared or otherwise connected with the output of `@backstage/config-loader`. After that we could look at options around watching/polling/observing config.

**Comment by tkrop** [comment]
@Rugvip sound a great way to proceed. But I'm also a bit scared. We have realized that most components extract and store there configuration internally during setup. To have this changed consistently is a lot of work.

Please feel free to close this issue.

**Comment by Rugvip** [comment]
@tkrop yep, and it's likely not reasonable to require all configuration to be watchable. I think enabling the possibility would be the first step, but then we'd have to do more targeted changes to support on-the-fly changes of specific config values.

It does add a bunch of friction to the implementation of features if you have to support config updates, so tbh I think it's good to not require it in any way.
