### ISSUE TITLE
🐛 Bug Report: Azure DevOps Backend fails to start, missing config value at 'azureDevOps.token'

### ISSUE THREAD

**Issue by dylanjustice** [backstage/backstage#23995]
### 📜 Description

When upgrading to v0.6.3 of @backstage/azure-devops-backend the backend fails to start with the message `Backend failed to start up Error: Missing required config value at 'azureDevOps.token' in 'app-config.local.yaml'`
Downgrading to v0.5.1 resolves the error.

### 👍 Expected behavior

azureDevOps config section should be deprecated and not required.

### 👎 Actual Behavior with Screenshots

 Backend failed to start up Error: Missing required config value at 'azureDevOps.token' in 'app-config.local.yaml'

### 👟 Reproduction steps

Remove azureDevOps section from app-config.yaml, use only the integrations.azure for authentication. Preferably a managed identity. Bump to latest backstage version with azure-devops-backend@v0.6.3, yarn run dev.

### 📃 Provide the context for the Bug.

```
 Backend failed to start up Error: Missing required config value at 'azureDevOps.token' in 'app-config.local.yaml'
[1]     at ConfigReader.getString (C:\projects\tfs\platform\backstage\node_modules\@backstage\config\src\reader.ts:350:13)
[1]     at ObservableConfigProxy.getString (C:\projects\tfs\platform\backstage\node_modules\@backstage\backend-app-api\src\config\ObservableConfigProxy.ts:117:30)
[1]     at createRouter (C:\projects\tfs\platform\backstage\node_modules\@backstage\plugin-azure-devops-backend\src\service\router.ts:62:14)
[1]     at createPlugin (c:\projects\tfs\platform\backstage\packages\backend\src\plugins\azure-devops.ts:6:22)
[1]     at main (c:\projects\tfs\platform\backstage\packages\backend\src\index.ts:109:51)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### 🖥️ Your Environment

yarn run v1.22.19
$ C:\projects\tfs\platform\backstage\node_modules\.bin\backstage-cli info
OS:   Windows_NT 10.0.19045 - win32/x64
node: v18.17.1
yarn: 1.22.19
cli:  0.26.2 (installed)
backstage:  1.25.2

Dependencies:
  @backstage/app-defaults                                          1.5.3
  @backstage/backend-app-api                                       0.5.14, 0.6.2
  @backstage/backend-common                                        0.20.2, 0.21.6
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.9
  @backstage/backend-plugin-api                                    0.6.16
  @backstage/backend-tasks                                         0.5.21
  @backstage/backend-test-utils                                    0.3.6
  @backstage/catalog-client                                        1.6.3
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4
  @backstage/cli                                                   0.26.2
  @backstage/config-loader                                         1.7.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.3
  @backstage/core-compat-api                                       0.2.3
  @backstage/core-components                                       0.13.10, 0.14.3
  @backstage/core-plugin-api                                       1.9.1
  @backstage/dev-utils                                             1.0.30
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.3
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.25
  @backstage/integration                                           1.9.1
  @backstage/plugin-adr-backend                                    0.4.13
  @backstage/plugin-adr-common                                     0.2.21
  @backstage/plugin-adr                                            0.6.16
  @backstage/plugin-api-docs                                       0.11.3
  @backstage/plugin-app-backend                                    0.3.64
  @backstage/plugin-app-node                                       0.1.16
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.8
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.8
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.11
  @backstage/plugin-auth-backend-module-github-provider            0.1.13
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.13
  @backstage/plugin-auth-backend-module-google-provider            0.1.13
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.11
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.13
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.9
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.7
  @backstage/plugin-auth-backend-module-okta-provider              0.0.9
  @backstage/plugin-auth-backend                                   0.22.3
  @backstage/plugin-auth-node                                      0.4.11
  @backstage/plugin-auth-react                                     0.0.3
  @backstage/plugin-azure-devops-backend                           0.5.1
  @backstage/plugin-azure-devops-common                            0.3.2, 0.4.0
  @backstage/plugin-azure-devops                                   0.4.2
  @backstage/plugin-catalog-backend-module-azure                   0.1.36
  @backstage/plugin-catalog-backend-module-github                  0.5.7
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.24
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.14
  @backstage/plugin-catalog-backend-module-unprocessed             0.4.3
  @backstage/plugin-catalog-backend                                1.21.0
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.3
  @backstage/plugin-catalog-import                                 0.10.9
  @backstage/plugin-catalog-node                                   1.11.0
  @backstage/plugin-catalog-react                                  1.11.2
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.1
  @backstage/plugin-catalog-unprocessed-entities                   0.2.2
  @backstage/plugin-catalog                                        1.18.2
  @backstage/plugin-devtools-backend                               0.3.2
  @backstage/plugin-devtools-common                                0.1.9
  @backstage/plugin-devtools                                       0.1.12
  @backstage/plugin-events-node                                    0.3.2
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.37
  @backstage/plugin-explore                                        0.4.19
  @backstage/plugin-github-actions                                 0.6.14
  @backstage/plugin-home-react                                     0.1.11
  @backstage/plugin-home                                           0.7.2
  @backstage/plugin-org                                            0.6.23
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.27
  @backstage/plugin-permission-react                               0.4.21
  @backstage/plugin-proxy-backend                                  0.4.14
  @backstage/plugin-scaffolder-backend-module-azure                0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.6
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.8
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.6
  @backstage/plugin-scaffolder-backend-module-github               0.2.6
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.2
  @backstage/plugin-scaffolder-backend                             1.22.3
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node-test-utils                     0.1.2
  @backstage/plugin-scaffolder-node                                0.4.2
  @backstage/plugin-scaffolder-react                               1.8.3
  @backstage/plugin-scaffolder                                     1.19.2
  @backstage/plugin-search-backend-module-catalog                  0.1.21
  @backstage/plugin-search-backend-module-pg                       0.5.25
  @backstage/plugin-search-backend-module-techdocs                 0.1.21
  @backstage/plugin-search-backend-node                            1.2.20
  @backstage/plugin-search-backend                                 1.5.6
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.9
  @backstage/plugin-search                                         1.4.9
  @backstage/plugin-sonarqube-backend                              0.2.18
  @backstage/plugin-sonarqube-react                                0.1.14
  @backstage/plugin-sonarqube                                      0.7.15
  @backstage/plugin-tech-radar                                     0.7.2
  @backstage/plugin-techdocs-backend                               1.10.3
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.8
  @backstage/plugin-techdocs-node                                  1.12.2
  @backstage/plugin-techdocs-react                                 1.2.2
  @backstage/plugin-techdocs                                       1.10.3
  @backstage/plugin-user-settings                                  0.8.4
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.3
  @backstage/theme                                                 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @dylanjustice, this is very strange. It was deprecated in `0.6.0`: https://github.com/backstage/backstage/blob/master/plugins/azure-devops-backend/CHANGELOG.md#060

The entire config is optional: https://github.com/backstage/backstage/blob/229ce8be63fb5813595e551b29a81d051f7dd021/plugins/azure-devops-backend/config.d.ts#L21

But I do see that `token` is not, do you have some of this config in place somewhere in you `app-config.yaml` or a `app-config.*.yaml`?

**Comment by awanlin** [comment]
Nope, I see the bug, it's right here:

https://github.com/backstage/backstage/blob/229ce8be63fb5813595e551b29a81d051f7dd021/plugins/azure-devops-backend/src/service/router.ts#L62

This should be `getOptionalString` :(

**Comment by awanlin** [comment]
PR to fix it is here: https://github.com/backstage/backstage/pull/23996

**Comment by dylanjustice** [comment]
> Nope, I see the bug, it's right here:
> 
> https://github.com/backstage/backstage/blob/229ce8be63fb5813595e551b29a81d051f7dd021/plugins/azure-devops-backend/src/service/router.ts#L62
> 
> This should be `getOptionalString` :(

Nice! Good work finding that so quickly.

**Comment by awanlin** [comment]
Yeah, wish I didn't introduce a bug in the first place. Sorry about that :(
