### ISSUE TITLE
[Plugin] PagerDuty

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#240]
Create (port) a plugin for PagerDuty. It should primarily serve as an example of a Backstage integration.

**Comment by stefanalund** [comment]
@freben are you really doing this one? If not please remove yourself so that someone else can pick it up.

**Comment by andrewthauer** [comment]
I think this can be closed?

**Comment by Rugvip** [comment]
Yep! Fixed by https://github.com/backstage/backstage/pull/3317
