### ISSUE TITLE
🚀 Feature (catalog): log the number of api requests needed for catalog processing

### ISSUE THREAD

**Issue by novellat** [backstage/backstage#24008]
### 🔖 Feature description

The catalog plugin is processing the catalog every _processingInterval_ seconds.
It would be useful to see how exhausting (on the apis) is all this requesting.

### 🎤 Context

Many users of backstage are hitting the github rate limits and this would help in debugging it

### ✌️ Possible Implementation

After every cycle processing cycle I'd like to see soem summary such as:

```
Processing entities in http://github.com/blah/locations.yaml required 345 requests.
Processing entities in http://github.com/blahblah/locations.yaml required 234 requests.
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by zcason** [comment]
Is there any documentation on soem that you can provide for context?

**Comment by novellat** [comment]
I see. That's fair enough, thanks.

Our current rate limit issue was solved by adjusting the refreshInterval and we hope this has fixed the issues forever.

 In the ideal case I'd be able to at least implement logging every github request, but that cannot be part of the mainline, since he debug logs would overwhelm the system. 

One last question (I haven't delved into it that much yet) - what is normally being downloaded every `refreshInterval` seconds? The whole contents of the catalogs, or only the new commits/git diff ?
