### ISSUE TITLE
🐛 Bug Report: incorrect policy check for Github Users

### ISSUE THREAD

**Issue by manishprivet** [backstage/backstage#24073]
### 📜 Description

Github allows usernames ending with `-`, however the default policy regex for `metadata.name` is `^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9-]$`, which makes username ending with `-` invalid. This is resulting in Github org data ingestion incorrect and buggy, and I cannot add the team member manually as well.

### 👍 Expected behavior

It should allow usernames ending with `-` as a valid `metadata.name` for entity type `User`

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/54291836/4ed688a8-51fe-4651-aed1-e9d884c0cf53)

### 👟 Reproduction steps

1. Try ingesting a User entity with name ending with `-`

### 📃 Provide the context for the Bug.

https://backstage.io/docs/integrations/github/org/

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Updated the docs https://github.com/backstage/backstage/pull/24075
