### ISSUE TITLE
🐛 Bug Report: Default catalog processing interval doesn't follow the suggestion

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#24115]
### 📜 Description

Default catalog processing config says the following:
```js
* ```yaml
* catalog:
*   processingInterval: { minutes: 30 }
* ```
*
* Note that this is only a suggested minimum, and the actual interval may
* be longer. Internally, the catalog will scale up this number by a small
* factor and choose random numbers in that range to spread out the load. If
* the catalog is overloaded and cannot process all entities during the
* interval, the time taken between processing runs of any given entity may
* also be longer than specified here.
```

While the default processing interval is as:

```ts
return createRandomProcessingInterval({
  minSeconds: 100,
  maxSeconds: 150,
});
```

### 👍 Expected behavior

The defaults should follow the suggested configuration

### 👎 Actual Behavior with Screenshots

Processing of entities is running a lot of times causing issues if config is not in place

### 👟 Reproduction steps

Start backstage with some catalog processors

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Hm. I don't think there's a problem really - the code block is just an example of how to set it. The text below is general and doesn't refer to the code block at all. When it says "this is only a suggested minimum", it refers to whatever you set `processingInterval` to. If you set it to one minute, you tell the catalog that your suggested minimum is one minute. And then the catalog [does scale that up](https://github.com/backstage/backstage/blob/2ca9dc00b2a1d26cbf8f4700463bdeeb962fec55/plugins/catalog-backend/src/service/CatalogBuilder.ts#L845) as stated to form a random range.

Feel free to suggest a rewording of the text to make it clearer though.
