### ISSUE TITLE
🐛 Bug Report: Creation of Auth custom resolvers lead to NotFoundError

### ISSUE THREAD

**Issue by darrenyung** [backstage/backstage#24118]
### 📜 Description

I'm using Microsoft Provider for user authentication in my org instance of Backstage with additional resolution logic to consolidate user profiles from various systems. 

With the recent version release (https://backstage.io/docs/releases/v1.24.0#auth-backend-guest-module), I need to move the auth module over to the new backend system. 

With this [guide](https://backstage.io/docs/backend-system/building-backends/migrating#custom-resolver), I tried to port across the resolution logic but during local runtime, I ran into an unknown error.

Did I miss something?

### 👍 Expected behavior

User login successfully

### 👎 Actual Behavior with Screenshots

Popup dialog provided an output with error

### 👟 Reproduction steps

1. Use the new backend system

Backend index.ts as follows
```
const backend = createBackend();

// Auth Modules
backend.add(import('@backstage/plugin-auth-backend'));
backend.add(import('@backstage/plugin-auth-backend-module-guest-provider'));
// backend.add(import('@backstage/plugin-auth-backend-module-microsoft-provider'));
backend.add(authModuleMicrosoftProvider);

backend.start();
```

Custom provider in different file as follows

```
export const authModuleMicrosoftProvider = createBackendModule({
  pluginId: 'auth',
  moduleId: 'microsoft-provider',
  register(reg) {
    reg.registerInit({
      deps: {
        providers: authProvidersExtensionPoint,
        logger: coreServices.rootLogger,
        config: coreServices.rootConfig,
      },
      async init({ config, logger, providers }) {
        providers.registerProvider({
          providerId: 'microsoft',
          factory: createOAuthProviderFactory({
            authenticator: microsoftAuthenticator,
            async signInResolver({ profile }, ctx) {
              if (!profile.email) {
                throw new Error(
                  'Login failed, user profile does not contain an email',
                );
              }

              const [localPart] = profile.email.split('@');

              // Custom profile retriever and resolution logic

              const userEntityRef = stringifyEntityRef({
                kind: 'User',
                name: localPart,
                namespace: DEFAULT_NAMESPACE,
              });
              return ctx.issueToken({
                claims: {
                  sub: userEntityRef,
                  ent: [userEntityRef],
                },
              });
            },
          }),
        });
      },
    });
  },
```

### 📃 Provide the context for the Bug.

Popup error content

```
"error": {
    "name": "NotFoundError",
    "message": "No auth provider registered for 'microsoft'",
    "stack": "NotFoundError: No auth provider registered for 'microsoft'\n    at \u003Canonymous\u003E 
...
  },
  "request": {
    "method": "GET",
    "url": "/api/auth/microsoft/start?scope=openid%20offline_access%20profile%20email%20User.Read&origin=http%3A%2F%2Flocalhost%3A3000&flow=popup&env=development"
  },
  "response": {
    "statusCode": 404
  }
}
```

### 🖥️ Your Environment

OS:   Darwin 23.4.0 - darwin/x64
node: v20.11.0
yarn: 1.22.19
cli:  0.26.2 (installed)
backstage:  1.25.2

Dependencies:
  @backstage/app-defaults                                          1.5.3
  @backstage/backend-app-api                                       0.5.14, 0.6.2
  @backstage/backend-common                                        0.19.10, 0.21.6
  @backstage/backend-defaults                                      0.2.16
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.9
  @backstage/backend-plugin-api                                    0.6.16
  @backstage/backend-tasks                                         0.5.21
  @backstage/backend-test-utils                                    0.3.6
  @backstage/catalog-client                                        1.6.3
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4
  @backstage/cli                                                   0.26.2
  @backstage/config-loader                                         1.7.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.3
  @backstage/core-compat-api                                       0.2.3
  @backstage/core-components                                       0.11.2, 0.14.3
  @backstage/core-plugin-api                                       1.9.1
  @backstage/dev-utils                                             1.0.30
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.3
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.25
  @backstage/integration                                           1.9.1
  @backstage/plugin-api-docs                                       0.11.3
  @backstage/plugin-app-backend                                    0.3.64
  @backstage/plugin-app-node                                       0.1.16
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.8
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.8
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.11
  @backstage/plugin-auth-backend-module-github-provider            0.1.13
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.13
  @backstage/plugin-auth-backend-module-google-provider            0.1.13
  @backstage/plugin-auth-backend-module-guest-provider             0.1.2
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.11
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.13
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.9
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.7
  @backstage/plugin-auth-backend-module-okta-provider              0.0.9
  @backstage/plugin-auth-backend                                   0.22.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.11
  @backstage/plugin-auth-react                                     0.0.3
  @backstage/plugin-badges-backend                                 0.3.13
  @backstage/plugin-badges                                         0.2.57
  @backstage/plugin-bazaar-backend                                 0.3.14
  @backstage/plugin-bazaar                                         0.2.25
  @backstage/plugin-catalog-backend-module-github                  0.5.7
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.14
  @backstage/plugin-catalog-backend-module-unprocessed             0.4.3
  @backstage/plugin-catalog-backend                                1.21.0
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.3
  @backstage/plugin-catalog-import                                 0.10.9
  @backstage/plugin-catalog-node                                   1.11.0
  @backstage/plugin-catalog-react                                  1.11.2
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.1
  @backstage/plugin-catalog-unprocessed-entities                   0.2.2
  @backstage/plugin-catalog                                        1.18.2
  @backstage/plugin-cost-insights-common                           0.1.2
  @backstage/plugin-cost-insights                                  0.12.22
  @backstage/plugin-devtools-backend                               0.3.2
  @backstage/plugin-devtools-common                                0.1.9
  @backstage/plugin-devtools                                       0.1.12
  @backstage/plugin-entity-validation                              0.1.18
  @backstage/plugin-events-node                                    0.3.2
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.37
  @backstage/plugin-explore                                        0.4.19
  @backstage/plugin-github-actions                                 0.6.14
  @backstage/plugin-github-issues                                  0.4.0
  @backstage/plugin-github-pull-requests-board                     0.1.27
  @backstage/plugin-home-react                                     0.1.11
  @backstage/plugin-home                                           0.7.2
  @backstage/plugin-kubernetes-backend                             0.16.4
  @backstage/plugin-kubernetes-common                              0.7.5
  @backstage/plugin-kubernetes-node                                0.1.10
  @backstage/plugin-kubernetes-react                               0.3.3
  @backstage/plugin-kubernetes                                     0.11.8
  @backstage/plugin-org                                            0.6.23
  @backstage/plugin-permission-backend                             0.5.40
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.27
  @backstage/plugin-permission-react                               0.4.21
  @backstage/plugin-playlist-backend                               0.3.20
  @backstage/plugin-playlist-common                                0.1.15
  @backstage/plugin-playlist                                       0.2.7
  @backstage/plugin-proxy-backend                                  0.4.14
  @backstage/plugin-scaffolder-backend-module-azure                0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.6
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.8
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.6
  @backstage/plugin-scaffolder-backend-module-github               0.2.6
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.2
  @backstage/plugin-scaffolder-backend                             1.22.3
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.2
  @backstage/plugin-scaffolder-react                               1.8.3
  @backstage/plugin-scaffolder                                     1.19.2
  @backstage/plugin-search-backend-module-catalog                  0.1.21
  @backstage/plugin-search-backend-module-elasticsearch            1.3.19
  @backstage/plugin-search-backend-module-pg                       0.5.25
  @backstage/plugin-search-backend-module-techdocs                 0.1.21
  @backstage/plugin-search-backend-node                            1.2.20
  @backstage/plugin-search-backend                                 1.5.6
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.9
  @backstage/plugin-search                                         1.4.9
  @backstage/plugin-shortcuts                                      0.3.22
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.48
  @backstage/plugin-tech-insights-backend                          0.5.30
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.5.2
  @backstage/plugin-tech-insights                                  0.3.25
  @backstage/plugin-tech-radar                                     0.7.2
  @backstage/plugin-techdocs-addons-test-utils                     1.0.30
  @backstage/plugin-techdocs-backend                               1.10.3
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.8
  @backstage/plugin-techdocs-node                                  1.12.2
  @backstage/plugin-techdocs-react                                 1.2.2
  @backstage/plugin-techdocs                                       1.10.3
  @backstage/plugin-todo-backend                                   0.3.15
  @backstage/plugin-todo                                           0.2.37
  @backstage/plugin-user-settings                                  0.8.4
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.3
  @backstage/theme                                                 0.2.19, 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 4.77s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by anicke** [comment]
We do something similar and it's working for us. I think the error comes from missing "providers" in the config. Have you added this: https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin? The "signIn/resolvers".

**Comment by darrenyung** [comment]
> We do something similar and it's working for us. I think the error comes from missing "providers" in the config. Have you added this: https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin? The "signIn/resolvers".

Thanks! I don't know how I missed that first paragraph while looking at the custom guide at the bottom! I got a different output now and able to progress. Thank you!
