### ISSUE TITLE
Expose localization on mui table

### ISSUE THREAD

**Issue by MadhuSudhanBhaskar** [backstage/backstage#24124]
### 🔖 Feature description

Currenty, from CatalogTable there is no way to update the **ACTIONS** to a different text.  The only way to update is via exposing the localization prop that exists on mui table.

### 🎤 Context

I have just save as an action in my tables, I need to replace/edit the ACTIONS header text to SAVE.

### ✌️ Possible Implementation

Exposing the prop via already existing interface seems to be a good place for implementation.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Cross linking to https://github.com/backstage/backstage/pull/23392 which does some advancements here but doesn't make any additions on the localization prop. @mario-mui fyi
