### ISSUE TITLE
🐛 Bug Report: httpAuth issued cookies do not support split backend deployments

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#24135]
### 📜 Description

We deploy our techdocs-backend on a separate backend and observed that static asset requests that require cookie auth fails due to the cookie failing to be set on the browser. Here's my diagnosis of the issue:

In the following code a cookie is being set against the request origin header host:
https://github.com/backstage/backstage/blob/96b23786f648ea28c2ab81d4888c46ab8bbd907b/packages/backend-app-api/src/services/implementations/httpAuth/httpAuthServiceFactory.ts#L232-L242

In our use-case our frontend is being served from `backstage.company.com` while our techdocs backend is served from `backstage-techdocs.company.com`. Line 235 above is prioritizing the request origin so the cookie is being set for `backstage.company.com`. The browser ends up rejecting this as misconfigured since the request is against `backstage-techdocs.company.com/cookie` but the cookie is being attempted to set against `backstage.company.com`. 

I believe the solution is to just reverse the order of precedence to prefer the external base URL as determined by the DiscoveryService:
```ts
const externalBaseUrl = new URL(externalBaseUrlStr ?? origin); 
``` 

This should guarantee the cookie will always be set against the target domain (instead of the source) but wanted to run this by the maintainers first since there have been a couple auth changes in flux recently. Happy to open a PR fix if this solution makes sense 🙂 

### 👍 Expected behavior

Issued cookies should target the correct backend domain 

### 👎 Actual Behavior with Screenshots

Issued cookies target the request origin and is rejected by the browser

### 👟 Reproduction steps

1) Deploy the techdocs-backend plugin on a separate backend with a different host address
2) Cookie auth for static assets fails when requesting techdocs

### 🖥️ Your Environment

Backstage v1.25.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Yep I think you are quite right. Happy to discuss further and validate in a PR
