### ISSUE TITLE
🚀 Feature: Use the users oauth token in Azure

### ISSUE THREAD

**Issue by toasahi** [backstage/backstage#24131]
### 🔖 Feature description

I want to pass Azure Ad login user information to backstage template.

### 🎤 Context

I want to execute a custom action using an Ad user.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey :wave: So I think I understand the issue here, might need some more context.

But if you have Azure sign-in configured in Backstage you can use the `RepoUrlPicker` to get a token for the user.

https://backstage.io/docs/features/software-templates/writing-templates/#using-the-users-oauth-token
