### ISSUE TITLE
💬 RFC: Filter improvement suggestions

### ISSUE THREAD

**Issue by ShiranHi** [backstage/backstage#24143]
### 🔖 Need

Currently, users lack visibility into the options beneath each dropdown in the filter bar, necessitating occasional guesswork and resulting in unnecessary clicks. Additionally, we were thinking about adding a counter of items per each filter. As the filter bar component is widely in use, the suggestions below could help improve the user experience and the ease of filtering.

### 🎉 Proposal

We think about providing users with the ability to access and review all available options within each filter. This feature will enable users to easily scan the list and select the relevant items. Additionally, for longer lists, we propose implementing a scroll bar if there are more than five items. I will be happy to hear your thoughts and learn about any solution you may already have. 

![Filters](https://github.com/backstage/backstage/assets/77277517/f4fc6004-b91b-47c1-802f-7a8359b74025)

### 〽️ Alternatives

I was happy to see the discussion on the #19930 ticket,I think we can expand the discussion on it 

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by ShiranHi** [comment]
> I love these ideas and designs. I do have some questions for what it means when there are hundreds of options to select from etc, but those are details that always can be worked out one way or the other.

Hi @freben ,thank you for getting back to me. It seems I may not have clarified this point well enough. If there are hundreds of options, it doesn't make sense to list them all out. Therefore, this proposal is applicable for scenarios where we have up to around 20 results.

>I'll mention that besides changing the default looks of the catalog, there's also the opportunity to make [advanced customizations of the catalog](https://backstage.io/docs/features/software-catalog/catalog-customization#advanced-customization) where you pick any set of filters that you want - including bespoke ones or competing designs. One way forward here would definitely be to make an alternative library of filters that users can freely choose among.

Thank you for the link to the Advanced Customization, I will definitely take a look on that.

>If you don't mind me asking, is there a bigger effort or big picture thing from Red Hat's side? Anything that helps me see if there's something we can do to make a more concerted effort in responding to your design input.

Thanks for reaching out and offering your help, really appreciate it! We're always on the lookout for the best solutions for our frequently used components. Since our developer portal is based on Backstage, we're working hard to align it as closely as possible with our [PatternFly library](https://www.patternfly.org/). This helps keep the Red Hat products feeling consistent while staying true to Material Design guidelines. As a designer, I've found it can be tricky to integrate other Material Design components not included in the Backstage supported library. Sometimes we need to lean on the community for support, like with the issues #22735 and #23424.

**Comment by Rugvip** [comment]
@ShiranHi What's missing for me is a design that considers a bit more data. For example, instead of the 4 components kind in the example, what if there are 20? Likewise, How would we handle 20 different components types in addition to the 20 component kinds?

**Comment by ShiranHi** [comment]
@Rugvip I think it would be valuable to establish some clear conventions for the filter component. The choice of which component should depend on the number of filters available and the complexity of the filtering options. I agree that the design should be flexible and scalable.

Here are some ideas:

**Checkboxes:**
- Use when there are up to 5 items
- If there are more than 5 items, display the most popular as checkboxes and hide the rest in a collapsed section
- Ideal for scenarios where multiple options can be selected simultaneously

**Radio Buttons:**
- Use when there are up to 5 items
- If there are more than 5 items, display the most popular as checkboxes and hide the rest in a collapsed section
- Suitable when only one option can be selected at a time within a group

**Dropdown Menu:**
- Use when there are up to 10 items
- If there are more than 10 items, implement a dropdown with a type-ahead function, and support multi-select if necessary, using chips

**Toggle/Switch:**
- Best for binary filters that need quick access (on/off)

These suggestions are meant to keep the interface clear, easy to use, and help users find the filters they need quickly. What do you think?

**Comment by Rugvip** [comment]
@ShiranHi There's an extra complication that I've realized, which is that the available type values depend on what kind you have selected. You can see that in effect on the [demo site](https://demo.backstage.io/catalog). This means that if we allow for selection of multiple kinds at once, we also get a more complicated matrix of types to select from. Honestly I think it's likely not worth the hassle and it's best to stick to a single selection for the kind. It could make sense to switch to a multi-select for the type though? For that we could probably just use the same filter component as for the tags/owner etc, those scale to many more items.

**Comment by ShiranHi** [comment]
@Rugvip thanks for bringing this up. If users pick more than one Kind, the list of Types will update to show everything that matches. For example, if users select both API and Component, they’ll see all the Types related to both. 

I believe there’s value in letting users choose multiple Kinds at the same time:
- Selecting several Kinds gives more flexibility. This is especially helpful when users want to see a wider range of results
- It means users don’t have to keep opening and closing the dropdown to change their selection
- Checkboxes are always visible on the screen, so users can easily see all the available options and what they’ve already selected

I’d be happy to hear any feedback or thoughts on this.

**Comment by Rugvip** [comment]
@ShiranHi I gave it a try with the existing filters and I don't love it 😅 

<img width="342" alt="image" src="https://github.com/user-attachments/assets/9e626274-fc42-4461-87ee-a883574ad6a9">

I'd say we need a strong indicator that the inability to select multiple kinds is hurting the user flow. I do find it unlikely that someone landing on the entity page that is looking for something in the catalog doesn't already know what kind of entity they're looking for. If they don't know that they should likely be using search instead to get more open results.

**Comment by ShiranHi** [comment]
@Rugvip thanks for your sharing this! I get what you're saying about users likely knowing what kind of entity they're looking for, and how selecting multiple kinds might not be as important in those cases. You also make a good point about using search for those scenarios.

It’d be good to check if letting users pick multiple kinds really helps or if it’s just adding complexity. I'll be happy to learn if users are struggling with the current setup. Let me bring this up with others to gather more feedback.

In the meantime, I’d be happy to hear thoughts about the count indicator and the Clear/All quick actions mentioned in this RFC.

**Comment by Rugvip** [comment]
@ShiranHi both count indicators and clear all exist in the existing multi-select component. This is what the clear all looks like:

<img width="311" alt="image" src="https://github.com/user-attachments/assets/4bf29705-4d0c-4ba5-bb09-2c5115bf0f88">

The count isn't enabled by default afaik, but you can see it in https://github.com/backstage/backstage/issues/24143#issuecomment-2340156894

**Comment by ShiranHi** [comment]
@Rugvip thank you for sharing, I wasn't aware of the count indicator. I'm curious, though, if we display checkboxes, can we include a clear/all actions option like the one on the main post? 
We could consider the first option, where users select only one Kind at a time, but instead of using a dropdown, we could display it as a list, showing up to 5 items with the rest hidden under a 'More' option, similar to how Gmail handles it. I believe this would be a better solution, as users wouldn't need to repeatedly open and close a dropdown to change their selection, and the options would always remain visible on the screen.

**Comment by Rugvip** [comment]
@ShiranHi the "X" in the component at https://github.com/backstage/backstage/issues/24143#issuecomment-2345970520 is the "clear all" action. I'm thinking at this point the best path forward might  be if you have any suggestions for more incremental improvements for our multi-select filter component?

Don't know if the 'More' option in Gmail is a great example unless I misunderstand which one you're referring too, that one seems to just expand the full list when you click it, which doesn't seem like what we'd want here due to the potentially large list?

**Comment by ShiranHi** [comment]
To clarify, my primary concern with the current component is around displaying checkboxes and a visible list of items, versus when to use the dropdown component for handling a large number of items, as I mentioned [earlier](https://github.com/backstage/backstage/issues/24143#issuecomment-2310235258). If there are no other requests from the community to change this component, we can revisit this topic when the need arises.

**Comment by freben** [comment]
We're open to having a nice visible checkbox list for few items, as long as it also has an automatic many-items mode (probably still the dropdown then).

This probably won't work specifically for the Kind filter right now - since it's built as a single-select, and other bits of code rely on it being that way. Changing that specific filter to a multi-select might be a separate task, no matter what the visual representation of the control is.

**Comment by SzymonGr** [comment]
First of all - great work so far ❤️ I like the designs so much 🥇

Here are my comments in the topic of the catalog filters:

1. it'd be nice to have an option of having filters on the top also
- we had a feeling that filters on the left are taking too much space
- here is what we did
  
![image](https://github.com/user-attachments/assets/4c1be3e9-4080-4e53-87ae-418c3fd294a1)
![image](https://github.com/user-attachments/assets/9d95dc50-14d1-47d5-9f23-cbd0ad1e2f46)

2. another annoying thing is that whenever you open one of these

![image](https://github.com/user-attachments/assets/8939c0b6-3aae-4f7d-816d-cd1665733d43)
- then the content moves down 

![image](https://github.com/user-attachments/assets/98463f50-a032-4b55-a85a-9c8b993ff926)

- the dropdown should be on top of the content, and not taking the space

**Comment by ConstantinJun** [comment]
Hi @Rugvip, quite an old post, but I had a similar problem with the UX of the current selectors, and I improved it this way: instead of showing all of them in the input, which broke the layout, I just show the main one and group all the others.

When you open the selector, you can see them in either the Selected group or the Available group.

But in general, one issue I encountered is that I think this filter should belong directly in the table column. It feels more intuitive to look for filtering options in the column itself rather than in the sidebar.

This would also allow the filter to be richer than the current one. For example, supporting include/exclude options and other filtering capabilities.

I’m currently working on improving the table. Once I finish, I could create an issue/thread with my suggestions.

<img width="265" height="99" alt="Image" src="https://github.com/user-attachments/assets/cf7bce80-8a64-44bb-b023-085ecf85b3ed" />

<img width="261" height="308" alt="Image" src="https://github.com/user-attachments/assets/8bc25396-1099-4190-abf2-b96fac7f48f0" />

<img width="261" height="190" alt="Image" src="https://github.com/user-attachments/assets/6738341a-bb7e-4e8c-8dba-645eb7f874a3" />
