### ISSUE TITLE
🚀 Feature: <Update Copyright Year in Footer>

### ISSUE THREAD

**Issue by AmbrishRamachandiran** [backstage/backstage#24146]
### 🔖 Feature description

Currently, the copyright year in the footer of the backstage website is hardcoded, requiring manual updates each year. To improve maintainability and ensure the copyright year automatically updates, we should implement a dynamic solution.

### 🎤 Context

Replace the hardcoded year in the footer with JavaScript's Date object to automatically retrieve the current year.
Utilize JavaScript’s Date object to automatically retrieve the current year.
Update the copyright text to display the dynamic year, ensuring it stays up to date without manual intervention.

### ✌️ Possible Implementation

Identify the section of code in the footer responsible for displaying the copyright year.
Replace the hardcoded year with JavaScript code to fetch and display the current year dynamically.
Test the changes locally to ensure they function as expected.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
https://nexb.com/do-you-really-need-to-update-the-copyright-each-new-year/#:~:text=No%2C%20but%20a%20copyright%20statement,in%20their%20project's%20copyright%20notices.

**Comment by freben** [comment]
I think we'll close this; we don't really need or want to update the year.
