### ISSUE TITLE
Add secret scanning in Security Insights plugin

### ISSUE THREAD

**Issue by codehubmanish** [backstage/backstage#24155]
### 🔖 Feature description

To enhance the Security Insights plugin, integrating secret scanning functionality would be invaluable. This addition would enable the detection of any inadvertent exposure of sensitive information within GitHub repositories, thereby bolstering security measures.

It's widely acknowledged that Rodie Security Insights Plugin already provides Dependabot alerts and code scanning results. In line with this, it would be beneficial to incorporate secret scanning results into the plugin as well.

### 🎤 Context

In scenarios where a developer inadvertently commits a secret to their GitHub repository, having this feature can provide valuable alerts.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by awanlin** [comment]
Hi @codehubmanish, given that this would be a feature added to the Roadie plugin you'll get more tracking on this request if you make it here: https://github.com/RoadieHQ/roadie-backstage-plugins/issues

**Comment by codehubmanish** [comment]
Thanks @awanlin for guiding, i have raised an issue there
https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1340

**Comment by freben** [comment]
Alright, closing this one for now then.
