### ISSUE TITLE
Add Kubernetes as a generic plugin at root level

### ISSUE THREAD

**Issue by HarikaManchukonda** [backstage/backstage#24187]
### 🔖 Feature description

Not sure if this feature is already available, can we add kubernetes as a generic plugin at rool level(to the left menu bar) instead of tightly coupling it with component?

### 🎤 Context

In my use case i want to see cluster info for all apps not just for one component.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
The plugin is designed that way at the moment; nobody has built a usable index page for it yet.

However, I'm not sure what that index page would show. Especially in a large org with tens of thousands of apps etc. It'll be both a technical and design related exercise to make a usable landing page for that.
