### ISSUE TITLE
🚀 Feature: overwrite theme spacing 

### ISSUE THREAD

**Issue by dirkjf** [backstage/backstage#24183]
### 🔖 Feature description

When using [createUnifiedTheme](https://backstage.io/docs/reference/theme.createunifiedtheme/) there is currently no way of setting custom spacing settings. The interface looks like this:

```
interface UnifiedThemeOptions {
    palette: PaletteOptions & PaletteOptions$1;
    defaultPageTheme?: string;
    pageTheme?: Record<string, PageTheme>;
    fontFamily?: string;
    htmlFontSize?: number;
    components?: ThemeOptions['components'];
    typography?: BackstageTypography;
} 
```

It would be nice to be able to add custom spacing settings as can be done in Mui: https://mui.com/material-ui/customization/spacing/#custom-spacing. 

### 🎤 Context

Custom theme settings. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Makes sense, if this something you would be open to adding via a Pull Request @dirkjf?

**Comment by dirkjf** [comment]
@awanlin, I need to find some time to do it, but I am willing to add this and open a PR for it.

**Comment by awanlin** [comment]
Sounds good, I've assigned this to you, feel free to work on it when you have time, no rush 👍

**Comment by camilaibs** [comment]
Hi @dirkjf , do you still able to help us with this issue 🙂 ?

**Comment by dirkjf** [comment]
@camilaibs, I will have a look before the end of the week.

**Comment by dirkjf** [comment]
@camilaibs, I created an MR: https://github.com/backstage/backstage/pull/25349#issuecomment-2182390540

**Comment by freben** [comment]
@dirkjf Just checking in if this is something you'd still like to work on.
