### ISSUE TITLE
🐛 Bug Report: @backstage/testing-utils fails using @testing-library/react-14.3.1

### ISSUE THREAD

**Issue by Fuglen** [backstage/backstage#24214]
### 📜 Description

It bugs out when running our Jenkins pipeline for building Backstage

### 👍 Expected behavior

It should build Backstage without issues/errors when there are no major changes in our code

### 👎 Actual Behavior with Screenshots

We narrowed it down to a "@testing-library/react@^14.0.0" bumped it's version from `14.2.2` to `14.3.1` as shown on the following screenshot 
![image](https://github.com/backstage/backstage/assets/6181362/cb109098-174a-4398-9d78-15a3eeb3e832)

Using that version, it crashes or pipeline and says @testing-library is used by @backstage/testing-utils
![image](https://github.com/backstage/backstage/assets/6181362/6cb1aa0b-5538-4b2a-bd22-4db2d9697fee)

### 👟 Reproduction steps

We are running Backstage 1.25.1 with the following package.json in packages/app
```json
{
  "name": "app",
  "version": "0.0.0",
  "private": true,
  "bundled": true,
  "backstage": {
    "role": "frontend"
  },
  "scripts": {
    "start": "backstage-cli package start",
    "build": "backstage-cli package build",
    "clean": "backstage-cli package clean",
    "test": "backstage-cli package test",
    "lint": "backstage-cli package lint"
  },
  "dependencies": {
    "@backstage/app-defaults": "^1.5.3",
    "@backstage/catalog-model": "^1.4.5",
    "@backstage/cli": "^0.26.2",
    "@backstage/core-app-api": "^1.12.3",
    "@backstage/core-components": "^0.14.3",
    "@backstage/core-plugin-api": "^1.9.1",
    "@backstage/integration-react": "^1.1.25",
    "@backstage/plugin-api-docs": "^0.11.3",
    "@backstage/plugin-catalog": "^1.18.2",
    "@backstage/plugin-catalog-common": "^1.0.22",
    "@backstage/plugin-catalog-graph": "^0.4.3",
    "@backstage/plugin-catalog-import": "^0.10.9",
    "@backstage/plugin-catalog-react": "^1.11.2",
    "@backstage/plugin-devtools": "^0.1.12",
    "@backstage/plugin-github-actions": "^0.6.14",
    "@backstage/plugin-home": "^0.7.2",
    "@backstage/plugin-org": "^0.6.23",
    "@backstage/plugin-permission-react": "^0.4.21",
    "@backstage/plugin-scaffolder": "^1.19.2",
    "@backstage/plugin-search": "^1.4.9",
    "@backstage/plugin-search-react": "^1.7.9",
    "@backstage/plugin-tech-radar": "^0.7.2",
    "@backstage/plugin-techdocs": "^1.10.3",
    "@backstage/plugin-techdocs-module-addons-contrib": "^1.1.8",
    "@backstage/plugin-techdocs-react": "^1.2.2",
    "@backstage/plugin-user-settings": "^0.8.4",
    "@backstage/theme": "^0.5.2",
    "@material-ui/core": "^4.12.2",
    "@material-ui/icons": "^4.9.1",
    "backstage-plugin-xkcd": "^1.0.9",
    "history": "^5.0.0",
    "react": "^18.0.2",
    "react-dom": "^18.0.2",
    "react-router": "^6.3.0",
    "react-router-dom": "^6.3.0",
    "react-use": "^17.2.4"
  },
  "devDependencies": {
    "@backstage/test-utils": "^1.5.3",
    "@playwright/test": "^1.32.3",
    "@testing-library/jest-dom": "^6.0.0",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^14.0.0",
    "@testing-library/dom": "^9.0.0",
    "@types/react-dom": "*",
    "cross-env": "^7.0.0"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "files": [
    "dist"
  ]
}
```

Changing `"@testing-library/react": "^14.0.0",` to `"@testing-library/react": "14.2.2",` fixes the issue, but the recommended version is `"@testing-library/react": "^14.0.0",` which bumps it up to "@testing-library/react": "^14.3.1",

### 📃 Provide the context for the Bug.

This caused our pipeline to fail but we have already found a solution, just not a long-term one yet

### 🖥️ Your Environment

OS:   Linux 6.4.16-linuxkit - linux/x64
node: v20.11.1
yarn: 1.22.21
cli:  0.26.2 (installed)
backstage:  1.25.1

Dependencies:
  @backstage/app-defaults                                            1.5.3
  @backstage/backend-app-api                                         0.6.2
  @backstage/backend-common                                          0.21.6
  @backstage/backend-defaults                                        0.2.16
  @backstage/backend-dev-utils                                       0.1.4
  @backstage/backend-openapi-utils                                   0.1.9
  @backstage/backend-plugin-api                                      0.6.16
  @backstage/backend-tasks                                           0.5.21
  @backstage/catalog-client                                          1.6.3
  @backstage/catalog-model                                           1.4.5
  @backstage/cli-common                                              0.1.13
  @backstage/cli-node                                                0.2.4
  @backstage/cli                                                     0.26.2
  @backstage/config-loader                                           1.7.0
  @backstage/config                                                  1.2.0
  @backstage/core-app-api                                            1.12.3
  @backstage/core-compat-api                                         0.2.3
  @backstage/core-components                                         0.12.5, 0.14.3
  @backstage/core-plugin-api                                         1.9.1
  @backstage/e2e-test-utils                                          0.1.1
  @backstage/errors                                                  1.2.4
  @backstage/eslint-plugin                                           0.1.6
  @backstage/frontend-plugin-api                                     0.6.3
  @backstage/integration-aws-node                                    0.1.12
  @backstage/integration-react                                       1.1.25
  @backstage/integration                                             1.9.1
  @backstage/plugin-api-docs                                         0.11.3
  @backstage/plugin-app-backend                                      0.3.64
  @backstage/plugin-app-node                                         0.1.16
  @backstage/plugin-auth-backend-module-atlassian-provider           0.1.8
  @backstage/plugin-auth-backend-module-aws-alb-provider             0.1.8
  @backstage/plugin-auth-backend-module-gcp-iap-provider             0.2.11
  @backstage/plugin-auth-backend-module-github-provider              0.1.13
  @backstage/plugin-auth-backend-module-gitlab-provider              0.1.13
  @backstage/plugin-auth-backend-module-google-provider              0.1.13
  @backstage/plugin-auth-backend-module-microsoft-provider           0.1.11
  @backstage/plugin-auth-backend-module-oauth2-provider              0.1.13
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider        0.1.9
  @backstage/plugin-auth-backend-module-oidc-provider                0.1.7
  @backstage/plugin-auth-backend-module-okta-provider                0.0.9
  @backstage/plugin-auth-backend                                     0.22.3
  @backstage/plugin-auth-node                                        0.4.11
  @backstage/plugin-auth-react                                       0.0.3
  @backstage/plugin-catalog-backend-module-bitbucket-server          0.1.30
  @backstage/plugin-catalog-backend-module-github                    0.5.7
  @backstage/plugin-catalog-backend-module-msgraph                   0.5.24
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model   0.1.14
  @backstage/plugin-catalog-backend                                  1.21.0
  @backstage/plugin-catalog-common                                   1.0.22
  @backstage/plugin-catalog-graph                                    0.4.3
  @backstage/plugin-catalog-import                                   0.10.9
  @backstage/plugin-catalog-node                                     1.11.0
  @backstage/plugin-catalog-react                                    1.11.2
  @backstage/plugin-catalog                                          1.18.2
  @backstage/plugin-devtools-backend                                 0.3.2
  @backstage/plugin-devtools-common                                  0.1.9
  @backstage/plugin-devtools                                         0.1.12
  @backstage/plugin-events-node                                      0.3.2
  @backstage/plugin-github-actions                                   0.6.14
  @backstage/plugin-home-react                                       0.1.11
  @backstage/plugin-home                                             0.7.2
  @backstage/plugin-org                                              0.6.23
  @backstage/plugin-permission-common                                0.7.13
  @backstage/plugin-permission-node                                  0.7.27
  @backstage/plugin-permission-react                                 0.4.21
  @backstage/plugin-proxy-backend                                    0.4.14
  @backstage/plugin-scaffolder-backend-module-azure                  0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud        0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-server       0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket              0.2.6
  @backstage/plugin-scaffolder-backend-module-confluence-to-markdown 0.2.17
  @backstage/plugin-scaffolder-backend-module-gerrit                 0.1.8
  @backstage/plugin-scaffolder-backend-module-gitea                  0.1.6
  @backstage/plugin-scaffolder-backend-module-github                 0.2.6
  @backstage/plugin-scaffolder-backend-module-gitlab                 0.3.2
  @backstage/plugin-scaffolder-backend                               1.22.3
  @backstage/plugin-scaffolder-common                                1.5.1
  @backstage/plugin-scaffolder-node                                  0.4.2
  @backstage/plugin-scaffolder-react                                 1.8.3
  @backstage/plugin-scaffolder                                       1.19.2
  @backstage/plugin-search-backend-module-catalog                    0.1.21
  @backstage/plugin-search-backend-module-pg                         0.5.25
  @backstage/plugin-search-backend-module-techdocs                   0.1.21
  @backstage/plugin-search-backend-node                              1.2.20
  @backstage/plugin-search-backend                                   1.5.6
  @backstage/plugin-search-common                                    1.2.11
  @backstage/plugin-search-react                                     1.7.9
  @backstage/plugin-search                                           1.4.9
  @backstage/plugin-tech-radar                                       0.7.2
  @backstage/plugin-techdocs-backend                                 1.10.3
  @backstage/plugin-techdocs-module-addons-contrib                   1.1.8
  @backstage/plugin-techdocs-node                                    1.12.2
  @backstage/plugin-techdocs-react                                   1.2.2
  @backstage/plugin-techdocs                                         1.10.3
  @backstage/plugin-user-settings                                    0.8.4
  @backstage/release-manifests                                       0.0.11
  @backstage/test-utils                                              1.5.3
  @backstage/theme                                                   0.2.19, 0.5.2
  @backstage/types                                                   1.1.1
  @backstage/version-bridge                                          1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Hmm, this could be a Yarn bug/flakiness, I'm not seeing anything immediate that would cause this. I'd double check the layout of `node_modules` and see whether `@testing-library/react` is there or not. Doesn't look like this would be an issue related to Backstage itself.
