### ISSUE TITLE
🚀 Feature: Allow to add additional titles for same entities to enhance searches

### ISSUE THREAD

**Issue by mikevader** [backstage/backstage#24215]
### 🔖 Feature description

You should add a form of aliases to entities like systems and components because especially systems shift over their life cycle and might be known under different names.

A user of backstage should be able to find the right system regardless of what name under the different known name it was used to search for it.

### 🎤 Context

In our company we have usually the setup with project name and system name. A system is usually known under both and depending on the usergroup one of them is more prevalent. Because we want to use backstage as single point of entry for development resources, to be able to lookup and find systems etc is a key capability.

### ✌️ Possible Implementation

On a manifest level, one option would be to have a list of aliases in the metadata of all entities. In my point of view those aliases should not be an alternative for the name but for the title.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
This probably fits best as a custom extension to the model.

You could add an annotation, for example

```yaml
metadata:
  annotations:
    also-known-as: Older name, Even Older Name
```

and then make a collator for the search plugin that indexes that.

**Comment by mikevader** [comment]
@freben I tried it like this, took a while until I understood how to extend an existing collator, and it worked like a charm.

But I still have one missing piece: In my opinion the aliases are part of the main system model metadata and should be part of the standard overview/about component.
How can I customize the entity about card?

**Comment by vinzscam** [comment]
I think you should either fork the card, or create another card with the information you want, or propose a change to inject generic JSX content in a specific place of `AboutCard` that should make sense for other use cases as well

**Comment by mikevader** [comment]
Just searched through the discussion about the entity cards. Concluding from those I assume https://github.com/backstage/backstage/issues/16876 would implemented right implement this correctly? So either wait, contribute or customize completely.

Additionally I wanted to style the search result differently or more precisely just the aliases. Is this possible? (I'm a complete react newbie so I just tried to add html tag in the text which obviously didn't work.)
