### ISSUE TITLE
User settings backend returns 404

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#24278]
### 📜 Description

When using user settings backend as storage and item is not saved there, the API returns 404 causing unnecessary alerts in monitoring systems 

### 👍 Expected behavior

It should instead return 200 and no value

### 👎 Actual Behavior with Screenshots

404 returned

### 👟 Reproduction steps

1. Enable user settings backend
2. Try to fetch some value from it using `storageApi`
3. See network tab

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Hmm, I'd say don't alert on 404s in API responses, they're very much expected 😅

It's common to return 404 in case of a missing resource when path parameters are in use, which is the case here
