### ISSUE TITLE
🚀 Feature: Devtools Backend Tasks Status

### ISSUE THREAD

**Issue by billabongrob** [backstage/backstage#24286]
### 🔖 Feature description

In the devtools plugin, it would be nice to see the backend tasks (ref table: backstage_backend_tasks__tasks) that are upcoming, the status of previously run tasks, and potentially, the ability to change the date and time when the task will run again.  

### 🎤 Context

In our use case, it's helpful to not have to go to the database directly to view when these tasks are scheduled to run.  Additionally, updating them directly in the DB to force the task to run is error prone and offers a lot of room for trouble.  

### ✌️ Possible Implementation

Another tab on the DevTools page showing scheduled jobs.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by drodil** [comment]
We have our own service that collects all the schedulers from all plugins so we can show these on the devtools page and also trigger the tasks manually. Not very beautiful way of doing this but best for now :D

**Comment by alper98** [comment]
> We have our own service that collects all the schedulers from all plugins so we can show these on the devtools page and also trigger the tasks manually. Not very beautiful way of doing this but best for now :D

Would you mind sharing more details on this service? We would like a similiar feature, with the possibility of triggering the tasks as well

**Comment by alper98** [comment]
> There's been some discussion about making it possible to enumerate the installed plugins reliably but it's not been prioritised yet. When that's in place, we could add the rest of the pieces.

Are there any updates to this with the new backend system?

**Comment by freben** [comment]
No, the backend system in and of itself didn't implement that feature. It'll be nicer to build the feature upon that system, but no, it's not in place.
