### ISSUE TITLE
🐛 Bug Report: Search page result type filter accessibility issues

### ISSUE THREAD

**Issue by riginoommen** [backstage/backstage#24297]
### 📜 Description

When you are viewing the full search results page, and you select the "kind" filter, it collapses immediately. It should only collapse when the "collapse" heading is clicked

### 👍 Expected behavior

stay in the current state without collapsing

### 👎 Actual Behavior with Screenshots

N/A

### 👟 Reproduction steps

Navigate to search and try changing filters

https://github.com/backstage/backstage/assets/3840244/759994aa-5e59-45c0-8f81-20b1489b7917

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Could you provide a bit of information about how this hurts accessibility?
