### ISSUE TITLE
🚀 Feature: Kubernetes plugin add restart pod button

### ISSUE THREAD

**Issue by LegendSebastianoL** [backstage/backstage#24293]
### 🔖 Feature description

Would be good to be able to restart the pods via the Kubernetes plugin out of the box, maybe can be controlled via a configuration so that if someone doesn't want to enable it is not visible.

The button should appear on the container card at the bottom of each pod, alongside the logs button, like in the screenshot.
![restart](https://github.com/backstage/backstage/assets/61748264/6b92249c-c3ca-4cef-8450-789550ba694b)

### 🎤 Context

related with https://github.com/backstage/backstage/issues/24290 this is another feature we are maintaining alongside the backstage plugin and making it impossible for us to use the default backstage plugin version.

### ✌️ Possible Implementation

the `KubernetesProxyClient` class should implement the `restartPod` function like this:
```
  async restartPod({
    podName,
    namespace,
    clusterName,
    containerName,
    previous,
  }: {
    podName: string;
    namespace: string;
    clusterName: string;
    containerName: string;
    previous?: boolean;
  }): Promise<{ text: string }> {
    const params = new URLSearchParams({
      container: containerName,
    });
    if (previous) {
      params.append('previous', '');
    }
    return await this.kubernetesApi
      .proxy({
        clusterName: clusterName,
        path: `/api/v1/namespaces/${namespace}/pods/${podName}`,
        init: {
          method: 'DELETE',
        },
      })
      .then(response => this.handleText(response))
      .then(text => ({ text }));
  }
```

while the `KubernetesProxyApi` interface should have this code:
```
  restartPod(request: {
    podName: string;
    namespace: string;
    clusterName: string;
    containerName: string;
    previous?: boolean;
  }): Promise<{ text: string }>;
```

finally, a new component needs to be built to handle the new logic, I'm happy to provide the rest of the code if you want.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by mclarke47** [comment]
This sgtm!

**Comment by LegendSebastianoL** [comment]
hey, @Rugvip @mclarke47 if you want I can put the whole plugin in my personal GH account and link it here :) so you can see how we implemented it, it will include also the changes for https://github.com/backstage/backstage/issues/24290

**Comment by mclarke47** [comment]
To clarify I think the goal should be a "Delete pod" button rather than something to restart the container, since that would upset the pod lifecycle

**Comment by LegendSebastianoL** [comment]
sure, I think our code is deleting the pod by looking at this piece of code, I think they called it restart to don't scare users.

```
    return await this.kubernetesApi
      .proxy({
        clusterName: clusterName,
        path: `/api/v1/namespaces/${namespace}/pods/${podName}`,
        init: {
          method: 'DELETE',
        },
      })
```

**Comment by sebalaini** [comment]
attached is the full code from my [personal accout](https://github.com/sebalaini/backstage-kubernetes-react)

it contains:
- restart (delete) button
- namespace to all resources
- migrated to mui 5
- `KubernetesContent.tsx` also is coming from here, I saw it has been moved to the Kubernetes plugin (we have that in our repo and we maintain it ourselves but I hope to be able to use soon the Backstage one)

**Comment by Rugvip** [comment]
@sebalaini you'd need to open up a pull request towards this repo with the suggested additions. We can't bring in the code from an external repo since we require [signing DCO](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) as part of the contribution process.

**Comment by LegendSebastianoL** [comment]
hey @Rugvip It will have to wait till June because this week I can't and from next week I'm off for a month :)

**Comment by sebalaini** [comment]
hey 👋 @Rugvip @mclarke47 I finally found some time before leaving for A/L to open a PR for it 😊 I hope all is good with it.

**Comment by LegendSebastianoL** [comment]
hey @Rugvip @mclarke47 I'm waiting for approval on the PR, can you take a look, please?

**Comment by sebalaini** [comment]
unstale

**Comment by LegendSebastianoL** [comment]
unstale
