### ISSUE TITLE
🚀 Feature: Kubernetes plugin add namespace to resources

### ISSUE THREAD

**Issue by LegendSebastianoL** [backstage/backstage#24290]
### 🔖 Feature description

We are currently maintaining our own version of the plugin but would be good if we could use the Backstage one, without having to sync from time to time.

Would be good if all the K8 resources had a namespace in the drawer component like in the below screenshot.
![namespace](https://github.com/backstage/backstage/assets/61748264/558fe13c-2b7d-443e-b109-5c103c23003a)

All resources should have it and be accessible via `RESOURCE.metadata?.namespace` 

We applied this change to the following resources:

- cronjob
- daemonset
- deployment
- ingress
- service
- statefulset

### 🎤 Context

The reason behind this is that in our setup we have a lot of products that are hosted in 2 different namespaces, staging/production, and to slim down the catalog we onboard the product without making differences between the lifecycle but that makes it a bit harder to understand what resource belong to which namespace.

The implementation is straightforward, to the above services component (the drawer one) you just need to add this bit of code
```
const namespace = RESOURCE.metadata?.namespace;
...
{namespace && (
    <Grid>
        <Chip size="small" label={`namespace: ${namespace}`} />
    </Grid>
)}
```

### ✌️ Possible Implementation

all k8 resources should display in which namespace are located in the drawer component.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sebalaini** [comment]
closing this as it got merged today

**Comment by camilaibs** [comment]
> @mclarke47 we can close this as you merged the PR :)
Closing, thank you again 🎉
