### ISSUE TITLE
🚀 Feature: Allow EntityFilter `filterEntity` function to be async

### ISSUE THREAD

**Issue by secustor** [backstage/backstage#24304]
### 🔖 Feature description

Currently all functions of `EntityFilter` are synchronous which is enough if only data of the entity itself is used to decide on filtering on not. 

If other data of the catalog is needed this is not enough as using the catalog are asynchronous. 
We would need Promise support specifically for [`filterEntity`](https://github.com/backstage/backstage/blob/ae33ddccf7c2e5f2c0c95c42497412ef86936f8e/plugins/catalog-react/src/types.ts#L37)

### 🎤 Context

In my use case, I want to create a new EntityFilter to filter for all Entities which have a dangling relation. To be specific if the owner field is not pointing to a non existing Entity.

On the EntityPage this is already showed via `hasRelationWarnings` and `<EntityRelationWarning />`, tough it would be helpful if we could simply filter for them.  

### ✌️ Possible Implementation

Change function signature to `filterEntity?: (entity: Entity) => boolean | Promise<boolean> ;`, same then for [`reduceEntityFilters`](https://github.com/backstage/backstage/blob/ae33ddccf7c2e5f2c0c95c42497412ef86936f8e/plugins/catalog-react/src/utils/filters.ts#L88) and [`useEntityListProvider.tsx`](https://github.com/backstage/backstage/blob/ae33ddccf7c2e5f2c0c95c42497412ef86936f8e/plugins/catalog-react/src/hooks/useEntityListProvider.tsx)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Afaik we're moving away from that method more or less completely, @vinzscam knows more.

Even without considering #12247 I don't think it'd be a great idea from a performance PoV to allow this, feels like it would mostly be a foot-gun.

**Comment by secustor** [comment]
Users can definitely hurt themself with that, tough moving this to async would allow to parallelize the processing of all entities after the initially requesting the list using `getCatalogFilters`

**Comment by vinzscam** [comment]
I think one way for solving this would be to invoke the following once in the frontend:

```ts
catalogApi
      .getEntityFacets({ facets: ['relations.ownedBy'], })
```

this will give you back only the user entities that actually exist. You could then check whether each owner is present in the sets returned by the code above.

We actually already have the data in the frontend as the `EntityOwnerPicker` is fetching the same data via [useFacetsEntities](https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/components/EntityOwnerPicker/useFacetsEntities.ts#L43).
