### ISSUE TITLE
🐛 Bug Report: Search doesn't work in new backend system

### ISSUE THREAD

**Issue by LegendSebastianoL** [backstage/backstage#24308]
### 📜 Description

I'm upgrading to the new backend system and I can't use the search anymore, I can see how the collator has been added to the app
```
2024-04-16T13:07:10.032Z auth info Configuring "database" as KeyStore provider
2024-04-16T13:07:10.055Z techdocs info Creating AWS S3 Bucket publisher for TechDocs
2024-04-16T13:07:10.066Z search info Added ToolDocumentCollatorFactory collator factory for type tools
2024-04-16T13:07:10.066Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog
2024-04-16T13:07:10.066Z search info Added DefaultTechDocsCollatorFactory collator factory for type techdocs
2024-04-16T13:07:10.066Z search info Starting all scheduled search tasks.
```

I'm also following the instruction here https://github.com/backstage/backstage/tree/master/plugins/search-backend-module-catalog which aren't fully correct, the `import { searchPlugin } from '@backstage/plugin-search-backend/alpha';` get linted straight away and you need to use `import searchPlugin from ..` instead.

When I try to search I get this error
```
Missing index for software-catalog. This could be because the index hasn't been created yet or there was a problem during index creation.
```
it also mentions something about this `LunrSearchEngine.query` in the full error.

This is my old search:
```
import { createRouter } from '@backstage/plugin-search-backend';
import {
  IndexBuilder,
  LunrSearchEngine,
} from '@backstage/plugin-search-backend-node';
import { PluginEnvironment } from '../types';
import { DefaultCatalogCollatorFactory } from '@backstage/plugin-search-backend-module-catalog';
import { DefaultTechDocsCollatorFactory } from '@backstage/plugin-search-backend-module-techdocs';
import { Router } from 'express';
import { PgSearchEngine } from '@backstage/plugin-search-backend-module-pg';
import { ToolDocumentCollatorFactory } from '@backstage/plugin-search-backend-module-explore';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const searchEngine = (await PgSearchEngine.supported(env.database))
    ? await PgSearchEngine.fromConfig(env.config, { database: env.database })
    : new LunrSearchEngine({ logger: env.logger });
  const indexBuilder = new IndexBuilder({
    logger: env.logger,
    searchEngine,
  });

  const schedule = env.scheduler.createScheduledTaskRunner({
    frequency: { minutes: 15 },
    timeout: { minutes: 15 },
    initialDelay: { seconds: 3 },
  });

  indexBuilder.addCollator({
    schedule,
    factory: DefaultCatalogCollatorFactory.fromConfig(env.config, {
      discovery: env.discovery,
      tokenManager: env.tokenManager,
    }),
  });

  // collator gathers entities from techdocs.
  indexBuilder.addCollator({
    schedule,
    factory: DefaultTechDocsCollatorFactory.fromConfig(env.config, {
      discovery: env.discovery,
      logger: env.logger,
      tokenManager: env.tokenManager,
    }),
  });

  // collator gathers entities from explore.
  indexBuilder.addCollator({
    schedule,
    factory: ToolDocumentCollatorFactory.fromConfig(env.config, {
      discovery: env.discovery,
      logger: env.logger,
    }),
  });

  // The scheduler controls when documents are gathered from collators and sent to the search engine for indexing.
  const { scheduler } = await indexBuilder.build();
  scheduler.start();

  return await createRouter({
    engine: indexBuilder.getSearchEngine(),
    types: indexBuilder.getDocumentTypes(),
    permissions: env.permissions,
    config: env.config,
    logger: env.logger,
  });
}
```

and this is the new one:
```
import searchPlugin from '@backstage/plugin-search-backend/alpha';
import searchModuleCatalogCollator from '@backstage/plugin-search-backend-module-catalog/alpha';
import searchModuleTechDocsCollator from '@backstage/plugin-search-backend-module-techdocs/alpha';
import searchModuleExploreCollator from '@backstage/plugin-search-backend-module-explore/alpha';

// search plugin
backend.add(searchPlugin());
backend.add(searchModuleCatalogCollator());
backend.add(searchModuleTechDocsCollator());
backend.add(searchModuleExploreCollator());
```

### 👍 Expected behavior

The search in the new backend system should work as expected.

### 👎 Actual Behavior with Screenshots

the search plugin in the new backend system is failing due to missing index.

### 👟 Reproduction steps

once you are on the new backend system, use this code:
```
import searchPlugin from '@backstage/plugin-search-backend/alpha';
import searchModuleCatalogCollator from '@backstage/plugin-search-backend-module-catalog/alpha';
import searchModuleTechDocsCollator from '@backstage/plugin-search-backend-module-techdocs/alpha';
import searchModuleExploreCollator from '@backstage/plugin-search-backend-module-explore/alpha';

// search plugin
backend.add(searchPlugin());
backend.add(searchModuleCatalogCollator());
backend.add(searchModuleTechDocsCollator());
backend.add(searchModuleExploreCollator());
```

and the search will fail.

these are all the packages I can see related to the search in my package.json
```
    "@backstage/plugin-search-backend": "^1.5.6",
    "@backstage/plugin-search-backend-module-catalog": "^0.1.21",
    "@backstage/plugin-search-backend-module-explore": "^0.1.20",
    "@backstage/plugin-search-backend-module-pg": "^0.5.25",
    "@backstage/plugin-search-backend-module-techdocs": "^0.1.21",
    "@backstage/plugin-search-backend-node": "^1.2.20",
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by LegendSebastianoL** [comment]
I have to take back what I wrote 🤔 while writing this and having local still running now the search works as expected, is not clear why is now working, could it be because the new backend needed time to run the collator index?
nothing changed while I was writing this issue, it was running in the background.

**Comment by camilaibs** [comment]
Hi @LegendSebastianoL ,
Thank you for opening this issue 🙌🏻 
I managed to reproduce the error locally, and in my case the root cause was that the `Catalog` and `Explorer` collators were throwing an error when trying to generate a token to request the data to be indexed:

```
 Error: Unable to generate legacy token for communication with the 'software-catalog' plugin. You will typically encounter this error when attempting to call a plugin that does not exist, or is deployed with an old version of Backstage; caused by 
```

I created a pull request to migrate these modules to use the new authentication services (thanks @freben for the debugging help) and the `Catalog` error stopped happening to me.

**Comment by camilaibs** [comment]
Hey @LegendSebastianoL, has the fixes resolved the issue?
Please let me know if we can close this case 🙂

**Comment by LegendSebastianoL** [comment]
hey @camilaibs sorry for the delays but my teammate's doing the upgrade to 1.26, for us the search works but sometimes it doesn't finish the collator job at startup but on the next schedule so we have to wait till then for the search to work.

If we have problems on 1.26 I'll open a new issue :)

**Comment by freben** [comment]
@LegendSebastianoL Of course this should work well in all cases. But I'll mention though, that things are often built primarily with scaled production deployments in mind. In that scenario, during a rolling deploy, your search would both have its state retained since before (since the recommended pg and elasticsearch storages are persistent), AND there will anyway be other hosts to reach out to in the cluster that aren't mid-restart. Still, yeah, even for the single host / local dev use case it would make sense for this to work smoothly as well.

**Comment by LegendSebastianoL** [comment]
TY for the explanation :) I guess I didn't see it locally because I just run an instance, but in staging/prod even with 1 pod, the new one needs to be up and running before the old one gets deleted, wonder if this was a problem before...this is something I never checked TBH, I noticed it now because with the upgrade and moving to the new system I was checking everything was working on startup and found potential "bugs" which were already there but never seen them before 😓
