### ISSUE TITLE
🐛 Bug Report: SubmenuSubtitle is always white

### ISSUE THREAD

**Issue by tylerhcarter** [backstage/backstage#24315]
### 📜 Description

SubmenuSubtitle is always white, and references the palette value for "white". See [here](https://github.com/backstage/backstage/blob/master/packages/core-components/src/layout/Sidebar/SidebarSubmenu.tsx#L83). This creates an issue when the given theme has a white/light background.

### 👍 Expected behavior

This should be configurable with a specific style value. `navigation.submenu.title` for instance.

### 👎 Actual Behavior with Screenshots

The title is not readable on a light background:
![Screenshot 2024-04-16 at 3 31 04 PM](https://github.com/backstage/backstage/assets/159279/dcf8886c-444e-492f-a2eb-da8440aa11cd)

### 👟 Reproduction steps

1. Set the color for navigation to a light color `#FFF`
2. Define a submenu, per [documentation](https://backstage.io/docs/getting-started/app-custom-theme#sidebar-sub-menu)
3. Hover over submenu item.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
Thank you for reporting, that doesn't look right!

We'll leave this one open to community contributions. If anyone wants to work on this, please chime in, any help is appreciated! 🙏

**Comment by mritosa** [comment]
Hi, I would like to fix this issue.

**Comment by ShivamJha2436** [comment]
Is this issue has been resolved or not ?

**Comment by vinzscam** [comment]
> Hi, I would like to fix this issue.

contributions are welcome, feel free to open a PR @mritosa 🙏

**Comment by huggingpixels** [comment]
I saw this stale and was looking for a good first issue but I think there's another PR that fixes this already: [#24366](https://github.com/backstage/backstage/pull/24366)
