### ISSUE TITLE
🚀 Feature: TailwindCSS Integration in "Next" Frontend

### ISSUE THREAD

**Issue by CiscoRob** [backstage/backstage#24360]
### 🔖 Feature description

In customizing Backstage there are a lot of situations where the interfaces are entirely presentation with little interaction required.

Example being the use of InfoCard or other card based components could have been stylized div elements with TailwindCSS without the need for the Material UI library overhead.

Has there been any consideration for replacing the built-in Backstage theme and some of the basic components with TailwindCSS styled markup?

### 🎤 Context

Looking at the bundle size when importing dozens of plugins and the pain points in migrating from React 17 to 18 along with the Backstage dependencies on Material UI v4 it seems like this could be a good pivot point in migrating to the "Next" frontend to support a popular UI styling library like TailwindCSS.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
MUI solves a lot of these issues and more, both providing good layout abstractions and more complex components. That's all with excellent support for customization, theming, and a very good baseline for accessibility.

We're still settled on MUI as the default component library for Backstage and the recommended library for all plugins in the OSS ecosystem. We have however made sure that it's not tied into the core framework and is only introduced at the plugin layer. For anyone adopting Backstage building internal plugins, they can choose to use any other library for their own custom plugins, which if taken far enough can make up the entire app.
