### ISSUE TITLE
🚀 Feature: Enable to create a gitea public or private repository

### ISSUE THREAD

**Issue by cmoulliard** [backstage/backstage#24377]
### 🔖 Feature description

Enable to create a gitea repository `public` or `private` as currently every repository created using the template is `public`
Plugin: @backstage/plugin-scaffolder-backend-module-gitea

### 🎤 Context

This feature is needed for teams who don't want to expose publicly their gitea repositories

### ✌️ Possible Implementation

Todo:
- Add new parameter `repoVisibility` to the template action
- Check if the parameter is passed or not and convert it to `private: true|false` within the body of the POST request
- Add new test case
- Update the README file

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
> This ticket can be closed too as code is merged and will be released part of backstage 1.27

Thank you so much for letting us know, closing the issue 🙌🏻
