### ISSUE TITLE
🐛 Bug Report:  Microsoft auth provider: failed to fetch user profile

### ISSUE THREAD

**Issue by twanbeeren** [backstage/backstage#24387]
### 📜 Description

When I try to login using the microsoft provider I get the following error:  "failed to fetch user profile". It's the same issue as here: #23722 

The issue here was closed since that happened on an old/outdated backstage version, but I transitioned to 1.25 with the new frontend and backend system and I still get the same result. That's why it seemed valid to me to create a new issue for it.

### 👍 Expected behavior

It should open up the pop-up when try to login and give me an option to login with a microsoft account.

### 👎 Actual Behavior with Screenshots

It actually opens a pop-up and closes it immediately with error: "Authentication failed, failed to fetch user profile"

![image](https://github.com/backstage/backstage/assets/36261352/f54a01b2-e58b-49ee-9049-4b0a97e8bea6)

The GET http request returns as a 401: 
{{my_appConfig_baseUrl}}/api/auth/microsoft/refresh?optional=&scope=openid offline_access profile email User.Read&env=development

![image](https://github.com/backstage/backstage/assets/36261352/b72cec08-d3b0-4308-b586-e6449d4fb4f4)

The error seems a bit deceiving since I haven't filled in any credentials yet and still throws a 401 unauthorized.

### 👟 Reproduction steps

Make use of the new frontend and backend system

My app.config (same as [here](https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin))
```
auth:
  environment: development
  providers:
    # guest: {}
    microsoft:
      development:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityAnnotation
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailLocalPartMatchingUserEntityName
```

My backend/src/index.ts. Only show the auth plugins since I believe only these are relevant

```
const backend = createBackend();

// auth plugin
backend.add(import('@backstage/plugin-auth-backend'));
backend.add(import('@backstage/plugin-auth-backend-module-microsoft-provider'));
// See https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin
backend.add(import('@backstage/plugin-auth-backend-module-guest-provider'));
// See https://github.com/backstage/backstage/blob/master/docs/auth/guest/provider.md

backend.start();
```

The frontend hasn't changed since the change to the new system (didn't find that change on frontend side is necessary)
```
const app = createApp({
  apis,
  bindRoutes({ bind }) {
    bind(catalogPlugin.externalRoutes, {
      createComponent: scaffolderPlugin.routes.root,
      viewTechDoc: techdocsPlugin.routes.docRoot,
      createFromTemplate: scaffolderPlugin.routes.selectedTemplate,
    });
    bind(apiDocsPlugin.externalRoutes, {
      registerApi: catalogImportPlugin.routes.importPage,
    });
    bind(scaffolderPlugin.externalRoutes, {
      registerComponent: catalogImportPlugin.routes.importPage,
      viewTechDoc: techdocsPlugin.routes.docRoot,
    });
    bind(orgPlugin.externalRoutes, {
      catalogIndex: catalogPlugin.routes.catalogIndex,
    });
  },
  components: {
    // SignInPage: props => <SignInPage {...props} auto providers={['guest']} />,
    SignInPage: props => (
      <SignInPage
        {...props}
        auto
        provider={{
          id: 'microsoft-auth-provider',
          title: 'Microsoft Azure',
          message: 'Sign in using Microsoft Azure',
          apiRef: microsoftAuthApiRef,
        }}
      />
    ),
  },
});
```

### 📃 Provide the context for the Bug.

From the error I can only suspect that my App registration redirect URL might be configured wrong. But this doesn't explain the "failed to fetch user profile" error to me.

If you set your environment up like mine and don't face any issues I'm suspecting the App registration more.

A colleague of mine has created the app registration according to this site
https://backstage.io/docs/auth/microsoft/provider

### 🖥️ Your Environment

OS:   Linux 5.10.16.3-microsoft-standard-WSL2 - linux/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.26.2 (installed)
backstage:  1.25.0

Dependencies:
  @backstage/app-defaults                                          1.5.3
  @backstage/backend-app-api                                       0.5.14, 0.6.2
  @backstage/backend-common                                        0.20.2, 0.21.6
  @backstage/backend-defaults                                      0.2.16
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.9
  @backstage/backend-plugin-api                                    0.6.16
  @backstage/backend-tasks                                         0.5.21
  @backstage/catalog-client                                        1.6.3
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4
  @backstage/cli                                                   0.26.2
  @backstage/config-loader                                         1.7.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.3
  @backstage/core-compat-api                                       0.2.3
  @backstage/core-components                                       0.14.3
  @backstage/core-plugin-api                                       1.9.1
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.3
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.25
  @backstage/integration                                           1.9.1
  @backstage/plugin-api-docs                                       0.11.3
  @backstage/plugin-app-backend                                    0.3.64
  @backstage/plugin-app-node                                       0.1.16
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.8
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.8
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.11
  @backstage/plugin-auth-backend-module-github-provider            0.1.13
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.13
  @backstage/plugin-auth-backend-module-google-provider            0.1.13
  @backstage/plugin-auth-backend-module-guest-provider             0.1.2
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.11
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.13
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.9
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.7
  @backstage/plugin-auth-backend-module-okta-provider              0.0.9
  @backstage/plugin-auth-backend                                   0.22.3
  @backstage/plugin-auth-node                                      0.4.11
  @backstage/plugin-auth-react                                     0.0.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.14
  @backstage/plugin-catalog-backend                                1.21.0
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.3
  @backstage/plugin-catalog-import                                 0.10.9
  @backstage/plugin-catalog-node                                   1.11.0
  @backstage/plugin-catalog-react                                  1.11.2
  @backstage/plugin-catalog                                        1.18.2
  @backstage/plugin-events-node                                    0.3.2
  @backstage/plugin-github-actions                                 0.6.14
  @backstage/plugin-kubernetes-backend                             0.16.3
  @backstage/plugin-kubernetes-common                              0.7.5
  @backstage/plugin-kubernetes-node                                0.1.10
  @backstage/plugin-kubernetes-react                               0.3.3
  @backstage/plugin-kubernetes                                     0.11.8
  @backstage/plugin-org                                            0.6.23
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.13
  @backstage/plugin-permission-backend                             0.5.40
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.27
  @backstage/plugin-permission-react                               0.4.21
  @backstage/plugin-proxy-backend                                  0.4.14
  @backstage/plugin-scaffolder-backend-module-azure                0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.6
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.8
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.6
  @backstage/plugin-scaffolder-backend-module-github               0.2.6
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.2
  @backstage/plugin-scaffolder-backend                             1.22.3
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.2.10, 0.4.2
  @backstage/plugin-scaffolder-react                               1.8.3
  @backstage/plugin-scaffolder                                     1.19.2
  @backstage/plugin-search-backend-module-catalog                  0.1.21
  @backstage/plugin-search-backend-module-techdocs                 0.1.21
  @backstage/plugin-search-backend-node                            1.2.20
  @backstage/plugin-search-backend                                 1.5.6
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.9
  @backstage/plugin-search                                         1.4.9
  @backstage/plugin-tech-radar                                     0.7.2
  @backstage/plugin-techdocs-backend                               1.10.3
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.8
  @backstage/plugin-techdocs-node                                  1.12.2
  @backstage/plugin-techdocs-react                                 1.2.2
  @backstage/plugin-techdocs                                       1.10.3
  @backstage/plugin-user-settings                                  0.8.4
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.3
  @backstage/theme                                                 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Main piece to solve here I think is logging in the backend, so gonna link this to #22939 where we're looking to address that.

As for the actual issue the `/refresh` request might be a red herring. One option is to manually step through the flow to see if there's any information uncovered there: https://backstage.io/docs/auth/troubleshooting#stepping-through-authentication-manually.

Another possibility is that you're hitting the same issue as #23018?

**Comment by dbeltman** [comment]
(I'm taking over for my colleague @twanbeeren this week)

Thanks @Rugvip for your tip regarding the manual flow testing. I tested it and my findings are as follows:
When calling the `https://backstage.ourdomain.com/api/auth/microsoft/start?env=development` URL, i follow the flow until i get to the blank `handler/frame` path.
From there i query the authResponse value:
```
console.log(authResponse)
{"type":"authorization_response","error":{"name":"Error","message":"Failed to sign-in, unable to resolve user identity"}} [debugger eval code:1:9](chrome://devtools/content/webconsole/debugger%20eval%20code)
undefined
``` 
This error message led me to another recent issue #24572 . What i notice there is that he has the microsoftGraphOrg integration setup, which ingests the user/teams data from azure.

Maybe to clear some confusion on our end:

Do we need any other integration setup for working Azure SSO? 
- With *working* i mean; being able to login, without RBAC etc. 
  Just having a valid account on the tenant in azure would be enough for us right now.
  
  
P.S. we are not running into https://github.com/backstage/backstage/issues/23018 as we are not behind a corporate proxy.

**Comment by benjdlambert** [comment]
@dbeltman, just wanna call out my latest message in the https://github.com/backstage/backstage/issues/24572 thread, does your catalog have users ingested from `msgraph`?

**Comment by dbeltman** [comment]
Hi @benjdlambert, no we do not. But that was also our issue. 

We realised that not having users was likely the issue that was causing the error `failed to fetch user profile`.

After my comment i searched some more and came across this issue: https://github.com/backstage/backstage/issues/23748
[The comment summarizing the issue](https://github.com/backstage/backstage/issues/23748#issuecomment-2089061001) pointed me in the right direction. 

So we solved it by manually adding users to the catalog. In the future we will be ingesting users via msgraph so enrollment is handled in a better way.

@twanbeeren  could you close this issue as we have solved this?

**Comment by benjdlambert** [comment]
@dbeltman thanks for the update! Yeah, we would really like to get to the bottom of the `msgraph` ingestion potential issue for the users, so let's see where you land there. Would love to get some feedback in the #24572 if you manage to get it setup and working :pray:
