### ISSUE TITLE
🐛 Bug Report / Improvement: MultipleAnalyticsApi should log errors

### ISSUE THREAD

**Issue by OSfrog** [backstage/backstage#24424]
### 📜 Description

When providing several analytics (e.g `GoogleAnalytics4` and `BackstageInsightsApi`) APIs to `MultipleAnalyticsApi` and one of them fails, all of the provided plugins fail. There are no logs being produced by this because the `catch` block in the `captureEvent` method is [empty](https://github.com/backstage/backstage/blob/83b511d8728e9bdc14c4441ea0d5879fcdf680dd/packages/core-compat-api/src/apis/implementations/AnalyticsApi/MultipleAnalyticsApi.ts#L72). 

### 👍 Expected behavior

To help fail fast and catch the error, it should log the error.

### 👎 Actual Behavior with Screenshots

No screenshots

### 👟 Reproduction steps

In your `apis.ts` file, add this: 

```ts
export const apis: AnyApiFactory[] = [
  createApiFactory({
    api: analyticsApiRef,
    deps: {
      configApi: configApiRef,
      discoveryApi: discoveryApiRef,
      fetchApi: fetchApiRef,
      identityApi: identityApiRef,
      storageApi: storageApiRef,
    },
    factory: ({ configApi, identityApi, discoveryApi, fetchApi, storageApi }) =>
      MultipleAnalyticsApi.fromApis([
        BackstageInsightsApi.fromConfig(configApi, {
          discoveryApi,
          fetchApi,
          identityApi,
          storageApi,
        }),
        GoogleAnalytics4.fromConfig(configApi, {
          identityApi,
        }),
      ]),
  }),
];
```
and don't add a GA config in `app-config.yaml`.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hi @OSfrog 👋🏻  ,
Thanks for opening this issue and making yourself available to help us fix it 🙏🏻 
Please let us know what you think the fix should be (e.g. we should improve the logs or ignore provider errors).
We're also happy to talk more about it in your future pull request review 🙌🏻  .
