### ISSUE TITLE
🐛 Bug Report: [Techdocs] some mkdocs-material features are not working

### ISSUE THREAD

**Issue by dfl-aeb** [backstage/backstage#24436]
### 📜 Description

Some [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) features are not working as expected. For example:

```
---
status: deprecated
icon: material/emoticon-happy 
---
```
like described here: https://squidfunk.github.io/mkdocs-material/reference/

### 👍 Expected behavior

It's expected to work as [described here](https://squidfunk.github.io/mkdocs-material/reference/) and in the same way as when running `mkdocs serve` locally

![image](https://github.com/backstage/backstage/assets/128792991/f6f2305c-7ff5-4ac9-8456-144e4cab5373)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/128792991/71a73778-7766-45ce-9bd4-fbdd5ad5f568)

The reference config is not displayed

### 👟 Reproduction steps

Add the following lines at the top of a Markdown file to [display a status for a page](https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-status):

```
---
status: new
---
```

run 
```bash
techdocs-cli serve -v
```

it works when using the mkdocs-material docker-image
```bash
docker run -it --rm -p 8000:8000 -v ${PWD}:/docs --name mkdocs-material squidfunk/mkdocs-material
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjidotsh** [comment]
I just encountered the same issue. I'm pretty sure this is because Backstage does not support the CSS classes that mkdocs uses for the icons.

**Comment by cftad** [comment]
Not stale.

**Comment by darylgraham** [comment]
This was raised in #5279 which was closed in favor of #3998 which doesn't appear to have resulted in any changes that would support the new mkdocs-material CSS (or any extra styles added inside the docs).

From what I can see there is a set of styles manually copied from mkdocs-material and [hardcoded into the techdocs plugin](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/transformers/styles/rules/variables.ts). Obviously this hasn't been updated with all of the optional styles (eg: md-status--new). Long term, I feel like the best thing to do would be for a new RFC to be opened around improving this experience.

Short term, I worked around it by adding both my extra css as well as the default status variables into my `app\public\index.html`:
```
<head>
...
    <style>
      :root {
        --md-status--updated: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>cellphone-arrow-down</title><path d="M17,1H7A2,2 0 0,0 5,3V21A2,2 0 0,0 7,23H17A2,2 0 0,0 19,21V3A2,2 0 0,0 17,1M17,19H7V5H17V19M16,13H13V8H11V13H8L12,17L16,13Z" /></svg>');
        --md-status: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M11 9h2V7h-2m1 13c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8m0-18A10 10 0 0 0 2 12a10 10 0 0 0 10 10 10 10 0 0 0 10-10A10 10 0 0 0 12 2m-1 15h2v-6h-2v6Z"/></svg>');
        --md-status--new: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="m23 12-2.44-2.78.34-3.68-3.61-.82-1.89-3.18L12 3 8.6 1.54 6.71 4.72l-3.61.81.34 3.68L1 12l2.44 2.78-.34 3.69 3.61.82 1.89 3.18L12 21l3.4 1.46 1.89-3.18 3.61-.82-.34-3.68L23 12m-10 5h-2v-2h2v2m0-4h-2V7h2v6Z"/></svg>');
        --md-status--deprecated: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M9 3v1H4v2h1v13a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V6h1V4h-5V3H9m0 5h2v9H9V8m4 0h2v9h-2V8Z"/></svg>');
        --md-status--encrypted: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 1 3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4m0 6c1.4 0 2.8 1.1 2.8 2.5V11c.6 0 1.2.6 1.2 1.3v3.5c0 .6-.6 1.2-1.3 1.2H9.2c-.6 0-1.2-.6-1.2-1.3v-3.5c0-.6.6-1.2 1.2-1.2V9.5C9.2 8.1 10.6 7 12 7m0 1.2c-.8 0-1.5.5-1.5 1.3V11h3V9.5c0-.8-.7-1.3-1.5-1.3Z"/></svg>');
      }

      .md-status--updated::after {
        -webkit-mask-image: var(--md-status--updated);
        mask-image: var(--md-status--updated);
      }
    </style>
...
</head>
```

**Comment by cftad** [comment]
Not stale.

**Comment by alexlorenzi** [comment]
Yes, @darylgraham is correct that in the case of the status icons the CSS hasn't been copied across to support this. In the short term, we can add those so they're at least supported. 

A larger change that moves away from this necessity will take longer and require input from more parties, but is something we can start looking at.

**Comment by alexlorenzi** [comment]
@cftad - Hey, I have a PR open to fix this. LMK if this does or doesn't address or issues.
Thanks
