### ISSUE TITLE
🐛 Bug Report: TechDocs displays the default micdrop error page for any errors instead of utilizing the custom NotFoundErrorPage component from AppComponent.

### ISSUE THREAD

**Issue by akmarif** [backstage/backstage#24443]
### 📜 Description

When a mistake happens in the techdocs or documentation because something is missing or cannot be found, backstage displays a standard 'mic drop' 404 page. It doesn't use the custom DefaultNotFoundPage of NotFoundErrorPage properties of the component when creating the app. The ErrorPage component is hardcoded in the techdocs code to reveal an error if one occurs.

### 👍 Expected behavior

It should be feasible to employ the NotFoundErrorPage component from AppComponent for presenting a customized 404/500 error page UI instead of relying solely on the default mic drop design in Backstage. Presently, when Backstage encounters a missing catalog/docs/techdocs, it resorts to displaying the default mic drop 404 page. This is because the mic drop 404 page is hardcoded for missing/build issue techdocs. It would be advantageous if Backstage could be configured to showcase a custom 404/500 page specifically for cases where documentation is absent or not found, akin to the approach used with components#NotFoundErrorPage: DefaultNotFoundPage when developing an app.

### 👎 Actual Behavior with Screenshots

Techdocs/docs are showing default 404 mic drop error page because of hard coded ErroPage.

![Screenshot 2024-04-22 at 13 31 37](https://github.com/backstage/backstage/assets/7996493/1285d7fc-c672-4445-a7f6-bada99f44689)

### 👟 Reproduction steps

use `const DefaultNotFoundPage = () => <CustomErrorPage status="404" />;` and assign it in `NotFoundErrorPage` of components properties while creating the application. 
1. Click Docs from menu.
2. select any Documentation from docs which does not exists in storage or it has any build error.
3. You will see default mic drop 404/500 page

it does not shows CustomErrorPage component as default.

### 📃 Provide the context for the Bug.

Use want to use custom 404/500 error page(do not want to show default mic drop error page) allover the application to keep similarity for any type of 404/500 errors including techdocs 404.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Beamister** [comment]
We have also run into this issue and found that users are currently confused by the techdocs error page when they follow links to docs pages that have moved or been deleted. Being able to show the error page we've setup for the rest of Backstage would be great. @freben do you happen to know if someone is already planning to look at this?

**Comment by Rugvip** [comment]
@Beamister as far as I know nobody is working on this. Happy for any help towards getting this reseolved!
