### ISSUE TITLE
🐛 Bug Report: backstage-cli create-github-app permissions

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#24441]
### 📜 Description

When using `backstage-cli create-github-app` it does not add the needed permissions as per the docs here: https://backstage.io/docs/integrations/github/github-apps#app-permissions. Specifically there is issues with needing the commit statuses permission.

Historically this was added to the GitHub `UrlReader` and caused issues like this: https://github.com/backstage/backstage/issues/17465

### 👍 Expected behavior

Using `backstage-cli create-github-app` should add the needed permissions as per the docs here: https://backstage.io/docs/integrations/github/github-apps#app-permissions. 

### 👎 Actual Behavior with Screenshots

We get an error roughly like this:

```text
[1] 2023-04-27T11:05:01.825Z techdocs error Failed to build the docs page: Request failed for 
https://api.github.com/repos/<org>/<repo>/commits/master/status?per_page=0, 403 Forbidden Request failed for 
https://api.github.com/repos/<org>/<repo>/commits/master/status?per_page=0, 403 Forbidden type=plugin stack=Error: 
Request failed for https://api.github.com/repos/<org>/<repo>/commits/master/status?per_page=0, 403 Forbidden
```

### 👟 Reproduction steps

1. Create a Backstage instance
2. Run `backstage-cli create-github-app`
3. Configure the app in you `integration` section
4. Use TechDocs or the Scaffolder

Notice: you get the 403 error listed above

### 📃 Provide the context for the Bug.

Not having the right permissions meant we needed to hunt this down. We just wanted to setup a GitHub app and this seemed the easiest way.

### 🖥️ Your Environment

Not really environment specific you need to use `backstage-cli create-github-app`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
I think this section of code needs to be updated:

https://github.com/backstage/backstage/blob/1d02904ffd7162bcfb37d51f3452391d68d47081/packages/cli/src/commands/create-github-app/index.ts#L29-L50

To add the needed permissions specifically commit status which can be read.

**Comment by freben** [comment]
Made a stab at it. Needs some verification though
