### ISSUE TITLE
🚀 Feature: Show/Hide "<EntityLayout.Route >" using Ownership Entities

### ISSUE THREAD

**Issue by toasahi** [backstage/backstage#24462]
### 🔖 Feature description

I use the Kubernetes plugin. However, I am not able to maintain permissions on BackStage. Therefore, it is easy for developers who are not granted permissions to see the logs of confidential information pods.
I want to use "Ownership Entities" so that only users with the same Entity can see the Kubernetes plugin Workload.

### 🎤 Context

```
const MatchOwnerEntity = () => {
  const { entity } = useEntity()
  const identityApi = useApi(identityApiRef);

  const matchOwner = useAsync(async () => {
    const identity = await identityApi.getBackstageIdentity();
    const owner = identity.ownershipEntityRefs
    // Get after / in "development/guest
    return owner.map(value => value.substring(value.indexOf("/") + 1)).some((value)=>value === entity.spec?.owner)
  });

  if(!matchOwner.value){
     return <></>
  }

  return (
    <EntityKubernetesContent refreshIntervalMs={30000} />
  );
}

```

However, I get the following error.
"Routable extension component with mount point routeRef{type=absolute,id=kubernetes} was not discovered in the app element tree. Routable extension components may not be rendered by other components and must be directly available as an element within the App provider component."

What is your solution?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
The way that the frontend system works, is that it auto-discovers plugins through the root JSX tree. When you render this as a component, the kubernetes plugin is no longer part of the root tree, so it doesn't get auto discovered. Backstage doesn't think the plugin that `EntityKubernetesContent` belongs to exists.

The manual way of fixing this is to manually make sure the plugin gets discovered. You can do this by adding it to your `packages/app/src/plugins.ts`, or pass it to the `plugins` argument to `createApp` in `packages/app/src/App.tsx`.

The more thorough way to do it, is to instead just render the target component inside an `EntitySwitch` (like [in this example](https://github.com/backstage/backstage/blob/a03b86497b59124967dc4812ccec7de261c74658/packages/app/src/components/catalog/EntityPage.tsx#L140)) with a custom function passed to `if` that figures out to do. Then you don't need to manually register the plugin at all.

```ts
function isCustomOwned = async (entity: Entity, context: { apis: ApiHolder }): Promise<boolean> => {
  const identityApi = context.apis.get(identityApiRef);
  const identity = await identityApi.getBackstageIdentity();
  // ... do logic, return true or false
}
```
