### ISSUE TITLE
🐛 Bug Report: dead link for the Octopus Deploy Plugin

### ISSUE THREAD

**Issue by wiredsource** [backstage/backstage#24509]
### 📜 Description

gives a 404:
https://backstage.io/plugins
![image](https://github.com/backstage/backstage/assets/5127350/71cf0d5d-9824-42ac-a305-47c183cde3e6)

https://github.com/backstage/backstage/blob/master/plugins/octopus-deploy/README.md

### 👍 Expected behavior

.

### 👎 Actual Behavior with Screenshots

.

### 👟 Reproduction steps

Click on the Explore button

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Woops! They've all been moved into the [community-plugins](https://github.com/backstage/community-plugins) repository now. 

Think that they all need updating, is this something that you want to help us fix @wiredsource? :pray:
