### ISSUE TITLE
🐛 Bug Report: Separate Frontend and Backend 

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#24507]
### 📜 Description

We are working on separate frontend and backend server for backstage. We have separate URL for frontend and backend.

We are trying to inject backend URL into frontend App. It seems like injection does not work on run time.

ENV
export APP_CONFIG_app_baseUrl=http://example-app.com
export APP_CONFIG_backend_baseUrl=http://example-backend.com
export APP_CONFIG_backend_cors_origin=http://example-app.com

Error:
`react-dom.production.min.js:189 Error: Missing required config value at 'backend.baseUrl' in 'app-config.yaml'
    at k.getString (index.esm.js:334:13)
    at Object.factory (index.esm.js:38:20)
    at ct.load (index.esm.js:110:25)
    at ct.get (index.esm.js:95:17)
    at de (StorageApi-c8a5e616.esm.js:18:25)
    at dt (Root.tsx:107:24)
    at Ci (react-dom.production.min.js:167:137)
    at ta (react-dom.production.min.js:290:337)
    at qs (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
Ti @ react-dom.production.min.js:189
Show 1 more frame
Show less
react-dom.production.min.js:283 Uncaught Error: Missing required config value at 'backend.baseUrl' in 'app-config.yaml'
    at k.getString (index.esm.js:334:13)
    at Object.factory (index.esm.js:38:20)
    at ct.load (index.esm.js:110:25)
    at ct.get (index.esm.js:95:17)
    at de (StorageApi-c8a5e616.esm.js:18:25)
    at dt (Root.tsx:107:24)
    at Ci (react-dom.production.min.js:167:137)
    at ta (react-dom.production.min.js:290:337)
    at qs (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)`

Dockerfile:
USER root
RUN apk update && apk add jq && rm -rf /var/cache/apk/*
RUN rm -rf /usr/share/nginx/html/*
COPY packages/app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY docker/inject-config.sh /docker-entrypoint.d/40-inject-config.sh
RUN chmod 755 /docker-entrypoint.d/40-inject-config.sh
COPY ./dockerRun.sh /usr/share/nginx/html/dockerRun.sh
RUN chmod +x /usr/share/nginx/html/dockerRun.sh
USER 1001

# USER 1001
# [Optional] Set the default user. Omit if you want to keep the default as root.
ENTRYPOINT ["/usr/share/nginx/html/dockerRun.sh"]
EXPOSE 8080
CMD nginx`

Docker Run
#!/usr/bin/env sh
/docker-entrypoint.d/40-inject-config.sh
nginx -g 'daemon off;'

app/package.json

  "configSchema": {
    "$schema": "https://backstage.io/schema/config-v1",
    "title": "@internal/shared",
    "type": "object",
    "properties": {
      "backendBaseurl": {
        "type": "string",
        "visibility": "frontend"
      },
      "buildBranch": {
        "type": "string",
        "visibility": "frontend"
      },
      "backend": {
        "type": "object",
        "properties": {
          "baseUrl": {
            "type": "string",
            "visibility": "frontend"
          }
        }
      }
    }
  }
  
  
**Local Docker:**
2024-04-24 18:01:03 starting the script
2024-04-24 18:01:03 Runtime app config: {
2024-04-24 18:01:03   "backend": {
2024-04-24 18:01:03     "baseUrl": "http://localhost:8080"
2024-04-24 18:01:03   }
2024-04-24 18:01:03 }
2024-04-24 18:01:05 Writing runtime config to /usr/share/nginx/html/static/module-backstage.fe735dd0.js
2024-04-24 18:01:05 {\"backend\":{\"baseUrl\":\"http:\/\/localhost:8080\"}}
2024-04-24 18:01:05 End of Script

**Browser Console error:** 
  Uncaught SyntaxError: Unexpected identifier 'backend' (at module-backstage.fe735dd0.js:2:72233)
   
<img width="1728" alt="image" src="https://github.com/backstage/backstage/assets/225961/8a9347a0-acc0-465c-b044-698df09c4125">

### 👍 Expected behavior

We should inject backend URL on run time. It is not working, we are unable to inject any variables.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/225961/a4235670-7056-48c7-8f5e-1619216b3146)

### 👟 Reproduction steps

Follows steps from this documentation for separate frontend and backend 
https://backstage.io/docs/deployment/docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
I tried reproducing but it's working as expected. I created a new `@backstage/create-app` and set up https://github.com/backstage/backstage/tree/master/contrib/docker/frontend-with-nginx with the host build.

Seeing the following in logs related to the config injection:

```
Runtime app config: {
  "app": {
    "title": "Testing"
  }
}
Writing runtime config to /usr/share/nginx/html/static/module-backstage.e56bc9d9.js
```

In the frontend it all works fine and the app title is updated.

Seems like you're encountering a parsing error. It might help if you're able to dig into the source file and track down the part with the error and post that and the surrounding code here.

**Comment by lalit774** [comment]
@Rugvip I am getting same error with fresh backstage application. It is injecting the runtime config. but after that it throw the error.

Injection happen like this.

function ws(L="{"app":{"title":"Testing"}}"){const p=[{context:"app-config.yaml",data:{app:{title:"Scaffolded Backstage App",baseUrl:"http://localhost:3000"},organization:{name:"My Company"},backend:{baseUrl:"http://localhost:7007"},integrations

![image](https://github.com/backstage/backstage/assets/225961/d46750f4-97ea-49ca-9c1c-7b4f04596329)

Console Error:
![image](https://github.com/backstage/backstage/assets/225961/0441517d-db4c-4916-888b-f5af62b8696b)
[](url)

**Comment by Rugvip** [comment]
Hmm, that's strange. Your injected config isn't properly escaped, for me it looks like this after injected: `d="{\"app\":{\"title\":\"Testing\"}}"`

The escaping is handled by this line, could this be related to the sed version in the container? https://github.com/backstage/backstage/blob/7e2c0bc96f941328dfd3b04c5c4ec2efc3657ace/contrib/docker/frontend-with-nginx/docker/inject-config.sh#L26

**Comment by lalit774** [comment]
Thank You @Rugvip It works for us. we had sed version 4.0. It works with 4.9
