### ISSUE TITLE
🚀 Feature: plugins/catalog-backend-module-backstage-openapi Authorise SwaggerUI with current user session

### ISSUE THREAD

**Issue by secustor** [backstage/backstage#24515]
### 🔖 Feature description

SwaggerUI allows to authorise requests which will be sent when using the `Try Out` feature. 

This `authorise` feature should allow to authenticate using the logged in users permission. 

### 🎤 Context

I my case, we are seeing great interest in integrating external tooling into our Backstage instance. 
Tough for trying out the API or one shot queries e.g. such as creating reports it is cumbersome to deploy a separate service. 

Ideally it would be possible to use SwaggerUI to trigger such calls. Currently this is only possible via JWT tokens, which based on my limited understanding of the new auth system, can not be created by end users.

### ✌️ Possible Implementation

As mentioned above, my knowledge of the new auth system is limited. 

My expectation would be that is possible to use [`preauthorizeBasic`](https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/configuration.md#instance-methods) or [`responseInterceptor`](https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/configuration.md#network) to request a token from the auth system with `getLimitedUserToken` and add it to the headers. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by aramissennyeydd** [comment]
👋 Thanks for this! Can you share a little bit more what you're looking for? Are you looking to access the Backstage internal OpenAPI documentation from external SwaggerUIs or the internal SwaggerUI?

**Comment by secustor** [comment]
We are using the internal one and want to authorize using the login on the same Backstage instance.

**Comment by aramissennyeydd** [comment]
Can you try adding a `requestInterceptor` from [this guide](https://github.com/aramissennyeydd/backstage/blob/f798e475c028a334a99210a845174003585f4345/plugins/api-docs/README.md#adding-requestinterceptor-to-swagger-ui)? You can find the token from the frontend with the [frontend `identityApi`](https://github.com/aramissennyeydd/backstage/blob/f798e475c028a334a99210a845174003585f4345/packages/core-app-api/src/apis/implementations/FetchApi/IdentityAuthInjectorFetchMiddleware.ts#L64), you shouldn't need to use the new auth work as that is for the backend.

**Comment by aramissennyeydd** [comment]
@secustor That looks right, not sure why you're running into a URL error. I would open a separate issue.
