### ISSUE TITLE
🚀 Feature: Better documentation for sorting and paginating for Table

### ISSUE THREAD

**Issue by dariozachow** [backstage/backstage#24521]
### 🔖 Feature description

It is really hard to use the Table Component by Backstage, within your own plugin, because there are no docs for showing how this thing works. The types provided by Table or not really good documented as well. 

### 🎤 Context

I was trying simple things like custom sorting and server side pagination with the table but failed when trying. When looking in the backstage code I found that this is possible but not that easy as I'm not a frontend dev primarily. Therefore it would be really helpful to have some guidance in how to do such things.

### ✌️ Possible Implementation

Update the docs and explain how to do certain things with it. The only thing I found was https://backstage.io/docs/reference/core-components.table/ and the storybook.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by dariozachow** [comment]
Still struggling with implementing this 😓

**Comment by vinzscam** [comment]
we do something similar in https://github.com/backstage/backstage/blob/32cc4e64681bea7cbc27f141bae8dd714031c5e7/plugins/catalog/src/components/CatalogTable/PaginatedCatalogTable.tsx#L4

when paginating server side, you want to try to minimize the logic needed from the Table component, as everything will be handled server side. Under the hood, the `Table` component uses https://material-table-core.github.io/ and all the props are inherited.

**Comment by dariozachow** [comment]
Thanks for your answer. I already looked at the paginated Table, but when using the same settings/options for the table the pagination buttons were not clickable. This was kinda confusing and I could not figure out why.

I'll take a look into the material table soon.

**Comment by vinzscam** [comment]
ok, keep attention to the `page` and `totalCount` props as they are the two props that enable the pagination buttons (it was a small hack 😅)

**Comment by dariozachow** [comment]
Thanks for the input, I'll try that soon.
