### ISSUE TITLE
🚀 Feature: Documentation on "Publish private"

### ISSUE THREAD

**Issue by piatkiewicz** [backstage/backstage#24527]
### 🔖 Feature description

It would be very useful to have "Publish private" document describing proper way of publishing new or modified plugin. Currently the document is empty 
- https://backstage.io/docs/plugins/publish-private/ 
- https://github.com/backstage/backstage/edit/master/docs/plugins/publish-private.md

### 🎤 Context

Not sure what should be changed in package.json and other steps

### ✌️ Possible Implementation

There could be an example in documentation showing adding a simple `<p>hello</p>` in [@backstage/plugin-catalog-import](https://github.com/backstage/backstage/tree/master/plugins/catalog-import) somewhere, what other changes should be made to prepare it for private publish and how to publish it in some private registry GitHub/ADO Artifacts etc.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by subash-n-miq** [comment]
@piatkiewicz I would like to contribute. Can you assign it to me?

**Comment by subash54** [comment]
@piatkiewicz I would like to contribute. Can you assign it to me?

**Comment by benjdlambert** [comment]
Hey :wave: thanks for raising this issue!

I think there's definitely room to expand this documentation section to maybe `Publishing` in general, and talking about publishing from your own repository to publish `npm`, publishing from your own repository to your own `private` registry and also publishing from the [community plugins](https://github.com/backstage/community-plugins) repository too.

@subash54 do you think that this makes sense?

**Comment by subash54** [comment]
@benjdlambert Yeah it will be helpful.
We need to add the following Documents right.
- [ ] Docs to Publish a plugin to npm
- [ ] Docs to Publish a plugin to a private registry
- [ ] Docs to Publish from community plugins to npm or private registry 

Can you please verify?

**Comment by benjdlambert** [comment]
Last one should be `Docs to Publish from Community Plugins repo to the @backstage-community scope` or something I think

**Comment by djannot** [comment]
@subash54 do you already have a draft available ? I'd like to understand how to use the backend plugin I'm developing without submitting it.

**Comment by subash54** [comment]
@benjdlambert @djannot Here is my [PR](https://github.com/backstage/backstage/pull/25107) publish plugins to the private repository.

**Comment by subash54** [comment]
@benjdlambert  Can you please review the above PR?

**Comment by camilaibs** [comment]
Pull request re-opened.

**Comment by subash54** [comment]
@benjdlambert Can you please review the above PR?

**Comment by meleu** [comment]
As a docs consumer I can say that the contents of this PR, with an intro highlighting that this is just **one way** of publishing a plugin to a private registry, would be much more helpful than a page saying **TODO**.

Another alternative is simply removing that page as a whole, as **TODO** doesn't help and gives the impression that at some point the instructions will be there.

Again, l strongly believe that the instructions in this PR are short and helpful. A simple paragraph in the intro saying that there are many ways to publish packages to private registries, would be nice.
