### ISSUE TITLE
Extract the `Scheduler` service to `backend-defaults` and deprecated the `backend-tasks` package

### ISSUE THREAD

**Issue by camilaibs** [backstage/backstage#24535]
### Context

Ref: https://github.com/backstage/backstage/issues/24493

Default service implementations should be provided from the `backend-default` package before we release a stable backend system version.

### Description

The schedule service implementation, which is currently exported from the `backend-tasks` package, should be exported as a separate subpath from the `backend-defaults` package.

### Acceptance criteria

- Extracted code should be re-exported from the new module in a old package `deprecated.ts` file
- Deprecation exports should be annotated with `@deprecated` and contain a comment explaining what to replace with
- Other packages' import statements should be updated to use bindings from the new package
- Documentation examples should be revisited use code from the new package instead

**Comment by freben** [comment]
WIP branch: https://github.com/backstage/backstage/tree/freben/tasks-plugin-api

**Comment by freben** [comment]
Discussion ongoing about what our package/export structure should be with all this
