### ISSUE TITLE
🐛 Bug Report: Kubernetes react -> Warning: validateDOMNesting(...): <ul> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by sebalaini** [backstage/backstage#24533]
### 📜 Description

The Kubernetes react plugin contains some HTML validation errors, is located in the [FixDialog#L99-L109](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-react/src/components/Pods/FixDialog/FixDialog.tsx#L99-L109)[](url)

### 👍 Expected behavior

The wrapper `<Typography>` should be removed and possibly replace the plain `ul` & `li` with a `List, ListItem, ListItemText` from `@material-ui/core` to align with other parts of the site.

### 👎 Actual Behavior with Screenshots

following the HTML standard, list elements (in particular, ol and ul elements) cannot be children of p elements.

Currently, the `FixDialog` wraps a list element with a `<Typography>` component, besides returning a warning in the console during development it can also be seen when you run the `plugin-kubernetes-react` test suite.

```
console.error
  Warning: validateDOMNesting(...): <ul> cannot appear as a descendant of <p>.
```

Even though it's returned as an error in the terminal, it doesn't make the test fail.

<img width="845" alt="Screenshot 2024-04-27 at 10 45 14" src="https://github.com/backstage/backstage/assets/17096352/648ff442-b883-4632-94dc-7aa66ceae3a3">

### 👟 Reproduction steps

Run the `plugin-kubernetes-react` test suite and check the terminal for this error.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sebalaini** [comment]
I could open a PR @camilaibs if you are interested

**Comment by camilaibs** [comment]
> I could open a PR @camilaibs if you are interested

It would be greatly appreciated 🙏🏻 , would you mind if we assigned it to you?

**Comment by sebalaini** [comment]
Sure but before can you help fix my local? I changed the Mac and I can't install Backstage anymore.

This is the terminal log:
```
...
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 643ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 388ms
➤ YN0000: ┌ Link step
➤ YN0007: │ canvas@npm:2.11.2 must be built because it never has been before or the last one failed
➤ YN0009: │ canvas@npm:2.11.2 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/dg/4qgmkwtd2ml8fmbn3nclxk480000gn/T/xfs-1386aaf1/build.log)
➤ YN0000: └ Completed in 2s 498ms
➤ YN0000: Failed with errors in 3s 982ms
```

and this part of the log:
```
# This file contains the result of Yarn building a package (canvas@npm:2.11.2)
# Script name: install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@18.18.2 | darwin | arm64
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@18.18.2 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
gyp info it worked if it ends with ok
```

🤔 I'm quite sure I was using node 18.18 even in the old Mac.

**Comment by sebalaini** [comment]
I think the fix should be quite easy.

This is how I would fix it, lines 99 to 109 of `plugins/kubernetes-react/src/components/Pods/FixDialog/FixDialog.tsx`

```
<Grid item xs={12}>
  <Typography variant="h6">Fix:</Typography>
  <List>
    {(error.proposedFix?.actions ?? []).map((fix, i) => {
      return (
        <ListItem key={`${pod.metadata?.name ?? 'unknown'}-pf-${i}`}>
          {fix}
        </ListItem>
      );
    })}
  </ul>
</Grid>
```

**Comment by camilaibs** [comment]
> Sure but before can you help fix my local? I changed the Mac and I can't install Backstage anymore.
> 
> This is the terminal log:
> 
> ```
> ...
> ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
> ➤ YN0000: └ Completed in 0s 643ms
> ➤ YN0000: ┌ Fetch step
> ➤ YN0000: └ Completed in 0s 388ms
> ➤ YN0000: ┌ Link step
> ➤ YN0007: │ canvas@npm:2.11.2 must be built because it never has been before or the last one failed
> ➤ YN0009: │ canvas@npm:2.11.2 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/dg/4qgmkwtd2ml8fmbn3nclxk480000gn/T/xfs-1386aaf1/build.log)
> ➤ YN0000: └ Completed in 2s 498ms
> ➤ YN0000: Failed with errors in 3s 982ms
> ```
> 
> and this part of the log:
> 
> ```
> # This file contains the result of Yarn building a package (canvas@npm:2.11.2)
> # Script name: install
> 
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@1.0.11
> node-pre-gyp info using node@18.18.2 | darwin | arm64
> node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
> node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
> node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@18.18.2 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
> node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
> gyp info it worked if it ends with ok
> ```
> 
> 🤔 I'm quite sure I was using node 18.18 even in the old Mac, though is true that was an Intel Mac and this is the M2

Please follow these canvas installation requirements for MacOS:
https://www.npmjs.com/package/canvas#compiling

**Comment by sebalaini** [comment]
Thanks @camilaibs that solved the problem :) I'm going to open a PR for this issue.

**Comment by sebalaini** [comment]
@camilaibs PR opened :) let me know what do you think about it.

**Comment by camilaibs** [comment]
> @camilaibs PR opened :) let me know what do you think about it.

I just suggested fixing the changeset validation errors in the pull request. Other than that, the changes looks amazing 👏🏻

**Comment by sebalaini** [comment]
accepted :)

**Comment by LegendSebastianoL** [comment]
good to close this :) it got merged yesterday.

**Comment by Rugvip** [comment]
Thank you! 👍
