### ISSUE TITLE
Remove `ContainerRunner` and its implementations from the `backend-common` package

### ISSUE THREAD

**Issue by camilaibs** [backstage/backstage#24549]
### Context

Due to the backend common deprecation effort, the [ContainerRunner](https://github.com/backstage/backstage/blob/b22e4def6f9f6a09855cdea9e8712f06564d4d9a/packages/backend-common/src/util/ContainerRunner.ts#L61) interface and its implementations must be moved to a new package. The container runner is a utility that abstracts container orchestrator implementations (`DockerContainerRunner` and `KubernetesContainerRunner`) and it is used by multiple backend plugins (`Scaffolder` and `TechDocs`).

### Open questions

The team briefly discussed whether to convert it to a core service and extract it to the `backend-plugin-api` package, but we don't think that is the case.

So far, the following suggestions have been made:
- Convert this to a contrib tutorial file;
- Duplicate the utilities code in all packages where it is used;
- Move to the `Scaffolder` node package.

### Suggested approach

- [x] Determine where these utilities should be placed and relocate the files to the new package: https://github.com/backstage/backstage/issues/24928
  - [x] Update the `Scaffolder` and `TechDocs` plugin to import the utilities from the new package
    - [x] `Scaffolder` https://github.com/backstage/backstage/pull/24612
    - [x] `TechDocs`  https://github.com/backstage/backstage/pull/24593
  - [x] Deprecate the utilities on the `backend-common` package (usually we install the new package, create a `deprecated.ts` file and re-export the utilities annotating  them as `@deprecated`)
  - [x] Update also documentation code snippets to ensure they use the utilities from the new package

**Comment by camilaibs** [comment]
I just wanted to let you know that we will be discussing this on the Framework SIG today (cc/ @Rugvip).

**Comment by camilaibs** [comment]
The `TechDocs` and `Backend Common` pull requests were merged: https://github.com/backstage/backstage/pull/24593
https://github.com/backstage/backstage/pull/25269

**Comment by freben** [comment]
Fixed!
