### ISSUE TITLE
🚀 Feature: Improve auth handling in the proxy

### ISSUE THREAD

**Issue by freben** [backstage/backstage#24551]
### 🔖 Feature description

The incoming end of [the proxy-backend plugin](https://github.com/backstage/backstage/blob/ed83f855352307de4a67b878af97b6dbdb191d5f/plugins/proxy-backend) currently allows unauthenticated access. In the new backend system, we have the opportunity to improve this.

### 🎤 Context

The proxy backend currently [adds a blanket auth policy](https://github.com/backstage/backstage/blob/ed83f855352307de4a67b878af97b6dbdb191d5f/plugins/proxy-backend/src/alpha.ts#L47) of `allow: 'unauthenticated'`. This is possibly surprising in a backend ecosystem that wants to be secure by default.

### ✌️ Possible Implementation

Add an `auth` option on proxy endpoints.

```diff
 proxy:
   endpoints:
     '/sentry/api':
       target: https://sentry.io/api/
       allowedMethods: ['GET']
+      auth: require
       headers:
         Authorization: ${SENTRY_TOKEN}
```

Some ideas for possible values below. Not all are possibly relevant; they're just ideas. Could probably be shortened to just two or three options.

- `require`: Require any type of valid Backstage user or service token. The token is not passed through to the upstream. Ideally made the default in a breaking change.
- `require-user`: Require a Backstage user token specifically where you don't want to allow services to generally call it.  The token is not passed through to the upstream.
- `passthrough`: Require any type of valid Backstage user or service token. The token is forwarded to the upstream.
- `dangerously-allow-unauthenticated`: Like before; ignore incoming auth entirely.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Yep makes sense 👍

I'd argue that we might not need `require-user`? Or do you have a specific use-case in mind?

And yep, `require` or w/e we call it would be the default.

Regarding naming, `passthrough` could also be `forward`.

**Comment by freben** [comment]
No, `require-user` was just because I had a gut feeling that there are some cases where you really want to just drive user flows and aren't interested in "accidentally" letting your entire backend flora make accesses too via some static secret that you happen to have configured. Happy to keep it slim and not introduce anything unnecessary at all for starters.

`forward` sounds like the batter choice 👍
