### ISSUE TITLE
🚀 Feature: Dynamic configuration fetching of frontend from backend 

### ISSUE THREAD

**Issue by secustor** [backstage/backstage#24561]
### 🔖 Feature description

Currently all configuration has to be provided during compile time of the frontend. 
This complicates providing environment specific configuration e.g. Datadog RUM `env` settings. 

The frontend config API should provide a way to signal that a config value needs be fetched from the backend and implicitly check regularly the state. 

### 🎤 Context

I'm trying to setup environment specific setting such as URLs to service instances in the same environment. 
Another use case is setting `env` keys for observability, without building a separate frontend per environment. 

`@freben` discussed this some time ago on Discord.  https://discord.com/channels/687207715902193673/1026835211285184593/1027522150518755328

> If they are to be consumed by the frontend, you have to supply them (there's no config fetching protocol from the backend or so at runtime, it's all gotta be baked in)
But for everything else, like secrets and whatnot, stay lax
We want to change this so that the frontend fetches config dynamically. But it'll be some time until that becomes a priority, and there's still the bootstrapping problem of the frontend needing to know for example where to go to get that config in the first place 🙂

### ✌️ Possible Implementation

The backend would need a new `api/config` endpoint which returns configuration for plugins or all configurations based on the scope of the auth token. 

On the frontend side, we can change this behaviour under the hood and create an optional additional options parameter which allows to force behaviour.   

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Bit of a tricky one this. With the signals plugin it shouldn't be too hard to wire up the functionality, but I'm a bit worried what effect it might have on the frontend. Perhaps one of the main bits there being that you might end up with partial updates of config in plugins that might lead to bugs. If we wanted to do this I think we'd need to be very careful about how updates our applied. For now I don't think this is something we want to prioritize short/mid term.

What we have been discussing as part of #22423 is to at least notify users that configuration has been updated and that they should reload their page to view the latest version of the app. Do you think that would be an alright middle ground in this case too?

**Comment by secustor** [comment]
Yes, sound like the frontend rebuild could solve this. For my usecase I need a separate build per container start or configuration change, so it should be covered in that BEP.
