### ISSUE TITLE
Run integration tests on all major databases

### ISSUE THREAD

**Issue by freben** [backstage/backstage#2460]
## Feature Suggestion

The Backstage repo should come with a suite of database integration tests, which ensure that we stay compatible with the major databases that we want to support. The tests would ideally run all the migrations, fire up a backend, perform some basic operations, and clean up.

## Possible Implementation

These tests would probably fire up transient dockerized databases, for at least SQLite, PostgreSQL and MySQL/MariaDB, and run a battery of tests onto them equally.

## Context

At the moment, the tests for database cases have some room for improvement. Migrations are run during end-to-end tests but only for one of the database vendors. No full workflows are being tested with a multi-database focus. We should improve the confidence level for making DB related changes going forward, without risking breaking for just one of the database engines or similar.

**Comment by Rugvip** [comment]
Yep, think we should add this as a part of #2369, and also get some nightly builds going

**Comment by ThiruKMphasis** [comment]
Will it support rdf4j graph database
