### ISSUE TITLE
Decide what to do with the `Git` abstraction and deprecated it  from the `backend-common` package

### ISSUE THREAD

**Issue by camilaibs** [backstage/backstage#24604]
### Context

Ref: https://github.com/backstage/backstage/issues/24493

Before the stable release, we will be deprecating the backend common package, and the `Git` abstraction will be moved elsewhere. This task is for us to decide what to do with the Git abstraction, and then make the changes according to our decision.

### Open questions

Some of it can be moved into scaffolder-node implementations, but more discussion is needed.

### Suggested approach

- [x] Determine whether more than one plugin uses it
- [x] Examine whether it fits with a new backend concept
- [x] Extract the files and update the references import statements
- [x] Deprecate the export from the backend common package (re-export from the new package with "@deprecated" as a annotation)
- [x] Verify everything is working as before and update any documentation

**Comment by javiermartingonzalez** [comment]
Hello, how can I use the Git abstraction after deprecation?

**Comment by camilaibs** [comment]
Hi @javiermartingonzalez 👋🏻 , as we mentioned in the [changelog](https://github.com/backstage/backstage/blob/master/packages/backend-common/CHANGELOG.md#patch-changes-1), the abstraction will be removed from the backstage backend packages because it is not used in the framework itself, the implementation was created by the community and was only used by plugins. We recommend you copying the implementation to you plugin in case you are using it or as it’s a fairly thin wrapper on top of the underlying library you may enjoy using that directly instead of the wrapper 🙂 .
