### ISSUE TITLE
🚀 Feature: Home Page Quick Start Card

### ISSUE THREAD

**Issue by nikolarAutodesk** [backstage/backstage#24600]
### 🔖 Feature description

A Quick Start card on the home page can be helpful for new users to get up to speed on their companies internal developer portal.
![genericCard](https://github.com/backstage/backstage/assets/146387693/cf2b21e1-65ce-40a0-90f4-5db567c5f052)

https://github.com/backstage/backstage/assets/146387693/b7dff080-d490-465d-a478-6f48961c3e42

### 🎤 Context

Our team frequently receives questions about our new IDP and requests for help with onboarding. So, our product and design team created this Quick Start card to link users to the most important information when they first land on the IDP.

We thought this might be helpful for other Backstage adopters, but we want to get an opinion on this before submitting a PR contributing to the [[@backstage/plugin-home](https://github.com/backstage/backstage/blob/master/plugins/home/api-report.md)](https://github.com/backstage/backstage/blob/master/plugins/home/api-report.md)

### ✌️ Possible Implementation

The following displays all of the features of the card we have implemented on our end. We would contribute this as a basic QuickStart card, where a developer can pass in props to populate the card specifically for their company

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
friendly ping to @backstage/home-maintainers

**Comment by emmaindal** [comment]
Hello @nikolarAutodesk, thanks for opening this issue! Looks like a really good addition to the group of optional Homepage cards adopters can use for Backstage. I'll add a "help wanted" label to the issue so feel free to let us know if you are planning to work on it and we can assign you to the issue.

**Comment by nikolarAutodesk** [comment]
I'd like to work on this during KubeCon Contribfest

**Comment by awanlin** [comment]
Thanks @nikolarAutodesk, I've assigned it to you 🚀

**Comment by nikolarAutodesk** [comment]
Hi @awanlin I am not sure what happened, but my [PR](https://github.com/backstage/backstage/pull/27705) did not automatically request a reviewer. Was there a process change? Do I need to request specific people?

**Comment by nikolarAutodesk** [comment]
closing this issue since the related PR has been merged: https://github.com/backstage/backstage/pull/27705
