### ISSUE TITLE
TechDocs navigation on smaller devices collapses so it's not possible to navigate between pages.

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#2462]
![Screen Shot 2020-09-14 at 3 04 35 PM](https://user-images.githubusercontent.com/25153114/93089563-c5602e00-f69b-11ea-8615-3e32c41f8c9f.png)
![Screen Shot 2020-09-14 at 3 04 48 PM](https://user-images.githubusercontent.com/25153114/93089572-c8f3b500-f69b-11ea-9eb4-6790365d852b.png)

**Comment by mahmoodhosseini** [comment]
@emmaindal, what would be your suggested design for this?

**Comment by emmaindal** [comment]
@mahmoodhosseini I think the theme we are using (mkdocs material) should come with a collapsible "hamburger" menu. The fact that we are using a shadow dom to render the generated static html files could cause this issue. I think we might need to re-think the theme we are using which is kind of blocking this issue right now. @OrkoHunter @hooloovooo or do you have any insights here?

**Comment by OrkoHunter** [comment]
If there is an easy fix to see the nav menu without re-doing the theme, then that would be awesome!

**Comment by OrkoHunter** [comment]
I feel this is hard or messy to accomplish since we remove the header in Reader transformations. And the hamburger menu is part of that header. If we separate the menu out from the header, we need to additionally style it well.

Marking this blocked, and should be fixed by having our own theme.

**Comment by camilaibs** [comment]
Hi guys, I tried to simulate locally in the latest version of Backstage and this behavior no longer exists, as you can see below.
![backstage_docs_mobile_navigation_test](https://user-images.githubusercontent.com/6290749/124892337-11d57b00-dfda-11eb-9d15-a524e17c049c.gif)

So I'll close this issue. Please let us know if you still have the problem after upgrading your backstage instance.

**Comment by OrkoHunter** [comment]
That's definitely a progress @camilaibs ! I noticed that the sidebar disappears if your sidebar is "pinned".

![Screenshot 2021-07-08 at 11 53 25 AM](https://user-images.githubusercontent.com/8065913/124902744-8660e780-dfe3-11eb-960d-4b16298c98d3.png)
