### ISSUE TITLE
🐛 Bug Report: github authenticator signin does not reflect in 'backstage-plugin-github-pull-requests' 

### ISSUE THREAD

**Issue by xyzmurali** [backstage/backstage#24652]
### 📜 Description

We are seeing a similar issue reported in https://github.com/backstage/backstage/issues/20322

Logging in to github authenticator provider does not pass the authentication information to 'backstage-plugin-github-pull-requests' widget

But logging in to github through 'backstage-plugin-github-pull-requests' widget also logs in to github authenticator provider

### 👍 Expected behavior

github authenticator provider should pass the authentication information to 'backstage-plugin-github-pull-requests' widget 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/44962715/4163071d-eafb-4bc1-ab04-7df42f4f75d4)
![image](https://github.com/backstage/backstage/assets/44962715/accae06a-87fc-4b70-ac57-a6ef1b647cfd)

### 👟 Reproduction steps

This issue can be reproduced with below steps.

1. Go to page where Github authenticator sign in present
2. Login to github using Github authenticator
3. Go to page where 'backstage-plugin-github-pull-requests' widget is present (homepage). The github login should happen automatically and results should be displayed. But it asks for github login again on this page with no results displayed in the widget.
4. Go to page where Github authenticator sign in present
5. Log out of gihub
6. Go to page where 'backstage-plugin-github-pull-requests' widget is present.
7. Login to github from 'backstage-plugin-github-pull-requests' widget.
8. Go to page where Github authenticator sign in present. It will show already signed in

### 📃 Provide the context for the Bug.

I see that the fix for "scope: result.session.scope," was made only to one location in file plugins/auth-node/src/oauth/createOAuthRouteHandlers.ts 
but this code "scope: result.session.scope,"is present at two locations. Can this be an issue?

### 🖥️ Your Environment

$ ./node_modules/.bin/backstage-cli info
OS:   Linux 5.14.21-150400.24.100-default - linux/x64
node: v18.18.2
yarn: 1.22.21
cli:  0.25.2 (installed)
backstage:  1.23.4

Dependencies:
  @backstage/app-defaults                                          1.5.4
  @backstage/backend-app-api                                       0.5.14, 0.7.0
  @backstage/backend-common                                        0.20.2, 0.21.7
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.6.17
  @backstage/backend-tasks                                         0.5.22
  @backstage/catalog-client                                        1.6.4
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.14.4
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.31
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.7
  @backstage/frontend-plugin-api                                   0.6.4
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26
  @backstage/integration                                           1.10.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.4.12
  @backstage/plugin-auth-react                                     0.1.0
  @backstage/plugin-catalog-backend-module-github                  0.4.7
  @backstage/plugin-catalog-backend-module-incremental-ingestion   0.4.22
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.11.1
  @backstage/plugin-catalog-react                                  1.11.3
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-backend-module-github                   0.1.23
  @backstage/plugin-events-backend                                 0.2.22
  @backstage/plugin-events-node                                    0.2.22, 0.3.3
  @backstage/plugin-github-actions                                 0.6.16
  @backstage/plugin-home-react                                     0.1.12
  @backstage/plugin-home                                           0.7.3
  @backstage/plugin-jenkins-backend                                0.3.7
  @backstage/plugin-jenkins-common                                 0.1.26
  @backstage/plugin-jenkins                                        0.9.10
  @backstage/plugin-kubernetes-backend                             0.15.3
  @backstage/plugin-kubernetes-common                              0.7.5
  @backstage/plugin-kubernetes-node                                0.1.11
  @backstage/plugin-kubernetes-react                               0.3.4
  @backstage/plugin-kubernetes                                     0.11.9
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.28
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.4
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.22
  @backstage/plugin-search-backend-module-pg                       0.5.26
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-tech-radar                                     0.6.13
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.4
  @backstage/theme                                                 0.5.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
Done in 4.74s.
mkopensuse154: #

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by vinzscam** [comment]
hey, are you using a GitHub OAuth app or a GitHub app?
If you are using a GiHub app the defined scopes are ignored as hey need to be specified directly in the GitHub app

**Comment by xyzmurali** [comment]
Hi, apologies for late reply, we are using GitHub OAuth app

**Comment by Rugvip** [comment]
I believe this should be fixed by #24743, that that fixes refreshing with persisted scopes

**Comment by camilaibs** [comment]
> I believe this should be fixed by #24743, that that fixes refreshing with persisted scopes

@xyzmurali, we are closing this issue for now, but if the unexpected behavior persists after the pull request is released, please do not hesitate to ask us to reopen it. 🙂
