### ISSUE TITLE
🐛 Bug Report: GET locations by entity API call does not work

### ISSUE THREAD

**Issue by lunzmann1120** [backstage/backstage#24660]
### 📜 Description

The GET locations by entity API call referenced [here](https://backstage.io/docs/features/software-catalog/software-catalog-api/#get-locationsby-entitykindnamespacename) is always returning a 404 location not found error, even when we have verified the component exists and the location exists. The exact error we get is "Found no location with type component and target default/zzz-test". 
After further investigation into Backstage's code, we believe the error is coming from `line 148` in `DefaultLocationStore.ts`. It seems it is passing the `entityRefString` to the `parseLocationRef` method when it should be passing the `locationKeyValue`. 

![image](https://github.com/backstage/backstage/assets/81877642/cc71903a-178a-4310-99fe-9272d335558e)

### 👍 Expected behavior

The GET location by entity API call should return the id, type, and target of a Location based on the kind, namespace, and name of an entity.

### 👎 Actual Behavior with Screenshots

404 error even when the data is verified to be correct.

![image](https://github.com/backstage/backstage/assets/81877642/5368b42f-73b7-4940-a567-4f9411ace797)
![image](https://github.com/backstage/backstage/assets/81877642/4af287f2-a5f4-4cfd-b297-8af120188824)

### 👟 Reproduction steps

Make an API call to the catalog using the GET location by entity call: "/locations/by-entity/{kind}/{namespace}/{name}" and see that even when the inputs are correct it only returns a 404 error.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by aramissennyeydd** [comment]
👋 , I think you're right on! Would you be open to submitting a PR to fix this as well as add tests?

**Comment by lunzmann1120** [comment]
Yeah I can do that if you agree that seems to be the issue. I'll get on that and submit it soon.

**Comment by emre** [comment]
any updates on this? I've tried to provide a patch but my limited TS/BS experience kept me back to also provide a valid unit test. :)

**Comment by freben** [comment]
i took a stab at it ^

**Comment by emre** [comment]
< i took a stab at it ^

Thanks!
