### ISSUE TITLE
Question: permissions conditional rules

### ISSUE THREAD

**Issue by WeichengWang1** [backstage/backstage#24705]
### 📜 Description

I wrote a PermissionRule that check a user is authorized to delete an entity.
```ts
...
    apply: (resource: Entity, {permissionAction, permissionName }) => {
        if ({a func check whether the resource can be deleted, return true if can't}) {
            return false;
        }
        return true;
    },
...
```
case1: It works well in the frontpage. The Unregister Entity can not be clicked.
case2: the entity deleted successful when I request an api: /api/catalog/entities/by-uid/{uid}.

I find that the difference between case1 and case2 is the requestBody of api: /api/permission/authorize
resourceRef was missing in case2
case1:
```json
{
    "items":
    [
        {
            "id": "3e98faf5-f1c0-46ae-acb5-8ab492af6dad",
            "permission":
            {
                "type": "resource",
                "name": "catalog.entity.delete",
                "attributes":
                {
                    "action": "delete"
                },
                "resourceType": "catalog-entity"
            },
            "resourceRef": "template:default/demo-temp"
        }
    ]
}
```
case2:
```json
{
    "items":
    [
        {
            "id": "3e98faf5-f1c0-46ae-acb5-8ab492af6dad",
            "permission":
            {
                "type": "resource",
                "name": "catalog.entity.delete",
                "attributes":
                {
                    "action": "delete"
                },
                "resourceType": "catalog-entity"
            }
        }
    ]
}
```

In case2, this.permissionApi.authorizeConditional only passed permission.
```ts
  async removeEntityByUid(
    uid: string,
    options: { credentials: BackstageCredentials },
  ): Promise<void> {
    const authorizeResponse = (
      await this.permissionApi.authorizeConditional(
        [{ permission: catalogEntityDeletePermission }],
        { credentials: options.credentials },
      )
    )[0];
    if (authorizeResponse.result === AuthorizeResult.DENY) {
      throw new NotAllowedError();
    }
    if (authorizeResponse.result === AuthorizeResult.CONDITIONAL) {
      const permissionFilter: EntityFilter = this.transformConditions(
        authorizeResponse.conditions,
      );
      const { entities } = await this.entitiesCatalog.entities({
        credentials: options.credentials,
        filter: {
          allOf: [permissionFilter, basicEntityFilter({ 'metadata.uid': uid })],
        },
      });
      if (entities.length === 0) {
        throw new NotAllowedError();
      }
    }
    return this.entitiesCatalog.removeEntityByUid(uid, {
      credentials: options.credentials,
    });
  }
```
And the resourceRef missed caused different authorizeResponse. In case1, the result is DENY, while CONDITIONAL in case2

### 👍 Expected behavior

removeEntityByUid should check permission correctly
case1 and case2 in Description should both authorized as DENY

### 👎 Actual Behavior with Screenshots

case1 DENY
case2 entity deleted successfully

### 👟 Reproduction steps

write a custom PermissionRule and just return false in 'apply'
call /api/catalog/entities/by-uid/{uid} -X DELETE

### 🖥️ Your Environment

OS:   Darwin 21.6.0 - darwin/arm64
node: v18.12.0
yarn: 1.22.21
cli:  0.26.4 (installed)
backstage:  1.26.3

Dependencies:
  @backstage/app-defaults                                          1.5.4
  @backstage/backend-app-api                                       0.7.0
  @backstage/backend-common                                        0.21.7
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.6.17
  @backstage/backend-tasks                                         0.5.22
  @backstage/backend-test-utils                                    0.3.7
  @backstage/catalog-client                                        1.6.4
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.4
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.14.4
  @backstage/core-plugin-api                                       1.9.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.7
  @backstage/frontend-plugin-api                                   0.6.4
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26
  @backstage/integration                                           1.10.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.4.12
  @backstage/plugin-auth-react                                     0.1.0
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.11.1
  @backstage/plugin-catalog-react                                  1.11.3
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-node                                    0.3.3
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.28
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.4
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.22
  @backstage/plugin-search-backend-module-pg                       0.5.26
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.4
  @backstage/theme                                                 0.5.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
so the flow is correct.
In case 1: the frontend evaluates the permission, which wants to have a definitive decision (ALLOW/DENY). So the frontend wants to evaluate whether a specific entity can be deleted, but of course doesn't have the content of the entity, so it sends the entityRef to the permission backend which will evaluate the permission.

In case 2: the catalog-backend who wants to evaluate whether `catalog.entity.delete` should be granted. But catalog-backend already owns "the data". So it sends a `authorizeConditional` which basically says to the permission framework:
- if the permission is granted or denied please give me back the result (straight ALLOW/DENY).
- if the permission is conditionally allowed, please DON'T try to resolve it. Just give me back all the rules and I will handle it.
  Now that catalog-backend has the conditional result back, it passes the result to the `transformConditions` function which translate the conditional result to a database query that the catalog's database understand (by calling the `toQuery` method of your rule, not the apply method), which is then passed down to the database which filters out the entity in case the user shouldn't have access to.
  
  This is the way catalog works, but other plugins might behave differently. For example, scaffolder when authorizing actions, it first retrieves the data (the action itself) and then [applies the conditional results directly to the data](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts#L352) (via the `apply` method of the rules). 
  
  Now, let's imagine that instead of calling `.authorizeConditional()`, catalog-backend will call `.authorize()`. The authorize method returns ALLOW/DENY. This means that the permission-backend needs to reach out back to catalog in order to resolve any conditional decision, which is overkill and it is the reason why `.authorizeConditional()` exists.
  
I hope this helped you understanding more the flow. If you have more questions regarding this you are welcome to the `#permissions` channel on Discord 😄

**Comment by WeichengWang1** [comment]
> * This is the way catalog works

@vinzscam Got it! Thank you for your kindly reply.
