### ISSUE TITLE
🚀 Feature: new frontend system legacy plugin converter

### ISSUE THREAD

**Issue by marleypowell** [backstage/backstage#24707]
### 🔖 Feature description

The [@backstage/core-compat-api](https://github.com/backstage/backstage/tree/master/packages/core-compat-api) package seems to exist to provide compatibility for the new frontend system. It seems like the bridge for existing plugins is missing. This may have been intentional but it seems possible?

### 🎤 Context

This would allow existing plugins to be used with the new frontend system.

### ✌️ Possible Implementation

```ts
function convertLegacyPlugin(plugin: BackstagePlugin) {
  return createPlugin({
    id: plugin.getId(),
    extensions: Array.from(plugin.getApis()).map(factory =>
      createApiExtension({
        factory,
      }),
    ),
    routes: convertLegacyRouteRefs(plugin.routes),
    externalRoutes: convertLegacyRouteRefs(plugin.externalRoutes),
    featureFlags: Array.from(plugin.getFeatureFlags()),
  });
}
```

```ts
const app = createApp({
  features: [
    ...legacyFeatures,
    convertLegacyPlugin(catalogUnprocessedEntitiesPlugin)
  ],
});
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Yep we'll likely look at adding this! 👍 

The tricky bit are the extensions being provided through `plugin.provide(...)` in the old system, and how to handle those.

**Comment by Rugvip** [comment]
Initial implementation of this in #26057, appreciate feedback on that approach

**Comment by Rugvip** [comment]
Closing this for now as we don't have any planned work in this area at the moment, but still open to feedback.
