### ISSUE TITLE
🐛 Bug Report: <Kubernetes Plugin rendering issue>

### ISSUE THREAD

**Issue by nia-potato** [backstage/backstage#24714]
### 📜 Description

sizing issue of text will squeeze the content in the kubernetes plugin to non-readable text. 

### 👍 Expected behavior

either have it rendered as a list or maybe tweak the sizing issue. 

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-05-09 at 12 50 21](https://github.com/backstage/backstage/assets/117061613/1d900d3e-0ff7-421e-9fef-4a348a1f9406)

### 👟 Reproduction steps

use the latest kubernetes plugin

### 📃 Provide the context for the Bug.

I am open on trying to experiment with ways to better represent cluster information perhaps changing the layout a bit. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by nia-potato** [comment]
cc: @ahhhndre

**Comment by awanlin** [comment]
Thanks @nia-potato 👍

**Comment by WesleyJammer** [comment]
Hey i am a student that is experiencing the world of open source for the first time. I like to contribute to this issue, and if i am correct the kubernetes plugin doesnt make the text readable for the consumer. If i am wrong or if there is more information i need to know about, i really like to hear on what you have to say. i am looking forward to contributing to this project and i want to wish you a verry nice day.

**Comment by Rugvip** [comment]
@nia-potato did a quick glance in the local dev setup for the k8s plugin but could find these components. What part of the plugin is it that you're seeing this in?

@WesleyJammer what we likely need is a slight tweak to how we lay out the cards on the page. Although to avoid having to run a Kubernetes cluster locally for testing it might also need a new dev setup in https://github.com/backstage/backstage/blob/95518765ee6b5382357ca3cb1f177a1015fcc10d/plugins/kubernetes/dev/index.tsx#L136

**Comment by WesleyJammer** [comment]
@Rugvip I must say that creating a new dev setup is to complicated for me at the moment, because that is in a later stage in my study. my question is if there is a other solution to fix this issue or that you may have a issue that suits me more and doesnt need a new dev setup.

**Comment by nia-potato** [comment]
@Rugvip it was just a kubernetes plugin view of a cluster that had a a few services, the one i screenshot contained the grafana service if that is what you are asking about. if i find a vertical screen and see the layout there, you can see i have around 8 services, and that isnt actually alot of services for a individual cluster, so i think the layout would be the problem here when handling more services per cluster. 

i am just thinking out loud here but: 

perhaps a list view of kubernetes resources that can be potentially be alot in a view, such as (namespaces, services, then clicking each individual row in that list expands a horizontal layout would solve this issue?  instead of the current layout of cards? 


![Screenshot 2024-05-17 at 15 46 52](https://github.com/backstage/backstage/assets/117061613/6f7722e7-7eb7-44ee-a658-bd7047f460cf)

**Comment by Rugvip** [comment]
@mclarke47 wanna double check if you have any opinions here 😁

**Comment by mclarke47** [comment]
It would be ideal if we could capture this feedback into https://github.com/backstage/backstage/issues/18648

**Comment by icdemo** [comment]
I think after the deployments portion, the ingress and the services breaks. 

It looks like it is expected to only have one services, when multiple services are present the rendering breaks. It it has the same layout as the deployment, then it won't have this problem.

<img width="1125" alt="backstage-k8-view" src="https://github.com/user-attachments/assets/817e42ed-5247-40be-bb63-cf34736cb820">

**Comment by mclarke47** [comment]
@icdemo can you open a new issue?
