### ISSUE TITLE
🚀 Feature: Ability to enrich entities created from ingestion of org data

### ISSUE THREAD

**Issue by mprinold** [backstage/backstage#24710]
### 🔖 Feature description

When you use a provider to ingest org data, then entities are created for users and groups. As these entities aren't linked to yaml files there is currently no means to be able to enrich the data on these entities.

### 🎤 Context

As an example if i have a group entity it might be nice to be able to add the tech docs annotation to it so that i can reference a doc that describes the group. 

### ✌️ Possible Implementation

Possible None GUI approach: be able to define a yaml file for a group or user that extends the existing entity created by the org provider 
Possible GUI approach, edit button on group or user entities that takes you to a page to extend the existing entity. This would need to be configurable to utilise permissions.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
Yep definitely something we want to add better support for in the catalog! 👍
No plans right now to work on this right now in the maintainer team though.

There's a similar request here: https://github.com/backstage/backstage/issues/16155
And a related implementation here: https://roadie.io/docs/catalog/decorating-components/

Also added this to #14574

**Comment by wanisfahmyDE** [comment]
would be very useful to have this.
