### ISSUE TITLE
🚀 Feature: Documentation Request: Update guide "Writing Custom Actions" showing how to leverage Backstage CLI

### ISSUE THREAD

**Issue by Al-Serhan** [backstage/backstage#24719]
### 🔖 Feature description

I would like to request updating the documentations on "Writing Custom Actions" by adding a step showing how to use the Backstage CLI to create a scaffolder custom action

### 🎤 Context

The documentation in this [page describing how to write custom actions](https://backstage.io/docs/features/software-templates/writing-custom-actions/) goes over the code breakdown in low level detail but doesn't actually take advantage of the CLI to show how you can create a scaffolder custom action. Adding this information to this doc will make the experience of on-boarding a lot easier.

### ✌️ Possible Implementation

The documentation should include:

- A step-by-step guide on how to create a custom action using backstage cli.
- Screenshots or GIFs demonstrating the process.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @Al-Serhan, this makes sense to me. Just so I'm on the same page you mean adding details about running `yarn new` to create the package with things nicely setup for you, right?

I might avoid screenshots unless you think they are really needed, I find they can create a disjointed experience - they don't match, take up a lot of space, and don't get updated easily over time. Open to see what you have in mind though. 👍

**Comment by awanlin** [comment]
OK, great, I think this is a great idea. These docs dive right into the deep end so would appreciate you adding some of the steps before you get to that point 🚀 

Feel free to tag me on you PR to help review 👍 

Issue assigned 😄

**Comment by benjdlambert** [comment]
Just following up from the SIG here, that we got a report on discord that we should probably add support to the `yarn new` for scaffolder actions for the new backend system and exporting a `backendModule` too if that's possible :pray:

**Comment by Al-Serhan** [comment]
Hi @benjdlambert , since this would be an added code change, would it make sense to have it in an another seperate issue?

I tried to find the report on discord but I can't see it mentioned anywhere, maybe we can discuss in the SIG meeting.

**Comment by benjdlambert** [comment]
@Al-Serhan yeah, maybe another issue makes more sense - thought that this was the most relevant but I think you're right.
