### ISSUE TITLE
🐛 Bug Report: Event based GitHub Discovery is not working in latest version of backstage

### ISSUE THREAD

**Issue by jiyo86** [backstage/backstage#24734]
### 📜 Description

In backstage backend new approach & legacy this.events.publish() is not updating or creating entity in Backstage catalog. Currently github provider is only updating the info in database and that create the rate limit error. As per the documentation we can enable GITHUB Webhooks and backstage events based on events-backend-module-github we can achieve the catalog entity creation & updation but in V 26.0 it is not working as expected

### 👍 Expected behavior

New entity should be created in catalog listing using github webhooks using events-backend-module-github, by this endpoint /api/events/http/github

### 👎 Actual Behavior with Screenshots

NA

### 👟 Reproduction steps

configure /api/events/http/github in github wekhooks for push event and configure **events-backend-module-github,** and other dependency using **https://backstage.io/docs/integrations/github/discovery/** create new push to main branch in githuib to trigger the webhooks.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
have you also specified

```yaml
events:
  http:
    topics:
      - github
```      

in your app-config? 🤔 
BTW there are a bunch of related fixes coming out tomorrow with `1.27`, could you also try with `1.27` once is out?

**Comment by jiyo86** [comment]
I have added below code in my app-config. I will upgrade the version tomorrow and check again
events:
  http:
    topics:
      - github
