### ISSUE TITLE
🚀 Feature: Plugin Api-Docs Request Samples

### ISSUE THREAD

**Issue by BryanJaramilloAE** [backstage/backstage#24733]
### 🔖 Feature description

Hi, I've been using the api-doc plugin these days and I thought it would be great if it would show examples of endpoint requests, for example in curl, Nodejs or Python.

Something like this:

``` sh
curl --request POST \
  --url https://petstore.swagger.io/v2/pet/petId/uploadImage \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer 123' \
  --header 'Content-Type: multipart/form-data' \
  --form additionalMetadata= \
  --form file=
```

### 🎤 Context

This would be really usefull for users to quickly test the endpoind.

This is an exaple from Spotlight: https://elements-demo.stoplight.io/?spec=https%3A%2F%2Fpetstore.swagger.io%2Fv2%2Fswagger.json#/operations/uploadFile

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
thanks for the suggestion. Yes, it would be a nice addition
