### ISSUE TITLE
🐛 Bug Report: The issue of AWS Code Commit integration

### ISSUE THREAD

**Issue by Kang3498** [backstage/backstage#24763]
### 📜 Description

First of all, thank you so much for creating the AWS Codecommit Integration feature. 

I tried this feature as soon as it was released and I found one problem.

In the link below, config.host is forced to console.aws.amazon.com, so, If I set repoContentsUrl to {region}.console.aws.amazon.com in the catalog:register action, No Integration error occurs.
https://github.com/stijnbrouwers/backstage/blob/master/packages/integration/src/awsCodeCommit/config.ts#L67

Instead, if I remove the region from the url, an error occurs due to the link below.
https://github.com/stijnbrouwers/backstage/blob/master/packages/backend-common/src/reading/AwsCodeCommitUrlReader.ts#L70

I think it should be changed to load the host from config instead of forcefully assigning it in the first link.

### 👍 Expected behavior

I think the steps below should succeed.  

      input:
        catalogInfoPath: .backstage/catalog-info.yaml
        repoContentsUrl: https://ap-northeast-2.console.aws.amazon.com/codesuite/codecommit/repositories/test-repo/browse/--/

### 👎 Actual Behavior with Screenshots

InputError: No integration found for host https://ap-northeast-2.console.aws.amazon.com/codesuite/codecommit/repositories/test-repo/browse/refs/heads/main/--/catalog-info.yaml

### 👟 Reproduction steps

1. make simple template
2. add Register step like below
    - id: register
      name: Register2
      action: catalog:register
      input:
        catalogInfoPath: .backstage/catalog-info.yaml
        repoContentsUrl: https://ap-northeast-2.console.aws.amazon.com/codesuite/codecommit/repositories/test-repo/browse/--/

### 🖥️ Your Environment

backstage : v1.26.5

@backstage/backend-common: 0.21.6
@backstage/integration: 1.10.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Kang3498** [comment]
I created a PR that can be modified. (https://github.com/backstage/backstage/pull/24771)

**Comment by stijnbrouwers** [comment]
I think this issue can be closed due to #24843 ...
