### ISSUE TITLE
🐛 Bug Report: Support of an external config schema in the `app-backend` router is broken

### ISSUE THREAD

**Issue by davidfestal** [backstage/backstage#24778]
### 📜 Description

The support of an external config schema in the `app-backend` router is broken.

The external schema optionally passed to the router in the `createRouter()` method is not used anymore.
That means that all config values defined as frontend config values in an external schema will be ignored when filtering the config for the frontend.

**_This is a critical regression that breaks the dynamic plugins feature._**

### 👍 Expected behavior

When explicitly passing an external schema to the router, it should be taken in account when building the frontend configuration.

### 👎 Actual Behavior with Screenshots

When explicitly passing an external schema to the router, it is **not** taken in account when building the frontend configuration. It was in release `1.24.3`.

### 👟 Reproduction steps

1. Create a backend application that calls the `app-backend` `createRouter()` method  with an external schema that contains a specific frontend config value
2. Add this specific config value in your `app-config.local.yaml`
3. Build the frontend app to generate static assets
4. Run `yarn start-backend`
5. Point to the frontend in the browser and look into the injected configuration through the browser development tooling
6. Notice that the specific frontend config value has been filtered out, because the schema containing its definition has not been used.

### 📃 Provide the context for the Bug.

The external schema support in the `app-backend` plugin is used by the dynamic plugins feature, so that when a dynamic plugins loaded at application start, its schema is also taken in account.

**_This is why this bug is a critical regression that breaks the dynamic plugins feature._**

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Fixed!
