### ISSUE TITLE
🚀 Feature: Home Page Recently Visited component for entities with subpages 

### ISSUE THREAD

**Issue by pativa** [backstage/backstage#24819]
### 🔖 Feature description

`HomePageRecentlyVisited` is a nice component displaying the last few visited pages. However, we have multiple subpages for most component pages, and we would like to be able to count these as visits to the same page, or not count some pages as visits at all.

Example screenshot:
![recently-visited-duplicates](https://github.com/backstage/backstage/assets/83230533/367cd3be-d674-4b9b-b361-3e28509b4cbe)

These are links to different subpages on the same entity.

### 🎤 Context

As it is now, this component is not very useful for us as it is filled with duplicates for everyone (duplicates in the meaning that they point to the same entity, but different subpages).

### ✌️ Possible Implementation

I would suggest to add a method for transforming the `pathname` in [VisitListener](https://github.com/backstage/backstage/blob/master/plugins/home/src/components/VisitListener.tsx#L82) so that we can control which paths are registered to `VisitsApi`.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@backstage/home-maintainers
