### ISSUE TITLE
Support differing expiry of identity vs authorization OAuth tokens

### ISSUE THREAD

**Issue by acierto** [backstage/backstage#24815]
### 🔖 Need

Current issue:

If to open Backstage in 2 different tabs and perform `ScmAuthApi.getCredentials` in each tab, the token on tab 1 will be revoked. The problem lies that the session lives only in memory and the session manager doesn't reuse it. 

It's not unique when users can open Backstage in multiple tabs or in different browsers, in order to perform different scenarios in each browser session. 

### 🎉 Proposal

The proposal is to store the OAuth session in the database, for example in `backstage_plugin_auth` database in a new table `oauth_session` or something like this.

### ❌ Risks

Such tokens are short lived, i.e. GitLab token can be valid maximum for 2 hours.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
Which provider is it that you're seeing this for? The token being revoked is something that shouldn't happen regardless of whether we have backend storage or not. Agree that that would be a good addition though 👍 

There are some potential fixes for this on the way in #24743 too, I spotted some bugs for the refresh endpoint of some providers as part of that refactor.

**Comment by acierto** [comment]
I see it for GitLab provider.
I could reproduce it by opening 2 different scaffolder templates in separate tabs, where both require to get an access token

**Comment by dariozachow** [comment]
We are using the ID Token from GitLab to request some third party API and calling the `gitlabAuthApi.getIdToken()` everytime before the requests is made. The ID Token is valid just for 2mins thus every request after that time will fail. This makes it very annoying for the user as he must reload the page to get a new login window to get a fresh token. Background refreshing of the Token would be very helpful 🙏

**Comment by freben** [comment]
It's not technically possible to do it in background. And besides, even if it were possible, as reported at the top, that might even more aggressively revoke other ongoing token flows causing problems elsewhere right?

It sounds to me like this is a serious limitation in how gitlab does token handling in general. Any pointers or assistance in making this better is appreciated 🙏

**Comment by floric** [comment]
Thanks for your research. We decided to a Yarn patch as a hotfix like this:
```
// temporary fix for ID token expiration after 2 minutes, so refresh after 90 seconds instead of 120 minutes
if (provider.id === "gitlab") {
    return ((session.providerInfo.expiresAt.getTime() - Date.now()) / 1e3) < 7110;
}
```

Of course this is pretty hacky in `apis/implementations/auth/oauth2/OAuth2.ts` but solves the for us urgent issue for now. To be honest, I personally also think it should be fixed on the Gitlab side but there is an [open issue](https://gitlab.com/gitlab-org/gitlab/-/issues/377654) for one year now. Maybe we can really consider this as a workaround hotfix, maybe with a feature flag?

**Comment by camilaibs** [comment]
> session.providerInfo.expiresAt.getTime()

It appears that there is an intention of having separate provider checks in the `sessionShouldRefresh` function as mentioned by @Rugvip in this comment:
https://github.com/backstage/backstage/blob/78c9adcc61bc333aaa679e4d4f5b636e035a6dc2/packages/core-app-api/src/apis/implementations/auth/oauth2/OAuth2.ts#L137

I'm adding a `needs-discussion` label to hear from the team their recommendation.

**Comment by camilaibs** [comment]
Hi there, in conversation with @Rugvip, our initial recommendation would be adding a logic in the frontend that checks the expiration if the token is JWT token. Let us know if you have follow-up questions 🙂
