### ISSUE TITLE
🐛 Bug Report: scaffolder 'fetch' action not working for AWS CodeCommit

### ISSUE THREAD

**Issue by stijnbrouwers** [backstage/backstage#24824]
### 📜 Description

When using the 'fetch' step/action when a template is hosted on AWS Code Commit. You will receive an error stating that "no integration found for location ...".

### 👍 Expected behavior

I would expect the template to be able to fetch the data from CodeCommit

### 👎 Actual Behavior with Screenshots

![Screenshot_20240517_164846](https://github.com/backstage/backstage/assets/9864443/52004659-1214-478b-aff3-b1cdca86e955)

### 👟 Reproduction steps

- Create a template on AWS CodeCommit with a "Fetch" step/action
- Create a new component based on the template

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by stijnbrouwers** [comment]
I am working on a PR for this...

**Comment by Kang3498** [comment]
I think this is same issue with https://github.com/backstage/backstage/pull/24771.

**Comment by stijnbrouwers** [comment]
@Kang3498, you are right, it's the exact same issue.
Thank you for pointing this out to me!
I had a similar fix
