### ISSUE TITLE
🚀 Feature: Gitlab CI/CD pipelines

### ISSUE THREAD

**Issue by leoandrea7** [backstage/backstage#24823]
### 🔖 Feature description

Scaffolder-backend-module-gitlab miss action to trigger a Gitlab CI/CD pipeline.

### 🎤 Context

For Github scaffolder module there is an action to trigger GithubActions. There should be a similiar action in the gitlab scaffolder module to trigger a pipeline in Gitlab.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by elaine-mattos** [comment]
Hi! I have just started working on it: https://github.com/backstage/backstage/pull/24894
