### ISSUE TITLE
REST API documentation consistency improvements

### ISSUE THREAD

**Issue by alexvuka1** [backstage/backstage#24829]
### 📜 Description

I have identified the following possible instances of inconsistencies between [Open API specification](https://github.com/backstage/backstage/blob/2c3f493ee32d67d3a300d13e73e352f91145a3ee/plugins/catalog-backend/src/schema/openapi.yaml) and [Documentation](https://github.com/backstage/backstage/blob/2c3f493ee32d67d3a300d13e73e352f91145a3ee/docs/features/software-catalog/api.md):

- ### 🟩Found in Open API specification, 🟥Not found in Documentation
	- [ ] [`POST /refresh`](https://github.com/backstage/backstage/blob/2c3f493ee32d67d3a300d13e73e352f91145a3ee/plugins/catalog-backend/src/schema/openapi.yaml)
	- [ ] [`GET /entities/by-name/{kind}/{namespace}/{name}/ancestry`](https://github.com/backstage/backstage/blob/2c3f493ee32d67d3a300d13e73e352f91145a3ee/plugins/catalog-backend/src/schema/openapi.yaml)
	- [ ] [`GET /entity-facets`](https://github.com/backstage/backstage/blob/2c3f493ee32d67d3a300d13e73e352f91145a3ee/plugins/catalog-backend/src/schema/openapi.yaml)
	- [ ] [`POST /analyze-location`](https://github.com/backstage/backstage/blob/2c3f493ee32d67d3a300d13e73e352f91145a3ee/plugins/catalog-backend/src/schema/openapi.yaml)
	- [ ] [`POST /validate-entity`](https://github.com/backstage/backstage/blob/2c3f493ee32d67d3a300d13e73e352f91145a3ee/plugins/catalog-backend/src/schema/openapi.yaml)

- ### 🟩Found in Open API specification, 🟩Found in Documentation, 🟥Have Inconsistencies
	- | Inconsistency type | Open API specification <br /> [`DELETE /locations/{id}`](https://github.com/backstage/backstage/blob/2c3f493ee32d67d3a300d13e73e352f91145a3ee/plugins/catalog-backend/src/schema/openapi.yaml) | Documentation <br /> [`DELETE /locations/<uid>`](https://github.com/backstage/backstage/blob/2c3f493ee32d67d3a300d13e73e352f91145a3ee/docs/features/software-catalog/api.md?plain=1#L545) |
		| --- | --- | --- |
		| Path parameter name mismatch | `id` | `uid` |

**About**

This is part of the evaluation of my Master's Project at Imperial College London. The section above is automatically generated and aims to expose API documentation inconsistencies in real-world GitHub repositories. The end goal is for the tool to be used as part of CI/CD, namely as a GitHub action. 

Hopefully, this is a step towards easier maintenance of API documentation. If you find this helpful, please consider updating the documentation to keep it in sync with the source code. I am also happy to assist with it, if appropriate. If this has not been useful, consider updating this issue with an explanation, so I can improve my approach. Thank you!
    

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Thank you! 👍 

It would be useful to have links to the outdated documentation as well, since that might not be immediately clear

**Comment by alexvuka1** [comment]
I have updated the formatting of the description to make it more readable. The provided links should work properly, but if you would like them to be improved, please let me know. In case you have further feedback, it would be greatly appreciated. Thanks!

**Comment by ismailmmd** [comment]
@Rugvip I created https://github.com/backstage/backstage/pull/24999 to resolve this.

**Comment by ismailmmd** [comment]
@freben I think this can be closed
