### ISSUE TITLE
🚀 Feature: Use upsert to index documents to elasticsearch

### ISSUE THREAD

**Issue by zcmander** [backstage/backstage#24832]
### 🔖 Feature description

ElasticSearch search engine could be more efficient and less resource intensive by using upsert for updating and inserting documents. To make it work with deleted documents, it could be achieved by the following steps:

 * Send all documents to elastic search while booking sent document ids using upsert functionality
   * docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#doc_as_upsert 
 * Send a delete by query request to delete all documents that are not known.
   * docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html

### 🎤 Context

Current architecture is quite robust as it does the following:

 * Create a new index for documents
 * Upload all documents to the index
 * Switch alias to point to the new index
 * Remove old (stale) aliases

The way it works requires a lot of disk space: roughly 2x active index size. And more than that: it eats a lot of CPU and memory to even process all incoming data and that data does not really change that often (probably).

In an imaginary example, some organisation could include their whole confluence site using confluence plugin: https://github.com/K-Phoen/backstage-plugin-confluence

That could mean that confluence index has millions of pages that takes a lot of disk space cpu, time to process for "nothing" (only small portion of pages are actually changed between collator runs).

### ✌️ Possible Implementation

I was thinking a fork of the existing elastic search plugin: https://github.com/backstage/backstage/tree/master/plugins/search-backend-module-elasticsearch

And modify that to make use of `doc_as_upsert` and work top on that.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by zcmander** [comment]
Area should be search, i suppose?

**Comment by Rugvip** [comment]
@zcmander discoverability is fine, search is part of that. Will leave it to @backstage/discoverability-maintainers to comment on the way forward here and whether it's something we want to add

**Comment by benjdlambert** [comment]
@backstage/search-maintainers
