### ISSUE TITLE
🐛 Bug Report: Plugin Api-Docs not rendering schemas and example value for requests

### ISSUE THREAD

**Issue by manusant** [backstage/backstage#24845]
### 📜 Description

Current version of Swagger UI embedded into the api-docs plugin is not rendering request or response schemas/sample objects.
Additionally, if we use the official https://editor.swagger.io/ everything is properly rendered for the same OpenAPI definition. 

### 👍 Expected behavior

The OpenAPI definition should be rendered properly (It should do the same as in the Swagger Editor UI)

![faf0e4ba-ee28-4853-a301-8b7ecd3f6f17](https://github.com/backstage/backstage/assets/12997676/142c43b3-acf7-415e-9e08-c283a33c0cc0)

### 👎 Actual Behavior with Screenshots

Currently it's not rendering request and response schemas and example objects.

<img width="1074" alt="Screenshot 2024-05-21 at 11 46 44" src="https://github.com/backstage/backstage/assets/12997676/b75a2892-16a9-4518-8068-c868ad6a4f58">

### 👟 Reproduction steps

1. Pick a sample OpenAPI deffiniton with schemas for request and responses: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore-expanded.yaml
2. Open it with swagger UI editor: https://editor.swagger.io/ and confirm that both request and responses have sample objects and respective schema rendered:
<img width="851" alt="Screenshot 2024-05-21 at 11 51 44" src="https://github.com/backstage/backstage/assets/12997676/02b09ecf-533d-4802-ae10-b450caad7136">
3. Now publish the sample API to backstage and you will see that the backstage swagger ui is ignoring these schema definitions.

### 📃 Provide the context for the Bug.

basically it affects rendering off any OpenAPI specification.

### 🖥️ Your Environment

OS:   Darwin 23.4.0 - darwin/arm64
node: v20.11.1
yarn: 4.1.0
cli:  0.25.2 (installed)
backstage:  1.23.3

Dependencies:
  @backstage/app-defaults                                          1.5.0
  @backstage/backend-app-api                                       0.5.13
  @backstage/backend-common                                        0.21.2
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.5
  @backstage/backend-plugin-api                                    0.6.12
  @backstage/backend-tasks                                         0.5.17
  @backstage/backend-test-utils                                    0.3.2
  @backstage/catalog-client                                        1.6.0
  @backstage/catalog-model                                         1.4.4
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.3
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.6.2
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.12.0
  @backstage/core-compat-api                                       0.2.0
  @backstage/core-components                                       0.13.10, 0.14.0
  @backstage/core-plugin-api                                       1.9.0
  @backstage/dev-utils                                             1.0.27
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.5
  @backstage/frontend-plugin-api                                   0.6.0
  @backstage/integration-aws-node                                  0.1.9
  @backstage/integration-react                                     1.1.24
  @backstage/integration                                           1.9.0
  @backstage/plugin-api-docs                                       0.11.0
  @backstage/plugin-app-backend                                    0.3.60
  @backstage/plugin-app-node                                       0.1.12
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.4
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.7
  @backstage/plugin-auth-backend-module-github-provider            0.1.9
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.9
  @backstage/plugin-auth-backend-module-google-provider            0.1.9
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.7
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.9
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.5
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.2
  @backstage/plugin-auth-backend-module-okta-provider              0.0.5
  @backstage/plugin-auth-backend                                   0.21.2
  @backstage/plugin-auth-node                                      0.4.7
  @backstage/plugin-badges-backend                                 0.3.9
  @backstage/plugin-badges                                         0.2.54
  @backstage/plugin-bazaar-backend                                 0.3.10
  @backstage/plugin-bazaar                                         0.2.22
  @backstage/plugin-catalog-backend-module-github                  0.5.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.9
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.9
  @backstage/plugin-catalog-backend                                1.17.2
  @backstage/plugin-catalog-common                                 1.0.21
  @backstage/plugin-catalog-graph                                  0.4.0
  @backstage/plugin-catalog-import                                 0.10.6
  @backstage/plugin-catalog-node                                   1.7.2
  @backstage/plugin-catalog-react                                  1.10.0
  @backstage/plugin-catalog-unprocessed-entities                   0.1.8
  @backstage/plugin-catalog                                        1.17.0
  @backstage/plugin-code-coverage                                  0.2.23
  @backstage/plugin-devtools-backend                               0.2.9
  @backstage/plugin-devtools-common                                0.1.8
  @backstage/plugin-devtools                                       0.1.9
  @backstage/plugin-entity-feedback-backend                        0.2.9
  @backstage/plugin-entity-feedback-common                         0.1.3
  @backstage/plugin-entity-feedback                                0.2.13
  @backstage/plugin-entity-validation                              0.1.15
  @backstage/plugin-events-node                                    0.2.21
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.36
  @backstage/plugin-explore                                        0.4.16
  @backstage/plugin-github-actions                                 0.6.11
  @backstage/plugin-github-deployments                             0.1.61
  @backstage/plugin-github-pull-requests-board                     0.1.24
  @backstage/plugin-graphiql                                       0.3.3
  @backstage/plugin-home-react                                     0.1.8
  @backstage/plugin-jenkins-backend                                0.3.6
  @backstage/plugin-jenkins-common                                 0.1.24
  @backstage/plugin-jenkins                                        0.9.5
  @backstage/plugin-kafka                                          0.3.30
  @backstage/plugin-lighthouse-common                              0.1.4
  @backstage/plugin-lighthouse                                     0.4.15
  @backstage/plugin-org                                            0.6.20
  @backstage/plugin-permission-backend                             0.5.35
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.23
  @backstage/plugin-permission-react                               0.4.20
  @backstage/plugin-playlist-backend                               0.3.16
  @backstage/plugin-playlist-common                                0.1.14
  @backstage/plugin-proxy-backend                                  0.4.10
  @backstage/plugin-scaffolder-backend-module-azure                0.1.4
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.2
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.2
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.2
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.4
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.2
  @backstage/plugin-scaffolder-backend-module-github               0.2.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.15
  @backstage/plugin-scaffolder-backend                             1.21.2
  @backstage/plugin-scaffolder-common                              1.5.0
  @backstage/plugin-scaffolder-node                                0.3.2
  @backstage/plugin-scaffolder-react                               1.8.0
  @backstage/plugin-scaffolder                                     1.18.0
  @backstage/plugin-search-backend-module-catalog                  0.1.16
  @backstage/plugin-search-backend-module-elasticsearch            1.3.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.16
  @backstage/plugin-search-backend-node                            1.2.16
  @backstage/plugin-search-backend                                 1.5.2
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.6
  @backstage/plugin-search                                         1.4.6
  @backstage/plugin-shortcuts                                      0.3.19
  @backstage/plugin-sonarqube-backend                              0.2.14
  @backstage/plugin-sonarqube-react                                0.1.13
  @backstage/plugin-sonarqube                                      0.7.12
  @backstage/plugin-tech-radar                                     0.6.13
  @backstage/plugin-techdocs-backend                               1.9.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.5
  @backstage/plugin-techdocs-node                                  1.11.4
  @backstage/plugin-techdocs-react                                 1.1.16
  @backstage/plugin-techdocs                                       1.10.0
  @backstage/plugin-user-settings                                  0.8.1
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.6.2
  @backstage/test-utils                                            1.5.0
  @backstage/theme                                                 0.4.4, 0.5.1
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
OK. Opening up for contributions to update this! I seem to remember that updating that dependency was a bit tricky, but happy for any help.
