### ISSUE TITLE
🐛 Bug Report: githuborgentityprovider circular reference

### ISSUE THREAD

**Issue by joebowbeer** [backstage/backstage#24842]
### 📜 Description

Visit [GitHubOrgEntityProvider](https://backstage.io/docs/reference/plugin-catalog-backend-module-github.githuborgentityprovider) (note `H` in GitHub)

and click on the link to [GithubOrgEntityProvider](https://backstage.io/docs/reference/plugin-catalog-backend-module-github.githuborgentityprovider)

Repeat.

---
GitHubOrgEntityProvider
[Home](https://backstage.io/docs/reference/) > [@backstage/plugin-catalog-backend-module-github](https://backstage.io/docs/reference/plugin-catalog-backend-module-github) > [GitHubOrgEntityProvider](https://backstage.io/docs/reference/plugin-catalog-backend-module-github.githuborgentityprovider)

Warning: This API is now obsolete.

Use [GithubOrgEntityProvider](https://backstage.io/docs/reference/plugin-catalog-backend-module-github.githuborgentityprovider) instead.
---

### 👍 Expected behavior

Navigates to documentation for GithubOrgEntityProvider

### 👎 Actual Behavior with Screenshots

The old version and new version share the same URL, and the old version won.

### 👟 Reproduction steps

See description.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
This is a docusaurus thing. It just lowercases things like that. We should probably just entirely remove the old one.

**Comment by benjdlambert** [comment]
Closing as I think that this has been fixed now as we removed the legacy code instead.
