### ISSUE TITLE
🐛 Bug Report: Scaffolder Action "debug:wait" does not accept more than 30s waiting time

### ISSUE THREAD

**Issue by jomeier** [backstage/backstage#24846]
### 📜 Description

Hi,
debug:wait throws an error if set to more than 30s waiting time:

```
Error: Waiting duration is longer than the maximum threshold of 0 hours, 0 minutes, 30 seconds[25](http://127.0.0.1:3000/create/tasks/826df128-0309-4773-b675-88ea14b49163#line-25)    at Object.handler (/home/m/backstage-refactor/backstage/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/actions/builtin/debug/wait.ts:79:15)[26](http://127.0.0.1:3000/create/tasks/826df128-0309-4773-b675-88ea14b49163#line-26)    at NunjucksWorkflowRunner.executeStep (/home/m/backstage-refactor/backstage/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:380:22)[27](http://127.0.0.1:3000/create/tasks/826df128-0309-4773-b675-88ea14b49163#line-27)    at NunjucksWorkflowRunner.execute (/home/m/backstage-refactor/backstage/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:507:9)[28](http://127.0.0.1:3000/create/tasks/826df128-0309-4773-b675-88ea14b49163#line-28)    at TaskWorker.runOneTask (/home/m/backstage-refactor/backstage/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:176:26)
```

### 👍 Expected behavior

debug:wait should wait as long as its configured for.

### 👎 Actual Behavior with Screenshots

Scaffolder throws an error.

### 👟 Reproduction steps

```
- name: debug wait
  action: debug:wait  
  input:
    minutes: 5
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
This was a deliberate limitation just to set "something" - it's really not meant to be blocking for very long times, note its `debug` naming. It holds up workers unnecessarily.

If there's a business need to actually block for the completion of something or similar, you may want to make a custom action that knows how to wait the right amount of time or block on the right type of external condition, rather than using the debug action.

**Comment by acierto** [comment]
Hey @jomeier 👋 

Are you using this feature for debug but 30 seconds is pretty strict for you? Or what is your use case here?

**Comment by jomeier** [comment]
Hi,
yes I need this feature to debug complex templating scenarios.
Greetings,
Josef

**Comment by acierto** [comment]
Hi @jomeier, 
make sense.

Raised PR https://github.com/backstage/backstage/pull/25109 to increase max debug:wait to 10 minutes. 
If for example it won't be enough, few actions could be added.

With 30 seconds limits it would require really a lot of actions 😅

**Comment by jomeier** [comment]
@acierto:
Great! Thanks a lot!
