### ISSUE TITLE
🐛 Bug Report: Okta 'additionalScopes' not reflected during auth

### ISSUE THREAD

**Issue by sana-malik** [backstage/backstage#24875]
### 📜 Description

When adding additional scopes for Okta authentication as described in the [docs](https://backstage.io/docs/auth/okta/provider/#configuration), the configured scopes don't get reflected in the sign-in flow. 

### 👍 Expected behavior

Adding the `additionalScopes` parameter will send the specified scopes with the sign-in request.

### 👎 Actual Behavior with Screenshots

The additional scopes are not sent with the sign-in request.

`app-config.yaml`
![image](https://github.com/backstage/backstage/assets/1596686/9fc5632a-0bda-46a8-a2de-cbdeeccad1df)

Parameters sent during sign-in:
![image](https://github.com/backstage/backstage/assets/1596686/9043e9da-3aa3-42d0-8354-851f8bede1ee)
```
...&scope=openid email profile offline_access&state=...
```

### 👟 Reproduction steps

1. Follow the instructions in the [docs](https://backstage.io/docs/auth/okta/provider/#configuration) to configure Okta with `additionalScope`, e.g.,
```
    okta:
      development:
        clientId: <your_client_id>
        clientSecret: <your_client_secret>
        audience: https://<your-domain>.okta.com
        additionalScopes: groups
```
2. Sign in with Okta

### 📃 Provide the context for the Bug.

We would like to send additional scopes in order to receive custom claims in the response.

**Problem**
_During sign-in, on the frontend:_
1. In `packages/app-defaults/src/defaults/apis.ts`, the factory creates the Okta API via OktaAuth.create
1. In `packages/core-app-api/src/apis/implementations/auth/okta/OktaAuth.ts`, `OktaAuth.create`:
    1. reads `defaultScopes` from `options`, and defaults to `['openid', 'email', 'profile', 'offline_access']`
    1. creates `OAuth2` via `OAuth2.create` and passes it the `defaultScopes`
1. In `packages/core-app-api/src/apis/implementations/auth/oauth2/OAuth2.ts`, `OAuth2.create`:
     i.  reads `defaultScopes` from `options`
     ii. creates `RefreshingAuthSessionManager` and passes it `defaultScopes`
1. In `packages/core-app-api/src/lib/AuthSessionManager/RefreshingAuthSessionManager.ts`, it creates `SessionScopeHelper` and passes it `defaultScopes`, which it keeps for later

_During authentication:_
1. In `packages/core-components/src/layout/SignInPage/SignInPage.tsx`, `login` calls` OAuth2.getBackstageIdentity`
1. In `packages/core-app-api/src/apis/implementations/auth/oauth2/OAuth2.ts`, `getBackstageIdentity` calls `RefreshingAuthSessionManager.getSession`
1. In `packages/core-app-api/src/lib/AuthSessionManager/RefreshingAuthSessionManager.ts`, `getSession` calls SessionScopeHelper.getExtendedScope, which effectively returns defaultScopes
1. In `packages/core-app-api/src/lib/AuthSessionManager/RefreshingAuthSessionManager.ts`, `getSession` calls `DefaultAuthConnector.createSession` and passes it `scopes` it got from `SessionScopeHelper.getExtendedScope`
1. In `packages/core-app-api/src/lib/AuthConnector/DefaultAuthConnector.ts`, `createSession` calls `showPopup`/`executeRedirect`, and passes it `options.scopes`

_Summary_
- `additionalScopes` gets combined with the `defaultScopes` "openid profile email" and set as `scope` in the `Strategy` object in `plugins/auth-backend-module-okta-provider/src/authenticator.ts` 
- `OktaAuth.create` in `packages/core-app-api/src/apis/implementations/auth/okta/OktaAuth.ts` provides the `defaultScopes` as `['openid', 'email', 'profile', 'offline_access']` during authentication on the frontend

### 🖥️ Your Environment

Browser (Chrome)
```
Version 125.0.6422.61 (Official Build) (arm64)
```

<details>
<summary>yarn backstage-cli info</summary>
OS:   Darwin 22.4.0 - darwin/arm64
node: v18.16.0
yarn: 1.22.19
cli:  0.25.1 (installed)
backstage:  1.22.2

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.4.1, 0.5.10
  @backstage/backend-common                                        0.18.3, 0.19.10, 0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.5.4, 0.6.9
  @backstage/backend-tasks                                         0.5.14
  @backstage/backend-test-utils                                    0.2.10
  @backstage/catalog-client                                        1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.12.0
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.12.5, 0.13.10, 0.14.0
  @backstage/core-plugin-api                                       1.9.0
  @backstage/dev-utils                                             1.0.26
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.5.0, 0.6.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.3
  @backstage/plugin-catalog-backend-module-incremental-ingestion   0.4.13
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.16
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend                                1.16.2
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-home-react                                     0.1.7
  @backstage/plugin-home                                           0.6.1
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-backend                             0.5.32
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.20
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.6
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.1
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
</details>

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by liununu** [comment]
We have the same issue, and after some investigations we are thinking it was introduced by #21325 

Hi @ataylorme / @Josh-Uvi could you help to correct me for the below finding

```typescript
// Previously `plugins/auth-backend/src/providers/okta/provider.ts` would combine
// default and additional scopes when start authentication,
// and then pass combined scope to `executeRedirectStrategy` to override the value from http request.
async start(req: OAuthStartRequest): Promise<OAuthStartResponse> {
  const scope = this.combineScopeStrings(req.scope, this.additionalScopes);
  return await executeRedirectStrategy(req, this.strategy, {
    accessType: 'offline',
    prompt: 'consent',
    scope: scope,
    state: encodeState(req.state),
  });
}
```

```typescript
// Currently `plugins/auth-backend-module-okta-provider/src/authenticator.ts` 
// will save combined scope to `OktaStrategy` only, it will not pass to `helper` when start authentication. 
// By default, the value will always read from http request which is hardcoded in 
// `packages/core-app-api/src/apis/implementations/auth/okta/OktaAuth.ts`
async start(input, helper) {
  return helper.start(input, {
    accessType: 'offline',
    prompt: 'consent',
  });
},
```

**Comment by Rugvip** [comment]
Yep, these are indeed ignored since they're only configured as part of the strategy. I've got a fix for this on the way for all providers in #24743, but not sure whether we'll get that into the 1.28 release or not.

**Comment by liununu** [comment]
Hi @Rugvip thanks for the support, its verified `'additionalScopes' is working now for Okta provider.

**Comment by freben** [comment]
Thanks, closing!
