### ISSUE TITLE
🐛 Bug Report:  Auth Plugin: OAuth2Proxy Public Key Integration Issue

### ISSUE THREAD

**Issue by mschmermer** [backstage/backstage#24886]
### 📜 Description

I am encountering an issue with OAuth2Proxy authentication in Backstage where there is no way to specify the public key from our OAuth provider. As a result, the token verification fails.

### 👍 Expected behavior

There should be a way to specify the public key from our OAuth provider to extend the keystore for token verification.

Actual Behavior:
Token verification fails due to the missing public key in the keystore, resulting in the error JWKSNoMatchingKey: no applicable key found in the JSON Web Key Set.

### 👎 Actual Behavior with Screenshots

The following error 

```
{
"error": {
"name": "AuthenticationError",
"message": "Invalid token; caused by JWKSNoMatchingKey: no applicable key found in the JSON Web Key Set",
"cause": {
"code": "ERR_JWKS_NO_MATCHING_KEY",
"name": "JWKSNoMatchingKey",
"message": "no applicable key found in the JSON Web Key Set",
"stack": "JWKSNoMatchingKey: no applicable key found in the JSON Web Key Set\n    at LocalJWKSet.getKey (/opt/app-root/src/node_modules/jose/dist/node/cjs/jwks/local.js:84:19)\n    at RemoteJWKSet.localJWKSet [as _local] (/opt/app-root/src/node_modules/jose/dist/node/cjs/jwks/local.js:116:63)\n    at RemoteJWKSet.getKey (/opt/app-root/src/node_modules/jose/dist/node/cjs/jwks/remote.js:54:31)\n    at remoteJWKSet (/opt/app-root/src/node_modules/jose/dist/node/cjs/jwks/remote.js:90:64)\n    at flattenedVerify (/opt/app-root/src/node_modules/jose/dist/node/cjs/jws/flattened/verify.js:75:21)\n    at compactVerify (/opt/app-root/src/node_modules/jose/dist/node/cjs/jws/compact/verify.js:18:60)\n    at Object.jwtVerify (/opt/app-root/src/node_modules/jose/dist/node/cjs/jwt/verify.js:8:58)\n    at _UserTokenHandler.verifyToken (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:2540:36)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DefaultAuthService.authenticate (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:2156:24)\n    at async DefaultHttpAuthService.extractCredentialsFromRequest_fn (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:3144:10)\n    at async DefaultHttpAuthService.credentials (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:3065:181)"
}
},
"request": {
"method": "GET",
"url": "/api/catalog/entity-facets?facet=metadata.tags"
},
"response": {
"statusCode": 401
}
}
```

### 👟 Reproduction steps

Steps to Reproduce:

```
Use the following code for the sign-in resolver to authenticate the user:

import { createBackendModule } from "@backstage/backend-plugin-api";
import { OAuth2ProxyResult } from "@backstage/plugin-auth-backend-module-oauth2-proxy-provider";
import { authProvidersExtensionPoint, createProxyAuthProviderFactory, SignInInfo } from "@backstage/plugin-auth-node";
import { DEFAULT_NAMESPACE, stringifyEntityRef } from '@backstage/catalog-model';

var pluginAuthNode = require('@backstage/plugin-auth-node');
var errors = require('@backstage/errors');
var jose = require('jose');

const OAUTH2_PROXY_JWT_HEADER = "authorization";
const oauth2ProxyAuthenticator = pluginAuthNode.createProxyAuthenticator({
  defaultProfileTransform: async (result: any) => {
    console.log("oauth2ProxyAuthenticator result", result);
    return {
      profile: {
        email: result.getHeader("x-forwarded-preferred-email"),
        displayName: result.getHeader("x-forwarded-preferred-username") || result.getHeader("x-forwarded-user")
      }
    };
  },
  async initialize() {},
  async authenticate({ req }: any) {
    var _a;
    try {
      const authHeader = req.header(OAUTH2_PROXY_JWT_HEADER);
      const jwt = (_a = authHeader == null ? void 0 : authHeader.match(/^Bearer[ ]+(\S+)$/i)) == null ? void 0 : _a[1];
      const decodedJWT = jwt && jose.decodeJwt(jwt);
      const result = {
        fullProfile: decodedJWT || {},
        accessToken: jwt || "",
        headers: req.headers,
        getHeader(name: any) {
          if (name.toLocaleLowerCase("en-US") === "set-cookie") {
            throw new Error("Access Set-Cookie via the headers object instead");
          }
          return req.get(name);
        }
      };
      return {
        result,
        providerInfo: {
          accessToken: result.accessToken
        }
      };
    } catch (e) {
      throw new errors.AuthenticationError("Authentication failed (custom authenticate)", e);
    }
  }
});

export default createBackendModule({
  pluginId: 'auth',
  moduleId: 'oauth2-proxy-provider',
  register(reg) {
    reg.registerInit({
      deps: {
        providers: authProvidersExtensionPoint,
      },
      async init({ providers }) {
        providers.registerProvider({
          providerId: 'oauth2Proxy',
          factory: createProxyAuthProviderFactory({
            authenticator: oauth2ProxyAuthenticator,
            signInResolver: async (
              info: SignInInfo<OAuth2ProxyResult>,
              ctx,
            ) => {
              const name = info.result.getHeader('x-forwarded-preferred-username');
              if (!name) {
                throw new Error('Request did not contain a user (from custom module "oauth2proxy")')
              }

              const userEntity = stringifyEntityRef({
                kind: 'User',
                name: name,
                namespace: DEFAULT_NAMESPACE,
              });

              return ctx.issueToken({
                claims: {
                  sub: userEntity,
                  ent: [userEntity],
                },
              });
            },
          }),
        });
      }
    });
  }
});
```

On token verification, the following error occurs:

```
JWKSNoMatchingKey: no applicable key found in the JSON Web Key Set

    at LocalJWKSet.getKey (/opt/app-root/src/node_modules/jose/dist/node/cjs/jwks/local.js:84:19)

    at RemoteJWKSet.localJWKSet [as _local] (/opt/app-root/src/node_modules/jose/dist/node/cjs/jwks/local.js:116:63)

    at RemoteJWKSet.getKey (/opt/app-root/src/node_modules/jose/dist/node/cjs/jwks/remote.js:54:31)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async flattenedVerify (/opt/app-root/src/node_modules/jose/dist/node/cjs/jws/flattened/verify.js:75:15)

    at async compactVerify (/opt/app-root/src/node_modules/jose/dist/node/cjs/jws/compact/verify.js:18:22)

    at async Object.jwtVerify (/opt/app-root/src/node_modules/jose/dist/node/cjs/jwt/verify.js:8:22)

    at async _UserTokenHandler.verifyToken (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:2537:25)

    at async DefaultAuthService.authenticate (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:2154:24)

    at async DefaultHttpAuthService.extractCredentialsFromRequest_fn (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:3137:10)

    at async DefaultHttpAuthService.credentials (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:3060:181)
```

Temporary fix applied by modifying:
/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js
```
async verifyToken(token) {
  const verifyOpts = __privateMethod$3(this, _getTokenVerificationOptions, getTokenVerificationOptions_fn).call(this, token);
  if (!verifyOpts) {
    return void 0;
  }
  await this.jwksClient.refreshKeyStore(token);

  const spki = await fs.readFile('/opt/app-root/src/public-key.pem', { encoding: 'utf8', flag: 'r' });
  const publicKey = await jose.importSPKI(spki, 'RS256');

  console.log(`publicKey ${publicKey}`)
  console.log(`jwksClient.getKey ${this.jwksClient.getKey}`)

  const { payload } = await jose.jwtVerify(
    token,
    publicKey,
    verifyOpts
  ).catch((e) => {
    throw new errors.AuthenticationError("Invalid token", e);
  });
  const userEntityRef = payload.sub;
  if (!userEntityRef) {
    throw new errors.AuthenticationError("No user sub found in token");
  }
  return { userEntityRef };
}
```

### 📃 Provide the context for the Bug.

I see that the keystore is being updated from ${API_ENDPOINT}/.backstage/auth/v1/jwks.json and the public keystores are fetched from the database. There should be a documented way to include additional public keys in the keystore. Any guidance or solution to this issue would be highly appreciated.

### 🖥️ Your Environment

OS:   redhat/ubi9:9.3-1610
node: v20.13.1
yarn: 3.8.2
cli:  0.26.5 (installed)
backstage:  1.27.0

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.7.5
  @backstage/backend-common                                        0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.5
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.67
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.16
  @backstage/plugin-catalog-backend-module-incremental-ingestion   0.4.23
  @backstage/plugin-catalog-backend-module-ldap                    0.5.34
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.11.0
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.15
  @backstage/plugin-permission-backend                             0.5.42
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.7
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node                                0.4.4
  @backstage/plugin-scaffolder-react                               1.8.5
  @backstage/plugin-scaffolder                                     1.20.0
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ivangonzalezacuna** [comment]
I remember we had such an issue in the past with that Bearer token being missed. We had to use an oauth2-proxy alpha configuration to extend the headers. However, we now use the built-in resolvers and it works perfectly fine without needing extra configuration for the proxy.

In our case, we have this config for the provider:

```yaml
auth:
  environment: production
  providers:
    oauth2Proxy:
      signIn:
        resolvers:
          - resolver: emailMatchingUserEntityProfileEmail
```

And in the backend startup:

```ts
backend.add(import('@backstage/plugin-auth-backend'));
backend.add(
  import('@backstage/plugin-auth-backend-module-oauth2-proxy-provider'),
);
```

The oauth2-proxy should be sending the headers by default (email, user and so). So as long as your user in backstage has any of that information in the `spec.profile`, this will work. Here you have other options available for this provider: https://backstage.io/docs/auth/oauth2-proxy/provider

**Comment by mschmermer** [comment]
> I remember we had such an issue in the past with that Bearer token being missed. We had to use an oauth2-proxy alpha configuration to extend the headers. However, we now use the built-in resolvers and it works perfectly fine without needing extra configuration for the proxy.
> 
> In our case, we have this config for the provider:
> 
> ```yaml
> auth:
>   environment: production
>   providers:
>     oauth2Proxy:
>       signIn:
>         resolvers:
>           - resolver: emailMatchingUserEntityProfileEmail
> ```
> 
> And in the backend startup:
> 
> ```ts
> backend.add(import('@backstage/plugin-auth-backend'));
> backend.add(
>   import('@backstage/plugin-auth-backend-module-oauth2-proxy-provider'),
> );
> ```
> 
> The oauth2-proxy should be sending the headers by default (email, user and so). So as long as your user in backstage has any of that information in the `spec.profile`, this will work. Here you have other options available for this provider: https://backstage.io/docs/auth/oauth2-proxy/provider

Unfortunately it does not work for us because our keycloak does not set the following header. I have already invested several hours to adjust the configuration so that it works. The problem is that the following headers are not set by the keycloak:
const OAUTH2_PROXY_JWT_HEADER = “X-OAUTH2-PROXY-ID-TOKEN”;
result.getHeader(“x-forwarded-preferred-username”) 

so I had to rewrite them so that they are used:
const OAUTH2_PROXY_JWT_HEADER = “authorization”;
result.getHeader(“x-forwarded-username”) 

But as I understand it, this would not change anything because the token is still issued by the keycloak and without a public key, backstage cannot validate the signature.

Translated with DeepL.com (free version)

**Comment by mschmermer** [comment]
Okay i found my problem now. The oauth proxy override the autorisation header for backstage so that the backstage can verify the token at the end. :)

**Comment by mschmermer** [comment]
> > Okay i found my problem now. The oauth proxy override the autorisation header for backstage so that the backstage can verify the token at the end. :)
> 
> @mschmermer How did you resolve it?

by removing the config in oauth proxy to pass auth header:

--pass-authorization-header
