### ISSUE TITLE
🚀 Feature: Fetch Gitlab users for self-hosted Gitlab based on group assignment

### ISSUE THREAD

**Issue by hghtwr** [backstage/backstage#24889]
### 🔖 Feature description

When fetching users and adding them to the catalog, the GitlabOrgDiscoveryEntityProvider distinguishes between self-managed and SaaS instances. For self-managed instances, the provider fetches `/users?`, for SaaS `/groups/${encodeURIComponent(groupPath)}/members/all`. 

I propose to introduce a feature configuration for self-managed Gitlab instances to only fetch users that are assigned to the root group declared in the configuration.

### 🎤 Context

We are setting up Backstage for a project of around 500 developers. Our centrally managed Gitlab instance is used across the whole company which means with every start of Backstage we have to wait to load around 15.000 users into our catalog. 
It seems unnecessary to do so if the installation is not supposed to be used across the whole company (which would be nice, but you know...won't happen...). It increases the startup time and also leads to unnecessary load on the Gitlab API side.

### ✌️ Possible Implementation

A quick and dirty test in GitlabOrgDiscoveryEntityProvider shows that we can query the self-managed Gitlab API the same way as SaaS to obtain only the users from the root group.

```typescript
    if (this.gitLabClient.isSelfManaged()) {
      groups = GitlabDiscoveryEntityProvider.paginated(
        (options) => this.gitLabClient.listGroups(options),
        {
          page: 1,
          per_page: 100,
          all_available: true
        }
      );
      /*users = GitlabDiscoveryEntityProvider.paginated(
        (options) => this.gitLabClient.listUsers(options),
        {
          page: 1,
          per_page: 100,
          active: true
        }
      );*/
      groups = (await this.gitLabClient.listDescendantGroups(this.config.group)).items;
      const rootGroup = this.config.group.split("/")[0];
      users = GitlabDiscoveryEntityProvider.paginated(
        (options) => this.gitLabClient.listSaaSUsers(rootGroup, options),
        {
          page: 1,
          per_page: 100
        }
      );

    } else {
      groups = (await this.gitLabClient.listDescendantGroups(this.config.group)).items;
      const rootGroup = this.config.group.split("/")[0];
      users = GitlabDiscoveryEntityProvider.paginated(
        (options) => this.gitLabClient.listSaaSUsers(rootGroup, options),
        {
          page: 1,
          per_page: 100
        }
      );
    }
```

From this implementation I got the 17 assigned users in backstage, instead of 15k users available in Gitlab.

I hope, it would be possible to implement a configuration key for this use-case.
The condition `if (this.gitLabClient.isSelfManaged())` uses a function that doesn't seem to be used elsewhere which means we can maybe enrich it with another flag that adds more control. I would not make it dependent on the definition of a group in the app-config as both of the uses cases (loading all users vs. loading only group members) are valid, in my opinion.

I found recent issues for this topic but it seems like this particular thing hasn't been considered (https://github.com/backstage/backstage/pull/18889/files)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by veenarm** [comment]
I agree, this would be nice to have, it also would allow you to specify multiple root groups and have it sync separate users, where currently even if you do it it tries to load all users twice and throws duplicate entity warnings everywhere.

An addition to this would be to allow disable User ingestion period for Self Hosted, where as right now even if you remove the [User] Digest I believe it still attempts to pull all the users if groups are set, i'll double check this.

**Comment by vinzscam** [comment]
it makes sense, @hghtwr. Would you like to be assigned to the issue?

**Comment by hghtwr** [comment]
Sure, I'd be happy to contribute.

**Comment by benjdlambert** [comment]
Gonna close this as fixed :tada:
