### ISSUE TITLE
🚀 Feature: Being able to add properties to relations

### ISSUE THREAD

**Issue by J0shSkqlq** [backstage/backstage#24887]
### 🔖 Feature description

In order to able to get more Information into the Software Catalog and have more possibilities when extending the entity model, it would be great to be able to add properties to relations. This concept is also present in most graph databases like [neo4j](https://neo4j.com/docs/getting-started/data-modeling/guide-data-modeling/#_defining_properties).
A basic example would be adding the property `since:<date>` to the relation `memberOf`.

### 🎤 Context

The use-case in my organization that made me come up with this idea is the following:
We want to model the releases of our Product in the Software Catalog, including which versions of our services and external dependencies are contained in that release. My inital idea was to create a new entity kind "release" and use the exisiting relation type `hasPart` to connect it with the components that are contained in that release. Through labels on the relations you could then add version information like the version number and URLs to the container image and the SBOM for example.

I feel like this would be the most efficient way of modelling this, but feel free to suggest other ideas that don't involve usage of my proposed feature! 

### ✌️ Possible Implementation

Since I'm not that at home in the backstage codebase yet I will keep this at a higher level.
I would imagine adding the properties to the relation as purely optional key value pairs that don't follow a certain schema, though you could also argue that making a fixed set of keys configurable for a relation type could be the better option. 
Inside a `catalog-info.yaml`  of a service it could look like this: (this is just an example and it's probably not that useful to add one consumed endpoint)

```yaml
spec:
  type: service
  lifecycle: production
  owner: team-A
  system: Multitenancy
  dependsOn:
    - component:keycloak
  providesApis:
    - multitenancy-api
  consumesApis:
    - example-api:
        endpoint: example-endpoint
```
In the catalog backend, the according entity Processors would need to be extended and the entityRelation type in the catalog model likewise.

Concerning the front-end it would be cool to have these properties show up in the graph view similar to how it's done in neo4j: (while being able to disable them with a checkbox)

![neo4j!](https://neo4j.com/docs/getting-started/_images/property_graph_elements-arr.svg "propertyGraph")

I looking forward to hearing what you guys think of this idea!
Although I'm not really proficient in TypeScript or React i would give implementing this a try, given you support the idea.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
This is an ask that's been floated a number of times, see for example related issues and discussion from https://github.com/backstage/backstage/pull/22358 or https://github.com/backstage/backstage/issues/16389 (there's more!). Turns out to be technically slightly tricky, and semantically more than slightly tricky. :) For example, relations are bidirectional; what does that mean for the metadata in the "inverse" direction to what you defined? We do deduplication and processing of these, how does that work in a world where things are multivariate and where it may not be clear to code what to do with the collection of relations? Etc.

This is just me giving some context to where discussions have been at in the past. This may still be possible to do, but it's been a bit of a large ask and not been prioritized so far.

**Comment by vinzscam** [comment]
Closing the issue as it's already part of https://github.com/backstage/backstage/pull/22358

**Comment by J0shSkqlq** [comment]
Hey @freben, thanks for the quick reply and sorry for not checking wether an issue like this had already been raised thouroughly enough :/
I was already expecting there to be implications that make this more way more tricky than just sticking optional Key/Value Pairs onto the relations. The approach mentioned in #22358 (adding a new `complexRelation` type) sounds promising - I really hope you guys will prioritize this some time in the future since i think it would greatly expand the possibilities of the catalog.

Out of pure interest, i was also wondering wether migrating the backend to a graph database has ever been evaluated for backstage. This would obviously mean a ton of work but could really elevate the catalog graph to be more than just a neat visualization and create the possibilty of gaining alot of insights about the structure of your org and software through graph algorithms. 
I guess this would also make for a cool Plugin that could load your entities into a seperate DB, given that a complete migration probably isn't feasable.
