### ISSUE TITLE
🐛 Bug Report: create-app front-end still includes tech-radar icon after plugin removal from backend

### ISSUE THREAD

**Issue by vadave** [backstage/backstage#24898]
### 📜 Description

Commit 5adf594d77793c094233a6d9eb57b3f8c953b030 removed the tech-radar plugin from the back end, but the front-end template created by `create-app` still includes the icon (which errors out when you click it). 

### 👍 Expected behavior

That menu item should be removed in light of the removal of the plugin.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/8081753/8e84a1fc-6b1a-4487-b7dc-2352bbfc481e)

### 👟 Reproduction steps

Create a new app with latest `@backstage/create-app` and run `yarn dev`. The tech-radar menu item will show but will generate an error when you click it.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Closing as fixed in the PR
