### ISSUE TITLE
🚀 Feature: No Code UI For Software Templates

### ISSUE THREAD

**Issue by alper98** [backstage/backstage#24906]
### 🔖 Feature description

As seen with the no code ui for RBAC, it would be interesting with a similar feature for software templates.

Drag and drop input fields and actions.

### 🎤 Context

We want to make the creation of software templates as easy as possible.

### ✌️ Possible Implementation

Im not quite sure, but i could imagine the current `Template Editor` could be used in some way, or extended to allow for these capabilities.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
Hmm - this is an interesting idea for sure! Sorry this slipped through the net a little bit before, so added some labels to assign it to the right places. Might be interesting to chat about it in the next Scaffolder SIG next week!

**Comment by alper98** [comment]
No worries. It's vacay time here in scandinaviaa

**Comment by benjdlambert** [comment]
Think there's also some room here to improve the default template editor that we mentioned in the SIG around this.

- being able to create a new local template and maybe create from existing
- being able to raise PR's to existing templates with the changes that you might create in the editor
