### ISSUE TITLE
Backstage throws 401 error when use static token

### ISSUE THREAD

**Issue by quan1997ap** [backstage/backstage#24907]
### 📜 Description

Hi team, I'm using backstage for my project.
I want create new BE plugin. It call API of Backstage or Call function of Catalog ( to register / create component of backstage ).
But when I call API and pass Secret key to Header. Backstage throws 401 error.
My config like that: https://backstage.io/docs/auth/service-to-service-auth.
How can I call existing API without token from client. I want create token for new plugin.
Thank you so much. Sorry about English.

### 👍 Expected behavior

I want new plugin can call exist API.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/38683698/43f5661a-8e03-4a8e-bbdc-7bb4cc217034)

### 👟 Reproduction steps

.

### 🖥️ Your Environment

.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by quan1997ap** [comment]
@vinzscam  thank for response.
I found function. It can generate token for plugin.
```
    const {token} = await tokenManager.getToken()
```
What is the difference between these two ways?
Thanks.

**Comment by freben** [comment]
@quan1997ap That's the legacy API which is being phased out.

**Comment by quan1997ap** [comment]
Thank you so much
