### ISSUE TITLE
🐛 Bug Report: Stale entries seen on the Backstage Screen and no option to delete them

### ISSUE THREAD

**Issue by anishaanil1** [backstage/backstage#24901]
### 📜 Description

We accidentally put the group files in an incorrect location and started the Backstage System.
I presume these entries have been updated in the database.

We then moved it to the intended location and deleted the  files and updated the location in the yaml files but even after multiple restart the link to the files are still stored in the UI and we are not finding a way to delete them

### 👍 Expected behavior

The file location should be actually updated automatically but is not and the stale entries should not be seen

### 👎 Actual Behavior with Screenshots

![screen-2](https://github.com/backstage/backstage/assets/142504005/1f1c1ed6-6d60-44ba-9339-87d159d318a1)
![screen-1](https://github.com/backstage/backstage/assets/142504005/889bc415-cd02-4df4-a6dc-584bef437378)

### 👟 Reproduction steps

Create the new postgres DB
Ensure the values are updated in the app config files
Create the new groups file and update the yaml files and the location
Start the app and ensure that they are visible on the UI
stop the system
move the files 
restart the app
the incorrect file entries are seen on the UI

### 📃 Provide the context for the Bug.

The Production server has stale entries and it needs to be fixed and we are unable to remove them

### 🖥️ Your Environment

yarn backstage-cli info
yarn run v1.22.19
$ /data/backstage/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.15.0-88-generic - linux/x64
node: v18.18.2
yarn: 1.22.19
cli:  0.23.1 (installed)
backstage:  1.19.0

Dependencies:
  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.5.7, 0.5.9
  @backstage/backend-common                                        0.19.8, 0.20.0
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.6.6, 0.6.8
  @backstage/backend-tasks                                         0.5.11, 0.5.13
  @backstage/catalog-client                                        1.4.5, 1.5.1
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5, 0.2.1
  @backstage/cli                                                   0.23.1
  @backstage/config-loader                                         1.5.2, 1.6.0
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.13.6
  @backstage/core-plugin-api                                       1.7.0
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7, 0.1.8
  @backstage/integration-react                                     1.1.20
  @backstage/integration                                           1.7.1, 1.8.0
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.4
  @backstage/plugin-auth-node                                      0.4.0, 0.4.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-import                                 0.10.1
  @backstage/plugin-catalog-node                                   1.4.7
  @backstage/plugin-catalog-react                                  1.8.5
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-github-actions                                 0.6.6
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-home-react                                     0.1.4
  @backstage/plugin-home                                           0.5.9
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-permission-backend                             0.5.31
  @backstage/plugin-permission-common                              0.7.11, 0.7.9
  @backstage/plugin-permission-node                                0.7.17, 0.7.19
  @backstage/plugin-permission-react                               0.4.16
  @backstage/plugin-proxy-backend                                  0.4.4
  @backstage/plugin-scaffolder-backend                             1.18.1
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.7
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-tech-radar                                     0.6.9
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.1
  @backstage/plugin-techdocs-node                                  1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.6
Done in 0.86s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by vinzscam** [comment]
what's your goal here? Remove the files completely or move the files to a different location?

**Comment by anishaanil1** [comment]
We have removed the files but the entries are visible in the Frontend and hence I want to move them out completely from the UI

**Comment by anishaanil1** [comment]
Do we have an update here?????

**Comment by vinzscam** [comment]
are you sure the relative urls between entities are correct? If you move the files to a different location and then update the `catalog.locations` in your app-config it should make your Backstage pick up the new entities from a different location.

Also double check that the files are included in the generated Docker image
