### ISSUE TITLE
🐛 Bug Report: The templating engine converts the `|` into `>` 

### ISSUE THREAD

**Issue by Debanitrkl** [backstage/backstage#24913]
### 📜 Description

While trying to add newline in the custom action output when we use `|` or `|-` operator  it get's auto converted to `>` or `>-`
![Screenshot 2024-05-27 at 2 28 46 PM](https://github.com/backstage/backstage/assets/50622005/b94a3232-4510-4e8c-bf68-9a2eb964040c)

### 👍 Expected behavior

Shouldn't conver the original operator used by the user as `|` new line whereas `>` is used for other purposes

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-05-27 at 2 28 46 PM](https://github.com/backstage/backstage/assets/50622005/b94a3232-4510-4e8c-bf68-9a2eb964040c)

### 👟 Reproduction steps

Use the following output syntax

```
  output:
    text:
      - title: Output Variable 1
        content: |-
              Value of **Output Variable 1** is `${{ steps.trigger.output.outputVar1 }}`
              Value of **Output Variable 2 in 1st var step** is `${{ steps.trigger.output['pipeline.stages.build.spec.execution.steps.Run_1.output.outputVariables.outputVar2'] }}`
      - title: Output Variable 2
        content: |
          Value of **Output Variable 2** is `${{ steps.trigger.output['pipeline.stages.build.spec.execution.steps.Run_1.output.outputVariables.outputVar2'] }}`
```

### 📃 Provide the context for the Bug.

I'm trying to get the output in a new line but it appears on the same line

### 🖥️ Your Environment

backstage version 1.21

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by acierto** [comment]
Hey @Debanitrkl!

Do you encounter some issues because of this or is it a matter of taste?

**Comment by Debanitrkl** [comment]
> Do you encounter some issues because of this or is it a matter of taste?
Yeah it's quite confusing for developers when we try to display logs as an output. without line-breaks it's not possible to display the logs as it doesn't add any value then and becomes a cumbersome task for devs to read and understand.

**Comment by Rugvip** [comment]
Initial bunch here is that it's because the content is rendered as markdown, so you need two newlines.

**Comment by Debanitrkl** [comment]
> Initial bunch here is that it's because the content is rendered as markdown, so you need two newlines.

Yes exactly.

**Comment by benjdlambert** [comment]
I wonder if there's a way to treat the line breaks in the `MarkdownContent` as proper linebreaks without having to do `</br>` or double newlines.
