### ISSUE TITLE
Rename service config types to options: `ServiceRefConfig`, `RootServiceFactoryConfig` and `PluginServiceFactoryConfig`

### ISSUE THREAD

**Issue by camilaibs** [backstage/backstage#24923]
### Context

Ref: https://github.com/backstage/backstage/issues/24493

We are revising service types in preparation for the new backend system stable release.

### Description

All service config types should be renamed to option types in order to standardize frontend and backend `create` function signatures:

- [x] Rename `ServiceRefConfig` to `ServiceRefOptions`
- [x] Rename `RootServiceFactoryConfig` to `RootServiceFactoryOptions`
- [x] Rename `PluginServiceFactoryConfig` to `PluginServiceFactoryOptions`

### Acceptance criteria

- Deprecation export statements must be declared in a `deprecated.ts` file
- Deprecation export statements must be annotated with `@deprecated` and contain a comment with their replacements
- Other packages' import statements must be updated to use the new type name
- Documentation examples should be revisited to use the new type name

**Comment by ShivamJha2436** [comment]
Hey @camilaibs . Is this issue has been resolved or not ?

**Comment by camilaibs** [comment]
@ShivamJha2436 , I've started working on it today. I'm just curious, do you have any specific interest in this?

**Comment by ShivamJha2436** [comment]
I am interested to work on this issue, but if you already started working in this one, please go ahead.

**Comment by camilaibs** [comment]
> I am interested to work on this issue, but if you already started working in this one, please go ahead.

So kind of you, we have more items here in [this meta issue](https://github.com/backstage/backstage/issues/24493), please let me know if you would like to contribute with one of them, we appreciate your contribution 🙂

**Comment by camilaibs** [comment]
Currently on hold while waiting for service module features.

**Comment by camilaibs** [comment]
We a re good to merge the PR
