### ISSUE TITLE
🐛 Bug Report: oidc auth provider

### ISSUE THREAD

**Issue by phac008** [backstage/backstage#24935]
### 📜 Description

i add [oidc auth provider](https://github.com/backstage/backstage/tree/69924c8fa353e4ad475116e9d2706b70413e8a12/plugins/auth-backend-module-oidc-provider) to my app-config.yaml, additional i setup values regarding [official app-config.yaml](https://github.com/backstage/backstage/blob/69924c8fa353e4ad475116e9d2706b70413e8a12/app-config.yaml#L364)

i already switched to new-backend system:

> $ grep oidc packages/backend/src/index.ts
backend.add(import('@backstage/plugin-auth-backend-module-oidc-provider'));

running `yarn dev` on local environment -> everything works as expected.
When Deploying config with official [Helm Chart](backstage) - i receive following error:

> 2024-05-27T21:05:32.678Z auth info Configuring auth provider: github
2024-05-27T21:05:32.679Z auth info Configuring auth provider: oidc
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443
}
Node.js v18.20.2

in local environment i use default http://localhost:3000 for app.baseUrl and http://localhost:7007 for backend.baseUrl.

in helm deployment i use 
```    appConfig:
      app:
        title: my App
        baseUrl: https://backstage-127-0-0-1.nip.io

      organization:
        name: my App

      backend:
        # Used for enabling authentication, secret is shared by all backend plugins
        # See https://backstage.io/docs/tutorials/backend-to-backend-auth for
        # information on the format
        auth:
          keys:
            - secret: ${BACKEND_SECRET}
        baseUrl: https://backstage-127-0-0-1.nip.io
        listen:
          port: 7007
          # Uncomment the following host directive to bind to specific interfaces
          # host: 127.0.0.1
        csp:
          connect-src: ["'self'", 'http:', 'https:']
          frame-src: ['*.nip.io']
          # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
          # Default Helmet Content-Security-Policy values can be removed by setting the key to false
        cors:
          origin: https://backstage-127-0-0-1.nip.io
          methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
          credentials: true
....snip
      auth:
        session:
          secret: mysupersecret
        environment: development
        providers:
          github:
            development:
              clientId: ${GITHUB_CLIENTID}
              clientSecret: ${GITHUB_CLIENTSECRET}
              signIn:
                resolvers:
                  - resolver: usernameMatchingUserEntityName
              schedule:
                frequency: PT30M
                timeout: PT3M
          oidc:
            development:
              metadataUrl: https://keycloak-127-0-0-1.nip.io/realms/<myrealm>/.well-known/openid-configuration
              clientId: backstage
              clientSecret: <mysecret>
              prompt: auto
              signIn:
                resolvers:
                  - resolver: emailLocalPartMatchingUserEntityName
                  - resolver: emailMatchingUserEntityProfileEmail
 ```

          any ideas how to find the reason here?

### 👍 Expected behavior

oidc should work like local test environment

### 👎 Actual Behavior with Screenshots

backstage fails to start with helm chart deployment.

### 👟 Reproduction steps

deploy backstage with helm chart
setup oidc auth provider

### 🖥️ Your Environment

OS:   Darwin 23.4.0 - darwin/arm64
node: v20.13.1
yarn: 1.22.22
cli:  0.26.5 (installed)
backstage:  1.27.3

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.5.14, 0.7.5
  @backstage/backend-common                                        0.19.10, 0.20.2, 0.21.7, 0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-plugin-manager                                0.0.2-janus.5
  @backstage/backend-tasks                                         0.5.23
  @backstage/backend-test-utils                                    0.3.8
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5, 0.2.5
  @backstage/cli                                                   0.26.5
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.12.5, 0.13.10, 0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.32
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.67
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.11.0
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-backend                                 0.2.22
  @backstage/plugin-events-node                                    0.2.22, 0.3.4
  @backstage/plugin-home-react                                     0.1.13
  @backstage/plugin-home                                           0.7.4
  @backstage/plugin-kubernetes-backend                             0.17.1
  @backstage/plugin-kubernetes-common                              0.7.6
  @backstage/plugin-kubernetes-node                                0.1.12
  @backstage/plugin-kubernetes-react                               0.3.5
  @backstage/plugin-kubernetes                                     0.11.10
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.15
  @backstage/plugin-permission-backend                             0.5.42
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.7
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node                                0.2.10, 0.4.4
  @backstage/plugin-scaffolder-react                               1.8.6
  @backstage/plugin-scaffolder                                     1.20.0
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-explore                  0.1.24
  @backstage/plugin-search-backend-module-pg                       0.5.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 3.61s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by phac008** [comment]
Investigating further:

for another test i moved my Keycloak from local kind installation (https://keycloak-127-0-0-1.nip-io/..)  into one of our cloud providers clusters (adapt metadataurl to this new location)-> backstage oidc login works again 

back to my local setup
this may will be a conflict with metadataurl and nginx ingress 

> kubectl get ingress -A
NAMESPACE    NAME                               CLASS    HOSTS                        ADDRESS     PORTS     AGE
backstage    sx-backstage                       <none>   backstage-127-0-0-1.nip.io   localhost   80, 443   42h
keycloak     keycloak-service                   <none>   keycloak-127-0-0-1.nip.io    localhost   80, 443   4d13h

both services have tis setup with valid certificates (self signed)

Issuer from openid-client module (https://github.com/backstage/backstage/blob/69924c8fa353e4ad475116e9d2706b70413e8a12/plugins/auth-backend-module-oidc-provider/src/authenticator.ts#L80) seems to resolve my metadataurl link to 127.0.0.1:443

anything I can do to get this running?

**Comment by vinzscam** [comment]
sorry but isn't your `metadataUrl` the problem? If you use `https://keycloak-127-0-0-1.nip-io/` shouldn't it be resolved to localhost which means to the same backstage backend?

**Comment by phac008** [comment]
shouldn't, ingress configuration show to different backend services:
why ingress configuration isn't honored during validation check?

**Comment by vinzscam** [comment]
if you can provide us more precise reproduction steps we can have a look. But according to the information you have provided so far the issue looks unrelated to Backstage

**Comment by phac008** [comment]
sure - the easiest way to recreate will be our setup instruction for [local demo environment](https://github.com/suxess-it/sx-cnp-oss?tab=readme-ov-file#cnp-local-demo-environment)

to re-activate oidc login provider(currently disabled, so backstage can start) please uncomment line [in backstage configuration](https://github.com/suxess-it/sx-cnp-oss/blob/main/platform-apps/charts/backstage/values-k3d.yaml#L134-L146)

hope this help to recreate the issue

**Comment by phac008** [comment]
@vinzscam  - Update: I changed metadataUrl in backstage helm values files to internal service `metadataUrl: http://keycloak-service.keycloak.svc.cluster.local:8080/realms/sx-cnp-oss`, and added additional frontendUrl in keycloak to `https://keycloak-127-0-0-1.nip.io,` so that auth sequence can run properly.
Now this works for local test as expected
