### ISSUE TITLE
scaffolder: Enable branch protection for GitHub

### ISSUE THREAD

**Issue by timja** [backstage/backstage#2494]
## Feature Suggestion

Hi 👋 

It would be good if scaffolder added branch protection for the default branch.

## Possible Implementation

Either add by default or add some configuration that allows you to set it up.

In our case our default setup is:

Protect default branch
require review 1
include administrators

but this may be org specific

## Context

Require review on code changes

**Comment by mfrinnstrom** [comment]
Azure DevOps supports this as well and it would be nice to have this support there as well. 

Just adding this comment here so that we hopefully can build something generic.

**Comment by benjdlambert** [comment]
Hey, could you add you usecases and maybe some possible solutions to this RFC that we've currently got ongoing?

https://github.com/spotify/backstage/issues/2447

**Comment by Gaardsholt** [comment]
This is still relevant

**Comment by benjdlambert** [comment]
Yep - contributions are welcome to the new Publish Github action or a separate action entirely.

https://github.com/backstage/backstage/blob/289045ed66bf584f7f81b6697061ee43e07d87ee/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts
