### ISSUE TITLE
🚀 Feature: Describe how to add permissions framework with the new backend system

### ISSUE THREAD

**Issue by razvanonet** [backstage/backstage#24942]
### 🔖 Feature description

Following the changes that came with the new backend system, there are a lot of plugins/ implementations that are presented in the documentation and just don't work anymore. For someone that has worked with Backstage only since the new backend system came to live, it is very hard to implement things that are only explained for the legacy backend system into the new one.

### 🎤 Context

Trying to configure permissions framework and there I cannot find any example on how to add a policy and how to extend the plugin without using `createPlugin`.

### ✌️ Possible Implementation

documentation to be updated for the most important features of backstage. As a new backstage user (2 months), I have to say that the documentation is very very poor and I never implemented something that was just working out of the box. Most of the times I had to find implementations for stuff that is supposed to work with the new backend system in github issues or different threads online because in the documentation it is either vaguely explained or explained for the legacy backend system. I am thinking on using an older version of backstage, having the legacy system. It is all a mess now

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @razvanonet, sorry to hear that you had issues. We are actively working to get the documentation updated. There's a tracker here: https://github.com/backstage/backstage/issues/24195

For the permissions documentation this PR was merged last week: https://github.com/backstage/backstage/pull/24229. Are you saying the documentation is still not up to date for permissions? Can you share some links so we can make sure they get updated?

**Comment by razvanonet** [comment]
> Hi @razvanonet, sorry to hear that you had issues. We are actively working to get the documentation updated. There's a tracker here: #24195
> 
> For the permissions documentation this PR was merged last week: #24229. Are you saying the documentation is still not up to date for permissions? Can you share some links so we can make sure they get updated?

the page updated in PR #24229 is the only one that got updated, you can follow it to add the permissions plugin but there is no information on how to extend it to add a custom policy

**Comment by awanlin** [comment]
Thanks for the follow up @razvanonet, you are correct there is still things that are missing or not clear. I'm also not sure that these updates are actually visible, to see these changes I needed to go to: https://backstage.io/docs/permissions/getting-started--new/.

@Parsifal-M, looks like we might have missed a few things or perhaps this is for follow up work? Any chance you can help update the docs around this?

**Comment by leandro-cam** [comment]
Hey guys (@Parsifal-M and @awanlin  )!

Do we have any news about updating the permissions documentation for the new backend system?

I'm going through the same situation and having the same feeling of @razvanonet 

Are there examples that I can use to integrate permissions into the new system?

Is it better for me to use permissions on the old system?

**Comment by Parsifal-M** [comment]
> Hey guys (@Parsifal-M and @awanlin  )!
> 
> Do we have any news about updating the permissions documentation for the new backend system?
> 
> I'm going through the same situation and having the same feeling of @razvanonet 
> 
> Are there examples that I can use to integrate permissions into the new system?
> 
> Is it better for me to use permissions on the old system?

Hey! 👋

I'm going to take a stab at the next section this weekend, however it's not super complicated to setup and use permissions in the new backend, where are your concerns? Maybe we can take a look here, or in the permissions channel on the discord? 👍

**Comment by leandro-cam** [comment]
Very fast! 

I'm using the new backend system, and I already have the following in my backend/src/index.ts file (this comes by default):

```
// permission plugin
backend.add(import('@backstage/plugin-permission-backend/alpha'));
backend.add(
  import('@backstage/plugin-permission-backend-module-allow-all-policy'),
);
```

Now, I need to know the next steps to use the plugin.

**Comment by Parsifal-M** [comment]
> Very fast! 
> 
> I'm using the new backend system, and I already have the following in my backend/src/index.ts file (this comes by default):
> 
> ```
> // permission plugin
> backend.add(import('@backstage/plugin-permission-backend/alpha'));
> backend.add(
>   import('@backstage/plugin-permission-backend-module-allow-all-policy'),
> );
> ```
> 
> Now, I need to know the next steps to use the plugin.

Hey 😅

Now all you need to do is set this key in your app config:

```yaml
permission:
  enabled: true
```

And you're using permissions! 

But with that policy everything is allowed by default, so it will always return `ALLOW` which is maybe not what you want 😉

The next part is writing your own policy, that's the bit that's missing from the new docs which I will try to tackle on the weekend. But if youre in a bind, you can find that allow all policy you have in the repo and basically do the same _inline_ in your index.ts file, or outside in packages/backend and import it. 

Sorry for the bad formatting I'm on mobile! I'm going to call it a day now, good luck! I will check back later!

**Comment by leandro-cam** [comment]
Will you be able to help me?

**Comment by leandro-cam** [comment]
Thank you. I will try, and send updates here.

**Comment by leandro-cam** [comment]
Done! Steps from [Getting Started doc](https://backstage.io/docs/permissions/getting-started/) finished.

I followed the [permission-backend-module-policy-allow-all](https://github.com/backstage/backstage/blob/master/plugins/permission-backend-module-policy-allow-all/src/module.ts) source code.

Follows the code:

```ts
// For example, in packages/backend/src/policy.ts

import {
  AuthorizeResult,
  PolicyDecision,
} from '@backstage/plugin-permission-common';
import {
  PermissionPolicy,
  PolicyQuery,
} from '@backstage/plugin-permission-node';

import { BackstageIdentityResponse } from '@backstage/plugin-auth-node';

export class ANamePolicy implements PermissionPolicy {
  async handle(
    request: PolicyQuery,
    _user?: BackstageIdentityResponse,
  ): Promise<PolicyDecision> {
    if (request.permission.name === 'catalog.entity.delete') {
      return {
        result: AuthorizeResult.DENY,
      };
    }

    return {
      result: AuthorizeResult.ALLOW,
    };
  }
}
```

```ts
// For example, in packages/backend/src/module.ts

import { ANamePolicy } from './policy';
import { createBackendModule } from '@backstage/backend-plugin-api';
import { policyExtensionPoint } from '@backstage/plugin-permission-node/alpha';

export const permissionModuleANamePolicy = createBackendModule({
  pluginId: 'permission',
  moduleId: 'a-name-policy',
  register(reg) {
    reg.registerInit({
      deps: { policy: policyExtensionPoint },
      async init({ policy }) {
        policy.setPolicy(new ANamePolicy());
      },
    });
  },
});
```

Now, import permissionModuleANamePolicy

```ts
// For example, in packages/backend/src/index.ts

// ...
import { permissionModuleANamePolicy } from './module';
// ...

backend.add(import('@backstage/plugin-permission-backend/alpha'));
// backend.add(
//   import('@backstage/plugin-permission-backend-module-allow-all-policy'),
// );
backend.add(permissionModuleANamePolicy);
```

**Comment by freben** [comment]
Seems like it!

**Comment by madsteer** [comment]
I know this is closed now, but I'm not sure why ... or at least I think there's more work to be done.  [This page](https://backstage.io/docs/permissions/plugin-authors/02-adding-a-basic-permission-check) of the Using Permissions in your plugin tutorial talks about editing a `packages/backend/src/extensions/permissionsPolicyExtension.ts` file, which does not exist for me.  I will read through the previous posts and try to figure out a work around, but it's not possible to follow this tutorial as it's written anymore, is it?  Thanks!

**Comment by Parsifal-M** [comment]
> I know this is closed now, but I'm not sure why ... or at least I think there's more work to be done.  [This page](https://backstage.io/docs/permissions/plugin-authors/02-adding-a-basic-permission-check) of the Using Permissions in your plugin tutorial talks about editing a `packages/backend/src/extensions/permissionsPolicyExtension.ts` file, which does not exist for me.  I will read through the previous posts and try to figure out a work around, but it's not possible to follow this tutorial as it's written anymore, is it?  Thanks!

Hey! 👋

Did you by any chance miss a step here? https://backstage.io/docs/permissions/getting-started

There is a bullet point that mentions to create the file.

**Comment by madsteer** [comment]
> > I know this is closed now, but I'm not sure why ... or at least I think there's more work to be done.  [This page](https://backstage.io/docs/permissions/plugin-authors/02-adding-a-basic-permission-check) of the Using Permissions in your plugin tutorial talks about editing a `packages/backend/src/extensions/permissionsPolicyExtension.ts` file, which does not exist for me.  I will read through the previous posts and try to figure out a work around, but it's not possible to follow this tutorial as it's written anymore, is it?  Thanks!
> 
> Hey! 👋
> 
> Did you by any chance miss a step here? https://backstage.io/docs/permissions/getting-started
> 
> There is a bullet point that mentions to create the file.

Apparently.  I started at the "tutorial setup" here:  https://backstage.io/docs/permissions/plugin-authors/01-setup  seemed like the start. ¯\_(ツ)_/¯

**Comment by Parsifal-M** [comment]
> > > I know this is closed now, but I'm not sure why ... or at least I think there's more work to be done.  [This page](https://backstage.io/docs/permissions/plugin-authors/02-adding-a-basic-permission-check) of the Using Permissions in your plugin tutorial talks about editing a `packages/backend/src/extensions/permissionsPolicyExtension.ts` file, which does not exist for me.  I will read through the previous posts and try to figure out a work around, but it's not possible to follow this tutorial as it's written anymore, is it?  Thanks!
> > 
> > Hey! 👋
> > 
> > Did you by any chance miss a step here? https://backstage.io/docs/permissions/getting-started
> > 
> > There is a bullet point that mentions to create the file.
> 
> Apparently.  I started at the "tutorial setup" here:  https://backstage.io/docs/permissions/plugin-authors/01-setup  seemed like the start. ¯\\_(ツ)_/¯ 

Hmm yeah I definitely see now how that could be somewhat misleading. Will take a look to see if we can make it flow better!

Thanks for the heads up!

**Comment by madsteer** [comment]
> > > > I know this is closed now, but I'm not sure why ... or at least I think there's more work to be done.  [This page](https://backstage.io/docs/permissions/plugin-authors/02-adding-a-basic-permission-check) of the Using Permissions in your plugin tutorial talks about editing a `packages/backend/src/extensions/permissionsPolicyExtension.ts` file, which does not exist for me.  I will read through the previous posts and try to figure out a work around, but it's not possible to follow this tutorial as it's written anymore, is it?  Thanks!
> > > 
> > > 
> > > Hey! 👋
> > > Did you by any chance miss a step here? https://backstage.io/docs/permissions/getting-started
> > > There is a bullet point that mentions to create the file.
> > 
> > 
> > Apparently.  I started at the "tutorial setup" here:  https://backstage.io/docs/permissions/plugin-authors/01-setup  seemed like the start. ¯\_(ツ)_/¯
> 
> Hmm yeah I definitely see now how that could be somewhat misleading. Will take a look to see if we can make it flow better!
> 
> Thanks for the heads up!

While you're looking at this:  Take a look at how [this page](https://backstage.io/docs/permissions/writing-a-policy) has you make several changes that I'm not sure the tutorial expects.  To start the tutorial are you just supposed to put things back to the [getting started](https://backstage.io/docs/permissions/getting-started) page maybe?

Thanks!
