### ISSUE TITLE
🚀 Feature: how to modify Catalog Entity's name length restriction.

### ISSUE THREAD

**Issue by umyonghyun** [backstage/backstage#24958]
### 🔖 Feature description

 how to modify Catalog Entity's name length restriction.

### 🎤 Context

i create catalog entities from custom entity provider by this ways [external-integrations](https://backstage.io/docs/features/software-catalog/external-integrations). 

but when entities was created, several entities are failed for entity name length  restriction
([adrs-adr002](https://backstage.io/docs/architecture-decisions/adrs-adr002/#name))

i wonder how to modify Catalog Entity's name length restriction in my custom entity provider.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
https://backstage.io/docs/features/software-catalog/extending-the-model#changing-the-validation-rules-for-the-entity-envelope-or-metadata-fields

Beware though that the full entity ref (kind, namespace and name) can never be more than 250 characters due to how database index limitations work.
