### ISSUE TITLE
🐛 Bug Report: Adding Notifications Plugin to Backstage leads to TypeError

### ISSUE THREAD

**Issue by enyineer** [backstage/backstage#24961]
### 📜 Description

When creating a new Vanilla Backstage Instance and then adding the Notifications Plugin (`@backstage/plugin-notifications`) leads to a TypeError in the application.

### 👍 Expected behavior

It should render the Frontend components of the Notification Plugin.

### 👎 Actual Behavior with Screenshots

It actually throws an Error when adding these components according to the Plugins README.

```
TypeError
Cannot read properties of undefined (reading 'color')
Call Stack
 name
  node_modules/@backstage/plugin-notifications/node_modules/@backstage/core-components/dist/layout/Sidebar/Items.esm.js:65:41
 Object.create
  node_modules/@backstage/plugin-notifications/node_modules/@material-ui/styles/esm/getStylesCreator/getStylesCreator.js:27:35
 attach
  node_modules/@backstage/plugin-notifications/node_modules/@material-ui/styles/esm/makeStyles/makeStyles.js:110:32
 eval
  node_modules/@backstage/plugin-notifications/node_modules/@material-ui/styles/esm/makeStyles/makeStyles.js:252:7
 useSynchronousEffect
  node_modules/@backstage/plugin-notifications/node_modules/@material-ui/styles/esm/makeStyles/makeStyles.js:204:14
 useStyles
  node_modules/@backstage/plugin-notifications/node_modules/@material-ui/styles/esm/makeStyles/makeStyles.js:244:5
 useMemoStyles
  node_modules/@backstage/plugin-notifications/node_modules/@backstage/core-components/dist/layout/Sidebar/Items.esm.js:182:10
 eval
  node_modules/@backstage/plugin-notifications/node_modules/@backstage/core-components/dist/layout/Sidebar/Items.esm.js:264:19
 renderWithHooks
  node_modules/react-dom/cjs/react-dom.development.js:15486:18
 updateForwardRef
  node_modules/react-dom/cjs/react-dom.development.js:19240:20
```

<img width="944" alt="image" src="https://github.com/backstage/backstage/assets/27201677/b9900006-f91e-4e71-b7fe-302f79518e93">

### 👟 Reproduction steps

1. Create new Backstage Project
`npx @backstage/create-app@latest`
2. Install deps
`yarn install`
3. Install packages to backend
`yarn add @backstage/plugin-signals-backend @backstage/plugin-events-backend @backstage/plugin-notifications-backend`
4. Add Backend Plugins to index.ts
```ts
/* Signals */
backend.add(import('@backstage/plugin-signals-backend'));

/* Events */
backend.add(import('@backstage/plugin-events-backend/alpha'));

/* Notifications */
backend.add(import('@backstage/plugin-notifications-backend'));
```
4. Install package to app
`yarn add @backstage/plugin-notifications`
6. Add `<NotificationsSidebarItem />` to `Root.tsx` (according to README)
7. Add `<Route path="/notifications" element={<NotificationsPage />} />` to `App.tsx` (according to README)

### 🖥️ Your Environment

OS: Darwin (M1 Silicon) Sonoma 14.5

➜  backstage git:(main) ✗ cat backstage.json 
{
  "version": "1.27.0"
}
➜  backstage git:(main) ✗ node -v
v20.9.0
➜  backstage git:(main) ✗ yarn -v
3.3.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by mareklibra** [comment]
First thought to explore: there might be mismatch in the dependency versions.

When trying to reproduce and calling the `npx @backstage/create-app@latest` **outside** of the backstage/backstage sources, I got following error:

```
$ yarn start
yarn run v1.22.21
$ yarn workspace app start
$ backstage-cli package start
Loaded config from app-config.yaml
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
<i> [webpack-dev-server] Content not from webpack is served from '/home/mlibra/tmp/tmpbug24961/packages/app/public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
<i> [webpack-dev-middleware] wait until bundle finished: /
ERROR in ../../node_modules/material-ui-confirm/dist/material-ui-confirm.esm.js 2:0-42
Module not found: Error: Can't resolve '@mui/material/Button' in '/home/mlibra/tmp/tmpbug24961/node_modules/material-ui-confirm/dist'
```

**Comment by mareklibra** [comment]
Yet another call of `yarn install` fixed the last ^^^ issue. The Backstage UI from the `create-app` compiles and loads well for me now and I can see the Notifications page without any issue so far.

So back to the originally reported issue:
@enyineer Can you repeat your steps but **outside** of your Backstage repo? I mean call the `create-app` in i.e. `/tmp` folder.

If you see compilation or similar issues, please call `yarn install` one more time.
Did it help?

**Comment by enyineer** [comment]
Hi @mareklibra,

first of all, thanks for your help!

I have setup a completely fresh version of backstage using `npx @backstage/create-app@latest`. This creates a fresh Backstage instance of version `1.27.0` (according to `backstage.json`).

First problem I have is that the first install fails as I'm on a corporate machine with only yarn 3.3.0 available. I did migrate the fresh project according to https://backstage.io/docs/tutorials/yarn-migration.

I had to set a custom registry, as I'm also behind a corporate firewall, so my final .yarnrc.yml looked like this:

```yaml
nodeLinker: node-modules

npmRegistryServer: "<internalRegistryMirrorURL>"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
```

I ignored the Steps mentioned in https://backstage.io/docs/tutorials/yarn-migration/#migrate-usage as I don't care about the Docker build to resolve this issue.

First installation after migrating to Yarn 3 was fine. However, opening the `index.ts` of the backend package showed an error immediately:

<img width="988" alt="image" src="https://github.com/backstage/backstage/assets/27201677/df7e7de3-ca1e-4e3f-a622-f49488306a63">

I then added the package to the backend manually: `yarn add @backstage/plugin-app-backend`.

I then followed the steps 3 to 6 from my initial posting.

This time it seems to work. I have no idea what went wrong the last time I tried (even though it was also on a fresh install). Could have been some stale caches in our internal npm mirror. Thanks for suggesting to retry.

**Comment by enyineer** [comment]
I cannot really make sense of it, but after retrying in our existing Backstage project the error still persists (even after clearing the .yarn/cache and all node_modules folders). Any ideas on how to go forward with this?

**Comment by mareklibra** [comment]
@enyineerPlease make sure you do not have a `node_modules` folder in the hierarchy up the new app folder.

Then try `find . -name 'node_modules' -exec rm -rf {} \;` in your new app, followed by `yarn install`.
That works for me.

If not, I suggest to try the same without your local registries and caches.

**Comment by enyineer** [comment]
Still happens after removing all node_modules folders using your command and running a fresh install.

If I go into `packages/app/` and run `tree` inside it's node_modules folder I get
```
➜  tree -d -L 1 .
.
├── @testing-library
├── @types
├── react-use
└── throttle-debounce
```

Should those even be there and not hoisted up to the root? Looks like we do have some duplicated packages if I do correctly understand how Yarn works. I don't think these packages interfere with the package that causes this problem I think.

I do understand this Issue is now becoming some kind of StackOverflow question but I can't wrap my head around what could cause this while it works on a fresh install - even if the same corporate npm Mirror is used for that fresh install (so this can't really be the root cause). There needs to be something with our existing Backstage project causing this.

**Comment by enyineer** [comment]
Could it be that we're having some problem with the Unified Theme? As the suspected line in the Stacktrace seems to access `theme.palette.navigation.color` where `navigator` is undefined (Cannot read properties of undefined (reading 'color')).

We're providing a custom theme via `createUnifiedTheme` at `createApp` in `App.tsx` where `palette.navigation.color` is set to a specific color.

I tried removing those themes but the error persists.

**Comment by enyineer** [comment]
@freben I hope it's okay that I tag you here but do you have an educated guess what could be causing this? I tried different things like refactoring versions of the app package according to the versions of a fresh Backstage install but none of that helped. I'm totally out of guesses now.

If it's not okay to tag Maintainers to ask for help in Issues please lmk :) Thanks!

**Comment by enyineer** [comment]
@mareklibra we were actually able to fix this by setting a resolution of `@types/react` to `^17.0.0 || ^18.0.0`.

We're not quite sure yet why that does only cause problems in our existing project but not on fresh installs, but it helped in our case. The notifications plugin [does set an "older" version range](https://github.com/backstage/backstage/blob/master/plugins/notifications/package.json#L51) for that package which seems to be problematic in our existing project.
