### ISSUE TITLE
🚀 Feature: Documentation Request: Update "Input Examples" in 'Software Templates' section showing how to use placeholders 

### ISSUE THREAD

**Issue by rewixe** [backstage/backstage#24968]
### 🔖 Feature description

I would like to request updating the documentation on "Input Examples" by adding a section showing how to use placeholders to reference other YAML files from your template

### 🎤 Context

The documentation in this page which gives examples of [template inputs](https://backstage.io/docs/features/software-templates/input-examples) doesn't describe how you can make reference to remote YAML files in your template, allowing users to create smaller templates which can be referenced in your main template, potentially allowing for sections of templates to be more easily reused. Adding this information to this doc will make the experience of using this feature easier.

### ✌️ Possible Implementation

The documentation should include:

- A step-by-step guide on how to reference a YAML file from your template
- Screenshots demonstrating the process.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by rewixe** [comment]
Can this be assigned to me? I'm happy to work on this

**Comment by vinzscam** [comment]
absolutely, looking forward to the PR!

**Comment by awanlin** [comment]
Left a comment on the PR but also wanted to mention it here: https://github.com/backstage/backstage/pull/25365#issuecomment-2186473526
