### ISSUE TITLE
🐛 Bug Report: Filtering of entites using the filter provided in the CatalogIndexPage

### ISSUE THREAD

**Issue by Mortefal** [backstage/backstage#24985]
### 📜 Description

When using the filter to search for names of User entities, searching for "Guest" gives the user "Guest User", but inputing "Guest U" returns no results.

### 👍 Expected behavior

When using the filter to search for names of User entities, searching for "Guest" gives the user "Guest User", but inputing "Guest U" should return "Guest User". 

### 👎 Actual Behavior with Screenshots

<img width="1163" alt="Screenshot 2024-05-30 at 13 46 17" src="https://github.com/backstage/backstage/assets/22368613/8e7d9278-cd8a-41ac-b7c7-2a788b346cb1">
<img width="1086" alt="Screenshot 2024-05-30 at 13 46 32" src="https://github.com/backstage/backstage/assets/22368613/b1d89d98-fa49-472c-89ac-14fe04ad31e6">

Reproduced in the https://demo.backstage.io/ page.

### 👟 Reproduction steps

Go to https://demo.backstage.io/

Select kind User

Write "Guest U" in filter.

expect "Guest User" entity to be shown, but get no results.

### 📃 Provide the context for the Bug.

Trying to add the entire user base of a large organization (25k entities), with alot of users with the same first name, and need to be able to filter using lastname aswell.

### 🖥️ Your Environment

https://demo.backstage.io/ 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
yes, it looks like this bug was introduced with the entity presentation api. The column should use the entity presentation `primaryTitle` for filtering the results
