### ISSUE TITLE
🚀 Feature: Retrieve loading state from StorageApi

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#24980]
### 🔖 Feature description

StorageApi `snapshot` function returns `StorageValueSnapshot` type. This type should have an additional value for `loading` which indicates that the snapshot is loading from the storage. 

### 🎤 Context

This is necessary to detect when `@backstage/plugin-user-settings-backend` is fetching the data from the backend to display some loading indicator during the load. For the default local storage implementation, the loading value would probably be false at all times.

### ✌️ Possible Implementation

1. Add a new `loading` (optional?) boolean field to the `StorageValueSnapshot`
2. Add necessary implementation to the default and settings-backend storage options

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
For those cases, the snapshot is meant to have `presence: 'unknown'`, which essentially means that you're loading and the `observe$` observable will give you the actual value soon. Right? They work as a pair.

**Comment by drodil** [comment]
Ah, yes true, I just read the implementation of the `UserSettingsStorage`. Will close this!
