### ISSUE TITLE
🚀 Feature: Enable greater filtering on nodes in EntityRelationsGraph

### ISSUE THREAD

**Issue by jslott2sigma** [backstage/backstage#24996]
### 🔖 Feature description

Provide the ability to specify a custom filter on nodes when displaying an entity graph.

### 🎤 Context

Currently, `EntityCatalogGraph` provides the ability to filter nodes based upon `kind` and `relationship`. Often times, greater flexibility is needed by being able to filter on arbitrary attributes of an entity. For example, it is often desirable to display Components based upon their type.

### ✌️ Possible Implementation

One possible implementation is to add a `filter` function as a property to `EntityCatalogGraph` that controls whether a node is rendered. While this does not prevent entities from being loaded from the server, it's seems like a fine trade-off to do any coarse filtering using kind/relation and any fine-grained filtering using the filter function.

As an alternative, applications can supply a custom `renderNode` function and perhaps return `<div />` for nodes that it does not wish to render, however this would require forking `DefaultRenderNode`. (I have not yet tried this approach.) Another alternative is to fork `EntityCatalogGraph` entirely.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by vinzscam** [comment]
yes, it makes sense. Let's discuss this in a PR!

**Comment by dweber019** [comment]
I have a similar requirement where we like to only show nodes/entities of a certain `spec.type`.

**Comment by jslott2sigma** [comment]
@vinzscam @dweber019 Thank you! As you can see linked here, I've opened a PR with the most simple implementation I can think of. Thank you for your kind consideration and I look forward to any critique of the PR.
