### ISSUE TITLE
🐛 Backstage HeaderTabs with v1.26.0 cause breaking changes

### ISSUE THREAD

**Issue by malhotraashna** [backstage/backstage#25007]
### 📜 Description

I can see that Backstage has introduced tabs as Links in v1.26.0, with the href attribute. But with the change, you are removing leading slashes (/), and making paths relative which is breaking the navigation.

There are 2 issues,
1. If we had absolute paths before, eg. /team/members, introducing the following code change makes this path relative and so it gets appended to the URL and doesn't redirects to the correct page.
    ```
    // HeaderTabs.tsx

    function removeLeadingSlash(path: string) {
        return path.replace(/^\//, '');
      }
    ...
    component={Link}
    to={removeLeadingSlash(tab.id)}
    ...
    ```
2. If I change it to relative path, if it is outside of nested Routes, it works fine. But if it is in a route element component, the redirection doesn't work anymore. Though if we use the absolute path, and the leading slash is not removed, it works.

### 👍 Expected behavior

I wanted to understand the reason of introducing the method to remove leading slashes and make the path relative on purpose. Ideally, it should redirect to the correct path no matter if we pass absolute or relative path.

### 👎 Actual Behavior with Screenshots

It appends the path in the URL,

<img width="857" alt="Screenshot 2024-05-31 at 16 22 50" src="https://github.com/backstage/backstage/assets/26295917/72ac0ae3-cfd9-4cf0-860b-785f9a3c7903">

### 👟 Reproduction steps

For any HeaderTab implementation,

1. When I pass absolute path,

    ```
    const tabs = [
      { label: 'Tab 1', path: '/plugin-name' },
      { label: 'Tab 2', path: '/plugin-name/coverage' },
      { label: 'Tab 3', path: '/plugin-name/tab-3' },
    ];
    ...
    <HeaderTabs
          selectedIndex={selectedIndex}
           tabs={tabs.map(({ label, path, tabProps }) => ({
            id: path,
            label,
            tabProps,
          }))}
    />
    ```

2. The issue remains the same even when I have relative paths,

    ```
    const tabs = [
      { label: 'Tab 1', path: '' },
      { label: 'Tab 2', path: 'coverage' },
      { label: 'Tab 3', path: 'tab-3' },
    ];
    ...
    <HeaderTabs
          selectedIndex={selectedIndex}
           tabs={tabs.map(({ label, path, tabProps }) => ({
            id: path,
            label,
            tabProps,
          }))}
    />
    ```
    
For 2, the issue occurs when I use the above code inside `Content.tsx` from below (because Content gets re-rendered on click of tab and it updates the href),
    
    ```
    <Routes>
      <Route path="/" element={<DashboardContent />} />
      <Route
        path="/content"
        element={<Content />}
      />
    </Routes>
    ```

### 🖥️ Your Environment

OS:   Darwin 23.4.0 - darwin/arm64
node: v18.18.0
yarn: 1.22.19
cli:  0.26.6 (installed)
backstage:  1.27.5

@backstage/core-components: 0.14.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by vinzscam** [comment]
The fix was related to https://github.com/backstage/backstage/issues/19912

I'm trying to understand why you would want to use absolute path in Tabs. Ideally Tabs should only have paths relative to the current page, right?

**Comment by malhotraashna** [comment]
@vinzscam Apologies for the delay in response.
If you look through the reproduction steps, the issue remains for relative paths too. An alternative to bypass this issue with relative path was to use absolute path but that is also not possible.
I am not sure if the approach to use tabs inside Route elements is correct or not, but we have some use-cases where we do so.

**Comment by malhotraashna** [comment]
@vinzscam Did you get a chance to look into the issue? And does my answer above makes sense to you?

**Comment by malhotraashna** [comment]
@tudi2d @benjdlambert I see that you guys were part of the review process for the MR where `removeLeadingSlash` was introduced. Maybe you can provide some help. We are blocked from upgrading Backstage because of this issue.

**Comment by vinzscam** [comment]
sorry @malhotraashna but I can't reproduce the issue as it works fine for me.

This is the code of my `App.tsx`:

```tsx
const routes = (
  <FlatRoutes>
     ...
     <Route path="/content" element={<Content />} />
  </FlatRoutes>    
);
  
  
function Content() {
  const tabs = [
    { label: 'Tab 1', path: '', tabProps: {} },
    { label: 'Tab 2', path: 'coverage' },
    { label: 'Tab 3', path: 'tab-3' },
  ];

  const [selectedTab, setSelectedTab] = useState(0);

  return (
    <>
      <HeaderTabs
        tabs={tabs.map(({ label, path, tabProps }) => ({
          id: path,
          label,
          tabProps,
        }))}
        selectedIndex={selectedTab}
        onChange={index => setSelectedTab(index)}
      />
      <div>Selected tab: {tabs[selectedTab].label}</div>
    </>
  );
}
```

here is a recording:

https://github.com/backstage/backstage/assets/8433119/a3afcfaf-a9bb-46aa-a13e-da163b199de3

you said that your `Content` component gets re-rendered once a tab is clicked, could it be you are doing something different internally in the component?

**Comment by malhotraashna** [comment]
@vinzscam I've tried to reproduce it [here](https://github.com/malhotraashna/header-tab-demo).

Please let me know if you see something that should be different in the implementation.

https://github.com/backstage/backstage/assets/26295917/514dad65-ecce-4412-997b-d560bc6c5220

**Comment by vinzscam** [comment]
that's expected!
You are rendering `<PageTabs />` in different routes, which means that every time a route is selected, the current `<PageTabs />` gets unmounted and another one renders. So this is the flow:

1. `/demo` page gets rendered, fine
2. You press the `Results` tab which forwards you from `/demo` to `/demo/results`.
3. At this point the results page is rendered and another HeaderTabs is rendered.
4. You press the `Scenario` tab, which forwards you from the current "home" (`/demo/results`) to `/demo/results/scenarios` due to the fact that the root of `HeaderTabs` is `/demo/results`.

So to fix the issue you need to transform your component to something like:

```tsx
export const ExampleComponent = () => (
<>
  <HeaderTabs ... />
  <Routes>
    <Route path="/" element={<ServicesPage />} />
    <Route path="/scenarios" element={<ScenarioPage />} />
    <Route path="/results" element={<ResultsPage />} />
  </Routes>
</>
);
```

**Comment by malhotraashna** [comment]
@vinzscam I get it. And we tried to do the same for simple cases.
This is just a reproduction of the issue that I did for you. There are cases, where we have tabs inside tabs, and the routes are definitely defined in a single place. 

However, I still do not understand a good reason to explicitly remove the slashes from the path being sent in props. This way the path gets treated completely different from what the developer may want it to be. So, we are not left with any freedom to use the path and tabs in the way we want.

**Comment by vinzscam** [comment]
we are happy to look into any issue you might find within the component, but so far everything looks good.

**Comment by malhotraashna** [comment]
Thanks for looking into it @vinzscam. 
Looks like we will need to create our custom tabs in this case, as the implementation looks buggy for extended use-cases.

**Comment by vinzscam** [comment]
if you can provide some examples of your extended use cases we can look into it to see if there is any issue

**Comment by malhotraashna** [comment]
@vinzscam Sure. As mentioned before, one of the use case is when we have tabs inside tabs.

- There are HeaderTabs which act as primary navigation for the plugin.
- Then inside of the parent tab, we have set of tabs again, for the secondary navigation of that tab.
- Routes for all the paths are defined at a single place, i.e. in the Home component of the plugin.

Now, before you introduced changes with HeaderTabs, we were using absolute path to redirect to the correct path for the secondary tabs. So even when due to re-rendering of tabs, the current "home" url was changing, use of absolute path helped us redirect to the correct path.
We do not want to specify our routes for each instance of HeaderTabs, instead want to keep doing it at a single place. Does that help to understand?

**Comment by camilaibs** [comment]
Thanks for sharing @malhotraashna. I added a "needs-discussion" label to review the extended uses cases with our team.

**Comment by Rugvip** [comment]
Just wanna chime in quick here that I'm a bit confused about the recent changes to `HeaderTabs`, since we also have `RoutedTabs` and `TabbedLayout` for the case where tabs are used for navigation. It might be that we want to move over the use of the `Link` component in the tabs over there.

**Comment by malhotraashna** [comment]
@camilaibs I see the needs discussion label has been removed. Can you please share any update here too?

**Comment by camilaibs** [comment]
@malhotraashna the latest update is the @Rugvip comment 🙂

**Comment by benjdlambert** [comment]
I think that we should back out the previous change, and provide additional `TabProps` from `RoutedTabs` instead, I can whip up a PR for this.
