### ISSUE TITLE
🐛 Bug Report: 1.27.5: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#25006]
### 📜 Description

After upgrading to Backstage 1.27.5 the webpack compilation gives a warning that is almost impossible to trace where it comes from. This relates to the `resolvePackagePath` function at https://github.com/backstage/backstage/blob/855201c744ff8cdde6d95a5e4d9233ca290d05d2/packages/backend-plugin-api/src/paths.ts#L38

### 👍 Expected behavior

No warning shown

### 👎 Actual Behavior with Screenshots

```
[1] WARNING in ../../node_modules/@backstage/backend-plugin-api/dist/cjs/paths-D7KGMZeP.cjs.js 17:63-70
[1] Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
[1] 
[1] webpack compiled with 1 warning
```

### 👟 Reproduction steps

No idea, just happens in our Backstage instance after 1.27.5 update.

### 📃 Provide the context for the Bug.

I did change in my local compiled version of the paths.ts to only use `require` function without checking the `__non_webpack_require__` existence and the warning disappeared. As an example:

```diff
-const req = typeof __non_webpack_require__ !== "undefined" ? __non_webpack_require__ : require;
-return path.resolve(req.resolve(`${name}/package.json`), "..", ...paths);
+return path.resolve(require.resolve(`${name}/package.json`), "..", ...paths);
```

Related SO discussion: https://stackoverflow.com/questions/46185302/non-webpack-require-is-not-defined

### 🖥️ Your Environment

OS:   Darwin 23.5.0 - darwin/arm64
node: v18.19.0
yarn: 1.22.19
cli:  0.26.6 (installed)
backstage:  1.27.5

Dependencies:
  @backstage/app-defaults                                            1.5.5
  @backstage/backend-app-api                                         0.7.5
  @backstage/backend-common                                          0.22.0
  @backstage/backend-defaults                                        0.2.18
  @backstage/backend-dev-utils                                       0.1.4
  @backstage/backend-openapi-utils                                   0.1.11
  @backstage/backend-plugin-api                                      0.6.18
  @backstage/backend-tasks                                           0.5.23
  @backstage/backend-test-utils                                      0.3.8
  @backstage/catalog-client                                          1.6.5
  @backstage/catalog-model                                           1.5.0
  @backstage/cli-common                                              0.1.13
  @backstage/cli-node                                                0.2.5
  @backstage/cli                                                     0.26.6
  @backstage/config-loader                                           1.8.0
  @backstage/config                                                  1.2.0
  @backstage/core-app-api                                            1.12.5
  @backstage/core-compat-api                                         0.2.5
  @backstage/core-components                                         0.14.7
  @backstage/core-plugin-api                                         1.9.2
  @backstage/dev-utils                                               1.0.32
  @backstage/e2e-test-utils                                          0.1.1
  @backstage/errors                                                  1.2.4
  @backstage/eslint-plugin                                           0.1.8
  @backstage/frontend-plugin-api                                     0.6.5
  @backstage/integration-aws-node                                    0.1.12
  @backstage/integration-react                                       1.1.27
  @backstage/integration                                             1.11.0
  @backstage/plugin-api-docs                                         0.11.5
  @backstage/plugin-app-backend                                      0.3.67
  @backstage/plugin-app-node                                         0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider           0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider             0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider      0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider           0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider   0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider             0.2.13
  @backstage/plugin-auth-backend-module-github-provider              0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider              0.1.15
  @backstage/plugin-auth-backend-module-google-provider              0.1.15
  @backstage/plugin-auth-backend-module-guest-provider               0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider           0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider              0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider        0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider                0.1.9
  @backstage/plugin-auth-backend-module-okta-provider                0.0.11
  @backstage/plugin-auth-backend                                     0.22.5
  @backstage/plugin-auth-node                                        0.4.13
  @backstage/plugin-auth-react                                       0.1.2
  @backstage/plugin-catalog-backend-module-aws                       0.3.13
  @backstage/plugin-catalog-backend-module-github-org                0.1.13
  @backstage/plugin-catalog-backend-module-github                    0.6.1
  @backstage/plugin-catalog-backend-module-msgraph                   0.5.26
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model   0.1.16
  @backstage/plugin-catalog-backend-module-unprocessed               0.4.5
  @backstage/plugin-catalog-backend                                  1.22.0
  @backstage/plugin-catalog-common                                   1.0.23
  @backstage/plugin-catalog-graph                                    0.4.5
  @backstage/plugin-catalog-node                                     1.12.0
  @backstage/plugin-catalog-react                                    1.12.0
  @backstage/plugin-catalog-unprocessed-entities-common              0.0.1
  @backstage/plugin-catalog-unprocessed-entities                     0.2.4
  @backstage/plugin-catalog                                          1.20.0
  @backstage/plugin-devtools-backend                                 0.3.4
  @backstage/plugin-devtools-common                                  0.1.9
  @backstage/plugin-devtools                                         0.1.14
  @backstage/plugin-events-backend-module-github                     0.2.4
  @backstage/plugin-events-backend                                   0.3.5
  @backstage/plugin-events-node                                      0.3.4
  @backstage/plugin-home-react                                       0.1.13
  @backstage/plugin-home                                             0.7.4
  @backstage/plugin-kubernetes-common                                0.7.6
  @backstage/plugin-notifications-backend                            0.2.1
  @backstage/plugin-notifications-common                             0.0.3
  @backstage/plugin-notifications-node                               0.1.4
  @backstage/plugin-notifications                                    0.2.1
  @backstage/plugin-org                                              0.6.25
  @backstage/plugin-permission-backend                               0.5.42
  @backstage/plugin-permission-common                                0.7.13
  @backstage/plugin-permission-node                                  0.7.29
  @backstage/plugin-permission-react                                 0.4.22
  @backstage/plugin-proxy-backend                                    0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                  0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud        0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server       0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket              0.2.8
  @backstage/plugin-scaffolder-backend-module-confluence-to-markdown 0.2.19
  @backstage/plugin-scaffolder-backend-module-cookiecutter           0.2.42
  @backstage/plugin-scaffolder-backend-module-gerrit                 0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                  0.1.8
  @backstage/plugin-scaffolder-backend-module-github                 0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab                 0.4.0
  @backstage/plugin-scaffolder-backend                               1.22.7
  @backstage/plugin-scaffolder-common                                1.5.2
  @backstage/plugin-scaffolder-node-test-utils                       0.1.4
  @backstage/plugin-scaffolder-node                                  0.4.4
  @backstage/plugin-scaffolder-react                                 1.8.6
  @backstage/plugin-scaffolder                                       1.20.1
  @backstage/plugin-search-backend-module-catalog                    0.1.24
  @backstage/plugin-search-backend-module-elasticsearch              1.4.1
  @backstage/plugin-search-backend-module-techdocs                   0.1.23
  @backstage/plugin-search-backend-node                              1.2.23
  @backstage/plugin-search-backend                                   1.5.9
  @backstage/plugin-search-common                                    1.2.11
  @backstage/plugin-search-react                                     1.7.11
  @backstage/plugin-search                                           1.4.11
  @backstage/plugin-signals-backend                                  0.1.4
  @backstage/plugin-signals-node                                     0.1.4
  @backstage/plugin-signals-react                                    0.0.3
  @backstage/plugin-signals                                          0.0.6
  @backstage/plugin-techdocs-backend                                 1.10.5
  @backstage/plugin-techdocs-node                                    1.12.4
  @backstage/plugin-techdocs-react                                   1.2.4
  @backstage/plugin-techdocs                                         1.10.5
  @backstage/plugin-user-settings-backend                            0.2.17
  @backstage/plugin-user-settings                                    0.8.6
  @backstage/release-manifests                                       0.0.11
  @backstage/repo-tools                                              0.9.0
  @backstage/test-utils                                              1.5.5
  @backstage/theme                                                   0.5.5
  @backstage/types                                                   1.1.1
  @backstage/version-bridge                                          1.0.8
✨  Done in 2.13s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
Pinging @Rugvip here as well 🥹

**Comment by Rugvip** [comment]
Somehow `@backstage/backend-plugin-api` is being brought into the frontend build, which is the root cause of this issue. Changing the code where the error is thrown might un-break the build but won't fix the underlying issue.

What we'll really need is a version of our [dependency checking script](https://github.com/backstage/backstage/blob/cb11e2ce018c591db76eb2a3e6821aedf853c962/scripts/verify-local-dependencies.js) that's built into the CLI build process. Not quite as extensive though, it just needs to check that there are no package role conflicts. I'll give it a few min to see if it's a simple fix.

**Comment by drodil** [comment]
Yeah, that's what I though was the root cause for this as well (or actually it could be some other backend package too). I tried the script and found some issues, and fixed those, but still couldn't get it working. Have to keep digging.

**Comment by drodil** [comment]
Ahaa, the script doesn't check for invalid dependencies if the source role is `backend-plugin-module`. Added this to our fork of the script and found some more issues :D

**Comment by freben** [comment]
If you find something that can be improved in the OSS script, we'd of course love to see it too :)

**Comment by drodil** [comment]
Would be nice to have this as part of the `backstage-cli` as well :)

**Comment by Rugvip** [comment]
Got as far as thinking that we should add a check to the package build command here: https://github.com/backstage/backstage/blob/fe1a55efe4d2c21fe8bbf33893d05f96905d2805/packages/cli/src/commands/build/command.ts#L27-L28. I was aiming to use the `PackageGraph` util only, but while it can be used for the workspace deps I think we should also check the package roles one level down into `node_modules`. I.e. if a local package has an incompatible dependency on something from NPM, we'd fail the build, but we don't check deeper than that. Since the package graph util only cares about workspace package we'll also need to load in the `package.json` manually as well.

**Comment by luyc31** [comment]
Hi all - are there any updates on this?
