### ISSUE TITLE
🐛 Bug Report: Techdocs Code block copy to clipboard text overlapped with code

### ISSUE THREAD

**Issue by ziqgrab** [backstage/backstage#25002]
### 📜 Description

It bugs out when we have long single line of code in code block. When I clicked on the copy button, the text 'Copy to clipboard' overlapped with the code behind.

### 👍 Expected behavior

not overlap with the code behind will be nice, maybe just show a 'copied' text on top once user clicked the copy button

### 👎 Actual Behavior with Screenshots

![CleanShot 2024-05-31 at 15 16 49@2x](https://github.com/backstage/backstage/assets/161662717/9beef1dc-3af2-4a62-b534-3c0c5d007a48)

### 👟 Reproduction steps

1. Create a techdocs
2. Add a codeblock in that md file with long single line
3. Run techdocs-cli serve

### 📃 Provide the context for the Bug.

Small minor issue, but a lot of our users complaining about this issue.

### 🖥️ Your Environment

OS:   Darwin 23.4.0 - darwin/arm64
node: v18.19.1
yarn: 1.22.19
cli:  0.26.4 (installed)
backstage:  1.24.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by anmol-fzr** [comment]
Hi I'm interested to Work on this issue, please assign me this.

**Comment by vinzscam** [comment]
Sure, open a PR so that we can discuss 👍
