### ISSUE TITLE
💬 RFC: Documentation on how to install SSL certificates for HTTPS

### ISSUE THREAD

**Issue by cliffAtOsaic** [backstage/backstage#25009]
### 🔖 Need

I have searched and reviewed the documentation at Backstage.io and I cannot find instructions on how to install SSL certificates to enable HTTPS.  HTTPS is required by Azure Entra ID for authentication.

### 🎉 Proposal

Document how to install SSL certificates for Backstage.

### 〽️ Alternatives

Searching the internet for explanations or examples.

### ❌ Risks

None

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by benjdlambert** [comment]
Hey :wave: thanks for raising this!

So normally we'd recommend putting some form of SSL termination proxy or load balancer in front of the Backstage deployment which can take care of keeping the keys etc secure for you and out of the concerns of Backstage, but you can provide a `backend.https` config in `app-config.yaml` to do this at the Backstage backend server level if desired.

You can either provide `backend.https: true` to generate self-signed certs which is good for local development, or you can provide a key/cert pair instead: https://github.com/backstage/backstage/blob/master/packages/backend-common/config.d.ts#L49-L68

**Comment by cliffAtOsaic** [comment]
> Hey 👋 thanks for raising this!
> 
> So normally we'd recommend putting some form of SSL termination proxy or load balancer in front of the Backstage deployment which can take care of keeping the keys etc secure for you and out of the concerns of Backstage, but you can provide a `backend.https` config in `app-config.yaml` to do this at the Backstage backend server level if desired.
> 
> You can either provide `backend.https: true` to generate self-signed certs which is good for local development, or you can provide a key/cert pair instead: https://github.com/backstage/backstage/blob/master/packages/backend-common/config.d.ts#L49-L68
> 
> It's possible that the latter approach isn't really documented, so if you find something that works and with to contribute, we'd appreciate a contribution to add this to the docs 🙏

Thanks!  This points me in the right direction.  I was looking for the config.d.ts file you referenced in the link and I can't find it in my local app anywhere.  In fact, there is no backend-common directory under backstage/packages in my repo.

I assume I can simply create the file, but what is the proper location for it?

**Comment by benjdlambert** [comment]
@cliffAtOsaic sorry, the file I linked is something that we provide as a library, and you will already have this installed, this is just the config scheme of what you can provide in your `app-config.yaml`

The config should be placed in `app-config.yaml` like this:

```yaml
...
backend:
  https: true
...
```

Or by providing key/pairs:

```yaml
...
backend:
  https:
    certificate:
      cert: 
        $file: ./path/to/cert.pem
      key:
        $file: ./path/to/key.pem
...
```

**Comment by cliffAtOsaic** [comment]
Thank you!  I finally got this working.

Part of the problem was I didn't realize my Private Key was still encrypted.  Decrypting the private key was required.

The other part was I had the certificate information in the wrong section.

Cheers!  Appreciate the help!

**Comment by kentwongg** [comment]
@benjdlambert  I am trying to get the second solution working but having path issues.

I'd love to open a PR and add it to the documentation later if I can figure this out. 

I am getting:

`Error: Failed to read config file at "/app/app-config.production.yaml", error at .backend.https.certificate.cert, failed to read file ./cert.pem, NotFoundError: failed to include "/app/cert.pem", file does not exist
`

My `app-config.production.yaml`:

```
  https:
    certificate:
      cert:
        $file: ./cert.pem
      key:
        $file: ./key.pem
```

Inside my project, I've added the .PEM files to `packages/app/` but I don't think thats the right spot. Using docker to run the backstage so I'm thinking I need to bundle it, thats my assumption right now.

**Comment by benjdlambert** [comment]
Can you try place them in `packages/backend` folder instead?

The config files are relative from where the backend process runs I believe.

**Comment by kentwongg** [comment]
No good. 

I've tried placing the certs in the root of the directory, and inside `packages/app/` and `packages/backend/` 

It's odd that the error message appends `/app/` in front of the path, unless it's expecting an `app` folder inside `packages/backend/` ?
