### ISSUE TITLE
🚀 Feature: If statement in catalog-info.yaml

### ISSUE THREAD

**Issue by 63070054** [backstage/backstage#25018]
### 🔖 Feature description

I want to create a 1 template.yaml which will has a checkbox, each checkbox represent to a repository. So If I check 5 checkbox, This will create a new 5 repository and 6 catalog component and 5 catalog represent 5 repository and the last one is the main catalog component will has subComponent of this 5 catalog component. My question is can we add some if statement in catalog-info.yaml for has subComponent depends on amount of checkbox that user select.

### 🎤 Context

Because I have a lot of repository for only 1 project. So when we want to create a new project, we don't want to repeat to do the same thing a lot due to now i have only 1 template per 1 repository so I need to repeat to do the same thing a lot of time.

### ✌️ Possible Implementation

- If statement in catalog-info.yaml
- if statement in output part in template.yaml
or maybe can we trigger another template steps by one template so it would be easier to implement.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Think we need a little more detail here to really understand what you're trying to do.

But you can use the `each:` property in the `step` definitions to iterate over a list of things and execute the step for each of them.

**Comment by 63070054** [comment]
Sorry for not update the current situation. Now I am using each and it works perfectly but I want to group the component together but I am not sure how to do it because the amount of component that want to group depends on what is user gonna select. Any suggestion ?

**Comment by 63070054** [comment]
For me I think we should can do something like this
annonations:
     sonarqube.org/project-key:
             value: ${{ values.sonarProjectKey }}
             if: ${{ values.sonarProjectKey }}
      dev.azure.com/project
             value: ${{ values.azureProjectName }}
             if:  ${{ values.azureProjectName }}
      dev.azure.com/build-definition
             value: ${{ values.azureProjectName }}
             if: ${{ values.azureProjectName }}

**Comment by benjdlambert** [comment]
Oh ok, I think that the [nunjucks](https://mozilla.github.io/nunjucks/templating) documentation might be useful here.

You can do things like this:

```yaml
annotations:
{% if values.sonarProjectKey %}
  ${{ values.sonarProjectKey }}
{% endif %}
```
