### ISSUE TITLE
🐛 Bug Report: Secrets redaction not working with 1.27

### ISSUE THREAD

**Issue by floric** [backstage/backstage#25022]
### 📜 Description

Hey @benjdlambert , we tried the new release 1.27.2 with various secrets, safed in the secrets-scope with fetch:template and debug:log. Unfortunately, in comparison to our latest used release 1.26.2 now all secrets are logged. None of them are redacted. Before, at least some were marked as redacted.

Apart from the upgrade to 1.27 we didn't change anything. So unfortunately something must have been broken. I also looked into the changes in https://github.com/backstage/backstage/pull/24478 but couldn't find any problem so far.

Also check https://github.com/backstage/backstage/issues/24144

### 👍 Expected behavior

all secrets are redacted

### 👎 Actual Behavior with Screenshots

none are redacted after upgrade to 1.27.2

### 👟 Reproduction steps

1. Define secret parameters like in #24144
2. Log secrets
3. None are redacted

### 📃 Provide the context for the Bug.

The redaction worked partially in 1.26 but seems to be broken in 1.27. We tested it with two independent upgrades on two local dev setups.

### 🖥️ Your Environment

Not relevant

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by floric** [comment]
cc @dariozachow

**Comment by benjdlambert** [comment]
Hmm, we're unable to reproduce this locally. Whats you setup? When is it not logging the redacations, what secrets are you seeing logged and how are they set? Are you on the new backend system or old?
