### ISSUE TITLE
🚀 Feature: Allow decimal numbers in Gauge component

### ISSUE THREAD

**Issue by fabian-m-95** [backstage/backstage#25026]
### 🔖 Feature description

In the Gauge component, the large number in the middle should be able to display decimal numbers, such as "5.5".

### 🎤 Context

In my use-case, I want to display a value between 0 and 10. While the fill percentage of the circle is calculated correctly (5.5/10 yields 55% filling), the value displayed is rounded to 6, which is not acceptable for me.

### ✌️ Possible Implementation

The displayed value is rounded when the maximum is not 100 (see https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/ProgressBars/Gauge.tsx#L138). Since I do not know the intention behind that, I will keep this behavior.

I plan to add a new parameter ("decimalDigits" or the like), which I can set to 1 for my use-case (to yield "5.5" or "7.0"). If it is not set, the old behavior will be used to be backwards compatible.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
```[tasklist]
### Tasks
- [x] Implementation
- [ ] Documentation
```

**Comment by freben** [comment]
fixed!
