### ISSUE TITLE
🚀 Feature: <title> Load template from backend plugin

### ISSUE THREAD

**Issue by quan1997ap** [backstage/backstage#25030]
### 🔖 Feature description

Hi team.
I want to build feature.When I create component,  It can auto trigger call External API and auto register new component to Backstage.

Or backstage action can call existing API of backstage backend plugin. 

And I don't want use git to store yaml file. I want store yaml file in data base of backstage plugin.

Thank you. Sr about my english.

![image](https://github.com/backstage/backstage/assets/38683698/4c9dff6e-b63f-47e7-af6d-46c46958eb54)

### 🎤 Context

no

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey :wave:

So I'm not 100% sure on what you want to be able to do here.

Are you wanting to add things to the catalog without creating a `catalog-info.yaml` file in GitHub and using the scaffolder to do it?
