### ISSUE TITLE
🚀 Feature: Opentelemetry Support for Analytics Plugin

### ISSUE THREAD

**Issue by vanugrah** [backstage/backstage#25045]
### 🔖 Feature description

Hey folks - Opentelemetry Client SIG / opentemetry-js has made significant progress this year. 
Given that the Backstage backend observability is entirely Otel based - might I recommend adding Opentelemetry as an implementation option for the Analytics Plugin? 

https://backstage.io/docs/plugins/analytics/#supported-analytics-tools

### 🎤 Context

Having Opentelemtry as an option across the board makes it easier for teams to own/operate a single backend. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @vanugrah, I'm curious about this. Can you share some examples where Otel is being used as a replacement for tools like Google Analytics or the [other supported analytics tools](https://backstage.io/docs/plugins/analytics/#supported-analytics-tools)? Mostly asking as I didn't know this was something that Otel would support and my searches are coming up empty.

**Comment by vanugrah** [comment]
Hey @awanlin  - check out this talk from Kubecon EU earlier this year: 
https://www.youtube.com/watch?v=l2_wsvv-Rhs&amp;ab_channel=CNCF%5BCloudNativeComputingFoundation%5D

**Comment by awanlin** [comment]
Thanks for the link @vanugrah, took a quick look but I'm still not sure how Otel would provide the functionality that Google Analytics provides. To be clear I'd be happy for alternatives, GA is not ideal for a lot of Backstage Adopters, I've been in this spot myself. What I don't see is how can I use Otel to tell me how many visitors I have, what areas of the application are they visiting, what are the most used plugins, can I setup funnels, etc.
