### ISSUE TITLE
🚀 Feature: Add created/updated at value field as part of the metadata shape of the final_entity

### ISSUE THREAD

**Issue by C-RoblesAutodesk** [backstage/backstage#25044]
### 🔖 Feature description

Our team is looking to find a way to show our customers the create/update date of the entity, this helps customers and the development team to get an understanding of whether an entity was recently updated or not, when a user updates their entity takes time to see the new changes reflected, but users get confused since they don't understand update times if we show the entity date users will be aware that changes haven't reflected yet, this also helps to get context over the creation date and if something is wrong with the entity when registering, or if is register with wrong metadata, we can get the logs by finding by created at value or updated at, since these values are part of the database and is more complex to get a look over that, than just looking by the entity data.

### 🎤 Context

Show customers and developers when the entity was manipulated so any error or in case the entity hasn't been updated with latest changes, everyone can know that the latest changes still not part of the UI.

### ✌️ Possible Implementation

Looking at how you shape the entities after being processed, I believe we can use the same process to attach these values so can be ingested by users in the UI like the other metadata values, ex - UID & ETAG which are not part of the original entity, but are added as part of the metadata at the final shape.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
I think that overall this makes sense, thinking that it could be either dedicated endpoint for each entity which returns information similar to a `/debug` endpoint with things more internal, like `last_stitched_at` or it could be exposed with `annotations` like `backstage.io/last-updated-at`.

We're going to be looking at doing some more work around observability in the catalog later on this year, so we've added it to the milestone, but if you're wanting to throw a PR together which works in one direction we would be happy for contributions of course :pray:

**Comment by darylgraham** [comment]
Another option here is to add a “post-stitching” step that does a diff of the newly stitched entity against the previous version of the final entity. That way you can record when the metadata last changed, not just the last stitch time. It becomes more of an auditing field than a general debug field.

I also suspect that having a point in the entity flow where we can inspect and potentially modify an entity before it replaces the previous version would open up some interesting possibilities. Something like a CI pipeline where an entity can be validated against “merge checks” and blocked from updating if it does not pass. But that’s a different RFC for another day…
