### ISSUE TITLE
🚀 Feature: Keep comments from catalog-info skeleton

### ISSUE THREAD

**Issue by fedy97** [backstage/backstage#25041]
### 🔖 Feature description

Let's say I want to generate some entities' catalog-info from my skeleton's catalog-info, and I want to show comments that I wrote in the skeleton catalog-info in my entities' catalog-info. By turning a flag from configuration, it can be decided if comments are to be ignored or to be copied in the entity's catalog-info.

### 🎤 Context

Maybe I want that every entity created from my skeleton has some comments before some specific properties, that explain its functionality

### ✌️ Possible Implementation

in the `fetch:template` action, add a way to not ignore the comments inside the skeleton catalog-info, to be enabled from configuration

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey :wave: 

I think that you could perhaps wrap up the comments in blocks in nunjucks.

```yaml
{% if values.showComments %}
# this is something nice
{% endif %}
kind: Test
```

And then passing `showComments` to the `fetch:template` action would show and hide them. I'm not sure that we would want to add comment parsing as something native unfortunately, as all comment syntaxes are different for different languages, and the template skeleton files are not even valid files to parse without rendering them first. Could get quite complex.
