### ISSUE TITLE
💬 RFC: Change the source location from 1 - N to 1 - 1

### ISSUE THREAD

**Issue by luis-guts** [backstage/backstage#25059]
### 🔖 Need

Today we're facing a delay to sync the github teams with the backstage groups. We have 600+ github teams and i think the model 1 location source to all teams is the delay cause. If already existis alternatives to avoid this issue let me know and I close the RFC

### 🎉 Proposal

Create a way to configure to use 1 location source by team. Without broke the actual model

### ❌ Risks

The actual model stop working

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
Are you using the GitHub org processor? In that case I'd recommend moving to the org data provider instead: https://backstage.io/docs/integrations/github/org

**Comment by benjdlambert** [comment]
@luis-guts how does the GitHub org data get into the catalog initially?

**Comment by camilaibs** [comment]
Hi @luis-guts, could you provide more details on when the delay occurs and how often it is scheduled to run?
