### ISSUE TITLE
🐛 Bug Report: Location Is Registered But Component Does Not Appear In Catalog. 

### ISSUE THREAD

**Issue by charlesoscar** [backstage/backstage#25053]
### 📜 Description

A user registered an entity from GitHub and then tried to register the same entity from Azure DevOps.
The entity was not receiving updates from Azure DevOps since the entity from GitHub was still present. 

The GitHub repository was removed and the entity was unregistered from the catalog. 
Even though there is a location registered for Azure DevOps, the entity from Azure DevOps does not appear in the catalog.

### 👍 Expected behavior

Entity from Azure DevOps should appear in the catalog when there is a location registered. 

### 👎 Actual Behavior with Screenshots

Entity does not appear in the catalog, even though there is a location registered. 

### 👟 Reproduction steps

1. User register Component from GitHub called 'entity-x'
2. User tries to register 'entity-x'  from Azure DevOps Repos 
3. User Removes GitHub Repo
4. User Unregisters 'entity-x' from catalog. 
![image](https://github.com/backstage/backstage/assets/6524677/fea87485-801d-41c9-bffa-8a435c4f66a5)
5. User refresh Azure DevOps location for 'entity-x'
6. 'entity-x' does not appear in catalog. 

### 🖥️ Your Environment

OS:   Windows_NT 10.0.22621 - win32/x64
node: v18.17.1
yarn: 1.22.19
cli:  0.26.6 (installed)
backstage:  1.27.4

Dependencies:
  @backstage/app-defaults                                            1.5.5
  @backstage/backend-app-api                                         0.7.5
  @backstage/backend-common                                          0.21.7, 0.22.0
  @backstage/backend-defaults                                        0.2.18
  @backstage/backend-dev-utils                                       0.1.4
  @backstage/backend-openapi-utils                                   0.1.11
  @backstage/backend-plugin-api                                      0.6.18
  @backstage/backend-tasks                                           0.5.23
  @backstage/backend-test-utils                                      0.3.8
  @backstage/catalog-client                                          1.6.5
  @backstage/catalog-model                                           1.5.0
  @backstage/cli-common                                              0.1.13
  @backstage/cli-node                                                0.2.5
  @backstage/cli                                                     0.26.6
  @backstage/config-loader                                           1.8.0
  @backstage/config                                                  1.2.0
  @backstage/core-app-api                                            1.12.5
  @backstage/core-compat-api                                         0.2.5
  @backstage/core-components                                         0.13.10, 0.14.7
  @backstage/core-plugin-api                                         1.9.2
  @backstage/dev-utils                                               1.0.32
  @backstage/errors                                                  1.2.4
  @backstage/eslint-plugin                                           0.1.8
  @backstage/frontend-plugin-api                                     0.6.5
  @backstage/integration-aws-node                                    0.1.12
  @backstage/integration-react                                       1.1.27
  @backstage/integration                                             1.11.0
  @backstage/plugin-api-docs                                         0.11.5
  @backstage/plugin-app-backend                                      0.3.67
  @backstage/plugin-app-node                                         0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider           0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider             0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider      0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider           0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider   0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider             0.2.13
  @backstage/plugin-auth-backend-module-github-provider              0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider              0.1.15
  @backstage/plugin-auth-backend-module-google-provider              0.1.15
  @backstage/plugin-auth-backend-module-microsoft-provider           0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider              0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider        0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider                0.1.9
  @backstage/plugin-auth-backend-module-okta-provider                0.0.11
  @backstage/plugin-auth-backend                                     0.22.5
  @backstage/plugin-auth-node                                        0.4.13
  @backstage/plugin-auth-react                                       0.1.2
  @backstage/plugin-catalog-backend-module-azure                     0.1.38
  @backstage/plugin-catalog-backend-module-github                    0.6.1
  @backstage/plugin-catalog-backend-module-msgraph                   0.5.26
  @backstage/plugin-catalog-backend-module-openapi                   0.1.36
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model   0.1.16
  @backstage/plugin-catalog-backend-module-unprocessed               0.4.5
  @backstage/plugin-catalog-backend                                  1.22.0
  @backstage/plugin-catalog-common                                   1.0.23
  @backstage/plugin-catalog-graph                                    0.4.5
  @backstage/plugin-catalog-import                                   0.11.0
  @backstage/plugin-catalog-node                                     1.12.0
  @backstage/plugin-catalog-react                                    1.12.0
  @backstage/plugin-catalog-unprocessed-entities-common              0.0.1
  @backstage/plugin-catalog-unprocessed-entities                     0.2.4
  @backstage/plugin-catalog                                          1.20.0
  @backstage/plugin-events-node                                      0.3.4
  @backstage/plugin-home-react                                       0.1.13
  @backstage/plugin-home                                             0.7.4
  @backstage/plugin-kubernetes-backend                               0.17.1
  @backstage/plugin-kubernetes-common                                0.7.6
  @backstage/plugin-kubernetes-node                                  0.1.12
  @backstage/plugin-kubernetes-react                                 0.3.5
  @backstage/plugin-kubernetes                                       0.11.10
  @backstage/plugin-org                                              0.6.25
  @backstage/plugin-permission-backend                               0.5.42
  @backstage/plugin-permission-common                                0.7.13
  @backstage/plugin-permission-node                                  0.7.29
  @backstage/plugin-permission-react                                 0.4.22
  @backstage/plugin-proxy-backend                                    0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                  0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud        0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server       0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket              0.2.8
  @backstage/plugin-scaffolder-backend-module-confluence-to-markdown 0.2.19
  @backstage/plugin-scaffolder-backend-module-gerrit                 0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                  0.1.8
  @backstage/plugin-scaffolder-backend-module-github                 0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab                 0.4.0
  @backstage/plugin-scaffolder-backend                               1.22.7
  @backstage/plugin-scaffolder-common                                1.5.2
  @backstage/plugin-scaffolder-node-test-utils                       0.1.4
  @backstage/plugin-scaffolder-node                                  0.4.4
  @backstage/plugin-scaffolder-react                                 1.8.6
  @backstage/plugin-scaffolder                                       1.20.1
  @backstage/plugin-search-backend-module-catalog                    0.1.24
  @backstage/plugin-search-backend-module-pg                         0.5.27
  @backstage/plugin-search-backend-module-techdocs                   0.1.23
  @backstage/plugin-search-backend-node                              1.2.23
  @backstage/plugin-search-backend                                   1.5.9
  @backstage/plugin-search-common                                    1.2.11
  @backstage/plugin-search-react                                     1.7.11
  @backstage/plugin-search                                           1.4.11
  @backstage/plugin-techdocs-backend                                 1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                   1.1.10
  @backstage/plugin-techdocs-node                                    1.12.4
  @backstage/plugin-techdocs-react                                   1.2.4
  @backstage/plugin-techdocs                                         1.10.5
  @backstage/plugin-user-settings                                    0.8.6
  @backstage/release-manifests                                       0.0.11
  @backstage/repo-tools                                              0.9.0
  @backstage/test-utils                                              1.5.5
  @backstage/theme                                                   0.5.5
  @backstage/types                                                   1.1.1
  @backstage/version-bridge                                          1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
Thank you for reporting! Just to clarify regarding the reproduction steps: I understand the entity from Azure does not immediately appear in the catalog, but does it appear if you wait for a refresh?

**Comment by charlesoscar** [comment]
Correct, even after waiting. It does not appear.

**Comment by charlesoscar** [comment]
If the user tries to re-register the component in this state:
![image](https://github.com/backstage/backstage/assets/6524677/5867981c-3555-4302-aab4-32561c0f6f9c)

**Comment by freben** [comment]
It does seem like the original entity still lingers in the system, even though the unregister step happened.

I'm curious: after the initial registration from GitHub, did the entity seem to land successfully and completely in Backstage? As in, could you go to its entity page and did it seem to properly have been read from GitHub with all its properties?

Essentially what I'm pondering is, did the entity land in the `refresh_state` table, but not the `final_entities` table (due to having errors that made it not successfully land in the output set).

**Comment by freben** [comment]
Do you happen to have the unprocessed entities plugin installed? Does it show anything for this entity? 

https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-unprocessed
