### ISSUE TITLE
🐛 Bug Report: redirect_uri_mismatch Github SSO

### ISSUE THREAD

**Issue by omi-jbrivero** [backstage/backstage#25065]
### 📜 Description

When the project does not use https, we can sign in via GitHub.

But the moment when we used ALB and converted to HTTPS, the github throws an error 

error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=6e6f6e63653d4c3549463756354a583634253246504569426573586c554125334425334426656e763d646576656c6f706d656e74266f726967696e3d6874747073253341253246253246706567617375732e736d6f702e6173696126666c6f773d706f7075702673636f70653d7265616425334175736572

And

Github
Sign in using GitHub  Origin <insert https website> is not allowed

### 👍 Expected behavior

The expected behavior is we can sign in via github sso

### 👎 Actual Behavior with Screenshots

It just throws an origin error Sign in using GitHub  Origin <insert https website> is not allowed

### 👟 Reproduction steps

We already modified our app-config.yaml where the base URL is our domains.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
Whats your `app-config.yaml`? Does that include the `https://`? Also worth checking what the `callbackUrl`(?) is set as under the GitHub app and see what that looks like, I think that it will need to contain the correct protocol.
