### ISSUE TITLE
🚀 Feature: add setAllowedLocationTypes to catalogProcessingExtensionPoint

### ISSUE THREAD

**Issue by hubofgitongithub** [backstage/backstage#25062]
### 🔖 Feature description

https://github.com/backstage/backstage/pull/13013 - in this MR the CatalogBuilder got changed so that custom location types could be set explicitly, which is something I need in my new case.

We are however already migrated to the new backend architecture and in there you only have access to explicit exposed extension points set by the catalog backend plugin. The catalogProcessingExtensionPoint currently does not expose the ability to call `setAllowedLocationTypes`, which is something I need.

### 🎤 Context

My current workaround is to copy paste the **[CatalogPlugin.ts](https://github.com/backstage/backstage/blob/c8c0bb95ca85d8739f7582b1bdb1ab706a6f3544/plugins/catalog-backend/src/service/CatalogPlugin.ts)**, add a line:
`builder.setAllowedLocationTypes(["url", "my-custom-type"])` and use that in my `index.ts`: `backend.add(catalogPlugin);`

### ✌️ Possible Implementation

Add `setAllowedLocationTypes` to `catalogProcessingExtensionPoint`, which in turn add its value to the `CatalogBuilder`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
Yes, but thinking that the `catalogProcessingExtensionPoint` is probably not the right place for this.

Can we create a new one called `catalogLocationsExtensionPoint` instead and see how that feels in a PR? :pray:

**Comment by the-serious-programmer** [comment]
@benjdlambert added an MR but struggling with DCO

**Comment by the-serious-programmer** [comment]
@benjdlambert opened an MR, looks good?

**Comment by BryanJaramilloAE** [comment]
Hi! this is just what I was looking for, it looks good, is there any news?

**Comment by benjdlambert** [comment]
Sorry, I've been out on vacation! This has been merged! :pray:
