### ISSUE TITLE
🚀 Feature: Allow for changing of Scaffolder Wizard orientation to vertical

### ISSUE THREAD

**Issue by KrystianOcado** [backstage/backstage#25074]
### 🔖 Feature description

Allow for easily changing of Scaffolder Wizard orientation to vertical.

### 🎤 Context

We would like to have vertical stepper in Scaffolder wizard. Currently, there is no easy way to do it. There is now scaffolder next, maybe it is a good time to add it?

### ✌️ Possible Implementation

There are multiple possibilities, two ideas:

1. Add `stepperOrientation` property to `TemplateWizardPageProps` in `TemplateWizardPage.tsx`. This allows for setting this property in custom `TemplateWizardPage` and passing it using `EXPERIMENTAL_TemplateWizardPageComponent`.
2. Add `wizardOrientation` property to `RouterProps` in `Router.tsx` and pass it to `Stepper` in `Stepper.tsx`.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @KrystianOcado, any chance you can share some mock ups? Also, the "Scaffolder next" was released as the default I think nearly a year ago.

**Comment by alper98** [comment]
AFAIK there's no way to acheive this without providing a custom`TemplateWizardPageComponent` which is an experimental prop on the `ScaffolderPage`.
 
```tsx
  <ScaffolderPage
          components={{
    EXPERIMENTAL_TemplateWizardPageComponent: p => (
              <TemplateWizardPage {...p} />
            ),
          }}
        />

```
We did this, and pretty much customized the entire wizard page.

**Comment by KrystianOcado** [comment]
Hi all!

Thank you for your comments.

I've modified Scaffolder code to test my idea and it turns out, it is not that easy :).

This is what we have now:

![image](https://github.com/backstage/backstage/assets/52703631/e10c6220-932c-4161-bcec-aa9ed22e2fe3)

This is what I was expecting (MUI Stepper, vertical):

![image](https://github.com/backstage/backstage/assets/52703631/93e0efdf-c069-4177-9e47-0a0c066f2dc0)


This is what I got :)

![image](https://github.com/backstage/backstage/assets/52703631/f1203ec2-fa4e-4e9c-95ad-57d0aeb62df9)


I would leave this issue for now, maybe it gains traction, but we will try to write our own template wizard page and pass it to: `EXPERIMENTAL_TemplateWizardPageComponent` per @alper98 suggestion.

Thanks again!

**Comment by awanlin** [comment]
Thanks for the images @KrystianOcado, that really helps as well as the additional context. Would it make more sense for this request to be more focused on simply supporting more screen sizes? I don't think adding a prop to pick on or the other makes sense if that is the context. Ideally as the screen resizes the layout should adjust accordingly. What do you think?

**Comment by KrystianOcado** [comment]
Hi @awanlin !

Our UX really likes the vertical stepper :) for all screen sizes, so I don't think it is a question of responsive design.

Also there was this bug: https://github.com/backstage/backstage/issues/21578

It was fixed by adding a horizontal scroll, but for our UX people, it is not the best solution. We would prefer to always have vertical stepper.

**Comment by awanlin** [comment]
Ok, then I think we should close this issue and focus the conversation here in https://github.com/backstage/backstage/issues/23948

**Comment by benjdlambert** [comment]
Let's do that - let's keep conversation in one place :tada:
