### ISSUE TITLE
🐛 Bug Report: Search: Techdocs kind filter not working.

### ISSUE THREAD

**Issue by SonilPro** [backstage/backstage#25073]
### 📜 Description

Querying techdocs with a "kind" filter (`/search?query=&types[]=techdocs&filters[kind]=Component`) does not work.
It seems that during collating a `.toLocaleLowerCase()` is applied to the entityInfo [here](https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-techdocs/src/collators/DefaultTechDocsCollatorFactory.ts#L183), which is then propagated to the resulting TechdocsDocumentation  [object](https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-techdocs/src/collators/DefaultTechDocsCollatorFactory.ts#L236). This in turn causes the query attempt to fail because the kind is no longer uppercase (eg. Component) but is lowercase instead (eg. component).

### 👍 Expected behavior

The query should successfully return documents which is the case when we search with lowercase kind.
`/search?query=&types[]=techdocs&filters[kind]=Component` -> Not working:
`/search?query=&types[]=techdocs&filters[kind]=component` -> Working

The query filter is automatically generated by using the default filters from *@backstage/plugin-search*

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/51959110/363ad23c-1938-45ed-8c9a-625bf82f6689)

### 👟 Reproduction steps

- Enable collating for techdocs and add proper filters to the SearchPage.tsx
- Try searching some techdocs -> should result in documents being returned
- Try enabling kind filter -> does not find anything. Query: search?query=&types[]=techdocs&filters[kind]=Component
- Manual change the url query -> search?query=&types[]=techdocs&filters[kind]=component -> should work

### 🖥️ Your Environment

OS:   Linux 6.5.0-35-generic - linux/x64
node: v18.18.0
yarn: 1.22.19
cli:  0.26.6 (installed)
backstage:  1.27.5

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.5.14, 0.7.2, 0.7.5
  @backstage/backend-common                                        0.20.2, 0.21.7, 0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.17, 0.6.18
  @backstage/backend-tasks                                         0.5.22, 0.5.23
  @backstage/backend-test-utils                                    0.3.7, 0.3.8
  @backstage/catalog-client                                        1.6.4, 1.6.5
  @backstage/catalog-model                                         1.4.5, 1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.4, 0.26.6
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4, 1.12.5
  @backstage/core-compat-api                                       0.2.4, 0.2.5
  @backstage/core-components                                       0.13.10, 0.14.6, 0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.32
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.7, 0.1.8
  @backstage/frontend-plugin-api                                   0.6.4, 0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26, 1.1.27
  @backstage/integration                                           1.10.0, 1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.67
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.12, 0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.26
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15, 0.1.16
  @backstage/plugin-catalog-backend-module-unprocessed             0.4.5
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.22, 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.11.0
  @backstage/plugin-catalog-node                                   1.11.1, 1.12.0
  @backstage/plugin-catalog-react                                  1.11.3, 1.12.0
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.1
  @backstage/plugin-catalog-unprocessed-entities                   0.2.4
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-devtools-backend                               0.3.4
  @backstage/plugin-devtools-common                                0.1.9
  @backstage/plugin-devtools                                       0.1.14
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-explore-common                                 0.0.3
  @backstage/plugin-home-react                                     0.1.12, 0.1.13
  @backstage/plugin-home                                           0.7.4
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.15
  @backstage/plugin-permission-backend                             0.5.42
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.28, 0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10, 0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7, 0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7, 0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7, 0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10, 0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7, 0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.7, 0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3, 0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.5, 1.22.7
  @backstage/plugin-scaffolder-common                              1.5.1, 1.5.2
  @backstage/plugin-scaffolder-node                                0.4.3, 0.4.4
  @backstage/plugin-scaffolder-react                               1.8.6
  @backstage/plugin-scaffolder                                     1.20.1
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-explore                  0.1.23, 0.1.24
  @backstage/plugin-search-backend-module-pg                       0.5.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.21, 1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10, 1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.5.3, 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by SonilPro** [comment]
@awanlin done

**Comment by emmaindal** [comment]
Hello @SonilPro, just wanted to let you know that I'm able to reproduce the problem you are reporting, however we don't have any plans right now to change this. But in the meanwhile, to make search work for your use case: 

If you add the following to your app config, you can get around the problem. 

```
search:
  collators: 
    techdocs:
      legacyPathCasing: true
```

**Comment by SonilPro** [comment]
@emmaindal great, thanks for checking
