### ISSUE TITLE
🐛 Bug Report: AWS ALB Resolver does not provide user roles

### ISSUE THREAD

**Issue by arut95** [backstage/backstage#25077]
### 📜 Description

I am trying to implement **proxied authentication** in Backstage using **AWS ALB** as the proxy with **Microsoft Azure AD** for the Authentication. The current behavior of the `signIn` resolver in the AWS ALB provider does not provide access to the user's roles. This makes it difficult to assign appropriate permissions to the user in Backstage based on their Azure AD roles.

I had referred these documents
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html
- https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/aws-alb-aad-oidc-auth.md

### 👍 Expected behavior

Expecting another field in the resolver for accessing the users' roles.
(When using AWS ALB as a proxy for authentication with Microsoft Azure AD provider, I expect to be able to access the roles of the authenticated user in the `signIn` resolver.)

### 👎 Actual Behavior with Screenshots

Currently, the `signIn` resolver does not provide access to the user's roles. This makes it difficult to assign appropriate permissions to the user in Backstage based on their Azure AD roles.
_(Redacted most of the values to avoid leaking any sensitive info.)_

_Entire objects in authHandler and resolver_:

<img width="568" alt="image" src="https://github.com/backstage/backstage/assets/33226200/8b03b6e7-5a59-4747-bbea-e7e5854060e7">

<img width="567" alt="image" src="https://github.com/backstage/backstage/assets/33226200/de6af858-5d60-4329-8abf-3b2beeea2328">

_The access token (JWT) after decoding_:
<img width="396" alt="image" src="https://github.com/backstage/backstage/assets/33226200/79bb80a3-4ffc-4d33-a6be-821538532d7a">

### 👟 Reproduction steps

1. Configure Backstage to use the AWS ALB authentication provider.
    1. Refer [aws-alb-aad-oidc-auth.md](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/aws-alb-aad-oidc-auth.md) document for the configuration.
    2. In App.tsx, used this `ProxiedSignInPage` tag with `awsalb` provider, instead of the `SampleSignInComponent` mentioned in that doc.
        > <ProxiedSignInPage {...props} provider="awsalb" />

2. Try to access the user's roles in the `signIn` resolver.
3. Notice that the roles are not available.

### 📃 Provide the context for the Bug.

I am trying to assign permissions to users in Backstage based on their roles received from Microsoft Azure AD through AWS ALB authentication action.

### 🖥️ Your Environment

OS:   Darwin 20.6.0 - darwin/x64
node: v20.9.0
yarn: 1.22.21
cli:  0.26.5 (installed)
backstage:  1.26.0

Dependencies:
  @backstage/app-defaults                                          1.5.4, 1.5.5
  @backstage/backend-app-api                                       0.7.2
  @backstage/backend-common                                        0.21.7
  @backstage/backend-defaults                                      0.2.17
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.6.17
  @backstage/backend-tasks                                         0.5.22
  @backstage/catalog-client                                        1.6.4, 1.6.5
  @backstage/catalog-model                                         1.4.5, 1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.25.2, 0.26.5, 0.26.4
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5, 1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.13.10, 0.14.6, 0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.32, 1.0.31
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8, 0.1.7
  @backstage/frontend-plugin-api                                   0.6.4, 0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26, 1.1.27
  @backstage/integration                                           1.10.0, 1.11.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-guest-provider             0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.4.12
  @backstage/plugin-auth-react                                     0.1.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 1.0.22, 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.11.1
  @backstage/plugin-catalog-react                                  1.11.3, 1.12.0
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-node                                    0.3.3
  @backstage/plugin-home-react                                     0.1.12
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.28
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.5
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.23
  @backstage/plugin-search-backend-module-pg                       0.5.26
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.5, 1.5.4
  @backstage/theme                                                 0.4.4, 0.5.3, 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 2.54s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by arut95** [comment]
@benjdlambert Thank you for the response.
Right. I realize now that, this should have probably been a question for AWS.

Looks like the AWS ALB does not pass the ID token. (Mentioned here - [Link](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html#user-claims-encoding))

> The Application Load Balancer creates a new access token when authenticating a user and only passes the access tokens and claims to the backend, however it does not pass the ID token information.

**_I believe this is the current behavior:_**
The `Azure AD` sends the `roles` array with the users' roles in the `ID token` header.
That header is not sent past the `AWS ALB`.
_(In backstage `awsalb` resolver we don't fetch that header, as it's not sent anyways from the ALB)_
And so, the roles are missing.

Will probably use a workaround similar to your suggestion for now. Thank you.

**Comment by camilaibs** [comment]
Close

> @benjdlambert Thank you for the response. Right. I realize now that, this should have probably been a question for AWS.
> 
> Looks like the AWS ALB does not pass the ID token. (Mentioned here - [Link](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html#user-claims-encoding))
> 
> > The Application Load Balancer creates a new access token when authenticating a user and only passes the access tokens and claims to the backend, however it does not pass the ID token information.
> 
> **_I believe this is the current behavior:_** The `Azure AD` sends the `roles` array with the users' roles in the `ID token` header. That header is not sent past the `AWS ALB`. _(In backstage `awsalb` resolver we don't fetch that header, as it's not sent anyways from the ALB)_ And so, the roles are missing.
> 
> Will probably use a workaround similar to your suggestion for now. Thank you.

Thank you @arut95 for getting back to us, we are closing this issue for now 🙂
