### ISSUE TITLE
🐛 Bug Report: Not able to add `common-library` plugin using `yarn add`

### ISSUE THREAD

**Issue by athira-sabu** [backstage/backstage#25083]
### 📜 Description

I created a plugin that can be used for frontend and backend using command `yarn new` -> select `plugin-common`
It got created. But when I try to add it to my plugins or backend getting below error, 

```shell
❯ yarn --cwd packages/backend add @internal/backstage-plugin-notifications-common
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@internal%2fbackstage-plugin-notifications-common: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/athira.sabu/Athira/backstage/packages/backend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### 👍 Expected behavior

Should add package `@internal/backstage-plugin-notifications-common` in `package.json`

### 👎 Actual Behavior with Screenshots

Getting error `package not found`

### 👟 Reproduction steps

1. Create common plugin using `yarn new` -> select `plugin-common`
2. Try to add using command `yarn add packages/backend <plugin-name>`

### 🖥️ Your Environment

OS:   Darwin 21.5.0 - darwin/x64
node: v20.12.1
yarn: 1.22.19
cli:  0.26.6 (installed)
backstage:  1.27.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
This seems like a duplicate of: https://github.com/backstage/backstage/issues/25063

It would be really helpful to include details steps to reproduce, like what folders you were in for each step to help better understand where commands were being ran.

**Comment by Athira-Sabu** [comment]
Sure, [In the project](https://github.com/Athira-Sabu/backstage/tree/master/plugins), I have both frontend and backend plugins. I need to share some common types between these plugins, ('notifications-backend' and 'notifications'). 

- I created a common plugin using the `yarn new` command from the plugins path.
- Navigated to the `/plugins/notifications-backend` folder, attempted to add this common plugin using the `yarn add @internal/backstage-plugin-notifications-common` command.
- Getting below error
```
yarn add @internal/backstage-plugin-notifications-common
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
warning Lockfile has incorrect entry for "@types/react@^16.13.1 || ^17.0.0". Ignoring it.
error An unexpected error occurred: "[https://registry.yarnpkg.com/@internal%2Fbackstage-plugin-notifications-common:](https://registry.yarnpkg.com/@internal%2fbackstage-plugin-notifications-common:) Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/athira.sabu/Athira/backstage/plugins/notifications-backend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by benjdlambert** [comment]
@Athira-Sabu I think that the issue linked from @awanlin is going to help you. I think that this looks like a `yarn@1.x` bug, and upgrading to `yarn@4` will solve a lot of these issues.

Wonder if we should look at shipping something other that `yarn@1` in `create-app` soon too.

**Comment by awanlin** [comment]
Yes, was thinking about the fact that we should update `create-app` as well @benjdlambert. 👍

**Comment by awanlin** [comment]
We've since upgraded `create-app` to use Yarn 4 which should address this issue.
