### ISSUE TITLE
🐛 Bug Report: Getting error after Installing plugin-catalog-backend-module-ldap

### ISSUE THREAD

**Issue by jestevez-claro** [backstage/backstage#25082]
### 📜 Description

It bugs when I install and configure @backstage/plugin-catalog-backend-module-ldap.

### 👍 Expected behavior

It should run successfully after installing and configuring ldap-pluging.

### 👎 Actual Behavior with Screenshots

```
[root@lxtjmeter0004 backstage-app-tse]# yarn tsc
yarn run v1.22.21
$ tsc
packages/backend/src/index.ts:27:13 - error TS2345: Argument of type 'Promise<{ default: typeof import("/root/backstage-app-tse/node_modules/@backstage/plugin-catalog-backend-module-ldap/dist/index"); LDAP_DN_ANNOTATION: "backstage.io/ldap-dn"; LDAP_RDN_ANNOTATION: "backstage.io/ldap-rdn"; ... 8 more ...; readLdapOrg: (client: LdapClient, userConfig: UserConfig, groupConfig: GroupConf...' is not assignable to parameter of type 'BackendFeature | (() => BackendFeature) | Promise<{ default: BackendFeature | (() => BackendFeature); }>'.
  Type 'Promise<{ default: typeof import("/root/backstage-app-tse/node_modules/@backstage/plugin-catalog-backend-module-ldap/dist/index"); LDAP_DN_ANNOTATION: "backstage.io/ldap-dn"; LDAP_RDN_ANNOTATION: "backstage.io/ldap-rdn"; ... 8 more ...; readLdapOrg: (client: LdapClient, userConfig: UserConfig, groupConfig: GroupConf...' is not assignable to type 'Promise<{ default: BackendFeature | (() => BackendFeature); }>'.
    Type '{ default: typeof import("/root/backstage-app-tse/node_modules/@backstage/plugin-catalog-backend-module-ldap/dist/index"); LDAP_DN_ANNOTATION: "backstage.io/ldap-dn"; LDAP_RDN_ANNOTATION: "backstage.io/ldap-rdn"; ... 8 more ...; readLdapOrg: (client: LdapClient, userConfig: UserConfig, groupConfig: GroupConfig, opti...' is not assignable to type '{ default: BackendFeature | (() => BackendFeature); }'.
      Types of property 'default' are incompatible.
        Type 'typeof import("/root/backstage-app-tse/node_modules/@backstage/plugin-catalog-backend-module-ldap/dist/index")' is not assignable to type 'BackendFeature | (() => BackendFeature)'.

27 backend.add(import('@backstage/plugin-catalog-backend-module-ldap'));
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in packages/backend/src/index.ts:27
```

 ![image](https://github.com/backstage/backstage/assets/166733353/9ad73c27-bd5a-43c9-8d6f-d61f08ac2e8b)

### 👟 Reproduction steps

1. From your Backstage root directory, install: yarn --cwd packages/backend add @backstage/plugin-catalog-backend-module-ldap

2. Next add the basic configuration to app-config.yaml.

3. Add following line: backend.add(import('@backstage/plugin-catalog-backend-module-ldap')); on packages/backend/src/index.ts

### 🖥️ Your Environment

yarn run v1.22.21
$ /root/backstage-app-tse/node_modules/.bin/backstage-cli info
OS:   Linux 5.14.0-427.16.1.el9_4.x86_64 - linux/x64
node: v20.12.2
yarn: 1.22.21
cli:  0.26.6 (installed)
backstage:  1.27.6

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.7.5
  @backstage/backend-common                                        0.21.7, 0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.6
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.67
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-github                  0.6.1
  @backstage/plugin-catalog-backend-module-ldap                    0.5.34
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.11.0
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.15
  @backstage/plugin-permission-backend                             0.5.42
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.7
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node                                0.4.4
  @backstage/plugin-scaffolder-react                               1.8.6
  @backstage/plugin-scaffolder                                     1.20.1
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
Done in 1.44s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @jestevez-claro, the version of this module hasn't been release as part of the main Monthly release cycle yet. Though the docs got updated early so I can understand the confusion. To resolve this can you try using version `0.6.0-next.2` of `@backstage/plugin-catalog-backend-module-ldap`? If that doesn't work then I might do a version bump to the latest `next` Weekly release using `yarn backstage-cli versions:bump --release next`. Your last option is to wait for the Monthly release on June 18th.

**Comment by jestevez-claro** [comment]
Hi @awanlin, I tried `0.6.0-next.2` version and now I'm getting a different error:

![image](https://github.com/backstage/backstage/assets/166733353/a11d668c-83e4-490a-9351-978a7bf4b5f9)

**Comment by awanlin** [comment]
Ah, seems that was noted in the PR - https://github.com/backstage/backstage/pull/24909#issuecomment-2136271892 - can you try using what's mentioned there?

**Comment by jestevez-claro** [comment]
Thanks @awanlin, backstage instance started after applying changes mentioned in the PR you shared. It would be really helpful to update oficial documentation as well with this.

On the other hand, I configured LDAP on app-config.yaml, as successfully is connecting and reading users and groups:

catalog info Read 1 LDAP users and 1 LDAP groups in 0.3 seconds. Committing... 
catalog info Committed 1 LDAP users and 1 LDAP groups in 0.0 seconds...

But I don't see this user/group on the app:

![image](https://github.com/backstage/backstage/assets/166733353/143d5e41-c5c0-427c-9a62-a0472ab6ddf4)

**Comment by awanlin** [comment]
You're welcome! I think the issue with the schedule is a bug so that should be sorted out first.

As for as this latest issue I'm not going to be much help. I don't use LDAP and don't have much experience with it. I just jumped on this issue as I had a feeling it was due to the release state.

**Comment by jestevez-claro** [comment]
Alright, thank you man!

**Comment by jestevez-claro** [comment]
This got fix by following @awanlin guidelines.
