### ISSUE TITLE
🐛 Bug Report: Error in <Select> component that has empty string as placeholder

### ISSUE THREAD

**Issue by emilefokkema** [backstage/backstage#25090]
### 📜 Description

It bugs out when I follow the instructions that are visible on the index.html of [this reproduction in Stackblitz](https://stackblitz.com/edit/vitejs-vite-jruywp?file=src%2FApp.tsx). The reproduction uses React and @backstage/core-components.

### 👍 Expected behavior

It should not crash.

### 👎 Actual Behavior with Screenshots

It actually crashes. You can see it for yourself in the Stackblitz reproduction that I mentioned above.

### 👟 Reproduction steps

Please refer to the steps that are visible on the index.html of the Stackblitz reproduction that I mentioned above.

### 📃 Provide the context for the Bug.

Please refer to the Stackblitz reproduction that I mentioned above.

### 🖥️ Your Environment

Please refer to the Stackblitz reproduction that I mentioned above.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @emilefokkema, appreciate that you set this up in Stackblitz but that's not a good representation of how these components are intended to be used. Could you maybe setup a repo with a Backstage app where this is being used? Or if that's something you've done already some errors that you are seeing there?

This is also not a create example but the `Select` component is working in Storybook here: https://backstage.io/storybook/?path=/story/inputs-select--default

**Comment by emilefokkema** [comment]
@awanlin Thank you for your reaction. I'm afraid I don't quite understand. Are you saying this is not a bug? Does my reproduction use the component in a way in which it is not intended to be used?

**Comment by awanlin** [comment]
The problem is that I don't know if it is or is not a bug as it looks to be working in other places. It's just really handy to have all the context in the issue.

This is the error following the steps in the Stackblitz:

```text
TypeError: Cannot read properties of undefined (reading 'value')
    at chunk-ZITKFKUM.js?v=63a7b572:21197:34
    at Array.map (<anonymous>)
    at chunk-ZITKFKUM.js?v=63a7b572:21196:41
    at commitHookEffectListMount (chunk-VSTCBM7W.js?v=63a7b572:16936:34)
    at commitPassiveMountOnFiber (chunk-VSTCBM7W.js?v=63a7b572:18184:19)
    at commitPassiveMountEffects_complete (chunk-VSTCBM7W.js?v=63a7b572:18157:17)
    at commitPassiveMountEffects_begin (chunk-VSTCBM7W.js?v=63a7b572:18147:15)
    at commitPassiveMountEffects (chunk-VSTCBM7W.js?v=63a7b572:18137:11)
    at flushPassiveEffectsImpl (chunk-VSTCBM7W.js?v=63a7b572:19518:11)
    at flushPassiveEffects (chunk-VSTCBM7W.js?v=63a7b572:19475:22)
```

Do you have the error from your Backstage instance? That might help point to what part of the code might be failing, this error seems pretty obfuscated.

**Comment by emilefokkema** [comment]
@awanlin Well this weird. I tried to copy my reproduction to an actual Backstage app ([this is the repo](https://github.com/emilefokkema/backstage-test/tree/issue/25090-reproduction)), but then the error disappeared! How could this be? How could the same component work when inside a Backstage app, but not when used on its own? Especially since I originally found the error while using the `<Select>` inside a Backstage app, so I know there is something. I'll keep looking for a reproduction :)

**Comment by emilefokkema** [comment]
@awanlin Correction, the issue is actually visible in the [repo](https://github.com/emilefokkema/backstage-test/tree/issue/25090-reproduction) I mentioned! (I was looking at a production build earlier, where the error somehow doesn't appear.)

Here's the error in the Backstage instance from the repo:

<img width="585" alt="image" src="https://github.com/backstage/backstage/assets/11552774/3b4476a6-6ee0-460e-a887-3294ff4f395b">

**Comment by awanlin** [comment]
Thanks! I'll try and take a look but it may take me a while to get to it.

**Comment by emilefokkema** [comment]
@awanlin I found a greatly simplified reproduction. [This](https://stackblitz.com/edit/vitejs-vite-chk7u8) is the new Stackblitz, and I've updated the [repo](https://github.com/emilefokkema/backstage-test/tree/issue/25090-reproduction).

It seems to have to do with the fact that the 'placeholder' property has the empty string for a value.
