### ISSUE TITLE
🐛 Bug Report: Adding `pagination` property on `<CatalogIndexPage />` removes "Actions" column

### ISSUE THREAD

**Issue by piatkiewicz** [backstage/backstage#25097]
### 📜 Description

If I add `pagination` property to `<CatalogIndexPage />` element the "Actions" column disappears from the table.

I just installed fresh app with create-app script, initially it looks like this, you can see "Actions" column on the far right with View, Edit and Star option for each entity:
![image](https://github.com/backstage/backstage/assets/8793897/45362127-9137-4d9b-9369-06c0274dde1a)

Only 1 little change I do is adding pagination as mentioned above (like in [docs](https://backstage.io/docs/features/software-catalog/catalog-customization/#pagination))
![image](https://github.com/backstage/backstage/assets/8793897/329f3207-9659-42ba-8330-f7185cd67c6a)

Then Actions are gone
![image](https://github.com/backstage/backstage/assets/8793897/944d05be-431b-4cfc-b562-7a2441311591)

If that's not a bug for some reason it would be helpful to have it described in docs somewhere (here maybe https://backstage.io/docs/features/software-catalog/catalog-customization/#pagination)

There is an if statement in `CatalogTable` component that returns `PaginatedCatalogTable` or `Table<CatalogTableRow>`, but in both cases they receive same `columns` and `actions` objects - I can't locate where could they be modified. https://github.com/backstage/backstage/blob/d57ebbca65fdfbd66b91bd3c8357d75ae1ecbee7/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L193-L231

There is some warning in the devtools' console btw: `react-dom.development.js:86  Warning: MTablePagination: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at MTablePagination (webpack-internal:///../../node_modules/@material-table/core/dist/components/MTablePagination/index.js:96:10)`

### 👍 Expected behavior

Actions should still be visible and available

### 👎 Actual Behavior with Screenshots

"Actions" column is gone (screenshot above)

### 👟 Reproduction steps

Add pagination like this
`<Route path="/catalog" element={<CatalogIndexPage pagination />} />`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@vinzscam do you know anything about this?

**Comment by vinzscam** [comment]
it looks like a bug. `actions` doesn't seem to be passed down to `CatalogTable`

**Comment by piatkiewicz** [comment]
@vinzscam yup, you're right, prop was missed in `PaginatedCatalogTable`. I linked the PR with a fix above
