### ISSUE TITLE
🐛 Bug Report: Unable to unregister a component

### ISSUE THREAD

**Issue by dheerajkabra** [backstage/backstage#25108]
### 📜 Description

Hi, whenever I am trying to "unregister" a component, I get below error:
```
{
  "error": {
    "name": "error",
    "message": "select * from \"locations\" where \"id\" = $1 - invalid input syntax for type uuid: \"url:https://github.fkinternal.com/dheeraj-kabra/fcc-ansible/blob/backstage/ansible-component.yaml\"",
    "length": 229,
    "severity": "ERROR",
    "code": "22P02",
    "where": "unnamed portal parameter $1 = '...'",
    "file": "uuid.c",
    "line": "136",
    "routine": "string_to_uuid"
  },
  "request": {
    "method": "GET",
    "url": "/locations/url%3Ahttps%3A%2F%2Fgithub.fkinternal.com%2Fdheeraj-kabra%2Ffcc-ansible%2Fblob%2Fbackstage%2Fansible-component.yaml"
  },
  "response": {
    "statusCode": 500
  }
}
```

I go to 3 dots on right upper most corner for a given component, Click on "Unregister Entity" and I get this error.
I am on Backstage version  `"version": "1.21.0"`  and This is connected to the PostgrSQL running on Google cloud.

The Component is present in PostgrSQL:

```
fcc_backstage_catalog=> select * from locations where target = 'https://github.fkinternal.com/dheeraj-kabra/fcc-ansible/blob/backstage/ansible-component.yaml';
                  id                  | type |                                            target                                             
--------------------------------------+------+-----------------------------------------------------------------------------------------------
 b7e483cd-c06d-42c8-a874-20d3e8d2fcd4 | url  | https://github.fkinternal.com/dheeraj-kabra/fcc-ansible/blob/backstage/ansible-component.yaml
```

However it seems from the UI, when I try to unregister, the value `b7e483cd-c06d-42c8-a874-20d3e8d2fcd4` is not replacing the variable `$1` and hence the Query is failing with error `"select * from \"locations\" where \"id\" = $1 - invalid input syntax for type uuid:`

### 👍 Expected behavior

The component should get unregistered from Backstage UI.

### 👎 Actual Behavior with Screenshots

As described in "Description"

### 👟 Reproduction steps

Deploy BAckstage 1.21.0 with PosstgreSQL DB 
Register a component
Try to "unregister" given component.

### 🖥️ Your Environment

Backstage is running on K8S on Google GKE.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
I think that this has been fixed in later versions of Backstage. Looks like it was fixed in 1.22. https://github.com/backstage/backstage/issues/21962. 

Going to close this issue as it's a duplicate :) But please upgrade and report back if there's anything awry!
