### ISSUE TITLE
🚀 Feature: introduce lifecycle in catalog-model for Resource entity kind

### ISSUE THREAD

**Issue by hubofgitongithub** [backstage/backstage#25111]
### 🔖 Feature description

Currently only API and Component have lifecycle values. We will however also extensively add the Resource entity kind, wanting to leverage the lifecycle property. Preferably lifecycle gets added to the Resource entity kind, both in the documentation on for instance: https://backstage.io/docs/features/software-catalog/descriptor-format/ as well in the `catalog-model` package.

### 🎤 Context

We want to strongly type our code, which is why we for instance do:
```
import { ResourceEntity } from '@backstage/catalog-model';

const buildResourceSpec = (ourCustomCatalogFormat: OurCustomCatalogFormat): ResourceEntity["spec"] => {
.... code that maps custom format to the backstage catalog format
}
```

Currently we add mapping code in here to map our custom catalog lifecycle value for a resource into the backstage resource, except that this leads to typescript errors. Of course we can ignore these, but it feels like resource is missing this field that has no clear reason (at least to me) why it is not there, as both api and component already have it.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Hi!

Thanks for waiting. We discussed it briefly and the consensus is:

- The suggestion as such makes sense. Attaching an _optional_ lifecycle value to resources is useful and has clear-enough semantics
- At the same time, it may be useful to document that it's commonly more useful to _derive_ this value (in the frontend code for example) based on what the associated Component(s)/API(s) claim, for example, so as not to unnecessarily burden the users with updating effectively the same value in multiple places

Does that make sense?

If you want to make a contribution to the open source model, we're happy to continue the discussion in a PR 🙏
