### ISSUE TITLE
Update Datadog RUM  installation docs

### ISSUE THREAD

**Issue by camilaibs** [backstage/backstage#25217]
Document the step of adding the this script to the `package/app/public/index.html` file: https://github.com/backstage/backstage/issues/25190#issuecomment-2165518461.

**Comment by EvanGKelly** [comment]
Could I be assigned this please? Also is there a location you think is best for this to be documented?

**Comment by chussenot** [comment]
Hi, i'm trying to configure the logs and rum directly on the `packages/app/src/index.tsx`

This code is working properly... but I've got issue when I'm trying to load the app-config in this file.
Can I get help to continue on this? cc @EvanGKelly ?

```index.tsx

import "@backstage/cli/asset-types";
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import { datadogRum } from "@datadog/browser-rum";
import { datadogLogs } from "@datadog/browser-logs";

const Main = () => {

    datadogRum.init({
        clientToken: "CLIENT_TOKEN",
        applicationId: "APPLICATION_ID",
        site: "datadoghq.eu",
        service: "myconsole",
        env: "dev",
        version: "v0.18.6",
        trackUserInteractions: true,
        trackResources: true,
        trackLongTasks: true,
    });

    datadogLogs.init({
        clientToken: "CLIENT_TOKEN",
        site: "datadoghq.eu",
        service: "myconsole",
        env: "dev",
        version: "v0.18.6",
        forwardErrorsToLogs: true,
        forwardConsoleLogs: "all",
        forwardReports: "all",
        storeContextsAcrossPages: true,
    });

    return <App />;

}

ReactDOM.createRoot(document.getElementById("root")!).render(<Main />);

```

**Comment by camilaibs** [comment]
> Could I be assigned this please? Also is there a location you think is best for this to be documented?

For sure, thank you for helping us! This page could be a good place: https://backstage.io/docs/integrations/datadog-rum/installation/

The markdown lives here: https://github.com/backstage/backstage/blob/master/docs/integrations/datadog-rum/installation.md

**Comment by EvanGKelly** [comment]
Great, And thanks for linking that page I will work on this!

**Comment by EvanGKelly** [comment]
Cant assign myself can, is there someone with permissions?

**Comment by chussenot** [comment]
I'll be happy to contribute also... but I've got no permissions...

**Comment by chussenot** [comment]
Let's work on this branch Evan, https://github.com/chussenot/backstage/tree/docs/datadog-rum

**Comment by EvanGKelly** [comment]
Unfortunately Im working from a corporate account so cant contribute here. I should have a PR ready for review shortly and I will add a link to it here, and we can collaborate this way.

**Comment by chussenot** [comment]
You can make commits, here. https://github.com/chussenot/backstage/blob/docs/datadog-rum/docs/integrations/datadog-rum/installation.md

**Comment by chussenot** [comment]
> Unfortunately Im working from a corporate account so cant contribute here. I should have a PR ready for review shortly and I will add a link to it here, and we can collaborate this way.

Perfec, I'm ready for a review.

**Comment by freben** [comment]
Should you link to the PR here perhaps?

**Comment by chussenot** [comment]
@EvanGKelly any news ?

**Comment by EvanGKelly** [comment]
Hi, Yes waiting on approval on my end, and will be able to open a PR shortly

**Comment by EvanGKelly** [comment]
https://github.com/backstage/backstage/pull/25411

**Comment by calvin-funimation** [comment]
Thanks for the documentation! It was very helpful with our RUM integration.

Side note, there's a bug where `env` value MUST be specified at build time. We tried to have this be a system environment variable, but it did not work. We ended up setting the value during the build process.

**Comment by camilaibs** [comment]
Thanks for sharing @calvin-funimation. What do you mean by this?
> We tried to have this be a system environment variable, but it did not work

Did you try something like this in your app-config.yaml?

```yaml
...
  app:
    datadogRum:
      env: ${DATADOG_RUM_ENV}
...
      
```

**Comment by camilaibs** [comment]
@EvanGKelly Would you mind adding a note about it to the documentation pull request you are working on?
> The `env` value MUST be specified at build time.

**Comment by EvanGKelly** [comment]
> @EvanGKelly Would you mind adding a note about it to the documentation pull request you are working on?
> 
> > The `env` value MUST be specified at build time.

Yes that won't be a problem!
