### ISSUE TITLE
Revisit how new extensions and overrides are packaged

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#25218]
### Need
- There's no package role that fits the current way of structuring this in a repo.
- If you have a package that provides a lot of overrides with `createExtensionOverrides` it's not a `plugin` and it's not `plugin-module`. Perhaps a `web-library` but these are not automatically loaded with discovery.
- There's a fix needed at the tooling layer, what is the package name for this?
- `createExtensionOverrides` does two things, override plugin extensions or standalone extensions, and also add new extensions in the app that are not part of any particular extensions, new icons bundles or translations, then the name is awkward.

### Use Cases
- A package that provides an override for the Catalog Page
- A package that provides a translation for `core-components`
- A package that overrides the `sidebar`
- A package that provides extra Icons
- A package that provides a new theme

### Proposed Solution
- Figure out how to name these packages, and their roles.
- `container` or synonyms, a collection of things thats not just overrides could be a good example.

### Other Notes
- Revisit `createExtensionOverrides` naming, could be related to #25210 
- Let extension overrides provide more metadata

**Comment by freben** [comment]
https://github.com/backstage/backstage/pull/25947

**Comment by benjdlambert** [comment]
Fixed by #26245

**Comment by benjdlambert** [comment]
And #26340
