### ISSUE TITLE
🐛 Bug Report: Cannot find module '@backstage/plugin-kubernetes-backend'

### ISSUE THREAD

**Issue by aniket-a-mukherjee** [backstage/backstage#25229]
### 📜 Description

Trying to run the app after installing '@backstage/plugin-kubernetes-backend' following the page 
https://backstage.io/docs/features/kubernetes/installation/

### 👍 Expected behavior

It should not throw this error and I should be able see Kuberenetes services using backend plugin

### 👎 Actual Behavior with Screenshots

[0] Loaded config from app-config.yaml, app-config.local.yaml
[1] node:internal/modules/cjs/loader:1148
[1]   throw err;
[1]   ^
[1]
[1] Error: Cannot find module '@backstage/plugin-kubernetes-backend'
[1] Require stack:
[1] - /home/anikm03/idpdemo/packages/backend/src/plugins/kubernetes.ts
[1] - /home/anikm03/idpdemo/packages/backend/src/index.ts
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
[1]     at Module._load (node:internal/modules/cjs/loader:986:27)
[1]     at Module.require (node:internal/modules/cjs/loader:1233:19)
[1]     at require (node:internal/modules/helpers:179:18)
[1]     at Object.<anonymous> (/home/anikm03/idpdemo/packages/backend/src/plugins/kubernetes.ts:4:31)
[1]     at Module._compile (node:internal/modules/cjs/loader:1358:14)
[1]     at Module._compile (/home/anikm03/idpdemo/node_modules/pirates/lib/index.js:117:24)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
[1]     at Object.newLoader [as .ts] (/home/anikm03/idpdemo/node_modules/pirates/lib/index.js:121:7)
[1]     at Module.load (node:internal/modules/cjs/loader:1208:32) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   requireStack: [
[1]     '/home/anikm03/idpdemo/packages/backend/src/plugins/kubernetes.ts',
[1]     '/home/anikm03/idpdemo/packages/backend/src/index.ts'
[1]   ]
[1] }
[1]

### 👟 Reproduction steps

Followed the instruction https://backstage.io/docs/features/kubernetes/installation/
Adding Kubernetes Backend plugin

### 🖥️ Your Environment

 yarn backstage-cli info
yarn run v1.22.22

OS:   Linux 5.10.102.1-microsoft-standard-WSL2 - linux/x64
node: v20.14.0
yarn: 1.22.22
cli:  0.26.6 (installed)
backstage:  1.27.0

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.7.5
  @backstage/backend-common                                        0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.6
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.67
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-github-org              0.1.13
  @backstage/plugin-catalog-backend-module-github                  0.6.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.11.0
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-kubernetes-backend                             0.17.1
  @backstage/plugin-kubernetes-common                              0.7.6
  @backstage/plugin-kubernetes-node                                0.1.12
  @backstage/plugin-kubernetes-react                               0.3.5
  @backstage/plugin-kubernetes                                     0.11.10
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.15
  @backstage/plugin-permission-backend                             0.5.42
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.8
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node                                0.4.4
  @backstage/plugin-scaffolder-react                               1.8.6
  @backstage/plugin-scaffolder                                     1.20.1
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
Done in 0.67s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hello @aniket-a-mukherjee 👋🏻 , thanks for reaching out to us! Could you please confirm that there is an `node_modules/@backstage/kubernetes-backend folder in your root project directory?

**Comment by manishbhatt** [comment]
I am running into same issue, @camilaibs  Yes I do have that folder in the root project directory

**Comment by Rugvip** [comment]
Are you seeing any errors if you run `yarn tsc`?

Another thing to check for is that the `node_modules/@backstage/plugin-kubernetes-backend` folder seems correct, i.e. that it contains a `package.json` with an entry point field pointing to a file in `./dist`.

It might also be as simple as this being due to a bad install state or bug with Yarn. You can try deleting `node_modules` and re-running `yarn install` to see if that fixes it.

**Comment by manishbhatt** [comment]
Figured out. I have latest version I stared but I was following the documentation for old backend system. Following docs for new backend system resolved the issue. Thanks !

**Comment by freben** [comment]
Good to hear! Closing.
