### ISSUE TITLE
Add support for public sign-in page for protected frontends

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#25222]
### Need
- `index-public-experimental.tsx` is only available in the old system.
- We need an equivalent in the new system.

**Comment by Rugvip** [comment]
A way to do this in the new system is available, but we should make it even simpler: https://github.com/backstage/backstage/blob/7ee0e13eb2e9fce0e2fc04163ad3a5685e37102b/packages/app-next/src/index-public-experimental.tsx
