### ISSUE TITLE
🚀 Feature: Allow SignInPage to be replaced in DevAppBuilder

### ISSUE THREAD

**Issue by jslott2sigma** [backstage/backstage#25230]
### 🔖 Feature description

Allow plugins to set their own SignInPage when testing plugins to streamline and customize the login aspects.

### 🎤 Context

When we develop plugins, we often need some "real" user (versus guest) token and can use, for example ProxiedSignInPage to bypass an actual login in screen along with a custom sign-in provider/resolver that either returns the user running the process or grabs user credentials from the browser.

It also helps the plugin development experience by bypassing the explicitly login UI step and also not having to enable the OAuth2 identity provider (e.g. Azure, Okta) for local plugin development.

### ✌️ Possible Implementation

Add a setSignInPage method to DevAppBuilder that let's plugin development apps to replace the SignInPage set here: https://github.com/backstage/backstage/blob/cd9fb6dc2ccb45c6ded103ea44f093b5bebb6959/packages/dev-utils/src/devApp/render.tsx#L220

As an alternative, we can fork DevAppBuilder, but would prefer an upstream contribution.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hello @jslott2sigma, thanks for opening the issue 🙌🏻 . If you would like to propose something in a PR, please feel free to do so 🙂

**Comment by jslott2sigma** [comment]
As I've done further development I realized that I would like several more modifications to `DevAppBuilder`, so this one enhancement probably isn't worth it. [This comment in the source](https://github.com/backstage/backstage/blob/74e52d8114d55916581a464d10434874484c658b/packages/dev-utils/src/devApp/render.tsx#L295) code suggests that perhaps the architecture of `DevAppBuilder` itself should change to allow customization.

In the meantime, feel free to close this issue.

**Comment by Rugvip** [comment]
Most likely we'll end up focusing efforts around dev utils for the new frontend system, and broadly leave the existing dev app as is. Small improvements and tweaks are welcome though.

**Comment by Rugvip** [comment]
Will close, improvements in this area are already on our radar as part of finalizing the new frontend system.
