### ISSUE TITLE
🚀 Feature: Add support for GitHub Environment Tag Patterns

### ISSUE THREAD

**Issue by davidrichardsonleit** [backstage/backstage#25232]
### 🔖 Feature description

Support GitHub Environment Tag Patterns as per:

https://github.blog/changelog/2023-10-06-actions-secure-deployment-rollouts-to-protected-environments-based-on-select-tag-patterns/

### 🎤 Context

Currently the action ```github:environment:create``` only supports a custom branch policy.

When releasing software tagging a commit with something like ```release/v1.2.0``` is best practice.

But the current behaviour means that if a branch commit has a tag then it is not possible to use an environment.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by codingdiaz** [comment]
It looks like the API call that is creating protections is not specifying the `type` (might have not been available when written) and it’s defaulting to `branch`. 

I started a draft PR to try to address it! https://github.com/backstage/backstage/pull/25333

**Comment by benjdlambert** [comment]
Closing as fixed in the aforementioned PR! :tada:
