### ISSUE TITLE
🚀 Feature: Allow to supply additional IconLinks to AboutCard

### ISSUE THREAD

**Issue by secustor** [backstage/backstage#25234]
### 🔖 Feature description

Currently the AboutCard has exactly two IconLinks.  One for the source location and one for Techdocs. 
This feature request is about allowing to supply additional links depending on the implementers choices. 

Later on this could be embedded in the plugin system and plugins could provide additional IconLinks dynamically, though this is out of scope for now. 

### 🎤 Context

If implementers want to provide additional IconLinks it is necessary to copy the Card code and change it accordingly. 
This is not ideal from a maintenance and DRY standpoint. 

### ✌️ Possible Implementation

Add a new parameter to the props of AboutCards
```typescript
export interface AboutCardProps {
  variant?: InfoCardVariants;
  additionalIconLinks?: IconLinkVerticalProps[]
}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by darylgraham** [comment]
Would it make sense for this interface to encompass all icon links with the default being source location + techdocs, rather than just specifying additional links? That would then cover #24960 by giving a way to disable that link via the interface.

**Comment by secustor** [comment]
If it is possible to expose the the default ones, that makes sense. 

```typescript
export interface AboutCardProps {
  variant?: InfoCardVariants;
  iconLinks?: IconLinkVerticalProps[]
}
```

```typescript 
import { defaultIconLinks } from '@backstage/catalog';
import { myCustonIconLink } from './iconLinks';

<EntityAboutCard variant="gridItem" iconLinks={[...defaultIconLinks, myCustomIconLink ]} />
```

**Comment by awanlin** [comment]
Hi, just wanted to share prior work on this subject:

- https://github.com/backstage/backstage/pull/15306
- https://github.com/backstage/backstage/pull/14544
- https://github.com/backstage/backstage/pull/12651

**Comment by secustor** [comment]
Not sure what prevented #14544 to merged, which seems to do pretty much what I'm looking for. 

Maybe one of the maintainers can jump and give us input if that PR would be accepted today or what prevented it from being approved back then.

**Comment by awanlin** [comment]
Yes, I think it would be good to revisit this topic. Perhaps things have changed as the items I shared are a few years old now. I just wanted to raise awareness to past conversations on the topic. These were the easiest to find but I think there were also Issues on the topic too. The general recommendations has been to fork this card.

**Comment by camilaibs** [comment]
> Not sure what prevented #14544 to merged, which seems to do pretty much what I'm looking for.
> 
> Maybe one of the maintainers can jump and give us input if that PR would be accepted today or what prevented it from being approved back then.

Chatting with the team, we still hesitant about extending this card. This is one of those cards that is too adaptable, there have been so many requests to add to that card that it would probably have huge number of props by now. We'd prefer to make its atomic parts more reusable, so people can make their own specialized cards. Does this make sense to you 🙂?

**Comment by secustor** [comment]
Probably makes sense then to write this down somewhere. Maybe in the ADRs?

**Comment by freben** [comment]
Alright, made https://github.com/backstage/backstage/pull/25341
