### ISSUE TITLE
🐛 Bug Report: MultiEntityPicker causes browser to stop responding with bigger amount of entitites

### ISSUE THREAD

**Issue by Hi-Fi** [backstage/backstage#25243]
### 📜 Description

Earlier we were able to use MultiEntityPicker to select users in templates. Now whole template page gets stuck even without touching those pickers. 

When tested with Custom Field Explorer (found at path <backstage URL>/create/edit) also that would jam quite quickly unless adding some filtering and applying that before that happens.

### 👍 Expected behavior

Component should handle bigger amounts of data, and throw error if it can't handle it and not make browser to stuck.

### 👎 Actual Behavior with Screenshots

Browser window just gets stuck. E.g. Edge throws out "This page isn't responding" error, and Firefox:
![image](https://github.com/backstage/backstage/assets/1499780/42f465b7-2bf8-4b45-bb7a-138e95fce24e)

Before entity is loaded (in network tab) component displays "Loading" as it should.

### 👟 Reproduction steps

1. Ensure that you have ~a lot of data in backstage (in our case ~5000 user entities)
2. Go to /create/edit and select Custom Field Explorer
3. Select MultiEntityPicker
4. Open the entity list on the right side without any filtering

### 📃 Provide the context for the Bug.

This issue currently prevents using of the forms that have this type of selection in the form.

OwnerPicker works fine with that amount of users, but it is not so nice way to add multiple users (user have to press plus all the time and it has to be wrapped inside another component).

### 🖥️ Your Environment

Browsers:
- Firefox 127.0
- Edge 126.0.2592.56
Computer:
- Apple MacBook Pro with M3 Pro (2023 model)
Backstage version:
- 1.27.5

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by zcmander** [comment]
We're facing the same issue as described here. I think it comes down to the Autocomplete component not able to handle high number of items. The following issues might be relevant:

* https://github.com/mui/material-ui/issues/34712
* https://github.com/mui/material-ui/issues/17001

(Later one is for the Select component, I'm not sure whose fault it actually is...). Anyhow, the proposed solution here is to implement virtualization around the Listbox component, see example in MUI docs:

https://v4.mui.com/components/autocomplete/#virtualization
