### ISSUE TITLE
🐛 Bug Report: PluginTaskScheduler Issue with initialDelay

### ISSUE THREAD

**Issue by VaseemFathima-36** [backstage/backstage#25245]
### 📜 Description

When initializing the task scheduler, the initial task is scheduled to execute after an initial delay of 8 seconds. However, instead of running only once after the initial delay, the task scheduler executes the initial task 2 times. This behavior deviates from the expected functionality, where the initial task should execute exactly once after the specified delay before transitioning to the scheduled frequency for subsequent runs.

### 👍 Expected behavior

Initial Delay only runs once based on given time.

### 👎 Actual Behavior with Screenshots

When initializing the task scheduler, the initial task is scheduled to execute after an initial delay of 8 seconds. However, instead of running only once after the initial delay, the task scheduler executes the initial task 2 times. This behavior deviates from the expected functionality, where the initial task should execute exactly once after the specified delay before transitioning to the scheduled frequency for subsequent runs.

### 👟 Reproduction steps

Try with below code
const schedule = scheduler.createScheduledTaskRunner({
        frequency: { hours:0, minutes:2, seconds:4 },
        timeout: { hours: 0, minutes: 10, seconds: 9 },
        initialDelay: { hours: 0, minutes: 0, seconds: 8 },
        scope: 'global',
    });

### 🖥️ Your Environment

OS:   Windows_NT 10.0.22621 - win32/x64
node: v20.5.0
yarn: 1.22.19
cli:  0.26.4 (installed)
backstage:  1.26.0

Dependencies:
  @backstage/app-defaults                                          1.5.4, 1.5.5
  @backstage/backend-app-api                                       0.7.2, 0.7.5
  @backstage/backend-common                                        0.21.7, 0.22.0
  @backstage/backend-defaults                                      0.2.17
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.6.17, 0.6.18
  @backstage/backend-tasks                                         0.5.22, 0.5.23
  @backstage/catalog-client                                        1.6.4, 1.6.5
  @backstage/catalog-model                                         1.4.5, 1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.25.2, 0.26.5, 0.26.4
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5, 1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.13.10, 0.14.6, 0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.32, 1.0.31
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8, 0.1.7
  @backstage/frontend-plugin-api                                   0.6.4, 0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26, 1.1.27
  @backstage/integration                                           1.10.0, 1.11.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.4.12, 0.4.13
  @backstage/plugin-auth-react                                     0.1.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 1.0.22, 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.11.1
  @backstage/plugin-catalog-react                                  1.11.3, 1.12.0
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-node                                    0.3.3
  @backstage/plugin-home-react                                     0.1.12
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.28, 0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.5
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.23
  @backstage/plugin-search-backend-module-pg                       0.5.26
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.5, 1.5.4
  @backstage/theme                                                 0.4.4, 0.5.3, 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Twice immediately in succession? Or overlapping?

Does it happen on the same node always, ie does it happen even on a single machine?

**Comment by VaseemFathima-36** [comment]
The initial task is executed twice immediately in succession after the initial delay of 8 seconds. There is no overlapping in execution; rather, the second execution starts right after the first one completes. For example, if the initial task starts at 05:01:20 and completes at 05:01:21, the next execution starts at 05:01:26, which aligns with the initial delay and configured frequency.

This behavior is consistently observed on a single machine and same node.

**Comment by freben** [comment]
Interesting! I actually can't reproduce this, I think. Tried adding the following in just some plugin:

```ts
        await scheduler.scheduleTask({
          id: 'task-one',
          frequency: { seconds: 10 },
          timeout: { seconds: 5 },
          initialDelay: { seconds: 3 },
          scope: 'global',
          fn: async () => {
            console.log(
              '###################################################################',
            );
            console.log('TASK ONE', new Date().toISOString().split('T')[1]);
            console.log(
              '###################################################################',
            );
          },
        });

        await scheduler.scheduleTask({
          id: 'task-two',
          frequency: { seconds: 10 },
          timeout: { seconds: 5 },
          initialDelay: { seconds: 3 },
          scope: 'local',
          fn: async () => {
            console.log(
              '###################################################################',
            );
            console.log('TASK TWO', new Date().toISOString().split('T')[1]);
            console.log(
              '###################################################################',
            );
          },
        });
```

just to make sure to test both global and local variants. And it worked as intended:

```
###################################################################
TASK TWO 11:52:45.822Z
###################################################################
###################################################################
TASK ONE 11:52:45.830Z
###################################################################

...

###################################################################
TASK TWO 11:52:55.824Z
###################################################################
###################################################################
TASK ONE 11:52:55.857Z
###################################################################
```

same after a restart.
