### ISSUE TITLE
🐛 Bug Report: Unable to import catalog-info.yaml hosted in GitHub with "blob" in path

### ISSUE THREAD

**Issue by csuich2** [backstage/backstage#25246]
### 📜 Description

When attempting to import a catalog-info.yaml from GitHub that has "blob" in its path or that references another catalog-info.yaml with "blob" in its path the Backstage server fails with a 400.

### 👍 Expected behavior

The catalog-info.yaml should be able to be imported.

### 👎 Actual Behavior with Screenshots

The catalog-info.yaml fails to pass analysis and cannot be imported.

![image](https://github.com/backstage/backstage/assets/1966632/e4658809-3359-4d82-9ea5-05d7ac9040af)

```json
{
  "error": {
    "name": "InputError",
    "message": "Error: Unable to read url, Error: Request failed for https://raw.githubusercontent.com/csuich2/backstage-catalog-test/tree/main/pkg/catalog-info.yaml/, 400 Bad Request",
    "stack": "InputError: Error: Unable to read url, Error: Request failed for https://raw.githubusercontent.com/csuich2/backstage-catalog-test/tree/main/pkg/catalog-info.yaml/, 400 Bad Request\n at DefaultLocationService.processEntities (/Users/chris.suich/code/backstage/node_modules/@backstage/plugin-catalog-backend/src/service/DefaultLocationService.ts:110:15)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at DefaultLocationService.dryRunCreateLocation (/Users/chris.suich/code/backstage/node_modules/@backstage/plugin-catalog-backend/src/service/DefaultLocationService.ts:148:32)\n at <anonymous> (/Users/chris.suich/code/backstage/node_modules/@backstage/plugin-catalog-backend/src/service/createRouter.ts:253:24)"
  },
  "request": {
    "method": "POST",
    "url": "/locations?dryRun=true"
  },
  "response": {
    "statusCode": 400
  }
}
```

I originally found this on Backstage 1.22.2 and found the warning below. Note: This error originally occurred on a private project so I've manually updated the log message to match my reproduction repo.

```sh
[1] 2024-06-13T22:39:49.905Z catalog warn Unable to read url, NotFoundError: Request failed for https://api.github.com/repos/csuich2/backstage-catalog-test/tree/main/pkg/contents/catalog-info.yaml?ref=meta, 404 Not Found type=plugin entity=location:csuich2/monorepo-locations location=url:https://git.corp.tanium.com/csuich2/backstage-catalog-test/tree/main/catalog-info.yaml
```

### 👟 Reproduction steps

See https://github.com/csuich2/backstage-catalog-test for reproduction steps and catalog-info.yaml files.

### 🖥️ Your Environment

Reproduced on both Backstage 1.22.2 and 1.27.7.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hello @csuich2 👋🏻 , we notice that you are using Backstage v1.22.2. Would you be able to reproduce the error on the latest version? Also, could you tell us where "pkg" comes from in the error URL 🙂 ?

**Comment by csuich2** [comment]
Hey @camilaibs - sorry if my issue wasn't clear. I originally found it in 1.22.2. I upgraded to 1.27.7 and found the same issue there.

`pkg/` is a directory in [Golang's recommended folder structure](https://github.com/golang-standards/project-layout?tab=readme-ov-file#pkg).

**Comment by freben** [comment]
Oh. Let me go back on this. I think I see what you mean now. There was a blob _elsewhere_ in the URL, I realized this after looking more carefully at your repo. Yeah that does look like failure to parse the URL for some reason or other. Seems like a proper bug.

**Comment by csuich2** [comment]
Ahh, I see. Sorry for the confusion.

I dug far enough to find that it seemed like a bug in https://github.com/IonicaBizau/git-url-parse/blob/master/lib/index.js but didn't have time to debug that library.

**Comment by freben** [comment]
Is there? I made a quick test

```ts
import parseGitUrl from 'git-url-parse';

describe('blob', () => {
  it('should return the correct url for a blob', () => {
    expect(
      parseGitUrl(
        'https://github.com/csuich2/backstage-catalog-test/blob/main/pkg/blob/catalog-info.yaml',
      ),
    ).toBe({});
  });
});
```

and the failure said

```
    - Object {}
    + Object {
    +   "commit": "main",
    +   "filepath": "pkg/blob/catalog-info.yaml",
    +   "filepathtype": "blob",
    +   "full_name": "csuich2/backstage-catalog-test",
    +   "git_suffix": false,
    +   "hash": "",
    +   "host": "github.com",
    +   "href": "https://github.com/csuich2/backstage-catalog-test/blob/main/pkg/blob/catalog-info.yaml",
    +   "name": "backstage-catalog-test",
    +   "organization": "csuich2",
    +   "owner": "csuich2",
    +   "parse_failed": false,
    +   "password": "",
    +   "pathname": "/csuich2/backstage-catalog-test/blob/main/pkg/blob/catalog-info.yaml",
    +   "port": "",
    +   "protocol": "https",
    +   "protocols": Array [
    +     "https",
    +   ],
    +   "query": Object {},
    +   "ref": "main",
    +   "resource": "github.com",
    +   "search": "",
    +   "source": "github.com",
    +   "toString": [Function anonymous],
    +   "token": "",
    +   "user": "",
    + }
```

those values look kinda ok i think 🤔 but it's getting late and i may be missing something.

I was starting to wonder if it's our relative-path-resolution that's to blame. But I'll have to get back to this some other time I think.

**Comment by csuich2** [comment]
You're right - that all looks good. I'm still learning to debug in Backstage so I likely missed something else.

**Comment by csuich2** [comment]
Progress. It _does_ appear to be a bug with `git-url-parse`. At some point during the entity analysis the url gets changed from:

`https://github.com/csuich2/backstage-catalog-test/blob/main/pkg/blob/catalog-info.yaml`, to:
`https://github.com/csuich2/backstage-catalog-test/tree/main/pkg/blob/catalog-info.yaml`

The difference is that the first `blob` is changed to `tree`. When I run a simple test with that url against `git-url-parse` the problem becomes more apparent.

```
   - Object {}
    + Object {
    +   "commit": "catalog-info.yaml",
    +   "filepath": "",
    +   "filepathtype": "blob",
    +   "full_name": "csuich2/backstage-catalog-test/tree/main/pkg",
    +   "git_suffix": false,
    +   "hash": "",
    +   "host": "github.com",
    +   "href": "https://github.com/csuich2/backstage-catalog-test/tree/main/pkg/blob/catalog-info.yaml",
    +   "name": "pkg",
    +   "organization": "csuich2/backstage-catalog-test/tree/main",
    +   "owner": "csuich2/backstage-catalog-test/tree/main",
    +   "parse_failed": false,
    +   "password": "",
    +   "pathname": "/csuich2/backstage-catalog-test/tree/main/pkg/blob/catalog-info.yaml",
    +   "port": "",
    +   "protocol": "https",
    +   "protocols": Array [
    +     "https",
    +   ],
    +   "query": Object {},
    +   "ref": "catalog-info.yaml",
    +   "resource": "github.com",
    +   "search": "",
    +   "source": "github.com",
    +   "toString": [Function anonymous],
    +   "token": "",
    +   "user": "",
    + }
```

**Comment by csuich2** [comment]
I've opened https://github.com/IonicaBizau/git-url-parse/issues/167 since this seems to be a bug in IonicaBizau/git-url-parse.
