### ISSUE TITLE
🐛 Bug Report: Limited support for merging configuration

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#25244]
### 📜 Description

Right now you can't have a plugin module extend the plugin configuration in a clean way.

### 👍 Expected behavior

It should be straightforward for modules to provide additional config schema

### 👎 Actual Behavior with Screenshots

 For example, if you have config schema for the plugin `foo`:

```ts
interface Config {
  foo?: {
    x?: number
  }
}
```

It's not possible to have a module define additional config keys, since the original plugin schema expects there to not be any additional keys:

```ts
interface Config {
  foo?: {
    y?: number
  }
}
```

### 📃 Provide the context for the Bug.

Discovered in https://github.com/backstage/backstage/pull/25142#discussion_r1639671471

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by acierto** [comment]
Not an issue, debugged the flow and found that I missed "configSchema" in package.json.
