### ISSUE TITLE
Persists catalogue tags filter in URL 

### ISSUE THREAD

**Issue by FabianHippmann** [backstage/backstage#2525]
Persist the catalogue tags in the URL - so that pages can link to the catalogue with tags. 

## Feature Suggestion

Because we can filter pretty much everything with tags - for our case I recommend using tags in the schema for defining what languages/frameworks etc. were used in a service/component/website. 

In the Techradar we could then automatically deeplink a certain language to a filter with the tech/language already selected - allowing developers to explore the services directly from the techradar

## Possible Implementation

component schema: 
```yaml
...
  tags:
    - go
    - redis
    - mux
...
```

**Catelogue filter url** 

`/catalog?tags=go,redis,mux`

`/catalog?tags=go`

**Comment by freben** [comment]
And what page you are on, if paging is used on the table :)

**Comment by andrewthauer** [comment]
Also, some sort of page/offset for the entity table (when added) should also be reflected in the URL.

**Comment by BA1RY** [comment]
Hi @Fox32 @freben , I would like to work on this. How would you want me to implement this?

**Comment by freben** [comment]
Hi,

This one may be a bit involved... What I can say to get going is that you want to look into the [EntityFilterGroupsProvider](https://github.com/spotify/backstage/blob/master/plugins/catalog/src/filter/EntityFilterGroupsProvider.tsx). It stores all of the currently selected filters. Among them you will see for example `selectedFilterKeys` and `selectedTags` that hold the state of what's selected by the user.

Somehow, that (and possibly other info) would travel to and from the location bar.

**Comment by BA1RY** [comment]
@freben  According to my understranding, entities in catalog should be filtered by using tags in URL. When filters are selected in catalog page, they should persist even after navigating to another page and backwards. Other filters like owned or starred, page in table should also be stored in the state. Please correct me if I'm wrong.

**Comment by benjdlambert** [comment]
@BA1RY seems right to me, will assign it to you!

**Comment by BA1RY** [comment]
@benjaminr Will work on it :smile:

**Comment by BA1RY** [comment]
@freben I'm made a PR. Please check it out and let me know about the changes/optimizatons to be made. Thanks :smile: 
I'm not sure about the naming conventions or types declared by me. I've tried to implement this feature similar to the one being implemented in cost-insights plugin.

**Comment by Fox32** [comment]
Still open, only implemented in the API explorer so far.
