### ISSUE TITLE
🚀 Feature: Documentation Request: Update "Local File (type: file) Configurations" in 'Catalog Configuration' section

### ISSUE THREAD

**Issue by rewixe** [backstage/backstage#25268]
### 🔖 Feature description

I would like to request updating the documentation on "Local File (type: file) Configurations" as some of the information seems to be inaccurate or out of date

### 🎤 Context

The documentation in this page which gives examples of [local file configurations](https://backstage.io/docs/features/software-catalog/configuration/#local-file-type-file-configurations) seems to be inaccurate and missing details, for example the catalog examples link does not point to anything, perhaps it should point to [this file](https://github.com/backstage/backstage/blob/867bebf032e58fe6c82a1f143c015c4640ca4dfd/packages/create-app/templates/default-app/app-config.yaml.hbs#L80), and it also says `You are also not able to use placeholders in them like $text` whereas like text would be yaml, json, etc. Adding this information to this doc will reflect actual catalog capabilities.

### ✌️ Possible Implementation

The documentation should be updated such that :

- Links to examples point to existing files
- Accurate information is provided about catalog capabilities 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by rewixe** [comment]
Can this be assigned to me? I'm happy to work on this

**Comment by freben** [comment]
Sure, thanks! 🙏
