### ISSUE TITLE
🚀 Feature: Update CLI versions:bump default pattern to include @backstage-community packages

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#25276]
### 🔖 Feature description

Community plugins have been moved to a different npm package namespace and are no longer being updated from `backstage-cli version:bump` command without providing a custom `--pattern` option.

### 🎤 Context

Would like to update community plugin packages without needing to customize the `versions:bump` command options

### ✌️ Possible Implementation

Update the [DEFAULT_PATTERN_GLOB](https://github.com/backstage/backstage/blob/master/packages/cli/src/commands/versions/bump.ts#L52) to include the `@backstage-community/*` pattern.

`@backstage?(-community)/*`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @bforbis @benjdlambert @darylgraham, as the Community Plugins all get released on their own cadence and are not strictly tied to the Backstage release cycles anymore does it make sense to make this change?

As it's possible to do this already using: `yarn backstage-cli versions:bump --pattern '@{backstage,backstage-community}/*' `.
