### ISSUE TITLE
🚀 Feature: Peer Dependencies for Core Packages

### ISSUE THREAD

**Issue by aramissennyeydd** [backstage/backstage#25278]
### 🔖 Feature description

I'm trying to use Backstage in a pnpm monorepo. When trying to start the application after "fixing" some yarn specific checks with `backstage-cli start`, I run into the following error,
```
Cannot read properties of null (reading 'breakpoints')
```

After a bit of debugging, this is due to how pnpm is resolving the peer dependencies down to `@material-ui/core` and `@material-ui/styles`. For one we get a peer dependency on `@types/react: 18.2.0` and the other `@types/react: 18.2.79`. I think this is due to some Backstage packages not listing `@types/react` in their `peerDependencies` as well as listing them in their `dependencies`.

### 🎤 Context

Supporting additional package managers has been mentioned in #20658, this is part of the path to that.

### ✌️ Possible Implementation

Moving the types to dev dependencies and listing them in peer dependencies for Backstage packages.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by adminy** [comment]
I wonder if just manually editing the `pnpm-lock.yaml` file could fix these issues temporarily. create a patch that could be applied.
