### ISSUE TITLE
Bug (Scaffolder): The filename or extension is too long.

### ISSUE THREAD

**Issue by harshilparmar** [backstage/backstage#2527]
After #2448 fix, getting different error.

![docError](https://user-images.githubusercontent.com/45915468/93668250-e1533d80-faa8-11ea-8464-a2118e6ff2e5.PNG)
![error](https://user-images.githubusercontent.com/45915468/93668257-e87a4b80-faa8-11ea-9b81-7ce838118ac3.PNG)
![error2](https://user-images.githubusercontent.com/45915468/93668264-ed3eff80-faa8-11ea-959b-459e4b0a59d2.PNG)

## Context
Please refer #2448 for more details.

**Comment by XBeg9** [comment]
Same issue here, any ideas how to fix?

**Comment by OrkoHunter** [comment]
The TechDocs error of long file/repository name in Windows was fixed in this PR by @hooloovooo 
 https://github.com/backstage/backstage/pull/2538

It may be helpful for Scaffolder's preparer too.

**Comment by XBeg9** [comment]
@OrkoHunter I just cloned the latest `main` branch, and it shows the same error as above. :(

**Comment by freben** [comment]
@XBeg9 Right but, he is referring to another part of the system - the techdocs part - while this error is in the scaffolding (software templates) system.

If you are using a cloned repo, would you be able to add that same code

```ts
// Enables core.longpaths on windows to prevent crashing when checking out repos with long foldernames and/or deep nesting
// @ts-ignore
NodeGit.Libgit2.opts(28, 1);
```

In this location in your repo?

https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/service/router.ts#L33

And report back if it fixes your problem.

**Comment by XBeg9** [comment]
This does fix the problem, I am creating the PR. Btw, I am on Mac :) and was getting this issue.
