### ISSUE TITLE
Move `readCorsOptions + other readers` over with the `RootHttpRouter` implementation

### ISSUE THREAD

**Issue by camilaibs** [backstage/backstage#25273]
To do after https://github.com/backstage/backstage/issues/25272

**Comment by camilaibs** [comment]
Apparently, the readers were already moved by [this](https://github.com/backstage/backstage/pull/25293) pull request.
Is there anything else that needs to be done @freben ?

**Comment by Rugvip** [comment]
Yep, closing!
