### ISSUE TITLE
🚀 Feature: Easier customization support in authentication backend library to forwarding custom (authentication) cookies from authentication provider 

### ISSUE THREAD

**Issue by gusega** [backstage/backstage#25280]
### 🔖 Feature description

Use an authenticator and a list of cookies to forward to forward back authentication cookies from the authentication server.

### 🎤 Context

When I authenticate with my authorization server I get back an access token and an authentication cookie in `Set-Cookie` header. When I get protected resource, I provide both access token and the cookie. 

While backstage backend authentication customizations are very nice, the authenticator does not return cookies and cookie manager does not allow setting custom cookies. 

I create `AuthProviderRouteHandlers` with my own copy of `createOAuthRouteHandlers()` function that sets cookies in there.

### ✌️ Possible Implementation

`OAuthCookieManager` accepts a list of cookies to forward as optional parameter. The `Authenticator#authenticate()` returns all the cookies set with `Set-Cookie` and the cookie manager puts the ones that are to forward, if any on the response.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Maybe! Ping @Rugvip (who's on vacation; expect a few weeks before we get to this) on the design question. Feel free to make a PR in the mean time and we can continue the design details there.

Does your provider return an actual refresh token separately too, with offline scope or so?

Are you accessing resources statically with this (like images or whatnot), that aren't requested using explicit `fetch` calls?

**Comment by gusega** [comment]
Hi @freben , @Rugvip  

> Does your provider return an actual refresh token separately too, with offline scope or so?

Yes

> Are you accessing resources statically with this (like images or whatnot), that aren't requested using explicit fetch calls?

No, access token + cookie protect the API, so explicit calls.

**Comment by freben** [comment]
Alright. Slightly surprising that it requires both.

**Comment by gusega** [comment]
Both, you mean both refresh token and the cookie? From what I understand, if attacker steals the access token, they can't use it alone. I must provide both the access token and a matching cookie. It's basically an additional security measure.

For the offline flow, I must also provide the refresh token together with the same matching cookie to get new access token. 

Basically the cookie is a long lasting piece of authentication.

**Comment by gusega** [comment]
Ok, for now, I think, the most reasonable way to allow customization of the response would be to pass response (`express.Response`) to `authenticator.authenticate()`. This would allow me add necessary cookies on the response.

**Comment by gusega** [comment]
I created a PR: add response to authenticator parameters: https://github.com/backstage/backstage/pull/25587

please take a look.

**Comment by Rugvip** [comment]
The limited use of cookies is an architectural decision that we've taken to simplify integration with external services and split deployments. If we were to use cookies for API authentication we'd be dealing with either proxying a lot more requests, dealing with domain restrictions, or messy 3rd party cookies.

If you do want to implement this yourself as a deeper customization, you can decorate the handlers returned by `createOAuthRouteHandlers` within `createOAuthProviderFactory`, where you have access to the request and response objects.

Gonna close this as it's not something we want to add at this point

**Comment by Rugvip** [comment]
Oh, and you do also have `input.req.res`, which allows you to access the response object.
