### ISSUE TITLE
🚀 Feature: Documentation Request: Update 'Testing with Jest' documentation

### ISSUE THREAD

**Issue by rewixe** [backstage/backstage#25297]
### 🔖 Feature description

I would like to request updating the 'Testing with Jest' documentation as some of the documentation is missing or incomplete

### 🎤 Context

The documentation in [this page](https://backstage.io/docs/plugins/testing) is incomplete in parts, for example it does not describe how to run more than one suite of tests, and there is a section 'Testing Utilities' which is empty. Improving this documentation will make it easier to test with Jest.

### ✌️ Possible Implementation

The documentation should include:

- An example of how to specify multiple suites to run
- A description of testing utilities

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by rewixe** [comment]
I am happy to take on this work and make these changes.

**Comment by freben** [comment]
Sure! It looks mostly OK though, but I'm sure there's stuff that could be improved 🙏
