### ISSUE TITLE
🐛 Bug Report: Attempt to clone azure repo failing

### ISSUE THREAD

**Issue by GDivino** [backstage/backstage#25294]
### Problem
While trying to clone a repo using the `azure:repo:clone` action from [Parfuemerie-Douglas' plugin](https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-repositories), I noticed that I am not able to use the branch input successfully (unless we specify the default branch).

### Code (template.yaml)
```
id: cloneRepo
name: Clone Azure Repo
action: azure:repo:clone
input:
  remoteUrl: ...
  branch: new-branch
  targetPath: ./new-folder
```

For some reason, only using master works. Is this perhaps because the code clones the repository with only the default branch?

### 👍 Expected behavior

Successful clone and checkout of the branch

### Error message (in the backstage logs)
```
2024-06-12T14:11:59.000Z info: Creating new remote...
2024-06-12T14:11:59.000Z info: Checking out branch...
2024-06-12T14:11:59.000Z NotFoundError: Could not find origin/new-branch
```

### 👟 Reproduction steps

Simply utilize [this custom action](https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-repositories) when cloning an azure devops repository

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @GDivino, have you submitted an issue in [scaffolder-backend-module-azure-repositories](https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-repositories)? That's going to be the best place to get support 👍

**Comment by GDivino** [comment]
I have, but it seems to have a lack in support right now 😔

**Comment by awanlin** [comment]
Ok, you won't get much support from here though as the code in question is not part of the core Backstage framework, sorry.

**Comment by GDivino** [comment]
Thanks for your quick responses @awanlin. I went ahead and dove into solving it myself in the node_modules. Will set up a PR specific to the plugin. Thanks!

**Comment by pankajdevrani** [comment]
@GDivino Did you get any solution for this? I am also facing the same issue
