### ISSUE TITLE
🐛 Bug Report: Setting up Github auth on ec2

### ISSUE THREAD

**Issue by lwara** [backstage/backstage#25291]
### 📜 Description

I am configuring backstage on an ec2 instance. I run it using localhost (default setting ) and i configured nginx to point to the localhost backstage app. And using guest feautures i am able to load the app on browser using a public address of my  ec2 instance. the problem is , i need to configure github and it keeps failing  : "SITE CANT BE REACHED"

### 👍 Expected behavior

authenticate github 

### 👎 Actual Behavior with Screenshots

![ksnip_20240618-113459](https://github.com/backstage/backstage/assets/43346571/e7d7181e-cc6e-4a30-9d63-dd9753c6121a)

### 👟 Reproduction steps

followed instruction on how to setup a github authentiction from https://backstage.io/docs/auth/github/provider 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Both `app.baseUrl` and `backend.baseUrl` must be set "as seen from the browser". I.e. if you go to `https://backstage.example.net` to visit your backstage instance, you typically want to set both of those config values to that.

This is completely unrelated to what ports your service is listening on (that's controlled with the `backend.listen` directive if it can't be deduced from the base UR) or what your deployment topology is.

The authorization callback URL in your oauth settings on the remote auth provider needs to be set the same way too - it will want to call back to `<your public url>/api/auth/<provider>/handler/frame` typically for a normal oauth based one.

The URLs in the docs are what works for local dev. For production, the values have to be changed accordingly. And you also will need to make TWO oauth apps; one for local dev and one for prod, since the callback URLs will be different.

**Comment by lwara** [comment]
thanks, it worked . also i had to add my username to examples/org.yaml

**Comment by lwara** [comment]
hi @freben . 
i configure the auth app with this 
![image](https://github.com/backstage/backstage/assets/43346571/7619a8b3-5ff9-4530-96e0-4d816137b81b)
 Then when i start the application it point to githbub, sign in , but then when i click authorize it gives me this :  
![image](https://github.com/backstage/backstage/assets/43346571/3764b60d-a67f-411d-9265-c53ca30d5f7d)

**Comment by lwara** [comment]
and here are my configurations : Loaded config from app-config.yaml
app:
  title: EGPAF Backstage App
  baseUrl: http://localhost:3000
organization:
  name: EGPAF-HIS
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src:
      - "'self'"
      - "http:"
      - "https:"
  cors:
    origin:
      - https://abc.org
    methods:
      - GET
      - HEAD
      - PATCH
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowedHeaders:
      - Authorization
      - Origin
      - X-Requested-With
      - Content-Type
      - Accept
    credentials: true
  database:
    client: better-sqlite3
    connection: <secret>
integrations:
  github:
    - host: github.com
techdocs:
  builder: local
  generator:
    runIn: docker
  publisher:
    type: local
auth:
  environment: development
  providers:
    github:
      development:
        clientId: Ov23liQMaxWsB82t7aM3
        clientSecret: <secret>
        scopes:
          - read:org
          - repo
          - workflow
          - read:user
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
      production:
        clientId: Ov23liQMaxWsB82t7aM3
        clientSecret: <secret>
        scope:
          - read: org
          - read: user
          - user: email
          - repo
          - workflow
    guest: {}
    google:
      development:
        clientId: a3a4cf8631d9fa70eda1f74c65148f83183a7869
        clientSecret: <secret>
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        - Component
        - System
        - API
        - Resource
        - Location
  locations:
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow:
            - Template
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow:
            - User
            - Group
  providers:
    githubOrg:
      id: production
      githubUrl: https://github.com
      orgs:
        - WAMK-DEVOPS
      schedule:
        frequency: PT30M
        timeout: PT3M

Done in 3.17s.

**Comment by lwara** [comment]
{"error":{"name":"NotFoundError","message":"Unknown auth provider 'github'","stack":"NotFoundError: Unknown auth provider 'github'\n    at <anonymous> (/home/ubuntu/backstage-egpaf-app-live/node_modules/@backstage/plugin-auth-backend/src/service/router.ts:175:11)\n    at handleReturn (/home/ubuntu/backstage-egpaf-app-live/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /home/ubuntu/backstage-egpaf-app-live/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at Layer.handle [as handle_request] (/home/ubuntu/backstage-egpaf-app-live/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/ubuntu/backstage-egpaf-app-live/node_modules/express/lib/router/index.js:328:13)\n    at /home/ubuntu/backstage-egpaf-app-live/node_modules/express/lib/router/index.js:286:9\n    at param (/home/ubuntu/backstage-egpaf-app-live/node_modules/express/lib/router/index.js:365:14)\n    at param (/home/ubuntu/backstage-egpaf-app-live/node_modules/express/lib/router/index.js:376:14)\n    at Function.process_params (/home/ubuntu/backstage-egpaf-app-live/node_modules/express/lib/router/index.js:421:3)\n    at next (/home/ubuntu/backstage-egpaf-app-live/node_modules/express/lib/router/index.js:280:10)\n    at /home/ubuntu/backstage-egpaf-app-live/node_modules/express/lib/router/index.js:646:15\n    at next (/home/ubuntu/backstage-egpaf-app-live/node_modules/express/lib/router/index.js:265:14)\n    at Function.handle (/home/ubuntu/backstage-egpaf-app-live/node_modules/express/lib/router/index.js:175:3)\n    at router (/home/ubuntu/backstage-egpaf-app-live/node_modules/express/lib/router/index.js:47:12)\n    at handleReturn (/home/ubuntu/backstage-egpaf-app-live/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at router (/home/ubuntu/backstage-egpaf-app-live/node_modules/express-promise-router/lib/express-promise-router.js:64:7)"},"request":{"method":"GET","url":"/api/auth/github/?code=e792ffc71fa6f1fed91d&state=6e6f6e63653d7a524d697936394f6b77593751514d6a4d796363526725334425334426656e763d646576656c6f706d656e74266f726967696e3d68747470732533412532462532466261636b73746167652e6869736d616c6177692e6f726726666c6f773d706f7075702673636f70653d7265616425334175736572"},"response":{"statusCode":404}}
