### ISSUE TITLE
🚀 Feature: Permissions catalogConditions : verify the children of the owner's group.

### ISSUE THREAD

**Issue by Yghore** [backstage/backstage#25299]
### 🔖 Feature description

Add functions to catalogConditions to verify the children of the owner's group.

![BACKSTAGE_PERMISSIONS](https://github.com/backstage/backstage/assets/23425839/2910c533-a464-48ff-a5c9-0ab6d95425da)

Currently, catalogConditions.isEntityOwner() 
verifies only the first level of the group hierarchy (Group B) 
and not the higher levels (Group A). 
I propose adding a function to verify groups with depth options.

### 🎤 Context

```ts
return createCatalogConditionalDecision(_request.permission, {
  allOf: [
    catalogConditions.isEntityKind({kinds: ['Template']}),
    {
      anyOf: [
        catalogConditions.isEntityGroupDepthOwner({claims: _user?.identity.ownershipEntityRefs ?? [], depth: 3}),
        // OR
        catalogConditions.isEntityOwner({claims: _user?.identity.ownershipEntityRefs ?? [], depth: 4 },), // default depth = 1
      ]
    }
  ],
});
```

### ✌️ Possible Implementation

https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/permissions/rules/isEntityOwner.ts#L44

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
This is indeed intentional; ownership is meant to be deduced at auth time through the sign in resolver. https://backstage.io/docs/auth/identity-resolver
