### ISSUE TITLE
🐛 Bug Report: Cannot find module 'morgan'

### ISSUE THREAD

**Issue by dep** [backstage/backstage#25303]
### 📜 Description

This just started occurring today during this step of our automated CI process, namely the `[backstage] Publish Documentation` step:

```
- name: "[backstage] Install Python Dependencies"
  run: pip3 install mkdocs-techdocs-core==1.* mkdocs-section-index==0.*
- name: "[backstage] Install Node Dependencies"
  run: npm install -g @techdocs/cli
- name: "[backstage] Generate Tech Docs"
  run: techdocs-cli generate --no-docker --source-dir ./ --output-dir ./site
- name: "[backstage] Publish Documentation"
  run: techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
```

### 👍 Expected behavior

Runs without error

### 👎 Actual Behavior with Screenshots

```
Run techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
Cannot find module 'morgan'
Require stack:
- /opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/@techdocs/cli/node_modules/@backstage/backend-common/dist/index.cjs.js
- /opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/@techdocs/cli/dist/cjs/publish-CnXRqKHz.cjs.js
- /opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/@techdocs/cli/dist/index.cjs.js
- /opt/hostedtoolcache/node/20.4.0/x64/lib/node_modules/@techdocs/cli/bin/techdocs-cli
Error: Process completed with exit code 1.
```

### 👟 Reproduction steps

Use provided steps above

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by dep** [comment]
Rolling back to the following versions has alleviated the problem at this exact moment:

```
- name: "[backstage] Install Python Dependencies"
  run: pip3 install mkdocs-techdocs-core==1.3.5 mkdocs-section-index==0.*
- name: "[backstage] Install Node Dependencies"
  run: npm install -g @techdocs/cli@1.8.11
- name: "[backstage] Generate Tech Docs"
  run: techdocs-cli generate --no-docker --source-dir ./ --output-dir ./site
- name: "[backstage] Publish Documentation"
  run: techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
```

**Comment by polothy** [comment]
Ran into the same problem, thanks for providing a workaround.

**Comment by freben** [comment]
Thanks for reporting!

It seems that building, viewing and publishing locally works at least. Maybe it's somehow tied to the S3 publisher specifically; I'll keep looking. Any additional information is helpful! For example @polothy do you also publish specifically to S3 and ran into it only in the publish step?

**Comment by jonathonlacher** [comment]
This failed for me also, pinning did resolve the issue. We're publishing to `azureBlobStorage`. It failed only on publish.

**Comment by polothy** [comment]
> For example @polothy do you also publish specifically to S3 and ran into it only in the publish step?

Yes, it only failed on publish to S3 bucket.  We run on CI/CD if that helps (so clean environment each time).

**Comment by chap-dr** [comment]
Seeing this aswell, publishing to GCS.
