### ISSUE TITLE
🐛 Bug Report: BackstageError component removed class "BackstageErrorPage-container" in a recent update

### ISSUE THREAD

**Issue by michaelbarone** [backstage/backstage#25304]
### 📜 Description

In some cases I want to hide the BackstageError display from end users as it can sometimes occur when they dont have permissions for certain features on a page and shouldnt know about any issue to improve user experience.

I have this on certain pages like the EntityPage component to omit the error when permissions are not available:
```
<style>
    [class*="BackstageErrorPage-container"] {
        display:none;
    }
</style>
```

It appears after a recent update to current, this is no longer functioning and appears this class is not being applied to the BackstageError component on any pages.

### 👍 Expected behavior

We should have a way to silence/hide the Backstage Error page display when desired.  Either by using the old functionality of applying a specific class such as "BackstageErrorPage-container" to the parent/container element so we can apply custom css where needed, or another option to fulfil this use case.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/4596968/58e58525-9d32-43b8-9880-5d29fe1a5f1a)

As seen in the screenshot, this used to work until we recently updated to the current build.  We dont need this error to show as the user still has access to some relevant info on this page and the error is just taking up un-needed space in this context, and is expected because the user doesnt have some permissions on this page for additional data to display.

### 👟 Reproduction steps

Any page that shows the error for a single, or several components on the page while still allowing access to view other components on the page will result in seeing the error page as blocks of content.  Ideally, we can target these blocks with css and do a display: none or similar to remove the error from view when it is expected.

Using the dev tools, we can hide the error container manually to see the expected behavior and previous functionality of adding the below code to any page:
```
<style>
    [class*="BackstageErrorPage-container"] {
        display:none;
    }
</style>
```

### 📃 Provide the context for the Bug.

Yes, some users do not have full repository access which some components require, causing access issues and the BackstageError component to be displayed.  This is expected, and we would like to hide the error from view to have a better user experience for users with restricted access.

### 🖥️ Your Environment

OS:   Windows_NT 10.0.22631 - win32/x64
node: v20.11.0
yarn: 1.22.18
cli:  0.26.6 (installed)
backstage:  1.27.6

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.7.5
  @backstage/backend-common                                        0.21.7, 0.22.0
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/backend-test-utils                                    0.3.8
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.6
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.67
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-github                  0.6.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.11.0
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-home-react                                     0.1.13
  @backstage/plugin-home                                           0.7.4
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-backend                             0.5.42
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.7
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node                                0.4.4
  @backstage/plugin-scaffolder-react                               1.8.6
  @backstage/plugin-scaffolder                                     1.20.1
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-pg                       0.5.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey :wave:

I'm not sure that the approach of overriding this with CSS is a stable one, as these classes could change over time, and or when we move to different versions of `mui`.

Have you considered providing your own `NotFoundErrorPage` component where you can add the logic there instead and hide the default page if needed?

It's an option you pass to `createApp`.

```tsx
const app = createApp({
  ...
  components: {
    NotFoundErrorPage: MyCustomErrorPageComponent,
  }
});
```

**Comment by michaelbarone** [comment]
Interesting, I didnt know about that function.. Ill take a look and see if I can get this working in a less hacky way.  Appreciate the response.

**Comment by michaelbarone** [comment]
I was able to get a working solution for my issue by creating a custom error page component as mentioned above.  I added some helpful links to the backstage repo with examples to help with this process.
