### ISSUE TITLE
🐛 Bug Report: loadPhotos ignored for userGroupMember In the Microsoft Entra Tenant Data

### ISSUE THREAD

**Issue by msfe** [backstage/backstage#25313]
### 📜 Description

In the [Microsoft Entra Tenant Data](https://backstage.io/docs/integrations/azure/org) it is possible to load users through filters/search or the same for userGroupMember. In large organizations the docs also mention the issues with User Photos, however this property is only respected for users and ignored for userGroupMember.

If you try to be smart and set it in user while using userGroupMember you get an error.

```
Error: userFilter and userGroupMemberFilter are mutually exclusive, only one can be specified.
```

This looks like the place where we are lacking a few lines of code, but don't have the full picture of the setup.

https://github.com/backstage/backstage/blob/29a0f56831de683df148101a4acaa81971b2965f/plugins/catalog-backend-module-msgraph/src/microsoftGraph/config.ts#L286-L310

### 👍 Expected behavior

Photos should not be loaded for users when using _loadPhotos: false_ for userGroupMember. This following is an example configuration that i expect not to load photos.

```
catalog:
  providers:
    microsoftGraphOrg:
      default:
        tenantId: ${AZURE_TENANT_ID}
        userGroupMember:
          filter: "displayName eq 'my-group'"
          loadPhotos: false
```

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/1841491/fe7d7c73-310c-4c94-8759-7cccd5230eee)

Could also confirm with smaller group that photos was indeed loaded when using this setup.

### 👟 Reproduction steps

Configure a standard Azure catalog integration.

Try to set _loadPhotos: false_ for userGroupMember

```
catalog:
  providers:
    microsoftGraphOrg:
      default:
        tenantId: ${AZURE_TENANT_ID}
        userGroupMember:
          filter: "displayName eq 'my-group'"
          loadPhotos: false
```

### 📃 Provide the context for the Bug.

We want to include a few selected groups with guest users as well as tenant members. We have all required dynamic groups in place to do this.

### 🖥️ Your Environment

OS:   Linux 6.5.0-1021-azure - linux/x64
node: v20.14.0
yarn: 1.22.22
cli:  0.26.5 (installed)
backstage:  1.27.0-next.0

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.7.3
  @backstage/backend-common                                        0.21.8-next.0, 0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.5
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.66
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.26
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.10.11-next.2
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-home-react                                     0.1.13
  @backstage/plugin-home                                           0.7.4
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.15
  @backstage/plugin-permission-backend                             0.5.42
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.6
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node                                0.4.4
  @backstage/plugin-scaffolder-react                               1.8.5
  @backstage/plugin-scaffolder                                     1.20.0
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-pg                       0.5.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.22, 1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-tech-radar                                     0.7.4
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.5.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Alright, that sounds like an omission. Happy to accept a fix PR 🙏

**Comment by msfe** [comment]
I don't have a good understanding of this codebase. But could it be so easy as updating from

```ts
 const loadUserPhotos = config.getOptionalBoolean('user.loadPhotos'); 
```

To...

```ts
 const loadUserPhotos = config.getOptionalBoolean('user.loadPhotos') ?? config.getOptionalBoolean('userGroupMember.loadPhotos'); 
```

Or would this also require updates to schema and/or further logic?

**Comment by Parsifal-M** [comment]
FWIW this _seems_ to work for us somehow 😅 

```yaml
  providers:
    microsoftGraphOrg:
      default:
        ....
        user:
          loadPhotos: false
        userGroupMember:
          search: ...
        group:
          search: ...
        schedule:
          ....
```

But not sure if its intended that way (not looked at the code)

**Comment by msfe** [comment]
Oh, that may actually work. I think i was stupid and included a user filter to filter zero users as well to avoid the risk of default load all users. But it looks like that could actually be a workaround. Think this could still be worth fixing or clarify the documentation. Thanks for sharing @Parsifal-M!

**Comment by msfe** [comment]
Could also confirm now that it worked for me to import users. Ran into a new issue that the standard signin resolver didn't work now though. But even if i have to write a new resolver that feels more doable to fix on my side

```
auth:
    providers:
      microsoft:
        development:
          ...
          signIn:
            resolvers:
              - resolver: emailMatchingUserEntityProfileEmail
```

**Comment by freben** [comment]
Alright! Does this mean that we can close the issue?

**Comment by msfe** [comment]
I think it would be good to clarify documentation. Opened a PR with that minor modification that I would have liked to see to avoid opening this issue 😄

**Comment by msfe** [comment]
PR merged, closing. Thanks for the support everyone 👍
