### ISSUE TITLE
🐛 Bug Report: Pagination options are getting overridden in `PaginatedCatalogTable`

### ISSUE THREAD

**Issue by piatkiewicz** [backstage/backstage#25320]
### 📜 Description

Sorry if this isn't a bug, I just can't find a reasoning behind this.

I'm activating server-side pagination by adding `pagination` property to `<CatalogIndexPage />` like described here: https://backstage.io/docs/features/software-catalog/catalog-customization/#pagination

It makes pagination options disappear, I can't control page size from now. It because those options are getting overridden here:
https://github.com/backstage/backstage/blob/29a0f56831de683df148101a4acaa81971b2965f/plugins/catalog/src/components/CatalogTable/PaginatedCatalogTable.tsx#L40-L48

There is a comment saying it's needed for server-side rendering, but I don't know the details.

### 👍 Expected behavior

Options like `pageSize` should still display

### 👎 Actual Behavior with Screenshots

No page size options

![image](https://github.com/backstage/backstage/assets/8793897/b9782469-cbe2-4512-9393-78f8656ac48e)

### 👟 Reproduction steps

1. Fill catalog with example data
2. Add `pagination` to `<CatalogIndexPage />`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by vinzscam** [comment]
If your goal is to make the backend return more entities than the default 20 then you can do this by:

```tsx
<Route path="/catalog" element={<CatalogIndexPage pagination={{ limit: 50 }} />} />
```

the `pageSize` prop is locked on purpose to follow the number of entities fetched on each batch.

**Comment by piatkiewicz** [comment]
Shouldn't the total number of entities be displayed? Also numbers of currently displayed records? And first/last page buttons?
![image](https://github.com/backstage/backstage/assets/8793897/16e9faf4-f9d1-40af-aa5c-4fafe47083c4)

Total number of items is returned from backend:
![image](https://github.com/backstage/backstage/assets/8793897/5a77b873-16af-4bb7-ad78-4a22a01f4e60)

And `pageSizeOptions` is an empty array here. 
`byQuery` endpoint accepts `limit` so why can't that be integrated?

If I pass `pageSizeOptions` to regular `<CatalogIndexPage />` like this, it works:
`<Route path="/catalog" element={<CatalogIndexPage tableOptions={{pageSizeOptions: [5,10,20]}}/>} />`

![image](https://github.com/backstage/backstage/assets/8793897/f735c142-3309-4f53-9dff-7c18654353ec)

But if I do the same with pagination I don't have those options:
`<Route path="/catalog" element={<CatalogIndexPage pagination tableOptions={{pageSizeOptions: [5,10,20]}}/>} />`

![image](https://github.com/backstage/backstage/assets/8793897/59fa7bb7-ff1e-4b36-b6b7-7061282d3c50)

**Comment by vinzscam** [comment]
the thing is that you can't jump to the last page. You can only move forward and backwards one page at the time. Also changing page size would reset pagination, as you lose track of where you are. The total number of items could be displayed though.

**Comment by piatkiewicz** [comment]
Oh, I see it operates on `cursor`/`nextCursor`/`previousCursor` parameters, not skipping records. I didn't dive into that yet to understand it fully, but seams reasonable in this case. Thanks for the comments!

**Comment by vinzscam** [comment]
> Oh, I see it operates on `cursor`/`nextCursor`/`previousCursor` parameters, not skipping records. I didn't dive into that yet to understand it fully, but seams reasonable in this case. Thanks for the comments!

thanks for looking into this anyway 🙏
