### ISSUE TITLE
🐛 Bug Report: Custom fonts are not getting loaded with v 1.24.0 onwards

### ISSUE THREAD

**Issue by Nitinvonage** [backstage/backstage#25343]
### 📜 Description

I installed the latest version (v1.28) using npx @backstage/create-app@latest and added my font CSS file to load the font. However, none of the fonts are being loaded in the network tab. This behaviour has started coming from v1.24.0 onwards, before that custom fonts were loading

### 👍 Expected behavior

Custom fonts should get loaded

### 👎 Actual Behavior with Screenshots

Fonts are not loading
![image](https://github.com/backstage/backstage/assets/110883891/99fd2ccc-7185-43b7-bdd7-1e533ee79f79)

### 👟 Reproduction steps

1. Should be on v 1.24.0 or greator
2. Import css file in App.tsx, this css will be loading custom fonts using @font-face
3. Font load request should appear in the chrome network tab

### 📃 Provide the context for the Bug.

https://discord.com/channels/687207715902193673/1252313308099252336

### 🖥️ Your Environment

OS: MacOS Sonoma v14.5- M1 Chip
node: v18.12.1
yarn: 4.1.0
cli: 0.26.9 (installed)
backstage: 1.28.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Hey can you check if the resource corresponding to that font ever makes it into the `<head>` section of your index at all?

**Comment by freben** [comment]
Trying to reproduce in the main repo:

* Download some TTF font and convert to WOFF2
* Put WOFF file in `packages/app/src`
* Make a CSS file also in `packages/app/src` with a `@font-face` pointing to the WOFF2 file
* Add an `import './fonttest.css'` in my `App.tsx`
* Run `yarn tsc:full`, `yarn build:all`
* Observe that `packages/app/dist` has an `index.html` file with `<link href="/static/main.7a486c2d.css" rel="stylesheet">`
* Observe that `packages/app/dist/static/main.7a486c2d.css` has the expected `@font-face` declaration with `src: url(/static/KGDownBadCryingAtTheGym.fdf091ff58ef83a7550b.woff2) format('woff2');`
* Observe that that woff2 file does exist in packages`/app/dist/static`

So to me, it looks like it gets packaged correctly.

**Comment by Nitinvonage** [comment]
Inspect the HTML Document Manually, I inspected the HTML document to see if the font resource is included in the <head> section.
In my case i have defined a css file to load fonts like this and i found 
![Screenshot 2024-06-25 at 5 33 35 PM](https://github.com/backstage/backstage/assets/110883891/4e2c7bb7-d67e-4352-b821-d999029c11c7)

```
@font-face {
	font-family: SpeziaCompleteVariableUpright;
	font-stretch: 50% 200%;
	font-weight: 1 1000;
	src: url(/static/SpeziaCompleteVariableUprightWeb.9b285f761aefb2b78656.woff2) format('woff2');
}

@font-face {
	font-family: SpeziaCompleteVariableItalic;
	font-stretch: 50% 200%;
	font-weight: 1 1000;
	src: url(/static/SpeziaCompleteVariableItalicWeb.0e8f0e1363938997ca32.woff2) format('woff2');
}
```

**Comment by Nitinvonage** [comment]
@freben all the steps you mentioned, we were doing the same but for us Font is not loading. is it happening for you, do you see a network req for font in your browser

**Comment by freben** [comment]
I've backed out of the repro case for the time being - did you actually use the font as well? I am wondering if this is just browser semantics, it not loading fonts that it isn't trying to render.

**Comment by Nitinvonage** [comment]
the old backstage version is still rendering font correctly, we have not changed anything there in the new backstage version. 
Only thing to mention here is we are deploying frontend & backend separately.

**Comment by camilaibs** [comment]
@Nitinvonage could you please create a reproduction repo with fresh create-app and share it with us? We have been unable to reproduce the error.

**Comment by Nitinvonage** [comment]
https://github.com/nitin15j/my-backstage-app

**Comment by camilaibs** [comment]
I forked your repository and noticed the behavior Freben mentioned in this comment: https://github.com/backstage/backstage/issues/25343#issuecomment-2188851532

The font is loaded as soon as it is used in a component, check this [branch](https://github.com/camilaibs/backstage-25343/compare/main...camilaibs:backstage-25343:configure-font-css?expand=1): 

![image](https://github.com/backstage/backstage/assets/6290749/c3d13765-10aa-4e26-a54e-b95eccfd455c)

![image](https://github.com/backstage/backstage/assets/6290749/134fa157-d981-4d5d-ae1c-cac875aea263)


There is also a recommended way to override the font for your entire app using themes:
https://backstage.io/docs/getting-started/app-custom-theme/#custom-fonts

It's working for me too, see this [other branch](https://github.com/camilaibs/backstage-25343/compare/main...camilaibs:backstage-25343:customizing-font?expand=1):

![image](https://github.com/backstage/backstage/assets/6290749/f14678cc-1e94-44da-bbab-4ab455c8db6c)
