### ISSUE TITLE
 Create another login call my api

### ISSUE THREAD

**Issue by quan1997ap** [backstage/backstage#25367]
### 🔖 Feature description

Hi team.
I have api login. I want to custom form login to use my login API.
But I can't do it. Can you give me some suggestions ?
Thank you.

### 🎤 Context

Custom login form to call existed API login.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
What type of auth is it? If it's got a reverse authenticating proxy, then you may want to look into [proxy auth](https://backstage.io/docs/auth/#sign-in-with-proxy-providers). This usually gives by far the best end user experience.

But those auth docs in general contain a lot of useful information, like how to replace the sign in page with a custom one and making new auth providers if you need backend support, etc.

**Comment by quan1997ap** [comment]
> What type of auth is it? If it's got a reverse authenticating proxy, then you may want to look into [proxy auth](https://backstage.io/docs/auth/#sign-in-with-proxy-providers). This usually gives by far the best end user experience.
> 
> But those auth docs in general contain a lot of useful information, like how to replace the sign in page with a custom one and making new auth providers if you need backend support, etc.

Thank for response.
I'm bulding new project base on Backstage. And I have old project backend for store all user. 
I want to pick user in this project and add to my backstage app. Each use must login before. When user login success, I register and manage it on backstage.
I read your docs, all provider is base on platform/software ( git, microsoft). But in my project, i must connect to  existing database, login with old api ( by email and password ).
Sr about my english. Thank you.

**Comment by freben** [comment]
Do not add users to the catalog on sign-in; that's a distinct anti-pattern. Write an entity provider that ingests all users and groups and keeps them synced into the catalog, no matter if users sign in or not. I recommend that you expose those users and groups with an API that the catalog can consume, that does not require user sign-in.

**Comment by camilaibs** [comment]
@quan1997ap here a good post about entity providers 🙂 : https://backstage.io/blog/2023/01/31/incremental-entity-provider/#entity-providers

**Comment by durandom** [comment]
> Do not add users to the catalog on sign-in; that's a distinct anti-pattern. Write an entity provider that ingests all users and groups and keeps them synced into the catalog, no matter if users sign in or not. I recommend that you expose those users and groups with an API that the catalog can consume, that does not require user sign-in.

Hey @freben would you also recommend that for very large enterprises, where potentially 20.000+ users could log into backstage? Sorry to hijack this this issue.

**Comment by benjdlambert** [comment]
@durandom, yep, you should be able to ingest users into the catalog, would recommend this for any size organization and writing your own provider if these users are stored in a place where we don't already have integrations for.

Just as an aside, there's also [this documentation](https://backstage.io/docs/auth/identity-resolver/#sign-in-without-users-in-the-catalog) about not having to have the users in the catalog if you didn't want to include them in the catalog at all for sign-in, but I guess that you might not want to go down this route.

**Comment by quan1997ap** [comment]
I found solution in your docs. Thank you so much.
