### ISSUE TITLE
🐛 Bug Report: Auth redirect flow immediately requests the /refresh endpoint, and will not allow login if a refresh token is not returned from OAuth2 provider. 

### ISSUE THREAD

**Issue by mcintoac-aws** [backstage/backstage#25383]
### 📜 Description

With the `enableExperimentalRedirectFlow` option which was first introduced in this [PR](https://github.com/backstage/backstage/pull/15841), after login, a request is immediately made to the `/refresh` endpoint. This requires the existence of the `oauth2-refresh-token` session cookie, which is set from the `result.session` object. If a refresh token is therefore not included in the response from the provider, this cookie is not set, and the requests throws an error which prevents login.

### 👍 Expected behavior

On login, a request is not made to the `/refresh` endpoint, and therefore a refresh token is not required to allow initial login. Whether your identity provider doesn't support refresh flow, or doesn't have it enabled, login should still be allowed within the expiration of the original access token.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/121058213/28273222-6402-4e56-9e4f-122d6dbe91f7)
Note that the request headers do not include the proper cookie.

### 👟 Reproduction steps

Set the `enableExperimentalRedirectFlow: true` option in your config file, then attempt to login to an identity provider which does not return a refresh token in it's /token response.

### 📃 Provide the context for the Bug.

This was first introduced in this [PR](https://github.com/backstage/backstage/pull/15841).

A comment chain on the CR between the implementer and @Rugvip seems to be somewhat related, notably:
> "The only downside of that is that if the user doesn't go through with the sign-in then it'll cause a request to the /refresh endpoint for that provider on subsequent loads, but I think that's fine."
Seems like it could have something to do with the way the provider ID is handled being set in local storage.

### 🖥️ Your Environment

**Browser:** Google Chrome

```
yarn backstage-cli info
yarn run v1.22.21
$ /Users/mcintoac/Documents/repos/code-browser/Connected-mobility-solution-on-aws/source/modules/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 23.5.0 - darwin/arm64
node: v18.17.1
yarn: 1.22.21
cli:  0.26.6 (installed)
backstage:  1.26.4

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.7.5
  @backstage/backend-common                                        0.21.7, 0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/backend-test-utils                                    0.3.8
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.6
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.32
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.67
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-aws                     0.3.13
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-backend                                 0.3.5
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-home-react                                     0.1.13
  @backstage/plugin-home                                           0.7.4
  @backstage/plugin-kubernetes-common                              0.7.6
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.7
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node-test-utils                     0.1.4
  @backstage/plugin-scaffolder-node                                0.4.4
  @backstage/plugin-scaffolder-react                               1.8.6
  @backstage/plugin-scaffolder                                     1.20.1
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-pg                       0.5.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 0.75s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Am I understanding it right that even if the immediate refresh wasn't there, users would have a suddenly expired session after a while, and a broken Backstage experience? Just out of curiosity, how long is that expiry? Is this an intermediate state of things or is there some path forward where you can achieve refreshable sessions?

Either way, sure, if there is a way of avoiding this safely (without breaking other assumptions), then that sounds like a useful fix.

**Comment by mcintoac-aws** [comment]
@freben 

I don't think that understanding is entirely correct. I don't believe the refresh flow is broken, so without the immediate refresh, an expired session should ideally refresh correctly.

The issue I am referring to is that the initial login prompts a refresh immediately. So for a provider that does not provide a valid refresh token, the expectation is that login would be allowed, and then when the access token expires (refresh is now necessary), the refresh would fail and the user would be required to log back in. Instead, it is impossible to login at all without a refresh token, which should not be the expected behavior.

I am totally willing and able to submit a fix for this, as it is currently a bit of a blocker for us on our use case, but I am struggling to understand where this immediate refresh occurs.

**Comment by camilaibs** [comment]
Hi @mcintoac-aws the `/refresh` request is called [here](https://github.com/backstage/backstage/blob/2300a21ed69213dab59765a62bc07d840fddf61b/packages/core-app-api/src/lib/AuthSessionManager/RefreshingAuthSessionManager.ts#L140), when the `SignInPage` gets the user session it checks if the user session should be refresh.
I believe what @Rugvip was saying is that when do not have a real refresh token and we have a non-expiring access token, then the provider authenticator should use that as a refresh token, as the Github provider authenticator is doing [here](https://github.com/backstage/backstage/blob/2300a21ed69213dab59765a62bc07d840fddf61b/plugins/auth-backend-module-github-provider/src/authenticator.ts#L88-L101). If my understanding is correct, always calling the `/refresh` wouldn't be a problem because the provider authenticator is using a non-expiring Backstage token as a refresh token.

**Comment by Rugvip** [comment]
The redirect flow doesn't support providers without support for session refresh. This is because we use the session refresh to persist the session on a successful login, the frontend redirect doesn't carry any credentials itself and just rely on the cookie. We could change that of course, but it's a bit of a tricky change unless we're fine with exposing the access tokens in URL params.

Tbh I think the best solution is to "fake" session refresh but storing the access token in the session cookie, just like the GitHub provider does.

**Comment by mcintoac-aws** [comment]
@Rugvip and @camilaibs thank you for your input.

I finally got around to looking at this in more detail and running some local testing. I feel as if the suggestion above doesn't fully solve the problem, and I would like some more input on whether I am approaching this wrong.

The suggestion above would fix the need for a refresh token to be returned from the OAuth2 IdP's response, however it only does so if the access token is **unexpiring**. However, the issue I see is that even with an **expiring** access token, login should still be allowed and maintained **until the access token expires**, at which point a refresh attempt would be necessary, subsequently fail, and therefore the user would need to authenticate again.

I'm curious your thoughts on a theoretical "fix" along the same lines of how the Github refresh is "faked". The idea would be to assign the access token to `session.refreshToken` as is currently done in the GitHub workaround, *regardless of the access token expiration*. Then as part of the `refresh` call, it would be necessary to first check the expiration of the access token before manually returning the `fullProfile` and `session` in the way that the GitHub implementation currently does.

I see some difficulties here given that the expiration storage in the session does not keep track of the starting point, only the number of seconds until expiration, so there would need to be some extra state or session management to keep track of the actual expiration time, as is usually done in the `exp` claim of access tokens. Unless this is already handled by the `helper.fetchProfile(accessToken)` call and is therefore not necessary in the `refresh` manual workaround.

Let me know your thoughts and if you agree with my assessment that login should be allowed without a refresh token, and with an expiring access token, and therefore the initial suggestion of copying the GitHub provider implementation does not fully resolve the issue. Thanks.

**Comment by Rugvip** [comment]
@mcintoac-aws what user experience are you looking for in this solution? What should happen when the access token expires or is about to expire after a user has logged in?

The way we generally treat auth in Backstage is as a request for credentials that may fail, in which case the user is presented with an error. This could happen for any number of reasons, but the user should generally also be able to retry the action. I think a potential gap here is that in the case that the main Backstage session itself expires we don't really have anything specific to present to the user. We'd generally always want to tell the user to reload the page at that point, or otherwise send them back to the sign-in page, but right now they're instead just presented with an auth error.

Regarding the need to track the expiration before attempting to make a `refresh` call, you don't really need to do that. The `refresh` call will tell you whether the token is expired or not. It's basically forced to be implemented in such a way due to the fact that the refresh call also needs to return the user profile, i.e. make a call the a user info endpoint using the provided token.

**Comment by mcintoac-aws** [comment]
@Rugvip I don't have a super specific experience in mind for users, I'm mostly thinking more generally about the authentication concepts of our system. But in general I would expect some form of "Expired session" message to users, with a forced refresh and login required.

Regarding your second paragraph on current Backstage behavior, based on what you described, I'm curious what the behavior is when a refresh token expires? Unless I am mistaken, an expiring refresh token would be the same situation as an expiring access token without a refresh token available, in which case the needed behavior would already exist in Backstage. Is there currently no good way to handle an expired refresh token besides the displayed error you mentioned?

Regarding the last paragraph on the expiration check being inherently a part of the `refresh` call due to the "user info endpoint", can you clarify this based on this code [here](https://github.com/backstage/backstage/blob/2300a21ed69213dab59765a62bc07d840fddf61b/plugins/auth-backend-module-github-provider/src/authenticator.ts#L96-L127). Specifically, will the expiration check be handled as part of the `helper.refresh(input)` call, or as part of the `helper.fetchProfile(accessToken)` call? This is an important distinction since the `helper.refresh(input)` call will only happen in the instances where the refresh token is present, and otherwise it would be using the "workaround" implementation of calling `helper.fetchProfile(accessToken)`. So if I decided to implement the oauth2 workaround to allow using an _expiring_ access token as a "fake" refresh token, it would be important to ensure the expiration check is handled as part of the `helper.fetchProfile(accessToken)` call...which I would hope it would be, by utilizing the `exp` claim in the access token, but I want to confirm this with you.

Thanks for your quick response, this is very helpful and I am confident we can determine a best path forward soon which will surely result in at least some improvement.

**Comment by mcintoac-aws** [comment]
@Rugvip Friendly bump on this issue to see if you have time to respond to some of my follow-up questions above? Thank you.

**Comment by Rugvip** [comment]
@mcintoac-aws regarding refresh, yep, the user would get an error when trying to perform an action that requires auth

Regarding the expiration check it's done as a side-effect of using the token to fetch user information. That request will fail if the token is expired.

**Comment by mcintoac-aws** [comment]
Bumping this to avoid automatic closure. This is still something I'd like to fix, but just haven't had time recently. We have developed a workaround for our use case by allowing the choice between the popup flow or the experimental redirect flow, depending on use case and IdP.
