### ISSUE TITLE
🐛 Bug Report: The backstage interface does not load, it keeps trying to load all the time.

### ISSUE THREAD

**Issue by 0GiS0** [backstage/backstage#25389]
### 📜 Description

Suddenly, I am not able to have the API and the frontend running at the same time locally. The API works correctly and the logs are correct but the UI never finishes loading. Interestingly, the only times it has been available it does so through port 7007 (the API one) instead of 3000.

Any ideas?

### 👍 Expected behavior

API is running on port 7007 and UI in 3000

### 👎 Actual Behavior with Screenshots

The UI doesn't load 

![Image](https://github.com/user-attachments/assets/40b77a09-07a9-461a-9802-43adc3581226)

but the logs look ok:

`vscode ➜ /workspaces/app/backstage (main) $ yarn dev
yarn run v1.22.22
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/workspaces/app/backstage/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[1] Loading config from MergedConfigSource{FileConfigSource{path="/workspaces/app/backstage/app-config.yaml"}, EnvConfigSource{count=0}}
[1] 2024-06-25T08:41:49.139Z backstage info Found 1 new secrets in config that will be redacted 
[1] 2024-06-25T08:41:49.145Z rootHttpRouter info Listening on :7007 
[1] 2024-06-25T08:41:49.146Z backstage info Plugin initialization started: 'app', 'proxy', 'scaffolder', 'techdocs', 'auth', 'catalog', 'permission', 'search' type=initialization
[1] 2024-06-25T08:41:49.247Z scaffolder info Starting scaffolder with the following actions enabled github:actions:dispatch, github:autolinks:create, github:deployKey:create, github:environment:create, github:issues:label, github:repo:create, github:repo:push, github:webhook, publish:github, publish:github:pull-request, fetch:plain, fetch:plain:file, fetch:template, debug:log, debug:wait, catalog:register, catalog:fetch, catalog:write, fs:delete, fs:rename 
[1] 2024-06-25T08:41:49.274Z techdocs info Creating Local publisher for TechDocs 
[1] 2024-06-25T08:41:49.297Z auth info Configuring "database" as KeyStore provider 
[1] 2024-06-25T08:41:49.308Z catalog info Performing database migration 
[1] 2024-06-25T08:41:49.312Z auth info Configuring auth provider: guest 
[1] 2024-06-25T08:41:49.433Z permission warn Permission backend started with permissions disabled. Enable permissions by setting permission.enabled=true. 
[1] 2024-06-25T08:41:49.442Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog 
[1] 2024-06-25T08:41:49.442Z search info Added DefaultTechDocsCollatorFactory collator factory for type techdocs 
[1] 2024-06-25T08:41:49.498Z search info Starting all scheduled search tasks. 
[1] 2024-06-25T08:41:49.499Z backstage info Plugin initialization complete, newly initialized: 'app', 'proxy', 'techdocs', 'scaffolder', 'auth', 'permission', 'catalog', 'search' type=initialization
[1] 2024-06-25T08:41:49.512Z search info Task worker starting: search_index_software_catalog, {"version":2,"cadence":"PT10M","initialDelayDuration":"PT3S","timeoutAfterDuration":"PT15M"} task=search_index_software_catalog
[1] 2024-06-25T08:41:49.513Z search info Task worker starting: search_index_techdocs, {"version":2,"cadence":"PT10M","initialDelayDuration":"PT3S","timeoutAfterDuration":"PT15M"} task=search_index_techdocs
[0] webpack compiled successfully`

### 👟 Reproduction steps

1. `yarn install`
2. `yarn dev`

### 🖥️ Your Environment

```
vscode ➜ /workspaces/app/backstage (main) $ yarn backstage-cli info
yarn run v1.22.22
$ /workspaces/app/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 6.6.31-linuxkit - linux/arm64
node: v18.20.3
yarn: 1.22.22
cli:  0.26.9 (installed)
backstage:  1.28.2

Dependencies:
  @backstage/app-defaults                                          1.5.6
  @backstage/backend-app-api                                       0.7.8
  @backstage/backend-common                                        0.23.1
  @backstage/backend-defaults                                      0.3.2
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.13
  @backstage/backend-plugin-api                                    0.6.20
  @backstage/backend-tasks                                         0.5.25
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.6
  @backstage/cli                                                   0.26.9
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.6
  @backstage/core-compat-api                                       0.2.6
  @backstage/core-components                                       0.14.8
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.6
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.28
  @backstage/integration                                           1.12.0
  @backstage/plugin-api-docs                                       0.11.6
  @backstage/plugin-app-backend                                    0.3.69
  @backstage/plugin-app-node                                       0.1.20
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.1
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.12
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.3
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.3
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.15
  @backstage/plugin-auth-backend-module-github-provider            0.1.17
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.17
  @backstage/plugin-auth-backend-module-google-provider            0.1.17
  @backstage/plugin-auth-backend-module-guest-provider             0.1.6
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.15
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.1
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.13
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.13
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.1
  @backstage/plugin-auth-backend                                   0.22.7
  @backstage/plugin-auth-node                                      0.4.15
  @backstage/plugin-auth-react                                     0.1.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.18
  @backstage/plugin-catalog-backend                                1.23.1
  @backstage/plugin-catalog-common                                 1.0.24
  @backstage/plugin-catalog-graph                                  0.4.6
  @backstage/plugin-catalog-import                                 0.12.0
  @backstage/plugin-catalog-node                                   1.12.2
  @backstage/plugin-catalog-react                                  1.12.1
  @backstage/plugin-catalog                                        1.21.0
  @backstage/plugin-events-node                                    0.3.6
  @backstage/plugin-github-actions                                 0.6.16
  @backstage/plugin-org                                            0.6.26
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.17
  @backstage/plugin-permission-backend                             0.5.44
  @backstage/plugin-permission-common                              0.7.14
  @backstage/plugin-permission-node                                0.7.31
  @backstage/plugin-permission-react                               0.4.23
  @backstage/plugin-proxy-backend                                  0.5.1
  @backstage/plugin-scaffolder-backend-module-azure                0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.10
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.12
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.10
  @backstage/plugin-scaffolder-backend-module-github               0.3.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.2
  @backstage/plugin-scaffolder-backend                             1.22.10
  @backstage/plugin-scaffolder-common                              1.5.3
  @backstage/plugin-scaffolder-node                                0.4.6
  @backstage/plugin-scaffolder-react                               1.9.0
  @backstage/plugin-scaffolder                                     1.21.0
  @backstage/plugin-search-backend-module-catalog                  0.1.26
  @backstage/plugin-search-backend-module-techdocs                 0.1.25
  @backstage/plugin-search-backend-node                            1.2.25
  @backstage/plugin-search-backend                                 1.5.12
  @backstage/plugin-search-common                                  1.2.12
  @backstage/plugin-search-react                                   1.7.12
  @backstage/plugin-search                                         1.4.12
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-tech-radar                                     0.7.4
  @backstage/plugin-techdocs-backend                               1.10.7
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.11
  @backstage/plugin-techdocs-node                                  1.12.6
  @backstage/plugin-techdocs-react                                 1.2.5
  @backstage/plugin-techdocs                                       1.10.6
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.7
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.6
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
Done in 0.42s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
If you stop backstage entirely and try and hit `http://localhost:3000` does it do the same thing?

**Comment by 0GiS0** [comment]
Hi @benjdlambert! thanks for your answer

No, I don't have any other process in that port. If I stop it I get localhost refused to connect.

![Image](https://github.com/user-attachments/assets/b426a1c7-8a0e-4c10-a347-fb91fdeefe08)

I create a new instance and same behaviour

**Comment by benjdlambert** [comment]
Hmm - does it happen in all browsers? is there any information in the console? What happens if you `curl http://localhost:3000` once the bundle is complete?

**Comment by 0GiS0** [comment]
> Hmm - does it happen in all browsers? is there any information in the console? What happens if you `curl http://localhost:3000` once the bundle is complete?

Wow, I realized the problem is because I am using a Dev Container. It worked until now but something changed. If I `curl http://localhost:3000` insider the dev container it works, If I try to access from my local machine I can only access to the API but I can't to the UI.... super weird

**Comment by 0GiS0** [comment]
Fixed with [this](https://github.com/backstage/backstage/issues/24888#issuecomment-2137060437)
