### ISSUE TITLE
🚀 Feature: Initial Filter for Lifecycle in DefaultApiExplorerPage

### ISSUE THREAD

**Issue by HongQiGong** [backstage/backstage#25381]
### 🔖 Feature description

An initial filter for the lifecycle of APIs in DefaultApiExplorerPage

### 🎤 Context

Can we add an initial filter for the lifecycle of APIs that are shown by default in DefaultApiExplorerPage? When a user navigates to the API explorer page, it would be great to be able to configure the page to initially display the APIs in a specific lifecycle, especially the production lifecycle. The list of APIs can get kind of noisy if people are adding APIs that are in all lifecycles. It would be useful to first see the ones in the production lifecycle.

### ✌️ Possible Implementation

We could add a parameter in DefaultApiExplorerPage at this line: https://github.com/backstage/backstage/blob/c9a2e9663466c6db7d2ed9b036080e6205746268/plugins/api-docs/src/components/ApiExplorerPage/DefaultApiExplorerPage.tsx#L112

The EntityLifecyclePicker should already support an `initialFilter`: https://github.com/backstage/backstage/blob/c9a2e9663466c6db7d2ed9b036080e6205746268/plugins/catalog-react/src/components/EntityLifecyclePicker/EntityLifecyclePicker.tsx#L35

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
It makes sense, feel free to share the pull request when you're ready to contribute 🙂

**Comment by HongQiGong** [comment]
@camilaibs I probably won't have time in the next few months. But let me circle back to this later if no one else has made a PR.
