### ISSUE TITLE
Aggregation in Ownershipcard(Userpage) keeps loading if limiterFactory exceeds 10

### ISSUE THREAD

**Issue by Oviyasundari** [backstage/backstage#25396]
### 📜 Description

When trying aggregate relations in Group page using toggle, it keeps loading and doesn't return error/response. This caused by using **limiterFactory** in **p-limit**.  Here I needed to increase the concurrency value from 10 to more, say 20.

https://github.com/backstage/backstage/blob/02f9d469d0075b182cdf79dd51fb525993369d0e/plugins/org/src/components/Cards/OwnershipCard/useGetEntities.ts#L35

### 👍 Expected behavior

It should response will counter values properly

### 👎 Actual Behavior with Screenshots

<img width="642" alt="image" src="https://github.com/backstage/backstage/assets/30496471/117c07a0-36e1-4d9f-82e5-4c2858367806">

### 👟 Reproduction steps

1. Select to kind --> Group, type --> high level of aggregation
2. Takes to Group page 
3. Right side there will be ownership card
4. when aggregation goes beyond concurrency of 10 it keeps loading forever

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by SandipGyawali** [comment]
@Oviyasundari can i see it ?

**Comment by Oviyasundari** [comment]
I can attach for reference, this happens for huge data aggregation, if data is less then this works fine!

Uploading Screen Recording 2024-06-26 at 11.05.33 AM.mov…

**Comment by camilaibs** [comment]
Hi @Oviyasundari, could you please share what Backstage version are you on?
