### ISSUE TITLE
🚀 Feature: Add required token claims for the JWT (JWKS)

### ISSUE THREAD

**Issue by gregod-com** [backstage/backstage#25409]
### 🔖 Feature description

Add required token claims for the JWT (JWKS) auth method with external tokens.

### 🎤 Context

I am trying to allow authentication from Gitlab CI pipelines to the backstage API. Instead of injecting static tokens into the CI pipeline, I'd rather use the JWT method that is provided by Gitlab and tell backstage to allow certain JWTs to authenticate. This works fine, but currently can only be limited to 
* issuer
* aud
It would be nice, if I could limit by other arbitrary claims, so that I can tell backstage:
Allow JWT tokens that are signed by XYZ and have the claim: project_id = 123

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
So you are referring to [this config section](https://github.com/backstage/backstage/blob/732583700dd0809dae4614792bd67177d7c9246e/packages/backend-defaults/config.d.ts#L263) right? And the suggestion might be to add something like

```yaml
claims: { [key: string]: string | number };
```

or something like that?

Sure, that sounds reasonable. There's a bit of an overlap with the existing checks but there'll be effectively an AND between them all so it's at least not a security risk.

**Comment by gregod-com** [comment]
hey @freben 
yes exactly. Adding additional requirements and checks as you suggested would meet my requirement 100%.
Thanks for adding information
