### ISSUE TITLE
🚀 Feature: Allow repositories to be excluded from discovery

### ISSUE THREAD

**Issue by Xiol** [backstage/backstage#25405]
### 🔖 Feature description

Currently the discovery integrations (at least, the ones I'm using - Azure and Gitlab) have options to set what repositories should be included, e.g. `projectPattern` for the [Gitlab discovery plugin](https://backstage.io/docs/integrations/gitlab/discovery), however there is no option to exclude a repository from discovery.

I would like a way to provide a list of repositories to the discovery plugins which should not be included during discovery. For example, a new configuration option like `excludeRepositories` which takes a list of project paths:

```yaml
  providers:
    gitlab:
      our_org_gitlab:
        host: gitlab.myorg.co.uk
        branch: main
        fallbackBranch: master
        excludeRepositories:
          - foo/bar
          - foo/qux
          - group/subgroup/repo
```

A similar option for the Azure DevOps plugin could just take a list of repository names.

Repositories marked for exclusion would then not be discovered.

For me, this specifically relates to the Gitlab discovery plugin, but I think it would be useful on the others as well.

### 🎤 Context

The obvious solution here is to simply not add a `catalog-info.yaml` file to the repository to exclude it from discovery, right?

However, we currently have the situation where some of our repositories are hosted in Azure DevOps, and the code is then synced to our Gitlab instance where our CI/CD pipelines execute. We have a large number of repositories configured like this, but we also have an even larger number of projects that only exist within the Gitlab instance.

We would like to run discovery on both Azure DevOps and Gitlab, however the synced projects will be discovered twice, in two locations.

Ideally we would be able to exclude the synced repositories from discovery in one of the providers, so that we can avoid them being detected twice.

Using the include functionality (i.e. `projectPattern`) won't work for us since the project names and paths are many and varied, and it would require a large, complex, negative-lookahead regex to even start to make this work.

### ✌️ Possible Implementation

N/A

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hi @Xiol, this makes sense 🙂. Would you like to contribute with us?

**Comment by Xiol** [comment]
Unfortunately I have zero TypeScript and only minimal Javascript skills, so I'm not sure I'm in a position to contribute.

(This does raise a question as to why I'm the one setting this up, but I do like a challenge.)

**Comment by Xiol** [comment]
I overcome my reluctance and got stuck in. PR https://github.com/backstage/backstage/pull/25796 opened for the Gitlab provider.
