### ISSUE TITLE
🐛 Bug Report: EntityRefLink component usage inconsistency

### ISSUE THREAD

**Issue by Vity01** [backstage/backstage#25459]
### 📜 Description

if you use EntityRefLink component like this:
```
<EntityRefLink defaultKind="user" entityRef="some.username" />
``` 

It crashes with `had missing or empty kind (e.g. did not start with "component:" or similar)`. Note the `defaultKind` attribute is set.
The reason is `EntityRefLink` is using `const entityRoute = useEntityRoute(props.entityRef);` but `useEntityRoute` does not provide/pass `defaultKind` parameter into its `parseEntityRef` usage.

Note, same problem is with the `EntityDisplayName` component if I use it directly.

### 👍 Expected behavior

Should not throw exception or to start force using entityReference as full reference without defaultKind support.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/2512959/c4a411df-d1c5-49ef-b5b7-889c8032db46)

### 👟 Reproduction steps

Use this component: `<EntityRefLink defaultKind="user" entityRef="some.username" />`

### 📃 Provide the context for the Bug.

As a workaround, it can be used like that:
`<EntityRefLink defaultKind="group" entityRef={parseEntityRef(item.owner, {defaultKind: "group"})} />;`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by camilaibs** [comment]
Thanks for opening the issue, adding a help wanted label 🙏🏻 .
