### ISSUE TITLE
🚀 Feature: Export `defaultEksClusterEntityTransformer` from `catalog-backend-module-aws`

### ISSUE THREAD

**Issue by lorrrrrrrenzo** [backstage/backstage#25450]
### 🔖 Feature description

🚀 Feature: Export `defaultEksClusterEntityTransformer` from `catalog-backend-module-aws`

### 🎤 Context

When implementing a custom `clusterEntityTransformer`, I would prefer to be able to refer to `defaultEksClusterEntityTransformer` as defined in the `catalog-backend-module-aws` library and modify _its_ result -- which is mostly what I need but not quite -- instead of copying the current state of the function and making sure it stays up to date with library updates. The function already exists and just needs to be exported.

### ✌️ Possible Implementation

In the below `addMetadataTags` is an example of a small modification to the result of the default transformer. I can see this being helpful to many people

```typescript
// Import necessary types
import { 
  AwsEKSClusterProcessor, 
  EksClusterEntityTransformer, 
  DefaultEksClusterEntityTransformer, // this would be enabled by the change
} from '@backstage/plugin-catalog-backend-module-aws';


// Define the higher-order function with type annotations
const composeTransformers = (
  baseTransformer: EksClusterEntityTransformer,
  modifier: (entity: Awaited<ReturnType<EksClusterEntityTransformer>>) => Awaited<ReturnType<EksClusterEntityTransformer>>
): EksClusterEntityTransformer => {
  return async (cluster, accountId) => {
    const baseEntity = await baseTransformer(cluster, accountId);
    return modifier(baseEntity);
  };
};

// Define a modifier function to add metadata tags
const addMetadataTags = async (entity: Awaited<ReturnType<EksClusterEntityTransformer>>) => {
  return {
    ...entity,
    metadata: {
      ...entity.metadata,
      tags: ['eks', 'aws', 'kubernetes'],
    },
  };
};

// Compose the transformers
export const extendedEksClusterEntityTransformer: EksClusterEntityTransformer = composeTransformers(
  defaultEksClusterEntityTransformer,
  addMetadataTags
);
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hello @lorrrrrrenzo 👋🏻 , thank you for raising this issue, it sounds reasonable.
Our recommendations are as follows:
A) The default transformer could be exported from its package so that it can be imported and reused;
B) Provide the default transformer as a second parameter to the entity transformer callback.
We would be happy to provide feedback in a pull request if you would like to contribute. 🙂
