### ISSUE TITLE
🐛 Bug Report: fetch:plain Scaffolder action always use GitLab integration token

### ISSUE THREAD

**Issue by elaine-mattos** [backstage/backstage#25455]
### 📜 Description

Hi all!

I'm sorry if this is a duplicate issue, I couldn't find anything similar.

We recently developed a template using the fetch:plain action to retrieve repositories from GitLab. The action supports inputting a token, and given GitLab serves as our authentication provider, we intended to utilize the user's OAuth token for executing requests. However, we found an issue where requests consistently used the integration's personal access token instead of the user's OAuth token.

This issue prevents our users from running the template against their private repositories. As the technical user that holds the integration token is not a part of these private repos, the users get a 401 error. 
As we don't want to ask private repo owners to add the technical user to their private repositories we decided to change the code slightly. 

The modifications can be seen in [this PR](https://github.com/backstage/backstage/pull/25454). We appreciate your feedback! 

### 👍 Expected behavior

If the user provides a token, the `fetch:plain` action should be able to use it to perform requests. If no token is provided, then the integration token should be used.

### 👎 Actual Behavior with Screenshots

When users run templates with the `fetch:plain` action against their private repositories they get a 401 error.

### 👟 Reproduction steps

1. create a private GitLab repository;
2. create a template with the `fetch:action`action
3. add the private repo's url as input and run the template. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by veenarm** [comment]
I had experiences this as well when creating projects etc was always using Scaffolder instead of the users token.
