### ISSUE TITLE
🐛 Bug Report: Kuberenetes(AWS) Plugin in Backstag

### ISSUE THREAD

**Issue by sanathlokanath1991** [backstage/backstage#25453]
### 📜 Description

I am facing issue while adding k8's plugin in backkstage, After all roller coaster i am facing this blank page with the message 

Your Clusters
No Kubernetes resources
No resources on any known clusters for eks-demo

Kindly assist what could be the issue 

### 👍 Expected behavior

I should be populated the cluster details on backstage

[1] 2024-06-27T18:34:44.758Z kubernetes info action=loadClusterDetails numOfClustersLoaded=1 
[1] 2024-06-27T18:34:44.758Z rootHttpRouter info ::ffff:49.37.163.68 - - [27/Jun/2024:18:34:44 +0000] "GET /api/kubernetes/clusters HTTP/1.1" 304 - "http://3.215.208.215:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" type=incomingRequest
[1] 2024-06-27T18:34:45.331Z kubernetes info entity.metadata.name=my-app clusterDetails=[Backatage-Cluster]

### 👎 Actual Behavior with Screenshots

![Eks](https://github.com/backstage/backstage/assets/165782612/273ef944-99bf-45c2-9ad4-1c80b50d5325)

### 👟 Reproduction steps

My Current app-config.yaml 

kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://XXXXXXXXXXXXX6CEEDD32.gr7.us-east-1.eks.amazonaws.com
          name: Backatage-Cluster # You can use any name you want
          authProvider: aws  
          serviceAccountToken: /var/run/secrets/kubernetes.io/serviceaccount/token
          caData: $caData

aws:
  accounts:
    - accountId: $accountid
      accessKeyId: $accesskeys
      secretAccessKey: $secretkeys
      roleName: $role
      
  Catlog-info.yaml

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-app
  description: something
  annotations:
    backstage.io/kubernetes-id: my-app
    backstage.io/kubernetes-namespace: idp
spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest

  
  

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hi @backstage/kubernetes-maintainers did you spot any configuration errors at first glance?

**Comment by mclarke47** [comment]
Hey can you confirm you have labels the kubernetes resource correctly? Here's an [example](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/examples/dice-roller/dice-roller-manifests.yaml#L6) and the relevant [docs](https://backstage.io/docs/features/kubernetes/configuration#surfacing-your-kubernetes-components-as-part-of-an-entity).
