### ISSUE TITLE
🐛 Bug Report: Gitlab Scaffolding Action PipelineTrigger can't trigger with variables

### ISSUE THREAD

**Issue by veenarm** [backstage/backstage#25461]
### 📜 Description

You can't pass variables to a pipeline/trigger as per:

 https://docs.gitlab.com/ee/api/pipeline_triggers.html#trigger-a-pipeline-with-a-token

### 👍 Expected behavior

Allow you to create step actions that can trigger a pipeline with specific variables

### 👎 Actual Behavior with Screenshots

There is no option/mechanism to pass variables into the trigger.

### 👟 Reproduction steps

1. Setup backstage with a Gitlab account
2. Import/Load https://gitlab.com/backstage5212121/scaffolding-templates/-/blob/main/gitlab-pipeline-trigger/template.yaml
3. Run the scaffolder job and see that no variables occur in the pipeline outputs.

### 📃 Provide the context for the Bug.

Not sure if it's a bug or feature.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by veenarm** [comment]
I've already got a fix for this and tested it, Just need to spend some time doing all the necessary paperwork involved and submit the PR.

**Comment by veenarm** [comment]
PR #25466

**Comment by camilaibs** [comment]
It looks like pull request #25480 has been merged 🎉 , can this issue be closed now @veenarm ?
