### ISSUE TITLE
Hi Team Need any reference or documentation related to login to okta directly without backstage login page

### ISSUE THREAD

**Issue by vinaykv23** [backstage/backstage#25468]
### 🔖 Need

Hi Team
we have integrated okta authentication to backsage, but its going through backstage login page
Need any reference or documentation related to login to okta directly without backstage login page

### 🎉 Proposal

Hi Team
we have integrated okta authentication to backsage, but its going through backstage login page
Need any reference or documentation related to login to okta directly without backstage login page

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by freben** [comment]
You probably want to use a proxy provider then, which has no visible sign in page at all (because a reverse authenticating proxy already handled that). Like with the oauth2proxy provider.

https://backstage.io/docs/auth/oauth2-proxy/provider/

What's your actual proxy product? Is it okta itself or something else?

**Comment by vinaykv23** [comment]
Hi Freben
okta is the proxy provider

**Comment by camilaibs** [comment]
> Hi Freben okta is the proxy provider, our requirement once we open backstage url for authentication it should directly go to okta login page. Login page required here is okta login page

Thanks! Did you follow the [oauth2-proxy documentation](https://backstage.io/docs/auth/oauth2-proxy/provider/) that Freben shared? Asking to see if this solves the issue for you.

**Comment by vinaykv23** [comment]
> > Hi Freben okta is the proxy provider, our requirement once we open backstage url for authentication it should directly go to okta login page. Login page required here is okta login page
> 
> Thanks! Did you follow the [oauth2-proxy documentation](https://backstage.io/docs/auth/oauth2-proxy/provider/) that Freben shared? Asking to see if this solves the issue for you.

Hi I followed the [oauth2-proxy documentation](https://backstage.io/docs/auth/oauth2-proxy/provider/), it resulted in errors there it is not clear how to configure for okta

I am getting below error after making the changes in document

![image](https://github.com/backstage/backstage/assets/47448366/3250c394-c61b-47dc-b160-df1683c88443)
