### ISSUE TITLE
🐛 Bug Report: Custom Entity Providers documentation incomplete

### ISSUE THREAD

**Issue by sebalaini** [backstage/backstage#25463]
### 📜 Description

Referencing my issue #25404, from my work account, the [Custom Entity Providers](https://backstage.io/docs/features/software-catalog/external-integrations/#custom-entity-providers) doc is incomplete and needs to specify properly what you should do in the new Backend.

After following the guide and creating the `FrobsProvider` class in the old Backend you [install the provider](https://backstage.io/docs/features/software-catalog/external-integrations/#installing-the-provider) like so 
```
  const frobs = new FrobsProvider('production', env.reader);
  builder.addEntityProvider(frobs);

  const { processingEngine, router } = await builder.build();
  await processingEngine.start();

  await env.scheduler.scheduleTask({
    id: 'run_frobs_refresh',
    fn: async () => {
      await frobs.run();
    },
    frequency: { minutes: 30 },
    timeout: { minutes: 10 },
  });
```

while in the [new Backend](https://backstage.io/docs/features/software-catalog/external-integrations/#new-backend-system) it say to do it like so:
```
export const catalogModuleFrobsProvider = createBackendModule({
  pluginId: 'catalog',
  moduleId: 'frobs-provider',
  register(env) {
    env.registerInit({
      deps: {
        catalog: catalogProcessingExtensionPoint,
        reader: coreServices.urlReader,
      },
      async init({ catalog, reader }) {
        catalog.addEntityProvider(new FrobsProvider('dev', reader));
      },
    });
  },
});
```

As you can see, the whole scheduler is missing but especially this bit of code inside the scheduler is missing `await frobs.run();` in the new Backend and there is no mention of how to add it

### 👍 Expected behavior

The new Backend documentation should mention how to trigger the `run` function after installation, and to be completed, it would be nice to add also how you can add a scheduler.

### 👎 Actual Behavior with Screenshots

After following the documentation you end up with the new entity provider not working and without knowing the real reason why only the logger inside this function is triggered.

```
  async connect(connection: EntityProviderConnection): Promise<void> {
    this.logger.info('Establishing connection.');
    this.connection = connection;
  }
```

### 👟 Reproduction steps

- migrate the catalog to the new Backend
- add a new entity provider following the documentation above

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by aramissennyeydd** [comment]
👋 Would you be willing to submit a PR to fix this? 🙏

**Comment by sebalaini** [comment]
Hey @aramissennyeydd I'm not sure my solution is correct, I mean I understood that `async connect` is the only thing being called once the module is installed but is that the correct way to add all the logic plus the scheduler, or is there a different and better way of doing it?

**Comment by sebalaini** [comment]
I don't know if you saw my last comment in the other issue, this is my current `async connect`

```
  async connect(connection: EntityProviderConnection): Promise<void> {
    this.logger.info('Establishing connection with OKTA.');
    this.connection = connection;
    // load user on the 1st connection
    await this.run();

    // create scheduler task
    await this.scheduler.scheduleTask({
      id: 'refresh_users',
      fn: async () => {
        await this.run();
      },
      frequency: { cron: '0 0 * * *' },
      timeout: { minutes: 2 },
      initialDelay: { seconds: 3 },
    });
  }
```

**Comment by aramissennyeydd** [comment]
Looks like you would just need to update the snippet to something like,
```
export const catalogModuleFrobsProvider = createBackendModule({
  pluginId: 'catalog',
  moduleId: 'frobs-provider',
  register(env) {
    env.registerInit({
      deps: {
        catalog: catalogProcessingExtensionPoint,
        reader: coreServices.urlReader,
        scheduler: coreServices.scheduler,
      },
      async init({ catalog, reader, scheduler }) {
        const frobs = new FrobsProvider('dev', reader);
        catalog.addEntityProvider(frobs);
        await scheduler.scheduleTask({
          id: 'run_frobs_refresh',
          fn: async () => {
            await frobs.run();
          },
          frequency: { minutes: 30 },
          timeout: { minutes: 10 },
        });
      },
    });
  },
});
```

Adding in the scheduler core service and setting its fn. I'd recommend the above for any custom catalog providers instead of doing it in connect as you have more clear control in the above example. I'll open a PR to adjust the documentation here :)

**Comment by sebalaini** [comment]
waiting for your PR to be merged and then I'll update my code accordingly :) TY for the PR

**Comment by LegendSebastianoL** [comment]
hey @aramissennyeydd @freben today I externalised the user provider in a BE module and `yarn tsc` don't pass anymore.

if I follow the documentation at some point it says to use this command `yarn new --select backend-module --option id=catalog` to create a proper module, it creates everything and adds the module to the backend package.json which works perfectly but then once I commit the pipeline fail on the `tsc` part `Cannot find module '@internal/backstage-plugin-catalog-backend-module-okta-user-provider' or its corresponding type declarations.`
