### ISSUE TITLE
🚀 Feature: Plugin sandbox / isolation to ensure configuration does not break backend startup

### ISSUE THREAD

**Issue by CiscoRob** [backstage/backstage#25493]
### 🔖 Feature description

A common problem our organization runs into is installing a new plugin from the community. The plugin is installed pretty easily but if any of the configuration is missing or invalid the plugin will throw errors that will often result in an unhandled exception that blocks the packages/backend from starting.

We even see this in the identity guest module that does not support environment specific settings as most other auth identity plugins do. In the backend index.ts where we'd otherwise just import a module we have to first get the environment just to not import the guest module when targeting a production deployment to avoid it breaking deployments.

I understand that every part of the system is a plugin but when a non-critical nice-to-have plugin breaks, like kubernetes plugin or even Github provider, it often will lead to a failure in deployment. That leads to more delays and time spent trying to get the logs and understand how to resolve / what configuration is causing the problems. Add in all the migration to the "Next" framework it becomes very hard to tell if it's bad config, bug in migration, bug in our use of a plugin, or whatever else.

It would be nice to have a way to register "optional" plugins that if they break... so be it. Sandboxed to some extent so that the only places it might break otherwise would be in the routing if not done based on default router or the entity details page router...

### 🎤 Context

Having the ability to differentiate between "don't deploy we have to have this working" plugins and optional "this is nice to have - but not as critical as seeing / accessing the service catalog itself" plugins.

Providing a way to sandbox a plugin from registration so that its failures do not become a complete running system failure. Especially around configuration loading would be a value add.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by aramissennyeydd** [comment]
@CiscoRob I think the recommended approach here would be https://backstage.io/docs/backend-system/building-backends/index/#split-into-multiple-backends to split your existing Backstage deployment into "business critical" and "nice to have, but less critical" split deployments.

**Comment by Rugvip** [comment]
+1 to @aramissennyeydd suggestion, but I'll also say that this is on our radar and we're likely to explore ways to simplify configuration management quite soon as part of https://backstage.io/docs/overview/roadmap#configuration-improvements

**Comment by CiscoRob** [comment]
@aramissennyeydd thank you for the suggestion! Split deployments does sound like a simple solution... I like simple solutions. :) 

Validation checks using the backstage-cli weren't catching everything so we're building up docker-compose to setup a production environment to spin up and tear down for smoke tests.

@Rugvip awesome sauce. Thank you. :)
