### ISSUE TITLE
🐛 Bug Report: TechDocs does not work for custom catalog processor

### ISSUE THREAD

**Issue by jrkt** [backstage/backstage#25502]
### 📜 Description

In implementing a custom catalog processor on the new backend installation, everything is working as expected except for Techdocs. The error being returned from the techdocs plugin is: 

```
techdocs info Unable to get metadata for 'component:default/actions' with error InputError: Unable to resolve location type switchboard-catalog-processor
```

Our entire backend `index.ts` file contents:

```typescript
import {createBackend} from '@backstage/backend-defaults';
import {customAuthPlugin} from "./plugins/auth";
import {catalogModuleSwitchboardCatalogProcessor} from "./plugins/catalog";

const backend = createBackend();
backend.add(import('@backstage/plugin-app-backend/alpha'));
backend.add(import('@backstage/plugin-catalog-backend/alpha'));
backend.add(catalogModuleSwitchboardCatalogProcessor);
backend.add(
  import('@backstage/plugin-catalog-backend-module-scaffolder-entity-model'),
);
backend.add(customAuthPlugin);

backend.add(import('@backstage/plugin-proxy-backend/alpha'));
backend.add(import('@backstage/plugin-auth-backend'));
backend.add(import('@backstage/plugin-search-backend/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-catalog/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-techdocs/alpha'));
backend.add(import('@backstage/plugin-techdocs-backend/alpha'));
backend.start();
```

The `catalog` section of our `app-config.yaml`:

```yaml
catalog:
  readonly: true
  locations:
    - type: switchboard-catalog-processor
      target: ${CATALOG_PROCESSOR_HOST}/catalog
```

We also upgraded our entire backstage installation to the very latest. 

### 👍 Expected behavior

I expected the most recent version of the backend Techdocs plugin to respect the custom catalog processor just like every other plugin is doing.

### 👎 Actual Behavior with Screenshots

Techdocs fails to load.

![Screenshot from 2024-07-02 09-42-31](https://github.com/backstage/backstage/assets/6549363/644ed237-a32f-44ed-b2b7-8f0c2d8cb4e1)

### 👟 Reproduction steps

1. Upgrade to latest backstage installation
2. Implement custom catalog processor
3. Use Techdocs

### 🖥️ Your Environment

OS:   Linux 6.5.0-35-generic - linux/x64
node: v18.15.0
yarn: 1.22.21
cli:  0.26.10 (installed)
backstage:  1.28.3

Dependencies:
  @backstage/app-defaults                                          1.5.7
  @backstage/backend-app-api                                       0.7.9
  @backstage/backend-common                                        0.23.2
  @backstage/backend-defaults                                      0.3.3
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.14
  @backstage/backend-plugin-api                                    0.6.21
  @backstage/backend-tasks                                         0.5.26
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.6
  @backstage/cli                                                   0.26.10
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.13.0
  @backstage/core-compat-api                                       0.2.6
  @backstage/core-components                                       0.12.5, 0.14.8
  @backstage/core-plugin-api                                       1.9.3
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.6
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.28
  @backstage/integration                                           1.12.0
  @backstage/plugin-api-docs-module-protoc-gen-doc                 0.1.7
  @backstage/plugin-api-docs                                       0.11.6
  @backstage/plugin-app-backend                                    0.3.70
  @backstage/plugin-app-node                                       0.1.21
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.2
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.13
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.4
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.4
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.16
  @backstage/plugin-auth-backend-module-github-provider            0.1.18
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.18
  @backstage/plugin-auth-backend-module-google-provider            0.1.18
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.16
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.2
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.14
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.2
  @backstage/plugin-auth-backend-module-okta-provider              0.0.14
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.2
  @backstage/plugin-auth-backend                                   0.22.8
  @backstage/plugin-auth-node                                      0.4.16
  @backstage/plugin-auth-react                                     0.1.3
  @backstage/plugin-catalog-backend-module-github                  0.6.4
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.19
  @backstage/plugin-catalog-backend                                1.23.2
  @backstage/plugin-catalog-common                                 1.0.24
  @backstage/plugin-catalog-graph                                  0.4.6
  @backstage/plugin-catalog-import                                 0.12.0
  @backstage/plugin-catalog-node                                   1.12.3
  @backstage/plugin-catalog-react                                  1.12.1
  @backstage/plugin-catalog                                        1.21.0
  @backstage/plugin-events-node                                    0.3.7
  @backstage/plugin-github-actions                                 0.6.16
  @backstage/plugin-home-react                                     0.1.14
  @backstage/plugin-home                                           0.7.6
  @backstage/plugin-org                                            0.6.26
  @backstage/plugin-permission-common                              0.7.14
  @backstage/plugin-permission-node                                0.7.32
  @backstage/plugin-permission-react                               0.4.23
  @backstage/plugin-proxy-backend                                  0.5.2
  @backstage/plugin-scaffolder-backend-module-azure                0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.11
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.13
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.11
  @backstage/plugin-scaffolder-backend-module-github               0.3.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.3
  @backstage/plugin-scaffolder-backend                             1.22.11
  @backstage/plugin-scaffolder-common                              1.5.3
  @backstage/plugin-scaffolder-node                                0.4.7
  @backstage/plugin-scaffolder-react                               1.9.0
  @backstage/plugin-scaffolder                                     1.22.0
  @backstage/plugin-search-backend-module-catalog                  0.1.27
  @backstage/plugin-search-backend-module-pg                       0.5.31
  @backstage/plugin-search-backend-module-techdocs                 0.1.26
  @backstage/plugin-search-backend-node                            1.2.26
  @backstage/plugin-search-backend                                 1.5.13
  @backstage/plugin-search-common                                  1.2.12
  @backstage/plugin-search-react                                   1.7.12
  @backstage/plugin-search                                         1.4.12
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-tech-radar                                     0.7.4
  @backstage/plugin-techdocs-backend                               1.10.8
  @backstage/plugin-techdocs-node                                  1.12.7
  @backstage/plugin-techdocs-react                                 1.2.5
  @backstage/plugin-techdocs                                       1.10.6
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.8
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.7
  @backstage/theme                                                 0.2.19, 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by crazy-canux** [comment]
What could be the reason?  I got similar issue.
After add msgraph processor in catalog, techdoc not working.

**Comment by camilaibs** [comment]
Hi @backstage/techdocs-maintainers could you please take a look?

**Comment by PeaWarrior** [comment]
Hey, I think what @camilaibs [suggested](https://discord.com/channels/687207715902193673/1256104010469998652/1257363969484787823) in the discord thread about creating a custom preparer is the right path. Since you're using a custom location type and the default techdocs preparer, the preparer is unable to discern where your source files are and won't make any assumptions either.

**Comment by jrkt** [comment]
@PeaWarrior is there an example on how to do that? That's what I tried to do but there is no documentation on doing that and it's not very intuitive on how to do that.

**Comment by jrkt** [comment]
Also, it's worth noting all of the other plugins are operating just fine. I would expect the TechDocs plugin to also function properly with the new location type because it is defined in app-config.yaml catalog section. I have to assume that's why all the other plugins are respecting the new location type.

**Comment by camilaibs** [comment]
Hi @jrkt, in conversation with @Rugvip he explained to me that TechDocs locations aren't the same as catalog locations. So the issue here is that the TechDocs `dir:` type no longer works because it can't resolve relative to a custom catalog location type. You need to have a processor that adds a TechDocs annotation with an absolute `url:` location instead.

We think that the best solution is to make sure that https://backstage.io/docs/features/software-catalog/well-known-annotations/#backstageiosource-location is populated for the generated entities. Otherwise would have to install a custom dir preparer that knows to resolve to a custom catalog location type instead of using the default one.

**Comment by jrkt** [comment]
@camilaibs how does that annotation need to look for this to work? It looks like it's just a URL. It doesn't specify anything about the new location type.

**Comment by jrkt** [comment]
The interesting thing is that the search shows techdocs in the search results with the little summary which shows some of the actual techdocs content. But, if I click on that search result, I get the error described in this issue.

**Comment by camilaibs** [comment]
> @camilaibs how does that annotation need to look for this to work? It looks like it's just a URL. It doesn't specify anything about the new location type.

The value of the annotation should an absolute url location, 
![image](https://github.com/backstage/backstage/assets/6290749/8919458f-e999-4869-b9ca-c34ce48c4e72)

See more examples here: https://github.com/search?q=backstage.io%2Fsource-location+language%3AYAML&type=code&p=1&l=YAML

**Comment by jrkt** [comment]
@camilaibs is that going to be a problem that the URL points to a private GitHub repository? And now that I'm using a custom processor, I have completely removed the GitHub integration.

**Comment by Rugvip** [comment]
You'll want to keep that GitHub integration around just for the sake of being able to resolve URLs and potentially read content or take other actions. That URL in the `source-location` annotation should then point to the repo as usual. You'll want to set this up even if you don't read TechDocs content directly from the GitHub repo so that edit and issue links work correctly.

**Comment by jrkt** [comment]
@Rugvip if I don't use issue links, when would that GitHub integration ever be used? A normal url parser can resolve GitHub URLs just fine. I would prefer to keep the integration out of it. I don't think we actually need it.

**Comment by jrkt** [comment]
In fact, I was able to get techdocs working by simply setting the `backstage.io/source-location` annotation to the host name of our custom processor API.
