### ISSUE TITLE
🐛 Bug Report: Tech docs custom loader as places of progress bar loader

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#25504]
### 📜 Description

We are trying to customize the tech docs loader. we are unable to do so. can you please expose function/property to customize progress bar loader for tech docs.

### 👍 Expected behavior

user should have ability to customize loaders for tech docs.

### 👎 Actual Behavior with Screenshots

user don't have a way to customize loader for tech docs.

### 👟 Reproduction steps

if you want to change loader for tech docs. it does not work. if you use onReady function. you will get your customized loader top of by default loader. it will display 2 loaders.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by lalit774** [comment]
@vinzscam @freben 

Hey guys, we noticed the techdocs page loads a new index.html and css files on every navigate within the techdoc, which caused a flickering and loading issue on the page. It is a very bad user experience.

We tried to look into the backstage techdoc source code and documentation, but we cannot find any solution or potiential fixes for it.

We are blocked due to that , if we cannot find a fix for that, our executives will probably move away from backstage.

**Comment by johnphilip283** [comment]
@lalit774 We have a PR in the works to address the navigation bug you've mentioned in your comment. At the moment, we don't have a lot of requests coming in to customize the loading component - we'd be happy to accept a contribution to this component if you still want the functionality!
