### ISSUE TITLE
🚀 Feature: Fetch GitHub repository collaborators and teams access roles to use for Backstage access permissions

### ISSUE THREAD

**Issue by goodman-anne** [backstage/backstage#25525]
### 🔖 Feature description

Collaborator and team access roles that are set on organization-owned GitHub repositories should be reflected in the read, write, create, delete permissions of entities that come from those repositories when authenticated by a GitHub App in Backstage.

### 🎤 Context

We are using a GitHub App and OAuth App for authentication and discovery to view and create organization-owned repositories in Backstage. It's possible to register collaborators when creating new GitHub repositories from a scaffolding template but there's no way to access that collaborator information once the repository is registered as an entity in Backstage. We would like to use the collaborators' access roles (default Read, Triage, Write, Maintain, Admin) set on our GitHub repositories on Backstage by default rather than having to either call the GitHub API on every page read to fetch repository collaborators and match them to GitHub groups automatically imported into Backstage or manually having to add those collaborators already set on GitHub to each catalog-info using dependsOn or other spec.

GitHub repository roles docs: https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization

### ✌️ Possible Implementation

Here is an example of the implementation of this feature.

GitHub Repository Sample-Repo has the following teams set as collaborators:

Team 1 has "Maintain"
Team 2 has "Admin"
Team 3 has "Read"
Team 4 is not set as a collaborator on this repository

Since Teams 1, 2, and 3 are set as collaborators on the repository, they should all have read access to all entities (components, apis, etc) that come from Sample-Repo. Teams 1 and 2 should also have write access being Maintainers and Administrators. Since Team 4 is not set as a collaborator on this repository, entities from Sample-Repo should not be visible or accessible in the catalog.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by camilaibs** [comment]
Hi @goodman-anne, thank you for opening the issue 🙌🏻 
Our recommendation is to create a plugin module in the [community-plugins](https://github.com/backstage/community-plugins) repo or on another external repo as this is a very specific policy. Here is the our "modules" documentation for anyone interested in contributing. We're happy to provide feedback in a pull request 🙂:
https://backstage.io/docs/backend-system/building-plugins-and-modules/index#modules

**Comment by goodman-anne** [comment]
@camilaibs 
Thanks so much for the reply! A plugin module seems to be the way to go then.
I'm so sorry for the rudimentary question but I'm not very familiar with Backstage. In our case if we are trying to control permissions over entities in the catalog based on GitHub collaborators, would the plugin module extend the `catalog backend` like [@backstage/catalog-backend-module-github](https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-github) or would it be from `auth` and we'd have to create some sort of custom resolver like https://github.com/backstage/backstage/issues/23829?

**Comment by Rugvip** [comment]
@goodman-anne most likely it would primarily be an integration with the permission system. I think a good starting point might be to explore how this was been implemented to forward permission decisions to OPA in https://github.com/Parsifal-M/backstage-opa-plugins?tab=readme-ov-file#plugins

**Comment by goodman-anne** [comment]
@Rugvip thanks for the link! I'll check out these OPA docs and try to figure out how to make something like this work with the GitHub authentication already integrated in our backend. If you happen to think of any other similar implementations, I'm all ears.

**Comment by MaeIsBad** [comment]
I'm currently developing a plugin like this for @primait, I think that we'd be interested in publishing it to the community-plugins. No promises/ETA yet though

**Comment by MaeIsBad** [comment]
I don't have the time to open source our plugin at this time, but I can share our permission policy and give a quick overview of how we implemented it. Do note that I wouldn't call this a good implementation, but the best I could come up with at the time, while still learning how to use backstage.

```
class CustomPermissionPolicy implements PermissionPolicy {
  auth: AuthService;
  discovery: DiscoveryApi;

  constructor(auth: AuthService, discovery: DiscoveryApi) {
    this.auth = auth;
    this.discovery = discovery;
  }

  async handle(
    request: PolicyQuery,
    user: PolicyQueryUser,
  ): Promise<PolicyDecision> {
    if (isResourcePermission(request.permission, 'catalog-entity')) {
      const repos = githubID ? await this.getRepos(user.info.userEntityRef) : [];
      const rules = repos.map(r =>
        catalogConditions.hasAnnotation({
          annotation: 'github.com/project-slug',
          value: r,
        }),
      );

      return createCatalogConditionalDecision(request.permission, {
        anyOf: [
          catalogConditions.hasAnnotation({
            annotation:
              'access-control-allow-company-wide',
          }),
          // If entity is not annotated allow access by default
          {
            not: catalogConditions.hasAnnotation({
              annotation: 'github.com/project-slug',
            }),
          },
          ...rules,
        ],
      });
    }

    return { result: AuthorizeResult.ALLOW };
  }
```
The `github.com/project-slug` annotation is automatically added by the `AnnotateScmSlugEntityProcessor`. Note that by default this processor does not add that annotaion to every entity `Kind`

`getRepos` is a function that returns a list of repos the user has access to. We implement this with a plugin that on schedule calls `octokit.rest.repos.listCollaborators` on all github repos in our org and stores that data in a database, exposing it via an http API. When fetching we use the `github.com/user-login` annotation to map users to their github identities.

In an ideal world many improvements could be made, like creating a custom relation like `hasGithubAccess` between the user and all entities with the `github.com/project-slug` annotation, but this simple implementation works well.
