### ISSUE TITLE
Error: error:0480006C:PEM routines::no start line🐛 Bug Report: <title>

### ISSUE THREAD

**Issue by chrisolido** [backstage/backstage#25524]
### 📜 Description

When applying SSL cert 

`ubuntu@ip-172-27-0-123:~/backstage$ yarn start
yarn run v1.22.22
$ yarn workspace app start
$ backstage-cli package start
Loaded config from app-config.yaml

Error: error:0480006C:PEM routines::no start line

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/ubuntu/.nvm/versions/node/v18.20.3/bin/node
Arguments: /home/ubuntu/.nvm/versions/node/v18.20.3/lib/node_modules/yarn/lib/cli.js start
Directory: /home/ubuntu/backstage/packages/app
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ubuntu@ip-172-27-0-123:~/backstage$
`

### 👍 Expected behavior

Should start with HTTPS 

### 👎 Actual Behavior with Screenshots

`~/backstage$ yarn start
yarn run v1.22.22
$ yarn workspace app start
$ backstage-cli package start
Loaded config from app-config.yaml

Error: error:0480006C:PEM routines::no start line

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/ubuntu/.nvm/versions/node/v18.20.3/bin/node
Arguments: /home/ubuntu/.nvm/versions/node/v18.20.3/lib/node_modules/yarn/lib/cli.js start
Directory: /home/ubuntu/backstage/packages/app
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ubuntu@ip-172-27-0-123:~/backstage$
`

### 👟 Reproduction steps

Just folow the SSL cert installation

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hi @chrisolido, were you following a particular tutorial like [this](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/enable-ssl-self-signed.md)? It could be that you need to generate an self-signed X.509 certificate, see [this](https://stackoverflow.com/questions/76586329/how-do-i-solve-error0480006cpem-routinesno-start-line) for reference.
