### ISSUE TITLE
🐛 Bug Report: [DOCS] Wrong Application Link for Bitbucket Server Provider

### ISSUE THREAD

**Issue by flash-me** [backstage/backstage#25526]
### 📜 Description

The docs for the adding the Bitbucket Server Provider states to setup an [outgoing application link](https://backstage.io/docs/auth/bitbucketServer/provider/#create-an-application-link-in-bitbucket-server:~:text=outgoing%20application%20link), which makes no sense in this case. When configuring an outgoing application link, [Bitbucket acts as the OAuth Client](https://confluence.atlassian.com/bitbucketserver/configure-an-outgoing-link-1108483656.html#:~:text=which%20means%20that%20it%20acts%20as%20the%20OAuth%20client). 

### 👍 Expected behavior

What the reader usually wants in this case is to setup an incoming application link, [where Bitbucket acts as the OAuth provider](https://confluence.atlassian.com/bitbucketserver/configure-an-incoming-link-1108483657.html).

### 👎 Actual Behavior with Screenshots

(See Description)

### 👟 Reproduction steps

1. Visit https://backstage.io/docs/auth/bitbucketServer/provider/#create-an-application-link-in-bitbucket-server
2. Be confused

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @flash-me, thanks for logging this, feel free to tag me on the PR to update the documentation so I can help review 👍
