### ISSUE TITLE
🐛 Bug Report: Cron job really old

### ISSUE THREAD

**Issue by dweber019** [backstage/backstage#25546]
### 📜 Description

The cron job seams really old https://github.com/backstage/backstage/actions/runs/5370337951

### 👍 Expected behavior

Remove job

### 👎 Actual Behavior with Screenshots

NA

### 👟 Reproduction steps

NA

### 📃 Provide the context for the Bug.

Maybe this I blocking one slot for the CI.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by dweber019** [comment]
There are also some, which seam really old in the queue https://github.com/backstage/backstage/actions?query=is%3Aqueued

**Comment by dweber019** [comment]
Maybe it would make sense to define a `timeout-minutes` for the cron job, as normally, this should take sub 1 minute.

**Comment by Rugvip** [comment]
<img width="199" alt="image" src="https://github.com/backstage/backstage/assets/4984472/63da0996-634b-4dd0-83a5-98a52968ff19">

🤦 

Just deleted the runs instead, hopefully that fixes it.

Thank you for the heads up! A timeout sounds like a good fix 👍
