### ISSUE TITLE
🐛 Bug Report: GitHub user email not retrieved when using a GitHub app integration

### ISSUE THREAD

**Issue by mathieubrd** [backstage/backstage#25556]
### 📜 Description

I am using the plugin `@backstage/plugin-catalog-backend-module-github-org` to retrieve users from my GitHub organization. In my `app-config.yaml`, I configured the plugin to use a GitHub app, like so:
```yaml
integrations:
  github:
    - host: github.com
      apps:
        - appId: ...
          clientId: ...
          clientSecret: ...
```

I used a custom transformer to retrieve the `email` returned by the GitHub API to enrich my Backstage entities. The `email` field is never retrieved by the `GitHubOrgEntityProvider`.

I checked the source code of this class, it turns out that the function `getOrganizationUsers` only requests the `email` field if the GitHub plugin is configured using a token, not a GitHub app.

Here:
https://github.com/backstage/backstage/blob/91926252e00c57566655c448f33ebcf21437e2ac/plugins/catalog-backend-module-github/src/lib/github.ts#L138C23-L138C43

```typescript
const query = `
  query users($org: String!, $email: Boolean!, $cursor: String) {
    organization(login: $org) {
      membersWithRole(first: 100, after: $cursor) {
        pageInfo { hasNextPage, endCursor }
        nodes {
          avatarUrl,
          bio,
          email @include(if: $email),
          login,
          name,
          organizationVerifiedDomainEmails(login: $org)
        }
      }
    }
  }`;

// There is no user -> teams edge, so we leave the memberships empty for
// now and let the team iteration handle it instead

const users = await queryWithPaging(
  client,
  query,
  org,
  r => r.organization?.membersWithRole,
  userTransformer,
  {
    org,
    email: tokenType === 'token', // <--------- HERE IS THE ISSUE I GUESS
  },
);

return { users };
```

### 👍 Expected behavior

The function `getOrganizationUsers` should include the `email` field in the GraphQL query even if the plugin is configured using a GitHub app and not only with a token.

### 👎 Actual Behavior with Screenshots

The `email` field is only included in the GraphQL query if the plugin is configured with a GitHub token.

### 👟 Reproduction steps

1. Install the plugin `@backstage/plugin-catalog-backend-module-github-org` and use a GitHub app in your `app-config.yaml` like so:
```yaml
integrations:
  github:
    - host: github.com
      token: ...
```
2. Create a custom transformer the retrieve users' email and log it:
```typescript

export const userEmailTransformer: UserTransformer = async (user, ctx) => {
  console.log(user);

  return backstageUser;
};
```
3. Execute your backend, you will see that the `email` field is present.
4. Do the exact same thing but use a GitHub app instead of a token. You will see that the `email` field is no longer present.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
See #5680 for background on why the email is excluded for apps. It could be that this has been fixed on the GitHub end by now, but we'd need to very that exact case that make sure there's a safe way to implement it now.
