### ISSUE TITLE
🐛 Bug Report: GitHub plugins require a renewed login

### ISSUE THREAD

**Issue by davidg-idealo** [backstage/backstage#25566]
### 📜 Description

We configured a GitHub OAuth App on organisation level and are using this for the GitHub Auth provider.
The login works like a charm. We added a bunch of GitHub related plugins like:
* [Roadie GitHub PullRequest](https://www.npmjs.com/package/@roadiehq/backstage-plugin-github-pull-requests)
* [Roadie Github Insights](https://www.npmjs.com/package/@roadiehq/backstage-plugin-github-insights)
* [Community GitHub Actions](https://github.com/backstage/community-plugins/tree/main/workspaces/github-actions/plugins/github-actions)

These plugins trigger further (client side) GitHub API requests to fetch related data. Unfortunately, this does not work out of the box. The user is prompted with a dialogue asking them to log in again:
![Screenshot 2024-07-09 at 13 55 42](https://github.com/backstage/backstage/assets/26434987/0fecd1a3-a9b5-4b29-925e-99a2fc097745)
In addition, the user is asked to log in again depending on the use case (scope). In our setup, the user has to log in once for pull requests and again for the GitHub actions, which is of course very annoying in the workflow.

We also tried to use a GitHub App for the GitHub Auth Provider but the behaviour is still the same.

What we figured out is that the granted-scope after the initial login is `read:user`. This is shown in the cookie `github-granted-scope`. This is not sufficient for the plugins. E.g.: the PullRequest Plugin needs `repo`.
After logging in again for the PullRequest plugin the granted-scope is: `read:user repo`

Cookies after initial login:
![Screenshot 2024-07-10 at 11 13 21](https://github.com/backstage/backstage/assets/26434987/a01d7cc7-09cf-4191-8d18-c93322c15250)
Cookies after second login requested by the Pull Request plugin:
![Screenshot 2024-07-10 at 11 13 43](https://github.com/backstage/backstage/assets/26434987/02d5a4ab-52ff-4e96-8013-ceb6e9e96356)

### 👍 Expected behavior

There is no further login needed when using a GitHub Plugin to fetch further data.

### 👎 Actual Behavior with Screenshots

Using a plugin which fetches further data from GitHub leads to a prompt which requests to login again:
![Screenshot 2024-07-09 at 14 18 29](https://github.com/backstage/backstage/assets/26434987/b5465381-6b4e-4544-aa79-2ee242cdf87c)

### 👟 Reproduction steps

1. Create a new backstage environment `npx @backstage/create-app@latest`
2. Create an OAuth App in GitHub on Org-Level `https://github.com/organizations/$org/settings/applications/new`
3. Setup GitHub Auth Provider in Backstage https://backstage.io/docs/getting-started/config/authentication
4. Add your GitHub user name in `examples/org.yaml`
5. Add a GitHub related plugin (see examples in description) in a suitable entity page
6. Manually onboard one of your repos http://localhost:3000/catalog-import
7. Open the entity page with the GitHub plugin and you will get the login prompt
8. After logging in again, the data will be displayed.

If needed I can provide a repository with the described setup.

### 📃 Provide the context for the Bug.

Our observation is that the granted scope `read:user` after the initial login is not sufficient to fetch further data from the GitHub-API. For this reason, Backstage plugins that use the GitHub API request a login again to extend the scope by the scope required for their use case. E.g.: the [GitHub Actions Plugin](https://github.com/backstage/community-plugins/tree/main/workspaces/github-actions/plugins/github-actions) requires `read:org`.

Our suggestion would be to extend the GitHub Auth Provider and provide a field to configure additional scopes.
This is already the case for the [Okta Auth provider](https://backstage.io/docs/auth/okta/provider/). The field `additionalScopes` offers the option to configure additional scopes.

### 🖥️ Your Environment

```
yarn run v1.22.21
backstage-cli info
OS:   Darwin 23.4.0 - darwin/arm64
node: v20.14.0
yarn: 1.22.21
cli:  0.26.10 (installed)
backstage:  1.28.0

Dependencies:
  @backstage/app-defaults                                          1.5.7
  @backstage/backend-app-api                                       0.7.9
  @backstage/backend-common                                        0.23.2
  @backstage/backend-defaults                                      0.3.3
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.14
  @backstage/backend-plugin-api                                    0.6.21
  @backstage/backend-tasks                                         0.5.26
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.6
  @backstage/cli                                                   0.26.10
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.13.0
  @backstage/core-compat-api                                       0.2.6
  @backstage/core-components                                       0.14.8
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.6
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.28
  @backstage/integration                                           1.12.0
  @backstage/plugin-api-docs                                       0.11.6
  @backstage/plugin-app-backend                                    0.3.70
  @backstage/plugin-app-node                                       0.1.21
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.2
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.13
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.4
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.4
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.16
  @backstage/plugin-auth-backend-module-github-provider            0.1.18
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.18
  @backstage/plugin-auth-backend-module-google-provider            0.1.18
  @backstage/plugin-auth-backend-module-guest-provider             0.1.7
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.16
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.2
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.14
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.2
  @backstage/plugin-auth-backend-module-okta-provider              0.0.14
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.2
  @backstage/plugin-auth-backend                                   0.22.8
  @backstage/plugin-auth-node                                      0.4.16
  @backstage/plugin-auth-react                                     0.1.3
  @backstage/plugin-catalog-backend-module-github                  0.6.4
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.19
  @backstage/plugin-catalog-backend                                1.23.2
  @backstage/plugin-catalog-common                                 1.0.24
  @backstage/plugin-catalog-graph                                  0.4.6
  @backstage/plugin-catalog-import                                 0.12.0
  @backstage/plugin-catalog-node                                   1.12.3
  @backstage/plugin-catalog-react                                  1.12.1
  @backstage/plugin-catalog                                        1.21.0
  @backstage/plugin-events-node                                    0.3.7
  @backstage/plugin-home-react                                     0.1.14
  @backstage/plugin-org                                            0.6.26
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.18
  @backstage/plugin-permission-backend                             0.5.45
  @backstage/plugin-permission-common                              0.7.14
  @backstage/plugin-permission-node                                0.7.32
  @backstage/plugin-permission-react                               0.4.23
  @backstage/plugin-proxy-backend                                  0.5.2
  @backstage/plugin-scaffolder-backend-module-azure                0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.11
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.13
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.11
  @backstage/plugin-scaffolder-backend-module-github               0.3.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.3
  @backstage/plugin-scaffolder-backend                             1.22.11
  @backstage/plugin-scaffolder-common                              1.5.3
  @backstage/plugin-scaffolder-node                                0.4.7
  @backstage/plugin-scaffolder-react                               1.9.0
  @backstage/plugin-scaffolder                                     1.22.0
  @backstage/plugin-search-backend-module-catalog                  0.1.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.26
  @backstage/plugin-search-backend-node                            1.2.26
  @backstage/plugin-search-backend                                 1.5.13
  @backstage/plugin-search-common                                  1.2.12
  @backstage/plugin-search-react                                   1.7.12
  @backstage/plugin-search                                         1.4.13
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.8
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.11
  @backstage/plugin-techdocs-node                                  1.12.7
  @backstage/plugin-techdocs-react                                 1.2.5
  @backstage/plugin-techdocs                                       1.10.6
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.8
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.7
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 2.81s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
This is working as intended, and as you point out the `additionalScopes` configuration is the way to requests additional scopes upfront. This option is now available to all OAuth providers out of the box since the 1.28 release, so you should be able to use this with GitHub too.

**Comment by davidg-idealo** [comment]
Hi @Rugvip,
thanks for the hint. Works like a charm. 🚀

For the sake of completeness, I would like to mention that this works with GitHub OAuth as well as with GitHub Apps.

It would be very valuable if this would be mentioned in the documentation: https://backstage.io/docs/auth/github/provider
Is this planned? Or can I support here?

**Comment by MnLujan** [comment]
Hey guys, I'm currently facing the same problem. 
The main difference is that I'm using Backstage 1.21. I configured the [service-to-service auth](https://github.com/backstage/backstage/blob/master/docs/auth/service-to-service-auth--old.md), [Authenticate API Request](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md) as well, added the provider configurations:

```
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_DEVELOPMENT_CLIENT_ID}
        clientSecret: ${GITHUB_DEVELOPMENT_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
        additionalScopes: ['repo', 'read:org']
```
and still have the same issue 😞  

Would you recommend updating to version 1.24 with the new backend?

**Comment by davidg-idealo** [comment]
Hi @MnLujan,
you need to update to 1.2.8
In this version, the additionalScopes were introduced for all OAuth providers.
https://github.com/backstage/backstage/releases/tag/v1.28.0 >> BREAKING: OAuth Scope Updates

**Comment by MnLujan** [comment]
Thank you @davidg-idealo :)

**Comment by davidg-idealo** [comment]
Providing `additionalScopes` for all Auth providers with version 1.2.8 solves the problem described. The issue can therefore be closed.
