### ISSUE TITLE
Rename `setupRequestMockHandlers` to `registerMswTestHooks` for clarifying what is going on in tests (remember also to rename the frontend method too)

### ISSUE THREAD

**Issue by camilaibs** [backstage/backstage#25563]

**Comment by patroswastik** [comment]
Hey, I am new to open source and would like to contribute to this issue.
What I can see right now is there are 2 test files with the name `setupRequestMockHandlers.ts` and almost 120 files have called this method (including .md files). So, I believe all the mentions of `setupRequestMockHandlers` should be renamed to `setupMswHandlers`, right?

**Comment by camilaibs** [comment]
> Hey, I am new to open source and would like to contribute to this issue. What I can see right now is there are 2 test files with the name `setupRequestMockHandlers.ts` and almost 120 files have called this method (including .md files). So, I believe all the mentions of `setupRequestMockHandlers` should be renamed to `setupMswHandlers`, right?

Hi @patroswastik, there is a pull request in review already for this issues: https://github.com/backstage/backstage/pull/25569

But please pick up one of our [good first issues](https://github.com/backstage/backstage/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee) list, we are happy to happy to see you contributing with us 🙂 .

**Comment by patroswastik** [comment]
Thank you for your reply! I'll take a look at the good first issues and start contributing there.
