### ISSUE TITLE
🐛 Bug Report: Issue using containerSecurityContext.readOnlyRootFilesystem

### ISSUE THREAD

**Issue by coreydaley** [backstage/backstage#25573]
### 📜 Description

While applying additional Kubernetes security contexts to the default Backstage configuration I have run into any issue with enabling the `containerSecurityContext.readOnlyRootFilesystem`.
It seems that Backstage is injecting a redacted version of the `app-config` into one of the javascript files in the `dist/static` directory. This seems very odd to me and by it's very nature unexpected as I would not expect anything in the `dist/static` directory to change.
I have attached a screenshot of the javascript file that is modified (it also looks like the injection also reformats part(s) of the rest of the file resulting in further changes showing up in a diff). 

Does anyone have a reference to why the config is being injected this way instead of just being read into memory by the application and used that way? Maybe the configuration could be injected into a known file location that can be setup as a separate mount so that the rest of the root filesystem can be readonly?

Full example configuration:
```
containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      seccompProfile:
        type: "RuntimeDefault"
```

### 👍 Expected behavior

I would expect that no files in the `dist/static` directory would be changed at runtime and that the configuration would be read into memory or stored in a known file location that could be a separate mounted volume so as to be excluded from the readOnlyRootFilesystem security context.

### 👎 Actual Behavior with Screenshots

Redacted app-config is injected into a randomly named javascript file in the `dist/static` directory which prevents using the readOnlyRootFilesystem security context
![Screenshot 2024-06-27 at 2 47 01 PM](https://github.com/backstage/backstage/assets/5060301/346d26b1-de5f-435c-9678-637985ac6da4)

### 👟 Reproduction steps

Apply the example configuration to a backstage app-config and try to run the application.
```
containerSecurityContext:
      readOnlyRootFilesystem: true
```

### 📃 Provide the context for the Bug.

This issue is preventing us from decreasing the attack surface of the backstage application.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
You should be able to disable this behavior with the [app.disableConfigInjection](https://github.com/backstage/backstage/blob/f5d247fd3c5c4dd03a1c105e6142024e469baad6/plugins/app-backend/config.d.ts#L38) config. We'll want to keep the default as is though, as it's by far the most convenient way to configure the frontend.

There's also an issue somewhere for changing how we forward the config to the app, for example providing it on an endpoint or injecting it into `index.html` instead, but I can't find that one at the minute 😅. I think that would be the proper way forward here anyway.
