### ISSUE TITLE
💬 RFC: TechDoc Redirects

### ISSUE THREAD

**Issue by squid-ney** [backstage/backstage#25578]
### 🔖 Need
Improve handling of broken documentation links in Backstage.

### Problem
Broken links for documentation that has moved or been replaced.
Two main scenarios:
1. Redirect for the case where part of documentation has moved/been renamed.
2. Redirect for the case that the whole documentation site has moved.

##### Mkdocs-redirects plugin with transformer
The [mkdocs-redirects](http://mkdocs-redirects/) plugin resolves this redirect scenario for mkdocs. With some modification, we could make it work in TechDocs too. The plugin generates a redirect HTML file for each of the old docs declared in the redirect map in the `mkdocs.yaml`. Granular redirection is supported, redirects are per page in a documentation site.

Unfortunately, though, this plugin will not work out of the box with TechDocs. There are two main problems with it.
1. The `useSanitizerTransformer` removes the `<script>` and `<meta>` tags from the HTML page.
2. `<meta>` tags do not work in the shadow DOM. The browser needs to process these redirects and it is unaware of them in the shadow DOM.  

Note: This redirect plugin was previously discussed in this [thread](https://github.com/backstage/backstage/issues/4931).	

Therefore, we should transform the `<meta>` tags into a magic link `[techdocs_redirect](url)` and then use an addon to parse the link and perform the redirect. Additionally, if we go the addon path, we could further improve the user redirect experience. For example, by displaying some UI element to notify about the redirect. 

####  Scenario 2: Whole documentation site moved
The whole documentation site moved or was renamed. This is a common case internally for redirects. In this scenario, the old component does not exist in the catalog, but the broken url contains the old component ID. We will use this component ID in the solution detailed below. 

##### Catalog `backstage.io/techdocs-replaces` annotation
If a user renames their component, in the new component, add an attribute `backstage.io/techdocs-replaces` in the catalog-info.yaml. The value will be the old component ID. Within TechDocs, we will add logic to query the Catalog API to see if any components claim to replace the component ID in the current URL. Redirect, if so.

We can't go the other direction and add an annotation like, `backstage.io/techdocs-is-replaced-by` on the old component because the old component should be deleted.

##### Create our own `techdocs-mkdocs-redirects` plugin
We could clone `mkdocs-redirects` and modify the logic to add the `techdocs_redirects` magic link. Or start from scratch and go a different route, like generating the new files at the same path as the old. We would have a lot of autonomy with how we solve this problem. The main con though is that we would need to maintain another plugin. This plugin also may contain duplicate code of `mkdocs-redirects`. The `mkdocs-redirects` solution already solves the problem, so making it work in TechDocs seems more efficient. 

##### Documentation owners add the magic `[techdocs_redirect](url)` link
In this scenario, we would not use the `mkdocs-redirects` plugin. Instead, documentation owners would keep the old markdown file in their repository, but replace the file content with the `techdocs_redirect` magic link. Then, the TechDocs redirect addon will read that keyword and redirect to the new page. The main con with this approach is that the user has to maintain the old file paths in their documentation repository.

##### Redirect from `techdocs-backend` plugin based on `mkdocs-redirect` html files
Redirecting from the backend, is likely not worth the potential benefit to web crawlers, due to the complication of implementation in the BE over FE. For example, the endpoint that retrieves the static files calls the `docsRouter` middleware which is defined in the `PublisherBase` interface and has many different implementations. The `docsRouter` middleware sends the file response to the browser, making it more complicated to determine when to redirect. Also, TechDocs already has a pattern of transformers and addons in the FE.

##### Fix this in the Catalog
The most seamless solution would have the Catalog handle broken links when components are renamed. However, this could take time and we could implement the proposed solution for now.

#### Risks to "Catalog `backstage.io/techdocs-replaces` annotation" solution

1. There could be multiple pages claiming that they replace a documentation site. 
- We would need to decide how to handle this. Redirecting to the first result would be the simplest, but we could try and have more advanced logic to determine the oldest claim to replace the document.
- On the component page of the replacing components we can highlight that the component will not replace the old because another component already claims to.
2. We can't assume paths match across the old component and the new component.
- We could add logic to check if the doc path still exists in the new component or just redirect to the index page of the replacing doc site.
3. What if a component gets renamed multiple times?
- In this case, there would be 2+ old components that a new component needs to replace. We could make the `backstage.io/techdocs-replaces` annotation handle an array of component IDs.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by squid-ney** [comment]
Would love to hear thoughts from the community!

In the meantime, I have been experimenting with these solutions in draft PRs and would like to test them internally at Spotify. I may merge some code in beta, but it should not affect other consumers of TechDocs and can always be reversed if feedback for this RFC takes us in a different direction. 😄  It would be just to enable testing the proposal and getting user feedback internally.

**Comment by Rugvip** [comment]
Nice! 👍 

For the partial move it sounds like adjacent metadata in some form is the way to go indeed, which is then transformed during rendering. It can indeed be good to notify of the redirect.

For the full move I'd think it's best if we want solve that at the catalog level tbh, rather than an annotation that's specific to TechDocs. Most discussions so far about moving things in the catalog have been to move code but keep the name intact, this case is a little bit different and maybe simpler? There's a proposal towards this over here: https://github.com/backstage/backstage/issues/5231#issuecomment-2016342479. I'd expect the hardest part of this to figure out what the response should be from the different catalog APIs when accessing a moved entity. I doubt you'd want moved entities to show up when listing, only when fetching single entities, but on top of that there's batch endpoints and permissions to complicate things x)

**Comment by squid-ney** [comment]
Hi Patrik, thanks for linking that catalog proposal! The `movedFrom` relationship would be great and looks like it covers the use case of the `backstage.io/techdocs-replaces` annotation I proposed here. I agree, it would be a better solution to have the relationship be used across Backstage vs just TechDocs specific. 

Perhaps, I can start on the work for "Scenario 2: Whole documentation site moved" proposed in this RFC, but use the `movedFrom` relationship instead. Then, down the line if there is capacity for the catalog processor or other plugins to extend the functionality, the same annotation can be used.

**Comment by squid-ney** [comment]
From [Catalog documentation](https://backstage.io/docs/features/software-catalog/well-known-relations/#relations)
> Each relation has a `source` (implicitly: the entity that holds the relation), a `target` (the entity to which the source has a relation), and a type that tells what relation the source has with the target. 

Thinking more about the `movedFrom` annotation, it seems like this relation would be an outlier amongst the other well-known relations because the target in this relationship would be an entity that no longer exists.

**Comment by squid-ney** [comment]
@Rugvip

There is one scenario seen internally for TechDocs that the `movedFrom` annotation would not cover: when documentation moves from a component to the component's system entity. This is the main scenario I can think of for a TechDocs site moving separately from the owning entity. 

In this case, the documentation owner could use the `mkdocs-redirects` solution since the component still exists. However, it would be tedious to write out the redirect map for an entire TechDocs site. On the other hand, it also isn't ideal to have an annotation like `backstage.io/techdocs-replaces` specifically for this scenario because it creates overlap with the `movedFrom` annotation.

**Comment by iamEAP** [comment]
> _The `useSanitizerTransformer` removes the `<script>` and `<meta>` tags from the HTML page._

Would be worth investigating how easy (and precisely) you could allow the redirect meta tag through the DOMPurify sanitizer.

Since it has no effect in the shadow DOM, and because the server always responds with the HTML using plain text content type headers, I can't think of any downsides from a security perspective if you can safely only allow the redirect meta tag.

You'd still need an addon to parse out the tag and react to it, but you'd avoid having to do any pre-transformations in mkdocs-land. And, you'd be building the addon based on a well-understood standard.

**Comment by Rugvip** [comment]
For the case of things being moved across existing entities, I wonder if the simplest approach there might be to simply manually link to the new docs in the old TechDocs content?

**Comment by squid-ney** [comment]
@iamEAP  Hi Eric! In a past experiment, with DOMPurifier, I allowed all `meta` tags and `content` attributes.  I'll look into if I can get more precise than that. Would you mind sharing a link to the example you mentioned?

**Comment by squid-ney** [comment]
@Rugvip True. Thinking about it more, the scenario I mentioned makes sense as the responsibility of site maintainers to be good stewards of their documentation. If they moved documentation from a site they continue to maintain, then there shouldn't be a problem with having them inform/link their readers. They can either add an explanation and link to the new docs as you mentioned or redirect their users using the `mkdocs-redirect` plugin map. 

We can go ahead with only performing the automatic redirects for scenarios in which the old component no longer exists and there is a `movedFrom` relationship.

**Comment by iamEAP** [comment]
> _Would you mind sharing a link to the example you mentioned?_

Sure thing @squid-ney! I was imagining another transformer being applied somewhere in this hook: https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/components/TechDocsReaderPageContent/dom.tsx#L162-L163

**Comment by squid-ney** [comment]
Hey @iamEAP ! I have a draft PR, https://github.com/backstage/backstage/pull/25766 based on the suggestions you made in this RFC. This PR does not use and addon and instead lifts the meta tags from the shadowDom to the main document. Wanted to get your thoughts before I clean it up and add tests.

**Comment by squid-ney** [comment]
@Rugvip I have another concern with not redirecting TechDocs sites that move independently of their component. Mostly regarding the potential for consumers to land on outdated TechDoc sites.  For example, with documentation moving from component -> system, even if the site owners link the new documentation site on their home page, users could visit old links with nested paths would result in a 404 on the TechDocs site or outdated documentation if old pages weren't cleaned up. 

For the 404 scenario specifically, we definitely could have better handling within the TechDocs plugin. For ex: if a TechDoc site exists and the user navigates to a non-existing sub path, then fall back to the home page of the site. However, if the old pages aren't removed from the old component site, then the user is reading outdated documentation and that is concerning.  We would be asking the owner to remove all the outdated documentation and update the home page with content linking to the new documentation and then they would need to confirm a successful documentation build so the prod site gets updated. Having an annotation specific for moved documentation, `backstage.io/techdocs-replaces`, would simplify this process for the user, hopefully resulting in less 404s or outdated docs.

**Comment by Rugvip** [comment]
@squid-ney yep for this case I think it makes sense to have a solution specific to TechDocs, since that's really only where the redirect applies.

So to summarize:
- For cases where the old entity doesn't exist we introduce a catalog-wide concept that allows redirecting from old entities
- For cases where the old entity does exist but we want to redirect users to a new TechDocs page, we introduce a TechDocs-specific concept that allows redirecting to the new docs
