### ISSUE TITLE
🐛 Bug Report: Techdoc not using `BackstageContent` override color

### ISSUE THREAD

**Issue by LegendSebastianoL** [backstage/backstage#25582]
### 📜 Description

is there a way to change the techdocs body background color?

Currently is using the `background.default` from the custom theme, instead of using the override BackstageContent
```
...
      background: {
        default: '#040A1E',
        paper: '#363B4B',
      },
...
    BackstageContent: {
      styleOverrides: {
        root: {
          background: '#1D2335',
        },
      },
    },
...
```

![image](https://github.com/backstage/backstage/assets/61748264/28b59428-7525-4582-ade2-cbb2c2b05ae3)

### 👍 Expected behavior

if the custom theme has a `BackstageContent` the techdocs should use the same color

### 👎 Actual Behavior with Screenshots

Currently is using the `background.default` from the custom theme, instead of using the override BackstageContent.

### 👟 Reproduction steps

- create a custom theme
- copy the above snippet
- create a techdocs

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Yep this may not be available, but I'll defer to @backstage/techdocs-maintainers

**Comment by LegendSebastianoL** [comment]
any info on this?

**Comment by LegendSebastianoL** [comment]
for now I solved it with this in the GitHub workflow `find ./site/assets/stylesheets/ -name 'main.*.min.css' -exec sed -i 's/body{background-color:var(--md-default-bg-color);/body{background-color:#1D2335;/g' {} +`

It's not nice but it does the job, would be good to be able to set it somewhere.

**Comment by squid-ney** [comment]
Hi there!
I took a look at this and created a test theme locally that has a default background of green and overrides the `BackstageContent` background to blue. 
Test theme:

```typescript
export const myTheme = createUnifiedTheme({
  ...createBaseThemeOptions({
    palette: {
      ...palettes.light,
      background: {
        default: 'green',
      },

    },
  }),
  components: {
    BackstageContent: {
      styleOverrides: {
        root: {
          background: 'blue',
        },
      },
    },
  }
});

```
This is the result I saw on TechDocs.
<img width="1344" alt="Screenshot 2024-08-06 at 7 24 29 PM" src="https://github.com/user-attachments/assets/7be168a1-d63a-4502-95c1-243eccdc6045">

Why we are seeing this behavior:
The content override is getting applied to the div (as shown by the blue color in the screenshot). However, TechDocs has a style transformer that applies specific styles to the mkdocs content. [This line here](https://github.com/backstage/backstage/blob/2c08403f619f4f3fff7ba965df1d6118bebca3e8/plugins/techdocs/src/reader/transformers/styles/rules/variables.ts#L38) is causing the behavior you reported. 

Fix:
I'm not sure if these background overrides are still needed. TechDocs seemed to render fine locally when I tested removing them. I'll take a further look and get back to you.

**Comment by LegendSebastianoL** [comment]
hey :) 

If I remove the background overrides then I would need to override the table odds color to don't be the same as the background color. which is using the same variable in the end.

![image](https://github.com/user-attachments/assets/e7c8754b-aba8-40ca-88ad-049a08a1d63c)

**Comment by squid-ney** [comment]
Hi apologies for the confusion! I meant that the fixed background styles [line here](https://github.com/backstage/backstage/blob/2c08403f619f4f3fff7ba965df1d6118bebca3e8/plugins/techdocs/src/reader/transformers/styles/rules/variables.ts#L38) may not be needed anymore. Agree that the ability to override Backstage and Material UI components styles is needed and supported. 😄

**Comment by LegendSebastianoL** [comment]
no problem :)

**Comment by LegendSebastianoL** [comment]
another thing that would be good to remove as well is the color of the sidebar header, see screenshot.
it makes it a bit ugly to see considering that it lack some space between the title and the list.


![image](https://github.com/user-attachments/assets/9fb10ffd-1c59-4552-9a94-597123cfe171)

**Comment by squid-ney** [comment]
Hi there, following up! Since the mkdocs markdown page is rendered in the `shadowDom`, styles are applied to the `shadowDom` via the style transformers which causes limitations when reconciling the theme and overrides. I think it is for the best that the style transformers reference the theme because that should work for 90% of adopters use cases. To handle the edge case, I think allowing the theme to be modified specifically for the `TechDocsReader` page could solve your use case. This would allow changing the palette & fonts specifically for the TechDocs content while the rest of Backstage uses the default App level theme.

Here is a draft PR: https://github.com/backstage/backstage/pull/25956
The changes in `App.tsx` are just to illustrate how this solution could solve your use-case, they would be removed before merging. What are your thoughts?

**Comment by LegendSebastianoL** [comment]
hey :) that's looking awesome, as far as I'm allowed to customize it I don't mind if it needs to be done in the `App.tsx`

**Comment by LegendSebastianoL** [comment]
I understand this will be available in the next Backstage update right?

**Comment by LegendSebastianoL** [comment]
hey @squid-ney I just updated Backstage and applied the fix though it isn't what I was expecting, this is the result:
![image](https://github.com/user-attachments/assets/51b12f6a-9d18-4c7c-a27b-037a789b005a)

I'm using this code in my App.tsx
```js
// const overrideThemeOptions: Partial<ThemeOptions> = {
//   palette: {
//     background: {
//       default: '#1D2335',
//     },
//   },
// };
```
