### ISSUE TITLE
Unable to deploy backstage on kuberntes

### ISSUE THREAD

**Issue by kdr407** [backstage/backstage#25583]
### 📜 Description

Following the link : https://backstage.io/docs/deployment/k8s and deploying the backstage image on kubernetes. 

After you deploy the kubernetes/backstage.yaml file . the Pods getting error Crashloopback error. 

### 👍 Expected behavior

$ kubectl get deployments --namespace=backstage
NAME        READY   UP-TO-DATE   AVAILABLE   AGE
backstage   1/1     1            1           1m

### 👎 Actual Behavior with Screenshots

$ kubectl get deployments --namespace=backstage
NAME        READY   UP-TO-DATE   AVAILABLE   AGE
backstage   0/1     1            1           1m

### 👟 Reproduction steps

https://backstage.io/docs/deployment/k8s

### 🖥️ Your Environment

Using Minikube

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Hi! Please provide more information about why the deployed instance is not starting up correctly.
