### ISSUE TITLE
🐛 Bug Report: Left navigation gets stepped on with mkdocs-material blog feature, for full blog posts, at wide resolution

### ISSUE THREAD

**Issue by bcotton** [backstage/backstage#25581]
### 📜 Description

Originally reported at [Left navigation gets stepped on with mkdocs-material blog feature, for full blog posts, at wide resolution · Issue #159 · backstage/mkdocs-techdocs-core](https://github.com/backstage/mkdocs-techdocs-core/issues/159)

I'm using the new 1.3 version of this plugin, which enables the `mkdocs-material` blog plugin.

My `mkdocs.yaml` file looks like this:

```
site_name: 'Internal Blog for Bob Cotton'

theme:
  name: material
  features:
    - navigation.sections
nav:
  - Home: 'index.md'
  - Blog:
     - 'blog/index.md'

plugins:
  - techdocs-core
  - blog:
      post_url_format: "{date}/{slug}"
```

When the site get rendered, both under our backstage instance, and using `techdocs-cli` everything looks great, The nav on the left is correct. All the blog features are working.

Except when you drill down into a full blog post ("continue reading" or click on a post header)  and you have your screen resolution fairly wide (anything wider than when the hamburger gets rendered on the right side)

When looking at the list of posts, the left nav is great: 

![CleanShot 2023-12-06 at 09 05 35@2x](https://github.com/backstage/mkdocs-techdocs-core/assets/1392/09beb1be-a7ed-44de-9be5-f6d734f0eaf6)

However, when you select, or link directly to a post, the left-hand navigation get smashed into the content. e.g. 

![CleanShot 2023-12-06 at 09 22 09@2x](https://github.com/backstage/mkdocs-techdocs-core/assets/1392/9e4f5dde-079c-46c6-a41b-9e9cdae7ae2f)

When run under the `techdocs-core` container, without the backstage wrapper, it looks like this:

![CleanShot 2023-12-06 at 11 17 37@2x](https://github.com/backstage/mkdocs-techdocs-core/assets/1392/266c7d18-8cf7-4d61-b7b9-7a7b3d646e56)

I've created a repo with content and instructions to reproduce the issue
https://github.com/bcotton/techdocs-blog-testing

Not a front-end dev, so poking in the dark here, however,  Looking at chrome dev-tools, if I disable 
```
.md-sidebar {
  position: fixed;
}
```
Then it's lays out correctly

![CleanShot 2023-12-06 at 11 20 21@2x](https://github.com/backstage/mkdocs-techdocs-core/assets/1392/572ad28c-fa89-43c9-a99b-279788573e2e)

### 👍 Expected behavior

The navigation on the left should align correctly

### 👎 Actual Behavior with Screenshots

See above

### 👟 Reproduction steps

See `mkdocs.yaml` above

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Thanks for moving this over @bcotton, this does seem like the right place for it.
