### ISSUE TITLE
🚀 Feature: Allow for removal of some entity kinds from the catalog "Kind" filter dropdown

### ISSUE THREAD

**Issue by ColetteDeBeer** [backstage/backstage#25591]
### 🔖 Feature description

I would like to customize which entity types users can filter the catalog on by removing certain entity types from the dropdown.
![image](https://github.com/backstage/backstage/assets/141144710/d2a2178e-1af9-4b08-96b1-9bff40a829a8)

### 🎤 Context

I am currently not using all entity types for my catalog so to keep the UI clean, it would be wonderful if I could remove these unused kinds from the filter dropdown on the catalog default home page.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @ColetteDeBeer, you could simply setup a permission policy that does that. Permissions getting started docs are here: https://backstage.io/docs/permissions/getting-started

**Comment by ColetteDeBeer** [comment]
> Hi @ColetteDeBeer, you could simply setup a permission policy that does that. Permissions getting started docs are here: https://backstage.io/docs/permissions/getting-started

Thank you so much for the quick reply! I will look into this.

**Comment by Rugvip** [comment]
You can also customize this through the `allowedKinds` prop for the `EntityKindPicker`. See https://backstage.io/docs/features/software-catalog/catalog-customization#customize-filters for how to customize the catalog page filters in general. Gonna close this since this is already implemented.
