### ISSUE TITLE
Ability to control the refresh token max Age

### ISSUE THREAD

**Issue by bbasu** [backstage/backstage#25595]
### 📜 Description

We use backstage for a customer facing portal, the auth idp is Okta.

Backstage now has the ability to configure the backstage access token duration (minimum being 10mins), however, the refresh token duration is hard coded to 1000 days. For modern browsers the http secure cookie has a max 400 days duration, hence the refresh token cookie that is getting set is for 400 days.

We would want to control this so that our application does force logouts after a smaller duration (like 6hrs), I was looking through the code and I could find the implementation here:

```plugins\auth-backend\src\lib\oauth\OAuthAdapter.ts```

![image](https://github.com/backstage/backstage/assets/14269816/959cbf8e-961d-4d2c-9f9b-81105e1ce6a0)

We tried overriding the whole plugin, however after moving to the new BE plugin system this code does not seem to be invoked. We found another place where this same implementation is defined:

```plugins\auth-node\src\oauth\OAuthCookieManager.ts```

In the new BE system, the oktaAuthenticator imported from @backstage/plugin-auth-backend-module-okta-provider seems to be using the 
```createOAuthProviderFactory```  from auth-node which is internally using the ```OAuthCookieManager.```

![image](https://github.com/backstage/backstage/assets/14269816/7c16d109-0640-4f40-b5fb-aaa1e65a2e77)

Can you please tell me whats the cleanest way to override this piece of code so that we can control the refresh token max age.

### 👍 Expected behavior

We would want to control this so that our application does force logouts after a smaller duration (like 6hrs), 

### 👎 Actual Behavior with Screenshots

Has no ability to control the max age of refresh token.

### 👟 Reproduction steps

Create a new backstage app

Run the backstage app

Observe the refresh token duration in the cookie after refresh is invoked.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
I think is something we can add as a configuration parameter in the auth Backend tbh, I see that it could be useful. Although I do want to note that there are a few other solutions out there, like https://backstage.io/docs/auth/autologout/ or configuring the refresh token expiration in the identity provider itself for those that support that.

For making it configurable I have a feeling it might make the most sense to have it tied to OAuth providers directly and configured as part of each provider. That does allow you to have different durations for different providers and envs, and avoid the need to pass it from the plugin config to the provider, but ofc might also lead to some repetition. We should be able to read it from config and pass it forward [here](https://github.com/backstage/backstage/blob/dd99788e6bd85034e3aa8252723e6b5513ca8abe/plugins/auth-node/src/oauth/createOAuthRouteHandlers.ts#L107).

**Comment by bbasu** [comment]
Regarding configuring this at the provider end, in our case the IDP is Okta and for okta, the refresh token duration is overriden in the code to 1000 days, this is irrespective of what is set in okta, so the overrides are at the backstage end and does not take into consideration what is set at the IDP level
