### ISSUE TITLE
💬 RFC: Examples for Github Auth Integration

### ISSUE THREAD

**Issue by kotowick** [backstage/backstage#25597]
### 🔖 Need

Hey friends,

Wondering if anyone has any good examples of the Github Auth integration successfully working with the latest release/framework of backstage.

I have it working to the extent where adding "github usernames" under `examples/org.yaml`:

`
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: someGHUserNameHere
spec:
  memberOf: [guests]
---
`

But as I understand, it's possible to skip this and auto sync from Github. It doesn't make sense to manage a file like this.

### 🎉 Proposal

N/A

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
Sounds like you want a [GitHub org data integration](https://backstage.io/docs/integrations/github/org). I'm going to close this issue as it's not actionable, but please join our [community Discord](https://discord.gg/backstage-687207715902193673) if you have any further questions!
