### ISSUE TITLE
🐛 Bug Report: Requests for static TechDocs content missing Authorization header

### ISSUE THREAD

**Issue by Xiol** [backstage/backstage#25608]
### 📜 Description

I have a new installation of Backstage running as an Azure Web App, using Azure Easy Auth for authentication. Everything seems to be working fine except when I try to load TechDocs.

When visiting a TechDocs page, the static content first retrieved appears to be a CSS file. This gets a 401 status and then no more content is loaded. Unlike requests to other paths, the request for the CSS file is missing an `Authorization` header, which from [my understanding](https://backstage.io/docs/auth/service-to-service-auth) should be generated and injected by Backstage itself.

TechDocs content is stored in an Azure Storage Container.

If I use my browser DevTools to copy the request out as a curl request and add an `Authorization` header taken from one of the successful requests, I can successfully retrieve the CSS file. Because of this I'm confident the TechDocs<->Storage Container setup is correct, and the problem lies within Backstage.

We have not applied any major customisations to our Backstage installation yet, this all an out-of-the-box experience with configuration taken directly from the Backstage documentation.

An example failing request. Note the missing `Authorization` header.

![image](https://github.com/user-attachments/assets/a8776cec-8e57-4bfa-85f0-f4690ee632c2)
![image](https://github.com/user-attachments/assets/ba050516-e43b-426c-9ff0-be684364832f)

Relevant `app-config.yaml` configuration sections:

```
techdocs:
  builder:
  generator:
    runIn: 'local'
  publisher:
    type: 'azureBlobStorage'
    azureBlobStorage:
      containerName: ${AZURE_STORAGE_CONTAINER_NAME}
      credentials:
        accountName: ${AZURE_STORAGE_ACCOUNT_NAME}
        accountKey: ${AZURE_STORAGE_ACCOUNT_KEY}

auth:
  environment: production
  providers:
    azureEasyAuth:
      signIn:
        resolvers:
          - resolver: idMatchingUserEntityAnnotation
          - resolver: emailMatchingUserEntityProfileEmail
          - resolver: emailLocalPartMatchingUserEntityName
```

### 👍 Expected behavior

TechDocs content should load successfully.

### 👎 Actual Behavior with Screenshots

TechDocs page stalls loading with no error, the loading bar continuously moving. Only when inspecting through DevTools does it become apparent there is a problem, with the stylesheet expected from the rendered TechDocs returning a 401.

![image](https://github.com/user-attachments/assets/c4380fe9-6de4-4fc7-837e-dbe15f02bc80)

The only console message is the following, which I presume is down to the stylesheet returning an error as JSON instead of the actual stylesheet:

```
Refused to apply style from 'https://host.tld/api/techdocs/static/docs/default/component/xxxxxxxxxxxxx/assets/stylesheets/main.6543a935.min.css' because its MIME type ('application/json') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

Copying the stylesheet request out as a curl command and running it shows the returned content to be:

```json
{"error":{"name":"AuthenticationError","message":"Missing credentials"},"request":{"method":"GET","url":"/api/techdocs/static/docs/default/component/xxxxxxxxxxxx/assets/stylesheets/main.6543a935.min.css"},"response":{"statusCode":401}}
```

### 👟 Reproduction steps

Unknown. I created a new Backstage app initially on 1.28.0 (since upgraded to 1.28.4) and followed the documentation to get Backstage working on Azure behind Azure EasyAuth. I have configured catalog providers and integrations as per the documentation, pasting code directly from the documentation into Backstage with no modification.

### 🖥️ Your Environment
(OUTDATED, see [comment](https://github.com/backstage/backstage/issues/25608#issuecomment-2227974920))

```
OS:   Linux 6.9.7-200.fc40.x86_64 - linux/x64
node: v20.14.0
yarn: 1.22.22
cli:  0.26.10 (installed)
backstage:  1.28.4

Dependencies:
  @backstage/app-defaults                                          1.5.7
  @backstage/backend-app-api                                       0.7.9
  @backstage/backend-common                                        0.0.0-nightly-20240625021714, 0.23.2
  @backstage/backend-defaults                                      0.3.3
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.0.0-nightly-20240625021714, 0.1.14
  @backstage/backend-plugin-api                                    0.0.0-nightly-20240625021714, 0.6.21
  @backstage/backend-tasks                                         0.0.0-nightly-20240625021714, 0.5.26
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.6
  @backstage/cli                                                   0.26.10
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.13.0
  @backstage/core-compat-api                                       0.2.6
  @backstage/core-components                                       0.14.8
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.6
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.28
  @backstage/integration                                           1.12.0
  @backstage/plugin-api-docs                                       0.11.6
  @backstage/plugin-app-backend                                    0.3.70
  @backstage/plugin-app-node                                       0.1.21
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.2
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.13
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.4
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.4
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.16
  @backstage/plugin-auth-backend-module-github-provider            0.1.18
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.18
  @backstage/plugin-auth-backend-module-google-provider            0.1.18
  @backstage/plugin-auth-backend-module-guest-provider             0.1.7
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.16
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.2
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.14
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.2
  @backstage/plugin-auth-backend-module-okta-provider              0.0.14
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.2
  @backstage/plugin-auth-backend                                   0.22.8
  @backstage/plugin-auth-node                                      0.0.0-nightly-20240625021714, 0.4.16
  @backstage/plugin-auth-react                                     0.1.3
  @backstage/plugin-catalog-backend-module-azure                   0.1.41
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.20
  @backstage/plugin-catalog-backend-module-logs                    0.0.0-nightly-20240625021714
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.19
  @backstage/plugin-catalog-backend                                0.0.0-nightly-20240625021714, 1.23.2
  @backstage/plugin-catalog-common                                 1.0.24
  @backstage/plugin-catalog-graph                                  0.4.6
  @backstage/plugin-catalog-import                                 0.12.0
  @backstage/plugin-catalog-node                                   0.0.0-nightly-20240625021714, 1.12.3
  @backstage/plugin-catalog-react                                  1.12.1
  @backstage/plugin-catalog                                        1.21.0
  @backstage/plugin-events-backend                                 0.3.8
  @backstage/plugin-events-node                                    0.0.0-nightly-20240625021714, 0.3.7
  @backstage/plugin-org                                            0.6.26
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.18
  @backstage/plugin-permission-backend                             0.5.45
  @backstage/plugin-permission-common                              0.7.14
  @backstage/plugin-permission-node                                0.0.0-nightly-20240625021714, 0.7.32
  @backstage/plugin-permission-react                               0.4.23
  @backstage/plugin-proxy-backend                                  0.5.2
  @backstage/plugin-scaffolder-backend-module-azure                0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.11
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.13
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.11
  @backstage/plugin-scaffolder-backend-module-github               0.3.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.3
  @backstage/plugin-scaffolder-backend                             1.22.11
  @backstage/plugin-scaffolder-common                              1.5.3
  @backstage/plugin-scaffolder-node                                0.4.7
  @backstage/plugin-scaffolder-react                               1.9.0
  @backstage/plugin-scaffolder                                     1.22.0
  @backstage/plugin-search-backend-module-catalog                  0.0.0-nightly-20240625021714, 0.1.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.26
  @backstage/plugin-search-backend-node                            0.0.0-nightly-20240625021714, 1.2.26
  @backstage/plugin-search-backend                                 1.5.13
  @backstage/plugin-search-common                                  1.2.12
  @backstage/plugin-search-react                                   1.7.12
  @backstage/plugin-search                                         1.4.13
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.8
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.11
  @backstage/plugin-techdocs-node                                  1.12.7
  @backstage/plugin-techdocs-react                                 1.2.5
  @backstage/plugin-techdocs                                       1.10.6
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.8
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.7
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @Xiol, one things worth trying is to be properly on the latest version without these various nightly packages. Would help better validate things.

**Comment by Xiol** [comment]
I am immensely unqualified to be doing anything with a React codebase, so I have been following the docs closely, trying to avoid making any deviations. I'm not sure how nightly packages have ended up being installed.

I have used the `version:bump` tooling, but as per the docs, with no arguments. 

Could you advise how to rectify this, or point me to some documentation?

**Comment by darylgraham** [comment]
@Xiol Try removing @backstage/plugin-catalog-backend-module-logs, I'm fairly sure it's pre-release and caused the same issues for me.

**Comment by awanlin** [comment]
Can you clarify, @darylgraham, that packages cause the same auth issue or the various `next` packages being included or both?

**Comment by darylgraham** [comment]
@awanlin that was the cause of the next packages for me.

**Comment by Xiol** [comment]
Seems I added the `@backstage/plugin-catalog-backend-module-logs` package when following the documentation for the catalog configuration, which has a [logging section](https://backstage.io/docs/features/software-catalog/configuration/#logging-errors). This doesn't suggest the package is pre-release! However, I can confirm removing that package has removed all the nightly packages from my installation. Thanks for the pointers, @darylgraham.

<details>
<summary>Click for new `backstage-cli info` output</summary>

```
OS:   Linux 6.9.8-200.fc40.x86_64 - linux/x64
node: v20.14.0
yarn: 1.22.22
cli:  0.26.10 (installed)
backstage:  1.28.4

Dependencies:
  @backstage/app-defaults                                          1.5.7
  @backstage/backend-app-api                                       0.7.9
  @backstage/backend-common                                        0.23.2
  @backstage/backend-defaults                                      0.3.3
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.14
  @backstage/backend-plugin-api                                    0.6.21
  @backstage/backend-tasks                                         0.5.26
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.6
  @backstage/cli                                                   0.26.10
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.13.0
  @backstage/core-compat-api                                       0.2.6
  @backstage/core-components                                       0.14.8
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.6
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.28
  @backstage/integration                                           1.12.0
  @backstage/plugin-api-docs                                       0.11.6
  @backstage/plugin-app-backend                                    0.3.70
  @backstage/plugin-app-node                                       0.1.21
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.2
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.13
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.4
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.4
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.16
  @backstage/plugin-auth-backend-module-github-provider            0.1.18
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.18
  @backstage/plugin-auth-backend-module-google-provider            0.1.18
  @backstage/plugin-auth-backend-module-guest-provider             0.1.7
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.16
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.2
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.14
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.2
  @backstage/plugin-auth-backend-module-okta-provider              0.0.14
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.2
  @backstage/plugin-auth-backend                                   0.22.8
  @backstage/plugin-auth-node                                      0.4.16
  @backstage/plugin-auth-react                                     0.1.3
  @backstage/plugin-catalog-backend-module-azure                   0.1.41
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.20
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.19
  @backstage/plugin-catalog-backend                                1.23.2
  @backstage/plugin-catalog-common                                 1.0.24
  @backstage/plugin-catalog-graph                                  0.4.6
  @backstage/plugin-catalog-import                                 0.12.0
  @backstage/plugin-catalog-node                                   1.12.3
  @backstage/plugin-catalog-react                                  1.12.1
  @backstage/plugin-catalog                                        1.21.0
  @backstage/plugin-events-backend                                 0.3.8
  @backstage/plugin-events-node                                    0.3.7
  @backstage/plugin-org                                            0.6.26
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.18
  @backstage/plugin-permission-backend                             0.5.45
  @backstage/plugin-permission-common                              0.7.14
  @backstage/plugin-permission-node                                0.7.32
  @backstage/plugin-permission-react                               0.4.23
  @backstage/plugin-proxy-backend                                  0.5.2
  @backstage/plugin-scaffolder-backend-module-azure                0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.11
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.13
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.11
  @backstage/plugin-scaffolder-backend-module-github               0.3.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.3
  @backstage/plugin-scaffolder-backend                             1.22.11
  @backstage/plugin-scaffolder-common                              1.5.3
  @backstage/plugin-scaffolder-node                                0.4.7
  @backstage/plugin-scaffolder-react                               1.9.0
  @backstage/plugin-scaffolder                                     1.22.0
  @backstage/plugin-search-backend-module-catalog                  0.1.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.26
  @backstage/plugin-search-backend-node                            1.2.26
  @backstage/plugin-search-backend                                 1.5.13
  @backstage/plugin-search-common                                  1.2.12
  @backstage/plugin-search-react                                   1.7.12
  @backstage/plugin-search                                         1.4.13
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.8
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.11
  @backstage/plugin-techdocs-node                                  1.12.7
  @backstage/plugin-techdocs-react                                 1.2.5
  @backstage/plugin-techdocs                                       1.10.6
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.8
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.7
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
Done in 0.49s.
```
</details>

Unfortunately, the issue still remains as described above.

**Comment by marcus-crane** [comment]
Are you using the version of Techdocs provided by the new backend system? You should have something like this if so:

```
// packages/backend/index.ts

[ various imports ...]

const backend = createBackend();

[ various backend.add calls...]

backend.add(import('@backstage/plugin-techdocs-backend/alpha'));

[ various backend.add calls...]

backend.start();
```

Having just upgraded to the new backend myself, I had been using the legacy version of Techdocs (ie; `backend.add(legacyPlugin('techdocs', import('./plugins/techdocs')));`

Unfortunately it seems that using the legacy version of Techdocs with the new backend doesn't work as it has no way to do service authorization.

I would guess you're already using the new version since you created a new app with 1.28 but honestly, I find parts of the docs are still out of date and confusing if you're not aware about the rearchitecture

**Comment by Jenson3210** [comment]
We are also seeing this issue + there is a support chat open on discord also by someone else which I am following. Might be worth following that one also. 

Seeing a 401 only on `/api/techdocs/static/docs/default/system/.../assets/stylesheets/main.6543a935.min.css` after enabling permissions. 

We do have the new backend system enabled and no nightly dependencies.

**Comment by Xiol** [comment]
@marcus-crane, yes I'm using the new backend system. The complete `backend/src/index.ts` is:

<details> 
<summary>Click to see `backend/src/index.ts`</summary>

```typescript
import { createBackend } from '@backstage/backend-defaults';

const backend = createBackend();

backend.add(import('@backstage/plugin-app-backend/alpha'));
backend.add(import('@backstage/plugin-proxy-backend/alpha'));
backend.add(import('@backstage/plugin-scaffolder-backend/alpha'));
backend.add(import('@backstage/plugin-techdocs-backend/alpha'));

// auth plugin
backend.add(import('@backstage/plugin-auth-backend'));
// backend.add(import('@backstage/plugin-auth-backend-module-guest-provider'));
// See https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin
backend.add(
  import('@backstage/plugin-auth-backend-module-azure-easyauth-provider'),
);

// catalog plugin
backend.add(import('@backstage/plugin-catalog-backend/alpha'));
backend.add(
  import('@backstage/plugin-catalog-backend-module-scaffolder-entity-model'),
);

// permission plugin
backend.add(import('@backstage/plugin-permission-backend/alpha'));
backend.add(
  import('@backstage/plugin-permission-backend-module-allow-all-policy'),
);

// search plugin
backend.add(import('@backstage/plugin-search-backend/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-catalog/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-techdocs/alpha'));

// gitlab plugin
backend.add(import('@backstage/plugin-catalog-backend-module-gitlab/alpha'));

// ADO plugin
backend.add(import('@backstage/plugin-catalog-backend-module-azure/alpha'));

backend.start();
```
</details>

I'm making the assumption the load order doesn't matter?

@Jenson3210, will check out the Discord. I'll be honest, I'm glad it's not just me...

**Comment by Jenson3210** [comment]
@Xiol here you can find similar issue. Not saying it's related but looks similar for sure. 
[link to question](https://discord.com/channels/687207715902193673/1261411441819259031)

**Comment by Xiol** [comment]
Just to test, I temporarily added:

```
backend:
  auth:
    dangerouslyDisableDefaultAuthPolicy: true
```

To my `app-config.yaml` which allows TechDocs to load successfully, but obviously isn't something that I can use as a workaround. Does point to something wrong with authentication within Backstage, though.

**Comment by awanlin** [comment]
Hi, I've been helping here and on Discord. Everything in @Xiol setup looks good to me. There were a few similar bugs back during the 1.24-1.26 releases and I was trying to validate those first. This seems to be new but I'm still trying to narrow down where the actual issue is. It seems to be around the new auth policy and permissions.

We know that if you turn the default auth policy it works but that's not really a solution.

Can you try this, keep the default auth policy on

```yaml
backend:
  auth:
    dangerouslyDisableDefaultAuthPolicy: false
```

But then disable just permissions:

```yaml
permission:
  enabled: false
```

Does it work?

**Comment by Jenson3210** [comment]
I was able to get it working on my side. 
My issue turned out to be related to the `backstage-auth` cookie not being created in remote environment but it could be created in local. 
I have LDAP-auth which uses backstage-token by default (which also gets stored in cookies)

- In local connection browser -> no cookies present -> both `backstage-auth` and `backstage-token` cookies are set correctly. Catalog call sets no weird cookie
- In remote connection browser -> a lot of company cookies present for domain -> no backstage-auth cookie but seeing some weird cookie set by catalog call (d3xxxxxxc5fbff78xxxxxxabfxxxxxx8=b5736b19xxxxxxcxxxxxx80xxxxxx9a6; => masked as I do not know the importance)
- In remote connection incognito browser -> no company cookies present yet -> [`backstage-token`](https://github.com/search?q=repo%3Aimmobiliare%2Fbackstage-plugin-ldap-auth%20COOKIE_FIELD_KEY&type=code) present. Catalog call also sets a weird cookie. 

My solution for now is to ask LDAP-auth plugin to create a cookie called `backstage-auth` instead of `backstage-token`

**Comment by Rugvip** [comment]
@Xiol what does this request in your screenshot look like, does it successfully set a cookie for the correct host and path?

<img width="121" alt="image" src="https://github.com/user-attachments/assets/688e3ed8-ef92-4f6c-b6a7-119afc699398">

That's the request that sets the `backstage-auth` cookie to be used in followup requests for static resources by TechDocs. It's possible that the cookie doesn't get set correctly if you have an incorrect configuration of `backend.baseUrl` in your backend instance, which should be set to the externally reachable URL of your Backstage instance, here `https://host.tld`.

**Comment by Xiol** [comment]
Ahhh, I've fixed it!

@Rugvip, you pointed me in the right direction there.

My issue was I'd set the `baseUrl` value(s) to the Azure App Service-provided value of `$WEBSITE_HOSTNAME`, which will contain the full `*.azurewebsites.net` URL. However, I was accessing it via a custom domain CNAME'd onto that URL.

Setting `baseURL` to the custom domain value now allows TechDocs to load correctly.

I can now see that while there is still no `Authorization` header in the request for the TechDocs static content, a new cookie value is present `backstage-auth`, which appears to have been the problem for me.

Thank you, everyone.

**Comment by Jenson3210** [comment]
@Rugvip , what would explain why locally I can have two cookies and on remote solution only 1? 
I do not see the cookie http call on remote where I do see it on local (explaining the 2 cookies)

**Comment by Rugvip** [comment]
@Jenson3210 my guess would be that you've got a mix of package versions that may be working differently in different environments. I'd try to upgrade to the latest version.

**Comment by rschm007** [comment]
> I was able to get it working on my side. My issue turned out to be related to the `backstage-auth` cookie not being created in remote environment but it could be created in local. I have LDAP-auth which uses backstage-token by default (which also gets stored in cookies)
> 
> * In local connection browser -> no cookies present -> both `backstage-auth` and `backstage-token` cookies are set correctly. Catalog call sets no weird cookie
> * In remote connection browser -> a lot of company cookies present for domain -> no backstage-auth cookie but seeing some weird cookie set by catalog call (d3xxxxxxc5fbff78xxxxxxabfxxxxxx8=b5736b19xxxxxxcxxxxxx80xxxxxx9a6; => masked as I do not know the importance)
> * In remote connection incognito browser -> no company cookies present yet -> [`backstage-token`](https://github.com/search?q=repo%3Aimmobiliare%2Fbackstage-plugin-ldap-auth%20COOKIE_FIELD_KEY&type=code) present. Catalog call also sets a weird cookie.
> 
> My solution for now is to ask LDAP-auth plugin to create a cookie called `backstage-auth` instead of `backstage-token`

I am seeing this exact sequence of events as well. My local connection browser sets the `backstage-auth` cookie but my remote connection browser does not set that cookie.

We had to write a custom authentication module after migrating to the new backend system so I am wondering if this has to do with that.

**Comment by Jenson3210** [comment]
I will leave it up to @Rugvip or @awanlin as maintainers to see if this issue can be reopened or if we should open another. 

For me, I had 2 same tokens so i could just rename the working one. 

I suspect there is some optimization in some core package that finds a custom auth provider (I had imobilaris' ldap auth, @rschm007 has custom auth) and then does not do the cookie call in remote environment.

Unfortunately, I could not directly find the front end part that should use the get cookie call.

**Comment by rschm007** [comment]
I was able to get Techdocs working again on my end! It did end up being the missing backstage-auth cookie that was causing the issue. Here is how I resolved it:

I have a ProxiedSignInIdentity component that is responsible for managing the user's session by interacting with our custom authentication provider's refresh endpoint. In that component, I have a method, getSessionAsync, that checks if there is an active session or if a session fetch is in progress. If the session is active and hasn't expired, it returns the current session. Otherwise, it fetches a new session.

To fix the issue, I added a check for the backstage-auth cookie within the getSessionAsync method. If the cookie exists, we proceed as normal. If it doesn't exist, it sets the cookie using the token from the fetched session. The this.state.session is of type ProxiedSession and contains the Backstage identity token, which I use to set the cookie.

Here is the relevant part of the getSessionAsync method:

```
async getSessionAsync(): Promise<ProxiedSession> {
  if (this.state.type === "fetching") {
    return this.state.promise;
  } else if (this.state.type === "active" && new Date() < this.state.expiresAt) {
    return this.state.session;
  }

  const previous = this.state.type === "active" ? this.state.session : undefined;

  const promise = this.fetchSession().then(
    (session) => {
      this.state = {
        type: "active",
        session,
        expiresAt: tokenToExpiry(session.backstageIdentity.token),
      };

      // Set the backstage-auth cookie if it doesn't exist
      // WARNING: TechDocs will not work if "backstage-auth" cookie isn't set!
      if (!Cookies.get("backstage-auth")) {
        const date = new Date();
        date.setTime(date.getTime() + 1 * 24 * 60 * 60 * 1000); // Cookie expires in 1 day
        Cookies.set("backstage-auth", this.state.session.backstageIdentity.token, {
          path: "/",
          expires: date,
          domain: ${HOST_DOMAIN},
          secure: true,
          sameSite: "none",
        });
      }

      return session;
    },
    (error) => {
      this.state = {
        type: "failed",
        error,
      };
      throw error;
    },
  );

  this.state = {
    type: "fetching",
    promise,
    previous,
  };

  return promise;
}
```

Hopefully this helps folks to narrow down the issue if they're running into a similar problem.

**Comment by arian-press2015** [comment]
https://github.com/backstage/backstage/issues/26117#issuecomment-2370789881

**Comment by abhipsnl** [comment]
I'm still facing this issue, what was the real fix?

![Image](https://github.com/user-attachments/assets/e09380e3-d5fd-4056-925d-fc2803b7c1f9)

```
assets/stylesheets/main.0253249f.min.css 401
