### ISSUE TITLE
🚀 Feature: Add possibility to customize text of Software Template finalization button 

### ISSUE THREAD

**Issue by PedroAlmondo** [backstage/backstage#25605]
### 🔖 Feature description

It should be possible to change the text on the button in the final step of running Software Templates. 

The button I'm talking about: 
![image](https://github.com/user-attachments/assets/a803aa88-214a-4e39-a3de-1f40e967c1bd)

### 🎤 Context

Some of our Software Templates are not used exactly for 'creating' something, some of them are just 'run' and it would be good to have an option to change the text from 'Create', which can be misleading to something more generic, like f.e. 'Run'.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
I think that this is already a feature, but undocumented right now.

You should be able to pass something in the `template.yaml`.

```yaml
...
spec:
  presentation:
     buttonLabels:
       createButtonText: 'Run'
  parameters:
  ...
  steps:
  ...
```

**Comment by PedroAlmondo** [comment]
That solves our issue, I must have missed it somehow, thanks a lot!
