### ISSUE TITLE
Getting 401 unauthorized error after backstage application deployment to kubernetes environment

### ISSUE THREAD

**Issue by vinaykv23** [backstage/backstage#25620]
### 📜 Description

Created new project using "npx @backstage/create-app@latest"
project got created - done "yarn install" and "yarn dev"
backstage application started working using guest user in local system
same thing we deployed to kubernetes environment using docker image (same dockerfile is used what is generated default)
below auth setting changed for deployment environment "app-config.yaml"

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
      
once we access the application from deployment environment getting 401 Unauthorized error from all the apis
https://backstage-test/api/catalog/entity-facets?facet=relations.ownedBy 401 Unauthorized
https://backstage-test.torq.dev/api/catalog/entities?filter=kind%3Dapi 401 Unauthorized
https://backstage-test.torq.dev/api/catalog/entities/by-query?limit=1000&filter=metadata.name%3Dbackstage%2Cmetadata.name%3Dvalidation 401 Unauthorized

### 👍 Expected behavior

it should login as guest user

### 👎 Actual Behavior with Screenshots

once we access the application from deployment environment getting 401 Unauthorized error from all the apis
https://backstage-test/api/catalog/entity-facets?facet=relations.ownedBy 401 Unauthorized
https://backstage-test.torq.dev/api/catalog/entities?filter=kind%3Dapi 401 Unauthorized
https://backstage-test.torq.dev/api/catalog/entities/by-query?limit=1000&filter=metadata.name%3Dbackstage%2Cmetadata.name%3Dvalidation 401 Unauthorized

### 👟 Reproduction steps

Created new project using "npx @backstage/create-app@latest"
project got created - done "yarn install" and "yarn dev"
backstage application started working using guest user in local system
same thing we deployed to kubernetes environment using docker image (same dockerfile is used what is generated default)
below auth setting changed for deployment environment "app-config.yaml"

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
      
once we access the application from deployment environment getting 401 Unauthorized error from all the apis
https://backstage-test/api/catalog/entity-facets?facet=relations.ownedBy 401 Unauthorized
https://backstage-test.torq.dev/api/catalog/entities?filter=kind%3Dapi 401 Unauthorized
https://backstage-test.torq.dev/api/catalog/entities/by-query?limit=1000&filter=metadata.name%3Dbackstage%2Cmetadata.name%3Dvalidation 401 Unauthorized

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinaykv23** [comment]
Tried okta authentication, by following below documentation

https://backstage.io/docs/auth/okta/provider
https://backstage.io/docs/auth/#sign-in-configuration

**app-config.yaml**

auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    okta:
      development:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: ${AUTH_OKTA_DOMAIN}
        signIn:
          resolvers:
            # typically you would pick one of these
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailLocalPartMatchingUserEntityName
            - resolver: emailMatchingUserEntityAnnotation

**app.tsx**

components: {
    SignInPage: props => (
      <SignInPage
        {...props}
        providers={[
          'guest',
          {
            id: 'okta-auth-provider',
            title: 'Okta Preview',
            message: "Sign in using Okta",
            apiRef: oktaAuthApiRef,
          },
        ]}
      />
    ),
  },
});

**Comment by Rugvip** [comment]
The auth providers help you get a valid token for talking to those APIs, but you still need to include a token in those requests. If you simply want to disable API authentication altogether then you can use the following option: https://backstage.io/docs/tutorials/auth-service-migration#disabling-the-default-auth-policy

**Comment by vinaykv23** [comment]
Hi 
we tried this change, still resulting in same error. This is happening in kubernetes environment after deployment
in local system its working

backend:
  auth:
    dangerouslyDisableDefaultAuthPolicy: true
    
  
![image](https://github.com/user-attachments/assets/a679842d-719f-4f91-bda9-6cfb945c00c6)

**Comment by benjdlambert** [comment]
Is there an `Authorization` header being passed in those requests that are returning a 401?

Do you have permissions enabled?

**Comment by vinaykv23** [comment]
> Is there an `Authorization` header being passed in those requests that are returning a 401?
> 
> Do you have permissions enabled?

yes there is Authorization header passed

permissions is not enabled

![image](https://github.com/user-attachments/assets/e477cf45-ac4c-4f58-9d1a-b767ef1cea0c)

**Comment by vinaykv23** [comment]
Enabled permission using below 
https://github.com/backstage/backstage/issues/24942
still facing same issue

**Comment by nick-gray-bah** [comment]
I'm experiencing a similar issue when authenticating using Github. Guest user has no 401's but once authenticating we're getting 401 with a strange error 


`"error": {
        "name": "ResponseError",
        "message": "Request failed with 401 Unauthorized",
        "response": {
            "size": 0,
            "timeout": 0
        },
        "body": {
            "error": {
                "name": "AuthenticationError",
                "message": "Invalid token; caused by JWSSignatureVerificationFailed: signature verification failed",
                "cause": {
                    "code": "ERR_JWS_SIGNATURE_VERIFICATION_FAILED",
                    "name": "JWSSignatureVerificationFailed",
                    "message": "signature verification failed",
                    "stack": "JWSSignatureVerificationFailed: signature verification failed\n    at flattenedVerify (/app/node_modules/jose/dist/node/cjs/jws/flattened/verify.js:89:15)\n    at compactVerify (/app/node_modules/jose/dist/node/cjs/jws/compact/verify.js:18:22)\n    at Object.jwtVerify (/app/node_modules/jose/dist/node/cjs/jwt/verify.js:8:22)\n    at UserTokenHandler.verifyToken (/app/node_modules/@backstage/backend-defaults/src/entrypoints/auth/user/UserTokenHandler.ts:55:25)\n    at DefaultAuthService.authenticate (/app/node_modules/@backstage/backend-defaults/src/entrypoints/auth/DefaultAuthService.ts:61:28)\n    at DefaultHttpAuthService.#extractCredentialsFromRequest (/app/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:95:12)\n    at DefaultHttpAuthService.credentials (/app/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:138:9)\n    at /app/node_modules/@backstage/plugin-permission-backend/src/service/router.ts:225:27"
                },
                "stack": "AuthenticationError: Invalid token; caused by JWSSignatureVerificationFailed: signature verification failed\n    at /app/node_modules/@backstage/backend-defaults/src/entrypoints/auth/user/UserTokenHandler.ts:60:13\n    at UserTokenHandler.verifyToken (/app/node_modules/@backstage/backend-defaults/src/entrypoints/auth/user/UserTokenHandler.ts:55:25)\n    at DefaultAuthService.authenticate (/app/node_modules/@backstage/backend-defaults/src/entrypoints/auth/DefaultAuthService.ts:61:28)\n    at DefaultHttpAuthService.#extractCredentialsFromRequest (/app/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:95:12)\n    at DefaultHttpAuthService.credentials (/app/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:138:9)\n    at /app/node_modules/@backstage/plugin-permission-backend/src/service/router.ts:225:27"
            },
            "request": {
                "method": "POST",
                "url": "/authorize"
            },
            "response": {
                "statusCode": 401
            }
        },
        "cause": {
            "cause": {
                "code": "ERR_JWS_SIGNATURE_VERIFICATION_FAILED",
                "name": "JWSSignatureVerificationFailed",
                "message": "signature verification failed",
                "stack": "JWSSignatureVerificationFailed: signature verification failed\n    at flattenedVerify (/app/node_modules/jose/dist/node/cjs/jws/flattened/verify.js:89:15)\n    at compactVerify (/app/node_modules/jose/dist/node/cjs/jws/compact/verify.js:18:22)\n    at Object.jwtVerify (/app/node_modules/jose/dist/node/cjs/jwt/verify.js:8:22)\n    at UserTokenHandler.verifyToken (/app/node_modules/@backstage/backend-defaults/src/entrypoints/auth/user/UserTokenHandler.ts:55:25)\n    at DefaultAuthService.authenticate (/app/node_modules/@backstage/backend-defaults/src/entrypoints/auth/DefaultAuthService.ts:61:28)\n    at DefaultHttpAuthService.#extractCredentialsFromRequest (/app/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:95:12)\n    at DefaultHttpAuthService.credentials (/app/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:138:9)\n    at /app/node_modules/@backstage/plugin-permission-backend/src/service/router.ts:225:27"
            },
            "name": "AuthenticationError",
            "message": "Invalid token; caused by JWSSignatureVerificationFailed: signature verification failed",
            "stack": "AuthenticationError: Invalid token; caused by JWSSignatureVerificationFailed: signature verification failed\n    at /app/node_modules/@backstage/backend-defaults/src/entrypoints/auth/user/UserTokenHandler.ts:60:13\n    at UserTokenHandler.verifyToken (/app/node_modules/@backstage/backend-defaults/src/entrypoints/auth/user/UserTokenHandler.ts:55:25)\n    at DefaultAuthService.authenticate (/app/node_modules/@backstage/backend-defaults/src/entrypoints/auth/DefaultAuthService.ts:61:28)\n    at DefaultHttpAuthService.#extractCredentialsFromRequest (/app/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:95:12)\n    at DefaultHttpAuthService.credentials (/app/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:138:9)\n    at /app/node_modules/@backstage/plugin-permission-backend/src/service/router.ts:225:27"
        },
        "statusCode": 401,
        "statusText": "Unauthorized",
        "stack": "ResponseError: Request failed with 401 Unauthorized\n    at Function.fromResponse (/app/node_modules/@backstage/errors/src/errors/ResponseError.ts:76:12)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at PermissionClient.makeRequest (/app/node_modules/@backstage/backend-defaults/node_modules/@backstage/plugin-permission-common/src/PermissionClient.ts:160:13)\n    at AuthorizedEntitiesCatalog.entities (/app/node_modules/@backstage/plugin-catalog-backend/src/service/AuthorizedEntitiesCatalog.ts:55:7)\n    at /app/node_modules/@backstage/plugin-catalog-backend/src/service/createRouter.ts:135:40"
    },
    "request": {
        "method": "GET",
        "url": "/entities?filter=kind%3Dapi"
    },
    "response": {
        "statusCode": 401
    }
}`

**Comment by benjdlambert** [comment]
@nick-gray-bah what version of backstage are you on? I think that this is unrelated to this, but I seem to remember that this was caused by some incompatibilities use `legacyPlugin` or something to that effect. I wonder if it's the same thing that's been fixed already.

**Comment by nick-gray-bah** [comment]
Can you send a link to the issue/ pr that fixed this?

**Comment by vinaykv23** [comment]
> We're runnin

hi @benjdlambert we are using backstage version "version": "1.28.0"
Can you please let us know what will be the solution

**Comment by benjdlambert** [comment]
@vinaykv23 if you run the docker container locally does it still throw 401 after you have logged in?

@nick-gray-bah I could be getting confused with some other work as I can't seem to find it, one thing that's interesting though is that @aramissennyeydd @sennyeya (whichever you're logged in as 😅 ) seemed to run into the exact error message here https://github.com/backstage/backstage/pull/22564

Do you know what caused that and what the fix was :pray:

**Comment by vinaykv23** [comment]
hi @benjdlambert  I don't have provision to run docker container locally
I am deploying to K8 environment and doing validation

**Comment by aramissennyeydd** [comment]
@benjdlambert It ended up being an issue with the old backend permission setup not propagating the actual JWT error it was getting. This may be different since we switched to the newer auth system?

**Comment by Devil6sidekick** [comment]
@vinaykv23 Hello. I am having the same issue, were you able to solve it?

**Comment by vinaykv23** [comment]
> , were you able to solve it?

no issue is still open

**Comment by vinaykv23** [comment]
> Enabled permission using below #24942 still facing same issue

hi @benjdlambert 
error in "IdentityAuthInjectorFetchMiddleware"

![image](https://github.com/user-attachments/assets/71f9f535-b20d-4233-a9b5-92c2dc66cc55)

**Comment by benjdlambert** [comment]
@vinaykv23 yep that's just where the 401 error is thrown from, that's expected.

Is it not possible for you to start the container locally by just running `docker run`? 

Otherwise, can you create an reproduction repo so we can dig in a bit further by using `npx @backstage/create-app`?

**Comment by vinaykv23** [comment]
> @vinaykv23 yep that's just where the 401 error is thrown from, that's expected.
> 
> Is it not possible for you to start the container locally by just running `docker run`?
> 
> Otherwise, can you create an reproduction repo so we can dig in a bit further by using `npx @backstage/create-app`?

Hi @benjdlambert  I have created sample repo same is used to deploy  
https://github.com/vinaykv23/Backstage

**Comment by benjdlambert** [comment]
Hmm with that config it looks like all the default auth policies are turned off in production too, so i'm not sure if it's Backstage which is throwing the 401. Do you have some form of ingress / proxy in front of the Backstage deployment, either from k8s or something which sits in front of the k8s Deployment which could be interfering here?

**Comment by benjdlambert** [comment]
@vinaykv23 hmm my gut feeling is that it could be the kong ingress that's either injecting / mutating / stripping Authorization headers which is causing this 401, or it's throwing the 401. 

Is there an alternative ingress you could try? Maybe something like nginx or something instead?

**Comment by vinaykv23** [comment]
> @vinaykv23 hmm my gut feeling is that it could be the kong ingress that's either injecting / mutating / stripping Authorization headers which is causing this 401, or it's throwing the 401.
> 
> Is there an alternative ingress you could try? Maybe something like nginx or something instead?

hi @benjdlambert 
let me check but same deployment working for older backstage "version": "1.23.4"

**Comment by benjdlambert** [comment]
yeah, which I think leads me to believe that the ingress is adding an Authorization header or something which is now being validated in the new Backstage release and that header isn't a valid Backstage token or something which causes this error.

**Comment by vinaykv23** [comment]
> yeah, which I think leads me to believe that the ingress is adding an Authorization header or something which is now being validated in the new Backstage release and that header isn't a valid Backstage token or something which causes this error.

hi @benjdlambert 
after reducing the pod replicas from 2 to 1 it started working
can you please explain how it matters

**Comment by benjdlambert** [comment]
@vinaykv23 are you deploying with PostgreSQL or Sqlite? You'll wanna make sure you used a shared DB if you're deploying multiple replicas.

**Comment by KL2808** [comment]
Hey there same issue from my site. I migrated to the new backend. After migrating i got 401 and i tried everything to resolve it... after changing to 1 pod only on kubernetes it started working wtf... maybe the auth is now limited to be only used on the pod which issued the token?

I also have psql enabled and somehow all my templates got unregistred

**Comment by KL2808** [comment]
@vinaykv23 could we reopen this thread? or have you found the solution :)
