### ISSUE TITLE
🚀 Feature: NotificationTemplateRenderer should support async methods

### ISSUE THREAD

**Issue by kmikko** [backstage/backstage#25630]
### 🔖 Feature description

`NotificationTemplateRenderer` should support asynchronous methods, at least `getHtml` but maybe even all of them. [](url)

### 🎤 Context

We're experimenting with email notifications and ran into problems with our current way of constructing emails with the help of nunjucks and mjml that require asynchronous processing. We would like to do some async processing inside `getHtml` in order to generate the email which currently seems to be impossible.  In other words our current implementation of email notifications module looks something like this
```ts
export const notificationsModuleEmailTemplates = createBackendModule({
  pluginId: 'notifications',
  moduleId: 'email-templates',
  register(reg) {
    reg.registerInit({
      deps: {
        emailNotifications: notificationsEmailTemplateExtensionPoint,
        emailTemplating: emailTemplateServiceRef,
      },
      async init({ emailNotifications, emailTemplating }) {
        emailNotifications.setTemplateRenderer({
          ...,
          
          // Currently not possible
          async getHtml(notification) {
            const html = await emailTemplating.createNotification({
              ...
            });

            return html;
          },
        });
      },
    });
  },
});
```

### ✌️ Possible Implementation

Monkey patching `NotificationTemplateRenderer` interface and adding await [here]( https://github.com/backstage/backstage/blob/c7b5e8792f1bc653755588311cc5544189602895/plugins/notifications-backend-module-email/src/processor/NotificationsEmailProcessor.ts#L285) seemed to do the trick but I'm not very familiar with the notifications functionality so there might be something that I overlooked.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@kmikko this seems like a sane idea, do you want to open up a PR adjusting some of the types in a non-breaking way if possible? :pray:

**Comment by kmikko** [comment]
@benjdlambert Sure, I'll have a better look at this next week and see if there's a way to make this backwards compatible.
