### ISSUE TITLE
🐛 Bug Report: Duplicated Entities Returned By Catalog API /entities/by-query

### ISSUE THREAD

**Issue by zthfmh** [backstage/backstage#25632]
### 📜 Description

Hi, our team recently discovered that on the Catalog page the `All <entity kind> (<count>)` table header has a different count number from the `All` counts in the user list picker on the side filter panel. For example:

<img width="239" alt="Screenshot 2024-07-15 at 1 19 48 PM" src="https://github.com/user-attachments/assets/25d90a06-4810-46bb-b65f-a37efa11ce5c">

<img width="248" alt="Screenshot 2024-07-15 at 1 19 44 PM" src="https://github.com/user-attachments/assets/59cd7aee-8527-463a-8cb8-cd4cf315e5c9">

After some digging we realized that the component `UserListPicker` uses `useAllEntitiesCount` to retrieve the counts, which further relies on the Catalog API `GET /entities/by-query`. If no other filters are selected, the following criteria is used for the API:

`
{
    "filter": {
        "kind": "group"
    },
    "limit": 0
}
`

A manual API call reveals that this endpoint returns duplicated catalog entities with the same `metadata.uid` field, whereas the deprecated API `GET /entities` does not have the same issue. Looking at the implementation of the by-query endpoint, it seems to be using the table `backstage_plugin_catalog.search` to perform search by selecting rows that match the given criteria. In our case the table has duplicated rows which is what assumed to be causing the issue (on the other hand the `backstage_plugin_catalog.final_entities table` only has unique entities).

We have attempted to clean up all the duplicated rows in `backstage_plugin_catalog.search`, which temporarily fixed the issue until the next entity ingestion cycle ran and those duplicated rows came right back. In our case we have implemented a custom Catalog provider that ingests all Okta groups and users in the organization, using the `IncrementalEntityProvider` class provided by the plugin https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-incremental-ingestion. 

My questions are:

1. Our custom incremental entity provider has a fairly straightforward implementation where it just reaches out to Okta and creates the corresponding entity definition. There is no special manipulation to the lower level DB tables at all. What would be some possible cause that duplicated entries are created in the search table?
2. Should the Catalog API `GET /entities/by-query` not always assume that all rows in the table `backstage_plugin_catalog.search` are unique and will check for duplicates?

### 👍 Expected behavior

The Catalog API `GET /entities/by-query` should not return duplicated entity results

### 👎 Actual Behavior with Screenshots

When querying the Catalog API `GET /entities/by-query`, duplicated results are returned if table `backstage_plugin_catalog.search` contains duplicated rows

### 👟 Reproduction steps

1. Duplicate an existing row in `backstage_plugin_catalog.search`. E.g. `entity_id=<...> key=kind value=group original_value=Group`
2. Query the Catalog API `GET /entities/by-query`:
`
await fetch(
 '/api/catalog/entities/by-query?' + new URLSearchParams({
  filter: 'kind=Group', limit: 10000}), 
  { 
     method: 'GET',
     headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer <token>' }
  }).then((response) => response.json())
`
3. There will be one duplicated result matching the row that's duplicated in 1

### 🖥️ Your Environment

OS:   Darwin 23.5.0 - darwin/arm64
node: v20.11.0
yarn: 1.22.21
cli:  0.26.2 (installed)
backstage:  1.25.2

Dependencies:
  @backstage/app-defaults                                          1.5.3
  @backstage/backend-app-api                                       0.5.14, 0.6.2, 0.7.2, 0.7.5
  @backstage/backend-common                                        0.19.10, 0.20.2, 0.21.7, 0.22.0, 0.23.1
  @backstage/backend-defaults                                      0.2.16
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11, 0.1.9
  @backstage/backend-plugin-api                                    0.5.4, 0.6.17, 0.6.18, 0.6.20
  @backstage/backend-tasks                                         0.5.22, 0.5.23
  @backstage/backend-test-utils                                    0.3.6
  @backstage/catalog-client                                        1.6.4, 1.6.5
  @backstage/catalog-model                                         1.4.5, 1.5.0
  @backstage/cli-common                                            0.1.13, 0.1.14
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.2
  @backstage/config-loader                                         1.8.0, 1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.3
  @backstage/core-components                                       0.12.5, 0.13.10, 0.14.6, 0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.30
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.4, 0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26, 1.1.27
  @backstage/integration                                           1.10.0, 1.11.0, 1.12.0
  @backstage/plugin-adr-backend                                    0.4.13
  @backstage/plugin-adr-common                                     0.2.21
  @backstage/plugin-adr                                            0.6.16
  @backstage/plugin-api-docs                                       0.11.3
  @backstage/plugin-app-backend                                    0.3.64
  @backstage/plugin-app-node                                       0.1.16
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.8
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.8
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.11
  @backstage/plugin-auth-backend-module-github-provider            0.1.13
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.13
  @backstage/plugin-auth-backend-module-google-provider            0.1.13
  @backstage/plugin-auth-backend-module-guest-provider             0.1.2
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.11
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.13
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.9
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.7
  @backstage/plugin-auth-backend-module-okta-provider              0.0.9
  @backstage/plugin-auth-backend                                   0.22.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.12, 0.4.13, 0.4.15
  @backstage/plugin-auth-react                                     0.0.3
  @backstage/plugin-catalog-backend-module-aws                     0.3.11
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.14
  @backstage/plugin-catalog-backend-module-incremental-ingestion   0.4.23
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.14, 0.1.16
  @backstage/plugin-catalog-backend-module-unprocessed             0.4.3
  @backstage/plugin-catalog-backend                                1.21.0, 1.22.0
  @backstage/plugin-catalog-common                                 1.0.22, 1.0.23, 1.0.24
  @backstage/plugin-catalog-graph                                  0.4.3
  @backstage/plugin-catalog-import                                 0.10.9
  @backstage/plugin-catalog-node                                   1.11.1, 1.12.0, 1.12.2
  @backstage/plugin-catalog-react                                  1.11.3, 1.12.0
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.1
  @backstage/plugin-catalog-unprocessed-entities                   0.2.2
  @backstage/plugin-catalog                                        1.18.2
  @backstage/plugin-devtools-backend                               0.3.2
  @backstage/plugin-devtools-common                                0.1.9
  @backstage/plugin-devtools                                       0.1.12
  @backstage/plugin-events-node                                    0.2.21, 0.3.2, 0.3.4
  @backstage/plugin-github-actions                                 0.6.14
  @backstage/plugin-home-react                                     0.1.11
  @backstage/plugin-home                                           0.7.2
  @backstage/plugin-kubernetes-backend                             0.17.0
  @backstage/plugin-kubernetes-common                              0.7.5
  @backstage/plugin-kubernetes-node                                0.1.11
  @backstage/plugin-kubernetes-react                               0.3.4
  @backstage/plugin-kubernetes                                     0.11.9
  @backstage/plugin-org                                            0.6.23
  @backstage/plugin-permission-backend                             0.5.40
  @backstage/plugin-permission-common                              0.7.13, 0.7.14
  @backstage/plugin-permission-node                                0.7.28, 0.7.29, 0.7.31
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.14
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10, 0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.6, 0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.6, 0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.6, 0.2.8
  @backstage/plugin-scaffolder-backend-module-cookiecutter         0.2.40
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10, 0.1.8
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.6, 0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.6, 0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.2, 0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.3, 1.22.7
  @backstage/plugin-scaffolder-common                              1.5.2, 1.5.1
  @backstage/plugin-scaffolder-node                                0.1.5, 0.4.2, 0.4.4
  @backstage/plugin-scaffolder-react                               1.8.3
  @backstage/plugin-scaffolder                                     1.19.2
  @backstage/plugin-search-backend-module-catalog                  0.1.21, 0.1.24
  @backstage/plugin-search-backend-module-elasticsearch            1.3.19
  @backstage/plugin-search-backend-module-pg                       0.5.25
  @backstage/plugin-search-backend-module-techdocs                 0.1.21
  @backstage/plugin-search-backend-node                            1.2.21, 1.2.23
  @backstage/plugin-search-backend                                 1.5.6
  @backstage/plugin-search-common                                  1.2.11, 1.2.12
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.9
  @backstage/plugin-shortcuts                                      0.3.22
  @backstage/plugin-signals-node                                   0.0.1
  @backstage/plugin-signals-react                                  0.0.1
  @backstage/plugin-sonarqube-backend                              0.2.18
  @backstage/plugin-sonarqube-react                                0.1.14
  @backstage/plugin-sonarqube                                      0.7.15
  @backstage/plugin-tech-radar                                     0.7.2
  @backstage/plugin-techdocs-backend                               1.10.3
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.8
  @backstage/plugin-techdocs-node                                  1.12.2
  @backstage/plugin-techdocs-react                                 1.2.2
  @backstage/plugin-techdocs                                       1.10.3
  @backstage/plugin-user-settings                                  0.8.4
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.3
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.3, 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 2.43s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hmm, OK.

I think that the issue here is that theres duplicate entries in the search table, as that's what powers the counts.

Wondering if we can repurpose this issue a little bit to really focus on the cause of those duplicate entries, and where they come from. The `IncrementalEntityProvider` could be the culprit here, but could you provide some reproduction steps that focus on how to get duplicate search entries?
