### ISSUE TITLE
Make optional external routes the only option, forcing plugins to handle missing route bindings

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#25665]

**Comment by Rugvip** [comment]
Figured out a way to ship this:

1. Refactor `frontend-plugin-api` to always use option return from `useRouteRef`, for all types of route refs. i.e. every single type of route ref is treated as optional from now in.
2. Add support for using route refs defined by `frontend-plugin-api` in `core-plugin-api` directly
3. Deprecate `useRouteRef` and friends in `core-plugin-api`, point to `frontend-plugin-api` instead

**Comment by Rugvip** [comment]
Closing this since the immediate task is done in #25918. The followup is intended to be a more general `core-plugin-api` -> `frontend-plugin-api` migration.
