### ISSUE TITLE
🚀 Feature: BackStage's Template usage metrics

### ISSUE THREAD

**Issue by toasahi** [backstage/backstage#25687]
### 🔖 Feature description

We would like to visualize metrics in Grafana for the number of template executions in Backstage.
We have now added the OpenTelemetry configuration to BackStage, using the following URL as a reference.
https://backstage.io/docs/tutorials/setup-opentelemetry/

**We were able to output the built-in metrics here.**
![スクリーンショット 2024-07-18 20 58 25](https://github.com/user-attachments/assets/bd182a63-5442-4db8-b534-51ad7c4b7c21)

However, the metrics I want were not present.
I want metrics for the number of Template executions. I would like to be able to output the metrics here.

**Specifically, we would like to get metrics on success and failure of Template execution in Tasks in the image below.**
![スクリーンショット 2024-07-18 20 55 24](https://github.com/user-attachments/assets/2161d671-a58e-46f0-9d09-12aa5cc27f12)

I am currently trying to create my own custom metrics but am unable to reflect them in /metrics.
I would like to know if there is a helpful way to do this.
Here is my code.
```ts
import { NodeSDK } from '@opentelemetry/sdk-node';
import { PrometheusExporter } from '@opentelemetry/exporter-prometheus';
import { metrics } from '@opentelemetry/api';

const meter = metrics.getMeter('default');
meter.createCounter('template_usage_count', {
  description: 'Count the number of times Template is executed',
});

// By default exports the metrics on localhost:9464/metrics
const prometheus = new PrometheusExporter();
const sdk = new NodeSDK({
  // You can add a traceExporter field here too
  metricReader: prometheus,
  instrumentations: [],
});

sdk.start();
```

### 🎤 Context

I am now an egg of a platform engineer.
BackStage has always been a great help to me, Template has become richer and I would like to measure the effectiveness of how much BackStage is being used by the development team. One approach I wanted to take was to get metrics on the number of times Template is executed. We would love to see this added as a new feature.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
@toasahi there are some metrics already built in for the scaffolder. I think that you will want to make sure that you only have one installation of the `@opentelemetry/*` packages, so it might be worth using `yarn why @opentelemetry/sdk-node` etc for each package that you installed to make sure that there's only one version of them and they're not duplicated.

**Comment by toasahi** [comment]
Thank you @benjdlambert 

Custom metrics could be created by using the “@opentelemetry/*” package. The following code is an example implementation.

Why is there no standard Template usage metric (Counter)?

Since there are no Template usage metrics, I would like to set up metrics based on the information in the “tasks” table in the BackStage database.
```
import { metrics } from '@opentelemetry/api';
import {
  MeterProvider,
  PeriodicExportingMetricReader,
} from '@opentelemetry/sdk-metrics';
import { OTLPMetricExporter } from '@opentelemetry/exporter-metrics-otlp-grpc';
import { Resource } from '@opentelemetry/resources';
import {
  SEMRESATTRS_SERVICE_NAME,
  SEMRESATTRS_SERVICE_VERSION,
} from '@opentelemetry/semantic-conventions';

const meterProvider = new MeterProvider({
  resource: new Resource({
    [SEMRESATTRS_SERVICE_NAME]: 'backstage',
    [SEMRESATTRS_SERVICE_VERSION]: '1.0',
  }),
  readers: [
    new PeriodicExportingMetricReader({
      exporter: new OTLPMetricExporter(),
      exportIntervalMillis: 1000,
    }),
  ],
});

const meter = meterProvider.getMeter('backstage', '0.0.1');

const manager = DatabaseManager.fromConfig(
    new ConfigReader({
      backend: {
        database: {
          client: 'pg',
          connection: {
            host: ${POSTGRES_HOST},
            port: ${POSTGRES_PORT},
            user: ${POSTGRES_USER},
            password: ${POSTGRES_PASSWORD},
          },
        },
      },
    }),
  ).forPlugin('scaffolder');
  const databaseTaskStore = await DatabaseTaskStore.create({
    database: manager,
  });
  const { tasks } = await databaseTaskStore.list({});

  export const templateUsageCount = meter.createCounter('template_usage', {
    description: 'Count the number of times Template is executed',
  });

  // Bad Code:
  templateUsageCount.add(tasks.length, {
      template: "debug-template"
  });
```
The above code is problematic and will be modified in the future.

**Comment by benjdlambert** [comment]
@toasahi but there is a counter for task runs already? https://github.com/backstage/backstage/blob/b29b39302ca0df2bb4cd97753f60f52e6470d747/plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts#L523-L527

This is why I asked if you have duplicates of some of the packages here causing the auto collection not to work properly.

**Comment by JonasMH** [comment]
I'm seeing the same issue where the `scaffolder_*` metrics are not seen in the output.

According to `yarn why @opentelemetry/sdk-node` I only have one version installed:

```
├─ @opentelemetry/auto-instrumentations-node@npm:0.47.1
│  └─ @opentelemetry/sdk-node@npm:0.52.1 (via npm:^0.52.0)
│
├─ @opentelemetry/auto-instrumentations-node@npm:0.47.1 [aa597]
│  └─ @opentelemetry/sdk-node@npm:0.52.1 [aa597] (via npm:^0.52.0 [aa597])
│
└─ backend@workspace:packages/backend
   └─ @opentelemetry/sdk-node@npm:0.52.1 [aa597] (via npm:^0.52.0 [aa597])
```

But according to https://github.com/backstage/backstage/issues/22555#issuecomment-1923354028 this may be due to the scaffolder metrics implementation still using the `prom-cliemt` for metrics - a quick look into the source code seems to suggest this is still the case.

**Comment by benjdlambert** [comment]
Ah, that would do it, that's unfortunate. We want to remove `prom-client` really in favour of `otel`.

Would you be willing to contribute a PR using the `otel` metrics, but keeping the same `prom-client` metrics right now just for backwards compatibility for the time being? Similar to how the `catalog-backend` plugin does it?

https://github.com/backstage/backstage/blob/278b1bd1ec48c722c398d7d8d828a221044dcaf4/plugins/catalog-backend/src/database/metrics.ts

**Comment by JonasMH** [comment]
Yes: https://github.com/backstage/backstage/pull/26020 :-)

**Comment by benjdlambert** [comment]
Thanks @JonasMH for the contributions! Closing this as fixed! :tada:
