### ISSUE TITLE
🚀 Feature: [NBS] Add support for custom location processing in the Bitbucket Server integration

### ISSUE THREAD

**Issue by Maetis** [backstage/backstage#25696]
### 🔖 Feature description

This feature was suggested by @awanlin ([#25535](https://github.com/backstage/backstage/pull/25535#discussion_r1676823562)).

The Bitbucket Server integration allowed user to write custom location processing with the previous backend system.

Does this feature need to be supported with the new backend system?

### 🎤 Context

Migration of the plugin to the new backend system.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by flash-me** [comment]
@Maetis [Which Bitbucker Server Integration?](https://discord.com/channels/687207715902193673/1263834001236426833) :D

**Comment by freben** [comment]
@Maetis Did you get this sorted out, given that you made that docs PR?

**Comment by awanlin** [comment]
Hi @freben, we removed that section from the docs and so I recommended that we at least log an issue for it.

For references this is the part we removed:

## Custom location processing

The Bitbucket Server Entity Provider will by default emit a location for each
matching repository. However, it is possible to override this functionality and take full control of how each
matching repository is processed.

`BitbucketServerEntityProvider.fromConfig` takes an optional parameter
`options.parser` where you can set your own parser to be used for each matched
repository.

```typescript
const provider = BitbucketServerEntityProvider.fromConfig(env.config, {
  logger: env.logger,
  schedule: env.scheduler,
  parser: async function* customLocationParser(options: {
    location: LocationSpec;
    client: BitbucketServerClient;
  }) {
    // Custom logic for interpreting the matching repository
    // See defaultBitbucketServerLocationParser for an example
  },
});
```

**Comment by awanlin** [comment]
Hi @flash-me, what do you suggest we do to make this more clear?

**Comment by flash-me** [comment]
uuuh @awanlin to be fair, we're only looked at the auth part of the bitbucketServer, which was missing and I am planning to contribute. Somehow mixed this up. We are happy with the default Integration.

Sorry for taking your time here

**Comment by Rugvip** [comment]
Where has this ended up, is it alright to close? 😅
