### ISSUE TITLE
🐛 Bug Report: Documentation error in Getting-Started causes compilation error in local

### ISSUE THREAD

**Issue by rghara** [backstage/backstage#25694]
### 📜 Description

In the documentation page https://backstage.io/docs/getting-started/config/authentication/

under section: 
Add sign-in option to the frontend

Duplicate import for SignInPage causes compilation error in local

packages/app/src/App.tsx
import { githubAuthApiRef } from '@backstage/core-plugin-api';
<-- Below import is a duplicate and causes compilation errors -->
import { SignInPage } from '@backstage/core-components';

### 👍 Expected behavior

Code should compile correctly after following the instructions in the documentation

### 👎 Actual Behavior with Screenshots

Compilation error in local:
![duplicateImportError](https://github.com/user-attachments/assets/25d75c8a-0a7c-4c12-a387-ec7dcd482fc5)

### 👟 Reproduction steps

1. In the page https://backstage.io/docs/getting-started/config/authentication/ follow the instructions
2. start the app with "yarn dev"

### 📃 Provide the context for the Bug.

Following the documentation getting-started should run flawlessly to save time

### 🖥️ Your Environment

Running backstage in the local on WSL2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@rghara do you want to raise a PR with some suggested changes for new users that could be helpful? :pray:

**Comment by rghara** [comment]
@benjdlambert sure, I'll look into it.
