### ISSUE TITLE
🐛 Bug Report: in documentation getting-started/logging-in there is a reference to a screenshot that is missing

### ISSUE THREAD

**Issue by rghara** [backstage/backstage#25690]
### 📜 Description

https://backstage.io/docs/getting-started/logging-in there is a reference to an image of the login screen but the image is missing.

"1. Login to Backstage
Run your Backstage app with yarn dev. Navigate to http://localhost:3000.

If you're not already logged in, you should see a login screen like this,"

<-- login screen image is missing here -->

### 👍 Expected behavior

It should show the login screen:

![expected](https://github.com/user-attachments/assets/21d9f0bd-3270-47c2-a32b-c683d61732f7)

### 👎 Actual Behavior with Screenshots

It actually misses the login screen image

![actual](https://github.com/user-attachments/assets/8fc69a3e-b349-4052-9524-4870c17405d6)

### 👟 Reproduction steps

1. Go to https://backstage.io/docs/getting-started/logging-in
2. Scroll down to the section 1. Login to Backstage
3. Observe under "If you're not already logged in, you should see a login screen like this,"
<-- login screen image is missing here -->"

### 📃 Provide the context for the Bug.

1. In source code under docs/assets/getting-started add an image of the login screen as example "login-page.png"
2. Add image to the file docs/getting-started/logging-in.md as example 
"If you're not already logged in, you should see a login screen like this,

![Screenshot of the the login screen](../assets/getting-started/login-page.png)"

### 🖥️ Your Environment

Documentation on the web and in the local deployment 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@rghara oh no! Yep looks like it's a bad path, would you help updating the docs here? :pray:

**Comment by rghara** [comment]
@benjdlambert Hi Ben, I did raise a pull request: https://github.com/backstage/backstage/pull/25702

**Comment by freben** [comment]
Fixed!
