### ISSUE TITLE
Remove unmaintained `dora-metrics` plugin

### ISSUE THREAD

**Issue by dragonfleas** [backstage/backstage#25715]
## 📜 Description

The "DORA Metrics" plugin by [OkayHQ](https://www.okayhq.com/) is no longer maintained, and their platform is no longer offered as they were acquired by stripe over a year ago with no updates or new.

## Preface
Feel free to change the label/organization on this, as this is _not_ a bug report, but sort of a meta-issue relating to the management of unmaintained/abandoned backstage community plugins. I'm going to be opening an RFC that links to this as an example relating to the latter.

#### From the `microsite/` path:
- [ ] Remove the `/data/plugins/dora-metrics.yaml` file
- [ ] Remove the `/static/img/okay.png` file

## Relevant links:
https://github.com/OkayHQ/backstage-plugin
https://www.okayhq.com/

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Souvik-Cyclic** [comment]
Can you assign this to me please ?

**Comment by benjdlambert** [comment]
Ah this is unfortunate, depending on the license it might be worth moving some of the code to the `@backstage/community-plugins` repository if there's enough of an appetite to carry on maintaining it in that repository with some new owners maybe? :pray:

**Comment by awanlin** [comment]
As the plugin itself looks to be a heavily tied to Okay platform which now seems to not be offered I'm not sure that this plugin will be able to carry on in any form 🤔

**Comment by benjdlambert** [comment]
@awanlin in that case, yep, let's drop it from the microsite?
