### ISSUE TITLE
🐛 Bug Report: Failed to sign-in, unable to resolve user identity

### ISSUE THREAD

**Issue by EttilTony** [backstage/backstage#25719]
### 📜 Description

I have followed the new backend migration guide to set up github auth for the newly created scaffolded backstage app. But I keep on getting this error when I try to authenticate using github.

### 👍 Expected behavior

Should allow to logon to the backstage homepage

### 👎 Actual Behavior with Screenshots

<img width="452" alt="Screenshot 2024-07-21 at 3 12 19 PM" src="https://github.com/user-attachments/assets/9189c4da-1a47-4dff-9b10-592cad4fd426">

### 👟 Reproduction steps

created backstage app using npx @backstage/create-app@latest
Then:
yarn --cwd packages/backend add @backstage/plugin-auth-backend-module-github-provider
backend.add(import('@backstage/plugin-auth-backend'));
backend.add(import('@backstage/plugin-auth-backend-module-github-provider'));
After that added these to the app.config.yaml file

auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        ## uncomment if using GitHub Enterprise
        # enterpriseInstanceUrl: ${AUTH_GITHUB_ENTERPRISE_INSTANCE_URL}
        signIn:
          resolvers:
            # Matches the GitHub username with the Backstage user entity name.
            # See https://backstage.io/docs/auth/github/provider#resolvers for more resolvers.
            - resolver: usernameMatchingUserEntityName

Finally added the UI component in the App.tsx file
components: {
  SignInPage: props => (
    <SignInPage
      {...props}
      auto
      provider={{
        id: 'github-auth-provider',
        title: 'GitHub',
        message: 'Sign in using GitHub',
        apiRef: githubAuthApiRef,
      }}
    />
  ),
},

### 🖥️ Your Environment

node: v20.11.0
yarn: 1.22.21
cli:  0.26.10 (installed)
backstage:  1.28.0

Dependencies:
  @backstage/app-defaults                                          1.5.7
  @backstage/backend-app-api                                       0.7.9
  @backstage/backend-common                                        0.23.2, 0.23.3
  @backstage/backend-defaults                                      0.3.3
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.14
  @backstage/backend-plugin-api                                    0.6.21, 0.7.0
  @backstage/backend-tasks                                         0.5.26
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.6
  @backstage/cli                                                   0.26.10
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.13.0
  @backstage/core-compat-api                                       0.2.6
  @backstage/core-components                                       0.14.8
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.6
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.28
  @backstage/integration                                           1.12.0, 1.13.0
  @backstage/plugin-api-docs                                       0.11.6
  @backstage/plugin-app-backend                                    0.3.70
  @backstage/plugin-app-node                                       0.1.21
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.2
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.13
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.4
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.4
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.16
  @backstage/plugin-auth-backend-module-github-provider            0.1.18, 0.1.19
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.18
  @backstage/plugin-auth-backend-module-google-provider            0.1.18
  @backstage/plugin-auth-backend-module-guest-provider             0.1.7
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.16
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.2
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.14
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.2
  @backstage/plugin-auth-backend-module-okta-provider              0.0.14
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.2
  @backstage/plugin-auth-backend                                   0.22.8
  @backstage/plugin-auth-node                                      0.4.16, 0.4.17
  @backstage/plugin-auth-react                                     0.1.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.19
  @backstage/plugin-catalog-backend                                1.23.2
  @backstage/plugin-catalog-common                                 1.0.24
  @backstage/plugin-catalog-graph                                  0.4.6
  @backstage/plugin-catalog-import                                 0.12.0
  @backstage/plugin-catalog-node                                   1.12.3
  @backstage/plugin-catalog-react                                  1.12.1
  @backstage/plugin-catalog                                        1.21.0
  @backstage/plugin-events-node                                    0.3.7
  @backstage/plugin-org                                            0.6.26
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.18
  @backstage/plugin-permission-backend                             0.5.45
  @backstage/plugin-permission-common                              0.7.14, 0.8.0
  @backstage/plugin-permission-node                                0.7.32
  @backstage/plugin-permission-react                               0.4.23
  @backstage/plugin-proxy-backend                                  0.5.2
  @backstage/plugin-scaffolder-backend-module-azure                0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.11
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.13
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.11
  @backstage/plugin-scaffolder-backend-module-github               0.3.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.3
  @backstage/plugin-scaffolder-backend                             1.22.11
  @backstage/plugin-scaffolder-common                              1.5.3
  @backstage/plugin-scaffolder-node                                0.4.7
  @backstage/plugin-scaffolder-react                               1.9.0
  @backstage/plugin-scaffolder                                     1.22.0
  @backstage/plugin-search-backend-module-catalog                  0.1.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.26
  @backstage/plugin-search-backend-node                            1.2.26
  @backstage/plugin-search-backend                                 1.5.13
  @backstage/plugin-search-common                                  1.2.12
  @backstage/plugin-search-react                                   1.7.12
  @backstage/plugin-search                                         1.4.13
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.8
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.11
  @backstage/plugin-techdocs-node                                  1.12.7
  @backstage/plugin-techdocs-react                                 1.2.5
  @backstage/plugin-techdocs                                       1.10.6
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.8
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.7
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 0.74s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by darylgraham** [comment]
`unable to resolve user identity` generally means that the OAuth flow has completed successfully but Backstage is not able to resolve the returned values back to a valid user entity in the catalog. This is normally achieved by either setting up the Github Org provider (to ingest all of your users and groups from Github into Backstage), or using a static catalog file to create the user/s. 

If you are just getting set up, going down the static route will be the easiest to get your user up and running while you set everything else up. It may also be a good idea to re-enable the Guest provider so that you can log in and check the status of your user entity in the catalog.

**Comment by EttilTony** [comment]
Ok great thank u! it works after adding it to the static file.

**Comment by benjdlambert** [comment]
Going to close this as fixed, please reach out if there's anything else.

**Comment by marcelmedeiros1** [comment]
> `unable to resolve user identity` generally means that the OAuth flow has completed successfully but Backstage is not able to resolve the returned values back to a valid user entity in the catalog. This is normally achieved by either setting up the Github Org provider (to ingest all of your users and groups from Github into Backstage), or using a static catalog file to create the user/s.
> 
> If you are just getting set up, going down the static route will be the easiest to get your user up and running while you set everything else up. It may also be a good idea to re-enable the Guest provider so that you can log in and check the status of your user entity in the catalog.

HOW CAN I DO THAT?

**Comment by EttilTony** [comment]
@marcelmedeiros1 you need to navigate to the org.yaml file in the examples folder and your github username in the metadata.name field.

**Comment by marcelmedeiros1** [comment]
Thank you, now it works! But.. backstage could put it into the documentation.

**Comment by ekgra** [comment]
@marcelmedeiros1 - can you please share exactly what you did here?

**Comment by ekgra** [comment]
it worked. I'll share snippets of what I did 

file -- examples/org.yaml
`apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: <github-username>
spec:
  memberOf: [guests]
`

also worthwhile to understand [Backstage Catalog ](https://backstage.io/docs/features/software-catalog/configuration/)- 
and [descriptor formats](https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-user) -

**Comment by Koshiz** [comment]
Thanks @ekgra ensuring the catalog files are correctly set in the app-config.yaml did the trick for me.
