### ISSUE TITLE
🐛 Bug Report: upgrade dependency isolated-vm to v5+

### ISSUE THREAD

**Issue by batazor** [backstage/backstage#25735]
### 📜 Description

The project stopped building with nodeJS 21+

### 👍 Expected behavior

successful build

### 👎 Actual Behavior with Screenshots

-

### 👟 Reproduction steps

1. nvm use 1.21
2. yarn install
3. ---fail

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @batazor, Backstage only supports the current Active LTS versions of Node which are currently 18 and 20 - https://backstage.io/docs/overview/versioning-policy#nodejs-releases.

As for `isolated-vm` there have been issues with that package in the past and I would suggest sticking to `4.x` range for now.

**Comment by Rugvip** [comment]
As mentioned we need to stay on 4.x for now, and are not yet supporting Node.js v21, so gonna close this.
