### ISSUE TITLE
🐛 Bug Report: executeShellCommand does not write to stream correctly.

### ISSUE THREAD

**Issue by billyatroadie** [backstage/backstage#25732]
### 📜 Description

During the research I performed to create this ticket, it's unclear whether this is a backstage issue, or a winston logger issue.

When I use the executeShellCommand in my custom action, and I pass the logger as the writeable stream, I do not get anything on the writeable interface.

### 👍 Expected behavior

It should write to the stream that is passed in so that I can see the stdout and stderr of the command.

### 👎 Actual Behavior with Screenshots

It actually does not write to the stream. Instead, I get a console log: 
```[winston] Unknown logger level: undefined```

Which led me to look into how the stream is written, adjusting the code in the plugin to use .info, instead of .write logs the stream via an info log, but I don't think that's accurate.

### 👟 Reproduction steps

Implement the `executeShellCommand` in a custom module. Ensure you pass the context's logger to the child process in the options parameter. Here is how I have mine configured:

```
        const result = await executeShellCommand({
          command,
          args,
          options: {
            // shell: true,
            cwd: ctx.workspacePath,
          },
          logStream: ctx.logger,
        });
```

Use this custom module in a template and use a simple command like this:

```
    - id: run-echo
      name: echo
      action: custom:execShellCommand
      input:
        command: echo
        args:  [
          "Hello World!"
        ]
```

See that the output of that command is not written to the logger as expected.

### 📃 Provide the context for the Bug.

No relevant context.

### 🖥️ Your Environment

Backstage version "1.27.0"

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Are you getting any TypeScript error on this line? `logStream: ctx.logger`, those should not be compatible. You can use `ctx.logStream`, although that's deprecated so better do what the deprecation message suggests instead.

**Comment by elaine-mattos** [comment]
Hi @Rugvip ,

I'm also facing the same issue...`ctx.logStream` works fine but is deprecated. The deprecated message says  `@deprecated — - use ctx.logger instead` but when I use `ctx.logger` winston says the loglevel is missing `[1] [winston] Unknown logger level: undefined`... I'm a little lost here but will probably keep on using the logstream for now...

**Comment by benjdlambert** [comment]
@elaine-mattos hey :wave: sorry I think we should have been a little more helpful here with the deprecation message.

`ctx.logStream` is indeed deprecated, and the alternative is to wrap up the `ctx.logger` in a stream yourself similar to this: 

```ts
const logStream = new Writable({
  defaultEncoding: 'utf8',
  write(chunk, _encoding, next) {
    ctx.logger.verbose(chunk.toString().trim());
    next();
  },
});
```

Does this help? Where are is `logStream` being used? Maybe you can migrate to just using `logger` instead?

**Comment by benjdlambert** [comment]
Ah darn, I think we should have deprecated that too when we deprecated the `logStream` so that you pass in `logger` instance instead and create the log stream in the `executeShellCommand`. 

Do you want to raise a PR for this @elaine-mattos? :pray:

**Comment by elaine-mattos** [comment]
Sure!

**Comment by billyatroadie** [comment]
> @elaine-mattos hey 👋 sorry I think we should have been a little more helpful here with the deprecation message.
> 
> `ctx.logStream` is indeed deprecated, and the alternative is to wrap up the `ctx.logger` in a stream yourself similar to this:
> 
> ```ts
> const logStream = new Writable({
>   defaultEncoding: 'utf8',
>   write(chunk, _encoding, next) {
>     ctx.logger.verbose(chunk.toString().trim());
>     next();
>   },
> });
> ```
> 
> Does this help? Where are is `logStream` being used? Maybe you can migrate to just using `logger` instead?

Where is the class Writeable? I can't seem to find it..

**Comment by benjdlambert** [comment]
@billyatroadie `import { Writable } from 'stream'` I think should do it
