### ISSUE TITLE
🐛 Bug Report: Use ES2022 for every ESBuild

### ISSUE THREAD

**Issue by dariozachow** [backstage/backstage#25737]
### 📜 Description

Currently the latest version of the toolbox plugin https://github.com/drodil/backstage-plugin-toolbox can't be used due to issues with esBuild. In this PR https://github.com/backstage/backstage/pull/24776 some occasions of the es version has been updated to es2022. But the optimizer https://github.com/backstage/backstage/blob/38165a7313adf2fde44f6e62b714cac2dbe863ce/packages/cli/src/lib/bundler/optimization.ts#L31 still uses es2019 which leads to build issues with the plugin.

### 👍 Expected behavior

Backstage should no longer be build with es2019 but with es2022 everywhere, thus the plugin is usable again. When editing the node_modules directly and setting es2019 to es2022 the build runs successfully with the latest version of the plugin

### 👎 Actual Behavior with Screenshots

The problems are described in https://github.com/drodil/backstage-plugin-toolbox/issues/101 and https://github.com/backstage/backstage/issues/24939 and should be fixed by that change

### 👟 Reproduction steps

described in https://github.com/drodil/backstage-plugin-toolbox/issues/101 and https://github.com/backstage/backstage/issues/24939

### 📃 Provide the context for the Bug.

described in https://github.com/drodil/backstage-plugin-toolbox/issues/101 and https://github.com/backstage/backstage/issues/24939

### 🖥️ Your Environment

described in https://github.com/drodil/backstage-plugin-toolbox/issues/101 and https://github.com/backstage/backstage/issues/24939

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by drodil** [comment]
Ping @Rugvip, there was this PR where the esbuild was bumped to 2022: https://github.com/backstage/backstage/pull/24776
