### ISSUE TITLE
🚀 Feature: Support RepoUrlPicker for Prepopulation of GitLab Groups and Repos

### ISSUE THREAD

**Issue by piyush12** [backstage/backstage#25744]
### 🔖 Feature description

Allow users to fetch the group/owners and repositories using GitLab API calls.

### 🎤 Context

Currently, the RepoUrlPicker only supports manually entering the group/owner and repository. In our use case, we need to fetch the groups and repositories from the GitLab API. We propose adding keys for fetchOwners and fetchRepos which have options for API and parameters, as shown in the example below. This way, if anyone needs to fetch owners and repos from an API, they can pass the API info in the fetchOwners and fetchRepos keys; otherwise, these keys can be omitted.

<pre>
repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPickerCustom
          ui:options:
            allowedHosts:
              - gitlab.com
            fetchOwners:
              api: 'api/v4/groups'
              params:
                limit: '100'
                per_page: '200'
                owned: 'false'
            fetchRepos:
              api: 'api/v4/groups/:groupId/projects'
              params:
                limit: '100'
                per_page: '200'
                owned: 'false'
</pre>

### ✌️ Possible Implementation

To support the fetching of GitLab groups and repositories in the RepoUrlPicker component, I have implemented the following changes:

Updated RepoUrlPicker Component:
        Added support for new fetchOwners and fetchRepos keys in the ui:options configuration.
        These keys include the API endpoint and parameters required to fetch the data.

Example code changes. 

On initial render, we call the owner API and store it in the groups state.

<pre>
   useEffect(() => {
    async function getOwners() {
      const params = new URLSearchParams(fetchOwners?.params);

      await wait(500);

      const response = await fetchApi.fetch(
        'https://${state.host}/${fetchOwners?.api}?${params}',
        {
          headers: {
            Authorization: 'Bearer XXXXXX',
          },
        },
      );
      if (response.ok) {
        const data = await response.json();
        const getGroupName = data.map((group: any) => ({
          label: group.path,
          value: group.id,
        }));
        setGroups(getGroupName);
        const getFirstId = getGroupName[0].value;
        const getFirstName = getGroupName[0].label;
        setState(prevState => ({ ...prevState, owner: getFirstName }));
        const apiUrl = fetchRepos?.api.replace(':groupId', getFirstId);
        const repoResponse = await fetchApi.fetch(
          'https://${state.host}/${apiUrl}?${params}',
          {
            headers: {
              Authorization: `Bearer XXXXX`,
            },
          },
        );
        if (repoResponse.ok) {
          const data = await repoResponse.json();
          const getRepoName = data.map((repos: any) => repos.path);
          setRepos(getRepoName);
          setState(prevState => ({ ...prevState, repoName: getRepoName[0] }));
        }
      }
    }

    if (secrets && secrets.USER_OAUTH_TOKEN && fetchOwners) {
      getOwners();
    }
  }, [secrets]);

</pre>

getRepository method will call once user select the owners/groups

<pre>

{hostType === 'gitlab' && (
        <GitlabRepoPicker
          allowedOwners={fetchOwners ? groups : allowedOwners}
          rawErrors={rawErrors}
          state={state}
          onChange={value => {
            if (fetchOwners) {
              getRepository(value);
            }
            updateLocalState(value);
          }}
          loading={fetchOwners ? groups.length === 0 ? true : false : false}
        />
      )}

</pre>

<pre>
  const getRepository = async (value: RepoUrlPickerState) => {
    setRepos([]);
    const groupId = groups.find(group => group.label === value.owner)?.value;
    const params = new URLSearchParams(fetchRepos?.params);
    const apiUrl = groupId ? fetchRepos?.api.replace(':groupId', groupId) : '';
    const response = await fetchApi.fetch(
      `https://${state.host}/${apiUrl}?${params}`,
      {
        headers: {
          Authorization: 'Bearer XXXXXXX',
        },
      },
    );
    if (response.ok) {
      const data = await response.json();
      const getRepoName = data.map((repos: any) => repos.path);
      setRepos(getRepoName);
      setState(prevState => ({ ...prevState, repoName: getRepoName[0] }));
    }
  };
</pre>

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
:wave: Hey!

Thanks for raising this issue, I think that you might want to follow in the footsteps of @benjidotsh did to add the `autocomplete` to the bitbucket picker. https://github.com/backstage/backstage/pull/25132 is some prior art.

This `autocomplete` functionality would take the users GitLab token and pre-populate the fields using the scaffolder backend. I don't think we would need the additional `yaml` in the proposal this way.

Do you want to look at raising a PR for this functionality? :pray:

**Comment by benjdlambert** [comment]
https://github.com/backstage/backstage/pull/27367 is the latest work on this
