### ISSUE TITLE
🐛 Bug Report: Notifications don't work without users in catalog

### ISSUE THREAD

**Issue by raphtalia** [backstage/backstage#25768]
### 📜 Description

We are trying to use the notifications plugin with a [catalog with no users](https://backstage.io/docs/auth/identity-resolver/#sign-in-without-users-in-the-catalog). Unfortunately [this](https://github.com/backstage/backstage/blob/efa662505042fce8ad72066237942bcc64fe6c24/plugins/notifications-backend/src/service/router.ts#L113-L119) is resolving a list of user entity refs to entities in the catalog before sending out notifications resulting in no notifications being sent out in our case. I was able to fix this by commenting out the check in our codebase but I think an extension point to allow for custom user resolvers may be a better solution.

### 👍 Expected behavior

Given a list of user entity refs, notifications should be sent out to all of them.

### 👎 Actual Behavior with Screenshots

No notifications are sent out.

### 👟 Reproduction steps

1. Create sign-in resolver for catalog with no users
2. Send out notifications

### 📃 Provide the context for the Bug.

We have a custom sign-in resolver for allowing users to login without a corresponding user in the catalog.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by drodil** [comment]
Hi, made a fix #25781 that bypasses catalog calling for all user entity references. This would also help a bit to remove unnecessary calls to the catalog for notifications targeted directly to users.
