### ISSUE TITLE
🐛 Bug Report: Error when registering custom actions/new actions in new backend. 

### ISSUE THREAD

**Issue by ACEHiGH1** [backstage/backstage#25776]
### 📜 Description

 Unable to successfully register custom actions or Roadie's HTTP requests actions after installing their plugin.

### 👍 Expected behavior

Register the custom action/plugin's actions.

### 👎 Actual Behavior with Screenshots

 C:\Users\name\appName\node_modules\@backstage\backend-app-api\src\wiring\BackstageBackend.ts:69
[1]   if ('$$type' in feature) {
[1]       ^
[1]
[1]
[1] TypeError: Cannot use 'in' operator to search for '$$type' in undefined
[1]     at unwrapFeature (C:\Users\GDhima\platform2\node_modules\@backstage\backend-app-api\src\wiring\BackstageBackend.ts:69:7)
[1]     at <anonymous> (C:\Users\GDhima\platform2\node_modules\@backstage\backend-app-api\src\wiring\BackstageBackend.ts:35:47)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### 👟 Reproduction steps

1. Create a custom action by using Backstage CLI.
2. Register it to the backend (or at least try to)
3. Run `yarn dev`

### 📃 Provide the context for the Bug.

C:\Users\name\appName\node_modules\@backstage\backend-app-api\src\wiring\BackstageBackend.ts:69
[1]   if ('$$type' in feature) {
[1]       ^
[1]
[1]
[1] TypeError: Cannot use 'in' operator to search for '$$type' in undefined
[1]     at unwrapFeature (C:\Users\name\appName\node_modules\@backstage\backend-app-api\src\wiring\BackstageBackend.ts:69:7)
[1]     at <anonymous> (C:\Users\name\appName\node_modules\@backstage\backend-app-api\src\wiring\BackstageBackend.ts:35:47)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

---------------------------------------------------------------------------------------------------------------------------------------------

I created a custom action by using the `yarn backstage-cli new` command, in which I chose the scaffolder-module option. It generated a example scaffolder action, a backend module that registers the action in the scaffolder and the export index files. I made sure to register the action in backend by including: 
`"backend.add(import('backstage-plugin-scaffolder-backend-module-<custom-action-name>'));"` in _packages/backend/src/index.ts_

When I execute `yarn dev`, it gives me the error shown on top. I have already added **@backstage/plugin-scaffolder-node** as a dependency. I also tried installing the HTTP request plugin by Roadie. It also gives me a similar error in that case:

"[1] C:\Users\name\appName\node_modules\@backstage\backend-app-api\src\wiring\BackendInitializer.ts:105
[1]       throw new Error(
[1] Error: Failed to add feature, invalid type 'undefined'
[1]     at BackendInitializer.#addFeature (C:\name\appName\platform2\node_modules\@backstage\backend-app-api\src\wiring\BackendInitializer.ts:105:13)
[1]     at BackendInitializer.#doStart (C:\Users\GDhima\platform2\node_modules\@backstage\backend-app-api\src\wiring\BackendInitializer.ts:157:12)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at BackendInitializer.start (C:\Users\name\appName\node_modules\@backstage\backend-app-api\src\wiring\BackendInitializer.ts:150:5)
[1]     at BackstageBackend.start (C:\Users\name\appName\node_modules\@backstage\backend-app-api\src\wiring\BackstageBackend.ts:42:11
)
"

### 🖥️ Your Environment

node: v20.14.0
yarn: 1.22.4
cli:  0.26.11 (installed)
backstage:  1.28.0

Dependencies:
  @backstage/app-defaults                                          1.5.6
  @backstage/backend-app-api                                       0.7.9, 0.7.8
  @backstage/backend-common                                        0.0.0-nightly-20240627021712, 0.13.5, 0.21.7, 0.23.2, 0.23.3
  @backstage/backend-defaults                                      0.3.2
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.0.0-nightly-20240627021712, 0.1.14
  @backstage/backend-plugin-api                                    0.0.0-nightly-20240627021712, 0.6.21, 0.7.0
  @backstage/backend-tasks                                         0.0.0-nightly-20240627021712, 0.5.26, 0.5.27
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.6, 0.2.7
  @backstage/cli                                                   0.26.11, 0.26.9
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.1, 1.12.6
  @backstage/core-compat-api                                       0.2.6
  @backstage/core-components                                       0.14.8, 0.14.9-next.0
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.6, 0.6.7-next.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.28, 1.1.29-next.0
  @backstage/integration                                           0.0.0-nightly-20240627021712, 1.13.0, 1.12.0, 1.13.0-next.0
  @backstage/plugin-api-docs                                       0.11.6
  @backstage/plugin-app-backend                                    0.3.69
  @backstage/plugin-app-node                                       0.1.20
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.1
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.12
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.3
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.3
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.15
  @backstage/plugin-auth-backend-module-github-provider            0.1.17
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.17
  @backstage/plugin-auth-backend-module-google-provider            0.1.17
  @backstage/plugin-auth-backend-module-guest-provider             0.1.6
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.15
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.1
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.13
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.13
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.1
  @backstage/plugin-auth-backend                                   0.22.7
  @backstage/plugin-auth-node                                      0.0.0-nightly-20240627021712, 0.4.17, 0.4.16
  @backstage/plugin-auth-react                                     0.1.3
  @backstage/plugin-bitbucket-cloud-common                         0.2.21
  @backstage/plugin-catalog-backend-module-github-org              0.1.16
  @backstage/plugin-catalog-backend-module-github                  0.6.4
  @backstage/plugin-catalog-backend-module-logs                    0.0.0-nightly-20240625021714
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.19, 0.1.20
  @backstage/plugin-catalog-backend                                0.0.0-nightly-20240627021712, 1.23.2
  @backstage/plugin-catalog-common                                 1.0.24, 1.0.25
  @backstage/plugin-catalog-graph                                  0.4.6
  @backstage/plugin-catalog-import                                 0.12.0
  @backstage/plugin-catalog-node                                   0.0.0-nightly-20240627021712, 1.12.3, 1.12.4
  @backstage/plugin-catalog-react                                  1.12.1, 1.12.2-next.1
  @backstage/plugin-catalog                                        1.21.0
  @backstage/plugin-events-backend-module-github                   0.2.7
  @backstage/plugin-events-backend                                 0.3.8
  @backstage/plugin-events-node                                    0.0.0-nightly-20240627021712, 0.3.7
  @backstage/plugin-org                                            0.6.26
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.17
  @backstage/plugin-permission-backend                             0.5.44
  @backstage/plugin-permission-common                              0.7.14, 0.8.0
  @backstage/plugin-permission-node                                0.0.0-nightly-20240627021712, 0.7.32, 0.8.0
  @backstage/plugin-permission-react                               0.4.23
  @backstage/plugin-proxy-backend                                  0.5.1
  @backstage/plugin-scaffolder-backend-module-azure                0.1.13, 0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.11, 0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.11, 0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.11, 0.2.12
  @backstage/plugin-scaffolder-backend-module-cookiecutter         0.2.44
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.13, 0.1.14
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.11, 0.1.12
  @backstage/plugin-scaffolder-backend-module-github               0.3.2, 0.4.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.3, 0.4.4
  @backstage/plugin-scaffolder-backend                             1.22.11, 1.23.0
  @backstage/plugin-scaffolder-common                              1.5.3, 1.5.4
  @backstage/plugin-scaffolder-node                                0.4.8, 0.4.7
  @backstage/plugin-scaffolder-react                               1.9.0
  @backstage/plugin-scaffolder                                     1.21.0
  @backstage/plugin-search-backend-module-catalog                  0.0.0-nightly-20240627021712, 0.1.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.25
  @backstage/plugin-search-backend-node                            0.0.0-nightly-20240627021712, 1.2.26
  @backstage/plugin-search-backend                                 1.5.12
  @backstage/plugin-search-common                                  1.2.12, 1.2.13
  @backstage/plugin-search-react                                   1.7.12
  @backstage/plugin-search                                         1.4.12
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.7
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.11
  @backstage/plugin-techdocs-node                                  1.12.6
  @backstage/plugin-techdocs-react                                 1.2.5
  @backstage/plugin-techdocs                                       1.10.6
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.7
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.6
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by awanlin** [comment]
Hi @ACEHiGH1, taking a quick look at the packages info you shared you have lots of duplicates as well as nightly versions. I would try cleaning that up as it's likely to be part of the problem.

**Comment by Rugvip** [comment]
It's also best to check if there are any TypeScript errors with `yarn tsc`, you'll want to track down and fix all of those before debugging runtime issues.

**Comment by ACEHiGH1** [comment]
Hi @awanlin and @Rugvip . Thanks for the prompt reply. I cleaned all the nightly versions and most of the duplicates. It did not fix anything unfortunately. Regarding the Typescript errors, when I'm running `yarn tsc`, a mismatch arguments error comes up (as seen below). I'm new in TypeScript so any suggestions are helpful. Here's the error: 

"
Argument of type 'Promise<typeof import("C:/Users/GDhima/platform2/plugins/scaffolder-backend-module-customaction/src/index")>' is not assignable to parameter of type 'BackendFeature | (() => BackendFeature) | Promise<{ default: BackendFeature | (() => BackendFeature); }>'.
 Property 'default' is missing in type 'typeof import("C:/Users/GDhima/platform2/plugins/scaffolder-backend-module-customaction/src/index")' but required in type '{ default: BackendFeature| (() => BackendFeature); }'.

59 backend.add(import('backstage-plugin-scaffolder-backend-module-customaction'));
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 node_modules/@backstage/backend-app-api/dist/index.d.ts:446:9
 446 default: BackendFeature | (() => BackendFeature);
 ~~~~~~~
 'default' is declared here.
"


I have not changed anything at all from the action and backend module generated by Backstage CLI. 

**example.ts**
"import { createTemplateAction } from '@backstage/plugin-scaffolder-node';

/**
 * Creates an `acme:example` Scaffolder action.
 *
 * @remarks
 *
 * See {@link https://example.com/} for more information.
 *
 * @public
 */
export function createAcmeExampleAction() {
 // For more information on how to define custom actions, see
 // https://backstage.io/docs/features/software-templates/writing-custom-actions
 return createTemplateAction<{
 myParameter: string;
 }>({
 id: 'acme:example',
 description: 'Runs Yeoman on an installed Yeoman generator',
 schema: {
 input: {
 type: 'object',
 required: ['myParameter'],
 properties: {
 myParameter: {
 title: 'An example parameter',
 description: 'This is the schema for our example parameter',
 type: 'string',
 },
 },
 },
 },
 async handler(ctx) {
 [ctx.logger.info](https://ctx.logger.info/)(
 `Running example template with parameters: ${ctx.input.myParameter}`,
 );

 await new Promise(resolve => setTimeout(resolve, 1000));
 },
 });
}"

and 

**module.ts**
"
import { createBackendModule } from "@backstage/backend-plugin-api";
import { scaffolderActionsExtensionPoint } from '@backstage/plugin-scaffolder-node/alpha';
import { createAcmeExampleAction } from "./example";

/**
 * A backend module that registers the action into the scaffolder
 */
export const scaffolderModule = createBackendModule({
 moduleId: 'acme:example',
 pluginId: 'scaffolder',
 register({ registerInit }) {
 registerInit({
 deps: {
 scaffolderActions: scaffolderActionsExtensionPoint
 },
 async init({ scaffolderActions}) {
 scaffolderActions.addActions(createAcmeExampleAction());
 }
 });
 },
})

"

And of course the index.ts files.

**Comment by ACEHiGH1** [comment]
So, I changed  `backend.add(import('backstage-plugin-scaffolder-backend-module-customaction'));` to `backend.add(import('backstage-plugin-scaffolder-backend-module-customaction/src/actions/example'));` and it works fine now. I had the idea that the backend module would get re-exported all the way to main module ("backstage-plugin-scaffolder-backend-module-customaction", but doesn't look like it. Is this how we are intended to import the backend module?

**Comment by Rugvip** [comment]
@ACEHiGH1 not quite, that'll cause trouble in a production build. You'll want to make sure the module is manually exported as the default export from src/index.ts instead.

**Comment by ACEHiGH1** [comment]
@Rugvip I was able to do the following changes and make it work locally.

** Project Structure:**

plugins/
├─ scaffolder-backend-module-teamcity/
│  ├─ node_modules/
│  ├─ src/
│  │  ├─ actions/
│  │  │  ├─ index.ts
│  │  │  ├─ startbuild.ts
│  │  ├─ module.ts
│  │  ├─ index.ts

```

**In the src/actions/index.ts file:**
`export { createStartTCBuildAction } from './startbuild';`


**In the src/module.ts file:**
`import { createBackendModule } from "@backstage/backend-plugin-api";
import { scaffolderActionsExtensionPoint  } from '@backstage/plugin-scaffolder-node/alpha';
import { createStartTCBuildAction } from "./actions";
import { coreServices } from '@backstage/backend-plugin-api';

/**
 * A backend module that registers the action into the scaffolder
 */
export const scaffolderModuleTeamCity = createBackendModule({
  moduleId: 'teamcity',
  pluginId: 'scaffolder',
  register({ registerInit }) {
    registerInit({
      deps: {
        scaffolderActions: scaffolderActionsExtensionPoint,
        config: coreServices.rootConfig
      },
      async init({ scaffolderActions, config}) {
        scaffolderActions.addActions(createStartTCBuildAction({config: config}));
      }
    });
  },
})
`

**In src/index.ts: **

`export * from './actions';
export { scaffolderModuleTeamCity as default } from './module';`

_// Importing the custom action modules in packages/backend/src/index.ts_

```
backend.add(import('backstage-plugin-scaffolder-backend-module-teamcity'));
backend.add(import('backstage-plugin-scaffolder-backend-module-github-custom'));
```
```

So this works in my local environment without any issues at all. **However, I tried creating a Docker Image and running it and get the following import error message:** 

" Cannot find package 'backstage-plugin-scaffolder-backend-module-teamcity' imported from /app/packages/backe
nd/dist/index.cjs.js"

I can't seem to find the reason now why it is not correctly exporting the module. Any help is greatly appreciated.

**Comment by awanlin** [comment]
Hi @ACEHiGH1, I have not read everything but could you be missing your package scope? This:

```ts
backend.add(import('backstage-plugin-scaffolder-backend-module-teamcity'));
backend.add(import('backstage-plugin-scaffolder-backend-module-github-custom'));
```

Should be this:

```ts
backend.add(import('@internal/backstage-plugin-scaffolder-backend-module-teamcity'));
backend.add(import('@internal/backstage-plugin-scaffolder-backend-module-github-custom'));
```

By default when you use `yarn new` it creates the packages inside the `@interanl` scope.

**Comment by ACEHiGH1** [comment]
Hi @awanlin ,
First of all, thanks a lot for the help.

I wanted to create a custom action and used the yarn backstage-cli new command, in which I selected the : 
**scaffolder-module - An module exporting custom actions for @backstage/plugin-scaffolder-backend** option. However, the packages created are not part of the `@internal` scope. 

node_modules/
├─ @backstage/
├─ @azure/
├─ .../
├─ backstage-plugin-scaffolder-backend-module-teamcity/


When I switched over to this:
`backend.add(import('@internal/backstage-plugin-scaffolder-backend-module-teamcity'));
backend.add(import('@internal/backstage-plugin-scaffolder-backend-module-github-custom'));`


Even locally it complains that it can't find the module 
(Error: Cannot find module '@internal/backstage-plugin-scaffolder-backend-module-github-custom')

Here is my package.json file for one of the modules if it helps for anything:
`
{
  "name": "backstage-plugin-scaffolder-backend-module-teamcity",
  "description": "The teamcity module for @backstage/plugin-scaffolder-backend",
  "version": "0.1.0",
  "main": "src/index.ts",
  "types": "src/index.ts",
  "license": "Apache-2.0",
  "private": true,
  "publishConfig": {
    "access": "public",
    "main": "dist/index.cjs.js",
    "types": "dist/index.d.ts"
  },
  "backstage": {
    "role": "backend-plugin-module"
  },
  "scripts": {
    "start": "backstage-cli package start",
    "build": "backstage-cli package build",
    "lint": "backstage-cli package lint",
    "test": "backstage-cli package test",
    "clean": "backstage-cli package clean",
    "prepack": "backstage-cli package prepack",
    "postpack": "backstage-cli package postpack"
  },
  "dependencies": {
    "@backstage/plugin-scaffolder-node": "^0.4.8"
  },
  "devDependencies": {
    "@backstage/backend-common": "^0.23.3",
    "@backstage/cli": "^0.26.7"
  },
  "files": [
    "dist"
  ] `

**Comment by awanlin** [comment]
Ok, that's odd as it is the default: https://github.com/backstage/backstage/blob/edb89a2ee77b83ffe439383833021cc5cefaee5e/packages/create-app/templates/default-app/package.json.hbs#L25

You must have changed it at some point. That's the only thing that came to me when I spotted this.

**Comment by awanlin** [comment]
What does `packages/backend/package.json` look like?

**Comment by ACEHiGH1** [comment]
```{
  "name": "backend",
  "version": "0.0.0",
  "main": "dist/index.cjs.js",
  "types": "src/index.ts",
  "private": true,
  "backstage": {
    "role": "backend"
  },
  "scripts": {
    "start": "backstage-cli package start",
    "build": "backstage-cli package build",
    "lint": "backstage-cli package lint",
    "test": "backstage-cli package test",
    "clean": "backstage-cli package clean",
    "build-image": "docker build ../.. -f Dockerfile --tag backstage"
  },
  "dependencies": {
    "@backstage/backend-common": "^0.23.3",
    "@backstage/backend-defaults": "^0.3.0",
    "@backstage/backend-tasks": "^0.5.24",
    "@backstage/config": "^1.2.0",
    "@backstage/plugin-app-backend": "^0.3.68",
    "@backstage/plugin-auth-backend": "^0.22.6",
    "@backstage/plugin-auth-backend-module-github-provider": "^0.1.16",
    "@backstage/plugin-auth-backend-module-guest-provider": "^0.1.5",
    "@backstage/plugin-auth-node": "^0.4.14",
    "@backstage/plugin-catalog-backend": "^1.23.2",
    "@backstage/plugin-catalog-backend-module-github": "^0.6.4",
    "@backstage/plugin-catalog-backend-module-github-org": "^0.1.16",
    "@backstage/plugin-catalog-backend-module-logs": "^0.0.1",
    "@backstage/plugin-catalog-backend-module-scaffolder-entity-model": "^0.1.17",
    "@backstage/plugin-events-backend": "^0.3.8",
    "@backstage/plugin-events-backend-module-github": "^0.2.7",
    "@backstage/plugin-permission-backend": "^0.5.43",
    "@backstage/plugin-permission-backend-module-allow-all-policy": "^0.1.16",
    "@backstage/plugin-permission-common": "^0.8.0",
    "@backstage/plugin-permission-node": "^0.8.0",
    "@backstage/plugin-proxy-backend": "^0.5.0",
    "@backstage/plugin-scaffolder-backend": "^1.22.9",
    "@backstage/plugin-scaffolder-backend-module-cookiecutter": "^0.2.44",
    "@backstage/plugin-scaffolder-backend-module-github": "^0.4.0",
    "@backstage/plugin-search-backend": "^1.5.10",
    "@backstage/plugin-search-backend-module-catalog": "^0.1.27",
    "@backstage/plugin-search-backend-module-techdocs": "^0.1.24",
    "@backstage/plugin-search-backend-node": "^1.2.26",
    "@backstage/plugin-techdocs-backend": "^1.10.6",
    "@backstage/plugin-scaffolder-node": "^0.4.8",
    "@mdude2314/backstage-plugin-scaffolder-git-actions": "^1.1.1",
    "app": "link:../app",
    "better-sqlite3": "^9.0.0",
    "node-gyp": "^10.0.0",
    "pg": "^8.11.3",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "@backstage/cli": "^0.26.7",
    "@types/express": "^4.17.6",
    "@types/express-serve-static-core": "^4.17.5",
    "@types/luxon": "^2.0.4"
  },
  "files": [
    "dist"
  ]
} ```

**Comment by awanlin** [comment]
I would expect to see `backstage-plugin-scaffolder-backend-module-teamcity` and `backstage-plugin-scaffolder-backend-module-github-custom` listed under `dependencies` but they are not. I would add them.

**Comment by ACEHiGH1** [comment]
That worked! Thank you so much!

**Comment by camilaibs** [comment]
> That worked! Thank you so much!

Glad to hear that @ACEHiGH1, could we close this issue?

**Comment by amrsa1** [comment]
whats the solution i getting the same error upon running yarn dev

`[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/./my-backstage-app/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all
[1] /Users/./my-backstage-app/node_modules/@backstage/backend-app-api/src/wiring/helpers.ts:23
[1]   if ('$$type' in feature) {
[1]       ^
[1] 
[1] 
[1] TypeError: Cannot use 'in' operator to search for '$$type' in undefined
[1]     at unwrapFeature (/Users/./my-backstage-app/node_modules/@backstage/backend-app-api/src/wiring/helpers.ts:23:7)
[1]     at BackstageBackend.add (/Users/./my-backstage-app/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:33:29)
[1]     at Object.<anonymous> (/Users/./my-backstage-app/packages/backend/src/index.ts:56:9)
[1]     at Module._compile (node:internal/modules/cjs/loader:1358:14)
[1]     at Module._compile (/Users/./my-backstage-app/node_modules/pirates/lib/index.js:117:24)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
[1]     at Object.newLoader [as .ts] (/Users/./my-backstage-app/node_modules/pirates/lib/index.js:121:7)
[1]     at Module.load (node:internal/modules/cjs/loader:1208:32)
[1]     at Module._load (node:internal/modules/cjs/loader:1024:12)
[1]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
[1] `

**Comment by freben** [comment]
@amrsa1 what's on the line that causes the error (`packages/backend/src/index.ts:56`)?

Have you checked the fixes people above have mentioned?

Does `yarn tsc:full` complete successfully?

Did you add any `// @ts-ignore` or similar that might be hiding actual problems?

**Comment by amrsa1** [comment]
Hello @freben Thanks for getting back to me.

Actually i didnt know about this command yarn tsc:full, i follow up with the errors and fixed them.
Now its working without issue.

Thanks!

**Comment by ACEHiGH1** [comment]
> > That worked! Thank you so much!
> 
> Glad to hear that @ACEHiGH1, could we close this issue?

Sorry for the late response, I thought I had already answered. Yes, this issue can be closed.
