### ISSUE TITLE
The techdocs-container on DockerHub uses the readme from the root of the Backstage repo instead of the package readme's. The techdocs-core plugin published to pypi uses no readme.

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#2579]
We should be more specific here and point to the readme for the actual package instead of the general backstage readme.

- [x] techdocs-core to publish [this README](https://github.com/spotify/backstage/blob/master/packages/techdocs-container/techdocs-core/README.md) to pypi. #2578 

- [ ] techdocs-container to publish [this README](https://github.com/spotify/backstage/blob/master/packages/techdocs-container/README.md) to Docker Hub. #2593

**Comment by hooloovooo** [comment]
The techdocs-cli looks correct here. https://www.npmjs.com/package/@techdocs/cli
It it a bit misleading though that issues and PRs points to all issues and PRs in backstage though, but that might be hard to get around.

**Comment by emmaindal** [comment]
@hooloovooo oh that's correct, for that one it was links etc, will update the issue

**Comment by OrkoHunter** [comment]
We now have the packages in separate repositories. They will render the correct README. :)
