### ISSUE TITLE
🐛 Bug Report: Microsoft Azure Authentication Provider- Unable to resolve user identity

### ISSUE THREAD

**Issue by smmaster** [backstage/backstage#25790]
### 📜 Description

Getting Failed to sign-in, unable to resolve user identity when logging with Microsoft provider https://backstage.io/docs/auth/microsoft/provider/
![image](https://github.com/user-attachments/assets/e6adabb4-e81d-4bf2-8f03-a4eff85d0d60)

### 👍 Expected behavior

login should work using Microsoft Azure Authentication Provider

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/e6adabb4-e81d-4bf2-8f03-a4eff85d0d60)

### 👟 Reproduction steps

Plugin installation procedure https://backstage.io/docs/auth/microsoft/provider/

### 📃 Provide the context for the Bug.

login with Microsoft Azure Authentication Provider

### 🖥️ Your Environment

app created with latestversion 

npx @backstage/create-app@latest
Need to install the following packages:
@backstage/create-app@0.5.17

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @smmaster, this means that it was not able to match the user in the auth profile with a user in your Catalog. There's details about this logic in the resolvers section of the docs you shared: https://backstage.io/docs/auth/microsoft/provider#resolvers

Have you populated your Catalog with Users? Perhaps this could help: https://backstage.io/docs/integrations/azure/org
