### ISSUE TITLE
🐛 Bug Report:  Request failed with status 500 Missing index for software-catalog,techdocs. This could be because the index hasn't been created yet or there was a problem during index creation

### ISSUE THREAD

**Issue by vinaykv23** [backstage/backstage#25797]
### 📜 Description

Hi Team
Backstage **"version": "1.28.0"**
getting below error in the background, but catalog data is loading
what is the reason and how to correct this

{"level":"error","message":"Request failed with status 500 Missing index for software-catalog,techdocs. This could be because the index hasn't been created yet or there was a problem during index creation.","name":"MissingIndexError","service":"backstage","stack":"MissingIndexError: Missing index for software-catalog,techdocs. This could be because the index hasn't been created yet or there was a problem during index creation.\n    at LunrSearchEngine.query (/app/node_modules/@backstage/plugin-search-backend-node/dist/index.cjs.js:510:13)\n    at AuthorizedSearchEngine.query (/app/node_modules/@backstage/plugin-search-backend/dist/cjs/router-CDCjjf7o.cjs.js:89:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/node_modules/@backstage/plugin-search-backend/dist/cjs/router-CDCjjf7o.cjs.js:478:25","type":"errorHandler"}

### 👍 Expected behavior

Error should not occur in the backstage
Request failed with status 500 Missing index for software-catalog,techdocs. This could be because the index hasn't been created yet or there was a problem during index creation. 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/bc61c836-82c6-4d0f-b7c0-d44c5caad922)

### 👟 Reproduction steps

Create backstage app and implemented okta auth, gitlab integration and gitlab catalog discovery
deploy to kubernetes environment

kubectl logs backstage-5855werttyf-t9rty

"level":"error","message":"Request failed with status 500 Missing index for software-catalog,techdocs. This could be because the index hasn't been created yet or there was a problem during index creation."

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by PeaWarrior** [comment]
Hey, are you using [backstage-next](https://github.com/spotify/backstage-plugins/blob/a1d669cf7e202b934652378ba700043ede505fb4/packages/backend-next/src/index.ts) or the [legacy backstage](https://github.com/spotify/backstage-plugins/blob/a1d669cf7e202b934652378ba700043ede505fb4/packages/backend/src/index.ts) set up?

**Comment by vinaykv23** [comment]
> Backstage **"version": "1.28.0"**

Hi @PeaWarrior 
we are using Backstage "version": "1.28.0"
not getting what is [backstage-next](https://github.com/spotify/backstage-plugins/blob/a1d669cf7e202b934652378ba700043ede505fb4/packages/backend-next/src/index.ts) or the [legacy backstage](https://github.com/spotify/backstage-plugins/blob/a1d669cf7e202b934652378ba700043ede505fb4/packages/backend/src/index.ts) set up, once I try to access this like getting "page not found" error

![image](https://github.com/user-attachments/assets/697dc4bf-09cb-48a9-99fb-8a0379822588)

**Comment by PeaWarrior** [comment]
Sorry, I updated the links to the correct one. Could you share how you're setting up your backstage?

**Comment by vinaykv23** [comment]
> ching within a tech doc o

hi @PeaWarrior 

I am using https://github.com/backstage/backstage/blob/master/packages%2Fbackend%2Fsrc%2Findex.ts
error is displaying when we click on catalog menu and on load of backstage home page

**Comment by freben** [comment]
Are you using that literal file? As in, did you clone the main repo and try to deploy that? If that's the case, you will want to follow [the getting-started guide](https://backstage.io/docs/getting-started/) instead where you make your own repo from scratch.

The error is most likely correct, in the sense that those indices weren't produced so there was nothing to search through. So the question is, why are those indices not present. Maybe there are other errors in the log that point to why the search backend failed to make those indices? Could there be a permissions issue such that it can't write to your storage of choice? Could it be failing to reach out to the catalog or techdocs backends to scrape them for data while collating?

**Comment by vinaykv23** [comment]
> Are you using that literal file? As in, did you clone the main repo and try to deploy that? If that's the case, you will want to follow [the getting-started guide](https://backstage.io/docs/getting-started/) instead where you make your own repo from scratch.
> 
> The error is most likely correct, in the sense that those indices weren't produced so there was nothing to search through. So the question is, why are those indices not present. Maybe there are other errors in the log that point to why the search backend failed to make those indices? Could there be a permissions issue such that it can't write to your storage of choice? Could it be failing to reach out to the catalog or techdocs backends to scrape them for data while collating?

Hi @freben 

I followed [the getting-started guide](https://backstage.io/docs/getting-started/) to create project
its able fetching catalog data from gitlab, but in the background we are seeing this error

**Comment by JounQin** [comment]
I'm meeting this error quite often too.

<img width="682" alt="image" src="https://github.com/user-attachments/assets/32e77c00-707d-4c3a-a417-0a1b03431218">

I'm using the following database settings, not sure could that be the problem.

```yaml
database:
  client: better-sqlite3
  connection:
    directory: './dbs'
```

**Comment by ggkoning** [comment]
I am having the same issue with techdocs.

And also an issue with techdocs not loading.
<img width="1255" alt="Screenshot 2024-08-19 at 17 39 50" src="https://github.com/user-attachments/assets/360eac13-e2c7-45ef-bde6-b8d8c0ba3ad1">

Environment
Backstage: 1.28.3
Backend: new
Frontend: old

**Comment by ggkoning** [comment]
I followed [the getting-started guide](https://backstage.io/docs/getting-started/) to create a project.
I then added a component with a techdocs url to a private repository.
Lastly I added github integration with credentials.

The result was a working techdocs page of the specific component but the search for techdocs remain broken.

**Comment by ggkoning** [comment]
@freben I have the same issue and it is dependent on which database you use. The problem occurs when using the following database configuration ```  database:
    client: better-sqlite3
    connection: ':memory:'```

but when using the pg client with the following configuration it works ass expected
```  database:
    client: "pg"
    connection: "postgresql://postgres:backstage-main@127.0.0.1:5433"```

**Comment by freben** [comment]
Yeah postgres is the only supported production database. Don't worry about sqlite; it's only meant for brief local testing and similar. Sqlite is in-memory and/or local, and Backstage is critically dependent on having a central separate database to coordinate through. Hence, pg.

**Comment by Ijaz1-Mohammed** [comment]
search error Request failed with status 500 Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation. type="errorHandler" cause=undefined name="MissingIndexError" stack="MissingIndexError: Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation.\n    at LunrSearchEngine.query (/app/node_modules/@backstage/plugin-search-backend-node/dist/engines/LunrSearchEngine.cjs.js:115:13)\n    at AuthorizedSearchEngine.query (/app/node_modules/@backstage/plugin-search-backend/dist/service/AuthorizedSearchEngine.cjs.js:88:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/node_modules/@backstage/plugin-search-backend/dist/service/router.cjs.js:111:25"

this issue happens when running backstage from docker container and its working perfectly in my system.
