### ISSUE TITLE
💬 RFC: How to get Okta Sign in page directly instead of backstage Sign in page 

### ISSUE THREAD

**Issue by vinaykv23** [backstage/backstage#25798]
### 🔖 Need

backstage "version": "1.28.0"
Implemented okta authentication and once we run the application we are getting "backstage Sign in page" then inside its asking for okta  Sign in

our requirement is once we open backstae url directly goto "okta sign in page" instead of "backstage Sign in page" 

### 🎉 Proposal

How to achieve this functionality

backstage "version": "1.28.0"
Implemented okta authentication and once we run the application we are getting "backstage Sign in page" then inside its asking for okta  Sign in

our requirement is once we open backstae url directly goto "okta sign in page" instead of "backstage Sign in page" 

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by stephenglass** [comment]
https://backstage.io/docs/auth/#sign-in-configuration

It sounds like `enableExperimentalRedirectFlow: true` and a custom sign in page would provide what you're looking for.

**Comment by vinaykv23** [comment]
> enableExperimentalRedirectFlow: true

hi @stephenglass 

enableExperimentalRedirectFlow: true is avoiding login popup, its integrated

![image](https://github.com/user-attachments/assets/2a277f42-e51c-4b3c-9875-0a5646119826)

once we open backstage url its going for backstage login page and then we need to click on sign in button
its going for okta login

![image](https://github.com/user-attachments/assets/eba91f0e-7e2a-4ffb-bc2f-9dca6100aa82)


we need to avoid this step "click on sign in button" in backstage page, directly it should go for okta login page
can you please help me with this

**Comment by benjdlambert** [comment]
I think you would be best off providing your own implementation of the `SignInPage` component which doesn't render any header or options and does the automatic sign in for you.

You can see the default implementation here: 
https://github.com/backstage/backstage/blob/ff7e12632dde109b909948ed693f4da36e91eab5/packages/core-components/src/layout/SignInPage/SignInPage.tsx#L92-L198 

You can most likely copy and paste this, change it around a little bit to not render the buttons or anything and just call login if you're not already logged in etc. You can provide this to `createApp({ compoents: { SignInPage: ... } })` to override it.

**Comment by vinaykv23** [comment]
> export const SingleSignInPage = ({ 
>    provider, 
>    auto, 
>    onSignInSuccess, 
>  }: SingleSignInPageProps) => { 
>    const classes = useStyles(); 
>    const authApi = useApi(provider.apiRef); 
>    const configApi = useApi(configApiRef); 
>    const { t } = useTranslationRef(coreComponentsTranslationRef); 
>   
>    const [error, setError] = useState<Error>(); 
>   
>    // The SignIn component takes some time to decide whether the user is logged-in or not. 
>    // showLoginPage is used to prevent a glitch-like experience where the sign-in page is 
>    // displayed for a split second when the user is already logged-in. 
>    const [showLoginPage, setShowLoginPage] = useState<boolean>(false); 
>   
>    type LoginOpts = { checkExisting?: boolean; showPopup?: boolean }; 
>    const login = async ({ checkExisting, showPopup }: LoginOpts) => { 
>      try { 
>        let identityResponse: BackstageIdentityResponse | undefined; 
>        if (checkExisting) { 
>          // Do an initial check if any logged-in session exists 
>          identityResponse = await authApi.getBackstageIdentity({ 
>            optional: true, 
>          }); 
>        } 
>   
>        // If no session exists, show the sign-in page 
>        if (!identityResponse && (showPopup || auto)) { 
>          // Unless auto is set to true, this step should not happen. 
>          // When user intentionally clicks the Sign In button, autoShowPopup is set to true 
>          setShowLoginPage(true); 
>          identityResponse = await authApi.getBackstageIdentity({ 
>            instantPopup: true, 
>          }); 
>          if (!identityResponse) { 
>            throw new Error( 
>              `The ${provider.title} provider is not configured to support sign-in`, 
>            ); 
>          } 
>        } 
>   
>        if (!identityResponse) { 
>          setShowLoginPage(true); 
>          return; 
>        } 
>   
>        const profile = await authApi.getProfile(); 
>        onSignInSuccess( 
>          UserIdentity.create({ 
>            identity: identityResponse.identity, 
>            authApi, 
>            profile, 
>          }), 
>        ); 
>      } catch (err: any) { 
>        // User closed the sign-in modal 
>        setError(err); 
>        setShowLoginPage(true); 
>      } 
>    }; 
>   
>    useMountEffect(() => login({ checkExisting: true })); 
>   
>    return showLoginPage ? ( 
>      <Page themeId="home"> 
>        <Header title={configApi.getString('app.title')} /> 
>        <Content> 
>          <Grid 
>            container 
>            justifyContent="center" 
>            spacing={2} 
>            component="ul" 
>            classes={classes} 
>          > 
>            <GridItem> 
>              <InfoCard 
>                variant="fullHeight" 
>                title={provider.title} 
>                actions={ 
>                  <Button 
>                    color="primary" 
>                    variant="outlined" 
>                    onClick={() => { 
>                      login({ showPopup: true }); 
>                    }} 
>                  > 
>                    {t('signIn.title')} 
>                  </Button> 
>                } 
>              > 
>                <Typography variant="body1">{provider.message}</Typography> 
>                {error && error.name !== 'PopupRejectedError' && ( 
>                  <Typography variant="body1" color="error"> 
>                    {error.message} 
>                  </Typography> 
>                )} 
>              </InfoCard> 
>            </GridItem> 
>          </Grid> 
>        </Content> 
>      </Page> 
>    ) : ( 
>      <Progress /> 
>    ); 
>  };



> I think you would be best off providing your own implementation of the `SignInPage` component which doesn't render any header or options and does the automatic sign in for you.
> 
> You can see the default implementation here:
> 
> https://github.com/backstage/backstage/blob/ff7e12632dde109b909948ed693f4da36e91eab5/packages/core-components/src/layout/SignInPage/SignInPage.tsx#L92-L198
> 
> You can most likely copy and paste this, change it around a little bit to not render the buttons or anything and just call login if you're not already logged in etc. You can provide this to `createApp({ compoents: { SignInPage: ... } })` to override it.
> 
> It's also possible that you could try the `ProxiedSignInPage` instead, and see how far that get's you, but not 100% sure it's what you're looking for. With `provider='okta'`
> 
> https://github.com/backstage/demo/blob/master/packages/app/src/App.tsx#L54-L56

hi @benjdlambert 

to support code in  "SignInPage.tsx" we require to import below items how to do handle this in our custom code

![image](https://github.com/user-attachments/assets/e1140357-aef4-448e-94b7-aabd5ee9583c)

**Comment by benjdlambert** [comment]
Most of the things in there should already be exported. Otherwise you can copy what you need locally and import from that

**Comment by benjdlambert** [comment]
If you look at the actual bits you need it's pretty small right? You don't need any of the material UI stuff as you're doing it headless, it's just the part that checks if your signed in or not and then does the login for instead.

**Comment by vinaykv23** [comment]
hi @benjdlambert 
I am done with the setup and tried to signin directly to okta login without backstage signin page, but ending with errors
Can you please help me with which part of the code helps to directly call signin and check if already session exists

**Comment by benjdlambert** [comment]
@vinaykv23, after having some chats with other maintainers this morning, I think there's a different way for us to do this.

There's an `auto` prop on the default `SignInPage`, which I think you can use in combination with `enableExperimentalRedirectFlow: true` mentioned in the first comment.

You should be able to do something like this:

```ts
const app = createApp({
  apis,
  plugins: [badgesPlugin],
  components: {
    SignInPage: props => <SignInPage {...props} providers=["github"] auto />,
  },
  ...
})
```

**Comment by vinaykv23** [comment]
hi @benjdlambert 
I tried using the mentioned settings, but its behaving the same

components: {
    SignInPage: props => (
      <SignInPage
        {...props}
        auto
        providers={[
          {
            id: 'okta-auth-provider',
            title: 'Okta Preview',
            message: "Sign in using Okta",
            apiRef: oktaAuthApiRef,
          }
        ]}
      />
    ),
  }

its giving same behavior, we are getting backstage sign in page then need to click on signin to go for okta login
instead we require direct okta login to be displayed

![image](https://github.com/user-attachments/assets/ca5da6d5-5b65-4f1e-820f-d3b288a41a0e)

**Comment by stephenglass** [comment]
@vinaykv23 For the `auto` prop to work you will need to also change `providers` to `provider` and pass in a single provider only (in your case the Okta provider). 

Note that even in this configuration, the user will still briefly see the login screen before being auto redirected. To solve this you would need to create a custom sign in component. I think I'll create a PR to fix this behavior for the future.

**Comment by vinaykv23** [comment]
Thanks @stephenglass

**Comment by benjdlambert** [comment]
@vinaykv23 did the solution work for you? Can we close this issue? :pray:

**Comment by vinaykv23** [comment]
> @vinaykv23 did the solution work for you? Can we close this issue? 🙏

@benjdlambert 
Yes worked, I am closing the ticket

**Comment by vinaykv23** [comment]
hi @benjdlambert 

After implementing the suggested solution we are facing issue with logout, 
once we click on logout its redirecting back to home page

![image](https://github.com/user-attachments/assets/b4adf2dd-1a99-417c-aa44-88b649052588)

![image](https://github.com/user-attachments/assets/ade6e298-adc4-42ed-9f12-5d6522075e18)

**Comment by freben** [comment]
Hey could you make a separate ticket for the sign out specific problem? See #12016 for reference

**Comment by benjdlambert** [comment]
@vinaykv23 I think that you can close this issue, and that the issue you're seeing now is the one that @freben linked.
