### ISSUE TITLE
GitLab Processor: support provider options (similar to GithubReaderProcessor.ts)

### ISSUE THREAD

**Issue by therealadum** [backstage/backstage#2581]
## Add Provider Configuration for GitLab Processor
Currently, the `GitlabReaderProcessor.ts` does not support additional parameters such as target or apiBaseUrl. 

## Possible Implementation
Copy the providerconfig and implementation from GithubReaderProcessor in a way that makes sense for GitlabReaderProcessor.

## Context
Access a self-hosted gitlab instance with a custom url that doesn't match the traditional gitlab.example.com format.

**Comment by freben** [comment]
Yep! Thanks. Do you want to get assigned to it as well?

**Comment by therealadum** [comment]
Works for me! PR incoming

**Comment by freben** [comment]
@therealadum Any progress on this?

The config is now here
https://github.com/backstage/backstage/blob/master/packages/integration/src/gitlab/config.ts

And the URL builders are being moved into the same place by this
https://github.com/backstage/backstage/pull/3489

**Comment by timbonicus** [comment]
The GitLab integration now supports `apiBaseUrl`:

https://backstage.io/docs/integrations/gitlab/locations
