### ISSUE TITLE
💬 RFC: Deprecated Documentation for Search Plugin

### ISSUE THREAD

**Issue by achasek** [backstage/backstage#25826]
### 🔖 Need

Some of the documentation regarding more of Backstage's specific features are now deprecated as of the migration to [the new backend system](https://backstage.io/docs/plugins/new-backend-system/) and are not labeled as such. 

The particular example that I present is with the [Search Plugin](https://backstage.io/docs/features/search/), which seems to be deprecated. The [documentation](https://backstage.io/docs/features/search/getting-started#adding-search-to-the-backend) suggests deprecated dependencies per [this chart](https://backstage.io/docs/backend-system/building-backends/migrating/#the-plugins-in-backstage-repo). 

This makes the implementation and customization of the search plugin more difficult than it needs to be.  

### 🎉 Proposal

To update the documentation in the aforementioned places to reflect the newest changes made to the backend system.

### 〽️ Alternatives

[Other documentation](https://backstage.io/docs/backend-system/building-backends/migrating/#the-plugins-in-backstage-repo) loosely suggests this deprecation, but it is never outright stated in the specific documentation for the search plugin. The other documentation, however, does not fully detail the conventions of the new backend system in the search plugin.

### ❌ Risks

The only risks would be a confusion of what the current convention may be, which is already happening here anyway.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by awanlin** [comment]
Hi @achasek, just wanted to share a couple items:

- This issue tracks the New Backend System documentation updates: https://github.com/backstage/backstage/issues/24195
- This PR tackles updating the Search documentation: https://github.com/backstage/backstage/pull/25621

It's summer time so PR review are much slower than normal.
