### ISSUE TITLE
🐛 Bug Report: publish:bitbucketCloud race condition failure

### ISSUE THREAD

**Issue by msperrin** [backstage/backstage#25821]
### 📜 Description

We've had an intermittent issue where sometimes a user will experience a failure when utilising a template that uses this action. The failure manifests as a 404 error stating that the repository is not found when an attempt to push to the repository is made. When checked afterwards the repository exists and attempting to utilise the 'start-over' function will lead to a subsequent failure for the user as on attempting to create the repo as Bitbucket will respond stating the repository exists.

The issue appears to be a race condition where the Bitbucket Cloud API will return a 200 response for the repo create request but the attempt to use git to push the newly init'd repository returns a 404 failure. Assumption here is that there is something async occurring on the Bitbucket side which leaves the repo in a state where it's not ready to be pushed to but returns a 200 on the create call.

### 👍 Expected behavior

Git push should not fail when using this action if the create repo call succeeds. There is a possibility this needs a retry mechanism as it's not consistent but occurs regularly enough to be fed back to us.

### 👎 Actual Behavior with Screenshots

2024-07-29T12:40:07.000Z Beginning step Publish
2024-07-29T12:40:09.000Z info: Init git repository {dir=C:\Users\<redacted>\AppData\Local\Temp\17f05717-2cd7-44ff-a9bc-a5c5dcd60498}
2024-07-29T12:40:09.000Z info: Adding file {dir=C:\Users\\<redacted>\AppData\Local\Temp\17f05717-2cd7-44ff-a9bc-a5c5dcd60498,filepath=.}
2024-07-29T12:40:09.000Z info: Committing file to repo {dir=C:\Users\\<redacted>\AppData\Local\Temp\17f05717-2cd7-44ff-a9bc-a5c5dcd60498,message=Initial commit}
2024-07-29T12:40:09.000Z info: Creating new remote {dir=C:\Users\\<redacted>\AppData\Local\Temp\17f05717-2cd7-44ff-a9bc-a5c5dcd60498,remote=origin,url= https://<redacted>@bitbucket.org/<redacted>/test-repo222.git, Opens in a new window}
2024-07-29T12:40:09.000Z info: Pushing directory to remote {dir=C:\Users\\<redacted>\AppData\Local\Temp\17f05717-2cd7-44ff-a9bc-a5c5dcd60498,remote=origin}
2024-07-29T12:40:10.000Z error: Failed to push to repo {dir=C:\Users\\<redacted>\AppData\Local\Temp\17f05717-2cd7-44ff-a9bc-a5c5dcd60498, remote=origin}
2024-07-29T12:40:10.000Z Error: HTTP Error: 404 Not Found {data={"statusCode":404,"statusMessage":"Not Found","response":"You may not have access to this repository or it no longer exists in this workspace. If you think this repository exists and you have access, make sure you are authenticated.\n"}}
    at Git.push (C:\test\bsdemo2\node_modules\@backstage\plugin-scaffolder-node\src\scm\git.ts:288:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.initRepoAndPush (C:\test\bsdemo2\node_modules\@backstage\plugin-scaffolder-node\src\actions\gitHelpers.ts:74:3)
54    at Object.handler (C:\test\bsdemo2\node_modules\@backstage\plugin-scaffolder-backend-module-bitbucket-cloud\src\actions\bitbucketCloud.ts:253:28)
55    at NunjucksWorkflowRunner.executeStep (C:\test\bsdemo2\node_modules\@backstage\plugin-scaffolder-backend\src\scaffolder\tasks\NunjucksWorkflowRunner.ts:366:9)
56    at NunjucksWorkflowRunner.execute (C:\test\bsdemo2\node_modules\@backstage\plugin-scaffolder-backend\src\scaffolder\tasks\NunjucksWorkflowRunner.ts:498:9)
57    at TaskWorker.runOneTask (C:\test\bsdemo2\node_modules\@backstage\plugin-scaffolder-backend\src\scaffolder\tasks\TaskWorker.ts:176:26)
58    at async run (C:\test\bsdemo2\node_modules\p-queue\dist\index.js:163:29)

### 👟 Reproduction steps

Attempt to scaffold a template using which publishes to bitbucket.org. The issue is intermittent so multiple attempts are required to replicate. 

### 🖥️ Your Environment

  @backstage/app-defaults                                          1.5.9
  @backstage/backend-app-api                                       0.8.0
  @backstage/backend-common                                        0.23.3
  @backstage/backend-defaults                                      0.4.1
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.15
  @backstage/backend-plugin-api                                    0.7.0
  @backstage/backend-tasks                                         0.5.27
  @backstage/backend-test-utils                                    0.4.4
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.26.11
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.1
  @backstage/core-compat-api                                       0.2.7
  @backstage/core-components                                       0.13.10, 0.14.9
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.36
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.7
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.29
  @backstage/integration                                           1.13.0
  @backstage/plugin-api-docs                                       0.11.7
  @backstage/plugin-app-backend                                    0.3.71
  @backstage/plugin-app-node                                       0.1.22
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.14
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.5
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.5
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.17
  @backstage/plugin-auth-backend-module-github-provider            0.1.19
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.19
  @backstage/plugin-auth-backend-module-google-provider            0.1.19
  @backstage/plugin-auth-backend-module-guest-provider             0.1.8
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.17
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.15
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.15
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.3
  @backstage/plugin-auth-backend                                   0.22.9
  @backstage/plugin-auth-node                                      0.4.17
  @backstage/plugin-auth-react                                     0.1.4
  @backstage/plugin-bitbucket-cloud-common                         0.2.21
  @backstage/plugin-catalog-backend-module-logs                    0.0.1
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.30
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.20
  @backstage/plugin-catalog-backend                                1.24.0
  @backstage/plugin-catalog-common                                 1.0.25
  @backstage/plugin-catalog-graph                                  0.4.7
  @backstage/plugin-catalog-import                                 0.12.1
  @backstage/plugin-catalog-node                                   1.12.4
  @backstage/plugin-catalog-react                                  1.12.2
  @backstage/plugin-catalog                                        1.21.1
  @backstage/plugin-events-node                                    0.3.8
  @backstage/plugin-home-react                                     0.1.15
  @backstage/plugin-home                                           0.7.8
  @backstage/plugin-org                                            0.6.27
  @backstage/plugin-permission-backend                             0.5.46
  @backstage/plugin-permission-common                              0.8.0
  @backstage/plugin-permission-node                                0.8.0
  @backstage/plugin-permission-react                               0.4.24
  @backstage/plugin-proxy-backend                                  0.5.3
  @backstage/plugin-scaffolder-backend-module-azure                0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.12
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.14
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.12
  @backstage/plugin-scaffolder-backend-module-github               0.4.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.4
  @backstage/plugin-scaffolder-backend                             1.23.0
  @backstage/plugin-scaffolder-common                              1.5.4
  @backstage/plugin-scaffolder-node-test-utils                     0.1.9
  @backstage/plugin-scaffolder-node                                0.4.8
  @backstage/plugin-scaffolder-react                               1.10.0
  @backstage/plugin-scaffolder                                     1.23.0
  @backstage/plugin-search-backend-module-catalog                  0.1.28
  @backstage/plugin-search-backend-module-pg                       0.5.32
  @backstage/plugin-search-backend-module-techdocs                 0.1.27
  @backstage/plugin-search-backend-node                            1.2.27
  @backstage/plugin-search-backend                                 1.5.14
  @backstage/plugin-search-common                                  1.2.13
  @backstage/plugin-search-react                                   1.7.13
  @backstage/plugin-search                                         1.4.14
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.9
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.12
  @backstage/plugin-techdocs-node                                  1.12.8
  @backstage/plugin-techdocs-react                                 1.2.6
  @backstage/plugin-techdocs                                       1.10.7
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.10
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.9
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Hmm what a wonderful case of eventual consistency :tada:

I wonder if we can add some form of delay here, or at least poll and endpoint for it to be available or something before we try to push to it?

Do you want to contribute something to the action? :pray:

**Comment by msperrin** [comment]
> Hmm what a wonderful case of eventual consistency 🎉
> 
> I wonder if we can add some form of delay here, or at least poll and endpoint for it to be available or something before we try to push to it?
> 
> Do you want to contribute something to the action? 🙏

Did a bit more digging after logging the issue and I've come to the conclusion that the Bitbucket API is not a reliable narrator for this - inserting a GET request to the API for the repository returns a 200 but the git push can still return a 404.

I've tried adding a 5 second sleep and that seems to give enough time for this to work (I haven't been able replicate the issue when this is set) - I wasn't sure if this would be an acceptable solution but if it is I'm happy to submit it.

The other idea I had was to use something maybe adding some retry logic around the git commands but that would mean modifying initRepoAndPush which feels a bit dirty for something which I would presume to be only affecting Bitbucket Cloud.

**Comment by benjdlambert** [comment]
You could add a retry in the actual action itself, wrapping the `initRepoAndPush` I guess?

Might be worth a look around the other actions to see if there's any of this waiting in others and see if it's worth pushing it down to the `initRepoAndPush` anyways?

**Comment by benjdlambert** [comment]
Just another followup note here, is that @freben did some digging into a separate issue and it appears that in GitHub documentation also it says that if you create a repository using the API, you should wait at least 1 second before calling any of the read API's 🙃 so I guess we can implement this at the `initRepoAndPush` level so that it rolls out to all providers for free :tada:
