### ISSUE TITLE
🐛 Bug Report:  `issuer` field on jwks type backend.auth.extermalAccess app-config key are not working 

### ISSUE THREAD

**Issue by lulala1126** [backstage/backstage#25829]
### 📜 Description

Hi team, we are working to migrate our backend to the new backend system, and we decided to use JWKS Token auth as the backend default auth.externalAccess. 
One time, we set the wrong issuer by accident, so the passed JWTs do not have an iss claim that matches the specified issuer, but the whole backend is still working normally, request with the Authorization can be processed successfully. 
We are very curious, so we tried to remove the wrong issuer to see what happens. we found the backend still working normally even without the issuer on the JWKS type externalAccess.

### 👍 Expected behavior

It should fail/warning when the issuer is not match iss claim on the JWTs.

### 👎 Actual Behavior with Screenshots

Nothing, it just working normal.

### 👟 Reproduction steps

app-config.yaml 
```
backend:
  auth:
    externalAccess:
      - type: jwks
        options:
          url:  https://test.example.net/api/auth/.well-known/jwks.json
```
deploy backend and test API call:
`curl -H "Authorization: Bearer JVuer554QXmKfXhrty5"  -X GET "https://test.example.net/api/dummy"`

### 🖥️ Your Environment

OS:   Darwin 23.5.0 - darwin/arm64
node: v20.12.2
yarn: 1.22.19
cli:  0.26.11 (installed)
backstage:  1.28.0

Dependencies:
  @backstage/app-defaults                                          1.5.8
  @backstage/backend-app-api                                       0.7.9, 0.8.0
  @backstage/backend-common                                        0.23.2, 0.23.3
  @backstage/backend-defaults                                      0.3.3, 0.4.1
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.15
  @backstage/backend-plugin-api                                    0.6.21, 0.7.0
  @backstage/backend-tasks                                         0.5.27
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.26.11
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.0
  @backstage/core-compat-api                                       0.2.7
  @backstage/core-components                                       0.14.9
  @backstage/core-plugin-api                                       1.9.3
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.7
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.29
  @backstage/integration                                           1.13.0
  @backstage/plugin-api-docs                                       0.11.7
  @backstage/plugin-app-backend                                    0.3.71
  @backstage/plugin-app-node                                       0.1.22
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.14
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.5
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.5
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.17
  @backstage/plugin-auth-backend-module-github-provider            0.1.19
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.19
  @backstage/plugin-auth-backend-module-google-provider            0.1.19
  @backstage/plugin-auth-backend-module-guest-provider             0.1.8
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.17
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.15
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.15
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.3
  @backstage/plugin-auth-backend                                   0.22.9
  @backstage/plugin-auth-node                                      0.4.17
  @backstage/plugin-auth-react                                     0.1.4
  @backstage/plugin-bitbucket-cloud-common                         0.2.21
  @backstage/plugin-catalog-backend-module-aws                     0.3.17
  @backstage/plugin-catalog-backend-module-openapi                 0.1.40
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.20
  @backstage/plugin-catalog-backend                                1.24.0
  @backstage/plugin-catalog-common                                 1.0.25
  @backstage/plugin-catalog-graph                                  0.4.7
  @backstage/plugin-catalog-import                                 0.12.1
  @backstage/plugin-catalog-node                                   1.12.4
  @backstage/plugin-catalog-react                                  1.12.2
  @backstage/plugin-catalog                                        1.21.1
  @backstage/plugin-events-node                                    0.3.8
  @backstage/plugin-home-react                                     0.1.15
  @backstage/plugin-home                                           0.7.7
  @backstage/plugin-kubernetes-common                              0.8.1
  @backstage/plugin-org                                            0.6.27
  @backstage/plugin-permission-common                              0.7.14, 0.8.0
  @backstage/plugin-permission-node                                0.7.32, 0.8.0
  @backstage/plugin-permission-react                               0.4.24
  @backstage/plugin-proxy-backend                                  0.5.3
  @backstage/plugin-scaffolder-backend-module-azure                0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.12
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.14
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.12
  @backstage/plugin-scaffolder-backend-module-github               0.3.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.4
  @backstage/plugin-scaffolder-backend                             1.22.11
  @backstage/plugin-scaffolder-common                              1.5.4
  @backstage/plugin-scaffolder-node                                0.4.8
  @backstage/plugin-scaffolder-react                               1.10.0
  @backstage/plugin-scaffolder                                     1.23.0
  @backstage/plugin-search-backend-module-catalog                  0.1.28
  @backstage/plugin-search-backend-module-pg                       0.5.32
  @backstage/plugin-search-backend-module-techdocs                 0.1.27
  @backstage/plugin-search-backend-node                            1.2.27
  @backstage/plugin-search-backend                                 1.5.14
  @backstage/plugin-search-common                                  1.2.13
  @backstage/plugin-search-react                                   1.7.13
  @backstage/plugin-search                                         1.4.14
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.9
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.12
  @backstage/plugin-techdocs-node                                  1.12.8
  @backstage/plugin-techdocs-react                                 1.2.6
  @backstage/plugin-techdocs                                       1.10.7
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.9
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.8
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
When the `options.issuer` is not set for your entry, enforcement of the `iss` is completely disabled. So when there's no such configuration key present, it's expected that your tokens will pass with any `iss` given, as long as they're signed by any of the keys in the jwks.

But it seems that you did have an `options.issuer`, but a token not matching that got accepted? I'd have to look into that.

**Comment by freben** [comment]
I don't think I can reproduce this.

Started a local testing jwks server on port 8080 and added the following to my config:

```yaml
backend:
  auth:
    externalAccess:
      - type: jwks
        options:
          url: http://localhost:8080/.well-known/jwks.json
```

Trying to make a dummy query:

```
curl -i 'http://localhost:7007/api/catalog/entity-facets?facet=kind' -H 'Authorization: Bearer <token>'
```

🟢 OK, dummy query works

Added the correct iss to the config:

```yaml
backend:
  auth:
    externalAccess:
      - type: jwks
        options:
          url: http://localhost:8080/.well-known/jwks.json
          issuer: https://example.com
```

🟢 OK, dummy query works

Set an invalid iss to the config:

```yaml
backend:
  auth:
    externalAccess:
      - type: jwks
        options:
          url: http://localhost:8080/.well-known/jwks.json
          issuer: https://not-the-example.com
```

🔴  OK, dummy query returns 401

**Comment by lulala1126** [comment]
> I don't think I can reproduce this.
> 
> Started a local testing jwks server on port 8080 and added the following to my config:
> 
> ```yaml
> backend:
>   auth:
>     externalAccess:
>       - type: jwks
>         options:
>           url: http://localhost:8080/.well-known/jwks.json
> ```
> 
> Trying to make a dummy query:
> 
> ```
> curl -i 'http://localhost:7007/api/catalog/entity-facets?facet=kind' -H 'Authorization: Bearer <token>'
> ```
> 
> 🟢 OK, dummy query works
> 
> Added the correct iss to the config:
> 
> ```yaml
> backend:
>   auth:
>     externalAccess:
>       - type: jwks
>         options:
>           url: http://localhost:8080/.well-known/jwks.json
>           issuer: https://example.com
> ```
> 
> 🟢 OK, dummy query works
> 
> Set an invalid iss to the config:
> 
> ```yaml
> backend:
>   auth:
>     externalAccess:
>       - type: jwks
>         options:
>           url: http://localhost:8080/.well-known/jwks.json
>           issuer: https://not-the-example.com
> ```
> 
> 🔴 OK, dummy query returns 401

Hi @freben, that's very weird, thanks for the confirmation, I've rechecked on our backend.
