### ISSUE TITLE
🐛 Bug Report: Not able to ingest a group that ends with a period

### ISSUE THREAD

**Issue by chancethecoder** [backstage/backstage#25828]
### 📜 Description

If the name of the group read from MSGraph ends with a period (ex. "Some Group Name."), the group will not be created properly.

### 👍 Expected behavior

The group should be created.

### 👎 Actual Behavior with Screenshots

The group was not created, and the following error message was found in the refresh_state table.

```sql
select * from refresh_state
```

> {"metadata": ... "name":"data_engineering_dept.","description":""},"apiVersion":"backstage.io/v1alpha1","kind":"Group","spec":{"type":"team","profile":{"displayName":"Data Engineering Dept.","email": ...
> ... [{"name":"InputError","message":"Policy check failed for group:default/data_engineering_dept.; caused by Error: \"metadata.name\" is not valid; expected a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total but found \"data_engineering_dept.\". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md","cause":{"name":"Error","message":"\"metadata.name\" is not valid; expected a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total but found \"data_engineering_dept.\". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md","stack":"Error: \"metadata.name\" is not valid; expected a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total but found \"data_engineering_dept.\". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md

### 👟 Reproduction steps

1. Integrate with [MSGraph](https://backstage.io/docs/integrations/azure/org/)
2. Create provider configuration with filter. ex) `group.filter=displayName eq 'Data Engineering Dept.'`
4. Run the backstage backend

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Zaperex** [comment]
Entity names can't being or end with a non-alphanumerical character, so you will most likely need to provide custom group transformers to mutate the name of your group to the supported format (this WILL override the [default transformers](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/src/microsoftGraph/defaultTransformers.ts) though). 

If you're using the new backend system, you can create a backend module with pluginId: `catalog`, and use the [`microsoftGraphOrgEntityProviderTransformExtensionPoint`](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/src/module/catalogModuleMicrosoftGraphOrgEntityProvider.ts#L81) to register your transformers.

**Comment by chancethecoder** [comment]
Thank you @Zaperex

I'll try custom group transformer. 👍🏼
