### ISSUE TITLE
🐛 Bug Report: Importing a new backend module when following the docs fails

### ISSUE THREAD

**Issue by arvid-digg** [backstage/backstage#25862]
### 📜 Description

When I create a new backend module with `yarn new` and then try to import it according to [the docs](https://backstage.io/docs/backend-system/architecture/modules), I get an ` Cannot find module` error when running `yarn tsc`. 

### 👍 Expected behavior

The plugin was imported and no errors from `yarn tsc`.

### 👎 Actual Behavior with Screenshots

 Cannot find module

![image](https://github.com/user-attachments/assets/2d809af0-a275-473f-b464-6ad8acc65cf7)

### 👟 Reproduction steps

1. Create a new backend module with `yarn new`. I used `permission` as plugin id and `custom-policy` as module id.
2. Import the backend module, according to [the docs](https://backstage.io/docs/backend-system/architecture/modules), add `backend.add(import('backstage-plugin-permission-backend-module-custom-policy'));` to your `index.ts` backend app.
3. Run `yarn tsc`, which now will fail since it can't find the module.

![image](https://github.com/user-attachments/assets/7cf72b5c-5534-4ecf-b397-bdd5feff98d8)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by fedy97** [comment]
mmmh which version of backstage are you running? I am not reproducing it. You should have the import automatically added in your index.ts

Try to change from `backstage-plugin... to  `@backstage/plugin..` in your index.ts

**Comment by awanlin** [comment]
Yup, there's a typo in the docs, @fedy97 is close but this:

`backend.add(import('backstage-plugin-permission-backend-module-custom-policy'));`

Should be this:

`backend.add(import('@internal/backstage-plugin-permission-backend-module-custom-policy'));

When you use `yarn new` to create anything it will default to `@internal` as the package org unless you have changed that command or passed it in.

**Comment by fedy97** [comment]
> When you use `yarn new` to create anything it will default to `@internal` as the package org unless you have changed that command or passed it in.

Oh okay thanks, I was looking at this repo where we have `--scope backstage` but yes default is internal

**Comment by alper98** [comment]
What version of the CLI do you use?

Any backend plugin/module should be auto added to your backend https://github.com/backstage/backstage/pull/25376

**Comment by arvid-digg** [comment]
@alper98 currently using `@backstage/cli 0.26.9` so it seems I don't have the latest version of the CLI with the changes you mentioned. The docs are still incorrect though.

**Comment by awanlin** [comment]
Got a PR to address the docs: https://github.com/backstage/backstage/pull/25937
