### ISSUE TITLE
🚀 Feature: Scaffolder - RepoUrlPicker Support autocompletion of GitHub Organizations and Repos

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#25873]
### 🔖 Feature description

Allow the logged in user to fetch organizations and repositories using GitHub API calls

### 🎤 Context

Currently, the RepoUrlPicker only supports manually entering the organization and repository for GitHub. In our use case, we need to fetch the organizations and repositories the logged in user has access to from the GitHub API.

### ✌️ Possible Implementation

There are two similar integrations for Bitbucket #25132 and GitLab #25842 

Proposing we follow the footsteps of @benjidotsh as @benjdlambert proposed [here](https://github.com/backstage/backstage/issues/25744#issuecomment-2249930130) ideally using a Github App

In our use-case we have one large organization where some users have write access to thousands of repositories and are looking for guidance from the community on the best way to implement this for cases like this. 

@benjdlambert looks like you tried implementing a similar feature [here](https://github.com/backstage/backstage/pull/25132#issuecomment-2161205871) wondering if you were able to get something working using a Github App any guidance would be appreciated!  

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
So I think the original thought is that you would have to probably manually enable to use the `integrations` config, and it would prefer to use the user token provided from the frontend, but if there wasn't one and the config was enabled, it would use the `GitHub` app or `integrations.token` to retrieve the details for the requested autocomplete resource.

Does this make sense?

**Comment by msperrin** [comment]
I would add that this would be a good feature for all the SCM integrations, albeit implemented with there specific implementation, e.g. for Bitbucket returning the workspace(s)/project(s).

**Comment by regicsolutions** [comment]
> So I think the original thought is that you would have to probably manually enable to use the `integrations` config, and it would prefer to use the user token provided from the frontend, but if there wasn't one and the config was enabled, it would use the `GitHub` app or `integrations.token` to retrieve the details for the requested autocomplete resource.
> 
> Does this make sense?

Hey @benjdlambert Thanks for the reply, Can you explain what you mean by manually enabling to use the integrations config?

Assuming your referring to the USER_OAUTH_TOKEN thats documented [here](https://backstage.io/docs/features/software-templates/writing-templates#using-the-users-oauth-token) ?

Does look like GitHub has API endpoints to fetch both [Organizations](https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#list-organizations-for-the-authenticated-user) and [Repositories](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-the-authenticated-user) for the authenticated user.

**Comment by fedy97** [comment]
> > So I think the original thought is that you would have to probably manually enable to use the `integrations` config, and it would prefer to use the user token provided from the frontend, but if there wasn't one and the config was enabled, it would use the `GitHub` app or `integrations.token` to retrieve the details for the requested autocomplete resource.
> > Does this make sense?
> 
> Hey @benjdlambert Thanks for the reply, Can you explain what you mean by manually enabling to use the integrations config?
> 
> Assuming your referring to the USER_OAUTH_TOKEN thats documented [here](https://backstage.io/docs/features/software-templates/writing-templates#using-the-users-oauth-token) ?
> 
> Does look like GitHub has API endpoints to fetch both [Organizations](https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#list-organizations-for-the-authenticated-user) and [Repositories](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-the-authenticated-user) for the authenticated user.

Hi @regicsolutions I can try to answer this. I think (correct me if I am wrong @benjdlambert ) he is referring to the fact that, if the user does not authenticate using the frontend (with `USER_OAUTH_TOKEN`) the implementation could fallback to the token provided to `integrations`. Right now, my PR regarding autocomplete in Gitlab does not fallback to integrations, and neither does the Bitbucket one.

**Comment by benjdlambert** [comment]
Yeh that's correct. For reference the `USER_OAUTH_TOKEN` just the pattern of collecting the token in the frontend, currently done in a few places, but it already happens in the `RepoUrlPicker` and we took advantage of that fact to automatically populate a secret if needed, but you don't have to use that secret if you don't want to.

The idea is, that in the `autocomplete` handlers, you can pass a `token` which will be used by default. We would need to add additional logic here, which can disable this logic and use the `integrations` config instead which is in the backend.

Thinking something like `scaffolder.autocomplete.useBackendConfig` or `scaffolder.autocomplete.useIntegrationsConfig`, please if you have any other ideas, go ahead :)

Not sure if this config belongs on the `ui:options` in the template, or if it belongs in the `app-config.yaml` yet. Is there a use case that this should be configured per template, or is it more of a company wide global option for the scaffolder are some things to think about I guess.

We also might want a config option to disable the token lookup in the frontend, and that combined with the other option of using the `integrations` config is probably what people will do if they just want to use the backend config that is already listed.
