### ISSUE TITLE
🚀 Feature: Secret Provider Service for Backend Plugins

### ISSUE THREAD

**Issue by zeshanziya** [backstage/backstage#25885]
### 🔖 Feature description

Introduce a Secret Provider Service in Backstage that allows backend plugins to retrieve secrets from various sources, organized under different accounts. This service will provide a centralized solution for managing secrets, supporting account-based grouping to facilitate different credentials for various clients. Backend plugins will request secrets using secretKet and an optional entity reference or secret account, allowing the service to deliver secrets from the appropriate account or default account if no reference is provided.

### 🎤 Context

We are an agency working with multiple clients. We use several plugins, such as Sentry, New Relic, and Jira. Currently, they are set up using the proxy plugin. Since each client may have its own Sentry or other service accounts, we needed a way to pass secrets dynamically to the proxy plugin based on the entity reference. Therefore, we are using a modified version of the proxy-backend plugin, which supports multiple secrets based on the component.

Some time ago, I raised a [PR](https://github.com/backstage/backstage/pull/21530) and an [Issue](https://github.com/backstage/backstage/issues/21528)  to support dynamic secret replacement for the proxy plugin. However, it was turned down. Please see the reason below.

<img width="859" alt="image" src="https://github.com/user-attachments/assets/a2cea7ed-b33e-479e-ac45-4ac9cb4be7bb">

To address this, we implemented a concept of "secret accounts," where secrets are grouped under accounts and can be requested based on annotations specified in the Backstage entity.

By introducing the annotation `backstage.io/secret-account` for entities, backend plugins can specify the secret account they need. The Secret Provider Service will then identify the correct account and provide the required secrets. If no annotation is present, the service will default to providing secrets from the default account.
 
So in the future, once each frontend plugin has its own backend plugin and manages secrets on its own, it will be challenging for us to support the multiple secrets feature.

Example secret configuration:
```yaml
secrets:
  default:
    sentry_token: 'abc-token'
    new_relic_user_key: 'relic-token'
    jira_token: 'jira-token'
  account1:
    sentry_token: 'abc-token-1'
    new_relic_user_key: 'relic-token-1'
    jira_token: 'jira-token-1'
  account2:
    sentry_token: 'abc-token-2'
    new_relic_user_key: 'relic-token-2'
    jira_token: 'jira-token-2'
```

### ✌️ Possible Implementation

We built a plugin called `secret-manager` which exposes a service `secretServiceRef` and an extension point `secretManagerExtensionPoint` for registering a secret provider.

As of now, we have built three provider plugins:

1. Initially, we started with a `secret-provider-config` plugin, which provides secrets from app-config.yaml.
2. We then built another plugin, `secret-provider-db`, as we needed a way to create and store secrets using a UI. This avoids the need to change the app-config.yaml whenever we onboard a new component with its own Sentry or New Relic account. This plugin provides an interface to create secret accounts and their secrets and then exports a provider based on the above-mentioned extension point.
3. Since Backstage is primarily an aggregator and rarely the source of truth, we built another plugin `secret-provider-onepassword` that exposes a provider supplying secrets from 1Password. It utilizes the 1Password service account feature to manage secrets from 1Password.

Example of backend plugin requesting a secret:
```ts
secretService.getSecret(options: SecretParams)
```

Where `SecretParams` is:
```ts
export type SecretParams = {
  secretKey?: string;
  accountName?: string;
  entityRef?: string;
};
```

Plugins can pass a `secret key` and its account directly to get a secret, or just a secret key to fetch from the default account. If `entityRef` is passed, it will try to identify the account secret by the annotation `backstage.io/secret-account` and provide the secret from that account. If the annotation is not present, it will default to the default account.

Exploring how we can integrate this feature would be a significant plus for Backstage. I would be happy to write a BEP if this feature makes sense.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
We do want to consider more structured integrations with different secret provider systems. It also ties into the config system, where it would be great to out-of-the-box just type `password: ${vault:my_password_secret_key}` or whatnot.

It'll take a fair bit of consideration and will be cross cutting. Given that, I don't think we're ready to tackle it in the near term as we finish off some of the other large overhauls (auth, frontend system, backend system, ...). Later on though, we do want to look into the bigger picture of what integrations look like overall.

Might be best to hold on to this idea for a bit, and then down the line we'll all keep it in mind as we start forming the BEPs around these advancements. For now, I hope you're unblocked in being at least able to do these things in a bespoke way, instead of through a framework feature.

**Comment by zeshanziya** [comment]
Thanks @freben  for the detailed response! I understand the current priorities and the need to focus on the major overhauls. I appreciate that you're keeping this in mind for future BEPs. In the meantime, I'll work with the bespoke solutions.

Looking forward to seeing how the bigger picture of integrations evolves. Please let me know if there's any way I can contribute to this discussion down the line.
