### ISSUE TITLE
💬 RFC: Integrate Sentry Logging into Backstage Logger Service

### ISSUE THREAD

**Issue by zeshanziya** [backstage/backstage#25880]
### 🔖 Need

We needed to enhance our logging infrastructure by integrating Sentry for advanced error tracking and monitoring. We achieved this by overriding the root logger service as below.

Is the current approach of overriding the logger service the best way to add Sentry transport?

```ts
import {
  coreServices,
  createServiceFactory,
} from '@backstage/backend-plugin-api';
import { format, transports } from 'winston';
import Sentry from 'winston-sentry-log';
import { WinstonLogger } from '@backstage/backend-defaults/rootLogger';
import { createConfigSecretEnumerator } from '@backstage/backend-defaults/rootConfig';

export default createServiceFactory({
  service: coreServices.rootLogger,
  deps: {
    config: coreServices.rootConfig,
  },
  async factory({ config }) {
    const trasporters: any[] = [new transports.Console()];
    const logConfig = config.getOptionalConfig('logging.sentry');
    if (logConfig && logConfig.getBoolean('enabled')) {
      trasporters.push(
        new Sentry({
          config: {
            dsn: logConfig.getString('dsn'),
            environment: logConfig.getString('environment'),
            initialScope: {
              tags: { apptype: 'backend' },
            },
          },
          level: 'warn',
        }),
      );
    }

    const logger = WinstonLogger.create({
      meta: {
        service: 'backstage',
      },
      level: process.env.LOG_LEVEL || 'info',
      format:
        process.env.NODE_ENV === 'production'
          ? format.json()
          : WinstonLogger.colorFormat(),
      transports: trasporters,
    });

    const secretEnumerator = await createConfigSecretEnumerator({
      logger,
    });
    logger.addRedactions(secretEnumerator(config));
    config.subscribe?.(() => logger.addRedactions(secretEnumerator(config)));

    return logger;
  },
});

```

Instead of completely overriding the root logger service, Is there any way to just add the new transport? This approach ensures that any updates or changes to the root logger service are automatically inherited, reducing the need for manual checks and updates.

### 🎉 Proposal

The current approach involves overriding the root logger service and manually adding the Sentry transport. However, to streamline this process and maintain alignment with updates to the root logger service, we propose investigating a method to extend the root logger service to allow for adding new transports. This could potentially be achieved through extension points or a more dynamic configuration.

### 〽️ Alternatives

NA

### ❌ Risks

NA

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by freben** [comment]
In the near term, yes, I think what you have looks right. There are some improvements being planned in terms of being able to compose features onto services (like for example making it possible to add just one more transport to the existing logger), but it's not quite there yet. Keep your eye on the release notes in the future and you may see movement in this direction.
