### ISSUE TITLE
🚀 Feature: Allow publish:gerrit action to receive user credentials

### ISSUE THREAD

**Issue by marianomoura** [backstage/backstage#25891]
## Objective
Enhance the createPublishGerritAction to accept user credentials, similar to the existing createPublishGitlabAction. This would allow for more flexible and secure integration with Gerrit, particularly in scenarios where user authentication is required for specific operations.

## Current Behavior
Currently, the createPublishGerritAction in Backstage does not support directly receiving authentication tokens or user credentials. This limitation restricts its use in environments where operations need to be authenticated using specific user tokens.

### 🎤 Context

Consider a scenario where developers initiate the createPublishGerritAction using their authenticated sessions. By requiring individual authentication tokens, the system can verify each user's identity and permissions. This ensures that only authorized personnel have the ability to create repositories, aligning with best practices for secure access control and preventing unauthorized changes within the Gerrit environment.

### ✌️ Possible Implementation

The proposal is to extend the functionality of createPublishGerritAction to include an authentication token input, similar to the createPublishGitlabAction. Below are the suggested details for the new implementation:

- Add a new input field in the schema named token, which will accept a string representing the authentication token.
- The token will be used to authenticate all operations with Gerrit, ensuring that actions are performed within the user's permission boundaries.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes

**Comment by freben** [comment]
You can for sure add a secret field that can hold a token, short term. But it seems pretty technical and inconvenient from an end user's standpoint. Maybe the bigger picture is, is there a way that we could interact better overall with gerrit auth? I do not use that product myself. For the other integrations such as github, we negotiate oauth tokens behind the scenes using proper integrations that get passed through down. If there's some work that could be contributed toward making that form of a smooth experience for gerrit users as well, then that would be valuable. 🙏
