### ISSUE TITLE
🚀 Feature: Support entity kind property for page entity theme

### ISSUE THREAD

**Issue by shmaram** [backstage/backstage#25902]
### 🔖 Feature description

Currently, if we wish to override a page theme we can do it only for "type" property. (see code example bellow) 

```
export const unifiedTheme = createUnifiedTheme({
  palette: palettes.dark,
  defaultPageTheme: 'home',
  pageTheme: {
    team: genPageTheme({ colors: ['#0E6717', '#1CCD2E'], shape: shapes.wave }), //<-- works
    group: genPageTheme({ colors: ['#0E6717', '#1CCD2E'], shape: shapes.wave }), //<-- works
    system: genPageTheme({ colors: ['#0E6717', '#1CCD2E'], shape: shapes.wave }), //<-- doesn't work
  },
});
```

I would like to be able to make overrides using Kind property also 

### 🎤 Context

With the current implementation, I cannot override "System" or "Domain" entities. I can do it only by adding the "Type" property to the entity, which is not used currently at all.

Also, I wish to have an alignment with the page header color per Kind, as currently, I have many "Resource" entities with different types, and I need to duplicate the code for each type. Also adding new types will be tedious as I need to keep duplicating the theme override for each new type added

### ✌️ Possible Implementation

Under [EntityLayout.tsx](plugins/catalog/src/components/EntityLayout/EntityLayout.tsx), there is a Page element that currently check for the given type and defaults to "home" for the `themeId` property. 

We can add a new logic that first falls back to check for Kind (after the type is not found) and then falls back to "home" if needed (check if that is a definition for the kind)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Yep! 👍 can probably get rid of the `'home'` defaulting too in the `Page` component. It should really be up to the theme to decide what is the default page theme. It might take a bit of consideration how to roll this out, but I don't think it's gonna be too bad, especially since it's a visual change.
