### ISSUE TITLE
🐛 Bug Report: BackstageSidebarSubmenu is not availble under BackstageComponentsNameToClassKey core components

### ISSUE THREAD

**Issue by gayatrisamant18** [backstage/backstage#25915]
### 📜 Description

I am trying to add custom styles using custom theme for  MyGroupsSidebarItem which provides quick access to the group(s) the logged in user is a member of directly in the sidebar.
This uses the BackstageSidebarSubmenu which is not available under BackstageComponentsNameToClassKey core components.

### 👍 Expected behavior

BackstageSidebarSubmenu should be available to apply custom styles

### 👎 Actual Behavior with Screenshots

<img width="754" alt="Screenshot 2024-08-06 at 2 22 33 PM" src="https://github.com/user-attachments/assets/00514161-1c7f-46ee-8121-a25c4361ee01">

### 👟 Reproduction steps

Followed the steps to MySquad .
https://www.npmjs.com/package/@backstage/plugin-org/v/0.0.0-nightly-20220607024221

Try to apply custom styles to the SidebarSubmenu using Unified theme.
It doesnt work

### 🖥️ Your Environment

This is have produced in my local
<img width="701" alt="Screenshot 2024-08-06 at 2 29 11 PM" src="https://github.com/user-attachments/assets/224a1ef5-8480-42b5-acb2-a2b1283fc7fb">
Unable to set custom styles to this component

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by darylgraham** [comment]
May be fixed under #25618

**Comment by gayatrisamant18** [comment]
@darylgraham  Any ETA, when it will be merged

**Comment by darylgraham** [comment]
> @darylgraham Any ETA, when it will be merged

Not sure sorry. I’m not involved in that PR, I was just watching it because I also ran into the same issue as you.

**Comment by darylgraham** [comment]
@gayatrisamant18 this should be fixed with v1.31.0

**Comment by Rugvip** [comment]
Closing as fixed by #25618
