### ISSUE TITLE
🐛 Bug Report: TechDocs for split monorepo hosted on AWS S3 not creating correct paths for child components

### ISSUE THREAD

**Issue by CodeMajik** [backstage/backstage#25917]
### 📜 Description

404 when trying to read docs in Docs tab for catalog entries of child components of a split monorepo.
I have created a root Location type catalog-info.yaml for the repo.
I have created multiple sub components of type Component and an mkdocs.yml and docs folder per sub component.
The root mkdocs.yml is referencing each child mkdocs.yml

### 👍 Expected behavior

Generate a catalog entry for each child component.
Generate and publish all docs to S3 bucket in AWS.
Clicking the Docs tab for each child component should allow us to read it's respective documentation.

### 👎 Actual Behavior with Screenshots

Child components do have their catalog entries created.
404 page not found error on every child components Docs tab.
The directories in the S3 bucket have the child components nested in the parent component, backstage not including the parent component name in the path when trying to pull from the S3 bucket.
![image](https://github.com/user-attachments/assets/548a7eaa-4175-4493-93b1-5340b4fc6813)

![image](https://github.com/user-attachments/assets/03427c6a-92c2-4ecf-a6ce-d83ba24bb0e6)

![image](https://github.com/user-attachments/assets/7aab6ed2-ee04-41bd-8a04-8c5f3a4b908b)

### 👟 Reproduction steps

Setup a split monorepo in line with the documentation (https://github.com/RoadieHQ/sample-split-monorepo/tree/main/services).
Configure your backstage instance to use AWS & S3 for techdocs hosting s per official documentation.
Run techdocs cli generate and publish commands.

### 📃 Provide the context for the Bug.

I am unable to view documentation for each sub component in our monorepo.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by johnphilip283** [comment]
Hi there! Are you currently using the monorepo plugin as described [here](https://github.com/backstage/mkdocs-monorepo-plugin?tab=readme-ov-file#usage)?

**Comment by CodeMajik** [comment]
Hi @johnphilip283 , I implemented a monorepo approach using the plugin and making the root yaml for the repo of type Component yes, and it was able to run and combine all the docs of the child components into a single docs page and it only had the root omponent in the catalog. However my requirement is to have a catalog entry for every child component and be able to click the Docs tab in each component and see just it's respective set of docs.

**Comment by PeaWarrior** [comment]
Hey @CodeMajik, at the moment I don't think we support what you're requesting. However, you should be able to link your subcomponents to the root techdocs using the [backstage.io/techdocs-entity](https://backstage.io/docs/features/software-catalog/well-known-annotations/#backstageiotechdocs-entity) annotation in their respective `catalog-info.yaml`.
