### ISSUE TITLE
🐛 Bug Report: Okta provider: Login failed; caused by ResponseError: Request failed with 401 Unauthorized

### ISSUE THREAD

**Issue by andreikrautsou** [backstage/backstage#25921]
### 📜 Description

Migrated backstage version from `v1.22.1` to `v1.26.4` by this doc - https://backstage.io/docs/backend-system/building-backends/migrating/
Okta was added as an auth provider by this doc - https://backstage.io/docs/auth/okta/provider
Okta works correctly with the previous version

Okta config:
<img width="473" alt="okta" src="https://github.com/user-attachments/assets/6a2b7c54-072c-4b63-bae1-2a7a01a30886">

New backend index file:
<img width="622" alt="index" src="https://github.com/user-attachments/assets/eb8f1c0e-43fa-4d40-a35e-03f43b50e310">

Frontend page:
<img width="539" alt="ui" src="https://github.com/user-attachments/assets/f1a50609-0875-4381-8ec2-be6c373533d4">

### 👍 Expected behavior

It should log in correctly with okta

### 👎 Actual Behavior with Screenshots

<img width="700" alt="error_msg" src="https://github.com/user-attachments/assets/73d302e3-984c-425b-b4f3-441adb0193a1">

### 👟 Reproduction steps

Login with okta credentials.

### 📃 Provide the context for the Bug.

Okta Login failed 

### 🖥️ Your Environment

OS:   Darwin 21.6.0 - darwin/arm64
node: v18.20.4
yarn: 3.2.4
cli:  0.26.4 (installed)
backstage:  1.26.4

Dependencies:
  @backstage/app-defaults                                          1.5.4
  @backstage/backend-app-api                                       0.5.14, 0.7.1
  @backstage/backend-common                                        0.20.2, 0.21.7, 0.23.3
  @backstage/backend-defaults                                      0.2.17
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.6.21, 0.6.17, 0.7.0
  @backstage/backend-tasks                                         0.5.27, 0.5.22
  @backstage/catalog-client                                        1.5.2, 1.6.4, 1.6.5
  @backstage/catalog-model                                         1.4.3, 1.5.0, 1.4.5
  @backstage/cli-common                                            0.1.13, 0.1.14
  @backstage/cli-node                                              0.2.7, 0.2.5
  @backstage/cli                                                   0.25.2, 0.26.4
  @backstage/config-loader                                         1.8.1, 1.8.0
  @backstage/config                                                1.1.1, 1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.12.5, 0.13.10, 0.14.5
  @backstage/core-plugin-api                                       1.8.2, 1.9.2
  @backstage/dev-utils                                             1.0.31
  @backstage/errors                                                1.2.3, 1.2.4
  @backstage/eslint-plugin                                         0.1.8, 0.1.7
  @backstage/frontend-plugin-api                                   0.5.0, 0.6.4
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.23, 1.1.26
  @backstage/integration                                           1.10.0, 1.13.0, 1.8.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.4.12, 0.4.17
  @backstage/plugin-auth-react                                     0.1.1
  @backstage/plugin-badges-backend                                 0.4.1
  @backstage/plugin-badges                                         0.2.59
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.15
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend-module-unprocessed             0.4.4
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 1.0.20, 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.11.1
  @backstage/plugin-catalog-react                                  1.11.3, 1.9.3
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.1
  @backstage/plugin-catalog-unprocessed-entities                   0.2.3
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-node                                    0.3.3
  @backstage/plugin-github-actions                                 0.6.16
  @backstage/plugin-home-react                                     0.1.12
  @backstage/plugin-home                                           0.7.3
  @backstage/plugin-kubernetes-backend                             0.17.0
  @backstage/plugin-kubernetes-common                              0.7.5
  @backstage/plugin-kubernetes-node                                0.1.11
  @backstage/plugin-kubernetes-react                               0.3.4
  @backstage/plugin-kubernetes                                     0.11.9
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.14
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.12, 0.7.13, 0.7.14, 0.8.0
  @backstage/plugin-permission-node                                0.7.32, 0.7.28
  @backstage/plugin-permission-react                               0.4.19, 0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.4
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.23
  @backstage/plugin-search-backend-module-pg                       0.5.26
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.10, 1.2.11
  @backstage/plugin-search-react                                   1.7.5, 1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-sentry                                         0.5.20
  @backstage/plugin-sonarqube-react                                0.1.16
  @backstage/plugin-sonarqube                                      0.7.17
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.50
  @backstage/plugin-tech-insights-backend                          0.5.32
  @backstage/plugin-tech-insights-common                           0.2.13
  @backstage/plugin-tech-insights-node                             0.6.1
  @backstage/plugin-tech-insights                                  0.3.27
  @backstage/plugin-tech-radar                                     0.7.4
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.1.15, 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.4
  @backstage/theme                                                 0.2.19, 0.5.0, 0.5.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7, 1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Do you still happen to have all or parts of https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md set up? That'll all need to be removed as it conflicts with the built-in auth in more recent versions of Backstage.

**Comment by Rugvip** [comment]
@andreikrautsou and you're sure there's nothing in the backend? We'd likely need reproduction steps with a new app as a starting point or a repro repo to help out otherwise. The one other thing to call out is to make sure that all core plugins have been fully migrated to the new backend system, including avoiding the use of `legacyPlugin`.
