### ISSUE TITLE
🐛 Bug Report: Autologout feature resulting in console error in browser "Refused to create a worker from because it violates the following Content Security Policy directive: "script-src 'self' 'script-src-elem' 'unsafe-eval' 'unsafe-inline'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback."

### ISSUE THREAD

**Issue by vinaykv23** [backstage/backstage#25923]
### 📜 Description

Backstage "version": "1.28.0"
Added autologout feature by following
https://backstage.io/docs/auth/autologout/

after deployment, backstage is not loading resulting in browser console error

console error in browser "Refused to create a worker from because it violates the following Content Security Policy directive: "script-src 'self' 'script-src-elem' 'unsafe-eval' 'unsafe-inline'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback."

react-dom.production.min.js:188 DOMException: Failed to construct 'Worker': Access to the script at 'blob:https://backstage-dev/2988656f-aa6b-49ab-b088-3d98c735e94e' is denied by the document's Content Security Policy.

### 👍 Expected behavior

Auto logout should not impact backstage loading

### 👎 Actual Behavior with Screenshots

console error in browser "Refused to create a worker from because it violates the following Content Security Policy directive: "script-src 'self' 'script-src-elem' 'unsafe-eval' 'unsafe-inline'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback."

react-dom.production.min.js:188 DOMException: Failed to construct 'Worker': Access to the script at 'blob:https://backstage-dev/2988656f-aa6b-49ab-b088-3d98c735e94e' is denied by the document's Content Security Policy.

### 👟 Reproduction steps

Backstage "version": "1.28.0"
Added autologout feature by following
https://backstage.io/docs/auth/autologout/

after deployment, backstage is not loading resulting in browser console error

console error in browser "Refused to create a worker from because it violates the following Content Security Policy directive: "script-src 'self' 'script-src-elem' 'unsafe-eval' 'unsafe-inline'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback."

react-dom.production.min.js:188 DOMException: Failed to construct 'Worker': Access to the script at 'blob:https://backstage-dev/2988656f-aa6b-49ab-b088-3d98c735e94e' is denied by the document's Content Security Policy.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Hmm, do you have `useWorkerTimers` set on the `AutoLogout` component? Might be that you want to disable that, or configure the environment to allow for the worker script to be loaded. If this is the fix I think it would be good to add some more hints to the docs around this, potentially even disabling worker timers by default. Do you have any thoughts on this @manuelscurti?

**Comment by ahmm16** [comment]
Any solutions about this error? It's still happening and I didn't see any warning in the documentation...

@manuelscurti 
@Rugvip 
@vinaykv23 

![image](https://github.com/user-attachments/assets/3a14e9f8-def6-4e5c-9a9c-30bbd305ac35)

**Comment by manuelscurti** [comment]
h

> Any solution about this error? It's still happening and I didn't see any warning in the documentation...
> 
> @manuelscurti @Rugvip @vinaykv23
> 
> ![image](https://private-user-images.githubusercontent.com/39168831/380172731-3a14e9f8-def6-4e5c-9a9c-30bbd305ac35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjE4MzYsIm5iZiI6MTcyOTg2MTUzNiwicGF0aCI6Ii8zOTE2ODgzMS8zODAxNzI3MzEtM2ExNGU5ZjgtZGVmNi00ZTVjLTlhOWMtMzBiYmQzMDVhYzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEzMDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZjhhMTJkZWE0MWVmNWY2ZTRiM2VkZWFjOTVjNzBhMmIzYTE3N2FmM2RmM2FiY2YyODhiMTM1YTcyMDUzMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hVvazZYlBewcwe_4VP0j7oXcROEMSFpj-zp3ZP5sBW4)

hi! could you please try to set `auth.autologout.useWorkerTimers` to `false` in your app-config? 

https://backstage.io/docs/auth/autologout/

**Comment by ahmm16** [comment]
> > Any solution about this error? It's still happening and I didn't see any warning in the documentation...
> > @manuelscurti @Rugvip @vinaykv23
> > ![image](https://private-user-images.githubusercontent.com/39168831/380172731-3a14e9f8-def6-4e5c-9a9c-30bbd305ac35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjE4MzYsIm5iZiI6MTcyOTg2MTUzNiwicGF0aCI6Ii8zOTE2ODgzMS8zODAxNzI3MzEtM2ExNGU5ZjgtZGVmNi00ZTVjLTlhOWMtMzBiYmQzMDVhYzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEzMDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZjhhMTJkZWE0MWVmNWY2ZTRiM2VkZWFjOTVjNzBhMmIzYTE3N2FmM2RmM2FiY2YyODhiMTM1YTcyMDUzMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hVvazZYlBewcwe_4VP0j7oXcROEMSFpj-zp3ZP5sBW4)
> 
> hi! could you please try to set `auth.autologout.useWorkerTimers` to `false` in your app-config?
> 
> https://backstage.io/docs/auth/autologout/

Omg, now I see the warning: _In case of browser incompatibility, try setting this to false. Sorry and thank you a lot!
