### ISSUE TITLE
🐛 Bug Report: Local dev documentation does not work with Yarn Berry

### ISSUE THREAD

**Issue by pc-bob** [backstage/backstage#25957]
### 📜 Description

Local dev documentation found [here](https://backstage.io/docs/tooling/local-dev/linking-local-packages/) was originally written 3 years ago for yarn 1. Does not appear to work with Yarn Berry. 

### 👍 Expected behavior

I should be able to follow the instructions in the local dev documentation to link a package from upstream backstage to my backstage implementation for debugging or new feature development. 

### 👎 Actual Behavior with Screenshots

<img width="2138" alt="Screenshot 2024-08-08 at 3 38 04 PM" src="https://github.com/user-attachments/assets/014efd3f-0dfb-474a-b530-1bb76d5212ae">

```
➜  procore-backstage git:(procore-backstage-0.566.000) ✗ yarn 
➤ YN0000: · Yarn 4.3.0
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @backstage/backend-common@workspace:^: Workspace not found (@backstage/backend-common@workspace:^)
    at St.getWorkspaceByDescriptor (/Users/boblaskowski/code/procore/procore-backstage/.yarn/releases/yarn-4.3.0.cjs:210:3520)
    at c1.getCandidates (/Users/boblaskowski/code/procore/procore-backstage/.yarn/releases/yarn-4.3.0.cjs:140:115470)
    at Pd.getCandidates (/Users/boblaskowski/code/procore/procore-backstage/.yarn/releases/yarn-4.3.0.cjs:141:1311)
    at Pd.getCandidates (/Users/boblaskowski/code/procore/procore-backstage/.yarn/releases/yarn-4.3.0.cjs:141:1311)
    at /Users/boblaskowski/code/procore/procore-backstage/.yarn/releases/yarn-4.3.0.cjs:210:8422
    at Yy (/Users/boblaskowski/code/procore/procore-backstage/.yarn/releases/yarn-4.3.0.cjs:140:53917)
    at ht (/Users/boblaskowski/code/procore/procore-backstage/.yarn/releases/yarn-4.3.0.cjs:210:8402)
    at async Promise.allSettled (index 0)
    at async _c (/Users/boblaskowski/code/procore/procore-backstage/.yarn/releases/yarn-4.3.0.cjs:140:53245)
➤ YN0000: └ Completed in 2s 692ms
➤ YN0000: · Failed with errors in 2s 699ms
```

### 👟 Reproduction steps

1. Create a new backstage app following https://backstage.io/docs/getting-started/#1-create-your-backstage-app
2. Follow the tutorial to migrate to Yarn 3+: https://backstage.io/docs/tutorials/yarn-migration
    * really just need the [installation](https://backstage.io/docs/tutorials/yarn-migration#installation) section. use `yarn set version stable` instead of `yarn set version 3.x`
3. Clone the [backstage/backstage](https://github.com/backstage/backstage) repo in a separate directory
4. Follow the tutorial to link a local package: https://backstage.io/docs/tooling/local-dev/linking-local-packages

### 📃 Provide the context for the Bug.

I am trying to debug a separate issue related to catalog metrics but am unable to easily do so due to my lack of ability to run a local version of the catalog-backend plugin.

### 🖥️ Your Environment

OS:   Darwin 23.5.0 - darwin/arm64
node: v20.14.0
yarn: 4.3.0
cli:  0.26.11 (installed)
backstage:  1.28.4

Dependencies:
  @backstage/app-defaults                                          1.5.8
  @backstage/backend-app-api                                       0.5.14, 0.7.9, 0.8.0
  @backstage/backend-common                                        0.19.10, 0.20.2, 0.21.7, 0.22.0, 0.23.3
  @backstage/backend-defaults                                      0.3.3, 0.4.1
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.15
  @backstage/backend-plugin-api                                    0.6.21, 0.7.0
  @backstage/backend-tasks                                         0.5.27
  @backstage/backend-test-utils                                    0.3.8, 0.4.4
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.26.11
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.0
  @backstage/core-compat-api                                       0.2.7
  @backstage/core-components                                       0.12.5, 0.14.9
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.35
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.7
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.29
  @backstage/integration                                           1.13.0
  @backstage/plugin-analytics-module-ga4                           0.2.4
  @backstage/plugin-api-docs                                       0.11.7
  @backstage/plugin-app-backend                                    0.3.71
  @backstage/plugin-app-node                                       0.1.22
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.14
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.5
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.5
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.17
  @backstage/plugin-auth-backend-module-github-provider            0.1.19
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.19
  @backstage/plugin-auth-backend-module-google-provider            0.1.19
  @backstage/plugin-auth-backend-module-guest-provider             0.1.8
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.17
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.15
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.14, 0.0.15
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.3
  @backstage/plugin-auth-backend                                   0.22.9
  @backstage/plugin-auth-node                                      0.4.17
  @backstage/plugin-auth-react                                     0.1.4
  @backstage/plugin-bitbucket-cloud-common                         0.2.21
  @backstage/plugin-catalog-backend-module-github-org              0.1.17
  @backstage/plugin-catalog-backend-module-github                  0.6.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.20
  @backstage/plugin-catalog-backend                                1.24.0
  @backstage/plugin-catalog-common                                 1.0.25
  @backstage/plugin-catalog-graph                                  0.4.7
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.12.4
  @backstage/plugin-catalog-react                                  1.12.2
  @backstage/plugin-catalog                                        1.21.1
  @backstage/plugin-circleci                                       0.3.34
  @backstage/plugin-events-node                                    0.3.8
  @backstage/plugin-github-actions                                 0.6.15
  @backstage/plugin-home-react                                     0.1.15
  @backstage/plugin-home                                           0.7.7
  @backstage/plugin-kubernetes-backend                             0.18.3
  @backstage/plugin-kubernetes-common                              0.8.1
  @backstage/plugin-kubernetes-node                                0.1.16
  @backstage/plugin-kubernetes-react                               0.4.1
  @backstage/plugin-kubernetes                                     0.11.12
  @backstage/plugin-org                                            0.6.27
  @backstage/plugin-permission-backend                             0.5.46
  @backstage/plugin-permission-common                              0.7.14, 0.8.0
  @backstage/plugin-permission-node                                0.7.32, 0.8.0
  @backstage/plugin-permission-react                               0.4.24
  @backstage/plugin-proxy-backend                                  0.5.3
  @backstage/plugin-scaffolder-backend-module-azure                0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.12
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.14
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.12
  @backstage/plugin-scaffolder-backend-module-github               0.4.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.4
  @backstage/plugin-scaffolder-backend                             1.23.0
  @backstage/plugin-scaffolder-common                              1.5.4
  @backstage/plugin-scaffolder-node                                0.2.10, 0.4.8
  @backstage/plugin-scaffolder-react                               1.10.0
  @backstage/plugin-scaffolder                                     1.23.0
  @backstage/plugin-search-backend-module-catalog                  0.1.28
  @backstage/plugin-search-backend-module-pg                       0.5.32
  @backstage/plugin-search-backend-module-techdocs                 0.1.27
  @backstage/plugin-search-backend-node                            1.2.27
  @backstage/plugin-search-backend                                 1.5.14
  @backstage/plugin-search-common                                  1.2.13
  @backstage/plugin-search-react                                   1.7.13
  @backstage/plugin-search                                         1.4.14
  @backstage/plugin-shortcuts                                      0.3.23
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.9
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.12
  @backstage/plugin-techdocs-node                                  1.12.8
  @backstage/plugin-techdocs-react                                 1.2.6
  @backstage/plugin-techdocs                                       1.10.7
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.9
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.8
  @backstage/theme                                                 0.2.19, 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR! Caveat: I don't know how to fix this.

**Comment by Rugvip** [comment]
See https://backstage.io/docs/tooling/local-dev/linking-local-packages#backend-issues, you'll need to link in each dependency too. There's definitely room for improvement here though as it's clearly not optimal.

**Comment by camilaibs** [comment]
> See https://backstage.io/docs/tooling/local-dev/linking-local-packages#backend-issues, you'll need to link in each dependency too. There's definitely room for improvement here though as it's clearly not optimal.

Hi @pc-bob, did you have a chance to check the linked documentation 🙂? Considering that, I wonder whether this issue can be closed.

**Comment by Rugvip** [comment]
Confirmed that this is indeed an issue and it's generally not possible to get local package linking working while using Yarn 3+. We'll be working to find a solution to achieve the same effect, probably outside of Yarn

**Comment by freben** [comment]
This should be fixed now! https://backstage.io/docs/tooling/local-dev/linking-local-packages
