### ISSUE TITLE
🐛 Bug Report: GitHub Archiving/Unarchiving Repo Webhook is not working

### ISSUE THREAD

**Issue by davidg-idealo** [backstage/backstage#25951]
### 📜 Description

With feature request [21906](https://github.com/backstage/backstage/issues/21906), further GitHub events were taken into account via webhooks.
Related commit: https://github.com/Bonial-International-GmbH/backstage/commit/9112efc364d24f134881e9c09db1323fdfcc4165

Unfortunately, the events for archiving and unarchiving repositories are not processed correctly.

### 👍 Expected behavior

If a repository is archived it should be removed from the backstage catalog.
If a repository is unarchived it should be added to the backstage catalog.

### 👎 Actual Behavior with Screenshots

If a repository is archived it is still registered and you need to unregister ist manually or delete the catalog-info.yaml.
If a repository is unarchived it is not registered and you need to manually register it or wait for the complete organization scan.

### 👟 Reproduction steps

To archive a repository you can follow the steps described here: https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories
Afterwards check if the repository is still registered in backstage.

For unarchiving you can follow the same steps and check afterwards if the repo is registered.

### 📃 Provide the context for the Bug.

The root cause for this bug is that the payload for archiving/unarchiving repositories is slightly different then for push events.

You are checking here if the org from the webhook is the same then in the config: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/providers/GithubEntityProvider.ts#L411
If not you log the org from the event. We see in the logs:

> catalog debug skipping repository event from organization undefined target=github-provider:idealo

The `undefined` has surprised us.

The data classes from octokit are used and you use the field `organization` from the object `Repository`:
https://github.com/octokit/webhooks/blob/main/payload-types/schema.d.ts#L793

Then we checked the payload from the archive event and it doesn't contain the field `organization` in the object `Repository`.
Shorten payload for an archive repo event:
```
{
  "action": "archived",
  "repository": {
    "id": 834002178,
    "node_id": "R_kgDOMbXdAg",
    "name": "backstage-onboarding-demo",
    "full_name": "idealo/backstage-onboarding-demo",
    "private": true,
    "owner": {
      "login": "idealo",
...
    },
  },
  "organization": {
    "login": "idealo",
...
  },
  "enterprise": {
...
  },
  "sender": {
...
  },
  "installation": {
...
  }
}
```
Due to the missing `organization` field in the `Repository` object it results in the undefined response.

In contrast, the `organization` field is included in the `Repository` object in the payload for a push event and due to this the check [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/providers/GithubEntityProvider.ts#L326) works.

We therefore propose to adjust the `organization` validation as follows:
```
private async onRepoChange(event: RepositoryEvent) {
    if (this.config.organization !== event.organization.login) {
      this.logger.debug(
        `skipping repository event from organization ${event.organization.login}`,
      );
      return;
    }
```
We would then make use of the `organization`object: https://github.com/octokit/webhooks/blob/main/payload-types/schema.d.ts#L7473
I am unsure whether it is necessary to check whether `organization` is undefined before accessing the `login` field.

### 🖥️ Your Environment

OS:   Darwin 23.5.0 - darwin/arm64
node: v20.14.0
yarn: 1.22.21
cli:  0.26.11 (installed)
backstage:  1.29.2

Dependencies:
  @backstage/app-defaults                                          1.5.9
  @backstage/backend-app-api                                       0.7.9, 0.8.0
  @backstage/backend-common                                        0.22.0, 0.23.3
  @backstage/backend-defaults                                      0.4.1
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.15
  @backstage/backend-plugin-api                                    0.6.21, 0.7.0
  @backstage/backend-tasks                                         0.5.27
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.26.11
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.1
  @backstage/core-compat-api                                       0.2.7
  @backstage/core-components                                       0.13.10, 0.14.9
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.36
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.7
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.29
  @backstage/integration                                           1.13.0
  @backstage/plugin-api-docs                                       0.11.7
  @backstage/plugin-app-backend                                    0.3.71
  @backstage/plugin-app-node                                       0.1.22
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.14
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.5
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.5
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.17
  @backstage/plugin-auth-backend-module-github-provider            0.1.19
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.19
  @backstage/plugin-auth-backend-module-google-provider            0.1.19
  @backstage/plugin-auth-backend-module-guest-provider             0.1.8
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.17
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.15
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.15
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.3
  @backstage/plugin-auth-backend                                   0.22.9
  @backstage/plugin-auth-node                                      0.4.17
  @backstage/plugin-auth-react                                     0.1.4
  @backstage/plugin-bitbucket-cloud-common                         0.2.21
  @backstage/plugin-catalog-backend-module-github-org              0.1.17
  @backstage/plugin-catalog-backend-module-github                  0.6.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.20
  @backstage/plugin-catalog-backend                                1.24.0
  @backstage/plugin-catalog-common                                 1.0.25
  @backstage/plugin-catalog-graph                                  0.4.7
  @backstage/plugin-catalog-import                                 0.12.1
  @backstage/plugin-catalog-node                                   1.12.4
  @backstage/plugin-catalog-react                                  1.12.2
  @backstage/plugin-catalog                                        1.21.1
  @backstage/plugin-devtools-backend                               0.3.8
  @backstage/plugin-devtools-common                                0.1.11
  @backstage/plugin-devtools                                       0.1.16
  @backstage/plugin-events-backend-module-github                   0.2.8
  @backstage/plugin-events-backend                                 0.3.9
  @backstage/plugin-events-node                                    0.3.8
  @backstage/plugin-home-react                                     0.1.15
  @backstage/plugin-home                                           0.7.8
  @backstage/plugin-org                                            0.6.27
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.19
  @backstage/plugin-permission-backend                             0.5.46
  @backstage/plugin-permission-common                              0.7.14, 0.8.0
  @backstage/plugin-permission-node                                0.7.32, 0.8.0
  @backstage/plugin-permission-react                               0.4.24
  @backstage/plugin-proxy-backend                                  0.5.3
  @backstage/plugin-scaffolder-backend-module-azure                0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.12
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.14
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.12
  @backstage/plugin-scaffolder-backend-module-github               0.4.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.4
  @backstage/plugin-scaffolder-backend                             1.23.0
  @backstage/plugin-scaffolder-common                              1.5.4
  @backstage/plugin-scaffolder-node                                0.4.8
  @backstage/plugin-scaffolder-react                               1.10.0
  @backstage/plugin-scaffolder                                     1.23.0
  @backstage/plugin-search-backend-module-catalog                  0.1.28
  @backstage/plugin-search-backend-module-pg                       0.5.32
  @backstage/plugin-search-backend-module-techdocs                 0.1.27
  @backstage/plugin-search-backend-node                            1.2.27
  @backstage/plugin-search-backend                                 1.5.14
  @backstage/plugin-search-common                                  1.2.13
  @backstage/plugin-search-react                                   1.7.13
  @backstage/plugin-search                                         1.4.14
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.9
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.12
  @backstage/plugin-techdocs-node                                  1.12.8
  @backstage/plugin-techdocs-react                                 1.2.6
  @backstage/plugin-techdocs                                       1.10.7
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.10
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.9
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 2.16s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by davidg-idealo** [comment]
Hi @pjungermann
maybe you can have a look. @wanisfahmyDE and me can support fixing that and we can also provide further Webhook payloads to ensure that the other GitHub events work.

**Comment by pjungermann** [comment]
I'll have a look. I'm back on Monday.

**Comment by pjungermann** [comment]
`$.repository.organization` only gets set at `push` events. `$.organization` and `$.organization.login` are provided at `push` and `repository` events.

I will provide a fix later today.
