### ISSUE TITLE
🐛 Bug Report: Admonitions in Backstage Docs not working in TechDocs

### ISSUE THREAD

**Issue by darylgraham** [backstage/backstage#25973]
### 📜 Description

I was browsing the docs via the demo site and noticed that the admonitions are not working. Checking the microsite shows them fine, so I assume that the admonition formats between the microsite and techdocs differs.

```md
# https://github.com/backstage/backstage/blob/master/docs/features/techdocs/how-to-guides.md?plain=1#L502-L507
:::note Note

The values of `site_name`, `component_id` and `site_description` depends
on how you have configured your `template.yaml`.

:::
```

The [example docs](https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/examples/documented-component/docs/extensions.md) in the `techdocs-backend` plugin indicate that this syntax is wrong.

### 👍 Expected behavior

How it renders in the microsite.

<img width="1671" alt="Screenshot 2024-08-11 at 10 38 18 AM" src="https://github.com/user-attachments/assets/cf312beb-f8c2-4bb3-b033-5ee7bb9e8bb2">

### 👎 Actual Behavior with Screenshots

How it renders in TechDocs on the demo site.

<img width="1683" alt="Screenshot 2024-08-11 at 10 36 19 AM" src="https://github.com/user-attachments/assets/e2eac26c-b9d9-461d-b960-58f7b0375d29">

### 👟 Reproduction steps

Browse the Backstage documentation through the demo site.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @darylgraham, the Backstage docs shown are intended to work with Docusaurus which uses a different pattern for  admonition. There isn't a way to fix this as it will end up being broken in one place or the other. Moving to use MkDocs for the docs on Backstage.io doesn't seem worth the effort. We could simply remove the Backstage docs from the Demo site but I think the Community would be lesser for it.

**Comment by aramissennyeydd** [comment]
@awanlin Maybe a parser to translate from the Docusaurus admonitions to MkDocs ones would make sense here? Something like https://github.com/oprypin/markdown-callouts/tree/master.

**Comment by Rugvip** [comment]
Yep I'd call this out of scope for TechDocs and tbh I don't think we should start playing catch-up with Docusaurus here either, there are more important things to focus on :grin:. I think it's worth evaluating whether we should remove the docs from the demo site, but checking in with @backstage/techdocs-maintainers for some thoughts on the topic.

**Comment by darylgraham** [comment]
That all makes sense. Maybe now is the time to re-visit a Docusaurus processor for TechDocs? 

I'll close this out.
