### ISSUE TITLE
🚀 Feature: github.com/host & /branch annotation to help support multiple github enterprises environments

### ISSUE THREAD

**Issue by Coderrob** [backstage/backstage#25971]
### 🔖 Feature description

The available project-slug is useful because you're able to get the organization along with the repository name. What we don't know is ... what is the host? GitHub integrations have GitHub Enterprise support through server host properties. 

I found that adding an additional annotation to entities can help eliminate the guess. 
```yaml
cisco.com/host: ghe.somewhere.com
```
Between that annotation and the project-slug it's enough to create a URL to the repository for use in custom template actions or in custom GitHub plugins.

The only other thing to consider is for a GitHub URL it's basically `<host>/<org>/<repo>` and the `branch`. Based on GitHub Api schema I'd also propose a `default_branch` identifier. Something like:

```yaml
cisco.com/default-branch: main
```

It looks like this "missing piece" has been an issue for others if I'm understanding the comments from the end of the file at https://github.com/coder/backstage-plugins/blob/main/plugins/backstage-plugin-devcontainers-backend/src/processors/DevcontainersProcessor.ts#L219

### 🎤 Context

Supporting Enterprise environments with thousands of repositories spread across multiple GitHub Enterprise (GHE) hosts most plugins don't take advantage of the ScmAuthApi to merge multiple providers (GitHub Enterprise for me) into a single interface. It's also been hit or miss on whether or not plugins support not just a single instance of GHE but potentially dozens.

What has helped me was a host annotation but branch is also important as a unique identifier to the source code. Based on that I'd propose to provide two additional GitHub Annotations:

```yaml
cisco.com/host
cisco.com/branch
```

Could go either way but keeping with GitHub Api's schema response they used `default_branch` so keeping context close to home. For non-default branch could see `branch` to be able to provide ability to target tags feature branches on entities.

### ✌️ Possible Implementation

Addition of two new Well Known Annotations for GitHub:
```yaml
cisco.com/host
cisco.com/branch
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
The [`backstage.io/source-location`](https://backstage.io/docs/features/software-catalog/well-known-annotations/#backstageiosource-location) is a widely used annotation that I think serves this use-case well too. It keep track of both where the entity is hosted and optionally which branch it's on. Ideally you're able to use that without any further additions.

**Comment by CiscoRob** [comment]
@Rugvip the problem I ran into with source-location is in a large enterprise with hundreds of GitHub orgs across dozens of GHE servers was enabling access to the repos to keep catalog data updated and current. As a tradeoff we created a "phone book" repository that contained catalog data in a shared space that points outwards to the resources.

For those services defined in a shared repo the `source-location` is the repo containing the _entity definitions_ and not the actual GitHub repo where the service code is located.

In that case the `source-location` becomes the source of the metadata that's where the necessity to have support for pointing the GitHub integrations, through annotations, to the "source" repo of the service.

**Comment by Rugvip** [comment]
@CiscoRob with a phone book repo pattern you'd still actually want to point `source-location` to where the actual source code of the component resides. The [`backstage.io/managed-by-location`](https://backstage.io/docs/features/software-catalog/well-known-annotations/#backstageiomanaged-by-location) is the annotation that keeps track of where the entity is defined. Afaik you can explicitly define the `source-location` annotation with the correct location of the source code, and the catalog processing should not override that.
