### ISSUE TITLE
🐛 Bug Report: VirtualizedListbox cuts off list items when few items are present

### ISSUE THREAD

**Issue by kmikko** [backstage/backstage#25974]
### 📜 Description

`VirtualizedListbox` implemented in https://github.com/backstage/backstage/pull/25380 and https://github.com/backstage/backstage/pull/25315 cuts off list items also when there are only few items present. The listbox cuts off last item into half to give user a visual feedback that the list has more items than are currently being displayed. This logic should be only applied when all of the list items cannot be shown at once.

Thanks for @ionition for [spotting](https://github.com/backstage/backstage/pull/25315#issuecomment-2276022072) this!

Working example with many items:
<img width="545" alt="Screenshot 2024-08-12 at 8 25 38" src="https://github.com/user-attachments/assets/dcc61252-a258-48fc-8a9a-8504fa4dca5f">

### 👍 Expected behavior

If all list items can be shown at once (N <= 10) they should be fully visible

<img width="540" alt="Screenshot 2024-08-12 at 8 26 21" src="https://github.com/user-attachments/assets/f4b24252-83b2-4ee9-8cc5-b4dac892433a">

### 👎 Actual Behavior with Screenshots

Instead the last item is always cut into half no matter the item count

<img width="540" alt="Screenshot 2024-08-12 at 8 24 05" src="https://github.com/user-attachments/assets/917d4fc7-9d9c-4ad3-8be1-900343afda47">

### 👟 Reproduction steps

Open `Custom Field Explorer` and select `EntityPicker` or `MultiEntityPicker`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
I believe this is about to be fixed by #25948, see https://github.com/backstage/backstage/pull/25948/files#r1711374187

**Comment by camilaibs** [comment]
> I believe this is about to be fixed by #25948, see https://github.com/backstage/backstage/pull/25948/files#r1711374187

@kmikko, the mentioned pull request was merged. Did the issue get resolved for you?

**Comment by kmikko** [comment]
> > I believe this is about to be fixed by #25948, see https://github.com/backstage/backstage/pull/25948/files#r1711374187
> 
> @kmikko, the mentioned pull request was merged. Did the issue get resolved for you?

Yes, that seems to fix the issue 👍
