### ISSUE TITLE
🐛 Bug Report: <title>

### ISSUE THREAD

**Issue by IvanMkk** [backstage/backstage#26003]
### 📜 Description

this link doesn't work for me
https://hellodev.hellofresh.io/project/kafka/docs/connect/bring-data-to-datalake/postgres-kafka-s3-cdc/

### 👍 Expected behavior

-

### 👎 Actual Behavior with Screenshots

-

### 👟 Reproduction steps

-

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @IvanMkk, have a feeling this was for the wrong repo, going to close, feel free to follow up if you feel that's not correct.
