### ISSUE TITLE
Scaffolder: Call the Catalog API instead of getting passed the template

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#2601]
## Feature Suggestion
Right now, the Scaffolder gets called with the catalog entity which is to be templated. This should be replaced with a call to the catalog API to get the most recent and up to date version of the Template entity.

## Possible Implementation
Using the tooling available when https://github.com/spotify/backstage/issues/2600 is merged, use call the the catalog API, and update the frontend to only pass the Template entity ID to the scaffolder.

**Comment by mehuled** [comment]
Hey, @benjdlambert would like to pick this up! Would appreciate any leads. I am looking into it meanwhile.

**Comment by benjdlambert** [comment]
Hey @mehuled I added you to the issue.

Currently there is an example of backend plugins using the `discoveryApi` it's in the `auth-backend` plugin.
Theres a CatalogIdentityClient(
https://github.com/spotify/backstage/blob/56215d02f09510f163156a976c0a09604eab65ea/plugins/auth-backend/src/lib/catalog/CatalogIdentityClient.ts) which i'd recommend we duplicate to the `scaffolder-backend` but change the name and update the logic to CatalogEntityClient or something. 

you'll see in the `POST v1/jobs` route in the `scaffolder-backend` how the entity comes from the `POST Body`. This should be replaced with a call to the copied over client with only a name that comes from the `POST Body` and then in the `scaffolder` plugin (Which is the frontend part) you can remove the `POSTing` of the entire entity and just send the entityId for now.

Any questions let me know!

Then on the frontend, if you look at the scaffolder

**Comment by mehuled** [comment]
sure, this really helps! On it.
