### ISSUE TITLE
🚀 Feature: Scaffolder ActionContext should include task id/url

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#26070]
### 🔖 Feature description

Scaffolder action context should include task id or/and task URL so that it can be used in the action.

### 🎤 Context

For example, creating a pull request from action, I would like to include the URL of the task in the description so that it can be backtracked to the task used to create the PR. Additionally, this can be used in other actions as well to point users back to the origin of the data. 

Having just id would be sufficient as the base URL can be fetched from config but if it's possible, it would also make sense to have the URL that points to the frontend task f.eg. `/create/tasks/12345`. This though might be a bit harder as the backend doesn't know anything about frontend routing. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
I think that this is pretty closely related https://github.com/backstage/backstage/issues/25553

**Comment by Ghaby-X** [comment]
Hello, can I work on this issue?

**Comment by awanlin** [comment]
Sure! I've assigned it to you @Ghaby-X 👍

**Comment by acierto** [comment]
Hey @Ghaby-X 👋 

Do you have any progress on this one?

**Comment by drodil** [comment]
Not stale, waiting for @Ghaby-X :)

**Comment by benjdlambert** [comment]
Fix is #27592

**Comment by benjdlambert** [comment]
Closing as this has now been fixed :tada:
