### ISSUE TITLE
🐛 Bug Report: `backend.auth.externalAccess` should be optional in schema

### ISSUE THREAD

**Issue by JounQin** [backstage/backstage#26103]
### 📜 Description

It's declared as required at

https://github.com/backstage/backstage/blob/47d3d9298f0dd920a03688219789a19a5c259e5d/packages/backend-app-api/config.d.ts#L74

and

https://github.com/backstage/backstage/blob/47d3d9298f0dd920a03688219789a19a5c259e5d/packages/backend-defaults/config.d.ts#L77

### 👍 Expected behavior

It should be optional

### 👎 Actual Behavior with Screenshots

Required

### 👟 Reproduction steps

N/A

### 📃 Provide the context for the Bug.

There was a PR #25391 but closed

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Oh no! This looks like it slipped through the net on the holidays and it's on me! 

I've re-opened the PR, and fixed it up to it should pass, will get this in and in a patch release today on top of the latest 1.30.0. Thanks for raising!
