### ISSUE TITLE
🐛 Bug Report: Techdocs page not loading with customised authorization header

### ISSUE THREAD

**Issue by ggkoning** [backstage/backstage#26117]
### 📜 Description

Techdocs page not loading

### 👍 Expected behavior

It should load a techdocs page

### 👎 Actual Behavior with Screenshots

A loading bar is shown instead of the documentation.
![image](https://github.com/user-attachments/assets/c672937a-8ced-4d6c-b9c5-392d7f58d20a)

Requested stylesheet: ```http://localhost:7007/api/techdocs/static/docs/default/component/backstage/assets/stylesheets/main.6543a935.min.css```

It seems like it keeps loading because of a stylesheet that is not able to be fetched and gives a 401 Unauthorized. The http get should ignore the Authorization header because it only needs the backstage-auth cookie. 

I have oauth2proxy that injects an Authorization header for SSO. I customised the Backstage Authorization header to "Backstage-Authorization" because the oauth2proxy injected Authorization header conflicts with the backstage Authorization header.

### 👟 Reproduction steps

1. Create new backstage application [the getting-started guide](https://backstage.io/docs/getting-started/)
2. Add component to /examples/entities.yaml with a techdocs url to a Github repo.
3. Add the following code to packages/backend/src/index.ts
```
backend.add(rootHttpRouterServiceFactory({
    configure: ({ app, applyDefaults }) => {
        app.use((req, _, next) => {
            if (req.headers['backstage-authorization']) {
                req.headers.authorization = Array.isArray(req.headers['backstage-authorization']) ? req.headers['backstage-authorization'][0] : req.headers['backstage-authorization'];
                delete req.headers['backstage-authorization'];
            }
            next();
        });
        applyDefaults();
    },
}));
```
4. Add the following code to packages/app/src/apis.ts
```
createApiFactory({
    api: fetchApiRef,
    deps: {
      configApi: configApiRef,
      identityApi: identityApiRef,
      discoveryApi: discoveryApiRef,
    },
    factory: ({ configApi, identityApi, discoveryApi }) => {
      return createFetchApi({
        middleware: [
          FetchMiddlewares.resolvePluginProtocol({
            discoveryApi,
          }),
          FetchMiddlewares.injectIdentityAuth({
            identityApi,
            config: configApi,
            header: {
              name: 'Backstage-Authorization',
              value: (backstageToken) => `Bearer ${backstageToken}`,
            }
          }),
        ],
      });
    },
  }),
```
5. Install a browser extension that adds an Authorization header to imitate the behaviour of oauth2proxy. Suggested extension for firefox: "Modify Header Value (HTTP Headers)" suggestion for Google Crome: "ModHeader - Modify HTTP headers"
6. Use the browser extension to inject a Authorization header into the website Make sure to prepend "Bearer" to the value of the header it does not matter if the token is valid in this case because the issue is that it reads the Authorization header.
7. Visit the documentation page for the added component

### 🖥️ Your Environment

backstage version: 1.30.0
OS:   Darwin 23.6.0 - darwin/arm64
node: v20.9.0
yarn: 1.22.22
cli:  0.27.0 (installed)
backstage:  1.30.0

Dependencies:
  @backstage/app-defaults                                          1.5.10
  @backstage/backend-app-api                                       0.9.1
  @backstage/backend-common                                        0.24.0
  @backstage/backend-defaults                                      0.4.3
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.16
  @backstage/backend-plugin-api                                    0.8.0
  @backstage/backend-tasks                                         0.6.0
  @backstage/catalog-client                                        1.6.6
  @backstage/catalog-model                                         1.6.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.27.0
  @backstage/config-loader                                         1.9.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2
  @backstage/core-compat-api                                       0.2.8
  @backstage/core-components                                       0.14.10
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.7.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30
  @backstage/integration                                           1.14.0
  @backstage/plugin-api-docs                                       0.11.8
  @backstage/plugin-app-backend                                    0.3.72
  @backstage/plugin-app-node                                       0.1.23
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.4
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.15
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.6
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.6
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.2.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.18
  @backstage/plugin-auth-backend-module-github-provider            0.1.20
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.20
  @backstage/plugin-auth-backend-module-google-provider            0.1.20
  @backstage/plugin-auth-backend-module-guest-provider             0.1.9
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.18
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.4
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.16
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.4
  @backstage/plugin-auth-backend-module-okta-provider              0.0.16
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.4
  @backstage/plugin-auth-backend                                   0.22.10
  @backstage/plugin-auth-node                                      0.5.0
  @backstage/plugin-auth-react                                     0.1.5
  @backstage/plugin-bitbucket-cloud-common                         0.2.22
  @backstage/plugin-catalog-backend-module-logs                    0.0.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.21
  @backstage/plugin-catalog-backend                                1.25.0
  @backstage/plugin-catalog-common                                 1.0.26
  @backstage/plugin-catalog-graph                                  0.4.8
  @backstage/plugin-catalog-import                                 0.12.2
  @backstage/plugin-catalog-node                                   1.12.5
  @backstage/plugin-catalog-react                                  1.12.3
  @backstage/plugin-catalog                                        1.22.0
  @backstage/plugin-events-node                                    0.3.9
  @backstage/plugin-kubernetes-backend                             0.18.4
  @backstage/plugin-kubernetes-common                              0.8.2
  @backstage/plugin-kubernetes-node                                0.1.17
  @backstage/plugin-kubernetes-react                               0.4.2
  @backstage/plugin-kubernetes                                     0.11.13
  @backstage/plugin-org                                            0.6.28
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.20
  @backstage/plugin-permission-backend                             0.5.47
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.1
  @backstage/plugin-permission-react                               0.4.25
  @backstage/plugin-proxy-backend                                  0.5.4
  @backstage/plugin-scaffolder-backend-module-azure                0.1.15
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.13
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.15
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.13
  @backstage/plugin-scaffolder-backend-module-github               0.4.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.5
  @backstage/plugin-scaffolder-backend                             1.24.0
  @backstage/plugin-scaffolder-common                              1.5.5
  @backstage/plugin-scaffolder-node                                0.4.9
  @backstage/plugin-scaffolder-react                               1.11.0
  @backstage/plugin-scaffolder                                     1.24.0
  @backstage/plugin-search-backend-module-catalog                  0.2.0
  @backstage/plugin-search-backend-module-pg                       0.5.33
  @backstage/plugin-search-backend-module-techdocs                 0.2.0
  @backstage/plugin-search-backend-node                            1.3.0
  @backstage/plugin-search-backend                                 1.5.15
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.7.14
  @backstage/plugin-search                                         1.4.15
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.11
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.13
  @backstage/plugin-techdocs-node                                  1.12.9
  @backstage/plugin-techdocs-react                                 1.2.7
  @backstage/plugin-techdocs                                       1.10.8
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.11
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.10
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
You need to instead configure oauth2proxy to NOT overwrite the existing Authorization header. You cannot customize Backstage successfully to do the opposite.

**Comment by ggkoning** [comment]
The oauth2proxy is used company wide so I can not change the configuration for it.

@freben Do you know what I should do in Backstage to fix this?

**Comment by ggkoning** [comment]
It has overlap with this [issue](https://github.com/backstage/backstage/issues/23015)

**Comment by ggkoning** [comment]
I am willing to make the necessary changes my self but maybe you could help me with finding where the changes need to be made.

**Comment by freben** [comment]
Adding the ability to choose the auth header name freely is intentionally left out of scope, I'm not foreseeing it being added in the near to mid term. There's a myriad of places that use the Authorization header name explicitly, so it would not just be a change that affected our internal repo, but likely a lot of third party repos globally too.

The oauth2proxy settings can probably be changed per target. Double check with the owners of that facility. I know others have had the same question and they've all solved it with a small config tweak. I don't use the product myself so I don't have at-hand what the exact change is. Backstage really needs to be able to transfer the Authorization header untainted from source to target with its own token.

**Comment by ggkoning** [comment]
@freben All other plugins I use work with customized authorization header names since frontend plugins migrated the use of IdentityApi to fetchApi. It is just this stylesheet from techdocs that is not working properly.

**Comment by ggkoning** [comment]
This link is working properly ```http://localhost:7007/api/techdocs/static/docs/default/component/backstage/index.html```
With 2 authorization headers ```Authorization```,  ```backstage-authorization``` and without backstage-auth cookie

**Comment by ggkoning** [comment]
@freben I solved the issue. 

The issue is that file "/api/techdocs/static/docs/default/component/backstage/assets/stylesheets/main.6543a935" is included in the head of the mkdocs as a html link but that means the header "backstage-authorization" is not added. 

To resolve this add the following code to file packages/backend/src/index.ts

```
backend.add(rootHttpRouterServiceFactory({
    configure: ({ app, applyDefaults }) => {
        app.use((req, _, next) => {
            // Remove Authorization header for this stylesheet
            if (req.url.includes("/api/techdocs/static/docs/default/component/backstage/assets/stylesheets/main.")) {
                req.headers.authorization = "";
            }
            next();
        });
        applyDefaults();
    },
}));
```

This code wil remove the added "authorization" header by oauth2proxy so the request is authorized based on the cookie "backstage-auth"

**Comment by arian-press2015** [comment]
A temporary workaround:
this issue is caused by a css file that fails to load. i saved a copy of that css, and used nginx to serve it instead of getting it from backstage. 
to solve this issue without the need to change backstage code, i added an entry to my nginx to serve the css file from a static location(the css is the same for all docs):

```
# route for techdocs css
        location ~ ^/api/techdocs/static/docs/default/(component|system|api|resource|template)/[a-zA-Z0-9_-]+/assets/stylesheets/main\..*\.css$ {
            alias /usr/share/nginx/html/main.min.css;

            # Fake headers
            add_header Content-Security-Policy "default-src 'self';base-uri 'self';font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self' 'unsafe-eval';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests;connect-src 'self' http: https:";
            add_header Referrer-Policy "no-referrer";
            add_header Strict-Transport-Security "max-age=15552000; includeSubDomains";
            add_header X-Content-Type-Options "nosniff";
            add_header X-DNS-Prefetch-Control "off";
            add_header X-Download-Options "noopen";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-Permitted-Cross-Domain-Policies "none";
            add_header X-XSS-Protection "0";
            add_header Cache-Control "public, max-age=0";
            add_header Vary "Accept-Encoding";

            # Ensure Content-Type and Encoding match
            default_type "text/css; charset=utf-8";
            gzip on;
            gzip_types text/css;

            # Serve the content with appropriate modification headers
            add_header Last-Modified "Tue, 24 Sep 2024 09:07:33 GMT";
            add_header ETag 'W/"20ec5-192234934db"';
        }
```
