### ISSUE TITLE
Get rid of token manager and identify service and document how to replace them

### ISSUE THREAD

**Issue by camilaibs** [backstage/backstage#26120]
### Open Questions
Should we provide built-in shims for token manager and identity service in backend system 1.0? Not allowing plugins to depend on them, but providing implementations in `backend-defaults`.

**Comment by camilaibs** [comment]
Pull request: https://github.com/backstage/backstage/pull/26115

**Comment by Rugvip** [comment]
Some more cleanup that's needed: #26125

**Comment by Rugvip** [comment]
Final removal in https://github.com/backstage/backstage/pull/26141
