### ISSUE TITLE
🚀 Feature: `createDevApp` should support translations

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#26161]
### 🔖 Feature description

`createDevApp` for local development should support the addition of translation resources and defining the allowed languages.

### 🎤 Context

When working with translations, it's much easier to see missing ones from the UI. That's why the `createDevApp` should allow adding translation resources and the possibility to change the language on the fly.

https://github.com/backstage/backstage/pull/26127 relates.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Ah that makes sense for the old frontend system for sure. Would you like to give it a stab?
