### ISSUE TITLE
🚀 Feature: Ability to access rootConfig from index.ts with the New Backend System

### ISSUE THREAD

**Issue by pegtrifork** [backstage/backstage#26170]
### 🔖 Feature description

Being able to load coreServices.rootConfig or similar in 'packages/backend/src/index.ts'

### 🎤 Context

In my usecase, I would like to add plugins conditionally based on if an entry exists in app.config.
I know this is supposed to be done via feature flagging within the plugins, but I am using plugins where this is not supported (e.g. @backstage/plugin-kubernetes-backend/alpha)
With the old backend system this was easy, since you loaded the config via `loadBackendConfig` from `@backstage/backend-common` while creating the PluginEnvironments.
However `loadBackendConfig` has been deprecated, and I don't see a good alternative.

My new approach, which doesn't seem correct, since the config is now loaded twice (in my code, and when the backend is created):
```
import { createBackend } from '@backstage/backend-defaults';
import { ConfigSources } from '@backstage/config-loader';
const backend = createBackend();

const source = ConfigSources.default({});
ConfigSources.toConfig(source).then(config => {
  if (config.has('kubernetes')) {
    backend.add(import('@backstage/plugin-kubernetes-backend/alpha'));
  }

  backend.start();
});
```
I would therefore like to be able to hook in to the config which is already being loaded during the creating of the backend.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
This is the sort of thing that feature loaders are good for.

https://github.com/backstage/backstage/blob/93f4a773d4decfb0d0a59b835954fb4fe95bf8e4/packages/backend/src/index.ts#L24

They can have deps just like other backend features.

**Comment by pegtrifork** [comment]
Cool! This is just what I was looking for, I just didn't manage to find it somehow. 
Thank you for pointing me in the right direction!
