### ISSUE TITLE
🐛 Bug Report: Notification icons not displayed

### ISSUE THREAD

**Issue by dweber019** [backstage/backstage#26255]
### 📜 Description

When using a icon when producing a notification with the following tutorial https://backstage.io/docs/notifications/#upgrade-to-the-latest-version-of-backstage the icon is not shown. I can provide the icon like this https://github.com/backstage/backstage/blob/master/plugins/notifications-common/src/types.ts#L52

### 👍 Expected behavior

Icon is used and displayed in table.
Is this the intended feature when providing an icon, to take precedence over the severity icon?

### 👎 Actual Behavior with Screenshots

The severity icon is always displayed https://github.com/backstage/backstage/blob/master/plugins/notifications/src/components/NotificationsTable/NotificationsTable.tsx#L223

### 👟 Reproduction steps

https://backstage.io/docs/notifications/#upgrade-to-the-latest-version-of-backstage

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@backstage/notifications-maintainers

**Comment by benjdlambert** [comment]
Ping also @drodil

**Comment by drodil** [comment]
And @mareklibra

**Comment by mareklibra** [comment]
Thanks for reporting that. 
@dweber019 will you provide a PR?

**Comment by dweber019** [comment]
@mareklibra sure if you can confirm how the feature should behave 😉 
If an icon is provided, should we display the severity icon or not? So either only one icon should be show or we show two icons.
I guess, when the icon is provided we should not show the severity icon, right?

**Comment by mareklibra** [comment]
Yes, that was the idea, just one icon per row. Thank you!

**Comment by dweber019** [comment]
@mareklibra created PR https://github.com/backstage/backstage/pull/26419
