### ISSUE TITLE
🚀 Feature: Allow to pass React element as title prop into SignInPage

### ISSUE THREAD

**Issue by Zakemi** [backstage/backstage#26304]
### 🔖 Feature description

This change would allow to pass a React element as `title` prop into `SignInPage` without TypeScript error. Current type allows only `string`.
Now:
```
<SignInPage
  title="Sign in page title"
  ...
/>
```
After:
```
<SignInPage
  title={<Logo />}
  ...
/>
```
Currently a React element passed as `title` is rendered properly, but it throws a TypeScript error.

### 🎤 Context

Sometimes the business requests placing not only a simple text but something more complex to reflect the company's brand. In my use-case, I need to place a logo in the title. Allowing passing React element would enable more customization of the login page.

### ✌️ Possible Implementation

The current Backstage code does work properly when passing a React element as `title` prop. The only issue is the TypeScript error that `TS2322: Type Element is not assignable to type string`.

Current type:
https://github.com/backstage/backstage/blob/09f24bd0c240d9629d099e26794c043042a80497/packages/core-components/src/layout/SignInPage/SignInPage.tsx#L41-L45

Allowing `ReactNode` could solve this TS issue:

```
type MultiSignInPageProps = SignInPageProps & {
  providers: IdentityProviders;
  title?: ReactNode;
  align?: 'center' | 'left';
};
```

Or, I have seen that sometimes another `titleComponent` prop is added while keeping the `title`. However, it would require more changes to render it:

```
type MultiSignInPageProps = SignInPageProps & {
  providers: IdentityProviders;
  title?: string;
  titleComponent?: ReactNode;
  align?: 'center' | 'left';
};
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@Zakemi seems sane - do you want to raise a PR for this?

**Comment by Zakemi** [comment]
Thanks you @benjdlambert for checking it! I can work on it only tomorrow. If anyone wants to open a PR before that, please feel free to do that.
