### ISSUE TITLE
🐛 Bug Report: Docker run is failing with an error

### ISSUE THREAD

**Issue by adityai** [backstage/backstage#26370]
### 📜 Description

I followed the instructions posted on this document https://backstage.io/docs/deployment/docker for building a docker container with backstage. When I executed the docker run command as stated in the document, I see errors.

### 👍 Expected behavior

Expected to see a running backstage docker container.

### 👎 Actual Behavior with Screenshots

Error message is in the Reproduction steps below.

### 👟 Reproduction steps

Commands executed in sequence:
```
npx @backstage/create-app@latest
cd backstage
yarn install --frozen-lockfile
yarn tsc
yarn build:backend --config ../../app-config.yaml
docker image build . -f packages/backend/Dockerfile --tag backstage
docker run -it -p 7007:7007 --name backstage backstage 
```
Console output:
```
Loading config from MergedConfigSource{FileConfigSource{path="/app/app-config.yaml"}, FileConfigSource{path="/app/app-config.production.yaml"}, EnvConfigSource{count=0}}
{"level":"info","message":"Found 0 new secrets in config that will be redacted","service":"backstage"}
{"level":"info","message":"Listening on :7007","service":"rootHttpRouter"}
{"level":"info","message":"Plugin initialization started: 'app', 'proxy', 'scaffolder', 'techdocs', 'auth', 'catalog', 'permission', 'search', 'kubernetes'","service":"backstage","type":"initialization"}
/app/node_modules/@backstage/backend-defaults/dist/database.cjs.js:457
        throw new Error(
              ^

Error: Failed to connect to the database to make sure that 'backstage_plugin_app' exists, Error: connect ECONNREFUSED 127.0.0.1:5432
    at PgConnector.getClient (/app/node_modules/@backstage/backend-defaults/dist/database.cjs.js:457:15)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.20.4
```

### 📃 Provide the context for the Bug.

I am trying to run the app for the first time.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey :wave: This looks like it's struggling to connect to the database? Do you have a running PostgreSQL database that you've configured?
