### ISSUE TITLE
🐛 Bug Report: Favourite icon components not using theme colors

### ISSUE THREAD

**Issue by callebstrom** [backstage/backstage#26385]
### 📜 Description

The colour of the `Star` component in catalog, home and techdocs are using a hard-coded yellow colour instead of the primary theme colour.

### 👍 Expected behavior

The various `Star` components should use overrideable theme colours to allow for customisation.

For example (see favourite icon - `Star`):
![image](https://github.com/user-attachments/assets/0681bbe8-1dbc-45d3-ab40-a27839c4f114)

### 👎 Actual Behavior with Screenshots

Observe the yellow star in the catalog entity table:
![image](https://github.com/user-attachments/assets/8a1d4a6a-ce9b-4795-bda0-f9884872e4d4)

### 👟 Reproduction steps

Visit any `/catalog` or `/docs` to observe the color of the favourite icon (`Star`).

You can find all occurrences by searching for `#f3ba37` throughout the code base.

### 📃 Provide the context for the Bug.

The current hard-coded yellow color conflicts with our "warning" theme color.  

### 🖥️ Your Environment

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Woops! Yep this needs a fix, opening up for some contributions :tada:

**Comment by callebstrom** [comment]
@benjdlambert I'll have a look :+1:
