### ISSUE TITLE
🐛 Bug Report: Backstage application Google-Auth error

### ISSUE THREAD

**Issue by soarbackstagegcp** [backstage/backstage#26411]
### 📜 Description

```
import {
  AlertDisplay,
  OAuthRequestDialog,
  SignInPage,
} from '@backstage/core-components';
import { createApp } from '@backstage/app-defaults';
import { AppRouter, FlatRoutes } from '@backstage/core-app-api';
import { CatalogGraphPage } from '@backstage/plugin-catalog-graph';
import { RequirePermission } from '@backstage/plugin-permission-react';
import { catalogEntityCreatePermission } from '@backstage/plugin-catalog-common/alpha';
import { providers } from './identityProviders';

const app = createApp({
  apis,
  components: {
    SignInPage: props => {
      return (
        <SignInPage
          {...props}
          providers={['guest', ...providers]}
          title="Select a sign-in method"
          align="center"
        />
      );
    },
  },

=========================================================

import {
  googleAuthApiRef
} from '@backstage/core-plugin-api';

export const providers = [
  {
    id: 'google-auth-provider',
    title: 'Google',
    message: 'Sign In using Google',
    apiRef: googleAuthApiRef,
  },
};
added Google provider in  App.tsx

=========================================================

added below in app-config.yaml 
  auth:
  environment: development
  providers:
    google:
      development:
        clientId: ******************
        clientSecret: ***************
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: usernameMatchingUserEntityName
            
=====================================================
```

configured Oauth in GCP console and im a google organization user my email ends with @google.com

![image](https://github.com/user-attachments/assets/2bf28e65-130a-4c86-92e5-5246369dc27e)

![image](https://github.com/user-attachments/assets/b26df7a2-1019-464e-98e2-82e468824c8d)

### 👍 Expected behavior

it should login with my organization username/password.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/c7f72848-fbb0-4663-8406-aea70c85a648)
getting above error 

### 👟 Reproduction steps

need help on this

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jhaals** [comment]
Sorry to hear that you're having issues. It does look like that error message is coming from Google and not from backstage, it kinda looks like the project does not have access to auth that domain but I'm not an expert in this domain. 
One alternative is to make the auth app external and verify domain using a sign in resolver.
