### ISSUE TITLE
🐛 Bug Report: Default password shown in plain text in template creation review page

### ISSUE THREAD

**Issue by jesuino** [backstage/backstage#26418]
### 📜 Description

While creating template in RHDH, if password value is not provided , review page shows default password in plain text instead of asterisks.

### 👍 Expected behavior

It should not show the password in plain text

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/4f2f9094-7c74-4635-a5f8-e446b9f5f5ef)

### 👟 Reproduction steps

1. Create a Software Template with this input field eg -: https://github.com/sudhishmk/rhdhcatlogexample/blob/main/defaultpswdtemplate.yml
2. Create a resource using this template
3. Leave the Repository password field untouched. The default value defghj will be used
4. Click Next until the Review page is shown
5. The value defghj will be visible in plain text
6. Repeat the steps above and fill in a random password
7. The password is masked with asterisks on the Review page 

### 📃 Provide the context for the Bug.

Workaround is not use a default value for the password, however, there are cases where a default password is being used.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by mahendra1290** [comment]
@jesuino I can work on this

**Comment by jhaals** [comment]
Does it make a difference to remove the default value?

**Comment by jesuino** [comment]
Hello,

Good news! I can't reproduce this with Upstream backstage! I will just track the fix to link it here. Any hints about where I should look is welcome. Thanks!

![Peek 2024-09-06 14-52](https://github.com/user-attachments/assets/ff5829ea-c4b3-4005-9389-c0d4a06fd19c)

**Comment by jesuino** [comment]
I tracked the fix to this PR - I can confirm it indirectly fixed this issue because before it secret fields were not handled in 'ReviewState.tsx'. 

https://github.com/backstage/backstage/pull/26110

I am closing this issue, thank you all!
