### ISSUE TITLE
🚀 Feature: Extend login page functionality to provide extra content

### ISSUE THREAD

**Issue by jboeijenga** [backstage/backstage#26423]
### 🔖 Feature description

I would like to give our backstage users more context while login in to the application.

### 🎤 Context

In my case we want to inform users on our privacy statement and terms of use. I would like to ad a link and / or more content to the login page to provide them the information they need to agree upon in order to use our application.

### ✌️ Possible Implementation

I could see a few options.

1) Export the `getSignInProviders` and `useSignInProviders` from the core-components package so users can build their custom login page.
2) Allow children for the `SignInPage` component.
3) Allow children in the `SignInProviderConfig`.

I think 1 would give the ultimate flexibility without changes to the existing component. But it would also introduce the need to maintain your custom login page.
We can also consider introducing and exporting a new hook like:

```typescript
export function useSignInProviderElements (providers: IdentityProviders, onSignInSuccess: (userIdentity: UserIdentity) => void) {
  const signInProviders = getSignInProviders(providers);
  return useSignInProviders(
    signInProviders,
    onSignInSuccess,
  );
}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by svsven** [comment]
Hi, just wanted to check in to see if anything has happened with this functionality? I came across this issue and PR when searching how to implement a custom sign in page, but saw that both the PR and this issue got closed.
