### ISSUE TITLE
[catalog] Add cloud billing entity (e.g. GCP project) support to the catalog plugin

### ISSUE THREAD

**Issue by brendasukh** [backstage/backstage#2645]
## Feature Suggestion
Update catalog plugin to support cloud billing entities to track ownership of cloud resources. 

## Context
The catalog plugin tracks software ownership and metadata for an organization. There is an additional need to track ownership of cloud resources. At Spotify, this ownership is tracked at the level of cloud billing entities, such as GCP projects.

Adding support for billing entities, along with the identity plugin to associate users with groups, will allow a full picture of common cloud resource ownership.

**Comment by nikek** [comment]
I wouldn't say this is a good first issue, it might be quite tricky to get a new entity into the catalog right now. And the way the catalog handles relationships is not really settled either AFAIU. But it's being worked on.
