### ISSUE TITLE
🐛 Bug Report: signing_keys query fails

### ISSUE THREAD

**Issue by ladislav-svob** [backstage/backstage#26457]
### 📜 Description

After migrating to new backend, the query to get keys from `signing_keys` fails every time, because `created_at ` is returned from database as null, even though that when querying the db directly results in the date being returned correctly. This results in users not beign able to authenticate against the auth backend.

### 👍 Expected behavior

The user should be able to authenticate his requests.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/65647f73-2efd-4ac5-aaa3-52ca983f730b)

![image(1)](https://github.com/user-attachments/assets/add0b44e-2b3e-4438-81b0-9e43136a5f84)

### 👟 Reproduction steps

EnterpriseDB Postgres 13.10.14

1. log in
2. open any page that requires auth

### 📃 Provide the context for the Bug.

`{"level":"info","message":"[04/Sep/2024:12:04:01 +0000] \"GET /api/catalog/entity-facets?facet=spec.owner HTTP/1.1\" 401 621 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0\"","service":"rootHttpRouter","type":"incomingRequest"}`

`{"level":"error","message":"Request failed with status 500 Failed to parse date, reason: invalid input, explanation: null","service":"rootHttpRouter","stack":"Error: Failed to parse date, reason: invalid input, explanation: null\n at parseDate (/app/plugins/plugin-auth-backend/dist/index.cjs.js:1628:11)\n at /app/plugins/plugin-auth-backend/dist/index.cjs.js:1649:20\n at Array.map (<anonymous>)\n at DatabaseKeyStore.listKeys (/app/plugins/plugin-auth-backend/dist/index.cjs.js:1647:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async TokenFactory.listPublicKeys (/app/plugins/plugin-auth-backend/dist/index.cjs.js:1550:29)\n at async /app/plugins/plugin-auth-backend/dist/index.cjs.js:1439:22","type":"errorHandler"}`

`{"level":"info","message":"[04/Sep/2024:12:04:01 +0000] \"GET /api/auth/.well-known/jwks.json HTTP/1.1\" 500 198 \"-\" \"jose/v5.6.3\"","service":"rootHttpRouter","type":"incomingRequest"}
`

### 🖥️ Your Environment

I tried to update to next version to try if new versions of dependencies haven't fixed the problem. But the issue started ever since moving to new backend in version v1.29.0.

backstage:  1.31.0-next.1

Dependencies:
  @backstage/app-defaults                                          1.5.11-next.0
  @backstage/backend-app-api                                       0.10.0-next.1, 0.8.0, 0.9.2, 0.9.3
  @backstage/backend-common                                        0.23.3, 0.24.0, 0.24.1, 0.25.0-next.1
  @backstage/backend-defaults                                      0.4.3, 0.4.4, 0.5.0-next.1
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-dynamic-feature-service                       0.2.15
  @backstage/backend-openapi-utils                                 0.1.17, 0.1.18-next.1
  @backstage/backend-plugin-api                                    0.7.0, 0.8.0, 0.8.1, 0.9.0-next.1
  @backstage/backend-tasks                                         0.5.27, 0.6.1
  @backstage/backend-test-utils                                    0.6.0-next.1
  @backstage/catalog-client                                        1.6.6, 1.6.7-next.0
  @backstage/catalog-model                                         1.6.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.27.1-next.1
  @backstage/config-loader                                         1.9.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2
  @backstage/core-compat-api                                       0.3.0-next.1
  @backstage/core-components                                       0.14.11-next.0
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.8.0-next.1
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30
  @backstage/integration                                           1.14.0
  @backstage/plugin-api-docs                                       0.11.9-next.1
  @backstage/plugin-app-backend                                    0.3.74-next.1
  @backstage/plugin-app-node                                       0.1.23, 0.1.25-next.1
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.0-next.1
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.2.0-next.1
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.0-next.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.0-next.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.0-next.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.0-next.1
  @backstage/plugin-auth-backend-module-github-provider            0.2.0-next.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.0-next.1
  @backstage/plugin-auth-backend-module-google-provider            0.2.0-next.1
  @backstage/plugin-auth-backend-module-guest-provider             0.2.0-next.1
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.0-next.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.0-next.1
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.0-next.1
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.0-next.1
  @backstage/plugin-auth-backend-module-okta-provider              0.1.0-next.1
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.0-next.1
  @backstage/plugin-auth-backend                                   0.23.0-next.1
  @backstage/plugin-auth-node                                      0.4.17, 0.5.0, 0.5.1, 0.5.2-next.1
  @backstage/plugin-auth-react                                     0.1.6-next.0
  @backstage/plugin-bitbucket-cloud-common                         0.2.22
  @backstage/plugin-catalog-backend-module-backstage-openapi       0.4.0-next.1
  @backstage/plugin-catalog-backend-module-gitlab                  0.4.2-next.1
  @backstage/plugin-catalog-backend-module-logs                    0.1.0-next.1
  @backstage/plugin-catalog-backend-module-openapi                 0.2.0-next.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.0-next.1
  @backstage/plugin-catalog-backend-module-unprocessed             0.5.0-next.1
  @backstage/plugin-catalog-backend                                1.25.2, 1.25.3-next.1
  @backstage/plugin-catalog-common                                 1.0.26
  @backstage/plugin-catalog-graph                                  0.4.9-next.1
  @backstage/plugin-catalog-import                                 0.12.3-next.1
  @backstage/plugin-catalog-node                                   1.12.5, 1.12.6, 1.12.7-next.1
  @backstage/plugin-catalog-react                                  1.12.4-next.1
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.4
  @backstage/plugin-catalog-unprocessed-entities                   0.2.8-next.0
  @backstage/plugin-catalog                                        1.22.1-next.1
  @backstage/plugin-devtools-backend                               0.4.0-next.1
  @backstage/plugin-devtools-common                                0.1.12
  @backstage/plugin-devtools                                       0.1.18-next.1
  @backstage/plugin-events-backend                                 0.3.10
  @backstage/plugin-events-node                                    0.3.10, 0.3.9, 0.4.0-next.1
  @backstage/plugin-kubernetes-backend                             0.18.6-next.1
  @backstage/plugin-kubernetes-common                              0.8.2
  @backstage/plugin-kubernetes-node                                0.1.19-next.1
  @backstage/plugin-kubernetes-react                               0.4.3-next.0
  @backstage/plugin-kubernetes                                     0.11.14-next.1
  @backstage/plugin-org                                            0.6.29-next.1
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.0-next.1
  @backstage/plugin-permission-backend                             0.5.49-next.1
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.1, 0.8.2, 0.8.3-next.1
  @backstage/plugin-permission-react                               0.4.25
  @backstage/plugin-proxy-backend                                  0.5.6-next.1
  @backstage/plugin-scaffolder-backend-module-azure                0.2.0-next.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.0-next.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.0-next.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.0-next.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.0-next.1
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.0-next.1
  @backstage/plugin-scaffolder-backend-module-github               0.5.0-next.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.5.0-next.1
  @backstage/plugin-scaffolder-backend                             1.25.0-next.1
  @backstage/plugin-scaffolder-common                              1.5.5
  @backstage/plugin-scaffolder-node                                0.4.11-next.1, 0.4.9
  @backstage/plugin-scaffolder-react                               1.12.0-next.1
  @backstage/plugin-scaffolder                                     1.25.0-next.1
  @backstage/plugin-search-backend-module-catalog                  0.2.1, 0.2.2-next.1
  @backstage/plugin-search-backend-module-pg                       0.5.35-next.1
  @backstage/plugin-search-backend-module-techdocs                 0.2.2-next.1
  @backstage/plugin-search-backend-node                            1.3.0, 1.3.1, 1.3.2-next.1
  @backstage/plugin-search-backend                                 1.5.17-next.1
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.8.0-next.1
  @backstage/plugin-search                                         1.4.16-next.1
  @backstage/plugin-signals-react                                  0.0.5-next.0
  @backstage/plugin-techdocs-backend                               1.10.13-next.1
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.14-next.1
  @backstage/plugin-techdocs-node                                  1.12.11-next.1
  @backstage/plugin-techdocs-react                                 1.2.8-next.1
  @backstage/plugin-techdocs                                       1.10.9-next.1
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.12-next.1
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.6.0-next.0
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Mounik-tech** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer

**Comment by DavidSousaZ** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer

**Comment by freben** [comment]
[This](https://github.com/backstage/backstage/blob/c2384b139149f7edd5475701d76016e9938f80c9/plugins/auth-backend/src/identity/DatabaseKeyStore.ts#L37) is where the error is being emitted. I am not sure that it's an _actual_ null, but rather that the `luxon` library didn't have more info to provide so the explanation was null.

I've never worked with EnterpriseDB. I wonder if the pg driver gets something unexpected back in that column.

One thing you could do is to locate that line in your `node_modules` and console.log the actual value of the `date` argument. Let's see what's actually in it.

**Comment by ladislav-svob** [comment]
Thank you for responding, i have already tried to copy plugin-auth-backend to my project and edit the `databaseKeystore.ts` for more info. But the problem truly is that the date itself in the row object is null, i have even tried to set the `created_at` to string in a hope that it would maybe help, in case there is a problem with the format, but the it was still null. Interestingly enough, we propably have the same issue somewhere in the catalog plugin with time of next update of entity. I have tried to look at the versions of Knex used in the old version we had where the issue wasn't present and the new one, but i think both were knex 3.0.0

**Comment by freben** [comment]
Yeah I really can't think of anything that might have reasonably changed in terms of knex or the pg driver lately. 🤔

**Comment by freben** [comment]
I see some old issues that seem related.

https://github.com/knex/knex/issues/4229#issuecomment-760491299

https://github.com/knex/knex/issues/1477#issuecomment-1301637206

https://github.com/knex/knex/issues/2685#issuecomment-402467722

These taken together do seem to imply that this may be related to the underlying pg library instead of knex. Does it help to provide a `version` setting explicitly?

**Comment by freben** [comment]
See also this discussion with the pg maintainer https://github.com/brianc/node-postgres/issues/471

**Comment by ladislav-svob** [comment]
I have already checked that the database returns ISO, but i will try the explicit `version` config, thank you.

**Comment by ladislav-svob** [comment]
The version setting doesn't help. But since this is a pg client problem, i think this issue can be closed and i will open different ticket in correct project. Thank you.

**Comment by Rugvip** [comment]
@ladislav-svob alright, thank you! 👍 If it turns out there's something we can fix on your end, don't hesitate to open a new issue 😁
