### ISSUE TITLE
[cost-insights] Associate/replace Cost Insights entities with entities from the catalog plugin

### ISSUE THREAD

**Issue by brendasukh** [backstage/backstage#2646]
## Feature Suggestion
Cloud costs should be tied to the software catalog entities that incurred the cost. 

## Possible Implementation
Update `Entity` in cost-insights to use `Entity` from the catalog plugin. 

## Context
Cost Insights currently has its own Entity definition; this should instead reference catalog entities where possible. This will enable cloud costs to be shown on pages for catalog entities, and linking to catalog pages from Cost Insights.

Costs may be returned for entities that are not registered in the software catalog; this complicating factor should also be handled.

**Comment by BA1RY** [comment]
Hi @brendasukh I would like to work on this. How do you want me to implement it?

**Comment by brendasukh** [comment]
Hey @BA1RY, thanks for the interest in working on this! Unfortunately, we might have pre-maturely opened this issue up as we are still figuring out the implementation on our side 😅Going to close this up for now until we have more details but until then, you can check out the other first issue[ ideas](https://github.com/backstage/backstage/labels/good%20first%20issue) in backstage
