### ISSUE TITLE
🚀 Feature: Optionally disable user profile picture loading in Azure authentication

### ISSUE THREAD

**Issue by jslott2sigma** [backstage/backstage#26503]
### 🔖 Feature description

Provide the ability to skip the loading of user profile photos in the Microsoft Azure authenticator.

### 🎤 Context

We have noticed the loading of profile photos takes ~400-500ms during login, which isn't necessary for our organization since we load user photos from another service. By disabling the loading of user photos (via a fork of the microsoft authenticator), we have noticed the login experience to be much "snappier".

This issue came up in Issue #20965 too. However in that case, it seems the performance of Azure itself was the issue; we have confirmed that is not the case in our situation.

### ✌️ Possible Implementation

We are currently forking the microsoft authenticator to simply call `done(null, undefined)` in the `ExtendedMicrosoftStrategy`, however we need to fork much of the package to make this change. We are looking to upstream some change that will allow us to avoid forking the code.

Possibilities?
1. Check a "loadPhotos" configuration flag to determine whether to load photos
2. Provide a way to replace the MicrosoftStrategy while minimizing the need to fork much of the rest of the package
3. Remove the User.Read scope, which I believe has to happen on the Azure side, but I'm hesitant to do so since we may need this scope elsewhere.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
Really unfortunate that this is taking so long, both in request ms and that it isn't addressed yet. I think a config option would be the cleanest implementation

**Comment by jslott2sigma** [comment]
@jhaals Thanks for the response! No worries -- we are currently forking code for this now, so we aren't blocked, but just wanted to upstream what I think will be a useful change. I will go ahead with the config option approach.

**Comment by afscrome** [comment]
There is an option for this already - https://backstage.io/docs/integrations/azure/org/#user-photos

**Comment by afscrome** [comment]
Actually you're talking about the login provider, not the entity provider which is different.  Although it's probably not a bad thing to use the photo from the catalog if it already exists.

**Comment by jslott2sigma** [comment]
Thank you @afscrome! In our case we load users from an entirely separate source from Azure (and same with our pictures, which we do use). I think the config option you provided is a terrific example that I think can also be implemented by the Azure authentication provider.

**Comment by camilaibs** [comment]
Thanks @jslott2sigma, your suggestion sounds good to us. Could you please raise a pull request contributing to the `ExtendedMicrosoftStrategy `? We would be happy to provide feedback there 🙂

**Comment by jslott2sigma** [comment]
@camilaibs PR submitted, thanks!
