### ISSUE TITLE
🐛 Bug Report: Unrelated error masks the cause of underlying test failures when assertion values include core services

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#26529]
### 📜 Description

If I have a test where there is an assertion against the input of a mocked function that takes a logger in as one of its arguments...

```ts
describe('repro', () => {
  it('booms', () => {
    const someFunction = jest.fn();

    someFunction({
      logger: mockServices.logger.mock(),
      other: true,
    });

    expect(someFunction).toHaveBeenCalledWith(
      expect.objectContaining({ other: false }),
    );
  });
});
```

If the assertion fails (because the asserted value doesn't match the expectation), instead of seeing an error about the incorrect value, I see the following error:

```
tried to read ServiceRef.T of serviceRef{core.logger}
```

### 👍 Expected behavior

The underlying failed assertion should be printed as expected.

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-09-06 at 12 35 35](https://github.com/user-attachments/assets/912c3596-4797-4860-9968-a5e46fa385b5)

### 👟 Reproduction steps

(See above)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
Thanks for reporting this!
