### ISSUE TITLE
🚀 Feature: docker and devcontainer support out of the box

### ISSUE THREAD

**Issue by peterclemenko** [backstage/backstage#26543]
### 🔖 Feature description

docker and dev container support out of the box would make a lot of sense and make life easier

### 🎤 Context

docker and dev container support out of the box would make a lot of sense and make life easier

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by darylgraham** [comment]
@peterclemenko what is missing from the Docker support? There is a Dockerfile and instructions for use in the docs. Is there something missing that would have made it easier for you to get started?

I’m on board for the devcontainer, but I also recognise that not everyone likes to use them for development.
