### ISSUE TITLE
🚀 Feature: Customize Backstage cli command that create plugins

### ISSUE THREAD

**Issue by brendaHuang-2023** [backstage/backstage#26548]
### 🔖 Feature description

We'd like to run `backstage-cli new --select plugin` and have the option to generate a plugin that uses MUI 5 and custom eslint config. 

### 🎤 Context

We have different eslint config than what the command currently generates, and we use MUI 5 instead of Material UI 4, which is the default of Backstage. Currently we have to manually update files after we generate the plugin. This is a common use case for us, since we have a steady stream of contributors who need to generate new plugins. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Yep, thanks! I re-opened the old one, closing this one as a duplicate
