### ISSUE TITLE
🐛 Bug Report: Page not found when visit Releases menu of Backstage website 

### ISSUE THREAD

**Issue by node** [backstage/backstage#26556]
### 📜 Description

When I click the  "Releases" on the main menu of https://backstage.io/ , it redirects to https://backstage.io/docs/releases/v1.30.0, then got a "Page Not Found" error.

### 👍 Expected behavior

It should display the latest version (v1.30.0) release  info. 

### 👎 Actual Behavior with Screenshots

![CAPTURE_202499_171901](https://github.com/user-attachments/assets/0ea08b57-492d-4947-8f3e-e1fbf3bd1eb9)

### 👟 Reproduction steps

- Go to https://backstage.io/
- Click "Releases" 
- Bug here : Page Not Found 

### 🖥️ Your Environment

Chrome on windows system. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Thanks for logging this @node, I noticed if you click on the drop down for the versions on the far right it loads `1.29.0` which is the previous release, `1.30.0` is the latest. I'm wondering if maybe that file isn't being picked up 🤔

**Comment by freben** [comment]
Ah this probably just means that the release notes were merged into main _after_ the release was cut, and the microsite build is set to target the actual version tag so to speak. Hm. We'll have to look into that; the releases list should always be built from the very latest no matter what.

**Comment by Rugvip** [comment]
Fixed by #26606, porting this back to the current release is a bit cumbersome though, so unfortunately we'll likely leave this broken until the 1.31 next tuesday.

**Comment by Rugvip** [comment]
This was fixed halfway by the merge of #26606 as the release notes are now available. It doesn't properly show the sidebar yet, but expecting that to be fixed by the mainline release tomorrow.

**Comment by camilaibs** [comment]
Hello @node 👋🏻 , can this issue be closed now that https://github.com/backstage/backstage/pull/26606 has been merged?

**Comment by node** [comment]
> Hello @node 👋🏻 , can this issue be closed now that https://github.com/backstage/backstage/pull/26606 has been merged?

Yes, thanks for the great work.
