### ISSUE TITLE
🐛 [Docs] Bug Report: "Edit this page" directs you to a 404 on GitHub

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#26563]
### 📜 Description

If you use the "Edit this page" button at the bottom of any of the pages under https://backstage.io/docs you'll be taken to a 404 page on GitHub.

### 👍 Expected behavior

It should take you to the Markdown file for the page

### 👎 Actual Behavior with Screenshots

It brings you to a 404 page on GitHub

### 👟 Reproduction steps

1. Go here: https://backstage.io/docs/overview/what-is-backstage
2. Scroll to the bottom
3. Click on "Edit this page"

Notice you get a 404 page for this URL: https://github.com/backstage/backstage/edit/master/docs/versioned_docs/version-stable/overview/what-is-backstage.md

### 📃 Provide the context for the Bug.

For people who might want to quickly fix a typo they spot this creates friction for them as they need to hunt down the actual file and honestly they may simply not know where to find it.

Myself I often use it to see the history of a given page

### 🖥️ Your Environment

This is from the microsite since we added versioning. It's not really environment specific.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
This works on the Docusaurus site itself - https://docusaurus.io/docs/versioning - but I can't seem to find the docs on how to make it work 😆

**Comment by Parsifal-M** [comment]
Hey! 👋 

Do we potentially need to look at https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#custom_edit_url until we figure out versioning? An assumption is that because we don't use that versioning structure its not happy 😞 

WDYT?

**Comment by awanlin** [comment]
That seems like a good path to explore, thanks for pointing that out @Parsifal-M! I'll admit I don't have a lot of time to work on this, if you can that would be nice but totally understand if you are in the same spot as me. This issue is here for anyone else who might want to help out!

**Comment by Parsifal-M** [comment]
Hello! 👋 

Had a quick look at this on the weekend, I can't seem to reproduce it locally 😭 not super experienced with the microsite or docosaurus (yet) sadly.

Any ideas how we could reproduce / test it locally? 🤔 💭

**Comment by Rugvip** [comment]
@Parsifal-M ah right you need to replicate the production build where we take a snapshot of the stable docs:

https://github.com/backstage/backstage/blob/8c5c6b8c1ace5ce1a2e6f5e134b0111514ca0b44/.github/workflows/deploy_microsite.yml#L192-L194

Running that command is the most important part, you don't really need to be on the release tag

**Comment by Parsifal-M** [comment]
> @Parsifal-M ah right you need to replicate the production build where we take a snapshot of the stable docs:
> 
> https://github.com/backstage/backstage/blob/8c5c6b8c1ace5ce1a2e6f5e134b0111514ca0b44/.github/workflows/deploy_microsite.yml#L192-L194
> 
> Running that command is the most important part, you don't really need to be on the release tag

Okidoke! Thanks!

Travelling back to the Netherlands today, will take another look tomorrow 🙏

**Comment by Parsifal-M** [comment]
I will close this as its been merged! 👏
