### ISSUE TITLE
🐛 Bug Report: TechDocs - rendering of indented content within lists is inconsistent with GitHub

### ISSUE THREAD

**Issue by mtlewis** [backstage/backstage#26575]
### 📜 Description

Lists with nested indented content only render inconsistently with GitHub in some circumstances.

### 👍 Expected behavior

The following content renders correctly in GitHub:

```markdown
1. First
1. Second
   * Sublist 1

   Nested body text:
   * Sublist 2
   * Sublist 3
1. Third
```

**Demo**

1. First
1. Second
   * Sublist 1

   Nested body text:
   * Sublist 2
   * Sublist 3
1. Third

### 👎 Actual Behavior with Screenshots

In TechDocs, this same content renders incorrectly - after the nested content, bullets and numbered list items are no longer detected.

![Screenshot 2024-09-09 at 15 54 52](https://github.com/user-attachments/assets/bec0c84f-f986-4f39-9650-1043ccc328e2)

### 👟 Reproduction steps

To reproduce, add the content above to a TechDocs markdown file and view it in Backstage.

### 📃 Provide the context for the Bug.

Appreciate that there are often inconsistencies between different markdown renderers - however in general folks expect content to render consistently between TechDocs and GitHub, so unless there's specific conflicts between the two that mean we can't render correctly in both, it would be great to try and get them in sync.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @mtlewis, there's actually a working example of this on the Demo site as it's come up before - https://demo.backstage.io/docs/default/component/backstage-demo/examples/lists/ - from that example:

> The [`techdocs-core`](https://github.com/backstage/mkdocs-techdocs-core) MkDocs plugin includes the [`mdx_truly_sane_lists`](https://github.com/radude/mdx_truly_sane_lists) plugin which has a default of 2, this means that each nested list needs to be 2 spaces under its parent.

We could maybe change this default in `techdocs-core`?

**Comment by mtlewis** [comment]
Thanks for sharing @awanlin! I definitely realise that it's possible to fix the syntax so that it works in both places - but the (perhaps overly ambitious) goal I'm proposing is that we try to fix rendering inconsistencies, so that folks writing documentation can feel confident that if markdown renders correctly in GitHub, it'll render correctly in TechDocs too, and vice versa.

**Comment by kriswest** [comment]
Sorry to see this closed - its taken a while to find a reference for the problem, which we observe in many of our docs. Developers working in GitHub, GitLab or VSCode will expect output to match the previews they see in those environments - it does not.

**Comment by kriswest** [comment]
Its also frustrating that tools like Markdownlint will flag the syntax we need to use in backstage as incorrect:

## Works but flagged as wrong:

```md
Body text introducing list:

1. First numbered bullet
  - Unordered bullet 1
  - Unordered bullet 2
2. Second numbered bullet
```

**GitHub rendering:**

Body text introducing list:

1. First numbered bullet
  - Unordered bullet 1
  - Unordered bullet 2
2. Second numbered bullet

![Image](https://github.com/user-attachments/assets/0c54864f-00bb-484b-a6a4-8b964323f72b)

## Doesn't work but is the syntax required elsewhere:

```md
Body text introducing list:

1. First numbered bullet
    - Unordered bullet 1
    - Unordered bullet 2
2. Second numbered bullet
```
**GitHub rendering:**

1. First numbered bullet
    - Unordered bullet 1
    - Unordered bullet 2
2. Second numbered bullet

![Image](https://github.com/user-attachments/assets/1df44dbf-519a-464f-b4df-d4f0399ea6bf)
