### ISSUE TITLE
🚀 Feature: `IdentityApi.getProfileInfo` extend returned data

### ISSUE THREAD

**Issue by LegendSebastianoL** [backstage/backstage#26650]
### 🔖 Feature description

Currently, the `IdentityApi.getProfileInfo` only returns this info:
```js
type ProfileInfo = {
    email?: string;
    displayName?: string;
    picture?: string;
}
```

In our setup, due to our organization structure and our custom RBAC, we extended the yaml to include this:
```js
spec: {
  profile: {
    displayName: user.profile.displayName,
    email: user.profile.email,
    pillar: user.profile.Pillar,
    tribe: user.profile.Tribe,
    squad: user.profile.Squad,
  },
  memberOf: memberOfGroups,
```

it would be good if any info present inside the profile object is being returned instead of only the `ProfileInfo` one.

### 🎤 Context

having a for loop of keys in the `profile` object would be beneficial for people who use custom structures during the creation of their users.

They could leverage the in-built function without needing to run an extra query to the catalog, to solve the above limitation I had to add this:
```js
const { email } = await identityApi.getProfileInfo();

if (email === undefined) {
  throw new Error('no email found from the profile info');
}

const { items: users } = await catalogApi.getEntities({
  filter: {
    'spec.profile.email': email as string,
  },
});

if (users.length === 0) {
  throw new Error(`User with email ${email} not found in the catalog`);
}

return users[0].spec?.profile;
```

which is OK if is only for one plugin, but if we want to add this logic to more plugins is a lot of duplicate code, or else externalize it into an isomorphic package for reusability but is still extra code to maintain.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
The `ProfileInfo` is intentionally quite slim, as its primarily used to show user information for each auth provider. Fetching the user entity instead is the way to go 👍. If you want to reuse that internally across your plugins, you could create your own [Utility API](https://backstage.io/docs/api/utility-apis) for that purpose.

**Comment by LegendSebastianoL** [comment]
thanks for the explanation :)
