### ISSUE TITLE
🐛 Bug Report: updated plugin documentation is missing

### ISSUE THREAD

**Issue by prasoon-pxc** [backstage/backstage#26695]
### 📜 Description

I want to install some plugins on NBS backstage but it seems there is not any updated documentation for plugins like `to-do` also, I think some of the plugins are updated with NBS but there documentation are not updated. 

### 👍 Expected behavior

Clear documentation and list of plugins which support NBS  backstage 

### 👎 Actual Behavior with Screenshots

No clear documentation of updated plugins 

### 👟 Reproduction steps

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @prasoon-pxc, just curious but where have you looked for this? Can you share a clear list of all the plugins you feel are not up to date? As we have put a lot of effort into updating this documentation having some actionable details would be greatly appreciated!

**Comment by awanlin** [comment]
Also, is this for just plugins here in the Backstage repo or the Community Plugins repo? If this is really just for those in the Community Plugins repo I'll move this issue over there.

**Comment by prasoon-pxc** [comment]
I would say it is more of community plugins repo.

---
If I am checking the `to-do backend` readme file it is still pointing to old backend configuration. 

Example:

https://github.com/backstage/community-plugins/tree/main/workspaces/todo/plugins/todo-backend#installation
https://github.com/backstage/community-plugins/tree/main/workspaces/playlist/plugins/playlist-backend#adding-the-plugin-to-your-packagesbackend

Also, there are some plugins which I want to use :

- Grafana
- playlist
- to-do
- tool-box

Please let me know, If I am still missing something

**Comment by awanlin** [comment]
OK, did you look for the docs in those plugins? Sorry, as those are part of the Community Plugins repo I'm less aware of their state. It would be up to the authors of these plugins to help you. I'm going to move this to the Community Plugins repo as that at least seems like a better location for this.

**Comment by prasoon-pxc** [comment]
Yes, I have check the docs for that plugins but there is not any update.
