### ISSUE TITLE
🐛 Bug Report: Events HTTP Verification Breaks Due to JSON Parsing Changing Request Body

### ISSUE THREAD

**Issue by codingdiaz** [backstage/backstage#26708]
### 📜 Description

The events backend plugin router is using the [express.json()](https://github.com/backstage/backstage/blob/master/plugins/events-backend/src/service/http/HttpPostIngressEventPublisher.ts#L74) middleware. JSON payloads are [already parsed](https://github.com/backstage/backstage/blob/master/plugins/events-node/src/api/http/validation/RequestDetails.ts#L22) by the time a request verifier gets the payload to verify the request. 

There can be very subtle differences in the parsed request body compared to the raw body which will cause verification to fail for valid events. 

For example this is an example for a difference between a GitHub webhook event and the parsed event:

```diff
<           "score": 5.0
---
>           "score": 5
```

The raw un-parsed body should be sent to request verifiers to ensure proper validation.

### 👍 Expected behavior

The raw un-parsed body should be sent to request verifiers to ensure proper validation.

### 👎 Actual Behavior with Screenshots

A parsed and modified body was sent to a verifier causing a valid event to fail.

### 👟 Reproduction steps

This was a little hard to replicate and discover. I had to find some specific GitHub webhook events that were failing (due to parse differences) and re-send them with some logging.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Thank you for opening the issue, it makes sense.
We are happy to provide feedback in a pull request if there is an opportunity for you to contribute with a fix 🙂

**Comment by benjdlambert** [comment]
I think that this is fixed now in #27121. Closing!
