### ISSUE TITLE
🐛 Bug Report: Dependencies of plugins are downloaded when first visiting Backstage homepage

### ISSUE THREAD

**Issue by jslott2sigma** [backstage/backstage#26718]
### 📜 Description

We have noticed that the Javascript bundles for dependencies of plugins are downloaded when first visiting the home page. Is this expected behavior (in the "old" front-end system)?

We have defined a UI component in the plugin as follows:
```
export const MyRoutablePage = myPlugin.provide(
  createRoutableExtension({
    name: "MyRoutablePage ",
    component: () => {
      return import("./components/MyRoutablePage ").then(m => m.MyRoutablePage );
    },
    mountPoint: myRouteRef,
  }),
);
```
and establish a route in `App.tsx`:
```
<Route path="/myroute" element={<MyRoutablePage />} />
```
(This follows, for example `UserSettingsPage` among other examples). We have observed third-party dependencies that are used by the plugin (e.g. ag-grid) gets downloaded immediately upon visiting the home page. As a test, if we remove the route, then those dependencies are not immediately downloaded.

Is this expected behavior?

### 👍 Expected behavior

Dependencies of plugins should only be downloaded when the UI of the plugin is actually navigated to in the UI.

### 👎 Actual Behavior with Screenshots

Upon visiting the home page, we observe in the browser's Network tab that dependencies are plugins are immediately downloaded.

### 👟 Reproduction steps

1. Define a plugin that exports a routable extension as above and this plugin uses some third-party dependency.
2. Define a route in App.tsx that uses that routable extension
3. Navigate to the home page while viewing the Network developer tools tab in the browser
4. Observe dependencies are downloaded immediately.

### 🖥️ Your Environment

OS:   Linux 6.1.85-ts1-amd64 - linux/x64
node: v20.14.0
yarn: 1.23.2
cli:  0.27.0 (installed)
backstage:  1.30.4

Dependencies:
  @backstage/app-defaults                                          1.5.10
  @backstage/backend-app-api                                       0.9.3
  @backstage/backend-common                                        0.24.1
  @backstage/backend-defaults                                      0.4.4
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.17
  @backstage/backend-plugin-api                                    0.8.1
  @backstage/backend-tasks                                         0.6.1
  @backstage/catalog-client                                        1.6.6
  @backstage/catalog-model                                         1.6.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.27.0
  @backstage/config-loader                                         1.9.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2
  @backstage/core-compat-api                                       0.2.8
  @backstage/core-components                                       0.14.3, 0.14.10
  @backstage/core-plugin-api                                       1.9.1, 1.9.3
  @backstage/dev-utils                                             1.0.37
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.7.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30
  @backstage/integration                                           1.14.0
  @backstage/plugin-app-backend                                    0.3.73
  @backstage/plugin-app-node                                       0.1.24
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.17
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.7
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.7
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.2.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.19
  @backstage/plugin-auth-backend-module-github-provider            0.1.21
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.21
  @backstage/plugin-auth-backend-module-google-provider            0.1.21
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.19
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.17
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.6
  @backstage/plugin-auth-backend-module-okta-provider              0.0.17
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.5
  @backstage/plugin-auth-backend                                   0.22.12
  @backstage/plugin-auth-node                                      0.5.1
  @backstage/plugin-bitbucket-cloud-common                         0.2.22
  @backstage/plugin-catalog-backend-module-github                  0.7.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.22
  @backstage/plugin-catalog-backend-module-unprocessed             0.4.11
  @backstage/plugin-catalog-backend                                1.25.2
  @backstage/plugin-catalog-common                                 1.0.26
  @backstage/plugin-catalog-node                                   1.12.6
  @backstage/plugin-catalog-react                                  1.12.3
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.4
  @backstage/plugin-catalog                                        1.22.0
  @backstage/plugin-devtools-backend                               0.3.10
  @backstage/plugin-devtools-common                                0.1.12
  @backstage/plugin-events-node                                    0.3.10
  @backstage/plugin-home-react                                     0.1.16
  @backstage/plugin-home                                           0.7.9
  @backstage/plugin-org                                            0.6.28
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.2
  @backstage/plugin-permission-react                               0.4.25
  @backstage/plugin-proxy-backend                                  0.5.5
  @backstage/plugin-scaffolder-backend-module-azure                0.1.16
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.14
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.16
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.14
  @backstage/plugin-scaffolder-backend-module-github               0.4.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.6
  @backstage/plugin-scaffolder-backend                             1.24.1
  @backstage/plugin-scaffolder-common                              1.5.5
  @backstage/plugin-scaffolder-node                                0.4.10
  @backstage/plugin-search-backend-module-catalog                  0.2.1
  @backstage/plugin-search-backend-module-pg                       0.5.34
  @backstage/plugin-search-backend-module-techdocs                 0.2.1
  @backstage/plugin-search-backend-node                            1.3.1
  @backstage/plugin-search-backend                                 1.5.16
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.7.14
  @backstage/plugin-search                                         1.4.15
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.12
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-node                                  1.12.10
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.11
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.10
  @backstage/theme                                                 0.5.2, 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jslott2sigma** [comment]
Bump on this please. It would be really helpful to just get an idea of what to expect, so I know where I can look to debug further. Thanks!

**Comment by Rugvip** [comment]
Ah sorry, realized I never replied to this.

I had a look at this when you posted it originally, and couldn't reproduce the issue using your reproduction steps. As far as I can tell they assets are not loaded until you actually browse to `/myroute`.

It could be that you have a separate eager import of `MyRoutablePage` through a different code path?

**Comment by jslott2sigma** [comment]
Closing out this issue. We identified the problem. From the plugin, we exported a React component in the `index.ts` that uses the transitive dependencies and even though this component was never imported or used by the front-end application itself, removing the unused export solved the issue. I'm not sure I totally understand why though. Thanks so much for the help!
