### ISSUE TITLE
🚀 Feature: Kubernetes plugin: logs --previous=true

### ISSUE THREAD

**Issue by ifkit** [backstage/backstage#26726]
### 🔖 Feature description

An additional button that shows logs for the previous container instance. Equivalent to `kubectl logs -p ...`.

### 🎤 Context

Key feature for troubleshooting. https://github.com/backstage/backstage/issues/15753

### ✌️ Possible Implementation

function `getPodLogs()` already has the parameter `previous` in KubernetesProxyClient.ts

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Arup-Chauhan** [comment]
Hi @ifkit, @camilaibs 

I wanted to contribute to this issue, and I think we can build upon the suggestion you gave. Here’s one way we can go about it:

1. In `KubernetesProxyClient.ts`, locate the `getPodLogs()` function, which already fetches logs. We'll ensure it can handle logs from the *previous* container instance.
   
2. Introduce a "View Previous Logs" button in the UI, allowing users to easily check logs from before a pod restarted.

3. When clicked, the button will trigger the log retrieval with the `--previous=true` flag, using the existing infrastructure.

Let me think what you think of this approach, and I can possibly collaborate on this issue.

**Comment by camilaibs** [comment]
@backstage/kubernetes-maintainers any recommendations?

**Comment by mclarke47** [comment]
Hey all, the code for this [exists already](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-react/src/components/Pods/PodLogs/PodLogs.tsx#L46) and is used in the error detection functionality.

Did you want to suggest adding this as a option somewhere else?

**Comment by Arup-Chauhan** [comment]
> Hey all, the code for this [exists already](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-react/src/components/Pods/PodLogs/PodLogs.tsx#L46) and is used in the error detection functionality.
> 
> Did you want to suggest adding this as a option somewhere else?

Are these logs only available when the pods are running into error? Because I am assuming the original need was for collecting the logs even for the successful pod instances as well.
