### ISSUE TITLE
🐛 Bug Report: Unable to register entities in software catalog that have URL longer than 255 chars

### ISSUE THREAD

**Issue by 04kash** [backstage/backstage#26747]
### 📜 Description

Registering a git repo with a Url longer than 255 chars results in the follow errors:
```
024-09-17T16:11:27.926Z backstage error Filtered internal error with logId=2ed5833c8aa18af867ba from response insert into "locations" ("id", "target", "type") values ($1, $2, $3) - value too long for type character varying(255) type=errorHandler logId=2ed5833c8aa18af867ba length=99 name=error severity=ERROR code=22001 detail=undefined hint=undefined position=undefined internalPosition=undefined internalQuery=undefined where=undefined schema=undefined table=undefined column=undefined dataType=undefined constraint=undefined file=varchar.c line=632 routine=varchar stack=error: insert into "locations" ("id", "target", "type") values ($1, $2, $3) - value too long for type character varying(255)
```
```
stack=error: insert into "refresh_keys" ("entity_id", "key") values ($1, $2) - value too long for type character varying(255) 
```

### 👍 Expected behavior

The entity should be registered in the catalog.

### 👎 Actual Behavior with Screenshots

It results in the errors specified above.

Screenshot:
![Screenshot from 2024-09-17 13-06-44](https://github.com/user-attachments/assets/26c216f5-b259-40f8-9fd7-07f97ce2625e)

### 👟 Reproduction steps

Try to add a repo with a long Url (eg: https://gitlab.com/backstage-test-1/very-long-group-name-that-exceeds-255-characters-just-to-test-the-limits-of-url-length-in-the-catalog-info-yaml-file-and-see-how-the-backstage-system-handles-it-making-it-as-long-as-possible/test-1/-/blob/main/catalog-info.yaml) as an entity into the software catalog

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Yep we need to be smarter about huge refresh keys. See discussion in the PR.
