### ISSUE TITLE
🐛 Bug Report: incorrect PluginCacheManager and CacheManager deprecation warnings

### ISSUE THREAD

**Issue by ericis** [backstage/backstage#26791]
## Incorrect deprecation recommendations

Use of `PluginCacheManager` from the "@backstage/backend-common" package includes an invalid deprecation warning to:

> Use `PluginCacheManager` from the @backstage/backend-defaults package instead

<https://backstage.io/docs/reference/backend-common.plugincachemanager/>

The "@backstage/backend-common" package also contains the deprecated `CacheManager` that recommends:

> Use `CacheManager` from the @backstage/backend-defaults package instead

<https://backstage.io/docs/reference/backend-common.cachemanager/>

However, the "@backstage/backend-defaults" package does not contain a `PluginCacheManager` or `CacheManager`.

<https://backstage.io/docs/reference/backend-defaults/>

## Example of a correct deprecation recommendation

The "@backstage/backend-common" package also includes the deprecated `cacheToPluginCacheManager()` function and recommends:

> Migrate to use the new CacheService instead.

<https://backstage.io/docs/reference/backend-common.cachetoplugincachemanager/>

_\*Note: this deprecation message could probably also benefit from noting that it is in the "@backstage/backend-plugin-api" package._

### 👍 Expected behavior

Clearer deprecation notices that are possible to take action on.

### 👎 Actual Behavior with Screenshots

_See links and descriptions in bug report._

### 👟 Reproduction steps

n/a

### 📃 Provide the context for the Bug.

n/a

### 🖥️ Your Environment

n/a

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by knowacki23** [comment]
> Hi @ericis 👋🏻 , you can import `CacheManager` from the `@backstage-defaults/cache` subpath, here is an example:
> 
> ```ts
> import { CacheManager } from "@backstage-defaults/cache";
> ```
> 
> And you can call the `CacheManager.forPlugin` method to get a `CacheService` for a plugin.

Hey, I think the import should be:
```ts
import { CacheManager } from "@backstage/backend-defaults/cache";

```
