### ISSUE TITLE
🐛 Bug Report: Origin 'http://localhost:7007' is not allowed

### ISSUE THREAD

**Issue by rjangelov** [backstage/backstage#26795]
### 📜 Description

GitHub auth has been configured and working in dev mode(yarn dev) also when running it in a docker container in production mode.
The problem comes when I deploy my image via the backstage Helm chart on K8S.

### 👍 Expected behavior

Successful login to Backstage via GitHub.

### 👎 Actual Behavior with Screenshots

"Origin 'http://localhost:7007' is not allowed" Error after GitHub login.

### 👟 Reproduction steps

npx @backstage/create-app@latest
Customise the frontend - https://backstage.io/docs/getting-started/app-custom-theme
Configure GitHub auth - https://backstage.io/docs/auth/, https://backstage.io/docs/auth/github/provider/, 
Configure permissions - https://backstage.io/docs/permissions/overview
Build the image(Host build) - https://backstage.io/docs/deployment/docker

Deploy the image through Helm values on a k8s cluster.

### 📃 Provide the context for the Bug.

Not able to log in.

### 🖥️ Your Environment

Browsers Chrome/Mozilla

app:
  baseUrl: http://localhost:7007
backend:
  baseUrl: http://localhost:7007
  listen: :7007
  database:
    client: better-sqlite3
    connection: <secret>
  cors:
    origin: http://localhost:7007
    methods:
      - GET
      - HEAD
      - PATCH
      - POST
      - PUT
      - DELETE
    credentials: true
    Access-Control-Allow-Origin: "*"
techdocs:
  builder: local
  generator:
    runIn: docker
  publisher:
    type: local
auth:
  environment: production
  providers:
    guest: {}
    github:
      production:
        clientId: KJHKH89ds798ldssd
        clientSecret: <secret>
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        - Component
        - System
        - API
        - Resource
        - Location
  locations:
    - type: file
      target: ./examples/entities.yaml
    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow:
            - Template
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow:
            - User
            - Group
permission:
  enabled: true

 % yarn backstage-cli info
OS:   Darwin 24.0.0 - darwin/arm64
node: v18.20.4
yarn: 4.4.1
cli:  0.27.1 (installed)
backstage:  1.31.1

Dependencies:
  @backstage/app-defaults                                          1.5.11
  @backstage/backend-app-api                                       1.0.0
  @backstage/backend-common                                        0.25.0
  @backstage/backend-defaults                                      0.5.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.18
  @backstage/backend-plugin-api                                    1.0.0
  @backstage/catalog-client                                        1.7.0
  @backstage/catalog-model                                         1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.8
  @backstage/cli                                                   0.27.1
  @backstage/config-loader                                         1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.15.0
  @backstage/core-compat-api                                       0.3.0
  @backstage/core-components                                       0.15.0
  @backstage/core-plugin-api                                       1.9.4
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.9
  @backstage/frontend-plugin-api                                   0.8.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.31
  @backstage/integration                                           1.15.0
  @backstage/plugin-api-docs                                       0.11.9
  @backstage/plugin-app-backend                                    0.3.74
  @backstage/plugin-app-node                                       0.1.25
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.0
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.0
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.2.0
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.0
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.0
  @backstage/plugin-auth-backend-module-github-provider            0.2.0
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.0
  @backstage/plugin-auth-backend-module-google-provider            0.2.0
  @backstage/plugin-auth-backend-module-guest-provider             0.2.0
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.0
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.0
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.0
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.0
  @backstage/plugin-auth-backend-module-okta-provider              0.1.0
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.0
  @backstage/plugin-auth-backend                                   0.23.0
  @backstage/plugin-auth-node                                      0.5.2
  @backstage/plugin-auth-react                                     0.1.6
  @backstage/plugin-bitbucket-cloud-common                         0.2.23
  @backstage/plugin-catalog-backend-module-logs                    0.1.0
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.0
  @backstage/plugin-catalog-backend                                1.26.0
  @backstage/plugin-catalog-common                                 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.9
  @backstage/plugin-catalog-import                                 0.12.3
  @backstage/plugin-catalog-node                                   1.13.0
  @backstage/plugin-catalog-react                                  1.13.0
  @backstage/plugin-catalog                                        1.23.0
  @backstage/plugin-events-node                                    0.4.0
  @backstage/plugin-kubernetes-backend                             0.18.6
  @backstage/plugin-kubernetes-common                              0.8.3
  @backstage/plugin-kubernetes-node                                0.1.19
  @backstage/plugin-kubernetes-react                               0.4.3
  @backstage/plugin-kubernetes                                     0.11.14
  @backstage/plugin-org                                            0.6.29
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.0
  @backstage/plugin-permission-backend                             0.5.49
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.3
  @backstage/plugin-permission-react                               0.4.26
  @backstage/plugin-proxy-backend                                  0.5.6
  @backstage/plugin-scaffolder-backend-module-azure                0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.0
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.0
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.0
  @backstage/plugin-scaffolder-backend-module-github               0.5.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.5.0
  @backstage/plugin-scaffolder-backend                             1.25.0
  @backstage/plugin-scaffolder-common                              1.5.6
  @backstage/plugin-scaffolder-node                                0.4.11
  @backstage/plugin-scaffolder-react                               1.12.0
  @backstage/plugin-scaffolder                                     1.25.0
  @backstage/plugin-search-backend-module-catalog                  0.2.2
  @backstage/plugin-search-backend-module-pg                       0.5.35
  @backstage/plugin-search-backend-module-techdocs                 0.2.2
  @backstage/plugin-search-backend-node                            1.3.2
  @backstage/plugin-search-backend                                 1.5.17
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.8.0
  @backstage/plugin-search                                         1.4.16
  @backstage/plugin-signals-react                                  0.0.5
  @backstage/plugin-techdocs-backend                               1.10.13
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.14
  @backstage/plugin-techdocs-node                                  1.12.11
  @backstage/plugin-techdocs-react                                 1.2.8
  @backstage/plugin-techdocs                                       1.10.9
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.12
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.6.0
  @backstage/theme                                                 0.5.7
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.9

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hi @rjangelov 👋🏻 , could you double check if the app base url is set to localhost in your app config file?

**Comment by rjangelov** [comment]
Hello @camilaibs. Thank you for your reply.

Yes, it’s in the config.

I am now thinking that it is a networking thing since my cluster is running on minikube. Respectively localhost on my machine might be treated different than the cluster.

**Comment by Rugvip** [comment]
The error message `Origin 'http://localhost:7007/' is not allowed` indicates that the `app.baseUrl` is set to an incompatible value. There's a check that makes sure that the requested frontend origin matches one of the allowed app origins, which by default is set based on `app.baseUrl`.
