### ISSUE TITLE
🐛 Bug Report: Backstage upgradation from 1.29.2 to 1.31.1 is not building correctly

### ISSUE THREAD

**Issue by Nitinvonage** [backstage/backstage#26793]
### 📜 Description

While moving from v1.29.2 to latest(1.31.1) Yarn install is failing because the remote archive doesn't match the expected checksum for typescript@patch:typescript@npm%3A5.5.4

### 👍 Expected behavior

yarn install should work

### 👎 Actual Behavior with Screenshots

When doing yarn install its giving error suggesting "typescript@patch:typescript@npm%3A5.5.4#optional!builtin<compat/typescript>::version=5.5.4&hash=379a07: The remote archive doesn't match the expected checksum"
![image](https://github.com/user-attachments/assets/90a1ce16-395a-4ba8-8d05-bd6759673f4f)

### 👟 Reproduction steps

1. During upgrdation to latest version Did `yarn backstage-cli versions:bump`
2. Used upgrade helper to make other required changes
3. Did yarn install
4. yarn install failed with error - `typescript@patch:typescript@npm%3A5.5.4#optional!builtin<compat/typescript>::version=5.5.4&hash=379a07: The remote archive doesn't match the expected checksum`
5. Tried yarn cache clean but same result
6. removed the yarn.lock file and did yarn install again - this worked but then
7. It failed while building the docker image, here in docker file  
```
RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000     
yarn workspaces focus --all --production"
```
8. This is the error while building yarn workspace inside docker image 
```
#13 29.55 ➤ YN0009: │ cpu-features@npm:0.0.10 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-f6ebe301/build.log)
#13 30.09 ➤ YN0009: │ better-sqlite3@npm:11.3.0 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-2fa8f62d/build.log)
#13 30.09 ➤ YN0009: │ isolated-vm@npm:4.7.2 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-868727d2/build.log)

```

### 📃 Provide the context for the Bug.

Not able to do yarn install

Docker file
```
# This dockerfile builds an image for the backend package.
# It should be executed with the root of the repo as docker context.
#
# Before building this image, be sure to have run the following commands in the repo root:
#
# yarn install
# yarn tsc
# yarn build:backend
#
# Once the commands have been run, you can build the image using `yarn build-image`

FROM node:20-buster-slim

# Install isolate-vm dependencies, these are needed by the @backstage/plugin-scaffolder-backend.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends python3 g++ build-essential && \
    yarn config set python /usr/bin/python3

# RUN mkdir /app && chown node:node /app

# From here on we use the least-privileged `node` user to run the backend.
# USER node
# This should create the app dir as `node`.
# If it is instead created as `root` then the `tar` command below will fail: `can't create directory 'packages/': Permission denied`.
# If this occurs, then ensure BuildKit is enabled (`DOCKER_BUILDKIT=1`) so the app dir is correctly created as `node`.
WORKDIR /app
# This switches many Node.js dependencies to production mode.
ENV NODE_ENV=production

# Copy over Yarn 3+ configuration, release, and plugins
COPY .yarn ./.yarn
COPY .yarnrc.yml ./

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
# COPY --chown=node:node yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

# RUN --mount=type=cache,target=/home/node/.yarn/berry/cache,sharing=locked,uid=1000,gid=1000 \
#     yarn workspaces focus --all --production

RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn workspaces focus --all --production && rm -rf "$(yarn cache clean)"

# Then copy the rest of the backend bundle, along with any other files we might want.
#COPY --chown=node:node packages/backend/dist/bundle.tar.gz app-config.yaml ./
COPY packages/backend/dist/bundle.tar.gz app-config.yaml backstage.json ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["node", "packages/backend", "--config", "app-config.yaml", "--config", "/app/overrides/app-config.overrides.yaml"]
```

### 🖥️ Your Environment

yarn 4.4.1
node v18.12.1
OS - MAC 14.6.1 (23G93)

 "@backstage-community/plugin-sonarqube-backend": "^0.2.23",
    "@backstage/backend-defaults": "^0.5.0",
    "@backstage/backend-plugin-api": "^1.0.0",
    "@backstage/catalog-client": "^1.7.0",
    "@backstage/catalog-model": "^1.7.0",
    "@backstage/config": "^1.2.0",
    "@backstage/plugin-app-backend": "^0.3.74",
    "@backstage/plugin-auth-backend": "^0.23.0",
    "@backstage/plugin-auth-backend-module-github-provider": "^0.2.0",
    "@backstage/plugin-auth-backend-module-guest-provider": "^0.2.0",
    "@backstage/plugin-auth-node": "^0.5.2",
    "@backstage/plugin-catalog-backend": "^1.26.0",
    "@backstage/plugin-catalog-backend-module-github": "^0.7.3",
    "@backstage/plugin-catalog-backend-module-github-org": "^0.3.0",
    "@backstage/plugin-catalog-backend-module-logs": "^0.1.0",
    "@backstage/plugin-catalog-backend-module-scaffolder-entity-model": "^0.2.0",
    "@backstage/plugin-catalog-backend-module-unprocessed": "^0.5.0",
    "@backstage/plugin-catalog-common": "^1.1.0",
    "@backstage/plugin-devtools-backend": "^0.4.0",
    "@backstage/plugin-kubernetes-backend": "^0.18.6",
    "@backstage/plugin-permission-backend": "^0.5.49",
    "@backstage/plugin-permission-backend-module-allow-all-policy": "^0.2.0",
    "@backstage/plugin-permission-common": "^0.8.1",
    "@backstage/plugin-permission-node": "^0.8.3",
    "@backstage/plugin-proxy-backend": "^0.5.6",
    "@backstage/plugin-scaffolder-backend": "^1.25.0",
    "@backstage/plugin-scaffolder-backend-module-github": "^0.5.0",
    "@backstage/plugin-search-backend": "^1.5.17",
    "@backstage/plugin-search-backend-module-catalog": "^0.2.2",
    "@backstage/plugin-search-backend-module-elasticsearch": "^1.5.6",
    "@backstage/plugin-search-backend-module-pg": "^0.5.35",
    "@backstage/plugin-search-backend-module-techdocs": "^0.2.2",
    "@backstage/plugin-search-backend-node": "^1.3.2",
    "@backstage/plugin-techdocs-backend": "^1.10.13",
    "@gitbeaker/node": "^34.6.0",
    "@internal/common-utils": "workspace:^",
    "@internal/plugin-home-dashboard-backend": "^0.2.0",
    "@roadiehq/scaffolder-backend-module-http-request": "^4.3.2",
    "@types/cookie-parser": "^1.4.3",
    "@types/node-jose": "^1.1.10",
    "aws-sdk": "^2.1379.0",
    "cookie-parser": "^1.4.6",
    "express": "^4.17.1",
    "express-prom-bundle": "^6.4.1",
    "express-promise-router": "^4.1.0",
    "fs-extra": "^11.1.1",
    "jose": "^4.8.1",
    "jwt-decode": "^3.1.2",
    "knex": "^2.2.0",
    "luxon": "^2.3.1",
    "node-gyp": "^10.0.0",
    "node-jose": "^2.1.1",
    "pg": "^8.11.3",
    "prom-client": "^14.0.1",
    "unzip-stream": "0.3.1",
    "verbal-expressions": "^1.0.2",
    "winston": "^3.2.1"

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by camilaibs** [comment]
Hi @Nitinvonage, could you run `YARN_CHECKSUM_BEHAVIOR=update yarn` and see if that solves the issue?

**Comment by paladini** [comment]
@camilaibs , this command worked for me. Thanks!
