### ISSUE TITLE
🐛 Bug Report: App startup fails with Error: insert into "static_assets_cache"

### ISSUE THREAD

**Issue by hosamana** [backstage/backstage#26814]
### 📜 Description

When attempting to insert data into the static_assets_cache table in PostgreSQL using Knex.js, an error occurs indicating invalid input syntax for type bytea. This issue arises due to improper handling of binary data meant for a bytea column.

### 👍 Expected behavior

The binary data should be correctly inserted into the bytea column without any errors.

### 👎 Actual Behavior with Screenshots

An error occurs indicating invalid input syntax for type bytea.

**Error Message:**

```
ForwardedError: Plugin 'app' startup failed; caused by Error: insert into "static_assets_cache" ("content", "namespace", "path") values ($1, $2, $3) on conflict ("namespace", "path") do nothing - invalid input syntax for type bytea
    at /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:704:19
    at async /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:703:11
    at async Promise.all (index 0)
    at async #doStart (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:657:5)
    at async BackendInitializer.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:582:5)
    at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:867:5) {
  cause: Error: insert into "static_assets_cache" ("content", "namespace", "path") values ($1, $2, $3) on conflict ("namespace", "path") do nothing - invalid input syntax for type bytea
      at Client._emitResult (/app/node_modules/pg-native/index.js:180:26)
      at Client._read (/app/node_modules/pg-native/index.js:222:31)
      at PQ.emit (node:events:518:28) {
    severity: 'ERROR',
    code: '22P02',
    where: "unnamed portal parameter $1 = '...'",
    file: 'varlena.c',
    line: '335',
    routine: 'byteain'
  }
}
```

### 👟 Reproduction steps

Just trying to run the app in non-development mode.

### 📃 Provide the context for the Bug.

**Root Cause:**
The issue is due to improper encoding/formatting of binary data being inserted into the bytea column in PostgreSQL.

**Debugging Insights:**
From initial debugging, it appears the line [StaticAssetsStore.ts#L120](https://github.com/backstage/backstage/blob/master/plugins/app-backend/src/lib/assets/StaticAssetsStore.ts#L120) is causing the issue. Modifying it to the following seems to fix the problem:

```
Buffer.from(await asset.content()).toString('base64')
```

### 🖥️ Your Environment

Database: PostgreSQL v15.8
Node.js Version: v20.11.0
Backstage Version: v1.31.1
OS: Red Hat Enterprise Linux 8.10 (Ootpa)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by camilaibs** [comment]
@hosamana, could you please create a repro repo that contains a file that triggers this issue? It would be very helpful to us.

**Comment by hosamana** [comment]
If I recall correctly from my tests, this happens with all static files in the directory. The issue completely disappeared when I went ahead and `base64` encoded the contents of the file.

I can try to isolate the problem further with the help of a fresh installation. I would need some time for this though. Currently, I'm planning on disabling static assets cache altogether.

**Comment by freben** [comment]
I see `pg-native` in there - what do the `backend.database` settings look like in your app-config? If you've explicitly set `client: pg-native`, I think that would leave to issues.

You probably do not want to disable that cache. People will likely get problematic 404 errors at the time right after a redeploy with a changed frontend.

**Comment by hosamana** [comment]
This is how our `backend.database` config looks like:

```
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DATABASE}
    pluginDivisionMode: schema
```

**Comment by hosamana** [comment]
Unsetting the above leads to the following:

```
/app/node_modules/pg-protocol/dist/parser.js:270                                                                                                                                                                                        │
│                 throw new Error('Unknown authenticationOk message type ' + code);                                                                                                                                                       │
│                 ^                                                                                                                                                                                                                       │
│                                                                                                                                                                                                                                         │
│ Error: Unknown authenticationOk message type 7                                                                                                                                                                                          │
│     at Parser.parseAuthenticationResponse (/app/node_modules/pg-protocol/dist/parser.js:270:23)                                                                                                                                         │
│     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:116:29)                                                                                                                                                        │
│     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)                                                                                                                                                                │
│     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)                                                                                                                                                           │
│     at Socket.emit (node:events:518:28)                                                                                                                                                                                                 │
│     at addChunk (node:internal/streams/readable:559:12)                                                                                                                                                                                 │
│     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)                                                                                                                                                              │
│     at Readable.push (node:internal/streams/readable:390:5)                                                                                                                                                                             │
│     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)                                                                                                                                                                      │
│     at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by freben** [comment]
What's your db provider? Are you using some odd way of connecting to it, like are there intermediaries between backstage and the actual database?

**Comment by hosamana** [comment]
I think we have GSSAPI enabled. This might be the reason why we need `pg-native`. Is there a way to get static assets cache working with `pg-native`?

**Comment by benjdlambert** [comment]
Hmm looks like we might be running into a `pg-native` bug here. 

https://github.com/brianc/node-postgres/issues/980
https://github.com/brianc/node-postgres/issues/2426

Maybe there's some fix that we can contribute to Backstage for this, but I would say that even if we were to fix this particular issues, here be dragons as its not officially supported.

There's some workarounds in some of those issues, do you want to try some of them and maybe contribute a fix? :pray:
