### ISSUE TITLE
🐛 Bug Report: Scaffolder Template Not Preserving Changes

### ISSUE THREAD

**Issue by zthfmh** [backstage/backstage#26826]
### 📜 Description

Hello, we recently found that a number of our scaffolder templates no longer update their fields the second time someone goes back and modifies those input values. The same behavior can also be seen on a freshly installed stock Backstage app that is at version `1.31.1` (latest at the time of writing):

https://github.com/user-attachments/assets/f91e695e-c98a-4007-8f16-f073f8476c3a

Inspecting a custom written scaffolder field that suffers from the same issue, we realized that `props.formContext.formData` seems to be preserving a copy of the previous state which overwrites the newer value passed in via `props.onChange`. The package @backstage/plugin-scaffolder-react might be related to this bug since downgrading it to 1.8.3 solves the problem. 

### 👍 Expected behavior

Before submitting the scaffolder form, we should be able to go back to a previous step and modify any fields there, and the updated values should be preserved on both the field itself and the review screen.

### 👎 Actual Behavior with Screenshots

Only the first entered value is preserved, any subsequent changes will be lost which essentially renders the form uneditable.

### 👟 Reproduction steps

Shown in the video attached

### 📃 Provide the context for the Bug.

Someone should be able to modify any previously entered field value before the actual submission.

### 🖥️ Your Environment

OS:   Darwin 23.6.0 - darwin/arm64
node: v20.16.0
yarn: 4.4.1
cli:  0.27.1 (installed)
backstage:  1.31.1

Dependencies:
  @backstage/app-defaults                                          1.5.11
  @backstage/backend-app-api                                       1.0.0
  @backstage/backend-common                                        0.25.0
  @backstage/backend-defaults                                      0.5.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.18
  @backstage/backend-plugin-api                                    1.0.0
  @backstage/catalog-client                                        1.7.0
  @backstage/catalog-model                                         1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.8
  @backstage/cli                                                   0.27.1
  @backstage/config-loader                                         1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.15.0
  @backstage/core-compat-api                                       0.3.0
  @backstage/core-components                                       0.15.0
  @backstage/core-plugin-api                                       1.9.4
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.9
  @backstage/frontend-plugin-api                                   0.8.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.31
  @backstage/integration                                           1.15.0
  @backstage/plugin-api-docs                                       0.11.9
  @backstage/plugin-app-backend                                    0.3.74
  @backstage/plugin-app-node                                       0.1.25
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.0
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.0
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.2.0
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.0
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.0
  @backstage/plugin-auth-backend-module-github-provider            0.2.0
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.0
  @backstage/plugin-auth-backend-module-google-provider            0.2.0
  @backstage/plugin-auth-backend-module-guest-provider             0.2.0
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.0
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.0
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.0
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.0
  @backstage/plugin-auth-backend-module-okta-provider              0.1.0
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.0
  @backstage/plugin-auth-backend                                   0.23.0
  @backstage/plugin-auth-node                                      0.5.2
  @backstage/plugin-auth-react                                     0.1.6
  @backstage/plugin-bitbucket-cloud-common                         0.2.23
  @backstage/plugin-catalog-backend-module-logs                    0.1.0
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.0
  @backstage/plugin-catalog-backend                                1.26.0
  @backstage/plugin-catalog-common                                 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.9
  @backstage/plugin-catalog-import                                 0.12.3
  @backstage/plugin-catalog-node                                   1.13.0
  @backstage/plugin-catalog-react                                  1.13.0
  @backstage/plugin-catalog                                        1.23.0
  @backstage/plugin-events-node                                    0.4.0
  @backstage/plugin-kubernetes-backend                             0.18.6
  @backstage/plugin-kubernetes-common                              0.8.3
  @backstage/plugin-kubernetes-node                                0.1.19
  @backstage/plugin-kubernetes-react                               0.4.3
  @backstage/plugin-kubernetes                                     0.11.14
  @backstage/plugin-org                                            0.6.29
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.0
  @backstage/plugin-permission-backend                             0.5.49
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.3
  @backstage/plugin-permission-react                               0.4.26
  @backstage/plugin-proxy-backend                                  0.5.6
  @backstage/plugin-scaffolder-backend-module-azure                0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.0
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.0
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.0
  @backstage/plugin-scaffolder-backend-module-github               0.5.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.5.0
  @backstage/plugin-scaffolder-backend                             1.25.0
  @backstage/plugin-scaffolder-common                              1.5.6
  @backstage/plugin-scaffolder-node                                0.4.11
  @backstage/plugin-scaffolder-react                               1.12.0
  @backstage/plugin-scaffolder                                     1.25.0
  @backstage/plugin-search-backend-module-catalog                  0.2.2
  @backstage/plugin-search-backend-module-pg                       0.5.35
  @backstage/plugin-search-backend-module-techdocs                 0.2.2
  @backstage/plugin-search-backend-node                            1.3.2
  @backstage/plugin-search-backend                                 1.5.17
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.8.0
  @backstage/plugin-search                                         1.4.16
  @backstage/plugin-signals-react                                  0.0.5
  @backstage/plugin-techdocs-backend                               1.10.13
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.14
  @backstage/plugin-techdocs-node                                  1.12.11
  @backstage/plugin-techdocs-react                                 1.2.8
  @backstage/plugin-techdocs                                       1.10.9
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.12
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.6.0
  @backstage/theme                                                 0.5.7
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.9

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
@benjdlambert @acierto any idea of the root cause of this? and if, any idea if this is such a bug that requires a patch release?

**Comment by benjdlambert** [comment]
I have a feeling that it's most likely something to do with some of the state changing here https://github.com/backstage/backstage/pull/26363 @jboeijenga do you have some time to look into this issue? :pray:

**Comment by lucasmdrs** [comment]
I tried to pin the issue and `@backstage/plugin-scaffolder-react@1.12.0-next.1` was the minimal version working, [1.12.0-next.2](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-react/CHANGELOG.md#1120-next2) had the issue described here.

**Comment by jboeijenga** [comment]
That brings it back to my change indeed. Not sure what is going wrong here, I thought I've tested all scenarios.. I guess the best thing to do now is to roll it back and let me have some more time to work on a better solution for this.

**Comment by jboeijenga** [comment]
@benjdlambert
The issue is that there is a single form for multiple steps. The changes I have made to split formState from a single object to a state per step is not handled correctly since the onChange of the form can be triggered while the correct formData for that step is not yet set in the form. Therefore the onChange is triggered with the wrong data for that step and the wrong data is set causing to overwrite existing data or writing wrong data to that step.

I have worked on two solution directions:
1) Split the form into multiple forms per step, the challenge here is how to handle the initial data set by the query, since this is not split up into the steps the form has.
2) Set a timeout while navigating between steps and ignore the onChange event in that time. This is not super nice since the update of the form will take place a couple of ms after navigating.

Do you see other options to fix this?

**Comment by Vity01** [comment]
Any chance to get it into 1.32.2? It's quite nasty bug, the only workaround is to update templates.

**Comment by benjdlambert** [comment]
@Vity01 there's a PR to fix this but it's still broken https://github.com/backstage/backstage/pull/26929#issuecomment-2413079497 if we can get a fix for it i'm happy to patch it, but theres comments that need addressing

**Comment by benjdlambert** [comment]
I'm looking at trying to fix this another way, will try and get something out today.

**Comment by benjdlambert** [comment]
@florinnania thanks for raising this.

I'm not sure that this is the same issue though as this.

I'm also not sure what you're trying to do in the template, can you explain a little more what you expect to see and what's happening? :pray:

**Comment by florinnania** [comment]
@benjdlambert basically I'm trying to pre-populate Name ID and Namespace ID fields based on url from prev scaffolding step and as you can see in the image pre-population is working, only the validation failed because after pre-filling Namespace ID formContext.formData is overwritten and contains only "namespace": "cto", but doesn't contain anymore "name": "avast-backstage".

**Comment by benjdlambert** [comment]
Can you try https://github.com/backstage/backstage/pull/27273? I have a feeling that these are closely related.

**Comment by florinnania** [comment]
Not sure how to try #27273 as it seems to not be merged. What is the version which contain this change?

**Comment by florinnania** [comment]
@benjdlambert I've tested and I confirm that after your fix my flow is working is working fine again, please ship it out as a patch with the latest changes and thanks for fixing it.

**Comment by benjdlambert** [comment]
@florinnania thanks for the confirmation - there's a patch taking shape here: https://github.com/backstage/backstage/pull/27317
