### ISSUE TITLE
🚀 Feature: Support using Backstage User entity profile data for UserSettingsAvatar

### ISSUE THREAD

**Issue by secustor** [backstage/backstage#26838]
### 🔖 Feature description

The user settings plugin should show profile data, in my case the profile picture, if it is defined by the Backstage User entity but not by the identity provider

### 🎤 Context

Right now only the Identity Provider data is considered, but not the Catalog data. 

This leads in my case in which the Catalog has the picture data and the IdentityProvider not to inconsistent UX. 
On the settings page the picture is empty and on the User entity page the profile picture is correctly shown.  

### ✌️ Possible Implementation

https://github.com/backstage/backstage/blob/17ecea82239f25a4ee89f9c59fe43e735d1c80a2/plugins/user-settings/src/components/useUserProfileInfo.ts#L31-L36

Should also call the CatalogAPI to gather optionally infos about the Catalog entity based on the return value of `getBackstageEntity`. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by deejay1** [comment]
@secustor please take a look at the attached PR, is it what you were looking for?

**Comment by secustor** [comment]
Pretty much, though the sure is different. See my comments on the PR.

**Comment by deejay1** [comment]
Fixed

**Comment by freben** [comment]
You could achieve this by [changing your profile transform](https://backstage.io/docs/auth/identity-resolver/#profile-transforms) of your auth provider setup so that the correct image is present upfront.
