### ISSUE TITLE
🐛 Bug Report: catalog entity provider refresh failed, error: insert into "refresh_state" - value too long for type character varying(255)

### ISSUE THREAD

**Issue by nick-gray-bah** [backstage/backstage#26840]
### 📜 Description

The following error log appears everytime the GithubOrgEntityProvider task runs. 

`GithubOrgEntityProvider:dev refresh failed, error: insert into "refresh_state" ("entity_id", "entity_ref", "errors", "last_discovery_at", "location_key", "next_update_at", "unprocessed_entity", "unprocessed_hash") values.... , ($295, $296, $297, CURRENT_TIMESTAMP, $298, CURRENT_TIMESTAMP, $299, $300) - value too long for type character varying(255) insert into "refresh_state" ("entity_id", "entity_ref", "errors", "last_discovery_at", "location_key", "next_update_at", "unprocessed_entity", "unprocessed_hash") values ($1, $2, $3, CURRENT_TIMESTAMP, $4, CURRENT_TIMESTAMP, $5, $6)`

When I look at the refresh_state table, there is one column `next_stitch_ticket` which is type character varying(255) which I believe this error applies to. The only values for that column in our db are an empty value and the text 'initial'. Not sure if that is expected but seems odd. 

### 👍 Expected behavior

This error does not occur and the GithubOrgEntityProvider task can refresh successfully. 

### 👎 Actual Behavior with Screenshots

see error message above

### 👟 Reproduction steps

Run the GithubOrgEntityProvider task

### 📃 Provide the context for the Bug.

We're running new backend system with a GithubOrgEntityProvider that pulls from our github org in regular intervals. Everytime it runs we see the error above. 

### 🖥️ Your Environment

OS:   Darwin 23.6.0 - darwin/arm64
node: v18.20.4
yarn: 1.22.22
cli:  0.27.0 (installed)
backstage:  1.29.2

Dependencies:
  @backstage/app-defaults                                          1.5.9
  @backstage/backend-app-api                                       0.8.0
  @backstage/backend-common                                        0.23.3
  @backstage/backend-defaults                                      0.4.1, 0.5.0
  @backstage/backend-dev-utils                                     0.1.4, 0.1.5
  @backstage/backend-openapi-utils                                 0.1.15, 0.1.18
  @backstage/backend-plugin-api                                    0.6.18, 0.7.0, 0.8.1, 1.0.0
  @backstage/backend-tasks                                         0.5.27
  @backstage/backend-test-utils                                    0.4.4
  @backstage/catalog-client                                        1.6.5, 1.7.0
  @backstage/catalog-model                                         1.6.0, 1.5.0, 1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7, 0.2.8
  @backstage/cli                                                   0.26.11, 0.27.0
  @backstage/config-loader                                         1.8.1, 1.9.0, 1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.1
  @backstage/core-compat-api                                       0.2.7
  @backstage/core-components                                       0.13.10, 0.14.9
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.36
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.7
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.29
  @backstage/integration                                           1.13.0, 1.14.0, 1.15.0
  @backstage/plugin-api-docs                                       0.11.7
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.14
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.5
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.5
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.17
  @backstage/plugin-auth-backend-module-github-provider            0.1.19
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.19
  @backstage/plugin-auth-backend-module-google-provider            0.1.19
  @backstage/plugin-auth-backend-module-guest-provider             0.1.8
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.17
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.15
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.15
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.3
  @backstage/plugin-auth-backend                                   0.22.9
  @backstage/plugin-auth-node                                      0.2.19, 0.4.17, 0.5.2
  @backstage/plugin-auth-react                                     0.1.4
  @backstage/plugin-bitbucket-cloud-common                         0.2.21
  @backstage/plugin-catalog-backend-module-github-org              0.1.17
  @backstage/plugin-catalog-backend-module-github                  0.6.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.20
  @backstage/plugin-catalog-backend                                1.26.0
  @backstage/plugin-catalog-common                                 1.0.25, 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.7
  @backstage/plugin-catalog-import                                 0.12.1
  @backstage/plugin-catalog-node                                   1.12.4, 1.13.0
  @backstage/plugin-catalog-react                                  1.12.2
  @backstage/plugin-catalog                                        1.21.1
  @backstage/plugin-events-backend-module-aws-sqs                  0.4.1
  @backstage/plugin-events-backend-module-github                   0.2.10
  @backstage/plugin-events-backend                                 0.3.11
  @backstage/plugin-events-node                                    0.3.10, 0.3.8, 0.4.0
  @backstage/plugin-home-react                                     0.1.15
  @backstage/plugin-home                                           0.7.8
  @backstage/plugin-kubernetes-backend                             0.18.3
  @backstage/plugin-kubernetes-common                              0.8.1
  @backstage/plugin-kubernetes-node                                0.1.16
  @backstage/plugin-kubernetes-react                               0.4.1
  @backstage/plugin-kubernetes                                     0.11.12
  @backstage/plugin-org                                            0.6.27
  @backstage/plugin-permission-backend                             0.5.46
  @backstage/plugin-permission-common                              0.7.13, 0.8.0, 0.8.1
  @backstage/plugin-permission-node                                0.7.29, 0.8.0, 0.8.3
  @backstage/plugin-permission-react                               0.4.24
  @backstage/plugin-proxy-backend                                  0.5.3
  @backstage/plugin-scaffolder-backend-module-azure                0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.12
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.14
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.12
  @backstage/plugin-scaffolder-backend-module-github               0.4.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.4
  @backstage/plugin-scaffolder-backend                             1.23.0
  @backstage/plugin-scaffolder-common                              1.5.4
  @backstage/plugin-scaffolder-node                                0.4.8
  @backstage/plugin-scaffolder-react                               1.10.0
  @backstage/plugin-scaffolder                                     1.23.0
  @backstage/plugin-search-backend-module-catalog                  0.1.28, 0.2.2
  @backstage/plugin-search-backend-module-pg                       0.5.32
  @backstage/plugin-search-backend-module-techdocs                 0.1.27, 0.2.2
  @backstage/plugin-search-backend-node                            1.2.27, 1.3.2
  @backstage/plugin-search-backend                                 1.5.14
  @backstage/plugin-search-common                                  1.2.14, 1.2.13
  @backstage/plugin-search-react                                   1.7.13
  @backstage/plugin-search                                         1.4.14
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.13
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.12
  @backstage/plugin-techdocs-node                                  1.4.2
  @backstage/plugin-techdocs-react                                 1.2.6
  @backstage/plugin-techdocs                                       1.10.7
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.10
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.9
  @backstage/theme                                                 0.4.4, 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Hi! Sorry, for some reason I missed this issue.

I'll go ahead and guess that it's the entity_ref that causes it. The kind + namespace + name can really not exceed that hard limit. Do you have groups or users with very long names?

**Comment by amintong** [comment]
insert refresh_state happen before  `catalogModel.setFieldValidators`;  entity's ref length big than 255 will case provider fail.
