### ISSUE TITLE
🐛 Bug Report: Yarn Lock File Cash Value Changed Without Modifying package.json

### ISSUE THREAD

**Issue by rcramtharan** [backstage/backstage#26850]
### 📜 Description

The Yarn.lock file has been updated with a changed hash value, even though no modifications were made to the package.json file. This happens unexpectedly after yarn install.

### 👍 Expected behavior

The Yarn.lock file should remain unchanged unless the package.json file has been modified or a new dependency has been installed.

### 👎 Actual Behavior with Screenshots

After running yarn install the yarn.lock file is modified with a new hash , even though no changes were made to the dependencies in package.json

```
15075c15075<   resolution: "app@file:../app#../app::hash=81f0c3&locator=backend%40workspace%3Apackages%2Fbackend"--->   resolution: "app@file:../app#../app::hash=67d1f2&locator=backend%40workspace%3Apackages%2Fbackend"15116c15116<   checksum: 10c0/0334d78af9e93774bd912db6383d819afd60ef3d3800dd08e57e229e7e65def18df849840ee765411e01caaa701b4afd24d207ec4896fcb277cc39b522bacc01--->   checksum: 10c0/d9c8bf38b689f6296169a17a0684b12ea6566330da93beae60b9d4da4359213eaf88c53bff17ea9d3f8e576b819d1fe619407a671f7ea35b46f247104ae1bf51 
```

### 👟 Reproduction steps

yarn install on project without modifying the package.json  
check the git status and notice that yarn.lock file has been updated unexpectedly. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hmm, can you try using `link:../app` instead of `file:.` that you might have in you `packages/backend/package.json`?

**Comment by rcramtharan** [comment]
issue resolved
