### ISSUE TITLE
🐛 Bug Report: ReviewState Title Customization

### ISSUE THREAD

**Issue by elaine-mattos** [backstage/backstage#26882]
### 📜 Description

Our customer realized the ReviewState Title formatting is capitalizing strings where it should not.  Also, slashes are substituted by greater than.

For example, in this template:
```yaml
 properties:
    checkbox_apiaas_resource:
         title: I already have a APIaaS Tool / Resource
         type: boolean
         default: false
```
the property's `checkbox_apiaas_resource` title gets shown as :

"I Already Have A **AP Iaa S** Tool **>** Resource"  instead of:

"I already have a APIaaS Tool / Resource"

I am not, by any means, a React developer but I have looked in the `ReviewState` component code and found out that the `titleFormat`property in the `options` object end up being [hardcoded](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-react/src/next/components/ReviewState/ReviewState.tsx#L105), with the formatter being the [`lodash.startCase`](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-react/src/next/components/ReviewState/util.ts#L31).
Since the [`StructuredMetadataTable`](https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/StructuredMetadataTable/StructuredMetadataTable.tsx#L162) component  accepts the title formatting as an option, wouldn't it be nice to let the template creator (maybe via a `ui:backstage` option) (or even better, the plattform team in the `app-config.yaml`) decide how the titles in the Review State are going to be formatted?

Please let me know if this could be done in another way!
Also, I am more than glad to colaborate in a PR, would need a little guidance when it comes to the `Stepper`component (I saw it gets called by way too many other components and I am unsure if a change to the `ReviewState` and the `Stepper` could break other components. I am also unsure about where exactly the option should be placed (as stated above, in the template itself or the config...)

### 👍 Expected behavior

The ReviewState should be able to format different types of abbreviations. 

### 👎 Actual Behavior with Screenshots

<img width="712" alt="image" src="https://github.com/user-attachments/assets/fb804a7b-1e67-4ecb-879f-c7ba0ec36272">

### 👟 Reproduction steps

Create a template with an abbreviation that would be incorrectly parsed by `lodash.startCase`, like this one:

```yaml
 properties:
    checkbox_apiaas_resource:
         title: I already have a APIaaS Tool / Resource
         type: boolean
         default: false
```

### 🖥️ Your Environment

backstage:  1.31.1

Dependencies:
  @backstage/app-defaults                                          1.5.11
  @backstage/backend-app-api                                       1.0.0
  @backstage/backend-common                                        0.23.3, 0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.5.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.18
  @backstage/backend-plugin-api                                    0.7.0, 0.8.1, 1.0.0
  @backstage/backend-tasks                                         0.6.1
  @backstage/backend-test-utils                                    1.0.0
  @backstage/catalog-client                                        1.7.0
  @backstage/catalog-model                                         1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.8
  @backstage/cli                                                   0.27.1
  @backstage/config-loader                                         1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.15.0
  @backstage/core-compat-api                                       0.3.0
  @backstage/core-components                                       0.14.10, 0.15.0
  @backstage/core-plugin-api                                       1.9.4
  @backstage/dev-utils                                             1.1.0
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.9
  @backstage/frontend-plugin-api                                   0.8.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.31
  @backstage/integration                                           1.15.0
  @backstage/plugin-api-docs                                       0.11.9
  @backstage/plugin-app-backend                                    0.3.74
  @backstage/plugin-app-node                                       0.1.25
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.0
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.0
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.2.0
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.0
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.0
  @backstage/plugin-auth-backend-module-github-provider            0.2.0
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.0
  @backstage/plugin-auth-backend-module-google-provider            0.2.0
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.0
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.0
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.0
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.0
  @backstage/plugin-auth-backend-module-okta-provider              0.1.0
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.0
  @backstage/plugin-auth-backend                                   0.23.0
  @backstage/plugin-auth-node                                      0.4.17, 0.5.2
  @backstage/plugin-auth-react                                     0.1.6
  @backstage/plugin-bitbucket-cloud-common                         0.2.23
  @backstage/plugin-catalog-backend-module-gitlab                  0.4.2
  @backstage/plugin-catalog-backend-module-openapi                 0.2.0
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.0
  @backstage/plugin-catalog-backend-module-unprocessed             0.5.0
  @backstage/plugin-catalog-backend                                1.26.0
  @backstage/plugin-catalog-common                                 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.9
  @backstage/plugin-catalog-import                                 0.12.3
  @backstage/plugin-catalog-node                                   1.13.0
  @backstage/plugin-catalog-react                                  1.13.0
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.4
  @backstage/plugin-catalog                                        1.23.0
  @backstage/plugin-events-backend-module-gitlab                   0.2.11
  @backstage/plugin-events-backend-test-utils                      0.1.35
  @backstage/plugin-events-backend                                 0.3.12
  @backstage/plugin-events-node                                    0.4.0
  @backstage/plugin-home-react                                     0.1.17
  @backstage/plugin-home                                           0.7.10
  @backstage/plugin-kubernetes-backend                             0.18.6
  @backstage/plugin-kubernetes-common                              0.8.3
  @backstage/plugin-kubernetes-node                                0.1.19
  @backstage/plugin-kubernetes-react                               0.4.3
  @backstage/plugin-kubernetes                                     0.11.14
  @backstage/plugin-org                                            0.6.29
  @backstage/plugin-permission-backend                             0.5.49
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.3
  @backstage/plugin-permission-react                               0.4.26
  @backstage/plugin-proxy-backend                                  0.5.6
  @backstage/plugin-scaffolder-backend-module-azure                0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.0
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.0
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.0
  @backstage/plugin-scaffolder-backend-module-github               0.5.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.5.0
  @backstage/plugin-scaffolder-backend                             1.25.0
  @backstage/plugin-scaffolder-common                              1.5.6
  @backstage/plugin-scaffolder-node-test-utils                     0.1.12
  @backstage/plugin-scaffolder-node                                0.4.11
  @backstage/plugin-scaffolder-react                               1.12.0
  @backstage/plugin-scaffolder                                     1.25.0
  @backstage/plugin-search-backend-module-catalog                  0.2.2
  @backstage/plugin-search-backend-module-explore                  0.2.2
  @backstage/plugin-search-backend-module-pg                       0.5.35
  @backstage/plugin-search-backend-module-techdocs                 0.2.2
  @backstage/plugin-search-backend-node                            1.3.2
  @backstage/plugin-search-backend                                 1.5.17
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.8.0
  @backstage/plugin-search                                         1.4.16
  @backstage/plugin-signals-react                                  0.0.5
  @backstage/plugin-techdocs-backend                               1.10.13
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.14
  @backstage/plugin-techdocs-node                                  1.12.11
  @backstage/plugin-techdocs-react                                 1.2.8
  @backstage/plugin-techdocs                                       1.10.9
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.12
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.6.0
  @backstage/theme                                                 0.5.7
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.9

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by stephenglass** [comment]
Hmm it's a little tricky because the title formatting option is provided to the entire review table component. 

One solution could be adding a condition to the `formatKey` function in `ReviewState/util.ts` where it skips formatting. 

For example, if key follows pattern `$raw:<custom title>` then don't format.

**Comment by benjdlambert** [comment]
I'm thinking that if this is the behaviour of `startCase` and it's unable to be configured to work how we want, then `startCase` isn't the right solution here. It seems to be doing things that we wouldn't expect, and I'm not really sure where you would want the current behaviour at all?

I wonder if there's some alternatives that we can look into instead?

**Comment by elaine-mattos** [comment]
Hi,

we have created a yarn patch that leaves the strings as the template owner wrote them with the exception of the first character in the string, that now gets capitalized. 
It works for us but I am not sure this encompasses every (or most of the) use case(s)...

``` typescript
// import { startCase } from 'lodash';
import { upperFirst } from 'lodash';
...
function formatKey(key) {
  // const parts = key.split("/");
  // return parts.filter(Boolean).map((part) => upperFirst(part)).join(" > ");
  return upperFirst(key);
}
```

**Comment by benjdlambert** [comment]
@elaine-mattos do you want to whip up a PR contributing some of this pack to the main repo? It feels like anything that's better than the current implementation is an improvement as the current behaviour is broken :)

**Comment by stephenglass** [comment]
The `startCase` is really there to format the property key. There are other parts of scaffolder UI which do the same. The review page currently allows you to customize the title in 3 ways (each one takes precedent over the other).
1. `ui:backstage.name`
2. `title`
3. none of the above specified so it will use the key

However IMO it only really makes sense to use `startCase` formatting on the property key, NOT the `ui:backstage.name` or `title` value. The other behavior that should be maintained is the formatting of nested properties e.g. `Parent > Child > Property Name`.

**Comment by benjdlambert** [comment]
Yep, agree with that. Let's only use `startCase` if the `key` is used as the last resort, otherwise just use the `ui:backstage.name` or `title` as is.

Side note that we might look at other alternatives for `ui:backstage.*` eventually, but for now it's staying around.
