### ISSUE TITLE
🐛 Bug Report: ldapOrg will not map user-group relationships due to case-sensitivity of entryDN vs memberOf groups.

### ISSUE THREAD

**Issue by veenarm** [backstage/backstage#26887]
### 📜 Description

ldapOrg is not mapping our groups to users correctly due to case sensitivity.

When it attempts to get the groups from the groupMap it never finds the entryDN key due to that being brought in with multi case strings (e.g. cn is uppercase and an ou is uppercase, but the rest is lowercase) however the 'memberOf' is always returning as lowercase.

Thus when it attempts to find the key from the maps, it's always false.

Please don't ask why our organisation is storing data this way !

I believe a solution would be add a config of say `vendor.casesensitive = true` by default and if we set it to false add a inbound function to store all the data in either upper or lowercase when we do the ldap calls. (preferably uppercase IMO, but I'll leave that as a design choice).

### 👍 Expected behavior

ignore case sensitivity when mapping user group and users.

### 👎 Actual Behavior with Screenshots

It doesn't map users and groups, noting that we use `entryDN` and a specific uuid for Tivoli AD.

### 👟 Reproduction steps

Have your membersOf return all lowercase in AD and your DN (entryDN) for users return multicase or uppercase.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Sure - sounds like a feature request! It would preferably be built in such a way that it preserves the original case on its output, but is case insensitive only internally. Maybe it could even be built in such a way that it tries to make matches case sensitively first, and only look for a case insensitive match if that fails (and the config flag is set).

Would you like to contribute this? 🙏

**Comment by veenarm** [comment]
Happy to look into it as it stops me moving from gitlab org to ldap ingestion just yet, problem is the usage of maps etc there's no default way to get insensitivity out of the maps. Simpler would be to just force everything that comes out of AD to a specific case  if the flag is set, but I will try to see if there's another way (maybe duplicate the field/keys into another map with it all lowered etc..) that'd work... I'll spend some time tonight/tomorrow on it and see which way seems to hold true easier :)

**Comment by veenarm** [comment]
Cleanest way I can see is to add a vendor config setting to conditionally map the DN and memberOf attributes to all be lowercase based on that condition. It would also require the ANNOTATION for entryDN to also force lowercase ousing the same condition. This is due to half of the jobs using the annotation, and the other half using the 'entry' search criteria.

I've hard tested this at work locally and minor updates would resolve the issue, wi'll look to make a PR now.

**Comment by veenarm** [comment]
This has been resovled enough to solve our issue, however it does come with the caveat that the Entities will show the DN's all lowercase, and not match the actual LDAP servers.

I'll keep this here for now whilst I try to find a cleaner solution that allows both, I was reserved earlier due to the amount of extra data required to be passed around to maintain 2 states of the DN loops. If I find a nicer way, will update.

**Comment by veenarm** [comment]
New solution has been provided in https://github.com/backstage/backstage/pull/27791 @freben

**Comment by veenarm** [comment]
https://github.com/backstage/backstage/pull/27791

**Comment by veenarm** [comment]
PR Merged - closed in 1.34.0
