### ISSUE TITLE
🐛 Bug Report: General docs conflicts on frontend plugin proper usage

### ISSUE THREAD

**Issue by joshjung** [backstage/backstage#26928]
### 📜 Description

By default, I have had some success creating new plugins using `yarn new --select plugin`.

However, I am trying to develop a plugin that does not have a root page, and am running into considerable confusion from the code and documentation on how anything is supposed to work.

The following will be a brain dump of questions that I would love to know the answers to and then I am more than willing to help organize the documentation to make the answers to these questions clearer, especially to new frontend plugin developers.

### 1. How can I listen for plugin bootstrapping?

Plugin systems for most platforms I have ever worked on in the past provide:

- A way to register the plugin with a root object (usually both implicitly and explicitly)
- A way to find other plugins via some sort of other id with that root object (e.g. Plugin A can find if Plugin B is registered and then optionally talk to Plugin B)
- Every plugin has a root reference to the root application object
- At least one function that is called on that plugin object for various frontend events ('bootstrapHandler', 'routeChangeHandler', etc.)

In my case, I was looking all over for a way to listen for when a frontend plugin has been bootstrapped and could not find it.

I might be mistaken, but it appears that this registration is now no longer required, somehow? Is the assumption that importing the plugin will magically cause it to register itself when the `createFrontendPlugin()` function is called?

It is unclear from the documentation:

- How a plugin in the new frontend system is registered with the application
- How plugins are supposed to talk to eachother
- What is the lifecycle of a frontend plugin (or if there is a lifecycle)
- How plugins are supposed to register to listen to events in the lifecyle of the frontend backstage application (e.g. I want my plugin to save something to LocalStorage when a user clicks a link)

### 2. What is the `plugins` portion of `createApp` used for?

This one is very curious to me:

```
/**
   * A list of all plugins to include in the app.
   */
  plugins?: Array<
    BackstagePlugin & {
      output?(): Array<
        { type: 'feature-flag'; name: string } | { type: string }
      >; // support for old plugins
    }
  >;
 ```

It is not marked as deprecated, but I cannot find any good examples of its usage anywhere in the documentation. This is extra confusing because the comment says "all plugins" and yet, I have dozens of plugins installed and none of them are included in this array!

I can see [How to create a plugin](https://backstage.io/docs/frontend-system/building-plugins/index#the-plugin-instance) but this does not contain anything about this usage of `plugins` passed into `createApp`.

However, am I supposed to believe by the documentation that the plugin just... magically gets registered when I call `createFrontendPlugin`? What does it get registered to? Does it get registered at all when I call `createFrontendPlugin`?

The example says:

```
export const examplePlugin = createFrontendPlugin({
  id: 'example',
  extensions: [],
}); // Why is the generated instance completely ignored almost every time?
```

But then... nothing happens with the `examplePlugin` object. My natural expectation is that `createFrontendPlugin` would instantiate an instance of Plugin that has member methods to interact with the plugin. I would then expect that I would take that instantiated object and `register` it with the backstage application. **This is how the backend plugin system works, right?** I would also then expect that different plugins on the frontend would talk to each other *through* that instantiated Plugin object.

However, in almost every single example I can find... that exported `examplePlugin` reference is completely ignored and thrown away, but I cannot figure out why.

So this brings me to the `plugins` object in `createApp` again. What is this for and how would I use it? Is there documentation somewhere on how to use this?

### 3. Documentation is unclear on the relationship between api references and plugins

Note: this is primarily discovered when I could not find a clean way for one plugin to listen for the instantiation of another plugin, and then talk to it. I realized that maybe the intention was that plugins would talk to each other through their apis.

When reading the documentation on frontend plugins, there are examples where we are told that the apis for that plugin should be created as extensions of that plugin. So far so good. The impression I get is that the plugin *owns* that api and would manage its lifecyle - if it has one. However, this appears not to be the case.

However, then when you take a look at `createApp`, you can explicitly provide api references... without any reference to an owning plugin at all:

```
const app : BackstageApp = createApp({
  apis // Why do we have this here, but then we need to use ApiBlueprint to provide an api to createFrontendPlugin()?
});
```

What is the purpose of having apis be registered as extensions of a plugin when you can just put them right here in createApp?  Is it like a shortcut?

Does this mean that you could in theory take the api from a plugin and instantiate it in `createApp` without ever calling `createFrontendPlugin` for that imported plugin?

Apologies for the deluge of questions, I have been swimming through docs and code examples from Roadie plugins and the generated plugins for the last day and a half and am trying to give a braindump just so others can see the natural thought processes while trying to use things :D

I have every intention of helping to improve the docs on this once I get my head wrapped around how this is all supposed to work!

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

UPDATE:

Okay, another update on the confusion. The Backstage documentation says:

```
If you add support for the new system to your plugin, please do so under a `/alpha` sub-path export.
```

However! The entire Roadie codebase for their plugins uses an `alpha` folder which does not use the new frontend system. This is confusing because I was expecting the `alpha` directory to contain references to usage of the new plugin system, but apparently not.

**Comment by joshjung** [comment]
I think I may have discovered the answer to question (2).

[It is found here](https://backstage.io/docs/frontend-system/building-apps/migrating#plugins)

These docs definitely needs to be reworked for a couple reasons:

- I am not migrating from the old to the new, so I would not expect to have to read one of the migration pages to learn a core feature
- I am trying to work on a new plugin, so I was not ever thinking about looking at the "App" section of the new frontend system (since my app is already running)
- There is no way anyone is going to intuitively think to use the `features` field of the `createApp` in order to install a plugin when there is a non-deprecated `plugins` object right there.

**Comment by joshjung** [comment]
Update: one other thing I just noticed that has caused a lot of my confusion.

Where did `createApiExtension` go? The documentation references it. I saw it used in this plugin here:

https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/backstage-plugin-argo-cd/src/alpha/apis.tsx#L2

But apparently it no longer exists anywhere in the repository codebase?

I can find no reference anywhere in the version releases that `createApiExtension` was removed or instructions on what to use as an alternative.

**Comment by joshjung** [comment]
Sorry for yet another update, but figure I will keep documenting things.

I just discovered that:

- All old frontend plugin documentation uses the `createPlugin()` method
- `createPlugin()` and `BackstagePlugin` are both marked as deprecated, and we are told to replace with `createFrontendPlugin()` and `FrontendPlugin`
- All documentation for `createFrontendPlugin()` is in the `New Frontend System` section of the documentation
- The `New Frontend System` section is incomplete and we are all encouraged not to use it

The old docs say to use the new docs, and the new docs say not to use them because it is in alpha and incomplete.

So what are we supposed to use?

**Comment by benjdlambert** [comment]
Hey :wave: thanks for raising this and the previous again!

Ok, a lot to unpack here, I'm gonna try and answer some of the bits, but I think it would be useful to also bring in @Rugvip and @freben too to share their opinions! :pray:

> How plugins are supposed to talk to eachother

So I think that this might be a bit of the confusion here, plugins don't have the ability to talk to each other, extensions do, and for that you're gonna be using `inputs` and `outputs` of extensions to hop into the tree to provide some data to another extension or vice versa.

The `appTreeApi` might be of some use here understanding how things fit together a little more.

>  What is the plugins portion of createApp used for

This was the old system, this was a way to explicitly register plugins that did not appear in the JSX tree. In the new system there is no real JSX tree that's exposed to the end user to register plugins, so we can do that by autodetecting what you have installed, or by adding them explicitly to the `features:`  array in `createApp` in the new system.

> It is not marked as deprecated

It's not as yet, as we haven't started deprecation of the old system and anything that lives under `app-defaults`, but that entire package, along with `core-app-api` and `core-plugin-api` will be deprecated and removed.

> However, in almost every single example I can find... that exported examplePlugin reference is completely ignored and thrown away, but I cannot figure out why.

It might be worth calling out [the installation](https://backstage.io/docs/frontend-system/building-apps/index/#the-app-instance) parts here a bit more. This explains why `export { plugin as default } ...` is used. And as I mentioned above the `plugins` options has been replaced with either the `features` array or [feature discovery](https://backstage.io/docs/frontend-system/architecture/app#feature-discovery). I realised that those two links are not on the same page, so there's definitely some cleanup needed there for sure!

> However, then when you take a look at createApp, you can explicitly provide api references... without any reference to an owning plugin at all:

This is exactly the same issue as the `plugins` part, API's could be discovered from the JSX tree in the old system as they were bundled with the plugin, but for things that weren't explicitly registered in the tree and discovered that way, you could add them to this list to add to the app. This again has been completely replaced with `extensions` in the new frontend system, so there's no special kind, they're just extensions bundled in an plugin.

I think that there's lot of confusion between what's new frontend system and what's the old frontend system which is probably mudding the waters a little bit. Part of this is that there really wasn't that great documentation for the old system in the first place for a lot of these things - this we're hoping to make better in the new system with thanks to issues like this :pray:

> The old docs say to use the new docs, and the new docs say not to use them because it is in alpha and incomplete.

Let's get rid of that, we're encouraging people to try and use it, but not for new adopters, this would be for people that are building plugins that want to support both, and adopters that want to try out the new system.

Wondering if we should clean up `app-next` too, as it would be good to have a better reference implementation rather than the one that we've got today which is a bit cluttered with comments for implementation and code.

> Where did createApiExtension go? The documentation references it. I saw it used in this plugin here

All the old `create*Extension` helpers have been removed, and have been replaced with the Blueprint alternative instead. So you'd want to be looking at using `ApiBlueprint.make` instead. There's some more doc under the [migrations](https://backstage.io/docs/frontend-system/architecture/migrations#blueprints-instead-of-extension-creators) too.

**Comment by joshjung** [comment]
@benjdlambert Thank you for your detailed response! I hope you all realize I am being verbose in the process of frustration trying to understand what is going on primarily so that I can expose all the pain points in trying to step through the code and documentation. I have a hunch that most people are encountering similar issues, but are confused about how to speak up.

Obvious first goal for me is to help out in improving the documentation if I can, so I am not just trying to throw out giant lists of issues. I would *love* to submit PRs fixing documentation, but just need to first understand how things work!

This week I have spent between 24-30 hours trying to do what I would consider to be the most basic things with a plugin and am just running into so many issues!

> Hey 👋 thanks for raising this and the previous again!
> 
> Ok, a lot to unpack here, I'm gonna try and answer some of the bits, but I think it would be useful to also bring in @Rugvip and @freben too to share their opinions! 🙏
> 
> > How plugins are supposed to talk to eachother
> 
> So I think that this might be a bit of the confusion here, plugins don't have the ability to talk to each other, extensions do, and for that you're gonna be using `inputs` and `outputs` of extensions to hop into the tree to provide some data to another extension or vice versa.

Okay, this sounds great, but I cannot for the life of me get the new frontend system working - it is just one problem after another. So I'm stuck in the old system, so I need to get the old plugins talking to each other.

> 
> The `appTreeApi` might be of some use here understanding how things fit together a little more.
> 

How are we supposed to know about this? I don't remember seeing this anywhere in all the documentation I have read and a search for it in the docs reveals this:

![Screenshot 2024-10-04 at 12 11 08](https://github.com/user-attachments/assets/49ae8704-60a0-4b3e-83fe-7e58a59508da)

> > What is the plugins portion of createApp used for
> 
> This was the old system, this was a way to explicitly register plugins that did not appear in the JSX tree. In the new system there is no real JSX tree that's exposed to the end user to register plugins, so we can do that by autodetecting what you have installed, or by adding them explicitly to the `features:` array in `createApp` in the new system.

So I can pretty confidently say there is a bug here. I kinda deduced that might be what the field is for, but as soon as I put one plugin in this field, all the other plugins were reported as missing. So, the claim that this field is just for plugins that do not appear in the tree is not working for me right now.

> > It is not marked as deprecated
> 
> It's not as yet, as we haven't started deprecation of the old system and anything that lives under `app-defaults`, but that entire package, along with `core-app-api` and `core-plugin-api` will be deprecated and removed.

Okay, I think the docs need to make it super clear that:

- If you switch to the new frontend system, you must completely switch
- Extensive documentation on how to slow-migrate to the new frontend system, if possible

> 
> > However, in almost every single example I can find... that exported examplePlugin reference is completely ignored and thrown away, but I cannot figure out why.
> 
> It might be worth calling out [the installation](https://backstage.io/docs/frontend-system/building-apps/index/#the-app-instance) parts here a bit more. This explains why `export { plugin as default } ...` is used. And as I mentioned above the `plugins` options has been replaced with either the `features` array or [feature discovery](https://backstage.io/docs/frontend-system/architecture/app#feature-discovery). I realised that those two links are not on the same page, so there's definitely some cleanup needed there for sure!
> 

In the old plugin system the plugin object is thrown away as well, right? I was expecting to find somewhere, because it is called a "plugin", that it would, well, be "plugged in". This is how every plugin system I have seen works, so I was just basically going off of past experience with plugin systems.

> > However, then when you take a look at createApp, you can explicitly provide api references... without any reference to an owning plugin at all:
> 
> This is exactly the same issue as the `plugins` part, API's could be discovered from the JSX tree in the old system as they were bundled with the plugin, but for things that weren't explicitly registered in the tree and discovered that way, you could add them to this list to add to the app. This again has been completely replaced with `extensions` in the new frontend system, so there's no special kind, they're just extensions bundled in an plugin.

Well, I'm super thankful you are getting rid of the weird discovery through the JSX tree! That has been throwing me off for months!

> 
> > The old docs say to use the new docs, and the new docs say not to use them because it is in alpha and incomplete.
> 
> Let's get rid of that, we're encouraging people to try and use it, but not for new adopters, this would be for people that are building plugins that want to support both, and adopters that want to try out the new system.

Okay, I'll see if I can find time to get a PR addressing this.

> 
> Wondering if we should clean up `app-next` too, as it would be good to have a better reference implementation rather than the one that we've got today which is a bit cluttered with comments for implementation and code.

I'll confess I don't know what you are talking about here.

> 
> > Where did createApiExtension go? The documentation references it. I saw it used in this plugin here
> 
> All the old `create*Extension` helpers have been removed, and have been replaced with the Blueprint alternative instead. So you'd want to be looking at using `ApiBlueprint.make` instead. There's some more doc under the [migrations](https://backstage.io/docs/frontend-system/architecture/migrations#blueprints-instead-of-extension-creators) too.

Is there a place in the docs where this addressed? I tried multiple times to search back multiple versions in the version changes docs and found nothing explaining this decision.

> 
> --
> 
> I think that there's lot of confusion between what's new frontend system and what's the old frontend system which is probably mudding the waters a little bit. Part of this is that there really wasn't that great documentation for the old system in the first place for a lot of these things - this we're hoping to make better in the new system with thanks to issues like this 🙏

Yes! 100%. I think that for the sake of people trying to adopt the system today, serious improvements should be made ASAP on both parts of the documentation for old and new frontend systems to clarify a lot of these issues.

Unfortunately, because things are so complicated, I think that most people are going to be crippled in trying to help out in updating the documentation. For a short period of time, I think the most capable people on the planet of updating the documentation are going to be the engineers who made all the decisions. I can try, though... which is why I am erring on the side of overexplaining my pain points.
