### ISSUE TITLE
🚀 Async userTransformer function in GitlabOrgDiscoveryEntityProvider

### ISSUE THREAD

**Issue by Vol1and** [backstage/backstage#26931]
### 🔖 Feature description

You have @backstage/plugin-catalog-backend-module-gitlab. It implements **GitlabOrgDiscoveryEntityProvider**, which has **userTransformer** arument. I suggest you to modify the type of an argument to make it also **accept promises**, and make Provider handle it through **await** in the code.

### 🎤 Context

I want to add some custom fields to my User entity in my userTransformer, and i want fetch them though API. This feature will allow me to call async function in userTransform. Plus, you've already done it in the same package for github. [Here is the code](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/lib/defaultTransformers.ts#L41). 

### ✌️ Possible Implementation

It has type: (options: UserTransformerOptions) => UserEntity. 
I suggest you to make it's type: (options: UserTransformerOptions) => UserEntity | Promise\<UserEntity\>.
And add **await** at [this line at GitlabOrgDiscoveryEntityProvider.ts](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-gitlab/src/providers/GitlabOrgDiscoveryEntityProvider.ts#L481).

This won't affect other's implementations, and also add a possibility to pass async functions in Provider.

Thank you in advance

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
What are you wanting to do in the `async` handler? Just wanting to point out that this feels like a bit of a footgun that if you're wanting to make async requests to some other service, you might be at risk of DDOS'ing that service every processing loop.

We might want to look at adding some `limiter` for running these `userTransformers` if thats the case.

**Comment by Vol1and** [comment]
You are right, it's not an elegant choice, but I found it's the only option to add some async data to Gitlab user. If you have better solution, I would be really glad if you tell me. 

About the `limiter`, you already have `timeout` object in scheduler, which sets the maximum amount of time for single task to take. 

Thank you.

**Comment by Vol1and** [comment]
Sure, I will raise a PR. Thank you
