### ISSUE TITLE
🐛 Bug Report: scaffolder-node plugin's gitHelper fails to create a new branch

### ISSUE THREAD

**Issue by rjdecilos** [backstage/backstage#26962]
### 📜 Description

scaffolder-node plugin `createBranch` function is checking out to a non-existing branch instead of creating the branch. It looks like it's using the checkout function instead of the branch function.

### 👍 Expected behavior

It should create a new branch instead of trying to checkout to an existing branch.

### 👎 Actual Behavior with Screenshots

It actually tries to checkout to a branch, and assumes that the branch exists.

### 👟 Reproduction steps

1. Write a code that uses @backstage/plugin-scaffolder-node `createBranch` function.
2. Use a ref branch name that doesn't exist yet in the repository.
3. The function should throw an error that the branch doesn't exist.

### 📃 Provide the context for the Bug.

Please see my PR here: https://github.com/backstage/backstage/pull/26963

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
What's the error you're seeing when the checkout method is called without an existing branch name?

**Comment by rjdecilos** [comment]
Here's a sample output of the code below when I use the function on one of my custom scaffolder action:

```js
await createBranch({
  dir: 'clonedirhere',
  ref: 'testCreateBrn',
  auth: {
	username: 'user',
	password: token
  },
  logger: ctx.logger
})
```

![image](https://github.com/user-attachments/assets/5f8ec945-2b37-44c2-b5ff-7c8ee403427a)

This is also the same output when using the deprecated backend-common git:

```js
const git = Git.fromAuth({
  username: 'user',
  password: token,
  logger: ctx.logger,
});
await git.checkout({ dir: 'clonedirhere', ref: 'testCreateBrn' });
```
