### ISSUE TITLE
🐛 Bug Report: confusing error message about routable extension component

### ISSUE THREAD

**Issue by joshjung** [backstage/backstage#26976]
### 📜 Description

This error message is so cryptic I do not know what in the world it means:

![Screenshot 2024-10-04 at 11 28 34](https://github.com/user-attachments/assets/0f6e00fa-2d64-401c-a902-738bb88f7261)

### 👍 Expected behavior

An error message should provide some context as to what caused it and how to fix it or a reference to documentation on what is going on.

### 👎 Actual Behavior with Screenshots

- I don't know what a routable extension component is
- I don't know how I accidentally broke my app so that a plugin I did not write suddenly is not working
- "Routable extension components may not be rendered by other components" why? What does this mean?
- "must be directly available as an element within the App provider component" I have no idea what this means, because App.tsx is something generated by Backstage, and I have no idea what a "App provider component" is

A search of my entire for codebase for "provider" yields no results that closely resemble this error.

### 👟 Reproduction steps

I am not sure. I think I triggered it by starting to use:

```
const app : BackstageApp = createApp({
  ...
  plugins: [monitoringPlugin, argocdPlugin, jenkinsPlugin],
  ...
});
```

The issue I had was getting my plugin installed into the App. So I figured I would install it in the most obvious place imaginable, inside the `plugins` field of `createApp`. The code comment for `plugins` field says: "A list of all plugins to include in the app." So great, I put my plugin into this field.

Unfortunately, when I put my plugin in here, errors started popping up saying that the other plugins were not installed. This confused me greatly. Why would putting my plugin in the `plugins` field suddenly break the entire application? Nothing in the comment indicates this should happen.

It occurred to me that maybe the comment was misleading. Perhaps the `plugins` field is considered to be an extensive list of all plugins that could ever by referenced in the app. So I put the ArgoCd plugin and Jenkins plugin in there.

This worked! For one page load. Then I clicked a link to go to the Jenkins tab in the EntityPage and I get the error:

```
Routable extension component with mount point routeRef{type=absolute,id=jenkins} was not discovered in the app element tree. Routable extension components may not be rendered by other components and must be directly available as an element within the App provider component.
```

How in the world did it half work to put the plugin in the `plugins` field and then blow up in a place it never broke before with such an obtuse error. I don't know, but I am completely lost.

### 📃 Provide the context for the Bug.

Just trying to get a tiny plugin I am writing installed. I've spent about 16-20 hours so far trying to get the most basic features working.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by joshjung** [comment]
Small update, "routable extension component" is not found anywhere in the docs:

![Screenshot 2024-10-04 at 11 47 49](https://github.com/user-attachments/assets/c15c6503-8f02-4676-a4f2-53739a7dc8d9)

**Comment by Rugvip** [comment]
Yep element tree concept is confusing in general but can get really confusing at the scale we're doing it at. Most other libs like MUI and react-router do it with fairly small and/or shallow trees. We were looking for an "app as sitemap" solution with flexible routing and no custom compilation, and figured that JSX is a fairly well-known declarative format and went for that rather than more of a plain TS API. It works well for the simple use-cases but quickly gets very tricky when you want to customize or provide extensibility. Clearly defined extensibility is a high prio in the new frontend system, which is the way forward.

**Comment by joshjung** [comment]
Sorry been on vacation!

Overall, I think that it would make a lot of sense to just explain how things work, and make the comments more verbose in the more complicated sections of the code (e.g. `AppManager`). At the very least, when someone does run into a weird error they can search the codebase and at least get some idea of what might be going on.

It feels in the documentation like there is a hesitancy to explain the more complicated parts of the Backstage frontend system in depth. Personally, I feel that everyone would love to at least have the ability to learn how it works, the thought process behind it, etc. When we encounter errors that contain complex phrasing like "routable extension component" we should at least be able to search the docs OR search the code and find a doc or a code comment about it.

I'm working on another PR related to frontend stuff, what I might consider doing is adding a page explaining how things work and addressing what a "routable extension component" is etc.

**Comment by Rugvip** [comment]
Yep I generally agree, but I don't think it's an area that is worthwhile investing time into at this point. It's very hard to build extension points in the old frontend system and I wouldn't want to encourage that any more at this point with the incoming move to the new frontend system and it having a much better solution towards that.

**Comment by joshjung** [comment]
Alright, I understand the sentiment. I think that maybe these examples could be a signal to everyone that for the new frontend system, a stronger emphasis on documentation and clear error messaging is needed!

**Comment by asoov** [comment]
@Rugvip Are there any resources on the element tree concept? I've been working on a Backstage project for 2,5 months now and have encountered this error multiple times and there is practically 0 resources on why it is happening. I mostly encounter this when using some kind of plugin that is defined as a routableExtension. I still don't know WHY this error is happening and what's the use of a routableExtension vs. a simple componentExtension. I would love to just have a component that I can integrate on a route. 

I didn't grasp this to this day and tbh it feels like a PITA and unnecessarily complex.  If there are any resources to give me some context about this it would be lovely if someone could share it with me.
