### ISSUE TITLE
🚀 Feature: Add @required annotation to TSDoc comments of new plugin config extensions

### ISSUE THREAD

**Issue by melloc01** [backstage/backstage#26974]
### 🔖 Feature description

By adding a `@required` annotation plugin developers wouldn't need to resort to jsonSchema when writing plugin types, additionally, there's no clear mention that all `.d.ts` extensions are required [on the docs](https://backstage.io/docs/conf/defining/).

### 🎤 Context

I'd like to use `.d.ts` to extend the app config but can't because it's my extension has optional fields

### ✌️ Possible Implementation

I'm not very familiar with the codebase but it would follow the same implementation of the `visibility` paramters.

Defaulting the `required` value to `true` (and adding to the docs) would be a way to have backwards compatibility or make a breaking change and follow the jsonSchema standard which I believe is false?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
You should be able to use typescript `?` to specify if fields are optional or not in the `config.d.ts`

```ts
myRequiredProperty: string;
myOptionalProperty?: string;
```

Does this solve your use case?

**Comment by melloc01** [comment]
> You should be able to use typescript `?` to specify if fields are optional or not in the `config.d.ts`
> 
> ```ts
> myRequiredProperty: string;
> myOptionalProperty?: string;
> ```
> 
> Does this solve your use case?

Oh god, of course! 😓 
It works. Thank you!
