### ISSUE TITLE
💬 RFC: Allow Custom Elements/Web Components in TechDocs

### ISSUE THREAD

**Issue by h7kanna** [backstage/backstage#26988]
### 🔖 Need

Integrate [custom components](https://developer.mozilla.org/en-US/docs/Web/API/Web_components) in Markdown independent of current limitation of the hard dependency on Mkdocs and lack of support or plan to allow alternative SSG frameworks/MDX.

Example: https://github.com/github/tab-container-element

### 🎉 Proposal

Allow [Custom Element configuration](https://github.com/cure53/DOMPurify?tab=readme-ov-file#control-behavior-relating-to-custom-elements) provided by DOMPurify to the configuration.

As previously discussed in many related issues and [comments](https://github.com/backstage/backstage/issues/13856#issuecomment-1284222765) security being the main reason to disallow [extra_javascript in Mkdocs](https://www.mkdocs.org/user-guide/configuration/#extra_javascript).

This proposal will still maintain the security requirement of disallowing arbitrary JavaScript in the html.

How it works

1) User will add markdown extensions that will generate the html with custom elements or embed them in source markdown(configure the extension)
2) User will add the required javascript to the backstage public html (so controls which elements are registered)
3) Configure the allowlist in the app-config.yaml

Example:

## Configuration:

```yaml
  sanitizer:
    allowedCustomElementTagNameRegExp: '^backstage-'
    allowedCustomElementAttributeNameRegExp: 'attribute1|attribute2'
```

## Integration:

In app/public/index.html
```html
<script type="module" src="/custom-elements-js/index.js" defer></script>
```

## Source

```markdown
# Test Custom elements

This must be allowed in the markdown processor/extensions

<backstage-custom-element attribute1="test" attribute2></backstage-custom-element>

```

### 〽️ Alternatives

There is no alternative other than to allow the DOMPurify configuration

### ❌ Risks

* Custom elements can impact the look and feel of the Backstage TechDocs viewer as they can provide their own [styling](https://developer.mozilla.org/en-US/docs/Web/API/Web_components#shadow_dom). 
This can be mitigated by following the usual guidelines of using Backstage design guidelines for them.
* This will only work in browsers with the support for Custom elements
* Care must be taken when writing the sanitizer config (allow regex patterns)

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by h7kanna** [comment]
Changes needed if accepted are in PR
https://github.com/backstage/backstage/pull/26989

**Comment by squid-ney** [comment]
Hi @h7kanna , this PR looks good- it is well documented and tested.

I'd just like to ask a few questions regarding the approach. I was reading the discussion from one of the [references](https://github.com/backstage/backstage/issues/13856#issuecomment-1284222765) you linked:
> In a nutshell, TechDocs exposes an official interface, which is TechDocs Addons, that allows you to customize your sites to your liking, you can even go as far and ship your custom CSS and custom JavaScript with it. You could also restrict it to certain pages only by inspecting the currently displayed entity docs. 

Internally, we do not use any markdown extensions that require allowing custom elements. So, I have not personally tried this out with TechDocs. I am curious if you considered using the Addons framework for your custom elements? If, so could you share if there are any blockers/problems with that approach and the estimated effort to resolve that in comparison to the allowlisting of custom elements approach in PR
https://github.com/backstage/backstage/pull/26989 ?

**Comment by h7kanna** [comment]
Hi, Yes I tried to use the Addon approach. 
But the Techdocs Addons only support acting upon the DOM in the effects. But by the time Addon logic runs, the HTML is sanitized and the custom elements are removed.

**Comment by squid-ney** [comment]
Thanks! Okay I think your approach works well and I like the `allowedCustomElementTagNameRegExp` configuration in which orgs have to explicitly allow custom elements. This seems more secure than changing sanitization rules for addons.

**Comment by squid-ney** [comment]
Merged! Thanks for your contribution 🚀

**Comment by h7kanna** [comment]
This RFC has been accepted and implemented in https://github.com/backstage/backstage/pull/26989
