### ISSUE TITLE
🐛 Bug Report: Backstage.io Reference Search Results Misleading

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#26985]
### 📜 Description

When using the search on Backstage.io I've noticed that it will send me to me to misleading results which then could lead one down a pretty confusing rabbit hole.

### 👍 Expected behavior

Ideally it should prioritize current over alpha or have some way to make that more clear.

### 👎 Actual Behavior with Screenshots

If I search for `createApp` the top result is this: https://backstage.io/docs/reference/frontend-app-api.createapp/. Which is from the `@backstage/frontend-app-api` package which is only for things for the new frontend system. The issue with that is `createApp` is part of the current frontend system and is documented here: https://backstage.io/docs/reference/app-defaults.createapp. The only way to get to the proper documentation is to - know about it and also use the "See all results" feature: 

![image](https://github.com/user-attachments/assets/33dbfed3-db3d-4465-981a-1a8b7daa2015)

### 👟 Reproduction steps

Search for `createApp` the top result is this: https://backstage.io/docs/reference/frontend-app-api.createapp/. Which is from the `@backstage/frontend-app-api` package which is only for things for the new frontend system. 

### 📃 Provide the context for the Bug.

Being sent to incorrect documentation means people are spending time heading off in the wrong direction and getting frustrated at the results. 

### 🖥️ Your Environment

Not environment specific but just using: https://backstage.io/

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
I think that we had some weighting config for things like this before to rank the other results above the automatically generated reference documentation. Maybe that config needs updating - I think @jhaals might know more.

**Comment by Rugvip** [comment]
This was likely due to the new `/next` docs being picked up by the crawler. We've just reconfigured it so in about ~1h hopefully search results will be fine 😁
