### ISSUE TITLE
🐛 Catalog: EntityPresentationApi does not provide Icon for custom kinds.

### ISSUE THREAD

**Issue by yashoswalyo** [backstage/backstage#26983]
### Plugin Name

Catalog

### 📜 Description

Currently the EntityPresentationApi uses a static list of icons, instead it should be able to get custom Kind icons too which are defined by user
```tsx
createApp({
  icons:{
    'kind:mykind':  IconComponent
  }
})
```

### 👍 Expected behavior

The presentationApi snapshot should provide Icon for custom kind

### 👎 Actual Behavior with Screenshots

The graph is rendered node without the Icon is creates confusion

![image](https://github.com/user-attachments/assets/3179b5d4-435d-4c5a-89db-79694fcd00d1)

### 👟 Reproduction steps

1. Create custom kind using entity processor and emit relation to some entity
2. Assign icon using `createApp()`
3. See the catalog-graph card, the icon is not rendered there

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/community-plugins/blob/main/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by jacri901** [comment]
Hi, I can take a closer look at this one

**Comment by benjdlambert** [comment]
@jacri901 please go ahead :tada:

**Comment by yashoswalyo** [comment]
Hey team, I was able to achieve this using by modifying `packages/app/src/api.ts` and add this to the apis array.
```tsx
createApiFactory({
    api: entityPresentationApiRef,
    deps: {
      catalgoApi: catalogApiRef,
    },
    factory({ catalgoApi }) {
      return DefaultEntityPresentationApi.create({
        catalogApi: catalgoApi,
        kindIcons: {
          mykind: Icon1,
          mykind-2: Icon2
        },
      });
    },
  }),
```
