### ISSUE TITLE
🐛 Bug Report: Owner name is overflowing in AboutContent Component of Catalog Plugin 

### ISSUE THREAD

**Issue by its-mitesh-kumar** [backstage/backstage#26990]
### 📜 Description

In the AboutContent component of the Catalog plugin, longer owner names is causing layout issues due to text overflow. To maintain a consistent and user-friendly design, we need to truncate owner names that exceed a specific length and display the full name upon hover. 

### 👍 Expected behavior

Instead of displaying the full owner name, names longer than a specified length should be truncated and the full name shown on hover.

### 👎 Actual Behavior with Screenshots

We can see owner name text is overflowing .
<img width="1710" alt="Screenshot 2024-10-04 at 3 04 07 PM" src="https://github.com/user-attachments/assets/c62a05df-4286-4f42-82ac-b4fded532158">

### 👟 Reproduction steps

Create Catalog Plugin having longer owner name 

### 🖥️ Your Environment

Not environment specific .

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
Ah yep, this looks like it should have some additional properties.

Perhaps `text-overflow: ellipsis` and `overflow: hidden`. Do you want to raise a PR with a suggested fix? :pray:

**Comment by its-mitesh-kumar** [comment]
Yes I am working on it , I raise a PR soon .

**Comment by its-mitesh-kumar** [comment]
PR : https://github.com/backstage/backstage/pull/27044
