### ISSUE TITLE
🚀 Feature: Allow to customize element display of EntityAutocompletePicker

### ISSUE THREAD

**Issue by secustor** [backstage/backstage#26995]
### 🔖 Feature description

Allow to provide alternative way to render auto complete contents.  

### 🎤 Context

Currently [`EntityAutocompletePicker`](https://github.com/backstage/backstage/tree/master/plugins/catalog-react/src/components/EntityAutocompletePicker) is simply using a Textfield. 

In my use case I have a number of Pickers I want to add which have as content entity references. 
Right now they will be simply rendered with their ID, which is not helpful in our case as they are only machine readable. 
Therefore I would rather like to use `<EntityDisplayName />`

### ✌️ Possible Implementation
That way we should be able to unify implementation to some degree with `EntityOwnerPicker`. 
I see two options: 
- directly expose the render function with the current one as default
- Create an outlet

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Actually that sounds pretty sensible for general use. I wouldn't be against maybe making it the default but at least adding a prop to switch to using `EntityDisplayName`. We haven't settle the pattern for providing component overrides just yet so would like to keep that somewhat limited for now.
