### ISSUE TITLE
🚀 Feature: ElasticSearch loading of SSL self sign Certs into app-config.yaml

### ISSUE THREAD

**Issue by joaquin386** [backstage/backstage#26994]
### 🔖 Feature description

Allow ElasticSearch loading of SSL self sign Certs into app-config.yaml via an option like `key` and `cert`

### 🎤 Context

The communication to the ES nodes is done via https:9200 connection.
Discord Support Question [here](https://discord.com/channels/687207715902193673/1006844959170764851/threads/1292765682366156810)

### ✌️ Possible Implementation

allow tls loading of the self sign certs via the app-config.yaml file

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
I think that you might need to add these when running Node.

From memory you can use the `NODE_EXTRA_CA_CERTS` environment variable to reference a path with additional trust chains.

https://nodejs.org/api/cli.html#node_extra_ca_certsfile

**Comment by joaquin386** [comment]
@benjdlambert Thanks will try that one. If it works will close the Feature.

**Comment by joaquin386** [comment]
@benjdlambert Still same error:
`"level":"error","message":"unable to verify the first certificate"`
Even that I set:
` NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/tls.crt`
And the tls.crt is there

**Comment by joaquin386** [comment]
@benjdlambert After setting `NODE_EXTRA_CA_CERTS=ca.crt` the https connection with the self sign certs is working correctly.
Reference here: [stackoverflow](https://stackoverflow.com/questions/73248201/unable-to-verify-the-first-certificate-when-connecting-to-elasticsearch-from-n)
