### ISSUE TITLE
Infrastructure as code static analysis plugin (checkov)

### ISSUE THREAD

**Issue by schosterbarak** [backstage/backstage#2706]
## Summary

A plugin that can scan IaC manifests such as k8.yaml, serverless, terraform, cloudformation and azure arm templates before provisioning using checkov. would you see it as a good fit?

## Project website (if applicable)
 https://github.com/bridgecrewio/checkov/

**Comment by stefanalund** [comment]
Hey! I think this sounds like an interesting plugin indeed. Are you thinking the results of the scan would be visualised in Backstage? I think you could also consider presenting the user with the option to enable checkov scanning if this is not already enabled for the component.

I'm not sure if the plugin itself would be involved in triggering the scan though -- guessing that is done during CI?

**Comment by schosterbarak** [comment]
I'm not sure about the exact implementation yet and would love to do a zoom on it.
The mission i would like to answer is making sure a service in the service catalog is vetted by checkov. is it a good match?

**Comment by stefanalund** [comment]
It sounds like it to me, even though I'm not an expert in checkov :)

**Comment by schosterbarak** [comment]
can a plugin scan other plugins or services?

**Comment by stefanalund** [comment]
Not really. A plugin is primarily a UI element, see https://backstage.io/docs/plugins/
