### ISSUE TITLE
Backstage search plugin to support partial search update

### ISSUE THREAD

**Issue by Lukmin1999** [backstage/backstage#27065]
_Originally posted by @Lukmin1999 in https://github.com/backstage/backstage/issues/6177#issuecomment-2403388396_
                          Hi, I've recently been working on Backstage, and I think this issue should be brought back. Postgres seems to have similar problems with searching, particularly with titles with special characters like hyphens and periods (try for instance foo-bar.com, for example)

**Comment by jhaals** [comment]
closing this as a duplicate and reopening the old issue

**Comment by Lukmin1999** [comment]
@jhaals 
> closing this as a duplicate and reopening the old issue

When will the old issue be reopened?
