### ISSUE TITLE
Not able to run plugins individually (techdocs, lighthouse, etc.)

### ISSUE THREAD

**Issue by exp-dev-dj** [backstage/backstage#2707]
Previously, a user can cd to **plugins/techdocs** directory and run **yarn start** to start Techdocs plugin individually for development and testing. But when you try to do the same now, you will get "ERROR 404: PAGE NOT FOUND.  Looks like someone dropped the mic!"  

## Expected Behavior

A user can cd to **plugins/techdocs** directory and run **yarn start** to start Techdocs plugin individually for development and testing

## Current Behavior

When you try to do the same now, you will get "ERROR 404: PAGE NOT FOUND.  Looks like someone dropped the mic!"  

## Steps to Reproduce

1. Checkout the latest open source [Backstage code](https://github.com/spotify/backstage) to your local
2. Follow the [steps](https://backstage.io/docs/getting-started/running-backstage-locally) to install all dependencies
3. cd to **plugins/techdocs** and run **yarn start**
4. Open browser and nativate to http://localhost:3000/docs and you will see the Error page

## Context

This issue is preventing developers to run Techdocs plugins individually for development or testing.

**Comment by hooloovooo** [comment]
Seems like this applies to any plugin being run as standalone.

**Comment by hooloovooo** [comment]
@spotify/backstage-core Is this something you know anything about?

**Comment by OrkoHunter** [comment]
Updated the title to reflect that this an issue with all the plugins.

**Comment by marcuseide** [comment]
@exp-dev-dj Unfortunately running plugins in isolation was not covered in a recent refactor we did (#2076). We aim to reintroduce this behaviour, but we cannot give a specific time for that right now.

**Comment by hooloovooo** [comment]
Any news on this?

**Comment by benjdlambert** [comment]
We discussed this today - kind of waiting for the Plugin API and routing to be stabllised which we are currently working on fixing up. So hopefully we can start on this soon!

**Comment by Rugvip** [comment]
Gonna close as this has been solved for a while through updates to the plugin an `@backstage/dev-utils` API. Here's a pretty complete example for how to wire up a development harness for a plugin: https://github.com/backstage/backstage/blob/master/plugins/sonarqube/dev/index.tsx
