### ISSUE TITLE
🐛 Bug Report: "no implementation available" after converting EntityPage to a functional component

### ISSUE THREAD

**Issue by joshjung** [backstage/backstage#27141]
### 📜 Description

Switching from `export const entityPage = <EntitySwitch...` to `export const EntityPage = () => {` breaks the entire application.

If I want to add some hooks to the base of the `EntityPage` I cannot do it.

For some reason this causes all plugins to not be found, and I cannot find an explanation why.

This works:

```
export const EntityPage = <EntitySwitch>
  ...
</EntitySwitch>
```

This does not:

```
export default () => {
  const monitoringApi = useApi(monitoringApiRef);
  monitoringApi.registerMonitoringProvider(elasticSearchMonitoringProvider);

  return <EntitySwitch>
    ...
  </EntitySwitch>;
};
```

### 👍 Expected behavior

This should not happen.

### 👎 Actual Behavior with Screenshots

It happens.

![Screenshot 2024-10-15 at 08 23 56](https://github.com/user-attachments/assets/a099dd55-0423-43aa-bc7e-c7ab67588ee9)

### 👟 Reproduction steps

Just do what is above.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Yep, this is expected and part of the design of the current frontend system, see https://backstage.io/docs/plugins/composability#using-extensions-in-an-app

**Comment by joshjung** [comment]
How in the world is anyone supposed to know they need to read that exact page in the composability section to know they cannot convert the EntityPage to a functional component?

**Comment by Rugvip** [comment]
@joshjung it's a very tricky design in general and we're moving away from it with the new frontend system. Happy for any suggested doc updates for our existing plugin docs in the meantime though

**Comment by joshjung** [comment]
For future reference, see the following section in the documentation:

https://backstage.io/docs/plugins/composability#using-extensions-in-an-app

In the meantime, I'm going to post an image of the hack @vinzscam posted in Discord so that if a future person finds this bug report, they can see what is up:

![Screenshot 2024-10-15 at 11 14 20](https://github.com/user-attachments/assets/cf802d41-e18f-4df2-8d67-93f07db28b13)
