### ISSUE TITLE
🐛 Bug Report: `EntityPicker` passes display name when `allowArbitraryValues` is `true` (as it is by default)

### ISSUE THREAD

**Issue by zcmander** [backstage/backstage#27214]
### 📜 Description

a while back I contributed a change to Backstage that modifies how `EntityPicker` shows selected value to the user: #26866

unfortunately that end up having a bug when `allowArbitraryValues` is true as in that case it will forward display name as value of field and that causes significant problems down the line.

### 👍 Expected behavior

When `allowArbitraryValues` is true it should pass entityref as it does when `allowArbitraryValues` is false.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/9780f0c5-81db-420b-9365-28fd0bca6478)

### 👟 Reproduction steps

1. Go to: https://demo.backstage.io/create/custom-fields
2. Select "Artists"
3. Click *Review*
4. Check field value, it's "Artist" instead of "domain:default/artists".

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@zcmander oh no! I'm thinking that I will raise a PR to roll this change back for now, and we can followup with another fix for the `next` release next week?

**Comment by zcmander** [comment]
As discussed in Discord: I'll look into this for the next 1.5h or so (before lunch:D). If I can't figure any fix in time then I guess we have to roll back the change and do proper fix later.
