### ISSUE TITLE
🐛 Bug Report: Techdocs missing 1 required positional argument: 'md_globals'

### ISSUE THREAD

**Issue by KL2808** [backstage/backstage#27223]
### 📜 Description

When upgrading to the new Backend System techdocs is not able to "build" documentations anymore when run inside docker. Locally its working fine and i have not changes the dockerfile at all.

The error:
```TS
Error reading page '[index.md, Opens in a new window](http://index.md/)': extendMarkdown() missing 1 required positional argument: 'md_globals'[68](https://backstage.app.private.flaschen.io/#line-68)Traceback (most recent call last):[69](https://backstage.app.private.flaschen.io/#line-69)  File "/opt/venv/bin/mkdocs", line 8, in <module>[70](https://backstage.app.private.flaschen.io/#line-70)    sys.exit(cli())[71](https://backstage.app.private.flaschen.io/#line-71)  File "/opt/venv/lib/python3.9/site-packages/click/[core.py, Opens in a new window](http://core.py/)", line 1157, in __call__[72](https://backstage.app.private.flaschen.io/#line-72)return self.main(*args, **kwargs)[73](https://backstage.app.private.flaschen.io/#line-73)  File "/opt/venv/lib/python3.9/site-packages/click/[core.py, Opens in a new window](http://core.py/)", line 1078, in main[74](https://backstage.app.private.flaschen.io/#line-74)    rv = self.invoke(ctx)[75](https://backstage.app.private.flaschen.io/#line-75)  File "/opt/venv/lib/python3.9/site-packages/click/[core.py, Opens in a new window](http://core.py/)", line 1688, in invoke[76](https://backstage.app.private.flaschen.io/#line-76)return _process_result(sub_ctx.command.invoke(sub_ctx))[77](https://backstage.app.private.flaschen.io/#line-77)  File "/opt/venv/lib/python3.9/site-packages/click/[core.py, Opens in a new window](http://core.py/)", line 1434, in invoke[78](https://backstage.app.private.flaschen.io/#line-78)return ctx.invoke(self.callback, **ctx.params)[79](https://backstage.app.private.flaschen.io/#line-79)  File "/opt/venv/lib/python3.9/site-packages/click/[core.py, Opens in a new window](http://core.py/)", line 783, in invoke[80](https://backstage.app.private.flaschen.io/#line-80)return __callback(*args, **kwargs)[81](https://backstage.app.private.flaschen.io/#line-81)  File "/opt/venv/lib/python3.9/site-packages/mkdocs/__main__.py", line 288, in build_command[82](https://backstage.app.private.flaschen.io/#line-82)[build.build, Opens in a new window](http://build.build/)(cfg, dirty=not clean)[83](https://backstage.app.private.flaschen.io/#line-83)  File "/opt/venv/lib/python3.9/site-packages/mkdocs/commands/[build.py, Opens in a new window](http://build.py/)", line 310, in build[84](https://backstage.app.private.flaschen.io/#line-84)_populate_page([file.page, Opens in a new window](http://file.page/), config, files, dirty)[85](https://backstage.app.private.flaschen.io/#line-85)  File "/opt/venv/lib/python3.9/site-packages/mkdocs/commands/[build.py, Opens in a new window](http://build.py/)", line 167, in _populate_page[86](https://backstage.app.private.flaschen.io/#line-86)page.render(config, files)[87](https://backstage.app.private.flaschen.io/#line-87)  File "/opt/venv/lib/python3.9/site-packages/mkdocs/structure/[pages.py, Opens in a new window](http://pages.py/)", line 268, in render[88](https://backstage.app.private.flaschen.io/#line-88)md = markdown.Markdown([89](https://backstage.app.private.flaschen.io/#line-89)  File "/opt/venv/lib/python3.9/site-packages/markdown/[core.py, Opens in a new window](http://core.py/)", line 126, in __init__[90](https://backstage.app.private.flaschen.io/#line-90)self.registerExtensions(extensions=kwargs.get('extensions', []),[91](https://backstage.app.private.flaschen.io/#line-91)  File "/opt/venv/lib/python3.9/site-packages/markdown/[core.py, Opens in a new window](http://core.py/)", line 181, in registerExtensions[92](https://backstage.app.private.flaschen.io/#line-92)ext.extendMarkdown(self)[93](https://backstage.app.private.flaschen.io/#line-93)TypeError: extendMarkdown() missing 1 required positional argument: 'md_globals'
```

Dockerfile:
```dockerfile
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip3 install mkdocs-techdocs-core && \
    pip3 install 'mkdocstrings[python]'
```

App config:
```yaml
 techdocs:
  builder: 'local'
  publisher:
    type: 'azureBlobStorage'
    azureBlobStorage:
      containerName: 'techdocs'
      credentials:
        accountName: prodsrebackstagewesa
  generator:
    runIn: local
```

### 👍 Expected behavior

Build and display the updates Techdocs

### 👎 Actual Behavior with Screenshots

Failing to build the Techdocs

### 👟 Reproduction steps

Copy above config and dockerfile, and try to build techdocs

### 🖥️ Your Environment

OS:   Darwin 24.0.0 - darwin/arm64
node: v18.18.2
yarn: 1.22.22
cli:  0.27.1 (installed)
backstage:  1.30.0

Dependencies:
  @backstage/app-defaults                                          1.5.11
  @backstage/backend-app-api                                       0.9.3, 1.0.0
  @backstage/backend-common                                        0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.4.4, 0.5.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.18
  @backstage/backend-plugin-api                                    0.8.1, 1.0.0
  @backstage/backend-tasks                                         0.6.1
  @backstage/backend-test-utils                                    0.5.1
  @backstage/catalog-client                                        1.7.0
  @backstage/catalog-model                                         1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.8
  @backstage/cli                                                   0.27.1
  @backstage/config-loader                                         1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.15.0
  @backstage/core-compat-api                                       0.2.8, 0.3.0
  @backstage/core-components                                       0.14.10, 0.15.0
  @backstage/core-plugin-api                                       1.9.4
  @backstage/dev-utils                                             1.1.1
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.9
  @backstage/frontend-plugin-api                                   0.7.0, 0.8.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.32
  @backstage/integration                                           1.15.0
  @backstage/plugin-api-docs                                       0.11.10
  @backstage/plugin-app-backend                                    0.3.74
  @backstage/plugin-app-node                                       0.1.25
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.17
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.7
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.7
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.2.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.19
  @backstage/plugin-auth-backend-module-github-provider            0.1.21
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.21
  @backstage/plugin-auth-backend-module-google-provider            0.1.21
  @backstage/plugin-auth-backend-module-guest-provider             0.1.10
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.19
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.17
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.6
  @backstage/plugin-auth-backend-module-okta-provider              0.0.17
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.5
  @backstage/plugin-auth-backend                                   0.22.12
  @backstage/plugin-auth-node                                      0.5.2
  @backstage/plugin-auth-react                                     0.1.6
  @backstage/plugin-bitbucket-cloud-common                         0.2.23
  @backstage/plugin-catalog-backend-module-azure                   0.2.2
  @backstage/plugin-catalog-backend-module-logs                    0.0.4
  @backstage/plugin-catalog-backend-module-msgraph                 0.6.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.22, 0.2.0
  @backstage/plugin-catalog-backend                                1.26.1
  @backstage/plugin-catalog-common                                 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.10
  @backstage/plugin-catalog-import                                 0.12.4
  @backstage/plugin-catalog-node                                   1.13.0
  @backstage/plugin-catalog-react                                  1.13.1
  @backstage/plugin-catalog                                        1.23.1
  @backstage/plugin-events-node                                    0.3.10, 0.4.0
  @backstage/plugin-home-react                                     0.1.17
  @backstage/plugin-home                                           0.7.11
  @backstage/plugin-kubernetes-backend                             0.18.6
  @backstage/plugin-kubernetes-common                              0.8.3
  @backstage/plugin-kubernetes-node                                0.1.19
  @backstage/plugin-kubernetes-react                               0.4.3
  @backstage/plugin-kubernetes                                     0.11.15
  @backstage/plugin-org                                            0.6.30
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.21
  @backstage/plugin-permission-backend                             0.5.49
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.3
  @backstage/plugin-permission-react                               0.4.26
  @backstage/plugin-proxy-backend                                  0.5.6
  @backstage/plugin-scaffolder-backend-module-azure                0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.0
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.0
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.0
  @backstage/plugin-scaffolder-backend-module-github               0.5.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.5.0
  @backstage/plugin-scaffolder-backend                             1.25.0
  @backstage/plugin-scaffolder-common                              1.5.6
  @backstage/plugin-scaffolder-node                                0.4.11
  @backstage/plugin-scaffolder-react                               1.12.1
  @backstage/plugin-scaffolder                                     1.25.1
  @backstage/plugin-search-backend-module-catalog                  0.2.2
  @backstage/plugin-search-backend-module-pg                       0.5.35
  @backstage/plugin-search-backend-module-techdocs                 0.2.2
  @backstage/plugin-search-backend-node                            1.3.2
  @backstage/plugin-search-backend                                 1.5.17
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.8.0
  @backstage/plugin-search                                         1.4.17
  @backstage/plugin-signals-react                                  0.0.5
  @backstage/plugin-techdocs-backend                               1.10.13
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.15
  @backstage/plugin-techdocs-node                                  1.12.11
  @backstage/plugin-techdocs-react                                 1.2.8
  @backstage/plugin-techdocs                                       1.10.10
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.6.0
  @backstage/theme                                                 0.5.7
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.9

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by anicke** [comment]
You probably need to pin the "mkdocstrings[python]" version. Try "mkdocstrings[python]==0.25.2".

**Comment by KL2808** [comment]
@anicke it worked! Thank you i was trying so many thing but did not thought about removing/downgrading mkdocsstrings... You're a gem! 💎
<img width="1486" alt="image" src="https://github.com/user-attachments/assets/dd3bf928-cd36-40b7-a196-22d959b2c6b0">
