### ISSUE TITLE
🚀 Feature: Catalog Index Customization Add Column Example

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#27238]
### 🔖 Feature description

We should add an example of how to add a column when customizing the catalog index page

### 🎤 Context

If you want to add a new column to the catalog index page it's not clear how to do that without diving into the code base

### ✌️ Possible Implementation

You could just look at this - https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/columns.tsx - and then come up with a column that isn't in this list. Maybe an example of showing a User's email address.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by JP-sDEV** [comment]
Hi can I be assigned this ticket?

**Comment by awanlin** [comment]
Just wanted to add that this would get added to this section of the current docs on this subject: https://backstage.io/docs/features/software-catalog/catalog-customization#customize-columns and the source file for that is here: https://github.com/backstage/backstage/blob/master/docs/features/software-catalog/catalog-customization.md

**Comment by awanlin** [comment]
Hi @JP-sDEV, sure, make sure to take account what I just posted above when you begin working on this 👍

**Comment by JP-sDEV** [comment]
I followed the "Getting Started" section in `CONTRIBUTING.md` and when installing via `yarn install` - `canvas 2.11.2` and `isolated-vm 4.7.2` fail to install. Is this a common error?

**Comment by JP-sDEV** [comment]
Hi @awanlin, I'm still getting an issue with Node v20.9.0 getting the same error when installing `canvas@npm:2.11.2`

**Comment by jescalada** [comment]
Hello @awanlin, I just made a small PR for this issue after experimenting with implementing the email column for the User entity. https://github.com/backstage/backstage/pull/27353

I may have missed the point though, please let me know your thoughts!

Thank you :)

**Comment by jescalada** [comment]
@JP-sDEV Sorry for jumping to contribute without asking! 😓 I am currently using Node v21.1.0 without issues after following their setup guide, have you tried going through the guide with that version? I also had issues with other versions such as Node 18 on WSL (due to dependency resolution mishaps), and Node 22 on Windows, but Node 21 works like a charm.
