### ISSUE TITLE
🐛 Bug Report: Microsoft Additional Scopes not working as intended

### ISSUE THREAD

**Issue by TheGemmell** [backstage/backstage#27259]
### 📜 Description

When Entra ID/Microsoft additional scopes are passed in via the app-config, there is logic for detecting if a specified custom resource is having it's scopes requested and if so, to only include those requested scopes as well as 'offline_access' to ensure Backstage gets a refresh token.

https://github.com/backstage/backstage/blob/6cbe4f999c9c8e9e090d3be5a7c3af71d59e507d/plugins/auth-backend-module-microsoft-provider/src/authenticator.ts#L31-L40

I have tested this in a live environment where it is highly beneficial to request specific scopes through custom resources and through monkey-patching, it appears that there was just a small oversight; the passed in additionalScopes config key is passed in as the 'additional' parameter, not as 'requested' and simply modifying lines 36 and 38, it is fixed.

Reporting this issue so I can make the fix and commit back to allow for myself and anyone else wanting to take full advantage of it, without the need for custom patches to be applied at runtime.

### 👍 Expected behavior

When a custom `<resource>/<scope>` is passed into the additionalScopes key in the app-config. Backstage should ignore the default scopes required and only request the additionalScopes & 'offline_access'

### 👎 Actual Behavior with Screenshots

Can't provide screenshots unfortunately, but what happens instead is the request to Entra ID to exchange the opaque token for an access token instead requests for the entire default scopes as well as the custom resource's scopes, which results in errors.

### 👟 Reproduction steps

1. Put a custom resource's scope into your `additionalScopes` key for your app-config's Microsoft auth provider. ie:
```auth:
  environment: development
  providers:
    microsoft:
      development:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        domainHint: ${AZURE_TENANT_ID}
        additionalScopes:
          - c8271-etc-etc/User.Read
```
2. Any authentication attempts from Backstage will fail with Microsoft errors as Backstage just appends the custom resource's scope to it's scopes, instead of replacing

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Thank you for reporting! We don't use this aurh provider ourselves and it's a bit of a tricky one so bear with us as we figure it out :sweat_smile: 

How come you need to add a resource scope as an additional scope? Iirc the issue here is that you can only request scopes for one resource at a time, so we would need additional logic to filter the additional scopes and verify that they aren't for a mix of resources. If the client is requesting scopes we'd need need to make sure those don't conflict with the additional ones. That might get pretty confusing too though as the scopes may or may not be included, depending on the request. It might honestly be best to reject additional scopes for resources. Do you need this additional scope specifically for sign-in?

**Comment by TheGemmell** [comment]
We personally need it as we have custom claims provided with our Backstage application registration in Entra ID, but if we request the generic User.Read from the Microsoft Graph resource, it won't provide those custom claims, we need to request it via a custom resource. The proposed one line fix just utilises the already written check to see it's a custom resource. This doesn't interfere with people requesting more scopes that aren't specified on a custom resource, say; Calendar.Read or Mail.Write, etc.

The current check here:
https://github.com/backstage/backstage/blob/6cbe4f999c9c8e9e090d3be5a7c3af71d59e507d/plugins/auth-backend-module-microsoft-provider/src/authenticator.ts#L36-L39

Already detects if it's a custom resource via the forward slash. It's just that at the moment, it checks the wrong array of passed in options, requested instead of additional. Just need to change that check to use `additional` not `requested`

If people don't need this for sign-in but want to get it after log-in, they can still request it via the getAccessToken method on the microsoftAuthApi and passing in the requested scope.
