### ISSUE TITLE
🐛 Bug Report: cannot build docker image with Dockerfile from documentation

### ISSUE THREAD

**Issue by vasili439** [backstage/backstage#27271]
### 📜 Description

I'm trying to build new image with multistage build as described here: https://backstage.io/docs/deployment/docker#multi-stage-build
I've replaced .dockerignore according documentation but during the build I got:
```
569.3  YN0000: └ Completed in 9m 16s
569.3  YN0000: Failed with errors in 9m 22s
------
Dockerfile:44
--------------------
  43 |     
  44 | >>> RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
  45 | >>>     yarn install --immutable
  46 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn install --immutable" did not complete successfully: exit code: 1
```
what could be the issue?
```
docker --version
Docker version 26.0.0, build 2ae903e
```

### 👍 Expected behavior

Docker container ready to push to docker registry

### 👎 Actual Behavior with Screenshots

```
569.3 ➤ YN0000: └ Completed in 9m 16s
569.3 ➤ YN0000: Failed with errors in 9m 22s
------
Dockerfile:44
--------------------
  43 |     
  44 | >>> RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
  45 | >>>     yarn install --immutable
  46 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn install --immutable" did not complete successfully: exit code: 1
```

### 👟 Reproduction steps

1. Go to: https://backstage.io/docs/deployment/docker#multi-stage-build
2. Clone git repo + checkout to latest release tag
3. Copy Dockerfile content and put it in git repo's root
4. Replace .dockerignore with file provided in documentation
5. Run `docker image build -t backstage .`

### 📃 Provide the context for the Bug.

Fail to build docker image

### 🖥️ Your Environment

```
docker --version
Docker version 26.0.0, build 2ae903e
```
```cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @vasili439, cloning the Backstage repo is not the supported or recommended path for this. The[ documentation you linked](https://backstage.io/docs/deployment/docker/#multi-stage-build:~:text=This%20section%20assumes%20that%20an%20app%20has%20already%20been%20created%20with%20%40backstage/create%2Dapp) calls this out at the very top. I would follow the [getting started guide](https://backstage.io/docs/getting-started/) and then try this again 👍

**Comment by vasili439** [comment]
@awanlin thanks for your reply. Will follow guide you have provided
