### ISSUE TITLE
🚀 Feature: Keep CatalogKindHeader

### ISSUE THREAD

**Issue by javiermartingonzalez** [backstage/backstage#27275]
### 🔖 Feature description

According to [CatalogKindHeader](https://backstage.io/docs/reference/plugin-catalog.catalogkindheader) deprecation warning "_This component has been deprecated in favour of the EntityKindPicker in the list of filters. If you wish to keep this component long term make sure to raise an issue at github.com/backstage/backstage_", I want to keep the component.

I tried the EntityKindPicker but I don't like the design, I prefer the old one. The functionality is the same but the "new" layout is taking lotf of space and is not aligned correctly.

**Old CatalogKindHeader**:

![old1](https://github.com/user-attachments/assets/9d7631ee-ebc3-4182-91f5-2c847e5e276a)
![old2](https://github.com/user-attachments/assets/07962c29-6d92-4ed5-94c0-83ad583b7dc2)

**New EntityKindPicker**:
![new1](https://github.com/user-attachments/assets/f43601bd-40ed-4c60-86a3-aab217582334)
![new2](https://github.com/user-attachments/assets/4c7d556c-e7b4-4b45-ae07-8ae82983355b)

### 🎤 Context

As showed before, the behaviour is the same but the new layout is not well designed.

### ✌️ Possible Implementation

Keep both components or be able to add some customizations to choose the layout

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by jhaals** [comment]
That does not look like it is used correctly based on the appearance in that screenshot. See the demo site which is using the new filter https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Bnamespace%5D=default&filters%5Buser%5D=all&limit=20

**Comment by javiermartingonzalez** [comment]
OK, I'm using CustomPage and I checked that the idea in the demo is to have the Kind selector into the filters tabs and not in the title.

Thanks!

![newfinal](https://github.com/user-attachments/assets/2421529a-2796-415c-9272-6c06f926a25c)

**Comment by camilaibs** [comment]
Hey @javiermartingonzalez, yes the new component is currently designed for use in filters lists. If you find the time, we would greatly appreciate a pull request suggesting how we might improve it for reuse in other places 🙂 .
