### ISSUE TITLE
🐛 Bug Report: The deprecation process is poorly executed

### ISSUE THREAD

**Issue by planeiii-te** [backstage/backstage#27279]
### 📜 Description

This is not a code issue. This is a people/communication/documentation problem.

I understand that `@backstage/backend-common` is deprecated. The process to deprecate it has provided a poor developer experience. 

The primary APIs we were using were `errorHandler` for `express` and `getVoidLogger` for unit testing. I searched for those things directly which resulted in 404s on the documentation site as well as 404s in the GitHub repo. Ultimately I had to search Discord to find other people asking the same questions and looking for the same breadcrumbs to be able to get the system upgraded. This process should be so much better and more convenient.

### 👍 Expected behavior

The Backstage team provides a _clear path_ for developers to follow to replace the deprecated APIs in their code with the new APIs and the where to import those new APIs from.

### 👎 Actual Behavior with Screenshots

There is nothing but dead ends available to upgrading developers. The package itself has an incomplete deprecation message. Looks like it was _almost_ going to be useful.

<img width="1192" alt="image" src="https://github.com/user-attachments/assets/2d2be0f4-232a-4afd-8eca-77ebc7177189">

The documentation where I would expect to find statements like "replace `errorHandler` with `X` from `@backstage/new-package-name`" is just a [404 now](https://backstage.io/docs/reference/backend-common.errorhandler/). [This](https://backstage.io/docs/reference/backend-common.getrootlogger/) would be a great place to provide a diff of the upgrade process (before and after with the new API location).

<img width="1181" alt="image" src="https://github.com/user-attachments/assets/ecf36a04-1581-4743-a38e-87107fb6559b">

Maybe find the [old package in source](https://github.com/backstage/backstage/tree/master/packages/backend-common) and look for that documentation there? Nope. Another dead end. 

<img width="1239" alt="image" src="https://github.com/user-attachments/assets/ba0a11da-c6dc-45b8-a822-8b149ad18a94">

### 👟 Reproduction steps

1. Try to find an upgrade path from the deprecated APIs provided in `@backstage/backend-common`.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Thank you for your feedback! 🙏 

I realize our deprecation strategy is very heavily centered around feedback in local development and relies on editors/IDEs that highlight deprecation message. Without looking at those there is very little information to be found indeed. The good news is that we do have instructions for the deprecation of all exports from the `@backstage/backend-common` package!

Closing this gap in #27332
