### ISSUE TITLE
🐛 Bug Report: Upgrading to 1.32.2 fails on database migration

### ISSUE THREAD

**Issue by acierto** [backstage/backstage#27272]
### 📜 Description

Upgrading to 1.32.2 fails on database migration.

### 👍 Expected behavior

It should upgrade smoothly.

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-10-21 at 09 57 28](https://github.com/user-attachments/assets/0aa04965-5773-4084-b422-2186d8f797af)

It feels like the plugin just doesn't load them properly.

### 👟 Reproduction steps

Just follow the normal procedure of upgrade.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jhaals** [comment]
Sorry to hear that! From which version did you upgrade? Would like to be able to see if we can reproduce this ourselves.

**Comment by acierto** [comment]
Hey @jhaals 👋 

Atm we are on `1.31.2`, first time seeing such problem during migration 😅
