### ISSUE TITLE
🐛 Bug Report: ObservableConfigProxy Does Not Thrown an Error When Getting a Missing Config (via getConfig)

### ISSUE THREAD

**Issue by gobrgotm** [backstage/backstage#27288]
### 📜 Description

The `ObservableConfigProxy` class implements the `Config` interface. In the interface definition, `getConfig(key: string)` should have the following behaviour: "Same as getOptionalConfig, but will throw an error if there's no value for the given key."

The `ConfigReader` class also implements the `Config` interface, and its `getConfig(key: string)` method does indeed throw an error when there is no value for a given key.

```javascript
// from ConfigReader
getConfig(key: string): ConfigReader {
  const value = this.getOptionalConfig(key);
  if (value === undefined) {
    throw new Error(errors.missing(this.fullKey(key), this.context));
  }
  return value;
}
```
However, `ObservableConfigProxy's` `getConfig(key: string)` method does not throw an error when there is no value for a given key. Instead, it will return an instance of the `ObservableConfigProxy` with no internal values.

```javascript
// from ObservableConfigProxy
getConfig(key: string): Config {
  return new ObservableConfigProxy(this, key);
}

// constructor being called
private constructor(
  private readonly parent?: ObservableConfigProxy,
  private readonly parentKey?: string,
  private readonly abortController?: AbortController,
) {
  if (parent && !parentKey) {
    throw new Error('parentKey is required if parent is set');
  }
}
```

When writing a plug-in, the `Config` returned by the `coreServices.rootConfig` seems to be an instance of `ObservableConfigProxy`, which exhibits unexpected behaviour when retrieving a non-existent configuration.

### 👍 Expected behavior

When retrieving a configuration that doesn't exist using `ObservableConfigProxy's` `getConfig(key: string)` method, an error should be thrown (similar to `ConfigReader`).

### 👎 Actual Behavior with Screenshots

During debugging, the `Config` returned is an instance of `ObservableConfigProxy`. Even though `this.config.getConfig('spreadsheet')` should return null and throw an error because the "spreadsheet" section doesn't exist in the config YAML file. However, what is returned is an instance of `ObservableConfigProxy`. 
![getConfigNotThrowingErrors](https://github.com/user-attachments/assets/da3979fe-74e0-42ee-a8f4-2eb6e6a530f8)

This screenshot shows the `spreadsheetConfig` returned is an instance of `ObservableConfigProxy` with no values:
![listOfSpreadsheetConfigs](https://github.com/user-attachments/assets/79951b8f-8d6b-49d2-8969-05b6cb908edf)

This screenshot shows `this.config` does not have a key called `spreadsheet`, so `this.config.getConfig('spreadsheet')` should throw an error: 
![listOfAllConfigKeys](https://github.com/user-attachments/assets/ca536e14-a1dc-4345-94e9-d591ab15a17c)

This behaviour means we can't rely on `getConfig(key: string)` throwing an error when the necessary configuration for a plug-in is missing. Instead, we must use `getOptionalConfig(key: string)` and do a null check. The main issue is that the behaviour differs from what is documented in the `Config` interface.

### 👟 Reproduction steps

1. Create a plug-in that expects an instance of `RootConfigService` (in the constructor)
2. In the module to load the plug-in, retrieve an instance of the configuration via `coreServices.rootConfig` and passes it into the plug-in's constructor
3. Within the plug-in, use the passed in instance of `RootConfigService` to retrieve a configuration that does not exist (no value associated with a key) using `config.getConfig(key: string)`
4. Based on the `Config` interface's definition, an error should be thrown, but no error is throw. Instead, an instance of `ObservableConfigProxy` is returned with no values

### 📃 Provide the context for the Bug.

I found this bug while writing a plug-in to ingest entity information to populate the catalogue. While debugging my implementation, I noticed a weird behaviour while trying to retrieve a configuration from my YAML file. I then realised I made a typo, so the configuration section doesn't exist in the YAML file, but no error was thrown. I expected errors to be thrown in such situations based on the documentation associated with the `Config` interface.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hi @gobrgotm thanks for providing such details about the issue.
Would you be interested in investigating and sharing the impact of the change? We think that would be helpful information for us to consider 🙂 .

**Comment by Emhdirahmani** [comment]
Ok📣😘😘😘😘😘👀🎯

**Comment by freben** [comment]
For posterity - this is more of a docs issue than a bug; it is intentionally made to work this way. It's a common pattern to make a single `getConfig` at the top of your code to get the "root" of your config block.

If you then do individual `getString` etc relatively off of that, you get a more precise error message saying what full key wasn't present.

If you instead do a `getOptionalString` off of it, you get the proper undefined back without extra levels of checks.

Convenient but can also confuse - a double edged sword perhaps. If it were named `withPrefix` instead of `getConfig` it might have been clearer.
