### ISSUE TITLE
🐛 Bug Report: Microsoft Azure Authentication always require "Approve sign in request" via the Authenticator app every time a user signs in

### ISSUE THREAD

**Issue by pointmekin** [backstage/backstage#27290]
### 📜 Description

After running yarn backstage-cli versions:bump from version "1.19.6" to "1.31.3", then Azure AD authentication popup no longer remembers the email and password saved by the browser. Additionally, each time a user signs in, the user needs to "Approve sign in request" by filling in the number shown in the authenticator app every single time.

### 👍 Expected behavior

It should show the available accounts previously used to sign in and it should not ask for the user to "Approve sign in request" by filling in the number shown in the authenticator app every single time.

![image](https://github.com/user-attachments/assets/e570e102-4414-4cf8-a171-c9d41d726a37)

### 👎 Actual Behavior with Screenshots

The browser doesn't save the previous sign in information
![image](https://github.com/user-attachments/assets/9b8cd23a-991c-4968-9925-915d4943b183)

Each time the user signs in, the user is always presented with the screen requiring approval from Authenticator app.
![image](https://github.com/user-attachments/assets/b9d4af10-37ca-4b24-98f5-d34b446eb566)

### 👟 Reproduction steps

1. run `yarn backstage-cli versions:bump` from version "1.19.6" to "1.31.3"
2. configure Microsoft auth according to https://backstage.io/docs/auth/microsoft/provider/
3. configure a custom signin resolver according to https://backstage.io/docs/auth/identity-resolver/#building-custom-resolvers
4. start Backstage in dev mode with `yarn dev`
5. sign in using "Sign in using Azure Active Directory"

---

We use a custom authentication provider and followed the instructions specified in https://backstage.io/docs/auth/identity-resolver/#building-custom-resolvers
```ts
...

// Customer Resolve
export const authModuleMicrosoftProvider = createBackendModule({
    pluginId: 'auth',
    moduleId: 'microsoftProvider',
    register(reg) {
        reg.registerInit({
            deps: { providers: authProvidersExtensionPoint },
            async init({ providers }) {
                providers.registerProvider({
                    providerId: 'microsoft',
                    factory: createOAuthProviderFactory({
                        authenticator: microsoftAuthenticator,
                        async signInResolver(fullProfile, ctx) {
 
                            // ... resolver logic ...
                            
                            const issuedToken = ctx.issueToken({
                                claims: {
                                    sub: userRef,
                                    ent,
                                },
                            });
                            return issuedToken;
                        },
                    }),
                });
            },
        });
    },
});
...

backend.add(authModuleMicrosoftProvider);

...
```
Here is our app-config.local.yaml
```yaml
...
auth:
  environment: development
  providers:
    microsoft:
      development:
        clientId: '...'
        clientSecret: '...'
        tenantId: '...'
...      
```

### 📃 Provide the context for the Bug.

For context, we enabled 2-factor authentication, requiring all users to connect the Microsoft account to a the Microsoft Authenticator app.

We previously bumped the Backstage version from "1.19.6" to "1.31.3"

Previously, it was only about once per day before the user needs to fill in the number in the authenticator app again. As of the latest version, the user needs to enter the email, password, and authentication number every time the user signs in.

We're trying to make the authentication flow the same as it was in version 1.19.6

### 🖥️ Your Environment

OS:   Darwin 23.6.0 - darwin/arm64
node: v18.20.4
yarn: 1.22.19
cli:  0.27.1 (installed)
backstage:  1.31.3

Dependencies:
  @backstage/app-defaults                                          1.5.11
  @backstage/backend-app-api                                       0.7.5, 1.0.0
  @backstage/backend-common                                        0.21.7, 0.22.0, 0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.5.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.18
  @backstage/backend-plugin-api                                    0.6.18, 0.8.1, 1.0.0, 1.0.1
  @backstage/backend-tasks                                         0.5.23, 0.6.1
  @backstage/catalog-client                                        1.7.0, 1.7.1
  @backstage/catalog-model                                         1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.8
  @backstage/cli                                                   0.27.1
  @backstage/config-loader                                         1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.15.0
  @backstage/core-compat-api                                       0.2.8, 0.3.0
  @backstage/core-components                                       0.14.10, 0.14.7, 0.15.0
  @backstage/core-plugin-api                                       1.9.4
  @backstage/dev-utils                                             1.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.9
  @backstage/frontend-plugin-api                                   0.6.7, 0.7.0, 0.8.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.32
  @backstage/integration                                           1.15.0
  @backstage/plugin-api-docs                                       0.11.10
  @backstage/plugin-app-backend                                    0.3.75
  @backstage/plugin-app-node                                       0.1.25
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.0
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.0
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.2.0
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.0
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.0
  @backstage/plugin-auth-backend-module-github-provider            0.2.0
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.0
  @backstage/plugin-auth-backend-module-google-provider            0.2.0
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.0, 0.2.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.0
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.0
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.0
  @backstage/plugin-auth-backend-module-okta-provider              0.1.0
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.0
  @backstage/plugin-auth-backend                                   0.23.0
  @backstage/plugin-auth-node                                      0.4.13, 0.5.2, 0.5.3
  @backstage/plugin-auth-react                                     0.1.6
  @backstage/plugin-bitbucket-cloud-common                         0.2.23
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.0
  @backstage/plugin-catalog-backend                                1.26.1
  @backstage/plugin-catalog-common                                 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.10
  @backstage/plugin-catalog-import                                 0.12.4
  @backstage/plugin-catalog-node                                   1.13.0
  @backstage/plugin-catalog-react                                  1.13.1
  @backstage/plugin-catalog                                        1.23.1
  @backstage/plugin-events-node                                    0.3.4, 0.4.0
  @backstage/plugin-github-actions                                 0.6.16
  @backstage/plugin-home-react                                     0.1.17
  @backstage/plugin-home                                           0.7.11
  @backstage/plugin-org                                            0.6.30
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.1
  @backstage/plugin-permission-backend                             0.5.50
  @backstage/plugin-permission-common                              0.7.13, 0.8.1
  @backstage/plugin-permission-node                                0.7.29, 0.8.3, 0.8.4
  @backstage/plugin-permission-react                               0.4.26
  @backstage/plugin-proxy-backend                                  0.5.6
  @backstage/plugin-scaffolder-backend-module-azure                0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.0
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.0
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.0
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.0
  @backstage/plugin-scaffolder-backend-module-github               0.5.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.5.0
  @backstage/plugin-scaffolder-backend                             1.25.0
  @backstage/plugin-scaffolder-common                              1.5.6
  @backstage/plugin-scaffolder-node                                0.4.11
  @backstage/plugin-scaffolder-react                               1.12.1
  @backstage/plugin-scaffolder                                     1.25.1
  @backstage/plugin-search-backend-module-catalog                  0.2.2
  @backstage/plugin-search-backend-module-pg                       0.5.35
  @backstage/plugin-search-backend-module-techdocs                 0.2.2
  @backstage/plugin-search-backend-node                            1.3.2
  @backstage/plugin-search-backend                                 1.5.17
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.8.0
  @backstage/plugin-search                                         1.4.17
  @backstage/plugin-signals-node                                   0.1.11
  @backstage/plugin-signals-react                                  0.0.2, 0.0.5
  @backstage/plugin-tech-radar                                     0.7.4
  @backstage/plugin-techdocs-backend                               1.10.13
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.15
  @backstage/plugin-techdocs-node                                  1.12.11
  @backstage/plugin-techdocs-react                                 1.2.8
  @backstage/plugin-techdocs                                       1.10.10
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.6.0
  @backstage/theme                                                 0.5.7
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.9

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by camilaibs** [comment]
Hi @pointmekin, It is indeed an unexpected behavior, and we suspect that the refresh token is not properly stored. Does this troubleshooting docs helps?
https://backstage.io/docs/auth/troubleshooting/#inspecting-the-refresh-call
