### ISSUE TITLE
🐛 Bug Report: extra paths added for openAPI references splitted in several files for plugin "plugin-catalog-backend-module-openapi"

### ISSUE THREAD

**Issue by dancer1325** [backstage/backstage#27324]
### 📜 Description

If you are trying to register an API, using `@backstage/plugin-catalog-backend-module-openapi`, in which OpenApi file is splitted in several files,references by `$ref:`, the file "jsonSchemaRefPlaceholderResolver.ts" is adding an 👀 extra 👀 relative path url, making impossible the register

https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-openapi/src/jsonSchemaRefPlaceholderResolver.ts#L38

### 👍 Expected behavior

Being able to register the API

### 👎 Actual Behavior with Screenshots

> Error: Placeholder $openapi unable to bundle the file at ./*/dancer-swagger.yaml, ResolverError: Error reading file \"https://github.*/master/*/components/components/schemas.yaml\""},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}

Remark the 👀 extra `/components/` 👀, that the error is hitting, and obviously failing miserable the register.  In the reproduction steps, you can visualize how the reference does NOT duplicate that `/components` that the "jsonSchemaRefPlaceholderResolver.ts" is identifying

### 👟 Reproduction steps

Let's have the next structure of folders in a github repo
  <img width="219" alt="image" src="https://github.com/user-attachments/assets/f0129f5a-586a-47af-8db0-d729260eb879">

  <img width="429" alt="image" src="https://github.com/user-attachments/assets/61205789-a115-4999-9e01-b81fc25766ba">
  
  <img width="575" alt="image" src="https://github.com/user-attachments/assets/854f940f-e28b-4da7-9515-908228f91f20">
  
  <img width="299" alt="image" src="https://github.com/user-attachments/assets/7962645c-48a5-4e98-b325-82e87833ec89">

### 📃 Provide the context for the Bug.

Registering an API dynamically (NOT statically, via locations)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by aramissennyeydd** [comment]
👋 Does this work if you specify the full path (relative to the repo or just the full URL)?

**Comment by dancer1325** [comment]
> 👋 Does this work if you specify the full path (relative to the repo or just the full URL)?

Hi @aramissennyeydd , thank you so much, for the fast reply. If you refer to the url pass in the box, I am passing the full URL, directly to the "catalog-info.yaml" file
  <img width="706" alt="image" src="https://github.com/user-attachments/assets/8536fb0d-04c3-44a9-bf67-0de66c4919de">

**Comment by aramissennyeydd** [comment]
@dancer1325 Can you see if this works without the `/components` prefix in your spec?

**Comment by dancer1325** [comment]
> @dancer1325 Can you see if this works without the `/components` prefix in your spec?

Hi @aramissennyeydd ,

Then, the generation of classes do NOT work. The whole context is that those ".yaml" are originally consumed by https://openapi-generator.tech/, to generate the classes

**Comment by aramissennyeydd** [comment]
@dancer1325 Makes sense, I meant it only as a testing approach to see what the issue is here.
