### ISSUE TITLE
🐛 Bug Report: Searching User or Group entities by displayName in the catalog table doesn't work

### ISSUE THREAD

**Issue by Julien-Hery** [backstage/backstage#27354]
### 📜 Description

When searching in the catalog table an entity of `kind: User` or `kind: Group` using the value of its `spec.profile.displayName` no results are returned

### 👍 Expected behavior

When searching in the catalog table it is possible to search for entities of `kind: Component` by their `metadata.title`
I would expect the same to be possible for `kind: User` and `kind: Group` but with `spec.profile.displayName` as they don't have `metadata.title`.
Moreover, using global search it is possible to search users and groups by `displayName`

### 👎 Actual Behavior with Screenshots

Failing to search by displayName in the catalog table : 
<img width="1161" alt="Capture d’écran 2024-10-25 à 12 20 48" src="https://github.com/user-attachments/assets/492fb1b5-0e3f-45b9-bbc0-4c6e2b01ad2c">

Working with the global search : 
<img width="1297" alt="Capture d’écran 2024-10-25 à 12 21 11" src="https://github.com/user-attachments/assets/c65b1ab7-9339-4351-ac15-872a2a36b8ed">

Expected behavior : 
<img width="1154" alt="Capture d’écran 2024-10-25 à 12 23 15" src="https://github.com/user-attachments/assets/41857d07-4d43-4cdb-8a39-5fdbe78e218a">

### 👟 Reproduction steps

1. Go to [demo site](https://demo.backstage.io/catalog?filters%5Bkind%5D=user&filters%5Bnamespace%5D=default&filters%5Buser%5D=all&limit=20)
2. Search user by its `displayName` (actually it's the value displayed on each rows). If you put just first word it will usually work because the `metadata.name` is something like `amelia.park` so be sure to put more than just the first word
3. No results displayed

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
@Julien-Hery , thank you for opening a pull request 🙌🏻 . Just letting you know that we are in reduced capacity this week, so it might take us a little while to get it reviewed.
