### ISSUE TITLE
🚀 Feature: Personalize Template Publish Process with Custom Documentation

### ISSUE THREAD

**Issue by Teemukoivumaa** [backstage/backstage#27364]
### 🔖 Feature description

You should be able to modify the "Publish changes"-documentation in the template editor page so that you can guide your contributors to use the process that you use.

### 🎤 Context

Currently all of the texts are staticly declared in here: [plugins/scaffolder/src/translation.ts](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/translation.ts#L321) and are not applicable for everyone. 

Allowing for custom documentation to be added for your own Backstage instance makes it easier for contributors to know the template publish process you use.

Current text:
![image](https://github.com/user-attachments/assets/ee3778b2-210e-4601-8471-7c9f6e488f80)

### ✌️ Possible Implementation

Possibly having the possibility to declare this info in the app-config.yaml file like you can declare what to show in the [support buttons](https://github.com/backstage/backstage/blob/master/app-config.yaml#L15) and then using that text instead of the default one?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hi @Teemukoivumaa 👋🏻 , to better understand what you would like to be able to do, would it be hiding this modal or changing its layout, or would it be more changing the text? I'm asking because it is currently possible to change the text by [overriding](https://backstage.io/docs/plugins/internationalization#for-an-application-developer-overwrite-plugin-messages) the default translation file.

**Comment by Teemukoivumaa** [comment]
@camilaibs it's about changing the text ("customizing" it so it suits our process)😊

 I will check the link you have provided and see if that solves this!
