### ISSUE TITLE
🐛 Bug Report: docs -- isolated-vm does not compile on Jod LTS release

### ISSUE THREAD

**Issue by jghiloni** [backstage/backstage#27396]
### 📜 Description

The docs state that backstage works with the Active Node LTS version. However, the `isolated-vm` package does not compile on MacOS Sequoia on node version 22.x (`lts/Jod`). When I back-level to `20.x` (`lts/Iron`) it compiles successfully

### 👍 Expected behavior

The docs accurately list the versions of Node that work

### 👎 Actual Behavior with Screenshots

I know Jod is very new to the LTS stream so this just needs to be updated till the package is fixed.

### 👟 Reproduction steps

Follow the steps to create a new backstage app with Node.js v22

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Related: https://github.com/backstage/backstage/issues/27403

**Comment by camilaibs** [comment]
Hi @jghiloni, could you please take a look at this comment?
https://github.com/backstage/backstage/issues/27403#issuecomment-2449526277
cc/ @Rugvip

**Comment by Rugvip** [comment]
This was fixed by #27286, but you'll need to wait for the 1.33 Backstage release to be published, or use a `next` release.

It's the bump of `isolated-vm` from v4 to v5 that fixes this, since v5 is required for Node.js 22

**Comment by awanlin** [comment]
Hi @jghiloni, what page did you look at? Was it this one: https://backstage.io/docs/overview/versioning-policy#nodejs-releases? If so the second bullet point says this: "Once a new Node.js release becomes Active LTS we switch to support that release and the previous one. The switch is not immediate but done as soon as possible. "

Is there something you suggest we could improve on this to make that more clear? I did take a swing at it in #27415
