### ISSUE TITLE
Add a Card to the Lighthouse plugin which displays scores using GaugeProgress

### ISSUE THREAD

**Issue by iain-b** [backstage/backstage#2740]
## Feature Suggestion

Based on the conversation in #2709 It would be nice to have a more visual display of lighthouse scores like, lighthouse itself:
![image](https://user-images.githubusercontent.com/1415599/95016788-1afd7a00-064d-11eb-8d75-750acbf81df0.png)

## Possible Implementation

We could use an array of GaugeProgress elements. Ideally these would be a medium / small size.

## Context

I've created #2738  also so that we have more control over GaugeProgress sizing. Probably best to wait until that's been looked at.

**Comment by blueelvis** [comment]
I would like to pick this up.

**Comment by stefanalund** [comment]
All yours @blueelvis -- thanks 🙏
