### ISSUE TITLE
🐛 Bug Report: missing webpack loader for webp imports

### ISSUE THREAD

**Issue by Antolius** [backstage/backstage#27411]
### 📜 Description

Webpack configuration is missing a loader for handling imports of *.webp images.

### 👍 Expected behavior

It should be possible to import webp images from typescript srouce files.

### 👎 Actual Behavior with Screenshots

Webpack error is thrown.

![Screenshot 2024-10-31 at 14-56-17 Backstage Example App](https://github.com/user-attachments/assets/2391bc51-a07a-4fef-ab09-7475b90f236f)

### 👟 Reproduction steps

Create a .webp image and try importing it into a source file.

### 🖥️ Your Environment

Current master branch of the backstage repo.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Antolius** [comment]
I hope you don't mid me reporting this as a bug. It could be considered a new feature request, as I think this never worked. I opened it as a bug because I noticed there is some config for webp in [asset-types.d.ts](https://github.com/backstage/backstage/blob/d02e2dd8a41a070a470ec59cdca4cf4f9c743951/packages/cli/asset-types/asset-types.d.ts#L53-L56), so I guess that there is assumption that it should work.

**Comment by Rugvip** [comment]
Thank you for reporting!

This would require fixes in these areas:
- bundling: https://github.com/backstage/backstage/blob/e4125fb698cd361086918a5acd4f21727126c001/packages/cli/src/lib/bundler/transforms.ts#L144-L152
- building: https://github.com/backstage/backstage/blob/ea1663376eb45753c0de4722a0e25e2faefbd82f/packages/cli/src/lib/builder/config.ts#L165-L174
- testing: https://github.com/backstage/backstage/blob/6819f8cef2ad79583750ebb893073159c67b1007/packages/cli/config/jest.js#L216

Would you like to contribute a fix?
