### ISSUE TITLE
🚀 Feature: Add Headlamp UI support for Kubernetes dashboard integration

### ISSUE THREAD

**Issue by yolossn** [backstage/backstage#27463]
### 🔖 Feature description

Requesting Integration for Headlamp Kubernetes dashboard.

### 🎤 Context

The kubernetes plugin supports various dashboards like k8s dashboard, rancher, gke, etc. Requesting support for [Headlamp](http://www.headlamp.dev)

### ✌️ Possible Implementation

Have raised a PR here https://github.com/backstage/backstage/pull/27383

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mclarke47** [comment]
I'm honestly not a huge fan of how the current dashboard formatting works and think it needs a bit of an overhaul, it's also very under documented

**Comment by yolossn** [comment]
Agree on the under documentation, the link in the [docs](https://backstage.io/docs/features/kubernetes/configuration/#clustersdashboardapp-optional) to see example formatter implementation is also broken.

**Comment by teemow** [comment]
A first version of a backstage plugin was released: https://github.com/headlamp-k8s/backstage-plugin

Thanks @yolossn

**Comment by vinzscam** [comment]
Closing this issue as it isn't related to the core project, but it could be an addition to https://github.com/backstage/community-plugins

**Comment by yolossn** [comment]
@vinzscam AFAIU the kubernetes plugin is part of the core, this issue is related to adding headlamp support to the `kuberntes-react` plugin. I have raised a [PR](https://github.com/backstage/backstage/pull/27383/files) for this.
