### ISSUE TITLE
[RFC] Squad/Group page

### ISSUE THREAD

**Issue by JacobValdemar** [backstage/backstage#2752]
**Status:** Open for comments

## Need

With the implementation of #1401 it should be possible to create a page for squads (technical groups). This comes from a need to make it possible for a squad to get a holistic overview in regards to what the squad owns and has responsibility for.

## Proposal

![billede](https://user-images.githubusercontent.com/16527874/95062689-9c144a00-06fd-11eb-8194-fbfbf18ebb08.png)

I think the most natural implementation would be to have it as an entity page for the group entity defined in #1401. Thus, the squad page can also be built with tabs in the same way as other entities. These tabs can be plugins or they can be categories in which there are different components belonging to plugins that can be inserted. I think I prefer the last one, which is similar to the vision for the overview page in the service entity. I think it would be an easy solution to reuse a lot of what has already been implemented for entity pages in general.

I imagine that it could be possible for **each squad to customize their own overview page** based on what they would like to see. Maybe this would be configured in the yaml file that contains the group entity, but I'm not quite sure how this should be implemented. 

In addition, I think it should be possible to have your **squad page as the "homepage" in Backstage**, but I'm also not quite sure how that would be implemented.

## Alternatives

An alternative could be something like what is shown in the Backstage demo of the internal Spotify project - but I don't have any idea how that would be implemented.

![billede](https://user-images.githubusercontent.com/16527874/95060209-425e5080-06fa-11eb-845a-ac3b64768f82.png)

## Risks

It could be a problem if #1401 is solved in a way that does not recognize these demands/considerations.

**Comment by althafh** [comment]
+1 This would be a great addition. Some of my thoughts 

I agree you would want to re-use as much as possible with the Entity Catalog homepage and keep the concepts similar.

For customization, the entity page can be differentiated based on it's type or someone element of it's spec. (just like the service catalog entity page can show a different page based on the type of the component). If a group wants to customize it's own entity then it should define the page based on that new type. They can then define which tabs they want to appear as well as which widgets appear on the overview page. 
For e.g. A mobile team/squad is going to have a different page than a backend team or a product team is going to have a different page to an internal platform team. 
Reference implementation from the catalog: https://github.com/spotify/backstage/blob/master/packages/create-app/templates/default-app/packages/app/src/components/catalog/EntityPage.tsx#L125

**Comment by JacobValdemar** [comment]
@althafh That's actually a quite good idea for making it customizable, but I imagine that it would be hard to maintain if you had 50+ squads 🙂

**Comment by JacobValdemar** [comment]
Actually, I think I will try to make something like what's described, and I think it's possible with customization with the method @althafh described. :)

**Comment by stefanalund** [comment]
> If a group wants to customize it's own entity then it should define the page based on that new type. They can then define which tabs they want to appear as well as which widgets appear on the overview page.

FWIW this is a level of customisation I would not aim, at least not initially. Figuring out how to make this page customisable enough that it fits different companies adopting Backstage is, in my view, good enough for a first version. This is also in line with how the Overview pages are designed today. Our view has always been that the core Backstage experience is curated by a central ("platform") team, rather than different customer teams using Backstage having to configure it.

Something I would love your opinion on: how would a user find this page? Is it a separate menu item in the sidebar or perhaps something that takes over "home"? Moving [Services | Websites | ...] one step to the right is one option. Another option is that it's separate from the Backstage Software Catalog all together, thus leaving room for more dedicated tabs/views (as show in the example above).

Even though `Groups` are also entities in the Catalog, I don't think the UX necessarily has to be identical to `Components` (i.e. the Software Catalog). This opens up another question:

Should it be possible to find and visit other team's pages? If so, how?

**Comment by althafh** [comment]
> FWIW this is a level of customisation I would not aim, at least not initially. 

You are right, I wrote customize it's own entity, when I meant customize it's entity type page. i.e. every individual group shouldn't be able to customize it's individual page. 

>Something I would love your opinion on: how would a user find this page?

For the first version, I'm perfectly fine with just having Groups as another tab in between Documentation and Other as it stands currently. It muddies the line between Software Catalog and an Entity Catalog, but I think that's already done with documentation being there so I think it's fine.

> Should it be possible to find and visit other team's pages? If so, how?

While it would be possible to have permissions to restrict pages, I don't think that's necessary initially either. If we do follow the above method of having Groups discoverable through the Catalog search itself that's one way of finding the team page. Another way is via an owner or annotation [entity reference](https://backstage.io/docs/features/software-catalog/references). If the owner or an annotation is used and then referred to a Group Entity, that can then be linked to the Owner Page. 

```
# Example:
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  namespace: external-systems
  description: Petstore
spec:
  type: service
  lifecycle: experimental
  owner: group:pet-managers
```

With this example Service Component, in the Service Entity page, there can be a link to the Group Entity Page.

**Comment by freben** [comment]
> > Something I would love your opinion on: how would a user find this page?
> 
> For the first version, I'm perfectly fine with just having Groups as another tab in between Documentation and Other as it stands currently. It muddies the line between Software Catalog and an Entity Catalog, but I think that's already done with documentation being there so I think it's fine.

The catalog pages are currently explicitly limited to kind Component (the client filters it that way). We have this same discussion for other types of thing as well - where do you see the list of APIs? Of templates? Etc. We need to take some kind of greater stab at what we want the routing structure to look like for all of these kinds.

> > Should it be possible to find and visit other team's pages? If so, how?

Oh yes definitely! They should eventually be possible to find via search, and you should be able to see the owner on a component page and click it and get to that group page with more info about the team that owns it (full contact info, more things that they own, etc etc). I think this is an important part of the experience.

**Comment by JacobValdemar** [comment]
> how would a user find this page?

As a tab in the Catalog, as @althafh suggested, or like API Docs plugin explorer page:
![billede](https://user-images.githubusercontent.com/16527874/95082905-0d62f580-071c-11eb-9333-9c8066982217.png)

> Should it be possible to find and visit other team's pages? If so, how?
 
I don't think it's necessary to restrict that.

> this is a level of customisation I would not aim

That's completely ok! At Lunar it's a high demand feature so I think I'm going to make something to do it internally then 😉 I though about a solution with something like

```
export const EntityPage = () => {
  const { entity } = useEntity();
  switch (entity?.spec?.type) {
    case 'service':
      return <ServiceEntityPage entity={entity} />;
    case 'website':
      return <WebsiteEntityPage entity={entity} />;
    case 'squad':
      return <SquadEntityPage entity={entity} />;
    default:
      return <DefaultEntityPage entity={entity} />;
  }
};
```

```
const SquadEntityPage = ({ entity }: { entity: Entity }) => (
  <EntityPageLayout>
    <EntityPageLayout.Content
      path="/*"
      title="Overview"
      element={<SquadOverviewContent entity={entity} />}
    />
    <EntityPageLayout.Content
      path="/test/*"
      title="Test"
      element={<TestRouterThing entity={entity} />}
    />
  </EntityPageLayout>
);
```


```
const SquadOverviewContent = ({ entity }: { entity: Entity }) => (
  <Grid container spacing={3}>
    <Grid item md={6}>
       if entity?.spec?.overviewContent contains metrics
      <MetricsCard entity={entity} />
       if entity?.spec?.overviewContent contains httpErr
      <HttpErrCard entity={entity} endpoint={entity?.spec?.overviewContentDetails?.httpErr} />
    </Grid>
  </Grid>
);
```

```
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: The infra business unit
spec:
  type: business-unit
  parent: ops
  ancestors: [ops, global-synergies, acme-corp]
  children: [backstage, other]
  descendants: [backstage, other, team-a, team-b, team-c, team-d]
  overviewContent: [metrics, httpErr]
  overviewContentDetails:
    httpErr: "auth-endpoint"
```

Does that make sense? I don't think it's too complex 😁

**Comment by Fox32** [comment]
How would you decide which group page is displayed to a user if it was the home page? The current user/group model allows to be in multiple groups right? Maybe it could be an option on a team page to promote/star it to be the users home page. So he can choose himself.

**Comment by freben** [comment]
I would expect `/` to be different from `/group/one-of-my-groups`.

When visiting the first one, your mindset is "i want to have a bird's eye look of how all of the things that I am responsible for are doing" plus quick nav to favorites and recently visited and stuff like that. Bird's eye view of things that you care about.

The latter, will probably be a much more matter-of-factly "here's a presentation of this group, here's a list of all of the members of the group, and here's a list of stuff they own" (where the latter probably will be hidden in a subnav somewhere).

**Comment by stefanalund** [comment]
@JacobValdemar if you want to take a crack at this I think building it as a separate plugin is a good start. Once it is finalised we can figure out how to make it more integrated into the rest of the system.

**Comment by JacobValdemar** [comment]
@stefanalund I can do that  :)

**Comment by dtuite** [comment]
@JacobValdemar are you still working on this? We would like to pick it up if you don't have time. We will develop the plugin inside Backstage so happy to collab if you'd like? /cc @freben

**Comment by JacobValdemar** [comment]
Hi @dtuite, as I don't have much time for developing the plugin in the coming weeks, I'd happily welcome you to pick it up 🙂 We (@lunarway) would also be happy to come with some input on plugin here and there - just hit me up on discord 🙂

**Comment by freben** [comment]
@dtuite i assigned you then :)

**Comment by jlind23** [comment]
@dtuite Is there any progress made so far?

**Comment by dtuite** [comment]
Hi @jlind23 The team page now exists and shows the members of the team and the number of components they own. You can also traverse up and down through the heirarchy by clicking links. 

Further work should include the ability to aggregate KPIs on this page like internal Backstage does but I'm not aware of anyone working on that feature at the moment.

![Screenshot 2021-03-02 at 09 27 38](https://user-images.githubusercontent.com/562403/109631544-f47d3580-7b3d-11eb-97da-256c58ceb59c.png)

I believe this RFC has served it's purpose now and I will close it.

**Comment by jlind23** [comment]
Ownership summary is not clickable right? Fair enough if it's closed now.

**Comment by dtuite** [comment]
@jlind23 Not yet. It would totally make sense to have a separate GitHub issue for that though. This is just the RFC to get the page created so it could be considered a separate piece of work.
