### ISSUE TITLE
🚀 Feature: Capitalize Kind Facets in Catalog Table Title

### ISSUE THREAD

**Issue by tylerd-canva** [backstage/backstage#27631]
### 🔖 Feature description

Use the properly capitalized version of the entity Kind in the Catalog Table. This is what it *should* look like:

![mockup with capitalized Components title](https://github.com/user-attachments/assets/3525ae43-5681-48e8-9527-3236cd763fe4)

### 🎤 Context

Currently the default CatalogTable shows a dynamic title based on the Kind and Type filters. Kind is a special case because there is a properly capitalized version (eg `Component`) which shows up in the Filter/Picker but under the hood we use a lowercase version (eg `component`). Unfortunately the current title construction only has access to the filter value so you get the lowercase version in the title.

![existing behavior with lowercase components title](https://github.com/user-attachments/assets/2fa4f6e5-86f1-4f2f-b248-3fa686306259)

### ✌️ Possible Implementation

I tried two different approaches for this before opening this issue:
* https://github.com/backstage/backstage/pull/27590 adds a `label` attribute to the `EntityKindFilter` and then pulls that if it is set when constructing the table title.
* https://github.com/backstage/backstage/pull/27603 exports the `useAllKinds()` hook and uses that to retrieve the labels for a given Kind filter value when constructing the table title.

Both of them work functionally, but I think they both have similar issues at the React level (which I am far from an expert with) and both seem to have test-time issues which I haven't been able to fully resolve.

I am looking for advice on which of these two approaches is preferred, or if there is an even better third option (likely) that I haven't considered.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tylerd-canva** [comment]
Related question, is there ongoing work to change how the CatalogTable toolbar/search/title works as implied in this TODO?

https://github.com/backstage/backstage/blob/13180c52602fbd3c6c8a719711ddbf7fa35d52e2/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L174

cc @timbonicus

**Comment by vinzscam** [comment]
which version of Backstage are you using? It looks correct on demo.backstage.io

**Comment by tylerd-canva** [comment]
No, that page shows `All components (16)` -- it should be `All Components (16)` (note the capital `C`)

**Comment by tylerd-canva** [comment]
After discussing with a coworker who knows more about react, I've reworked my second approach into https://github.com/backstage/backstage/pull/27648 and have all the tests passing.

The only thing I'm concerned about is a visible re-render on the CatalogTable, but I can see this on `master` with no changes as well so I don't think I've broken anything.

**Comment by tylerd-canva** [comment]
Looks like the `APIS`/`APIs` issue is well known in the pluralize library: https://github.com/plurals/pluralize/issues/127

**Comment by vinzscam** [comment]
Thanks for the suggestion @tylerd-canva 🙏
Could you share more about the reasoning for why it should be capitalized?

**Comment by tylerd-canva** [comment]
It's capitalized everywhere else in the UI, including in the Kind picker/filter visible on the same page. Mostly it just looks bad without the capitalization. `components` is an innocent example but we have a few more custom Kinds in my org, for example `UserOperation` and `UserFlow`. `useroperation` and `userflow` looks WAY worse in comparison.
