### ISSUE TITLE
🐛 Bug Report: @techdocs/cli Error: Config file 'mkdocs.yml' does not exist

### ISSUE THREAD

**Issue by mycodeself** [backstage/backstage#27730]
### 📜 Description

Hey, 

today all my CI systems that generate documentation started to fail with `Failed to generate docs from /dir into /dir/site; caused by Error: Docker container returned a non-zero exit code (1)`

After that, I pulled one project and tried to generate the documentation and it worked successfully, the documentation was generated, so I started to get crazy 😄.

In my pipelines the latest version of `@techdocs/cli` is always installed with `npm` (no version pinning), so I upgraded my local installation `@techdocs/cli` version and tried to generate the documentation, **it didn't work**!. 

Using verbose mode the error was:

```bash
verbose: Error: Config file 'mkdocs.yml' does not exist.
```

What is even more strange and confuses me a lot is that I tried to install an older version of `@techdocs/cli`, in fact I tried with the latest five versions, including 1.7.0... and still doesn't work... same in my CI trying with previous versions 😕

Is someone having similar issues after upgrade to `@techdocs/cli@1.8.22`?

### 👍 Expected behavior

`techdocs-cli generate` command must generate the static site documentation properly, finding the `mkdocs.yml` file 

### 👎 Actual Behavior with Screenshots

`techdocs-cli generate` command gives an error `verbose: Error: Config file 'mkdocs.yml' does not exist.`

![image](https://github.com/user-attachments/assets/93e46a0e-da75-4f1f-8d59-1feca4651092)

### 👟 Reproduction steps

Install latest version of `@techdocs/cli`

```bash
npm install -g @techdocs/cli
```

Create new docs project

```bash
mkdir -p test-docs/docs
cd test-docs
cat "# hello world" > docs/index.md
touch mkdocs.yml
```

Add this content to the `mkdocs.yml` file

```yaml
site_name: Documentation Site
docs_dir: docs

nav:
  - Home: index.md

plugins:
  - techdocs-core
```

Run

```bash
techdocs/cli generate
```

### 📃 Provide the context for the Bug.

Yesterday this was working properly, today a colleague did a commit with a small doc change and it doesn't work anymore.

I tried with previous versions and it doesn't work either, I also tried to create a new empty project and I get the same result... even though the `mkdocs.yml` file is generated by the `generate` command itself it doesn't find it.

### 🖥️ Your Environment

- Ubuntu 22.04
- @techdocs-cli 1.8.22
- Node 20.14

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by rofafor** [comment]
I'm experiencing the same issue. I've tested with newer and older version, but no luck. All these combinations fails.
```
npx --yes @techdocs/cli@v1.8.22 generate -v
npx --yes @techdocs/cli@v1.8.20 generate -v
npx --yes @techdocs/cli generate -v --docker-image=spotify/techdocs:latest
npx --yes @techdocs/cli generate -v --docker-image=spotify/techdocs:1.2.5
```

```
info: Using source dir /xyz
info: Will output generated files in /xyz/site
verbose: Creating output directory if it does not exist.
info: Generating documentation...
verbose: {"status":"Pulling from spotify/techdocs","id":"v1.2.4"}
verbose: {"status":"Digest: sha256:bf9ca0f99d4e19e826bc6be4541ff062b11ecae40a99d056cac03f0cecdc1f24"}
verbose: {"status":"Status: Image is up to date for spotify/techdocs:v1.2.4"}
verbose: Error: Config file 'mkdocs.yml' does not exist.
Failed to generate docs from /xyz into /xyz/site; caused by Error: Docker container returned a non-zero exit code (1)
```

**Comment by rofafor** [comment]
Defined my own debug image via `--docker-image` and inspecting the container gives these results, i.e. mounts are missing:
```
        "Mounts": [],
        "Config": {
            "Env": [
                "HOME=/tmp",
            ],
            "Cmd": [
                "build",
                "-d",
                "/output"
            ],
            "Volumes": null,
            "WorkingDir": "/input",
        },
```

**Comment by KrishanNagarro** [comment]
I am also facing this issue. Any workaround for the same?

**Comment by benjdlambert** [comment]
@backstage/techdocs-maintainers can you take a look at this? :pray:

**Comment by iamEAP** [comment]
Pretty sure this is related to #27755

**Comment by benjdlambert** [comment]
Yep looks like it @iamEAP, I was just coming here to write the same thing :joy:

**Comment by benjdlambert** [comment]
Should be fixed with the patch that's going out :)

**Comment by mycodeself** [comment]
I can confirm that my pipelines are working properly again today and the docs are generated without any problem! 🎉 

great job guys!

**Comment by ajac-zero** [comment]
I am battling with this issue on v1.10.0. Is there a known fix?
