### ISSUE TITLE
🐛 Bug Report: Module not found error related to swagger-api

### ISSUE THREAD

**Issue by singhswg** [backstage/backstage#27774]
### 📜 Description

I have followed the steps laid out in https://backstage.io/docs/getting-started/ and installed all dependencies. 

`npx @backstage/create-app@latest` finishes succesfully as shown. 

When i test the app locally and run `yarn dev`, I keep getting the error - 

```
Module not found: Can't resolve '@swagger-api/apidom-json-pointer' in '.../backstage-app/node_modules/@swagger-api/apidom-ns-openapi-3-1/src/refractor'
node_modules/@swagger-api/apidom-ns-openapi-3-1/src/refractor/toolbox.mjs
```

I am using node v20 on a MacOS.

### 👍 Expected behavior

App should run on port 3000 locally

### 👎 Actual Behavior with Screenshots

Noticing backend errors - 

```
[backend]: 2024-11-21T21:31:12.359Z search info Collating documents for techdocs succeeded documentType=techdocs
[backend]: 2024-11-21T21:31:12.367Z search info Collating documents for software-catalog succeeded documentType=software-catalog
[app]: ERROR in ../../node_modules/@swagger-api/apidom-ns-openapi-3-1/src/refractor/toolbox.mjs 2:0-87
[app]: Module not found: Error: Can't resolve '@swagger-api/apidom-json-pointer' in '.../backstage-app/node_modules/@swagger-api/apidom-ns-openapi-3-1/src/refractor'
[app]: 
[app]: ERROR in ../../node_modules/@swagger-api/apidom-reference/es/dereference/strategies/openapi-3-1/selectors/uri.mjs 4:0-97
[app]: Module not found: Error: Can't resolve '@swagger-api/apidom-json-pointer' in '.../backstage-app/node_modules/@swagger-api/apidom-reference/es/dereference/strategies/openapi-3-1/selectors'
[app]: 
[app]: ERROR in ../../node_modules/@swagger-api/apidom-reference/es/dereference/strategies/openapi-3-1/visitor.mjs 5:0-97
[app]: Module not found: Error: Can't resolve '@swagger-api/apidom-json-pointer' in '.../backstage-k8s/backstage-app/node_modules/@swagger-api/apidom-reference/es/dereference/strategies/openapi-3-1'
[app]: 
[app]: webpack compiled with 3 errors
```

### 👟 Reproduction steps

Install  via `npx @backstage/create-app@latest` and then run `yarn dev`

### 🖥️ Your Environment

MacOS and node v20

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by singhswg** [comment]
Had to add `"@swagger-api/apidom-json-pointer": "0.99.1"` in package.json and then run `yarn install` to fix the issue

**Comment by Damounet** [comment]
It is related to this : https://github.com/swagger-api/apidom/issues/4539

So I think we might wait for backstage next release (either 1.32.5 or 1.33) so that they increase swagger-api version accordingly to prevent us to add the lib as you did.

I don't want to have to handle this lib versioning on my part as Backstage will handle it properly, but as a workaround, it may be fine :)
