### ISSUE TITLE
🐛 Bug Report: Error related to '@swagger-api/apidom-json-pointer' in npx @backstage/create-app@latest

### ISSUE THREAD

**Issue by Sir-gits-a-lot** [backstage/backstage#27780]
### 📜 Description

I am trying out the backstage getting started tutorial but it seems to throw 3 errors related to '@swagger-api/apidom-json-pointer' for the frontend app.

### 👍 Expected behavior

npx @backstage/create-app@latest should successfully bootstrap backstage and yarn dev should compile and run it.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/de7ea2d5-0039-450c-ba56-e8da360dffa4)

### 👟 Reproduction steps

Just following the backstage getting started tutorial from https://backstage.io/docs/getting-started/. I tried in WSL linux machine as well as codespace linux machine but in both the environments, it throws the same error. 

### 📃 Provide the context for the Bug.

ERROR in ../../node_modules/@swagger-api/apidom-ns-openapi-3-1/src/refractor/toolbox.mjs 2:0-87
[app]: Module not found: Error: Can't resolve '@swagger-api/apidom-json-pointer' in '/home/sre/idp/dev-portal/node_modules/@swagger-api/apidom-ns-openapi-3-1/src/refractor'
[app]: 
[app]: ERROR in ../../node_modules/@swagger-api/apidom-reference/es/dereference/strategies/openapi-3-1/selectors/uri.mjs 4:0-97
[app]: Module not found: Error: Can't resolve '@swagger-api/apidom-json-pointer' in '/home/sre/idp/dev-portal/node_modules/@swagger-api/apidom-reference/es/dereference/strategies/openapi-3-1/selectors'
[app]: 
[app]: ERROR in ../../node_modules/@swagger-api/apidom-reference/es/dereference/strategies/openapi-3-1/visitor.mjs 5:0-97
[app]: Module not found: Error: Can't resolve '@swagger-api/apidom-json-pointer' in '/home/sre/idp/dev-portal/node_modules/@swagger-api/apidom-reference/es/dereference/strategies/openapi-3-1'
[app]: 
[app]: webpack compiled with 3 errors

### 🖥️ Your Environment

OS:   Linux 5.15.167.4-microsoft-standard-WSL2 - linux/x64
node: v22.11.0
yarn: 4.4.1
cli:  0.29.2 (installed)
backstage:  1.33.0

Dependencies:
  @backstage/app-defaults                                          1.5.14
  @backstage/backend-app-api                                       1.0.2
  @backstage/backend-common                                        0.25.0
  @backstage/backend-defaults                                      0.5.3
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.3.0
  @backstage/backend-plugin-api                                    1.0.2
  @backstage/catalog-client                                        1.8.0
  @backstage/catalog-model                                         1.7.1
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.10
  @backstage/cli                                                   0.29.2
  @backstage/config-loader                                         1.9.2
  @backstage/config                                                1.3.0
  @backstage/core-app-api                                          1.15.2
  @backstage/core-compat-api                                       0.3.3
  @backstage/core-components                                       0.16.1
  @backstage/core-plugin-api                                       1.10.1
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.5
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.2
  @backstage/frontend-defaults                                     0.1.3
  @backstage/frontend-plugin-api                                   0.9.2
  @backstage/frontend-test-utils                                   0.2.3
  @backstage/integration-aws-node                                  0.1.13
  @backstage/integration-react                                     1.2.1
  @backstage/integration                                           1.15.2
  @backstage/plugin-api-docs                                       0.12.1
  @backstage/plugin-app-backend                                    0.4.2
  @backstage/plugin-app-node                                       0.1.27
  @backstage/plugin-app                                            0.1.3
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.2
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.2
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.3.0
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.2
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.2
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.2
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.2
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.2
  @backstage/plugin-auth-backend-module-github-provider            0.2.2
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.2
  @backstage/plugin-auth-backend-module-google-provider            0.2.2
  @backstage/plugin-auth-backend-module-guest-provider             0.2.2
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.2
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.2
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.2
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.2
  @backstage/plugin-auth-backend-module-okta-provider              0.1.2
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.2
  @backstage/plugin-auth-backend                                   0.24.0
  @backstage/plugin-auth-node                                      0.5.4
  @backstage/plugin-auth-react                                     0.1.9
  @backstage/plugin-bitbucket-cloud-common                         0.2.25
  @backstage/plugin-catalog-backend-module-logs                    0.1.4
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.2
  @backstage/plugin-catalog-backend                                1.28.0
  @backstage/plugin-catalog-common                                 1.1.1
  @backstage/plugin-catalog-graph                                  0.4.13
  @backstage/plugin-catalog-import                                 0.12.7
  @backstage/plugin-catalog-node                                   1.14.0
  @backstage/plugin-catalog-react                                  1.14.2
  @backstage/plugin-catalog                                        1.25.1
  @backstage/plugin-events-node                                    0.4.5
  @backstage/plugin-kubernetes-backend                             0.19.0
  @backstage/plugin-kubernetes-common                              0.9.0
  @backstage/plugin-kubernetes-node                                0.2.0
  @backstage/plugin-kubernetes-react                               0.5.1
  @backstage/plugin-kubernetes                                     0.12.1
  @backstage/plugin-org                                            0.6.33
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.2
  @backstage/plugin-permission-backend                             0.5.51
  @backstage/plugin-permission-common                              0.8.2
  @backstage/plugin-permission-node                                0.8.5
  @backstage/plugin-permission-react                               0.4.28
  @backstage/plugin-proxy-backend                                  0.5.8
  @backstage/plugin-scaffolder-backend-module-azure                0.2.2
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.2
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.2
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.3
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.2
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.2
  @backstage/plugin-scaffolder-backend-module-github               0.5.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.6.1
  @backstage/plugin-scaffolder-backend                             1.27.1
  @backstage/plugin-scaffolder-common                              1.5.7
  @backstage/plugin-scaffolder-node                                0.6.0
  @backstage/plugin-scaffolder-react                               1.14.1
  @backstage/plugin-scaffolder                                     1.27.1
  @backstage/plugin-search-backend-module-catalog                  0.2.5
  @backstage/plugin-search-backend-module-pg                       0.5.38
  @backstage/plugin-search-backend-module-techdocs                 0.3.3
  @backstage/plugin-search-backend-node                            1.3.5
  @backstage/plugin-search-backend                                 1.7.0
  @backstage/plugin-search-common                                  1.2.15
  @backstage/plugin-search-react                                   1.8.3
  @backstage/plugin-search                                         1.4.20
  @backstage/plugin-signals-react                                  0.0.7
  @backstage/plugin-techdocs-backend                               1.11.3
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.18
  @backstage/plugin-techdocs-node                                  1.12.14
  @backstage/plugin-techdocs-react                                 1.2.11
  @backstage/plugin-techdocs                                       1.11.2
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.16
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.7.2
  @backstage/theme                                                 0.6.2
  @backstage/types                                                 1.2.0
  @backstage/version-bridge                                        1.0.10

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jonshilton** [comment]
I'm also getting this issue this morning. Not looked into it too much just yet but @swagger-api published version 1.0.0-beta.0 of their packages yesterday which is causing the issue.

Although not a fix, as a temporary workaround you could update `resolutions` in package.json to lock to the previous versions:

```
"resolutions": {
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@swagger-api/apidom-ast": "1.0.0-alpha.10",
    "@swagger-api/apidom-ns-openapi-3-0": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-openapi-json-3-1": "1.0.0-alpha.10",
    "@swagger-api/apidom-core": "1.0.0-alpha.10",
    "@swagger-api/apidom-ns-openapi-3-1": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-openapi-yaml-2": "1.0.0-alpha.10",
    "@swagger-api/apidom-error": "1.0.0-alpha.10",
    "@swagger-api/apidom-ns-workflows-1": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-openapi-yaml-3-0": "1.0.0-alpha.10",
    "@swagger-api/apidom-json-pointer": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-api-design-systems-json": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-openapi-yaml-3-1": "1.0.0-alpha.10",
    "@swagger-api/apidom-ns-api-design-systems": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-api-design-systems-yaml": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-workflows-json-1": "1.0.0-alpha.10",
    "@swagger-api/apidom-ns-asyncapi-2": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-asyncapi-json-2": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-workflows-yaml-1": "1.0.0-alpha.10",
    "@swagger-api/apidom-ns-json-schema-draft-4": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-asyncapi-yaml-2": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-yaml-1-2": "1.0.0-alpha.10",
    "@swagger-api/apidom-ns-json-schema-draft-6": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-json": "1.0.0-alpha.10",
    "@swagger-api/apidom-reference": "1.0.0-alpha.10",
    "@swagger-api/apidom-ns-json-schema-draft-7": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-openapi-json-2": "1.0.0-alpha.10",
    "@swagger-api/apidom-ns-openapi-2": "1.0.0-alpha.10",
    "@swagger-api/apidom-parser-adapter-openapi-json-3-0": "1.0.0-alpha.10"
  },
```

This seems to give me an error-free build for now until a proper fix can be put in place.

**Comment by benjdlambert** [comment]
I made this upstream too: https://github.com/swagger-api/apidom/issues/4539

**Comment by Sir-gits-a-lot** [comment]
Thanks @jonshilton. Been scratching my head over this for a while thinking upstream backstage cannot have a bug. But good to know someone else is also facing similar issues. Will try out the resolution you suggested and let u know.

**Comment by Sir-gits-a-lot** [comment]
Updating the resolutions in package.json worked like a charm. Thanks for the help.

**Comment by Sir-gits-a-lot** [comment]
Keeping this issue to see if there a scope for resolution.

**Comment by benjdlambert** [comment]
Looks like this has been fixed in the upstream package. Should be able to remove the resolutions now.
