### ISSUE TITLE
Plugin Configuration

### ISSUE THREAD

**Issue by tarcinil** [backstage/backstage#278]
Much like #138, it would also be nice to be able to spinkle plugin configuration.

I am thinking of creating a new plugin and it would be nice to have the ability to configure things specific to the plugin, rather than entirely in the component. 

```
let Foo: { environment: string, url: string }[] = [
  { "environment": 'test', "url": "localhost:3000" },
  { "environment": 'stage', "url": "localhost:3001" },
];
```

Possibly under the `createPlugin`

EDIT:
Expanded idea: it would also be nice if I can added to SidebarItem from the config as well.

**Comment by Rugvip** [comment]
Completely agree that we need something here.

From a related discussion on discord:

> ... we might use something similar for configuring plugins, but it depends a bit on where we go with the plugin API. One idea is that a plugin would announce that they depend on a config object registered as for example "foo.bar", and the app would register a configuration for that name.

**Comment by mikerhyssmith** [comment]
Just came across this when looking for a way of passing environment variables for different URLS to a plugin.

Would be happy to help out with this if there are any implementation ideas 🙂

**Comment by Rugvip** [comment]
[This](https://github.com/spotify/backstage/blob/691616efe1d71596506d971a5bf96ec59b4fdcf0/packages/app/src/apis.ts#L39) is the recommended solution for this atm.

Use `process.env.NODE_ENV` checks inside `apis.ts` if you want different config for dev/prod. We'll likely bring in an `env` API soon that makes that a bit simpler.

Then we'll likely continue exploring ways of supplying plugin config as we look closer at how to tie in backends.

Ideas are still very welcome though!

**Comment by adamdmharvey** [comment]
I believe the root of this issue has been resolved, and is described here:
https://backstage.io/docs/conf/defining

Plugins can define a config schema, validate against it, and allow users to configure settings via the app-config.yaml.

Would others agree?  Possibly good to close.

**Comment by OrkoHunter** [comment]
🧹 🧹 🧹 🧹
