### ISSUE TITLE
Investigate in how we can add vale linter quality checks to all docs components created through backstage

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#2780]
With the great contribution from @Marvin9 [to add vale linter to check words quality in markdown files](https://github.com/spotify/backstage/pull/2631) in the Backstage repo we now want this to be added to all components that are created through Backstage docs-template. 

Use Case:
If I create a new component through the `Documentation Template`(see screen shot) I would like to get vale linter set up by default. 
<img width="1440" alt="Screen Shot 2020-09-15 at 8 17 29 PM" src="https://user-images.githubusercontent.com/25153114/95307387-d9591300-0888-11eb-80c6-86165a4a8ee9.png">

**Comment by Marvin9** [comment]
Waiting for vale author's response on this [issue](https://github.com/errata-ai/vale/issues/243) to make integration easier.

**Comment by emmaindal** [comment]
Hey @Marvin9 just wanted to jump in here and see status on this issue? Are you planning to work on this? 🎉

**Comment by Marvin9** [comment]
Yes. I'll work on this soon.

**Comment by OrkoHunter** [comment]
Based on our experience with Vale in Backstage mono-repo, adding Vale automatically to a new project can cause friction. Not being able to commit without the vocabulary list in `.github/styles/vocab.txt`, setting up pre-commit hook correctly, etc. can be cumbersome and hence not worth investigating more. Closing this issue as we don't want to do this on component creation.

However, we can have Tech Writing resources/docs on recommending writers to setup tools like Vale, https://prowritingaid.com, etc.
