### ISSUE TITLE
🐛 Bug Report: Latest spectral-core dependency has very specific node version requirements

### ISSUE THREAD

**Issue by jslott2sigma** [backstage/backstage#27819]
### 📜 Description

In Backstage 1.33.4, the `@stoplight/spectral-core` dependency version (1.18.0) has a very specific set of node versions it wants. From [this PR in their repo](https://github.com/stoplightio/spectral/pull/2724/files), the aim to remove support for node 12/14 resulted in the following required node version:
```
"node": "^16.20 || ^18.18 || >= 20.17"
```
If we do not have those specific versions, a `yarn versions:bump` will fail.
```
error @stoplight/spectral-core@1.19.4: The engine "node" is incompatible with this module. Expected version "^16.20 || ^18.18 || >= 20.17". Got "20.14.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### 👍 Expected behavior

Yarn should succeed with the same allowable versions of node that Backstage requires

### 👎 Actual Behavior with Screenshots

If we do not have those specific versions, a `yarn versions:bump` will fail.
```
error @stoplight/spectral-core@1.19.4: The engine "node" is incompatible with this module. Expected version "^16.20 || ^18.18 || >= 20.17". Got "20.14.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### 👟 Reproduction steps

Run `yarn versions:bump` while having an earlier version of node installed (in my case node 20.14).

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jslott2sigma** [comment]
For now, I'm going to try `resolutions` in my `package.json` to use an older version of spectral-core to see if that solves the problem.

**Comment by Rugvip** [comment]
@jslott2sigma are you able to move to a more recent minor release of Node.js v20? We also generally expect that a fairly recent minor release of each major release is being used. Current minor is `.18` though, so `>= .17` is quite strict.

**Comment by jslott2sigma** [comment]
@Rugvip Yes, we are able to move to the latest node 20 release but I also tested a workaround using `resolutions` as follows that fixed the problem too that pins to versions of spectral without the specific node 20 requirement:
```
    "resolutions": {
        "@stoplight/spectral-core": "1.18.3",
        "@stoplight/spectral-formats": "1.6.0",
        "@stoplight/spectral-formatters": "1.3.0",
        "@stoplight/spectral-functions": "1.7.2",
        "@stoplight/spectral-parsers": "1.0.3",
        "@stoplight/spectral-rulesets": "1.18.1",
        "@stoplight/spectral-runtime": "1.1.2",
    },
```
Feel free to close this issue -- or perhaps leave it open if it reminds us to upgrade to the latest Spectral when they address the issue, which agreed is the proper fix.
