### ISSUE TITLE
🐛 Bug Report:  @visibility modifier not working for frontend code with yarn dev

### ISSUE THREAD

**Issue by deejay1** [backstage/backstage#27871]
### 📜 Description

I have a custom config for a plugin, with the config.d.ts added to package.json as per docs.
When running backstage-cli config:print --frontend it can see the fields market with @visibility frontend, unfortunately when accessing it through another plugin it is in the filteredKeys section

The config file is as follows:
```typescript
export interface Config {
myPlugin: {
    /**
     * @visibility frontend
     */
    providers: Array<{
       /**
       * @visibility frontend
       */
      name: string;
     }>;
}}
```

plugin definition:
```typescript
export const myPlugin = createPlugin({
  id: 'my-plugin',
  routes: {
    root: rootRouteRef,
  },
  apis: [
    createApiFactory({
      api: myJobApiRef,
      deps: {
        discoveryApi: discoveryApiRef,
        identityApi: identityApiRef,
        configApi: configApiRef,
        alertApi: alertApiRef,
      },
      factory: ({ discoveryApi, identityApi, configApi, alertApi }) => {
        return new JobApiClient({
          discoveryApi,
          identityApi,
          configApi,
          alertApi,
        });
      },
    }),
]})
```

```json title='package.json'
  "files": [
    "dist",
    "config.d.ts"
  ],
  "configSchema": "config.d.ts"
```

I'm trying to access the config inside JobApiClient it seems like the config is being fetched fine, but the visibility modifiers arent applied properly there

Backstage version 1.32.3 EDIT: Also affects 1.33.4

### 👍 Expected behavior

Config is visible to frontend

### 👎 Actual Behavior with Screenshots

Content not visibl;e

### 👟 Reproduction steps

1. Create a custom plugin
2. Create a config file and add it to `packages.json`
3. Add `@visibility frontend` annotation to config variable
4. Try to access is inside plugin code

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Not able to reproduce this, followed your steps and tried with the following config:

```yaml
myPlugin:
  providers:
  - name: 'a'
  - name: 'b'
```

Config is showing up alright in the frontend in a new app created from the `1.33.4` release

**Comment by deejay1** [comment]
@Rugvip hmm, I recreated it in a separate repo https://github.com/deejay1/backstage_config_issue
Url:  `http://localhost:3000/myotherplugin` config should be visible in console.

Maybe the problem here is that the config is exposed  in a backend plugin and I'm trying to access it from another plugin?

**Comment by Rugvip** [comment]
@deejay1 [this](https://github.com/deejay1/backstage_config_issue/blob/804935701086bea8f156f0fabe259d8d670451b6/plugins/myotherplugin/src/api/myapi.ts#L18) line will not necessarily log all config, try switching it out for a `configApi.get()`

**Comment by deejay1** [comment]
OK, seems like to have access to the configuration from `pluginA` in `pluginB` I have to add `pluginA` to the dependencies list.

**Comment by freben** [comment]
Yes, since the only way of getting a config key into the frontend is for it to have a config schema key with the right visibility. And the schemas are "discovered" dynamically based on what you install.

**Comment by freben** [comment]
That being said, it's an antipattern to have plugins access each other's config. So beware.
