### ISSUE TITLE
Unable to create Web App from Template & Unable to select any text

### ISSUE THREAD

**Issue by blueelvis** [backstage/backstage#2788]
## Expected Behavior
So, I got the backstage working locally with the UI, Backend and Auth working on my Windows machine with Docker installed. I am trying to work on the Lighthouse plugin and hence have a Spotify Lighthouse CI server running on minikube.

1. I expect that when I create a Website from the template, it should create it.
2. I should be able to select and copy-paste the logs which are generated while the scaffolding is running.

## Current Behavior
1. When the template is running, I get the following error -
```
{"status":"Extracting","progressDetail":{"current":283,"total":283},"progress":"[==================================================\u003e]     283B/283B","id":"22e94daf4797"}
...
{"status":"Status: Downloaded newer image for node:lts-alpine"}
: Stage failed with error: process.getuid is not a function {"id":"af78c31a-0820-46ab-bb3d-4ce60c9d33ac","stage":"Run the templater","timestamp":"2020-10-07T18:27:02.805Z"}
```
2. When I try to select the text in the logs, I am unable to select the text inside the logs section.
![image](https://user-images.githubusercontent.com/6985763/95375082-c2ec9f00-08fc-11eb-86c4-09aaf11857af.png)

## Possible Solution
1. Add to the instructions if it is possible to build and run from Windows.
2. Use an alternative to `process.getuid`
3. Disabling the highlighted CSS enables the selection and copy pasting of text.
![image](https://user-images.githubusercontent.com/6985763/95375906-ed8b2780-08fd-11eb-98c2-292a37d0a59a.png)

## Steps to Reproduce

1. Clone Backstage on Windows with Docker running.
2. Run backend and frontend on Windows in separate command line terminals.
3. Once the frontend is online, try creating a new Website from the service catalog and wait for provisioning. It will error out.

## Context
1. I am trying to resolve the issue over here - https://github.com/spotify/backstage/issues/2740
2. Unable to copy paste logs is an issue.
3. I have configured the Lighthouse plugin to run with a spotify lighthouse ci server on minikube. The Lighthouse results are showing up properly.

## Your Environment

- NodeJS Version (v12): v12.18.4
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 Enterprise Version	10.0.18363 Build 18363
- Browser Information: Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by benjdlambert** [comment]
OK - This looks like an issue that `process.getuid` is not available on windows.

I think that we can skip adding this stuff to the docker run command if you're running on windows. Do you wanna pick this up @blueelvis?

**Comment by StefanoVuerich** [comment]
Any news on this. Seems impossibile to create a new component using Windows environment.

**Comment by benjdlambert** [comment]
@StefanoVuerich do you wanna pick this up? I think it's just a case of removing the `process.getuid` calls on windows?

**Comment by StefanoVuerich** [comment]
Yes, sure

**Comment by StefanoVuerich** [comment]
@benjdlambert I'm ready with the fix, could you give me permission to push new branch?

**Comment by benjdlambert** [comment]
I think if you fork the project and push to your fork you should be able to open a pull request that way instead.

**Comment by StefanoVuerich** [comment]
@benjaminr https://github.com/backstage/backstage/pull/3325
