### ISSUE TITLE
🐛 Bug Report: Catalog won't start due to TypeError: meter.createGauge is not a function (v1.34.0-next.1)

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#27992]
### 📜 Description

We upgraded the Demo site to the latest next version - `v1.34.0-next.1` - and now it isn't starting up. After running the code locally we noticed the following error during the start up of the backend:

```text
Error: Failed to instantiate service 'core.scheduler' for 'catalog' because the factory function threw an error, TypeError: meter.createGauge is not a function
```

### 👍 Expected behavior

The backend should start up as expected.

### 👎 Actual Behavior with Screenshots

The backend does not start up and we get the following error:

```text
Error: Failed to instantiate service 'core.scheduler' for 'catalog' because the factory function threw an error, TypeError: meter.createGauge is not a function
```

### 👟 Reproduction steps

Pull down the latest code from the Demo site and run `yarn dev` you'll get the error right away.

### 📃 Provide the context for the Bug.

This is preventing us from deploying the latest next version - `v1.34.0-next.1` - of the Demo site and it's currently crashing.

### 🖥️ Your Environment

This is specifically a regression in `v1.34.0-next.1`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Closing as duplicate of as I didn't think they were related initially: https://github.com/backstage/backstage/issues/27979

**Comment by awanlin** [comment]
This will be fixe din the next, next release, workaround for now is to add a resolution like this: `@opentelemetry/api": "1.9.0"`

**Comment by aarti-pandya-2025** [comment]
@awanlin while upgrading to v1.35 , iam getting the error. Can you specify in which package.json we need to add this package. I have added in main package.json plus frontend and backend as well.

**Comment by awanlin** [comment]
You should not need to make any changes as it was fixed in the follow up next release and is part of the `1.34.0` release. Perhaps you have some existing resolutions causing you issues or duplicates in your lock file causing problems.
