### ISSUE TITLE
🐛 Bug Report: UserProfile info is not being returned from identityApi

### ISSUE THREAD

**Issue by ankitapandey1106** [backstage/backstage#28010]
### 📜 Description

We are trying to upgrade from `1.20` to `1.31` with our own customizations in different plugins, one of them is `Scaffolder`, and we have created a custom picker called `LoggedInUserPicker` where we fetch user email from `IdentityApi`, it used to work fine before the upgrade but not anymore, what are we missing here, please?

```ts
const state = await identityApi.getProfileInfo();
```
we used to fetch email from state but this is now null.

Strangely the same code works when I login on local development with guest and `dangerouslyDisabled` true for auth.

### 👍 Expected behavior

User info should be available in `Scaffolder` template.

### 👎 Actual Behavior with Screenshots

NA

### 👟 Reproduction steps

It's a custom use of `Scaffolder` template to fetch logged in user email.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ankitapandey1106** [comment]
Hi @freben  any inputs would be helpful please

**Comment by camilaibs** [comment]
Hi @ankitapandey1106 👋🏻, 
Could you please share with us what the backend response looks like? We would also like to know if the email is in the sign-in resolver and profile transformer.

**Comment by ankitapandey1106** [comment]
Hi @camilaibs sorry I missed your response, this issue is sorted now. thank you!
