### ISSUE TITLE
🚀 Feature: Can the Catalog Import Plugin wizard use JSON files rather than YAML files to register new components? 

### ISSUE THREAD

**Issue by jesus-vc** [backstage/backstage#28115]
### 🔖 Feature description

Hello there! Please let me know if this issue falls under a category other than 'feature'.

Has anyone tried enabling the Backstage frontend to process descriptor files with extensions other than .yaml, such as .json?

In our case, we’re exploring ways to customize Backstage to handle existing package.json files from our GitHub repositories instead of the default catalog.yaml files. On the backend, we’ve implemented a custom CatalogProcessorParser that successfully processes package.json files into Entity objects.

However, we’ve encountered an issue on the frontend.

Based on the source code of the Catalog Import Plugin wizard, it appears that the wizard only supports URLs with pathnames ending in .yaml or those containing a path parameter with a value matching yaml. This behavior is evident in lines 64-65 in the source code: https://github.com/backstage/backstage/blob/657193572813af9bed3e55248b2c10f105068fe9/plugins/catalog-import/src/api/CatalogImportClient.ts#L65. 

For context, I’ve attached a screenshot showing how we currently append the URL with ?path=catalog.yaml to trick the wizard into processing our package.json file instead of a .yaml file.

Does anyone know how to modify the wizard to process non-.yaml files directly, without relying on the path parameter workaround? Or would this require submitting a feature request?

Any ideas would be appreciated. If indeed this is a limitation of the wizard, perhaps another option is to remove the wizard from the frontend and leverage Software Templates instead where we have greater control of the URLs inputted by users. 

### 🎤 Context

It would allow organizations to ingest entities using JSON files rather than solely YAML.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
Hi @jesus-vc, was the a reason you opened a new issue over just following up on the previous issue you logged about this? https://github.com/backstage/backstage/issues/27773

That would help keep on the conversation in one place and avoid duplication.

**Comment by jesus-vc** [comment]
Yes, thank you, awanli! Apologies!
