### ISSUE TITLE
🚀 Feature: Subscribe user to newly created GitHub repository in action

### ISSUE THREAD

**Issue by jsundquist** [backstage/backstage#28123]
### 🔖 Feature description

Subscribe users to a newly created repository using the `publish:github` action.

### 🎤 Context

Currently when a user uses the scaffolder that calls `publish:github` it will create the new repository for the user, however it does not automatically subscribe the user to the new repository similar to how GitHub does when creating a new repository. In order to ensure that users have the same experience when creating a repository via the scaffolder action or GitHub UI, they should be subscribed by default.

### ✌️ Possible Implementation

It would be possible to extend `publish:github` to call an additional end point as all of the information necessary is already available within the action request. Additionally, could create a new action which could do the subscription request as well. The preferred method would be to use `publish:github`.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Ah, sure. Yeah feel free to make a PR for that! 🙏
