### ISSUE TITLE
🐛 Bug Report: <Geeting build error while trying to use an apiref in a backend module >

### ISSUE THREAD

**Issue by ankitapandey1106** [backstage/backstage#28131]
### 📜 Description

Hi Team, so we are in the process of upgrading to version 1.31 from 1.20.
We have a scaffolder backend module extension - 

```ts
/**
 * @public
 * The feedback Module for the Scaffolder Backend
 */
export const feedbackModule = createBackendModule({
  pluginId: 'scaffolder',
  moduleId: 'feedbackModule',
  register({ registerInit }) {
    registerInit({
      deps: {
        scaffolder: scaffolderActionsExtensionPoint,
        config: coreServices.rootConfig,
        auth: coreServices.auth,
        feedback: feedbackServiceRef,
      },
      async init({ scaffolder, config, feedback, auth }) {
        scaffolder.addActions(
          **feedbackCreateAction(feedback, config, auth),
         feedbackEntityCreateAction(feedback, config, auth),**
        );
      },
    });
  },
});
```

we rare trying to call apis of "feedback plugin from the customs actions here, highlighted in bold. I did try a couple of combinations but all unsuccessful.

So our current "feedback" plugin structure is - "feedback", "feedback-backend" abd "feedback-client"
the "feedback-client" folder has a FeedbackClient.ys and a FeedbackService.ts and api.ts containing "export interface FeedbackApi"

**Tried approaches---**
1) use feedbackServiceRef to pass from the module shown above and use the same in Actions, build fails here saying - "WARNING in ../../node_modules/@backstage/backend-plugin-api/dist/paths.cjs.js 17:63-70
➤ YN0000: [backstage-app]: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted"

2 & 3) Don't pass the serviceRef in module, rather do a useApi in the Action class - 
const feedbackApi = useApi(feedbackServiceRef) OR
const feedbackApi = useApi(feedbackApiRef),

where feedbackApiRef is defined in frontend plugin.ts class as 

```ts
export const feedbackApiRef = createApiRef<FeedbackApi>({
  id: 'plugin.feedback.service',
});

and feedbackServiceRef is created in feedback-client folder as 
export const feedbackServiceRef = createServiceRef<FeedbackApi>({
  id: 'feedback-client',
  defaultFactory: async service =>
    createServiceFactory({
      service,
      deps: {
        config: coreServices.rootConfig,
      },
      async factory({ config }) {
        return new FeedbackClient(config);
      },
    }),
});
```

Above method errors out saying -

```
export { AnalyticsContext } from './analytics/AnalyticsContext.esm.js';
➤ YN0000: [backstage-backend]: ^^^^^^
➤ YN0000: [backstage-backend]:
➤ YN0000: [backstage-backend]: SyntaxError: Unexpected token 'export'
..........
 at Object.<anonymous> (d:\dev\Workspace_VSC\gitttt\backstage-app\plugins\scaffolder-backend-feedback\src\actions\feedback-create.ts:11:36)
```

I have also tried changing the role fo client package from common library to a node library but nothing seems to work.
Can someone please help, what am I missing here? @freben any help would be appreciated

### 👍 Expected behavior

build should pass and app should load

### 👎 Actual Behavior with Screenshots

NA

### 👟 Reproduction steps

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by dyatlov** [comment]
I just ran into exact same issue!
We wanted to share common API functionality between frontend and backend modules and moved it into a common plugin.
But the moment I utilize `createApiRef` backend fails with the same `Unexpected token Export`
had to get rid of the use of that package and instead accept callbacks as parameters which resolve into actual method calls within target plugins.. that's of course a hack.
Also looking for a solution.

**Comment by ankitapandey1106** [comment]
hi @freben @Rugvip @camilaibs  Any help would be appreciated

**Comment by freben** [comment]
I think there's some confusion here on frontend vs backend vs common.

Backend can never import frontend things. For example, `useApi` can never ever be a thing outside of frontend-specific packages. The inverse is true too: frontend packages can't use backend packages.

On top of this, common is VERY special and rarely used and can't import EITHER frontend OR backend specific things. Therefore, common packages are usually very small and only contain e.g. types and helpers and such that you distinctly need to share between frontend and backend. They are rare for a reason and a bit harder to work with because they are so restricted in what they can do.

You probably need to go through your package.json files and clean them out, carefully looking at every single dependency. Does any backend package depend on `@backstage/test-utils` instead of `@backstage/backend-test-utils` for example?

**Comment by ankitapandey1106** [comment]
I had to refactor the common module into node library and common library and he error seems to have been resolved
