### ISSUE TITLE
🚀 Feature: emailMatchingUserEntityProfileEmail should be case-insensitive

### ISSUE THREAD

**Issue by tdabasinskas** [backstage/backstage#28166]
### 🔖 Feature description

Email addresses are case-insensitive, therefore it would make sense for common sign-in resolver `emailMatchingUserEntityProfileEmail` to be case-insensitive as well.

### 🎤 Context

In our use case, we import users from GitHub, while we use Microsoft for authentication. It works quite well, as the users have same e-mail addresses set to their GitHub Accounts and Entra ID.

However, there are users that have their e-mails set as `Name.Surname@company.com` in one system and `name.surname@company.com` in another. Authentication for such users fails with the error saying that the user does not exist in the catalog. This confuses the users, requires them to approach the platform team and update their e-mail addresses once instructed.

I cannot think of a reason we would want the e-mail comparison to be case-sensitive.

### ✌️ Possible Implementation

Not sure if we can lowercase specific filter names passed to `signInWithCatalogUser()`, but I believe we should at least lowercase `profile.email` before passing it to the function.

I'm aware we can create our own `sigInResolver` which would lowercase the e-mail, but I think it might be worth addressing this in the built-in resolver. I can do a PR, but would like to align on the approach before.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@Rugvip for some eyes here too.

**Comment by Rugvip** [comment]
This needs to stay as is unfortunately, see ` BS-CR-24-105` in the full audit report from https://backstage.io/blog/2024/12/17/backstage-security-audit-2024

**Comment by tdabasinskas** [comment]
Thanks, @Rugvip, wasn't aware of this 😮
