### ISSUE TITLE
🐛 Bug Report: Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled and manifest file 404 with blank screen

### ISSUE THREAD

**Issue by maheshwari1501** [backstage/backstage#28181]
### 📜 Description

i have set up the application and then exposed it to ingress path based, in google cloud

app:
  title: Backstage App
  baseUrl: https://qa.leap.net/backstage
organization:
  name: Spotify

backend:
  baseUrl: https://qa.leap.net/backstage
  listen:
    port: 7007
  csp:
    connect-src: ['*']
  cors:
    origin: https://qa.leap.net/backstage
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy: {}

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

scaffolder: {}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

# Consolidated Kubernetes configuration
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: 
          name: 
          authProvider: 'google'
          skipTLSVerify: false
          skipMetricsLookup: true

permission:
  enabled: true

ingress file 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/backstage/static/(.*)$ /static/$1 break;
      add_header X-Content-Type-Options nosniff;
      add_header X-Frame-Options SAMEORIGIN;
      add_header X-XSS-Protection "1; mode=block";
      add_header Content-Security "default-src 'self' 'unsafe-inline' 'unsafe-eval'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' *; img-src 'self' data:; style-src 'self' 'unsafe-inline';";
    nginx.ingress.kubernetes.io/proxy-redirect-from: "off"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: backstage.backstage.svc.cluster.local
    nginx.ingress.kubernetes.io/use-regex: "true"
  creationTimestamp: "2024-12-17T06:07:01Z"
  generation: 9
  name: dummy
  namespace: backstage
  resourceVersion: "921390731"
  uid: 78127ce5-b2ed-421a-b7ff-2faafc19e230
spec:
  ingressClassName: nginx
  rules:
  - host: qa.leap.net
    http:
      paths:
      - backend:
          service:
            name: backstage
            port:
              number: 80
        path: /backstage/(.*)
        pathType: Prefix
      - backend:
          service:
            name: backstage
            port:
              number: 80
        path: /static/*
        pathType: Prefix

### 👍 Expected behavior

I am getting application is running inside the pod but 404 error for manifest.json file 

### 👎 Actual Behavior with Screenshots

I am getting errors:
Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
and then getting 404 manifest.json file not found 
so https:qa.leap.ai is coming black screen 

### 👟 Reproduction steps

i was editing the app.config.yaml and ingress files to resolve,

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey :wave: I replied in the other issue that you commented on. Going to close this, and keep the conversation in one place https://github.com/backstage/backstage/issues/25662
