### ISSUE TITLE
🐛 Bug Report: GitlabUrlReader not working since undici change

### ISSUE THREAD

**Issue by davidgiga1993** [backstage/backstage#28190]
### 📜 Description

After upgrading to backstage 1.34.0 which includes the undici change it is not possible anymore to use `fetchContents` with the `GitlabUrlReader`.

### 👍 Expected behavior

The call should copy the entire repository

### 👎 Actual Behavior with Screenshots

Gitlab responds with `406`. After further investigation it looks like the `sec-fetch-mode: cors` header is the root cause which causes gitlab to reject the `../repository/archive` request.

This was not the case before updating backstage - I suspect this header wasn't included before.

### 👟 Reproduction steps

1. Use gitlab integration:
```
integrations:
  gitlab:
```

2. Run fetchContents with a gitlab repository:
```ts
await fetchContents({
        reader: reader,
        integrations: integrations,
        fetchUrl: ctx.input.url as string,
        outputPath: templateDir,
      });
```

### 🖥️ Your Environment

OS:   Windows_NT 10.0.19045 - win32/x64
node: v22.11.0
yarn: 4.4.1
cli:  0.29.4 (installed)
backstage:  1.33.0

Dependencies:
  @backstage/app-defaults                                          1.5.15
  @backstage/backend-app-api                                       1.1.0
  @backstage/backend-common                                        0.25.0
  @backstage/backend-defaults                                      0.5.3, 0.6.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.4.0
  @backstage/backend-plugin-api                                    1.0.2, 1.1.0
  @backstage/backend-test-utils                                    1.2.0
  @backstage/catalog-client                                        1.8.0, 1.9.0
  @backstage/catalog-model                                         1.7.1, 1.7.2
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.11
  @backstage/cli                                                   0.29.4
  @backstage/config-loader                                         1.9.2, 1.9.3
  @backstage/config                                                1.3.0, 1.3.1
  @backstage/core-app-api                                          1.15.3
  @backstage/core-compat-api                                       0.3.4
  @backstage/core-components                                       0.16.2
  @backstage/core-plugin-api                                       1.10.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.5, 1.2.6
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.3
  @backstage/frontend-defaults                                     0.1.4
  @backstage/frontend-plugin-api                                   0.9.3
  @backstage/frontend-test-utils                                   0.2.4
  @backstage/integration-aws-node                                  0.1.13, 0.1.14
  @backstage/integration-react                                     1.2.2
  @backstage/integration                                           1.15.2, 1.16.0
  @backstage/plugin-api-docs                                       0.12.2
  @backstage/plugin-app-backend                                    0.4.3
  @backstage/plugin-app-node                                       0.1.28
  @backstage/plugin-app                                            0.1.4
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.3
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.3.1
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.3
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.3
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.3
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.3
  @backstage/plugin-auth-backend-module-github-provider            0.2.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.3
  @backstage/plugin-auth-backend-module-google-provider            0.2.3
  @backstage/plugin-auth-backend-module-guest-provider             0.2.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.3
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.3
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.3
  @backstage/plugin-auth-backend-module-okta-provider              0.1.3
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.3
  @backstage/plugin-auth-backend                                   0.24.1
  @backstage/plugin-auth-node                                      0.5.4, 0.5.5
  @backstage/plugin-auth-react                                     0.1.10
  @backstage/plugin-bitbucket-cloud-common                         0.2.26
  @backstage/plugin-catalog-backend-module-gitlab                  0.5.0
  @backstage/plugin-catalog-backend-module-logs                    0.1.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.3
  @backstage/plugin-catalog-backend                                1.29.0
  @backstage/plugin-catalog-common                                 1.1.2
  @backstage/plugin-catalog-graph                                  0.4.14
  @backstage/plugin-catalog-import                                 0.12.8
  @backstage/plugin-catalog-node                                   1.15.0
  @backstage/plugin-catalog-react                                  1.15.0
  @backstage/plugin-catalog                                        1.26.0
  @backstage/plugin-events-node                                    0.4.6
  @backstage/plugin-kubernetes-backend                             0.19.1
  @backstage/plugin-kubernetes-common                              0.9.1
  @backstage/plugin-kubernetes-node                                0.2.1
  @backstage/plugin-search-backend-module-pg                       0.5.39
  @backstage/plugin-search-backend-module-techdocs                 0.3.4
  @backstage/plugin-search-backend-node                            1.3.6
  @backstage/plugin-search-backend                                 1.8.0
  @backstage/plugin-search-common                                  1.2.16
  @backstage/plugin-search-react                                   1.8.4
  @backstage/plugin-search                                         1.4.21
  @backstage/plugin-signals-react                                  0.0.8
  @backstage/plugin-techdocs-backend                               1.11.4
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.19
  @backstage/plugin-techdocs-node                                  1.12.15
  @backstage/plugin-techdocs-react                                 1.2.12
  @backstage/plugin-techdocs                                       1.12.0
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.17
  @backstage/release-manifests                                     0.0.12
  @backstage/test-utils                                            1.7.3
  @backstage/theme                                                 0.6.3
  @backstage/types                                                 1.2.0
  @backstage/version-bridge                                        1.0.10

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Wow, the discussions in https://github.com/nodejs/undici/issues/1305 are... Colorful.

If you do feel up to it, we'd love your help attempting:

- setting a `mode` field in each fetch that goes through by passing in a little "wrapper", or
- just reverting to node-fetch and adding a comment linking to this issue and explaining why we didn't succeed in using undici just yet

It would be lovely if the first option worked out. But if it's faster and safer to revert, then let's absolutely do that and we can make a patch release for it.

**Comment by davidgiga1993** [comment]
Thanks for the quick reply! Yes I've stumbled upon this thread as well, very colorful indeed.

Regarding the first option: What would be the expected code to execute when the `no-cors` option is given? As far as I understand undici doesn't allow disabling it for `fetch`.

**Comment by freben** [comment]
Maybe I misread, but from a quick glance it seemed that that setting might actually have an effect (eg something like `fetch('url', { mode:...`. But I'm not sure.

**Comment by davidgiga1993** [comment]
Sadly the mode flag only sets the value of the `sec-fetch-mode` header (see [this function](https://github.com/nodejs/undici/blob/main/lib/web/fetch/util.js#L243)).
So we either need to go with 2 or 3 as it looks like to be impossible to disable / bypass this behavior.

Regarding the architecture, should this be the default in general for the backend? In that case I could just wrap the global `fetch` method and inject that option there. Given that non-browser requests (usually) never include cors it would make sense I guess. Also from a developer perspective as it would "just work" the expected way.

Or would you rather prefer to have an explicit 2nd fetch definition that the caller must import? That would somehow work against `adr-014` I guess.

Regardless of those options: What would be a good place to add this code to?

**Comment by freben** [comment]
Oh, at the top it said

> it looks like the `sec-fetch-mode: cors` header is the root cause

So I thought that would be a viable fix?

Either way, `fetchContents` ends up calling `readTree` [here on the GitLab URL reader](https://github.com/backstage/backstage/blob/be83f053076f00d687eebbf334eafa95acc73a85/packages/backend-defaults/src/entrypoints/urlReader/lib/GitlabUrlReader.ts#L111). It calls a [`getGitLabRequestOptions` function] which sets some properties. My hope was that that one could always forcibly add a `mode` property to the `RequestInit`.

**Comment by benjdlambert** [comment]
> we can instead try the diffrent-but-actually-better undici.requests instead of fetch in that class

Yeah, I'm wondering if this is really the way that we want to go anyways, maybe?

**Comment by davidgiga1993** [comment]
> Oh, at the top it said
> 
> > it looks like the `sec-fetch-mode: cors` header is the root cause
> 
> So I thought that would be a viable fix?

The issue is that the header will still be included, just with `no-cors` as value. Gitlab will reject any request with the `sec-fetch-mode` header set.

**Comment by freben** [comment]
> > we can instead try the diffrent-but-actually-better undici.requests instead of fetch in that class
> 
> Yeah, I'm wondering if this is really the way that we want to go anyways, maybe?

In many places yes I think so. There's nothing holding us to using specifically the `fetch` API, except familiarity. There's nothing magic about it really.

**Comment by benjdlambert** [comment]
Gonna ship this in the `-next` release today, if someone could just do a quick check to make sure it's back to a working state, and then we can fix a patch release over the next few days if it's deemed to be fixed.

**Comment by freben** [comment]
One confirmation: https://discord.com/channels/687207715902193673/1319982951672446976/1321057003308716062

**Comment by benjdlambert** [comment]
Patch is here https://github.com/backstage/backstage/pull/28289

**Comment by benjdlambert** [comment]
Patch is out, so gonna close this issue, but we should look at moving to `unidici.requests` most likely then @freben?

**Comment by freben** [comment]
Probably best to try to stick to undici yeah if we can since it's truly the embraced library at this point

**Comment by gmezaTektonlabs** [comment]
I'm using latest backstage version and checked that this issue returned for fetch from gitlab, I was checking and figured it that the code was updated in the latest months so the fix was override

**Comment by benjdlambert** [comment]
https://github.com/backstage/backstage/issues/34395#issue-4522730401
