### ISSUE TITLE
🐛 Bug Report: funny typo

### ISSUE THREAD

**Issue by avila-m-6** [backstage/backstage#28200]
### 📜 Description

It's just a typo for `thew` instead of `threw` here:

https://github.com/backstage/backstage/blob/87a4f97f750f6b860dbe81a48c2f382ebf238b8b/packages/backend-app-api/src/wiring/createInitializationLogger.ts#L78

### 👍 Expected behavior

Correct spelling

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
Hahah, woops.

Is this something you would like to contribute a fix for?

**Comment by srushti-712** [comment]
Hi @benjdlambert , I have created a [PR](https://github.com/backstage/backstage/pull/28244) for this

**Comment by benjdlambert** [comment]
Closing as this is fixed in the PR :tada:
