### ISSUE TITLE
🐛 Bug Report: profile picture omitted up in user object

### ISSUE THREAD

**Issue by NoamMuallem** [backstage/backstage#28273]
### 📜 Description

I want to display the user profile picture 

### 👍 Expected behavior

The user profile object should include the profile picture
![Screenshot 2024-12-22 at 14 28 19](https://github.com/user-attachments/assets/02bb3730-ae59-4c62-90db-f49663c16627)

### 👎 Actual Behavior with Screenshots

No picture on user profile object 
![Screenshot 2024-12-22 at 14 29 34](https://github.com/user-attachments/assets/ced3b876-e99b-4f29-9c18-9bf3e426d977)
![Screenshot 2024-12-22 at 14 28 57](https://github.com/user-attachments/assets/192c6681-f68e-48cb-ade6-1a4545e54a34)

### 👟 Reproduction steps

1. add a picture field to the user entity yaml file.
2. use identityApi.getProfileInfo() to get the user profile.

### 📃 Provide the context for the Bug.

I created a form where developers in my company can change the profile picture and add more relevant contact information.
I want to store and read the images from s3 bucket

### 🖥️ Your Environment

OS:   Darwin 23.6.0 - darwin/arm64
node: v20.15.1
yarn: 1.22.22
cli:  0.28.1 (installed)
backstage:  1.32.3

Dependencies:
  @backstage/app-defaults                                          1.5.12
  @backstage/backend-app-api                                       1.0.1
  @backstage/backend-common                                        0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.5.2
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.2.0
  @backstage/backend-plugin-api                                    0.8.1, 1.0.1, 1.1.0
  @backstage/backend-tasks                                         0.6.1
  @backstage/backend-test-utils                                    1.0.2
  @backstage/catalog-client                                        1.7.1, 1.9.0
  @backstage/catalog-model                                         1.7.0, 1.7.2
  @backstage/cli-common                                            0.1.14, 0.1.15
  @backstage/cli-node                                              0.2.9
  @backstage/cli                                                   0.28.1
  @backstage/config-loader                                         1.9.1
  @backstage/config                                                1.2.0, 1.3.1
  @backstage/core-app-api                                          1.15.1
  @backstage/core-compat-api                                       0.3.1
  @backstage/core-components                                       0.15.1
  @backstage/core-plugin-api                                       1.10.0
  @backstage/dev-utils                                             1.1.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4, 1.2.6
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.0
  @backstage/frontend-defaults                                     0.1.1
  @backstage/frontend-plugin-api                                   0.9.0
  @backstage/frontend-test-utils                                   0.2.1
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.2.0
  @backstage/integration                                           1.15.1
  @backstage/plugin-api-docs                                       0.11.11
  @backstage/plugin-app-backend                                    0.3.76
  @backstage/plugin-app-node                                       0.1.26
  @backstage/plugin-app                                            0.1.1
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.1, 0.3.3
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.1, 0.1.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.2.1, 0.3.1
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.1, 0.2.3
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.1, 0.2.3
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.1, 0.1.3
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.1, 0.3.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.1, 0.3.3
  @backstage/plugin-auth-backend-module-github-provider            0.2.1, 0.2.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.1, 0.2.3
  @backstage/plugin-auth-backend-module-google-provider            0.2.1, 0.2.3
  @backstage/plugin-auth-backend-module-guest-provider             0.2.1
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.1, 0.2.3
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.1, 0.3.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.1, 0.2.3
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.1, 0.3.3
  @backstage/plugin-auth-backend-module-okta-provider              0.1.1, 0.1.3
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.1, 0.2.3
  @backstage/plugin-auth-backend                                   0.23.1, 0.24.1
  @backstage/plugin-auth-node                                      0.5.3, 0.5.5
  @backstage/plugin-auth-react                                     0.1.7
  @backstage/plugin-bitbucket-cloud-common                         0.2.24
  @backstage/plugin-catalog-backend-module-aws                     0.4.4
  @backstage/plugin-catalog-backend-module-logs                    0.1.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.1
  @backstage/plugin-catalog-backend                                1.27.1
  @backstage/plugin-catalog-common                                 1.1.0, 1.1.2
  @backstage/plugin-catalog-graph                                  0.4.11
  @backstage/plugin-catalog-import                                 0.12.5
  @backstage/plugin-catalog-node                                   1.13.1, 1.15.0
  @backstage/plugin-catalog-react                                  1.14.0
  @backstage/plugin-catalog                                        1.24.0
  @backstage/plugin-events-node                                    0.4.3
  @backstage/plugin-kubernetes-backend                             0.18.7
  @backstage/plugin-kubernetes-common                              0.8.3
  @backstage/plugin-kubernetes-node                                0.1.20
  @backstage/plugin-kubernetes-react                               0.4.4
  @backstage/plugin-kubernetes                                     0.11.16
  @backstage/plugin-org                                            0.6.31
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.1
  @backstage/plugin-permission-backend                             0.5.50
  @backstage/plugin-permission-common                              0.8.1, 0.8.3
  @backstage/plugin-permission-node                                0.8.4, 0.8.6
  @backstage/plugin-permission-react                               0.4.27
  @backstage/plugin-proxy-backend                                  0.5.7
  @backstage/plugin-scaffolder-backend-module-azure                0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.1
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.1
  @backstage/plugin-scaffolder-backend-module-github               0.5.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.6.0
  @backstage/plugin-scaffolder-backend                             1.26.2
  @backstage/plugin-scaffolder-common                              1.5.6
  @backstage/plugin-scaffolder-node                                0.5.0
  @backstage/plugin-scaffolder-react                               1.13.2
  @backstage/plugin-scaffolder                                     1.26.2
  @backstage/plugin-search-backend-module-catalog                  0.2.4
  @backstage/plugin-search-backend-module-pg                       0.5.37
  @backstage/plugin-search-backend-module-techdocs                 0.3.1
  @backstage/plugin-search-backend-node                            1.3.4
  @backstage/plugin-search-backend                                 1.6.1
  @backstage/plugin-search-common                                  1.2.14, 1.2.16
  @backstage/plugin-search-react                                   1.8.1
  @backstage/plugin-search                                         1.4.18
  @backstage/plugin-signals-react                                  0.0.6
  @backstage/plugin-techdocs-backend                               1.11.1
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.16
  @backstage/plugin-techdocs-node                                  1.12.12
  @backstage/plugin-techdocs-react                                 1.2.9
  @backstage/plugin-techdocs                                       1.11.0
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.14
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.7.0
  @backstage/theme                                                 0.6.0
  @backstage/types                                                 1.1.1, 1.2.0
  @backstage/version-bridge                                        1.0.10

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Hey :wave: thanks for raising this!

AFAIK It should be on the type https://github.com/backstage/backstage/blob/d2f133fa5e9344fbebac4ae0d6768badd776cad9/packages/core-plugin-api/src/apis/definitions/auth.ts#L245-L260

What auth provider are you using?

**Comment by NoamMuallem** [comment]
I am using a custom onlogin provider,  but implemented a form so  the users can update the user entity yaml (I use ejs on the backend to generate the yaml).
The image is stored in an s3 bucket and the relevant url is then stored in the picture field, the entire yaml is stored in the same bucket.

**Comment by benjdlambert** [comment]
So what you get when calling the `IdentityApi.getProfile` does not come from the entity in the catalog, rather it comes from the `auth-backend` and the `profile` that's returned there.

Are you using the `Onelogin` provider from `@backstage/plugin-auth-backend-module-onelogin` or you using something entirely custom?

**Comment by NoamMuallem** [comment]
I am using a custom implementation of the onelogin provider:
```
/* eslint-disable @typescript-eslint/no-use-before-define */
import {
  coreServices,
  createBackendModule,
} from '@backstage/backend-plugin-api';
import {
  DEFAULT_NAMESPACE,
  stringifyEntityRef,
} from '@backstage/catalog-model';
import { oneLoginAuthenticator } from '@backstage/plugin-auth-backend-module-onelogin-provider';
import {
  authProvidersExtensionPoint,
  createOAuthProviderFactory,
} from '@backstage/plugin-auth-node';
import { UserYamlFields } from '@internal/backstage-plugin-shared-types-common';
import { getErrorMessage } from '@internal/common-services';

const ALLOWED_DOMAINS = [...];

// Sources:
// https://backstage.io/docs/auth/identity-resolver#building-custom-resolvers
// https://github.com/backstage/backstage/issues/23829#issuecomment-2019982106
export const customOneloginProvider = createBackendModule({
  pluginId: 'auth',
  moduleId: 'custom-onelogin-provider',
  register(reg) {
    reg.registerInit({
      deps: {
        providers: authProvidersExtensionPoint,
        config: coreServices.rootConfig,
        logger: coreServices.logger,
      },
      async init({ providers, config, logger }) {
        providers.registerProvider({
          providerId: 'onelogin',
          factory: createOAuthProviderFactory({
            authenticator: oneLoginAuthenticator,
            async signInResolver({ profile: { email } }, ctx) {
              if (!email) {
                throw new Error(
                  'Login failed, user profile does not contain an email',
                );
              }
              const [localPart, domain] = email.split('@');
              if (!ALLOWED_DOMAINS.includes(domain)) {
                throw new Error(
                  `Login failed, the provided email does not belong to the required domain`,
                );
              }
              const userEntity = stringifyEntityRef({
                kind: 'User',
                name: localPart,
                namespace: DEFAULT_NAMESPACE,
              });
              try {
                // Throw if user is not in the catalog
                await ctx.findCatalogUser({
                  entityRef: userEntity,
                });
                // Sign in with catalog entity
                return ctx.signInWithCatalogUser({
                  entityRef: userEntity,
                });
              } catch {
                await addUserToCatalog({
                  backendURL: config.getString('backend.baseUrl'),
                  email,
                  onError: e => {
                    logger.error(`Failed to create user entity: ${e}`);
                  },
                });
                return ctx.issueToken({
                  claims: {
                    sub: userEntity,
                    ent: [userEntity],
                  },
                });
              }
            },
          }),
        });
      },
    });
  },
});

const addUserToCatalog = async ({
  backendURL,
  email,
  onError,
}: {
  backendURL: string;
  email: string;
  onError: (e: string) => void;
}) => {
  const [localPart] = email.split('@');
  if (backendURL) {
    try {
      const body: UserYamlFields = {
        displayName: localPart
          .replace(/\./g, ' ')
          .replace(/\b\w/g, char => char.toUpperCase()),
        email,
      };
      await fetch(`${backendURL}/api/catalog-entities-form/user-entities`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      });
    } catch (e) {
      onError(getErrorMessage(e));
    }
  }
};

```

**Comment by NoamMuallem** [comment]
@benjdlambert so what do you think I should do? the FE will not have a direct access to the bucket, so how can I infer that a user has a profile image? I can build the location as it is in the same bucket with the same prefix and with the user name, but I just needs to know that the user has an image there...

**Comment by NoamMuallem** [comment]
@benjdlambert thanks! I used the identityApi to get the userRef and queried the catalog for the full user entity!
