### ISSUE TITLE
[RFC] Static Configuration Schema

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#2854]
**Status:** Open for comments

## Need

Backstage's [static configuration](https://backstage.io/docs/conf/) is being used extensively throughout the project, by both the core packages and plugins. In many places there are examples of valid config, in some places the expected format is documented, but in most cases you need to go read the source code to understand what config you can use. That trajectory that we're on is obviously not scalable, and I think we need more guidelines and/or tooling in place to help make the configuration schema easier to document, discover, and validate.

A separate concern is the uncertainty in who reads each part of the configuration, as in what scope it has. For example, given a configuration value, is it needed by the frontend only? both frontend and backend? only backend? backend and it should be a secret? Given the lack of documentation of the configuration, there's also little clarity in the scope of each value and you again end up relying mostly on examples. In this case it doesn't even help to read the source code though, as that doesn't tell you whether the value is secret or not. Even with solid documentation of the scope of each value, it would be even better to know the scope of each value when loading the documentation. That way we can enforce some values to be treated as secrets and never be sent to the frontend, and we can also omit any backend-only config from the frontend.

### Schema

We add support for declaring static configuration schema through [JSONSchema](https://json-schema.org/). Each package provides it's own sub-schema, and the entire schema can then be stitched together into full view for each individual Backstage app.

Schema is directly or indirectly provided through a `package.json` `configSchema` field. The field can either contain inline JSONSchema, or be a reference to a `.json` or `.yaml` file that contains the schema.

Both the schema itself and the static configuration is validated whenever configuration is loaded, for example when starting up a backend, or building a frontend app. The schema is validated for conflicts, for example if one packages declares a `number` value where another package declares a `string`, an error is thrown. We also validate the configuration itself, for example if (`app-config.yaml`) declares a `string` value where the schema expects a `number`, an error will the thrown.

In addition to validation, we also use the stitched schema to generate documentation. Initially this likely takes the form of a basic CLI tool that prints configuration in the terminal, or whatever else is easiest to set up. Continued work would be to generate either Markdown or a documentation site, as well as bringing the schema into text editors.

### Configuration Value Scope

We also extend JSONSchema with a custom `scope` field. This field is used to indicate where the configuration is loadable from. Valid values are `app`, `default`, and `secret`, where `default` is the default 🙄 . The field applies to any value type, and when used for objects or arrays it applies to all children too, unless they declare a different scope.

Specifying a scope of `app` means that the value will also be sent to the frontend, while a `secret` scope means the value is secret and should never be sent to the frontend, and may have additional validation or tooling tied to it, such as being filtered from logs.

During schema stitching we may discover different declared scopes for the same value, in which case the most specific scope will apply. For example, if a value has both `app` and `default`, the resulting scope is `app`, likewise, `secret` and `default` will result in `secret`. The combination `app` and `secret` is forbidden however, and will cause the schema validation to fail.

## Alternatives

Skip the JSONSchema part and standardize on a way of writing documentation for configuration instead. We'd likely provide a Markdown template to paste into the README and fill in. This does not help solve the configuration scope at runtime, but could still be used to document the scope. A big downside of this approach is that there is no way to aggregate the documentation into a single big schema and document for a given project. When writing configuration you simply have to bounce around different READMEs to figure out the complete schema.

## Risks

Writing JSONSchema can be a bit tedious and it may make people more hesitant to makes things configurable in the first place, especially for more complex configuration. There's also a risk that there are bugs in the schema, as in the schema and the code reading the config don't match. For both of these I think adding tooling around generating either schema from TypeScript types or the other way around could be useful, but nothing to keep in scope before basic functionality is in place.

We may also want to avoid allowing configuration to be inlined in `package.json`, as it could have an impact on what tooling we're able to use.

**Comment by freben** [comment]
Future extension: automatic completion when writing config files in editors :)

:shipit: this will be a great addition and quality of life improvement

**Comment by Rugvip** [comment]
> Future extension: automatic completion when writing config files in editors :)
> 
> :shipit: this will be a great addition and quality of life improvement

Yeah that's in the "continued work" bit xP. Nothing to look at now. For a simple editor integration we'd have to make things as static as possible, but tbh that should already be the case.

**Comment by Fox32** [comment]
I always look into code or copy & paste examples. A documentation would be great here 👍 JSON schema is a nice approach (beside the version chaos).

Knowing where each config is used is a real problem. We weren't sure last weak how secrets are handled and whether they are included in the UI code 😆 Luckily they aren't 😉 

If I have multiple configs that are merged (e.g. app-config.yaml + local, production, ...), the merged configuration is validated, right?
We might have to think about the schemas if we also want to use the schema for auto completion in the separate files?

**Comment by Rugvip** [comment]
> I always look into code or copy & paste examples. A documentation would be great here 👍 JSON schema is a nice approach (beside the version chaos).

We'll likely provide our own JSONSchema schema, extending one of the existing drafts and adding the `scope` field.

> If I have multiple configs that are merged (e.g. app-config.yaml + local, production, ...), the merged configuration is validated, right?

Yes

> We might have to think about the schemas if we also want to use the schema for auto completion in the separate files?

Not following, are you concerned about how to bring all the schemas together so that we can reference it for autocompletion? I'm thinking the `backstage-cli` will provide a command to merge together all known schemas and output a single file that is checked into the app repo and used for autocompletion.

**Comment by andrewthauer** [comment]
I wonder if an alternative to hand crafting the schema files could be a declarative code first config API? Each plug-in could use this API to describe the configuration it exposes. It could potentially just generate a runtime schema behind then scenes.

**Comment by Fox32** [comment]
> Not following, are you concerned about how to bring all the schemas together so that we can reference it for autocompletion?

For autocomplete I don't need required fields to be required, as they might be defined in another file. For validation I would expect the required fields to be required.

**Comment by Rugvip** [comment]
@Fox32 Ah yes idd. So if we generate a schema file for completion we would want to make all fields optional in the entire schema.

**Comment by Rugvip** [comment]
@andrewthauer Yeah mentioned that option in the risks section, but I'm not sold on starting out there as it's a lot more complex and requires some form of tooling. Hoping that it's something we can add in as an optional advanced use-case later, or switch to completely if it's simple enough.

That said, thinking https://github.com/gristlabs/ts-interface-checker or https://github.com/YousefED/typescript-json-schema would be things to look at, and we could even provide some ways to load config straight into those types. A possible way to add the feature would be to be able to specify a `.ts` file and perhaps type in the `configSchema` field in `package.json`. For example `"configSchema": "src/config/types.ts#RootConfig"`.

**Comment by andrewthauer** [comment]
@Rugvip - Sorry, missed your point on the additional tooling in the risks section. Agreed, this could be added later as an alternative convenience option. Although, I do feel like the config schema may be overlooked and not easy to catch if there isn't some guard rails in place.

Another thing, I've found a little frustrating is that when a config value is missing a common pattern is the plugin will console warn in development but throw a runtime error in the prod build/env. The console warnings are easy to miss and therefore it's easy to end up with a production runtime error. I would prefer the app hard fails in development if the config does not match the schema. This could be a runtime error and/or a CLI lint command that validates in CI.

**Comment by Rugvip** [comment]
@andrewthauer Yeah I would like to move the optional startup logic to the backend instead of within the plugins. Plugins would just throw an error if required config is missing, but the errors could be caught and logged in the backend in development. It's pretty convenient to have it set up like that in this repo for example, but internally in an org you could ensure that you always have proper test credentials in place and could disable that behaviour.
