### ISSUE TITLE
Display lighthouse API error in the lighthouse card

### ISSUE THREAD

**Issue by iain-b** [backstage/backstage#2865]
We encountered an issue where our lighthouse plugin was configured in correctly so we got a 404 trying to load the lighthouse card. The error is posted to the errorAPI and displayed in the snackbar at the top. Some other plugins seem to render the error message in the card but others seem to follow this pattern. Which is the preferred pattern ? Can we make a PR to render the message in the card?

## Feature Suggestion

Render lighthouse API errors in the lighthouse card (and not in the snackbar).

## Possible Implementation

The lighthouse hook response object has an error field which we could display (formatted) to the user.

## Context
 
This is what we see currently:

<img width="1603" alt="Screenshot 2020-10-12 at 14 35 39" src="https://user-images.githubusercontent.com/1415599/95754304-bd93a980-0c9a-11eb-8ea4-3f3ef3796815.png">

cc: @lewtakm

**Comment by stefanalund** [comment]
@katz95 wanna chime in? Do we have any guidelines for error handling?

**Comment by dtuite** [comment]
When I see the error in the screenshot it makes me think that the whole page is broken. That's not really the case here, it's only the Lighthosue Audit card which is broken. Everything else should work fine. If the error/warning was displayed in context, within the Lighthouse card, it would be easier for me to know what the problem relates to.

**Comment by ayshiff** [comment]
I think snackbars should always have the same position, which in this case is at the top of the screen.
We could perhaps add a context to the error message in order to have a more precise message.

![Capture d’écran 2020-10-13 à 19 30 59](https://user-images.githubusercontent.com/32459935/95895232-a207cc00-0d8a-11eb-9d01-af3019c758b3.png)

(I don't know what is the best solution, @katz95 will certainly have a better idea to handle the problem)

**Comment by dtuite** [comment]
You're right @ayshiff, if the error is co-located with the component which is causing the error, it no longer makes sense to use a Snackbar component to display it.

**Comment by vividh** [comment]
What is the conclusion here? I would like to help fix this based on whatever we decide.

P.S. I personally think it makes sense to show a warning like message inside the lighthouse card itself. Snackbar should be reserved for other global / page level warnings or errors.

**Comment by dtuite** [comment]
We've started using a pattern where the error shows up in place of the card. We use an error boundary on the widget to do this. It's clear that there is an error and it is co-located with the card that is causing the problem.

It would probably be slightly better if the name of the card was still shown, even when there is an error.

![error](https://user-images.githubusercontent.com/562403/97465930-79f79b80-193a-11eb-9bc3-71d100f9745e.png)

**Comment by Rugvip** [comment]
Happy to extend the [ErrorApi](https://github.com/spotify/backstage/blob/5adfc005e8cff34ee54e23be1fc59e3479c604dd/packages/core-api/src/apis/definitions/ErrorApi.ts#L33) with a context description
