### ISSUE TITLE
[RFC] Seperate the techdocs-ref annotation concerns for reading & building/publishing

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#2878]
**Status:** Open for comments

## Need

The TechDocs solution is intended to support both multiple integration use cases. One of these is allowing backstage to read & render pre-existing docs sites that were not built using the `techdocs-backend`. Currently the `backstage.io/techdocs-ref` annotation seems to be used for both building/publishing & indicating a component has techdocs (for the reader). This causes the `techdocs` to try and build/publish docs from the repo when it's not required.

## Proposal

There is a mechanism to separate the concerns of building/publishing docs sites from indicating the component has docs.

I don't have a specific proposal, but listed some ideas in the alternatives section.

## Alternatives

I'm thinking this could be handled in one or more of the following ways:

- If only the `techdocs.requestUrl` config setting is set, assume the docs are already published via other means
- Add a new config setting to the `techdocs` section in the `app-config.yaml` to control the mode (more explicit then the above)
- Add another annotation for the reader onl side. Maybe the existing `techdoc-ref` would imply the reader side when the new one is not present. However, when the new reader annotation is present the `techdocs-ref` is uused to indicate the docs should be built/published.
- ???

## Risks

Keeping the existing annotation handling multiple concerns will likely be limiting and confusing down the road. However, changing the behaviour of the existing annotation could affect existing users, so some sort of backwards compatibility support would need to be added during a transition period.

**Comment by hooloovooo** [comment]
@andrewthauer You could try removing techdocs-backend and run without that. The only purpose of techdocs-backend is supposed to be building and publishing, so that's how it's meant to work. That said there are some things that might cause issues at the moment so not sure exactly how it'll work.

**Comment by andrewthauer** [comment]
> @andrewthauer You could try removing techdocs-backend and run without that. The only purpose of techdocs-backend is supposed to be building and publishing, so that's how it's meant to work. That said there are some things that might cause issues at the moment so not sure exactly how it'll work.

@hooloovooo - Thanks, I'll try that out and see what happens.

**Comment by andrewthauer** [comment]
So just confirming that removing the backend has not affect on this behaviour. The front end still attempts to update the docs site when viewing.

**Comment by freben** [comment]
I didn't know that it was an intended feature to support non-techdocs-built sites as well. Interesting.

For that use case, will the techdocs backend still be used for "routing" (helping with the fetching of site data)? Or will the frontend be expected to be able to fetch the site data directly from elsewhere? And if so, how is that "elsewhere" pointed out?

Sorry for the noob questions, I am hoping to perhaps be helpful with the catalog model part of it :)

**Comment by andrewthauer** [comment]
@freben - Yes, the `techdocs` frontend package & reader component currently works without the backend. It will do the fetching of the site, etc. based on the `techdocs.requestUrl` config setting. In our case we also override the `TechDocsStorage` API to control how URL's are constructed by the frontend. Everything works well, except we spiny loaders when viewing a docs site, even thought the site is already built and ready to go.

**Comment by OrkoHunter** [comment]
Thanks @andrewthauer for your response and thanks @freben for asking! Moving forward, it makes sense to have `techdocs` use `techdocs-backend` as much as possible (maybe just as a proxy). This will help 1. Limit access to certain groups/orgs. Doing this in the backend will be easier/optimal. 2. For improving security, only allow `techdocs-backend` to access the external storage (GCS, S3, etc.) either via IP restriction or good ol' access tokens.

But yeah, as of now it's simple enough to directly read the files from `techdocs.storageUrl` app config.

**Comment by andrewthauer** [comment]
@OrkoHunter - This seems sounds like a reasonable approach. Having the docs request route through a future backstage backend would be fine for us. The 2 requirements for us in this scenario would be:

- The backend doesn't need to manage building the docs site. I believe the idea of having the `techdocs-cli` able to do this in CI would mean that is the case
- The ability to control how site pages are found. For instance, we don't currently use the implied prefix for docs entities that includes the namespace etc. We are able to customize this with the frontend `TechDocsStorage` ref now. Assuming this feature is carried over to the backend, then all should be good I suspect.

**Comment by hooloovooo** [comment]
@andrewthauer Both of your scenarios are things we plan to support. The second scenario won't be very accessible and will still require a custom api implementation since it's not something we recommend for most people. As @OrkoHunter said we want the techdocs-backend to be a middleware even when you have your own build flow set up somewhere else since it allows things such as using Backstages access control. This also means that we want to rebuild parts of the backend to support serving without building the docs. Not sure exactly how the config will look like for that, but i feel like looking if we have `storageUrl` set isn't a very obvious solution. I'm leaning towards having it set explicitly as a flag, something like `techdocs.backend.manageBuild = <boolean>`.

We're rebuilding the techdocs-cli to contain the entire build process needed for techdocs. When that is ready we'll likely add a few more `prepare` handlers that will make more sense in the CI/CD context. For example one where you can pass in your `component-info.yaml` and have it resolve a `techdocs-ref` with the `dir` type (exactly how this preparer should work is not something we've discussed yet, so it's mostly me speculating exactly how we will handle the prepare step in CI/CD).

**Comment by OrkoHunter** [comment]
> This causes the techdocs to try and build/publish docs from the repo when it's not required.

It's now possible to set [`techdocs.builder` to `external`](https://backstage.io/docs/features/techdocs/configuration) in app config and TechDocs will not try to build docs. Sites will only be fetched from the storage in a read-only mode. So in a way - `backstage.io/techdocs-ref` is no longer being used for building sites, and the [prepare/generate/publish steps could be done separately on CI/CD](https://backstage.io/docs/features/techdocs/configuring-ci-cd) using `techdocs-cli`.

I think it's safe to close this issue now @andrewthauer. Let me know if you have any questions.
