### ISSUE TITLE
Onboarding wizard for repos that do not have a catalog-info.yaml

### ISSUE THREAD

**Issue by freben** [backstage/backstage#2901]
## Feature Suggestion

A lot of users will start their Backstage journey with an empty catalog but a lot of existing source code repos that they would like to get in there. The current workflows require them to manually create catalog-info.yaml files for each one of them and register that. This is tricky to get right from the start and requires low level fiddling with YAML files whose format you are not yet familiar with.

Backstage already has a "Create..." sidebar entry and a "Register existing component" functionality. It should be extended with an "import" wizard that lets you onboard an existing repo of code as easily as possible.

## Possible Implementation

Illustrating the idea with an example user journey:

1. There is already a Java backend repo in a GitHub enterprise installation, and the user wishes to add it to the catalog.
2. The user clicks "Create..." in the sidebar and then "Import existing component".
3. A wizard appears, which asks for what repository and path you want to import. This could be as simple as a text box into which you can paste for example `https://ghe.mycompany.net/myorg/myrepo`. Or it could be helpful and presents a list of repos that you have access to. Then the user presses Next.
4. A spinner appears while the wizard analyses the target repository. It searches for a long list of well known things. It finds a `.github/CODEOWNERS` file, it finds a `pom.xml` file, it finds an `openapi.json` file nearby, it loads the teams present in the org to see which ones the user is a member of.
5. A page of findings is presented. It suggests that the `owner` is managed by codeowners, but the user can choose to either select from a list of teams they are a member of, or to type a string manually. It suggests the component name and description from the contents of the pom file. It could not find any data on the lifecycle of the component, so it asks the user to provide one. It said it found a nearby OpenAPI declaration and suggests making an API entity for that too and link it up to the service. When the user is satisfied with the wizard, they click Create.
6. The wizard uses the GitHub API to create a pull request in the target repo, that creates a `catalog-info.yaml` file. The file contains the service component and the api entity, wired up and with the right data entered. The file is automatically registered in the catalog with a special flag that tells the catalog that it's OK that it isn't present yet, because it will be at a later time.
7. The user is presented with an "all done" final state, with a link to the generated file and an offering to import one more repo.

## Context

The onboarding process is pretty technical and requires a fair amount of work before seeing the full value of the system. Adding a wizard like this would also make it easier to distribute the effort, so that individual teams more easily can take care of their own onboarding in a point-and-click interface instead of manually learning and writing the catalog info format.

## Future work

In the future, it may not even be necessary to create the yaml file at all; instead, we could register the repo as the actual location. With the right set of processors, it could be possible to get all the information needed without having to tether to a specific catalog-info file. The refresh loops would then re-examine the entire repo state on each run and adapt as necessary.

**Comment by dtuite** [comment]
Related discussion in https://github.com/spotify/backstage/issues/2801.

FWIW we've had conversations with at least one company who consider the YAML files to be a critical part of the value of Backstage. They want to be able to search across them with SourceGraph.

**Comment by koalado** [comment]
@dtuite  please take other git providers in mind as well 😃  At my company we use Bitbucket for all our repositories.

**Comment by dtuite** [comment]
@koalado As a workaround, perhaps you could consider migrating your company to GitHub?

😂  Just kidding! You are right. Ideally a feature like this would support all the major players.

**Comment by koalado** [comment]
> @koalado As a workaround, perhaps you could consider migrating your company to GitHub?
> 
> 😂 Just kidding! You are right. Ideally a feature like this would support all the major players.

Good one! 😄 Apart from the provider, if it's GitHub, I really like the idea about the GitHub apps event driven approach.

**Comment by stefanalund** [comment]
I think this is a great idea. Ideally it should be built in a way where the community can help contribute parsers for different kinds of repo -> entity mappings.

**Comment by Rugvip** [comment]
@stefanalund Hopefully we'd be able to re-use existing entity processors for that. Basically start out with a bare entity, run it through a bunch of processors, and use the output entity in the PR. We have enough API surfaces to take care of already 😅

**Comment by mcalus3** [comment]
> The file is automatically registered in the catalog with a special flag that tells the catalog that it's OK that it isn't present yet, because it will be at a later time.
@freben Question about implementation - could this flag be a custom annotation like `backstage.io/pending-pull-request: true` in the entity (the thing that is being saved to the database)? Could this annotation be removed after PR merging (ideally - automatically by a GitHub App or webhook)?

**Comment by freben** [comment]
@mcalus3  I meant the saved location (/entity/locations); the entity itself won't appear in the catalog until after merge

**Comment by freben** [comment]
@stefanalund @Rugvip yeah I hope that this will be basically entirely backend driven with mostly existing mechanisms, maybe a new /catalog/analyze or so

**Comment by dtuite** [comment]
We at roadie.io would like to contribute this feature. I've asked @stefanalund to assign me to it.

@freben we'd love to have a quick sync at some point over the next few days to talk through the plan we have put together. I'll reach out on Discord.

**Comment by stefanalund** [comment]
@dtuite thanks for picking this up. I've assigned you!

**Comment by dtuite** [comment]
We've been prototyping a bit on this over the last few days. Consider this just directional rather than a final implementation.

https://www.loom.com/share/e735120566ed4df4922573e2c728c1e6

**Comment by regicsolutions** [comment]
@dtuite Just wanted to check in to see if there has been any further development with this feature? Prototype looks awesome!

**Comment by dtuite** [comment]
@regicsolutions some of the work is close to being merged in https://github.com/backstage/backstage/pull/3121

We are working on a clicky-checkbox importer which we will open source on the RoadieHQ organization. I guess we need to have a discussion with the core team about whether or not that gets pulled into the monorepo.

**Comment by dtuite** [comment]
By the way, we are looking for people to provide feedback on early versions of this. It helps to get feedback on real usage as there a few different GitHub permission edge cases which can come up. 

Email me at david@roadie.io if you would like to take part.

**Comment by regicsolutions** [comment]
@dtuite would love to provide feedback, but we are using Bitbucket, any plans to adding Bitbucket support?

**Comment by dtuite** [comment]
@regicsolutions Our team at roadie.io have no immediate plans to add Bitbucket support. 

The code is open source and Bitbucket support may be contributed by someone else in the community.

**Comment by adamdmharvey** [comment]
The `@backstage/catalog-import` plugin currently has a few different avenues, and does now have the capability to add a PR to register existing code:

![image](https://user-images.githubusercontent.com/33203301/112246181-9f0de300-8c28-11eb-824a-04024d1c2504.png)

I think the heart of the ask here is likely resolved; what do you think @dtuite ? I know there's even further work to potentially separate out the wizard, which may now even be a bit too complex, but that is tracked elsewhere.

I propose this could be closed.

**Comment by benjdlambert** [comment]
I concur
