### ISSUE TITLE
Pre-configure techdocs sites with repo_url in mkdocs.yml file

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#2903]
To show the edit button on pages of documentation the repo_url config need to be set in the mkdocs.yml file. To avoid one extra step of configuration we want this to be pre-configured in the process of generating documentation. 

The location of the repository can be gathered from the techdocs_ref annotation as it is now, even though this might change in the future. 

The edit button is the "pen" to the right.
<img width="847" alt="Screen Shot 2020-10-14 at 5 18 57 PM" src="https://user-images.githubusercontent.com/25153114/96009799-624feb80-0e41-11eb-8881-5defcdf1b5af.png">

**Comment by Marvin9** [comment]
I would like to work on it.

**Comment by OrkoHunter** [comment]
Hi @emmaindal cc @hooloovooo !

I wonder if `repo_url` is something worth adding to TechDocs Metadata - especially if we only need it for the Edit button.

I am assuming that the URL where this Edit icon will take the user to, will not be different from where this entity is hosted. This information (i.e. entity's location URL) is available in Entity metadata. And we already use it here to show the code `<>` icon.

![Screenshot 2020-11-24 at 23 41 56](https://user-images.githubusercontent.com/8065913/100159764-a6a5c100-2eae-11eb-9418-7706f20cc160.png)

So, my question is can we not we re-use the location of Entity to construct the URL where the "Edit" icon will lead us to?

e.g. (pseudo code)

```
let entityLocation = "https://github.com/backstage/backstage/tree/master/plugins/techdocs-backend/examples/documented-component"

let pageEditLocation = entityLocation.replace("tree", "edit")
pageEditLocation += "/docs/${path}.md"
```

**Comment by emmaindal** [comment]
Hey @OrkoHunter 

> I am assuming that the URL where this Edit icon will take the user to, will not be different from where this entity is hosted.

The difference is, the edit button will be the page your are looking at and if repo_url is added, mkdocs gives us the correct edit link for free for that particular page, as in for example I'm reading the first page of techdocs documentation for the backstage docs, the edit button will be `https://github.com/backstage/backstage/edit/master/docs/README.md` if repo_url is set to where the docs folder lives, in this case `https://github.com/backstage/backstage`. 

Where the link for the code icon is a link to repo level (the whole docs site).

So to answer your question, yes we can use the entity location and create our own edit icon to render if we don't want to use the one we get from mkdocs for free. But then we are back to the TechDocs "widget" framework since we need to render a react component inside of the shadow dom. It also important to keep in mind that the entity location will not always be where the docs folder lives, for example in the monorepo use case.

**Comment by OrkoHunter** [comment]
Aha! @emmaindal I totally forgot about the "for free from MkDocs" bit, i.e. MkDocs has the config [`repo_url`](https://www.mkdocs.org/user-guide/configuration/#repo_url) which we can set and it will render the edit icon for us.

Thanks so much for your response! I think now I understand the issue clearly. :)
