### ISSUE TITLE
Allow or document how to link  backstage packages/plugins to Applications locally. 

### ISSUE THREAD

**Issue by GoWind** [backstage/backstage#2917]
## Feature Suggestion
The simplest solution would be to provide a command within `backstage-cli` that can build or setup the packages in such a way that  they can then be linked using `yarn link` into an application.

If that is not possible, or not in scope at the moment because of constraints, it would be nice to have at least some documentation on how the project is build programmatically. 

## Possible Implementation

A `backstage-cli setup-local` and a `backstage-cli tearup-local` which will `link` and `unlink` the various packages in`backstage` project for use locally. 

## Context

Currently as Backstage is still a project in Alpha and under heavy development, I run into a lot of instances where I am not sure if there is a bug or a limitation (or if some feature is simply not available) in any one of Backstage's packages or plugins. 

The context is when attempting to use the **catalog-backend**  plugin in our application, I ran into an issue where my requests to create a new `Entity` was failing and the error response that was returned, was not sufficient for me to debug why my requests were getting a HTTP 500 response. 

**sunrise** is the name of our backstage generated application. It has 2 packages `app` (frontend) and `backend`.

In an attempt to understand that, I tried to `yarn link` `plugins/catalog-backend` into the `backend` package of our application, but this did not work as the server threw a build error
On first investigation, it looked like this might be because of the `main` entry in `package.json` of `catalog-backend` being `index.ts` rather an `index.js`  or a `index.cjs.js`. 

My hypothesis is that the runtime couldn't understand typescript directly and thus threw a build error.
In an attempt to solve this problem, I added a `tsconfig.json` in the root of our `backend` package, with a `path` entry in the `compileOptions` section:
```
{
 "baseUrl":".",
 "paths": {
   "@backstage/plugin-catalog-backend": "node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js"
 }
}
```
This still doesn't seemed to have solved the problem. 
```
➜  backend git:(process-kio-locations) ✗ pwd
/home/gnagarajan/work/sunrise/packages/backend
➜  backend  yarn start

yarn run v1.22.5
$ backstage-cli backend:dev
Build succeeded
.../work/govind-backstage/plugins/catalog-backend/src/index.ts:17
export * from './catalog';
^^^^^^
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at eval (webpack-internal:///@backstage/plugin-catalog-backend:1:18)
    at Object.@backstage/plugin-catalog-backend (/home/gnagarajan/work/sunrise/packages/backend/dist/main.js:1267:1)
    at __webpack_require__ (/home/gnagarajan/work/sunrise/packages/backend/dist/main.js:749:30)
```
 
Upon attempting to debug the stacktrace, it looks like the backend is built via the `backstage-cli:build` command which is implemented via the `cli` package. As this is not directly using `tsc` but rather using (`rollup`?) to build packages, It is not clear how to setup a local backstage package that can be linked into an application for development and debugging.

**Comment by Rugvip** [comment]
Error is coming from the fact that the TypeScript isn't being transpiled, most likely because it's in `node_modules` and https://github.com/spotify/backstage/blob/a19377601f989a3b8465645a44de6ce0f4b814b6/packages/cli/src/lib/bundler/transforms.ts#L37

The paths in `tsconfig.json` won't affect the build, only the type checking, and the module aliases isn't something that exposed (for good reasons 😅 ).

I'm thinking there are two ways forward:

1. Figure out a way to not exclude the linked packages from transforms.
2. Use dist versions of the packages instead. This may a be a bit more straight-forward to set up, but would require a rebuild on every change.

An option to using `yarn link` is to use `resolutions` in the root `package.json` to point straight to the package dirs, similar to how `packages/e2e-test` is set up here. It would require that all devs working on the project checking the repos out adjacent to each other, or usage of submodules.

When using resolutions it may be possible to set up some magic to transform those packages, but very hesitant to that sorta thing. Do you think trying to find a solution that uses `dist/` is fine, or is that gonna too much overhead? The trickiest thing to figure out there is how to switch the entrypoint to `dist/index.cjs.js` in a sane way.


You should be able to set up yarn resolutions and manually edit the `package.json` in the main Backstage repo to at least get things working, maybe that's enough and you can let us know how that goes? :grin:

**Comment by GoWind** [comment]
Okay, your comment is a lot of JS context for me to parse :sweat_smile: , but I will try to understand the solutions you propose and then add my comments to it. 

1. Figure out a way to not exclude the linked packages from transforms.
The `buildBackendConfig` fn that creates the config for the backend to be built (via Webpack) uses the `transforms` fn to obtain a list of `loaders`. The `loader` for `.ts` , excludes `/node_modules` directory for the dependencies when the backend code is compiled and run , right ?
I noticed that there is a config named `isDev` that loads a HotModuleLoaderPlugin if the environment is `development`.

https://github.com/spotify/backstage/blob/2e1a0b8c99afa8557078afc8ab7102430513e6f7/packages/cli/src/lib/bundler/transforms.ts#L30
Can this flag be not re-used to load `tsx` files within `node_modules` ?

2. Use `dist` versions of the packages instead. 
Does this mean, instead of depending of loading the source of the dependencies, the compiles `js` and `d.ts` versions are loaded and bundled ? And therefore, whenever there is a change in the `source` of the dependency, these will have to be re-generated ? 

On inspecting `publishConfig` I assume that these are the files that are `published` when a new version of the project is published. 
Shouldn't yarn link (or `cli -> backend:build`) ideal read this field and honor it ? I assume that during development, a watch for changes in the files of the dependencies is set anyway? and the dist/*.js can be thus re-generated and re-loaded ? (Some documentation or explanation around this would be nice)

Looking up the purpose of the `resolutions` field in `yarn` [here](https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-selective-versions-resolutions.md), I think it would be an abuse of the purpose , which is to resolve the package versions when there are multiple deps for diff. versions for the same package. I don't think it would be a nice idea to break conventional semantics as it might lead to more confusion. (Please do correct me if I have misunderstood it).

**Comment by kiranpatel11** [comment]
Hi @Rugvip,

I am getting the same ```SyntaxError: Unexpected token 'export'```

Can you please provide some details on your option #2. 

>Use dist versions of the packages instead. This may a be a bit more straight-forward to set up, but would require a rebuild on every change.

I am trying to integrate with Bitbucket Server (not cloud one), and have to make modifications to plugins/scaffolder-backend and packages/backend-common.

Ideally, I would have liked to avoid modifications to any of the backstage code, but as per the current design, I will have to provide integration with Bitbucket Server for catalog and scaffolder features. My suggestion would be to de-couple the provider integrations from core catalog and scaffolder framework. (open-close principle).

**Comment by andrewthauer** [comment]
Another option I've used in the past to test non released packages or forks in an app created by the CLI is using the`yarn workspaces` feature. It's relatively easy to setup for local development. For build artifacts though, you need to create a custom dockerfile, copy over the linked package in n`ode_modules` and replace the `main` entry` with the dist output. This is definitely not an ideal setup but does work.

Here are snippets of the main aspects of the pattern. NOTE: The `Dockerfile`, etc. is only required if your trying to create a build artifact as well.

```json5
// package.json
{
"workspaces": {
    "packages": [
      "backstage/packages/[package-to-test]", // points to either a local `backtage` gitsubmodule (persistent) or a symlink
      "packages/*",
      "plugins/*"
    ]
  },
}
```

Dockerfile for backend

```dockerfile
# Dockerfile for backend
# .... copy files

# Overwrite the original packages
COPY backstage/packages/[package-to-test] packages/[package-to-test]

# Frozen lock won't work in with this hack
RUN yarn install --production

# NOTE: This is temporary for usage with the backstage submodule
RUN apt-get update && apt-get -y install jq && rm -rf /var/lib/apt/lists/*
COPY docker/setup-backend.sh setup-backend.sh
RUN ./setup-backend.sh
```

Script to fix the package `main` entry points:

```bash
#!/usr/bin/env bash
set -Eeuo pipefail

for f in node_modules/@backstage/**/package.json; do
  tmp=$(mktemp)
  echo "Updating $f ..."
  jq '.main = "dist/index.cjs.js"' "$f" >"$tmp" && mv "$tmp" "$f"
done
```

**Comment by andrewthauer** [comment]
Although, I do also think having something built into the `backstage-cli` for testing forks locally would be very handy.

**Comment by GoWind** [comment]
@andrewthauer : Thanks for the tip, I will try it out. 
But I do have a question for you and @Rugvip . 
https://classic.yarnpkg.com/en/docs/workspaces
documentation here mentions `workspaces` has to be an array of `glob` patterns.
Whereas in the `json` that was generated by the `backstage-cli create-app` , the package.json had the following format for workspaces, that we continue to use.

```
"workspaces": {
    "packages": [
      "packages/*",
      "plugins/*"
    ]
  },
```
Question: Is this still set up by Yarn ? If not, does the `cli` read this field in order to understand the dependencies ?

**Comment by kiranpatel11** [comment]
Hi @andrewthauer,

Trying out your suggestion, can you please help me with the details. 

Below is my setup : 

1. created an app using @backstage/create-app cli, say my-backstage.
2. copy-pasted backend-common package from `backstage` git repo to `my-backstage/packages` folder and written implementation for BitbucketServerUrlReader
4.yarn linking .... `cd backend-common` and `yarn link` ; `cd backend` and `yarn link @backstage/backend-common`
5. What should be my workspace config  in `package.json` ?
    tried below options without a luck :(
   ```
  "workspaces": {
    "packages": [
     // how to configure local relative symlink here ?
      "@bakstage/backend-common",
    // "my-backstage/packages/backend-common"            // this did not work either.
      "packages/*",
      "plugins/*"
    ]
  }
   ```
   Please note I have copy-pasted backend-common into local packages folder.

 Getting below error : 
 
```
export * from './config';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\workspace\my-backstage\node_modules\@backstage\plugin-auth-backend\dist\index.cjs.js:12:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

**Comment by andrewthauer** [comment]
> Question: Is this still set up by Yarn ? If not, does the `cli` read this field in order to understand the dependencies ?

@GoWind - The yarn workspaces array takes either a path to a package or a glob pattern for each entry. It takes care of symlinking the actual package into your node_modules so the `cli` should treat it just like other packages so nothing special required.

**Comment by andrewthauer** [comment]
@kiranpatel11

Don't use `yarn link` with this workaround. The yarn workspaces should take care of this for you. When I said symlink, I meant if you want to include a package from outside the root of your backstage app. I typically have done this where the it's a relative git submodule including in the workspaces array.

If you've copied the code directly to the `packages` directory then you don't need to add `my-backstage` in front, since the `packages/*` would include this.

For example:

```
├── forked-backstage # git submodule to https://github.com/fork-of/backstage.git
│   └── packages
│       └── backend-commom
├── packages
│   ├── app # your cli created app
│   └── backend # your cli created backend
├── package.json
└── tsconfig.json
```

Your `package.json` would like like:

```json5
"workspaces": {
    "packages": [
      "packages/*",
      "plugins/*",
      "forked-backstage/packages/backend-common"
    ]
  }
```

Also make sure you include `"forked-backstage/packages/backend-common"` in your tsconfig.json's `include` section.

**Comment by kiranpatel11** [comment]
Thanks @andrewthauer 

Since I am copying the `backend-common` to my local packages, I don't need any extra settings in workspaces. Get That.
But it does not work. build goes through fine, but `yarn start` fails. Any idea why wouldn't it work ?

Let me try your approach as well by having it placed parallel to `packages`

**Comment by andrewthauer** [comment]
I have to ask, but also make sure you run yarn install after setting up the new workspace 😀. If you look at your node_modules/@backstage directory you should see it symlinked to the relative directory.

**Comment by kiranpatel11** [comment]
yes offcourse.
I can see symlinked `backstage-common` 
![image](https://user-images.githubusercontent.com/8432431/96540783-47babe00-12ea-11eb-9777-58564a946242.png)

**Comment by andrewthauer** [comment]
@kiranpatel11 - Sorry, missed this message. Were you able to get this working? Without looking at the code, it's hard to say what the actual problem is unfortunately. Looking back on your previous error, it looks like it's not an error in `backend-common` but in `plugin-auth-backend`. I'm not 100% sure, but it's possible you might need to do this for other backend packages maybe. I've used this pattern 2 twice recently. The first was with every main package/plugin, and the second with just the `@backstage/cli` package. I've never tried it with just one actual runtime package. Although this is a theory, it's possible that's a difference.

**Comment by kiranpatel11** [comment]
Hi @andrewthauer, 

I could not get it working, hence switch to forking the entire backstage repo :-( to test my changes.
However, I have pushed my earlier changes @ https://github.com/kiranpatel11/my-backstage if you like to have a look at the code. Fundamentally, it has only packages/backstage-common added and my changes for BitbucketServer.
I did notice the error is coming from `plugin-auth-backend`, but I suspect that way I would end up having so many transitive dependencies included, which is not viable option for me. I would like to include only packages/plugins where I am adding a customization. (In this case, I have no changes to be done in `plugin-auth-backend`).

PS: There is a PR open for review on bitbucket server support, so these custom changes may not be required, However, the pattern is important to make similar future chanegs when working with create-app cli. e.g. scaffolder.

**Comment by andrewthauer** [comment]
@kiranpatel11 - Sorry, not sure exactly what the problem might be exactly. I experimented with this earlier with a plugin. Assuming the code for the package is physically located (which would be the case for a git submodule) within the `packages` or `plugin` directories then yarn workspaces should pick it up and be happy. However, I noticed that it won't work correctly if it's a symlink unfortunately. I tried both symlinking to the `plugins` directory and also adding a new relative yarn workspace entry. Neither of those worked. So it seems for now at least, a git submodule which is included as a workspace should work in most cases.

**Comment by andrewthauer** [comment]
Interestingly enough, this actually works, BUT "only" if you symlink the `node_modules` from the backstage app to the relative project (e.g. ../../path/to/backstage-plugin/node_modules).

```
"workspaces": {
    "packages": [
      "backstage/packages/cli",
      "packages/*",
      "plugins/*",
      "../../path/to/backstage-plugin/"
    ]
  },
```

**Comment by kiranpatel11** [comment]
For my usecase, since the PR for bitbucket server is now merged, I dont need to make a change in `packages/backstage-common` .

However, I have a similar change in `plugins/scaffolder-backend`, and there I don't see this issue. It pick up my changes without any compile-time or runtime issues. For now I am good, not blocked due to this.

**Comment by andrewthauer** [comment]
@kiranpatel11 - Good to hear.

I do think the original ask of having a mechanism to test packages from outside the monorepo is still very relevant though. For the times I've needed to do this, it's always a bit of a struggle and requires some very hack solutions.
