### ISSUE TITLE
Allowing customization of the Catalog Page 

### ISSUE THREAD

**Issue by althafh** [backstage/backstage#2923]
## Feature Suggestion
Right now the Catalog Page hardcodes the types of Components visible to Services, Websites, Libraries, Documentation and Other. This mean custom component types defined appear in Other.

## Possible Implementation
A simplistic way is to pull that via a Config Array but that seems like Config Bloat.
Maybe a similar implementation to EntityPage which sits in the application itself and not the plugin and thus allows customization?

Open to other suggestions. 
Happy to work on this given a proposed implementation.

**Comment by andrewthauer** [comment]
@althafh - I started #2791 which is exactly meant address this. I e since gotten side tracked with some other things so I'd be perfectly happy if you wanted take this over and/or use the code I started on.

**Comment by althafh** [comment]
Oh perfect! Let me take a look at it next week!

**Comment by andrewthauer** [comment]
Thanks! Assigned to you @althafh!

**Comment by andrewthauer** [comment]
Being worked on in #2791

**Comment by andrewthauer** [comment]
Work moved to #5643. Assigning to you @timbonicus.

**Comment by timbonicus** [comment]
Closed via #5643. This should no longer need customization, since that PR switches the tabs to a select list that loads all types registered in the catalog.
