### ISSUE TITLE
Upgrade to webpack 5.x

### ISSUE THREAD

**Issue by freben** [backstage/backstage#2969]
The cli currently uses webpack 4.x for some of its functionality. This should be bumped to webpack 5.x, but there are a couple of changes between the major versions that need to be addressed to make it possible.

**Comment by Marvin9** [comment]
Working on it.

**Comment by stefanalund** [comment]
Thanks @Marvin9 -- assigned you! 💯

**Comment by Marvin9** [comment]
I don't know when I will have time to complete this. Unassigning for now.
