### ISSUE TITLE
Migrating Microsite from Docusaurus V1 to V2

### ISSUE THREAD

**Issue by abhishekjakhar** [backstage/backstage#2986]
## Feature Suggestion

The microsite has not been updated from quite a long time now, It is still using Docusaurus 1.

We could follow migrating guide provided by Docusaurus to migrate Docusaurus from V1 to V2.

## Possible Implementation

Docusaurus migration guide: https://v2.docusaurus.io/docs/migrating-from-v1-to-v2
Docusaurus docs: https://v2.docusau

## Context

I am looking to do open-source contribution and I find this project very interesting, also It would be a great learning opportunity for me.

**Comment by stefanalund** [comment]
Really? I think we are on v2. Search, for example, is only enabled for v2 sites.

**Comment by abhishekjakhar** [comment]
> Really? I think we are on v2. Search, for example, is only enabled for v2 sites.

The search is there in V1 also, you could see that in this link https://docusaurus.io/docs/en/search, this link is of V1 docs.

There is lot of stuff in V2, I will list some of them below.

**Folder structure of V1**

├── docs
└── website
    ├── blog
    ├── core
    │   └── Footer.js
    ├── package.json
    ├── pages
    ├── sidebars.json
    ├── siteConfig.js
    └── static

**Folder structure of V2**

website
├── blog
├── docs
├── src
│   ├── components
│   ├── css
│   └── pages
├── static
├── package.json
├── sidebars.json
├── docusaurus.config.js

We can migrate CommonJS to ES6 imports/exports.

In Docusaurus v1, pages received the siteConfig object as props, but In Docusaurus v2, we can get the siteConfig object from useDocusaurusContext instead.

You could see lots of other things which are different in V2 here https://v2.docusaurus.io/docs/migrating-from-v1-to-v2 and https://v2.docusaurus.io/docs/

**Comment by abhishekjakhar** [comment]
In package.json we have updated the version to latest V2 but all of the code which we are running is still of V1.

**Comment by freben** [comment]
Is this something you would like to take on? Otherwise I could add a help-wanted label or so

**Comment by abhishekjakhar** [comment]
@freben I would love to do this, could you please assign this to me?

**Comment by freben** [comment]
Done.

**Comment by abhishekjakhar** [comment]
Thank you, I will start working on it.

**Comment by abhishekjakhar** [comment]
Hey, I am working on this. I am halfway there, will take me 2-3 days more to finish this up.
