### ISSUE TITLE
Refresh Token for GitLab

### ISSUE THREAD

**Issue by sandstroms** [backstage/backstage#3044]
Authentication via GitLab does not use refresh tokens even though GitLab supports using them (https://docs.gitlab.com/ee/api/oauth2.html). As a result, whenever I refresh the page, I have to login again.

## Expected Behavior

After logging in via GitLab, then refreshing the page, the user does not need to authenticate.

## Current Behavior
After logging in and refreshing, the user must authenticate.

## Possible Solution
Request an access/refresh token from GitLab

## Steps to Reproduce
1. Login via GitLab
2. Refresh the page

## Context
Want to be able to stay logged in after authenticating with GitLab once.

## Your Environment
- K8s cluster

**Comment by stefanalund** [comment]
@sandstroms wanna take a stab at this yourself? If not I can add a few more labels to the ticket.

**Comment by sandstroms** [comment]
@stefanalund No, I'm not comfortable enough with the code. You can add the labels.

**Comment by stefanalund** [comment]
@sandstroms no worries -- thanks for reporting! Let's hope someone else steps up to the challenge 😄

**Comment by rishibarad** [comment]
Hi @sandstroms, I'd love to take a stab at this! May I claim this issue?

**Comment by stefanalund** [comment]
All yours @rishibarad 💯

**Comment by paolomainardi** [comment]
@rishibarad are you still working on this ? I would like to give an hand on this.

**Comment by rishibarad** [comment]
Hi @paolomainardi, I'm making progress on this. Would you want to collaborate?

**Comment by freben** [comment]
@rishibarad How are things going? Need any help?

**Comment by freben** [comment]
I wonder if it's covered by https://github.com/backstage/backstage/pull/5702 . The issue description claims that we don't use refresh tokens for this provider at all, but I haven't investigated whether that's the case.

**Comment by timbonicus** [comment]
The GitLab auth provider does set [disableRefresh: true](https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/providers/gitlab/provider.ts#L137) for OAuth, though I'm not sure why since the [passport-gitlab2](http://www.passportjs.org/packages/passport-gitlab2/) package says that refresh tokens are optionally supported 🤔

**Comment by freben** [comment]
@Rugvip do you remember?

**Comment by Rugvip** [comment]
@freben The `disableRefresh: true` was part of the initial PR to add GitLab auth, so I would imagine it was copied from the GitHub implementation by mistake. Most likely isn't supposed to be there.

**Comment by satrox28** [comment]
Any solution?. I tried to keep single provider only Gitlab, am experiencing the same issue after refreshing the page it asks to sign in again.

**Comment by Rugvip** [comment]
@satrox28 I'd expect the solution to be to remove the `disableRefresh: true` option, but there might be more to it. I believe the frontend is trying to refresh because from its point of view GitLab supports refresh

**Comment by satrox28** [comment]
@Rugvip removing `disableRefresh:true`, didn't solve the issue. After removing it, am unable to authenticate via Gitlab, getting below error.

`Missing refresh token`

**Comment by Rugvip** [comment]
Alright, needs a bit more work then. I guess you're on it @OrkoHunter? :grin:

**Comment by OrkoHunter** [comment]
Since I already created a branch - will find time this week 😄

**Comment by OrkoHunter** [comment]
@satrox28 Based on our Discord chat, wondering if you're still up for working on this and if I should assign this to you? Happy to support nevertheless. 🙂

**Comment by satrox28** [comment]
@OrkoHunter I didn't get to check on it had modified my auth to Google where I don't see the issue.
