### ISSUE TITLE
Add role to user

### ISSUE THREAD

**Issue by jcarres-mdsol** [backstage/backstage#3051]
The User model provides a name, email, picture. 
I think it would be very useful to add "role" , where role could be any string or we could provide the possible options like "tester", "manager", "architect", etc.

**Comment by freben** [comment]
So the semantics would be that this is the _primary_ role they are _employed_ as, right?

In more advanced scenarios I could picture this being a property on a relation instead - "A is-a-member-of B as-a C", where you could have different roles in different groups.

**Comment by jcarres-mdsol** [comment]
Very true.
Then it becomes more complicated but probably the most flexible improvement would be to make `memberOf` an object so you can add the role you use for each of the groups you are member of.

**Comment by freben** [comment]
The very first version of the relations model will not have support for additional data on relations, but it is something that we intend to add.

**Comment by Rugvip** [comment]
Could be very interesting to discover this kind of thing through analyzing contributions too. For example automatically tagging with known languages and technologies and so on.

**Comment by freben** [comment]
@Rugvip Could this actually be a label? Employee role, that is

**Comment by freben** [comment]
I mean in an output sense it totally could be. But even in an input sense?

**Comment by JoostvdB94** [comment]
Came across this feature request. Are there any plans to take this further? 
The method as mentioned by @freben would be ideal as we use Entra (Azure AD) as the source for users, but YAML files to specify relations between user and team. 

> So the semantics would be that this is the _primary_ role they are _employed_ as, right?
> 
> In more advanced scenarios I could picture this being a property on a relation instead - "A is-a-member-of B as-a C", where you could have different roles in different groups.

Having tags/labels to indicate someone's role is limited as one could have a different role in other teams. (e.g. A team member could also be a member of some technology guild or community) Having multiple tags and still provide an overview is almost impossible in my opinion.
