### ISSUE TITLE
Cloud Code support for Catalog entity types

### ISSUE THREAD

**Issue by timbonicus** [backstage/backstage#3064]
## Feature Suggestion

[Google Cloud Code](https://cloud.google.com/code) is a plugin for VSCode and JetBrains IDEs that features [autocomplete for k8s YAML](https://cloud.google.com/blog/products/containers-kubernetes/cloud-code-features-expanded-support-for-kubernetes-crds) files. This would be quite handy for Backstage Catalog files that use the k8s object format.

Cloud Code allows you to add your own resource types for autocomplete given a URL location of [CustomResourceDefinition](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/) schema files.

## Possible Implementation

The [catalog-model kinds](https://github.com/spotify/backstage/tree/master/packages/catalog-model/src/kinds) could be defined and validated by means of CustomResourceDefinition files, then these could be loaded as resource types for autocomplete in Cloud Code.

## Context

To accomplish swanky IDE autocomplete 😄

**Comment by freben** [comment]
Oh, interesting way of accomplishing it! Hm, we are modeled after the k8s format but are considering making at least one incompatible change, namely to allow complex (non-string) annotations. I wonder if there's a similarly easy way of getting going without being forced to be actual valid CRDs.

**Comment by freben** [comment]
Like, for example, linking to something akin to json-schema files instead
