### ISSUE TITLE
Core feature: is it a Software Catalog or a Service Catalog?

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3065]
## Feature Suggestion

In terms of the Backstage documentation, there's an entire section of the Core Features labeled as "Software Catalog" inferring that's a key feature.  However, opening that section, everywhere it's actually described instead as a "Service Catalog". And within the product itself, it also refers to Services of course.

The reason for this feature request is to help define:
**Is Backstage's core feature a "Service Catalog" or a "Software Catalog"?**

![image](https://user-images.githubusercontent.com/33203301/97030755-44634480-152d-11eb-91f6-d322e42eee18.png)

Inside of the documentation, there are 25 references to "software catalog" and 35 to "service catalog".  I wonder if an ADR would be appropriate here, but in discussing with my team I'm not sure if it's really one or the other.  Service of course drives to support of microservices, though some companies won't be using such an approach. Software is more generic, and more understood in the industry so I'm leaning that it seems it should be "Software Catalog".

As I pitch the product with my squad, getting alignment for me would be key.

Based on any discussions, happy to file a change to update it but wanted to drive the alignment.

## Possible Implementation

Update to the documentation sidebar nav, as well as some tweaks to the content.  Also would involve some minor code changes where, for example on the homepage, it says "Organization Name Service Catalog".

## Context

```bash
/mnt/c/github/backstage/docs(master)*$ grep -i -R "software catalog" | wc -l
25
/mnt/c/github/backstage/docs(master)*$ grep -i -R "service catalog" | wc -l
32
```

Specifically, the sidebar is defined as:

```json
"Core Features": [
      {
        "type": "subcategory",
        "label": "Software Catalog",
        "ids": [
          "features/software-catalog/software-catalog-overview",
          "features/software-catalog/installation",
          "features/software-catalog/configuration",
          "features/software-catalog/system-model",
          "features/software-catalog/descriptor-format",
          "features/software-catalog/references",
          "features/software-catalog/well-known-annotations",
          "features/software-catalog/extending-the-model",
          "features/software-catalog/external-integrations",
          "features/software-catalog/software-catalog-api"
        ]
      },
```

**Comment by stefanalund** [comment]
Hey @adamdmharvey -- thanks for raising this. This conversation has come up before, and I wrote down some of our reasoning in the following issue:

https://github.com/spotify/backstage/issues/2148

What do you think, does this make sense?

**Comment by freben** [comment]
So the instances of the other term, as pointed out by @adamdmharvey , should be renamed, right?

**Comment by adamdmharvey** [comment]
Indeed, I think some edits are necessary at least to reduce confusion to those users new to the system (myself, though I'm feeling more comfortable!).  Not only is there the difference in the doco, but there are the occasional potential tweaks in the UI, such as:

![image](https://user-images.githubusercontent.com/33203301/97516404-6b74a880-1969-11eb-9c4f-a0a5f2694ffd.png)

Based on your suggestions, I would propose:

* Change all instances in the application itself which are UI related stick to Service Catalog
* Change the wording in the documentation to say "Service Catalog", though retaining those places that make the clarity clear (e.g., keeping things like "the Backstage Service Catalog — actually, a software catalog, since it includes more than just services — is a centralized system")
* Retain the file naming structure `software-catalog` to not create broken links at this time, and future proof (it may come up as a difference, but it's less obvious than reading two different terms in the same reading session)
* Rename the section in the left nav to Service Catalog (a la `sidebar.json`)

Thoughts?  Happy to take a stab at this as necessary.

**Comment by jvaleriano** [comment]
Hi in the model documentation https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system Backstage has many entities but none of them is Software or Service. As it is today is a Component Catalog.
Regards,

**Comment by adamdmharvey** [comment]
Note to add on to @jvaleriano 's feedback, while there is no service `Kind` service, note for the `Kind:component` one of the meta data attributes is `service`:
https://backstage.io/docs/features/software-catalog/descriptor-format#spectype-required
(where it's service, library, website, etc.)

**Comment by adamdmharvey** [comment]
Some industry reference to help align:

https://www.gartner.com/en/information-technology/glossary/service-catalog
> A service catalog contains templates with specifications that define parameters and features of a service (such as bandwidth and speed). Compared to the product catalog, the service catalog describes product features in technical terms.

https://tylerjewell.substack.com/p/2021-developer-trends
> Trend #1: Emergence of the Service Catalog? Potential $500M Market That Redefines the Foundational Nature of Development Infrastructure.

Note Backstage is specifically called out in "Group 3" in Tyler's blog post.  FYI @stefanalund if you hadn't seen that yet.

But given your previous feedback, Stefan, would you agree there should be some minor refactoring to try to align back to true Service Catalog via my proposals above? (e.g., refactoring in the docs sidebar and minor PR tweaks to the UI)
