### ISSUE TITLE
Input validation of required fields when creating new component

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3067]
## Feature Suggestion

On the create new component screen, it indicates which fields are _required_ by the template. However, the interface does not actually require the user to enter them. The result will be a failure.

![image](https://user-images.githubusercontent.com/33203301/97039264-23edb700-153a-11eb-923d-7f35458697ab.png)

It may be preferable to validate the input and potentially not let the user proceed to the next step in the wizard, until the required fields are completed.  It properly errors out, though would be more user friendly to guide the user prior to encountering what looks like a more severe error (400 bad request).

This may be tangentially related to #2794, unless the focus of that is exclusively related to the modal popup _after_ completion of the wizard.

## Context

Reproducible steps:
1. Click create new component
2. Pick the React App template
3. On first screen where `Name*` is required, click _Next Step_
4. On second screen where `Owner*` and `Store Path*` are required, click _Next Step_
5. On the third screen, click _Confirm_
6. Error presented

![image](https://user-images.githubusercontent.com/33203301/97039138-f0ab2800-1539-11eb-95a0-e931db1b9d6d.png)

![image](https://user-images.githubusercontent.com/33203301/97039180-03256180-153a-11eb-834e-ef1f9477c506.png)

![image](https://user-images.githubusercontent.com/33203301/97039372-51d2fb80-153a-11eb-9262-2d9824bae4a6.png)

![image](https://user-images.githubusercontent.com/33203301/97039264-23edb700-153a-11eb-923d-7f35458697ab.png)

**Comment by Rugvip** [comment]
👍 , this should be tackled as part of https://github.com/spotify/backstage/issues/2771.

It's also very much related to https://github.com/spotify/backstage/issues/2832. As there I think adding validation as part of JSONSchema makes sense: https://json-schema.org/draft/2019-09/json-schema-validation.html

**Comment by erictnilsson** [comment]
I'm failing to reproduce the bug @adamdmharvey, arent the required fields already validated? This is what pops up when i skip Name*: 
<img width="1160" alt="Screenshot 2020-10-23 at 22 17 00" src="https://user-images.githubusercontent.com/16206098/97050519-cc713a80-157d-11eb-81df-930e1d328149.png">

How are you circumventing this?

**Comment by adamdmharvey** [comment]
Create question!!  I'm on https://github.com/spotify/backstage/commit/e83b9753448f9b111c1048b601ae40b8de52bb23 if it helps?

```
/mnt/c/github/backstage(master)*$ git describe --tags
v0.1.1-alpha.25-383-ge83b9753
/mnt/c/github/backstage(master)*$ git log --oneline
e83b9753 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #3046 from RoadieHQ/feat/add-security-insights-plugin
c8ed8b6c Update security-insights.yaml
01f536a3 Merge pull request #3060 from ayshiff/feat/cli-test-mock-fs-2
61b4deec test(cli): add mocked file content + refactor
162c3089 Merge pull request #3038 from erictnilsson/master
```

**Comment by erictnilsson** [comment]
Hmmm... The behaviour is still the same for me on `e83b975` 🤔

**Comment by benjdlambert** [comment]
What browser are you using? Wondering if this is something related to the library using HTML5 validation for the form that maybe your browser doesn't respect. I get this in Chrome:
<img width="1792" alt="Screenshot 2020-10-25 at 02 26 36" src="https://user-images.githubusercontent.com/3645856/97096256-c3f62e00-1669-11eb-8c31-f9030e4e19f6.png">

**Comment by benjdlambert** [comment]
I wonder if we're hitting this: https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/.

Specifically:
```
By default, the form uses HTML5 validation. This may cause unintuitive results because the HTML5 validation errors (such as when a field is required) may be displayed before the form is submitted, and thus these errors will display differently from the react-jsonschema-form validation errors. You can turn off HTML validation by setting the noHtml5Validate to true.
```

**Comment by adamdmharvey** [comment]
Apologies, I failed _Intro to Web App Issue Reporting_.  😊 

* Windows 10 1909
* Microsoft Edge 86.0.622.48 (which is based on Chrome)

And @benjdlambert 's feedback was interesting, so I also tried with:

* Chrome 86.0.4240.111 (real Chrome)

And same error, no validation is performed.  So for me this may not be browser related.

**However**, I may just introducing an edge case (or a newbie failure case) based on where I am in the setup/configuration process, and by that I mean: I don't have a working scaffolder/templater yet. My system is not yet able to create GitHub Enterprise repos and fill them in with template content, so I wonder if the element doing the validation is tied into that package?  (I'm still learning all the terminology here, but something about the scaffolder?)

I haven't yet figured out how to properly configure my `app-config.local.yaml`. I've tested both with a GitHub PAT for my personal account on my GHE instance, as well as a GitHub app, and I can authenticate with OAuth as my user ID into Backstage, but I've not yet been able to actually get the scaffolder work as I don't understand it well enough yet and didn't get it through the getting instructions just yet.

In my scenario, perhaps the proper thing would be to change how the template page looks?  Something along the line of a horizontal warning saying this Backstage instance is not yet configured to support templates, and thus only let me choose register existing component (which I do have working)?  I also wonder if there may be users who want to use Backstage and literally NOT use the scaffolder at all, only allowing registering from pre-existing components, and in those cases do the validators work?

Not sure if this helps to point to where the issue may be better, and to be fair stabbing at the dark a bit.

**Comment by adamdmharvey** [comment]
To note, my failure to have templates working likely relates to my not (yet) using a Docker image to host the preparer backend, which I assume is used to create the repo content needed to actually push up? So anyway, since my preparer backend is broken, that may be why the validation isn't working..

**Comment by adamdmharvey** [comment]
Ah - better info.  The validation works beautifully _if_ I generate an app (i.e., `npx blah blah`) and run that:

![image](https://user-images.githubusercontent.com/33203301/97134260-265f3500-1723-11eb-9b25-6d0cef56bdf0.png)

The validation does NOT kick in if I just do the raw `yarn start` out of the cloned Git repo, a la https://backstage.io/docs/getting-started/running-backstage-locally#clone-and-build.

As a new user, it would seem to me a bug, though I'm sure from a real perspective users should never be running the example Git code and always be creating their own app.

**Comment by benjdlambert** [comment]
hmm - this is interesting. For me I only have it cloned and it works for me. 

The validation is done client side and server side, but it appears that the client side validation isn't working. I will take a look at this a little more to see if I can replicate this afternoon.

**Comment by benjdlambert** [comment]
@adamdmharvey so I tried with a fresh clone of `spotify/backstage`, did a `yarn install` and then ran the frontend and backend and on the templates that I could choose, if I don't put any values in the validation works as expected.

![Screenshot 2020-10-26 at 22 49 31](https://user-images.githubusercontent.com/3645856/97232704-f163e880-17dd-11eb-8542-ae86ba9339bc.png)

Is there something I'm missing?

Could you list your exact steps to reproduce? Maybe you could run `yarn cache clean` and do a fresh `yarn install` if theres something corrupt in your `yarn cache` or something? I'm really just reaching here as I don't know what the problem could be other than some bad dependency?

**Comment by adamdmharvey** [comment]
Not having this issue anymore, and I've updated numerous times so assuming maybe this was a temporary issue or environmental. Closing for clean up.

**Comment by benjdlambert** [comment]
Sweet - good to know!
