### ISSUE TITLE
[RFC] Stability Index

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#3076]
**Status:** Open for comments

## Need

Backstage is heading out of alpha and on to a path to an eventual long-term stable release and version `1.0`. The community and ecosystem is growing at an increasing rate, and we want to provide a solid foundation for everyone building things in, with, and around Backstage.

At this stage of the project we also want to be able to move fast and break things. There are many areas where we want to be able to revise design decisions, often based on valuable feedback from the Backstage community! We also want to be able to ship new features and systems but keep iterating and gathering feedback before they reach a stable API.

Because of the rapid evolution combined with the stabilization efforts, there's uncertainty in what parts of the project are stable and which are not. Regardless of whether you're contributing to the project directly, setting up your own Backstage, or building plugins, you will be using various parts of the project with differences in stability. Many API surfaces of Backstage are reasonably solid and are unlikely to see any big breaking changes, while others are much more uncertain and may even have planned breaking changes that haven't shipped yet.

There is clearly room for more guidance both for contributors and users, as well as commitment from the core team to ensure stability of certain parts of the platform.

### Stability Index

We introduce a Stability Index, similar to [the one used by Node.js](https://nodejs.org/dist/latest-v12.x/docs/api/documentation.html#documentation_stability_index). It is a score assigned to a subset of the project, indicating the level of maturity of the API and the commitment to backwards compatibility. However, because of the current phase of the project, and essentially all API surfaces being experimental, we use a slightly different implementation. Instead of the score indicating a perceived stability, a higher score is instead a commitment to providing a smoother upgrade path for users, through both better documentation and backwards compatibility. Importantly, the Stability Index does not supersede [semver](https://semver.org/), meaning we will still adhere to semver and only do breaking changes in minor releases as long as we are on `0.x`.

My proposal is a 0-3 score as follows, each point building on top of the previous one:

0. Breaking changes are noted in the changelog, and documentation is updated.
1. The changelog entry includes a clearly documented upgrade path, providing guidance for how to migrate previous usage patterns to the new version.
2. Breaking changes always include a deprecation phase where both the old and the new APIs can be used in parallel. This deprecation must have been released for at least two weeks before the deprecated API is removed in a minor version bump.
3. The time limit for the deprecation is 3 months instead of two weeks.

TL;DR:

0. There's a changelog entry.
1. There's a migration guide.
2. 2 weeks of deprecation.
3. 3 months of deprecation.

Note that these are commitments to a minimum, as in we may for example still provide a deprecation path even if an API has a stability score of 1.

I am also suggesting that we do not keep this system in place after version `1.0`, at least not in its current form. The suggestion is based on something that makes sense for the current state of the project, and may even evolve before we reach version `1.0`.

There are some intricacies of employing these rules across the board, as there are various different kinds of breakages that behave in different ways. So there are a couple more points to help guide the process:

- Changes that cause breakages outside the main repo without the user doing a version bump should always have a deprecation path. This includes things like changing our example catalog yaml files, which people rely on directly through GitHub.
- Breaking changes only apply to public API. In the case of TypeScript packages, the public API is any types exported by the package, except explicit exceptions like marking a particular function experimental or private.
- In cases where it is not possible to provide a smooth deprecation path for APIs with a score of 2 or above, the breaking change must be as apparent and clear to the user as possible. It might for example include an error being thrown with clear instructions for how to migrate, or even suggest a new code snippet.
- Changes to templates, such as the `create-app` package, are not considered breaking changes. The stability score refers to the interaction with the template itself.

### API Surfaces

For the index to be useful we need to make a sane split of the project in to smaller slices. I suggest that we start the division with each package being its own surface, where some packages are further divided into different sections. We may divide or merge sections as necessary over time, in order to provide the granularity we need.

We also only assign scores to the packages and plugins in the main Backstage repository, and while other plugins are welcome to adopt the Stability Index, it is nothing we would enforce in any way.

Private packages such as the `example-app` or `storybook` are excluded.

### Implementation

A new documentation page is added with a full map of the project, with a list of all packages and sections. Each package or section includes a short description, the stability index, and possibly a motivation. We could also use this file as a place to note deprecations for removal in the future. It might look something like this:

> # Backstage Stability Index
>
> ## Packages
>
> ### @backstage/catalog-model
>
> Contains the core catalog model, for usage in both the frontend and the Backend.
>
> Stability: 2. The catalog model is evolving, but because of the broad usage we want to ensure some stability.
>
> ### @backstage/config
>
> Provides the logic and interfaces for reading static configuration.
>
> Stability: 2
>
> ### @backstage/core
>
> #### Section: React Components
>
> All of the React components exported from `src/components/` and `src/layout/`
>
> Stability: 1
>
> #### Section: Plugin API
>
> The core plugin API and the way plugins expose functionality to Apps.
>
> Stability: 2. There are planned breaking changes around the way that plugins expose components for apps.
>
> Deprecations:
>
> - `v0.2.1` Deprecated the Foo API, it will be removed in a release after 7th Dec 2020.
>
> #### Section: App API
>
> The APIs used in the app, such as `createApp`.
>
> Stability: 2
>
> ...
>
> ### @backstage/dev-utils
>
> Provides utilities for developing plugins in isolation.
>
> Stability: 0. This package is largely broken and needs updates.
>
> ...
>
> ## Plugins
>
> Plugins are rarely marked as stable as the `@backstage/core` plugin API is under evolution.
>
> ### @backstage/catalog
>
> Stability: 1
>
> ...

## Risks

A commitment to stability will also mean greater friction for both contributors and for the core team to manage the project as a whole. For this reason we would need to carefully assess what scores we assign, as over-promising may lead to significant overhead.

Tied to the above risk is the fact that managing the deprecations is a bunch of work. Realistically this is necessary regardless of whether we introduce an API Stability Index or not, as long-term stability is hugely important for a project like this.

Another risk is that the division of the project is too granular, coarse, and/or confusing. I'm hoping we'll be able to work out a good model though, and we can definitely keep evolving it over time too.

## Alternatives

The scoring system is based around our commitment to smoothing out breaking changes. We could take the approach of scoring based on the perceived stability of the API instead, basically 1 = extremely likely to change and 5 = very unlikely to change. I find that it is easy to not be careful enough when assigning that kind of score though, and that a system with some actual implications of each score is more effective in achieving the intended results.

There are many alternatives to the suggested implementation too. We could for example be much more granular and assign a score for type and method exposed by packages in JSDoc, or move the scores to each package README. I feel that a single file with all packages and sections is likely to be the most valuable at this point. It ensures that we keep the total length and time of reading down, while also providing a single point for a quick overview of the project.

**Comment by dtuite** [comment]
This is my first time coming across this stability index idea. It sounds good.

Should it be be implemented with a testing plan to help ensure that commits are not accidentally sending out unexpected breaking changes to packages which are intended to be stable?

**Comment by Rugvip** [comment]
@dtuite Yep, agree that we will need some CI checks to make sure we maintain backwards compatibility. Haven't explored this in-depth yet, but https://api-extractor.com/ seem interesting for ensuring backwards compatibility, along with many other things :grin:

As we start getting closer to stable APIs I'd love to get some higher level and mostly frozen unit tests in place too, testing packages using their exports only.
