### ISSUE TITLE
Question about adding a new plugin

### ISSUE THREAD

**Issue by SurjitCS** [backstage/backstage#3091]
We have a Java project that we use for Automation testing using Rest Assured and Selenium which is currently hosted in Azure DevOps. We are in process of exploring Backstage. Could you please guide us to achieve incorporating our automation java code in backstage or guide us with some training/tutorial which would be useful. Thanks in advance!!

**Comment by OrkoHunter** [comment]
Hey @SurjitCS ! I assume that the project you are using can be added as a plugin in Backstage. And then when you deploy Backstage, the plugin will do the job.
Could you also share the name of this Java project? We can create another issue and track the progress there.

Plus, welcome to the community! :)

**Comment by SurjitCS** [comment]
Thank You! do we have any videos which can guide us and one more thing in Demo instance i was trying to create Component but  all time I used to get error at publish template time.
Thanks for the help!
