### ISSUE TITLE
Double border on CI/CD widget

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#3093]
There is a double bottom border on the Recent Workflow Runs card when it only has a small number of runs in it.

![Screenshot 2020-10-26 at 09 20 35](https://user-images.githubusercontent.com/562403/97155136-cdb48a00-176c-11eb-9f5d-dba46e31568d.png)

**Comment by dtuite** [comment]
Probably a candidate for Good First Issue. I can't add labels.

**Comment by abhishekjakhar** [comment]
Can I pick this up?

**Comment by freben** [comment]
Sure!

**Comment by abhishekjakhar** [comment]
@dtuite I am not able to see the **Recent Workflow Runs** section when I run the backstage application using **yarn dev**. I guess I have not setup my application properly, could you please tell me what else do I need to do to see other features like **Recent Workflow Runs**, **Auditing** etc.

**Comment by abhishekjakhar** [comment]
How could I develop something like https://demo.roadie.so/catalog locally?

**Comment by dtuite** [comment]
@abhishekjakhar I recommend creating a GitHub repo with some GitHub actions configured and only running one build just to get some sample data.  You can fork https://GitHub.com/RoadieHQ/sample-service if you like.
