### ISSUE TITLE
[Plugin] FOSSA

### ISSUE THREAD

**Issue by dhenneke** [backstage/backstage#3094]
## Summary

We use [FOSSA](https://fossa.com/) to scan our dependencies for Open Source licensing issues. Each service has a [project dashboard](https://app.fossa.io/projects/git%2Bgithub.com%2Ffossas%2Ffossa-cli) and there is an [API](https://reference.fossa.io/) to get details about the scans.

The plugin could:
1. Show the current status and the issue count.
2. Tell more about the licensing issues (number of flagged, denied, or unlicensed dependencies).

We currently have a plugin that does **1.**:
![image](https://user-images.githubusercontent.com/720821/97156451-ffcae980-1776-11eb-9e8a-354e3c6a6970.png)

We can contribute it as Open Source if others are interested in it. We just miss some fine tuning and a proper documentation.

btw: This screenshot shows the licensing issues with our internal backstage installation. I can't provide a public link to the FOSSA dashboard but we might come back with some issues 😉. Though some of them might be false-positivies since FOSSA doesn't know _how_ we use the dependencies.

**Comment by Fox32** [comment]
Would be a good candidate to integrate with a Status API #2292

**Comment by stefanalund** [comment]
Would be great if you guys wanted to release this. Thanks in advance!

**Comment by dtuite** [comment]
100% would love to see this open sourced.
