### ISSUE TITLE
TechDocs: Add support for different CI providers

### ISSUE THREAD

**Issue by soapraj** [backstage/backstage#3097]
- Circle CI
- Github Actions

**Comment by erikxiv** [comment]
Travis-CI? Specific support might not be needed if tooling is easy to use from any CI tool, though

**Comment by OrkoHunter** [comment]
@erikxiv Exactly! There will be CLI commands that could build on any kind of environment.

However, there can be additional features specific to CI provider like a GitHub actions template which one can use with few configs in the GitHub workflows.

**Comment by andrewthauer** [comment]
For CircleCI this could be provided as an [Orb](https://circleci.com/developer/orbs).

**Comment by erikxiv** [comment]
Fyi: I did a naive implementation of a github action here: https://github.com/erikxiv/techdocs-action. A more serious one would probably want to align better with techdocs backend supporting different storage vendors though. (Let me know if I should unpublish from marketplaces as being confusing, thought it might be helpful for likeminded adventurers)

**Comment by OrkoHunter** [comment]
@erikxiv Appreciate you sharing your GitHub Action. :) Yes, the official one will align with `techdocs-backend` and the external storage support. That being said, you don't have to unpublish it. Community building tools around Backstage is good news for all of us.
