### ISSUE TITLE
TechDocs: Eject the independent packages into new repositories on github.com/backstage

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#3111]
We will shortly be moving to the dedicated [`backstage`](https://github.com/backstage) org on GitHub. Some of TechDocs packages can make good use of living in separate repositories out of this mono-repo. Note that, our main plugins [`techdocs`](https://github.com/spotify/backstage/tree/master/plugins/techdocs) and [`techdocs-backend`](https://github.com/spotify/backstage/tree/master/plugins/techdocs-backend) will stay inside the Backstage mono-repo.

The proposed new repositories are following -

- [x] **1. techdocs-container**

_What is it?_
The Docker container responsible for converting markdown source into static site.

_Current home_
https://github.com/spotify/backstage/tree/master/packages/techdocs-container
_New home_
https://github.com/backstage/techdocs-container

_Benefits of moving to a new repository?_
- Independent release process on DockerHub. Since DockerHub depends on git tags for releases, it is hard to decouple the release while being in the mono-repo. This results in a number of docker image tags without any actual difference.
- [DockerHub](https://hub.docker.com/r/spotify/techdocs) will render correct README of this package instead of the root Backstage README.

_Progress_
- [x] Create the repository
- [x] Test a new release.
- [x] Remove from existing mono-repo

---

- [x] **2. techdocs-cli**

_What is it?_
CLI for local development of a techdocs site. Currently WIP.

_Current home_
https://github.com/spotify/backstage/tree/master/packages/techdocs-cli
_New home_
https://github.com/backstage/techdocs-cli

_Benefits of moving to a new repository?_
More visibility maybe? This package can use some _love_ and turn out to be a very useful tool. There are no strong reasons to keep it in the mono-repo.

_Progress_
- [x] Create the repository
- [x] Test a new release on npm with new repository (v0.2.1)
- [x] Remove from existing mono-repo
- [x] Configure dependabot for the repository (so that @backstage/cli is updated)

---

3. [x] **3. mkdocs-techdocs-core**

_What is it?_
Core mkdocs plugin used by TechDocs. (Python package)

_Current home_
https://github.com/spotify/backstage/tree/master/packages/techdocs-container/techdocs-core
_New home_
https://github.com/backstage/mkdocs-techdocs-core

_Benefits of moving to a new repository?_
Decoupling releases. Has independent use case in the community. No strong reasons to keep it in the mono-repo.

_Progress_
- [x] Create the repository
- [x] Test a new release on PyPi
- [x] Remove from existing mono-repo

---

4. [x] **4. mkdocs-monorepo-plugin**

_What is it?_
MkDocs plugin to support building docs in mono-repo. (Python package)

_Current home_
https://github.com/spotify/mkdocs-monorepo-plugin
_New home_
https://github.com/backstage/mkdocs-monorepo-plugin

This package already exists out of the mono-repo. The benefit of moving this from spotify/ to backstage/ will be keeping all the TechDocs projects close. That is the only benefit as I can see. 

_Progress_
- [x] Moved the repository
- [x] Test a new release via GitHub workflow, to make sure tokens are there

---

@spotify/backstage-core Let us know if there are any comments or concerns. cc @spotify/techdocs-core

**Comment by OrkoHunter** [comment]
Question: While we are at this change, can we rename `mkdocs-techdocs-core` to add the word `plugin`?
We already have `mkdocs-monorepo-plugin`. So we will maintain consistency. And IMO `mkdocs-techdocs-core` does not convey very well that it is just a MkDocs plugin and not the "core" of techdocs.

@emmaindal @hooloovooo

**Comment by OrkoHunter** [comment]
@stefanalund Let us setup the `techdocs-core` team on https://github.com/backstage (i.e. invite the members), and then we can setup the repositories needed here. We are ready to do it as soon as possible, and as it fits in the plan. :)

**Comment by stefanalund** [comment]
@OrkoHunter you, @emmaindal, @soapraj and @hooloovooo have now been invited. Please let me know if it looks good!

**Comment by OrkoHunter** [comment]
This is 100% complete.💥 🎉
