### ISSUE TITLE
[Scaffolder] Support adding scaffolded components from Azure DevOps and GitLab to catalog

### ISSUE THREAD

**Issue by mfrinnstrom** [backstage/backstage#3138]
## Feature Suggestion

Right now the scaffolder is hard-coded to construct a GitHub url for newly scaffolded components and try to add them to the catalog. This should also work for Azure DevOps and GitLab. I haven't checked checked GitLab but Azure DevOps does not work right now.

## Possible Implementation

Move logic for adding scaffolded components from the frontend to scaffolder-backend. Also let the different publishers construct the final url to `catalog-info.yaml` since they differ between the different providers.

## Context

We want scaffolded components in Azure DevOps to be available in the catalog.

**Comment by benjdlambert** [comment]
@mfrinnstrom wanna pick this up yourself after we've got #2881 merged?

**Comment by mfrinnstrom** [comment]
@benjdlambert we need it so why not

**Comment by regicsolutions** [comment]
Would be great to also have this feature for Bitbucket Server!

**Comment by mfrinnstrom** [comment]
@regicsolutions There doesn't seem to be any support for Bitbucket Server at all in Backstage right now. I'm trying to make that easier to add through #3313 &  #3351. If there had been initial support I could probably have added this functionality for that as well. I don't know Bitbucket Server well enough to add all of it though.

**Comment by mfrinnstrom** [comment]
@benjdlambert do you want to keep this issue around or should new ones be created for the things I didn't include in the mentioned PRs?

**Comment by benjdlambert** [comment]
Think we can close this and create issues for new stuff as and when it's needed.

**Comment by mfrinnstrom** [comment]
Closing this then. @regicsolutions you might want to open a new issue for Bitbucket Server instead.
