### ISSUE TITLE
feature(scaffolder-ui): Full screen logs.

### ISSUE THREAD

**Issue by Marvin9** [backstage/backstage#3169]
Ability to view these logs in full screen.

![Screenshot from 2020-10-30 10-14-48](https://user-images.githubusercontent.com/17699717/97660984-1e8fef80-1a99-11eb-974f-44ac83baab92.png)

## Possible Implementation

Adding additional component [here](https://github.com/spotify/backstage/tree/master/plugins/scaffolder/src/components/JobStage) which may be another ```Dialogue``` but full screen.

## Context

Something like this one?

![Screenshot from 2020-10-30 10-31-20](https://user-images.githubusercontent.com/17699717/97661802-5b5ce600-1a9b-11eb-8212-ceaefb4dc944.png)

**Comment by stefanalund** [comment]
@Marvin9 good idea! Do you wanna work on this yourself? 💯

**Comment by Marvin9** [comment]
Yes  🕶

**Comment by stefanalund** [comment]
@Marvin9 awesome, I've assigned you
