### ISSUE TITLE
Question: Use of JSON Forms Rule feature in Scaffolder

### ISSUE THREAD

**Issue by hendrikmaus** [backstage/backstage#3175]
_I couldn't find any existing issue on the topic, so here goes a question._

The [documentation](https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template) of `backstage.io/v1alpha1`'s `Template` resource states:

> (...) and also for documenting the variables that the template requires using [JSON Forms Schema](https://jsonforms.io/).

Is there support to use the [rule](https://jsonforms.io/examples/rule) feature of JSON Forms Schema in order to control the enablement of fields?

**Comment by benjdlambert** [comment]
Hey @hendrikmaus, 

so It looks like the react library we use to implement json schema forms doesn't support the rule syntax after trying their playground with the json schema form example.

Maybe you could use some alternative they have in their examples though?

https://rjsf-team.github.io.

Maybe you could also raise an issue on their repo too to track this feature, as I couldn't find it in closed issues or PRs?

**Comment by hendrikmaus** [comment]
Thanks for getting back to me, I will have a go at it.

Unfortunately your link yields a 404, I reckon you meant https://github.com/rjsf-team/react-jsonschema-form

**Comment by benjdlambert** [comment]
@hendrikmaus yep, apologies that's the link!
