### ISSUE TITLE
Database section in Docs needs updating

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3186]
## Feature Suggestion

The docs section on databases states Lighthouse supports PostgreSQL, but that the catalog is only SqlLite based.  I believe that's no longer accurate? There are two issues referenced, both of which are now closed, and looks like a ton of great work to enhance the database connectivity. My understanding is the system as a whole now supports BOTH PostgreSQL and Sqlite3 for the main app?

https://backstage.io/docs/overview/architecture-overview#databases

I'm doing database setup myself right now, so was just walking through this section and trying to understand it more, but I'm not knowledgeable enough yet to update this chapter so thought I'd point it out in case someone who is might be able to take a stab!!

![image](https://user-images.githubusercontent.com/33203301/97747517-7bec6680-1ac2-11eb-8ddb-4fe71cd94ecc.png)

## Possible Implementation

* Removal of the links to closed issues (possible replacement to others if there are open ones?)
* Statement that the system now supports PostgreSQL I believe?

## Context

* May or may not relate to https://github.com/spotify/backstage/issues/1169

**Comment by freben** [comment]
Thanks for reporting! Made https://github.com/backstage/backstage/pull/3250 with updated wording.
