### ISSUE TITLE
Add support to deploy Backstage as Immutable Web App

### ISSUE THREAD

**Issue by geototti21** [backstage/backstage#3194]
## Feature Suggestion

👋 hey, this is a feature request for Backstage, to deploy it as an[ Immutable Web App](https://immutablewebapps.org/). At the moment if you want to do this I don't believe is possible with the existing `Config` API as we want to read on runtime config from the `window` object as it is described in the Immutable Web App example. It will great if we can somehow add an option to Backstage to read config from the `window`.
 

## Possible Implementation

I think if we provide an option to the app-config.yaml to tell the config to read from the "window" will be ideal. 

As this is not supported yet we implemented the following workaround:

Have an `app-config.build.yaml` with an immutable key reference (eg `IMMUTABLE_ENV_APP_TITLE`), this is just a placeholder key that will be replaced at compile time.
```yaml
    app:
      title: IMMUTABLE_ENV_APP_TITLE
```
And after we "build" the bundles we run a script that will replace the `"IMMUTABLE_ENV_APP_TITLE"` with `window.env.APP_TITLE` and also creates index.html specifics for environments where we set the environment-specific values. e.g.
```html
    ........
    <body style="margin: 0;">
    <script>
      env = {
        APP_TITLE: "Backstage (staging)",
      }
    </script>
    ........
```

## Context

Appreciate your help 😄

**Comment by Rugvip** [comment]
Thanks for bringing this up, it's a good idea! :grin: It's actually already being worked on as followup to #2889, with https://github.com/spotify/backstage/issues/2889#issuecomment-708398400 providing some more info. The idea is to make the [default config loader](https://github.com/spotify/backstage/blob/019278935a91b32a4c9089292bfea924d4f353f6/packages/core/src/api-wrappers/createApp.tsx#L45) also search for config on the `window` object, for example a `window.__BACKSTAGE_APP_CONFIG__`, and if it exists, pick it up. That's along with some basic support for the backend to load the the config at runtime.

@martina-if I'm thinking we track the work here, alright if I assign this issue to you?

There's actually basic support for this feature already though, as you can set `APP_ENV_<config-key>=<config-value>` when serving with both our nginx image and the `app-backend` plugin. The work being done is to allow config files to be used in addition to that.

**Comment by geototti21** [comment]
Thanks @Rugvip, really glad that this is already planned 🎉 . I saw the `APP_ENV_<config-key>=<config-value>` but as we deploy backstage to S3(as webserver) we don't have the option to do that.

**Comment by martina-if** [comment]
@Rugvip yes, please, assign it to me for now and we will see who in the Roadie team works on it :)

**Comment by Rugvip** [comment]
@iain-b, need a comment on this issue to be able to assign it 😅

**Comment by iain-b** [comment]
I'm happy to take that 😄

**Comment by geototti21** [comment]
Thank you all 🙌
