### ISSUE TITLE
Flexible Deployment Model with NextJS

### ISSUE THREAD

**Issue by jd-carroll** [backstage/backstage#3195]
## Feature Suggestion
We are looking to build a site similar to Backstage with almost identical use cases.  (Nice podcast btw @stefanalund!)  One of our use cases is rendering dynamic content, stored as markdown, which is updated multiple times per day.  Think real-time documentation.  It would be unrealistic to trigger a full build process each time there is a content update.

It would be great if Backstage became more opinionated on how the front-end app is served.  Specifically, I think it would be great if the front-end app adopted NextJS to serve all web assets.  The added capabilities within NextJS would unlock the type of dynamic content use cases I am looking into.

Note: I don't think any of NextJS's API capabilities should be utilized if NextJS is adopted.  I think the current app vs backend separation is pretty elegant.

## Possible Implementation
I'm not sure what all it would take to implement NextJS within the current code base.  My assumption is that there would be a number of manual tasks but nothing architecturally would need to change.

## Context
I am still new to Backstage, so maybe there is a way to do this already.  Although, any way that is currently supported probably cannot utilize the full power of NextJS given the missing NextJS specific `<Link>` tags.

Unfortunately, this particular use case (real-time docs) will prevent us from adopting Backstage.  So if there is support for an idea like this, we would likely be able to contribute to the implementation.  Otherwise, we will have to go our own way. (Which would be a bummer! 😞 )

**Comment by OrkoHunter** [comment]
Live rendering of Markdown content, seems like an amazing flavour of [TechDocs in Backstage](https://backstage.io/docs/features/techdocs/techdocs-overview) 😄

**Comment by Rugvip** [comment]
@jd-carroll As @OrkoHunter pointed out one of the core features of Backstage is TechDocs. It enables you to take markdown content in Git and render it in the frontend. It sounds like that it is either pretty much exactly what you need, or that it could be adapted for what you need.

Was there any particular part of the Next.js tooling that you where interested in though, like MDX and file-system based routing?

**Comment by jd-carroll** [comment]
The most appealing feature of Next.js is the capability to compile/render markdown files on the fly.  Unless I'm missing something, I'm pretty sure the current process publishing markdown content in Backstage is something along the lines of:
* Edit markdown file
* Commit changes into repo
* **Build whole Backstage project**
* Publish newly built web assets to web server

Whereas with Next.js the process would be something like:
* Edit markdown file
* Commit changes into repo

That's it, no additional steps would be required.  Maybe this is already possible with Backstage and I'm just not getting it (if so, please point me in the right direction).

It's probably also useful to know that we are building much more than a developer portal.  We are building the next-gen platform for business operations at the company, and I am thinking of Backstage as the backbone for this platform.  Our use case might be too specialized / customized for the Backstage project, but it would be awesome to try and figure this out!

**Comment by Rugvip** [comment]
The `edit -> commit` flow is exactly what TechDocs enables, but it's geared towards technical documentation and tied to the Catalog. There's definitely a possibility to reuse much of that infra for more general purpose pages if that's what you're looking for though.

My main question would be whether you're looking for MDX features and being able to write Markdown with access to a component library, or whether standalone markdown is completely fine. I know TechDocs have the addition of add-ons in the roadmap, which would allow you to provide custom components and tags as part of Markdown. MDX would be another level of flexibility but much more complex.

Glad to hear you're looking at Backstage for that purpose though, happy to bounce ideas!

**Comment by jd-carroll** [comment]
MDX is a really cool feature and is something that I am considering, but it is definitely not a day 1 feature and would be happy to wait for enabling capability within Backstage.

I think the ability of re-using the TechDocs infra is exactly what I am looking to do.  Could you point me to some documentation / code where I could start to understand how that would work?

Also, the `edit -> commit` capability of TechDocs is very not clear to me and the process I outlined above is a little incomplete.  The real process I am looking for is `edit -> commit -> viewable in any browser` and ideally that would happen without triggering any type of CI build.  If the "viewable in any browser" aspect is currently available with TechDocs could you point me to some documentation or even code where I could understand that?

**Comment by hooloovooo** [comment]
@jd-carroll I'm not sure i understand exactly how you see that as working. The main issue we have now is that we always need to run it through a static site generator before viewing the docs. The thing that forces that flow right now is that the reader is built around MkDocs and reading remote HTML pages. (We try to explain the current setup in the docs here. https://backstage.io/docs/features/techdocs/architecture)
I think the short term solution in your case could be to set up the build step to run on your CI/CD build instead of having techdocs-backend handle it. We briefly mention how it can be done from here https://backstage.io/docs/features/techdocs/getting-started#setting-the-configuration
We do have on the roadmap to provide better tools and documentation for how to build your doc sites within your own build tools. :)

That said, we have been talking about different approaches. We might settle on a way to view docs that takes a markdown (or other supported format) directly without needing to pass it through a build step on the server side down the line. This would allow a flow more like the one you're proposing. :)

**Comment by Rugvip** [comment]
@jd-carroll, pop by [Discord](https://discord.gg/EBHEGzX) and we can set something up!

**Comment by freben** [comment]
Should we update this issue after the meeting?

**Comment by Rugvip** [comment]
@jd-carroll Gonna close for now, let us know if you want to re-open
