### ISSUE TITLE
[RFC] Plugins should support custom EmptyState components / instructions

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#3217]
**Status:** Open for comments

## Need

The new `EmptyState` and `MissingAnnotationEmptyState` components are very helpful. However, the current default ones don't necessarily convey intuitive (or complete) instructions for an individual organization. There might be some additional steps before adding any catalog file annotations would be applicable (e.g. CI/CD configuration). It would be nice to be able to customize the content of these components.

_NOTE_: This is currently possibly by customizing the EntityPage components. However, it requires wrapping tabs and widgets in order to customize the empty state. Having a native/common pattern that plugins use that allow empty state to be customized would be very helpful.

## Proposal

My first reaction would be to have both the plugin `Router` and any `Widgets` expose a new prop that allows you to override the default empty state component:

```tsx
<SonarQubeCard emptyState={MyOrgSonarQubeEmptyState} />
// or
<DocsRouter emptyState={MyOrgDocsEmptyState} />
```

## Alternatives

Longer term, I think it would be beneficial to see if the `EmptyState` / `MissingAnnotation` components could be extended with additional information. However, I haven't really thought through what that might look like.

## Risks

There doesn't see to be a risk in doing this as the default empty state would not need to change and the new `emptyState` props would be optional. It's purely introducing a pattern to allow customizing and/or overriding the empty state.

**Comment by freben** [comment]
Maybe this could fit in the app-components concept, as with the `SignInPage`. https://github.com/backstage/backstage/blob/master/packages/app/src/App.tsx#L45

This doesn't let you customise on a per-page basis, but may work well enough for the default behaviour. What do you think?

**Comment by andrewthauer** [comment]
@freben - I'm not sure how useful that would be. I'm noticing that each plugin integration that requires manual a configuration action requires a different series of steps. For the ones that don't, the current default empty page components are unusually sufficient.

**Comment by freben** [comment]
Heh, "unusually sufficient" was an amusing typo. :)

Yeah you are right, mostly the EmptyState is a fit for this and does provide less value.

**Comment by Rugvip** [comment]
This takes me back to our ideas in https://github.com/backstage/backstage/issues/1536#issuecomment-665669837 (which are yet to be finalized 😅).

Possibly enabling something like this to override the default empty state component:

```tsx
<DocsRouter>
  <MyOrgDocsEmptyState />
</DocsRouter>
```

**Comment by andrewthauer** [comment]
@Rugvip - I agree the child pattern is nicer from a readability perspective, but doesn't it put more work on each component that needs to implement it? Unless there is a plan to make some generalized utilities for this pattern maybe.

**Comment by Rugvip** [comment]
@andrewthauer There are potential plans for making some generalized utilities for this pattern maybe :p

**Comment by freben** [comment]
Haha, that wasn't vague :D

**Comment by adamdmharvey** [comment]
Related, but something we've considered, is if I have say 20 people using Backstage, and one person onboards a component, obviously that component is now visible to all 20 people.  That means if 20 of them search for or find that component, and say click on one of the tabbed features or sees a widget, the instructions are regarding the missing annotation. But theoretically, 19 of those 20 users don't care - they aren't fixing it. It would be the component owner. (bear with me on numbers and/or concepts about teams digging in to help each other :) )

So I wonder if the missing annotation bit, even if not defaulted shouldn't necessarily make the primary focus that "you" haven't finished configuring it, but just that there is no value for this thing or there is no linkage to a CI/CD pipline or no Sentry record (and so on, to the above point that each plugin is very specific).

Now, having SOME pointer would be helpful on this page, but perhaps more parenthetically or in smaller text near the bottom, something like "To fix this, ensure to align the proper annotation" ... blah blah.

**Comment by Rugvip** [comment]
@andrewthauer Much less vague ideas here: https://github.com/backstage/backstage/issues/1536#issuecomment-729621634 :p

**Comment by tragiclifestories** [comment]
Just chiming in to say that this would be useful for us. EG, we have a monorepo for the catalog and generate the YAML from jsonnet sources, so the MissingAnnotationEmptyState is very misleading and currently difficult to override for the reasons given. I have to say I can't see a super-clean way to do it since it essentially needs to be supported individually by every individual component, but I'd certainly be happy to put it in our "things to upstream" epic and have a crack.

**Comment by andrewthauer** [comment]
💯 We've experimented with wrapping some of the Entity components from the catalog and checking for an annotation and then directing to a custom empty state component specific to our orgs use case. This works in most cases, but the ceremony and code required to do this is not ideal. Would be much nicer is there was an adopted / canonical way to do override the empty state on entity based components.

**Comment by freben** [comment]
Would it help if the empty state was very small, undramatic and targeted at both owners and non-owners?

@adamdmharvey mentions that for most people, they are entirely uninterested in seeing all the info and how to fix things. I think that's an important observation.

Sounds to me like the empty state for e.g. CI/CD could be the text `No builds configured. <More info>`, where "More info" is a link-like text. Clicking on it, a drawer opens on the right side of the screen that explains (1) What it means, and (2) how to fix it.

Even the owners themselves would probably be happy about the change, as they are capable of knowing whether to worry (and fix) about the individual empty states. If they worry, then the info is a click away. If they don't, a warning isn't in their face all the time :)

This of course doesn't directly address the original ask to be able to formulate company-specific information texts and links in that drawer. :)

**Comment by andrewthauer** [comment]
@freben - I think that could work well TBH. For a couple things, we've created a markdown file in the backstage `docs` directory for instruction and this could just be a link to the docs in backstage itself.

**Comment by andrewthauer** [comment]
Another thought, I've had is having a link to some self serve UI that can help setup/configure/fix a common problem. This might be a wizard or button that interacts with some infra service.

**Comment by freben** [comment]
> Another thought, I've had is having a link to some self serve UI that can help automatically setup/configure/fix a common problem. This might be a wizard or button that interacts with some infra service.

Extension (?) of that thought:

What if every exceptional state in the interface had a stable identifier. Like knowledge base IDs. No cicd configured? That's `KB100001`. It will have a definition (essentially a ReactNode to render in the drawer, and a titleto draw on the page next to the `More info`?) and you can override each and every one of them in the app builder if you want. Either with actual content, or with links to some other page.

**Comment by Fox32** [comment]
Or just external route refs that can redirect to whatever site?

**Comment by freben** [comment]
Where the default site is backstage.io!
