### ISSUE TITLE
cli: create-plugin should handle build and type checking failures more gracefully

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#3227]
## Expected Behavior

When using the `backstage-cli create-plugin` some build step tasks like `yarn tsc` might fail. These aren't required to be run and we could handle failures in a more graceful way, simply warning the user that the build task failed.

## Current Behavior

If for example `yarn tsc` fails, the following error is logged:

```
It seems that something went wrong when creating the plugin 🤔
We are going to clean up, and then you can try again.
```

The new plugin is removed as well.

## Possible Solution

If any of the tasks following the creation step fails, `yarn install` and beyond, we should just warn the user about the failure but not remove the plugin.

## Steps to Reproduce

1. Introduce for example a TypeScript issue that makes `yarn tsc` fail
2. Try to create a new plugin using `yarn backstage-cli create-plugin`

## Context

https://discordapp.com/channels/687207715902193673/687235481154617364/773303667675758643

**Comment by raosumanth** [comment]
Thanks @Rugvip .

**Comment by tudi2d** [comment]
Hey. I would like to give it a try and fix this bug!

**Comment by Rugvip** [comment]
Thanks @tudi2d, assigned you! :grin:

**Comment by tudi2d** [comment]
I decided for a straightforward solution by replacing the `throw new Error(...)` with `Task.error('Warning: ...)` and it would look something like this:

![image](https://user-images.githubusercontent.com/8904624/98178616-5239a200-1efd-11eb-8650-4181f0c37e51.png)

This fixes the bug and should give the user enough information. Nevertheless it might be more elegant and longer lasting to add a `Task.warn(...)` to the class Task and use that instead.

Is this solution fine for this bug or should I solve it more generally?
