### ISSUE TITLE
cli e2e test should clean up after itself

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#323]
Would be nice if the cli e2e test script (https://github.com/spotify/backstage/blob/master/scripts/cli-e2e-test.js) removes the created plugin when done. Makes it easier to work with locally

**Comment by braulio-balanza** [comment]
Wouldn't it be good to have a "remove-plugin" cli command that is invoked at the end of cli-e2e-test.js?

**Comment by Rugvip** [comment]
@braulio-balanza yup, that's a good idea! Been missing that during development as well. Do you wanna take a stab at it? :grin:

**Comment by nwmandel** [comment]
@Rugvip mind if I take a crack at it? 😀

**Comment by Rugvip** [comment]
@nwmandel Sure, thanks! :grin:

**Comment by braulio-balanza** [comment]
I was actually going to say the same thing. I had already started working on the command, but if you want to take it @nwmandel go ahead!

**Comment by Rugvip** [comment]
@braulio-balanza, ah, got far? Would make sense for you to take it then

**Comment by braulio-balanza** [comment]
I am about half way done through it.

**Comment by Rugvip** [comment]
Ok sorry for the confusion @nwmandel , but I'm sure you're ok with me assigning it to @braulio-balanza?

Best let us know if you started looking into an issue though

**Comment by braulio-balanza** [comment]
Awesome! I have a question though, would it be worth it to ask whether the user wants to permanently delete the plugin or send it to the trash folder?

**Comment by nwmandel** [comment]
@Rugvip Sure, it's no problem!

**Comment by Rugvip** [comment]
@braulio-balanza I'd say just delete it and rely on git to roll back mistakes.

**Comment by Rugvip** [comment]
@braulio-balanza are you still looking at this? Would like to reassign it otherwise

**Comment by braulio-balanza** [comment]
Yeah, still working on the removePlugin command, I was just doing some
testing to make sure everything works!

**Comment by Rugvip** [comment]
@braulio-balanza awesome :grin: no stress, just checking in.

Btw, if you have something that's close to ready I think it's best to submit a PR, and we can iron out the details there!

**Comment by braulio-balanza** [comment]
Ok! Sounds good!

**Comment by Rugvip** [comment]
Had this for a long time, closing :>
