### ISSUE TITLE
Flaky e2e tests

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#3235]
## Expected Behavior

E2E tests in CI should not fail for other reasons than bad changes.

## Current Behavior

E2E tests are flaky and need to be retriggered often. For example https://github.com/backstage/backstage/runs/1352271046?check_suite_focus=true

## Possible Solution

There are a couple of common reasons for failures. I'll list some known ones with possible solutions:

* `yarn install` fails because of networking issues
  - Tricky to do much about this one, we could try adding retries but most likely we just have to keep retriggering these.
* `yarn install` build step fails (usually nodegit)
  - Try to avoid native modules, especially trying to remove `nodegit` as a dependency as its been causing some issues in other places too.
* Failures in using internal packages from other packages in the repo.
  - Afaik this is down to race conditions in executing the pre/post-pack scripts during builds in the CLI. Have not been able to reproduce

## Steps to Reproduce

¯\\\_(ツ)\_/¯

## Your Environment

GitHub Actions

**Comment by OrkoHunter** [comment]
Loved how you accurately described the Steps to Reproduce.
