### ISSUE TITLE
[tech-radar] Footer legend doesn't respect Backstage theme

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3243]
In the footer of the Tech Radar plugin, the legend that indicates the triangles of moving up or down don't seem to reflect the Backstage theme, making the text sometimes hard to read depending on your theme choice:

  > ▲ moved up ▼ moved down

## Expected Behavior

The legend that is displayed in the footer on tech-radar plugin should respect the chosen theme so the text is properly visible.
* Light Theme
  * Main text on the Tech Radar page is black
  * Legend text should also be black
* Dark Theme
  * Main text on the Tech Radar page is white
  * Legend text should also be white

## Current Behavior

When viewing the Tech Radar page while using the Dark theme, the legend is hard to read.

**Hard to read on Dark theme**
![image](https://user-images.githubusercontent.com/33203301/98194437-6b3a5700-1eed-11eb-9522-6c07dd089b6a.png)

**Easy to read on Light theme**
![image](https://user-images.githubusercontent.com/33203301/98194485-84430800-1eed-11eb-8c19-8e3abe761cf0.png)

## Possible Solution

Load the Backstage theme on that page, and either have it inherently apply to the `<Text />` attribute, or apply it explicitly a la `${theme.palette.infoText}` or some such?  I don't understand the theming well enough yet to have figured out exactly what to do, and tried various permutations which didn't work.

## Steps to Reproduce

1. Turn on Light theme in Backstage
2. View Tech Radar, scroll to bottom, looks good!
3. Turn on Dark theme in Backstage
4. View Tech Radar, see text is hard to read (black on dark grey background)

## Context

The relevant code is here:

https://github.com/backstage/backstage/blob/bd2879640ec45c2f75e1119889130f305f7af6b4/plugins/tech-radar/src/components/RadarFooter/RadarFooter.tsx#L39-L45

I attempted to tweak it, but wasn't able to get various permutations of the BackstageTheme to apply. Thinking there's something more inherent to it, so reporting (_instead of fixing!_).

## Your Environment

- NodeJS Version (v12): v12.16.2
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909, WSL 2, Ubuntu 18.04
- Browser Information: Microsoft Edge (Chrome)

**Comment by Fox32** [comment]
I would use the theme palette to set the text color via CSS classes. I create #3245 for that.

**Comment by adamdmharvey** [comment]
Thanks @Fox32 !
