### ISSUE TITLE
Automatically bootstrap https[s] proxy in the backend

### ISSUE THREAD

**Issue by freben** [backstage/backstage#3263]
## Feature Suggestion

The default backend (in the repo, and as scaffolded by create-app) do not honor the `HTTP_PROXY` and `HTTPS_PROXY` environment variables. This naturally surprises surprised users.

The backend is using cross-fetch, which in turn uses node-fetch, which ultimately uses the built-in http modules - none of which automatically pick up the standard env vars.

## Possible Implementation

1. Introduce a configuration block under `backend`, both in the in-repo `app-config.yaml` and the one created by default by `create-app`:

```yaml
backend:
  reverseProxy:
    http: { $env: HTTP_PROXY }
    https: { $env: HTTPS_PROXY }
```

2. Introduce a dependency on [global-agent](https://github.com/gajus/global-agent), both in the in-repo `packages/backend` and the one created by default by `create-app`, and initialise it with the above values (only if they are present).

## Context

Reverse proxies are common in corporate settings, and this question has been raised several times on support channels.

**Comment by freben** [comment]
We had a discussion and decided that it's probably best to not implement this as code + extra dependency, and instead make sure that we have clear documentation for how to add this manually in your own project. The contact surface for this is so small, and it's most commonly only useful in local dev and something you may not want in a typical prod setting.

**Comment by freben** [comment]
https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md

**Comment by freben** [comment]
@Rugvip @benjdlambert  ok one final question - would this proposal still be helpful to add ONLY in the example backend in the repo? For the getting-started-easily factor.

**Comment by Rugvip** [comment]
@freben and that would make sense, makes it easier to do local development when behind a proxy
