### ISSUE TITLE
Nexus Repository Manager Plugin

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#3269]
Plugin to track artifact versions from a Nexus Repository v3

## Context

As a developer I would like to get insights into my containers/helm charts having a Nexus Dashboard that provides me with an instant view into previous and latest tags with a direct link to the container or chart/package in nexus and be able to support other repository formats like npm, maven in a further iteration using a [tabbed layout](https://backstage.io/storybook/?path=/story/navigation-tabbedlayout--default) 

Using annotation of:

`sonatype.com/repository-slug: format,group?,artifact-id,group-owner-tag?`

Example Component:

`sonatype.com/repository-slug: format=docker,group=docker-release-group,id=backstage-service,owner=infrastructure-team`

Defining group ownership in the slug would enable the ability to perform write type functions such as uploading a component dependency to the repository target in a further release.

https://help.sonatype.com/repomanager3/integrations/rest-and-integration-api/components-api

[Harbor Registry Plugin](https://github.com/BESTSELLER/backstage-plugin-harbor) for some good inspiration 😃 

![image](https://user-images.githubusercontent.com/6157895/157784085-5dadb4fe-cf73-4993-b50e-1d5be0061b8b.png)

**Comment by andrewthauer** [comment]
@regicsolutions - Are you planning on working on this?

**Comment by andrewthauer** [comment]
I'd like to see this still.

**Comment by regicsolutions** [comment]
Idea on what this one could maybe look like would be to show a summary card similar to the SonarQube one like this - ![image](https://user-images.githubusercontent.com/6157895/119814634-9f408e00-beb8-11eb-8f64-1e44ab7641e1.jpeg)

**Comment by andrewthauer** [comment]
I kinda envisioned this plugin having 2 main parts. One being an overview card that can associate entity components to packages in nexus. The other being a top level explore/search page.

I'm not entirely sure the best way to associate components to packages though. An entity annotation could work for simple cases, but we have quite a few monorepo's that contain multiple smaller libraries. Automating these linkages through some monorepo package discovery process would be ideal.

**Comment by shailahir** [comment]
I m interested to contribute. Please share more info about the requirements

**Comment by regicsolutions** [comment]
Great!

I was thinking it would be great to see artifact details about a component
such as nexus repository name and type (maven/npm), latest version of the
components artifact and it’s mapped dependencies.

Maybe setting annotations of:

sonatype.com/repository: npm
sonatype.com/component-tag: org/repo-name

Believe would allow us to fetch the data needed?

**Comment by regicsolutions** [comment]
Great @shailahir !

I was thinking it would be great to see artifact details about a component such as nexus repository type (maven/npm), latest version of the components artifact and it’s mapped dependencies. 

Maybe setting annotations of:

sonatype.com/repository-type: npm
sonatype.com/component-tag: org/repo-name

Believe would allow us to fetch the data needed?

**Comment by shailahir** [comment]
Please assign it to me. I will implement it.

**Comment by regicsolutions** [comment]
@freben i don't have access to assign, can you please assign @shailahir

**Comment by freben** [comment]
Sure.

**Comment by shailahir** [comment]
Thanks for assignment :)

I have started development. Please see the current view screenshots and provide feedback.

![nexus details page](https://user-images.githubusercontent.com/31934874/158108252-f87177b0-6fa2-42de-8177-8b09bb8c866f.png)
![nexus-main page](https://user-images.githubusercontent.com/31934874/158108255-c8ed943a-2d26-4ee4-aaf7-a1b403cfbd6b.png)

**Comment by regicsolutions** [comment]
Looking great @shailahir! 🎉

Few comments: 

1. Heading nitpick: (Capital N) Sonatype Nexus 😀 Is this using Nexus v2 or v3x API?

2. It would be great to be able to support multiple repository formats in a tabbed view where you can view maven2 and docker where applicable. Setting an annotation for each repo format seems like a bit much. @freben any recommendations on the best way to solve this one where one would need to pass 1 or more repository formats?

3. I love the download option, would https://github.com/backstage/backstage/pull/9840 be great to also allow uploading artifacts to the current target path  where only group owners have access to the upload option, they would have the ability to upload a static dependency to the root target path or a sub path within the target. Similar type of permission was recently added to the Jenkins plugin: https://github.com/backstage/backstage/pull/9840 

4. Would be great to also have Component Security  insights. Looks like this project: https://github.com/sonatype-nexus-community/auditjs is making use of the OSS Index v3 API:  https://ossindex.sonatype.org/rest

**Comment by shailahir** [comment]
@regicsolutions  Thank you for feedback. Let me explore about the suggested implementations and update the code. It may take a little time. will do it on this weekend.

**Comment by regicsolutions** [comment]
@shailahir Wasn't sure if you were aware of this [js-sona-types](https://github.com/sonatype-nexus-community/js-sona-types) library, just came across it and wanted to share as it seems to provide some common communication code to retrieve vulnerabilities 😁

**Comment by shailahir** [comment]
- [ ] One being an overview card that can associate entity components to packages in nexus
- [ ] The other being a top level explore/search page.
- [ ] see container/artifact details about a component sorted in different tabs by repository type
- [ ] developers can get insights into there containers such as previous and latest tag name with a direct link to the container or package in nexus. - means need to show all versions of a component.
- [ ] uploading a component dependency in a further release.
- [ ] Heading nitpick: (Capital N) Sonatype Nexus and maybe change All nexus assets to All Assets or All Artifacts.
- [ ] Is is possible to also return the type: group name as well?
- [ ] I love the download option, would be great to limit this option to the group owner of the component
- [ ] allow uploading artifacts to the current target path where only component owners have access to the upload option
- [ ] Would be great to also have Component Security insights

**Comment by regicsolutions** [comment]
@shailahir just checking in to see if you made any progress. The requirements list is a bit on the heavy side for the first iteration, are you okay releasing what's been done so far as a first iteration so we can get some feedback from the community?

**Comment by shailendra-ahir-cbre** [comment]
Yes @regicsolutions , let me clean it up and push by this Sunday afternoon IST time.

**Comment by shailahir** [comment]
Yes @regicsolutions , let me clean it up and push by the sunday afternoon IST time.

**Comment by regicsolutions** [comment]
> Yes @regicsolutions , let me clean it up and push by the sunday afternoon IST time.

Sounds good thanks

**Comment by regicsolutions** [comment]
> Yes @regicsolutions , let me clean it up and push by the sunday afternoon IST time.

Hi @shailahir just checking in to see if you had a chance to clean up the plugin?

**Comment by shailahir** [comment]
Hi @regicsolutions , unfortunately, I have lost the code.

**Comment by dweber019** [comment]
Probably solved now with https://janus-idp.io/plugins/nexus-repository-manager/

**Comment by vinzscam** [comment]
fantastic! Closing the issue
