### ISSUE TITLE
Character encoding seems off in welcoming banner

### ISSUE THREAD

**Issue by O5ten** [backstage/backstage#3275]
The welcome banner at the top does not seem to display ÅÄÖ in usernames correctly. In this case the username comes from a GitHub Enterprise installation through the OAuth2 auth plugin. 

![image](https://user-images.githubusercontent.com/3242379/98781905-66970680-23f7-11eb-98ad-a4ff036b21c9.png)

It should show those letters with the correct encoding even if the underlying. 

## Current Behavior

Currently it displays my last name as **Ã**

## Possible Solution

Find and use the correct encoding for the welcome plugin. I'm not entirely sure where that would be. 

## Steps to Reproduce

1. Use an OAuth app from GitHub to authenticate
2. Have an Ö in the username 
3. Open the first page of backstage

## Context

It's a mildly annoying error at best, not particularly premium when doing demoes when i cannot change my name in either the github enterprise installation nor backstage. 

## Your Environment

- NodeJS Version (v12): Node v12.19.0
- Operating System and Version (e.g. Ubuntu 14.04): Windows and WSL1 with ubuntu 18.04
- Browser Information: Chrome

**Comment by Fox32** [comment]
Our colleague Jörg also observed this issue 😆 We also noticed that the issue was only in the welcome banner, but not on other parts of the UI. However, we never debugged it and switched to a different auth provider since then and it is gone now.

**Comment by O5ten** [comment]
@Fox32 yeah, we had a laugh about it within the team that the application generally supports lots of different charsets really well in the greeting but in the end failed in the name. 

Oh the toxins of user-provided input. :)

**Comment by freben** [comment]
Yup, can totally reproduce! Good thing I also have non-7bit chars in my name!

**Comment by freben** [comment]
Noting that the frontend receives wrongly encoded data from the backend.

![Screenshot 2020-11-11 at 16 40 07](https://user-images.githubusercontent.com/3097461/98831982-91577e00-243c-11eb-97da-c9bca609fce2.png)

**Comment by freben** [comment]
in `plugins/auth-backend/src/lib/flow/authFlowHelpers.ts`, the `atob('${base64Data}')` results in the broken chars. We need to either encode this differently on the sending side, or utf decode on the receiving side.

**Comment by Fox32** [comment]
Just read a little bit about this. The problem here seems bigger than I first thought. Decoding utf on the receiving side feels difficult as it seems to require 3rd party libraries. Right now the HTML is quite simple and doesn't require any external depenencies. I wonder what the reason is to encode the JSON data at all? Otherwise we could just directly embed the JSON into the javascript?

**Comment by Rugvip** [comment]
@Fox32 Security. It's for eliminating the possibility of any form of script injection, don't wanna mess with any kinda escaping or so for that :p

https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder and https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder should be able to help out here

**Comment by freben** [comment]
Yep TextEncoder is what I looked at as well. It is [NOT in legacy IE](https://caniuse.com/textencoder), but that doesn't worry me - we can just try/catch wrap that (and have the broken names in IE) or perhaps polyfill if possible

**Comment by freben** [comment]
PR is up

**Comment by O5ten** [comment]
kudoes for the quick turnaround @freben!
