### ISSUE TITLE
TechDocs has a hardcoded remoteUrl in LocalPublish

### ISSUE THREAD

**Issue by taras** [backstage/backstage#3292]
I'm not sure what problems this will cause, but I suspect nothing good can come out of hard coding the backend URL in https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/techdocs/stages/publish/local.ts#L67

## Expected Behavior

TechDocs should use `backend.baseUrl` instead of a hardcoded host.

## Current Behavior

It's hardcoded and I suspect would break when using anything other than `localhost:7000`

## Possible Solution

Use `backend.baseUrl`

## Steps to Reproduce

It's in the source code.

## Context

I just came across this by accident while implementing a workaround for #3290.

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): 18
- Browser Information: all

**Comment by freben** [comment]
Yeah it's specifically the _local_ publish - but should still be resolved using the right facility.

**Comment by taras** [comment]
@freben yeah, it's the new internalUrl that should be used.
