### ISSUE TITLE
Backstage-cli can't build backend

### ISSUE THREAD

**Issue by JacobValdemar** [backstage/backstage#3304]
When running `yarn workspace backend build`, it prints the following

```
Generated an empty chunk: "index.d"
Generated an empty chunk: "index.d"
```
...and then waits indefinitely

## Expected Behavior

Backstage-cli at least quits - possibly with some error, but optimally after expected files has been generated. 

## Current Behavior

Written at the top

## Possible Solution

`backstage-cli backend:build` works fine on 0.1.1-alpha.25 and the problem starts in 0.1.1-alpha.26 - so I guess the changes in 0.1.1-alpha.26 introduced the bug.

## Steps to Reproduce

1. Be in a backstage project root
2. Delete yarn.lock and node modules
3. `yarn`
4. `yarn tsc` (should not return any errors)
5. `yarn workspace backend build`

## Your Environment

- NodeJS Version (v12): v12.18.3 (`node --version`)
- Operating System and Version (e.g. Ubuntu 14.04): Darwin x64 19.6.0 (macOS Catalina 10.15.7) - also happened on node:12 base image.
- Backstage cli version: 0.2.0 (`yarn backstage-cli -V`)
- Yarn version: v1.22.5 (`yarn version`)

**Comment by Crevil** [comment]
I hit this yesterday as well. I'm unsure as to what was going on, but adding an import statement for `logform` triggerede the behaviour.
I could get around it by using the reexported symbols from `winston` instead of the issue disappeared.

Also this was with the latest release of the CLI, so I think we can close this off @JacobValdemar ?

**Comment by JacobValdemar** [comment]
Alright 👍

**Comment by rlangfordBV** [comment]
So if you're facing this issue, what is the resolution?

**Comment by JacobValdemar** [comment]
@rlangfordBV I think the solution was to delete the yarn.lock file. Upgrade the version of backstage-cli to the latest, and then run yarn install.

**Comment by Rugvip** [comment]
Hopefully just installing the latest version of `@backstage/cli` would be enough, without deleting `yarn.lock`
