### ISSUE TITLE
Favoriting a component resets interface to your owned components

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3310]
When you favorite/star a component, the table view actually refreshes to show you only those components you "own" regardless of what you did or did not star or what filter section you were in. Your updated starred count in left nav updates. However, neither the filtered list (all , starred, or owned) highlight in the left nav changes, nor does the header of the page itself.

## Expected Behavior

Favoriting a component should simply mark the star as favorite (filled in yellow) or no longer a favorite (outlined), and should update the favorite count in the left navigation under Personal / Favorite. However, which ever view or table list you were on should remain.

## Current Behavior

Using the Backstage sample out of the box on a fresh SqlLite database and all example components, you see this view:

![image](https://user-images.githubusercontent.com/33203301/99342391-bfccc300-2859-11eb-997b-1259e31725b8.png)

If you click the star to favorite `playback-order`, everything seems to work. The yellow star is visible, the left nav updates to show 1:

![image](https://user-images.githubusercontent.com/33203301/99342420-ceb37580-2859-11eb-8b71-21854299f02b.png)

However, if you then click all,
![image](https://user-images.githubusercontent.com/33203301/99342484-f0acf800-2859-11eb-951f-adf91e869366.png)

And on this screen, now click the yellow star to _unfavorite_ `playback-order`, you see:

![image](https://user-images.githubusercontent.com/33203301/99342505-00c4d780-285a-11eb-9d8f-fef2972c502c.png)

You've been reset to show you the three components you own instead of the all list you were just on, which is not ideal.  Now, the good thing is your left navigation count for how many are starred has been properly updated, HOWEVER, you've been reset back to your "owned" components list (showing three), even though the header for the section still says "All" which is not correct.

## Steps to Reproduce

See above.

## Context

There are various permutations of this, but all resulting in a reset of the table list to show you only your owned components.  For example:

1. favorite one component
2. In left nav, select Starred.
3. Unfavorite it in this view.
4. You'll be reset again to show your three owned components, you'll have no favorites in left nav, but your header on the main page will still say "Starred".

![image](https://user-images.githubusercontent.com/33203301/99342763-91031c80-285a-11eb-98b0-359899fc2d51.png)

## Your Environment

- NodeJS Version (v12): v12.16.2
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL 2
- Browser Information: Microsoft Edge (Chrome)

**Comment by adamdmharvey** [comment]
Going to guess, starring an entity causes a reload of the entire table, and I believe it's this code which defaults it to show only owned entities:

https://github.com/backstage/backstage/blob/e9bcb7b446425276b6545616cff726be12afd0dd/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L184-L188

So is there some way that after favoriting, the entire table is not refreshed?

**Comment by nhidtran** [comment]
hello! 🦄 would I be able to take on this bug/issue? Just want to make sure no one else is working on it before I give it a go

I delved into this a bit, and the weird thing happens when you click one of the SideBar item cards. 
1. You initially start on owned
2. You click the "All" menu card Item => sets the currentFilter to "all' correctly
3. If you click the "All' menu card Item again => the focus state stay on that card, and all of the items on the right are rendered correctly but on console log it consoles "owned" 

Still debugging, but making sure no one is else has started on this

**Comment by OrkoHunter** [comment]
@nhidtran Assigned it to you - don't worry, take your time and submit a PR!

**Comment by adamdmharvey** [comment]
😄 🕺 Related PR didn't close this ticket automatically, but for sure it fixed it locally for me so hooray! Thanks @nhidtran
