### ISSUE TITLE
Readme link broken

### ISSUE THREAD

**Issue by O5ten** [backstage/backstage#3312]
When i click the readme-link that directs me to our resident GitHub Enterprise repo readme i end up at a malformed URL without the colon **(:)** of the protocol https//ghe.some.company.com. 

If you click here: 
![image](https://user-images.githubusercontent.com/3242379/99361904-16b2b680-28b3-11eb-8fd3-8e29932db195.png)

Link showing in the bottom of the browser before click:
![image](https://user-images.githubusercontent.com/3242379/99362018-3649df00-28b3-11eb-8d81-34349966b009.png)

Link showing in the omnibar after following the link:
![image](https://user-images.githubusercontent.com/3242379/99362150-685b4100-28b3-11eb-8bc6-203a8d8eeade.png)

## Expected Behavior

I expect to end up at my example-docker-service readme. 

## Current Behavior

I end up at a malformed URL

## Possible Solution

Figure out where the colon is removed in the backstage redirect link. 

## Steps to Reproduce

1. Open a component with a github readme
2. follow the readme link

## Context

Not a particularly important feature to me so i guess it doesn't bug too many. But still, links should work! :) 

## Your Environment

- NodeJS Version (v12):  v12.19.0
- Operating System and Version (e.g. Ubuntu 14.04): RHEL7 for host os, application running in docker container packaged by vanilla Dockerfiles from the backstage project. 
- Browser Information: Chrome, Version 86.0.4240.193 (Official Build) (64-bit)

**Comment by Fox32** [comment]
The widget you are refering to is from an external plugin managed here: https://github.com/RoadieHQ/backstage-plugin-github-insights I guess they will see it here to, otherwise you have to create an issue there.

**Comment by O5ten** [comment]
Ah, yes, of course. I'll create the issue there and close this one.
