### ISSUE TITLE
[Search] Improve search match

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#3340]
The new frontend search plugin makes it possible to search across names and descriptions of entities. The name of an entity sometimes includes an hyphen, if I do search for that plugin I might search for "documented component" instead, without the hyphen. This will not give me a match as it is now, only if I search for "documented-component" with the hyphen included. 

We would like to match a result even if the search query in the input field doesn't include the hyphen.

**Comment by BA1RY** [comment]
Hi @emmaindal, I would like to work on this.

**Comment by emmaindal** [comment]
Great, I'll assign you @BA1RY 🎉

**Comment by BA1RY** [comment]
Hi @emmaindal, I've made a PR. Please let me know if there are changes to be made. Thanks :smile:

**Comment by emmaindal** [comment]
closed by #3365
