### ISSUE TITLE
[Search] Search input in side bar -> Search Page flow

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#3341]
We do have a search input field in the side bar which currently are rendered without no other functionality. With that said, the search page is currently only accessible if you navigate to the /search route manually. 

Ideally we would like a user to be able to input a search query in the input field that exist in the side bar and get redirected to the search page while they are typing.

**Comment by Fox32** [comment]
If we pass the search query to the search route as a query parameter, we could also use the query parameter to return to the current state of the search page. That would be useful if I click on a search result and then navigate back with the browser history to the search.

**Comment by Fox32** [comment]
I can take this over
