### ISSUE TITLE
[Search] Second iteration of search result component

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#3343]
"The table is nice and clean, but it sort of makes us do some gymnastics to make the search results conform to the columns.

I like the idea of coming in with an opinionated view of a "search result" model (e.g. title, summary, link, type, owner, etc.), and mapping entities (maybe other things in the future) to match that model."

Would love to collect your ideas and suggestions here so please comment below!

**Comment by Fox32** [comment]
Maybe different kind of entities will also have different ways of visualizing the results in the future? Maybe tech-docs will display the snippet that contains the search result, api docs might show parts of the api definition where the search term is found, users might have a photo and a generic entity display for everything else?

**Comment by emmaindal** [comment]
@Fox32 This is really good feedback, I think this issue can be responsible for collecting ideas for now and I'll work together with our designer and get some suggestions out. 

If we were about to visualizing the different entities in different ways, do you think it make sense to separate the different entity types into different sections in the search result? Like groups?

**Comment by Fox32** [comment]
Not sure, I would probably expect them to be sorted by relevance and not grouped by kind. But a kind filter would be something I expect (which is already there if I have seen it correctly)

**Comment by emmaindal** [comment]
Closing this issue as we now have a new custom search result together with the ability to create custom search result list items available through #5786 which is documented in #5715.
