### ISSUE TITLE
[Search] Dynamically load filter options 

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#3344]
On the search page we do have two filter types at the moment. A selection of Kinds and checkboxes of lifecycles. The data for this is currently just hard coded in the [Filters component.](https://github.com/backstage/backstage/blob/master/plugins/search/src/components/Filters/Filters.tsx#L68)

The different kinds and lifecycles can look different depending on what entities that exist, therefore it would be nice to dynamically load all the filter options that exist for all your entities. 

For example, "The kind filter doesn't include User and Group, though they are in the table listing for me." and "e.g., if there are no APIs registered, than we shouldn't need to filter by them."

- [ ] Investigate if there is any existing api for this, maybe in the catalog client. 
- [ ] Replace the hard coded filters with dynamically loaded data.

**Comment by magneticz** [comment]
Hi @emmaindal 

I was looking at this issue and have a question/idea. Right now it seems that search page is acting like a filter page (where all entities are loaded first, and then search is done on whatever is received). If that's the case, we can identify filters (kind, lifecycle) based on the data available in the entities. Or, is it going to be different in the future? 

If getting filters from received entities is fine, i can create PR

**Comment by emmaindal** [comment]
Hi @magneticz yes that is correct, it will change as soon as we start work on a backend search plugin powered by elastic search or something else. I was thinking a little bit about this and that it maybe could be something the catalog api could provide an endpoint for so that we could get it from there. But also the solution you are mentioning above. I think for now, let's do what you are saying.

This might be something we need to re-think on a more backstage core level since filters is used a little bit here and there so I'll bring this discussion to a meeting we have next week but don't want to block this on that so I'll assign this to you to start work on 🎉
