### ISSUE TITLE
Add a backend:bundle command to the CLI

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#3347]
## Feature Suggestion

Right now the only simply way to deploy a production version of the backend is by using the `backend:build-image` command. It creates a temporary folder outside of the repo and copies over the distribution versions of each backend package in the monorepo and then runs the Docker build within that package. This ensures that the resulting backend image only contains backend dependencies and built code. It also avoid installation of development dependencies.

Because the `backend:build-image` command is operating both on the host machine and docker, it can't be used inside a docker build itself, or in build environments that run exclusively in docker containers and don't support docker in docker. There is a lower-level `build-workspace` command that can be used to replicate this setup, but the `backend:build-image` command also adds proper docker build caching of `yarn install` as well as automatic detection and building of all dependencies of the backend within the monorepo, both which are very tedious and verbose to replicate manually within a Dockerfile.

We should aim to restructure the backend production build process to preferably generate usable build output isolated to just the `dist/` dir. It should also allow for `yarn install --production` to be run afterwards, with installation limited to only the involved packages.

## Possible Implementation

Possibly something similar to how the current `build-workspace` and `backend:build-image` commands work, but move the output to a `dist/` dir instead? It's tricky because we want to ensure that the `node_modules` structure is the same as during development.

## Context

This is brought up daily in Discord #support 😅

**Comment by fidelcoria-aa** [comment]
I've started looking at speeding up our glacial docker builds in GitHub Actions. Starting with yarn cache.

> It creates a temporary folder outside of the repo [...]
> backend:build-image command also adds proper docker build caching of yarn install

How can I save and restore the cache you mention? I can't find where the `docker build caching of yarn install` is set up.

Is this moot once you're figured out how to get the backend:bundle to work?

**Comment by freben** [comment]
@fidelcoria-aa see our repo for inspiration on  how we do the caching - it's a bit involved to get it as efficient as possible. https://github.com/backstage/backstage/blob/master/.github/workflows/ci.yml#L32

**Comment by fidelcoria-aa** [comment]
@freben, that isn't doing docker build. We already do yarn caching like you have there. 
The problem is the docker build does not use the yarn cache. 

I also already set up:

      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        env:
          cache-base:  v1-${{ runner.os }}-cache-docker
        with:
          path: /tmp/.buildx-cache
          key: ${{ env.cache-base }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-base }}-

But  how to get the backstage build to use the cache... still digging around. maybe you can help
how can I get the same effect as:

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ steps.getTag.outputs.shaImageTag }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

when I have to do a `run: yarn workspace @runway/backend build-image`

**Comment by Rugvip** [comment]
@fidelcoria-aa Is this for building the backend only? and are you calling `backstage-cli backend:build-image` along with a `Dockerfile` that includes an `ADD` for `skeleton.tar` such as the on in this repo? https://github.com/backstage/backstage/blob/master/packages/backend/Dockerfile

The `skeleton.tar` contains all the necessary files to do a cached `yarn install` at the docker cache level. When it comes to using yarn cache itself that's not really possible with regular docker build tooling afaik. It would require mounting of host directories into the build containers. That's unless you use a base image that already contains some of the packages which you rebuild occasionally.

For speeding up the builds I would generally suggest a local caching NPM proxy if that's a possibility, as that can be quick enough that it doesn't really matter much whether you're fetching packages over the network or build cache.

**Comment by freben** [comment]
@Rugvip is working on this very thing - is there something you would like to share here?

**Comment by fidelcoria-aa** [comment]
Sorry to pollute this PR, this could've been a discord or a new issue.

> Is this for building the backend only? and are you calling backstage-cli backend:build-image along with a Dockerfile that includes an ADD for skeleton.tar such as the on in this repo?

yes and yes. We have the latest version of backstage-cli as well. But the yarn install during docker build is way too slow to be using a cache. (When a docker build is repeated in the same GH Action Job there is caching and faster build).

Yeah I thought about mounting host directories but was looking for a more compact option. I'm trying [this](https://github.com/marketplace/actions/docker-layer-caching) out now.  I'll open a new issue if I can't get it to work.
