### ISSUE TITLE
Provide autocompletion and schema checks when editing configuration files

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#3366]
## Feature Suggestion

#3264 added support for configuration schema, but does not make the entire fully stitched schema available for editor integration. Having this schema available in editors would make it much nicer to edit `app-config.yaml` files and the like, as it would provide autocompletion and documentation popups.

## Possible Implementation

We could provide a command from the cli that allows you to save the entire stitched schema to a file, something like `backstage-cli config:generate-schema --output .config-schema.local.yaml`. This could then be added as a `"postinstall"` step and the schema file itself could be registered in the editor to at least handle `app-config*.yaml` files.

Another option would be a more direct editor integration like a VSCode extension that is able to with the `@backstage/config-loader` package to load in the schema behind the scenes. This has the benefit of not adding additional processes and files to the repo, but is a bit more of a maintenance burden and perhaps something that anyone from the community could pick up separately.

## Context

#2854

**Comment by desktophero** [comment]
I like the VS Code being an option here so that organizations can bring their own spec to their internal implementation and not affect others or overly customize outside and run into painful upgrades.

Each team, org, company, industry will end up with their "version" of reality. VS Code extensions sound great 👍

**Comment by tanguyantoine** [comment]
This extension has been released in June: https://marketplace.visualstudio.com/items?itemName=Intility.vscode-backstage

https://github.com/schemastore/schemastore/ contains a json schema definition which is being used by https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
