### ISSUE TITLE
Configuration documentation generation

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#3367]
## Feature Suggestion

#3264 added support for configuration schema, but there is not yet a way to view the schema in a nice documentation format. We should add that! :grin:

## Possible Implementation

Since schemas are stitched together based on the dependencies of each app, it's tricky to provide one documentation that fits everyone. I'm thinking that [godoc](https://godoc.org/golang.org/x/tools/cmd/godoc) is something we can model the solution after. It provides a CLI that serves content locally based on local packages, but also has a hosted service that provides documentation for all community packages. Both of those could be desirable but either way we'd start be shipping the CLI :grin:

For documentation generation based on JSON Schema there are quite a lot of options. It's ofc best if we're able to stick to node modules though, or we'd likely want to provide a publicly hosted service that does the conversion. One option is https://github.com/adobe/jsonschema2md but there seems to be many more, haven't dug deep into options here so suggestions are welcome! A fallback would ofc be to create our own as well, but that would be nice to avoid

## Context

#2854

**Comment by keshann93** [comment]
@Rugvip I would like to work on this, hope some experience from #3364  will help to speedup the implementation

**Comment by Rugvip** [comment]
@keshann93 Awesome, thank you! :grin:

Best sync ideas early either here on in draft PRs btw, since the issue is pretty open ended

**Comment by kaos** [comment]
@keshann93 have you made any progress with this? 

Otherwise, I'll have a go at it.. ;)

**Comment by keshann93** [comment]
@kaos I couldn't work on it! Feel free to have it a go :)

**Comment by freben** [comment]
@kaos assigned!

**Comment by Rugvip** [comment]
@kaos alright, no worries, thank you for the update!

**Comment by Rugvip** [comment]
Fixed by #5328
