### ISSUE TITLE
Search Results Dark Mode Issue

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#3377]
I'm a dark mode user. There is one place in the search results that isn't supporting it right now:

## Current Behavior

![image](https://user-images.githubusercontent.com/648527/99820579-4383f980-2b51-11eb-9495-4f8f0ff013e2.png)

Looks file in light mode:

![image](https://user-images.githubusercontent.com/648527/99820843-96f64780-2b51-11eb-9bf7-db61f7f0104e.png)

## Possible Solution

The color should depend on the theme, not sure on which color to choose right now.

## Context

I can take a look next week, should be easy to fix. Otherwise I would be open if someone else fixes it.

**Comment by emmaindal** [comment]
Thanks for reporting @Fox32 I opened a fix using the palette colors! :)
