### ISSUE TITLE
Software Template Marketplace

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#3383]
Similar to the Plugin Marketplace, it would be great to have a **Template** Marketplace as well so the community can share Software Templates!

**Comment by stefanalund** [comment]
Yep, fully agree. One thing we have been discussing is to create a dedicated repo and move existing templates there: `backstage/software-templates`.

I think that is a good starting point and will improve discoverability and contributability (yeah, it’s a word 🙃). What do you think @regicsolutions?

**Comment by regicsolutions** [comment]
@stefanalund Agreed, that would be a great starting point!

**Comment by OrkoHunter** [comment]
@stefanalund It will be awesome to have `backstage/software-templates` repository. TechDocs can also make good use of it for its documentation templates. :) cc @emmaindal I remember you talking about it on Discord.

**Comment by emmaindal** [comment]
Yes agree, a backstage/software-templates repo would be awesome! I can see it hasn't been created yet, want me to create it? @OrkoHunter @stefanalund

**Comment by OrkoHunter** [comment]
@emmaindal IMO we'll need to figure _some_ structure to the new repository. It may also make sense to do it when @bodilb has the new documentation templates ready, so that the new repo looks "rich". :) Let's talk more in an architecture weekly sync w/ everyone.

**Comment by benjdlambert** [comment]
Yep, we did have this work planned as part of the move to `demo.backstage.io` as we were going to pull out the example templates into their own repository. Not sure how long it will take for us to get around to that though right now.

**Comment by emmaindal** [comment]
Cool @OrkoHunter @benjdlambert sounds like you have a plan! 🎉

**Comment by benjdlambert** [comment]
@leemills83 here's the ticket I mentioned this morning in planning wrt the other ticket on the board.

**Comment by OrkoHunter** [comment]
@backstage/maintainers - FYI @bodilb @garyniemen and I are planning to create the repository, bootstrap with few documentation templates, make it public and then figure out migration of existing templates later on (in close collaboration with you).

**Comment by Rugvip** [comment]
> @backstage/maintainers - FYI @bodilb @garyniemen and I are planning to create the repository, bootstrap with few documentation templates, make it public and then figure out migration of existing templates later on (in close collaboration with you).

👍 , just gotta be mindful of the existing templates once we get there, since moving those is gonna be a breaking change. We likely want to add new ones in place and then move references over, perhaps renaming the existing ones with a `deprecated-` prefix too.

**Comment by regicsolutions** [comment]
@benjdlambert with the introduction of scaffolder actions this may be a good place to share them

**Comment by benjdlambert** [comment]
Hmm yep maybe - maybe they could be seperate npm packages or something, needs more thought though.

**Comment by radicaled42** [comment]
I was asking just this on the general forum on discord. I have been working on a couple of templates that could be good to share (documentation and kubernetes templates).

**Comment by benjdlambert** [comment]
Maybe you could add them to `contrib` for now and we can work out a plan to move them somewhere special afterwards? Thinking `contrib/software-templates`? Or something for now?

**Comment by OrkoHunter** [comment]
We'll call this done with #6286

**Comment by OrkoHunter** [comment]
We can call this done now 💯 

https://github.com/backstage/software-templates
