### ISSUE TITLE
Catalog importer should add a configurable description when opening pull requests

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#3384]
## Feature Suggestion

The new Catalog Importer (https://github.com/backstage/backstage/pull/3121) opens a pull request to add a `catalog-info.yaml` file to the repo if none exists already.

![Screenshot 2020-11-21 at 18 29 59](https://user-images.githubusercontent.com/562403/99884619-9a5c0280-2c27-11eb-9454-02516aa79c61.png)

Currently, there is no description in the pull request which is opened by the automation. The Pull Request should have a description which explains its purpose. The pull request should be configurable because different organisations will want to explain Backstage differently, depending on their unique context.

## Possible Implementation

 - The PR is opened from the frontend of Backstage so whatever configuration is passed in will need to be available there.
 - The description might get a bit long to make sense in the `app-config.yaml`.

## Context

 1. I want to explain to my team why these pull requests are being opened and help people understand the value of Backstage.
 2. I want to be able to look back the pull requests in future and remember, by reading the description, why they were opened.

**Comment by adamdmharvey** [comment]
It does now:

![image](https://user-images.githubusercontent.com/33203301/112380138-6705af00-8cbf-11eb-9054-6e5731e057a3.png)

@dtuite going to close, but feel free to reopen if you think further work needed here?
