### ISSUE TITLE
Catalog importer should support monorepos

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#3385]
## Feature Suggestion

The [Catalog importer](https://github.com/backstage/backstage/pull/3121) can currently only add `catalog-info.yaml` files into the root of the repos that are being added. Monorepos may need multiple `catalog-info.yaml` files at different paths.

## Possible Implementation

Allow the user to choose (via dropdown) or enter (via basic text input) the path at which they would like the `catalog-info.yaml` file to appear.

**Comment by andrewthauer** [comment]
Speaking of which, the `CodeOwnersProcessor` should also be updated to support monorepos as well.

**Comment by freben** [comment]
For codeowners, we've been talking about a central facility for analyzing locations - essentially a Backstage specific analog to git-url-parse that is aware of our config and knows about private hostnames and auth decoration of requests etc. Such a facility would be useful to be able to go from catalog info url to repo root url and many other things. I recently got started on the [integration](https://github.com/backstage/backstage/tree/master/packages/Integration) package that could be at the foundation of it (and then core exposing an apiRef for plugins)

**Comment by freben** [comment]
For placement - would not the user just point to the right subfolder to begin with? As in, in the first step, if i pasted the url `https://github.com/backstage/backstage/tree/master/packages/app` it would know to place the file directly where I pointed?

**Comment by freben** [comment]
If you meant more like a batch thing that detects all the multiple roots, then hm. I think the main choices there are to make one file at the root with all the yamls in it, or one in each detected root separately. Not sure if the user needs to be presented with an exact choice, right?

**Comment by dtuite** [comment]
> For placement - would not the user just point to the right subfolder to begin with?

This is a pretty good workaround and would be a great start. I can't help but feel like it's not what I would naturally do if I was using Backstage for the first time.

An alternative is what ArgoCD does - dynamically displaying a list of directories in the repo.

https://www.loom.com/share/ff2221268f714edf82e9467a6aaa779a

I'm not sure that this is better than simply pasting in the direct link to the directory tbh. You have to wonder how they support deploying a nested directory. It is more discoverable as a feature though.

**Comment by andrewthauer** [comment]
Most of the monorepos we have are for shared libraries. For that, we've realized we can probably automate the entire batch process by using our private package registry. We are going to try and create a custom catalog processor the points to the registry (target), then scans our private packages, parses the library package file (e.g. `package.json`, `gemspec`, `pom.XML` and emits new entity specs for each library location. Still need to try it out but it seems most of the metadata we would need should be available in the libraries as they typically have more context then services.

**Comment by freben** [comment]
@dtuite For sure, a browse-to-target thing is definitely desirable in the end. With some platform similar to what I mentioned, it could perhaps be something along the lines of:

- First, use a core api to list the available integrations, and ask the user which one they want. If there's only one, maybe skip this step.
- Ask the user for the relevant auth for that particular provider. If we already have a token for them, it is used transparently
- Using the user's token, show some form of helpful list of repos that they have access to. Maybe do clever things like highlight newly created ones, or ones that aren't yet registered, or something like that
- After selecting the repo, do an initial quick analysis round
- If more than one possible root was found, let the user pick among them, otherwise skip this step
- Continue as before

Something like that? The step of being able to choose the intended target first could be important here I think.

**Comment by freben** [comment]
@andrewthauer Sounds cool and open sourceable though. It may want to be stateful (be backed by a database) to not have to re-analyze packages that haven't been changed.

**Comment by freben** [comment]
@andrewthauer It's not how we envisioned it of course - I need to think about it for a while. I mean, it does preclude you from putting more fields in the yaml file than can be auto-generated, which you mention too.

**Comment by andrewthauer** [comment]
&freben - I'd like to dive into this concept a bit more, but also don't want to hijake this issue. I'll create another GH issue specific to automation.

**Comment by freben** [comment]
Go for it!

**Comment by stefanbuck** [comment]
I guess we can close this issue. <ultiple catalog files within a monorepo are supported by now see https://github.com/backstage/backstage/pull/4271

**Comment by freben** [comment]
I think we can do so for now, and if there are certain aspects of it that are still to do, we can make narrower issues for those.

@dtuite feel free to reopen if i misjudged this

**Comment by dtuite** [comment]
👍
