### ISSUE TITLE
Don't remove the bootstrap location on removal of a child-entity

### ISSUE THREAD

**Issue by dhenneke** [backstage/backstage#3398]
When you use the `Unregister Entity` button on one of the entities that are registered via the `app-config.yaml`:

https://github.com/backstage/backstage/blob/6a6744c014f37b7602d57a4a8f66ca4a895ea8ba/app-config.yaml#L157-L175

the `bootstrap` location is removed. In installations with a persistent database, this breaks the as-code registration for the future.

## Expected Behavior

* The `bootstrap` location should not be deletable
* Maybe not remove all sibling-entities from this special location

## Possible Solution

Different options:
1. Disable the unregister function for as-code entities
2. Special code on unregister to not remove the bootstrap location
3. Always add it on startup, if missing
4. …
5. Replace the `bootstrap` location with something else.

**Comment by joscha** [comment]
This just cost us half a day to find. For any poor soul that suddenly sees:
```
catalog info Locations Refresh: Beginning locations refresh type=plugin component=catalog-all-locations-refresh
catalog info Locations Refresh: Visiting 0 locations type=plugin component=catalog-all-locations-refresh
catalog info Locations Refresh: Completed locations refresh in 3ms type=plugin component=catalog-all-locations-refresh
```
this issue is the reason. You can either regenerate a bootstrap entry via:
```sql
INSERT INTO location VALUES (gen_random_uuid(), 'bootstrap', 'bootstrap');
```
into the `backstage_plugin_catalog.locations` table to recreate the bootstrap, or you can go to https://your.backstage/catalog-import and pass your catalog reference there.

**Comment by freben** [comment]
Addressed the core of the issue here https://github.com/backstage/backstage/pull/4092

But we may still want to make more helpful frontend changes as well.

**Comment by dhenneke** [comment]
> But we may still want to make more helpful frontend changes as well.

I could imagine different options for this:
1. Remove the delete button for the bootstrap location.
2. Disable the button and show a tooltip on hover that tells why it is disabled.
3. As-is but show a reasonable error message (I'm not sure what happens atm; need to check).

**Comment by uri-canva** [comment]
The bootstrap location can't be deleted from the frontend, it's that if you unregister any of the components that are loaded from it, it gets deleted, I guess to prevent the component from being re-registered automatically?

**Comment by freben** [comment]
Yeah indeed when unregistering an entity what it actually does is to remove the location. It shows a dialog to that effect, informing you that if you unregister this entity, then these other entities will also go away (if more than one were coming from the same location).

THAT dialog should probably be changed, to show something like "You cannot unregister this entity, since it originates from static Backstage configuration (location <location type and target goes here>). If you believe this is in error, please contact your Backstage operator team at <ideally some configured contact point here>" ... well, some form of user friendly wording along those lines.

https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/UnregisterEntityDialog/UnregisterEntityDialog.tsx

**Comment by dhenneke** [comment]
I'll prepare a PR to propose a change.

**Comment by dhenneke** [comment]
@freben Seems like there is something off. You tell that:

> It shows a dialog […] informing you that if you unregister this entity, then these other entities will also go away

which is also what I remember to have seen in the past. But it doesn't do that. Question is whether "same location" means in our example `bootstrap` or the file that the entity was actually read from.

For example, the [`artist-lookup` Entity](https://github.com/backstage/backstage/blob/ba59fb6e1de58e4bf6133f198f3eec4697a3a624/packages/catalog-model/examples/components/artist-lookup-component.yaml) is added via the [bootstrap location in the `app-config.yaml`](https://github.com/backstage/backstage/blob/ba59fb6e1de58e4bf6133f198f3eec4697a3a624/app-config.yaml#L184-L186) ➡️ [`all-components.yaml`](https://github.com/backstage/backstage/blob/ba59fb6e1de58e4bf6133f198f3eec4697a3a624/packages/catalog-model/examples/all-components.yaml#L8) ➡️ [`artist-lookup-component.yaml`](https://github.com/backstage/backstage/blob/ba59fb6e1de58e4bf6133f198f3eec4697a3a624/packages/catalog-model/examples/components/artist-lookup-component.yaml) and results into the following entity:

```yaml
{
  metadata: {
    annotations: {
      'backstage.io/managed-by-location': 'url:https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/components/artist-lookup-component.yaml'
    },
    name: 'artist-lookup',
    description: 'Artist Lookup',
    tags: [ 'java', 'data' ]
  },
  apiVersion: 'backstage.io/v1alpha1',
  kind: 'Component',
  spec: {
    type: 'service',
    lifecycle: 'experimental',
    owner: 'team-a',
    system: 'artist-engagement-portal'
  }
}
```

So the info that it originally came from the `bootstrap` location is lost (in the frontend). The backend does remember it since it is stored with the `bootstrap` [location](https://github.com/backstage/backstage/blob/ba59fb6e1de58e4bf6133f198f3eec4697a3a624/plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts#L98) [id](https://github.com/backstage/backstage/blob/ba59fb6e1de58e4bf6133f198f3eec4697a3a624/plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts#L176), which is also used during the [removal process](https://github.com/backstage/backstage/blob/b2b9595ad4f70c10d09a8451fad89b7e5e98bc2c/plugins/catalog-backend/src/database/CommonDatabase.ts#L344-L347).

Question is if this [database-code](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/catalog/DatabaseEntitiesCatalog.ts#L83-L96) is still needed (or can still work; should be irrelevant if a location-id is connected; might get interesting if there is no location-id). This also means that [this code in the `UnregisterEntityDialog`](https://github.com/backstage/backstage/blob/b2b9595ad4f70c10d09a8451fad89b7e5e98bc2c/plugins/catalog/src/components/UnregisterEntityDialog/UnregisterEntityDialog.tsx#L43-L55) can't work anymore, nor something that hints the user that he is about to remove the `bootstrap` location, which is not allowed, but which we only know once we actually remove it.

Maybe the answer would be to create a `dryRun` for entity removals as an analogy to the `dryRun` for location-adds. If the backend is the only one to know these things, then the backend can decide if the operation would be allowed and also tell what would actually be removed. What do you think?

**Comment by freben** [comment]
@Rugvip fyi ^

Good call. I must admit this had gone forgotten for a while at the back of my mind. It's also related to some of the thoughts in https://github.com/backstage/backstage/issues/2001.

> Question is if this [database-code](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/catalog/DatabaseEntitiesCatalog.ts#L83-L96) is still needed (or can still work; should be irrelevant if a location-id is connected; might get interesting if there is no location-id).

It works for the common case where the location a user registered is the one with the actual entities in it. For that case you want to both remove the location, and the entities that it spawned. The problem you see is rather related to when there are Location entities so you lose track of the original lowercase-l location.

As you'll see in #2001, we're considering revamping the foundations of location management.

> Maybe the answer would be to create a `dryRun` for entity removals as an analogy to the `dryRun` for location-adds. If the backend is the only one to know these things, then the backend can decide if the operation would be allowed and also tell what would actually be removed. What do you think?

Hm, maybe. Or maybe just hold off (accepting late failure, but with a good error message) until we can get something like #2001 in place where hopefully this traceability gets a lot clearer.

**Comment by Rugvip** [comment]
@dhenneke @freben I'm thinking we just nuke the entire entity removal endpoint, and if you want to know what the impact of removing a location will be you just query the catalog first. Then we add origin location, in addition to parent location. That way it would be really simple to grab the list of impacted entities, but you can still traverse the tree.

So this would handle the deletion:

```ts
const loc = await getOriginLocation(entityToDelete)
if (loc.type === 'bootstrap') { // frontend check for speed, but validate in backend as well
  throw new Error("can't delete the bootstrap location, duh")
}

const deletedEntities = await getEntitiesWithOrigin(loc)
console.log('about to delete all of these, are you sure?', deletedEntities)

await deleteLocation(loc)
```

Then we're not properly removing the entities yet, just the location, but that's kind of a general problem that we have with the catalog. For now we could just delete all entities at that location and if some of them happen to be registered through other paths they'll return during the next processing loop.

I think there's a lot of debate and ideas to be had about how to handle entity deletions as a whole, but would really like to not discuss that here x)

If we wanna go with ^ long term I think the thing to implement now is the origin location, that way we can do the frontend changes. First as an annotation, and then at some point we could end up moving it to a relation to simplify traversal.

**Comment by dhenneke** [comment]
Relations for this sound interesting, but the quick fix with adding an additional relation would be a reasonable workaround for now.

Since the `await deleteLocation(loc)` part is already done in the existing code when removing an entity, it would just be a matter of adding this missing information and getting a quick fix for the dialog running that gets the related entities from the catalog. I'll take a look at that tomorrow. I would assume that this annotation will then also be added during the refresh loop so that existing entities get updated(?).

I'm indecisive whether removing the endpoint is good or not. Could also be delayed until the outcome of #2001 is realized in the near-/mid-/far- future.
