### ISSUE TITLE
[RFC] Standardized Date & Time library

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#3401]
**Status:** Open for comments

Continuation from https://github.com/backstage/backstage/pull/3387/files#r528254139

## Need

The usage of [momentjs](https://momentjs.com/) should be sunset for a more modern alternative based on the [projects own status and suggestions](https://momentjs.com/docs/#/-project-status/). There should ideally be one standard library that is used in the core packages and plugins for date manipulation beyond what can be easily handled by the JS `Date` object.

- [Why you shouldn't use Moment.js...](https://inventi.studio/en/blog/why-you-shouldnt-use-moment-js)
- [More alternatives to Moment.js](https://blog.logrocket.com/4-alternatives-to-moment-js-for-internationalizing-dates/)
- [You don't (may not) need Moment.js](https://github.com/you-dont-need/You-Dont-Need-Momentjs)

Some common requirements are:

- Duration / diffs
- Humanizing relative time & durations (e.g. `2 days ago`, `about 2 mins`)
- ISO 8601 period support (e.g. `P1M`, `P30D`)
- etc.

## Proposal

We should pick a date/time library that can be used consistently across the core packages and plugins. After picking the library, we create and ADR and work towards replacing existing usage of `momentjs`, etc. to use the new standardized choice. We should also consider creating some standard helper functions for things like duration and relative time, which are very common for CI plugins, etc.

The following are the most likely candidates which cover many of the requirements and have feature rich APIs. Here's a list of relevant notes on these libraries.

This site does a good comparison - https://github.com/you-dont-need/You-Dont-Need-Momentjs

#### [luxon](https://moment.github.io/luxon/)

- Familiar API to `momentjs` wrapper object
- Uses immutable objects
- No tree shaking
- Does not support relative time

#### [date-fns](https://date-fns.org/)

- Uses JS dates directly (no wrapper objects)
- Provided as a series of functions that can be composed using FP techniques
- Supports tree shaking

#### [dayjs](https://day.js.org/)

- Uses a wrapper object similar to `momentjs` & `luxon`
- Small footprint size (2k)
- Fast
- No tree shaking support

## Alternatives

Are there any alternatives we should consider?

## Risks

Continued usage of `moment` will make it harder to switch to another library in the future. It also will affect front-end bundle sizes as `moment` is not tree shaking friendly. Not picking a standardized library that supports the common use cases will likely cause multiple libraries to be used over time. This could cause greater bundles in the full front-end build and also require learning multiple libraries.

**Comment by GoWind** [comment]
If I may chime in, Immutable date objects is a Huge win and I love the FP style of `date-fns` (Clojure FTW :)).
Also building on top of standard Date objects is a good added benefit for interop. :+1:  on `date-fns`.

**Comment by benjdlambert** [comment]
Just gonna drop in our two cents here. On my previous squad inside Spotify we evaluated `luxon` and `date-fns` but found that `date-fns` doesn't support Timezones yet https://github.com/date-fns/date-fns/issues/180

**Comment by andrewthauer** [comment]
@benjdlambert - Not natively in v2, but https://github.com/marnusw/date-fns-tz seems to be the go to solution for time zones. Not sure if there are plans to roll this into the official package or not.

**Comment by brendasukh** [comment]
Heads up that `luxon` does support relative time as of [`1.9.0` ](https://github.com/moment/luxon/blob/master/CHANGELOG.md#190). Haven't used `date-fns` so I can't say much, but definitely prefer `luxon` over `dayjs`, just for the duration math alone. 
``` 
dayjs.duration('P60D').add(dayjs.duration('P60D')).days()
0
dayjs.duration('P60D').add(dayjs.duration('P60D')).months()
4

luxon.Duration.fromISO('P60D').plus(luxon.Duration.fromISO('P60D')).days
120
luxon.Duration.fromISO('P60D').plus(luxon.Duration.fromISO('P60D')).months
0
```

**Comment by freben** [comment]
Oh `dayjs` tries to normalize durations upfront? Nooo

**Comment by andrewthauer** [comment]
Did some digging into `date-fns` support for the scenario @brendasukh pointed out for ISO duration. 

- `date-fns` has a `formatISODuration`, the inverse `parseISODuration` is being worked on in https://github.com/date-fns/date-fns/pull/1947 (discussion here  https://github.com/date-fns/date-fns/issues/1858)
- There is an open [addition and scalar multiplication for durations](https://github.com/date-fns/date-fns/issues/2034)

To demonstrate the composition / flexibility in `date-fns` I was able to replicate this with the following. NOTE: Some of these is planned to be added `parseISODuration`, `addDuration` (which may be extended upon `add`). The others `durationToInterval` & `difference` are my additions which also seem potential core candidates.

```ts
import { add, differenceInDays, differenceInMonths, intervalToDuration } from 'date-fns';

difference(parseISODuration('P60D'), parseISODuration('P60D'), 'days') // => 120
difference(parseISODuration('P60D'), parseISODuration('P60D'), 'months') // => 4

function addDuration(durationA, durationB) {
  const start = new Date(1900, 1, 1)
  const end = add(add(start, durationA), durationB)
  return intervalToDuration({ start, end })
}

function durationToInterval(duration) {
  const start = new Date(1900, 1, 1)
  const end = add(start, duration)
  return { start, end }
}

function difference(durationA, durationB, type) {
  const diffFnMap = { 'days': differenceInDays }
  const {start,end} = durationToInterval(addDuration(durationA, durationB))
  return diffFnMap[type].apply(this, [end, start])
}

// Simplified from PR - https://github.com/date-fns/date-fns/pull/1947/files
function parseISODuration(argument) {
  const nr = '\\d+(?:[\\.,]\\d+)?'
  const dateRegex = '(' + nr + 'Y)?(' + nr + 'M)?(' + nr + 'D)?'
  const timeRegex = 'T(' + nr + 'H)?(' + nr + 'M)?(' + nr + 'S)?'
  const durationRegex = new RegExp('P' + dateRegex + '(?:' + timeRegex + ')?')

  const match = argument.match(durationRegex)
  const parsePart = (val) => !!val ? parseFloat(val) : 0; //?

  return {
    years: parsePart(match[1]),
    months: parsePart(match[2]),
    days: parsePart(match[3]),
    hours: parsePart(match[4]),
    minutes: parsePart(match[5]),
    seconds: parsePart(match[6]),
  }
}
```

**Comment by freben** [comment]
@andrewthauer Thanks for that. Main concern is if the library is incomplete and we supply helpers out of the core library, then we are "owning" those helpers and their API stability, meaning gradual deprecation as the upstream merges happen etc. If something else has it all out of the box, then that would be compelling. I personally don't have a great sense of how big of a mismatch there is between what users need right now, and what `date-fns` has out of the box though, so take that worry with a grain of salt.

**Comment by andrewthauer** [comment]
@freben - That's a fair point. The work around for supporting this particular use case seems recent so hopefully it is officially added soon. As far as other use cases I suspect all 3 are mostly in parity across the board but their approaches to solving differ. The ideal case would be native JS support for these cases through the `Temporal` tc39 proposal. But it's only stage 2 at the moment (no pun intended).

**Comment by freben** [comment]
If they do the temporals right - then aw yiss that will be an awesome addition

**Comment by brendasukh** [comment]
Following up on this - I spent some time trying out both `date-fns` and `luxon` as replacements to `moment` within the cost insights plugin. 

For `date-fns`, I had issues with UTC support, and found myself having to write a utility function (similar to this[ one](https://github.com/date-fns/date-fns/issues/376#issuecomment-353871093)) to first get the UTC date before doing any formatting/adding/subtracting. This isn't something we had to deal with when using `moment` and feels like a big enough issue to keep me from recommending `date-fns` as there doesn't seem to be a fix in progress for this and the issue is locked.  I found some good write ups with similar findings [here](https://github.com/redbadger/pride-london-app/issues/248) and [here](https://github.com/date-fns/date-fns/issues/376#issue-199257518). 

For `luxon`, I found it easy to migrate as a `moment` user given this [doc](https://moment.github.io/luxon/docs/manual/moment.html) outlining the major differences and method mappings. Didn't run into any issues, mostly just getting used to the syntax/method naming. 

Overall, I'm not sure that the small build size of `date-fns` is worth the issues with UTC and the inconsistencies with date calculations/formatting. I would recommend `luxon` over both `date-fns` and `dayjs` unless there are other use cases it doesn't cover that are necessary for Backstage.

**Comment by benjdlambert** [comment]
+1 for luxon

**Comment by andrewthauer** [comment]
Seems like `luxon` might be the best fit then. Although I do like functional approach to `date-fns` it seems that some important features are missing and not a lot of movement is being made to address them natively.

**Comment by benjdlambert** [comment]
Maybe we should settle on`luxon` and collect some of the feedback here to create an ADR for it?

**Comment by adamdmharvey** [comment]
For completeness, I also noticed the Sentry plugin uses `timeago.js` to standardize the whole "12 minutes ago" style of output. Display vs. just raw date processing is of course different, but wanted to note it here, if recommending a common way to manage/process dates, possibly used by plugin authors as well.

https://github.com/backstage/backstage/blob/23190a8a76fd7d94b5813c1d5101e7355651d6be/plugins/sentry/src/components/SentryIssuesTable/SentryIssuesTable.tsx#L20
https://github.com/backstage/backstage/blob/23190a8a76fd7d94b5813c1d5101e7355651d6be/plugins/sentry/src/components/SentryIssuesTable/SentryIssuesTable.tsx#L34-L38

https://www.npmjs.com/package/timeago.js

**Comment by andrewthauer** [comment]
Absolutely. I believe all the popular date libraries we are talking about support this out of the box. I believe `luxon` calls this `humanizing`. I think an ADR should suggest that plugin authors (and core) use the same library, but I'm unsure if we need to provide some utility wrappers yet. Those could be added as needed if we start seeing patterns emerge.

**Comment by benjdlambert** [comment]
Yep :100: @andrewthauer  - Do you want to volunteer writing the ADR or I can do it if I have some spare time over the weekend.

**Comment by andrewthauer** [comment]
I can take a stab at starting one, but might not be until sometime next week if that works. Assuming there's not rush :)

**Comment by andrewthauer** [comment]
Looks like the [Temporal](https://tc39.es/proposal-temporal/docs/) TC39 proposal made it to Stage 3. Exciting to see that more advanced native date support is coming to JS.
