### ISSUE TITLE
Unexpected token from plugin-kubernetes-backend

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3403]
I believe since #2977 I'm having issues starting up my local backstage backend with failures in the `plugin-kubernetes-backend` stating:

```
Error: Module build failed (from /home/aharvey29/github/backstage/node_modules/@sucrase/webpack-loader/dist/index.js):
SyntaxError: Error transforming /home/aharvey29/github/backstage/node_modules/@backstage/plugin-kubernetes-backend/src/service/getKubernetesObjectsForServiceHandler.ts:
Unexpected token (105:10)
```

and

```
aharvey@mycomp:~/github/backstage/packages/backend(master)*$ yarn start
yarn run v1.22.1
$ backstage-cli backend:dev
Build succeeded
webpack-internal:///../../node_modules/@backstage/plugin-kubernetes-backend/src/service/getKubernetesObjectsForServiceHandler.ts:1
throw new Error("Module build failed (from /home/aharvey29/github/backstage/node_modules/@sucrase/webpack-loader/dist/index.js):\nSyntaxError: Error transforming /home/aharvey/github/backstage/node_modules/@backstage/plugin-kubernetes-backend/src/service/getKubernetesObjectsForServiceHandler.ts: Unexpected token (105:10)
```

Is anyone else seeing that?  I did a `yarn cache clean`, a re: `yarn install`, `yarn tsc`, `yarn build`, and all good, but the startup fails.  I wonder if it requires a YAML config in alignment or something?

Note this is with the raw mem-based SqlLite database so no catalog entries with k8s annotations that I'm aware of.

## Expected Behavior

No failures on backend service startup.

## Current Behavior

Failed backend msg, and backend is not working properly. Catalog is failing to load when using through the front end.

## Steps to Reproduce

1. Get latest code
2. Yarn install, yarn tsc, yarn build
3. yarn start in monorepo home, and then yarn start in packages/backend.
4. Immediate errors in the backend at startup.

## Your Environment

- NodeJS Version (v12): 12.16.2
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL2
- Browser Information: Microsoft Edge (Chrome engine)

**Comment by adamdmharvey** [comment]
It seems to suggest the error is on line 105 here I believe?

https://github.com/backstage/backstage/blob/eeda19c7cefb9ab9650c1c0546cdc69a0c313f1f/plugins/kubernetes-backend/src/service/getKubernetesObjectsForServiceHandler.ts#L97-L105

**Comment by adamdmharvey** [comment]
My `app-config.yaml` matching whats in the repo is as so:

Local code:
```yaml
kubernetes:
  serviceLocatorMethod: 'multiTenant'
  clusterLocatorMethods:
    - 'config'
  clusters: []
```
https://github.com/backstage/backstage/blob/eeda19c7cefb9ab9650c1c0546cdc69a0c313f1f/app-config.yaml#L75-L79

So perhaps that needs the `selector` key added?

**Comment by adamdmharvey** [comment]
For me at least, jumping between the git commit for the K8S PR does seem to introduce the error for me, at least locally w/ my env. (clearly the CI/CD ran well for that PR to go in, so must be environmental elsewhere?)

works -> eba3841a2b5c27307bce94040afeb70d235b25db 
fails -> d98fab545130de9d7fd1ff35ada29b31fabb6266

```
aharvey@computer:~/github/backstage/packages/backend(detached*)*$ git checkout d98fab545130de9d7fd1ff35ada29b31fabb6266
M       app-config.yaml
Previous HEAD position was eba3841a2 Merge pull request #3397 from backstage/rugvip/bundlexperiment
HEAD is now at d98fab545 Merge pull request #2977 from moustafab/feature/k8s-label-selector
aharvey@computer:~/github/backstage/packages/backend(detached*)*$ yarn start
yarn run v1.22.1
$ backstage-cli backend:dev
Build succeeded
webpack-internal:///../../node_modules/@backstage/plugin-kubernetes-backend/src/service/getKubernetesObjectsForServiceHandler.ts:1
throw new Error("Module build failed
```

**Comment by benjdlambert** [comment]
@adamdmharvey in a meeting right now but will look at this directly after

**Comment by OrkoHunter** [comment]
I removed the type assertion `<ObjectFetchParams>` from https://github.com/backstage/backstage/blob/eeda19c7cefb9ab9650c1c0546cdc69a0c313f1f/plugins/kubernetes-backend/src/service/getKubernetesObjectsForServiceHandler.ts#L97-L105 and the backend was up and running!

**Comment by adamdmharvey** [comment]
@OrkoHunter  Confirmed that worked for me too for backend to start successfully. 🚀

**Comment by OrkoHunter** [comment]
Thanks @adamdmharvey for confirming! Will create a PR shortly.
