### ISSUE TITLE
Broken "Getting Started" link (http://localhost:3000/welcome)

### ISSUE THREAD

**Issue by johnsaigle** [backstage/backstage#3407]
## Expected Behavior

The link should bring the user to documentation.

## Current Behavior

I got a 404 error page with a link to this repo.

## Steps to Reproduce

1. Install a new projec.t Launch with `yarn start`
2. On the first page a a banner appears with "Welcome to Backstage! Take a look around and check out our getting started page."
3. Click the link for "getting started."

## Context

I was testing out the app and was trying to learn about how it works.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 20.04 (Windows Subsystem for Linux)
- Browser Information: Latest Chrome.

**Comment by tragiclifestories** [comment]
@johnsaigle Why did you close this out of interest? Just ran into the same thing.

**Comment by johnsaigle** [comment]
I went back to the instructions and saw that there are two process to run to make the app work. I can't remember the syntax off the top of my head but basically you need to start both a front-end client app as well as a server back-end. If you only do the former, this error appears.
