### ISSUE TITLE
Backend failed to start up [Error: ENOENT: no such file or directory, scandir '/Users/name/dev/external/backstage/packages/app/dist/static'

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#3412]
## Expected Behavior

I can start the `packages/backend` of this repository when I make a clean checkout of this repository or after running `yarn clean`.

## Current Behavior

While working on Backstage (this repository, not my own instance!) I often run into the following error when doing `yarn dev` or `yarn start-backend`:

```
2020-11-24T09:06:28.506Z app info Serving static app content from /Users/name/dev/external/backstage/packages/app/dist
[1] Backend failed to start up [Error: ENOENT: no such file or directory, scandir '/Users/name/dev/external/backstage/packages/app/dist/static'] {
[1]   errno: -2,
[1]   code: 'ENOENT',
[1]   syscall: 'scandir',
[1]   path: '/Users/name/dev/external/backstage/packages/app/dist/static'
[1] }
```

The problem is, that I haven't compiled the frontend (and I don't need to locally as I'm using `yarn dev`) and therefore the folder `/dist/static` is missing in `packages/app`. The `plugin-app-backend` expects that folder to be their to serve its content.

## Possible Solution

There are several solutions:

* Manually create empty `/dist/static` after running `yarn clean`.
* Making sure that `/dist/static` exists in the `yarn dev` or `yarn start-backend` command
* Removing the `plugin-app-backend` plugin, but it's good that we show the usage here.
* Changing `plugin-app-backend` to allow the missing folder. This is in my option a bad choice as it will hide real errors if the compiled code is really missing.

**Comment by andrewthauer** [comment]
I've run into then as well. We use the `app-backend` for our internal deployments but I rarely use the port 7000 version when working locally. I'm thinking this has nothing to do with cleaning specifically so maybe naturally is part of `yarn dev`.

Another option could be for the  the `app-backend` to read a config setting that is only set in the `app-config.local.yaml`.

**Comment by Fox32** [comment]
Changing `yarn dev` to `mkdir -p packages/app/dist/static && concurrently \"yarn start\" \"yarn start-backend\"` would probably not work on Windows. If I recall correctly, `-p` isn't supported.

**Comment by andrewthauer** [comment]
Yeah, maybe it would be better to actually build a `backstage-cli dev:start` command or something? @Rugvip - Thoughts?

**Comment by Rugvip** [comment]
I'm thinking that the app-backend should just fail to start along with a warning, like some of the other backend plugins. But the backend should still start up and run all working plugins.

Definitely interesting to look at bringing it all together into a single dev server, but that's likely a lot more work :grin:

**Comment by Fox32** [comment]
I made a PR that changes this to be a warning: #3450
