### ISSUE TITLE
Add Kubernetes plugin to Marketplace

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#3436]
@mclarke47 ping 🙂

https://backstage.io/docs/plugins/add-to-marketplace

**Comment by adamdmharvey** [comment]
Mind if I help with this one?

**Comment by stefanalund** [comment]
Go for it @adamdmharvey 👍

**Comment by mclarke47** [comment]
I should have chimed in that we aren't going to add this until we re-vamp the UI and announce it, I will revert (https://github.com/backstage/backstage/issues/3436) and then we can add it in again.

**Comment by mclarke47** [comment]
Kubernetes will actually be classified as a core feature and not a plugin, so I will close this.
