### ISSUE TITLE
Remove usage of React.FC from the entire codebase

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#3440]
## Feature Suggestion
We have some tech debt based on the ADR for Removing React.FC from the codebase.

https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr006-avoid-react-fc.md

Let's do that!

## Possible Implementation
Use the method in the ADR, or `PropsWithChildren` instead.

**Comment by magneticz** [comment]
I could take this task, good chance to get familiar with the code base, but probably over the course of the week

**Comment by benjdlambert** [comment]
@magneticz no probs! I've assigned you!

**Comment by magneticz** [comment]
Hi all,

Sorry, it's taking more time than i promised. Got sick and wasn't able to work for a week. Will continue working on this at a slower pace

**Comment by magneticz** [comment]
I guess this can be closed now

**Comment by benjdlambert** [comment]
Perfect! Thanks for you work @magneticz 🎉
