### ISSUE TITLE
Setup Preview Deployments for Backstage PR's

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#3442]
## Feature Suggestion
- We'd love to be able to see the code changes that we're deploying
- We have an example-app in the repo already with some plugins automatically included
- We want to deploy these example app and backend somewhere part of a PR so we can see the changes introduced by the PR if possible

## Possible Implementation
- Using something like https://tugboat.qa deploy the changes
- Post back to the PR with the preview deployment

**Comment by benjdlambert** [comment]
@backstage/techdocs-core for visibility

**Comment by OrkoHunter** [comment]
Referring to this old, relevant issue about previews
https://github.com/backstage/backstage/issues/535
