### ISSUE TITLE
"export 'Select' was not found in '@backstage/core'

### ISSUE THREAD

**Issue by StefanoVuerich** [backstage/backstage#3443]
I'm facing this problem in my plugin ExampleComponent

![image](https://user-images.githubusercontent.com/7600331/100228820-8e23be00-2f23-11eb-90a0-cbb7d0e2719e.png)

Module '"../../../../../node_modules/@backstage/core/dist"' has no exported member 'Select'.ts(2305)

WARNING in ./src/components/ExampleComponent/ExampleComponent.tsx 44:34-40
"export 'Select' was not found in '@backstage/core'

- NodeJS Version: v14
- Operating System and Version : Windows 10

**Comment by stefanalund** [comment]
Pretty sure Select should be imported from Material directly:

```
import { Select } from '@material-ui/core';
```

**Comment by StefanoVuerich** [comment]
Yes, this works but in [ this page](https://backstage.io/storybook/?path=/story/inputs-select--default) their using a backstage version of the select...

**Comment by freben** [comment]
I think the core Select component should be removed. So do use the material-ui one until then.

**Comment by StefanoVuerich** [comment]
Ok, thanks for the clarification!
