### ISSUE TITLE
Add sanity check to the release flow to make sure all changed packages have a changeset

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#3447]
## Feature Suggestion

To avoid forgetting to add changesets to certain packages before a release it's best if we can have a GitHub workflow or bot that warns us that a packages is missing changesets. Not all changes to a package would need a changeset, for example a spelling fix in a line comment would not. Because of that it's likely best to make it a hint rather than a hard failure.

## Possible Implementation

A new workflows that runs a script that diff's towards the latest release and compares that to the planned changeset version bumps. Or something completely different ¯\\\_(ツ)\_/¯

Either way it would be something that shows up in the "Version Packages" PR, e.g. #3446, as helping out the maintainers with the release process.

## Context

#3445

**Comment by freben** [comment]
We are now trying out the changeset bot as well.
