### ISSUE TITLE
Add auth0 auth

### ISSUE THREAD

**Issue by toonsevrin** [backstage/backstage#347]
All though closed source, auth0 is a really easy and clean oauth provider, consolidating all other providers.

**Comment by AndreasAugustin** [comment]
To be able to access restricted ressources It would be nice to have OAUTH2 client credentials flow together with OpenID connect enabled within the UI in a general way. That would also include the request within this ticket for the AUTH0 provider.

**Comment by Rugvip** [comment]
Discussing the backend capabilities part of this in #366

**Comment by adamdmharvey** [comment]
Thinking this one can be closed?  🧹 

https://github.com/backstage/backstage/pull/1611

**Comment by OrkoHunter** [comment]
🧹
