### ISSUE TITLE
Dialog component

### ISSUE THREAD

**Issue by katz95** [backstage/backstage#3497]
## 🗒 General

Would love if someone could help us create a dialog component, modeled after Material's [dialog component](https://material.io/components/dialogs#usage). We're leveraging our primary + secondary buttons in this dialog component.

![dialog](https://user-images.githubusercontent.com/61153904/100623665-be53ce00-3322-11eb-8c09-0784ed55237e.gif)

## 💻 Usage

This component is used for whenever confirmation of some sort is needed, such as:
        - consent to sensitive matters like GDPR/access/etc.
        - save/submit/cancel after a form is completed
        - alert message
        - optional action buttons

## 📐 Specs

Specs can be found in our [Figma file](https://www.figma.com/community/file/850673348101741100/Backstage-Design-System), under the 'Form Validation' page. 

<img width="1547" alt="Screenshot 2020-11-30 at 3 46 17 PM" src="https://user-images.githubusercontent.com/61153904/100624012-33270800-3323-11eb-8885-079877dab174.png">

We've included various sizes based on the width of the viewport.
<img width="1074" alt="Screenshot 2020-11-30 at 3 47 26 PM" src="https://user-images.githubusercontent.com/61153904/100624152-5c479880-3323-11eb-9151-4f5bbafc3b3a.png">

## 🔮 Future

We'll be adding an example of inline error messaging to this component too.

**Comment by freben** [comment]
Is this component meant to have any differences to the [builtin dialog](https://material-ui.com/components/dialogs/)?

This sounds like it should be added only in the form of a storybook entry, where we explain the conventions of how to use the builtin one properly (what to wrap in Typography, what variant to use for buttons, general JSX structure, etc), rather than making an actual wrapper component in core.

**Comment by katz95** [comment]
ooh good point @freben - you are exactly right! if we could just add it to the storybook with the conventions explained above and in Figma, that would be great!

**Comment by freben** [comment]
Yep the need is definitely there to have it explained and laid out clearly to the user in storybook!

**Comment by karinanguyen** [comment]
working on it!

**Comment by mateusmarquezini** [comment]
Heeey! Can I look into this?

@freben sorry but I didn't understand about this [point](https://github.com/backstage/backstage/issues/3497#issuecomment-735882216), I thought to create a component into /core/components and make it visible under the Layout section in the storybook. Does it sound good @freben @katz95?

Please, feel free to give me some other examples if needed.

**Comment by freben** [comment]
No, I meant that we should leverage raw material-ui as much as is possible instead of inventing wrappers. And that some storybook examples of appropriate usage of raw material-ui might be best.

**Comment by mateusmarquezini** [comment]
ooh ok, I got the point @freben! Could you please assign it for me?

**Comment by freben** [comment]
Sure!
