### ISSUE TITLE
Inline Errors + Nondismissable Banners

### ISSUE THREAD

**Issue by katz95** [backstage/backstage#3498]
## 🗒 General

Would love help with two components: inline errors and nondismissable banners. Nondismissable banners are quite similar to our [dismissable ones](https://backstage.io/storybook/?path=/story/feedback-dismissablebanner--error).

![inline-error](https://user-images.githubusercontent.com/61153904/100624538-ded05800-3323-11eb-9146-03c528ed7239.gif)
![dialog-box](https://user-images.githubusercontent.com/61153904/100624549-e132b200-3323-11eb-9003-f6f7d7c120a4.gif)

## 💻 Usage

Inline validation 
This is used in immediate response to user actions in settings like:
        - incorrect password
        - other errors
Use a red vertical line to additionally highlight the error if there are multiple fields in the form.

Nondismissable banner 
Unlike dismissable banners, these are utilized to indicate mandatory changes that the user must make. They can also be used to feature action buttons.

## 📐 Specs
Specs can be found in our [Figma file](https://www.figma.com/community/file/850673348101741100/Backstage-Design-System) under the 'Form Validation' page.
<img width="1547" alt="Screenshot 2020-11-30 at 3 46 17 PM" src="https://user-images.githubusercontent.com/61153904/100624837-2a830180-3324-11eb-9fca-147a4af08af2.png">

## 🔮 Future
Potentially adding different types of nondismissable banners - currently we've only put the error version.

**Comment by freben** [comment]
Just to clarify: inline errors are part of MUI. https://material-ui.com/components/text-fields/

The nonstandard vertical extra line is tricky though. I would really prefer that it be added, if at all, using MUI/aria facilities. Maybe we can latch onto their CSS classnames, or make use of something like `input[aria-invalid=true]:before` globally. We should avoid wrapping these components at all cost.

**Comment by freben** [comment]
For banners, we've been leaning towards https://material-ui.com/components/alert/ , even though it's still in the MUI lab phase. Making use of one of those, without a dismiss button, should work.
