### ISSUE TITLE
Side Panel Component 

### ISSUE THREAD

**Issue by qzheng2** [backstage/backstage#3499]
## 🗒 General

Would love some help building out this side panel component for Storybook! The side panel component can be triggered by a clickable component or a row of table to display additional information, with or without a lightbox in the background.

![Side Panel](https://user-images.githubusercontent.com/74984488/100632024-58ebe700-32fa-11eb-9b66-5f07cf4ad0c7.gif)

### Side Panel with Lightbox
- User can click the trigger to open the side panel, which slides in from the right
- There is a lightbox in the background of the side panel and block the page content
- User can click the close button or the lightbox to close it, and the panel will disappear by sliding over to the right

<img width="1440" alt="Has Lightbox_1" src="https://user-images.githubusercontent.com/74984488/100631396-ab78d380-32f9-11eb-9530-d23d78ef2fcd.png">
<img width="1440" alt="Has Lightbox_2" src="https://user-images.githubusercontent.com/74984488/100631405-addb2d80-32f9-11eb-8240-cc963cb35d97.png">

### Side Panel without Lightbox
- User can click the trigger to open the side panel, which slides in from the right
- There is no lightbox in the background of the side panel and user can scroll and interact with page content while side panel is open
- User can click on another button (‘trigger’ area) in the main page to swap the content of the side panel without closing it (e.g. click various rows of a table to view different details in side panel)
- User can click the close button or the “non trigger” area outside the side panel to close it, and the panel will disappear by sliding over to the right

<img width="1440" alt="No Lightbox_1" src="https://user-images.githubusercontent.com/74984488/100631486-c2b7c100-32f9-11eb-8b49-78a9ec1b592a.png">
<img width="1440" alt="No Lightbox_2" src="https://user-images.githubusercontent.com/74984488/100631664-f72b7d00-32f9-11eb-8ee5-14691fde1b35.png">
<img width="1440" alt="No Lightbox_3" src="https://user-images.githubusercontent.com/74984488/100631678-fabf0400-32f9-11eb-8d7c-1f96913a6465.png">

## 📐 Specs
You can access specs by duplicating our [Figma UI Kit](https://www.figma.com/file/nUaAw56hTgC0RIOYkuLSrB/Backstage-Design-System?node-id=1145%3A0). Click on the 'Side Panel' page on the left hand side.

<img width="1183" alt="Spec Img" src="https://user-images.githubusercontent.com/74984488/100631990-4ffb1580-32fa-11eb-8dc7-5ad53863e640.png">

**Comment by ayshiff** [comment]
Can I work on this ?

**Comment by katz95** [comment]
Yes!! @ayshiff thank you!!

**Comment by freben** [comment]
I think this is also a case of using just the builtin drawer.

https://material-ui.com/components/drawers/

So the task may be to add a storybook that documents how to use it in a way that matches the designs, or to collaborate to tweak the designs slightly if the builtins have a corresponding similar-enough concept/component.

@ayshiff would you be up for that?

**Comment by ayshiff** [comment]
> I think this is also a case of mostly using the MUI builtin drawer.
> 
> https://material-ui.com/components/drawers/
> 
> So the task may be to add a storybook that documents how to use it in a way that matches the designs, or to collaborate to tweak the designs slightly if the builtins have a corresponding similar-enough concept/component.
> 
> @ayshiff would you be up for that?

Yes, sure ! 👍
