### ISSUE TITLE
[RFC] Support for different breakdown dimensions in Cost Insights

### ISSUE THREAD

**Issue by timbonicus** [backstage/backstage#3515]
**Status:** Closed for comments

## Need

Cost Insights supports a breakdown of entity costs by SKU as of #3268. We have a need internally at Spotify to show cost breakdowns by other dimensions - for example, by deployment (GCE vs GKE) or data pipeline trigger type (automatic, manual, backfill).

## Proposal

The modal dialog for SKU breakdowns should have tabs in cases where different dimensions are available. Alternatively, we can switch breakdowns to MUI's [Drawer](https://material-ui.com/components/drawers/) if this feels unappealing for a dialog.

In the current implementation, a singular breakdown is fetched as part of `CostInsightsApi.getProductInsights`, in `Entity.entities`. We could change the `entities` field to `Record<string, Entity[]>` to support multiple breakdowns by different types; this would require fetching all breakdowns for entities at load time. Alternatively, we can add an API method:

```typescript
type CostInsightsApi = {
  ...
  getEntityBreakdown(options: EntityInsightsOptions): Promise<Entity[]>
};

type EntityInsightsOptions = {
  entity: Entity;
  product: string;
  kind: string; // kind of breakdown, e.g. SKU, deployment
  duration: Duration;
  lastCompleteBillingDate: string;
};
```

In this case, the `Entity` type returned in `getProductInsights` should list the kinds of breakdowns supported by the entity.

A downside to this approach is that we won't know until fetching the breakdown whether the breakdown is meaningful. For example, do we want to show a deployment breakdown for things deployed in a single environment?

## Alternatives

One could argue that such breakdowns are another level of hierarchy in cost data, that an entity can have costs in different deployments which can _further_ be broken down by SKU. This would imply more of a drill-in hierarchical breakdown.

This could be useful in some examples and burdensome in others where switching between dimensions would be preferred. I'm not confident that we can (or want to) enforce that the relationship always be hierarchical. For our purposes internally, a drill-down approach seems undesirable since the dimensions offer a different insight than SKU.

Another alternative is to have a stacked bar chart, as shown in #3357. This seems undesirable in two ways:

- Breakdowns are available via two different mechanisms (hover + click), presenting a confusing UI.
- Limited number of breakdown entities supported

## Risks

Both API approaches detailed above are backwards-incompatible. We should be sure to note this with migration instructions in the changeset.

**Comment by brendasukh** [comment]
> The modal dialog for SKU breakdowns should have tabs in cases where different dimensions are available. Alternatively, we can switch breakdowns to MUI's [Drawer](https://material-ui.com/components/drawers/) if this feels unappealing for a dialog.

I think tabs works fine here, given that we might get a design overhaul in the near-ish future anyway. 

> A downside to this approach is that we won't know until fetching the breakdown whether the breakdown is meaningful

It feels weird to have to fetch a list of supported breakdowns and then have to fetch the breakdown data separately, all the while not knowing if we'll display that data at all (in cases like having a single deployment environment). I prefer updating the `entities` field, although that may have its own issues, it feels slightly better than the alternative.

**Comment by timbonicus** [comment]
To clarify, I was proposing tabs in either case. They just might look better in a Drawer than a Dialog. 😄 

I was assuming a list of supported breakdowns would probably be a static list per product (e.g. certain breakdowns for services vs data pipeline entity types). So we're not really _fetching_ per se. Maybe that implies this approach should be configuration-driven? We toyed with the `product` configuration having `entityType` before, maybe it should have an array of supported breakdowns?

**Comment by brendasukh** [comment]
@timbonicus ah, static list makes sense. If we add it as part of the config, it might be get a little wordy if we have to specify SKU breakdown for each product ? I think I still somewhat prefer just updating `entities` unless there are major concerns with that.
