### ISSUE TITLE
Add scaffolding support for Bitbucket and Bitbucket Server

### ISSUE THREAD

**Issue by goober** [backstage/backstage#3526]
## Feature Suggestion

Backstage has support for fetching catalog entities from Bitbucket and Bitbucket server. However, the scaffolding feature lacks support for these systems.
This feature request suggests that support is added to improve the experience for organisations using Bitbucket as their source versioning system.

## Possible Implementation

Take inspiration from other implementations at: https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/src/scaffolder/stages

I volunteer if no one else is currently working on an implementation

**Comment by flyhard** [comment]
Would this one include generating the TechDocs from bitbucket? I just opened a Feature request (#3525) for that.

**Comment by goober** [comment]
@flyhard I think they are separate feature requests since they are located in different plugins.

**Comment by hooloovooo** [comment]
I'm not sure what the status is on the scaffolder to use the UrlReader for fetching files, but if that is on the roadmap this should probably be implemented as a UrlReader. That way there's no need to implement BItbucket support for each plugin that requires it. Ping @benjdlambert

**Comment by regicsolutions** [comment]
This would be a great feature! @benjdlambert is the Urlreader something in the near term roadmap for the scaffolder?

**Comment by freben** [comment]
The UrlReader does not yet have readTree support for Bitbucket ... so that would have to be contributed separately first if you were to use UrlReader to implement this.

Barring that, you could contribute bitbucket support in the scaffolder by amending the `prepare` and `publish` folders accordingly. It may be the case that it's pretty much a matter of some copy-paste and light editing for the preparer - they mostly use nodegit, and that should work for bitbucket as well, right? The publisher probably requires using a dedicated bitbucket API library.

**Comment by freben** [comment]
https://github.com/backstage/backstage/issues/3546 aims to add the readTree support

**Comment by goober** [comment]
A quick update. I have a working example running locally now. Currently there are some rough edges and I have not tested it with Bitbucket Cloud yet.

**Comment by benjdlambert** [comment]
Sorry just catching up with all this, as @freben mentioned #3546 is for the `BitBucket` support, but there's a lot of work coming up with the scaffolder over the next quarter or so which would include the refactor to start using the `readTree` functionality, which it currently does not.

There's an ongoing RFC here #2771 which collects a lot of thoughts for the new direction of the scaffolder.

**Comment by regicsolutions** [comment]
@goober that's great news! looking forward to this feature.

**Comment by regicsolutions** [comment]
> A quick update. I have a working example running locally now. Currently there are some rough edges and I have not tested it with Bitbucket Cloud yet.

@goober Wondering if a pull request been created for this feature?

**Comment by goober** [comment]
@regicsolutions I have just created a draft PR that you can try out. However, it is not ready to be merged yet but can be used for testing Bitbucket Server scaffolding

**Comment by regicsolutions** [comment]
@goober excellent! I’ll start testing this and let you know my findings

**Comment by kiranpatel11** [comment]
@goober thank you so much for implenting bitbucket server support for scaffolder.

Any thoughts on using IdentityApi to use logged in user's identity while making bitbucket api calls ?
The general problem with using token configured in app-config.yaml for write api calls (e.g. scaffolder) won't work in most cases with security concerns. The user with access to backstage can bypass the security defined in bitbucket server and will be able to create repos without having appropriate permission.

**Comment by freben** [comment]
@goober closing the ticket now that this is merged and released, feel free to reopen if that is in error

**Comment by freben** [comment]
@kiranpatel11 We are doing a major refresh of the scaffolder, work on that is expected to start this quarter. As part of that, we will likely look at the auth interactions as well.
