### ISSUE TITLE
Provision to change the greeting message in the catalog page.

### ISSUE THREAD

**Issue by arunpramodh** [backstage/backstage#3529]
Need to customize the Greetings text with type user on /catalog page.
## Feature Suggestion
Currently the greetings message is generated in @backstage/plugin-catalog with Guest/User name concatenated is being displayed on the /catalog page.
I didn't find a way to replace that greetings message with my custom code. 

## Possible Implementation

Need to overwrite the greetings message within the packages/app code.

**Comment by timbonicus** [comment]
Should be resolved in #5111.
