### ISSUE TITLE
Automatically create GitHub releases with summary of all bumped packages

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#3531]
## Feature Suggestion

After moving over to changeset and individual package releases, we stopped creating releases in GitHub. GitHub releases is something that many rely on to know when there's been a new release, and it would be best if we could keep using them.

## Possible Implementation

Either fully automatically or assisted by some scripts we could make each merge of the "Version Packages" PR lead to the creation of a GitHub release along with a summary of all changes in that release.

**Comment by OrkoHunter** [comment]
This would be awesome! I imagine the following -

* A GitHub action workflow that runs when Pull Requests are merged.
* See if the PR was created by @backstage-service and has the title `Version Packages`.
* Use the newer version in the PR's root `package.json` file. Use this as the new tag, the PR's summary as release description, and create a release using GitHub API (and @backstage-service's token).

Can I work on this? :)

**Comment by freben** [comment]
Sure :)
