### ISSUE TITLE
Identity information inconsistent between Microsoft authentication and Microsoft Graph user data in catalog 

### ISSUE THREAD

**Issue by backjo** [backstage/backstage#3535]
I'm running a Backstage application with authentication provided by the Microsoft provider, and data ingested into the catalog via the microsoftGraph processor. For an email like backjo@foo.com, the following various data points look something like this:

Backstage User record:
```yaml
kind: User
metadata:
  name: backjo_foo.com
```
Backstage Identity:
```json
{
  "id": "backjo"
}
```

Because of this inconsistency, filters like 'Owned' do not work correctly. 
## Expected Behavior
As a user, I expect that information from Microsoft for Identity and Catalog information should match. Ideally, this is automatic, but if not, it would be nice to allow a user-defined function for both plugins to establish the unique identity string. 

## Current Behavior
Identity and catalog information is inconsistent. 

## Steps to Reproduce
Connect to Microsoft Graph for authentication and catalog, and try to view "owned" resources.

**Comment by Fox32** [comment]
This is indeed a problem we didn't noticed when we wrote the user & group ingestion. We are not using the build in microsoft login but build our own that is implemented using a reverse proxy infront of the backend (oauth2-proxy). I guess it would make sense to change the microsoft login to generate similar user names. We choose the longer names for the user import as we otherwise would have duplicates in our instance.

**Comment by backjo** [comment]
Even with the long names, we have duplicates :( 

I wonder if it makes sense to have some sort of middleware for both, so that plugin users can pass in custom functions to extract a name.

**Comment by dhenneke** [comment]
The ownership-feature in the catalog table is currently assuming that the userid matches the user entity: https://github.com/backstage/backstage/blob/05f3ca491e1fb07814f936f7539baa92312e5938/plugins/catalog/src/components/useOwnUser.ts#L30-L32

But it would be better to get the full entity from the identity api. But I think there are not yet concrete plans on how this would look like.

**Comment by freben** [comment]
Ultimately, I think we will have to make it possible for an org to choose how they do this mapping. As in, to inject actual code in the `backend` package that maps from the input data to an output identifier (or even to an entire entity out of the catalog, perhaps, if that can't be done uniformly by the framework).

**Comment by freben** [comment]
To be clear, I realise that that response wasn't particularly helpful to get this sorted out in the near term. I hope to gather some feedback and ideas and then see how we best address this question of how to form names for externally sourced entities. If you move ahead with some tweak or fix, do keep us in the loop.

**Comment by freben** [comment]
> Even with the long names, we have duplicates :(

I'd like to understand this part. Do you have multiple users with the same email for example? Or how does this collision happen?

**Comment by backjo** [comment]
> Ultimately, I think we will have to make it possible for an org to choose how they do this mapping. As in, to inject actual code in the `backend` package that maps from the input data to an output identifier (or even to an entire entity out of the catalog, perhaps, if that can't be done uniformly by the framework).

We ended up doing this, through:
- A location-specific post-processor that changes the name. 
- A custom auth provider that resolves the name (we needed the custom one anyway for our oidc proxy). 

I think i misspoke about the duplicates - we had duplicates with the long name strategy, but on Groups, not Users. We had User duplicates on the shorter name strategy due to having multiple domains managed in the same AD instance.

**Comment by freben** [comment]
Cool that you found a way forward! Thanks for reporting the details of it. The system is pretty flexible. But we could make it easier and clearer for users because it's going to happen to others.

Would it make sense to you, if you used namespaces for the different domains? Then your components could be owned by `org1/group1` or `org2/group1`.

**Comment by backjo** [comment]
Oops - thought I had replied to this. Namespacing does seem to be the most logical way to avoid conflicts across domains.
