### ISSUE TITLE
Implement readTree on BitBucketUrlReader

### ISSUE THREAD

**Issue by hooloovooo** [backstage/backstage#3546]
We should implement support for the readTree method on BitBucketUrlReader. The implementation can hopefully be more or less copied from one of the UrlReaders that implements the method already. 
https://github.com/backstage/backstage/blob/master/packages/backend-common/src/reading/GithubUrlReader.ts

**Comment by lykims** [comment]
Hi! 👋
I'd like to work on this. This is also my first time contributing to `backstage`.

**Comment by stefanalund** [comment]
@lykims welcome to Backstage! I’ve have assigned you.

**Comment by freben** [comment]
Heh, I happened to poke at this a bit last night but it's not finished. I'd be happy for you to continue with it since I'll be busy elsewhere.

Here's my branch that you can keep working on https://github.com/backstage/backstage/tree/bitbucket-read-tree

**Comment by lykims** [comment]
@freben Thank you for sharing! I'll take a look, and compare with what I have.
