### ISSUE TITLE
Implement readTree on GitlabUrlReader

### ISSUE THREAD

**Issue by hooloovooo** [backstage/backstage#3547]
We should implement support for the readTree method on GitlabUrlReader. The implementation can hopefully be more or less copied from one of the UrlReaders that implements the method already. 
https://github.com/backstage/backstage/blob/master/packages/backend-common/src/reading/GithubUrlReader.ts

**Comment by mateiidavid** [comment]
Hi, this seems like a straightforward issue. Bit of a JS noob but would love to get more familiar with the language and the project. 

I would be looking at getting this done within a week or so. @hooloovooo @Rugvip

**Comment by Rugvip** [comment]
@mateiidavid Awesome, thank you! Let us know if you need any pointers, or pop by Discord

**Comment by freben** [comment]
If it helps at all, here is the beginnings of the bitbucket implementation - not finished, but maybe it can be helpful to look at the diff to get started
