### ISSUE TITLE
Cache docs pages built with UrlReader

### ISSUE THREAD

**Issue by hooloovooo** [backstage/backstage#3548]
Currently we cannot detect updates to source files when techdocs are built using the UrlReader. This means we can't do caching of built docs and have to reload on every pageload. We need to find some way of checking the last updated date of files in a repository or subtree of a repository.

This will probably require a solution for each supported VCS. For example in Github we can probably use the api and check when a file or directory was last updated.

Ideas on how to approach this is welcome!

**Comment by Rugvip** [comment]
@hooloovooo I'm thinking it might make sense to use a plain git client for this to fetch the `HEAD` sha. @benjdlambert is looking into switching over to using https://github.com/isomorphic-git/isomorphic-git, and we'll likely tie that up to be easily usable with the integrations config to talk to different type of providers. The piece that would then be missing is a way to know what the `sha` is when using `readTree`. It's not strictly required though, If you due to a race happen to download a newer version than what you expect that's probably not gonna leave to any breakages anyway.

**Comment by hooloovooo** [comment]
@Rugvip Yea that could work assuming it's fast enough. This is something that would have to run on every page load.

**Comment by benjdlambert** [comment]
I might get some time on this today, I've currently got the scaffolder to work with github with cloning and pushing a scaffolded repository. Seems pretty easy to use and a little easier and cleaner than node-git.

**Comment by freben** [comment]
> @Rugvip Yea that could work assuming it's fast enough. This is something that would have to run on every page load.

Maybe "At most every 30 seconds", or similar, if some delay is ok for the sake of speed and less checking.

The internal techdocs has a caching proxy that is exercised regularly for all known sites right? Is such a scheme something that's on the radar for the future? Or even a reactive, event/webhoook driven rebuild process that only runs on merges and then the read pipe does no freshness check?

**Comment by OrkoHunter** [comment]
> Or even a reactive, event/webhoook driven rebuild process that only runs on merges and then the read pipe does no freshness check?

@freben Yes! We don't recommend the TechDocs plugin to care about building docs, it can do no checks and will depend on the storage to read docs from.

In https://github.com/backstage/backstage/pull/3432/files#diff-4f66343e18ab461dbd20cff06f40423029316cfbb01b559d60b1dfda3a3281c6R38-R45, I am working on adding a config where users will depend on the repository's CI/CD pipeline to build docs and publish to storage. TechDocs will switch to consume-only mode in this case. Wrote more about it here https://backstage.io/docs/features/techdocs/architecture

However, in the Basic "out-of-the-box" experience of Backstage/TechDocs, we don't expect that users will setup the CI/CD pipeline to just see how it looks, hence we will keep the behavior of TechDocs building docs locally, publishing to storage and then reading from the storage.

**Comment by freben** [comment]
Makes sense!

**Comment by Rugvip** [comment]
Maybe a separate discussion but I've been wondering why TechDocs doesn't refresh docs upfront rather tha in the user request path? Periodically grabbing all entities with the annotation and checking if then need a refresh

**Comment by freben** [comment]
That's essentially what the internal proxy does right? There's a little thing that just on a timer asks for all of the docs sites' landing pages and throws away the response. Or is that just for getting the (already generated) files out of the slower backing store?

**Comment by hooloovooo** [comment]
That could make sense. Don't know how it would scale to potentially thousands of entities though, but i guess even that is up to how often you check if a particular doc site it up to date.
