### ISSUE TITLE
Collapsed sidebar shows scroll bar when window not full size

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3556]
With the sidebar collapsed (appearance pin sidebar is off), at full screen it looks fine. However, anything other than full screen shows me a scroll bar.

## Not full screen

![image](https://user-images.githubusercontent.com/33203301/101087041-af1d8c00-357f-11eb-8cfa-f1425bb8b001.png)

## Full Screen

![image](https://user-images.githubusercontent.com/33203301/101087008-a462f700-357f-11eb-8dc9-65fd65f3d667.png)

## Environment

Node v12.16.2
Microsoft Edge (Chrome 
At master commit: 05f3ca491e1fb07814f936f7539baa92312e5938

![image](https://user-images.githubusercontent.com/33203301/101087747-aaa5a300-3580-11eb-9384-c2dc570ff717.png)

---

> Side note: I would open a ticket about the browser scroll bar being visible on the left 😬

_Originally posted by @stefanalund in https://github.com/backstage/backstage/issues/3542#issuecomment-737827518_

**Comment by zygof** [comment]
Hello, 
I can propose a solution on this ?

**Comment by adamdmharvey** [comment]
@zygof yes, absolutely!  Propose away!  Are you willing to work on it, maybe contribute a PR? If so we could assign you as well. Happy to have any contribution. 👏

**Comment by zygof** [comment]
@adamdmharvey Thank you for the welcoming 😀! Yes, i will do a PR soon !
