### ISSUE TITLE
Public Container Images

### ISSUE THREAD

**Issue by rlangfordBV** [backstage/backstage#3557]
Is there a plan to release container images to docker hub for public consumption?

## Context

I want to get backstage up and running quickly in Kubernetes.  I don't want to build container images for it, I want to download a helm chart.  I've played with the example helm chart, but I'd really like a clean install.

**Comment by freben** [comment]
This is not planned at least in the near term.

What would you like to use this installation for? Mainly to get a feel for the interface?

The value and power of Backstage comes from its customisability and how things integrate. Building fixed frontend or backend images for it would provide very little value without the organisation in question adding their own data sources and configuration (which would imply a build step happening after that). The frontend and backend images would just be docker images that expose a port each, and the installation experience of those would be very similar to what your organisation already most likely uses, so the learnings from that would arguably be limited as well.

If you describe your use case we may be able to help out better, such as pointing to a demo site or provide contact details for demo and discussion. You're also welcome on Discord to get into details.

**Comment by rlangfordBV** [comment]
I want to use it the way that it sounds like Spotify uses it.  Setting up app scaffolding and service catalog-y things that our developers are asking for.  I want to run it in Kubernetes, and add config to it via `values.yaml` that gets sucked in the appropriate places(like a configmap) and passed to the container(s) when starting.  

I want to use and administer it for multiple application teams without mucking with JS, basically.

**Comment by freben** [comment]
Right. Yeah we use it by having a monorepo into which the entire org contributes various plugins and enhancements. This repo gets built and deployed by our CI/CD system just like any website/service is, so it's highly automated and driven by pull requests. The config is part of the code, so config changes get built and shipped as well. The "use case" and deployment of Backstage is owned and managed by a team, while the individual plugins therein are owned by the teams that contribute them. This is the flow that will be used by most intended adopters as well.

For your use case, there are a few things that aren't in place yet.

Loading config data from a config map isn't something that can happen directly, but they can be translated to env vars in the consuming side, right? In that case, that would work for individual values. But the config yaml file inside the image needs to have the corresponding placeholders like `$env: MY_ENV_VAR`, so to get them in place you are already looking at making a build step.

And extending the system and adding plugins that provide the actual value - that needs code and config. Usually not at all much, per plugin - but some, and it varies. We have gotten requests to look into the possibility of having one-click plugin addition wherein the already-running Backstage can dynamically add and remove plugins, but that is not something that will transpire in the near term.

I hope that helped and didn't sound too daunting. I want to be honest about what it means to run Backstage. :) It is a bit of effort at the start, and ownership and care needs to be part of the picture to be really successful. But when those plugins start to come into place and the org starts finding ways to extend and enrich things even more beyond what the open source world does - then it'll shine.

**Comment by rlangfordBV** [comment]
Ok, maybe I just need to ask questions in Discord.  I think i'll make another request to provide a frontend `Dockerfile`.  I found the one for the backend, but a frontend file is not included when you pull the thing in via `npx` as described in [here](https://backstage.io/docs/getting-started/)

**Comment by Rugvip** [comment]
@rlangfordBV The frontend Dockerfile was actually removed, as we moved over to the frontend being served by the backend by default. The Dockerfile in this repo is still an example of how to Dockerize the frontend using a standalone image

**Comment by rlangfordBV** [comment]
@Rugvip,

Is there some updated documentation somewhere?  The example helm chart in the repo has separate containers, so I'm at a loss for what to do here.  I want to evaluate this tool because my co-workers are asking for it, but I'm struggling to get docker image(s).

**Comment by freben** [comment]
There's the docs at https://backstage.io/docs/getting-started/ to begin with. We're happy to help out on Discord if there are gaps in there.

**Comment by Rugvip** [comment]
@rlangfordBV also https://github.com/backstage/backstage/blob/master/packages/create-app/CHANGELOG.md#patch-changes-1 for the recent changes

**Comment by rlangfordBV** [comment]
@freben yes, that's what I've been using.  I can get the app going locally.  I need it in k8s to properly kick the tires, however.

**Comment by regicsolutions** [comment]
Would be cool to have a Backstage package on [Artifact HUB](https://artifacthub.io/packages/search)

**Comment by IliaGe** [comment]
I'm joining the not so good experience over here...
All I want is to run 'helm install backstage' and have this software running .. but it's not possible :0
1 Chart in the repo configured with spotify dockerhub - which presents downloads.
1 Chart in the repo configured with someone private hub account :\

**Comment by Rugvip** [comment]
Added an entry to the FAQ about why there aren't any public container images: https://backstage.io/docs/FAQ#why-are-there-no-published-docker-images-or-helm-charts-for-backstage. It also contains some basic instructions for how to build your own images, with more docs on that to come.

Alright to close this issue?
