### ISSUE TITLE
Catalog: Make Catalog Table Headers Customizable

### ISSUE THREAD

**Issue by tradcliffe-expediagroup** [backstage/backstage#3560]
Catalog table column headers are hard coded currently in the [open source Backstage](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L35-L66). If we want to make changes to these to align better with our companies metadata, we have to make changes in our copy of the open source catalog, which we want to avoid. So our request is to do the work of making these customizable and contributing it back to Backstage. 

## Feature Suggestion

Once approved, I can do the work for this feature request. 

## Possible Implementation

Our idea to implement this is to follow a similar pattern found in [this PR](https://github.com/backstage/backstage/pull/2791/files), minus the routing changes. 

## Context

We are trying to accomplish making Backstage more customizable. This will allow us to customize the catalog table to match with different companies metadata, without having to change the code inside the plugin

**Comment by stefanalund** [comment]
+1

Would you like me to assign you?

**Comment by tradcliffe-expediagroup** [comment]
Yes please Stefan!

**Comment by JacobValdemar** [comment]
+1
Also something we could use :)

**Comment by JacobValdemar** [comment]
I think you should try to make sure it will be compatible with https://github.com/backstage/backstage/issues/3274, so you can also filter based on the headers :-)

**Comment by Rugvip** [comment]
@tradcliffe-expediagroup heads up that https://github.com/backstage/backstage/issues/3414 may affect this work. It may make it more straight-forward to implement but could also add some additional requirements. If unsure you could sync and discuss ideas in this issue or in a draft PR.

**Comment by tradcliffe-expediagroup** [comment]
Thank you @JacobValdemar and @Rugvip. I will take a look at both of these PRs and let you know if I have any questions. Thank you!
