### ISSUE TITLE
Can't build backend docker container

### ISSUE THREAD

**Issue by rlangfordBV** [backstage/backstage#3578]
Can't build backend docker container

## Expected Behavior

A docker container is built

## Current Behavior

When running `yarn workspace backend build`, it prints the following

```
Generated an empty chunk: "index.d"
Generated an empty chunk: "index.d"
```

## Steps to Reproduce

```
$ uname -a
Darwin rlangford-retina.local 18.7.0 Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64
$ node --version
v14.15.1
$ yarn
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 1.12s.
$ yarn tsc
yarn run v1.22.10
$ tsc
✨  Done in 3.95s.
$ yarn backstage-cli -V
yarn run v1.22.10
$ /path/to/backstage/node_modules/.bin/backstage-cli -V
0.4.0
✨  Done in 0.18s.
$ yarn workspace backend build
yarn workspace v1.22.10
yarn run v1.22.10
$ backstage-cli backend:build
Generated an empty chunk: "index.d"
Generated an empty chunk: "index.d"
✨  Done in 1.21s.
✨  Done in 1.55s.
$
```

## Your Environment

- NodeJS Version (v12): v14.15.1
- Operating System and Version (e.g. Ubuntu 14.04): macOS, Mojave (10.14.6)

I see this is also mentioned in issue [#3304], but I don't understand how this is resolved.

**Comment by Rugvip** [comment]
The `Generated an empty chunk: "index.d"` are warnings, afaik because the backend package doesn't export any types. I think we'll be able to get rid of them as part of #3153 

The backend docker containers are for the time being build with `yarn backstage-cli backend:build-image`, which is usually run as a yarn script of the backend package with an additional `--build` flag.

Help screen for that command:

```bash
$ yarn backstage-cli backend:build-image --backstage-cli-help
Usage: backstage-cli backend:build-image [options]

Bundles the package into a docker image. All extra args are forwarded to `docker image build`.

Options:
  --build                 Build packages before packing them into the image
  --backstage-cli-help    display help for command
```
