### ISSUE TITLE
TechDocs: Show status of build process similar to scaffolder

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#3579]
## Feature Suggestion

If TechDocs is configured to build docs, tell the user about the progress. Something like this

```
-> Fetching documentation files from source
   Generating TechDocs site
   Storing files to storage
```

```
✅ Fetching documentation files from source
-> Generating TechDocs site
   Storing files to storage
```

```
✅ Fetching documentation files from source
✅ Generating TechDocs site
-> Storing files to storage
```

_and then docs will appear._

## Possible Implementation

Scaffolder creates a new job for each scaffolding process and then fetches the job status every second. Implement the feature here in a similar way.

Or perhaps, use web sockets?

## Context

As of now, if a user opens a TechDocs site and if docs are being built before it loads, there is no status of the process. Given the waiting period could be 20-60 seconds, it's good to see some status.

Might be convenient to start work after https://github.com/backstage/backstage/pull/3432 is merged.

**Comment by freben** [comment]
We'll probably end up doing significant work to build a little task coordination system for the new scaffolder. Looks like that may happen during Q1. This will be required to make it scale to multiple hosts.

This task is a great idea. Maybe our t goals overlap. Let's coordinate!

**Comment by OrkoHunter** [comment]
@freben Awesome to hear about the step towards a better approach. I'll be happy to help and/or follow closely.

**Comment by Fox32** [comment]
This would also be a good place to show errors in the generation process. Till now they are only outputed to the stdout of the backend process, which normal users won't have access too.

**Comment by Fox32** [comment]
Seems to be somewhat related: #4111

**Comment by Fox32** [comment]
Parts of this are implemented now. We have a UI that's shows build logs and errors. But there is coordination for task in multiple backend replicas or parallel requests.

**Comment by OrkoHunter** [comment]
Thanks @Fox32 ! The problem described in the context of this issue seems to be resolved now. I'd like to close this!
