### ISSUE TITLE
GitHub plugins should have the option of using a PAT stored in the backend

### ISSUE THREAD

**Issue by omerlh** [backstage/backstage#3586]
## Feature Suggestion

Today, many GitHub plugins (like `RoadieHQ/backstage-plugin-github-pull-requests`) requires the user to login with GitHub for them to operate properly. This is while Backstage has support for GitHub integration with PAT.

I would like to use other authentication methods while keep using GitHub plugins - so I would like plugins to be able to use either the existing PAT or even GitHub application for authentication to GitHub.

## Context

RoadieHQ/backstage-plugin-github-pull-requests#33

**Comment by OrkoHunter** [comment]
Perhaps [@backstage/integration](https://github.com/backstage/backstage/tree/master/packages/integration) package can be used for this. [`integrations`](https://github.com/backstage/backstage/blob/b6aa734b2338837dce951cc449af3641d31e7e2f/app-config.yaml#L87-L91) in `app-config.yaml` looks to be the single source of truth for GitHub Personal Access Token.

**Comment by dtuite** [comment]
The GitHub Actions plugin in the main Backstage monorepo is probably an even better example. It would be great if a pattern could be established for other plugins to follow.

This potentially overlaps with plans to move to GitHub Apps in future?

**Comment by Rugvip** [comment]
The PAT or tokens derived from GitHub App keys can't be accessed by the users directly, as they have a much broader scope than what the user is supposed to have access to in most scenarios. For this use-case we'd really need a backend that can properly filter requests based on what the user should have access to in GitHub. There may be some use-cases were we don't really need to filter things, like listing Pull Requests, but we'd still need backend logic to ensure that the tokens are not being used for other things.

Overall this is an extremely common pattern at this point, not only for GitHub or even repo providers. Many plugins rely on proxy configuration to inject tokens in requests, which is not a great pattern from a security point of view. For some services it might be fine but it's way too easy to make mistakes.

What I think we could search for is a good pattern for plugins to provide a thin backend API proxy layer, either calling through directly to upstream endpoints or injecting some additional logic. GraphQL is a good candidate for this, as it both gives us some schema and tooling around it, some clear patterns in both the frontend and backend, and also possibility of having generic solutions for observability and microservice patterns such as circuit breaking etc.

**Comment by andrewthauer** [comment]
From my current understanding, using the existing `backstage/integrations` token will result in rate limiting (e.g. 5000 requests per hour) for the user that created the token (not GH logged in user). This would include all catalog refresh calls along with anything via a backend proxy accessed by the frontend. I think this would also potentially apply to GH apps, but I'm not sure on the details. We've already started hitting rate limits for catalog refreshes even with a subset of repos setup.

**Comment by Rugvip** [comment]
@andrewthauer the `backstage/integrations` will move over to using GitHub Apps as well, PAT should only be for experimental setups long-term

**Comment by andrewthauer** [comment]
Curious, what will the backend would use for catalog refreshes, etc. in the case of GH apps? Afaik this scenario could also be affected by rate limiting for the user that owns the GH app.

**Comment by Rugvip** [comment]
@andrewthauer With GitHub apps the rate-limiting should hopefully be much less if an issue, since catalog refreshes will primarily be done in reaction to webhooks. I also think we have some opportunities to be a bit smarter about how catalog refreshes of individual entities are done, e.g. using data that already exists in the catalog to not do unnecessary work, instead of doing a full refresh and then comparing at write time

**Comment by andrewthauer** [comment]
@Rugvip - For sure. Webhooks could definitely help, but could also make it worse depending on how frequent code is changing, etc. Caching and using existing data will likely be key.

**Comment by Fox32** [comment]
We only refresh our catalog entries from GitHub once an hour as we would otherwise hit the rate limiting of PAT very quickly. While I think GitHub apps make this a bit better, there are still quotas and they aren't so much higher (12,500, factor 2.5). The key is really the event driven approach.

Beside that I think we should do as much as possible in the context of the current user to avoid using PAT and GitHub Apps (except for the catalog ingestion). Like GitHub actions, showing PRs, creating PRs, ...

**Comment by freben** [comment]
See [this comment](https://github.com/backstage/backstage/issues/3734#issuecomment-745933782) about leveraging etag match 304s not counting towards quotas.
