### ISSUE TITLE
Failed to build docker images

### ISSUE THREAD

**Issue by omerlh** [backstage/backstage#3587]
## Expected Behavior

Deploying a production instance of backstage should be simple

## Current Behavior

Not enough docs, after digging around I find that I probably should do something like:

```
yarn
yarn workspace backend run build-image 
```

From the root folder of the project.

This works fine on my local machine, but fail with a very unclear error in the CI:

```
yarn workspace v1.22.10
yarn run v1.22.10
$ backstage-cli backend:build-image --build --tag gcr.io/snyk-main/backstage
$ /home/circleci/project/node_modules/.bin/lerna run --scope backend --scope app build
lerna notice cli v3.22.1
lerna info ci enabled
lerna notice filter including ["backend","app"]
lerna info filter [ 'backend', 'app' ]
lerna info Executing command in 2 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in 'app'
lerna ERR! yarn run build stdout:
$ backstage-cli app:build
Loaded config from app-config.yaml, app-config.local.yaml
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
Env config file 'app-config.production.yaml' is not loaded as APP_ENV and NODE_ENV-based config loading has been removed
To load the config file, use --config <path>, listing every config file that you want to load
internal/child_process.js:403
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at spawn (child_process.js:553:9)
    at Object.fork (child_process.js:121:10)
    at fork (/home/circleci/project/node_modules/worker-farm/lib/fork.js:17:36)
    at Farm.startChild (/home/circleci/project/node_modules/worker-farm/lib/farm.js:107:16)
    at Farm.processQueue (/home/circleci/project/node_modules/worker-farm/lib/farm.js:288:10)
    at Farm.<anonymous> (/home/circleci/project/node_modules/worker-farm/lib/farm.js:98:21)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -12,
  code: 'ENOMEM',
  syscall: 'spawn'
}
error Command failed with exit code 1.
```

Probably related to backstage/backstage#2994

## Possible Solution

* Document the flow for deploying backstage images (ideally, with common CI tools like GitHub actions)

## Steps to Reproduce

1. Create new backstage project 
2. Try to build docker image in CircleCI

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): Circle docker image for node
- Browser Information:

**Comment by Rugvip** [comment]
Seems like it's a memory issue, as it's throwing `ENOMEM`. You could reduce the work that the CLI is attempting to do in parallel by setting `PARALLEL_ENV_VAR=1` in the env.

@andrewthauer, is this the issue or a similar one to what you were facing?

**Comment by andrewthauer** [comment]
Yep, seems like it. CircleCI boxes incorrectly report the number of CPU's so tasks like `terser` may fail on their default `medium` machines.

You could try setting this first in the CI environment:

```bash
NODE_OPTIONS="--max-old-space-size=4096"
```

If that doesn't help then try setting which will limit `terser` to 2 parallel build tasks. This has been working for us consistently for the past 2-3 months now.

```bash
BACKSTAGE_CLI_BUILD_PARALLEL="2"
```

**Comment by omerlh** [comment]
Yep, it took my some time (the config file error was really confusing) but I figured this was it and fixed it.
Non the less, it might be good to have an example build / release pipeline

**Comment by andrewthauer** [comment]
@omerlh - Was the config error misleading in this context? I ended up contributing the `BACKSTAGE_CLI_BUILD_PARALLEL` fix a while back, but it was decided to keep it undocumented while it was being tried out. For us it's been working well, so maybe it's time to document it. @Rugvip - Where would be the best place to document this? Can we output environment variables in the CLI --help? I suspect it needs to be documented in a couple of places probably.

**Comment by omerlh** [comment]
This one: 
> Env config file 'app-config.production.yaml' is not loaded as APP_ENV and NODE_ENV-based config loading has been removed
To load the config file, use --config <path>, listing every config file that you want to load

It took me a while to figure I can just ignore it and it has nothing to do with my actual build issue

**Comment by Rugvip** [comment]
> This one:
> 
> > Env config file 'app-config.production.yaml' is not loaded as APP_ENV and NODE_ENV-based config loading has been removed
> > To load the config file, use --config , listing every config file that you want to load
> 
> It took me a while to figure I can just ignore it and it has nothing to do with my actual build issue

Yep I think we can remove that warning at this point tbh, it's been gone for quite a while at this point and is a potential source of confusion.

**Comment by Rugvip** [comment]
@andrewthauer In the CLI docs 😅  (they don't exist, I wanna write some proper ones but still a bit swamped)

**Comment by regicsolutions** [comment]
@omerlh do you have a sample Dockerfile i can reference? i have the app-backend plugin enabled and was looking to build one image with the frontend and backend if possible.

**Comment by andrewthauer** [comment]
If it helps, this is more or less what we have for running the app-backend:

```Dockerfile
FROM node:14-buster
WORKDIR /usr/src/app
COPY yarn.lock package.json ./
COPY app-config.yaml app-config.production.yaml ./
COPY packages/app ./packages/app
COPY packages/backend ./packages/backend
COPY plugins/welcome ./plugins/welcome
RUN yarn install --frozen-lockfile --production
CMD ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.production.yaml"]
```

and then build with:

```bash
yarn tsc && yarn workspace backend build && yarn workspace app build:prod && docker build . -t backstage
```

**Comment by regicsolutions** [comment]
Thanks @andrewthauer have you tried running the container as non-root user?

**Comment by andrewthauer** [comment]
@regicsolutions - Not with this image. But if you used the official node base images you could easily try it out with the `node` user.

**Comment by regicsolutions** [comment]
@andrewthauer I am getting the following error with this Dockerfile in my /backend folder what am i missing?: 

```
$ yarn tsc && yarn workspace backend build && yarn workspace app build:prod && docker build . -t backstage
yarn run v1.22.1
$ tsc
Done in 3.35s.
yarn workspace v1.22.1
yarn run v1.22.1
$ backstage-cli backend:build
Generated an empty chunk: "index.d"
Generated an empty chunk: "index.d"
Done in 1.65s.
Done in 1.92s.
yarn workspace v1.22.1
yarn run v1.22.1
error Command "build:prod" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
```

**Comment by andrewthauer** [comment]
Oh,sorry that was a custom npm script. You can probably just use `build` in your case.

**Comment by regicsolutions** [comment]
@andrewthauer That worked, Thanks! Assuming your npm script allows you to build a specific environment? Would love to check it out!

**Comment by andrewthauer** [comment]
The `build:prod` just adds a custom config file since we don't use `production` as our environment name. It's unlikely needed for most people. To be honest, I'm not sure this is actually needed with the `app-backend` now that I think about it. It might be a hold over from when we we had the frontend split out into another container.

```json5
// in packages/app/package.json
scripts: {
  "build:prod": "backstage-cli app:build --config ../../app-config.yaml --config ../../app-config.some-other-env.yaml"
}
```

**Comment by regicsolutions** [comment]
@andrewthauer Thanks for sharing! With the app-backend plugin this script should technically live in the backend package.json no? definitely see it coming in handy when building multiple environments, each having there own command 😃

**Comment by adamdmharvey** [comment]
Any additional action on this, or perhaps close ? I know the Docker relating doco has been updated quite a bit, and with the progression of the project newer issues relating to the newer code may be a bit more valuable.  I'd suggest close but open to other opinions.

**Comment by benjdlambert** [comment]
Think this is stale now and hopefully should be fixed with the latest docs here: https://backstage.io/docs/getting-started/deployment-docker
