### ISSUE TITLE
Registering existing component should link to the component

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#3591]
When I add a new `catalog-info.yaml` file to Backstage, I find myself wanting to view the component. However, there is no button or link to the component in the catalog.

## Expected behaviour

The importer should link to the created component in the last step of the process.

## Current behaviour

![Screenshot 2020-12-06 at 11 54 22](https://user-images.githubusercontent.com/562403/101281287-12006480-37c6-11eb-8289-0052f5ed05af.png)

The link to the component is visible on step 2, but that panel closes when I click the "Next" button.

![Screenshot 2020-12-06 at 11 54 15](https://user-images.githubusercontent.com/562403/101281322-2b091580-37c6-11eb-8cfb-750c9a0a73e0.png)

**Comment by dtuite** [comment]
This should have the Good First Issue label.

**Comment by Fox32** [comment]
Would also like if the "Next" button on the 2 step would be called "Register" or something like that. Because that's the critical point were something is changed.

**Comment by Fox32** [comment]
> Would also like if the "Next" button on the 2 step would be called "Register" or something like that. Because that's the critical point were something is changed.

Nevermind, looks like it is already imported at that stage 😉 . Maybe we first perform a dry run instead? The old dialog supports that: https://github.com/backstage/backstage/blob/master/plugins/register-component/src/components/RegisterComponentPage/RegisterComponentPage.tsx#L90 
We could show a preview and then offer the user to "Register" the location.

**Comment by padraigobrien** [comment]
I would like to take on this issue if that cool with yall?
