### ISSUE TITLE
Connect repo with lgtm.com/Semmle for static code scanning (SAST)

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3607]
## Feature Suggestion

GitHub purchased https://lgtm.com/ / Semmle a while back, and offers it free to open source projects.  Recommend tying into that service.

I ran it manually and it found one error, three warnings, and two recommendations, including things like code paths that are unreachable, and other good stuff:

![image](https://user-images.githubusercontent.com/33203301/101396766-d1721b00-3899-11eb-8c34-60e2c4aea062.png)

---

![image](https://user-images.githubusercontent.com/33203301/101396556-7f30fa00-3899-11eb-9225-a36bdf9fad50.png)

---

![image](https://user-images.githubusercontent.com/33203301/101396951-0a11f480-389a-11eb-8924-fd027590b0a9.png)

---
![image](https://user-images.githubusercontent.com/33203301/101397342-90c6d180-389a-11eb-9c25-fc2d09875036.png)

## Possible Implementation

Install the Lgtm.com app into the repo:
https://github.com/marketplace/lgtm

You can also connect it to your GitHub.com account, it'll find your related apps, and give you a one button click to "Enable for your project" (See screen cap above).

It will then tie into PRs for review.

## Context

Enhance static code review with a SAST tool, and find security issues and code findings before merge!

**Comment by Fox32** [comment]
I wonder how this differ to the already enabled [codeql analysis](https://github.com/backstage/backstage/blob/10052e0d7f8914fd56b08a1ce5e5ab9e49d45aca/.github/workflows/codeql-analysis.yml#L46). At least the things you found using LGTM.com were not displayed there. But maybe it only displays security related stuff.

**Comment by adamdmharvey** [comment]
Great question. So Semmle is basically the _front-end_ to those same CodeQL, since both come from GitHub (a la Microsoft).

The nice thing about Semmle is it has the app which interacts/feeds back into the PRs and such (more like the changeset bot this repo has?) to tell users there are issues?  i think there's a nice value add there, and i'll  amid to not being fully up on the CodeQL action but they do refer to each other!

https://github.com/github/codeql

> CodeQL: the libraries and queries that power security researchers around the world, as well as code scanning in GitHub Advanced Security (code scanning), LGTM.com, and LGTM Enterprise

https://github.com/github/codeql-action

And I'll be honest, I can't if there is any guidance of when to use one or the other!  But the interface to LGTM/Semmle, and the human context it gives, is really valuable. (showing you links back to relevant CVEs and MITRE reports, that sort of thing)

**Comment by adamdmharvey** [comment]
Also Semmle has the nice reports which the raw GitHub Action will lack:

![image](https://user-images.githubusercontent.com/33203301/101791205-44190b80-3ad1-11eb-92cb-38f4a992e4de.png)
![image](https://user-images.githubusercontent.com/33203301/101791265-54c98180-3ad1-11eb-90fe-d9f51b107493.png)

**Comment by adamdmharvey** [comment]
While this would elevate the info beyond the maintainers, I can appreciate that having the GitHub.com based security alerts available to maintainers is valuable and this duplication may not be necessary. Given that, closing!
