### ISSUE TITLE
Extend group entity with additional profile details

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#3616]
## Feature Suggestion

Right now the group entity only has a basic `name` (technical) and a `description`, while the user also has a `profile` section containing `displayName`, `picture`, and `email`. These details can be displayed on the group entity page to provide some more details and contact options for a group. The picture and display name might also be used elsewhere to reference the group. The `displayName` would be useful for cases were the group name does not nicely translate into an entity name (because it uses characters that are not allowed in the entity name).

## Possible Implementation

I propose to add the same profile section to groups that users have. In a second step the existing imported can be extended to emit the new details. I would appreciate input on this!

## Context

External user sources have different levels of support for these features:

* GitHub provides a description, picture and a name: ![image](https://user-images.githubusercontent.com/648527/101483326-502d8d80-3958-11eb-9e02-f6c7fb4bf53b.png)
* Microsoft provides description, display name, picture and e-mail: 
![image](https://user-images.githubusercontent.com/648527/101483696-d5b13d80-3958-11eb-9a75-c5cc52e181fd.png)
* LDAP provides free form data and it depends on the organization whether these details are available.

**Comment by freben** [comment]
Absolutely! This makes a lot of sense and has been asked for several times.
