### ISSUE TITLE
Search missing from newly created Apps

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#3618]
## Feature Suggestion

Global search is a feature that's definitely interesting for anyone adopting Backstage, but it is missing from the default set of plugins when you create a new Backstage app.

## Possible Implementation

Should be similar to how "API docs" was added:

https://github.com/backstage/backstage/pull/3460/files

Ping @emmaindal

**Comment by tudi2d** [comment]
I would like to add search to the default set of plugins 👍

**Comment by stefanalund** [comment]
All yours @tudi2d -- thanks!

**Comment by emmaindal** [comment]
Awesome, thank you @tudi2d 🎉

**Comment by tudi2d** [comment]
Hey - I have a little question concerning the local debugging of `default-app`. 

**Problem:** I can´t figure out how to serve & debug the "default-app"
**Approach:** I tried a few things: Running `yarn run backstage-cli app:serve` in `./packages/create-app/templates/default-app` was the script I expected to work. My OS is Windows - I also tried the command using WSL Ubuntu. As far as I could understand the `readline` Error (see image) relates to nodejs. My node Version is v14.4.0.
**What I want to know:** Can you spot a common mistake? Did I do something fundamentally wrong trying to debug the "create-app"?

![image](https://user-images.githubusercontent.com/8904624/102529942-ec663b80-40a0-11eb-9c45-f3bc12de72f8.png)

In general: Should I ask question in the Issue itself or jump over to Discord and message people directly?

Thanks in advanced for any help! :)

**Comment by freben** [comment]
@tudi2d Well this is a completely different issue that kinda gets hijacked :) You can't run inside the template, please follow https://backstage.io/docs/getting-started/ and then you are more than welcome to pop by Discord with follow-up questions (or to post new separate issues as appropriate). No need to ping individuals - we are on a shared goalie schedule and somebody typically gets back to you some time later.

**Comment by freben** [comment]
@tudi2d I think when you make changes to the create-app template, you will want to run the actual create-app script to get everything generated and filled in properly.

In the repo root:

```bash
yarn backstage-create-app
(give it some name, such as "foo")
cd foo
yarn tsc
yarn start
```

I realise that the feedback loop won't be super fast since creating an app takes a little time (2 minutes on my machine).

**Comment by tudi2d** [comment]
Alright! Thanks for the quick response & have great evening @freben 👍
