### ISSUE TITLE
Add edit button to Missing Annotation Page

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3642]
## Feature Suggestion

When a plugin isn't enabled, the Missing Annotation page is shown.  At the bottom of the example, a Read More button is available to go to the docs to show how to add the annotation. It would be great if this page also included an Edit button to go straight to the meta data to update it as well.

![image](https://user-images.githubusercontent.com/33203301/101584463-bb547f80-39ab-11eb-8144-b8dbbb884043.png)

## Possible Implementation

I got the visual to work with this rough sample code:

```tsx
<Grid container>
  <Grid item>
    <Button
      variant="contained"
      color="primary"
      href="https://backstage.io/docs/features/software-catalog/well-known-annotations"
    >
      Edit Metadata
    </Button>
  </Grid>
  <Grid item>
      <Button
        variant="contained"
        color="primary"
        href="https://backstage.io/docs/features/software-catalog/well-known-annotations"
      >
        Read more
      </Button>
  </Grid>
</Grid>
```

However, what's really needed is essentially to reuse the code in the catalog plugin (https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/createEditLink.ts), but since this annotation is in core I wasn't quite sure how to work that out. (move the catalog code INTO core perhaps?)  Since I'm not quite sure, thought I'd open an enhancement to get other's suggestions/feedback.

## Context

It seems reasonable that as a user if I want say, tech docs to be enabled, the missing annotation page tells me not only how, but gives me a super quick link to go directly to the metadata file to actually edit it.

**Comment by Fox32** [comment]
Nice idea. We should take that we don't add too much to the empty state as it's already hard to use for smaller widgets. See #2827. But freben made some suggestion here that could resolve that issue: https://github.com/backstage/backstage/pull/3479#issuecomment-734920731

**Comment by andrewthauer** [comment]
I like the good idea for a stock setup. However, I think #3217 is what is really needed to customize this in general for an organization. I'm finding many plugins require additional setup before adding an annotation will have any effect. So purely having a link to the `catalog-info.yaml` file may not always be intuitive regarding logical steps.

**Comment by adamdmharvey** [comment]
@andrewthauer I really like your point. What's interesting is there are likely two user populations. The fact that the plugin hasn't been configured to even work, period, is a key point that the Backstage managing team is responsible for.  To your point, it's sort of like an issue for stock setup or just first time a team is setting up a new plugin.

The other users are just all the component users.  It's then in the long term that it's more likely just a missing annotation is whar is preventing the data from displaying, and in that case it's not the Backstage admin team but the component owner who needs to fix it.

I almost wonder if plugins need some sort of extension to the isPluginEnablement techniques like, isPluginConfigured?  Or if that's just going too far, then maybe we do purely expect plugins are working and the annotation is the "only thing"?  What's an example Andrew of additional config, that might be beyond, say, setting up a proxy or a token in a plugin? (i haven't hit any yet, though can see how it might be necessary, with annotation being the last step?)

**Comment by andrewthauer** [comment]
@adamdmharvey - I completely agree. I would say that the first is a bit more nuanced though Possibly split into 2 sub categories. First there are the cases where the backstage managing team needs to configure something globally across the org. The other is when the team needs to do some background work on each entity to configure it. Some examples of the latter for us are `sonarqube` setup requires CI changes, and the new `pagerduty` plugin requires configuring integration keys for services. We are working to automate as much of this as possible, but some things are difficult to do that with.
