### ISSUE TITLE
Better error handling when TechDocs can't find Docker

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3645]
## Expected Behavior

A friendly error message is presented to the user if/when Docker isn't available to generate the docs tab on components.

## Current Behavior

When I have Docker running, the sample "documented-component" correctly displays:

![image](https://user-images.githubusercontent.com/33203301/101588824-38382700-39b5-11eb-8109-3e3f071bc46d.png)

However, when I shut down Docker, I just see this:

![image](https://user-images.githubusercontent.com/33203301/101588933-7897a500-39b5-11eb-95e0-6db6a9342bec.png)

## Possible Solution

I couldn't quite figure out how to trap this error, which I gather comes from the techdocs-backend, but doing some sort of return to the user using `<Alert>` of some type, a more standard error presentation than just raw spitting out the error path would be ideal, something to help guide the user.  Maybe even adding a link to "setting up techdocs" in the doco here?

https://backstage.io/docs/features/techdocs/getting-started

## Steps to Reproduce

Run locally, and,

1. Ensure no Docker daemon is running
2. Start up raw app latest off `master` branch
3. View the "documented-component" sample entity
4. Click docs tab
5. See error screen shot above

## Your Environment

- NodeJS Version (v12): v12.16.2
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL2 Ubuntu 18.04
- Browser Information: Microsoft Edge (Chrome)

**Comment by adamdmharvey** [comment]
Any fixes for #3660 may also fix this, as I believe the point in the other issue (which is very nicely laid out!) is that the various errors display poorly to the end user.

**Comment by adamdmharvey** [comment]
This was fixed via https://github.com/backstage/backstage/pull/4314, as seen here:

![image](https://user-images.githubusercontent.com/33203301/107306827-98018b80-6a53-11eb-8161-f1e90ba8e25c.png)

Resulting backend error:

```
2021-02-09T02:20:12.611Z backstage error Failed to generate docs from /tmp/backstage-EsUwnM
into /tmp/techdocs-tmp-BcmhQJ with error This operation requires Docker.
Docker does not appear to be available. Docker.ping() failed with:
connect ECONNREFUSED /var/run/docker.sock type=errorHandler stack=Error:
Failed to generate docs from /tmp/backstage-EsUwnM into /tmp/techdocs-tmp-BcmhQJ
with error This operation requires Docker. Docker does not appear to be available.
Docker.ping() failed with: connect ECONNREFUSED /var/run/docker.sock
```

It would be nice to be able to even further trap THAT error, and generate a custom error object specifically for a Docker socket error as we talked about separately @OrkoHunter, so that a nuanced msg could be displayed to the user.  But the ask here to improve the error handling is good for now so closing this bug to eliminate some noise.

**Comment by cmoulliard** [comment]
Is there a workaround when backstage runs as a pod on kubernetes and cannot also access docker ? @adamdmharvey

**Comment by adamdmharvey** [comment]
@cmoulliard This particular ticket was about trapping the error itself for when Docker isn't available; so that one was fixed.

Are you noting that if you run Backstage in pods, you still get the raw error (just text within the nav frame) and not the friendly one? or is it more of a question on how do you setup Backstage and TechDocs with k8s?

If the former, i might suggest a new ticket spun out and if you could provide the exact steps to reproduce that might be helpful to the project community.

If the latter, there is info on [setting up Backstage with Kubernetes](https://backstage.io/docs/deployment/k8s) in the documentation, and if any further clarification that might be better suited for a Discord question or even maybe query in the [Discussions](https://github.com/backstage/backstage/discussions) ?

**Comment by cmoulliard** [comment]
> Are you noting that if you run Backstage in pods, you still get the raw error (just text within the nav frame) and not the friendly one?

Here is the error generated when uusing backstage with TAP-GUI - https://docs.vmware.com/en/Tanzu-Application-Platform/1.0/tap/GUID-tap-gui-about.html

![Screenshot 2022-03-03 at 16 53 44](https://user-images.githubusercontent.com/463790/156601447-ed8aac27-e3cf-45a0-b190-c7c71458bfba.png)

**Comment by adamdmharvey** [comment]
Got it. I think that might be worthy of a new issue, as the error is being elevated to the UI, but in your example and screen shot, it's not possible to read and so that could/should be improved! it may be that the CSS for that heading doesn't expect a very long string and so it's writing over itself, but definitely looks like a bug.

I think what I would suggest is pull any queries out of this now closed issue so you can get better visibility to either fixing bugs to elevate issues to the UI, and/or if you're looking to get an issue fixed through discussions or discord!  Hope that helps!

**Comment by cmoulliard** [comment]
> I think that might be worthy of a new issue, as the error is being elevated to the UI, but in your example and screen shot, it's not possible to read and so that could/should be improved! it may be that the CSS for that heading doesn't expect a very long string and so it's writing over itself, but definitely looks like a bug.

Ok. will then create a new issue from my comment
