### ISSUE TITLE
A simple getting-started that just .... works?

### ISSUE THREAD

**Issue by IliaGe** [backstage/backstage#3650]
A simple helm package that can just install & start using

## Feature Suggestion
It's been a whole day now that I'm trying to get the app to work outside of my local laptop...
I never had such a bad experience with a CNCF project :\

## Possible Implementation
Why aren't there any public available ready images for the backend + frontend?

**Comment by Rugvip** [comment]
Seen this question a couple of times now, enough to add it to the FAQ :grin: #3653

The docker build is still WIP though, even though there's a something in place right now we still have https://github.com/backstage/backstage/issues/3347 to deal with. Hoping to get a flow in place in the app and this repo that makes a bit more sense once that's solved.

If you have any specific questions about the flow mentioned in the updated FAQ please open a new issue or pop by Discord!
