### ISSUE TITLE
Add PagerDuty plugin to Marketplace

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#3663]
## Feature Suggestion

Add PagerDuty plugin to the Backstage plugin marketplace: https://backstage.io/plugins

## Possible Implementation

https://github.com/backstage/backstage/tree/master/plugins/pagerduty

https://backstage.io/docs/plugins/add-to-marketplace

## Context

By adding plugins to the Marketplace we improve discovery and reuse.

**Comment by stefanalund** [comment]
Possible icon to use: https://avatars2.githubusercontent.com/u/766800?s=200&v=4

![icon](https://avatars2.githubusercontent.com/u/766800?s=200&v=4)

**Comment by keshann93** [comment]
Hi @stefanalund, I would like to take up this task

**Comment by freben** [comment]
assigned.

**Comment by keshann93** [comment]
I hope we can close this issue

**Comment by freben** [comment]
Yes!
