### ISSUE TITLE
[RFC] Allow GitHub Actions or Jenkins as backend for jobs

### ISSUE THREAD

**Issue by taras** [backstage/backstage#3708]
**Status:** Open for comments

*I'm not advocating for a change (yet). I'd love to find out what people think about the idea and discussions happened on the subject*

## Need

Backstage uses long-running jobs to scaffold projects & generate documentation. The actual jobs themselves run with Docker or executables installed on the Backstage container. The presence of Docker is not guaranteed in all deployment environments(for example [AKS 1.19 is not shipping with Docker](https://github.com/Azure/AKS/issues/1989)).  Adding executables to the Backstage container makes Backstage container images bigger and complicates managing executables' dependencies.   

We need a robust and reliable way to run jobs that can be isolated into their own containers without requiring Docker.

## Proposal

Allow using GitHub Actions or Jenkins to run jobs instead of a custom jobs system. Each job can be expressed as a workflow in a GitHub repository or a Jenkins job. We already have Private Access Tokens for GitHub authentication and token for Jenkins for those who use it.

## Alternatives

I'm not sure. This is what I'd like to find out.

## Risks

Not every project uses GitHub Actions or Jenkins which can make it harder for them to get started with Backstage. We'll need to maintain the existing internal jobs mechanism & support for running jobs in an external automation system. This will increase maintenance overhead for the Backstage project.

**Comment by benjdlambert** [comment]
I'm wondering if the basis for some of this work could be captured in #2771.

We basically want to make it easier to be able to compose custom logic in steps, and maybe one of those steps could be to start a workflow in jenkins with parameters and poll until completion and grab the log output and dump in the job in the scaffolder?

**Comment by taras** [comment]
> We basically want to make it easier to be able to compose custom logic in steps, and maybe one of those steps could be to start a workflow in jenkins with parameters and poll until completion and grab the log output and dump in the job in the scaffolder?

Yeah, that sounds good.

**Comment by taras** [comment]
@benjaminr another use case for scaffolder is being able to trigger a webhook to register the newly created project with Jenkins (for example)

**Comment by freben** [comment]
Repeating from the other ticket:

My current thinking is that the scaffolder is a good fit for a broker + workers architecture. In such a solution, the "central" scaffolder backend would mostly deal with receiving task descriptions and persisting them, and coordinating the work of distributing and tracking them as they get picked up and worked off by the worker nodes. Then, the workers will be "just another service", nothing special about them, and there's no need to "spawn" anything at all since they churn away locally and are deployed just like any other service.

**Comment by freben** [comment]
That being said, I do understand that this jenkins-driven way of doing things could be beneficial as well, particularly in the situation you describe.
