### ISSUE TITLE
Support spawning containers through Kubernetes API

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#3710]
## Feature Suggestion

Hello all. At my place we've been looking into using backstage and have just bumped into something (sorry if this has been discussed before). 

Several plugins (eg techdocs and the scaffolder) work by spawning external processes, with the choice of running either locally or with Docker. Running locally is fine in development but it's not ideal if your API server gets OOM-killed because techdocs had a lot of work to do; running in Docker is better in principle, but because Backstage talks directly to the Docker agent, it's not ideal if you're running in a modern cloud environment (ie Kubernetes). The API server would have to be run as a privileged container which is a security nightmare. 

What would be nice is if it also supported spawning these subprocesses by talking to the Kubernetes API. This would obviously be a complicated thing to implement, but would bring it in line with how other things are typically run nowadays.

## Possible Implementation

An implementation might create a `Job` in a given cluster and namespace that runs the subcommand, and watches until the job is complete, then doing whatever final necessary steps. 

A significant complication is with storage - the current implementation uses Docker mounts to extract file output. Doing the equivalent with k8s storage APIs will involve code gymnastics of some sort.

Maybe this would also present an opportunity to centralise the 'runner' functionality (which is largely duplicated between different plugins at the moment AFAICT - eg, [here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/stages/templater/helpers.ts) and [here](https://github.com/backstage/backstage/blob/master/packages/techdocs-common/src/stages/generate/helpers.ts))

**Comment by tragiclifestories** [comment]
Just saw @taras raise a similar suggestion here for running in other backends https://github.com/backstage/backstage/issues/3710

**Comment by freben** [comment]
My current thinking is that the scaffolder is a good fit for a broker + workers architecture. In such a solution, the "central" scaffolder backend would mostly deal with receiving task descriptions and persisting them, and coordinating the work of distributing and tracking them as they get picked up and worked off by the worker nodes. Then, the workers will be "just another service", nothing special about them, and there's no need to "spawn" anything at all since they churn away locally and are deployed just like any other service.

**Comment by tragiclifestories** [comment]
So then, I guess, the techdocs plugin could be implemented as a sort of subfeature of the scaffolder?

**Comment by tragiclifestories** [comment]
Wondering if this is now effectively covered by https://github.com/backstage/backstage/issues/3746?

**Comment by benjdlambert** [comment]
@tragiclifestories yep. closing this in favour of #3746
