### ISSUE TITLE
TechDocs: Support AWS S3 as TechDocs external storage (to store and read generated documentation sites)

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#3714]
## Feature Suggestion

In the [TechDocs Architecture](https://backstage.io/docs/features/techdocs/architecture), users should be able to use any kind of storage system to store their generated documentation site.

Currently, Google Cloud Storage and Local filesystem are supported. Add support for Amazon S3 buckets as well.

## Possible Implementation

TechDocs has a main [Publisher](https://github.com/backstage/backstage/blob/master/packages/techdocs-common/src/stages/publish/publish.ts) factory class which initialises a publisher based on app's config `techdocs.publisher.type` [in the backend](https://github.com/backstage/backstage/blob/767b679f4388b9296d2f18af12f4f7ccc994b38b/packages/backend/src/plugins/techdocs.ts#L52).

A TechDocs publisher is responsible for two things (two-way communication between `techdocs-backend` and the storage)
1. Publish generated static files to a storage. (Only if the `techdocs.builder` is set to `local` which means Backstage is supposed to locally generate sites from source markdown files and publish to storage)
2. Read files from storage when users visit a TechDocs page (TechDocs requests `techdocs-backend` which uses the Publisher's APIs).

Add a new `amazonS3.ts` publisher [here](https://github.com/backstage/backstage/tree/master/packages/techdocs-common/src/stages/publish) similar to [`googleStorage.ts` publisher](https://github.com/backstage/backstage/blob/master/packages/techdocs-common/src/stages/publish/googleStorage.ts). The S3 publisher needs to implement [`PublisherBase`](https://github.com/backstage/backstage/blob/767b679f4388b9296d2f18af12f4f7ccc994b38b/packages/techdocs-common/src/stages/publish/types.ts#L40-L64) abstract class and its four methods. Use Google Storage as an example since S3 is going to be very similar.

Some additional checklist
- Add new configs under `techdocs.publisher`. Update config reference documentation. https://backstage.io/docs/features/techdocs/configuration
- Add steps about how to use Amazon S3, similar to GCS here https://backstage.io/docs/features/techdocs/using-cloud-storage
- Add changesets for the plugin and packages (packages/techdocs-common and plugins/techdocs-backend)
- Make sure to add tests and mocks. :) (Use the PR below for example on GCS.)

## Context

PR which added Google Cloud Storage support - https://github.com/backstage/backstage/pull/3432

Feel free to ask questions/clarifications here. You can also use `#docs-like-code` channel on Discord for any help (we can pair program together if that helps).

**Comment by ayshiff** [comment]
@OrkoHunter Can I work on this ?

**Comment by OrkoHunter** [comment]
Hello @ayshiff ! Awesome, yes. Let us know if you need any kind of help.

**Comment by regicsolutions** [comment]
@ayshiff just checking in to see if you made any progress?

**Comment by OrkoHunter** [comment]
Hey @regicsolutions, the PR is open at #3794.
