### ISSUE TITLE
TechDocs: Make requestUrl and storageUrl optional configs by using discovery APIs

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#3715]
As of now, TechDocs has two URLs in its config, [`techdocs.requestUrl` and `techdocs.storageUrl`](https://github.com/backstage/backstage/blob/767b679f4388b9296d2f18af12f4f7ccc994b38b/app-config.yaml#L73-L74). The `requestUrl` is used by TechDocs frontend plugin to discover `techdocs-backend` endpoints, and the `storageUrl` is another endpoint in `techdocs-backend` which acts as a middleware between TechDocs and the storage (where static generated docs site are stored).

These configs need not be defined and can be optional. Using Backstage core's Discovery mechanism, one could get the url for `techdocs-backend`, and use that to construct endpoints for `requestUrl` and `storageUrl`.

Give this feature a backwords compatibility and if the user defines `techdocs.requestUrl` and `techdocs.storageUrl`, continue to use them over discovery API.

## Context

Backend Discovery API https://github.com/backstage/backstage/tree/master/packages/backend-common/src/discovery
Frontend Discovery API https://github.com/backstage/backstage/blob/master/packages/core-api/src/apis/definitions/DiscoveryApi.ts

Suggestion from @freben https://github.com/backstage/backstage/pull/3432/files#r538687470

**Comment by ParthS007** [comment]
@OrkoHunter I want to work on this one. Can you please assign it to me. Thanks :)
