### ISSUE TITLE
TechDocs: Create type for TechDocs Metadata

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#3716]
Every TechDocs site has a TechDocs Metadata (A JSON with information like site name and description). This is stored in a `techdocs_metadata.json` file along at the root of TechDocs storage with other generated documentation site files.

A Techdocs Publisher implements a method called [`fetchTechDocsMetadata`](https://github.com/backstage/backstage/blob/767b679f4388b9296d2f18af12f4f7ccc994b38b/packages/techdocs-common/src/stages/publish/types.ts#L53) which reads the `techdocs_metadata.json` file and responds to TechDocs frontend.

Instead of a responding with string, this method should return a typed object. Create a type like this

```ts
export type TechDocsMetadata = {
	site_name: string
	site_description: string
}
```

in `publish/types.ts`(https://github.com/backstage/backstage/blob/767b679f4388b9296d2f18af12f4f7ccc994b38b/packages/techdocs-common/src/stages/publish/types.ts) and use it in `packages/techdocs-common` and `plugins/techdocs-backend`. `plugins/techdocs-backend` already imports the techdocs-common package. Make the changes to the [Local Publisher](https://github.com/backstage/backstage/blob/767b679f4388b9296d2f18af12f4f7ccc994b38b/packages/techdocs-common/src/stages/publish/local.ts#L91) and [Google Storage publisher](https://github.com/backstage/backstage/blob/767b679f4388b9296d2f18af12f4f7ccc994b38b/packages/techdocs-common/src/stages/publish/googleStorage.ts#L135) as well, since they implement this method. Use the same type defined in `techdocs-common` package in [this `techdocs-backend` endpoint's response](https://github.com/backstage/backstage/blob/767b679f4388b9296d2f18af12f4f7ccc994b38b/plugins/techdocs-backend/src/service/router.ts#L56-L69).

The above changes are in TechDocs backend. TechDocs frontend plugin uses the metadata endpoint defined in TechDocs backend to render those metadata (site name and description). This is done [here](https://github.com/backstage/backstage/blob/767b679f4388b9296d2f18af12f4f7ccc994b38b/plugins/techdocs/src/reader/components/TechDocsPage.tsx#L31). Add the same type defined above in the `plugins/techdocs` package and use it for all the occurrences of the TechDocs Metadata object.

**Comment by mateiidavid** [comment]
Hi 👋  @OrkoHunter thanks for such a detailed description! I'd like to work on this if that's cool :)

**Comment by OrkoHunter** [comment]
@mateiidavid That is awesome! Assigned it to you.

**Comment by mateiidavid** [comment]
Awesome, I'll try to get it done in the upcoming week. Will reach out here or on Discord if I need to clear any assumptions. Thank you!

**Comment by OrkoHunter** [comment]
Happy to help. 😁
