### ISSUE TITLE
TechDocs: Do async build if docs are outdated, serve existing documentation if available

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#3717]
## Current situation

When a user visits a TechDocs page, it checks if the site has been generated or if the site has become outdated. In either case, if Backstage is configured to (re-)generate docs, it blocks the user from reading anything and asks them to wait ~20-60 seconds while the docs are being built.

## Proposed

In case when the site has become outdated but pre-generated docs exist, TechDocs should serve them. It should then trigger an asynchronous build. (Bonus: Once the build is done, and if the user is on an outdated page, the user should be notified that there has been an update to the site, maybe via a small popup.). This is a common behaviour seen on Wikis. In most cases, the users would want to read _something_ even if some bits of the site went outdated a minute ago.

## Possible Implementation

Build asynchronously [here](https://github.com/backstage/backstage/blob/41e8cff82aec6dae4e1b40c80142b6a34a85d71a/plugins/techdocs-backend/src/service/router.ts#L137).

**Comment by freben** [comment]
I would add that the user should ideally be notified from the very start that what they are looking at is stale and being rebuilt, hold on, we'll notify you when it's done.

**Comment by adrianke77** [comment]
If no docs have been built and are still building, the implementation of this could also provide a page saying "Please wait, documentation is being built" or similar notification

**Comment by adrianke77** [comment]
At Grab we're seeing two issues that could be both solved by this issue, one of generation speed (the build could be moved to a worker instead of main thread) and the other being no proper handling of accessing the docs while generation is incomplete (getting 404s and so on).  I may be able to help with this approach in two or three weeks after my current tasks are done.

**Comment by OrkoHunter** [comment]
Awesome to hear that @adrianke77. Happy to mob/pair together on it.

**Comment by adrianke77** [comment]
(Bonus: Once the build is done, and if the user is on an outdated page, the user should be notified that there has been an update to the site, maybe via a small popup.)

This bit would require some kind of streaming mechanism to frontend? For first implementation I would go with a note that says 'A documentation update is in progress and will be viewable in a short while' or something like that, since we don't have a streaming backbone to send signals on right now? (as far as i know)

**Comment by OrkoHunter** [comment]
Yes, this sounds reasonable to me. I agree with the pop-up. I think a background HTTP request from the frontend to backend on an endpoint like `/sync` could be used for the pop-up, to know whether the page (or just the TechDocs site) should be reloaded.

**Comment by adrianke77** [comment]
As in a polling request to check when the build is done?

**Comment by OrkoHunter** [comment]
This is the flow that I am thinking, considering we won't have to change too much. But feel free to suggest alternative approaches

1. User loads a page on TechDocs frontend.
2. TechDocs frontend directly requests the storage via TechDocs backend and serves the page with assets. (No checks for page being outdated or unavailable here, no blocking request, since in the most common reading experience, pages don't update that frequently.)
3. Then, a small component on TechDocs frontend, like a status button/component sends a request to the backend and communicates the status to the user.

3a. Step 3 could be done by a single endpoint `/sync` which immediately responds if the site is up-to-date, or takes some time to build when the site is outdated.

3b. Or we could split the `/sync` into two separate endpoints. One endpoint for retrieving the status, which will return whether or not the site needs re-build, and one endpoint for triggering the build, which responds when the rebuild finishes. On a separate note, the trigger build endpoint can also be used for this https://github.com/backstage/backstage/issues/4071

**Comment by adrianke77** [comment]
'one endpoint for triggering the build, which responds when the rebuild finishes'
We might get a HTTP timeout with this flow, for big doc sites. Which we could handle by requesting the endpoint again?

**Comment by OrkoHunter** [comment]
Yeah @adrianke77 you are right about network timeout and it will be a problem for large sites (it exists even now in TechDocs). That's one reason, why I was unable to install Backstage/TechDocs on Heroku, due to their 30 second timeout setting.

We could make all these changes in TechDocs in a big bang, but I think it will be better to first address the async build flow and then later, improve the endpoint to fix the network timeout issue.

@backstage/maintainers feel free to jump in and share some thoughts. I remember Scaffolder does poll every second to retrieve the status, but maybe the behavior changed or it will soon, I'm not sure. (On a side note, in near future should we also document the "Scaffolder architecture", for people who want some technical overview? 😄 )

**Comment by adrianke77** [comment]
We seem to have enough to go from, I'll get started on the above.

**Comment by adrianke77** [comment]
Suggest I implement for 3a) and the endpoint also takes something like '?forceBuild=true' to trigger a compulsory rebuild, for #4071.

**Comment by adrianke77** [comment]
![image](https://user-images.githubusercontent.com/14866712/110759377-8268c700-8288-11eb-927b-00498c0d7926.png)
![image](https://user-images.githubusercontent.com/14866712/110759453-96142d80-8288-11eb-98f8-9f7c39c925b2.png)

How does this look?

**Comment by OrkoHunter** [comment]
Looks great to begin with! We should probably append the success message (bottom) with "Please refresh to load the latest version.". We should not force refresh the page, to avoid disrupting the reading behavior.

**Comment by adrianke77** [comment]
i'm seeing this behavior where while waiting for the sync endpoint to respond during a newer build, clicking on documentation links in the left index changes the url visible in the address bar but doesn't navigate to the new page. Any idea why this might be?

**Comment by adrianke77** [comment]
Ignore the useNavigate comment I put above, the problem is with logic i added. :/

**Comment by adrianke77** [comment]
@OrkoHunter I'll like to suggest we don't include the forceBuild argument in the MR for this issue, as it seems better include it in #4071 when that gets done,

**Comment by OrkoHunter** [comment]
@adrianke77 Sure, it's alright! :)

**Comment by adrianke77** [comment]
Created PR, https://github.com/backstage/backstage/pull/4968

**Comment by OrkoHunter** [comment]
Great - reviewing now. 🚀

**Comment by adrianke77** [comment]
Is this issue closable now? Since the PR is merged

**Comment by OrkoHunter** [comment]
Yep!
