### ISSUE TITLE
Some Categories are wrong in the marketplace

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#3741]
There's some wrong category lables in the Plugin Marketplace.

AWS Lambda  and Firebase Functions could be Infrastructure instead or something better than monitoring at least.

**Comment by dtuite** [comment]
@mcalus3 could you ensure Roadie plugins have the correct labels please? I will work with you on determining what they should be if needed.

**Comment by iamrajiv** [comment]
@benjaminr I want to work on this.

**Comment by OrkoHunter** [comment]
@iamrajiv Go ahead!
