### ISSUE TITLE
[Plugin] APIGEE 

### ISSUE THREAD

**Issue by Priyabrata-dev** [backstage/backstage#3743]
I do not see any plugin for integrating with APIGEE for Backstage ,Will it work?

**Comment by OrkoHunter** [comment]
Hey @Priyabrata-dev, awesome that you created the issue! Could you also give brief insights about APIGEE and what are some key usecases of it? That would help contributor(s) implementing this plugin. 

Assuming, we are referring to https://cloud.google.com/apigee

**Comment by OrkoHunter** [comment]
Just noticed that #3327 exists, so we can discuss more over there. Should we close this issue?

**Comment by Priyabrata-dev** [comment]
Yes @OrkoHunter  its the same . APIGEE is nothing but the API Management Platform provided by Google where we are exposing all our API Proxies to internal and external  consumer .
And for API discovery we have a Integrated Portal but with limitations so thought if we can leverage Backstage for API Discoveries for internal and external COnsumer?

**Comment by benjdlambert** [comment]
Closing in favor of the duplicate. Let's take the discussion there 👍
