### ISSUE TITLE
[Story] Github Apps Integration

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#3744]
Allow backend plugins to authenticate with Github with a GithubApp.

Be able to grab a token from other plugins which is authenticated on behalf of this plugin.

- [x] #4006
- [x] #4010
- [x] #4126

**Comment by Rugvip** [comment]
Last two parts of this is to get the scaffolder ported, #4126, and to migrate techdocs over to only use `UrlReader.readTree`
