### ISSUE TITLE
Catalog: Horizontal Scalability

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#3748]
Allow multiple instances of the Catalog backend to cooperate and not do duplicate work.

TBD

**Comment by lowjoel** [comment]
Would this need to be generalised to other plugins, like a database API?

Most other applications I've built/used generally relied on a redis/some other in-memory store for keeping track of task lists/distributed locks etc.

**Comment by freben** [comment]
There will have to be some level of distributed coordination written as part of this, yeah, and possibly (but not necessarily) in a form that is reusable by other plugins. We may not want to force people to run redis as well so we may build it on top of the existing database instead, but TBD.

**Comment by lowjoel** [comment]
Yeah, OK. It's possible to provide a Redis-like API (incrementBy, compareAndSwap) with TTL constraints by writing an SQL emulation layer. It won't be pretty, though, but it should at least be (somewhat) correct (if all the nodes have time within a minute of each other... for TTL)

**Comment by freben** [comment]
It'd probably be talking to the database master and not getting absolute timestamps from the clients.

**Comment by lowjoel** [comment]
Don't think we can get SQL databases to impose TTLs on individual records. It'll have to be implemented on the adapter. We can discuss this design once the work actually gets under way, or if it's needed. I suspect we (Grab) may be running into some parallelisation problems, not sure if it's because of imports running in parallel.

**Comment by freben** [comment]
Yeah that's correct, the TTL handling has to be in client code. We have the same kind of locking functionality in place in our legacy internal catalog, so there's some prior art.

**Comment by freben** [comment]
If you see any kind of problem like that, do make an issue! Let's track it.

**Comment by benjdlambert** [comment]
This is still ongoing :)
