### ISSUE TITLE
Catalog: Avoid unnecessary work in the Processors

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#3749]
Avoid refetching data that already exists in the catalog.

TBD

**Comment by benjdlambert** [comment]
Still ongoing!

**Comment by Rugvip** [comment]
So implementation plan for this is to allow each processor to store a piece of information for each entity. A lot of the plumbing for this is in place as we've already made space for it in the processing, https://github.com/backstage/backstage/blob/d89629a85dde7dac6d3af6a8f7a2b4bc87905384/plugins/catalog-backend/migrations/20210302150147_refresh_state.js#L50-L55.

The main piece left is to figure out what the API looks like for processors, how it interacts with different steps, and that we potentially want to make some overall improvements to the catalog processor API while we're at it.

**Comment by Fox32** [comment]
Also want to add that #5323 is kind of related - there it's even more work we can avoid. Having a way to store metadata for attachment is great.
