### ISSUE TITLE
 Catalago registration using repo on azure, does not fill in the filepathtype variable

### ISSUE THREAD

**Issue by gampeixoto** [backstage/backstage#3752]
When trying to pass the link of the repo pointing to the file catalog-info.yaml or template.yaml, the code link does not fill in the variable filepathtype of the parseGitUri library, thus requesting a pull request to add a catalog file.
the link used in the test was [https://dev.azure.com/DEVOPS-RCHLO/cell-cac/_git/cac.backstage.custom?path=%2Fcatalog-info.yaml&version=GBmaster&_a=contents](url)

![image](https://user-images.githubusercontent.com/13747069/102366210-23e8c100-3f97-11eb-950b-69b582d5e7b1.png)

## Expected Behavior

Detect the presence of the .yaml file and skip the step of creating a pull request

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- v14.15.0
- Operating System and Version (e.g. Ubuntu 14.04):
- Windows 10 pro 10.0.18363
- Browser Information:
O Microsoft Edge  87.0.664.60

**Comment by gampeixoto** [comment]
@freben, you can help me?

**Comment by freben** [comment]
@gampeixoto Made #4014 as an attempt at improving things.
