### ISSUE TITLE
Developer Utilities Plugin Request

### ISSUE THREAD

**Issue by Adamseyer** [backstage/backstage#3758]
Was pointed to a useful local application that provided a number of frequently used developer tools that engineers may not feel comfortable using a third party site for, so a local version was made.  This would actually make a great use case inside of Backstage, as it will be hosted on a know safe internal developer portal.

https://devutils.app/

**Comment by andrewthauer** [comment]
This is interesting. Before we adopted backstage, we built a developer portal that contained various tools like this (although most are org specific). We haven't gotten around to porting them to backstage yet though.

I had imagined each tool might be it's own plugin. So maybe this plugin would be a landing page that can link out to other registered tool plugins?

**Comment by freben** [comment]
This actually pretty cool. And then bind it to a hotkey so you can always get to it fast for some quick-and-dirty utilitizin', possibly as a popover even so you don't lose your context. :)

**Comment by adamdmharvey** [comment]
Really neat idea!!

Seems could use the concepts introduced here with this QuickJump prototype re: your idea there @freben?  https://github.com/backstage/backstage/pull/2916

A quick jump to a dynamic list of 20 tools - CIDR lookup, Base64 encoder, JWT encoder, blah blah.

**Comment by freben** [comment]
Yep, something like that.

Or make it its own page with routes so you can link to it? Not sure :) Could also have both (the same component, but rendered either in a popup by hotkey or as a route if you want to visit it).

**Comment by OrkoHunter** [comment]
Re-opening since plugin suggestion issues are now exempt from [stalebot](https://github.com/backstage/backstage/blob/18f7345a6c29dcfccef7df081b1708f2bf8f62ff/.github/stale.yml#L9).

**Comment by drodil** [comment]
I actually like the idea and started working with something like this. It's in the very early stages and has very basic functionalities but it might come something cool. You can find it here https://github.com/drodil/backstage-plugin-devtools .. and as always, please feel free to contribute!

**Comment by ahhhndre** [comment]
@drodil, there's actually an RFC #9737 (https://github.com/backstage/backstage/issues/9737#issuecomment-1315569839) open for a DevTools plugin with something similar and I have a PR in the works to add a DevTools plugin so maybe you could contribute the changes there once my initial PR gets merged in? Thought I would get this done over the holidays but other things took up my time

**Comment by drodil** [comment]
Nice plugin @ahhhndre but maybe this is something else completely (just named the same way 😆 ). My plugin was to bring similar tools like in https://devutils.app/ to the Backstage like originally proposed in the issue. How do you feel, should these kinds of features be inside the plugin you are developing or should there be a name change for my plugin to distinct these two? Thanks for pointing this out though!

**Comment by andrewthauer** [comment]
Not sure how feasible this is, but it would be nice if it were possible to embed [CyberChef](https://github.com/gchq/CyberChef) into Backstage somehow.

**Comment by ahhhndre** [comment]
@drodil yeah, I guess if you called it DevTools then to me I don't see why they wouldn't fit in. But I can also see where you are coming from. My plugin is focused on DevTools to help Backstage "Admins" or "Operators" support and diagnose their running Backstage instance. Your call at the end of the day how you want to approach this. If I hadn't already submitted a PR I would have been open to change the name but it's pretty set on my end, sorry.

**Comment by drodil** [comment]
@ahhhndre no worries, I can change the name 🤠 DevUtils it is then!
