### ISSUE TITLE
Settings Page: Available Providers Tab: GitHubAuth not showing Sign Out

### ISSUE THREAD

**Issue by alzafacon** [backstage/backstage#3768]
## Expected Behavior

After I log in to Backstage using GitHub Provider
I should be able to log out using Available Providers tab under Settings Page.
I should also be able to log out if I reopen the tab.

## Current Behavior

I can't sign out on Available Providers Tab.

![](https://cdn.discordapp.com/attachments/687235481154617364/789128077304922112/unknown.png)

## Steps to Reproduce

I sign in using GitHub. I go to Available Providers tab. Sometimes on the first login I get the option to `Sign Out`. But when I reload the page and go the Available Providers the button says 'sign in`

## Your Environment

@Rugvip reproduced on master branch
I have a generated app that is slightly out of date.
https://demo.roadie.so/

**Comment by Rugvip** [comment]
Fixed half of this in #3770. Sign in/out should work, but it's not initialized properly yet

**Comment by adamdmharvey** [comment]
This works for me with latest code off `master` now.  @alzafacon how's it for you now?  Thinking this can be closed.

![image](https://user-images.githubusercontent.com/33203301/112378370-391f6b00-8cbd-11eb-83bb-cac120862d6a.png)

**Comment by alzafacon** [comment]
looks good to me!
