### ISSUE TITLE
Templatize the pull request content used during catalog registration

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3769]
As a developer supporting a Backstage instance, I would like to be able to modify a template used for filling in a pull request when registering components in the catalog, so that I can customize it for my use case and potentially provide wording or links that reference my team or company's specific information.

This would be applied to the `@backstage/catalog-import` plugin.

---

Spun out of:

> I think this is quite specific for every adopter. Maybe we should make the summary and body configurable from the outside? I also think that the generated YAML file itself should be passend in as a template from the outside. We for example would like to introduce some comments that give custom instructions (like where our documentation is) and pre fill some fields. That could solve topics like #3678 too.

_Originally posted by @Fox32 in https://github.com/backstage/backstage/issues/3681#issuecomment-743058844_

**Comment by dhenneke** [comment]
This feature has been implemented: https://github.com/backstage/backstage/tree/ba479febd305768dd1a46bfc889c59c48e0cdede/plugins/catalog-import#customize-the-title-and-body-of-the-pull-request. The user can also edit the description prior to submitting the PR.
