### ISSUE TITLE
[RFC] Error messaging guidance and design language

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3781]
**Status:** Open for comments

## Need

A consistent design language for error messaging and when to use/not to use, and an ability for Backstage core or plugin developers to refer to it to better understand when and how they should alert to the end user. The goal would be to drive a more consistent error interface to the user, whether allowing graceful or more informational, etc.

What sparks the question for me, is I see a lot of mix of things like red popups that hover across the top of the interface (outputs of the AlertAPI, and it's extensions such as ErrorAPI), but also mixed with inline displaying of errors (things like the WarningPanel component, or plugins just printing out error message they trap).  But as a user, I have a specific example:

On a component page, I have a number of widgets. One of them is Lighthouse, as a component has it configured. However, my Lighthouse docker image was down. When that happens, I get a large red popup across the top of the screen. But as a user, that's likely the least of my worries. I would prefer just the widget itself, the Lighthouse widget, have a much more simple "error collecting audit" or something. But as a pattern, this applies across the board.

So for me identifying also who is the target of the error is key. So if the pattern of "the Backstage infrastructure team" maintaining the system might be say, 5 users, while the "Backstage user audience" might be say 500.  In that vein, only the 5 can fix Lighthouse (or your plugin of choice), while the other 500 only know a widget is down. But having Lighthouse be down, or any other element driving a component, shouldn't affect my user experience that floats above ALL of my widgets when my goal is to learn about my product. I might have 20 widgets on a page, and if one fails, ok that widget should gracefully display a msg but not pop above my entire experience. (And maybe behind the scenes, the ErrorApi might be able to be tied into the observability, so that the infra team could be made aware, but that's a topic for a different day!)

### Examples

Here's an example of my Lighthouse widget failing, but it's below the screen and I can't even tell the error was FOR Lighthouse, outside of any of my other enabled widgets for this component:

![image](https://user-images.githubusercontent.com/33203301/102634720-3cd0ae00-4120-11eb-8f21-f0b4b397bd7c.png)

And others just for discussion purposes:

![image](https://user-images.githubusercontent.com/33203301/102633449-70123d80-411e-11eb-8736-b3d618f7ee0d.png)
![image](https://user-images.githubusercontent.com/33203301/102633491-7ef8f000-411e-11eb-827e-fec842cd5085.png)
![image](https://user-images.githubusercontent.com/33203301/102633531-8fa96600-411e-11eb-8985-5ee0ede17ad4.png)
![image](https://user-images.githubusercontent.com/33203301/102633579-9d5eeb80-411e-11eb-8ef9-f48d4fa4aec2.png)
![image](https://user-images.githubusercontent.com/33203301/102633614-a8198080-411e-11eb-9d8d-3380b53187f9.png)
![image](https://user-images.githubusercontent.com/33203301/102633656-b798c980-411e-11eb-92cf-a62655a3e5b4.png)
![image](https://user-images.githubusercontent.com/33203301/102634612-0dba3c80-4120-11eb-9f2a-56527686e7bd.png)

## Proposal

1. Might we lack a design methodology to describe how and when to error, which can be used both for core contributions as well as plugins? Just to drive consistency across the product, plugins, and experience?
2. Perhaps we could use an example in storybook? (examples header, maybe a page of infocard widgets, some working some erroring?)  Something like, graceful error messaging or something.
2. Within an individual widget, the WarningPanel in my mind is too obtrusive. It works well say on an entire page, where an entire page may be broken, but I would suggest we're missing a reusable component that would drive a consistent error msg that is more easily digestible for use in a widget (InfoCard)?  (e.g., WidgetWarning?) Or do we just refer say to a material-ui/labs component, or another one,e tc.

## Risks

Standardizing error messaging too much, to the point where plugins can lose their own distinct look and feel. (re: the iOS vs. Android design control argument 😁  )

**Comment by adamdmharvey** [comment]
Related https://github.com/backstage/backstage/issues/2865

**Comment by adamdmharvey** [comment]
In support of my #4151, got good feedback from @katz95 about the design of an accordion WarningPanel.

Here's her screen cap:
![image](https://user-images.githubusercontent.com/33203301/106050909-bd86b080-60b5-11eb-9c42-907b788473ca.png)

In tweaking a possible PR, I noticed the current `<WarningPanel>` element says this,

>  Show a user friendly error message to a user similar to **ErrorPanel** except that the warning panel only shows the warning message to the user

However, in Backstage open source there is no such thing as an `<ErrorPanel>`.  Most packages and plugins are using Material-UI's `<Alert>`.  Is this perhaps that your internal Spotify instance has both a `<WarningPanel>` and an `<ErrorPanel>`?

I wonder if in support of standardizing the error UI (point of this RFC), I would propose:

* Make the `<WarningPanel>` more generic and rename it to `<AlertPanel>`
* Give it a parameter, similar to the Material-UI `<Alert severity="error">`, so we could have `<AlertPanel severity="warning">` and `<AlertPanel severity="error">`.
* The color would be driven off the severity.
* But it would retain the accordion fold out allowing either warnings or errors details via children elements to provide additional unfoldable context (stack traces).

What do you think?

**Comment by freben** [comment]
That makes sense to me. And then we try to replace all of the usages of `Alert` all over the place, I guess.

Still looking to do the accordion right? I could have also imagined having details like that in a drawer.

About the `ErrorPanel`: It was just never lifted over. It was more complex, and had an interaction with a core API that does not exist yet in the open source version of Backstage - a thing to which you could post errors along with long messages etc, which could be shown "out of band" in a drawer for those that wanted to see the full details on the error.

**Comment by freben** [comment]
What steps might remain to implement here, now that the WarningPanel is in place?

**Comment by adamdmharvey** [comment]
@freben While WarningPanel was a start, I actually didn't manage to drive any discussion on the topic here hence this was a request for Comments that has none. 😁  There are other tickets, such as mine here https://github.com/backstage/backstage/issues/4292, which I think still hits a key issue for me: when should the errorApi / AlertApi be triggered?

With my Lighthouse Docker image down, for example, I get this hitting an entity:

![image](https://user-images.githubusercontent.com/33203301/108020836-390bbb80-6feb-11eb-8486-898fb1d272e9.png)

Should the user's UI be blocked with a modal popup, that will follow them page to page to page, because one small card on an entity that contains a dozen cards is down?  I think no. So it harks back to the three bullets in the original RFC below, in particular outlining an error page on the story book to show examples of when best to error and pointing the user to which design solution - a warning panel, a more simple widget error, or the full blown errorApi/AlertApi, should be used and when?

thoughts/opines from the group?

**Comment by freben** [comment]
Well we could make transient popups that disappear on route changes. But yeah, point taken.

**Comment by freben** [comment]
We talked a bit about this today.

The tsdoc for this one mentions that it is mainly to be used when inline signalling is not possible or does not make sense. So, mostly for async things and similar - which should be rare.

Does that help?

https://github.com/backstage/backstage/blob/a4dbd8353cfa4d4d4334473e2c33afcda64e130d/packages/core-api/src/apis/definitions/ErrorApi.ts#L44
