### ISSUE TITLE
Lighthouse plugin treats URLs with or without a trailing slash as different

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3783]
## Expected Behavior

When running a Lighthouse audit against a URL that contains a trailing slash, I would expect that would be identified as the same web site as one that does not contain the trailing slash. At least when that trailing slash is off the root FQDN. (see Context below for more)

## Current Behavior

If you register two identical URLs, one with and one without a trailing slash, you end up with two different list of audit reports.

![image](https://user-images.githubusercontent.com/33203301/102660157-93ea7900-4148-11eb-91a3-a696bb7e2670.png)

![image](https://user-images.githubusercontent.com/33203301/102660493-1e32dd00-4149-11eb-8f16-ccf4835a3ee3.png)

![image](https://user-images.githubusercontent.com/33203301/102660529-2ab73580-4149-11eb-8096-911153da3a7c.png)

## Possible Solution

At submission of an audit, strip any trailing slashes identified.

## Steps to Reproduce

1. Go to the Lighthouse plugin
2. Audit a public web site that just is a pure domain name
3. Run that same audit, providing the same domain name, but add a trailing slash.
4. See that you've created two different audit records, rather than now having a history of running two audits against the same site.

## Context

I can appreciate on the web, the presence or lack of a slash could mean a different site. So potentially this would only be done if the URL ended in just `.something/`. I wonder if there's a library or at least a precedent to review on the web.

## Your Environment

Used the Roadie Backstage demo URL: https://demo.roadie.so/lighthouse

**Comment by adamdmharvey** [comment]
And open to other opinions on it, it just seems a bit weird.

Google will treat them as different, so presumably Lighthouse (from Google) would :)
https://developers.google.com/search/blog/2010/04/to-slash-or-not-to-slash

Would we lookup the value first, see if it's bit audited before with or without a slash, and offer a "do you mean https://foo.bar ?"

**Comment by Rugvip** [comment]
Could imagine stripping trailing `/`'s from FQDNs as suggested is pretty safe an simple fix :grin:

**Comment by mick-feller** [comment]
The code that got merged for this strips any trailing slash of not just the FQDN.

Our infrastructure relies on trailing slash in some cases. for example:
https://my-awesome-domain.com/service/some-service-url/

gets turned into:
https://my-awesome-domain.com/service/some-service-url

which in our case this throws a 404 because we rely on that trailing slash.
