### ISSUE TITLE
lighthouse: Add breadcrumbs to navigate back to the main audit table

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3784]
## Feature Suggestion

The Lighthouse plugin lacks breadcrumbs. When you view the homepage of the plugin, you get a list of audits. Then if you click one audit, you get the audit page. But there's no way to navigate back to the list of audits, without clicking back in your browser.

![image](https://user-images.githubusercontent.com/33203301/102663168-45d87400-414e-11eb-815a-7cd0fcb2c799.png)

## Possible Implementation

https://material-ui.com/components/breadcrumbs/ maybe?

**Comment by tudi2d** [comment]
I would like to work on this :)

**Comment by adamdmharvey** [comment]
@tudi2d fantastic, thanks for chipping in!  Assigned you.

**Comment by tudi2d** [comment]
@adamdmharvey I have question concerning proxy/CORS of plugins. I tried serving the Lighthouse Plugin, but the request gave back a CORS error (because it is served over Port 3003 & the FE runs on 3000). Do I have to do some other configurations? :/
![image](https://user-images.githubusercontent.com/8904624/103370599-7f559b80-4acd-11eb-9c9e-22c98aeeecf0.png)

**Comment by adamdmharvey** [comment]
@tudi2d I don't have it fully working myself, but in the plugin README, it notes you do need to define CORS config but in the `lighthouse-audit-service`, not in Backstage.  Not sure if you had done that?  Note I also tried to improve some of that doco with #3895 .

**Comment by tudi2d** [comment]
Thanks for the quick response & the improvements of the docs! I did not read it carefully enough & will give it another try :)

**Comment by tudi2d** [comment]
I tried setting up `lighthouse-audit-service` a few times now, and I'm unfortunately not able to get it working. It’s my fault, as I’m not proficient enough using WSL 2, Docker & Postgres. I'm a bit annoyed of myself that I failed here, but think some one else with a working setup should be able to implement this enhancement quickly & painless. Thanks for your help @adamdmharvey, you can assign someone else.

**Comment by adamdmharvey** [comment]
Directly relates to #3965 . If that evolves globally, this one may not even be necessary anymore!
