### ISSUE TITLE
GitHub Auth Login Popup Race Condition

### ISSUE THREAD

**Issue by fidelcoria-aa** [backstage/backstage#3785]
## Expected Behavior
Log into Backstage using GitHub auth provider.

## Current Behavior

Sometimes when logging in with GitHub auth provider I get a toast that says `Incorrect app origin, expected`.
But only sometimes.

## Possible Solution

I found the race. it's in packages/core-api/src/lib/loginPopup.ts messageListener and intervalId are racing. basically. when the window closes message listener "un-registers' the interval (but only at the very end of the fn) while messageListener is running the intervalId fn sometimes triggers and causes the error to show up

The easiest fix is to delete the  intervalId. otherwise not using useInterval for the error checking or just setting up a semaphore of some kind (not sure a semaphore would work in this case).

## Steps to Reproduce

1. Setup GitHub Auth provider
2. Login
3. logout
4. try again

Discussion on this started on discord with user bubo and @freben

**Comment by fidelcoria-aa** [comment]
Root cause seems to be combining polling and messaging. How about deleting intervalId, and instead have the OAuthAdapter sends an error message only when the popup unloads but has not yet sent and authorization_response?

**Comment by freben** [comment]
Trying to reproduce this, on latest master (b2195fc06c68cc0e6aa84fae00ae5e5e31045ef4).

- macOS Firefox 84.0.1 (64-bit)
- macOS Chrome 87.0.4280.88 (Official Build) (x86_64)
- macOS Safari 14.0 (15610.1.28.1.9, 15610)

Unable to make this happen. I've logged out and back in repeatedly many times on each browser and still haven't seen the issue. Odd.
