### ISSUE TITLE
tutorials/quickstart-app-auth is out of date

### ISSUE THREAD

**Issue by n2ygk** [backstage/backstage#3788]
The [Monorepo App Setup With Authentication](https://backstage.io/docs/tutorials/quickstart-app-auth) tutorial is out of date. See detailed bug report at https://github.com/johnson-jesse/simple-backstage-app/issues/1

## Expected Behavior

I should be able to use the demo repo to build a new app.

## Current Behavior

A number of compilation errors due to changes in the code base since the tutorial [repo](https://github.com/johnson-jesse/simple-backstage-app) was created.

## Possible Solution

Upgrade the tutorial docs/repo and keep current, or perhaps just remove this tutorial.

## Steps to Reproduce

Detailed at https://github.com/johnson-jesse/simple-backstage-app/issues/1

## Context

Trying to build my first backstage app starting with `create-app` which I noticed was missing frontend apis. Saw
a lot of documentation for plugins saying to use `builder.add` but couldn't find any examples in the current backstage repo but did find in the demo repo. This looks like I went down a long twisty path of historical code that isn't used that way anymore.

And, no, I am not an experienced typescript developer by any means. I copy/paste/modify until stuff works;-)

## Your Environment

- NodeJS Version (v12): 12 or 14
- Operating System and Version (e.g. Ubuntu 14.04): MacOS Catalina
- Browser Information: N/A

**Comment by Xantier** [comment]
I think I could take a stab at this to revamp the documentation and create an example repository for this.

**Comment by freben** [comment]
Ok, assigned!

**Comment by adamdmharvey** [comment]
@Xantier I believe this one can be closed - would you agree? cc @n2ygk

**Comment by Xantier** [comment]
Yeah, I believe so. We could extend the tutorial a little bit by adding more information about the usage of `app-config.local.yaml` but the documentation of using that is already in here: https://backstage.io/docs/conf/writing so it's not necessarily needed. Unrelated to this issue though.

**Comment by adamdmharvey** [comment]
Taking the liberty to close this then.  The app config is in there as you note, so if any further clarity can be needed, PRs can be opened to further address. Thanks for all the support and @n2ygk if you need any further clarification, don't hesitate to open an issue or post on Discord! 

https://backstage.io/docs/support/support

**Comment by n2ygk** [comment]
> Taking the liberty to close this then. The app config is in there as you note, so if any further clarity can be needed, PRs can be opened to further address. Thanks for all the support and @n2ygk if you need any further clarification, don't hesitate to open an issue or post on Discord!
> 
> https://backstage.io/docs/support/support

@adamdmharvey Honestly I've stopped doing it this way and am just maintaining a branch off of master with my local config.
