### ISSUE TITLE
[Plugin] Kafka

### ISSUE THREAD

**Issue by nirga** [backstage/backstage#3791]
## Summary

Provide visibility into a Kafka cluster. Connect to it, sample messages from all topics and expose them in relation to entities in Backstage.

The plugin should support new metadata properties for components, that specify consumed and produced topics. The plugin can then expose a list of sampled messages from produced and consumed topics in an entity page.

We began working on a UI (unrelated to Backstage) that allows you to view sampled messages as well as the topics that exist in a Kafka cluster, something similar to https://github.com/obsidiandynamics/kafdrop using [KafkaJS](https://github.com/tulios/kafkajs).

I wonder if it might be useful to port and continue this development based on Backstage. Assuming that each service can report (in its configs) the topics that it produces to (or consumes from) kafka, it can allow you to view information about consumed and produced messages for each service. 

## Project website (if applicable)

Kafka - https://kafka.apache.org/
KafakaJS - https://github.com/tulios/kafkajs

## Context

Our internal architecture is mainly event-based, and so we use Kafka extensively throughout our microservices. We began working on a UI (unrelated to Backstage) that allows you to view sampled messages as well as the topics that exist in a Kafka cluster, and wonder if it might be useful to port it to Backstage and continue working on it here.

**Comment by freben** [comment]
Oh yes, this is an excellent use case! It would be great if you wanted to contribute a plugin for that.

This can be useful in two distinct ways. For one, as part of an entity view, to be able to see what topics it relates to and to be able to inspect those topics (metrics, data, permissions...). And for the second, to be able to (not from an entity POV) to discover and learn about and inspect topics overall.

I feel that a kafca topic can probably be modeled as an API entity, so we could actually index them that way I the catalog. An ingesting processor could be pointed at the master, and read information out of it.

One thing to consider here is security. The contents of topics may well fall under legal regulation in some instances, or be highly sensitive for other reasons. So the inspection part may need some careful consideration.

**Comment by nirga** [comment]
Yes, I want to start working on it.

You're definitely right about the security issues around inspection. Since people are serializing data in Kafka differently (for example we use Protobuf but many use Avro), it might make more sense to leave the actual serialization to the app that's using the plugin and then it can also decide if it needs to sanitize the data / hide it altogether.

**Comment by freben** [comment]
Nice - assigned you.

You are very welcome on Discord or in issues if you hit any blockers or have questions.

**Comment by andrewthauer** [comment]
I agree this would be very useful 🎉.

I'm not necessarily sure that trying to model a single topic to an API Entity makes sense though. It is very common to have to use multiple topics for related things cantering around a bounded context. The API docs plugin already supports AsyncAPI so I'd like to see how that could tie into this. I've thought about this a little bit already and it seems to me like a service should be able to provide many channels/topics which could be modelled as a single AsyncAPI.

Another thing that comes to mind is handling of different environment. You may have a staging and production environment that have different topic names, etc. Perhaps AsynAPI can help in this regard as it's a spec instead of an environment.

Completely agree about the security aspects of introspection. I think it would be best to make this optional and also support things like avro.

**Comment by freben** [comment]
Hm! So, would it make more sense for an API entity to be able to reference (by annotation or otherwise) the topic(s) that it represents? Could that even be extracted from the asyncapi spec? Sorry I haven't personally worked much with this.

**Comment by freben** [comment]
This strikes me as overlapping with the concept of regular API endpoints and the webpage link concept. They boil down to "where can I consume this thing"

**Comment by andrewthauer** [comment]
AsyncAPI has core concepts such as channels and messages which map to topics and schemas in Kafka respectively. It also has the concept of servers which could map to environments or clusters.

Knowing which topics are produced and consumed by an entity would be very useful. However, there is an opportunity here to describe the relationships of the underlying message schemas and how they are produced and consumed.

I'm not exactly sure on what the best way to model this in the backstage would be yet. AsyncAPI can likely model most setups, but I'm not sure it makes sense to leverage it, or remodel something similar in the catalog itself. The API spec should probably be the source of truth. However, does that mean catalog uses the spec directly or tries to remodel it into constituent entities and their attributes?

**Comment by nirga** [comment]
I wasn't familiar with AsyncAPI and I actually think it might be a great model to use. Now thinking about it a bit more I actually see 2 different components here:

1. A `KafkaCatalogProcessor` that can connect to a Kafka cluster and generate AsyncAPI specification by observing the different topics (possibly allowing further customization using a callback to the app).
2. A `KafkaPlugin` that can present these AsyncAPis, enriching them with more data from the cluster (message throughput, number and details on consumers, etc.)

**Comment by andrewthauer** [comment]
@nirga - I think there could be 2 different approaches for the first point. A `KafkaCatalogProcessor` could be used for a code first approach where things are discovered after the fact. Another might be `schema first` which may involve creating an `AsyncAPI` spec as being the source of truth. Each approach would be more specific to how the org operates.

There are probably 2 core categories to model. One would be core `kafka` related concepts, their metadata and relationships. The other might be more operational information that could be queried at runtime vs stored in the catalog directly. Here's a list of things that might be candidates for the catalog, although I'm not sure if all make sense or not:

- Clusters & brokers
- Topics + partition information, etc.
- Consumers & consumer groups
- Schema registry subjects
- Kafka connectors

**Comment by nirga** [comment]
Yeah, definitely it make sense! I guess I'll support first reading an AsyncAPI from a component and then querying the Kafka cluster to show relevant information (topics, consumer, volume, etc).

**Comment by andrewthauer** [comment]
Technically AsyncAPI would be attached to an `API` entity which in turn could be associated with a `Component` which has support in the [API Doc Plugin](https://github.com/backstage/backstage/tree/master/plugins/api-docs).

I personally haven't spent a huge amount of time looking into this, but AsyncAPI is poised to be the canonical way to model these scenarios. From a practical standpoint, I'm wondering how closely AsyncAPI docs (as is) can model these concepts in a meaningful `kafka` way?

This also touches on the overall usage of the `spec` field of an `API`. I can't recall an existing precedent where plugins will make detailed use of `entity.spec` in a very dynamic way that this might on the `api.spec.definition`. However, to me it seems perfectly reasonable for plugins to expand and augment the API definition spec of an entity with operational data, etc. @freben - Maybe you can articulate the thinking here a little better than I 😄 .

**Comment by adamdmharvey** [comment]
@nirga I'm thinking this one can be closed, what do you think?  Based on all of your hard work, Kafta plugin now exists and can continue to be iterated.  Thoughts?

https://backstage.io/plugins

**Comment by nirga** [comment]
Yep, make sense.
