### ISSUE TITLE
Route order in App.tsx may cause catalog-import to fail

### ISSUE THREAD

**Issue by erikxiv** [backstage/backstage#3793]
In `App.tsx`, if you put the `/catalog/*` route before the `/catalog-import/*` route, attempting to visit `/catalog-import` will yield a blank page.

## Expected Behavior

The page should show the catalog-import page.

## Current Behavior

A blank page is displayed. Seems the `/catalog/*` route is matched, but that component does not show anything since the URL is not as expected.

## Possible Solution

Is this a bug in React Router? Or how backstage uses it? If not easily fixable, maybe a warning somewhere to avoid adopters accidentally arranging Routes in an order that causes this behaviour.

## Steps to Reproduce

1. `git clone git@github.com:backstage/backstage.git`
2. In App.tsx, move the `/catalog-import/*` route below the `/catalog/*` route.
3. `yarn dev`
4. Visit http://localhost:3000/catalog-import

## Context

Stumbled on this while bumping versions to use the new catalog-import. Cost me a few hours of troubleshooting. Might give others the same.

## Your Environment

- NodeJS Version (v12): v12.19.0
- Operating System and Version (e.g. Ubuntu 14.04): OSX 10.15.7 (same issue when running Docker, node:12-buster image)
- Browser Information: Chrome latest

**Comment by Rugvip** [comment]
Thanks for reporting! Took care of this as part of #3826 which will be rolling out soon
