### ISSUE TITLE
Lighthouse audit frame blocked by Content Security Policy

### ISSUE THREAD

**Issue by erikxiv** [backstage/backstage#3796]
The lighthouse plugin displays details for a specific audit in a frame. This frame is blocked by the default Content Security Policy.

## Expected Behavior

A fresh installation of Backstage should display the Lighthouse audit view without errors.

## Current Behavior

The lighthouse audit view displays a sad/blocked rectangle (in Chrome).

The Javascript console diplays `Refused to frame 'http://localhost:7000/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".`

If `frame-ancestors` is modified as below, the Javascript console instead displays `Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.`

## Possible Solution

Adding the following configuration to `app-config.local.yml` fixes the problem:
```
backend:
  csp:
    frame-ancestors: ["'self'", 'localhost:3000']
    script-src: ["'self'", "'unsafe-inline'"]    
```

`frame-ancestors` above would only apply to the local env where app and backend is separated, so adding this as a default value might be an easy fix. `script-src` is a different, and more dangerous, animal where it might be suitable to refactor the lighthouse audit service to avoid the need.

## Steps to Reproduce

1. git clone git@github.com:backstage/backstage.git
1. Setup lighthouse as per https://github.com/backstage/backstage/blob/master/plugins/lighthouse/README.md
    1. Start an instance of https://github.com/spotify/lighthouse-audit-service
    1. Configure the lighthouse service url in your app-config.yaml
1. `yarn dev`
1. Browse to the lighthouse page (`/lighthouse`) and submit an audit for a website
1. When the audit has finished, click it to go the audit detail page (`/lighthouse/audit/xxx`)
1. Where the audit details should be seen, a grey/sad rectangle is shown instead and an error is written to the Javascript console

## Context

This has cost me a few hours of debugging, and might do others. The `unsafe-inline` configuration might be a blocker for security conscientious adopters.

## Your Environment

- NodeJS Version (v12): v12.19.0
- Operating System and Version (e.g. Ubuntu 14.04): OSX 10.15.7 (same issue when running Docker, node:12-buster image)
- Browser Information: Chrome latest

**Comment by bgfernandes** [comment]
I came here because I was having a similar problem when trying to serve Lighthouse Audit Service from Backstage's backend proxy, in order to simplify our infra.

For anyone having this problem, the "Possible solution" mentioned worked for me:
```
backend:
  csp:
    frame-ancestors: ["'self'", 'localhost:3000']
    script-src: ["'self'", "'unsafe-inline'"]    
```
