### ISSUE TITLE
Bootstrap locations by adding an option for a "scraper-like" job that finds backstage yamls

### ISSUE THREAD

**Issue by nirga** [backstage/backstage#3802]
## Feature Suggestion

This is somewhat related to #2001 but I didn't want to overwhelm the discussion there so creating a new one here.
My suggestion is to add a new layer on top of the current location mechanism that allows to generate a set of locations. This can be done using a background "scraper-like" job (that for example scans every day the org's repos, finding the Backstage yamls URLs). Then, it outputs this set of yamls to the next level that parses them and add those entities to Backstage.

You might ask at this point (assuming you agreed with me it's a viable feature) - if #2001 is implemented, is there any reason you'll need to scrape all locations from github more than once? And I think the answer is yes because of monorepos. Sometimes teams add multiple services to the same repo. Even if we had some API into Backstage that allows us to "push" new components there still wouldn't be anything that does that automatically for teams that just add a new folder in an existing repo for a new service they're creating. So there still be a need for re-scanning all the repos every now and then and see if anything changed. 

## Possible Implementation

This might not require any architecture change at all - we can just use the current logic in `HigherOrderOperations.refreshAllLocations`. Scraping github can just be another "location" that we process. Since this scraping may take a while, we might need to improve the parallelism there so that it won't hold back the entire initialization as happens today. I imagine also it might be useful to provide some bootstrapped scraper like this out of the box (where the code to scan an org's repos is already there, you just need to add some functional-like logic specifying how to reach the yaml in each repo).  

## Context

Our org already contains a significant amount of repos and services, and to allow for an easier migration into Backstage, we did the following:

1. Used an existing yaml we were using internally, and wrote a new processor that knows how to translate it to Backstage components.
2. Created an offline job that scans our org's github repos every now and done, produces a set of locations where those yamls exist.

I currently don't see any other clean solution for doing this in Backstage and I think this might be something many orgs will encounter when wanting to migrate.

**Comment by andrewthauer** [comment]
Related to #3941 ?
