### ISSUE TITLE
[Kubernetes plugin] - Include listing CronJobs & Jobs in default objects

### ISSUE THREAD

**Issue by makkeess** [backstage/backstage#3804]
## Feature Suggestion
As a developer I'm interested in seeing CronJobs and Jobs in the Kubernetes plugin page.

## Possible Implementation
---

## Context
Services, deployments, ingresses and more k8s objects are automatically picked up by the kubernetes plugin if they have the `backstage.io/kubernetes-id` label set on them. However CronJobs and Jobs is not part of the default objects that get picked up by the plugin, could they be added?

**Comment by Rugvip** [comment]
@makkeess Agreed! Would you like to work on this or is it up for grabs? :grin:

**Comment by makkeess** [comment]
Anyone willing can feel free to grab it! :)

**Comment by O5ten** [comment]
@makkeess & @Rugvip i think we should be able to squeeze in StatefulSet and DaemonSet as controllers aswell with this issue seeing as they are closely related to Deployments. :)

**Comment by jessesanford** [comment]
I am very interested in this. Anyone have any information on how to get started?
