### ISSUE TITLE
[Composability] Document new composability system and APIs

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#3809]
## Feature Suggestion

Document all new building blocks that have been added and what it means for plugins, apps, and how to migrate.

- [ ] Extensions and Component Data
- [ ] Extensions from a plugin developer's point of view
- [ ] Using Extensions in an app
- [ ] `RouteRef`s, `useRouteRef`, and plugin `routes` and `externalRoutes`
- [ ] Binding external routes in the app
- [ ] New catalog components, `EntitySwitch` & `EntityLayout`, and how to use those in the app

We probably want this documentation to cover all aspects and not build on existing documentation. As we migrate away from the 3 different older API versions we can start cleaning up and removing existing documentation.

## Context

#3414

**Comment by andrewthauer** [comment]
Does this mean I could potentially revisit  #2791 soon'ish? 😄

**Comment by Rugvip** [comment]
@andrewthauer yes :grin:
