### ISSUE TITLE
Bug: Register an existing component using analyze-location fails if a catalog-info.yaml exists

### ISSUE THREAD

**Issue by erikxiv** [backstage/backstage#3811]
If one registers an existing component and points to a github repository with an existing `catalog-info.yaml` file, the wizard fails as it tries to add a new file on top of the old one.

## Expected Behavior

If one is lazy, forgetful or doesn't know better and input a repo location with an existing `catalog-info.yaml`, the analyze-location feature detects the file and registers that one as-is to the backstage catalog.

## Current Behavior

Backstage alerts with a `Failed to submit PR to repo: Couldn't create a commit with catalog-info.yaml file added, received http response status code 422: Invalid request. "sha" wasn't supplied.` message. Checking the network log, github responds with `{  "message": "Invalid request.\n\n\"sha\" wasn't supplied.",  "documentation_url": "https://docs.github.com/enterprise/2.22/rest/reference/repos#create-or-update-file-contents" }`

## Possible Solution

Modify the reigster/analyze feature to allow for responding with an existing `catalog-info.yaml` instead of trying to add a new one.

## Steps to Reproduce

1. `git clone git@github.com:backstage/backstage.git`
2. `yarn dev`
3. Go to Create... > Register existing component
4. Point to a repo that has an existing `catalog-info.yaml`, e.g. `https://github.example.com/user/repo/`
5. Click Next
6. Review and click next
7. View the error message

## Context

This is a nice-to-have, making the backstage experience smooth for everyone.

## Your Environment

- NodeJS Version (v12): v12
- Operating System and Version (e.g. Ubuntu 14.04): OSX Catalina
- Browser Information: Chrome latest
- Github Enterprise 2.22

**Comment by Rugvip** [comment]
Assuming best solution here is to simply treat an existing `https://github.example.com/user/repo/catalog-info.yaml` as a registration instead of an import?

**Comment by freben** [comment]
Yep but this should be detected I think. @mcalus3 ping

**Comment by Xantier** [comment]
I could take a look at this and modify it to treat those as a reg of existing instead of trying to add a new file.

**Comment by freben** [comment]
assigned!

**Comment by adamdmharvey** [comment]
Off `master`, this is no longer a bug. When pointing to an existing repo which already has a `catalog-info.yaml`, the wizard now loads the YAML and suggests you can import.

![image](https://user-images.githubusercontent.com/33203301/112377856-99fa7380-8cbc-11eb-839c-63af1a957fc8.png)

If anyone has any counter opinions, feel free to re-open or comment?  Thanks!

**Comment by mazimcoder** [comment]
# solution: just do the following to resolve this issie: 
- delete the existing `catalog-info.yaml` in the repo
- delete `backstage-integration` branch in the repo
- change the the new PR title from `add catalog-info.yaml config file` to something else like `new catalog-info.yaml config file`
