### ISSUE TITLE
Bug: Register an existing component using analyze-location on GHE does not provide required spec.owner property

### ISSUE THREAD

**Issue by erikxiv** [backstage/backstage#3812]
If one registers an existing component and points to a github enterprise repository, the added `catalog-info.yaml` file does not contain the `spec.owner` property, which in turn will cause the location refresh cycle to throw an error instead of inserting the repo into the catalog.

## Expected Behavior

When using the wizard and merging the pull request, the new entity should show up in the catalog.

## Current Behavior

The wizard creates the PR OK (without the required field). The location refresh cycle throws the following errors:

```
Failed to read codeowners for location github:https://github.example.com/user/repo/blob/master/catalog-info.yaml, Error: Unable to read https://example.com/user/repo/blob/master/CODEOWNERS, FetchError: request to https://example.com/user/repo/blob/master/CODEOWNERS failed, reason: getaddrinfo ENOTFOUND example.com
catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity Component:default/repo at github https://github.example.com/user/repo/blob/master/catalog-info.yaml, ValidationError: spec.owner is a required field
```

## Possible Solutions

* Add an unknown owner if that is allowed?
* The CODEOWNERS error above indicates a feature to list the repo CODEOWNERS as owners of the entity, which sounds like a nice default. The error above seems to be that the GHE host has been mangled (example.com instead of github.example.com) somewhere in the process.

## Steps to Reproduce

1. `git clone git@github.com:backstage/backstage.git`
2. `yarn dev`
3. Go to Create... > Register existing component
4. Point to a repo that has no existing `catalog-info.yaml`, e.g. `https://github.example.com/user/repo/`
5. Click Next
6. Review and click next
7. Merge the pull request as suggested
8. Wait for the location refresh loop and check the error logs

## Context

Sounds like a blocker for GHE + the nice new analyze-location feature.

## Your Environment

- NodeJS Version (v12): v12
- Operating System and Version (e.g. Ubuntu 14.04): OSX Catalina
- Browser Information: Chrome latest
- Github Enterprise 2.22

**Comment by adamdmharvey** [comment]
This may be a duplicate of https://github.com/backstage/backstage/issues/3678, introduced after `spec.owner` was marked required.

**Comment by erikxiv** [comment]
Agreed, closing as duplicate.
