### ISSUE TITLE
Deploy on server with docker error

### ISSUE THREAD

**Issue by gharsallahmoez** [backstage/backstage#3817]
I'm trying to eploy backstage on my server using docker (i'm following this https://backstage.io/docs/getting-started/deployment-other) . it works in my local machine but not in my server. any help?

**Comment by OrkoHunter** [comment]
@gharsallahmoez Could you share some logs of the error from server?

**Comment by gharsallahmoez** [comment]
@OrkoHunter I tried to installed locally on my ubuntu server using following this https://backstage.io/docs/getting-started/running-backstage-locally
I  get `404s will fallback to /index.html` in the frontend part (running on port 3000)
and `net::ERR_SSL_PROTOCOL_ERROR` in the console log for the backend (running on port 7000)
I installed an ssl certificate for the server, not I didn't get any console output for the backend and I get a white screen

**Comment by gharsallahmoez** [comment]
@OrkoHunter  any update ?

**Comment by OrkoHunter** [comment]
@gharsallahmoez Were you able to run Backstage locally after doing a git clone? Try without SSL, just on http (which should be the default).

The `404s will fallback to /index.html` is not an error. After doing `yarn start` for frontend, webpack takes time to create the frontend bundle (takes few seconds while there is a white screen in browser). The `net::ERR_SSL_PROTOCOL_ERROR` should not be there when you are running locally without SSL.

**Comment by samwiskow** [comment]
As mentioned by @freben in #3279 

> Does the following in the app-config.yaml fix things?
>``` yaml
>backend:
>  csp:
>    upgrade-insecure-requests: false
>```
>You may want to place this in an app-config.local.yaml that gets picked up automatically during local dev.

This should help you solve the automatic HTTP -> HTTPS overwrite.
