### ISSUE TITLE
feat: Notify on new releases to Discord #announcements channel

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3833]
## Feature Suggestion

It would be nice when a release is made, that an announcement is posted to the Discord `#announcements` channel. This might be useful for users who don't want to subscribe to releases through GitHub itself, and for new users to Discord to sort of see the frequency with which it happens (potentially driving valuable discourse on the topic).

![image](https://user-images.githubusercontent.com/33203301/102934093-7f242300-4471-11eb-8aa0-4f74b5853ac0.png)

## Possible Implementation

* Grab a Discord web hook for the `#announcements` channel
* Add the new webhook on this repo: https://github.com/backstage/backstage/settings/hooks/new
* Paste the webhook, ending with `/github`
* For which events, select only the "Releases" event

In this way, if either automation (i.e., GitHub Actions :octocat: ) or manual (human 👩 / rodent 🐭 / other 🐊 ) creates and publishes a release, the web hook fires, and Discord gets the update.

## Context

Not required by any stretch, but a potentially on the side as a "nice to have".

**Comment by Rugvip** [comment]
Good idea!

Gonna grab this as I'm working on some overall improvements to the release process :>
