### ISSUE TITLE
Catalog-import should be more generic to support multiple Git providers

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3858]
Regarding `@backstage/catalog-import`:

> i confirmed the same basic import functionality is working with Bitbucket Server. I do think we need to make the verbiage of the plugin a bit more generic and ideally specific to the integration in use given in the app-config, given someone using Bitbucket wouldn't benefit from all the GitHub verbiage 😀 

> Anything that makes reference to GitHub maybe keep it generic for now and update to something like from "your repository" until we can have it changed to integration.bitbucket = Bitbucket or integration.gitlab = GitLab etc... The Start tracking your component in "Backstage" verbiage should also be updated to "my app" in the app-config, believe that's in the register-component... thoughts? 

![2020-12-28_9-50-12](https://user-images.githubusercontent.com/6157895/103223348-06e7b280-48f4-11eb-9cc3-ee45c58f8895.png)

_Originally posted by @regicsolutions in https://github.com/backstage/backstage/pull/3782#issuecomment-751716202_

**Comment by goober** [comment]
I am taking a look at this. However, my react skills are limited to bear with me. So it can be assigned to me for the time being.
