### ISSUE TITLE
lighthouse: Suggest rename annotation due to use of inaccurate domain name

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3879]
## Feature Suggestion

The current annotation for the Lighthouse plugin is `lighthouse.com/website-url`.  In fact, that domain name is a parked one owned by a hosting provider and has no relationship at all with Google or Chrome Dev Tools.   I suggest using it infers inaccurate accountability, and down the line could be used maliciously by whomever is the owner is to confuse the industry or any users who might infer it's owned by Alphabet in some way.

https://github.com/backstage/backstage/blob/0acf4c92992c7a243d6b9a44d328f4c91ad4b8c7/plugins/lighthouse/constants.ts#L16

I propose it be changed to `google-lighthouse/website-url`, and looking for feedback on a few elements.

## Possible Implementation

This plugin does not exist in the Stability index, and thus infers no stability.

I don't know if there is any precedent for changing annotations, but two approaches:

* **Support Double Annotations**
    * Define a second annotation, and update plugin to use either one
    * If the old one is used, optionally note this in the widget (though I believe this might confuse users, rather than say a Backstage support team, so I'd potentially not suggest this)
    * Release the new code with info in the CHANGELOG regarding the deprecation of the old annotation, but stating both are viable
    * After two weeks, in another minor bump, remove the legacy annotation returning the code to just a single annotation
* **Info Only Before Removal**
    * Issue a PR indicating the annotation is being deprecated, with a patch bump
    * Wait two weeks
    * Issue a new PR to change the annotation, issuing a minor bump

Since it is a frontend plugin, logging a warning to the backend is of no value (I believe?).

## Context

The goal would be to move to the new annotation in the least impacting way.

Usage?  https://www.npmtrends.com/@backstage/plugin-lighthouse-vs-@backstage/core

**Comment by benjdlambert** [comment]
@adamdmharvey maybe `lighthouse.google.com`? They don't have to be proper domains as such and valid, but maybe `lighthouse.com` isn't the greatest.
