### ISSUE TITLE
Bug: Backend fails to start due to db migration failure

### ISSUE THREAD

**Issue by lucasmelin** [backstage/backstage#3888]
After creating a new backstage application with `npx @backstage/create-app` and selecting the SQLite database option, the backend fails to start up due to a failed database migration.

## Expected Behavior

The migrations should complete successfully and the backend should startup.

## Current Behavior

The migration `20200702153613_entities.js` fails when trying to drop the index `entities_unique_name` due to a no such index error. This results in the backend failing to startup entirely.
![image](https://user-images.githubusercontent.com/205707/103358212-04679300-4a83-11eb-9841-60bc78050536.png)

## Possible Solution

If I delete lines 34-36 in `/node_modules/@backstage/plugin-catalog-backend/migrations/20200702153613_entities.js` then the migrations complete successfully and the backend starts up.

![image](https://user-images.githubusercontent.com/205707/103358419-88ba1600-4a83-11eb-8f5f-f35c8e0145c1.png)

## Steps to Reproduce

1. Run `npx @backstage/create-app` and select SQLite as a backend in the creation wizard.
2. `cd` into the new backstage directory
3. Run `yarn start-backend`

## Context

Full output:

```
mell@backstage-dev:~/temp-backstage$ yarn start-backend
yarn run v1.22.5
$ yarn workspace backend start
$ backstage-cli backend:dev
Build succeeded
2020-12-30T14:42:22.460Z backstage info Loaded config from app-config.yaml
2020-12-30T14:42:22.464Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucket{host=bitbucket.org,authed=false},github{host=github.com,authed=true},gitlab{host=gitlab.com,authed=false},fallback=fetch{}}
migration file "20200702153613_entities.js" failed
migration failed with error: drop index `entities_unique_name` - SQLITE_ERROR: no such index: entities_unique_name
Backend failed to start up, Error: drop index `entities_unique_name` - SQLITE_ERROR: no such index: entities_unique_name
```

## Your Environment

- NodeJS Version (v12): v12.19.0
- Operating System and Version (e.g. Ubuntu 14.04): 18.04-LTS
- Browser Information: N/A

**Comment by freben** [comment]
Fixed! :) https://github.com/backstage/backstage/pull/3881

**Comment by freben** [comment]
If you want to get unblocked quickly, before a new release is cut, you can actually change that file inside `node_modules/@backstage/plugin-catalog-backend/migrations`. If you change the try/catch to instead be an if statement like in that pull request (the other ones in the other files aren't strictly necessary), it'll go through.

**Comment by freben** [comment]
Put a will-fix label in the sense that we will make a release of the fixed code next week.

**Comment by lucasmelin** [comment]
Thanks, can confirm that your suggested fix works.

**Comment by benjdlambert** [comment]
@lucasmelin going to close this ticket now as the fix has been merged. Feel free to re-open if there's something that is still not right.

**Comment by regicsolutions** [comment]
@benjaminr when is the next release of the catalog-backend plugin scheduled?

**Comment by benjdlambert** [comment]
@regicsolutions @benjaminr get's a lot of tags here that aren't meant for him.. Sorry @benjaminr.  haha.

It's planned for Thursday 7th, however if you need it right now, you can use `nightly` as the version in your `package.json` for some of the packages as they are built, well, nightly. 👍

**Comment by regicsolutions** [comment]
Thanks the nightly release worked
