### ISSUE TITLE
`id_token` is not returned from the OAuth2 Strategy when the `openid` scope is used

### ISSUE THREAD

**Issue by bbourqu** [backstage/backstage#3894]
## Expected Behavior

When using the OAuth2 strategy and using the scope `openid` the provider will provide back a `id_token` that can be jwt decoded and get certain aspects of the user including the email which is used for the backstage id

## Current Behavior
With the oauth2 auth strategy I'm getting an empty profile.  I took a look and I don't seem to be getting back the id_token from the provider.  Looking through the code the `passReqToCallback` seems to be set to `false` https://github.com/backstage/backstage/blob/202da8ab36ed6942c10db994031329ec0a4f5e77/plugins/auth-backend/src/providers/oauth2/provider.ts#L60 this seems to make the params empty on userProfile callbacks so I never get the email

## Possible Solution

* `passReqToCallback` should be set to `true`.
* Check scope to see if it contains `openid`?  If so, then use the `id_token` to retrieve details

* Provide a way to include the /userinfo url and retrieve details from it with the access_token 

## Steps to Reproduce

1. Have a working OAuth2 identity provider that allows the `openid` scope to exist which returns back a `id_token` element
2. Setup a working OAuth2 strategy and pass in the callback/client id, client secret, etc
3. Try to use the signin page component to complete the sign in process

## Context

Without this a user is not able to successfully log in for OAuth2 Providers

## Your Environment

- NodeJS Version (v12): using node:12-buster docker image
- Operating System and Version: using node:12-buster docker image
- Browser Information: Chrome
- Identity Provider: Ping Federation

**Comment by bbourqu** [comment]
https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L53 Looking at step 9 of https://www.pveller.com/oauth2-with-passport-10-steps-recipe/ (I know its a little old but I think it's still relevant) it looks like this would be needed.

**Comment by regicsolutions** [comment]
Thanks for sharing! i have been pulling my hair out with this same issue using the Okta provider. Guess our only option at this point is to manually update the auth-backend plugin and set the flag to true?

**Comment by freben** [comment]
@Rugvip this is something we actually talked about briefly, right? Maybe you can share what the reasoning was

**Comment by Rugvip** [comment]
I don't think setting `passReqToCallback ` affects the id token passing, looking at for example the Google provider, it's picking up the ID token from params: https://github.com/backstage/backstage/blob/5b8eef2e5a829e63f6bc4939a8b6cd64f6529cd8/plugins/auth-backend/src/providers/google/provider.ts#L76

In fact, the `oauth2` strategy already does this as well, https://github.com/backstage/backstage/blob/5b8eef2e5a829e63f6bc4939a8b6cd64f6529cd8/plugins/auth-backend/src/providers/oauth2/provider.ts#L69

Are you sure your OAuth provider supports OIDC?
