### ISSUE TITLE
 Make it possible to use redoc instead of swagger-ui to render openapi-specifications

### ISSUE THREAD

**Issue by O5ten** [backstage/backstage#3898]
## Feature Suggestion

Some of our developers are asking to display their swagger/openapi specifications with redoc instead of swagger-ui to render their openapi specs. I had a short look through it and it seems very usable, albeit strictly developer oriented. Seems to have a React component and everything. Perhaps we can make the api-docs-plugin renderer pluggable? 

### project:
https://github.com/Redocly/redoc

### petstore demo
http://redocly.github.io/redoc

## Possible Implementation

Make the renderer pluggable. 

## Context

Our developers want this and we are asked to provide it. :)

**Comment by dhenneke** [comment]
You should already be able to do that by overriding the `apiDocsConfigRef` ([see here for the default value](https://github.com/backstage/backstage/blob/091561031a702d928f8c7fb2723b6d5a08e3d1c0/plugins/api-docs/src/plugin.ts#L31)). Use the [`defaultDefinitionWidget()`](https://github.com/backstage/backstage/blob/091561031a702d928f8c7fb2723b6d5a08e3d1c0/plugins/api-docs/src/components/ApiDefinitionCard/ApiDefinitionWidget.tsx#L31) and provide a new widget for openapi (or any other new type) that renders the definition text in the lib of your choice.

But we should definitely improve the docs for this customizations.

**Comment by webark** [comment]
@O5ten did you ever get this working? For some reason, it seems like redoc wants to be rendering on the server cause I'm getting these "path.join" errors when trying to use the `RedocStandalone` component.

**Comment by fabidick22** [comment]
Hi @webark, did you have any luck implementing redoc?

**Comment by webark** [comment]
Yea. We use redoc. There's an api ref you can extend. I keep meaning to get the code for you, but i forget.

**Comment by webark** [comment]
@fabidick22 

```typescript
import React from 'react';

import type { ApiEntity } from '@backstage/catalog-model';
import { createApiFactory } from '@backstage/core-plugin-api';
import { apiDocsConfigRef, defaultDefinitionWidgets } from '@backstage/plugin-api-docs';

import { ApiSpec } from '@internal/plugin-api-docs-module-api-platform';

export function apiDocsConfigFactory() {
  return createApiFactory({
    api: apiDocsConfigRef,
    deps: {},
    factory: () => {
      // load the default widgets
      const definitionWidgets = defaultDefinitionWidgets();
      return {
        getApiDefinitionWidget: (apiEntity: ApiEntity) => {
          if (apiEntity.spec.type === 'openapi') {
            return {
              rawLanguage: 'json',
              title: 'OpenAPI',
              type: 'openapi',
              component: (definition: string) => <ApiSpec definition={JSON.parse(definition)} />,
            };
          }

          // fallback to the defaults
          return definitionWidgets.find(d => d.type === apiEntity.spec.type);
        },
      };
    },
  });
}
```
and then right now we have to pull from the CDN version of redoc cause the package wasn't working a while back.. so we do this hack.
```tsx
import React, { useEffect } from 'react';

declare const Redoc: any;

async function loadScript(scriptSrc: string) {
  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = scriptSrc;
    script.async = true;
    script.onload = resolve;
    script.onerror = reject;
    document.head.appendChild(script);
  });
}

function RedocStandalone({ spec, specUrl, options, onLoaded }: any) {
  useEffect(() => {
    async function setupRedoc() {
      if (typeof Redoc === 'undefined')
        await loadScript('https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js');

      Redoc.init(spec || specUrl, options, document.getElementById('redoc-container'), onLoaded);
    }

    setupRedoc();
  });

  return <div id="redoc-container" data-testid="redoc-container" />;
}

export function ApiSpec({ definition }: { definition: any }) {
  return (
    <div style={{ backgroundColor: 'white' }}>
      <RedocStandalone
        spec={definition}
        options={{
          showExtensions: true,
          nativeScrollbars: true,
          theme: {},
        }}
      />
    </div>
  );
}
```

**Comment by fabidick22** [comment]
Awesome, I'll to replicate this in my backstage instance, thanks.
