### ISSUE TITLE
Ability to deploy a helm chart via scaffolder or other plugin

### ISSUE THREAD

**Issue by braghettos** [backstage/backstage#3905]
## Summary

I think that Backstage is missing a key value that could be deploying a helm chart with the templated values to a Kubernetes cluster. 
Right now there is a Kubernetes plugin that fetches resources on a cluster, but it doesn't allow to deploy them.

**Comment by benjdlambert** [comment]
Realised I commented on this the wrong way round, so copying the quote from the other PR.

>Hey @braghettos, thinking that maybe helm should be it's own plugin and not really tied to the k8s underlying API.
>
>Helm is an abstraction on the top of k8s, so I think it deserves it's own space to manage this. But it might depend on the k8s >api to talk to tiller or what have you.

**Comment by braghettos** [comment]
Thank you @benjaminr ! Are there any insights regarding a development of a plugin for helm chart deployment from the Backstage core team?

**Comment by kaos** [comment]
FYI. We are currently in the process of developing a service aimed at deploying "stuff". (it is working on a high level of abstraction, so deploying helm charts to a k8s cluster is just one of many possible use cases.)
There will be a backstage plugin for it to leverage everything backstage. We plan to release it as open source later this year, hopefully by the summer there will be a version you can try out.

**Comment by benjdlambert** [comment]
@braghettos sorry, I've just seen this, It appeared that you tagged the wrong user!

There's nothing ongoing from the core team but contributions would of course be welcome to contributions.

I think that some of the work around #3745 might be of interest to you, as we're changing how to define steps for the scaffolder. So it's making it much easier to add new functions and chain them together, and maybe write a new function to handle deploying some helm chart somewhere.

However, this really maybe isn't something that really the scaffolder should be concerned with. It wont have any permissions to any clusters or anything, and thinking that a better place for this logic should be in the CI build after the scaffolder has created the repository.

**Comment by regicsolutions** [comment]
@braghettos Backstage out of the box uses cookiecutter as its templating engine which is very popular where you can find tons of cookiecutter helm templates on GitHub. [Cookiecutter](https://cookiecutter.readthedocs.io/en/latest/) uses [Jinja2](https://jinja.palletsprojects.com/en/2.11.x/) syntax to replace or customize folder and file names, as well as file content, here’s some sample cookiecutter helm templates: 

https://github.com/michalvanco/gdc-k8s-templates

**Comment by benjdlambert** [comment]
@braghettos wondering if we can close this issue now?

**Comment by braghettos** [comment]
Hi @benjaminr , we can definitely close the issue, I used cookiecutter to template an helm chart.
