### ISSUE TITLE
Config file validation should consider dynamic data for required fields

### ISSUE THREAD

**Issue by dhenneke** [backstage/backstage#3922]
> “On the hunt for edge-cases...”

Given the following config schema:

```ts
// config.d.ts
{
  /**
   * some random required property
   */
  myProperty: string
}
```

If one uses the following `app-config.yaml`'s, it works as expected:
```yaml
# app-config.correct.yaml
myProperty: anything

# -> Result: valid
```
```yaml
# app-config.invalid.yaml
myPropertyyyyy: anything

# -> Result: Config should have required property 'myProperty' { missingProperty=myProperty }
```

But if one uses the [Secrets and Dynamic data](https://backstage.io/docs/conf/writing#secrets-and-dynamic-data) functionality, it breaks:
```yaml
# app-config.env.yaml
myProperty:
  $env: FILLED_AT_DEPLOYMENT_NOT_AT_BUILD

# -> Result: Config should have required property 'myProperty' { missingProperty=myProperty }
```

## Expected Behavior

The value of `$env` / `$data` / `$include` might only be available at deployment time, so the config validator should interpret them as "valid value".

## Current Behavior

The value is indeed empty, so it complains about it correctly. But since we expect it to be filled _after_ then build, it should somehow work.

## Context

#3739 and #3776 (correctly) introduced the config schemas for the catalog. But with the following in our app-config:

```yaml
#...

catalog:
  # ...
  processors:
    microsoftGraphOrg:
      providers:
        - target: https://graph.microsoft.com/v1.0/
          tenantId: ***
          clientId:
            $env: AUTH_MICROSOFT_CLIENT_ID
          clientSecret:
            $env: AUTH_MICROSOFT_CLIENT_SECRET
```

we get:

```sh
$ yarn backstage-cli config:check
Loaded config from app-config.yaml, app-config.local.yaml

Error: Configuration does not match schema

  Config should have required property 'clientId' { missingProperty=clientId } at .catalog.processors.microsoftGraphOrg.providers[0]
  Config should have required property 'clientSecret' { missingProperty=clientSecret } at .catalog.processors.microsoftGraphOrg.providers[0]

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
---
I would be happy to contribute the solution, but would need some initial guidance on how this could be solved.

**Comment by Fox32** [comment]
I would expect the cli to skip variables that are filled from the environment. The cli is a development tool and won't have access to the real environment and won't run in that environment? We could also add this as an optional flag if we don't want to make it the default behavior, like `yarn backstage-cli config:check --ignore-env-substitutions`?

**Comment by Rugvip** [comment]
👍  to assuming that env vars are filled in. I think the simplest fix would be to extend the config loader and config check command so that every env var is fulled in with just `"x"` or w/e. After we've loaded the config we lose any information about any substitutions that were or weren't done, so can't really do it then unless we do a bigger refactor.

**Comment by dhenneke** [comment]
Yeah that should work for the simple cases (if they request a string). But I'd imagine this would break for things like [the suggested GitHub App config](https://github.com/backstage/backstage/blob/4211198c3076d337de1789230469d195f9c81345/docs/plugins/github-apps.md#including-in-integrations-config) where I also assume that not everyone has these info already in the build process. Also a (future) schema-based config editor might want to support this feature. But It wouldn't be reasonable to make _every_ single field a `T | {$env: string} | {$include: ...} | ...` and bloat the schema with that. Things like #3528 make things more complicated, too, though there would be at least something somewhat semantically correct remaining after a substitution with "empy".
