### ISSUE TITLE
demo: Viewing an API throws Error: No implementation available for apiRef{plugin.api-docs.config}

### ISSUE THREAD

**Issue by tkrajcar** [backstage/backstage#3923]
When going to https://demo.backstage.io/catalog/default/component/wayback-search/api I get the following in the console log:

```
2react-dom.production.min.js:209 Error: No implementation available for apiRef{plugin.api-docs.config}
    at T (index.esm.js:55)
    at A (index.esm.js:393)
    at $i (react-dom.production.min.js:153)
    at go (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at ou (react-dom.production.min.js:246)
    at Zo (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Wl (react-dom.production.min.js:122)
Za @ react-dom.production.min.js:209
react-dom.production.min.js:209 TypeError: Cannot read property 'scrollWidth' of null
    at a.value (material-table.js:624)
    at lo (react-dom.production.min.js:212)
    at pu (react-dom.production.min.js:255)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Wl (react-dom.production.min.js:122)
    at du (react-dom.production.min.js:248)
    at Zo (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Wl (react-dom.production.min.js:122)
Za @ react-dom.production.min.js:209
index.esm.js:55 Uncaught (in promise) Error: No implementation available for apiRef{plugin.api-docs.config}
    at T (index.esm.js:55)
    at A (index.esm.js:393)
    at $i (react-dom.production.min.js:153)
    at go (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at ou (react-dom.production.min.js:246)
    at Zo (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Wl (react-dom.production.min.js:122)
```

Tested with my usual Chrome and a fresh (no extensions/config) Firefox, same behavior.

**Comment by Fox32** [comment]
The api-docs plugin is not initialized correctly. I created a small PR in the relevant repository https://github.com/backstage/demo/pull/14

**Comment by Remyapraveen** [comment]
Hi, While I am trying to start the techdocs in the local server using the below command "npx @techdocs/cli serve --docker-image spotify/techdocs" I am getting an error of "No implementation available for apiRef{plugin.search.queryservice}". 

The whole error message shows something like this. 

Error

Error
Message

No implementation available for apiRef{plugin.search.queryservice}
Stack Trace

ne@http://localhost:3000/static/main.78e87b92.js:30:85915
Se@http://localhost:3000/static/main.78e87b92.js:31:167399
Ge@http://localhost:3000/static/main.78e87b92.js:31:168603
ui@http://localhost:3000/static/module-react-dom.5abdac04.js:12:52896
ws@http://localhost:3000/static/module-react-dom.5abdac04.js:16:8700
hs@http://localhost:3000/static/module-react-dom.5abdac04.js:16:939
Za@http://localhost:3000/static/module-react-dom.5abdac04.js:16:870
$t@http://localhost:3000/static/module-react-dom.5abdac04.js:16:726
Mi@http://localhost:3000/static/module-react-dom.5abdac04.js:14:10871
52967/mo/<@http://localhost:3000/static/module-react-dom.5abdac04.js:12:38720
9670/L.unstable_runWithPriority@http://localhost:3000/static/module-react-dom.5abdac04.js:23:3904
Sn@http://localhost:3000/static/module-react-dom.5abdac04.js:12:38498
mo@http://localhost:3000/static/module-react-dom.5abdac04.js:12:38668
Le@http://localhost:3000/static/module-react-dom.5abdac04.js:12:38601
un@http://localhost:3000/static/module-react-dom.5abdac04.js:14:8448
fi@http://localhost:3000/static/module-react-dom.5abdac04.js:12:58178
67896/ye/</<@http://localhost:3000/static/main.78e87b92.js:490:6241

**Comment by Remyapraveen** [comment]
Could anyone please do help me out with this. I had this thing working a few weeks ago. Not sure what went wrong now..

**Comment by andrewthauer** [comment]
This issue is different from what you are seeing, aside from the message (e.g. different plugin). My suggestion is to open an new GH issue.

However, that said I have a guess on what might have happened (not the actual issue). When you install the `techdocs-cli` it will install all of it's dependencies that are defined in the `package.json`. Since most of these dependencies are not pinned to an exact version, it's possible you updated it and it pulled in a newer version within the semver range and that dependency isn't playing nice with techdocs-cli. We've seen this happen in the past, but it's not common. As for what package or the actual issue, I'm not entirely sure. This is just a guess why it started all of the sudden.

**Comment by Remyapraveen** [comment]
hi @andrewthauer, thanks a lot for your response. So, do you suggest I go ahead and open a new issue?
