### ISSUE TITLE
[Plugin] Gitlab CI

### ISSUE THREAD

**Issue by deepakbitragunta** [backstage/backstage#3926]
## Summary

Gitlab offers SCM and a declarative CI(Continuous Integration) pipeline. Backstage can offer a 1-click new project creation and a corresponding CI pipeline creation as well.

## Project website (if applicable)

- https://github.com/screwdriver-cd/scm-gitlab
- https://gitlab.com/gitlab-org/gitlab-foss/-/issues

## Context

Application development teams need a simpler process to create source code repositories and CI pipelines using templates. The templates allow teams to maintain development standards and follow compliance restrictions if there is any

**Comment by OrkoHunter** [comment]
> Backstage can offer a 1-click new project creation

This is currently achievable even for GitLab using the Scaffolder plugin. https://backstage.io/docs/features/software-templates/software-templates-index

**Comment by zarry** [comment]
What is the state of this?  This looks to be in the "plugins already in progress section" but I don't see an MR or repo linked.  Is someone working on this?  Is the desired approach using Scaffolder instead?

**Comment by freben** [comment]
As mentioned, we do have support already for creating new software repositories from templates in GitLab. The ticket mentions pipeline creation - with the new scaffolder work that is ongoing right now, it will be possible to add custom steps that do things like that after creation of the repo itself.

@deepakbitragunta Is there something else besides that, that you intended the ticket to cover?

**Comment by zarry** [comment]
Appreciate the response @freben.  It sounds like scaffolder will eventually cover most use cases involving gitlab for creation.  One area that hasn't been mentioned yet is the CI aspect that gitlab provides.  Is there a current mechanism/plugin for visualizing the state of a build, kicking a build off, etc as you would see with some of the other CI plugin integrations?

**Comment by freben** [comment]
Good point, no I don't think there is yet.

**Comment by satrox28** [comment]
We are working on the Gitlab Plugin, to show the pipeline status, retry pipeline, list contributors, list languages

**Comment by eperdeme** [comment]
> We are working on the Gitlab Plugin which will have below features.
> 
> Pipeline status
> Retry build
> List contributors
> List languages
> List Merge Request
> MR metrics(Avg Time taken to approve MR).
> 
> Please assign the ticket to me, thanks.

This is great news. Could I ask for tasks such as retry/etc are you planning to use the users auth token to do this? Otherwise if its a backend shared API key, then any backstage user could gain elevated privileges.

**Comment by satrox28** [comment]
> > We are working on the Gitlab Plugin which will have below features.
> > Pipeline status
> > Retry build
> > List contributors
> > List languages 
> > List Merge Request
> > MR metrics(Avg Time taken to approve MR).
> > Please assign the ticket to me, thanks.
> 
> This is great news. Could I ask for tasks such as retry/etc are you planning to use the users auth token to do this? Otherwise if its a backend shared API key, then any backstage user could gain elevated privileges.

Currently, we are trying to do only read operation so the API scope for the user required is Read API. Retry build is optional feature which we are thinking right now as any one on Backstage can trigger any other services build as Backstage don't offer RBAC.

**Comment by satrox28** [comment]
Gitlab Plugin released 

https://github.com/backstage/backstage/pull/6857

**Comment by NishkarshRaj** [comment]
Awesome work @satrox28 👍

**Comment by jhaals** [comment]
Looks like this is implemented :)
Closing the issue for now, feel free to reopen if more discussions are needed.
