### ISSUE TITLE
Limit authorized email domains when using OAuth2

### ISSUE THREAD

**Issue by Crevil** [backstage/backstage#3935]
When using the Google oauth2 provider any email hosted by google can be used, e.g. `@mycompany.com`, `@gmail.com`. This can be unexpected when setting up the provider and further more there is no way to limit what domains to authorize.

## Feature Suggestion

Add a configuration option for valid email domains that are verified in the ID tokens to limit the usable domains.

### Similar features in other projects

- [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) project provides an `--email-domain` flag ([docs](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview)).
- [grafana](https://github.com/grafana/grafana) provides the `allowed_domains` configuration ([docs](https://grafana.com/docs/grafana/latest/auth/generic-oauth/))
- Google provides the [`hd` (hosted domain)](https://developers.google.com/identity/protocols/oauth2/openid-connect#hd-param) paramater to limit the presented range of emails when selecting. (note: this is a visual filter only but can be used by validating the ID token)

## Possible Implementation

Add a configuration option for valid domains on the google provider and validate the authenticated email against the domains afterwards.

The `hd` parameter is only supported by Google directly so that option is limited to a single provider. If a more generic validation is added we can cover all of the providers (a better solution IMO).

### Other implementations

- oauth2-proxy validation step: https://github.com/oauth2-proxy/oauth2-proxy/blob/d7abd56981c72ab71baf5429e5eefc7406c9677f/oauthproxy.go#L806-L818
- grafana: https://github.com/grafana/grafana/blob/8485283077febc08a5fc036a878484c0cb465313/pkg/api/login_oauth.go#L171-L174

## Context

Many users in Lunar has both a private and cooperate email on their laptops, e.g. `@gmail.com` and `@lunar.app`.
This is a potential 

## Note

We are happy to provide the implementation of this feature if acceptable.

**Comment by tragiclifestories** [comment]
Possibly related https://github.com/backstage/backstage/issues/3870

**Comment by Crevil** [comment]
The RFC of #3870 and its successor #4089 does include options for restricting access as sugested.

The work being done in #4532 gives us a hook to add this limitation with the `ProfileTransform<AuthResult>` type.

**Comment by Crevil** [comment]
I can see that @OrkoHunter ia doing some work on the PR that fixes this request. Let's keep this non-stale just a bit further. 🙏

**Comment by timbonicus** [comment]
#4532 will add the hook to prevent this securely on the backend, but the frontend configuration option is still desirable to limit the sign-in options presented (rather than permitting selection of invalid domains and then failing).

**Comment by sbrnunes** [comment]
Hi @Rugvip , any chances of having #4532 merged soon? Came across this issue when fighting a similar concern (restricting the access to selected hosted domains from Google).

**Comment by freben** [comment]
@sbrnunes We have a task on our board to look at it very soon, but I can't promise it happens before the release tomorrow.

**Comment by sbrnunes** [comment]
> @sbrnunes We have a task on our board to look at it very soon, but I can't promise it happens before the release tomorrow.

Thanks @freben. No worries, was only afraid it could be blocked for some reason. Glad to know you're going to look at it soon enough. 🙇

**Comment by Rugvip** [comment]
@sbrnunes yep!

**Comment by Rugvip** [comment]
Linking this to #6512 as well as that's where it's ultimately being implemented

**Comment by Crevil** [comment]
This was actually closed in #6512 👍
