### ISSUE TITLE
TechDocs: AWS S3 SDK version bump

### ISSUE THREAD

**Issue by ayshiff** [backstage/backstage#3944]
## Feature Suggestion

Currently the `aws-sdk` used in TechDocs is in version 2.
As v3 was just released it could be good to bump the sdk version.
[Link](https://aws.amazon.com/about-aws/whats-new/2020/12/aws-sdk-javascript-version-3-generally-available/)

Here are the benefits of v3:
- Add a better TypeScript support
- A modular architecture with a separate package for each service. 
It will allow us to do:
```ts
import { S3 } from ‘’@aws-sdk/client-s3;
```
 instead of:
```ts
import aws from 'aws-sdk';
```
- We no longer need to use `.promise()` which are not required

## Possible Implementation

Remove the aws sdk v2 and install the AWS service package for Amazon S3 `@aws-sdk/client-s3`.
Update`packages/techdocs-common/src/stages/publish/awsS3.ts` to use v3 and the S3 mock here `packages/techdocs-common/__mocks__/aws-sdk.ts` to match the new S3 signature.

## Context

PR which added Techdocs AWS S3 support #3794

**NOTE :** This feature is **already implemented**.
I could not include it in the PR because `aws-sdk-js-v3` had some TypeScript issues which were pending fix.
I will do a PR in the next few days.

**Comment by OrkoHunter** [comment]
Took the liberty to assign the issue to you since you already have something on this. Hope that's okay!
