### ISSUE TITLE
TechDocs: Improve S3 credentials handling

### ISSUE THREAD

**Issue by ayshiff** [backstage/backstage#3946]
## Feature Suggestion

The user should be able to load AWS credentials from the shared credentials file.
- Linux, Unix, macOS: `~/.aws/credentials`
- Windows: `C:\Users\USER_NAME\.aws\credentials`

## Possible Implementation

Handle S3 configuration apart from explicitly defining configs.

**Expected behaviour:** 

If the user specifies an `accessKeyId` and a `secretAccessKey` ([Link](https://github.com/backstage/backstage/blob/60f16c9cb57efdf9d1931517c82d6f5f7a2532f8/packages/techdocs-common/src/stages/publish/awsS3.ts#L34)) we should use them (as it is now):

```ts
const storageClient = new aws.S3({
  credentials: { accessKeyId, secretAccessKey },
});
```

**If not:**

By default, when the SDK loads, it automatically searches the shared credentials file, called `credentials`.
So we can instantiate the sdk without explicitly defining credentials:

```ts
new aws.S3()
```

We can also check if the user has correctly set his credentials:

```ts
AWS.config.getCredentials((err) => {
  if (!err) {
     // Credentials are loaded
    console.log("Access key id:", AWS.config.credentials.accessKeyId);
    console.log("Secret access key:", AWS.config.credentials.secretAccessKey);
  }
});
```

Here is a diagram to recap:
<p align="center">
<img src="https://user-images.githubusercontent.com/32459935/103789736-a1589c00-5040-11eb-8ccf-54c5921533b3.png" width="600" />
</p>

## Context

PR which added Techdocs AWS S3 support #3794

**Comment by OrkoHunter** [comment]
Notes:
1. `region` is required in the aws-sdk v3 client. However, `AWS_REGION` and `AWS_DEFAULT_REGION` is used by the client as fallback. So, in `app-config.yaml` we can keep it as optional.
2. `AWS.config.getCredentials()` sounds like a good idea. However, we also need to ensure that the credentials provided has access to the S3 bucket. Hence bucket metadata retrieval makes more sense to me.
