### ISSUE TITLE
Possibility to mock backstage apis for plugin dev environment

### ISSUE THREAD

**Issue by mcalus3** [backstage/backstage#3950]
I am exploring the possibility to do cypress testing for backstage plugins. One requirement for it is to be able to mock backstage apis used by the plugin to prevent communication with external servives like OAuth providers. I was trying to run plugin development environment (createDevApp from @backstage/dev-utils) with mocked backstage api's, but from what I see in the code, although there is a possibility to add a *new* api by `DevAppBuilder.registerApi` method, it's impossible to change implementation for apis that are already defined in `defaultApis` export from `backstage\packages\core\src\api-wrappers\defaultApis.ts` file. I've also tried to wrap my plugin react component for dev environment with ApiProvider component with custom ApiRegistry (i've seen that pattern in jest tests, for example in `backstage\plugins\scaffolder\src\components\TemplatePage\TemplatePage.test.tsx`):

```ts
const apis = ApiRegistry.from([
  [errorApiRef, errorApiMock],
  [catalogApiRef, catalogApiMock],
]);

export const pluginStandalone: BackstagePlugin = createPlugin({
  id: 'firebase-functions',
  register({ router }) {
    router.addRoute(standaloneRootRouteRef, () => (
      <ApiProvider apis={apis}>
        <FirebaseFunctionsPage entity={getEntityMock()} />
      </ApiProvider>
    ));
  },
});
```

but still without success.

For now I gave up with trying to run the standalone plugin dev environment with mocked backstage apis, but if you know any way to get it working or decide to implement such a possibility, you can let me know.

**Comment by lowjoel** [comment]
I think this would also help #2178.

**Comment by freben** [comment]
So APIs are registered with a certain `priority`, and you are allowed to override things that aren't of the `"static"` priority. There are three such APIs in the default app builder: `appThemeApiRef`, `configApiRef`, and `identityApiRef`. Was it one of these that caught you?

**Comment by mcalus3** [comment]
No, I wanted to mock `GoogleAuthApi` and `GithubAuthApi`. Thanks for the info that it's possible to override it :) When I get back to this I'll try it.

**Comment by freben** [comment]
Ok! Let us know how it goes

**Comment by adamdmharvey** [comment]
@mcalus3 Wanted to check in - did you give the mocking a try or any other feedback to your original ticket?

**Comment by mcalus3** [comment]
@adamdmharvey no, I haven't been working on it.

**Comment by benjdlambert** [comment]
@mcalus3 could we close this ticket with the suggestions that already mentioned?

**Comment by mcalus3** [comment]
Yes, sure
