### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by katz95** [backstage/backstage#3965]
## 🗒 General
![ezgif com-gif-maker](https://user-images.githubusercontent.com/61153904/104009999-27452600-51ac-11eb-8ef2-3de9b892a0d3.gif)

We'd love help building out a breadcrumb component for Backstage! Breadcrumbs take place in the header, above the Title. Our breadcrumbs are expandable and can also show (via dropdown) pages that are on the same hierarchical level.

## 💻 Usage

![Breadcrumbs in Header](https://user-images.githubusercontent.com/61153904/104010414-bce0b580-51ac-11eb-999b-31698ee44629.png)

An example of the logic of our breadcrumbs is as follows:
![Logic Examples](https://user-images.githubusercontent.com/61153904/104011148-f665f080-51ad-11eb-9f12-662608866830.png)

## 📐 Specs

Specs can be found by duplicating our [UX kit in Figma](https://www.figma.com/@backstage). Under the 'Headers (w/ Breadcrumbs' page, you'll find breadcrumb specs.

## 🔮 Future

We're playing around with the idea of modifying the header, so breadcrumbs potentially can live outside of the header (above the page title instead). Stay tuned.

**Comment by emmaindal** [comment]
Awesome @katz95 Thank you!!

**Comment by benjdlambert** [comment]
These look awesome! @katz95

**Comment by tudi2d** [comment]
The component looks great - I would like to help implementing it! :)

**Comment by emmaindal** [comment]
Amazing @tudi2d I'll assign it to you!

**Comment by tudi2d** [comment]
Just a small, edge case question @katz95. What should happen if layered breadcrumbs are hidden? Should there be an expandable accordion in the Popover?

Here is a first look. I will probably finish it over the weekend.
![image](https://user-images.githubusercontent.com/8904624/107712567-ed46d280-6cc9-11eb-9eba-ca8cfea93eb1.png)

**Comment by benjdlambert** [comment]
@tudi2d not sure if you're also already doing this, but there's some nice components already in MUI that could be worth having a look at too https://material-ui.com/components/breadcrumbs/

**Comment by katz95** [comment]
thank you for doing all of this! @tudi2d it looks great. if layered breadcrumbs are in a dropdown, i'm thinking we should just keep it simple and not show any accordion. if the user clicks on a layered breadcrumb within a dropdown though, we can just take them to that 'current page', where it shows the dropdown.

**Comment by freben** [comment]
Oh yeah, the ones that @benjdlambert linked to - do they actually support the use cases we need or at least satisfactorily? If we can, we should leverage that one 100%, and if not, use it as much as possible and make smaller additions where necessary (the dropdown thing?).

**Comment by tudi2d** [comment]
@freben Agree. I basically used the MUI component and enforced the proposed style. Furthermore I added a different hidden behavior, as MUI does not use a Popover, but rather extends hidden Links inline. Always happy about feedback :)
