### ISSUE TITLE
TechDocs: Binary file is not showed up with awsS3 publisher

### ISSUE THREAD

**Issue by jizg** [backstage/backstage#3990]
I am trying to using awsS3 as publishser, and found that binary file such png image cannot be showed up at frontend. I've done some debug and found out that if remove the `toString()` function in the following code, png image file is displayed normally.

https://github.com/backstage/backstage/blob/54faa6fa8d32da6568ff8cf073328352e7881b2a/packages/techdocs-common/src/stages/publish/awsS3.ts#L189

**Comment by OrkoHunter** [comment]
I tried your suggestion and it worked. :) PR is up at https://github.com/backstage/backstage/pull/3991

Thank you for reporting @jizg, this is a great contribution!
