### ISSUE TITLE
CI/CD switcher defaults to Github Actions for github repositories

### ISSUE THREAD

**Issue by erikxiv** [backstage/backstage#3996]
In `EntityPage.tsx`, for both the CI/CD tab as well as the overview page widget, there is a CI/CD switch statement with the intent to choose the CI/CD tool in use for the specific entity. The switch uses the exported function `isPluginApplicableToEntity` from respective plugin to check if the CI/CD tool is in use. The `isPluginApplicableToEntity` function for the github actions plugin responds with true for all entities that have specificed the `github.com/project-slug` metadata annotation, even though this does not mean that github actions is used as the CI/CD tool for the entity.

## Expected Behavior

The CI/CD tool that is applicable for the current entity is chosen/displayed

## Current Behavior

Github Actions is chosen as the CI/CD tool (if it is earlier in the switch statement than the actual CI/CD tool).

## Possible Solution

* Use another annotation to signify github actions
* Check with github if github actions is enabled/used on the repository

## Steps to Reproduce

1. Start example-backend in backstage (with all CI/CD providers enabled)
2. Add an entity with the `github.com/project-slug` metadata annotation specified
3. Visit the overview page for that entity, or the CI/CD tab on the entity page.
4. The page will show `This component has GitHub Actions enabled, but no data was found`

## Context

We are mainly using Travis (but also some Github Actions) further down in the switch statement. To get that to work I need to change the order of the CI/CD switcher to avoid Github Actions shadowing Travis content.

## Your Environment

- NodeJS Version (v12): v12
- Operating System and Version (e.g. Ubuntu 14.04): Docker/alpine
- Browser Information: Chrome

**Comment by andrewthauer** [comment]
I agree this annotation is to general and I believe is used for at least couple of different  uses that can be enabled independently.

The way around this is to ensure another CI/CD provider is higher in the case statement. However this only works for the entity tab and not the workflow widget. On top of that it is possible to use multiple CI/CD solutions for a single entity which means the case statement approach doesn't work.

**Comment by freben** [comment]
Agreed that this is problematic.

The annotation mechanism is a blessing and a curse :) We could extend with specific annotations for each feature easily, and the concept is pretty powerful. But since they are fairly commonly written by humans, it quickly gets old to have a ton of annotations to type out / copy-paste, many with overlapping values as well, just to enable every single feature you want to use in the frontend.

I don't have a great answer straight off the top of my head, when the base, simple classification is insufficient. Ideally the frontend would talk to the underlying provider and decide whether there's anything to show or not (as you yourself suggest). Drawback being, that there will be spinners and delays in the interface just to decide that there was nothing to draw in the first place, even in the cases where we maybe knew from the get-go that we were only interested in one of many side effects of adding the annotation.

Sometimes one can improve the frontend experience by using caching. The backend could keep an up-to-date state of all projects, what features that are actually in use for that project. Or something like that. But that obviously increases complexity. So, short term, adding "smarts" to `isPluginApplicableToEntity` sounds like the best approach.

**Comment by andrewthauer** [comment]
Very good points here. Some features could also probably be detected as part of a catalog processor pass as well. For instance, pretty sure an API call to GH could determine if the repo has actions configured or not. This detail could then be append to the entity which is then available for the UI to use as needed. Thus avoiding the need for humans to maintain this information.

**Comment by freben** [comment]
Yeah. With the caveat then, that one starts to wonder how much such "cache" data to put in the catalog - and in particular, how much of it should really be directly ON the entity, inside itself? As opposed to being in a separate cache bag somewhere. Then my mind starts to drift and thinking ... IS the annotations basically that cache bag and should rightfully be regarded as such and used as such without abandon? Hm. It's in the metadata part for a reason...

**Comment by erikxiv** [comment]
Playing devils advocate to my own issue: might be this specific issue is a non-issue in most deployments, where the adopter knows a priori which ci/cd systems are in use and can select those, order them if wanted and perhaps even skip the switcher and show two widgets/tabs for two different ci/cd systems? Rethinking annotations and the conceptual basis for them sounds really interesting and valuable for coming scenarios, but a bit overkill for this smallish thing? Maybe just reordering github actions to the bottom of the example-app is the appropriate response?

**Comment by erikxiv** [comment]
Auto-detection of features (and errors) sounds really helpful though to keep the catalog fresh and complete. Maybe a dependabot strategy where a daily pass of entities automatically adds pull requests to modify catalog-info.yaml with added and removed features, removes hanging references and whatnot? A helpful assistant that tries to keep catalog metadata up to date with reality, with optional human approval before merging. This assistant can also be externalized, looking through various external systems to find entities missing in the catalog etc. Just thinking out loud.

**Comment by andrewthauer** [comment]
I think it probably makes sense to lower the priory of GitHub, in the sample app. The odds are if someone has another provider enabled it is most likely the primary. There are also workarounds as you mention to support multiple so it is possible as well.

> Auto-detection of features (and errors) sounds really helpful though to keep the catalog fresh and complete. Maybe a dependabot strategy where a daily pass of entities automatically adds pull requests to modify catalog-info.yaml with added and removed features, removes hanging references and whatnot? A helpful assistant that tries to keep catalog metadata up to date with reality, with optional human approval before merging. This assistant can also be externalized, looking through various external systems to find entities missing in the catalog etc. Just thinking out loud.

The idea around posting PR updates is interesting. However, I think any data that can be automatically added to the entity should probably just be appended in the background for the team. That way it keeps the catalog file down to the essentials. It also gives a way to override the auto value more deterministically. That said it does make it challenging for understand the entity data in its entirety and how it came to be.

Another idea we've been floating around is the idea of a hygiene scorecard. Essentially this would indicate things about the component that may not be configured it an optimal way. This could be anything from infra setup to suggested catalog fields missing.

**Comment by Rugvip** [comment]
👍  to lowering the priority as a short-term fix, but then also continue work on how we handle this long-term.

One idea for a long-term fix would be to have a processor that simply checks if `.github/workflows` exists for github repos, and in that case add a more specific annotation that enables GitHub Actions tooling

**Comment by andrewthauer** [comment]
It looks like this is already fixed. GH actions is the lowest priority in the example apps CICDSwitcher.
