### ISSUE TITLE
Github Actions plugin does not support GHE

### ISSUE THREAD

**Issue by erikxiv** [backstage/backstage#3997]
It seems as if the Github Actions plugin does not support GHE. Despite configuring a GHE instance/api url, the plugin asks api.github.com for data.

## Expected Behavior

The plugin queries GHE for data

## Current Behavior

The plugin queries api.github.com for data, and responds with `Bad credentials` as the GHE credentials does not work with github.com

## Possible Solution

* According to https://octokit.github.io/rest.js/v18, one can set `baseUrl` to work with GHE

## Steps to Reproduce

1. Configure backstage with a GHE instance + apiURL
2. Start backstage, with Gitihub Actions plugin enabled on Entity Page
3. Add an entity with a github.com/project-slug metadata annotation
4. Visit the entity overview page
5. See the Bad credentials notification
6. Look at network requests and see a 401 request to `https://api.github.com/repos/org/repo/actions/runs?per_page=4&page=1`

## Context

Not a problem for me now, but will be when we start usinig Github Actions more

## Your Environment

- NodeJS Version (v12): v12
- Operating System and Version (e.g. Ubuntu 14.04): Alpine
- Browser Information: Chrome

**Comment by benjdlambert** [comment]
Do you wanna take a stab at this @erikxiv? Think it's just a case of using the `integrations` config to find the `apiBaseUrl` for the repository and using that to create the client in the frontend.

**Comment by erikxiv** [comment]
Submitted a PR here https://github.com/backstage/backstage/pull/4019 with some caveats.
