### ISSUE TITLE
[RFC] Simplifying TechDocs (Frontend) Architecture

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#3998]
**Status:** Open for comments

This proposal addresses several limitations in the current implementation of TechDocs, its relationship with MkDocs and describes solutions for them. Most of the problems arise due to the fact that we use the [MkDocs Material](https://squidfunk.github.io/mkdocs-material/) theme to generate a TechDocs site.

# Abstract

TechDocs uses MkDocs and the MkDocs Material theme to create a documentation website. This website can be hosted on its own, it is self-sufficient and does not really need TechDocs/Backstage. The website has its own styling, search, Google Analytics, Disqus integration and what not. We store these generated files in TechDocs storage. When a Backstage user visits a docs page, TechDocs does a series of ["Transformations"](https://github.com/backstage/backstage/tree/master/plugins/techdocs/src/reader/transformers), eventually manipulating the HTML and CSS for them to render correctly in Backstage. Here is how it works -

![techdocs-current (1)](https://user-images.githubusercontent.com/8065913/104134746-e6a40300-538b-11eb-904f-b7f0da2aff58.png)

Thinking clearly, **TechDocs does not need a website, it needs content.** TechDocs/Backstage is already a website, with its own search, navigation menu, headers, footers, etc. All it needs is the content HTML to render (Mostly paragraphs and images and sometimes - code blocks, collapsible content, note, warning, etc.).

# Problems

### 1. **Patching of HTML and CSS is fragile and sensitive to `mkdocs` / `mkdocs-material` versions and its dependencies.**

Since we don’t control the MkDocs theme, we have to manipulate (transform) the generated HTML and CSS a lot. This is not just complicated, but also creates a fragile system. We depend on specific CSS selectors for the transformation, which are liable to change with theme versions. In the internal version of TechDocs, we had a chaotic week once when the `mkdocs-material` version got updated. The gist can be found in the bug report from @andrewthauer when they bumped the `mkdocs-material` version. [https://github.com/backstage/backstage/issues/3558](https://github.com/backstage/backstage/issues/3558)

The dependency on the theme for its stylesheets limits us in terms of things we want to do. For example, the TechDocs navigation is not responsive, and disappears on smaller screens. [https://github.com/backstage/backstage/issues/2462](https://github.com/backstage/backstage/issues/2462)

If we take control of the MkDocs theme used for generation, we can generate the HTML so that it is optimized for being rendered in TechDocs.

### 2. Most of the generated files are unused

**Most of the generated files contain unused HTML and CSS right now. Yet we store these unused files and transfer them over network - wasting storage space and bandwidth. The size of the HTML/CSS file directly impacts the loading speed of a TechDocs site.**

The crux of what TechDocs needs from an MkDocs theme is [this line](https://github.com/squidfunk/mkdocs-material/blob/14a7be164f58aec97eabb3fadd28dbe81aed7f59/material/base.html#L166) i.e. the content of the markdown file rendered in HTML.

```jsx
{{ page.content }}
```

Let's look at a file size comparison for the TechDocs site of [backstage.io/docs](https://github.com/backstage/backstage/tree/master/docs). (As of Jan 10)
_(Excluding images from comparison since they remain unaffected.)_

| File Size  | (Current) mkdocs-material-theme | (Proposed) mkdocs-techdocs-theme |
|------------|---------------------------------|----------------------------------|
| HTML       | 8 MB                            | 2.2 MB                           |
| Javascript | 1.2 MB                          | 0                                |
| CSS        | 0.3 MB                          | 0                                |
| **Total**  | **9.5 MB**                      | **2.2 MB**                       |

> **Size of generated HTML/JS/CSS reduced by 76.8% here for one TechDocs site like** [backstage.io/docs](https://github.com/backstage/backstage/tree/master/docs).

At a scale of Spotify, this means GBs of data saved in storage space and Bandwidth transfer costs.

### 3. Slow page loading and page switching

Page loading and switching time could be reduced by 50-75% if we do not load external CSS on every request and the HTML is reduced in size. Here is a screenshot of the Network tab showing a waterfall of requests and how much time they take. (Using Google Cloud Storage as publisher)

<img width="1792" alt="Screenshot 2021-01-11 at 22 55 59" src="https://user-images.githubusercontent.com/8065913/104243023-3fdd6680-5460-11eb-95e0-d42fd588d755.png">

### 4. Not using Backstage's theme and native components

On each page visit in TechDocs, we fetch its CSS generated by `mkdocs-material`. We later patch some of it using Backstage's theme. This in unnecessary and slows down page load. Backstage/MaterialUI theme is capable of designing a TechDocs site, it doesn't need external CSS.

Since the base CSS of all the TechDocs sites comes from `mkdocs-material`, we are missing out on using the components that are native to Backstage. [https://backstage.io/storybook](https://backstage.io/storybook)

For example: The navigation menu is hardcoded in every TechDocs page's HTML and is reloaded again and again on each page change. The experience with the nav can be improved as shown in this gif, leading to a faster client side navigation and a more native feel.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/8065913/104134861-8cf00880-538c-11eb-82a5-cc6fb42dce10.gif)

(GIF from @hooloovooo's prototype in [https://github.com/backstage/backstage/pull/3842](https://github.com/backstage/backstage/pull/3842))

### 5. Simplify TechDocs Reader

Reducing the number of transformers will simplify the TechDocs `Reader` component and will reduce the number of possible bugs.

### 6. Limitations introduced by ShadowDOM

ShadowDOM is useful for isolating smaller components. But it is not ideal to render an entire page. It causes styling issues like unresponsive behavior on smaller screens [https://github.com/backstage/backstage/issues/2462](https://github.com/backstage/backstage/issues/2462). Analytics tools like [https://www.hotjar.com](https://www.hotjar.com/) do not work with ShadowDOM.
ShadowDOM is an improvement over iFrame, but maybe none is optimal for rendering a TechDocs page.

# Plan

Create a minimalistic [MkDocs theme](https://www.mkdocs.org/user-guide/custom-themes/). The output of `mkdocs build` when using this theme only needs to be the smallest possible HTML with the content of each Markdown page and the assets (images, JSON, etc.). The goal of the theme is to generate the usable HTML content for TechDocs, and not to generate a self-sufficient static website. The theme will generate no Stylesheets and no Javascript.

An MkDocs theme is a [Jinja2 template](https://jinja.palletsprojects.com/en/master/) (what powers Cookiecutter in Scaffolder). It will be a Python package that would look like this -

```jsx
mkdocs_techdocs_theme/
    __init__.py
    main.html
    mkdocs_theme.yml
setup.py
```

And the `main.html` would be as simple as 

```jsx
{% block content %} {{ page.content }} {% endblock %}
```

`page.content` is an [MkDocs variable](https://www.mkdocs.org/user-guide/custom-themes/#pagecontent) containing the HTML rendered from Markdown.

The (much smaller and reduced) generated files will be stored in the same manner as they are currently being stored. Refer to [TechDocs Architecture](https://backstage.io/docs/features/techdocs/architecture).

When a user visits a docs site in TechDocs frontend, the following two processes can happen (we need to decide on one).

Option 1: TechDocs Frontend fetches the HTML file for the page → uses [`sanitize-html`](https://github.com/apostrophecms/sanitize-html) to remove unwanted HTML tags → then uses [`DOMPurify`](https://github.com/cure53/DOMPurify) which removes all kinds of injection scripts (XSS attacks) → and then uses React's [`dangerouslySetHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) to render the HTML content natively without any ShadowDOM.

Option 2: TechDocs Frontend fetches the HTML → uses  [`sanitize-html`](https://github.com/apostrophecms/sanitize-html) to remove unwanted HTML tags → parses the HTML into React components using [`react-html-parser`](https://github.com/wrakky/react-html-parser) (which does not use `dangerouslySetHTML` but uses [`htmlparser2`](https://github.com/fb55/htmlparser2)) → (Maybe: replaces some of these components with Backstage componets i.e. [codeblock](https://backstage.io/storybook/?path=/story/data-display-codesnippet--multiple-lines)) → then runs [`DOMPurify`](https://github.com/cure53/DOMPurify) for security → Renders the components natively without any ShadowDOM.

Notes:

- TechDocs page styling will be available in TechDocs Frontend and will use Backstage theme for colors, fonts, etc.
- [We already use sanitize-html](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/transformers/sanitizeDOM/index.ts) for security and have an allowed list of HTML tags. `sanitize-html` uses `htmlparser2` for the string to HTML parsing.
- For best security practice, DOMPurify always needs to run at the end of all the steps, and just before rendering the HTML.

**Navigation menu**

Site navigation menu on the left will not be present in the HTML files (controlled by the proposed mkdocs theme). The theme will generate the nav into a a file along with `techdocs_metadata.json`. TechDocs will use an API to fetch the nav and render it using native Backstage/MaterialUI components (as shown in GIF above). This way, navigation details will only be fetched once per TechDocs site, even if user switches pages.

(With APIs like these we are unlocking ways to visit the "Future" as described below).

# Risks

*Edge cases of styling*: The above mentioned approach does not create any stylesheets along with the generated HTML. Most of the HTML is supposed to be filled with basic HTML elements like `p`, `img`, `a`, `h1`, `h2`, etc. They are easy to style using native Backstage/TechDocs theme. However, when using specific MkDocs plugins, there can be some blocks/divs with specific class names which would be styled by the CSS generated by the theme. The TechDocs custom theme needs to ensure that the edge case is handled.
Reference of what mkdocs-material supports https://squidfunk.github.io/mkdocs-material/reference/code-blocks/

*Losing some out-of-the-box features of mkdocs-material*: `mkdocs-material` theme comes with quite a few ready-made web components for us to consume: edit page icon, nav menu, next page and previous page links, search box. We are still going to have ALL of these, but they won't be part of the generated HTML. They will be React components created in TechDocs frontend and natively rendered.

*Security*: Since Backstage/TechDocs will consume HTML from an external source, this leads to a possibility of cross-site scripting. We are taking multiple actions to prevent this -
- Using [`sanitize-html`](https://github.com/apostrophecms/sanitize-html) library with an allowed list of attributes (which does not contain `script` tag).
- On top of it, using [DOMPurify](https://github.com/cure53/DOMPurify) to remove scripts.
- Limiting `script-src` [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) in Backstage's [app-config.yaml](https://github.com/backstage/backstage/blob/ded50057994d94c3ca97eac5977d7e141b6ed086/packages/backend-common/src/service/lib/ServiceBuilderImpl.ts#L55)

# Benefits

- Reduce complexity, lesser bugs in Reader and avoid frontend incidents due to vendor (mkdocs-material) version changes →  "Make TechDocs stable and rock solid"
- Faster page load and page switch times due to smaller HTML file size. and no external CSS loading. (Every page now fetches the CSS files on each load. Currently we delay rendering of HTML until CSS files are loaded to "prevent" the glitch experience.)
- $$ Savings - Reduced cloud storage space and Cloud inbound/outbound data cost.
- TechDocs can be natively styled with Backstage theme. Thus, following the philosophy of Backstage to standardize Developer Experience with familiar design patterns.
- Unlock the future of TechDocs.

# Future of TechDocs: MkDocs should be an option, not a requirement

_(This proposal only paves the way for the future to be possible, but the work is out of the scope of custom theme development.)_

Markdown is a very popular choice for writing documentation, and will be our top priority moving ahead; but we are aware of the alternatives of Markdown.

MkDocs is just one static site generator which has served well in Spotify's TechDocs journey so far, but there are alternatives and some are [even more popular](https://github.com/topics/static-site-generator) with insane build speed ([Hugo takes <1s for generating 10K pages](https://forestry.io/blog/hugo-vs-jekyll-benchmark/)).

As stated previously, **TechDocs does not need a website, it needs content.** The content can just be HTML or something more fundamental. We are already on a website (i.e. Backstage) and we need data that we have to render. The data can be in a JSON format adhering to a specification that TechDocs understands and knows how to render. The JSON would represent something similar to a DOM tree with the types of elements and their content. Some of these elements may have class names . And maybe some additional metadata for TechDocs specific elements (like warnings and notes).

An example spec in JSON (Of course, looks a lot similar to HTML DOM).

```js
[
	{
		elementType: 'p',
		data: 'This is a paragraph'
	},
	{
		elementType: 'img',
		source: 'https://backstage.io/img/logo.svg'
	},
	{
		elementType: 'codeembed',
		source: 'https://raw.githubusercontent.com/backstage/backstage/master/Dockerfile',
		lineStart: 5,
		lineEnd: 8
	}
]
```

The new MkDocs theme can serve as a spec for other static site generators, thus TechDocs supporting not just MkDocs, but Hugo, Sphinx, Jekyll, etc.

Irrespective of having the spec in JSON, or leaving it in HTML - **TechDocs should not care how docs are built, as long as it can receive some content that it knows how to render.**

![Untitled Diagram](https://user-images.githubusercontent.com/8065913/104134881-ad1fc780-538c-11eb-8516-a5c9e0c06cb4.png)

And once we have this Spec, we could even think about the real-time rendering in TechDocs (without the need of building sites and storing them in storage anywhere). A world where all the docs in Backstage are up-to-date, always. In fact, @hooloovooo in https://github.com/backstage/backstage/pull/3842 created a prototype of real-time documentation rendering as shown in the GIF above. The future is exciting! ✨ 

---

Edit: 11 Jan - Added new problem "Slow page loading and page switching"

**Comment by andrewthauer** [comment]
I really like the thinking behind this 😀.

I can however see it being difficult to maintain a rich set of rendering features while keeping the spec generic. A risk being the solution could end up having to cater to the lowest common denominator being supported. However, given the potential of the proposed solution it might be a worthwhile trade off and figure out ways to mitigate that being an issue.

**Comment by OrkoHunter** [comment]
Thanks! The first step to consume a basic HTML with custom MkDocs theme ("Plan") seems feasible. However, the generic spec ("Future of TechDocs") is indeed, a challenging moon-shot problem as of now. 😄

**Comment by andrewthauer** [comment]
Makes a lot of sense. The first phase will likely need to deal with some of the problem in the form of supporting mkdocs plugins that rely on non standard or uncommon markdown conventions.

**Comment by OrkoHunter** [comment]
Suggestion needed: Would you suggest a good profiler which can record the time it takes to load a TechDocs page and switch pages using the benefits of client side rendering? It should do the action for >100 iterations and on different internet connection speeds to generate a good benchmarking results.

[Lighthouse](https://developers.google.com/web/tools/lighthouse) seems to give a score of the site performance, and that's good. I believe here, we are mostly interested in the time it takes to do the following two events in TechDocs.

Event 1 - Opening a docs site from `/docs` homepage for the first time.
Event 2 - On a TechDocs site, switching from the index page to a sub page.

Let me know if you have any recommendations. I'll explore Lighthouse more.

---

I have some manual profiling results that I can share as of now -

Publisher: Both Local and Google Cloud Storage
TechDocs site: `backstage.io/docs`
Number of runs: 10
In second event, I am switching from Index page to Getting Started.
All data using Chrome dev tools (on a 200 Mbps connection speed)

Event 1 takes roughly between 4 to 6 seconds with local storage and 1.4 to 2 seconds with external storage.
Event 2 takes roughly between 3.5 to 5 seconds with local storage and 1.5 to 2.2 seconds with external storage.

**Comment by iamEAP** [comment]
To zoom out a little bit...  Given the current overall architecture (static site gen -> aggregated storage -> render full pages within Backstage), there are (to my mind) three possible ways to achieve the last step:

1. Embed the statically generated content within Backstage via iframe
2. Inject the statically generated content within Backstage via shadow DOM
3. Inject the statically generated content within the Backstage DOM Directly

And your proposal here is to use the 3rd approach in favor of the second approach.

Naturally, each approach has its advantages and drawbacks, and as you point out, a big advantage of the 3rd approach is tighter integration with the host site (Backstage), including style reuse, component reuse, and other standard webpage things (like analytics, etc).

However one commonality between approaches 1 and 2 is that they both allow us to leverage the mkdocs ecosystem to its fullest.  Out of the box, we make use of mkdocs material theme and its associated sub-extensions. This architecture also allows (although it does not make it easy for) implementors to install and leverage mkdocs extensions of their choice.

If we go with approach 3, we take on the burden of re-implementing and maintaining any functionality we currently rely on from the material theme (which is hard to quantify, but seems large to me), but maybe more importantly, it seems like this change would shut off the ability for TechDocs adopters to use mkdocs extensions that are not provided by TechDocs.

I also wonder if this change would actually eliminate the fragility of interdependencies between generated code and TechDocs Reader code.  With control over the theme, we get rid of the need for many transformations, but would there not still be dependencies between code generated by plugins (that may change version-over-version) and the extra CSS/JS we maintain in the Reader to keep existing functionality?

**Comment by OrkoHunter** [comment]
> Naturally, each approach has its advantages and drawbacks

> If we go with approach 3, we take on the burden of re-implementing and maintaining any functionality we currently rely on from the material theme (which is hard to quantify, but seems large to me), but maybe more importantly, it seems like this change would shut off the ability for TechDocs adopters to use mkdocs extensions that are not provided by TechDocs.

Complete agree. And it is going to be quite a bit of work to support a list of mkdocs extensions that comes out of the box with mkdocs-material theme.

(By the way, we can see the list here in references https://squidfunk.github.io/mkdocs-material/reference/abbreviations, so we know exactly what these features are that we must support before transitioning to the new theme.)

My thinking of TechDocs is that it should be stable and fast enough when it comes to supporting the basic features of a technical documentation site.

There are some things which constitutes the majority of a documentation site - `text, images, code blocks`. (I don't know what percentage "majority" translates to). Then there are some features which make a documentation site look great - `notes, warnings, UML diagrams`. And then there are some features which are mindblowing, but are not critical, are rarely used and have alternative ways of writing them - `Abbreviations`.

TechDocs with the new architecture, must support the basic _and_ what makes a documentation site look great.

So, yes we are left with a choice. In my opinion, we should still try to make a lightweight theme and use Backstage for designing the page. Especially if it makes the reading experiencing great by reducing page load time, etc. We can be explicit and have a list of mkdocs extensions we support. And I feel, that will be "good enough" for a very high number of documentation sites there can be.

**Comment by iamEAP** [comment]
A couple more thoughts:

**On Performance**: If I'm reading the waterfall above correctly, the vast majority of those bars are spent in the green `waiting` state while the blue `download` itself is _extremely_ short, which implies to me optimization on size will help with storage, but not necessarily performance.  I'd be curious to understand where most of that `wait` time is spent in the backend.

FWIW, although I wasn't here at the time, my understanding is that the same performance issue was encountered internally; although inelegant, I believe the performance problems were resolved by 1) eliminating API/network calls to storage by statically caching files to disk, and 2) proxying access to those files using a reverse proxy rather than through node.js.  I would imagine a lot of that `wait` time is spent on similar things, here.

Perhaps one optimization would be for the techdocs backend to stream the file directly from storage through to the client, rather than buffering it all into memory, then sending to the client.

**On Fragility of Generated Docs Code vs. Reader Code**: I wonder if there's a more surgical way to eliminate the fragility than abandoning mkdocs material altogether.

The mkdocs theme is open source, and I have to imagine "embedding a docs site into a parent site" has to be a more common use-case than just Backstage (and obviously the Backstage use-case is growing rapidly too).  Would it be possible to remove some transformation code by making some things configurable (e.g. exclusion of header/footer/nav) at the mkdocs level?  Could other transformers instead be implementable as our own mkdocs plugin as well?  Like a post-processing step.

**Comment by freben** [comment]
I believe one could say that GCS is a known-slow storage mechanism, at least in terms of startup time per item - its potential throughput when taking parallelism into account is astronomical :P

Nearline CDN-like caching may indeed improve things a lot. And I don't expect node to be a bottleneck as such, if we choose to put caching at that level.

**Comment by adrianke77** [comment]
For our team at Grab, we're doing conversion of existing Confluence documentation to Markdown, and this requires a certain amount of CSS to help the html inline in the Markdown after conversion to display correctly. Would like to request some sort of support for insertion of such CSS. Otherwise it would become effectively impossible to display the inline HTML correctly.

**Comment by OrkoHunter** [comment]
Thank you all for sharing your thoughts on the RFC. After many weeks of bouncing ideas and experiments, we have concluded to close the RFC with following notes

- Current approach (display HTML with shadowDOM) vs proposed approach (render content and style it with TechDocs theme) is a difficult trade-off problem. There is a great deal of work needed to make the change, but on other other hand, the known problems have to be solved as well.
- Current priority in TechDocs is to fix the problems highlighted here in the RFC ([Page responsiveness](https://github.com/backstage/backstage/issues/2462), allowing to customize frontend [using Backstage theme](https://backstage.io/docs/getting-started/app-custom-theme) (Material UI) palette, etc.) without moving to a new architecture.
- In future (two or three quarters from now), when [TechDocs widgets framework](https://backstage.io/docs/features/techdocs/techdocs-overview#project-roadmap) work starts, we'll re-evaluate this RFC. It's possible that the proposed architecture will make it easier to implement TechDocs widgets and presence of ShadowDOM may make it harder to do so.
