### ISSUE TITLE
Implement IdentityApi in Bitbucket Server Scaffolder

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4002]
@goober thank you so much for implenting bitbucket server support for scaffolder.

Any thoughts on using IdentityApi to use logged in user's identity while making bitbucket api calls ?
The general problem with using token configured in app-config.yaml for write api calls (e.g. scaffolder) won't work in most cases with security concerns. The user with access to backstage can bypass the security defined in bitbucket server and will be able to create repos without having appropriate permission.

__Originally posted by @kiranpatel11 in https://github.com/backstage/backstage/issues/3526#issuecomment-757625505__

**Comment by benjdlambert** [comment]
So one idea we've had is that the user's token would be used in the client to provide a dropdown of where you're allowed to create repositories, but the actual creation could be done by a separate token entirely.

This is for many reasons, a good one being that user owned repo's are not always great for security, seen as people leave companies, and can be a pain to get them moved ownership. Also passing tokens from the frontend to the backend can also be a little bit of a security hole too.

Open to ideas though! :)

**Comment by regicsolutions** [comment]
I like that approach. Is there a tentative date on when this will be available and is the plan for it to be available for all currently supported integrations? 

Can you label this one with as 'help wanted' please.

**Comment by regicsolutions** [comment]
@benjdlambert just wondering if there has been any progress with introducing the drop down option with identityApi support in the new iteration of the scaffolder ?

**Comment by benjdlambert** [comment]
Hey! So in the release today we're shipping a `repoUrlPicker` component which is rendered part of the `scaffolderv2` work we've been hard working on the past few months. The logic would go in this component I suspect, so I think maybe once it's shipped you could have a play at making something work and shipping a draft PR or opening an RFC on how to do this?

**Comment by kiranpatel11** [comment]
> This is for many reasons, a good one being that user owned repo's are not always great for security, seen as people leave companies, and can be a pain to get them moved ownership. Also passing tokens from the frontend to the backend can also be a little bit of a security hole too.

While the dropdown approach would work for this usecase, but isn't passing user accesstoken from frontend to backend and using it to authorize the api/data access is standard pattern for SPA.

In case of Bitbucket Server, the user still have to have a _admin_ permission at project-level to be allowed to create a new repository (and I guess it is similar for other platforms too). In most cases, user gets that previlleges as part of being a member of project admin group and that way the concerned on user-owned-repo is addressed.

Furthermore, security team is usually NOT in favor of creating a global service-account/robot user that is required to configure for scaffolder plugin which has access to create repositories under any project within organization.

**Comment by freben** [comment]
@Rugvip any opinions on the suitability of using the user's frontend-issued access tokens passed down to the backend for creation of projects on their behalf etc?

**Comment by Rugvip** [comment]
@freben @kiranpatel11 I'd say we want to make it configurable whether user credentials or server credentials are used of the repository creation, as I see both strategies being things that organizations would require. GitHub Apps already makes it a lot cleaner as there's no need for a god mode account, so that's also something we want to replicate.

When it comes to using the user tokens it's a bit tricky as we don't exactly what tokens are needed when triggering the template in the frontend, which is a problem we already hit with the Kubernetes plugin. I would imagine we want to come up with a standard solution for that problem, whether it's some kind of token request scheme to grab them from the frontend, or storing more tokens in the backend.

With the current implementation it's also a bit unfortunate that we'd need to store the tokens as part of the task spec in DB in the scaffolder backend, especially GitHub ones as they don't expire. It's something we may want to find a better solution for than just the simplest implementation.

**Comment by regicsolutions** [comment]
@Rugvip just checking back in on this one to see if there is a clearer direction on how this should or could be accomplished? 

Would the creation of a Bitbucket Server auth provider solve this issue? Bitbucket Server does support OAuth 1.0 with the usage of Application Links and seems like there is a [https://bitbucket.org/atlassianlabs/passport-atlassian-oauth/src/master/](passport-atlassian-oauth) auth strategy that looks promising ...

**Comment by Rugvip** [comment]
@regicsolutions getting a Bitbucket OAuth provider in place certainly is a dependency and would help us on the way. The main thing to be solved is still the authenticated scaffolding, which is on our radar but not priorotized just yet.

**Comment by FilipSwiatczak** [comment]
Hello @Rugvip I've just written Bitbucket OAuth provider  #7308 in case it helps above. Cheers

**Comment by regicsolutions** [comment]
Closing this https://github.com/backstage/backstage/pull/7308
