### ISSUE TITLE
docker compose deployment

### ISSUE THREAD

**Issue by gharsallahmoez** [backstage/backstage#4023]
## Feature Suggestion

I'm looking for docker compose deplyment that contains frontend and backend.

**Comment by dtuite** [comment]
@gharsallahmoez At the moment, there is nothing which will work out of the box for this. There used to be a sample `docker-compose.yaml` file in the `contrib` directory but it seems to be gone.

I have written a blog post tutorial which shows [how to build a Backstage instance and run it with Docker Compose](https://roadie.io/blog/backstage-docker-service-catalog/). Hopefully it is useful.

**Comment by gharsallahmoez** [comment]
@dtuite it works in my local machine, but when I tried to build it on my public server I got a white screen in the browser and this error `net::ERR_SSL_PROTOCOL_ERROR` in the console. did u tried to build backstage on a server? and do u have an idea what goes wrong?

**Comment by gharsallahmoez** [comment]
here is the full console log
```
GET https://myserver.com:7000/static/kyma-project.12.eca6006b.css net::ERR_SSL_PROTOCOL_ERROR
GET https://myserver.com:7000/favicon.ico net::ERR_SSL_PROTOCOL_ERROR
GET https://myserver.com:7000/favicon-32x32.png net::ERR_SSL_PROTOCOL_ERROR
GET https://myserver.com:7000/favicon-16x16.png net::ERR_SSL_PROTOCOL_ERROR
```

**Comment by dtuite** [comment]
@gharsallahmoez the scope of the tutorial is local development only. I wouldn't be surprised if it doesn't work on a server. Unfortunately I have no insight into what is causing the specific errors you are seeing.

**Comment by benjdlambert** [comment]
@gharsallahmoez do you have SSL certificates setup for your server deployment? It looks like you're trying to load `https` when it only listens with http.

**Comment by marcosnils** [comment]
:wave: https://play-with-docker.com author here.  I was looking for a way to test backstage and found that https://demo.backstage.io/ seems to be broken. We've developed a "Try in PWD" button (see example repo here https://github.com/tillias/microservice-catalog) that allows deploying a compose file to demo products. 

@dtuite if you think it's worth I can bring back the `docker-compose.yml` file and add the "Try in PWD" button so users can actually test backstage before setting it up locally. 

WDYT?

**Comment by dtuite** [comment]
@marcosnils Could you be more specific about what is broken with the Backstage demo please? At a glance, it seems to work for me right now. I'm sure it would help the team to know what is broken.

If you show me how to add that button I'm happy to try it out and maybe add it to the blog post mentioned above. I have been maintaining up to date Backstage Docker images: [backend](https://hub.docker.com/repository/docker/roadiehq/roadie-backstage-backend) and [frontend](https://hub.docker.com/repository/docker/roadiehq/roadie-backstage-frontend) which could be used.

Shoot me an email at david@roadie.io

**Comment by marcosnils** [comment]
> Could you be more specific about what is broken with the Backstage demo please?

Sorry for that, the `create component` action returns 404. It'd be awesome if you could create a component from a public github repo and make backstage pick that to play in the demo.

> If you show me how to add that button I'm happy to try it out and maybe add it to the blog post mentioned above. I have been maintaining up to date Backstage Docker images: [backend](https://hub.docker.com/repository/docker/roadiehq/roadie-backstage-backend) and [frontend](https://hub.docker.com/repository/docker/roadiehq/roadie-backstage-frontend) which could be used.

Sure, adding the button is pretty straightforward, you just need to have a public `docker-compose` file that is configured with all the required services and add a link like this one (https://github.com/tillias/microservice-catalog/blame/master/README.md#L14) to send the user to PWD and reference that stack.

**Comment by adamdmharvey** [comment]
Also relates to the existing bug report of the create catalog button looking broken on demo (though it's actually not been installed by design, and the referenced issue being kept open to better explain/error that to the end-users):
https://github.com/backstage/backstage/issues/4085

**Comment by marcosnils** [comment]
> Also relates to the existing bug report of the create catalog button looking broken on demo (though it's actually not been installed by design, and the referenced issue being kept open to better explain/error that to the end-users):

And it makes total sense to avoid polluting the demo environment. Having said that, I believe that a straightforward approach by using a single docker-compose file locally to spin up all the services would be really neat since the docs are recommended docker anyways to start the postgres database. 

If we provide this, then adding something like the "Try in PWD" button so anyone can easily spin-up their demo environment is just trivial

**Comment by marcosnils** [comment]
@adamdmharvey gente ping
