### ISSUE TITLE
Docs: Update K8 docs location

### ISSUE THREAD

**Issue by AlleyWei** [backstage/backstage#4037]
## Expected Behavior

Move the K8 doc to https://backstage.io/docs/features/kubernetes and change title in menu to Kubernetes
## Current Behavior

Currently appears in https://backstage.io/docs/features/software-catalog/kubernetes-in-backstage and is labeled "Kubernetes in Backstage"

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by AlleyWei** [comment]
Can this be updated ASAP? Will need it for the K8 marketing launch

**Comment by OrkoHunter** [comment]
Sure! I can do this

**Comment by AlleyWei** [comment]
Thank you!!!

**Comment by AlleyWei** [comment]
@OrkoHunter can this be moved to above Software catalog? In your screenshot, it shows as the bottom-most section in Core Features, and we'd like to see it as the 1st core feature.

**Comment by OrkoHunter** [comment]
Oh okay 😄
