### ISSUE TITLE
TechDocs: improve scrolling for long documentation

### ISSUE THREAD

**Issue by LeKeve** [backstage/backstage#4043]
## Feature Suggestion

As a user I would like to easily navigate between documentation pages or sections inside of longer documentation. Currently, if I scroll down to the middle of a page or reach the end of a long page I have to scroll all the way back to the top of the page to navigate elsewhere.

## Possible Implementations

- Documentation search
- Fix position of documentation navigation and Table of Contents sidebar
- Add a back to top button

**Comment by OrkoHunter** [comment]
Yes. 💯 I like both 2 and 3 as a fix. Documentation search would search within all the pages of the TechDocs site - it's helpful but maybe not so much as the default browser "Find in page".
