### ISSUE TITLE
TechDocs: degrade on #3990  Binary file is not showed up with awsS3 publisher

### ISSUE THREAD

**Issue by jizg** [backstage/backstage#4051]
I updated to the latest master branch and found the bug fixed by #3991 happened again.
The latest codes went back to stream object to string and response the string to the frontend which resulted the binary file such as png image not displayed.

https://github.com/backstage/backstage/blob/5032aa4bba5b3d3366066b1471f1b27ba3045b65/packages/techdocs-common/src/stages/publish/awsS3.ts#L27-L38

**Comment by OrkoHunter** [comment]
Ooops. I believe we missed to highlight this when reviewing https://github.com/backstage/backstage/pull/3953. cc @ayshiff just for your information.

Apologies, will fix this now.

**Comment by freben** [comment]
@OrkoHunter oh sorry, i eagerly got started on that https://github.com/backstage/backstage/pull/4053

**Comment by OrkoHunter** [comment]
Aah, no worries! 😄
