### ISSUE TITLE
kubernetes: Enhance identification of detail drawer availability

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4068]
## Feature Suggestion

The deployment and pod headings are clickable to bring up the sidebar drawer with more details about the given element, which is awesome.

It would be nice if the UI indicated that in some way to the end user.

| Finding hotspots | Drawer |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/33203301/104552353-aac8a200-5606-11eb-93ba-ecc2963017b8.png) | ![image](https://user-images.githubusercontent.com/33203301/104552525-fe3af000-5606-11eb-97f7-a9af76d337f9.png) |

## Possible Implementation

* Selection of the Material-UI MenuOpen icon next to the text? (`import MenuOpenIcon from '@material-ui/icons/MenuOpen';`)
* Some sort of color indication? Or an outline?

## Context

I only knew the drawers existed by reading the [K8s blog post](https://backstage.io/blog/2021/01/12/new-backstage-feature-kubernetes-for-service-owners), so tried clicking around until I found them. Realized there was no drawer for the cluster, and as clicking just realized it would be nicer to have some visual cue of more info being available.

**Comment by Rugvip** [comment]
Yeah this was debated quite a bit already 😅 

Icon would prolly look something like this:

![image](https://user-images.githubusercontent.com/4984472/104626742-887e6500-5696-11eb-887f-49b03080b675.png)

Not a huge fan tbh.

Internally we have a color indication on hover, but tbh I don't know if that helps in this case? Perhaps static color, but keeping the hover area dimming to distinguish it from a link?

![image](https://user-images.githubusercontent.com/4984472/104627313-2b36e380-5697-11eb-8969-d0215a48a4fd.png)

@katz95, any other ideas? 😅

**Comment by freben** [comment]
I'm definitely also a fan of making them link-like but ideally with a distinguishing factor.

An alternative is to enforce a rule that if it's a sidebar or popup, it must always be triggered by a visual button - not a link. That kind of restriction does put some constraint on the design of the rest of the page though.

**Comment by adamdmharvey** [comment]
I hadn't considered a tool tip, but it might be nice even as an incremental improvement.  Something like, "View more details"?

![image](https://user-images.githubusercontent.com/33203301/104640423-78ef2400-5676-11eb-858b-1f81d1fa32c5.png)

Something a little more visual so a user knows to hover/click for sure, but what do you think?

**Comment by mclarke47** [comment]
@Rugvip and I discussed this when I implemented the UI. We looked at an example of with the icon and without the icon and decided against it.

I would still prefer an icon, but I'll go for anything that makes it more obvious it is clickable tbh.

**Comment by OneCricketeer** [comment]
Personally, I prefer the `ExitToApp` or `Launch` icons, and towards the right side

At the very least, on the left-side of the divider in the "deployment" panel. 

In the table, I think a mouseenter event with a cursor hand and a row-highlight would suffice to indicate something happens there

**Comment by freben** [comment]
I guess we're open to ideas basically :) Maybe it's one of those "anything is better than nothing" situations in just putting some clarifying icon or color or whatnot in there
