### ISSUE TITLE
AzureUrlReader fails to read url for repos that have the same name as project

### ISSUE THREAD

**Issue by mcalus3** [backstage/backstage#4074]
Azure DevOps urls are inconsistent - for repos that have the same name as project two url formats are valid:

- `https://dev.azure.com/<userOrOrg>/_git/<repoName>`
- `https://dev.azure.com/<userOrOrg>/<projectName>/_git/<repoName>`

## Expected Behavior

Url format should be parsed and recognized. Based on it app could:

1. Infer project name from the repository name if the url is in the shorter format,
2. If not preferable, there should at least be a custom error message that says that the url format is wrong and it has to include project name.

## Current Behavior

The first format is appearing to be default when browsing Azure DevOps so users that have same-named repositories will try to paste this url to the catalog-import or register-component plugin and will get error message:

```
Error: Unable to read url, Error: Incorrect URL: https://dev.azure.com/marek-calus/_git/backstage-test?path=%2Fcatalog-info.yaml, Error: Wrong Azure Devops URL or Invalid file path at Module.generalError (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/results.ts:59:56) at UrlReaderProcessor.readLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/UrlReaderProcessor.ts:75:67)
```

## Possible Solution

The error is being thrown here in the code: https://github.com/backstage/backstage/blob/3f7bfe7b1153e2477587669bb8234b98e19b6bd7/packages/integration/src/azure/core.ts#L54 because the url is being split wrongly (based on assumption that the project name is always in the url) and the url format recognizing logic could also be there.

## Steps to Reproduce

You can try it out with these links:
- https://dev.azure.com/marek-calus/_git/backstage-test?path=%2Fcatalog-info.yaml
- https://dev.azure.com/marek-calus/backstage-test/_git/backstage-test?path=%2Fcatalog-info.yaml

## Context

I think there could be some users that evaluate the backstage and will create test projects and repositories with the same name, so this could affect them.

**Comment by PhakornKiong** [comment]
I was tinkering with this for a while and noticed that there is no `Error thrown`

but the console does have a `Catalog warn`
```
catalog warn Detected conflicting entityRef component:default/sample-service already referenced by url:https://dev.azure.com/marek-calus/backstage-test/_git/backstage-test?path=%2Fcatalog-info.yaml and now also url:https://dev.azure.com/marek-calus/_git/backstage-test?path=%2Fcatalog-info.yaml type=plugin
```

UI wise, it does not trigger any error as well, but allows to continue to import.

I think the right behavior might be to show `refresh` instead.
