### ISSUE TITLE
DCO check is missing for the project

### ISSUE THREAD

**Issue by idvoretskyi** [backstage/backstage#4075]
Greetings, project maintainers.

CNCF's IP policy (https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy) requires all projects to use either CLA (Contributor License Agreements) or DCO (Developer Certificate of Origin). Unless there's a strong necessity to use CLA, we encourage projects to use DCO as it's easier to setup and use. Ref.: https://github.com/cncf/foundation/issues/130

During the audit, we've noticed that one or a few repositories of your project doesn't have the DCO check enabled. Please enable the DCO check for all repositories in your GitHub organization. You may find more details here - https://github.com/apps/dco.

Thanks

**Comment by OrkoHunter** [comment]
Ref: DCO being added here https://github.com/backstage/backstage/pull/4513

**Comment by idvoretskyi** [comment]
@OrkoHunter great, thanks!
