### ISSUE TITLE
backend-common: URL Reader should return metadata about HEAD commit

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#4097]
## Feature Suggestion

URL Reader's `readTree` method response should contain metadata about the HEAD commit e.g. timestamp and sha. https://github.com/backstage/backstage/blob/6e382fc4c70e8b9703f15dd554959e0cfa4dcb8d/packages/backend-common/src/reading/types.ts#L42

cc @Rugvip 

## Context

URL Reader is used to download a repository/tree when a location is defined as `url:target` (commonly used in Catalog/TechDocs and to be used at other places). [Here are some docs](https://backstage.io/docs/features/techdocs/how-to-guides#how-to-use-url-reader-in-techdocs-prepare-step) on why it is useful, especially for TechDocs.

With the timestamp, TechDocs can invalidate the cache properly when building the sites. As of now, it just stores the build for 30 minutes.

**Comment by freben** [comment]
So if we make it part of this particular API method instead of a separate one, we should ideally take care to only lazily load the actual data blob, until the user calls `files`, `archive`, or `dir`. Right? Since you may want to check the metadata only, and then not read the data at all, if it hasn't changed.

**Comment by Rugvip** [comment]
@freben That'd cause trouble if we want other parts of the response of the actual tree fetch to be available in the response object, but it would be one way to do it.

Another option would be to be able to supply a hash/etag and get a NotModifiedError thrown. That has the downside of actually executing the fetch if there is a modification, which is some cases might be unnecessary, for example if actual docs fetching and building happens in a separate process. Although tbh I have a feeling this would work well in practice.

We could also add a `readStat`/`readInfo`/`readMeta`-like endpoint, along with possible changes to the `read` method we could end up here:

```ts
type UrlReader = {
  readFile(url: string, options?: ReadTreeOptions): Promise<ReadFileResponse>;
  readTree(url: string, options?: ReadTreeOptions): Promise<ReadTreeResponse>;
  readMeta(url: string, options?: ReadTreeOptions): Promise<ReadResponseResponse>;
};
```

Last option should obviously have a bit more friction as we don't wanna get carried away and bloat the interface.

I'd actually vote for the sha-based approach for now. Thinking that making use of that in techdocs would be a minor refactor in any, and is useful regardless of whether we expand the interface or not.

**Comment by OrkoHunter** [comment]
Adding a sha in the response of `readTree` is surely useful for something like TechDocs since it can store the state of the generated docs for future cache invalidation.

However, since TechDocs frequently tries to check if the docs site has been outdated, it needs some interface to call and get the latest sha of the url's target. If `readTree` is the only way to get the sha, then we are unnecessarily downloading the tree again and again, which is obviously inefficient.

So, I think it makes sense that in addition to adding the sha in the ReadTree Response, URL Reader should also provide a way to get the latest sha without "reading" the files. Either we do it by adding a `readMeta` or lazy loading on `dir()`, `archive()`, or `files()` is up for discussion.

**Comment by Rugvip** [comment]
@OrkoHunter Sure it's not possible to fit in the `NotModifiedError` approach in TechDocs? What's the piece that prohibits that? I'm thinking that approach is preferable as it's the smallest modification that is unlikely to cause issues in the future. Making the `dir()` etc. lazy I think is troublesome for the reason I mentioned above.

**Comment by OrkoHunter** [comment]
Aah, let me try to be verbose here and tell me if this is correct. The `ReadTreeOptions` will have an optional `sha` parameter. The very first time TechDocs calls `reader.readTree(url)`, TechDocs will have no sha to provide to `readTree` for the particular `url`. So, `readTree` will do a full fetch and respond with the blob and the sha, that TechDocs stores. The next time TechDocs calls `reader.readTree(url, { sha })`, the readTree will compare the sha against the url's target and will throw a `NotModifiedError` if the target has not been updated. But if the target has been updated, `readTree` will respond with a new sha and new blob.

I think this makes sense and is a small modification indeed. Unless, I understood it wrong.

**Comment by Rugvip** [comment]
@OrkoHunter Yep, that's it. I'm thinking that in practice there's actually no case where you want to check if there's an update and then not download the tree if there is.

**Comment by OrkoHunter** [comment]
Yep, agreed.

**Comment by freben** [comment]
Where will the sha history be stored? Just in memory (best effort, per host), or in the db, or in the target as a metadata file or whatever?

**Comment by OrkoHunter** [comment]
URL Reader's readTree will always fetch the latest SHA from the source code provider - GitHub/GitLab/etc. So, it won't store SHA anywhere.

TechDocs currently stores the build timestamp in memory. So, the first step will be for TechDocs to store the SHA in memory as well and use it for calls to readTree. But I guess an improvement will be to support multiple Backstage instances? But if local filesystem is being used in TechDocs to store the built files in a Backstage instance, then perhaps it makes sense to have each instance store its own SHA or build timestamps.

(Just thinking out loud, and why it makes sense to not build docs on Backstage instance and use CI/CD + External storage for the setup).

**Comment by freben** [comment]
Sure, which is why it sounds like it might be part of the storage handler to keep track of the last hash. Some may just have it in memory, some may have it centrally stored.
