### ISSUE TITLE
Allow customisation of default catalog filter

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#4099]
## Feature Suggestion

Currently, when the user logs in to backstage, they get the page of their owned components. This is hardcoded into the `CatalogPage` component code. The feature request is to make this configurable/customisable.

## Possible Implementation

Concretely that would depend on the work in https://github.com/backstage/backstage/issues/3274 to update the filtering system as a whole, but basically you could support a configuration option in app-config.yaml like

```yaml
catalog:
  defaultFilter: all
```

Or I guess you could provide a way to bootstrap this data in application code.

```tsx
// packages/app/App.tsx
const App = () => (
  <AppProvider>
    <AppRouter>
      <SidebarPage>
        <AppSidebar />
        <Routes>
          <Navigate key="/" to="/catalog" />
          <Route
            path="/catalog/*"
            element={<CatalogRouter defaultFilter="all" EntityPage={EntityPage} />}
          />
          // ...
        </Routes>
      </SidebarPage>
    </AppRouter>
  </AppProvider>
);

```

## Context

Currently, the out-of-the-box behaviour results in the default screen showing nothing when the user has done the bare minimum to get started (ie, has not linked it up to a corporate auth backend). It is at least arguable that it would be more useful to show everything than nothing in this case.

Of course, once you _do_ have auth and identity set up, it is likely more useful to just see your own stuff. However, until we have support for transitive ownership filtering via groups (#4089) this screen is not going to be terribly useful in organisations with a culture of team rather than individual ownership of components.

**Comment by Rugvip** [comment]
Yep, think it would be best to add this as a prop! Should add it to the new CatalogIndexPage as well.

**Comment by benjdlambert** [comment]
Hey @tragiclifestories! Is this something you would like to work on?

**Comment by tragiclifestories** [comment]
I'll give it a go if I get a couple of hours.

**Comment by geototti21** [comment]
👋 hey team, any progress with that? We need this feature as well 😄

**Comment by freben** [comment]
@geototti21 We haven't heard back on this one. Would you like to take a stab?

**Comment by tragiclifestories** [comment]
Hello, yes, sorry! We have a list of things to upstream but no immediate plans so if someone else wants to take a crack at it then that is certainly fine by me.

**Comment by andrewthauer** [comment]
This seems somewhat related to #2791. Which I'm still hoping to get some early feedback on :)

**Comment by geototti21** [comment]
Hey, happy to take a stab, I assume all it needs is an optional prop like this:
```js
 <Route path="/catalog" element={<CatalogIndexPage defaultSelectFilter="all" />} />
```
Is this okay @freben and is it compatible with your proposal @andrewthauer ? :)

**Comment by andrewthauer** [comment]
@geototti21 - My PR is looking at refactoring a lot of the underlying filter logic and structure around the index page in general. It's built out as a parallel set of pages so you could take a shot at implementing this in the existing pages.

NOTE: You may run into some friction depending on what your trying to filter on though. For instance, the current structure of the existing index page is based around tabs based on `spec.type` for `Component` kinds. If your trying to show all kinds for instance this may not be trivial without a lot of changes. You might also be interested in #4852 or also using the `search` plugin in the interim.

**Comment by geototti21** [comment]
Thanks for explaining @andrewthauer 🙌 , I think something like replacing the hardcoded `owned` in the [CatalogPage](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogPage/CatalogPage.tsx#L200) with the prop value will do the trick for now, I will try to PR it tomorrow :)

**Comment by andrewthauer** [comment]
I think I skimmed over the full description and just looked at the title as it's somewhat generalized. Your specific case of making the default selection different then `owned` should probably be possibly without too many changes.

**Comment by geototti21** [comment]
PR ready to be reviewed https://github.com/backstage/backstage/pull/4885 :)

**Comment by awanlin** [comment]
This is an awesome addition! I've tried using this via `app-config.yaml` configuration but that doesn't seem to work, looking over the code I don't think that was implemented. Is that still in the plans? With this being closed I have a feeling it's not 😞

**Comment by heatheralee** [comment]
> This is an awesome addition! I've tried using this via `app-config.yaml` configuration but that doesn't seem to work, looking over the code I don't think that was implemented. Is that still in the plans? With this being closed I have a feeling it's not 😞

Hi @awanlin -- not sure if this is still an issue for you, but the way to set the initially selected filter is by going into your `App.tsx` file and updating the component `<CatalogIndexPage />` to contain a new prop `<CatalogIndexPage initiallySelectedFilter="all" />`
