### ISSUE TITLE
Backstage dev experience on simple plugin addition

### ISSUE THREAD

**Issue by jmfrancois** [backstage/backstage#4101]
The dev experience is really important to build a strong community.
I just have started to play with backstage and take this ticket as a discussion around backstage dev experience.

Just installing a plugin can become a nightmare even for developpers.

## Expected Behavior

Having clear message / doc / tooling to help installing existing plugins on the repository

## Current Behavior

While installing the **catalog-import** on a almost fresh instance (only one week) I have a broken Tile.
As a JS Developer, very easy I popup the devtool.

The console has the following error:

Uncaught Error: No implementation available for apiRef{plugin.catalog.service}

```  at useApi (index.esm.js?420c:57)
    at RegisterComponentForm (index.esm.js?84e3:234)
```

So not afraid I decide to dive into backstage code: 

useApi comes from `packages/core-api/src/apis/system/ApiProvider`
In there you have APIProvider (React Context) + useAPI hook API.
The context is well resolved.

APIProvider receive the following:
* parentholder undefined (provider cascade
* holder 

holder is composed of apis and factories (at this stage I have understood you want to have lazy instatiation)

<img width="1275" alt="Screen Shot 2021-01-15 at 14 13 41" src="https://user-images.githubusercontent.com/19857479/104731390-e7e28080-573b-11eb-9b27-fc14ad896d23.png">

<img width="1293" alt="Screen Shot 2021-01-15 at 14 13 44" src="https://user-images.githubusercontent.com/19857479/104731385-e618bd00-573b-11eb-8bbf-655296ecd8e2.png">

The factory 20 is our `plugin.catalog.service` API factory.
Weird, why it do not succeed to instanciate it ?

So now let s take a look at the APIResolver:

```
const factory = this.factories.get(ref);
```

This line return undefined with apiRef{plugin.catalog.service};
But when we look into the factories which is a Map we have it.

So it seems it is a reference issues in the factories Map: Making the catalog plugin APIRef global so we can check that:

<img width="1154" alt="Screen Shot 2021-01-15 at 14 42 07" src="https://user-images.githubusercontent.com/19857479/104734053-f16de780-573f-11eb-9ea4-9a48cd5bf4c3.png">

So yes ref != catalogAPIRef and because it is a Map I have to find how this factories Map is built

validateFactoris is OK !

Now lets compare the useAPI(ref with the recorded one)

The CatalogImport component use the following import:
```javascript
import { catalogApiRef } from '@backstage/plugin-catalog';
```

So I bet there are multiple versions of the plugin installed

Found !!!! 🍾 
```
$ yarn list --pattern catalog
yarn list v1.22.10
├─ @backstage/catalog-client@0.3.4
├─ @backstage/catalog-model@0.6.0
├─ @backstage/plugin-catalog-backend@0.5.2
├─ @backstage/plugin-catalog-import@0.3.4
│  ├─ @backstage/catalog-model@0.6.1
│  └─ @backstage/plugin-catalog@0.2.11
└─ @backstage/plugin-catalog@0.2.10
✨  Done in 1.22s.
```
## Possible Solution

the backstage/cli should detect duplicate of modules and should warn about it.
It is valid in JS but when API keys are the objects the tooling should help you.

## Your Environment

- NodeJS Version (v14): v14
- Operating System and Version (e.g. Ubuntu 14.04): Mac
- Browser Information:

**Comment by Rugvip** [comment]
Agreed! I think adding a check to `yarn start` that at least prints a warning would be good, since this is a common issue.

There's already a `backstage-cli versions:check` command that will tell you that this issue exists, and you can also add a `--fix` flag to it to attempt to automatically fix the issue. That's not the first place you check when you hit this problem though.

In general there's ongoing work to smooth out the process of installing new plugins in the app. Especially the recent additions described here are working towards that: https://backstage.io/docs/plugins/composability

Let's repurpose this issue for the task of adding the check to `yarn start`, using the existing logic in the CLI that powers `versions:check`. The command in questions is `app:serve`, and I think the best thing would be to print a warning banner in yellow along with instructions for how to fix the issue, i.e. running `yarn backstage-cli versions:check --fix`

**Comment by LeKeve** [comment]
@Rugvip For what it's worth, I ran into this exact issue as well and running `yarn backstage-cli versions:check --fix` did not automatically fix the issue. It did however point to a missing range of versions for the duplicate module which did help.

Opened a PR to add a check in the `yarn start` command.

**Comment by jmfrancois** [comment]
Here is what I did to keep my setup in good shape against a release of backstage

https://gist.github.com/jmfrancois/6d0de8152fb0274858b1d36684c4ec21
