### ISSUE TITLE
[TechDocs HomePage] Support Button

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#4102]
This is a sub-issue out of #2028. 

On the TechDocs HomePage, a Support Button should exist with the possibility for a Backstage integrator to insert information to the team responsible for TechDocs within the organization.

<img width="542" alt="Screen Shot 2021-01-15 at 3 20 56 PM" src="https://user-images.githubusercontent.com/25153114/104738055-524bee80-5745-11eb-9306-3dd9f52925e1.png">

**Comment by adamdmharvey** [comment]
A UX query to the experts if I may.

"Support" could be for an integrator, but might be interpreted from the reader as to the content/quality of the docs themselves.  

So either...

1. **Support with Two Methods**:  support button could have two pieces of info in it, a) where to submit fixes for the docs, i.e. edit in the repo, and b) where to get integrator support for TechDocs.

2. **Edit + Support**: perhaps a separate "edit" button next to support that links to the GIt provider's edit link for the repo?

**Comment by emmaindal** [comment]
> A UX query to the experts if I may.
> 
> 
> 
> "Support" could be for an integrator, but might be interpreted from the reader as to the content/quality of the docs themselves.  
> 
> 
> 
> So either...
> 
> 
> 
> 1. **Support with Two Methods**:  support button could have two pieces of info in it, a) where to submit fixes for the docs, i.e. edit in the repo, and b) where to get integrator support for TechDocs.
> 
> 
> 
> 2. **Edit + Support**: perhaps a separate "edit" button next to support that links to the GIt provider's edit link for the repo?
> 
> 

Thanks for your comment. Just to clarify. This should not be displayed on a TechDocs site but the TechDocs Homepage. So /docs. And it should include a support channel to the "team" who are responsible for the TechDocs plugin within an organization.

For support/edit individual TechDocs sites/pages, we will use other components. As you mention an edit button etc! :)
