### ISSUE TITLE
[TechDocs HomePage] Create Docs Component Button

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#4104]
This is a sub-issue out of #2028.

On the TechDocs HomePage, a "Create Docs Component" Button should exist that takes a user to the default docs-template (/create/docs-template) or let a Backstage integrator decide where the button should take the user. 

<img width="493" alt="Screen Shot 2021-01-15 at 3 21 38 PM" src="https://user-images.githubusercontent.com/25153114/104738311-a656d300-5745-11eb-87d4-4ea2739e94a8.png">

**Comment by Anshultilondiya** [comment]
@emkidwell Could you assign me this issue, right now I have college exams but I will contribute to this in a few days after the end of my exams

**Comment by OrkoHunter** [comment]
Sure, done! :D

**Comment by Anshultilondiya** [comment]
I have fixed the URL, but can you explain what that latter part of the description means so I could contribute to that too if required

**Comment by adamdmharvey** [comment]
Based on the discussions in the sample PR, I might suggest implementing this be broken up into two:

* [ ] Add a create docs button to the docs homepage which just takes the user to create components (whether or not it shows only docs)
* [ ] Design and figure out a way to identify "the docs template(s)" for a given instance and link directly to the setup page for that given template

One might be easier done than the other, and an incremental improvement towards @emmaindal 's outcome?

**Comment by Anshultilondiya** [comment]
@OrkoHunter @emmaindal Will backstage be there in GSoC'21 ?

I'm trying for GSoC'21, could you please confirm ?

**Comment by OrkoHunter** [comment]
Good luck @Anshultilondiya with GSoC and thanks for showing interest! Backstage has not applied as a GSoC '21 organization.

**Comment by Anshultilondiya** [comment]
Well I liked the project, I'm thinking to contribute as soon as I get better understanding, the demo video was really helpful in encouraging my interest in backstage 😅

**Comment by ajpatterson7** [comment]
Hi, reviving this a bit, I may be able to contribute here. What I have right now is simply duplicating the logic that the catalog page uses to produce this button, and applying a `?filters[type][0]=documentation` to the end of the link. This is pretty brittle and not really extensible in the way one might like, given "Link to set of templates" seems like it would be commonly used.

I'd propose an additional property on the route refs to indicate query parameters. This would allow integrators full control over what the docs button links to while having the ability to provide a sane default. If this already exists in the routing system, let me know :)
