### ISSUE TITLE
Lighthouse Card not hidden when annotation removed from catalog entity

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4110]
## Expected Behavior

When removing a Lighthouse annotation from a catalog entity, that entity is no longer registered with lighthouse.

## Current Behavior

My component had a test annotation of:
```yaml
annotations:
  lighthouse.com/website-url: https://spotify.com
```

Note I did not actually run spotify.com through my Lighthouse instance, so it's NOT in the Lighthouse database. I ended up removing that annotation from `catalog-info.yaml`.  I waited for the refresh, but also forcibly re-registered the component. But now every time I visit the overview page, the Lighthouse card displays (which it now should not) and it also errors out with:

![image](https://user-images.githubusercontent.com/33203301/104758606-aeeedf80-572c-11eb-816f-2753b02c36cb.png)

Because I never actually ran an audit for that site.  But I believe the error msg is just an effect of the root cause being my component still thinks it has a Lighthouse annotation (when it doesn't).

## Possible Solution

...

## Steps to Reproduce

1. Install Lighthouse plugin
2. Add a Lighthouse annotation to a component pointing to any fake web site (no need to actually run an audit against it!)
3. Remove the Lighthouse annotation
4. See that Lighthouse card is still visible on the entity

I have a feeling the edge case here is an audit website (annotation value) that never exists, maybe somehow doesn't let it get unregistered full??

## Context

I just added this annotation as a test, but seems now I can't remove it. I wondered if maybe I needed a hook to remove it from the plugin, however in this instance it must be the entity itself which believes the annotation still exists in the catalog, otherwise the card would never even TRY to loop. So I wonder if all annotations are somehow not cleaned up or orphaned in some way?

I've tried with other ones which DID exist with an audit, and they DO seem to remove. I'm still working out edge cases, but opening in case others saw similar or know any related issues.

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL2 Ubuntu 18.04
- Browser Information: Microsoft Edge

**Comment by adamdmharvey** [comment]
* Whenever I remove the lighthouse annotation from my component, whether or not I let the all locations catalog refresh trigger, or create new (to forcibly reload the catalog-info.yaml), the card won't disappear.
* After ensuring the annotation was removed....
  * If I restart the backend only, and refresh the browser, it's still there.
  * If I restart the front end, it's still there.
  * Through all this, confirmed it's not in the `catalog-info.yaml` for my component.

**Comment by freben** [comment]
I think I know what is going on here. There's a mechanism for merging annotations, stolen from a k8s behavior, and I think we need to disable it. It probably makes it effectively impossible to remove annotations.

Here's the line that does the updating. https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/catalog/DatabaseEntitiesCatalog.ts#L371

It ultimately calls this code. https://github.com/backstage/backstage/blob/b2b9595ad4f70c10d09a8451fad89b7e5e98bc2c/packages/catalog-model/src/entity/util.ts#L110

This should just be deleted. We re-calculate the annotations over and over again anyway.

**Comment by freben** [comment]
I'll try to address that asap

**Comment by freben** [comment]
PR is up

**Comment by adamdmharvey** [comment]
Fix works like a charm, @freben thanks! Adding annotation, refresh picked it up. Removing annotation, refresh hid the card. Thanks for quick fix!! 🎉
