### ISSUE TITLE
Linking in local Backstage packages

### ISSUE THREAD

**Issue by LARGH** [backstage/backstage#4115]
I have created my backstage app. So, I need to work on @backstage/core package located in another folder.
by following this instructions (https://backstage.io/docs/getting-started/create-an-app#linking-in-local-backstage-packages), it is installed successfully. 

## Expected Behavior

With this in place you I now modify the @backstage/core package within the main repo, and have those changes be reflected and tested in my app. Simply run your app using yarn start as normal.

## Current Behavior

It is installed @backstage/core from registry npm, but the local backstage package components are not installed instead.

## Steps to Reproduce

1. Add path to workspace files **package.json** and **lerna.json** 
```
"workspaces": {
    "packages": [
      "packages/*",
      "plugins/*",
      "../backstage/packages/core"  // -> new path added
    ]
  },
```
2. Install command:
```
yarn install
```
Also, I deleted the root **node_modules** and reinstall as additional step.

## Context

I am trying to get custom componets for my custom application.

On the other hand, if I run the command:
```
yarn tsc
```
I get stack trace error log: 

```
Type 'import("/backstage-sample/sample/node_modules/@backstage/theme/dist/index").BackstageTheme' is not assignable to type 'import("/backstage/packages/theme/src/types").BackstageTheme'.
...
packages/app/src/sidebar.tsx:29:18 - error TS2322: Type 'OverridableComponent<SvgIconTypeMap<{}, "svg">>' is not assignable to type 'ComponentType<OverrideProps<SvgIconTypeMap<{}, "svg">, "svg">>'.
  Type 'OverridableComponent<SvgIconTypeMap<{}, "svg">>' is not assignable to type 'FunctionComponent<OverrideProps<SvgIconTypeMap<{}, "svg">, "svg">>'.
    Types of parameters 'props' and 'props' are incompatible.
```

I need help to solve this issue. Any solution?

## Your Environment

- NodeJS Version (v14): v14
- Operating System and Version (e.g. Ubuntu 14.04): MacOS 10.15.7
- Browser Information: Safari, Chrome, (it is not important)

**Comment by OrkoHunter** [comment]
Hey! This issue does not seem to be related to the [TechDocs feature](https://backstage.io/docs/features/techdocs/techdocs-overview), hence I'd update the title. :)

**Comment by Rugvip** [comment]
@LARGH Does `yarn start` work as expected?

Tbh I don't think we can guarantee that types work smoothly since the linked packages will use the types from that repo, which means any dependency versions between the two projects have to match. A workaround that did work for me was to copy the `yarn.lock` from the linked in project to the app and running `yarn install`, in this case copying `backstage/yarn.lock` to `sample/yarn.lock`. This is quite intrusive to an existing project and may cause breakages in other places though, so not a silver bullet.

One thing I did notice when messing around with this a bit is that incremental types don't work correctly. Changes in the linked in packages won't be reflected unless the type cache in `dist-types` is cleaned. A workaround for this is to add `"incremental": false` in the compiler options in `tsconfig.json`, gonna add that to docs too.

**Comment by ZLTECTEMAWEB20** [comment]
Curiously, when I execute `yarn start`, the project builds successfully but the core components are from registry.

So that you said, I should test to change `"incremental": false` or I should wait to the #4116 pull request?

**Comment by LARGH** [comment]
Curiously, when I execute `yarn start`, the project builds successfully but the core components are from registry.

So that you said, Should I should test to change `"incremental": false`? or Should I wait to the #4116 pull request?
Or, Is there another way to modify core components?

Do you think if it is better to create my own components library based on the core components package?

**Comment by Rugvip** [comment]
@LARGH Updated https://backstage.io/docs/getting-started/create-an-app#linking-in-local-backstage-packages with my comments from above. The main thing you'd need to do if you want type checking to work is to sync up dependency versions.

Regarding modifying core components, the best way is to do it in the main repo and then sending a PR, perhaps opening an issue with ideas before that. We may eventually allow components to be overridden in the app as well, but no concrete plans for that yet. For creating your own components you'd just put them in plugins, or in a separate package in your app monorepo.
