### ISSUE TITLE
scaffolder url integration ignores the specified branch

### ISSUE THREAD

**Issue by n2ygk** [backstage/backstage#4118]
Scaffolder ignores the **non-default** branch specified in the URL 

## Expected Behavior

url integration should get the URL ref's branch, not the default.

## Current Behavior

the default branch is cloned

## Possible Solution

Make this call to git clone include the `parsedGitLocation.ref`: 
https://github.com/backstage/backstage/blob/57460cda021bddaf04e7c3351c3881a3f24859b0/plugins/scaffolder-backend/src/scaffolder/stages/prepare/github.ts#L68-L71

Workaround: make sure the URL ref is to the default branch.

## Steps to Reproduce

1. create a (private) repo in github that has more than one branch.
2. make sure the non-default branch *lacks* the directory referenced in the templater url.
2. specify a url in that repo that references the non-default branch.
3. select create a component in the UI
4. Step 1: prepare the skeleton will succeed.
5. cd into the cloned tmp directory and do a `git branch` and see that the default branch is the only one present.
5. Step 2: fails with ENOENT when attempting to write to `cookiecutter.json` because the directory is not in the cloned repo.

## Context

I was testing writing my own templater in a non-default branch of my repo.

## Your Environment

- NodeJS Version (v12): v12.20.0
- @backstage/plugin-scaffolder-backend: "^0.4.1"

**Comment by benjdlambert** [comment]
OK so I think we have to pass in the `ref` to the clone command. Sounds like a sensible solution.

Do you want to have a stab at contributing this fix @n2ygk?

**Comment by n2ygk** [comment]
@benjdlambert I've started working on this and will submit a draft PR shortly. I'm "underskilled" in typescript/javascript so bear with me ;-)

**Comment by benjdlambert** [comment]
@n2ygk perfect! No probs at all! Love the contributions!
