### ISSUE TITLE
TechDocs: Change metadata fields to camel case

### ISSUE THREAD

**Issue by mateiidavid** [backstage/backstage#4119]
## Context

#3716 suggested to add an explicit type to handle TechDocs metadata. These changes have been introduced in #3968. 

Based on the PR feedback ([1](https://github.com/backstage/backstage/pull/3968#pullrequestreview-564403983)), ([2](https://github.com/backstage/backstage/pull/3968#issuecomment-757202924)) a further improvement could be made to the field names; more specifically to change them from snake_case to camelCase.

The advantage here is stylistic. Changing these fields would promote consistency across the codebase and adhere to JS naming standards. At first I thought I could make these changes as part of #3968 but I think this would have added quite a bit of work and would have stalled the review process. It would be great to have it done now as a follow-up.

## Possible Implementation

I haven't looked much at possible implementations but I have snooped around the TechDocs codebase in the past week.  I can think of two approaches to this.

1.  Based on @OrkoHunter's helpful comment: 
> The site_name inside mkdocs.yml has to be snake case because of mkdocs. However, we do have a choice to change them in techdocs_metadata.json file. I'm 50/50 about this.

We can change the mkdocs techdocs script to add the fields as camelCase to `techdocs_metadata.json` -- this would happen [here](https://github.com/backstage/mkdocs-techdocs-core/blob/main/src/core.py#L38). We can then go through `techdocs-common`, `techdocs`, `techdocs-backend` and change all occurrences of the fields to their camelCase counterpart. I don't expect there to be (many) changes to the publishers and any of the parsing logic, but I also haven't checked very thoroughly.

2. Without any changes to `mkdocs-techdocs-core` we can change the publishers and add a bit more logic to each when we parse `techdocs_metadata`. Off the top of my head something like this should work for all three of them:
e.g  in `stages/publisher/local.ts`
```JS
fetchTechDocsMetadata():
...
fetch(metadataURL)
          .then(response =>
            response
              .json()
              .then(resp => {
               const techdocsMetadata = {
                     siteName: resp.site_name,
                     siteDescription: resp.site_description,
               } 
               resolve(techdocsMetadata))
}
```

Both of these would do the trick, it's likely I'm missing something and I get a hunch tests will have to be changed either way :). In terms of trade-offs I think something like option 1 would be a bit cleaner since there won't have to be any explanations in the future when a new publisher is added (or a publisher is changed); less rules and constraints to keep track off and less chance for errors. The downside of it is that it will require two PRs, I am also not sure what the community guidelines are or what the rules of thumb are when dealing with the `mkdocs-techdocs-core` repo (if there are any).

I'm more than happy to look into this myself.

@OrkoHunter @adamdmharvey tagging you both here as you've given me the feedback to begin with. Lmk what you think!

**Comment by OrkoHunter** [comment]
Hey @mateiidavid, I like option 2 over 1. All the publishers can use a single helper function which maps the snake_cake `techdocs_metadata.json` values to camelCase TechDocsMetadata instance.
