### ISSUE TITLE
backstage-cli: lint command should lint a package/plugin's dependencies with custom rules

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#4125]
## Feature Suggestion

When `backstage-cli lint` is run in a package or plugin, it should take a look at the dependencies and throw warnings/errors based on some rules.

1. If you are importing packages which should not be imported, the backstage instance should log a warning. (e.g. @backstage/core should also not be imported [docs](https://backstage.io/docs/tutorials/migrating-away-from-core)).
2. Frontend packages should not be imported in backend packages/plugins and vice versa. (e.g. there are two separate Discovery APIs in separate packages for frontend/backend)

(Future scope)
3. (?) Suggestions on some packages and their dependencies based on ADRs. For example, using `luxon` over any other date time library. https://github.com/backstage/backstage/issues/3401

## Possible Implementation

Challenging but depends on each rule. Having a "Disallowed list" of dependencies is one way to do (1).

## Context

Discussion https://github.com/backstage/backstage/pull/4069#issuecomment-760038965

**Comment by TejasQ** [comment]
I shall create an ESLint plugin for backstage since we'll have more needs arise eventually. Already started. Here's what I have so far:

![image](https://user-images.githubusercontent.com/9947422/118853655-454a3200-b8d4-11eb-8895-1395e4d3583d.png)

**Comment by Rugvip** [comment]
@TejasQ Tbh the core/core-api import rule isn't too necessary as they're both likely to be deprecated and replaced soon. The frontend/backend rule is interesting though, although first step is to figure out how we want to be identifying them in the first place :grin:

**Comment by TejasQ** [comment]
> Tbh the core/core-api import rule isn't too necessary as they're both likely to be deprecated and replaced soon.

Oh, lol I wish I knew this earlier. I will try to ask before I tackle issues in the future.

About the frontend/backend rule – is it documented somewhere which packages/plugins are frontend and which are backend?

**Comment by Rugvip** [comment]
@TejasQ There's nothing that definitely tells you if it's a frontend or backend package. As mentioned on slack it's possible to check the extension of the `publishConfig.main` and `publishConfig.module` field in `package.json`, but that's not a completely reliable check either as it may change with custom build setups etc. It's probably best check we have for now though, and since the lint rule is easy to disable for cases where it doesn't fit I'm thinking it would be a good addition.

**Comment by freben** [comment]
Noting that we now have backstage roles in package.json - this work should be easier now.
