### ISSUE TITLE
Modify GithubIntegrationConfig injection to be set up on client instantiation

### ISSUE THREAD

**Issue by Xantier** [backstage/backstage#4127]
_Originally posted by @Rugvip in https://github.com/backstage/backstage/pull/4059#discussion_r558343168_

Move configuration of GithubIntegrationConfig to be set up properly for Octokit during instantiation of clients that are using it so we don't pass it around unnecessarily. See wrong usage in `plugins/catalog-import/src/util/useGithubRepos.ts` and replace with pattern mentioned in: https://github.com/backstage/backstage/issues/4127#issuecomment-762251095

See referenced issue/PR comments for more information.

**Comment by Rugvip** [comment]
Not quite sure what you mean by "during instantiation", what do you have in mind? :grin:

**Comment by Xantier** [comment]
Oh, that's mostly just fancy wordplay from your comment on the linked PR: `Better pass in the config when constructing the instance of this client and keep it as internal state`.

Reading it back now it looks to be missing some words which could make it clearer. Ideally we would want 
1. Get rid of the dependency `@backstage/integration`
2. Remove the need to pass around config items since they should be already configure within the client "during instantiation" ;)

In reality this will likely lead to a some kind of a wrapper around Octokit in this specific case. I'm assuming, if I understood the discussion in https://github.com/backstage/backstage/pull/3613#issuecomment-7408929430 correctly.

**Comment by Rugvip** [comment]
We're not looking to get rid of the `@backstage/integration` dep though, at least not at this point. You'll want to use that to construct the configs we're using to do the lookups

**Comment by Rugvip** [comment]
A good example of how to structure it is here: https://github.com/backstage/backstage/blob/8250ffb443443250762d7127ed9c32804245ab27/plugins/pagerduty/src/api/client.ts#L37, along with instantiation here: https://github.com/backstage/backstage/blob/8250ffb443443250762d7127ed9c32804245ab27/plugins/pagerduty/src/plugin.ts#L37

**Comment by Xantier** [comment]
> We're not looking to get rid of the `@backstage/integration` dep though, at least not at this point. You'll want to use that to construct the configs we're using to do the lookups

I might have misunderstood the comment you made in the MR here: https://github.com/backstage/backstage/pull/3613/files#r538709302. I'll modify the issue to match that and address only instantiation of the client then.
