### ISSUE TITLE
Scaffolder frontend : ability to customize the steps in JsonForm

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#4137]
As of now scaffolder UI has hardcoded 2 steps. First steps allows to capture all template properties from user.
We can certainly use `object` property type to organize capturing the information in different sections, but wizard using multiple steps to organize the info would be much better UX, instead of scrolling thru long form. 

## Feature Suggestion
Allow using customization of scaffolder form steps using JsonForm uischema.

## Context
The scaffolding of a real-world component, api, etc requires to capture lot more inputs from users, things like org-unit, domain, in some cases CI/CD related options, observability and/or cloud tenancy etc. 
To organize capturing these information it is useful to take users through the wizard with the ability to skip some sections. 
This requires to allow customizing scaffolder template form using jsonform schema/uischema.

**Comment by benjdlambert** [comment]
Hey - yep this is a limitation right now and I understand what you mean about the long forms. We have a similar problem with the one that we provide right now with the https://github.com/spotify/cookiecutter-golang template that we ship as demo data.

We're looking at updating the schema for the scaffolder part of the v2 work in this ticket #3745, and whilst I can't commit to doing this work part of that ticket, it's definitely something we will bare in mind for that work and maybe introduce after that work is completed.
