### ISSUE TITLE
[TechDocs] AWS Publisher Docs Router should stream assets through to client

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#4141]
## Suggestion

Rather than reading/buffering asset contents into memory and sending them once fully read, we should stream file contents through from AWS S3 to the client.

## Possible Implementation

In the [AWS S3 Publisher](https://github.com/backstage/backstage/blob/371f67e/packages/techdocs-common/src/stages/publish/awsS3.ts#L201), Pipe the readable stream from AWS onto `res`, which is a writeable stream to the client. Take care to pass headers and status codes as they are passed now.  See [the GCS change](https://github.com/backstage/backstage/pull/4109) for inspiration.

## Context

The goal of this change is to improve memory usage and efficiency when serving TechDocs sites from AWS S3.

This is a follow-up to #4109, which implemented the same suggestion for Google Cloud Storage.

**Comment by ParthS007** [comment]
Hi @OrkoHunter I want to work on this issue. Can you please assign it to me. Thanks :)

**Comment by OrkoHunter** [comment]
Sure!

**Comment by OrkoHunter** [comment]
This was done in https://github.com/backstage/backstage/pull/4434/files#diff-c6eb397b95095a19c7ffdd8b1422ae6b00f31b80dffe957a224ad24fd38c6e98R187
