### ISSUE TITLE
TechDocs: Use p-limit to limit number of concurrent file upload processes

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#4143]
## Feature Suggestion

In [Google Cloud Storage](https://github.com/backstage/backstage/blob/e1e4d4a88e2d128de0113fc554ac47404ae30c74/packages/techdocs-common/src/stages/publish/googleStorage.ts#L112-L120) publisher and [AWS](https://github.com/backstage/backstage/blob/e1e4d4a88e2d128de0113fc554ac47404ae30c74/packages/techdocs-common/src/stages/publish/awsS3.ts#L151-L153) publisher of TechDocs, we should limit the number of concurrent file upload processes being created. The current implementation would upload spawn any number of processes for large projects with thousands of files.

## Possible Implementation

Use the [p-limit](https://github.com/sindresorhus/p-limit) library and limit max processes to 10.

## Context

TechDocs documentation - https://backstage.io/docs/features/techdocs
Feel free to ask any questions.

**Comment by mateiidavid** [comment]
👋 I'll take this on

**Comment by OrkoHunter** [comment]
🚀
