### ISSUE TITLE
Spelling mistake: Fullcreen instead of Fullscreen

### ISSUE THREAD

**Issue by Anoyomouse** [backstage/backstage#4144]
I'm trying to set up an instance of Backstage, and when invoking the Job Stage, the button says "OPEN IN FULLCREEN"

## Expected Behavior

The button should rather say FULLSCREEN

## Current Behavior

currently says FULLCREEN

## Possible Solution

https://github.com/backstage/backstage/blob/060fd0a44a3d14fd1f783755dd6753c36d79f74f/plugins/scaffolder/src/components/JobStage/JobStage.tsx#L164

Quick spelling fix

## Steps to Reproduce

1. Create a new Job
2. Start Job
3. See button with wrong spelling

## Context

Just a small spelling error

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04): Windows
- Browser Information: Chrome

**Comment by OrkoHunter** [comment]
Thanks for reporting!
