### ISSUE TITLE
cli: bump style-loader and mini-css-extract-plugin to latest major versions

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#4149]
## Expected Behavior

Should be able to bump these two without issues

## Current Behavior

Bumping them results in the following error when building:

```
Error: Failed to compile.
chunk kyma-project [initial]
static/module-kyma-project.31d3f200.js
Conflict: Multiple chunks emit assets to the same filename static/module-kyma-project.31d3f200.js (chunks 14 and 14)
```

And when including a content hash in the filename to ensure uniqueness, you get this:

```
Error: Failed to compile.
static/module-kyma-project.1e9dec32.ab58b93b.js from Terser
Unexpected token: punc (.) [webpack://./node_modules/@kyma-project/asyncapi-react/lib/styles/fiori.css:13,0][static/module-kyma-project.1e9dec32.ab58b93b.js:13,0]
```

## Possible Solution

Seems like duplicate assets are emitted, possibly one CSS and one JS one, but not sure exactly what's going on.

## Steps to Reproduce

1. Bump `mini-css-extract-plugin` to `1.3.4` and `style-loader` to `2.0.0`
2. Run `yarn build` in `packages/app`

## Context

https://github.com/backstage/backstage/pull/4139

## Your Environment

- NodeJS Version (v12): v12.16.3
- Operating System and Version (e.g. Ubuntu 14.04): MacOS 10.15.7
- Browser Information: N/A

**Comment by Fox32** [comment]
Looks like the asyncapi-react package is a special snowflake, we already have the workaround for jest in place 🤔 

```
  "jest": {
    "transformModules": [
      "@kyma-project/asyncapi-react"
    ]
  }
```

**Comment by Fox32** [comment]
Looks like they suggest to use the web component version instead if the module format is a problem. Not sure if that works for us: https://github.com/asyncapi/asyncapi-react/issues/177

**Comment by Rugvip** [comment]
@Fox32 it also uses a bunch of node builtins ('http', 'util', etc.) as well, so all up for finding alternatives 😅

**Comment by Fox32** [comment]
We could just use 

```typescript

export const AsyncApiDefinitionWidget = ({ definition }: Props) => {
  const classes = useStyles();
  // lazy import for component
  useEffect(() => import("@asyncapi/web-component/lib/asyncapi-web-component"), []);

  return (
    <div className={classes.root}>
      <asyncapi-component schema={definition} cssImportPath="./asyncapi.css" />
    </div>
  );
};
```

But it runs into missing typing and the question is how we can style that component (right now it expects that the `asyncapi.css` is present somewhere and we also have our custom overrides for the styling 🤔 ).

**Comment by Rugvip** [comment]
Btw, I'm not sure this issue happens to be triggered by the `@kyma-project/asyncapi-react/lib/styles/fiori.css` first and removing it would just lead to some other `.css` import to fail, or if it's actually the only one. Will verify that

**Comment by Rugvip** [comment]
Yep confirmed that this is a general css issue:

```
Error: Failed to compile.
static/module-swagger-ui-react.65f0ed0b.3c640652.js from Terser
Unexpected token: punc (.) [webpack://./node_modules/swagger-ui-react/swagger-ui.css:1,0][static/module-swagger-ui-react.65f0ed0b.3c640652.js:1,0]
```

**Comment by Fox32** [comment]
So you mean it's not directly related to the asyncapi-react module? 👍 Then I would refrain from working with the web component for now.

**Comment by Fox32** [comment]
Just as a reference, maybe for later: https://github.com/backstage/backstage/compare/master...SDA-SE:feat/async-api-web-component

**Comment by Rugvip** [comment]
> So you mean it's not directly related to the asyncapi-react module? 👍 Then I would refrain from working with the web component for now.

Yep!
