### ISSUE TITLE
Run prettier check in CI

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#415]
## Feature Suggestion

We should run prettier checks as a part of CI, and possibly supply a yarn script for running it locally too.

## Possible Implementation

Prettier checks can take a while so would like to separate it out as a command inside each package, so that we can run it with `lerna --since` in CI.

## Context

Getting some PRs without proper code formatting, which will happen as long as we don't enforce prettier checks. Not everyone has prettier installed locally or uses an Editor that supports it.

**Comment by ericis** [comment]
#417 demonstrates an example of this.

*Suggest:*
- [`Prettier`](https://prettier.io/docs/en/) for consistent code styles
- [`husky`](https://github.com/typicode/husky) for Git hooks
- [`pretty-quick`](https://github.com/azz/pretty-quick) for pre-commit code style linting on staged changes

**Comment by ericis** [comment]
Once you have [Husky], you can consider things like [`commitlint`](https://commitlint.js.org/) for enforcing [Conventional Commits](https://www.conventionalcommits.org/). But, that's a separate issue.

**Comment by SrdjanCosicPrica** [comment]
I think you could also add [prettier-eslint](https://github.com/prettier/prettier-eslint) which, in theory, should allow a call to the lerna lint command

`yarn run lint -- -- --fix` 

Instead of calling prettier explicitly

**Comment by sladyn98** [comment]
@ercis We could definitely use an inhouse github action that automatically applies prettier and pushes the changes after a commit on a PR so that users dont have to deal with it
cc @rugvip

**Comment by stefanalund** [comment]
@Rugvip still relevant?

**Comment by Rugvip** [comment]
Yes 😅

**Comment by kingasieminiak** [comment]
@Rugvip Not sure if this is related, but seeing the issues described in [#backstage/pull/730](https://github.com/backstage/backstage/pull/730), you could think of solving [husky/yarn workspace issue](https://github.com/typicode/husky/issues/677).

**Comment by Rugvip** [comment]
@kingasieminiak Haven't had many reports about issues around this lately actually. Gonna close this one tho, as it was fixed in #2295
