### ISSUE TITLE
UX Guidelines for an accordion-style error and warning panels

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4151]
## 🗒 General

In support of #3781, suggest the use of an accordion-style extension to errors/warning panels where summary info can be shared but an expandable panel can be optionally opened where more details (such as a stack trace) are provided.

There have been discussions before that Backstage has an approach of elevating information under the assumption that more info, and the transparency, helps drive up engagement and allows different teams to help engage to improve the system and/or fix errors.

In this regard, detailed error messaging should still comes through the front end. But for newer users, the level of technical details is not particularly friendly and may not be something they are not even interested in seeing.  I equate this to the old-style HTML View Source for front-end devs; you may get an error, but a dev could always view source to see potential hidden errors in comments a la `<!-- error code 43 -->`.

**Folded**
![image](https://user-images.githubusercontent.com/33203301/105080021-3c4c6f80-5a5e-11eb-9bc2-2ea5cbf27f17.png)

**Expanded**
![image](https://user-images.githubusercontent.com/33203301/105080036-44a4aa80-5a5e-11eb-9271-a5c659b82d54.png)

## 💻 Usage

This component would be used whenever an error or warning needs to be displayed to the system.

The accordion is intended to support the multiple end-user views.

In support of the [Backstage Glossary of user profiles](https://backstage.io/docs/glossary#backstage-user-profiles),

* Software Engineer would see the friendly error, such as your card can't be displayed, or your catalog is not available.
  ![image](https://user-images.githubusercontent.com/33203301/105063100-53cd2d80-5a49-11eb-9aaa-8bcee98d5b8c.png)
* A contributor, for e.g. the owner of a plugin, could expand the accordion to see, "oh - my SonarQube API end point is failing, which is why this error is shown. i'll go see if i can fix that!"
* An integrator, e.g. the owners of the Backstage service, could expand the accordion to see, "oh catalog is broken, seems my database might be down" with relevant details.
  ![image](https://user-images.githubusercontent.com/33203301/105063164-69daee00-5a49-11eb-8027-63f2ce28680e.png)

## 📐 Specs

* Could apply to both Warnings (`<WarningPanel />`) and Errors (`<Alert />`).
* Could ideally hide the complexity of implementation, as such potentially replace the existing WarningPanel and Alert with the ability to customize as necessary. (although optionally, create new components)  i.e., don't necessarily require users to add the three `<Accordion />` elements, if that approach is taken, and instead maybe add props like summary and details to the existing `<Alert />` or `<WarningPanel />` ?
* Should be full width (my examples below are not) based on styling.
* Coloring should inherit from the parent warning or alert object, i.e. the panel could be red while the opened accordion could be a dark grey? This is where a designer needs to say I'm out of my mind. 😁
* I would suggest this could be an extension to the existing warning panel, possibly with children properties, that allow for a header error message.

Roughed out sample code:

```typescript
if (error) {
    return (
      <div>
        <Alert severity="error">
          <Accordion>
            <AccordionSummary expandIcon={<ExpandMore />}>Error encountered while fetching catalog entities.</AccordionSummary>
            <AccordionDetails>{error.toString()}</AccordionDetails>
          </Accordion>
        </Alert>
      </div>
    );
  }
```

## 🔮 Future

Once existing, refactoring to core packages to leverage it by moving any elements of printing out stack traces and the like to the details panel.

**Comment by freben** [comment]
@katz95 ^!

**Comment by katz95** [comment]
Awesome idea - let me consult with my team and we'll get back to you early this week!

**Comment by katz95** [comment]
Hi! We suggest using this type of interaction pattern for the expandable error/warning panels. If we could also change the text color from white to black, that would be great (for A11Y purposes). [image](https://user-images.githubusercontent.com/61153904/105983445-109e3a80-6099-11eb-88aa-a96db23c6d3d.png)

**Comment by adamdmharvey** [comment]
Awesome; thanks @katz95 !  Question if I may on color.

* Current WarningPanel background in open source Backstage is: #F59B23
* Your screen shot example is actually more like: #FBC863 (lighter)

With changes to the panel, should we align it with the lighter color and per your screen shot too?

![image](https://user-images.githubusercontent.com/33203301/106052726-ead45e00-60b7-11eb-9abf-7c4d07e57376.png)

**Comment by adamdmharvey** [comment]
I ended up with this for now before fixing the tests and submitting a PR:

![image](https://user-images.githubusercontent.com/33203301/106055628-9f23b380-60bb-11eb-8a08-73637a01473a.png)

![image](https://user-images.githubusercontent.com/33203301/106055591-916e2e00-60bb-11eb-9dc4-89056c6d0ff0.png)


![image](https://user-images.githubusercontent.com/33203301/106055493-756a8c80-60bb-11eb-9b4c-4f9a712e3698.png)

Only nitpick for me, is the black background inside the unfolded accordion in dark theme mode seems to ever so slightly contrast with the non-black dark mode background? wonder if it should be the same background as the rest of the theme?

**Comment by freben** [comment]
It'd say stay with the colors provided through the Backstage mui theme object's palette. To make sure they stay the same across the entire site

**Comment by freben** [comment]
(That also lets us automatically have different colors in dark and light mode, should we wish to)
