### ISSUE TITLE
Update Repository URL within the catalog-import plugin is incorrect and should be driven by which integration is enabled

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4153]
## Expected Behavior

Repository URL should match what is defined in integrations.scm.host

## Current Behavior

Repository URL is defaulted to https://github.com/backstage/backstage for all integrations

## Possible Solution

Suggesting verbiage to be changed as follows (Example of Bitbucket Integration):

![image](https://user-images.githubusercontent.com/6157895/105089089-aff47980-5a6a-11eb-8b77-83b313495338.png)

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by adamdmharvey** [comment]
Good call out re: # 1, @regicsolutions.

Considering right around the entry box is wrapped the wording "Repository URL", I wonder if the step should be more descriptive and general to align to step 2 and 3.  Something more like "Identify entity location" or something?

![image](https://user-images.githubusercontent.com/33203301/105080294-9fd69d00-5a5e-11eb-93bf-7d0ebf6d99e4.png)

**Comment by regicsolutions** [comment]
> Good call out re: # 1, @regicsolutions.
> 
> Considering right around the entry box is wrapped the wording "Repository URL", I wonder if the step should be more descriptive and general to align to step 2 and 3. Something more like "Identify entity location" or something?
> 

I think that makes sense, can you label this one as help wanted please? i updated the image.

**Comment by adamdmharvey** [comment]
Given the refactoring to the catalog import process and it's related wizard, the good suggestions here in have both been partially implemented but also no longer directly apply.

Current UI looks like this:
![image](https://user-images.githubusercontent.com/33203301/112377102-b34ef000-8cbb-11eb-8e4a-4ef19c15fd20.png)

Note the wizard instructions on the side of the import page do still list GitHub.com examples, but they are listed as examples. There's even further discussion around separating this wizard to simplify it a bit more, so I'm going to go ahead and close this particular ticket and we can then apply newer feedback for the newer code as it continues to evolve.

Thanks for all of the continued feedback @regicsolutions !
