### ISSUE TITLE
DEVEX-858: "Next Page" links in the footer of TechDocs document page doesn't work

### ISSUE THREAD

**Issue by rneumaier** [backstage/backstage#4156]
DEVEX-858: "Next Page" links in the footer of TechDocs document page doesn't work

## Expected Behavior

Document navigation links in the footer of each document should redirect the user to the next document defined in the managing mkdocs.yml file.

## Current Behavior

Document footer links fail to navigate with in the current browser window.

## Possible Solution

Depends on the actual root cause.  I am suspicious of the following:
1. Any external dependencies that need to be accessed to fully configure the footer.
2. Special characters that might be ignored when the user opens the linked to page in a new browser window.

## Steps to Reproduce

1. Open environment URL
2. Navigate to Documents Search Page
3. Navigate to a specific document
4. Scroll down to the footer of the document
5. Click either links for the "prev" link or "next" link
6. Note nothing happens.
7. Right click on the link and select "Open Link in New Window"
8. Page loads in new window without any issue.

## Context

The document linking relationship is defined in the related mkdocs.yml file.

Link failing to resolve:
```
<a href="https://backstage.expedia.biz/docs/eg-flyte/flyte/operational-guide/flows-and-datastore/" title="Flows &amp; Datastore" class="md-footer-nav__link md-footer-nav__link--next" rel="next">
            <div class="md-footer-nav__title">
              <div class="md-ellipsis">
                <span class="md-footer-nav__direction">
                  Next
                </span>
                Flows &amp; Datastore
              </div>
            </div>
            <div class="md-footer-nav__button md-icon">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M4 11v2h12l-5.5 5.5 1.42 1.42L19.84 12l-7.92-7.92L10.5 5.5 16 11H4z"></path></svg>
            </div>
          </a>
```

## Your Environment
- Backstage Code Version: 0.1.1-alpha.18 - https://github.com/backstage/backstage/commit/13908d69c2ddc24b852319c3ff8e09d06cb5ff8f#diff-658b9e62d9d9175692d564450386f1a5aa7f6c4fe08f3e2cc895d2aac58f2e7d
- NodeJS Version (v12): v12
- Mkdocs-maiterial v5.3.2

Example Machine Testing Backstage/Techdocs Site:
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 Enterprise Version 10.0.17763
- Browser Information: Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by OrkoHunter** [comment]
Hey @rneumaier ! What is the version of `@backstage/plugin-techdocs` and `@backstage/plugin-techdocs-backend` you are using?

`0.1.1-alpha.18` looks like a really old version to be honest. :) Please take a look at the `@backstage/create-app` [CHANGELOG](https://github.com/backstage/backstage/blob/master/packages/create-app/CHANGELOG.md) to upgrade your Backstage app and other plugins.

By clicking on the "Next page", do you see any error in the browser (Right click on the page, click "Inspect" and look into "Console" logs) or does the link redirect to a wrong URL?

Try using `mkdocs serve` (or  `mkdocs build`) to see if the "Next page" is working or wrong over there as well. Thank you!

**Comment by rneumaier** [comment]
Hello @OrkoHunter ,
Since pulling out the code, we have upgraded to `0.1.1-alpha.23`.  The point of clarifying `0.1.1-alpha.18` was to determine when the code was essentially split (and further developed).  
My team has been instructed to contribute back to the open source code base.  However, we are not yet architectually at a point where that would make sense.

We also have not fully introduced the `@backstage/plugin-techdocs-backend` codebase in to our techdocs processes:
https://github.com/backstage/backstage/tree/master/plugins/techdocs-backend
I do not know if the functionality worked correctly in our environment previously.

My hope in logging this request was that the issue previously existed in the original codebase and a simple fix could be applied at the code level on our end.

While taking a second look, I realize I have provided the wrong versioning information for techdocs:
https://github.com/backstage/backstage/blob/master/plugins/techdocs/package.json
`  "name": "@backstage/plugin-techdocs",
  "version": "0.5.3",`
Our techdocs code base:
`  "name": "@eg-backstage/plugin-eg-techdoc",
  "version": "0.2.8",`

I am going to discuss with my team regarding comparing the versions and making the necessary changes to upgrade it.  I will provide an additional update after getting some clear direction.  Thanks for the helpful discussion so far.

**Comment by rneumaier** [comment]
Currently my focus is to identify the differences in the 2 codebases.
What would be helpful is to understand how the `prev` and `next` links at the bottom of the mkdocs `*.md` files are generated.
Are you able to help with that or point me to some relevant documentation for it?

**Comment by OrkoHunter** [comment]
Hey @rneumaier ! Thank you for the explanation. :)

We have improved TechDocs a lot since the fork you made and are continuing to accelerate with new features and addressing stability concerns. Take a look at all the docs in this space https://backstage.io/docs/features/techdocs

You are always welcome to request features and even develop some of them with us!

> Currently my focus is to identify the differences in the 2 codebases.
> What would be helpful is to understand how the `prev` and `next` links at the bottom of the mkdocs `*.md` files are generated.
> Are you able to help with that or point me to some relevant documentation for it?

Try running `mkdocs build` separately to debug the output of it. TechDocs only imports the HTML with slight CSS transformations.

**Comment by rneumaier** [comment]
Is there a reason why the mkdocs and mkdocs-material versions are pinned in the following?
https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/test-utils/fixtures/mkdocs-index.ts#L29

**Comment by OrkoHunter** [comment]
Hello, I will close this issue since it happened due to using a custom version of techdocs/mkdocs/mkdocs-material.
