### ISSUE TITLE
Add Kubernetes plugin install instructions

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4170]
## Feature Suggestion

As found out by [`@newbee` on Discord](https://discord.com/channels/687207715902193673/761562031521792020/801467635928924170), the Kubernetes plugin isn't installed into the result of a created sample app (`npx @backstage/create-app`).  In answering, however, I also noticed the Kubernetes README instructions lack install instructions, showing only annotation type settings needed to enable the integration.

Suggestion is that the steps to install the plugin (yarn, plugins.ts, App.tsx, etc.) be added to https://github.com/backstage/backstage/blob/master/plugins/kubernetes/README.md 📝 .

## Possible Implementation

Write the Markdown ! 😁 

## Context

New users who want to use Kubernetes plugin, but who aren't using the raw cloned repo, won't have it by default, and while installing plugins is relatively repetitive and familiar to moderate or advanced users, it may not be obvious to new users who want to try out this [newly defined core feature](https://backstage.io/docs/features/kubernetes/overview).

**Comment by OrkoHunter** [comment]
Examples of (getting started) -

https://backstage.io/docs/features/software-catalog/installation
https://backstage.io/docs/features/software-templates/installation
https://backstage.io/docs/features/techdocs/getting-started

**Comment by adamdmharvey** [comment]
An interesting point behind your links there, @OrkoHunter.  TechDocs is a core feature, and now Kubernetes is. So maybe rather than modifying the README.md, what we should have is a new file added in the Kubernetes section, and the README can link back out to that?

![image](https://user-images.githubusercontent.com/33203301/105212629-b8f15380-5b1b-11eb-82ca-65c9d838848a.png)

**Comment by OrkoHunter** [comment]
Yes, agreed! The instructions should be added to `backstage.io/docs` (using the `docs/` directory). 

READMEs aren't that visible in mono-repos IMO. 😬
