### ISSUE TITLE
Using custom domain name for gitlab repo

### ISSUE THREAD

**Issue by nikhilesh-parupalli** [backstage/backstage#4179]
When using a GitLab instance that does not contain "Gitlab" in its URL, the techdocs fails to fetch the repository.

[Link to the code](https://github.com/backstage/backstage/blob/8226e06cb36b67abde877383cb4b4e30cdf93a30/packages/techdocs-common/src/git-auth.ts#L25)

**Comment by OrkoHunter** [comment]
Hey @nikhilesh-parupalli ! Please update your `backstage.io/techdocs-ref` from `gitlab:<URL>` to `url:<URL>`. That should work with the host if you have defined it under `integrations` config. Some docs on this: https://backstage.io/docs/features/techdocs/how-to-guides#how-to-use-url-reader-in-techdocs-prepare-step

Please re-open the issue if you think the problem still exists!
