### ISSUE TITLE
RFC: Navigation Targets

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#418]
# RFC: Navigation Targets

This is a proposal for new way of handling navigation and registration of plugin routes.

## Current Solution

Routing is handled through regular plain-text paths, plugins register routes themselves, for example:

```tsx
router.registerRoute('/my-plugin', MyPluginPage);
```

To link to the plugin page, you simply link to the page by it's pathname `'/my-plugin'`, and adding a link in the app sidebar is done with

```tsx
// Clickable link
<Link href="/my-plugin">My Plugin</Link>

// Sidebar item
<SidebarItem icon={MyIcon} to="/my-plugin" title="My Plugin" />
```

If it's a parameterized route, it's handled as usual with react-router. For example, the registered plugin route would be `'/my-plugin-thing/:id'`, someone would link to it with `'/my/plugin-thing/146'`

## Problems with the Current Solution

 - There is no way for apps to override the location of a plugin page.
 - Moving plugin routes is a backwards-incompatible change without resorting to redirects.
 - Choosing a route is tricky because you don't want to cause conflicts but you probably want a short and simple one.
 - Discoverability of plugin routes is somewhat poor. Plugins need to manually document routes and it's tricky to get all context when inspecting the route registration code.
 - There is no compile-time check for routes, or route params. There is also no runtime check unless you try to navigate to the actual route.
 - Routes can't have any additional metadata associated with them, that always needs to live next to whoever links to the route.

## Proposed Solution

Add the concept of Navigation Targets (name TBD?). In its simplest for it is a function that returns a route path that takes you to the given target.

For example, given the following app and plugin code:

```tsx
// Plugin
export default createPlugin({
  id: 'home-page',
  register({ router }) {
    router.registerRoute('/home', HomePage);
  },
});

// App Sidebar
<SidebarItem icon={HomeIcon} to="/home" text="Home" />
```

an implementation of navigation targets might look something like this:

```tsx
// Plugin
export const homeNav = createNavTarget('/home')

export default createPlugin({
  id: 'home-page',
  register({ router }) {
    router.registerRoute(homeNav(), HomePage);
  },
});

// App Sidebar
import { homeNav } from '@backstage/plugin-home-page'

<SidebarItem icon={HomeIcon} target={homeNav()} text="Home" />
```

Now the `'/home'` path is only defined in a single place, and if needed, we can add the possibility of overriding the route in the app:

```tsx
homeNav.override('/landing');
```

Here's a minimal (untested) implementation, which should work as long as the override is called before plugins are registered.

```tsx
function createNavTarget(path: string) {
  const navFunc = () => path;
  navFunc.override = newPath => {
    path = newPath;
  }
  return navFunc;
}
```

The above example is a simple solution mostly used to explain the concept, and it really only solves the problem of letting the app override that paths. To attack all of the listed problems, I'm proposing a more full-fledged solution with both metadata and typed route parameteres.

Given a similar example, I'm thinking we could add something that would make the following possible:

```tsx
// nav.ts, nav target defined in a separate file so that plugin can link to itself

// Nav targets can have default icon and titles to display when linking to them
export const deploymentsListNav = createNavTarget({
  path: '/deployments',
  icon: DeplyomentsIcon,
  title: 'Deployments',
})

// Params are added as type parameters to the target
export const deploymentNav = createNavTarget<string>({
  relativeTo: deploymentsListNav, // Relative to other nav targets? ¯\_(ツ)_/¯
  path: '/:name',
  icon: DeplyomentsIcon,
  // Titles can be generated based on params
  title: ({ params: [name] }) => `Deployment - ${name}`,
})

// plugin.ts
export default createPlugin({
  id: 'deployments-plugin',
  register({ router }) {
    // The deployments list page would use the deploymentNav to link to a single deployment, but
    // a page can also use relateive sub-routes internally, but it won't be possible to deep-link to those.
    router.registerRoute(deploymentsListNav, DeploymentsListPage);
    // Nav params would be forwarded as regular route params, with types extracted from the deploymentNav target.
    router.registerRoute(deploymentNav, ({params: [name]}) => <DeploymentsPage name={name}/>);
  },
});

// App Sidebar
import { deploymentsListNav } from '@backstage/plugin-deployments'

// The SidebarItem is able to use the icon and title from the nav target
<SidebarItem target={deploymentsListNav} />
// But can also override properties
<SidebarItem target={deploymentsListNav} icon={MyDeploymentsIcon} />

// The app can override any property of the nav target
deploymentNav.override({
  path: '/my-deployments/:name',
  icon: MyDeploymentsIcon,
})

// Links can be generated directly from nav target, with type safety
const path = deploymentNav.link('my-deployment-123')

// But we can also have a nav target aware Link component, and set a11y attrs etc.
<Link to={deploymentNav} params={['my-deployment-123']}>
```

With the proposed solution I'm hoping we can solve the mentioned problems, but also provide a bit more context to routes, and ease discovery and documentation of what routes plugins expose through generated docs. We should also be able to introduce a bunch of compile-time checks, like what top-level pages aren't linked to anywhere by the app. And we could also allow nav target to be registered as more of a freeform favorites list, curated by each user.

## Drawbacks

There are a couple of drawbacks with the proposed solution, main one being added complexity and adding a new concept to learn to be able to write plugins. There's also the risk that we don't interact with react-router correctly and step on each others toes a bit when it comes to route params.

---

Brain dump complete, curious about feedback before we discuss a potential implementation.

**Comment by ericis** [comment]
I like the abstraction, especially since plug-ins are an external extension to the host application. So, the app-specific abstraction (on top of React Routing) directly mirrors the design choice to support plug-ins.

If plug-ins were required to register a unique name (like npm packages), then routing could simply default to the convention of using the plug-ins package ID as the base route. If you use the npm name, then you get some enforced uniqueness for free (not considering multiple package repositories). While this convention may not always yield "pretty" URLs, it will help ensure routes are actually "unique" as app resources (i.e. Uniform Resource Identifiers or URIs).

To avoid recreating an abstraction, you might consider replicating Ionic's StencilJS routing, where Ionic has experience with deep implementations and integrations across React, Angular, Vue, and standard JS.

**Comment by soapraj** [comment]
+1 

I like the proposed solution for the way we abstract away string-based routing, handle metadata and being able to rename route without resorting to redirects. Other than linting for non-usage of Nav Targets, another possible use could be in e2e tests where you can have an e2e test suite run against all or few Nav Targets.

I am not sure how we would handle route uniqueness if we let the app override the routes?

**Comment by freben** [comment]
How does this relate to things that are subviews? E.g. `/services/my-service-id/circleci` where the last part of the URL is what the plugin contributes - and the view does need to get the previous (dynamic) part of the URL as a prop or get it out of the route, whichever applies.

I am not sure I understand how this solves redirects. Redirects are there for external links to your app to not break; internally within the app is often less of a problem. If you had two views `/foo/a` and `/foo/b` that got collated into the new `/bar`, you still need manual string based redirects.

**Comment by freben** [comment]
I just want to also reiterate that what we will base routing on, is extremely likely to be react-router 6, with its changed way of how hierarchical routing works.

**Comment by Rugvip** [comment]
Thank you for the comments!

@ericis Yeah I like the idea of providing some guarantee of uniqueness without having to manage it manually. We need to keep in mind that there is a benefit to the paths being human readable and easy to dictate to someone though. Maybe getting the plugin id in there could make sense.

@ericis Regarding StencilJS routing, we're currently using [react-router](https://reacttraining.com/react-router/web/guides/quick-start), and it seems to me that they solve the same problem, or do you think StencilJS routing has a different scope?

@soapraj I think uniqueness would be enforced in the app API, and it would be up to the app to handle conflicts through overrides.

@freben I think we can solve that somehow, possibly by using names for the path parameters instead of an array, although that will make it trickier to give them types. It could even be cool if it was possible to override the `relativeTo` property of a nav target, but not sure if that would be useful. The example you brought up is more related to Phase 2 though, and I'm pretty sure that we can solve that through entity navigation target or something like that :p. In general I think this is something to dive deeper into later, pretty confident we'll be able to find some solutions.

@freben It doesn't solve redirects, but it does avoid the app breaking if a plugin changes a route

@freben Idd, react-router v6 would likely be the solution for relative routes inside a nav target

**Comment by Escalion** [comment]
+1
I like the proposed solution.

As a suggestion, uniqueness could be enforced by a plugin cache which is checked when the plugin registers itself, and in the event of a conflict do something simple with the override such as append its version, and failing that, version + some form of a hash of the registering file.
