### ISSUE TITLE
[Plugin] Bitrise

### ISSUE THREAD

**Issue by petergrau** [backstage/backstage#4180]
## Summary

The plugin should display `builds` from `[bitrise](https://www.bitrise.io)` for the selected component. The idea is to provide easy access to all relevant builds and related information.

## Project website

- [bitrise website](https://www.bitrise.io)
- [bitrise APIs](https://api-docs.bitrise.io)

## Context

The plugin follows kind of the idea of other CI plugins: [CircleCI](https://github.com/backstage/backstage/tree/master/plugins/circleci), [Jenkins](https://github.com/backstage/backstage/tree/master/plugins/jenkins), [GitHub Actions](https://github.com/backstage/backstage/tree/master/plugins/github-actions)

From a feature perspective we would regard the following as useful: 
- re-trigger builds
- download the build artefact
- display/link the logs of that build
- filter builds by `workflow` || `app name`

A first UI sketch idea looks like the following:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/46317312/105325735-36c16780-5bcd-11eb-9042-5e55325cb441.png">

**Comment by benjdlambert** [comment]
Is this something that you want to work on @petergrau? The designs look like a good start, you could also take inspiration from the other CI/CD plugins we have like Circle CI and Github.

**Comment by petergrau** [comment]
@benjaminr we are currently investigating the effort needed and if feasible we are planning to work on it.

**Comment by petergrau** [comment]
@benjaminr we have started working on it. will open a PR once it has reached a state where it can be published.

**Comment by moatazeldebsy** [comment]
Hello @petergrau I'm trying to add Bitrise Plugin to Backstage but I got an error with the API because there is no proxy endpoint as mentioned in the plugin Readme file, I added the Auth Token, and the plugin displayed as a tab in the project but can you please clarify to me how to integrate Bitrise. Thank you!

**Comment by petergrau** [comment]
@backstage/sda-se-reviewers  can you look at it?

@moatazeldebsy can you add the errors in the log or actually even create a separate issue for it?
