### ISSUE TITLE
GitHub Actions crashes due to missing config parameters

### ISSUE THREAD

**Issue by dhenneke** [backstage/backstage#4188]
Since #4019, the GitHub Actions plugin uses the integrations package to read the GitHub host from the config, but in combination with a configured GitHub App, the plugin breaks and leads to the following error:

![image](https://user-images.githubusercontent.com/720821/105350635-c118c400-5beb-11eb-8cb1-55aba46900c0.png)

This is not surprising since the config reader requires [values](https://github.com/backstage/backstage/blob/5ebe5dc83e27dfb9eb089fa8ff285ce45756afca/packages/integration/src/github/config.ts#L110-L116) that are not [accessible to the frontend](https://github.com/backstage/backstage/blob/5ebe5dc83e27dfb9eb089fa8ff285ce45756afca/packages/integration/config.d.ts#L87-L112).

## Expected Behavior

The GitHub Actions plugin still works.

## Current Behavior

It doesn't.

## Possible Solution

* Read the hostname from the config directly instead of using the integrations package (might break with future changes).
* Provide a new function to the github integration to get the configured host (though this info might be missing in a separately deployed frontend).
* Provide a new variant of `readGitHubIntegrationConfig` that only focuses on values that are available to the frontend / that only returns the needed list of hosts.

## Context

We don't use the app-backend but serve the frontend from nginx, which doesn't include the [GitHub app credentials](https://backstage.io/docs/plugins/github-apps#including-in-integrations-config) file at all. But I expect that this is also an issue with the app-backend.

If we decide on a possible solution, I can implement the fix.

**Comment by freben** [comment]
Thanks, this list should not be shipped to the frontend at all at this point. Fix PR incoming in a few minutes
