### ISSUE TITLE
/welcome and /settings return 404

### ISSUE THREAD

**Issue by arhill05** [backstage/backstage#4191]
When I navigate to either the welcome or settings pages when running locally, the 404 page is displayed.

Interestingly enough, I also receive a 404 for /welcome on https://demo.backstage.io/welcome, but not for https://demo.backstage.io/settings.

## Expected Behavior

I should be able to access the welcome and settings pages

## Current Behavior

The welcome and settings pages return a 404

## Steps to Reproduce

1. Create app with `npx @backstage/create-app`, selecting sqlite for the database
2. Run the app as indicated in the instructions in the [Getting Started docs](https://backstage.io/docs/getting-started/create-an-app#run-the-app)
3. Try to navigate to /welcome or /settings on the app running locally

## Context

I can't access either of those pages, which means I can't follow the welcome tutorial in the app.

## Your Environment

- NodeJS Version (v12): v12.20.1
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10
- Browser Information: Chrome 88.0.4324.96

**Comment by benjdlambert** [comment]
Hey!

So the `welcome` plugin is not registered in either the demo app or `create-app` versions right now, as we just simply haven't really gotten around to plan for it yet. It used to be registered, but then we defaulted to using the `/catalog` page as the root route for now.

The `/settings` route I think was not added to the `create-app` but should have been added in this most recent release which is currently building right now. So should be available very soon!

**Comment by arhill05** [comment]
Thank you for the quick reply! If I clone the app instead of using `create-app`, would the /welcome and /settings pages be available?

**Comment by benjdlambert** [comment]
So there's a new `create-app` which has just been released which will have the `/settings` route. But the `/welcome` route is not going to be available as we don't know what that's going to look like right now. I guess you've spotted the `/welcome` route somewhere in docs, can I ask where? We should remove that for now as it's not going to be something we're focusing on yet and is a bit misleading.

**Comment by arhill05** [comment]
I found it in the demo as well as my local instance - the banner at the top that shows when you first visit provides a link to `/welcome`, but it navigates to a 404. I didn't see it in the docs anywhere, though.

![image](https://user-images.githubusercontent.com/13209244/105365430-3c6a7d80-5bcc-11eb-95ca-4266615eb2ae.png)

**Comment by benjdlambert** [comment]
Ah ok 🤦  this should be removed. This page basically just listed some basic information about how to get started with backstage, which has all moved really to https://backstage.io/docs. I've just created a PR to remove this welcome banner for now until we get round to making this welcome plugin more specific to end user needs. https://github.com/backstage/backstage/pull/4193

**Comment by arhill05** [comment]
Awesome. Thanks again for the quick response and fixing it so quickly!
