### ISSUE TITLE
SonarQube Plugin Update Issue - Failed to load resource | 400 Bad Request 

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4197]
The latest update broke integration with SonarQube:

http://localhost:7000/api/proxy/sonarqube/measures/search?projectKeys=backstage&metricKeys=alert_status,bugs,reliability_rating,vulnerabilities,security_rating,security_hotspots_reviewed,security_review_rating,code_smells,sqale_rating,coverage,duplicated_lines_density:1  

{"errors":[{"msg":"The following metrics are not found: security_hotspots_reviewed"}]}

**Comment by adamdmharvey** [comment]
@regicsolutions The referenced PR above notes:

> it looks like the metrics should be there since at least version 7.8 / 8.2 with a "proper" introduction in 8.2.

Know the version you're using?  Onprem or cloud?

**Comment by dhenneke** [comment]
Yes that was kind of expected... Sadly the SonarQube API wasn't designed with complete up/downward compatibility in mind. Would be best to make this new feature an opt-in or opt-out.

**Comment by dhenneke** [comment]
Or even better. There is an endpoint where one can search which metrics are available, so we could exclude the ones that are not supported: https://sonarcloud.io/web_api/api/metrics/search

**Comment by dhenneke** [comment]
Should be fixed with https://github.com/backstage/backstage/pull/4200

**Comment by regicsolutions** [comment]
> @regicsolutions The referenced PR above notes:
> 
> > it looks like the metrics should be there since at least version 7.8 / 8.2 with a "proper" introduction in 8.2.
> 
> Know the version you're using? Onprem or cloud?

SonarQube on-prem

**Comment by regicsolutions** [comment]
Confirmed latest fix #4200 resolved my issue running on SonarQube version 8.1
