### ISSUE TITLE
Allow custom error messages from LocationAnalyzer

### ISSUE THREAD

**Issue by tylermarien** [backstage/backstage#4199]
If you are attempting to Register an existing component and the `/api/catalog/analyze-location` endpoint fails, then it returns the status code and text as the error message (https://github.com/backstage/backstage/blob/master/plugins/catalog-import/src/api/CatalogImportClient.ts#L57). This error message is very generic and doesn't provide the user with actionable feedback. It would be nice to be able to provide a customized error message to allow for better feedback to the user.

## Feature Suggestion
Use the response body to provide a more customizable error message to the user. If the response body contains an error message then return that to the user rather than using the status code and text. Not sure if there is a standardized error response format that could be reused here.

## Context
We have customized the LocationAnalyzer to fetch data from GitHub. It will automatically pull information from GitHub to add to the generated Entity. This is an effort to make the generated catalog-info.yaml file more accurate and reduce friction when importing existing Components. If the user types in a non-existent GitHub repository URL then they will get a very generic message. It would be nice to be able to provide a more useful message like "That repository does not exist, please check the URL". This would also provide feedback sooner as it will also fail when trying to make a PR to that repository in the last step of the Import process.

**Comment by andrewthauer** [comment]
Wondering if there is an opportunity to use the new `errors` package here.

**Comment by benjdlambert** [comment]
@andrewthauer yep good suggestion.
