### ISSUE TITLE
npx @backstage/create-app not working after recent release

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#4201]
## Expected Behavior

`npx @backstage/create-app` should work and scaffold a new Backstage app.

## Current Behavior

It throws an error

```
▶ npx @backstage/create-app

npx: installed 67 in 9.101s
Cannot find module '@backstage/backend-common/package.json'
Require stack:
- /Users/himanshum/.npm/_npx/97126/lib/node_modules/@backstage/create-app/dist/index.cjs.js
- /Users/himanshum/.npm/_npx/97126/lib/node_modules/@backstage/create-app/bin/backstage-create-app
```

## Possible Solution

Is it because of the first release of `@backstage/create-app` with 1.x.x version?

For users: You can try out an older version of create-app script `npx @backstage/create-app@0.3.5`.

## Steps to Reproduce

Run `npx @backstage/create-app`

## Context

Also reported couple times on Discord today
https://discord.com/channels/687207715902193673/687235481154617364/801832402526666762
https://discord.com/channels/687207715902193673/687235481154617364/801849838945173514

**Comment by OrkoHunter** [comment]
Looking at the latest release of the package, only `@backstage/cli-common` was bundled. Hence the package missing error. 🤔 

![Screenshot 2021-01-21 at 18 07 02](https://user-images.githubusercontent.com/8065913/105385307-8034a580-5c13-11eb-9a61-081c146b7395.png)

**Comment by willashford** [comment]
Thought I was going insane
