### ISSUE TITLE
Microsite: Screen width issue

### ISSUE THREAD

**Issue by AlleyWei** [backstage/backstage#4205]
## Expected Behavior
Left hand margins should appear as follows:

![width 1920](https://user-images.githubusercontent.com/64219471/105414139-16ad9a80-5c05-11eb-913e-033643ced5c9.png)

## Current Behavior
Currently, the width of the site appears too far to the left (according to @OrkoHunter, the margin in the left almost disappears on a 1440px width screen). This is how it currently appears:

![width 1440](https://user-images.githubusercontent.com/64219471/105414149-1ca37b80-5c05-11eb-9810-8db8e5c490c7.png)

## Possible Solution
Please fix the margins for various screen sizes.

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by chinmaym07** [comment]
Can I work upon this issue .?

**Comment by adamdmharvey** [comment]
@chinmaym07 Fantastic, assigned you!

I'll note, looking at the screen shot, I wonder if the issue with the gutter is that there's a lot of space inside of that image on the right so what LOOKS like misalignment might be properly aligned in terms of the content actually there (text + image).  But yeah if you can take a stab that would be great!! 🎉 🎉 🎉

**Comment by chinmaym07** [comment]
@adamdmharvey sir just to verify . should I fix the margin's of other section's also as some other sections also have this issue for eg :
![Screen Shot 2021-02-12 at 20 12 37](https://user-images.githubusercontent.com/44670961/107782220-d0b0a600-6d6e-11eb-9a7a-e7c22835b068.png)
![Screen Shot 2021-02-12 at 20 12 55](https://user-images.githubusercontent.com/44670961/107782224-d1e1d300-6d6e-11eb-8b04-e274274410db.png)

**Comment by OrkoHunter** [comment]
@chinmaym07 Thanks for noticing ! It'd be great to have some spacing in all screen sizes for the whole page. So, it's awesome that you're thinking about it.

**Comment by chinmaym07** [comment]
@OrkoHunter sir , @adamdmharvey sir I have fixed the above issue .
Please look at the below screenshot & let me know shall I create a PR for the same ?
I have not done any changes to navbar . While taking screenshot it just slides below 😁 

![Screenshot_2021-02-22 Backstage Service Catalog and Developer Platform · An open platform for building developer portals](https://user-images.githubusercontent.com/44670961/108729419-825e8c80-7550-11eb-83f7-4e5bf6e64e5d.png)

**Comment by adamdmharvey** [comment]
I'd say for sure submit any PR when you have something you think is ready. Pull requests are the ideal place for your changes to be presented, and the feedback inline for what looks good, how to tweak it, is likely best held there with this report of the initial issue a place to discuss the overall (and tracking if it's been closed).

Now, what you show seems to relate to what I was wondering which is this:

![image](https://user-images.githubusercontent.com/33203301/108741023-47366c00-7504-11eb-8f1c-724e3954af93.png)

It looks like to visually make it seem to align, you've had to push one of the images off of the screen? I just had wondered whether the issue from a design stand point maybe wasn't one of CSS alignment but one of aligning content which may actually LOOK bigger (an image with space around it INSIDE of an image).  I'm not a designer, but just what I had noticed.

**Comment by chinmaym07** [comment]
Ohk I got it sir .. I have made the changes & I'll create a PR for now & I'll ask you to review it. thanks a lot !!

![Screen Shot 2021-02-22 at 22 28 44](https://user-images.githubusercontent.com/44670961/108742083-5b5a8780-755d-11eb-9279-aae81e7a2ebe.png)
