### ISSUE TITLE
Update Scaffolder front-end content to be integration specific

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4207]
Front-end Software Template content is specific to Github and should be specific to whatever integration is in place. This is a proposal to make it specific to the origin of the template location and stripping out anything after two slashes and adding `new-repo`

### Example

**When location is set to:** `https://github.com/backstage/backstage/blob/9d2e270631462ad01adc931d981ef5dffcced5b9/plugins/scaffolder-backend/sample-templates/create-react-app/template.yaml `

**Content should be updated to:** 
`https://github.com/backstage/new-repo`

I marked out in red where i have seen this content come up, please comment if you have seen it anywhere else.

I cant take the credit for this idea, @goober came up with the location idea!

![image](https://user-images.githubusercontent.com/6157895/105425370-3cdc3600-5c17-11eb-95ec-4918e49b2d2f.png)

**Comment by benjdlambert** [comment]
It could be good to parse the URL that you have typed in a maybe suggest hints.

For the record, the end result for this page is to have a dropdown select for your project in whatever provider and then you type in the repo name. The dropdown will show you the different places where you're able as a signed in user to Backstage create repositories too.

**Comment by regicsolutions** [comment]
> It could be good to parse the URL that you have typed in a maybe suggest hints.
> 
> 
> 
> For the record, the end result for this page is to have a dropdown select for your project in whatever provider and then you type in the repo name. The dropdown will show you the different places where you're able as a signed in user to Backstage create repositories too.

Understand, any timeframe on when the dropdown functionality will be available?

**Comment by benjdlambert** [comment]
I think it will be on our list probably end of Q1 maybe, most probably will come with the change to the schema as that is when the frontend will be worked on I think.
