### ISSUE TITLE
org: Visual alignment of data on User Profile Card

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4211]
Trivial visual bug of aligning text on the User Profile Card in the `org` plugin.

## Expected Behavior

The displayed data for a user lines up in a table-like fashion.

## Current Behavior

The user's e-mail address and the list of their group memberships aren't fully aligned, likely because the e-mail and group icons are slightly different widths.

![image](https://user-images.githubusercontent.com/33203301/105450244-12ef3780-5c48-11eb-8306-857961143316.png)

## Possible Solution

Display the data in this section of the card in a table to drive better alignment - icons first row, data second, etc.

Currently, the e-mail icon + e-mail is displayed in one Grid element, and the group icon + group names are displayed in another grid element. So the grid items line up, but the element spacing _in them_ do not. Could set some sort of forced width on the icons, if that's a thing, or refactor the Grid as either fixed width (as you wouldn't want the icons to move away from the text), or refactor as a table.

https://github.com/backstage/backstage/blob/master/plugins/org/src/components/Cards/User/UserProfileCard/UserProfileCard.tsx

## Steps to Reproduce

1. Load user data to the catalog entities
2. At least one user must have an e-mail provided (I used GitHub) and at least one group
3. View the user's card at `/catalog/default/user/<userid>`

## Context

Neither my users nor I will likely think about it again, unless it comes back at me in my dreams  haunting my alignment sensibilities.  😴 👻 :twisted_rightwards_arrows:

But as more and more data is displayed in this card over time, the alignment may become more noticable.

## Your Environment

- NodeJS Version (v12): v12 and v14
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information: Microsoft Edge (Chrome engine)

**Comment by freben** [comment]
Or refactor as a single [List](https://material-ui.com/components/lists/) perhaps.
