### ISSUE TITLE
Parse GitURL as assumed provider

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#4215]
Right now, we are unable to parse URL's consistently as they are parsed based on the hostname which for on prem services wont follow the same standard in hostname.

We know what provider the URL comes from, so we should be able to force a particular type, and fallback to the current `gitUrlParse` implementation.

## Feature Suggestion
- Either raise a PR to gitUrlParse to say, parse this as this type
- Or force the hostname in the URL that we parse to be of that default type
- Or pick apart that library and re-implement our own

**Comment by OrkoHunter** [comment]
There are so many inconsistencies in `git-url-parse`, but it explodes with Bitbucket URLs (especially when `?ref=branchname` is added to the URL suffixes.)

**Comment by ayshiff** [comment]
I'll be happy to help on this 👍

**Comment by OrkoHunter** [comment]
Just mentioning it here that @n2ygk has already raised a PR to improve the library for Azure DevOps. https://github.com/IonicaBizau/git-url-parse/pull/124

If we can aggregate all the issues we are facing, I'm hopeful we can improve the upstream. 💯

**Comment by benjdlambert** [comment]
I wonder if it make sense to contribute a feature then to the upstream that we can pass in a parse method too for on prem hostnames too then? There's a hacky workaround that we could force the URL hostname to the one that we know it could be, but i'd rather us try to standardize passing in the type instead.
