### ISSUE TITLE
Lack of warning for spaces in component names

### ISSUE THREAD

**Issue by willashford** [backstage/backstage#4216]
When creating a new component, (e.g. "sample docs"), there are no warnings relating to the presence of a space in the name. When trying to register this in the catalog, there was a unclear "something went wrong" style message. 

When trying to manually register the component afterwards, the following error was raised:
<img width="713" alt="image" src="https://user-images.githubusercontent.com/42339022/105485199-6e4f1300-5ca4-11eb-94ee-6a48e856045e.png">

## Expected Behavior

Appreciate that there is a convention but raising this error prior to the creation of a component would make life easier. 

## Current Behavior

There's no warnings and plebs like me create components with non-compliant names. 

## Possible Solution

Validate the component names using the same entity name policy as the manual registry. 

## Steps to Reproduce

1. Create a component with a space in the name. 
2. Registry in the catalog should fail. 
3. Try and manually register it. 

## Context

Just a pain really.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): macOS Big Sur v11.0.1 (M1 Chip)
- Browser Information: Safari Version 14.0.1 (16610.2.11.51.8)

**Comment by benjdlambert** [comment]
Thanks for the report - yep you're right , we should have some better validation around this!
