### ISSUE TITLE
Usage statistics of the platform

### ISSUE THREAD

**Issue by nirga** [backstage/backstage#4221]
## Feature Suggestion

This might be somehow related to #1519 but not exactly. I want to suggest adding a layer of the allow admins to see usage statistics of the platform. This can be super basic like showing what features teams are using, how often do people go into the platform, slice it by team or project, etc. 

## Context

I think this can be really useful when teams are deploying this tool to organization to measure how successful has the deployment been and is it worth to continue investing in it. We recently deployed a code search tool and having the ability to see usage statistics was super helpful in convincing stakeholders about the usefulness of this new tool.

**Comment by benjdlambert** [comment]
Hey, so we have Google Analytics support built in which will give you page views. You can enable that by adding the tracking data to this config, https://github.com/backstage/backstage/blob/e9bcb7b446425276b6545616cff726be12afd0dd/app-config.yaml#L4

We don't have an event's API wrapped around it to do something a little more granular. It's not something the core team will be focusing on soonish, but we're open to contributions if it's something that you think would bring good value!

**Comment by nirga** [comment]
Definitely @benjdlambert, you can assign it to me and I'll try to come up with a proposal.

**Comment by freben** [comment]
done!

**Comment by adamdmharvey** [comment]
BTW to @benjdlambert 's point, that Google tracking thing isn't called out in doco anywhere, so it wouldn't be easy or possible for most new Backstage users to know it exists? Is it a part of a 3rd library we have as I don't really see it used anywhere besides being passed into an HTML WebPack library?  Anyway, if it's "robust" enough to use, wonder if should spin up a story for someone to add that to https://backstage.io/docs maybe to elevate that as could be useful to audiences?

**Comment by freben** [comment]
Sure. I wonder where that doc would fit in the hierarchy 🤔

**Comment by andrewthauer** [comment]
We ended up adding `page_view` events by adding a `useGoogleAnalytics` hook that in turn uses `useLocation` changes from `react-router`. Had to rework this recently due to the `FlatRoute` changes. It's a bit specific to our auth provider, but it could be possible to extract part of it and push upstream. Or could be added to contrib.

**Comment by freben** [comment]
Added a small PR to get going with SOME observability docs at least.

https://github.com/backstage/backstage/pull/4339

**Comment by kuangp** [comment]
Hi, I was wondering if anyone has any updates on this? it looks like the current implementation only tracks each initial hit to the Backstage site but doesn't report hits per route? @andrewthauer it sounds like you hooked up a way to report per route metrics? would it be possible to share how one would go about doing this? (sorry not familiar with react)

**Comment by andrewthauer** [comment]
> Hi, I was wondering if anyone has any updates on this? it looks like the current implementation only tracks each initial hit to the Backstage site but doesn't report hits per route? @andrewthauer it sounds like you hooked up a way to report per route metrics? would it be possible to share how one would go about doing this? (sorry not familiar with react)

Here's the relative simple solution we have to track page views. This could probably go into `contrib` but for speed, I'll just paste it here. Feel free to contrib it :)

```diff
// packages/app/public/index.html
-  gtag('config', '<%= app.googleAnalyticsTrackingId %>');
+ gtag('config', '<%= app.googleAnalyticsTrackingId %>', { end_page_view: false });
```

```tsx
// packages/app/src/hooks/useGoogleAnalytics.ts
import { configApiRef, identityApiRef, useApi } from '@backstage/core';
import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';

export function useGoogleAnalytics() {
  const config = useApi(configApiRef);
  const identityApi = useApi(identityApiRef);
  const location = useLocation();

  useEffect(() => {
    if (window.gtag !== undefined) {
      gtag('event', 'page_view', {
        page_title: document.title,
        page_location: window.location.href,
        page_path: location.pathname,
      });
    }
  }, [config, location]);

  useEffect(() => {
    const analyticsTrackingId = config.getOptionalString(
      'app.googleAnalyticsTrackingId',
    );

    if (window.gtag !== undefined && analyticsTrackingId) {
      gtag('config', analyticsTrackingId, {
        user_id: identityApi.getUserId(),
      });
    }
  }, [config, identityApi]);
}
```

```tsx
// package/app/src/App.tsx
const Analytics = () => {
  useGoogleAnalytics();
  return <span />; // empty component
};

const App = () => (
  <AppProvider>
    <AppRouter>
      <Analytics />
      <Root>{routes}</Root>
    </AppRouter>
  </AppProvider>
);
```

**Comment by snake163** [comment]
Is anyone using or considering using [Pendo](https://www.pendo.io/) with Backstage?

**Comment by waldirmontoya25** [comment]
Is anyone using or considering using [Pendo](https://www.pendo.io/) with Backstage?
