### ISSUE TITLE
Absolute Import with baseUrl and path in tsconfig

### ISSUE THREAD

**Issue by ShadOoW** [backstage/backstage#4222]
Hello,

Does backstage support Absolute Imports?

I've tried setting it up in the root dir tsconfig file without success.

In my plugin I want to change this
```javascript
import { Text } from './../../../../../typography';
```

To this
```javascript
import { Text } from 'my-plugin/typography'
```

**Comment by Rugvip** [comment]
We do not. Too much hassle supporting it throughout all build systems and not enough benefit. Gotta support it in webpack, rollup, type declarations, storybook, jest, eslint, and prolly more ._.

See #729

**Comment by ShadOoW** [comment]
@Rugvip Thanks for the quick clarification, and explanation.

I will close this issue, hopefully one day we will have this feature.
