### ISSUE TITLE
microsite feat: Add category/tag filter to plugin marketplace

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4234]
## Feature Suggestion

The plugin marketplace is growing, with 28 plugins available now and more on their way.

It would be great to have a quick filter of some type along the top of the marketplace page to be able to say, pick monitoring plugins, or security plugins, even as a way to slightly reduce the number as the list continues to grow.

![image](https://user-images.githubusercontent.com/33203301/105651279-6948ba00-5e84-11eb-9cb7-7180d451389b.png)

## Possible Implementation

Ideas, though don't need all of them:

* A filter at the far top right that collects all categories defined in the YAMLs, and provides a selection box to only show cards in that category
* A left nav filter, possibility emulating the filter on the Backstage search page, that has the search + tags
* Ability to search by tags. The plugin YAML metadata has tags today, though they aren't exposed yet in anyway. Adding a tag searcher could be useful.

Modifying code here: https://github.com/backstage/backstage/blob/master/microsite/pages/en/plugins.js

## Context

I saw another new plugin addition PR and realized it's the sixth monitoring plugin, and would be great to see them all together in some way.

**Comment by benjdlambert** [comment]
@katz95 @AlleyWei thoughts?

**Comment by AlleyWei** [comment]
@benjdlambert @adamdmharvey I think this is a great idea, particularly since we have labels for each plugin anyway. Will loop back with design/copy and share suggestions. Thank you!

**Comment by adamdmharvey** [comment]
If you don't mind @AlleyWei , assigned to you in terms of next steps, and once we have a proposed design, can unassign again to get the community to chip in to implement.

**Comment by freben** [comment]
Closing as a duplicate of the larger docusaurus 2 work
