### ISSUE TITLE
Docs: Improve TechDocs example documentation component

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#4237]
## Feature Suggestion

Backstage mono-repo comes with an example component for TechDocs. It is located here
https://github.com/backstage/backstage/tree/master/plugins/techdocs-backend/examples/documented-component
and is loaded into the app from here https://github.com/backstage/backstage/blob/c3ea694e8400a35e2dfe4cf577c0fa66c66a8570/app-config.yaml#L207-L209

This component should be an exhaustive display of all the features that TechDocs/MkDocs provides.

## Possible Implementation

- Add few more sub pages.
- Use one image and refer into markdown as relative path.
- Load an external image using URL.
- Look at the MkDocs extension that comes with [mkdocs-techdocs-core](https://github.com/backstage/mkdocs-techdocs-core#mkdocs-plugins-and-extensions) and add a section in a page for each.

## Context

Essentially we want this component for two use-cases
1. Display most of the features
2. Use as a place to test new implementations and making sure it doesn't break any of these plugins. (Will follow up with regression tests after the component is improved)

**Comment by Aiwwa** [comment]
Hi, i can help with this improvement :)

**Comment by OrkoHunter** [comment]
Assigned it to you! Ask here or drop by on Discord's #docs-like-code channel if you need any help.

**Comment by OrkoHunter** [comment]
@Aiwwa I can't see your comment anymore hence, marking this issue up for grabs. Let us know if you're still working on it.
