### ISSUE TITLE
Schema and Kind validation do not work for POST /api/catalog/entities

### ISSUE THREAD

**Issue by ruloweb** [backstage/backstage#4248]
When you create an entity with `POST /api/catalog/entities` schema and kind validations do not run.

## Expected Behavior

All entity validations should occur when the entity is created/updated. 

## Current Behavior

Entity validations occur only when an entity is created from a Location.

## Possible Solution

Move entity validations from Location ingestion into the entity creation/update process.

## Steps to Reproduce

This should fail because `kind` `a` does not exsit:
```
curl \
  -d @- \
  -H "Content-Type: application/json" \
  -X POST http://localhost:7000/api/catalog/entities <<EOF
{
  "apiVersion": "backstage.io/v1alpha1",
  "kind": "a",
  "metadata": {
    "name": "test",
    "namespace": "default"
  },
  "spec": {
    "owner": "team-a",
    "system": "artist-engagement-portal"
  }
}
EOF
```

This should fail because required fields `type` and `lifecycle` are missed:
```
curl \
  -d @- \
  -H "Content-Type: application/json" \
  -X POST http://localhost:7000/api/catalog/entities <<EOF
{
  "apiVersion": "backstage.io/v1alpha1",
  "kind": "Component",
  "metadata": {
    "name": "test",
    "namespace": "default"
  },
  "spec": {
    "owner": "team-a",
    "system": "artist-engagement-portal"
  }
}
EOF
```

## Context

I want to create entities with no need of a YAML file.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): macOS Catalina 10.15.7
- Browser Information: cli

**Comment by freben** [comment]
The location based flows are actually the only ones we have primary support for. You've hit a bit of a dark corner. But if I may ask, I'd like to understand what your needs are, and why you want to do things specifically this way. Maybe we can help.

**Comment by ruloweb** [comment]
I've created a new entity kind and I would like the user to create entities using the UI, which will call the entity REST API.

**Comment by freben** [comment]
The location based ingestion flows are really being invested in, and I don't foresee us putting a direct-push version to the forefront within reasonable time. This may seem odd, but there are several reasons - one of them is that we are looking into overhauling the foundations of how processing happens in the catalog, to enable scaling and features. Those will be harder to do when supporting several paradigms.

One suggestion that may sound unexpected but which aligns you with this world:

You could make a simple entity store of your own, that you can manage items within. Then you make a little custom processor in the catalog that actually consumes that entity store. For example you'd add something like this to your config:

```yaml
catalog:
  locations:
    - type: custom-store
      target: http://customstore.company.net:8080/entities
```

**Comment by freben** [comment]
Hey, would it be OK to close this ticket at this point? Given our our current state and plans, and the sketch of an alternative solution for the shorter term.
