### ISSUE TITLE
Local installment bugs

### ISSUE THREAD

**Issue by khanh-cg** [backstage/backstage#4264]
Installing issue: https://backstage.io/docs/getting-started/running-backstage-locally#clone-and-build

## Expected Behavior

"yarn install" runs without issue 

## Current Behavior

[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@backstage/core > material-table@1.69.1" has unmet peer dependency "@date-io/core@^1.3.6".
warning "@backstage/core > react-router@6.0.0-beta.0" has unmet peer dependency "history@>=5".
warning "@backstage/core > react-router-dom@6.0.0-beta.0" has unmet peer dependency "history@>=5".
warning "@backstage/core > @testing-library/user-event@12.0.7" has unmet peer dependency "@testing-library/dom@>=7.16.0".
warning "@backstage/core > @backstage/cli > eslint-plugin-jsx-a11y@6.2.3" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6".
warning "@backstage/core > material-table > @material-ui/pickers@3.2.10" has unmet peer dependency "@date-io/core@^1.3.6".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > @backstage/plugin-rollbar > @testing-library/react-hooks@3.4.1" has unmet peer dependency "react-test-renderer@>=16.9.0".
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.2" has unmet peer dependency "@octokit/core@>=3".
warning " > @spotify/eslint-config-oss@1.0.2" has unmet peer dependency "eslint@>=6".
warning "@spotify/eslint-config-oss > eslint-plugin-notice@0.9.10" has unmet peer dependency "eslint@>=3.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > example-app > eslint-plugin-cypress@2.11.2" has unmet peer dependency "eslint@>= 3.2.1".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addons@6.1.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addons@6.1.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react@6.1.14" has unmet peer dependency "@babel/core@^7.11.5".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react@6.1.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react@6.1.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > storybook-dark-mode@1.0.3" has unmet peer dependency "@storybook/api@>= 6.x".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > storybook-dark-mode@1.0.3" has unmet peer dependency "@storybook/components@>= 6.x".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > storybook-dark-mode@1.0.3" has unmet peer dependency "@storybook/core-events@>= 6.x".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > storybook-dark-mode@1.0.3" has unmet peer dependency "@storybook/theming@>= 6.x".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > @backstage/plugin-api-docs > graphiql@1.0.3" has unmet peer dependency "prop-types@>=15.5.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > @backstage/plugin-kafka > @testing-library/react-hooks@3.4.2" has unmet peer dependency "react-test-renderer@>=16.9.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/addons@6.1.11" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/addons@6.1.11" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/api@6.1.11" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/api@6.1.11" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/client-api@6.1.11" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/client-api@6.1.11" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/components@6.1.11" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/components@6.1.11" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/theming@6.1.11" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/theming@6.1.11" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > react-inspector@5.0.1" has unmet peer dependency "react@^16.8.4".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-links > @storybook/router@6.1.11" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-links > @storybook/router@6.1.11" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-storysource > @storybook/source-loader@6.1.11" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-storysource > @storybook/source-loader@6.1.11" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-storysource > react-syntax-highlighter@13.5.3" has unmet peer dependency "react@>= 0.14.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addons > @storybook/api@6.1.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addons > @storybook/api@6.1.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addons > @storybook/router@6.1.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addons > @storybook/router@6.1.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addons > @storybook/theming@6.1.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addons > @storybook/theming@6.1.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @babel/preset-flow@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core@6.1.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core@6.1.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > babel-plugin-named-asset-import@0.3.6" has unmet peer dependency "@babel/core@^7.1.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > react-docgen-typescript-plugin@0.6.3" has unmet peer dependency "typescript@>= 3.x".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > @backstage/plugin-api-docs > graphiql > codemirror-graphql@0.12.0" has incorrect peer dependency "codemirror@^5.54.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > @backstage/plugin-catalog-graphql > @graphql-modules/core > @graphql-modules/di@0.7.17" has unmet peer dependency "reflect-metadata@^0.1.12".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > @backstage/plugin-catalog-graphql > apollo-server > graphql-subscriptions@1.1.0" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has unmet peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/components > markdown-to-jsx@6.11.4" has unmet peer dependency "react@>= 0.14.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/components > react-popper-tooltip@3.1.1" has unmet peer dependency "react@^16.6.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/components > react-popper-tooltip@3.1.1" has unmet peer dependency "react-dom@^16.6.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/components > react-textarea-autosize@8.2.0" has unmet peer dependency "react@^16.8.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/theming > @emotion/core@10.1.1" has unmet peer dependency "react@>=16.3.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/theming > @emotion/styled@10.0.27" has unmet peer dependency "react@>=16.3.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/theming > emotion-theming@10.0.27" has unmet peer dependency "react@>=16.3.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @babel/preset-flow > @babel/plugin-transform-flow-strip-types@7.12.10" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core > @storybook/client-api@6.1.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core > @storybook/client-api@6.1.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core > @storybook/components@6.1.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core > @storybook/components@6.1.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core > @storybook/ui@6.1.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core > @storybook/ui@6.1.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > react-docgen-typescript-plugin > react-docgen-typescript@1.20.5" has unmet peer dependency "typescript@>= 3.x".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > @backstage/techdocs-common > @aws-sdk/client-s3 > @aws-sdk/middleware-retry > react-native-get-random-values@1.5.0" has unmet peer dependency "react-native@>=0.56".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > @backstage/plugin-catalog-graphql > apollo-server > apollo-server-core > graphql-upload@8.1.0" has incorrect peer dependency "graphql@0.13.1 - 14".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/api > @reach/router > create-react-context@0.3.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/components > react-color > @icons/material@0.2.4" has unmet peer dependency "react@*".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/components > react-popper-tooltip > react-popper@2.2.4" has unmet peer dependency "react@^16.8.0 || ^17".
omponents > react-textarea-autosize > use-composed-ref@1.0.0" has unmet peer dependency "react@^16.8.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/components > react-textarea-autosize > use-latest@1.1.0" has unmet peer dependency "react@^16.8.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/theming > @emotion/styled > @emotion/styled-base@10.0.31" has unmet peer dependency "react@>=16.3.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @babel/preset-flow > @babel/plugin-transform-flow-strip-types > @babel/plugin-syntax-flow@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core > @storybook/ui > downshift@6.0.7" has unmet peer dependency "react@>=16.8.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core > @storybook/ui > react-helmet-async@1.0.4" has unmet peer dependency "react@^16.6.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core > @storybook/ui > react-helmet-async@1.0.4" has unmet peer dependency "react-dom@^16.6.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core > @storybook/ui > react-hotkeys@2.0.0" has unmet peer dependency "react@>= 0.14.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core > @storybook/ui > react-sizeme@2.6.12" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/react > @storybook/core > @storybook/ui > react-sizeme@2.6.12" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning "workspace-aggregator-11fc14f4-4610-4c78-a4d1-03781092aa56 > storybook > @storybook/addon-actions > @storybook/components > react-textarea-autosize > use-latest > use-isomorphic-layout-effect@1.0.0" has unmet peer dependency "react@^16.8.0".
[5/5] Building fresh packages...
Done in 2344.47s.

## Your Environment

- NodeJS Version (v12):14.15.4
- Operating System and Version (e.g. Ubuntu 14.04): windows 10 pro buid 18363.1316
- Browser Information: chrome

**Comment by OrkoHunter** [comment]
> Done in 2344.47s.

Looks like it worked. All these warnings are expected. 😁
