### ISSUE TITLE
Create a new entity Kind with no core modifications

### ISSUE THREAD

**Issue by ruloweb** [backstage/backstage#4275]
If I add a new entity kind, I have to add it into the `BuiltinKindsEntityProcessor`.

## Expected Behavior

Add new entity kinds with no core modifications.

## Current Behavior

If you don't add your new entity kinds into the `BuiltinKindsEntityProcessor` class, validations will fail.

## Steps to Reproduce

1. Create a new entity kind class
2. Import an entity of the new kind from a YAML file

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): macOS Catalina 10.15.7
- Browser Information: CLI

**Comment by freben** [comment]
Hi!

The correct course of action is to create a new custom corresponding plugin of your own, and to add it to the catalog. The `BuiltinKindsEntityProcessor` continues to take care of the builtin kinds and yours takes care of the custom kinds.

You will have a file similar to [this](https://github.com/backstage/backstage/blob/master/packages/backend/src/plugins/catalog.ts#L26) in your backend. The builder has an [`addProcessor` method](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/CatalogBuilder.ts#L18).

**Comment by freben** [comment]
I'll close this one since I believe the use case is covered. Feel free to reopen the issue if you feel that this was in error!
