### ISSUE TITLE
jenkins: Improve error display on Jenkins latest build overview card

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4292]
Improve error handling for the Jenkins overview card.

## Expected Behavior

If there is a misconfiguration of a Jenkins pipeline, I believe the expected behavior should be:

* the Jenkins card should still display, but inline to the card the card should display the error
* there should not be an errorApi alert popup for the user

## Current Behavior

In this case, the initial GitHub org path had a typo in it, so this component's Jenkins latest build card was broken. However, it's not so friendly to have a large red popup, and the sort of "can't display React" error for the card which infers there's a problem with Backstage (thus "go get the integrator to fix it"). The issue was in the entity config, itself.  Would be better to trap that error within the card and indicate it can't be displayed, and print the error.

![image](https://user-images.githubusercontent.com/33203301/106180828-d69d6900-616a-11eb-9cd2-a92c2b61c089.png)

## Steps to Reproduce

1. Install Jenkins plugin, placing the overview card on the entity overview page
2. Provide an invalid annotation in an entity for `jenkins.io/github-folder`
3. View the entity's overview page

## Context

Simply moving the error from alertApi popup/errorApi over to the card with maybe a `<WarningPanel>` would be great, but EVEN BETTER would be to trap this specific type of error, and provide some error context to the user such as can't find the job in Jenkins, which is different than can't CONNECT to Jenkins, and thus the inference may be an incorrect annotation. That might allow the entity owner to fix it themselves, rather than engaging the integrator team.

## Your Environment

- NodeJS Version (v12): v12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL 2 Ubuntu 18.04
- Browser Information: Microsoft Edge (Chrome Engine)

**Comment by TejasQ** [comment]
@adamdmharvey would the above PR suffice to help in your use case, or would you require more by way of errors?

**Comment by alexksbr** [comment]
Coincidentally, I was playing around with a solution as well, which complements @TejasQ 's pull request quite well. I have not touched the existing `ErrorBoundary`, but instead switched to a `WarningPanel` within the Card instead of an error.

Maybe you can have a look at it as well, but I think it could be a good addition to PR #5755
