### ISSUE TITLE
[catalog-frontent] : truncate description and provide hover-over in entity list in home screen

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#4297]
Entity descriptions are usually a brief paragraph/few lines. Current entity list shows full description text, which ends up being multiple lines for a single component, makes it visually inconsistence/asymetric. As an alternative, I suggest to trunate the text after 1/2 lines and provide a (...), which can be hover-over to show tooltip with full description.

## Feature Suggestion
Use fix length for description text in list view, optionally hover-over with tooltip for complete description.

## Possible Implementation
As an alternative, I suggest to trunate the text after 1/2 lines and provide a (...), which can be hover-over to show tooltip with full description.

**Comment by adamdmharvey** [comment]
@kiranpatel11 If possible, could you provide some screen shots pointing to what you're seeing on your side and the rough length?

I'll admit to not having tested really long ones before. I like the display on the About Card, but I can see what you mean on the main catalog table, and in fact the length is distracting also on the Search results page as well. Given that, it might make sense to have a reusable method to call to truncate it and show a tool tip, such that it could be reused in both the `plugin-catalog` as well as `plugin-search`, and potentially reusable by any plugin that might have the same challenge.

![image](https://user-images.githubusercontent.com/33203301/106217086-7b876880-61a2-11eb-8606-8595866dc0c0.png)

![image](https://user-images.githubusercontent.com/33203301/106217050-63afe480-61a2-11eb-9207-1f86f425c14a.png)

![image](https://user-images.githubusercontent.com/33203301/106217122-8d690b80-61a2-11eb-8d5e-eae61bfd46e4.png)

**Comment by kiranpatel11** [comment]
@adamdmharvey yes I am refering to same issues as in your screenshots...

I fixed it in local, but not yet as reusable component. 
![Home _ Services _ Backstage - Google Chrome 1_29_2021 12_22_01 PM](https://user-images.githubusercontent.com/8432431/106219410-63106000-622d-11eb-8667-8e2bd1baaad1.png)

**Comment by adamdmharvey** [comment]
That looks awesome, @kiranpatel11 !  If you're willing, I'd file a PR to get that in just to the catalog - it's incrementally better than what we all have today. Then once it's in, we can all then refactor it to continue improving, maybe making it that reusable component, put it into Search plugin also, etc.  🎉

**Comment by kiranpatel11** [comment]
Sure @adamdmharvey
