### ISSUE TITLE
user-settings: Pin sidebar disappears on smaller screens

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4298]
## Expected Behavior

In user settings, the _Pin sidebar_ configuration in the **Appearance** card should always be visible even if the screen width gets smaller.

## Current Behavior

On the user settings page, if you reduce the screen size so the two current cards - Profile and Appearance - stack one on top of the other, the "Pin sidebar" configuration element disappears.

**Full screen**
![image](https://user-images.githubusercontent.com/33203301/106232487-23605e80-61c2-11eb-9921-0a9805481c7a.png)

**Smaller screen** - where'd it go? 🔍 
![image](https://user-images.githubusercontent.com/33203301/106232713-a71a4b00-61c2-11eb-876d-87acdc49f7db.png)

## Possible Solution

Check and validate the Grid settings in the Appearance card.

## Steps to Reproduce

1. Visit settings page
2. See appearance card with Pin Sidebar
3. Reduce screen size until the profile and appearance cards stack on top of each other

## Context

All in all, a few elements on this pace seem to get partially hidden or move around a bit funny, so someone with a keen eye and knowledge of the MUI grid settings just might need to take a peek.

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL 2 Ubuntu 18.04
- Browser Information: Microsoft Edge (Chrome engine)

**Comment by adamdmharvey** [comment]
Hmm... done on purpose?

https://github.com/backstage/backstage/blob/a22fc866eb80d60b4cb35162a0375f58799d15f5/plugins/user-settings/src/components/General/General.tsx#L32-L37

And yep, from the blame view, trace back to the really clearly documented PR (thank you! 👏 ) :
https://github.com/backstage/backstage/pull/3084

What I don't know is... why?  @abhishekjakhar do you recall any context on the removal re: mobile and in this case `!fullScreen`?

**Comment by freben** [comment]
Agreed, this should always be visible!
