### ISSUE TITLE
gitlab (repo) support for Entity File URL 

### ISSUE THREAD

**Issue by asanami01** [backstage/backstage#4302]
Is it possible to specify gitlab repository for an existing entity file URL when registering an existing component to the catalog.

At the moment, it looks like only github repositories can be specified? I've tried a URL to a gitlab repo, but it throws an error:

```
Unable to read url, NotAllowedError: Reading from 'https://<gitlabl>/<repo>/blob/master/quota-api-component.yaml' is not allowed
```

**Comment by freben** [comment]
Hi!

You have to add an entry under `integrations` in your app-config that tells the backend how to interact with your gitlab source.

See the [in-repo app-config](https://github.com/backstage/backstage/blob/master/app-config.yaml#L109) file for some examples. There's also a [config schema](https://github.com/backstage/backstage/blob/master/packages/integration/config.d.ts#L118) to look at.

Closing for now - feel free to reopen if this didn't solve the problem!
