### ISSUE TITLE
TechDocs not working with Self Hosted GitLab community edition server

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#4303]
Reported by @michelv 

https://discord.com/channels/687207715902193673/687235481154617364/804646824232878151

Something might be wrong with `readTree` for self hosted GitLab CE version 13.7.1

**Comment by michelv** [comment]
It looks like the URL that is constructed to download the zip file is not compatible with GitLab's Community Edition.

On a GitLab EE instance, the URL to download a project seems to be `https://HOST/projects/PROJECT_NAME_WITH_NAMESPACE/repository/archive.zip?sha=DEFAULT_BRANCH`.

Whereas on a GitLab CE instance, that URL is `https://HOST/PROJECT_NAME_WITH_NAMESPACE/-/archive/DEFAULT_BRANCH/PROJECT_NAME-DEFAULT_BRANCH.zip`

**Comment by OrkoHunter** [comment]
Closing the issue since the problem was missing `apiBaseUrl` for the gitlab host in app-config.yaml.

But will follow up with more meaningful error when `apiBaseUrl` is undefined.
