### ISSUE TITLE
docs: add integrations section

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#4310]
Would suggest that we add a new top-level section to the docs called "Integrations", where we document how to get set up with GitHub, GitLab, Azure, Bitbucket, and any other that might come 😅 

Could be something like an overview section that explains the basics, where config goes, which parts of Backstage interacts with integrations, etc. Then perhaps one page per integration with more in-depth documentation on configuration of each one, the various flavors, as well as interaction and further configuration for the different core features.

**Comment by adamdmharvey** [comment]
@timbonicus You seem to be working on this one, but the root ask from @Rugvip here is already addressed: there is an integrations section.  Not sure if you're working on an internal story or not, but wondering if we want to close this and pivot it to say separate stories, one per integration, that could possibly allow different teams in the community who may have experience with one or another contribute them back into this section?  Thoughts?

**Comment by timbonicus** [comment]
@adamdmharvey Yeah, seems like this can be closed. I'm working on another PR with a similar treatment for auth providers. Maybe some cross-references between the docs will be sufficient? Or maybe there is a need for "BitBucket all the things" type tutorials/pages that link out to integrations, auth, etc docs.

**Comment by freben** [comment]
I think the "all the things" page could be `integrations/bitbucket/index`.

**Comment by freben** [comment]
I'd say this is done, and is now just an ongoing improvement thing.
