### ISSUE TITLE
scaffolder needs feature parity across all remote git repo types

### ISSUE THREAD

**Issue by n2ygk** [backstage/backstage#4316]
Scaffolder only appears to have first-class support for GitHub repos. GitLab, BitBucket and Azure support is limited and does not include things like:
- repo visibility (being addressed in #4315)
- support for orgs
- specific users given access for private repos
- etc.

## Expected Behavior

If the remote repo service supports the equivalent functionality (most do), then that functionality should be implemented.
 
## Current Behavior

Only the GitHub scaffolder publisher implements complete functionality.

## Possible Solution

Update the gitlab, bitbucket, azure modules.

## Steps to Reproduce

Compare the source code of `plugins/scaffolder-backend/src/scaffolder/stages/publish/{github,gitlab,bitbucket,azure}.ts`

## Context

My organization uses GitLab and I'd like the GitHub equivalent functionality.

## Your Environment

- @backstage/plugin-scaffolder-backend: 0.5.2

**Comment by freben** [comment]
It may be a bit premature to add the help wanted label. We are rewriting things to be a lot more flexible, and in the new system it'll be clearer how to build this out. But if contributions land before then in the old code, we'll probably be able to lift it out into the new framework. So there's still value in contributing, even though it'll soon shift around.
