### ISSUE TITLE
Org Data in Software Templates: Ability to inject org specific data as contextual "extra values" in a template request 

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4325]
Introduce a way to capture org data up front for new teams initially requesting Software Templates such as team name, division etc... 

It would be ideal to be able to reference a shared common file for teams, divisions etc... where an engineer could click on a Select your team drop down menu to select his team name, oh wait it doesn't exist because i never used backstage before, let me add my team by clicking the "Add Team" option in the dropdown so i can add my team and myself so this catalog item gets properly mapped up front! 

## Possible Implementation

I brought this up in discord and master @freben mentioned that we could potentially add a hook that lets you inject org specific data as contextual "extra values" in the templating request, that your templates are free to use if they wish!

**Comment by andrewthauer** [comment]
Out of curiosity, would this team selection be to set the ownership of the generated code component?

**Comment by regicsolutions** [comment]
> Out of curiosity, would this team selection be to set the ownership of the generated code component?

Yep!

**Comment by freben** [comment]
Aha! But these are two slightly different things then, if I read the issue correctly. An owner selector frontend component similar to how you describe it should definitely be built, and it should come with a field type in the schema that anybody can use easily. It would then be one of the regular inputs.

The extra fields that I talked about, was more along the lines of if you wanted to pass along contextual data whether the template explicitly asked for them or not. Like the profile data of the current user that started the scaffolding process, or the name of the app ("Backstage" by default but can be changed), etc etc. Stuff that you know that all your templates will want easy access to.

**Comment by regicsolutions** [comment]
> Aha! But these are two slightly different things then, if I read the issue correctly. An owner selector frontend component similar to how you describe it should definitely be built, and it should come with a field type in the schema that anybody can use easily. It would then be one of the regular inputs.
> 
> The extra fields that I talked about, was more along the lines of if you wanted to pass along contextual data whether the template explicitly asked for them or not. Like the profile data of the current user that started the scaffolding process, or the name of the app ("Backstage" by default but can be changed), etc etc. Stuff that you know that all your templates will want easy access to.

Ah ok, what are your thoughts on adding Group/Team and Domain to the user's profile? Thinking it may make sense to enforce a new user to create a profile on first login (for the exception of name and email which should already be populated by the auth provider) that way we can pull it from the profile? 

From an ownership perspective, there should technically be two levels of ownership right?

1. The engineer who actually registered that component in Backstage 
2. The Group/Team that engineer belongs to

**Comment by freben** [comment]
> Ah ok, what are your thoughts on adding Group/Team and Domain to the user's profile? Thinking it may make sense to enforce a new user to create a profile on first login (for the exception of name and email which should already be populated by the auth provider) that way we can pull it from the profile?

https://github.com/backstage/backstage/issues/4089

There's a bit of a conflict here - we expect backstage to get its profile/user/groups source data from external sources, not to supply that outwards.

A user will have any number of group memberships. These should be fetched from an external source such as LDAP, or an in-house solution, or what you happen to have.

By domain, do you mean the entity kind `Domain`?

What could be useful, is to let users remember their defaults between sessions. For example when creating a new component using the wizard, it could let you prefill your regular values. A user settings plugin to the backend could do something like that - it's something we'll need to build either way.

> From an ownership perspective, there should technically be two levels of ownership right?
> 
> 1. The engineer who actually registered that component in Backstage
> 2. The Group/Team that engineer belongs to

We focus on modeling the second one. That group name is what you will fill in the `owner` field with. You are automatically an owner by virtue of being a member of that group.

**Comment by adamdmharvey** [comment]
@andrewthauer did you mean to assign us?  🤔 😊 

![image](https://user-images.githubusercontent.com/33203301/106406361-0a94ba80-6407-11eb-8e05-cb0d318b8c76.png)

**Comment by andrewthauer** [comment]
No 😥. Not sure how that happened. Sorry.

**Comment by vaimo-magnus** [comment]
I have similar request... 

Ability to get the current user from custom scaffolder action. 

It could be enough to be able to add custom template fields (for example a hidden field, where we could add add the email of the current user), of course it would be nice if we did not need to and this information could be fetch from backend directly...  

but i think in terms of flexibility this would allow developers to add what they require to be passed.

**Comment by benjdlambert** [comment]
@vaimo-magnus I think that these are separate issues. Would you mind creating a different ticket for your request as they won't be solved by the same solution :)
