### ISSUE TITLE
Scaffolder Workflow Automation Engine 

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4326]
Just wanted to throw out a crazy idea! Thinking years down the road when you have hundreds of Software Templates with a wide range of hooks and triggers... it could start to get messy to manage as use cases become more complex.

I started playing around with a node based open-source workflow automation tool, built in TypeScript called [n8n](https://github.com/n8n-io/n8n) that has over [200 integrations](https://n8n.io/integrations) that would be extremely useful to use once you drop that shinny boilerplate repo into your target storePath such as invoking a [lambda function](https://n8n.io/integrations/n8n-nodes-base.awsLambda) or even looking at it from an operational view where Site Reliability Engineers have the ability to drag in a [PagerDuty](https://n8n.io/integrations/n8n-nodes-base.pagerDuty) node to automatically trigger an incident when a component goes offline.

**Comment by Rugvip** [comment]
Could be interesting. What kind of integration do you have in mind? Something like being able to trigger a n8n workflow from a scaffolder templating run?

**Comment by regicsolutions** [comment]
Yep! one use case that we have right now is having the ability to trigger a [lambda function](https://n8n.io/integrations/n8n-nodes-base.awsLambda) once a repo is generated successfully to create a Jenkins job that maps to that generated repo and register that app in our central [PostgreSQL](https://n8n.io/integrations/n8n-nodes-base.postgres) CI/CD database, if a database was selected in the template, we would create that database in RDS, get that app setup in Datadog for monitoring and lastly, if it was a "Golden Path" template we would create a namespace/role binding in OpenShift! 

This could be defined as a re-usable baseline workflow that could be built on for new software templates. Engineers from other teams can contribute to building there own event based "nodes" where you are now able to integrate with other endpoints on an event basis, which is pretty powerful in my option!

**Comment by Rugvip** [comment]
@regicsolutions Alright, linking this to #2771, as I think it will address this at a lower level. The intention is that it will add the building blocks needed for this to be implemented on top of
