### ISSUE TITLE
Jenkins Plugin - Add Broader Support outside of just Github

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4328]
As mentioned in issue [#3975 ](https://github.com/backstage/backstage/issues/3975) The current Jenkins Plugin has only been tested and known to work with GitHub, this request is to add broader support for all Git-based version control solutions and support the generic usage of Jenkins freestyle and pipeline type projects.

**Comment by n2ygk** [comment]
@fox32 @freben I've tested and this works with GitLab Enterprise and Jenkins on-prem.
It's a little confusing using the name `jenkins.io/github-folder` in the annotation. Maybe this could be changed to `jenkins.io/job` or `jenkins.io/project` which are the Jenkins terms. I imagine it will work similarly with any other git SCM that the Jenkins [git plugin](https://plugins.jenkins.io/git/) supports.

![image](https://user-images.githubusercontent.com/4356471/108756657-cdf44480-7516-11eb-866a-a7c59c2639ac.png)


![image](https://user-images.githubusercontent.com/4356471/108756818-08f67800-7517-11eb-8a6d-ea314b55424e.png)

**Comment by Fox32** [comment]
Yeah, the name is definitly missleading

**Comment by adamdmharvey** [comment]
Agree re: point on confusion.

https://www.jenkins.io/doc/book/glossary/

Note "job" is now deprecated, in favor of project according to their official glossary.

Maybe it's enhanced to support both names `jenkins.io/project` and legacy `jenkins.io/github-folder`, and log a warning if a deprecated annotation is found (maybe even expose this in the frontend UI), and give it a month before then formally deprecating it.   It's not technically even in the [stability index](https://backstage.io/docs/overview/stability-index#docsNav) at the moment.

**Comment by freben** [comment]
Sounds like a plan.

Is just a single project string enough? Thinking of... Which ones are they? Bitbucket and/or hosted azure? ...that have a bit of their own naming scheme, maybe with three levels instead or two.

Sorry for being vague, don't recall the exact details right now :)

**Comment by n2ygk** [comment]
@freben The project slug is Jenkin's, not the git repo's. They don't have to match at all.
For example, for Jenkins project `ac45/django-training-multibranch` the git repo is `https://gitlab.cc.columbia.edu/cuit-ent-arch/django-training.git`:

![image](https://user-images.githubusercontent.com/4356471/108771708-07827b00-752a-11eb-964b-0476a5fe3dcb.png)

**Comment by n2ygk** [comment]
hmm maybe the annotation name should be `jenkins.io/project-slug` to be consistent with how github annotations are given?

**Comment by freben** [comment]
That could make sense yeah - symmetric with the other well known annotations and leaves room for expansion. But if it is known that it's definitely just gonna be a name, eg if that's all that jenkins' model supports, then it's fine to keep the other name

**Comment by regicsolutions** [comment]
Agreed! GitHub icon should probably be updated to a Jenkins or git icon as well? 

https://simpleicons.org/?q=Jenkins 

Believe a GitHub hyperlink is also referenced when you drill down into a build, should maybe update that to what's being used in the app-config like the catalog-import plugin does?

**Comment by sfatzinger** [comment]
Hi! Our org would like to help contribute to this issue if possible. Our Jenkins configuration is currently setup to use Multibranch Pipelines (as opposed to Organizational Folders). My first thought was to add config to this plugin to allow the user to opt into a given Jenkins mode, and provide implementation in the plugin code accordingly. Does this seem like a reasonable approach or are we way off here?

Multibranch Jenkins configuration uses a notion of "managed masters" (their term), which I have been able to get a naive solution working locally by threading in the name of the "master" extracted from the annotation value (of the form: `master/project/resource-name`), and destructured in `useProjectSlugFromEntity`. This then is leveraged in `getClient()` to concatenate to the baseProxy url. While this definitely isn't a scalable approach, the changes in `0.4.0` of the plugin seem to have broken that altogether, so looking for any guidance here.

Also, if this all sounds completely off base, please let me know :)

**Comment by goober** [comment]
@sfatzinger Have you had any more progress around this issue lately?

**Comment by regicsolutions** [comment]
@goober Any interest in getting assigned to this one?

**Comment by emoreth** [comment]
Hello! 

I'm trying to make this work for the last few hours and decided to ask some clarifying questions here before I move forward so I don't potentially loose my time.

I was able to work it out with Jenkins API so I can call both (maybe all) types types of jobs in a single query. My main problem now relies on this plugin heavily relying on `lastBuild` object. While this is fine for WorkflowMultiBranchProject (github one, with dynamic projects being created as jobs for each branch) , it doesn't work for WorkflowJob's since there is always a single project with multiple builds. 

With that in mind, I believe I have 2 major options to work with:
- To create an interface/facade for all the information we want exposed to frontend, and stop sending almost all Jenkins API response to the frontend. In this method both/all types of projects would be required to comply with a single data format to be exposed to the frontend
- Or to keep Jenkins API information being sent to frontend and figuring it out in FE where to get information from. (e.g: `obj.lastBuild.number || obj.number`). This option gives more space for people to interact with Jenkins data since almost all information is forwarded to FE. (Unsure how sensitive that information could be).


What do you think would be the best option here?

**Comment by thaicomcs1** [comment]
@emoreth hi are you still working on the issue?

**Comment by mark-reidman-intel** [comment]
> Hello!
> 
> I'm trying to make this work for the last few hours and decided to ask some clarifying questions here before I move forward so I don't potentially loose my time.
> 
> I was able to work it out with Jenkins API so I can call both (maybe all) types types of jobs in a single query. My main problem now relies on this plugin heavily relying on `lastBuild` object. While this is fine for WorkflowMultiBranchProject (github one, with dynamic projects being created as jobs for each branch) , it doesn't work for WorkflowJob's since there is always a single project with multiple builds.
> 
> With that in mind, I believe I have 2 major options to work with:
> 
> * To create an interface/facade for all the information we want exposed to frontend, and stop sending almost all Jenkins API response to the frontend. In this method both/all types of projects would be required to comply with a single data format to be exposed to the frontend
> * Or to keep Jenkins API information being sent to frontend and figuring it out in FE where to get information from. (e.g: `obj.lastBuild.number || obj.number`). This option gives more space for people to interact with Jenkins data since almost all information is forwarded to FE. (Unsure how sensitive that information could be).
> 
> What do you think would be the best option here?

Hi, Will you be abel to share your code that pull jenkins info, we are workign with pipelines and I'm looking at modifying jenkins plugin to get basic info of the last build

**Comment by rahulsaw2003** [comment]
Hi, I am facing issues with integrating jenkins for multiple global instances which are defined for different jobs. Please help me out!
