### ISSUE TITLE
catalog component readme doesn't include embedded images

### ISSUE THREAD

**Issue by n2ygk** [backstage/backstage#4345]
This is a pretty minor nit, but the catalog/default/component/_component-name_ pulls in the README.md but not
any referenced images that are pulled in, e.g. via `![alt-text](docs/media/CCbyncsa4.0.png "CC BY-NC-SA 4.0")`

## Expected Behavior

The "mini" README should render completely

## Current Behavior

Image references are rendered as broken images:
![image](https://user-images.githubusercontent.com/4356471/106511134-d15b5980-649d-11eb-8160-8eda4d682b63.png)

## Steps to Reproduce

1. Add this component: https://github.com/columbia-it/django-jsonapi-training/blob/master/catalog-info-github.yaml
2. Go to http://localhost:3000/catalog/default/component/django-jsonapi-training

## Your Environment

- "@backstage/catalog-client",  "version": "0.3.5",

**Comment by adamdmharvey** [comment]
@n2ygk Is this a report against RoadieHQ GitHub Insights plugin (https://github.com/RoadieHQ/backstage-plugin-github-insights)  by chance? if so, may need to pivot an issue into that repo, as Jira isn't a part of the Backstage core (this repo).  I may be wrong, but though I'd note it!

**Comment by n2ygk** [comment]
> @n2ygk Is this a report against RoadieHQ GitHub Insights plugin (https://github.com/RoadieHQ/backstage-plugin-github-insights) by chance? if so, may need to pivot an issue into that repo, as Jira isn't a part of the Backstage core (this repo). I may be wrong, but though I'd note it!

Yes, it could be. Not using Jira anywhere though. It's just pulling in a README from github.

**Comment by adamdmharvey** [comment]
Sorry, I wrote JIRA, I meant "github insights" 😁.

**Comment by n2ygk** [comment]
Yes, the readme shows up on the Code Insights and and Overview tabs. I'll move this over there.
