### ISSUE TITLE
user-settings: Link to settings in side bar does not work

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4362]
## Expected Behavior

When clicking "Settings" at the bottom left of Backstage, the user should be taken to the user settings page.

## Current Behavior

From latest code on master on 2 Feb 2021, I've found a few weird situations where the routing to the settings doesn't quite work.  However, if I manually change my URL to force the route `/settings`, the settings page loads up fine. There seems to be some situation where some aspect of the catalog "breaks" my catalog route, as off a fresh install I'm able to get to the settings from clicking it. But not once clicking around in the catalog itself.

## Steps to Reproduce

1. Open Backstage
2. Open a SPECIFIC entity (not the catalog main page)
3. Click Settings at bottom left
4. Get routed to catalog homepage

Also, ONCE on this "catalog" page after being redirected from Settings, you can not get to settings anymore. The route to it seems to have been broken somehow.

## Context

Two recent PRs in this space that might possibly be at play, though I'm not sure:

https://github.com/backstage/backstage/pull/4341 - new composability routing
https://github.com/backstage/backstage/pull/4348 - user settings Pin sidebar panel fix

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by adamdmharvey** [comment]
Have Chrome DevTools with react aligned, and nothing is being spit out.  I thought I was confused, because I reset everything and settings panel DID work. But then I managed to clobber it again by doing something, and best I can tell is it gets clobbered when hitting an entity page.

**Comment by Rugvip** [comment]
Fixed in #4363. The settings plugin was using a bit of an unusual sidebar item setup compared to other plugins, so missed that interaction

**Comment by adamdmharvey** [comment]
Tested `rugvip/fixxings` locally and it fixed the issue I see; what turnaround time!!! 👏 👏 👏 😁 cheers sir!
