### ISSUE TITLE
Support configurable committer Name and Email

### ISSUE THREAD

**Issue by tsjnsn** [backstage/backstage#4364]
## Feature Suggestion

Support configurable committer name and email for the scaffolder plugin.

## Possible Implementation

default to current settings, add option in config yaml to override

## Context

The Scaffolder currently commits and pushes its changes with a static name and email. This is not compatible with Gitlab setups which require commit authors to be valid Gitlab users:

> Check whether author is a GitLab user
Restrict commits by author (email) to existing GitLab users

https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/stages/publish/helpers.ts#L55

The Scaffolder fails with "pre-receive hook declined" if that Gitlab setting is active

**Comment by benjdlambert** [comment]
Closing as duplicate tracked here: https://github.com/backstage/backstage/issues/6217
