### ISSUE TITLE
Unable to build docker image based on current documentation

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#4366]
## Expected Behavior

The docker image should get built without any errors

## Current Behavior

When we run `docker build -t example-deployment .` using the documentation from here: https://backstage.io/docs/getting-started/deployment-other using a clone of this repo we are running into the following errors, sorry there is a lot:

[5/5] Building fresh packages...
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/app/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /app/node_modules/keytar
Output:
prebuild-install WARN install No prebuilt binaries found (target=14.15.4 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.4 | linux | x64
gyp http GET https://nodejs.org/download/release/v14.15.4/node-v14.15.4-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.15.4/node-v14.15.4-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.15.4/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.15.4/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/app/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/node_modules/keytar/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/app/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/14.15.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/14.15.4',
gyp info spawn args   '-Dnode_gyp_dir=/app/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/14.15.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/app/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.19.121-linuxkit
gyp ERR! command \"/usr/local/bin/node\" \"/app/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /app/node_modules/keytar
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok"

Then it runs `tsc` which ends up with 61 error.

Here is the full output: [docker-build-error-log.txt](https://github.com/backstage/backstage/files/5914807/docker-build-error-log.txt)

## Possible Solution

I really don't know what to suggest, this is a little out of my skill set :(

## Steps to Reproduce

This assumes that you are running this using a clone of the Backstage repo which already has the proper `.dockerignore` file in the root

1. Create a Dockerfile in the root of the repo with the same content from here: https://backstage.io/docs/getting-started/deployment-other
2. Then run `docker build -t example-deployment .`

Notice that you have the following errors:

[5/5] Building fresh packages...
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/app/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /app/node_modules/keytar
Output:
prebuild-install WARN install No prebuilt binaries found (target=14.15.4 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.4 | linux | x64
gyp http GET https://nodejs.org/download/release/v14.15.4/node-v14.15.4-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.15.4/node-v14.15.4-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.15.4/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.15.4/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/app/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/node_modules/keytar/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/app/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/14.15.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/14.15.4',
gyp info spawn args   '-Dnode_gyp_dir=/app/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/14.15.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/app/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.19.121-linuxkit
gyp ERR! command \"/usr/local/bin/node\" \"/app/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /app/node_modules/keytar
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok"

Then it runs `tsc` which ends up with 61 error.

Here is the full output: [docker-build-error-log.txt](https://github.com/backstage/backstage/files/5914807/docker-build-error-log.txt)

## Context

Just trying to take advantage of the multistage build and being able to run the straight docker command will simplify our build pipeline

## Your Environment

We mostly use Windows 10 so I'm not sure if that has any impact on this. Node is 14.15

**Comment by adamdmharvey** [comment]
I have a feeling this isn't an issue with the documentation, per se, but a missing library in your build env.  If you're on Windows 10, are you using WSL?  Ubuntu 18.04 or another image?

If I run this on my Windows 10 WSL2 Uuntu 18,04, I can see I already have the library installed:

```
$ apt list --installed | grep libsecret

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libsecret-1-0/bionic,now 0.18.6-1 amd64 [installed,automatic]
libsecret-1-dev/bionic,now 0.18.6-1 amd64 [installed]
libsecret-common/bionic,now 0.18.6-1 all [installed,automatic]
```

If you also have Ubuntu, may I suggest a `sudo apt install libsecret-1` and then see if the build works after that?

I'd assume also cloning the repo locally, and then doing a `yarn build` would trigger this SAME error (without Docker).

Maybe give those a shot and see if that helps?

**Comment by awanlin** [comment]
@adamdmharvey thanks for taking the time to look at this. I agree, it's not an issue with the documentation. I'm not using WSL.

I've gone through the following steps to retest this today:

1. Completely deleted my clone of the backstage repo
2. Did a fresh clone of the backstage repo
3. Ran yarn install, yarn tsc, and yarn build all without any errors
4. Then added the Dockerfile as per the documentation
5. Then ran `docker build -t example-deployment .`

I got all the same errors before, these errors are all taking place "in" the docker container. If you look at the log file you'll see what I mean, it's just super long to post so here's the file:
[docker-build-error-log.txt](https://github.com/backstage/backstage/files/5935357/docker-build-error-log.txt)

**Comment by Rugvip** [comment]
@awanlin Looks like you're missing the `COPY plugins plugins` in the first stage, causing plugin dependencies not to be installed

**Comment by awanlin** [comment]
@Rugvip, good call, totally missed that. When I try with the `COPY plugins plugins` line uncommented I get this error:

Step 13/22 : RUN yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies
 ---> Running in 5507f7a77886
yarn run v1.22.1
error Command "backstage-cli" not found.

Here's the full log, note that keytar error is still in there: [docker-build-error-log-with-plugins.txt](https://github.com/backstage/backstage/files/5944881/docker-build-error-log-with-plugins.txt)

**Comment by Rugvip** [comment]
Oh hmm, I think it's because the CLI `bin` script isn't available during the install, so it never gets added to node_modules. It may be possible to work around by running another install after the `COPY . .`, but tbh that dockerfile is not mean to be run in the main repo. In a repo created with `@backstage/create-app` the CLI will be installed as a dependency instead of part of the source tree.

**Comment by awanlin** [comment]
Ok, thanks. We'll keep using `yarn docker-build` as that is working fine for us. Just felt like doing it this way would streamline our process. 

Should I close this issue then?

**Comment by Rugvip** [comment]
@awanlin Oh but then you might be interested in this piece: https://backstage.io/docs/cli/commands#backendbundle :grin:

Docker deployment docs very much needs a bit of an update there though : /

**Comment by awanlin** [comment]
Sorry for the slow follow up, thanks for that link, when I have more time I'll see how we might be able to use that.

I'm going to close this issue though, thanks for all the help everyone :)
