### ISSUE TITLE
Helm chart installation with additional plugins

### ISSUE THREAD

**Issue by asanami01** [backstage/backstage#4376]
This guide describes a helm chart installation on kubernetes:

https://github.com/backstage/backstage/blob/master/contrib/chart/backstage/README.md

Are there any instructions on adding plugins from https://backstage.io/plugins to the deployment?

**Comment by dtuite** [comment]
@asanami01 Plugins are added before the build step. The basic idea is that you:

1. Scaffold a Backstage application for your organisation using the provided `create-app` command line client.
2. Edit the code of this application to add the plugins you want to use.
3. Build that into a Docker image.
4. Deploy it with helm.

I will assume that answers the question and close this issue. Please reopen if you need more advice.
