### ISSUE TITLE
Welcome Plugin: enable-welcome-box Feature Flag not working

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4377]
## Expected Behavior

When enabling the welcome-box the welcome plugin box should be shown on home page

![image](https://user-images.githubusercontent.com/6157895/106781720-5b7afd80-6617-11eb-9b38-d38163afa36f.png)

No Welcome Box - 

![image](https://user-images.githubusercontent.com/6157895/106781900-93824080-6617-11eb-96e8-6740cbe83fb9.png)

## Current Behavior

Welcome box is not showing 

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12): Node12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10
- Browser Information: Chrome

**Comment by Fox32** [comment]
Not sure if this is a bug. I don't think that the welcome banner was ever related to that feature flag.

The welcome banner was removed recently as there isn't really a use in the default app https://github.com/backstage/backstage/pull/4193 .

Personally, if you need some kind of banner to welcome new user, I would recommend to copy that code into your local app. We did that, it works well and we are even able to customize it to our needs.

**Comment by Fox32** [comment]
We could remove the feature flag registration there, or might even delete the whole plugin? Right now it doesn't seem to have a purpose except being a placeholder?

**Comment by regicsolutions** [comment]
hmm the feature flag worked before the last release.  I think it is nice to have, especially when you are about to go live. Thanks for the suggestion, i will try copying the code into the front-end.

**Comment by adamdmharvey** [comment]
Yeah, there's a panel on the /welcome plugin itself which when you hide sets a COOKIE. But it's not a feature flag.

I agree I too thought this was confusing at first, but since the welcome plugin is sort of unused now (it USED to be the homepage, now the homepage is the catalog) I forgot about it.

I agree with @Fox32 , some of this likely just needs to be better refactored for sure!

**Comment by adamdmharvey** [comment]
And sorry, I should have been more clear - the screen shot you show where the original "intro to backstage" panel was shown right above the entity list is shown is on the **catalog plugin** and is cookie based (not feature flag), NOT the welcome plugin, which is the one I meant is cookie based.  So the feature flag WORKS, but it shows/hides a panel on `/welcome` which is different than the one you see in that screenshot.

So by deprecating the welcome, the feature flag would be hidden. But what might be useful is converting the intro as well to be a feature flag.

I'll throw a quick PR in to help clear up SOME of this, at least to try to reduce a bit of confusion.

**Comment by adamdmharvey** [comment]
@regicsolutions With the PR from early Feb merged and closed, the referenced feature flag has been removed.  I think the confusion it introduced is no longer there, even if perhaps the root goal of your expectation - that that flag controlled the "welcome to Backstage" sort of feature may not be.

I think I'm going to close this one as nailed, but if you think there's still more work or a useful enhancement here, might you be willing to spin up a new issue with a specific expectation/ask?  It might help build a better "new user experience" picture.  Hope that is ok!
