### ISSUE TITLE
Backend Dockerfile using Alpine

### ISSUE THREAD

**Issue by taras** [backstage/backstage#4390]
<img width="1117" alt="backstage-image" src="https://user-images.githubusercontent.com/74687/106917789-9b54ea00-66d6-11eb-928c-885b57ee965a.png">

We're using Backstage in an enterprise environment where Twistlock is used to assess the security of containers. Official Node.js Docker images are notorious for [reporting many security](https://github.com/nodejs/docker-node/issues/787) vulnerabilities. For this reason, our organization uses Alpine as a base for the majority of containers which have much fewer vulnerability reports in the base operating system.

Scaffolder uses Alpine already, but the base container created with `@backstage/create-app` is using [Ubuntu Buster](https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/packages/backend/Dockerfile#L1). 

## Feature Suggestion

Either provide an alternative to Ubuntu that uses Alpine or replace Ubuntu with Alpine base image.

## Possible Implementation

I tried to do this myself several times but I kept getting segfault errors. I believe the Backstage core team is aware of this.

**Comment by taras** [comment]
@Rugvip informed me that some native dependencies changed in a recent version of Backstage. I'm going to try upgrading to the latest version and report back.

**Comment by awanlin** [comment]
Would it be possible to also include an example Dockerfile with the mkdocs and cookiecutter dependencies working under Alpine? Like this one: https://github.com/backstage/backstage/blob/master/contrib/docker/kubernetes-example-backend/Dockerfile

**Comment by backjo** [comment]
fwiw, we're using this Dockerfile based on Alpine for our UI and Backend deployments

```dockerfile
FROM node:14-alpine as builder
WORKDIR /usr/src/app
RUN apk add make gcc g++ python build-base cairo-dev jpeg-dev pango-dev giflib-dev
COPY yarn.lock package.json ./
COPY app-config.yaml ./
COPY packages/app/package.json ./packages/app/package.json
COPY packages/backend/package.json ./packages/backend/package.json
RUN yarn install --frozen-lockfile
COPY packages/app ./packages/app
COPY packages/backend ./packages/backend
COPY tsconfig.json ./
COPY lerna.json ./
RUN yarn tsc && yarn build

FROM builder as backend
CMD ["node", "packages/backend", "--config", "app-config.yaml"]

FROM artifactory.legalzoom.com/docker-remote/nginx:mainline as ui

# The purpose of this image is to serve the frontend app content separately.
# By default the Backstage backend uses the app-backend plugin to serve the
# app from the backend itself, but it may be desirable to move the frontend
# content serving to a separate deployment, in which case this image can be used.

# This dockerfile requires the app to be built on the host first, as it
# simply copies in the build output into the image.

# The safest way to build this image is to use `yarn docker-build:app`

RUN apt-get update && apt-get -y install jq && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/app/packages/app/dist /usr/share/nginx/html
COPY docker/default.conf.template /etc/nginx/conf.d/default.conf.template
COPY docker/run.sh /usr/local/bin/run.sh
CMD run.sh

ENV PORT 80
```

**Comment by JacobValdemar** [comment]
@backjo Does that Dockerfile include enough mkdocs/techdocs and cookiecutter dependencies, so that they can run locally in the container?
