### ISSUE TITLE
feat: Generate map of an entire system

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4394]
## Feature Suggestion

Using the `<DependencyGraph>` component, visualize a map of an entire system.

![image](https://user-images.githubusercontent.com/33203301/106936396-82563400-66ea-11eb-8cde-a09fa77d2dab.png)

In @Fox32 's #4392, among other PRs, we're really starting to flesh out the linkages that the individual elements in the catalog include.  We're getting tables, pages in the `org` plugin, info on the entity `AboutCards`, etc.

The current system model is documented here: https://backstage.io/docs/features/software-catalog/system-model#ecosystem-modeling

Visualizing this model representing the as-is state, provides the following benefits:
* Shows the current state of the system, as opposed to a ideal intended architecture
* Allows new users to more easily understand how all of the components fit together
* Provides those performing operations a better understanding of impacts of service degredation
* Identifies gaps in an intended architecture: are we missing an API? maybe it exists but it hasn't yet been added to the catalog? etc.

This example just uses this rough code:

```
 const exampleNodes = [
    { id: 'supporting-functions-domain' },
    { id: 'reporting-system' },
    { id: 'service-a' },
    { id: 'service-b' },
    { id: 'service-b' },
    { id: 'corporate-reporting-website' },
    { id: 'api-a' },
    { id: 'api-b' },
  ];
  
  const exampleEdges = [
    { from: 'reporting-system', to: 'supporting-functions-domain', label: 'part of' },
    { from: 'api-a', to: 'reporting-system', label: 'part of' },
    { from: 'api-b', to: 'reporting-system', label: 'part of' },
    { from: 'service-a', to: 'reporting-system', label: 'part of' },
    { from: 'service-b', to: 'reporting-system', label: 'part of' },
    { from: 'service-b', to: 'reporting-system', label: 'part of' },
    { from: 'corporate-reporting-website', to: 'reporting-system' },
    { from: 'corporate-reporting-website', to: 'reporting-system', label: 'part of' },
    { from: 'service-a', to: 'api-a', label: 'provides' },
    { from: 'service-b', to: 'api-b', label: 'provides' },

  ];

  ... snip ...

  return (
            <DependencyGraph
                nodes={exampleNodes}
                edges={exampleEdges}
                paddingX={50}
                paddingY={50}
                direction={'BT'}
              />
  );
```

## Possible Implementation

* I feel like this should be front and center as a simple way to digest a system, before drilling down further into tables of information, so maybe visible on the main System card in the `org` plugin?  And/or, potentially exposable by the new `explore` plugin in some way as well, but I'm sure it can be iterated. But to be honest, once the component itself exists and is put into the code base, the project can continue to iterate as it finds it's ideal home.
* Each element in the graph should ideally be clickable, but if not in the first iteration I think that's fine.

**Comment by andrewthauer** [comment]
Was just thinking about this as well 😄 .

Before backstage, I built a custom tool that could generate a system map with dependencies based on some data collected from our infrastructure setup. As pointed out the Backstage catalog now provides all the core parts to be able to do this in a very nice way. I also just found a new API in Datadog that can be used to extract service dependencies based on APM tracing - https://docs.datadoghq.com/api/latest/service-dependencies/.

I'm wondering, would the edges be based on the API consumes/provides relationships that are attached to components and/or systems? I've been toying with the idea of taking the DD service dependency data and mapping into the catalog entities. I'll pose the question, do we want to enforce having an API to show a system dependency relationship? In my example of automatically creating these dependencies via `apm` data this would likely require making an artificial `API` just to model the relationship. This might be ok, but also feels a little strange.

**Comment by adamdmharvey** [comment]
I'll admit, that even though my corporate technical doctrine (see DXC's Technical Doctrine: https://www.dxc.technology/innovation/insights/147802-dxc_s_technical_doctrine 🔌 /plug 😉  ) defines, "Everything must have an externalizable service interface", I work with many teams which haven't yet been able to implement this. So I would hope that having an API doesn't become a requirement in this visualization, but absolutely should be exposed if it exists (and could be enhanced as you say with plugins able to add on additional info into the catalog).

And in fact, as we make this more complex in the future, I can envisage we could add on some visual elements on the nodes to better identify them (like a globe icon for web sites 🌏 , or a plug for API 🔌 , etc, drawn on the map)

**Comment by Fox32** [comment]
Btw, I already had a PR with the dependency graph in the past, very similar to the picture above but we removed it again. Here is the code: https://github.com/backstage/backstage/compare/master...SDA-SE:feat/api-docs-relation-card

We have a ticket in our internal backlog for this topic, I could take a look.

**Comment by Fox32** [comment]
Btw, this also has some requirements on the backend. We need a more efficient way of reading related entities, in the best case with some kind of "relatation depth". Till now that is something I thought we will probably not be added to the REST API but would only be part of a graphql API.

**Comment by freben** [comment]
Naive hot take: The dataset is generally small enough to just get _everything_ and filter + process it in memory :) At least for a first stab at this.

**Comment by adamdmharvey** [comment]
I took a very quick stab at this yesterday, and wanted to just share here for feedback. I'd likely need to submit a draft PR for collaboration as the more advanced JavaScript programming is a bit beyond my skills.

![image](https://user-images.githubusercontent.com/33203301/107384420-f3696300-6abf-11eb-809f-67b17cf8a32f.png)

* In the picture, the map is still mostly static but I do generate the system name dynamically as a start.
* This includes a new `<SystemDiagram>` card. At the moment, I placed it in `plugin-catalog` - does that make sense?
* To freben's point re hot take, I can see two ways of doing this, any thoughts on either?
  * Use the `getEntityRelations()` helper in a loop, collecting the relations suffixing results to the nodes/edges arrays.
  * Use the `getEntities()` for everything in a massive catalog in mem, and then loop through that (is this what you were eluding to @freben ?)

It's for sure that last point I'll be weak on, and to be fair what I did so far is the "easy part".  If others are willing, could open up a branch in the repo rather than my fork and throw up what I've got to see if it sticks. There's free 🍕 in it for you. 😁

**Comment by freben** [comment]
Yeah, to get it all. The catalog API also supports fetching just [parts of each entity](https://github.com/backstage/backstage/blob/master/packages/catalog-client/src/types.ts#L21) - such as the relations, and the name etc, whatever is necessary to draw the graph. At least that makes the response a bit smaller.

**Comment by adamdmharvey** [comment]
So I can get simple filters to work, and the field identification works great (esp because right now this MVP is super simple: only looking at the `metadata.name`!) but having difficulty with more complex ones, and/or maybe `catalogApi.getEntities()` doesn't fully support complex filters?.

So for example, this works just fine to get a system node:

```
filter: {
  kind: ['system'],
  'metadata.name': entity.metadata.name,
}
```

But I tried to do something a bit more complex, i.e. pull in multiple filters into a single array, and can't figure out the permutation to get it to work.  I attempted a few versions of this without luck:

```
filter: {
  [
    kind: ['system'],
    'metadata.name': entity.metadata.name,
  ],
  [
    kind: ['component'],
    'spec.system': entity.metadata.name,
  ]
}
```

Couldn't find any complex filter examples in the repo at the moment.  Any guidance from the group?

**Comment by freben** [comment]
@adamdmharvey An important point here is that you should always consume the `relations` structure where appropriate. The system relation cannot be taken out of the `spec` since it might be populated in any number of ways, and since the actual resolution of the full entity kind + name + namespace triplet should be done server-side to be sure that defaults etc are obeyed consistently.

Unfortunately the `filter=` feature does not yet support querying for relations. We have been debating back and forth what it should look like. So you will have to resort to getting them all and filter in memory instead.

**Comment by andrewthauer** [comment]
@adamdmharvey - This is really neat 🌮! We've been slowing starting to use [C4 Model](https://c4model.com/) to describe systems and I think the Backstage ecosystem model maps quite nicely to the context/container/component diagrams within C4. Been meaning to try to model out one our our systems in the catalog. Would love to collaborate and/or help out on this 😄.

**Comment by adamdmharvey** [comment]
Awesome. Let me push up what I've got now then, and maybe we can align together on it.

**Comment by adamdmharvey** [comment]
So no PR yet. Played around yesterday and honestly wrote and re-wrote a few times, trying some `.map()` stuff, and sort of ended up with something that only partially works but is very raw, newbie programmer read-top-bottom.  And still only PARTIALLY works.

What I found interesting is that not all cases have a clean relationship to a system (`relation.type='system'`) AND `spec.system: entity` properly defined - reading the System Model info in the docs, I thought it would have always have been both enforced by the catalog model (one or other inferred), but I may be wrong there?

Anyway, here's the (awful) code I ended up with. Before firing my PR, welcome pointers/suggestions/comments like "why the heck did you do that you dummy, it could have been done in one line like so", etc.  😁 

I also played around with all lowercase, as there are cases where the kinds are mixed, and for sure that could be pulled out into a utility function but this was just quick hacking.

Goal out of this is to end up with a properly formatted `systemNodes` object of entities with `{ id: 'node-name' }` and then edges with `{ from: 'source-entity', to: 'dest-entity', label: 'partOf' }`, etc.

```
 let systemNodes = [];
  let systemEdges = [];

  if (catalogResponse && catalogResponse.items) {
    for (let catalogItem of catalogResponse.items) {

      // Process system
      if (catalogItem.kind === 'System' && catalogItem.metadata.name === entity.metadata.name) {
        systemNodes.push( { id: catalogItem.kind.toString().toLowerCase() + ':' + catalogItem.metadata.name} );
        continue;
      }

      //console.log(catalogItem);
      // Process anything assigned to the system
      if (catalogItem.spec?.system && catalogItem.spec.system === entity.metadata.name) {
        systemNodes.push( { id: catalogItem.kind.toString().toLowerCase() + ':' + catalogItem.metadata.name } );
        systemEdges.push( { from: catalogItem.kind.toString().toLowerCase() + ':' + catalogItem.metadata.name, to: 'system:' + entity.metadata.name, label: 'spec\'d'})
      }

      // Process relationships
      if (catalogItem.relations) {
        for (let relation of catalogItem.relations) {
          if (relation.target.kind === 'system'
            && relation.target.name === entity.metadata.name) {
            systemNodes.push( { id: catalogItem.kind.toString().toLowerCase() + ':' + catalogItem.metadata.name } );
            //let myArray = ['Component','Resource','API','Domain'];
            //if (myArray.includes(catalogItem.kind)) {
              if (relation.type == 'partOf') {
                systemEdges.push({
                  to: catalogItem.kind.toString().toLowerCase() + ':' + catalogItem.metadata.name,
                  from: relation.target.kind.toString().toLowerCase() + relation.target.name,
                  label: relation.type,
                });              
              }
              if (relation.type = 'hasPart') {
                systemEdges.push({
                  from: relation.target.kind.toString().toLowerCase() + relation.target.name,
                  to: catalogItem.kind.toString().toLowerCase() + ':' + catalogItem.metadata.name,
                  label: relation.type,
                });              
              }
            //}
          }
        }
      }

    }
```

**Comment by freben** [comment]
Haven't looked at the code yet, but a couple answers to the rest:

> What I found interesting is that not all cases have a clean relationship to a system (`relation.type='system'`) AND `spec.system: entity` properly defined - reading the System Model info in the docs, I thought it would have always have been both enforced by the catalog model (one or other inferred), but I may be wrong there?

You mean [`relation.type=partOf`](https://backstage.io/docs/features/software-catalog/descriptor-format#specsystem-optional) I presume.

The system [is](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/schema/kinds/Component.v1alpha1.schema.json#L42) indeed [optional](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/kinds/ComponentEntityV1alpha1.ts#L37)!

> I also played around with all lowercase, as there are cases where the kinds are mixed, and for sure that could be pulled out into a utility function but this was just quick hacking.

There's [this one](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/entity/ref.ts#L227), but maybe not sufficient here.
