### ISSUE TITLE
Add indices on `locations_id` columns  in `entities` and `location_update_log`

### ISSUE THREAD

**Issue by GoWind** [backstage/backstage#4406]
This is similar to the [migration](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/migrations/20201210185851_fk_index.js), adding indices on foreign key references, to speed up queries. 

I noticed that deletes (especially bulk deletes) on `location` tables are slow as the Foreign keys referencing `id` do not have an index on them. 

## Feature Suggestion

Add indices on `entities(location_id)` and `location_update_log(location_id`) via a migration

**Comment by GoWind** [comment]
If you think this is worth it,I could assist by raising a PR for this.

**Comment by Rugvip** [comment]
Yep, makes sense 👍 

Please do @GoWind, will assign you
