### ISSUE TITLE
TechDocs: Deprecate legacy `git clone` and dir preparer in favor of URL Reader

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#4409]
# What?

When [TechDocs is set to generate docs](https://backstage.io/docs/features/techdocs/getting-started#should-techdocs-backend-generate-docs) on the Backstage server, it has to "prepare" the source files before it can generate the site. In the early days, TechDocs implemented a simple `git clone` way of downloading the repository. If your [`backstage.io/techdocs-ref`](https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageiomanaged-by-origin-location) annotation is not prefixed with `url:`, but has `github:` or `gitlab:`, TechDocs will use the legacy `git clone` preparer. The `dir:` is a syntactic sugar for the git preparer.

Later on, URL Reader received the feature of `readTree` by which it can read files and trees by downloading an archive of the repository.

# Why deprecate?

1. URL Reader (downloading archive) is much faster than Common git preparer (a git clone). TechDocs preparer step only needs markdown files and not the git history of the repository, which could increase the size 10x for a repository as large as Backstage mono-repo (Prepare times reduces from 1 minute to 5 seconds)
2. URL Reader is used across Backstage and not just TechDocs. Thus, it is much actively maintained and receives frequent support. Common Git Preparers are maintained by TechDocs and only used in it.
3. URL Reader supports more source code host providers (GitHub/GHE/GitLab(and hosted)/BitBucket(and hosted)/Azure DevOps (and on-premises)) and their intricacies like different API versions than Common Git Preparers in TechDocs. Using URL Reader adds support for GHE, Bitbucket, etc. It's quite likely that URL Reader will continue to be stable and exhaustive with more providers.
4. `dir:` preparer is complicated to maintain alongside `url:` preparer (and is only used and maintained by TechDocs). I feel that the syntactic sugar is not worth the effort of maintaining it for just one plugin. `url:` is _standard_ across backstage.

# How to migrate?

The [software templates](https://github.com/backstage/backstage/blob/a034569199aa59830aad18e2b6ea91253d8dbc70/plugins/scaffolder-backend/sample-templates/docs-template/%7B%7Bcookiecutter.component_id%7D%7D/catalog-info.yaml#L8) in this mono-repo already uses the `url:` format in `backstage.io/techdocs-ref` annotation in the Entity's `catalog-info.yaml`.

If you have created your own Software Templates, which use `github:`, `gitlab:`, `dir:`, etc. for `backstage.io/techdocs-ref` annotation. - update them with `url:` format. You also need to update existing `catalog-info.yaml` that have been created and use TechDocs annotation. Here is a simple HOW TO guide to help you https://backstage.io/docs/features/techdocs/how-to-guides#how-to-use-url-reader-in-techdocs-prepare-step

Note that `dir:` was sometimes used for local development when working with TechDocs. Now, we can use https://github.com/backstage/techdocs-cli for preview when writing docs locally and to debug any build errors. However, an alternative will be to keep dir preparer but not maintain it for production use-case.

# Plan

Throw warning in backend logs when non-URL preparer is used, with the migration link. Release on Day X.

In the release after X + 30 days, drop support for git and dir preparers in TechDocs.

Open for comments.

**Comment by OrkoHunter** [comment]
In the value of `backstage.io/techdocs-ref` annotation (`url:TARGET`) the `TARGET` can only be an absolute URL, but it makes sense to support the use case of `url:./` or other relative URLs.

Quoting @freben for implementation suggestion

> In some places we support that and use the `ScmIntegrationProviders` stuff to help resolve into an absolute URL
> I think the logic in that case would be, start with a base of the annotation backstage.io/source-location if it exists and otherwise backstage.io/managed-by-location, and then resolve the backstage.io/techdocs-ref on top of that

**Comment by soapraj** [comment]
- Once deprecated remove the docs on github: gitlab: format usage
- Can we just use URLReader for all formats and the users can migrate formats later
- Can we automate the migration of the format in CLI

**Comment by OrkoHunter** [comment]
> Can we just use URLReader for all formats and the users can migrate formats later?

👍 If by format, you meant `github:` and `gitlab:` prefixes, then yes! In fact, URL Reader supports more options, except the `dir:` for local development. But we should be using `techdocs-cli` for local preview anyway.

> Can we automate the migration of the format in the yamls and the software catalog using the CLI?

Worth exploring @Rugvip's newly introduced [`@backstage/codemods`](https://github.com/backstage/backstage/tree/master/packages/codemods) package for updating those YAML files.

**Comment by davereid** [comment]
Something for everyone else to keep in mind, if you're using this to display inner-source enterprise docs that aren't necessarily meant for public display, switching from a git clone to an URL reader means that you *must* include your docs in the Github ZIP archives that are automatically created, and you cannot use `.gitattributes` with `/docs export-ignore` otherwise your docs will never show up.

Our Drupal projects are inner-source, and our module we wrote has proprietary documentation, and we have to add a special step to delete our docs directory before it is sent to our private Composer registry, which leaves the Github archives with the docs directory intact. This caused us several weeks of frustration and it would have been really nice to continue to use the git clone method instead.

**Comment by iamEAP** [comment]
Fancy running into an old Drupal person 'round these parts!  Thanks for the note @davereid.

I believe the overall Backstage project has moved on from git-based operations in most situations for performance/scalability reasons (not only for the client consuming the underlying content, but also for the server, serving the content).

But this seems like a pretty gnarly gotcha!  I've opened up a PR to at least capture that in docs: https://github.com/backstage/backstage/pull/18047
