### ISSUE TITLE
Migrate AWS JS SDK back to V2

### ISSUE THREAD

**Issue by backjo** [backstage/backstage#4415]
Backstage recently migrated the AWS JS SDK being used to V3 (#3953, #4035). While this is great in terms of keeping Backstage updated with the latest dependencies, the V3 SDK has not implemented a number of authentication-related features that make it more difficult to use with Backstage, namely:
- No clean way to chain credentials with automatic refresh - see https://github.com/aws/aws-sdk-js-v3/issues/1796 . This is important for Backstage especially because, depending on the cloud account setup for a company, Backstage might be using AWS APIs in several accounts (i.e. reading Organizations data from a privileged account, storing S3 data in another account, scraping EKS data from a bunch). Without ChainableTemporaryCredentials, this is extremely difficult to do effectively. 

- No support for IAM Roles for Service Accounts - see https://github.com/aws/aws-sdk-js-v3/issues/1808 . This makes it difficult for folks running Backstage on EKS to easily integrate with IAM roles. There are workarounds available - using KIAM, static credentials, shared node credentials - but these workarounds have security tradeoffs involved. 

If we decide to migrate back to V2, it would make it easier for folks running on AWS to use the built in AWS integrations, especially those using multiple accounts or those running Backstage on EKS.

**Comment by Rugvip** [comment]
@backstage/maintainers leaning towards migrating back to v2. Seems like it might take quite a while until v3 implements these features.

Any thoughts on this @ayshiff or anyone else? As I understand it the migration to v3 was mainly do to it being a bit nicer to use in modern JS/TS, but not driven by any other need. As mentioned it's ofc best to stay on top of the latest versions, but it's a bit troublesome that we're seemingly losing these auth features.

**Comment by andrewthauer** [comment]
Agreed. I believe the decision was based on better TS support and being on the latest version. Unfortunate that v3 does not have feature parity.

**Comment by Rugvip** [comment]
Alright, repurposed this issue for the task of migrating back to v2. We should strive to do it in an as clean way as possible with few unrelated changes, just to make it easy to use it as a reference once we want to go back to v3. Ofc the existing PRs are good references for migrating back, #3953, #4035

**Comment by sgran** [comment]
This is great news from my point of view.  I'm looking forward to being able to use OIDC auth from my EKS cluster.

Thanks for prioritising functionality for us users over keeping up with latest and greatest!
