### ISSUE TITLE
[microsite] Improve color contrast of preformatted text

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#4419]
Preformatted text, meaning content wrapped in `<pre>` tags are displayed with very low color contrast on the microsite.  

URL: https://backstage.io/docs/reference/utility-apis/IdentityApi#signout

<img width="1440" alt="Screen Shot 2021-02-08 at 9 03 49 AM" src="https://user-images.githubusercontent.com/25153114/107191563-a23c6f00-69ec-11eb-86af-012c8ac640d5.png">

**Comment by ron-debajyoti** [comment]
Hi! Can I take this up if it's valid for beginner level contributors?

**Comment by adamdmharvey** [comment]
Would love the help @ron-debajyoti ! Assigned you. Don't hesitate to ask for help if you need it.

**Comment by ron-debajyoti** [comment]
I added a small change in `/static/css/custom.css`, which shows the changes for all the docs using the `<pre>` tag

**Comment by ron-debajyoti** [comment]
Also, I couldn't help but notice that using the search bar for a page in the locally directs to the result page hosted at `backstage.io`. Ideally, it should direct to the result page hosted at `localhost` right? :confused: 
Is this a possible bug ?

**Comment by OrkoHunter** [comment]
Won't call it a bug, but probably a misconfiguration with how Docusaurus search? 😅 

But yes, agreed that local search should resolve to local URLs. :)

**Comment by ron-debajyoti** [comment]
> Won't call it a bug, but probably a misconfiguration with how Docusaurus search? sweat_smile
> 
> But yes, agreed that local search should resolve to local URLs. :)

Ohh I did some reading about the Docusaurus search and noted that it only works when the website is publically available. Now it makes sense why it redirects. :smiley:

**Comment by freben** [comment]
Nice. Thinking of the bigger picture, should not these particular examples have been using `<code>` or a similar facility instead? I miss padding and differently-colored background, possibly a copy to clipboard button, syntax highlighting etc :)

**Comment by OrkoHunter** [comment]
+1. The sidebar also disappears on these pages - I had no idea how to navigate to this page without knowing the URL.

**Comment by ron-debajyoti** [comment]
All the docs for utility-apis are under `reference/utility-apis/README` under API references :smile:
