### ISSUE TITLE
Remove usage of `res.send()`, using `res.json()` or `res.end()` instead

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#4423]
## Feature Suggestion

We should avoid using `res.send(...)` when retuning JSON. Using `res.json(...)` forces the response body to be sent as JSON, while using `send` could result in it being interpreted as other content types. Using `res.end()` instead of an empty `res.send()` also more clearly conveys the intent of the code.

## Possible Implementation

Switch usages of `res.send()` to either `res.json()` or `res.end()`. Add a lint rules the discourage usage of `res.send()` in this repo.

**Comment by nhidtran** [comment]
hi @Rugvip ! Do you mind if I take a look at this issue this week

**Comment by Rugvip** [comment]
@nhidtran Sure! Thank you!

**Comment by nhidtran** [comment]
hello @Rugvip! If we wanted to discourage the use of `res.send` to use either `res.json()` or `res.end()`, did you want to have those linting rules live in `/backstage/packages/` or make a separate rule https://github.com/spotify/web-scripts package

**Comment by freben** [comment]
@Rugvip I reviewed the corresponding PR in #4621 and feel that there seems to be perfectly legitimate uses of `.send` and that the lint idea may not be possible to put in place short term.

**Comment by freben** [comment]
Oh you mean to actually use the data form of `end`. I see. The express docs say `Use to quickly end the response without any data. If you need to respond with data, instead use methods such as res.send() and res.json().`, but the `ServerResponse.end` docs say no such thing 🤔

**Comment by freben** [comment]
I also see that `The method, response.end(), MUST be called on each response.`. So I guess there are still a ton of places that just send and then don't call end.

**Comment by Rugvip** [comment]
`.end()` would just be for empty responses, but I was thinking we just ignore the lint rule in the places were we wanted to use send. You can also write but tbh I don't think that's safer. Happy to skip the lint rule for now and just focus on getting the risky usages fixed

**Comment by Rugvip** [comment]
@freben I'm assuming that's nodejs docs? Express doesn't require it

**Comment by freben** [comment]
Oh now I see that there are probably places where we should do `res.sendStatus(n)` instead of just setting the raw status ...

**Comment by freben** [comment]
Yeah correct, the docs for ServerResponse in node. OK then.

**Comment by benjdlambert** [comment]
Closing this as it's fixed in #4621
