### ISSUE TITLE
docs: Merge Authentication glossary with main glossary

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4432]
## Feature Suggestion

At the moment there are two glossaries in the Backstage documentation:

https://backstage.io/docs/auth/glossary
https://backstage.io/docs/glossary

## Possible Implementation

This is just a documentation update suggestion to try to better align the two.  I have a feeling moving the authentication one into the main glossary, and then linking out to the main glossary might be ideal, but the person who picks up this ticket might be able to give it a better view.

**Comment by ron-debajyoti** [comment]
Hi ! Can I take up this issue?

I went through the docs and noticed that the authentication glossary has all the technical details related to `Auth and Identity` hence the placement of the docs in the subsection there, whereas the main glossary is more related to the overall Backstage project. So, maybe we can add redirect links of each other in the respective docs page? Or renaming the authentication glossary to something more convenient?

**Comment by benjdlambert** [comment]
@ron-debajyoti assigned!

I'm thinking that instead of merging them as they have kind of different audiences and have separate concerns, we should have an auth section which links to the auth glossary from the normal glossary.

**Comment by ron-debajyoti** [comment]
Added a simple hyperlink :smile:
