### ISSUE TITLE
[Search] Create indexing pipeline diagrams for plugins (e.g TechDocs) 

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#4449]
## What / Why

Consider adding a high-level diagram illustrating the process of ingesting TechDocs documents into Search in  the "how-to" section describing the process of adding the TechDocs collator in Backstage Backend.

**Comment by iamEAP** [comment]
Wonder if this is now duplicative of #4568?

**Comment by emmaindal** [comment]
@iamEAP could be, but I think this is more of a diagram/visual representation (could be clarified in the description though)
