### ISSUE TITLE
OIDC provider hardcodes non-standard "default" scope

### ISSUE THREAD

**Issue by n2ygk** [backstage/backstage#4466]
## Expected Behavior

OIDC login should use standard scopes as defined by the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims).

## Current Behavior

`default` is concatenated to the list of scopes here:
https://github.com/backstage/backstage/blob/ae5a2e643e4897fb735ff4e0ed0e0b966cbb6430/plugins/auth-backend/src/providers/oidc/provider.ts#L63-L71

## Possible Solution

Remove `default` and add configurable list of scopes and/or set a default of `openid profile email`.

## Steps to Reproduce

See code above

## Context

Unable to use OIDC for user sign-on.

`default` scope is nowhere in the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims) so that's apparently an artifact of somebody's non-compliant OP.

_Originally posted by @n2ygk in https://github.com/backstage/backstage/issues/4430#issuecomment-776228054_

## Your Environment

- @backstage/plugin-auth-backend: 0.2.12
- NodeJS Version (v12): v14.15.4

**Comment by Rugvip** [comment]
Yep fine to remove, if default scopes are desired we configure those in the frontend.

Copying link here too https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/providers/oidc/provider.ts#L68

**Comment by n2ygk** [comment]
> Yep fine to remove, if default scopes are desired we configure those in the frontend.
> 
> Copying link here too https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/providers/oidc/provider.ts#L68

@rugvip See #4465 -- Is that the wrong place to add scope configuration?

**Comment by Rugvip** [comment]
Ah, yes it is indeed 😅 . Default scopes can be provided by supplying a custom auth api instance in the frontend, see https://github.com/backstage/backstage/blob/master/packages/core/CHANGELOG.md#minor-changes-4

**Comment by n2ygk** [comment]
Oh that's too bad. I was so proud of my PR.

And the ability to make it just work via adding a line to app-config.local.yaml.

Oh well.

**Comment by n2ygk** [comment]
@Rugvip In thinking about this some more, technically the scopes are "bound" to the clientId which is configured in the backend. I'm thinking specifying scopes from the frontend doesn't make sense for login.... Scopes can be restricted by the AS to be allowed only for a specific clientId and the frontend has no idea what clientId has been configured in the backend.

**Comment by n2ygk** [comment]
Conversation moved to #4465

**Comment by rmanny** [comment]
Working on a quick PR for this

**Comment by rmanny** [comment]
I made a PR above, but I am not sure what the process would be for regression testing this feature. Fixes the specific issue I was having with Dex but I doubt that is enough validation 😀

**Comment by benjdlambert** [comment]
Is it possible to close this issue now the PR has been merged?
