### ISSUE TITLE
[Scaffolder] Issue creating component ( from template)  using  Own Hosted Bitbucket 

### ISSUE THREAD

**Issue by kaparwan** [backstage/backstage#4489]
## Expected Behavior

@benjdlambert  
 
Creating bitbucket repo  using `/create` by choosing one of the templae. 

## Current Behavior

getting error : 

```
Create a new component α
Create new software components using standard templates
Nodejs   Template
Fill in template parameters
Choose owner and repo
Review and create
Description	NodeJS template  
Component Id	nodejs123
Owner	MyID
Store Path	https://<mybitbucket_host>/<PRJ>/repos 
Access	MyID
Failed to create component
error: Stage failed with error: The "path" argument must be of type string. Received undefined {"id":"a9b4abea-5f77-4d45-bb1d-26135661f193","stage":"Prepare the skeleton","timestamp":"2021-02-11T12:40:48.428Z"}
```

## Possible Solution

issues with the scaffolder and scaffolder-backend  version with own-hosted bitbucket 

## Steps to Reproduce

```
1.  create mono-repo 
2. yarn install; yarn tsc; yarn build 
3. cd packages/backend 
4. yarn start 
5. cd ../..
6. yarn start 
7. register template ( nodejs/java/..) using /create 
8. fill template values 
9. storagePath: https://<mybitbucket_host>/<PRJ>/repos    #PRJ -> my project in bitbucket 
10. Click next 
11. and getting above error 
error: Stage failed with error: The "path" argument must be of type string. Received undefined {"id":"a9b4abea-5f77-4d45-bb1d-26135661f193","stage":"Prepare the skeleton","timestamp":"2021-02-11T12:40:48.428Z"}
```

Then 

lowered the version 

to 

`"@backstage/plugin-scaffolder-backend":  "^0.3.7",
`
and

`"@backstage/plugin-scaffolder": "^0.4.0",
`

and Then below 

```
Publish Stage : 
info: Will now store the template {"id":"2c47ce36-a0d3-467b-8d4c-5286e9516310","stage":"Publish template","timestamp":"2021-02-11T03:07:15.977Z"}
error: Stage failed with error: Not a valid response code {"errors":[{"context":null,"message":"Project https: does not exist.","exceptionName":"com.atlassian.bitbucket.project.NoSuchProjectException"}]} {"id":"2c47ce36-a0d3-467b-8d4c-5286e9516310","stage":"Publish template","timestamp":"2021-02-11T03:07:16.137Z"}
```
So, issue related to  `The "path" argument must be of type string. `  is no longer exists,  
But it is looking 1st word of storepath as project . therefore the error` 'Project https: does not exist.  ( backend is going back to old style format os storepath but frontend is force to use https://<> in store path 

`
Further as suggest by @bih  on #Support channel 

with changing in package.json 
scaffolder --> 0.3.6  and scaffolder-backend --> 0.4.1
 
resulting in UI not opening `/create`  - looks page render issue . 
Console Tab is showin "`Uncaught Error: No implementation available for apiRef{plugin.catalog.service}`" and  `Uncaught (in promise) Error: No implementation available for apiRef{plugin.catalog.service}`

1. Step 1
packages\app\package.json

{```

  "name": "app",
  "version": "0.0.0",
  "private": true,
  "bundled": true,
  "dependencies": {
    "@backstage/catalog-model": "^0.7.0",
    "@backstage/cli": "^0.6.0",
    "@backstage/core": "^0.6.0",
    "@backstage/plugin-api-docs": "^0.4.2",
    "@backstage/plugin-catalog": "^0.3.0",
    "@backstage/plugin-catalog-import": "^0.3.3",
    "@backstage/plugin-circleci": "^0.2.5",
    "@backstage/plugin-github-actions": "^0.3.0",
    "@backstage/plugin-lighthouse": "^0.2.8",
    "@backstage/plugin-org": "^0.3.4",
    "@backstage/plugin-scaffolder": "^0.4.0",
    "@backstage/plugin-search": "^0.2.5",
    "@backstage/plugin-sonarqube": "^0.1.7",
    "@backstage/plugin-tech-radar": "^0.3.2",
    "@backstage/plugin-techdocs": "^0.5.2",
    "@backstage/plugin-user-settings": "^0.2.3",
    "@backstage/test-utils": "^0.1.6",
    "@backstage/theme": "^0.2.2",
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "history": "^5.0.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router": "6.0.0-beta.0",
    "react-router-dom": "6.0.0-beta.0",
    "react-use": "^15.3.3"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.10.1",
    "@testing-library/react": "^10.4.1",
    "@testing-library/user-event": "^12.0.7",
    "@types/jest": "^26.0.7",
    "@types/node": "^12.0.0",
    "@types/react-dom": "^16.9.8",
    "cross-env": "^7.0.0",
    "cypress": "^4.2.0",
    "eslint-plugin-cypress": "^2.10.3",
    "start-server-and-test": "^1.10.11"
  },
  "scripts": {
    "start": "backstage-cli app:serve",
    "build": "backstage-cli app:build",
    "test": "backstage-cli test",
    "lint": "backstage-cli lint",
    "clean": "backstage-cli clean",
    "test:e2e": "cross-env PORT=3001 start-server-and-test start http://localhost:3001 cy:dev",
    "test:e2e:ci": "cross-env PORT=3001 start-server-and-test start http://localhost:3001 cy:run",
    "cy:dev": "cypress open",
    "cy:run": "cypress run"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "files": [
    "dist"
  ]
}
```

packages\backend\package.json


```
{
  "name": "backend",
  "version": "0.0.0",
  "main": "dist/index.cjs.js",
  "types": "src/index.ts",
  "private": true,
  "engines": {
    "node": "12 || 14"
  },
  "scripts": {
    "build": "backstage-cli backend:build",
    "build-image": "backstage-cli backend:build-image --build --tag backstage",
    "start": "backstage-cli backend:dev",
    "lint": "backstage-cli lint",
    "test": "backstage-cli test",
    "clean": "backstage-cli clean",
    "migrate:create": "knex migrate:make -x ts"
  },
  "dependencies": {
    "app": "0.0.0",
    "@backstage/backend-common": "^0.5.0",
    "@backstage/catalog-model": "^0.7.0",
    "@backstage/config": "^0.1.2",
    "@backstage/plugin-app-backend": "^0.3.3",
    "@backstage/plugin-auth-backend": "^0.2.6",
    "@backstage/plugin-catalog-backend": "^0.6.0",
    "@backstage/plugin-proxy-backend": "^0.2.3",
    "@backstage/plugin-scaffolder-backend":  "^0.6.0",
    "@backstage/plugin-techdocs-backend": "^0.5.2",
    "@octokit/rest": "^18.0.0",
    "@gitbeaker/node": "^25.2.0",
    "dockerode": "^3.2.1",
    "express": "^4.17.1",
    "express-promise-router": "^3.0.3",
    "knex": "^0.21.6",
    "pg": "^8.3.0",
    "pg-connection-string": "^2.3.0",
    "sqlite3": "^4.2.0",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "@backstage/cli": "^0.6.0",
    "@types/dockerode": "^3.2.1",
    "@types/express": "^4.17.6",
    "@types/express-serve-static-core": "^4.17.5",
    "@types/helmet": "^0.0.47"
  },
  "files": [
    "dist"
  ]
}

```

and the app config 

```
```
scaffolder:
  bitbucket:
    api:
      host: https://<myBitbucket_host> 
      username:
        $env: USER
      token:
        $env: TOKEN
  generator: local
```

 
 with above package.json app and backend 

`error: Stage failed with error: The "path" argument must be of type string. Received undefined 
`

## Your Environment

- NodeJS Version (v12): v14.15.4
- Operating System and Version (e.g. Ubuntu 14.04): UBuntu14 
- Browser Information:: Chrome 
- Atlassian Bitbucket  v5.11.1   (own-hosted)

**Comment by kaparwan** [comment]
Hi @bih 

we discussed this in #support channel during last couple of days. 
But here is the summary please.

> On Jan 8th 2021 release  ( I think with below versions) 

scaffolder   | scaffolder-backend 
-----------   | --------------------
0.3.6            | 0.4.1

It worked well with bitbucket repo creation using /create 

> 3 days back  , it was working till before publish stage -- and we discussed the Auth issue it was throwing 

> 1 day back / today - it is not crossing 1st stage itself... ( and breaking with  above error) -` error: Stage failed with error: The "path" argument must be of type string.`





 Hi @bih 

we discussed this in #support channel during last couple of days. 
But here is the summary please.

> On Jan 8th 2021 release  ( I think with below versions) 

scaffolder   | scaffolder-backend 
-----------   | --------------------
0.3.6            | 0.4.1

It worked well with bitbucket repo creation using /create 

> 3 days back  , it was working till before publish stage -- and we discussed the Auth issue it was throwing 

> 1 day back / today - it is not crossing 1st stage itself... ( and breaking with  above error) -` error: Stage failed with error: The "path" argument must be of type string.`

**Comment by benjdlambert** [comment]
@kaparwan also for hosted bitbucket servers. You can use `https://mybitbucket.com/project/reponame` for the `storePath`

**Comment by kaparwan** [comment]
thank you @benjdlambert . ok.

**Comment by kaparwan** [comment]
Hi @benjdlambert 
Just thought to check when this will be available in node packages please?
Nightly build job is just over sometime ago,
https://github.com/backstage/backstage/actions/runs/559742566

I was looking at the related PR but couldnt see our  #4501  in there. 

Kindly advise.

Thanks
