### ISSUE TITLE
Techdocs: Unable to generate docs on Gitlab hosts locally

### ISSUE THREAD

**Issue by yorickgirard** [backstage/backstage#4495]
## Expected Behavior

Gitlab projects cloned inside /tmp/backstage-xxxx

## Current Behavior

Gitlab projects are currently being cloned inside a subfolder /tmp/backstage-xxxx/repository-name-xxxx
When generating the doc, mkdocs can't find the mkdocs.yml file because the mkdocs is not inside /tmp/backstage-xxxx but inside /tmp/backstage-xxxx/repository-name-xxxx

## Steps to Reproduce

1. Create a Gitlab repository with documentation inside it (I had the issue on Gitlab enterprise)
2. Have a backstage project linked to it
3. Run your backstage backend
4. Run your backstage frontend
5. Go to the documentation page
6. The error should be displayed on the backend console

## Context

On my dev env, I was trying to display the documentation of a project hosted on Gitlab
I don't have backstage running in a container, I directly used yarn start on my host machine from a clone of backstage.
Techdocs is configured like this:

```
techdocs:
  requestUrl: http://localhost:7000/api/techdocs
  storageUrl: http://localhost:7000/api/techdocs/static/docs
  builder: 'local'
  generators:
    techdocs: 'docker'
  publisher:
    type: 'local' 
```

Here is a stack trace:

```
2021-02-11T14:30:04.980Z techdocs warn Could not read file /tmp/backstage-r2ayTr/mkdocs.yml before running the generator. ENOENT: no such file or directory, open '/tmp/backstage-r2ayTr/mkdocs.yml' type=plugin
2021-02-11T14:30:07.585Z backstage error Failed to generate docs from /tmp/backstage-r2ayTr into /tmp/techdocs-tmp-cBtwQo with error Docker container returned a non-zero exit code (1) type=errorHandler stack=Error: Failed to generate docs from /tmp/backstage-r2ayTr into /tmp/techdocs-tmp-cBtwQo with error Docker container returned a non-zero exit code (1)
    at TechdocsGenerator.run (webpack-internal:///../techdocs-common/src/stages/generate/techdocs.ts:120:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DocsBuilder.build (webpack-internal:///../../plugins/techdocs-backend/src/DocsBuilder/builder.ts:94:5)
    at async eval (webpack-internal:///../../plugins/techdocs-backend/src/service/router.ts:143:13)
```

## Your Environment

- NodeJS Version (v14.15.4):
- Ubuntu 20.04
- backend-common (v0.4.3)

**Comment by OrkoHunter** [comment]
Just to make sure - you are not on `gitlab.com` but on hosted GitLab? Do you have a version for it - wondering how I can deploy a hosted GitLab to test.

Note of the problem: The URL reader is extracting the folder in a sub-directory of the tmp path.

**Comment by yorickgirard** [comment]
@OrkoHunter I confirm I'm on a hosted GitLab the version is: 13.6.3-ee

**Comment by OrkoHunter** [comment]
@yorickgirard Thanks! Could you helps us out by attaching a zip file that gets downloaded when you hit the archive endpoint for the repository

https://github.com/backstage/backstage/blob/0f029aefbb830645d8d7120d98effd5a5de3d3e7/packages/backend-common/src/reading/GitlabUrlReader.ts#L130-L133

(Please make sure the repository has no sensitive data, you can create a new blank repo with just a README)

An example API URL you can use to download is -
`https://gitlab.mycompany.com/api/v4/projects/backstage%2Fmock/repository/archive.zip?sha=master` from the test
https://github.com/backstage/backstage/blob/1b38e38094c729e4ca9e4fc43041318801b61f53/packages/backend-common/src/reading/GitlabUrlReader.test.ts#L240

**Comment by OrkoHunter** [comment]
Ummm - @backstage/backend-common v0.4.3 seems to be quite old https://github.com/backstage/backstage/blob/master/packages/backend-common/CHANGELOG.md

Could you try `yarn backstage-cli versions:bump` and test with the latest version of the URL Reader? It's possible that the previous versions had bugs with hosted GitLab.

https://backstage.io/docs/FAQ#how-do-i-keep-my-backstage-app-up-to-date

**Comment by yorickgirard** [comment]
Here is the project

I'll update my dependencies right now thanks

[project-sample-backstage-master.zip](https://github.com/backstage/backstage/files/5966677/project-sample-backstage-master.zip)

**Comment by yorickgirard** [comment]
@OrkoHunter after updating the dependencies it works properly, I think the issue can be closed
