### ISSUE TITLE
API Design: Query the catalog by relations

### ISSUE THREAD

**Issue by freben** [backstage/backstage#4499]
## Background

The catalog supports filtering when listing entities, through the use of e.g.

```
GET /api/catalog/entities?filter=kind=component,metadata.namespace=default
```

These essentially locate fields by their paths in the JSON structure and compare to a (stringified) value. It also "flattens" arrays, so you can for example match on `metadata.tags=java` to match on any single tag being equal to `"java"`.

The search implementation is backed by the `entity_search` lookup table in the catalog database. It contains all possible key-value pairs for all entities. This table is populated for each entity write operation.

## Feature Suggestion

A user should be able to query for entities by their relations. This is not possible today.

Example entity data:

```json
{
  "apiVersion": "backstage.io/v1alpha1",
  "kind": "User",
  "metadata": {
      "name": "tara.macgovern",
      "namespace": "default",
      ...
  },
  "spec": {
      "memberOf": [
          "team-c"
      ],
      ...
  },
  "relations": [
      {
          "target": {
              "kind": "group",
              "name": "team-c",
              "namespace": "default"
          },
          "type": "memberOf"
      }
  ]
}
```

Add the ability to query for entities that have a certain type of relation, with a certain target.

## Possible Implementation

This is the point where we ask for suggestions!

- Let's figure out a sensible query format.
- Should it be part of the `filter` syntax, or a separate query format?
- Shall the user have to supply all three parts of the target, or will there be a defaults mechanism?
- Shall it be possible to query for the very existence of a relation, or only specific targets?

One possible candidate would be:

```
?filter=relations.memberOf=group:team-c
```

Which is similar in structure to the other filtering, and fits within the `entity_search` table. What other candidates are there?

**Comment by adamdmharvey** [comment]
Thinking this one is possibly able to be closed now?

https://github.com/backstage/backstage/blob/6e55099b584ab4cf26bc786c3f392bf54447db09/plugins/catalog-react/src/utils/getEntityRelations.ts#L19-L26

**Comment by freben** [comment]
Not quite - that request gets the individual relations of one entity, while what I want from the ticket is to be able to query the REST api and filter among all entities based on what relations emanate from, or point at, each entity

**Comment by grantila** [comment]
> * Let's figure out a sensible query format.
> * Should it be part of the `filter` syntax, or a separate query format?

This is becoming a search which makes me think, moving to POST and having a JSON payload fits better than query parameters, with the only real drawback being reducing cacheability. This is also true for very complex queries, or batch queries, where the query string would potentially exceed the limits of whatever proxies, load balancers, etc one might have.

Regardless,
Today filter is a generic key-value e.g. `kind=User` of the type `filter?: Record<string, string | string[]> | undefined;`.

I think it would help if these keys were *known*, well defined. Consider (also `| undefined` is unnecessary when `?`):

```diff
+export type CatalogEntitiesRequestFilter = {
+  kind?: string;
+  relations?: EntityRelation[];
+};

 export type CatalogEntitiesRequest = {
-  filter?: Record<string, string | string[]> | undefined;
-  fields?: string[] | undefined;
+  filter?: CatalogEntitiesRequestFilter;
+  fields?: string[];
 };
```

This API, for plugins, allows for using `EntityRelation` types to the interface of the CatalogClient. Example in [OwnershipCard](https://github.com/backstage/backstage/blob/master/plugins/org/src/components/Cards/OwnershipCard/OwnershipCard.tsx#L149-L151) you'd be able to do:

```diff
       filter: {
         kind: kinds,
+        relations: entity.relations,
       },
```

I think the *things* you can filter should be explicit like that, in `CatalogEntitiesRequestFilter` and then have its own serialization/deserialization, such that (slightly pseudo):

```ts
// CatalogClient.getEntities
let filter: CatalogEntitiesRequestFilter; // from the caller
const queryString = 'filter=' +
    [
        ...(filter.kind ? [ `kind=${kind}` ] : []),
        ...(filter.relations ? relations.map(({type, target}) => `relation.${type}=${stringifyEntityRef(target)}`) : []),
        // ... filter metadata and whatnot goes here ...
    ]
    .filter(v => v)
    .join(',')
```

...but with proper url encoding, obviously.

> * Shall the user have to supply all three parts of the target, or will there be a defaults mechanism?

I vote for having them intersectioned (e.g. sql `and`) with default `true`, so if you don't provide metadata then anything goes. Each filter you add will then add an extra constraint - without that filter, no corresponding constraint.

> * Shall it be possible to query for the very existence of a relation, or only specific targets?

Something like custom reductions; `?filter=relation.memberOf={target_entity_ref}&reduce=count`?

Or possible rely on HTTP status codes, e.g: `HEAD /entities?filter=relation.memberOf={target_entity_ref}` returning 200 for *exists* and 204 for *doesn't exist*.

I think both of these could be added later yet be compatible.

I'm personally not a fan of `=` in values, but unsure what else. Possibly `:` (`?filter=kind:User,relation.memberOf:{ref}`)...

**Comment by Rugvip** [comment]
@grantila We're not really looking to change the existing format at this point, so let's stick to using the double `=`. I don't think we need to be able to query of the existence of relations yet tbh, or partially defined targets, so could prolly skip that too.

> I think it would help if these keys were _known_, well defined.

They're not, orgs can define their own fields for custom entities, we can't really make any assumptions except for the base `metadata`/`spec`/`relations` etc.

I'm thinking this is good enough for now

```ts
getEntities({
  filter: {
    [`relations.${RELATION_OWNED_BY}`]: stringifyEntityRef(user)
  }
})

// ?filter=relation.ownedBy=user:default/guest
```

**Comment by grantila** [comment]
Ok, would that work right now, and if so, how would I know that this works? Both the key and the value are just a raw strings. Should I follow the flow to the backend to see what the backend is doing with this string wrt creating database calls? I'm trying to understand how I as a plugin developer would go about using this filter and knowing *how* I could use it.

If it *does* work now, how do I know this will work 2 months from now, if the backend changes how it deals with these strings? I don't feel comfortable writing such a filter without knowing this is *the* supported method for doing so.

**Comment by Rugvip** [comment]
@grantila It doesn't work now. The key is just the dot-separated path inside the entity JSON with arrays ignored, nothing too magic about that. The relation target is a bit more magic though, and it's perhaps even unfortunate that your JSON entity representation using the entity full name object rather than a ref for the target entity. Could be that we want to look into what it would mean to change that.

If we do want to go down the route of switching the target the actually be a stringified ref, then we avoid the magic value so design here is reasonably sound. We could then happily implement this now knowing that we'll migrate to something that fits well with it in the future.

Thoughts on moving to stringified entity refs for the relation targets @freben? Should dig up the reasoning there in the first place and see if we had some good reasons to go down this route

**Comment by grantila** [comment]
> The key is just the dot-separated path inside the entity JSON with arrays ignored

Interesting, if this is set in stone, are arrays ignored as in "all entries are filtered as a union"?

If so, perhaps this can be solved (ish) today, e.g. fetch all users of a group by `filter=kind=User,relations.target.name=the_group_name` and do client-side filtering to ensure correct relation _types_, right? It's not an ideal query format (both API-wise and efficiency-wise), but would be feasible in our use case.

**Comment by freben** [comment]
After the catalog rewrite that was just merged, this has basic support in the form

`/catalog/entities?filter=relations.ownedBy=user:default/guest`

There is room for extending this of course, but the basic need is addressed for now.
