### ISSUE TITLE
multi-stage-frontend Dockerfile is broken

### ISSUE THREAD

**Issue by camberkenpas** [backstage/backstage#4504]
contrib/docker/multi-stage-frontend/Dockerfile is broken

## Expected Behavior

Building the multi-stage-frontend should result in a fully working image.

## Current Behavior

Building the multi-stage-frontend results in an almost working image. Going to http://localhost:<port>/ works, navigating from
there to any sections such as /api-docs, /catalog, etc works. However, if you enter http://localhost:<port>/catalog directly into the browser or simply reload the page nginx returns a 404. The logs report that the /path/to/nginx/dir/catalog does not exist.

The above is caused by the Dockerfile failing to pull in `docker/default.conf.template`. The Dockerfile also fails to pull in `docker/run.sh`. This is due to the `docker` folder missing from `contrib/docker/frontend-with-nginx/docker`.

## Possible Solution

This mostly fixes it:
```sh
 cp -a contrib/docker/frontend-with-nginx/docker contrib/docker/multi-stage-frontend/
```

However, the `COPY` commands' source paths to these files are relative:
```
COPY docker/default.conf.template /etc/nginx/conf.d/default.conf.template
COPY docker/run.sh /usr/local/bin/run.sh
```

Attempting to build the image inside `contrib/docker/multi-stage-frontend/` to get around this does not work. Building from the root of the repo works if you update the paths in ` contrib/docker/multi-stage-frontend/Dockerfile` to:
```
COPY contrib/docker/multi-stage-frontend/docker/default.conf.template /etc/nginx/conf.d/default.conf.template
COPY contrib/docker/multi-stage-frontend/docker/run.sh /usr/local/bin/run.sh
```

But is this what we want to do? Perhaps these paths and/or `contrib/docker/multi-stage-frontend/README.md` need to be updated to reflect the correct build instructions.

Once we're able to copy in `default.conf.template` and `run.sh`, the issues described are resolved.

## Steps to Reproduce

The build completes if run from the root, but has the aforementioned issues:
`docker build -t backstage-frontend -f contrib/docker/multi-stage-frontend/Dockerfile .`

The following fails with `error Cannot find the root of your workspace - are you sure you're currently in a workspace?`:
```sh
cd contrib/docker/multi-stage-frontend/
docker build -t backstage-frontend -f Dockerfile .
```
### What does work:
Updating the `COPY`commands in `contrib/docker/multi-stage-frontend/Dockerfile` to:
```
COPY contrib/docker/multi-stage-frontend/docker/default.conf.template /etc/nginx/conf.d/default.conf.template
COPY contrib/docker/multi-stage-frontend/docker/run.sh /usr/local/bin/run.sh
```
And then running `docker build -t backstage-frontend -f contrib/docker/multi-stage-frontend/Dockerfile .` will result in a working image!

**Comment by freben** [comment]
I believe that this is no longer the case; the Dockerfile has been iterated on since. Closing, and please do reopen if the problem manifests itself still

**Comment by freben** [comment]
for posterity - we actually went ahead and cleaned up this to make it work https://github.com/backstage/backstage/pull/5391
