### ISSUE TITLE
Ecosystem model diagram refers to relationship which is not implemented

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4505]
## Expected Behavior

High-level ecosystem model diagram represents available relationships.

## Current Behavior

In developing the system diagram map in #4502 , I realized that the `dependsOn` example shown in the sample model is not fully implemented in Backstage's system model. There are partial aspects of it but it seems incomplete?

![image](https://user-images.githubusercontent.com/33203301/107726309-7f44e000-6cb6-11eb-9826-c435b8a11345.png)

## Possible Solution

Either:

1. Update the diagram to remove `dependsOn` as a relationship type until a future time in which this relationship is fully provided by the model.
2. Update the model to fully support it.

## Steps to Reproduce

1. View the docs
2. Check the model types in the system: https://github.com/backstage/backstage/search?q=dependsOn and https://github.com/backstage/backstage/search?q=RELATION_DEPENDS_ON

## Context

I may be wrong in terms of how it is implemented, but it does not seem to me that it would fully work, even if it's roughed out in some constants?

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by freben** [comment]
Right! I think the relation is sound, to the best of my knowledge it's the one we decided to use for this purpose. So your solution number 2 would be appropriate. This is now a feature request ticket! :)

We'd have to add a `spec` field to be able to either

- point out resources that your component depends on, [here](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/schema/kinds/Component.v1alpha1.schema.json#L43) and [here](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/kinds/ComponentEntityV1alpha1.ts#L30), or
- from a resource point out the components that depend on you, [here](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/schema/kinds/Resource.v1alpha1.schema.json#L37) and [here](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/kinds/ResourceEntityV1alpha1.ts#L30)

Or actually both could be supported! To fit different mental models or availability of source data for the field.

And then to update the relevant relation-generating [processor](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/BuiltinKindsEntityProcessor.ts#L78).

**Comment by jmgrimes** [comment]
I'd be quite interested in this, as it could help us model some of the resources created via our infrastructure as code projects and the dependencies on them.  I might take a shot at this if I have some free time next week.

**Comment by adamdmharvey** [comment]
Consider it yours!  Thanks, @jmgrimes. Feel free to reach out and ask for help from the community. I'll note the System Diagram, which was now merged in, would also need manual updating to support the new relationship type as well. (and potentially a better way to reflect multiple types, period!)

**Comment by jmgrimes** [comment]
I was able to get the catalog model updated for both Component and Resource, and updated the entity processor to create the proper relationships.  Adding the relationship support to the graph appears to have worked, but there's a layout issue I'm encountering with the DependencyGraph component that I'm not able to sort out on my own.  Because of the specific model being used, I'm encountering some clipping on one of the edges.

<img width="500" alt="Screen Shot 2021-03-26 at 11 24 48 PM" src="https://user-images.githubusercontent.com/1869138/112708801-87359980-8e8a-11eb-947b-cc9c145ff5eb.png">

**Comment by adamdmharvey** [comment]
@jmgrimes Agreed; there are definitely some formatting issues with `SystemDiagram`, some of which may be inherent to the library used for the `DependencyGraph` component itself. I wasn't really able to get it to better dynamically fit. Hoping other iterations and bug fixes can continue to improve it for sure!  But your adding support for your new modelling type is wonderful, so thx for that!

**Comment by jmgrimes** [comment]
Yeah, I found when trying to dig into the right set of options to change to fix the clipping, I was in a bit over my head haha.  I'll poke around and see if there's anything else that I might be able to help with.  Thanks!
