### ISSUE TITLE
Org Plugin: Themed Ownership Card

### ISSUE THREAD

**Issue by egnwd** [backstage/backstage#4519]
## Feature Suggestion

 - Currently the [OwnershipCard](https://github.com/backstage/backstage/blob/master/plugins/org/src/components/Cards/OwnershipCard/OwnershipCard.tsx) only uses the default theme colours
 - It would be nice if they matched the theme of the backstage app in which they the component resides
 - Potential drawback: custom themes that don't cover all the page theme ids will all fallback to the default theme and so the page will look less exciting. (Though will still match the page themes within the app)

## Possible Implementation

I had a go at making the change so if this is something that people think belongs in the base plugin I'm happy to submit a PR. (Just need to figure out the changeset and tidy some things up). The `theme` is already threaded through to the styles so it was simply a case of reading the styles from the theme.

Example (monochrome theme):

<img width="835" alt="Skärmavbild 2021-02-14 kl  02 14 01" src="https://user-images.githubusercontent.com/2790386/107866589-739a1a80-6e6a-11eb-914e-ca0a748440c0.png">

Would love to know people's thoughts on this.

**Comment by adamdmharvey** [comment]
I agree. All plugins should support the theming, such that anyone switching the base light/dark or even a custom theme see a consistent interface across their entire instance and any plugin their install. And absolutely fair if it was added without it, you may have just caught a nice incremental update. Thanks for taking a stab, @egnwd !!

**Comment by adamdmharvey** [comment]
Oh, and apols - initially thought you _already_ took a stab at fixing this based on linked PR, so assigned you (but I just re-read it).  Are you wanting/willing to give it a shot or should we open this one up to the community?

**Comment by egnwd** [comment]
Happy to open a PR for this, I just didn't want to conflate the storybook PR with this update. I need to look at seeing if I can get the theme I use for the widget to respond the the light mode/dark mode button in the storybook UI.

**Comment by freben** [comment]
How would the theming be implemented? The Backstage core theme (search for BackstageTheme for examples in the code base) does have some extensions already on top of MUI, such as the custom status colors palette and more. Would this be something added to the core theme such that it aligns with other colors, or would it be card specific somehow?

**Comment by egnwd** [comment]
@freben I had some time to finish that [PR](https://github.com/backstage/backstage/pull/4586) hopefully that answers your question/opens the discussion of how to possibly change my implementation 😄
