### ISSUE TITLE
Unable to generate or upload relations when `POST`-ing entities to the catalog-backend.

### ISSUE THREAD

**Issue by GoWind** [backstage/backstage#4538]
The route handling function for `POST /entities` in the `catalog-backend` [disregards](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/router.ts#L64)  `relations` `POST`-ed in the request and also does not generate relationships, when an `Entity` is posted. 

## Expected Behavior

Either relationships should be allowed to be injected manually, or auto-generated, such as done in the [BuiltinKindsEntityProcessor](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/BuiltinKindsEntityProcessor.ts)

## Current Behavior
Relationships are not generated, or allowed when `POST`-ing entities. The lack of relationships affects a lot of UI features, for example, to jump to the  `Group` that owns a  `Component` on the Catalog. This makes `Locations` the only functioning way to inject entities into the catalog database with relations.

## Possible Solution

1. Allow relations to be POST-ed along with entities.
2. Generate entity relations before add entites to the database.

This could involve splitting out the logic to generation relations into a separate function that can then be re-used in the Kinds and the 
## Steps to Reproduce

Post an Entity of kind `Group` with an arbitrary name `a`.
Post an Entity of kind `Component` with `name` `Alpha` with `spec.owner` set to `a`.

No `ownedBy` relation for `Alpha` is generated with `target` to `{default, Group A}`.

The catalog UI plugin's overview does not link to `a`  for Alpha due to the missing relationship.

## Context

I was trying to generate entities from an existing service by `POST`-ing to the catalog backend and the UI did not show the relationships as expected. On further inspection and reading the code, it looks like relation ships are not generated (and ignored, if present in the payload) when entities are directly POSTED to the catalog.

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by GoWind** [comment]
I added the bug label to this, but I would like to know why relationships were ignored in the payload (as linked above). Was this a design choice or just not fixed at the moment ?

**Comment by freben** [comment]
The short story is, POST creation is an old and unsupported remnant. We do not recommend using it. Prefer to make dumps that are imported as locations instead, or make a custom catalog processor to ingest the data directly. Those are the two supported flows right now.

The POST endpoint should probably not have been created at all until the entire flow could have been laid out properly. We have a goal this quarter to finalise several aspects of the catalog to stabilize it. At that point we'll probably take a long hard look into this flow to either fix it or to remove it.

**Comment by freben** [comment]
Side note about relations. They are currently defined explicitly to be read-only - they can only be generated by the backend, not by the user or the input files.

**Comment by GoWind** [comment]
@freben : `make a custom catalog processor to ingest the data directly` is again through `locations` right ? Or is there another way to use processors to ingest data ?

**Comment by GoWind** [comment]
In any case, if `post`-ing is not meant to be supported anymore, can we mark it as deprecated ?

**Comment by freben** [comment]
Yeah all processors are _triggered_ by locations; that's how they enter the processing loop. So you would have to have an initiating location (probably with a custom location `type`), probably under `processor.locations` in your config.

Agreed, we should be clearer in messaging that the POST endpoint should be avoided. We'll get back to that in the next couple of weeks as we overhaul it all.

Is this ticket closeable at this point? Or are there more actionable things?

**Comment by GoWind** [comment]
Just the Deprecation notice, but otherwise this can be closed.

**Comment by martina-if** [comment]
Hi @freben I was thinking about this and imagine there was a GHA that whenever a PR is open would check that the catalog-info.yaml file is valid and then when the PR gets merged it would push its entities to Backstage. Wouldn't this endpoint be useful in that case? Or would that be done through a different one?

**Comment by freben** [comment]
Hi! Yeah we are very interested in getting an event driven architecture into place, what you describe is accurate from an end user perspective. We will see if it in practice is solved like this though, or in some other manner. For example, an alternative solution could be a webhook driver that marks locations dirty and then those get pulled in from the catalog side instead.

We'll be working on the catalog this quarter, and then we'll dissect the processing loop and see what we can do about things. To make processing truly deterministic, we need to make sure that things that have requirements on their surroundings are in place. For example, to have proper resolution of relations with other entities, it may not be enough to "know of" only the local entity itself; you may need to be able to access a context around you too. This is where the mismatch between the "push" and "pull" models come into play.

But yeah, we'll look at that for sure.
