### ISSUE TITLE
Add core plugins to backstage.io/plugins

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#4546]
There is a bunch of core plugins (catalog, techdocs, scaffolder). These plugin have a dedicated section in the docs, but for visibility it would be cool to have them in the plugin catalog, too!

One issue might be, that they would need an icon to integrate them 😉 

Maybe there are still some plugins in the plugins directory that we don't showcase yet.

- [ ] techdocs
- [ ] catalog
- [ ] scaffolder

**Comment by OrkoHunter** [comment]
+100

**Comment by adamdmharvey** [comment]
I agree.  👍 for the idea of elevating other plugins to the market place.

In alignment, I will say it becomes harder and harder to me to defend a plugin that is ALSO a listed core feature. _If it's a core feature, why is it not a core package?_ A core package doesn't infer that it's not open source and not available for community feedback/enhancement, but that it should be provided by default and has higher visibility to maintainers for quality, inclusion, etc.  I think the recent Kubernetes addition to the doco, for example. If it's labeled as a core feature, used to align with CNCF and the industry as a whole, then why would it be listed as a "plugin" which _sounds_ optional - `optional != core` ?.  For sure that's a product owner/manager decision, but just something I think about occasionally. Just adding that in as it relates to which ones get added as per this idea!

**Comment by OrkoHunter** [comment]
Closing this issue in favor of https://github.com/backstage/backstage/issues/4897
