### ISSUE TITLE
proposal: Remove "system" from entity tables

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4553]
## Feature Suggestion

After the inclusion of tables via #4392, I wanted to see what the group thought about maybe removing the system column from those tables.

At the moment, I'm on a 1920x1080 screen - a reasonable, if not huge, screen size. (no external monitor)

When I view a system: I see each of the tables with small horizonal scroller bars. Having a table of all items assigned to a system, where one of the columns should always be system, I would posit isn't useful in this specific context?

![image](https://user-images.githubusercontent.com/33203301/108109150-87f33880-705f-11eb-8319-23bf10873072.png)

In addition, with subcomponents, I think the likelihood of a subcomponent being in a DIFFERENT system when the main component (and where the system name is visible and linkable in the about card) may also not be needed here:

![image](https://user-images.githubusercontent.com/33203301/108108470-a86ec300-705e-11eb-94d0-071df18bf453.png)

## Possible Implementation

Remove the system column from the tables.

## Context

Reduces the information in the tables making them easier to digest when that info is elsewhere on the screen (as in the about card) or could be assumed (subcomponents), and squashes them a bit for moderate screen sizes.

There may be nuances that if they are removed, their reuse elsewhere might not be as valuable so open to opinions or if they could be passed on as optional, that sort of thing.

**Comment by adamdmharvey** [comment]
...oh and domain from domain table I think?

![image](https://user-images.githubusercontent.com/33203301/108110584-7448d180-7061-11eb-98b8-0bdd5dcef10b.png)

**Comment by adamdmharvey** [comment]
cc @Fox32

**Comment by adamdmharvey** [comment]
And sorry, I _think_ some of this might be as easy as changing these ?

![image](https://user-images.githubusercontent.com/33203301/108111543-cc340800-7062-11eb-9ad3-bb9e977f80a7.png)

At least looks good on my side (except for the API table, which still shows system on the systems side):

![image](https://user-images.githubusercontent.com/33203301/108111666-00a7c400-7063-11eb-8ac5-8b9c47092e7e.png)

Again, wanted to get some feedback before I fired a PR in case these are used in other ways and I'm off base on them 😀

**Comment by freben** [comment]
Yes! I realize now that I think we could remove a lot of description columns too - they prey on other columns and make them linebreak awkwardly. Could compensate by having tooltip like hover (or expandable rows) with extra info if needed

**Comment by freben** [comment]
Also - remember that in the new composability world, an org will be at liberty to design these pages responsibly as they see fit. If you prefer to have a 4 / 8 column split on large screens and everything table-like on the right, or to aggressively stack things vertically instead of side by side on less-than-xl widths, you can totally do that

**Comment by freben** [comment]
Totally a side note, but when the dust has settled and things are mostly in place, I think it would be great to spend a bit of time going through most of the default Backstage experience, on (1) a <800 px wide browser and (2) a fairly modern cellphone. Ideally it should be perfectly usable on both without awkwardness.

**Comment by adamdmharvey** [comment]
Absolutely. What _triggered_ the idea for me was the scroll bar, and then realized on certain pages it was duplicated. But we'll never want to perfectly control that, but for sure the integrator can pick/choose what to put and where to put it in their app! And I may use a bigger monitor next week, or a zoomed out screen, whatever, so it needs to flex.

If ok then, given at least your feedback Fredrik, maybe I'll try a PR and welcome counter opinions on it?

I also like your idea about the descriptions, tried removing those since this looks easy and they really do squash a lot better.

**Comment by freben** [comment]
Yeah go ahead I'd say, maybe @Fox32 or the others have some other ideas of how to make things leaner too

**Comment by freben** [comment]
Regarding what to change - not sure if the defaults are what you want to change, or if you will want to supply custom columns as a prop per place.

**Comment by adamdmharvey** [comment]
Ah - don't believe they are overridable ATM. Given that, maybe will hold off as have a bunch of other stuff to get to this (shortened US) week. 😁 

![image](https://user-images.githubusercontent.com/33203301/108114135-69dd0680-7066-11eb-81ad-d689c9105d4c.png)
![image](https://user-images.githubusercontent.com/33203301/108114166-73666e80-7066-11eb-9de9-0fc24c29f31d.png)

**Comment by Fox32** [comment]
The component table column preset is also used on the API entity page where the system wouldn't be redudant (providers/consumers card). Not 100% sure if I would say that nobody cares "by which systems an API is used". If we change set we should probably use a different set of columns for the `HasComponentsCard`. Not sure what to do about the `HasSubcomponentsCard`, I would argue that all subcomponents are from the same system, so we could remove it there too? 

About the systems of a domain: Yeah let's remove the duplicate domain details.

**Comment by Fox32** [comment]
Btw, we use different grid breakpoints in our app - we even have different tabs. So the usage here in the example app might not be a good choice.

**Comment by freben** [comment]
@adamdmharvey Take your time, still like the suggestion, let's slim things down a bit when you can

**Comment by adamdmharvey** [comment]
Per conversation in the small PR I just opened, seems to make sense for this fix to actually include an overriding mechanism so each chosen display of a table could potentially be suited to it's own need. (Some we may want a system column, some maybe not, esp if integrators customize.)

Given that, marked it `help wanted` and open to the community to take a stab if willing/able!
