### ISSUE TITLE
[Scaffolder] Component creation failing in publish stage after #4489 fix... 

### ISSUE THREAD

**Issue by kaparwan** [backstage/backstage#4554]
## Expected Behavior

Creating bitbucket repo using `/create `by choosing one of the template.

## Current Behavior

```
Component Id	nodejs
Owner	<Owner>
Store Path	https://mybitbuckthost.com/PRJ/repo11
Access	<Owner>
Failed to create component
info: Will now store the template {"id":"c20f9d36-9955-41f8-af71-7cf19889ac87","stage":"Publish template","timestamp":"2021-02-16T23:42:20.929Z"}
error: Stage failed with error: Not a valid response code {"errors":[{"context":null,"message":"You are not permitted to access this resource","exceptionName":"com.atlassian.bitbucket.AuthorisationException"}]} {"id":"c20f9d36-9955-41f8-af71-7cf19889ac87","stage":"Publish template","timestamp":"2021-02-16T23:42:21.041Z"}

```
## Possible Solution

I was trying to debug this in local but getting error in Templator stage in local . due to Docker dependency. It is looking for mkdocs docker container download. Though, I have mkdocs installed locally. It should have  picked up mkdocs binary directory and not to go for docker for mkdocs. So couldn't debug it further as I couldn't reach to publish stage in local. 

## Steps to Reproduce

1.  create mono-repo 
2. yarn install; yarn tsc; yarn build 
3. run docker for both frontend and backend 
4. register template ( nodejs/java/..) using /create 
5. fill template values 
6. `storagePath: https://<mybitbucket_host>/<PRJ>/repos  `  #PRJ -> my project in bitbucket 
7. Click next 
8. and getting above error 

```
Failed to create component
info: Will now store the template {"id":"c20f9d36-9955-41f8-af71-7cf19889ac87","stage":"Publish template","timestamp":"2021-02-16T23:42:20.929Z"}
error: Stage failed with error: Not a valid response code {"errors":[{"context":null,"message":"You are not permitted to access this resource","exceptionName":"com.atlassian.bitbucket.AuthorisationException"}]} {"id":"c20f9d36-9955-41f8-af71-7cf19889ac87","stage":"Publish template","timestamp":"2021-02-16T23:42:21.041Z"}
```

## Your Environment

NodeJS Version (v12): v14.15.4
Operating System and Version (e.g. Ubuntu 14.04): UBuntu14
Browser Information:: Chrome
Atlassian Bitbucket v5.11.1 (own-hosted)

**Comment by kaparwan** [comment]
Hi @bih 
Thank you  for providing the fix for filepath issue - #4554 . As discussed earlier publish stage issue is appearing now.  I was trying to debug it further , but  `generator:local ` isnt quite working to run the templator stage in my local machine in order to use mkdocs locally but not to look for mkdocs docker image. but having said that that is an different issue. so you can advise on publish issue as mentioned above that will be great.

**Comment by benjdlambert** [comment]
Ok so let's deal with the publish problem first. I think you want to set your storePath to `https://mybitbucket/{user/owner}/{name}` can you try that first. Also are you using token config or username and appPassword?

**Comment by kaparwan** [comment]
Thanks. 

https://github.com/backstage/backstage/issues/4489#issuecomment-777741656
we are using https://mybitbucket.com/project/reponame as mentioned in above please

**Comment by benjdlambert** [comment]
>Also are you using token config or username and appPassword?

 what about this - what does your appConfig look like.

The `generator:local` stuff doesn't belong under the scaffolder config, it should be under techdocs. @OrkoHunter can help here.

**Comment by OrkoHunter** [comment]
Yep - generator is a [`techdocs` config](https://backstage.io/docs/features/techdocs/configuration) to know whether it should use Docker to generate sites or should use locally installed `mkdocs` executable.

In Scaffolder, I think this is managed automagically - if you have `cookiecutter` installed locally, it will be used - otherwise a Docker container will be invoked which has cookiecutter set up. Ben can correct me if I am wrong.

**Comment by kaparwan** [comment]
thank you  @OrkoHunter @benjdlambert 
I have cookiecutter installed locally. 

```
$ cookiecutter -h
Usage: cookiecutter [OPTIONS] TEMPLATE [EXTRA_CONTEXT]...

  Create a project from a Cookiecutter project template (TEMPLATE).

```
But it is not used. It it trying to invoke `docker` locally.

**Comment by kaparwan** [comment]
Hi @bih 

Based on the below link... added `token:`  along with  the other bitbucket integration configs  ( `appPassword:` and `username:` ) .  

https://github.com/backstage/backstage/blob/8ebcb85dab97bc7025c2397c675c4e736d0e909f/plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts#L157

and it worked :-) 

this issue can be closed  or we can close this after  cleanup fixes which you would be adding as you were mentioning code shouldn't expect all ( `appPassword:`  and `token:` ...) .
