### ISSUE TITLE
[TechDocs] Implement a DefaultTechDocsCollator

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#4568]
## What / why

In #4438, we introduced the concept of a Search collator, which is a class that a plugin can export whose purpose is to return all indexable documents the plugin is responsible for.  We should  implement a `DefaultTechDocsCollator` which returns documents representing individual TechDocs pages across every known TechDocs site.

## Possible Implementation

- Iterate through the software catalog, looking for TechDocs annotated entities.
- The basis for the aggregated index should be the lunr index that is generated for us by mkdocs (e.g. [the `docs` key here](https://demo.backstage.io/api/techdocs/static/docs/default/Component/backstage/search/search_index.json))
- The `location` field will need to configurable (recommend following the pattern in [DefaultCatalogCollator](https://github.com/backstage/backstage/blob/a99e0bc/plugins/catalog-backend/src/search/DefaultCatalogCollator.ts#L42)
- Capture other potential metadata beyond the given `title`, `text` fields (like entity name/kind/namespace, etc.)

**Comment by kenny-chow-my** [comment]
Hi I see https://github.com/backstage/backstage/pull/5927 has been merged last week. Does it mean this is now going to be worked on soon?

**Comment by iamEAP** [comment]
Hey @kenny-chow-my, we at Spotify are not actively working on this, or TechDocs search generally, however I've heard that @rodmachen may be working on this.  Perhaps you two could coordinate efforts?

**Comment by iamEAP** [comment]
Follow-up to my last comment, Rod's comment on discord:

> _...We're still talking about it at Expedia about committing to taking [this] on. If someone else wants to, they absolutely should._

So if anyone wants to take a crack at it, we'd be super happy to support / review PRs / etc!  Hopefully there's sufficient detail in the `possible implementation` section to help folks get started.

**Comment by Xantier** [comment]
I could grab this and start chipping away to bring the search to docs as well. I'll start crafting types and shapes, open up a PR on those and we can then iterate from there with the implementation and tests to surround rest of the logic.

**Comment by Fox32** [comment]
From our experience from implementing this internally, I recommend running `unescape` from `lodash` on both `text` and `title`. Otherwise, the steps from "possible implementation" above are straight forward.

**Comment by iamEAP** [comment]
Thanks @Xantier!  Going to assign this to you, just to reflect what you're up to.  Reach out here or on discord if you run into any snags.

**Comment by rodmachen** [comment]
Looking forward to this work. At Expedia, we're about to start work on implementing the new V1 Global Search, and will use this functionality as soon as it's ready. Please let us know if we can help in any way.

**Comment by dtuite** [comment]
@iamEAP Just FYI, Roadie (primarily Xantier) are planning on driving through the whole TechDocs/ElasticSearch implementation to completion. This is step 1 but we are hoping to get them all done.

**Comment by iamEAP** [comment]
That's great news @dtuite!  I've added a couple of notes to #4447 with a few ideas/tips based on experiences we've had running Backstage on Elastic internally.
