### ISSUE TITLE
Unable to reestablish database conneciton 

### ISSUE THREAD

**Issue by stefanbuck** [backstage/backstage#4573]
## Expected Behavior

If the database connection drops, Backstage eg. `@backstage/plugin-catalog-backend` should be able to reestablish the database connection.

## Current Behavior

Backstage is unable to recover if the database connection is lost. Only restarging the backend helps to recover. 

## Steps to Reproduce

1. `docker run -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres`
1. yarn start
1. yarn start-backend
1. teardown database 
1. Reloading the app prompts the following error `Error: Could not fetch catalog entities. Error: Request failed with 500 Internal Server Error, database "backstage_plugin_catalog" does not exist`

## Context

We are using a hosted database so it's very unlikely that this instance goes down. However a connection drop is more likely and the only solution is to restart the backend. That said, I wonder if the `livenessProbe` should check the database connection as well. On the other hand restarting a pod just to reestablish the connection sounds overkill.  

```
backstage error database "backstage_plugin_catalog" does not exist type=errorHandler length=109 name=error severity=FATAL code=3D000 detail=undefined hint=undefined position=undefined internalPosition=undefined internalQuery=undefined where=undefined schema=undefined table=undefined column=undefined dataType=undefined constraint=undefined file=postinit.c line=888 routine=InitPostgres stack=error: database "backstage_plugin_catalog" does not exist
    at Parser.parseErrorMessage (/Users/stefanb/projects/backstage/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/stefanb/projects/backstage/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/stefanb/projects/backstage/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/stefanb/projects/backstage/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

## Your Environment

- NodeJS Version: 14.15.4

```
    "@backstage/backend-common": "^0.5.2",
    "@backstage/catalog-model": "^0.7.1",
    "@backstage/config": "^0.1.2",
    "@backstage/plugin-app-backend": "^0.3.6",
    "@backstage/plugin-auth-backend": "^0.3.0",
    "@backstage/plugin-catalog-backend": "^0.6.0",
    "@backstage/plugin-proxy-backend": "^0.2.4",
    "@backstage/plugin-scaffolder-backend": "^0.7.0",
    "@backstage/plugin-techdocs-backend": "^0.6.0",
```

**Comment by Fox32** [comment]
I have seen this error message before, but till now I thought it only happens if I not only restart the database but also delete all contents from it during the restart. For example if you start the database in Docker without any volume mounts. Can you confirm that the database content is still there after restart?

**Comment by stefanbuck** [comment]
Good shout. Indeed there was no volume attached and therefore the database was empty when restarting the container. Thanks for the hint.

Conclusion: Backstage does reconnect and if the database is not empty it will work.

**Comment by freben** [comment]
Good that it got sorted out! Thanks both
