### ISSUE TITLE
GA script missing in index.html template for standalone app

### ISSUE THREAD

**Issue by rbideau** [backstage/backstage#4576]
## Expected Behavior

In the [observability doc about google analytics](https://backstage.io/docs/plugins/observability#google-analytics), it says I can add a tracking id enable Google Analytics integration.

## Current Behavior

When creating a new app, the configuration `app.googleAnalyticsTrackingId` has not effect.

## Possible Solution

The script is only present in the app [index.html](https://github.com/backstage/backstage/blob/release-2021-02-16/packages/app/public/index.html#L52), not in the template for new app [index.html](https://github.com/backstage/backstage/blob/release-2021-02-16/packages/create-app/templates/default-app/packages/app/public/index.html#L51).

Additionally, content security policy for script-src must be overriden to allow `www.googletagmanager.com` and `'unsafe-inline'`, this could be said in the doc.
There have been discussions about the csp issue on discord [here](https://discord.com/channels/687207715902193673/687207715902193679/808359593847160852)

## Steps to Reproduce

1. Create a new standalone app: `npx @backstage/create-app`
2. Set `app.googleAnalyticsTrackingId` in app-config.yaml
3. Start the app

## Your Environment

- NodeJS Version (v12): v14.15.1
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10
- Browser Information: Firefox Developer 86.0b8
- Backstage version: [release-2021-02-16](https://github.com/backstage/backstage/releases/tag/release-2021-02-16)

**Comment by rbideau** [comment]
I will start working on a PR to fix the index.html and improve the doc

**Comment by freben** [comment]
Thanks, assigned!

**Comment by freben** [comment]
The doc could live under the new "integrations" section!

See this PR for inspiration https://github.com/backstage/backstage/pull/4561

It should be a new section Integrations -> Google Analytics -> Installation or whatever right

**Comment by rbideau** [comment]
@freben,  I was thinking about adding to the doc about [observability](https://backstage.io/docs/plugins/observability#google-analytics) under Plugin (the last one 😅)

But this could be moved to a new section Integrations -> Google Analytics -> Installation like you said,  I will to that.
