### ISSUE TITLE
Scaffolder Plugin: add audit log event when new repo created

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#4592]
Add an audti log event in scaffolder-backend plugin when new repos are created for improved observability.

## Feature Suggestion
Log event to capture who created repo, against which target org/project depending on SCM system.

## Possible Implementation

Log event should capture minimally : timestamp, user, destination repo/url

## Context

In our env, we have (unfortunately) very old Bitbucket Server, and AuthN and AuthZ of Bitbucket server is different from what we are planning to for Backstage. Hence, it will be a while we will be able to propagate the logged in user identity to our API integrations. 
Till we sort out some solution to synchonize/correlate the identity tokens between these two systems, We would like to report audit events via logging option.

**Comment by adamdmharvey** [comment]
May tie into #1519

**Comment by freben** [comment]
Yes, audit logging definitely ties into #1519. We don't have a great story for it now, and would love the input. If there are specific needs, specific systems or libraries, or specific areas that we should look into, let us know.
