### ISSUE TITLE
Improve the catalog experience on newly created apps

### ISSUE THREAD

**Issue by freben** [backstage/backstage#4613]
## Feature Suggestion

When doing `npx @backstage/create-app` as is recommended, the out-of-the-box catalog experience is_very_ barebones. Only Component and API kinds have dedicated views, and only service and website component types are handled.

This should be much richer and have more useful views out of the box.

## Possible Implementation

The template source for the entity page is [here](https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/packages/app/src/components/catalog/EntityPage.tsx). It should at least be much closer to the example app page [here](
https://github.com/backstage/backstage/blob/master/packages/app/src/components/catalog/EntityPage.tsx).

User and Group pages should use the org plugin.

Ideally the switch at the bottom should explicitly mention every single kind in the core model - including things like Template, for example - even if they are rendering the default view like before.

**Comment by BA1RY** [comment]
@freben I would like to work on this.

From what I've understood I'll have to make the template source for `npx @backstage/create-app` similar to the one in example app. Should end result be same as example app or anything extra should be added?

**Comment by freben** [comment]
Cool, thanks!

My immediate concern is the catalog pages. As mentioned in the description, it would be great if all kinds were mentioned explicitly so it's clear to a user where to go to add their custom pages. And that the org plugin's views are used for User and Group entities. And make sure that the structure of the code is similar :)

Maybe others have more ideas.

**Comment by adamdmharvey** [comment]
Good one.  I happened to notice the Sidebar is entirely different: create-app uses sidebar.tsx but the example uses a Root.tsx, so aligning that for sure!

**Comment by jvilimek** [comment]
Thanks all. As for our situation: we have used `npx @backstage/create-app` to prepare first version of our backstage app. Of course we added few plugins here and there. Now, when we want to upgrade to latest backstage core components and plugins we again run `npx @backstage/create-app` and compare the differences. Therefore having the newly created app to be working&up to date would be awesome. As for the upgrade: should we use another approach? E.g. comparing to the example app? Is it maintained / tested?

**Comment by BA1RY** [comment]
@freben I had a look at it and made few changes in `EntityPage.tsx` file present under `templates/default-app` folder. Then tried to run `npx @backstage/create-app` to test the changes. But, changes made are not reflected in the new app created. Not able to figure out why. Any idea why it's happening?

**Comment by jvilimek** [comment]
one additional info though: I was unable to use `npx @backstage/create-app`. I have to download current backstage github repo, run `yarn install`, switch to  `./packages/create-app/' and then `yarn backstage-create-app`. See [readme].(https://github.com/backstage/backstage/tree/master/packages/create-app)

**Comment by adamdmharvey** [comment]
@jvilimek The recommended path is not to create a new app each time you want to upgrade.

https://backstage.io/docs/FAQ#how-do-i-keep-my-backstage-app-up-to-date

Ideally, all of your customizations are stored in your app, and then you simply link to all of the plugins.  Then the CLI has the commands `versions:check` and `versions:bump`, which will update all of your dependencies.

Now, as the product is still in alpha, the CHANGELOGs are being used to identify if/when you have changes you need to make that relate to the INTERFACE of the plugin. (that is, a semantic version-compliance breaking change)  So you'll many times see a CHANGELOG entry that says something like, "This change to `@backstage/core` rewrites the routes, and to update your app you will need to do xyz.`

So if you use versions:bump, and follow the changelog, you should not need to use npx each time.  And when the product leaves alpha, and the [stability indicies](https://backstage.io/docs/overview/stability-index#docsNav) are more, um, stable, then you'll be able to better identify breaking changes via the version numbers.

Hope that helps!

**Comment by freben** [comment]
> @freben I had a look at it and made few changes in `EntityPage.tsx` file present under `templates/default-app` folder. Then tried to run `npx @backstage/create-app` to test the changes. But, changes made are not reflected in the new app created. Not able to figure out why. Any idea why it's happening?

You can run `yarn backstage-create-app` to run it directly - check the `node_modules/.bin` folder and you'll see the backstage scripts with their local names. They support being run "locally" (taking into account local code changes instead of using the remote)

**Comment by jvilimek** [comment]
FYI: thw original issue was error while stc on the newly created app via `npx @backstage/create-app` when compiling **backend/src/plugins/scaffolder.ts **:
```
Argument of type '{ preparers: PreparerBuilder; templaters: Templaters; publishers: PublisherBuilder; logger: winston.Logger; config: Config; dockerClient: Docker; database: PluginDatabaseManager; catalogClient: CatalogClient; }' is not assignable to parameter of type 'RouterOptions'.
  Object literal may only specify known properties, and 'catalogClient' does not exist in type 'RouterOptions'.
```
Now this seems to be more like dependency issue, namely the ["@backstage/plugin-scaffolder-backend@^0.7.1"](https://registry.yarnpkg.com/@backstage/plugin-scaffolder-backend/-/plugin-scaffolder-backend-0.7.1.tgz#1f00262162b2aaac18f5f461777004e0d3e4fe11) does not contain [this commit](https://github.com/backstage/backstage/commit/478d87e6129cef8f00c4af838fc4a25b11eeffc6) and thus the current version from create-app is broken...

**Comment by freben** [comment]
As mentioned in Discord - yeah, that indeed looks like a broken release. If you want to get unblocked quick, you could perhaps clone this repo and use `yarn backstage-create-app` from within it.

**Comment by freben** [comment]
Oh sorry - we already talked about that above. Lots going on now :)

**Comment by BA1RY** [comment]
Hi @freben , I'm not getting time to work on this. I've unassigned myself. Someone else can take this up.

**Comment by freben** [comment]
Ok, no worries!
