### ISSUE TITLE
[RFC] Component visibility level in backstage

### ISSUE THREAD

**Issue by Andrei-Predoiu** [backstage/backstage#4616]
**Status:** Open for comments

## Need

A lot of our teams have apis and components that they(and also our organization) want catalogued in backstage. That being said, some of these apis and components are considered private for the team, and clutter for everyone else.

## Proposal

Add a `visibleTo` option at the component level.

It works simmilar to owner, except it determines who can see the component in the catalog. Only the team set as visibleTo, along with all descendant will be able to see the component. 

If the value is missing then backstage should use the current behavior, where the component is visible to everyone.

## Alternatives

Add a visiblity option at the component level.

visibility would be `public`, `restricted` or `private`. 
Simmilar to object oriented programming concepts:
* `public` - The component is visible to everyone in the org
* `restricted` - The component is only visible to the owner team and descendants of the owner team
* `private` - The component is only visible to the owner team

## Risks

A big rist is that teams could default to making their components private. This goes against one of the core concepts of backstage. To combat this, i suggest that users should always be able to bypass the visiblity settings(with some work) through an option the the ui.

**Comment by freben** [comment]
Hi!

> Add a visibleTo option at the component level.

I think this would be unfortunate. Both for the reason you state, but also because we are probably longer-term going to add an access control system on top of the catalog. For example, something RBAC based that is tied to users' identities. With a system like that in place, we could apply it to visibility as well.

> Add a visiblity option at the component level.

This makes a lot of sense though. We've had this on our wish list since some time back. The hard part is to settle on the right set of classifiers, because there are several aspects that one might want to model. Whether something is for limited or general consumption. What reliability level it promises. What security classification level it has. What "tier" of service it is. Whether it is exposed to end users or employees only. Etc.

> public - The component is visible to everyone in the org
> restricted - The component is only visible to the owner team and descendants of the owner team
> private - The component is only visible to the owner team

Out of these, public and restricted make the most sense, but i would call restricted "private". We generally want ownership to be transitive "downwards" as a rule. I would also like to make it a "soft" rule - it would mainly affect search and the catalog view and similar - private things would be hidden by default but could be included by ticking a checkbox if you want to dive deep.

**Comment by jbadeau** [comment]
Just thinking out loud here:

Could these things not be managed by an auth model like [NGAC](https://thenewstack.io/why-you-should-choose-ngac-as-your-access-control-model)


> NGAC is based on the assumption that you can represent the system you want to protect in a graph that represents the resources you want to protect and your organizational structure, in a way that has meaning to you and that adheres to your organization semantics. On top of this model that is very particular to your organization, you can overlay policies. Between the resource model and the user model, the permissions are defined. This way NGAC provides an elegant way of representing the resources you want to protect, the different actors in the system, and how both worlds are tied together with permissions.

Companies with very open access would only need to manage a small set of policies but would scale to enterprises which have much more complex authorization needs.

Terms like Public, Private are Restricted are not always easy to apply to every organization.

I would be happy to try and map the backstage system model to a simple and moderately complex org structure?

**Comment by Andrei-Predoiu** [comment]
I took a look at NGAC and i think using graphs is great access management approach. 

Personally I am just looking to make things private at the team level and adding something like NGAC would make things a lot more complicated to configure.

**Comment by nadworny** [comment]
hi @Andrei-Predoiu - does this also apply to the software templates? I'm going through the open issues and trying to figure out if there is already RFC for Authorization but I don't find it. 

I'm basically trying to implement the following use case: define a software template that is only visible to a predefined group of people.

**Comment by Andrei-Predoiu** [comment]
I would like to have this setting for all components

**Comment by joeporpeglia** [comment]
Hey @Andrei-Predoiu, documentation for the Backstage permission framework is now available here: https://backstage.io/docs/permission/overview

This should support your need through the use of conditions defined in a [`PermissionPolicy`](https://backstage.io/docs/permission/writing-a-policy). Currently supported conditions for catalog entities are defined in the `catalogConditions` export of `@backstage/plugin-catalog-backend` (see [api-report.md](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/api-report.md)). Please open an issue if you find any problems along the way!

**Comment by Rugvip** [comment]
Gonna close this since the permission framework is shipped and covers this use-case

**Comment by bforbis** [comment]
> Hey @Andrei-Predoiu, documentation for the Backstage permission framework is now available here: https://backstage.io/docs/permission/overview
> 
> This should support your need through the use of conditions defined in a [`PermissionPolicy`](https://backstage.io/docs/permission/writing-a-policy). Currently supported conditions for catalog entities are defined in the `catalogConditions` export of `@backstage/plugin-catalog-backend` (see [api-report.md](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/api-report.md)). Please open an issue if you find any problems along the way!

The docs link you provided is dead. It should be https://backstage.io/docs/permissions/overview
