### ISSUE TITLE
Catalog plugin dev page crashes on load

### ISSUE THREAD

**Issue by egnwd** [backstage/backstage#4617]
## Expected Behaviour

When running the dev page in the catalog plugin, one should see some example catalog components.

## Current Behaviour

<details>
<summary>The page crashes with <code>No path for externalRouteRef{create-component}</code> and displays a white page (Full error in toggle block)</summary>
<pre>
Error: No path for externalRouteRef{create-component}
	resolve (hooks.tsx:60)
	mountMemo (react-dom.development.js:15465)
	useMemo (react-dom.development.js:15761)
	useRouteRef (hooks.tsx:126)
	CatalogPageContents (CatalogPage.tsx:85:99)
	renderWithHooks (react-dom.development.js:14826)
	mountIndeterminateComponent (react-dom.development.js:17506)
	callCallback (react-dom.development.js:189)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.development.js:238)
	invokeGuardedCallback (react-dom.development.js:293)
	beginWork$1 (react-dom.development.js:23235)
	performUnitOfWork (react-dom.development.js:22189)
	workLoopSync (react-dom.development.js:22162)
	performSyncWorkOnRoot (react-dom.development.js:21788)
	performSyncWorkOnRoot
	(anonym funktion) (react-dom.development.js:11112)
	unstable_runWithPriority (scheduler.development.js:653)
	flushSyncCallbackQueueImpl (react-dom.development.js:11107)
	workLoop (scheduler.development.js:597)
	flushWork (scheduler.development.js:552)
	performWorkUntilDeadline (scheduler.development.js:164)
</pre>
<pre>
The above error occurred in the <CatalogPageContents> component:
    in CatalogPageContents (at CatalogPage.tsx:215)
    in EntityFilterGroupsProvider (at CatalogPage.tsx:214)
    in CatalogPage (at extensions.tsx:52)
    in RoutableExtensionWrapper (at extensions.tsx:96)
    in Suspense (at extensions.tsx:95)
    in Extension(Component) (at dev/index.tsx:31)
    in GatheringRoute (at render.tsx:117)
    in FlatRoutes (at render.tsx:152)
    in div (at Page.tsx:71)
    in SidebarPage (at render.tsx:150)
    in Route (at App.tsx:342)
    in Routes (at App.tsx:341)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.tsx:340)
    in AppRouter (at render.tsx:149)
    in RoutingProvider (at App.tsx:278)
    in CssBaseline (created by WithStyles(CssBaseline))
    in WithStyles(CssBaseline) (at AppThemeProvider.tsx:94)
    in ThemeProvider (at AppThemeProvider.tsx:93)
    in AppThemeProvider (at App.tsx:277)
    in AppContextProvider (at App.tsx:276)
    in ApiProvider (at App.tsx:130)
    in Provider (at render.tsx:144)
    in DevApp (created by HotExportedDevApp)
    in AppContainer (created by HotExportedDevApp)
    in HotExportedDevApp (at render.tsx:184)

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
</pre>
</details>

## Possible Solution

I think it's because the DevApp doesn't have a notion of bindRoutes. In the example app this external route is bound in [App.tsx](https://github.com/backstage/backstage/blob/master/packages/app/src/App.tsx#L70). Whereas the DevApp just has the apis and plugins, we could add something like:
```diff
  const app = createApp({
    apis: this.apis,
    plugins: this.plugins,
+   bindRoutes({ bind }) {
+     // Add bindings from something like .addBinding(routeRef)
+   },
  });
```

I might be way off though.

## Steps to Reproduce

1. `git switch master` (I was on 1add977)
2. `cd plugins/catalog`
3. `yarn start`
4. Click the "🔖 Catalog" in the sidebar
5. 💥 

## Context

I found this whilst trying to work on the TechDocs plugin locally in the hope it would should me how to fix up the TechDocs dev environment 😅 (#4619)

## Your Environment

- NodeJS Version : v14.15.1
- Operating System and Version: macOS Big Sur (11.2)
- Browser Information: Tried in Chrome and Safari with the same result

**Comment by freben** [comment]
Yep indeed, confirmed, thanks for reporting! Should be fixed in https://github.com/backstage/backstage/pull/4632
