### ISSUE TITLE
Document MicrosoftGraphOrgReaderProcessor integration

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#4627]
Now that we have a good documentation for [`GithubOrgReaderProcessor`](https://backstage.io/docs/integrations/github/org) and [`LdapOrgReaderProcessor`](https://backstage.io/docs/integrations/ldap/org) thanks to #4561 we should also provide one for `MicrosoftGraphOrgReaderProcessor`.

* How to setup?
* How to configure? (Secrets, filters, ...)

**Comment by freben** [comment]
Would this be in an Azure section or a Microsoft Graph section? It's for more than just Azure right

**Comment by Fox32** [comment]
I'm not an expert of Microsoft products, but I think it's not related to Azure.

**Comment by TejasQ** [comment]
Are we sure about the `good first issue` label here? As a newbie, I'm not entirely sure where to get started if I decide to pick this up. Which – I'd like to pick this up if possible. 😬

**Comment by freben** [comment]
It would be a kinda good learning exercise for understanding the catalog, I think! You have the two other "Org Data" sections in the docs (e.g. [here](https://backstage.io/docs/integrations/github/org)) to base it off of, and it's mostly about documenting the config options etc which requires you to learn a bit about how config propagates in backstage. Little things like that. I can help out if you want.

**Comment by Amir-Abushanab** [comment]
Hi folks, if @TejasQ hasn't been assigned to this and isn't already working on it, I'd appreciate if I could take a stab at it

**Comment by Rugvip** [comment]
@TejasQ, do you want this one or should we pass it on to @Amir-Abushanab?

**Comment by jhaals** [comment]
Seems like @TejasQ is busy with other things :) it's all yours @Amir-Abushanab

**Comment by Fox32** [comment]
My PR for splitting this out into a separate package (#5854) also contains the documentation in the README. Do we just want to include a small page in the microsite that links to the README?
