### ISSUE TITLE
cost-insights: KubernetesMigrationAlert not exported

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4634]
Reusing some sample code, realized `KubernetesMigrationAlert.tsx` is not exported.

## Expected Behavior

I don't know if it's expected or not, but I copied the sample Cost Insights client and was trying to begin a custom one, and would have expected with only some base complex array definitions, that all source code could be pulled from the plugin.

## Current Behavior

Importing alerts from the plugin, I got this error:

![image](https://user-images.githubusercontent.com/33203301/108762596-49a5bf80-751e-11eb-8e9d-4bc238f6b009.png)

Checked, and it's in the plugin:

![image](https://user-images.githubusercontent.com/33203301/108762666-6215da00-751e-11eb-9008-1e025795dcfb.png)

But not explicitly exported in it's parent package:

https://github.com/backstage/backstage/blob/f7b951d9f5cfaf90eb5d228888a41ab100e52fdb/plugins/cost-insights/src/index.ts#L26

## Possible Solution

Export it, or replace the three exports to `*` to export them all up the tree.

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Context

What I'm missing as I learn this more, is if these are NOT intended to be reused per se outside of the plugin and are only intended for sample code.

As feedback, I think what throws me off as I walk through this is that it seems the plugin code itself is so intricately mixed in with the "sample" client API code that I would be expected to customize, that I'm finding it a bit tricky to figure out what I'm supposed to write as a full "my custom stuff" and put into my own app, versus what I'm expected to reuse OUT of the plugin (and that I get leverage with from doing like `yarn backstage-cli versions:bump`). Or am I supposed to 100% fork cost insights at all times, and never bump it, but any bug fixes or anything I need to rework manually back into my fork of cost-insights (I'd guess not).

So I almost wonder if the plugin could use some work in this area to better separate say all sample code into a folder with it's own README to say something like "copy this in to your scaffolded `/app/` folder or something, and leave the exports to ONLY those things which are relevant _specifically_ to the plugin itself, it's "service/library" as it were, though I know it's a bit complex.

I guess what I'm not understanding yet is if I need a `KuberentesMigrationAlert` in my app, or if that's representative of an example copied alert and I shouldn't worry about it.

All in all, a little clean up to either make it clear I don't need it, or that it works OOTB, may be needed.

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by adamdmharvey** [comment]
And maybe a suggestion: I wonder if the sample code should be refactored OUT of this plugin, and put into another one like `@backstage/plugin-cost-insights-sampleclient`. That way the patterns of what that uses out into the "shared library" cost-insights might be made more clear, and tests could be added to validate that contract, and then the "forking" is sort of users forking exactly the sample client and doing as they see fit?

**Comment by timbonicus** [comment]
Well observed, the `KubernetesMigrationAlert` was added recently as an example, so it's not intended to be exported - but that isn't clear from the code structure.

@backstage/silver-lining

**Comment by ryanvazquez** [comment]
@adamdmharvey An additional, full-on separate plugin would be a bit challenging to maintain and keep in sync with changes across backstage as well as change to the core plugin itself. We're a small team these days :) 

But to your broader point, I agree more could be done to make public/shared code more explicit - as well as call out implementation code more explicitly.

Some documentation could go a long way here too - users shouldn't have to delve too deeply into source code to know whats available OOTB or understand how to implement a custom alert, etc. We lean heavily on code comments for that at the moment but it's an approach that could be worth revisiting. We've prioritized this and will to put a little more love into our docs in the coming weeks.
