### ISSUE TITLE
API Catalog: Add the ability to customize table columns and filters

### ISSUE THREAD

**Issue by hostsamurai** [backstage/backstage#4637]
Add the ability for users to specify custom table columns, and the ability to
filter by them, to the API catalog plugin.

## Feature Suggestion

Having the ability to add custom fields inside of an API descriptor file's
`metadata` opens up the possibility for displaying this data in the API catalog.
Naturally, we would have the ability to filter by this data.

## Possible Implementation

Backstage already defines a set of default columns to display and filter by in
the API catalog. In addition to these, we would allow users to define any
additional columns and/or filters. We could allow the user to specify a list of
column names, if the columns are part of the default set, and `TableColumn`s
that denote the additional, custom columns to display. Filters would behave in
the same way.

For example, suppose that I want to display all of the default columns, with the
exception of 'System', and add a column to display the business domain that an
API belongs to. I would declare it like so:

```ts 
const domainColumn = { title: 'Domain', field: 'entity.metadata.domain' };
const customColumns = [
  'Name',
  'Description',
  'Owner',
  'Lifecycle',
  'Type',
  domainColumn,
];
```

My original implementation was based off `v0.4.3` of the plugin and added
`columns` and `filters` props to the `ApiExplorerPage` component. On `v0.4.4`,
the plugin changed to use the new [composability system](https://backstage.io/docs/plugins/composability#extensions), so it doesn't seem like
using props is the way to go with routable extensions, which `ApiExplorerPage`
now is. Any pointers for making these customizations available and configurable
via the host app are greatly appreciated.

## Context

At the moment, we have a business need to display a pair of custom columns that
denote the domain and capabilities for each of the APIs that we're listing in
the catalog, as well as filter by these fields. I did some work in modifying the
plugin to let us do this, with the intention of contributing the changes to
Backstage. This work was originally meant to happen in #3560 (full disclosure -
@tradcliffe-expediagroup is a colleague of mine), but the `api-docs` plugin
declares its own columns and filters.

**Comment by Rugvip** [comment]
👍 , should prolly biggy-back on #2791 for this.

Wanna clarify that you can definitely use props for routable component extensions if you want, it just that it may not be the nicest API always

**Comment by andrewthauer** [comment]
@Rugvip - I'm looking to expose the catalog index page as part of #2791. However, the table component as it currently sits is nested under a couple of children which as I see it would require bubbling up props children for a bunch of nested concerns. I'm curious if you have an example reference for what your actually thinking here?

**Comment by hostsamurai** [comment]
> you can definitely use props for routable component extensions if you want, it just that it may not be the nicest API always

Cool. Yeah, I totally see your point regarding props. My initial implementation lets me declare custom table columns and filters by declaring them like so:

```tsx
      <ApiExplorerPage columns={customColumns} filters={customFilters} />
```
But, I'm now thinking that using component data might make that cleaner. The argument that component data, "adds more structured access and simplifies evolution," from the docs is a compelling one. There is a bit of prop drilling going at the moment in my implementation, which, if I'm understanding things correctly, would be avoided by relying on that concept.

**Comment by andrewthauer** [comment]
I think we'd also want the columns to be able to change dynamically in some cases depending on a certain filter set. Also, a possible future case that allows the end user to customize the columns they want to see as a persisted preference.

**Comment by hostsamurai** [comment]
Okay, I took an [initial pass](https://github.com/backstage/backstage/pull/4845) at implementing this and am looking for feedback 🙂 . Hopefully, it is not too naive of an implementation. I also looked at #2791, but it didn't look like I could hook into any of its changes to help me drive the customization here.

**Comment by andrewthauer** [comment]
> Okay, I took an [initial pass](https://github.com/backstage/backstage/pull/4845) at implementing this and am looking for feedback 🙂 . Hopefully, it is not too naive of an implementation. I also looked at #2791, but it didn't look like I could hook into any of its changes to help me drive the customization here. 

#2791 is still a WIP and could change so that makes sense. I'd been mostly focused on refactoring the filter logic for now. Left some comments on your PR 😃.
