### ISSUE TITLE
Refactor plugins to use Backstage's <Breadcumbs> component

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4641]
## Feature Suggestion

A Backstage-specific `<Breadcrumbs>` component which uses the styling from this project was introduced in #4511.

See also storybook: https://backstage.io/storybook/?path=/story/layout-breadcrumbs--in-header

Three plugins still use `<Breadcrumbs>` from Material-UI and needs to be refactored to use the new component.

* [x] GitHub Actions #4686
* [x] CircleCI
* [x] CloudBuild

![image](https://user-images.githubusercontent.com/33203301/108800878-4f24f900-7562-11eb-9c6e-56c91f4fa415.png)

## Possible Implementation

Replace the import from Material-UI with one from `@backstage/core`, and ensure all compiling, testing, and the visuals still look good.

## Context

Standardize the user interface.

**Comment by wrousseau** [comment]
I've fixed this for the github actions plugin in #4686

**Comment by wrousseau** [comment]
Quick question @adamdmharvey, do we happen to have an example .yaml file that would easily allow to test the circle.ci plugin as well as cloudbuild? I can take care of both but would be easier if I don't have to create a component just for it

**Comment by adamdmharvey** [comment]
You should be able to just fake out an annotation for each, which will "turn them on". If the annotations aren't on https://backstage.io.docs/, then you'd likely be able to search their relevant plugins for the word annotation to find them. You could then throw that onto an entity metadata file.

_However_, that may not get you to the part of the app to let you SEE the breadcrumb?  It might, but it also might just error out and say not let you drill down to get to the part where you'd click back "up" a breadcrumb path.

If you're willing to take a stab though, that would be amazing.

**Comment by adamdmharvey** [comment]
Completed via linked PR; thanks @wrousseau !!
