### ISSUE TITLE
[RFC] UX change of entity horizontal tabs to left nav

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4648]
**Status:** Open for comments

## Need

As [noted in Discord](https://discord.com/channels/687207715902193673/687235481154617364/813437099743248425) and I think I've seen @freben mention it a few times:

> remove the tabs entirely and instead make it a filter in the left side of the page

This RFC is intended to drive feedback/comments into a more concrete UX spec which could then be picked up by someone to implement.

The demo's Spotify has shared publicly of their internal instance show this:

![image](https://user-images.githubusercontent.com/33203301/108805096-281ff480-756d-11eb-81c4-6268123ede3d.png)

They've grown and have many many more tabs than most example instances (at least that I've seen) yet of Backstage.

Versus what is in the open source app today:

![image](https://user-images.githubusercontent.com/33203301/108805987-7aade080-756e-11eb-974b-d3f82a01eb40.png)

## Proposal

* Movement of an entity's horizontal navigation to the left side of the screen.
* A very simple change of modifying the Material-UI `<Tabs>` element with a new `orientation="vertical"` property does some of this easily. (Note this is used in multiple places, see Risks section)
* Custom theming?
* Ability to define a tab's name with some sort of alpha property, or potentially elevate plugin metadata into the tab.

In `@backstage/core` in the `HeaderTabs.tsx` file, making this one line change:

```diff
<Tabs
        indicatorColor="primary"
        textColor="inherit"
        variant="scrollable"
        scrollButtons="auto"
        aria-label="scrollable auto tabs example"
+        orientation="vertical"
        onChange={handleChange}
        value={selectedTab}
      >
```

And then forcing the menu on left in `Tabbed.tsx` via these sort of changes:

```diff
    return (
      <>
+        <Box>
          <HeaderTabs
            tabs={tabs}
            selectedIndex={selectedIndex}
            onChange={onTabChange}
          />
+        </Box>
+        <Box>
          <Content>
            <Helmet title={title} />
            {currentRouteElement}
          </Content>
+        </Box>
      </>
    );
```
Gets us PART of the way there:

![image](https://user-images.githubusercontent.com/33203301/108805040-00c92780-756d-11eb-872d-a4fc7e549109.png)

## Alternatives

* Retain horizontal nav with the right arrow chooser which lets more and more tabs extend out to the right (but are hidden from view).
  * ![image](https://user-images.githubusercontent.com/33203301/108806094-bea0e580-756e-11eb-8f5a-e66920e96dd7.png)

## Risks

* The open source Backstage already has a left nav which drives to certain parts of the app and by convention is usually used for plugins which are not entity specific but could be more broad reaching (like Cost Insights which today isn't widget or entity based, but GCP project based). Adding another left nav to it begins to complicate the left side of the screen and reduces overall real estate horizontally.  This makes it even harder to view the app on smaller screens without a dynamic way of handling these menus.
* The current `<HeaderTabs>` component is used in multiple places in the app, including to select different entity kinds in the catalog, and so wholesale replacing some of the elements in this tab may not be possible. So I think the risk is in making any key changes to the existing tabbing needs to ensure it doesn't change where horizontal tabs may want to be kept? (if they do at all)

**Comment by Fox32** [comment]
Oh, I thought @freben actual meant the tabs above the catalog table?

I have to admit that I actual like the tabs on the entity page. Right now the tabs don't take up much space compared to a vertical layout. But they might not scale well with many entries.

**Comment by adamdmharvey** [comment]
All the better to collect comments 😀

**Comment by Rugvip** [comment]
We do have some ongoing design research that might touch on this, so will hopefully have some updates in the future.

Will add that the horizontal tabs is the newer design, which we use in some places internally as well
