### ISSUE TITLE
techdocs rendering with github app error

### ISSUE THREAD

**Issue by ebarriosjr** [backstage/backstage#4656]
While testing the new githubapp implementation in the techdocs plugin I discovered that if the techdocs reference still starts with githib: instead of url: the docs will not render and there is no error message stating this. You only see in the backend logs that the default branch could not be fetch. 

## Expected Behavior

Should render the docs even with the old github: url in the techdocs ref.

## Current Behavior
A blank page is returned and only an error in the backend logs shows up. But it doesn't tell you the reason.

## Possible Solution
Add an error message in the frontend stating the change in the techdocs ref or implementing the github app for old github refs

## Steps to Reproduce

1. Set up github app on backstage
2. Add a component with the old techdos reference
3. Try to render the docs

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by OrkoHunter** [comment]
Hey @ebarriosjr! @backstage/maintainers can correct me if I am wrong but UrlReader is capable of working with the GitHub Apps implementation. So, you should be using `url:` to make use of the GitHub Apps and not the `github:` (which is basically a simple `git clone` of the repository, and has no advance token fetch mechanism using GitHub Apps. Details #4409)

**Comment by ebarriosjr** [comment]
Hey @OrkoHunter , I see what you mean, and you are right. I am using a githubApp. I still think it would still be nice to get a warning or an error on the logs and not just a blank page. just my 2 cents :)

**Comment by OrkoHunter** [comment]
Sure, I agree. As of now, TechDocs build logs can only seen in the Backend. I'll close this issue in favour of https://github.com/backstage/backstage/issues/3579 :)
