### ISSUE TITLE
Error when I run yarn install

### ISSUE THREAD

**Issue by Jerry4013** [backstage/backstage#4660]
Hi, 

I clone the backstage repo and run yarn install, but there are some errors at the end.

`[5/5] Building fresh packages...
[11/20] ⠠ cypress
[10/20] ⠠ keytar
[-/20] ⠠ waiting...
[-/20] ⠐ waiting...
warning Error running install script for optional dependency: "C:\\Users\\*************\\code\\backstage\\latest0223\\node_modules\\ke
ytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: C:\\Users\\***********\\code\\backstage\\latest0223\\node_modules\\keytar
Output:
prebuild-install WARN install No prebuilt binaries found (target=14.15.4 runtime=node arch=x64 libc= platform=win32)
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.15.4 | win32 | x64
gyp info find Python using Python version 3.9.1 found at \"C:\\Users\\***********\\AppData\\Local\\Programs\\Python\\Python39\\pytho
n.exe\"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the \"Desktop development with C++\" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\\Users\\***********\\code\\backstage\\latest0223\\node_modules\\@npmcli\\run-scrip
t\\node_modules\\node-gyp\\lib\\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\\Users\\jingchao.zhang\\code\\backstage\\latest0223\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp
\\lib\\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\\Users\\***********\\code\\backstage\\latest0223\\node_modules\\@n
pmcli\\run-script\\node_modules\\node-gyp\\lib\\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\\Users\\***********\\code\\backstage\\latest0223\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp
\\lib\\find-visualstudio.js:70:14
gyp ERR! stack     at C:\\Users\\***********\\code\\backstage\\latest0223\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp
\\lib\\find-visualstudio.js:372:16
gyp ERR! stack     at C:\\Users\\***********\\code\\backstage\\latest0223\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp
\\lib\\util.js:54:7
gyp ERR! stack     at C:\\Users\\***********\\code\\backstage\\latest0223\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp
\\lib\\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\***********\\\\code\\\\backstage\\\\latest0223\\\\no
de_modules\\\\@npmcli\\\\run-script\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Users\\jingchao.zhang\\code\\backstage\\latest0223\\node_modules\\keytar
Done in 859.60s.`

## My Environment

- NodeJS Version (v14.15.4):
- Operating System and Version: Windows 10 enterprise
- npm: v6.14.10

Thanks!

**Comment by freben** [comment]
Seems that it includes detailed instructions on what you need to do, including installing visual studio and the `"Desktop development with C++" workload`. So this is because `gyp` that compiles native modules must have a C++ compiler present.

**Comment by Jerry4013** [comment]
@freben Thank you for your quick reply! I'll try it. Do you think it is necessary to add this requirement in the docs of Backstage?
