### ISSUE TITLE
Pagerduty Plugin: Error: No ApiProvider available in react context 

### ISSUE THREAD

**Issue by athal7** [backstage/backstage#4661]
## Expected Behavior

Page renders

## Current Behavior

Page not rendering, with the console error: `Error: No ApiProvider available in react context`

## Possible Solution

n/a

## Steps to Reproduce

1. Follow the instructions in the README 
2. Visit overview page

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3): v0.3.0
- Backstage version (e.g. 0.1.1-alpha23): 0.6.0
- NodeJS Version (e.g. v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): Docker node:14-buster
- Browser Information (e.g. chrome 85): chrome 88

**Comment by freben** [comment]
Hi! Go to the project root and run `yarn backstage-cli versions:check` and then probably with the `--fix` argument. You seem to have multiple conflicting versions of the Backstage libraries in your lockfile. It can happen.

**Comment by athal7** [comment]
Thanks @freben!
