### ISSUE TITLE
User Identity lifecycle: addressing inactive users and their relationship to owned kinds

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4666]
## Feature Suggestion

It would be nice if the Backstage UI somehow interpreted inactive/disabled identities out of the corresponding integration to help elevate issues which should be addressed in the overall system.

e.g.,

![image](https://user-images.githubusercontent.com/33203301/108886787-62be7700-75d7-11eb-89ec-dcdfc44bd052.png)

We are using an `integrations.processors.githubOrg` to load up an org's membership to align them to components.  We have a few users who left the firm, but the relevant components still are assigned to them. (a gap we need to fix!!)

Currently, the components show their ownership, and I can bring their card up which looks like this:

![image](https://user-images.githubusercontent.com/33203301/108885921-5f76bb80-75d6-11eb-9feb-a669a3bad0be.png)

So they do technically exist in the org, and do have an account in our GitHub that represents their commit history. (this user also had teams, but it seems that when flagged as suspended, their membership is no longer reflected which is good, but they as a user still exist to maintain commit tracking)  However, they are flagged as suspended:

![image](https://user-images.githubusercontent.com/33203301/108886129-96e56800-75d6-11eb-8408-6e8c2b3dfc2e.png)

Would be great for a similar style indicator to be reflected up into Backstage.

## Possible Implementation

* Does it make sense to keep the lifecycle consistent and use a `spec.lifecycle` attached to a User entity as an indication as to whether they still exist?  Many times users stay in systems like this as a reference point, even if they aren't technically valid anymore to own or have accountability or be assigned to work. (e.g., in our Jira we also disable users who left the firm, but don't immediately say close all of their backlog items they reported or change that - we keep it knowing THEY reported it even if they are no longer active and can't continue to report new work or be assigned to it)
* Reflection on the User entity card
* An ability to elevate this type of info out of different providers. I'd guess this type of suspension/active/inactive sort of flag may exist in other providers?
* Ability to search for this, which could let me say elevate a card on the System entity page to show all components in a system with no valid owners. (this could include components that lack owners too)
* With the new search architecture, possible ability to decorate search results so inactive users are clearly indicated  ( cc @emmaindal  )
     ![image](https://user-images.githubusercontent.com/33203301/108887042-b8931f00-75d7-11eb-94f7-42edbc815674.png)

**Comment by emmaindal** [comment]
I really like this, thanks for opening the issue @adamdmharvey and sharing your ideas. With this, we build trust which is more and more important the more components you have within your organization. But also can help close the gap you are touching on: 
> We have a few users who left the firm, but the relevant components still are assigned to them. 

because you will be able to more easier see what users are inactive and active, it will help someone who maybe "manage groups and metadata" to update the ownership of these components. 

To add to the list I believe a indicator such as "owner inactive" even on TechDocs sites can be valuable.

**Comment by freben** [comment]
Makes sense. I was initially thinking that maybe we should not have inactive users in the catalog, which may lead references to be dangling, which is also detectable and actionable. However, what you propose makes this more intentional and clear (instead of trying to assign meaning to the very binary there-or-not-there predicate).

`lifecycle` could work. Not sure what's best there and if there are other classifiers that may apply and overlap. Any suggestions are welcome from the community.

**Comment by adamdmharvey** [comment]
This of course also has tie ins with #4089.

Re @freben yep.  If an inactive user is removed from Backstage and a component is left without owner, obviously we could identify entities without owners. But actually _leaving_ an owner but knowing that owner is invalid has an engineering leadership value, where if you know who owned it before, the knowledge of that may help realize, "Oh Jeff was on the *silver-lining* squad and he left, so this component likely should be elevated up to be owned by the entire squad rather than an individual. I'll go modify the metadata. _Fixed!_"  The inactive users could even end up being a page or a plugin that is perhaps targeted at leadership rather than exploring the individual entities, sort of targeting a @leemills83 persona, that would be something that needs to be addressed at a leadership/mgmt perspective rather than within a squad itself.

We recently did a reorg of one team, and we've got a great strategy on moving from one system to another, but in that process, I worked with teams to review 400 repos tagged to an org where we did find both those which should be retired but caught a few which were still in production and yet weren't "officially" tagged to be tagged specific squad.  So indeed it's all about elevating and as you said intentionally exposing this.
