### ISSUE TITLE
[Plugins] api-docs is missing oauth2-redirect.html

### ISSUE THREAD

**Issue by n2ygk** [backstage/backstage#4668]
## Expected Behavior

Using API-docs with an openapi spec file that includes OAuth 2.0 Authorization Code flow, one should be able to "Authorize" in swagger-ui in order to "Try it out."

## Current Behavior

404 error for `http://localhost:3000/oauth2-redirect.html?code=<code>&state=<state>`

## Possible Solution

Add a static `oauth2-redirect.html`.

Apparently `swagger-ui` implements this but `swagger-ui-react` doesn't. See Limitations at https://github.com/swagger-api/swagger-ui/tree/master/flavors/swagger-ui-react. I don't quite understand why that would be.

## Steps to Reproduce

I don't have a public way to reproduce this but see [this OAS schema doc](https://github.com/columbia-it/django-jsonapi-training/blob/master/docs/schemas/openapi.yaml) which demonstrates an OAuth 2.0 Authorization Code flow.

When I run this with my OAuth2 service, all the redirects work for the login up to the final redirect back to
/oauth2-redirect.html which there's no route for.

## Context

Unable to use the "Try it out" functionality when using OAuth 2.0 Authorization Code flow.

Screen shots:

Swagger UI:
![image](https://user-images.githubusercontent.com/4356471/108908763-b3db6480-75f1-11eb-85b6-312ca0f5d9be.png)

Clicked Authorize and filled in client credentials, selected scopes. etc:
![image](https://user-images.githubusercontent.com/4356471/108908338-2d268780-75f1-11eb-838e-d030b70bf796.png)

(Shibboleth/CAS redirects not shown.)

OAuth 2.0 scope approvals:
![image](https://user-images.githubusercontent.com/4356471/108908396-416a8480-75f1-11eb-96da-c9af48cfc87e.png)

Mic drop!
![image](https://user-images.githubusercontent.com/4356471/108908497-5d6e2600-75f1-11eb-899c-d698121fd64b.png)

## Your Environment

- @backstage/plugin-api-docs: 0.4.6
- NodeJS Version (v12): v14.15.4
- Operating System and Version (e.g. Ubuntu 14.04): MacOS Catalina 10.15.7 (19H524)
- Browser Information: Chrome 88.0.4324.182 (Official Build) (x86_64)

**Comment by Fox32** [comment]
Oh, this is an interesting use case. I guess we won't be able to provide that file under that location form the plugin, but you should be able to place the file in `packages/app/public`.

**Comment by n2ygk** [comment]
> Oh, this is an interesting use case. I guess we won't be able to provide [that file](https://github.com/swagger-api/swagger-ui/blob/master/dist/oauth2-redirect.html) under that location form the plugin, but you should be able to place the file in `packages/app/public`.

I believe that will require some configuration in swagger-ui is all.

**Comment by n2ygk** [comment]
OK, so this seems really easy with no need to change the swagger-ui `redirect_url` location.  Just copy oauth2-redirect.html into packages/app/public.

I'll try to figure out a PR for this...

**Comment by Fox32** [comment]
If you create a PR, can you document it in the README of the `api-docs` plugin too?

**Comment by freben** [comment]
And make sure (by html comments or whatnot) that the file clearly explains its purpose for future unknowing readers

**Comment by n2ygk** [comment]
Hmm, I'm not sure why swagger-ui-react is missing `oauth2-redirect.html`. See https://github.com/swagger-api/swagger-ui/issues/5384

I'm loathe to copy the file into the `plugins/api-docs/dist` as that doesn't feel right.... 

@Fox32 I would appreciate some guidance on how to add a `postinstall` script to package.json (or whatever the correct mechanism is) to copy the static content to packages/app/public.

Or do I have to add it to `packages/create-app/templates/default-app/packages/app/public/`, effectively decoupling it from the plugin?

**Comment by Fox32** [comment]
Not sure if I would make it full automated. Isn't if sufficient to tell the user in the README to copy the file from the repository into the `packages/app/public/` folder if he wants to use that feature?

I think api-docs is part of the default-app, so adding it there would be an option too.

**Comment by n2ygk** [comment]
I could always do that, but, as a user of this plugin, I would find it to be really nice if it "just worked" out of the box. If upstream swagger-ui-react had oauth2-redirect.html include in dist/ would it get installed anywhere useful by default? Or would it still need to get copied to packages/app/public? I'm a newbie when it comes to npm/yarn package management.

I guess just having it as part of the default create-app, even though decoupled from the plugin, would be better than requiring someone to follow steps in a README.

What do you think @freben?

**Comment by Fox32** [comment]
I don't think that it's possible to fix that upstream. Coping the file to that location has to be done in Backstage, as it is quite specific to the repository setup. If you want to automate it, I guess a post install hook might be useful, but I'm not an expert there.

Including it in the default create-app would make sense, as the api-docs plugin is installed by default.
