### ISSUE TITLE
Unable to build on MacOS BigSur - node version incompatibility 

### ISSUE THREAD

**Issue by RobbieJVMW** [backstage/backstage#4674]
When I attempt to build and deploy the example app using MacOS BigSur (11.2.1 - 20D74 ). 
yarn run fails with the error : 

The engine "node" is incompatible with this module. Expected version "12 || 14". Got "15.10.0"

## Expected Behavior

example application to build. 

## Current Behavior

yarn run v1.22.1
error root@1.0.0: The engine "node" is incompatible with this module. Expected version "12 || 14". Got "15.10.0"
error Commands cannot run with an incompatible environment.

## Possible Solution

Update build script to support more recent version of node. 

## Steps to Reproduce

Using MacOS BigSur
Homebew to setup deps. 

1. brew install yarn
2. brew install node 
3. yarn docker-build

## Context

This issue is impacting my initial investigation into the project. 

## Your Environment

- NodeJS Version (v12): Node 15.10.0
- Operating System and Version (e.g. Ubuntu 14.04): MacOs BigSur ( 11.2.1 )
- Browser Information: Safari Version 14.0.3 (16610.4.3.1.4)

**Comment by freben** [comment]
Yes, we haven't yet tested fully with node 15. While I do expect it to probably work, our target is, and will remain for a while longer, the latest LTS release which is 14.

You may want to install the `nvm` tool to easily co-deploy several node versions and easily switch between them.

**Comment by RobbieJVMW** [comment]
How best can I get involved with the node 15 testing and validation effort ?

**Comment by Rugvip** [comment]
@RobbieJVMW We're currently sticking to the LTS releases, so next version we'll be looking at supporting would be 16, which should have its initial release in about 2 months

**Comment by freben** [comment]
Just checking @RobbieJVMW - does this present a problem to you? In terms of alignment on what your org recommends using internally etc.

**Comment by RobbieJVMW** [comment]
Not really, I just need to spin up a LinuxVM rather than doing a local build on MacOS.  In terms of adoption supporting MacOS for build/deploy falls into my 'quick and easy to try' I will spend more time looking into this project.    It maybe something worth considering.

**Comment by freben** [comment]
Point taken!

Did you have the ability to use nvm? That's what we use and happily switch back and forth between several installed versions in different projects - no linux vm necessary usually.

**Comment by freben** [comment]
And to be clear - we are mainly on MacOS all of us as well. On both the previous OS version and the new one.

**Comment by Rugvip** [comment]
Alright to close @RobbieJVMW? Assuming that running v14 with rosetta is alright for now. It should also be possible to override the engine requirements in separate apps/forks

**Comment by RobbieJVMW** [comment]
Yup its all working locally for me now, thanks for the dialog.
