### ISSUE TITLE
Suggestions based on using the catalog importer

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#4683]
I've been playing with the catalog importer today and I thought I would open an issue to collect some thoughts. If these are reasonable requests I can open individual issues and close this. 

### Type configuration

The Entity configuration section should have an option to set the `type` of the component being created.

![preparing-pull-request-entity-configuration](https://user-images.githubusercontent.com/562403/109021536-e13c1700-76b2-11eb-8510-e43cad693407.png)

### Going to the imported entity

There should be some way to go to the entity that will be created by clicking a link. I'm guessing this is tricky because the link will 404 if the PR hasn't been merged yet? 

This feels like what I want to do as a user. I took an action and next I want to see the effect of that action. 

Is there any way to detect when the PR is merged so we could have a link which is enabled/disabled based on the merge state of the PR?

![Screenshot 2021-02-24 at 15 16 04](https://user-images.githubusercontent.com/562403/109022295-98d12900-76b3-11eb-9a48-0b6a8e68277d.png)

### Specific "component" copy

I notice the text specifies "Component" but in reality any kind of entity can be added via this interface. Is importing all kinds of entity via this interface the expected mechanism to add them? Even templates seem to be importable here.

![Screenshot 2021-02-24 at 15 20 02](https://user-images.githubusercontent.com/562403/109023518-c5d20b80-76b4-11eb-9708-e9e1afb9c412.png)

**Comment by wrousseau** [comment]
Taking a spin at it if that's ok. i'm suggesting an autocomplete field with all types of entities.

**Comment by Rugvip** [comment]
@wrousseau Sounds good, thank you! :grin:

Will assign you to make sure we don't end up with duplicate efforts, let us know if we should un-assign

**Comment by wrousseau** [comment]
I've made a pull request, awaiting tests to pass #4704
It addresses 2 of the topics you mentioned, I feel like the "Going to the imported entity" is a bit more complex. Maybe we should open a separate issue for it?

**Comment by dhenneke** [comment]
This "you created a pr and registered the location but you need to wait until you merged the pr and the catalog refresh loop did it's work" intermediate state is indeed unfortunate and hard to explain to the user. Maybe we want to register the entities "temporarily" in the catalog and they will be replaced with the correct ones once the location processor read them from the repo? But I'm unsure how this could look like.

**Comment by adamdmharvey** [comment]
Agree with you @dhenneke . There's also the challenge of hanging entities.  I played around a bit, and had closed a PR instead of merging it, and realized I orphaned an entity in the catalog which kept warning in my backend console log that it could not be found at it's target location. There is nothing stopping the owner of the target repo from rejecting the PR and say asking for a new one with a different name, which might permanently leave the catalog with that hanging entity. The PR function as a whole I think is extremely valuable, but has some quirks which still need working out.

**Comment by wrousseau** [comment]
What I think would work best:
* V2 : there is a hook that is called by github when the PR is merged so that the entity is created only then
* V3 : the front-end polls (or websocket) to update the front-end in case the user merges the PR real fast and stays on the backstage tab
