### ISSUE TITLE
Unregister entity modal goes full screen when width < 960 px

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4685]
## Expected Behavior

The unregister entity popup is a modal that pops above content in all situations when attempting to perform the unregister function. It centers in the middle of the screen and lets the user click it.

## Current Behavior

I had my screen moderately sized, and clicked the unregstier entity by using the vertical dots link at far top right of an entity, and discovered below 960px the modal goes full screen:

![image](https://user-images.githubusercontent.com/33203301/109042901-b5af3180-769e-11eb-8bc1-a737422b76ed.png)

<kbd>
<img src="https://user-images.githubusercontent.com/33203301/109042487-41748e00-769e-11eb-8c29-e909ae19c7f4.png" />
</kbd>

## Possible Solution

I think going full screen is good, but maybe 960px width is too large for this flex to trigger?

## Steps to Reproduce

1. Make your Backstage window less than full screen
2. Open an entity
3. Click the two dots at top right to trigger an Unregsiter entity, then click unregister
4. See a modal which is centered in middle of screen.
5. With the modal centered, reduce the width to 960px (you can guess or use Chrome DevTools responsive which tells you the number) and you'll see the modal go full screen.

## Context

This may have been entirely intentional, controlled globally, or something else, but it just surprised me and given the small size of the content in the modal, just seems very large to be breaking to flex at that size; open to counter opinions on it.

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information: Microsoft Edge (Chrome 8x)

**Comment by wrousseau** [comment]
This behavior does not seem to be what Material-ui recommends as I don't see any breakpoint on https://material-ui.com/components/dialogs/

So my recommendation would be to remove the behavior to be consistant with material-ui. what do you think?

**Comment by kaos** [comment]
#4729 missed the "closes" keyword in the ref to this issue... ;)

**Comment by freben** [comment]
indeed
