### ISSUE TITLE
Broken link on External Integrations page

### ISSUE THREAD

**Issue by lndbrg** [backstage/backstage#4688]
## Expected Behavior

When clicking the `Next` link at the bottom of the [External Integrations](https://backstage.io/docs/features/software-catalog/external-integrations) page I expect the link to take me to a valid documentation page

I also expect the `Next` link to have a more descriptive text than `Next`, like the other documentation navigation links that exists.

## Current Behavior

The `Next` link takes me to the url https://backstage.io/docs/features/software-catalog/kubernetes-in-backstage which results in a github 404 page.

## Possible Solution

I see 2 possible solution:

1. Remove any and all documentation such as no links exists. 

2. Figure out why there's no descriptive text for that link and why it sends you to a 404 page.

I personally believe that option 2 is the much better option to go with

## Steps to Reproduce

1. Open https://backstage.io/docs/features/software-catalog/external-integrations
2. Scroll to the bottom
3. Click next

**Comment by freben** [comment]
Yep! We don't control the buttons so the reason it has no text is probably related to why it's 404ing

**Comment by OrkoHunter** [comment]
I think the fix is to remove this line
https://github.com/backstage/backstage/blob/674202d2d2d5f05eec7279b168cdf77daa69ebe1/microsite/sidebars.json#L62

**Comment by ShubhamPatel33** [comment]
Hi,i wanted to take this issue and solve but on the integration page at the end i see a button of API and it dosen't led to a 404 page,is it solve ?

**Comment by lndbrg** [comment]
Yup, it seems to be fixed with https://github.com/backstage/backstage/pull/4421
