### ISSUE TITLE
Document the API

### ISSUE THREAD

**Issue by jcarres-mdsol** [backstage/backstage#4694]
Backstage has an HTTP API, for instance `api/catalog/entities` but I do not think it is documented anywhere. Maybe I just could not find it.
If not documented, then ideally an openapi file could be used to document the API.

**Comment by freben** [comment]
Hi! Yes, this is definitely a need. We are still iterating on the APIs but as they settle we will want to have specs for them.

There's already [this](https://github.com/backstage/backstage/issues/2566), maybe yours could be considered a duplicate of that?

**Comment by Rugvip** [comment]
👍  to the idea, but as freben mentioned I think this is close enough to #2566 that I think we can close and continue the discussion there.
