### ISSUE TITLE
EntityLinksCard Improvements

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#4717]
## Feature Suggestion

There are a couple of things that could improve the overall experience of the new'ish `EntityLinksCard` component.

#### 1. Help & Support

Provide a help / support link to the `EntityLink` documentation even when there are links already added (non empty state)

#### 2. An "Edit" button

Once entity links are established it's not necessarily obvious how to edit them.

Having an edit button that takes you directly to the catalog file in SCM edit mode so you can add links in GitHub etc might be nice. Ideally this would point directly to the `metadata.links` section if it exists. Not exactly sure the idea behaviour for when the `links` field is completely missing, so maybe that's where the support link / hint might come in.

Another approach might be to have a wizard that can open a PR and or build the require yaml for you and/or insert the additional links. This is more ambitious but would provide a better experience and less error prone.

## Considerations

- Some Backstage integrators have custom and/or external catalog feeds that don't point to a SCM `catalog-info.yaml` file. It might be nice to have the edit button customizable. In fact some code was recently added for the other `edit` links to do this. Perhaps that can be leveraged in a shared way.

- Since it's possible to add links via a catalog processor there also may not be any links in the actual `catalog-info.yaml` file. This could mean there are links in the UI but not in the actual physical `catalog-info.yaml` file. This could be potentially be confusing to those unfamiliar with how the automatically added ones go there. Not exactly sure about this. Maybe some small glyph that indicates they where auto added might be useful. However, this may require the processor (e.g. `EntityLinksProcessor` to add an additional field to those links so the card knows when to shoe this visual indicator. It would probably be ok to split this concern apart from the main goal of the edit button though.

## Possible Implementation

![image](https://user-images.githubusercontent.com/6507159/109307902-515faf80-780f-11eb-881e-3e0c4048efc8.png)

- Modify the [EntityLinksCard](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityLinksCard/EntityLinksCard.tsx)
- May require using code that may or may not exist in `@backstage/integration` to provide an appropriate edit link.
- Using GitHub accepts an options line number fragment on edit links (e.g. https://github.com/backstage/backstage/edit/master/catalog-info.yaml#L7). Perhaps the component could fetch the `catalog-info.yaml` file before to try and find the `links` field which may or may not exist?

**Comment by adamdmharvey** [comment]
Great points!  If I could throw one more in there, I think the content layout could still do with a bit more tweaks. I can't say specifically, but I've happened across a few weird ones that show up like this:

![image](https://user-images.githubusercontent.com/33203301/109312941-a30b3880-7815-11eb-806b-6427c0ddcd9a.png)

Essentially, it's a relatively long title which wraps, AND wraps away from the icon.

**Comment by andrewthauer** [comment]
@adamdmharvey - That is true. I was fully aware that could and will happen in some cases so that's why there is also a `cols` prop on the card which lets you set the number of columns in total (e.g. `cols={2}`) or for each media break point (e.g. `cols={ lg: 4, md: 2, sm: 1 }`). It's really hard to predicate how big this card will be based on how it's used in the entity page and at which breakpoints. Unfortunately I couldn't find a better solution with the material-ui components as is. That said, I'd love to hear some ideas around addressing this in a better way.

**Comment by Fox32** [comment]
About the edit link, I think the new annotation (backstage.io/edit-url) and my changes in #4702 should give you all you need.

**Comment by Fox32** [comment]
> Using GitHub accepts an options line number fragment on edit links
Would be cool, but that link doesn't work for me 😞

**Comment by andrewthauer** [comment]
> > Using GitHub accepts an options line number fragment on edit links
> 
> Would be cool, but that link doesn't work for me 😞

@Fox32 - Interesting. I've tried in both Firefox and Chrome and it works for me. It's not as noticeable as line number highlighted for PR's, but there is a little cursor on the line #7 in my case.

**Comment by Fox32** [comment]
Tried it again, this time it worked. Maybe I just missed the very little cursor 😆

**Comment by Rugvip** [comment]
Wanna through in that we probably don't wanna be polluting the entity page with too many buttons and places to edit things, I think the help button makes sense, but perhaps that one could point to the main metadata card as a method for editing the entity yaml? Also helps keeping that concern in a single place where we handle edge cases like the entity not being editable etc.

**Comment by freben** [comment]
Agreed ^ frankly I've been pondering whether we should strip out all actions and move them to a dedicated actions bar at the top instead... No design set in stone at all, but having actions spread out all over the viewport will make things hard to find indeed
