### ISSUE TITLE
[RFC] Provide a new entrypoint to the onboarding process of new or existing things into the catalog

### ISSUE THREAD

**Issue by dhenneke** [backstage/backstage#4741]
**Status:** Open for comments

> This RFC focuses mainly on `Components` though this applies to other entity kinds as well.

## Need

There are different ways to get content into Backstage:
1. Use the _scaffolder plugin_ to create a new component and register it automatically.
2. Let the users create `catalog-info.yaml` files in their repositories and use the _catalog-import plugin_ to register them manually (either with a direct link to a file or a function like "discover files in repository").
3. Use the _catalog-import plugin_ to assist the users by creating a Pull Request/Merge Request that creates a generated `catalog-info.yaml` in their repositories and registers it automatically.

Then there are special configurations with automated processes:

4. Have a reader that automatically finds all `catalog-info.yaml` files in a (GitHub) orgainzation (e.g. the [`GithubDiscoveryProcessor`](https://github.com/backstage/backstage/blob/d7a5bfd57ff09062523df1572370197900550783/plugins/catalog-backend/src/ingestion/processors/GithubDiscoveryProcessor.ts)).
5. Have a custom processor that derives the catalog entities from all source code repositories or from a third-party source.

Each integration will have different configurations depending on their workflow or their tooling:
* Some will use **1.**, **2.** & **3.** as equally valid options
* Some will use **4.** only, while others might want to use **4.** in combination with **3.** and/or **1.**
* Some will use **5.**, but might also want to use **1.**

### Current State

Currently, the equality of the flows **1.**, **2.**, and **3.** is not represented by the `Create...` page:

<img src="https://user-images.githubusercontent.com/720821/109497613-99423900-7a92-11eb-89b4-639326c01267.png" width="500">

Once on the "Register Existing Component" page, flows **2.** & **3.** are entangled which requires a coherent and complex wizard behavior and extensive documentation to tell the user what to expect for what inputs:

<img src="https://user-images.githubusercontent.com/720821/109498548-e07cf980-7a93-11eb-874a-de4b25402b6d.png" width="500">

To conclude: We need a more coherent onboarding process that guides the user to the available options and lets the integrators customize the experience to their liking.

## Proposal: Create a new onboarding page

One option could be to add a new onboarding route in front of the scaffolder/catalog-import. Citing @freben (https://github.com/backstage/backstage/pull/4271#issuecomment-770630625):

<img src="https://user-images.githubusercontent.com/720821/109500752-ec1def80-7a96-11eb-9dd2-6af3aaf82307.png" width="500">

* This makes it obvious that the three options are equally valid
* Integrators might choose to skip an option or might want to add additional ones (e.g. a link to what users need to do if their components are missing in scenario **4.** or **5.**).
* Handling the different flows "add existing catalog-info.yaml" (**2.**) and "help to create a catalog-info.yaml" (**3.**) separately allows the catalog-import plugin to have more targeted and reduces docs for the flows.

Since this component is heavily dependent on the integrators, I would tend to manage this in the application itself, instead of putting it into either the scaffolder or the catalog-import, or into a new plugin. The `create-app` cli could provide a reasonable default page which can then be customized by either reordering or removing/adding things. The scaffolder and catalog-import plugins could then include docs in their Readme which instruct the users how to add them to the default `OnboardComponent` and export route refs to directly jump to the correct flows.

This could be some follow-up steps to get it running:

1. Get a UI/UX person to compile a well-looking and -usable onboarding page.
> This should also account that the users might not be experienced with the Backstage terminology but are used to company specific language. There are also discussions around the term "Create a Component" as this might also be used to create Systems, APIs, … (see also #4683 or #4704).
2. Create the `OnboardingPageComponent` and mount it at the `/create` route. I'm not sure if this fits perfectly into the composability concepts so this might be implemented as a routable-extension?
3. Refactor the catalog-import plugin to make the [different flows](https://github.com/backstage/backstage/blob/ec832c5bf6c08a59131b17eddc6a31e2fc19fa33/plugins/catalog-import/src/components/useImportState.ts#L22-L26) directly addressable via router-params and add a tailored input-page for [each flow](https://github.com/backstage/backstage/blob/ec832c5bf6c08a59131b17eddc6a31e2fc19fa33/plugins/catalog-import/src/components/ImportStepper/defaults.tsx#L105) and revisit the docs section of the plugin.

### Add legacy options as scaffolder cards

Another option could be to add the options for legacy projects as options in the template selection:

<img src="https://user-images.githubusercontent.com/720821/109500017-f986aa00-7a95-11eb-99f0-37ab6a7f08fa.png" width="500">

* (Same as before): Handling the different flows "add existing catalog-info.yaml" (**2.**) and "help to create a catalog-info.yaml" (**3.**) separately allows the catalog-import plugin to have more targeted and reduces docs for the flows.
* Seeing it side-by-side to the other templates could be a good idea as it maybe not necessarily is a "Golden Path" but a good alternative to that.
* Mixing the domains of scaffolding and importing might be confusing. Especially as one might not want to have these options at the first ones, this functionality can become quite hidden and unintuitive inbetween all the templates easily.

This alternative might be easier to implement(?) but I would prefer the other option since it guides the user better and lets the most room for customizations.

## Risks

---

I would be happy about getting feedback on this topic so we can create a plan to get this implemented if we get to an agreement about the next steps.

**Comment by regicsolutions** [comment]
One idea that comes to mind is being able to map a group/team to a SCM Org/Project once that mapping has been established for the group, they could click a “Discover” button and it would return a list of repositories that have not been on boarded into Backstage. This could replace the register existing component button.

**Comment by freben** [comment]
@regicsolutions That look great. I think that kind of a repo picker is useful both for the import and register flows. But I think the use case of just pasting a URL is so quick and smooth that we want to have it easily available too.

@dhenneke I vote for the three "hero" buttons upfront I think :) I also think that it should be an app-owned page, where the default is to just render a single default element that ... maybe core? exposes. It could make use of the [optional external routes](https://github.com/backstage/backstage/pull/4700) feature to enable/disable each of the three buttons (and immediately navigate to it if just one of them was given). And it would be replaceable just [like the `SignInPage` is](https://github.com/backstage/backstage/blob/master/packages/app/src/App.tsx#L64). @Rugvip does that sound like a sensible use of facilities / features?

**Comment by jinnjwu** [comment]
why automaticly close it，a great idea
