### ISSUE TITLE
Custom tab in Techdocs Homepage

### ISSUE THREAD

**Issue by adrianke77** [backstage/backstage#4757]
Would like to have some way to have a custom tab in Techdocs Homepage with a view of lists of documentation landing sites filtered by tags or predicate functions.

## Feature Suggestion

We're looking for a way to show particular subcategories of documentation in a clear way to users. Specifically we would like to show each subcategory as a horizontal list of cards much like the current Overview (but probably with shorter cards to save on screen space).
![image](https://user-images.githubusercontent.com/14866712/109630831-53639e80-7b80-11eb-9337-d3831c2f2221.png)

## Possible Implementation

1) Pass some configuration in createApp or in App.tsx that specifies a custom tab's layout. Eg:
```
const customTab = {
  tabName: "Main Documents",
  widgets: [{
      title: "Product Documentation",
      type: "cardlist",
      filterTag: "product"
  },{
      title:"Tech Bulletins",
      type: "cardlist",
      filterPredicate: (entity: Entity) => entity?.metadata?.tags.includes('bulletin'))
  }],
};
```
Items listed in the `widgets array` would be understood to always occupy their own full rows (multiple widgets on one row could be an array within the main array), and thus flow vertically down the tab display. 
 
Eg the above would show two horizontal rows of cards with their own title, possibly two cards tall, with their own scrollbars if list of documents exceeds two rows. 

Additional widgets could be added to this system over time, such as something like the large catalog view with filters that is Owned Documents, with a custom filter predicate (a full width very tall widget), or this small view that could stack horizontally:
![image](https://user-images.githubusercontent.com/14866712/109638617-2d8ec780-7b89-11eb-955f-3858fde5791e.png)

With this approach existing pages could be also refactored to use this tab configuration approach. 

2) Allow passing in a render function to TechDocs somehow that renders the whole tab. It would be useful to allow some way for this function to import UI components from TechDocs plugin, not sure if this is feasible?

**Comment by emmaindal** [comment]
Hey @adrianke77 thank you for opening this issue 🎉 
Customization of TechDocs homepage and tabs is definitely interesting as we move forward. To open up the flexibility to custom your homepage based on your organizations needs. I'll loop @garyniemen in here for some comments from a product perspective and then I'll think it through myself and add some comments from my side.

**Comment by garyniemen** [comment]
Can we get view from @katz95 ...I know we did have some Figmas from a while back.

**Comment by emmaindal** [comment]
So with the configuration above specified in `App.tsx` for example, something like this is what you expect to be rendered @adrianke77?

<img width="805" alt="Screen Shot 2021-03-03 at 2 16 05 PM" src="https://user-images.githubusercontent.com/25153114/109812219-1a810380-7c2c-11eb-9b65-19a586261499.png">

**Comment by JacobValdemar** [comment]
I would like to add that any kind of customization of the Techdocs overview page is something we at Lunar would be very excited about - it's currently very hard to find and locate your docs. I think your awesome design proposal @emmaindal would improve our developers' satisfaction with finding docs immensely! 🚀 I'm not completely up to date with what's happening in different plugins, but some kind of filtering would also be nice 🙂 But first things first 🙂

**Comment by adrianke77** [comment]
@emmaindal More or less what you've mocked up with small changes
1) each row automatically adds a scrollbar to itself only if there are more items than can be shown in, say, two rows
2) cards to be shorter as there seems to be quite a bit of empty space in existing cards. I suggest three rows of text space available for description, and additional text be ellipsed out

**Comment by adamdmharvey** [comment]
To suit your Item 1 there, @adrianke77 , the horizontal scroll grid component could be put in use:
https://backstage.io/storybook/?path=/story/layout-horizontalscrollgrid--default

And to suit your Item 2, agree, that was recently updated in the template section as well here:
https://github.com/backstage/backstage/pull/4759

**Comment by adrianke77** [comment]
Ah very nice. I'll start work on this sometime next week probably.

**Comment by katz95** [comment]
hi! unsure how relevant this might be for you all, but there was an exploration of tabs a while back: 

https://github.com/backstage/backstage/issues/2028#issuecomment-718736681

https://github.com/backstage/backstage/issues/2028#issuecomment-718737662

we typically use horizontal tabs as the first level of sub navigation/categorising

**Comment by adrianke77** [comment]
@katz95 thanks, I'll try to structure it so it's possible to have designs similar to what is highlighted there.

**Comment by adrianke77** [comment]
I was thinking the config object could be passed to TechdocsPage in routes in App.tsx but it doesn't seem to work that way. Any suggestions how to get a config object passed to the TechdocsHome component ? (preferably in Javascript so we can pass filter predicates along)

**Comment by freben** [comment]
Regarding the specific question of screen space:

On later versions of Backstage these cards have been revamped in core. On current master, this is what it looks like

![Screenshot 2021-03-18 at 11 21 55](https://user-images.githubusercontent.com/3097461/111610909-2946e900-87dc-11eb-911c-da16e72d6909.png)

**Comment by soapraj** [comment]
@freben @patriko - the larger question is around a general pattern of how to extend / customise plugins. The requirement to have a custom config would mean the `plugin-techdocs` needs to be changed to accept custom config that is either passed from App or read via config?

I do see a few ways in which this could be done

1) Create a new techdocs plugin `plugin-custom-techdocs` that would reuse the components from `plugin-techdocs` and export its own version of the TechDocsHome and TechDocsPage components. The config for tabs (and predicates to use) could be part of the custom plugin? 

2) Wrap the TechDocsPlugin in App.tsx with a Context and pass a custom config JSON which could be read anywhere in the tree and this would mean we make changes to the `plugin-techdocs` which is common for everyone which I think is fine.

3) Is there a way to pass custom JSON via ConfigApi? I remember ConfigApi can read files as String. Do you think this a good approach? or is there a case here for ConfigApi to support read JSON files?

@realandersn @iamEAP - please do chime in if I have missed anything.

**Comment by adrianke77** [comment]
I would opt for 2 from the perspective of least effort to implement, but perhaps this is a chance to have a standard pattern to pass custom configuration objects to plugins, at least for their frontend portion.

**Comment by adrianke77** [comment]
Are there any comments/suggestions on if we can use approach 2) above? I can start implementation effort once we can decide on it.

**Comment by freben** [comment]
In general in a situation like this, I favour composability, using JSX, over any other more hardcoded solution.

The way we have designed the catalog/entity pages, is that the user has the chance to design their layout any way they like, and the catalog plugin provides the component building blocks for you to do that in the most effective way.

If we want users to be able to tweak their docs landing pages, which sounds like a thing that will be asked for a lot, would it make sense to do something like the following?

- Have the core and/or the techdocs plugin export components such as `Card`, `CardGrid`, `HorizontalScrollGrid`, etc that can be composed - including even higher-level things like `OwnedDocumentsGrid` or whatever that does all of the legwork of finding all your owned docs and rendering them in a grid in the default way
- Have the techdocs plugin export something like a `DefaultTechdocsPage` that is what users with basic needs could choose to mount on that route. That one most likely uses `OwnedDocumentsGrid` and the other similar facilities
- The user can mount whatever else they want to have on the route in question if they want to customise things

```tsx
// In the app's App.tsx
<Route path="/docs" element={<MyCustomTechdocsPage />} />

// In your @internal/custom-techdocs-react or whatever
export const MyCustomTechdocsPage = () => (
  // ... use either some techdocs exported TechdocsLayout facility,
  // or even go so low level as to rendering your own Page/Header/HeaderTabs etc etc
);
```

this does probably require that techdocs is fully migrated to the composability system to be effective

**Comment by freben** [comment]
now having said that, even if we based things on this "base approach" of replacing the page with your own content - the techdocs plugin could _even so_ also export a convenient config driven component that you can _choose_ to put in that custom JSX if you choose to use it. The point is, then power users aren't limited to that one facility, and can choose to do whatever they want on top of the page if they like to

**Comment by iamEAP** [comment]
Thanks @freben and thanks @adrianke77 for your patience and willingness to contribute!

After (re-)familiarizing myself with the plugin and reading over the above thread, I'm inclined to recommend going with the composability approach over the context approach (e.g. number 1 in @soapraj's post, as described in more detail by @freben above).  I'm not sure that "tabs configured via JSON / with a filter predicate" is going to cover future needs.  ...But exposing the building blocks and allowing folks to iterate seems like a great way to find out.

Maybe the way to achieve it would be to extract the `<Table>` rendering from `<OwnedContent />` and the `<ItemCardGrid>` rendering from `<OverviewContent />`, and spin them out to their own, exported components (e.g. `<DocTable entities={[]} />` and `<DocCardGrid entities={[]} />`?

**Comment by adrianke77** [comment]
So this would mean the custom documentation landing page will show on a different route? As with frontend plugins at the moment.

**Comment by adrianke77** [comment]
So it seems a first step would be moving TechDocs to composability API, and then a second step is exposing the <Table>, <ItemCardGrid> and similar as exported renderer components that take an entity list. Does this sound right?

**Comment by iamEAP** [comment]
@adrianke77 your proposed sequence of TechDocs composability API compatibility + components sounds right.

**Comment by adrianke77** [comment]
Could someone more knowledgable take a look at the TechDocs frontend as it is now and comment on what changes are needed for migration to composability system? I've been taking a look but it seems a lot of required items exist already. @iamEAP ?

**Comment by adrianke77** [comment]
PR created for first step above:  https://github.com/backstage/backstage/pull/5218

**Comment by adrianke77** [comment]
Hey I have a suggestion. How about we do both ?
So 
1) TechDocs homepage will have a hardcoded config that produces the current landing page (overview + owned tabs)
2) A optional custom config object passed by context to TechDocs can produce a custom landing page (customization restricted to one of each per tab: rendering function, title, description, entity filter function)
3) We also export DocTable and DocCardGrid that both take a array of Entities, for those who want to do more indepth customization.

My guess is that 2) will cover quite a lot of customized landing page use cases (including my own), so it's valuable to have it out of the box with just a config object. I'm already mostly done with 3) as it turns out to be not much effort, so I could include all of this in one PR.

**Comment by adrianke77** [comment]
^ PR created

**Comment by adrianke77** [comment]
@iamEAP now that it's already merged in hindsight i'm thinking it would have been better to have each custom tab simply specify a single component to render everything in that tab. So that component could make use of DocTable and DocCardGrid if it wanted to, or include other view elements - I'm already getting requests from my side to be able to customize the columns in DocTable..

**Comment by freben** [comment]
Those kinds of request indeed tend to crop up...

Striking the right balance with what to make tweakable, and in what way, is tricky. On the backend side of things, we've started naming things `Default*` more and more to clarify that this is the default impl but you can substitute your own.

Translated to the fronted world you might have exported a `DefaultXPage` that renders a `DefaulyXTable` (which is just an `XTable` with sensible defaults, which in turn is just a `Table` with even more defaults), for example. Then you'd not spend too much effort making the `DefaultXTable` tweakable because there's the escape hatch of digging down to the next level instead.

Does that make sense? It can all depend a lot on circumstances...
