### ISSUE TITLE
Squad/Group page ownership

### ISSUE THREAD

**Issue by jlind23** [backstage/backstage#4758]
Squad/Group Page includes a summary of components ownership.
![image](https://user-images.githubusercontent.com/43535167/109636066-6dcf5500-7b4b-11eb-808c-574d0759f79f.png)

## Feature Suggestion

Components must be clickable in order to explore the ownership of every group and teams

## Context

Trying to easily discover teams ownership.

**Comment by dhenneke** [comment]
There is no view where these cards can link to, yet. But I guess this will be added or at least enabled by #2791 so the catalog table can display entities filtered by author.

**Comment by jlind23** [comment]
If links can be translated into a single query field then yes it will do the job. 👍 
Like application search with owner="jlind23"

**Comment by andrewthauer** [comment]
This may not be directly addressed by #2791 as it's probably going to get a bit big. But it should hopefully provide the basis for being able to filter by a query strings.

**Comment by freben** [comment]
Eventually we will be able to link to the /catalog page with appropriate filters. Closing for now
