### ISSUE TITLE
Ability to resolve duplicate catalog items

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#4760]
Where a location provides two catalog items with the same name, we see the database insert statement fail due to a database constraint.

## Feature Suggestion
This highlights a larger question around conflicting ownership of names and namespaces. e.g. if two components use the same name, who or what resolves this conflict. At present, backstage will honor the first component that comes along unless they come together at the same time.

Minimum solution:
The backstage backend either chooses one of the two components and inserts it and logs that it has ignored the second one.

Possible solution:
Surface to the administrator of backstage that multiple components have conflicting catalog definitions and allow mechanism to resolve this by ignoring one or the other.

## Context
An attempt was made to fix this by the following pull request https://github.com/backstage/backstage/pull/4720.

**Comment by desktophero** [comment]
At scale, I think applying the `namespace` and `component` identifiers will help remove the collision or at least give a better sense of what is needed. I'm referencing the [Entity References](https://backstage.io/docs/features/software-catalog/references#string-references) docs, so my understanding of the problem statement and approach is a bit constrained and does start to imply a new semantic for `namespace`.

**Comment by Rugvip** [comment]
Yep! Namespaces are supposed to be a tool for keeping naming sane among other things. We do also want to be able to deal with both accidental and intentional naming collisions though, not only by trying to avoid them but by having a strict set of rules for how conflicts are resolved.

**Comment by GoWind** [comment]
Not sure, but I have a feeling that this is in someways tied to the aliasing proposal in my  [RFC](https://github.com/backstage/backstage/issues/4961) (last comment).

**Comment by desktophero** [comment]
Another aspect of the duplicate item topic is handling multiple versions of the same service that are concurrently supported, like V1 and V2 of `api/someawesomeservice`. The repo and component are still one "thing" but with multiple versions. Would concurrent versions be something to address or is that already handled?

**Comment by freben** [comment]
We believe that this is fixed in the rewritten catalog engine. There may be some corner cases, one of which we are addressing as we speak, but this more general ticket can be closed now.

The intended solution:

- The first location to "claim" an entity with a given reference, wins
- This fact is persisted in the database; there's a connection between the entity in the database, and the location that actually spawned it
- Future attempts to overwrite that entity from a different location, are rejected and the error is surfaced on the other entity that tried to emit this conflict

**Comment by freben** [comment]
@desktophero This is kind of a separate discussion, but an interesting one. Typically, the V1 and V2 of an API are effectively completely different "things" - even if they may or may not be serviced by the same underlying deployable thing. So you would often choose to have a `MyApiV1` and a `MyApiV2` entity, possibly exposed by the same `MyService` (or two different).
