### ISSUE TITLE
FeatureFlagsApiRef is loaded into the app before ConfigsApiRef

### ISSUE THREAD

**Issue by Raffitzz** [backstage/backstage#4761]
## Expected Behavior

I should be able to use ConfigsApi inside my custom FeatureFlagsApi override.

## Current Behavior

FeatureFlagsApiRef is loaded into the app before ConfigsApi making it impossible to generate our custom ApiFactory, having ConfigsApi as a dependency. The following error is thrown: `Uncaught Error: Tried to access config API before config was loaded`. 

## Possible Solution

Loading ConfigsApiRef in before FeatureFlagsApiRef.

## Steps to Reproduce

1. Create an ApiFactory
```
export const apis = [
    createApiFactory({
        api: featureFlagsApiRef,
        deps: { 
            configApi: configApiRef
         },
        factory: ({ configApi }) => new MyFeatureFlagsApi(configApi),
      }),
]
```
2. Launch the server and access it through the frontend.
3. Open the browser console and observe the error `Uncaught Error: Tried to access config API before config was loaded` is thrown.

## Context

I need to override the behavior of FeatureFlagsApi and to do so I need to access some environment variables inside, therefore I will need to have the config loaded as a dependency.

This was my stacktrace:
```
Uncaught Error: Tried to access config API before config was loaded
    at Object.factory (index.esm.js?f1dc:2013)
    at ApiResolver.load (index.esm.js?f1dc:136)
    at ApiResolver.loadDeps (index.esm.js?f1dc:145)
    at ApiResolver.load (index.esm.js?f1dc:135)
    at ApiResolver.get (index.esm.js?f1dc:121)
    at PrivateAppImpl.getRoutes (index.esm.js?f1dc:1879)
    at Module.eval (App.tsx?0f9c:41)
    at eval (App.tsx:103)
    at Module../src/App.tsx (main.chunk.js:57)
    at __webpack_require__ (runtime.js:854)
```

## Your Environment

- NodeJS Version (v14.15.5)
- MacOS Catalina 10.15.7
- Google Chrome

**Comment by benjdlambert** [comment]
I wonder if we can move around the priority and fix so that config is loaded first. Will try and take a look at this tomorrow.
