### ISSUE TITLE
Release-2021-02-23  version bump -  issues with bitbucket server integration ( packages ) 

### ISSUE THREAD

**Issue by kaparwan** [backstage/backstage#4765]
## Expected Behavior

Read Bitbucket template URL - when adding through /create 

## Current Behavior

Unable to read URL : 401 UnAthorised 

Unable to read url, Error: https://mybitbuckethost.com/projects/PRJ/repos/app-examples/browse/composite-yaml/catalog-info.yaml could not be read as https://mybitbuckethost.com/rest/api/1.0/projects/PRJ/repos/app-examples/raw/composite-yaml/catalog-info.yaml?at=, 401 Unauthorized

## Steps to Reproduce

1.   create mono-repo
2.   yarn install; yarn tsc; yarn build
3. yarn backstage-cli versions:bump
4.  yarn tsc; yarn build
3.   run docker for both frontend and backend
4.   register template ( nodejs/java/..) using /create
5.   fill template values
6.   storagePath: https://<mybitbucket_host>/<PRJ>/repos #PRJ -> my project in bitbucket
7.   Click next
 

## Your Environment

NodeJS Version (v12): v14.15.4
Operating System and Version (e.g. Ubuntu 14.04): UBuntu14
Browser Information:: Chrome
Atlassian Bitbucket v5.11.1 (own-hosted)

**Comment by kaparwan** [comment]
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/24486542/109746367-5ff00180-7c29-11eb-9ade-1fd0ead9d00c.png)
 error log screenshot

**Comment by OrkoHunter** [comment]
Is there any chance that your Bitbucket token has expired or does not have scope to read that file? Clearly Bitbucket API is rejecting Backstage's request for authentication.

I am looking at our logic to set the authentication request header, and it hasn't been updated in 3 months. https://github.com/backstage/backstage/blob/28ac6aefb0901fe07eb580a7ed2ef7c23ef5b787/packages/integration/src/bitbucket/core.ts#L148-L171

Could you try sending a manual request to that URL and use the token or the username/password combo in the header, to see if the it's still valid?

**Comment by kaparwan** [comment]
Thank you @OrkoHunter 
I will test it  update.

**Comment by kiranpatel11** [comment]
@kaparwan 

This is not an issue, the env variables are not getting set due to switch to powershell. syntax for setting env variable is different.
Please close the issue.
