### ISSUE TITLE
Not able to install anything in project directory using yarn like Redux , react-bootstrap, react-router etc

### ISSUE THREAD

**Issue by sanjeetCoder** [backstage/backstage#4774]
## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by OrkoHunter** [comment]
If you install the frontend packages inside `packages/app` and the backend packages inside `packages/backend`.

Also the issue needs more information with logs and errors.

**Comment by sanjeetCoder** [comment]
Actually I was trying to install outside packages/app. Now it's working

Thank you
