### ISSUE TITLE
Not able to create microservices and entity, templates etc.

### ISSUE THREAD

**Issue by sanjeetCoder** [backstage/backstage#4775]
## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by OrkoHunter** [comment]
Issue lacks information. How are you running Backstage, what are the errors in the browser and/or backend when you try to do this?
