### ISSUE TITLE
backstage.spotify.net is not working

### ISSUE THREAD

**Issue by sanjeetCoder** [backstage/backstage#4776]
## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by OrkoHunter** [comment]
Hey! That is an Spotify-internal website and not supposed to be accessed publicly.

We do have a publicly hosted demo if you want to checkout https://demo.backstage.io
