### ISSUE TITLE
while installing package using npm, it deletes some backstage file.

### ISSUE THREAD

**Issue by sanjeetCoder** [backstage/backstage#4777]
## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by OrkoHunter** [comment]
Backstage uses `yarn` over `npm`.


Your issue needs more details. e.g. I was trying to do install package `@backstage/x` and it deleted the file y, and here are the logs from the terminal.

**Comment by sanjeetCoder** [comment]
Actually I was trying to install redux, react-router etc outside packages/app. Now it's working

Thank you
