### ISSUE TITLE
Add explicit config option for webpack: publicPath

### ISSUE THREAD

**Issue by geototti21** [backstage/backstage#4780]
## Feature Suggestion
👋 Hey team, we are hosting Backstage as an immutable app and now the app grows in size so it starts utilizing the Chank feature of webpack. While this happened we started getting an error `ChunkLoadError: Loading chunk XX failed. react` that means we couldn't load the chunk files. The problem was the `publicPath` was set to "/" but as we have immutable app the static files are not served in the same location.

Our workaround was to replace this path in runtime https://stackoverflow.com/questions/39879680/example-of-setting-webpack-public-path-at-runtime

But we would like to have this set on build time if possible. I can see this managed [here](https://github.com/backstage/backstage/blob/49be39b92a7c2c76f1a8f709c165de20dcede400/packages/cli/src/lib/bundler/server.ts#L49) and uses the `app.baseUrl` config but it doesn't work when we want to set something explicitly: eg. "https://our-central-place-for-static-files"

## Possible Implementation

We can possibly introduce a config option, that can override the existing implementation and fall back to it if not set? 🤔 
```yaml
app:
  publicPath: "https://our-central-place-for-static-files"
```

## Context

Thanks  and let me know what you think 🚀

**Comment by Rugvip** [comment]
@geototti21 I'm a bit confused, are you using the webpack dev server to serve the app in production, but then at the same time fall back to a static file server for some of the assets?

What would the `app.publicPath` be able to do that we can't do with `app.baseUrl`? Where would be use that config value?

Regarding the chunk load error, is it something that happens consistently when loading the initial page, or intermittently when browsing? It may be that dynamically loaded chunks need a fallback, but it could also be something else. Would need to get a bit better understanding of your deployment strategy to be able to help out.
