### ISSUE TITLE
core: Add ErrorApi helper that catches unhandled promise rejections and forwards them

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#4782]
## Feature Suggestion

Add an `ErrorApi` helper that catches unhandled promise rejections and forwards them to an `ErrorApi` implementation.

## Possible Implementation

Something like an `UncaughtErrorForwarder` class that uses the [unhandledrejection  event](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event#preventing_default_handling) to capture uncaught promise rejections.

Could be something like this:

```tsx
class UnhandledErrorForwarder {
  static forward(errorApi: ErrorApi) {
    ...
  }
}
```

And then we hook it up as a part of the default `ErrorApi` implementation [here](https://github.com/backstage/backstage/blob/28ac6aefb0901fe07eb580a7ed2ef7c23ef5b787/packages/core/src/api-wrappers/defaultApis.ts#L68) like so:

```ts
createApiFactory({
  api: errorApiRef,
  deps: { alertApi: alertApiRef },
  factory: ({ alertApi }) => {
    const errorApi = new ErrorAlerter(alertApi, new ErrorApiForwarder());
    UnhandledErrorForwarder.forward(errorApi);
    return errorApi;
  }
}),
```

## Context

Suggestion by @grantila that we handle unhandled rejections somehow.

**Comment by freben** [comment]
candidate: https://www.npmjs.com/package/trace-unhandled

**Comment by tudi2d** [comment]
Would like to work on this 👍
