### ISSUE TITLE
allow configuration of default branch for new repositories created by templates

### ISSUE THREAD

**Issue by the-mikedavis** [backstage/backstage#4785]
## Feature Suggestion

:wave: hello!

In our org we use `main` as the default branch for new repositories. When creating new components through the templates feature, though, new repositories are made with a `master` branch. It'd be great if we could specify in a Template manifest which branch we'd like to use; I know some people like `main` and others like `trunk`.

## Possible Implementation

I think an optional input called `branch` could be a good place to configure this in the manifest for the `publish:github` step. E.g. from the docs on template manifests using the `backstage.io/v1beta2` api version:

```diff
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:cookiecutter
      input:
        url: ./template
        values:
          name: '{{ parameters.name }}'

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is {{ parameters.name }}'
        repoUrl: '{{ parameters.repoUrl }}'
+       branch: main
```

It could be an optional field defaulting to `master` to keep backwards compatibility.

## Context

Isomorphic git's [`init`](https://isomorphic-git.org/docs/en/init.html) function appears to be the culprit defaulting the `master` branch right now.

Looks like it'd need a modification here: https://github.com/backstage/backstage/blob/eba975b693/packages/backend-common/src/scm/git.ts#L153-L160

```typescript
  async init({ dir }: { dir: string }): Promise<void> {
    this.config.logger?.info(`Init git repository {dir=${dir}}`);

    return git.init({
      fs,
      dir,
    });
  }
```

Which is called here in the `initRepoAndPush` helper (would probably need to take on a new parameter for branch): https://github.com/backstage/backstage/blob/eba975b693/plugins/scaffolder-backend/src/scaffolder/stages/publish/helpers.ts#L38-L40

```typescript
  await git.init({
    dir,
  });
```

And then that change will need to be consumed in the `plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/<provider>.ts`, e.g. for github: https://github.com/backstage/backstage/blob/eba975b693/plugins/scaffolder-backend/src/scaffolder/stages/publish/github.ts

```typescript
  return createTemplateAction<{
    repoUrl: string;
    description?: string;
    access?: string;
    repoVisibility: 'private' | 'internal' | 'public';
  }>({
    id: 'publish:github',
    schema: {
      input: {
        type: 'object',
        required: ['repoUrl'],
        properties: {
          repoUrl: {
            title: 'Repository Location',
            type: 'string',
          },
          description: {
            title: 'Repository Description',
            type: 'string',
          },
          access: {
            title: 'Repository Access',
            type: 'string',
          },
          repoVisibility: {
            title: 'Repository Visiblity',
            type: 'string',
            enum: ['private', 'public', 'internal'],
          },
        },
      },
```

(I think that'd need a new input for branch defaulting to `master`)

I'm not much of a typescript or even javascript developer but I'd be happy to give this a try at some point. If anyone has ideas and wants to go ahead and implement this, though, don't wait for me :slightly_smiling_face:

**Comment by regicsolutions** [comment]
Also looking to do this as well but using the template name + app name input variable as the branch name. Would also be nice to be able to create a pull request action as well. 

@blam any suggestions?

**Comment by benjdlambert** [comment]
yep - I think adding the `branch` or `defaultBranch` option to the new action seems like the way forward. Maybe just make it optional and default to master if it's not provided. @the-mikedavis i'll assign you now, but if someone else want's to pick it up sooner then go ahead.

@regicsolutions yep, so we've built the scaffolder in a way that it's much more flexible now. You can create actions to grab files from wherever, or use the custom ones we've builtin.

The `fetch` built in action will go and grab the `.tar` of the repo, without the git history, so I'd say that if you wanted to do git actions like creating branches etc, it probably makes sense to create an action to `clone` the repo using the `git` helper, and then create another action which does the `create-branch` for you. Then a seperate one to create a `pull-request`. All of these seems like actions we'd likely accept into the builtin ones too.

**Comment by OrkoHunter** [comment]
Looks like `defaultBranch` is now available in all publish actions (github, gitlab, azure, etc.). Looking at `/create/actions` in backstage.
