### ISSUE TITLE
Support GHE in new workflow link in Actions Plugin

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#4790]
## Feature Suggestion

Currently the link to create new workflows is hard coded to github.com. Can we instead read the `integrations.github.host` config so that this will link correctly to GHE instances?

## Possible Implementation

Build the url using the `integrations.github.host` config and default to github.com if not defined. 
## Context
https://github.com/backstage/backstage/blob/073bba7151adb463a6d62d30c802cf41019ce79a/plugins/github-actions/src/components/Cards/RecentWorkflowRunsCard.tsx#L84

**Comment by adamdmharvey** [comment]
This _might_ be an easy one. Just a few lines above where the owner and repo var are defined, is the hostname:

https://github.com/backstage/backstage/blob/073bba7151adb463a6d62d30c802cf41019ce79a/plugins/github-actions/src/components/Cards/RecentWorkflowRunsCard.tsx#L56-L61

I don't have GHE actions running, but maybe you'd be willing to give it a shot and if it works, file a PR for it @kuangp ?

**Comment by kuangp** [comment]
Thanks @adamdmharvey I made the changes according to your suggestion and its working correctly linking to my GHE instance
