### ISSUE TITLE
[Plugin] GitHub Deployments / Environments

### ISSUE THREAD

**Issue by tadashi0713** [backstage/backstage#4794]
## Summary

Although it's in beta, GitHub provides environments / deployments API to track and visualize deployments of each environment.

I believe integrating this to backstage is very beneficial.

![102237891-224dc900-3ec3-11eb-845b-a88b2a36845a](https://user-images.githubusercontent.com/8651308/109901453-760aca00-7cdc-11eb-9d48-19e543b6cce4.png)

## Project website (if applicable)

https://docs.github.com/en/rest/reference/repos#deployments
https://docs.github.com/en/github/administering-a-repository/viewing-deployment-activity-for-your-repository
https://github.blog/changelog/2020-12-15-github-actions-environments-environment-protection-rules-and-environment-secrets-beta/

**Comment by benjdlambert** [comment]
Is this something you'd like to work on @tadashi0713?

**Comment by tadashi0713** [comment]
@benjdlambert I would like to work on

**Comment by benjdlambert** [comment]
Ok I will assign you! What are you thinking that the designs will look like? Thinking that there might be a `deployments` tab or something eventually, but maybe if you can build a widget that shows you Deployments and Environments for now that would be a good step :)

**Comment by tadashi0713** [comment]
> maybe if you can build a card that shows you Deployments and Environments for now that would be a good step :)

Thanks, I will do as a first step

**Comment by anderoo** [comment]
Hey @tadashi0713 - Just checking if work has started on this? I've started on the same plugin before I noticed this and don't want to duplicate effort.

**Comment by tadashi0713** [comment]
@anderoo I've not made much progress, you can start working on this

**Comment by freben** [comment]
Assigned you for now, @anderoo :)

**Comment by anderoo** [comment]
Initial draft of plugin is here: https://github.com/backstage/backstage/pull/5114

**Comment by anderoo** [comment]
Think this can be closed now?
