### ISSUE TITLE
namespace separation on k8s plugin

### ISSUE THREAD

**Issue by gazandic** [backstage/backstage#4810]
Hi folks, I would like to request a feature changes.
After this [discussion](https://github.com/backstage/backstage/pull/4743#discussion_r587404386), we would like to add new feature for k8s plugin to have namespace separation

## Feature Suggestion

We would like to have namespace separation for k8s plugin because in this 
[code](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesFetcher.ts#L206), the plugin fetch all namespace with labelSelector.
We would like to separate between k8s namespaces.

## Context

When we want to separate namespace, we should add extra label selector
like [this](https://github.com/backstage/backstage/blame/3b2312b8a8461d600f2f26b2caeb85ef18facd75/docs/features/kubernetes/troubleshooting.md#L74). We don't want this to be bad practice.

> yup, backstage selector for annotations on catalog-info,yaml, and backstage.io/kubernetes-id for query to k8s
> I print the plugin there and using labelSelector for it if params not described, the frontend in my local hit without labelSelector params.
> 
> https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesFetcher.ts#L119
> 
> Then, the logger print this
> <img alt="Screen Shot 2021-03-04 at 08 53 54" width="925" src="https://user-images.githubusercontent.com/9495683/109899158-012d9500-7cc8-11eb-8842-ca9ed83aba60.png">
> 
> But i didn't try yet when there are no annotations on catalog-info.yaml. I think its possible just using backstage.io/kubernetes-id on k8s related yaml, and not define anything on catalog-info.yaml, but it will be scan all Namespace so there are no separations between namespace, i think it will be useful for namespace separation (staging|production)
> 
> https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesFetcher.ts#L206

**Comment by adamdmharvey** [comment]
Is your thought to pre-filter by namespace?  Becuase I also wondered if the opposite might be useful, a label selector across multiple namespaces, and maybe the namespaces are then exposed into the UI as tabs where you could pick  a different tab which helps identify the forced separation of a namespace?  e.g., what if you have a single K8s cluster with a dev and a uat namespace, you have your k8s page help expose those as subtabs?

just a thought!

**Comment by gazandic** [comment]
Nice, thats great idea for namespace separation in UI. 

Before i make this issue, i think the namespace separation would be like configuration that could be on backend/frontend plugin. We could enable/disable it  with config/updating labels on component entities.

I totally agree that its nice to have separation in UI, so we could use label freely like i did to separate between namespaces using additional label.

**Comment by adamdmharvey** [comment]
Only one other point, as I saw this in another plugin, but the nice little formatter at top right could be an interesting UI hack for filter namespaces also

![image](https://user-images.githubusercontent.com/33203301/109988916-fd087400-7cd5-11eb-9c4a-480735027898.png)

**Comment by mclarke47** [comment]
For now an annotation on the entity with the namespace to use might be good

**Comment by mclarke47** [comment]
Still relevant

**Comment by djsly** [comment]
Keep alive

**Comment by zoidbergwill** [comment]
A new annotation sounds like a good solution. My initial ideas are all O(n) though for all namespaces we might wanna support for an entity, but maybe that's acceptable.
