### ISSUE TITLE
Not able to load docs

### ISSUE THREAD

**Issue by Skandh15** [backstage/backstage#4811]
## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by OrkoHunter** [comment]
Hi! Your issue needs more information for us to help out - like browser console logs, backend logs, error messages, your environment etc.

**Comment by OrkoHunter** [comment]
Going to close this now. Feel free to re-open with more helpful debug info, thanks!
