### ISSUE TITLE
Scaffolder with v1beta2 schema template fails to create correct folder structure for existing cookiecutter templates

### ISSUE THREAD

**Issue by jessebye** [backstage/backstage#4824]
## Expected Behavior

Using an existing Cookiecutter template repo with the scaffolder on v1beta2 schema should produce the correct repo structure:
```
.
├── components
├── package.json
└── pages
```

## Current Behavior

The templated repo has an extra folder in the root, under which all the expected contents (that should be in the root) are nested. Also the `hooks` folder and `cookiecutter.json` are copied over from the template:
```
.
└── my-service
    ├── components
    ├── cookiecutter.json
    ├── hooks
    ├── package.json
    └── pages
```

## Possible Solution

https://github.com/backstage/backstage/blob/f094bf78238ad2109aec9debf2aab9f1cb53cbc2/plugins/scaffolder-backend/src/scaffolder/actions/builtin/fetch/cookiecutter.ts

It looks like the logic here is incorrect for existing cookiecutter templates. I'm not exactly sure how the bug would be fixed, but the way the directory structure is generated in this action seems to cause the problem.

## Steps to Reproduce

1. Create a `template.yaml` following the `v1beta2` schema and pointing at an existing cookiecutter template repo that uses the nested `{{cookiecutter.component_id}}` structure. For example: https://github.com/spotify/cookiecutter-golang
2. Update your backstage config to use this new template.
3. Create a repo with the template.
4. Observe that the files are NOT under the root of the repo, and the hooks didn't run because Cookiecutter was pointing at the wrong directory for the template.

## Context

We are upgrading our templates to `v1beta2` to take advantage of the new custom actions, but are blocked because of this bug.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): Alpine Linux
- Browser Information: Chrome

**Comment by Rugvip** [comment]
@jessebye the layout of the alpha1 and beta2 template contents aren't directly compatible. In alpha1 the template dir is the root of the cookiecutter directory, which usually would contain the `cookiecutter.json`, hooks, and template dir. In beta2 templates instead point straight at the template dir. 

You should be able to either rename the dir and point to it, or set the template path to include `'{{cookiecutter.component_id}}'`

**Comment by jessebye** [comment]
@Rugvip will hooks still function for beta2?

**Comment by Rugvip** [comment]
@jessebye no, although it could be worked in. The intention is really that additional steps with custom actions are used instead.

**Comment by benjdlambert** [comment]
@jessebye I'd recommend renaming the folder, as we prolly want to avoid using `'{{cookiecutter.component_id}}'` in the template schema as it could be confusing if it gets templated or not with the other template variables in the `v2` template.

@ruvip how would we manage the hooks? Have a seperate `hooks` folder input to the `fetch:cookiecutter` action?

**Comment by Rugvip** [comment]
@benjdlambert tbh I don't think the pattern of executing shell scripts on hosts is great, neither in docker but especially not in the same environment as the backend. Any hook that was just there to e.g. curl some other endpoint would be simple to replace with an action that simply does the same, could even be something we want to provide as a built-in one potentially. Scripts that modified the templates is a bit trickier, but tbh it should always be possible to just have the template in the correct shape from the beginning afaik?

**Comment by benjdlambert** [comment]
I mean I fully agree that it would be best to move them into Typescript actions anyway, that way they are re-usable across templates and not bound to cookiecutter. What do your hooks do @jessebye? Could you move them into custom typescript actions instead?

**Comment by jessebye** [comment]
@benjdlambert @Rugvip We can make this work, but our templates will be a bit more convoluted as a result. We were using hooks to do things like delete a few folders based on user selections. For instance, if the user does not need a database, we delete two folders from the template with the hook. We can do this with templating but you end up with really ugly folder nested folders like this:
```
└── {{\ "database"\ if\ "Database"\ in\ cookiecutter.service_reqs\ else\ ""\ }}
    └── {{\ "migrations"\ if\ "Database"\ in\ cookiecutter.service_reqs\ else\ ""\ }}
        └── {{\ "1_create_table.up.sql"\ if\ "Database"\ in\ cookiecutter.service_reqs\ else\ ""\ }}
```
The `if` statements have to follow the folders all the way down, and also have to be included for every filename inside the folders.

While we could create a TypeScript action to do this just like the hook did, it gets a bit convoluted because each template has different set of files that might be deleted.

**Comment by jessebye** [comment]
I realized that we can simplify our structure a bit. We can have the conditional for just the filename, not the directories too - since empty directories will not be committed to git.

**Comment by osiris-dev** [comment]
Hi team. Wondering what the status is around hooks currently. I have started using backstage and my cookiecutter post generate hooks do not appear to execute as expected when running fetch:template with cookiecutterCompat mode. Have hooks or some alternative to them been worked in yet?

**Comment by benjdlambert** [comment]
@osiris-dev - we've purposefully left hooks out of the `cookiecutter` action and the `cookiecutterCompat` mode for security reasons by default. We'd recommend that you convert your hooks to [custom actions](https://backstage.io/docs/features/software-templates/writing-custom-actions) instead, or you can build your own action that can run `cookiecutter` templates with the hooks instead of course, but then there's the added security risk that those hooks will just run arbitrary bits of code that you have no control or review over which we'd advise against 👍

**Comment by edbighead** [comment]
@benjdlambert thanks for confirming. Are the hooks explicitly disabled somewhere in the code? Looking through https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend-module-cookiecutter/src/actions/fetch/cookiecutter.ts

**Comment by WiktorMadejski** [comment]
Hey @benjdlambert, @Rugvip, 

How can I modify [fetch:cookiecutter](https://github.com/backstage/backstage/blob/ad8ff14dd09ef4ee68075c0b95bc27e982f3e9db/plugins/scaffolder-backend-module-cookiecutter/src/actions/fetch/cookiecutter.ts#L101) into custom action that executes hooks? Are they  disabled in some cross-dependent code, could you point us to it?

PS. Cookiecutter CLI that [fetch:cookiecutter](https://github.com/backstage/backstage/blob/ad8ff14dd09ef4ee68075c0b95bc27e982f3e9db/plugins/scaffolder-backend-module-cookiecutter/src/actions/fetch/cookiecutter.ts#L101) uses can disable hooks execution with ["--accept-hooks"](https://cookiecutter.readthedocs.io/en/stable/cli_options.html#cmdoption-cookiecutter-accept-hooks) flag.
