### ISSUE TITLE
TechDocs breadcrumb: highest level link is broken

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4825]
## Expected Behavior

After using the TechDocs home page to navigate to a certain documentation page, I should be able to use the breadcrumbs to navigate back to the TechDocs homepage.

## Current Behavior

Clicking on the "root" Breadcrumb element of an individual docs page, takes you to a generic catalog (not documentation) homepage (and that's also due to an invalid entity link).

**TechDocs Homepage**:
![image](https://user-images.githubusercontent.com/33203301/110056909-9d3db780-7d2d-11eb-8830-105cd10cb2ee.png)

**Backstage Component docs page**:
![image](https://user-images.githubusercontent.com/33203301/110056983-bfcfd080-7d2d-11eb-8a48-90de0f97b537.png)

**Returned to the catalog homepage**:
![image](https://user-images.githubusercontent.com/33203301/110057044-d9711800-7d2d-11eb-9312-29083f1f19de.png)

## Possible Solution

* Statically hardcode the main route for the page that draws the documentation as `/docs`?
* Currently, the breadcrumb seems to display "entityname / Mkdocs Site Name" as elements. However, I would have expected the breadcrumbs to be "Docs / Mkdocs Site Name", where "Docs" (or Tech Docs or something that triggers for the user "a list of all available documentation) is what brings me back to the `/docs` route.

## Steps to Reproduce

1. Visit the TechDocs main route of /docs: http://localhost:3000/docs
2. Select a specific piece of documentation, e.g. the sample `backstage` site: http://localhost:3000/docs/default/Component/backstage
3. Along the top, see the Breadcrumbs which should say "backstage > Backstage".
4. Click the left-most home link "backstage" which should take you to this link: http://localhost:3000/catalog/Component/backstage
5. This is the catalog homepage.

The correct entity link in this case could have been http://localhost:3000/catalog/default/component/backstage.

But my expectation would have been getting right back to the main TechDocs homepage instead (back to the /docs route).

## Context

The reason you're brought back to the catalog homepage is in fact the entity link is wrong.  You're taken here:
http://localhost:3000/catalog/Component/backstage

But the correct entity page for that component should be:
http://localhost:3000/catalog/default/component/backstage

However, that's not where I expected to be taken back to.

## Your Environment

- NodeJS Version (v12): v12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 WSL2 Ubuntu 18.04
- Browser Information: Edge (Chrome engine)

**Comment by tudi2d** [comment]
Hey - I would like to fix this. My solution would be to replace the "entityName" Link with a "Docs" Link, which brings you back to ".../docs". Is that alright @adamdmharvey? Also I would like to take a look if this is a bug I introduced by adding the `Breadcrumbs` component in #3965.

**Comment by adamdmharvey** [comment]
That's what I think too, @tudi2d. However, I can't say I know where this comes in - I couldn't find a clear "docs-specific Breadcrumb" component, so it may be buried under an entity front end in somehow, but I have no idea how so won't be able (myself) to be too much help there 😁

**Comment by tudi2d** [comment]
> 
>
> I couldn't find a clear "docs-specific Breadcrumb" component, so it may be buried under an entity front end in somehow, but I have no idea how so won't be able (myself) to be too much help there 😁

😄 I helped adding a `Breadcrumb` component in #3965 to the `core` layout components, which is also used in the `Header`. As far as I remember the Docs were the only place using a "depth" of 2 in the breadcrumbs - so will check that again 👍
