### ISSUE TITLE
Unable to use @backstage/core in Custom Actions

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4848]
## Expected Behavior

Able to add a custom action to /backend/src/actions/createNewFileAction.ts and everything mentioned in the following doc to /backend/src/plugins/scaffolder.ts

https://backstage.io/docs/features/software-templates/writing-custom-actions#docsNav

when running `yarn tsc` i am getting a number of errors related to fs-extras

## Steps to Reproduce

Follow this doc - https://backstage.io/docs/features/software-templates/writing-custom-actions#docsNav 

## Your Environment

- NodeJS Version (v14)
- Win 10

**Comment by freben** [comment]
What errors? Cloud you provide the log output?

**Comment by regicsolutions** [comment]
I guess that would help huh lol my bad i ended up getting passed the error but it still looks like i am not able to use @backstage/core directly in the action. It was mentioned on Discord its something about how its being used in @backstage/backend-common ?

Here's what my scaffolder.ts in case in helps anyone - 

```
import { ScmIntegrations } from '@backstage/integration';
import { SingleHostDiscovery } from '@backstage/backend-common';
import { CatalogClient } from '@backstage/catalog-client';
import {
  CookieCutter,
  createRouter,
  Preparers,
  Publishers,
  CreateReactAppTemplater,
  Templaters,
  createBuiltinActions,
} from '@backstage/plugin-scaffolder-backend';

import { myCustomAction } from '../actions/publish/myCustomAction';
import Docker from 'dockerode';
import { Router } from 'express';
import type { PluginEnvironment } from '../types';

export default async function createPlugin({
  logger,
  config,
  database,
  reader,
}: PluginEnvironment): Promise<Router> {
  const cookiecutterTemplater = new CookieCutter();
  const craTemplater = new CreateReactAppTemplater();
  const templaters = new Templaters();

  templaters.register('cookiecutter', cookiecutterTemplater);
  templaters.register('cra', craTemplater);

  const preparers = await Preparers.fromConfig(config, { logger });
  const publishers = await Publishers.fromConfig(config, { logger });
  
  const integrations = ScmIntegrations.fromConfig(config);
  const dockerClient = new Docker();
  
  const discovery = SingleHostDiscovery.fromConfig(config);
  const catalogClient = new CatalogClient({ discoveryApi: discovery });
  
  const proxyUrl = await discovery.getBaseUrl('proxy');
  const builtInActions = muCustomAction({
    dockerClient,
    integrations,
    catalogClient,
    templaters,
    reader,
  });
  const actions = [...builtInActions, myCustomAction({ proxyUrl })];
  
  return await createRouter({
    preparers,
    templaters,
    publishers,
    logger,
    config,
    dockerClient,
    database,
    catalogClient,
    reader,
    actions,
  });
}
```

**Comment by freben** [comment]
Oh, core is a frontend-only package - it's entirely not possible to use it in backend packages. You can tell by its being built as ESM https://github.com/backstage/backstage/blob/master/packages/core/package.json#L

Compare to a backend package which is CJS https://github.com/backstage/backstage/blob/master/packages/backend-common/package.json#L10

Or to a universal package which supports both https://github.com/backstage/backstage/blob/master/packages/catalog-model/package.json#L10

**Comment by freben** [comment]
Does this mean that the issue can be closed?

**Comment by Rugvip** [comment]
@regicsolutions what exports from the `@backstage/core` package is it that you want to use?

**Comment by benjdlambert** [comment]
@regicsolutions can we close this issue after our discussions on Discord or do you want to keep this around?

**Comment by regicsolutions** [comment]
> @regicsolutions can we close this issue after our discussions on Discord or do you want to keep this around?

Yep
