### ISSUE TITLE
[TechDocs] Allow to configure AWS S3 endpoint url

### ISSUE THREAD

**Issue by rbideau** [backstage/backstage#4867]
## Feature Suggestion

Right now, only the region is configurable. The full url is the built by the aws sdk.  
The goal is to allow to configure an endpoint url when publishing to AWS S3.

## Possible Implementation

Add an optional configuration `techdocs.publisher.awsS3.endpoint`. If present, set the endpoint in the S3 constructor.

For reference:
- [S3 constructor in the aws-sdk v2 api](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property)
- [S3 constructor in the aws-sdk v3 api](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/globals.html#s3clientconfig)

## Context

This would enable to use other storage provider with a S3-compatible API, like [MinIO](https://min.io)
(For MinIO, you will need to enable virtual-host-style requests, see [the bttom of the configuration guide](https://docs.min.io/docs/minio-server-configuration-guide.html))

**Comment by rbideau** [comment]
I'm ready to work on this, you can assign me.

**Comment by benjdlambert** [comment]
Done @rbideau! Thanks 🙏
