### ISSUE TITLE
Share Catalog Data Between Multiple Backstage Instances

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#4888]
## Summary

One might want to share catalog entities between multiple Backstage instances. There are some use cases where this is interesting:

* During development to get data into a test instance
* In a setup where multiple Backstage instances are used in an organization, but you want to share catalog content between them (for example because of compliance constraints in an organization)
* If you have a broader ecosystem of services that you want to share between Backstage instances of multiple organizations.

Right now, one has to register the location of `catalog-info.yaml` files in all instances to have the same data available. If different views on the data are required (e.g. some fields should be excluded), this wouldn't work with duplicating the location and would require a separate data set.

In these cases it would be interesting to share the basic data from the catalog, like name, ownership, lifecycle, ... . However, other data, like integrations might not be shared. To avoid name collision one could facilitate namespaces. A backend plugin might provide an endpoint that emits all entities that another Backstage instance can register as a location.

## Context

At SDA SE, we reuse the content we have in our internal service catalog based on Backstage to offer them to external partners in our ecosystem. For that we have a second Backstage instance in the ecosystem where only selected services are shared. In addition, only some fields of the entities are shared. Users can add an annotation to an entity and the entity (and some related entity like systems & domains) are automatically provided to the other instance.

This isn't actually a request for implementation as we have a working solution for this internally. However if there is demand for this to be open sourced, or directly integrated into Backstage, this is something we might consider.

**Comment by freben** [comment]
Thanks for writing this up. The idea of federation of catalogs has been on our mind for a long time, but we've postponed it until things were more settled and the community had started to see the need for it so we could collect the use cases and package it better.

There are a couple different ways one could want to do this.

One very basic way would be to basically mirror the locations registry, fetching it periodically from the upstream catalog. That way, at least all user-registered (as opposed to config driven) locations are always available to your catalog too. The drawback is that now you are doubling the refresh load as well, and you have to wait for all of the data to pour in during the first refresh cycle.

Another way would be to read actual entities, probably with a filter query, and to store those. You would probably not easily get `uid`/`generation`/`etag` matching, but that's probably not a problem for most use cases. This should happen as a reader processor to get the processors to do their work. I'll assume that this is the one you've written?

**Comment by Fox32** [comment]
Yes, we choose to go with pulling the data from an existing instance instead of duplicating the locations. We have a custom backend that filters and process the entities from the catalog API and returns them in the multi document YAML format that the existing url readers can ingest.

**Comment by freben** [comment]
Oh I meant rather that you'd perhaps register a driver location `catalog-entities:http://backstage-backend-2.services.example.net/api/catalog/entities?filter=namespace=non-secret` and then a processor latches onto that, makes a regular catalog client read from that, and emits the read entities one by one after stripping off `relations` and `metadata.{etag,generation,uid}`.

**Comment by Fox32** [comment]
Doing the logic in the destination instance would be easier to implement, but we chose to do it in the source as we need access control on entity level. As long as the catalog doesn't have this, we need a custom backend. Even though I think that this case might be a bit special here. 
We have an annotation that marks entities as exported and also exports related entities. Right now our backend also discovers the related entities as it's difficult to automatically add the annotation to all entities. If the ingestion loop was a bit more flexible and would allow to modify other entities, our filter condition could be a lot easier.

**Comment by freben** [comment]
that might be a thing in our rewrite of the processing logic that's ongoing ... :) @benjdlambert @Rugvip @jhaals just to note, one possible use for one entity leading to changes in another entity ^
