### ISSUE TITLE
Authentication cookie as a part of the login process

### ISSUE THREAD

**Issue by GoWind** [backstage/backstage#4901]
It would be a good idea to generate a standard authentication cookie, as a part of the login process, along  with the 
`AuthResponse`.
 
## Feature Suggestion

The Authentication model currently returns a `AuthResponse` that contains a providerInfo, profile and BackstageIdentity objects, along with an optional refresh token cookie.
The **suggestion** is to add a standardized, optional Authentication cookie to this response.

## Possible Implementation
The `Auth` handler returns an `Authorization` cookie, with the value that is either the token, or a derivative of the token set in the `OAuthResponse`. 
The Auth handler provides a mechanism to authenticate this cookie.

A possible way to control this is via the `OAuthAdapter`. 
An option can be passed to the `OAuthProvider` to enable disable this feature. 
Based on the flag, the OAuthAdapter can set this cookie, similar to how the refresh token cookie is [set](https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/lib/oauth/OAuthAdapter.ts#L126)

### Cookie vs Header - Prioritization
`Authorization` Header always has priority.
The cookie is a workaround, to solve issue where it is not possible to set a Header.
The cookie workaround has to be an opt-in, mostly through a middleware. 
Implementations should still try to use the Header as much as possible, and only resort to the cookie mechanism
if it is not possible (static resources, iframes, etc).

## Context

Why ? 
With SPAs, a lot of resource fetching and rendering is done asynchronously through `fetch` and `AJAX` APIs. But nevertheless,
a lot of resource requests are still initiated by the browser, for which it is not possible to set the right Authorization Headers. 

As the backend becomes the resource server, for plugins, more and more requests flow directly to the backend, which when hosted on a different domain/sub-domain than the frontend, needs authorization. 

An example of this is [techdocs](https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/service/router.ts#L85) , which, currently has a custom logic to solve this problem. As more people adopt backstage, this problem starts getting more relevant and we need to solve this problem.

**Comment by GoWind** [comment]
Please let me know what you think of this suggestion. Would be willing to contribute this if the core team feels this is necessary (and not being solved in a different issue)

**Comment by freben** [comment]
Gonna ping @Rugvip for this one I think. We've mentioned this briefly before and were thinking that there are CSRF protection concerns.

**Comment by GoWind** [comment]
There are a few ways to secure the cookie, but how exactly do you think it could have issues ? 
I set `httpOnly` for example, to ensure that `getCookie` cannot access this.
