### ISSUE TITLE
[TechDocs] Support Redirects in TechDocs

### ISSUE THREAD

**Issue by bret-hubbard** [backstage/backstage#4931]
## Feature Suggestion
Add support for redirects so when a file is renamed a bookmarked link still works.

## Possible Implementation
Add logic to the Reader (perhaps in the form of a new transformer) to detect and react to `<meta http-equiv="refresh" content="0; [location]">` meta tags.  This would provide de-fact support for those using the [mkdocs-redirects](https://github.com/datarobot/mkdocs-redirects) extension, but at least follows a standard that is generic beyond the extension.

## Context
If a doc is bookmarked and the name of that doc is changed it can cause issues like returning a 404 page or possibly worse, retrieving an old version of the doc if it wasn't cleaned up.

Feature non-goals:
- We're not aiming to solve entity renames which would necessitate redirects (this should be handled primarily by the Software Catalog)
- We're not aiming to solve vanity redirects or shortened doc URLs/paths (this can be handled at the App-level, for now)

**Comment by bret-hubbard** [comment]
I have looked into this a little and have had a few thoughts on implementation. After looking through the code I think we could support the same `mkdocs-redirects` plugin syntax
```yaml
plugins:
    - redirects:
        redirect_maps:
            'old.md': 'new.md'
            'old/file.md': 'new/file.md'
            'some_file.md': 'http://external.url.com/foobar'
```
though I don't think we can use a mkdocs plugin because of how everything is (rightly) sanitized. I have a few thoughts on how we could implement this.

Since we need to support doc generation and publication locally, in docker, and externally, we probably need to handle this in `techdocs-common` and I think storing the redirect maps in `techdocs_metadata.json` makes sense.

That idea does present some other issues like we will either have to hardcode `mkdocs.yml` again (or fix [this TODO](https://github.com/backstage/backstage/blob/master/packages/techdocs-common/src/stages/generate/techdocs.ts#L70)) or alternatively I guess we could add this logic to `patchMkdocsYmlPreBuild`.

For the redirecting part, we could handle that in either `techdocs` or `techdocs-backend` if the redirect happens in the backend it will be faster but supporting redirects to external links wouldn't work. Since the front end is already getting the `techdocsMetadata` and can redirect externally (maybe wrapped in "you're leaving backstage" link) I think it makes sense for the redirects to happen there.

I realize I've only spent a handful of hours looking through the code and am not an expert so I'm open to alternatives and feedback. Would love to hear from you about this!

**Comment by OrkoHunter** [comment]
The `mkdocs-redirects` plugin is [quite a thin MkDocs plugin](https://github.com/datarobot/mkdocs-redirects/blob/9195930d18fbd8df2a9585134460d0e89af0997a/mkdocs_redirects/plugin.py#L40) to generate placeholder HTMLs, which uses Javascript to do the navigation. The `script` tag gets stripped when imported into TechDocs.

If another MkDocs plugin would use the "HTML way" of creating redirects, then TechDocs might be able to handle those.

```html
<meta http-equiv="refresh" content="0; url=/path/to/new/page" />
```

Storing redirects data in the `techdocs_metadata.json` is also not a bad idea but invites more work in the `techdocs-common` package.

**Comment by bret-hubbard** [comment]
Yeah good point on the "HTML way"! To go this route, we will have to configure `sanitize-html` to allow `meta` tags which is easy enough but I'm not sure what risk introducing that change would create.

**Comment by iamEAP** [comment]
Upon closer inspection, the MkDocs plugin _does_ place the appropriate meta tag just below the script tag, so I think that's a plausible way forward.  A quick experiment seems to indicate meta tags have no effect within the ShadowDom, so the handling logic would have to be added to `Reader`.

This is a great suggestion, though!  Would've come in handy so many times.

**Comment by bret-hubbard** [comment]
I didn't notice that the plugin includes the meta tag until you pointed that out. Looking at `Reader` we could possibly use the canonical link and do something like this

```typescript
  const canonicalLink = Array.from(transformedElement.getElementsByTagName('link')).find(e => e.rel === "canonical")
  if (canonicalLink && canonicalLink.href !== window.location.href) {
    window.location.replace(canonicalLink.href);
  }
```

Not a huge fan of the idea. I am also not sure if we want to include this as a core feature of techdocs or if we want to only include it in a plugin like the mkdocs plugin works. If we do something in `Reader` or the original option I mentioned including it in the `techdocs_metadata.json` file, it becomes more of a core feature. I do think this is a critical feature for a tech docs solution to have personally but I don't want to necessarily force that on everyone.

**Comment by iamEAP** [comment]
Mmm...  Now that I think of it, I wonder if the redirect problem is more of an App-level concern, rather than a TechDocs Plugin-level concern.  Certainly documentation pages change locations from time to time within a particular docs site, but I think a larger (or at least equally large) problem is when _software catalog entities_ change names and the whole docs site (as well as other catalog-related views) would benefit from redirects.

I agree supporting redirects in some way is key, but maybe implementation should be determined based on what makes the most sense from a redirect authoring/management perspective?

**Comment by iamEAP** [comment]
Alright!  So based on some discussion in the above PR, I'm thinking it's reasonable to support `<meta>`-style redirects in the Reader, which implicitly supports the aforementioned `mkdocs-redirects` extension (without being explicitly tied to it).  It could be implemented as its own transformer.

I'll open up a separate issue for wider redirect scenarios, which may more appropriately be handled by the catalog.
