### ISSUE TITLE
[TechDocs] Owned documents page is blank (and shows no friendly messaging)

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4932]
## Expected Behavior

When I have no documents I own, the new TechDocs homepage "Owned Documents" tab should tell me I have none.

## Current Behavior

TechDocs has a cool new homepage which has introduced tab structures, letting me view my own owned documents.  In the code, there's an empty state which should show if my documents is zero. However, it looks like I'm first hitting a 404 to the backend entity API because my logged in identity doesn't exist as a "user" entry in the actual catalog (I have no github org processor loaded at the moment), and so it's triggering an immediate exit at the top of the component so it never gets anywhere near to rendering the empty state.  The same thing happens if I login to Backstage as a "guest".

![image](https://user-images.githubusercontent.com/33203301/110851012-7e37ac00-827e-11eb-8335-abeb3966f391.png)
![image](https://user-images.githubusercontent.com/33203301/110850183-7aeff080-827d-11eb-966a-242609a02b46.png)

## Possible Solution

Rework the early exit here:
https://github.com/backstage/backstage/blob/c8b54c370223d8eb8f9e3ad05681edb8ec368b86/plugins/techdocs/src/home/components/OwnedContent.tsx#L46

So the empty state can be properly displayed later:
https://github.com/backstage/backstage/blob/c8b54c370223d8eb8f9e3ad05681edb8ec368b86/plugins/techdocs/src/home/components/OwnedContent.tsx#L109-L121

## Steps to Reproduce

1. Have no docs you own
2. Visit techdocs homepage
3. Open owner page

## Context

As context,
* I'm logged into my instance as my GItHub profile.
* I have not defined a location to load users out of my GitHub instance at the moment (the github org processor), and so while I myself exist and am authenticated, _technically_ my profile doesn't exist as a real "user" in the backstage system. If I go to search, there are no users in the filter. (therefore, my user doesn't really exist)
* So while my doco component says I'm the owner, and it relates to my logged in identify, backstage doesn't believe I'm a real "user."
* So I'd guess this is why then the `!user` check is shooting the early exit.

I don't know if this is just considered an edge case or not, but when the user can't be found in the catalog, the message MAYBE could be different or something?

Note the same thing happens if I login as "Guest" to backstage.

## Your Environment

- NodeJS Version (v12): v12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL2 Ubuntu 18.04
- Browser Information: MSFT Edge (Chrome engine)

**Comment by pedro-cze** [comment]
Hi, I've never contributed to backstage, but I'd like to and this issue seems as a good starting point to me. Can I have a look at it? 
Thanks

**Comment by OrkoHunter** [comment]
@pedro-cze  Sure! Assigned it to you :)

**Comment by soapraj** [comment]
Looks like this issue might already be resolved as the Techdocs homepage components have been refactored since. Can you confirm @adamdmharvey ?

![Screenshot 2022-01-20 at 19 51 42](https://user-images.githubusercontent.com/3055673/150403396-bf52b24a-5409-49a9-820d-777c2056d047.png)

I tried setting entities to empty and user to undefined and in both cases the empty state in the screenshot showed up.

**Comment by soapraj** [comment]
Closing this issue for now. Please re-open if needed.

**Comment by adamdmharvey** [comment]
Yep, this looks good now!  👍🏻 

<img width="918" alt="image" src="https://user-images.githubusercontent.com/33203301/153313448-a9d2f078-e0fc-4644-ad83-f7e6dfa2a3c5.png">
