### ISSUE TITLE
JsonObject causes TypeScript type instantiation is excessively deep and possibly infinite error

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#4949]
While working on #2791, I started running into the following TypeScript error when using the `Entity` type within a reducer function:

```
Type instantiation is excessively deep and possibly infinite.ts(2589)
```

Tracking this down it seems to be related to `JsonObject` circular references (`JsonObject -> JasonValue -> JsonObject`).

## Expected Behavior

TypeScript is happy

## Current Behavior

TypeScript is not happy

## Possible Solution

In https://github.com/backstage/backstage/blob/master/packages/config/src/types.ts#L17:

```diff
- export type JsonObject = { [key in string]?: JsonValue };
+ export type JsonObject = { [key in string]?: any };
```

## Steps to Reproduce

If you pull down #2791 and remove the `as any` casting workarounds in the [reducer](https://github.com/andrewthauer/backstage/blob/feat/custom-catalog-tabs/plugins/catalog/src/state/reducer.ts) the error should occur. Changing https://github.com/backstage/backstage/blob/master/packages/config/src/types.ts#L17 to use `any` will make the error go away.

## Context

Trying to use `redux-toolkit` which uses `immer`'s `WriteableDraft<Entity>` type within a reducer function. I suspect this error could occur in other scenarios due to the fact it's just a TS deepth limit error.

**Comment by freben** [comment]
Hm this could be an interaction with immer specifically. Can absolutely reproduce, not able to fix it yet though.

**Comment by andrewthauer** [comment]
Well using `any` instead of `JsonObject` does it fix it for me. Is there any semantic value of having `JsonObject` over using `any`? It seems like it's essentially trying to mimic `any`.

**Comment by freben** [comment]
It's much, much narrower than `any`. For example it can't contain regexes or functions.

It's explicitly meant to be used as "the set of safely json ecodeable things".

**Comment by andrewthauer** [comment]
I see. That makes sense. When I googled this error it comes up a lot for various things. From what I gathered there was a limit introduced in TS around version 3.7/3.8. Presumably to avoid performance issues or walking type chains. Although this is happening for immer specifically, I can see this showing up elsewhere at some point.

**Comment by freben** [comment]
Yeah for sure. Something somewhere makes things go close to that limit I bet, and this was just where the last straw was put on

**Comment by freben** [comment]
Okay, I THINK that it's solved by this one. https://github.com/backstage/backstage/pull/4959

It did remove the error when applied on top of your branch it seems. Let me know how it goes.
