### ISSUE TITLE
catalog-import: Confusing UI error if integration isn't configured properly

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4957]
## Expected Behavior

The error presented to a user is clear about the problem when providing a URL to use when manually registering a URL.

## Current Behavior

If an integrator has misconfigured GitHub as an integration, the UI for the catalog import says "Invalid URL".

![image](https://user-images.githubusercontent.com/33203301/111196959-45584980-8594-11eb-8d16-afc347a2730f.png)

This error is thrown:

https://github.com/backstage/backstage/blob/1cc27f7e10c80df9a9520b148df95011016a3655/plugins/catalog-import/src/api/CatalogImportClient.ts#L101

My colleague and I @tom-halpin played around for a little bit expecting it was permissions issue, or maybe a wrong URL, until we realized his GitHub integration wasn't properly configured.

## Possible Solution

Change this error output to better reflect the issue. Possibly see if multiple error types could be thrown, and if there's a specific error about the integration being misconfigured, elevate that info to the UI instead.

## Steps to Reproduce

1. Scaffold a brand new app with zero configuration
2. Launch it: `yarn dev`
3. Register a component manually
4. Enter any URL that is not https://github.com
5. See "Invalid url"

## Context

Given a config where only GitHub.com should be valid, the invalid URL message _sort of_ makes sense - but it lacks enough context to be particularly valuable.  Maybe even the error could say `Invalid URL for this "integration.github.host"` or something?  Not sure, but it was not clear to a new user (even w/ my support).

## Your Environment

- NodeJS Version (v12): v14 (I think)
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 WSL 2 Ubuntu 20.04
- Browser Information: Edge

**Comment by freben** [comment]
made a pr, see if that clarifies things for the end user
