### ISSUE TITLE
'Blessed' icons for core plugins

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#4970]
## Feature Suggestion

Select icons to represent major parts of Backstage, for use in buttons and links into these components. EG:

* catalog
* scaffolder & templates
* techdocs
* search?

## Possible Implementation

Probably just need to add them in here: https://github.com/backstage/backstage/blob/master/packages/core-api/src/icons/icons.tsx#L33-L44

## Context

I bumped into this when changing the layout of some component to make use of icons and needing one to represent a link into the catalog. It occurred to me that it might be worth having a consistent choice for things like this. [Discord discussion](https://discordapp.com/channels/687207715902193673/696709358544879716/821352656597286944)

**Comment by freben** [comment]
As I mention in the discussion - while it's a bit odd to have plugin concerns in the app builder, the mentioned plugins are so core that they warrant the exception. They are basically like default implementations of core concerns.

**Comment by chinmaym07** [comment]
Hey Can I do this ? Also Can you please share the link to icons you want to add here ?

**Comment by Rugvip** [comment]
@chinmaym07 Sure, thanks!

We don't actually have a set of icons that we want to use yet, would you like to suggest some from https://material-ui.com/components/material-icons/ ?

Perhaps something like MenuBook for TechDocs, AccountTree for catalog, and Build for the scaffolder? But best to get a couple of candidates to select from for each.

**Comment by TejasQ** [comment]
This issue is not immediately clear to me. 🤔 

Seems we already have icons for core plugins?

https://github.com/backstage/backstage/blob/99dddfb61001ee823e717047fc3e9e9954a86b04/packages/core-api/src/icons/icons.tsx#L34-L47

Is the goal of this issue to confirm the choice of icons?

**Comment by tragiclifestories** [comment]
I think for a start everything listed under 'core features' in the docs should have one. Just because you get a lot of linking between them. It's not an urgent thing, I just found myself in need of an icon for catalog and found that there wasn't one; consistent look and feel is a good thing to have IMHO.

**Comment by hrithiksawhney** [comment]
https://github.com/backstage/backstage/pull/7850
