### ISSUE TITLE
Support namespacing groups ingested via the GithubOrgReaderProcessor

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#4982]
## Feature Suggestion

The current functionality for importing GitHub org data allows for targeting a specific GitHub org and ingesting all users/team as `Users`/`Groups` under the `default` namespace.

Under our use-case, we have a GHE instance that supports having multiple GitHub orgs (usually created per dept. or domain). If we import multiple orgs that contain the same team names then they will both merge under the same `Group` in the `default` namespace (I assume, haven't tested). It would be helpful if we could namespace the imported `Group` that indicates the GitHub org they reference

For example, I have the following GitHub orgs and teams: 
FooOrg: team-abc, team-efg
BarOrg: team-abc, team-xyz

After importing from both orgs, I would expect the following entities:
`Group:FooOrg/team-abc`, `Group:FooOrg/team-efg`, `Group:BarOrg/team-abc`, `Group:BarOrg/team-xyz`

This would allow components to specify their `owner` fields to correctly reflect team ownership.

Another thing I would like to note is that users in our GHE may have multi-org memberships so in our use-case it wouldn't make sense to namespace `Users` since there will only be one unique set of usernames.  

## Context
 There might be related to discussions in https://github.com/backstage/backstage/issues/4089 and I'm not sure how exactly this would fit in with the proposal described there.

**Comment by andrewthauer** [comment]
#4977 is relevant to this as well.

**Comment by kuangp** [comment]
If someone can provide me with some guidance, I'm willing to take a stab at implementing this since its a key blocker for us.

I thinking the implementation would be similar to how the LDAP processor works by doing the following:

1) Extend the `githubOrg` config to expose a `groups.set` option similar to the LDAP config (we can probably also support a `users.set` option while we're at it):
https://github.com/backstage/backstage/blob/0c26a45ea8c4c4ce85e4047ec43b4c5c3eb79b35/plugins/catalog-backend/src/ingestion/processors/ldap/config.ts#L97

2) Refactor the following function to read in the new config options: https://github.com/backstage/backstage/blob/0c26a45ea8c4c4ce85e4047ec43b4c5c3eb79b35/plugins/catalog-backend/src/ingestion/processors/github/config.ts#L46
by extracting out and reusing logic from the LDAP config reader:
https://github.com/backstage/backstage/blob/0c26a45ea8c4c4ce85e4047ec43b4c5c3eb79b35/plugins/catalog-backend/src/ingestion/processors/ldap/config.ts#L191-L201

3) Apply the same processing from LDAP: 
https://github.com/backstage/backstage/blob/0c26a45ea8c4c4ce85e4047ec43b4c5c3eb79b35/plugins/catalog-backend/src/ingestion/processors/ldap/read.ts#L74-L78
in this function for GitHub:
https://github.com/backstage/backstage/blob/0c26a45ea8c4c4ce85e4047ec43b4c5c3eb79b35/plugins/catalog-backend/src/ingestion/processors/github/github.ts#L127  

4) Check if `groups.set` is defined and contains `metadata.namespace` and prefix the group names when setting `user.spec.memberOf` in the following (to support the use-case where users and groups are set with different namespaces): 
https://github.com/backstage/backstage/blob/0c26a45ea8c4c4ce85e4047ec43b4c5c3eb79b35/plugins/catalog-backend/src/ingestion/processors/GithubOrgReaderProcessor.ts#L93-L103

I also want to confirm that the following function would still work correctly without adding namespace prefixes because according to the [specification](https://backstage.io/docs/features/software-catalog/descriptor-format#specchildren-required), these relations will default to using the same namespace as the current entity (ie. all groups in the current provider ingestion will have the same namespace):
https://github.com/backstage/backstage/blob/0c26a45ea8c4c4ce85e4047ec43b4c5c3eb79b35/plugins/catalog-backend/src/ingestion/processors/util/org.ts#L19-L35

Let me know if my proposed implementation makes sense or if there's anything I missed. 

(side note: if my understanding of how namespacing and entity relation identifying is correct, I'm not sure if the [LDAP processor](https://github.com/backstage/backstage/blob/0c26a45ea8c4c4ce85e4047ec43b4c5c3eb79b35/plugins/catalog-backend/src/ingestion/processors/ldap/read.ts#L410) correctly handles the scenario where users and groups are under different namespaces)

**Comment by kuangp** [comment]
I also want to note here that it looks like if you namespace teams to handle the multi-org use-case, the `CodeOwnersProcessor` will not work correctly since it looks like it strips out the org prefix when setting `owner`:
https://github.com/backstage/backstage/blob/dcb5d5e373f8b300389a248b18d2beb831660d21/plugins/catalog-backend/src/ingestion/processors/codeowners/resolve.ts#L37-L44

You would probably need to write a custom code owners processor and replace the default one in order to handle this correctly. (also note that according to https://github.com/backstage/backstage/issues/4977#issuecomment-800652564 there's currently no way to just replace one processor)

**Comment by kuangp** [comment]
Another thing I just realized (and I'm not sure what the best way to handle it is), the scenario where users have multi-org memberships which extends to having cross org team memberships. 

The following code only updates memberships for users found in the current org but that user might already exist from a previously processed org so it needs to somehow merge its membership list instead of overwriting it:
https://github.com/backstage/backstage/blob/0c26a45ea8c4c4ce85e4047ec43b4c5c3eb79b35/plugins/catalog-backend/src/ingestion/processors/GithubOrgReaderProcessor.ts#L93-L103

This seems to require the processor to somehow receive the current "in-flight" user entities in order to update existing users or somehow merging any duplicate entities at the end of the processor chain. Either way this looks like it will really complicate the current ingestion workflow and potentially cause breaking side effects.

An alternative solution here may be to create a new dedicated GHE processor that fetches all orgs/teams/users within your enterprise instance and emits group entities for all teams namespaced according to their origin org and a single set of unique user entities with group memberships set that correctly handles cross org team memberships. I'm happy to implement and contribute this new processor if it makes sense as a viable offering

cc: @freben for your thoughts here

**Comment by andrewthauer** [comment]
> You would probably need to write a custom code owners processor and replace the default one in order to handle this correctly. (also note that according to [#4977 (comment)](https://github.com/backstage/backstage/issues/4977#issuecomment-800652564) there's currently no way to just replace one processor)

The `CodeOwnersProcessor` should be updated to handle this naively. For instance:

- Compare the `org` from the location target and the codeowner team and if they don't match use the fully qualified `some-other-org:some-team` form of the entity relation. Likely would need to be configurable as this may not be desired behaviour by default.
- Provide a configurable org to namespace mapping then normalize function can use

I've also been debating a proposal to Introduce a new `ownerr-managed-by-codeowners` (name may change) annotation that could both be used to indicate the owner was derived from the codeowners. In this can it could also indicate a strategy, etc. used to resolve the owner. However, it may make sense to separate these 2 concerns.

**Comment by freben** [comment]
> Apply the same processing from LDAP

let me just note quickly that this code actually is not working right - the input schema says it should be an object `[key: string]: JsonValue }` but the code acts as if it's `{ key: string, value: JsonValue }[]` (hope I got that right)

Just so nobody falls into a copy-paste trap :)

see discussion here https://github.com/backstage/backstage/pull/4871

**Comment by kuangp** [comment]
Update on my end: I created a custom processor for my use-case.

It extends the functionality current `GithubOrgReaderProcessor` with the following changes:
- Support GitHub app auth via `GithubCredentialsProvider`
- Grab all orgs to be ingested by getting all org installations of the GitHub app (only supports the first github app defined in the config)
- Loop through all orgs, creating groups from teams namespaced according to its org
- Merge all users from each org and updates `memberOf` relations to account for cross org team memberships

I'm happy to contribute this back to the project/update the current `GithubOrgReaderProcessor` if people are interested. It could potentially also take in a list of orgs via the config and default to the above if not defined eg. `GithubMultiOrgReaderProcessor` as a separate processor

**Comment by freben** [comment]
That's cool! Glad that you found the processors useful to extend.

The first is definitely wanted - it's an oversight that it doesn't support that yet I think.

The second one - yeah that's a sensible thing to do isn't it - the token issued by the app won't let you access other repos with it right? If so, then it's equally useful to contribute I think.

The last two are trickier. The org-to-namespace mapping and the user-merge logic may be more appropriate to handle in code, eg by initializing the processor using its constructor and  giving it callbacks. If you have ideas there, let me know!

**Comment by kuangp** [comment]
Posted the implementation of our custom processor here for community feedback: https://github.com/backstage/backstage/pull/5173

**Comment by benjdlambert** [comment]
PR is in progress, @kuangp just hasn't had time to fix up the work yet. Removing the stale label :)
