### ISSUE TITLE
Catalog struggles with large number (12000+) of entities

### ISSUE THREAD

**Issue by m5m1th** [backstage/backstage#4992]
Discord thread: https://discord.com/channels/687207715902193673/687235481154617364/817317617030660117

## Expected Behavior

Catalog is fast. :)

## Current Behavior

After importing 12k entities into the catalog using an internal Spinnaker CatalogProcessor, the UI is trying to load up the entire entity list on app start from http://localhost:7000/api/catalog/entities?filter=kind=Component which returns a 10MB payload. This is causing noticeable performance issues.
 
## Possible Solution

Catalog UI/API could use paging and not fetch the full list.

## Context

I'm only populating the required entity properties, but the payload is still excessively large.

**Comment by dtuite** [comment]
Potentially fixed by https://github.com/backstage/backstage/pull/4993 ?

**Comment by freben** [comment]
Not quite. It enables the backend part of the equation, but the frontend has to opt in to it.

**Comment by freben** [comment]
One more thing that the frontend could do, is to make use of the `?fields=x,y` facility of the API, to only fetch the parts of the payload that the frontend needs. But this is basically begging for graphql to fall into place in the future instead - with proper pagination it should be come less interesting to fiddle with payload field slicing.

**Comment by Fox32** [comment]
Related to #4961
