### ISSUE TITLE
Add last updated timestamp to Backstage docs

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#5005]
## Feature Suggestion
Following along with TechDoc principles, it would be nice if the [Backstage documentation](https://backstage.io/docs) included a `Last updated` timestamp.

It would probably be even more helpful if each page had a timestamp so people can easily see if there might be new info since the last time they visited a particular page (eg. see [Heroku docs](https://devcenter.heroku.com/articles/heroku-cli))

**Comment by OrkoHunter** [comment]
Looks like this is simple enough to enable by setting

```json
enableUpdateTime: true
```

in [siteConfig.js](https://github.com/backstage/backstage/blob/e3718ad40670e2f73d2d4ba745758032527b6990/microsite/siteConfig.js#L108).

**Comment by chinmaym07** [comment]
Can I do this ? @OrkoHunter sir
