### ISSUE TITLE
Line chart component with axes, legend, multiple series

### ISSUE THREAD

**Issue by baarden-wayfair** [backstage/backstage#5012]
## 🗒 General

We are looking for a line chart component to use in Backstage. There are a few specific features we think are needed for an effective chart: axis labels, a legend, tooltips displays for data points, and the ability to show multiple series in the same chart. We initially assumed we would be able to use the TrendLine component to draw graphs, but then realized that it's built on `react-sparklines`, which is a nice-looking library but is intended for different purposes.

For instance, here is a typical chart component with these features (from the Nivo library):

<img width="643" alt="Screen Shot 2021-03-17 at 3 28 06 PM" src="https://user-images.githubusercontent.com/80785226/111631815-3b1f9080-87ca-11eb-8f98-51bc0c2f6e6e.png">

## 💻 Usage

Our goal is to present line charts of Software Development and Operations key metrics for apps in Backstage (deploy frequency, change lead time, etc.). It’s important for our users to understand not only if values are trending up or down, but also if they're high or low, and how they compare to other data.

The specific charting features we're looking for are:

- Customizable axis ticks, labels, and title
- Customizable legend size and location
- Automatic tooltips that appear when hovering over a data point
- Support for multiple data series and labels

Also, it would be great if the line chart component defaulted to the Backstage theme. 

## 📐 Specs

If it's preferable to have a single component that handles rendering the entire graph, similar to TrendLine, there are some libraries that combine configuration of legends, data series, and axes into a single component, and might be good candidates for a component like this. Here are a few we're familiar with: 

- `nivo`: Includes Typescript support. Footprint of core and line chart packages is ~140kb (plus dependencies on some `d3` math packages).
- `react-chartjs-2`: Includes Typescript support (`chart.js` has @typed support). Combined footprint with `chart.js` is ~130kb (plus dependency on `moment`).
- `echarts-for-react`: Written in Typescript (`echarts` includes Typescript support). Combined footprint with `echarts` might be ~300kb (plus dependency on `zrender`).

## 🔮 Future

Eventually we might want similar functionality for bar charts, pie charts, and other data display components, so having a library to draw from that already implements those components could be helpful.

**Comment by timbonicus** [comment]
We evaluated a number of libraries including nivo for the [cost-insights](https://github.com/backstage/backstage/tree/master/plugins/cost-insights) plugin and settled on [Recharts](http://recharts.org/). It's been pleasant to work with and supports the features you're looking for. Check out the [cost-insights demo](https://demo.backstage.io/cost-insights) for some examples. We've been able to incorporate MUI for custom tooltips and such, so it fits into the Backstage theme nicely.

**Comment by baarden-wayfair** [comment]
We're happy to use Recharts — a composable library like that should be very convenient. Thanks for the pointer!
