### ISSUE TITLE
Missing analyzer backend if using @backstage/create-app

### ISSUE THREAD

**Issue by azerbe** [backstage/backstage#5033]
When bootstrapping a backstage application with `npx @backstage/create-app` the catalog option to `Register an existing component` offers the ability to import repositories without `catalog-info.yaml`.
After configuring GitHub auth and trying to import a repository like `https://github.com/organization/project`, the backend reports a 404 error.

`Failed to generate entity definitions. Received http response 404: Not Found`
![image](https://user-images.githubusercontent.com/4478773/111868198-d8202c00-8978-11eb-8ad2-960706aca298.png)

When building from source (`backstage/backstage`) the functionality is working fine.

## Expected Behavior

The wizard should provide me with information about a PullRequest that is going to be opened with base configuration of the component.

## Current Behavior

The Website/Console/Backend report a 404 for the `http://localhost:7000/api/catalog/analyze-location` path.

## Steps to Reproduce

1. Bootstrap a new application with `npx @backstage/create-app`
2. Configure auth for Github (https://backstage.io/docs/tutorials/quickstart-app-auth)
3. Try to `Register an existing component` with a repository without component configuration

## Context

I'm trying to setup a new backstage application for my company and to import existing projects to the catalog.

## Your Environment

I've tested different kind of combinations of browsers, databases and configurations.

- NodeJS Version (v14):
- Operating System and Version (MacOS BigSur):
- Browser Information: Firefox/Chrome/Safari
- SQLite and Postgresql

**Comment by freben** [comment]
The presence is gated by the presence of a certain input parameter 

https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/router.ts#L164

And indeed that isn't passed in here 

https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/packages/backend/src/plugins/catalog.ts#L11

It should rather look like this 

https://github.com/backstage/backstage/blob/master/packages/backend/src/plugins/catalog.ts#L34

**Comment by LEBATRUNG** [comment]
Tkanhs
