### ISSUE TITLE
Jenkins Plugin - support nested folder jobs

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#5044]
## Feature Suggestion

Currently the Jenkins plugin only supports jobs that exist in folders one level deep. Is it possible to support jobs that live in nested folders? eg. `root-folder/nested-folder/my-jenkins-job`

**Comment by freben** [comment]
Hi! I believe this should no longer be true in the latest release - or at least it was intended to be updated.

https://github.com/backstage/backstage/pull/4930

Please check if an upgrade fixes it (for example with `yarn backstage-cli versions:bump`) and close if it does. If the problem still persists, provide some logs or screenshots or similar, showing how the error manifests itself.

**Comment by kuangp** [comment]
ah sorry, the project I tested with was not GitHub backed
