### ISSUE TITLE
Kubernetes: Entity name is used instead of value of `backstage.io/kubernetes-id` annotation

### ISSUE THREAD

**Issue by mclarke47** [backstage/backstage#5051]
## Expected Behavior

The value of the entity annotation `backstage.io/kubernetes-id` should be used to lookup Kubernetes resources.

## Current Behavior

The value of the entity's name is used to to lookup the Kubernetes resources.

## Possible Solution

https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesFanOutHandler.ts#L61 should be removed and replaced by looking up the annotation value in the entity like https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesFanOutHandler.ts#L88 for `backstage.io/kubernetes-label-selector`

**Comment by benjdlambert** [comment]
Believe it was fixed in #5053?
