### ISSUE TITLE
Timezone mixup for signing key expiry?

### ISSUE THREAD

**Issue by erikxiv** [backstage/backstage#5058]
## Expected Behavior

If a signing key (auth-backend) used to issue tokens is set to expire in 60 seconds, it should be available for at least 60 seconds

## Current Behavior

A signing key set to expire in 60 seconds when using Postgres as a database in a CET timezone expires immediately.

I believe this is caused by the postgres library using the local timezone to interpret the signing key creation date, but the creation date is set using UTC. As per the [docs](https://node-postgres.com/features/types):

> node-postgres converts DATE and TIMESTAMP columns into the local time of the node process set at process.env.TZ

## Possible Solution

* Start backstage with env var TZ=utc
* Change database to use the timezone aware `TIMESTAMPTZ` datatype instead

## Steps to Reproduce

1. Setup backstage with postgres database
2. Change keyDuration at https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/service/router.ts#L58 to 60 seconds
3. Browse to the backstage instance and login (notice the new signing key be created as per logs)
4. Browse to `/api/auth/.well-known/jwks.json` (notice the empty response, and the log stating that the key has expired)

## Context

So far, I've only noticed this when debugging auth. It took me a few hours to find the cause though. Since the default expiration is an hour and auth-backend retains the key for 3 hours, this issue would only be noticeable in countries farther away from GMT and on backstage instances verifying the issued token.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS X Catalina
- Browser Information: Chrome

**Comment by benjdlambert** [comment]
@erikxiv is this something you want to have a stab at fixing? 🙏

**Comment by erikxiv** [comment]
https://github.com/backstage/backstage/pull/5133
