### ISSUE TITLE
TechDocs reader displaying the last edited timestamp for the current page shown

### ISSUE THREAD

**Issue by adrianke77** [backstage/backstage#5064]
## Feature Suggestion

Hi team, our users for TechDocs are requesting that the TechDocs reader display the last edited time for the current page shown, similar to that on a Confluence wiki or other wikies. 

## Possible Implementation

The timestamp could be taken from Git, similar to the last modified date shown on a Github/ Gitlab repo UI for a particular file. This seems quite difficult to achieve however, given the many different ways files can be retrieved for the reader.

## Context

Our users would like to be able to see when a page was last updated from the TechDocs reading view much like a wiki page shows its last edited date. The use cases are much the same, such as checking if the information on a page might be outdated and so on.

**Comment by iamEAP** [comment]
Yeah, this is a tough problem, given how things are implemented right now.  URL Reader adoption has done wonders for performance and maintenance, but I think we basically lose out on any benefits of knowing that it's backed by git under the hood.

The two overall approaches that came to mind were: 

1. **mkdocs plugin + (optional) reader tweaks**: maybe we can add [mkdocs-git-revision-date-plugin](https://github.com/zhaoterryy/mkdocs-git-revision-date-plugin) to the standard mix of plugins we run, and add the revision date to the template in a standard form.  We could then, if we so chose, parse/capture/hide the date in the markup of the document itself, and expose it elsewhere in the TechDocs UI (e.g. in the header of the page) via the Reader.

2. **Capture and store the metadata centrally at build-time**: similar to above, but store it as a property of `techdocs_metatadata.json` (or a sibling JSON file) and load that file dynamically at run-time.

But both of those options assume that the files exist locally as a git repo, which is reasonable to assume in the recommended deployment (CI/CD), but won't work for the out-of-the-box experience.

**Comment by adrianke77** [comment]
1) seems reasonable.  I'm a little unclear what you meant by the out of the box experience? As in the markdown files were stored in a non-Git source?

**Comment by andrewthauer** [comment]
We have a custom MkDocs CI build and use https://github.com/timvink/mkdocs-git-revision-date-localized-plugin. The timestamps show in the site but not when viewed in Backstage. Have been meaning to investigate this actually. I suspect maybe the reader sanitizer is doing something but not sure.

**Comment by iamEAP** [comment]
> 1. seems reasonable.  I'm a little unclear what you meant by the out of the box experience? As in the markdown files were stored in a non-Git source?

Ah, sorry @adrianke77.   By "out-of-the-box" experience, I'm referring to the default way that TechDocs is experienced when you create a Backstage app instance (where the TechDocs backend will load the source code from a remote location, build it, and then serve it from local).  As compared to the recommended production deployment setup where the TechDocs backend just acts as a proxy to a cloud storage provider, which is populated with built docs sites via some other means (like CI/CD).

In the case of CI/CD, TechDocs builder/publisher would have access to git details because it was probably cloned in the normal course of a build.  But when TechDocs backend builds it locally, it pulls the underlying files via the `UrlReader`, which pulls a tar archive without any git metadata.

**Comment by adrianke77** [comment]
Perhaps we could have something that adds timestamps for docs with Git details and doesn't display if they're not available? 

@andrewthauer yes sounds like sanitisation is removing the DOM elements with the timestamp in them. A bit more added to the transforms in the TechDocs Reader page would probably easily render them again.

**Comment by adrianke77** [comment]
@andrewthauer it looks like mkdocs-git-revision-date-localized-plugin  and similar only work in CI?

**Comment by adrianke77** [comment]
@andrewthauer I seem to be seeing the `mkdocs-git-revision-date-localized-plugin` try to run `git log` on files to establish change dates but with TechDocs the files are cached outside the current directory (`/private/var/folders/0x/...`) so it gives InvalidGitRepositoryError. Did you have a workaround for this, I'm a little stumped..

**Comment by adrianke77** [comment]
@OrkoHunter if you had any suggestions on sorting out the above it would be much appreciated 😄

**Comment by andrewthauer** [comment]
@adrianke77 - We are currently just running the mkdocs build directly in CI without using the `techdocs-cli`. If the cli is copying the files to a temp directly without the git directory info this would explain your issue. We are planning to port over the cli in the next couple of months so we likely will run into this as well (assuming it's not resolved).

**Comment by adrianke77** [comment]
@andrewthauer I'm also running mkdocs build directly, although on my local instead of CI. Perhaps in CI conditions a temp directory isn't being used for some reason. I'm still digging into it.

**Comment by adrianke77** [comment]
@andrewthauer in case the info is useful for you, with `mkdocs-git-revision-date-localized-plugin` at this point in time I see the timestamps at page bottoms in Backstage,

Yes it looks like if Backstage is preparing/building docs, due to the docs being prepared to a temp folder without Git information the abovementioned plugin won't be able to generate edit dates. It however seems to work fine when run directly from a Git cloned folder, which means that it should produce edit dates correctly in CI.

**Comment by julian-alarcon** [comment]
This is a good feature to have.
