### ISSUE TITLE
ldapOrg will not map user-group relationships when using Active Directory

### ISSUE THREAD

**Issue by goober** [backstage/backstage#5074]
## Expected Behavior

When I am using the ldapOrg processor to fetch users and groups from our Active Directory it fails to map the relationship between a group and its members.

## Current Behavior

No users are mapped to their corresponding groups

## Possible Solution

I can see that it is expected that an ldap entity has the attributes `entryDN`
 and `entryUUID`. However, our Active Directory does not have these values for all entries. Instead they have an `objectGUID` which could be mapped to the current hardcoded `entryUUID` and a `distinguishedName` attribute  that could be mapped to the hardcoded `entryDN`.

So my proposal is that those values should be configurable, and could be defaulted to the current hardcoded values.

See:
https://github.com/backstage/backstage/blob/ff1e5da547c55a4b12a6b562deb948cd2a49c2f0/plugins/catalog-backend/src/ingestion/processors/ldap/read.ts#L28-L32

and: https://github.com/backstage/backstage/blob/3529831c459a664ef630dcb17b606019553b2db1/plugins/catalog-backend/src/ingestion/processors/ldap/read.ts#L259-L272

## Your Environment

- NodeJS Version: v14.15.1
- Operating System and Version (e.g. Ubuntu 14.04): osx or RHEL-8

**Comment by freben** [comment]
Oh. Ha,_of course_ they were different for some provider 😆

Yes, we could make this configurable then. The annotations might have slightly confusing names for some I guess, but those can't easily be changed so let's leave them alone.

https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageioldap-rdn-backstageioldap-uuid-backstageioldap-dn

Is this something that you would like to take a stab at addressing?

**Comment by goober** [comment]
Yes, you can assign me and I will try to come up with a PR tomorrow

**Comment by goober** [comment]
The only thing that I am concerned with is that the objectGUID is stored in a binary format and needs to be converted into a uuid string. https://github.com/ldapjs/node-ldapjs/issues/297

Do you have some thoughts on how we should do this with a more general approach?

**Comment by freben** [comment]
Oh, hm. That I don't know. I'd say it is probably not super important that the and result is exactly on guid form, but we'd at least have to translate it into something within the regular character range. So even detecting binary and transforming to hex might do I guess

**Comment by freben** [comment]
Wait the code makes it look like the source attribute actually contained hex, is that correct? If so, i wonder if we might just plain use it without any transcoding and just live with it
