### ISSUE TITLE
design: full Figma drop down menu only visible on very large screens

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#5085]
## Expected Behavior

When pulling the drop down in Figma, we can see all of the categories of the Backstage design that are available.

## Current Behavior

I'm at a standard HP Laptop 15" screen size of 1920x1080. At this size, I can't see the full menu viewing the Figma either in it's regular view or even full screen.

**Regular view:**
![image](https://user-images.githubusercontent.com/33203301/112351271-1f235f80-8ca0-11eb-8ebe-496bae274715.png)

**Full screen:**
![image](https://user-images.githubusercontent.com/33203301/112351362-319d9900-8ca0-11eb-89d1-bde177a5cf55.png)

**To see the full list, I have to zoom out once to 90% *and* have Figma in full screen view:**
![image](https://user-images.githubusercontent.com/33203301/112351507-58f46600-8ca0-11eb-99de-e6ff7e69697b.png)

## Possible Solution

Reorganize the sections so there are fewer of them, or see if Figma allows for a better way to create the menu system.

## Steps to Reproduce

1. Set screen size to 1920x1080.
2. View https://www.figma.com/community/file/850673348101741100
3. Click around various regular vs. Figma full screen, browser full screen, browser zoom in, etc.

## Context

I didn't know there was more design information available until I tested zooming out. Other users may not know also.

## Your Environment

- NodeJS Version (v12): n/a
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10
- Browser Information: Microsoft Edge (Chrome engine)

**Comment by adamdmharvey** [comment]
@katz95 is this one something you or your team could look into? thanks!

**Comment by benjdlambert** [comment]
@adamdmharvey have you tried using the desktop app of figma? I'm wondering if this is a bug caused by figma in the browser which is not something we can solve?

**Comment by adamdmharvey** [comment]
For sure, I'd say this is not something that can be "fixed" in the sense that as you point out, it's likely how Figma displays in the browser. And backstage just has a very long list of chapter sections. I'll be honest, I had no idea there even is a Desktop App of Figma; Backstage is the first project I've ever come across that uses it. 😁 So no, haven't tried it.

So I'd say two options.

* Rework the organization of Backstage's Figma chapters to organize it a bit less granularly; could be a good idea, but also I could appreciate that it might hide nuance.
* Update the backstage.io/docs to suggest to Backstage contributors that they should browse the Figma design not via the web but only via the thick client? (otherwise they'll never be able to get to all of the design recommendations?) [not ideal, but doable!]

**Comment by katz95** [comment]
Hmm I think this is a Figma thing...can you scroll down the list? I'm able to scroll and see everything in the dropdown
