### ISSUE TITLE
BarChartLegend not exported in @backstage/plugin-cost-insights 0.8.3

### ISSUE THREAD

**Issue by joaomilho** [backstage/backstage#5094]
BarChartLegend is exported in @backstage/plugin-cost-insights 0.8.2, but it is not in 0.8.3. As a breaking change this shouldn't happen and breaks our internal project when updating dependencies that use ^. I think there are some other non exported things like BarChartLegendOptions.

```sh
plugin-cost-insights ➜ cat package.json | jq .version
"0.8.2"
plugin-cost-insights ➜ grep -ril BarChartLegendOptions .
./dist/esm/index-ea2b68c2.esm.js.map
./dist/index.d.ts
```

```sh
plugin-cost-insights ➜ cat package.json | jq .version
"0.8.3"
plugin-cost-insights ➜ grep -ril BarChartLegendOptions .
./dist/esm/index-5681cdc4.esm.js.map
```

## Expected Behavior

0.8.3 should export at least the same components 0.8.2 did.

## Possible Solution

Not sure, but would be nice to have a spec that guarantees the API to the exported. But checking the code briefly I feel this is a build bug? In this case, needs more thinking.

## Steps to Reproduce

1. Install (`yarn add @backstage/plugin-cost-insights@0.8.2`)
2. Create a file with `import { BarChartLegend } from "@backstage/plugin-cost-insights";`
3. See there are no TS errors.
4. Install (`yarn add @backstage/plugin-cost-insights@0.8.3`)
3. See there are TS errors.

## Your Environment

- NodeJS Version (v12): 14.15.5
- Operating System and Version (e.g. Ubuntu 14.04): macOS Catalina (10.15.7)
- Browser Information: not relevant

**Comment by freben** [comment]
I believe this was fixed earlier today. https://github.com/backstage/backstage/pull/5080/files

**Comment by ryanvazquez** [comment]
Hey @joaomilho, some exports got missed during a refactor. The above PR resolves it. Sorry for the inconvenience.

**Comment by joaomilho** [comment]
Cool. Here's a quick suggestion that is not bullet proof, but I believe it is a good 20/80 https://github.com/backstage/backstage/pull/5102

A assume this patch will generate 0.8.4. Any plans to use `npm deprecate` on 0.8.3?

**Comment by ryanvazquez** [comment]
> I assume this patch will generate 0.8.4. Any plans to use npm deprecate on 0.8.3?

Yes, we will deprecate this patch once the new version is released. Probably sometime today

> Cool. Here's a quick suggestion that is not bullet proof, but I believe is a good 20/80 #5102

Thanks for this PR. I think some form of sanity check is warranted, we can discuss more there.

**Comment by benjdlambert** [comment]
This should be fixed with the release yesterday. Are we good to close this?
