### ISSUE TITLE
The backend-scaffolder publisher commit properties, like committer should be configurable

### ISSUE THREAD

**Issue by xliu-indeed** [backstage/backstage#5098]
## Feature Suggestion
Currently the commit action of the publish has hard coded the message, author and committer.
https://github.com/backstage/backstage/blob/68a10d34f90a8170e90f371de7f7b390c8f06080/plugins/scaffolder-backend/src/scaffolder/stages/publish/helpers.ts#L55

The request is to make this to be configurable, specifically to allow changing of the committer. It is true that the scaffolder is doing the work, but what triggered it was a specific user.

## Possible Implementation

Since the main use case of this is to make sure the scaffolder commits with the correct user context, it feels like this information should come from the current user's context.

## Context

For organizations like mine, commits to our internal repo are constrained to specific email domains. This is done via a precommit hook. The project scaffolder, by always having the commit email to be scaffolder@backstage.io, breaks this.

As previous stated, it also makes more sense to have the author be the user that triggered the project creation. From a project commit perspective it's important to have this information.

**Comment by benjdlambert** [comment]
+1

Yep this is something that should be configurable. Do you think that putting this in config is a good idea?

```yaml
scaffolder:
  commiter:
    name: Something
    email: myemail@scaffolder.com
```

Is this something you want to work on?

**Comment by benjdlambert** [comment]
Indeed it should be configurable. I was thinking at first that this could be config driven, but as you said it might be good to take the information from the user that created it. Internally at Spotify it's configured to be one email and one user, I wonder if we can do this in a nice way? @backstage/maintainers correct me if i'm wrong, but I think I can see a few issues with making this user driven. we don't actually have a single source of truth for the user's email do we? And I'm guessing that it's not going to be in the backstage token that is passed from the client to server right? The auth side is something i'm still catching up on, so could be wrong. How do you feel about making this config driven for a start so we can pull it out of `scaffolder.user` or something?

**Comment by freben** [comment]
The [identity API](https://github.com/backstage/backstage/blob/master/packages/core-api/src/apis/definitions/IdentityApi.ts#L22) does have a space for user profile info including their email. Not sure that that's what we want to drive this with, but mentioning it nonetheless.

On top of that, when the new identity to ownership [RFC](https://github.com/backstage/backstage/issues/4089) falls into place, the current user identity can be amended with additional alternate identities that are relevant to it. When those map to users in the catalog, those may have additional [profile info](https://backstage.io/docs/features/software-catalog/descriptor-format#specprofile-optional-1) too. So when the time comes to make a pull request, maybe the user could be asked as what identity they want the PR to be made.

**Comment by benjdlambert** [comment]
Closing as duplicate tracked here: https://github.com/backstage/backstage/issues/6217
