### ISSUE TITLE
Ability to create components from templates in a monorepo

### ISSUE THREAD

**Issue by h7kanna** [backstage/backstage#5099]
## Feature Suggestion
Feature: Ability to use templates to create pull requests for existing projects.

## Possible Implementation
Currently catalog-import has a similar feature of creating a pull request to a Github repo with catalog-info.
This is could be extended to templates as well. 

## Context

I would like to use this feature to create templates for terraform-modules, go packages, catalog-info.yaml  that can be targeted at a specific path in a monorepo.

**Comment by benjdlambert** [comment]
Hey! So this is something that we want to support, and a monorepo is an interesting use case. You can find more discussion on this here: https://github.com/backstage/backstage/discussions/5101#discussioncomment-528509

**Comment by h7kanna** [comment]
Hi ,
I referred to that mentioned comment.

For an initial support without the provider integration, the template can run all the steps and make the output of the template available as download in the results and the user can do the clone, branch, PR manually.

I see a file publisher added(#5049), there could be download result action. Does it sound okay?

**Comment by h7kanna** [comment]
Moreover, I am not able try out the template feature on with Github, because the Github access restricts the 'delete repo' role.
To try out if the template is generating expected output. there can be a preview download link to the output.

**Comment by h7kanna** [comment]
Thinking again download link option can be difficult to implement in the backend, because output has to be stored in the DB for that run.

**Comment by jhaals** [comment]
Hi!

I think you should be able to achieve this with the new scaffolder, perhaps not as tightly integrated as it could be but still doable.

Create a scaffolder template for a specific task(templating a new Go service for example) and take the path in the monorepo as input, then have a custom action that clones the monorepo, does necessary templating, pushes to a new branch and then creates a PR.

**Comment by tragiclifestories** [comment]
Internally we've built an action to publish a Github PR which we could probably upstream.

**Comment by h7kanna** [comment]
@tragiclifestories Please do. It will be really helpful..  for us adding components to monorepo is more frequent than creating new repos

**Comment by tragiclifestories** [comment]
Will do. 

I should say it's pretty dumb - it just takes whatever's in the workspacePath or a specific subdirectory and PRs everything into the target repo (again, optionally at some subdirectory). But it's working for a trivial template (essentially adding catalog YAMLs to a monorepo) and we've got plans to use it for something heftier (adding micro-frontends to a monorepo).
