### ISSUE TITLE
Allow registering custom field components in scaffolder

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#5134]
## Feature Suggestion

Add an interface for users to create their own fields and use them in scaffolder templates.

```tsx
// my-backstage/packages/app/src/App.tsx
const MyNewField: Field = (props: FieldProps) => {
  // return some JSX that does the right thing
}

scaffolderClient.registerField('MyNewField', MyNewField);
```

## Possible Implementation

My guess is that registerComponent would go on the `ScaffolderClient` as a new method, but there may be reasons not to do that or do something else.

## Context

Obviously it's a good thing to upstream generically useful field implementations, but there are also situations where you want to do business specific stuff like custom validations, populating select options from internal APIs, etc. So a fallback to add new components would be handy.

**Comment by tragiclifestories** [comment]
Alternative implementation - make it a prop on the router and thread down to the TemplatePage component?

**Comment by jhaals** [comment]
Yes! An API for registering custom fields with validation is something that has come up a few times since we released the updated scaffolder. It makes sense to allow for custom registration as long as we play nicely with react-jsonschema-form. Even though ScaffolderClient is poorly named for this functionality it's probably the place where it make sense to add it to. @benjdlambert feel free to suggest otherwise if you've got other ideas.

@tragiclifestories are you interested in working on this? 🙏

**Comment by tragiclifestories** [comment]
My team is basically working on backstage full time at the moment and I think that this would help unblock us and even prototype stuff upstream, so I'm going to say yes. But if my team-mates disagree I will say so here.

**Comment by tragiclifestories** [comment]
In terms of using the client, what would be the 'right' way to store these things? With a `useRef` type hook or something like that?

**Comment by freben** [comment]
I would say that this is something we can consider as static config - but in code. You'd supply one more entry [here](https://github.com/backstage/backstage/blob/master/packages/app/src/apis.ts#L44) where you supply a custom instance of the same API. You'd basically copy everything [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-import/src/plugin.ts#L38) and just give one more argument to the `CatalogImportClient` or so

**Comment by jhaals** [comment]
☝️  what @freben says is probably the way, feel free to open a draft PR if you wish to receive feedback early on. I'm assigning you to this issue, just reach out if you change your mind.

**Comment by benjdlambert** [comment]
Yep - I think we can probably rename the `scaffolderClient` to be `ScaffolderApi` and then registers it into a `Map` in the `ScaffolderApi`. 

Few considerations about typescript that I think you'll need to take into account, to make sure that the components are valid, and also what to do when there's already a field registered etc.

But go ahead and spin up a draft PR for some feedback and we can take a look 👍

**Comment by benjdlambert** [comment]
This is totally done and shipped - just missed this ticket.

**Comment by tragiclifestories** [comment]
Oh, awesome! Sorry I completely forgot I said I'd do this 😅
