### ISSUE TITLE
[plugin-lighthouse] create empty states to help guide new users

### ISSUE THREAD

**Issue by fastfrwrd** [backstage/backstage#514]
users of the plugin-lighthouse will either be faced with:

- the Lighthouse plugin which isn't yet correctly hooked up to lighthouse-audit-service
- a brand new instance of lighthouse-audit-service with nothing in it

both of those scenarios aren't really handled yet in the plugin, though the Intro component is a good start.

## Feature Suggestion

- Create a view that populates AuditList when the LighthouseApi is undefined, which instructs the user on how to register an API with the API registry in their Backstage app. Hide the Create Audit button in this state?
- Create a view that populates AuditList when the LighthouseApi is unreachable, which instructs the user to properly configure their lighthouse-audit-service. Hide the Create Audit button in this state?
- Create a view that populates AuditList with an empty version of the AuditListTable, which prompts the user to create their first audit.

## Context
- As a first-time user of the lighthouse plugin, I would like assistance getting the plugin working so that I can run my first audit.
- As an existing user of the lighthouse plugin, I would like a helpful message if something goes awry with my connection to lighthouse-audit-service, so that I can understand and fix my issue and use the plugin again.

**Comment by stefanalund** [comment]
@katz95

**Comment by fastfrwrd** [comment]
another notable empty state: what should we see in the columns with sparklines for a website that's having its first audit run right now? For now I'm just leaving them empty and adding some padding to keep the table row heights consistent.

<img width="1695" alt="Screen Shot 2020-04-08 at 12 19 27 PM" src="https://user-images.githubusercontent.com/231133/78808525-86fb7000-7993-11ea-93f2-60f064f27708.png">
