### ISSUE TITLE
Change GitHubAppConfig appId type to string

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#5140]
I'm trying to populate my GitHub app config credentials via env vars like so:
```
appId: ${GITHUB_APP_ID}
```
However, the config validation throws this error:
```
Error: Configuration does not match schema
 
  Config should be number { type=number } at /integrations/github/0/apps/0/appId
```

## Feature Suggestion
Since env vars are interpreted as strings, is it possible to update the type definition for `appId` to `string` to support this use-case?
https://github.com/backstage/backstage/blob/5618ffa733073b9fb13b91b360965896bef25add/packages/integration/src/github/config.ts#L78

**Comment by andrewthauer** [comment]
I ran into this as well and ended up hard-coding the appId in the yaml as a number. Should probably be `number | string` and the coerced to a number before being used.

**Comment by freben** [comment]
Or the config validator and loader should perhaps be able to silently detect / coerce stringified numbers. We've discussed this in the past. Ping @Rugvip

**Comment by freben** [comment]
The getter does coerce.

https://github.com/backstage/backstage/blob/master/packages/config/src/reader.ts#L18

So maybe this is just a matter of adding similar smarts to the schema? It would be risky for those that want to use raw `get()` to read the config as json data though 🤔

**Comment by andrewthauer** [comment]
> It would be risky for those that want to use raw `get()` to read the config as json data though 🤔 

Not sure I completely follow this point. Isn't using `get()` already more risky as it bypasses any configuration checking?

**Comment by freben** [comment]
The schema check still happens at startup though. So if you make it `string | number` the coercion / check burden is put on the consumers if they use `get`. If we instead make the framework coerce eagerly, at startup essentially, then you could declare it `number` and still pass in a string which gets handled silently, and `get` users could still more simply trust their schema.

Again, this isn't a feature yet, I'm just musing a bit
