### ISSUE TITLE
[core] extract a PluginIntro 

### ISSUE THREAD

**Issue by fastfrwrd** [backstage/backstage#515]
The Lighthouse Plugin has an Intro component which shows off portions of the README and a link to the blog. We should consider making this part completely free for plugin authors with a super-smart core component.

## Possible Implementation
- use react-markdown, a markdown AST solution, and some kind of rollup setup to allow imports of the markdown README to avoid docs drifting out of date
- implement some kind of component which interprets the lead image from the blog and formats a card for you

```
<PluginIntro
  dismissStorageKey="some.key.that.goes.in.local.storage"
  onDismiss={() => {}}
  usageCardTabs={{
    'Tab 1': 'markdown',
    'Tab 1': 'more markdown'
  }}
  blogCardUrl="https://backstage.io...."
/>
```

**Comment by braulio-balanza** [comment]
I think I could take a shot at this one. Any pointers on how to start the rollup config?
