### ISSUE TITLE
DOC - Contributors page, repo cloning instruction command incorrect url

### ISSUE THREAD

**Issue by cirpo** [backstage/backstage#5162]
[In the Getting Started - Contributors page](https://backstage.io/docs/getting-started/contributors) the instruction to clone the backstage repo has an incorrect url.

## Expected Behavior

Following the instructions on the page, `git clone git@github.com/backstage/backstage --depth 1` I should be able to successfully clone the backstage repo

## Current Behavior

```bash
fatal: repository 'git@github.com/backstage/backstage' does not exist
```

## Possible Solution

Change the instruction from 
```bash
git clone git@github.com/backstage/backstage --depth 1
```
to
```bash
git clone git@github.com:backstage/backstage --depth 1
```
PR here: https://github.com/backstage/backstage/pull/5163

## Steps to Reproduce

Follow the instructions on the [Getting Started - Contributors page](https://backstage.io/docs/getting-started/contributors)

**Comment by benjdlambert** [comment]
Fixed in #5163
