### ISSUE TITLE
bug(todo): Plugin doesn't support "file" location type from sample entities

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#5166]
## Expected Behavior

The out of the box examples and code straight from `master` shows how the Todo plugin works with the sample entities.

## Current Behavior

Pulling straight off `master`, the TODO plugin doesn't display any results for the sample `artist-lookup` entity, as it uses a local file processor in `app-config.yaml`.

![image](https://user-images.githubusercontent.com/33203301/112846572-32ee0d80-9074-11eb-8886-1637e8523536.png)

## Possible Solution

I believe I saw elsewhere this entity uses the managed by location dynamic annotation, or possibly source annotation, so perhaps this needs to check if that is `file` and have a more smooth error interface i.e., rather than throwing this warning panel, just say something like expected not to be able to read TODOs if that's not possible. (or fall back to identify if the entity has source code available linked via another annotation?)

## Steps to Reproduce

1. Clone off master
2. Run

## Context

Referenced entities come from here:

```yaml
locations:
  # Backstage example components
  - type: file
    target: ../catalog-model/examples/all-components.yaml
```

## Your Environment

- NodeJS Version (v12): Node v12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 WSL2 Ubuntu 18.04
- Browser Information: Edge (Chrome engine)

**Comment by benjdlambert** [comment]
it doesn't right now, maybe this is a feature request @adamdmharvey  :)
