### ISSUE TITLE
TODO Plugin Not working with Bitbucket Server SCM

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#5194]
Getting a 404 using the TODO's plugin with Bitbucket Server 

Not able to see the TODO comment i listed as:

`// TODO: Ideally this would be working`

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/6157895/113229005-17e1f000-9264-11eb-9f57-6e277e5a861c.png)

![image](https://user-images.githubusercontent.com/6157895/113229089-3d6ef980-9264-11eb-9fa1-bbad05fe79fe.png)

## Your Environment

- NodeJS Version (v12): Node 14
- Operating System and Version (e.g. Ubuntu 14.04): Win10
- Browser Information: Chrome

**Comment by Rugvip** [comment]
Did you install the backend plugin as well? Could see this happening otherwise

**Comment by regicsolutions** [comment]
@Rugvip Yep, I did install the backend plugin.

**Comment by regicsolutions** [comment]
Actually missed a line when adding the plugin to the backed, seems to be working now.

**Comment by kunickiaj** [comment]
> Actually missed a line when adding the plugin to the backed, seems to be working now.

Can you tell us what line it was? I have the same issue.

**Comment by regicsolutions** [comment]
packages/backend/src/index.ts

https://github.com/backstage/backstage/blob/0c58dd73d0e98b7c08b5f770bbb30e3c1923e55f/packages/backend/src/index.ts#L99
