### ISSUE TITLE
[RFC] oauth: use username instead of first part of e-mail address

### ISSUE THREAD

**Issue by rkristelijn** [backstage/backstage#5196]
**Status:** Open for comments

## Need

To have a proper greeting to users one would like to be greeted with his/her/its name instead of a part of the e-mail address.

## Proposal

oauth has a name property by default, this should be used. It could be that one has a middle name to (very common in the Netherlands)

## Risks

Backwards compatibility: could have a fallback to the previous solution.

Code involved: https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/providers/oauth2/provider.ts

**Comment by Rugvip** [comment]
#4532 and the broader implementation of it for all providers is the intended fix for this. Not sure when we'll be able to continue work there though

**Comment by Rugvip** [comment]
Will close this as #4532 is shipped, more information about customizing sign-in can be found at https://backstage.io/docs/auth/identity-resolver
