### ISSUE TITLE
Search backend does not work when Backstage API requires auth

### ISSUE THREAD

**Issue by erikxiv** [backstage/backstage#5207]
## Expected Behavior

* Search backend worker process collates documents successfully

## Current Behavior

* Search backend worker process fails with the error message below as no Authorization header is sent when fetching catalog entities.

```
2021-04-01T23:38:59.804Z search info Collating documents for software-catalog via DefaultCatalogCollator type=plugin
2021-04-01T23:38:59.810Z backstage info ::ffff:127.0.0.1 - - [01/Apr/2021:23:38:59 +0000] "GET /api/catalog/entities HTTP/1.1" 401 12 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
(node:81127) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://localhost:7000/api/catalog/entities reason: Unexpected token U in JSON at position 0
    at /adopter/backstage/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DefaultCatalogCollator.execute (/adopter/backstage/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:3268:22)
    at async /adopter/backstage/node_modules/@backstage/plugin-search-backend-node/dist/index.cjs.js:39:23
    at async Promise.all (index 0)
(node:81127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
```

## Possible Solution

* Have Search backend issue its own token to use when calling Backstage APIs (see https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/providers/google/provider.ts#L164 for a possible example). Add token as a parameter to [IndexBuilder](https://github.com/backstage/backstage/blob/master/plugins/search-backend-node/src/IndexBuilder.ts#L101) and [DocumentCollator interface](https://github.com/backstage/backstage/blob/master/packages/search-common/src/types.ts#L59)

## Steps to Reproduce

1. Follow instructions in https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md on how to require authentication of the backstage api
1. Start backstage
1. Look at the logs to see the error message (search backend runs on a timer)

## Context

Currently no impact as the search backend is not yet in use I think? When it is, I assume search will break for adopters using API auth.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS X Catalina
- Browser Information:

**Comment by iamEAP** [comment]
I wonder if we can work around this (while a common client for the scaffolder gets ironed out) by just conditionally using a pre-configured local instance of the catalog (if available), and falling back to HTTP if not?

I would guess most folks are deploying a monolithic backend (similar to the example backend) at this point, rather than spinning them off into individual services, and this would handle all of those cases in the interim.

**Comment by codingdiaz** [comment]
We are hitting this issue as well. We were looking to implement some new search capabilities with Elastic Search.

**Comment by erikxiv** [comment]
The PR looks like just the thing. Have not tried it yet, but closing this issue with good faith in the implementors.
