### ISSUE TITLE
Machine to machine authenticated API requests

### ISSUE THREAD

**Issue by lndbrg** [backstage/backstage#5210]
Sorry for diverging from using a template for this. I'm not sure if it's a bug, a feature request or an RFC. What I do know is that it needs to be discussed and I think there is some need for a strategy around this so that things do not break.

In #4515 there was a bunch of changes to search one of which was a commit that moved away from using the node/typescript api to using fetch: https://github.com/backstage/backstage/commit/44ec2571b65de281dd68c669562c1a67dc0976ce#diff-33c4c325b02f015fd1c7bc73792b6f3db9c7795c95bb703fc764821163536dbcR37
While I do believe that this is the overall correct way to approach this as running backstage on several nodes makes it more webscale ™️.

Most of the client requests have logic for passing along a token if the request is initiated from the frontend and an identity exists: https://github.com/backstage/backstage/blob/master/packages/catalog-client/src/CatalogClient.ts#L105.
This is not really suitable for backend initiated requests to other backends because that token simply does not exist. We discovered this problem when we enabled auto discovery through github. The auto discovery uses the DefaultCatalogCollator running periodically, and as you can see the collator uses the catalog entities api (through fetch) and is oblivious to any need for authnz.

Like mentioned before using fetch is likely the correct solutior but this introduces a few problems, yes i am aware that running the [API behind an auth middleware](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md) isn't necessarily supported, and that it's probably a better idea to put it behind a proper proxy/IdP that does this auth.
We as software engineers know most users aren't a fan of great ideas, but will rather settle for things that looks easy (we are an example of this, as it seems much easier to just add an auth middleware than it would be to configure and maintaining a full fledged IdP solution).

With that in mind, as end users of backstage we currently have a few different options to solve this problem (i have, maybe not helpfully, striked through the solutions that we don't want to do):
- ~~to remove auth from that API route~~ (not wanted)
- ~~diverge from upstream and inject a machine/service account token if the request is initiated purely from the backend~~ (diverging is not what we want)
- ~~setup a full fledge IdP~~ (not really wanted either)
- ~~disable the auto discovery of catalog-infos~~ (not wanted)
- start the discussion around the problem of backend initiated request that does not have a token passed a long from the frontend (much wanted)

As I don't want to come off as just a negative nelly I have produced the following words that are slightly more solution oriented:
If documentation exists on how to do do authenticated API requests, that solution will be used, despite not being officially supported. I'm not proposing removing this documentation, what I'm proposing is that, as this documentation exists, care needs to be taken to not break it for end users, and that we need to come up with a strategy around how to make it easy to adopt. I don't necessarily know what that strategy is, but I'm going to propose a solution to get the discussion going:

- Make auth for the backend/api requests configurable and abstract the fetching of things behind the TS/JS api as to never use fetch for things that have a client. This means that the client would know that it needs to add an auth header if it's configured and probably use fetch instead of querying the database straight away (or maybe always use fetch and there is a different API being used for actually querying the datasource, separating client APIs and data access layers, I don't know, I'm brainstorming).

**Comment by ericis** [comment]
Is this related to issue #5207?

**Comment by lndbrg** [comment]
> Is this related to issue #5207?

Yes, that descibes the specific issue of the collator, which is what we also ran into. But I believe that there's a bigger discussion to be had around how backend to backend calls work and also how authnz should work for api requests as a whole

**Comment by Rugvip** [comment]
Been thinking about the client approach as well, as I think it's the only sane way to be able to hook in whatever service authentication solutions are out there. An idea I've been toying with is to give it a handler for a custom `plugin:` protocol, for example:

```ts
const http = useApi(httpApiRef);

const res = await http.fetch('plugin://catalog/entities');
```

It would let us automatically include identity tokens and resolve plugin endpoints for those requests, which should mostly solve the problem of those things otherwise being a bit opt-in and forgotten. For backend requests we'd probably supply a default service token if a user token is not provided, using whatever form of service to service authentication that has been configured (including no authentication). Now I think there's a bunch of trouble with that approach that I won't go into x), but I would love to explore more options.

When it comes to the particular technology used for service to service authentication, I don't think we should be opinionated and allow whatever form of Mutual TLS/Token/ALTS/SPIFFE/Eggshell/Nothing to be hooked in.

This is also an area that while it's in the back of our minds, it's not our focus right now, and we lack the bandwidth to invest and come up with a good solution. That's one of the reasons why we at the moment have a very minimal and manual approach, as it's relatively quick and safe from a design point of view. We appreciate any and all suggestions from the community on this topic that can help drive it forward!

**Comment by freben** [comment]
Would it make sense to pass the Backstage specific auth as a dedicated `x-backstage-auth` token? To be able to use it specifically  for gatekeeping for example the proxy while still passing an `Authorization` to the upstream

**Comment by freben** [comment]
For the backend, this ties into the discussion in #1519 about continuation-local storage. I'd love to provide a similar fetch wrapper as part of a `getContext()` that has the ability to pass on user-provided auth etc

**Comment by lndbrg** [comment]
I do understand that solving the over arching strategy is not something that's going to happen _now_. And i think #5207 is the more important one to focus on in the short term. I do appreciate that a long term solution is some time in the future, I strongly believe that acknowledging the fact that you now have users with API auth enabled (this sounds a bit harsh maybe, I know that you know and that you don't break it on purpose, what I mean is acknowledging it in the development process) and making sure that you have it in mind during the development/review process.

I'm very much pro the solution that @Rugvip is presenting (exact implementation is not that important, but having a smart abstraction around it is).

@freben that sounds like a solution that can be implemented in the short term, before any larger abstraction, so I'm pro that too.

Would there be any value in me trying to create a more coherent RFC from the word salad I produced in the initial post?

**Comment by Rugvip** [comment]
Yep! RFC would be awesome. Tbh I think at this point it would make sense to focus it on ideas for how we would implement a common client or something equivalent. I'm very much still up for exploring other options, but to be able to make some kind of decision I think we need to really dig into the common client idea and what it could look like, including how other projects approach the same problem.

**Comment by iamEAP** [comment]
`┬─┬ノ(ಠ_ಠノ)`

**Comment by tomwwright** [comment]
My team is invested in this one after hitting this issue https://github.com/backstage/backstage/pull/6345 (and similar) after implementing the guidance on API security. Anything we can do to help?

**Comment by iamEAP** [comment]
Hey folks!  Looks like the plan to tackle this is starting to coalesce in #7253 -- if you're interested in helping out, recommend joining forces in that meta issue!

**Comment by freben** [comment]
This is starting to come together through https://github.com/backstage/backstage/pull/7943 !

**Comment by freben** [comment]
There are also some RFCs for context passing within backends, and a variant of the httpApi that @Rugvip mentions:

https://github.com/backstage/backstage/pull/8042

https://github.com/backstage/backstage/pull/6399

**Comment by feedmypixel** [comment]
If I understand correctly, can this functionality also be used to fix the Badges call to the catalog API when you have Authed your catalog? As described here https://github.com/backstage/backstage/issues/5039
If so I can raise a PR when this has been released as we would love to have badges available

**Comment by feedmypixel** [comment]
If I understand correctly, can the functionality found in https://github.com/backstage/backstage/pull/7943 also be used to fix the Badges call to the catalog API when you have Authed your catalog? As described here https://github.com/backstage/backstage/issues/5039
If so I can raise a PR when this has been released as we would love to have badges available

**Comment by nissayeva** [comment]
#7943 has been merged! the solution fixes the breaking collators. is this issue alright to close? is there any bug or proposal here that hasn't been captured elsewhere yet?

**Comment by Rugvip** [comment]
I think we have to original issue covered and are good to close! Let's cover any specific places where we need to add in authenticated requests in separate issues.

Regarding my suggestion about an http API we'll be working on shipping https://github.com/backstage/backstage/pull/6399, so that'll be covered too. Let's not block this issue on that though :grin:
