### ISSUE TITLE
Support having scaffolder perform Github publish action on behalf of user

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#5215]
## Feature Suggestion

Utilize the [user-to-server](https://docs.github.com/en/developers/apps/identifying-and-authorizing-users-for-github-apps) functionality of GitHub apps to perform the repo publish action on behalf of the user.

## Possible Implementation

See https://github.com/backstage/backstage/issues/5214

## Context

The scaffolder now support auth via GitHub apps and allows you to publish a new repo on any GitHub org that the app is installed in. However, this also allows a user to create a new repo in an org the app has access to but the user itself does not. By allowing the GitHub app to act on behalf of the user instead of itself, it would limit the GitHub request to the permissions that the user has.

Additionally, our GitHub org admins would prefer to have repo creation events attributed to the actual user who triggers the action for [audit purposes](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/reviewing-the-audit-log-for-your-organization).

**Comment by kuangp** [comment]
Also noting that we have the use-case where we want to set the repo access to the username of the user triggering the scaffold process. We're currently doing this by asking the user to enter their username in the form UI and passing this to the `access` parameter of the GitHub publish action in our template since there doesn't seem to be any other way to automatically do this.

Supporting publishing repos via a user-to-server request would also solve this issue since the user will inherently be added as a collaborator.

**Comment by kuangp** [comment]
This issue is still relevant for us

**Comment by kuangp** [comment]
still relevant

**Comment by regicsolutions** [comment]
@kuangp wondering if your using the repoPickerExtension? We are looking to do something similar in the short term for Bitbucket Server and have the user provide a Bitbucket username, anything you can share would be helpful, Thanks!

**Comment by kuangp** [comment]
> @kuangp wondering if your using the repoPickerExtension? We are looking to do something similar in the short term for Bitbucket Server and have the user provide a Bitbucket username, anything you can share would be helpful, Thanks!

I am currently using the `repoPickerExtension` and a custom hidden extension that grabs the current user
s username but don't currently have a workaround for performing the publish on behalf of the user since the backend still relies on the GitHub app's permissions

**Comment by regicsolutions** [comment]
Thanks for the reply @kuangp any way you can share a sample of the hidden extension you are using that grabs the current user?

**Comment by kuangp** [comment]
Here's our very simple implementation: 
```ts
const CurrentUserField = ({ onChange }: FieldProps<string>) => {
   const identityApi = useApi(identityApiRef);
   onChange(identityApi.getUserId());
  
   return (<></>);
};
 
export const CurrentUserFieldExtension = scaffolderPlugin.provide(createScaffolderFieldExtension({
  component: CurrentUserField,
  name: 'GetCurrentUser',
}));
```

**Comment by Rugvip** [comment]
How do you feel about closing this as a duplicate of #5214? Seems to be pretty much the same issue to me tbh. Groundwork for these are being done in #7141 btw, but we also need to figure out how to communicate the need for a token.

**Comment by kuangp** [comment]
sure, closing as duplicate
