### ISSUE TITLE
Use service-id instead of integration-key for pagerduty plugin

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#5223]
The pagerduty backstage plugin expects an annotation on the component called "pagerduty.com/integration-key". This integration-key is sensitive. https://community.pagerduty.com/forum/t/event-api-integration-key-does-it-need-to-be-a-secret/429/2

Preferably the service-id should be used in place of the integration-key.

There is a challenge here. The frontend react application is using the integration key to create an alert via the pager duty events API.

This means that if the integration-key is removed a new mechanism is needed to keep the feature that triggers an alert.

The available alternative is to use the pager duty rest API instead of the pager duty events API to trigger the alert. This has some advantages and disadvantages. e.g. the rest api "trigger alert" action is not as fully featured as the event api. However, the events API appears to be designed for backend systems to trigger alerts and requires the sensitive integration key. As such it is possible that using rest api authenticated using Oauth maybe the right thing to do.

## Feature Suggestion
- replace the annotation integration-key with service-id
- change the trigger alert feature to use the pager duty rest api instead of the events api
- change the trigger alert feature to be authenticated with an oauth client on pager duty and send an alert as the logged in user, using the service id.

**Comment by andrewthauer** [comment]
Another consideration is that not all services defined in PagerDuty will map 1 to 1 to a component. For instance, you may have have a component service that has difference escalation policies that map to different PagerDuty services. This implies that it might be `Backstage Entity 1..* PagerDuty Service`.

**Comment by freben** [comment]
I'll just note here, that a typical Backstage installation will be secured and isolated to a given organisation. The potential audience for the integration keys will typically be your own company's employees, alleviating this issue significantly.

This also made me think - maybe there's room to consider field-level access controls in the future RBAC work. It could be that potentially sensitive fields like this could be cut out for catalog callers that do not have the right permissions to see them. This is just a loose thought, not really related to the ask :)
