### ISSUE TITLE
[Search] Introduce a global/modal search experience

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#5225]
## Context
The search bar in the nav can feel cramped, and forcing users to navigate to the search page to find results introduces an unnecessary step in their discoverability journey.  Instead, what if we introduced a simple search modal UX of some kind, that shows results without having to navigate to the full search page?

## Scope / UAT Target
- [ ] TBD

## Possible Implementation Details
Would be good to re-use as much as possible from existing search components introduced as part of this milestone.

**Comment by andrewthauer** [comment]
Having a search/command palette that is activated via a global keyboard shortcut would be amazing!
