### ISSUE TITLE
Github Application not used when fetching catalog-info.yaml

### ISSUE THREAD

**Issue by dariddler** [backstage/backstage#5230]
When discovering private repositories using the [github discovery](https://backstage.io/docs/integrations/github/discovery) process as documented WITHOUT token being defined on `integrations.github` you end up being able to fetch a list of repositories that should be discovered but fails due to assuming that its a public repository as the optional token is missing  from the integrations

## Expected Behavior
If we define a github application it should be used for the entire flow.

If a repository is discovered with the expected files, it should be imported and made visible in the catalog

## Current Behavior
The backend properly discovers the repositories with a catalog-info.yaml file but fails to fetch them throwing a `404` as they are not public.

## Possible Solution
Create short-lived access tokens using the application to pass along to the reader

## Steps to Reproduce

I will not provide github application details for obvious reasons :)

1. Define `integrations.github.apps` according to documentation in `app-config.yaml`
2. Make sure `token` is not defined  on `integrations.github`
3. Attempt to discover a private repository that the github application has access to

**Comment by lndbrg** [comment]
The issue seems to be that the github integration is using config.token: https://github.com/backstage/backstage/blob/c1113129f040a297b7cefc39a1649fb262defe87/packages/integration/src/github/core.ts#L75
When it should be using the GithubCredentialsProvider:
https://github.com/backstage/backstage/blob/0b08c09dce59a860afeec5af1799ec26b3a68c20/packages/integration/src/github/GithubCredentialsProvider.ts

**Comment by lndbrg** [comment]
It looks like the todo plugin also needs to have the GithubCredentialsProvider added

**Comment by andrewthauer** [comment]
I believe the `GithubOrgReaderProcessor` is also not using the `GithubCredentialsProvider` yet either.

**Comment by dariddler** [comment]
After some more detective work, this appears to be caused by a faulty github app configuration yaml file on the server.
