### ISSUE TITLE
Cannot link Okta Users & Groups to Apps and components in Service Catalog.

### ISSUE THREAD

**Issue by ParthaGoswami** [backstage/backstage#5238]
Need Help/Knowledge.

I have created new services where I have placed the "login user " as an owner. But still don't see the service getting filtered as a part of the logged in user. I am use Okta for authentication with configured groups already integrated with backstage. How can I use the group information and other attributes present in Okta portal to use that as a part of Service Catalog filtering ?

Thanks in Advance.

<img width="894" alt="backstage1" src="https://user-images.githubusercontent.com/44538343/113822752-75fa6000-979b-11eb-8874-7f81ffd41239.png">

**Comment by Rugvip** [comment]
Org user and group information isn't actually brought in via authentication, it needs a separate ingestion process in the catalog, [here](https://backstage.io/docs/integrations/ldap/org) is how you set it up for LDAP for example.

The entire org data / auth / ownership chain is still WIP though, you can read more about it in the latest RFC on the topic: https://github.com/backstage/backstage/issues/4089
