### ISSUE TITLE
Archived Repositories are not removed from Backstage

### ISSUE THREAD

**Issue by nirga** [backstage/backstage#5239]
I'm using `github-discovery` to scan and import repositories in my organization to Backstage. When a repository is archived, it still remains in Backstage (and there's no way to remove it).

## Expected Behavior

Archived repos should be removed from view.

## Current Behavior

Archived repos are forever left in the UI and the DB.

## Steps to Reproduce

1. Use `github-discovery` to scan an entire org's repos.
2. Archive one of the repos that was added to Backstage.
3. Repo still appear in Backstage.

## Context

`github-discovery` is the main method we use for syncing Backstage with our repositories.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS X
- Browser Information: Chrome

**Comment by nirga** [comment]
@Rugvip I can take it, I wonder though what's the best way to resolve it. Since the main problem is that the catalog DB works in "upsert" mode and there's no way to delete components that were added before.

**Comment by Rugvip** [comment]
@nirga Thank you! I think it's best to just have it select the correct set of repos and not worry about deletions for now. It should be possible to test by pointing it to an org that already has a couple of archived projects and make sure it doesn't show up. Probably leave it with a `// TODO` that it needs catalog deletions implemented for it to work fully.

**Comment by wanisfahmyDE** [comment]
Hey @freben @nirga the issue still persists for me running on the latest 1.20.3, I checked the github webook events and they repository.archived is published correctly, however it seems backstage is not catching this one.

I am using the GitHubEntityProvider with the below config and this works for adding/deleting a catalog-info.yaml in our org, but archiving events not.

```yaml
catalog:
  providers:
    github:
      providerId:
        organization: 'myorg'
        catalogPath: '/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '.*'
        validateLocationsExist: true
```

```TypeScript
//packages/backend/src/plugins/catalog.ts
const githubProvider = GithubEntityProvider.fromConfig(env.config, {
        logger: env.logger,
        schedule: env.scheduler.createScheduledTaskRunner({
            frequency: {minutes: 720}, /* twice per day checking all repos and importing/refreshing in the catalog */
            timeout: {minutes: 30},
        })
    });
    env.eventBroker.subscribe(githubProvider); /* any new add/delete/modify actions in catalog-info.yaml will be handled by the event broker */
    builder.addEntityProvider(githubProvider);
```

is there a config missing for archiving events?

**Comment by wanisfahmyDE** [comment]
created a new issue here: https://github.com/backstage/backstage/issues/21906
