### ISSUE TITLE
Cannot import SignInConfig in App.tsx from @backstage/core

### ISSUE THREAD

**Issue by jl98741** [backstage/backstage#5270]
After adding the GitLab authentication provider as per the [documentation](https://backstage.io/docs/auth/#adding-the-provider-to-the-sign-in-page), compilation with `yarn tsc` fails as it can't find SignInConfig from @backstage/core

## Expected Behavior

`yarn tsc` compiles the project without errors

## Current Behavior

```packages/app/src/App.tsx:27:28 - error TS2459: Module '"@backstage/core"' declares 'SignInConfig' locally, but it is not exported.

27 import { gitlabAuthApiRef, SignInConfig, SignInPage } from '@backstage/core';
                              ~~~~~~~~~~~~

  node_modules/@backstage/core/dist/index.d.ts:784:14
    784 declare type SignInConfig = {
                     ~~~~~~~~~~~~
    'SignInConfig' is declared here.
```

## Steps to Reproduce

1. Add code to import SignInConfig from @backstage/core in App.tsx as per the documentation
2. Run `yarn tsc`

## Context
Using a backstage app originally created using `npx @backstage/create-app` (@backstage/core 0.7.3)

## Your Environment

- NodeJS Version: 14.16.1
- Operating System and Version: Ubuntu 20.04.2 LTS

**Comment by timbonicus** [comment]
Thanks, my mistake! Remove the type for now if this is blocking you, but will be fixed by #5277. 🙂
