### ISSUE TITLE
Too small font size in techdocs tables generated from markdown

### ISSUE THREAD

**Issue by madtrick** [backstage/backstage#5276]
The tables rendered in TechDocs from markdown documents have a too small font size compared to the rest of the document.

This a complementary problem with tables to that reported at https://github.com/backstage/backstage/issues/5264.

## Expected Behavior

![image](https://user-images.githubusercontent.com/48772/114203144-2d3bd600-9958-11eb-95d8-61e5c4baa7ac.png)

The tables would use a font size in line with the rest of the document (I manually tweaked the classes for the above screenshot)

## Current Behavior

![image](https://user-images.githubusercontent.com/48772/114202956-01205500-9958-11eb-8248-9592fb93a95f.png)

As it can be seen in the screenshot, the font size is to small for it to comfortable to read.

## Steps to Reproduce

1. Create a MD file with a table. For example
```markdown
## Functions

|  Function | Description |
|  --- | --- |
|  [createClient(options)](./http-client-fork.createclient.md) | Creates a new http client instance |
```
2. run `techdocs-cli serve`

## Your Environment

- NodeJS Version: v14
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS
- Browser Information: Chrome 89
- `@techdocs/cli` version: `0.3.3`

**Comment by Crevil** [comment]
I think it's the same case for admonitions?

**Comment by dtuite** [comment]
This was fixed in https://github.com/backstage/backstage/pull/5281

**Comment by WillSewell** [comment]
> I think it's the same case for admonitions?

@Crevil, yes, I think so. I created an issue for this: https://github.com/backstage/backstage/issues/5448
