### ISSUE TITLE
MkDocs Material CSS Variables not being applied to docs shadow-dom

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#5279]
## Expected Behavior

The CSS variables which come packaged with MkDocs Material should apply to elements inside the shadow-dom that hosts docs in Backstage.

MkDocs material comes with a number of CSS variables like this (many have been omitted here for brevity).

```css
:root{--md-default-fg-color:rgba(0,0,0,0.87);--md-default-fg-color--light:rgba(0,0,0,0.54);--md-default-fg-color--lighter:rgba(0,0,0,0.32);}
```

You can see all these variables in the CSS file served by Backstage at http://localhost:7000/api/techdocs/static/docs/default/Component/sample-service-1/assets/stylesheets/main.fe0cca5b.min.css

## Current Behavior

These CSS variables do not bind to the shadow-dom because (I believe) the selector `:root` refers to the top level `<html />` element rather than the shadow-dom `<html />` element.

## Possible Solution

The solution could involve using the `:host` selector instead of `:root` ([here's a StackOverflow example](https://stackoverflow.com/questions/42627939/css-selector-for-shadow-root-or-all-top-level-elements-in-shadow-root)). This CSS with all the variables comes packaged with the MkDocs Material library.

## Steps to Reproduce

Load a Backstage docs page and compare the styling differences to a [typical MkDocs Material page](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme).

To see the fix in the browser, add the following HTML to the `<head />` element of the shadow-dom which hosts the docs.

```html
<style>
:host{--md-default-fg-color: hsla(0, 0%, 0%, 0.87);--md-default-fg-color--light: hsla(0, 0%, 0%, 0.54);--md-default-fg-color--lighter: hsla(0, 0%, 0%, 0.32);--md-default-fg-color--lightest: hsla(0, 0%, 0%, 0.07);--md-default-bg-color: hsla(0, 0%, 100%, 1);--md-default-bg-color--light: hsla(0, 0%, 100%, 0.7);--md-default-bg-color--lighter: hsla(0, 0%, 100%, 0.3);--md-default-bg-color--lightest: hsla(0, 0%, 100%, 0.12);--md-primary-fg-color: hsla(231, 48%, 48%, 1);--md-primary-fg-color--light: hsla(230, 44%, 64%, 1);--md-primary-fg-color--dark: hsla(232, 54%, 41%, 1);--md-primary-bg-color: hsla(0, 0%, 100%, 1);--md-primary-bg-color--light: hsla(0, 0%, 100%, 0.7);--md-accent-fg-color: hsla(231, 99%, 66%, 1);--md-accent-fg-color--transparent: hsla(231, 99%, 66%, 0.1);--md-accent-bg-color: hsla(0, 0%, 100%, 1);--md-accent-bg-color--light: hsla(0, 0%, 100%, 0.7)}

:host>*{--md-code-bg-color: hsla(0, 0%, 96%, 1);--md-code-fg-color: hsla(200, 18%, 26%, 1);--md-text-color: var(--md-default-fg-color);--md-text-link-color: var(--md-primary-fg-color);--md-admonition-bg-color: var(--md-default-bg-color);--md-admonition-fg-color: var(--md-default-fg-color);--md-footer-bg-color: hsla(0, 0%, 0%, 0.87);--md-footer-bg-color--dark: hsla(0, 0%, 0%, 0.32);--md-footer-fg-color: hsla(0, 0%, 100%, 1);--md-footer-fg-color--light: hsla(0, 0%, 100%, 0.7);--md-footer-fg-color--lighter: hsla(0, 0%, 100%, 0.3)}
</style>
```

## Context

I suspect this problem is the root cause of #5264, the weirdness I noticed while upgrading MkDocs Material in https://github.com/backstage/mkdocs-techdocs-core/pull/23 and potentially other styling issues.

## Your Environment

- NodeJS Version (v15):
- Operating System and Version: Mac
- Browser Information: Chrome 89.0.4389.114

**Comment by dtuite** [comment]
Digging into this a little deeper, I can see that @Fox32 hit this problem before and opted to copy/paste some of the styling from MkDocs Material into `plugins/techdocs/src/reader/components/Reader.tsx` with `injectCss`.

It seems that one problem you hit when copying the CSS variable colors over and using `:host` is that dark mode state is not shared with the CSS variables inside the shadow-dom. They stay on light mode when I switch to dark mode.

**Comment by Fox32** [comment]
Yep, this is not nice. I guess one option is to have an own theme that use different techniques, but that might be a lot of work. #3998 talks about these limitations and possible solutions.

**Comment by dtuite** [comment]
Closing in favor of #3998
