### ISSUE TITLE
Add "if" prop to "EntityLayout.Route"

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#5296]
## Feature Suggestion

Creating an issue to formally request and track suggested enhancement mentioned in https://github.com/backstage/backstage/pull/5233#issuecomment-815852770

## Context
 We would like support to conditionally show Entity page tabs similar to the functionality provided by `EntitySwitch.Case`. For our use-case this is the last blocker for us to fully convert our Entity page to the new composability API.

**Comment by freben** [comment]
Makes sense! Is this something that you would like to be assigned to?

**Comment by kuangp** [comment]
@freben I'm not very familiar with React but I can take a stab at it. Is there any example code I can take inspiration from? Should I just look at the `EntitySwitch.Case` implementation?

**Comment by freben** [comment]
That's a good place to start. @Rugvip anything you wanted to push for from the start?

**Comment by kuangp** [comment]
@freben @Rugvip I might need some guidance here...

Digging into the code it looks like the implementation for `EntityLayout.Route` has migrated to `TabbedLayout.Route` in `@backstage/core`:
https://github.com/backstage/backstage/blob/2373468553e804ef904535c6c7d58af84dfcca8b/plugins/catalog/src/components/EntityLayout/EntityLayout.tsx#L195

I was hoping to add a `if` prop to `TabbedLayout.Route` but since this component exists in `@backstage/core` it doesn't look like it's appropriate to `import { useEntity } from '@backstage/plugin-catalog-react'` in order to grab the entity context to evaluate the `if` condition.

Some possible solutions:
- Re-implement the a dedicated `EntityLayout.Route` component that is Entity context aware and export and use `RoutedTabs` directly instead of using `TabbedLayout`
- Somehow inspect the `EntityLayout.Route` child nodes of `EntityLayout` and bind the `if` prop callbacks with the Entity context before passing down to `TabbedLayout`

What would you recommend I do here?

**Comment by Rugvip** [comment]
@kuangp Seeing as we also want to control the tabs that are being displayed, I don't think we can get away from a more custom implementation of `TabbedLayout`. I'd say duplicate the code from `@backstage/core` for now.

We're also looking for ways to make the process of creating custom layouts easier though, so if there are some things that can be abstracted away in the process in a sane way, that could be useful for the future.
