### ISSUE TITLE
Add config option to Google auth to restrict allowed authentication domain

### ISSUE THREAD

**Issue by timbonicus** [backstage/backstage#5300]
## Feature Suggestion

Google auth supports a `hd` / `hostedDomain` param to limit domains allowed to OAuth (e.g. to `spotify.com` instead of any Google login).

## Possible Implementation

This [passport-google-oauth issue](https://github.com/jaredhanson/passport-google-oauth/issues/5) makes me think it should be supported if we had an auth config for it and passed `hostedDomain: [<domains>]` in [here](https://github.com/backstage/backstage/blob/18f7345a6c29dcfccef7df081b1708f2bf8f62ff/plugins/auth-backend/src/providers/google/provider.ts#L98).

Though Google warns against [relying only on this](https://developers.google.com/identity/protocols/oauth2/openid-connect):

> Don't rely on this UI optimization to control who can access your app, as client-side requests can be modified. Be sure to validate that the returned ID token has an hd claim value that matches what you expect (e.g. mycollege.edu). Unlike the request parameter, the ID token hd claim is contained within a security token from Google, so the value can be trusted.

**Comment by freben** [comment]
Agreed, this can simplify the login dialog to not present irrelevant options. The changes started in #4532 will help make it possible to put the safety checks in place.

**Comment by Crevil** [comment]
Related to #3936 I think?

**Comment by freben** [comment]
Ah yes! Closing as duplicate, thanks for linking them up.
