### ISSUE TITLE
New app created with @backstage/create-app fails to build

### ISSUE THREAD

**Issue by TrentScholl** [backstage/backstage#5305]
A new app created with @backstage/create-app fails to build.

## Expected Behavior

The app should build successfully.

## Current Behavior

The following error is outputted when running `yarn build`

```
Error: Failed to compile.
/backstage-app/node_modules/graphql-language-service-interface/esm/GraphQLLanguageService.js 100:23
Module parse failed: Unexpected token (100:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         }
|         let customRules = null;
>         if (extensions?.customValidationRules &&
|             typeof extensions.customValidationRules === 'function') {
|             customRules = extensions.customValidationRules(this._graphQLConfig);

error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in 'app'
error Command failed with exit code 1.
```

## Steps to Reproduce

1. Create a new app with `npx @backstage/create-app` (Doesn't matter if it's SQLite or Postgres)
2. Run `yarn build` in the root directory of the new app

## Your Environment

Tried NodeJS 12 & 14 on Windows 10, WSL (Ubuntu 20.04) and in a Docker build using node:14-buster.

**Comment by OrkoHunter** [comment]
Closing as duplicate. Please see https://github.com/backstage/backstage/discussions/5298#discussioncomment-600702
