### ISSUE TITLE
Documentation on Deploying/Upgrading to Released versions

### ISSUE THREAD

**Issue by bbgobie** [backstage/backstage#5318]
Sorry, have no experience with Node projects.
From what I've seen of playing around and going through the docs:
npx @backstage/create-app
and yarn backstage-cli versions:bump
Are creating/updating the app to the latest from github? It seems quite a bit can be broken by going with this approach.

Would it be possible to document/provide info about how to create an app at a released version, and subsequently upgrade to another released version?

eg
npx @backstage/create-app:2021-04-18
yarn backstage-cli versions:bump -r 2021-04-13

**Comment by OrkoHunter** [comment]
> Are creating/updating the app to the latest from github? It seems quite a bit can be broken by going with this approach.

> Would it be possible to document/provide info about how to create an app at a released version, and subsequently upgrade to another released version?

The `create-app` and `versions:bump` will both make sure that your Backstage app is at the latest "released" version from NPM. They are not pulled from the latest GitHub.
