### ISSUE TITLE
[Create Form]User doesn't know what has occurred when submitting with errors

### ISSUE THREAD

**Issue by MiguelRamBalt** [backstage/backstage#5336]
## Expected Behavior
Send focus up to the "Errors" text at the top. Then the user will immediately hear there are errors and can navigate back through the form.

## Current Behavior
When the form is submitted with errors, it's immediately clear to sighted users who see the errors and the red text. For a screen reader user they don't hear anything and focus stays on the button. It will be unclear if the button worked and how to proceed.
https://user-images.githubusercontent.com/24494837/114787314-33112d00-9d45-11eb-98bb-df72da7dbcb7.mov

## Possible Solution

add a custom parameter passing from a parent component to replace a [noHtml5Validate](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx#L85) for [MultistepJsonForm](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx#L52)

## Steps to Reproduce

1. Go to /create
2. Choose one of the cards to open the form
3. Navigate to "Next step" button and trigger without filling in form

## Your Environment

MAC OS

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by freben** [comment]
Hi, thanks for reporting! I am not entirely sure I understand the possible solution though, sorry. Is this something that you might be able to contribute a fix for?

**Comment by MiguelRamBalt** [comment]
Hi @freben I want to suggest if we can add [noHtml5Validate](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx#L91) as a parameter, we can remove or add that behavior when is needed. so in this case the '@rjsf/core' library doesn't have the ability to focus the first error in the form when noHtml5Validate is true.
what do you think about that solution??
Thanks! Regards!

**Comment by MiguelRamBalt** [comment]
Hi @freben  Do you have any feedback regarding this issue???

Thank you in advance!

**Comment by freben** [comment]
Did you mean _removing_ that flag? 🤔  If it solves the accessibility, and doesn't introduce additional issues, then sure!
