### ISSUE TITLE
[TechDocs] Introduce a healthcheck endpoint for the TechDocs backend

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#5345]
## Feature Suggestion

When deploying the TechDocs backend (as part of a more monolithic Backstage backend, or in isolation), it will be important to know that the TechDocs backend is healthy and correctly configured.

We should expose the health of the TechDocs backend service on an http endpoint for the benefit of external systems, e.g. a Kube liveness probe or a synthetic monitoring service.

## Possible Implementation

Add a route `/healthz` to `techdocs-backend`, which leverages the result of a configured publisher's `getReadiness` method, as well as configuration, to indicate a healthy service using HTTP status codes according to [kube conventions](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request).

The current `getReadiness` implementations simply check that a configured storage provider is _accessible_, but we should add two more checks:
- `isReadable` (indicating that the TechDocs backend is able to read from the configured storage)
- `isWriteable` (indicating that the TechDocs backend is able to write to the configured storage)

Which we could conditionally validate based on configuration...  e.g. If `techdocs.builder` is `external`, then we could ignore the `isWriteable` check

## Context

This is a follow-up to #5260, which added a `getReadiness` method to Publishers.

**Comment by dhenneke** [comment]
The `backend-common` package already provides a rudimentary health check endpoint for the backend: https://github.com/backstage/backstage/blob/826d50e033648c3c6950f778dac6667d053f7b36/packages/backend/src/plugins/healthcheck.ts#L24

It _could_ be an option to investigate if we should extend this functionality so other backends could register own health checks. 

On the other hand one needs to carefully select what to include in readiness/liveness checks since some issues should not result in an unreachable deployment. But the `/healthz` endpoint can for sure be a nice source for SLA monitoring or other synthetic monitoring strategies.

**Comment by iamEAP** [comment]
> It _could_ be an option to investigate if we should extend this functionality so other backends could register own health checks.

I was diving into this a little bit recently...  And it looks like the simplest thing to do would be to pass in custom status check logic in `src/plugins/healthcheck.ts`, like so:

```diff
diff --git a/packages/backend/src/plugins/healthcheck.ts b/packages/backend/src/plugins/healthcheck.ts
index 8ecae6be8..ab48716f0 100644
--- a/packages/backend/src/plugins/healthcheck.ts
+++ b/packages/backend/src/plugins/healthcheck.ts
@@ -21,5 +21,13 @@ import { PluginEnvironment } from '../types';
 export default async function createRouter({
   logger,
 }: PluginEnvironment): Promise<Router> {
-  return await createStatusCheckRouter({ logger, path: '/healthcheck' });
+  return await createStatusCheckRouter({
+    logger,
+    path: '/healthcheck',
+    statusCheck: () => {
+      return new Promise(() => {
+        // Custom status check logic here.
+      });
+    },
+  });
 }
```

The problem is that the types of stuff we might want to check (like the TechDocs publisher instance) are instantiated elsewhere and we don't have access to them here.

So we may want some other way to more easily compose health checks across multiple plugins in a single Backstage instance.

**Comment by iamEAP** [comment]
Noting thoughts from @freben [in discord](https://discord.com/channels/687207715902193673/687207715902193679/846413223845822475):

> I mean the health endpoint could be a class that accepts a number of () => Promise<boolean> callbacks and just runs them and also fails if they throw or something like that. But the value and structure added would be rather small on its own
>
> Things could be different if there were some inversion of control in place, where plugins are able to register themselves into an environment in several aspects in one single callback. But that kind of work is still TBD
>
> Ie, absent a more formal plugin system, this is likely staying as Just One More Thing to wire up manually (kinda bespoke)

...So I think we probably postpone this for now.
