### ISSUE TITLE
Issue with npx @backstage/create-app

### ISSUE THREAD

**Issue by damianesteban** [backstage/backstage#5384]
## Expected Behavior

A backstage app should be generated.

## Current Behavior

A vite app is generated.

## Steps to Reproduce

When I run the following:

```
npx @backstage/create-app
```

Here is what I see:

<img width="414" alt="Screenshot on 2021-04-19 at 20-43-29" src="https://user-images.githubusercontent.com/4554498/115320527-15cacd00-a150-11eb-89e4-a8bd64f7784d.png">

Based on the documentation from the Backstage site, this should create a Backstage application correct?

![Screenshot on 2021-04-19 at 20-45-04](https://user-images.githubusercontent.com/4554498/115320646-4448a800-a150-11eb-8df7-e9cdc2689704.png)

## Context

I recall several months ago there was a `create-app*` script that got a skeleton project up quickly.

## Your Environment

- NodeJS Version (v12): v14.15.1
- Operating System and Version (e.g. Ubuntu 14.04): macOS 11.2.2 (M1)
- Browser Information:

**Comment by adamdmharvey** [comment]
That is definitely not the output of `npx @backstage/create-app`. 😁  Hate to ask, and it's cutoff in your screen shot, but can you double check exactly what command you ran that triggered that list of sample React-type templates?

**Comment by OrkoHunter** [comment]
Yeah, looks like a [vite app](https://github.com/vitejs/vite/tree/main/packages/create-app#vitecreate-app) as you mention in the issue.

Strange that `npx @backstage/create-app` would do that - a screenshot with the command will help. :)

**Comment by damianesteban** [comment]
So I found out the issue, nothing to do with you and your team :).

For the past week I've been hacking away on Emacs eshell and was working on a plugin for "smart prediction" but apparently:

1. It isn't that smart.
2. It's not quite doing what I want to.

But I'll get there.

Thanks!

**Comment by damianesteban** [comment]
Ok so actually, I tried it again with my plain old zsh shell and get the following.

When I run it under nodejs v15:

<img width="1351" alt="Screenshot on 2021-04-20 at 22-38-25" src="https://user-images.githubusercontent.com/4554498/115488862-36b32100-a229-11eb-8519-3614b32d92d9.png">

When I switch back to nodejs v14 nvm nvm:

<img width="1090" alt="Screenshot on 2021-04-20 at 22-39-28" src="https://user-images.githubusercontent.com/4554498/115488935-53e7ef80-a229-11eb-9c06-06fd0487a1dd.png">

And then when I run it again:


<img width="732" alt="Screenshot on 2021-04-20 at 22-40-20" src="https://user-images.githubusercontent.com/4554498/115489013-75e17200-a229-11eb-900c-efd27e0703f8.png">

**Comment by damianesteban** [comment]
OK...super weird. I installed `@backstage/create-app` globally with npm and now it looks like it is successfully generating a project.

**Comment by OrkoHunter** [comment]
Cool! Closing as non-issue.

**Comment by brandonbloom** [comment]
I'm seeing this as well. Was very confused!
