### ISSUE TITLE
Plugin Feature Flag Feature Not Working as Documented

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#5394]
## Expected Behavior

The following should enable a Feature Flag and it currently doesn't:

```
import {
    createPlugin,
    createRoutableExtension,
    createRouteRef,
  } from '@backstage/core';
  import WelcomePageComponent from '../pages/WelcomePage';
  
  export const rootRouteRef = createRouteRef({
    title: 'Welcome',
  });
  
  export const welcomePlugin = createPlugin({
    id: 'welcome',
    register({ router, featureFlags }) {
      router.addRoute(rootRouteRef, WelcomePageComponent);
      featureFlags.register('enable-welcome-box');
    },
  });
```
When going to /settings/feature-flags i still see No Feature Flags

![image](https://user-images.githubusercontent.com/6157895/115430085-0e4c0800-a1d2-11eb-9c75-2879ad83f4b5.png)

**Comment by adamdmharvey** [comment]
This almost looks like the plugin isn't properly registered.  Assuming you created it with the `/welcome` route, does that route work as well in your instance? (thus proving it correctly registered?)

**Comment by regicsolutions** [comment]
Yep, the route works fine to /welcome. I ended up just adding the welcome plugin to the front end as suggested by others given its just a simple page.. 

Anything pop out at ya?

1. Add welcome.ts
```
//packages/app/src/plugins/welcome.ts
import {
    createPlugin,
    createRoutableExtension,
    createRouteRef,
  } from '@backstage/core';
  import WelcomePageComponent from '../pages/WelcomePage';
  
  export const rootRouteRef = createRouteRef({
    path: '/welcome',
    title: 'Welcome',
  });
  
  export const welcomePlugin = createPlugin({
    id: 'welcome',
    register({ router, featureFlags }) {
      router.addRoute(rootRouteRef, WelcomePageComponent);
      featureFlags.register('enable-welcome-box');
    },
  });
  
  export const WelcomePage = welcomePlugin.provide(
    createRoutableExtension({
      component: () => import('../pages/WelcomePage').then(m => m.default),
      mountPoint: rootRouteRef,
    }),
  );
```

2.  Added my WelcomePage to `packages/app/src/pages/WelcomePage.tsx` tested with the [out of the box page](https://github.com/backstage/backstage/blob/master/plugins/welcome/src/components/WelcomePage/WelcomePage.tsx)

3. Then added it to my App.tsx

```
//packages/app/src/App.tsx
import  WelcomePage from './pages/WelcomePage';

    <Route path="/explore" element={<ExplorePage />} />

```

**Comment by adamdmharvey** [comment]
That sample code may be old, and likely changed due to the composability work. You should no longer need to register the routes by using addRoute.

I have my own plugin called homepage, and I just tested adding a feature flag and it worked fine. I had to only add these three lines:

```diff
 export const homepagePlugin = createPlugin({
   id: 'homepage',
   routes: {
     root: rootRouteRef,
   },
+  register({featureFlags}) {
+    featureFlags.register('foo');
+  },
 });
```

Not sure if that helps?  But if you're using the old Welcome plugin, you may find you're better off doing a fresh `yarn backstage-cli create-plugin`, and replacing some of the components into a freshly provisioned one which will use the latest wiring?

**Comment by regicsolutions** [comment]
Thanks that helped!

**Comment by Rugvip** [comment]
Yeah feature flag API is a bit behind the composability work, iirc it's currently only possible to check if a flag is active via the API itself, meaning that you'll need to manually check the state of the flag and then not render the rest of the react tree within your own component. We definitely want to provide some more utilities to make feature flags easier to work with.

One idea is to just have a single `FeatureFlagged` component for use in the app, that'll both take care of acting as a switch but also register the feature flag. It would be implemented to work with the composability API, and simply act as a switch for whether its children should be renderer. Basically this:

```tsx
const routes = (
  <FlatRoutes>
...
    <FeatureFlagged flag="show-welcome-page">
      <Route path="/welcome" element={<WelcomePage />} />
    <FeatureFlagged>
...
  <FlatRoutes>
)
```

Where the `Route` works as expected, is discovered in the app etc, and the `"show-welcome-page"` flag is both automatically registered as well as used to toggle whether the welcome page should be renderer. I'm not sure if that exact implementation is possible, but something of that sort x)

This'd lift the feature flag registration from plugins to the app, which we can ofc debate a bit ;)

**Comment by augustomeireles05** [comment]
Hy there, Rugvip.
If it's possible, I would like to take some doubt with you: I need to know how to disable this option from the screen. 
I saw on core-plugin-api folder into node modules that exist a FeatureFlagState type where we can declare an attribute none  0. How to put in a component SidebarSettings to disable this element?
