### ISSUE TITLE
[RFC] New Home Page

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#5416]
**Status:** Open for comments

## Need

Right now when starting Backstage, the user enters the catalog. While the catalog contains a lot of stuff, it's probably not what a user is looking for when opening Backstage, in the end it's just *one* of Backstage's core features.

## Proposal

I propose to add a home page that has the same composability as the entity page. The home page is always in the view of a single team. As a user might be part of multiple teams, the page contains a switcher to choose another team (maybe even a team that the user is not part of). The last selected team is stored, so the page opens again in the previous state.

The home page can be used to show:
* Team KPIs, like vulnerabilities, runtime metrics, error rates, ... (but not on the component level, but aggregated)
* Owned entities
* Open PRs in related repositories
* Required actions, e.g. "Review the costs of project XYZ..."
* Activities in the context of the team
* News of the portal itself
* Starred entities
* ...

## Implementation

I propose to either make this part of the catalog, or as a new plugin called `home`. We can reuse most of the features that can be used to configure the entity page (like `EntityContext`, `EntitySwitch`, `useEntity`, ...). Instead of passing the current entity, we pass the entity of the selected team to each widget (`Entity*Card`). Widgets that already work in the context of a team can be reused here (like `OwnershipCard`), others can use the existing hooks to request all entities owned by the team. I would avoid passing all owned entities into the widgets, as widget might use more efficient ways to retrieve the required data.

The cool greetings feature could also be moved from the catalog page to the home page.

## Context

Here are some older screenshots with ideas for this page:

![image](https://user-images.githubusercontent.com/648527/115577876-0f119680-a2c5-11eb-9c1a-b682d96ee97d.png)

![image](https://user-images.githubusercontent.com/648527/115577889-1173f080-a2c5-11eb-9b9c-91c0c2c1c23d.png)

And [some thoughts](https://github.com/backstage/backstage/issues/2752#issuecomment-703681047) by @freben. Please comment with some more references if you know any!

## Alternatives

It is already possible for an integrator of Backstage to swap out the home page and place custom content there. But I think this could already be part of Backstage out of the box.

## Risks

There is already a group entity page so there could now be two places with the same content. But I think that the use-case is different. It's "What are the ownership and members of a team?" vs "What are my KPIs, status, and my ownership?". The home page would focus more on what is relevant for the team itself.

**Comment by adamdmharvey** [comment]
I'm right there with you!

Two key features:
* Update to sidenav separating home from catalog
* Dismissable intro card

I've created an internal `plugin-homepage` for exactly this purpose, and reworked the sidenav like so:

<img width="214" alt="image" src="https://user-images.githubusercontent.com/33203301/115590972-99df9a80-a29f-11eb-8f0f-3cd520f8ddb0.png">

Also, those I've shown my system to really question the value, even if the concepts of developer experience are well understood.  So ideally some intro card a user can hide after they know what it is. Tells the user what this Backstage or software catalog thing is, where to start or link out to get more info, possibly a few visually pleasing hero links for like creating a golden path component or seeing their data, that sort of thing.  But then let them hide it once Backstage is just their default homepage or their first thing after coffee in the morning.

**Comment by adamdmharvey** [comment]
Possibly also a built in announcements/news card?  May be relatively similar to the pulse card in the screen shot above, but something where the integrator could announce to the teams.  e.g., we still have some teams who do small code freezes, and would be nice to let leaders bubble those things up, or changes to tools that could be announced, and then quickly dismissed. (to be fair, that could be it's OWN plugin I guess!)

**Comment by timbonicus** [comment]
Thanks for creating the RFC to get the discussion going! This has been long-desired and is definitely something we have and appreciate internally at Spotify, as shown in the first screenshot. I've seen similar home pages from many companies mature in their Backstage adoption.

It makes sense to me as a separate (but included out of the box in `create-app`) plugin from the catalog. This can definitely benefit from the composability changes, since it should be flexible to add many different types of content from other (sometimes internal) plugins.

Some other minor inspiration; the [cost-insights plugin](https://github.com/backstage/backstage/tree/master/plugins/cost-insights) has a group switcher underneath the header that behaves as you describe:

![cost-insights-group-switcher](https://user-images.githubusercontent.com/556258/115591847-cee3f100-a28f-11eb-89b5-c1b6accaf88a.png)

I saw this [video from @dtuite](https://github.com/backstage/backstage/discussions/5401#discussioncomment-638486) showing dynamic addition of cards; supporting customizing and reorganizing the content of the home page could be a super cool long-term goal. An MVP that's only customizable by the Backstage administrator makes a lot of sense as a starting point, though.

**Comment by OrkoHunter** [comment]
Sharing here for reference https://youtu.be/UZTVjv-AvZA?t=1787 - @soapraj's demo on the new Backstage homepage inside Spotify during the Backstage Community Session on May 19th!

(It was a call out during the meetup to share when the recording is up 😁 )

**Comment by satrox28** [comment]
@OrkoHunter Thanks for sharing, Any ETA on when the new home page will be available on Opensource?.

**Comment by emmaindal** [comment]
Hey, our team will be working on parts of this during the summer so will assign it us for now and you will be able to track issues in a milestone sometime next week!

**Comment by rubenLindstrom** [comment]
Hello everyone! We have now opened up a PRFC (Pull Request For Comments) for this, which you can find [here](https://github.com/backstage/backstage/pull/6486). Looking forward to hearing all your suggestions!

**Comment by kiranpatel11** [comment]
Question: 
Will this be covering the _Welcome Experience_ for users login into platform for the first time ?
Bare Minimal would be the option to have **HomePage Sliders**, which can highlight key features...links to important docs, etc.

**Comment by rubenLindstrom** [comment]
> Question:
> Will this be covering the _Welcome Experience_ for users login into the platform for the first time ?
> Bare Minimal would be the option to have **HomePage Sliders**, which can highlight the key features...links to the important docs, etc.

Hi @kiranpatel11, thanks for your input! The scope of our current work is to create an easily composable home page. As soon as we're confident in the API, we'll begin looking at what components we can contribute with, and a _Welcome Experience_ component certainly makes sense from my perspective, although we do have some other ideas as well.

We hope to create a system where it will be easy for everyone to contribute with new components that can be integrated into any homepage!
