### ISSUE TITLE
GithubOrgReaderProcessor to support the GithubCredentialsProvider in the same way that the github processor does

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#5417]
The standard github processor supports configuring either a personal access token (PAT) or a github app to authenticate against the github APIs. 

The GithubOrgReaderProcessor (aka github-org) only supports a PAT.

## Feature Suggestion

It would be fantastic if the processor that handlers github-org locations could also support the ability to configure auth using a github app. See here https://backstage.io/docs/plugins/github-apps

## Context
I am collecting members and teams data from github and also collecting catalog files from github into my backstage instance. Today I use a personal access token (PAT) from github to configure the authentication for both. There are many advantages to using a github app for authenticating with github. As such I would like to move to using a github app instead of a PAT. I can configure backstage to use a github app to collect catalog yaml files, however I cannot do the same for the github-org locations.

**Comment by kuangp** [comment]
I implemented this support in a related feature PR: https://github.com/backstage/backstage/pull/5173
Depending on what feedback received there, it may be merged with the existing `GithubOrgReaderProcessor` to satisfy this request
