### ISSUE TITLE
Mismatching System Entity Directions

### ISSUE THREAD

**Issue by jrusso1020** [backstage/backstage#5420]
## Expected Behavior
Examples on https://backstage.io/docs/features/software-catalog/descriptor-format should match throughout the page.

## Current Behavior
Currently the entity component example towards the top of the page has `metadata.labels.system` set https://github.com/backstage/backstage/blame/master/docs/features/software-catalog/descriptor-format.md#L47 but further down on the page it's `spec.system` https://github.com/backstage/backstage/blame/master/docs/features/software-catalog/descriptor-format.md#L423. Which is the correct usage? 

## Possible Solution
Update the document to use the same example

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Context
Was following this documentation to prototype adding this functionality into our Backstage instance but ran across the discrepancy.

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by freben** [comment]
Oh, definitely in `spec`!

https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/BuiltinKindsEntityProcessor.ts#L171

Would you be up for submitting a fix?

**Comment by Fox32** [comment]
I think that example also shows that you can label things, back then the system example was probably good, but today it's confusing. I would vote for replacing it with another label example, but I can't come up with a nice idea...

**Comment by jrusso1020** [comment]
Yep, I can submit a fix today! @freben 

@Fox32 if you have a better example in mind after some thinking let me know

**Comment by jrusso1020** [comment]
https://github.com/backstage/backstage/pull/5432 PR up here, open to any suggestions

For now I just took an example of a label from https://github.com/backstage/backstage/blob/cbfa75bf69da90961daae517f28a106327ceb5d0/packages/catalog-model/src/entity/policies/SchemaValidEntityPolicy.test.ts#L36
