### ISSUE TITLE
Allow custom background images for TemplateCard

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#5426]
## Feature Suggestion

It should be possible to specify an alternative background image for the template cards on the new component page.

## Possible Implementation

Wrap the current image lookup in a hook, which would fall back to the existing implementation of finding the standard 'swooshy vector thing' from pageTheme. 

## Context

When you have a lot of templates of the same type, it can be hard to visually distinguish them at a glance. EG, we have a template for Ruby services, a couple for Golang ones etc. It would be nice to have a ruby for the Ruby template, and gophers for the Golang ones.

Of course, this may be a weird thing to solve for only this one component, so perhaps someone has a bigger and better idea for customising cards of this general sort.

**Comment by Rugvip** [comment]
Not sure if we want to head to this level of customization to be honest. What do you think about creating your own plugin that shows the templates, with whatever extra custom annotations or frontend logic that you need? You can still rely on the existing scaffolder plugin for actually executing the templates by linking to the template form page, assuming we add a route ref for that.

**Comment by msamad** [comment]
Hi, is there not a way to override or append to this list somehow?
https://github.com/backstage/backstage/blob/master/packages/theme/src/pageTheme.ts#L57

**Comment by Rugvip** [comment]
@msamad there is! https://backstage.io/docs/getting-started/app-custom-theme#creating-a-custom-theme

**Comment by msamad** [comment]
@Rugvip Thanks for that, will give that a try.

**Comment by freben** [comment]
We had [a brief discussion](https://discord.com/channels/687207715902193673/696709358544879716/874297979765399572) about this on Discord today as well, hinting that maybe we could add this under the `bursts` config.

I'll close this for now, since we have discussed both the option of making a custom page for it, or contributing a theme extension point for it. Feel free to reopen if this was too eagerly closed of me!
