### ISSUE TITLE
Support "owner" field for Template kinds

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#5440]
## Feature Suggestion

It would be nice to let Template entities be associated with an owner so that users/teams can track them along with the components they own or allow another consumer to look up the owner to report any issues with the scaffold.

## Possible Implementation

It was suggested by @Rugvip [here](https://discord.com/channels/687207715902193673/687235481154617364/834811545116082216) that "we'd need the `BuiltinKindsEntityProcessor` to add an owner relation as it does for the other entity kinds"
## Context

See above.

**Comment by Rugvip** [comment]
Yep we do indeed want this. The missing piece is to create the ownership relations when the field is present in the entity. It should be handled the same way as the other entity types and added here: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/BuiltinKindsEntityProcessor.ts

**Comment by freben** [comment]
@kuangp Is this something you would like to contribute? :)

**Comment by kuangp** [comment]
@freben sure I can take a stab at it

**Comment by freben** [comment]
Thanks, assigned!

**Comment by kuangp** [comment]
Closed via #5578
