### ISSUE TITLE
Expose user info for scaffold templates

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#5441]
## Feature Suggestion

When writing scaffolder templates, it would be useful to have some basic info about the user who triggered the job injected so it can be used when composing action steps. Some values to start with might be:
`{{ user.name }}`
`{{ user.username }}`
`{{ user.email }}`

## Possible Implementation

Not sure?

## Context

The same way we are able to grab the form  UI parameters with `{{ parameters.name }}` and action outputs with `{{ steps.publish.output.remoteUrl }}`, we would like to grab some basic user info to use as inputs to actions eg. setting the `input.access` to the users username for `publish:github`

**Comment by Rugvip** [comment]
Not sure what a possible implementation of this would be either at this point tbh, would need to brainstorm and explore it a bit more. One thing I can say is that I feels it's in the same problem space as forwarding generic access tokens to the actions as well. That piece is being discussed in #5214

**Comment by benjdlambert** [comment]
Related #6217

**Comment by kuangp** [comment]
still relevant

**Comment by tejaswivinodg** [comment]
> still relevant

@kuangp I'd like to know more about how you have implemented this. Thanks. I want to keep track of users who have triggered the job using templates.

**Comment by jrusso1020** [comment]
would it be worthwhile contributing the scaffolder field extension to the open source version? @kuangp we are also thinking about building this ourselves to get the current logged in user

**Comment by benjdlambert** [comment]
@jrusso1020 if you take a look at the `Get open scaffolder tasks` the user info doesn't require a new component :)

**Comment by peimanja** [comment]
still relevant

**Comment by Rugvip** [comment]
A different approach that we discussed briefly could be to move this to the backend instead. Thinking a custom action that uses either the Backstage token or other secrets to fetch user information, which can then be used in subsequent steps. Thinking something like `catalog:user-info`, `github:user-info`, or that kinda thing. Is someone that is looking at or already using the frontend workaround up for trying that out instead?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
@kuangp : How did you manage to integrate this piece, currently if I use the below code 

export const LoggedInUser = ({ onChange }: FieldProps<string>) => {
  const identityApi = useApi(identityApiRef);

  useAsync(async () => {
    const state = useAsync(() => identityApi.getProfileInfo(), [identityApi]);
    const email = state.value?.email;
    onChange(email);
  });

  return (<></>);
};

export const LoggedInUserFieldExtension = scaffolderPlugin.provide(createScaffolderFieldExtension({
  component: LoggedInUser,
  name: 'GetLoggedInUser',
}));

And use the following in the scaffolding template, it is blank

parameters:
    - title: Requesting User
      properties:
        requestingUser:
          title: User Requested
          type: string
          description: User Requesting
          ui:field: LoggedInUser
          readOnly: true

![image](https://user-images.githubusercontent.com/86959288/165102836-7efb233b-458d-4bf9-8cd2-6a0b752696d5.png)

**Comment by mustafazeya** [comment]
We are using Azure as an authentication provider but neither creating catalog users nor using discovery. I am wondering,is there any way we can fetch user's email from the authentication provider and use that to see who has created the template?

**Comment by benjdlambert** [comment]
I mentioned actually here: https://github.com/backstage/backstage/pull/11308#issuecomment-1149932486 that might be best off creating a `Custom Field Extension` that could use the `scmAuthApi` to get a token, and then make a request to the Azure API's to grab the profile or something instead. These docs should get you up and running: https://backstage.io/docs/features/software-templates/writing-custom-field-extensions

**Comment by benjdlambert** [comment]
Going to close this issue for now, as with #11994

**Comment by Vinesh9224** [comment]
Is there any active working solution for this issue?

**Comment by benjdlambert** [comment]
@Vinesh9224 it's been shipped already. I think these docs should help: https://backstage.io/docs/features/software-templates/writing-templates/#accessing-the-signed-in-users-details
