### ISSUE TITLE
Renamed or deleted entities not removed from catalog

### ISSUE THREAD

**Issue by erikxiv** [backstage/backstage#5442]
## Expected Behavior

1. When an entity is renamed by changing the `metadata.name` property in a registered `catalog-info.yaml` file, the existing entity is renamed
2. When an entity is removed by removing the reference in a registered location file, the existing entity is removed

## Current Behavior

in both cases above, the existing entity still exists in the catalog (database) after the ingestion loop has finished. In the renaming case a new entity with the new name has been added. It is also not possible to, via the UI, remove only the old/renamed entry without also remove the new entry, requiring the entity to be re-registered.

This seems like a known issue, and it seems that the area is currently being refactored, but I thought it might be worth having an issue to list/monitor that this currently doesn't work as I would expect

## Possible Solution

* In the ingestion loop, compare the existing list of entities in the database with the newly generated list of entities and delete the missing ones from the database
* See @freben comment: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts#L85

## Steps to Reproduce

See description in expected behaviour section above.

## Context

* In our environment we auto-generate a fairly large amount of entities from an external source and then use a location entity to assist Backstage to consume the generated yaml-files. With the bug, we need to periodically delete all entities in the database from this location to prune orphaned/deleted entities.
* Authors get confused when they rename entities and they end up with duplicate entries. Deleting the duplicate entry via the UI causes both entries to be removed from the catalog.

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by dtuite** [comment]
This appears to be a duplicate of https://github.com/backstage/backstage/issues/3750 (albeit with a much more thorough description 😄 )

**Comment by erikxiv** [comment]
Great! I was a bit confused that I didn't find an issue about it, but apparently I just need to work no my google-fu a bit. Thank you!

**Comment by freben** [comment]
Also, this is what we're literally this minute working on - look forward to improvements! :)
