### ISSUE TITLE
Small font-size for TechDocs admonitions

### ISSUE THREAD

**Issue by WillSewell** [backstage/backstage#5448]
The `admonition` CSS class assigns `font-size: .64rem`, which is much smaller than other text sizes on backstage page.

<img width="932" alt="Screenshot 2021-04-23 at 09 59 05" src="https://user-images.githubusercontent.com/1119785/115847647-11860480-a41b-11eb-9366-565d2b465dc4.png">

This issue was fixed for tables in https://github.com/backstage/backstage/pull/5281.

## Current Behavior

Font size should be the same as the default.

## Possible Solution

Inspiration could be taken from the fix to tables in https://github.com/backstage/backstage/pull/5281.

## Steps to Reproduce

1. Render https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/examples/documented-component/docs/extensions.md#admonitions
2. View generated HTML

## Your Environment

```
@backstage/plugin-techdocs-backend: 0.7.1
@backstage/plugin-techdocs: 0.7.2
@backstage/techdocs-common: 0.5.0
```

**Comment by Crevil** [comment]
I'd like to take a stab on this.
