### ISSUE TITLE
How do we get access token when authenticating using Auth0 or Okta (Help needed)

### ISSUE THREAD

**Issue by maha-z** [backstage/backstage#5470]
I tried setting up Auth0 and Okta for auth. I am unable to figure out how to fetch tokens post authentication. Could you please help me out. 

Actually we wanted to show backstage components based on the user scope and roles. I have set my scopes in auth0 and okta. Facing issue on how to fetch scopes post authentication

## Expected Behavior
Get access token and scopes post authentication

**Comment by Rugvip** [comment]
Simply call `getAccessToken` on the appropriate auth API! For example like this: https://github.com/backstage/backstage/blob/61fdfd70a3d29d4588144159e43f64572bcc743b/plugins/github-deployments/src/api/index.ts#L92

**Comment by freben** [comment]
Closing as probably solved - please reopen and clarify if this is a mistake on my part.
