### ISSUE TITLE
Getting error when creating template while running backstage application in docker

### ISSUE THREAD

**Issue by maha-z** [backstage/backstage#5471]
Tried to run backstage application in docker following the docs page. Getting error while creating from template when running the application in docker. 
 
[Screenshot from 2021-04-26 12-31-45](https://user-images.githubusercontent.com/49862228/116041997-89f2fc80-a68b-11eb-9591-c30408ce279c.png)

## Expected Behavior![Screenshot from 2021-04-26 12-31-45](https://user-images.githubusercontent.com/49862228/116041997-89f2fc80-a68b-11eb-9591-c30408ce279c.png)

Template should have been created in the specified github repository.

## Current Behavior

Currently getting error like "A valid repository /input could not be found in the following locations

## Steps to Reproduce

1. Create a multi stage dockerfile as per the [docs](https://backstage.io/docs/deployment/docker#multi-stage-build) 
2. Click on create new component and choose a template and choose a template
3. Fill in all the required fields in the form
4. Now click on create to see the error

**Comment by OrkoHunter** [comment]
Since you have used Docker to deploy your Backstage app, make sure to install [Cookiecutter](https://github.com/cookiecutter/cookiecutter) inside the container as well. It's currently using Docker inside docker which is not preferable. https://backstage.io/docs/features/software-templates/installation#disabling-docker-in-docker-situation-optional

**Comment by maha-z** [comment]
@OrkoHunter do we need to install cookie cutter globally or how do we install the cookiecutter?

**Comment by adamdmharvey** [comment]
Sidebar: wonder if this should spin out into a way to output an improved error msg that might be a bit more friendly, almost like a "I wonder if you are using Docker-in-Docker; see this documentation for how to..." blah blah.  Or trapping a particular error response we know always means it's this issue.

**Comment by OrkoHunter** [comment]
@maha-z Well, this is partially my fault and partially the README of [Cookiecutter](https://github.com/cookiecutter/cookiecutter) for not writing 

```
pip install cookiecutter
```

explicitly. I suspect that you installed cookiecutter using npm/yarn, which is totally another package.

[This Dockerfile](https://github.com/backstage/backstage/blob/cbfa75bf69da90961daae517f28a106327ceb5d0/contrib/docker/kubernetes-example-backend/Dockerfile) is a good example you can reference to update your Docker container.

**Comment by maha-z** [comment]
@OrkoHunter post cookie cutter installation at publish step I am getting the following error
![Screenshot from 2021-04-27 13-09-44](https://user-images.githubusercontent.com/49862228/116204184-21bf1c00-a75a-11eb-8d65-b042de29f778.png)

**Comment by timbonicus** [comment]
That seems to be #5488, an unfortunately timed but unrelated issue.

**Comment by freben** [comment]
@maha-z I believe that what you saw was indeed fixed since then, and has now also been released. Closing the issue for now, but absolutely do not hesitate to reopen it if the problem persists
