### ISSUE TITLE
TechDocs cache invalidation to check timestamp of only commits affecting documentation directory.

### ISSUE THREAD

**Issue by adrianke77** [backstage/backstage#5472]
## Feature Suggestion

it seems that in packages/techdocs-common/src/stages/prepare/dir.ts DirectoryPreparer, the check for cache invalidation only checks the timestamp on the last commit of a repo. But the last commit is not necessarily the timestamp of last documentation change of the docs in question, and is even unlikely to be so if the repo is a monorepo or has active code changes all the time.

## Possible Implementation

Perhaps we can change 'getLastCommitTimestamp' to 'getLastDocsCommitTimestamp' and use something like 'git log -1 {folder path containing catalog yaml file}' (or equivalent isomorphic-git method and arguments) for last commit timestamp that modified anything in the docs folder, to avoid unneeded rebuilds. 
-Edit: getLastCommitTimestamp is not in use for annotations specified using `url:` (UrlReader)

This might be computationally quite expensive but it seems unavoidable that this or a similar check needs to be done. Restricting the check to once per attempt to read the docs might be acceptable? 

## Context

With the current 'async build while viewing docs' setup:
1) the note on the TechDocs Reader page that a newer version of docs is being built both shows too frequently and is also not often actually true 
2) backend has unnecessary rebuild runs on any code changes in the source repo.

Hopefully this resolves the above.

**Comment by adrianke77** [comment]
A little stuck. So turns out the current way Backstage retrieves raw TechDocs from, to take an example, Gitlab is by the Gitlab API for retrieve single branch: `https://docs.gitlab.com/ee/api/branches.html#get-single-repository-branch`  And the last commit date for the whole branch comes in the response there. But there seems to be no other API to obtain 'last commit that affect this subdirectory'. 

It seems that in order to get this information, we would need to git clone the directory first so that a git log or other equivalent would work. Which would be reverting to the legacy Git preparer's approach that also results in slower file copying...

**Comment by adrianke77** [comment]
Turns out Gitlab api allows passing a path to a commits endpoint request, so with a path to a docs folder, should give an appropriate commit with the timestamp for last docs change.

**Comment by dhenneke** [comment]
But is the timestamp of the `docs/` folder enough? There is also the `mkdocs.yml` that is not part of the `docs/` folder but will probably most commonly stored in the repository root. Sure, the probability that someone changes _only_ the `mkdocs.yml`, might be low, but I wouldn't want to exclude it from the up-to-date checking.

**Comment by adrianke77** [comment]
I meant by docs folder the folder including the mkdocs.yml and the /docs folder as well, i.e. the folder specified by the annotation to be containing mkdocs.yml

**Comment by adrianke77** [comment]
Created PR for https://github.com/backstage/backstage/pull/5599 for the Gitlab case (I'm not sure I can parse the Github equivalent correctly, and I don't have an instance of the other Git storage solutions to test with).
