### ISSUE TITLE
Make it possible to fetch all related entities in a single request

### ISSUE THREAD

**Issue by WillSewell** [backstage/backstage#5475]
## Feature Suggestion

Currently, fetching related entities is inefficient because a request is made to the backend for each relation.

This TODO

https://github.com/backstage/backstage/blob/769112c63ce587e521a144e2e3564d848a400268/plugins/catalog-react/src/hooks/useRelatedEntities.ts#L43-L46

by @Fox32 lists a couple of potential solutions to this. I wanted to create this issue to encourage further discussion around the approach to take.

## Possible Implementation

There are some possible solutions mentioned in the linked TODO.

## Context

We're using `useRelatedEntities`, but the number of returned entities can be >1k. This currently leads to >1k requests to the backend, which is slow and can lead to failed requests in Chrome.

**Comment by WillSewell** [comment]
I just found a more specific issue related to one of the possible solutions: https://github.com/backstage/backstage/issues/4499.

**Comment by Rugvip** [comment]
Tbh I think #4499 covers this and we could probably close this one as a duplicate to focus the discussion there

**Comment by WillSewell** [comment]
In the short term I actually think the approach of doing a "batch request" could be a quick win. The `/catalog/entities` endpoint [already permits entities to be filtered by name](https://github.com/backstage/backstage/blob/f9d077f5f6c3bf1e20255359798dd1febbeb3e27/plugins/catalog-backend/src/database/types.ts#L129-L131).`useRelatedEntities` could be updated to pass in the names of each related entity using the `filter` param.

The downside of this approach is it would lead to a very large query string, but I think this would still be a lot more efficient than making a request for each related entity.

Unfortunately this approach is not currently possible due to a small limitation on the client, which I attempted to resolve in https://github.com/backstage/backstage/pull/5493.

**Comment by freben** [comment]
> The downside of this approach is it could lead to a very large query string if there are a lot of related entities. However, I think this would still be a lot more efficient than making a request for each related entity.

(sorry for accidentally editing your comment -_-)

Could still batch get like a hundred of them at a time or so.

**Comment by WillSewell** [comment]
Yes good point. I've already inlined `useRelatedEntities` and updated it to function in this way, so I'd be happy to add this functionality to the code in backstage once https://github.com/backstage/backstage/pull/5493 is merged.

**Comment by freben** [comment]
That one is now merged! It was not in before today's release though.

**Comment by freben** [comment]
Should we close this issue? Or do we keep it alive until `useRelatedEntities` has been fixed accordingly?

**Comment by WillSewell** [comment]
Keep it alive until `useRelatedEntities` is making use of it? I'm going to have a go at it next week
