### ISSUE TITLE
core: add a FeatureFlagged component

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#5480]
Giving this a new home since https://github.com/backstage/backstage/issues/5394 is closed :grin:

## Feature Suggestion

Looking for feedback on the idea to add a single `FeatureFlagged` component for use in the app, that'll both take care of acting as a switch but also register the feature flag. It would be implemented to work with the composability API, and simply act as a switch for whether its children should be renderer. Basically this:

```tsx
const routes = (
  <FlatRoutes>
...
    <FeatureFlagged flag="show-welcome-page">
      <Route path="/welcome" element={<WelcomePage />} />
    <FeatureFlagged>
...
  <FlatRoutes>
)
```

Where the `Route` works as expected, is discovered in the app etc, and the `"show-welcome-page"` flag is both automatically registered as well as used to toggle whether the welcome page should be renderer. I'm not sure if that exact implementation is possible, but something of that sort x)

This'd lift the feature flag registration from plugins to the app, which we can ofc debate a bit ;)

## Possible Implementation

TBD, looking at the idea first x)

## Context

https://github.com/backstage/backstage/issues/5394

**Comment by ljupchokotev** [comment]
I was using `featureFlagsApiRef` to conditionally render a tab on the service/website entity page which is not possible to do anymore with the new composability changes. Since the `serviceEntityPage` and `websiteEntityPage` are not components anymore, there is no way to make use of the API to do this.

Your proposal will work for my usecase, so :+1: !

**Comment by regicsolutions** [comment]
Love the idea!!!

**Comment by sbrnunes** [comment]
I was trying that approach, to hide the tabs that we still do not support, but this fails with `Child of EntityLayout must be an EntityLayout.Route`:
```
<EntityLayout>
   ...
   <FeatureToggled name="toggle">
      <EntityLayout.Route path="/ci-cd" title="CI/CD">
          {cicdContent}
      </EntityLayout.Route>
   </FeatureToggled>
   ...
</EntityLayout>
```
Any idea how to get around this?

**Comment by benjdlambert** [comment]
@sbrnunes yep that's another use case of the feature that is being suggested part of this ticket. I would assume that it would be compatible for both uses :)

**Comment by ryanvazquez** [comment]
@sbrnunes Unfortunately not without modifying `EntityLayout`. 

The initial approach seems to break down whenever there is a tight coupling between the parent component and child. The parent expects a direct child of a certain kind with specific props, doesn't find them/recognize the intermediary FeatureFlagged component, and fails.

This can be circumvented by modifying the parent to be feature flag aware. For example, in `EntityLayout`
```ts
function createSubRoutesFromChildren(
  childrenProps: React.ReactNode,
  entity: Entity | undefined,
): SubRoute[] {
  // Directly comparing child.type with Route will not work with in
  // combination with react-hot-loader in storybook
  // https://github.com/gaearon/react-hot-loader/issues/304
  const routeType = (
    <Route path="" title="">
      <div />
    </Route>
  ).type;

  return Children.toArray(childrenProps).flatMap(child => {
    if (!isValidElement(child)) {
      return [];
    }

    if (child.type === Fragment) {
      return createSubRoutesFromChildren(child.props.children, entity);
    }

    if (child.type.displayName === 'FeatureFlagged') { // some arbitrarily named component
      return createSubRoutesFromChildren(child.props.children, entity);
    }

    if (child.type !== routeType) {
      throw new Error('Child of EntityLayout must be an EntityLayout.Route');
    }

    const { path, title, children, if: condition, tabProps } = child.props;
    if (condition && entity && !condition(entity)) {
      return [];
    }

    return [{ path, title, children, tabProps }];
  });
}
```
Couple drawbacks with this approach though:

1. `EntityLayout`, `FlatRoutes`, etc. - every parent component of this type needs to be modified to be feature flag aware. 

2. May not play nice with third party libs with similar parent/child API.

3. Semi-inconsistent state. In the above example, the parent registers the subroutes of the child regardless of the state of the flag (which arguably may be necessary to allow the user to toggle the feature freely without breaking the app). This introduces inconsistency between enabled/disabled states which could lead to bugs.

4. Users might want more control than just rendering a child or not. Likely want the ability to render a default component if the flag is disabled.

**Comment by Rugvip** [comment]
A possible approach would be to standardize the child element collection functions added in https://github.com/backstage/backstage/pull/5677. If the collection function(s) end up being provided by the core library, we can have it stop depth traversal if it encounters a `FeatureFlagged` element with a flag that isn't set. It's a pretty deep integration but could potentially be worth it

**Comment by nqkdev** [comment]
Using `FeatureFlagged` does not automatically register the flag as proposed. @Rugvip Was there any reason to drop this functionality? 😄
