### ISSUE TITLE
Unable to instantiate from a template after migrating to github apps for backend authentication

### ISSUE THREAD

**Issue by Pranava29** [backstage/backstage#5488]
## Expected Behavior
I should continue to be able to create the template in the target repository using  github apps for backend authentication.

## Current Behavior
Im getting the following error in the **Publish** phase. - 
```
The visibility parameter is valid only when the nebula-preview header is provided.
```
PFA
![Screenshot from 2021-04-27 12-26-03](https://user-images.githubusercontent.com/10139286/116198803-08b36c80-a754-11eb-91fc-c44cb53a6090.png)

## Possible Solution
-

## Steps to Reproduce
1. Setup github apps by following the instrcutions documented [here](https://backstage.io/docs/plugins/github-apps)
2. Give permissions to the app to create/manage repos in your github org settings. https://github.com/organizations/<org-name>/settings/apps/<app-name>/permissions)

## Context
-

## Your Environment
- NodeJS Version: v14.16.0
- Operating System and Version: Ubuntu 20.04
- Browser Information: Google Chrome Version 90.0.4430.72 (Official Build) (64-bit)

**Comment by jh-sh** [comment]
Same error here but without setting up an github app.
We use Azure AD auth, & GH PAT only.

**Comment by Pranava29** [comment]
Thanks @freben

**Comment by banshee86vr** [comment]
I'm still facing this error using the docker image backed for the backend with this Dockerfile (starting from  main branch):

```
FROM node:14-buster

WORKDIR /usr/src/app

# (workaround) Install cookiecutter and mkdocs to avoid the need to run docker in docker
RUN cd /tmp && curl -O https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tar.xz && \
    tar -xvf Python-3.8.2.tar.xz && \
    cd Python-3.8.2 && \
    ./configure --enable-optimizations && \
    make -j 4 && \
    make altinstall

RUN apt update
RUN apt install -y mkdocs

RUN pip3.8 install mkdocs-techdocs-core

RUN pip3.8 install cookiecutter && \
    apt remove -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev libbz2-dev g++ python-pip python-dev && \
    rm -rf /var/cache/apt/* /tmp/Python-3.8.2

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
ADD yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./

RUN yarn install --frozen-lockfile --production

# This will copy the contents of the dist-workspace when running the build-image command.
# Do not use this Dockerfile outside of that command, as it will copy in the source code instead.
COPY . .

CMD ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.development.yaml"]
```

Someone have already tried to instantiate a component from a template using the backend from a docker image with cookiecutter? What Dockerfile are you using?

STEPS TO REPRODUCE:

1. Clone backstage repo (`main` branch)
2. Change Dockerfile in `packages/backend/Dockerfile` with the content above
3. Instantiate a component from a template
