### ISSUE TITLE
[Search] Add a dropdown that exports search results

### ISSUE THREAD

**Issue by GaboFrontDev** [backstage/backstage#5499]
## Feature Suggestion
Add a dropdown that exports search results into a .csv or a .xls file. 
In Expedia Group we want to contribute to the search milestone with this feature. Actually, we got the results and display a dropdown where we pick up our desire extension.

## Possible Implementation

Here we have some screenshots of our export feature

this is how the search with dropdown view looks
![image](https://user-images.githubusercontent.com/39060802/116305291-2dfea580-a769-11eb-806b-20c259c167f0.png)

click event 
![image](https://user-images.githubusercontent.com/39060802/116305386-54244580-a769-11eb-94d0-ed3b271c5c3c.png)

after clicking on the extension desired, it will download the file with the desired extension. In this case, I have selected both extensions at different times
![image](https://user-images.githubusercontent.com/39060802/116307154-951d5980-a76b-11eb-92f2-7087758280e2.png)

and the results on an XLS file
![image](https://user-images.githubusercontent.com/39060802/116305626-a4030c80-a769-11eb-9add-d21ff7a80355.png)

## Context
We at Expedia have created an Export Button and we’d like to contribute it to Backstage Search.

**Comment by freben** [comment]
Nice. Does it effectively export only visible items on the screen, or can it go beyond that?

On the topic of design, this is probably not a super common thing to want to do, and I think it could be collapsed into a smaller button than this - perhaps in the table, as one of the top-row action buttons?

**Comment by GaboFrontDev** [comment]
Hi @freben!
> Nice. Does it effectively export only visible items on the screen, or can it go beyond that?
It exports all the search results even if those are paginated in thousands!

> On the topic of design, this is probably not a super common thing to want to do, and I think it could be collapsed into a smaller button than this - perhaps in the table, as one of the top-row action buttons?
the design isn't locked to one specific component. We can explore possible designs options

**Comment by freben** [comment]
Cool. Let us know if we can be of assistance somehow.

**Comment by GaboFrontDev** [comment]
@freben can you assign me this issue? It would be helpful!

**Comment by freben** [comment]
Sure!

**Comment by GaboFrontDev** [comment]
Just made a PR 😄
