### ISSUE TITLE
[TechDocs] Inline-comment format feedback

### ISSUE THREAD

**Issue by adrianke77** [backstage/backstage#5502]
## Feature Suggestion/Context

Our users have highlighted they would like to be able to leave feedback comments on specific lines of a TechDocs page.

## Possible Implementation

It seems that it would be difficult to use Git issues to handle line-specific feedback as identifying the specific line would be difficult. Unless there is some way to link to the exact section that was commented on from the issue created? 

Assuming that TechDocs would have to track and store comments, there may need to be a database that tracks 1) start and end character in the document 2) the string actually highlighted, for possible use in positioning the comment and 3) a string that is input as the comment. The UI could default to not showing comments unless they are turned on. 

A possible implementation could be like Discord message input where highlighting some text and releasing the mouse button pops up a context menu; in our case it could have a button for Add Feedback. It might be difficult to calculate which piece of text in the overall post-transform HTML was highlighted.

A problem might be with mapping comment positions with the post-transform document. Using character position from the start of the document would work but the position would become inaccurate with small changes to the transform functions. We could have a system where it uses relative start/end from doc start, then attempts to match the string nearby, and if still not matchable, simply apply the relative position directly

Very open to suggestions, and also information about why/how inline comments in the the current Spotify documentation reader is implemented would probably be very useful here.

**Comment by iamEAP** [comment]
Hey @adrianke77!  Thanks for opening this up.

> A possible implementation could be like Discord message input where highlighting some text and releasing the mouse button pops up a context menu; in our case it could have a button for Add Feedback. It might be difficult to calculate which piece of text in the overall post-transform HTML was highlighted.

I can confirm the implementation currently (internally) at Spotify is quite similar to this.  We side-step a lot of the complexities you highlighted by just stuffing the highlighted text into the issue template without specific reference to a line of code (just a quote with the highlighted text + reference to the markdown file):

![how-spotify-does-it](https://user-images.githubusercontent.com/3496491/119368695-a0ed3480-bcb3-11eb-959c-edb8d6826dee.gif)
