### ISSUE TITLE
pagerduty: Add screenshots to documentation

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#5510]
## Summary

It would be great to add some screenshots of the current PagerDuty plugin to its README here:

https://github.com/backstage/backstage/blob/master/plugins/pagerduty/README.md

Specifically, it says it has three features.  Would be awesome to have one screen shot of each to better understand how it can be used.

**Comment by adamdmharvey** [comment]
Just tagging a few people who I believe may be users of this tool or know how it works, and might have more ability than others to add some sample screen shots?  Clearly, keeping them up to date is tricky, but I was looking to understand more about the capabilities and screen shots would be amazing!

cc @joaomilho @grantila @samiramkr

**Comment by jamesrenaud** [comment]
Just in case anyone is watching this issue, I've created PR #6262 with some screenshots.
