### ISSUE TITLE
Better implementation docs for Tech Radar plug-in

### ISSUE THREAD

**Issue by ericis** [backstage/backstage#5513]
## Feature Suggestion

The [current "Getting Started" instructions](https://github.com/backstage/backstage/tree/master/plugins/tech-radar#getting-started) suggest...

- "...you can set a variety of configuration directly in your apis.ts", but never give any advice for how to configure "packages/app/src/apis.ts"
- Talks about configuring routes with `<TechRadarRouter ...` while the default app template actually defines the route with `<TechRadarPage ...` instead
- It briefly shows a specification of `TechRadarPageProps`, which could be used to configure the route's `<TechRadarPage ...`, including the `getData()` function, but without an example. Later, in the FAQ, it indirectly explains ["How do I load in my own data"](https://github.com/backstage/backstage/tree/master/plugins/tech-radar#how-do-i-load-in-my-own-data) and talks about the "getData()" function, but instead references the `<TechRadarComponent  ...` (which is yet another component that is neither the `<TechRadarRouter ...` or `<TechRadarPage ...` mentioned earlier.)

## Possible Implementation

Clean up component references and examples. Relate the documentation to how the Backstage app template sets things up initially.

**Comment by freben** [comment]
Hi! Made a PR to address most of it, give it a look. I left out part of the potential confusion on the last point, at least it now doesn't talk about `TechRadarRouter` which indeed was wrong and confusing
