### ISSUE TITLE
yarn build does not have --lax option exposed

### ISSUE THREAD

**Issue by heatheralee** [backstage/backstage#5520]
## Expected Behavior

We have the `--lax` option available for both `config:print` and `config:check` CLI commands as a result of fixing [this issue](https://github.com/backstage/backstage/issues/3922). `yarn build` is experiencing something similar where it does not interpret dynamic fields such as environment variables as a valid value. 

I would expect that the --lax option is also available during `yarn build` so that we can still maintain validation during run time, while avoiding throwing config errors like:
```
Config should have required property 'myProperty' { missingProperty=myProperty }
``` 
during `yarn build`.

## Current Behavior

Currently, if I build a Dockerfile on my local instance, errors are currently thrown for missing properties, where these properties are an environment variable which is later defined during run time on the server where the Docker image is deployed.

## Possible Solution

Add the `--lax` option to `app:build` command in commands/index.ts. Also update `build.ts` to include `mockEnv: cmd.lax`.

## Steps to Reproduce

1. Add a custom plugin which has configSchema defined in its package.json, where the schema file refers to an environment variable.
2. Run `yarn build` and note that there is an error thrown similar to:
```
Config should have required property 'myProperty' { missingProperty=myProperty }
``` 

## Context

This issue makes it tougher to create a Docker image where the environment variables might be defined later on the server where the Docker image will run. While a simple workaround would be to set placeholder values for each env variable before building the Docker image, it's easier with a `--lax` option. Then, if a user wants to skip this, they can add `--lax` to their package.json `build` script.

## Your Environment

- NodeJS Version (v12): v12.19.0
- Operating System and Version (e.g. Ubuntu 14.04): macOS Catalina 10.15.7
- Browser Information: Chrome

**Comment by Rugvip** [comment]
Could you share a bit more about how you end up hitting this issue? Generally frontend configuration is often not configured through env vars, and if it is it is often required at build time.

**Comment by heatheralee** [comment]
> Could you share a bit more about how you end up hitting this issue? Generally frontend configuration is often not configured through env vars, and if it is it is often required at build time.

Hi @Rugvip! Yes, [here is an example of an environment variable which we configure in our app-config.yaml](https://github.com/backstage/backstage/pull/5498/files), but throws an error:
```
Config should have required property 'eventsRestEndpoint' { missingProperty=eventsRestEndpoint } at /splunkOnCall
```
when we run `yarn build`.

Ideally, we would want to be able to build the Docker image without `eventsRestEndpoint` defined at this point in time, and define this variable later on down the line (and possibly re-use the image while switching out the eventsRestEndpoint for sandbox versus production). 

Happy to elaborate more about this if you have any more questions! Thanks in advance.
