### ISSUE TITLE
Build docker image using cloud native buildpacks

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#5530]
## Feature Suggestion

Provide **_source to image_** experience using Cloud native buildpacks. (https://buildpacks.io/)

## Possible Implementation

Produce docker image using opinionated buildpack and have less/no reliance on end-user to know docker best-practices.

## Context

Buildpacks for building backstage docker image with best practices (https://buildpacks.io/features/) 
Consider dependent software packages required for some of the plugins - cookiecutter for scaffolder, mkdocs for techdocs, etc.

**Comment by freben** [comment]
Sounds interesting. What is the main benefit to Backstage adopters as you would see it? To not have to set up their environments with Node etc?

One caveat we've seen is that the build times are significantly worse in Docker than on the host.

**Comment by freben** [comment]
Initial gut feeling I have, is that this could be a good fit for the contrib folder, to be used as an opt-in for those that want it, rather than making it a default blessed path. Any other opinions?

**Comment by kiranpatel11** [comment]
yes @freben, its a candidate for contrib folder and should be opt-in.

Main benefits is less reliance on developer to write optimize dockerfile, there are best practices such as running container as non-root, multi-stage docker image, etc are not straightforward to get it right for all developers.

Also buildpacks makes it easy to rebase images without needing to rebuild them, if there is change in base layers/image.

**Comment by lmasiero** [comment]
bump
