### ISSUE TITLE
techdocs - font size too small for note\attention...

### ISSUE THREAD

**Issue by falconbin** [backstage/backstage#5541]
font size within note\attention is 10.24px which is too small.

## Expected Behavior
font size should be 12.8px which is same as mkdocs.
![image](https://user-images.githubusercontent.com/20329141/116662365-44ef0300-a9c8-11eb-98b6-6f85ec97849d.png)

## Current Behavior
font size is 10.24px
![image](https://user-images.githubusercontent.com/20329141/116662231-1709be80-a9c8-11eb-9b2a-215f63e5f51c.png)

## Possible Solution
inject style to make font size bigger,  add following code to https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/components/Reader.tsx
![image](https://user-images.githubusercontent.com/20329141/116663412-a663a180-a9c9-11eb-8c37-c83ca5f11ae7.png)

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by falconbin** [comment]
font size within mkdocs note is 12.8px, but in techdocs it's 10.24px, the reason is that in mkdocs, the root font size is 20px, so the note font size is 20px*0.64 = 12.8px, but in techdocs, the root font size is default 16px, so the note font size is 16px*0.64=10.24px, if we change the relative size to 0.8rem, then the note font size(16px*0.8=12.8px) is same as techdocs.

**Comment by adamdmharvey** [comment]
May duplicate #5448

**Comment by Crevil** [comment]
We can close this as well as a fix has been released in #5778
@freben

**Comment by freben** [comment]
Ok!
