### ISSUE TITLE
[RFC] Increase the `metadata.name` character limit

### ISSUE THREAD

**Issue by WillSewell** [backstage/backstage#5543]
**Status:** Open for comments

## Need

We have existing components whose names exceed [the 63 character limit](https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md#name).

## Proposal

Make the limit configurable.

## Alternatives

* Hard code the limit to something higher
* We could work around outside the issue outside of Backstage
  * Rename our components, or
  * Fork the catalog plugin and adjust the limit

## Risks

Currently the spec is inspired by Kubernetes manifests (which limit the name to 63 chars). Using a well known spec avoids needing to re-invent one. Diverging from this well-known loses this benefit.

**Comment by freben** [comment]
This is actually possible!

Pass [custom validators](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/CatalogBuilder.ts#L177) to the catalog builder in [your backend setup](https://github.com/backstage/backstage/blob/master/packages/backend/src/plugins/catalog.ts#L56). Construct them easily from the baseline by only [overriding the specifics that you care about](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/validation/makeValidator.ts#L33).

**Comment by WillSewell** [comment]
Ah, thank you!
