### ISSUE TITLE
GitHub Discovery for non-organizations

### ISSUE THREAD

**Issue by simonknittel** [backstage/backstage#5544]
## Feature Suggestion

I'm using Backstage only for my personal projects and therefore don't have a GitHub Organization. While experimenting with the [GitHub Discovery feature](https://backstage.io/docs/integrations/github/discovery) I noticed that it can only discover repositories within organization accounts because of the use of the [`organization` GraphQL endpoint in the catalog-backend](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/github/github.ts#L232). It would be nice if you could also discover repositories of non-organizationss.

```graphql
  organization(login: $org) {
    name
    repositories(first: 100, after: $cursor) {
      nodes {
        name
        url
        isArchived
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
```

## Possible Implementation

Since there is a similar endpoint available for _normal_ accounts, it's maybe not hard to add this feature.

```graphql
user(login: "simonknittel") {
  repositories(first: 100) {
    nodes {
      name
      url
      isArchived
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```

**Comment by freben** [comment]
Oh I was under the impression that the personal ones were also returned by the current query. Did you double check that it didn't have anything to do with permissions?

We'd of course welcome a contribution. Is this something you'd like to look into?

**Comment by simonknittel** [comment]
I've given my personal access token every possible scope and it still returns the error `GraphqlError: Could not resolve to an Organization with the login of 'simonknittel'.`. Even with GitHub's own [GraphQL Explorer](https://docs.github.com/en/graphql/overview/explorer) I'm getting the same error message. So yeah, seems like it's not possible with that endpoint.

@freben Sure, I can look into it. However, I'm not sure what the best way to do it would be. Just request the organization endpoint first and if that fails try the user endpoint... or maybe some additional property for the app-config.yml? Something like
```yaml
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
      organization: true
```

**Comment by simonknittel** [comment]
@freben I've created a (draft) Pull Request: https://github.com/backstage/backstage/pull/5547 Since I'm not sure if that's the best way to solve this, maybe you could take a look before I go ahead and add changeset+tests.
