### ISSUE TITLE
Authentication provider for Cloudflare Access

### ISSUE THREAD

**Issue by simonknittel** [backstage/backstage#5564]
## Feature Suggestion

[Cloudflare Access](https://www.cloudflare.com/en-gb/teams/access/) acts as authentication proxy in front of applications/sites. When enabled you'll have to log in to Cloudflare Access before being able to access your application/site. In order to prevent the issue of having to log in twice, once for Cloudflare Access and once for Backstage itself, it would be nice if Backstage could use Cloudflare Access' session to identify the user.

## Possible Implementation

When accessing your application through Cloudflare Access, it will inject a header and cookie containing a JWT with your identity (see https://developers.cloudflare.com/cloudflare-one/identity/users/validating-json). Similarly to the AWS ALB provider (see https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/providers/aws-alb/provider.ts) this JWT could be used to create the identity and session for Backstage.

## Context

Cloudflare Access is a relatively new service for the trending _Zero Trust_ idea. More and more teams and companies are using similar services like this.

**Comment by simonknittel** [comment]
I'm interested in working on this 😄

**Comment by freben** [comment]
Of course, thank you - assigned!

**Comment by FabianHippmann** [comment]
Hi - very good timing we also wanted to start working on such a feature for GCP IAP (identityAwareProxy) - which has the same authflow.

Would also be interesting to check if the same can be done for keycloak.

I'll be doing a quick pic for IAP - let me know if we can support with this feature

**Comment by simonknittel** [comment]
Maybe there is room for something like a generic JWT provider instead of individual Cloudflare Access and GCP IAP providers when they got the same flow.

**Comment by anovis** [comment]
I am interested in this as well for IAP. Looks like passport does support a generic jwt package. 
http://www.passportjs.org/packages/passport-jwt/

Curious what the status is on this.

**Comment by FabianHippmann** [comment]
hi @anovis - i created a quick draft branch for the GCP IAP provider -> https://github.com/moonshiner-agency/backstage/tree/feature/add-gcp-iap-auth-provider

Documentation + Tests need to be adapted - but the provider itself works !

I'll update this thread as soon as i create a PR

**Comment by anovis** [comment]
@FabianHippmann awesome! that is exactly what I was looking for! I had started on this myself, but had trouble connecting it to the frontend. now i see from your code where I went wrong!

I am curious how you generated the iap headers locally to test the ```oAuth2Client.verifySignedJwtWithCertsAsync(``` function since I couldn't get that part to work either.

**Comment by FabianHippmann** [comment]
I'd recommend disabling the provider in the app-config or app-config.local locally

We developed it using trial and error - by deploying to Google cloud run - with a load balancer & IAP

**Comment by benjdlambert** [comment]
@FabianHippmann how far did you manage to get with the IAP Auth Provider? Looks pretty good so far! :)

**Comment by FabianHippmann** [comment]
Currently working on creating a PR for GCP IAP - i'll let you know as soon as the PR is created!

**Comment by freben** [comment]
@FabianHippmann That's great to hear, looking forward to it! Did you see the new work [here](https://github.com/backstage/backstage/issues/6245)? It is of interest to add that `signInResolver` etc.

**Comment by js0cha** [comment]
Is it still possible to use cloudflareaccess for Backstage ?

**Comment by rhoml** [comment]
Hi Lovely community. Since #12234 was merged I think this issue can be closed.

**Comment by benjdlambert** [comment]
Woop! thanks!
