### ISSUE TITLE
cli: add context for versions:bump on what version was bumped to

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#5565]
## Feature Suggestion

When running `yarn backstage-cli versions:bump`, if it upgrades packages that have a minor or higher change, it warns the user about possible changes.  However, when viewing the changelogs this time, it wasn't clear to me what version I was being bumped from and to, to know how to best read the change log.

```
⚠️  The following packages may have breaking changes:

  @backstage/catalog-model
    https://github.com/backstage/backstage/blob/master/packages/catalog-model/CHANGELOG.md

  @backstage/cli
    https://github.com/backstage/backstage/blob/master/packages/cli/CHANGELOG.md

  @backstage/core
    https://github.com/backstage/backstage/blob/master/packages/core/CHANGELOG.md

  @backstage/plugin-catalog
    https://github.com/backstage/backstage/blob/master/plugins/catalog/CHANGELOG.md

Version bump complete!
```

It would be great if it said something like:

```
  @backstage/plugin-catalog : 0.6.4 -> 0.7.4
    https://github.com/backstage/backstage/blob/master/plugins/catalog/CHANGELOG.md
```

## Possible Implementation

A few pages up in the console scroll log, the user does have this:

```
Some packages are outdated, updating

bumping @backstage/plugin-catalog in @roadiehq/backstage-plugin-github-pull-requests to ^0.5.6
bumping @backstage/core in @roadiehq/backstage-plugin-github-pull-requests to ^0.7.7
bumping @backstage/catalog-model in @roadiehq/backstage-plugin-github-pull-requests to ^0.7.7
bumping @backstage/cli in @roadiehq/backstage-plugin-github-pull-requests to ^0.6.9
```

So the context is there, but can be lost, so would be helpful just to print it again as sort of a "summary of what the cli did".

## Context

When upgrading, the versions bump warns the user there may be manual instructions in the CHANGELOGs they need to address. But would be nice to be even more specific, potentially even guessing at the chapter hash inside of the changelings, to better guide the user. (Since the changelog for each package doesn't have a date, the user may not know how far to go back.)

**Comment by BA1RY** [comment]
Hi @adamdmharvey , I would like to work on this. How can I go about implementing this?

**Comment by benjdlambert** [comment]
@BA1RY so that script is here: https://github.com/backstage/backstage/blob/f5b0d234315cc0f4ab38d0b17443d69650c21528/packages/cli/src/commands/versions/bump.ts

You should be able to cache the versions before the yarn install is run for the packages that have been unlocked and then grab their new versions from the lockfile after the install to get the new version I think.

**Comment by BA1RY** [comment]
Hi @benjdlambert , thanks for the heads up.
I went through the code and discovered that the `breakingUpdates` stores both the from and to version numbers.
https://github.com/backstage/backstage/blob/f5b0d234315cc0f4ab38d0b17443d69650c21528/packages/cli/src/commands/versions/bump.ts#L174
So I used the same to display the version update. Updated the test cases for the same.

I've made a PR. Please have a look at it and let me know if there are any changes to be made. Thanks 😃
