### ISSUE TITLE
Badges Plugin - Incorrect Link Provided

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#5566]
## Expected Behavior

The Badge Link generated in Backstage should be the correct link that directs the user to the component page.

![image](https://user-images.githubusercontent.com/6157895/116929940-19208700-ac2d-11eb-8e18-e89c5fc4b059.png)

## Current Behavior

The generated link is incorrect:  `https://my-backstage-instance/catalog/component/default/my-component-name`

when it should be: `https://my-backstage-instance/catalog/default/component/my-component-name`

**Comment by kuangp** [comment]
seems like a duplicate of #5112

**Comment by regicsolutions** [comment]
Thanks @kuangp will close this one then.
