### ISSUE TITLE
GitFeedbackLink requires github or gitlab hosts in integrations

### ISSUE THREAD

**Issue by ougfh** [backstage/backstage#5575]
## Expected Behavior

- FeedbackLink is working with self-hosted git
- FeedbackLink is working without `integrations` in `app-config.yaml` because it is an optional configuration 

## Current Behavior

In `app-config.yaml` is required to have `github.com` or `gitlab.com` integration and `github` or `gitlab` host in `SourceUrl` to add `FeedbackLink`

## Possible Solution

- Do not check `integrations` in the `addGitFeedbackLink`, instead check `sourceURL` to identify git type.

## Context

Can't use `GitFeedbackLink` in `techdocs` with GitHub Enterprise.

**Comment by kuangp** [comment]
is this the same as #5438

**Comment by ougfh** [comment]
@kuangp no, #5438 was resolved in https://github.com/backstage/backstage/pull/5461

**Comment by freben** [comment]
The integrations are meant to be _the_ way to interact with any provider - it is expected that you'll add config there for the things you work with. The `ScmIntegrations` class is also meant to always supply a `github.com` etc entry whether you specify one or not - the public ones should always be there automatically.

The thing about URLs is, there's no way for us to know what the provider is just based on the URL. A lot of the time, companies have a `https://scm.company.net` or whatever and nothing stating if it's github enterprise or what. And each of those systems have specifics around how to properly resolve paths within them and stuff like that. We really want to have that information.

**Comment by freben** [comment]
Is there something in particular that makes you _not_ want to specify it under `integrations` in config?

**Comment by timbonicus** [comment]
I guess the comment here is that the feedback link could work with the provided public integrations, where no config is required. This could fallback to URL detection if no integration config is found, and only support well-known hosts like `github.com`, `gitlab.com`, etc.

**Comment by ougfh** [comment]
@freben feedback link could work without integrations. Integrations currently are used to identify the type of the link, and it seems that it could be done without `integrations` key in config.

@timbonicus yeah, it is the second point of feedback that the current set of the host is limited. But if the latest release can be used different hosts because was checked `sourceURL`.

**Comment by ougfh** [comment]
I understand the thing about URLs. Anyway, if correct GitHub integration will be specified now the feedback link will not work with GitHub enterprise

**Comment by ougfh** [comment]
Sorry, I was wrong about that it will not work. Closing the issue because it is not.a bug

**Comment by freben** [comment]
Yep happy to hear it turned out OK! The code in there tries its absolute best to always under all circumstances have a `github.com` entry in there, but there could for sure have been some bug in that :)
