### ISSUE TITLE
Unable to instantiate from a template using docker image with cookiecutter 

### ISSUE THREAD

**Issue by banshee86vr** [backstage/backstage#5584]
Trying to instantiate a service from a component template using an image with cookiecutter I'm facing the same error reported in #5488.

## Expected Behavior

I should continue to be able to create the service starting from a component template.

## Current Behavior

Im getting the following error in the Publish phase:

`The visibility parameter is valid only when the nebula-preview header is provided.`

## Steps to Reproduce

1. Clone backstage from `main` branch
2. Create new application (same behaviour using the original root repo path)
3. Build docker image for the backend using the Dockerfile provided in `contrib` folder, adding the installation of `cookiecutter`:
```
FROM node:14-buster

WORKDIR /app

RUN cd /tmp && curl -O https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tar.xz && \
    tar -xvf Python-3.8.2.tar.xz && \
    cd Python-3.8.2 && \
    ./configure --enable-optimizations && \
    make -j 4 && \
    make altinstall

RUN apt update
RUN apt install -y mkdocs

RUN pip3.8 install mkdocs-techdocs-core

RUN pip3.8 install cookiecutter && \
    apt remove -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev libbz2-dev g++ python-pip python-dev && \
    rm -rf /var/cache/apt/* /tmp/Python-3.8.2

COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn install --frozen-lockfile --production --network-timeout 300000 && rm -rf "$(yarn cache dir)"

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY packages/backend/dist/bundle.tar.gz app-config.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```
5. Build docker image for the frontend:
```
FROM nginx:mainline

RUN apt-get update && apt-get -y install jq && rm -rf /var/lib/apt/lists/*

COPY packages/app/dist /usr/share/nginx/html
COPY docker/default.conf.template /etc/nginx/templates/default.conf.template

COPY docker/inject-config.sh /docker-entrypoint.d/40-inject-config.sh

ENV PORT 80
```
6. Register the component template from [https://github.com/projectkerberus/gcp-stack-template](https://github.com/projectkerberus/gcp-stack-template)
7. Create service from the imported component template, facing the error:

![Screenshot 2021-05-05 at 15 01 37](https://user-images.githubusercontent.com/53040714/117144936-d688b700-adb2-11eb-950f-0721964e714a.png)

**Comment by Fox32** [comment]
I think this is a duplicate of #5488 right?

**Comment by banshee86vr** [comment]
I don't think so because I try to start from scratch cloning the `master` branch today. The fix #5488 has been merged 8 days ago.

**Comment by banshee86vr** [comment]
I'm facing the same error also using examples provided here [https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates](https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates).

**Comment by benjdlambert** [comment]
@banshee86vr what version of the `@backstage/plugin-scaffolder-backend` are you using @banshee86vr?

**Comment by banshee86vr** [comment]
@benjdlambert I'm using `0.11.0`

**Comment by timbonicus** [comment]
@banshee86vr are you using a GitHub Apps configuration with `plugin-github-apps`? A similar issue was pinpointed with GitHub Apps configuration in Discord, wondering if it's the same here.

**Comment by timbonicus** [comment]
I unfortunately wasn't able to reproduce this, either in a new `@backstage/create-app` application or in the main repo. In both cases I used GitHub Apps authentication, and was running a built Docker image with `cookiecutter` installed locally as mentioned above.

The code only sends the `visibility` param when the owner is set to an organization, so I was careful to use an org as the owner. I could see the visibility successfully set to `private` on the repo when I had `scaffolder.github.visibility` configured as such in `app-config.yaml`. No trouble or mention of `nebula-preview` with either `v1alpha1` or `v1beta2` templates.

Maybe it's worthwhile to make a minimal reproduction example, @banshee86vr? I'm wondering at this point if there's a problem with multiple versions of `plugin-scaffolder-backend` plugin installed (check `yarn.lock`) or something else weird going on here.

**Comment by banshee86vr** [comment]
Thanks @timbonicus for your reply. So, probably I'm not doing something right during the building of the docker images. Please, could you share with me your procedure and your Dockerfiles?

**Comment by timbonicus** [comment]
Yep, this was my process:

1. `npx @backstage/create-app`
2. `yarn backstage-cli create-github-app <org>`
3. Set in `app-config.yaml`:

```yaml
integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-<app_name>-credentials.yaml

scaffolder:
  github:
    visibility: private # or 'internal' or 'private'

catalog:
  rules:
    - allow: [Component, Template, Location]
  locations:
    # Backstage example templates
    - type: url
      target: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/sample-templates/all-templates.yaml
```

4. Updated Dockerfile to install cookiecutter as you mention. I did not separate the backend and frontend deployment, just for simplicity. In theory this shouldn't matter, since the task is backend-executed.

```
FROM node:14-buster

WORKDIR /app

RUN cd /tmp && curl -O https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tar.xz && \
    tar -xvf Python-3.8.2.tar.xz && \
    cd Python-3.8.2 && \
    ./configure --enable-optimizations && \
    make -j 4 && \
    make altinstall

RUN pip3.8 install cookiecutter

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn install --frozen-lockfile --production --network-timeout 300000 && rm -rf "$(yarn cache dir)"

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY packages/backend/dist/bundle.tar.gz app-config.yaml github-app-orchestra-app-credentials.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```

5. `yarn build-image`
6. `docker run -p 7000:7000 backstage`
7. Created services from a few of the sample templates

Does this work outside of Docker for you? This doesn't seem to have anything to do with Docker or cookiecutter, it's just with how the scaffolder-backend communicates with GitHub. Have you checked `yarn.lock` (or `yarn why @backstage/scaffolder-backend`) to make sure there's not somehow different versions of `scaffolder-backend` installed?

**Comment by banshee86vr** [comment]
Thanks @timbonicus, starting from a newer version of backstage it's working.
