### ISSUE TITLE
[Techdocs] Blank page displayed when using the latest version of @techdocs/cli

### ISSUE THREAD

**Issue by abdulakhter** [backstage/backstage#5591]
## Expected Behavior

Display mkdocs documentation in the backstage-like interface that is launched when running npx @techdocs/cli serve. 

## Current Behavior

Currently running the latest version causes the browser to show a blank instead of the documentation. Running the older version 0.3.3 does not show this incorrect behavior.

## Possible Solution

Looks like it was introduced after [these](https://github.com/backstage/techdocs-cli/pull/44) changes were included in the main package.

## Steps to Reproduce

1. Run npx @techdocs/cli serve in a folder that contains a mkdocs yaml+documentation present.
2. Navigate to http://localhost:3000/docs/default/component/local/

## Context

Trying to deploy techdocs to our fork of backstage but it is currently not functional. Instead we have pinned it to the older version for the meantime. 

## Your Environment

- NodeJS Version (v12): v14.15.4
- Operating System and Version (e.g. Ubuntu 14.04): MacOSX Catalina 10.15.7
- Browser Information: Latest stable version of Chrome and Firefox.

**Comment by OrkoHunter** [comment]
Should be fixed by this https://github.com/backstage/techdocs-cli/pull/48 from @iamEAP 

Try the latest `v0.3.5` version of the cli?

**Comment by abdulakhter** [comment]
Ayyy perfect! Thank youuuu! :D

**Comment by abdulakhter** [comment]
> Should be fixed by this [backstage/techdocs-cli#48](https://github.com/backstage/techdocs-cli/pull/48) from @iamEAP
> 
> Try the latest `v0.3.5` version of the cli?

Ayyyy perfect thank youuuu! :D

**Comment by iamEAP** [comment]
Thanks y'all!
