### ISSUE TITLE
techdocs - highlight focusable items in the left tree

### ISSUE THREAD

**Issue by falconbin** [backstage/backstage#5596]
for techdocs, I want clearly know which item and it's parent items I'm on for the left tree, refer to angular docs behavior(https://angular.io/docs), for current, sometimes, it's hard to know it's parent. refer to below screenshot:
![image](https://user-images.githubusercontent.com/20329141/117241086-e95bc400-ae64-11eb-9d6e-74bf21111fdf.png)

## Feature Suggestion
1. highlight the selected item including all its parent items.  - Resilience4J is selected, it's parent items 'Fault Tolerance' and 'LWC' are highlighted in blue.
2. set hovered item's font and background color - Authentication item
refer to below screenshot:
![image](https://user-images.githubusercontent.com/20329141/117238264-202edb80-ae5f-11eb-9c87-93c60b4a15d6.png)

## Possible Implementation
inject new css style(https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/components/Reader.tsx): 
![image](https://user-images.githubusercontent.com/20329141/117241185-21630700-ae65-11eb-80b9-1eca51400399.png)

**Comment by Crevil** [comment]
For people having issues with seeibg contrasts or colors, it might be nice if there was another clue along with colors. An icon, under line or alike.

**Comment by gtzefrain** [comment]
I'll pick this up!

**Comment by adamdmharvey** [comment]
Thanks @gtzefrain ! Assigned to you.

**Comment by garyniemen** [comment]
@camilaibs For your review list this week perhaps.
