### ISSUE TITLE
Deprecate old `TemplateV1alpha1` Syntax

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#5620]
- [x] Deprecation warnings when calling legacy actions
- [x] Migrate the sample templates to v2
- [x] Migration guide for end users
- [x] #5620
- [x] After 2 weeks remove the old router logic and remove old legacy actions

**Comment by benjdlambert** [comment]
Work for migration guide here: https://github.com/backstage/backstage/pull/5678

**Comment by OscarDHdz** [comment]
Hi there!!
Wanted to know if you guys have an estimated date in which Alpha Templates will be completely deprecated???  In our Org we have quite a few alpha templates and we want be prepared for that (e.g. send communication to our people (template owners) about the migration).

**Comment by benjdlambert** [comment]
Hey @OscarDHdz - so the deprecation warnings were released 12 days ago, we have some docs for migrating here: https://backstage.io/docs/features/software-templates/migrating-from-v1alpha1-to-v1beta2 and will probably look to remove support for v1 in around 2 weeks I believe. Releases after that won't support the old v1alpha1 template syntax.

There's also this PR, which we will hope to ship this week which moves our built in templates to `v1beta2` for some reference too.

**Comment by OscarDHdz** [comment]
@benjdlambert Thanks!!! That's exactly what we wanted to know. 😃
