### ISSUE TITLE
Support "system" field for Template kind

### ISSUE THREAD

**Issue by rbideau** [backstage/backstage#5638]
## Feature Suggestion

Add the field `system` under `spec` for the `Template` kind

## Possible Implementation

- emit the relation in the [BuiltinKindsEntityProcessor](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/BuiltinKindsEntityProcessor.ts) as it does for the other entity kinds (with tests)
- update the [json schemas](https://github.com/backstage/backstage/tree/master/packages/catalog-model/src/schema/kinds)
- update the [type and validators](https://github.com/backstage/backstage/tree/master/packages/catalog-model/src/kinds) (with tests)
- update the [doc](https://github.com/backstage/backstage/blob/master/docs/features/software-catalog/descriptor-format.md#kind-template)
- update the [TemplateCard](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/TemplateCard/TemplateCard.tsx) to show a link when the template has entities with relation `RELATION_PART_OF` (using `getEntityRelations`)
- update the [TemplatePage](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/TemplatePage/TemplatePage.tsx) header to show a link when the template has entities with relation `RELATION_PART_OF` (using `catalogApi.getEntityByName` and `getEntityRelations`)
- create a `EntityHasTemplateCard` to display template part of a system, leveraging #5361

## Context

System already allows to group resources, components and APIs together around business functionalities. With the new template (version `v1beta2`), template can be use to do even more thing, sometime related to other components or API. It could be useful to group the template in the system as well.

See also #5440

**Comment by freben** [comment]
Hm. We had not intended for these to be categorized as such. The original thought is that Templates are a kind of global concern, and that users might use facilities such as tags and similar to arrange, filter and order them.

At the _very least_, the system would have to be an optional thing for a Template. But still not sure it should be there at all.

Do I understand your context to mean, that you want to use the scaffolder to run tasks that only even make sense at all, within the context of a single system? Can you elaborate on what it is that you want to achieve with this?

**Comment by rbideau** [comment]
Of course system would be optional.

In our company, we have two use cases for that:
- We have a set of front-end library used for cross-cutting concern (generic UI component, authentication). We want to be able to register each library as a `Component`, with a documentation etc ... but we will also have a `Template` to scaffold a new project based on those library. 
- We are using a API management solution and we have a `Component` for some guidelines, documentation and a `Template` for creating new API proxy. We will probably add other `Template` later for interacting with it.

In both cases, having a `System` would be useful for discovery.

**Comment by rbideau** [comment]
We have found another solution for our use case by having a naming convention for our templates.
I'm closing this.
