### ISSUE TITLE
how to make a step id optional in v1beta2 schema 

### ISSUE THREAD

**Issue by sharadpattanshetti** [backstage/backstage#5646]
Wanted to know how to make any step id optional so that user can skip it while using the template. Already checked the related issue -https://github.com/backstage/backstage/issues/3745
but did not find anything in documentation. 
Any suggestions ?
 

 steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:cookiecutter
      input:
        url: ./template
        values:
          name: '{{ parameters.name }}'

    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        targetPath: ./community
        url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is {{ parameters.name }}'
        repoUrl: '{{ parameters.repoUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

**Comment by jhaals** [comment]
Hi @sharadpattanshetti,
There is currently no support for making actions optional. You can however make an action "optional" by wrapping it in a custom action that only executes the action if some condition is met.

**Comment by benjdlambert** [comment]
I think however this is something that would be useful. We spoke in the initial RFC about having a `if` parameter which can use template syntax to check for boolean. Either from `parameters` or from `step.{name}.output.something`

**Comment by jhaals** [comment]
I agree, it's definitely a feature worth adding. Perhaps we have some nice contributor that are interested in picking this up? 😉

**Comment by sharadpattanshetti** [comment]
Thank you @jhaals  and @benjdlambert  will look forward for this feature. We are also trying to achieve same using custom actions.

**Comment by OrkoHunter** [comment]
It's now possible to use `if:` when writing a step to make it optional. Just like GitHub Actions!
https://backstage.io/docs/features/software-templates/writing-templates
