### ISSUE TITLE
[Badges Plugin] Generated badge markdown links are broken

### ISSUE THREAD

**Issue by bgutschke** [backstage/backstage#5660]
## Expected Behavior

The generated link in the badge markdown is linking to the entity.

## Current Behavior

The generated link in the badge markdown is broken, since entity kind and namespace are in the wrong order.

## Possible Solution

In `plugins/badges-backend/src/badges.ts`:27:

bug:
```ts
const entityUri = `${e.kind}/${
    e.metadata.namespace || ENTITY_DEFAULT_NAMESPACE
}/${e.metadata.name}`;
```

fix:
```ts
const entityUri = `${e.metadata.namespace || ENTITY_DEFAULT_NAMESPACE}/${
    e.kind
  }/${e.metadata.name}`;
```

## Steps to Reproduce

1. Run example backstage via `yarn dev`
2. Open `http://localhost:3000/catalog/default/component/artist-lookup`
3. Open the badges preview window via the three dots in the upper right corner.
4. Check the link in the provided markdown and compare to the actual url of the entity.

**Comment by adamdmharvey** [comment]
I believe this duplicates #5112.  Thanks for the PR for it!

**Comment by bgutschke** [comment]
It is. Sorry, don't know how I missed it yesterday, when searching for it. It's quite obvious.
