### ISSUE TITLE
Role or scope based authorization

### ISSUE THREAD

**Issue by maha-z** [backstage/backstage#5679]
We want to implement scope based authorization. For users with different roles or scopes we would like to show or hide certain features in backstage. Can we have multiple authorization? For users who have logged with github when they click on a specific tab we would like to authorize using okta or auth0 and show the content based on the role or scopes of the user

**Comment by freben** [comment]
For entity visibility specifically, there's [this issue](https://github.com/backstage/backstage/issues/3218).

Large parts of the interface are composable in such a way that you could wrap them in an auth barrier, at the JSX level in your app package. We have no builtin functionality for this, but a part of what you mention you can probably implement as a custom thing for your org.

**Comment by OrkoHunter** [comment]
The permissions framework as proposed in [the RFC](https://github.com/backstage/backstage/pull/7761) is now being implemented. On top of that, Spotify is developing an RBAC plugin which will be paid. For more details, see https://backstage.spotify.com/blog/authorization-framework-rfc/
and https://backstage.spotify.com/blog/paid-plugins-announcement/

**Comment by benjdlambert** [comment]
The Permission Framework is now mostly in place I believe. Thinking that we are going to close this ticket now, as the RBAC plugin, which is built upon the open source Permission Framework has been mentioned.
