### ISSUE TITLE
Tech-radar search option

### ISSUE THREAD

**Issue by jvilimek** [backstage/backstage#5692]
We are using [tech-radar](https://github.com/backstage/backstage/tree/master/plugins/tech-radar) to provide hints for our developers what to use and where to find more info (links for wiki).

It would help the user experience to add also some sort of search. E.g. techradar from Thoughworks has built in search like this:
![image](https://user-images.githubusercontent.com/16001792/118484791-e93aae80-b717-11eb-9baa-6b17f93c0bcb.png)

Another way how to improve the UX is to include search for tech-radar among search results /search route. I asume this would be way more difficult as the way how the tech-radar data is populated is "on-fly"...

## Feature Suggestion

Search in [tech-radar](https://github.com/backstage/backstage/tree/master/plugins/tech-radar) 

## Possible Implementation

I guess only improving client side improving would be great. Yes, the user can use "CTRL+F" but.. would it search also among description? How about zooming to the quadrant/ring or provide some sort of result list?

## Context

Using CTRL+F to search among tech-radar entries is not quite user friendly and it does not search in the description.

**Comment by freben** [comment]
That makes a lot of sense! Added a help wanted label on it. Is this something you'd like to work on?

**Comment by jvilimek** [comment]
Thanks. Unfortunatelly I am not much skilled in typescript. But I can ask among colleagues.

**Comment by adamdmharvey** [comment]
Tying into the proposed [Backstage search architecture](https://backstage.io/docs/features/search/architecture) is for sure a great idea, and it's already been proposed to support the concept of enhancing search items from plugins.  So seeing where the search team is where that, and building off on it for tech-radar specifically likely is the way to go!

It might be a bit far off, given Search API integration is identified in milestone [Search v3](https://backstage.io/docs/features/search/search-overview#project-roadmap), and Search V1 (same link) is just being finished now.

cc @emmaindal

**Comment by emmaindal** [comment]
Hi @jvilimek and thanks for opening this issue. As mentioned above already, I think this makes a lot of sense, and I also agree with your additional idea in including tech radar results in the more "global" search results on the /search page. 

So as @adamdmharvey mention, our Search V3 milestone is where this will be fully supported and prioritized based on our current roadmap. With that said, I would see V1 already as an opportunity to contribute with something like this potentially, and we are currently [working on documentation](https://github.com/backstage/backstage/pull/5715) for [how other plugins can provide documents to index](https://github.com/backstage/backstage/pull/5715/files#diff-e5799b0f9b82a6029a57c80c71143dce7d8dd51b759c3fa35eb7922c764432dfR264) using something we call Collators. So when we reach our V1 milestone (very soooon 🥳) and the documentation is out, it will be easier for your to think about how this can be implemented.

In addition to that, we are also currently working on some reusable components ([see issue](https://github.com/backstage/backstage/issues/4445#issuecomment-826603847)) for other plugins to build search pages or even add just a search bar to a landingpage for example, so you can see these things comiing soon as well! (also in V1 milestone)

**Comment by benjdlambert** [comment]
Can we close this now?
