### ISSUE TITLE
How to override paddingBottom of InfoCard

### ISSUE THREAD

**Issue by HongliBu** [backstage/backstage#5698]
Hi I am using InfoCard of backstage storybook, I saw it inherits the paddingBottom of Material UI Card Content property:
```
.MuiCardContent-root-16432:last-child {
    padding-bottom: 24px;
}
```
I want to make it to 0,
I tried this:

```
const useStyles = makeStyles<BackstageTheme>((theme) =>
    createStyles({
        doCard: {
            "&:last-child": {
                paddingBottom: "0 !important"
            }
        }
    }));
```

and use it :

```
<InfoCard title="Do It" className={classes.doCard}>
   <div>
    Something
   </div>
   <div >
       <Button size="small" color="primary">
                       View More
         </Button>
   </div>
 </InfoCard>

```

it doesn't work. so is there a simple way to override the paddingBottom??

Thanks

**Comment by Irma12** [comment]
Hi @HongliBu I think what you probably need to do is use **cardClassName** since that is targeting InfoCard content. So instead of having :

```ts
 <InfoCard title="Do It" className={classes.doCard}>
     <div>
        Something
     </div>
     <div>
        <Button size="small" color="primary">
           View More
         </Button>
      </div>
  </InfoCard>
```
try

```ts
 <InfoCard title="Do It" cardClassName={classes.doCard}>
     <div>
        Something
     </div>
     <div>
        <Button size="small" color="primary">
           View More
         </Button>
      </div>
  </InfoCard>
```
Hope it will work :)

**Comment by HongliBu** [comment]
Hi @Irma12 , it doesn't work.
By the way I changed the doCard to :
```
        doCard: {
            flex: 1,
            "&>div": {
                paddingBottom: "0px !important"
            }
        }
```
and it works,
but I still want to know if any other methods or suggestions??

**Comment by freben** [comment]
This should already [be addressed](https://github.com/backstage/backstage/pull/5583) in later versions of the `@backstage/theme` package. Could it be that you are on an older version?

The PR shows the most proper way of fixing this: by tackling the central MUI theme.
