### ISSUE TITLE
Laggy on-page search on api-docs plugin

### ISSUE THREAD

**Issue by gasandov** [backstage/backstage#5719]
API Explorer component is lagging while on-page search

## Expected Behavior

Interacting with the UI has a perceptibly immediate reaction indicating the action has been recognized (e.g a click should immediately trigger some form of feedback - in the case of the form field, it should show focus in 0.2 sec or less; typing should follow the natural speed of the typist)

## Current Behavior

1. First issue: No response from the UI for ~2 - 4 seconds even indicating the click happened or that the field will indeed receive focus
2. Second issue: it takes around ~2 - 4 seconds for the first letter to appear after typing

## Possible Solution

The first thing that I did it was comparing the `catalog` code-base ([CatalogTable](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L159)) against the `api-docs` code-base, since on the catalog view this behavior is not present.

Found out that [ApiExploraarTable](https://github.com/backstage/backstage/blob/master/plugins/api-docs/src/components/ApiExplorerTable/ApiExplorerTable.tsx#L210) has two removable props `initalState` and  `onStateChange`

`onStateChange` is using a hook [useQueryParamState](https://github.com/backstage/backstage/blob/850a882762f5cd28d913f0bffec79b2260c22022/packages/core/src/hooks/useQueryParamState.ts#L59) that has a `debounce` inside of it.

So, I decided to remove those props to test the behavior and it was successful. I'm assuming that this hook was used at some point, but now it doesn't contribute more to the component itself, it's only wasting computing resources.

Also, debounce will work best if we call an API for results many times (while searching), but since we are searching inside data that was already fetch it doesn't add much meaning to it

I can contribute back once I receive feedback

## Steps to Reproduce

1. Go to the `api-docs` route (APIs list view)
2. Attempt to place focus on the on-page search field (in this case, click on `search` input)
3. Attempt to type an API name

## Context

https://user-images.githubusercontent.com/49690408/118715351-258a0f80-b7e9-11eb-89df-217c7d2957fb.mov

## Your Environment
The was bug caught on production env

- NodeJS Version (v12): v12
- Operating System and Version (e.g. Ubuntu 14.04): macOS Catalina v10.15.7
- Browser Information: Google Chrome v90.0.4430.212

**Comment by Fox32** [comment]
The `useQueryParamState` hook is responsible for updating the history state so that you return back to the previous filter state when navigating between routes - so just removing it is not an option.

Actually I think the issue lies in the table component as modifying the state still rerenders too much of it. We could resolve this by building an own toolbar and doing the search on our own. In the long term I think this would be the way to go, especially if we consider moving filtering to the backend.
