### ISSUE TITLE
Any reference for customize components in storybook?

### ISSUE THREAD

**Issue by HongliBu** [backstage/backstage#5753]
Hi I am using backstage storybook(https://backstage.io/storybook/). Sometimes I need to override some styles to fulfill my requirements. Often, this styles is deefined in material-ui and wrapped up in your components. 

For example,
In you Table Component(https://backstage.io/storybook/?path=/story/data-display-table--default-table),  I want to use className to define some css styles, I want to use stickyHeader. These can be achieved easily if I use Material-UI Table component, but it confused me how to do this when using Table in storybook?

So any suggestions to customized the components in a flexible way? if you have any reference or docs, can you share with me?

## Feature Suggestion

Documents for Components and Components APIs.

**Comment by Rugvip** [comment]
Yep, the component library is lacking in this department. It's something we want to improve

**Comment by benjdlambert** [comment]
@soapraj this is stale, but not sure if it's of value to you?
