### ISSUE TITLE
Support object-array notation in APP_CONFIG environment variable overrides

### ISSUE THREAD

**Issue by grv-trip** [backstage/backstage#5762]
Allow APP_CONFIG notation to support object-array notation since it currently seems to support only a limited amount of things

## Feature Suggestion

As mentioned [here](https://backstage.io/docs/conf/writing), currently config overrides only support `.` based prefixes such as `app.baseUrl` however, if there are array values present, dynamic value overrides are not getting picked up.

Example of current configs supported vs things not supported that were found are:

- **supported** which works:
  - app_config env var: 
  ```
  app: 
    baseUrl: http://localhost:3000
  ```
  - equivalent override: `APP_CONFIG_app_baseUrl`

- **Not supported/erroring out**
  -  app_config env var:
  ```
  support:
    items: 
      - title: Issues
   ```
   
   - equivalent override: `APP_CONFIG_support_items-title` (not working)
   

## Possible Implementation

Probably need changes in this file to begin with: [link](https://github.com/backstage/backstage/blob/master/packages/config-loader/src/lib/env.ts)

## Context
The motivation behind this feature request is to accomplish a separate frontend and backend separation of env vars following the [frontend with nginx](https://github.com/backstage/backstage/tree/master/contrib/docker/frontend-with-nginx) contrib helm chart way of deploying to Kubernetes (to be able to scale containers individually). 

Its mentioned to facilitate this approach, `you will have to supply the list of configuration files as part of the command line at build` with the related examples (inject-config.sh file) in the same directory. The image build for frontend containers does not use the app-config files for reading configuration.

Object-array type of notation in app-config.yaml file can be found [here](https://github.com/backstage/backstage/blob/master/app-config.yaml#L11-L23).

**Comment by Rugvip** [comment]
Thank you for the suggestion! We're quite hesitant to add this though. Would the following work for you instead?

```yaml
support:
  items:
    - title: `${MY_SUPPORT_TITLE}`
```

Along with setting `MY_SUPPORT_TITLE` in env

**Comment by grv-trip** [comment]
> Thank you for the suggestion! We're quite hesitant to add this though. Would the following work for you instead?
> 
> ```yaml
> support:
>   items:
>     - title: `${MY_SUPPORT_TITLE}`
> ```
> 
> Along with setting `MY_SUPPORT_TITLE` in env

Is this something already supported or it needs to be implemented? I have not given this a try, I can check

**Comment by Rugvip** [comment]
@grv-trip it's already supported

**Comment by grv-trip** [comment]
So I tried the following approaches (maybe I'm missing something, do let me know):

In the `app-config.yaml` file, in the root of create-react-app, I added:

```
support:
  items:
    - title: `${MY_SUPPORT_TITLE}`
```
and ran **yarn build** from the parent directory (After yarn install --> yarn tsc), I keep getting:

`Error: Configuration does not match schema
  Config should have required property 'title' { missingProperty=title } at /app/support/items/0`
  
 Thinking if there were some problems in the quotation marks, I even tried following:
 -  title: '${MY_SUPPORT_TITLE}'
 -  title: "${MY_SUPPORT_TITLE}"
 -  title:
       $env: MY_SUPPORT_TITLE
       
Where `MY_SUPPORT_TITLE` I am trying to pass as env vars from Kubernetes frontend deployment files, but not able to proceed to the step of depoyment since I am not even able to finish the yarn build.

Is there something I am missing?

**Comment by benjdlambert** [comment]
@grv-trip is this something than be closed now?

**Comment by grv-trip** [comment]
@benjdlambert and @Rugvip  Thanks for your help guys. I redid my current setup and got it working via the `${env}` way.

This can be closed now but would be curious to know the reasoning behind supporting `.` notations but not able to support object-array notations. Is this a breaking change in the data model?

**Comment by freben** [comment]
Yeah it's tricky. With objects, there are clear semantics for what the effect will be. For arrays, it's notoriously harder. For example to understand if the user intent is replacement or amending (consider cases where there already existed one or more elements beforehand). Some suggest being able to target individual items by index in an existing array which feels very leaky and unstable over time.

Essentially, given that there exists a semantically clear alternative (to add the actual item in config instead and to fill in its inner fields using env vars), we didn't feel that this was worth the effort and confusion. I would even venture so far as to say (though some will disagree) that the entire method of using `APP_CONFIG_x` should be avoided whenever possible.

**Comment by mingfang** [comment]
Please re-open this; I need to be able to set any app config using environment variables.
This problem has been solved by Spring https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0
