### ISSUE TITLE
Edit button on documentation pages produces unacceptable PRs

### ISSUE THREAD

**Issue by rvandegrift** [backstage/backstage#5800]
## Expected Behavior

If there's an Edit button on the docs, it should produce usable PRs that meet the repo's standards for acceptance.

## Current Behavior

I ran into some issues with the documentation page, so I clicked Edit to submit the changes.  The result was a PR missing a DCO statement - and so it couldn't be merged.  See https://github.com/backstage/backstage/pull/5798

**Comment by jhaals** [comment]
This is unfortunately a process that don't work automatically in the GitHub UI and the best we can do is to provide documentation, the same issue occurs when accepting suggestions on a PR and is something that the user has to add manually in the UI or by amending the commit message later on.

<img width="1269" alt="Screenshot 2021-05-28 at 10 14 43" src="https://user-images.githubusercontent.com/68980/119952842-b1e0c300-bf9d-11eb-99ca-e38114b070d5.png">
