### ISSUE TITLE
Yarn Start Live Reload

### ISSUE THREAD

**Issue by remarcbalisi** [backstage/backstage#5802]
Every time I have changes, I had to re-serve the local server to be able to reflect the change.

**Comment by remarcbalisi** [comment]
Yes modifying app-config.yaml and also when I change the logo in
app/src/components/Root/LogoFull.tsx and LogoIcon.tsx

I am running this under Ubuntu 20 WSL.

**Comment by jhaals** [comment]
`app-config.yaml` is not picked up automatically and a restart is required.

`.tsx` files should be picked up and reloaded automatically, is this happening for all .tsx files or just those two?
Changes are picked up on my Mac when I edit those tsx files but perhaps some friendly Windows user could help out verifying/testing this too.

**Comment by remarcbalisi** [comment]
> 
> 
> `app-config.yaml` is not picked up automatically and a restart is required.
> 
> `.tsx` files should be picked up and reloaded automatically, is this happening for all .tsx files or just those two?
> Changes are picked up on my Mac when I edit those tsx files but perhaps some friendly Windows user could help out verifying/testing this too.

I think it is for all .tsx files. As I also change some in `/src/App.tsx` (adding microsoft provider) and I had to restart.

**Comment by jvilimek** [comment]
I am having the same issue.. and I see in the bworser console following error `[WDS] Disconnected!`
Working on Windows 10, starting the backstage via WSL2.

**Comment by jvilimek** [comment]
and it may be connected with this issue: https://github.com/microsoft/WSL/issues/4739
```
If your project folder is under /mnt/..., the server won't detect any file modifications because Windows will not notify the development server. That means that you will need to restart the server after each modification to see any change in your views. The build can also be slow under that file system.

One workaround is to move your project into /home/<your username> and access to that folder via \\wsl$\... under Windows but it's not practical at all.
```
