### ISSUE TITLE
Tech-radar support for CSV data source

### ISSUE THREAD

**Issue by jvilimek** [backstage/backstage#5807]
Now there is a simple way how to feed data from [tech-radar](https://github.com/backstage/backstage/tree/master/plugins/tech-radar) plugin via "getData" attribute. We did implement our own feeder that loads data from CSV. However when we tried to put the url in the configuration we hit the wall many times as there is no easy way, how to achieve this "out" of the component.

I have prepared an enhancemen that fullfills our needs of loading tech-radar data from CSV. I would like to contribute to the comunity and want to gather feedback to this feature.

## Feature Suggestion

New attribute `useCsvLoader` in the TechRadarPage component:

```html
<TechRadarPage ... useCsvLoader />
```

New configuration:

```yaml
techradar:
  csvEntriesUrl: https://location-of-csv-source/xxx.csv
  quadrants:
    - id: lngfwk
      name: Languages & Frameworks
    - id: tools
      name: Tools
   ...
  rings:
    - id: adopt
      name: Adopt
      color: '#009688'
    - id: trial
      name: Trial
      color: '#6acbef'
   ...
```

## Possible Implementation

plugins/tech-radar/src/components/RadarComponent.tsx
```typescript
...
import { TechRadarCsvDataLoader } from './csv-support/TechRadarCsvDataLoader';
...
const useTechRadarLoader = (props: TechRadarComponentProps) => {
  ...
  const configApi = useApi(configApiRef);
  const csvEntriesUrl = configApi.getOptionalString('techradar.csvEntriesUrl') ?? 'https://unknown-url-please-configure';
  ...
  const state = useAsync(async () => {
    if (useCsvLoader) {
      const response: TechRadarLoaderResponse = await TechRadarCsvDataLoader(csvEntriesUrl);
      return response;
    }
    if (getData) {
      ...
    }
    return undefined;
  }, [getData, errorApi]);
  ...
};
```

plugins/tech-radar/src/components/csv-support/TechRadarCsvDataLoader.ts
```typescript
export { TechRadarCsvDataLoader };

import { GetRadarEntries } from "./GetRadarEntries";
import { TechRadarLoaderResponse } from "../../api";

const TechRadarCsvDataLoader = async (csvEntriesUrl: string) : Promise<TechRadarLoaderResponse> => {
    const entries = await GetRadarEntries(csvEntriesUrl);
    return Promise.resolve({
        quadrants: //TBD: load from config or get from parameter,
        rings: //TBD
        entries: entries,
    });
}
```

plugins/tech-radar/src/components/csv-support/GetRadarEntries.ts
```typescript
import { RadarEntry } from "../../api";
import { GetCsvEntries } from "./GetCsvEntries";

export async function GetRadarEntries(
    csvEntriesUrl: string
): Promise<RadarEntry[]> {
    const entries: RadarEntry[] = [];
    const csvRecords = await GetCsvEntries(csvEntriesUrl);
    var i = 0;
    csvRecords.forEach((row: { name: string; ring: string; quadrant: string; movedState?: number; description: string; url?: string;}) => {
        i++;

        entries.push({
            url: row.url ?? '#',
            key: 'key_' + i,
            id: 'id_' + i,
            title: row.name,
            quadrant: row.quadrant,
            description: row.description,
            timeline: [
                {
                    //TBD: only one row used?
                    moved: row.movedState,
                    ringId: row.ring,
                    date: new Date('2020-01-01'), //TODO
                    description: row.description,
                }
            ]
        })
    });
    return Promise.resolve(entries);
}
```

plugins/tech-radar/src/components/csv-support/GetCsvEntries.ts
```typescript
import parse from 'csv-parse/lib/sync';

export async function GetCsvEntries(
    csvEntriesUrl: string,
): Promise<any> {
    console.log("Fetching csv from %s", csvEntriesUrl);
    const response = await fetchUrl(csvEntriesUrl);
    const records = parse(response, {
        columns: true,
        skip_empty_lines: true,
        delimiter: ",",
    })
    return Promise.resolve(records);
}

const fetchUrl = async (
    url: string,
): Promise<string> => {
    const response = await fetch(url);
    if (response.status === 200)
        return await response.text() as string;
    throw new Error("Response not 200");
};
```

sample data (plugins/tech-radar/sample-data.csv):
```csv
name,ring,quadrant,movedState,description,area,url
Backstage,adopt,platforms,0,"An open platform for building developer portals: Powered by a centralized service catalog, Backstage restores order to your infrastructure and enables your product teams to ship high-quality code quickly — without compromising autonomy.",development,https://backstage.io/
```

## Context

We want to load data for tech-radar from csv.

**Comment by jhaals** [comment]
Hi, would it be possible to supply some more context to the current problem you are having and why you've picked csv as the format for this data? CSV is not a particularly user friendly format for editing by hand compared to the configuration file.

**Comment by Fox32** [comment]
While I don't think that CSV is a good choice, it would still be useful if there is a layer of abstraction between to configuration and the display component - Most Backstage plugins provide an API that you can override to configure your custom loading logic. That is missing here, but should be introduced. That way we don't have to add CSV support directly like suggested above. It could be done like in the explore plugin https://github.com/backstage/backstage/blob/master/plugins/explore-react/src/tools/api.ts and provide a default implementation that reads from the configuration.

**Comment by Fox32** [comment]
On the other hand, there already seems to be support for it, using a simple callback: https://github.com/backstage/backstage/discussions/5540#discussioncomment-750514

**Comment by jvilimek** [comment]
> Hi, would it be possible to supply some more context to the current problem you are having and why you've picked csv as the format for this data? CSV is not a particularly user friendly format for editing by hand compared to the configuration file.

Absolutely: my colleague already have already built a tech radar via a thoughworks, for details see [how-to-byor](https://www.thoughtworks.com/radar/how-to-byor). They are using **Google sheet** to define the tech radar with the sharing link to read it and then display it. So I have decided to use the very same data source (this google shared sheet) but I am a newbie in the typescript and the possibilities so I have exported it to CSV and stored it in the repo...with the possibility to publish it to the azure storage eventually. This way we can see the tech radar changes in the git history, we have even the possibility to review the changes in pull request and still be able to provide a simple way for other (business) users to change the source via known tools like Excel (csv source) or google sheet (web access).

**Comment by jvilimek** [comment]
> On the other hand, there already seems to be support for it, using a simple callback: [#5540 (comment)](https://github.com/backstage/backstage/discussions/5540#discussioncomment-750514)

Yes. That is exactly the callback I have tried to use initialy. And in fact in case you read from the CSV and if you have the url hardcoded in the function it works just fine. Complications started when we wanted to move the configuration of the url to the app-config.yaml so we do not have hardcoded urls...and maybe we can have different XLS for dev and live environment. then you realize you can have `useApi(configApiRef)` in the callback function. Nor in the app.tsx or have async calls there...well you can  use something like this:
![image](https://user-images.githubusercontent.com/16001792/119998448-fe91c180-bfd0-11eb-94b0-611e481447aa.png)
but it doesnt feel right as it may introduce race-condition...

Believe me I have spent maybe days (with several hours of the help of our typescript guru) and adjusting the tech-radar plugin was the best solution we came with.

Also bear in mind you need to somehow and somewhere define "visibility" for the configuration of the app-config.yaml...

**Comment by Fox32** [comment]
Yeah, you are right the `getData` callback doesn't play nicely whit other Backstage patterns at all... If I was an API, it would be easy to access the `configApi`...
I would suggest replacing `getData` with an API and provide a default implementation that reads from the config. Writing one that reads from a custom backend or directly from another source (e.g. CSV file in a bucket) would be easy then!

**Comment by jvilimek** [comment]
So what do you suggest is to add API to tech-radar to load the data for frontend and in that API provide the possibility to replace the implementation to get data? I believe I can prepare something like this. It would be a bit worse in performance as I wanted to put the CSV on the CDN, on the other hand the architecture would be cleaner in a way...  another possible implementation would be to instead of "getData" callback have the possibility to specify url where to find JSON data for the tech radar. And the logic of  retrieving from CSV/google sheet and publishing it as JSON can be done in our custom pipeline...

**Comment by Fox32** [comment]
Actually that shouldn't have a performance impact. With API I mean an interface in the frontend that an adopter can replace with an own implementation. See the example for the explore plugin linked above.

**Comment by benjdlambert** [comment]
Hey :wave: So i've been hacking a little on making the `TechRadar` a little more flexible on how you load data.

It's not yet finished as I need to write some documentation, but in theory you can create your own `class` which implements `TechRadarApi` with a `load` method that should return the correct JSON object, and how you build that JSON object is entirely up to you. So you can read a CSV URL from config if you want and parse that CSV file and create the required JSON object.

#5891

**Comment by jvilimek** [comment]
Thank you very much, @benjdlambert !
Just few days back I have implemented loader via your API and it works like a charm!

**Comment by satrox28** [comment]
Hi @jvilimek 
I am trying to load Techradar data from an API, May I know the format you used, can you provide me the sample format of the input.

**Comment by benjdlambert** [comment]
> Hi @jvilimek 
> 
> I am trying to load Techradar data from an API, May I know the format you used, can you provide me the sample format of the input.
> 
> 
> 
> 
> 
> 

I think you might want to follow the guide here: https://github.com/backstage/backstage/blob/master/plugins/tech-radar/README.md#how-do-i-load-in-my-own-data @satrox28
