### ISSUE TITLE
Exporting more components related to the AboutCard

### ISSUE THREAD

**Issue by heatheralee** [backstage/backstage#5813]
## Feature Suggestion

Hi! We are currently looking at adding an additional icon to the `AboutCard`. Our current plan is to create a patch using [npm's patch-package](https://www.npmjs.com/package/patch-package) package that exports `AboutCardContent`, `AboutField`, `ScmIntegrationIcon`, and the utilities under `utils` from the `catalog` plugin. That way, we can make our own copy of the `AboutCard` and make the necessary changes. However, it would be fantastic if we could export these components and utility functions and push this upstream so that we don't end up adding more patches than we need to. I'd also love to hear any feedback that might make these exports not necessary/hear about any other workarounds/how other people have tackled this problem. Thanks in advance!

## Possible Implementation

Update plugins/catalog/src/index.ts to export `AboutCardContent`, `AboutField`, and other helpful functions so that we can implement `AboutCard` ourselves if we want to.

## Context

We are trying to create our own `AboutCard` with a new icon up at the top.

**Comment by benjdlambert** [comment]
@heatheralee yep I think you can go ahead and make a PR to export these components, What other changes were yout thinking about making configurable? We'd ideally like to make them as configurable as possible and avoid having to use the `npm-patch-package` thing. :)

**Comment by heatheralee** [comment]
Awesome, thank you @benjdlambert! I'll take a look at making these changes and think about ways to make some of these components more configurable. :)

**Comment by heatheralee** [comment]
Just created a PR for exporting some of these components! I'm still thinking about ways to export the viewInSource, viewInTechDocs, and viewApi logic so that it might eventually be possible to go and configure the `AboutCard` directly rather than creating a custom one. I can follow up in another PR for that. Thanks in advance!
