### ISSUE TITLE
templates: RepoUrlPicker is magical, or docs are missing something

### ISSUE THREAD

**Issue by rvandegrift** [backstage/backstage#5815]
I had a heck of a time getting backstage to create repos from my own template.  I'm finally up and running, though I wanted to offer some feedback on what tripped me up, and offer possible suggestions.  I'm not very confidant whether this bug report is about:
1. documentation gaps/issues
2. usability of Template v1beta1
3. terminological confusion
4. something else entirely

Hopefully this is clear enough to be useful - apologies in advance if it isn't.

## `RepoUrlPicker` seems magical

As a new user, the template from [1] looked too complicated.  So I trimmed it down to the bare minimum, hardcoding values to try and get going.  I ended up unable to `publish`, getting error messages like this:
```
2021-05-25T16:41:22.000Z Beginning step Publish
2021-05-25T16:41:22.000Z InputError: Invalid repo URL passed to publisher: https://mygitlab.com/path/to/myproject, missing owner
```
Since the error message mentioned "owner", I started trying lots of permutations of the various owner related stuff.  None of that made a difference.

Finally, I tracked it down to my simplification - I had removed the parameter using `RepoUrlPicker` and just hardcoded a repo in the `publish` step.  I'm puzzled about why this didn't work:

1. The docs at `/create/actions` say that `repoUrl` is the repo location, and it's a string - so I think I was using that api correctly.
2. The explanation at [2] makes it sounds like `RepoUrlPicker` is mere convenience.
3. I later tried Template v1alpha1, and entering the same repo format in the form worked fine.

I *think* I might be confused by two different owners: the result of `OwnerPicker` (I guess that's the owner of the component in backstage) and the owner from `RepoUrlPicker` (ie the gitlab/github group where the repo should be created).  If so, using "owner" for both of these is unfortunate.

## Possible Solution
A number of things may have helped:

1. Writing Templates [1] should start with a simpler use-case.  In fact, it'd be great to start with a zero parameter template.  That way, I could validate that the app is loading template and creating repos correctly.  Then, stage two could involve updating the template to accept parameters from the user and pass them to cookiecutter.
2. The text at [2] should say that using `RepoUrlPicker` is required, or maybe
3. Template v1beta1 needs to make explicit however the owner parameters comes from `RepoUrlPicker`.
4. The `publish:gitlab` and `publish:github` docs from `/create/actions` seem wrong - `repoUrl` is not just a string with the repo location.
5. Reserve the term "owner" for the backstage owner, use "group" for the source code repo location.
6. It'd be nice to have an explanation about the difference between a template's `spec.owner` and the owner supplied in the form.

[1] - https://backstage.io/docs/features/software-templates/writing-templates
[2] - https://backstage.io/docs/features/software-templates/writing-templates#the-repository-picker

**Comment by ghassen1khalil** [comment]
Hi @rvandegrift, did you find a solution the 'mission owner' issue with your template please ?

**Comment by brodo** [comment]
The repo URL must be of the format 'gitlab.com?repo=project_name&owner=group_name.' It is not the repository's actual URL.
