### ISSUE TITLE
Github Actions plugin fails to load jobs list

### ISSUE THREAD

**Issue by yafanasiev** [backstage/backstage#5819]
## Expected Behavior

Should load the jobs list in the workflow view.

## Current Behavior

Job list is empty, request to Github API fails with 404.

## Possible Solution

Looks like request for jobs is made here: https://github.com/backstage/backstage/blob/ad3188cafd90b0627e0470c7ac437fbabe4a00c9/plugins/github-actions/src/components/WorkflowRunDetails/useWorkflowRunJobs.ts#L28
Since this is regular fetch, no Github token is supplied and request is unauthenticated (404 is Github's forbidden response in this case, same request made through Postman and PAT works)

## Steps to Reproduce

1. Set up plugin according to [docs](https://github.com/backstage/backstage/tree/ad3188cafd90b0627e0470c7ac437fbabe4a00c9/plugins/github-actions)
2. Set up Github App
3. Add a component with valid `github.com/project-slug` annotation.

## Your Environment

- NodeJS v14.16.0:
- MacOS 11.3.1:
- Chrome 90.0.4430.212

![Screenshot 2021-05-26 at 15 57 46](https://user-images.githubusercontent.com/66992401/119663632-2fd88900-be3b-11eb-88d4-1c313a6b3666.png)
![Screenshot 2021-05-26 at 15 54 10](https://user-images.githubusercontent.com/66992401/119663642-3109b600-be3b-11eb-84f9-27d15a7c3791.png)

**Comment by benjdlambert** [comment]
Looks like this plugin will need to use the `githubAuthApiRef` to grab the signed in users token and use that to make a request.

Is this something you want to contribute @yafanasiev?

**Comment by djamaile** [comment]
If @yafanasiev doesn't want to do it, I can pick it up

**Comment by yafanasiev** [comment]
I could take a look later this week. I am not that good with JS, but I will do my best :grin:
