### ISSUE TITLE
Adding a sub menu option to the nav bar components

### ISSUE THREAD

**Issue by tradcliffe-expediagroup** [backstage/backstage#5826]
## Feature Suggestion

At Expedia, we are looking to create a sub menu in the side navigation bar so we can group together similar plugins in the navigation. We wanted to see if the Backstage owners were interested in this being added to Storybook as part of the side navigation. 

## Possible Implementation

Our initial thought to approach this for open source was to add a new component to Storybook [SideBar](https://github.com/backstage/backstage/tree/master/packages/core/src/layout/Sidebar) that took in a title, icons and names associated with the icons to create a sub menu of `SidebarItem` under the title. 

## Context

We are looking to add the ability to group sidebar navigation items together with a title.

**Comment by jhaals** [comment]
Hi @tradcliffe-expediagroup! 

It would be great if you could expand this issue with some mockups and further context to get the discussions going as these UI changes tend to require quite a bit of discussions and iterations.

**Comment by tradcliffe-expediagroup** [comment]
@jhaals 
I have submitted a ticket with our UX team today and will get the UI mockups to you when they are ready. Thank you very much!

**Comment by tradcliffe-expediagroup** [comment]
Hello, my team has currently put this work on hold as we are going to be working with Spotify design team for a different Nav OSS contribution. I will update this ticket as I find out more information. Thank you.

**Comment by freben** [comment]
That sounds great! Thanks for reporting back.
