### ISSUE TITLE
Scaffolder: Hidden fields are not completely hidden

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#5833]
## Expected Behavior

Fields hidden with `ui:widget: hidden` should be invisible.

## Current Behavior

Hidden fields are hidden, but the wrapping grid is still displayed with its padding and margin taking up space.

<img width="789" alt="Bildschirmfoto 2021-05-27 um 10 13 48" src="https://user-images.githubusercontent.com/648527/119790807-8219b880-bed4-11eb-9438-5efb47c1f1c6.png">

## Possible Solution

One solution is to hide the grid item if `ui:widget: hidden` is used. Afaik to there is no way in CSS to select the parent of an element to hide it, so we actually can't create a workaround and have to fix the issue.

I guess this is actually a problem in the upstream `@rjsf/material-ui` package.

## Steps to Reproduce

Include a `ui:widget: hidden` in you template, the problem is even more visible if you add more than one.

```yaml
properties:
  mode:
    type: string
    enum:
    - create_repo
    ui:widget: hidden
```

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS
- Browser Information: Chrome

**Comment by Fox32** [comment]
This seems to be a known issue upstream https://github.com/rjsf-team/react-jsonschema-form/issues/1974

**Comment by Fox32** [comment]
I created a PR upstream https://github.com/rjsf-team/react-jsonschema-form/pull/2405

**Comment by Fox32** [comment]
Good news, my upstream PR is merged. I'm just not sure when it will arrive in a release.

**Comment by freben** [comment]
![image](https://user-images.githubusercontent.com/3097461/122077644-320b8300-cdfc-11eb-8909-651b44c47be4.png)

**Comment by cognizant-pooja** [comment]
conditionally add  ui:widget: hidden or  ui:widget: select based on some value ??
