### ISSUE TITLE
Improve debugging experience when stepping from app code into plugins

### ISSUE THREAD

**Issue by taras** [backstage/backstage#5840]
There was a report from [OlindaSpider](https://discord.com/channels/687207715902193673/687207715902193679/833048139689754654) in Discord about challenges debugging the app. 

## Expected Behavior

It should be easy for someone working on the Backstage frontend in their local instance of Backstage to step through their own code and into the code provided by plugins installed from NPM.

## Current Behavior

At the moment, something seems to be broken in that workflow. 

## Possible Solution

@jbolda and I are looking at Webpack config. 

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

**Comment by jbolda** [comment]
This was building on #5368 and #2785, and I believe we have it finally resolved in #5841.
