### ISSUE TITLE
Make results of scaffolder more visible

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#5848]
## Feature Suggestion

Right now, the result of the scaffolder are quite hidden and are limited to one external URL and one entity. I think, for the user the feedback that the job is completed is quite hidden.

![image](https://user-images.githubusercontent.com/648527/119967705-f162db80-bfac-11eb-8804-cb4d39b2c82f.png)

Actual, the "skipped" part is something I'm working on and not related to this issue.

## Possible Implementation

Implement a fullscreen page that displays the links, allow to place more than one link with title (+ icon) and allow to place text/markdown content too.

For example:

![image](https://user-images.githubusercontent.com/648527/119968386-b2815580-bfad-11eb-8cd5-d6567e03f738.png)

* On the left we always introduce a Completed/Result/Finish/Summary step that displays the results
* The user can still switch to the logs in the previous steps
* The finish page contains a visual element to show the user that the job is completed
* The finish page can be customized from the template, like passing a markdown text that tell the user about the next steps (e.g. checkout the repo to get started)
* If the markdown is generated by handlebars, you could actually skip the links feature and include them there (there could be a handlebars helper for entity links).
* Otherwise provide a customizable way of placing links or entity references with icon and title. Maybe you have multiple links to get started (e.g. linking to techdocs & the repo) or you output multiple components (a UI and a service?).

**Alternativ implementation:**

One could create a custom action that outputs these details in ASCII style with ASCII art 😆 into the log.

## Context

Another note: I noticed that the job can still fail outside of steps, e.g. if your output syntax is wrong (if you use handlebars there). You won't get any feedback in that case and even get green ticks at every step but now result. The finish page could also collect these errors that are outside the step.

**Comment by benjdlambert** [comment]
@katz95 do you think you could take a look at this and have any input on how we can make this flow a little nicer from a UX POV :)

**Comment by KatherineZhou** [comment]
Hi! Just to clarify, "for the user the feedback that the job is completed is quite hidden" --> is this feedback supposed to be shown in the "Results" page that's labeled 'skipped'? I'm trying to understand what those two links that you've circled have to do with the overall process! :)

**Comment by Fox32** [comment]
@KatherineZhou My screenshot is a bad example. There is no result page yet, I just had a step that was called result. Also ignore the "skipped" part.

But one solution could be a "Results" page at the end of the list that opens up a page on the right with more details. The two links that I have circled is the current way to show the result, now limited to links that link to the generated repositories or entities. I would move them to the results page and make them more visible. Here I could also imagine a bit more freedom to tell the user what has happened and what his next steps are (e.g. as markdown free text). 

This could also be a place to show error messages that happened outside of a step, e.g. while generating the outputs.

I hope this quick mock shows that a bit better than the arrows 😆 

![image](https://user-images.githubusercontent.com/648527/121525590-cfc81200-c9f8-11eb-99d7-fb5b095edb1b.png)

**Comment by Rugvip** [comment]
Wanna throw in that if we end up (re)designing the scaffolder task page we shouldn't forget to add in retries in some nice way. Probably being able to go back to the form with all values still filled in or something like that.

**Comment by Fox32** [comment]
Just as a quick update, we solved this for now with the `debug:log` action and have a step called "results" that has some ASCII art. Has some charm, but would still be interested in a built in solution 😆 

![image](https://user-images.githubusercontent.com/648527/122077399-ff618a80-cdfb-11eb-841a-9181f5b92036.png)

**Comment by KatherineZhou** [comment]
Sharing a potential design for the scaffolder! Let me know your thoughts. Changed the right hand view to just a normal confirmation view. Also using the [simple stepper component](https://backstage.io/storybook/?path=/story/navigation-simplestepper--default) for the wizard.

 ![Overview](https://user-images.githubusercontent.com/16808998/122783112-8f4a7d00-d2b1-11eb-9931-a13c9dd2b0e6.png)

**Comment by Fox32** [comment]
Does anyone know whether the background image is already available in Backstage? And where? I could give this a try.

**Comment by Fox32** [comment]
> @Fox32 Seems that it's been duplicated a few times in [pagerduty](https://github.com/backstage/backstage/blob/master/plugins/pagerduty/src/assets/emptystate.svg), [splunk](https://github.com/backstage/backstage/blob/master/plugins/splunk-on-call/src/assets/emptystate.svg), [kubernetes](https://github.com/backstage/backstage/blob/master/plugins/kubernetes/src/assets/emptystate.svg). 😅 Time to make it more general?

We could export them from core, together with the existing empty state images.

**Comment by benjdlambert** [comment]
@Fox32 maybe `@backstage/core-components` 👍  as `@backstage/core` is going :wave:

**Comment by regicsolutions** [comment]
@Fox32 were you ever able to get this working with the background @KatherineZhou provided?

**Comment by benjdlambert** [comment]
Think that this has been closed with the new design of the #16081  and the ability to provide your own `Outputs` component to the Router to display your own view.
