### ISSUE TITLE
apiBaseUrl is not considered in publish:bitbucket action in scaffolder-backend plugin

### ISSUE THREAD

**Issue by mrjerzy** [backstage/backstage#5851]
I am referring to an issue, which is very similar to https://github.com/backstage/backstage/issues/5577. It is related to the scaffolder-backend plugin.

In our company, we are running a self-hosted Bitbucket repository. It can be accessed via https://code.mycompany.com/bitbucket/. Therefore the base path for APIs is at https://code.mycompany.com/bitbucket/rest/api/1.0/ (note the /bitbucket/ in the path)

The Scaffolder Backend plugin communicates during execution via HTTP with our Bitbucket instance. Unfortunately, the plugin assumes that the API base path is https://code.mycompany.com/rest/api/1.0/, (without a possibility to add /bitbucket in its path). This leads to HTTP 404 during the creation of a new repository

Issue https://github.com/backstage/backstage/issues/5577 solved the problem inside the publisher, but it is also present within the actions - here: 
https://github.com/backstage/backstage/blob/2b5b5b54fc9f925ba36cde0a12f3140cd57b163e/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/bitbucket.ts#L113

## Expected Behavior

When the configuration file sets an `integrations.apiBaseUrl`, it should be considered inside the publish:bitbucket action. 

## Current Behavior

The bitbucket action uses the `integrations.host` configuration, which does not allow for custom API base URLs, as described above. 

## Possible Solution
Make a change, similar to https://github.com/backstage/backstage/issues/5577. 

I suggest two changes: 
1. Use `integrations.apiBaseUrl` when it is set in the configuration file
2. it is counter intuitive that the project name is taken from the ${owner} variable. You will notice in Steps to Reproduce that i need to provide an `owner` and `repo` query-parameter to make the action work. This is validated [here](https://github.com/backstage/backstage/blob/2b5b5b54fc9f925ba36cde0a12f3140cd57b163e/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/bitbucket.ts#L215), and will lead to a non-successful run when not present. I seems to me to be specific to other source-code repos different from bitbucket and should probably be changed. Maybe i just do something wrong (and documentation needs to be improved). 

Replace the current line: 
```diff
- response = await fetch(`https://${host}/rest/api/1.0/projects/${owner}/repos`, options, );
+ const baseUrl = this.config.apiBaseUrl ? this.config.apiBaseUrl : `https://${host}/rest/api/1.0`;
+ response = await fetch(`${baseUrl}/projects/${project}/repos`, options);
```

## Steps to Reproduce

Create a custom template. Add a step with action `publish:bitbucket`. Provide a repoURL which contains /bitbucket/ in its path. 

```
  - id: publish-application-repo
      name: Publish Application Code
      action: publish:bitbucket
      input:
        description: 'Initialized by Backstage'
        repoUrl: 'code.mycompany.com/bitbucket/projects/{{ parameters.bitucket_project }}/repos/{{ parameters.project_slug }}?owner={{ parameters.bitucket_project }}&repo={{ parameters.project_slug }}'
```

See Possible Solution, in case you wonder why there is an owner/repo query parameter. 

```
2021-05-28T13:35:10.176Z Beginning step Publish Application Code
2021-05-28T13:35:10.256Z Error: Unable to create repository, 404 Not Found, <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /></body></html>
    at createBitbucketServerRepository (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:1695:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.handler (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:1770:44)
    at async TaskWorker.runOneTask (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2469:11)
    at async /app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2404:9
```

## Context

I am not able to instantiate templates using the publish:bitbucket action, with a self-hosted Bitbucket server with a customised api-base-path

## Your Environment

Docker container, based on node:14

**Comment by benjdlambert** [comment]
@mrjerzy is this something you want to contribute? 👍

**Comment by mrjerzy** [comment]
Unfortunately my Typescript skills will not allow it.

**Comment by djamaile** [comment]
I would like to pick this up

**Comment by benjdlambert** [comment]
Assigned! Go for it 👍
