### ISSUE TITLE
Documentation for built in `ui:fields` for Scaffolder

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#5883]
## Feature Suggestion
Document the provided built in `ui:fields` for the schema form with corresponding `parameters` yaml examples.

`OwnerPicker` `RepoUrlPicker` `EntityPicker`. And their props which can be used with `ui:options`.

Some sample usages would be good.

**Comment by Parsifal-M** [comment]
Hey, I'd like to help with this :wave: 

Where would be the best place to start?

Thanks!

**Comment by benjdlambert** [comment]
Hey :wave: I'd recommend starting a new page on the microsite, take a look at the `docs/features/software-templates` folder and create another markdown file in there that can house this documentation. I'd like to see examples for the `RepoUrlPicker` and maybe the `EntityPicker` as a start. I'd like to see an example of some `yaml` with some examples of the different `ui:options` that you can pass in?

Does that work?

**Comment by Parsifal-M** [comment]
Sounds good, will take a look! You can assign to me if you like.

**Comment by benjdlambert** [comment]
Perfect! Thanks! Assigned! 👍

**Comment by jhaals** [comment]
@Parsifal-M any update on this? Not sure if it's taken care of already

**Comment by Parsifal-M** [comment]
Hey, sorry will have to drop for now, I made a start but got snowed under all of a sudden and I kind of forgot about it :fearful: 

I will keep an eye on it, if no-one picks it up I will continue on it in the background :smile:

**Comment by Rugvip** [comment]
@Parsifal-M no worries, thank you for letting us know! 👍

**Comment by GyaniRoman23** [comment]
@Rugvip @benjdlambert Could I work on this issue as its still open?

**Comment by jhaals** [comment]
Yes you can @GyaniRoman23! 👍

**Comment by benjdlambert** [comment]
@GyaniRoman23 any update on this? :pray:

**Comment by floresjma** [comment]
Hi 👋, I'd like to contribute to this if it's open and not assigned?
Thank you

**Comment by benjdlambert** [comment]
Hey @floresjma please do! I will assign you :pray: thanks!

**Comment by floresjma** [comment]
Would love to hear your feedback, and thanks again for giving me the chance to do my first contribution :)

**Comment by benjdlambert** [comment]
Going to close this as fixed for now, but let's treat this as a living document and new additions to the FieldExtension collections should be updated here too..
