### ISSUE TITLE
@items.visibility throws errors in config schema file

### ISSUE THREAD

**Issue by althafh** [backstage/backstage#5912]
## Expected Behavior

Previously our plugin had a config.d.ts file as below

```
export interface Config {
  'mrt-plugin': {
    /** @items.visibility frontend */
    superusers: string[];
  };
}

```
This worked fine but updating to release-2021-05-27 seems to break the validation with following error 

```
$ backstage-cli app:build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
strict mode: "items" is 1-tuple, but minItems or maxItems/additionalItems are not specified or different
Error: Schema at <plugin-path>/config.d.ts is invalid, Error: strict mode: unknown keyword: "text"
```

## Possible Solution
Based on @freben's suggestion on discord this patch might need to be extended to items.visibility as well 
https://github.com/backstage/backstage/commit/438a512ebb91228b53d591cca8900973163404da

Happy to put in a fix if this is indeed the correct solution

**Comment by freben** [comment]
Would you like to be assigned and give it a shot? It'd be great if you could, since you already have the error repro present

**Comment by freben** [comment]
@Rugvip

**Comment by althafh** [comment]
I was attempting to replicate this yesterday on a copy of the backstage repository but was unable to do and was a bit stumped. (Still unclear why it doesn't replicate)
Today however I created a fresh app using create-app and then created a new plugin in that fresh app and added the above config and was able to replicate it. 

However now I'm unclear how I would test if my change actually works. That is how do I get the config:check command to use my local changes.

**Comment by althafh** [comment]
Thanks @Rugvip
