### ISSUE TITLE
[Scaffolder] removes executable permission on unzipped files

### ISSUE THREAD

**Issue by goober** [backstage/backstage#5918]
## Current behaviour
We have a cookiecutter template with gradle wrapper executables `gradlew` and `gradlew.bat`. They are marked as executables in our repository and if we download the repository archive as a zip and extract it manually the executable permission is there. However, when we run through Backstage and the scaffolder the resulting generated repository contains the expected files, but without the executable file permission, meaning that we need to manually change the file permissions afterwards.

## Possible Solution

I can see that Backstage is using the unzipper package to unzip the downloaded template archive from the source respository. There is an open issue in that library that clearly states that the does not preserve the file permissions on the extracted files: https://github.com/ZJONSSON/node-unzipper/issues/216

Downloading the archive as a Gzipped Tar file instead of a zip file will solve the issue for Bitbucket.
## Steps to Reproduce

1. Create a cookiecutter template with a file that has the executable file permission set (`chmod +x testfile`)
2. Publish it to your VCS and import it to backstage.
3. Create a new project from the newly created cookiecutter template

Expected result: The file `testfile` should have the executable permission set in the newly created repository

Actual result: The file `testfile` exists in the newly created repository but does not have the executable permission set.

## Your Environment

- NodeJS Version (v14): v14
- Operating System and Version (e.g. Ubuntu 14.04): OSX locally or RHEL 8 in our production environment
- Browser Information: Chrome
- Version Control System: Bitbucket Server

**Comment by freben** [comment]
I see you already addressed this, assigned nonetheless for completeness :)

**Comment by benjdlambert** [comment]
@goober going to close this, please re-open if you think it's needed
