### ISSUE TITLE
[Scaffolder] [Meta issue] Templating engine improvements

### ISSUE THREAD

**Issue by freben** [backstage/backstage#5919]
Covers some improvements to the templating engines in scaffolder to make non-Node.js dependencies optional (e.g. Python, cookiecutter) and to standardize templating syntax across Software Templates.

- [x] #6285
- [x] #6286 
- [x] https://github.com/backstage/backstage/issues/6437
- [x] https://github.com/backstage/backstage/issues/6415

## Context

[Software Templates](https://backstage.io/docs/features/software-templates/software-templates-index) currently use [Jinja2](https://pypi.org/project/Jinja2/) syntax for files in the templates. [Cookiecutter](https://github.com/cookiecutter/cookiecutter) is a python-based CLI which is used in the [`fetch:cookiecutter`](https://backstage.io/docs/features/software-templates/builtin-actions) task to generate components from these templates. Since there are no alternatives to cookiecutter, Python is a hard requirement to use Software Templates. This ultimately results in complex Dockerfiles like [these](https://github.com/backstage/backstage/blob/112fd4ddb36057065f43a83037bbf363b1cc474a/contrib/docker/kubernetes-example-backend/Dockerfile#L5-L11)

The first experience of adopters is marred by having to install the cookiecutter cli. There’s a [docker image](https://hub.docker.com/r/spotify/backstage-cookiecutter) that can help, but it’s still far from a `yarn install && yarn dev` experience.

In order to make things simpler for adopters, we can look to add a new templating system which runs purely in Node.js. We’ll keep the `fetch:cookiecutter` action for backwards compatibility but use our new action in the built-in [sample templates](https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates). Folks that want to use cookiecutter will still need to ensure the CLI is available in their environment, but for anyone who isn’t using it, it won’t need to be set up.

**Comment by goober** [comment]
Have you looked at the possibilities to support [yeoman](https://yeoman.io/) as the default scaffolder engine? Since it is a node based tool it could be a good fit.

**Comment by freben** [comment]
That is indeed a fine engine. I think we'll not have a default one though, per se - the endgame is to support a wide variety of template engines without any particular preference. We just got started with cookiecutter (we use that one a lot internally), and people who use that should be able to get going with as little friction as possible.

**Comment by andrewthauer** [comment]
https://plopjs.com/ is another possible option.

**Comment by kiranpatel11** [comment]
any CRUFT equivalent for node-based template engine ?

see context #5955

**Comment by benjdlambert** [comment]
@kiranpatel11 we probably wouldn't support that out of the box, but it's maybe something that we could consider further down the line.
