### ISSUE TITLE
Scaffolder: Provide link to template source

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#5946]
## Feature Suggestion

In our organization, we want to give teams the options to contribute and improve our templates. Or to use them as a blueprint to start a new template. For that it would be useful, if the teams can easily discover the source code of the available templates.

Right now, neither the template overview page, nor the template details page provides a link to the template location (e.g. based on `backstage.io/source-location` or `backstage.io/view-url`).

## Possible Implementation

The header on the details page of a template could include a link to the source code defined by `backstage.io/source-location`.

**Comment by timbonicus** [comment]
Makes sense! We have this internally at Spotify, on both the card when choosing a template, and header of the template once chosen:

![create-card](https://user-images.githubusercontent.com/556258/121084982-8aa8a380-c79e-11eb-8a71-b9ca48f43b0d.png)

![template-header](https://user-images.githubusercontent.com/556258/121085009-92684800-c79e-11eb-80e8-fb45e6563660.png)
