### ISSUE TITLE
Scaffolder: action for cruft templater

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#5955]
Have [CRUFT](https://github.com/cruft/cruft) as one of the scaffolder action, so that templates evolution can be better managed and retrofitted in already scaffolded projects.

## Feature Suggestion
Cruft action can either be added to built-in actions or can be added to contrib folder.

## Possible Implementation
We already have implemented custom action using CRUFT, need feedback on where it should be contributed - built-in or contrib folder.

## Context

Backstage include cookie-cutter, create-react-app as default templating engines. The usual challenges with these code-generators is to keep the already scaffolded projects current when code-generator templates evolve over a period.

Cruft solves that problem by providing ability to check differences against latest version of the template, and update new changes in automated way much like git-merge or shows diff when conflicts.

Another advantage in favor of Cruft is - It is compatible with cookie-cutter templates, as it is technically a wrapper utility on cookie-cutter only.

References: 
https://github.com/cruft/cruft#why-create-cruft
https://github.com/cookiecutter/cookiecutter/issues/784

**Comment by Rugvip** [comment]
Thank you for the suggestion!

Perhaps we could move forward with draft PR that adds it in whatever way is easiest for you? Just to get and understanding of how it's set up and where it would best fit in.

**Comment by regicsolutions** [comment]
Agreed! Cruft is an excellent Add-on to cookiecutter 🍪
