### ISSUE TITLE
[Contrib] Lack of permissions prevents inject-config.sh entrypoint to execute

### ISSUE THREAD

**Issue by manusant** [backstage/backstage#5956]
The docker files provided for the frontend app as a separated deployment using Nginx uses a **inject-config.sh** script that is ignored because of lack of permissions.

 ## Affected files:
* [frontend-with-nginx/Dockerfile.hostbuild)](https://github.com/backstage/backstage/blob/master/contrib/docker/frontend-with-nginx/Dockerfile.hostbuild)
* [frontend-with-nginx/Dockerfile.dockerbuild](https://github.com/backstage/backstage/blob/master/contrib/docker/frontend-with-nginx/Dockerfile.dockerbuild)

## Expected Behavior
When running backstage frontend app as a separated deployment and providing environment variables override (variables with prefix **APP_CONFIG_**) this variables should be read and binded to App environment as shown in the nginx logs below:

![Screenshot 2021-06-08 at 12 29 45](https://user-images.githubusercontent.com/12997676/121177400-40cec480-c855-11eb-9a64-86c4b8251ce2.png)

## Current Behavior
But with the current DockerFiles the **inject-config.sh** entrypoint script is ignored as shown below:
![Screenshot 2021-06-08 at 12 35 04](https://user-images.githubusercontent.com/12997676/121178158-1f220d00-c856-11eb-8f73-b64a1c7339cc.png)

## Possible Solution
Applying permissions to the *inject-config.sh** entrypoint script solves the issue:
```sh
COPY docker/inject-config.sh /docker-entrypoint.d/40-inject-config.sh
RUN ["chmod", "+x", "/docker-entrypoint.d/40-inject-config.sh"]
```

## Context
This issues shows up while i'm trying to provide a production deployment of backstage where the backend and frontend are deployed independently using Docker + Kubernetes. This is being accomplished using Dockerfile provided with backstage for the backend part and Dockerfiles provided at **backstage/contrib/docker/frontend-with-nginx** for the frontend.

**Comment by Rugvip** [comment]
What build environment are you using?

The `inject-config.sh` file in contrib is marked as executable and ends up being executable inside the container as well. Did you perhaps copy the contents of the file rather than the file itself?

**Comment by manusant** [comment]
Hi and thanks for your feedback.
Now that you stated it i've probably copied the content... but sounds a good idea to assign the permissions from the docker file itself.

**Comment by Rugvip** [comment]
Haven't seen `chmod +x` used in docker images much, and looking at a couple of different official images they don't use it either, e.g. [couchbase](https://github.com/couchbase/docker/blob/5929be778eb5306f116f71cc9a0a23fea6d9a7aa/enterprise/couchbase-server/7.0.0-beta/Dockerfile#L66) and [redis](https://github.com/docker-library/redis/blob/4422738bea4a9d38971a87fc820525864bb5ff62/6.2/Dockerfile#L116). I think it's best to avoid the extra layer and keep as is.
