### ISSUE TITLE
[Plugin] Bazaar

### ISSUE THREAD

**Issue by lykkeaxlin** [backstage/backstage#5963]
## Summary

As a Lund Summer of Code project at @AxisCommunications,  me and @klaraab are working on a plugin for announcing new project ideas. The main idea is to enable cross team cooperation within companies by creating a marketplace for internal projects suitable for inner sourcing.

The Bazaar overview will show up on the backstage homepage and display the latest project ideas:

![Screenshot from 2021-06-08 13-39-01](https://user-images.githubusercontent.com/46992305/121178585-ecc8dd80-c85e-11eb-9d28-794899a69842.png)

The view all button will take you to a catalog with all the Bazaar projects, similar to the backstage catalog.

The project page will display overall information and a promotion card:

![Screenshot from 2021-06-08 13-51-53](https://user-images.githubusercontent.com/46992305/121180094-c015c580-c860-11eb-9ba6-4af7a1dd2fb3.png)

The plugin will include a template for creating a Bazaar project.

We have a few questions about how to proceed:
* Where do you prefer that we put our code? We are currently working on a fork
* Does anybody want to join? 

Feedback and suggestions are much appreciated! :smile:

**Comment by Rugvip** [comment]
Hi, thank you for the information!

There's a bit of overlap with the [explore plugin](https://github.com/backstage/backstage/tree/master/plugins/explore), but if the intention that this is a user-curated list of projects I can see that it's different enough to need its own thing. It could potentially be useful to make the list of projects browsable via the explore plugin though. We actually also have something similar internally but more tailored towards opportunities in working in different teams rather than bootstrapping projects.

As for where to put the code, the most important thing is that wherever you have it you make sure that it's nicely contained within one or a few plugins, with that it'll be easy to move around. Beyond that it's mostly up to you whether you want to put it in your own repo with separate publishing and licensing, or in the main repo. If you want to request it to be added to the main repo, also be sure to leave time for going back and for with reviews a bit.

**Comment by andrewthauer** [comment]
Extending on what @Rugvip said, the explore plugin could be used as a place to host content that is either from another plugin or something internal to your org.

I created #6025 a couple days ago that allows the explore plugins tabs to be customized and extended. If this bazar/innersource explorer were component with a plugin it could be easily mounted on a `/explore/bazar` route.

**Comment by klaraab** [comment]
Thank you both for the input! 

Integrating bazaar into the explore plugin is an interesting idea. Are the components shown in the explore plugin fetched from the catalog? 

@Rugvip We want the projects shown in the bazaar preview for example to be the latest projects or projects that is in need of some extra visibility. 

We would like the code to be added to the main repo. How does the procedure for that look?  

@andrewthauer  regarding the inner source annotation, I’m not sure what you mean. Do you mean that projects in the Bazaar would be represented as regular backstage components tagged with ‘bazaar’? Meaning that it wouldn’t need its own template?  

And do you know where we can find out more about the inner sourcing marketplace Github has been working on?  

Also, looking at your PR it seems like you’re also working on something related to inner sourcing. Are you only working on the customizable tab feature, or are you also planning to add content to display inner sourcing projects?

**Comment by andrewthauer** [comment]
> We would like the code to be added to the main repo. How does the procedure for that look?
> 
> @andrewthauer regarding the inner source annotation, I’m not sure what you mean. Do you mean that projects in the Bazaar would be represented as regular backstage components tagged with ‘bazaar’? Meaning that it wouldn’t need its own template?

I was thinking this could introduce a well known catalog file annotation that can then be queried against. Any repo/source code that wants to be considered as innersource would add something like:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: some-internal-library
  annotations:
    innersourcecommons.org/enable: featured 
```

> And do you know where we can find out more about the inner sourcing marketplace Github has been working on?
> 
> Also, looking at your PR it seems like you’re also working on something related to inner sourcing. Are you only working on the customizable tab feature, or are you also planning to add content to display inner sourcing projects?

**Comment by julioz** [comment]
Can this issue be closed?

**Comment by freben** [comment]
@lykkeaxlin @klaraab closing this now since it's in place for some time and has evolved a couple steps as well, let me know if that's the wrong decision!
