### ISSUE TITLE
Upgradeable template

### ISSUE THREAD

**Issue by paulpach** [backstage/backstage#597]
If I generate an app with the cli,  I should be able to upgrade it with the latest template.  That way I can keep up with development of backstage.

## Feature Suggestion

Suppose I generate an app:
```sh
backstage-cli create-app
```
I would then proceed to add a few plugins to it and customize it.

I would like to be able to upgrade my app with the latest development from backstage.  For example:
```
backstage-cli upgrade
```

## Possible Implementation

A possible way to implement it is that the generated app contains very minimal code,  basically an App.tsx that would load a "Backstage" component with my list of plugins and whatever configuration I might need. 

Something along the lines of:

```js
const App: FC<{}> = () => 
  <Backstage
       title="MyApp"
       theme="myTheme"
       plugins={[plugin1, plugin2, plugin3]} />

export default App;
```

Notice I don't worry about sidebar, or header or anything like that,  that would be part of the <Backstage> core component which would be upgraded with the backstage packages.

A user that wants more control, would not use `<Backstage>`. but create their own component, which would not be upgradable.

when we invoke 
```
backstage-cli upgrade
```

It would simply upgrade backstage in package.json.

## Context

Create my backstage app instance and keep it up to date with upstream backstage.

The idea was proposed in discord, and I was asked to put it here for discussion.

The example app would ideally use this component too,  so it is always in sync with the cli generated apps.

**Comment by freben** [comment]
(Made a minor edit only to add backquotes to the `<Backstage>` tag.)

Thanks! This is definitely on our minds too. We need to find a balance and nice structure to the app to make it easy to stay up to date with the latest developments.

About the sidebar specifically, I think that's one piece that one wants to have customisable. Even so, that could be done with JSX as well:

```
const Sidebar = (
  <Sidebar>
    <SidebarLogo />
    <SidebarSpacer />
    <SidebarDivider />
    <SidebarItem icon={HomeIcon} to="/" text="Home" />
    ...
  </Sidebar>
);

return (
  <Backstage
      sidebar={sidebar}
      ...
);
```

and still those components are just imported from core and part of the contract/API for how to make sidebars.

We could also discuss the granularity of the `Backstage` item - whether it could be broken apart into `Application`, `PluginProvider`, `SidebarArea`, `ContentArea` or whatever. Maybe it'll be up to you whether to use the smooth superwrapper, or to "eject" and explode it into its constituent parts to get even more flexibility. It could still all be in `App.tsx`.

**Comment by Rugvip** [comment]
Work towards this: https://github.com/spotify/backstage/pull/702

**Comment by adamdmharvey** [comment]
Additional work in terms of Backstage CLI commands `versions:check` and `versions:bump` were implemented as well, and are documented here:

https://backstage.io/docs/FAQ#how-do-i-keep-my-backstage-app-up-to-date
https://backstage.io/docs/cli/commands#versionsbump

In addition, the CHANGELOGs published for apps using `yarn changeset`, any upgrade needs are documented and consolidated.

I have a feeling the **need** described here in this issue is now addressed, with further work and newer stories able to continue refactoring.

Propose this could be closed - others?

**Comment by OrkoHunter** [comment]
`versions:bump` is a really good one I think. One day I was thinking that "how to upgrade backstage app" should result in a Stackoverflow question, where this CLI command is the accepted answer.
