### ISSUE TITLE
Scaffolding failing on @gitbeaker dependency

### ISSUE THREAD

**Issue by grumpyoldman-io** [backstage/backstage#5980]
After running the `npx @backstage/create-app`, starting the app in dev mode `yarn dev` I'm confronted with an error

## Expected Behavior

The app will start correctly

## Current Behavior

I'm confronted with a dependency error after successfully running the `npx @backstage/create-app` command and starting either the app in dev mode `yarn dev` or just the backend `yarn start-backend`

```
Error: Cannot find module '/xxx/backstage/node_modules/@backstage/plugin-scaffolder-backend/node_modules/@gitbeaker/node/dist/index.js'. Please verify that the package.json has a valid "main" entry
[1]     at tryPackage (internal/modules/cjs/loader.js:303:19)
[1]     at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
[1]     at Module.require (internal/modules/cjs/loader.js:952:19)
[1]     at require (internal/modules/cjs/helpers.js:88:18)
[1]     at Object.<anonymous> (/xxx/backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:16:12)
[1]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[1]     at Module.load (internal/modules/cjs/loader.js:928:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[1]     at Module.require (internal/modules/cjs/loader.js:952:19)
[1]     at require (internal/modules/cjs/helpers.js:88:18)
[1]     at eval (webpack-internal:///@backstage/plugin-scaffolder-backend:1:18)
[1]     at Object.@backstage/plugin-scaffolder-backend (/xxxx/backstage/packages/backend/dist/main.js:1035:1)
[1]     at __webpack_require__ (/xxx/backstage/packages/backend/dist/main.js:749:30) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   path: '/xxx/Platform/backstage/node_modules/@backstage/plugin-scaffolder-backend/node_modules/@gitbeaker/node/package.json',
[1]   requestPath: '@gitbeaker/node'
```

## Steps to Reproduce

1. `npx @backstage/create-app`
2. follow wizard (use sqlite)
3. `cd project-name`
4. `yarn dev`

## Your Environment

- NodeJS Version (v12): lts/fermium
- Operating System and Version (e.g. Ubuntu 14.04): MacOS (m1)
- Browser Information: N.A.

**Comment by Fox32** [comment]
Related #5977

**Comment by freben** [comment]
Yep, closed as duplicate. The next release with the fix is tomorrow. Let us know in the linked discussion if the short term fix doesn't work out for you.

**Comment by grumpyoldman-io** [comment]
@freben the linked issue is indeed a fix for now.

```
"resolutions": {
    "**/@gitbeaker/node": "29.2.4",
    "**/@gitbeaker/core": "29.2.4",
    "**/@gitbeaker/requester-utils": "29.2.4"
  }
```

**Comment by 5-k** [comment]
This is still the issue with latest react create, Node version 18

```
Now using node v18.18.2 (npm v9.8.1)
pmishra7@HCFGQJ690V hackathon-24 % npx @backstage/create-app@latest


? Enter a name for the app [required] backstage

Creating the app...

 Checking if the directory is available:
  checking      backstage ✔ 

 Creating a temporary app directory:

 Preparing files:
  copying       .dockerignore ✔ 
  templating    .eslintrc.js.hbs ✔ 
  templating    .gitignore.hbs ✔ 
  copying       .prettierignore ✔ 
  copying       README.md ✔ 
  copying       app-config.local.yaml ✔ 
  copying       .eslintignore ✔ 
  copying       app-config.production.yaml ✔ 
  templating    app-config.yaml.hbs ✔ 
  templating    backstage.json.hbs ✔ 
  templating    catalog-info.yaml.hbs ✔ 
  copying       playwright.config.ts ✔ 
  copying       tsconfig.json ✔ 
  copying       yarn.lock ✔ 
  templating    package.json.hbs ✔ 
  copying       lerna.json ✔ 
  copying       README.md ✔ 
  copying       entities.yaml ✔ 
  copying       org.yaml ✔ 
  copying       template.yaml ✔ 
  copying       catalog-info.yaml ✔ 
  copying       index.js ✔ 
  copying       package.json ✔ 
  copying       README.md ✔ 
  templating    .eslintrc.js.hbs ✔ 
  copying       Dockerfile ✔ 
  copying       README.md ✔ 
  templating    package.json.hbs ✔ 
  copying       index.ts ✔ 
  copying       types.ts ✔ 
  copying       index.test.ts ✔ 
  copying       auth.ts ✔ 
  copying       app.ts ✔ 
  copying       catalog.ts ✔ 
  copying       proxy.ts ✔ 
  copying       scaffolder.ts ✔ 
  templating    search.ts.hbs ✔ 
  copying       techdocs.ts ✔ 
  copying       .eslintignore ✔ 
  templating    .eslintrc.js.hbs ✔ 
  templating    package.json.hbs ✔ 
  copying       app.test.ts ✔ 
  copying       android-chrome-192x192.png ✔ 
  copying       apple-touch-icon.png ✔ 
  copying       favicon-16x16.png ✔ 
  copying       favicon-32x32.png ✔ 
  copying       favicon.ico ✔ 
  copying       manifest.json ✔ 
  copying       index.html ✔ 
  copying       robots.txt ✔ 
  copying       safari-pinned-tab.svg ✔ 
  copying       App.test.tsx ✔ 
  copying       App.tsx ✔ 
  copying       apis.ts ✔ 
  copying       setupTests.ts ✔ 
  copying       index.tsx ✔ 
  copying       LogoFull.tsx ✔ 
  copying       LogoIcon.tsx ✔ 
  copying       index.ts ✔ 
  copying       Root.tsx ✔ 
  copying       EntityPage.tsx ✔ 
  copying       SearchPage.tsx ✔ 

 Moving to final location:
  moving        backstage ✔ 
  init          git repository ◜ 
 Installing dependencies:
  init          git repository ✔ 
  determining   yarn version ✔ 
  executing     yarn install ✔ 
  executing     yarn tsc ✔ 

🥇  Successfully created backstage


 All set! Now you might want to:
  Run the app: cd backstage && yarn dev
  Set up the software catalog: https://backstage.io/docs/features/software-catalog/configuration
  Add authentication: https://backstage.io/docs/auth/

pmishra7@HCFGQJ690V hackathon-24 % cd backstage 
pmishra7@HCFGQJ690V backstage % ls
README.md			app-config.yaml			dist-types			node_modules			playwright.config.ts		yarn.lock
app-config.local.yaml		backstage.json			examples			package.json			plugins
app-config.production.yaml	catalog-info.yaml		lerna.json			packages			tsconfig.json
pmishra7@HCFGQJ690V backstage % yarn dev
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace backend start
$ yarn workspace app start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/pmishra7/Documents/repos/hackathon-24/backstage/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] node:internal/modules/cjs/loader:1098
[1]   const err = new Error(`Cannot find module '${request}'`);
[1]               ^
[1] 
[1] Error: Cannot find module '/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/@gitbeaker/rest/dist/index.js'
[1]     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1098:15)
[1]     at finalizeEsmResolution (node:internal/modules/cjs/loader:1091:15)
[1]     at resolveExports (node:internal/modules/cjs/loader:567:14)
[1]     at Module._findPath (node:internal/modules/cjs/loader:636:31)
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
[1]     at a._resolveFilename (/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/tsx/dist/cjs/index.cjs:1:1729)
[1]     at Module._load (node:internal/modules/cjs/loader:922:27)
[1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[1]     at require (node:internal/modules/cjs/helpers:119:18)
[1]     at Object.<anonymous> (/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/@backstage/plugin-scaffolder-backend-module-gitlab/dist/index.cjs.js:9:12)
[1]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[1]     at Object.S (/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/tsx/dist/cjs/index.cjs:1:1292)
[1]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[1]     at Module._load (node:internal/modules/cjs/loader:960:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[1]     at require (node:internal/modules/cjs/helpers:119:18) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   path: '/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/@gitbeaker/rest/package.json'
[1] }
[1] 
[1] Node.js v18.18.2
[0] webpack compiled successfully
^C[0] <i> [webpack-dev-server] Gracefully shutting down. To force exit, press ^C again. Please wait...

pmishra7@HCFGQJ690V backstage % [1] yarn start-backend exited with code SIGINT
[0] yarn start exited with code SIGINT
nvm ^C
pmishra7@HCFGQJ690V backstage % npm --version
9.8.1
pmishra7@HCFGQJ690V backstage % node --version
v18.18.2
```

**Comment by juvi07** [comment]
> This is still the issue with latest react create, Node version 18
> 
> ```
> Now using node v18.18.2 (npm v9.8.1)
> pmishra7@HCFGQJ690V hackathon-24 % npx @backstage/create-app@latest
> 
> 
> ? Enter a name for the app [required] backstage
> 
> Creating the app...
> 
>  Checking if the directory is available:
>   checking      backstage ✔ 
> 
>  Creating a temporary app directory:
> 
>  Preparing files:
>   copying       .dockerignore ✔ 
>   templating    .eslintrc.js.hbs ✔ 
>   templating    .gitignore.hbs ✔ 
>   copying       .prettierignore ✔ 
>   copying       README.md ✔ 
>   copying       app-config.local.yaml ✔ 
>   copying       .eslintignore ✔ 
>   copying       app-config.production.yaml ✔ 
>   templating    app-config.yaml.hbs ✔ 
>   templating    backstage.json.hbs ✔ 
>   templating    catalog-info.yaml.hbs ✔ 
>   copying       playwright.config.ts ✔ 
>   copying       tsconfig.json ✔ 
>   copying       yarn.lock ✔ 
>   templating    package.json.hbs ✔ 
>   copying       lerna.json ✔ 
>   copying       README.md ✔ 
>   copying       entities.yaml ✔ 
>   copying       org.yaml ✔ 
>   copying       template.yaml ✔ 
>   copying       catalog-info.yaml ✔ 
>   copying       index.js ✔ 
>   copying       package.json ✔ 
>   copying       README.md ✔ 
>   templating    .eslintrc.js.hbs ✔ 
>   copying       Dockerfile ✔ 
>   copying       README.md ✔ 
>   templating    package.json.hbs ✔ 
>   copying       index.ts ✔ 
>   copying       types.ts ✔ 
>   copying       index.test.ts ✔ 
>   copying       auth.ts ✔ 
>   copying       app.ts ✔ 
>   copying       catalog.ts ✔ 
>   copying       proxy.ts ✔ 
>   copying       scaffolder.ts ✔ 
>   templating    search.ts.hbs ✔ 
>   copying       techdocs.ts ✔ 
>   copying       .eslintignore ✔ 
>   templating    .eslintrc.js.hbs ✔ 
>   templating    package.json.hbs ✔ 
>   copying       app.test.ts ✔ 
>   copying       android-chrome-192x192.png ✔ 
>   copying       apple-touch-icon.png ✔ 
>   copying       favicon-16x16.png ✔ 
>   copying       favicon-32x32.png ✔ 
>   copying       favicon.ico ✔ 
>   copying       manifest.json ✔ 
>   copying       index.html ✔ 
>   copying       robots.txt ✔ 
>   copying       safari-pinned-tab.svg ✔ 
>   copying       App.test.tsx ✔ 
>   copying       App.tsx ✔ 
>   copying       apis.ts ✔ 
>   copying       setupTests.ts ✔ 
>   copying       index.tsx ✔ 
>   copying       LogoFull.tsx ✔ 
>   copying       LogoIcon.tsx ✔ 
>   copying       index.ts ✔ 
>   copying       Root.tsx ✔ 
>   copying       EntityPage.tsx ✔ 
>   copying       SearchPage.tsx ✔ 
> 
>  Moving to final location:
>   moving        backstage ✔ 
>   init          git repository ◜ 
>  Installing dependencies:
>   init          git repository ✔ 
>   determining   yarn version ✔ 
>   executing     yarn install ✔ 
>   executing     yarn tsc ✔ 
> 
> 🥇  Successfully created backstage
> 
> 
>  All set! Now you might want to:
>   Run the app: cd backstage && yarn dev
>   Set up the software catalog: https://backstage.io/docs/features/software-catalog/configuration
>   Add authentication: https://backstage.io/docs/auth/
> 
> pmishra7@HCFGQJ690V hackathon-24 % cd backstage 
> pmishra7@HCFGQJ690V backstage % ls
> README.md			app-config.yaml			dist-types			node_modules			playwright.config.ts		yarn.lock
> app-config.local.yaml		backstage.json			examples			package.json			plugins
> app-config.production.yaml	catalog-info.yaml		lerna.json			packages			tsconfig.json
> pmishra7@HCFGQJ690V backstage % yarn dev
> yarn run v1.22.19
> $ concurrently "yarn start" "yarn start-backend"
> $ yarn workspace backend start
> $ yarn workspace app start
> $ backstage-cli package start
> $ backstage-cli package start
> [0] Loaded config from app-config.yaml
> [0] <i> [webpack-dev-server] Project is running at:
> [0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
> [0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/pmishra7/Documents/repos/hackathon-24/backstage/packages/app/public' directory
> [0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
> [0] <i> [webpack-dev-middleware] wait until bundle finished: /
> [1] node:internal/modules/cjs/loader:1098
> [1]   const err = new Error(`Cannot find module '${request}'`);
> [1]               ^
> [1] 
> [1] Error: Cannot find module '/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/@gitbeaker/rest/dist/index.js'
> [1]     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1098:15)
> [1]     at finalizeEsmResolution (node:internal/modules/cjs/loader:1091:15)
> [1]     at resolveExports (node:internal/modules/cjs/loader:567:14)
> [1]     at Module._findPath (node:internal/modules/cjs/loader:636:31)
> [1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
> [1]     at a._resolveFilename (/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/tsx/dist/cjs/index.cjs:1:1729)
> [1]     at Module._load (node:internal/modules/cjs/loader:922:27)
> [1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
> [1]     at require (node:internal/modules/cjs/helpers:119:18)
> [1]     at Object.<anonymous> (/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/@backstage/plugin-scaffolder-backend-module-gitlab/dist/index.cjs.js:9:12)
> [1]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
> [1]     at Object.S (/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/tsx/dist/cjs/index.cjs:1:1292)
> [1]     at Module.load (node:internal/modules/cjs/loader:1119:32)
> [1]     at Module._load (node:internal/modules/cjs/loader:960:12)
> [1]     at Module.require (node:internal/modules/cjs/loader:1143:19)
> [1]     at require (node:internal/modules/cjs/helpers:119:18) {
> [1]   code: 'MODULE_NOT_FOUND',
> [1]   path: '/Users/pmishra7/Documents/repos/hackathon-24/backstage/node_modules/@gitbeaker/rest/package.json'
> [1] }
> [1] 
> [1] Node.js v18.18.2
> [0] webpack compiled successfully
> ^C[0] <i> [webpack-dev-server] Gracefully shutting down. To force exit, press ^C again. Please wait...
> 
> pmishra7@HCFGQJ690V backstage % [1] yarn start-backend exited with code SIGINT
> [0] yarn start exited with code SIGINT
> nvm ^C
> pmishra7@HCFGQJ690V backstage % npm --version
> 9.8.1
> pmishra7@HCFGQJ690V backstage % node --version
> v18.18.2
> ```

Hey @5-k I just tried a fresh install using the `npx @backstage/create-app@latest` on node `v18.18.0 ` and npm `9.8.1` and did not encounter this issue. I suggest you check your env setup.

**Comment by 5-k** [comment]
Yes now this is not longer an issue after the fix. Thanks everyone for the quick response and helping fix this. Cheers
