### ISSUE TITLE
Authentication for multiple users

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#5996]
Hi, I am wondering if there is any way to do authentication for multiple users. I am currently using GHE authentication, but in the app-config.yaml, only configured one user, it means only the developer can log in. Actually, Backstage will be putting in use in our company, I need to allow all users can sign in using their GHE account.

Is there any way for users to log in on the SignIn Page using their GHE account, not only developer?

**Comment by timbonicus** [comment]
Yes, definitely! If you have [GHE authentication](https://backstage.io/docs/auth/github/provider) already configured, then anyone with a GHE account on that host should be able to login using this authentication provider.

To make sure their user account has full details including groups they are a member of, you'll want to set up [Github org data](https://backstage.io/docs/integrations/github/org) ingestion. Does that help?

**Comment by chuliang014** [comment]
> Yes, definitely! If you have [GHE authentication](https://backstage.io/docs/auth/github/provider) already configured, then anyone with a GHE account on that host should be able to login using this authentication provider.
> 
> To make sure their user account has full details including groups they are a member of, you'll want to set up [Github org data](https://backstage.io/docs/integrations/github/org) ingestion. Does that help?

Yes! I've fixed it. I will close this issue
