### ISSUE TITLE
The TODO plugin cannot read most of our Gitlab repos 

### ISSUE THREAD

**Issue by Jerry4013** [backstage/backstage#5997]
Hello, 
We installed the TODO plugins (both front-end and back-end plugins), but it only works well on a very small Gitlab project/repo. In most of our repos, it's loading forever with a loading spinner. 

I tried to debug this issue and inserted some logs in the source code. We found that the issue is from the GitlabUrlReader of the backend-common package. When calling the readTree method, the function is stuck when reading some image file or svg file. Sometimes it's also stuck on some other files.

Could anyone help on this? Thanks!

**Comment by Rugvip** [comment]
Thanks for reporting and digging in to the issue!

Perhaps we could extend the [`readTree` filter](https://github.com/backstage/backstage/blob/2147ab9c1bd37e93e9e332c5ee14daa08be031e6/plugins/todo-backend/src/lib/TodoReader/TodoScmReader.ts#L86) so that it skips well known non-text files like `.png`, `.jpeg`, etc. I could have a look at it at some point but I'll leave this fix up for grabs if anyone wants to tackle it sooner.

**Comment by djamaile** [comment]
@Jerry4013 do have an example repo I can use the reproduce the problem?

**Comment by Jerry4013** [comment]
@djamaile Sorry, it's our company's Gitlab repo, but if I put a png file in the repo, it will be stuck.

**Comment by adamdmharvey** [comment]
I'd guess some quick work here might do it:

https://github.com/backstage/backstage/blob/667656c8b5f93cb38dfb9016ccc64b60580e9f9a/plugins/todo-backend/src/lib/TodoReader/TodoScmReader.ts#L90-L95

Something like `if file ends in .png then continue` sort of thing...

**Comment by djamaile** [comment]
I can give it a shot for sure.

**Comment by Rugvip** [comment]
@djamaile thanks!

**Comment by biki0109** [comment]
I also have the same situation as you, the todo plugin cannot read some certain files, for example the `go.mod` and `go.sum` files in my golang project.
To workaround this, I did make a copy of https://github.com/backstage/backstage/blob/master/plugins/todo-backend/src/lib/TodoReader/TodoScmReader.ts file here and add in some filter.
```typescript
const tree = await this.reader.readTree(url, {
      etag,
      filter(path) {
        return !path.startsWith('.') && !path.includes('/.') && !path.includes('.mod') && !path.includes('.sum');
      },
    });
```
Then in my todo packages/backend/src/plugins/todo.ts file, I use my custom filter instead of the original plugin of the package

**Comment by djamaile** [comment]
Thanks @biki0109 , I was running it on random repo’s but didn’t try it out an golang repo.

**Comment by Jerry4013** [comment]
@biki0109 Thanks for your solution! I tried it and it works in most cases. However, one of my python file includes some json-format code, then the detector was stuck there. And also I need to skip all the html and json files. 

I'm gonna research more on the reader library and find out the reason. 

Thank you again for your information. It helped us a lot!

**Comment by Jerry4013** [comment]
Getting file archive with **tar.gz** is the default of Gitlab.  [https://docs.gitlab.com/ee/api/repositories.html#get-file-archive](https://docs.gitlab.com/ee/api/repositories.html#get-file-archive)

On my side, if I modify the packages/backend-common/src/reading/GitlabUrlReader.ts file so that using tar.gz instead of zip, this issue is resolved.

@Rugvip Could you change the @backstage/backend-common GitlabUrlReader.ts to use tar.gz instead of zip in Backstage? We are using a standalone app of Backstage, so, we wish to use @backstage/backend-common as a dependency. 

Thanks!

**Comment by freben** [comment]
@Jerry4013 We could but, if you have this working, would you want to perhaps make the pull request for it?

**Comment by Jerry4013** [comment]
@freben Yes, sure. I would like to submit a pull request for it today. Thanks!

**Comment by snakecharmer** [comment]
After a version bump, works for us. The only problem is the link from backstage to Gitlab. 
But it's missing the project and the branch reference:

URL generated from backstage:

https://gitlab.{instance}.de/{group}/Sources/App/Models/Entities/Asset/Asset.swift#L202

Right URL in Gitlab
https://gitlab.{instance}.de/{group}/{project_name}/-/blob/master/Sources/App/Models/Entities/Asset/Asset.swift#L202

**Comment by satrox28** [comment]
@Rugvip still we are facing issue with URL formatting as mentioned my @snakecharmer on v0.1.11 on plugin-todo-backend
