### ISSUE TITLE
[jenkins-plugin] Add annotation for Bitbucket

### ISSUE THREAD

**Issue by goober** [backstage/backstage#6008]
## Feature Suggestion

The current jenkins-plugin is documented to only support GitHub through the [GitHub Branch Source Plugin](https://plugins.jenkins.io/github-branch-source/). With background the annotation `jenkins.io/github-folder` sounds reasonable.

However, the current implementation also supports jobs in Jenkins that have been created for Bitbucket through the [Bitbucket Branch Source plugin](https://plugins.jenkins.io/cloudbees-bitbucket-branch-source/). By having a GitHub related annotation for a Bitbucket job could be confusing.

So what I am suggesting is to either deprecate the current annotation and replace it with a more general alternative, or introduce a new annotation that is specific to Bitbucket. e.g. `jenkins.io/github-folder`

I can probably support you with the implementation, when we have concluded what direction we want to go

**Comment by Fox32** [comment]
Related #4328

**Comment by goober** [comment]
Closing this in favour of the related issue.
