### ISSUE TITLE
Catalog Customization: CatalogLayout & CreateComponentButton not exported

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#6028]
Following the documented [Catalog Customization](https://backstage.io/docs/features/software-catalog/catalog-customization) walkthrough is not possible since the `CatalogLayout` & `CreateComponentButton` components are currently not exported from the `@backstage/plugin-catalog` package.

## Expected Behavior

To be able to customize the `CatalogIndexPage` in `packages/app`.

## Current Behavior

It does not seem possible to customize the `CatalogIndexPage` in `packages/app` without recreating the page layout and context.

## Possible Solution(s)

- Export the `CatalogLayout` & `CreateComponentButton` components from `@backstage/plugin-catalog`
- Possibly move `CatalogLayout` to  `@backstage/plugin-catalog-react` and export it from there.

## Steps to Reproduce

Follow the steps in [Catalog Customization](https://backstage.io/docs/features/software-catalog/catalog-customization).

## Context

Looking to customize the catalog index page experience.

## Your Environment

n/a

**Comment by timbonicus** [comment]
#5984 takes care of `CreateComponentButton`, but `CatalogLayout` still needs exported. Good catch!
