### ISSUE TITLE
Search: make "no results" more visible

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#6031]
## Feature Suggestion

If the new search result page returns no result, the result list is only empty. There is no difference between "loading" and "no results" - which might confuse the user.

![image](https://user-images.githubusercontent.com/648527/121887205-bdaae400-cd16-11eb-8f3d-2de6542b4a0d.png)

## Possible Implementation

Just a simple text saying "no results" or even a nice picture like on the 404 page. Maybe add an animation while it is loading.

## Context

It's possible to show empty results right now, because it is quite extensible, but I would wish that that there is a build in component for it.

**Comment by emmaindal** [comment]
Thanks for opening this issue @Fox32, I think we can use the [EmptyState component ](https://backstage.io/storybook/?path=/story/feedback-emptystate--data), something like `<EmptyState missing="data" title="Sorry, no results were found" />` for errors as well as [Progress component](https://backstage.io/storybook/?path=/story/feedback-progress--progress) when loading, what do you think?

**Comment by Fox32** [comment]
> Thanks for opening this issue @Fox32, I think we can use the [EmptyState component ](https://backstage.io/storybook/?path=/story/feedback-emptystate--data), something like `<EmptyState missing="data" title="Sorry, no results were found" />` for errors as well as [Progress component](https://backstage.io/storybook/?path=/story/feedback-progress--progress) when loading, what do you think?

Oh, good idea! I guess `<EmptyState>` is something I could already use (empty `results` from `<SearchResult>`), but I'm not sure if the progress is already exposed by `<SearchResult>`.

**Comment by emmaindal** [comment]
No its not, if we want it to be composable, the loading and error state needs to be passed through from here https://github.com/backstage/backstage/blob/master/plugins/search/src/components/SearchResult/SearchResult.tsx

**Comment by iamEAP** [comment]
Yeah, maybe we default to `<EmptyState />` and some loading state, but allow them to be overridden via props on `<SearchResult />`?

**Comment by Fox32** [comment]
I think a default would be nice for both cases.

**Comment by camilaibs** [comment]
There is an example using empty state (here)[https://github.com/backstage/backstage/issues/6062] including nice suggestion for pagination until this issue be resolved 🙂

**Comment by Fox32** [comment]
Having a look at the source code I noticed that this is already implemented, there is just a trivial bug that prevents this from working. I created a PR for it #6165

**Comment by emmaindal** [comment]
Thank you @Fox32 for fixing this, @rubenLindstrom as you were working on this and just about to open a PR I wanted you to know its solved, but thanks for looking into it anyways!
