### ISSUE TITLE
[jenkins-plugin] Wrong branch is fetched when build includes multiple repositories

### ISSUE THREAD

**Issue by goober** [backstage/backstage#6033]
We have Jenkins jobs that clone a common Jenkins Pipeline Library in the beginning of the job and also some gitops related repositories in the end of the build. This will have the effect that Jenkins API returns multiple `hudson.plugins.git.util.BuildData` objects where the target repository is not first in the list. Since the current implementation of the Jenkins plugin will just take the first BuildData object and extract the branch information from there we gets the information from one of the related repositories and no for the target one.

## Expected Behavior

When I list Jenkins builds for a service I expect that the returned builds include the correct branch information.

## Current Behavior

The branch and sha information are taken from one of the related repositories that are part of the build and not from the target repository.

## Possible Solution
We could include the folder's `jenkins.scm.api.metadata.ObjectMetadataAction` object when we fetch the jobs. This object contains the root url to the repository.  We can then use the [git-url-parse](https://github.com/IonicaBizau/git-url-parse) library to parse the repository server, owner and name. This information can than be used to filter the `hudson.plugins.git.util.BuildData` objects by `remoteUrls` to only include the BuildData that corresponds to the folder's repository.

## Steps to Reproduce

Create a new Jenkins job that also clone a jenkins-pipeline-library repository in the beginning of the job.

**Comment by goober** [comment]
@freben You could assign me to this ticket. I am on it.

Just waiting for https://github.com/IonicaBizau/git-url-parse/pull/128 to be accepted and released so we can parse the folder repository for Bitbucket correctly.

**Comment by freben** [comment]
Ok!

**Comment by goober** [comment]
Still valid

**Comment by goober** [comment]
Another issue that blocks this: https://github.com/IonicaBizau/git-url-parse/issues/133

**Comment by freben** [comment]
Hm is this library really a good fit for parsing general URLs of any possible type? Not sure it was meant to be. Could it be the case that we should replace the URL parsing with a custom one, if we encounter issues URLs and other random stuff...?
