### ISSUE TITLE
feature request: expose template info in the custom action

### ISSUE THREAD

**Issue by missedone** [backstage/backstage#6047]
i'm writing a custom action by following https://backstage.io/docs/features/software-templates/writing-custom-actions
in the custom action handler, the `ctx` object provides the baseUrl of the template, but i want to know the template name as well

## Feature Suggestion

```js
import { createTemplateAction } from '@backstage/plugin-scaffolder-backend';
import fs from 'fs-extra';

export const createNewFileAction = () => {
  return createTemplateAction<{ contents: string; filename: string }>({
    id: 'mycompany:create-file',
    schema: {
      input: {
        ...
      },
    },
    async handler(ctx) {
      // THIS IS WHAT I NEED, TO GET THE TEMPLATE NAME OR MORE TEMPLATE METADATA
      ctx.logger.info(ctx.template.name)
    },
  });
};
```

## Context

we already have a scaffolding service similar to the backstage scaffolder, i'm not trying to integrate the existing one into backstage, i'm building the adapter custom action, Ex. use the backstage UI take the params, and call the custom action which call our existing scaffolding service rest api to create the project, the existing scaffolding service take template name as param.

**Comment by benjdlambert** [comment]
Is this something you'd want to contribute @missedone? :pray:

**Comment by Joonpark13** [comment]
I'm looking for good first issues to tackle - I can look into this if there's still a need for it.
