### ISSUE TITLE
Adding Features to Pagerduty Plugin

### ISSUE THREAD

**Issue by douglasread** [backstage/backstage#6048]
## Feature Suggestion

To include new features offered by Pagerduty natively in the plugin.

## Context

The current Pagerduty plugin offers the following:
1. A link directly to the service in Pagerduty
2. A button for creating a new incident
3. A display of recent incidents
4. A list of those currently on call for the service

This plugin, however, could easily be expanded. Some basic functionalities that would empower users to better track their application and its performance would be:
1. Adding ability to track change events
   - Would allow users to quickly correlate recent changes with the incidents they are seeing without having to leave Backstage
2. Adding a direct link to a service's escalation policy
   - This helps enforce good practices for services with Pagerduty integrations (having well-defined on call schedules).
   - If a user has a reason to change a service's on-call rotation/escalation, a direct link would be convenient
3. Add the ability to track analytics like response time and number of incidents
   - Creates more accountability and allows a team to track how their service is performing over time 

## Possible Implementation

Could potentially create some sort of tabbed design for flipping between change events and incidents. This could look something like:
<img width="777" alt="App_Markup" src="https://user-images.githubusercontent.com/56704541/122106750-4ba2cf80-cde8-11eb-8d8c-60942f8f677f.png">

Change events can easily be added by borrowing existing logic that pulls in incidents, but hitting this endpoint instead: https://api.pagerduty.com/change_events. These events could be displayed in a similar list fashion to incidents. Some important things to include would probably be: change title, how long ago the change happened, and links to the change. This could look something like:
<img width="780" alt="Change Event Screen" src="https://user-images.githubusercontent.com/56704541/122108821-ab01df00-cdea-11eb-9031-aaf165098392.png">

Analytics is more of a nice to have, but unfortunately the endpoint is still in early access. Due to this, implementing it now is probably not the best option, but it is worth keeping in mind for the future.

For linking to the escalation policy in PD, the link is provided in the response the plugin already gets from the PD service endpoint. This makes it trivial to implement. Best case scenario would be to offer some way to edit this from Backstage, but the mapping of this information is likely too complicated for accomplishing that.

**Comment by benjdlambert** [comment]
@marcuseide @samiramkr for visibility

**Comment by douglasread** [comment]
I would definitely be interested in contributing here @benjdlambert. Also interested in feedback/suggestions on the proposal.

**Comment by douglasread** [comment]
Hey @benjdlambert. I'm free to start working on these changes; just wanted to check whether you guys thought these additions were worthwhile beforehand.

**Comment by benjdlambert** [comment]
Hey sorry @douglasread I missed your previous message. Sure go ahead! There's some folks out on holiday at the minute that built this originally, but I think go for it and we can get you some feedback on it when they're back!

Looks like some great additions! :tada: Will assign you!

**Comment by freben** [comment]
closing for now, please add specific feature requests in https://github.com/backstage/community-plugins
