### ISSUE TITLE
[TechDocs] Support creating doc playlists

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#6063]
## Feature Suggestion

Allow users the ability to create "playlists" for docs. Borrowing from Spotify's music analogies, just like music playlists, I think it would be valuable to be able to create curated lists of related docs, sharing lists, and adding existing lists created by others to your "library" (ie. Favorites). 

## Possible Implementation

This may require a new `kind` similar to a `system` where multiple docs are part of a `doc-playlist` entity. There is also potential considerations related to https://github.com/backstage/backstage/issues/5913

## Context

Following some potential future [discoverability & search](https://backstage.io/blog/2020/09/08/announcing-tech-docs#discoverability-and-search) features demonstrated from Spotifys internal TechDocs, a concept of TechDocs playlists would align very well with discoverability and promotion of Golden Paths. Sets of related documentation can be curated around disciplines (eg. web developer, SRE, etc), domain areas, or team/org structures.

This allows you go beyond https://github.com/backstage/backstage/issues/4108 by capturing sparse knowledge banks into well defined groupings in a shareable manner.

**Comment by freben** [comment]
Spontaneously, my first reaction is that this sounds like it could be useful, but that the storage model shouldn't be in the form of entities. If we were to make collections like this, we might as well either

1. Make a database backed backend thing that can hold documentation lists, or perhaps better,
2. Just implement it as a [documentation entity](https://github.com/backstage/backstage/issues/5913) that's a markdown file that happens to link out to other docs.

The latter has the benefit of needing no extra systems support while also allowing all of the extra markdown features of grouping, extra info, headers, etc etc etc

**Comment by kuangp** [comment]
@freben that's a good point, this technically should already be possible by just creating a doc that contains links to other docs.

I think a large part of making this valuable would be the UI to be easily be able to create/edit playlists similar to just having to hit the "star" to star entities. It also helps to have a visual distinction for "playlists" items that may appear in a dedicated tab/section on the TechDocs page. Option 1 may align better with this vision since these lists would be more interactive. 

Option 2 may become awkward in regards to where the backing entity files should live when users are free to create any number of "playlists" similar to creating favorites/shortcuts (which I believe currently live in local storage?)

**Comment by timbonicus** [comment]
Slightly different concept, but the idea reminds me a bit of this mockup in [#4757](https://github.com/backstage/backstage/issues/4757#issuecomment-789713976) 😄

**Comment by kuangp** [comment]
The mock up from #4757 definitely has a similar "flavor" to this concept. I think the main difference is push vs pull where that type of categorization allows doc authors to "push" labels with their docs to be picked up by UI filters whereas this allows any user to "pull" any docs into their own custom categorization. 

I also see a possible implementation leveraging the Techdocs page customization support that was recently released (with some additional enhancements). If the `DocsGrid` and `DocsTable` supports custom actions (in similar vein to https://github.com/backstage/backstage/pull/6035) to add some sort of "add to playlist" action, one may be able to create a "TechDocs Plugin" that exports that action and additional `playlistsTable` and `playlistEdit` components that can be inserted as widgets/tabs on the TechDocs page. Assuming we go with a DB backed backend, this would also ship with a backend plugin.

**Comment by kuangp** [comment]
still interested in this feature

**Comment by kuangp** [comment]
still interested but haven't had the bandwidth to prioritize working on this on our end :/

**Comment by kuangp** [comment]
For those who are still interested I was able to hack together a plugin for this in my spare time, check it out in the linked PR!
