### ISSUE TITLE
TechDocs Reader 404 when clicking link to relative image

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#6069]
Click on hyperlinks to a relative image files within the techdocs reader will result in a 404. When this is done in the raw MkDocs static site, the image is displayed full screen in the browser. However, the techdocs reader appends a `/index.html` to the end of the image file (which does not exist).

## Expected Behavior

You can click a link that points to an image file and the image will be displayed in techdocs reader component within Backstage.

## Current Behavior

Within Backstage, clicking on these links will cause a 404. The techdocs reader tries to fetch the file at `https://docs-storage/.../some-image.png/index.html` which doesn't exist. The raw MkDocs site will open the image file in the browser full screen.

I suspect this could also be an issue for other types of asset files as well (e.g. PDF's, SVG's, etc.).

## Possible Solution

I haven't investigated beyond this so I'm not sure about what solutions are possible to fix this. We could embed the images into a markdown file to workaround this. However if the image is large it's not always practical to view. Some sort of modal lightbox possibly with zooming and panning would probably be very helpful for these situations.

## Steps to Reproduce

1. Create a simple markdown docs site with a random image + a single markdown file containing a link to the image. For example:

  ````md
  - [link to relative image](some-image.png)
  - [another link to relative image](./some-image.png)
  ````

2. Run `techdocs-cli serve`
3. Click the link & inspect the network request.

## Context

We use PlantUml a fair bit and sometimes the generated images are quite large to fit into a page. So viewing them full screen (not scaled) is sometimes needed.

**Comment by iamEAP** [comment]
Just to note, one (not always ideal, but valid) workaround for this is to write the link as an HTML anchor with a `download` attribute, e.g. `<a href="some-image.png" download>link to relative image</a>`.  ...If your backend and your frontend share the same origin, this will actually cause a download (rather than view in-browser), but it's something.

The actual fix will probably end up in some combination of [addBaseUrl.ts](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/transformers/addBaseUrl.ts#L68), which doesn't get applied to `<a>` tags (except with `download` attr)...  And [addLinkClickListener.ts](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/transformers/addLinkClickListener.ts#L35), which handles eventual navigation.

**Comment by andrewthauer** [comment]
> As an alternative, we could try and add a "click to zoom" capability on all images to further work around the need?

A click to zoom / lightbox for all images would be useful in general I think. This could possibly be a good solution for images that are scaled down. Wondering if this could work with SVGs as well.

**Comment by onematchfox** [comment]
Also ran into this/a similar issue... In my case all my navigation links are broken as the techdocs reader is appending `index.html`  to all menu links. Tracked this down to the following line of code: https://github.com/backstage/backstage/blob/d1030eb8bb578aee2ad09925f81cf7d8c06224bc/plugins/techdocs/src/client.ts#L162-L167

Not 100% sure my understanding of this code is correct... But, I could resolve my issue by changing the logic to only suffix `index.html` if `path` is empty (i.e. for requests to the root entity). E.g. 

```
async getEntityDocs(entityId, path) {
    const {kind, namespace, name} = entityId;
    const storageUrl = await this.getStorageUrl();
    const token = await this.identityApi.getIdToken();
    let url = `${storageUrl}/${namespace}/${kind}/${name}/`;
    if (path != ""){
      url = `${url}${path}`;
    } else {
      url = `${url}index.html`
    }
    const request = await fetch(url, {
      headers: token ? {Authorization: `Bearer ${token}`} : {}
    });
``` 

@iamEAP wondering if you perhaps have an opinion on whether this "fix" would be something worth submitting? Or, does this feel like there's something wrong with my setup (`local` build, generate and publish)?

**Comment by iamEAP** [comment]
> _...an opinion on whether this "fix" would be something worth submitting? Or, does this feel like there's something wrong with my setup..._

Hmm...  Yeah, something doesn't quite feel right.  Is this happening on all of your Docs sites or only some?  Can you share a snippet of an `mkdocs.yaml` `nav` key?  Wondering if there's something unexpected about the way pages are set up there.

**Comment by onematchfox** [comment]
> Is this happening on all of your Docs sites or only some? 

On all of them. Even happens when rendering Backstage's own `mkdocs.yml` - https://github.com/backstage/backstage/blob/master/mkdocs.yml

> Can you share a snippet of an `mkdocs.yaml` `nav` key? 

```
nav:
  - Overview:
      - Team API: 'team-api.md'
      - Contributing: 'contributing.md'
  - Systems:
    - XYZ: 'systems/xyz.md'
```

**Comment by iamEAP** [comment]
@onematchfox, are you on at least `v0.9.6` of the TechDocs plugin?  There was a related [fix](https://github.com/backstage/backstage/blob/master/plugins/techdocs/CHANGELOG.md#096) in that version...  Just want to make sure.

**Comment by onematchfox** [comment]
> @onematchfox, are you on at least `v0.9.6` of the TechDocs plugin? There was a related [fix](https://github.com/backstage/backstage/blob/master/plugins/techdocs/CHANGELOG.md#096) in that version... Just want to make sure.

Yes, I am running `v0.9.7`. Not sure that fix is my issues as the link looks correct in the rendered site - e.g. in the nav above the link to `Contributing` is http://localhost:3000/docs/default/Domain/xyz/contributing.html`. It is only when clicking on the link that the extra `/index.html` gets added to the request that is made. I debugged in the browser and the additional suffix seems to be coming from https://github.com/backstage/backstage/blob/d1030eb8bb578aee2ad09925f81cf7d8c06224bc/plugins/techdocs/src/client.ts#L162-L167

In the call to `getEntityDocs`, `entityId` is set to `{kind: "Domain", namespace: "default", name: "xyz"}` and `path` to `contributing.html`. This results in the URL `http://localhost:7000/api/techdocs/static/docs/default/Domain/xyz/contributing.html/index.html` being requested which results in a `404`.

**Comment by iamEAP** [comment]
Looking at the URL you pasted, I have a feeling this is a mismatch between how TechDocs _expects_ nav links to have been generated by mkdocs vs. how they are being generated in your setup.  I think TechDocs is expecting `static/docs/default/Domain/xyz/contributing/` (or similar), and then adds the `index.html`.  So I'm thinking there's something unique about plugins you're using to generate the docs.  ...And perhaps we should support both.

> _P.S. My apologies for spamming this issue in the event that this issue is unrelated to the one described here - would be happy to open a new issue if anyone thinks that would be best._

No worries!  But probably a good opportunity to fork this into another issue, as I think they are probably different.

**Comment by pschildkamp** [comment]
Hi, 

I ran into exact the same issue as @onematchfox. I'm hosting docs on an Azure storage account, but pages won't load because techdocs index.html files which do not exists. 

We made multiple pages in the docs directory containing 3 .md file's. The mkdocs.yml containers the following:
```
nav:
  - Home: index.md
  - Glossary: glossary.md
  - Current architecture: currentarchitecture.md
```

This results in the 3 .html files containing index.html, glossary.html and currentarchitecture.html. Techdocs generates the correct navigation with the corresponding URL'S:
```
- docs/default/Component/customer-domain/index.html
- docs/default/Component/customer-domain/glossary.html
- docs/default/Component/customer-domain/currentarchitecture.html
```
This is comform the file path's in the Azure storage container. 

Now the issue is, is that the Azure dependency is looking for the following Blobs which do not exists:
```
- docs/default/Component/customer-domain/index.html
- docs/default/Component/customer-domain/glossary.html/index.html
- docs/default/Component/customer-domain/currentarchitecture.html/index.html
```

I've checked versions, and I also run version 0.9.6

The HTML generated to the other pages is very basic. 
```

<li class="md-nav__item">
   <a href="glossary.html" title="Glossary" class="md-nav__link">
   Glossary
   </a>
   </li>
   <li class="md-nav__item">
   <a href="currentarchitecture.html" title="Current architecture" class="md-nav__link">
   Current architecture
   </a>
   </li>  
```

So 0.9.6 doesn't fix the issue for me.

**Comment by andrewthauer** [comment]
The originally commented part of this is still an ongoing issue, especially with large images.

**Comment by zinizhu** [comment]
Re-opening this issue as I am having the same problem -  is there any update on fixing the original issue?

**Comment by Depado** [comment]
Facing the same issue here. Is there a way to re-open this or, if it was fixed, tell us how to fix it on our end?

**Comment by julian-alarcon** [comment]
I'm still having the issue.

**Comment by yoanho** [comment]
I'm having the same problem

**Comment by jaalvarezuria** [comment]
Anybody resolve the problem? I´m facing the same problem after create backstage from scratch. I don´t know the reason why is adding an index.thml at the end of the url requested. 
Thanks
