### ISSUE TITLE
SonarQube/SonarCloud overview of projects

### ISSUE THREAD

**Issue by jvilimek** [backstage/backstage#6075]
## Summary

Now there is [SonarQube](https://github.com/backstage/backstage/tree/master/plugins/sonarqube) plugin that proxies results of last analysis for the service if there is anotation.

We are looking for a way how to see overview of results of multiple services. It may integrate to existing plugin, it may be a new plugin.

## Project website (if applicable)

https://github.com/backstage/backstage/tree/master/plugins/sonarqube

## Context

Now you need to go to the detail of each service to see the SonarQube analysis results. It is not easy to see "your" services or all services results.

Now..there is something similar already in the SonarQube portal or [sonarcloud](https://sonarcloud.io/projects)), i.e.
![image](https://user-images.githubusercontent.com/16001792/122362006-0dc4b900-cf58-11eb-8202-4d22d23a6364.png)

So it is not ideal to duplicate such overview in the Backstage "as is" but maybe add some more context to it. E.g. integrate it somehow also with the search of backstage? With the services, tags and the other meta data? Show only "my" services? Show only services from service catalog?

WDYT?

**Comment by Fox32** [comment]
We already did something similar for the FOSSA plugin. While I think duplicating just the view seem to be less interesting, having a way to see you my owned stuff seems to be appealing.

**Comment by andrewthauer** [comment]
Or aggregated metrics rolled up per owner group might also be interesting.

**Comment by benjdlambert** [comment]
Is this something you want to contribute @jvilimek? :pray:

**Comment by jvilimek** [comment]
> Is this something you want to contribute @jvilimek? 🙏

well..I am personally quite newbie in js/typescript/react so probably not. But I can ask one of our internal team to help as this is something we are really looking for...
