### ISSUE TITLE
[Plugin] Honeybadger Plugin

### ISSUE THREAD

**Issue by voodooGQ** [backstage/backstage#6086]
## Summary

Honeybadger.io plugin to display errors on a Componentized basis.

Features:
	- Display the top 25 most recent errors on an Entity page
	- Display the 5 most frequent errors within a one-week period as an Overview card.
	- Annotation to specify the project id
	- Annotation to specify a custom query based on Honeybadger's DSL: https://docs.honeybadger.io/guides/search.html#how-to-search

## Context

We utilize Honeybadger within our Organization and have just recently started testing the waters of Backstage for our software catalog. In order to gauge the difficulty of custom plugin development, we wanted to start with an easy first offering that provides a couple of key observability features for Honeybadger. 

We're currently in active development of a plugin that will allow you to view the 25 most recent errors on a dedicated entity page, as well as an Overview card that will display the 5 most frequent errors with the last week. Annotations have been provided to target a specific projectId as well as provide a query to scope the requirements of the Component.

Are there any other features people would like to see? We'll keep this thread updated as we progress through development.

**Comment by jebentier** [comment]
@voodooGQ I'm looking for a honeybadger plugin as well just as you describe in the request here. I see you marked this as completed, did you find an implementation of this plugin somewhere?

**Comment by voodooGQ** [comment]
Hello @jebentier!

`completed` is probably not a good status, it probably is more considered `abandoned` unfortunately. The code still exists, however, due to management changes at the organization that was supporting it we never fully pursued getting it open sourced. It's been awhile though, and we've had more management changes since then 😆 . Let me discuss internally at my org to see how we feel about open sourcing it at this time to give back to the community.

I'm sorry, I wish I could just pass along the code, but since it was on the company dime my hands are tied without approval.

Will try and reply back to this thread in the next week with my findings. Appreciate the interest!

**Comment by jebentier** [comment]
Thanks for getting back to me on this @voodooGQ. Totally understand and appreciate you looking into the possibility. Maybe we'll be able to make one in-house and open source it as well and merge concepts at some point if your org gives the green light.
