### ISSUE TITLE
Support Postgres setup without permissions to `pg_database` or database creation

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#6090]
## Feature Suggestion

Skip the call to `ensureDatabaseExists` for deployments where access is only given to the specific provisioned databases 
 https://github.com/backstage/backstage/blob/ae501c04dfb57d79e0252a54b8f11e44d84e9acb/packages/backend-common/src/database/DatabaseManager.ts#L208

## Possible Implementation

Maybe drive this through a config in `backend.database` in your `app-config.yaml`?

## Context

We're deployed in a Heroku-like environment where we attach provisioned PG databases which only come with limited permissions to access the specific database in the shared instance. As a result the call to `ensureDatabaseExists` fails since it attempts to access `pg_database`. We're able to handle manually provisioning a DB per plugin by utilizing the new `DatabaseManager` to config a per plugin connection since we don't have permissions to create new DBs on the fly either.

**Comment by kuangp** [comment]
Just FYI, we're been able to workaround this by using an internal DB manager and was hoping to be able to deprecate our internal manager in favor of the upstream one but hit this blocker.

**Comment by hichristo** [comment]
Upvoting, not really possible to deploy to heroku with postgres

**Comment by freben** [comment]
Oh I'd missed this ticket! Good thing you upvoted visibly :)

This sounds like it makes total sense. [This](https://github.com/backstage/backstage/blob/29862be2bc6847c28f7c47cfff46ec3fcf6f3699/packages/backend-common/config.d.ts#L57) is where that configuration section is declared.

Maybe a simple `ensureExists?: boolean` that's default true? For bonus points, perhaps have it both on the root and (when applicable) in the per-plugin sections as an override?

Sounds like a great, small, well delimited contribution. Would any of you be up for it? 🙌

**Comment by kuangp** [comment]
@freben I can look into implementing it, thanks for the feedback!

**Comment by hichristo** [comment]
Great stuff guys 🙌
