### ISSUE TITLE
Catalog : New Entity type and specs for defining workflow/businessprocess

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#6101]
New Entity type and specs for defining workflow/businessprocess

## Feature Suggestion

Define new entity type (Workflow/Process) to define/model business processes which can reference the involved systems.
The intentions is to provide broader ecosystem view for the courser-grain business processes, most probably under Explore plugin.

## Possible Implementation

The specs for the Workflow can be similar to AWS steps funtions/steps in scaffolder templates.

Workflow steps would reference the available domains:system to create the representation and provide context into business processes.

Reference: 
The workflow visualization can be something like this : 
![image](https://user-images.githubusercontent.com/8432431/122533324-c5df8800-d064-11eb-971b-1ac9628498a8.png)

This visualization allows to overlay many variants of similar process using minimum space and clutter.

Library for Tube map :  https://observablehq.com/@johnwalley/d3-tube-map

### Alternate approach considered : 
Domains and Systems (or even components) can be tagged with XYZ business processes. However, this approach does not seem to be managible as 

1. It may get clutter with N number of high level business processes.
2. It relies on multiple multiple teams to apply consistent tags for e2e business process view, which is practically not easy to achieve due to cross-team dependencies. 

## Context

Current Ecosystem covers views for domains and systems. These information can be further leveraged to define business proces context in which they are used by refering them into Workflow kind, which is also stored as catalog entity.

**Comment by freben** [comment]
Hey! I just wanted to acknowledge that I saw this ticket so it doesn't seem to go unnoticed into the aether.

We're sort of careful with adding more kinds to the core offering. However, [adding custom private extensions](https://backstage.io/docs/features/software-catalog/extending-the-model) to the model is quite fine. Especially adding a completely new kind, which would not interfere with existing things.

I'll also add that in a lot of cases, documentation is good holder for information like this, and it might be fine to reference that documentation as [`metadata.links`](https://backstage.io/docs/features/software-catalog/descriptor-format#links-optional) for example.

Closing this for now. Do feel free to continue the discussion here or on Discord if you feel for it!
