### ISSUE TITLE
create-plugin's example plugin is incorrectly set up

### ISSUE THREAD

**Issue by delanni** [backstage/backstage#6108]
A newly created plugin (which I assume is the starting point for first time plugin authors) is inconsistent with the documentation and expectations, probably due to some incorrect configuration.

## Expected Behavior
When you go through the suggested flow for creating a plugin, it's incorrectly set up - and I'd be able to develop in a sandbox under `localhost:3000/<plugin-name>`. 
_(I assume it's suggested since we have pre-created scripts for these in the create-app's templates, and the backstage-cli)_

See the following example:
```shell
yarn create-plugin        # answer with the plugin name 'dingos'
cd plugins/dingos
yarn start                # running 'backstage-cli plugin:serve'
```
According to the readme docs, I'd expect to find my developed plugin under `/dingos`.

## Current Behavior
Currently, plugins are served under `/page-1` (which I guess is a default route path in lieu of a configured path.

## Possible Solution
I'm yet to figure out the whole plugin/route config semantics of the backstage libraries, but I'd guess I should be able to somehow prescribe under what path I'd like to serve my plugin, if not, I'd expect that to be the root path `/` or the `id` of the plugin. Neither is true. I am guessing some configuration is not trickled down to the server's config.

## Steps to Reproduce

1. Step: Set up new example plugin
```shell
yarn create-plugin        # answer with the plugin name 'dingos'
cd plugins/dingos
yarn start                # running 'backstage-cli plugin:serve'
```
2. Step: Wonder where you'll find your plugin displayed?

## Context
As a beginner just starting out, it's already confusing enough that I'd have to live with a lot of things hidden into `@backstage/core` functions. It can get really difficult to find out what's the reality vs what's the suggested behaviour in the `README`.

## Your Environment

- NodeJS Version (v12): v12.22.1 (shouldn't matter)
- Operating System and Version (e.g. Ubuntu 14.04): OSX Darwin
- Browser Information: Chrome

**Comment by angeliski** [comment]
Hey @delanni , when the docs talk about the `ĺocalhost:3000/<plugin-name>` is a reference for your main app running, not the plugin develop mode. If you run `yarn start` at the root folder you will see that behavior. 

You can check then your `packages/app/src/App.tsx` file is updated to include the plugin config too.

Maybe we can update the docs to give more context about that, WDYT?

We can update the [dev](https://github.com/backstage/backstage/blob/master/packages/cli/templates/default-plugin/dev/index.tsx.hbs#L5) mode to provide the same behavior and avoid that type of confusion too

**Comment by angeliski** [comment]
@delanni Could you take a look at #6120?
I believe we can resolve there :)

**Comment by delanni** [comment]
Hey!
I checked the PR, I think this is a good resolution. Looking at the code now, I see that this bit was the missing piece:
```
    path: '/{{ id }}'
```

Without the path parameter, the single development page for the plugin would go to a default sequential page like `page-1` was. Now it is okay, at least devs can now understand that their plugin `xyz` would be hosted under `/xyz` - since this is explicit in the plugin's dev config. Thanks for the update!
