### ISSUE TITLE
API Explorer loses filter state on navigation

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#6110]
## Expected Behavior

When configuring a filter in the API explorer, then navigating to an entity, and then back to the API explorer with the browser history, the filter state should be restored. The filter parameters are added to the URL and kept in the browser history.

## Current Behavior

Filters are not restored, they aren't added to the URL anymore.

## Possible Solution

Store filters in the URL.

## Steps to Reproduce

1. Navigate to the API explorer
2. Select a filter, e.g. an owner
3. Click on one of the entities
4. Use the browser history to navigate back to the API explorer
5. Filter for owner should still be set

## Context

There were some recent changes to the API explorer, I guess it was broken by them (#5984).

## Your Environment

Current `master`

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by benjdlambert** [comment]
@kunagp for visibility, also @timbonicus is this something that we have a solution for in the catalog page that we can help move across to here?

**Comment by timbonicus** [comment]
Nothing in place on the catalog page at the moment, I made a draft PR #6140 to show how it might be fixed. 🤔 In case anyone wants to pick this up.

**Comment by kuangp** [comment]
@timbonicus took the opportunity to pick up where you left off in your draft, thanks for getting it started!
