### ISSUE TITLE
[TODO] Allow custom filter for the TODO Reader

### ISSUE THREAD

**Issue by egnwd** [backstage/backstage#6111]
## Feature Suggestion

In some of our repos there are third party deps in the source and at the moment the todo-backend plugin will read the files and report their todos.

It would be nice if (perhaps per entity somehow) we could add a list of globs to ignore from the reader e.g. `**/vendor/**`.

## Possible Implementation

I think it would involve adding some config in the `app-config.yaml` or the backend `plugins/todo.ts` for some ignored globs, if it was per entity perhaps a list in the annotations? I'm not sure on the best practice there.

And then I think the current filter would then need to delegate to the filter [here](https://github.com/backstage/backstage/blob/399abf9670c724fd5ae166e323239896b85a0dae/plugins/todo-backend/src/lib/TodoReader/TodoScmReader.ts#L85).

## Context

The context is we have a fair few "false positives" on things we can fix, and short of ripping the vendor folder out of our repo I think this might be a nice thing to have.

I thought about, as a workaround, using the source annotation to specify our `src` folder in the repo, but unfortunately in some cases the vendor is in some sub-dir of the `src` (no idea why). But that is by-the-by.

**Comment by Rugvip** [comment]
Fixed by #9564
