### ISSUE TITLE
PAGERDUTY_TOKEN does not work

### ISSUE THREAD

**Issue by ananthulasrikar** [backstage/backstage#6142]
https://github.com/backstage/backstage/blob/f2b2cf98846cac673d06bd736ccf1edff82a9644/app-config.yaml#L75

Above line is not same as

https://github.com/backstage/backstage/blob/master/plugins/pagerduty/README.md#providing-the-api-token

 Authorization: Token token=${PAGERDUTY_TOKEN} - works 
 Authorization: ${PAGERDUTY_TOKEN} - does not work

**Comment by OrkoHunter** [comment]
Aah, thanks for reporting! Would you like to create a PR with the fix? :)

**Comment by ananthulasrikar** [comment]
Would love too.

**Comment by ananthulasrikar** [comment]
Closes #6149
