### ISSUE TITLE
getOptionalString doesn't return custom keys

### ISSUE THREAD

**Issue by yonimoses** [backstage/backstage#6144]
Using the provided api, i can seem to get the custom key:value from app-config.yaml

my code is 
`
  const configApi = useApi(configApiRef);
  const key = configApi.getOptional('mykey.instances')
`
my app-config.yaml

`
.
.
.

organization:
  name: My Orgy

mykey:
    instances:
      - baseUrl: http://localhost:8080/plugins/some_external_api
 .
.
.

`

The code is latest (updated the app yesterday) and my code is inside a custom plugin i've created.

Any ideas?

**Comment by OrkoHunter** [comment]
Make sure the config has visibility set to "frontend". By default any new configs are only visible in the backend, to prevent accidental leakage of secrets. :)

https://backstage.io/docs/conf/defining#visibility

**Comment by yonimoses** [comment]
looks like I missed these docs! 
thanks a lot ;)
Working perfectly.
