### ISSUE TITLE
catalog - links missing for component

### ISSUE THREAD

**Issue by falconbin** [backstage/backstage#6155]
In the latest backstage, catalog component links missing in the UI even though I configed it in component yaml file(metadata.links).
![image](https://user-images.githubusercontent.com/20329141/122869392-cb87e700-d35e-11eb-8085-9486ab19a41c.png)

## Expected Behavior
The links should be shown in the right panel, refer to below screenshot:
![image](https://user-images.githubusercontent.com/20329141/122869051-4a305480-d35e-11eb-85c3-e0520082a0c0.png)

## Current Behavior
The links missing
![image](https://user-images.githubusercontent.com/20329141/122869286-9e3b3900-d35e-11eb-9f92-f0b4d69f74ee.png)

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by freben** [comment]
These pages are fully under the adopters' control. You'll have to add the various cards that you want, in some arrangement that fits your needs. Here is how the example app adds it on the overview page 

https://github.com/backstage/backstage/blob/master/packages/app/src/components/catalog/EntityPage.tsx#L240

**Comment by falconbin** [comment]
> These pages are fully under the adopters' control. You'll have to add the various cards that you want, in some arrangement that fits your needs. Here is how the example app adds it on the overview page
> 
> https://github.com/backstage/backstage/blob/master/packages/app/src/components/catalog/EntityPage.tsx#L240

Thank you, @freben . 👍 The links are now shown. But the appearance doesn't looks well when the title is a bit long:
![image](https://user-images.githubusercontent.com/20329141/122876426-178b5980-d368-11eb-9f39-a935fa6ec5bc.png)

**Comment by freben** [comment]
Agreed! That's not nice. Would possibly be in a position to experiment and submit a fix? 🙌

**Comment by freben** [comment]
Eh, I got inspired :) https://github.com/backstage/backstage/pull/6156
