### ISSUE TITLE
[Plugin] catalog - show extra fields in component\overview page

### ISSUE THREAD

**Issue by falconbin** [backstage/backstage#6164]
Is there a way to show extra fields in component\overview page ? currently the overview page only show description, owner,system,type, lifecyle and tags. What if we have more elements ?

## Feature Suggestion
if not, maybe we can show the extra fields behind the last element(TAGS) or in a separate section?
![image](https://user-images.githubusercontent.com/20329141/122931254-4b35a600-d39f-11eb-80c9-223f0514d700.png)

**Comment by freben** [comment]
Sure! If you look in `packages/app/src/components/catalog/EntityPage.tsx`, you'll see that you are in full control of the entire web page structure and experience here. You can try to use the builtin cards and functionality exported from `core-components` and `plugin-catalog`, but you can also make entirely your own.

**Comment by falconbin** [comment]
> Sure! If you look in `packages/app/src/components/catalog/EntityPage.tsx`, you'll see that you are in full control of the entire web page structure and experience here. You can try to use the builtin cards and functionality exported from `core-components` and `plugin-catalog`, but you can also make entirely your own.

I'll try it tomorrow.

**Comment by falconbin** [comment]
We can define our own card to show extra information, so closed.
![image](https://user-images.githubusercontent.com/20329141/123043034-479b3100-d42a-11eb-8fed-82c727a6a40e.png)

**Comment by falconbin** [comment]
@freben , can you export AboutField under AboutCard? I have to copy the entire component for our use.

**Comment by freben** [comment]
The field component is already exported as such, but you are right that the card does not accept a custom list of fields yet.

Is that something you would like to contribute? Essentially, the card could accept an optional children prop, `children?: React.ReactNode`. If it is undefined, it renders the current list of fields. If it's defined, it renders only those fields.

This `children` prop will be passed down into `AboutContent` which is responsible for drawing them.

This would probably best be accompanied with having easy access to a set of default fields. See what the entity table does [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/components/EntityTable/EntityTable.tsx#L77) for inspiration. Maybe there would be `AboutTable.fields` which is all of the available default fields in an object, and `AboutTable.defaultFields` as an array, so you can do

```ts
<EntityAboutCard>
  {...EntityAboutCard.defaultFields}
  <MyCustomAboutField1 />
</EntityAboutCard>
```

where `MyCustomAboutField1` can use the `useEntity()` hook to get access to the actual entity that is being displayed.

**Comment by freben** [comment]
I made [an issue](https://github.com/backstage/backstage/issues/6175) with that information, so you or somebody else could pick it up at will.
