### ISSUE TITLE
New catalog engine produces duplicate groups 

### ISSUE THREAD

**Issue by KennyLindahl** [backstage/backstage#6179]
When doing the suggested changes of `catalog.ts` according to [0.3.26](https://github.com/backstage/backstage/blob/master/packages/create-app/CHANGELOG.md#0326) then it produces a multiplication of groups listed in the group and user page.

## Data used

```js
const parentGroup = {
  apiVersion: 'backstage.io/v1alpha1',
  kind: 'Group',
  metadata: { name: 'parent-group', description: '' },
  spec: {
    type: 'team',
    children: ['sub-group'],
    profile: { displayName: 'parent-group', picture: undefined },
    members: [ 'user' ]
  }
}

const subGroup = {
  apiVersion: 'backstage.io/v1alpha1',
  kind: 'Group',
  metadata: { name: 'sub-group', description: '' },
  spec: {
    type: 'team',
    parent: 'parent-group',
    children: [],
    profile: { displayName: 'sub-group' },
    members: [ 'user' ]
  }
}


const user = {
  apiVersion: 'backstage.io/v1alpha1',
  kind: 'User',
  metadata: { name: 'user' },
  spec: {
    profile: {
      displayName: 'User',
    },
    memberOf: [
      'parent-group',
      'sub-group'
    ]
  }
}

emit(results.entity(location, parentGroup));
emit(results.entity(location, subGroup));
emit(results.entity(location, user));
```

## Expected Behavior (using old catalog engine)

<img width="657" alt="Screenshot 2021-06-23 at 12 27 21" src="https://user-images.githubusercontent.com/1323068/123081622-70b5c480-d41e-11eb-8676-2d244557fe07.png">
<img width="658" alt="Screenshot 2021-06-23 at 12 27 11" src="https://user-images.githubusercontent.com/1323068/123081632-73181e80-d41e-11eb-95b1-cb023821eaa3.png">

## Current Behavior (using new catalog engine)

<img width="659" alt="Screenshot 2021-06-23 at 12 25 06" src="https://user-images.githubusercontent.com/1323068/123082302-2a149a00-d41f-11eb-80ad-0e11162306d7.png">
<img width="658" alt="Screenshot 2021-06-23 at 12 24 43" src="https://user-images.githubusercontent.com/1323068/123082308-2bde5d80-d41f-11eb-85d6-94e6ca130245.png">

## Possible Solution

If i set the properties `children` and `members` to empty array then it works as expected.

If this change is intended i can't see any documentation about it and you still set both `parent` and `children` in your [GithubOrgReaderProcessor](https://github.com/backstage/backstage/blob/9bc6c7860c9626af61dfca73b7ad47e349070ec2/plugins/catalog-backend/src/ingestion/processors/util/org.ts#L26-L50).

## Steps to Reproduce

See "Data used" section in the top, using the new catalog engine as instructed here:
https://github.com/backstage/backstage/blob/master/packages/create-app/CHANGELOG.md#0326

## Your Environment

- NodeJS Version: v14.16.1
- Operating System and Version: MacOS Big Sur 11.2.3
- Browser Information: Chrome 91.0.4472.114 (Official Build) (arm64)

**Comment by erikxiv** [comment]
I can reproduce the same issue with backstage master and the example data, so seemingly unrelated to GithubOrgReaderProcessor. Checking the data in the database (`final_entities` table) and the api response it seems that the group entities look like they should (parent, children have no duplicates) but there is duplicate `parentOf`/`childOf` relations. Other relations seems unaffected.

**Comment by freben** [comment]
I'd guess there's a regression in the dedupe logic in the Stitcher. We'll look into it!
