### ISSUE TITLE
plugin-tech-radar 0.4.0 lost support for multiple radars

### ISSUE THREAD

**Issue by ashirley** [backstage/backstage#6180]
As part of #5891 and release 0.4.0 of the tech radar plugin, it is no longer possible to have multiple radars in backstage. It used to be possible to define multiple routes in App.tsx and re-use TechRadarRouter with a different getData function for each.

e.g. 
```typescript
          <Route
            path="/be-tech-radar"
            element={
              <TechRadarRouter
                width={1500}
                height={800}
                getData={() => {
                  return getTechRadarLoaderResponse('Back-End');
                }}
                title="Back-End Tech Radar"
                subtitle="Home: https://example.com/display/radar/Tech+Radar+-+Home"
                pageTitle="Back-End Radar"
              />
            }
          />
          <Route
            path="/fe-tech-radar"
            element={
              <TechRadarRouter
                width={1500}
                height={800}
                getData={() => {
                  return getTechRadarLoaderResponse('Front-End');
                }}
                title="Front-End Tech Radar"
                subtitle="Home: https://example.com/display/radar/Tech+Radar+-+Home"
                pageTitle="Front-End Radar"
              />
            }
          />
```

## Possible Solution

The API exposed takes some sort of identifier (title? or a new id prop) in the `load` function so it can differentiate between the radars it is loading data for.

**Comment by freben** [comment]
Hi! Yeah an ID prop sounds like a viable solution here. Honestly I don't think we really thought that it'd be a use case with multiple radars, but looking back, it makes sense. Maybe it would be best to make it an optional property, making it a non-breaking change.

Is this something you might be interested in contributing?
