### ISSUE TITLE
can we overrite the static assets/files path during yarn build?

### ISSUE THREAD

**Issue by jsdorababu** [backstage/backstage#6182]
can we overrite the baseurl only for the static files during runtime or while doing yarn build?

We have a requirement where our base URL is something like https://demo.backstage.io
and want our static files to be stored in location https://demo.backstage.io/myassets

Currently static(or)asset files are stored in bundle in the https://demo.backstage.io/static 
but in the server we wanted our static(or)asset files to be stored in https://demo.backstage.io/myassets/static

**Comment by Rugvip** [comment]
Leaving this stale but anyone finding this, do chime in if you want this implemented. We could probably add something to the app configuration that controls it

**Comment by Rugvip** [comment]
Closing this to continue the discussion in #7285
