### ISSUE TITLE
Custom error messages/handling (for plugins and other components)

### ISSUE THREAD

**Issue by loujaybee** [backstage/backstage#6183]
Hello, Backstage friends! 🚀

## Feature Suggestion

As a Backstage implementer, I would like greater (or possibly full) control over error states from plugins. 

## Context

The example below is from tech docs, but there are other similar scenarios with this plugin and others in our implementation. Currently, the tech docs plugin shows an error message (example below) when the catalog annotation is not provided. The error state for tech docs on the client is private to the component ([e.g. tech docs error handling logic](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/components/Reader.tsx#L314)) the parent has no way to know the child component is or isn't rendering an error. 

However, in our case the error message presented is misleading as it shows an example relating to a catalog file, whereas in our implementation we're using a custom metadata file (with [a custom catalog processor](https://backstage.io/docs/features/software-catalog/external-integrations)) and not a vanilla catalog file, so in this case we'd want to override the error message and provide a custom one of our own...

<img src="https://user-images.githubusercontent.com/5528307/123158797-21928280-d464-11eb-831d-6fd79d4ce88d.png" alt="drawing" width="400"/>

## Possible Implementation

1. **Error states passed to parents**: Implement a best practice whereby all plugins include an interface (e.g. a callback for instance) which propagates internal error states to the implementing component so that they can handle the error states themselves. It would be interesting to come up with a generic contract here so that the API could be the same if adopted across other plugins. 

2. **Make error text configurable:** Implement a best practice whereby all plugins ensure that all error message text is configurable via the parent. In the case of tech docs, there's quite a bit of error handling, so this potentially could get quite messy.

3. **Throw errors** I'm not 100% on how this might work in reality, but a plugin could just throw an error explicitly, and leave it up to the implementer to handle the errors using [error boundaries](https://reactjs.org/docs/error-boundaries.html) / handling etc. 

I'd be happy to raise a PR for tech docs if we agree on the best way forward to manage this but ideally would like a pattern that could be implemented throughout other plugins, and not just tech docs... if possible.

**Comment by freben** [comment]
Hey, thanks for writing this up.

The app itself, on a higher level, has the [ability to supply](https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/app/types.ts#L170) "app components" that are used throughout the app. I wonder if it might actually make sense to think in the same way for this problem - essentially your option 2, but with a convention for an optional prop to the root component.

```tsx
<Route path="/docs" element={
  <TechdocsPage components={{
    missingAnnotation: <MyCustomPageForThat />
  }} />
} />
```

I was considering whether this could be supplied using the apiRef mechanisms as well. Like, a `techdocsComponentsApiRef` that returns a component per concern, too. Hm. That'll be pretty heavyweight but does let you specify it just once and apply across the app. Also may work best for future hosted scenarios?

There is one more option which is to use the new composability system with element extensions. I believe that is way too heavyweight / involved of a mechanism to use for something like this, so leaving that aside for now.

@backstage/maintainers Gonna ping you for some more input here I think. Maybe @Fox32 @andrewthauer @dhenneke et al have ideas too?

**Comment by andrewthauer** [comment]
There is related discussion in #3217 as well but it's purely focused on the empty state. So we could consider this issue partly a duplicate of that one.

I'm not really a fan of using an apiRef for this. There is too much ceremony involved for simply modifying the UI presentation / behaviour. I thin some sort of composition makes sense. A common prop that components expose to override the default empty state, missing annotation or errors would be ideal.

This can be worked around in the `app` as-is in many cases now, but it's not ideal imo. You can often wrap the component and do a check for the annotation and then display a custom annotation message/component. This however requires a lot of duplication and extra code though. But in a pinch this can work right now.

**Comment by dhenneke** [comment]
In this particular case, the missing annotation is not really a proper error but more a configuration hint. The code is also not in the linked Reader component but in the [wrapper component `EmbeddedDocsRouter`](https://github.com/backstage/backstage/blob/9258c54f874b8ba1e5a916caa14bfbe47204322d/plugins/techdocs/src/Router.tsx#L47-L63).

Would it be possible to extend the "app-wide component override" function with a "component/plugin specific component override" where we something like a hook that try to find the registered implementations for the component at the different levels?

**Comment by loujaybee** [comment]
> The app itself, on a higher level, has the ability to supply "app components" that are used throughout the app. I wonder if it might actually make sense to think in the same way for this problem - essentially your option 2, but with a convention for an optional prop to the root component. - @freben 

The most promising option on paper seems like the idea of having a centrally configured component, which could maybe take some props like an error code (and possibly a plugin namespace), and allows you to provide some case-like switch statement to check for the plugin + error code. But I guess that convention needs to be adopted throughout all components. 

> You can often wrap the component and do a check for the annotation and then display a custom annotation message/component. - @andrewthauer

That's true, we could make a helper for this, but I guess only tackles the configuration hint part rather than wider error handling. 

> The code is also not in the linked Reader component but in the wrapper component EmbeddedDocsRouter. - @dhenneke 

True, and good point. We do also want to mock the tech docs error which is linked (the 404 tech docs not found) in addition to the configuration hint. This is made a little more fiddly with techdocs as the "state" of whether the techdocs exists or not is not known until a request is send to grab them (additional context that I missed: we're fetching docs from S3).

As before, if we did decide on a way forward, happy to raise a PR that implements this pattern in techdocs, and we can extend the convention elsewhere.
