### ISSUE TITLE
[Plugin] Bugsnag

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#6200]
## Summary

[Bugsnag](https://www.bugsnag.com/) has a similar functionality to `rollbar` & `sentry` but optimized for mobile applications.

## Project website

https://www.bugsnag.com/

## Context

This plugin could follow a similar UI design to the existing rollbar and/or sentry plugins to start.

**Comment by dtuite** [comment]
@Irma12 is going to work on this plugin.

**Comment by Irma12** [comment]
Hey guys, yes, I would like to proceed with this one :)

**Comment by Irma12** [comment]
Hey guys this is out now https://www.npmjs.com/package/@roadiehq/backstage-plugin-bugsnag, there is a PR for adding it to marketplace :)
