### ISSUE TITLE
errorHandler middleware in backend-common throws Exception when serializing errors as JSON

### ISSUE THREAD

**Issue by GoWind** [backstage/backstage#6207]
errorHandler middleware in backend-common throws an Exception when serializing errors as JSON when the error object contains circular references.  As a consequence, instead of the errorHandler logging the error cleanly, further errors are thrown causing issues with the response. 

Also the entire stacktrace is returned in the response, leaking unnecessary details to the end user. 

Another side-effect is log pollution, where, due to the incorrect handling of `error` objects, the logs are full of error stack traces that make them unreadable. 

## Expected Behavior
A simple string representation of the error is returned in the response.

## Current Behavior
An exception is thrown when the errorHandler tries to log the error message: 
```
    "stack": "TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'EventEmitter'\n    |     property '_events' -> object with constructor 'Object'\n    |     property 'options' -> object with constructor 'Array'\n    |     index 0 -> object with constructor 'EE'\n    --- property 'context' closes the circle\n    at JSON.stringify (<anonymous>)\n    at stringify (/usr/src/app/node_modules/express/lib/response.js:1123:12)\n    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:260:14)\n    at /usr/src/app/node_modules/@backstage/backend-common/dist/index.cjs.js:749:28\n    at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:55:9\n    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:315:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at next (/usr/src/app/node_modules/express/lib/router/route.js:127:14)\n    at /usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:46:9\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
```

The problem seems to be the default serialization of the error as a `JSON` response [here](https://github.com/backstage/backstage/blob/4045eaab952fec349e443990330bd1ac5b2c9c18/packages/backend-common/src/middleware/errorHandler.ts#L96).

This triggers a naive `JSON.stringify` within `express` which leads to the exception being thrown. 

I also noted the `serializeError` function being used to safely serialize the error, but this piece of [code](https://github.com/backstage/backstage/blob/4045eaab952fec349e443990330bd1ac5b2c9c18/packages/errors/src/serialization/error.ts#L48) looks suspicious to me and I wonder if this returned object itself contains circular references, thus negating the safe serialization.

## Possible Solution

Winston already solved this [problem](https://github.com/winstonjs/winston/issues/978) by using a serialization method free of this issue: [here](https://github.com/winstonjs/logform/pull/35).

Also instead of calling `.json(body)`  on the response (which we know causes the problem), call `res.headers("Content-Type: application/json").send(serializedText)` to ensure that the problematic stringify isn't triggered. 

- NodeJS Version (v12): 14
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by freben** [comment]
Oof! I'll look at fixing that

**Comment by freben** [comment]
OK I have been trying this out. In a route:

```ts
const e = new Error('a') as any;
const a: any = {};
a.a = a;
e.a = a;
throw e;
```

this is handled correctly:

```json
{
  "error": {
    "name": "Error",
    "message": "a",
    "a": {
      "a": "[Circular]"
    },
    "level": "error",
    "service": "backstage",
    "stack": "Error: a\n    at eval (webpack-internal:///../../plugins/catalog-backend/src/service/router.ts:80:19)\n    at handleReturn ...
```

So I am curious why your occurrence of circularity wouldn't been handled. We do have an explicit serialization in place which is [supposed to handle](https://www.npmjs.com/package/serialize-error) these

**Comment by freben** [comment]
Is this error object somehow under your control? Is it expected that it contains an `EventEmitter` really?

**Comment by freben** [comment]
If you check the serialization library's [documentation](https://www.npmjs.com/package/serialize-error), it says "Non-error values are passed through. Custom properties are preserved.", and "If the input object has a .toJSON() method, then it's called instead of serializing the object's properties. It's up to .toJSON() implementation to handle circular references and enumerability of the properties.". I wonder if there's something that could be done in that regard on your end.

**Comment by GoWind** [comment]
I will investigate a little bit more deeply. The entire structure of the object is not clear to me at the moment. (perhaps) the object that extends the `EventEmitter` has a custom `.toJSON()` method. Will investigate further and update this ticket, if it is still a bug in the middleware.

**Comment by freben** [comment]
It could be, that it might make sense to switch out the serialisation library to one that handles this better (and which does descend into even "unknown" values and treat them as well). But yeah before diving into that it would be neat to see if there are more learnings or alternative paths to take to avoid the situation.

Could also be really thorough and do custom JSON.stringify as you mention, using something really simple like mentioned here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value#circular_references
