### ISSUE TITLE
Allow the catalog import client for other Git providers

### ISSUE THREAD

**Issue by biki0109** [backstage/backstage#6209]
Hi, it would be great if Backstage add another plugin for other Git providers, such as Gitlab or Gitlab Enterprise in the search and analyze url step of the catalog import client. This idea maybe has been raised before.

## Feature Suggestion

On this page there are currently 4 steps. Add an additional step at first to select the Git provider using a dropdown or use the Git provider based on the login type of the current user.
![image](https://user-images.githubusercontent.com/48164880/123321665-7534c700-d55d-11eb-9dbd-a0e63c684f46.png)

## Implementation suggestion

Maybe create a copy of `plugins/catalog-import`, add new changes to the file `plugins/catalog-import/src/api/CatalogImportClient.ts` for other Git provider.

The steps would be similar, analyze url and search the repo using the current Git provider API with the appropriate of the application secret. For Gitlab, `['read_api']` would be for search of catalog-info.yaml file and `['api']` would be for the main flow of import, similar to Github. 

The create merge request flow could use `Gitbeaker/node` or use Gitlab api/v4, similar to Github using `Octokit`

## Context

There are many organizations currently using Gitlab for their microservices. Backstage would be ideal to keep track of their system.

**Comment by freben** [comment]
The intent here is that you should be able to paste any URL, for any provider that your org has configured, and it should "do the right thing". So I think there should not need to be a picker as such upfront.

Extending the capabilities of this plugin is highly desirable though! Both in the flow of importing existing yaml files, and in the "suggest creation of a new yaml file" flow.

**Comment by Rugvip** [comment]
Groundwork for auth for this is done in #7002, but it still needs more logic for each provider
