### ISSUE TITLE
Bitbucket cloud auto Discovery

### ISSUE THREAD

**Issue by azhurbilo** [backstage/backstage#6216]
## Feature Suggestion

Now only on-premise bitbucket server supported https://backstage.io/docs/integrations/bitbucket/discovery

It will be great to support Cloud version too https://bitbucket.org

**Comment by freben** [comment]
Agreed! Would you like to take a stab at making that work?

**Comment by FilipSwiatczak** [comment]
FYI I've pulled changes by @barticus to my local contributor installation of backstage and the auto discovery for BB cloud is working well.
Ps.: does anyone know how to pull specific commit/pr for a particular package update inside lerna monorepo? I've copied the changes manually but using yarn add <url/commit ref> doesn't work. Cheers!

**Comment by FilipSwiatczak** [comment]
Also I've noticed the processor polls for changes very frequently resulting in rate limit being hit for BB cloud users. 
A setting for polling interval in ms would be desirable!

**Comment by aravindparappil46** [comment]
Just adding my thumbs up here! This would be a great value-add and would save a lot of time for organizations on BB Cloud!
