### ISSUE TITLE
Improve type-soundness by extending the Window interface

### ISSUE THREAD

**Issue by TejasQ** [backstage/backstage#6220]
We assert that `window` is `any` in multiple places in this project like so:

https://github.com/backstage/backstage/blob/4f5ef39cb91f61821315db5867fc5803c79a2e1b/packages/core-app-api/src/app/createApp.tsx#L82

This is dangerous because it makes the code unreliable and unpredictable. To remedy this, we can use interface merging to add optional properties to the global `Window` interface that will allow us to take full advantage of TypeScript's static analysis.

**Comment by freben** [comment]
Sure! But I'd argue that those types should be local to only the part that uses them and not leak to the outside. So no "central" extension or type.ts file. For your example, I believe the scope of that type would be only inside that exact file (I may be wrong about that! But I think it's only webpack that's the other party that interacts with it) so we could add that type at the top but its value might be rather low - it'd just avoid an occurrence of the `any` keyword basically. Granted, there may be other places where the value of window typing might be higher.
