### ISSUE TITLE
Rendering logic change for SVGs on Techdocs breaks our Backstage instance.

### ISSUE THREAD

**Issue by GoWind** [backstage/backstage#6222]
[Commit](https://github.com/backstage/backstage/commit/1b24ae1c7fc7611213bb9d7a0fbbd66726835752) changed the behaviour of the Techdocs plugin for rendering SVGs from browser initiated requests to `Fetch` based requests. 
This broke our Techdocs plugin, as all images are considered sensitive and thus not authorized without a valid Authentication Header/Cookie.

Previously, to solve the problem, we had set session cookies on our Authentication responses, that will be sent by the browser when making requests to the backend for images. 

Changing this to `fetch` broke this behaviour, as `fetch` does not by default send Cookies, unless explicitly opted in via passing the parameter `credentials: include`. 

## Possible Solution

1. Obtain the Tokens and set the right headers  on the request from techdocs plugin before making fetch requests to the backend.
(OR)
2. Add a `credentials: include` option in the parameters to the `fetch` request.

My Vote would be for Option 2. I would also like to provide a PR for this.

Authorization is important for any image based data, as they could consider sensitive domain information such as data schemas, architecture diagrams, credentials etc.

## Steps to Reproduce

Require authentication information on routes for techdocs resources on the backend. 
Open any documentation that needs SVG based resources that are access-controlled.

**Comment by iamEAP** [comment]
Thanks for the report @GoWind!  I like option 2 as well.  If you're willing to contribute as a PR, even better!

**Comment by GoWind** [comment]
Awesome. I will send a PR soon :)

**Comment by iamEAP** [comment]
Closing this out because...  It's fixed!  Thanks again for the contribution.
