### ISSUE TITLE
PlantUML as svg_object  not rendered in techdocs

### ISSUE THREAD

**Issue by Crevil** [backstage/backstage#6232]
## Expected Behavior

When using the PlantUML plugin in techdocs with the `svg_object` option it should render the drawings.
Available formats are documented in the [`plantuml-markdown` plugin](https://pypi.org/project/plantuml-markdown/).

## Current Behavior

Nothing is rendered as `sanitzeHtml` strips the `object` tag.
This change was introduced in https://github.com/backstage/backstage/commit/348c46896fed3a0b92bd376ad5825323637e402a unfortunately there are no context in the commit message as to why this was removed nor is there a PR reference (that I found).

## Possible Solution

Allow `object` tags again or we should make sure to document this limitation of the PlantUML plugin.

## Steps to Reproduce

Add a PlantUML tag to a tech docs document with the format set to `svg_object`.

````
```plantuml format="svg_object"
Alpha->Beta: Hello
```
````

When testing with `techdocs-cli` it shows correctly, but when browsed in backstage an empty `<p>` tag remains after the generated `<object>` tag is sanitized.

## Context

After upgrading backstage we noticed that no PlantUML diagrams were rendered in our techdocs.
We use the `svg_object` format extensively.

## Your Environment

- NodeJS Version (v12): v14.16.0
- Operating System and Version (e.g. Ubuntu 14.04): Alpine 3.13

**Comment by iamEAP** [comment]
Hey @Crevil!  Unfortunate that the details are not really well-linked in that commit.  For a little bit more detail, check [this out](https://github.com/advisories/GHSA-gg96-f8wr-p89f).

You should be able to swap out `svg_object` for `svg_inline` to get the same set of features as you had previously.

**Comment by Crevil** [comment]
That makes sense, thanks for linking that up.

Should we add a notice to the tech-docs plugin documentation that the `svg_object` is not allowed? Maybe with a link to the advisory?

**Comment by iamEAP** [comment]
That's a great idea. Was looking for a good spot... Maybe under troubleshooting?

**Comment by Crevil** [comment]
I have added a PR to both techdocs troubleshooting and the mkdocs plugin. Hopefully that can help others in the future.

**Comment by iamEAP** [comment]
Closing this out now that the docs changes above are in!  Thanks again.
