### ISSUE TITLE
useEntity not working after killing first nodejs process

### ISSUE THREAD

**Issue by matthisholleville** [backstage/backstage#6233]
Hello,

I'm trying to develop a backstage plugin. When I use the useEntity function directly in my component I get the following error:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component.
```

What is strange is that I had no problem when I developed my plugin. I started to get the error when I killed my process node and then restarted.

Would you know from where to tell me if this is a bug or just a bad understanding/use of the method?

## Steps to Reproduce

1. Create a component in your plugin
```
import {useEntity} from "@backstage/plugin-catalog-react";

export const MyComponent = () => {
  const { entity } = useEntity();
  return ();
}
```
2. Configure your plugin with this
```
import {createPlugin, createRoutableExtension} from '@backstage/core';

import { rootRouteRef } from './routes';

export const myPlugin = createPlugin({
  id: 'my-plugin',
  routes: {
    root: rootRouteRef,
  }
});

export const EntityMyPlugin = myPlugin.provide(
    createRoutableExtension({
        component: () =>
            import('./components/MyComponent').then(m => m.MyComponent),
        mountPoint: rootRouteRef,
    }),
);
```
3. Add your custom entity in your `EntityPage.tsx`

```
<EntitySwitch>
    <EntitySwitch.Case>
      <EntityMyPlugin />
    </EntitySwitch.Case>
<EntitySwitch>
```
## Your Environment

- NodeJS Version (v12): v12.22.1
- Operating System and Version (e.g. Ubuntu 14.04): macOs Big Sur 11.2.3
- Browser Information: Chrome

**Comment by matthisholleville** [comment]
Now only by restarting the nodejs process I don't have the same error but the attribute is suddenly undefined

**Comment by freben** [comment]
Haven't seen this one before! :)

So this is while developing, which means it's using hot reloading and stuff. And if I understood correctly, you killed the service and restarted it, so I guess it would get a severed connection to the dev server for a while.

Does this happen consistently? Are you doing something exotic at all? How do you kill the process? Doing anything else while his all is going on, such as upgrading packages?

**Comment by freben** [comment]
Googling for the issue shows people encountering this in weird circumstances where their node_modules folder has gotten in a weird state. Might be worth wiping the working dir entirely, re-cloning and seeing if it persists

**Comment by matthisholleville** [comment]
Indeed, by deleting all the node_modules everything works again... Sorry for the lost time and thanks for your answer

**Comment by freben** [comment]
No worries, we learned something! Haha what a bug
