### ISSUE TITLE
Catalog Overview Page - owner column should use 'display name'

### ISSUE THREAD

**Issue by sherlockshao** [backstage/backstage#6237]
In the overview table of Catalog Page, the default owner column display the related user/group metadata name.
In our case, the metadata name filed should be an id to ensure the uniqueness(username would duplicate), but we want to view the user's display name in the overview table.

So is it possible to use the 'display name' or another filed as a replacement?

**Comment by Fox32** [comment]
You should already be able to replace the owner column with a custom one, that has this behavior. You can pass [`columns` to the `CatalogTable` ](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L54) which can be different from the [`defaultColumns`](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L43-L51). The default implementation for the [owner column](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/columns.tsx) uses the entity relations to display the name. In your case it get's a bit more complicated as you have to fetch the user/group entity first to resolve the `displayName`. You can use the catalog API for that.

**Comment by sherlockshao** [comment]
Thank you, It's a kind of solution, but currently I only need to customize the owner column.
So is it possible to export the [columnFactories](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/columns.tsx), so that I can use the other default columns.

**Comment by Fox32** [comment]
Oh, if they aren't, that is probably a mistake. Or they are exported by `catalog-react`, not sure though

**Comment by sherlockshao** [comment]
Find it, let me try.

**Comment by freben** [comment]
Just a small hint. I think it can easily get a bit expensive to fetch the names of these users. You will probably want to use some heuristic so that you can choose to either batch-fetch users by their refs if it's a small number of them, or get all users and groups with carefully sliced out `fields` (so the response doesn't get huge) once upfront, and pick among those.

When we get around to fronting the catalog with a graphql layer, this will become a lot easier and faster.

**Comment by sherlockshao** [comment]
Sorry for late update, because I'm still working on how to retrieve users' display name if they are already in database by default behavior.
I just found the front end call `/entities?filter=kind=component`, and with seldom users info(metadata name, namespace, kind) include in respond.
I wonder if I can pass some filter to get users' display name, and if It's the best practice for the time being.

**Comment by freben** [comment]
No, that's not possible.

Those three (kind + namespace + name) are [the triplet that uniquely identifies](https://backstage.io/docs/features/software-catalog/references) a given entity, so it's the "ID" of the target of the relation. The API has no graph edge traversal capabilities. As mentioned in the comments above, you will have to take those "IDs" and make additional calls to the catalog to get the actual entities that they correspond to - and those may or may not exist, as well. This will come with a nontrivial performance cost.

**Comment by sherlockshao** [comment]
OK, got it. Thank you very much.
