### ISSUE TITLE
Mobile & responsive improvements for sidebar

### ISSUE THREAD

**Issue by tudi2d** [backstage/backstage#6239]
I would like to work on this :) 

With this ticket I want to improve the UX of the Sidebar in Backstage for devices, which are not desktop clients. This ticket is not meant to change the UI of the Sidebar - it should just be better useable across devices.

## Feature Suggestion

- Don't expand Sidebar on click, as it hides most content after already redirecting to the clicked page
- Add a wrapper component for the possibility to make plugins scrollable to avoid a cut-off (not the whole sidebar though, like introduced in #3556)
  - Add Wrapper for SidebarItems. Org-specific items will take as much space as there, but plugins will be scrollable like Shortcuts are right now
  - Allows the sidebar to be always completely visible & SidebarSettings to be reachable anytime

## Context

https://user-images.githubusercontent.com/8904624/123631025-8ceaa480-d816-11eb-9764-612620644fe5.mov

**Comment by freben** [comment]
Nice. When you mention the scrollable / size limited stuff, do you mean you'd apply something akin to a min-height to those or something?

**Comment by freben** [comment]
Swipe open the sidebar with touch gestures would be nice too, if we don't already have that. I believe the MUI sidebar stuff has support for that now?

**Comment by tudi2d** [comment]
> When you mention the scrollable / size limited stuff, do you mean you'd apply something akin to a min-height to those or something?

Yes. I replaced the min-height with height for the page & added a wrapper component used for the plugins & shortcuts in the sidebar.

> Swipe open the sidebar with touch gestures would be nice too, if we don't already have that. I believe the MUI sidebar stuff has support for that now?

Good point - that would be nice indeed! I went through the MUI docs, found the [Drawer](https://material-ui.com/components/drawers/#drawer) & will give it a go. Thanks! :)
