### ISSUE TITLE
auth-backend: implement auth handler and sign-in resolvers for more auth providers

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#6245]
## Background

The Google auth provider has adopted a new pattern for making the authentication more configurable in #4532. The PR added a way to configure both an auth handler and a sign-in resolver, with both of them being callbacks that are called at different points of authentication.

The auth handler is responsible for validating each login and generating a lightweight profile for the user which is used in the frontend only to be showed to the user themselves so that they know what account they are logged in with. The auth handler can also throw an error in order to completely reject the authentication.

The sign-in resolver is responsible for assigning a Backstage Identity to the user. Long-term this will be an optional step that is only implemented for the auth providers that integrators want to use to identify users in Backstage, as opposed to other providers that may only be used for access to third party resources.

You can read more about the auth handlers and sign-in resolvers in the [documentation](https://backstage.io/docs/auth/identity-resolver).

## Future Work

The pattern established in PR #4532 is something that we want to apply to all our current authentication providers, in order to provide more power to the configuration of all different auth providers.

The following is a list of all auth providers and whether they have been refactored or not:

- [x] Auth0 #8658
- [x] AWS-ALB #7380
- [x] GitHub #6912
- [x] GitLab #6535
- [x] Google #4532
- [x] Microsoft #6430
- [x] OAuth2 #6512
- [x] OIDC #8318
- [x] Okta #6713
- [x] OneLogin #8658
- [x] SAML2 #8331

The maintainers will work to migrate these providers over time, but we are thankful for any contributions that help speed up the process 🙏 

## Refactoring

In order to make contributing easier these are some pointers to guide the process. While PR #4532 serves as a template, it may not be easy to see what work was done and why. When migrating a provider, the main chunk if not all of the changes happen in the provider file itself, meaning that if you're looking at the PR it's the changes inside `packages/auth-backend/src/providers/google/` that are the most interesting.

The refactoring can be broken down into these steps:

- The `create*Provider` method should already have an `options` parameter that is probably unused, add the `authHandler` and `signIn.resolver` options to it in the same way as is done in the Google provider. The type parameters of the two options should match for example the first type parameter of `executeFrameHandlerStrategy`, for OAuth-based providers it's `OAuthResult`.
- Refactor the provider class so that the auth result is handled in a single place, if this is not already the case, this is the `handleResult` method in #4532. If the callback passed to the passport strategy is doing a lot of work you will want to refactor it to do as little as possible and move that work out.
- Add `authHandler` and `signInResolver` options to the provider class and use these to transform the auth result, typically replacing things like `makeProfileInto`, `this.tokenIssuer.issueToken` calls. You will likely also need to add new members to the class to be passed on in the context of the `signInResolver` call. Note that the `signInResolver` should be optional and only be used to populate the `backstageIdentity` in the result if it is defined.
- Move the old auth handling and sign-in resolution logic into new functions that we'll use as the default implementations, these are the `googleDefaultSignInResolver` and inline `makeProfileInfo` call in the Google auth provider. Note that any existing sign-in logic is likely sub-optimal, but we keep it in place as is and make it the default in order to avoid a breaking change.
- Refactor the `create*Provider` implementation to pass on the new options and fall back to the defaults, similar to how `createGoogleProvider` was changed in #4532.
- Update or add tests! See #4532 for how to add some basic tests, and don't hesitate to move this step earlier if you want to.
- If there are any obvious additional sign-in resolvers that could be exported along with provider, implement and export these as part of the provider. An example of this in #4532 is the `googleEmailSignInResolver`.
- Chime in in the comments if I missed anything 😉

**Comment by akibabu** [comment]
Don't have the bandwidth to try this out, but casting my vote on Okta and GitHub :grinning:

**Comment by GoWind** [comment]
I can take a shot at this for the Generic `OAuth2` authentication provider. Also I noticed that I can improve the documentation around Identity and Authorization a bit more as a part of the task.

**Comment by Rugvip** [comment]
@GoWind awesome, thank you!

**Comment by chicoribas** [comment]
I'm working on Microsoft refactor... I'll PR it soon...

**Comment by chicoribas** [comment]
PR for Microsoft provider opened: #6430!

**Comment by Rugvip** [comment]
Thank you @chicoribas!

We now also have #6430 to serve as a reference for the refactor 👌

**Comment by tom-odb** [comment]
Opened a PR for GitLab: https://github.com/backstage/backstage/pull/6535

**Comment by Symbianx** [comment]
Opened a PR for Okta as well https://github.com/backstage/backstage/pull/6713

**Comment by Andrew-Wichmann** [comment]
Hi, I am not very versed in the security/authorization realm, but I've been charged with blocking unauthorized access to our Backstage deployment. Can you tell me if this issue resolves [this note](https://backstage.io/docs/auth/using-auth#identity---wip) in the documentation?

**Comment by Rugvip** [comment]
@Andrew-Wichmann It does not.

The best way would be to do what the note suggests, as in using something like IAP. In your case probably AWS ALB, [which you can also use for sign-in](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/aws-alb-aad-oidc-auth.md). There's also a [tutorial in contrib/](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md) on how to protect a Backstage instance itself, but it is a community effort only at this point as we're not supporting that just yet.

**Comment by lihongbj** [comment]
@Rugvip , @freben ,
How are you. 
We are evaluating backstage for our team dev work,  I am not sure if this is the right place to ask help for my question: 
 --  **Does backstage support multiple github user/account auth?**

To auth single github user, below `auth` config can be applied in `app-config.yaml`, and env variable `AUTH_GITHUB_CLIENT_ID` can be set for one github user: 
```yaml
auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
```

How to config and auth **other github users**?  Does backstage support **multiple** github user/account ?  `clientId` in `github` seems only accept single value.
Thank you for your help in advance.

**Comment by Rugvip** [comment]
@lihongbj the `clientId` and `clientSecret` are for either [GitHub Apps](https://docs.github.com/en/developers/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps) or [GitHub OAuth Apps](https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app), both of which support authentication of multiple users. There's a bit more info on that in [the auth setup docs](https://backstage.io/docs/auth/github/provider) too

**Comment by lihongbj** [comment]
@Rugvip , thank you very much for your kind help. It works now.

**Comment by Rugvip** [comment]
Finally done 😅

Big thanks to everyone that helped out!
