### ISSUE TITLE
Add AWS s3 integration for reading data from s3 buckets 

### ISSUE THREAD

**Issue by kjost-splunk** [backstage/backstage#6250]
## Feature Suggestion

I want to add AWS S3 integration to read data from a s3 bucket. This can be like the data reading integration that already exists for Google GCS ([GoogleGcsUrlReader.ts](https://github.com/backstage/backstage/blob/4045eaab952fec349e443990330bd1ac5b2c9c18/packages/backend-common/src/reading/GoogleGcsUrlReader.ts)).

I would like to work on this. 

## Context

For the purpose of reading .yaml files from an aws s3 bucket for service catalog data.

**Comment by freben** [comment]
Sure, cool! Assigned.

**Comment by seant-splunk** [comment]
Hello, I am working alongside kjost-splunk on this issue. Would you mind assigning me to this issue as well?

**Comment by loujaybee** [comment]
@seant-splunk / @kjost-splunk we also need this feature, let us know how you get on and if you need any support, we potentially can implement, also.

**Comment by kjost-splunk** [comment]
@loujaybee we are working on implementing it now, should be done in the near future!

**Comment by OrkoHunter** [comment]
Since you all are writing a URL Reader, I'll appreciate your feedback on https://github.com/backstage/backstage/pull/6313

Give a shoutout if there's anything you find confusing or want to be documented.

**Comment by seant-splunk** [comment]
Hello! I just have a minor suggestion, for the section "Using inside a plugin" it may be helpful to add 'URL Reader' to the title, I.e. the title would be "Using a URL Reader inside a Plugin".
