### ISSUE TITLE
Allow system in systems or domains in domains

### ISSUE THREAD

**Issue by jcarres-mdsol** [backstage/backstage#6269]
## Background

In our company we have services that are deployed as multiple containers. 
Let's say the User service is an API container , a worker container in charge of notificaitons, another container dealing with audits, etc. 
This service is part of what we call the platform which itself is part of our SaaS offering
In backstage terms I think the proper way would be:
- component = Each container type
- system = User service
- Domain = Platform
- Domain = SaaS (hasPart Platform)

But it seems `partOf` does not work between Domains, at least seems to be failing for us and [the test](https://github.com/backstage/backstage/blob/4045eaab952fec349e443990330bd1ac5b2c9c18/plugins/catalog-backend/src/ingestion/processors/BuiltinKindsEntityProcessor.test.ts) does not seem to test that so probably the code does not allow it.

## Feature suggestion

For flexibility I think Domain as part of Domain makes sense, there will be companies with even more convoluted or deeper kind of structure than us. 
In the same line I think System as part of System makes sense also, in fact I think we have that case also here but I have not looked at that in detail yet.

## Possible Implementation

No idea of the effort involved.

**Comment by andrewthauer** [comment]
Curious, are your different role containers deployed at be the same time? Is the related code in a single repo or multiple?

Have you thought about using `subcomponentOf` to model some of your containers instead of parts of a system directly?

As for domain of domain it sounds like you asking for sub domain support. This probably makes sense  and could be useful. However, I think the relation type `partOf` might be confusing and calling it `subdomainOf` might be more clear.

Also, in your case is platform also a team? Just wondering if it could make sense to model this as platform = owner of various systems, and SaaS as the domain for those systems and possibly others.

**Comment by jcarres-mdsol** [comment]
Good questions. 
Yes, one system/service lives in one repo and multiple containers may be deployed out of this codebase. Obviously the starting point of each container is differnt but they may share a bunch of things, like the models to access the DB.

If I understand your `subcomponentOf` suggestion, you are saying that the service should be a component and the containers be subcomponents of that?

About the organization, yes. more or less:
service -> owned by engineering manager
platform -> owned by director
SaaS ->  owned by CTO

we have other possible domains, at the same level than platform like data fabric, etc.

**Comment by andrewthauer** [comment]
> If I understand your subcomponentOf suggestion, you are saying that the service should be a component and the containers be subcomponents of that?
If so would this make sense?

I think it could make sense, but it's probably up for debate and open to interpretation. There are 2 main considerations for modelling imo. One is the logical view of how an organization might want it described and the other is how it's presented in Backstage. 

For example, the common pattern to customize how the EntityPage presents data is to use a components `spec.type`. However if you had say a single repo with multiple component services you could end up with each sharing the same CI, quality, docs data. This might make sense but could also be slightly confusing. Being able to sub classify parts of a repo and maybe turn off / hide backstage features in the UI likely requires  more then just component type. I've done some initial experimentation in a similar fashion to your setup where a there's a top level service component and then sub components for different roles. Then tried to customize the EntityPage accordingly. However I'm still not  set on a perfect path forward here.

Perhaps others could chime if they have other thoughts on this. I think it's an interesting discussion that is very relevant to how you decide to model relations of components and system.

**Comment by andrewthauer** [comment]
@jcarres-mdsol - I agree, Platform doesn't seem like a system. However, I'm not sure Platform needs to be a system in this example. Why not just create a User Service system that contains the User Service component? The component will drive the backstage source code based functionality while the system is a higher level logical representation of functionality.

**Comment by jcarres-mdsol** [comment]
That was our initial thought but then there is only one entity over the services (domain) and we are going to have a deeper structure than that. Thus the original idea in this issue which is to allow domains to be contain in bigger domains or system in systems or both

**Comment by freben** [comment]
The [format docs](https://backstage.io/docs/features/software-catalog/descriptor-format) are always the authoritative source for what you can do with the files, and indeed there is no such field currently for the `Domain` kind.

You could fairly easily [add that field](https://backstage.io/docs/features/software-catalog/extending-the-model#adding-new-fields-to-the-spec-object-of-an-existing-kind) as a local concern to your own org. It would involve making a custom catalog processor to take that `spec` field and emitting relations based on it, similarly to what the [builtin kinds](https://github.com/backstage/backstage/blob/0fec73ac8e7a5b1c694680ef7babe6cb47cd13ca/plugins/catalog-backend/src/ingestion/processors/BuiltinKindsEntityProcessor.ts#L178) processor does.

I think we can say with some confidence that we won't want to introduce any explicit hierarchy into the core system model, that's deeper than what we have today. But wanting to declare that things are `partOf` a greater whole "sideways" so to speak in the model, as you mention, could still make sense!

**Comment by andrewthauer** [comment]
@freben - I'm curious on a standard convention to model a service that has a few components/containers (e.g. `api`, `queue`, `worker`, etc.) but is contained with a single repo. These could be modelled as a single component service, or as separate services with a system that they are part of. In the latter case, each of these component containers would end up being separate catalog entities, but they also end up sharing much of the same underlying data that is presented in the EntityPage (e.g. quality metrics, readme, PRs, CI results, etc). Are there any recommendations on the based way to model this sort of service?

**Comment by freben** [comment]
@andrewthauer Hm. I think that them being in one repo isn't necessarily an indicator either way. It could even be the case that if you have several things that are strictly co-deployed for example as one main container and several sidecar containers ... then those could hypothetically be modelled as a single unit Component. I think ultimately, often these decisions come down to how people think of their things. What's the "unit" of "thing" as you think of it and deploy it and manage it? That's probably a good boundary around the component. What you described did sound more like several separate components, and they would probably have a lot of things separate from each other too. Shared CI, sure, that's one piece of tooling that might start to seem muddled. Maybe in some cases there's an annotation to put on the individual components to discern them from the others in the backing system - for example, if they have test coverage metrics, maybe there's an annotation saying "i'm the one that's in folder `plugins/x`" to show the right slice of data.

Then what granularity to make systems into ... Yeah it's hard to give a single coherent answer to

**Comment by andrewthauer** [comment]
@freben - Thanks that is useful to think about in this way. We have many cases where a repo maps to what we call a service. The service consists of an API container, queue container, poller/consumer container, etc. Often these are the same code base and are just setup to run as different roles. In some cases there are completely different packages within the repo and may have different Dockerfiles. However in both cases it's common for the deployment to trigger a re-deploy of all of these. So to your point the most logical approach for us is to use a single service component to define these. 

However, in some cases we want to create a logical breakdown of the service which is where it becomes a bit more muddy and subjective as to the best approach in regards to the Backstage catalog.

I think it might be beneficial if there were some more detailed examples for various scenarios and possible approached to handle the modelling. Right now, there's lots of options for eco-system modelling but its not always completely clear what is the best approach is and what are the pros/cons & trade offs for a specific approach.

**Comment by freben** [comment]
Hm! Interesting way of arranging things... Yeah I'm not sure my initial answer is perfect either. Not gonna have time to fill in more right now sadly.

Yes docs by example is something I think we need in general. Especially for the most flexible aspects - the system model, deployment methods, auth scenarios...

**Comment by jcarres-mdsol** [comment]
@andrewthauer  we have exactly the same setup here. 
And similar conundrum. 
In our case for instance we need to audit changes to our data, so basically all services send information to the audit system but for performance reasons that's not done by the container exposing an API but it happens in a background container/lambda. 

And when it comes to use `dependsOn` it feels it is different to depend on an API which is hard dependency and if not available your own API can't respond than to depend on the audit service that if down you just delay audit information , it will be sent later.

But if we break into components and `system` is used for the abstract idea of service, then we have the problem of only having one layer (domain) above which is not enough to model the organization of our company

**Comment by andrewthauer** [comment]
Yep, I'm not sure the best answer here. There are a few variables at play. The orgs setup, how they view their systems/services, and how the org wants to see the data presented in Backstage.

It can be tricky in some cases to come up with the right blend. One reason, we've been kicking the can the road as far as ecosystem modelling goes.

**Comment by jcarres-mdsol** [comment]
This is still a  major headache.

In our company, depends on the service, we may have 3 or 4 layers in the organization.
For instance, we deploy an opentelemetry-collector for our traces. In the org this is:
```
Otel-collector -> telemetry -> observability -> Internal tools
```
None of these can be skipped.  We have other internal tools, like `deployment` or `testing`.  We have ton of different things in `observability` and we have multiple things within `telemetry`

In other cases, we have one less layer:
```
profile service -> users -> platform
```

Again, for reasons, this makes sense as it is.

As systems can't be part of systems I lack one layer to do the first case, so far I could only think of two potential solutions for that:
- Make the top level Groups `Platform` group, and `Internal Tools` group
The problem here is that a `domains` view will not make sense, it will be sparserly populated, it will only exist when there is a need of that extra layer, else not. In this case `observabilily` would be domain but on the platform example there will be no domains.
- Make the lowest level a subcomponent. So `users` , `telemetry` would be `Component` and the real services also and be a subcomponent of the above. This has the problem that in the default component view both will mix, although we would create a `kind` for the abstract entity and we can filter by it, etc. seems a lot of work.
