### ISSUE TITLE
[scaffolder] add a node-based templating action

### ISSUE THREAD

**Issue by mtlewis** [backstage/backstage#6285]
## Feature Suggestion

Create a new scaffolder action which only uses node.js dependencies that templates can use instead of `fetch:cookiecutter`. This new action would be an addition alongside `fetch:cookiecutter` and not a replacement. This proposal doesn't imply removing or changing `fetch:cookiecutter` in any way.

## Possible Implementation

We no longer support running any additional scripts as part of the scaffolding process. Most of our internal templates have very modest needs, in terms of just wanting some basic `jinja` syntax replacement and control statements.

It should be possible to implement a simple `cookiecutter` replacement with pure Node code, which traverses the input directory and copies things to the output directory while running for example [jinja-js](https://www.npmjs.com/package/jinja-js) or similar on file/dir names and contents.

If none of the templates in a given Backstage instance use `fetch:cookiecutter`, this would allow integrators to skip installing the cookiecutter CLI and its dependencies.

## Context

The current implementation of the `fetch:cookiecutter` action in the scaffolder backend plugin relies on either (1) docker being available to run cookiecutter in a container, or (2) a local version of  the `cookiecutter` CLI script.

The former leads to annoying docker-in-docker problems in some environments. The latter requires the Backstage operator to figure out how to get cookiecutter injected into their actual production runtime environment, which can be nontrivial.

This is a recurring source of confusion and frustration, as evidenced by Discord and GitHub support discussions. We should be able to implement this without the requirement on an external `cookiecutter` in the runtime environment. By adding an additional action instead of changing the existing one, we can mitigate this pain for users that want to avoid the cookiecutter and python dependencies without breaking existing templates.

**Comment by benjdlambert** [comment]
https://mozilla.github.io/nunjucks for reference too. Thinking that `jinja-js` is a little unmaintained and a little inactive for consideration maybe.

**Comment by timbonicus** [comment]
Yeah to reinforce that, the [jinja-js repo](https://github.com/sstur/jinja-js) has a deprecation notice 😅 

> This project has not been actively maintained for almost 7 years at the time I'm writing this. I do not recommend using this.
