### ISSUE TITLE
[scaffolder] Update default templates to use new templating action

### ISSUE THREAD

**Issue by chaseajen** [backstage/backstage#6286]
## Feature Suggestion

Update the scaffolder templates which currently use the `fetch:cookicutter` action to use the new nodejs-based templating action created in #6285.

## Migration plan

The plan below is one potential option; however, other migration plans should be explored based on desired template distribution plans. @backstage/maintainers please let us know your thoughts.

### Possible plan
1. Copy existing sample templates into [software-templates repository](https://github.com/backstage/software-templates) (this will also close #3383)
1. Update templates in software templates repo to use new nodejs-based action
1. Update example app in this repo to ingest templates from the new location (which use the new action)
1. Update `README` in software-templates repo to indicate that files should not be directly referenced, as they are mutable and could result in breaking changes

## Context

Backstage integrators routinely consume the templates in the repository — see [current search results](https://github.com/search?l=&q=https%3A%2F%2Fgithub.com%2Fbackstage%2Fbackstage+template.yaml&type=code) for examples. These default templates will be updated with backwards-incompatible changes by adding this new action.

**Comment by joeporpeglia** [comment]
Template migration done in https://github.com/backstage/software-templates/pull/2
