### ISSUE TITLE
How do we identify github enterprise projects with github.com/project-slug

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#6287]
Hi,

How do we identify github enterprise projects with `github.com/project-slug`?

![image](https://user-images.githubusercontent.com/56138162/124019248-ae29cd00-d99d-11eb-8b9c-46d476a6558b.png)

Is `github.com/project-slug` in effect with `View source` button?

I tried to configure it, but it could not point to the source code.

My project is in Github Enterprise, and I configured in this way `ghe.mycompany.com/project-slug: <repo-name>/<project-name> ` or `github.com/project-slug: <repo-name>/<project-name> `, but they didn't work.

**Comment by kuangp** [comment]
`github.com/project-slug` is the correct annotation, for GHE, I believe you would have to configure `integrations.github` in your `app-config.yaml`: https://backstage.io/docs/integrations/github/locations

**Comment by chuliang014** [comment]
> `github.com/project-slug` is the correct annotation, for GHE, I believe you would have to configure `integrations.github` in your `app-config.yaml`: https://backstage.io/docs/integrations/github/locations

Yes, I've configured it like below, but the `View source` still not point to my GHE project.

![Xnip2021-06-30_12-46-51](https://user-images.githubusercontent.com/56138162/124022203-59885100-d9a1-11eb-8e24-d38ff3d5d966.jpg)

**Comment by kuangp** [comment]
hm, are you specifying `<github-org>/<repo-name>` for the value (eg. `backstage/backstage` for this repo)? You post says you tried `github.com/project-slug: <repo-name>/<project-name>` which looks like its different from the expected value according to https://backstage.io/docs/features/software-catalog/well-known-annotations#githubcomproject-slug

**Comment by chuliang014** [comment]
> hm, are you specifying `<github-org>/<repo-name>` for the value (eg. `backstage/backstage` for this repo)? You post says you tried `github.com/project-slug: <repo-name>/<project-name>` which looks like its different from the expected value according to https://backstage.io/docs/features/software-catalog/well-known-annotations#githubcomproject-slug

I just changed `github.com/project-slug: <repo-name>/<project-name>`  to `<github-org>/<repo-name>`, but also did not work...

**Comment by kuangp** [comment]
Is the "View Source" button currently linking to public github.com right now? ie. `https://github.com/<github-org>/<repo-name>/<path-to-catalog-file>` ?

**Comment by chuliang014** [comment]
> Is the "View Source" button currently linking to public github.com right now? ie. `https://github.com/<github-org>/<repo-name>/<path-to-catalog-file>` ?

It is linking to GHE now. like `https://ghe.<my-company>.io/<github-org>/<repo-name>/<path-to-catalog-file>`.
One thing I want to mention is that the repo of my Backstage and the repo of catalog file is from different.
Will this have an effect?

**Comment by kuangp** [comment]
Having different repos shouldn't have any effect, that's the intended setup where your entities in Backstage are usually backed by a catalog file living in their respective repos. 

It looks like it's working now for you? I'm assuming the entity page was updated after you made the `<github-org>/<repo-name>` change but there was a delay because of the catalog refresh interval where changes are picked up (by default every 100s I believe)

**Comment by chuliang014** [comment]
emm.  It is just linking to the path to catalog file, but i'd like to redirect to the repo of my Backstage, just like this demo https://demo.backstage.io/catalog/default/component/backstage.  I click the `View Source`, it will redirect to Backstage repo, not catalog file.

**Comment by kuangp** [comment]
Ah, I may of misunderstood here and I think I may have been mistaken about the use of the `github.com/project-slug` annotation. If you want to customize where the "View Source" button links to you can use the [`backstage.io/view-url`](https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageioview-url-backstageioedit-url) annotation.

By default, it does link to where ever your catalog file lives. I thought your catalog file represented a different project, not your backstage component itself

**Comment by chuliang014** [comment]
> may have been mistaken about the use of the

Yep. We have been integrating 

> Ah, I may of misunderstood here and I think I may have been mistaken about the use of the `github.com/project-slug` annotation. If you want to customize where the "View Source" button links to you can use the [`backstage.io/view-url`](https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageioview-url-backstageioedit-url) annotation.
> 
> By default, it does link to where ever your catalog file lives. I thought your catalog file represented a different project, not your backstage component itself

yep, do you have template for `backstage.io/view-url`? I configured it with `backstage.io/view-url: https://ghe.mycompany.io/<org-name>/<repo-name>`, but still not work

**Comment by adamdmharvey** [comment]
@chuliang014 Check out the documentation here if it helps:

https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageioview-url-backstageioedit-url

**Comment by chuliang014** [comment]
> @chuliang014 Check out the documentation here if it helps:
> 
> https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageioview-url-backstageioedit-url

For `View Source` button, should use `backstage.io/source-location:`. now it works.

**Comment by kuangp** [comment]
ah, sorry for the confusion, the `backstage.io/view-url` annotation corresponds to the view button under the Actions column in the catalog grid
<img width="108" alt="Screen Shot 2021-06-30 at 8 59 16 PM" src="https://user-images.githubusercontent.com/6998196/124049365-477cd180-d9e6-11eb-8c14-2d47084bee86.png">

hm, its a bit strange that this button is not consistent with the "View Source" button on the Entity page but I guess I can see the use-case where this is intended to link to a deployed app rather then the source code

**Comment by chuliang014** [comment]
> ah, sorry for the confusion, the `backstage.io/view-url` annotation corresponds to the view button under the Actions column in the catalog grid
> <img alt="Screen Shot 2021-06-30 at 8 59 16 PM" width="108" src="https://user-images.githubusercontent.com/6998196/124049365-477cd180-d9e6-11eb-8c14-2d47084bee86.png">
> 
> hm, its a bit strange that this button is not consistent with the "View Source" button on the Entity page but I guess I can see the use-case where this is intended to link to a deployed app rather then the source code

Yes, I think this might be added to docs for clarify. BTW, it is really thanks for your help.
