### ISSUE TITLE
[Techdocs] Tiny headers

### ISSUE THREAD

**Issue by estahn** [backstage/backstage#6289]
I've moved our first docs into Backstage, which was using Material for mkdocs. Unfortunately, the headers look all fairly tiny. Is this an issue with the config or is that just how the theme looks.

![image](https://user-images.githubusercontent.com/362174/124044301-792a8280-da50-11eb-9266-4a6cff3f9a91.png)

## Expected Behavior

The ratio between header and text should be "better", e.g. similar to Material for Mkdocs.

## Current Behavior

Tiny headers.

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by estahn** [comment]
Still relevant

**Comment by kuangp** [comment]
should this be reopened?

**Comment by kuangp** [comment]
still relevant

**Comment by estahn** [comment]
still relevant

**Comment by camilaibs** [comment]
Hi everyone, we will have a look at this sprint, so we hope to have some good news soon!
