### ISSUE TITLE
Techdocs: Can no longer specify docs_dir with local builder

### ISSUE THREAD

**Issue by tmalinakis-vng** [backstage/backstage#6308]
## Expected Behavior

Hello, we are still using the out of the box local building for Techdocs. Some of our projects need to define a custom `docs_dir` which is within the project directory (at the root of the project or subdirectory). This used to work and does not pose a security concern.

## Current Behavior

This is no longer allowed with the message `docs_dir configuration value in mkdocs can't be an absolute directory or start with ../ for security reasons.` Debugging into the issue, it seems that [isChildPath](https://github.com/backstage/backstage/blob/0ce80ab75ad6bbb0aa0a5923e4f373e6a2b348cf/packages/techdocs-common/src/stages/generate/helpers.ts#L181) no longer returns true, because the workspace is a temp directory. Resolving a local path such as `docs` contains quite a lot of `..`.

## Steps to Reproduce

1. Create a Backstage application with local Techdocs
2. Import a project where `mkdocs.yml` contains a valid `docs_dir` entry such as `docs`.

## Your Environment

- NodeJS Version (v12): 14
- Operating System and Version (e.g. Ubuntu 14.04):  Kubernetes - Node 14 Container (Debian 10)
- Browser Information: N/A

Thanks for your help!

**Comment by OrkoHunter** [comment]
Related https://github.com/backstage/backstage/security/advisories/GHSA-pgf8-28gg-vpr6

**Comment by kuangp** [comment]
Hi I am also running into this issue now and its a huge blocker for us since newly registered docs can no longer be built. Is there any known workaround or should we downgrade our version of `@backstage/plugin-techdocs-backend` ?

**Comment by ajohanssonwalder** [comment]
Similar but (perhaps) temporary workaround is to no longer specify the `docs_dir` attribute - obviously this may not work for all (depending on your specific setup).

For custom locations, we've been using the `backstage.io/techdocs-ref` annotation on components to declare where `mkdocs.yml` lives and then placing markdown in the default `docs` folder in the same space: 

eg. the following setup renders:
`my-component.yaml`
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/my-org/my-component/tree/master/custom/directory/for/mkdocs
    github.com/project-slug: my-org/my-component
  name: my-component
....
```
my-component doc structure:
```
my-component/custom/directory/for/mkdocs/
├── docs
│   └── index.md
└── mkdocs.yml
```


`mkdocs.yml`
```
site_name: 'my-component-docs'
nav:
  - Home: index.md

# disabled so backstage successfully renders
# docs_dir: './docs'

plugins:
  - techdocs-core
```

Note: Not sure if this helps as this isn't technically a local TechDocs setup? 😄

**Comment by onematchfox** [comment]
> Related [GHSA-pgf8-28gg-vpr6](https://github.com/backstage/backstage/security/advisories/GHSA-pgf8-28gg-vpr6)

Just FYI, I think this issue was introduced subsequent to the patch for this advisory (`0.6.5`). The issue seems to have been introduced in `0.6.6` in this commit https://github.com/backstage/backstage/commit/ab5cc376fac968c0643d1b624fb37d3117d399de due to the differences between the original implementation (`path.resolve().startsWith()`) and the new `isChildPath` which uses `path.relative`. `path.relative` is returning the path relative to the working directory (`e.g. `packages/backend`) rather than the temp directory.
