### ISSUE TITLE
Allow initial git branch to be named `main`

### ISSUE THREAD

**Issue by kjjuno** [backstage/backstage#6310]
In accordance with github and others switching from `master` to `main` I would like to be able to init new repositories from a template and have that show up in the main branch, rather than master.

## Possible Implementation

Allow a config parameter to specify the default branch name when initializing a repository

## Context

https://github.com/github/renaming

**Comment by OrkoHunter** [comment]
Yep! This is being worked upon for GitHub https://github.com/backstage/backstage/pull/6195
