### ISSUE TITLE
[RFC] Improve responsiveness

### ISSUE THREAD

**Issue by tudi2d** [backstage/backstage#6318]
## Need

Backstage is mainly designed for & used on desktop devices. Nevertheless there are use cases, where the screen dimensions differ from a classic desktop environment. Examples are split screens for working with several applications at the same time, smaller laptop/tablet screens & sometimes even mobile devices.

The goal should be to improve the UI & UX across different screen sizes & support responsiveness out of the box for further developments.

Potential for improvement are overflowing areas, accessibility, improvements in core components & the sidebar.

### Useable UI (Easy-wins)
- [x] [Improve Sidebar UX for smaller screens](https://github.com/backstage/backstage/issues/6239)
- [x] Wrap components when it is possible
  - [x] https://github.com/backstage/backstage/pull/6397/
  - [x] Generic table page

### Improved UI
- [x] https://github.com/backstage/backstage/pull/6497
  - [x] Page Header responsive
- [x] Catalog fully responsive
  - [x] https://github.com/backstage/backstage/pull/6635 
  - [x] https://github.com/backstage/backstage/pull/6397
- [x] https://github.com/backstage/backstage/pull/6611
  - [x] Keyboard accessibility 
  - [x] Screen Reader accessibility
  - [x] Dark Mode improvements
    - [x] https://github.com/backstage/backstage/pull/6761 
    - [x] https://github.com/backstage/backstage/issues/6326
- [ ] Performance (optional)
  - [ ] Audit & iterate

### Extended UI (Further ideas)
- [x] Refactor Sidebar
  - [x] #6779 
  - [x] #6905 

### Mobile Sidebar Design

| Main | Menu | Profile |
|---|---|---|
| ![Main page](https://user-images.githubusercontent.com/8904624/128710570-db9754bc-4072-4c0f-bc50-7cce6a973a65.png) | ![Menu](https://user-images.githubusercontent.com/8904624/128710580-fcb513cd-6fb5-490c-9c22-a42e10233c77.png) | ![Search2](https://user-images.githubusercontent.com/8904624/128710649-235e0073-42a1-4bdb-aee7-8c59c6d74556.png) |

## Risks

There is the risk of breaking current functionality & plugins with this. Therefore when changing things it should be thoughtfully validated what the effect of the changes are. Especially for the changes extending the current UI & touching the root application elements there should be a good test coverage validating the functionality.

Furthermore there is the risk that components or plugins, which will be added in the future, break the responsiveness of the application making this effort useless. To avoid that, it is important to first tackle the _Useable UI_ & _Improved UI_ steps & extending the documentation on how to design plugins.

----

### Catalog/API Explorer  Page

| Before | After |
|:------:|:-----:|
| <img src="https://user-images.githubusercontent.com/8904624/125321397-ec7ba080-e33c-11eb-8465-6449e49be865.gif" width="500" /> | <img src="https://user-images.githubusercontent.com/8904624/126137059-d8f020ec-a989-4232-bd64-02de562a04b5.gif" width="500" /> |

### Entity Page
| Before | After |
|:------:|:-----:|
| ![before](https://user-images.githubusercontent.com/8904624/126157080-0234f6ad-5f3f-4843-b8ce-d49c0f7394a5.gif)  | ![after](https://user-images.githubusercontent.com/8904624/126157206-581df8f2-b20a-4dd0-8b92-41aaadd7d8f6.gif) |

**Comment by TejasQ** [comment]
This is a lovely issue and I'm glad we're putting care into this! I'd suggest adding a piece on end-to-end/visual regression testing as well to ensure the UI and the responsiveness we work so hard to create _stays_ using something like Applitools or similar

**Comment by freben** [comment]
Strong vote here for `<meta name="viewport" content="width=device-width,initial-scale=0.4" />`!

For the edge case of some rare mobile device visit (and that device supports `initial-scale`), this in and of itself makes that experience almost perfectly usable.

**Comment by tudi2d** [comment]
@freben Thanks for your feedback! For me the focus would not be on mobile device support, but rather to make it useable, accessible & good looking across all screen sizes. Example: Opening Backstage on a 13' Laptop - when changing to split view all components should respond & wrap properly not forcing the user to zoom or anything and still be able to perform any action. Would agree that changing the viewport could be a quick fix, but would argue that there is potential for a better UX (personally judging from looking at Backstage with `inital-scale=0.4` on a iPhone X - picture bellow)

<img width="330" alt="Screenshot 2021-07-02 at 16 06 14" src="https://user-images.githubusercontent.com/8904624/124288594-a6128e80-db51-11eb-9da3-9fe1ea4c6689.png">

**Comment by tudi2d** [comment]
> [...] I'd suggest adding a piece on end-to-end/visual regression testing as well to ensure the UI and the responsiveness we work so hard to create _stays_ [...]

Good point - added E2E testing to the 2nd goal & would suggest for now to use Cypress, as it is the currently used E2E test tool & has support for testing different viewports. Happy to discuss this with you though! :)

**Comment by tudi2d** [comment]
Closing this as the PR for the mobile sidebar was merged & the goal of the RFC is reached - future responsiveness improvements are of course always welcomed - feel free to just create a new issue :)
