### ISSUE TITLE
Catalog Import Showing Wrong Entity Type

### ISSUE THREAD

**Issue by j021006** [backstage/backstage#6329]
After the latest release, When I import any entity type it always says a location entity was imported. For example i will import a template type using the catalog-import plugin and i get this:

![image](https://user-images.githubusercontent.com/86613021/124318321-7a3ddb80-db46-11eb-84d0-d8b841eca8b5.png)

I cant find the template type, only the location when searching or going to the /create page.

**Comment by benjdlambert** [comment]
@j021006 can we see the `template.yaml` that you're trying to register? It could be invalid.

**Comment by j021006** [comment]
Template file encoding was UTF-8 once changed to UTF-16 worked fine.
