### ISSUE TITLE
[Home] Create composable homepage plugin

### ISSUE THREAD

**Issue by rubenLindstrom** [backstage/backstage#6353]
Create plugin for composable homepage and include it at root, "/".

- [x] Create routable plugin
- [x] Add navigation link in sidebar to plugin root.
- [x] Update link to Catalog in sidebar navigation.
- [x] Create new homepage component in [App](https://github.com/backstage/backstage/tree/master/packages/app/src/components).
- [x] Replace "/" route with home plugin in [App.tsx](https://github.com/backstage/backstage/tree/master/packages/app/src/App.tsx).
- [x] Make homepage JSX composable through passing homepage components as children.

**Comment by Rugvip** [comment]
Done!
