### ISSUE TITLE
[Home] Documentation

### ISSUE THREAD

**Issue by rubenLindstrom** [backstage/backstage#6358]
Create new "Home" folder in [docs/features](https://github.com/backstage/backstage/tree/master/docs/features)

Getting Started guide:
- [ ] How to set up homepage in App

Concepts:
- [ ] What is a homepage components?

How-to-guides: 
- [ ] How to customize the homepage with components
- [ ] How to create a new homepage component

**Comment by OrkoHunter** [comment]
Definitely a need for a top level "Extending and customizing Backstage" section in docs. ref. https://github.com/backstage/backstage/pull/6313#issuecomment-872535965

**Comment by emmaindal** [comment]
Read initial docs for the homepage plugin here https://github.com/backstage/backstage/blob/master/plugins/home/README.md
