### ISSUE TITLE
TechDocs annotation should have a sensible default

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#6360]
## Feature Suggestion

Assuming a company is not using mono-repos, the docs are likely in the `docs` directory at the root of the repo that contains the component. Can we make this the default in order to make the `techdocs-ref` annotation optional?

## Possible Implementation

No idea 😄 

## Context

Adoption of TechDocs is more likely if the user has to do less work to configure it. Every little bit of friction counts.

**Comment by Fox32** [comment]
Probably something that should be easy to accomplish using a custom catalog processor. We are using them a lot to query external tools and add annotations automatically. Here you could check whether the repo contains an `mkdocs.yaml` at root and add the annotation automatically (right now the `techdocs-ref` requires an absolute path!). Backstage already has all APIs for that 🙂 

Make the annotation entirely optional is difficult, as it used to decide whether an entity has a documentation (not really evaluating the content in the recommended setup).

**Comment by dtuite** [comment]
> Probably something that should be easy to accomplish using a custom catalog processor

There are likely some custom processors that will be repeatedly created by different companies who use Backstage and might make more sense to be either included by default or picked from a marketplace. I guess I'm trying to understand if this is one of those cases.

> Make the annotation entirely optional is difficult

Assuming the repo has a `mkdocs.yaml` file and a `docs` directory in the root, and Backstage knows where the repo is (via the `github.com/project-slug` or similar annotation), could it attempt to parse the `docs` dir it and display an error if it turns out to not be correct `MkDocs` content?

Perhaps the complication arises when using a CI to generate docs with the `techdocs-cli`?

**Comment by Fox32** [comment]
> Make the annotation entirely optional is difficult

With that I only meant that the follow up processes in the techdocs backend and frontend need that annotation, so we can't get rid of it completely, but can add it automatically. So that the user doesn't need to know about it.

**Comment by dtuite** [comment]
Ahh.. I understand you now. I was thinking in the business logic layer. Yep, I agree.

**Comment by andrewthauer** [comment]
Adding to this discussion, we are currently in the process of taking the "remove the friction" a step further. We've build code the will auto create an mkdocs.yml file dynamically in CI which means a repo really only needs a `docs` directory and an index/readme file. At that point we can auto build/publish the docs to storage. Then we have a custom processor that checks the existence of the docs directory for the entity and enriched the entity with the techdocs annotation. The difference being there is actually no physical mkdocs.yml file that is persisted anywhere.

**Comment by pashcan** [comment]
@andrewthauer That sounds super useful! If you have something shareable :crossed_fingers: I am sure many would benefit from this.

**Comment by dhenneke** [comment]
You can also use `backstage.io/techdocs-ref: dir:.` to link to a `mkdocs.yml` that is stored relative to your `catalog-info.yaml` file. This could be a intermediate solution to simplify the configuration, even though you still need to add it to your entity.

**Comment by pashcan** [comment]
@dhenneke True dat. And I guess if they are adding mkdocs.yml via CI can also just add annotation at the same time. Also thanks to #6495\, you might even be able to drop `dir:` part.

**Comment by dhenneke** [comment]
> [...] thanks to #6495, you might even be able to drop `dir:` part.

Unfortunately, this specific feature was removed from the PR. I probably need to update the PR title to better describe the change that was merged.

**Comment by andrewthauer** [comment]
> @andrewthauer That sounds super useful! If you have something shareable :crossed_fingers: I am sure many would benefit from this functionality.

Definitely considering contributing bits of this. Much of this was hand rolled prior to the full techdocs solution, so we are in the process of migrating over to use more of the full techdocs solution. Once that's done, it should hopefully be a bit easier to contribute the mkdocs.yml not required feature and a couple of other things.

**Comment by Crevil** [comment]
Chiming in here. We have that exact processor implemented as @dtuite mentions.

If an `mkdocs.yml` file exists set the annotation. Would be great if it was standard someway.

**Comment by andrewthauer** [comment]
Makes sense. The reason I didn't offer to open source ours is that it looks for published site rather then the mkdocs.yml (since we generate that on the fly).

That said, I've been actually thinking there could be a generic `AppendAnnotationProcessor` that is configured with a predicate (eg URL read for existence) and annotation builder function. The predicate could be a URL read that when it evaluates to true it appends the desired annotation. This is essentially what our custom one does and exactly what the mkdocs one would need to do as well. The difference would be this processor could be registered in the backend multiple times for different annotations.

**Comment by Crevil** [comment]
Yeah that use case is kind of generic. The nature of our custom processors is often `if file exists - add annotation` or `if file exists - emit entity with its contents`. The latter is for things like API definitions like `swagger.yaml` files where we generate `API` entities.

Whether a generic processor would fit both of these, I'm unsure though.

**Comment by freben** [comment]
An out-of-the-box available processor that scans for an mkdocs file or properly detects an interesting docs dir sounds like it would be very useful!

@backstage/techdocs-core Could you chime in here? This sounds like a worthwhile contribution, whether by maintainers or by the community.

**Comment by andrewthauer** [comment]
One concern I have for this is rate limiting. Each individual processor that needs to check the existence of a file/dir will contribute to quickly add up and cause possible issues. We already have the the codeowners (which should probably be optimized as there are 3 possible locations). Internally we do a couple additional existence checks against the repo as well. I haven't really looked into this too much, but it might be nice to have something that can check for a series of files/dirs in one shot and then provide that info as context to various processors. The GH graphql API supports something like this, but it's not scm agnostic and probably not the easiest to extend into this concept.

**Comment by iamEAP** [comment]
^ I can see where Andrew's coming from re: needing to read multiple files.  ...We may even need to check multiple files in this one processor (see below).

In any event, seems like we can basically merge this and #2099.  It sounds like there are some edge cases to think through:

- The `mkdocs.yml` file is not adjacent to the `*-info.yaml` file
- TechDocs is configured with an external builder and the `mkdocs.yml` is generated on the fly (so it's not even in VCS)
- TechDocs is configured with an external builder and there _is_ an `mkdocs.yml` in VCS, but a build hasn't occurred for an entity's docs yet.
- `mkdocs.yaml` is used instead of `mkdocs.yml` (newly a thing as of a couple weeks ago!)
- ...Anything else?

Perhaps we could break it down like this...

- If builder is configured to be external, `GET /api/techdocs/static/docs/namespace/entity/kind/index.html`.  If it's a 200, then append the annotation ref.
- If builder is local, check for an adjacent `mkdocs.yml` OR `mkdocs.yaml` and if it's there, append the ref.

For other exotic configs (monorepos, different `mkdocs.yml` locations), manually writing the ref is the way to go?

**Comment by andrewthauer** [comment]
> If builder is configured to be external, GET /api/techdocs/static/docs/namespace/entity/kind/index.html. If it's a 200, then append the annotation ref.

This is essentially how we handle it now. We check if the docs are published rather then the existence of an `mkdocs.y*ml` file. This seems more reliable and also avoids rate limits imposed by SCM. It would be more suited for `external` techdocs published via CI rather then `local`, but perhaps it can also work for both?

**Comment by iamEAP** [comment]
> but perhaps it can also work for both?

I think it becomes a chicken-and-egg situation.  The index file won't appear until someone tries to load the page and the docs get built for the first time.  But no one knows to do that unless there's an annotation ref to indicate that they exist.  You could maybe wire up the processor to trigger an initial build?  But that might have similarly bad scalability consequences compared with the SCM rate limiting issue.

**Comment by garyniemen** [comment]
@dtuite Do you know if this issue progressed? Can the issue be closed or...?
