### ISSUE TITLE
Feedback when app-config.yaml is filtered at runtime

### ISSUE THREAD

**Issue by TejasQ** [backstage/backstage#6365]
## Feature Suggestion
Working on the frontend, I added a key to `app-config.yaml` that was being filtered out when using a `ConfigReader` to read it in my browser for apparently no reason. Having missing keys without any feedback, I asked for help and was told I needed to:

1. Add a type definition for this key to `packages/app/config.d.ts`.
2. Add `@visibility frontend` in a comment directly above it.

While this is covered in the docs, I feel the developer experience could be improved by `console.warn`ing or `console.info`ing in a browser's console when keys are being filtered out from a read `app-config.yaml` with a link to relevant documentation and suggestions to adjust visibility then and there.

## Possible Implementation
At the time of filtering out keys, add a `console.warn` statement similar to 

```
Key [key] is not marked as visible to the frontend, so it will be omitted from ConfigReader's output. 
Please add `@visibility frontend` to your app's config.d.ts to adjust it.

More info: https://backstage.io/docs/conf/defining#visibility
```

**Comment by OrkoHunter** [comment]
> At the time of filtering out keys

Since a looot of config keys will not be available on frontend, it might be too many console warnings for an average user of Backstage.

I was thinking that a console error or warning should be printed only when you run `config.get*` API in the frontend _and_ if the key is missing visibility frontend.

---

Quoting @freben 

> Could perhaps store all of the “potential” keys to read, even ones that were pruned - enough info for the frontend to learn that as you attempt to read a key, it failed because it has been pruned. Discern between “missing because it was never there” vs “missing because it’s been cut out”

**Comment by freben** [comment]
Yep that was my thought as well. Basically only make noise if there's an explicitly known misconfiguration / misbehaviour

**Comment by freben** [comment]
Pseudo-design-idea:

Maybe the config blob that's given to the frontend could contain an additional field:

```yaml
__prunedKeys: ['integrations.bitbucket.appPassword', ...]
```

or similar. Enough info for the `get` functions on the reader end to deduce that what's being read used to exist AND was specified, but was intentionally exluded.

**Comment by joaomilho** [comment]
Adding to @TejasQ , as a short term improvement, I feel we could go further and break the build, as console warns are not obviously noticeable. It is a better DX to get the error before the confusion ensues.

On a higher level note, 2 things:

1. I wonder if conflating backend and frontend config together is the source of the problem here. The design limitations here revolve around avoiding backend secrets to leak to the frontend and if these are more clearly separated we could avoid the issue altogether and relying on comments, warning or throwing, exposing __prunedKeys, etc...

2. webpack has its own ways of expanding env vars in the bundle and then eliminating dead code with terser. This breaks when all config is parsed from a single variable. As an example:

```js
const config = JSON.parse(process.env.APP_CONFIG);

if (process.env.A === "1") console.log("A is 1");
if (process.env.B === "1") console.log("B is 1");
if (config.a) console.log("config.a is 1");
if (config.b) console.log("config.b is 1");
```

with the following config in webpack:
```js
new webpack.DefinePlugin({
    "process.env.A": "1",
    "process.env.APP_CONFIG": JSON.stringify({ a: "1" }),
}),
```

Compiles to:

```js
(()=>{const o=JSON.parse({a:"1"});"1"===process.env.B&&console.log("B is 1"),o.a&&console.log("config.a is 1"),o.b&&console.log("config.b is 1")})();%
```

Note the conditional using `process.env.A` goes away while the one with `config.a` doesn't.

**Comment by Rugvip** [comment]
I think adding a warning/error when filtered config values are accessed in the frontend is a great idea, I might have a look at if I can get that in. Probably just do it for development mode though, as I wouldn't want to bloat production builds with all of that extra information. Pretty much all of the confusion that we've seen is during development anyway, as in "why doesn't this config value that I just added show up in the frontend?"

@joaomilho

> Adding to @TejasQ , as a short term improvement, I feel we could go further and break the build, as console warns are not obviously noticeable. It is a better DX to get the error before the confusion ensues.

The build doesn't know what config values are being accessed, just like we can't break the build if a certain global variable isn't accessed at runtime. It's actually one of the reasons the config schema exists, as it lets us break the build early when values are missing in config.

> 1. I wonder if conflating backend and frontend config together is the source of the problem here. The design limitations here revolve around avoiding backend secrets to leak to the frontend and if these are more clearly separated we could avoid the issue altogether and relying on comments, warning or throwing, exposing __prunedKeys, etc...

Yeah the mixing of frontend and backend config undeniably comes with its set of problems, just like mixing frontend and backend packages in the same repo. I do still think it's worth it though, as the problem space has quite a big overlap with the problem of managing config from a bunch of different plugins. I see config schema as helping both problems, with the only extra addition needed to handle the mix being the config visibility, which we also use to filter secrets. I'm also quite happy with the security aspect of the existing solution, as it takes a conscious decision to make something available in the frontend.

The main contender of the current solution in my mind is to completely split frontend and backend schema and config, essentially having both `frontend-config.yaml` and `backend-config.yaml`, as well as `frontend-config.d.ts` and `backend-config.d.ts`. That's the main thing I'm comparing to anyway, but please do add more ideas to the table if possible.

You don't need to use comments btw, you can use [plain old JSON Schema](https://github.com/backstage/backstage/blob/06205426d8b285709c068b1fad98e62cd2f172f2/packages/backend-common/config-schema.json) if you want, it's just not what most people prefer 😅

> 2. webpack has its own ways of expanding env vars in the bundle and then eliminating dead code with terser. This breaks when all config is parsed from a single variable.

A big benefit of the current config system is that it's possible to override values per deployment, allowing for example just the `app.baseUrl` to be tweaked for a preview build. That ofc is not possible if substitution happens at build time.
