### ISSUE TITLE
Publish step of scaffolder step in gitlab is returning 400 bad request

### ISSUE THREAD

**Issue by sjamidar** [backstage/backstage#6379]
Hi Team,

I am getting 400 bad request while running publish step in backstage for gitlab.
I have updated all the configs as according to Ticket id : https://github.com/backstage/backstage/issues/6181
Please help me out for integration with gitlab.

![image](https://user-images.githubusercontent.com/85929731/124756623-48fc4b80-df4a-11eb-8ff5-9aaa0d02266e.png)

**Comment by timbonicus** [comment]
Do you have a GitLab integration set up in your `app-config.yaml`? It should look something like:

```yaml
integrations:
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}
```

Does the GitLab token used here have the `write_repository` scope? Are there any errors in the `yarn dev` output from the backend? Is this gitlab.com or self-hosted GitLab?

**Comment by sjamidar** [comment]
Hi @timbonicus ,

app-config.yml is have same setup for gitlab in integrations.
Also not getting any error in yarn dev .
It is self hosted gitlab.
Also gitlab token have write repository access.

**Comment by mustafa89** [comment]
Did you figure this out by any chance? I'm getting the same thing

**Comment by klmmmv** [comment]
I am getting the same error. Any input on that matter?
Configuration on gitlab integration and the template look the same. Access token has all rights.
