### ISSUE TITLE
CPU Spikes with the Catalog because of Location -> Entity Relations

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#6383]
## Feature Suggestion
- When a Catalog has just 1 seed location, and multiple entities being emitted they all get queued for refresh at the SAME time.
- This causes spikes when the catalog refreshes and refreshes all the entities and re-writes them to the database.

## Possible Implementation
- Internal `etag`, so that we don't write unless things have changed?

- When processing a location emits entities, and that entity has been processed before, let's add a random number of seconds (between 0 and refresh interval in seconds) to try and spread out the CPU usage so we don't cause spikes of CPU and in tern cause scaling issues.

## Context
https://discord.com/channels/687207715902193673/687235481154617364/862333895160889354

![Screenshot 2021-07-07 at 16 41 39](https://user-images.githubusercontent.com/3645856/124780409-db98ec80-df42-11eb-906f-57e881e1f0bc.png)
![Screenshot 2021-07-07 at 16 41 27](https://user-images.githubusercontent.com/3645856/124780411-dcca1980-df42-11eb-8ef7-cc092fba9625.png)

**Comment by freben** [comment]
fixed by https://github.com/backstage/backstage/pull/6822
