### ISSUE TITLE
Notification and alerting API

### ISSUE THREAD

**Issue by sagacity** [backstage/backstage#639]
## Feature Suggestion

Backstage can be considered the "front door" for developers using our company's infrastructure. So, high-level information can be shown in Backstage before drilling down into downstream services. I believe the same concept should apply for notifications and alert triggered in downstream services. If I am the owner of a service I would like to receive these notifications and alerts in a uniform way, to further strengthen the concept of Backstage being the front door.

Just like Backstage offers an abstraction around the infrastructure (so it doesn't matter where certain data about my service comes from), the same goes for notifications. It doesn't matter which underlying system they originate from, I just know that the notifications have something to do with my service and they're all in a similar format.

## Possible Implementation

While it could be nice if Backstage handles all the aggregation, it could also maybe just offer a basic REST API that downstream services may send alerts to, which it then in turn can delegate to a dedicated notification service. A lot of services currently already offer a way to send notifications via HTTP so they'd be able to use this notification API, although I guess they all send notifications in their own format.

I guess it does not make too much sense to create an API for Backstage plugins to be able to trigger notifications since a plugin is only a client-side concept right now? 

## Context

As an example, if I am the creator of a new service I may have issues in my GCP infrastructure, my Kubernetes pod may have a misconfiguration and there could be some linting errors in my API. It would be great if I can just tell Backstage "Please use this Slack channel for all notifications and alerts for this service". Looking further, perhaps people can choose to subscribe to certain types of notifications of their (and other) services, as well.

A second reason is that currently a lot of internal tooling we build is reinventing the wheel around notifications (and other things such as user/group management) every time. If this could be centralized through a common API then our internal tools can be more focused on their actual purpose (e.g. scanning GCP logs, storing API specs, etc) instead of dealing with the non-core aspects of it all.

**Comment by freben** [comment]
This is a great idea!

In the internal Backstage, we have a very rudimentary and slightly underused notification function, with a typical bell in the corner. There have also been snackbar pop-ups for simple event messages. We've had plans in the back of our minds to make better use of these, and to build a nice general messaging/notifications API from the frontend side of things.

What you propose sounds like it goes a bit  farther and wants to address the "backend" side of things, e.g. the aggregation and persistence of various events or notifications that then drive the frontend.

This sounds like a very interesting thing to get going.

**Comment by Rugvip** [comment]
Yep! Def wouldn't want to build the backend part of that from scratch though, so would be interesting to see what's out there.

**Comment by mbruggmann** [comment]
Not sure if this is the same thing, but I'm interested in having a unified event stream of what changes that are going on in the infrastructure (PR merges, service deploys, alerts, config changes, etc). We could, as you say, have some type of REST API that can be used as a webhook for infra services or external systems, possibly with a separate type of plugin to translate from upstream-specific into the Backstage data model. 

If that was a thing, Backstage could visualize a filtered version of that in a feed of events related to systems I own. We could special-case warnings/alerts and prompt the user directly. And of course, the event stream could also be exposed to downstream systems eg for a Slack bot.

Not sure about the implementation. Maybe Pub/Sub for the underlying event stream? Although then we'll end up with something cloud-specific (AWS, GCP, ...). We'd also need to index it somewhere for the personalized feed and notification queries to be efficient.

**Comment by kissmikijr** [comment]
Super cool idea and I think it would be really useful, I'm happy to work on this in my free time, but not sure what is the next step or how do you wan to tackle this. Any suggestion?

**Comment by grumpyoldman-io** [comment]
Perhaps a good start can be to make the current notification implementation from @freben open source, see how it is structured, or perhaps some pointers towards the backstage internals where this might work best? If we can somehow share events with plugins (Ive just started diving in to Backstage) the community could take over or assist.

**Comment by benjdlambert** [comment]
Hey @kissmikijr - I'm thinking that this is probably not something that's the best fit for a community contribution just yet, as we haven't really thought about what it means and how to implement this either. The purpose of this ticket I guess was to gather some feedback and thoughts about how we could implement it. 

It's something we want, but haven't really had the time to look at just yet.

**Comment by kissmikijr** [comment]
@benjdlambert Ah, ok make sense, we just started to adopt backstage here at Prezi, and we are definietly intrested in this, so maybe we'll implement something on our own when we get there. Thanks! :)

**Comment by grumpyoldman-io** [comment]
@benjdlambert ideally there would be something like an internal pub/sub system which plugins can hook in to, so for instance I roll my own Slack plugin, and choose to send Slack messages based on the events coming by.

so plugin X fires event Y.
Backstage catches event Y and publishes this to all plugins
Plugin Z will listen to event Y and handle it.

**Comment by andrewthauer** [comment]
It almost sounds like a message bus/queue abstraction would be needed for this. It almost definitely will need to be backend driven.

I suspect from an event publisher perspective this would be as simple as having an interface like `eventApi.publish(message)`. Some new backend plug-in could then store a log/queue of the messages and/or forward them to a proper message broker for subscribers to use. Another abstraction could be created on the consumer side as well.

This seems straightforward as an abstraction, but factoring in reliable message delivery, schema management, typescript typing of messages, etc. it can start getting complex quickly to manage across a plug-in architecture imo.

Don't get me wrong, I think this is an a great and worthy feature, but lots of planning and design would be required to roll this out as a core feature that all plugins can hook into.

**Comment by freben** [comment]
Yep. This is the reason that it's been lingering for so long - it hasn't been prioritized yet and we feel that the complexity level and design required is pretty significant so we'd have to set aside a fair chunk of time for it. If it should also support plugging in different backends/brokers, we get in the position of needing to design some lowest-common-denominator but also sufficient-and-evolvable interface on top of them, which is a bit of an undertaking.

**Comment by freben** [comment]
Adding:

I suppose there are some small tentative steps that could be made instead of worrying about the full scale enterprise grade solution. As mentioned earlier, maybe it is fairly reasonable to design a fairly open ended frontend API, possibly based on Observable or callbacks, that can be subscribed to. And possibly having a basic subscriber that you can use if you want to, that gets all alerts and filters by a user-specified function, and shows a popup message at the top of the screen using the alert api.

There will still be some design and stuff to sort out for that, but that's one limited thing to look at.

Then we could talk about a common backend plugin API for client-to-backend subscriptions, if we want the option of making "general" backend plugins that are bridges to some form of backing store such as google pubsub or kafka. This API could be similar to what the scaffolder does perhaps, just a kinda standard pipe for getting an events fire-hose.

Then we could perhaps talk about a backend plugin that acts as a message broker and can receive messages and store them in the database, and emitting them to the above mentioned firehose ... but we are not yet sure whether that's useful or a mechanism that we want to build and maintain ourselves.

**Comment by grumpyoldman-io** [comment]
I'm wondering if the database is not a step too far, I think having a back-end message broker that just emits (also to the client) and handles event catching is enough. You could leverage the `visibility` property as with config schemas and output ephemeral events. If you wish to store events, or port them over to a third party solution, you can always create a simple plugin to do that.

Plugin A -> push event to Broker
Broker -> checks visibility of event -> emits to proper channels
Plugin B -> listens to all events and sends these to a third party solution

The Broker would have to be something isomorphic though, but I think the hardest part is landing on a way to send them over from backend to frontend. (sockets / server push events).

**Comment by freben** [comment]
@grumpyoldman-io The thing is, if there is no backing system behind it, message fanout and distributed message delivery come into play. What if you have a distributed deployment with multiple hosts, possibly on different continents? :) And what do "proper" channels mean - what's the distribution / subscription mechanism? Who is targeted by a given event? Etc.

It's just overall tricky.

But anyway, I digress. I agree, we probably don't want to write and maintain _anything_ more ambitious than "thin" backend adapter plugins that essentially translate from the client-to-server pipe protocol to an actual backing system such as rabbitmq, kafka etc. It would be a fun exercise, but not sure it's a great idea from a product / time-spent perspective :)

**Comment by sagacity** [comment]
Is there a 'knex'-style abstraction library for messaging for NodeJS? A wrapper for such a library could make it in-process for simple deployments, but make it robust for larger scale deployments.

**Comment by andrewthauer** [comment]
> Is there a 'knex'-style abstraction library for messaging for NodeJS? A wrapper for such a library could make it in-process for simple deployments, but make it robust for larger scale deployments.

I haven't come across anything that stands out in particular. However something like https://cloudevents.io/ has similar motivations, except it's not JS/Node specific.

**Comment by tragiclifestories** [comment]
I'm not sure how closely this is aligned to this issue, but it would be handy to have notifications go to other places too - eg slack, emails etc. That would further militate towards a backend-heavy solution.

Don't suppose this has moved up the roadmap in the last 6 months? 😅

**Comment by benjdlambert** [comment]
Unfortunately not, it's not something that's on our roadmap yet, but open to contributions :+1:

**Comment by kunickiaj** [comment]
Came across this thread while looking to see if anything had been done already. I'm even looking to build something basic like a backend plugin that can send emails or slack notifications invoked by other plugins.

Using the database for queuing isn't a bad solution imho as that's how the catalog processing loop works, though integration with event system would certainly be nice.

For non-critical, low volume notifications I might just have a hacky backend plugin that does a mail fire and forget.

**Comment by awanlin** [comment]
@kunickiaj did you see these two PRs?

- https://github.com/backstage/backstage/pull/21889
- https://github.com/janus-idp/backstage-plugins/pull/933

They are both working towards this 👍
