### ISSUE TITLE
Not able to publish component - Error: Failed to add branch protection to 'Repo-Name'

### ISSUE THREAD

**Issue by ravargs** [backstage/backstage#6394]
The workflow to publish the application from the create catalogue templates fails with the error _Error: Failed to add branch protection to 'Repo-Name', HttpError: Not Found_

## Expected Behavior
Backstage application should publish the template to github repo. (https://github.com/xyzco/backstage-test-app.git)

## Current Behavior
Publish step fails with the error _Error: Failed to add branch protection to 'Repo-Name', HttpError: Not Found_
I am trying to publish to code the github organization (**_xyzco_**) https://github.com/xyzco/backstage-test-app1.git but instead it is trying with a different org/url. https://github.com/<abc>/backstage-test-app.git
**_abc_** is the user created the github token.
## Steps to Reproduce

1. Step 1
Click on Create Component  and Select Any component.
Provide below details
name: 
description: 
owner: 
2. Step 2
Provide these details in the next page
Host: github.com
owner: ravargs
repository name: backstage-test-app
3. Step 3
In the Next step review details and submit
Name	backstage-test-doc
Description	backstage-test-app
Owner	ravargs
Repo Url	github.com?owner=ravargs&repo=backstage-test-app

## Context
Error log
```
2021-07-08T03:05:55.805Z info: Creating new remote {dir=/tmp/a5d7c67d-110b-4793-a0eb-4af952d0439e,remote=origin,url=https://github.com/xyzco/backstage-test-app.git} {"timestamp":"2021-07-08T03:05:55.803Z"}
2021-07-08T03:05:55.808Z info: Pushing directory to remote {dir=/tmp/a5d7c67d-110b-4793-a0eb-4af952d0439e,remote=origin} {"timestamp":"2021-07-08T03:05:55.806Z"}
2021-07-08T03:05:58.448Z Error: Failed to add branch protection to 'backstage-test-app1', HttpError: Not Found
    at Object.handler (/app/plugins/scaffolder-backend/dist/index.cjs.js:972:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async TaskWorker.runOneTask (/app/plugins/scaffolder-backend/dist/index.cjs.js:2710:11)
    at async /app/plugins/scaffolder-backend/dist/index.cjs.js:2612:9
```
## Your Environment

- NodeJS Version (v14.16.0):
- Operating System and Version: Ubuntu 20.04
- Browser Information: Firefox
- Release version : release-2021-06-28

**Comment by timbonicus** [comment]
This should be addressed by #6331 set to be released today!

**Comment by freben** [comment]
It actually went out just now!

**Comment by benjdlambert** [comment]
Can we close this now @ravargs?

**Comment by benjdlambert** [comment]
Going to close, feel free to re-open if there's something we've missed!

**Comment by ravargs** [comment]
@benjaminr - I would like to reopen the issue. 
Even though the branch protection is resolved the backstage is trying to publish the repo to incorrect location.

If I provide '**backstage-test-app3**' as the repo name to publish, backstage is trying to publish to https://github.com/user1/backstage-test-app3. **user1** is the user for the personal access token.

If I provide https://github.com/myorg/backstage-test-app3 as the git repo, backstage is trying to publish to https://github.com/user1/https-github.com-myorg-backstage-test-app3

```
Review and create
Component Id	backstage-test-app3
Java Package Name	backstage
Description	testing
Owner	ravargs
Repo Url	github.com?owner=ravargs&repo=https%3A%2F%2Fgithub.com%2Fmyorg%2Fbackstage-test-app3

2021-07-13T06:58:17.098Z info: Creating new remote {dir=/tmp/188a62d4-151a-4699-8e26-73eafbf8b165,remote=origin,url=https://github.com/user1/https-github.com-myorg-backstage-test-app3.git} {"timestamp":"2021-07-13T06:58:17.097Z"}
2021-07-13T06:58:17.101Z info: Pushing directory to remote {dir=/tmp/188a62d4-151a-4699-8e26-73eafbf8b165,remote=origin} {"timestamp":"2021-07-13T06:58:17.101Z"}
2021-07-13T06:58:19.981Z warn: Skipping: default branch protection on 'https-github.com-myorg-backstage-test-app3', Not Found {"timestamp":"2021-07-13T06:58:19.980Z"}
2021-07-13T06:58:19.981Z Finished step Publish

2021-07-13T06:58:19.984Z Beginning step Register
2021-07-13T06:58:19.992Z info: Registering https://github.com/user1/https-github.com-myorg-backstage-test-app3/tree/master/catalog-info.yaml in the catalog {"timestamp":"2021-07-13T06:58:19.991Z"}
2021-07-13T06:58:20.027Z Finished step Register
```

**Comment by benjdlambert** [comment]
@ravargs so just to confirm, you have something that looks like this: 
![Screenshot 2021-07-13 at 10 19 53](https://user-images.githubusercontent.com/3645856/125417394-56a0dd14-2ea4-4c5b-8714-ddd3bad0e04c.png)

In the owner field of the `choose your location` you have only placed in the name? not a full URL?

**Comment by ravargs** [comment]
> @ravargs so just to confirm, you have something that looks like this:
> ![Screenshot 2021-07-13 at 10 19 53](https://user-images.githubusercontent.com/3645856/125417394-56a0dd14-2ea4-4c5b-8714-ddd3bad0e04c.png)
> 
> In the owner field of the `choose your location` you have only placed in the name? not a full URL?

In the owner field I was providing username instead of organization name.  If I provide organization name it works.
Thanks.

**Comment by benjdlambert** [comment]
yeah the owner field is either the name of the organisation or name of the user.

**Comment by ltdonner** [comment]
I also ran into this issue when trying to use the name of a user instead of an org in the owner field. I was told this was to prevent another user (the owner of the PAT) from accessing your personal repos. So even if you use some kind of bot account you can't create personal repos for anything other than the bot account if I'm understanding correctly. (For orgs as the owner it works fine)

Can you confirm?

**Comment by benjdlambert** [comment]
We recommend that you use Github Apps for authentication in production not PAT, but you should be able to enter a user or an organisation, not the full url, only the name in the `RepoUrlPicker` as shown above and it create repositories there. Don't think theres any special logic being it, it just needs to be the owner of the PAT IIRC.

**Comment by ltdonner** [comment]
This might be a separate discussion to have elsewhere but should a user be able to create a personal repo when using Github Apps? We've been unsuccessful there too. 
InputError: No token available for host: github.company.com, with owner user1, and repo test-personal-repo-1

**Comment by ltdonner** [comment]
Oh sorry nevermind - looks like this is in the works https://github.com/backstage/backstage/issues/5214
