### ISSUE TITLE
Catalog : Extra attributes/context for entity relationships

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#6414]
Allow extra context to be captured in catalog-info.yaml for dependency relationships.

## Feature Suggestion

Want to run through the idea with the community if it is a common need to enhance the consumes/provides relationship with extra attributes. few usecases :

1. Capacity modeling: one of our team is considering to build capacity modeling plugin based on catalog entity relationships. They proposed to have a "weight" attribute of type float for `consumes` relationship, so that it provides rough idea how each call to the service translate to # of downstream dependency invocations. This can be done for new entities in design phase to workout capacity modeling/impact of a change on throughput/capacity planning.
2. Specifies a particular version being consumed. 
3. Consumer may define higher level throughput/load requirements against a provider, so that provider may get a view on cummulative traffic requirements (at least the order-of-magnitude level).  

Drawback : 
Backstage catalog currently provides component level view and relationships. This may become too granular information and get into transaction level view ?

I am not 100% sure if all these are valid usecases, keen to get community feedback

## Possible Implementation

Provide schema extention for adding more context to relationships.

**Comment by sagacity** [comment]
Just my two cents, but in our organisation we would probably not want to model this in the service catalog, but rather look at actual metrics to see how the load on a certain producer is distributed among consumers. The reasoning behind is that these patterns may change over time, but they can also be highly dependent on the time-of-day, the day-of-week, etc. Capturing all of this with a `weight` attribute would not be enough.

**Comment by andrewthauer** [comment]
Another possible usage of this is just giving more context to the purpose of the relation and/or if the relation was auto created using some sort of automated enrichment process.

#1 and #3 sound a little bit in the real of SLO, service level objectives. I can see this being useful to define for a given component as a target value and then possibly comparing it to some sort of APM runtime data. However, it seems the tracking of this might be easier to accomplish through a purpose built solution like an APM?

**Comment by kiranpatel11** [comment]
Thanks for the comments, yes, I have the similar dilemma on the catacity modeling usecase. 

However, another usecase that came to my mind that can benefit from this is referning consumer-driven contracts (like [Pact file](https://docs.pact.io/getting_started/terminology/#pact-file)) on a  `consumes` relationship.

**Comment by andrewthauer** [comment]
Pact / consumer driven contracts is indeed another interesting use case here. If there was say a Pact plugin, it would likely need to operate on the API relations. Without thinking this through completely, I think it might be possible to just do an annotation lookup on the components on each end to resolve the actual contract. Is there context that needs to be in the catalog for this or can this just be a runtime lookup-query? Some of these use cases can likely be solved at runtime and others not as easily.

**Comment by kiranpatel11** [comment]
> Pact / consumer driven contracts is indeed another interesting use case here. If there was say a Pact plugin, it would likely need to operate on the API relations. Without thinking this through completely, I think it might be possible to just do an annotation lookup on the components on each end to resolve the actual contract.
> 
> Is there context that needs to be in the catalog for this or can this just be a runtime lookup-query? Some of these use cases can likely be solved at runtime and others not as easily.

You are right - Pact plugin can lookup PactBroker based on consumer-provider name pair and identify the contract if defined without having any extra info in the catalog (even  no extra annotation). However, for the sack of efficiency, the lookup can be optional and only done if the link to contract/some indication provided by the consumer, as Pact is not used that commonly across services. (though I personally recommend to use is when possible).

Also there are other ways than PACT consumer-driven contracts are implemented, so general purpose reference link to contract may be convenient.
