### ISSUE TITLE
Unable to add packages or plugins | expected workspace package to exist for X

### ISSUE THREAD

**Issue by TejasQ** [backstage/backstage#6416]
## Current Behavior
![image](https://user-images.githubusercontent.com/9947422/125051746-904a1f80-e0a3-11eb-81c6-c857c6156edc.png)

I try to `yarn add @backstage/plugin-catalog-backend-module-ldap` and it errors because apparently I need `css-loader` installed in my workspace. 🤔 

## Expected Behavior
The plugin _just installs_ without error.

## Steps to Reproduce
Create a new backstage app and try to `yarn add @backstage/plugin-catalog-backend-module-ldap` in `packages/backend`.

## Context
I'm trying to import users and groups from an LDAP-compatible service. I tried step 1 of [the official documentation](https://backstage.io/docs/integrations/ldap/org#docsNav) and failed.

## Your Environment

- NodeJS Version (v12): 14.16.1
- Operating System and Version (e.g. Ubuntu 14.04): macOS Big Sur
- Browser Information: N/A

**Comment by benjdlambert** [comment]
This is actually something that effects all installs of things in the workspace. Been unable to work out what the issue is though. @OrkoHunter I think had a workaround, but you can add the package explicitly in the `package.json` manually and run `yarn install` for now

**Comment by OrkoHunter** [comment]
Yeah, this is so annoying! Affecting both the mono-repo and generated Backstage apps as well.

**Comment by benjdlambert** [comment]
OK - So I did some `git bisect` magic between a working revision and `master` using a `git bisect run` to run a simple `yarn add` in `catalog`. Turns out it's this commit: 613e46d23488c19b9b822cf3724aee2b880c7d24 or #6290 which makes sense as we've shipped this to users too. 

Need to write a resolution override to test but first 🥘

**Comment by benjdlambert** [comment]
So I'm not sure where the `css-loader` comes into this, so there could be an extra dependency that got upgraded and broke this too, but I remember it being related to `jsonfile` too which this dependency seems to change. So let's see if this PR can help.

**Comment by benjdlambert** [comment]
Gonna keep this open until we do a release and confirm it fixed the issue. Think it's fixed on master now at least.

**Comment by benjdlambert** [comment]
Could be related breaking change for `create-app` installs also #6253

**Comment by benjdlambert** [comment]
Maybe we should consider updating `yarn` too if this is going to happen for any new major version change of a library too. Can't keep rolling back stuff, especially when there might be security fixes in dependencies.

**Comment by benjdlambert** [comment]
Just following up with this, looks like upgrading to latest 1.x release of yarn doesn't help, but updating to `berry (2.x)` seems to fix the issue too and I can install as expected. Maybe we can fix this short term for now, but look at moving to 2.x otherwise I think this is going to keep cropping up and causing issues blocking us from upgrading versions.

@Rugvip I know you had some thoughts on berry or had tried it, what were your findings?

**Comment by jrusso1020** [comment]
one thing to note on berry @benjdlambert is that it doesn't work with dependabot yet sadly, so you will lost dependabot if you upgrade yarn to 2.X. https://github.com/dependabot/dependabot-core/issues/1297

Dependabot will still open PR's for version updates though it just doesn't update dependencies correctly, so my workaround in another project was to let it open up PR's and then I would manually update them myself and merge. Although this may be more difficult for a project of this size

**Comment by benjdlambert** [comment]
I'm gonna go ahead and close this for now as I've not seen this come up since we rolled back the `fs-extra` changes. Although we should look moving to `berry` once there's an upgrade path that doesn't see us lose functionality.

**Comment by Vernon-van-der-Merwe** [comment]
Hello Guys!

Seems like this issue might still be happening.
im using yarn@1.22.17.

And this is my err after running the `yarn` command

```yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
error An unexpected error occurred: "expected workspace package to exist for \"@vercel/style-guide\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/vernon/Desktop/my-turborepo/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.```

**Comment by freben** [comment]
We ourselves are using 3.2.3 in the main repo. Any chance of upgrading?

https://github.com/backstage/backstage/tree/master/.yarn/releases
