### ISSUE TITLE
[RFC] Minimize missing type exports by enabling `ae-forgotten-export` in api-exporter

### ISSUE THREAD

**Issue by goober** [backstage/backstage#6422]
I have several times missed to validate that all necessary types are exported outside of my module, which leads to that an implementer cannot use the functionality as expected.

By enabling the `ae-forgotten-export` check in the API Extractor you get warnings at build time that you have forgotten to export the required types from your module.

I would like to discuss this improvement before I create an initial pull request. Pros and cons, should the warning be printed to the console or should it be included in the api-report.md file?

See https://api-extractor.com/pages/messages/ae-forgotten-export/ for details.

_Originally posted by @goober in https://github.com/backstage/backstage/issues/6403#issuecomment-876763494_

**Comment by benjdlambert** [comment]
@Rugvip thoughts on this? Sounds pretty reasonable?

**Comment by Rugvip** [comment]
Yep, totally, only reason warnings weren't enabled already was because absolute file paths where being included, which breaks CI. It required yet another ugly workaround to get around that, but should be fixed by #6472
