### ISSUE TITLE
Backstage doesn't load in Safari (when using @backstage/integration-react)

### ISSUE THREAD

**Issue by egnwd** [backstage/backstage#6426]
## Expected Behavior

I should be able to load a page in Safari.

## Current Behavior

I get a white screen and a console log saying: 

```
SyntaxError: Invalid regular expression: invalid group specifier name
```

## Possible Solution

Possibly parsing git urls some other way? or somehow pin the normalize-url version, and live with the security vulnerability (see context below). neither option seem great.

## Steps to Reproduce

1. Use `@backstage/integration-react` in app
2. Boot the app
3. Visit any page in Safari
4. 💥 

## Context

There is a fair bit of context, it seems:
 - Safari doesn't support Lookbehinds in regex in Javascript
 - the [bug](https://github.com/sindresorhus/normalize-url/issues/105) is in [this package](https://github.com/sindresorhus/normalize-url) and [they claim it shouldn't be used in browsers](https://github.com/sindresorhus/normalize-url/commit/76172da85d377d5221413117e5398d3af37db60f#r37078743), stating if you need it to work in browsers then you should use the previous version (v4.5.0)
 - This package gets used because: [@backstage/integration-react](https://github.com/backstage/backstage/blob/master/packages/integration-react/package.json#L26) > [@backstage/integration](https://github.com/backstage/backstage/blob/master/packages/integration/package.json#L34) > [git-url-parse](https://github.com/IonicaBizau/git-url-parse/blob/master/package.json#L32) > [git-up](https://github.com/IonicaBizau/git-up/blob/b37e5d40a65155d45483535e8532a07183f5dabe/package.json#L31) > [parse-url](https://github.com/IonicaBizau/parse-url/blob/master/package.json#L35) > [normalize-url](https://github.com/sindresorhus/normalize-url)@^6.0.1
 - So even though the version of git-url-parse is pointing at the right one I think yarn is picking up the latest normalize-url?
    At leat that is what `yarn why normalize-url` suggests
    ```
     Found "parse-url#normalize-url@6.0.1"
     info This module exists because "_project_#backend#@backstage#backend-common#git-url-parse#git-up#parse-url" depends on it.
    ```
 - However in newer versions, git-up uses a later version because of a [security vulnerability](https://github.com/IonicaBizau/git-up/issues/27), [knowing it will break Safari](https://github.com/IonicaBizau/git-up/issues/27#issuecomment-876178124)
 - Someone more well versed in yarn versioning might be able to see through this sea of versions better than I.

## Your Environment

- NodeJS Version: v14.15.1
- Operating System and Version (e.g. Ubuntu 14.04): macOS Big Sur 11.2
- Browser Information: Version 14.0.3 (16610.4.3.1.4)

**Comment by timbonicus** [comment]
Thanks for reporting! This may be the same as #6039?

**Comment by egnwd** [comment]
@timbonicus yes, I missed it, sorry about that, I'll close as a duplicate
