### ISSUE TITLE
Master Windows builds failing due to railsNewRunner

### ISSUE THREAD

**Issue by timbonicus** [backstage/backstage#6427]
The [Master Windows Builds](https://github.com/backstage/backstage/actions/workflows/master-win.yml) are failing due to path separator issues on Windows. For example:

```
Rails Templater › when rails is available › update the template path to correct location

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    - Expected
    + Received

    @@ -1,11 +1,11 @@
      Object {
    -   "args": ArrayContaining [
    +   "args": Array [
          "new",
    -     "tempdir\\intermediate\\rails-project",
    +     "tempdir\\intermediate/rails-project",
          "--template",
    -     "tempdir\\something.rb",
    +     "./something.rb",
        ],
        "command": "rails",
```

I took a quick look at this, but wasn't able to reason about some of the non-trivial codepaths. There are some places that should use `path.join`, `path.normalize` or `path.sep`. Reproducible in Windows via:

```
cd plugins\scaffolder-backend-module-rails
yarn test railsNewRunner
```

@angeliski any chance you can have a look?

**Comment by OrkoHunter** [comment]
Adding to Tim's excellent suggestions, also replace `/tmp` with a variable which is equal to `os.tmpdir()`. Usually the problem lies at the use of `/tmp` since this is resolved to `C:\\tmp` on Windows CI runner, and ofcourse expecting `/` as the path separator.

We can also do (as done in a lot of places already)
```ts
    const tmpDir = os.platform() === 'win32' ? 'C:\\tmp' : '/tmp';
```
