### ISSUE TITLE
CookieCutter is not a constructor

### ISSUE THREAD

**Issue by yonimoses** [backstage/backstage#6431]
Updated to latest version ( versions:bump)
and got a
` _backstage_plugin_scaffolder_backend__WEBPACK_IMPORTED_MODULE_2__.CookieCutter is not a constructor
`

tried deleting node_modules from the root and reimport everything, still getting it.

any ideas?

**Comment by yonimoses** [comment]
downgraded to 

`  "devDependencies": {
    "@backstage/cli": "^0.7.1",
    "@spotify/prettier-config": "^7.0.0",
    "concurrently": "^6.0.0",
    "lerna": "^4.0.0",
    "prettier": "^1.19.1"
  },`

and 

`  "dependencies": {
    "app": "0.0.0",
    "@backstage/backend-common": "^0.8.3",
    "@backstage/catalog-model": "^0.8.3",
    "@backstage/catalog-client": "^0.3.13",
    "@backstage/config": "^0.1.5",
    "@backstage/plugin-app-backend": "^0.3.14",
    "@backstage/plugin-auth-backend": "^0.3.13",
    "@backstage/plugin-catalog-backend": "^0.10.3",
    "@backstage/plugin-proxy-backend": "^0.2.10",
    "@backstage/plugin-scaffolder-backend": "^0.12.2",
    "@backstage/plugin-search-backend": "^0.2.1",
    "@backstage/plugin-search-backend-node": "^0.2.1",
    "@backstage/plugin-techdocs-backend": "^0.8.3",
    "@gitbeaker/node": "^30.2.0",
    "@octokit/rest": "^18.5.3",
    "dockerode": "^3.2.1",
    "express": "^4.17.1",
    "express-promise-router": "^4.1.0",
    "knex": "^0.21.6",
    "sqlite3": "^5.0.0",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "@backstage/cli": "^0.7.1",
    "@types/dockerode": "^3.2.1",
    "@types/express": "^4.17.6",
    "@types/express-serve-static-core": "^4.17.5"
  },` 
on the backend 


` "dependencies": {
    "@backstage/catalog-model": "^0.8.3",
    "@backstage/cli": "^0.7.1",
    "@backstage/core": "^0.7.13",
    "@backstage/integration-react": "^0.1.3",
    "@backstage/plugin-api-docs": "^0.6.0",
    "@backstage/plugin-catalog": "^0.6.3",
    "@backstage/plugin-catalog-import": "^0.5.10",
    "@backstage/plugin-catalog-react": "^0.2.3",
    "@backstage/plugin-explore": "^0.3.6",
    "@backstage/plugin-github-actions": "^0.4.9",
    "@backstage/plugin-org": "^0.3.14",
    "@backstage/plugin-scaffolder": "^0.9.8",
    "@backstage/plugin-search": "^0.4.0",
    "@backstage/plugin-tech-radar": "^0.4.0",
    "@backstage/plugin-techdocs": "^0.9.6",
    "@backstage/plugin-user-settings": "^0.2.11",
    "@backstage/test-utils": "^0.1.13",
    "@backstage/theme": "^0.2.8",
    "@internal/plugin-devops-tools-usage": "^0.1.0",
    "@internal/plugin-infra-gate": "^0.1.0",
    "@internal/plugin-service-domain-instances": "^0.1.0",
    "@internal/plugin-service-domain-metadata": "^0.1.0",
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "history": "^5.0.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router": "6.0.0-beta.0",
    "react-router-dom": "6.0.0-beta.0",
    "react-use": "^15.3.3"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.10.1",
    "@testing-library/react": "^10.4.1",
    "@testing-library/user-event": "^12.0.7",
    "@types/jest": "^26.0.7",
    "@types/node": "^14.14.32",
    "@types/react-dom": "^16.9.8",
    "cross-env": "^7.0.0",
    "cypress": "^7.3.0",
    "eslint-plugin-cypress": "^2.10.3",
    "start-server-and-test": "^1.10.11"
  },`
on the app. 

and it's working again.

**Comment by freben** [comment]
I think that's part of the old fixed pipeline stuff that has been migrated to the newer flexible templates. Check the changeset and the linked migration guide to see if it applies to you.

https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/CHANGELOG.md

**Comment by benjdlambert** [comment]
Cookiecutter is no longer exported from the `scaffolder-backend`, only in action format.

https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/CHANGELOG.md#minor-changes is probably the exact migration you're looking for.

**Comment by ChristianAvila** [comment]
I got the same issue, I use this [code](https://github.com/backstage/backstage/blob/b9cba53a05c85d442e6a6961b7ca1a857e8577d3/packages/create-app/templates/default-app/packages/backend/src/plugins/scaffolder.ts) as a base to update my app.

**Comment by benjdlambert** [comment]
@ChristianAvila have you used `yarn backstage-cli versions:bump`?

**Comment by ChristianAvila** [comment]
Yes, I executed `yarn backstage-cli versions:bump`. and it shows me a bunch of errors for `scaffolder` plugging. 

```sh
yarn run v1.22.4
$ tsc
packages/backend/src/plugins/scaffolder.ts:7:3 - error TS2305: Module '"@backstage/plugin-scaffolder-backend"' has no exported member 'CookieCutter'.

7   CookieCutter,
    ~~~~~~~~~~~~

packages/backend/src/plugins/scaffolder.ts:8:3 - error TS2305: Module '"@backstage/plugin-scaffolder-backend"' has no exported member 'CreateReactAppTemplater'.

8   CreateReactAppTemplater,
    ~~~~~~~~~~~~~~~~~~~~~~~

packages/backend/src/plugins/scaffolder.ts:10:3 - error TS2305: Module '"@backstage/plugin-scaffolder-backend"' has no exported member 'Preparers'.

10   Preparers,
     ~~~~~~~~~

packages/backend/src/plugins/scaffolder.ts:11:3 - error TS2305: Module '"@backstage/plugin-scaffolder-backend"' has no exported member 'Publishers'.

11   Publishers,
     ~~~~~~~~~~

packages/backend/src/plugins/scaffolder.ts:12:3 - error TS2305: Module '"@backstage/plugin-scaffolder-backend"' has no exported member 'Templaters'.

12   Templaters,
     ~~~~~~~~~~

packages/backend/src/plugins/scaffolder.ts:41:5 - error TS2345: Argument of type '{ preparers: any; templaters: any; publishers: any; logger: winston.Logger; config: Config; database: PluginDatabaseManager; catalogClient: CatalogClient; reader: UrlReader; }' is not assignable to parameter of type 'RouterOptions'.
  Object literal may only specify known properties, and 'preparers' does not exist in type 'RouterOptions'.

41     preparers,
       ~~~~~~~~~


Found 6 errors.
```

Then I applied the changes in the code and the tsc command worked like a charm

**Comment by benjdlambert** [comment]
Perfect! So we can close?
