### ISSUE TITLE
Change log breaking change suggestion for scaffolder wrong

### ISSUE THREAD

**Issue by neilbeukes** [backstage/backstage#6448]
## Expected Behavior

There is a correct guide on how to migrate/change your `scaffolder.ts` file here : https://github.com/backstage/backstage/blob/master/packages/catalog-model/CHANGELOG.md#minor-changes

## Current Behavior

Currently this change log here is suggesting changes that produce errors: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/CHANGELOG.md#minor-changes

## Possible Solution

They are suggesting different changes to the same file, One faulty and one correct. Create PR to update markdown and change log suggestion

## Steps to Reproduce

Go to links

**Comment by neilbeukes** [comment]
I can create a PR if this Issue is not wrongfully opened.

**Comment by OrkoHunter** [comment]
> They are suggesting different changes to the same file,

Can you highlight the difference? In any case, you are welcome to open a PR!

**Comment by kyle-thedelta** [comment]
Just ran into this issue as well, found this github issue by chance.  
Lets please add this to docs on backstage
