### ISSUE TITLE
Support additional keys in oauth state parameter?

### ISSUE THREAD

**Issue by iain-b** [backstage/backstage#6449]
We've found that we need to pass information in the state parameter in our github oauth flow. Ideally there'd be a way of adding an additional value(s) into the encoded state e.g. nonce=adsf&env=development&additionalState=ourstate.

We recognise this probably means we need to implement a custom provider but we'd like to be able to leverage the good work the core team & community has done in providing the auth-backend (the github provider in particular).

I am of course happy to do the work here if any of these implementations (or another) is agreeable.

## Feature Suggestion

As above either we could pass through an optional function to generate additional state or the auth-backend could expose more to cut down the boilerplate for users who wish to modify an existing provider (i.e. create a custom provider based on an existing one).

## Possible Implementation

I _think_ any of these three solutions would give us the flexibility we need. Though I understand these may not be desirable. From what I gather the interface for custom providers was deliberately kept small.

1. The OauthAdapter takes a function which can generate additional state. (This does _not_ override the env or nonce)
      1.  encodeState would accept additional key(s) rather than just env & nonce keys
2. The provider classes are exported (so we can extend the github provider and use this in a custom provider)
      1.  encodeState would accept additional key(s) rather than just env & nonce keys
      2. (I imagine this is probably too much but it's an option)
3. Export members of `lib/passport` to better support users who need to implement a custom provider. This way we can just lift the github provider into our backend and make our changes without having to duplicate much else.

## Context

In our case we've multiple backstage installations and we want to be able to use the same Github App for each. This means we need to use the same redirect url for each so we pass along information in the state parameter to determine the particular backstage instance to redirect back to. Note also that we could potentially have more instances than the max allowed redirect urls (10).

**Comment by Rugvip** [comment]
With the work going on in #6245 we're moving to making the auth providers way more configurable, and this could potentially be something that we work in in a similar way. Also open to cleaning up and exporting some of the internal helpers to make it easier to implement custom providers as well.

If I understand correctly the end result you want here is to be able to set the app origin of the `postMessage` coming from the login popup to the URL of the target instance right? We have a similar use-case internally for preview deployments, where we pass a numerical ID from the frontend and through OAuth state, to eventually have the result be posted to the correct origin.

It feels like there's more to your use-case than just passing through state though. You wouldn't want someone visiting a different instance to have their credentials handed over to that instance right? How do you do the mapping in the first place, as in if there's some piece of information you want to store in the state, where does that come from? Is it possible for you to have a user -> instance mapping that happens after auth, possibly removing the need for using OAuth state altogether?

**Comment by iain-b** [comment]
> If I understand correctly the end result you want here is to be able to set the app origin of the postMessage coming from the login popup to the URL of the target instance right? 

Yes, ultimately. What we've done is create a simple lambda application which accepts the github callback and redirects to the `handler/frame` endpoint of the instance which initiated the request. It knows this by inspecting the state. The state we pass through contains a short lived, signed JWT token which contains the public url of the handler frame endpoint. This is generated via a backend plugin in the backend of the particular instance. We do verify the domain is one we know about and if the user did happen to be redirected to another instance the handler frame endpoint would fail (AFAIK) as the nonce cookie wouldn't be set on the request as the domain is different (this is done for us by the auth-backend plugin; thanks).

> Is it possible for you to have a user -> instance mapping that happens after auth

We could I suppose put this logic in our lambda handler but the issue I see is where the same user is present across multiple backstage instances. i.e. if I have two separate backstage installations on say prod1.roadie.io and prod1-preview.roadie.io I'm not sure how I would know which to redirect back to based only on the user. This is a real use case for us as we often create prod-like test environments for testing. 
I hope I've understood your question/suggestion correctly.

> the work going on in #6245 

I hadn't seen this (😔), thanks.

**Comment by Rugvip** [comment]
@iain-b As part of supporting #6648 we'll likely be passing the app origin to the auth backend, and adding it to the OAuth state. Would that be enough to support your use-case?

So frontend includes `origin=https://prod1.roadie.io` in the `/start` request, and the start handler then encodes that into the OAuth state. For the purposes of #6648 we'll then validate that origin and use it when sending back the auth result from the popup via the `postMessage`. For your purpose you'd read the origin from the OAuth state in the lambda and then route to the correct instance. As I understand the missing piece would be the verification of the URL through the JWT, but is that really protecting again anything as I assume you could just send the request straight to one of the backends instead?

**Comment by iain-b** [comment]
@Rugvip Yep I think that would cover us. 

We can do without the JWT encoding for the OAuth flow. Particularly as the lambda also handles installation callbacks it gave us confidence the request was initiated via roadie. There's no particular threat it's protecting us from more just caution / over caution.

**Comment by Rugvip** [comment]
👍, it's being implemented in #6772

**Comment by Rugvip** [comment]
Closing this as #6772 is now merged. It'll be included in the Aug 19th release
