### ISSUE TITLE
[RFC] Explicit status check handlers

### ISSUE THREAD

**Issue by TejasQ** [backstage/backstage#6450]
**Status:** Open for comments

## Need
https://github.com/backstage/backstage/blob/7a6a3586ac4be347724071cd1a94c91b4504504c/packages/backend-common/src/service/createStatusCheckRouter.ts#L25

Currently, the `statusCheck` property is _optional_: users can call `createStatusCheckRouter` and _not provide_ an actual status check. If a status check is not provided, it simply returns a `200` and `''` in a header (why?), passing a health check.

https://github.com/backstage/backstage/blob/7a6a3586ac4be347724071cd1a94c91b4504504c/packages/backend-common/src/middleware/statusCheckHandler.ts#L46

The implicitness of this has proven a bit confusing for us, because our health check endpoints return a status of `200` in the absence of an explicit handler, without _any code in our codebase_ indicating why/how this is happening. A Cmd+Shift+F codebase search also returns 0 results. Effectively, we have no answer for "why is this behaving this way" unless we dive through this project's source code and read the "reasonable" fallback.

## Proposal

I propose making the `statusCheck` property _required_ and expecting consumers/users to take care of status checks. This would also simplify Backstage's source code immediately by removing the fallback.

## Alternatives

We could also leave everything as it is and merely _document_ the implicit 200 fallback, but that would still make things a little less convenient for our users I imagine because they'd first experience surprising implicit behavior, _then_ Google, _then_ find the docs, _then_ understand why. 

I believe explicitness would be more ideal in this case.

## Risks

This could be a breaking change for plugin authors et al, but I believe it would bring greater returns longer term for users/developers who work with Backstage at the code level.

**Comment by OrkoHunter** [comment]
We should definitely document the default behavior as close to the code as possible. PR here https://github.com/backstage/backstage/pull/6451

Now to the question of whether we should make `statusCheck` mandatory, let's think about "Does this change increase the difficulty of creating new plugins?".

So my vote goes to either (1) leave everything as-is or (2) mark `statusCheck` mandatory and update the `@backstage/create-app` skeleton properly to make sure this is implemented out-of-the-box.

cc @andrewthauer What are your thoughts on this? I ran `git praise` and found you. 😄

**Comment by andrewthauer** [comment]
I would call this the default behaviour rather then a fallback. The simplest health check is typically checking if the server is responding, so that's essentially what it's doing. I personally have no issues making it mandatory either, assuming there's a simple default status check that is exported and usable for the default/simple status/health check behaviour.
