### ISSUE TITLE
Backstage core Table pagination not working

### ISSUE THREAD

**Issue by victorhahn** [backstage/backstage#6452]
We have discovered a recent regression in the pagination functionality of the `@backstage/core-components` Table component in our Backstage installation.

## Expected Behavior
When a user presses the "next page" or "previous page" arrow buttons to toggle pages within a Table it should display the next set of data.

## Current Behavior
When a user presses the "next page" or "previous page" arrow buttons no action is performed. An error is thrown and displayed in the console:
![Screen Shot 2021-07-13 at 10 25 09 AM](https://user-images.githubusercontent.com/19331310/125469551-a81ff75f-f11d-4821-bf44-cb865554e36d.png)

## Possible Solution
This error seems to be related to https://github.com/mbrn/material-table/issues/2943
A potential solution suggested in that issue is to downgrade to an older material-table version until the downstream issue is fixed. There is currently a PR available that should resolve this issue on material-table's side

## Steps to Reproduce
1. Navigate to the Catalog page
2. Click the "next page" arrow button (assuming your catalog has more entities than currently displayed)

## Context
Currently, our users cannot navigate through the pages of data within the catalog (and other custom portions of the app that uses the Backstage Table component). The users can only search for catalog entities or adjust the rows-per-page.

## Your Environment
- NodeJS Version (v12): Node 14
- Operating System and Version (e.g. Ubuntu 14.04): node:14-buster-slim official Docker image
- Browser Information: Chrome Version 91.0.4472.114

**Comment by jh-sh** [comment]
We did update today and don't face any issue with the tables. Yet
our `yarn.lock` looks this way:
```
...
material-table@1.69.2, material-table@^1.69.1:
  version "1.69.2"
...
```
The latest available version is 1.69.3 (released in April)
So another workaround may be resolving `material-table` to 1.69.2 like this:
```
// /package.json
  "resolutions": {
    "**/**/material-table": "1.69.2"
  },
```
