### ISSUE TITLE
Todo plugin hits Github rate limit quickly

### ISSUE THREAD

**Issue by nirga** [backstage/backstage#6473]
Todo plugin hits rate limiting of Github too fast which renders it useless most of the time - it shows a 500 error instead of the TODO list.

## Expected Behavior

TODOs should be cached or rather synced in the background and saved to avoid this.

## Current Behavior

HTTP 500 error (which is a 403 from GitHub) is shown on most renders.

<img width="1440" alt="Screen Shot 2021-07-14 at 18 13 42" src="https://user-images.githubusercontent.com/4224692/125646748-4c0e5e11-3a92-47d8-a32e-edde5e5385d3.png">

## Possible Solution

Caching of responses, or even - move the fetch logic to happen entirely in the background (like components config refresh).

**Comment by OrkoHunter** [comment]
Having very little knowledge of the plugin, but it does seem to be caching the results.

https://github.com/backstage/backstage/blob/12a62ea5f6c4c52284612622cecc35a6e825e920/plugins/todo-backend/src/lib/TodoReader/TodoScmReader.ts#L65-L77

**Comment by nirga** [comment]
Interesting. I wonder though if the read request from Github hits the rate-limit anyway (even if the etag hasn't changed). My 2nd guess is that this might have to do with the background refresh job that runs across all our repos and fetches configs - it might be running too often thus pushing us closer to Github's rate limit.
