### ISSUE TITLE
Custom Error Message on TechDocsNotFound / ErrorPage 

### ISSUE THREAD

**Issue by gasandov** [backstage/backstage#6478]
1. I want to be able to customize the error message that is being displayed on the `TechDocsNotFound` component e.g instead of having this [hardcoded message](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/components/TechDocsNotFound.tsx#L33) by providing a custom message.
2. `ErrorPage` is grabbing content/configurations from the `app-config.yaml` we can leverage a custom section for techdocs only or add new attributes that I can point out to some documentation and not only support channels/pages.
 
![image](https://user-images.githubusercontent.com/49690408/125694253-66dccd60-b805-41ab-a4df-6d901bb7388a.png)

## Feature Suggestion

Enhance error messaging on techdocs and/or backstage in general

## Possible Implementation

TBD | Suggestion: Use `app-config.yaml` 

## Context

Users cannot solve/understand errors fully by reading generic error messages and we cannot deliver a solution to them either

**Comment by OrkoHunter** [comment]
I think it should be possible to customize the ErrorPage component in TechDocs. But instead of going the 'app-config.yaml' way of adding a new techdocs.errorMessage config, it should be neat to override the ErrorPage with a custom one in your Backstage app.

**Comment by dhenneke** [comment]
Related to the discussions in https://github.com/backstage/backstage/issues/6183.
