### ISSUE TITLE
feat(cli): Add a command to ensure all necessary tools are installed to run Backstage locally

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#6479]
## Feature Suggestion

Running a Backstage app locally needs a few things installed in your local computer, `yarn` and `node` being just a few of them. Since Backstage apps are platforms on which developers contribute, we need to ensure that it's easy for them to run Backstage locally.

There should be a command in `backstage-cli`, which they can run as part of "getting started" to ensure that they have all the necessary tools for running a Backstage app, installed in their system.

## Possible Implementation

* Add a command here https://github.com/backstage/backstage/tree/master/packages/cli/src/commands which uses some "command-exists" library to make sure few executables are installed. And optionally prints out installation instructions in console.
* Update the root [`package.json`](https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/package.json.hbs) in the create-app template as well as backstage/backstage repository to add this command as a script. 

## Context

https://github.com/backstage/backstage/pull/5152/files had started this discussion long time ago. https://github.com/backstage/backstage/pull/6477 just now, pushed me into creating this issue.

**Comment by benjdlambert** [comment]
`backstage-cli` check.

**Comment by iamrajiv** [comment]
@OrkoHunter I want to work on this.

**Comment by OrkoHunter** [comment]
Great @iamrajiv ! Assigned it to you

**Comment by freben** [comment]
@iamrajiv @OrkoHunter could this be the same command as #6519 ? I think they could be. So essentially what that ticket suggests, but with the addition of running --version etc and being able to print installation instructions if they aren't there

**Comment by freben** [comment]
Could also warn about unsupported node versions and how to use eg nvm to change it

**Comment by OrkoHunter** [comment]
@freben Yeah, I think `info` can cover both of these use-cases - print versions and stuff, but also warn if every requirement isn't installed.

**Comment by OrkoHunter** [comment]
Closing in favor of #6519
