### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#6485]
### Discussed in https://github.com/backstage/backstage/discussions/6483

<div type='discussions-op-text'>

<sup>Originally posted by **younky-yang** July 15, 2021</sup>
With enabled the LdapOrgReaderProcessor to my company's ldap server, I can successfully load the user and group information to the final_entity table, but I also received the error of "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory"

It happens on both Mac and Windows with Node ver 14.7.1 (Mac) and Node ver 14.6.0(Win). Before I enabled this LdapOrgReaderProcessor from config and catalog.ts, there is no such issue. 

> 2021-07-15T02:28:03.330Z catalog info Reading LDAP users and groups type=plugin
2021-07-15T02:29:43.448Z catalog info Reading LDAP users and groups type=plugin
2021-07-15T02:31:23.526Z catalog info Reading LDAP users and groups type=plugin
2021-07-15T02:33:03.697Z catalog info Reading LDAP users and groups type=plugin
2021-07-15T02:34:43.942Z catalog info Reading LDAP users and groups type=plugin
2021-07-15T02:36:25.749Z backstage info ::ffff:127.0.0.1 - - [15/Jul/2021:02:36:25 +0000] "GET /api/catalog/entities HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
2021-07-15T02:40:27.813Z catalog info Reading LDAP users and groups type=plugin

<--- Last few GCs --->

[78267:0x104d00000]  1181495 ms: Scavenge (reduce) 4079.4 (4100.8) -> 4078.5 (4101.8) MB, 3.8 / 0.0 ms  (average mu = 0.097, current mu = 0.001) allocation failure 
[78267:0x104d00000]  1181502 ms: Scavenge (reduce) 4079.4 (4100.8) -> 4078.6 (4101.8) MB, 4.3 / 0.0 ms  (average mu = 0.097, current mu = 0.001) allocation failure 
[78267:0x104d00000]  1181510 ms: Scavenge (reduce) 4079.5 (4100.8) -> 4078.7 (4102.1) MB, 4.9 / 0.0 ms  (average mu = 0.097, current mu = 0.001) allocation failure 

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x101317585 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000b25c9 node::Abort() [/usr/local/bin/node]
 3: 0x1000b272f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001f6eb7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001f6e53 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x1003a6eb5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x1003a897a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x1003a4049 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x1003a18e1 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x1003b019a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x1003b0221 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x100376d57 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/local/bin/node]
13: 0x1005cf0d8 v8::internal::Handle<v8::internal::NameDictionary> v8::internal::HashTable<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::EnsureCapacity<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::NameDictionary>, int, v8::internal::AllocationType) [/usr/local/bin/node]
14: 0x1005cfe01 v8::internal::Handle<v8::internal::NameDictionary> v8::internal::Dictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::Add<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::NameDictionary>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDetails, v8::internal::InternalIndex*) [/usr/local/bin/node]
15: 0x1005cfd3d v8::internal::BaseNameDictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::Add(v8::internal::Isolate*, v8::internal::Handle<v8::internal::NameDictionary>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDetails, v8::internal::InternalIndex*) [/usr/local/bin/node]
16: 0x10070dbab v8::internal::Runtime_AddDictionaryProperty(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
17: 0x100a8adf9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]

</div>

**Comment by younky-yang** [comment]
More information:
Now I can provide the information as below as I can't always query our ldap server for this testing.
With the test I have got more than 20k users returned and they are all in the final_entity tables already. But we just query one group which just 10+ members in. We didn't query other groups.

I didn't notice the size of the ldap response yet, but I do use the new plugin with and without the customer transformer.

But there is another finding about this. After I encountered this issue, I also tried to running the app from debugging mode in node, but the issue didn't showup, it only happens with normal run. (yarn start-backend).

**Comment by younky-yang** [comment]
Went through the code in catalog-backend-module-ldap/src/ldap/read.ts, and function resolveRelations() has many embeded loop, like below, not sure if this will cause problem if the userMap is bigger. 

  for (const [userN, groupsN] of userMemberOf.entries()) {
    const user = userMap.get(userN);
    if (user) {
      for (const groupN of groupsN) {
        const group = groupMap.get(groupN);
        if (group) {
          ensureItems(newUserMemberOf, user.metadata.name, [
            group.metadata.name,
          ]);
        }
      }
    }
  }

**Comment by coding-to-music** [comment]
I use a droplet on Digitalocean for my development environment.

My usual droplet, plenty for my usual work, is 2 CPU each 2GB memory so 4 GB total
Ran out of memory doing `build tsc` with the same messages shown above in this issue

Tried a larger droplet 4 CPU each 2GB memory so 8 GB total
Ran out of memory doing `build tsc` with the same messages shown above in this issue

Tried a larger droplet 8 CPU each 2GB memory so 16 GB total
Worked!!

**Comment by benjdlambert** [comment]
@coding-to-music what version of `node` are you using? And are you building a fork of the repository or an `npx @backstage/create-app` verison of the source code?

**Comment by benjdlambert** [comment]
We're also moving towards dropping support for node 12 here #6889

**Comment by sagacity** [comment]
We are running into similar crashes at runtime using node 14. We can certainly try to up the amount of memory in the pod, but we have noticed that whereas the backend normally only uses something like ~100-200mb when doing LDAP processing it spikes to 2gb+ and crashes. Perhaps the processor can be improved somewhat to be a bit less memory-intensive :)

**Comment by coding-to-music** [comment]
My notes from when I did the hello world if that helps
https://github.com/coding-to-music/coding-to-music.github.io/issues/237
