### ISSUE TITLE
bump @octokit/rest from 18.5.6 to 18.6.7

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#6489]
Dependabot opened a PR where some types now are `string | undefined` so we just need to update the code to support the new types.

Should be a pretty simple job. PR exists here: #6374

Happy hacking!

**Comment by iamrajiv** [comment]
@benjdlambert I guess we have to do `yarn add string`.

**Comment by iamrajiv** [comment]
@benjdlambert But the branch of #6374 is deleted how I can cherry-pick the commit. It saying `fatal: bad revision '4349a88'`.

**Comment by benjdlambert** [comment]
@iamrajiv the branch is restored, you should be able to fetch the branch now and either carry on working on that branch, or cherry pick the commit onto your own fork.

**Comment by Crevil** [comment]
As PR #6494 got closed due to incomplete implementation I'd like to take this one on me to do another run 😄
