### ISSUE TITLE
TimeLimitExceededError for LDAP

### ISSUE THREAD

**Issue by roylisto** [backstage/backstage#6490]
## Expected Behavior
The ingestion works successfully

## Current Behavior
I get this error 
`Processor LdapOrgReaderProcessor threw an error while reading ldap-org:ldap://ldap.jumpcloud.com:389; caused by Error: LDAP search at DN "ou=Users,o=xxxx,dc=jumpcloud,dc=com" failed, 3 TimeLimitExceededError: Time Limit Exceeded type=plugin
`
when ingesting data from LDAP to backstage. 
This is only happening when the data is large. I have more than 3000 LDAP users data that need to be ingested. If the data is below 2000, it still works.
## Steps to Reproduce

by following this doc https://backstage.io/docs/integrations/ldap/org
## Context

We have a large LDAP users, and all of them need to be inside backstage

## Your Environment

- NodeJS Version (v14):
- Operating System and Version: MacOs Catalina
- Browser Information: Chrome

**Comment by freben** [comment]
For posterity and others searching for the same problem, did you enable the `paged` option to get this sorted?
