### ISSUE TITLE
Include @types/react as a dependency when running backstage CLI create-plugin command

### ISSUE THREAD

**Issue by rubenLindstrom** [backstage/backstage#6508]
## Feature Suggestion
@types/react is not included as a dependency by the `create-plugin` backstage CLI command, but I believe it is needed.
However, if it is not really needed, please close this issue.

## Possible Implementation
Include @types/react v. 16.9 as a dependency in the package.json generated by the `create-plugin` command in the backstage CLI.

**Comment by OrkoHunter** [comment]
> Closing since it isn't required for all plugins, and should thus just be added manually. https://github.com/backstage/backstage/pull/6509#issuecomment-882354759

@rubenLindstrom can the issue be closed as well?
