### ISSUE TITLE
cli: add a `backstage-cli info` command

### ISSUE THREAD

**Issue by freben** [backstage/backstage#6519]
## Feature Suggestion

Similarly to [the Tauri CLI](https://tauri.studio/en/docs/usage/development/integration), add an `info` command to `backstage-cli` that lists at least

- [ ] operating system 
- [ ] node version 
- [ ] npm version
- [ ] yarn version (even if this is expected to be the pinned one in the repo - still useful to look for deviations)
- [ ] the version of the currently running backstage-cli
- [ ] whether the current repo is a clone or a fork or a create-app generated repo?
- [ ] more? Perhaps actual _resolved_ versions of backstage libraries that the app and backend packages build against?

## Context

When helping users with issues, we very often ask for info like this. It would be very useful to be able to tell users to paste the output of this command as-is.

**Comment by allentv** [comment]
Is someone working on this?

**Comment by OrkoHunter** [comment]
@allentv Doesn't look like it. Would you like to work on this?

**Comment by Charizard** [comment]
@OrkoHunter I would like to take a stab at this.

**Comment by lmasiero** [comment]
Builds are failing while trying to use documentation. backstage-cli not found.
Perhaps a updated Dockerfile / packages.json could solve this issue? 

```Step 13/22 : RUN yarn --cwd packages/cli/bin backstage-cli backend:bundle --build-dependencies
 ---> Running in 05802f86acf8
yarn run v1.22.1
error Command "backstage-cli" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn --cwd packages/cli/bin backstage-cli backend:bundle --build-dependencies' returned a non-zero code: 1```

**Comment by OrkoHunter** [comment]
@lmasiero You're running backstage-cli from a different place than the one on docs https://backstage.io/docs/deployment/docker#multi-stage-build

`yarn --cwd packages/cli/bin backstage-cli ...` vs `yarn --cwd packages/backend backstage-cli`

**Comment by orihomie** [comment]
@OrkoHunter Hi, could you please give me an advice of the documentation of multi-stage build since it isn't working exactly on the step you've mentioned in your last message here?
I've tried both of that folders you have mentioned and none of them worked.

>  [build 8/8] RUN yarn --cwd packages/cli/bin build:                                                       
#11 0.559 yarn run v1.22.1
#11 0.628 $ backstage-cli package build
#11 0.642 /bin/sh: 1: backstage-cli: not found
