### ISSUE TITLE
[Plugin] Allure Test Report

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#6528]
## Summary

Allure is a test report framework supporting many test frameworks across programming languages. 
Allure reports are html based, can be embeded as iframe to backstage UI under catalog component.

## Project website (if applicable)
https://docs.qameta.io/allure/
https://github.com/fescobar/allure-docker-service

## Context
Allure Framework is a flexible lightweight multi-language test report tool that not only shows a very concise representation of what have been tested in a neat web report form, but allows everyone participating in the development process to extract maximum of useful information from everyday execution of tests.

**Comment by deepak-bhardwaj-ps** [comment]
I would like to work on this

**Comment by deepak-bhardwaj-ps** [comment]
Can someone, please, assign this to me :)

**Comment by deepak-bhardwaj-ps** [comment]
Can we close this now as the Allure plugin is published.
