### ISSUE TITLE
Support request timeouts in the UrlReader

### ISSUE THREAD

**Issue by dhenneke** [backstage/backstage#6531]
For some applications, it would be helpful to be able to timeout a `readUrl(...)` request. We sometimes use a circuit breaker in combination with a timeout from [cockatiel](https://www.npmjs.com/package/cockatiel) to wrap calls in our custom plugins. However, when we timeout, the call is still in progress and might also finish after we went ahead with other tasks. We could also handle this by discarding a response after it has finished, but that isn't a really good solution.

For `fetch` calls, the following should work:

```ts
const timeoutMs = 5000;

const controller = new AbortController();
setTimeout(() => controller.abort(), timeoutMs);

fetch('https://example.com', { signal: controller.signal });
```

It might be good to provide a helper function that creates the signal.

## Possible Implementation

1. Add a `{ timeout?: number }` property to [`ReadUrlOptions`](https://github.com/backstage/backstage/blob/5b9e6a78b56533ebb39cbb3b8b55683b0aa09828/packages/backend-common/src/reading/types.ts#L60-L73) and [`SearchOptions`](https://github.com/backstage/backstage/blob/5b9e6a78b56533ebb39cbb3b8b55683b0aa09828/packages/backend-common/src/reading/types.ts#L178-L191).
2. Add the (optional) timeout logic to all `UrlProcessors` that either use `fetch` or which library support timeouts.

**Comment by freben** [comment]
Still relevant!

**Comment by freben** [comment]
Gave this a shot ^

**Comment by freben** [comment]
I preferred to send in the actual signal instead, since that's the API that should be the most familiar, and is directly usable by the implementation. It also plays well with a possible future [context](#8042), which wants to merge different timeouts/deadlines etc.
