### ISSUE TITLE
Api Docs CORS proxy support

### ISSUE THREAD

**Issue by brethubbard** [backstage/backstage#6540]
## Feature Suggestion

Add support for a proxy for requests coming from SwaggerUI

## Possible Implementation

I found [this issue](https://github.com/swagger-api/swagger-ui/issues/5731#issuecomment-559768068). We could expose a `requestInterceptor` then pass it into `<SwaggerUI ... />`.

## Context

It would be easier for teams to adopt if each service didn't have to configure CORS for Backstage.

**Comment by wanisfahmyDE** [comment]
Hi @brethubbard is this already supported or is there a workaround available? 
thanks
