### ISSUE TITLE
Why do URL Reader response types return Buffer instead of string?

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#6547]
The response type of [`readUrl`](https://github.com/backstage/backstage/blob/e47f2a3c095227245e5ac0048daa6fbea989ea8b/packages/backend-common/src/reading/types.ts#L82), [`readTree`](https://github.com/backstage/backstage/blob/e47f2a3c095227245e5ac0048daa6fbea989ea8b/packages/backend-common/src/reading/types.ts#L155), and [`search`](https://github.com/backstage/backstage/blob/e47f2a3c095227245e5ac0048daa6fbea989ea8b/packages/backend-common/src/reading/types.ts#L220) all have methods which return a Promise of a Buffer with the contents of a file.

To align with this API, the URL Reader implementations e.g. [GitHub](https://github.com/backstage/backstage/blob/e47f2a3c095227245e5ac0048daa6fbea989ea8b/packages/backend-common/src/reading/GithubUrlReader.ts#L113) have a create a Buffer from the text they receive from GitHub in response. The consumer of the URL Reader API then has to convert these Buffers into text for further use.

Two questions on URL Reader API -
1. What is the benefit of having a method which returns a Buffer instead of plain string?
2. Should we change Buffer to string or add a new method which returns string?

**Comment by freben** [comment]
There was no assumption on the API level that users were always going to read _only_ text format things using the `UrlReader` API. It's actually a bit odd that the github implementation is made that way since it kinda limits the usage of the reader.

**Comment by OrkoHunter** [comment]
Buffer makes sense - sounds good to me!
