### ISSUE TITLE
[TablePagination] Uncaught TypeError: _this.props.onChangePage is not a function

### ISSUE THREAD

**Issue by ConnorDY** [backstage/backstage#6553]
We're using `@material-ui/core@^4.11.0` and experiencing the following error when clicking the button to go the next page:
```
m-table-pagination.js:67 Uncaught TypeError: _this.props.onChangePage is not a function
    at eval (m-table-pagination.js:67)
```

This code previously worked:
```tsx
import { TablePagination } from '@material-ui/core';

export default function Demo() {
  return (
    <TablePagination
      component="div"
      count={50}
      page={0}
      rowsPerPageOptions={[5, 10, 20]}
      rowsPerPage={10}
      onChangeRowsPerPage={(event) => console.log(event.target.value)}
      onChangePage={(_event, newPage) => console.log(newPage)}
    />
  );
}
```

TypeScript complains that `onPageChange` is needed and that `onChangeRowsPerPage` and `onChangePage` are deprecated.

So we changed the code to:
```tsx
<TablePagination
  {/* ... */}
  onRowsPerPageChange={(event) => console.log(event.target.value)}
  onPageChange={(_event, newPage) => console.log(newPage)}
/>
```

With this we're still getting the same error as above.

I tried creating a clean repo with only React and `@material-ui/core` as the dependencies and this error went away.

It would appear that somehow it's using the component from the `material-table` package instead even though we're not importing anything from `material-table`:
```bash
> find . -name "m-table-pagination.js"
./node_modules/material-table/dist/components/m-table-pagination.js
```

## Your Environment

- NodeJS Version: `v14.13.0`
- Operating System and Version: `macOS 10.15.7`
- Browser Information: `Chrome 91.0.4472.114`

**Comment by benjdlambert** [comment]
@ConnorDY replied to you in Discord too, but if you wanna build up a PR for moving to the new library over `material-table` i'd be happy to take a look :)

**Comment by jh-sh** [comment]
@benjdlambert I guess this one is the same #6452

**Comment by benjdlambert** [comment]
Indeed @jh-sh - That's where I saw the other mention of `material-table`. Couldn't find it when I was looking for it.
