### ISSUE TITLE
Refactor CopyTextButton to use Clipboard API

### ISSUE THREAD

**Issue by tudi2d** [backstage/backstage#6566]
## Feature Suggestion

The `CopyTextButton` in `backstage/core-components` uses the deprecated `document.execCommany('copy');` functionality. The implementation currently requires a workaround creating a non-visible textarea with the visible text, which should be copied:
```jsx
<textarea
  ref={inputRef}
  style={{ position: 'absolute', top: -9999, left: -9999 }}
  defaultValue={text}
/>
``` 
and manually triggering a select on the non-visible textarea:
```ts
inputRef.current.select();
document.execCommand('copy');
``` 
This leads to issues related to a11y & creates an unnecessary overhead (rendering the same text in 2 elements & using refs). Furthermore the new Clipboard API provide more flexibility & will be future proof approach.

## Possible Implementation

In `CopyTextButton.tsx`:

`handleCopyClick` - use the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
): 
```ts
navigator.clipboard.writeText("<empty clipboard>").then(() => {
  /* clipboard successfully set */
}, () => {
  /* clipboard write failed */
});
```

`render`: 
```diff
-<>
-   <textarea
-      ref={inputRef}
-      style={{ position: 'absolute', top: -9999, left: -9999 }}
-      defaultValue={text}
-   />
    <Tooltip ...>
      ....
    </Tooltip>
-</>
```

## Context

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard
https://dequeuniversity.com/rules/axe/4.3/label?application=axeAPI
https://backstage.io/storybook/?path=/story/inputs-copytextbutton--default

**Comment by vcapretz** [comment]
hey @tudi2d, I implemented the suggested solution and created the PR, I tested it using storybook and it works great :D

**Comment by tudi2d** [comment]
Closing this issue as PR #6869 is merged.
