### ISSUE TITLE
[GitHubAuth] Restrict org memebership for sign in

### ISSUE THREAD

**Issue by axdotl** [backstage/backstage#6577]
When sign-in with GitHub on `SignInPage` only users which are member of a specific org should be allowed.

## Feature Suggestion

Our primary sign-in method is GitHub (we also use the GitHub org processor), so users have an overview about their owned services, etc.
Currently we're running an [oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/) in front of backstage, which requires a login with users Google account to ensure org restriction.

## Context

To improve user experience it would be great to get rid of the additional authentication step in front of backstage.

**Comment by timbonicus** [comment]
This should be possible using `signInProvider` once the GitHub portion of #6245 is available.
