### ISSUE TITLE
[Plugin] Release Manager

### ISSUE THREAD

**Issue by miixell** [backstage/backstage#659]
## Summary
This is a proposal for a new plugin called “Release Manager”. The purpose of the plugin is to get an overview of the ongoing mobile releases. 

## Context

We have worked on a plugin, written in TS, called “Release Manager”. This view gives the users an overview of the current release and the status of it. The aim of this plugin is to gather all the sources of information in a release into one place, so that the user can feel confident about releasing their product. We have mainly one backend that orchestrates the necessary requests to our backend services. We want to open source one pane “Latest Build in App Store”, and ask the community to add improvements or their own panes.
 
“Latest Build in App Store”-pane interacts with two backend services that are written in Python which sends requests directly to Google Play Store and the Appstore using their official API’s. The user would need to provide service accounts to both of the stores in order to use the backend services.

![image](https://user-images.githubusercontent.com/11750941/80376749-91c26a00-889a-11ea-8135-30aa0bbb00dc.png)

“Latest Build in App Store” pane for Android
![image](https://user-images.githubusercontent.com/11750941/80376715-87a06b80-889a-11ea-8dfe-c1e9af3f56c6.png)

“Latest Build in App Store” for iOS

![image](https://user-images.githubusercontent.com/11750941/80376661-72c3d800-889a-11ea-95bb-aff8e10c85f2.png)

Our question is if there are any recommendations in regards to open sourcing backend services? 

Please let us know if you have any feedback, further questions or suggestions! 🎊

**Comment by BalestraPatrick** [comment]
This looks good! I think the backend could definitely be shared with the plugin I proposed in #603 since they both hit the official App Store Connect API.

**Comment by miixell** [comment]
@BalestraPatrick Definitely! 👏 💪

**Comment by sterlingwes** [comment]
@miixell would love to help with this. Curious how you're getting release status from Google Play? Their documented API is quite limited to the release workflow ("edits") and not so much for querying status unless you retain those identifiers

**Comment by miixell** [comment]
@sterlingwes Hi! We've already implemented the plugin(just fine tuning it now). Like it said in the description, we're retrieving the status through their API by using a backend service. Thanks for offering to help! 🙏

**Comment by petergrau** [comment]
@miixell is it already available for usage / beta testing?

**Comment by benjdlambert** [comment]
There's a PR that @adamdmharvey just mentioned https://github.com/backstage/backstage/pull/3729 with some progress.

**Comment by regicsolutions** [comment]
@miixell was wondering if there are any plans on open-sourcing the release-manager plugin shown?
