### ISSUE TITLE
Relax restrictions on component names

### ISSUE THREAD

**Issue by madelson** [backstage/backstage#6592]
## Feature Suggestion

Today, I when ingesting catalog info files I see the error `Error: "metadata.name" is not valid; expected a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total but found...`

## Possible Implementation

Hard to say; I'm not sure why component names are restricted in this way (still very new to Backstage!). I see that supporting `/` might be tough currently because of the namespace syntax; perhaps namespace would take precedence when parsing such names?

## Context

I'm trying to populate backstage with NuGet and npm packages as library-type components. I'd really like to populate backstage with our internal and external package dependencies and link these to our services so we can use Backstage for processes like flagging apps that reference out-of-date/vulnerable package versions and understand usages across our ecosystem.

All of our internal packages (and many external ones we reference) use a scope to avoid name collisions. Therefore, the names are like `@<company>/abc-xyz`. 

In a few cases, we've also run into the length limitation; some packages are very verbosely named such as https://www.nuget.org/packages/runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl/.

Given that packages have well-known and unique names, I'd really like to just be able to use the true name of the package as the component name rather than mangling the name to meet the restrictions.

**Comment by freben** [comment]
Hi!

You can make your own validation rule overrides by using [makeValidator](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/validation/makeValidator.ts#L33) and [passing that to the catalog builder](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/next/NextCatalogBuilder.ts#L18) in your [backend setup of the catalog](https://github.com/backstage/backstage/blob/master/packages/backend/src/plugins/catalog.ts#L27).

However as you say, slashes (and colons) are discouraged and may lead to breakage in unexpected places.

The reason that this is kind of restricted is that it's more than a name - it's [the unique ID](https://backstage.io/docs/features/software-catalog/references) of the entity (together with namespace and kind).

**Comment by madelson** [comment]
Thanks @freben . Perhaps my enhancement request then is to make the default set of validation rules more flexible so that things like importing package dependencies will work "out of the box". Curious whether that change (and my use-case) seem reasonable to you?

**Comment by freben** [comment]
Probably not - at-signs maybe, but I'd say not slashes. Besides, the current rules are 1:1 to the actual k8s rules which are kind of familiar and easy to type out and render in URLs etc.

I'd say the best way here is a canonical encoding in the name, eg `company--abc-xyz` or so. And then we could work toward having adding `metadata.title` support for other kinds than just `Template`. That way you can always get the nice human friendly rendering in the interface with the full package name without restriction, while not having to mess with the validation rules.

**Comment by madelson** [comment]
> I'd say the best way here is a canonical encoding in the name, eg company--abc-xyz

I think `--` is actually disallowed currently (at least I was getting errors until I removed it from names).

> we could work toward having adding metadata.title support

This would definitely help with the usability issue and seems like a great build if the team intends to keep the current restrictions.

In my opinion, though, it would still be ideal if users of the system didn't have to do the name mangling and could just use the "true" names of their components, letting backstage handle URL generation and such.

**Comment by freben** [comment]
> I think `--` is actually disallowed currently (at least I was getting errors until I removed it from names).

That was actually relaxed in a recent pull request! Should be released yesterday, if not even the week before.

> In my opinion, though, it would still be ideal if users of the system didn't have to do the name mangling and could just use the "true" names of their components, letting backstage handle URL generation and such.

Yeah I understand. The trickiest thing here is that we've this established standard of how to encode `kind:namespace/name` triplets _without encoding_, and it gets into unsolvable situations where we don't know if a segment is part of a name or a namespace if there are slashes.

To be able to write such triplets by hand with your proposed relaxation, we'd have to ask people to do some form of encoding by hand when typing out the name - less than ideal too.

**Comment by madelson** [comment]
I still think that building in a more robust approach to component naming would be valuable. Requiring name mangling to work with npm packages out of the box is pretty frustrating both in terms of setup and in terms of leading to a worse UX.

**Comment by madelson** [comment]
Curious if the maintainers anticipate ever taking this on or whether it is deemed too difficult/not aligned with the project. We have a group that is thinking about whether to adopt backstage for our components and having to mangle all the names will definitely reduce the usability of the system.

**Comment by Rugvip** [comment]
@madelson What we're currently thinking is that we want to make it way easier to do these kind of overrides. As in setting up your own rules for what the catalog expects should be a quick and simple customization.

As for changing the defaults that we ship with the catalog there's gonna be a fair bit of resistance there right now, which will just increase over time as it ends up being a fairly significant breaking change.

I'll add in that the catalog model supports any characters in the name, including `:` and `/`, except of course that the schema forbids them. Only the first `:` or `/` encountered in an entity reference will be used as dividers for kind and namespace, and because of that we do forbid those characters in the kind and namespace. For example `foo:bar/baz/qux` would be parsed as `kind=foo`, `namespace=bar`, `name=baz/qux`. A pretty huge caveat though is that if you enter the name in isolation somewhere that expects an entity reference, that'll end up being parsed as `namespace=baz`, `name=qux`

**Comment by madelson** [comment]
> What we're currently thinking is that we want to make it way easier to do these kind of overrides

+1. We wouldn't want to do this unless it was going to be well-supported going forwards. Would this grant flexibility over length? Would it allow `/` (since we have a lot of npm packages which are named `@scope/xyz` the `/` comes up a lot)?

**Comment by jhaals** [comment]
There's definitely a possibility of hitting some hidden/future bugs going with `/` in names where plugins or some third party integration later relies on some string splitting that isn't properly configured for this use case.
The name length can be changed. It's carried over from Kubernetes. These names has to conform with the DNS limitations as it often converted to a DNS record. As we want to play nicely with other CNCF projects which also had tons of research behind their limitations we opted to use the same limitations. Again this can be changed but with a big warning that things might break in unexpected ways now or at a later stage.
