### ISSUE TITLE
EntityPage tab height displaying incorrectly in Firefox

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#6596]
When viewing the EntityPage in Firefox, the tabs under the page header are sometimes cut off.

## Expected Behavior

Tabs should always be rendered at full height like:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/6507159/126803908-6d3c42b9-6804-43b3-9231-0df0f80104ad.png">

## Current Behavior

At some browser screen widths the tabs are rendered like:

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/6507159/126803785-d21bf479-15ee-410e-9c22-41650107277c.png">

## Possible Solution

?

## Steps to Reproduce

Must view in Firefox (developer edition in this case)

1. Open Firefox
2. Navigate to a component entity page
3. Change the browser widow width. At some breakpoints the top part of the tab gets cut off

## Context

Started happening when upgrading to the newest release which was 2 released behind.

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04): macOS
- Browser Information:  / Firefox Developer Edition

**Comment by benjdlambert** [comment]
@tudi2d this isn't some regression from the performance work is it?

**Comment by tudi2d** [comment]
will take a look at it

**Comment by tudi2d** [comment]
The linked PR would fix this issue. As far as I understand it is a different in how Grid Layouts are implemented. I saw another problem related to this. In Firefox the Tabs are breaking the width of the page leading to a weird scroll. To solve both of this issues the easiest thing would be to remove the Grid Layout from the page.

![firefox_tabs](https://user-images.githubusercontent.com/8904624/127199392-2bc62043-7aaa-45fc-a61b-a6405d5c3317.gif)
