### ISSUE TITLE
Inherit techdocs location in a system/domain

### ISSUE THREAD

**Issue by abgn** [backstage/backstage#6603]
## Feature Suggestion
If a component or resource is a part of a system or a domain and the techdocs annotation is unspecified it would be nice if the location of documentation is inherited.

## Context
I would like to write documentation on the highest level of abstraction and still have the individual components in a system/domain to link back to it.

**Comment by andrewthauer** [comment]
@abgn - I'm not 100% following what your suggesting here. Can you clarify? In your scenario where is the documentation located? Is it on the domain/system or component? Are you trying to aggregate component level documentation into the parent system/domain?

Also #5913 might be relevant to this discussion.

**Comment by abgn** [comment]
@andrewthauer exactly, the idea is that the "generic" documentation might reside at a domain/system level with breakouts of more specialized documentation at component/resource level. Not everything need to be documented but most likely everything need to have some documentation attached to it.
#5913 would probably solve this though since my main gripe right now is that /docs gets pretty busy when linking everything in a system to the same documentation.

**Comment by dhenneke** [comment]
One thing that came to my mind when we added Backstage to a monorepo that hosts a `System` and multiple `Component`s and `API`s is that I sometimes wish I could just say "this API should have the same documentation as its providing component" or "... as its system". I wouldn't go that far to want to have it done automatically, but we could add a `backstage.io/techdocs-ref: catalog:system:my-entity` annotation.

The `catalog:<entity-ref>` type could mean that the docs reader either displays the documentation of the other entity, or it simply shows a big "see the documentation of <entity-ref>" link that forwards you to the other entity.

**Comment by MouadhDos** [comment]
still relevant

**Comment by bforbis** [comment]
Looks like this functionality was done in #19279. It requires you to specify an annotation on your component to link to the system docs:
```
annotations:
    backstage.io/techdocs-entity: system/default:my-system
```
