### ISSUE TITLE
The way to change Catalog Page title

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#6604]
Hi,

Is there a way to change Catalog page title?
![image](https://user-images.githubusercontent.com/56138162/126887677-634f4574-1b93-4e8f-a7d9-95546028d424.png)

**Comment by chuliang014** [comment]
I am wondering if there is any possibility to make this prop configurable.
![image](https://user-images.githubusercontent.com/56138162/126888306-4ceabd04-2f70-45c3-aca8-755e36ea430d.png)

**Comment by benjdlambert** [comment]
You can of course set `organization.name` in `app-config.yaml` to override the `Catalog` prefix, but if you wanted to replace the entire wording then I think you would have to use the components that the `plugin-catalog` exports to create your own `CatalogPage` at the moment.
