### ISSUE TITLE
[RFC] Improve Developer Experience of LDAP Plugin

### ISSUE THREAD

**Issue by TejasQ** [backstage/backstage#6606]
**Status:** Open for comments

## Need

Currently, the LDAP plugin is quite opaque: when using it to read and ingest users from an LDAP service, we have nearly no output other than one line in the logs:

```bash
2021-07-26T08:35:21.071Z catalog info Reading LDAP users and groups type=plugin
```

When `LOG_LEVEL=debug` is used, we get a little bit more, but not nearly enough to facilitate efficient development. Specifically, we do not know when:
- the plugin boots up,
- the plugin connects to an LDAP service,
- the plugin successfully reads users and groups or fails,
- ingestion starts,
- ingestion is in progress over time, with ideally an estimated time of completion because some orgs have upwards of 10K records and predictability would help a lot here, and finally when
- ingestion ends and all users/groups have been imported.

## Proposal

I propose we add more detail to the logging that exposes this information in order to allow for a lot more transparency to developers using this plugin. I believe this will improve its developer experience.

### Reasonable Defaults

To further improve the developer experience, I also propose adding reasonable defaults to the LDAP reader's configuration, specifically

```
scope: sub
paged: true
```

Let's talk about these.

1. **`scope: sub`**: This directive indicates to the LDAP reader to search for all descendants of the search base, instead of the first level down, or just the base object. This is useful because it fits a more generic user/group data model and accommodates varying organizational structures of LDAP directories. I feel this would be the easiest for most consumers to adopt for these reasons. Other alternatives include reading users and groups from levels that are either too shallow or too deep.

2. **`paged: true`**: At scale, without paging, this plugin will receive more data than it can handle and either crash or timeout, as we've experienced using this at Spotify. To remedy this, I propose adding paging as a reasonable default.

We would of course add documentation to make these defaults explicit, as well as instruct users on how to customize them to best suit their organization.

## Alternatives

We leave it the way it is? 🤔 

## Risks

1. The `sub` search might get quite deep in an organization's LDAP tree and take a very long time to yield results, however our use of paging remedies this.

**Comment by freben** [comment]
I vote yes for all of these! Path of least surprise and most visibility.

**Comment by benjdlambert** [comment]
I wonder if it makes sense to also move over to using https://github.com/ldapts/ldapts instead of ldapjs. Maybe a nicer query API and looks to be maintained. Wondering if ldapjs is kind of no longer maintained?

**Comment by TejasQ** [comment]
This is a lovely idea! TypeScript for life!
