### ISSUE TITLE
[scaffolder] Link to documentation of a template if it exists in TemplateCard

### ISSUE THREAD

**Issue by Pike** [backstage/backstage#6649]
I've created documentation for a template (just local dev for now), and it'd be nice if that doc would be linked from `http://localhost:3000/create/`

## Feature Suggestion

Add link to documentation for scaffolder templates. This would help in cases where you want to share more context about what a template would be good for. Say you have a few dashboard templates, and you want to explain to a data science engineer which to use.

## Possible Implementation

Similar to the VCS source location, optionally link to the documentation of a template in `TemplateCard`.

**Comment by rodgomes** [comment]
We would love something like that as well. 
@Pike where in the card would you put this icon?

**Comment by Pike** [comment]
I'd probably put it in the card actions, next to https://github.com/backstage/backstage/blob/25b94e63455f1fb170506f9e84e3f430f4b79406/plugins/scaffolder/src/components/TemplateCard/TemplateCard.tsx#L210-L217.

In the meantime, I started wondering if this can be implemented w/out adding a dependency on the techdocs plugin.

**Comment by benjdlambert** [comment]
I actually think that this has been done over here in https://github.com/backstage/backstage/pull/13662

**Comment by rodgomes** [comment]
that is indeed exactly what I was looking for, thanks for sharing the PR link

**Comment by freben** [comment]
Alright, closing as fixed for now!
