### ISSUE TITLE
Real User Monitoring: Generic support in CLI package for different Monitoring Provider 

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#6657]
We are facing challenges in getting the NewRelic Browser/RUM monitoring working.

We noticed the changes made in `cli` package for GoogleAnalytics and DataDog via this PR : https://github.com/backstage/backstage/pull/5374

## Feature Suggestion

Can it be refactored to support RUM in more generic way without making provider specific changes in core cli module ?

## Context

We tried different approaches to make it work:
1. Added NewRelic browser monitoring script via `react-helmet` and `react-helmet-async`.  At runtime, this script dynamically injects another <script> element, which makes the RUM work.
2. For guest user, NewRelic RUM api calls are not happening, but does work if the page is manually refreshed- as the script takes different route to lookup localstorage for user/auth context after the first page load.
3. For logged in user (Microsoft AD), NR api calls are not happening, even after refreshing the page.

**Comment by kiranpatel11** [comment]
Also does the `cli` bundler, replaces the config placeholders (clientKey, AccountId, etc) at build-time or run-time ?  

It seems to be build-time to me, if that is the case, its also cumbersome to build image per environment as we have different configuration for non-prod and prod.

**Comment by regicsolutions** [comment]
@kiranpatel11 wondering if you ever got passed this issue? Running into a similar issue

**Comment by kiranpatel11** [comment]
@regicsolutions, yes we managed to make it work with `react-helmet-async`. 

In our case, we need to include the NewRelic monitoring script into <head> element, the custom env specific configuration were introduced to app-config.yaml by extending the schema in app/package.json.

Please let me know if you need further details.

**Comment by Rugvip** [comment]
Gonna close this as I think the direct ask was fixed in #8545. I still think we want to modularize the analytics integrations in the frontend, but leaving that to be handled in separate issues
