### ISSUE TITLE
Templates: Ability to pin recommended templates

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#6661]
To make the recommended templates visible when user land on **Templates** page, allow to pin those templates at 
the top of the grid. 

## Feature Suggestion
Similar to how core plugins are visiable at the top of the marketplace here https://backstage.io/plugins. The recommended templates should appear at the top in the Templates page.

## Context

In a large org, there are quite a few templates added, some are recommended templates managed by shared-services/platform team - serving the need of wider audience; others are managed by specific teams - serving the need of the smaller number of users/team. 
As Backstage site admin, it should allow to show particular templates at the top of the list to make the recommendations easily visiable by default.

**Comment by kuangp** [comment]
I'm interested in this functionality

**Comment by freben** [comment]
Sure!

**Comment by jrusso1020** [comment]
Opened up a PR for this https://github.com/backstage/backstage/pull/8252 @freben @kuangp
