### ISSUE TITLE
`npx @backstage/create-app` should support a `--tiny` or `--bare` flag

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#6666]
## Feature Suggestion

It should be possible to create a new Backstage app with bare minimum dependencies (plugins) installed.

## Possible Implementation

For the tiny Backstage app, we can probably remove the following from the current [default create-app template](https://github.com/backstage/backstage/tree/master/packages/create-app/templates/default-app)

- api-docs plugin
- tech-radar plugin
- cypress E2E tests setup
- sample entities provided in app-config.yaml
- Docker related files
- proxy plugin(?)
- techdocs(?)
- scaffolder(?)

Open for suggestions!

## Context

After creating a new app and trying to remove API docs plugin - I felt this was not straightforward for me. I had to update few things in `App.tsx` and `EntityPage` and I was still not sure if it's all gone. I can imagine some newcomers would also want to start from "scratch/tiny/bare app" to understand what's going on when adding plugins.

**Comment by freben** [comment]
Could also be implemented in terms of an entirely separate [template](https://github.com/backstage/backstage/tree/master/packages/create-app/templates) instead. Question is how well this all scales in terms of maintenance.

**Comment by freben** [comment]
I mean, in an ideal world, the default template is the completely bare one, and plugin installation is trivial.

**Comment by OrkoHunter** [comment]
@freben Hmm, I'm not sure if the _current_ default template is the bare app in its smallest form. If my first instinct after creating a Backstage app is to remove a couple of plugins which I don't need at the beginning (e.g. techradar), I think it can be further simplified. :) The same argument doesn't suit for Catalog since that is something you'd start with.

**Comment by freben** [comment]
No you are right, I meant that ideally the default should be completely bare. And that we should make it so trivial to add plugins, that the value of a non-bare template becomes almost zero
