### ISSUE TITLE
scaffolder: sample templates should validate component name properly

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#6687]
## Expected Behavior

Components created through our sample templates should always be possible to register in the catalog using the default validation rules.

## Current Behavior

The validation of the entity name in our sample templates is too lax, for example allowing spaces. This will break the catalog registration step when creating the new component.

## Possible Solution

Validate the name field in our sample templates using the same Regex as entity names are validated by, for example here: https://github.com/backstage/backstage/blob/13f5d78b0bb079030c9c8d1d58cea2bb6bacfa38/plugins/scaffolder-backend/sample-templates/react-ssr-template/template.yaml#L20

## Steps to Reproduce

1. Try to create a component called `A B C`
2. Wait for scaffolder job to complete, which it will do succesfully
3. Try to find the component in the catalog, it's not there. Check backend logs for error: `Policy check failed; caused by Error: "metadata.name" is not valid; expected a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total but found "A B C"`

**Comment by Rugvip** [comment]
As pointed out by @mtlewis this needs to be fixed in https://github.com/backstage/software-templates/tree/main/scaffolder-templates as well :grin:

**Comment by mtlewis** [comment]
Adding the [pattern used to validate entity names](https://github.com/backstage/backstage/blob/82b6d84cf3dfcefe0ce4c49935e4b737d0d223f9/packages/catalog-model/src/validation/KubernetesValidatorFunctions.ts#L51) results in pretty ugly error messages (see screenshot below), and by copying it into the template we also leave ourselves open to the risk that the requirements for entity names change and leave the templates out of sync.

![Screenshot 2021-08-02 at 14 54 24](https://user-images.githubusercontent.com/542836/127872941-4bfc9217-3219-486e-8105-b257e3df77bd.png)

Is it perhaps worth considering introducing a new UI field for names that bakes in validation and friendly error messages?

**Comment by benjdlambert** [comment]
Yeah, we could have a `componentName` picker, one thing to consider however, is that people can override their own validation logic in the catalog too https://github.com/backstage/backstage/blob/82b6d84cf3dfcefe0ce4c49935e4b737d0d223f9/packages/catalog-model/src/validation/makeValidator.ts#L24

So we have to support this validation being overridden and it being duplicated, or we expose the validators in the catalog.

**Comment by regicsolutions** [comment]
The [react-jsonschema-form](https://rjsf-team.github.io/react-jsonschema-form/) library has a [extraErrors](https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/#custom-error-messages) option that looks like this:

```
{
  "firstName": {
    "__errors": [
      "some error that got added as a prop"
    ]
  }
}
```

Which would give us something that looks like this:
![image](https://user-images.githubusercontent.com/6157895/128220987-3b982477-4cbd-4e49-a8b6-928d5bc14354.png)

It would be good to have something like this in place for regular expressions, they also have [Custom validation rules](https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/#custom-validation-rules) which would also come in handy!

**Comment by mtlewis** [comment]
@regicsolutions great suggestions, thanks for pointing it out. There's definitely more we can do with respect to support for improved validation errors in general, especially when it comes to fields that are validated via the `pattern` property. I'd love to explore in particular how we can provide a generalized implementation of `transformErrors` that allows providing a custom error message alongside the pattern itself in the schema.

For entity names specifically, I don't think using a pattern in the templates is the right solution. Entity names are always validated the same way in a given Backstage instance, so spreading the validation rules across all the templates creates unnecessary duplication. It also prevents us from reusing the catalog validation code itself when validating entity names.
