### ISSUE TITLE
Group tabs with IF condition are not changed with page change, but with browser refresh.

### ISSUE THREAD

**Issue by iammuho** [backstage/backstage#6699]
When I go from subgroup to parent group(or vise-versa), tabs are not disappeared or presented, but after browser refresh (simply f5) they change.

I've figured out tabs with IF condition only doesn't change, but rest is okay.

Example:
```
<EntityLayout.Route path="/jira" title="Jira" if={isJiraAvailable}>
      <EntityJiraOverviewCard />
    </EntityLayout.Route>
```

## Expected Behavior

Tabs should be adjusted depends on the entity and if conditions.

## Current Behavior

IF-conditioned tabs don't change.

## Steps to Reproduce

1. Add a group and subgroup
2. Install Jira plugin and tab to catalog entity page with IF condition be sure to sub group has JIRA annotation but not parent group.
3. Browse from sub-group to parent group (or wise-versa)

## Context

Without a hard refresh, tabs are not being valid for any group.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04):  docker node:14-buster-slim
- Browser Information:  docker node:14-buster-slim

**Comment by benjdlambert** [comment]
Right ok - Managed to replicate this, it's basically when navigating without the catching `EntityLayout.Route` handler changing, it doesn't respond to the entity changing so we never call the `if`'s again with the new entity. Will dig into a fix and try and get something up tonight!
