### ISSUE TITLE
Handle expiring/expired auth tokens from github

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#6710]
By default github times out github app user to server access tokens after 8 hours. This is not the case for Oauth apps. Backstage does not currently handle github access tokens that timeout and shows an alert "Bad credentials"

## Feature Suggestion
It would be fantastic if the github oauth feature was able to recognise that the token has expired and then renegotiate a new token with github.

## Possible Implementation
I havent looked into it in great detail, however the response from the token API contains an expiresAt field. It can be used to determine if a token is no longer valid.

## Context
By using a singe github app for frontend (user to server) and backend (server to server) auth, we reduce the complexity of configuration supporting backstage. There is simply one app to create in github that can be used for both. Enabling a security feature such as this (user to server token timeout) is desirable.

**Comment by Rugvip** [comment]
Most auth clients handle expiring tokens, and it's done through the [RefreshingAuthSessionManager](https://github.com/backstage/backstage/blob/71ca123f24c5aa74b84906454a6f5464dafc52cf/packages/core-app-api/src/lib/AuthSessionManager/RefreshingAuthSessionManager.ts#L42). The GitHub case is a bit tricky, as you have both this issue and the fact that permissions are handled completely differently with GitHub Apps.

To really tidy up things I think we need a bit of a rework of how auth works towards SCMs, but for now I'd be happy with any kind of solution to this tbh :grin:. I wonder if it's for example possible to just use the plain `OAuth2` implementation for GitHub apps and registering that as the implementation of the GitHub Auth API instead?
