### ISSUE TITLE
[Plugin] Add authentication token for SonarQube api calls

### ISSUE THREAD

**Issue by ssaraswati** [backstage/backstage#6718]
## Feature Suggestion

Add authentication token to SonarQube plugin calls to the backend api proxy.

## Possible Implementation

IdentityApi from @backstage/core-plugin-api is used in other plugins like Jenkins and Kubernetes to provide these tokens.

## Context

Attempting to use the SonarQube plugin with the authentication setup detailed in [backstage/contrib/docs/tutorials/authenticate-api-requests.md](https://github.com/backstage/backstage/blob/8b71ba6a90f71874e27e30204f28e7725b8dfa99/contrib/docs/tutorials/authenticate-api-requests.md) however it doesn't currently send an authentication token.

**Comment by jhaals** [comment]
Closed by #6719 🥇
