### ISSUE TITLE
"Launch" Search Beta Release

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#6720]
## What / Why

Lots of great stuff in #6569 and #6682 has effectively made production-ready search engines available.  These are still a little hidden from adopters, however, because they are not yet easily discoverable.

In order to "launch" the search beta, we need to make these things default / discoverable / clearly documented.

## Scope / UAT Target
- [x] As an App Integrator, my created app's SearchPage implementation should account for pagination (depends on #6062)
- [x] As an App Integrator, my created app should include the `DefaultTechDocsCollator` in the backend, and an updated Search Page frontend that includes the `techdocs` type (not directly related to the beta milestone, but we get questions about this often)
- [x] As an App Integrator, if I select `postgres` as my data store when running `create-app`, my Backstage search should default to using the `PgSearchEngine` implementation instead of `LunrSearchEngine`.

**Comment by Fox32** [comment]
Beside solving paging I would also throw in possible breaking changes around the collator, decorator and search engine design:

Right now the collator provides a list of all documents that should be indexed, which can be a big amount of memory. I would recommend to switch to a stream based API where the results are streamed from the collator to the decorators and then to the search engine. That way we only hold in memory what is really required.

**Comment by Fox32** [comment]
I could imaging a change like this: https://github.com/backstage/backstage/compare/master...SDA-SE:feat/experiment-search-redesign

If there are collators that can only return a full result they could still do it, if there are decorators that want to process all results at once they can keep doing it, and if a search engine want's to gather all results before submitting them it's still possible. But it's also possible to process documents in batches. However, this architecture might have an impact on performance, but should hold less data in memory at once.

**Comment by iamEAP** [comment]
Yeah, that makes a lot of sense, @Fox32!  Created #6734 to track.

What are your thoughts on a straight-up stream-based approach (where perhaps decorators would act like pipes) vs. AsyncGenerators as proposed?  I kind of naturally gravitate to the stream/pipe approach, but I have a weird history implementing data pipelines in node, so I don't actually know how idiomatic streams are.

**Comment by iamEAP** [comment]
Sooooo close.  Hang in there, stablebot.
