### ISSUE TITLE
Jenkins pluging ci/cd tab is not displaying build information

### ISSUE THREAD

**Issue by spasumalaithevan** [backstage/backstage#6725]
## Expected Behavior

Would like to see all build information in the CI/CD tab.

## Current Behavior

I see the Jenkins summary build (master) in the overview page. However ci/cd tab is not able to display other builds. See below exception in the logs. 

backstage error Cannot read property 'building' of null type=errorHandler stack=TypeError: Cannot read property 'building' of null
    at _JenkinsApiImpl.augmentProject (/app/node_modules/@backstage/plugin-jenkins-backend/dist/index.cjs.js:65:34)
    at _JenkinsApiImpl.getProjects (/app/node_modules/@backstage/plugin-jenkins-backend/dist/index.cjs.js:34:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/node_modules/@backstage/plugin-jenkins-backend/dist/index.cjs.js:196:22

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information: Chrome

**Comment by benjdlambert** [comment]
What version of the Jenkins plugin are you using?

**Comment by spasumalaithevan** [comment]
@benjdlambert  Thanks for looking into this. 
backstage/plugin-jenkins": "^0.5.0"
backstage/plugin-jenkins-backend": "^0.1.1"

**Comment by freben** [comment]
So it would seem that the `lastBuild` field was `null`.

https://github.com/backstage/backstage/blob/dc05aef9e73d78382cb79ae3da0565c6874eb3d1/plugins/jenkins-backend/src/service/jenkinsApi.ts?plain=1#L156

I don't have a Jenkins server to easily test against, so it would be great if you had the ability to debug this a bit on your end. Maybe you could attempt to make the corresponding API calls manually, or worst case even insert console.log statements directly in the built code of the Jenkins backend plugin in `node_modules`.

**Comment by JParisR** [comment]
I'm having the same problem, it only happens with some of the repositories though, and I can't see the difference between the ones that work well and the ones that don't.

I'm currently using this versions:
	backstage/plugin-jenkins": "^0.5.0
	backstage/plugin-jenkins-backend": "^0.1.2

**Comment by regicsolutions** [comment]
Also running into the same issue as well with the latest versions of both plugins

Noticed this in the browser console:
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-XXXXXXXXXXXXXXXXXXXX'), or a nonce ('nonce-...') is required to enable inline execution.

Also get the following error when trying to reach: http://localhost:7000/api/jenkins/v1/entity/default/Component/my-componentl/projects?branch=master

`{"error":{"name":"TypeError","message":"Cannot read property 'building' of null","level":"error","service":"backstage"},"request":{"method":"GET","url":"/v1/entity/default/Component/my-component/projects?branch=master"},"response":{"statusCode":500}}`

Also tried adding back `upgrade-insecure-requests: []` back to my app-config but and am still seeing the same error given i noticed this PR: (https://github.com/backstage/backstage/pull/5926/commits/fb815402ffd8b4d57778abc86a99212b22a95f7b

**Comment by GregoireW** [comment]
In jenkins, it is possible to enable build clean action ( globally or per job ) to remove old build. It is also possible when jenkins scan for branch / tags / PR  to set rule to prevent build on some case. It means some job are created, but there is no last build.

I put at the end of this message [1] an example of json jenkins-backend get from jenkins when calling the `/api/json?tree=jobs[actions[*]...` api.

The jenkins-backend plugin do not test for such case:  

https://github.com/backstage/backstage/blob/89c5ee5793956e1f8521a6d48432f6ad0275aa67/plugins/jenkins-backend/src/service/jenkinsApi.ts#L156

hence the error. 
To fix that, it is not a simple statement to add at this line, later on the process, lastBuild is also used.

https://github.com/backstage/backstage/blob/89c5ee5793956e1f8521a6d48432f6ad0275aa67/plugins/jenkins-backend/src/service/jenkinsApi.ts#L168

I hope the front will be ok if we sent nothing at lastBuild.


[1] : json file from jenkins API:  1st jobs has no `lastBuild`, 2nd job got one.

```json
{
  "_class": "org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject",
  "jobs": [
    {
      "_class": "org.jenkinsci.plugins.workflow.job.WorkflowJob",
      "actions": [
        {
          "_class": "hudson.plugins.jobConfigHistory.JobConfigHistoryProjectAction",
          "jobConfigHistory": [
            {}
          ]
        },
        {
          "_class": "jenkins.scm.api.metadata.ObjectMetadataAction",
          "objectDescription": null,
          "objectDisplayName": "01-11-2020-1",
          "objectUrl": "https://github.com/my-org/my-repo/tree/01-11-2020-1"
        },
        {
          "_class": "org.jenkinsci.plugins.displayurlapi.actions.JobDisplayAction",
          "displayUrl": "https://my.jenkins.net/blue/organizations/jenkins/my-folder%2Fmy-repo/"
        },
        {
          "_class": "com.cloudbees.plugins.credentials.ViewCredentialsAction",
          "stores": {}
        }
      ],
      "displayName": "01-11-2020-1",
      "fullDisplayName": "my-folder » my-repo » 01-11-2020-1",
      "fullName": "my-folder/my-repo/01-11-2020-1",
      "name": "01-11-2020-1",
      "inQueue": false,
      "lastBuild": null
    },
    {
      "_class": "org.jenkinsci.plugins.workflow.job.WorkflowJob",
      "actions": [
        {
          "_class": "hudson.plugins.jobConfigHistory.JobConfigHistoryProjectAction",
          "jobConfigHistory": [
          {}
          ]
        },
        {
          "_class": "jenkins.scm.api.metadata.ObjectMetadataAction",
          "objectDescription": null,
          "objectDisplayName": "1-1-0",
          "objectUrl": "https://github.com/my-org/my-repo/tree/1-1-0"
        },
        {
          "_class": "org.jenkinsci.plugins.displayurlapi.actions.JobDisplayAction",
          "displayUrl": "https://my.jenkins.net/blue/organizations/jenkins/my-folder%2Fmy-repo/"
        },
        {
          "_class": "com.cloudbees.plugins.credentials.ViewCredentialsAction",
          "stores": {}
        }
      ],
      "displayName": "1-1-0",
      "fullDisplayName": "my-folder » my-repo » 1-1-0",
      "fullName": "my-folder/my-repo/1-1-0",
      "name": "1-1-0",
      "inQueue": false,
      "lastBuild": {
        "_class": "org.jenkinsci.plugins.workflow.job.WorkflowRun",
        "actions": [
          {
            "_class": "hudson.model.CauseAction",
            "causes": [
              {
                "_class": "hudson.model.Cause$UserIdCause",
                "shortDescription": "Started by user xxxxx xxxxxx",
                "userId": "xxxxxxxx",
                "userName": "xxxxxx xxxxxxx"
              }
            ]
          },
          {
            "_class": "jenkins.metrics.impl.TimeInQueueAction",
            "blockedDurationMillis": 0,
            "blockedTimeMillis": 0,
            "buildableDurationMillis": 0,
            "buildableTimeMillis": 3,
            "buildingDurationMillis": 4636854,
            "executingTimeMillis": 4628236,
            "executorUtilization": 1,
            "queuingDurationMillis": 4,
            "queuingTimeMillis": 12,
            "subTaskCount": 1,
            "totalDurationMillis": 4636858,
            "waitingDurationMillis": 1,
            "waitingTimeMillis": 1
          }
        ],
        "building": false,
        "displayName": "#1",
        "duration": 4636854,
        "fullDisplayName": "my-folder » my-repo » 1-1-0 #1",
        "number": 1,
        "result": "SUCCESS",
        "timestamp": 1585310079433,
        "url": "https://my.jenkins.net/job/my-folder/job/my-repo/job/1-1-0/1/"
      }
    }
  ]
}
```
