### ISSUE TITLE
API definition text can't be fetched from a non-GitHub location

### ISSUE THREAD

**Issue by mx-foxtel** [backstage/backstage#6732]
I am trying to point the definition.$text location to a URL which is non GitHub but there is an error in fetching the openapi spec file from that link.
## Expected Behavior

Backstage should be able to fetch OpenAPI spec from the specified location.

## Current Behavior

There is an exception thrown
```
catalog warn Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location https://xxx-yyy-api.content.platform01.aaaa-platform-prod.com/api-doc/openapi.yaml, NotAllowedError: Reading from 'https://xxx-yyy-api.content.platform01.aaaa-platform-prod.com/api-doc/openapi.yaml' is not allowed type=plugin
```

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12): v14.17.3
- Operating System and Version (e.g. Ubuntu 14.04): MacOS 11.4
- Browser Information: Chrome

**Comment by Rugvip** [comment]
See #6735 and let me know if the improved error message helps :grin:

**Comment by mx-foxtel** [comment]
Much helpful. Thanks.

**Comment by mx-foxtel** [comment]
Issue resolved after setting
```
backend:
  reading:
      allow:
        - host: 'xxx-yyy-api.content.platform01.aaaa-platform-prod.com'
 ```
