### ISSUE TITLE
[Search] Improve memory efficiency of indexing process

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#6734]
## What / Why

The current `DocumentCollator` and `DocumentDecorator` interfaces expect an entire index's worth of data to live in-memory at index-time.  This makes sense with the out-of-the-box search engine (Lunr) because the index _itself_ lives in memory.  However, in even medium-sized Backstage instances, this can easily exhaust available resources.

We should update the interface so that collators and decorators do not need the entire index in-memory to operate, and then update any/all Search Engine index implementations to take advantage of this.

## Possible Implementation

- [AsyncGenerator](https://github.com/backstage/backstage/compare/master...SDA-SE:feat/experiment-search-redesign)
- Stream-based approach?

**Comment by freben** [comment]
Back linking to recent message from @althafh https://discord.com/channels/687207715902193673/903569385476747305/920188515483009056
