### ISSUE TITLE
Safari white screen affected from regular expressions of dist/static bundles when npx@backstage/create-app locally

### ISSUE THREAD

**Issue by arlindhoxhaa** [backstage/backstage#6743]
## Expected Behavior

Would like to see all the content of Backstage when opening it locally on Safari.

## Current Behavior

I see the white screen in Safari, but when actually trying to open the Backstage with another browser for example Google Chrome, then it's running perfectly.

<img width="1437" alt="Screen Shot 2021-08-06 at 4 05 28 PM" src="https://user-images.githubusercontent.com/39049202/128524213-9a2eb0ab-aea9-430f-8b49-696c7012fe66.png">

## Possible Solution

 Check used regular expressions which are causing this..
 https://caniuse.com/js-regexp-lookbehind

## Environment details

- npx/backstage/create-app
- NodeJS Version (v14):
- Operating System and Version (e.g. macOS Big Sur):
- Browser Information: Safari

**Comment by OrkoHunter** [comment]
Possibly related to https://github.com/backstage/backstage/issues/6039

**Comment by freben** [comment]
Thank you for reporting; this is indeed related to the other issue and I'll close in favor of that one to keep the discussion in one place.
