### ISSUE TITLE
catalog via github-discovery using a github app defaults to raw reading (unauthenticated)

### ISSUE THREAD

**Issue by mattops** [backstage/backstage#6746]
When using `github-discovery` type, and having a `github app` for credentials -  fetching the `catalog-info.yaml` files from each repo default to fetching via github raw (raw.githubusercontent.com) with no authentication.

This means `internal` or `private` repos do not work.  Similar issue noted here https://github.com/backstage/backstage/issues/1525 and fixed in https://github.com/backstage/backstage/pull/1560 ...but I wonder if this bug is related to using a `github app` instead of a `GITHUB_TOKEN`?

## Expected Behavior

 `github-discovery` should fetch the `catalog-info.yaml` files in each repository via the github API using authentication.

## Current Behavior

backstage successfully gets a complete list of repos and starts iterating over them, however it fetches each repo using raw github contents,  example log entry:

```
{"type":"plugin","plugin":"catalog","service":"backstage","entity":"location:default/generated-5a8887d861a79f609d66ec8c4ba365c72436ff67","level":"warn","message":"Unable to read url, NotFoundError: https://github.com/example-org/example-private-repo/blob/main/catalog-info.yaml could not be read as https://raw.githubusercontent.com/example-org/example-private-repo/main/catalog-info.yaml, 404 Not Found"}
```

**Comment by freben** [comment]
Hm. This one may be a bit complex.

The `GithubUrlReader` is responsible for the actual reading of data. For each URL to read, it [tries to translate that](https://github.com/backstage/backstage/blob/0c58dd73d0e98b7c08b5f770bbb30e3c1923e55f/packages/integration/src/github/core.ts?plain=1#L32) to the actual API or raw URL to use. it does so synchronously based on the config given - at that point it does not know whether the repo is private or not. You'll see at the bottom of the file that it'll prefer the raw path if it can, when there's no token given.

I'll look into whether we can leverage the `GithubCredentialsProvider` outside of this flow to use _that_ token onto the API path when possible.

**Comment by mattops** [comment]
is there any work around so we can get it to always go via the API route?

**Comment by freben** [comment]
Not really. See https://github.com/backstage/backstage/pull/6787 for a proposed fix!

**Comment by vschettino-asimov** [comment]
Is it possible we had a regression on this one? GitHub App Auth is working fine here (e.g. creating PRs for new projects) but fails to load an existing `catalog-info.yaml`:

```
NotFoundError: Unable to read url, NotFoundError: https://github.com/org/repo/tree/main/catalog-info.yaml could not be read as https://raw.githubusercontent.com/org/repo/main/catalog-info.yaml, 404 Not Found
```

I doubled checked the URL and the credentials as well.

**Comment by stephanschielke** [comment]
I ran into the same error and it took me a while to understand what I'm doing wrong, so I want to share that the `integration.github.token` configuration is used instead of the `auth.providers.github` configuration.

The catalog importer will use the `integration` config:
```
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
```
It will _not_ use the `auth.providers` configuration:
```
auth:
  providers:
    github:
      <env>:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
```

**Comment by lfialho** [comment]
Still getting same error after PR  6787 was merged
