### ISSUE TITLE
[Plugin] Drone.io plugin

### ISSUE THREAD

**Issue by Solisol** [backstage/backstage#675]
## Summary
We are using Drone.io as a build pipeline and for applying yaml configuration on Kubernetes. 
It would be nice to have something similar to [#667](https://github.com/spotify/backstage/issues/667) but for drone.io

## Project website (if applicable)
https://docs.drone.io/api/overview/

## Context
Bringing the CI into backstage will allow users to gather all they need in one place.

**Comment by kowsheek** [comment]
I'd be interested in helping on this. How deep of an integration do we envision the plugin? We could potentially start with it being a link out to the drone server or by embedding it.

**Comment by stefanalund** [comment]
Awesome, thanks! I’d suggest looking at the CircleCI plugin for inspiration https://github.com/spotify/backstage/tree/master/plugins/circleci

**Comment by adamdmharvey** [comment]
@kowsheek Is this still something you're looking into?  Wanted to just check in.  Thanks!!

**Comment by kowsheek** [comment]
Hey! We moved away from Drone to GitHub Actions so haven't been able to allocate time for this.

Maybe better for someone else to take over.

**Comment by OrkoHunter** [comment]
Re-opening since plugin suggestion issues are now exempt from [stalebot](https://github.com/backstage/backstage/blob/18f7345a6c29dcfccef7df081b1708f2bf8f62ff/.github/stale.yml#L9).

**Comment by Spedge** [comment]
Probably no longer relevant as Drone.io has been since purchased by Harness.io. 

https://siliconangle.com/2020/08/05/harness-buys-drone-io-automate-software-delivery/

Haven't seen anyone wanting a plugin for Harness, so I think you can probably close this and allow someone with a requirement for Harness.io to raise/lobby for it's addition.

**Comment by kowsheek** [comment]
Yeah, we've also since migrated to GitHub actions.

**Comment by freben** [comment]
Alright, thanks for calling that out!

**Comment by Spedge** [comment]
Haha, woot - first contribution to Backstage :smiley_cat:

**Comment by Spedge** [comment]
Hey @kowsheek - did you have any migration scripts or anything? Considering making the same move (Drone 0.8 to Actions)

**Comment by kowsheek** [comment]
We didn't have any scripts, The migration was pretty straightforward & painless after we did the first one, we did it manually for 6 packages I think.

**Comment by OrkoHunter** [comment]
For anyone that's coming to this issue after searching for the plugin - the Drone/Harness plugin is now available on the [marketplace](https://backstage.io/plugins). Checkout https://github.com/harness/backstage-plugins.
