### ISSUE TITLE
TechDocs Entity Sync broken by webpack5 upgrade

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#6752]
![webpack5](https://user-images.githubusercontent.com/3496491/128606303-e1ef007d-bdf8-472e-b186-c673dd8f7a91.gif)

## Steps to Reproduce

1. Pull the latest code from the master branch, `yarn install`, etc
2. Start up the app with all stock `app-config.yaml` values: `yarn dev`
3. Navigate to a TechDocs site

```
TypeError: (intermediate value)(intermediate value)(intermediate value).request is not a function
```

Error goes away when reverting to SHA `b319a924df7569cc2b667af7944cdaa3ed8d1b7f`, just prior to the Webpack 5 upgrade.

## Context

Seems to be triggered when instantiating `EventSource()` [in the TechDocs client](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/client.ts#L217).  Stack trace is:

```
TypeError: (intermediate value)(intermediate value)(intermediate value).request is not a function
    at connect (eventsource.js:139)
    at new EventSource (eventsource.js:253)
    at eval (client.ts:218)
    at new Promise (<anonymous>)
    at TechDocsStorageClient.syncEntityDocs (client.ts:216)
    at async eval (useReaderState.ts:289)
```

Seemingly because, `require('http')` within eventsource.js resolves `undefined`.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): MacOS 10.15
- Browser Information: Chrome 92

**Comment by iamEAP** [comment]
\cc @benjdlambert

**Comment by Rugvip** [comment]
How come `EventSource` is imported? Is this fixed by just using the built-in one?

**Comment by iamEAP** [comment]
Yeah, that does it.  Will require a little extra work to get the tests passing again.  Makes me think that was part of why it was imported in the first place.  Will take a look Monday unless someone else gets to it first!

**Comment by dhenneke** [comment]
> How come `EventSource` is imported? Is this fixed by just using the built-in one?

The built-in one lacks some features so I choose to use the library instead (see https://github.com/backstage/backstage/pull/6341#discussion_r666741815). But feel free to change that if it is problematic.

**Comment by Rugvip** [comment]
@dhenneke ah alright, thank you for the context. Perhaps we should try https://github.com/Yaffle/EventSource then? As it's a polyfill with header support that's built around XHR rather than the Node.js modules
