### ISSUE TITLE
Pass externalId along with the sts assume role for k8 plugin

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#6757]
AWS provide the ability to configure an External ID with a cross account role. It adds an extra layer of security for sharing cross account roles. Without the external ID, the role cannot be assumed.

## Feature Suggestion

It would be great if we could add a new optional setting, externalId, to the AWS/EKS authentication options in the kubernetes plugin. If it is set, the externalId is passed to the assume role call, in the kube plugin.

## Possible Implementation

#6747 

## Context

By adding the external ID we are adding an extra layer of security between the running backstage instance and the AWS role exposed to the backstage instance.

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

**Comment by freben** [comment]
Merged!
