### ISSUE TITLE
backstage-cli plugin:diff fails with `Error: No template file handler found for dev\index.tsx`

### ISSUE THREAD

**Issue by alzafacon** [backstage/backstage#6762]
## Expected Behavior

running yarn backstage-cli plugin:diff should make it through the entire plugin files.

## Current Behavior

diff fails on dev/index.tsx file and does not continue.

## Steps to Reproduce

1. clone backstage
2. yarn create-plugin
2. cd to the new plugin folder
3. yarn backstage-cli plugin:diff

## Context

I'm working on keeping our instance of backstage up to date with backstage but verifying plugin changes is not working anymore.

## Your Environment

- NodeJS Version (v12): 14
- Operating System and Version (e.g. Ubuntu 14.04): windows

**Comment by Rugvip** [comment]
Created #6850 as a fix. Wanna try it out to see that it's all good? :grin:

**Comment by alzafacon** [comment]
looks good! thanks
