### ISSUE TITLE
[Jenkins-plugin] Add an optional secondary branch to EntityLatestJenkinsRunCard

### ISSUE THREAD

**Issue by JParisR** [backstage/backstage#6771]
## Feature Suggestion
Add the option to have a secondary branch to be displayed in the `EntityLatestJenkinsRunCard` in case the first one doesn't exist. The idea here it's to solve the problem between the "main" and "master" branches.

## Possible Implementation
Two possible implementations:

- **First one:**
Add a second optional branch to the `EntityLatestJenkinsRunCard`: the plugin should be able to use the second branch when the first does not exist in the project.
It could be something like this:
```yaml
<EntityLatestJenkinsRunCard  branch="master" secondarybranch="main" />
```

- **Second one:**
Another solution could be the possibility of adding the default branch in the annotation itself:

```yaml
annotations:
    jenkins.io/github-folder: 'folder-name/project-name/default-branch'
```

## Context

Due to the renaming of the default GitHub branch there are some new repositories with the main branch by default and others with the master branch, which causes that in some cases the card cannot show the latest build.

**Comment by freben** [comment]
Could we make it so that if if no branch is given at all to `EntityLatestJenkinsRunCard`, it is smart enough to try both `master` and `main`? I feel that this would give the best end user experience with little implementation overhead

**Comment by JParisR** [comment]
Sure! that's probably the best approach to solve the problem
