### ISSUE TITLE
Allow users to refresh already registered locations in the catalog-import plugin

### ISSUE THREAD

**Issue by dhenneke** [backstage/backstage#6775]
## Feature Suggestion

We tell our users that they can simply register their location again to trigger a location update outside of the catalog refresh interval. Unfortunately, this isn't supported by the "next" catalog anymore.

![image](https://user-images.githubusercontent.com/720821/128883073-d3c2fcd1-392b-40cc-8ff2-44f3c3fbd2cb.png)

How about recognizing this special situation and provide a "refresh" button to the user:

![image](https://user-images.githubusercontent.com/720821/128883168-0bef8355-88a5-41df-8d9a-bab36deba7ae.png)

This is how this could look like in a video (based on [this experiment](https://github.com/backstage/backstage/compare/master...SDA-SE:feat/handle-import-conflict)):

https://user-images.githubusercontent.com/720821/128883103-e1fd8fda-db9f-4953-9d32-6a747ba31ea4.mov

## Possible Implementation

https://github.com/backstage/backstage/pull/6441 introduces an endpoint to trigger a location refresh via the API. If that would be merged, the catalog-import plugin could:

1. Catch the `ConflictError`.
2. Provide the Refresh Button.
3. On click, get the location id and call the refresh endpoint.
4. Go to the "summary" tab and view the refreshed entities

I'm open for suggestions of how to display this. An alternative could be to show a descriptive text and switch out the `Import` button with a `Refresh` button. Maybe in a different color to see that the action is different.

## Alternative Implementation

We could handle this case silently, so the user doesn't see that it was only refreshed instead of added. This is similar to how it was with the old catalog backend. With #6441 implemented, the catalog-import plugin could:

1. Catch the `ConflictError`
2. Get the location id and call the refresh endpoint.
3. Go to the "summary" tab and view the refreshed entities.

**Comment by freben** [comment]
Good call! Maybe there's value in being informed about the fact that it actually has been registered already. I'd prefer:

- an info box saying it already is registered
- a button to click to go to the entity (not refresh it)
- a button, always present, on the entity overview page that lets you initiate a refresh at any point in time, not just when registering

Note that the initial design for the refresh does NOT expect to be waiting for completion; it'll most likely just update a timestamp value and then arbitrarily far in the future some worker will get around to performing the update. Hopefully within fractions of a second - but in backed-up scenarios where there's a line of stuff waiting that have a timestamp far in the past but still haven't been processed, they will get their turn first.

**Comment by dhenneke** [comment]
> - a button to click to go to the entity (not refresh it)

When I refresh a location entity, would that that automatically refresh all downstream entities or do we need a kind of "bulk refresh" mode in the frontend to trigger such?

**Comment by freben** [comment]
The refresh function in the backend isn't built yet so it's open to discussion how to best shape that (ie who does what)

**Comment by freben** [comment]
Cross referencing: #6441

We are starting to look at this internally and hope to have something to share in the near future.
