### ISSUE TITLE
Gitlab-Actions

### ISSUE THREAD

**Issue by sjamidar** [backstage/backstage#6788]
Trying to create plugin which can perform CICD operations through gitlab. And we can utilize it on backstage portal.
If anyone owns such plugin already. let me know.

**Comment by freben** [comment]
Alright! Is this something you would like to try contributing yourself?

**Comment by satrox28** [comment]
We have recently published Gitlab Plugin for Backstage. We didn't enable to retry actions on it as there is no RBAC at this time so anyone will be able to rerun the pipeline. But if your team interested on it, sure we can work it.

**Comment by adamdmharvey** [comment]
There's another GitLab plugin published to the [Backstage Plugin marketplace](https://backstage.io/plugins) for GitLab as well:

https://github.com/immobiliare/backstage-plugin-gitlab

They look similar, but based on the name I can only assume they are two plugins that may do the same thing. (there are common contributors across them as well?  Do either of you know @Balasundaram @antoniomuso ?

However, based on both of these I think the original intent of this request has been satisfied by the community, so if it's OK, going to close this one.  🎉

**Comment by satrox28** [comment]
New plugin is fork of old one that's why you see common contributors.
