### ISSUE TITLE
Edit and Issue buttons in Tech-Docs don´t work correctly 

### ISSUE THREAD

**Issue by lukasgomez** [backstage/backstage#6789]
## Expected Behavior

Creating a correct `mkdocs.yml` file using the `edit_uri: edit/main/docs/` annotation should build a correct URI if you use the Edit button and the Issue button in a Tech-Doc template.

## Current Behavior

If you try to fix the annotation in the `mkdocs.yml` only the edit button works and the issue button builds the redirect URI incorrectly. And if you try to fix the  the issue button,  edit button stops working also.

## Steps to Reproduce

1. Create an mkdocs.yml
    
2. Build a correct mkdocs.yml
```
site_name: 'Backstage documentation'
repo_url: <YOUR_REPO_URL>
edit_uri: edit/main/docs/

plugins:
  - techdocs-core
  - search
  
markdown_extensions:
  - admonition
  
nav:
  - Home: index.md
  - Getting started:
    - Adding components: catalog-info.md
    - Adding APIs: apis.md
  - TechDocs:
    - Creating docs: documentation.md
    - Custom mkdocs: mkdocs.md
  - Tech-radar: tech-radar.md
  - Roadmap: roadmap.md
```

3. Go to your Backstage running instance
4. Go to the Docs tab
5. Try to use the edit and issue button of any template

## Context

This problem don´t let us edit the template from Backstage opening a new tab neither create an issue related with the template

**Comment by Fox32** [comment]
What SCM provider are you using? There is a recent PR that will make some changes here, not sure if that will help you #6773

**Comment by lukasgomez** [comment]
This problem has been solved in https://github.com/backstage/backstage/pull/6880
