### ISSUE TITLE
[RFC] Github Apps for Backend Authentication Browser Local Storage Risks

### ISSUE THREAD

**Issue by danludwig-happymoney** [backstage/backstage#6792]
**Status:** Open for comments

## Need

This is more of a question than anything, because I was unable to find any documentation around it.

While testing backstage with the GitHub Apps for Backend Authentication [as documented](https://backstage.io/docs/plugins/github-apps), we discovered that a github access token is created and put into local browser storage. That access token is then used to invoke the github api from the browser for many operations, such as loading pr data for the pull requests plugin, etc.

This means any successful XSS attack against a backstage deployment that uses this authentication mechanism would gain access to this user's github access token.

We need a better storage target for this github access token, one on the backend that is secured by a session cookie which isn't vulnerable to XSS and which we can mitigate against CSRF attacks. We're also open to alternative solutions which would protect the token from these kinds of attack vectors (XSS, CSRF).

Note that we have not yet tested backstage with a user login authentication provider. 

## Proposal

If there is already a way to configure backstage and/or the github apps auth provider to store access tokens in targets other than local browser storage, please point to existing documentation (or create it) that details how such a configuration can be achieved.

## Alternatives

No alternatives considered.

## Risks

Storing a token credential on the backend is only as safe as the credential that authenticates backend access from the frontend, and measures such as session cookies must be protected against their own class of attack vectors such as CSRF.

**Comment by Rugvip** [comment]
You may notice that the GitHub provider is the only one that does this, and tbh the GitHub OAuth app flow and its lack of refresh is a bit mind blowing. I'm figuring it was built for different purposes than how many OAuth apps are used today. 🤷 It is actually possible to wire up the GithubAuth API in the frontend so that it doesn't store the token in local storage by omitting the `StaticAuthSessionManager`, but that means users have to log in to GitHub a lot 😅

Imo the real way forward here is to move over to GitHub Apps instead, as they support expiring access tokens and refresh tokens, which we end up storing in http-only secure cookies.

When it comes to the overall auth architecture in Backstage it is optimized for keeping plugin development friction flow, and especially have the plugin backends decoupled from each other. Because of that we keep auth state client-side rather than in a session database or anything of that sort.

**Comment by danludwig-happymoney** [comment]
>It is actually possible to wire up the GithubAuth API in the frontend so that it doesn't store the token in local storage by omitting the StaticAuthSessionManager, but that means users have to log in to GitHub a lot 

That sounds like it could be an acceptable solution if it means covering it against XSS. How would one accomplish this? Can it be achieved from the app-config.yaml, or would we have to fork the github auth provider package and use a custom variation of it?

>Imo the real way forward here is to move over to GitHub Apps instead, as they support expiring access tokens and refresh tokens, which we end up storing in http-only secure cookies.

We do have the backstage github app set up at the organization level, and are referencing it from a github `integration` in the app-config.yaml, but tbh, I'm still not sure what it actually does. It seems that the things we have been using so far, which are importing existing components from github repos, and test driving the pull requests plugin from roadiehq, are using the gh auth provider with that browser local storage token.

I understand that keeping auth state client-side helps optimize for development friction, but these tokens are critical secrets and a stolen one could lead to disastrous consequences. Even with our best efforts to prevent successful XSS attacks, I don't feel good about letting backstage live in a production deployment with gh access tokens kept in browser local storage.

**Comment by danludwig-happymoney** [comment]
@Rugvip could you please address the followup questions I asked above? This is a pretty big barrier to adoption for us.

**Comment by Rugvip** [comment]
Leaving the storage out is a bit deeper customization so you'll have to do it through code. You replicate the [creation of the GithubAuth instance](https://github.com/backstage/backstage/blob/37e25f3b30632a1d12ccf56cc6a2050a2e2ed6ce/packages/core-app-api/src/apis/implementations/auth/github/GithubAuth.ts#L53) but leave out the `AuthSessionStore` (not the `StaticAuthSessionManager`, got that wrong in the previous comment 😅). Then you register that implementation as the implementation of the GithubAuth API in your app like [this](https://github.com/backstage/backstage/blob/37e25f3b30632a1d12ccf56cc6a2050a2e2ed6ce/packages/app/src/apis.ts#L44). There's a bit more info on working with APIs [in the docs](https://backstage.io/docs/api/utility-apis)

The GitHub Apps are currently primarily used for ingesting data in the backend, so for example reading `catalog-info.yaml` files from GitHub. If you dig around the codebase it's anything that uses the `GithubCredentialsProvider` that supports auth via GitHub Apps.
