### ISSUE TITLE
Scaffolder: Template action to create partial templates

### ISSUE THREAD

**Issue by Pike** [backstage/backstage#6794]
## Feature Suggestion

Right now, `fetch` comes with `plain` and `template` actions, and working on a template with GH actions and Django templates, I really felt the urge to have a mix between the two.

## Possible Implementation

My idea (and WIP patch) is to apply templating to files with a dedicated extension (`.njk` is suggested by nunjucks) to trigger content processing, and to do path processing at all times.

## Context

The idea is to have a single template with

* proper syntax and syntax highlighting for unmodified files
* proper syntax and syntax highlighting for modified files
* consistently adjusted paths for files and directories
* all in one template

**Comment by Rugvip** [comment]
I think templates are they are are heavily coupled between the template contents and the template declaration (yaml file). With that I think it could be reasonable to add ignore/include options for which files end up being templated? I can see that GitHub workflows are a bit of a pain to template.

Another workaround you can do right now is to split it into two separate directories and bring the workflows in with a plain fetch and then template the rest, but it's not entirely optimal.

Tbh I also don't think it's that big of a deal to have to escape a few things, so we shouldn't go out of our way to fix this imo 😅

**Comment by Pike** [comment]
It's been easy enough to just hack up an action. I have a patch and tests locally, I'll create a PR tomorrow.

One thing that's nice is that I didn't have to bother about cookiecutter compat, and it's problems around templating file names. Which I think is a cookiecutter bug to some extent, which I filed as https://github.com/cookiecutter/cookiecutter/issues/1588.
