### ISSUE TITLE
Implement readTree() in AWSUrlReader and Create New Catalog Processor

### ISSUE THREAD

**Issue by seant-splunk** [backstage/backstage#6795]
## Feature Suggestion

I want to implement the readTree() method and create a new catalog processor for the purposes of ingesting data from an S3 bucket using readTree() 

## Context

For the purpose of reading more than one .yaml file from an S3 Bucket to populate the service catalog

**Comment by freben** [comment]
Nice! Is it something you yourselves will be looking at (and might be assigned) or is it more of a feature ask?

**Comment by seant-splunk** [comment]
We would love to add this feature and be assigned to it!

**Comment by freben** [comment]
Awesome - done
