### ISSUE TITLE
Bug: It should be possible to use the SQLite database based on a file

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#6811]
## Feature Suggestion

The Backstage example app in this repository uses an in-memory SQLite database. This means that if the user changes the state of the database, and restarts the backend, all the changes disappear. This eventually becomes a source of confusion for Backstage contributors.

~~If the default SQLite connection were based on filesystem, instead of in-memory, the data will persist. And it will still be lightweight than PostgreSQL.~~

~~We already discourage the use of example app in production, hence this change does not increase the risk of people using SQLite in production.~~

It should be possible to switch the in-memory SQLite config to one that is based on a file.

## Possible Implementation

Discovering this PR https://github.com/backstage/backstage/pull/5308 from @Fox32,  looks like it's possible to update the app-config.yaml to

```yaml
backend:
  database:
    client: sqlite3
    connection:
      filename: 'backstage-db.sqlite'
```

and start using filesystem based SQLite connection!

But unfortunately this does not work for me and throws a "migrations directory is corrupt" error.

```
Backend failed to start up Error: The migration directory is corrupt, the following files are missing: 20200511113813_init.js, 20200520140700_location_update_log_table.js, 20200527114117_location_update_log_latest_view.js, 20200702153613_entities.js, 20200721115244_location_update_log_latest_deduplicate.js, 20200805163904_location_update_log_duplication_fix.js, 20200807120600_entitySearch.js, 20200809202832_add_bootstrap_location.js, 20200923104503_case_insensitivity.js, 20201005122705_add_entity_full_name.js, 20201006130744_entity_data_column.js, 20201006203131_entity_remove_redundant_columns.js, 20201007201501_index_entity_search.js, 20201019130742_add_relations_table.js, 20201123205611_relations_table_uniq.js, 20201210185851_fk_index.js, 20201230103504_update_log_varchar.js, 20210209121210_locations_fk_index.js, 20210302150147_refresh_state.js, 20210622104022_refresh_state_location_key.js
    at validateMigrationList (/Users/himanshum/workspace/github.com/backstage/backstage/node_modules/knex/lib/migrations/migrate/Migrator.js:575:11)
    at Migrator.latest (/Users/himanshum/workspace/github.com/backstage/backstage/node_modules/knex/lib/migrations/migrate/Migrator.js:70:7)
    at async Function.create (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/DatabaseTaskStore.ts:70:5)
    at async createRouter (webpack-internal:///../../plugins/scaffolder-backend/src/service/router.ts:95:29)
    at async createPlugin (webpack-internal:///./src/plugins/scaffolder.ts:46:10)
    at async main (webpack-internal:///./src/index.ts:121:32)
```

## Context

**Why the default should be in-memory SQLite database which does not persist across sessions?**

(I don't have any strong reasons here to be honest. Please comment!)

* A nudge for people to switch to PostgreSQL so that they don't accidentally deploy sqlite database.
* Speed?

**Why the default should be a file based sqlite database, which persists across sessions?**

1. No surprise loss of data for new Backstage integrators.

This has been a constant source of confusion on Discord for new people. Quoting @Pike here (in a call with @adamopenweb) - _I was told to use SQLite for my new Backstage app saying it's safe now and easy to switch later. I lost my populated catalog eventually - so it wasn't safe._

2. Authentication signing key gets lost, forcing user to sign out and sign in for token verification to work every time

While working with verifying a Backstage token in the backend, we found out that a signing key is created by the auth-backend plugin when the first user signs in and the key is stored in the database. After restarting the backend, the user is still logged in, but there is no signing key available in the database. This means the backstage token can no longer be verified without the user signing out and signing in again. This dramatically increases the debugging cycle.

**Comment by Fox32** [comment]
> But unfortunately this does not work for me and throws a "migrations directory is corrupt" error.

Actually I thought I fixed that 🤔

I think the problem is that all plugins are using the same database. It's important to specify a directory so that every plugin gets an own file. But I haven't used it for a long time, could be broken.

**Comment by Fox32** [comment]
On topic: it depends on what you are working on. If I'm trying out catalog ingestion, a fresh start is quite nice. To try out search indexing, a filled catalog is nice... 

But in the end it's easy to have a custom default locally.

**Comment by OrkoHunter** [comment]
@Fox32 A directory containing all the `.sqlite`s should be good enough. I tried setting the `backend.database.connection.database` as well, which looks like something which was written to address this use-case https://github.com/backstage/backstage/blob/ec62af1da511db555b459d58ef4e1daac4ca1118/packages/backend-common/src/database/connectors/sqlite3.ts#L89-L103

I found out that this omission of `database` key needs to be updated first, to not do that in case of `sqlite3`.
https://github.com/backstage/backstage/blob/ec62af1da511db555b459d58ef4e1daac4ca1118/packages/backend-common/src/database/DatabaseManager.ts#L157

Even then, the corrupt migrations directory issue does not go away. 😢 

> But in the end it's easy to have a custom default locally.

That would definitely be helpful. But I personally feel that non-persistent in-memory database feels more surprising than a file based sqlite db which you can delete to start afresh. I could be wrong though. 🙂

**Comment by Rugvip** [comment]
So we (discussed this in sync) want to keep in-memory DBs as the default, as it's really convenient for many development use-cases, and it doesn't pollute the repo. We do ofc want to fix the issues with the file-based approach tho :grin:

**Comment by OrkoHunter** [comment]
Makes sense to me @Rugvip - I'll re-purpose the issue!

I think we could save some people by adding just a warning log in backend saying that the database used is in-memory and will be cleaned when the backend starts.

**Comment by Fox32** [comment]
I think #5700 broke how sqlite databases are created. Look like sqlite means `:memory:` right now.

**Comment by sunshine69** [comment]
I hit that issue, strange that is it too hard to fix this? Running on memory is not really good for me.

**Comment by trankchung** [comment]
This works if I set `backend.database.connection.directory: /abs/path/to/sqlite/db/folder`.

**Comment by zentala** [comment]
It's enough to set:

``` yaml
  database:
    client: better-sqlite3
    connection:
      directory: "./db"
    useNullAsDefault: true
```

It will place the folder with `*.sqlite` files under `packages/backend/db`.
