### ISSUE TITLE
[Plugin] Argo CD

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#683]
## Summary

From the Argo CD [website](https://argoproj.github.io/argo-cd/):

> Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes.

This plugin should implement the same functionality as the default UI component provided by the project, shown in the architecture image taken from Argo's website:

![](https://argoproj.github.io/argo-cd/assets/argocd_architecture.png)

## Project website (if applicable)

https://argoproj.github.io/argo-cd/

## Context

Why build a Backstage plugin when there is already a UI for Argo CD? The benefit of having a plugin is that Argo's functionality can live together with other infrastructure tools, making it better integrated into the overall developer tooling around Kubernetes (see https://github.com/spotify/backstage/issues/632, https://github.com/spotify/backstage/issues/631 and https://github.com/spotify/backstage/issues/633).

**Comment by martina-if** [comment]
We started working on an [ArgoCD plugin](https://github.com/roadiehq/backstage-plugin-argo-cd) at Roadie!

We now have a working widget with information about the health and status of a service, check it out:

![argo3](https://user-images.githubusercontent.com/736631/100900318-03af0180-34c3-11eb-9cec-cd104f0b0ff3.png)

Feedback is very welcome!

**Comment by backjo** [comment]
@martina-if the Argo plugin looks awesome - would love to see it on NPM to make it more accessible!

A few thoughts:
- It'd be nice to have support for multiple ArgoCD instances. I know that some large organizations out there swimlane their ArgoCD instances by organization or environment - it'd be nice to be able to collect data from more than a single instance. 
- It'd be nice to be able to associate a catalog entity with an ArgoCD AppProject. One use case could be where a service has multiple environments grouped under a project - it'd be great just to link the project and automatically show the sync status/health of each environment.

**Comment by martina-if** [comment]
Thanks @backjo ! I opened some issues for those ideas :+1: [#1](https://github.com/RoadieHQ/backstage-plugin-argo-cd/issues/1) [#2](https://github.com/RoadieHQ/backstage-plugin-argo-cd/issues/2)

**Comment by adamdmharvey** [comment]
This plugin is live and has been for some time:

https://roadie.io/backstage/plugins/argo-cd/

I don't know if it aligns or matches the ask in this initial issue, but thinking this can be closed now? Any iterations could be additional stories/contribs to Roadie's plugin?

Thoughts?

![image](https://user-images.githubusercontent.com/33203301/105521438-e3711700-5ca9-11eb-8806-5a5cb0264511.png)
