### ISSUE TITLE
Custom templating in index.html

### ISSUE THREAD

**Issue by brethubbard** [backstage/backstage#6830]
## Feature Suggestion

Allow for custom templating in the `index.html` that is served by the app plugin.

## Possible Implementation

We could pass the rest of `app` config because extraneous fields are not removed.

## Context

I would like to be able to modify the `index.html` by conditionally adding certain script tags. Unfortunately, because of the limited variables passed to the `HtmlWebpackPlugin`, I am unable to do so.

**Comment by freben** [comment]
Hi! Is this because you want the file to be different between environments? For example having some features in staging but not in production.

**Comment by brethubbard** [comment]
In my case it's different in dev than deployed which is why I proposed the solution I did. It would be better, in my opinion, to make the templating more robust so it's not done at build time but realize that's a bigger ask.

**Comment by brethubbard** [comment]
After further consideration, I think the more robust solution is better to allow different scripts to be included per environment. To accommodate this I would like to avoid setting these value at build time. If I opened a PR to allow for a templating engine (e.g. ejs) in the `app-backend` to generate the `index.html` file rather than using `HtmlWebpackPlugin`, would that be considered?

**Comment by Rugvip** [comment]
A possible way forward here is to power up the `app-backend` plugin a bit and let it template the index file. That's be the most straightforward place and perhaps least hacky as well. It really wouldn't need any file rewrites or anything either, just a custom handler.

Other options if you want to do this in the deployment end are scripts similar to https://github.com/backstage/backstage/blob/557faeb7e1d1480ae6618ee4068079fec98fb85f/contrib/docker/frontend-with-nginx/docker/inject-config.sh#L5 or perhaps some other flavors of dynamic web servers.

**Comment by andrewthauer** [comment]
You could likely use something like https://www.npmjs.com/package/express-mung in the `app-backend` to help do this.
