### ISSUE TITLE
Pin Siderbar doesn't work.

### ISSUE THREAD

**Issue by SerenaIce** [backstage/backstage#6837]
After upgrading to **release-2021-7-29**, the Sider bar doesn't work

And after upgrading to the **latest version(release-2021-8-12)**, it still doesn't work. And not sure if it's caused by the Material-UI error:

![ui-error](https://user-images.githubusercontent.com/43363062/129531864-6cf41176-6eca-47ca-924d-04ad4bac03d7.PNG)

**Comment by SerenaIce** [comment]
I checked this problem which might not caused by the upgrading to any specific version. And I will keep diving into this issue. If anyone met the similar issue, please leave your comment.

**Comment by Yharooer** [comment]
I have met this issue when upgrading to version ^0.3.0. @SerenaIce please let me know if you found a way to resolve the issue.

**Comment by Rugvip** [comment]
This is most likely due to duplication of the `@backstage/core-components` package. We'll likely get this sorted out in the implementation but for now you can try to make sure you only have a single version installed, using yarn resolutions if needed.

**Comment by SerenaIce** [comment]
I've find the root cause: https://backstage.io/docs/tutorials/migrating-away-from-core. 
We still imported the @backstage/core, as the document says, we should leverage @backstage/core-app-api, @backstage/core-plugin-api, and @backstage/core-components instead of @backstage/core.

So that this issue can be solved.

@Yharooer , please check your code, if you have the same case.
