### ISSUE TITLE
Backstage Backend Fails to start due to database constraint error

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#6838]
The backend appears to be failing startup due to the following error

```
2021-08-16T09:02:00.081Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=true},bitbucket{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=true},fetch{}
Backend failed to start up ConflictError: Rejected due to a conflicting entity; caused by error: insert into "refresh_state" ("entity_id", "entity_ref", "errors", "last_discovery_at", "next_update_at", "unprocessed_entity") values ($1, $2, $3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, $4) - duplicate key value violates unique constraint "refresh_state_entity_ref_uniq"
    at DefaultProcessingDatabase.transaction (/usr/src/app/plugins/catalog-backend/dist/index.cjs.js:2717:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.applyMutation (/usr/src/app/plugins/catalog-backend/dist/index.cjs.js:2779:7)
```

## Expected Behavior
I think we would expect that the application would not cause a database constraint like this and/or continue the startup of the application regardless of the failure.

## Current Behavior
It fails with the error mentioned above.

## Possible Solution
I havent investigated this issue completely. But we are working on understanding it.

## Steps to Reproduce
I am not yet sure how to reproduce this issue.

## Context
TODO

## Your Environment
- NodeJS Version v14.17.0
- Operating System and Version (e.g. Ubuntu 14.04): Docker container built from node:14-buster-slim
- Browser Information: N/A

**Comment by Rugvip** [comment]
What version of the catalog backend plugin are you running? We added some conflict resolution logic some month ago, so you'll want to make sure it's less than a month old

**Comment by punkle** [comment]
I believe you are right. We are running a forked version 0.10.4 of the catalog-backend. We are updating shortly. It's very likely that we have not take a fix. Ill close this.

Thanks for your help. :)
