### ISSUE TITLE
feature: clickable URLs in log viewer

### ISSUE THREAD

**Issue by BernhardRode** [backstage/backstage#6841]
In Log views, it would be awesome to have clickable URLs.

## Feature Suggestion

If URLs are logged, people can open them without copy/pasting.

## Possible Implementation

Regex in LOG viewer to parse http/https urls.

**Comment by jhaals** [comment]
Hi @BernhardRode,
With 'log viewer' do you mean the scaffolder log output or someplace else in backstage?

**Comment by jhaals** [comment]
@BernhardRode I take your thumbsup that was spot on :) 
Would you be interested in looking into ways of implementing this feature?

**Comment by BernhardRode** [comment]
Maybe I will be able, but we are not there yet (enterprise and legal...).

First i wanted to know if this feature would be a good idea, at all.

**Comment by wdbetts** [comment]
A good reference implementation can be found in Gitlab log view introduced in [this MR](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/47532). Note that the regex to recognize links was refactored to this: 

```javascript
/**
 * capture anything starting with http:// or https://
 *   https?:\/\/
 *
 * up until a disallowed character or whitespace
 *   [^"<>()\\^`{|}\s]+
 *
 * and a disallowed character or whitespace, including non-ending chars .,:;!?
 *   [^"<>()\\^`{|}\s.,:;!?]
 */
export const linkRegex = /(https?:\/\/[^"<>()\\^`{|}\s]+[^"<>()\\^`{|}\s.,:;!?])/g;
```

[Gitlab JS license is MIT exapt btw](https://gitlab.com/gitlab-org/gitlab/-/blob/master/LICENSE#L8)

**Comment by freben** [comment]
@wdbetts oh thanks for digging that up, really helpful!

**Comment by WarlenRodrigues** [comment]
Hi, is this issue still open? May I start working on it?

**Comment by BernhardRode** [comment]
I already tracked the issue down. The feature needs to be implement in https://github.com/mozilla-frontend-infra/react-lazylog

I've also found a possible solution but still had no time to put it up on github (and open an issue over there).

**Comment by benjdlambert** [comment]
Does someone want to create at ticket on the upstream repo then?

**Comment by 97amarnathk** [comment]
@BernhardRode 
This sounds interesting and a low hanging fruit. I can pick this up

**Comment by skfarhat** [comment]
Should @BernhardRode be assigned this issue then? Could help people browsing `good first issue` labels  🙂

**Comment by BernhardRode** [comment]
The task is basically done... I did not get any responses from the people over at react-lazylog.

**Comment by skfarhat** [comment]
My point is: first time contributors might look at this issue and think they could take it because no Github `Assignee` is set. They would have to read all comments, then read the ones on the PR in `react-lazylog` to conclude that all is already done. 

Could save them some time. 

Thanks for taking the time to implement this of course 🙂

**Comment by Rugvip** [comment]
Ah, bit of a development here is that we no longer use `react-lazylog`, had to switch away from it due to license incompatibility. We now have our own implementation instead, over at https://github.com/backstage/backstage/tree/b1190bf6761294d31af074d21eef514591f2df38/packages/core-components/src/components/LogViewer.

**Comment by awanlin** [comment]
@Rugvip @benjdlambert can we re-open this? As far as my investigate has found the custom `LogViewer` does not have this feature. I'm also busy working on this now as this would be really helpful

**Comment by Rugvip** [comment]
@awanlin alright! 😁

**Comment by awanlin** [comment]
Thanks @Rugvip!

**Comment by awanlin** [comment]
Yay, got a PR that adds this: #17286
