### ISSUE TITLE
[TechDocs] Support MathJax

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#6873]
## Feature Suggestion

Support using MathJax syntax in TechDocs to render formulas, etc. 

## Possible Implementation

According to @emmaindal: "We have mathjax (or https://katex.org/ actually) support internally, but it has been a bit flaky so at one point we may add it in our core package, but not supported now"
## Context

This is currently not possible due to this [restriction](https://github.com/backstage/backstage/issues/4123#issuecomment-854097995)

**Comment by enerdgumen** [comment]
Just so you know, I have the same issue using the [Arithmatex](https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/) Markdown extension.

**Comment by kuangp** [comment]
still interested

**Comment by jmpicnic** [comment]
Still interested. Either this, or enable `svg` rendering to be able to use `mdx_math_svg`.

**Comment by cvsik** [comment]
Is there any way this feature could be enabled? We'd be really happy to use it, but not being able to have some sort of math rendering seems to be a bit of a blocker for us. Thanks a lot!

**Comment by dfl-aeb** [comment]
What works halfway is this mkdocs plugin:
https://pypi.org/project/markdown-katex/

Mkdocs output:
![image](https://github.com/user-attachments/assets/10f26e67-4828-47ea-bfde-587be5834e6b)

Techdocs output:
![image](https://github.com/user-attachments/assets/0ce4a897-4fd5-468d-8b0d-b430740c2720)


Maybe I can tweak it a bit to make it work properly.

**Comment by kunickiaj** [comment]
Still looking for a solution to this (particularly MathJax)
