### ISSUE TITLE
Github Integrations not refreshing user token

### ISSUE THREAD

**Issue by chandlj** [backstage/backstage#6877]
We are currently using the Github Integration using a Github App setup following this tutorial: <https://backstage.io/docs/plugins/github-apps>. The integration works, but after about a day API requests to the Github API for Github Actions and Pull Requests start throwing a `401` error. The error goes away and the integrations works as expected if you log out of Backstage and log back in.

## Expected Behavior

API requests to the Github API should continuously work without having to log out and log back in.

## Current Behavior

See summary.

## Possible Solution

My current hypothesis is that the user token for the app is not being refreshed. I saw somewhere that the token is cached in the browser, so maybe the cache isn't being updated?

## Steps to Reproduce

1. Setup Github Integration with Github Apps
2. Wait
3. Observe that the API no longer accepts requests using the current credentials
4. Log out of Backstage
5. Log back into Backstage
6. Observe that the integration works again

## Your Environment

This has been observed in multiple environments (both locally using the scaffolded Backstage app and our production deployment inside a k8s cluster) so I do not believe it is environment specific.

**Comment by jhaals** [comment]
Hi @chandlj,

Just to clarify that this the OAuth login flow for the user in the UI right? There's currently no support for refresh tokens as the traditional OAuth apps never expire so you can't refresh them. However the new Github apps support refresh tokens so we need to implement it in the backend. There's also a caveat that you can't request additional scopes in the user flow and are tied to those granted to the app itself. @Rugvip is looking into ways to detect this and handle it properly, the story continues... :)

**Comment by yafanasiev** [comment]
We have the same issue as well. We use separate OAuth integration for actual login, and have Github App set up for authenticating to the Github Actions plugin. We observe the same behaviour, and to fix the problem we have to log out from github and user profile and login again.
