### ISSUE TITLE
[plugin-api-docs] OpenAPI definition is broken for latest versions of backstage

### ISSUE THREAD

**Issue by manusant** [backstage/backstage#6878]
When opening the visual representation of an API component of type opeapi the "**ReferenceError: Buffer is not defined**" error is shown in the console and the swagger UI page isn't shown.

**This is also happening in a fresh project generated by the @backstage/cli": "^0.7.6".**

## Expected Behavior
No error is fired and Swagger UI is shown with the API definition

## Current Behavior
Currently this error is show in the console:
![Screenshot 2021-08-18 at 17 18 46](https://user-images.githubusercontent.com/12997676/129934639-5ab6b150-ca58-4b25-8685-3bf13f99ef43.png)

and this is shown in the UI:
![Screenshot 2021-08-18 at 17 19 00](https://user-images.githubusercontent.com/12997676/129934740-2b903281-e8ba-4c49-a3a7-2e119a728bc4.png)

## Possible Solution
Don't know.
Note: If i update the backstage repository and start the example app everything is working as expected. So i tried to allign all dependencies to match the ones in the example app but unfortunately i wasn't able to make it work.

## Steps to Reproduce

1. Use @backstage/cli version ^0.7.6 to generate a new project 
2. Start the project using _**yarn install && yarn tsc && yarn build && yarn dev**_
3. Wait until catalog entities are loaded
4. Navigate to **_/catalog/default/api/spotify/definition_** and the error appears

## Context
Fresh installation generate by @backstage/cli version ^0.7.6

## Your Environment

- MacOS Big Sur (Version 11.5.2)
- NodeJS Version (v14.17.3):
- Browser Information: Google Chrome

**Comment by timbonicus** [comment]
Thanks for reporting! This is fixed in #6810 set to release tomorrow.
