### ISSUE TITLE
Catalog : data quality checks and reporting

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#6885]
Some indication/status on catalog entities to mark the entities with dangling references (missing dependent entities/resources or missing teams for ownership) and missing recommended annotations.

## Feature Suggestion

The `catalog-info.yaml` is maintained by respetice owner of the entities, we see various level of data quality issues depending on the team's maturity. 

It would be great if such data quality checks can periodically run agains all of catalog entities and mark them against the respective entities, so that team can see and do the **self-corrective action**. Some of these checks can be added as linting rules (e.g. recommended annotations), others may need to do some external calls/catalog calls to validate the integrity of the catalog data (e.g. reporting dangling references).

## Possible Implementation

- Run offline jobs to validate entities and mark the status of validations against them in a single view/card.
- Ability to exclude some entities from validations.
- Allow the validation rules to be customizable, potentially with external integrations.

**Comment by jhaals** [comment]
Hi @kiranpatel11, 

It's probably hard to make some general plugin/feature that fits all organisations when it comes to data quality. 
All entities are periodically refreshed and what you could do to improve data quality in your organisation is to create a custom processor that validates the entity against your defined rules, adds annotations and does necessary actions depending on your exact needs and preferences.

**Comment by kiranpatel11** [comment]
@jhaals 

What I am hinting towards the platform capability which can facilitate such checks and visualization.

Some ideas:

- Catalog db schema extension may be require to associate the check status, comments, timestamp against the entity (much like a scorecard). 
- OR the scorecard can be a separate plugin with its own backend storage with `EntityRef`, `Check`, `Status`, `Remarks`, `TimeExecuted`, etc.
- How the scorecard is populated with different checks is upto the organization, the platform may include default checks such as dangling references upon ingestion/refresh.
- Check Validation Triggers: 
       1) **on ingestion/onchange** the custom processor would do for this scenario.
       2) **Scheduled triggers** are needed for validations which depends on external factors such as dangling references may get resolved when other team register the missing dependent entity, or entity relationships/resources defined in the catalog-info.yaml is outdated based on data being captured by the APM system.

**Comment by freben** [comment]
I think this can overlap with tech insights though! https://github.com/backstage/backstage/issues/2723 There's a lot of potentially interesting discussion in that issue.
