### ISSUE TITLE
[Home] StarredEntities homepage component

### ISSUE THREAD

**Issue by rubenLindstrom** [backstage/backstage#6906]
## Feature Suggestion
A homepage Component that renders a selection of starred entities. Could be ordered by recency of starring, or perhaps user defined.

## Context
For the new homepage as described in #5416 to be of use, there has to exist an ecosystem of components to be used for composing a homepage. This issue suggests the implementation of one such component.

**Comment by guillermomanzo** [comment]
perhaps we can take this? :) we have something similar in place
![image](https://user-images.githubusercontent.com/19312468/151290928-f49669d3-c094-46e7-86fa-9618b6da71bf.png)

**Comment by emmaindal** [comment]
Oh that definitely looks promising, is that something you want to contribute as a homepage component @guillermomanzo?

**Comment by emmaindal** [comment]
@katz95 did you have some designs ready similar to our internal version that you can share in this issue too?
