### ISSUE TITLE
Catalog: Noisy logging of NotFoundErrors for optional entries

### ISSUE THREAD

**Issue by sagacity** [backstage/backstage#6908]
## Expected Behavior

When discovering catalog entries in GitHub or GitLab, many discovered repositories may not actually contain a `catalog-info.yaml` file. This is okay, because these discovered entries are marked as `optional` by the discovery processors.

I would expect these missing `catalog-info.yaml` files to not cause any warnings in the logs, since we expect plenty of repositories to not contain these files, and they're optional, after all.

## Current Behavior

Every optional catalog entry url that is not found throws a `NotFoundError` which is logged as a warning. This results in a lot of `warn` logs every refresh interval.

## Possible Solution

Log `NotFoundError` at a lower level (i.e. `debug`) for optional entries.

**Comment by ChloeTigre** [comment]
yo @sagacity 
Please use `https://gitlab.com/<myorg>/blob/*/**/catalog-info.yaml` as your catalog locations target for gitlab-discovery. It will work better.

**Comment by Rugvip** [comment]
This was fixed by https://github.com/backstage/backstage/pull/8343
