### ISSUE TITLE
[Plugin] Nomad

### ISSUE THREAD

**Issue by juliosueiras** [backstage/backstage#691]
## Summary

A Nomad Plugin for managing(full lifecycle) its tasks

## Project website (if applicable)

https://nomadproject.io

**Comment by BenjaminToth** [comment]
Any news about that ? Exists plan to implement ?

**Comment by Maetis** [comment]
How this plugin should work?

**Comment by Oloremo** [comment]
Same idea as Backstage k8s plugin?

**Comment by jjtimmons** [comment]
I'm trying (on the side) to make this over in https://github.com/backstage/backstage/pull/18010

It would help if folks clarified how much of Nomad's functionality they'd want within a Nomad tab. My thought right now is that each entry has:
- deployments
- allocations

And entities are tied to Nomad jobs/groups with annotations that are regex matches like:
```
  annotations:
    nomad.io/job: redis
    nomad.io/group: 'redis|redis-sidecar'
```

Either job or group can be specified, they'd wind up being passed to filters: https://developer.hashicorp.com/nomad/api-docs#filtering
