### ISSUE TITLE
Upgrade to React 17

### ISSUE THREAD

**Issue by grantila** [backstage/backstage#6910]
Currently, all backstage packages depend on React 16. React 17 has been stable for quite a while now, and provides better handling of multiple React versions running concurrently. Eventually using the new jsx factory would be great, but let this issue be only about bumping everything to 17.

Since this is a breaking change, it should be done in a breaking version bump.

I'm not 100% sure of what else will be needed for this, but at least `react` and `react-dom` need to be upgraded together.

On current master it's mostly 16.13.1, but a few other have sneaked in:

```
❯ rg --files -g package.json | xargs jq '.dependencies.react' | grep -v null | sort | uniq -c | sort -rn
  43 "^16.13.1"
   8 "^16.12.0"
   1 "^17.0.2"
   1 "^16.8.5"
   1 "^16.0.0"
```

When testing locally, I found that pinning `react` and `react-dom` to `17.0.2` and `@hot-loader/react-dom` to `17.0.1` works. Haven't done any thorough testing, but the UI loads and navigation works fine from what I can see.

Do we know of any other blocking issues before bumping?

**Comment by grantila** [comment]
`@material-ui/lab@4...` should probably be bumped to 5 for React 17 compatibility (on paper anyway)

**Comment by ellisio** [comment]
We have added the following to our root `package.json` `resolutions` block:

```
"@types/react": "^17.0.20",
"@types/react-dom": "^17.0.9",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-use": "^17.3.1"
```

@Rugvip suggested [this in Discord](https://discord.com/channels/687207715902193673/687235481154617364/884843913670692874). Since our user base is small right now, we're willing to be the sacrificial lamb to testing React 17. Our setup is not complex, but it should help give some insight on anything that might break from a simple setup.

So far we can confirm that the application builds and deploys successfully.

**Comment by ellisio** [comment]
@Rugvip Quick update: `@material-ui/*` is going to the major battle here. React installs fine, but issues start popping up like crazy once you attempt to load the app. It all comes back to using v4 of those packages.

[v5 was supposed to ship on September 1, 2021](https://material-ui.com/versions/#release-schedule), but it does not appear that they are there, yet. It looks like it got bumped to September 15th [here](https://github.com/mui-org/material-ui/milestone/44).

Once v5 is released, I could start a PR to work on this. However, I don't want to make any promises as I would have to do this in my spare time between work and kids. :(

**Comment by Rugvip** [comment]
@ellisio no pressure, any help is appreciated, and thank you for checking it out this far! 👍

So MUI v5 migration is another thing on the menu and we'll definitely want to be a bit late and careful with that one. Rolling that out in a smooth way will be a challenge. I'd say the best case there being that we can let people do it at their own pace as much as possible. Gonna create another issue for that one so we can keep this one focused on React v17

**Comment by webark** [comment]
If these two issues are going to be closed, is there any tracking issue or a rough timeline (like 2022 or 2023) when these will be picked up?

**Comment by Rugvip** [comment]
I'd actually love to gather some more feedback on how React 17 works for people. Basically trying out the following resolutions added to the root `package.json` and seeing how well it works:

```json
"resolutions": {
  "react": "^17",
  "react-dom": "^17",
  "@hot-loader/react-dom": "^17",
  "@types/react": "^17",
  "@types/react-dom": "^17",
}
```

If the types turn out to cause issues those two resolutions could be dropped.

With the above resolutions in place, how well do things work? Does the dev server work, production builds, hot reloads, type checking, and tests?

Tried it out in the main repo and it seems to work fine, but would like some more insight before we begin recommending migration.

When it comes to us moving our packages over to React 17, I imagine that might be more of a `^16 || ^17` thing

**Comment by ellisio** [comment]
@Rugvip I haven't looked at this in a while now, work priorities are destroying my free time for cool things. However, when I did set resolutions like this I had many errors on the frontend with MUI.
