### ISSUE TITLE
Rendering html in readme.md in github-insights plugin

### ISSUE THREAD

**Issue by kcheriyath** [backstage/backstage#6913]
## Feature Suggestion

_Adding this issue as a feature request as this capability likely was not in scope for the plugin_

Enhance Github insights plugin readme widget to render html markups. Readme containing html styling in github allow-lists are rendered to spec so  `<table>...</table>` will be displayed as a table.

## Current Behaviour

HTML mark-up in readme is rendered as code like below

![image](https://user-images.githubusercontent.com/14891259/130259206-3ca2923b-cf2c-4139-a1ab-b952c3830361.png)

## Steps to Reproduce

1. Add an html table into readme.md
```
<table>
<tbody>
  <tr>
    <td>1</td><td>2</td>
  </tr>
  <tr>
    <td>3</td><td>4</td>
  </tr>
</tbody>
</table>
```

2. View readme through github (renders fine).
3. View readme from backstage (renders raw html).

## Context

Trying to add repos with https://allcontributors.org/ spec. All-contributors bot generates a contributors table in html format like here https://github.com/all-contributors/all-contributors. The html portions of this readme is not rendered correctly in backstage UI.

**Comment by jhaals** [comment]
Hi @kcheriyath!

The plugin is actually hosted in a different organisation. Please open your issue against https://github.com/RoadieHQ/roadie-backstage-plugins
