### ISSUE TITLE
Splunk On Call Plugin: Update portal link in card to go to team specific page

### ISSUE THREAD

**Issue by heatheralee** [backstage/backstage#6914]
## Feature Suggestion

Currently, the Portal link for the Splunk On Call EntitySplunkOnCallCard goes to "https://portal.victorops.com/". We would like to update this to point to a team specific page.

## Possible Implementation

**Implementation 1:**
Update [EntitySplunkOnCallCard](https://github.com/backstage/backstage/blob/master/plugins/splunk-on-call/src/components/EntitySplunkOnCallCard.tsx#L169) to get the `slug` for the team API response. Then construct a link like:
```
portalLink = `${portalLink}dash/${socInstance}#/team/${teamSlug}`;
```
where `socInstance` is populated by app-config.yaml.

**Implementation 2:**
Add a new annotation that corresponds to the team specific URL, and have the Portal link go to the URL stored in the annotation.

## Context

We are trying to provide the user with a bit more context rather than sending them straight to the portal homepage. I am open to pushing this contribution upstream.

Thanks in advance!

**Comment by heatheralee** [comment]
Hi @freben! Yes, this is. I'll take a look at creating an MR. Thanks! 😸

**Comment by freben** [comment]
Nice, assigned!
