### ISSUE TITLE
Azure DevOps catalog-info import not working

### ISSUE THREAD

**Issue by defaultbr** [backstage/backstage#6916]
## Expected Behavior

Loading the catalog-info and registering it from azure devops

## Current Behavior

Azure DevOps url for importing `.yaml` is not working anymore since latest release

the change that made it stopping to work: https://github.com/backstage/backstage/commit/ced85b598e92416ff78d4efc0906f6532f091d34#diff-623b82a44180c2915cf566959ddebee1b33c1ad1d1df683bd94904fa5ab31564R56

For azure file path, we should check the searchParams for the key `path` and not only the `URL(url).pathname`

## Possible Solution

File and line to edit: https://github.com/backstage/backstage/blob/56139cfd1eb39ca0b35655af83054729f7dbf550/plugins/catalog-import/src/api/CatalogImportClient.ts#L56

Return to the old format to check the url -> `url.match(/\.ya?ml$/)`  or add a `or` validation to check if searchParams has a key for path and the value:

>  if (new URL(url).pathname.match(/\.ya?ml$/) || new URL(url).searchParams.get("path")?.match(/\.ya?ml$/)) {

![image](https://user-images.githubusercontent.com/5432351/130295916-4e44620d-3600-4941-9306-721f212ef229.png)
I'm pretty sure that there is another way to do it more elegantly

## Steps to Reproduce

Update to the latest backstage and try to import any catalog-info from azure devops

![error-backstage](https://user-images.githubusercontent.com/5432351/130292394-d6673c31-7acc-4ee5-b540-3604d98af4fb.jpg)

**Comment by defaultbr** [comment]
I've sent a PR -> https://github.com/backstage/backstage/pull/6926

**Comment by jhaals** [comment]
Fixed by #6926, thank you!
