### ISSUE TITLE
[Plugin] Vault

### ISSUE THREAD

**Issue by juliosueiras** [backstage/backstage#692]
## Summary

A Plugin to allow display and management of Vault secrets and its roles

## Project website (if applicable)

https://vaultproject.io/

**Comment by timchepeleff** [comment]
I'm happy to claim this one.

**Comment by soapraj** [comment]
@timchepeleff assigned to you!

**Comment by bnaganathan** [comment]
Hello,
We are planning to use backstage in our organization for setting up a developer portal. We also have an enterprise Hashicorp vault setup. I see that you are working on developing a vault plugin for backstage. I wanted to explain to you about our vault setup and the use-cases which we expect the backstage vault plugin to take care of. I also would like to understand the architecture/design of the plugin, provide inputs and contribute if possible, for this purpose. Can we have a call regarding this? 

Thanks,
Bala

**Comment by stefanalund** [comment]
@timchepeleff are you still working on this?

**Comment by timchepeleff** [comment]
@bnaganathan - 

I'd love to chat. Just getting back from a short holiday so I apologize for the slow response here. 

@stefanalund - 

Still chugging along!

**Comment by dtuite** [comment]
@bnaganathan @timchepeleff Could you include me in the conversation too please? We're not using Vault yet but it's likely that we will in the near future and I'd love to hear how you're going to use it with Backstage.

**Comment by bnaganathan** [comment]
> @bnaganathan -
> 
> I'd love to chat. Just getting back from a short holiday so I apologize for the slow response here. Feel free to send me an email (on my GH profile) - there are a few other folks that have reached out I'd like to include in the conversation as well.
> 
> @stefanalund -
> 
> Still chugging along!

@timchepeleff No Problem. Thank you for your time. I have also added few other people to the meeting.

**Comment by bnaganathan** [comment]
> @bnaganathan @timchepeleff Could you include me in the conversation too please? We're not using Vault yet but it's likely that we will in the near future and I'd love to hear how you're going to use it with Backstage.

@dtuite  I have forwarded the meeting invite to your email - david@roadie.io.

**Comment by timchepeleff** [comment]
Syncing back up with notes on the discussion.

Current plan is to create a CRUD plugin that enables developers to manage their services secrets within Backstage, rough plan is as follows: 
- Start by creating a simple UI that can display a list of secrets associated with a service (based off of a Vault Namespace/Keyspace). Read only to start.
- Create a proxy backend that attaches a vault `token` to any API requests to prevent it from being compromised. 
- Explore ways to "add" / "persist" team/user specific tokens to open up access to the Create, Update, Delete functionality of the plugin. This isn't mandatory for development of the Create, Update, Delete, but will likely be mandatory 
- (Maybe?) Extend the service catalogue to support dynamic vault paths so various different secret structures are supported and configurable. 

bnaganathan / @dtuite totally add some color/notes when you have a chance.

**Comment by freben** [comment]
👍 it'll be interesting to see what ways there are to authenticate toward vault and how we wire that up with the current backstage user.

**Comment by OrkoHunter** [comment]
Re-opening since plugin suggestion issues are now exempt from [stalebot](https://github.com/backstage/backstage/blob/18f7345a6c29dcfccef7df081b1708f2bf8f62ff/.github/stale.yml#L9).

**Comment by iiro** [comment]
This is definitely an interesting idea as it'd again let the devs utilize Vault without knowing anything about it - using the same Backstage UI like with everything else.

Does anyone know what's the current progress on this...?

**Comment by freben** [comment]
@ivangonzalezacuna If you start on it, let us know and we can assign you to the issue.

**Comment by ivangonzalezacuna** [comment]
> @ivangonzalezacuna If you start on it, let us know and we can assign you to the issue.

I'm already working on it. I'm starting with a basic listing functionality, so Backstage will only need a LIST permission token in vault, making it more secure for now.

I need to add some documentation and probably a token-refresh functionality as well, or a way to implement it by the user if it's needed (in our company we will need that, as the token will expire after 24h)

**Comment by cthtrifork** [comment]
I keep getting `No implementation available for apiRef{plugin.vault.service}` in the frontend. Any ideas? running backstage 1.4

**Comment by jhaals** [comment]
@cthtrifork sorry to hear that you're having issues, would you be able to open a dedicated issue for this problem with this information alongside how the plugin is installed.
I'm going to close this issue as the Vault plugin is live 🚀
