### ISSUE TITLE
[scaffolder] Expose formData to fields

### ISSUE THREAD

**Issue by Pike** [backstage/backstage#6935]
Right now, the complete `formData` isn't accessible to field implementations.

## Feature Suggestion

Expose `formData` to fields to allow context dependent behavior. I've been thinking about both defaults and validation, but if #6932 is about scaffolder, it could also be used to populate options dynamically.

## Possible Implementation

Create a React context for `formData` and expose it to fields. Maybe even together with a `setFormData` entry point to change status.

## Context

I would like to create repository name defaults based on metadata for the created project, and validate some constraints while still being able to adjust the name manually.

Having a `setFormData` could allow a field to add computed values, which could be helpful for actions. I'm also seeing a lot of opportunity for shooting yourself in the foot here, though.

**Comment by Pike** [comment]
I'd be happy to take a look at this, but I'd like to get some feedback on the proposal first. And possibly an example to follow. I think I found at least two different ways on where to put the code that exposes a context on a plugin api.

**Comment by benjdlambert** [comment]
Like @freben says, it feels a little unfortunate to have these invisible dependencies between fields, I wonder if it's possible to have a Custom Field Extension that can render multiple input fields and track the state between them in that component instead? Does that work for you use case @pike?

**Comment by Pike** [comment]
TBH, I've tabled this as "not part of the demo". In the end, if we write a frontend for a scaffolder, it'll be the same kinda work independent of scaffolder-backend or not. If a mostly-full-page field is engineering-wise and ux-wise a good option would be for another day. Surely an option to look at, though.
