### ISSUE TITLE
Get an error with using ItemCardHeader

### ISSUE THREAD

**Issue by SerenaIce** [backstage/backstage#6936]
Get an error with using ItemCardHeader when updating the @backstage/core-components to version ^0.3.2 and also update all the related packages to the latest. Please refer to the error below:

![image](https://user-images.githubusercontent.com/43363062/130619547-3edbfb2b-1fd3-4fcb-afc8-92057c38d163.png)

Upgrade to the latest version of Backstage: release-8-20
And
 "@backstage/catalog-model": "^0.9.0",
    "@backstage/core-components": "^0.3.2",
    "@backstage/core-plugin-api": "^0.1.6",
    "@backstage/errors": "^0.1.1",
    "@backstage/plugin-catalog-react": "^0.4.3",
    "@backstage/theme": "^0.2.10",
    "@material-ui/core": "^4.12.2",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "4.0.0-alpha.45",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-use": "^17.2.4"

     "@backstage/cli": "0.7.9",
    "@backstage/core-app-api": "^0.1.9",
    "@backstage/integration-react": "^0.1.7",
    "@backstage/plugin-api-docs": "^0.6.6",
    "@backstage/plugin-catalog": "^0.6.12",
    "@backstage/plugin-catalog-import": "^0.5.18",
    "@backstage/plugin-explore": "^0.3.13",
    "@backstage/plugin-org": "^0.3.19",
    "@backstage/plugin-scaffolder": "^0.11.1",

**Comment by SerenaIce** [comment]
The only difference I can tell is in Backstage the '@hot-loader/react-dom' module version shows 16.13.0+4.12.20, but in my source code the module version generated shows 16.14.0+4.13.0. However, it's weird that we both using the backstage/cli@0.7.9 and the '@hot-loader/react-dom' should be handled by backstage/cli.

**Comment by joeporpeglia** [comment]
Looks like your theme doesn't include `palette.bursts.gradient`, which was added in #6780. This might be a result of using a custom theme, but could also happen if an older version of `@backstage/theme` is installed (`< 0.2.10`). `yarn why @backstage/theme` will show all of the versions you have installed.

**Comment by SerenaIce** [comment]
Thanks, @joeporpeglia. This issue was solved. It's caused by the gradient. We override the theme,  so after the upgrade, we need to add the 
 gradient: {
        linear: 'xxxxxx',
   },
to our customized configuration.
