### ISSUE TITLE
Changes to support extra App Origins breaks existing implementations

### ISSUE THREAD

**Issue by JP-Dhabolt** [backstage/backstage#6939]
https://github.com/backstage/backstage/blob/5722fb788287849e0b4b2230c3d1db52b7b3df0a/plugins/auth-backend/src/lib/oauth/OAuthAdapter.ts#L119-L128

Given that the `OAuthState` has an optional `origin`, when it goes through the serialization process, it ends up with the string literal `undefined`.  The string `'undefined'` makes it through the `if(state.origin)` check, but throws an exception on the `new URL(state.origin)`, as `'undefined'` string literal is not a valid URL.  This results in a failure to log in with the `App origin is invalid, failed to parse` error message.

A potential fix would be to update the conditional check:

```ts
if (state.origin || state.origin === 'undefined') {
  // existing logic
}

```

I have been able to work around this issue because we use a custom `OAuthHandler`, so I am modifying the request state to include the origin (pulled from the config) before performing the OAuth redirect, however this does not help anybody using the built-in `oidc` or any other provider where the origin is not set.

**Comment by Rugvip** [comment]
Thank you for reporting! Working on a fix
