### ISSUE TITLE
List catelogs owned by my team

### ISSUE THREAD

**Issue by Jerry4013** [backstage/backstage#6957]
In the home page/catelog page, there is a button called "Owned", which lists all the catalogs that belongs to the current login user. However, in most cases, a repo is owned by a team in a company, instead of a single person.

## Feature Suggestion

We hope that there is a button like owned by my team, which will display all the entities owned by my team. Thanks!

**Comment by freben** [comment]
The meaning of "ownership" is actually configurable by your company. The `auth` backend responds with a token that contains claims about what you are owning stuff through - if that claim contains both your user and your team, then the Owned filter will show entities marked as owned by either of those two.

This is a good place to start for some background: https://github.com/backstage/backstage/issues/4089

This is a ticket tracking the introduction of more sign in resolvers: https://github.com/backstage/backstage/issues/6245

In the mean time, there's a compatibility mode in place where if you have a User in the catalog with your username, which is a member of a Group in the catalog, then ownership works through that too.

Closing as "fixed" so to speak, let us know if we can clarify more.
