### ISSUE TITLE
Public Backstage Backstage Deployment

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#697]
## Feature Suggestion

We should have a public Backstage app deployed for managing this project. Use cases would be exploring available plugins, overseeing PR deployments and GitHub workflows, providing an auth backend for development, and simply trying out some plugins, and more.

## Possible Implementation

We may want to deploy this outside of Spotify infra so that we can have more direct dogfooding of public plugins for .e.g k8s.

## Context

Dogfooding at it's finest 👌. But it should also be useful as a showcase and for people contributing to the project.

**Comment by stefanalund** [comment]
demo.backstage.io

**Comment by Rugvip** [comment]
backstage.backstage.io 🤯

**Comment by Rugvip** [comment]
An alternative/addition to this would be to have an internal deployment too, then we could try out managing a larger number of services.

**Comment by dtuite** [comment]
If you're open to having an outsider do this, I would like to fund and manage this. 

I can deploy a public Backstage on an EC2 instance to get started but I agree a k8s deployment would be better long term. I [already have a docker-compose script](https://upstage.dev/blog/backstage-docker-compose/) which stands the whole thing up so that people can use the lighthouse plugin.

I can also set a refresh schedule to periodically pull from master and rebuild as desired.

**Comment by Rugvip** [comment]
@dtuite I don't think we're opposed to it, but I do feel that it would be good for us to manage a deployment of Backstage ourselves. Just so that we get to feel all the pain points of the deployment process and iron those out.

That said I don't see much trouble with having more deployments :grin:. What do you think @stefanalund?

**Comment by Rugvip** [comment]
It's also tied to authentication btw, we'll likely use the public deployment as the default auth backend for local development.

**Comment by dtuite** [comment]
@Rugvip  We might be thinking of two different things. 

In my head, a useful Backstage demo can be used by anyone. I'm imagining a flow where I come to the Backstage website knowing nothing about Backstage, I click a link to the Demo, I can sign up (or even better - I don't have to sign up) and  I can view/edit dummy data freely so I can get a sense of the product before I go and install it myself.

I understand now that what you're suggesting is different.

**Comment by adamdmharvey** [comment]
Think this might be able to be closed, @OrkoHunter ?

https://demo.backstage.io now exists, and is and can continue to be upgraded.

**Comment by OrkoHunter** [comment]
Yes I think it can be closed. Thanks looking into old issues!
