### ISSUE TITLE
Plugin failed to compile in Backstage App but compiles standalone

### ISSUE THREAD

**Issue by seizadi** [backstage/backstage#6975]
I created a plugin using backstage-cli

## Expected Behavior
I should be able to create a npm module and include it in the backstage app

## Current Behavior
The plugin standalone project compiles
```bash
❯ yarn tsc
yarn run v1.22.5
$ /Users/seizadi/projects/go-projects/src/github.com/seizadi/plugin-cost-insights-backend/node_modules/.bin/tsc
✨  Done in 6.17s.
```

It fails when I add it to my backstage app and run build:
```bash
'ERROR in /Users/seizadi/projects/go-projects/src/github.com/seizadi/backstage-helm/node_modules/plugin-cost-insights-backend/src/api.ts 13:14
Module parse failed: Unexpected token (13:14)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export class FetchError extends Error {
>     get name(): string {
|         return this.constructor.name;
|     }
ℹ ｢wdm｣: Failed to compile.
'
```

## Possible Solution
I added a tsconfig.json to my plugin project but it did not change the behavior.

I am running the plugin as @internal from plugins directory

## Steps to Reproduce

I created the app using
```bash
npx @backstage/create-app
```
Added cost-insight-plugin, following these 
[directions](https://github.com/backstage/backstage/tree/master/plugins/cost-insights)
```bash
cd packages/app
yarn add @backstage/plugin-cost-insights
```

Created a new plugin:
```bash
% yarn create-plugin --backend --no-private
```
Added logic and checked into Git repo and added to backstage app:
```bash
cd packages/app
yarn add git+https://github.com/seizadi/plugin-cost-insights-backend.git 
```
Build of the app fails with new plugin
```bash
yarn build
...
ERROR in /Users/seizadi/projects/go-projects/src/github.com/seizadi/backstage-helm/node_modules/plugin-cost-insights-backend/src/api.ts 13:14
Module parse failed: Unexpected token (13:14)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export class FetchError extends Error {
>     get name(): string {
|         return this.constructor.name;
|     }
ℹ ｢wdm｣: Failed to compile.
```

1. Step 1
```bash
git clone git@github.com:seizadi/backstage-helm.git
```
2. Step 2
```bash
yarn build
```

The plugin that fails is located here:  https://github.com/seizadi/plugin-cost-insights-backend

## Context
I am trying to build a backend for cost-insights frontend plugin

## Your Environment

- NodeJS Version:
```bash
❯ node
Welcome to Node.js v14.15.5.
```

- Operating System and Version (e.g. Ubuntu 14.04):
MacOS 10.15.7

- Browser Information:
Chrome

**Comment by freben** [comment]
What strikes me as really odd in here, is `yarn add git+https://github.com/seizadi/plugin-cost-insights-backend.git`. I'm honestly not sure what effect that will have on your package.json and yarn.lock. What it should contain, is only a line like `"plugin-cost-insights-backend": "^0.1.0"`.

I also notice that your checked-in backend has a package-lock.json file, indicating that you'd been using npm - you probably want to delete that one and make sure to keep using yarn.

**Comment by mwz** [comment]
Hi @seizadi - have you been able to find a solution for this or did you end up publishing the package to npm instead?

**Comment by cmoulliard** [comment]
That should be great that backstage project explains how to handle such a use case when we develop a new component, plugin, etc. 
I posted too a question on discord : https://discord.com/channels/687207715902193673/1196725671007879219
