### ISSUE TITLE
[GitHub Action Plugin]Support GitHub Apps in addition to GitHub OAuth Apps

### ISSUE THREAD

**Issue by kim5566** [backstage/backstage#6976]
## Feature Suggestion

Github Action Plugin requires to install Github OAuth App. 
https://roadie.io/backstage/plugins/github-actions/
This Github Action API is available for GitHub Apps as well.

## Possible Implementation

1. get config from Integrations
2. leverage GithubCredentialsProvider
## Context

It would benefit for people who have no Github OAuth App setup.

**Comment by freben** [comment]
I wonder - maybe this actually works anyway, if you enter the GH app information in your config? 🤔  In any case, you may want to raise this with Roadie as well on their repo for that plugin.

**Comment by punkle** [comment]
As I understand it, all of our (RoadieHQ) plugins work with GH Apps. At least we do not use PATs anymore.

**Comment by Rugvip** [comment]
This should be fixed by #6912 as we now support both GitHub Apps and OAuth Apps for client-side auth. Roadie docs need some updating though (@punkle @dtuite)

**Comment by dtuite** [comment]
@Rugvip Which docs exactly? Off the top of my head I can't think where we referenced that.

**Comment by Rugvip** [comment]
@dtuite In the docs referenced in the issue ^ 😅, https://roadie.io/backstage/plugins/github-actions/, and that one links on to the main piece: https://roadie.io/blog/github-auth-backstage/

**Comment by dtuite** [comment]
@Rugvip oh right yes. Sorry 😂 Will get that fixed.

**Comment by benjdlambert** [comment]
can we close this?

**Comment by dtuite** [comment]
Our docs are fixed now. This can probably be closed if you like?
