### ISSUE TITLE
[Search] Add SearchType component to storybook search collection

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#6996]
## 🗒 General

It would be useful if the [SearchType component](https://github.com/backstage/backstage/tree/master/plugins/search/src/components/SearchType) could be added to the Storybook search collection.

Read about how to [create a new Story](https://backstage.io/docs/dls/contributing-to-storybook#creating-a-new-story).

**Comment by Rajat-patel19** [comment]
can i work on this

**Comment by vinzscam** [comment]
Hi @Rajat-patel19!
Sorry, last week I forgot to mention here that I had already picked up the issue: #7079
