### ISSUE TITLE
[Home Page] Welcome Experience Component

### ISSUE THREAD

**Issue by rubenLindstrom** [backstage/backstage#6998]
## Feature Suggestion
As suggested by @kiranpatel11, a home page component that introduces a welcome experience would certainly be useful for the home page. There are many ways in which such a system could be used, but some key features could include highlighting of key features, links to important docs, etc.

## Possible Implementation
Given the complexity of this, and all the different alternatives that are available, it would probably be wise to tie this to some sort of wizard in the long run. Short term implementation could be a simple card based slideshow layout, which can render an arbitrary amount of tips.

## Context
For the new Home Page as described in #5416 to be of use, there has to exist an ecosystem of components to be used for composing a home page. This issue suggests the implementation of one such component.

**Comment by freben** [comment]
Hi! This one is a bit light on details - not sure what the wizard would entail, and what set of cards one might get started with. Would we be providing cards that look neat but whose title and description and image you have to provide as props, or is the abstraction on another level than that?

I'll just drop a (low-resolution but hopefully clear enough) screencap from the Runway demo that American Airlines made some time ago:

<img width="527" alt="Screenshot 2021-08-30 at 20 52 16" src="https://user-images.githubusercontent.com/3097461/131389792-2a11d50b-d365-4f85-8bcb-b3876186ecb3.png">

Do you mean those kinds of hero button experiences, or something else?
