### ISSUE TITLE
Create a new column

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#7004]
Hi,

Could we create a new column in the catalog page, and do not create a new plugin for it? For example, create a column for showing slack channel.

![image](https://user-images.githubusercontent.com/56138162/131395230-14bb7495-c7bc-4086-a1cb-7c70cc955cc6.png)

**Comment by timbonicus** [comment]
Yes, you can provide `columns` as a prop in your `packages/app/src/App.tsx`:

```diff
+import {
+  createNameColumn,
+  createOwnerColumn,
+  createSystemColumn,
+  createSpecTypeColumn,
+  createSpecLifecycleColumn,
+  createMetadataDescriptionColumn,
+  createTagsColumn,
+} from '@backstage/catalog';

+const columns: TableColumn<EntityRow>[] = [
+ createNameColumn(),
+ createSystemColumn(),
+ createOwnerColumn(),
+ createSlackChannelColumn(), // your custom column definition
+ createSpecTypeColumn(),
+ createSpecLifecycleColumn(),
+ createMetadataDescriptionColumn(),
+ createTagsColumn(),
+];

const routes = (
  <FlatRoutes>
    ...
-    <Route path="/catalog" element={<CatalogIndexPage />} />
+    <Route path="/catalog" element={<CatalogIndexPage  columns={columns} />} />
    ...
);
```

See those [default column definitions](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/columns.tsx) to see what defining a column looks like.

**Comment by chuliang014** [comment]
Greate! But I still need to implement the function for handling the field from my entity yaml file, right? like entity.metadata.slackchannel.

**Comment by timbonicus** [comment]
@chuliang014 Yep, that's right! `createSlackChannelColumn()` in this example would define how to get the information to display off the entity passed in for each row.

**Comment by freben** [comment]
@chuliang014 Closing this as answered - I hope that's OK. Let us know if not!

**Comment by chuliang014** [comment]
@freben one more questions, could we customized our owned AboutCard, like add a Slack field on AboutCard.

![image](https://user-images.githubusercontent.com/56138162/131559980-abe4013b-79ea-41f1-b438-2ca3cac28f28.png)

**Comment by timbonicus** [comment]
This is proposed in #6175 but not yet available. In the meantime, you _can_ use [metadata.links](https://backstage.io/docs/features/software-catalog/descriptor-format#links-optional) for this purpose perhaps.
