### ISSUE TITLE
code mods not working on windows

### ISSUE THREAD

**Issue by alzafacon** [backstage/backstage#7018]
## Expected Behavior

I should be able to run npx @backstage/codemods apply core-imports in my project successfully.

## Current Behavior

> npx @backstage/codemods apply core-imports

npx: installed 466 in 59.658s
Running jscodeshift with these arguments: --parser=tsx --extensions=tsx,js,ts,tsx --transform ..\..\..\..\AppData\Roaming\npm-cache\_npx\24996\node_modules\@backstage\codemods\transforms\core-imports.js --ignore-pattern=**/node_modules/** .
'jscodeshift' is not recognized as an internal or external command,
operable program or batch file.

Command 'core-imports' exited with code 1

## Possible Solution

🤷‍♂️ 

## Steps to Reproduce

1. generated a project with old create-app
2. npx @backstage/codemods apply core-imports
3. see error

## Context

I have to manually do the core import upgrades

## Your Environment

- NodeJS Version (v12): 14
- Operating System and Version (e.g. Ubuntu 14.04): windows 10
- Browser Information: n/a

**Comment by timbonicus** [comment]
This seems like a PATH issue, `npx` installs the dependencies and then can't find them. Does setting [this npm config](https://stackoverflow.com/a/58354623/99021) help?

**Comment by alzafacon** [comment]
Well I don't have any spaces in my user path....
so first I tried running `PS C:\Users\work\git\backstage> npx @backstage/codemods apply core-imports` in backstage itself, and it worked 🤷 
```
Running jscodeshift with these arguments: --parser=tsx --extensions=tsx,js,ts,tsx --transform ..\..\AppData\Roaming\npm-cache\_npx\13112\node_modules\@backstage\codemods\transforms\core-imports.js --ignore-pattern=**/node_modules/** .
Processing 6445 files...
Spawning 15 workers...
```


then I tried the config you shared for my generated project... but it did not work
```
PS C:\Users\work\git\runway> npm config set cache "C:\Users\work\AppData\Roaming\npm-cache" --global
PS C:\Users\work\git\runway> npx @backstage/codemods apply core-imports
npx: installed 466 in 49.397s
Running jscodeshift with these arguments: --parser=tsx --extensions=tsx,js,ts,tsx --transform ..\..\AppData\Roaming\npm-cache\_npx\6820\node_modules\@backstage\codemods\transforms\core-imports.js --ignore-pattern=**/node_modules/** .
'jscodeshift' is not recognized as an internal or external command,
operable program or batch file.

Command 'core-imports' exited with code 1
```

**Comment by Rugvip** [comment]
Been leaving this as low prio as there's a workaround, but in case anyone wants to investigate this it's good to know that the invocation of `jscodeshift` is set up a bit strangely. It's because the published executable file in `jscodeshift` has a `\r\n` line ending after the `#!/usr/bin/env node` shebang, which breaks execution in unix.
