### ISSUE TITLE
Not able to see component logs while creating new catalog service

### ISSUE THREAD

**Issue by sjamidar** [backstage/backstage#7024]
i am using plugin scaffolder backend plugin and gitlab ,
Creating new catalog service using template. But not able to get any logs in UI once click on create button.
getting only Loading and Waiting for Logs update 
Eventstream API is returning proper data.

![image](https://user-images.githubusercontent.com/85929731/131614923-adfa2d22-f988-4f61-8392-29b21966f15e.png)

**Comment by Rugvip** [comment]
Hi! Need a bit more info for this one, are you seeing any errors anywhere?

Could it be that you're facing the same issue as in #6546?

Another possibility could be that the scaffolder backend is having trouble connecting to GitLab?
