### ISSUE TITLE
Owner field in catalog table converted to lower case

### ISSUE THREAD

**Issue by kcheriyath** [backstage/backstage#7027]
## Expected Behavior

Entity names can follow the pattern below.

- Must consist of sequences of [a-z0-9A-Z] possibly separated by one of [-_.]
- Example: visits-tracking-service, CircleciBuildsDumpV2_avro_gcs

Assumption is that this allows team names to be Uppercase and the case will be preserved in the UI.

## Current Behavior

Team names are switched to lower case in catalog table.

Whilst largely cosmetic, an unintended consequence is that this breaks the ownership link in the UI between the Teams screen and catalog table. 

Now if we go to team view and see the team owns N components, clicking on the link takes you to the catalog table with filter applied on owner column for the team. 
For upper case teams, this link shows no rows as the catalog table view has converted the values to lower case. The user can get he correct results by selecting the lower case equivalent of the team name in the drop down.

## Steps to Reproduce

1. Have at least one team with an Uppercase name owning at least one component
2. Go to Explore -> Groups -> Uppercase team name
3. Click component link in ownership card
4. This takes the page to catalog table with no records displayed and Owner dropdown selected as Uppercase team name
5. Selecting lower case team name displays the components owned by the team

## Context

Uppercase team names are converted and displayed in lower case in few other screens like explore and system views but the hyperlinks redirect correctly, so the issue is cosmetic. From the team view, this causes incorrect/misleading results.

**Comment by johanhammar** [comment]
I believe this is still a problem, so not stale?

**Comment by Rugvip** [comment]
Will chime in with that this is largely due to the use of the lower-cased canonical representation returned by `serializeEntityRef` being the one that we store relation pairs in the database. A possible solution could be to also store a case-sensitive version of the target ref and use that in the relation target representation within entities. Or even just store the existing target ref in case-sensitive non-canonical form, although that is a bit scary and could lead to issues if not handled correctly. A workaround for that could be to use case-insensitive text fields in Postgres, but I'm worried that's leaning a bit too heavily into DB features.

**Comment by johanhammar** [comment]
This is still an issue. Are there any workarounds or advice how a solution could be implemented?

**Comment by freben** [comment]
We just talked about this among ourselves and I agree that the entity refs being lowercased is really frustrating and ultimately an artifact of database internals that should not leak out to end users. However, addressing it and making them retain the original case will be a delicate, long-running effort that risks causing breakages in various parts of the application. Therefore we want to be really careful and plan it out, if we are to make that change.

In the mean time, individual pieces of code (such as the catalog filters, and the pickers, etc) need to be properly case insensitive in their behavior. If they aren't then that's a bug in that component and needs to be addressed!
