### ISSUE TITLE
TechDocs: GitHub fetching broken for branches including slash "/"

### ISSUE THREAD

**Issue by FilipPyrek** [backstage/backstage#7031]
I'm trying to implement TechDocs for our organization.. but I've stumbled upon a problem that we use feature branches like `f/some-branch` or `feature/some-branch` etc. but Backstage detects as a branch only `f` or `feature`. 

```
"backstage.io/techdocs-ref": "url:https://github.com/purple-technology/some-branch/tree/feature/some-feature"
```

## Expected Behavior

Backstage TechDocs should fetch docs from correct branch `feature/some-branch`.

## Current Behavior

Backstage TechDocs throws error because it can't find (nonexisting) incorrect branch `feature`.

Error:
```
Building a newer version of this documentation failed. Error: "Request failed for https://api.github.com/repos/purple-technology/some-repo/branches/feature, 404 Not Found"
```

## Possible Solution

I tried to do some digging and I found this:

https://github.com/backstage/backstage/blob/master/packages/backend-common/src/reading/GithubUrlReader.ts#L275
```ts
const parsed = parseGitUrl(url);
const { ref, full_name } = parsed;
```
and it seems that the "broken" behavior is coming from package `git-url-parse` which parses `ref` inside which is only `feature`.

I'm not sure whether it parses it correctly according to git docs or not.. but I think that many developers are using `/` in their branch names and this problem makes it very limiting.

![image](https://user-images.githubusercontent.com/6282843/131693886-00cda1b1-e919-4751-989b-ea3a8eece52d.png)

## Steps to Reproduce

1. Create in your GitHub repo branch with name which includes slash `/` - for example `feature/some-branch`
2. Add annotation to your Component: `'backstage.io/techdocs-ref': url:https://github.com/${your-org}/${your-repo}/tree/feature/some-branch`
3. Open TechDocs for your Component
4. Take a look at the error 🙂 

## Context

'm trying to implement TechDocs for our organization.. but I've stumbled upon a problem that we use feature branches like `f/some-branch` or `feature/some-branch` etc. but Backstage detects as a branch only `f` or `feature`. 

And this is a huge show stopper for us.

## Your Environment

- NodeJS Version: v14
- Operating System and Version: macOS BigSur 11.5.2
- Browser Information: Chrome  92.0.4515.159

**Comment by dhenneke** [comment]
Related to https://github.com/backstage/backstage/issues/2815.

**Comment by freben** [comment]
Yep, closing as duplicate to keep the discussion focused there. Thanks for reporting though, and the additional context added. Feel free to chime in additionally on that issue.
