### ISSUE TITLE
Highlight terms in search results

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#7041]
## Feature Suggestion

In the search result page, highlight the user's search keywords in the result text.

## Possible Implementation

**Backend**: The interface for search results for the various backends should be changed to return optionally an array of highlight positions:

```ts
type Position = {
  term: string; // the actually matched word(s) after stemming etc
  field: JSONPath; // where in the doc was it found, eg title or body
  pos: number; // index in string of first character
}
```

These would be forwarded to the client in `GET /search/query` responses.

Obviously support for this is variable - Lunr has it ([demo](https://olivernn.github.io/moonwalkers/)), ElasticSearch also IIRC. But I can't find any evidence that Postgres does.

**Client**: I think I built something like this once, or maybe I just spent a lot of time fixing off by one bugs in something that was already there - those memories are well repressed 😅 But essentially you're going to walk through each matchable field, building up an array of text fragments and `<span>`s or whatever, and then rendering that in your component. Of course there are edge cases around complex unicode characters and so on. 

## Context

Now we have search in TechDocs, it's a much more useful feature for us. However, that in turn builds up demand for common UX affordances like this. Highlighting results is very common in search pages, from Google on down.

**Comment by Fox32** [comment]
Yeah, you are right it's more complicated for postgres. While there is a [`ts_headline` functio](https://www.postgresql.org/docs/9.5/textsearch-controls.html#TEXTSEARCH-HEADLINE)n, this doesn't really help here because it's formatting it as HTML (not outputing some kind of `Position` object) and it's also operating on the source text, which in our case in a JSON document. Not sure how to implement it there…

**Comment by iamEAP** [comment]
The method I'm most familiar with for ES is also not ideal (one adds a `highlight` option to the query with options like number of fragments, fragment size, fields, etc).  But it too returns HTML (although you can specify the tag).

Given the diverse set of engines, we may have to go with the client-side approach.

**Comment by tragiclifestories** [comment]
Obviously if we get back a highlighted string that makes the client code 'easier' (good old `dangerouslySetInnerHTML` to the rescue 🙈 ). But of course it'll break CSS encapsulation and so on. 

You could use the `StartSel/StopSel` options in PG (and ES equivalents) to parse out your own position array as per above of course. But that might be a lot of work for large result sets.

**Comment by Fox32** [comment]
> You could use the `StartSel/StopSel` options in PG (and ES equivalents) to parse out your own position array as per above of course. But that might be a lot of work for large result sets.

Had the same idea 😆  Then one still has the problem that `ts_headline` expects a `text` as an input, but we have `jsonb` 😞  

```
ts_headline([ config regconfig, ] document text, query tsquery [, options text ]) returns text
```

We could call it for every field (as your suggested `Position` object contains the field name, nice!), just wondering how to handle arrays, we could either skip or concat them 🤔. Or make `pos` optional for array fields.

**Comment by tragiclifestories** [comment]
Yeah, my PG text-search understanding is ... suboptimal 🙈 From looking at the migrations in the plugin it looks like you're generating a single tsvector from concatenating the fields in the body JSON - is that right? Not sure if that can be reverse-engineered at query time 🤔

**Comment by Fox32** [comment]
`ts_headline` doesn't operate on `tsvector`, it uses a simple `text`. Good news is, that we still have the full json document. So we can:

* For every result
  * For every field in `document`
    * Call ts_headline 
    * Process result and convert separators and add to position array.

We could also just ignore array fields (for now), highlighting terms is probably most important for text and title.

Would love to see this and I'm open to implement the postgres part 🙂

**Comment by Fox32** [comment]
Just one thing that comes into my mind that would vote for a client side implementation: You can use the positions to highlight the results in the search page, but if you want to highlight it in the techdocs view (like in the lunr example) you will run into issues. The index provided by mkdocs might be hard to map on the actual DOM elements of the techdocs view.

Maybe there is even an mkdocs plugin that already support this, based on the mkdocs index in the client 🤔

**Comment by kuangp** [comment]
still very interested in this

**Comment by kuangp** [comment]
still interested

**Comment by kuangp** [comment]
still interested

**Comment by kuangp** [comment]
Took a stab at this in the linked PR using a different approach. Let me know what everyone thinks!
