### ISSUE TITLE
Grey out Create button in template after initial click

### ISSUE THREAD

**Issue by hiba-aldalaty** [backstage/backstage#7045]
## Feature Suggestion

Disable/Grey out the 'Create' button in templates after initial click

## Possible Implementation

Before click:
![image](https://user-images.githubusercontent.com/72443252/131863239-17b21b04-57ed-4557-8be9-7fc5ddefc3f7.png)

After click:
![image](https://user-images.githubusercontent.com/72443252/131860689-3210bb20-2c2e-42d5-95fc-9131a6e8502d.png)

## Context
Sometimes, slowness in starting the template execution can cause the end user to think they didn't successfully click the "Create" button. This means the customer will likely click it a second time or more.
This will lead to multiple applications being created and will cause additional confusion for the customer.

Disabling this button after click will indicate to the customer that they successfully clicked the button, and will prevent multiple applications being created.

**Comment by Rugvip** [comment]
👍 🎉
