### ISSUE TITLE
Sentry Plugin - Missing Annotation Bug v0.3.20

### ISSUE THREAD

**Issue by satrox28** [backstage/backstage#7058]
Sentry plugin v0.3.20 have a bug, where its complaining about missing annotation after having the annotation on the catalog-info.yaml
## Expected Behavior
To display the Sentry Issues on the service catalog.

## Current Behavior
Displaying missing annotation content. Attached screenshot for the reference.

## Steps to Reproduce

1. When a user download v0.3.20 will be able to reproduce the issue.
2. Switch to v0.3.19, it should work as expected without any changes.

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04): 
- Browser Information: 

![Sentry-Missing-Annotation-Bug](https://user-images.githubusercontent.com/24196271/131990378-e5695ce7-d853-4259-a25a-0e6d8aa0f12a.png)

**Comment by Rugvip** [comment]
Would assume that this is a versioning issue. Could you run a `yarn why @backstage/plugin-catalog-react` and check what versions of it that you have? Perhaps also a `yarn backstage-cli versions:check` and see if it has any warnings

**Comment by satrox28** [comment]
it's working now after yarn backstage-cli versions:bump
