### ISSUE TITLE
Custom filters on ScaffolderPage

### ISSUE THREAD

**Issue by victormorfin97** [backstage/backstage#7063]
## Feature Suggestion

Enable the customization of the ScaffolderPage to add custom filters as we have it on the other catalogs.

## Context
At Expedia we don't limit the user to a set of categories, so the current categories filter is a long list of checkbox and we would like to change it to a dropdown. In other use case probably in future we would like to add more filters to improve the user experience (maybe filter by ratings), and with the ability to custom filter we are going to be able to do it.
<img width="690" alt="Screen Shot 2021-09-03 at 8 17 53" src="https://user-images.githubusercontent.com/40499017/132020387-da2f04e1-fcbc-4d33-aa6a-a4e50f470fea.png">

## Possible Implementation

Currently in Service Catalog & Api Catalog Page we have that functionality , to add our custom filters by making our own ApiExplorerPage or CatalogPage. So I was thinking that we could make some changes to scaffolder-plugin to enable that something similar.

**Comment by timbonicus** [comment]
This should be possible already as of #6150, which changed the ScaffolderPage to use the same `EntityListProvider` mechanism as the CatalogPage and ApiExplorerPage. Potentially could replace this with `EntityTypePicker` which uses Autocomplete.

**Comment by victormorfin97** [comment]
Hi @timbonicus ,
Well I think the EntityTypePicker could work to change it as a dropdown, but it don't have the autocomplete functionality, so I think, we have two options:

- Update the EntityTypePicker component to have the autocomplete functionality.
- Change the current type filter component to a dropdown and autocomplete functionally. 

I think the first option would be the ideal so we can avoid to have two components that do the same thing.
