### ISSUE TITLE
SAML authentication bypass possibility due lack of SAML authn response audience verification

### ISSUE THREAD

**Issue by srd90** [backstage/backstage#7067]
## Expected Behavior

SAML authentication response must be discarded if its `audience` is not Backstage instance.

## Current Behavior

Backstage does not validate `audience` so it is/would be possible to get authenticated session to Backsage by replaying auth response which was targeted to some other SP as long as SPs involved use same IdP because message's signature is valid from Backstage point of view (*). `passport-saml`'s `audience` check is disabled by default. It is enabled if SP (Backstage) provides value to `audience`configuration parameter. See: https://github.com/node-saml/passport-saml/tree/04ee9415f7aad1f7763690b8e4711af6157c1985#config-parameter-details 

(*) assuming that response signature validation is turned on at `passport-saml` configuration. If not then Backstage instance is open for everyone without having to ever visit IdP at all and it would be possible impersonate any user including but not limited to admin users. `passport-saml`'s versions `< 3.0` skip authentication response signature validation if `cert` configuration parameter is not present at configuration options provided to `passport-saml`'s `Strategy`. I.e. if Backstage instance which uses SAML authentication fails to set up `cert` it - Backstage - would be open for everyone who decides to post saml authentication response message to Backstage's assertion consuming endpoint.

There is no way to set `audience` parameter to `passport-saml` instance:
https://github.com/backstage/backstage/blob/7f00902d976297bb03b1ff6c27d2fac424243319/plugins/auth-backend/src/providers/saml/provider.ts#L123-L150

## Possible Solution

Consider making `audience` mandatory configuration value even though `passport-saml` doesn't require it at the moment / yet. Most SP implementations / SAML stacks consider `audience` validation mandatory. Related `passport-saml` side issue/comment: https://github.com/node-saml/passport-saml/issues/137#issuecomment-883482011

## Steps to Reproduce

Intercept and store(*) response to some other SP and then replay that authentication response to Backstage instance within `NotOnOrAfter` time limits.

(*) browser's network tab. "Interception" can occur also so that some other SP happens to log all HTTP traffic after HTTPS termination point i.e. if SAML login responses are picked up from some other SP's logs and then posted to Backstage's assertion consuming endpoint.

Note: replay attack with stored authentication response would work indefinitely (or as long as IdP certificate is not expired) if Backstage instance configures `passport-saml` with `acceptedClockSkewMs = -1` because it would disable `NotOnOrAfter` validation so consider also making values less than zero unacceptable to `acceptedClockSkewMs` (`passport-saml`'s default vale for `acceptedClockSkewMs` is zero).

Note2: replay attack would be possible even if `audience` is validated if `acceptedClockSkewMs` is set to `-1`. I.e. user who has lost access to Backstage instance (if IdP would not allow login anymore due removed privileges etc.) could use/replay stored authentication response to log into Backstage instance.

## Your Environment

Affects all Backstage instances which use SAML authentication.

**Comment by freben** [comment]
Related ongoing work:

https://github.com/backstage/backstage/pull/7014

https://github.com/backstage/backstage/pull/7015

**Comment by srd90** [comment]
`passport-saml >= 4.0` is (probably) going to have `audience` validation turned on by default.

Related pull request: https://github.com/node-saml/node-saml/pull/25

Note: If you wonder why referenced pull request is at [node-saml/node-saml](https://github.com/node-saml/node-saml) repository answer is that: They have moved/splitted [node-saml/passport-saml](https://github.com/node-saml/passport-saml) < 4.0 versions' core SAML functionality to separated module. `passport-saml >= 4.0` - once it is released - shall use `node-saml >= 4.0`.
