### ISSUE TITLE
Backstage OAuth2.0 Implementation changes

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#7088]
Hi,

We have cloned the backstage repository and have integrated with our SSO provider which internally implements OAuth2.0. 
Now once we hit our main url it basically goes back to SSO provider which asks for username/password and upon validation with the LDAP server, it returns the Backstage Sign In page, which gives us multiple options to sign in again which is not the desired user experience. But, another issue happens here is when we click on the "Sign In" button of the OAuth2.0 plugin, it says "Auth response is missing cookie nonce"

Our desired user experience is that when our main url connects to the SSO provider and after the user is authenticated correctly, then user should be logged in ( of course using Oauth2.0 plugin ) and it should directly take us to landing page. ( without showing the Sign In page again )
Can someone throw me some light on to how this could be possible.

**Comment by Rugvip** [comment]
So as I understand it you're deploying Backstage behind an authenticating reverse-proxy, which is good! If you want to and are able to re-use the identity from the proxy you can use something like [this](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/aws-alb-aad-oidc-auth.md), which allows you to skip the sign-in page altogether.

Regarding the sign-in error I suspect that's because your proxy is filtering out cookies that are needed for the OAuth dance.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Ok thanks or this option.
But, lets suppose we use @backstage:create-app version, which automatically does the sign in as guest user. And with this create-app version if we were to have create a dummy sign in page, which displays few authentication providers and then when users clicks on one of the sign options, it connects the authentication provider and logs the user back in. How should we do this?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Regarding https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md, we use OAuth provider ( which internally uses OIDC ). If I just implement what is mentioned in the document, which means only use the refresh tokens, then the system will complain regarding env and headers. Is there any example implementation where it says about authentication with a provider before the app but with OAuth

**Comment by Rugvip** [comment]
> Ok thanks or this option.
> But, lets suppose we use @backstage:create-app version, which automatically does the sign in as guest user. And with this create-app version if we were to have create a dummy sign in page, which displays few authentication providers and then when users clicks on one of the sign options, it connects the authentication provider and logs the user back in. How should we do this?

Why do you want to do this though? 😅 If you're behind a proxy that you trust and is able to prove the user's identity you can register a sign-in page that is completely automatic, with no user interaction required. Or am I misunderstanding something with your setup?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Yes, our first option is to use the auth provider which is behind the proxy, but when we try to use fetch(`${window.location.origin}/api/auth/oauth2/refresh`)  as suggested under https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md , we get error which says "env" query param not found and when we add the "env" parameter, it says "invalid x-requested-with header".
Not sure if I have misunderstood how to implement.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
I have resolved this by not using the authentication directly but go through the sign in page as the landing page

**Comment by EyalAbadi** [comment]
@shanthisagar-dhanya-kumar-db  how did you navigate to the sign in page? I click logout and it keeps me on the same page still logged in as guest

**Comment by shanthisagar-dhanya-kumar-db** [comment]
@EyalAbadi : Do you have any auth providers other than the guest? If not, then it will just log you back.

**Comment by EyalAbadi** [comment]
I do, github and OAuth2, but it doesn't do anything and I can see logs. If I try authenticating either from the settings or even in the register existing component, I get this error with nonce

**Comment by shanthisagar-dhanya-kumar-db** [comment]
What does your SignInPage: props => (
looks like?

**Comment by EyalAbadi** [comment]
I'm not modifying the code, just template over it, so its the standard SignInPage from backstage. I'm using docker to build the image
