### ISSUE TITLE
Provide an API to extend Webpack config

### ISSUE THREAD

**Issue by taras** [backstage/backstage#7102]
## Context

On the HP DevEx project, we're using Backstage backend to build a system model. The project setup is similar to the default created by @backstage/create-app. On the frontend, we're using GraphQL with Relay which uses [relay-compiler](https://relay.dev/docs/guides/compiler/#internaldocs-banner) to compile GraphQL queries into TypeScript types. This mechanism requires [babel-plugin-relay](https://relay.dev/docs/getting-started/installation-and-setup/#set-up-babel-plugin-relay) to extract `graphql` tag string. Unfortunately, the only way to integrate this functionality into the project is via the babel plugin. Backstage doesn't use Babel, so it needs to be added to Webpack config.

## Feature Suggestion

Provide an API to extend the Webpack config that's used by `@backstage/cli plugin:build`. There are lots of ways to do this. In our case, here is patch that we made to the `@backstage/cli@0.7.10` to add `babel-plugin-relay`.

```diff
diff --git a/node_modules/@backstage/cli/dist/cjs/paths-0c550867.cjs.js b/node_modules/@backstage/cli/dist/cjs/paths-0c550867.cjs.js
index 660cea7..01071d9 100644
--- a/node_modules/@backstage/cli/dist/cjs/paths-0c550867.cjs.js
+++ b/node_modules/@backstage/cli/dist/cjs/paths-0c550867.cjs.js
@@ -78,11 +78,22 @@ const transforms = (options) => {
     {
       test: /\.(tsx?)$/,
       exclude: /node_modules/,
-      loader: require.resolve("@sucrase/webpack-loader"),
-      options: {
-        transforms: ["typescript", "jsx", ...extraTransforms],
-        production: !isDev
-      }
+      use: [
+        {
+          loader: require.resolve("@sucrase/webpack-loader"),
+          options: {
+            transforms: ["typescript", "jsx", ...extraTransforms],
+            production: !isDev
+          }
+        },
+        {
+          loader: require.resolve('babel-loader'),
+          options: {
+            presets: [require.resolve('@babel/preset-react'), require.resolve('@babel/preset-typescript')],
+            plugins: ['relay']
+          }
+        },      
+      ]
     },
     {
       test: /\.(jsx?|mjs)$/,
``` 

## Possible Implementation

We can contribute the implementation if Backstage team can provide direction on what API should be exposed.

**Comment by Rugvip** [comment]
Quick update on where we are with this: We'll likely go with recommending that you set up your own webpack build of the project instead of providing an API to tap into the config. With the build system we've always had the goal for the to be possible and therefore avoid any too deeply integrated compiler customization. The missing piece is ofc a more thorough documentation of our build pipeline, which I have on a TODO note 😅

The reason for not going the config route is to not encourage it at all, as it will lead to hard to fix breakages for people in the future. We like to be able to freely switch out things like the hot reloading and transpilers as the web landscape moves along. We want the choice of customizing the compilation to be a very deliberate one with an understanding that it will require some effort.

**Comment by taras** [comment]
@Rugvip that makes sense. We're already finding that our project layout is sufficiently different that trying to fit it into `@backstage/cli` might be counterproductive. Your response gives us more confidence to move in that direction. Thank you. I'll close this issue.

**Comment by taras** [comment]
For posterity, if you need to make changes to Webpack config. You can use [patch-package](https://www.npmjs.com/package/patch-package ) to patch dist of `@backstage/cli` package. This workaround is not perfect, but it'll give you something workable.

In root of the workspaces,

1. yarn add -D -W patch-package
2. Add "postinstall": "patch-package" to scripts in package.json
3. Modify dist files in node_modules
4. Run yarn patch-package <package-name>
5. Add generated and modified files to git 
When you pull down the code, it'll automatically apply the patches. You can remove it when you don't need it anymore.
