### ISSUE TITLE
Plugins folder not found when creating Multi-stage Docker Image using documentation

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#7107]
## Expected Behavior

The Docker image should be created

## Current Behavior

If you follow the documentation found here: https://backstage.io/docs/deployment/docker#multi-stage-build on creating a multi-stage docker image and you have a plugins folder you'll run into the following error: "failed to compute cache key: "/plugins" not found: not found"

![image](https://user-images.githubusercontent.com/67169551/132551396-033fc326-ed53-43f7-a3e3-d6fd3cf234a6.png)

## Possible Solution

Currently a fresh run of `npx @backstage/create-app` does not include any plugins so the easy solution would be to remove the reference to `plugins` in the `.dockerignore` file that is created. 

BUT, we are in a bit of a Host Build vs. Multi-stage build situation. Perhaps clarifying the documentation might be a better solution?

## Steps to Reproduce
 1. Run `npx @backstage/create-app`
 2. Then follow the Multi0stage build instructions here: https://backstage.io/docs/deployment/docker#multi-stage-build
 3. Now run `docker image build -t backstage .`

Notice that you'll get the error mentioned above

## Context

It was a little confusing as I clearly had a plugins folder and I thought I was following the documentation as intended. I've been able to work around this but logged this ticket so we can clear this up for others down the road

## Your Environment

There isn't any environment specific things in this case.

**Comment by awanlin** [comment]
I think my issue was that I assumed that I should append the `.dockerignore` file and not overwrite the contents with that was provided in the instructions.

**Comment by satrox28** [comment]
@awanlin you have to comment that copy lines for plugin, it will be automatically from package.json

**Comment by awanlin** [comment]
Thanks @Rugvip I was going to submit a PR for this but wasn't sure if I was just a one off or not. you update makes things more clear 👍
