### ISSUE TITLE
template for creating an catalog descriptor file

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#7111]
Hi,

Since we have unified place for storing all the catalog yaml file, could we use template for creating a catalog descriptor file(do not need to include any code) and then push to the our repo?  If have, this would be the most convenient way for users to onboard their service via frontend.

For example, after the user submit the form,  the scaffolder can create the path based on the form content and push to github repo.

![image](https://user-images.githubusercontent.com/56138162/132598686-8d7549ea-4c5f-49ce-8ad2-21a7e14abed0.png)

**Comment by Rugvip** [comment]
For this I think you want on piecing together existing actions. There's `catalog:write` that can create the `catalog-info.yaml` for you, and then `publish:github:pull-request` for publishing a PR. Right now it's only GitHub that has support for publishing via a PR.

**Comment by chuliang014** [comment]
Hi @Rugvip, could we customized our owned repoUrl?  Cause now seems accept the format `github.com?repo=reponame&owner=owner`.  For example, I hope it can push to `github.com/<Org>/<Repo>/<team-name>/<service-name>/catalog.yaml` , and `team-name` and `service-name` are from the user entered.

**Comment by Rugvip** [comment]
@chuliang014 Yep, you should be able to template that using the [templating syntax](https://backstage.io/docs/features/software-templates/writing-templates#the-templating-syntax)

**Comment by chuliang014** [comment]
@Rugvip Perfect!  I was trying to use `catalog:write` and `publish:github:pull-request`, but how to get the `catalog-info.yaml` after executed? I saw the PR, and the catalog-info file is empty.
![image](https://user-images.githubusercontent.com/56138162/132923233-3dafddb7-f182-459e-a5f1-7655692ad14b.png)
![image](https://user-images.githubusercontent.com/56138162/132923286-726e8b7c-6b1f-49ce-ad94-64f2f6237193.png)

**Comment by Rugvip** [comment]
@chuliang014 You'll want to lowercase the `entity` under the input in that yaml

**Comment by benjdlambert** [comment]
Can we close this?

**Comment by chuliang014** [comment]
Sure. Please close it.
