### ISSUE TITLE
Paginate for list repositories accessible to the app installation

### ISSUE THREAD

**Issue by kim5566** [backstage/backstage#7112]
## Feature Suggestion
When a GITHUB app installation has a repository restriction, current GithubCredentialsProvider attempts to check if the repo was not accessable to the github app installation. There is an additional api call to list the repositories available to installation but according to [doc](https://github.com/octokit/plugin-rest-endpoint-methods.js/blob/master/docs/apps/listReposAccessibleToInstallation.md) , the default setting is listing 30 repos per page.

It assumes if I have Backstage App installed to 31 repos, my 31st repo cannot grab an access token and with error message 
`The Backstage GitHub application used in the ${owner} organization does not have access to a repository with the name ${repo} `

This is an invalid assumption and mislead error message. 

I understand we can't add filtering based on selected repositories like below because of github-org processor does not use the concept of repositories. 
```javascript
      const result = await this.appClient.apps.createInstallationAccessToken({
        installation_id: installationId,
        headers: HEADERS,
        selected_repositories,
      });
```
 However Github API allows results per page with max 100. Could we change to it or a better way to handle more than 30 pages and provide a more reasonable error.

## Possible Implementation

https://github.com/backstage/backstage/blob/36e26fb9591cd62a87876bec39329d3f24cbd952/packages/integration/src/github/GithubCredentialsProvider.ts#L114
Change to: `await installationClient.apps.listReposAccessibleToInstallation({ per_page: 100 })`

https://github.com/backstage/backstage/blob/36e26fb9591cd62a87876bec39329d3f24cbd952/packages/integration/src/github/GithubCredentialsProvider.ts#L120

Add something like

```javascript
 if (!hasRepo && result.data.total_count > 100) {
          throw new Error(
             Exceeded list limits 100 repos per page,
          );
}
```

**Comment by dhenneke** [comment]
Octokit also provides a `paginate` function that could help here. It is also already used in another part of this file: https://github.com/backstage/backstage/blob/36e26fb9591cd62a87876bec39329d3f24cbd952/packages/integration/src/github/GithubCredentialsProvider.ts#L134

**Comment by kim5566** [comment]
> Octokit also provides a `paginate` function that could help here. It is also already used in another part of this file:
> 
> https://github.com/backstage/backstage/blob/36e26fb9591cd62a87876bec39329d3f24cbd952/packages/integration/src/github/GithubCredentialsProvider.ts#L134

Thanks! I wasnt aware there's a `paginate` function.
