### ISSUE TITLE
Sonarqube Plugin missing annotation

### ISSUE THREAD

**Issue by maurosala** [backstage/backstage#7120]
In catalog-info.yaml I have this

```apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ship-01"
  description: "ship-01"
  annotations:
    github.com/project-slug: maurosala/ship-01
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: "ship-01"
    backstage.io/kubernetes-id: "ship-01"
    sonarqube.org/project-key: maurosala_ship-01
spec:
  type: service
  lifecycle: experimental
  owner: "maurosala"
```

but in dashboard sonarqube plugin still saying "Missing Annotation"

## Expected Behavior

I expect the plugin says code quality information
![image](https://user-images.githubusercontent.com/10496197/132710742-5ea50dec-1967-4a2a-a652-635d7aa3b379.png)

## Current Behavior

You can view repository here [https://github.com/maurosala/ship-01/blob/main/catalog-info.yaml](url)

## Steps to Reproduce

1. add sonarqube plugin [https://www.npmjs.com/package/@backstage/plugin-sonarqube](url)
2. add item with any template (e.g. create react app)
2. add annotation in catalog-info.yaml

**Comment by maurosala** [comment]
This is the error

![image](https://user-images.githubusercontent.com/10496197/132711496-e16072c8-5c95-43bd-adc2-361f81fce23a.png)

**Comment by satrox28** [comment]
Could be related to this, can you try to do version bump.
https://github.com/backstage/backstage/issues/7058
