### ISSUE TITLE
[Plugin] Prometheus

### ISSUE THREAD

**Issue by jackskj** [backstage/backstage#714]
## Summary
Allow developers to view the health and performance of their application by viewing Prometheus queries.

## Motivation
I am using Istio service mesh (on top of k8s) and receive a wealth of telemetry data through Prometheus metrics for each service. 
Metrics like client request volume or % of 5XX responses are very useful in determining the health and performance of the application.
I believe it would be beneficial for developers to see this information directly in Backstage.

https://istio.io/docs/tasks/observability/metrics/using-istio-dashboard/istio-service-dashboard.png

**Comment by stefanalund** [comment]
Excellent! Do you want to work on this yourself or should I add a `help wanted` label on it?

**Comment by jackskj** [comment]
I got Spinnaker feature assigned already. I can take a stab at prometheus after spinnaker

**Comment by alileza** [comment]
@jackskj I wonder if you start working on this? I'd be happy to jump in if it'll take a bit more time in the future. I'm looking forward to having this in my set-up

**Comment by marcuseide** [comment]
Hey, seems you can go ahead and work on this @alileza.

**Comment by JacobValdemar** [comment]
@alileza How are you progressing with this?

**Comment by alileza** [comment]
@JacobValdemar hey, I got pulled on something else, I only done very early stage with prometheus query console UI, might take a bit sometime for graph UI

**Comment by djamaile** [comment]
How is this coming along?

**Comment by JacobValdemar** [comment]
@djamaile I don't think anyone is working on it

**Comment by stefanalund** [comment]
I stumbled upon this recently and thought it could be used for inspiration: https://github.com/prometheus/prometheus/tree/master/web

**Comment by djamaile** [comment]
Thanks, will try something out @ my company

**Comment by OrkoHunter** [comment]
Re-opening since plugin suggestion issues are now exempt from [stalebot](https://github.com/backstage/backstage/blob/18f7345a6c29dcfccef7df081b1708f2bf8f62ff/.github/stale.yml#L9).

**Comment by Xantier** [comment]
4th time is the charm hopefully. I'll grab this and create a plugin for prom.

**Comment by djamaile** [comment]
@Xantier haha I tried to do something, but in the end I couldn’t find a reason why people would use this instead of using Prometheus directly. So, I stopped working on it. Excited to see what you will cook up.

**Comment by dtuite** [comment]
I have updated the assignment of this issue to reflect the recent reality.

**Comment by dtuite** [comment]
I have just linked [a PR which makes a prometheus plugin available for Backstage](https://github.com/RoadieHQ/roadie-backstage-plugins/pull/230). Reviews and comments welcome!
