### ISSUE TITLE
LDAP: Reduce memory use when ingesting LDAP org data

### ISSUE THREAD

**Issue by freben** [backstage/backstage#7142]
## Feature Suggestion

In its current implementation, the LDAP ingestion takes unnecessarily large amounts of memory for huge orgs. One expected reason is that we hold on to the entire result set from the LDAP client itself, before transforming it to entities.

## Possible Implementation

The [current implementation](https://github.com/backstage/backstage/blob/c9ce2ba317b6860b06a241dc9ece6ad2e5f73dca/plugins/catalog-backend-module-ldap/src/ldap/client.ts#L76) of `search` returns all of the `SearchEntry` instances. These are [then transformed](https://github.com/backstage/backstage/blob/c9ce2ba317b6860b06a241dc9ece6ad2e5f73dca/plugins/catalog-backend-module-ldap/src/ldap/read.ts#L110) by the callers.

Introduce a new function, `searchStreaming` or similar. It could be in the form of an async generator function, which yields one entry at a time. Or it could be a single call which takes a transform callback which is invoked for each entry and returns all of the transformed items. Either way, this will let each raw LDAP entry be dropped and garbage collected as the search progresses. The generated transformed entities should occupy a smaller amount of memory.

It is probably not worthwhile to try to do the catalog database updates in a batched fashion though. That's a much larger change to the code, which we probably aren't prepared to support just yet.

**Comment by Erog38** [comment]
As an added idea, could `searchStreaming` take in a batch of entries so it can still batch entity storage calls to persistent storage? At least that way we aren't just transferring the efficiency issue from memory to database transactions.

**Comment by Erog38** [comment]
Open PR with these changes #7180, but it needs some extra help from a maintainer to run the workflows since this is my first contribution.
