### ISSUE TITLE
Issues when app.baseURL uses sub-paths

### ISSUE THREAD

**Issue by blaryjp** [backstage/backstage#7147]
## Expected Behavior

All the links in any pages must correctly route to the right one, so using the sub-path.

## Current Behavior

When you use a baseUrl with a sub-path (for example: `baseUrl: http://localhost:3000/example`), I spotted 2 major bugs:

- the catalog page with the table of entities (so `/example/catalog`) is correctly displayed, but links inside of this table are wrong. They don't have the subpath.
- when you go inside an entity (with the subpath in the URL), and you click on a tab related to a Plugin (github PR, Lighthouse, ...), it throws [this Error](https://github.com/backstage/backstage/blob/7f221c6c6b1be96b0aec02b2c3e5ac65f51af596/packages/core-app-api/src/routing/RouteResolver.ts#L171).

## Possible Solution

I don't find any solution. Updating to last beta of react-router seems not fix the issue.

## Steps to Reproduce

1. Fresh install of Backstage (git clone Backstage from github.com/backstage/backstage)
2. yarn install
3. Modify the `app-config.yaml`, and put a subpath in the `app.baseUrl`, for example: `baseUrl: http://localhost:3000/example`.
4. yarn dev

## Context

We'ld like to deploy Backstage to an URL using a sub-paths.

Note that @Rugvip already fixes related problems, specially for the Sidebar (see [this](https://github.com/backstage/backstage/pull/6749)).

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 18.04
- Browser Information: Chromium 92

**Comment by Rugvip** [comment]
This issue and a lot like it were fixed by #7367, so will close

Please open new issues for any specific instances of sub-paths not being supported
