### ISSUE TITLE
Sort Jenkins builds by timestamp

### ISSUE THREAD

**Issue by akibabu** [backstage/backstage#7155]
## Feature Suggestion

Make timestamp default sorting order in the builds table (CITable.tsx)

## Possible Implementation

The timestamp seem to already be available in the interface returned from the API

## Context

We are not finding the table useful for us because it is cluttered with old builds of old branches.
Data quality aside, is timestamp a better default sorting order?
If not, can it be provided as an option to EntityJenkinsContent

https://github.com/backstage/backstage/blob/master/plugins/jenkins/src/components/BuildsPage/lib/CITable/CITable.tsx

**Comment by san-coding** [comment]
Hey , I am new to open source, Can I work on this

**Comment by freben** [comment]
Thanks, assigned!

**Comment by adamdmharvey** [comment]
@san-coding If it helps as you come up to speed, you'll find some tips in the project [CONTRIBUTING.md](CONTRIBUTING.md) for things like how to add a change set, signing off your commits, etc, and the community is engaging to help as well with any questions. (e.g., Discord is a good avenue for that)  Appreciate it!!

**Comment by san-coding** [comment]
Thanks I will look into it

**Comment by WarlenRodrigues** [comment]
Hi, I was looking into a good open source project to contribute to and found out Backstage (wich is used by a company I used to work) is an open source tool. Is this issue still available so I can start working on it?

**Comment by san-coding** [comment]
Sure, feel free to work on this, I have been a lot busy lately

**Comment by benjdlambert** [comment]
@WarlenRodrigues assigned!

**Comment by WarlenRodrigues** [comment]
Thanks! I'm working in this issue with some friend to a college class based on open source communities and development. They're @manucirne and @gabrielnoal . We're facing some problems to set the jenkins plugin working and see the builds list. We've searched a lot and did not found any backstage/plugin developer's doc that shows how to connect it effectivelly. Can we get some support/direction on this?

**Comment by esquireofoz** [comment]
@WarlenRodrigues since https://github.com/backstage/backstage/pull/7594 produces the requested functionality and has been merged, it looks like this issue can be closed unless there is anything else outstanding.

**Comment by benjdlambert** [comment]
Closing! :pray:
