### ISSUE TITLE
Help wanted: Improving API Reference

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#7162]
We just merged #7150, which finally gives us a working, albeit MVP, [API reference](https://backstage.io/docs/reference/). As you might [notice](https://backstage.io/docs/reference/plugin-catalog-react) [rather](https://backstage.io/docs/reference/core-plugin-api) [quickly](https://backstage.io/docs/reference/integration) [while](https://backstage.io/docs/reference/backend-common) [browsing](https://backstage.io/docs/reference/catalog-client) [around](https://backstage.io/docs/reference/core-app-api), it needs a lot of work.

From our end we'll all chip in on improving the documentation, but this is also an excellent opportunity if you're looking for ways to contribute to the Backstage! 🎉

There's plenty of low-hanging fruit that doesn't require you to get too familiar with the project, and we're happy for any help we can get!

Below are instructions for getting started and some guidelines for how to write good looking documentation, useful for anyone that wants to dive in :grin:

# 🙏 Thank you

A list of contributions towards this so far:

- #7375 (@szubster)
- #7381 (@szubster)
- #7437 (@PhakornKiong)
- #7457 (@PhakornKiong)
- #7610 (@jluk-box)
- #7825 (@alexcurtin)
- #7862 (@jluk-box)
- #8315 (@adamdmharvey)
- #8534 (@lukzerom)

# 🏃 Getting Started

To preview the documentation locally you need to have the microsite development build up and running, and also build the API docs whenever you make any changes:

```bash
cd microsite
yarn install # if you haven't already
yarn start # leave this running and open a separate terminal

# new terminal, from the project root
yarn install # the root and microsite have separate yarn installs, it's needed in both
yarn build:api-docs # this generates `docs/reference`, re-run this whenever you want to update the docs
``` 

Once you have the microsite up and running and the docs are built, you can navigate to http://localhost:3000/docs/reference to preview the docs.

# 📜 Guidelines

We use [API Extractor](https://api-extractor.com/pages/overview/demo_docs/) to generate our documentation, which in turn uses [TSDoc](https://github.com/microsoft/tsdoc) to parse our doc comments.

The doc comments are of the good ol' `/** ... */` format, with tags of the format `@<tag>` used to mark various things. The [TSDoc website](https://tsdoc.org/) has a good index of all available tags.

There are a few things to pay attention to to make the documentation show up in a nice way on the website...

## Use the `function` keyword to define components

API documenter doesn't have any special handling of React components. In order to still provide documentation for them that looks decent, we opt for using the `function` keyword to define components. This will make the components show up among the list of functions in the API reference, and are then easily discoverable through the `(props)` args (which you should be sure to include!).

![image](https://user-images.githubusercontent.com/4984472/133120461-59d74c3e-ebd9-44f9-900d-cc30f54a3cd2.png)

```ts
/**
 * Properties for ErrorPanel.
 */
export interface ErrorListProps {
  ...
}

/**
 * Renders a warning panel as the effect of an error.
 */
export function ErrorPanel(props:ErrorPanelProps) {
  ...
}
```

## Do not destruct parameters in public methods

If the parameters of a function are destructed in the parameter list, they will show up in the documentation like this:

![image](https://user-images.githubusercontent.com/4984472/133117011-3e6cb6da-40dd-450e-8d33-51bdcf412e08.png)

Instead prefer to use a single parameter variable and then move the destructuring into the function body instead, which will look much nicer:

![image](https://user-images.githubusercontent.com/4984472/133120542-d648de43-5495-43a8-b532-f5e6f6ab736e.png)

Also be sure to check that the type used by the parameter is exported, as it otherwise won't be discoverable through documentation.

## Use `@remarks` to split long descriptions

The API reference has an index of exported symbols for each package, which uses a short description, while clicking through to the page for a symbol shows the full description. By default all descriptions are considered "short", and you have manually add a divider where the description should be cut off using the `@remarks` tag.

```ts
/**
 * This function helps you create a thing.
 *
 * @remarks
 *
 * Here is a much longer and more elaborate description of how the 
 * creation of a thing works, which is way too long to fit on the index page.
 */
function createTheThing() {
}
```

## Use `@param` to document parameters

When using the `@param` tag to document a parameter it will show up in the **Parameters** section:

![image](https://user-images.githubusercontent.com/4984472/133120977-64004074-0afb-4e8a-9a2a-c846f04eb3d9.png)

Be sure to include a `-` after the parameter name as well as [required by TSDoc](https://tsdoc.org/pages/tags/param/), or you'll get a warning in the API report.

```ts
/**
 * Generates a PluginCacheManager for consumption by plugins.
 *
 * @param pluginId - The plugin that the cache manager should be created for. Plugin names should be unique.
 */
forPlugin(pluginId: string): PluginCacheManager {
  ...
}
```

## Fill in missing references using `{@link ...}`

Not all types are detected and referenced on the documentation page. Most notably variables, and therefore ApiRefs, will not have clickable links to other symbols that they reference. We instead fill in this missing information using inline `{@link ...}` tags in the description:

```ts
/**
 * {@link ApiRef} for the {@link DiscoveryApi}.
 */
export const discoveryApiRef: ApiRef<DiscoveryApi> = createApiRef(...);
```

![image](https://user-images.githubusercontent.com/4984472/133123632-d00cefd9-a70f-43f6-8f14-40c253554ee1.png)

**Comment by san-coding** [comment]
Hey , can I work on this issue?

**Comment by Rugvip** [comment]
@san-coding Absolutely, thank you! 👍

The scope is a bit too wide to assign to a single person, so I think the best way is to make small quick PRs to reduce the possibility of stepping on each other's toes.

**Comment by aemann2** [comment]
I'm brand new to this project and this issue seems like a good way to get acquainted. @Rugvip, will follow your advice on small PRs.

**Comment by EugeneGohh** [comment]
I am getting into this, will follow @Rugvip's advice.

**Comment by EugeneGohh** [comment]
I followed every step in getting started section but after running `yarn build:api-docs`, I got an error saying:

```
<--- Last few GCs --->

[5808:000001E596B78BC0]   216511 ms: Scavenge (reduce) 2044.0 (2054.1) -> 2043.2 (2054.4) MB, 7.2 / 0.0 ms  (average mu = 0.298, current mu = 0.239) allocation failure
[5808:000001E596B78BC0]   220672 ms: Mark-sweep (reduce) 2044.1 (2051.4) -> 2043.1 (2052.4) MB, 4146.3 / 
0.0 ms  (average mu = 0.175, current mu = 0.073) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7B5B34BDF napi_wrap+111007
 2: 00007FF7B5AD8166 v8::base::CPU::has_sse+59910
 3: 00007FF7B5AD9066 node::OnFatalError+294
 4: 00007FF7B63B217E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7B6396F4D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF7B624008C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
 7: 00007FF7B624B4AA v8::internal::Heap::ProtectUnprotectedMemoryChunks+1258
 8: 00007FF7B62485E9 v8::internal::Heap::PageFlagsAreConsistent+2457
 9: 00007FF7B623D181 v8::internal::Heap::CollectGarbage+2049
10: 00007FF7B623B385 v8::internal::Heap::AllocateExternalBackingStore+1349
11: 00007FF7B625B7FB v8::internal::Factory::NewFillerObject+203
12: 00007FF7B5F8A2D1 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1409
13: 00007FF7B643B03D v8::internal::SetupIsolateDelegate::SetupHeap+465325
14: 00007FF7B643BFB7 v8::internal::SetupIsolateDelegate::SetupHeap+469287
15: 00007FF7B64691CB v8::internal::SetupIsolateDelegate::SetupHeap+654139
16: 00007FF7B64B2039 v8::internal::SetupIsolateDelegate::SetupHeap+952745
17: 00007FF7B63D34E2 v8::internal::SetupIsolateDelegate::SetupHeap+40530
18: 00007FF7B63D34E2 v8::internal::SetupIsolateDelegate::SetupHeap+40530
19: 00007FF7B63D34E2 v8::internal::SetupIsolateDelegate::SetupHeap+40530
20: 00007FF7B63D34E2 v8::internal::SetupIsolateDelegate::SetupHeap+40530
21: 00007FF7B63D34E2 v8::internal::SetupIsolateDelegate::SetupHeap+40530
22: 00007FF7B63D34E2 v8::internal::SetupIsolateDelegate::SetupHeap+40530
23: 00007FF7B63D34E2 v8::internal::SetupIsolateDelegate::SetupHeap+40530
24: 00000155864F658C
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Rugvip** [comment]
@EugeneGohh ah shiet, haven't seen that error during the docs build, but can happen sometimes.

Are you running at least Node.js v14 or v16? There's been some changes to the default heap size that should help you out.

**Comment by EugeneGohh** [comment]
> @EugeneGohh ah shiet, haven't seen that error during the docs build, but can happen sometimes.
> 
> Are you running at least Node.js v14 or v16? There's been some changes to the default heap size that should help you out.

I am running on Node.js v14.17.5.

**Comment by EugeneGohh** [comment]
> @EugeneGohh ah shiet, haven't seen that error during the docs build, but can happen sometimes.
> 
> Are you running at least Node.js v14 or v16? There's been some changes to the default heap size that should help you out.

I bumped Node.js to v14.18.0. It's the latest version of LTS. Updated to latest version, still same.

**Comment by khoaHyh** [comment]
> > @EugeneGohh ah shiet, haven't seen that error during the docs build, but can happen sometimes.
> > Are you running at least Node.js v14 or v16? There's been some changes to the default heap size that should help you out.
> 
> I bumped Node.js to v14.18.0. It's the latest version of LTS. Updated to latest version, still same.

My case was `yarn tsc` which gave me the same error. I was able to fix this on my local machine using `NODE_OPTIONS="--max-old-space-size=4096" yarn ...`.

**Comment by lukzerom** [comment]
Hey @Rugvip , could i work on  this package -> @backstage/core-components  ? :)

**Comment by Rugvip** [comment]
@lukzerom sure! 😁, same recommendations as above apply, best look at a couple of things to fix at a time rather than everything at once :p

**Comment by lukzerom** [comment]
@Rugvip Okey, sure! 😌

**Comment by lukzerom** [comment]
https://github.com/backstage/backstage/pull/8534 First pack of some components 😉

**Comment by cmlino** [comment]
Is there still work to be done on this issue?

**Comment by adamdmharvey** [comment]
As of today, the blanks on the API reference are few and far between:

https://backstage.io/docs/reference/

There's still some work to do, but I might recommend in terms of a focused effort to  "improve the API reference", it is vastly improved and as new plugins and core packages get added, they'll continue to need to get their documentation added. There will always be "low hanging fruit 🍒 " for open source contributors to jump in and help improve that.

I recommend we close?
<img width="820" alt="image" src="https://user-images.githubusercontent.com/33203301/190174864-4ca2c9ac-dff1-4ee7-8928-e0e298e1a368.png">

**Comment by Rugvip** [comment]
@adamdmharvey, thank you, agreed! 👍 

The guidelines here can always be found at https://github.com/backstage/backstage/blob/master/STYLE.md#documentation-guidelines
