### ISSUE TITLE
useEntity hook indefinitely loading some time after @backstage/plugin-catalog-react v0.4.2

### ISSUE THREAD

**Issue by askreet** [backstage/backstage#7168]
## Expected Behavior

Having multiple components on an entity page that use the `useEntity` hook should each receive valid `entity` members.

## Current Behavior

The `entity` variable is undefined and `loading` is true for any elements using >0.4.2 of `@backstage/plugin-catalog-react`.

## Possible Solution

Unknown.

## Steps to Reproduce

Create a second React component function that calls `useEntity` and displays basic information about it, such as its name.

## Context

I created a new plugin and the linter prompted me to explicitly depend on `@backstage/plugin-catalog-react`. I ran `yarn add @backstage/plugin-catalog-react` in `packages/app` by mistake, then in `plugin/my-plugin`, resulting in updating from `v0.4.2` to `v.0.4.5` and all components except `EntityAboutCard` to be stuck indefinitely in loading. Updating both `package.json` files to `v0.4.2` and running `yarn install` and redeploying resolved my issue.

With no evidence whatsoever, the memoization item in the `v0.4.4` changelog sounds like it may be related?

## Your Environment

- NodeJS Version (v12): v12.22.6
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu (unknown)
- Browser Information: Google Chrome

**Comment by askreet** [comment]
According to @timbonicus on Discord, this may not be a regression, but the result of me having multiple versions of `@backstage/plugin-catalog-react` loaded at the same time. Feel free to close this out or let me know if there's anything specific I can provide to help.

**Comment by Rugvip** [comment]
@askreet Indeed! This is being fixed by #7149, so this problem should disappear in future versions.

Will close since there's nothing left to do here but wait and try to deduplicate existing version x)
