### ISSUE TITLE
Could you provide Backstage image on DockerHub?

### ISSUE THREAD

**Issue by chendelin1982** [backstage/backstage#7173]
## Expected Behavior

`docker run -it -p 7000:7000 backstage` for testing Backstage 

## Current Behavior

user need npm build and docker build, it very difficult

**Comment by timbonicus** [comment]
I understand this wish, and indeed I'd love to see the same! It might be possible long-term, but at the moment this would essentially just be the [demo site](https://demo.backstage.io).

The thing preventing this is customization - adding integrations and access tokens specific to your company, installing plugins, setting up backend services to have in your installation. This simply isn't possible to do within a pre-built Docker image the way Backstage is set up today. I can imagine it, but there's a lot of change needed to get there.

The value I see is having a quick way to get started and kick the tires, even if we expect that many adopters would eventually "eject" and have a need or desire to create a full application and deployment. Rest assured, having an easier road to try Backstage weighs heavily on our minds. I hope that you'll stick it through and give Backstage a try even without this convenience!
