### ISSUE TITLE
how to delete the additional templates

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#7200]
Hi,

Why did my templates include other template? Actually I just defined one template in `app-config`, but there are 6 templates included in the website. `Onboarding new service` is our own.

I am wondering how to delete other five templates.
![image](https://user-images.githubusercontent.com/56138162/133509368-0c4882c9-5e02-423e-be0e-6ae58ad3c92c.png)
![image](https://user-images.githubusercontent.com/56138162/133509403-56b0bfc8-2c24-4ca6-b1af-dab0b89b01c0.png)

**Comment by timbonicus** [comment]
These are the default templates that serve as examples when creating a new Backstage app. They can be removed by [unregistering the templates from the catalog](https://github.com/backstage/backstage/discussions/5315#discussioncomment-605929).

**Comment by chuliang014** [comment]
Hi @timbonicus,  seems my catalog page doesn't have a dropdown. 
![image](https://user-images.githubusercontent.com/56138162/133840101-a29bd38a-83c0-4fc6-b1df-e6bffb58974c.png)

**Comment by timbonicus** [comment]
@chuliang014 Ah, the dropdown for `kind` was added in `plugin-catalog: 0.6.14` so perhaps you're on an earlier version.

To work around this, if you don't want to upgrade at this time, you can either go straight to the template URL (e.g. `/catalog/entities/by-name/template/default/<name>`), or go to `/search` which had a kind filter before this.
