### ISSUE TITLE
Bring back the multi-lingual greeting to the home page

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#7225]
## Feature Suggestion

![image](https://user-images.githubusercontent.com/648527/133742557-19669c9e-62e0-48c0-8a2a-5f6ef87e915b.png)

In the past, the home (back than the catalog page) had a multi lingual welcome message to greet the user with different languages and greetings depending on the time of the day. That gave Backstage a nice playful touch! But it also confused some users, causing it to be removed from the catalog page in #5483.

For the new home page (#5416), we should (optional) bring that feature back.

## Possible Implementation

Implement a component that shows the message. ~~The home page header might have to be extended to show components instead of strings for the title~~ (already done!). The code for the message itself is [still in the repo](https://github.com/backstage/backstage/tree/master/plugins/welcome/src/utils) - but unused.

**Comment by freben** [comment]
Yep for sure it should be available for voluntary inclusion at least right? :)
