### ISSUE TITLE
Type 'Dictionary<string | undefined>' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by cbwilliamsnh** [backstage/backstage#7234]
Build error on line 39 of plugins/auth-backend/src/lib/oauth/helpers.ts

## Expected Behavior

Code should build

## Current Behavior

Code doesn't build

## Possible Solution

haven't started exploring one

## Steps to Reproduce

Try to build using:

❯ node --version
v14.17.5

on MacOS Catalina

**Comment by cbwilliamsnh** [comment]
Proposed fix that is working:

`export const encodeState = (state: OAuthState): string => {
  const _undefined = undefined
  const stateString = new URLSearchParams(
    pickBy(state, value => value !== _undefined),
  ).toString();

  return Buffer.from(stateString, 'utf-8').toString('hex');
};`

**Comment by Rugvip** [comment]
Thank you for reporting!

You likely have some difference in your setup since we're not seeing this error on the latest master, any idea of what that might be?

**Comment by cbwilliamsnh** [comment]
No idea. I'm working on a MacBook with node.js 14.xxx and everything else up to date. If no one else is having the issue, I'll just patch the file as I build.

**Comment by Rugvip** [comment]
Hmm, strange, but alright. Are you fine with closing this issue for now and then revisit if anyone else has the same issue?

**Comment by cbwilliamsnh** [comment]
Closing issue and will revisit if others have the same issue.
