### ISSUE TITLE
Deprecated Golang template linked from newly scaffolded Backstage app

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#7236]
When scaffolding a brand new Backstage app off `npx @backstage/create-app` there's a warning upon startup about an entry that can't be read.

Specifically, it relates to this linked Golang template:

https://github.com/backstage/backstage/blob/f38ac1a4e0eca7dc0e390a3a223fc9685e8ae875/packages/create-app/templates/default-app/app-config.yaml.hbs#L110-L112

And that template is still a legacy apiVersion `v1alpha`:

https://github.com/spotify/cookiecutter-golang/blob/54d0c7738ea8d9125094f09902cd5636aaa63491/template.yaml#L1-L6

## Expected Behavior

No catalog warnings processing catalog imports when scaffolding a brand new app.

## Current Behavior

Two warnings in the logs of a fresh app:

```
[1] 2021-09-18T01:33:11.433Z catalog warn No processor recognized the entity as valid, possibly caused by a foreign kind or apiVersion type=plugin
[1] 2021-09-18T01:33:11.433Z catalog warn No processor recognized the entity as valid, possibly caused by a foreign kind or apiVersion type=plugin entity=template:default/golang-starter
```

## Possible Solution

So it would seem to me two options:

1. Simply remove this linkage from the scaffolded template for newly created apps
2. Migrate that `spotify/cookiecutter-golang` template to use the new template following https://backstage.io/docs/features/software-templates/migrating-from-v1alpha1-to-v1beta2#migrating-a-v1alpha1-template , and assuming there would't be any apps out there any longer who may have missed the deprecation notice.

Before opening a PR, thought I'd see if there were preferences out there?

## Steps to Reproduce

1. Scaffold a new app: `npx @backstage/create-app`
2. Make no customizations but start the app up, a la `yarn dev`
3. Review logs

## Your Environment

- NodeJS Version (v12): 14.17.6
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS Big Sur
- Browser Information: Safari 14

**Comment by freben** [comment]
Indeed! This one just needs to be migrated. I'll see if I can get that done (or remove it, even).
