### ISSUE TITLE
Environment specific "Create Component"

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#7240]
## Expected Behavior

If we use the below code
process.env.NODE_ENV under 

```
export const Root = ({ children }: PropsWithChildren<{}>) => (
  <SidebarPage>
    <Sidebar>
      <SidebarLogo />
      <SidebarSearch />
      <SidebarDivider />
      {/* Global nav, not org-specific */}
      <SidebarItem icon={HomeIcon} to="catalog" text="Home" />
      <SidebarItem icon={ExtensionIcon} to="api-docs" text="APIs" />
      <SidebarItem icon={LibraryBooks} to="docs" text="Docs" />
if(process.env.NODE_ENV !== 'production') {
      <SidebarItem icon={CreateComponentIcon} to="create" text="Create..." />
}
      {/* End global nav */}
      <SidebarDivider />
      <SidebarItem icon={MapIcon} to="tech-radar" text="Tech Radar" />
      <SidebarDivider />
      <SidebarSpace />
      <SidebarDivider />
      <SidebarSettings />
    </Sidebar>
    {children}
  </SidebarPage>
```

This should work

## Current Behavior

The expected behaviour is that irrespective of the different environments, the create component is visible

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by freben** [comment]
`process.env` is a backend thing only, it doesn't apply in frontend scenarios. I am not sure what you want to achieve here, you say that it SHOULD be visible no matter what env you are in?

If you want to have different frontend behaviours in different envs, you can use different overlaying config files such as app-config.yaml plus app-config.production.yaml and supply those with --config arguments at startup

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Yes, then I thought we can create environment variables under app-config and app-config-production yaml files and pass them accordingly, but that doesn't seem to work as well . Please see #7243

**Comment by shanthisagar-dhanya-kumar-db** [comment]
My main aim is based on whether the environment is either production, dev or uat, toggle the "Create Component", "Register the Component" in the front end.

**Comment by freben** [comment]
Alright, let's see where #7243 leads us then, and close this if it solves the problem.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
I was able to achieve it using the things mentioned under #7243 . Thanks

**Comment by Rugvip** [comment]
Glad to hear! Is it alright to close this issue?
