### ISSUE TITLE
configSchema in package.json for new environment variable not working

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#7243]
I need to add a new property lets say "environment" under app-config.yaml but before that  I have added the below in the main package.json

```json
"configSchema": {
    "type": "object",
    "properties": {
      "environment": {
        "type": "string",
        "description": "Environment Value",
        "visibility": "frontend"
      },
      "required": ["environment"]
    }
 }
```

But when I use the below code 

```ts
const environment = () => {
  const env = useApi(configApiRef);
  console.log(env.getString('environment'));
  return env.getString('environment');
}
```

It doesn't print the value stored under environment variable

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by freben** [comment]
Hm I wonder if maybe this isn't possible in the project root package.json. All of the schema declarations I've seen so far have been in `plugins/x` or `packages/x`. They have also [had the schema declaration and a title](https://github.com/backstage/backstage/blob/9375de0d6ca10da17a4b1ae13978bdfbeefb33da/packages/cli/package.json?plain=1#L164), but I don't think that's enforced. Maybe try adding it nonetheless.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Hi. Thanks this worked. I have added this in packages/app folder and it worked

**Comment by Rugvip** [comment]
👍, I felt it was a bit too confusing that the initial attempt didn't work, so fixing that in #7326
