### ISSUE TITLE
[scaffolder] Allow for mono-repo templates with template inheritance

### ISSUE THREAD

**Issue by Pike** [backstage/backstage#7246]
I'd like to be able to use template inheritance when creating scaffolder templates. That way, more organizational parts of a project could be centrally maintained, and adapted to concrete templates.

This would be an alternative to having one big template with a lot of options.

One benefit I see to multiple templates is that you can document them individually, which should make it easier to decide what you want. Another one would be that the form can be reduced to the questions that matter to a particular template.

Related issue could be #6964.

## Feature Suggestion

nunjucks supports template inheritance, but only finds templates in the specified lookup directories. If we want to support that, we'll need to add the lookup root, and we need to put the base templates into the same template repository as the inheriting ones. Which led me to a mono-repo for templates, and each template is then looked up in a source directory.

## Possible Implementation

Add a `sourceDir` parameter to `fetch:template` to pick a subdirectory, and pass the `templateDir` to `nunjucks.configure` as first parameter.

**Comment by Pike** [comment]
@benjdlambert I have a local patch, would it help if I pushed that into a PR?

**Comment by benjdlambert** [comment]
Hey - sorry for not getting back soon on this, it's been on my list but had a lot of other stuff to do. I'd really like to try and keep the templating super simple, and not rely on the more `view` templating features that `nunjucks` supports. Feels like we would couple ourselves and templates to close to them. Maybe you could use a `custom` action instead and wrap up that in a more `nunjucks` specific name and action.
