### ISSUE TITLE
Backstage Homepage Template

### ISSUE THREAD

**Issue by KatherineZhou** [backstage/backstage#7249]
## 🗒 General

Hi! We'd love to bring the Backstage homepage to life as a template for adopters to use and modify. This is quite similar to the Backstage homepage that we utilise at Spotify.

Building on top of the awesome work done for #6486, we'd love to provide a structured template using composable cards for folks customise for their teams. 

From user research done at Spotify with our own Backstage users, we've found that most users open Backstage already knowing what they want to access. With that knowledge, we've incorporated a direct search bar above the fold. Adopters are free to replace the Backstage art above the search with their own company logos.

Guidelines for the homepage
1. Ideally should have a prominent search bar for users to quickly get to what they are looking for
2. Should not be overwhelming - we've found that our users rarely scroll too much on the homepage, so most content should 'above the fold'. We recommend 4 composable cards, maximum.
3. Composable cards can contain a variety of content. Some really great suggestions were presented in #5416 

![Main](https://user-images.githubusercontent.com/16808998/134015227-28a3d39a-854c-4234-836c-018f20165698.png)

## 💻 Usage

In our own instance of Backstage at Spotify, we've also leveraged the "Quick Access" section, which includes sections like 'Frequently Visited' and 'Recently Visited' - these two were especially requested during our user research sprints. This card is an optional part of the template, as well as the toolkit section.

 
![Generic](https://user-images.githubusercontent.com/16808998/134015194-9d0efc09-74bd-495f-8aac-4a47128317be.png)

![Suggested Template Items](https://user-images.githubusercontent.com/16808998/134021142-1674575b-3fb2-444b-9ecb-0d962ac2623e.png)

Ideally, there would be an introductory, tutorial experience for this new homepage as well (alluded to in #6998), similar to the following.

Some guidelines for tutorials:
1. Should be less than 5 steps.
2. Must have the option to skip.
3. Explanatory copy should be less than 3 sentences
4. Must include 'back', 'next', and 'finish' buttons.

![Tutorial 1](https://user-images.githubusercontent.com/16808998/134020424-21992573-fb98-4a7d-a365-7581d4f85494.png)
![Tutorial 2](https://user-images.githubusercontent.com/16808998/134020420-1d427705-4e8c-4b04-9ae4-98ae43f7038e.png)
![Tutorial 2](https://user-images.githubusercontent.com/16808998/134020949-e7fb6408-d9c8-4f1f-97ff-db1834c8892a.png)
![Tutorial 1](https://user-images.githubusercontent.com/16808998/134020955-17bf45d9-b20f-4127-8494-93cca6251a60.png)

![Tutorial 3](https://user-images.githubusercontent.com/16808998/134020937-d1361b45-6583-4631-ba23-2b3ef483323b.png)

## 📐 Specs
[Figma link](https://www.figma.com/file/nUaAw56hTgC0RIOYkuLSrB/Backstage-Design-System?node-id=2185%3A2978) where you can duplicate the template and view additional guidelines. 

<img width="1149" alt="Screenshot 2021-09-20 at 4 49 45 PM" src="https://user-images.githubusercontent.com/16808998/134023205-3e02ddae-0413-4bd5-9436-e919d906b233.png">

## 🔮 Future
Any suggestions or feedback? Let us know. We also hope to add this to our Storybook.

**Comment by BenDu89** [comment]
Hi @KatherineZhou - when i try to access the Figma link, i get the following error message: File not found

Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions.

**Comment by KatherineZhou** [comment]
hmm thanks for raising that! you can access it [here](https://www.figma.com/community/file/850673348101741100) --> you can duplicate this file and find the 'Homepage' page on the left hand side (the 'pages' column)

<img width="1419" alt="Screenshot 2021-09-21 at 11 08 15 AM" src="https://user-images.githubusercontent.com/16808998/134144106-ecb4504a-1499-4198-888c-cfca0c285f0b.png">

<img width="1143" alt="Screenshot 2021-09-21 at 11 08 40 AM" src="https://user-images.githubusercontent.com/16808998/134144085-202da55a-6c95-4940-bd7a-e9d414d067ed.png">

**Comment by BenDu89** [comment]
That works - I guess the link in the initial post is broken - Thanks for helping out :-)

**Comment by regicsolutions** [comment]
Great work! Looks awesome, I don’t know why but this landscape is still my favorite 😀

<img width="776" alt="B47715CB-7ECD-4785-9BDE-DDEDE6AEB084" src="https://user-images.githubusercontent.com/6157895/134266193-af96b3a5-ddeb-4530-9863-9ec9386beb0e.png">

**Comment by deepak-bhardwaj-ps** [comment]
It would be nice to have the home page be more like a dashboard with dynamic widgets that user can configure. React Grid Layout could be a possible solution - https://www.npmjs.com/package/react-grid-layout. 

Here is a nice demo: https://react-dashboard-demo.cube.dev/

**Comment by adamdmharvey** [comment]
I love the quick links and the tools! That could drive a ton of value.

As some additional feedback, with some of the first few internal shows I've done of Backstage, there was a definite "what is the value to me of this Backstage thing" perception. Given that, we played around with some hero-style cards which I think in my mind would be ideal to be there, but maybe be dismissible.  That is, if I have a 1000 person org, then these cards would be most useful to the broader population, but as teams became more and more familiar with Backstage, as the "rumors of its value" as a product became to permeate the org, then users should be able to ditch the hero cards and straight back into the higher value things like search (discoverability), quick access, etc.

Given that, we just roughly had drafted this:

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/33203301/137327746-0c645ad2-7ddd-48dd-8385-ceebac318d5d.png">

**Comment by katz95** [comment]
Featuring some variations on a new template for the homepage that shows more metrics and data visualizations - these are suggested layouts, you would be able to modify as you wish! I've also utilized a darker theme as proposed in #7633 as a trial in these mockups. 

Let me know your thoughts and if you have any other requests! Our homepage is composable, so you'd be able to modify these as you see fit for your organization. 

We also hope to get some help building out these templates for our Storybook.

![Main](https://user-images.githubusercontent.com/61153904/141287276-fb3dfb91-5723-40e6-859e-7b1b90cd17f7.png)

![Main-2](https://user-images.githubusercontent.com/61153904/141287269-57d52427-3e01-433a-aaed-f9b9629e0a78.png)
![Main-3](https://user-images.githubusercontent.com/61153904/141287273-e35334e3-2099-4c74-a638-ecd74f7bbe67.png)

![Main-1](https://user-images.githubusercontent.com/61153904/141287257-e569aa8b-65ba-4c9d-92a0-25a4ef12bc8d.png)
.

**Comment by regicsolutions** [comment]
Wow looks awesome!!

**Comment by katz95** [comment]
Thanks!! Let us know if there are any other templates you'd like to see. Also if there are any folks that want to help us build out these starter templates for the home page, please let me know and we can collaborate together!

**Comment by emmaindal** [comment]
Assigning myself to this issue @KatherineZhou as I'll start implementing a storybook template of the first version. Then we will create follow up issues after than as discussed!

**Comment by emmaindal** [comment]
I'll now close this issue, as we have both documentation of how to add a custom Homepage here https://backstage.io/docs/getting-started/app-custom-theme#custom-homepage and a collection of templates (only one for now) on our storybook under [Plugins > Home > Templates](https://backstage.io/storybook/?path=/story/plugins-home-templates). If you want to contribute with more templates, please open a PR with additions to the storybook collection or open an issue suggesting your template. Let me know if you think we should leave this issue open @KatherineZhou until we have more templates available and we can re-open it again!
