### ISSUE TITLE
Filters not cleared when switching between kinds in the Software Catalog

### ISSUE THREAD

**Issue by johanhammar** [backstage/backstage#7264]
As the title says filters are not cleared when switching between kinds in the Software Catalog. I.e filter for tags for components then switch to another kind, i.e domains, and the tags filter is still active

## Expected Behavior

Filters should be cleared, atleast when switching to a kind that does not have the filter.

## Current Behavior

Filters are not cleared. See screenshots below

## Possible Solution

N/A

## Steps to Reproduce

Tested in release-2021-09-16 and also reproducible at https://demo.backstage.io 

1. Go to the Software Catalog at https://demo.backstage.io
2. Select a tag, i.e 'go'

![2021-09-21 11_24_37-Window](https://user-images.githubusercontent.com/69011/134148720-c6259105-5b77-4dc1-89ab-51c41104f4ca.png)

3. Switch to another kind, i.e 'Domains' and the filter is still active

![2021-09-21 11_26_39-Window](https://user-images.githubusercontent.com/69011/134148790-a71ac7da-4d5b-4864-b103-e8453506908e.png)

## Context

See screenshots above

## Your Environment

- NodeJS Version (v14): N/A
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 20H2
- Browser Information: Firefox 92.0 & Microsoft Edge 93.0.961.52

**Comment by Rugvip** [comment]
Thank you for reporting! 👍 

Definitely agree that any field that disappears when you switch kind should be reset or at least not applied. If it's easy to implement I think not applying those filters could be slightly nicer, but could skip that if it's a big hassle imo.

**Comment by Guzzler** [comment]
I'd like to pick this up if possible @Rugvip. What approach would you recommend? Do you think clearing the filters is more consistent a behaviour or not applying them?

**Comment by Rugvip** [comment]
I would suspect that keeping the filters intact but not applying them would provide a nicer UX when switching around, but not an expert in that area :grin:

I think it could be a good initial approach and then we see if it's simple enough to implement or if we gotta jump through a bunch of hoops

**Comment by N426ER** [comment]
We're having this issue as well. Commenting to keep stalebot at bay.
