### ISSUE TITLE
Conditional Value Checking In Software Templates

### ISSUE THREAD

**Issue by asummers** [backstage/backstage#7274]
## Feature Suggestion

Currently, the parameters set via software templates can be checked for truthiness, and that logic can be present both within an `if:` directive within a step, as well as in e.g. string contents for conditionally creating parts of the string as in a PR description. Yay! However, there does not seem to be a way to check this value against another string as Nunjucks allows you to do. Handlebars (unsure why we have ANOTHER template tool here...) balks at the `{{#if parameters.foo == "bar"}}` syntax with a stack trace in the `handlebars.compile` function balking at the `EQUALS` token, and `if: {{parameters.foo}} == "foo"` and similar returns truthy always.

Given these constraints, I tried using JSON Schema dependencies and `oneOf` s with a bunch of hidden fields to allow me to coerce the string values to booleans, with `enum: true/false` and `default: true/false` on a form element here via `isFoo` and similar fields with mutually exclusive values between the sections. This almost works. If someone fills out the form from the top and does not go back to the conditional section and change any of the conditional values, this works. But if they ever go back to the thing that was being switched on, the form gets into a state where it cannot be submitted because the various true/false values conflict between the various sections, with no visible UI feedback. The user can `reset` their form here, but there's no indication they should have to do that when a hidden form does not have expected value. 

Happy to expand further if any of this is unclear.

## Possible Implementation

Allow switching on string and numeric values here, somehow. None of the hacky workarounds I listed allow this in a clean way.  Allowing the template to use nunjucks like the things it eventually inflates would also allow this, I believe, as we could defer to nunjucks' conditional logic implementation here.

**Comment by Fox32** [comment]
Did you try the [`eq` helper](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts#L62)? 

I don't have an example ready, but I think you use it like: `id: eq variable "constant"`

**Comment by asummers** [comment]
That seems to work!

Interestingly it does not seem to work in the `{{#if eq paramaters.foo "foo" }}` syntax, but seems to with the `if: '{{ eq parameters.foo "foo" }}` syntax.

I think this could definitely use a callout in the docs.
