### ISSUE TITLE
Ability to serve static files from a suburl

### ISSUE THREAD

**Issue by TheAschr** [backstage/backstage#7285]
## Feature Suggestion

Is it possible to serve the static files for the app under a suburl?

For example

https://DOMAIN/documentations/static/module-react-virtualized.041e2be8.js

instead of 

https://DOMAIN/static/module-react-virtualized.041e2be8.js

setting the app.baseUrl and backend.baseUrl only seem to configure the url the client can be accessed at but not the url static files.

Normally you would fix this in React by setting the environment variables PUBLIC_URL like so

```
    "build": "cross-env PUBLIC_URL=/documentation/ backstage-cli app:build",
```

but PUBLIC_URL doesn't seem to be picked up by the build process.

**Comment by OrkoHunter** [comment]
To me it looks like the `static` folder is hard coded in the webpack config.
https://github.com/backstage/backstage/blob/e1c141a2d5e426fd6fda8d0a2f0b2eaab7b2852c/packages/cli/src/lib/bundler/config.ts#L214-L217

**Comment by vinzscam** [comment]
It looks it is hardcoded also in other places: 

https://github.com/backstage/backstage/blob/9a180af86e0e694a7ed4f122d2c27a928fbc306e/plugins/app-backend/src/service/router.ts#L94

Feel free to open a PR if this is something you really need.

**Comment by freben** [comment]
Hm. That's only the local path on disk that it serves from - it's supposed to have the frontend files in `dist/static`. That should not be connected with what external HTTP route that it serves from

**Comment by freben** [comment]
If I understand the ask correctly, this would be a matter of choosing a different root route for this line in your backend: https://github.com/backstage/backstage/blob/master/packages/backend/src/index.ts#L131

**Comment by Rugvip** [comment]
I think what we're really looking for is the ability to configure the URL that the frontend expects to find the static files at right? We'd keep the `static/` folder in the build output, but you'd then want to copy those files somewhere else for the deployment.

Just for understanding, why do you need this? Given your example you should be able to serve the entire app at `https://DOMAIN/documentations`, just not serving it at `https://DOMAIN` while having static content at `https://DOMAIN/documentations/static`.

A possible implementation of this could be to add an optional `app.publicUrl` or something like that, which would resolve relative to the `app.baseUrl`. The `static/` part would likely still be hardcoded though, as in the static assets still being expected at `<app.publicUrl>/static`

**Comment by Rugvip** [comment]
Will add that in out setup we host the contents of the `static/` folder separately from the other things. The frontend is deployed with nginx with the `static/` foulder being routed out to a GCP bucket sometimes

**Comment by TheAschr** [comment]
@Rugvip 

> Just for understanding, why do you need this?

We have multiple react applications behind an nginx reverse proxy on a single domain.

`https://DOMAIN/app1`
`https://DOMAIN/app2`

When I try to apply this same technique to serve backstage under `https://DOMAIN/documentation` the index.html is able to load but not any of the JavaScript files. When I look at the network requests react is looking for the JavaScript files at `https://DOMAIN/static/JS_FILE` instead of `https://DOMAIN/documentation/static/JS_FILE` (where it is actually hosted).

An app.publicUrl configuration option would be awesome.

**Comment by Rugvip** [comment]
@TheAschr You should be able to use the following in your app config to support that:

```yaml
app:
  baseUrl: https://DOMAIN/documentation
```

**Comment by Hanyman8** [comment]
Hello, we are not able to change to change the static file.

After configuring APP_CONFIG_app_baseUrl= http://DOMAIN/our-catalog/
it is still https://DOMAIN/static/ and not http://DOMAIN/our-catalog/static/

**Comment by mist3r3** [comment]
Any news on this issue? I can't see any solution for that...

**Comment by Rugvip** [comment]
@mist3r3 yep! see #13872. It can already be done by setting the `app.baseUrl` config at build time though.
