### ISSUE TITLE
Compile errors after applying patches

### ISSUE THREAD

**Issue by cbwilliamsnh** [backstage/backstage#7286]
I'm using `waf` to apply a collection of patches to `backstage` prior to compiling it. The patches are all successfully applied but the build process has two compile errors.

## Expected Behavior

`backstage` should compile (and run) after the patches are applied.

## Current Behavior

I get the following two errors during the build process:

```
plugins/auth-backend/src/lib/oauth/helpers.ts:39:5 - error TS2345: Argument of type 'Dictionary<string | undefined>' is not assignable to parameter of type 'string | Record<string, string> | string[][] | URLSearchParams | undefined'.
  Type 'Dictionary<string | undefined>' is not assignable to type 'string'.

39     pickBy(state, value => value !== undefined),
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins/catalog-import/src/components/StepPrepareSelectLocations/StepPrepareSelectLocations.tsx:55:34 - error TS7006: Parameter 'l' implicitly has an 'any' type.

55     prepareResult?.locations.map(l => l.target) || [],
                                    ~


Found 2 errors.

error Command failed with exit code 1.
```

Note that neither of these files are patched!

## Context

I'm currently unable to build my `backstage` application.

## Your Environment

- NodeJS Version (v14): 14.17.5
- Operating System and Version (e.g. Ubuntu 14.04): MacOS Catalina

**Comment by OrkoHunter** [comment]
Few questions:
1. What is `waf`? 
2. What patches are you trying to apply? Is it coming from the CHANGELOGS of Backstage packages?
3. What version of [auth-backend](https://github.com/backstage/backstage/blob/master/plugins/auth-backend/CHANGELOG.md) are you on? Try bumping it and see if the errors disappear?

**Comment by cbwilliamsnh** [comment]
@OrkoHunter  I hope this helps a bit:

1. [waf](https://waf.io/) is a meta-build system
2. I created the patch files by creating a private branch from `master`, applying a series of edits/commits to that branch and running `git format-patch master`. The waf build then clones a specific commit on `master` and automatically applies the patch files before `backstage` is compiled. The patches do things like changing the OAuth app to AzureAD, add our corporate theme, etc. This is done so I don't have to fork the `backstage` repo and constantly deal with new commits on master that break my customizations.
3. I'm using whatever is in the `package.json` files in `'backstage`

**Comment by cbwilliamsnh** [comment]
This is the rather lengthy build command `waf` issues:

```yarn run tsc && yarn run build: bsdev/cypress/package.json bsdev/microsite/package.json bsdev/package.json bsdev/packages/app/package.json bsdev/packages/backend/package.json bsdev/packages/backend-common/package.json bsdev/packages/backend-test-utils/package.json bsdev/packages/catalog-client/package.json bsdev/packages/catalog-model/package.json bsdev/packages/cli/asset-types/package.json bsdev/packages/cli/package.json bsdev/packages/cli-common/package.json bsdev/packages/codemods/package.json bsdev/packages/config/package.json bsdev/packages/config-loader/package.json bsdev/packages/core-app-api/package.json bsdev/packages/core-components/package.json bsdev/packages/core-plugin-api/package.json bsdev/packages/create-app/package.json bsdev/packages/dev-utils/package.json bsdev/packages/e2e-test/package.json bsdev/packages/errors/package.json bsdev/packages/integration/package.json bsdev/packages/integration-react/package.json bsdev/packages/search-common/package.json bsdev/packages/storybook/package.json bsdev/packages/techdocs-common/package.json bsdev/packages/test-utils/package.json bsdev/packages/test-utils-core/package.json bsdev/packages/theme/package.json bsdev/packages/version-bridge/package.json bsdev/plugins/allure/package.json bsdev/plugins/api-docs/package.json bsdev/plugins/app-backend/package.json bsdev/plugins/auth-backend/package.json bsdev/plugins/badges/package.json bsdev/plugins/badges-backend/package.json bsdev/plugins/bitrise/package.json bsdev/plugins/catalog/package.json bsdev/plugins/catalog-backend/package.json bsdev/plugins/catalog-backend-module-ldap/package.json bsdev/plugins/catalog-backend-module-msgraph/package.json bsdev/plugins/catalog-graph/package.json bsdev/plugins/catalog-graphql/package.json bsdev/plugins/catalog-import/package.json bsdev/plugins/catalog-react/package.json bsdev/plugins/circleci/package.json bsdev/plugins/cloudbuild/package.json bsdev/plugins/code-coverage/package.json bsdev/plugins/code-coverage-backend/package.json bsdev/plugins/config-schema/package.json bsdev/plugins/cost-insights/package.json bsdev/plugins/explore/package.json bsdev/plugins/explore-react/package.json bsdev/plugins/firehydrant/package.json bsdev/plugins/fossa/package.json bsdev/plugins/gcp-projects/package.json bsdev/plugins/git-release-manager/package.json bsdev/plugins/github-actions/package.json bsdev/plugins/github-deployments/package.json bsdev/plugins/gitops-profiles/package.json bsdev/plugins/graphiql/package.json bsdev/plugins/graphql/package.json bsdev/plugins/home/package.json bsdev/plugins/ilert/package.json bsdev/plugins/jenkins/package.json bsdev/plugins/jenkins-backend/package.json bsdev/plugins/kafka/package.json bsdev/plugins/kafka-backend/package.json bsdev/plugins/kubernetes/package.json bsdev/plugins/kubernetes-backend/package.json bsdev/plugins/kubernetes-common/package.json bsdev/plugins/lighthouse/package.json bsdev/plugins/newrelic/package.json bsdev/plugins/org/package.json bsdev/plugins/pagerduty/package.json bsdev/plugins/proxy-backend/package.json bsdev/plugins/rollbar/package.json bsdev/plugins/rollbar-backend/package.json bsdev/plugins/scaffolder/package.json bsdev/plugins/scaffolder-backend/package.json bsdev/plugins/scaffolder-backend-module-cookiecutter/package.json bsdev/plugins/scaffolder-backend-module-rails/package.json bsdev/plugins/scaffolder-backend-module-yeoman/package.json bsdev/plugins/search/package.json bsdev/plugins/search-backend/package.json bsdev/plugins/search-backend-module-elasticsearch/package.json bsdev/plugins/search-backend-module-pg/package.json bsdev/plugins/search-backend-node/package.json bsdev/plugins/sentry/package.json bsdev/plugins/shortcuts/package.json bsdev/plugins/sonarqube/package.json bsdev/plugins/splunk-on-call/package.json bsdev/plugins/tech-radar/package.json bsdev/plugins/techdocs/package.json bsdev/plugins/techdocs-backend/package.json bsdev/plugins/todo/package.json bsdev/plugins/todo-backend/package.json bsdev/plugins/user-settings/package.json bsdev/plugins/welcome/package.json bsdev/plugins/xcmetrics/package.json
```

`bsdev` is the cloned `backstage/master` repo.

**Comment by Rugvip** [comment]
What version of `@types/lodash` do you end up with (`yarn why @types/lodash`)? Could be that newer or older versions have changed how `pickBy` works. Could also be worth checking your version of `typescript` as well.

I tried creating #7299 in case it would fix it, although even if it does it would be interesting to know why :grin:

**Comment by cbwilliamsnh** [comment]
> What version of `@types/lodash` do you end up with (`yarn why @types/lodash`)? Could be that newer or older versions have changed how `pickBy` works. Could also be worth checking your version of `typescript` as well.
> 
> I tried creating #7299 in case it would fix it, although even if it does it would be interesting to know why 😁

❯ yarn why @types/lodash
yarn why v1.22.1
[1/4] 🤔  Why do we have the module "@types/lodash"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@types/lodash@4.14.168"
info Reasons this module exists
   - "_project_#@backstage#catalog-model" depends on it
   - Hoisted from "_project_#@backstage#catalog-model#@types#lodash"
   - Hoisted from "_project_#@backstage#plugin-catalog-backend-module-ldap#@types#lodash"
   - Hoisted from "_project_#@backstage#plugin-catalog-backend-module-msgraph#@types#lodash"
   - Hoisted from "_project_#@backstage#plugin-catalog-backend#@types#lodash"
   - Hoisted from "_project_#@backstage#plugin-kafka-backend#@types#lodash"
info Disk size without dependencies: "3.52MB"
info Disk size with unique dependencies: "3.52MB"
info Disk size with transitive dependencies: "3.52MB"
info Number of shared dependencies: 0
✨  Done in 2.25s.

**Comment by cbwilliamsnh** [comment]
What about this error:

```
plugins/catalog-import/src/components/StepPrepareSelectLocations/StepPrepareSelectLocations.tsx:55:34 - error TS7006: Parameter 'l' implicitly has an 'any' type.

55     prepareResult?.locations.map(l => l.target) || [],
```

???

**Comment by cbwilliamsnh** [comment]
Here's the fix - make it explicit!

```
    prepareResult?.locations.map((l: any) => l.target) || [],
```
