### ISSUE TITLE
[RFC] Merge the techdocs-cli back into main repo

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#7288]
**Status:** Open for comments

## Need

The [techdocs-cli](https://github.com/backstage/techdocs-cli) was originally part of the main Backstage repo but was separated out quite a while ago. It still uses the [@backstage/techdocs-common](https://github.com/backstage/backstage/tree/master/packages/techdocs-common) package as a core dependency, which provides some of the common features of building & publishing docs sites for local mode (non CI publishing).

However, this separation has brought some friction and issues:

- It is difficult to determine how changes `techdocs-common` will affect the `techdocs-cli` since they are in separate repos. For example, introducing a new feature might be more difficult to implement in the `techdocs-cli` since it is typically run in a different environment (e.g. `CI`) which may not have the same setup/access as the full Backstage instance.
- Breaking changes can be introduced accidentally. One example is a patch level change to `techdocs-common` that is actually a minor breaking change could be picked up on the next yarn install of the `techdocs-cli` and cause a runtime error.
- It is a lengthy process to contribute a change to the `cli` which also requires changes to `techdocs-common`. This requires a PR cycle in the main repo, wait for the next release, and then another PR/release cycle for the CLI. The turnaround time could take weeks.

## Proposal

Merge the `techdocs-cli` repo code base back into this repo. This would consist of 2 packages:

- [@techdocs/cli](https://github.com/backstage/techdocs-cli/tree/main/packages/techdocs-cli)
- [@techdocs/embedded-techdocs-app](https://github.com/backstage/techdocs-cli/tree/main/packages/embedded-techdocs-app) used by the techdocs cli for previewing

Doing so would provide the following benefits:

- TypeScript tsc checks across dependencies
- Atomic changes across `techdocs-common`, the `cli` & `techdocs-backend`
- Easier to test changes in all related packages
- Ability to ship changes on the same release cadence as everything else
- The introduced packages can leverage the existing repo tooling and processes

## Alternatives

The only alternative here seems to be leave it as is. However, this doesn't solve any of the concerns/issues. Feel free to comment any additional ideas.

## Risks

- This will be a decently large lift. However, the refactoring in https://github.com/backstage/techdocs-cli/pull/89 is a good indication this shouldn't be technically difficult
- Merging the repo means that issues and existing PRs would need to be ported over to this repo. Although, there isn't a huge number so this may not be a major issue.

**Comment by iamEAP** [comment]
Another alternative (though most likely not worth pursuing) is creating a TechDocs monorepo that houses the CLI + common + backend + frontend.  ...We'd get techdocs-specific benefits, but at the expense of shared tooling, and the ability to benefit from core features in one go.

**Comment by Rugvip** [comment]
@iamEAP some day x)

**Comment by iamEAP** [comment]
And with that (#8007), we have arrived!

Thanks for kicking this off @andrewthauer.

I will be going through the process of closing out the old repo, but development can otherwise continue seamlessly in this repo.
