### ISSUE TITLE
LDAP: Add support for LDAPTLS_IDENTITY and certificate chain

### ISSUE THREAD

**Issue by julioz** [backstage/backstage#7294]
## Feature Suggestion

We would like to use the LDAP plugin for processing our org data. In my company, we rely on Google's LDAP server. My org's security team provided me with a user/password combination, plus a set of certificate (.crt) files. They also pointed me to [this page](https://support.google.com/a/answer/9089736) in order to set up access.

Backstage's code delegates calls to `ldapjs` to bind to LDAP servers, but there is no entry in the documentation (or GitHub repo, also to mention) for the role the certificate files play.
The Google documentation on the link above mentions a proxy called `stunnel` but I am hesitant to set something like that up side-by-side within my Kubernetes deployment of Backstage.

Even when using the environment variable `NODE_EXTRA_CA_CERTS` to point to the cert file, I am unable to connect to Google's LDAP server from within Backstage:
```
Processor LdapOrgReaderProcessor threw an error while reading ldap-org:ldaps://ldap.google.com; caused by LDAP bind failed for uid=<USERNAME>,ou=<OU>,dc=<DC>,dc=com, 49 InvalidCredentialsError: Incorrect password
```

When I bind (with the same credentials) through `ldapsearch` on my MacBook, connection is OK and I can query the LDAP directory:

```
LDAPTLS_IDENTITY="LDAP Client" ldapsearch -H ldaps://ldap.google.com:636 -b dc=<DC>,dc=com '(uid=<SOME_QUERY>)'
```

Note how in the second one, I am passing `LDAPTLS_IDENTITY` which points to the certificate in my keychain (done following https://support.google.com/a/answer/9089736?hl=en#zippy=%2Cldapsearch-macos), whereas for Backstage I believe that doesn't happen.

## Context

Binding to Google's LDAP server (through TLS). [Here are their docs](https://support.google.com/a/answer/9089736).

**Comment by OrkoHunter** [comment]
@TejasQ Do you have any suggestions for this one, since I remember you recently worked on the LDAP plugin? :)

**Comment by Rugvip** [comment]
I believe the missing piece here is to forward `tlsOptions` to the `ldap.createClient` from `ldapjs`. Through that you'd pass a custom `secureContext` that contains the client certificate. Just to clarify as well, it is a client certificate you're looking to add right? As in the the certificate files that you received contain a key as well?

**Comment by julioz** [comment]
@Rugvip Correct, I've received both `crt` and `key` files (note the certificates might be self-signed), and I'm also able to generate a `pem` out of these two.

**Comment by Rugvip** [comment]
Alright, well then the fix is to start forwarding the client certificate via the `tlsOptions` as discussed above. Keeping this marked as helped wanted as we're not able to prioritize it right now. I'll label it as a good first issue too, so if anyone want to take this on please reach out here and we'll help fill in the gaps.
