### ISSUE TITLE
Feature to use  multiple Proxies of same product say sonar, Jenkins etc 

### ISSUE THREAD

**Issue by skgandikota** [backstage/backstage#7295]
Most of projects use self hosted sonar, jenkins and maintain as part of BAU activity, Now after introducing backstage we got alot of  request with different sonarqube url's and jenkin's urls-  it would be great if we allow multiple proxy of same kind

**Comment by Rugvip** [comment]
I'd actually say that https://github.com/backstage/backstage/issues/5518 is the way forward here, meaning dedicated backend plugins that can handle the routing of requests.

Another option is to explore if we should power up the proxy plugin a bit more and start adding support for more dynamic routing based on entities or whatnot. That'll definitely make it a more complex plugin with configuration through code though, but that might be alright.
