### ISSUE TITLE
Improve helpers support in the template kind (include handlebars lowercase filter)

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#7310]
## Feature Suggestion

Improve helpers support in the template `handlebars` engine.

## Possible Implementation

In your `TaskWorker` file, add another `handlebars` helper:

`this.handlebars.registerHelper('lcase', value => value.toLowerCase());`

and/or

`this.handlebars.registerHelper('lcasetrim', value => value.trim().toLowerCase());`

This might be only during a transition period until you fully migrate to `nunjucks` and seems like the most simple, fast, and a proper solution without the need for workarounds.

The trimmed version is also important. In most cases, besides changing the case, we need to trim the value.

## Context

I have a situation where my template skeleton has a dynamic filenames based on the user input. For example:

`${{values.myFileName}}.yaml`

This works nicely and the file is created correctly, with the correct filename. However, the problem is that I want to control the case of the filename. To be exact, I want to have it lowercased.

From the template, where we have `handlebars` engine, I have a limited number of helpers to use therefore I cannot pass down the value in a case-controlled way like this `{{lcase parameters.myFileName}}`.

Also, something like this `${{values.myFileName | lower}}.yaml` for the filenames does not work for me. A filename like that is not supported.

**Comment by regicsolutions** [comment]
Couldn't you just enforce the value to be lowercase from the front-end using the built-in TextValuePicker that has this validation in place? 

https://github.com/backstage/backstage/blob/8796e812e6c90583be07ee859f87721f2259d93d/packages/app/src/components/scaffolder/customScaffolderExtensions.tsx#L29

**Comment by ProticM** [comment]
Hi @regicsolutions 

That is a custom extension that we do not have out of the box. By default, `TextValuePicker` has no extensions and validations if I'm not mistaken.

Another thing, the value I'm sending from the UI is the `entity name` that is being used in the YAML files metadata, therefore it must pass the entity name validation as well, meaning that I must use the built-in `EntityNamePicker` field which does not validate the casing.

What I see as a solution is a custom field or field extension (similar to the one you pointed in your comment) which will control the case and validate the entity name at the same time or a simpler one that I suggested above with addition to the `handlebars` helpers registrations.

To me, it seems like overkill to create a custom field for this.

**Comment by benjdlambert** [comment]
@ProticM so we're currently working on deprecating the handlebars templating syntax from the `Template` kind, and aligning them with the nunjucks templating engine in the Actions. There's more info in this ticket here: #7268. Does it work for you to wait for the `backstage.io/v1beta3` templates to be rolled out as you'll be allowed to use `${{ parameters.blah | lower }}` there?

**Comment by benjdlambert** [comment]
Rather than us adding more features to something that's going to become the legacy way pretty soon? 👍

**Comment by ProticM** [comment]
Hi @benjdlambert I'm aware of the transition process, and I think it is good that you aim to unify templating engine and provide the same workflow in template kinds and skeletons :thumbsup:

I guess I can wait and implement a workaround :clock1: How long do you think it would take to update the templates?

In my opinion how to handle this, if it is going to be one month, and you aim to release a new version in the next couple of days, then it would be nice and worth including the `handlebars` helper to manage the transition period. Correct me if I'm wrong, but I don't think it is too much of a problem and a huge deal to add it, and also it would be easier to migrate to the new `nunjucks` syntax afterward (no need to delete the custom fields/extensions that were created for this use case previously). On the other hand, if the transition is going to be completed sooner, then there is no need to add it and we can focus on the `nunjucks` syntax and filters :thumbsup:

Also, not sure how many people are encountering this scenario and thus not sure whether this requirement is that highly needed to be taken into count that seriously.

**Comment by benjdlambert** [comment]
@ProticM so I'm expecting that we should have `nunjucks` support and will be dropping the `backstage.io/v1beta3` templates either this week or next if all goes to plan. Ideally I think we'd really like to avoid backporting features to the legacy part, and have it be more of an encouragement to upgrade rather than stay on the older version 👍 

We're hoping also that the migration between the two template versions will be pretty easy and maybe even automatable, so don't want to add a feature that we have to provide an upgrade path for, as `nunjucks`'s `jinja2` syntax is reasonably different from the `handlebars` helper syntax as you've mentioned already - `${{ parameters.myField | lower }}` compared to `{{ toLower parameters.myField }}`. If we introduce this feature to `handlebars` it just makes the api surface bigger for no real reason. We'd rather get people to change their templates once rather than twice, and be on the latest and greatest!

More info to come on the `nunjucks` templating soon! Watch this space!

**Comment by ProticM** [comment]
@benjdlambert I agree with the idea of promoting the package update rather than staying behind, and it should be like that 👍 

Yes, the migration from one template to another should be pretty easy and this was my point in the previous comment. I would prefer template migration instead of clearing out the custom fields that are needed to handle this scenario at the moment.

Thank you for the update 👍 I will watch for the changes here 👀

**Comment by ProticM** [comment]
We can close this one since there is a new API version implemented
