### ISSUE TITLE
[Search] Add Search Modal

### ISSUE THREAD

**Issue by rodmachen** [backstage/backstage#7318]
## Feature Suggestion

As per the most recent Community Meetup, Expedia would like to contribute a Modal to the cadre of Search components.

This will be an iterative process with this first contribution being a basic model with only search bar, results, error page, and pagination. 

## Possible Implementation

This first iteration will use all open source components.

<img width="1437" alt="Screen Shot 2021-09-24 at 9 41 24 AM" src="https://user-images.githubusercontent.com/7606483/134729231-bd6ad7ab-5867-4cf4-b23f-ddfe8454e43a.png">

## Context

Backstage could benefit from a feature like Apple's Spotlight search that allows searching from anywhere within the app. Quick results would be displayed, allowing users to quickly find an item, without all of the detail of the full search page.

**Comment by rodmachen** [comment]
WIP PR for feedback. Changeset, tests, and docs still needed. 

https://github.com/backstage/backstage/pull/7316

**Comment by emmaindal** [comment]
Closing this as it was implemented in #7316
