### ISSUE TITLE
Ownership card gives no routeRef error after upgrading

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#7320]
I have used the latest org plugin, and with the OwnershipCard there is additional implementation showing the url's for the catalog
For example in OwnershipCard.tsx we see const catalogLink = useRouteRef(catalogRouteRef); which gives the below error
Uncaught Error: No path for routeRef{type=absolute,id=Catalog}
    at useRouteRef (index.esm.js:347)
    at OwnershipCard (OwnershipCard.tsx:134)

meaning it was unable to establish the route url. Is this a known defect? Do I need to upgrade any other component?

**Comment by timbonicus** [comment]
I expect you'll need to use `yarn backstage-cli versions:bump` to update catalog-related packages that produce this routeRef. The `org` plugins lists the appropriate dependency, but with a monorepo you can sometimes get referential issues from having different versions of the same package. You can check which versions are present with `yarn why @backstage/catalog-react`.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Ok you can close this as I have resolved this by bumping the version
