### ISSUE TITLE
Azure DevOps Discovery Processor for Discovering Catalog Entities

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#7330]
## Feature Suggestion

Currently there is no discovery processor for Azure DevOps to find catalog entities automatically. It would be great if this feature was available

## Possible Implementation

At this point I'm not sure exactly how discovery processors work from an implementation perspective. I'd assume that we could use the Azure DevOps Code Search REST API for find the `catalog-info.yaml` files within repos. We could even search in the body of the files for `apiVersion: backstage.io/v1alpha1`.

Documentation on the API for this can be found here: https://docs.microsoft.com/en-us/rest/api/azure/devops/search/code-search-results/fetch-code-search-results?view=azure-devops-rest-6.0

**Note:** Search is always on for the Cloud version of Azure DevOps. For the on-prem version you can choose not to use it. Honestly it's a very powerful feature not to us, so this seems like it would be an edge case and not the norm.

## Context

This would reduce the need to manually add these entities to Backstage and also get Azure DevOps closer to parity with the other SCM Integrations.

**Comment by Rugvip** [comment]
It looks like we actually already have search implemented for the [AzureUrlReader](https://github.com/backstage/backstage/blob/1fd9e6f601cabe42af8eb20b5d200ad1988ba309/packages/backend-common/src/reading/AzureUrlReader.ts#L147). It'll take care of discovering files within each repo. That means that the missing pieces is the repo discovery, which we probably want to implement similar to the [GithubDiscoveryProcessor](https://github.com/backstage/backstage/blob/1fd9e6f601cabe42af8eb20b5d200ad1988ba309/plugins/catalog-backend/src/ingestion/processors/GithubDiscoveryProcessor.ts#L100). The way it works is that it finds all repos that match the provided location target pattern. It then generates an [optional location for every repo](https://github.com/backstage/backstage/blob/1fd9e6f601cabe42af8eb20b5d200ad1988ba309/plugins/catalog-backend/src/ingestion/processors/GithubDiscoveryProcessor.ts#L124) that it finds, which in turn then gets picked up by the `UrlReaderProcessor` that executes the actual file search, fetch, and parsing.

**Comment by goenning** [comment]
Hi @awanlin @Rugvip I've added a draft PR to support ADO discovery, there's a few things missing, but I just wanted to get your feedback if I'm on the right track before I spend more time on it. Thanks

PS: It worked locally with our the cloud version!

**Comment by awanlin** [comment]
Thanks @goenning for getting this done, very happy to see this in place! 🚀
