### ISSUE TITLE
[Plugin] Tech Stacks

### ISSUE THREAD

**Issue by easylo** [backstage/backstage#734]
## Summary
share links and documentation on the tools we use.

like [stackshare](https://stackshare.io/stacks)

## Context
provide a default configuration and configuration file to enable the tools used in your organization

preview :

![Screenshot 2020-05-07 at 12 08 19](https://user-images.githubusercontent.com/1778568/81282909-1c098b80-905c-11ea-948c-fc4817373021.png)

**Comment by stefanalund** [comment]
Very nice! Do you want me to assign you (since it looks like you're working on it)?

**Comment by easylo** [comment]
Yes, you can.
Thanks

**Comment by stefanalund** [comment]
Done. There is also an interesting overlap here with the native [Explore plugin](https://github.com/spotify/backstage/tree/master/plugins/explore) in Backstage:

<img width="1060" alt="Screenshot 2020-05-02 at 10 28 55" src="https://user-images.githubusercontent.com/190856/81299057-f2f5f480-9075-11ea-8b33-3e692cb123c5.png">

However the use-cases are slightly different, so I think these plugins are complementary. Your plugin outlines the broader tech stack of a company whereas the Explore plugin is meant to help users of Backstage find what plugins are available in their companies' Backstage deployment.

**Comment by easylo** [comment]
I have a question:
I need to store the logos of the applications and they must be publicly accessible.
Do you have any recommendations?

**Comment by stefanalund** [comment]
My suggestion would be to use existing public URLs if possible.

**Comment by kiranpatel11** [comment]
Hi @easylo,

You may use most logos from here: https://landscape.cncf.io/
