### ISSUE TITLE
backstage-cli plugin:serve not working on windows

### ISSUE THREAD

**Issue by alzafacon** [backstage/backstage#7345]
cli version 0.7.13
this used to work on windows. we will work on rolling back one version at a time to see when it works again

## Expected Behavior

backstage-cli plugin:serve should start up the frontend plugin. 

## Current Behavior
```
PS C:\Users\work\git\backstage\plugins\home> yarn start
yarn run v1.22.1
$ backstage-cli plugin:serve
Loaded config from app-config.yaml
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
<i> [webpack-dev-server] Content not from webpack is served from '/' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\work\git\backstage\plugins\home> node -v
v14.16.0
```
## Possible Solution

🤷  not sure

## Steps to Reproduce

1. clone backstage on windows
2. cd plugins/welcome
3. yarn start 

## Context

starting up the app can be very slow. this could help save developers time.

## Your Environment

- NodeJS Version (v14): 14.16.0
- Operating System and Version (e.g. Ubuntu 14.04): windows 10
- Browser Information: chrome

**Comment by alzafacon** [comment]
I found that at release 2021-08-05 the cli version is 0.7.7 and yarn start still works ✔️ 
at the next release 2021-08-11 the cli version is 0.7.7 but yarn start fails ❌ 

https://github.com/backstage/backstage/compare/release-2021-08-05...release-2021-08-11
shows webpack changes were made in packages/cli that might be responsible

**Comment by alzafacon** [comment]
looks like a migration to webpack 5 might be responsible
https://github.com/backstage/backstage/pull/5292

**Comment by Rugvip** [comment]
@alzafacon well shit, that's the webpack 5 bump 😅. Thank you for reporting tho, gonna try to reproduce. Gotta say it's weird if this only is a problem for the plugin serve

**Comment by alzafacon** [comment]
yeah, even weirder is my team mates with macOS don't have this problem 🤷

**Comment by alzafacon** [comment]
🥳 
it works thanks
