### ISSUE TITLE
Entities should have an optional display name

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#7361]
## Feature Suggestion

I would like service metadata to include an optional display name which could be used to record a more human friendly name. 

The limitations around use of whitespace, and the compactness of the table in the main service catalog, can render service names difficult to read. They're also not very human friendly due to the use of hyphens.

![Screenshot 2021-09-28 at 13 24 46](https://user-images.githubusercontent.com/562403/135086762-e3a4c999-7a4e-4ae0-a972-724c1fe08559.png)

## Possible Implementation

The human friendly name would be used in the catalog list and in the header of the main entity page. It would not need to be unique.

**Comment by freben** [comment]
Support for this was added through `metadata.title`: https://github.com/backstage/backstage/pull/6888

What remains is to actually make use of that feature throughout the interface.
