### ISSUE TITLE
Login failed : Incorrect app origin

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#7362]
This issue is related to #3223.

Basically our app is deployed on a server and the landing page shows multiple login options. We use oauth2.0 sign.
The app's url's is frontend with the webserver which just acts as a proxy. 
Now, user uses webserver url to which proxies the request to the service (frontdn+backend) running on a server, clicks on the sign in page, which takes the user to the oauth2.0 provider and then after login, displays the message "Login failed : Incorrect app origin".
I know it is something to do with the CORS. Is there any solution already in place for this?

**Comment by benjdlambert** [comment]
You probably want to make sure that `app.baseUrl` is set as the exact same address in the address bar when you're navigating to backstage./

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Yes, i tried that and it worked. Thanks. And bascially had to set the backend.cors.origin to the same thing as well.
Is there any way we can configure lets say multiple cors origin url's (but not wildcard *)?

**Comment by adamdmharvey** [comment]
oops; saw you snuck in another question, apols, re-opening!

**Comment by benjdlambert** [comment]
@shanthisagar-dhanya-kumar-db don't think so, what is your use case here? Why do you need multiple origins?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Sorry, I just realised that having multiple cors for us requires multiple app.baseurl ( we use oauth2.0 so the origin;s will fail ) which is not possible with just one instance of application. May be a very stupid question . I will close this
