### ISSUE TITLE
Collapse overview widget cards when entity not configured

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#7365]
## Feature Suggestion

The entity page should not look so messy when various annotations do not exist. I have screenshotted an example at the bottom of this issue. We are using the Snyk, Links and SonarQube plugins but they are not configured for this particular entity. I would like the page to look less messy.

There is some value in having the cards appear, even though the annotation is not set for this particular component.

1. The card can teach the user how to set the annotation, which encourages it to show up.
2. Snyk (for example) might be a requirement for all components in my org. If so, I want to know that it is not configured.

## Possible Implementation

Cards could collapse when the annotation is not set. I could expand them to see the missing annotation content. This would keep them accessible while not being so visually distracting.

I also considered having a magic annotation which would turn off the plugin for a particular component. This, however, would require rolling out across many teams in an org in order to clean up the UI in Backstage.

I'd love to hear other implementation suggestions of course.

## Context

![demo2 roadie so_catalog_default_component_sample-service-2](https://user-images.githubusercontent.com/562403/135116367-37c55129-19c5-4cc4-93b9-2572644c1553.png)

**Comment by dhenneke** [comment]
Remotely related to https://github.com/backstage/backstage/issues/3781.

What I could imagine is some kind of central warning panel per entity that tells you that you are missing some recommended annotations or features. Or use a system like https://github.com/backstage/backstage/issues/2662 / https://github.com/backstage/backstage/pull/7193 to display it. Something similar to the screenshot that [Monzo](https://monzo.com/blog/2021/09/15/how-we-measure-software-excellence) presented:
<img src="https://user-images.githubusercontent.com/720821/135236975-3c5fa108-e5dc-42e1-bc4b-bb985554820f.png" width="400">

Widgets that are not configured would simply be hidden and entities have some kind of "score" in the about card and could also display the most important issue (like a missing required integration) in a prominent warning panel. It could also be part of the [home page](https://github.com/backstage/backstage/issues/5416) if it is a critical issue.
