### ISSUE TITLE
Timeout Scaffolder Log Stream

### ISSUE THREAD

**Issue by OscarDHdz** [backstage/backstage#7370]
When running Scaffolder tasks, if `backend` stops for any reason (i.e. a deploy),  the log stream never gets a "end signal" which causes the UI (tasks/:taskId) page to render the task execution as it was still executing. 

![image](https://user-images.githubusercontent.com/18434722/135173939-bf66db8f-9174-455c-87e5-bd0fc4a2d128.png)

## Feature Suggestion

It would be nice if we could set a limit to timeout tasks logs. For example, if the task execution has exceeded 1hr, set an "end log" to the task log stream. 

## Possible Implementation

This "end log" could be set on demand when the log stream is requested (/tasks/:taskId page is loaded). If log stream has taken more than 1hr, set the "end log" with a proper error.  

## Context

This causes confusion to Backstage end users. Sometimes we do many deployments in our environment which trigger this behavior. This means that users often get a "Never ending Scaffolder task execution", which makes them believe that something is still running while the true is that the process got stopped and nothing is running.

**Comment by benjdlambert** [comment]
Hmm yep, I think we did toy around with the idea of having a `heartbeat` for each of the workers, but I'm not sure that we actually implemented it yet. The idea would be that if a worker dies half way through the job, it would set the job to failed, and possibly requeue it to be picked up by another worker if possible.

**Comment by freben** [comment]
Hmmm yeah the liveness thing doesn't really cover the case of service shutdown / death.

https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/tasks/StorageTaskBroker.ts#L90

**Comment by OscarDHdz** [comment]
Hi there, wanted to revive this issue and see if we could work on it? 😃

**Comment by benjdlambert** [comment]
Sure - I can assign you if you would like?

**Comment by OscarDHdz** [comment]
Yaaay, please!

**Comment by benjdlambert** [comment]
Closing as fixed  with #13429! :tada:
