### ISSUE TITLE
Bitbucket Cloud Discovery Getting Rate Limited

### ISSUE THREAD

**Issue by aravindparappil46** [backstage/backstage#7383]
## Expected Behavior

For integrations with Bitbucket Cloud, API rate limits should not be hit when discovery is configured.

## Current Behavior

Bitbucket Cloud REST API rate limits are hit, which prevents further scanning/onboarding of repos

## Possible Solution

Some ideas, although not sure how feasible they are:
- Configurable polling frequency through the `app-config.yaml`
- Once rate limits are hit, future scans should pick up from where the previous scan left off, instead of scanning all over again

## Steps to Reproduce

1. Configure Bitbucket cloud discovery according to [this](https://backstage.io/docs/integrations/bitbucket/discovery) doc
2. Wait till scanning/polling happens

## Context

Recently, in [6216](https://github.com/backstage/backstage/issues/6216), support for auto-discovery of entities from Bitbucket Cloud repositories was rolled out. However, the scanning for repos happen too frequently and this leads to the Bitbucket Cloud REST APIs returning HTTP Code 429, as the rate limits of BB Cloud is being hit. Rate limits also get hit when scanning a wide sample space, say a Bitbucket workspace which contains 1000+ repos. _Note: This is an issue originally mentioned by @FilipSwiatczak in the plugin request thread_

Btibucket Cloud API limits: https://support.atlassian.com/bitbucket-cloud/docs/api-request-limits/

## Your Environment

- NodeJS Version: 14.4.0
- Operating System and Version (e.g. Ubuntu 14.04): MacOS 11.6
- Browser Information: Chrome v94

**Comment by FilipSwiatczak** [comment]
hi @aravindparappil46 I am currently successfully working around rate limits by specifying:
```
  const { processingEngine, router } = await builder.setRefreshIntervalSeconds(600).build();
```
in
`packages/backend/src/plugins/catalog.ts`
600 sec/10 min makes for 6 queries per hour and BB Cloud rate limit for repositories is 1000/h so 1000/6=166 would be your max number of separately called entities. Let me know if that works :)
