### ISSUE TITLE
[TechDocs] Adding Video in TechDocs

### ISSUE THREAD

**Issue by brondum** [backstage/backstage#7393]
More a request for help than a bug ( i think ). 
I am trying to add a video file to the techdocs section by using the `<video>` html tags.
It uploads and the videofile to the GCS bucket just fine and the link to the file seems fine in backstage, but i cant load the file. ( gives me a status code 206).

Anything i am missing? 

doing something like:
```
<video src="../assets/create_gh_repo/create_gh_repo.mp4" autoplay controls width="100%"></video>
```

## Your Environment

- NodeJS Version (v14):  v14
- Browser Information: Chrome

**Comment by brondum** [comment]
Short update, i think some of my responses was cached but now i am able to get a MIME type error. So i guess it relates to: #6015 ?

![image](https://user-images.githubusercontent.com/34370407/135585163-32593183-8b1c-419a-88e2-61bd34b563d1.png)

**Comment by brondum** [comment]
> Short update, i think some of my responses was cached but now i am able to get a MIME type error. So i guess it relates to: #6015 ?
> 
> ![image](https://user-images.githubusercontent.com/34370407/135585163-32593183-8b1c-419a-88e2-61bd34b563d1.png)

Okay ignore this one, it was just me who was a complete moron. the builder gave me the following error:
```
WARNING  -  A relative path to 'create_gh_repo' is included in the 'nav' configuration, which is not found in the documentation files
```

Which could be solved by adding a proper path to the file index file in the nav.

Now i am back to the original error, with videos not loading. Anyone experienced this? and could be something i have to add to mkdocs ?

**Comment by brondum** [comment]
note stale

**Comment by garyniemen** [comment]
@emmaindal or @iamEAP - thinking about our recent work with iframes - can you shed any light on this?
