### ISSUE TITLE
Trouble running new plugin....

### ISSUE THREAD

**Issue by cbwilliamsnh** [backstage/backstage#7395]
I'm trying to start backstage and am getting the following error:

$ yarn workspace example-app start
$ yarn workspace example-backend start
$ backstage-cli app:serve
$ backstage-cli backend:dev
[0] 
[0] Error: No existing version was accepted for range ^0.9.3, searching through 0.9.2,0.8.4, for package @backstage/catalog-model
[0] 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
[0] Exit code: 1
[0] Command: /usr/local/bin/node
[0] Arguments: /Users/chwilliams/eig/backstage-curtain/bsdev/.yarn/releases/yarn-1.22.1.js start
[0] Directory: /Users/chwilliams/eig/backstage-curtain/bsdev/packages/app
[0] Output:
[0] 
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[0] yarn start exited with code 1```

## Environment ##

MacOS Catalina
❯ yarn -v
1.22.10
❯ node -v
v14.17.
[okd-plugin.zip](https://github.com/backstage/backstage/files/7261415/okd-plugin.zip)

I've also made mods to App.tsx and Root.tsx if those are needed as well.
5

**Comment by adamdmharvey** [comment]
Sounds like you might have an older scaffolded version of Backstage?

Not sure if this helps, but you could give these a shot:
https://backstage.io/docs/cli/commands#versionsbump

The bump command will help get you to the new versions, along with warning you if there are any breaking changes for your app. While the check command should help fix anything if there are duplicates.  That may, or may not, help in your case?

Another option, especially if you're just playing around, might be to scaffold a brand new version with the latest packages.   (i.e., [Create an app](https://backstage.io/docs/getting-started/create-an-app))
