### ISSUE TITLE
Failed to refresh access token while using load balancer

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#7405]
We have a load balancer frontend with 2 instances of our application (frontend+backend). And we use Oauth2.0 for authentication
Now when we hit the load balanced url, the first very first time it will ask us for login because the refresh token doesn't exist and we login. Let's say in this case the instance 1 is used for authentication in the backend.

After login, lets say if we manually refresh the window or open the same url (in this case load balancer url) in a different window, it is going back to the sign page again asking for the user to sign in , but in this case it is using the instance 2 for the backend authentication and the refresh token fail to fetch and we get "Failed to refresh access token [object Object]".

**Comment by benjdlambert** [comment]
Think we need some more info here, could you do some debugging to find out what the `[object Object]` is?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
The object object is as below
{
  statusCode: 400,
  data: '{"error":"invalid_grant","error_description":"Stale token"}'
}

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Yes, the authentication using the two proxies work as expected and if I try to hit both the application url's manually , they work independently.
The clocks are in sync too.
