### ISSUE TITLE
Getting Error After Catalog Service Creation

### ISSUE THREAD

**Issue by sjamidar** [backstage/backstage#7408]
![image](https://user-images.githubusercontent.com/85929731/135599142-aa0ad128-fbe3-44dc-8acb-b5bf501c03ca.png)

After success of Catalog Service creation's register step, We should get Repo link. but getting attached error in that.
Checked the configs, and those are proper.
Looks like react dom issue , but not sure what is the exact sure. 
Can anyone please help on this.

**Comment by benjdlambert** [comment]
Hmm this could be because of duplications with the `catalog-react` package. Can you run `yarn why @backstage/catalog-react` and paste the output :)

**Comment by sjamidar** [comment]
Output of above command : 
yarn why v1.19.0
[1/4] Why do we have the module "@backstage/catalog-react"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
error We couldn't find a match!
Done in 8.47s.

**Comment by benjdlambert** [comment]
Sorry mybad. `yarn why @backage/plugin-catalog-react`

**Comment by sjamidar** [comment]
Same here as well
yarn why v1.19.0
[1/4] Why do we have the module "@backage/plugin-catalog-react"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
error We couldn't find a match!
Done in 7.56s.

**Comment by benjdlambert** [comment]
Can you ping me on discord and we can go through. It should be backstage not backage I updated the spelling?
