### ISSUE TITLE
GKE K8s Plugin Requires Auth Provider, not GKE Credentials

### ISSUE THREAD

**Issue by KnechtionsCoding** [backstage/backstage#7429]
The k8s plugin configuration section implies a different workflow for a user when installing the k8s plugin

## Expected Behavior

The documentation on the K8s plugin setup for GKE seems to imply that setting `GOOGLE_APPLICATION_CREDENTIALS` would be enough for the kubernetes section of backstage to show up, and resources to get populated.

I shouldn't need to configure an auth provider for google for users to see their resources, nor should they have to login to google to do so?

## Current Behavior

When configuring only the `GOOGLE_APPLICATION_CREDENTIALS` I was consistently getting a No Auth Provider Registered for Google message when actually trying to view the actual k8s tab, and required a login.

It wasn't until I added an auth provider for google that I was able to actually login and see the k8s resources for a component. This either needs to be called out in the documentation, or seems to be a misconfiguration somewhere.

## Steps to Reproduce

1. New Backstage instance
2. Configure k8s, and add GKE cluster
3. Don't configure auth provider.
4. Get No Auth Provider error message when you try to open the k8s tab and auth for google.

## Context

Trying to get backstage setup, and ideally want to give backstage the credentials required to have users not be required to login to see their k8s resources, especially as each cluster exists in different projects.

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by benjdlambert** [comment]
Dont think this is a bug, more a fact that we need to add support for authenticating with `GOOGLE_APPLICATION_CREDENTIALS` instead. Is this something you want to contribute?

**Comment by KnechtionsCoding** [comment]
If someone can point me in the right direction for where to contribute it as a method of auth, yes. I reported it as a bug though because the `GOOGLE_APPLICATION_CREDENTIALS` is specifically called out as the method of auth for the k8s-plugin https://backstage.io/docs/features/kubernetes/configuration#gke

**Comment by dirathea** [comment]
Hi folks, I think I'm encounter the same issues but with different authentication provider. My Backstage instance uses GitHub Authentication, while my deployment is on GKE.

I think one of the way to access GKE without using Google Auth, is just using the service account configuration with caData. There is an official docs around how to connect to GKE without gcloud [here](https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#environments-without-gcloud)

to support this, I also already opened a PR #7555 to add this support.

**Comment by djamaile** [comment]
@KnechtionsCoding will you pick up this issue? I am also very interested in this.

**Comment by KnechtionsCoding** [comment]
@djamaile I don't have time to pick it up at this point, so feel free.

**Comment by djamaile** [comment]
I was thinking maybe it's best till this #7555 merged? If you want to authenticate though `$GOOGLE_APPLICATION_CREDENTIALS` you would need to set ca data in the kubeconfig anyway. Could be, I am mixing stuff up, but I think thats how it works.

**Comment by kim5566** [comment]
Could it be possible like using Cloud Storage for Techdocs, automatically use the environment variable GOOGLE_APPLICATION_CREDENTIALS to authenticate if running on GKE.
