### ISSUE TITLE
AboutCard in plugin-catlog not showing Tech Docs Link when Annotation is Set

### ISSUE THREAD

**Issue by codingdiaz** [backstage/backstage#7441]
## Expected Behavior

When I set this annotation `backstage.io/techdocs-ref`, I should get a link to the tech docs on the AboutCard component. 

## Current Behavior

The link is disabled when this annotation is set. 
![Screen Shot 2021-10-04 at 4 06 12 PM](https://user-images.githubusercontent.com/20445982/135917539-27d11f49-4296-40c7-ae5c-e5fa10abbde1.png)
![Screen Shot 2021-10-04 at 4 06 27 PM](https://user-images.githubusercontent.com/20445982/135917547-30d9dd8b-57d6-4972-811d-217764a9fdce.png)

## Steps to Reproduce

1. Add Tech Docs annotation to a component
2. Check the component using the AboutCard to see if the link works or not

## Your Environment

- NodeJS Version (v14): 14.17.0
- Operating System and Version (e.g. Ubuntu 14.04): OSX
- Browser Information: Chrome

**Comment by adamdmharvey** [comment]
* Can you include the entire catalog log info yaml, even if partially redacted, so we can help see if it's in the correct place?
* Do the docs show up in the Docs left navigation menu as an existing documentation and only not in the AboutCard? (or does it not show up anywhere, in which case it's more likely just something wrong with the core annotation definition itself)

**Comment by adamdmharvey** [comment]
The relevant info is here, but as you've noted, the value is similar to that which is in this doc:
https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageiotechdocs-ref

**Comment by iamEAP** [comment]
Hey @codingdiaz, there was a change recently that now requires that you bind this route in your App.tsx. Can you make sure you've made the following change?

https://github.com/backstage/backstage/blob/master/packages/create-app/CHANGELOG.md#0338
