### ISSUE TITLE
Error: The migration directory is corrupt

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#7442]
Hi, I'm currently using the AWS RDS postgre, but I'm stuck with the problem below. 

![image](https://user-images.githubusercontent.com/56138162/135941393-ab2a2344-1640-40c5-a367-d8eba3d5500c.png)

**Comment by planeiii-te** [comment]
> Your best bet is to rollback the database to an older version before these unwanted migrations ran, or to start over fresh.

Is there any documentation for this?

**Comment by angeliski** [comment]
We created in #28692
