### ISSUE TITLE
Trying to create a Docker Container to Run Front-End with app-config configurable

### ISSUE THREAD

**Issue by seizadi** [backstage/backstage#7490]
## Feature Suggestion
When I build the Front-End using the instructions here:
https://github.com/backstage/backstage/tree/master/contrib/docker/frontend-with-nginx

It pulls the app-config.yaml content and it has some items that should be configurable.
e.g. 
```bash
backend:{baseUrl:"http://localhost:7000"}
```

## Possible Implementation

Option 1 - We could have a unique resource for front-end configuration that can be read when front end loads. This resource
can be built for each environment (e.g. helm chart)  and mounted as a volume by docker/kubernetes.

Option 2 - If the front-end loads and its domain is not localhost e.g.
https://backstage.demo.com, it could try backend at http://backstage.demo.com/api and fallback to app-config settings. It would be nice if backend has a well known api end point that could be a probe.

## Context

Trying to containerize Front-End.

**Comment by freben** [comment]
If you use the nginx base image that we have in the repo, it has a launch script that makes it possible to use `APP_CONFIG_*` [environment overrides](https://backstage.io/docs/conf/writing#environment-variable-overrides). They get injected at startup. Maybe that could be a strategy for your needs.

Apart from that, you might also look into either serving the frontend through the app-backend plugin for the regular node backend, or writing an entirely custom config loader to inject into the app at startup. But the env var approach is probably the way to go for now.

**Comment by freben** [comment]
Nice! I'll close this issue as the workaround is in place, and thank you for the fix pull request, let's continue there!
