### ISSUE TITLE
The footer navigation in tech docs is not responsive on the pinned state of the sidebar

### ISSUE THREAD

**Issue by shvmbisht** [backstage/backstage#7494]
## Expected Behavior
The footer navigation in tech docs should be responsive irrespective of the pinned/unpinned state of the sidebar.

## Current Behavior
The footer navigation in tech docs is not responsive on the pinned state of the sidebar. It is responsive for the unpinned state of the sidebar.

### Unpinned sidebar view
![unpinned-sidebar](https://user-images.githubusercontent.com/19923220/136382474-29c1242c-14cf-4e59-9041-26ca532ad639.png)

### Pinned sidebar view
![pinned-sidebar](https://user-images.githubusercontent.com/19923220/136382536-ddb99d53-2097-4a69-9872-9a89686c567e.png)

## Possible Solution
Pinned/Unpinned state of the sidebar can be used to inject CSS dynamically, but the issue with this approach is that the pinned/Unpinned state of the sidebar is local to `plugin-user-settings`  and footer navigation lies inside `plugin-techdocs`.

## Steps to Reproduce
Go to `https://demo.backstage.io/docs/default/component/backstage/conf` and view the component in pinned state of the sidebar.

## Your Environment

- NodeJS Version (v14): v14.17.5
- Operating System and Version (e.g. Ubuntu 14.04): macOS Big Sur (version 11) 
- Browser Information: Google chrome Version 94.0.4606.61

**Comment by kuangp** [comment]
still an issue
