### ISSUE TITLE
Error: Auth refresh request failed, Unauthorized after Oauth2.0 token expired while user browses catalog page

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#7498]
We use OAuth2.0 for authentication and the refresh token expiry period is set as per the provider.
When the user is idle for more then set expiry time, and when they try to fetch any page ( without doing any browser refresh ), instead of redirecting them back to the Sign In page, it displays the error message on the screen "Error: Auth refresh request failed, Unauthorized". 
In the developer console we see the error "Failed to refresh access token"

**Comment by freben** [comment]
This sounds like it might be related to the other issue you posted.

Normally what should happen is a silent refresh in the background without user interaction, if refreshes are supported at all by the provider in question. Do you know if a refresh token is actually set by your provider and communicated up to the frontend or not?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
We just have Oauth 2.0 as Sign In Provider.

SignInPage: props => (
      <SignInPage
        {...props}
        providers={[oauth2Provider]}
      />
    ),

What details are you after?

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Once the refresh token / access token expires, meaning the "exp" on the Oauth claims is before the current date, would the backstage automatically sign out the logged in user? I have observed the other Oauth implementation elsewhere where the user is automatically signed off and the login page is presented again.

What is happening now is that we login using Oauth2.0 the very first time and the token expires after 90 min, the screen is constant until we reload the browser url. I have left the screen without moving any cursor for almost 2 days and it's still sitting there. Should't the backstage automatically logout the user presenting the sign in page again?

**Comment by benjdlambert** [comment]
Hmm it won't refresh the page as soon as the token expires, it will just do this transparently when you request something new and the token needs refreshing. Do you have a `/refresh` endpoint setup for your auth provider?
