### ISSUE TITLE
Push specific files from one Repo into another Repo using software template.

### ISSUE THREAD

**Issue by aswathysen** [backstage/backstage#7564]
How to **push files (GitHub action workflow file) from one repo to another repo** using templates(software templates)? #Helpwanted

**Comment by aswathysen** [comment]
> `fetch:plain` and `fetch:template` these two actions does it fetch all the contents from the repo or specific files only? my requirement is to push the github action workflow file and its associated folders from one repo to another another.

**Comment by Rugvip** [comment]
@aswathysen the `fetch:plain` action should let you fetch the existing actions, and for pushing that content to an existing repo you'll have to use a pull request action. Those only exist for GitHub at the moment though, `publish:github:pull-request`

For more information on templates, please check out https://backstage.io/docs/features/software-templates/writing-templates and the surrounding documentation
