### ISSUE TITLE
$ref : Error downloading 

### ISSUE THREAD

**Issue by fb33** [backstage/backstage#7571]
Hi

External ref to a schema doesn't seem to work

Here's my case: 
I've got a API described by this : 
_api-info.yaml_
```
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bridge-machine-service-maintenance-kafka
  description: bridge machine service maintenance kafka
spec:
  type: asyncapi
  lifecycle: production
  definition: 
    $text: ./contract.yml
```
And the asyncapi contract looks like : 
_contract.yml_
```
asyncapi: "2.1.0"
info:
  title: bridge-machine-service-maintenance
  version: "1.0.0"
  description: |
    This service 

channels:
  public.data.service.tracking.consolidated:
    description: Maintenance intervention messages from kafka
    bindings:
      kafka:
        topic:
          partitions: 5
          cleanup.policy: delete
    publish:
      operationId: consumeMaintenanceIntervention
      traits:
        - $ref: "#/components/operationTraits/kafkaConsume"
      message:
        $ref: "#/components/messages/maintenanceInterventionPayload"
        
components:
  messages:
    maintenanceInterventionPayload:
      name: Maintenance intervention
      title: Maintenance intervention message
      summary: This is the definition of a maintenance intervention message
      traits:
        - $ref: "#/components/operationTraits/kafkaKey"
      schemaFormat: "application/vnd.apache.avro;version=1.9.0"
      contentType: avro
      payload:
        - $ref: "https://raw.githubusercontent.com/ept/avrodoc/master/schemata/example.avsc"
    
  operationTraits:
    kafkaConsume:
      bindings:
        kafka:
          groupId:
            type: string
            enum: ["bridge-machine-service-maintenance"]
    kafkaKey:
      bindings:
        kafka:
          key:
            type: string
            description: Equipment serial number

```            
       
## Expected Behavior
The external ref should be well parsed
```
      payload:
        - $ref: "https://raw.githubusercontent.com/ept/avrodoc/master/schemata/example.avsc"
```
The result shoud be like when I use the editor  https://asyncapi.github.io/asyncapi-react/ with the content of contract.yml

## Current Behavior

I've got an error in the asynapi tab : 
`Error: Error downloading https://raw.githubusercontent.com/ept/avrodoc/master/schemata/example.avsc (intermediate value)(intermediate value)(intermediate value).get is not a function`

## Steps to Reproduce

1.  create an API with api-info.yaml (see above)
2.  go to <Backstage_base_url>/catalog/default/api/bridge-machine-service-maintenance-kafka/definition

Regards

**Comment by Rugvip** [comment]
Thank you! Sounds like enough cause to reopen :grin:

**Comment by brethubbard** [comment]
I found the culprit. It looks like at some point the `http` and `https` resolutions were disable explicity [here](https://github.com/backstage/backstage/blob/59e822b43c39f1128188a8a0f7df053bd708f4dd/packages/cli/src/lib/bundler/config.ts#L193). When I delete those two lines it works.

I imagine this was intentional to ensure only certain hosts could be reached but it is causing issues.

**Comment by freben** [comment]
@fb33 is this ready to close?

**Comment by fb33** [comment]
Hi @freben , I'm not sure, the problem is still there.
I think other people must have the same need. ($ref with a url )
Otherwise it's up to you to see if it's a feature to integrate.

On my side I customized the asyncApi widget, so I'm not blocked.

**Comment by brethubbard** [comment]
I'm just seeing there is an open PR on this and I'm struggling a little to understand the logic of the conversations in both places. In this issue we discussed that there is config that is breaking functionality of the plugin that _could_ be removed and it would just work :tm: . In the PR it sounds like if anyone wants this functionality then they need to customize the component that should work out of the box.

Maybe I am just misunderstanding what was said in the PR and if so please let me know.

**Comment by fb33** [comment]
Hello, yes it's about that. 
I didn't find where and why this configuration is used. So I though it was for good reason (security) and we couldn't modify it.
That why I wrote the PR for those who use a schema registry and reference there schema with as URL.
But if you're OK with modifying the bundler config, it's fine for me 🙂

**Comment by dweber019** [comment]
What is the status of the PR? just created an other issue as I didn't saw this.
https://github.com/backstage/backstage/issues/9040

**Comment by Rugvip** [comment]
Repeating again that #9040 contains another writeup of this issue with some more context 👍

**Comment by kareemshahin** [comment]
Also running into the same problem and didn't see any PRs open to address this yet!

**Comment by dweber019** [comment]
@Rugvip can be closed as it's solved.
