### ISSUE TITLE
Calling logUpdateFailure for all of `readerOutput.entities` slows down locations refresh

### ISSUE THREAD

**Issue by heatheralee** [backstage/backstage#7573]
Hi there! We are currently experiencing the issue where our locations refresh ends up being progressively slower over time (from what is usually 1.67s, to 1464.8s, all the way to 20k+ seconds if we don't restart our instance frequently). This leads us to getting updates on a significantly less regular basis.
 
## Expected Behavior

It makes sense that the ingestion loop might be slowed down by ingesting more entities, but when an error is caught in `plugin-catalog-backend` when calling `await this.entitiesCatalog.batchAddOrUpdateEntities`, it should only call 
```
await this.locationsCatalog.logUpdateFailure(...)
```
for the batch of 100 entities that failed, not all `readerOutput.entities`.

## Current Behavior

When an error is caught in `HigherOrderOperations.refreshSingleLocation`, all of the `readerOutput.entities` are [looped through and written to the update log failure table](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/legacy/ingestion/HigherOrderOperations.ts#L193). This proves to be an expensive operation for those who are sourcing a lot of data from app-config.yaml.

## Possible Solution

Update `batchAddOrUpdateEntities` to throw a more verbose error with the batch of size 100 containing the problematic entity. Then continue to loop through this batch maxed out at size 100 and write these entities to the location update log.

## Steps to Reproduce

1. Add a location to app-config.yaml which sources 10k+ entities.
2. One of those entities should have the same `metadata.name` (which will result in a `ConflictError`).
3. Note that over time, "Locations Refresh: Completed locations refresh in NNNs" that NNN grows in value.

## Context

We are currently using the legacy CatalogProcessor. A stop gap measure has been introduced where we tested out this theory. We used `patch-package` to comment out these lines:
```
      for (const entity of readerOutput.entities) {
        await this.locationsCatalog.logUpdateFailure(location.id, e, entity.entity.metadata.name);
      }
```
and the Backstage instance had no problem pulling data at the expected 1.67 intervals. Without this patch, the time it takes to ingest new data from locations defined in app-config.yaml becomes more and more spread out.

## Your Environment

- NodeJS Version (v14): v14
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by Rugvip** [comment]
The `HigherOrderOperations` and friends are part of the legacy catalog implementation that we phased out a few months ago and is about to disappear. Please move to using the new catalog implementation at it overall has much better performance, scalability, is more deterministic and exposes errors better. The old catalog won't receive any more updates.

A good place to scan for how to update to the new catalog is the [create-app changelog](https://github.com/backstage/backstage/blob/master/packages/create-app/CHANGELOG.md). Search for entries that make changes to the `catalog.ts` in the backend
