### ISSUE TITLE
Provide an alternative to event streams in the scaffolder and in techdocs

### ISSUE THREAD

**Issue by dhenneke** [backstage/backstage#7579]
We use Backstage in an environment where the users are in a network that requires a HTTP proxy to access the internet (and Backstage). We noticed that eventsource connections are not handled correctly as the used proxy service doesn't support long running connections correctly. The connection stays open but no content is streamed. After 1 minute (the assumed timeout of the proxy server), it finishes the connection with all the content. This is not really usable.

## Feature Suggestion

Make it work 😄.

## Possible Implementation

* Provide an alternative long-polling implementation for the endpoints. This can also be config-driven i.e. a global switch for a backstage installation instead of a client-side fallback mechanism.
* Find out if there is any workaround with setting certain HTTP headers (we tried, but didn't find anything).

We already tried to replace the frontend API and provide a new backend route that mimics long-polling. But maybe it would be nice to have out-of-the-box support for this in backstage.

<details>
<summary>A workaround</summary>

```ts
// /packages/backend/plugin/scaffolder.ts

// ...

const router = await createRouter({
  containerRunner,
  logger,
  config,
  database,
  catalogClient,
  reader,
  actions,
  taskWorkers: 2,
});

router.get('/v2/tasks/:taskId/logs', async (req, res) => {
  const { taskId } = req.params;

  const baseUrl = await discovery.getBaseUrl('scaffolder');

  const logs: any[] = [];

  const source = new EventSource(`${baseUrl}/v2/tasks/${taskId}/eventstream`);

  source.addEventListener('log', (e: any) => logs.push(e));
  source.addEventListener('completion', (e: any) => logs.push(e));
  source.onerror = () => source.close();

  // TODO: something shorter?
  await new Promise(resolve => setTimeout(resolve, 500));

  source.close();

  return res.json(logs);
});

return router;
```
</details>

---

Does anyone else have this problem?

**Comment by dhenneke** [comment]
Yes. In my experimental code that I listed above I did an arbitrary wait of 500ms to collect events. But sure, it at least shouldn't return if there was no new log line yet to limit "useless" returns.

**Comment by Fox32** [comment]
@dhenneke This is resolved, right?

**Comment by dhenneke** [comment]
@Fox32 the techdocs part is still open. There is a non-eventstream support [in techdocs](https://github.com/backstage/backstage/blob/7439368ce532e98bea8994b2be1899c9af9626ca/plugins/techdocs-backend/src/service/router.ts#L165-L170), but that doesn't use long polling but stays open until it finishes. And it is planned to be removed and there is no frontend implementation for it.

But I guess it is not that critical for techdocs to see live logs as it is in the scaffolder. Since the event stream is closed by the server once done, it should still return all logs and errors once the process finished. This would be the same behavior as the "old" techdocs version prior to live-logs.

**Comment by dhenneke** [comment]
I think we can close this, as our main issue is solved.
