### ISSUE TITLE
[RFC] Template Actions Anywhere

### ISSUE THREAD

**Issue by hostsamurai** [backstage/backstage#7593]
**Status:** Open for comments

## Need

We need a lightweight mechanism for executing one-off template actions from the
context of an entity page, card, or something similar. The main motivating
factor is this: suppose that you have thousands of services and a new, optional
integration comes online, then another, and another, and so on. We'd want users
to apply these integrations to existing services as they see fit. 

## Proposal

This work would build on top of what #7211 is proposing. The idea is to execute
template actions without the need for a template. On the frontend, we would use
the same mechanism that renders the templates to do the same for an action's
`schema.input`. The values that the user enters will be `POST`ed to `/v2/tasks`
[route](https://github.com/backstage/backstage/blob/9460224ac618dea46fbf284aabcf3044e8f8dbd5/plugins/scaffolder-backend/src/service/router.ts#L158); we could either check for certain request values or use a new query
parameter to determine whether we're trying to run a task based on template
values or standalone action ones. From there, the existing scaffolder task logic
would run as if the user had filled out a template to create a new project. This
assumes that we generated a valid [task spec](https://github.com/backstage/backstage/blob/02572242c0fb04ea4a1ee4114ac9645218724c21/plugins/scaffolder-backend/src/service/router.ts#L194-L203) for the action before sending it off
to the [task broker](https://github.com/backstage/backstage/blob/02572242c0fb04ea4a1ee4114ac9645218724c21/plugins/scaffolder-backend/src/service/router.ts#L212-L214).

## Alternatives

1. Rather than repurposing the existing `/tasks` route, we could create a new
   one for these one-off scenarios. The logic would be similar but adhere to the
   proposal above.
1. Export the [task broker](https://github.com/backstage/backstage/blob/9460224ac618dea46fbf284aabcf3044e8f8dbd5/plugins/scaffolder-backend/src/scaffolder/tasks/StorageTaskBroker.ts) so that backend plugins can dispatch task
   [specs](https://github.com/backstage/backstage/blob/9460224ac618dea46fbf284aabcf3044e8f8dbd5/plugins/scaffolder-backend/src/service/router.ts#L198-L200) with only the actions that we have in mind.
1. Execute the action(s) using a template wrapper. This wrapper would be nothing
   more than the JSON representation of the template descriptor and would allow
   us to reuse the same logic for creating new projects using templates.

The third alternative would work in a similar fashion to the proposal above and
use much of the existing logic to carry out its task. It would circumvent the
[fetching](https://github.com/backstage/backstage/blob/9460224ac618dea46fbf284aabcf3044e8f8dbd5/plugins/scaffolder-backend/src/service/router.ts#L162-L164) of an existing template and craft a temporary one that serves only to
wrap the action(s) that we want to execute before sending it off to the task
broker. And to clarify, circumventing the fetching of an existing template does
not mean that we skip validation of the temporary template that we're creating.
The temporary template would be nothing more than the JSON representation of a
basic template descriptor. We would inject the action(s) inside of `spec.steps`.

## Risks

As far as I can tell, validating user inputs for actions outside of a template
is pretty rudimentary. The third alternative above could help with that. The
problem with that alternative is the added complexity. The case could be made to
add a new route for that purpose, but the more that I think about it, the less
it makes sense to do so for such a specific use-case. That being said, both the
proposal and the temporary template alternative are possibly more ideal than
exposing the task broker.

**Comment by hostsamurai** [comment]
> I'm thinking a great use case here would be to take a repository that's already been scaffolded previously, run a codemod or something on it to upgrade it to the latest base template and then push the changes as a PR to the repo.

The codemod idea makes sense. The adavantage here is that we don't have to
modify anything. That leaves us with the idea of being able to apply these
codemods from anywhere, similar to what #7211 is proposing.

As a contrived example, suppose you're browsing a service and click on its
pipeline tab. CI/CD has not been setup for this service, so the pipeline page
displays a button or link to get it setup. Clicking on this should bring up
a template that would allow you to run the codemod for the repo that the
service resides in.

**Comment by abkura** [comment]
@hostsamurai @benjdlambert @sagacity is this feature implemented?

**Comment by benjdlambert** [comment]
So there's something similar that was implemented but it's not been released yet. #15162. More info to follow about how to use this eventually.

**Comment by pc-bob** [comment]
Has this been released?
