### ISSUE TITLE
Todo Plugin - Request Failed with 400 InputError

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#7595]
## Expected Behavior

Able to see a list of TODO's

## Current Behavior

When registering components using the Bitbucket Repository Parser i am getting a 400 input error

Here is how i am constructing the Component entity:

```
  const location = {
    type: 'bitbucket-discovery',
    target: integration.resolveUrl({ url: '.', base: target }),
  };

    const component = {
      apiVersion: 'backstage.io/v1alpha1',
      kind: 'Component',
      metadata: {
        name: name,
        annotations: {
          'backstage.io/source-location': `bitbucket:${integration.resolveUrl({
            url: '.',
            base: target,
          })}`,
        },
        tags: tags,
      },
      spec: {
        type: type,
        lifecycle: lifecycle,
        owner: owner,
        system: system,
      },
    } as ComponentEntity;
```

I am able to access the entity directly when clicking on view source

![image](https://user-images.githubusercontent.com/6157895/137229572-96f4acae-4eb9-4342-8425-f6274a1a081a.png)

Full Error as JSON:
```
{
  "error": {
    "name": "InputError",
    "message": "Invalid entity source location type for Component:default/bookinfo-productpage, got 'bitbucket'",
    "stack": "InputError: Invalid entity source location type for Component:default/bookinfo-productpage, got 'bitbucket'\n    at TodoReaderService.getEntitySourceUrl (/opt/app-root/src/node_modules/@backstage/plugin-todo-backend/dist/index.cjs.js:309:15)\n    at TodoReaderService.listTodos (/opt/app-root/src/node_modules/@backstage/plugin-todo-backend/dist/index.cjs.js:257:22)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /opt/app-root/src/node_modules/@backstage/plugin-todo-backend/dist/index.cjs.js:155:19"
  },
  "request": {
    "method": "GET",
    "url": "/api/todo/v1/todos?entity=component%3Adefault%2Fbookinfo-productpage&offset=0&limit=10"
  },
  "response": {
    "statusCode": 400
  }
}
```

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by freben** [comment]
The todo plugin can only handle `url` type locations, not `bitbucket`. I'm a bit confused as well as to why you are constructing this thing manually, and why you are looking at _its_ todo tab rather than the discovered actual things 🤔 

The flow I'd expected to see, would be for there to be a location in your app-config:

```yaml
catalog:
  locations:
    - type: bitbucket-discovery
      target: ...
```

and as a result of that existing, you'd get a list of entities registered in your catalog after the first discovery run. All of them will have `backstage.io/source-location: url:https://your-bitbucket/...`. Those should be possible to view TODOs for.

**Comment by regicsolutions** [comment]
Thanks @Rugvip that worked
