### ISSUE TITLE
[Analytics Event]: Analytics events for Scaffolder usage

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#7599]
*How often is the Scaffolder used in our organization, and with which templates?*

We would like to know more about the scaffolder adoption in our organization. How often is it used (successfully, till the end)? How often is each template used?

Right now you only have the choose event on the main scaffolder screen and navigate events to the task page.

## Feature Suggestion

Add an event that is triggered once a template run is completed.

**Comment by kuangp** [comment]
we're still interested in this on our end

**Comment by benjdlambert** [comment]
@kuangp is this something you would be interested in contributing?

**Comment by msamad** [comment]
Interested in knowing what would the event contain in general? And could that be more than just an analytics event?

We managed to build something like below using the catalog entities api but yeah, thinking about it, if there is a guaranteed event (with the ability to enrich the event and hook an implementation) once the scaffolder starts and finishes, we could do a lot more.

(Shameless showcasing but also hoping someone may find it interesting - catalog entities is valuable api) :)
![2022-01-24 15_43_36-2022-01-24 15_41_30- png - Windows Photo Viewer](https://user-images.githubusercontent.com/24932925/150714655-42ebb1b2-d861-4d5d-adc1-9f03dc730ac5.png)
