### ISSUE TITLE
[Analytics Event]: Analytics events for catalog import usage

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#7601]
*How often is the catalog import used?*

Right now, we are still in the progress of importing existing services into our catalog. Therefore we would like to know how often the catalog import/registration dialog is used. While there is already a navigate event for the page, we still don't know whether the dialog was actually used and if the usage was successful (that the user went through the process till the end).

## Feature Suggestion

I'm not sure which events to emit exactly, but I'm open to suggestions.

**Comment by kuangp** [comment]
we're still interested in this on our end

**Comment by benjdlambert** [comment]
@kuangp is this something you would want to contibute?
