### ISSUE TITLE
[Documentation] Azure DevOps Locations - Required scopes for personal access token

### ISSUE THREAD

**Issue by abhith** [backstage/backstage#7608]
[Azure DevOps Locations documentation page](https://backstage.io/docs/integrations/azure/locations) mentions an optional PAT (personal access token).

![image](https://user-images.githubusercontent.com/7039457/137317835-21c56607-db53-4942-adf3-b5672ce15d30.png)

It will be helpful if we have the list of Azure DevOps scopes required by the integration in the documentation page ([source](https://github.com/backstage/backstage/edit/master/docs/integrations/azure/locations.md)),  So that we can create PAT with just those scopes.

![image](https://user-images.githubusercontent.com/7039457/137317173-ee60199f-df04-43ee-abbc-7b0408d67269.png)

**Comment by Abhith** [comment]
The idea is to communicate what are the features offered by the `Azure DevOps` integration, and the scopes required in PAT for those features to work properly. I assume not all the scopes are required by the current integration. 
Kindly open this towards the integration contributors.
