### ISSUE TITLE
Allow custom error handling in the express server on the Backend

### ISSUE THREAD

**Issue by moltenice** [backstage/backstage#7609]
## Feature Suggestion

In the `backend-common` package, the Express middleware is present here:
https://github.com/backstage/backstage/blob/923491eece9bd571aceb9d44f119db2fdd98c782/packages/backend-common/src/service/lib/ServiceBuilderImpl.ts#L156

It isn't exported so unavailable to call directly.

The default error handler is also not customisable and is called directly:
https://github.com/backstage/backstage/blob/923491eece9bd571aceb9d44f119db2fdd98c782/packages/backend-common/src/service/lib/ServiceBuilderImpl.ts#L172

This means that if users of this package want to write custom error handling this would be impossible.

## Possible Implementation

Allow a custom error handling function to be passed into the Service Builder which can then be added to the Express app:

```typescript
if (customErrorHandler) {
  app.use(customErrorHandler());
}
```

## Context

By allowing custom error handling, we can ensure that different users of the `backstage-common` package can optionally customise the error handling logic for all Express endpoints to fit their workflow (for example sending it over the network to an alerting tool).

While a Express Router can do most things the Express App can do, error handling isn't one of them: https://stackoverflow.com/questions/45431595/express-error-handler-inside-router-doesnt-work

**Comment by Rugvip** [comment]
Quick note on this that yep, we very much want this. 👍

We're not super focused on the backend bits right now so wouldn't want to do any massive refactor, but perhaps we can implement your suggested solution as a stop-gap as I think we really should support this. Will open this up for contributions, let us know if this is something you want to work on @moltenice!

**Comment by radoslaw-wielonski-nc** [comment]
I've created new PR for this: https://github.com/backstage/backstage/pull/8377

**Comment by radoslaw-wielonski-nc** [comment]
I think we can close this issue as PR for this was merged to master.
