### ISSUE TITLE
GitHub rate limit introspection

### ISSUE THREAD

**Issue by Crevil** [backstage/backstage#7628]
We are currently indexing a rather large GitHub organization with a couple of custom processors and see intermediant 403 responses from GitHub. Unfortunately we have no way of knowing more about what happened.

```
TechDocsPreProcessor: Failed to check for mkdocs.yml file: Error: https://github.com/lunarway/x/blob/master/mkdocs.yml could not be read as https://api.github.com/repos/lunarway/x/contents/mkdocs.yml?ref=master, 403 Forbidden
```

## Feature Suggestion

It would be nice if I could (maybe temporarily) enable some debug logging to get more insights into the HTTP requests that's failing. GitHub provides some HTTP headers that tell you about whether you reached the limit and how mainy requests you have left. ([GitHub Resources in the REST API - rate limiting](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting))

```
x-ratelimit-limit: 5750
x-ratelimit-remaining: 5747
x-ratelimit-reset: 1634293237
x-ratelimit-resource: core
x-ratelimit-used: 3
```

## Possible Implementation

As the URL processors does not currently have any logging instance injected there is no non-breaking implementation if logging is the goal.

Another possibility would be for the `GithubUrlReader` to detect this case and throw another error like `Error: GitHub rate limit exceeded`.

## Context

We are using the GitHub App installation which should give us some high limits on requests.
The scraped GitHub organization has around 600 repositories and >100 members spread through >20 teams.

Further more we have several custom processors that does lookups for different files along with the `GitHubOrgReaderProcessor`

**Comment by Crevil** [comment]
I've been thinking about this a bit more and I think we should catch this state and return a dedicated error. As an operator it is relevamt to see the exact cause and the 403 error just doesn't add any context as such.

We'd be happy to implement this if it aligns with you views. 🙏

**Comment by jhaals** [comment]
Hey!

Thanks for bringing this up. I personally like the idea of updating the GitHubUrlReader and append `(ratelimit exceeded)` or something similar to the error message.

For your rate limiting issues, I'd suggest configuring GitHub Apps for authentication https://backstage.io/docs/plugins/github-apps and look at caching for your custom processors https://backstage.io/docs/features/software-catalog/external-integrations#caching-processing-results

**Comment by Crevil** [comment]
Yeah, it could be as little as that 👍

(We already use the Github Apps integration. We increased the catalogs refresh interval which "fixed" the issue which makes me even more convists this is rate limit caused)
