### ISSUE TITLE
Default Dark Mode is too bright

### ISSUE THREAD

**Issue by MvRemmerden** [backstage/backstage#7633]
## Feature Suggestion

The default Dark Mode is too bright, as `material-ui` is **optimized for mobile and not for desktop**. In addition to that, there are a few further aspects that could be improved:

- The left sidebar is the primary navigation component, so it **should be the darkest**. Instead it has the same color as e.g. a table on the detail view, creating a confusing visual hierarchy.
- There are **too many grey shades** with the zebra striping, the active states for radio, etc... 

## Possible Implementation

If we were to simply apply the Dark Mode colors from the Spotify App UI and removed Zebra striping, it could look like this: 

| Before | After |
| ----- | ----- |
| ![image](https://user-images.githubusercontent.com/18680169/137483836-d5e8e78b-bef7-4506-b686-c05a172d4d99.png) | ![image](https://user-images.githubusercontent.com/18680169/137483888-03d9a44b-9731-4258-9943-776e1140a2f8.png) |
| ![image](https://user-images.githubusercontent.com/18680169/137483996-d0955165-3ab9-4733-9628-41dd883a2761.png) | ![image](https://user-images.githubusercontent.com/18680169/137484021-204cb038-e9a7-4c70-9981-f3bef07999f1.png) |

**Comment by katz95** [comment]
This is great! Thanks for bringing this up!

**Comment by MvRemmerden** [comment]
@katz95 @Rugvip What do you think would be the smartest approach here? Should we create a PR to just make these the new default values, or is there something else you would prefer? 🙂

**Comment by katz95** [comment]
Wonderful, feel free to create a PR. For reference, I've attached two screenshots regarding the color choices for dark mode. The base color is 121212. The elevated background is 242424. The tinted background is 252525.

<img width="558" alt="Screenshot 2021-11-11 at 11 43 08 AM" src="https://user-images.githubusercontent.com/61153904/141284614-97f316d6-a080-4484-8a88-26a8cc017fe5.png">

<img width="563" alt="Screenshot 2021-11-11 at 11 43 24 AM" src="https://user-images.githubusercontent.com/61153904/141284607-9482e070-79f0-49dd-9b91-32196abe37ac.png">

**Comment by MvRemmerden** [comment]
@Rugvip I might need extra guidance (just a designer trying to code 😆). I was able to adapt the default colors in the theme, but I'm not sure how to adapt some of the colors that are not mentioned in there.

One example: In my designs, I have changed the right border of the sidebar, but I can't find a variable in the themes that would address that. When looking at the HTML, it seems like the class I would need to change is `.BackstageSidebar-drawer-8`, but I can't find that anywhere in the code base. 

Is there already some documentation for where this part of the code would be, or would you mind expanding a bit on that?

**Comment by jhaals** [comment]
Hi @MvRemmerden!

I'm not sure about the components internals but I think you should be able to name the `makeStyles` inside the component which should allow for overrides. There's some documentation for it here that might be of help https://backstage.io/docs/getting-started/app-custom-theme#overriding-backstage-and-material-ui-components-styles

**Comment by awanlin** [comment]
Can we reopen? Would still love to see this myself. @MvRemmerden are you still working on this?

**Comment by MvRemmerden** [comment]
@awanlin Not currently working on this, too many other things going on. If you want to give it a try, feel free to take over, I could provide the first set of colors based on @katz95 recommendations and do the design review to make sure we fix the smaller pieces together 🙂

**Comment by benjdlambert** [comment]
So a little update is that @katz95 is no longer working on Backstage, https://github.com/backstage/backstage/issues/11686#issuecomment-1216323947, so if someone wants to own this and whip up a PR with what they think is right we can discuss it further in the PR until our new team comes along 🤞

**Comment by MvRemmerden** [comment]
> So a little update is that Kat is no longer working on Backstage, [#11686 (comment)](https://github.com/backstage/backstage/issues/11686#issuecomment-1216323947), so if someone wants to own this and whip up a PR with what they think is right we can discuss it further in the PR until our new team comes along 🤞

@benjdlambert Do you happen to know if there is any designer in the team that I could collaborate with on this?

**Comment by benjdlambert** [comment]
I reached out internally to try and get some eyes on this and get a reply 🤞

**Comment by Rupsnigdha** [comment]
Could you assign this issue to me? Thank you!

**Comment by jhaals** [comment]
Absolutely, good luck @Rupsnigdha! 👏
