### ISSUE TITLE
Entity referenced with ownership (group) always gets stored in lowercase

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#7638]
Lets say we create a group with "BACKSTAGE".
And we create an entity with the name "BackstageEntity" but has a reference of the ownership as "BACKSTAGE" ( group reference ), 

Observation:
The group gets created as  "BACKSTAGE"
The Entity gets created with right name "BackstageEntity", but the ownship reference gets stored as "backstage" instead of "BACKSTAGE" and this creates referential integrity issues.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Create a group with "BACKSTAGE".
Create an entity with the name "BackstageEntity" but has a reference of the ownership as "BACKSTAGE" ( group reference ),

Observation:
The group gets created as "BACKSTAGE"
The Entity gets created with right name "BackstageEntity", but the ownership reference gets stored as "backstage" instead of "BACKSTAGE".
Can you confirm this first?
Now when you select the group "BACKSTAGE" and under the ownership tiler, if you click on the entity, what do you see?

**Comment by freben** [comment]
Of note: We are moving away from compound references and instead returning the string-form (always-lowercase) refs instead. https://github.com/backstage/backstage/pull/9671

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Yes, I saw those changes in the new versions for example, v.1.0.0. Thanks. I will close this ticket now.
