### ISSUE TITLE
Support other data types in annotation catalog entity

### ISSUE THREAD

**Issue by dehamzah** [backstage/backstage#7652]
Backstage as the source of truth of information, makes him to be able to put any information in it, supporting various data type in the catalog entity spec would help the user to put information based on his use cases.

## Feature Suggestion

It would be nice if user can put information in an annotation catalog entity other than string data types.

## Possible Implementation

Add option to extend catalog entity spec of annotation to support other data types than string.

## Context

https://discord.com/channels/687207715902193673/687235481154617364/898236751510929409

In the company that I am working for, there are use case to put information like array of dashboard with named links, array of accounts, and other information that has dynamic size.

**Comment by Rugvip** [comment]
Thank you for the suggestion! This has been discussed before, but we've never quite gotten to the point of being able to motivate the change. It's definitely unfortunate to diverge from the k8s YAML format, so we shouldn't do so without good reason. Another driver for not adding this is that we in the end don't really want annotations to be something that users add by hand most of the time, which makes it fine to have some more machine generated syntax.

Are you able to share a bit more about your use-cases and the need for adding these as annotations? More often than not it'd be fine to extend either the `spec` or `metadata` fields with internal additions directly. The primary function of `annotations` is really to serve as an integration point for open source plugins and bridging together other standardized concerns that we don't want to make part of the base entity schema.

**Comment by roylisto** [comment]
Hi @Rugvip, what if some plugins need multiple data and annotations are mostly used by plugin to see their configuration right?
