### ISSUE TITLE
Sections from Tech Radar disappear when there are too many entries

### ISSUE THREAD

**Issue by julioz** [backstage/backstage#7664]
## Expected Behavior

As seen in the [demo](https://demo.backstage.io/tech-radar), when the tech radar is rendered, we expect four sections to surround the drawing.

## Current Behavior

When there are too many entries to the radar, some of the sections disappear. This must be a rendering bug, since using the 'search' functionality to filter out entries brings the sections back.

Changing the `width` and `height` properties of the React component does not help.

You can plug-in the [ThoughtWorks public radar data](https://docs.google.com/spreadsheets/d/18A7oDuavlh89rAmqcaXpqle8QLqIvlAkoEUxcObzuUM/edit#gid=1985253373) to reproduce the bug.

## Steps to Reproduce

1. Include 100+ entries distributed across the radar data
2. Observe

## Your Environment

- NodeJS Version (v14): v16.8.0
- Operating System and Version (e.g. Ubuntu 14.04): MacOS Big Sur
- Browser Information: Chrome Version 94.0.4606.81

**Comment by julioz** [comment]
Hi @freben, yes I did. Even while scrolling the sections don't show up. I did try opening the same page on Firefox though, and I do see the sections, although they are rendered on top of each other, as the screenshot shows:
<img width="212" alt="Screenshot 2021-10-19 at 06 01 22" src="https://user-images.githubusercontent.com/1541701/137841779-2c0ecc93-b681-4d72-beba-4ad15191d9d3.png">

So I do think there are bugs with the layout when we stress a bit the dataset.

**Comment by benjdlambert** [comment]
Is this something you want to try and fix @julioz?

**Comment by Apaachai** [comment]
Oh really, hm that’s weird. Because when I add hundreds of entries in the radar and try to render/view it in Firefox, there is still an overflow between the quadrants/sidebars. Hence, the scrolling does not work as well in Firefox. I have forked the backstage repo last week, maybe it has been fixed since then? I will try it out again later.
<img width="459" alt="Screenshot 2022-07-15 at 12 31 12" src="https://user-images.githubusercontent.com/44773696/179206941-4e0b9309-b991-4c20-b04b-2b426b7a62f4.png">

**Comment by Apaachai** [comment]
@benjdlambert Yes please, I would like to provide a solution (create a pull request) for this issue.

**Comment by Apaachai** [comment]
> @Apaachai no, apologies this was closed as stale. If you want to take a look at fixing this, then let me know and I will assign you and re-open this ticket.

@benjdlambert Yes please, I would like to provide a solution (create a pull request) for this issue.

**Comment by benjdlambert** [comment]
You're assigned! Sorry I missed your previous message!~

**Comment by Apaachai** [comment]
> You're assigned! Sorry I missed your previous message!~

No worries :) I have now created a PR for this issue now, please take a look whenever your time allows it.

**Comment by jhaals** [comment]
Closing this! Please reopen if needed :)
