### ISSUE TITLE
Ability to override webpack config from backstage app

### ISSUE THREAD

**Issue by alzafacon** [backstage/backstage#7682]
## Expected Behavior

I would like to be able to override/extend the webpack config with extra plugins.
this way I can customize my build, and support older browsers if needed.

## Current Behavior

there is no way to customize the webpack plugins. 

## Possible Solution

allow for a webpack.config.js file to be included in the root of a backstage app.

## Steps to Reproduce

1. visit backstage on chrome 79

## Context

due to personal reasons my backstage app must run on chrome 79. 
chrome 79 does not support optional chaining, but I can't configure webpack to add the appropriate babel plugins to compile optional chaining in backwards compatible way.

plugin desired @babel/plugin-proposal-optional-chaining

## Your Environment

- NodeJS Version (v14): 14
- Operating System and Version (e.g. Ubuntu 14.04): windows
- Browser Information: chrome 79

**Comment by adecchi-2inno** [comment]
how can i create the webpack.config.js to be able to debug the fronend ?
