### ISSUE TITLE
Add extra logs if a `publish` action fails so that users know how to proceed. 

### ISSUE THREAD

**Issue by OscarDHdz** [backstage/backstage#7683]
## Feature Suggestion
* Add logging/messaging if a `publish` action fails so that users know how they proceed. 
 
## Possible Implementation

* Add a couple of `ctx.logger.info` statements after a `publish` action has failed. 

## Context
When something fails as part of a publish action (Github screenshot i.e.) it logs the error and template execution stops.
![image](https://user-images.githubusercontent.com/18434722/138005628-92edf0fe-dd62-4cea-b2d0-18d9b2451df5.png)

We think `publish` actions are the starting point of a template execution, and if it fails, we can say users can easily try again the template without compromises.  It would be nice to have additional logging/messaging to tell the user that is executing a template that is fine to retry 👍  Something like:
> Failed to publish code, feel free to delete repo and try again
// or  even
Failed to create remote, please try again.

> Note:
We are currently only using `publish:github` action, but this could apply to other `publish` actions 😄 .

**Comment by benjdlambert** [comment]
@OscarDHdz how do you think you would go about fixing this? what you're thoughts?
