### ISSUE TITLE
Testers Wanted: `scaffolder.backstage.io/v1beta3` templates

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#7686]
Hey 👋 

We've recently rolled out the ability to create new `beta3` templates, which brings with it some nice new features as well as aligned template syntax's throughout Backstage. No more handlebars!

We'd really appreciate it if you could give the [migration guide](https://backstage.io/docs/features/software-templates/migrating-from-v1beta2-to-v1beta3) a try on maybe just a few of your templates,  maybe some simple and some complex, and run them to see if they operate as expected. Feel free to call them something different in the `yaml` so you don't have to roll back.

Let us know any feedback on this issue!

Also, this is not a deprecation warning! we're not saying you need to upgrade all of your templates immediately! That will happen after we feel that it's all in a good place and working as expected!

Thanks!
@backstage/maintainers

**Comment by ProticM** [comment]
I'm having the same issue like @Fox32 while parsing strings. Examples that fail:

- ./skeleton
- View Pull Request

The template works, but with parsing errors in the log

**Comment by brethubbard** [comment]
We noticed an issue when moving to v1beta3. When referencing the output of steps,
```yaml
- url: ${{ steps.publish-github.output.remoteUrl }}
```
`publish-github` doesn't work in `v1beta3` but it did in `v1beta2`. If we switch it to `publishGithub` it works.

I'm sure this is documented in handlebars and/or nunjucks documentation but I thought I'd point it out here as it seems to be a breaking change that wasn't documented in the migration guide.

**Comment by ProticM** [comment]
@benjdlambert Any movement towards avoiding the string rendering error message of valid strings that are not templated?

**Comment by benjdlambert** [comment]
@ProticM sorry, been OOO for a week, just coming back round to this now. Yeah of course I think we can probably come up with a solution here, but need to have a little more thought about when we should log errors. I guess it's when we can't parse an `object` properly.

**Comment by brethubbard** [comment]
> @brethubbard very interesting - and to confirm that the `id ` of your step is `publish-github` right? Looks like we should add that to the migration guide as a breaking change, although it's pretty unfortunate that it doesn't support hyphens in the id's.

Yeah the I'd was `publish-github`. I did fail to mention originally that I believe it did work if we used bracket notation so
```yaml
- url: ${{ steps["publish-github"].output.remoteUrl }}
```
I'll have to confirm that's true though

**Comment by benjdlambert** [comment]
@brethubbard can confirm that using the bracket notation does work as expected. The reason is that `publish-github` will evaluate as a math term and provide `NaN` as the result. Doesn't look like theres a nice way around this without using the bracket notation unfortunately.

**Comment by benjdlambert** [comment]
Think we should just add this to the migration guide to be honest to use the bracket notation, or change the step ids to camel cased. It was a nice thing that handlebars supported but it's not supported with nunjucks by the looks of it.

**Comment by ProticM** [comment]
@benjdlambert Can we use Nunjucks syntax outside of the steps in our templates? I have a use case where my template is becoming a bit big and it would be nice to be able to split it and just include the YAML chunks in the main template at the proper places.

Something like:

`{% include '...path-to-my-chunk.yaml' %}`

**Comment by benjdlambert** [comment]
Unfortunately not, it's only the values that are treated as `nunjucks` template variables.

**Comment by ProticM** [comment]
> Unfortunately not, it's only the values that are treated as `nunjucks` template variables.

Ok, tnx for the info

**Comment by Crevil** [comment]
As a work around on the error logs when parsing non-templated value you can template the raw strings

```yaml
key: ${{"value"}}
```

This will remove the error logs until we have a more permanent fix.

**Comment by benjdlambert** [comment]
Good news! I worked out where these log lines were coming from.. It was a bug in the check that we had when parsing the `nunjucks` template to check that it was something that should be parsed. We ended up trying to parse all `non-nunjucks` templates basically... :shrug: 

https://github.com/backstage/backstage/pull/8226

**Comment by skfarhat** [comment]
> @brethubbard very interesting - and to confirm that the `id ` of your step is `publish-github` right? Looks like we should add that to the migration guide as a breaking change, although it's pretty unfortunate that it doesn't support hyphens in the id's.

👋 Spent about a good hour debugging why the migration to `v1beta3` was not working, turns out it was the hyphens in my step's `id`. Good thing I landed on this issue 🙂 

This is still not documented on the migration page https://backstage.io/docs/features/software-templates/migrating-from-v1beta2-to-v1beta3. 

Would you like me to do a PR for this? If so, do you think the below near the end of the page will do? 

> Note: For hyphenated ids, make sure to use `nunjucks` bracket notation. 
> e.g. replace `{{ steps.my-hyphenated-step.output.value }}` with `${{ steps["my-hyphenated-step"].output.value }}` otherwise `nunjucks` will attempt subtraction operation on strings resulting in `NaN`.

**Comment by benjdlambert** [comment]
Ah that's pretty annoying, yeah maybe we should either suggest using the array notation version or using underscores for the step ids. Please go ahead an open a PR updating the docs! 🙏
