### ISSUE TITLE
 Document and remove warnings in Core API’s api reports

### ISSUE THREAD

**Issue by jhaals** [backstage/backstage#7688]
This meta ticket describes changes required to the API documentation in order to release Backstage Core APIs as version 1.0

The following warnings need to be removed before an item should be crossed in the list below:

- Exported methods must have documentation. Missing documentation is indicated by `// @public (undocumented)` in the api report. Best practises for writing API documentation can be found in #7162
- All type names used by the API need to be exported. Please note that type name has previously not been exported and might therefore need a new name suitable for external use. This is indicated by `// Warning: (ae-forgotten-export) The symbol "FoobarOptions" needs to be exported by the entry point index.d.ts`
- Package exports must be marked `@public`. `// Warning: (ae-missing-release-tag) "FiltersButton" is exported by the package, but it is missing a release tag (@alpha, @beta, @public, or @internal)`

Documentation added to all exports:

- [x] config
- [x] theme
- [x] version-bridge
- [x] cli-common
- [x] config-loader
- [x] core-app-api
- [x] test-utils
- [x] test-utils-core
- [x] core-plugin-api
- [x] errors

Exports marked as public

- [x] config
- [x] theme
- [x] version-bridge
- [x] cli-common
- [x] config-loader
- [x] core-app-api
- [x] test-utils
- [x] test-utils-core
- [x] core-plugin-api
- [x] errors

Type names exported

- [x] config
- [x] theme
- [x] version-bridge
- [x] cli-common
- [x] config-loader
- [x] core-app-api
- [x] test-utils
- [x] test-utils-core
- [x] core-plugin-api
- [x] errors

**Comment by djamaile** [comment]
cli package doesn't generate a `api-report.md` file for me, does it work for you?
