### ISSUE TITLE
Review public utility APIs

### ISSUE THREAD

**Issue by jhaals** [backstage/backstage#7690]
Go through list of public utility APIs and make sure that major concerns are fixed before 1.0

- [ ] `AlertApi`
- [ ] `AnalyticsApi`
- [ ] `appThemeApiRef`
- [ ] `auth`
- [ ] `ConfigApi`
- [ ] `DiscoveryApi`
- [ ] `ErrorApi`
- [ ] `FeatureFlagsApi`
- [ ] `IdentityApi`
- [ ] `oauthRequestApi`
- [ ] `StorageApi`

**Comment by Rugvip** [comment]
This was done, with the output being tracked in #8412
