### ISSUE TITLE
Backstage not working in Chrome 

### ISSUE THREAD

**Issue by sarahpmedeiros** [backstage/backstage#7750]
Backstage is not working in Chrome version Version 94.0.4606.54
## Expected Behavior
On yarn start the application should load and show page to select a sign-in method.

## Current Behavior
Seeing 

```
This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```
The page is loading in Firefox.

## Steps to Reproduce
Following the documentation to run Backstage locally and go to localhost:3000 in Chrome after the application is running.

## Your Environment

- NodeJS Version (v14): v14.17.6
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS Big Sur v 11.6
- Browser Information: Version 94.0.4606.54 (Official Build) (x86_64)

OS:   Darwin 20.6.0 - darwin/x64
node: v14.17.6
yarn: 1.22.1
cli:  0.8.0 (local)

Dependencies:
  @backstage/catalog-client       0.3.19
  @backstage/core-api             0.2.23
  @backstage/core-components      0.3.3, 0.4.2, 0.5.0, 0.6.1
  @backstage/core                 0.7.14
  @backstage/plugin-catalog-react 0.4.6, 0.5.2

**Comment by freben** [comment]
Haven't seen a report like this before. Could it somehow be because of company security policies or extensions that make this specific to that browser? Does it make any difference if you try the same in incognito mode?

**Comment by sarahpmedeiros** [comment]
If this issue is only happening on my machine then it most likely is a security policy issue. Thank you for looking into this I think it can be closed and I can look into it more internally. It also seems to be working today even though I haven't changed anything since updating Chrome. 

I'm sorry, thanks for looking!

**Comment by benjdlambert** [comment]
No worries @sarahpmedeiros let us know how it goes and if you find anything!
