### ISSUE TITLE
[Search] Handle search indexing coordination among nodes

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#7784]
## Feature Suggestion

Coordinate running search indexing on the collators between the deployed backend nodes to avoid clashing/duplication of work.

## Possible Implementation

Maybe use a similar mechanism as entity processing by placing index tasks in the DB to be claimed by available nodes. 

## Context

I believe I am running into the following issue according to @iamEAP :

> Two nodes booting up at about the same time could trample over themselves as they try and rotate out indices (there is a system in place that writes net-new indices and then flips an alias pointer -- but if two nodes try and do that operation at the same time, it may fail them both and delete everything

This results in intermittent failures when trying to use search until a new index run is triggered.

**Comment by freben** [comment]
#7612 is merged and #8567 (optional) is in the pipe.

**Comment by kuangp** [comment]
Revisiting this now that the above mentioned PRs have been merged and released. However, I'm not quite sure how the task schedule can currently be used along with the `IndexBuilder` scheduler?

From what I understand, [`IndexBuilder`](https://github.com/backstage/backstage/blob/4045eaab952fec349e443990330bd1ac5b2c9c18/plugins/search-backend-node/src/IndexBuilder.ts#L96) should be refactored to be constructed with an instance of `TaskScheduler` which is passed to [`Scheduler`](https://github.com/backstage/backstage/blob/4045eaab952fec349e443990330bd1ac5b2c9c18/plugins/search-backend-node/src/Scheduler.ts) which in turn could act as a wrapper delegating the actual task to `TaskScheduler`. However [`Scheduler.stop()`](https://github.com/backstage/backstage/blob/4045eaab952fec349e443990330bd1ac5b2c9c18/plugins/search-backend-node/src/Scheduler.ts#L70) seems to have no corresponding support in `TaskScheduler` at the moment ...

@freben @benjdlambert thoughts?

**Comment by freben** [comment]
Yeah the task scheduler does not have an explicit stop method, instead all [task invocations accept](https://github.com/backstage/backstage/blob/f0050d457e8f0035ae9ec84c8857a8f8749c84a2/packages/backend-tasks/src/tasks/types.ts#L53) an `AbortSignal` which when triggered will stop all execution.

I see that the only actual usage of `Scheduler.stop` is in the case of [hot module reloading](https://github.com/backstage/backstage/blob/f0050d457e8f0035ae9ec84c8857a8f8749c84a2/packages/backend/src/plugins/search.ts#L95). If one wants to mimic this, you can create an `AbortController` that you pass to all the tasks and call `abort()` on it when an HMR happens.

Either way, yeah, passing in a `TaskScheduler` to `IndexBuilder`, and deprecating `Scheduler`, sounds like it might be the right fix here.

**Comment by freben** [comment]
@kuangp is this something you would be up for trying to implement? :)

**Comment by kuangp** [comment]
yes, I may have some time to look into it this week

**Comment by emmaindal** [comment]
That would be awesome @kuangp, do you want me to assign you to this issue?
