### ISSUE TITLE
Support systems in OwnershipCard component 

### ISSUE THREAD

**Issue by jvilimek** [backstage/backstage#7806]
See the current visualization of our team in Backstage. There is currently missing the entity kind "system" ownership.

![image](https://user-images.githubusercontent.com/16001792/139115150-c917ecc3-f990-4754-bbd9-bf0367c24086.png)

## Feature Suggestion

Since there is always an owner specified also for System entity it should be visible among other components in the org ownership card page. Or at least make this configurable.

## Possible Implementation

see [OwnershipCard](https://github.com/backstage/backstage/blob/master/plugins/org/src/components/Cards/OwnershipCard/OwnershipCard.tsx)
```
const kinds = ['Component', 'API'];
```
I kindly suggest either adding also "System" entity kind here or make this somehow configurable.

## Context

We consider system an entity might encapsulates multiple backend and frontend components with usually one team as an owner. Thus we would like to see that component in the ownership card.

**Comment by freben** [comment]
Yeah the display probably needs to be tweaked a bit when the type disappears. Maybe it should always show the type AND kind (or just kind if there's no type) in the cards?

Either way, it makes sense to show everything that's ownable there, so changing the defaults makes sense to me.

Another way of doing it might be to not have the kind filter at all, and instead show everything based on whether they have the right `ownedBy` relation - no matter what.

Is this something (in either of the proposed forms) you'd like to work on?

**Comment by jvilimek** [comment]
@freben Yep. Sorry for not letting you know earlier, I have poked around this issue this weekend and "just did it"... hopefully in the right way..

**Comment by jvilimek** [comment]
I believe this is now solved.
