### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by nodify-at** [backstage/backstage#7818]
If we start a webpack dev. server, an overlay with this warning displayed on an overlay div. We need to close this windows each time after starting the dev. server and we can not resolve this warning because it is a sub dependency of backstage core component.

Warning output:
WARNING in ../../node_modules/power-assert-formatter/lib/create.js 30:28-49
Critical dependency: the request of a dependency is an expression

`yarn why power-assert-formatter` output:

```
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "power-assert-formatter"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "power-assert-formatter@1.4.1"
info Reasons this module exists
   - "_project_#app#@backstage#core-components#react-markdown#remark-parse#mdast-util-from-markdown#power-assert" depends on it
   - Hoisted from "_project_#app#@backstage#core-components#react-markdown#remark-parse#mdast-util-from-markdown#power-assert#power-assert-formatter"
info Disk size without dependencies: "408KB"
info Disk size with unique dependencies: "10.22MB"
info Disk size with transitive dependencies: "12.1MB"
info Number of shared dependencies: 10
✨  Done in 1.46s.

```
## Expected Behavior

- This warning should be resolved.
- Config file or CLI args. can be applied to webpack dev. server

## Current Behavior

A Warning has been logged after server start.
A Warning windows blocks the page until user closes this panel. It happens each time whenever the server starts.

## Possible Solution

In best case we expect to resolve this warning. Backstage can try to update to latest version of react-markdown or try to create an issue on react-markdown module. 

Creating an issue only to react-markdown does not help us to resolve this issue, backstage must also upgrade to the related version after fixing the error.

At least we should be to configure "overlay.client" parameter of webpack dev. server to disable overlay panel for warnings. This may be a temp. solution while we are waiting a fix which resolves this warning.

## Steps to Reproduce

1. yarn start ( calls backstage-cli app:serve)
2. see console logs to see this warning
3. open web page to see the overlay

## Context

During the development we need to close each time this window and we can not able to resolve this issue in any way. We can not control webpack dev. server options to manage when this windows should display the logs. In some cases it is enough to see errors on this window only, we can still see the warnings in the console.

## Your Environment

```
OS:   Darwin 21.1.0 - darwin/x64
node: v14.18.1
yarn: 1.22.17
cli:  0.8.0 (installed)

Dependencies:
  @backstage/backend-common                                0.9.7
  @backstage/catalog-client                                0.5.0
  @backstage/catalog-model                                 0.9.5
  @backstage/cli-common                                    0.1.4
  @backstage/cli                                           0.8.0
  @backstage/config-loader                                 0.7.0
  @backstage/config                                        0.1.10
  @backstage/core-app-api                                  0.1.18
  @backstage/core-components                               0.7.1
  @backstage/core-plugin-api                               0.1.11
  @backstage/dev-utils                                     0.2.12
  @backstage/errors                                        0.1.3
  @backstage/integration-react                             0.1.12
  @backstage/integration                                   0.6.8
  @backstage/plugin-api-docs                               0.6.12
  @backstage/plugin-auth-backend                           0.4.5
  @backstage/plugin-badges                                 0.2.13
  @backstage/plugin-catalog-backend                        0.17.1
  @backstage/plugin-catalog-import                         0.7.3
  @backstage/plugin-catalog-react                          0.6.1
  @backstage/plugin-catalog                                0.7.2
  @backstage/plugin-code-coverage                          0.1.15
  @backstage/plugin-explore-react                          0.0.6
  @backstage/plugin-explore                                0.3.20
  @backstage/plugin-github-actions                         0.4.22
  @backstage/plugin-graphiql                               0.2.20
  @backstage/plugin-jenkins-backend                        0.1.6
  @backstage/plugin-jenkins                                0.5.11
  @backstage/plugin-kafka                                  0.2.19
  @backstage/plugin-kubernetes-backend                     0.3.18
  @backstage/plugin-kubernetes-common                      0.1.5
  @backstage/plugin-kubernetes                             0.4.17
  @backstage/plugin-lighthouse                             0.2.29
  @backstage/plugin-org                                    0.3.27
  @backstage/plugin-proxy-backend                          0.2.13
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.2
  @backstage/plugin-scaffolder-backend                     0.15.10
  @backstage/plugin-scaffolder-common                      0.1.0
  @backstage/plugin-scaffolder                             0.11.8
  @backstage/plugin-search-backend-node                    0.4.2
  @backstage/plugin-search-backend                         0.2.6
  @backstage/plugin-search                                 0.4.15
  @backstage/plugin-shortcuts                              0.1.12
  @backstage/plugin-sonarqube                              0.2.6
  @backstage/plugin-tech-radar                             0.4.11
  @backstage/plugin-techdocs                               0.12.3
  @backstage/plugin-user-settings                          0.3.10
  @backstage/search-common                                 0.2.0
  @backstage/techdocs-common                               0.10.4
  @backstage/test-utils-core                               0.1.3
  @backstage/test-utils                                    0.1.19
  @backstage/theme                                         0.2.11
  @backstage/version-bridge                                0.1.0
✨  Done in 0.92s.
```

**Comment by freben** [comment]
Alright, just acknowledging that I've seen this.

I can see the require [in their source code](https://github.com/power-assert-js/power-assert-formatter/blob/master/lib/create.js#L30), and there have been no changes there for many years. No apparent related issues on GitHub for `react-markdown` as far as I can see.

`mdast-util-from-markdown` [added that dependency](https://github.com/syntax-tree/mdast-util-from-markdown/commit/a13fbcc27de7f2e44212e65b9788caf7b7f62b0e#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) a month ago. They then pretty quickly [backtracked on that](https://github.com/syntax-tree/mdast-util-from-markdown/commit/ff32dafa0158cb477b7f2e009b8711592c0777e6#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519).

You should be able to bump your `mdast-util-from-markdown` dependency in yarn, to see if that gets rid of the problem.

**Comment by nodify-at** [comment]
@freben Thank you! After resolving this dependency explicitly to a newer version, this warning does not appear anymore.

I think it would be also a good feature to be able to send webpack dev. server parameters via backstage cli. We can customise the server for our needs. I can try to create a PR for this improvement, if this feature makes also sense for backstage community :)

**Comment by Rugvip** [comment]
@nodify-at If there are some specific parameters that would be useful to pass through I think that's all good. We want to avoid too much customization of the webpack setup itself though because we want to maintain the flexibility to switch those pieces out as needed.

**Comment by nodify-at** [comment]
At this moment I am not sure which parameters could be specified to pass :) If I need some special params, I will create another issue. Thanks for your support, this issue has been resolved after upgrading the mdast-util-form-markdown using a resolution to force to use a newer version.
