### ISSUE TITLE
"Undefined" kind for customresource

### ISSUE THREAD

**Issue by camaeel** [backstage/backstage#7821]
I configured StatefulSet as a CustomResource. But its kind label says undefined.

<img width="1460" alt="Screenshot 2021-10-28 at 16 25 35" src="https://user-images.githubusercontent.com/12999736/139276237-fb43ceed-d6c5-4228-8bdf-a702a0e8d505.png">
## Expected Behavior

I'd expect it shows StatefulSet as it's type under the name on Accordion

## Current Behavior

I get undefined. 

## Steps to Reproduce

1. Setup kubernetes plugin in backstage.
2. Add CustomResource to the kubernetes configuration:
```
kubernetes:
  customResources:
    - group: 'apps'
      apiVersion: 'v1'
      plural: 'statefulsets'
```
3. On the kubernetes cluster create Statefulset and grant access for backstage to read StatefulSets.
4. Configure Component that points to this StatefulSet by correct label

## Context

I want to show additional resources on Kubernetes page. 

## Your Environment

- NodeJS Version (v14): v14
- Operating System and Version (e.g. Ubuntu 14.04): macos BigSur
- Browser Information: Firefox 93.0, Chrome Version 95.0.4638.54 (Official Build) (x86_64)

**Comment by chuliang014** [comment]
running into this issue currently.
![image](https://user-images.githubusercontent.com/56138162/145971225-8f668e3e-e567-455a-9ca7-26cdf40e0fa2.png)

**Comment by chuliang014** [comment]
any updates on this? I also have the same issue on fetching StatefulSet and DeamonSet.
![image](https://user-images.githubusercontent.com/56138162/146291445-e53cf1b1-9596-4dbc-92c1-819c147ad122.png)

**Comment by freben** [comment]
@mclarke47 maybe? I don't have a great setup to test this - but it does seem like the kind isn't carried over from the backend.

**Comment by mclarke47** [comment]
Yup, I can look at this when I get a second

**Comment by benjdlambert** [comment]
Ping @mclarke47 :pray:
