### ISSUE TITLE
create a publish:gitlab:merge-request action

### ISSUE THREAD

**Issue by djamaile** [backstage/backstage#7828]
Currently there is a such action but only for github. It would be nice if something similar would be created for Gitlab. 

## Feature Suggestion

I think this would a great action for teams to create a catalog-info.yaml for there existing repo's. For example, they can choose to scaffold a catalog-info.yaml file by filling in some properties. Afterwards a merge request for their repository will be created. This makes product teams more inclined to migrate their repo towards backstage.  

## Possible Implementation

Not sure yet how this would look in code. But I know with `@gitbeaker/node` it is possible to create a merge request.

**Comment by dublx** [comment]
Following updates from @satrox28, we're highly interested in that too, same use case as described here.
Some other use case that would benefit from this is described in this comment: https://github.com/backstage/backstage/issues/7799#issuecomment-966184585

**Comment by satrox28** [comment]
Hi,

We have submitted the initial PR here https://github.com/backstage/backstage/pull/7940

**Comment by shvmbisht** [comment]
@satrox28 please include a sample template for the PR u raised.  Thanks 💯

**Comment by satrox28** [comment]
Hi @shvmbisht please refer here for the Gitlab MR template https://github.com/backstage/software-templates/pull/7

**Comment by djamaile** [comment]
@satrox28 how is the progress going with the PR?

**Comment by shvmbisht** [comment]
@satrox28 thanks a ton for the template, I also made some changes to the template as I use `fetch:template` for all templates, I also tested your  [initial PR](https://github.com/backstage/backstage/pull/7940),  it works functionality-wise 👍

**Comment by djamaile** [comment]
this is fixed in #8277 so I will be closing this issue. @Balasundaram thanks for your work!
