### ISSUE TITLE
Add support to insert a processor before the defaultProcessors in the CatalogBuilder

### ISSUE THREAD

**Issue by bryce-od** [backstage/backstage#7834]
I would like to add a `CatalogProcessor` that is run before the `defaultProcessors`.
Our company has a custom yaml file type, that we convert to an entity that is emitted, then we can return `true`.

We would like to use the great ecosystem of processors such as `GithubDiscoveryProcessor` and `BitbucketDiscoveryProcessor`, however since they both return a target type of `url`, the `UrlReaderProcessor` will attempts to process the file, (and throw an errors) before our Custom Processor is able to make decide if it is a catalog-info.yaml format OR our custom yaml.

## Feature Suggestion

Without having to copy / paste / maintain the default set of processors, add support to allow for our custom processors be run before the defaults.

## Possible Implementation

current code:
```ts  
    // These are only added unless the user replaced them all
    if (!this.processorsReplace) {
      processors.push(
        new FileReaderProcessor(),
        BitbucketDiscoveryProcessor.fromConfig(config, { logger }),
        GithubDiscoveryProcessor.fromConfig(config, { logger }),
        GithubOrgReaderProcessor.fromConfig(config, { logger }),
        GitLabDiscoveryProcessor.fromConfig(config, { logger }),
        new UrlReaderProcessor({ reader, logger }),
        CodeOwnersProcessor.fromConfig(config, { logger, reader }),
        new AnnotateLocationEntityProcessor({ integrations }),
      );
    }

    // Add the ones (if any) that the user added
    processors.push(...this.processors);
```

Option 1)
`builder.addProcessor` - instead of being is added AFTER the default processors add it BEFORE the defaults.
This might be a breaking change.

```ts  
    // Add the ones (if any) that the user added
    processors.push(...this.processors);

    // These are only added unless the user replaced them all
    if (!this.processorsReplace) {
      processors.push(
        new FileReaderProcessor(),
        BitbucketDiscoveryProcessor.fromConfig(config, { logger }),
        GithubDiscoveryProcessor.fromConfig(config, { logger }),
        GithubOrgReaderProcessor.fromConfig(config, { logger }),
        GitLabDiscoveryProcessor.fromConfig(config, { logger }),
        new UrlReaderProcessor({ reader, logger }),
        CodeOwnersProcessor.fromConfig(config, { logger, reader }),
        new AnnotateLocationEntityProcessor({ integrations }),
      );
    }
```

Option 2)
`builder.insertProcessor` - extend the `CatalogProcessor` with another method that would, hold another array of processors that will be inserted BEFORE the default processors.

```ts  
    // Add the ones (if any) that the user needs before the defaults
    processors.push(...this.insertProcessors);

    // These are only added unless the user replaced them all
    if (!this.processorsReplace) {
      processors.push(
        new FileReaderProcessor(),
        BitbucketDiscoveryProcessor.fromConfig(config, { logger }),
        GithubDiscoveryProcessor.fromConfig(config, { logger }),
        GithubOrgReaderProcessor.fromConfig(config, { logger }),
        GitLabDiscoveryProcessor.fromConfig(config, { logger }),
        new UrlReaderProcessor({ reader, logger }),
        CodeOwnersProcessor.fromConfig(config, { logger, reader }),
        new AnnotateLocationEntityProcessor({ integrations }),
      );
    }

    // Add the ones (if any) that the user needs after the defaults
    processors.push(...this.processors);

```

## Context

There has a few issues that are similar, this it feels like `replaceProcessors` is problematic.

https://github.com/backstage/backstage/issues/5388
https://github.com/backstage/backstage/pull/5414
https://github.com/backstage/backstage/issues/6542
https://github.com/backstage/backstage/issues/7661

**Comment by regicsolutions** [comment]
@bryce-od was wondering if you are adding any additional default processors outside of the processors defined below?  When i use `addProcessors` i don't get this error, wasn't sure if i may be missing a processor...

`Error: scaffolder error Failed to parse template string: /catalog-info.yaml with error Unexpected token / in JSON at position 0 type=plugin`

```
import {
    AnnotateLocationEntityProcessor,
    BitbucketDiscoveryProcessor,
    CatalogBuilder,
    FileReaderProcessor,
    LocationEntityProcessor,
    UrlReaderProcessor,
  } from '@backstage/plugin-catalog-backend';
  import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
  import { Router } from 'express';
  import { PluginEnvironment } from '../types';
  import { ScmIntegrations } from '@backstage/integration';
  import { customBitbucketRepositoryParser } from './catalog/customBitbucketRepositoryParser';

  export default async function createPlugin(
    env: PluginEnvironment,
  ): Promise<Router> {
    const integrations = ScmIntegrations.fromConfig(env.config);
    const builder = await CatalogBuilder.create(env);
  
    builder.replaceProcessors([
      new ScaffolderEntitiesProcessor(),
      new FileReaderProcessor(),
      BitbucketDiscoveryProcessor.fromConfig(env.config, {
        parser: customBitbucketRepositoryParser,
        logger: env.logger,
      }),
      new UrlReaderProcessor({ reader: env.reader, logger: env.logger }),
      new LocationEntityProcessor({ integrations }),
      new AnnotateLocationEntityProcessor({ integrations }),
    ]);

    const { processingEngine, router } = await builder.setRefreshIntervalSeconds(600).build();
    await processingEngine.start();
    return router;
  }
```

**Comment by bryce-od** [comment]
@jhaals 

I created a PR, let me know what you think:
https://github.com/backstage/backstage/pull/7885

I was not able to make the method static without including the all of the args to wire up the config, logger etc, so I opt-ed to just make it an instance method.

**Comment by jhaals** [comment]
Thanks @bryce-od! Looks good and I just merged it in 👍  Great contribution

**Comment by regicsolutions** [comment]
@bryce-od how are you adding getDefaultProcessors in your catalog.ts? After this change I am getting the following error when using replaceProcessors: 


info.message.replace is not a function type=plugin entity=location:default/generated-3bde7d383af466010592c866ff6e704a05451302`
