### ISSUE TITLE
[Plugin] New Relic Dashboards

### ISSUE THREAD

**Issue by mufaddal7** [backstage/backstage#7849]
## Summary

Import [dashboards](https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards/#:~:text=To%20access%20dashboards%2C%20go%20to,with%20your%20New%20Relic%20account.&text=Account%3A%20The%20account%20the%20dashboard,user%20who%20created%20the%20dashboard) from New Relic. 

The imported snapshot(image) can be visible in a new tab for Kind component, user, group, etc. 

The imported dashboard image is a **real-time snapshot** of the particular entity. 

## Context

Many organizations use New Relic Dashboards, it would be a helpful feature to see New Relic dashboard snapshots 
New Relic provides support for this feature via nerdgraph. 

Requirements for the plugin to work 
- API key (Needs to be provided in the app.config.yaml)
- Dashboard GUID (Will be entered by the user in catalog descriptor file)

**Comment by Rugvip** [comment]
Sound like a good idea! Is this something you want to work on @mufaddal7 or should we open it up for contributions?

**Comment by mufaddal7** [comment]
Yes, I would like to work on this. You may assign it to me.

**Comment by Rugvip** [comment]
Fixed by #8201 🎉
