### ISSUE TITLE
In code coverage plugin, the Explore Files bread crumb links do not work

### ISSUE THREAD

**Issue by jeremyguarini** [backstage/backstage#7867]
When viewing a code coverage report, there is the Explore Files section at the bottom.  Clicking on a parent in the bread crumb results in no files listed and cannot get back to original file listing view.

## Expected Behavior

When clicking on a link in the bread crumb the list of files would update with the relevant file listing. I should be able to navigate all the way back to the original view.

## Current Behavior

When clicking on a link in the bread crumbs, no files are listed and the link appears to be broken (see screen shots)

image showing bread crumbs before clicking on any of the links
<img width="435" alt="Screen Shot 2021-11-01 at 4 32 49 PM" src="https://user-images.githubusercontent.com/23618053/139756229-6f9b58ee-300a-4a1f-a4dc-d4c28111815e.png">

image showing bread crumb after clicking on backend-common link
<img width="297" alt="Screen Shot 2021-11-01 at 4 32 54 PM" src="https://user-images.githubusercontent.com/23618053/139756275-66409a7e-1345-400b-a521-3d709a6abcf0.png">

starting from the same location of `root/packages/backend-common/src/` and clicking on `packages` we can see that the `root` part of the path is dropped but the list of files is actually shown. So this is only partly broken in that one cannot get back to `root` view.
<img width="346" alt="Screen Shot 2021-11-01 at 4 45 36 PM" src="https://user-images.githubusercontent.com/23618053/139756862-f0eca03b-26f6-4e5d-a7c7-5d5585bed135.png">

## Steps to Reproduce

Upload a code coverage report for the component. View the report and drill down in the Explore Files to get a few directories deep. Next click on a parent or grandparent link in the bread crum.

## Context

Unable to navigate back or up a directory to view other files.

## Your Environment

```
yarn backstage-cli info
OS:   Darwin 20.6.0 - darwin/x64
node: v16.9.1
yarn: 1.22.1
cli:  0.8.1 (local)

Dependencies:
  @backstage/catalog-client       0.3.19
  @backstage/core-components      0.6.1
  @backstage/plugin-catalog-react 0.5.2
```

- Browser Information: Chrome Version 95.0.4638.54 (Official Build) (x86_64)

**Comment by eoghanmcilwaine** [comment]
Hey folks 👋  Is help still needed on this? Mind if I take it on?

**Comment by jeremyguarini** [comment]
I'll need to check to see if the issue has been resolved. 
-------- Original message --------From: Eoghan McIlwaine ***@***.***> Date: 1/28/22  5:17 AM  (GMT-08:00) To: backstage/backstage ***@***.***> Cc: jeremyguarini ***@***.***>, Author ***@***.***> Subject: Re: [backstage/backstage] In code coverage plugin, the Explore Files bread crumb links do not work (Issue #7867) 

Hey folks 👋  Is help still needed on this? Mind if I take it on?

**Comment by jhaals** [comment]
@eoghanmcilwaine absolutely! Just make sure to double check that you can reproduce this. I'm assigning you to the issue.

**Comment by eoghanmcilwaine** [comment]
Nice, thanks @jhaals! It's still reproducible as follows:

1. Import the test data from `plugins/code-coverage-backend/src/service/__fixtures__/cobertura-testdata-1.xml`
2. Under "explore files", click on "com", then "example", then "utils". This should navigate through the file tree.
3. Click on "example" in the breadcrumbs to go back up to that folder.
4. "No files found" appears, and the breadcrumbs become broken and unclickable. Refreshing the page restores correct behaviour.

I'll be pushing a fix shortly.
