### ISSUE TITLE
Support async validation in scaffolder custom field extensions

### ISSUE THREAD

**Issue by alexrybch** [backstage/backstage#7868]
I think it can be useful to have a possibility to add backend validation in scaffolder form

## Feature Suggestion
Async validation in scaffolder form

## Possible Implementation
Allow async validation in `createScaffolderFieldExtension` or maybe pass `addError` method as prop to field component

**Comment by benjdlambert** [comment]
Sorry I missed this, so I think this would be quite a simple thing to implement, we just need to grab the ones that are async and execute them after the sync validation has completed I believe.

**Comment by timbonicus** [comment]
Copying some Discord comments from @benjdlambert:

> I think we need to adjust the signature of the `CustomFieldValidator` [to use Promise] and run the validators all as async, and run them all outside of the validate function. So we would do it in `onNext` of the stepper and then use the `extraErrors` prop for all validation.

> Or we could check if the validation function smells like a Promise and run those in `onNext` and keep the current behavior. Either way works.

> Maybe saying that all validators are async isn’t that much of a breaking change, since you can always `await` a sync value. But if we were to change the signature of course it could be breaking unless we supported both for now

**Comment by benjdlambert** [comment]
To be honest looking through the code, I think this would be much easier to do after a refactor of the `MultiStepForm` and the `TemplatePage` to clarify the boundary between the two and move all validation into the `MultiStepForm` without the mix and match between the two. Will look at coming up for a plan with that first.

**Comment by timharris777** [comment]
Any news on this? We are needing async validation support. We coded our validation code properly but it seems the code is not working properly through the web interface. @jemejones @MarcFogleman

**Comment by benjdlambert** [comment]
Hey :wave: so I've been looking at implementing this in the `NextScaffolderRouter` which is a re-write of the frontend plugin with tests and making it easier to build features like this moving forward. There's no real timeframe set as yet as to how long it's going to take to get it out though unfortunately, but will keep you posted as I work through the re-write.

**Comment by timharris777** [comment]
This is still a desired feature. Please don't close.
