### ISSUE TITLE
diff's in docs site shouldn't include '+' when copying

### ISSUE THREAD

**Issue by timja** [backstage/backstage#7870]
See https://backstage.io/docs/auth/#adding-the-provider-to-the-sign-in-page

```diff
+ import { githubAuthApiRef } from '@backstage/core-plugin-api';
+ import { SignInProviderConfig, SignInPage } from '@backstage/core-components';

+ const githubProvider: SignInProviderConfig = {
+  id: 'github-auth-provider',
+  title: 'GitHub',
+  message: 'Sign in using GitHub',
+  apiRef: githubAuthApiRef,
+};
```

## Feature Suggestion

When I copy config from the docs I should not have the '+' in my copy

## Possible Implementation

Haven't looked but I've seen other tools have this feature, GitHub does it I believe

## Context

Copy paste from docs without annoying me

**Comment by Rugvip** [comment]
Totally agree, but might be tricky to fix 😅, kind of at the mercy of Docusaurus here. We're currently on v1 and it's possible that v2 has a fix for this, but ofc it might not too. I'd avoid any big customizations that aren't also compatible with v2 atm though, as we ofc do want to move over at some point.

**Comment by cmpadden** [comment]
@Rugvip , in the [v1 Docusaurus documentation](https://v1.docusaurus.io/docs/en/doc-markdown#adding-copy-code-buttons) they link to a [set of instructions](https://gist.github.com/yangshun/55db997ed0f8f4e6527571fc3bee4675) for adding a copy button to code blocks. But the final comment on the instructions say, "Please upgrade to Docusaurus v2 instead!". So I suspect that upgrading might be the move!

**Comment by timja** [comment]
not stale

**Comment by timja** [comment]
Go away
