### ISSUE TITLE
[RFC] Should We Publish All Plugins that We Create?

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#7893]
**Status:** Open for comments

## Need

We are at the point where we recognize the need for adding a plugin to our application. We need a couple of custom cards and some other things.

Backstage CLI provides a neat way of creating a plugin, but there is a question that I want to clarify. The default command is:

`backstage-cli create-plugin --scope internal --no-private`

After running it, the plugin will be created with the publish config set up.

Does this mean that you recommend that we publish all our plugins to some private/public registry? It is not a problem for us to publish to GitHub packages or AWS, but in reality, our plugins will be used only by the backstage app, therefore they do not require to be published in terms of being shared among other apps in the organization.

I understand that backstage utilizes Lerna and Yarn workspaces, therefore, installing non-published packages in our backstage instance should not be an issue?

**Comment by Rugvip** [comment]
There's generally no need to publish the plugin packages, it's enough to just build an app bundle and ship that to production, for both frontend and backend. Publishing packages is actually quite unlikely to be done from within a regular app monorepo, any published plugins that I know of have a standalone monorepo or single package repo setup.

... so I think it makes sense to have the plugin packages be private by default, #7907

**Comment by ProticM** [comment]
Yes, agreed.

Good enough for me, we can close this one if nothing is to be added by someone

**Comment by Rugvip** [comment]
Alright, can always reopen if needed too!
