### ISSUE TITLE
[GA Plugin] The ga plugin does not works in docker container

### ISSUE THREAD

**Issue by thiagoluiznunes** [backstage/backstage#7925]
## Expected Behavior

Google Analytics plugin works in docker

## Current Behavior

I installed the google analytics plugin in backstage following the documentation. Its worked perfectly! But, when I ran the docker file suggested by backstage and when I goes to localhost:7000 exposed by container, the google analytics plugin does not send any POST request do my analytics dashboard the opposite when I run using yarn start.

### Using yarn
It can see the google analytics post request:
![image](https://user-images.githubusercontent.com/11435231/140999238-835d4617-72c7-4eff-9a68-a51b60f6f2fe.png)

### Using docker
The request is not sent:
![Screen Shot 2021-11-09 at 17 36 29](https://user-images.githubusercontent.com/11435231/141000763-b6a78496-2ce0-438a-bff8-a27f60717329.png)

I entered in the image crated by docker and I founded code lines about google analytics in the file module-backstage.bb4276ac for exemple the UI-***** analytics tracking ID.

## Steps to Reproduce

1. Install GA plugin following : [ga](https://github.com/backstage/backstage/blob/master/plugins/analytics-module-ga/README.md)
2. Use backstage Dockerfile [docker link](https://backstage.io/docs/deployment/docker#docsNav)
2. Run image

## Context

This is affecting our team because we need monitoring the dev UX in our company.

## Your Environment

Docker version 20.10.8, build 3967b7d
OS:   Darwin 20.6.0 - darwin/x64
node: v14.17.4
yarn: 1.22.11
cli:  0.7.16 (installed)

Dependencies:
  @backstage/backend-common                                0.9.7
  @backstage/catalog-client                                0.5.0
  @backstage/catalog-model                                 0.9.5
  @backstage/cli-common                                    0.1.4
  @backstage/cli                                           0.7.16
  @backstage/config-loader                                 0.6.10, 0.7.0
  @backstage/config                                        0.1.11
  @backstage/core-app-api                                  0.1.18
  @backstage/core-components                               0.7.2
  @backstage/core-plugin-api                               0.1.12
  @backstage/errors                                        0.1.4
  @backstage/integration-react                             0.1.12
  @backstage/integration                                   0.6.8
  @backstage/plugin-analytics-module-ga                    0.1.2
  @backstage/plugin-api-docs                               0.6.12
  @backstage/plugin-app-backend                            0.3.17
  @backstage/plugin-auth-backend                           0.4.5
  @backstage/plugin-catalog-backend                        0.17.1
  @backstage/plugin-catalog-import                         0.7.3
  @backstage/plugin-catalog-react                          0.6.1
  @backstage/plugin-catalog                                0.7.2
  @backstage/plugin-github-actions                         0.4.22
  @backstage/plugin-kubernetes-backend                     0.3.18
  @backstage/plugin-kubernetes-common                      0.1.5
  @backstage/plugin-kubernetes                             0.4.17
  @backstage/plugin-newrelic                               0.3.8
  @backstage/plugin-org                                    0.3.27
  @backstage/plugin-proxy-backend                          0.2.13
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.2
  @backstage/plugin-scaffolder-backend                     0.15.10
  @backstage/plugin-scaffolder-common                      0.1.0
  @backstage/plugin-scaffolder                             0.11.8
  @backstage/plugin-search-backend-node                    0.4.2
  @backstage/plugin-search-backend                         0.2.6
  @backstage/plugin-search                                 0.4.15
  @backstage/plugin-tech-radar                             0.4.11
  @backstage/plugin-techdocs-backend                       0.10.5
  @backstage/plugin-techdocs                               0.12.3
  @backstage/plugin-user-settings                          0.3.10
  @backstage/search-common                                 0.2.0
  @backstage/techdocs-common                               0.10.4
  @backstage/test-utils-core                               0.1.3
  @backstage/test-utils                                    0.1.19
  @backstage/theme                                         0.2.12
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.0

**Comment by thiagoluiznunes** [comment]
I founded a solution after a massed searching about my problem and the problem were the new header CSP (content security policy) recently implemented by browsers. It were blocking the google analytics files request. So, I tried to add the header using meta tag without success.
`<meta
      http-equiv="Content-Security-Policy"
      content="script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com/analytics_debug.js;
      "
/>`
After hours of searching I founded a solution in the app.config.yaml file. There is an option in the backend section called "csp". So, I noticed that there could be the problem. It is necessary add the csp permission in the backend rather than frontend.

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    script-src: ["'self'", "'unsafe-inline'", "'unsafe-eval'", 'https://www.google-analytics.com/analytics_debug.js']
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: db
      port: 5432
      user: docker
      password: docker

  cache:
    store: memory

**Comment by hardboiled** [comment]
I had to whitelist the img-src as well
```yaml
    script-src: ["'self'", "'unsafe-eval'", "'unsafe-inline'", 'https://www.google-analytics.com/analytics.js']
    img-src: ["'self' *.google-analytics.com"]
```
This is what it looked like for me.
