### ISSUE TITLE
Not getting Logged in User details in scaffolder plugin

### ISSUE THREAD

**Issue by sjamidar** [backstage/backstage#7930]
Hi Team,

Not able to get logged in user details in Scaffolder-backend plugin, As i needed those to make call while creating template. Can someone help here.

**Comment by Rugvip** [comment]
You can achieve this through adding your own [custom field extensions](https://backstage.io/docs/features/software-templates/writing-custom-field-extensions). They have access to the react context and can for example use the Identity API to fetch user information. If you're looking to include credentials that's slightly different though, as you wouldn't want those to stick around in the task data. See #7684 for continued discussion there
