### ISSUE TITLE
catalog-backend LocationReaders MAX_DEPTH is not enough

### ISSUE THREAD

**Issue by erkanzileli** [backstage/backstage#7984]
## Feature Suggestion

We are using a structure something like the following. Each parent location targets its child.

![image](https://user-images.githubusercontent.com/26749979/141300900-77bd95cc-5fe0-4136-918c-e55062e6b557.png)

When we do this we see the following error maybe there is an issue on here because our total sequential child directory count is 5.

`Max recursion depth 10 reached for location bootstrap bootstrap`

## Possible Implementation

We know we can't want you to make the `MAX_DEPTH` value bigger. If this field can be configurable it makes more sense.

## Context

We are using `@backstage/plugin-catalog-backend` with static Location URLs.

cc: @yilmazo @previousdeveloper

**Comment by Rugvip** [comment]
I believe this was a limitation in older versions of the catalog, moving to a newer version should fix the issue. See the [changelog](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/CHANGELOG.md) for migration guides, along with some [general tips on staying up to date](https://backstage.io/docs/getting-started/keeping-backstage-updated)

**Comment by erkanzileli** [comment]
We used new codes but our objects are written to the `final_entities` table not to `entities` table. This means we can't see our Components or Resources on our UI.

Our plugins versions are the following

```
"@backstage/backend-common": "^0.9.9"
"@backstage/plugin-catalog-backend": "^0.17.3"
```

Here are our configs.

app-config.yaml
```yaml
catalog:
  rules:
    - allow: [Component, API, Group, User, Template, Location, System, Domain, Resource]
  locations:
    - type: url
      target: https://file-url-which-contains-component
```

catalog.js (which tries to run processors)
```ts
import {CatalogBuilder, UrlReaderProcessor,} from '@backstage/plugin-catalog-backend';
import {PluginEnvironment} from './types';

export async function createReader(
    env: PluginEnvironment,
): Promise<any> {
    const builder = await CatalogBuilder.create(env);

    const urlReader = new UrlReaderProcessor({reader: env.reader, logger: env.logger})
    builder.addProcessor(urlReader)

    const {processingEngine, router} = await builder.build();

    await processingEngine.start();

    return router
}
```

types.ts
```ts
import { Logger } from 'winston';
import { Config } from '@backstage/config';
import {
    PluginDatabaseManager,
    UrlReader,
} from '@backstage/backend-common';

export type PluginEnvironment = {
    logger: Logger;
    database: PluginDatabaseManager;
    config: Config;
    reader: UrlReader;
};
```

**Comment by Rugvip** [comment]
@erkanzileli sorry could you elaborate a bit more? Code looks good. Did you just bump the version and encounter a new issue? Or is it still the same issue

**Comment by erkanzileli** [comment]
OK than. The first problem is legacy limits(MAX_DEPTH) but when we use the new code it is not working at all. Opening new issue for the second one. Thanks a lot.
