### ISSUE TITLE
How to get rid of `You are running an example backend`

### ISSUE THREAD

**Issue by sunshine69** [backstage/backstage#8011]
Missing documentation about how to build deploy production system

## Expected Behavior

Document should be clear to show the boundary between developments and deployment.
Should support build in build script.

## Current Behavior

I follow the docker build doco, basically 

```
# at root
yarn install --frozen-lockfile
yarn tsc
yarn build
# create dockerfile using the doc copy and paste
# build 
docker image build -t backstage:stevek-test -f Dockerfile .
```

Run it - always have this message

```
2021-11-12T01:47:27.750Z backstage info You are running an example backend, which is supposed to be mainly used for contributing back to Backstage. Do NOT deploy this to production. Read more here https://backstage.io/docs/getting-started/ 
```
OK get back to the doco link above, read , read, read and did not find what to get it out.

The Site Tittle always has `Backstage Example App`

**Comment by freben** [comment]
It seems that you have cloned the main repo and are running that. The intended workflow for getting Backstage [is documented in the getting started section](https://backstage.io/docs/getting-started/create-an-app) of the docs. Essentially, you can clone/fork the main repo just to poke around, or to more easily make some forms of core contribution, but to get your own Backstage instance going, you should use the `npx @backstage/create-app` flow to get your own, personalized, private repo set up.

**Comment by sunshine69** [comment]
Hi,
What I did is to clone and run based on the doc.

The advise to use create app is no good, that is the bad things in terms of devops, How you automate the build by running npx @backstage/create-app ?

How to build the docker image after create the app? No doc clearly show

I would like to have a *release* process automated via CI/CD which build a production image of backstage and read a `app-config.yaml` passed in by docker config params.

I *don't* want to clone the repo, run  @backstage/create-app - config tinkering with config until it works and leave it as production if that is what you mean.

I may miss some doco part but if so, then the doc is so terse that I could not spot it out in the first instance.

If I miss the doc somewehre please point me the URL and the screenshot of the text containing the instruction rather than only URL, as I said, the doc is totally in a terse format ...

Thanks

**Comment by timbonicus** [comment]
> How you automate the build by running npx @backstage/create-app ?

The `npx @backstage/create-app` command is meant to be run once, then the resulting directory should be checked into source control and built from that repository using normal CI/CD workflows afterwards.

> How to build the docker image after create the app? No doc clearly show

See the [Docker documentation](https://backstage.io/docs/deployment/docker) for instructions, this is just a few commands.

> I don't want to clone the repo, run @backstage/create-app - config tinkering with config until it works and leave it as production if that is what you mean.

For configuration, commonly you will have an `app-config.local.yaml` for local development that differs from your production settings. Sensitive information such as tokens should be referenced as environment variables in the config (e.g. `${GITHUB_TOKEN}`) and included in the env, as you say (via Docker, Kubernetes secrets, etc).

**Comment by sunshine69** [comment]
Thanks it makes more sense now, however question still remains, how can I upgrade to new release tag of backstage?

**Comment by sunshine69** [comment]
Not sure you can see qhat I see. This is awkward. You can not just copy the package.json from the source repo to the app and run yarn update, they are different. The most obvious way is form the main source, run create-app again and check out into the deploy/build repo.

However the `npx @backstage/create-app` does not take arguments - it is interactive. :( .

What am I missing here?

**Comment by jhaals** [comment]
There is a `yarn backstage-cli versions:bump` command that you use for keeping things up to date.
It's definitely not intended to take the package.json from the root of the repo and put it in your app created from `npx @backstage/create-app`.
Backstage is similar to create-react-app in the sense that you scaffold a new application using a command. Forking or using the repository directly is only intended for development on backstage itself.
