### ISSUE TITLE
TechDocs: Button to copy code given in code blocks

### ISSUE THREAD

**Issue by koralcem** [backstage/backstage#8079]
## Feature Suggestion

Provide a button in code blocks which, when clicked, will put all code in the code block on the clipboard.

## Possible Implementation

Not sure. But [this comment](https://github.com/mkdocs/mkdocs/issues/2238#issuecomment-735470910) makes it sound like it's possible and maybe even already present in other projects.

## Context

In following technical documentation, there are often code blocks. And quite often, the code in those blocks needs to end up in my text editor or IDE. I currently have to select all the code with my mouse and copy it. This is fine if I'm dexterous, but I sometimes copy one extra line of the surrounding text, or miss the last line of the code block, which cause hiccups in productivity. If I know I need all of the code, a way to put it on my clipboard would be great.

**Comment by BenDu89** [comment]
Sounds like a good idea - looking forward to seeing this in one of the next updates :-)

**Comment by koralcem** [comment]
I'd still like to see this, so commenting in order to avoid closure due to staleness.

**Comment by iamEAP** [comment]
(Should be available in the next TechDocs release coming out next Friday!
