### ISSUE TITLE
[Plugin] Backstage Config Explorer

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#809]
## Summary

A plugin for exploring the configuration of a Backstage instance. Listing all installed plugins and their versions, and any other config that is available. For example URLs and registered entity types, etc. 

Could also be a place to show which plugins have new versions or recommended replacements.

## Context

Should be a useful tool for maintainers to get an overview of an installation, and help out with troubleshooting.

**Comment by stefanalund** [comment]
This open up a whole category of potential tools and dashboards under an `/admin` umbrella 😄

**Comment by dtuite** [comment]
Might want to move to a config based plugin install for this effort. Adding or removing plugins currently requires code changes in `plugins.ts` and potentially (?) `app/src/apis.ts` which I presume means a commit, build and redeployment.

**Comment by Rugvip** [comment]
@dtuite we'd have access to that at runtime though. But we do want to move things to static config for that any many other reasons :grin:

**Comment by stefanalund** [comment]
Related discussion https://github.com/spotify/backstage/issues/138.

**Comment by OrkoHunter** [comment]
Re-opening since plugin suggestion issues are now exempt from [stalebot](https://github.com/backstage/backstage/blob/18f7345a6c29dcfccef7df081b1708f2bf8f62ff/.github/stale.yml#L9).

**Comment by adamdmharvey** [comment]
This plugin as a sort of "overall management" tool would have good linkage to the new plugin here:
https://github.com/backstage/backstage/tree/master/plugins/config-schema

cc @Rugvip

**Comment by adamdmharvey** [comment]
I feel like @awanlin 's [DevTools plugin](https://github.com/backstage/backstage/tree/master/plugins/devtools) has completed the intent behind this.  I'd suggest this could likely be closed.  Any one else second that? :)

<img width="1152" alt="image" src="https://github.com/backstage/backstage/assets/33203301/88981036-7e56-4065-83d3-738c910047e9">

**Comment by benjdlambert** [comment]
@adamdmharvey agreed - closing! :tada:
