### ISSUE TITLE
[TechDocs CLI] awsS3 publisher does not support AWS_CONFIG role_arn, preventing sts:AssumeRole and publishing to bucket

### ISSUE THREAD

**Issue by matchaxnb** [backstage/backstage#8102]
Hey there,

The awsS3 publisher does not support loading a profile from the AWS config.

Our setup uses gitlab-ci runner pods in an EKS cluster. Each k8s pod is assigned an IAM role through kube2iam. That role can then use AWS STS to assume another role in workload accounts.

I want to push docs for ongoing development projects to a s3 bucket that resides in the dev workload AWS account, and docs for the main branches (deployed to production) in the prod workload account.

For historical reasons the runners run in a dedicated CI AWS account and not in the workload accounts. So in order to map profile names to the ARNs to impersonate, I add a `.aws/config` file in my running images that contains a map of profile names and ARNs like this:

```
[profile dev]
role_arn = arn:aws:iam::<dev_account_id>:role/cicd/delegated-cicd-role
credential_source = Ec2InstanceMetadata
[profile prod]
role_arn = arn:aws:iam::<prod_account_id>:role/cicd/delegated-cicd-role
credential_source = Ec2InstanceMetadata
```

And when I set the `AWS_PROFILE` env variable to `dev` or `prod`, the AWS SDK usually loads the adequate role_arn and does the impersonation for its authentication.

Except it seems, after investigating, that the AWS SDK for JavaScript that techdocs uses does not support that.

I had to resort to a quite dirty hack to get it running. Sharing so other people don't spend 1 day figuring it.

```bash
export AWS_PROFILE=$CI_ENVIRONMENT_NAME # will be dev or prod
export AWS_SDK_LOAD_CONFIG=1
export ARN_TO_IMPERSONATE=$(fgrep -A100 '[profile '${AWS_PROFILE}']' /root/.aws/config | grep role_arn | head -n 1 | awk '{print $NF}') # this is causing bleeding in my eyes
touch /root/.aws/credentials
techdocs-cli generate --no-docker
techdocs-cli publish --publisher-type awsS3 --awsRoleArn $ARN_TO_IMPERSONATE --storage-name $TECHDOCS_BUCKET_NAME --entity ${ENTITY_NAMESPACE}/${ENTITY_KIND}/${ENTITY_NAME}
```
Suggested fix would be to add support for a `--awsS3.profile` parameter to techdocs-cli that would make use of [AWS.SharedIniFileCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html#constructor-property). I lack skill in JS to hack this properly but I'd be glad to contribute later if no one addresses it.

Thanks :)
Matcha

**Comment by garyniemen** [comment]
We in [@backstage/techdocs-core](https://github.com/orgs/backstage/teams/techdocs-core) do not use AWS internally so we are not in the best position to investigate this issue further.

It would be great if anyone from the community who uses Backstage within AWS is able to investigate this and contribute a fix if possible. We can support with PR reviews and getting the fix in.
