### ISSUE TITLE
[TechDocs CLI] Publishing to AES256 encrypted S3 bucket

### ISSUE THREAD

**Issue by nomeelnoj** [backstage/backstage#8104]
In our org, we have a default policy that denies unencrypted uploads to buckets via headers.  This prevents uploading objects to the bucket without encryption.

Normally, when using the AWS CLI, this is resolved by passing `--sse AES256` as a command line arg.  It does not seem that this is possible with the techdocs-cli `publish` command.

Can it be added?

For reference, here is the bucket policy in question causing the issue.  As soon as we remove this section of the policy, the command functions as expected:

```
{
    "Version": "2012-10-17",
    "Statement":
    [
        {
            "Sid": "DenyIncorrectEncryptionHeader",
            "Effect": "Deny",
            "Principal":
            {
                "AWS": "*"
            },
            "Action": "s3:PutObject",
            "Resource":
            [
                "arn:aws:s3:::testbucket/*",
                "arn:aws:s3:::testbucket"
            ],
            "Condition":
            {
                "StringNotEquals":
                {
                    "s3:x-amz-server-side-encryption": "AES256"
                }
            }
        },
        {
            "Sid": "DenyUnencryptedUploads",
            "Effect": "Deny",
            "Principal":
            {
                "AWS": "*"
            },
            "Action": "s3:PutObject",
            "Resource":
            [
                "arn:aws:s3:::testbucket/*",
                "arn:aws:s3:::testbucket"
            ],
            "Condition":
            {
                "Null":
                {
                    "s3:x-amz-server-side-encryption": "true"
                }
            }
        }
    ]
}
```

**Comment by garyniemen** [comment]
@camilaibs just wondering about these PRs to close this issue.

**Comment by therynamo** [comment]
@garyniemen - both PRs have been merged and released https://github.com/backstage/backstage/pulls?q=is%3Apr+is%3Aclosed+author%3Atherynamo. 

I've tested this with `sse` and everything works as expected. I'd also expect `AES256` to work accordingly - but I have no buckets to test that with at the moment.

**Comment by soapraj** [comment]
@nomeelnoj - seems like the support has been added. would you be able to test this at your end?

**Comment by camilaibs** [comment]
> @nomeelnoj - seems like the support has been added. would you be able to test this at your end?

Hi @nomeelnoj, just pinging you, looking forward to hearing good news 🙂

**Comment by soapraj** [comment]
Hi! @nomeelnoj - Closing this issue for now. Please re-open if needed.
