### ISSUE TITLE
[TechDocs CLI] More peace-of-mind E2E and Unit Tests

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#8105]
#### Browser-based E2E Test for techdocs-cli serve
We've run into several issues recently where bumps to Backstage packages and plugins have resulted in a non-functional preview environment when running `techdocs-cli serve`.

We added basic end-to-end tests for the CLI itself in backstage/techdocs-cli#55.  We should add one more case that actually loads up a headless browser and asserts that the Backstage app loads and renders as expected.

#### Unit tests for techdocs-cli publish
Although most publishers are quite well-covered in `@backstage/techdocs-common`, we don't have any validation in this repo for the `publish` command.  It might be sufficient to just ensure that we call `publisher.publish` with the expected args.

**Comment by soapraj** [comment]
not stale
