### ISSUE TITLE
[TechDocs CLI] ACL (bucket-owner-full-control) config for AWS publisher

### ISSUE THREAD

**Issue by JonasAmrich** [backstage/backstage#8106]
Hey all, I'm trying to solve a peculiar issue. Our CI runs in a separate AWS account and we have our Backstage instance together with its techdocs s3 bucket in another AWS account. 

This means that objects uploaded to the techdocs bucket are owned by CI AWS account and Backstage doesn't have access rights to display them. Common solution is to set `bucket-owner-full-control` ACL when uploading objects to S3. How would you recommend to address this situation? Would it make sense to make ACL configurable, or can you see a different solution?

Thanks

**Comment by garyniemen** [comment]
We in [@backstage/techdocs-core](https://github.com/orgs/backstage/teams/techdocs-core) do not use AWS internally so we are not in the best position to investigate this issue further.

It would be great if anyone from the community who uses Backstage within AWS is able to investigate this and contribute a fix if possible. We can support with PR reviews and getting the fix in.

**Comment by edbighead** [comment]
for anyone stumbling upon this closed issue, as of November 2021, it is possible to enforce a proper bucket and skip setting the ACLs

https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-object-ownership-simplify-access-management-data-s3/
