### ISSUE TITLE
[TechDocs CLI] Automatically publish a Docker image for every CLI release

### ISSUE THREAD

**Issue by taras** [backstage/backstage#8108]
## Motivation

I'm going to be building techdocs on Jenkins CI. It would be helpful for me to have a Docker image that I could use to execute `techdocs-cli` in CI. This same image could be used for GitHub Actions. Having such an image would eliminate the need for me to build this image locally.

## Approach

One way to do it would be automatically publish a Docker image when a new version of techdocs-cli is released. I can create a PR for this.

**Comment by garyniemen** [comment]
This is from quite a while ago now @taras - any further thoughts?

**Comment by taras** [comment]
I think we can probably close this. I don't really need it and if no one else does then we're good.
