### ISSUE TITLE
[TechDocs CLI] Known limitation: No mkdocs.yml or missing nav will fail the serve command

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#8110]
`mkdocs serve` command's live reload does not work if `mkdocs.yml` does not have a [`Nav`](https://www.mkdocs.org/user-guide/configuration/#nav). Hence, techdocs-cli will also fail.

Document this somewhere here and maybe even lint `mkdocs.yml` as part of the serve command in the CLI and throw warning/error if `Nav` is missing.

**Comment by iamEAP** [comment]
Re-associating with the up-to-date PR: https://github.com/backstage/mkdocs-monorepo-plugin/pull/69
