### ISSUE TITLE
Catalog import plugin should default spec.type to "service"

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#8113]
## Feature Suggestion

The [Backstage docs say that](https://backstage.io/docs/features/software-catalog/descriptor-format#spectype-required) "the current set of well-known and common values for this field [spec.type] is service, website and library".

When opening a pull request, the catalog-import plugin sets the `spec.type` value to `"other"`. This cannot be changed when opening the pull request.

## Possible Implementation

Default `spec.type` to `"service"` instead.

## Context

Defaulting to service is beneficial for a number of reasons:

1. It is more likely to be correct. In reality, my Component may or may not be a service. But it's definitely not an "other". The difference is potentially correct vs. always wrong.
2. It helps discoverability. Defaulting to "service" teaches me what the spec.type field means, without me having to read the docs. "other" doesn't tell me anything.

**Comment by freben** [comment]
Hm. I'm not sure what's the right stance to take on "potentially correct vs. always wrong" :) Could be a case of "obviously a placeholder that needs updating vs. why is this software guessing so poorly" :D Both sides could be argued for sure, so not trying to shoot it down really. Also the docs might warrant some updating - I wonder if it would be worthwhile to actually put in print some kind of "unknown" or "other" or similar value that can be used where absolutely necessary.

We could make it a mandatory parameter of course, and at the same time try to make the guessing better.

**Comment by andrewthauer** [comment]
I think `unknown` would be more appropriate unless you can be sure  what the type should be. It's likely easier to find and reclassify, then say a library that was classified as a service incorrectly.

We actually built a custom `RepoLocationAnalyzer` that tries to guess the `spec.type` based on some internal conventions that are used for repo names. This approach can also be used to override or add additional field as well.

**Comment by freben** [comment]
Agreed. I think a tech insights-like solution would also appreciate being able to look for this `unknown` and apply a lower score accordingly, or in other ways notify engineers that they should take action to improve their metadata, than to put a valid-but-wrong value in there.

**Comment by dtuite** [comment]
Great points above! It sounds like there is no appetite for this so I will close it. Thank you!

**Comment by freben** [comment]
Thanks for the suggestion though! And I think we have a nice way forward in the other issue you made, so all good on our part.

**Comment by dtuite** [comment]
@freben Totally. My idea was just to suggest a few different solutions to generate discussion.
