### ISSUE TITLE
Catalog import plugin should support setting type

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#8114]
## Feature Suggestion

When opening a pull request with the catalog import plugin, I should be offered a set of options based on well-known types.

## Possible Implementation

If the catalog is empty, show a `<select />` populated with the [well-known types](https://backstage.io/docs/features/software-catalog/descriptor-format#spectype-required).
If the catalog is not empty, show a `<select />` populated with the set of existing types, plus the well-known types.

A pattern like this is already in place for Entity Owner.

![Screenshot 2021-11-17 at 16 26 43](https://user-images.githubusercontent.com/562403/142240616-87a386fc-34ac-4d83-8fe1-56003f843de2.png)

## Context

I am trying to create a PR with some sensible settings in order to get my component into Backstage. Without this, I have to create the PR, then pull the new code, then edit the `spec.type` to something sensible and commit.

**Comment by dtuite** [comment]
Related to #8113.

**Comment by freben** [comment]
Makes sense! All required parameters should probably be represented one way or another through this flow.
