### ISSUE TITLE
Get open scaffolder tasks

### ISSUE THREAD

**Issue by nhomble** [backstage/backstage#8124]
## Feature Suggestion

We would like to let developers see pending templates so that they aren't left wondering if their template has finished yet.

## Possible Implementation
Maybe we could add some metadata to the task spec for better querying (maybe we need an owner for a task spec?) and then expose a new route to find tasks.

## Context

We have use cases for certain templates to take some time. We appreciate the fact that the task broker stores these tasks in a database owned by the scaffolder plugin.

We think our developers would like the visibility.

**Comment by nhomble** [comment]
Looking at previous RFCs, my use case is similar to what is described here: https://github.com/backstage/backstage/issues/4319

and in the case of ansible step at the end of the golden path, there might be other workflow activities that take slightly longer than a user may want to wait in the UI for.

**Comment by freben** [comment]
Yep! This is something we've wanted for some time. At the very least, the Backstage token from the identity API on the frontend should be passed along with the request to the scaffolder, and the scaffolder should take the user ID from it and associate that with each created task. Then there would be a REST API extension to let you query for tasks that belong to a certain user.

Is this something that you might be interested in working on?

**Comment by nhomble** [comment]
I would be interested in helping but I need to sort out my employers policies first :/

I'll comment back here if I'm able to pick this up but I don't think it'll be in the next couple weeks.

**Comment by benjdlambert** [comment]
@nhomble no probs at all!

Just to throw some more thoughts down here, as we've been thinking about this on discord in Voice chat, and I don't think anything has been written down for the world to see or documented in tickets or whatnot.

So I think there's actually two parts of this view or Feature that we'd really like to get in for the Scaffolder. 

There's one part which is definitely the see all jobs that's active right now, so if you lose the tab you can still see things that are running, or as an admin of a system see things which have been running for too long or whatever. And then there's also the side that as a normal user of a system I want to be able to see just `My Jobs` that i've created. 

And that might not only be jobs that are currently running either, that might have the ability to show jobs that you ran before, and that failed so you can get some logs or whatever for debugging or passing along to someone else.

The `My Jobs` feature, is something that relates a lot to the Identity part which is currently undergoing some heavy refactoring and deprecations, but I think we should be storing some form of `createdBy` field in the database too so we can use the field for grabbing all jobs by a user for displaying in the frontend.

**Comment by benjdlambert** [comment]
Related to this work too https://github.com/backstage/backstage/issues/5441

**Comment by benjdlambert** [comment]
So this ticket came up again pretty recently, if anyone would like to take this on and make it production worthy i've got a branch with pretty much the implementation it just needs rewriting with tests and cleaning up a little bit. You can find the branch here: https://github.com/backstage/backstage/compare/blam/store-created-by, and it looks a little bit like below:

https://user-images.githubusercontent.com/3645856/153530487-55ed7464-3b5f-45c2-8647-f3f145a0caa8.mov


Please.. feel free to change anything and everything in that branch, it's mainly there for just a starter, and I promise you a donkey could make a better UI than I can, so please go ahead and help us out!

Also please if you can fix the sidebar ahaha, I just tried to throw something together as a seperate link, but it should probably be a `subRouteRef` of the `/create` `route` :)

**Comment by benjdlambert** [comment]
Of course happy to help anyone that wants to pick this up before we get to it too!
