### ISSUE TITLE
[RFC] TypeError: Network request failed

### ISSUE THREAD

**Issue by parulagg-1199** [backstage/backstage#8140]
Tried to deploy backstage through docker.
The build was successful, image creation done.
While doing port mapping for seeing the UI through browser the catlog entities failed to load.

![backstage_issue](https://user-images.githubusercontent.com/68728482/142404488-7176dd5d-49a8-407e-a30e-f75c37f0c4f5.png)

**Comment by goenning** [comment]
The default app-config is setup to run front end on one address and backend on another.

When using docker, if you're bundling all together, you will need to change the app-config accordingly.

1. What's the URL you're using on the frontend?
2. Can you look at the network and see if that gives you any extra insights? It might be trying to connect to the wrong address
