### ISSUE TITLE
Align import references of Link component to use @backstage/core-components

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#8146]
This issue is to collect a list of outstanding places where the `Link` component is imported not from `@backstage/core-components` but instead from other, generally 3rd party packages (e.g., MUI). The intent is to properly align the functionality of links across the system as a whole.

Links in the Backstage UI should be generated out of this component: https://backstage.io/storybook/?path=/story/navigation-link--default

### Backstage Core

* [ ] `packages/app` https://github.com/backstage/backstage/blob/153eac4252f2b47d246cdfff3f567644761af201/packages/app/src/components/Root/Root.tsx#L18
    * Not fixed as of 2022-07-14
* [ ] `create-app` `template` https://github.com/backstage/backstage/blob/153eac4252f2b47d246cdfff3f567644761af201/packages/create-app/templates/default-app/packages/app/src/components/Root/Root.tsx#L18
    * Not fixed as of 2022-07-14
*  [ ] `techdocs-cli-embedded-app` https://github.com/backstage/backstage/blob/ff7fdcb1b1241a570c8fcf4565a2177464987ea0/packages/techdocs-cli-embedded-app/src/components/Root/Root.tsx#L19
    * Package was refactored from `embedded-techdocs-app` to `techdocs-cli-embedded-app` but still is old link
    * Not fixed as of 2022-07-14
* [x] `@backstage/core-components` `layout/ErrorPage` https://github.com/backstage/backstage/blob/153eac4252f2b47d246cdfff3f567644761af201/packages/core-components/src/layout/ErrorPage/ErrorPage.tsx#L19
* [x] `@backstage/core-components` `HeaderLabel` https://github.com/backstage/backstage/blob/153eac4252f2b47d246cdfff3f567644761af201/packages/core-components/src/layout/HeaderLabel/HeaderLabel.tsx#L18
* [ ] `@backstage/core-components` `Sidebar` https://github.com/backstage/backstage/blob/153eac4252f2b47d246cdfff3f567644761af201/packages/core-components/src/layout/Sidebar/Intro.tsx#L20
    * Not fixed as of 2022-07-14

### Plugins

* [ ] `@backstage/plugin-bazaar`  (multiple references)
* [ ] `@backstage/plugin-catalog` https://github.com/backstage/backstage/blob/fb03c47c8b1e6d37bfe182e88d675e7b330615d9/plugins/catalog/src/components/Router.tsx#L22
* [ ] `@backstage/plugin-circleci`  (multiple references)

### Context

Specifically, @freben noted in a PR review,

> Could you try to change the import of `Link` in this file to instead use the one from `@backstage/core-components`? That one is _supposed_ to be used everywhere (but apparently wasn't in this file), and it is meant to set `target` and `rel` automatically and correctly so you could remove these here hopefully. The other benefit is that it'll be connected to analytics, styling etc etc in a cross-app way.

_Originally posted by @freben in https://github.com/backstage/backstage/pull/8115#discussion_r752158316_

**Comment by adamdmharvey** [comment]
Note there are multiple MUI Link references in Storybook stories for components, and I figure those are correct since they're using a raw link as opposed to driving functionality in Backstage? if not, they could be added also. Welcome contribs/suggestions to this list!!

**Comment by freben** [comment]
Thanks for making this!

**Comment by WarlenRodrigues** [comment]
Working on this!

**Comment by benjdlambert** [comment]
Think that a lint rule here makes a lot of sense too 👍

**Comment by dmitry-lobanov** [comment]
Hi everyone,
I had some time to work on this issue, created a PR #14050
- aligned import references of Link component
- [added a lint rule](https://github.com/backstage/backstage/pull/14050/commits/5b38b1bae7197542fff9a12e237c187b81ef6f4a) (please let me know if there's a better place for it)
