### ISSUE TITLE
Catalog events

### ISSUE THREAD

**Issue by vincentbriglia** [backstage/backstage#8162]
## Feature Suggestion

Backstage is a centralized software catalog, with very nice features around collecting, ingesting and sharing information in that context. One of the things that would make it more powerful is that it can send out catalog events whenever the software catalog discovers a change. We have `postProcessEntity` events but it would be nice if we had events / webhooks that we could hook into to listen to when an entity was deleted, updated, added, stitched, etc ... 

I can see this has been mentioned in past issues like https://github.com/backstage/backstage/issues/3221 and a few more; I can really see the benefit for this. 

## Possible Implementation

we have an engineering team that can jump on this, but would like guidance if there were already some thoughts on this

## Context

While Backstage aims to be a place of ingestion of information, since a lot of these entities often collate data from different data sources and enhances some metadata, the shift-left approach in Backstage where the `catalog-info.yaml` files are the primary entry point into ingesting information, there are systems that could benefit from receiving events. 

### aggregation of updated information and sending of emails

We would like to send an email to owners, once a week about their Entities, or entities they have favorited, are listed. This would mean we could say "Entity X has a new annotation: you can now view its Sentry metrics"

### updating an external service catalog

We also have a tool like LeanIX. While backstage is great, and deals with exposing a good entry point for all sorts of information, there are some pieces of information we would like to only have to update once (through `catalog-info.yaml`) and propagate to the other system.

**Comment by freben** [comment]
Hi! Glad to see that this caught your interest. We'd absolutely love this as well, as you saw in the other ticket.

I'll do some _very_ back-of-the-napkin level design suggestions just to think out loud. Don't take it as gospel, just getting some thoughts started:

This will probably need some low level hooks to be added first. Then, some levels higher up the stack, we should offer integrators to subscribe to the hooks and do what they want to do with them (emit metrics, perform logging, emit pubsub messages, or whatnot).

[Here is an old branch](https://github.com/backstage/backstage/compare/freben/events-experiment) where I experimented with using [emittery](https://github.com/sindresorhus/emittery) to expose the ongoings in the stitcher. That's the component that is responsible for ultimately introducing or updating the final public form of an entity. I still feel that this was a pretty decent start to things.

Then, at the very upper level of things, the `CatalogBuilder` could one way or the other expose all of the various hooks from various subsystems. Perhaps something like

```ts
const { events } = catalog.build();
events.stitcher.stitchCompleted.subscribe(({ entityRef }) => {
  eventChangeTopic.publish({ type: 'catalog-entity-changed', ref: entityRef });  
});
```

in pseudocode :)
