### ISSUE TITLE
Analyse import on catalog import page to return an async response

### ISSUE THREAD

**Issue by nicolasarnold12321** [backstage/backstage#8165]
## Feature Suggestion

`dryrun` request returns an async response immediately, accepting the request with an id that then can be referenced at a later time.

## Possible Implementation

Create a new api endpoint in the catalog that allows the user to send an `ID` of a location addition.
The `POST` locations has an option to be sync or async `&async=true`.

Frontend makes a request to the backend and stores the ID of the location addition. It then polls against the new backend api (eg. every 1 second) until it is completed.
Displays the information as it was before

## Context

When analysing catalog-info.yaml files, requests are sent to the backend to run a dry-run to add locations. This request is not resolved until the component tree is completed. This may cause issues if you have a proxy in front of backstage as these proxies may or may not have timeouts associated with them.

For example, we have created a monorepo [here](https://github.com/RoadieHQ/monorepo-sample-service/blob/main/catalog-info.yaml) with 200 components. The analysis took just over one minute to resolve. This is not ideal.

<img width="1708" alt="Screenshot 2021-11-19 at 11 15 48" src="https://user-images.githubusercontent.com/24317810/142614607-21e0f13e-6b9d-4468-9822-98ae69caa0bb.png">

**Comment by dtuite** [comment]
Here's a test case with 200 Backstage YAML files which can be used to demonstrate the need for this: https://github.com/RoadieHQ/big-monorepo-fixture

**Comment by freben** [comment]
Unfortunately the underlying engine of the catalog is not yet well prepared for something like this. Each location (and things emitted from that location, recursively) is a standalone atom being processed in isolation without any overarching task ID or similar; furthermore, we do not know upfront the amount of work to be done so it's hard to derive after the fact as well.

We're of course open to discussing ways of making this work within the engine! It seems upfront like it might take some arch/design work to get there.
