### ISSUE TITLE
Enhancement to Software templates to fetch values from a file  and populate them automatically in the template when User inputs values.  **HELP WANTED**

### ISSUE THREAD

**Issue by aswathysen** [backstage/backstage#8166]
## Feature Suggestion

Enabling Software template to fetch values from files that contains list of values and populate them as user inputs in the required area.

Enable support to dependencies while providing inputs through the software template

## Context

`When a user enters a value example in this case Azure subscription name and gives a azure region it **should auto-populate or at least list out** the Vnets etc. available in that subscription and region, **if not found the user should be able to provide value** to the new vnet name etc. in the UI itself. And the user should be able to see the populated values in the UI before going to next step (next step: other values that is required for deployment of the azure resource) `

 ```
Requirement in real world: 
1. we can create an integration with azure (using an API call)
2. we can have a file (can be csv, json,yaml format etc) that contains the list of values and the software template will go and compare with the subscription and produce the required results in the UI at the same time before going to the next step
```

**Comment by benjdlambert** [comment]
Hey! Sorry this has taken a while to get back to you on here. I thought i'd replied already but apparently I closed the tab without hitting comment!

So I think that this is possible using your own [`CustomFieldExtensions`](https://backstage.io/docs/features/software-templates/writing-custom-field-extensions), you can read more on them here: 

You'd ideally have one `FieldExtension` that could render two inputs in the form, and keep all the state in that React component that renders these two fields. If you take a look at the [`RepoUrlPicker`](https://github.com/backstage/backstage/blob/0e9fef8e3fc2f60d95075ad52441273f98e974a2/plugins/scaffolder/src/components/fields/RepoUrlPicker/RepoUrlPicker.tsx) you will see that that is a `CustomFieldExtension` which renders multiple Fields in the form and there's state stored in the React Component.

You probably want to render one field, and `onBlur` of that field, go and make an async request to populate the fields in the second input.
