### ISSUE TITLE
[RFC] Provide standalone, packaged versions of @techdocs/cli

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#8168]
**Status:** Open for comments

## Need

The TechDocs CLI serves two distinct purposes for two distinct audiences:

1. **For machines**: as a mechanism for generating and publishing documentation in a CI/CD pipeline for those who've adopted TechDocs in the [recommended TechDocs deployment](https://backstage.io/docs/features/techdocs/architecture#recommended-deployment).
2. **For humans**: as a mechanism to _preview_ changes to documentation before committing and merging them (applicable to any TechDocs deployment strategy).

Of note for us here, we can't really assume much about _who_ those humans are in number two.  They are likely technical in some way (they are, after all, working on technical documentation), but we shouldn't assume they have any familiarity with the node.js ecosystem (e.g. `npm`, or `npx`), or the Backstage developer process (e.g. `backstage-cli`), or any desire to have to install/learn those things just to preview their documentation.

For these folks, installing or keeping-up-to-date with changes to the TechDocs CLI can be a hassle:
- `npx @techdocs/cli serve` is nice for always running the latest version of the CLI, but it is not a great experience if you frequently preview docs (as it will re-install all of the CLI's dependencies with each invocation)
- `npm install -g @techdocs/cli && techdocs-cli serve` is a better ongoing experience, but updating requires some node-specific knowledge. 

^ Each of the above will also spew out quite a bit of log output, possibly with errors or warnings related to compilation / `node-gyp` (as [seen recently](https://discord.com/channels/687207715902193673/714754240933003266/893373793278525460) due to shifting underlying dependencies) which may or may not affect the way the CLI works.

## Proposal

To better support humans who use the TechDocs CLI, we should offer the CLI as a standalone package, bundled with the relevant node.js runtime.  This package should be as easily installed as any other command line tool (e.g. via a shell one-liner, or perhaps brew).

To improve the update experience, we should offer a `techdocs-cli update` command which handles this on behalf of users, similar to other CLIs from cloud providers.

The intention is not to implement these things ourselves (which could be kind of tedious and error prone, especially across platforms and CPU architectures), but instead to adopt a CLI framework built to enable this kind of stuff, such as `oclif`, which supports [exactly these kinds of release features](https://oclif.io/docs/releasing#standalone-tarballs). 

## Alternatives

Would love to hear what others with experience in this area have done to make the CLI experience for devs nice and smooth.

**Comment by OrkoHunter** [comment]
I agree - techdocs cli is to be installed on the computers of Backstage users, unlike backstage cli. So, assumptions on node, npm etc. are not great.

> we should offer the CLI as a standalone package, bundled with the relevant node.js runtime.

Is the idea here to ship a binary? And/or to provide brew/apt formulae for techdocs cli? Just thinking about some concrete steps needed to implement the proposal.

**Comment by iamEAP** [comment]
> Is the idea here to ship a binary? And/or to provide brew/apt formulae for techdocs cli? Just thinking about some concrete steps needed to implement the proposal.

Yep! Could be something like...

```
curl https://techdocs.backstage.io/install.sh | bash
```

As a starting point. And/or then on the other end of the spectrum, the `oclif` tools mentioned above could even generate signed pkgs for MacOS as well as Windows installers if we wanted.

Package manager formulae are also a possibility! And would be somewhere in the middle in terms of audience/ease-of-use.

Would love to hear thoughts on how others would want to provide their TechDocs users with this kind of tooling.
