### ISSUE TITLE
Theme Property is Deprecated and yet Mandatory on AppTheme type

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#8194]
According to the migration guide from here: https://backstage.io/docs/api/deprecations#app-theme we should migrate and use `Provider` property instead of `theme`. But, when doing so, typescript complaints that the `theme` is a mandatory property, and it is, as seen here: https://github.com/backstage/backstage/blob/01a0a39521ab1c2132e972b8263d519e1a553a77/packages/core-plugin-api/src/apis/definitions/AppThemeApi.ts#L47

## Expected Behavior

The `theme` property should be optional considering that it is deprecated

## Current Behavior

Theme property is a required property on `AppTheme` type

## Possible Solution

Make the property optional

## Steps to Reproduce

Follow the migration guide from here https://backstage.io/docs/api/deprecations#app-theme

**Comment by freben** [comment]
@Rugvip

**Comment by Rugvip** [comment]
The migration was a bit tricky because we needed the `theme` to be present in the consuming end, but optional in the providing end.

It should be possible to do something like this:

```ts
createApp({
  themes: [{
    // ...,
    Provider: // ...
  }]
})
```

Are you assigning the custom theme to an intermediate variable or something like that? Perhaps we can update the migration guide to be a bit clearer there

**Comment by ProticM** [comment]
Yes, I have a separate function exported from my theme plugin that is creating a theme. That function returns the `AppTheme` type. So, the returning object is the intermediate variable :)

What I did here to overcome the issue is casting the returned object to any

**Comment by Rugvip** [comment]
Alright, makes sense 👍 

Adding a note in #8206, and can say that this will also be a quite short lived deprecation as the current state is less than ideal.
