### ISSUE TITLE
Scaffolder : specify allowed owner from applications templates 

### ISSUE THREAD

**Issue by LucileDesfour** [backstage/backstage#8205]
## Scaffolder : Specify allowed owners from RepoUrlPicker

It could be interesting to me to force the organization of the repository for a template. In my case I need all the future applications to be stored inside a specific organization on Github.

## Possible Implementation

On the scaffolder plugin we could add the allowed owners like the allowed host in the RepoUrlPicker.tsx  

## Context

In this way I could parse all the repository inside this specific organization to build CI / CD pipeline

**Comment by timja** [comment]
Could be good to hide the field too if there's only 1 allowed owner?

**Comment by LucileDesfour** [comment]
> Could be good to hide the field too if there's only 1 allowed owner?

I think its interesting for the user to see on which organization the repo will be created ?

**Comment by timja** [comment]
> > Could be good to hide the field too if there's only 1 allowed owner?
> 
> I think its interesting for the user to see on which organization the repo will be created ?

Well, coming from an organisation with 1 github org, not very interesting. 😄 
configurable would be nice
