### ISSUE TITLE
Badges broken EntityBadgeSpecsUrl

### ISSUE THREAD

**Issue by johanhammar** [backstage/backstage#8210]
Badges broken due to invalid entityBadgeSpecsUrl

## Expected Behavior

Badges should be rendered correctly

## Current Behavior

Badges not rendered

![image](https://user-images.githubusercontent.com/69011/143022252-08707415-1532-406e-993e-d93b5d6b4313.png)

## Possible Solution

I believe this commit https://github.com/backstage/backstage/commit/c67e023eae1dc6e37c9a551c1fd040258f81a2e6 broke the EntityBadgeSpecsUrl

![image](https://user-images.githubusercontent.com/69011/143022389-29cfc20f-ae8f-41bf-af55-bac587a3efec.png)

I'd be happy to fix it but am not sure which solution is prefered:

1) `const path = generatePath(`:kind/:namespace/:name`, routeParams);` -> `const path = generatePath(`:namespace/:kind/:namespace/:name`, routeParams);`
2) `const path = generatePath(`:kind/:namespace/:name`, routeParams);` -> `const path = generatePath(`entityRoute.path`, routeParams);`
3) something else

## Steps to Reproduce

1. Run Backstage from master
2. Go to any component
3. Click on Badges

![image](https://user-images.githubusercontent.com/69011/143022252-08707415-1532-406e-993e-d93b5d6b4313.png)

## Your Environment

- NodeJS Version (v14): Node v14.18.1
- Operating System and Version (e.g. Ubuntu 14.04): Windows using WSL1 / Ubuntu 20.04
- Browser Information: n/a

**Comment by feedmypixel** [comment]
Also seeing this Badges functionality broken over here FYI @benjdlambert

**Comment by benjdlambert** [comment]
Hmm - yep, I guess that commit did break it. Sorry this is my bad. It should be `:namespace/:kind/:name` instead.
