### ISSUE TITLE
[Jenkins-Plugin] Backend - Compiler error for the DefaultJenkinsInfoProvider

### ISSUE THREAD

**Issue by kudos-dude** [backstage/backstage#8214]
## Expected Behavior

It should compile using the instructions from the README

## Current Behavior

There seems to be 2 definitions of CatalogClient. One within the library itself, the other within Backstage. Their definitions conflict and it won't allow the Typescript compiler to work, which breaks the plugin (ts(2322)) :

```
Type 'import("backstage-deployment/node_modules/@backstage/catalog-client/dist/index").CatalogClient' is not assignable to type 'import("backstage-deployment/node_modules/@backstage/plugin-jenkins-backend/node_modules/@backstage/catalog-client/dist/index").CatalogClient'.
  
Types have separate declarations of a private property 'discoveryApi'.ts(2322)

index.d.ts(63, 9): The expected type comes from property 'catalog' which is declared here on type '{ config: Config; catalog: CatalogClient; }'
```

## Possible Solution

Ensure that the declaration of the class is not done twice.

## Steps to Reproduce

Follow the instructions on the Backstage Jenkins Plugin (backend) README.
Attempt a build or view in the IDE

## Your Environment

- NodeJS Version: v14
- Operating System and Version: Ubuntu/Docker (node14 RHEL container)

**Comment by Rugvip** [comment]
Thank you for reporting!

I'm not able to reproduce this. Tried in a new `npx @backstage/create-app` and installed just the jenkins backend plugins, but I'm not seeing any issues when running `yarn tsc:full`. Using Node.js 14 btw

Is there anything particular in your environment that could be causing this or that I'm missing when trying to reproduce?

**Comment by kudos-dude** [comment]
Thanks for the quick response @Rugvip 

Closing this issue. Bumping the versions of the core libraries + the plugin  ended up resolving it.

Wish I could say I took note of the version numbers, but I don't have access to that code base anymore, so can't recall it.
