### ISSUE TITLE
Speed up npx @backstage/create-app

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#8225]
## Expected Behavior

I should be able to run `npx @backstage/create-app` in a reasonable amount of time on a modest network connection.

## Current Behavior

When I run `npx @backstage/create-app`, `npx` first installs `@backstage/create-app` in a temporary location, which currently downloads ~844MB worth of packages.  On a mobile broadband connection, this can take 5-10 minutes.  This can sometimes result in `ERR_SOCKET_TIMEOUT` errors in the middle of the process, which then must be restarted.

...Only then does it begin the process of actually scaffolding out the app and running (another) `yarn install`, which itself takes quite a bit of time (but this is outside the scope of this issue, in my opinion).

## Possible Solution

It appears `npx` installs all peer dependencies.  Do all of the included `@backstage/*` packages really need to be included as peer dependencies?  Can we express that some other way?

![Screenshot 2021-11-24 at 13 43 32](https://user-images.githubusercontent.com/3496491/143241095-07cd77e4-874a-4cdb-acca-0bd6df340c33.png)

The biggest offenders:
- `@material-ui/*`: ~85MB
- `aws-sdk`: ~70.5MB
- `TypeScript:` ~60MB
- `typescript-json-schema`: ~59MB
- `@azure/*`: ~16MB
- `@testing-library/*`: ~14MB

## Your Environment

- NodeJS Version: v16
- Operating System and Version: MacOS Catalina 10.15

**Comment by OrkoHunter** [comment]
Oh installing peer deps look so unnecessary for the first step in create-app. 850 MB is too much 😕

**Comment by freben** [comment]
Yeah the entire point of having create-app separate from backstage-cli is to be able to make it lightweight and not pull in the entire world upfront before starting. We'll look into it.

**Comment by Rugvip** [comment]
Good find! A sneaky one it seems, couldn't reproduce without a custom cache location, as in it seemed to install a lot less stuff than in a clean install. Trying out #8231

**Comment by Rugvip** [comment]
Verified that this is indeed fixed after #8231 was released, so gonna close

![image](https://user-images.githubusercontent.com/4984472/143465927-dd3c14f6-77ee-4ebe-9122-2bc71ccfe2bc.png)
