### ISSUE TITLE
Add Line Linking In Software Template Logs

### ISSUE THREAD

**Issue by asummers** [backstage/backstage#8229]
## Feature Suggestion

Currently there is no way to link people to specific log sections or lines within a perhaps long log. This would be useful, and has prior art in GitHub, CI systems, among others. This exists on client side, as I can click a log line to highlight, so there's some facility for it, but it never persists in the URL to allow me to share with others.

## Possible Implementation

There's 2 pieces of information to deal with here, the actual section and the line number itself, so perhaps an anchor like `#step-title-L7` or something to facilitate both and allow the UI to respond appropriately when directly opened. I don't feel very strongly about this format, but it illustrates the idea.

**Comment by freben** [comment]
Sure! This would be practical. Are you up for getting started with an implementation?

**Comment by asummers** [comment]
Unfortunately don't have bandwidth to tackle this currently. Just a usage observation from folks on my team =)
