### ISSUE TITLE
Catalog update loop may anger GitHub's secondary rate limits

### ISSUE THREAD

**Issue by Xantier** [backstage/backstage#8232]
## Context

When having a Backstage monorepo location we are seeing GitHub getting angry at us and shouting that secondary rate limits are being hit. 

To reproduce import this catalog-info.yaml either by UI or adding as a location in config: https://github.com/xantier/big-monorepo-fixture/blob/main/catalog-info.yaml . It is a monorepo with 2000 catalog items within it. 

You might need to run through the (very long) update process multiple times to hit this limit on a singular run. For easier reproduction open a few browser tabs and add this location at the same time from each of them. 

We are seeing the following errors around these:
```
2021-11-24T13:16:16.719Z backstage error Error: Unable to read url, HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. type=errorHandler stack=Error: Error: Unable to read url, HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
    at DefaultLocationService.dryRunCreateLocation (/usr/src/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:3960:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /usr/src/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:3080:22
```

Note that GitHub primary rate limits are not being hit during this, just secondary limits. 
```
2021-11-24T13:16:49.108Z githubAppSupport info {"ratelimitData":{"resources":{"core":{"limit":5000,"used":3159,"remaining":1841,"reset":1637762834},"search":{"limit":30,"used":0,"remaining":30,"reset":1637759869},"graphql":{"limit":5000,"used":9,"remaining":4991,"reset":1637762897},"integration_manifest":{"limit":5000,"used":0,"remaining":5000,"reset":1637763409},"source_import":{"limit":100,"used":0,"remaining":100,"reset":1637759869},"code_scanning_upload":{"limit":500,"used":0,"remaining":500,"reset":1637763409},"actions_runner_registration":{"limit":10000,"used":0,"remaining":10000,"reset":1637763409},"scim":{"limit":15000,"used":0,"remaining":15000,"reset":1637763409}},"rate":{"limit":5000,"used":3159,"remaining":1841,"reset":1637762834}}} type=plugin
```

## Why is this happening? 

GitHub doesn't seem to like if the same endpoint is called multiple times concurrently or in rapid succession. https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits 

This is something that seems to happen on monorepos where the Processor/GithubUrlReader loops through the targets within the main catalog-info.yaml file and calls the API once for each target to get more data from the same repository.

## Feature Suggestion & Possible Implementation

Modify processors retrieving data to be aware of the location of the files they are getting. Add logic to retrieve needed files with a singular call to third party APIs. This can be done on few different levels if a hierarchical structure of targets is constructed across multiple yaml files.

**Comment by Rugvip** [comment]
Just to double check, is this with or without the new catalog and UrlReader improvements that enables ETag caching of requests towards GitHub?

**Comment by Xantier** [comment]
> Just to double check, is this with or without the new catalog and UrlReader improvements that enables ETag caching of requests towards GitHub?

Yeah, this would be with both of those on latest-ish. `catalog-backend` on `^0.17.0` and `backend-common` at `^0.9.1` with catalog instantiated with `CatalogBuilder.create`.

I have a feeling that the problem might be monorepo specific where the request loop on large monorepos fetches (sub-entity catalog-info.yaml) files from the same repository while it is traversing the tree of entities it finds. I also can't say I am 100% certain that the issue is surfaceable every time with only a single process looping through the entities and downloading those files, or does it need 2 concurrent processes. Regardless, the UrlReader makes a call to the "sameish" (same repo, different file) GitHub endpoint multiple times and fast which I believe is causing this, that's how I was able to reproduce it. 

We've seen this happening in logs in the past on few occasions, but it has settled fairly quickly after GitHub has reset their limits or otherwise calmed down a little bit. With the addition of these being written to the database as well on PR https://github.com/backstage/backstage/pull/7676, we are seeing some detrimental UX effects when these secondary rate limit errors are bubbled all the way to the UI.

**Comment by Rugvip** [comment]
Would this be using multiple plain registered `url` locations rather than `github-discovery` or a url with a wildcard pattern or anything like that?

I think using a single URL with a pattern like `.../<owner>/<repo/blob/*/**/catalog-info.yaml` will be both more performant and kinder to rate limiters compared to a large number of registered URLs, since it'll use the search API or an archive download.

**Comment by Xantier** [comment]
Hmm, that's interesting. I will need to test that out with the setup again. The reproduction I've done is with a single location in the config file: url pointing to value `https://github.com/xantier/big-monorepo-fixture/blob/main/catalog-info.yaml`. If the wildcard would catch those `catalog-info.yaml` files in subdirectories as well we should be able to circumvent this issue completely then I guess. Then that single location wouldn't need to expand to it's sub-locations necessarily.

The thing to note here though is that the file naming would become stricter and items like defined in[ catalog-model ](https://github.com/backstage/backstage/tree/master/packages/catalog-model/examples)for example wouldn't really play too well with it.

**Comment by Rugvip** [comment]
Yep definitely! You'd need to stick to something a bit more strict most likely, perhaps plain `catalog-info.yaml`, `*-info.yaml` and any other pattern :grin:

Should note ofc that this is another reason to move the webhooks work forward

**Comment by zhammer** [comment]
hey @Rugvip ! is there an issue to track broader work on "the webhooks work"? asking as i was referred here from the discord by @jhaals as the closest issue to tracking changes from pull-based to push-based architecture for the catalog [here](https://discord.com/channels/687207715902193673/923144214580191282/929164089668804689).

it's important for our org to have some insight into progress here, both so we can have a loose understanding of timelines (and potential changes to our architecture) and also to provide input into architecture decisions based on our needs. (for instance, i would like to know if the decided solution is strictly _webhooks_ or if there's a potential for a CI pipeline push model that behaves like the recommended techdocs CI push architecture.)

**Comment by benjdlambert** [comment]
Maybe not very specific, but we have some loose ticket tracking here #8162 #9161 

Probably could do with a little more effort to put some better higher level ticket together.

**Comment by jcarres-mdsol** [comment]
This has stated to happen to us when upgrading to backstage 1.5 and to github provider rather than processor
In our case we are running a job that retrieves all the catalog files, add extra info and puts them in one directory in a repository, our config looks like this

```
  providers:
    github:
      generatedFactbooks:
        organization: 'YYYY'
        catalogPath: 'generated/*.yaml'
        filters:
          branch: 'develop'
          repository: 'YYYYYY'
```

there are like 300 files on that generated directory.

Our previous configuraiton using the processor did not hit the limit or it did not log the error

**Comment by benjdlambert** [comment]
@jcarres-mdsol what is the schedule that you are running the Provider on? The Provider will not run on the same loop as before with the processor so it could be that it's running too often? By default I think it runs every 30mins, but that should be enough?

**Comment by jcarres-mdsol** [comment]
@benjdlambert yes, it is running every 30 min, we could potentially tweak that I imagine
