### ISSUE TITLE
cli: yarn start should warn when app.baseUrl conflicts with backend.baseUrl

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#8251]
## Feature Suggestion

If the `app.baseUrl` and `backend.baseUrl` are set to the same value when running `yarn start` we should probably warn or even hard fail, as I can't think of any valid configuration where you would want that.

I think it's worth a warning because it's hard to figure out what going wrong if you do this by mistake, as running both the backend and the frontend on the same port can lead to some pretty unexpected behavior.

Worth noting that using an identical value for the two URLs is a fully valid production configuration, but `yarn start` is only for use in development.

## Possible Implementation

We could implement this as part of the `app:serve` command in the CLI, which already [loads in the app-config](https://github.com/backstage/backstage/blob/dc57a35ad5eda6c22e5cbe532c3ded14b9250cb0/packages/cli/src/commands/app/serve.ts#L59). It could make sense to limit the check to `localhost:*` URLs, as there could potentially be valid setups that use the same URL but with other hostnames. It's probably best to start off with a warning.

## Context

[Troubleshooting this on Discord](https://discord.com/channels/687207715902193673/913134083180199986/913576427830542446)

**Comment by Rugvip** [comment]
Yep this is just for local development, for production it's fine if they're the same

**Comment by djamaile** [comment]
@Rugvip seems like putting comments down at two in the night impacted my reading abilities! Sorry, for the comment 😃
