### ISSUE TITLE
Airbrake Plugin

### ISSUE THREAD

**Issue by doreilly257** [backstage/backstage#8268]
Integrate Airbrake Error and Performance Monitoring data and app/code health into Portal

https://airbrake.io/
Similar service and integration required as per Rollbar

SaaS API - https://airbrake.io/docs/api/
Github - https://github.com/airbrake/

**Comment by freben** [comment]
Nice! Is this something that you would be up for contributing yourselves?

**Comment by moltenice** [comment]
Hello @freben, we are looking into implementing this and would be happy to contribute.

We are thinking of creating this plugin on this repo itself.

Are there any steps on contribution I should follow and how do you recommend I start? Happy to just start coding away and making a PR as a first step :)

**Comment by freben** [comment]
@moltenice Yeah go ahead! Start small and then iterate in future PRs is often a good idea, to make it easier to review. If you have any questions about specifics, always feel free to reach out. There's a fair bit of inspiration to be taken from other plugins that are in roughly the same space as well. I'll assign you to the ticket to mark it as being "claimed", if that's ok.

**Comment by moltenice** [comment]
> @moltenice Yeah go ahead! Start small and then iterate in future PRs is often a good idea, to make it easier to review. If you have any questions about specifics, always feel free to reach out. There's a fair bit of inspiration to be taken from other plugins that are in roughly the same space as well. I'll assign you to the ticket to mark it as being "claimed", if that's ok.

Sounds good, thanks very much!

**Comment by moltenice** [comment]
Oh completely forgot updating here, but the Airbrake plugin is live! 🎉 

https://github.com/backstage/backstage/tree/master/plugins/airbrake

It's very early stages so won't provide the most value up front (just shows the last few Airbrakes on a tab for each project), but we hope to start adding more features to it over time, and of course contributions from anyone else welcome!

**Comment by freben** [comment]
Ah, so let's close then! 🥳
