### ISSUE TITLE
[RFC] Can we override catalog-react plugin components?

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#8270]
**Status:** Open for comments

## Need

I need a simple change like changing the background color on https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/components/UserListPicker/UserListPicker.tsx#L49

This component cannot be overridden (not available in BackstageOverrides) and it is a bit tricky to uniquely identify it because of JSS classes conversion after building the app (the class `CatalogReactUserListPicker` is renamed after build)

Any recommendations on overriding the styles for the components that are not available in the BackstageOverrides group?

**Comment by Rugvip** [comment]
You should be able to override it using the `CatalogReactUserListPicker` key and the instructions over [here](https://backstage.io/docs/getting-started/app-custom-theme#overriding-backstage-and-material-ui-components-styles), does that work?

**Comment by ProticM** [comment]
Yes, this is how I'm creating my overrides.

The problem is that `CatalogReactUserListPicker` key does not exist in the `BackstageOverrides` type, so I cannot use that key to override the background.

Not sure, but it seems that the `catalog-react` plugin misses `overridableComponents` file like one of these two:

https://github.com/backstage/backstage/blob/45c04f6ffdeb6ee58361d040ee5feb95d15f0ad8/packages/core-components/src/overridableComponents.ts

https://github.com/backstage/backstage/blob/a239f67c7f4c9b64675f77a864dc55502a4b74aa/plugins/catalog/src/overridableComponents.ts

Is that may be the cause why the key is not there?

**Comment by simonsandersje** [comment]
Importing the catalog-react overrides and adding to the theme works for me:

`import { BackstageOverrides as UserListOverrides } from '@backstage/plugin-catalog-react'

export const createUserPickerOverrides = (_: BackstageTheme): UserListOverrides => {
  return {
      CatalogReactUserListPicker: {
        root: {
          backgroundColor: '#fafafa'
        }
      }
  }
}

export const lightTheme: BackstageTheme = {
  ...lightThemeBase,
  overrides: {
    // These are the overrides that Backstage applies to `material-ui` components
    ...lightThemeBase.overrides,
    // These are your custom overrides, either to `material-ui` or Backstage components.
    ...createCustomThemeOverrides(lightThemeBase),
    ...createUserPickerOverrides(lightThemeBase)
  }
}
`

**Comment by ProticM** [comment]
Hi @simonsandersje 👋 

It seems that the overridable components were added in the mean time. See here https://github.com/backstage/backstage/blob/2997bbe3c4a859447933790c7419010189ac8632/plugins/catalog-react/src/overridableComponents.ts

We can now see that the `CatalogReactUserListPicker` can be found in the file above. 🚀 

This configuration was missing for the `catalog-react` plugin, as mentioned here https://github.com/backstage/backstage/issues/8270#issuecomment-982361648 

Good to have this in place 🚀 Thanks for mentioning it here 🙇
