### ISSUE TITLE
Unable to hit backstage frontend : running on localhost:3000

### ISSUE THREAD

**Issue by Chetan77-hub** [backstage/backstage#8271]
Please provide solution. Not able to hit backstage frontend from browser.If any changes needed app.config.yaml . Thanks.

**Comment by Rugvip** [comment]
Hi! Would need a more information to be able to figure out what's up in this case. Did you follow the instructions at https://backstage.io/docs/getting-started/create-an-app?

You should be able to run `yarn dev` in your Backstage app and then visit localhost:3000. If that doesn't work there should hopefully be some output in the terminal with some clues towards what might be going wrong, in which case you could post that here.

I will close this for now, please reopen if you still end up having trouble getting started!
