### ISSUE TITLE
Kafka - throwing 404 errors

### ISSUE THREAD

**Issue by nvadluri** [backstage/backstage#8288]
Hello, I have followed the instructions and installed Frontend and Backend Kafka plugins, and updated the configs accordingly, but I am getting 404 still. This is how I set it up

1. app-config.yaml
kafka:
  clientId: consumer-atg-enterprise-2
  clusters:
    - name: east-preprod
      brokers:
         - mybroker.us-east-1.aws.confluent.cloud:9092
      sasl:
        mechanism: plain # or 'scram-sha-256' or 'scram-sha-512'
        username: 6SUC*************
        password: nxXPiI1VkW************************************************

2. on component 
  annotations:
    kafka.apache.org/consumer-groups: east-preprod/my-consutmer-group-name

3. packages/backend/src/plugins/kafka.ts
import { createRouter } from '@backstage/plugin-kafka-backend';
import { PluginEnvironment } from '../types';

export default async function createPlugin({
  logger,
  config,
}: PluginEnvironment) {
  return await createRouter({ logger, config });
}

4. packages/backend/src/index.ts
import kafka from './plugins/kafka';
// ...
async function main() {
  // ...
  const kafkaEnv = useHotMemoize(module, () => createEnv('kafka'));
  // ...
  apiRouter.use('/kafka', await kafka(kafkaEnv));

Getting below 404 error 
<img width="1534" alt="Screen Shot 2021-11-30 at 1 45 54 PM" src="https://user-images.githubusercontent.com/84935639/144108882-ed8abbb3-8b1d-44af-a47a-ac6e9d603abe.png">

**Comment by nvadluri** [comment]
Any help please ?

**Comment by adamdmharvey** [comment]
The 404 would certainly mean that `/kafka` Backend link didn't properly get registered.

I'll admit to not being familiar with this particular plugin, bu wonder if you check one of the other backend ones if you can find a difference?

e.g., https://github.com/backstage/backstage/tree/master/plugins/todo-backend

I'll suggest your step 3 looks a lot more lightweight than the example in the todo-backend like maybe something is missing.  I'd agree the kafka-backend plugin README likely needs some improving!

**Comment by adamdmharvey** [comment]
e.g., should there be a KafkaService object in there somewhere?

```typescript
export default async function createPlugin({
  logger,
  reader,
  config,
  discovery,
}: PluginEnvironment): Promise<Router> {
  const todoReader = TodoScmReader.fromConfig(config, {
    logger,
    reader,
  });
  const catalogClient = new CatalogClient({ discoveryApi: discovery });
  const todoService = new TodoReaderService({
    todoReader,
    catalogClient,
  });

  return await createRouter({ todoService });
}
```

**Comment by nvadluri** [comment]
@adamdmharvey Thanks for checking...Yes, I agree, but I am not sure how can I make up my file with that. Do you mind helping me get my file as the to-do file? I am trying to mimic that, but I am getting errors.

**Comment by Rugvip** [comment]
Setup looks alright tbh. Is there any clue in the contents of the 404 response? Does it tell you if it that the endpoint is missing or whether it's successfully looking things up in kafka but failing to find anything?

**Comment by nvadluri** [comment]
I can only see the message which is on the post…other than that, nothing I can see about the issue..

Thanks & Regards
Naveen Vadluri

________________________________

**Comment by nvadluri** [comment]
2021-12-01T23:49:51.959Z backstage info ::ffff:10.*.*.* - - [01/Dec/2021:23:49:51 +0000] "GET /api/kafka/consumers/east-preprod/my-consutmer-group-name/offsets HTTP/1.1" 404 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36" type=incomingRequest

**Comment by nvadluri** [comment]
@Rugvip I can see this thing only, no other info

 2021-12-01T23:49:51.959Z backstage info ::ffff:10...* - - [01/Dec/2021:23:49:51 +0000] "GET /api/kafka/consumers/east-preprod/my-consutmer-group-name/offsets HTTP/1.1" 404 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36" type=incomingRequest

**Comment by nvadluri** [comment]
@Rugvip 
Questions-
does the cluster name play key role ? or it doesn't matter ?
Can we user clusterid instead of cluster name ? if yes, how can we annotate ?

**Comment by andrewthauer** [comment]
Try setting `ssl: true` as well.

```
clusters:
  - name: my-cluster
    brokers:
      - my-bootstrap-server:9092
    ssl: true
    sasl:
      mechanism: plain
      username: xxxx
      password: xxxx
```

**Comment by nvadluri** [comment]
@andrewthauer I did try earlier with SSL true, and now as well, no change. Do I need to add any proxy settings or any API related settings?

**Comment by andrewthauer** [comment]
I don't think so. Could it be an ACL issue?

**Comment by nvadluri** [comment]
I did install the Kafka CLI in my pod and verified the connectivity with this below command, and I got the response. 

bin/kafka-console-consumer.sh --bootstrap-server mybroker.us-east-1.aws.confluent.cloud:9092 --from-beginning --topic my-topic-name --consumer.config command.config

How can I verify the ACL is actually allowing the action?  is there any way to verify from the pod (which backstage is trying to do)?

**Comment by nvadluri** [comment]
@andrewthauer I did install the Kafka CLI in my pod and verified the connectivity with this below command, and I got the response.

bin/kafka-console-consumer.sh --bootstrap-server mybroker.us-east-1.aws.confluent.cloud:9092 --from-beginning --topic my-topic-name --consumer.config command.config

How can I verify the ACL is actually allowing the action? is there any way to verify from the pod (which backstage is trying to do)?

**Comment by andrewthauer** [comment]
ACLs would only be applicable if your using a service account I. confluent. In that case, I believe all you need is allow describe permissions on the resources your are accessing.

**Comment by nvadluri** [comment]
@andrewthauer 
<img width="1301" alt="Screen Shot 2021-12-02 at 12 57 28 PM" src="https://user-images.githubusercontent.com/84935639/144477834-337973de-fb87-46b6-8848-5fc028d6b76e.png">


This is one of our topics.

**Comment by nvadluri** [comment]
@andrewthauer  I did run this on the pod and got the response (did hide the details with *)

root@backstage-5694654794-qbqt4:/app/kafka_2.13-3.0.0# bin/kafka-topics.sh --describe --topic my-topic-name --bootstrap-server my-broker:9092 --command-config command.config
[2021-12-02 20:35:52,763] WARN The configuration '[Tuesday' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
Topic: qa.core.res.atg_create_order_na  PartitionCount: 3       ReplicationFactor: 3    Configs: min.insync.replicas=2,segment.bytes=104857600,message.format.version=2.3-IV1,max.message.bytes=2097164
        Topic: qa.core.**********  Partition: 0    Leader: 2       Replicas: 2,0,3 Isr: 3,2,0
        Topic: qa.core.**********  Partition: 1    Leader: 0       Replicas: 0,1,5 Isr: 5,1,0
        Topic: qa.core.**********  Partition: 2    Leader: 5       Replicas: 5,2,4 Isr: 5,4,2
root@backstage-5694654794-qbqt4:/app/kafka_2.13-3.0.0#

**Comment by nvadluri** [comment]
@andrewthauer or Team, any solution ?

**Comment by andrewthauer** [comment]
@nvadluri - The config I posted above should work with Confluent. 

Your CLI test is using the native java library so it's possible there is a default config difference from `kafkajs` in relation to how it works with your pod networking setup. Perhaps taking a closer look at the underlying `kafkajs` code for some differences might give some insight.

**Comment by nvadluri** [comment]
@andrewthauer Finally it worked, with a simple unexpected fix. I just rearranged the statements in packages/backend/src/index.ts, moved from bottom to top, and it worked. 

  const apiRouter = Router();
  **apiRouter.use('/kafka', await kafka(kafkaEnv));**
  apiRouter.use('/aws', await aws(awsEnv));
  apiRouter.use('/catalog', await catalog(catalogEnv));
  apiRouter.use('/scaffolder', await scaffolder(scaffolderEnv));
  apiRouter.use('/auth', await auth(authEnv));
  apiRouter.use('/techdocs', await techdocs(techdocsEnv));
  apiRouter.use('/proxy', await proxy(proxyEnv));
  apiRouter.use('/search', await search(searchEnv));
  apiRouter.use(notFoundHandler());

**Comment by jhaals** [comment]
Thanks a lot Andrew and Adam for helping out!
I'm closing this issue as it looks like it's resolved now. Just reopen if that's not the case.
