### ISSUE TITLE
How to enable LOG_LEVEL=debug ?

### ISSUE THREAD

**Issue by nvadluri** [backstage/backstage#8289]
Hello,

my backstage application is running on the EKS cluster, and I would like to enable LOG_LEVEL=debug, can you please provide me instructions to enable that?

**Comment by jrusso1020** [comment]
@nvadluri do you have an example of your Backstage k8s deployment YAML file? The short answer is you need to set the `LOG_LEVEL` environment variable for you deployment however you set environment variables

You can set `LOG_LEVEL` either in a k8s configmap which your deployment uses to populate it's environment from or you can add the environment variable directly to the container for the deployment.

Check out https://humanitec.com/blog/handling-environment-variables-with-kubernetes if you are unsure how to do this

**Comment by nvadluri** [comment]
thank you for the reply, and I enabled it by adding the env variable directly to my deployment, and it's working now...thank you so much for the response

**Comment by nvadluri** [comment]
@jrusso1020 thank you for the reply, and I enabled it by adding the env variable directly to my deployment as you mentioned, and it's working now...thank you so much for the help. (I have another issue, if you can please check that once and provide any suggestions, would be very helpful)
