### ISSUE TITLE
Backstage app not able to fetch a page with base URL on refresh

### ISSUE THREAD

**Issue by meghanakhuntia** [backstage/backstage#8293]
The backstage app with a basePath such as `/backstage` is able to load the page `/backstage/catalog` for the first time, but once refreshed it is not able to fetch/ get the page with route `/backstage/catalog`

## Expected Behavior

It should be able to render the page with the `/backstage/catalog` route

## Current Behavior

Currently, it crashes with a message `Cannot GET /backstage/catalog`

## Steps to Reproduce

[Follow this link to reproduce the issue](https://github.com/backstage/backstage/pull/6749)

## Your Environment
Using these versions
 "@backstage/core-app-api": "^0.1.23",
 "@backstage/core-components": "^0.6.0",
 "@backstage/core-plugin-api": "^0.1.9",

**Comment by jhaals** [comment]
Hi

Are you seeing this problem in production or just during local development?

It's currently a known problem in development where the dev server tries to load the index.html from /.
This is of course something we should fix but I just want to double check if there's an issue in production as well.

**Comment by meghanakhuntia** [comment]
Yes, this issue is there in production as well. This is our app config ```
app:
  title: ${TITLE}
  baseUrl: ${HOST_URL}/${BASE_PATH}
  gqlUrl: ${GRAPHQL_URL}

organization:
  name: ${COMPANY_NAME}

backend:
  baseUrl: ${URL}/${BACKEND_BASE_PATH}
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: ${HOST_URL}
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
        host: ${POSTGRES_HOST}
        port: ${POSTGRES_PORT}
        user: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
  cache:
    store: memory

integrations:
  github:
    - host: github.com
      token:
        $env: GITHUB_TOKEN
techdocs:
  builder: 'local'
  generators:
    techdocs: 'docker'
  publisher:
    type: 'local'

auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
    auth0:
      development:
        clientId: ${AUTH0_CLIENT_ID}
        clientSecret: ${AUTH0_CLIENT_SECRET}
        domain: ${AUTH0_DOMAIN}
    okta:
      development:
        clientId: ${OKTA_CLIENT_ID}
        clientSecret: ${OKTA_CLIENT_SECRET}
        audience: ${OKTA_DOMAIN}

scaffolder:
  github:
    token: 
      $env: GITHUB_TOKEN
    visibility: public
```
We are facing this issue on page refresh but for now we have handled using nginx config.
 But the UI component served by internal plugins doesn't include the base path. For ex: /search and other internal buttons

**Comment by sachin-kumar-ik8** [comment]
Steps to produce this error:

1. Serve frontend with basepath
2. build and deploy frontend with nginx or http-server.
3.  route to different page forex: /basepath/catalog or any other path
4. Refresh the page. On refresh it will so can not get /basepath/catalog and site will crash.

**Comment by meghanakhuntia** [comment]
Hi,
This issue seems to be resolved in the production environment. When we created a new `test app` and served using Nginx it seemed to work. Currently, we are migrating away from backstage/core and will update here if the issue still exists.
