### ISSUE TITLE
Reviewers Wanted!

### ISSUE THREAD

**Issue by jhaals** [backstage/backstage#8294]
We are looking for your help reviewing incoming pull requests to community plugins.
There is a constant stream of contributions to our community plugins and we are looking for contributors to help us out reviewing these changes. If you have created, made contributions to, or used an existing plugin, then you can help the community by reviewing incoming changes!

### I’m not an experienced reviewer
No one is perfect at code reviews but more eyes on pull requests lead to less bugs, mistakes and in the end better code! Your stamp of approval will count as another signal for the maintainers ultimately merging the pull request. Pre-approved pull requests are much more likely to be reviewed and merged quicker.

### What if I don’t have enough time?
No worries. Your life isn’t going to change being a code owner, the primary difference is that you will get notified about changes by Github automatically instead of having to manually scan for incoming PRs.

### Does it mean I can merge code if I think it looks good?
Not initially as we want to make sure that everything runs smoothly and cannot be abused.

### Suggested Codeowners
We’ve run through the plugins that we currently have in the monorepo and picked a few key contributors that we think would be a great fit for Codeowners and be the first point of contact when it comes to changes to the plugins. Of course, we’re not going to force you to commit to doing it, but it would be great if you think there’s someone else that you could nominate instead :pray: 

If your name isn’t listed in the suggestions, but still feel like you would be a great fit for reviewing code changes in a particular plugin then feel free to skip to the next section and raise a PR adding yourself! :)

| plugin name                              | suggested reviewers + codeowners  |
| ---------------------------------------- | --------------------------------- |
| `allure `                                | @deepak-bhardwaj-ps               |
| `api-docs `                              | @fox32                            |
| `app-backend `                           | @backstage/maintainers            |
| `auth-backend `                          | @backstage/maintainers            |
| `azure-devops `                          | @awanlin @marleypowell            |
| `azure-devops-backend `                  | @awanlin @marleypowell            |
| `azure-devops-common `                   | @awanlin @marleypowell            |
| `badges `                                | @kaos                             |
| `badges-backend `                        | @kaos                             |
| `bazaar `                                | @lykkeaxlin @klaraab              |
| `bazaar-backend `                        | @lykkeaxlin @klaraab              |
| `bitrise `                               | @petergrau                        |
| `catalog `                               | @backstage/maintainers            |
| `catalog-backend `                       | @backstage/maintainers            |
| `catalog-backend-module-ldap `           | @backstage/maintainers            |
| `catalog-backend-module-msgraph `        | @fox32                            |
| `catalog-graph `                         | @fox32                            |
| `catalog-graphql `                       | @backstage/maintainers            |
| `catalog-import `                        | @dhenneke                         |
| `catalog-react `                         | @backstage/maintainers            |
| `circleci `                              | @andrewthauer                     |
| `cloudbuild `                            | @ebarriosjr                       |
| `code-coverage `                         | @alde                             |
| `code-coverage-backend `                 | @alde                             |
| `config-schema `                         | @backstage/maintainers            |
| `cost-insights `                         | @silver-lining                    |
| `explore `                               | @fox32                            |
| `explore-react `                         | @fox32                            |
| `firehydrant `                           | @hizegi                           |
| `fossa `                                 | @dhenneke                         |
| `gcp-projects `                          | @ebarriosjr                       |
| `git-release-manager `                   | @erikengervall                    |
| `github-actions `                        | @backstage/maintainers            |
| `github-deployments `                    | ❓                                |
| `gitops-profiles `                       | @chanwit                          |
| `graphiql `                              | @backstage/maintainers            |
| `graphql-backend `                       | @backstage/maintainers            |
| `ilert `                                 | @yacut                            |
| `jenkins `                               | @timja @ashirley                  |
| `jenkins-backend `                       | @timja @ashirley                  |
| `kafka `                                 | @nirga @andrewthauer              |
| `kafka-backend `                         | @nirga @andrewthauer              |
| `kubernetes `                            | @mclarke47 @backstage/maintainers |
| `kubernetes-backend `                    | @mclarke47 @backstage/maintainers |
| `kubernetes-common `                     | @mclarke47 @backstage/maintainers |
| `lighthouse `                            | ❓                                |
| `newrelic `                              | ❓                                |
| `org `                                   | @lewtakm                          |
| `pagerduty `                             | @backstage/maintainers            |
| `permission-backend `                    | @backstage/maintainers            |
| `permission-common `                     | @backstage/maintainers            |
| `permission-node `                       | @backstage/maintainers            |
| `proxy-backend `                         | @dhenneke                         |
| `rollbar `                               | @andrewthauer                     |
| `rollbar-backend `                       | @andrewthauer                     |
| `scaffolder `                            | @backstage/maintainers            |
| `scaffolder-backend-module-rails `       | @angeliski                        |
| `scaffolder-backend-module-yeoman `      | @pawelmitka                       |
| `scaffolder-backend-module-cookiecutter` | @backstage/maintainers            |
| `search-backend-module-elasticsearch `   | @xantier                          |
| `search-backend-module-pg `              | @fox32                            |
| `sentry `                                | @rodiongork                       |
| `sentry-backend `                        | @rodiongork                       |
| `shortcuts `                             | @backstage/maintainers            |
| `sonarqube `                             | @dhenneke                         |
| `splunk-on-call `                        | @taitken-splunk                   |
| `tech-insights-backend `                 | @xantier                          |
| `tech-insights-backend-module-jsonfc `   | @xantier                          |
| `tech-insights-common `                  | @xantier                          |
| `tech-insights-node `                    | @xantier                          |
| `tech-radar `                            | @backstage/maintainers            |
| `todo `                                  | @backstage/maintainers            |
| `user-settings `                         | @backstage/maintainers            |
| `xcmetrics `                             | @ngranander                       |

### How do I add myself? 
Simple, raise a PR against `.github/CODEOWNERS` adding yourself to an existing plugin in the list or create a new line for the plugin of your interest. It’s important to have `@backstage/reviewers` as the first entry in the list of owners and then your username.

```yaml
/plugins/plugin_name				@backstage/reviewers @username
```

**Comment by Fox32** [comment]
I would like to handover my assignments to someone at SDA SE, for example @dschwank, I will probably not be able to handle it in the future 😞 But I don't think he will get a notification this way?

**Comment by benjdlambert** [comment]
@Fox32 yep thought that might be the case, but that's great. @dschwank does that seem OK to you that we you in the `CODEOWNERS` for all the things that's owned by @Fox32 right now in the above list?

**Comment by dhenneke** [comment]
@benjdlambert I will also very likely not be able to do it. Especially the `fossa` and `sonarqube` plugins might be open to be taken over by someone from the SDA SE. The other topics are quite specific and are open for the community.

**Comment by petergrau** [comment]
@benjdlambert is is possible to assign a GitHub group that is part of another organisation? (I think that would be the preferred solution for the SDA SE instead of assigning individuals.)

**Comment by benjdlambert** [comment]
@petergrau I believe it should be possible, if not we could create a group in the Backstage Org instead. Do you have one that we could try with maybe and see what our options are?

**Comment by timja** [comment]
> @petergrau I believe it should be possible, if not we could create a group in the Backstage Org instead. Do you have one that we could try with maybe and see what our options are?

highly doubt an outside group will be possible, you can't even ping teams from outside the org you're currently interacting in.

**Comment by dschwank** [comment]
@benjdlambert @jhaals @dhenneke @Fox32 Sure, happy to contribute & help you out with some reviews 🥳

> @benjdlambert @jhaals is is possible to assign a GitHub group that is part of another organisation? (I think that would be the preferred solution for the SDA SE instead of assigning individuals.)

A group would be awesome, so we can share the ownership within the SDA SE!

**Comment by benjdlambert** [comment]
Yep @timja is right, doesn't look like that is possible. @backstage/maintainers what do you think about the option of creating some additional org groups for use cases like this or should we stick to list of users?

**Comment by freben** [comment]
That should be ok. Maybe make some naming pattern for them - `codeowners-sda-se` etc?

**Comment by timja** [comment]
> Not initially as we want to make sure that everything runs smoothly and cannot be abused.

Have you tested this out? According to the GitHub docs you need write access, https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

> The people you choose as code owners must have write permissions for the repository

**Comment by petergrau** [comment]
> That should be ok. Maybe make some naming pattern for them - `codeowners-sda-se` etc?

that would work for us.

**Comment by Rugvip** [comment]
@petergrau sent over an invite, we'll see if I can let you invite the rest or if we're gonna need a list x)

**Comment by Rugvip** [comment]
@petergrau Alright, gave you access to manage the team, let me know if that's enough or if we need to handle the organization level access too

**Comment by petergrau** [comment]
> @petergrau Alright, gave you access to manage the team, let me know if that's enough or if we need to handle the organization level access too

@Rugvip Looks like that I can add members but only if they are part of the org already. Should I give you a list of people?

**Comment by Rugvip** [comment]
@petergrau yep, please do, haven't found any better way to handle it right now short of setting up automation ._.

**Comment by petergrau** [comment]
> @petergrau yep, please do, haven't found any better way to handle it right now short of setting up automation ._.

@Rugvip here you go: 

- dschwank
- adrianbarwicki
- kaiszybiak
- m4s7
- iammnils

**Comment by jhaals** [comment]
Closing this issue now. Help and review support is still welcome of course ❤️

**Comment by freben** [comment]
@petergrau invited!

**Comment by Hennnnes** [comment]
Hey,
could you please remove @dschwank and add @jsprh (https://github.com/jsprh) to our team (https://github.com/orgs/backstage/teams/sda-se-reviewers)? Thanks in advance :)
