### ISSUE TITLE
info.message.replace is not a function when viewing a Component 

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#8306]
## Expected Behavior

I should be able to view my component in the catalog.

## Current Behavior

After the last upgrade, I am getting a series of the same error, info.message.replace is not a function when viewing a component, this was working fine 2 releases ago.

![image](https://user-images.githubusercontent.com/6157895/144273639-2d630320-b178-446e-9654-ad3bc968c585.png)

## Steps to Reproduce

1. Open Component 
2. Same error shows multiple times

## Your Environment

- NodeJS Version (v14): Node16
- Operating System and Version (e.g. Ubuntu 14.04): Win10
- Browser Information: Chrome and Edge

**Comment by jhaals** [comment]
That is strange indeed. With last upgrade do you mean the latest version? `yarn backstage-cli info` will output the versions of all dependencies.

This is likely something blowing up in the backend which can't be serialised properly. Could you check if you get more clues or a stack trace from the backend? You can run the backend with `LOG_LEVEL=debug yarn start-backend`

**Comment by freben** [comment]
Potentially related (fairly low certainty level, but worth mentioning): https://github.com/backstage/backstage/pull/8143
Temporary fix that doesn't address underlying cause: https://github.com/backstage/backstage/pull/8326

**Comment by freben** [comment]
OK after some discussion, it seems that #8326 might actually be a proper fix for what amounts to a legitimate logging call. It's merged and will be released later today. After the release, you should be able to bump your dependency on `@backstage/backend-common` to make this problem go away. Thanks for reporting!

**Comment by regicsolutions** [comment]
Thanks, ill give it another try with the latest release.

Question: This is how i have been using `replaceProcessors `in my backend catalog.ts (been working fine since **release-2021-11-17.1**

```
  builder.replaceProcessors([
    new ScaffolderEntitiesProcessor(),
    new FileReaderProcessor(),
    BitbucketDiscoveryProcessor.fromConfig(env.config, {
      parser: customBitbucketRepositoryParser,
      logger: env.logger,
    }),
    LdapOrgReaderProcessor.fromConfig(env.config, {
      logger: env.logger,
      groupTransformer: customGroupTransformer,
      userTransformer: customUserTransformer,
    }),
    new UrlReaderProcessor({ reader: env.reader, logger: env.logger }),
    new LocationEntityProcessor({ integrations }),
    new AnnotateLocationEntityProcessor({ integrations }),
  ]);
  
```
Given `FileReaderProcessor`, `UrlReaderProcessor `and `AnnotateLocationEntityProcessor` are being returned as part of the `getDefaultProcessors`:

https://github.com/backstage/backstage/blob/c2da6492fb917002517a54638e1da6fa523f2a8f/plugins/catalog-backend/src/service/NextCatalogBuilder.ts#L289

Would i just add it like this?
```
  builder.replaceProcessors([
    new ScaffolderEntitiesProcessor(),
    BitbucketDiscoveryProcessor.fromConfig(env.config, {
      parser: customBitbucketRepositoryParser,
      logger: env.logger,
    }),
    LdapOrgReaderProcessor.fromConfig(env.config, {
      logger: env.logger,
      groupTransformer: customGroupTransformer,
      userTransformer: customUserTransformer,
    }),
    new LocationEntityProcessor({ integrations }),
  ]);
// Gets Default Processors 
    builder.getDefaultProcessors();
```

**Comment by regicsolutions** [comment]
@freben i have confirmed your fix in the latest release fixed my issue, Thank You!
