### ISSUE TITLE
[Plugin] Teamcity

### ISSUE THREAD

**Issue by nhall97** [backstage/backstage#833]
## Summary
Show general build status against PRs, deployments from a Teamcity server.

## Project website (if applicable)

https://www.jetbrains.com/teamcity/

## Context
Similarly to the issues raised around Jenkins and other CI solutions - Teamcity is a common enterprise CI/CD solution.

While not open source, there is a free tier available classed as 'professional'.

**Comment by stefanalund** [comment]
@nhall97 nice! Will you be working on this or do you want me to add a [help wanted] label?

FYI you can probably look at this PR for inspiration: https://github.com/spotify/backstage/pull/748

**Comment by nhall97** [comment]
thanks @stefanalund. I don't think I'd be able to build the whole thing but certainly interested around getting involved 

Potentially help wanted would be useful :+1:

**Comment by MarkZither** [comment]
hi, has any progress been made on this? If not I can have a go, based on the circle ci example and https://www.jetbrains.com/help/teamcity/rest-api.html#General+Usage+Principles it should be ok to do.

**Comment by stefanalund** [comment]
I have assigned you @MarkZither -- thanks!

**Comment by OrkoHunter** [comment]
Re-opening since plugin suggestion issues are now exempt from [stalebot](https://github.com/backstage/backstage/blob/18f7345a6c29dcfccef7df081b1708f2bf8f62ff/.github/stale.yml#L9).

**Comment by matt-richardson** [comment]
Hey @MarkZither - did you manage to make any progress on this? We'd be keen to use it and/or contribute to the development.

**Comment by AtebMT** [comment]
We'd also been keen to use a teamcity plugin.

**Comment by danielgonzalez3** [comment]
Hey Folks,

I found this plugin to work pretty well for our org:
https://www.npmjs.com/package/backstage-plugin-teamcity

**Comment by jhaals** [comment]
Closing as it seems like we have a teamcity plugin 👏 !

**Comment by Ernstsen** [comment]
The mentioned plugin is no longer working properly, which forced us to make a fork to be able to use it.
We are keeping the work public, it is available here:
https://github.com/stakeholderit/backstage-teamcity
https://www.npmjs.com/package/@stakeholderit/backstage-plugin-teamcity

We will do our best to react to PRs if there are missing features.
