### ISSUE TITLE
dependency checker picks up imports that happen inside JavaScript comments

### ISSUE THREAD

**Issue by cowboyd** [backstage/backstage#8339]
## Expected Behavior

You should be able to have code examples in documentation that make use of import statements, especially when the purpose of the documentation is to demonstrate an integration with a 3rd party library.

## Current Behavior

In #8147 which allows you to bring your own search client, I wanted to add some documentation(https://github.com/backstage/backstage/pull/8147/files#diff-f44544683d7f8bc09f46b1ef1bcfd748e9f5c8cb12d7c95bdb618ec547774763R18-R25) on how to import your 3rd party dependency, and the dependency checker picked up as a dependency that needed to be addressed(https://github.com/backstage/backstage/runs/4297876300?check_suite_focus=true#step:20:16)

## Possible Solution

We can strip out comments before searching for dependencies. 

## Context

I'm happy to take a stab at this in order to get it across the finish line.

**Comment by OrkoHunter** [comment]
Thanks for reporting @cowboyd - I believe [this import detection logic](https://github.com/backstage/backstage/blob/a2fbab1f07ccd9fa1724fdc7e0bbc92bae54fc48/scripts/check-type-dependencies.js#L79-L92) needs to be a bit smarter. :D

**Comment by RushilMehra** [comment]
I’d love to try and pick this up as my very first issue. Is anyone able to reproduce locally?

**Comment by OrkoHunter** [comment]
@RushilMehra Awesome! If you checkout the PR https://github.com/backstage/backstage/pull/8147 locally, you will find that running `node scripts/check-type-dependencies.js` will result into the same error as in the CI run logs https://github.com/backstage/backstage/runs/4297876300?check_suite_focus=true#step:20:16

Make sure to do the init steps as well e.g. `yarn install`, `yarn build` and `yarn tsc`.

**Comment by RushilMehra** [comment]
@OrkoHunter Thanks! Will do

**Comment by cowboyd** [comment]
@OrkoHunter It doesn't seem like there are any tests for the dependency checker. Is this something that would be worth adding?

**Comment by RushilMehra** [comment]
@cowboyd That's a good idea, I can look into adding some test coverage for this function as well

**Comment by OrkoHunter** [comment]
Yeah, none of the `./scripts` we have to manage this repository has tests. @Rugvip thoughts? Should they be its own package with tests and utility and all?
