### ISSUE TITLE
TechRadar Url Target Definition

### ISSUE THREAD

**Issue by brunopenso** [backstage/backstage#8347]
TechRadar Url Target Definition

## Feature Suggestion

Add the ability to define which target the URL will open when clicking on the `Learn More` link

## Possible Implementation

as-is:
```
export const setUsedTools = (entries: RadarEntry[]): void => {
  entries.push({
    timeline: [
      {
        ringId: 'use',
        date: new Date('2020-08-07'),
      },
    ],
    url: 'https://github.com',
    key: 'github-code',
    id: 'github-code',
    title: 'GitHub',
    quadrant: 'tools',
  });
}
```

to-be:
```
export const setUsedTools = (entries: RadarEntry[]): void => {
  entries.push({
    timeline: [
      {
        ringId: 'use',
        date: new Date('2020-08-07'),
      },
    ],
    url: 'https://github.com',
    urlTarget: '',
    key: 'github-code',
    id: 'github-code',
    title: 'GitHub',
    quadrant: 'tools',
  });
}
```

The field urlTarget should support all oficial w3c data: https://www.w3schools.com/tags/att_a_target.asp

## Context

When you are first looking to the tech radar you are curious to understand each information, but when you click on the `Learn More` the current tab browser is redirect to the destination.

Should I open a PR?

**Comment by jhaals** [comment]
Hi @brunopenso
Is this primarily to be able to do `target='_blank'` and open in a new tab or are there other reasons? If that's the case I'd vote for making this the default and call it a day :)

**Comment by freben** [comment]
Seems from [the implementation](https://github.com/backstage/backstage/blob/884c451191480a0389e7e76744d08ba2aab7f09f/plugins/tech-radar/src/utils/components.tsx#L30) that it uses a regular `<a>` today. If you change this to instead use the `Link` component from `@backstage/core-components`, you'll get the proper, system-wide-standard, link behavior and styles. This includes opening external links in a new tab/window, per default.

**Comment by brunopenso** [comment]
@jhaals for our use case you are right, maybe target blank could be the default option.

@freben thx. I will look at it.

**Comment by benjdlambert** [comment]
Assigned!

**Comment by brunopenso** [comment]
Hi Guys, PR is open and waiting for your validation.
Thx

**Comment by benjdlambert** [comment]
Closing ats the
