### ISSUE TITLE
AWS S3 Discovery processor not added

### ISSUE THREAD

**Issue by nigelwright-roam** [backstage/backstage#8351]
## Expected Behavior
   
Going through the documents here : https://backstage.io/docs/integrations/aws-s3/discovery it is assumed that there are no additional config steps required in order to enable S3 discovery. I have an S3 integration added, and can add items from my bucket into the catalog using the importer, but discovery would throw a warning message: `warn No processor was able to handle reading of s3-discovery:https://my-bucket.s3.ap-southeast-2.amazonaws.com/` 

## Current Behavior

s3-discovery processor not added and a  `warn No processor was able to handle reading of s3-discovery:https://my-bucket.s3.ap-southeast-2.amazonaws.com/` message is raised.

## Possible Solution

If I add a new processor in plugins/catalog.ts then the s3 discovery works fine :
`builder.addProcessor(new AwsS3DiscoveryProcessor(reader))`
 
I'm not sure if this is expected, or if there is just a gap in the documentation right now .

## Steps to Reproduce

Create S3 bucket and provide access
 
Add AWS S3 Integration:
https://backstage.io/docs/integrations/aws-s3/locations#configuration
 
Add s3 discovery location:
https://backstage.io/docs/integrations/aws-s3/discovery
 
No processor warning for s3-discovery : ` warn No processor was able to handle reading of s3-discovery:https://my-bucket.s3.ap-southeast-2.amazonaws.com/`

## Context

Trying to utilise the s3 discovery to import all my entities

## Your Environment

OS:   Darwin 20.6.0 - darwin/arm64
node: v14.18.2
yarn: 1.22.10
cli:  0.9.1 (installed)

**Comment by jhaals** [comment]
Hi @nigelwright-roam,
This is expected as the S3 discovery processor is not one of the default providers.
But you're right that some documentation would help new users. Would you be willing to contribute a few lines to https://github.com/backstage/backstage/edit/master/docs/integrations/aws-s3/discovery.md ? :)

**Comment by nigelwright-roam** [comment]
@jhaals - yup, added a brief update on the docs to reflect this.
