### ISSUE TITLE
New Display Switch

### ISSUE THREAD

**Issue by Expalex** [backstage/backstage#8352]
##  Feature Suggestion
Expedia Group (EG) would like to propose an OS contribution for a display switch feature that follows a mouseover:   [New Display_switch_video](https://drive.google.com/file/d/14l3UhO40K1CBQGFqnyW6iUC0r5eMBZtV/view?usp=sharing) . 
Something similar is already on our EG’s Backstage:  [Existing_switch_video](https://drive.google.com/file/d/1hqMnbaMQmf7_lFSOMBHiw4v3Yp8Ui7ko/view?usp=sharing) .

**Questions**
1. Does this new display switch feature need OS contribution for us to use or is it not needed because it’s similar to the one existing?
2. If it does, what else can we provide you?

## Usage
The switch feature is to display metrics and additional information. 
Tooltip will tell what the graph is about.

**Comment by jhaals** [comment]
First of all I think this looks good and makes this more understandable! :)
Is this additional features to an existing component or is this a new "score card" component?
@Xantier and his team at roadie has been working on the backend parts of tech insights and this looks very related but for the frontend. Perhaps there's some opportunities to work together on those efforts!

**Comment by Xantier** [comment]
Could this be something to be added as a higher order wrapper component for the core framework where the integrator can pass in default displayable component and the hover component?

**Comment by Expalex** [comment]
This would be a replacement component.
What’s shown in  Existing_switch_video is really a design bug. We are replacing this behavior with “I” information icon via tooltip and static progress indicator. On projects where it’d benefit to show an additional information will be conveyed as shown in New Display_switch_video.

**Comment by Expalex** [comment]
@jhaals @Xantier I a UX designer and still new to the OS contribution process. Would a good following step be to start developing this ourselves or have our developer contact Xantier directly to discuss a possible collaboration effort in detail?

**Comment by Xantier** [comment]
Absolutely. If there's a need to bounce off ideas, ask questions etc. I'll be available on the Backstage Discord during (central european) working hours.

**Comment by jhaals** [comment]
I assume this is for the Gauge component and it should be fine to just add it as optional props on that component.
I'm not sure about how the implementation would look for the higher order wrapper component but feel free to explore it if you'd like! :)

**Comment by benjdlambert** [comment]
Closing as #8807 is now merged.
