### ISSUE TITLE
Errors with self-hosted gitlab instances with subpath in the url

### ISSUE THREAD

**Issue by daydy16** [backstage/backstage#8358]
We're experiencing different issues with backstage not correctly calling gitlab's api when using a subpath in the gitlab url.
Our self-hosted gitlab has the url: git.abc.com/gitlab 

First issue: Register step fails 
When creating a component the scaffolder fails at the registering step because it seems to use a wrong api-url.
We're using a self-hosted gitlab that is only reachable when using the subpath /gitlab. 
Even though the url is displayed correctly in the log output, the request is sent to a wrong url, what you can see later in the logs.

Second issue: [Gitlab discovery ](https://backstage.io/docs/integrations/gitlab/discovery) not working
When using the gitlab discovery feature the same error appears

## Expected Behavior
Backstage should use the correct gitlab url so that 
1. the component can be registered porperly
2. the component scanning works

## Current Behavior

1. Backstage seems to build the wrong api url for some calls (strangely enough it uses the correct url at the publish step)
The component creation fails at the 3. step (register), after templating and publishing correctly
right url: https://git.abc.com/gitlab/dfl/david/-/blob/master/catalog-info.yaml
wrong url: https://git.abc.com/api/v4/projects/gitlab%2Fdfl%2Fdavid

> 2021-12-03T09:12:17.000Z` Beginning step Register

>2021-12-03T09:12:40.000Z info: Registering https://git.abc.com/gitlab/dfl/david/-/blob/master/catalog-info.yaml in the catalog {"timestamp":"2021-12-03T09:12:32.054Z"}
2021-12-03T09:15:35.000Z Error: {"error":{"name":"Error","message":"Error: Unable to read url, Error: Could not get GitLab project ID for: **https://git.abc.com/gitlab/dfl/david/-/blob/master/catalog-info.yaml**, FetchError: invalid json response body at **https://git.abc.com/api/v4/projects/gitlab%2Fdfl%2Fdavid** reason: Unexpected token < in JSON at position 0","level":"error","service":"backstage"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":500}}
>    at CatalogClient.addLocation (/tmp/backstage/backstage-test/node_modules/@backstage/catalog-client/dist/index.cjs.js:94:13)
>    at runMicrotasks (<anonymous>)
>    at processTicksAndRejections (internal/process/task_queues.js:95:5)
>    at async Object.handler (/tmp/backstage/backstage-test/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:146:24)
>    at async HandlebarsWorkflowRunner.execute (/tmp/backstage/backstage-test/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2184:11)
>    at async TaskWorker.runOneTask (/tmp/backstage/backstage-test/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2444:143)
>    at async /tmp/backstage/backstage-test/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2438:9`

2.: When adding gitlab-discovery to the catalog in app-config.yaml the discovery fails with following error:
right url: https://git.abc.com/gitlab/api/v4/groups/dfl/projects?group=dfl&last_activity_after=2021-12-03T11%3A14%3A13.015Z&page=1&include_subgroups=true
wrong url: https://git.abc.com/gitlab/api/v4/groups/gitlab%2Fdfl/projects?group=gitlab%2Fdfl&last_activity_after=2021-12-03T11%3A14%3A13.015Z&page=1&include_subgroups=true

>[1] 2021-12-03T11:18:19.229Z catalog warn Processor GitLabDiscoveryProcessor threw an error while reading gitlab-discovery:https://git.abc.com/gitlab/dfl/blob/*/catalog-info.yaml; caused by Error: Unexpected response when fetching https://git.abc.com/gitlab/api/v4/groups/gitlab%2Fdfl/projects?group=gitlab%2Fdfl&last_activity_after=2021-12-03T11%3A14%3A13.015Z&page=1&include_subgroups=true. Expected 200 but got 404 - Not Found type=plugin entity=location:default/generated-7ae1f5b64c6c61003b96425cdfc1f7ab4d53440f

## Possible Solution

1. Allow subpaths in host url in the integrations in app-config.yaml
2. Fix wrong url build with subpath somewhere deep in the code. I specified the baseURL and apiBaseURL in the integrations but it looks like at a few places these vars are not used correctly

## Steps to Reproduce
>Gitlab Config in app-config.yaml
>'integrations:
>  gitlab:
>    - host: 'git.abc.com/gitlab'
>      apiBaseUrl: https://git.abc.com/gitlab/api/v4
>      baseUrl: https://git.abc.com/gitlab
>      token: lalilu
>
>scaffolder:
>  gitlab:
>    token: lalilu
>    visibility: 'internal' # or 'public' or 'private'
>
>catalog:
>  rules:
>    - allow: [Component, System, API, Group, User, Resource, Location]
>    
>  locations:
>    - type: gitlab-discovery
>      target: https://git.abc.com/gitlab/dfl/blob/main/catalog-info.yaml'

Im trying to create a default spring boot component from the default backstage spring-boot-sample 
Used template:

> apiVersion: backstage.io/v1beta2
> kind: Template
> metadata:
>   name: springboot-template
>   title: Spring Boot Service
>   description: Create a simple microservice using Spring Boot Java with presets
>   tags:
>     - recommended
>     - java
>     - springboot
> spec:
>   owner: daydy16
>   type: service
>   
>   parameters:
>     - title: Provide some simple information
>       required:
>         - component_id
>         - owner
>         - java_package_name
>       properties:
>         component_id:
>           title: Name
>           type: string
>           description: Unique name of the component
>         java_package_name:
>           title: Java Package Name
>           type: string
>           description: Name for the java package. eg (com.abc.)
>         description:
>           title: Description
>           type: string
>           description: Help others understand what this app is for.
>         owner:
>           title: Owner
>           type: string
>           description: Owner of the component
>           ui:field: OwnerPicker
>           ui:options:
>             allowedKinds: 
>               - Group
>     - title: Choose a location  
>       required:
>         - repoUrl
>       properties: 
>         repoUrl:
>           title: Repository Location
>           type: string
>           ui:field: RepoUrlPicker
>           ui:options:
>             allowedHosts:
>               - git.abc.com
>               - github.com
> 
>   steps:
>     - id: template
>       name: Fetch Skeleton + Template
>       action: fetch:template
>       input:
>         url: ./skeleton
>         values:
>           component_id: '{{ parameters.component_id }}'
>           description: '{{ parameters.description }}'
>           artifact_id: '{{ parameters.component_id }}'
>           java_package_name: '{{ parameters.java_package_name }}'
>           owner: '{{ parameters.owner }}'
>           destination: '{{ parameters.repoUrl }}'
>           http_port: 8080
> 
>     - id: publish
>       name: Publish
>       action: publish:gitlab
>       input:
>         allowedHosts:
>         - git.abc.com
>         - github.com
>         description: 'This is {{ parameters.component_id }}'
>         repoUrl: '{{ parameters.repoUrl }}'
> 
>     - id: register
>       name: Register
>       action: catalog:register
>       input:
>         repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
>         catalogInfoPath: '/catalog-info.yaml'
> 
>   output:
>     repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
>     remoteUrl: '{{ steps.publish.output.remoteUrl }}'
>     entityRef: '{{ steps.register.output.entityRef }}'

## Context

As long as backstage cant handle host urls with subpaths we cant start using it

## Your Environment
local development windows 10 with wsl2 and Ubuntu 20.04.3 LTS and Google Chrome

yarn run v1.22.17
$ backstage-cli info
Debugger attached.
OS:   Linux 5.10.16.3-microsoft-standard-WSL2 - linux/x64
node: v14.18.1
yarn: 1.22.17
cli:  0.9.0 (installed)

**Comment by jhaals** [comment]
Hi @daydy16, sorry to hear that you're having issues.
Regarding the internals, I believe both of these uses the GitlabUrlReader(https://github.com/backstage/backstage/blob/master/packages/backend-common/src/reading/GitlabUrlReader.ts) for reading files if you're interested to learn more about what's happening internally.
Could you try to make `host: 'git.abc.com/gitlab'` into `host: 'git.abc.com'` in your app-config.yaml. I'm appending your subpath in the baseUrl and apiBaseUrl should be enough.

**Comment by daydy16** [comment]
Hey @jhaals 
Thanks for your quick reply.
It was a copy paste issue in my previous post
`host:` is configured as you suggested: git.abc.com
If I enter git.abc.com/gitlab the app does not start correctly and says that host url is not valid.
I will have a look at the gitlabUrlReader tomorrow, thx :)

**Comment by daydy16** [comment]
I found a few spots that causes the error:
https://github.com/backstage/backstage/blob/master/packages/integration/src/gitlab/core.ts#L141
In my opinion it would be better to use 
`${config.apiBaseUrl}/projects/${encodeURIComponent`
instead of `${url.protocol + url.hostname}/api/v4/projects/${encodeURIComponent`

Another problem is, that `url.pathname` includes the /gitlab suffix, that belongs to the host
So a better way would be to generate the pathname by removing parts of the apiBaseUrl of the path

I "fixed" the compontent registration issue by statically replacing some vars. I'm not sure whats the best way to proceed in this case.

**Comment by Develbold** [comment]
@daydy16 Could you please elaborate on your solution? I'm having the same problem, but I can't fix it yet

**Comment by daydy16** [comment]
@Develbold unfortunately i'm not a developer. As i said, i fixed it by using the javascript "replace" comand and adding /gitlab to some variables.
But I try my best to find the errors and provide a solution.

Btw: at the moment I only fixed the registration issue, not the gitlab component scanner.

**Comment by daydy16** [comment]
Here is my workaround for both issues: 
https://github.com/daydy16/backstage-issue-8358/commit/68c87095fa435a0dbfcca3ea65d594b93caba754
I also fixed the component scanner.
The hardest part was to find the right spots in the code.
I tried to fix it in a propper way, so that we could merge it, but i dont know what would be the best approach to do it.
If anyone of the devs could have a look and provide an easy solution, would be awesome!

**Comment by daydy16** [comment]
I also had to fix an issue when pulling a template skeleton from our gitlab instance:
https://github.com/daydy16/backstage-issue-8358/commit/8de52a6080cd67982631d27b2e464c9f17e0ce0c

**Comment by daydy16** [comment]
Here is another fix that is needed for the OAuth Login 
https://github.com/daydy16/backstage-issue-8358/commit/c798d641fb03c4deda55bcf9557681a15a532381

**Comment by freben** [comment]
@daydy16 Could your findings be turned into a pull request? 🙏

**Comment by daydy16** [comment]
@freben: unfortunately i'm not a developer. I only built a workaround by stripping /gitlab in some vars and adding /gitlab to some others, so that we can test backstage internaly. Thats not how we can use it in production.
I dont know how to fix it in a right way. Maybe there has to be a change in how the gitlab-config-vars from app-config.yaml are used in the code (see:
https://github.com/daydy16/backstage-issue-8358/commit/68c87095fa435a0dbfcca3ea65d594b93caba754)

**Comment by jhaals** [comment]
Are there perhaps some places not using the baseUrl correctly? We have a slightly related problem for bitbucket which is getting fixed by https://github.com/backstage/backstage/pull/9177 but that integration did not even have the concept of baseUrl previously.

**Comment by daydy16** [comment]
Thanks @jhaals. Look's like that's exactly what is missing here.
Should we copy the finding of this [pull request ](https://github.com/backstage/backstage/pull/9177) into another one for gitlab?

**Comment by Rugvip** [comment]
@daydy16 Yep, although the GitLab config already has a `baseUrl` that can be set. It's likely more about making sure we're using it were needed. There's likely some significant overlap with #9095 too though, as that's aiming for a general solution to SCM URL parsing, which we definitely wanna move forward :grin:

**Comment by daydy16** [comment]
@Rugvip Can you help me to find out where the baseurl is set?
