### ISSUE TITLE
yarn test ( backstage-cli test ) hangs forever

### ISSUE THREAD

**Issue by shanthisagar-dhanya-kumar-db** [backstage/backstage#8367]
$ yarn test --verbose --logHeapUsage --useStderr --passWithNoTests --forceExit --detectOpenHandles packages/backend
yarn run v1.22.11
$ backstage-cli test --json --verbose --logHeapUsage --useStderr --passWithNoTests --forceExit --detectOpenHandles packages/backend
PASS example-backend packages/backend/src/index.test.ts (55 MB heap size)
  test
    √ unbreaks the test runner (5 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.545 s
Ran all test suites matching /packages\\backend/i.

After the above run, it just hangs there forever

**Comment by jhaals** [comment]
Hi
This is expected behaviour when running tests and not a bug. It monitors the files for changes. If you want it to not wait use `--watch=false` or set the environment variable `CI=true`
