### ISSUE TITLE
Make software template dropdown fields with one option readonly

### ISSUE THREAD

**Issue by nissayeva** [backstage/backstage#8368]
## Feature Suggestion

Make required scaffolder dropdown fields readonly by default if there is only one option available

## Possible Implementation

Somehow set `disabled={true}` on all `Select` components if there is only one `option`, with the value set to the value of that option

## Context

With software templates, it seems unnecessary to be able to edit required dropdown fields if there is only one option available, but it might be useful to still see the value in the form (as well as submit that value with the form). Examples of this are the `host` field in `RepoUrlPicker` when the template includes only one option for `allowedHosts`, and more recently the `owner` field in `RepoUrlPicker` when `allowedOwners` only has one option (introduced in #8207).

**Comment by lukzerom** [comment]
@nissayeva can i take it as my first issue here? ❤️

**Comment by timbonicus** [comment]
@lukzerom For sure, assigned!

**Comment by lukzerom** [comment]
@timbonicus  Great ! :)

**Comment by benjdlambert** [comment]
Just a little observation that this could be a little tricky as we don't control the rendering of all input fields. It's done by `react-jsonschema-form` and then the `material-ui` theme ontop of it. I wonder if it's worth us trying to contribute this to the upstream library instead of solving this locally in Backstage instead? Thinking that other users of this library would also be happy to have this as a feature too!

I think we could do it locally in Backstage, but think it would require a little trickery to render the parent `FieldTemplate` with some clever options, and not sure of the viability or complexity it would require.

**Comment by lukzerom** [comment]
@benjdlambert yeah, this is tricky -  it's would be good idea to make some feature request into `react-jsonschema-form` - anyway, i started digging deep - so I will try to provide solution for option 1.  fix locally in Backstage and then we can decide - or do both : )

**Comment by lukzerom** [comment]
Hey @timbonicus @benjdlambert . So, i made some research about above and tried to write it as clean as possible. 

First approach  was to add some rule in [shema.ts](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/MultistepJsonForm/schema.ts) that would disable controls if there are `options.length === 1`

Unfortunately - the place where we fetch options, for example  for repo hosts  in [RepoUrlPicker](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/RepoUrlPicker/RepoUrlPicker.tsx) is somewhere deep inside the form, close to MUI controls.

So, the final solution would be adding something very simple like this , next to our MUI Select and AutocompleteSelect controls: 

`  <Select  disabled={hosts?.length === 1} {...someProps} ` and this could work. 
This is how it will looks like :

<img width="732" alt="Zrzut ekranu 2021-12-10 o 00 08 47" src="https://user-images.githubusercontent.com/55348672/145490430-869eeddb-7dd8-4c16-a8fe-b12bd96b1fa8.png">

I actually prepared branch with simple changeset - but can't push it to create PR 😬 i got some 
403 permission error. 

So i would have 2 more questions -

**1. Question.** 

 Do you know how i can push my branch ? 😅 

**2. Question**

During all this research - i have noticed that MUI Components are imported directly from `@material-ui/core` when we already have them (documented with storybook etc) in `@backstage/core-components` - which is better to use?

Best regards 
Łukasz

**Comment by benjdlambert** [comment]
You'll need to fork the project I think and push to your fork, and then open a PR from the fork.

wrt components in `core-components` can you give examples of some?

**Comment by lukzerom** [comment]
@benjdlambert  sure , for example this -> [https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/Select/Select.tsx](https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/Select/Select.tsx) Same component from Material UI library wrapped with our props, test, styles etc. But for scaffolder purposes - some API extension to this component would be needed.

**Comment by benjdlambert** [comment]
Maybe we could override the `Select` that is rendered in `react-jsonschema-form` for our own select that wraps up the `@backstage/core-components` one? I think it should be possible with some additional props in `<Form>` hopefully.

Otherwise maybe try it in the `RepoUrlPicker` and see what it looks like?

**Comment by lukzerom** [comment]
@benjdlambert  ok - I will propose this approach with the soonest PR

**Comment by lukzerom** [comment]
@benjdlambert @timbonicus here is ready PR [https://github.com/backstage/backstage/pull/8453/files](https://github.com/backstage/backstage/pull/8453/files)
