### ISSUE TITLE
Can't change the location Host when creating a new Software Component

### ISSUE THREAD

**Issue by tkmdenis** [backstage/backstage#8375]
Hello, 

I am trying to create a component from a template but i can't change the location host as you can see on the image below. I want to add my enterprise gitlab private repository. 

![image](https://user-images.githubusercontent.com/19282853/144821858-ada659fa-acbb-4c05-aacb-21df1a211e16.png)

I added the gitlab integration as mentionned here : https://backstage.io/docs/integrations/gitlab/locations. 

I also added Gitlab to scaffolder inside the app-config.yml but nothing has change. I also try to open my backstage app in a private navigation mode but it doesn't change anything. 

If there is a solution, feel free to respond. If not, you can also respond. Maybe i would have to develop a plugin which can integrate Gitlab? I don't know.

**Comment by jhaals** [comment]
Hi, 

The allowed host for publishing is configured in the scaffolder template. Look for `allowedHosts` in the template in and make sure that gitlab.com is added to the list.

Please reopen this issue if you have further problems or questions about this! Good luck
