### ISSUE TITLE
[TechDocs] Docs are not loaded on Entity Page due to TechDocs Beta Migration

### ISSUE THREAD

**Issue by mertcb** [backstage/backstage#8381]
On entity page "Docs" tab, plugin tries to go `api/techdocs/static/docs/default/Component/<component_name>` endpoint. So since we migrated our documentations to TechDocs Beta, loading the documentations fails.

## Expected Behavior

On the actual docs page, plugin tries to go `api/techdocs/static/docs/default/component/<component_name>` like shown in below. And as it's supposed to be... 

<img width="1792" alt="Ekran Resmi 2021-12-06 14 16 26" src="https://user-images.githubusercontent.com/36340604/144837040-bace95cb-c413-43f2-916b-526f759ee426.png">

So on entity page "Docs" tab, plugin should go to `api/techdocs/static/docs/default/Component/<component_name>` endpoint.

## Current Behavior

On entity page "Docs" tab, plugin tries to go `api/techdocs/static/docs/default/Component/<component_name>` like shown in below. 

<img width="1792" alt="Ekran Resmi 2021-12-06 14 13 13" src="https://user-images.githubusercontent.com/36340604/144836621-bdc611c3-1471-45bb-9a3c-c1a3f8c384d9.png">

## Possible Solution

On this line, https://github.com/backstage/backstage/blob/594e73aa1c222820f7f96f0162076aea38adec25/plugins/techdocs/src/EntityPageDocs.tsx#L26 lowerCaseMaybe function can be added to entity kind name. 

## Steps to Reproduce

Firstly, create documentation on your component. Then try to go this documentation with TechDocs home page. You should see the documentation. After that, try to go documentation on Entity's page by Docs tab here. You should see the documentations doesn't load. 

Btw, in our catalog-info.yaml ( we are using different name of file, but doesn't matter), the kind of entity is uppercased. (i.e `kind: "Component"`).

## Your Environment

- NodeJS Version (v14): v14.17.5
- Operating System and Version (e.g. Ubuntu 14.04): MacOS Big Sur 11.5.2
- Browser Information: Brave Browser

**Comment by mertcb** [comment]
A PR fixes this issue at #8394 @OrkoHunter

**Comment by emmaindal** [comment]
Thanks for opening this issue and a follow up PR @mertcb, I've added a couple of comments on the PR!
