### ISSUE TITLE
EntityPicker - option for disabling arbitrary values

### ISSUE THREAD

**Issue by GoFightNguyen** [backstage/backstage#8388]
In the `EntityPicker`, make the `Autocomplete.props.freeSolo` configurable.

## Feature Suggestion

There are times when we need a user to choose a processed entity.

## Possible Implementation

Add `allowArbitraryValues` boolean to `ui:options`, defaulting to true so existing behavior remains.

## Context

We are creating software-templates to assist teams in quickly cataloging their entities piece-by-piece.

**Comment by GoFightNguyen** [comment]
If you like this direction, we are ready and willing to create the PR

**Comment by benjdlambert** [comment]
Sure sounds good - assigned to you!
