### ISSUE TITLE
Oauth2 Failed - Multiple Providers

### ISSUE THREAD

**Issue by bradrisse** [backstage/backstage#8389]
Attempting to login using Oauth2 provider that previously worked, it now provides the error 

`
Login failed; caused by Error: Authentication failed, Cannot supply multiple client credentials. Use one of the following: credentials in the Authorization header, credentials in the post body, or a client_assertion in the post body.
`

## Expected Behavior

Authorization modal to open and redirect appropriately after login

## Current Behavior

Opens authorization modal, closes immediately, and then displays error above

## Possible Solution

I believe this addition caused the error.

https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/providers/oauth2/provider.ts#L88

**Comment by jhaals** [comment]
should be fixed by #8303 8397

**Comment by benjdlambert** [comment]
Closing as should have been shipped today. Re-open if still having problems :)
