### ISSUE TITLE
Techdocs Context Search returns no results with PGSearchEngine due to inconsistent casing

### ISSUE THREAD

**Issue by jasonhadi** [backstage/backstage#8390]
## Expected Behavior

When searching using the search bar on a Techdocs page backed by PGSearchEngine, the search bar will return some results.

## Current Behavior

When searching using the search bar on a Techdocs page backed by PGSearchEngine, the search bar will return **no results.**  Searching in the Catalog Search is successful, and results for content in Techdocs documentation are presented. 

For example, on the page `/docs/default/component/xyz`, search requests are to `/api/search/query?term=request&filters%5Bkind%5D=component...` which return 200, but no results are returned.

![image](https://user-images.githubusercontent.com/1145473/144932622-91c54ddc-68d1-41ce-b0eb-2880d7857910.png)

 If the page is changed to `/docs/default/Component/xyz` (note the casing) search requests to `/api/search/query?term=request&filters%5Bkind%5D=Component...` are generated which return 200 and has results.

![image](https://user-images.githubusercontent.com/1145473/144932867-3cd7b489-cfc3-47d9-a30f-8873213ca9ca.png)

Setting `techdocs.legacyUseCaseSensitiveTripletPaths: true` in the `app-config.yaml`  changes the documentation index to link to `/docs/default/Component/xyz` but the page itself returns a 404. 

## Possible Solution

Some discussion has occurred in https://github.com/backstage/backstage/pull/7800. I think it would be ideal if the requests were case insensitive, whether that be achieved on the indexer using a lower case entity name, or the application normalizing to a consistent casing. 

## Steps to Reproduce

1. Enable the PGSearchEngine as indicated on https://backstage.io/docs/features/search/search-engines#postgres
2. Follow backstage.io documentation to create a component and an attached set of TechDocs documentation. Any of the legacy case sensitive flags should not be enabled. 
3. Browse to the documentation via `/docs` and select the component's documentation on the page `/docs/default/component/xyz`.
4. Attempt to search for anything and find no results.
5. Change the URL to `/docs/default/Component/xyz` and search, finding search results. 

## Context

The TechDocs context search is enabled by default and would like to have it working for our users! 

## Your Environment

Reproduced in Firefox 94.0.2.

```
OS:   Linux 5.4.72-microsoft-standard-WSL2 - linux/x64
node: v14.17.3
yarn: 1.22.10
cli:  0.9.1 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.1
  @backstage/backend-common                                0.9.12
  @backstage/catalog-client                                0.5.2
  @backstage/catalog-model                                 0.9.7
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.10.0, 0.9.1
  @backstage/config-loader                                 0.8.1
  @backstage/config                                        0.1.11
  @backstage/core-app-api                                  0.1.24
  @backstage/core-components                               0.7.6
  @backstage/core-plugin-api                               0.2.2
  @backstage/errors                                        0.1.5
  @backstage/integration-react                             0.1.14
  @backstage/integration                                   0.6.10
  @backstage/plugin-api-docs                               0.6.16
  @backstage/plugin-app-backend                            0.3.19
  @backstage/plugin-auth-backend                           0.4.10
  @backstage/plugin-catalog-backend                        0.19.0
  @backstage/plugin-catalog-graph                          0.2.2
  @backstage/plugin-catalog-import                         0.7.4
  @backstage/plugin-catalog-react                          0.6.4
  @backstage/plugin-catalog                                0.7.3
  @backstage/plugin-github-actions                         0.4.25
  @backstage/plugin-org                                    0.3.29
  @backstage/plugin-proxy-backend                          0.2.14
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.5
  @backstage/plugin-scaffolder-backend                     0.15.15
  @backstage/plugin-scaffolder-common                      0.1.1
  @backstage/plugin-scaffolder                             0.11.13
  @backstage/plugin-search-backend-module-elasticsearch    0.0.5
  @backstage/plugin-search-backend-module-pg               0.2.1
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.2.7
  @backstage/plugin-search                                 0.5.0
  @backstage/plugin-tech-radar                             0.4.12
  @backstage/plugin-techdocs-backend                       0.11.0
  @backstage/plugin-techdocs                               0.12.8
  @backstage/plugin-user-settings                          0.3.12
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.10.8
  @backstage/test-utils                                    0.1.23
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.0
Done in 0.69s.
```

**Comment by Xantier** [comment]
I believe this issue was introduced during item #7800. Instead of restoring the original casing to the collator, we should modify it to follow the convention in use in the rest of the tech docs search space. Elsewhere `techdocs.legacyUseCaseSensitiveTripletPaths` configuration option is adhered to and that determines which casing should be used for URLs and search params. The collator should be made to be aware of that config also.

**Comment by emmaindal** [comment]
Thank you for opening this issue @jasonhadi I'll assign it to me and start take a look at a solution for this now!

**Comment by emmaindal** [comment]
@Fox32 can you check the two problems listed above and if solving the case sensitivity for postgres is something you have been looking into before?

**Comment by Fox32** [comment]
@emmaindal I tried to explain the problem in #7800.

I'm not working on Backstage anymore, so I can support help on this topic.

**Comment by Xantier** [comment]
Not stale. This is fixed with https://github.com/backstage/backstage/pull/9333

**Comment by emmaindal** [comment]
Since the above PR is merged, I'll go on and close this issue, please re-open if the issue still occurs.
