### ISSUE TITLE
Scaffolder: EntityPicker Read Only and Owned ui:option ?

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#8391]
## Feature Suggestion

It would be great to have a `ui:option` to make the EntityPicker field Read only and be able to only show entities owned by the logged in user.

## Possible Implementation
If I want to show all component in 'Read' only mode and only list entities with the kind 'Component' that are 'Owned' by the logged in user:

        component:
          title: Component
          type: string
          description: Component
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - Component
            allowedPermissions:
              - Read
              - Owned 
            defaultKind: Component

## Context

User `john.smith` who is part of the `infrastructure` group wants to increase his services memory from 2GB to 4GB to a component owned by his group. This entails opening a PR against the secured repository that contains a `Deployment.yaml` that is owned by the `infrastructure` group.

**Comment by benjdlambert** [comment]
Thinking that maybe we should move this stuff to a new component instead. Maybe an `OwnedEntitiesPicker` rather than adding things on top of the entity picker which is supposed to be pretty light.

**Comment by regicsolutions** [comment]
My pleasure, thanks for the PR!

**Comment by mufaddal7** [comment]
We can close this issue and link it with [8438](https://github.com/backstage/backstage/pull/8438)

**Comment by regicsolutions** [comment]
https://github.com/backstage/backstage/pull/8438 ✅ 

TODO: Add option to disable arbitrary values within the New OwnedEntityPicker to mimic same option added to standard EntityPicker #8441
