### ISSUE TITLE
GitHub Catalog Ingestion - Support users belonging in multiple GitHub orgs

### ISSUE THREAD

**Issue by tmalinakis-vng** [backstage/backstage#8401]
A GitHub user who belongs to GitHub teams in multiple GitHub orgs cannot be imported. The catalog fails with the following warning:

```
2021-12-07T12:30:40.437Z catalog warn Detected conflicting entityRef user:default/<USERNAME> already referenced by github-org:https://github.com/<ORG1> and now also github-org:https://github.com/<ORG2> type=plugin
```

## Expected Behavior

GitHub users should be imported without a problem. The memberships should be the union of the memberships of all the GitHub orgs. GitHub users are globally unique. However, this is not true for GitHub teams where there are no guarantees for uniqueness across GitHub orgs (?).

## Current Behavior

We get the warning about conflicting entityRefs and the user's memberships are incomplete (missing the ones from the later org).

## Steps to Reproduce

1. Create a GitHub User
2. Create a GitHub Team in GitHub Org A and assign the user there
3. Create a GitHub Team in GitHub Org B and assign the user there
4. Ingest the GitHub org for both GitHub Orgs (we are using a GitHub App but it's probably not important).

## Context

We are rolling out Backstage to the users of the GitHub Enterprise which consists of multiple GitHub Orgs. Some users contribute and are part of teams that are cross org.

## Your Environment

- NodeJS Version: v 16
- Operating System and Version: Debian Buster
- Browser Information: N/A

**Comment by tmalinakis-vng** [comment]
Hi, I just found out about this the MultiOrg Processor (https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/GithubMultiOrgReaderProcessor.ts). It looks like it could fit our needs. I see that it's alpha and kind of undocumented at the moment though. Are there any strong reasons against using it? Also, would we have to run a migration for the users and teams that have already been imported?

**Comment by benjdlambert** [comment]
@tmalinakis-vng I think you should just replace the current processor with the `MultiOrg` processor and it should work. Don't think there's any reason not to use it, it's probably alpha due to it not being used widely and lacking documentation. Going to close this ticket and re-open if you find anything else :)
