### ISSUE TITLE
Utility API Deprecations

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#8412]
**Analytics API**
@iamEAP - is there any changes that you've noticed from dogfooding this API that you think we should be adding in to run up to core 1.0? Any deprecations that you'd like to make?

- [x] Remove `AnyAnalyticsContext`?
- [ ] ~`CommonAnalyticsContext` fields?~
- [x] Mark AnalyticsApi as experimental

**AppTheme**
- [ ] ~`variant` -> `mode`?~

**Auth**
- [x] mark all `authApi`'s as experimental
- [x] deprecate `auth0AuthApiRef` and create migration guide to creating your own `authApiRef`
- [x] deprecate `oauth2ApiRef` and create migration guide to creating your own `authApiRef`
- [x] deprecate `oidcAuthApiRef` and create migration guide to creating your own `authApiRef`
- [x] Investigate removal of `oneloginAuthApiref`?
- [x] Investigate removal of `samlAuthApiRef`?
- [x] Rename `AuthProvider` to something more specific
- [ ] ~Rename `AuthRequester` to something less awkward?~
- [x] `AuthRequester` -> `OAuthRequester`
- [x] `AuthRequesterOptions` -> `OAuthRequesterOptions`
- [x] `AuthRequestOptions` -> `OAuthRequestOptions`
- [ ] ~`AuthRequester` to options instead of plain `scopes` param~

**Discovery**
- [ ] ~`DiscoveryApi` -> `PluginDiscoveryApi`?~
- [ ] ~`getBaseUrl` -> `getPluginBaseUrl`?~

**ErrorApi**
- [ ] ~`ErrorApiErrorContext` rename `hidden`?~

**ProfileInfoApi**
- [ ] ~`getProfile` -> `getProfileInfo` same as `IdentityApi`~

**StorageApi**
- [x] Investigate async `get`?

The items marked with `?` probably warrant a little more discussion in either the deprecation PR or whilst the work is happening in the mob before committing to doing so.

**Comment by Rugvip** [comment]
Kept `oneloginAuthApiref` because it provides access to some useful user management APIs

**Comment by Rugvip** [comment]
`AuthProvider` was renamed to `AuthProviderInfo` along with the addition of the `id` prop
