### ISSUE TITLE
[RFC] Introduce Dependency Injection Container framework container for Backstage Backend API

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#8414]
**Status:** Open for comments

## Need

We would like to introduce additional customization's for the backstage backend API application.

One such example is the GitHubCredentialsProvider. It is used in a couple of places across the backstage backend application. It is difficult to customize it without creating a static factory method and configuring it upfront using a static setter method (as is proposed here https://github.com/backstage/backstage/pull/8408).

## Proposal

A nicer pattern that can be applied here is use a Dependency Injection Container framework, to allow all mappings of class implementations to interfaces to be explicitly defined upfront in the application.

One such example is a framework call inversify. There are almost certainly others.

## Alternatives

I am not sure about altertives except the static setter method on a global factory as I described above. Maybe there are other alternatives that I do not know about.

## Risks
The challenge with these types of frameworks is that their implementations go wide and deep into the code base and can be difficult to turn back from once they are integrated.

**Comment by punkle** [comment]
This is my first RFC, I hope I structured it correctly. Please let me know.

**Comment by punkle** [comment]
The next steps in this RFC is to provide a couple of proposals of libraries and possible integrations of those libraries into the backstage Backend. Roadie will get benefit from this work and we endeavour to get to it as soon as our priorities allow us.

**Comment by freben** [comment]
Closing as implemented through the new backend system.
