### ISSUE TITLE
warning Resolution field "graphql-language-service-interface@2.8.2" 

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#8421]
I am getting the following warning when bumping to the latest release-2021-12-07

```
warning Resolution field "graphql-language-service-interface@2.8.2" is incompatible with requested version "graphql-language-service-interface@^2.10.1"
warning Resolution field "graphql-language-service-parser@1.9.0" is incompatible with requested version "graphql-language-service-parser@^1.10.4"

```

My build is getting taking a lot longer than usual and stays stuck on this warning:

`warning "workspace-aggregator-9c13275b-5fdb-490a-a395-d7137f0a10c4 > app > @backstage/plugin-api-docs > graphiql > @graphiql/toolkit@0.4.2" has unmet peer dependency "graphql-ws@>= 4.5.0".`

## Your Environment

- NodeJS Version (v14): Node 14
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by benjdlambert** [comment]
I think you should be able to remove the `resolutions` block in your `root` `package.json` that have either the `service-interface` or `service-parser` in them. And if you do a `yarn backstage-cli versions:bump` you should pull in the latest versions for the `api-docs` and `graphiql` plugin if you're using them which should remove this warning.

**Comment by benjdlambert** [comment]
Closing as should have been fixed with the release last week.
