### ISSUE TITLE
Clusters in Rancher

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#8427]
Hi,

Does anyone deploy a cluster on Rancher and connect to the Backstage successfully? I have trouble with authentication.  😭

**Comment by jhaals** [comment]
Hi @chuliang014, would you be able to provide some additional context to what problem you're having?
Deploying Backstage to Rancher shouldn't be any different from deploying to any other service.

**Comment by chuliang014** [comment]
Hi @jhaals, I'm not deploying Backstage to Rancher, but using the Backstage Kubernetes plugin.  And the cluster is on the Rancher, so I tried to connect to that cluster in Rancher from Backstage, but seemed to be failed.  
![image](https://user-images.githubusercontent.com/56138162/145487519-23bad6af-60e9-443f-a2a4-af9c701f650f.png)

What way can I do for checking if I connect to Rancher from backstage successfully?  only 3 logs in terminal.
![image](https://user-images.githubusercontent.com/56138162/145487769-ffd1de50-1f1f-48c7-a50a-34b92a7740d0.png)

**Comment by chuliang014** [comment]
Hi @jhaals, I fixed this issue with upgrading the related `catalog` package such as `@backstage/plugin-catalog`, `@backstage/plugin-catalog-react`
