### ISSUE TITLE
Catalog does not listen to change events in `location`

### ISSUE THREAD

**Issue by hiba-aldalaty** [backstage/backstage#8432]
Issue mentioned in following PR and Discord:
PR: https://github.com/backstage/backstage/pull/8378
Discord: https://discord.com/channels/687207715902193673/687235481154617364/917756886491754526
## Expected Behavior
I should be able to use a `<Link /> ` to navigate to the catalog and use the search query to apply filters e.g.,
```
<Link to="/catalog?filters%5Bkind%5D=component&filters%5Btype%5D=service" />
```

This would allow us to have a `<SidebarSubmenuItem/>` that can be clicked to navigate to the catalog with different filters applied. 

```
          <SidebarSubmenuItem
            title="Services"
            to="catalog?filters%5Bkind%5D=component&filters%5Btype%5D=service"
            icon={HomeIcon}
          />
          <SidebarSubmenuItem
            title="Libraries"
            to="catalog?filters%5Bkind%5D=component&filters%5Btype%5D=library"
            icon={HomeIcon}
          />
```
Clicking the first one would would take us to the catalog, components filtered by service type.
Clicking the second one would change the filter from 'service' -> 'library' in the catalog (causing a re-render).

## Current Behavior

Currently, the Catalog does not react to change events in the `location`. Once it gets loaded, filtering is only done by js.
In the `<SidebarSubmenu/>` case above, 
- Clicking the first one would would take us to the catalog, components filtered by service type.
- Clicking the second one would cause a change in the location (`catalog?filters%5Bkind%5D=component&filters%5Btype%5D=service` -> `catalog?filters%5Bkind%5D=component&filters%5Btype%5D=library`) but the view won't change - the catalog doesn't re-render and continues displaying only the components with `type=service`

Vice versa: if I filter the catalog from within, `location` (`const location = useLocation()`) does not get updated, so the items in the sidebar/submenu won't be set to be active.

## Steps to Reproduce

You can try replacing the Sidebar content and replacing with this snippet locally in `Root.tsx`
```
<Sidebar disableExpandOnHover>
  <SidebarItem icon={HomeIcon} text="Catalog">
    <SidebarSubmenu title="Catalog">
              <SidebarSubmenuItem
                title="Services"
                to="catalog?filters%5Bkind%5D=component&filters%5Btype%5D=service"
                icon={HomeIcon}
              />
              <SidebarSubmenuItem
                title="Libraries"
                to="catalog?filters%5Bkind%5D=component&filters%5Btype%5D=library"
                icon={HomeIcon}
              />
    </SidebarSubmenu>
  </SidebarItem>
</Sidebar>
```

1. Go to `http://localhost:3000/1`
2. Click the 'Services' submenu item in the sidebar - this should take you to the catalog, filtered by `type=service`
3. Click the 'Libraries' submenu item in the sidebar - this will change the search query but the catalog will remain filtered by 'type=service'

Vice versa:
1. Go to http://localhost:3000/catalog
2. Manually filter by Service type - this will update search to something like `catalog?filters%5Bkind%5D=component&filters%5Btype%5D=service` .
3. The 'Service' submenu item won't be highlighted/set to active. 

## Context

Implemented new features for the Sidebar based on this issue: https://github.com/backstage/backstage/issues/6933
 PR: https://github.com/backstage/backstage/pull/7521
The design includes 3 submenu items which allow us to click on them to go to the catalog with different filters applied such as 'service', 'library' and 'website' which is not possible at the moment.

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by benjdlambert** [comment]
Is this something you'd like to contribute @hiba-aldalaty? 🙏

**Comment by daniel-samet** [comment]
Hi @benjdlambert, I am a colleague of @hiba-aldalaty (at Expedia). I will be working on this issue and look forward to contributing. I will be sure to reach out if I have any questions.

**Comment by benjdlambert** [comment]
Great @danielsamet! Let us know if you have any problems or any questions we'd be happy to help :pray:

**Comment by danielsamet** [comment]
Hi @benjdlambert 👋. As the history here shows, I have just created a PR draft to fix this issue. However, I am experiencing a weird issue with it and thought I would reach out for some help.

Testing the code manually seems to work fine. So I proceeded to create a test for my code but noticed something weird. The drafted test code adds 'service' to the URL search parameters and that works fine (it correctly updates the filter dropdown to display 'Service' and filter accordingly). The strange thing happens when changing 'service' to any other option, for example 'library'. We would expect the filter to update to 'Library'... but it doesn't! And I can't explain why.

To clarify, this issue is specifically within Jest - I have not been able to reproduce it when manually testing in the browser.

Click to see the [Test Code](https://github.com/backstage/backstage/pull/8763/files#diff-f7875989ac019df85df0872647a95c39a6bef053b254b5d94d2f3fc1c734747a) in question.

Please let me know if you require any further context to this.

**Comment by awanlin** [comment]
I was just trying to setup the same things and have run into this issue. @danielsamet any updates on this? Anything I might be able to do to help?

**Comment by danielsamet** [comment]
Hi @awanlin, what specifically is the issue you are running into? If you click through to the PR draft you can see the latest updates on it.

**Comment by awanlin** [comment]
Hello @danielsamet, I'm running into the exact issue described in the Steps to Reproduce. We'd like to make seeing the different Kinds easier as the drop down in the Catalog for this isn't very obvious. This seems like a great approach but if you are looking at say APIs and then want to see Components the catalog won't refresh.

I'll keep my eyes on the PR, thanks for contributing this fix 👍

**Comment by awanlin** [comment]
I'm still having the issue described here. I have confirmed that I'm using version 0.6.14 of @backstage/plugin-catalog-react which has the suggested fix in it. Can we re-open this?

**Comment by awanlin** [comment]
Still and issue for us, can we re-open, please? @timbonicus

**Comment by freben** [comment]
Let's revisit! Is there any chance you might be able to help look into the underlying cause?

**Comment by timbonicus** [comment]
Strange, I tested that PR using the snippets from this issue 🤔  happy to chip in here too if needed @awanlin.

**Comment by awanlin** [comment]
I am doing something a little different - I'm only filtering on Kind - but it should still work. Here's the code I'm using for this:

```ts
<SidebarItem icon={MenuBookIcon} to="catalog" text="Catalog">
          <SidebarSubmenu title="Catalog">
            <SidebarSubmenuItem
              title="Domains"
              to="catalog?filters%5Bkind%5D=domain"
              icon={DomainIcon}
            />
            <SidebarSubmenuItem
              title="Systems"
              to="catalog?filters%5Bkind%5D=system"
              icon={SystemIcon}
            />
            <SidebarSubmenuItem
              title="Components"
              to="catalog?filters%5Bkind%5D=component"
              icon={ComponentIcon}
            />
            <SidebarSubmenuItem
              title="APIs"
              to="catalog?filters%5Bkind%5D=api"
              icon={ApiIcon}
            />
            <SidebarDivider />
            <SidebarSubmenuItem
              title="Resources"
              to="catalog?filters%5Bkind%5D=resource"
              icon={ResourceIcon}
            />
            <SidebarSubmenuItem
              title="Templates"
              to="catalog?filters%5Bkind%5D=template"
              icon={CreateComponentIcon}
            />
            <SidebarDivider />
            <SidebarSubmenuItem
              title="Groups"
              to="catalog?filters%5Bkind%5D=group"
              icon={GroupIcon}
            />
            <SidebarSubmenuItem
              title="Users"
              to="catalog?filters%5Bkind%5D=user"
              icon={UserIcon}
            />
          </SidebarSubmenu>
        </SidebarItem>
```

**Comment by timbonicus** [comment]
Ahh, that makes sense. I didn't make the same functional update to `CatalogKindHeader` in that PR, so that's still needed. I'll take a look at this next week if no one else gets to it.

**Comment by awanlin** [comment]
Thanks @timbonicus, I've been poking around but I'm still at React 101, this feel a lot more advanced then I can tackle right now. No rush, we have this behind a feature flag for now so easy for me to test when a fix does show up 😄

**Comment by awanlin** [comment]
Had some time to look at it closer, between your previous PR and pointing out the `CatalogKindHeader` I've been able to put in a fix for this. When you have time, I know it's hack week, can you take a look at PR #10036, please?
