### ISSUE TITLE
backstage-cli plugin:serve doesn't work when used in a standalone plugin

### ISSUE THREAD

**Issue by blaryjp** [backstage/backstage#8435]
Hello,

I use/develop some plugins in separate GIT repository (so, outside the monorepo).
Everything works well except one CLI command: "plugin:serve".

You can, for example, find a standalone plugin [here](https://github.com/K-Phoen/backstage-plugin-opsgenie).

I looked at the code, and I identified the problem:
The "loadCliConfig" of the command (see [here](https://github.com/backstage/backstage/blob/master/packages/cli/src/commands/plugin/serve.ts#L28-L31)) is called with the parameter "fromPackage: the-name-of-the-plugin". So, in that function, the function "findPackages" is called (see [here](https://github.com/backstage/backstage/blob/master/packages/cli/src/lib/config.ts#L48)) and this throw an error, because it tries to find the package in the Lerna packages. And we don't have any Lerna configuration, because it's a standalone plugin.

## Expected Behavior

The plugins can be served when they are in a separated repository.

## Current Behavior

It throws an error "`Error: Package 'name-of-the-plugin' not found`".

## Possible Solution

I propose 2 solutions. Tell me if one these is correct, or give me an other one maybe, and I'll create a pull-request.

So, in the this file [here](https://github.com/backstage/backstage/blob/master/packages/cli/src/lib/config.ts#L48) :

Solution 1:

```javascript
- const localPackageNames = options.fromPackage ? findPackages(packages, options.fromPackage) : packages.map((p: any) => p.name);
+ const localPackageNames = options.fromPackage ? packages.length ? findPackages(packages, options.fromPackage) : [options.fromPackage] : packages.map((p) => p.name);
```
If we've a "fromPackage", and no "packages.length" from lerna, so takes the "fromPackage" directly.

Solution 2:

```javascript
  const {Project} = require("@lerna/project");
  const project = new Project(index.paths.targetDir);
+ let localPackageNames;
+ if (Object.keys(project.config).length === 0) {
+    localPackageNames = [options.fromPackage];
+  } else {
+   const packages = await project.getPackages();
+   localPackageNames = options.fromPackage ? findPackages(packages, options.fromPackage) : packages.map((p: any) => p.name);
+  }
- const localPackageNames = options.fromPackage ? findPackages(packages, options.fromPackage) : packages.map((p: any) => p.name);
```

Here we test if "project.config" is an empty object. It means that we have not found any Lerna configuration.

## Steps to Reproduce

1. git clone a standalone repo (for example [this one](https://github.com/K-Phoen/backstage-plugin-opsgenie)).
2. yarn install
3. yarn start

## Context

All the developers of standalone plugin outside the monorepo can't launch a standalone website for the plugin.

## Your Environment

- NodeJS Version (v14): NodeJS 14.18.1
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 18.04
- Browser Information: /

**Comment by Rugvip** [comment]
Thank you for reporting! 👍 

I think option 1 is good as it seems a little bit cleaner, and I don't expect it to be very wasteful to do the lerna package lookup

**Comment by freben** [comment]
(But preferably with if/else instead of nested ternaries :))
