### ISSUE TITLE
Error fetching Kubernetes resource: '/apis/batch/v1/cronjobs', error: UNKNOWN_ERROR, status code: 404

### ISSUE THREAD

**Issue by nvadluri** [backstage/backstage#8440]
Hello, I am getting this error on the Kubernetes tab, anything I am missing? below screenshot is my rbac showing the permissions, and the error image. I did modify rbac to clear other errors, but this is still coming. Please suggest me..btw, I can load the cluster details though, but this warning/error coming on the screen and on the logs..

Logs
2021-12-09T22:28:52.716Z kubernetes warn statusCode=404 for resource /apis/batch/v1/cronjobs body=[{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}] type=plugin

Error fetching Kubernetes resource: '/apis/batch/v1/cronjobs', error: UNKNOWN_ERROR, status code: 404

<img width="288" alt="Screen Shot 2021-12-09 at 5 54 48 PM" src="https://user-images.githubusercontent.com/84935639/145488979-5b9bc709-62c6-4bca-9609-46e27e0a3fe5.png">

<img width="1383" alt="Screen Shot 2021-12-09 at 5 54 25 PM" src="https://user-images.githubusercontent.com/84935639/145489017-9ef62fb8-119e-4b67-89b1-61b270a162c6.png">

**Comment by chuliang014** [comment]
I'm also having the same issue.
![image](https://user-images.githubusercontent.com/56138162/145707424-149d94b1-e289-4a80-b217-3d42bb81f825.png)

**Comment by OrkoHunter** [comment]
cc @mclarke47

**Comment by nvadluri** [comment]
@chuliang014  Try this as suggested by Ray, worked for me. 

"ray-ted — 12/10/2021
By default API version is set to v1 for cronjobs, you will need to override that in passing something like this in app-config.yaml

kubernetes:
  apiVersionOverrides:
    cronjobs: 'v1beta1'

**Comment by nvadluri** [comment]
For me, the issue has been fixed with the help Ray's suggestion on Backstage chat. Please close the issue.
<img width="1167" alt="Screen Shot 2021-12-13 at 1 34 27 PM" src="https://user-images.githubusercontent.com/84935639/145868723-ce2152de-acee-4c1a-8d1b-d15cd3452e78.png">


<img width="1323" alt="Screen Shot 2021-12-13 at 1 28 04 PM" src="https://user-images.githubusercontent.com/84935639/145868470-312256c5-0f7c-43fd-8ad2-8b7e1b54b759.png">

**Comment by nvadluri** [comment]
@chuliang014 and also, to fix the other ingress error, keep "networking.k8s.io" in the API groups on RBAC (Please refer the above RBAC image.

**Comment by chuliang014** [comment]
@nvadluri  works like a charm

**Comment by freben** [comment]
Thanks everybody! Closing this for now then.
