### ISSUE TITLE
BuiltinKindsEntityProcessor error

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#8458]
After upgrading the related frontend and backend package about `catalog` and `scaffolder`, I got this error.  And I didn't import any about API catalog, I just imported the kind is `Component`

![image](https://user-images.githubusercontent.com/56138162/145702005-7703b013-86b8-4935-bd94-240c66a011db.png)

**Comment by OrkoHunter** [comment]
Hi @chuliang014 ! Looks like you are ingesting an entity via `app-config.yaml` using the `catalog.locations` property. And you have a rule only allowing `API` kinds.

Can you make sure that you have an `allow` property like this[1] in your `catalog.rules` config, which allows kinds other than `API`?

https://github.com/backstage/backstage/blob/a3ec122170e0205fd3f9c307b98b1c5e4f55bf5f/app-config.yaml#L184-L195

**Comment by chuliang014** [comment]
Hey @OrkoHunter. I've allowed these values.
![image](https://user-images.githubusercontent.com/56138162/145703208-3b124b3d-e25e-4ed2-9506-44cb2c843bac.png)

**Comment by chuliang014** [comment]
@OrkoHunter fixed the issue after delete `node_modules` and `yarn install`

**Comment by joslat** [comment]
Hi, I am having the same issue, trying to get a component that dependsOn: another component and the app-config is good:
`catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]`
    
 tried the deletion of the `node_modules` folder followed by reinstalling yarn, same happens..
