### ISSUE TITLE
Customized Components dropdown button

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#8459]
Hi, 

I'm wondering if we can customized the `Components` dropdown button in service catalog like just keep only `Component` and `Template`.

![image](https://user-images.githubusercontent.com/56138162/145707245-de05008d-b835-4ce9-83f9-ddc81993bf69.png)

**Comment by timbonicus** [comment]
At the moment this fetches all available kinds from the catalog and doesn't have any way to customize it. To support that, I can imagine adding `allowedKinds` to CatalogKindHeader and filtering the kinds from this list [around here](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogKindHeader/CatalogKindHeader.tsx#L73). That would still require [catalog customization](https://backstage.io/docs/features/software-catalog/catalog-customization) to pass in; some related discussion about making this easier [here](https://github.com/backstage/backstage/issues/8336#issuecomment-988326697).
