### ISSUE TITLE
Extend the "SeachQuery" interface

### ISSUE THREAD

**Issue by camilaibs** [backstage/backstage#8468]
## Feature Suggestion

We don't have a recommended property in the `SearchQuery` interface for sort results clauses, for example, an object of type `{ column: false, direction: 'asc' }` and it can be different according to the Search API Implementation we may be using. Same for **pagination**, today we have only a `pageCursor` property to store the current page number, but what if you want to specify the number of results as a limit in your query?

## Possible Implementation

We can write our own extended `SearchProvider` to call the Search API with more parameters, missing the zero-configuration experience we have today, or we can use the generic JSON object for filters, though I'm not sure sorting and filters are conceptually the same things. I would recommend adding a JSON object to sort in the `SearchQuery` interface or adding something like extra fields for things like complex pagination as well.

## Context

I want to extend the query object with specific search parameters that my search API implementation supports.

**Comment by soapraj** [comment]
Looks like there is some need for configuring search properties like pageSize, sort order that provides a consistent UX across engines - https://github.com/backstage/backstage/issues/9162

**Comment by camilaibs** [comment]
The following issue seems related to this one: https://github.com/backstage/backstage/issues/13597/.

**Comment by iamEAP** [comment]
Also linking https://github.com/backstage/backstage/issues/9162 from a page size perspective
