### ISSUE TITLE
SideMenu taking space on small screens

### ISSUE THREAD

**Issue by sachin-kumar-ik8** [backstage/backstage#8471]
Side navigation bar is taking space on small screen device. User can toggle the side menu from settings page but can we make it default toggle hide?

## Expected Behavior
To collapse sidebar by default.

## Current Behavior
Have to go to settings page to collapse it.

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by timbonicus** [comment]
Perhaps #6905 is the right solution here 🙂

**Comment by sachin-kumar-ik8** [comment]
Thanks. Are we planning to merge this PR?

**Comment by tudi2d** [comment]
Yes - but this tackles mobile screen sizes. Otherwise #7521 added `<Sidebar disableExpandOnHover>` - not sure if this is more what you are aiming for here :)
