### ISSUE TITLE
Use <SearchBar /> in the Sidebar

### ISSUE THREAD

**Issue by camilaibs** [backstage/backstage#8483]
## Feature Suggestion

I noticed that we are using a `<TextField />` for search, in the sidebar, and I wonder if it would be better to use `<SearchBar />` instead, considering it as the recommended input component for search, avoiding having multiple implementations for the same purpose. One advantage of this is that you can set a debounce time and no configuration is required to use the defined search implementation.

https://github.com/backstage/backstage/blob/842e338efbff8481391a6bdfab42638aac8a1e50/packages/core-components/src/layout/Sidebar/Items.tsx#L531

## Possible Implementation

We may need to change `SearchBar` first to accept all the properties that the `TextField` accepts today before doing the component swap.

## Context

Want to avoid multiple implementations of the same component and use Backstage Design System components as much as possible.

**Comment by camilaibs** [comment]
Same for the Search Modal, should we use `<SearchBar />` there too?
https://github.com/backstage/backstage/blob/master/plugins/search/src/components/SearchModal/SearchModal.tsx#L101

**Comment by freben** [comment]
Sounds sensible. But maybe it'll need some prop like `dense` or similar, that makes sure that its padding/other sizes aren't overly large, and that it doesn't have too many extra input adornments etc that fit well in the large use case but not so much in the small sidebar?

**Comment by camilaibs** [comment]
> Sounds sensible. But maybe it'll need some prop like `dense` or similar, that makes sure that its padding/other sizes aren't overly large, and that it doesn't have too many extra input adornments etc that fit well in the large use case but not so much in the small sidebar?

I agree with you regarding the sidebar, thanks for pointing that.

It really doesn't seem right that the core component package has dependencies on plugin components. The opposite seems more suitable, for example, if we had a default Search Input in the core package, we could use it as the basis for the search box components in the search plugin.

But SearchBarField doesn't seem to have the purpose of being a search input to be used as a base, because it is coupled with a style that is specific to the sidebar. That's why I agree with you.

The search boxes in the search plugin, on the other hand, have the same purpose and repeat properties and behaviors already defined in the base input of the Search Bar or which can be moved and reused from it.

I created a pull request draft [here](https://github.com/backstage/backstage/pull/8532) so you can see the idea regarding the search plugin components, I'll be happy to receive your review.

**Comment by camilaibs** [comment]
Closed here:

https://github.com/backstage/backstage/pull/8532
