### ISSUE TITLE
backstage-cli bundling creates nested bundle.tar.gz when there's no plugins

### ISSUE THREAD

**Issue by plektra** [backstage/backstage#8501]
## Expected Behavior

When building the bundle without plugins folder available (there aren't any plugins), using backstage-cli to build the bundle, should create bundle.tar.gz with all bundled files within the gzip file. Following command is used for building the bundle:

yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies

## Current Behavior

The file bundle.tar.gz contains the same bundle.tar.gz in folder packages/backend/dist (within the gzip archive) while it should contain the extracted files. To work around this issue, the nested bundle.tar.gz must be extracted again in the application root folder.

## Possible Solution

The produced bundle.tar.gz should not create another bundle.tar.gz inside itself, but instead have the same file and folder structure as if the bundle was built with plugins enabled.

## Steps to Reproduce

1. Remove all plugins from the code
2. Remove plugins folder
3. yarn install --frozen-lockfile
4. yarn tsc
5. yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies
6. Open/extract packages/backend/dist/bundle.tar.gz
7. Notice that in the extracted packages/backend/dist folder there's bundle.tar.gz again

## Context

The issue affects the build pipeline. As a workaround, there needs to be an additional extraction of the bundle.tar.gz only in case if there aren't any plugins yet installed/enabled. If plugins are enabled, the bundle doesn't have any issues, content isn't "double-zipped".

Here's the listing of the extracted, problematic bundle.tar.gz:
```
$ ls -R 
package.json    packages        yarn.lock

./packages:
backend

./packages/backend:
dist         package.json

./packages/backend/dist:
bundle.tar.gz   skeleton.tar.gz
```

## Your Environment

The affected environment doesn't have any plugins enabled or installed.

- NodeJS Version (v14): v14.18.2
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS, node-14-buster docker image
- Browser Information: not relevant

**Comment by Rugvip** [comment]
Thank you for reporting!

What version of the cli are you on? This might've been fixed by https://github.com/backstage/backstage/pull/8041

**Comment by plektra** [comment]
Hi, the version of backstage-cli I'm using is 0.7.14.
