### ISSUE TITLE
Disable/Enable Scaffolder NEXT STEP Button

### ISSUE THREAD

**Issue by sharadpattanshetti** [backstage/backstage#8502]
![image](https://user-images.githubusercontent.com/43475650/146227417-f44dfe1e-82f3-4e51-adec-9cd0d2c1f8e6.png)

Hi, 
Is it possible to control enabling/disabling the NEXT STEP Button in Scaffolder Page based on user inputs to the fields?

**Comment by freben** [comment]
Not sure if this is supported out of the box in rjsf - do you mean that you want to control this based on schema validity of the current page's data, or something else?

Either way I think this might mean needing some implementation work if it were to become supported. Is this something you might be interested in looking into?

**Comment by razbensimon** [comment]
Opening this one again 🙏🏼 
is this possible in 2024?
We have a step with a custom UI component, while fetching data (loading) we should not allow the user to proceed to next step. 

is it possible to control it?
