### ISSUE TITLE
Database - Postgres connection string issue

### ISSUE THREAD

**Issue by lucasvieirazup** [backstage/backstage#8518]
## Expected Behavior

Hello guys,

I got some error with **connection string**, if i wont use my build working good. I want to use RDS with it, soo i have had no option to use locally.

```
  database:
    client: pg
    connection: postgresql://xxx:xx@postgres.xxxxx.sa-east-1.rds.amazonaws.com:5432/postgres
      # I tried with this in connection too: postgresql://postgresql://xxx:xx@postgres.xxxxx.sa-east-1.rds.amazonaws.com:5432/postgres?ssl=true&sslmode=require&sslrootcert=/opt/backstage/rds-combined-ca-bundle.pem'
      host: postgres.xxxxxx.sa-east-1.rds.amazonaws.com
      port: 5432
      user: xxxxx
      password: xxxx
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      ssl: true
        ca: # if you have a CA file and want to verify it you can uncomment this section
          $file: /opt/backstage/rds-combined-ca-bundle.pem
```
## Current Behavior
I got this error when i tried to build, if i wont use connection string i'll build successfully.
```
yarn build
yarn run v1.22.17
$ lerna run build
lerna notice cli v4.0.0
lerna info Executing command in 2 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in 'app'
lerna ERR! yarn run build stdout:
$ backstage-cli app:build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:

YAMLSyntaxError: Failed to read static configuration file; caused by YAMLSyntaxError: All collection items must start at the same column

error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in 'app'
error Command failed with exit code 1.
```

## Your Environment

- NodeJS Version (v14):
- Amazon Linux 2:
- Browser Information:

**Comment by jhaals** [comment]
Looks like that's some yaml syntax error in the file, strings containing colon `:` must be quoted.

**Comment by adamdmharvey** [comment]
Indeed a YAML issue.

I've not set up Backstage with RDS to be fair, but I'd also not expect anything to be after the `connection:` key ?  (meaning no string value, the values are sub-elements on the subsequent lines?)  I wasn't aware if this code supported connection strings, and instead is designed to support explicitly named host, port, then password?

The setup instructions are here:
https://backstage.io/docs/tutorials/switching-sqlite-postgres#add-postgresql-configuration

And if you find something else worked, they could always use contribution/tweaks/improvements as well.

**Comment by lucasvieirazup** [comment]
i got CA and key in different lines in yaml, now is ok, thank you all.
