### ISSUE TITLE
Allow entities from non-url locations to be refreshed in the UI

### ISSUE THREAD

**Issue by cooperbenson-qz** [backstage/backstage#8525]
## Feature Suggestion

I would love to be able to refresh entities that come from sources other than the `url` processor, particularly the `file` processor

## Possible Implementation

As best as I can tell this is solely a frontend limitation, although I am new to this codebase and might be missing something. If there is no backend reason to forbid this for all processors, it should be as simple as removing or expanding [this check](https://github.com/backstage/backstage/blob/38d6df6bb9ecdce798ea9033f5b68490dcfe9823/plugins/catalog/src/components/AboutCard/AboutCard.tsx#L130-L131).

## Context

I'm using the `file` location to provide entities during local development, but I currently have to restart the entire backend any time I want to see the results of a change to an entity (i.e. changing annotations on a `Component`).  Having the ability to refresh the component directly would save me a ton of time

**Comment by Rugvip** [comment]
We added file watching of the app configuration not too long ago, so that additions to `catalog.locations` are picked up automatically during local development. Once refreshes have worked their way into the catalog providers I'm thinking we may tackle this by providing file watching of `file` locations as well

**Comment by cooperbenson-qz** [comment]
It seems like refreshing is already part of the catalog API considering it works for `url` entities. What I'm wondering is why this is limited to just the `UrlReaderProcessor` and what is required to extend it to other processors

**Comment by Rugvip** [comment]
Ah, the frontend check is actually just there to avoid triggering very expensive refreshes too often. In practice it should be possible to refresh any type of location. Tbh I think it would be fine to expand the check to include `file` locations as well, not seeing any big problem with that as it's already allowed via the API anyway. Assuming it all works as intended that is :grin:
