### ISSUE TITLE
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#8535]
I extended catalog table with custom field. I noticed this error from past few days. on troubleshot, if i remove following code
from columns.tsx in my custom component.
```
<OverflowTooltip
        text={entity.metadata.description}
        placement="bottom-start"
      />
```
it works perfectly without tooltip. 
![Screen Shot 2021-12-17 at 9 17 54 AM](https://user-images.githubusercontent.com/225961/146557928-8a8391d5-2998-49e7-9db1-98683867513f.png)

**Comment by freben** [comment]
Alright, thanks for reporting - fixed in https://github.com/backstage/backstage/pull/8563
