### ISSUE TITLE
Backstage Github Auth reporting: Login failed; caused by Error: Authentication failed, Failed to obtain access token

### ISSUE THREAD

**Issue by hsparmar1** [backstage/backstage#8543]
Hi team: Hoping you can help. I am trying to use an on-prem Enterprise Github instance for authentication.  I am having some difficult after creating the OAuth application in Github. I have followed all the direction on the Backstage documenation site for using Github authentication (along with making the edits to the login page). On the 'localhost:3000' sign-in page, when I click 'Sign In', I get the following error: "Login failed; caused by Error: Authentication failed, Failed to obtain access token". 

Here is my configuration in app-config.yaml: 

auth:
  environment: development
  providers:
    github:
      development:
        clientId: XXXXX
        clientSecret: XXXXX
        enterpriseInstanceURL: https://some.agency.gov/

When I check Github, I can see that I user token has been issued. In the backend logs, I can see that "code" has been received, and I can use that code in a cURL command to get the access token from our Github repo; however, I cannot seem to fix the above error in Backstage. Any advice would be greatly appreciated.

Last thing: When I try outside the boundary of our organization using my personal Github account (going against the default "github.com"), with an another OAuth application I defined in my personal Github account, and finally, without the use of enterpriseInstanceURL, it works just fine.

**Comment by hsparmar1** [comment]
After writing out some logs, I discovered that the error is related to 

"Failed to obtain access token: Error: unable to get local issuer certificate ... code: UNABLE_TO_GET_ISSUER_CERT_LOCALLY"

Tried a bunch of stuff that I saw on the web including: 

1. Passing the Root CA / certificate chain using NODE_EXTRA_CA_CERTS=${CERT-FILE}

2. --use-openssl-ca option to node

I am disinclined to set "strict-ssl" to false, and am temporarily using the NODE_TLS_REJECT_UNAUTHORIZED=0.  Is there a better recommended solution?

**Comment by hsparmar1** [comment]
Hi Adam,

Thanks for the feedback. I did see note, or something similar. I tried exporting this variable into my profile; I also tried invoking command like: `NODE_EXTRA_CA_CERTS=${PATH_TO_PEM_FILE}`. Unfortunately, neither seemed to work for me.

Will keep trying without making changes to the code base.

**Comment by adamdmharvey** [comment]
Oh duh!! `/smackshead` Ha sorry, see you tried that one. Yeah nothing pops off the top of my head; but def think you're on the right track. The root CA you provided isn't a public one, i.e. you selected some sort of internal one that is likely custom to your org?

Maybe others have ideas!!!

**Comment by hsparmar1** [comment]
Hi Adam: Definitely have the PIV keychain exported in PEM format in the following order: Root Cert > Intermediate Certs > User Cert. Also tried the order in reverse (don't know why, but at the time was short of options) :). Having the Git folk at the agency track the request, but a token is exchanged, so its definitely an issue on the way back to our enterprise Github to get the bearer token. Let's see what they say; maybe they can shed some light on this issue. Will keep the folks updated.

**Comment by hsparmar1** [comment]
Hi team. Apologies for the late reply. I heard back from our Git folks, and they mentioned that the issue was related to not having the "full" git cert chain in our CA store. I added the one the recommended, and the issue resolved itself. Thanks for the help!

**Comment by gyan9427** [comment]
hi , after working with the setup for a whole day when i tried to login in backstage in my local setup I started getting this error

{
    "error": {
        "name": "AuthenticationError",
        "message": "Refresh failed; caused by Error: unable to get local issuer certificate",
        "cause": {
            "name": "InternalOAuthError",
            "message": "Failed to fetch user profile",
            "oauthError": {
                "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY",
                "name": "Error",
                "message": "unable to get local issuer certificate",
                "stack": "Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)\n    at TLSSocket.emit (node:events:524:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1076:8)\n    at ssl.onhandshakedone (node:_tls_wrap:862:12)"
            },
            "stack": "InternalOAuthError: Failed to fetch user profile\n    at /home/gyan/backstage-works/backstage-v2/back-app/node_modules/passport-github2/lib/strategy.js:98:19\n    at ClientRequest.<anonymous> (/home/gyan/backstage-works/backstage-v2/back-app/node_modules/oauth/lib/oauth2.js:166:7)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
        },
        "stack": "AuthenticationError: Refresh failed; caused by Error: unable to get local issuer certificate\n    at Object.refresh (/home/gyan/backstage-works/backstage-v2/back-app/node_modules/@backstage/plugin-auth-node/src/oauth/createOAuthRouteHandlers.ts:361:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async OAuthEnvironmentHandler.refresh (/home/gyan/backstage-works/backstage-v2/back-app/node_modules/@backstage/plugin-auth-node/src/oauth/OAuthEnvironmentHandler.ts:60:5)"
    },
    "request": {
        "method": "GET",
        "url": "/github/refresh?optional&scope=read%3Auser&env=development"
    },
    "response": {
        "statusCode": 401
    }
}


despite of doing all the aforementioned settings still i am getting this error, can some one state the exact reason behind it?
