### ISSUE TITLE
Remove non-`fetch` http libraries

### ISSUE THREAD

**Issue by freben** [backstage/backstage#8553]
There are some remaining usages of `axios` and `got` (and more?) in the project. These should be removed, and replaced with `fetch`.

In backend packages, the `node-fetch` library should be used.

In frontend and isomorphic packages, the `cross-fetch` library should be used.

**Comment by jhaals** [comment]
These packages need fixing:
- [ ] `@backstage/plugin-auth-backend` usage of `got`
- [ ] `@backstage/plugin` usage of `axios`

Created ADR #8560

**Comment by julioz** [comment]
Can we somehow prevent new usages of non-`fetch`? Maybe a lint rule of sorts?

**Comment by jhaals** [comment]
> Can we somehow prevent new usages of non-`fetch`? Maybe a lint rule of sorts?

Yes, we'll most likely add that once the plugins have been migrated.
