### ISSUE TITLE
[Urgent]undefined (reading 'userEntityRef')

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#8556]
Hi,

I got undefined error(reading 'userEntityRef') in 3 pages.`settings`,`pagerduty` and  `cost insights`. It felt like all these pages need to read userID
![image](https://user-images.githubusercontent.com/56138162/146864055-11d161f5-2222-49d0-a137-55b78e4886b9.png)

**Comment by chuliang014** [comment]
I've updated my `users-setting` and `auth-backend` plugin to latest version, but not work

**Comment by chuliang014** [comment]
It seems this problem has been solved, but not released. https://github.com/backstage/backstage/pull/8526

**Comment by adamdmharvey** [comment]
That's batched up for the next release: https://github.com/backstage/backstage/pull/8514

The maintainers are on holiday until 3 January, so I believe they'll likely kick the next release the first week of the New Year.

**Comment by Rugvip** [comment]
As long as no major blocker shows up we'll have a release as usual this Thursday! 😁

**Comment by chuliang014** [comment]
@adamdmharvey @Rugvip Thanks for your information.

**Comment by benjdlambert** [comment]
@chuliang014 this has been released now, so think that you can do a `yarn backstage-cli versions:bump` and it should work. Going to close this now, and re-open if you have any other issues or it's not working as expected! 👍
