### ISSUE TITLE
Extra empty rows in grid

### ISSUE THREAD

**Issue by sachin-kumar-ik8** [backstage/backstage#8558]
There are so many extra empty rows added inside the grid which makes the page scrollable and also move down the pagination controls.

## Expected Behavior

Should add rows for available data.

## Current Behavior

Inspect the backstage demo official site grid in docs page -> https://demo.backstage.io/docs?filters%5Buser%5D=all
<img width="1303" alt="Screenshot 2021-12-21 at 10 44 40 AM" src="https://user-images.githubusercontent.com/79145678/146875142-4bbeaf2d-e2f7-4608-b119-0f8e7b397428.png">

There is only one data so first row has content in it but rest other<tr> are empty and taking 49px height each.
## Steps to Reproduce
Inspect grid on this page https://demo.backstage.io/docs?filters%5Buser%5D=all

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by mufaddal7** [comment]
The empty rows are rendered by material-ui automatically as the default number of rows in the above screenshot is set as **20** 

![image](https://user-images.githubusercontent.com/42934221/147209688-522b5fe5-e841-4358-9769-0d3c9abe5d9c.png)

**Comment by sachin-kumar-ik8** [comment]
yes then in that case how to set the default page size? is there any option to pass it in props? @mufaddal7

**Comment by cmpadden** [comment]
@sachin-kumar-ik8 as far as I can tell, it is not possible to override the `options` prop of the docs table which sets `pageSize` to 20.

https://github.com/backstage/backstage/blob/04da4ec45c87b794ac82101ddf1d44f6a9c77794/plugins/techdocs/src/home/components/DocsTable.tsx#L93-L101

If you'd like to change this value, I suspect you could add an options prop, similar to the `columns` and `actions` props of the `DefaultTechDocsHome` component which get passed along to `EntityListDocsTable` and ultimately `DocsTable`.
