### ISSUE TITLE
Add system level view to catalog graph plugin

### ISSUE THREAD

**Issue by niallmccullagh** [backstage/backstage#8591]
## Feature Suggestion

The catalog-graph plugin is great for visualising between entities but it can be hard to visualise those dependencies at a higher level. 

![system-relationships](https://user-images.githubusercontent.com/1196581/147120801-ba1ecc66-381f-4ab9-938a-0afc1219dfb9.png)

## Possible Implementation

* This could be built into the catalog-graph plugin exposed as another UI component.
* Clicking on a node would bring to that system's entity page
* Hovering over the relationship line could show more details on what the underlying relationships are
* Users could decide to place in a tab in explore plugin
* It could also be adapted to show other higher level groupings like domain/group relationships.

**Comment by freben** [comment]
So it would essentially round up the relations of underlying components/apis/resources, and show the union of them as a single edge basically? Sure, that might be a good fit as one more component in the catalog-graph plugin. Sounds like there might be some interesting possibilities in how to visualize the edges based on how much or in what ways they are connected to each other etc. Is this something that you would like to work on?

**Comment by niallmccullagh** [comment]
Hey @freben, it was on my radar to do over the holidays but I have had a chance to get back to it. I'm still keen but struggling to set some time aside for it at the moment.

**Comment by freben** [comment]
No worries!
