### ISSUE TITLE
Built in catalog:register action completes before the component is accessible via the catalog API

### ISSUE THREAD

**Issue by ConnorDY** [backstage/backstage#8597]
## Expected Behavior

Any custom Backstage actions that rely on the component already being registered should work immediately after the register component action finishes.

## Current Behavior

The built-in `catalog:register` action completes, and the next action after it runs before the component is accessible via the entity API. If the action after it hits the catalog API for that component, it will return a `Couldn't find entity with name: ...` error.

## Possible Solution

Ensure the `catalog:register` action does not complete until the component is accessible via the catalog API.

## Steps to Reproduce

1. Create a custom action that calls the `/api/catalog/entities/by-name/component/default/{component-name}` endpoint.
2. Add the custom action as a step that runs directly after the `catalog:register` action in a template.
3. Try using the template.

## Context

We have had to add a delay to our custom action of 1 second, but the entity API still returns a not found error sometimes. Increasing the delay seems like a poor solution.

## Your Environment

```
OS:   Darwin 20.6.0 - darwin/x64
node: v14.18.1
yarn: 1.22.17
cli:  0.10.2 (installed)
```

**Comment by Rugvip** [comment]
I think perhaps the best way to solve this would be if the catalog registration endpoint blocks until it is "done", whatever that means :grin: It pretty gets hairy pretty quickly though, as we don't know upfront what entities to expect from a particular location. It means we'd likely need to design some sort of wait mechanism in the catalog processing, or switch over all processing of added locations to be done eagerly and then submit the resulting batch of entities straight into the catalog output flow.

A workaround in the meantime could be a simple custom action that waits for a specific entity to existing in the catalog, probably along with a timeout. That way you can add an explicit wait, but it requires manual configuration
