### ISSUE TITLE
get rid of root inline styles

### ISSUE THREAD

**Issue by freben** [backstage/backstage#8600]
## Feature Suggestion

The default index.html has just two "inline" styles. This has led to some confusion in terms of CSP (see Context) it seems. I am not even sure that they are needed at all. They should be moved out or deleted, I think.

## Possible Implementation

Make a single small corresponding CSS file among the static files, which index.html references? Or remove the styles, after thoroughly checking in the major browsers (perhaps even on mobile?) that they indeed are unnecessary.

## Context

https://discord.com/channels/687207715902193673/687207715902193679/922539757475606629

![image](https://user-images.githubusercontent.com/3097461/147156618-aef2b115-28ef-4b7a-ba4b-a7af144f97aa.png)

**Comment by Rugvip** [comment]
Fixed by #8606
