### ISSUE TITLE
can filter out more projects in gitlab discovery

### ISSUE THREAD

**Issue by zhammer** [backstage/backstage#8623]
this is a very minor potential improvement to gitlab discovery, but i noticed when running gitlab discovery that backstage filters out "archived" projects but not "empty repo" projects (see: https://gitlab.com/gitlab-org/gitlab/-/issues/3800). these projects don't have a repository and thus don't have a default branch, though discovery assumes `project.default_branch` to exist and attempts to fetch a catalog file, erroring with:

```
catalog warn Unable to read url, Error: https://[gitlab-host]/[group]/[project]/-/blob/undefined/catalog-info.yaml could not be read as https://[gitlab-host]/api/v4/projects/[project-id]/repository/files/catalog-info.yaml/raw?ref=undefined, 403 Forbidden
```

not a huge deal but the warn logs are confusing: "why are we trying to discover from `?ref=undefined`?" on a gitlab instance with a lot of empty repo projects, discovery could save some time by filtering these out up front.

it seems a decent way to do this is filter out `project.empty_repo === true`, though this [isn't yet documented in their API](https://gitlab.com/gitlab-org/gitlab/-/issues/32694). we could also filter where `project.default_branch === undefined`.

https://github.com/backstage/backstage/blob/5284458e18f7da3bc0ba5eb8043e902108518726/plugins/catalog-backend/src/ingestion/processors/GitLabDiscoveryProcessor.ts#L97-L99

just wanted to flag! happy to put up a PR if desired.

**Comment by zhammer** [comment]
ah apologies, clicking "reference in new issue" on that code block didn't pull up the issue template. happy to re-format if folks prefer.

**Comment by Rugvip** [comment]
Thank you for reporting! I think the `default_branch === undefined` check makes sense if that's the only documented way to check it. No worries about the template

**Comment by zhammer** [comment]
yep, that makes sense. if i have some time this week i may put up a PR. wouldn’t mind getting in the habit of it :)
