### ISSUE TITLE
RouteRef is not assignable to type never

### ISSUE THREAD

**Issue by lqlamTMA** [backstage/backstage#8638]
I installed plugin catalog-graph (refer: https://github.com/backstage/backstage/blob/master/plugins/catalog-graph/README.md) and I have got an issue with the code lines below
`
bind(catalogGraphPlugin.externalRoutes, {
      catalogEntity:  catalogPlugin.routes.catalogEntity ,
 });
`
![image](https://user-images.githubusercontent.com/29789620/147389085-99a06e0a-275e-4507-9750-d290ba8fd3ab.png)
![image](https://user-images.githubusercontent.com/29789620/147389093-4ed2c77c-20d7-4a38-a159-de7bd6f43c07.png)

**Comment by Rugvip** [comment]
Is the rest of your Backstage app up to date? It possible there could be issues with installing a new plugin into an older app. I'd also double check the `catalogGraphPlugin` and `catalogPlugin` imports, and perhaps check the type of `catalogGraphPlugin.externalRoutes`, it should look something like this:

![image](https://user-images.githubusercontent.com/4984472/147488042-a478bc43-371d-4e8e-ba4f-272cc972b12b.png)

**Comment by ryharrin** [comment]
I ran into this same issue. I ran `backstage-cli versions:bump` and it fixed it. Not sure which of these packages it was:

bumping @backstage/plugin-search-backend in backend to ^0.3.0
bumping @backstage/backend-common in backend to ^0.10.0
bumping @backstage/test-utils in app to ^0.2.0
bumping @backstage/plugin-tech-radar in app to ^0.5.0
bumping @backstage/core-app-api in app to ^0.3.0
bumping @backstage/core-plugin-api in app to ^0.4.0
