### ISSUE TITLE
[RFC] Get a Provider Bearer Token from Backstage

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#8654]
**Status:** Open for comments

## Need

We need to be able to fetch the catalog data via API from other microservices and cloud scripts. We use Okta authentication therefore backstage is issuing a token for the logged in user. This is fine if the user is logged in via the sign in page from the portal and after that, we can use the catalog API to fetch the entities without a problem.

However, if the API is accessed from another microservice or script the request is not authorized.

So far, I was unable to find an appropriate endpoint that will issue a token for the given provider based on the clientid and secret from within the backstage APIs.

Is there a way to achieve this in backstage or do we need to get the token from Okta API and pass it down to the backstage request that we want to access/authorize?

**Comment by Rugvip** [comment]
This has begun being introduced in #7943, although it's not at the point of issuing tokens for external services yet. A stop-gap could be a simple utility that is able to generate a key in the same way as the `ServerTokenManager` does

**Comment by ProticM** [comment]
Thanks @Rugvip 

I'm aware of the change and we have the API protected with `ServerTokenManager.fromConfig` with some weak string until the change you are making settles.

I opened this issue to find out if there is a way to achieve what I need without adding utilities or customizations because I could not find anything in the backstage source code that proves it possible. Thank you for the quick answer 👍 

So for now, it is either that we need to use `ServerTokenManager.noop` or create something like a utility/custom API endpoint to issue a token, and in the upcoming releases, we will have this integrated into the core? Is this a correct assumption?

**Comment by Rugvip** [comment]
@ProticM yep something custom for now. If you make it an endpoint then you ofc wanna make sure that's protected in some way. We'll definitely want to provide a solution for this long term but no plans yet, happy to discuss the way forward in this issue.

And correct, this does not relate to any of the auth providers as those are all for individual user authentication. The service-to-service auth is a parallel track that lives alongside the user auth system, although they ofc intersect that the point of protecting backends and some other places.

**Comment by ProticM** [comment]
@Rugvip Yes, our instance is behind Cloudflare so we should be good 😸 

To clarify, I was thinking about having something exposed from backstage to be used by external systems to fetch the token/key and that resulting token/key to be used as an authorization in any further requests towards our backstage instance.

I was not thinking of having a utility to create a key outside of backstage, but it is worth considering that approach. When you say `utility`, did you have something like this in mind, outside of backstage?

**Comment by Rugvip** [comment]
What I had in mind was just a simple Node script or something of that sort, where you provide the secret and it hands you back a key that can then be configured in your external services.

**Comment by ProticM** [comment]
Yes, I assumed something like that based on your comments thus I asked just to be on the same page 👍

**Comment by ProticM** [comment]
I guess I'm trying to understand how the custom generated key/token (based on our secret in the config `auth.keys` section), unrelated to the provider, will bypass the Okta sign-in protection that we have in place, without the Okta token 🤔 

This is what the `ServerTokenManager` generates, to my understanding, and if that is the only thing we provide from an external system, I assume it will not be enough because of the Okta sign-in in place.

**Comment by Rugvip** [comment]
@ProticM It won't, you'll need to update your middleware to allow backend tokens through as well. Wanna emphasize again that deploying behind a reverse proxy or some other form of perimeter is the only way of protecting a Backstage instance the we recommend right now, as the authenticating middleware isn't something we're officially supporting.

The current use-case for backend authentication is for use with the permission plugin only, although you can bend it to protect the backend as well, that's not something we support out of the box. It likely will be built into the core in the future, but we're not there yet. But more context over here as well https://github.com/backstage/backstage/pull/7943#discussion_r755054836

**Comment by ProticM** [comment]
@Rugvip Yes, thanks for clearing it out. I can add here once more that we have it deployed behind Cloudflare

**Comment by Rugvip** [comment]
@ProticM ah are you looking into having external services get through cloudflare and reach your instance?

**Comment by ProticM** [comment]
@Rugvip Yes, this is the case that I'm looking into

I was trying to get the info is it possible to get the required token from backstage directly somehow, from the external service, since we already passed down okta client id and secret via config.

I did not find something like this in the source code. 

But the main goal here is to find the best approach to get through the cloudflare and I'm looking into the posibilities

**Comment by Rugvip** [comment]
@ProticM ah alright, that's really gonna be up to cloudflare/okta then tbh and not something we can handle in Backstage. Typically it'd be called "service account" or something or something like that, perhaps this? https://developers.cloudflare.com/cloudflare-one/identity/service-auth/service-tokens

**Comment by ProticM** [comment]
@Rugvip Yes, this is expected, but nice to have it confirmed. I was investigating, more or less, the `usual` flow where the service you want to access gives you the access token.

As for me, we can close this RFC
