### ISSUE TITLE
@backstage/plugin-kubernetes throws when pod limits are unset

### ISSUE THREAD

**Issue by esphen** [backstage/backstage#8671]
## Expected Behavior

When opening the "Deployment" pulldown in the kubernetes window of a component it should show pods related to the deployment.

## Current Behavior

When clicking a deployment which contains a pod that does not have any memory limits set the component throws due to a divide by zero in `currentToDeclaredResourceToPerc` invoked from `PodsTable` via `podStatusToMemoryUtil`.

## Possible Solution

Handle a potential zero in `metrics.memory.limitTotal` and `metrics.memory.requestTotal` by showing raw memory usage in the table instead of throwing when trying to calculate a percentage usage of the set memory limit. For example by introducing a new line invoking an early exit before the return in `podStatusToMemoryUtil` along the lines of:
```js
if (!memUtil.limitTotal || !memUtil.requestTotal) {
  // TODO: Verify correct division
  return `usage: ${memUtil.currentUsage / 1000000} MB`;
}
```

## Steps to Reproduce

1. Replace `memUtil`'s return in `podStatusToMemoryUtil` with a hard coded `{ currentUsage: "122798080", limitTotal: 0, requestTotal: 0 }`
2. Navigate to a component with kubernetes configured
3. Open a deployment
4. A crash is rendered in the plugin's ErrorBoundary

## Context

Screenshot of the issue after clicking a deployment:
![bilde](https://user-images.githubusercontent.com/5845924/147645903-832e0e7e-bfb0-429e-a646-6bb949440dcd.png)

Screenshot of the issue in the debugger. Notice `denominator` is zero triggering a divide by zero exception:
![2021-12-29-094636_1109x609_scrot](https://user-images.githubusercontent.com/5845924/147644008-4e1adf6a-6a9c-4be3-bd35-0a4f86e0b51c.png)

Invoked from:
![2021-12-29-094719_1633x588_scrot](https://user-images.githubusercontent.com/5845924/147644005-3caa922d-f991-4bfd-87f9-fae9db59545e.png)

Related: After adding a limitrange for memory it loads but CPU shows `requests: Infinity%, limits: Infinity%`. I have also made it show `NaN`, but have been unable to reproduce that lately. Probably a related issue that could be solved at the same time

## Your Environment

- NodeJS Version (v14): v16.9.1
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 20.04.3 LTS (Focal Fossa)
- Browser Information: Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0

```
  @backstage/app-defaults                                  0.1.3
  @backstage/backend-common                                0.10.0
  @backstage/catalog-client                                0.5.3
  @backstage/catalog-model                                 0.9.8
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.10.3
  @backstage/config-loader                                 0.9.0
  @backstage/config                                        0.1.11
  @backstage/core-app-api                                  0.3.0
  @backstage/core-components                               0.8.2
  @backstage/core-plugin-api                               0.4.0
  @backstage/errors                                        0.1.5
  @backstage/integration-react                             0.1.16
  @backstage/integration                                   0.6.10
  @backstage/plugin-api-docs                               0.6.19
  @backstage/plugin-app-backend                            0.3.20
  @backstage/plugin-auth-backend                           0.5.2
  @backstage/plugin-catalog-backend                        0.19.3
  @backstage/plugin-catalog-import                         0.7.6
  @backstage/plugin-catalog-react                          0.6.8
  @backstage/plugin-catalog                                0.7.5
  @backstage/plugin-github-actions                         0.4.28
  @backstage/plugin-kubernetes-backend                     0.4.1
  @backstage/plugin-kubernetes-common                      0.2.0
  @backstage/plugin-kubernetes                             0.5.2
  @backstage/plugin-org                                    0.3.32
  @backstage/plugin-permission-common                      0.3.0
  @backstage/plugin-permission-react                       0.2.0
  @backstage/plugin-proxy-backend                          0.2.15
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.6
  @backstage/plugin-scaffolder-backend                     0.15.18
  @backstage/plugin-scaffolder-common                      0.1.1
  @backstage/plugin-scaffolder                             0.11.15
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.3.0
  @backstage/plugin-search                                 0.5.2
  @backstage/plugin-tech-radar                             0.5.0
  @backstage/plugin-techdocs-backend                       0.12.1
  @backstage/plugin-techdocs                               0.12.11
  @backstage/plugin-user-settings                          0.3.14
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.11.1
  @backstage/test-utils                                    0.2.0
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1
```

**Comment by queueburt** [comment]
I want to +1 this, it's a bit of a sharp edge.  I realize it's an anti-pattern to not allocate memory limits to deployments, but anti-patterns shouldn't break developer interfaces when they're otherwise functionally usable in the cluster.  Consider as well that most test or demo environments aren't necessarily going to enforce resource limits while teams work through optimizing their apps' resource utilization.

**Comment by freben** [comment]
Hi! Are you able to try to contribute a fix for this bug?

**Comment by manuelstein** [comment]
Such a well documented bug, thank you, @esphen! Also, I was facing the same issue, so I took my chances and just proposed a PR with a fix, @freben
