### ISSUE TITLE
[Plugin] My Squad

### ISSUE THREAD

**Issue by padupe** [backstage/backstage#8678]
## Summary

Plugin to render "My Squad".

The idea would be a screen where the user selects his Squad, based on the integration with GitHuB and its members are rendered alongside.

## Context

As it is not yet possible to identify the user through the login via GitHub, I believe it is something interesting for developers to use.

Even though this information can be accessed by other "paths", I believe that a specific plugin would make the experience more pleasant.

**Comment by padupe** [comment]
1)![MinhaSquad_1](https://user-images.githubusercontent.com/72894267/147676765-c2e2992c-4118-49c4-9331-a19f82d1f220.png)

2)![MinhaSquad_2](https://user-images.githubusercontent.com/72894267/147676796-e162a415-1ac5-464c-9b61-e941da7a2c89.png)

3)![MinhaSquad_3](https://user-images.githubusercontent.com/72894267/147676812-a5fa4b6c-ea8e-4d8d-b98d-9d59bf73ec56.png)

4)![MinhaSquad_4](https://user-images.githubusercontent.com/72894267/147676828-325578e6-aa27-4297-af91-2feea1710383.png)

**Comment by awanlin** [comment]
This is a great idea, would be good if when built it's more generic, once the user is authenticated by any supported provider.

It would also be pretty awesome to use the existing Groups view as we and may others have customized this to your needs

**Comment by regicsolutions** [comment]
Agreed @awanlin in our case we call teams Pods instead of Squads and one engineer can be a member of one or more Pods

**Comment by awanlin** [comment]
I've create a sidebar component that does that following:

- If you are not logged in it's not visible
- If you are member of a single group then it will give show as simply "My Squad" which will link to the proper group page in the catalog
- If you are a member of more than one group it will show as "My Squads" and have an expanded sidebar with all your groups linking to their respective pages in the catalog
- The icon and titles can be passed in as props so if you want to use "Team" or "Pod" or "Ninja" that's possible

@freben I'm not sure where to put this, it's just a single component so a full on plugin feels pretty heavy. Any suggestions?

**Comment by awanlin** [comment]
@freben also, can you assign this to me please?

**Comment by freben** [comment]
Assigned!

**Comment by freben** [comment]
(we'll probably provide more feedback later)

**Comment by padupe** [comment]
I like the idea presented by @awanlin  But doesn't the possibility of the user selecting the team through a combo appeal to them as well?

**Comment by awanlin** [comment]
@padupe there is a good chance that I'm misunderstanding what you mean, so forgive me, but there is a way to see all the teams by using the existing Kind drop down in the catalog. For example this gets you to all the Groups (Teams) in the Demo Backstage instance: https://demo.backstage.io/catalog?filters%5Bkind%5D=group&filters%5Buser%5D=all

![image](https://user-images.githubusercontent.com/67169551/150799167-2905fa80-dbcd-4501-ac6d-36a4726acd32.png)

The idea I had for the sidebar component was to reduce the number of clicks to get to teams you are a part of which I think once you see it action it does pretty well 😄

**Comment by awanlin** [comment]
I've submitted a PR with the sidebar component I mentioned. Feel free to take a look #10026
