### ISSUE TITLE
NotAllowedError: Entity domain:default/mydomain is not of an allowed kind for that location

### ISSUE THREAD

**Issue by JarrodJ83** [backstage/backstage#8701]
## Expected Behavior
Expected the Domain to be imported

## Current Behavior

NotAllowedError: Entity domain:default/mydomain at url:<mygitlaburl>/-/blob/main/all-systems.yaml, originated at url:<mygitlaburl>/-/blob/main/all-systems.yaml, is not of an allowed kind for that location

## Possible Solution

I tried adding Domain to the app-config.yaml catalog rules like below but was unsuccessful in solving the issue:

```
catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location, Domain]
```

## Steps to Reproduce

Try to manually import a Domain via the UI using "Register New Component" and provide it with a yaml file that contains a `kind: Domain`
```
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: mydomain
  description: MyDomain
spec:
  owner: team-a
```

## Context

I'm trying to add my systems to a domain so that I can visualize things in the Diagram views.

## Your Environment

OS:   Windows_NT 10.0.19043 - win32/x64
node: v14.17.1
yarn: 1.22.5
cli:  0.10.4 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.3
  @backstage/backend-common                                0.10.1
  @backstage/backend-tasks                                 0.1.1
  @backstage/catalog-client                                0.5.3
  @backstage/catalog-model                                 0.9.8
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.10.4
  @backstage/config-loader                                 0.9.1
  @backstage/config                                        0.1.11
  @backstage/core-app-api                                  0.3.0
  @backstage/core-components                               0.8.2
  @backstage/core-plugin-api                               0.4.0
  @backstage/errors                                        0.1.5
  @backstage/integration-react                             0.1.17
  @backstage/integration                                   0.7.0
  @backstage/plugin-api-docs                               0.6.20
  @backstage/plugin-app-backend                            0.3.21
  @backstage/plugin-auth-backend                           0.6.0
  @backstage/plugin-catalog-backend                        0.19.4
  @backstage/plugin-catalog-import                         0.7.7
  @backstage/plugin-catalog-react                          0.6.9
  @backstage/plugin-catalog                                0.7.6
  @backstage/plugin-github-actions                         0.4.29
  @backstage/plugin-org                                    0.3.32
  @backstage/plugin-permission-common                      0.3.0
  @backstage/plugin-permission-react                       0.2.0
  @backstage/plugin-proxy-backend                          0.2.15
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.7
  @backstage/plugin-scaffolder-backend                     0.15.19
  @backstage/plugin-scaffolder-common                      0.1.2
  @backstage/plugin-scaffolder                             0.11.16
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.3.0
  @backstage/plugin-search                                 0.5.3
  @backstage/plugin-tech-radar                             0.5.0
  @backstage/plugin-techdocs-backend                       0.12.2
  @backstage/plugin-techdocs                               0.12.12
  @backstage/plugin-user-settings                          0.3.14
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.11.2
  @backstage/test-utils                                    0.2.1
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1

**Comment by jhaals** [comment]
Hi, sorry to hear that you're having issues. I'm not able to reproduce this problem by adding `Domain`
to my app-config.yaml allow list. 
```
catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location, Domain]
```
and then importing a location that includes a domain such as https://github.com/blamdemo/bigbadwolf1337/blob/master/catalog-info.yaml

Please try that location to see if that makes a difference.

**Comment by JarrodJ83** [comment]
Hi @jhaals . I get the same issue when importing your yaml file: 

> {"error":{"name":"Error","message":"NotAllowedError: Entity domain:default/mydomain at url:https://github.com/blamdemo/bigbadwolf1337/blob/master/catalog-info.yaml, originated at url:https://github.com/blamdemo/bigbadwolf1337/blob/master/catalog-info.yaml, is not of an allowed kind for that location","level":"error","service":"backstage"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":500}}

I'm very new to Backstage so maybe there is a better way for me to get started with things. I made sure I ran `yarn backstage-cli versions:bump` then `npx @backstage/create-app` to get started. I thought that would make sure I had all the latest code running but maybe not? Is there anything you can think of I should try?

**Comment by JarrodJ83** [comment]
Turns out I was editing the incorrect `app-config.yaml` file. After adding the Domain to the catalog rules this now works as expected. Apologies for the false alarm.

**Comment by Ubloobok** [comment]
Hi there! Just want to say thanks for this issue, because it may be found in the internet by the error description Entity ... at file ... is not of an allowed kind for that location".
