### ISSUE TITLE
Error compiling schema - index.js 

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#8705]
## Expected Behavior

App should start

## Current Behavior

App is starting with a blank page and am getting the following console errors after upgrading to release-2021-12-30

![image](https://user-images.githubusercontent.com/6157895/147799369-21345f7d-9b23-412d-a990-2c04a2e3539e.png)

**Comment by jhaals** [comment]
This is likely due to the new default CSP policy introduced in https://github.com/backstage/backstage/pull/8673

We are looking into adding a fix for this but the short term fix would be to add `script-src: ["'self'", "'unsafe-eval'"]` to your csp section in app-config.yaml

**Comment by Rugvip** [comment]
The fix for this will be released tomorrow, 2022-01-04
