### ISSUE TITLE
[RFC] Introduce package.json "role" field to simplify tooling configuration

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#8729]
**Status:** Open for comments

## Need

We currently have a handful of different kinds of package that can existing within a Backstage project, frontend plugins, backend plugins, the app and backend themselves, library packages, plugin libraries, etc. There's currently no way for tools to look at a package and reliably say what kind of package it is. There are some patterns we can check for, but nothing really enforces these pattern and that could often lead to incorrect results. We could try things like checking what `"build"` script is being used, and what suffix the package name has, both they're both pretty unreliable.

There are also parts of the tooling in the `@backstage/cli` that you're supposed to "set up the correct way" for each kind of package, you should use the correct `"build"` and `"start"` scripts, and set up `.eslintrc.js` correctly. Thankfully most of these are created with `backstage-cli create`, but there are some gaps there, and it makes it difficult to convert packages and update old packages. It also makes it impossible to ship some new features through the CLI without requiring updates of the target packages.

On that topic we're currently a little bit stuck upgrading Jest because we can't provide a generated configuration that makes sense. Jest recently switched the default environment away from `jsdom`, and we would like to follow that path. The trouble is that we're not able to inspect what kind of package we're dealing with from the built-in Jest configuration in the CLI, so we can't reliably select the correct environment.

## Proposal

Introduce a well-known `"role"` field to `package.json`, which declares the role of the package, for example `"backstage-plugin-frontend"`.

I find "role" to be a good overall term, since it's not as overloaded as "kind" within Backstage, and "type" is already a reserved field. It's definitely worth bike-shedding that term a bit though, as it would likely stick. On top of the discussion of the term itself we'd also need to settle on how it would be represented in `package.json`. For example should it be just `"role"`, or affixed for more context, like `"backstage-role"`?

The value of the role field would be a simple string enum, for example something like the following set:

```ts
"cli"
"web-library"
"common-library"
"node-library"
"backstage-app"
"backstage-backend"
"backstage-plugin-frontend"
"backstage-plugin-frontend-module"
"backstage-plugin-backend"
"backstage-plugin-backend-module"
```

The package `"role"` could then be read by various tooling and configuration generators. For example our `.eslintrc.js` could be shifted to do something like `require('@backstage/cli/config/eslint')(require('./package.json'))` which then resolves the correct base lint config. The `"build"` and `"start"` scripts could be switched out to simply always call `backstage-cli build` and `backstage-cli start` respectively.

It would also let us extend our possible tooling quite a bit, it would for example be easier to write repo linters that make sure that there aren't any forbidden dependencies in place, like a `"backstage-app"` depending on a `"backstage-plugin-backend"`. It would also open up for more powerful documentation generation and discoverability tools.

## Alternatives

One close alternative would be to use a less specific role declaration and perhaps break it down a bit too. For example, a role declaration could look more like this `"role": { "platform": "web", plugin: true }`. I'm currently in favor of the single identifier though as that lets you encapsulate more semantic meaning in each of the roles, and likely lets us do more powerful things in the future.

A naming alternative that I think is worth calling out is to nest the role inside a top-level `"backstage"` field, so that it looks something like this in `package.json`:

```json
{
  "name": "@backstage/plugin-foo",
  "backstage": {
    "role": "plugin-frontend"
  }
}
```

With that (along with alternatives like "backstage-role") we can drop the `"backstage-"` prefix and avoid the discussion of whether it should be `"backstage-web-library"` or just `"web-library"`.

## Risks

There's a significant risk of lock-in, and I think it's important that we provide ways to configure the build tooling so that any of the configurations that result from setting a package role are also reachable using flags, specific imports, etc. We should not end up in situations where someone has to use the Backstage CLI with package roles declared, for example one thing to avoid would be any kind of compiler integration that generates code based on the role of imported packages.

One risk of going with a single identifier for the role is that we get an explosion of different roles just so we can cover some matrix. Because of that it would be important to consider what the correct abstraction level is for all of the roles, does both `web-library` and `backend-plugin-frontend-module` make sense for example? I think it's best to err on the side of too many roles to begin with and then perhaps prune them over time, since it's easy to define aliases but you can't go the other way around. There would also likely be some utility in `@backstage/cli-common` to work with roles, making the implementation end of things not get too messy.

**Comment by JP-Dhabolt** [comment]
My thoughts are to use the top level `backstage` field, with `role` within the object.  This appropriately namespaces the setting so that the top-level of `package.json` isn't polluted with something ambiguous (and removes any risk of collision).  It also allows for extending the context if needed, by adding additional fields underneath `backstage`.

I agree with your thinking that discrete role names, rather than compound objects, provides more clarity.  I would also agree with the erring on the side of too many, rather than too few roles.

**Comment by Rugvip** [comment]
@JP-Dhabolt thank you for sharing your thoughts! 👍 

Totally agree, the more I've been thinking about this the more a top-level `"backstage"` field seems to be the way to go. I'm hearing an increasing number of ideas that fit into that world and would likely occupy other fields in the `"backstage"` object. One example being a frontend plugin declaring its accompanying backend plugin in `package.json`.

We also shouldn't forget about the top-level `experimentalInstallationRecipe` that we currently support through the experimental `backstage-cli install` command, that would likely be moved into the `"backstage"` field too.

**Comment by iamEAP** [comment]
> I'm hearing an increasing number of ideas that fit into that world and would likely occupy other fields in the `"backstage"` object. One example being a frontend plugin declaring its accompanying backend plugin in `package.json`.

In this world, is there any advantage to stuffing it on a namespaced portion of `package.json` vs. introducing a separate `backstage-info.[json|yaml]`? or similar?

**Comment by kuangp** [comment]
> In this world, is there any advantage to stuffing it on a namespaced portion of `package.json` vs. introducing a separate `backstage-info.[json|yaml]`? or similar?

There is the existing `backstage.json` file we may be able to reuse/extend here
https://github.com/backstage/backstage/blob/79f56f15532ce7256bedb9756732d44c348725e5/packages/cli-common/src/paths.ts#L171-L176

**Comment by Rugvip** [comment]
One pretty big advantage to adding it to `package.json` when you're building tooling is that package registries will return the contents of `package.json`, but if you want to access files you likely need to be downloading and extracting the archive

**Comment by plex-test** [comment]
Is there a usecase for a package to have multiple roles?

**Comment by plex-test** [comment]
> 

Sorry about the `plex-test` thing ;) I created an example GitHub org for testing and forgot I was still logged into that here on Monday morning.  

I guess 'common-library' would imply usage everywhere and I further guess those cases would be rare enough to not need more fine-grained control at this time. Perhaps in the future, if it becomes necessary, 'common-library' in combination with an "excluded-roles" block would cover all possible scoping cases.

**Comment by Rugvip** [comment]
@plex-test Please elaborate x), do you mean a common library that has certain exports that are only for web or node? Generally a common library should only contain isomorphic exports, and if needed web- or node-only things would be put in appropriate packages instead.

**Comment by plex-test** [comment]
Yes, isomorphic is a prerequisite for common usage indeed and good to point out explicitly. I see from your implementation that these are only used to guide internal Backstage logic and the not the functionality of other tooling so implementing a new role in the future should cover all usecases. Sorry for the noise!

**Comment by Rugvip** [comment]
@plex-test no worries!
