### ISSUE TITLE
Example star wars graphql fails

### ISSUE THREAD

**Issue by timjnh** [backstage/backstage#8743]
When attempting to run any query using the example starwars-graphql API I get an error related isObservable.  From what I can tell there's no network request being made so before any request goes out.  It's possible this is a configuration problem on my end but I'm at a loss to figure out where I'm going wrong.

## Expected Behavior

I should get a response or some sort of actionable error.

## Current Behavior

I get back the following error:

`{
  "errors": {
    "message": "Cannot use 'in' operator to search for 'subscribe' in null",
    "stack": "TypeError: Cannot use 'in' operator to search for 'subscribe' in null\n    at isObservable (webpack-internal:///../../node_modules/graphiql/esm/components/GraphiQL.js:1270:21)\n    at eval (webpack-internal:///../../node_modules/graphiql/esm/components/GraphiQL.js:1075:29)"
  }
}`

## Steps to Reproduce

1. npx @backstage/create-app and walk through the setup steps
2. yarn dev
3. Wait for startup
4. Navigate to http://localhost:3000/catalog/default/api/starwars-graphql/definition
5. Enter any query
6. Press the Execute button

## Context

Just trying to get a sample GraphQL API to work

## Your Environment

- NodeJS Version: 14.17.6
- Operating System and Version: Mac OS 10.14.6
- Browser Information: Chrome 96.0.4664.110

**Comment by timjnh** [comment]
Hmm, I believe I found the reason.  It looks like the default fetcher implementation just returns null.

https://github.com/backstage/backstage/blob/cbfa75bf69da90961daae517f28a106327ceb5d0/plugins/api-docs/src/components/GraphQlDefinitionWidget/GraphQlDefinitionWidget.tsx#L58

So is the only way to get this working to create a custom API implementation?

**Comment by benjdlambert** [comment]
Yeah I believe that it's not really setup to go and fetch any data yet, thinking that it might be this way due to things like Authorization headers or something like that not being so easy to attach for the queries. So it just displaying the query interface was a nice middleground.
