### ISSUE TITLE
Internal link in public docs https://backstage.io/docs/architecture-decisions/adrs-overview

### ISSUE THREAD

**Issue by StevenTCramer** [backstage/backstage#8761]
https://backstage.io/docs/architecture-decisions/adrs-overview links to 
https://engineering.atspotify.com/2020/04/14/when-should-i-write-an-architecture-decision-record/'

which is not public accessible. 

## Expected Behavior
Linked page to be visible.

## Current Behavior
403 Forbidden

## Possible Solution
Make blog post public.

**Comment by OrkoHunter** [comment]
Hi @StevenTCramer! The blog post you have linked is on a public Spotify Engineering blog site, and not an internal one. Here is a snapshot[1] of the page on archive.org - if you're unable to access the domain for some reason.

[1] https://web.archive.org/web/20220105114115/https://engineering.atspotify.com/2020/04/14/when-should-i-write-an-architecture-decision-record/

**Comment by benjdlambert** [comment]
Hmm this is pretty strange? That `engineering.atspotify.com` link works on my machine? Maybe it was a temporary hiccup?

**Comment by benjdlambert** [comment]
Hmm what. It works for me right now, I wonder if we've broken some routing internally. Let me ping internally..
![Screenshot 2022-01-11 at 16 24 33](https://user-images.githubusercontent.com/3645856/148970985-0df7bd80-9641-4f37-ba82-e9f127a4c996.png)

**Comment by adamdmharvey** [comment]
Yup works for me now:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/33203301/148996529-5dd27e59-4d95-4af3-8984-011d86366a53.png">
