### ISSUE TITLE
Add the option of inputs on the github:actions:dispatch Backstage Action

### ISSUE THREAD

**Issue by tradcliffe-expediagroup** [backstage/backstage#8770]
## Feature Suggestion

Adding inputs to pass to a Github action would allow the user to pass values from the Backstage action to the Github action the user wants to trigger, making the Github actions more useful. 

Inputs are allowed on the [createWorkflowDispatch](https://octokit.github.io/rest.js/v18#actions-create-workflow-dispatch) endpoint in octokit as an object, but have not been added to the Backstage [github:actions:dispatch](https://github.com/backstage/backstage/blob/dbce13d7ae2b0060acb506059639c3b95b7b8258/plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/githubActionsDispatch.ts#L67) Action. 

I saw it was also mentioned on Discord here: https://discord.com/channels/687207715902193673/687235481154617364/914810536217157642

But I did not seen an issue for this and I didn't see it implemented. 

## Possible Implementation

In our version of Backstage I implemented this by adding inputs as an optional parameter for the [gitubActionsDispatch](https://github.com/backstage/backstage/blob/dbce13d7ae2b0060acb506059639c3b95b7b8258/plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/githubActionsDispatch.ts) in both the createTemplateAction and when createWorkflowDispatch is called. Doing this allows Github to access the inputs through ${{ github.event.inputs.<NAME_OF_VALUE> }}.

One thing to note is that when using the fetch action with the github:actions:dispatch action with inputs, the user will need to add the Github Action yaml file path to the copyWithoutRender option. Or else the action will fail because github is not defined. 

## Context

I provided context above. Please let me know if you need more.

**Comment by benjdlambert** [comment]
@tradcliffe-expediagroup is this something you want to contribute from your internal source and open source it? :pray: Sounds like a great feature to have in the `github:actions:dispatch` action.

**Comment by tradcliffe-expediagroup** [comment]
Yep! I was just waiting for the go ahead. I will get started on contributing it this week! Thank you.

**Comment by benjdlambert** [comment]
Awesome - just assigned you!

**Comment by tradcliffe-expediagroup** [comment]
I have this done locally. I am just having issues getting the changes to GitHub. My new phone does not have my authentication app and I am away for the weekend.  I will be able to do this without issue on Monday morning PST.

**Comment by tradcliffe-expediagroup** [comment]
I have a PR open here: https://github.com/backstage/backstage/pull/9149
