### ISSUE TITLE
Create Component button available in readonly mode

### ISSUE THREAD

**Issue by jcarres-mdsol** [backstage/backstage#8812]
We deploy Backstage in Readonly mode (for now). The catalog still shows the "Create Component" button and allows any user to try register a component. The process will eventually fail due to the system being in Readonly mode.

I think it is a bug that the button and the Register Component UI are available if in Readonly, they should be inaccessible/hidden.

**Comment by Rugvip** [comment]
You can get rid of the "Create Component" button by removing the following line:

https://github.com/backstage/backstage/blob/71369c25917c14acb048890d9dd57bcdecdfe096/packages/app/src/App.tsx#L113

**Comment by jcarres-mdsol** [comment]
That's for the tip, I'll do so. I still think this should be fixed upstream, probably some kind of if statement around that line ?

**Comment by Rugvip** [comment]
It's not a clean 1-1 mapping between readonly catalog and whether that button should be shown. It's common to use readonly catalog along with for example GitHub discovery and repositories being created through the scaffolder. It's likely better to keep the two independent

**Comment by jcarres-mdsol** [comment]
Umm, Ok, I guess I misunderstood the goal of "create component", I thought the only functionality it provides is to register new elements into the catalog

**Comment by Rugvip** [comment]
There's also the register existing component on the scaffolder page https://github.com/backstage/backstage/blob/71369c25917c14acb048890d9dd57bcdecdfe096/packages/app/src/App.tsx#L126

That one might make sense to toggle based on the catalog readonly mode,  but would still wanna be a bit careful
