### ISSUE TITLE
[Techdocs] README.md index page fallback does not work during `techdocs-cli generate` without `--techdocs-ref`

### ISSUE THREAD

**Issue by ctrombley** [backstage/backstage#8816]
Relates to #7080.
Relates to #6057.

The feature implemented in #7080 provides a fallback to a `README.md` file in case `docs/index.md` is not found.   This doesn't appear to work when generating docs in a CI/CD pipeline with the `techdocs-cli generate` command.

## Expected Behavior

Docs generation should attempt to use a `README.md` in the source directory in case `docs/index.md` is not found.

## Current Behavior

Docs generation is not using the`README.md` in the source directory when `docs/index.md` is not found.

## Workaround

After some debugging, I found that providing a bogus value to the `--techdocs-ref` argument when generating from the root of my repository was enough to get the feature working:

```bash
# Fallback is not invoked
npx @techdocs/cli generate --no-docker -v

# Fallback works when providing a --techdocs-ref argument
npx @techdocs/cli generate --no-docker -v --techdocs-ref .
```

This seems to be because the `patchIndexPreBuild` method that provides the README.md fallback in techdocs-common is gated by the presence of a non-empty `--techdocs-ref` argument (represented by the `parsedLocationAnnotation` option):
https://github.com/backstage/backstage/blob/986a5d869ea976fee71844c2aadd777907fde082/packages/techdocs-common/src/stages/generate/techdocs.ts#L95-L103

## Possible Solution

I can't see why `patchIndexPreBuild` needs to be called from within the conditional block.  If it sounds like a reasonable path forward, I can PR a change that moves it outside so that it happens regardless of if a `--techdocs-ref` argument is provided during generation.

## Your Environment

- techdocs version: latest (using `npx` for invocation)
- NodeJS Version: v16.13.10
- Operating System and Version: MacOS Big Sur 11.6

**Comment by ngeegoh** [comment]
Hi @ctrombley ,

I have the same issue but thanks to your workaround I can get it generated now. However, I have a question, when Backstage displays readme.md contents in techdocs, all the images attached to README.md cant be rendered and displayed. It looks like this 
![image](https://user-images.githubusercontent.com/32254681/150878039-5599745a-5c07-4ffe-ab0f-eec38d4a8015.png)
Do you know whats the fix for this? or Backstage techdocs just cannot display images? (FYI: techdocs generates and publishs techdocs files to Azure storage account)

**Comment by ctrombley** [comment]
@ngeegoh You probably need to update your content security policy via the `backend.csp.img-src` config field to include the sites you're pulling in badges from.  Mine looks like this:

```yaml
backend:
  csp:
    img-src: ["'self'", 'https://circleci.com', 'https://sonarcloud.io']
```

**Comment by ngeegoh** [comment]
@ctrombley How do I know which sites im pulling in badges from? Its from the azure storage account I assume.
Can I do like this?
```
backend:
  csp:
    img-src: ["'self'", 'http:', 'https:']
```

**Comment by iamEAP** [comment]
There may be a promising solution in here: https://github.com/backstage/backstage/pull/8541, if someone in this thread would be willing to resurrect and address some of the suggestions in the feedback?

**Comment by soapraj** [comment]
Closing this issue for now. Please feel free to reopen if you have more inputs on this.
