### ISSUE TITLE
Running backend produces garbage due to using colors 1.4.2

### ISSUE THREAD

**Issue by ctudball** [backstage/backstage#8831]
The colors 1.4.2 package produces garbage output and causes an infinite loop as [shown here](https://github.com/Marak/colors.js/issues/289).

## Expected Behavior

Doing a `yarn start` on the backend would start the backend correctly.

## Current Behavior

Doing a `yarn start` on the backend causes garbage output and the terminal session to eventually lock up.

## Possible Solution

Lock the version of the colors library to 1.4.0, which is unaffected.  Currently the backend is using 1.4.2.

> yarn why v1.22.11
> [1/4] 🤔  Why do we have the module "colors"...?
> [2/4] 🚚  Initialising dependency graph...
> [3/4] 🔍  Finding dependency...
> [4/4] 🚡  Calculating file sizes...
> => Found "colors@1.4.0"
> info Reasons this module exists
>    - "_project_#app#cypress#cli-table3" depends on it
>    - Hoisted from "_project_#app#cypress#cli-table3#colors"
> info Disk size without dependencies: "116KB"
> info Disk size with unique dependencies: "116KB"
> info Disk size with transitive dependencies: "116KB"
> info Number of shared dependencies: 0
> => **Found "logform#colors@1.4.2"**
> info This module exists because "_project_#backend#@backstage#backend-common#logform" depends on it.
> info Disk size without dependencies: "120KB"
> info Disk size with unique dependencies: "120KB"
> info Disk size with transitive dependencies: "120KB"
> info Number of shared dependencies: 0
> ✨  Done in 1.01s.

## Steps to Reproduce

1. Clone the current release
2. Try and do a `yarn start` in `packages/backend`

## Your Environment

> OS:   Darwin 21.2.0 - darwin/x64
> node: v16.13.0
> yarn: 1.22.11
> cli:  0.10.5 (installed)
> 
> Dependencies:
>   @backstage/app-defaults                                  0.1.3
>   @backstage/backend-common                                0.10.2
>   @backstage/backend-tasks                                 0.1.2
>   @backstage/catalog-client                                0.5.3
>   @backstage/catalog-model                                 0.9.8
>   @backstage/cli-common                                    0.1.6
>   @backstage/cli                                           0.10.5
>   @backstage/config-loader                                 0.9.1
>   @backstage/config                                        0.1.11
>   @backstage/core-app-api                                  0.3.1
>   @backstage/core-components                               0.8.3
>   @backstage/core-plugin-api                               0.4.1
>   @backstage/errors                                        0.1.5
>   @backstage/integration-react                             0.1.17
>   @backstage/integration                                   0.7.0
>   @backstage/plugin-api-docs                               0.6.21
>   @backstage/plugin-app-backend                            0.3.21
>   @backstage/plugin-auth-backend                           0.6.1
>   @backstage/plugin-catalog-backend                        0.19.4
>   @backstage/plugin-catalog-import                         0.7.8
>   @backstage/plugin-catalog-react                          0.6.10
>   @backstage/plugin-catalog                                0.7.7
>   @backstage/plugin-github-actions                         0.4.30
>   @backstage/plugin-org                                    0.3.33
>   @backstage/plugin-permission-common                      0.3.0
>   @backstage/plugin-permission-react                       0.2.1
>   @backstage/plugin-proxy-backend                          0.2.15
>   @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.7
>   @backstage/plugin-scaffolder-backend                     0.15.19
>   @backstage/plugin-scaffolder-common                      0.1.2
>   @backstage/plugin-scaffolder                             0.11.17
>   @backstage/plugin-search-backend-node                    0.4.3
>   @backstage/plugin-search-backend                         0.3.0
>   @backstage/plugin-search                                 0.5.4
>   @backstage/plugin-tech-radar                             0.5.1
>   @backstage/plugin-techdocs-backend                       0.12.2
>   @backstage/plugin-techdocs                               0.12.13
>   @backstage/plugin-user-settings                          0.3.15
>   @backstage/search-common                                 0.2.1
>   @backstage/techdocs-common                               0.11.2
>   @backstage/test-utils                                    0.2.1
>   @backstage/theme                                         0.2.14
>   @backstage/types                                         0.1.1
>   @backstage/version-bridge                                0.1.1
> ✨  Done in 0.76s.

**Comment by freben** [comment]
Aw damn. So we did get bitten by this. Alright, of course let's try to get that fixed. It's very late now but we'll get on it.

**Comment by benjdlambert** [comment]
Ok, @ctudball if this was a new `npx @backstage/create-app`, then I think if you delete the `yarn.lock` and run `yarn` again it should fix it as the dependency is locked in `logform` now. We will do a release on thursday to force the latest version of `logform` in `backend-common` which locks it too.

https://github.com/winstonjs/logform/pull/128 should have fixed it in new `create-app` installs.

We're waiting for this one too: https://github.com/cypress-io/cypress/pull/19622

You could add a `resolutions` block in your root `package.json` to force `colors` to `1.4.0` but hopefully might not need that as it should be locked for most people already.

**Comment by benjdlambert** [comment]
https://github.com/backstage/backstage/pull/8836 is the pinned `logform` release which will go out on Thursday.
