### ISSUE TITLE
Can't search part of the word while using Postgres as the search engine

### ISSUE THREAD

**Issue by dehamzah** [backstage/backstage#8835]
While using LunrJS as the search engine I can search all part of the word. Example searching the word 'petstore', I can search using keyword: 'ets', 'tst', 'store'. But after switching to Postgres as the search engine, the search results is not found using the example keywords. The search results is still found if I search using keyword: 'petstore', 'pet', 'pets'.

## Expected Behavior

The search results should be found using keywords that uses second half part of the word.

## Current Behavior

<img width="950" alt="Screen Shot 2022-01-10 at 09 38 01" src="https://user-images.githubusercontent.com/6959476/148717562-e4312938-5b70-40cf-b6a9-e7da81789f90.png">

<img width="1065" alt="Screen Shot 2022-01-10 at 09 37 43" src="https://user-images.githubusercontent.com/6959476/148718152-d4c09f2b-abb9-440b-a181-92ba6fa1e803.png">

## Possible Solution

Probably need to update the search query in package `@backstage/plugin-search-backend-module-pg`

## Steps to Reproduce

1. Update the search engine to postgres
2. Search the keyword using half part of the word like the examples.

## Context

Using the LunrJS is not suitable for production use, and we want to try using Postgres as the search engine.

## Your Environment

```
OS:   Darwin 20.6.0 - darwin/x64
node: v14.18.1
yarn: 1.22.17
cli:  0.10.4 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.3
  @backstage/backend-common                                0.10.1
  @backstage/catalog-client                                0.5.3
  @backstage/catalog-model                                 0.9.8
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.10.4
  @backstage/config-loader                                 0.9.1
  @backstage/config                                        0.1.11
  @backstage/core-api                                      0.2.23
  @backstage/core-app-api                                  0.3.1
  @backstage/core-components                               0.8.3
  @backstage/core-plugin-api                               0.1.13, 0.3.1, 0.4.1
  @backstage/core                                          0.7.14
  @backstage/errors                                        0.1.5
  @backstage/integration-react                             0.1.17
  @backstage/integration                                   0.6.10, 0.7.0
  @backstage/plugin-api-docs                               0.6.20
  @backstage/plugin-app-backend                            0.3.21
  @backstage/plugin-auth-backend                           0.6.0
  @backstage/plugin-catalog-backend-module-ldap            0.3.8
  @backstage/plugin-catalog-backend                        0.19.4
  @backstage/plugin-catalog-graph                          0.2.4
  @backstage/plugin-catalog-import                         0.7.7
  @backstage/plugin-catalog-react                          0.6.9
  @backstage/plugin-catalog                                0.7.6
  @backstage/plugin-explore-react                          0.0.9
  @backstage/plugin-explore                                0.3.23
  @backstage/plugin-kubernetes-backend                     0.4.1
  @backstage/plugin-kubernetes-common                      0.2.0
  @backstage/plugin-kubernetes                             0.5.2
  @backstage/plugin-org                                    0.3.32
  @backstage/plugin-pagerduty                              0.3.20
  @backstage/plugin-permission-common                      0.3.0
  @backstage/plugin-permission-react                       0.2.0
  @backstage/plugin-proxy-backend                          0.2.15
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.7
  @backstage/plugin-scaffolder-backend                     0.15.19
  @backstage/plugin-scaffolder-common                      0.1.2
  @backstage/plugin-scaffolder                             0.11.16
  @backstage/plugin-search-backend-module-pg               0.2.3
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.3.0
  @backstage/plugin-search                                 0.5.3
  @backstage/plugin-shortcuts                              0.1.17
  @backstage/plugin-tech-radar                             0.5.0
  @backstage/plugin-techdocs-backend                       0.12.2
  @backstage/plugin-techdocs                               0.12.12
  @backstage/plugin-user-settings                          0.3.14
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.11.2
  @backstage/test-utils                                    0.2.1
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1
```

**Comment by garyniemen** [comment]
@emmaindal any thoughts on this?

**Comment by dehamzah** [comment]
Sorry about this, back then we are working at 2 things at the same time:
1. Moving to postgres search engine, and 
2. Splitting the backend pod that serve the rest API and the pod that run the search indexing

We do these because we are faced with the problem indexing a lot of data in the search, see https://github.com/backstage/backstage/issues/9178

The actual behavior on the above is that sometimes the search returning results and sometimes not if I type the correct query. Back then we had 2 pods, backend-search pod and backend pod, we disable the search indexing in backend pod and only enable it in backend-search pod. We didn't realize that the backend-search still serving API request from client, that's why the search sometimes returning results and sometimes not.

After we correct the configuration so that the backend-search didn't serve the rest API traffic, the search is still not functioning, it's turned out we need to run the `await indexBuilder.build()` in both pod, and only run `scheduler.start()` in the backend-search pod. This is needed because the search query route is checking the query's types property (which might have a value of, for example ['software-catalog']) corresponds to real types that the search-backend pod is aware of. See the related discussion on discord: https://discord.com/channels/687207715902193673/948065769294557264/951422894112661574

**Comment by sidprobstein** [comment]
If you chose the Postgres engine to avoid running Elasticsearch and hit this: we built a search engine module that runs in one container, no cluster, and matches part of a word. The title is indexed stemmed and as n-grams with BM25 ranking, and the index lives on disk so a restart costs nothing. The write-up with the cases from this thread and from 27339 and 6177 is at https://dev.to/sidswirl/why-backstage-search-returns-team-when-you-search-for-tech-and-what-we-did-about-it-pba, docs at https://docs.swirlaiconnect.com/backstage-overview. Apache 2.0.
