### ISSUE TITLE
npx @backstage/create-app doesn't work for node 17+

### ISSUE THREAD

**Issue by oparaskos** [backstage/backstage#8843]
When running  `npx @backstage/create-app`

then the process terminates with an error.
```
  executing     yarn install ◝ error root@1.0.0: The engine "node" is incompatible with this module. Expected version "14 || 16". Got "17.3.0"
```

## Feature Suggestion

Ideally this should support the latest stable version of node. In my case my node version is as below.
```
 -> % npx node --version
v17.3.0
```

**Comment by benjdlambert** [comment]
So we don't support 17, we support LTS versions which is 16 and 14. You can however proceed with 17 if you wish by using `--ignore-engines` as an `yarn install` command after, but we'd recommend using one of the LTS versions instead as there could be dragons with 17.
