### ISSUE TITLE
NunjucksWorkflowRunner don't pass token to task

### ISSUE THREAD

**Issue by diegoribeiro-hotmart** [backstage/backstage#8846]
When the API requests authentication is enabled (see [here](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md)), the action `catalog:register` stops working in templates with `apiVersion=scaffolder.backstage.io/v1beta3`, caused by a 401 error. The previous apiVersion works fine.

Looking at the `HandlebarsWorkflowRunner.ts`, we can see this code:

https://github.com/backstage/backstage/blob/8a7ccbdf73adb66f04ffd4b5af71dfdf7a51c737/plugins/scaffolder-backend/src/scaffolder/tasks/HandlebarsWorkflowRunner.ts#L234-L242

You can see the property `token` is set. Looking at the same point in `NunjucksWorkflowRunner.ts`, the property isn't set:

https://github.com/backstage/backstage/blob/8a7ccbdf73adb66f04ffd4b5af71dfdf7a51c737/plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts#L257-L264

[Here](https://github.com/diegoribeiro-hotmart/backstage/commit/fb3374544204c3c64c58673392352f4a5acbeeed) is a possible solution to the problem.

**Comment by benjdlambert** [comment]
Nice find - do you want to raise a PR with this change so we can get it in? :)

**Comment by freben** [comment]
Fixed!
