### ISSUE TITLE
[Tech Insights] Run checks for multiple entities in a single request

### ISSUE THREAD

**Issue by goenning** [backstage/backstage#8848]
## Feature Suggestion

We built some custom pages to display information from the Tech Insights plugin, It's essentially a dashboard of all checks and the overall progress across the org, very similar to what Spotify has internally from what I've seen on some videos. Things like: how many services are on Python 3? 

We have 300+ services and the way we do it today is to run the `POST tech-insights/checks/run/:namespace/:kind/:name` for each service, but that essentially means 300+ HTTP requests from the browser, which is not ideal.

I'd like to suggest a new endpoint which would accept multiple entities in a single request, it'd be far more efficient for this scenario.

## Possible Implementation

I'm thinking of something like:
```
POST tech-insights/checks/run
Body:
{
  "entities": [ "component/default:foo", "component/default:bar" ], // this array could also support a list of object triplet kind/namespace/name 
  "checks": [ "check1", "check2" ] // if empty, run all checks
}
```

Response would look similar to the single entity run, but an object keyed by the component identifier.

```
{
 "component/default:foo": [ check1result, check2result ... ],
 "component/default:bar": [ check1result, check2result ... ]
}
```

Benefit of the above is being able to get results of a specific entity with O(1)

Another alternative is to return an array:
```
[
  {
    "entity": "component/default:foo",
    "results": [ check1result, check2result ... ]
  },
  {
    "entity": "component/default:bar",
    "results": [ check1result, check2result ... ]
  }
}
```

**Comment by Xantier** [comment]
Thanks @goenning!

Yeah, that makes perfect sense and would be a good addition to those endpoints. I think I like the return type from the API as an array of objects better than keyed results. That way we can add additional data into it without breakages. I do think that for FE manipulation the keyed shape is better so maybe do a quick `keyBy` loop on the FE API client.

**Comment by goenning** [comment]
Thanks for the inputs, I created a draft PR
