### ISSUE TITLE
Provide a way to customize the EntityRelationsGraph

### ISSUE THREAD

**Issue by shailendra-ahir-cbre** [backstage/backstage#8850]
Please provide a way to customize the EntityRelationsGraph by accepting the CustomNode and CustomLabel in its props, similar to renderNode and renderLabel.

**Comment by shailahir** [comment]
I would like to contribute. Please assign it to me.

**Comment by freben** [comment]
OK, assigned!

**Comment by shvmbisht** [comment]
@shailahir please provide some sample examples or documentation for this amazing contribution
