### ISSUE TITLE
LdapOrgReaderProcessor is not registered by default

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#8855]
I am integrate ldap with backstage. My ldap connection not working on local machine.  I got following 2 errors

config: cannot find the config name
logger: No value exists in the scope for the shorthand property 'logger'.

As per following page documentation suggest following:
https://backstage.io/docs/integrations/ldap/org

The LdapOrgReaderProcessor is not registered by default, so you have to register it in the catalog plugin:
// packages/backend/src/plugins/catalog.ts
`builder.addProcessor(
  LdapOrgReaderProcessor.fromConfig(config, {
    logger,
  }),
);
`
My backstage backend application.
refer code link: https://github.com/backstage/backstage/blob/master/packages/backend/src/plugins/catalog.ts

`export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addProcessor(
    new ScaffolderEntitiesProcessor(),
    LdapOrgReaderProcessor.fromConfig(config, {
      logger
    }),
  );
  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
`

## Expected Behavior

ldap should work with backstage

## Current Behavior

Display following errors

config: cannot find the config name
logger: No value exists in the scope for the shorthand property 'logger'.

## Possible Solution

I might not understand based on current documentation. or documentation needs to update.

## Steps to Reproduce
Try to implement ldap using current documentation.

- NodeJS Version (v14):
- Operating System and Version (e.g. Mac):
- Browser Information:(chrome)

**Comment by jhaals** [comment]
Hi,
Both logger and config are available in the `PluginEnvironment` so in this case as `env.logger` and `env.config`, this is fairly common practise but it might help with some clarification in the docs. Suggestions to the documentation is very welcome!

I'm closing this issue as we likely identified the problem. Feel free to reopen this issue if there are further questions!
