### ISSUE TITLE
CatalogGraph enhancment to select Force Directed Graph

### ISSUE THREAD

**Issue by belech** [backstage/backstage#8857]
## Feature Suggestion

It would be great to have the possibilty to select additionally to the existing tree graph functionality, a forced directed graph like here: https://observablehq.com/@d3/disjoint-force-directed-graph

## Possible Implementation

Probably should stay with D3 package for this: https://github.com/d3/d3-force 

Needs to be done here: https://github.com/backstage/backstage/tree/master/packages/core-components/src/components/DependencyGraph

and probable here: https://github.com/backstage/backstage/tree/master/plugins/catalog-graph

## Context

With a tree shaped graph, it's quite hard to visualize many dependencies - especially if those dependencies are on the same level, e.g. a very flat hierarchy in an organisation

**Comment by dschwank** [comment]
Thanks for the input @belech !

Yeah, that could be interesting - we should just make sure to have the forces quite stable, thus the graph is stable & does not move.
@freben @Rugvip do you think that could be part of the `DependencyGraph`?

**Comment by freben** [comment]
The `DependencyGraph` in `core-components` may end up being deprecated in favor of the `catalog-graph` plugin. So maybe that one is less worth spending time on.

The idea is very interesting though! There may be a case for being able to switch between arrangement modes at will?

**Comment by dschwank** [comment]
Yeah, that's a good idea to deprecate one of them. Wasn't aware that this is already planned - or is it just an idea yet?

> There may be a case for being able to switch between arrangement modes at will?

From my point of view it would be the best to have it optional, yes. If it is pretty awesome then we could still make it the default one.
