### ISSUE TITLE
Docker image fails after adding a backend plugin

### ISSUE THREAD

**Issue by jbadeau** [backstage/backstage#8867]
## Expected Behavior

This issue is a clone of the closed issue (#8022)
Bundled package should work

## Current Behavior

Bundled package does not work, throwing the following error:

```
<html>
<body>
<!--StartFragment-->

/app/plugins/troux-backend/dist/index.cjs.js:129515
--
  | var memoizedProperty$3 = util_1.memoizedProperty;
  | ^
  |  
  | TypeError: Cannot read property 'memoizedProperty' of undefined
  | at Object.<anonymous> (/app/plugins/troux-backend/dist/index.cjs.js:129515:33)
  | at Module._compile (internal/modules/cjs/loader.js:1085:14)
  | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
  | at Module.load (internal/modules/cjs/loader.js:950:32)
  | at Function.Module._load (internal/modules/cjs/loader.js:790:12)
  | at Module.require (internal/modules/cjs/loader.js:974:19)
  | at require (internal/modules/cjs/helpers.js:93:18)
  | at Object.<anonymous> (/app/packages/backend/dist/index.cjs.js:8:26)
  | at Module._compile (internal/modules/cjs/loader.js:1085:14)
  | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
  | at Module.load (internal/modules/cjs/loader.js:950:32)
  | at Function.Module._load (internal/modules/cjs/loader.js:790:12)
  | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
  | at internal/main/run_main_module.js:17:47

<!--EndFragment-->
</body>
</html>
```

## Steps to Reproduce

1. Create a backend plugin
2. Remove service folder and route related files
3. Integrate with backend package
4. Build the bundle
5. Run docker image

NOTE: The application works fine outside of the docker image when running `yarn dev`

## Context

I'm trying to add a catalog processor, external integration as a separate plugin. I do not need any routing at the moment. The setup is like this one, for example:

https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-ldap

## Your Environment

OS:   Windows_NT 10.0.19042 - win32/x64
node: v14.17.1
yarn: 1.22.17
cli:  0.10.2 (installed)
 
Dependencies:
  @backstage/app-defaults                                  0.1.2
  @backstage/backend-common                                0.9.14
  @backstage/catalog-client                                0.5.2
  @backstage/catalog-model                                 0.9.8
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.10.2
  @backstage/config-loader                                 0.8.1
  @backstage/config                                        0.1.11
  @backstage/core-app-api                                  0.2.1
  @backstage/core-components                               0.8.1
  @backstage/core-plugin-api                               0.3.1
  @backstage/dev-utils                                     0.2.14
  @backstage/errors                                        0.1.5
  @backstage/integration-react                             0.1.15
  @backstage/integration                                   0.6.10
  @backstage/plugin-api-docs                               0.6.18
  @backstage/plugin-app-backend                            0.3.19
  @backstage/plugin-auth-backend                           0.4.10, 0.5.1
  @backstage/plugin-catalog-backend                        0.19.2
  @backstage/plugin-catalog-graph                          0.2.3
  @backstage/plugin-catalog-import                         0.7.5
  @backstage/plugin-catalog-react                          0.6.7
  @backstage/plugin-catalog                                0.7.4
  @backstage/plugin-github-actions                         0.4.27
  @backstage/plugin-graphiql                               0.2.24
  @backstage/plugin-home                                   0.4.7
  @backstage/plugin-jenkins                                0.5.14
  @backstage/plugin-kafka-backend                          0.2.12
  @backstage/plugin-kafka                                  0.2.22
  @backstage/plugin-org                                    0.3.31
  @backstage/plugin-proxy-backend                          0.2.14
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.5
  @backstage/plugin-scaffolder-backend                     0.15.17
  @backstage/plugin-scaffolder-common                      0.1.1
  @backstage/plugin-scaffolder                             0.11.14
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.2.8
  @backstage/plugin-search                                 0.5.1
  @backstage/plugin-sonarqube                              0.2.9
  @backstage/plugin-tech-radar                             0.4.13
  @backstage/plugin-techdocs-backend                       0.12.0
  @backstage/plugin-techdocs                               0.12.10
  @backstage/plugin-user-settings                          0.3.13
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.11.0
  @backstage/test-utils                                    0.1.24
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1

**Comment by jbadeau** [comment]
It is a backend catalog processor. It is imported into the backend package and works fine locally via `yarn dev`. It fails when running in docker.

**Comment by jbadeau** [comment]
I'm debugging but I added the issue as I saw that #8022 was the same issue but it's not clear what packages fixed it.

**Comment by jbadeau** [comment]
Ok, the plugin is running but the setup is very odd:

Locally I was successfully developing with these dependencies in my backend
```
    "@backstage/backend-common": "^0.9.14",
    "@backstage/config": "^0.1.8",
```
But it fails when compiled and running in docker.

I then looked at (package.json)[https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-ldap/package.json] and switched to these dependencies:

```
    "@backstage/catalog-model": "^0.9.7",
    "@backstage/config": "^0.1.11",
    "@backstage/errors": "^0.1.5",
    "@backstage/plugin-catalog-backend": "^0.19.0",
    "@backstage/types": "^0.1.1",
```

Now it works locally and in Docker. I am happy it works but I don't understand whats going on.

**Comment by benjdlambert** [comment]
Hmm I'm not 100% sure either - Happy it works though! @backstage/maintainers anyone have any clue what's going on here?

**Comment by Rugvip** [comment]
It's important to declare all dependencies in `package.json`, especially for the backend build. Without dependencies properly declared you may end up having rollup inlining code that potentially leads to breakages like this. The best way to keep on top of the dependencies is to make sure you're using the lint config provided by the `@backstage/cli`, or your own ESLint configuration with [`import/no-extraneous-dependencies`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md).

Can't say for sure that it's the actually the issue here, but it sounds, looks, and smells like it.

**Comment by jbadeau** [comment]
H,

I agree, the dependencies should be declared. The issue is that it's not documented what dependencies are needed.

I think something is wrong with the setup. Maybe a transitive dep is being hoisted that is cont compatible. In any case I think it should be explicitly stated that these deps are needed.

I will look into it next week to see if i can find the root cause.
