### ISSUE TITLE
Move out Storybook into it's own workspace

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#8869]
We've got a real issue with upgrading certain dependencies, looking at you webpack 👀 , because we have two different versions of webpack v4, and v5 running side by side, and the types are all over the place for the webpack plugins and libraries.

We have a stable build right now, but trying to upgrade dependencies #8793 #8548 are proving to be a massive time sink as we need to get the correct modules installed in the correct places for our typescript build to pass with `skipLibCheck: false`.

Not hoisting the packages from the `storybook` workspace has worked for now, but it would be really nice if we just had one version of webpack and all the dev-server dependencies in the project.

Until storybook starts to use v5 out of the box, there's little we can do, as you can use v5 with storybook, but it will also try and bring in v5 which makes the whole thing even worse.

Let's move out Storybook into it's own yarn workspaces, that requires a seperate yarn install to get up and running and would install things in `storybook/node_modules` seperate with it's own yarn.lock.

Maybe there's also a possibility to skip the build tooling of storybook entirely and just get it to generate something that we can hook into our own build system instead.

**Comment by snehaljos** [comment]
hi am interested to work on it but I need some help can I work  on it?

**Comment by benjdlambert** [comment]
So I think it should be a case of removing `storybook` from `packages` and placing it at the root level under `storybook/` and then making sure that all the stories still work, and that any workflows that run storybook need to do a `yarn install` in the `storybook` directory as well as a normal `yarn install`. Feel free to go ahead and see if you can get this working, maybe there could also be other dragons which make this a little tricky and not a `good first issue`. 😅

**Comment by benjdlambert** [comment]
Fixed! Thanks @snehaljos!
