### ISSUE TITLE
[RFC] Package Create Command

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#8885]
**Status:** Open for comments

## Need

We need to include some AWS automation and Fargate tasks in our workflow. This task will be a separate implementation with it own code, docker image and packages.

Considering that we have a monorepo, it would make sense to place this new implementation in the packages folder. One more reason that led me to think about this is that having the implementation in another repo would complicate things because our existing infrastructure needs to be shared between the backstage repo and the new repo (it is managed with terraform).

My question would be, is there a CLI command that we can use to create a package, like we have one for creating a plugin? Or, we need to use Lerna `create` command for this?

**Comment by Rugvip** [comment]
The CLI actually already introduced a more generic replacement for the `create-plugin`, `backstage-cli create`. It's a bit more pluggable with the possibility of adding [factories](https://github.com/backstage/backstage/tree/master/packages/cli/src/lib/create/factories) for different types of packages. Right now there are only a few factories though, and they don't include generic packages in `packages/`, totally something we want to add though! It pretty directly related to https://github.com/backstage/backstage/issues/8729 actually, where every package role likely has at least one factory in `create`.

**Comment by ProticM** [comment]
Yes, I'm aware of the new CLI command and I've been using it to create the plugins 👍 It feels like a proper replacement due to having other things, not just plugins, inside backstage repo. I will read the linked RFC, tnx.

So, I can assume that this is a work in progress and that at this moment we should use Lerna to add a package until the CLI command is updated/ready? Considering that we do not have this in the backstage CLI, I can also assume that the packages in this repo are created the same way, with Lerna?

**Comment by Rugvip** [comment]
Tbh the most common way of creating new non-plugin packages is by copying an existing similar package and switching things out. I can tell because it's common to miss a thing or two when doing that x)
