### ISSUE TITLE
msw deprecation not documented in create-app changelog

### ISSUE THREAD

**Issue by mscam** [backstage/backstage#8889]
Hello, I am updating a backstage installation to latest release. I just noticed`msw` module deprecation is not documented:

[CHANGELOG](https://github.com/backstage/backstage/blob/master/packages/create-app/CHANGELOG.md)

<img width="901" alt="Screenshot 2022-01-12 at 16 00 33" src="https://user-images.githubusercontent.com/349166/149167340-9c8d26eb-2677-4da9-a1e4-c4923ddaa702.png">

It has been replaced by `setupRequestMockHandlers`.

**Comment by Rugvip** [comment]
The create-app changelog only covers the `@backstage/create-app` command and the code that it generates. The `msw` migration was part of the plugin template in the `@backstage/cli`, which we currently don't have the same kind of changelog entries for. The actual removal of the `msw` helper was documented in the test-utils changelog though, first the deprecation in [0.1.20](https://github.com/backstage/backstage/blob/master/packages/test-utils/CHANGELOG.md#0120), then the removal in [0.2.0](https://github.com/backstage/backstage/blob/master/packages/test-utils/CHANGELOG.md#020).

Gonna close this as I don't see any actions atm, but please do reopen if there's anything else!

**Comment by mscam** [comment]
understood. however, as a lazy developer building custom plugins, I would like to have everything in a signle place :)

**Comment by Rugvip** [comment]
I hear you, we've definitely considered powering https://backstage.github.io/upgrade-helper/ up to support individual packages as well. If you want to you can open up an issue for that to give it more visibly

**Comment by mscam** [comment]
Thank you @Rugvip for the upgrade helper! 💯

**Comment by Rugvip** [comment]
Thank @vinzscam who set it up :grin:
