### ISSUE TITLE
GitLab Organizational Data support

### ISSUE THREAD

**Issue by mscam** [backstage/backstage#8894]
## Feature Suggestion

Add GitLab Organizational Data support

## Possible Implementation

Same as GitHub Organizational Data: https://backstage.io/docs/integrations/github/org

## Context

As requirement for the developer portal I am working on, I do need to import User and Group entities from a managed GitLab installation. 

Do you have any suggestion on how to implement this, or do you have an ETA for this feature?

Thanks!

**Comment by minnsoe** [comment]
Hey @mscam, I was working on this functionality before the festive season. I'm currently cleaning up both the implementation and the API options prior to marking it as ready. I can't give an ETA but I can say that it's being actively worked on. The PR can be followed here: https://github.com/backstage/backstage/pull/8917

**Comment by mscam** [comment]
Hello @minnsoe and thanks! I will check it out

**Comment by benjdlambert** [comment]
Closing as fixed in #15888

**Comment by matteosilv** [comment]
I think there is a problem with the URLs in the annotations and I also needed to strip the group prefix from the group path, so I opened this pull https://github.com/backstage/backstage/pull/16468. Let me know if you agree with the changes.
