### ISSUE TITLE
Swagger UI js console errors

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#8895]
Getting console errors on swagger UI page. If i click on get/post method. it display console errors too.

Cannot read properties of undefined (reading 'match')

![image](https://user-images.githubusercontent.com/225961/149209356-51aed68a-7c8c-4a35-8ec8-1332c40d3ba2.png)

## Current Behavior

It displays lit of console errors

## Steps to Reproduce

1. Step 1: open this URL https://demo.backstage.io/catalog/default/api/petstore/definition#/
2. Step 2: Click on inspect and click on console
3. Step3: you will see error like Cannot read properties of undefined (reading 'match')

**Comment by freben** [comment]
Hmm @dschwank have you seen this particular error crop up before? I'll have to look into if this has something to do with our example data being bad, or if it's something bigger at play.

**Comment by dschwank** [comment]
Seems to be caused by the `url`

<img width="405" alt="Bildschirmfoto 2022-01-14 um 16 12 56" src="https://user-images.githubusercontent.com/8232196/149538685-6f6ae7bb-0051-47e5-86e5-d687ebea1f28.png">

**Comment by freben** [comment]
Hm. I wonder what url that is supposed to be.

**Comment by dschwank** [comment]
@freben Just had a short look into that issue - it seems to be related to the [`url` argument](https://github.com/swagger-api/swagger-ui/blob/master/flavors/swagger-ui-react/README.md#url-proptypesstring) of the `SwaggerUI`. If that argument is not set, it will result to be `undefined` in the spec, which will cause the error then.

I haven't had time to go deeper into that issue - I assume that it is connected to the `setTimeout` which we use for initialization, but that's just an assumption.

I created a [small fix](#8940) which mitigates the issue, but I would like to double check / have a deeper look into that issue. Apparently I am on vacation on Monday & Tuesday ✌️, so my answers will be delayed in the next days. 😬
