### ISSUE TITLE
add possibility to download project generated from template as zip

### ISSUE THREAD

**Issue by alaczynski** [backstage/backstage#8914]
## Feature Suggestion

There are cases when git repository should not be created as result of project (component) generation from template.
It will be nice to have possibility to download result of project generation from template as a zip file. Similar idea is implemented by https://start.spring.io/. It gives possibility to download generated project locally and start experiments without messing up company's git repository.

## Possible Implementation

New custom template action, e.g. `publish:zip`.

## Context

Some heavily regulated companies has stron access polices around git repo creation. Current support for publishing to git repo is limited to single token which does not address more complex access setup to git repos (e.g. multi-nested groups in gitlab). This feature could help.

**Comment by freben** [comment]
Sure, that could be achieved with an action fairly easily. The file would have to be stored somewhere though; the workspace and runner as such want to be cleaned up and destroyed immediately after the run completes.

**Comment by benjdlambert** [comment]
Yep, which maybe we wouldn't always want to do with `publish:bucket` action as it could be that you want to persist that.

We could have the `zip` stored locally on the scaffolding machine, but then we have problem that when you go to download it, it might not be on the `scaffolder-backend` instance that you're talking to for that request. Little bit against storing these `zip` files in the database too as that just feels a little wrong for this use case, don't really want to give actions access to the database.

I believe that there is TTL settings on /most/ if not all bucket providers, so thinking that we could upload things there return the download zip URL to the frontend, and an option you could pass to the action would be a TTL for it to get cleaned up after like 1 day or whatever you configure in your template manifest.

Does that sounds like a decent approach?

**Comment by alaczynski** [comment]
Pushing to external storage like s3 or ADLS seems more flexible (ADLS also suport TTL https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-expiry).

**Comment by benjdlambert** [comment]
Yep thinking that we shouldn't try to abstract away these things into one `publish:bucket` action, as there's so many options these days that it just doesn't make sense to have one action supporting all these different config values for provider.

Would you like to have a go at implementing a `publish:adls` action with some properties to set TTL? :pray:

**Comment by alaczynski** [comment]
Agree, we should have separate actions for underlying storage (s3, adls, ...). Would you add this in that repository as new build-in action in new plugin? I can try implement `publish:adls` if you can give few hints, e.g. where put put it, which places which be adopted.

**Comment by benjdlambert** [comment]
So I think for now it's fine to include it with the `defaultActions` that you get part of the `scaffolder-backend` plugin. So somewhere alongside the current `publish` actions would be fine for now.

This is where they are stored: https://github.com/backstage/backstage/blob/ce82656901817c2072419b8913f03183d1043c08/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish

If you take a look at the other publish actions, you'll see that they have a lot of commonality with `git` but for this action, think we can skip that all together.

If we take the `publish:github` action as an [example](https://github.com/backstage/backstage/blob/95b369d808a44425ce4fc071c24e0c2cfc26d40e/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts), you want to create something similar.

https://github.com/backstage/backstage/blob/95b369d808a44425ce4fc071c24e0c2cfc26d40e/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts#L35-L44
Here is where we create the factory, and define some dependencies to create the action before anything is run,  these are probably gonna be things like getting config and creating a client with the right project and stuff for azure, maybe worth reaching out to @awanlin or @marleypowell to see if `adls` is something that you can share config values with, would be just a little more work if we couldn't share some of the config between all the azure stuff.


https://github.com/backstage/backstage/blob/95b369d808a44425ce4fc071c24e0c2cfc26d40e/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts#L46-L57
Here's where we define what typescript properties that the action will take for `input`, with the name of the action.


https://github.com/backstage/backstage/blob/95b369d808a44425ce4fc071c24e0c2cfc26d40e/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts#L60-L73
And here is where we translate that typescript stuff, into some nice json schema that will be used to validate the inputs and output of the action. Your inputs and actions are probbaly gonna be really different from anything currently in the `publish` folder, so don't worry if you drift. I guess you're gonna need to collect things like the `project`, `workspace` and maybe `subfolder` or something for `input`, along with taking some other optional options like TTL etc.


Once you've got all that in the action, you should be able to put the thing in the bucket, feel free to use a library to do this if there exists one, and then once thats uploaded with the right options lets generate a download link that we can use as an output as a `string` in the action which will be called something like `downloadPath` or `zipPath`.

Happy to help more, but maybe that's enough to get started at least?

**Comment by alaczynski** [comment]
Thank you for hints. I will do it.

**Comment by awanlin** [comment]
We actually don't use pure Azure just Azure DevOps so I won't be able to help much with this.

I do believe that @marleypowell is using Azure but will leave that to him

**Comment by mufaddal7** [comment]
> We could have the zip stored locally on the scaffolding machine, but then we have problem that when you go to download it, it might not be on the scaffolder-backend instance that you're talking to for that request. 

@benjdlambert We are working on something exactly like this. We created a custom action `zip:download` , this action copies the `ctx.workspacePath` to a new directory. 

For letting the users download it, we have created an API, which zips it, and responds with an attachment. This will act as a download URL 

This is WIP

**Comment by freben** [comment]
Is that directory on the same machine, or on a shared volume of some sort? Just checking if your solution would work when there are multiple backend hosts that autoscale, for example.

**Comment by NishkarshRaj** [comment]
> Is that directory on the same machine, or on a shared volume of some sort? Just checking if your solution would work when there are multiple backend hosts that autoscale, for example.

Collating everything that has been mentioned here, I think the workflow would be:

1. Scaffold repository to a local directory
2. Push this directory to s3
3. Delete the local directory
4. s3 public/internal URL is returned on the UI

**Comment by freben** [comment]
Point 3 will be automatic in a sense, because the scaffolder worker shuts down and its working data is wiped anyway.

**Comment by freben** [comment]
@alaczynski Will you be picking up this task and would like to be assigned on the issue?

**Comment by alaczynski** [comment]
@freben Please assign me to that task. I will implement support for `publish:adls`. Based on that any other storage could be added e.g. `publish:s3`.

**Comment by freben** [comment]
awesome, assigned!

**Comment by benjdlambert** [comment]
For anyone wanting to work on an S3 version, we already have some logic for pushing to S3 part of the techdocs publishers, so could be some re-use there somewhere?

**Comment by tfarooqaltia** [comment]
Any implementation that works?

**Comment by benjdlambert** [comment]
I think this is still being worked on - but if you'd like to help contribute some other actions that would be great 🙏

**Comment by tfarooqaltia** [comment]
If I would like to perform an action to download components directly without uploading them to any platform, any clue how I could do it?

> Sure, that could be achieved with an action fairly easily. The file would have to be stored somewhere though; the workspace and runner as such want to be cleaned up and destroyed immediately after the run completes.

**Comment by benjdlambert** [comment]
hmm - that's going to be pretty difficult for backstage to support, and probably not something that we're going to look at supporting first class just yet either. If you already had a webserver deployed where you were running backstage, you could use the `publish:file` action to copy the contents of the workspace to the `www` directory and then you could navigate to your webserver and download them there as a workaround.

**Comment by cmoulliard** [comment]
As the `publish:file` action is [deprecated](https://github.com/backstage/backstage/blob/30882884a4fe96c78b8ebfc0b7163ad5a1306ba4/docs/releases/v1.6.0-changelog.md#L557), what is then the alternative if there is one to download a file (zip, etc) from the backstage workspace ? 
**NOTE** Using the template editor is not an option

**Comment by benjdlambert** [comment]
@cmoulliard the best approach here would be to create an action that can publish the current workspace to S3 or Google Cloud Storage, or whatever bucket storage service is available to you.
