### ISSUE TITLE
Broken route for /catalog?filters

### ISSUE THREAD

**Issue by kim5566** [backstage/backstage#8929]
visit `/catalog/?filters%5Bkind%5D=component&filters%5Buser%5D=owned` directly from url broken

## Expected Behavior

Click url http://localhost:3000/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned should direct me to my owned entities

## Current Behavior

Click url http://localhost:3000/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned

But redirect me to http://localhost:3000/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all somehow

It works for demo site https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned,

So i suspect it caused by recent changes.

## Possible Solution

I haven't identified the cause yet.

## Steps to Reproduce

1. backstage version is up to date
2. import a catalog-info.yaml that you will own
3.  click `localhost:3000/catalog` --> seems default to show all entities
4. try to change this in App.tx
```
        <Route path="/catalog" element={<CatalogIndexPage initiallySelectedFilter='owned'/>}/>
```
5. click `localhost:3000/catalog`, the above DOES NOT work, still show me ALL entities.
6. view my owned entities directly from url `http://localhost:3000/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned`
7. The above DOES NOT WORK, still redirect me to `http://localhost:3000/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all`
8. The ONLY way to see my owned entitles is click from UI

## Context

Should the OWNED entities shown by default like the demo.backstage.io or at least be possible to set it up? 

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by mtlewis** [comment]
Thanks for reporting @kim5566! Looks like this was introduced in #8220 - specifically [this change](https://github.com/backstage/backstage/pull/8220/files#diff-8b1983e879ad61aae5b465c7e2e9695355be2fa7f4f67a6da61ad53ef8398519R163-R167) to the logic that determines the current filter.
