### ISSUE TITLE
Ability to select specific types to show at Group page

### ISSUE THREAD

**Issue by roylisto** [backstage/backstage#8986]
## Feature Suggestion
Need to filter or select what specific type to show, for example, we want to show the diagram which has `type: team` only.
Or we need to exclude some `type` from the diagram.

Is it possible to add this configuration to the plugin?

## Context
Currently on this diagram https://demo.backstage.io/explore/groups
We show all the data regardless. But sometimes we have another source that contains large sets of data for example from LDAP data. And it will ruin the UI because it would render all the data, imagine if we have 22K data at the moment, it will crash the browser also.

**Comment by mufaddal7** [comment]
We can use `@backstage/plugin-catalog-graph` 

In `EntityPage.tsx` , we have to replace the existing component i.e `EntitySystemDiagramCard`  with `EntityCatalogGraphCard` which will be imported from `@backstage/plugin-catalog-graph` 

You can even create a page by using `CatalogGraphPage` in `App.tsx` , [this page](https://demo.backstage.io/catalog-graph?rootEntityRefs%5B%5D=component%3Adefault%2Fartist-lookup&maxDepth=%E2%88%9E&unidirectional=true&mergeRelations=true&direction=LR&showFilters=true) has various filters , by which you can create different views as per your need

Hope this helps

**Comment by roylisto** [comment]
Thanks, @mufaddal7 , so by that means is to recreate the page on EntityPage.tsx?

**Comment by mufaddal7** [comment]
Add `@backstage/catalog-graph-plugin` as a `dependency` in `packages/app/package.json`

Apply the following changes to the `packages/app/src/components/catalog/EntityPage.tsx` file:

```diff
+ import {
+  Direction,
+  EntityCatalogGraphCard,
+ } from '@backstage/plugin-catalog-graph';
+ import {
+  RELATION_API_CONSUMED_BY,
+  RELATION_API_PROVIDED_BY,
+  RELATION_CONSUMES_API,
+  RELATION_DEPENDENCY_OF,
+  RELATION_DEPENDS_ON,
+  RELATION_HAS_PART,
+  RELATION_PART_OF,
+  RELATION_PROVIDES_API,
+ } from '@backstage/catalog-model';

//systemPage

    <EntityLayout.Route path="/diagram" title="Diagram">
-      <EntitySystemDiagramCard />
+      <EntityCatalogGraphCard
+        variant="gridItem"
+        direction={Direction.TOP_BOTTOM}
+        title="System Diagram"
+        height={700}
+        relations={[
+          RELATION_PART_OF,
+          RELATION_HAS_PART,
+          RELATION_API_CONSUMED_BY,
+          RELATION_API_PROVIDED_BY,
+          RELATION_CONSUMES_API,
+          RELATION_PROVIDES_API,
+          RELATION_DEPENDENCY_OF,
+          RELATION_DEPENDS_ON,
+        ]}
+        unidirectional={false}
+      />
    </EntityLayout.Route>
```

**Comment by Rugvip** [comment]
Thank you for the response @mufaddal7!

Is it alright to close the issue @roylisto?

**Comment by roylisto** [comment]
I am just want to clarify, so by that's mean we don't modify this page https://demo.backstage.io/explore/groups?
but instead, create our own page similar to this page https://demo.backstage.io/explore/groups by using @backstage/plugin-catalog-graph? is that what you mean @mufaddal7?

**Comment by roylisto** [comment]
I am thinking to modify this plugin https://github.com/backstage/backstage/tree/master/plugins/explore, or I can't?

**Comment by mufaddal7** [comment]
Yes, the use case mentioned above can be fulfilled by using @backstage/plugin-catalog-graph

To make Catalog-Graph more accessible you may add it in the sidebar.

**Comment by roylisto** [comment]
Alright thanks @mufaddal7

**Comment by roylisto** [comment]
I am closing the issue @Rugvip
