### ISSUE TITLE
Healthcheck does not exist on @backstage/create-app

### ISSUE THREAD

**Issue by nicolaszein** [backstage/backstage#9009]
On the [Observability Documentation](https://backstage.io/docs/plugins/observability) says that there is a health check endpoint. However, when creating an app with @backstage/create-app this endpoint does not exist.

Looking at the [default app](https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/packages/backend/src/index.ts#L96) it really does not exist.

How can we update the template to the last version?

**Comment by mufaddal7** [comment]
@nicolaszein It only makes sense to use the `/healthcheck` endpoint if we are adding custom logic to it, maybe that's why it's not included in the default app. 

https://github.com/backstage/backstage/blob/ec60bc64a9e2c2d2ee01e2c1dcb3861bb5f210ec/packages/backend-common/src/service/createStatusCheckRouter.ts#L44

**Comment by nicolaszein** [comment]
@mufaddal7 Yeah I understand that. But in my case it is important, I will also check if the database is available for example.

I know I can do it myself but it is not just about the healthcheck. How can I keep my template updated?

**Comment by mufaddal7** [comment]
> how can I keep my template updated?

You can run this command to bump all `@backstage` packages to the latest version:

`yarn backstage-cli versions:bump`

For more details on [keeping backstage updated ](https://backstage.io/docs/getting-started/keeping-backstage-updated)

**Comment by nicolaszein** [comment]
@mufaddal7 thank you for the attention! 😄
