### ISSUE TITLE
Rolling up APIs to system/domain

### ISSUE THREAD

**Issue by jcarres-mdsol** [backstage/backstage#9014]
Unless I am doing something wrong, at the system level I do not see any APIs because I do not define them in my system yaml files. Instead I define them with the components.

I think the correct behaviour would be that they "roll up" so at system level I have a list of APIs within this system. That's not happening to me so I am guessing this is a feature missing. If you agree that should be the behavior.

**Comment by Rugvip** [comment]
Yep, makes sense!

I'll call this a duplicate of #7109 and close this though, better focus the discussion in one place. Particularly https://github.com/backstage/backstage/issues/7109#issuecomment-921203821 presents ideas with some possible ways forward
