### ISSUE TITLE
Periodic catalog database reset?

### ISSUE THREAD

**Issue by leon-vg** [backstage/backstage#9030]
At our company, we use (a slightly changed version of) the `github-discovery` plugin to add entities to Backstage. In some specific cases, we noticed that some issues were introduced in the Backstage 'state':

- An entity was manually deleted (and apparently not picked up anymore by `github-discovery`)
- The main branch of a repo was changed and changes to the entity were not picked up anymore.

Of course specific issues like these could be tackled, but since the catalog is set to `readonly`, we would also be happy with having a periodic reset of the database. Right now that is at least how we fix these kinds of issues.

We were wondering if there is the possibility of a periodic (nightly) reset of the database. I think the ingrediënts are there, but we lack the required knowledge right now.

## Possible Implementation

A combination of the recently added TaskScheduler and some `knex` logic?

Other ideas? Perhaps we are not thinking correctly about this issue. Help is appreciated!

**Comment by Rugvip** [comment]
Feels a bit like we're opening a coconut with a howitzer x)

Before reaching for an automated full reset, I think it's best to uncover and fix any issues with self-healing that we have.

The first issue you mention should hopefully be fixed by #8936, which was part of today's release 🎉 

For the second issue you should be able to switch out the the explicit branch name in the discovery URLs for a `-`, https://backstage.io/docs/integrations/github/discovery. If that isn't working as expected I'd say we should investigate and look for a fix!

**Comment by leon-vg** [comment]
> Feels a bit like we're opening a coconut with a howitzer x)

Lol. In the Netherlands we call this a "paardenmiddel" (horse medicine) 😊.

I totally agree that it is preferred that this sort of behaviour does not surface in the first place.

> For the second issue you should be able to switch out the the explicit branch name in the discovery URLs for a `-`, https://backstage.io/docs/integrations/github/discovery. If that isn't working as expected I'd say we should investigate and look for a fix!

We already use the `-` to refer to the default branch. I'll see if I can reproduce the issue and if so, open up an issue here.

**Comment by leon-vg** [comment]
It seems that the latest version indeed fixes both issues. Note that for the Github main branch change to be picked up, it is necessary to both delete the entity _and_ the corresponding location.

**Comment by Rugvip** [comment]
@leon-vg great!

The rename is a bit tricky to handle completely automatically, as it's a safety mechanism to not allow entities with the same name to override each other. I this case I think we might be able to do a bit better though. If we were able to keep the `-` in the location URL all the way to when we read it on the individual location, then the catalog would consider it to be the same location and it should update immediately.

I'll create a separate issue to cover that and close this one as I don't see any more actions. Let us know if we missed anything and we can re-open.

**Comment by Rugvip** [comment]
Created #9086 for the default branch issue

**Comment by leon-vg** [comment]
Thanks for opening a new issue, @Rugvip. And for the support! Closing this issue is fine by me, since the root causes are fixed  now.
