### ISSUE TITLE
Whitespace in parent folder name causes error when generating api docs.

### ISSUE THREAD

**Issue by lukzerom** [backstage/backstage#9039]
Today, when generating docs ( using `yarn build:api-docs` command)  i found a bug , it took me a while to know what happened. An empty space in parent folder name caused tsc error like below on screen. I would say it's minor but maybe somebody has idea how to fix it fast.

<img width="924" alt="Zrzut ekranu 2022-01-19 o 18 45 07" src="https://user-images.githubusercontent.com/55348672/150185937-e08937f9-2bf5-4973-97e0-9317c042d8c0.png">

And after change folder name everything worked fine. 

 
## Expected Behavior

Empty space in folder parent name should not affect generating docs mechanism,. 

## Current Behavior

Emoty space in parent folder name caused tsc process issue. 

## Steps to Reproduce

1. Create clone version of backstage app and name folder like "open source" with whitespace inside
2. Try to generate docs using `yarn build:api-docs` command
3. Error in console will appear 

## Context

---

## Your Environment

- NodeJS  v14.17.2
- Mac OS Mojave 10.14.6

**Comment by freben** [comment]
Oh interesting, that string is sent directly to [spawnSync](https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options), so it's pretty surprising that escaping could possibly be wrong.

**Comment by Rugvip** [comment]
That is really strange indeed. Perhaps a workaround could be to use a relative path instead, since we're setting the cwd? https://github.com/backstage/backstage/blob/bed2da46afe484667bb2c8e25f89941bd78610c2/scripts/api-extractor.ts#L851

**Comment by freben** [comment]
Or look into using [cross-spawn](https://www.npmjs.com/package/cross-spawn) which tries to address some of the crazy quirks of the regular spawn commands.

https://stackoverflow.com/questions/21356372/node-child-process-spawn-not-working-with-spaces-in-path-on-windows
https://github.com/nodejs/node/issues/7367
