### ISSUE TITLE
catalog: deprecate EntitySystemDiagramCard

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#9060]
## Feature Suggestion

Deprecate `EntitySystemDiagramCard` from `@backstage/plugin-catalog`.

The `@backstage/plugin-catalog-graph` provides a nicer graph card that works for all kinds of entities, `EntityCatalogGraphCard`, so we should use that instead. It's already used in the [example-app](https://github.com/backstage/backstage/blob/bed2da46afe484667bb2c8e25f89941bd78610c2/packages/app/src/components/catalog/EntityPage.tsx#L625), but the [create-app template](https://github.com/backstage/backstage/blob/bed2da46afe484667bb2c8e25f89941bd78610c2/packages/create-app/templates/default-app/packages/app/src/components/catalog/EntityPage.tsx#L305) still uses the older card.

## Possible Implementation

We think this is a good first issue and would be happy if anyone from the community wants to pick this up! ❤️ 

A couple of things need to be done:

  - [x] Mark the `EntitySystemDiagramCard` as `@deprecated` and remove our own usage of it. Provide instructions in a [changeset](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets) for how to switch to the `EntityCatalogGraphCard` instead.
  - [x] Update the `create-app` template and provide a changeset with instruction for how to update existing apps.
  - [x] After at least two releases have gone by since the deprecation, completely remove the `EntitySystemDiagramCard` component. This can be done immediately with a PR that we don't merge until the desired date.

**Comment by eoghanmcilwaine** [comment]
👋  Hey! Eoghan here from Roadie. Mind if I pick this up?

**Comment by Rugvip** [comment]
@eoghanmcilwaine sorry, it was already picked up in #9066 😅

There's actually the last point left though. You could prep the removal PR that we merge in two weeks.

**Comment by eoghanmcilwaine** [comment]
Ah, no worries. Sure, I'll prep that removal PR now 👍

**Comment by Rugvip** [comment]
Alright, now completely removed, thank you both!
