### ISSUE TITLE
[TechDocs] DefaultTechDocsCollator can be unreliable with locally generated docs

### ISSUE THREAD

**Issue by iamEAP** [backstage/backstage#9062]
## Expected Behavior

All TechDocs site content should be indexed by the `DefaultTechDocsCollator`, even when TechDocs is configured for local generation and publishing.

## Current Behavior

When TechDocs is configured for local generation and publishing, documentation sites are only generated when a user attempts to read an entity's documentation.  Those generated files are persisted to disk in an ephemeral directory.

The `DefaultTechDocsCollator` attempts to load `search_index.json` files (generated by `mkdocs`) for each catalog entity that has a `backstage.io/techdocs-ref` annotation.  In the aforementioned TechDocs configuration, there is a possibility that a user has not yet visited a TechDocs site by the time a collator run attempts to load the index.  In such cases, the site is ignored and its content will be missing from the index.

This is exacerbated in common deployment architectures (like running Backstage Backend in a docker container), because the ephemeral directory containing TechDocs will be newly empty with each deployment.

## Possible Solutions

A few possible approaches, some of which may be considered in tandem.

- **Documentation Only**: Document problems with this configuration and recommend workarounds (e.g. setting up TechDocs in the "recommended" way, via CI/CD, or configuring TechDocs to use `memcache` with long TTLs)
- **Explicitly Do Not Support This**: Check configs in the `DefaultTechDocsCollator` and throw an error if a local publisher configuration is provided.
- **Warn on Invalid Config**: Same as above, but merely log a warning.
- **Artificial Results**: In the event a `search_index.json` file can't be found, go ahead and add a single entry for the component that links to the index of the TechDocs site.  In this case, at least the site will be represented in more global search contexts, and as users visit TechDocs sites, search results will become more detailed.
- **Actually try and support this**: Within the `DefaultTechDocsCollator`, when the local publisher is configured, for each entity where a search index cannot be found, trigger a new generation/build for the site via the TechDocs Backend.

**Comment by marct83** [comment]
Was this ever fixed or solved? I'm currently running into this. I'm using PG as database and techdocs local in k8s. Only techdocs that I have opened are showing in the search. All other's don't show. These errors are in the logs. 

{"level":"info","message":"::ffff:127.0.0.1 - - [27/Mar/2023:14:04:29 +0000] \"GET /api/techdocs/static/docs/toolbox/component/toolbox-wifi-worker/search/search_index.json HTTP/1.1\" 404 - \"-\" \"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)\"","service":"backstage","type":"incomingRequest"}
