### ISSUE TITLE
Sidebar closes while in Add Shortcuts dialog

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#9073]
## Expected Behavior

When opening the "Add Shortcut" dialog, the sidebar remain opens

## Current Behavior

When opening the dialog, the sidebar closes leaving the dialog "disconnected"

## Possible Solution

I suspect this regression was caused by this change: https://github.com/backstage/backstage/pull/8455 (cc: @Sarabadu) 

## Steps to Reproduce

https://user-images.githubusercontent.com/6998196/150444144-86211fbf-0476-4487-9c6e-7e45f9ab2142.mov

## Your Environment

- Backstage Release: release-2022-01-20
- NodeJS Version (v14): v14
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 18.04 
- Browser Information: Chrome v95

**Comment by Sarabadu** [comment]
Thanks @kuangp,  the `ignoreChildEvent` had some conflict with MUI popovers focus behavior #9121 should solve the problem
