### ISSUE TITLE
[Plugin] Notification events

### ISSUE THREAD

**Issue by pgraciabernal** [backstage/backstage#9085]
## Summary

Expose a notification section (with notification icon alarm with pending notification to read) to publish pro-actively information to other teams related to updates or new info in your portal like API update o new API published

## Project website (if applicable)

Backstage tool itself

## Context

NA

**Comment by freben** [comment]
See related discussion [here](https://github.com/backstage/backstage/issues/639).

What you asked for is slightly different in terms of the scope of implementation, even though the visual display might have an overlap with that ticket. So maybe there's something that can be done in terms of the frontend parts of this, that at the same time can be extended in the future to support the more advanced backend-driven events and notifications systems.

**Comment by pgraciabernal** [comment]
Thanks Fredrik for your reply. As you mention, this is an overlapping of other discussion, more focused on front-end. I proceed to close this ticket.

Thanks again.
