### ISSUE TITLE
Support default branch syntax in GitHub UrlReader

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#9086]
## Feature Suggestion

The [GitHub discovery](https://backstage.io/docs/integrations/github/discovery) processor currently supports using `-` in place of the branch name to represent the default branch. For example: `https://github.com/myorg/service-*/blob/-/catalog-info.yaml`

The `-` is resolved into the actual name of the default branch by the discovery processor before it creates the child location in the catalog, which will then be used for reading the target YAML. This means that the entity location URL will in the end be set to for example `https://github.com/myorg/service-foo/blob/master/catalog-info.yaml`. This then triggers a conflict if you ever rename the default branch, since for example `https://github.com/myorg/service-foo/blob/main/catalog-info.yaml` is considered a different location. You then need to delete the original entity before the new location is picked up, as discussed in #9030.

I think we can solve this by keeping the `-` in place in the location URL, and instead power up [GithubUrlReader.readUrl](https://github.com/backstage/backstage/blob/80177048d213441936640f30ac3080f4af1742b6/packages/backend-common/src/reading/GithubUrlReader.ts#L86) to support that syntax.

## Possible Implementation

We think this is a good first issue and would be happy if anyone from the community wants to pick this up! ❤️

On the UrlReader side it should be enough to switch out [this](https://github.com/backstage/backstage/blob/38e24db009a50428984103562e21ac3848f39c68/packages/integration/src/github/core.ts#L49) to not pass any `ref` query param if the ref is `'-'`.

In the discovery processor it should be enough to remove [this](https://github.com/backstage/backstage/blob/7ad2b4450af42bfa9994c7f510a7c591ef2a224d/plugins/catalog-backend/src/ingestion/processors/GithubDiscoveryProcessor.ts#L111) logic and pass through the `-` in the URL instead. It is probably best to keep the check that makes sure that the repository has a default branch when using `-` as well.

These are pretty small changes, but we'd want to spend some time verifying that this all works as intended, allowing switching out the default branch and so on. One important thing to verify and possibly work around is to make sure that this doesn't have a negative impact on existing catalogs that currently use GitHub discovery.

## Context

#9030

**Comment by Rugvip** [comment]
Noting that if this all works as expected it could be something to implement for the other discovery providers and discovery processors as well.

**Comment by devth** [comment]
Hi, I'm looking at this issue. Couple questions.

1. Is there a typo in here?

> This means that the entity location URL will in the end be set to for example `https://github.com/myorg/service-foo/blob/master/catalog-info.yaml`. This then triggers a conflict if you ever rename the default branch, since for example `https://github.com/myorg/service-foo/blob/master/catalog-info.yaml` is considered a different location. 

Shouldn't the 2nd url be different than the first, e.g:

```https://github.com/myorg/service-foo/blob/main/catalog-info.yaml```


2. It looks like having `-` in the url prevents `parseGitUrl` from fully parsing the file (`ref`, `filepath` and `filepathtype` are all empty `''`). Example:

```typescript
parseGitUrl('https://github.com/a/b/blob/-/path/to/ref-convention-example.yaml');

// result:
    {
      protocols: [ 'https' ],
      protocol: 'https',
      port: null,
      resource: 'github.com',
      user: '',
      pathname: '/a/b/blob/-/path/to/ref-convention-example.yaml',
      hash: '',
      search: '',
      href: 'https://github.com/a/b/blob/-/path/to/ref-convention-example.yaml',
      query: [Object: null prototype] {},
      token: '',
      toString: [Function (anonymous)],
      source: 'github.com',
      git_suffix: false,
      name: 'blob',
      owner: 'a/b',
      commit: 'path',
      ref: '',
      filepathtype: '',
      filepath: '',
      organization: 'a/b',
      full_name: 'a/b/blob'
    }



```

**Comment by Rugvip** [comment]
@devth good catch, thanks, updated :grin:

And alright thank you for the heads up! Being able to properly parse the URL would be part of implementing this as well then. Can say that we're aiming to move away from `git-url-parse` though (#9095)

**Comment by devth** [comment]
Sounds good! I'll look into the `git-url-parse` issue later. I could wait till that's resolved, or let me know if there's help wanted on that too.

**Comment by shimmieblum** [comment]
Hi, I'm simon and i'm looking to find ways to contribute to backstage.

I was looking at this issue, just wondering if your still planning on doing it @devth cos if not, I thought it may be a good first issue for me. I've had a look at some of the github discovery code so i'd be interested to try an help out with this one? 

do lmk, Thanks!

**Comment by devth** [comment]
Hi @shimmieblum, go for it!

**Comment by jhaals** [comment]
Best of luck @shimmieblum!

**Comment by shimmieblum** [comment]
Thanks!

**Comment by shimmieblum** [comment]
Hi, 1) apologies for the delay

**Comment by shimmieblum** [comment]
Hi, i've submitted a pr for this on my work account: https://github.com/backstage/backstage/pull/11399

**Comment by benjdlambert** [comment]
@shimmieblum did you get a round to looking at this? Otherwise I can re-assign to someone else if they want to pick it up? :pray:

**Comment by pjungermann** [comment]
I work on another change there and getting to what is needed here would be just a minor additional step
