### ISSUE TITLE
Authentication failed, Failed to obtain access token (Github authentication)

### ISSUE THREAD

**Issue by cosmin-constantin-oprea-db** [backstage/backstage#9087]
Github Authentication is not working

## Expected Behavior

Github Authentication should be succesfull

## Current Behavior

I get the error: Authentication failed, Failed to obtain access token. With no other logs.

## Possible Solution

I have no idea, what is going wrong.

## Steps to Reproduce

I follow the exact steps from the official documentation: https://backstage.io/docs/auth/github/provider 

1. Create a github OAuth App with the redirect url to http://localhost:7007/api/auth/github and app url to http://localhost:3000 as it's mentioned in the docs.
2. I add the following configuration as explained in the docs:

<img width="782" alt="Screenshot 2022-01-21 at 13 51 09" src="https://user-images.githubusercontent.com/68911768/150522489-d9b78317-05ba-4317-be51-16576674eede.png">

3. I start the backend with the following command: 
`env  AUTH_GITHUB_CLIENT_ID=xxx AUTH_GITHUB_CLIENT_SECRET=xxx yarn start`
4. I click on the login button, I choose my account and after I get the message from the below picture.

<img width="472" alt="Screenshot 2022-01-21 at 13 45 20" src="https://user-images.githubusercontent.com/68911768/150521789-7c0cc84e-7408-468c-b2a5-3be3443daaf9.png">

## Your Environment

yarn backstage-cli info
yarn run v1.22.17
OS:   Darwin 20.6.0 - darwin/x64
node: v16.13.2

yarn: 1.22.17
cli:  0.11.0 (installed)

Dependencies:
  @backstage/backend-common                                0.10.3
  @backstage/backend-tasks                                 0.1.3
  @backstage/catalog-client                                0.5.4
  @backstage/catalog-model                                 0.9.9
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.11.0
  @backstage/config-loader                                 0.9.2
  @backstage/config                                        0.1.12
  @backstage/errors                                        0.2.0
  @backstage/integration                                   0.7.1
  @backstage/plugin-app-backend                            0.3.21
  @backstage/plugin-auth-backend                           0.6.2
  @backstage/plugin-catalog-backend                        0.20.0
  @backstage/plugin-catalog-common                         0.1.0
  @backstage/plugin-permission-common                      0.3.1
  @backstage/plugin-permission-node                        0.3.0
  @backstage/plugin-proxy-backend                          0.2.15
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.8
  @backstage/plugin-scaffolder-backend                     0.15.20
  @backstage/plugin-scaffolder-common                      0.1.2
  @backstage/plugin-search-backend-node                    0.4.4
  @backstage/plugin-search-backend                         0.3.0
  @backstage/plugin-techdocs-backend                       0.12.3
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.11.3
  @backstage/types                                         0.1.1`

**Comment by Rugvip** [comment]
I think a common cause of that error is if the client ID or client secret is incorrect. I'd say double check that both of those are set correctly, making sure you didn't switch them around, add whitespace, etc.

**Comment by NicolasGras** [comment]
I am new in Backstage and I have the same error.
Has this issue been solved? 
If not, can this issue be reopened?

**Comment by tesharp** [comment]
In case anyone else struggle with this another cause can simply be that `github.com` is blocked by firewall. Had opened `api.github.com` in firewall, but not `github.com`. There was no good error message indicating that was the problem though.

**Comment by Jamstah** [comment]
Is there a good way to enable logs to identify the cause of this issue?

**Comment by G-man83** [comment]
> Is there a good way to enable logs to identify the cause of this issue?

@Jamstah here is some "tips" at least 😊 : https://backstage.io/docs/auth/troubleshooting/#stepping-through-authentication-manually

**Comment by joxondavis** [comment]
It may help for others. I am able to resolve 'Failed to obtain access token' by setting up proxy service and configuration mentioned here (I used Alternatives to global-agent )https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md
Learning points:
1) Internet connectivity is required for github (even for enterprise )authentication (In corporate network, this need to be managed using proxy)
2) Need to some tweaks as below for  Alternatives to global-agent(Location: packages/backend/src/index.ts)

# packages/backend/src/index.ts
import { HttpProxyAgent } from 'http-proxy-agent';
import { HttpsProxyAgent } from 'https-proxy-agent';

if (process.env.HTTP_PROXY) {
  http.globalAgent = new HttpProxyAgent(process.env.HTTP_PROXY);
}

if (process.env.HTTPS_PROXY) {
  https.globalAgent = new HttpsProxyAgent(process.env.HTTPS_PROXY);
}
3) Please set env variable for HTTPS_PROXY (eg: EXPORT HTTPS_PROXY=<Proxy URI>)

**Comment by hesse22** [comment]
@joxondavis did you encounter any issues while adding this code into your backstage app? I am facing similar issues and i assume they're also caused by the corporate proxy. For example i have static urls pointing to files in GitHub Repositories, which cannot be fetched because i get an error ECONNREFUSED.

So i implemented the very same logic you described. But on the virtual machine i get a 503 Status code for internal backstage services, as for example "Collating documents for techdocs failed: ResponseError: Request failed with 503 Service Unavailable documentType=techdocs"

**Comment by VladKay** [comment]
@hesse22 I had a very similar issue a few days ago. After spending several hours debugging, I discovered that the code snippet shared by @joxondavis (see message above) causes all HTTP and HTTPS requests to be routed through the proxy URL.

If you filter the requests and apply the proxying only to external services, internal Backstage services will continue to function correctly.

A simple implementation might look like this:
```
import { ProxyAgent, ProxyAgentOptions } from 'proxy-agent';
import http from 'http';
import https from 'https';

const proxyUrl = 'your-proxy-url';
# define Your domains for the proxy
const proxiedDomains = ['github.com'];

function shouldUseProxy(url: string): boolean {
  return proxiedDomains.some(domain => url.includes(domain));
}

const options: ProxyAgentOptions = {
  httpAgent: new http.Agent({ keepAlive: true }),
  getProxyForUrl: (url) => {
    console.log("URL: "+url);
    if (shouldUseProxy(url)) {
      console.log(`Proxy requested for: ${url}`);
      return proxyUrl;
    } else {
      return url;
    }
  },
};

https.globalAgent = new ProxyAgent(options);
http.globalAgent = new ProxyAgent(options);
```

Please also refer to the official guidance on authenticating with **Azure** when working on localhost.
You'll need to install the Azure Resource VS Code extension or use the Azure CLI to enable token forwarding from Azure to your local environment.

More information is available here: https://backstage.io/docs/integrations/azure/org
