### ISSUE TITLE
Documentation requires updating on port for backend api

### ISSUE THREAD

**Issue by alessioerosferri** [backstage/backstage#9088]
The auth with github documented at this page points to an api running on 7007 but actually it is 7000. Changing the url passed to the App fixes my login.

## Expected Behavior

Login should work via github

## Current Behavior

It doesn't work 

## Possible Solution

Already highlighted above

## Steps to Reproduce

Follow the tutorial at page https://backstage.io/docs/getting-started/configuration#setting-up-authentication

## Context
N/A

## Your Environment

N/A

- NodeJS Version (v16):
- MacOS Catalina
- Browser Information: Safari and Chrome

**Comment by Rugvip** [comment]
We [switched away from using 7000](https://github.com/backstage/backstage/blob/master/packages/create-app/CHANGELOG.md#patch-changes-8) because of conflicts on MacOS, so 7007 is the correct port. Where is the reference to port 7000? Is it in a project you set up recently?

**Comment by alessioerosferri** [comment]
Yes, I followed the tutorial with npx @backstage/create-app and by default the configuration points to port 7000

**Comment by Rugvip** [comment]
Hmm, tried a `npx @backstage/create-app` just now and I end up with a config that points to 7007.

What do you get if you check the version of create-app?

```sh
npx @backstage/create-app --version
```

**Comment by alessioerosferri** [comment]
0.4.14

**Comment by Rugvip** [comment]
Well that's the latest one O_o, very strange if you're seeing port 7000 there. Could you double check and point to where it shows up in that case?

**Comment by alessioerosferri** [comment]
I reran the command and it pointed me to port 7007. As I am using NVM, I guess I must have used a stale nodejs version with the backstage create app package a bit outdated and that still used 7000. Thanks for your help!
