### ISSUE TITLE
Link to Upgrade Helper in Releases

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#9090]
## Feature Suggestion

Would it be possible to include a link to the upgrade helper in the release notes for each new Release?

## Possible Implementation

We could put the link right under the release name before all the release notes something like this:

![image](https://user-images.githubusercontent.com/67169551/150538759-58e514f4-1292-4770-84cf-adf2e87a5876.png)

The link could be setup so that it automatically shows the previous release and the next release, perhaps like this:

https://backstage.github.io/upgrade-helper/?from=0.4.11&to=0.4.12

## Context

When upgrading there are always a few manual changes or the release notes are a little vague, not a big deal. But this does lead to searching through the code to view what specifically changed. Having the link to the Upgrade Helper like this will raise visibility of the tool and make it easier for people to upgrade as they will have the two most helpful piece of information at their hands

**Comment by jhaals** [comment]
Awesome idea, would you like to help out @awanlin? The workflow and generate release script is probably the place to start if you're interested.

**Comment by awanlin** [comment]
Sure, would be nice to learn this area better. Can you point me to the script? Also, I have two other PRs active that I'd like to finish up first, I plan to tackle the suggestion for those on Friday, guess that's tomorrow ;)

**Comment by jhaals** [comment]
Sorry for the delay Andrew, I hope you've been busy with other things.

The text that goes into the GitHub release is picked up from the last commit in the git tag, all of that including publishing the Github release is part of the [create-github-release](https://github.com/backstage/backstage/blob/master/scripts/create-github-release.js#L201) script.

It's executed here for some additional context https://github.com/backstage/backstage/blob/master/.github/workflows/deploy_packages.yml#L216

My suggestion is that we prepend a message about the upgrade helper in `create-github-release.js`

**Comment by awanlin** [comment]
No worries @jhaals I have been busy with other things 😉   I'll probably take a closer look at this on Friday, thanks for pointing me in the right direction 👍

**Comment by awanlin** [comment]
This would still be great to have, just haven't had the cycles to work on this

**Comment by awanlin** [comment]
Took a look at this again over the weekend and things have changes a lot since I made the suggestion.

There are now two ways this gets created: by hand from my understanding for `main` releases and then by automation for `next` releases.

I'm wondering if I should be adding the link at this point: https://github.com/backstage/backstage/blob/358aed614926b2af83e70a953a8e6818a9da143d/scripts/create-github-release.js#L157

Or if it should be higher up in the process, I was thinking here: https://github.com/backstage/backstage/blob/358aed614926b2af83e70a953a8e6818a9da143d/.github/workflows/sync_version-packages.yml#L19

But for the life of me I can't figure out where the code for `backstage/changesets-action@v2` lives

Any suggestions @jhaals or maybe @Rugvip?

**Comment by Rugvip** [comment]
@awanlin yeah it's a bit hidden 😅, GitHub Actions use the format `<org>/<repo>[/<path>]`, so it's over in the `changesets-action` repo. Actual code for generating the release notes is here: https://github.com/backstage/changesets-action/blob/254e41bb3aa2e9a00e32313596986533aca30175/src/run.ts#L243-L251

**Comment by awanlin** [comment]
Alright, took a swing at this. Seems 99% of what I need is there BUT the value of the previous release. I thought I could use the `octokit` here - https://github.com/backstage/changesets-action/blob/254e41bb3aa2e9a00e32313596986533aca30175/src/run.ts#L195 - to get the latest release but that's giving me errors. @Rugvip does this seem like a reasonable direction to be going? Also is there any way to run this to see the output?

**Comment by awanlin** [comment]
@Rugvip thanks for the tip, that made this pretty easy. I have a PR with the change ready for review: https://github.com/backstage/changesets-action/pull/3.
