### ISSUE TITLE
Not able to scroll on page after 0.8.5 @backstage/component upgrade

### ISSUE THREAD

**Issue by HChenCBRE** [backstage/backstage#9093]
Not able to scroll on page after 0.8.5 @backstage/component upgrade, seem like a change in the height value (from 100vh to 100%) in the Page component.

## Expected Behavior

Not able to scroll on page after 0.8.5 @backstage/component upgrade, seem like a change in the height value (from 100vh to 100%) in the Page component. issue resolved after downgrade to 0.8.4

## Current Behavior

 the height value (from 100vh to 100%) in the Page component.

## Possible Solution

Still trying to figure out the exact cause

## Context

Page component is not scrollable

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10
- Browser Information: all browsers(edge, chrome and firefox)

**Comment by tudi2d** [comment]
thanks for reporting this issue - I will fix it! sorry for any caused incovenience! :)
