### ISSUE TITLE
@backstage/plugin-gcp-projects react-router package error

### ISSUE THREAD

**Issue by PottierAlexis** [backstage/backstage#9097]
The plugin `@backstage/plugin-gcp-projects` is not working and display an error.

## Expected Behavior

The GcpProjectsPage should display properly.

## Current Behavior

The GcpProjectsPage component return the error:
`[ProxyFacade] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>`
<img width="1668" alt="Capture d’écran 2022-01-21 à 17 11 13" src="https://user-images.githubusercontent.com/48247439/150570145-11746221-e028-44eb-8244-1b6cc5554e9c.png">

## Possible Solution

Change `@backstage/plugin-gcp-projects` package `react-router-dom` version to 6.2.1

## Steps to Reproduce

1. Create a new project with:
`npx @backstage/create-app`

2. Install the plugin '@backstage/plugin-gcp-projects' with:
`yarn add @backstage/plugin-gcp-projects`

3. Add the following code in App.tsx
`import { GcpProjectsPage } from '@backstage/plugin-gcp-projects';`
`<FlatRoutes>
   ...
   <Route path="/gcp-projects" element={<GcpProjectsPage />} />
   ...
</FlatRoutes>`

4. Try accessing the `/gcp-projects` route

## Context

Can't use the plugin `@backstage/plugin-gcp-projects` with `@backstage/cli`

## Your Environment
`OS:   Darwin 20.5.0 - darwin/x64
node: v16.13.0
yarn: 1.22.10
cli:  0.12.0 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.5
  @backstage/backend-common                                0.10.4
  @backstage/backend-tasks                                 0.1.4
  @backstage/catalog-client                                0.5.5
  @backstage/catalog-model                                 0.9.10
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.12.0
  @backstage/config-loader                                 0.9.3
  @backstage/config                                        0.1.13
  @backstage/core-app-api                                  0.5.0
  @backstage/core-components                               0.8.5
  @backstage/core-plugin-api                               0.6.0
  @backstage/errors                                        0.2.0
  @backstage/integration-react                             0.1.19
  @backstage/integration                                   0.7.2
  @backstage/plugin-api-docs                               0.7.0
  @backstage/plugin-app-backend                            0.3.22
  @backstage/plugin-auth-backend                           0.7.0
  @backstage/plugin-catalog-backend                        0.21.0
  @backstage/plugin-catalog-common                         0.1.1
  @backstage/plugin-catalog-import                         0.7.10
  @backstage/plugin-catalog-react                          0.6.12
  @backstage/plugin-catalog                                0.7.9
  @backstage/plugin-gcp-projects                           0.3.14
  @backstage/plugin-github-actions                         0.4.32
  @backstage/plugin-org                                    0.4.0
  @backstage/plugin-permission-common                      0.4.0
  @backstage/plugin-permission-node                        0.4.0
  @backstage/plugin-permission-react                       0.3.0
  @backstage/plugin-proxy-backend                          0.2.16
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.9
  @backstage/plugin-scaffolder-backend                     0.15.21
  @backstage/plugin-scaffolder-common                      0.1.3
  @backstage/plugin-scaffolder                             0.12.0
  @backstage/plugin-search-backend-node                    0.4.4
  @backstage/plugin-search-backend                         0.3.1
  @backstage/plugin-search                                 0.5.6
  @backstage/plugin-tech-radar                             0.5.3
  @backstage/plugin-techdocs-backend                       0.13.0
  @backstage/plugin-techdocs                               0.13.0
  @backstage/plugin-user-settings                          0.3.17
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.11.4
  @backstage/test-utils                                    0.2.3
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1
✨  Done in 1.50s.`

**Comment by Rugvip** [comment]
Thank you for reporting! Turns out the package version wasn't being pinned correctly, #9117

A workaround for now is to manually pin the version by changing the following in `yarn.lock`:

```
react-router-dom@6.0.0-beta.0:
  version "6.0.0-beta.0"
  resolved "https://registry.yarnpkg.com/react-router-dom/-/react-router-dom-6.0.0-beta.0.tgz#9dcc8555365f22f7fbd09f26b6b82543f3eb97d6"
  integrity sha512-36yNNGMT8RB9FRPL9nKJi6HKDkgOakU+o/2hHpSzR6e37gN70MpOU6QQlmif4oAWWBwjyGc3ZNOMFCsFuHUY5w==
  dependencies:
    prop-types "^15.7.2"
    react-router "6.0.0-beta.0"

react-router-dom@^6.0.0-beta.0:
  version "6.2.1"
  resolved "https://registry.yarnpkg.com/react-router-dom/-/react-router-dom-6.2.1.tgz#32ec81829152fbb8a7b045bf593a22eadf019bec"
  integrity sha512-I6Zax+/TH/cZMDpj3/4Fl2eaNdcvoxxHoH1tYOREsQ22OKDYofGebrNm6CTPUcvLvZm63NL/vzCYdjf9CUhqmA==
  dependencies:
    history "^5.2.0"
    react-router "6.2.1"
```

To this:

```
react-router-dom@6.0.0-beta.0, react-router-dom@^6.0.0-beta.0:
  version "6.0.0-beta.0"
  resolved "https://registry.yarnpkg.com/react-router-dom/-/react-router-dom-6.0.0-beta.0.tgz#9dcc8555365f22f7fbd09f26b6b82543f3eb97d6"
  integrity sha512-36yNNGMT8RB9FRPL9nKJi6HKDkgOakU+o/2hHpSzR6e37gN70MpOU6QQlmif4oAWWBwjyGc3ZNOMFCsFuHUY5w==
  dependencies:
    prop-types "^15.7.2"
    react-router "6.0.0-beta.0"
```
