### ISSUE TITLE
Add rule 'delete entity' to plugin-catalog-backend

### ISSUE THREAD

**Issue by lqlamTMA** [backstage/backstage#9132]
Hi admin,

We have been using the catalog-backend plugin's rules and have been digging into the catalog-backend plugin's router lines of code Currently, they haven't been authorized when we UNREGISTER LOCATION or DELETE ENTITY
UI:
![image](https://user-images.githubusercontent.com/29789620/150747983-ba27c2fc-f7db-42e6-803d-5a52783fe172.png)
Code:
![image](https://user-images.githubusercontent.com/29789620/150756739-3c1053aa-b77a-4f77-bd16-3a8e16f9e595.png)
![image](https://user-images.githubusercontent.com/29789620/150756787-77372efb-e7e8-422e-a0fb-3ba7f1955883.png)

Why are there no rules for UNREGISTER LOCATION and DELETE ENTITY?
If they will be added to the feature, How long will there be rules for UNREGISTER LOCATION or DELETE ENTITY?
Because we would like to use them for our project.

Thanks,
Lam Ly.

**Comment by mtlewis** [comment]
Hi @lqlamTMA! Firstly, I do want to highlight that the integration of the permissions framework in the catalog is brand new, and we don't yet recommend that folks use the permission backend in their Backstage instance. Calls to the authorize method in the permission client are starting to land in various parts of Backstage, but [it's a no-op](https://github.com/backstage/backstage/blob/master/plugins/permission-common/src/PermissionClient.ts#L109) when permissions framework is disabled.

That said, feedback is still totally welcome on the permissions framework and integrations! To answer your question, you can find the authorization call associated with unregistering locations [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/AuthorizedLocationService.ts#L101), and the one for entity deletion [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/AuthorizedEntitiesCatalog.ts#L79).

**Comment by lqlamTMA** [comment]
Thanks @mtlewis. I will close this issue
