### ISSUE TITLE
[RFC] Catalog Model Introspection API

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#9139]
**Status:** Open for comments

## Need

There are several different places where we would like to know what entities stored in the catalog may look like. Things like

- What are the available entity kinds?
- What types of components and resources exist?
- What lifecycle fields should we expect for components?
- What additional metadata fields have been defined that we would like to filter the catalog page by?

The most important place where we need this information is the catalog index page. The way we currently do this is to fetch all entities in the catalog and then compute the possible fields client-side. This doesn't scale, and it doesn't work if we enforce pagination in the catalog either #5921. 

Another place where this has popped up is for scaffolder field extensions, for example #8667 and #9066. There's also the catalog-graph plugin, which requests like #7764 and #8986, as well as the fact that it currently fetches all entities just like the catalog index page.

## Proposal

Let's add an API that is able to answer the above questions, and more. While adding an endpoint for this to the catalog backend may be desirable in the long run, I propose that we start by adding a frontend API only. The default implementation of the API can do what we already do in many places - list all entities in the catalog. Simply by adding that API I think we can already make things a lot more efficient, since we'll then have a place to cache the information and avoid duplicate fetching.

Once the API is in place, it will likely be quite easy to override it with a custom implementation as well, and depending on the needs of each organization you may just simply use a list of hardcoded values as the implementation. That ofc makes things a lot more effective and lets us enforce pagination of catalog entities. After some time we can then investigate if it's worth adding an introspection endpoint to the catalog backend itself. Who knows, it might be that hardcoded values are just fine, or that we could power it via the search backend instead for example.

I'm not gonna suggest the full API in this RFC, since I think that requires further investigation and is going to be a substantial part of the effort to actually implement this. Here are some mockups for possible directions though:

```ts
export interface CatalogIntrospectionApi {
  getAvailableEntityKinds(): Promise<EntityKindInfo[]>;
  getMetadataFacets(): Promise<MetadataFacets>;
  getSpecFacets(kind: string): Promise<SpecFacets>;
}

export const catalogIntrospectionApiRef = createApiRef<CatalogIntrospectionApi>(...);
```

or perhaps something like this

```ts
export interface GetAvailableFieldValuesOptions {
  fields: string[] // ['spec.type', 'kind', ...etc]
  kinds: string[] // The kinds that we are interested in
}

export interface EntityShapeApi {
  getAvailableFieldValues(kinds: GetAvailableFieldValuesOptions): Promise<FieldByKind[]>;
}

export const entityShapeApiRef = createApiRef<EntityShapeApi>(...);
```

I didn't spend particularly much brainpower on these :grin: Just some examples to get going.

If there's anyone that wants to pick up this work I think the best starting point would be to investigate and list out all existing places that we're inspecting catalog data, as well as feature requests like the ones above. Once we've got that knowledge summarized it's likely a lot simpler to experiment and design an API around that. We're of course also happy to help out as needed.

## Alternatives

We could go straight for a backend endpoint instead of making this a frontend-only API. I think experimentation is going to be simpler in the frontend though, and I'm not sure we will even want a dedicated endpoint for this in the catalog in the long run. It's likely to add a lot of complexity to the catalog backend, and may be better served by the search backend. Regardless of where the backend implementation takes us I think we'll always want a frontend API for this, so that's why I'm proposing that we start there.

## Risks

I think a big risk - almost a certainty - is that we'll get the API wrong the first time. I propose we start of by marking it as `@alpha` and use the new release stage separation to only make it available via `@backstage/catalog-react/alpha` (or whatever package ends up owning this API).

**Comment by freben** [comment]
Throwing my suggestion into the mix:

```ts
getFacets(
  // intentionally exactly the same filter ability as getEntities
  // this is applied before the facet calculation as a pre-filter
  filter: CatalogEntitiesRequest['filter'],
  // e.g. ['metadata.tags', 'spec.type']
  facets: string[],
): Promise<Record<string, FacetInfo>>
```

**Comment by lalit774** [comment]
Currently, I focus on one problem for API Catalog. Table is super slow. Is there any way to reduce the download content.

In API Catalog, It download all(1637) api.json files and we don't search inside the json file as per my understanding.

can we do If user click on API Name( or option to choose related content download: by true/false by column) , Then only it will download the api.json file. I believe, it will improve the performance issue.

Total records: 1637, Display field 5.

![image](https://user-images.githubusercontent.com/225961/166958954-8bd41e94-8456-493e-9faf-11fe80ff678a.png)
