### ISSUE TITLE
Need More Jest Configuration Documentation

### ISSUE THREAD

**Issue by DavidZemon** [backstage/backstage#9147]
## Feature Suggestion

https://backstage.io/docs/plugins/testing#running-tests has extensive documentation on generic unit testing principles, but it seems to be severely lacking documentation on Backstage's Jest configuration and how to modify it. Can that be added? For instance, if I want to add jest-extended, I'm not sure how to do that. If I add something the `jest` property of `package.json`, will it work? Will it override the default Backstage jest configuration?

Some transparency in how it is currently configured and how it can/should be modified would help a lot.

## Context

I'm trying to make jest-extended available and, in the future, maybe some of my own custom assertions.

**Comment by jhaals** [comment]
Hi David, we have this docs section describing how to modify the jest configuration, see https://backstage.io/docs/local-dev/cli-build-system#jest-configuration

**Comment by DavidZemon** [comment]
Ah, that's great. Has exactly what I was hoping to find. Thank you.

Could you maybe include a reference to this CLI documentation in the /docs/plugins/testing page that I originally referenced? I can't be the only one that had trouble finding this info.

**Comment by jhaals** [comment]
Glad it helped! We have planned to rewrite some of these docs to be more of a getting started guide for new plugins. A reference sounds like a good idea in any case, would you be willing to help out and add it to the documentation?

**Comment by shailendra-asc** [comment]
Greetings all, I want to replicate the jest setup that is available in backstage. what is the equivalent jest.config.js file would be.
