### ISSUE TITLE
[Plugin] plugin-github-webhook

### ISSUE THREAD

**Issue by chicoribas** [backstage/backstage#9161]
## Summary

There are many users with the rate limit problem using github as source of catalog. The polling strategy is very efficient, but its easy to reach the hard limits of github. Furthermore, the actual solution is increase the refresh interval, turning the catalog data unsynchronized. 

## Context

Build an plugin that exposes an api route to receive github webhook events and  update the catalog in real time. Basically three github events would be received:
- push: to update catalog if an yaml file is included on some commit of this push.
- team: to update groups
- organization: to update members

I`ve been working on a API that receive those webhooks and updates backstage catalog using the Catalog API. It would be easy to bring that logic to a backstage plugin.

**Comment by jhaals** [comment]
Hi @chicoribas,

Yes, refreshing entities based on events like webhooks is definitely something that has been on the mental roadmap of the maintainer team for a long time. It's been requested/discussed in the past but I'm struggling to find any references. We'd want a somewhat generic system receiving these events as there are likely going to be events from other systems/providers that we would like to support. This is work is going to require some design proposal in form of an RFC as it's going to introduce some new integrations points to the catalog.

It would be interesting to know more about the hard limits you are currently hitting. Are your locations registered one by one or are you using a discovery processor? What problems are you seeing at this point? Getting rate limited by the catalog should be less of a problem know as requests are cached and subsequent requests use etags which does not count towards the quota

**Comment by benkeil** [comment]
The feature already exists (https://github.com/backstage/backstage/pull/13931).
If you use events, does the `CatalogBuilder` still need to poll?

**Comment by freben** [comment]
Indeed, deleting this issue in favor of the events system
