### ISSUE TITLE
Search Engine Postgres Can't Index Big Records of Entitities

### ISSUE THREAD

**Issue by dehamzah** [backstage/backstage#9178]
We were switching to Postgres Search Engine from LunrJS Search Engine because LunrJS is consuming high memory usage, we had around 40k entities across kind and previously LunrJS search engine can index all of this. After switching to Postgres Search Engine we realized that only ~24k records were indexed, thus resulting in limited search results found.

## Expected Behavior

Postgres Search Engine should be able to index all the entity records.

## Current Behavior

Postgres Search Engine can only able to index around ~24k records.

## Possible Solution

Maybe some enhancement in how to get the entities or how to index big records. For the longer term, maybe need to separate this process out from backend service that serves the API, doing some queueing when indexing the documents.
https://github.com/backstage/backstage/blob/9c8ea7e24e49a090050c227288db950217e76ed9/plugins/search-backend-node/src/IndexBuilder.ts#L115

In here it's calling get all entities 2 times one for Catalog and one for TechDocs. Imagine it's querying a 40k records in single call and iterate it 2 times.
https://github.com/backstage/backstage/blob/2a320c21b4aadd1b7739d76da8d783b62b48f585/plugins/catalog-backend/src/search/DefaultCatalogCollator.ts#L94

https://github.com/backstage/backstage/blob/9255e143099beaabbea637c1c51c69b7d6bfe0ef/plugins/search-backend-module-pg/src/PgSearchEngine/PgSearchEngine.ts#L66

https://github.com/backstage/backstage/blob/2a320c21b4aadd1b7739d76da8d783b62b48f585/plugins/techdocs-backend/src/search/DefaultTechDocsCollator.ts#L98

A temporary solution for me was limiting total documents we index, but this is not a desirable outcome.

## Steps to Reproduce

1. Import more than 30k entities into the catalog
2. Use postgres as the backend search engine
3. Wait some time to let the engine index the catalog
4. See table `documents` in db `backstage_plugin_search`

## Context

Using the default LunrJS search engine was not suitable for production since it's using high memory usage for big datasets, moving to the Postgres search engine was a gradual step before moving to ElasticSearch. The indexing should can handle big datasets for this search engine.

## Your Environment

```
OS:   Darwin 20.6.0 - darwin/x64
node: v14.18.1
yarn: 1.22.17
cli:  0.11.0 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.4
  @backstage/backend-common                                0.10.3
  @backstage/backend-tasks                                 0.1.3
  @backstage/catalog-client                                0.5.4
  @backstage/catalog-model                                 0.9.9
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.11.0
  @backstage/config-loader                                 0.9.2
  @backstage/config                                        0.1.12
  @backstage/core-app-api                                  0.4.0
  @backstage/core-components                               0.8.4
  @backstage/core-plugin-api                               0.5.0
  @backstage/errors                                        0.2.0
  @backstage/integration-react                             0.1.18
  @backstage/integration                                   0.7.1
  @backstage/plugin-api-docs                               0.6.22
  @backstage/plugin-app-backend                            0.3.21
  @backstage/plugin-auth-backend                           0.6.2
  @backstage/plugin-catalog-backend-module-ldap            0.3.9
  @backstage/plugin-catalog-backend                        0.20.0
  @backstage/plugin-catalog-common                         0.1.0
  @backstage/plugin-catalog-graph                          0.2.6
  @backstage/plugin-catalog-import                         0.7.9
  @backstage/plugin-catalog-react                          0.6.11
  @backstage/plugin-catalog                                0.7.8
  @backstage/plugin-explore-react                          0.0.10
  @backstage/plugin-explore                                0.3.25
  @backstage/plugin-kubernetes-backend                     0.4.3
  @backstage/plugin-kubernetes-common                      0.2.1
  @backstage/plugin-kubernetes                             0.5.4
  @backstage/plugin-org                                    0.3.34
  @backstage/plugin-pagerduty                              0.3.22
  @backstage/plugin-permission-common                      0.3.1
  @backstage/plugin-permission-node                        0.3.0
  @backstage/plugin-permission-react                       0.2.2
  @backstage/plugin-proxy-backend                          0.2.15
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.8
  @backstage/plugin-scaffolder-backend                     0.15.20
  @backstage/plugin-scaffolder-common                      0.1.2
  @backstage/plugin-scaffolder                             0.11.18
  @backstage/plugin-search-backend-module-pg               0.2.3
  @backstage/plugin-search-backend-node                    0.4.4
  @backstage/plugin-search-backend                         0.3.0
  @backstage/plugin-search                                 0.5.5
  @backstage/plugin-shortcuts                              0.1.19
  @backstage/plugin-tech-radar                             0.5.2
  @backstage/plugin-techdocs-backend                       0.12.3
  @backstage/plugin-techdocs                               0.12.14
  @backstage/plugin-user-settings                          0.3.16
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.11.3
  @backstage/test-utils                                    0.2.2
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1
```

**Comment by dehamzah** [comment]
Thank you for merging this PR! https://github.com/backstage/backstage/pull/7239

I think it still not solving my problem here. I found interesting logs:

```
[2m2022-03-11T08:24:19.499Z[22m [34msearch[39m [31merror[39m Collating documents for software-catalog failed: error: delete from "documents" where "type" = $1 and "hash" not in (select "hash" from "documents_to_insert") - canceling statement due to statement timeout [36mtype[39m=plugin
...
[2m2022-03-14T10:29:22.045Z[22m [34msearch[39m [32minfo[39m Collating documents for software-catalog succeeded [36mtype[39m=plugin
...
[2m2022-03-14T10:30:41.144Z[22m [34msearch[39m [31merror[39m Collating documents for techdocs failed: error: delete from "documents" where "type" = $1 and "hash" not in (select "hash" from "documents_to_insert") - canceling statement due to statement timeout [36mtype[39m=plugin
```

Sometimes it works, sometimes it's not. I think this is what causes the entities is not indexed properly.

I do check my postgres setting parameter `statement_timeout`, previously I had setting in 15s, and increased it to 60s, but no luck. The error still happening.

Any hints or clues to find out the possible cause of this problem? Is anyone know how to enable the raw query logging in backstage?

**Comment by dehamzah** [comment]
There are a lot of updates in the search module related, from the initial issue I created. Here is my updated dependencies used.

```
OS:   Darwin 20.6.0 - darwin/x64
node: v14.18.1
yarn: 1.22.17
cli:  0.15.3 (installed)

Dependencies:
  @backstage/app-defaults                                  0.2.0
  @backstage/backend-common                                0.12.1
  @backstage/backend-tasks                                 0.1.10
  @backstage/catalog-client                                0.8.0
  @backstage/catalog-model                                 0.11.0, 0.12.1
  @backstage/cli-common                                    0.1.8
  @backstage/cli                                           0.15.1
  @backstage/config-loader                                 0.9.6
  @backstage/config                                        0.1.15
  @backstage/core-app-api                                  0.6.0
  @backstage/core-components                               0.9.0, 0.9.1
  @backstage/core-plugin-api                               0.8.0
  @backstage/errors                                        0.2.2
  @backstage/integration-react                             0.1.24
  @backstage/integration                                   0.8.0
  @backstage/plugin-analytics-module-ga                    0.1.13
  @backstage/plugin-api-docs                               0.8.1
  @backstage/plugin-app-backend                            0.3.28
  @backstage/plugin-auth-backend                           0.12.0
  @backstage/plugin-auth-node                              0.1.4
  @backstage/plugin-catalog-backend-module-ldap            0.3.15
  @backstage/plugin-catalog-backend                        0.23.1
  @backstage/plugin-catalog-common                         0.2.1
  @backstage/plugin-catalog-graph                          0.2.13
  @backstage/plugin-catalog-import                         0.8.4
  @backstage/plugin-catalog-react                          0.8.1
  @backstage/plugin-catalog                                0.9.1
  @backstage/plugin-explore-react                          0.0.14
  @backstage/plugin-explore                                0.3.32
  @backstage/plugin-kubernetes-backend                     0.4.11
  @backstage/plugin-kubernetes-common                      0.2.6
  @backstage/plugin-kubernetes                             0.6.1
  @backstage/plugin-org                                    0.5.1
  @backstage/plugin-pagerduty                              0.3.28
  @backstage/plugin-permission-common                      0.5.2
  @backstage/plugin-permission-node                        0.5.3
  @backstage/plugin-permission-react                       0.3.3
  @backstage/plugin-proxy-backend                          0.2.22
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.2.3
  @backstage/plugin-scaffolder-backend                     0.17.3
  @backstage/plugin-scaffolder-common                      0.2.3
  @backstage/plugin-scaffolder                             0.14.0
  @backstage/plugin-search-backend-module-pg               0.3.0
  @backstage/plugin-search-backend-node                    0.5.0
  @backstage/plugin-search-backend                         0.4.6
  @backstage/plugin-search                                 0.7.2
  @backstage/plugin-shortcuts                              0.2.2
  @backstage/plugin-tech-radar                             0.5.8
  @backstage/plugin-techdocs-backend                       0.14.1
  @backstage/plugin-techdocs                               0.15.0
  @backstage/plugin-user-settings                          0.4.0
  @backstage/release-manifests                             0.0.2
  @backstage/search-common                                 0.3.0
  @backstage/techdocs-common                               0.11.11
  @backstage/test-utils                                    0.3.0
  @backstage/theme                                         0.2.15
  @backstage/types                                         0.1.3
  @backstage/version-bridge                                0.1.2
```

After looking again on the log timestamps here:

```
[2m2022-03-11T06:24:08.886Z[22m [34msearch[39m [32minfo[39m Collating documents for software-catalog via DefaultCatalogCollatorFactory [36mtype[39m=plugin
[2m2022-03-11T06:24:08.886Z[22m [34msearch[39m [32minfo[39m Collating documents for techdocs via DefaultTechDocsCollatorFactory [36mtype[39m=plugin
...
[2m2022-03-11T06:24:19.107Z[22m [34msearch[39m [32minfo[39m Collating documents for software-catalog succeeded [36mtype[39m=plugin
...
[2m2022-03-11T06:25:51.729Z[22m [34msearch[39m [31merror[39m Collating documents for techdocs failed: error: delete from "documents" where "type" = $1 and "hash" not in (select "hash" from "documents_to_insert") - canceling statement due to statement timeout [36mtype[39m=plugin
```

The collating process for software-catalog is taking 11s, and for techdocs is taking 1m 43s. That's why increasing the statement_timeout in postgres is not sufficient if it was set for 1 minute. I did increase the statement timeout again and the techdocs are collated successfully.


Looking at this problem, I wonder why the insert process is considered as one statement, is it because we are inserting using [one transaction](https://github.com/backstage/backstage/blob/0d995e0ddd165f99a29649b98fe86019da597850/plugins/search-backend-module-pg/src/PgSearchEngine/PgSearchEngineIndexer.test.ts#L78)?

Is there a way to improve the insert process, since I might hit this problem again with the increased indexed items.

FYI, I am using Postgres 12.7, in the [docs](https://postgresqlco.nf/doc/en/param/statement_timeout/14/) they said

> The timeout is measured from the time a command arrives at the server until it is completed by the server. If multiple SQL statements appear in a single simple-Query message, the timeout is applied to each statement separately. (PostgreSQL versions before 13 usually treated the timeout as applying to the whole query string.) In extended query protocol, the timeout starts running when any query-related message (Parse, Bind, Execute, Describe) arrives, and it is canceled by completion of an Execute or Sync message.

Is this also related with the current issue I am facing?


cc: @iamEAP

**Comment by iamEAP** [comment]
Hmm...  I'm not well-versed on PG transactions, and especially not how knex handles them.  What I'm not sure about is how PG treats the multiple calls we make via knex (including [temp table creation](https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-pg/src/database/DatabaseDocumentStore.ts#L83-L91), [copying](https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-pg/src/database/DatabaseDocumentStore.ts#L97-L107), and [deleting](https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-pg/src/database/DatabaseDocumentStore.ts#L110-L116)) vis-a-vis this line from the docs you linked: `If multiple SQL statements appear in a single simple-Query message, the timeout is applied to each statement separately.`

One possible avenue for improvement might be to expose the batch size as an option when constructing the search engine.  For instance, you'll see that it will insert [100 rows at a time](https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-pg/src/PgSearchEngine/PgSearchEngine.ts#L81), currently, but it's not configurable yet.  The small number there could be the bottleneck on sufficiently large indices.

Also cc'ing @ottosichert who is goalie this week.

**Comment by garyniemen** [comment]
@dehamzah Are you still held up by this?

**Comment by dehamzah** [comment]
We still blocked with this, we are trying to upgrade our Postgres version to 14 that might be solve our problem here, we will share our results here after the testing is done.

**Comment by dehamzah** [comment]
We have confirmed that after upgrading our Postgres version to 14 the search indexing work seamlessly, now it didn't count the whole indexing process in the transaction as one statement which leads to timeout when using a small statement timeout config.

I think we can close this issue, it was the Postgres engine issue.
