### ISSUE TITLE
Looking for recommendation on making ingestion more resilient to errors

### ISSUE THREAD

**Issue by taras** [backstage/backstage#9186]
# Motivation

Our client's project currently is ingesting data from 8 services with the goal of ingesting from 30+. The team wrote a bunch of ingestors to handle all of these data sources. We are finding that our ingestors are very fragile to the flakiness of services that we content to. The result of this flakiness is usually missing fields in entities that previously had data or orphaned entities that shouldn't be. 

I've been doing some code diving and I found the `cache` argument which I believe could solve my problem. I want to verify my approach and contribute the result to the docs.

## External service is unavailable while processing locations

An example of this use case may be, we have a discovery processor that emits locations. Location processor will read each location to emit entities. Typically, the code will look something like this,

```ts
import { results } from '@backstage/plugin-catalog-backend';

export class MyLocationProcessor implements CatalogProcessor {

async readLocation(location: LocationSpec, _optional: boolean, emit: CatalogProcessorEmit): Promise<boolean> {
    if (location.type !== 'my-location') {
      return false;
    }
    
    const entity = fetch(location.target);

    emit(result.entity(entity));

    return true;
  }
}
```

In this case, if `fetch` fails, the entity will become orphaned ( I believe ). Would the following be a correct way of handling this failure?

```ts
import { results } from '@backstage/plugin-catalog-backend';

export class MyLocationProcessor implements CatalogProcessor {

async readLocation(location, _optional, emit, _parser, cache): Promise<boolean> {
    if (location.type !== 'my-location') {
      return false;
    }

    try {
      const entity = fetch(location.target);
    } catch (e) {
      if (e.statusCode > 400) {
         emit(results.entity(cache.collect()))
         return true;
      }
    }
    
    emit(result.entity(entity));

    return true;
  }
}
```

## External service is unavailable while retrieving a field for an entity as part of entity processing

In this case, we're using `preProcessEntity` to enrich the entity.

```ts
import { results } from '@backstage/plugin-catalog-backend';

export class MyLocationProcessor implements CatalogProcessor {
  preProcessEntity(entity, location, emit, originLocation, cache) {
     if (entity.meta.kind !== 'MyEntity') {
       return entity;
     }
     
     const bio = fetch(`http://external-service.com/bio/${entity.meta.name}`);
     
     entity.spec.profile.bio = bio;
     
     return entity;
  } 
}
```

In this case, if the service fails, we'll end up without `bio` information. Would the following be a correct way of resolving this?

 ```ts
import { results } from '@backstage/plugin-catalog-backend';

export class MyLocationProcessor implements CatalogProcessor {
  preProcessEntity(entity, location, emit, originLocation, cache) {
     if (entity.meta.kind !== 'MyEntity') {
       return entity;
     }
     
     let bio;
     try {
       bio = fetch(`http://external-service.com/bio/${entity.meta.name}`);
     catch (e) {
       bio = cache.get('bio')
     }
     
     entity.spec.profile.bio = bio;
     
     return entity;
  } 
}
```

Thank you for your advice

**Comment by Rugvip** [comment]
> In this case, if `fetch` fails, the entity will become orphaned ( I believe ). Would the following be a correct way of handling this failure?

Yep, it would get orphaned.

The only public methods of the cache are `get` and `set`. Values that are set are available in all subsequent runs, until some other values are set. Explained differently, when you call set you clear out all existing values in the cache and replace them with all the new ones that you set during that run. Calling `set` also has no effect on the values that you can `get` in the existing run, the cache changes don't apply until the next run. This was all a bonus explanation in addition to what you can [find in the docs](https://backstage.io/docs/reference/plugin-catalog-backend.catalogprocessorcache) :grin:

So looking at the example we'd need to change some things. First thing is that it's important to `set` cache values, or they won't ever be stored. I also think it would be best to also fall back to the cached value if the request returns a server error, so that you don't get stuck with entities that have actually been removed, but that all ofc depends on the service you're calling.

It could look something like this:

```ts
import { results } from '@backstage/plugin-catalog-backend';

const CACHE_KEY = 'v1';

export class MyLocationProcessor implements CatalogProcessor {
  async readLocation(
    location: LocationSpec,
    _optional: boolean,
    emit: CatalogProcessorEmit,
    _parser: CatalogProcessorParser,
    cache: CatalogProcessorCache,
  ): Promise<boolean> {
    if (location.type !== 'my-location') {
      return false;
    }

    try {
      const entity = await fetch(location.target);
      cache.set(CACHE_KEY, entity)
      emit(result.entity(entity));
    } catch (e) {
      if (e.statusCode >= 500) {
        const cached = cache.get(CACHE_KEY);
        if (cached) {
          emit(result.entity(cached));
        }
      } else {
        throw e
      }
    }

    return true;
  }
}
```

> In this case, if the service fails, we'll end up without `bio` information. Would the following be a correct way of resolving this?

I'd recommend something similar to what we did above:

```ts
let bio;
try {
  bio = fetch(`http://external-service.com/bio/${entity.meta.name}`);
  cache.set(CACHE_KEY_BIO, bio)
} catch {
  bio = cache.get(CACHE_KEY_BIO)
}
```

Note that setting new cache values has no cost, so don't be afraid to set them on every iteration.

**Comment by taras** [comment]
@Rugvip thank you!

Should this find it's way into the docs somehow?

**Comment by jhaals** [comment]
I wrote this section some time ago https://backstage.io/docs/features/software-catalog/external-integrations#caching-processing-results. Is that something that could have helped? You're more then welcome to PR improvements 🙏

**Comment by taras** [comment]
@jhaals I read this page at some point, but I think I completely forgot about it. Thank you for sharing it. It includes many of the pieces that I was looking for.
