### ISSUE TITLE
Fetch template doesn't preserve unix permissions on files from git index

### ISSUE THREAD

**Issue by erihanse** [backstage/backstage#9198]
When fetching templates in the scaffolder with the fetch:template builtin action it seems like the permissions aren't preserved on the files in the template. This happens when running Backstage in Windows 11. 
## Expected Behavior
Given I add an executable to a template and tell git that it should be executable with `git update-index --chmod=+x gradlew`
When I create an application in Backstage using a template with fetch:template and publish:github builtin actions
Then I can clone this repo and run it with `./gradlew`

## Current Behavior

I get permission denied. I need to `chmod +x gradlew` before I can run it. This seems like an unnecessary step to do after a git clone of the newly created repository.

## Steps to Reproduce

1. Create a template with a file and mark it as executable, either with `chmod +x <file>` or git `update-index --chmod=-x <file>`
2. From within GUI, create an application based on the template
3. Clone the repository that was just created
4. Run the file. You will now get permission denied

## Your Environment

OS:   Windows_NT 10.0.22000 - win32/x64
node: v14.18.1
yarn: 1.22.17
cli:  0.12.0 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.5
  @backstage/backend-common                                0.10.4
  @backstage/backend-tasks                                 0.1.4
  @backstage/catalog-client                                0.5.5
  @backstage/catalog-model                                 0.9.10
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.12.0
  @backstage/config-loader                                 0.9.3
  @backstage/config                                        0.1.13
  @backstage/core-app-api                                  0.5.0
  @backstage/core-components                               0.8.5
  @backstage/core-plugin-api                               0.6.0
  @backstage/errors                                        0.2.0
  @backstage/integration-react                             0.1.19
  @backstage/integration                                   0.7.2
  @backstage/plugin-api-docs                               0.7.0
  @backstage/plugin-app-backend                            0.3.22
  @backstage/plugin-auth-backend                           0.7.0
  @backstage/plugin-catalog-backend                        0.21.0
  @backstage/plugin-catalog-common                         0.1.1
  @backstage/plugin-catalog-import                         0.7.10
  @backstage/plugin-catalog-react                          0.6.12
  @backstage/plugin-catalog                                0.7.9
  @backstage/plugin-github-actions                         0.4.32
  @backstage/plugin-org                                    0.4.0
  @backstage/plugin-permission-common                      0.4.0
  @backstage/plugin-permission-node                        0.4.0
  @backstage/plugin-permission-react                       0.3.0
  @backstage/plugin-proxy-backend                          0.2.16
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.9
  @backstage/plugin-scaffolder-backend                     0.15.21
  @backstage/plugin-scaffolder-common                      0.1.3
  @backstage/plugin-scaffolder                             0.12.0
  @backstage/plugin-search-backend-node                    0.4.4
  @backstage/plugin-search-backend                         0.3.1
  @backstage/plugin-search                                 0.5.6
  @backstage/plugin-tech-radar                             0.5.3
  @backstage/plugin-techdocs-backend                       0.13.0
  @backstage/plugin-techdocs                               0.13.0
  @backstage/plugin-user-settings                          0.3.17
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.11.4
  @backstage/test-utils                                    0.2.3
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1

**Comment by jhaals** [comment]
Is this running in WSL or Windows? I'm guessing this is because the executable bit does not follow over from linux to windows.

**Comment by erihanse** [comment]
Not WSL but Windows. Yes I agree, it does an fs.stat call and I'm guessing that's where it gets lost.

**Comment by jhaals** [comment]
Yeah that's likely the issue. I don't know how to solve it in a good way to be honest. A workaround is running it in WSL but it's perhaps not a preferable option. Do you have any suggestions?

**Comment by erihanse** [comment]
Nope, was wondering how a proper solution would look like myself. In order to do it in a platform agnostic way we would probably have to rely on git's index instead of fs.stat when setting the mode. 

I ended up just doing development in WSL anyway, that works fine for me!
