### ISSUE TITLE
scaffolder: default templates register step fails when description is omitted

### ISSUE THREAD

**Issue by mtlewis** [backstage/backstage#9226]
## Expected Behavior

Since the "description" field in default software-templates like [react-ssr-template](https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml) is optional, I'd expect it to be possible to scaffold a new component from these templates successfully without supplying a description.

## Current Behavior

Currently, omitting the description produces the error below during the register step:

![Screenshot 2022-01-27 at 17 15 38](https://user-images.githubusercontent.com/542836/151526258-13427872-f7af-4589-b6a6-718727c98c80.png)

![Screenshot 2022-01-27 at 17 15 54](https://user-images.githubusercontent.com/542836/151526250-b244a3f9-1bd1-4e76-8854-e2e14a4f71f7.png)

```
12022-01-27T17:15:49.542Z Beginning step Register
22022-01-27T17:15:49.547Z info: Registering https://github.com/mtlewis/test-mtl/tree/master/catalog-info.yaml in the catalog {"timestamp":"2022-01-27T17:15:49.546Z"}
32022-01-27T17:15:49.890Z Error: {"error":{"name":"Error","message":"InputError: Policy check failed; caused by Error: Malformed envelope, /metadata/description should be string","level":"error","service":"backstage","stack":"Error: InputError: Policy check failed; caused by Error: Malformed envelope, /metadata/description should be string\n    at DefaultLocationService.processEntities (webpack-internal:///../../plugins/catalog-backend/src/service/DefaultLocationService.ts:89:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async DefaultLocationService.dryRunCreateLocation (webpack-internal:///../../plugins/catalog-backend/src/service/DefaultLocationService.ts:127:22)\n    at async eval (webpack-internal:///../../plugins/catalog-backend/src/service/createRouter.ts:184:24)"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":500}}
4    at CatalogClient.addLocation (webpack-internal:///../catalog-client/src/CatalogClient.ts:259:13)
5    at runMicrotasks (<anonymous>)
6    at processTicksAndRejections (node:internal/process/task_queues:96:5)
7    at async Object.handler (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/actions/builtin/catalog/register.ts:127:24)
8    at async NunjucksWorkflowRunner.execute (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:277:11)
9    at async TaskWorker.runOneTask (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:113:13)
10    at async eval (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:104:9)
```

## Possible Solution

Seems like we should either update the scaffolder such that registration doesn't fail when description is missing, or update the default templates to make the field required. Not sure which is the right path here, but very happy to contribute the fix once we've discussed it!

**Comment by benjdlambert** [comment]
So testing this out a little bit, it looks like indeed that if a description is not provided, then the templating will no coerce this to a string. I gets left as `null` or `undefined` which makes it all the way to the template like this:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "asd"
  description: 
  annotations:
    github.com/project-slug: blamdemo/asdsafasgasgasgasg123d
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "boxoffice"
  ```

That means that in `json` terms, when submitting to the backend, that this becomes `description: null` which is interesting. As the `catalog` accepts `description: ''` which has all the same noninformation.

Thinking that there's a few ways we could fix this here, @freben @rugvip thought's behind allowing `null` as a description in the policy and is there a reason why it's not supported today? The other solution feels a little bit weird to add some templating logic to go `${{ parameters.description or '' }` just to make the policy happy.

**Comment by freben** [comment]
Hey could the template even contain

```
{% if parameters.description %}
description: ${{ parameters.description }}
{% endif %}
```

**Comment by benjdlambert** [comment]
Yeah we could wrap up the description - maybe that's fine for now. 

I feel that `optional !== null`, even though this could translate to `NULL` in the db somewhere maybe, could get confusing though.

@mtlewis do you wanna wrap up the `descriptions` in the templates like @freben mentioned with the block guard.

**Comment by mtlewis** [comment]
Hey @benjdlambert sorry for the slow reply on this! I gave this suggestion a try, but I actually don't think it's possible. Seems like these templates are parsed as yaml on load, so you can't wrap up individual object keys in nunjucks conditional blocks. 

How about explicitly defaulting the description parameter to `''` in templates?

```
2022-02-09T12:25:23.536Z catalog warn YAML error at url:https://github.com/backstage/software-templates/blob/optional-description/scaffolder-templates/springboot-grpc-template/template.yaml, YAMLSemanticError: Implicit map keys need to be followed by map values type=plugin entity=location:default/example-templates-remote
```

**Comment by mtlewis** [comment]
> How about explicitly defaulting the description parameter to '' in templates?

Gave this a spin, seems to work as expected! https://github.com/backstage/software-templates/pull/13

**Comment by benjdlambert** [comment]
Sorry to clarify @mtlewis amending the `catalog-info.yaml` that is called with `fetch:template` to wrap it up in that `yaml` bit file not the `template.yaml` file

**Comment by benjdlambert** [comment]
I think updating those files is a cleaner fix 🙏

**Comment by mtlewis** [comment]
Done, and backstage/software-templates#13 updated!
