### ISSUE TITLE
auth-backend: Upgrade openid-client to 5.x

### ISSUE THREAD

**Issue by jhaals** [backstage/backstage#9227]
A new major release of `node-openid-client` https://github.com/panva/node-openid-client/releases/tag/v5.0.0 has been released. We are currently on 4.x and need to upgrade. There are some breaking changes in the new release which need to be taken into consideration alongside some minor code changes.

**Comment by jhaals** [comment]
This is up for grabs for anyone interested in helping out! :)

**Comment by ismailelbadawy** [comment]
Is it okay if I start working on this?

**Comment by jahredhope** [comment]
Looking for an issue to pick up and I was checking if this issue should be closed or still needed work.
I noticed that openid-client now has two versions being used:

@kubernetes/client-node@^0.16.0 -> openid-client@^4.1.1
openid-client@^5.1.3

Is this issue being kept open until that dependency is updated or should it be closed?

**Comment by jhaals** [comment]
Thanks for asking and hunting things to fix @jahredhope! 👍  Looks like our internal dependency on this library is updated so this issue can indeed be closed
