### ISSUE TITLE
[@backstage/cli]: Unable to run a project with only backend plugins due to missing "react" dependency

### ISSUE THREAD

**Issue by marcuseide** [backstage/backstage#9228]
## Expected Behavior

`yarn start` in a project that's only using backend plugins (a `proxy` or `auth` service for example) should work.

## Current Behavior

`yarn start` is failing due to a missing dependency for `react`:

```
Error: Cannot find module 'react'
...
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'node_modules/react-hot-loader/dist/react-hot-loader.production.min.js',
    'node_modules/react-hot-loader/index.js',
    'packages/backend/dist/main.js'
  ]
```

## Possible Solution

Seems that this was introduced in `v0.10.1` of `@backstage/cli` as I was able to successfully run the service using `v0.10.0`.

Adding `react` to `devDependencies` works as a work-around for now.

## Steps to Reproduce

1. Use a project with only backend plugins (no frontend app)
2. Use `"@backstage/cli": "^0.10.1`
3. `yarn start`

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

```
OS:   Darwin 19.6.0 - darwin/x64
node: v16.10.0
yarn: 1.22.10
```

**Comment by Rugvip** [comment]
A bit stumped tbh, but I poked around a bit and I think this might've been an issue for longer than just the most recent release. We just recently removed an accidental dependency on `@backstage/test-utils` from `@backstage/auth-backend`, so when moving from that release in a backend-only project that may actually cause a removal on an indirect dependency on `react`. As in, this issue could've been around for a long time, just that we were installing `react` in backend projects by mistake.

Will keep digging later on, just and update with what I found so far :grin:
