### ISSUE TITLE
[Plugin] entity-validator

### ISSUE THREAD

**Issue by GoFightNguyen** [backstage/backstage#9245]
## Summary

A tool for editing and validating `catalog-info.yaml` files.

## Context

Users requested ways to lint and validate their `catalog-info.yaml` files before committing to their repos. 

Roadie solved this using a cli-tool.
We chose a different approach because our users desired:
- a faster feedback loop than waiting for a pipeline such as GitHub actions
- a faster feedback loop than waiting for the ingestion processor to complete
- to not install additional tools locally

We also chose a different approach in order to drive usage of our Backstage implementation.

### How we solved this

Created a frontend plugin utilizing `@monaco-editor/react`.

This required importing pieces from `@backstage/catalog-model` and duplicating logic from the `NextCatalogBuilder.ts` and `BuiltInKindsEntityProcessor.ts`.

### Caveats

Since much had to be duplicated, it is easy to fall out-of-sync.

Validation is isolated from the Software Catalog, therefore it is unable to validate cases such as:
- relationships to other entities
- distinct names

Because of the architecture, there are other edge-case limitations such as placeholders (e.g. $text).

### Examples of validations you can expect
- YAML semantics
- entity schema (https://backstage.io/docs/features/software-catalog/descriptor-format)

**Comment by GoFightNguyen** [comment]
@brethubbard

**Comment by awanlin** [comment]
@GoFightNguyen Roadie actually has  created an Entity Validator: https://github.com/RoadieHQ/backstage-entity-validator

**Comment by awanlin** [comment]
Sorry, missed the fine print ;)

**Comment by djamaile** [comment]
@GoFightNguyen Does this mean you will be opening a PR for this? I really like this idea

**Comment by GoFightNguyen** [comment]
The intention is to open a PR. The concern is around the imports and duplicated logic as there is not a readily-available module for the front-end to consume.

**Comment by freben** [comment]
Would it make sense to instead leverage the catalog for validation, by looking into adding a new POST endpoint for that express purpose? That would mean no duplication, and the ability to leverage any programmatic changes made in the catalog (such as if you've modified the field validation rules), etc.

**Comment by GoFightNguyen** [comment]
@freben that would be great. Honestly, I would need guidance/assistance as I originally found that area overwhelming and got lost

**Comment by freben** [comment]
Sure! It's a bit late for today, but in general a new `/validate-entity` endpoint on the [express router here](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/createRouter.ts) would be a great start I think.

**Comment by freben** [comment]
That's perfectly fine.

**Comment by awanlin** [comment]
@GoFightNguyen do you have something in mind for v1? This has been on the back of my mind for a bit. I'm thinking of building an "editor" for Users and Groups as we store them in YAML files and we've had owners of the Groups wanting to be able to manage them

**Comment by freben** [comment]
@awanlin see also the thread here if you missed it https://discord.com/channels/687207715902193673/923144214580191282/938553802162847755

**Comment by brethubbard** [comment]
@GoFightNguyen I created a PR for a validate-entity endpoint. A couple interesting notes that I learned doing it.

The name conflict detection happens when attempting to insert into the database so this still will not check for that use case.

It will check other use cases like the `$text` placeholders and even if the catalog is able to download from the location referenced.

It will ensure relationships are formatted correctly if there is no default (e.g. `dependsOn: ['component:default/name-of-component']` is not an error but `dependsOn: ['name-of-component']` is).

When processing the entity, it seems to stop processing at the first error so even though there may be several different failure conditions, it only shows 1.

In the current state, the frontend will still have to parse the yaml and send it to the server. This means that the front end will still be responsible for indicating yaml parsing failures. The endpoint also only accepts a single entity so that may cause issues for multi doc yaml files.

Having said all of that, I'm happy to scrap the work for the endpoint and call it a good learning experience if we want to move forward with the plugin in the current state.

**Comment by GoFightNguyen** [comment]
Thanks @brethubbard

The `/validate-entity` endpoint might be useful regardless of this frontend plugin. I would rely on the maintainers of backstage to determine that.

I think much of the endpoint explanation you provided should be explicitly stated in the endpoint PR (as it was not evident to me while reviewing the code) and possibly documented with the endpoint if it gets merged.

Thanks for calling attention to the one-error-at-a-time and the single-entity constraints of the endpoint. At our organization, all `catalog-info.yaml` files are multi-doc.

**Comment by brethubbard** [comment]
Good call @GoFightNguyen, I have added those comments to the PR as well.

**Comment by roylisto** [comment]
is this Idea the same as the Gitlab CI Editor? https://docs.gitlab.com/ee/ci/pipeline_editor/

**Comment by freben** [comment]
@roylisto Not really, the validation endpoint will have a quite different purpose and way of working. The only thing the location endpoint can do is to register a URL to an already complete, existing file in source code management. The validation endpoint will serve use cases such as IDE integration and validation, early checks from anywhere. Additionally, it'll likely have to be able to do so with some additional contextual data passed in etc (not even sure how this would best work).

**Comment by ivangonzalezacuna** [comment]
I have just left a message in Discord. (link [here](https://discord.com/channels/687207715902193673/687207715902193679/1068489724626473032)).

We have developed an internal frontend plugin to process the entity validation. It just uses the `/validate-entity` endpoint and shows the results to the user. Is this something you would like to be open-sourced? We have no problems doing so.

Here you have an screenshot with an example check:
![Screenshot from 2023-01-27 12-15-04](https://user-images.githubusercontent.com/49096359/215078087-3a817380-90bb-4e60-9467-8c2787b8ecb2.png)

**Comment by GoFightNguyen** [comment]
I think it would be an awesome contribution

**Comment by benjdlambert** [comment]
@ivangonzalezacuna think this makes sense! Raise a PR!

**Comment by GoFightNguyen** [comment]
The recently added `@backstage/plugin-entity-validation`, see [here](https://github.com/backstage/backstage/tree/master/plugins/entity-validation), makes this issue obsolete

**Comment by yuriy-sng** [comment]
@GoFightNguyen That takes to a 404. What's the new URL?
