### ISSUE TITLE
Adding role information to the  User model

### ISSUE THREAD

**Issue by jcarres-mdsol** [backstage/backstage#9276]
## Feature Suggestion

I think a common use-case to have user information in backstage is to be able to find the people you want to contact to get something done. 

If I want to deal with a security issue or if I want a feature or if tests are having issues in CI, I may want to interact with one person or a different person. 

So I think it is useful to have a "role" in the user model.

## Possible Implementation

I think a string open to the usage and interpretation of plugins. If a given ingestion mechanism (Github, etc) can not fill it in it is fine also. 

## Context

Try to avoid contacting the tester when I mean to contact the product owner and otherwise.

**Comment by benjdlambert** [comment]
#9310 added the rendering of `description` to the card, so maybe you could use this field?

Otherwise, you could probably extend you own model with something that writes `spec.role` in a catalog processor. I don't think something like this is ready to be added to the open source flavour just yet.

**Comment by freben** [comment]
Another food for thought - apart from roles as in "employment contract says hired as an X", there's also potential roles effectively on the group->user edge, "role within the team is Y". So X might say "backend engineer" and Y might say "tech owner" :)

**Comment by djamaile** [comment]
to piggy back of this issue. I also needed to show the role of a user (which comes from LDAP), one extra requirement was that these combination of users were not a group from LDAP. So, I needed to make a temporary group + update the user with the role. 

```tsx
// retrieve users from catalog
const user = await catalogApi.getEntityByName(name);

// update user
 user.metadata.annotations.role = role;
 user.relations?.push(memberOfRelation) // <- push the user to a temp group;
 keyRoleUsers.push(user);

...

return keyRoleUsers;

// render updated users (defaultEntity is the temp group
return (
 <TestApiProvider apis={[[catalogApiRef, catalogApi(keyRoleUsers ?? [])]]}>
      <EntityProvider entity={defaultEntity}>
        <KeyRoles />
      </EntityProvider>
    </TestApiProvider>
);

```

was wondering if there would be a better solution to this? Currently I also have these helper functions (makeUser, makeGroup, makeRelation) -> Maybe we can put these functions somewhere in the backstage repo?

**Comment by Rugvip** [comment]
Will close this since we've essentially arrived at no action, as we're keeping the provided org model very slim for now. Let's create separate issues if there are particular patterns we want to document, or open up a [discussion](https://github.com/backstage/backstage/discussions) if we're want to just explore possible patterns together. Can also ofc continue the discussion here too, we just want to clarify that we're not aiming to add anything to the core model right now.

Let us know if you want to re-open the issue
