### ISSUE TITLE
[Deployment/Documentation] Improves deployment documentation on Heroku

### ISSUE THREAD

**Issue by gabriel-dantas98** [backstage/backstage#9281]
## Context

I recently did a test deploy of the backstage deploy on Heroku but I realized that using the commands listed in the documentation I didn't have an expected success :(

I had to add some more commands to be able to build and publish the backstage image and add some settings in app-config.yaml.

Some examples of the problems I had.

The `heroku stack:set container -a <app-name>` command expects a heroku project to have already been created.

The `heroku containe:push web -a <app-name>` command also expects you to have a Dockerfile at the root and suffix with the dyno type.

I would like to contribute and improve the experience because I believe that Heroku can be a great experience to run the Backstage "online" 😉 

## Documentation Suggestion

So my suggestion is:

- Add additional Heroku commands to create a project and commands to build and publish the docker image.

- Show a suggestion to update app-config.yaml in order to receive the necessary settings from Heroku. _(app/backend.baseUrl and list.port)_

I believe there must also be some cool suggestions because I could see that the [demo](https://github.com/backstage/demo) also has Heroku settings.

**Comment by phamngocthanhtrung** [comment]
Unfortunately, I also have trouble connecting to the Heroku Postgres DB. 
Can this point also be taken into the enhancement?

**Comment by gabriel-dantas98** [comment]
I still haven't done a test on heroku using the postgres add-on but I can try to simulate it in the environment that I did the other tests. The test I did was using SQLite.

We can add this improvement as well a different issues maybe.
I'll run the tests and see if I can contribute too. 😉

**Comment by benjdlambert** [comment]
Closing as #9318 is merged! :tada:
