### ISSUE TITLE
[scaffolder-backend-module-cookiecutter] Default cookiecutter.json file is not loaded

### ISSUE THREAD

**Issue by slougheed** [backstage/backstage#9313]
## Expected Behavior

The fetch:cookiecutter action should fetch the existing cookiecutter.json value and combine this with values passed in from the catalog-info.yaml file before re-writing the cookiecutter.json value (https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend-module-cookiecutter/src/actions/fetch/cookiecutter.ts lines 71 to 79)

## Current Behavior

The fetchTemplateCookieCutter function looks in the wrong directory for the default cookiecutter.json file.

The contents of the template repository are downloaded to [workDir/template/{{cookiecutter and 'contents'}}](https://github.com/backstage/backstage/blob/e7f38e354612b7d060146108fbfcc0800b5d4c78/plugins/scaffolder-backend-module-cookiecutter/src/actions/fetch/cookiecutter.ts#L204) however, the action tries to read the default cookiecutter.json file from workDir/template. It's not there so the values from catalog-info.yaml are the only values used.

## Possible Solution

You could change the call to [fetchTemplateCookieCutter ](https://github.com/backstage/backstage/blob/e7f38e354612b7d060146108fbfcc0800b5d4c78/plugins/scaffolder-backend-module-cookiecutter/src/actions/fetch/cookiecutter.ts#L71)to use the /{{cookiecutter and 'contents'}} directory. However, I'm not certain what {{cookiecutter and 'contents'}} is supposed to resolve to. In my case it is taken as a string literal so looking at the workdir/tempalte it has one no files and one directory called "{{cookiecutter and 'contents'}}, that seems incorrect.

## Steps to Reproduce

I have created a very basic cookiecutter template project: https://github.com/slougheed/backstage-cookiecutter-template. 

1. Register an existing component from https://github.com/slougheed/backstage-cookiecutter-template
2. Attempt to create a new project from this template it should fail the fetch with an error of 
"Error message: 'collections.OrderedDict object' has no attribute 'project_slug'"

## Context

We use cookiecutter templates with and without backstage. Therefore, we do not want to duplicate any derived values (ex. project_slug) or constants (ex. version) in two places (cookiecutter.json and catalog-info.yaml).

## Your Environment

OS:   Linux 5.11.0-1027-azure - linux/x64
node: v14.18.3
yarn: 1.22.17
cli:  0.13.0

**Comment by benjdlambert** [comment]
Is this something that would like to contribute a fix? :pray:

**Comment by slougheed** [comment]
> Is this something that would like to contribute a fix? 🙏

I can create a simple PR that changes the call to fetchTemplateCookieCutter() to use the correct path. That will fix my issue and be a small delta, however, it means that there is some duplication and matching paths are defined in two places. Note that this is already the case with the templateDir [here](https://github.com/backstage/backstage/blob/07d9fa4301034c64fd6400494072e0461899be51/plugins/scaffolder-backend-module-cookiecutter/src/actions/fetch/cookiecutter.ts#L65) in the run function and [here](https://github.com/backstage/backstage/blob/07d9fa4301034c64fd6400494072e0461899be51/plugins/scaffolder-backend-module-cookiecutter/src/actions/fetch/cookiecutter.ts#L203) in the handler function.

Alternatively, I can tack both the templateDir and templateContentsDir to the values passed in (as was done for the imageName) so they are only defined in one place. Larger delta, but cleaner. Any preference?

**Comment by benjdlambert** [comment]
Maybe the last one I think would be better? I'm a little out of the loop on the status of the action to be honest, but let's start there.

Ideally we'd also want to add some of this behaviour to our `fetch:template` replacement for the `cookiecutter` action, as we're probably going to have the `cookiecutter` action be community contributed only, and we will maintain the `fetch:template` one moving forward. But that's a different conversation :)
