### ISSUE TITLE
Not possible to try out openapi endpoints with auth and payload

### ISSUE THREAD

**Issue by PavelPolyakov** [backstage/backstage#9345]
With fresh `backstage` when trying to try out any endpoint which is protected with auth and has payload (methods `POST`, `DELETE`, etc.) the UI stucks and there is an error in the console.

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/839290/152426635-2322eb14-d14b-40a2-808a-745b034125b7.png">
<img width="706" alt="image" src="https://user-images.githubusercontent.com/839290/152426688-289583b4-22a9-4484-bb55-2c5edd86043c.png">

## Expected Behavior

It works, like it worked before

## Current Behavior

It does not work

## Possible Solution

🤷‍♂️, do not use fresh backstage, which uses fresh `swagger-ui-react`

## Steps to Reproduce

1. install fresh `backstage` using `npx @backstage/create-app` 
2. run it with `yarn dev`
3. open http://localhost:3000/catalog/default/api/spotify/definition#/category-follow/endpoint-unfollow-artists-users and try to execute that

## Context

This is major feature of the `backstage` itself, it stops us from keeping the `backstage` fresh. Currently we can not update dependencies.

`Try out` in swagger UI still works with endpoints where no auth is configures (petstore example).

It looks it is related to this issue and connected with some fresh update of `swagger-ui-react`: https://github.com/swagger-api/swagger-ui/issues/7797#issuecomment-1028835529 . Long ago there was also an issue in the `React` repo: https://github.com/facebook/react/issues/14484, seems that this is happening when there is some `React` versions mismatch.

**Comment by benjdlambert** [comment]
OK - maybe if you can find a version that works for now we can update this ticket that people lock down the `swagger-ui-*` dependencies to that version until a bug fix is found for the upstream library?

**Comment by PavelPolyakov** [comment]
@benjdlambert 
What I see is, that it works with our "previous" version where `swagger-ui-react` is resolved to:
```
swagger-ui-react@^4.0.0-rc.3:
  version "4.1.0"
  resolved "https://registry.yarnpkg.com/swagger-ui-react/-/swagger-ui-react-4.1.0.tgz#6033d40de813b5ac2f76392be77f8b2c9d734b15"
  integrity sha512-+25y5Hn39S6MjRbKLfdcwwe1xRdAMCNabHKDHc3LAQ0PE1xPT7aWY6KTQIOGOwsb36ev5ic5ZoUz0Wx6xeDfnQ==
```

But previous version has other dependencies also in the "previous" state. And I don't know how to easily integrate this. What I've tried, is to change `@backstage/plugin-api-docs` version to the older one in the fresh installation: `@backstage/plugin-api-docs@^0.6.3"`. But this brings different errors to the front-end.

Any hints how can I test that correctly?

**Comment by benjdlambert** [comment]
I think what might be good is to temporarily add a `resolutions` block to the `app/package.json` that points to `4.1.0` explicitly.
https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

Or you could try first adding `swagger-ui-react` version `4.1.0` explicitly to the `dependencies` part of `packages/app/package.json`

**Comment by PavelPolyakov** [comment]
Indeed adding 
```
  "resolutions": {
    "@backstage/plugin-api-docs/**/swagger-ui-react": "4.1.0"
  }
```
to the `package.json`, then removing `yarn.lock` and executing `yarn install` helped to install the older version. BUT, the issue is still present 😢. Maybe, that issue is related to the `React` update then, but it's a long shot.

**Comment by benjdlambert** [comment]
Don't think it's related to the React 17 bump FWIW.

**Comment by PavelPolyakov** [comment]
> Reading through the bug ticket you had before, it also suggests that there could be something in `swagger-ui` maybe check what version of that works for you and you can add a resolution for that too? [swagger-api/swagger-ui#7797 (comment)](https://github.com/swagger-api/swagger-ui/issues/7797#issuecomment-1028835529)

ah you are right, I thought `swagger-ui-react` contains `swagger-ui`, but it's a dependency. Will do.

**Comment by PavelPolyakov** [comment]
Ok, new input. When I add resolution like this:
```
  "resolutions": {
    "**/swagger-ui-react": "4.1.0"
  }
```

Then it seems to work. In the `yarn.lock` I then get:
```
swagger-ui-react@4.1.0, swagger-ui-react@^4.1.3:
  version "4.1.0"
  resolved "https://registry.yarnpkg.com/swagger-ui-react/-/swagger-ui-react-4.1.0.tgz#6033d40de813b5ac2f76392be77f8b2c9d734b15"
  integrity sha512-+25y5Hn39S6MjRbKLfdcwwe1xRdAMCNabHKDHc3LAQ0PE1xPT7aWY6KTQIOGOwsb36ev5ic5ZoUz0Wx6xeDfnQ==
  dependencies:
    "@babel/runtime-corejs3" "^7.14.7"
    "@braintree/sanitize-url" "^5.0.2"
    base64-js "^1.5.1"
    classnames "^2.3.1"
    css.escape "1.5.1"
    deep-extend "0.6.0"
    dompurify "=2.3.3"
    ieee754 "^1.2.1"
    immutable "^3.x.x"
    js-file-download "^0.4.12"
    js-yaml "=4.1.0"
    lodash "^4.17.21"
    memoizee "^0.4.15"
    prop-types "^15.7.2"
    randombytes "^2.1.0"
    react-copy-to-clipboard "5.0.3"
    react-debounce-input "=3.2.4"
    react-immutable-proptypes "2.2.0"
    react-immutable-pure-component "^2.2.0"
    react-inspector "^5.1.1"
    react-redux "^7.2.4"
    react-syntax-highlighter "^15.4.4"
    redux "^4.1.0"
    redux-immutable "^4.0.0"
    remarkable "^2.0.1"
    reselect "^4.0.0"
    serialize-error "^8.1.0"
    sha.js "^2.4.11"
    swagger-client "^3.17.0"
    url-parse "^1.5.3"
    xml "=1.0.1"
    xml-but-prettier "^1.0.1"
    zenscroll "^4.0.2"
```
