### ISSUE TITLE
CricleCI Plugin - Feature: Trigger pipeline

### ISSUE THREAD

**Issue by igor-radulovic** [backstage/backstage#9361]
## Feature Suggestion
The CircleCI plugin is a great tool to visualize recent builds and provides the option to re-run builds. What I and my team feel is missing is an option to actually trigger the pipeline based on specific parameters. To better explain this feature: In our Circle config, we have certain workflows that can be triggered from Slack for instance, which is just based on some environment parameter in Circle. Having this option, CircleCi users in Backstage would have the flexibility to trigger pipelines and workflows that they want without having to base it on being triggered of a specific commit & push action. 

## Possible Implementation
A similar implementation that CircleCi uses today with the "Trigger Pipeline" button. 
[https://support.circleci.com/hc/en-us/articles/360050351292-How-to-trigger-a-workflow-via-CircleCI-API-v2](https://support.circleci.com/hc/en-us/articles/360050351292-How-to-trigger-a-workflow-via-CircleCI-API-v2)

## Context

![image](https://user-images.githubusercontent.com/92377369/152523849-0266201e-ed75-4d8c-ae6c-4b8804c123be.png)
![image](https://user-images.githubusercontent.com/92377369/152524158-00dc81a2-f8fb-4470-aef1-1d4e132db5a7.png)

**Comment by benjdlambert** [comment]
This sounds like a good enhancement, is this something that you want to help out and build? 🙏

**Comment by igor-radulovic** [comment]
@benjdlambert  Could start looking into it when I have some time over :)

Another "feature" or visualization improvement would be to include tasks that haven't started, and in addition to include "approval" steps which is a feature that CricleCI provides.

![image](https://user-images.githubusercontent.com/92377369/152973085-cdb1c282-b439-4ecb-9b9f-7e7f7ca8bc03.png)

So, as shown in the picture, only the job that has actually started/completed will be visible in the plugin, and the approval step is also excluded to trigger the next job.

Should I describe this in a separate issue or extend the feature here? :)

**Comment by benjdlambert** [comment]
I think a seperate issue could be good, in case someone else can contribute the other work and it 
keeps the PR's smaller.

**Comment by jithenshriyan** [comment]
@benjdlambert I'd love to work on this enhancement! Let me know if it's still open. Thanks

**Comment by benjdlambert** [comment]
Assigned!

**Comment by jithenshriyan** [comment]
@benjdlambert The current CircleCI SDK we're using is still on the v1 API which will be deprecated within the next year. In order to trigger a pipeline, we need to use the v2 API which the sdk doesn't support.

The workaround until we migrate the entire service to the v2 API is to trigger a new build job which is available in the current SDK. The only challenge with this is that pipelines/workflows can't be triggered.

As for migration to v2, we could generate all of the typescript types using their OpenAPI spec, and use a rest client to make the calls to their v2 API. I am open to working on this as well, I just don't know if I have time as this is a much larger task.

What are your thoughts?

**Comment by benjdlambert** [comment]
Yeah it seems we're a little stuck until there's any progress on this https://github.com/worldturtlemedia/circleci-api/issues/228 by the looks of things. If you could get the v2 stuff underway and maybe help push that issue along then we can migrate to that API instead. I think just do the best you can right now, and let's see where we get. It's a little tricky always with these dependencies, so making a link out to CircleCI so users can do things there could also be an option if we get stuck,
