### ISSUE TITLE
Problem opening doc in branch resource inside component 

### ISSUE THREAD

**Issue by tiago-celuppi** [backstage/backstage#9365]
I'm having a problem opening the doc in the created component, it's generating an error. 

Follow the error
Building a newer version of this documentation failed. Error: "Failed to retrieve default branch from https://api.bitbucket.org/2.0/repositories//contabilizei-ninjas, 404 Not Found"
![Captura de tela de 2022-02-04 10-45-56](https://user-images.githubusercontent.com/99027850/152539534-e31a3bff-86b5-4ee5-80f2-79f65c73f594.png)

From my analysis, I'm seeing that bitbucket is not passing the project name

**Comment by benjdlambert** [comment]
Hmm this looks like we're missing the project name from somewhere, @backstage/techdocs-core help here?

**Comment by camilaibs** [comment]
Hi @tiago-celuppi could you share how the `backstage.io/techdocs-ref` looks like for this repo?
