### ISSUE TITLE
cli: versions:bump ignores registry specified in local .npmrc / .yarnrc

### ISSUE THREAD

**Issue by mtlewis** [backstage/backstage#9368]
## Expected Behavior

When I run `yarn backstage-cli versions:bump`, I'd expect the registry used in the new and updated in yarn.lock to reflect the project-local configuration in .npmrc or .yarnrc.

## Current Behavior

Instead, it appears that local configuration is ignored in favor of the global registry configuration. 

## Possible Solution

From reading the backstage-cli code a bit, I can see that it works by removing entries from yarn.lock and then running yarn install. What's strange is, when I perform these two steps manually, the project-local configuration is respected. This leads me to suspect that something about the way that the cli runs the command is preventing it from reading the project-local config.

## Steps to Reproduce

1. In a new instance created by an old version of create-app, add an .npmrc or .yarnrc with the registry set to `https://registry.npmjs.org/`. Set the global registry to something else (**other than** `https://registry.yarnpkg.com` - I used a private registry). Feel free to start from https://github.com/mtlewis/registry-bug-repro, which already has this done - probably easier than futzing around getting an old version of create-app.
2. Confirm that all entries in yarn.lock currently reference the npmjs.org registry.
3. Run `yarn backstage-cli versions:bump`
4. Note that any packages in yarn.lock that required upgrading will now have a `resolved` field with the private registry  URL.
5. Delete one of the packages resolved through artifactory in 4., and re-run `yarn install` manually. Observe that the package correctly gets resolved through registry.npmjs.org.

## Context

This is a particular issue when people are working in both public and private contexts - they may have a global configuration using a private registry, and a project-local configuration that reverts to the public registry for Backstage specifically.

## Your Environment

- NodeJS Version (v14): v16
- Operating System and Version (e.g. Ubuntu 14.04): MacOS 12.2
- Browser Information: N/A

**Comment by Rugvip** [comment]
Just to double check, did you run the bump command in the repo root?

**Comment by mtlewis** [comment]
Hmm - I'm struggling to get a consistent repro here, and suspect this may actually be down to this bug in yarn itself: https://github.com/yarnpkg/yarn/issues/4458. In any case, I wouldn't recommend sinking any (more) time into triaging this for now.

**Comment by Rugvip** [comment]
Let's file this under reasons to migrate to yarn 3 😁

**Comment by mtlewis** [comment]
Totally.

**Comment by mtlewis** [comment]
Ah - figured out what I was doing wrong when putting together a repro for this before (I was trying to get yarn to switch between yarnpkg.com and npmjs.org to make the reproduction more universal, but I think there's special handling inside yarn to prevent unnecessarily switching between those two). Maybe worth a second person seeing if they can reproduce the issue by following the steps now listed in the issue summary.

**Comment by mtlewis** [comment]
Did a bit more digging into this. I suspect the problem is an inconsistency between the registry loading behavior inside `yarn install`, and the way configuration is propagated into the environment for scripts started through `yarn run`, as described [here](https://github.com/yarnpkg/yarn/issues/2091#issuecomment-288890717). When running `yarn install` directly, yarn correctly uses any local .npmrc file over the global one. Conversely, `yarn run` seems to read only the _global_ `.npmrc` when figuring out what to set the `npm_config_registry` environment variable to. This environment variable overrides configuration files, so when running `yarn install` through `yarn run`, the registry set by `yarn run` wins and the global registry is incorrectly used (you can see this directly by running `yarn run env`).

It's possible to reproduce this issue without involving backstage-cli at all - running `yarn install` will use the correct local registry in the resolved field in yarn.lock, while running `yarn exec yarn install` will incorrectly use the global one. It's also possible to work around the issue when running backstage-cli by running the script directly, rather than through yarn.

Other than recommending this workaround, the only thing I can think of to fix this is to manually override the `npm_config_registry` environment variable if a local `.npmrc` or `.yarnrc` is found, which to me doesn't seem worth the effort.

**Comment by mtlewis** [comment]
I like the idea of deleting the variable to let `yarn install` work out what it should be again! What's the motivation for stripping all of the npm_ variables though? Seems like a more targeted deletion would be less likely to have unintended side effects.

**Comment by Rugvip** [comment]
@mtlewis I chose it because it most closely mimics a plain `yarn install`, where you typically don't have any config set at all. Was worried that other configuration options might have similar issues that we just haven't discovered yet. I'm also a bit scared that removing a subset of vars would lead to even more confusion, as right it's more of a "we ignore all npm_ env vars", rather than "we ignore vars x, y, and z".
