### ISSUE TITLE
Make authenticated requests to backstage backend from third party

### ISSUE THREAD

**Issue by DefCon-007** [backstage/backstage#9374]
Backstage documentation explains how two plugins can easily communicate with each other, but is there a way I can call backstage backend APIs from an external service to programmatically access my data in Backstage? 

For e.g. using the API `http://localhost:7007/api/catalog/entities?filter=kind=API` to list all the APIs.

**Comment by freben** [comment]
Sure. These are just regular REST APIs with no particular magic. In particular the catalog api is distinctly meant to be usable by other services or consumers.

**Comment by DefCon-007** [comment]
@freben But what about authentication for the same? Surely the deployed the instances which a organisation is using won't have open access for these APIs, right?

**Comment by Rugvip** [comment]
@DefCon-007 We'll get proper docs for this in place, but for now you'll want to replicate this: https://github.com/backstage/backstage/blob/9370194ce9e52b8abeeda06539b67bb34b323c54/packages/backend-common/src/tokens/ServerTokenManager.ts#L85

So create a JWT with the payload `{"sub":"backstage-server"}` and sign it with the shared symmetric (`oct`) key that you configure in the Backstage backend.

Bit of a warning that the combination of backend authentication and external requests is still unstable and that we're likely to change the token format, for example adding an expiration, so you'll need to keep an eye out for that in the changelog.

**Comment by greptail** [comment]
Do we have proper documentation for it?
