### ISSUE TITLE
requestUserCredentials In Software Templates Not Requesting Scopes

### ISSUE THREAD

**Issue by bassrock** [backstage/backstage#9380]
## Expected Behavior

When using `requestUserCredentials` in a Backstage software template with GitHub a credential with `repo` permission should be created and used to create a new Github repository.

## Current Behavior

I put in a bunch of logging in https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts#L168 and dumped the created token that is being used.

As far as I can tell when verifying the token via the method [here](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps) , it looks like it is created without any OAuth scopes and is why it is not able to create a repository.

Note I am using a github app.

## Possible Solution

I have a feeling that this may be because of https://github.com/backstage/backstage/blob/f944a625c4a8ec7f6a6237502691da9209ce6b14/packages/core-app-api/CHANGELOG.md#0110 

When I setup my GitHub app to have full admin rights on the organization I am testing backstage with (which is not a great practice at all) Backstage is able to create a repository and it does it as the user that was authorized using `requestUserCredentials`. Also if i give it full admin rights and do not include `requestUserCredentials` the repository is created by the Backstage Github App.

## Steps to Reproduce

1. Setup backstage with a Github App using the default permissions listed in the github-apps documentation of backstage.
2. Use `requestUserCredentials` within software templates to create repositories.
3. Note repository will not create.

## Context

Currently the Backstage app I am using needs it's Github App to have read & write on `Administration` which are pretty valuable in a large Github Organization. Instead backstage should use a user's scoped permission to create repositories and not rely on the Github App permissions within the Org.

## Your Environment

yarn backstage-cli info
yarn run v1.22.17
$ /Users/daniel/Work/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 21.3.0 - darwin/arm64
node: v16.13.0
yarn: 1.22.17
cli:  0.12.0 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.6
  @backstage/backend-common                                0.10.6
  @backstage/backend-tasks                                 0.1.5
  @backstage/catalog-client                                0.5.5
  @backstage/catalog-model                                 0.9.10
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.12.0, 0.13.1
  @backstage/config-loader                                 0.9.3
  @backstage/config                                        0.1.13
  @backstage/core-app-api                                  0.5.2
  @backstage/core-components                               0.8.7
  @backstage/core-plugin-api                               0.6.0
  @backstage/errors                                        0.2.0
  @backstage/integration-react                             0.1.20
  @backstage/integration                                   0.7.2
  @backstage/plugin-api-docs                               0.7.1
  @backstage/plugin-app-backend                            0.3.23
  @backstage/plugin-auth-backend                           0.9.0
  @backstage/plugin-catalog-backend                        0.21.2
  @backstage/plugin-catalog-common                         0.1.2
  @backstage/plugin-catalog-graph                          0.2.9
  @backstage/plugin-catalog-import                         0.8.0
  @backstage/plugin-catalog-react                          0.6.13
  @backstage/plugin-catalog                                0.7.11
  @backstage/plugin-circleci                               0.2.36
  @backstage/plugin-github-actions                         0.4.34
  @backstage/plugin-org                                    0.4.1
  @backstage/plugin-pagerduty                              0.3.24
  @backstage/plugin-permission-common                      0.4.0
  @backstage/plugin-permission-node                        0.4.2
  @backstage/plugin-permission-react                       0.3.0
  @backstage/plugin-proxy-backend                          0.2.17
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.10
  @backstage/plugin-scaffolder-backend                     0.15.23
  @backstage/plugin-scaffolder-common                      0.1.3
  @backstage/plugin-scaffolder                             0.12.1
  @backstage/plugin-search-backend-module-pg               0.2.5
  @backstage/plugin-search-backend-node                    0.4.5
  @backstage/plugin-search-backend                         0.4.1
  @backstage/plugin-search                                 0.6.1
  @backstage/plugin-sentry                                 0.3.35
  @backstage/plugin-tech-radar                             0.5.4
  @backstage/plugin-techdocs-backend                       0.13.2
  @backstage/plugin-techdocs                               0.13.2
  @backstage/plugin-todo-backend                           0.1.20
  @backstage/plugin-todo                                   0.1.21
  @backstage/plugin-user-settings                          0.3.18
  @backstage/search-common                                 0.2.2
  @backstage/techdocs-common                               0.11.6
  @backstage/test-utils                                    0.2.4
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1

**Comment by benjdlambert** [comment]
> I have a feeling that this may be because of https://github.com/backstage/backstage/blob/f944a625c4a8ec7f6a6237502691da9209ce6b14/packages/core-app-api/CHANGELOG.md#0110

This is indeed the problem, the scopes don't work the same using the Github App for signin.

We could updating the error messages for the Github App, to require the permissions needed, but that's not going to help you. I think you're going to need an oauth app as well for the `auth-provider` so it can act on behalf of the user as user.

That way you can remove the admin privilege off the github app and just have content read, and then the oauth app doesn't have any permissions as it acts on behalf of the signed in user. You can still keep the github app under the `integrations` but just have a normal oauth app for the `auth-backend`.

**Comment by bassrock** [comment]
Ahh. @benjdlambert thank you that worked perfectly.

**Comment by benjdlambert** [comment]
Maybe we should add some explicit documentation under the setup for this somewhere, would you like to contribute some of this documentation? Otherwise we can close this ticket and pick up the docs seperately :pray:

**Comment by Rugvip** [comment]
Opened #9481 and figured we could continue discussions on ways forward there. Gonna close this, let us know if we missed something
