### ISSUE TITLE
[Search] Move to `opensearch` instead of `elasticsearch` library for `plugins-search-backend-module-elasticsearch`

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#9405]
GIven the conversation in #9153

>Anything past 7.13.x doesn't work with AWS hosted 'OpenSearch' so we'd need to keep the base at that one until we find a better solution to support both Elastic Elastic- and AWS OpenSearches. 7.13.0 is the only version on that minor number so in reality it doesn't make a difference if we add a tilde or not. I doubt new patches for that minor will be published in the future.

Let's move to the [opensearch](https://www.npmjs.com/package/@opensearch-project/opensearch) library instead and tests that this works with, AWS, Elastic.co and self hosted ElasticSearch.

**Comment by iamEAP** [comment]
@benjdlambert would you recommend either way re: putting all the deps in this one package and conditionally switching out the client?

There's just going to be _so_ much logical overlap and I don't really want to have to deal with an "elasticsearch module common" package or something.

**Comment by benjdlambert** [comment]
Yeah I mean that probably sounds reasonable until it doesn't right? How are you thinking of switching out the client? How does it work from a user perspective?
