### ISSUE TITLE
Not able to login to backstage site on https

### ISSUE THREAD

**Issue by sjamidar** [backstage/backstage#9411]
Hi Team,

I am trying to login to my backstage site. I am using google auth to login and it is working fine with http but when trying to login using https getting error login failed and redirected to login screen again.
Can anyone help here.

Thanks in Advance

**Comment by benjdlambert** [comment]
Need some more information here, what's the errors you see in the console? How are you running HTTPS? is this in production only in production?

**Comment by sjamidar** [comment]
@benjdlambert ,
On console i see attached error 
![image](https://user-images.githubusercontent.com/85929731/153172557-2b5b90af-03a6-4a65-9544-24341eba4da4.png)
And on signin window is see 
Origin 'https://developer.devint.webmdhelios.com' is not allowed error.
I am running this site in development environment for now.

**Comment by benjdlambert** [comment]
In your `app-config.yaml` do you have `https://` at the beginning or `http`? They will need to be set as `https://`

**Comment by sjamidar** [comment]
its https only at the beginning.

**Comment by benjdlambert** [comment]
For both `backend.baseUrl` and `app.baseUrl`?

**Comment by benjdlambert** [comment]
It looks like one of them is set to `https`?

**Comment by sjamidar** [comment]
backend.baseurl set to http.
I tried to make it https in local but it was throwing error there in refresh api call.
Invalid x-requested-with header. So made it http.

**Comment by benjdlambert** [comment]
Yes but when you deploy this to production it will need to be set as `https://` you should ensure that when you're deploying to production to maybe use another config that overrides this to the path that it deployed at, exactly what you would type in the browser address bar.

**Comment by benjdlambert** [comment]
Maybe you'll need to ammend the google signin also to enable your production https domain to call signin.

**Comment by sjamidar** [comment]
when i have converted it to https. getting below error in console log.
Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
https://developer.k8s.devint.webmd.com:80/api/auth/google/refresh?optional&env=development

**Comment by sjamidar** [comment]
when i am using https getting attached error 
![image](https://user-images.githubusercontent.com/85929731/153201274-476a00e1-badb-43a0-a5f4-cdd63916cff7.png)

**Comment by benjdlambert** [comment]
Do you have SSL termination enabled on your production host? Don't think there should be a port there. Remove the `:80`

**Comment by sjamidar** [comment]
No i do not have any such configs enabled.
Let me try removing :80 and check.

**Comment by sjamidar** [comment]
Now getting attached error 
![image](https://user-images.githubusercontent.com/85929731/153207476-49445a16-5b9c-4957-8b58-713dd242edba.png)

**Comment by benjdlambert** [comment]
What do you have as `backend.cors.origin` set as in `app-config.yaml`?

**Comment by sjamidar** [comment]
@benjdlambert , I have https://developer.devint.webmd.com as the backend.cors.origin value

**Comment by benjdlambert** [comment]
So that origin should be the same as `app.baseUrl` and you should be using `app.baseUrl` in the browser to access to I would expect it to be `https://developer.devint.webmdhelios.com` or whatever.

**Comment by benjdlambert** [comment]
Change the `app.baseUrl` and the `cors` header to `https://developer.devint.webmd.com` if you expect to hit backstage from that URL in the browser too.

**Comment by sjamidar** [comment]
It worked @benjdlambert .
Thanks for the help. Closing the ticket.

**Comment by hari2192** [comment]
@sjamidar - I am also trying to configure Google SSO for backstage application hosted in k8s.

Could you please share your changes you made under `app-config.yaml`, `packages/app/src/App.tsx` to make it work ?

**Comment by ankitjain1510** [comment]
Even after enabling `https://` for `baseUrl`, `backend baseUrl` and `cors origin`, what I am not getting is how to configure that backstage URL presents the certificate to the client/browser when connected?

**Comment by yj12** [comment]
can I configure - disable CORS ?

**Comment by benjdlambert** [comment]
@ankitjain1510 You would normally have a reverse proxy in front of backstage to do the termination of SSL. Wouldn't recommend running webpack in production, but you can also provide `https` settings to the `app-config.yaml` to do the SSL termination in `nodejs`. 

https://github.com/backstage/backstage/blob/master/packages/backend-common/config.d.ts#L55-L68

Something like this in `app-config.yaml`.

@yj12 whats the use case? It's there for security purposes.

**Comment by ankitjain1510** [comment]
> @ankitjain1510 You would normally have a reverse proxy in front of backstage to do the termination of SSL. Wouldn't recommend running webpack in production, but you can also provide `https` settings to the `app-config.yaml` to do the SSL termination in `nodejs`.
> 
> https://github.com/backstage/backstage/blob/master/packages/backend-common/config.d.ts#L55-L68
> 
> Something like this in `app-config.yaml`.
> 
> @yj12 whats the use case? It's there for security purposes.

@benjdlambert Thanks for the response. Let me give it a try.

**Comment by ElementalWarrior** [comment]
For those coming to this more recently. He was probably referencing the https config, which is now located here:
https://github.com/backstage/backstage/blob/master/packages/backend-defaults/config.d.ts#L47C5-L47C10

**Comment by ijazm123** [comment]
net::ERR_CERT_AUTHORITY_INVALID This is my error.
I am running backstage Kubernetes with ingress.

Any help is appreciated.

**Comment by segoja7** [comment]
> net::ERR_CERT_AUTHORITY_INVALID This is my error. I am running backstage Kubernetes with ingress.
> 
> Any help is appreciated.

@ijazm123 I have the same error, did you manage to find a solution?
