### ISSUE TITLE
Catalog API: Big files(> 1MB) - could not read location from Github repo 

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#9415]
GitHub does not show the content (or a diff) of a file larger than a certain size (over 1MB).
Open API Json file could not read location because of size. I have 50 files more than 1 MB. 
when we try to register any api from git repo it display following error

`catalog warn Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location <Github url>/apis/example.json, Error: <Github url>/apis/example.json could not be read as <Github url>example.json?ref=main, 403 Forbidden type=plugin entity=api:default/example
`
(< 1MB ) files works perfectly from same repo.
 
Github access URL is changed for big files(> 1MB). It is displaying with token.

It should register apis without size limit

## Possible Solution

No sure

## Steps to Reproduce
Step 1: Any open Api Json file with >1 MB from git repo
Step 2 : Register as new API
Step 3: you see the above error

## Context

We can't add files more than 1 MB by git repo

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by Rugvip** [comment]
This should be fixable by changing the [GitHubUrlReader](https://github.com/backstage/backstage/blob/d3292ab1ba163f538a311658c02806d6755e41c7/packages/backend-common/src/reading/GithubUrlReader.ts#L107) to fall back to a GitHub API that supports reading files larger than 1MB. As far as I know that means using the [blobs API](https://docs.github.com/en/rest/reference/git#get-a-blob), which also means we may need to look up the object SHA through the [tree API](https://docs.github.com/en/rest/reference/git#get-a-tree).

This isn't something we'll prioritize right now from the maintainer team, so happy if anyone from the community would like to pick this up! 🙏

**Comment by theparthshukla** [comment]
Don't know if this has already been addressed, but happy to take this up in case it hasn't!

**Comment by benjdlambert** [comment]
Feel free to pick this up @theparthshukla, will assign you!
