### ISSUE TITLE
Question in backstage/plugins/kubernetes changelog

### ISSUE THREAD

**Issue by initbar** [backstage/backstage#9416]
## Current Behavior

Hi Backstage team! This isn't a bug, but rather a question/clarification. The **@plugins/kubernetes** [0.5.0](https://github.com/backstage/backstage/blob/master/plugins/kubernetes/CHANGELOG.md#050) states:

![Screen Shot 2022-02-08 at 12 57 27 PM](https://user-images.githubusercontent.com/12630151/153047416-d8367e96-9ab6-4bdd-8d8d-0c74c7d877a9.png)

Wouldn't it be the case that if K8s distribution does _not_ have the metric server installed, we would need to set `skipMetricsLookup` to `true` instead of `false`?

**Comment by benjdlambert** [comment]
Good catch! I've made the change in the above PR! Thanks!
