### ISSUE TITLE
Catalog API: Could not read location from Gitlab repo ($text placeholder)

### ISSUE THREAD

**Issue by mscam** [backstage/backstage#9446]
## Expected Behaviour 

In my org we have OpenAPI definitions (`swagger.yaml`), hosted in a private GitLab repository, accessible only by authenticated users. 

API definitions are using raw GitLab URLs, with `$text` placeholder:

```
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-name
  description:  |
    Service Description
spec:
  type: openapi
  owner: project-owner
  lifecycle: production
  system: production
  definition:
    $text: https://gitlab.host.tld/org/group-name/subgroup-name/service-name/raw/master/swagger.yaml
```

GitLab discovery is enabled and correctly working for `catalog-info.yaml` files ingestion.

I would then expect also `swagger.yaml` files to be correctly read from the given definitions.

## Actual Behaviour 

Unfortunately, an error is occurring while creating the API catalog entities. It seems `$text` placeholder doesn't work with the above provided raw URLs.

## Steps to Reproduce

1. Provide a `swagger.yml` file on a private repos (self-hosted GitLab installation).
2. Create an API resource on `catalog-info.yaml` using `$text` placeholder.
3. Register the component by using backstage UI.

## Context

```
{"error":{"name":"Error","message":"InputError: Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location https://gitlab.host.tld/org/group-name/subgroup-name/service-name/raw/master/swagger.yaml, Error: Incorrect url: https://gitlab.host.tld/org/group-name/subgroup-name/service-name/raw/master/swagger.yaml, Error: Wrong GitLab URL","level":"error","service":"backstage"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":500}}
```

An attempt has also been made by using regular "blob" urls.

## Your Environment

Gitlab discovery is correctly configured and working for catalog entities creation. 

Adding the gitlab instance hostname to `backend.reading.allow` config setting (as documented here https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api) didn't work as expected.

```text
OS:   Darwin 21.2.0 - darwin/x64
node: v16.4.0
yarn: 1.22.15
cli:  0.11.0 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.4
  @backstage/backend-common                                0.10.3
  @backstage/backend-tasks                                 0.1.3
  @backstage/catalog-client                                0.5.4
  @backstage/catalog-model                                 0.9.9
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.11.0
  @backstage/config-loader                                 0.9.2
  @backstage/config                                        0.1.12
  @backstage/core-app-api                                  0.4.0
  @backstage/core-components                               0.8.4
  @backstage/core-plugin-api                               0.5.0
  @backstage/dev-utils                                     0.2.17
  @backstage/errors                                        0.2.0
  @backstage/integration-react                             0.1.18
  @backstage/integration                                   0.7.1
  @backstage/plugin-api-docs                               0.6.22
  @backstage/plugin-app-backend                            0.3.21
  @backstage/plugin-auth-backend                           0.6.2
  @backstage/plugin-catalog-backend                        0.20.0
  @backstage/plugin-catalog-common                         0.1.0
  @backstage/plugin-catalog-import                         0.7.9
  @backstage/plugin-catalog-react                          0.6.11
  @backstage/plugin-catalog                                0.7.8
  @backstage/plugin-github-actions                         0.4.31
  @backstage/plugin-org                                    0.3.34
  @backstage/plugin-permission-common                      0.3.1
  @backstage/plugin-permission-node                        0.3.0
  @backstage/plugin-permission-react                       0.2.2
  @backstage/plugin-proxy-backend                          0.2.15
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.8
  @backstage/plugin-scaffolder-backend                     0.15.20
  @backstage/plugin-scaffolder-common                      0.1.2
  @backstage/plugin-scaffolder                             0.11.18
  @backstage/plugin-search-backend-node                    0.4.4
  @backstage/plugin-search-backend                         0.3.0
  @backstage/plugin-search                                 0.5.5
  @backstage/plugin-sentry                                 0.3.33
  @backstage/plugin-tech-radar                             0.5.2
  @backstage/plugin-techdocs-backend                       0.12.3
  @backstage/plugin-techdocs                               0.12.14
  @backstage/plugin-user-settings                          0.3.16
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.11.3
  @backstage/test-utils                                    0.2.2
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1
✨  Done in 3.39s.
```

**Comment by Rugvip** [comment]
We don't actually support the `raw` URL format as you show it, but it should hopefully work alright if you switch it out for `blob`: `https://gitlab.host.tld/org/group-name/subgroup-name/service-name/blob/master/swagger.yaml`.

I guess it can be argued that we should support the raw format too, but there's always hidden complexities in supporting more things :grin: If you feel that's something that's worth the effort and you perhaps would like to contribute, you could always open an issue for tracking that.

**Comment by mscam** [comment]
Hello @Rugvip unfortunately last time I tried with "blob" GitLab URLs it didn't work, but I will retry tomorrow 🤞

**Comment by satrox28** [comment]
Hi @mscam @Rugvip 

I tested in my instance with Gitlab and its working fine :).
  definition:
    $text: https://gitlab.host.tld/group-name/sub-groupname/project-name/-/blob/main/openapi.yaml

**Comment by mscam** [comment]
@satrox28 @Rugvip  I took some time to try it now. Unfortunately it doesn't work for me:

<img width="783" alt="Screenshot 2022-02-13 at 14 53 53" src="https://user-images.githubusercontent.com/349166/153756527-a3d7d3b7-81e1-4eae-8d81-e80f654eb3ae.png">

Are `swagger.yaml` files supported?

**Comment by mscam** [comment]
I found out the issue, it looks URLs such as `https://gitlab.host.tld/group-name/sub-groupname/project-name/-/blob/main/openapi.yaml` are actually not supported:

Taken from https://github.com/backstage/backstage/blob/de1f77b71cf1a62f210a465a73516317fd618c3e/packages/integration/src/gitlab/core.ts#L71

```
export function buildRawUrl(target: string): URL {
  try {
    const url = new URL(target);

    const [empty, userOrOrg, repoName, blobKeyword, ...restOfPath] =
      url.pathname.split('/');

    console.log("Empty: " + empty);
    console.log("userOrOrg: " + userOrOrg);
    console.log("repoName: " + repoName);
    console.log("blobKeyword: " + blobKeyword);
    console.log("restOfPath: " + restOfPath);

    if (
      empty !== '' ||
      userOrOrg === '' ||
      repoName === '' ||
      blobKeyword !== 'blob' ||
      !restOfPath.join('/').match(/\.(yaml|yml)$/)
    ) {
      throw new Error('Wrong GitLab URL');
    }

    // Replace 'blob' with 'raw'
    url.pathname = [empty, userOrOrg, repoName, 'raw', ...restOfPath].join('/');

    return url;
  } catch (e) {
    throw new Error(`Incorrect url: ${target}, ${e}`);
  }
}
```

Console Output:

```
empty: 
userOrOrg: group-name
repoName: sub-groupname
blobKeyword: project-name
restOfPath: -,blob,main,openapi.yaml
```

As you can see, `blobKeyboard` is not correctly parsed

**Comment by mscam** [comment]
@satrox28 unless you used a different URL (not including a sub-group), this cannot work with URLs such as `https://gitlab.host.tld/group-name/sub-groupname/project-name/-/blob/main/openapi.yaml`.  `Wrong GitLab URL` should have been raised.

@Rugvip I would be happy to contribute if needed 🙏

**Comment by Rugvip** [comment]
@mscam bit confused tbh. We should really be hitting this https://github.com/backstage/backstage/blob/de1f77b71cf1a62f210a465a73516317fd618c3e/packages/integration/src/gitlab/core.ts#L44

Could you double check that the `-` in your URL is actually a `-` and not some other unicode impostor? :grin:

**Comment by Rugvip** [comment]
Alright, glad it got resolved!
