### ISSUE TITLE
[Plugin] CircleCI: tests

### ISSUE THREAD

**Issue by Nek** [backstage/backstage#949]
Several groups of tests should be implemented:
- [ ] custom hooks
- [ ] API integration
- [ ] UI components

**Comment by kernelgonnapanic** [comment]
Hi! I am new to the repo, but I would like to work on this issue (adding tests to the CircleCi plugin). I plan to inspire myself by a test setup from some other plugin to keep consistency.

**Comment by Rugvip** [comment]
@kernelgonnapanic Thanks, and welcome! :grin:
