### ISSUE TITLE
Sticky header on UserSettingsFeatureFlags

### ISSUE THREAD

**Issue by victormorfin97** [backstage/backstage#9520]
## Feature Suggestion

We would like to add a prop to stick the header on Feature Flag list :
**Header is showing at the start of the list.**
<img width="1592" alt="Screen Shot 2022-02-14 at 9 06 46" src="https://user-images.githubusercontent.com/40499017/153904242-b573016b-944f-4a36-b650-f334d0026ee8.png">
**On scrolling the header disappear**
<img width="1593" alt="Screen Shot 2022-02-14 at 9 06 56" src="https://user-images.githubusercontent.com/40499017/153904263-0a3c5b92-447d-4f0f-8423-7fdc98cb6392.png">

## Possible Implementation
We can add a prop to the component that set the sticky header.

## Context
At Expedia, we usually have a lot of feature flags registerer in our Backstage implementation we are using the UserSettingsFeatureFlags on a component with a custom height and with scroll, but when we start scrolling the header scrolls with the list, so we would like to contribute with this instead of creating a custom component.

**Comment by benjdlambert** [comment]
This seems like a nice feature, is this something you want to contribute?

**Comment by victormorfin97** [comment]
Sure, I would like it. I will start working on this! 😃

**Comment by benjdlambert** [comment]
Perfect! Will assign you! @victormorfin97
