### ISSUE TITLE
[catalog] Deactivated users and possibly groups

### ISSUE THREAD

**Issue by grantila** [backstage/backstage#9579]
We ingest users and groups to the catalog from LDAP, and when doing so we also get "deactivated" users (people who've left the company). It does make sense to have them in the catalog, if there are references to them (e.g. components owned by them), but at the same time, they should probably be filtered out of the catalog index and not show up as being users of a group.

Potentially, the concept of _deactivated_ would make sense for groups as well.

## Feature Suggestion

We should probably standardise (as a core type), a field like this on the `UserEntityV1alpha1` `spec`, such as `deactivated?: boolean`.

WDYT?

**Comment by benjdlambert** [comment]
I think maybe try and extend the model yourself internally first, and let's leave this ticket around to see if it's something that is wanted by others to add to the open source model. Does that work?

**Comment by grantila** [comment]
Sure, we'll go about this internally

**Comment by satrox28** [comment]
Hi @grantila, when you make ldap query, you can skip the deactivated users.
