### ISSUE TITLE
catalog-graph plugin requires a rootEntityRefs

### ISSUE THREAD

**Issue by wittwerch** [backstage/backstage#9603]
## Expected Behavior

I'd like to navigate to the Catalog Graph from the sidebar to browse it. When linking to /catalog-graph from the sidebar, the loading fails the the screen remains empty:

<img width="1629" alt="Screenshot 2022-02-17 at 11 02 52" src="https://user-images.githubusercontent.com/1575445/154452561-a483e4b1-f333-495b-a088-11dc914ce6ee.png">

Navigating from a component card to it works.

## Actual Behavior

I'd like to navigate to the Catalog Graph from the sidebar and start exploring

## Steps to Reproduce

* Install catalog-graph plugin (version 0.2.10) according to the docs
* Add it to App.tsx with the defaults (no props)

```
 <Route path="/catalog-graph" element={<CatalogGraphPage />} />
```

* Add it to the sidebar
```
<SidebarItem icon={GraphicEqIcon} to="catalog-graph" text="Graph" />
```

## Solution

I figured out that the reason is, that the `rootEntityRefs` is undefined. As soon as I adapt the initialState to include a random component, it works.

```
        <CatalogGraphPage
          initialState={{
            selectedKinds: ['Component'],
            rootEntityRefs: ['component:default/microservice-1'],
            selectedRelations: [
              RELATION_CONSUMES_API,
              RELATION_API_CONSUMED_BY,
              RELATION_PROVIDES_API,
              RELATION_API_PROVIDED_BY,
              RELATION_HAS_PART,
              RELATION_PART_OF,
              RELATION_DEPENDS_ON,
              RELATION_DEPENDENCY_OF,
            ],
          }}
        />
```

It would be nice if we could browse catalog graph without a starting point if that's possible. Otherwise that should probably goes into the docs, lost quite a bit of time on it :)

**Comment by loganwedwards** [comment]
Thanks for providing the example. I experienced the same behavior and noticed that the `rootEntityRefs` prop expects `string | string[]`, but looking into the underlying component, it checks against `EntityName`, so the structure to form via string form was not obvious out of the box.

**Comment by freben** [comment]
Hm - then again, how would such a root page even work? What would it show? The graph would need to be "rooted" in something; it wouldn't be possible to show the entire vast catalog, and even cutting it down to starting from "the top" and showing all domains will likely be way too much data for a decent sized org. It's just not made to be a root page. Could it make sense to make an entirely different page with a dedicated purpose, such as maybe showing a highlight of some common domains, or your own owned things, or similar - and offering to show the graph for whichever thing you then click?

**Comment by wittwerch** [comment]
Yes I see your point, somehow a root node has to be selected. Maybe updating the doc would be enough, just that other users don't have to spend that much time on finding the correct settings :)

If you give me a pointer to the doc I'm happy to contribute a section about that

**Comment by jhaals** [comment]
Isn't the already regular search good enough? Search the entity and when you open it you see the graph in a tab or widget.
