### ISSUE TITLE
[Catalog] Orphan Management View

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#9606]
## Feature Suggestion

It would be really helpful to have a view that would allow you to see all the orphans in your catalog. This view would the option to view the orphan in detail - the normal entity view - and would also have an option to delete each orphan (as well as all)

**Note:** We have built this and would like to contribute it but would like some guidance as to where it should go. Also implementing the delete needs to be added but we wanted to be able to use `DeleteEntityDialog` but we are unsure the best way forward: https://github.com/backstage/backstage/blob/47dac4081978cfa66ab6f5035b1191c67b6ebb9c/plugins/catalog/src/components/EntityOrphanWarning/EntityOrphanWarning.tsx#L48

## Possible Implementation

This could be simply a page with a table at some route, perhaps `/catalog/orphans`. Here's a quick example:

![image](https://user-images.githubusercontent.com/67169551/154464177-366bcbc2-a7fa-478e-b76a-163348fc6584.png)

Though this is currently missing the delete option but it would just be part of the actions column

## Context

What we have found as we have been developing our catalog is that things change and move and we end up with odd items in our catalog or in the various graphs. By keeping the orphans cleared this reduces the confusion. Using a script to manage this has been fine for a few users but as others are working in this area a more easy to use option has been helpful

**Comment by freben** [comment]
For orphaning _specifically_, it might make sense to actually just make it one more filter in the regular catalog home page - mightn't it? That lets you do things like looking for only orphaned things that are owned by you, or are of a specific kind, etc.

**Comment by awanlin** [comment]
That's actually a great idea, not something I had considered! It also seems very much more user friendly as I have no idea how my suggested idea would be accessed other than by people that just know the route. I'll take this away and see what I can build. Should be pretty easy, it's nearly like this example: https://backstage.io/docs/features/software-catalog/catalog-customization#docsNav

**Comment by freben** [comment]
Maybe a single Advanced dropdown with checkboxes perhaps, modeled after the "tags" one? "Is orphaned", "Has errors" (based on `(entity as AlphaEntity).status?.items?.length > 0`) etc https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/entity/Entity.ts#L74

**Comment by awanlin** [comment]
Oh, that sounds even better. For sure, will head that direction.

**Comment by jselleck-sans** [comment]
This would sure be useful for user entities!!!

**Comment by awanlin** [comment]
This has turned out to be a little harder than I expected. Still working on it just slowly ;)

**Comment by awanlin** [comment]
I've managed to make some really good headway on this, just sorting out some UI niggles and adding tests

**Comment by awanlin** [comment]
Alright, UI is working as expected now, will tackle tests next. Here's a quick demo:

https://user-images.githubusercontent.com/67169551/174493584-ff06b4d9-290f-485f-97d8-a3f48580d273.mov

I manually added the 'backstage.io/orphan' annotation to fake out an actual orphan for the `artist-lookup` component (this will also show up as an error because I don't think these are allowed to be added by hand) and then added an invalid tag to the `petstore` component to create an error case. 

@freben I know you suggested using a dropdown for this, what do you think of how I've implemented it here? I'm having a hard time getting this into a dropdown to be honest, my brain is having a hard time figuring out how to handle the two different filters that way. If you have some pointers or suggestions that would be awesome!
