### ISSUE TITLE
CatalogKindHeader drop down is not discoverable

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#9616]
## Expected Behavior

I've talked to a few users of our Backstage instance and almost all did not realize you can interact with the catalog kind header to see more then just components. Perhaps some additional visual queues beyond the drop down adornment could be used to help indicate this.

![image](https://user-images.githubusercontent.com/6507159/154498207-52617155-bd50-4868-bf7a-d51e383e60d6.png)

## Actual Behavior

The catalog kind picker looks like a label and you need to pay attention to the fact there is a drop down adornment to the right which indicates you can interact with it.

**Comment by benjdlambert** [comment]
Yep - this is a good point, @katz95 do you have any input here? :pray:

**Comment by freben** [comment]
An off-the-cuff suggestion - what if that control (`CatalogKindHeader`) had an optional `variant` prop that could be `"header"` (default, current style) or `"filter"` (looks and behaves like sidebar things). Then you just place it where it makes sense in your catalog page. Would that work?

**Comment by freben** [comment]
I would even personally be up for changing the default page (`DefaultCatalogPage`) to render it that way because I really agree about the confusion. Or heck, even to have it in _both_ places. But maybe let's await design input on that bit.

**Comment by andrewthauer** [comment]
A variation on this could be to add `CatalogKindPicker` which is like entity type, etc. and then just make the header a header. Possibly having the header update it's label based on the selected kind.

**Comment by freben** [comment]
Sure - that naming makes better sense!

**Comment by katz95** [comment]
This looks great @andrewthauer - thanks for the suggestion! Can we use the same caret icon that we use from Material (as opposed to the triangle)?

**Comment by benjdlambert** [comment]
@katz95 so I think the general consensus is that we're feeling that it's not as discoverable as we would like, and maybe want to ditch the caret all together as that menu is a little hidden. Do you have maybe some ideas as to what we could do? Sorry if that was unclear 😄

**Comment by katz95** [comment]
Got it, another alternative is to replace that header with tabs, as seen in this component: https://backstage.io/storybook/?path=/story/navigation-tabs--default

**Comment by katz95** [comment]
The explore page in the demo also has a tabbed variation: https://demo.backstage.io/explore

**Comment by andrewthauer** [comment]
Hi @katz95. This page used to have tabs, but was changed to accommodate a drop down since the list of kinds & types of entities is determined by what is in the catalog and not a finite list. The contents of each uses the same components as well. So I think a drop down like component is likely the best option for entity kind. Especially considering the list of kinds is unlikely to be more then 10-20 in extreme cases I would hope.

So, I'm thinking something like below might be more obvious. However, the header above the table that shows the selected kind is a bit redundant at this point. It could just say `Catalog`, but I believe that's already on most page headers so also redundant. Maybe that's a non issue. 

```
## <Selected Kind>

------------------
| kind picker ⬇️ |
------------------

... other filters

```

Another option would be to keep the head as a picker and also include an more standard drop down for kind like the other filters.

**Comment by freben** [comment]
As a larger scale discussion, I'd even like to revamp the filtering to be more like a list of active filter "pills" at the top and you remove filters with a cross in the pill and add more with a plus sign where you pick the filter type you want etc ... But then again, this view is supposed to kind of take a step back eventually and be replaced with more purposeful Explore / Manage views that are prefiltered more heavily. So not sure how much time to spend on such a revamp

**Comment by freben** [comment]
And agreed - not sure the kind warrants being an entirely stand-out, special-treatment filter design thing at this point? 🤔

**Comment by katz95** [comment]
Gotcha! I agree that it makes sense to have the kind picker be a standard drop-down, like the one shown for "Type" (as shown below). I also wonder if it's worth allowing users to choose more than one type of 'kind' - what if I want to see Locations _and_ Groups? Having a checkbox in the dropdown might help with that, if that's a relevant user scenario.


<img width="243" alt="Screenshot 2022-02-24 at 5 29 44 PM" src="https://user-images.githubusercontent.com/61153904/155566445-1f0cbf49-a9fc-4e74-a14a-f22ea1d76550.png">
"

**Comment by andrewthauer** [comment]
I still think this is relevant.

**Comment by Crevil** [comment]
@katz95 we just had a discussion internally on that idea actually. By default many developers at Lunar expect to see everything by default and the be able to trim it down. Currently the dropdown doesn't support an "all" option.

**Comment by benjdlambert** [comment]
@Crevil do you want to try and contribute something and open a PR for this?

**Comment by Crevil** [comment]
Sure thing 👍 I'll give it a go @benjdlambert

**Comment by Crevil** [comment]
I wonder if the `EntityKindPicker` is actually just what needs an implementation ? It was added without an implementation in #5643. WDYT @timbonicus ? Anything I'm missing?

**Comment by awanlin** [comment]
As we were running into this as well our solution was to just add this to the `Root.tsx`:

![image](https://user-images.githubusercontent.com/67169551/182883233-67aae9ef-db10-43b7-a12c-10dd313cf6f0.png)

We used the existing `SidebarSubmenu` with a `SidebarSubmenuItem` for each Kind, we left out Locations as they weren't something we felt needed to exposed here. The other benefit is being able to jump directly into a Kind list in the catalog from other plugins.

**Comment by Crevil** [comment]
That is actually pretty nice @awanlin . Thanks for sharing.

I have something working now with a multiple choice Kind picker but it has some unforseen consequences. Currently it modifies the `EntityKindFilter` but expanding it to support multiple values. This however breaks any column logic that makes decision on the "current kind", eg. show "this" column if kind is "that" as we do here: https://github.com/backstage/backstage/blob/f850661749065c36eae1c263b80e15a48f744c43/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L79

**Comment by Crevil** [comment]
@katz95 do you have an opinion here for the Sidebar variant? It defeats the possibility of showing multiple kinds at once, but might just prove to be the better solution after all?

**Comment by Crevil** [comment]
You can see a draft of the kind picker here: https://github.com/backstage/backstage/pull/12974

**Comment by awanlin** [comment]
@Crevil to be honest doing both would be awesome! Keep going with what you are doing as I think the features you are trying to add - all, multi-select - are worth having

**Comment by GoFightNguyen** [comment]
Like the original post, through user interviews we have also discovered that almost no one realizes the catalog kind header is interactive until they are shown

So I'm "upvoting" this so that the default will be a better UX.

**Comment by freben** [comment]
Oh no - I see that `EntityKindPicker` does exist as an optional picker to put in your sidebars, but [its visual parts haven't been implemented yet](https://github.com/backstage/backstage/blob/cfb35984105fb37c23f5e0c425c99543f8428516/plugins/catalog-react/src/components/EntityKindPicker/EntityKindPicker.tsx#L53) :/ It's a pretty easy thing to add, [loading the available kinds like the header does](https://github.com/backstage/backstage/blob/cfb35984105fb37c23f5e0c425c99543f8428516/plugins/catalog/src/components/CatalogKindHeader/CatalogKindHeader.tsx#L68). And finally adding it to [the default list of controls](https://github.com/backstage/backstage/blob/cfb35984105fb37c23f5e0c425c99543f8428516/plugins/catalog/src/components/CatalogPage/DefaultCatalogPage.tsx#L87). Anyone up for doing that?

**Comment by Crevil** [comment]
I made a rough draft in https://github.com/backstage/backstage/pull/12974 of this but turned out there were some things breaking with the kind filter. Maybe you can help answer some of the concerns in the PR? 

https://github.com/backstage/backstage/pull/12974

**Comment by freben** [comment]
@Crevil I'd love for it to NOT be a multi select though. It'd be a MUCH smaller change. I experimented a bit on my hack time to just mimic what the heading thing does, but got frustrated with keeping the two properly in sync, so dropped it for now.

**Comment by Crevil** [comment]
So keeping it as single select like the existing one? That would make it simpler to implement I'm sure. Maybe I can find time next week to give it another go 👍

**Comment by Crevil** [comment]
New PR ready for review with single selection and also managed to make the state propagate correctly to the header. 🎉 

https://github.com/backstage/backstage/pull/13869

**Comment by awanlin** [comment]
> As we were running into this as well our solution was to just add this to the `Root.tsx`:
> 
> ![image](https://user-images.githubusercontent.com/67169551/182883233-67aae9ef-db10-43b7-a12c-10dd313cf6f0.png)
> 
> We used the existing `SidebarSubmenu` with a `SidebarSubmenuItem` for each Kind, we left out Locations as they weren't something we felt needed to exposed here. The other benefit is being able to jump directly into a Kind list in the catalog from other plugins.

I've submitted #14386 to add this ^
