### ISSUE TITLE
How to read repo name from RepoUrlPicker field?

### ISSUE THREAD

**Issue by sharadpattanshetti** [backstage/backstage#9659]
I am using the RepoUrlPicker as below and need to get the repo name out of it. I tried ${{ parameters.repoUrl.repoName }} and ${{ parameters.repoUrl.repoName | parseRepoUrl }} but none of them work.

`- title: Choose a SCM Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - git.tools.org.com`

**Comment by freben** [comment]
Could you try something like `${{ (parameters.repoUrl | parseRepoUrl).repo }}`?

**Comment by sharadpattanshetti** [comment]
sure @freben, let me try that.

**Comment by sharadpattanshetti** [comment]
It worked, Thank you @freben

**Comment by shailendra-ahir-cbre** [comment]
HI @freben @Rugvip , Unrelated to the above issue but, Can we use the parseRepoUrl like this ? 

${{ (parameters.repoUrl | parseRepoUrl).host === 'dev.azure.com' ? steps.azure.output.remoteUrl : steps.github.output.remoteUrl }}

**Comment by sharadpattanshetti** [comment]
Hi @shailendra-ahir-cbre did above expression work for you?

**Comment by shailendra-ahir-cbre** [comment]
${{ steps.azure.output.remoteUrl if (parameters.repoUrl | parseRepoUrl).host === 'dev.azure.com' else steps.github.output.remoteUrl }}


The above expression worked.  
And to read repo name : ${{ (parameters.repoUrl | parseRepoUrl).repo }}

**Comment by sharadpattanshetti** [comment]
Thanks @shailendra-ahir-cbre , this works.

**Comment by owainow** [comment]
- id: fetch-remote
      name: Fetch Remote Repo
      action: fetch:plain
      input:
        url: https://${{ (parameters.argoRepoUrl | parseRepoUrl).host  }}/${{ (parameters.argoRepoUrl | parseRepoUrl).owner  }}/${{ (parameters.argoRepoUrl | parseRepoUrl).repo  }}.git 
        targetPath: ./my-app
        values:
          projectName: ${{ parameters.name }}
          appRepoUrl: ${{ parameters.appRepoUrl }}

**Comment by rdnkmrr** [comment]
Is there a way to dynamically retrieve the values from the parameters to the allowedRepos in repoURLPicker? I have tried providing something similar to the approach below, but it doesn't work. Can anyone provide some insights or suggestions?

allowedRepos:
              
${{parameters.name}}
