### ISSUE TITLE
Improve error handling when trying to use RAW github urls in annotations

### ISSUE THREAD

**Issue by sblausten** [backstage/backstage#9668]
Improve error messaging for invalid Github annotation urls to allow users to fix problems with annotations themselves.

Currently there is not much handling around common scenarios of invalid annotation urls that would allow a user to know what the problem is and fix it. They just get a generic `NotAllowedError(Reading from xxx is not allowed)`

## Feature Suggestion

When a user tries to link to a raw version of a file in Github i.e. `https://raw.githubusercontent.com/sonallux/spotify-web-api/main/official-spotify-open-api.yml` in an api spec annotation they just see `NotAllowedError(Reading from https://raw.githubusercontent.com/sonallux/spotify-web-api/main/official-spotify-open-api.yml is not allowed)` 

i.e. 
```
definition: 
  $text: https://raw.githubusercontent.com/sonallux/spotify-web-api/main/official-spotify-open-api.yml
```

It would be more helpful to explain that only valid Github web view addresses are allowed so users can fix this themselves.

## Possible Implementation

Add another fallback before the default error message here https://github.com/backstage/backstage/blob/9e8507305c90c790f47b292339ceccbfeb602458/packages/backend-common/src/reading/UrlReaderPredicateMux.ts#L90 

## Context

Allow users to fix problems with annotations themselves

**Comment by freben** [comment]
Maybe there's an argument to be had that we should be flexible and supporting raw urls too ... but that may be a bit of a bigger endeavor.

Is this type of checking something you might like to even contribute? One potential challenge is, should it be a fatal error that stops processing, or just some form of warning? We don't really have a nice mechanism for surfacing warnings unfortunately; logging isn't something the end user gets to see easily.
