### ISSUE TITLE
[RFC] Shifting release day from Thursday to Tuesday

### ISSUE THREAD

**Issue by jhaals** [backstage/backstage#9699]
**Status:** Open for comments

This is a lightweight proposal suggesting a change of release day from Thursday to Tuesday.

The maintainer team has found the Thursday release day to be problematic from a few standpoints:

- Thursday often collides with our monthly hackdays leading to less hacking and potentially less features and skunk work on Backstage.
- In the event of issues with the release those often surface late in the day or potentially the next day which lead to emergency releases on a Friday.
- Friday is also a mandatory day off after on-call leading to limited staffing to address issues and supporting users with questions related to the release.

Our proposal is therefore to change the release day to Tuesday leaving more working days for support and potential follow up work. If there are no strong objections to this proposal we hope to be able to shift to Thursday releases in a couple of weeks.

**Comment by djamaile** [comment]
I like it! Was there any specific reason why Monday was not chosen?

**Comment by jhaals** [comment]
> I like it! Was there any specific reason why Monday was not chosen?

Glad to hear that :) 
Monday is a bit like learning to use a computer again until you've caught up with issues and PRs. 😁
Jokes aside we are having a sync on Monday afternoons going through all new activity since last sync so it's good to do that before the release.

**Comment by djamaile** [comment]
@jhaals makes sense, thanks for the answer 😄

**Comment by jhaals** [comment]
Release day will shift in a couple weeks! Thanks for feedback in form of thumbs up 😁
