### ISSUE TITLE
Customize placeholder for Search Input in Table Component

### ISSUE THREAD

**Issue by marlonmg09** [backstage/backstage#9704]
## Feature Suggestion

Allow to customize the placeholder in the Search Input for the Table Component.
<img width="1688" alt="Screen Shot 2022-02-21 at 12 07 14" src="https://user-images.githubusercontent.com/24708046/155007689-e6cc2335-c638-448d-9079-bd4cd31928f0.png">

## Possible Implementation

Add the `placeholderText` attribute in the options prop and add the functionality in the Table Component for use that value and display the custom text in the placeholder for the Search Input.

## Context

At Expedia we make use of that Component quite a bit and we want to specify by the placeholder for which field in the table the search is perform, and with that give more information to the user about the search functionality in the table.

**Comment by freben** [comment]
May I ask what text you'd like to put there? Maybe there's a case to be made for changing the default text - I am not fond of it being "search", which kind of is a reserved word for the app-level search - and it's actually more of a filter than a search.

**Comment by freben** [comment]
And honestly - I'm more and more feeling that it's time to start looking into an i18n library, that would let users seamlessly change stuff like this in a central place instead of having to supply props all over...

**Comment by marlonmg09** [comment]
Or to intention is to display for example "Search by name" to let the user know for which field we're doing the search/filter for each table.

But if we use the i18n library we need to specify the value in a variable and then link it into the default placeholder, or how is the approach that you suggest?

**Comment by freben** [comment]
@marlonmg09 It would depend on the i18n library that we pick in the end. But most likely, it would be something like a file in your `packages/app` that has something like

```ts
export const languageOverrides = {
  'backstage:catalog:entities-table:filter:placeholder': 'Search by name',
};
```

along with all of the other overrides.
