### ISSUE TITLE
upgrade to recharts 2.x

### ISSUE THREAD

**Issue by freben** [backstage/backstage#9706]
## Feature Suggestion

Upgrade to `recharts` version 2.x for the entire project.

There are no migration guides for `recharts` 1->2 as far as we know, and there may be some work to make sure that the upgrade goes through properly. We would appreciate help from the community with making that happen!

## Context

We get reminded occasionally by dependabot that this upgrade should happen (see e.g. https://github.com/backstage/backstage/pull/9638), but we think that it'll take a slightly more concerted effort.

**Comment by benjdlambert** [comment]
Closing as duplicate of #12609
