### ISSUE TITLE
Error building new application - npx @backstage/create-app 2

### ISSUE THREAD

**Issue by LoveraSantiago** [backstage/backstage#9734]
I have followed the steps in [create-an-app](https://backstage.io/docs/getting-started/create-an-app) when I have tried the command npx @backstage/create-app the process has stopped with erro while executing yarn install

## Expected Behavior

The command finished correctly

## Actual Behavior

`gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/which/which.js:10:17)
gyp ERR! stack     at /home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/which/which.js:54:21)
gyp ERR! stack     at /home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/which/which.js:69:33)
gyp ERR! stack     at /home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/which/which.js:80:22
gyp ERR! stack     at /home/user/my-backstage-app/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/user/my-backstage-app/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 4.4.0-19041-Microsoft
gyp ERR! command \"/home/user/.nvm/versions/node/v16.14.0/bin/node\" \"/home/user/my-backstage-app/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/user/my-backstage-app/node_modules/cpu-features
gyp ERR! node -v v16.14.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok"
error /home/user/my-backstage-app/node_modules/@vscode/sqlite3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/user/my-backstage-app/node_modules/@vscode/sqlite3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.14.0 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
(node:2376) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/my-backstage-app/node_modules/@vscode/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.cache/node-gyp/16.14.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.cache/node-gyp/16.14.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.cache/node-gyp/16.14.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user/my-backstage-app/node_modules/@vscode/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/which/which.js:10:17)
gyp ERR! stack     at /home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/which/which.js:54:21)
gyp ERR! stack     at /home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/which/which.js:69:33)
gyp ERR! stack     at /home/user/my-backstage-app/node_modules/@npmcli/run-script/node_modules/which/which.js:80:22
gyp ERR! stack     at /home/user/my-backstage-app/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/user/my-backstage-app/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 4.4.0-19041-Microsoft
gyp ERR! command "/home/user/.nvm/versions/node/v16.14.0/bin/node" "/home/user/my-backstage-app/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/user/my-backstage-app/node_modules/@vscode/sqlite3
gyp ERR! node -v v16.14.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
yarn install v1.17.3
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-android-arm64@0.14.23: The platform "linux" is incompatible with this module.
info "esbuild-android-arm64@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-android-arm64@0.14.23: The CPU architecture "x64" is incompatible with this module.
info esbuild-freebsd-64@0.14.23: The platform "linux" is incompatible with this module.
info "esbuild-freebsd-64@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-freebsd-arm64@0.14.23: The platform "linux" is incompatible with this module.
info "esbuild-freebsd-arm64@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-freebsd-arm64@0.14.23: The CPU architecture "x64" is incompatible with this module.
info esbuild-darwin-arm64@0.14.23: The platform "linux" is incompatible with this module.
info "esbuild-darwin-arm64@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-darwin-arm64@0.14.23: The CPU architecture "x64" is incompatible with this module.
info esbuild-darwin-64@0.14.23: The platform "linux" is incompatible with this module.
info "esbuild-darwin-64@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-32@0.14.23: The CPU architecture "x64" is incompatible with this module.
info "esbuild-linux-32@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-arm@0.14.23: The CPU architecture "x64" is incompatible with this module.
info "esbuild-linux-arm@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-mips64le@0.14.23: The CPU architecture "x64" is incompatible with this module.
info "esbuild-linux-mips64le@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-arm64@0.14.23: The CPU architecture "x64" is incompatible with this module.
info "esbuild-linux-arm64@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-riscv64@0.14.23: The CPU architecture "x64" is incompatible with this module.
info "esbuild-linux-riscv64@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-ppc64le@0.14.23: The CPU architecture "x64" is incompatible with this module.
info "esbuild-linux-ppc64le@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-netbsd-64@0.14.23: The platform "linux" is incompatible with this module.
info "esbuild-netbsd-64@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-openbsd-64@0.14.23: The platform "linux" is incompatible with this module.
info "esbuild-openbsd-64@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-s390x@0.14.23: The CPU architecture "x64" is incompatible with this module.
info "esbuild-linux-s390x@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-sunos-64@0.14.23: The platform "linux" is incompatible with this module.
info "esbuild-sunos-64@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-windows-arm64@0.14.23: The platform "linux" is incompatible with this module.
info "esbuild-windows-arm64@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-windows-arm64@0.14.23: The CPU architecture "x64" is incompatible with this module.
info esbuild-windows-32@0.14.23: The platform "linux" is incompatible with this module.
info "esbuild-windows-32@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-windows-32@0.14.23: The CPU architecture "x64" is incompatible with this module.
info esbuild-windows-64@0.14.23: The platform "linux" is incompatible with this module.
info "esbuild-windows-64@0.14.23" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info This module is OPTIONAL, you can safely ignore this error
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  executing     yarn install ✖

Error: Could not execute command yarn install

It seems that something went wrong when creating the app 🤔

🔥  Failed to create app!`

## Steps to Reproduce

1. Step 1 npx @backstage/create-app
2. wait
3. Get the error

## Context

Running with local machine windows with WSL - ubuntu 20.04.3 LTS

## Your Environment

 yarn backstage-cli info
yarn run v1.17.3
warning package.json: No license field
$ /home/user/node_modules/.bin/backstage-cli info
OS:   Linux 4.4.0-19041-Microsoft - linux/x64
node: v16.14.0
yarn: 1.17.3
cli:  0.14.0 (installed)

Dependencies:
  @backstage/cli-common        0.1.8
  @backstage/cli               0.14.0
  @backstage/config-loader     0.9.5
  @backstage/config            0.1.15
  @backstage/errors            0.2.2
  @backstage/release-manifests 0.0.2
  @backstage/types             0.1.3
Done in 7.47s.

- Browser Information: NA

- Output of `yarn backstage-cli info`: 

```text
 yarn backstage-cli info
yarn run v1.17.3
warning package.json: No license field
$ /home/user/node_modules/.bin/backstage-cli info
OS:   Linux 4.4.0-19041-Microsoft - linux/x64
node: v16.14.0
yarn: 1.17.3
cli:  0.14.0 (installed)

Dependencies:
  @backstage/cli-common        0.1.8
  @backstage/cli               0.14.0
  @backstage/config-loader     0.9.5
  @backstage/config            0.1.15
  @backstage/errors            0.2.2
  @backstage/release-manifests 0.0.2
  @backstage/types             0.1.3
Done in 7.47s.
```

**Comment by SteffanVerlaan** [comment]
I had a similar problem. Haven't been able to fix it though.
Curiously this only happened with the SQLite option, Postgres works fine.

**Comment by freben** [comment]
I see `Error: not found: make`.

You may need to install build-essentials.

**Comment by peimanja** [comment]
> I see `Error: not found: make`.
> 
> You may need to install build-essentials.

Had the same issue. In my case I was missing `cmake`
