### ISSUE TITLE
[Plugin] Git Stats

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#9735]
## Summary

Git holds a treasure trove of valuable information. It would be awesome if we had a plugin that would be able to surface this information.

The work to create a bare clone of a git repo has already been done. This lets you get just the `.git` folder where all the stats are. From here we can use isomorphic-git to pull the logs though this is pretty limited and we may wish to look at using simple-git or even interacting with git directly.

**Note:** We have built some of this already to pull top contributors and would like to contribute it. This is what a sample of this would look like:

![image](https://user-images.githubusercontent.com/67169551/155173326-a272f1a9-b285-4c6b-9773-d564ba48eaa6.png)

## Project website (if applicable)

isomorphic-git - https://isomorphic-git.org/
simple-git - https://github.com/steveukx/git-js

## Context

Being able to get insight into git repos in Backstage provides another source of information for those looking at entities in the catalog or even aggregated up at the team level or on the home page!

**Comment by freben** [comment]
Hm! Sure - but a bare clone still includes the history and file blobs, does it not? Even though it doesn't put the current HEAD into the working directory. Did a quick googling and it sounds like it's actually tricky to get _only_ metadata-like things (such as commit markers) without the associated file data - but I'm extremely open to being wrong here :D

A lot of the providers probably have custom APIs to fetch top contributors, rather than going via git at all. Could it make sense to have this wrapped up and performed in the most efficient way possible per provider?

**Comment by awanlin** [comment]
Yes, this is true, bare clone is a tricky thing. Using `noCheckout` and `depth: 0` (all history) gets us just the `.git` folder without all the other files that we don't use for this, it's not perfect but for this purpose works well.

I agree, many other SCM tools have APIs for contributors but in our case both Azure DevOps and Bitbucket Server do not. And I have a feeling this has been built in the GitHub and GitLab plugins.

The heart of what I was hoping with this was help building a way to pull other git stats out. Contributors was the low hanging fruit for us. We use a modified git flow and it would be cool to see perhaps the age of code that has not been merged into `master`.

**Comment by regicsolutions** [comment]
Here's a sample implementation I came across that calculates the four DevOps Metrics identified in DORA's 2017 State of DevOps Report using public REST endpoints available in Atlassian's software (Jira, Bitbucket Server, Bamboo) and Jenkins.

https://bitbucket.org/atlassianlabs/devops-metrics/src/master/

**Comment by awanlin** [comment]
As this has turned out to be a flaky plugin on our side we won't be moving forward with open sourcing it at this time. If something changes we'll revisit it.
