### ISSUE TITLE
[RFC] Improvements to the Scaffolder Publish Action for Setting Author and Commit Message

### ISSUE THREAD

**Issue by NishkarshRaj** [backstage/backstage#9736]
**Status:** Open for comments

## Need

Currently, we have the following default author and commit message for Scaffolder:

<img width="997" alt="Screenshot 2022-02-22 at 9 47 34 PM" src="https://user-images.githubusercontent.com/35298207/155174428-1788ccf3-c0f4-4c4b-99fb-35385751caa9.png">

```yml
scaffolder:
  defaultAuthor:
    name: Scaffolder
    email:  scaffolder@backstage.io
  defaultCommitMessage: 'Initial commit'
```

We must be able to override these, there is an approach which is mentioned below under the `Alternatives` section.

With the latest changes in the Scaffolder by @benjdlambert - we are now capable of utilizing a signed-in user's secret credentials to publish repositories to VCS. I think we should modify the `publish` actions for different VCS providers to override the default author and commit message at the time of the creation of the new repository while using the Scaffolder. 

## Proposal

Make changes to the `publish` action for different VCS providers. 

For sample, we can view the inputs `publish:gitlab` action takes:

<img width="1229" alt="Screenshot 2022-02-22 at 9 56 34 PM" src="https://user-images.githubusercontent.com/35298207/155175331-21f7c0af-8912-47a6-b407-6e3bbfc17dfb.png">

Bikeshedding the naming exercise, I feel we should add a few more inputs like:

- `gitUserName`
- `gitUserEmail`
- `gitCommitMessage`

## Alternatives

The only way to override the default Author name and commit message is by defining your own default values in the `app-config.yaml` as described [here](https://backstage.io/docs/features/software-templates/configuration#publishing-defaults).

I feel that this is a very strict approach since for an organization with multiple teams, a single author won't suffice and different teams might have their own regex patterns for commit messages.

**Comment by shvmbisht** [comment]
https://github.com/backstage/backstage/pull/9859 @benjdlambert @freben @NishkarshRaj
