### ISSUE TITLE
[integration] [discovery] [Bitbucket Cloud] higher efficiency and multiple catalog files support by using code search

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#9765]
## Feature Suggestion

Create Location entities only for catalog files which exist. Current behavior adds Location entities with optional presence for each repository.

Additionally, we could support multiple catalog files (e.g., monorepo) using different path filter patterns.

Possible values for the `catalogPath` parameter:

- `/catalog-info.yaml` (absolute path)
- `catalog-info.yaml` (any dir; incl. example above)
- `/nested/path/catalog-info.yaml` (absolute path)
- `nested/path/catalog-info.yaml` (within any dir; incl. example above)
- `/nested/*/catalog-info.yaml` (one or more dirs allowed as replacement for `*`)
- `nested/*/catalog-info.yaml` (as example before, but without limit that `nested` is located within the root dir)

## Possible Implementation

Current discovery URL can look like `https://bitbucket.org/workspaces/my-workspace?catalogPath=my/nested/path/catalog.yaml` (see https://backstage.io/docs/integrations/bitbucket/discovery#bitbucket-cloud for complete list of options).

We could introduce a parameter `search=true` to activate using code search without breaking the existing behavior.

Bitbucket Cloud offers the code search API which could be used to find files only (excluding code/content matches).

Possible search query: `"catalog-info.yaml" path:catalog-info.yaml`
(For the `path` filter any of the example above could be used. The first part is required and could be extracted from the path provided.)

Alternatively, the whole query could be made accessible to the user/discovery URL config by e.g. using the existing `q` parameter (syntax and feature set are completely different though) or another parameter.

## Context

Using the discovery with Bitbucket Cloud, you can run into rate limits very quickly. Esp. if you have many repositories.
By registering Locations with present catalog file only, we can reduce the number of requests for the refresh cycle to a minimum and reduce the number of irrelevant Location entities stored.

**Comment by freben** [comment]
An initial thought: be careful about supporting too many syntaxes :) Especially the relative ones stand out. If the underlying platform changes or so, it may turn out to be almost impossible to keep supporting them. Maybe `*/filename` and `/filename` are the only ones we actually need in order to satisfy the vast majority of people.

But yeah, pruning the result set to only things that actually have any chance of containing matches sounds totally sensible 😅

**Comment by freben** [comment]
BTW this touches on an even more extreme possible future extension of this idea ... What if you had an entity provider that performed this search, _and fetched_ those resulting entities and emitted them directly. No intermediate locations at all. If the search result contains a head hash or etag or so, the provider could be smart enough to only fetch things that it knows has changed.

**Comment by pjungermann** [comment]
> Maybe `*/filename` and `/filename` are the only ones we actually need in order to satisfy the vast majority of people.

I will need myself `parentDir/filename` (relative) which could be the same as `*/parentDir/filename`.

>  it may turn out to be almost impossible to keep supporting them.

I guess we could fall back to post-filtering as it is used now for project and repo at both, Bitbucket Cloud and Bitbucket Server.

At the end though, we could just refer to what is available for the `path` filter at Bitbucket Cloud by linking to their docs instead of limiting it in any specific value set/syntax at Backstage itself. And people can easily try it at the code search themselves.

**Comment by pjungermann** [comment]
> What if you had an entity provider that performed this search,  and fetched those resulting entities and emitted them directly.

Yeah.. I thought about it. I like providers more than processors as they "own" their produced entities and take care of orphaned ones.

> If the search result contains a head hash or etag or so, the provider could be smart enough to only fetch things that it knows has changed.

That is a great idea. I guess we cannot really get an etag (e.g., doing a HEAD request would still be a request counted), but we can use the commit hash as reference (basically, some sort of identifier/version - to abstract it a bit more).

With this, we should be able to identify for which Location there is a new entity. With "Location" as a possible virtual idea (e.g., just an annotation to know the origin Location/URL for a persisted entity),

**Comment by freben** [comment]
The drawback of using a provider though is that you would invent a whole lot of supporting machinery to mimic the internal processing loops, in terms of distributing load. Processors even out the work across catalog nodes, doing one location at a time. A provider - in its basic form - would be solely responsible for the mass import of maybe thousands of things at once, on a single worker. Especially in the empty-state, first-run situation.

As mentioned, you could counteract this by inventing some statefulness and machinery around things, but it'd be a lot of reinventing of wheels.

And maybe, just maybe - it'll turn out that in reality, even an entire org with thousands of employees, don't change their remotes _all that often_ ... all things considered. Maybe it'll turn out that after the initial ingestion, the next runs will in 90% of the time do absolutely nothing, and in the remaining 10% of the time have only one or two files to deal with.

**Comment by pjungermann** [comment]
I didn't really look much into the provider setup, yet. In general, it sounds like something all providers would be interested in though (re spreading the load).

Overall, an even-based setup as primary ingestion solutions sounds like the best fit.
Initial ingestions or healings could be solved differently without any processing loop.

**Comment by pjungermann** [comment]
@freben I realized that the current wildcard filters for projects or repos are way more mighty (undocumented), but not sure if you would like to have this documented. What happens under the hood is that the `*` wildcard will be replaced by the RegExp version `.*` and all converted to a RegExp instance. Means, those fields have full support (just need to remove this minor transformation). The function doing this conversion is called `escapeRegExp` which is a bit misleading as it not escaping anything. Personally, I like to have this reg exp support, but not sure how you see it on your end.

**Comment by pjungermann** [comment]
another caveat:
So far I planned to reuse the existing `catalogPath` parameter. The only challenge might be that this parameter accepts a relative path which the gets converted into an absolute path considering the root of the project  (e.g., `catalogPath=my/path/catalog-info.yaml` -> used catalogPath `/my/path/catalog-info.yaml`).

With code search and using its `path:xyz` filter, people could state absolute paths vs relative ones with different meaning

- `/catalog-info.yaml` (absolute path)
- `catalog-info.yaml` (any dir; incl. example above)

Considering the option

- `/nested/*/catalog-info.yaml` (one or more dirs allowed as replacement for *)

it could be possible to express

- `catalog-info.yaml`  -> `/*/catalog-info.yaml`

And sticking with the current way of how `catalogPath` is used, we could omit the leading `/`, too

- `?catalogPath=catalog-info.yaml` -> `/catalog-info.yaml`
- `?catalogPath=*/catalog-info.yaml` -> `/*/catalog-info.yaml` (or `catalog-info.yaml`)
- `?catalogPath=nested/*/catalog-info.yaml` -> `/nested/*/catalog-info.yaml`
- `?catalogPath=*/nested/*/catalog-info.yaml` -> `/*/nested/*/catalog-info.yaml` (or `nested/*/catalog-info.yaml`)
- etc.

I would prefer to make it explicit though using the values as at the feature suggestion above, though.

Any thoughts?

**Comment by pjungermann** [comment]
Actually, passing `/*/catalog-info.yaml` at code search works exactly like `catalog-info.yaml`

So, instead of

> `/catalog-info.yaml` (absolute path)
> `catalog-info.yaml` (any dir; incl. example above)
> `/nested/path/catalog-info.yaml` (absolute path)
> `nested/path/catalog-info.yaml` (within any dir; incl. example above)
> `/nested/*/catalog-info.yaml` (one or more dirs allowed as replacement for `*`)
> `nested/*/catalog-info.yaml` (as example before, but without limit that `nested` is located within the root dir)

the options might might be sufficient as explanation:

`/catalog-info.yaml`
`/*/catalog-info.yaml`
`/nested/path/catalog-info.yaml`
`/nested/*/catalog-info.yaml` _(maybe not needed, too)_
