### ISSUE TITLE
Techdocs search is broken when navigating from other techdocs

### ISSUE THREAD

**Issue by sbellam1187** [backstage/backstage#9769]
## Expected Behavior
We should see search results of current techdocs we are in 

## Actual Behavior
You should be observe search results still referring to documented-component page instead of techdocs-e2e-fixture

## Steps to Reproduce

1. Add link `[Link for e2e-fixture ](http://localhost:3000/docs/default/component/techdocs-e2e-fixture)` in plugins\techdocs-backend\examples\documented-component\docs\index.md file.
2. Now, go ahead and open tech docs of documented-component and search something in the page
3. Click the link add on step-1 and search for the content techdocs-e2e-fixture. You should be observe search results still referring to documented-component page.

P.S: Running techdocs locally

## Context
Search is showing wrong results
![image](https://user-images.githubusercontent.com/73854984/155408514-ad8c10ec-8c6a-4900-b73b-dcacfaab3d77.png)

## Your Environment
Locally

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by sbellam1187** [comment]
I believe, filter context is not updated navigating through the links. that's why we do see old search results. But I don't know how to resolve the issue.  

```export const TechDocsSearch = (props: TechDocsSearchProps) => {
  const initialState = {
    term: '',
    types: ['techdocs'],
    pageCursor: '',
    filters: props.entityId,
  };
  return (
    <SearchContextProvider initialState={initialState}>
      <TechDocsSearchBar {...props} />
    </SearchContextProvider>
  );
};
```

**Comment by iamEAP** [comment]
Thanks for reporting @sbellam1187.  Perhaps something like #9791 could help?
