### ISSUE TITLE
catalog-backend-module-msgraph: support advanced query capabilities

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#9795]
## Feature Suggestion

The Microsoft Graph API supports "advanced query/filter capabilities" which need to enabled.
https://docs.microsoft.com/en-us/graph/aad-advanced-queries

Some of the filter options are limited to the advanced filters.

## Possible Implementation

As described at https://docs.microsoft.com/en-us/graph/aad-advanced-queries
this feature requires to send the header `ConsistencyLevel: eventual` as well as
the query parameter `$count=true` to enable the advanced query mode.

The suggested solution would be to introduce a new property for the config
```
advanced: false | true
```
with default value `false`.

When enabled, the required header and query parameter will be added to the request.

`userFilter` and `groupFilter` could make use of the advanced filter options then.

## Context

Allow users of the msgraph plugin to use all the filter options available if they need them.

**Comment by freben** [comment]
Sounds great!

In general boolean parameters can be a bit opaque and hard to evolve. Maybe rather use something like `queryMode: 'basic' | 'advanced'`?

**Comment by freben** [comment]
On the other hand, no config is always best - is there some way of just plain detecting which query mode to use?

**Comment by pjungermann** [comment]
It seems like the use of `$search` requires `$count`, too, besides the header, but the docs are not consistent about it.

as of https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#request-headers
> eventual. This header and $count are required when using $search, or in specific usage of $filter. For more information about the use of ConsistencyLevel and $count, see [Advanced query capabilities on Azure AD directory objects](https://docs.microsoft.com/en-us/graph/aad-advanced-queries).

as well as https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#properties
> Specific usage of $filter and the $search query parameter is supported only when you use the ConsistencyLevel header set to eventual and $count.

it seems like it is needed.

However at https://docs.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http it sounds like it is not needed.
> However, these advanced query capabilities are not available by default but, the requestor must also set the ConsistencyLevel header to eventual and, with the exception of $search, use the $count query parameter. The ConsistencyLevel header and $count are referred to as advanced query parameters.

Also, the existing implementation by PR #9721 did not include it.

Therefore, I will assume it is not needed for `$search`.
