### ISSUE TITLE
catalog-backend-module-msgraph: support $select to control returned data for User and Group

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#9796]
## Feature Suggestion

The Microsoft Graph API supports "advanced query/filter capabilities" which need to enabled.
https://docs.microsoft.com/en-us/graph/aad-advanced-queries

By default, only a subset of the information about the entities will be returned.
This can be changed using the `$select` parameter.

We could make this configurable so that users of msgraph can control which data is returned.

## Possible Implementation

Requires #9795 and `advanced: true` configured.

Additionally, we can the introduce `userSelect` and `groupSelect` to the config
which would be send to the API as `$select` parameter.

## Context

Allow users of the msgraph plugin to fetch any information they need, e.g. for custom user or group transformations.

**Comment by benjdlambert** [comment]
@pjungermann is this something you still want? :pray:

**Comment by pjungermann** [comment]
I think it would be nice to support to make msgraph more feature complete. I can provide a PR, too. Just busy with a few other changes at the moment

**Comment by pjungermann** [comment]
I think it makes sense to wait for the config alignment PR #12196

**Comment by pjungermann** [comment]
remove stale

**Comment by pjungermann** [comment]
resolved by PR #13553
