### ISSUE TITLE
Customize the Settings page with additional tabs

### ISSUE THREAD

**Issue by yousifalraheem** [backstage/backstage#9805]
I would like to have the ability to customize the settings page to cater for as many tabs as needed.

## Feature Suggestion

In the `user-settings-plugin` there are 3 pre-configured and hard-coded tabs. However, in our implementation at Zalando, we require more settings to be implemented in there. There isn't a way to do that at the moment, but this can be achieved by allowing us to add more tabs.

## Possible Implementation

This is where the tabs are rendered
https://github.com/backstage/backstage/blob/master/plugins/user-settings/src/components/SettingsPage.tsx

We could add a prop to the `SettingsPage` component to insert additional tabs. I would like to make this contribution and hopefully use it as soon as possible to address one limitation we have at the moment.

**Comment by freben** [comment]
Alright.

This would probably fit as one of these "composability" things where the plugin exposes a wrapper component plus the ability for users to make extension components that end up being rendered as tabs. @Rugvip for visibility
