### ISSUE TITLE
catalog-backend-module-msgraph: undocumented config options

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#9819]
## Expected Behavior

Documentation for the config options

- userExpand
- userGroupMemberSearch
- groupSearch

exist at the documentation/README.md of the catalog-backend-module-msgraph plugin.

## Actual Behavior

All the mentioned config options are not part of the documentation, yet.

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 20.6.0 - darwin/x64
node: v16.3.0
yarn: 1.22.1
cli:  0.14.1 (local)

Dependencies:
  @backstage/catalog-model        0.11.0
  @backstage/core-plugin-api      0.6.1
  @backstage/plugin-catalog-react 0.6.15
```

**Comment by pjungermann** [comment]
- seems like `$search` (`userGroupMemberSearch`, `groupSearch`) required advanced query capabilities (not yet available, feature request at #9795)
- `$expand` (config option `userExpand`) is not available at advanced query mode
- there is no search option for user (`userSearch`)

see https://docs.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http

**Comment by freben** [comment]
Alright - will you be looking into adding these as appropriate?

**Comment by pjungermann** [comment]
seems like these config options were introduced recently as part of PR #9721

**Comment by pjungermann** [comment]
advanced query capabilities don't support `$expand` -- but instead of validating it while calling the API, we could just let it fail with the APIs error. Might be more sensible and forward compatible in case they add support in the future.

What do you think @freben ?

**Comment by pjungermann** [comment]
> Alright - will you be looking into adding these as appropriate?

Yes. Likely I will take care of it as part of #9795 -- or a separate PR depending on what makes sense.

**Comment by pjungermann** [comment]
I will support additional parameters at a separate PR and only take care of the docs.
