### ISSUE TITLE
Redis cache connection URL should require protocol prefix

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#9825]
## Feature Suggestion

The protocol prefix for Redis connection URLs should be allowed to be specified by the Backstage integrator. 

## Possible Implementation

Remove hardcoded `redis://` prefix from https://github.com/backstage/backstage/blob/3b7a11e9c8058bc2ad758ccc867279234c6bc409/packages/backend-common/src/cache/CacheManager.ts#L136
## Context

It is standard for connection URLs for different resources to also specify the appropriate protocol prefix (eg. `postgresql://...`). We deploy Backstage with a Heroku like platform which automatically sets env vars for attached resource URLs using their standard connection string formats which includes their appropriate protocol eg. `redis://...`. In order to support these type of use cases where we don't have full control of connection url format, we should assume the full URL is being supplied and not assume the protocol.

**Comment by kuangp** [comment]
cc: @magnusp (original author) and maintainers on your thoughts before I open PR with the requested change

**Comment by magnusp** [comment]
Yeah I had conflicting thoughts about the protocol bit. I decided on keeping it as host+port since that is how the memcache client is configured. By adding the protocol we could remove the 'type' property all together, specifying memcache as memcache://host:port.

**Comment by magnusp** [comment]
By keeping that field we do end up in a situation where the user could specifiy memcache as store but mistakenly uses an Redis connection URL. Which field has priority in deciding what is correct? I guess it is a validation error?

**Comment by freben** [comment]
Yep, validation error sounds right.
