### ISSUE TITLE
Add icons to Storybook

### ISSUE THREAD

**Issue by lukzerom** [backstage/backstage#9837]
We use several icons , i wanted to document them in storybook so i can later use this reference in core component documentation. 

## Feature Suggestion

Add icons to storybook

**Comment by lukzerom** [comment]
Can i take it ? 😅

**Comment by emmaindal** [comment]
Hi @lukzerom awesome to see this issue. Just to clarify - when you say `several icons`, are you referring to icons used from material-ui, or custom icons? Can you give me an example?

**Comment by Rugvip** [comment]
@lukzerom totally :grin:

+1 to what Emma is asking, this is about the system icons received from the app theme right? as in these: https://github.com/backstage/backstage/blob/5d342c71694ad9ee64f3fab7d8ebcfd52a408e27/packages/core-components/src/icons/icons.tsx#L36-L78

**Comment by lukzerom** [comment]
@emmaindal ,  @Rugvip  yes, exactly, icons that we wrap and document 🙂 
<img width="1091" alt="Zrzut ekranu 2022-03-4 o 14 09 49" src="https://user-images.githubusercontent.com/55348672/156769350-ec248dc4-6bea-4e01-ba7f-78b2dc0e5279.png">
