### ISSUE TITLE
DockerContainerRunner.runContainer does not remove container when execution ends

### ISSUE THREAD

**Issue by Fs00** [backstage/backstage#9850]
## Expected Behavior

There should be no leftover containers after `runContainer` terminates its execution.

## Actual Behavior

Stopped containers aren't removed and remain there until someone removes them manually.

## Steps to Reproduce

1. Create a component with a template that uses an action that runs a Docker container (such as [`fetch:rails`](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend-module-rails/README.md))
2. Observe in Docker Desktop (if you're on Mac/Windows) or with `docker ps -a` that the container(s) used by the template action is/are still there

## Context

We observed this behavior while developing a template action that runs some operations in a Docker container.
While it's true that leftover containers typically occupy a small amount of disk space, they can pile up as time passes and are just garbage/useless data.
We investigated a bit in the codebase and found out that the [Dockerode client accepts the `AutoRemove` option](https://github.com/apocas/dockerode#equivalent-of-docker-run-in-dockerode) which does exactly what we want here.

**Comment by Rugvip** [comment]
Yep, great suggestion, let's have this :grin:

Would appreciate and gladly accept help with this one in case anyone wants to pick it up 🙏
