### ISSUE TITLE
[Home] add homepage banner component

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#9874]
A Banner component that can be used on the homepage. 

## Feature Suggestion
<img width="1376" alt="Screenshot 2022-03-01 at 11 48 26" src="https://user-images.githubusercontent.com/25153114/156155471-3ba3c72d-570e-40aa-9ebf-384b29505675.png">

## Possible Implementation

The Banner should be able to accept the following props:

* startTime
* endTime 
* info
* action (e.g. close button can be passed in)
* image? (e.g. background of the banner)

Another option is to keep only `startTime`, `endTime` and `action` as properties on the Banner component, and let it accept a children too, which will include info and image components.

The component should just render if the current date is within start and endTime.

Future iteration could also cover (but can be left out as a start):

* Being able to limit the visibility of the Banner to a specific group of users. If the announcement should not be shared with everyone. 

Happy to hear other needs/thoughts!

**Comment by kissmikijr** [comment]
Good idea! One thing is could we make somehow that the content of the banner could be configureable without deploying a new version of the application? Maybe as a next step also.

My thought process is there is a platform team who manages the internal backstage, but probably there could be nice announcements that are not coming from the platform teams. 

One solution could be that this banner plugin would have a frontend "editor" and backend to save these stuff in the DB directly. So some people could edit it maybe with the permission system they could be restricted.
Other idea is to fetch a json from some 3rd party hosting maybe ?

what do you think?

**Comment by kissmikijr** [comment]
@emmaindal can you assign this to me please?

**Comment by emmaindal** [comment]
@kissmikijr absolutley, thanks for picking this issue up!

**Comment by camilaibs** [comment]
Another demand that I saw internally is the need to control the visibility of the banner in the user's settings in case he closes the banner and doesn't want to see the message again and track user actions such as CTA's clicks in analytics.

**Comment by kissmikijr** [comment]
I have somehting for this, somewhere, just got stuck on some styling i believe, I'll dig it out and finish it!

**Comment by sharadpattanshetti** [comment]
Interested...

**Comment by camilaibs** [comment]
> I have somehting for this, somewhere, just got stuck on some styling i believe, I'll dig it out and finish it!

Amazing, we are looking forward to your contribution 🙌🏻

**Comment by camilaibs** [comment]
Hey @kissmikijr, just checking if you're still excited to help us solve this issue, and would also like to say again that we're more than happy to have you as a contributor. Is there something blocking you that we can help you with?

**Comment by kissmikijr** [comment]
@camilaibs Thanks for checking in and sorry about the slowness of this, some things came up and it got de prioritized! I'd love to contribute this, though so may I ask a little bit more time ? I am planning to do this EOW.

**Comment by garyniemen** [comment]
Perhaps to review @emmaindal
