### ISSUE TITLE
Incl. Authorization Token to New Relic Dashboard  Plugin

### ISSUE THREAD

**Issue by skgandikota** [backstage/backstage#9889]
[Plugin] New Relic Dashboards #7849  idea is fantastic, I have implemented in our lower environment and loved the feature but plugin is not sending any authorization token from the front end to backend. 

## Feature Suggestion

Include User Authorization token to New Relic Dashboards Plugin 

## Possible Implementation

Append myHeaders const with Authorization Token [at line 44 ](https://github.com/backstage/backstage/blob/da0675bf9f28ed1460f03635a22d3c26abd14707/plugins/newrelic-dashboard/src/api/NewRelicDashboardClient.ts#L44)   from IdentityApi

## Context

Authorising the new relic proxy call

**Comment by Rugvip** [comment]
Yep, makes sense! Is this something you would like to contribute?

**Comment by skgandikota** [comment]
yes !

**Comment by freben** [comment]
Might I suggest injecting and using the `fetchApi` instead (through `fetchApiRef`)? Example: https://github.com/backstage/backstage/blob/2c6eab72b74d196a9db46539bfc3f3db2585345b/packages/catalog-client/src/CatalogClient.ts#L213

It allows users to add global behaviors such as tracking / metrics, auth etc - and adding the user's Backstage token is one of those out-of-the-box behaviors.

**Comment by freben** [comment]
(feel free to make a pull request - easier to discuss on one of those)

**Comment by skgandikota** [comment]
@freben   Thanks for replying - I have raised the pull request : https://github.com/backstage/backstage/pull/10754 will soon update the fetchApi to fetchApiRef in the same pull request

**Comment by skgandikota** [comment]
New PR :  https://github.com/backstage/backstage/pull/10859
