### ISSUE TITLE
Contribute support for Gerrit

### ISSUE THREAD

**Issue by anicke** [backstage/backstage#9896]
## Feature Suggestion

Gerrit is an open source code collaboration tool (typically self hosted). We want to contribute code to add support for reading entities from Gerrit.

## Possible Implementation

Initally we would contribute the following:

- [x] A Gerrit Integration #10038
- [x]  "GerritUrlReader" that implements "readUrl" #10263
- [x] Implement "readTree".
- [x] A Gerrit EntityProvider that imporst entities from a set of repos.

**Comment by pjungermann** [comment]
FYI: #10183 - maybe you want to consider this right from the start for the discovery here.

**Comment by anicke** [comment]
> FYI: #10183 - maybe you want to consider this right from the start for the discovery here.

Thanks! You saved me some effort. I have already written a gerrit discovery (of the old "built in" type) and just started porting it to a "discovery plugin". I'll create a EntityProvider instead.

**Comment by jhaals** [comment]
Great job implementing this @anicke! Can this meta issue be closed?

**Comment by anicke** [comment]
Thanks! Yes, let's close this!
