### ISSUE TITLE
Pagination for catalog entities

### ISSUE THREAD

**Issue by nodify-at** [backstage/backstage#9905]
Backstage catalog api provides an endpoint to read all entities using some filters and additional parameters to restrict the response using limit and offset.

But we can not use as it is now, because we don't know how many elements can we get, after applying the filters. Using an offset and limit without this information is not possible.

## Feature Suggestion

It fill the basic requirement of a pagination but we need to improve the response to get one of:

* Total count of elements, after applying the filters so the caller can calculate the count of total pages 
**or**
* Return the page info defined in catalog-backend, but this can be only useful with a load more function. Returning a total count of elements would be better for the clients to build the pagination.

```ts
export type PageInfo =
  | {
      hasNextPage: false;
    }
  | {
      hasNextPage: true;
      endCursor: string;
    };
```

## Possible Implementation

- /entities endpoint must be improved
- DefaultEntitiesCatalog must be improved to return the total count of elements
- AuthorizedEntitiesCatalog might be improved?

Next steps:
- Catalog Index Page can be improved to use a pagination via REST API instead of doing this in client side. 

## Context

- UI/UX Improvements

See:
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/DefaultEntitiesCatalog.ts#L228
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/createRouter.ts#L119
https://github.com/backstage/backstage/blob/master/packages/catalog-client/src/CatalogClient.ts#L170

**Comment by Rugvip** [comment]
The entities endpoint is in a bit of a weird state in that it supports pagination, but returns it in a bit of an awkward way. We really want to move it over to the response body, but want to be a little bit careful in doing so to make sure we don't cause trouble when permissions are enabled. The CatalogClient ofc also needs to be forwarding this information in the response.

I think it's best that we stick to the existing issue over [here](https://github.com/backstage/backstage/issues/5921) though, as I think it covers the same area and we'd rather focus the discussion. Will close this one as a duplicate and link back from the other discussion
