### ISSUE TITLE
Migrate to react-router v6 stable

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#9913]
## Feature Suggestion

Migrate to [react-router v6](https://reactrouter.com/) stable. We're currently on `6.0.0-beta.0` and should migrate to the stable release.

## Possible Implementation

TBD, created this issue to track progress

**Comment by snehaljos** [comment]
Hi @Rugvip can I give it a try?

**Comment by Rugvip** [comment]
@snehaljos sure! Bit of a heads up that here be dragons, since we need to make sure that migration of existing projects is smooth. That said it would be valuable to just get the work of having this repo migrated done, it would take us a long way.

**Comment by testn** [comment]
I tried to do that in https://github.com/backstage/backstage/pull/10126

**Comment by Rugvip** [comment]
Done in #10450 🎉
