### ISSUE TITLE
[RFC] split bitbucket support into separate support for Bitbucket Cloud and Bitbucket Server

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#9923]
**Status:** Open for comments

## Need

Bitbucket Cloud and Bitbucket Server are different yet similar products which -- unfortunately -- just have similar names. The names suggest that one is on-premise and the other one the cloud/managed solution of the same product -- but that is not the case. Actually, there is Bitbucket Data Center as a hosted version of Bitbucket Server to make it more confusing.

Bitbucket Server was formally known as Stash. In 2015, Atlassian decided to rebrand it (https://confluence.atlassian.com/bitbucketserver/bitbucket-rebrand-faq-779298912.html), renaming
- Stash -> Bitbucket Server (since version 4.0)
- Stash Data Center -> Bitbucket Data Center
- Bitbucket -> Bitbucket Cloud

[Features at Bitbucket Server (or Data Center) as well as Bitbucket Cloud are not the same](https://confluence.atlassian.com/bitbucketserver/bitbucket-rebrand-faq-779298912.html#BitbucketrebrandFAQ-Whyaren'ttheServerandCloudfeaturesthesame?). These differences are also reflected with the codebase of Backstage and the documentation. Parts of the documentation might be confusing - which could be addressed individually, though.
Both products got closer feature-wise, but they still different.

- Bitbucket Cloud and Bitbucket Server have different APIs we can utilize. At `plugins/catalog-backend/src/modules/bitbucket/lib/client.ts`, all used endpoints are mixed within the same client implementation.
- The auth for those APIs is different, too.
- Even code line references are different for both products.
- At the Backstage codebase, you can find quite a few `isBitbucketCloud` checks.

Additionally, Bitbucket Server exists with many versions which could be used by the different users of Backstage while Bitbucket Cloud will always be the same for all.

Overall, maintenance and changes are harder when both are entangled. Contributors and maintainers need to figure out whether this impacts only one or both. And testing is harder if you want to contribute something for one of them, but then you might need to try it out with both even though you only use/have one of them.

At some features, we explicitly need to mention that this is "cloud only" like at https://backstage.io/docs/auth/bitbucket/provider.

## Proposal

I want to propose to split the support for Bitbucket into separate support for Bitbucket Cloud and Bitbucket Server. Explicit usage of these will make it clearer what you are using, developing for, etc. Supported features for Backstage users will be much clearer, too.

This may a certain level of duplication, but this duplication is very likely just on the same level as "bitbucket" vs "github". Also, there is less coupling if we don't but them together. And if it makes sense to keep some shared code, this could be extracted still.

Affected:

- packages/integration
- catalog-backend (discovery processor)
- scaffolder-backend (publish:bitbucket action)
- bitbucket auth provider (already Bitbucket Cloud only; potentially a "rename only" change)

## Risks

This change would be a breaking change. Users of "bitbucket"-related features would need to migrate. The change is likely to be subtle change like changing `bitbucket` to `bitbucketCloud`, etc. at the `app-config.yaml`.

Also, this change is impacting the support for Bitbucket Cloud as well as Bitbucket Server. Having (test/review) support by users of either products would be of great help to ensure everything is still operational as desired.
As this split would not intent to modify and behavior and is rather a refactoring and cleanup tasks, the risk shouldn't be very high though.

**Comment by dhruvaldarji** [comment]
As a Bitbucket user and as someone who has had to raise changes to the Bitbucket integration to support my company's implementation of the Bitbucket Server, I completely agree with the proposal here. 

There is a certain level of duplication that exists in each of the Bitbucket related files. It almost doesn't make sense to have it together when there is a fairly clear delineation between the two servers. 

One thing to consider is that the integration often bleeds into other plugins. For example, the TechDocs plugin often has issues sending requests to Bitbucket depending on the configuration. Modifications may be needed in some plugins to abstract out the integration logic for integrating with various git servers.

**Comment by pjungermann** [comment]
I think what you refer to at the end of your comment relates to his PR #9095 . Not sure whether this makes a big difference for the concern here as this is more around how the Git URL itself gets parsed.

**Comment by renlord** [comment]
To chime into this discussion, in Cloudflare we also use bitbucket server with cloudflare access gateway sitting infront as authentication proxy infront of bitbucket. This requires injecting custom authentication headers to be used by our access gateway.

See https://github.com/backstage/backstage/pull/11335 and https://github.com/backstage/backstage/issues/11233

**Comment by pjungermann** [comment]
FYI: https://bitbucket.org/blog/bitbucket-cloud-migration-qa

> With support for Atlassian Server products ending in February 2024, many of you are likely evaluating or planning your migration to Bitbucket Cloud. [...]

**Comment by Rugvip** [comment]
@pjungermann thank you for pointing that out! I'm assuming that applies to both way to use Bitbucket Server right? as in Bitbucket Data Center as well? Couldn't find that explicitly stated.

So what this means for us I would assume is a long-term plan to remove the Bitbucket Server integration and make Bitbucket Cloud the only one. So one point being very little push to implement new features or integrations for Bitbucket Server.

Brings up the naming question again :grin:. At this point it really does seem to make more sense to have `bitbucket` (cloud) + `bitbucketServer` as the two integration keys, so perhaps we can work towards that by completing the deprecation of the existing `bitbucket` integrations to free up that name?

**Comment by pjungermann** [comment]
@Rugvip yes, agree to all of that. Also thought about reclaiming "bitbucket" then for Bitbucket Cloud eventually.

Even though Atlassian stops support for Bitbucket Server in Feb 2024, some orgs might still use it longer.

Re Bitbucket Data Center, I didn't find any specific info either. At the end, it is the hosted version of Bitbucket Server. Therefore, I assume it is included.

Overall, Atlassian is pushing for the cloud options for all their products.

**Comment by dhruvaldarji** [comment]
Atlassian may be planning to drop support for Bitbucket Server, but my company legally can't use their cloud products to store source code of any kind due to specifics defined in our contracts. This may change in the future but it is unlikely to change quickly. In fact, we used to be on GitHub (the good ol' days) until contracts forced us to migrate to a self-hosted Bitbucket Server. 

Explaining just for context.

**Comment by pjungermann** [comment]
As there is a separate replacement for both, I will close this issue. The legacy implementation will be removed at some point in the future.
