### ISSUE TITLE
[RFC] Usage of (Stacked or Grid of) Cards instead of a table for the Catalog page.

### ISSUE THREAD

**Issue by oparaskos** [backstage/backstage#9947]
**Status:** Open for comments

## Need

At present the catalog table looks something like this
![image](https://user-images.githubusercontent.com/8076088/156571302-b51f7321-d2df-4d60-920e-b9952a1d1c1e.png)

The issue I have with this design is mainly that the description field is cut off after only one or two words, which renders it pretty useless. In addition at smaller screen sizes the other columns are cut off until you scroll horizontally.

## Proposal

I propose that a grid of [cards](https://m3.material.io/components/cards/guidelines) would be a more suitable pattern to use instead of a table. On smaller screens such as mobile devices the cards can collapse into a list, whereas on larger screens the horizontal space can be filled.

Additionally many components may be represented pictorially and a card gives a nice space to put icons or cover art.

### Examples of a design for similar applications:
**DockerHub** displays search results in a list of vertically stacked cards, where name and description take prominence next to an icon. tags and other tangential information is displayed around the borders of the card.
![DockerHub](https://user-images.githubusercontent.com/8076088/156573143-257b0e17-7bfa-416e-9d88-9691098b9e3c.png)

**ArtifactHub** does something very similar to DockerHub but as a grid with two columns:
![ArtifactHub](https://user-images.githubusercontent.com/8076088/156573660-6fc5aeb3-dbed-421b-82dc-6df05a5ae6c0.png)

**GitHub** does something similar to cards, by displaying search results in a list rather than in a table they can achieve a high information density, though at the expense of aesthetics.
![GitHub](https://user-images.githubusercontent.com/8076088/156573916-a85a7f9f-54b4-4d9a-b859-72a12a46bb69.png)

## Alternatives

Alternatively a more simple(?) solution may be to make the columns on the existing resizable (or resize to best fit their content)

## Risks

When sorting the table, in a card grid view it may not be _as_ obvious the order in which the items are sorted.

**Comment by freben** [comment]
I'd also like to suggest that maybe description should not be among the default columns, at all. It is more of a nuisance than a help, in my opinion :)

You can also remove that column yourself, by passing the `columns` prop to the catalog components, as touched upon in the examples here https://backstage.io/docs/features/software-catalog/catalog-customization

**Comment by kuangp** [comment]
I would also throw in that for us, we customized our table by specifying a smaller subset of columns using the method freben mentioned above and also adjusted the width of each column to allow the description column to take up more real estate

**Comment by freben** [comment]
Looping back on this - I'd love to see this personally, but it should probably be an option to toggle at the top, like

<img width="423" alt="Screen Shot 2022-03-09 at 12 04 09" src="https://user-images.githubusercontent.com/3097461/157429279-9825c431-25e0-49ec-ad14-2138b9268003.png">

that kind of group but with icons, so you can pick between the classic table and the larger view

**Comment by benjdlambert** [comment]
@oparaskos would you be up for maybe tidying up the implementation a little bit and have the toggle so that we can get this in an iterate on it? Looks like a great start so far!

**Comment by pallavipervaje** [comment]
> https://backstage.io/docs/features/software-catalog/catalog-customization



> I would also throw in that for us, we customized our table by specifying a smaller subset of columns using the method freben mentioned above and also adjusted the width of each column to allow the description column to take up more real estate in addition to increasing the char limit before truncating

@freben @kuangp @benjdlambert How can I increase each column width?

**Comment by freben** [comment]
Column definitions have a `width` field that's a string (so you can set it to any regular CSS value such as "10%" or "5em" etc)

**Comment by jgrumboe** [comment]
@oparaskos, what happened to this issue and your PR?
Just saw it and thought that would be a really great addition to the catalog view.

**Comment by ChristopheLBP** [comment]
Great job!
