### ISSUE TITLE
Failures in TechDocs builds showing in ui but show up successfully if the user comes back to the page later

### ISSUE THREAD

**Issue by adrianke77** [backstage/backstage#9971]
## Expected Behavior

When the TechDocs build takes longer than the allowed timeout for the HTTP request, A notification in ui along the lines of 'Build is taking longer than expected, please come back later' should be shown instead of displaying an error in build.

## Actual Behavior

When the Techdocs build takes longer than the allowed timeout for the HTTP request, it displays an error in the UI

## Steps to Reproduce

Run a TechDocs build while temporarily changing code in Techdocs backend to immediately return a timeout error, to simulate the HTTP request timing out before the build is done.

## Context

We have users that interpret the error as requiring them to review how their TechDocs is set up, instead of simply needing to wait a while more.

**Comment by garyniemen** [comment]
@adrianke77 do you still see this as a problem?
