### ISSUE TITLE
[TechDocs] Docker build fails on k8s

### ISSUE THREAD

**Issue by cmoulliard** [backstage/backstage#9983]
## Issue

Here is the error reported by backstage using TAP-GUI - https://docs.vmware.com/en/Tanzu-Application-Platform/1.0/tap/GUID-tap-gui-about.html

```
2022-03-03T14:32:58.733Z techdocs error Failed to build the docs page: Failed to generate docs from ${inputDir} into ${outputDir}; caused by Error: This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with; caused by Error: connect ENOENT /var/run/docker.sock Failed to generate docs from ${inputDir} into ${outputDir}; caused by Error: This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with; caused by Error: connect ENOENT /var/run/docker.sock type=plugin name=Error cause=Error: This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with; caused by Error: connect ENOENT /var/run/docker.sock stack=Error: Failed to generate docs from ${inputDir} into ${outputDir}; caused by Error: This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with; caused by Error: connect ENOENT /var/run/docker.sock
    at _TechdocsGenerator.run (/app/node_modules/@backstage/techdocs-common/dist/index.cjs.js:312:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DocsBuilder.build (/app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:136:5)
    at async DocsSynchronizer.doSync (/app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:214:23)
    at async /app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:305:7
```

The user will see using the UI the following error message

![Screenshot 2022-03-03 at 16 53 44](https://user-images.githubusercontent.com/463790/156601447-ed8aac27-e3cf-45a0-b190-c7c71458bfba.png)

**Comment by adamo57** [comment]
Do you have Docker running on your machine? Is this happening in a Docker container? If you are running Backstage in a docker container, you can set the `techdocs.runIn` in your `app-config.yaml` to `local` and see if that helps.

**Comment by cmoulliard** [comment]
> Do you have Docker running on your machine?

Yes

**Comment by cmoulliard** [comment]
> Is this happening in a Docker container?

No as the container is launched using kubernetes's pod

**Comment by garyniemen** [comment]
@cmoulliard did you manage to get unstuck with this?

**Comment by james-wilson-kidsloop** [comment]
I have Backstage installed on K3D and hitting the exact same thing. I tried a couple of the docker in docker solutions here: 
https://medium.com/hootsuite-engineering/building-docker-images-inside-kubernetes-42c6af855f25

It got me further but the next error was:
> techdocs error Unable to read techdocs_metadata.json at /app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/backstage-generated-docs-repo/techdocs_metadata.json. Error: Error: ENOENT: no such file or directory

Which is my reward for blindly hacking. It would be great if someone that knew what they were doing could point me in the right direction :)

**Comment by jamesw201** [comment]
I have Backstage installed on K3D and hitting the exact same thing. I tried a couple of the docker in docker solutions here:
https://medium.com/hootsuite-engineering/building-docker-images-inside-kubernetes-42c6af855f25

It got me further but the next error was:

> techdocs error Unable to read techdocs_metadata.json at /app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/backstage-generated-docs-repo/techdocs_metadata.json. Error: Error: ENOENT: no such file or directory

Which is my reward for blindly hacking. It would be great if someone that knew what they were doing could point me in the right direction :)

**Comment by garyniemen** [comment]
@camilaibs can you shed any light here?

**Comment by dweber019** [comment]
We are running Backstage on OpenShift successfully with a base image like
```
FROM docker.io/node:16-buster
RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y python3-pip \
 && apt-get install -y gcc musl-dev openjdk-11-jdk curl graphviz fonts-dejavu fontconfig \
 && rm -rf /var/lib/apt/lists/*
# Download plantuml file, Validate checksum & Move plantuml file
RUN curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.12.jar/download && echo "a3d10c17ab1158843a7a7120dd064ba2eda4363f  plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar
RUN pip3 install --upgrade pip && pip install mkdocs-techdocs-core==1.0.2
# Create script to call plantuml.jar from a location in path
#   When adding TechDocs to the Backstage Backend container, avoid this
#   error (OSError: [Errno 8] Exec format error: 'plantuml') by using the
#   following RUN command instead:
RUN echo '#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
# RUN echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml
```

And then the multi-stage build from https://backstage.io/docs/deployment/docker#multi-stage-build using the above base image.

Additionally this maybe helps https://discord.com/channels/687207715902193673/924606903122792469/929057374369628161.

**Comment by james-wilson-kidsloop** [comment]
Amazing, thank you. I'll try this out and report back!

**Comment by jamesw201** [comment]
Amazing, thank you. I'll try it out and report back

**Comment by cmoulliard** [comment]
> We are running Backstage on OpenShift successfully with a base image like

What you propose as CI/CD build to generate the documentation is different from the error I reported as this concerns the `online doc` generation which is failing on k8s

**Comment by cmoulliard** [comment]
FYI: Here is a nice trick https://www.vrabbi.cloud/post/tap-gui-techdocs-auto-rendering. Be aware that you can still get the docker error limit too :-( `│ time="2022-06-03T15:16:12.503806228Z" level=error msg="Handler for POST /images/create returned error: toomanyrequests: You have reached your pull rate limit. You m │
│ ay increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"`

**Comment by cmoulliard** [comment]
> I did the change you proposed
> 
> ```
> techdocs:
>   generator:
>     runIn: local
> ...
> ```

I did another test using the TAP Gui baskstage project and I got now
```
Build log error

info: Set {"edit_uri":"https://github.com/halkyonio/tap-catalog-blank/edit/main/domains/docs"}. You can disable this feature by manually setting 'repo_url' or 'edit_uri' according to the MkDocs documentation at https://www.mkdocs.org/user-guide/configuration/#repo_url {"timestamp":"2022-06-03T15:45:56.635Z"}
error: Failed to build the docs page: Failed to generate docs from ${inputDir} into ${outputDir}; caused by Error: spawn mkdocs ENOENT {"timestamp":"2022-06-03T15:45:56.672Z"}  
```

**Comment by hqr123** [comment]
why ?   Building a newer version of this documentation failed. Error: "Failed to generate docs from /var/folders/m0/ydxv6ks52xzcdwdkn9r7qn0c0000gn/T/backstage-mnhFbj into /private/var/folders/m0/ydxv6ks52xzcdwdkn9r7qn0c0000gn/T/techdocs-tmp-4QvtGq; caused by Error: This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with; caused by Error: connect ENOENT /var/run/docker.sock"

**Comment by tudi2d** [comment]
@hqr123 make sure you have Docke running locally, login using `docker login` & make sure the image was loaded (otherwise you might have to manually trigger it with `docker pull spotify/techdocs`

**Comment by omar-triguii** [comment]
> > If you are running Backstage in a docker container, you can set the `techdocs.runIn` in your `app-config.yaml` to `local` and see if that helps.
> 
> I did the change you proposed
> 
> ```
> techdocs:
>   generator:
>     runIn: local
> ...
> ```
> 
> on k8s but still got the same error

any updates?
